### ISSUE TITLE
Failure to run perception module following 'official' procedure

### ISSUE THREAD

**Issue by Autofoxsys** [ApolloAuto/apollo#10009]
I have followed the instructions to run the perception module standalone as [described here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.mdl):
The process fails as described below.

**To Reproduce**
1. Start with a clean install of 18.04 LTS on x86 system with Nvidia 1050 GPU
2. Install all drivers (Nvidia drivers v430), tools, SDK (Cuda), etc.
3. Follow the official guide to build Apollo.
4. Attempt to verify the build by running the demo as described at the end of the [guide here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_launch_Apollo.md).  I could see a little car advancing on the screen but no lanes or obstacles.  I assumed that the perception module was not working and tried to run it standalone following [this guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.mdl).  This didn't work either.

**Expected behavior**
I could not select any vehicle in Dreamview.  There is only Mkz_Example.  Furthermore, the guide mentions a "Transform" button in Dreamview - I see no such button.  I thus typed the following into the console (as described in the guide): `cyber_launch start /apollo/modules/transform/launch/static_transform.launch`.  Please see the progression of screenshots.

**Screenshots**
![Screenshot from 2019-10-24 16-19-30-clip](https://user-images.githubusercontent.com/39223300/67500136-8e97b880-f682-11e9-8b97-6e91762217de.png)
![Screenshot from 2019-10-24 16-23-04](https://user-images.githubusercontent.com/39223300/67500145-922b3f80-f682-11e9-8368-956a1a8af1ba.png)
![Screenshot from 2019-10-24 16-25-27](https://user-images.githubusercontent.com/39223300/67500154-96575d00-f682-11e9-8e3d-4e6f6dfa186e.png)

![Screenshot from 2019-10-24 16-29-13](https://user-images.githubusercontent.com/39223300/67500176-9c4d3e00-f682-11e9-800b-152bce0445f6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS 64-bit
 - Browser: Chome

![Screenshot from 2019-10-24 17-22-51](https://user-images.githubusercontent.com/39223300/67500441-f4844000-f682-11e9-83d9-a0ae3c9afe7f.png)

Any help would be greatly appreciated :-)

**Comment by Autofoxsys** [comment]
As there has been no response to my request after a couple of days I decided to start again, following the Apollo install guide, as any newcomer would.
For reference, I followed the steps outlined here: https://github.com/ApolloAuto/apollo#installation

In a new empty folder:
```
 git clone https://github.com/Autofoxsys/apollo.git
 cd apollo
 bash docker/scripts/dev_start.sh
 bash docker/scripts/dev_into.sh
 bash apollo.sh build
 bash scripts/bootstrap.sh
 cyber_recorder play -f docs/demo_guide/demo_3.5.record -l
```
All was fine up to the last command, when this happens... (can't find file)

![image](https://user-images.githubusercontent.com/39223300/67772947-36363180-fa5b-11e9-8008-247e5019130e.png)

.. because in my clean install - no such file exists.  There is a python script in this folder that will get the missing file.  So, the necessary additional step is:

`cd docs/demo_guide/
python rosbag_helper.py demo_3.5.record
cd ../../`

Now launching..
` cyber_recorder play -f docs/demo_guide/demo_3.5.record -l`

...starts pushing data to Dreamview, BUT - there are still no vehicles in dropdown list other than "Mkz Example" (whatever that is) and the Console output in Dreamview outputs the following message multiple times:

> You haven't selected a vehicle yet!

Surely, someone has come across this already?

**Comment by unacao** [comment]
You can select the "Mkz Example" vehicle and it will help copy the corresponding calibration parameters in the background. However playing the record does not need perception module to work. If you play it via cyber_recorder, and open dreamview, you should see the ego car moving along the planning trajectory with a few obstacles along the road. That is purely visualization and nothing to do with running any perception module.

**Comment by vlin17** [comment]
Hi @Autofoxsys , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
