### ISSUE TITLE
Can't successfully install Nvidia RTX 2080Ti driver on apollo kernel 

### ISSUE THREAD

**Issue by shutom001** [ApolloAuto/apollo#10001]
Hi,
    
I got a problem when installing Nvidia 2080ti driver on apollo kernel. Hope you guys can help me.
    
I can successfully install Nvidia 1080 Gpu Driver on ubuntu 14.04 and 18.04 with **apollo kernel.**
But with the same steps, it didn't work for **2080ti on apollo kernel.**
**and also I can successfully install RTX 2080ti driver on ubuntu standard kernel (**without apollo kernel).****

so I guess that maybe there are some conflicts between 2080ti driver( nvidia driver version >410) and apollo kernel. or maybe your team still don't support Nvidia 2080Ti.

### System information
os: ubuntu18.04
kernel:  4.4.32-apollo-2-RT(1.5.5)
Nvidia GPU: RTX 2080Ti
apollo: 5.0

### Steps to reproduce the issue:
I used the install option of "--no-kernel-module" to install 2080Ti driver on apollo kernel.
**Install commands :** 
$ sudo service lightdm stop
$ sudo ./NVIDIA-Linux-x86_64-430.14.run --no-x-check -a -s --no-kernel-module --no-opengl-files
$ sudo service lightdm start
$ nvidia-smi
**After the command of "nvidia-smi" then it print:** 
" NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

So nvidia 2080ti driver install failed on apollo kernel.
**But with the same steps, for 1080 driver on apollo kernel, After the command of "nvidia-smi" , it can successfully print the driver information. That's the point that confused me.**

Maybe there are some additional patch for 2080ti driver that are not public on this git hub.
looking forward to your reply !
Thank you very much !

**Comment by shutom001** [comment]
Thank you for your update!
https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/Install_nvidia_driver_on_ubuntu_18.04.md

**Comment by khsrhhh** [comment]
Did you success to install nvidia-430 driver on the 4.4.32-RT kernel version with referred that URL?

**Comment by khsrhhh** [comment]
> Thank you for your update!
> https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/Install_nvidia_driver_on_ubuntu_18.04.md

Did you success to install nvidia-430 driver on the 4.4.32-RT kernel version with referred that URL?
