### ISSUE TITLE
Any reference papers or  documents for piecewise_jerk_path_optimizer and piecewise_jerk_speed_optimizer?

### ISSUE THREAD

**Issue by lucianzhong** [ApolloAuto/apollo#10019]
Any reference papers or  documents for piecewise_jerk_path_optimizer and piecewise_jerk_speed_optimizer?

**Comment by lucianzhong** [comment]
@ jmtao @yifeijiang @natashadsouza

**Comment by jmtao** [comment]
@lucianzhong I searched and unable to find anything on internet.  There's a technical post from us: 
https://mp.weixin.qq.com/s/ao5hC_3A7fn8_L_PFw399A
You can find how we piecewise jerk algorithm there. 

thanks for supporting Apollo!

**Comment by lucianzhong** [comment]
@jmtao  Thanks a lot. 非常感谢
