### ISSUE TITLE
How to communicate selective channels if I am running cyber in two devices

### ISSUE THREAD

**Issue by lorugant123** [ApolloAuto/apollo#10020]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hi all, I have a question whether apollo has any feature where, cyber channels publishing in two different devices and would like to send only selective channel from one device to another. Thanks!

**Comment by r-ai-matt** [comment]
Is there a way to force a component to only use shm (for in this case the camera  driver) as opposed to sending over RTPS which is flooding the network between machines? While still allowing other messages to flow between nodes on different hosts?

**Comment by ctwfei** [comment]
> Is there a way to force a component to only use shm (for in this case the camera driver) as opposed to sending over RTPS which is flooding the network between machines? While still allowing other messages to flow between nodes on different hosts?

@r-ai-matt  By default, we only use rtps when transmitting messages across machines and  use shared pointer for in-process transfers. You can change the default transfer mode by modifying [cyber.pb.conf](https://github.com/ApolloAuto/apollo/blob/master/cyber/conf/cyber.pb.conf#L18-L22).

**Comment by ctwfei** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
> * **Apollo installed from (source or binary)**:
> * **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
> 
> ### Steps to reproduce the issue:
> * **Please use bullet points and include as much details as possible**:
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):
> Hi all, I have a question whether apollo has any feature where, cyber channels publishing in two different devices and would like to send only selective channel from one device to another. Thanks!

Hi @lorugant123  Sorry for the delay, apollo does not currently support the policy.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
