### ISSUE TITLE
[Mac Docker] localhost:8887 only available within docker not native host

### ISSUE THREAD

**Issue by dr-lab** [ApolloAuto/apollo#1002]
I following steps bellow, and all success

bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash scripts/hmi.sh

The last him.sh is run within docker or out side of docker? 

I can access localhost:8887 with curl within docker console:

```
curl http://localhost:8887
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/static/images/favicon.ico">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
```

But cannot access from host machine.  

```
curl localhost:8887
curl: (7) Failed to connect to localhost port 8887: Connection refused
```

From the him.sh, which calls modules/hmi/web/hmi_main.py, seems there is no docker port mapping there.

I am wondering where the docker "-P" port mapping been specified?  
bash scripts/hmi.sh

Per tutorial, seems it needs to be run after dev_into.sh which means under docker console.

Any one can help do a clarification?

**Comment by dr-lab** [comment]
read the post here:
https://github.com/ApolloAuto/apollo/issues/846

try to use http://<local IP address>:8887

Still not work.

Maybe there is no action, data/log/hmi.out is empty.

**Comment by dr-lab** [comment]
check the docker start command
`bash docker/scripts/dev_start.sh`

Seems no -p (port mapping) specified, is this intentionally or I miss some?


```
 docker run -it \
        -d \
        --privileged \
        --name apollo_dev \
        -e DISPLAY=$display \
        -e DOCKER_USER=$USER \
        -e USER=$USER \
        -e DOCKER_USER_ID=$USER_ID \
        -e DOCKER_GRP=$GRP \
        -e DOCKER_GRP_ID=$GRP_ID \
        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
        -v $APOLLO_ROOT_DIR:/apollo \
        -v /media:/media \
        -v $HOME/.cache:${DOCKER_HOME}/.cache \
        -v /etc/localtime:/etc/localtime:ro \
        --net host \
        -w /apollo \
        ${devices} \
        --add-host in_dev_docker:127.0.0.1 \
        --add-host ${LOCAL_HOST}:127.0.0.1 \
        --hostname in_dev_docker \
        --shm-size 512M \
        $IMG \
        /bin/bash
```

**Comment by xiaoxq** [comment]
Before running HMI, you need to build the system within the docker container: `bash apollo.sh build`

For the port setting, it's defined in the config proto which is 8887 by default:
https://github.com/ApolloAuto/apollo/blob/master/modules/hmi/proto/config.proto#L28

**Comment by dr-lab** [comment]
Sorry I forgot to mention that I already did the build and success before I run the him.sh.

8887 port defined bellow seems are within docker, sorry I may lack some necessary knowledge here, is the config.proto been used for docker port forwarding?

https://github.com/ApolloAuto/apollo/blob/master/modules/hmi/proto/config.proto#L28

```
/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1004 targets (12 packages loaded).
INFO: Found 1004 targets...
INFO: Elapsed time: 1395.916s, Critical Path: 113.59s
INFO: Build completed successfully, 2192 total actions

[ OK ] Build passed!
[INFO] Took 1420 seconds
```

**Comment by dr-lab** [comment]
never mind, I believe it is my local docker Ip router setup issue, since I cannot ping apollo_host_ip from native host.

I am working on Mac with default docker setup (of the latest stable docker CE).

Will update here after resolved.

**Comment by xiaoxq** [comment]
The config.proto just defines the config for HMI. The *port* value is used here:
https://github.com/ApolloAuto/apollo/blob/master/modules/hmi/web/hmi_main.py#L56

Good luck!

**Comment by dr-lab** [comment]
Hi @xiaoxq ,
Thanks for the link, seems I got the root cause. Mac does not support --net host mode.
https://docs.docker.com/docker-for-mac/networking/


So replace 
`--net host \`

with bellow, both 8887 and 8888 works.
`-p 8887:8887 -p 8888:8888 \`

Then in your native host, use your local host domain or local host IP address, 

http://localhost:8887
http://localhost:8888

If needed, I can do little more tests and create a PR.

**Comment by xiaoxq** [comment]
Thank you for figuring it out!

Currently working on Mac is not well tested. And for now '--net host' does make life easier, because you could change ports simply by editing config file or passing gflag, while not editing the docker container booting script.
Linux is always recommended if you can get one :)

**Comment by dr-lab** [comment]
hi @xiaoxq ,
Yes, you may right, Linux is the recommended. I will close this question.
