### ISSUE TITLE
Perception crashes without nvidia driver

### ISSUE THREAD

**Issue by davidadley** [ApolloAuto/apollo#10059]
Latest master branch.

**Describe the bug**
If perception is run from dreamview without the nvidia drivers installed it will crash after searching for `libcuda`. 

**To Reproduce**

1) Compile on a computer without nvidia drivers.
2) Try to run perception module in dreamview

**Workaround**
If you replace 
```
--cxxopt=-DCPU_ONLY
```
 with 
```
--define USE_GPU=false --cxxopt=-DCPU_ONLY --cxxopt=-DPERCEPTION_CPU_ONLY
```
everywhere in `apollo.sh`, it works as perception module doesn't appear to compile properly without the  `PERCEPTION_CPU_ONLY` compiler option.

**Comment by daohu527** [comment]
Yes, perception will need GPU, and don't support cpu only mode.
