### ISSUE TITLE
Apollo 5.0 build failed. libcuda.so.1 not found

### ISSUE THREAD

**Issue by YikeWang1103** [ApolloAuto/apollo#10055]
hi guys,

I am trying to build apollo 5.0 and I got this error. Can anybody help with that? Thanks in advance!

![image](https://user-images.githubusercontent.com/7753150/67822289-df803480-fafa-11e9-8108-07931fd365ec.png)

**Comment by YikeWang1103** [comment]
the same issues here https://github.com/ApolloAuto/apollo/issues/7203#issue-419189205

but I can't see how to solve the problem.

**Comment by cplusplus-is-best** [comment]
I met the same problem and it happened after an upgrade of docker, which makes nvidia-docker does't work properly. I then upgrade nvidia-docker to  nvidia-docker 2.0 and it works.
don't know if it works for you.

**Comment by YikeWang1103** [comment]
> I met the same problem and it happened after an upgrade of docker, which makes nvidia-docker does't work properly. I then upgrade nvidia-docker to nvidia-docker 2.0 and it works.
> don't know if it works for you.

well, thanks for your information. Let me have a try!

**Comment by natashadsouza** [comment]
You could also try the solution provided in [#5964](https://github.com/ApolloAuto/apollo/issues/5964)

**Comment by fireforge1982** [comment]
> You could also try the solution provided in [#5964](https://github.com/ApolloAuto/apollo/issues/5964)

Does APOLLO 5.0 support CUDA 10 ?

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
