### ISSUE TITLE
spline_1d_solver.h memory leak?

### ISSUE THREAD

**Issue by Aidous** [ApolloAuto/apollo#10057]
**Describe the bug**
In [spline_1d_solver.h](https://github.com/ApolloAuto/apollo/blob/3c644ba13bdde64db1d9f64a585d48b55e8b1691/modules/planning/math/smoothing_spline/spline_1d_solver.h#L42) the class Spline1dSolver should construct a virtual destructor "virtual ~Spline1dSolver() = default;".
Otherwise the derived classes cannot call destructor normally, which causing memory leaks.

**Comment by xiaoxq** [comment]
Thanks! Fix with https://github.com/ApolloAuto/apollo/pull/10063
