### ISSUE TITLE
vehicle_calibration question

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#10071]
apollo5.0 

When I try to use data_collector.py and the command was "60 20 -60" for example. Then I try to plot the fig. It looks like this:
![test](https://user-images.githubusercontent.com/39983896/67942091-041b0000-fc12-11e9-819a-475d2b589782.png)
I wonder know why there are so many 0 in this fig?

**Comment by BigBenSure** [comment]
I fix it. My code have started a canbus topic writer. Then I start an apollo canbus modules. My code have some error, and publish zero in topic.

**Comment by Addi2020** [comment]
Apollo 3.5
I want to update my Vehicle Calibration and use the same procedure 15 10 -15. but
Q1: python data_collector.py give error
No CAN Message Yet
Q2: 15 10 -15，  It means the vehicle will reach to speed 15 then decrease to stop? 

can you give some guidance about vehicle calibration?

**Comment by BigBenSure** [comment]
> Apollo 3.5
> I want to update my Vehicle Calibration and use the same procedure 15 10 -15. but
> Q1: python data_collector.py give error
> No CAN Message Yet
> Q2: 15 10 -15， It means the vehicle will reach to speed 15 then decrease to stop?
> 
> can you give some guidance about vehicle calibration?

"15 10 -15" is means use 15% throttle to speed up, when speed is on 10m/s, use 15% break to stop the car. 
I commented `No CAN Message Yet` code block. And I commented `XXX localization XXX` code block. I send this two message, but maybe the frequency is not same. So python data_collector.py give error. The output data was changed, but it is okey for use, I think.
you can read "data_collector.py" to get more details.

**Comment by Addi2020** [comment]
i try the command 15 10 -15 on real car, It start itself but the speed increases and the car do not stop itself. I think 15 10 -15 this cmd should move the car upto 10m/s speed but not more than 10m/s and then apply the soft break and stop the car. 
 
Also it give me new error today.. 
![1835797219](https://user-images.githubusercontent.com/61130487/79114269-6f6a2000-7db5-11ea-8c55-b0b1ec532cc5.jpg)
