### ISSUE TITLE
Apollo5.0.0 cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch can't work

### ISSUE THREAD

**Issue by cxr1996** [ApolloAuto/apollo#10070]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:ubuntu14.04
- **Apollo installed from (source or binary)**:binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

My camera has been successfully connected, and I can see real-time capture images in dreamview, but my camera is not officially recommended, it is my own monocular camera, and there is no radar, no GPS receiver. I'm using this camera as front_6mm and front_12mm, First run "cyber_launch start/Apollo/modules/transform/launch/static_transform. Launch" then run the "cyber_launch start/Apollo/modules/perception/production/launch/perception_camera. The launch" will appear the following error.Is my transform profile incorrect?

### Supporting materials (screenshots, command lines, code/script snippets):
[mainboard_default_10227]  E1031 17:05:46.224282 10255 transform_wrapper.cc:224] [mainboard] Can not find transform. 1572512746.146534 frame_id: novatel child_frame_id: front_6mm Error info: Could not find a connection between 'novatel' and 'front_6mm' because they are not part of the same tree.Tf has two or more unconnected trees.
[mainboard_default_10227]  E1031 17:05:46.224323 10255 fusion_camera_detection_component.cc:684] [perception] failed to get camera to world pose, ts: 1572512746.146534 camera_name: front_6mm

**Comment by ctwfei** [comment]
Hi @cxr1996, you need to adapt [static_transform_conf.pb.txt](https://github.com/ApolloAuto/apollo/blob/master/modules/transform/conf/static_transform_conf.pb.txt) to your sensor.

**Comment by HUI11126** [comment]
> Hi @cxr1996, you need to adapt [static_transform_conf.pb.txt](https://github.com/ApolloAuto/apollo/blob/master/modules/transform/conf/static_transform_conf.pb.txt) to your sensor.

Hello, I have the same problem. How to adapt static_transform_conf.pb.txt to my sensor? I use front_6mm and front_12mm.

**Comment by HUI11126** [comment]
In /apollo/modules/perception/data/params/front_12mm_extrinsics.yaml
`  frame_id: front_6mm
child_frame_id: front_12mm`

So I change the corresponding context in static_transform_conf.pb.txt, and it works . But currently I do not know the reason.
`extrinsic_file {
    frame_id: "front_6mm"  #"velodyne128"
    child_frame_id: "front_12mm"
    file_path: "/apollo/modules/perception/data/params/front_12mm_extrinsics.yaml"
    enable: true
}`

**Comment by HUI11126** [comment]
It does not work today, so I changed it back.

Edit those two files refer to Apollo 6.0

>/apollo5.5/modules/perception/production/conf/perception/camera/obstacle.pt
/apollo5.5/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt

**Comment by hjlhhh-eng** [comment]
> 它今天不起作用，所以我把它改回来了。
> 
> 编辑这两个文件，请参考 Apollo 6.0
> 
> > /apollo5.5/modules/perception/production/conf/perception/camera/obstacle.pt
> > /apollo5.5/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt

How did you modify the configuration?
