### ISSUE TITLE
springmvc整合阿波罗时，集群的配置为何不能在app.properties中完成而需要在server.xml中完成，很不方便

### ISSUE THREAD

**Issue by chelseXie** [ApolloAuto/apollo#10094]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by changsh726** [comment]
Hi @chelseXie , seems like your question is not about our project, so we will close the issue for now. Maybe you can ask for some help in https://github.com/ctripcorp/apollo/issues. If you have any additional question about the apollo autonomous driving system, please feel free to open a new issue.

Thank you for supporting Apollo!
