### ISSUE TITLE
How Can I debug the code?

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#1009]
I was used the develop environment like Visual Studio,CCS, I wonder how could I run the code step by step.You know the other development have,for example:step in,step out,run to cursor. We alse could see the adress of the variable,the value of the viralble. But I could I debeg the could in Apollo,Could you give me some help?

**Comment by lianglia-apollo** [comment]
Most of the bugs can be found through logging (using AERROR, AINFO, ADEBUG). For step by step debug, we usually use gdb.

**Comment by startcode** [comment]
The project is managed by bazel. You can integrate bazel with some IDEs. https://docs.bazel.build/versions/master/ide.html

**Comment by renzhuli** [comment]
Hello, I and you have the same confusion. I now have the Bazel plugin installed in Clion. But I can't successfully import Apollo code to compile. Do you have any methods? Thank you
