### ISSUE TITLE
Fusion component not reading messages from fusion camera detection

### ISSUE THREAD

**Issue by scui8** [ApolloAuto/apollo#10118]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Compile from source (lgsvl 5.0) 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as many details as possible**:
1. Insert `std::cout << message -> sensor_name_ << std::end;` at Proc() function in inside **fusion_component.cc** to print the messages published to channel **/perception/inner/PrefusedObjects**
2. Recompile Apollo 5 in docker see instruction below
3. Run Apollo 5 with LGSVL see instruction below
4. Only "velodyne128" is seen in the print output, there is no message coming from the camera fusion which also publishes to **/perception/inner/PrefusedObjects** seen in file **fusion_camera_detection_component**

### Launch apollo 5 with lgsvl simulator
1. Setup Apollo 5.0 + LGSVL following the instruction from https://github.com/lgsvl/apollo-5.0
2. Run LGSVL BorregasAve with Apollo 5.0
3. Into Apollo docker 
4. `cd /apollo/scripts`
5. `./dreamview.sh`
6. In dreamview, turn on transform and localization module
7. `cyber_launch start /apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch &`
8. `cyber_launch start /apollo/modules/perception/production/launch/perception.launch` to luanch camera and lidar perception
9. Hit start on LGSVL simulator, camera detection visualization window should popup

I just want to know are there flags to turn on using camera fusion detection results in the fusion component? Both lidar obstacle detection and camera obstacle detection are running correctly, but it looks like the fusion component only receives messages from lidar detection.

Thanks for your help!

**Comment by khsrhhh** [comment]
@scui8 
Could you tell me any related point about 'fusion component' and 'fusion camera detection component'?
As I know, fusion component is just related with LiDAR and Radar not camera. 
Give any information please.
