### ISSUE TITLE
How to upgrade 2.5 --> 3.5?

### ISSUE THREAD

**Issue by siqb** [ApolloAuto/apollo#10121]
Hi,

I have an Apollo 2.5 vehicle and I want to run Apollo 3.5 on it. I was able to download and build the docker image, can launch DreamView, and play the demo Cyber record file. But it doesn't run with live sensors and it's not clear how to make it run nor does it seem to be documented anywhere.

My questions:

1) Is it possible to make Apollo 3.5 run on a 2.5 vehicle? Or is a 3.5 sensor set strictly required?
2) What configuration files do I need to edit to make it talk to the sensors?
3) In our 2.5 repo, is there any config I can simply copy/port over to over to my 3.5 repo?

Thanks!

**Comment by natashadsouza** [comment]
@siqb thank you for your question and interest in Apollo!
Please refer to our [Apollo 3.5 quickstart](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_3_5_quick_start.md) for details on both software and hardware upgrades. IN response to your specific questions:
1. It will not be possible, as Apollo 3.5 requires a different sensor setup and supports only Urban Road Scenarios where as Apollo 2.5 was specially developed for Highway driving
2. Apollo 3.5 works on Cyber RT whereas Apollo 2.5 was built on ROS. Please refer to documentation on [Cyber RT](https://github.com/ApolloAuto/apollo/tree/master/docs/cyber) to learn about it.
3. As mentioned, the versions serve different purposes.

**Comment by siqb** [comment]
Thank you for your reply, @natashadsouza. However, I'm not convinced about this part: 

>     2. Apollo 3.5 works on Cyber RT whereas Apollo 2.5 was built on ROS. Please refer to documentation on [Cyber RT](https://github.com/ApolloAuto/apollo/tree/master/docs/cyber) to learn about it.

The docker container for 3.5 contains Cyber RT instead of ROS...after all, it's just user space middleware. As I mentioned in my original post, I can successfully play the demo Cyber record in the Docker container.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
