### ISSUE TITLE
Are there any documents about the mlp_evaluator neutral network model ?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#1013]
Are there any documents about the mlp_evaluator neutral network model in prediction module?
I want to know the structure of the model .

**Comment by jinghaomiao** [comment]
MLP model predicts the probability of a particular lane sequence that a vehicle is likely to take. It's a regression model. The structure is not open. But features of using this model are available in the code. You are free to use your own neural network model to replace MLP for your experimentations. Thanks!

**Comment by westeast** [comment]
ok thanks
