### ISSUE TITLE
How is the output of the perception module? (3.0 + 3.5)

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10145]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0 + 3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hello all,

I would like to know how the output from the perception module is structured for Apollo 3.0 and also 3.0+.
Which file type has the output file hand which information does it contain?

**Comment by ycool** [comment]
perception output protobuf is at https://github.com/ApolloAuto/apollo/blob/master/modules/perception/proto/perception_obstacle.proto#L169 and its topic is /apollo/perception/obstacles
