### ISSUE TITLE
On trying to cross compile cyberRT on PetaLinux arm-A53 core。

### ISSUE THREAD

**Issue by JoelinChee** [ApolloAuto/apollo#10157]
Hi, Everyone, I am trying to run Cyber RT on PetaLinux on arm-A53 core by using cross-compile way. This is the step I am trying to do. 
1. Installing the aarch64 cross compile tool chain.
2. Reinstalling the dependencies that cyber needed including:
    z   atomic   boost_atomic  fastcdr  fastrtps   tinyxml2    glog    gflags    protobuf
    uuid    PocoFoundation    boost_signals    boost_system    boost_thread    pthread
3. Finally I succeeded in compiling the cyber RT by using the cross compile tool chain.
4. I copy the example code in cyber RT to our PetaLinux OS.

The following is my question:
1.I can run the talker node, and the node can publish the messages.
2. I cannot start the listener node, the following is my error:
..................................................................................................................................................................................................
[RTPS_ERROR Error] Reader 1.f.46.cd.83.b.0.0.0.0.0.0|0.0.4.4 cannot match writer 1.f.46.cd.de.8.0.0.0.0.0.0|0.0.3.3 -> Function pairingReader
I1111 04:52:43.085566  2947 scheduler.cc:55] [listener] create croutine: listener_channel/task_state_response_new
Segmentation fault
..................................................................................................................................................................................................
I also found the following error on the PetaLinux OS:
..................................................................................................................................................................................................
[ 2263.396068] listener[2967]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x92000006, in libcyber_core.so[7fbba54000+30e000]
[ 2263.408536] CPU: 3 PID: 2967 Comm: listener Tainted: G        W       4.14.0-xilinx-v2018.3 #1
[ 2263.417155] Hardware name: xlnx,zynqmp (DT)
[ 2263.421337] task: ffffffc87ba50500 task.stack: ffffff800d658000
[ 2263.427252] PC is at 0x7fbbcf200c
[ 2263.430562] LR is at 0x58a904
[ 2263.433524] pc : [<0000007fbbcf200c>] lr : [<000000000058a904>] pstate: 80000000
[ 2263.440919] sp : 0000000000000000
[ 2263.444218] x29: 0000007fba2e2780 x28: 0000007fbaf04000 
[ 2263.449529] x27: 0000007fff49a258 x26: 0000007fba2e3270 
[ 2263.454840] x25: 0000007fba2e31b0 x24: 0000007fba2e38a0 
[ 2263.460153] x23: 0000000000001000 x22: 0000007fff49a257 
[ 2263.465464] x21: 0000007fff49a256 x20: 0000007fff49a258 
[ 2263.470777] x19: 0000007fba2e38b8 x18: 000000000000226f 
[ 2263.476088] x17: 0000000000652118 x16: 0000007fbbcf1fd0 
[ 2263.481402] x15: 0000007fbba68ad8 x14: 0000007fbbaaa580 
[ 2263.486712] x13: 000000000ba21e24 x12: 0000000000000001 
[ 2263.492026] x11: 0000000000000000 x10: 0101010101010101 
[ 2263.497337] x9 : 000000000ba21e48 x8 : 0000007fba2e2840 
[ 2263.502650] x7 : 0000007fbbcfb1a0 x6 : 0000000000000001 
[ 2263.507961] x5 : 000000000c09e9c0 x4 : 0000000000000000 
[ 2263.513274] x3 : 0000000000000000 x2 : 4b2ad28953d3bc3f 
[ 2263.518586] x1 : 0000007f3ffff010 x0 : 0000007fba2e38b8 
..................................................................................................................................................................................................
Does anyone have the same problems I faced rightnow?
I will be very appreiciated it if someone can help me.

**Comment by darbee** [comment]
@JoelinChee Sorry for the late reply. Can you paste  more detailed stack information, and the detailed steps of compiling the cyber

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
