### ISSUE TITLE
Apollo, missing input file in ad_rss_lib: build failed

### ISSUE THREAD

**Issue by arappazzo** [ApolloAuto/apollo#10159]
I'm trying to install Apollo from source. I've been following the guidelines so far, but two important steps had to be done in order to proceed.

1) Download _ad-rss-lib_

2) Download _adv-plat_

3) Put _ad-rss-lib_ and _adv-plat_ in a local path

4) Change the settings in _WORKSPACE.in_ accordingly. EG: that's how the settings for _ad-rss-lib_ should look like this:

_#ad-rss-lib
new_local_repository(
    name = "ad_rss_lib",
    build_file = "third_party/rss_lib.BUILD",
    path = "/home/tmp",
)_

Do the same for _adv-plat_
NB: it could be the case that the name of the folder containing the package has to be changed. In particular, the folder containing the equivalent of _adv-plat_ must be called _adv-plat_.

However, as I try to build Apollo, the build fails. By looking at the log file (see attachment), it seems like there's a missing input file (missing input file '@ad_rss_lib//:src/generated/situation/SituationType.cpp').
Have you got any ideas why this?

Thanks in advance

### System information

- **Ubuntu 18.04**:
- **Apollo installed from source**:

### Steps to reproduce the issue:
- **Download apollo**
- **Make changes as mentioned above**
- **bash docker/scripts/dev_start.sh**
- **bash docker/scripts/dev_into.sh**
- **bash apollo.sh build**

[myLog.txt](https://github.com/ApolloAuto/apollo/files/3831806/myLog.txt)

**Comment by arappazzo** [comment]
I've just done it again after clearing the Bazel cache. Build failed but with different error message. See attachment: missing input file '@adv_plat//:include/adv_trigger.h'

[myLog_1.txt](https://github.com/ApolloAuto/apollo/files/3841577/myLog_1.txt)

**Comment by arappazzo** [comment]
[log_tmp3.txt](https://github.com/ApolloAuto/apollo/files/3859372/log_tmp3.txt)

Further logs in case they were needed

**Comment by changsh726** [comment]
The ad_rss_lib and adv_plat have been pre-installed in the docker image. You can try the latest master branch.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
