### ISSUE TITLE
Failed to start Dreamview.

### ISSUE THREAD

**Issue by ankitdgolatkar** [ApolloAuto/apollo#10187]
OS Version: Ubuntu 18.04.3 LTS
Apollo Version: origin/r5.0.0

Hello,

I installed a fresh copy of Ubuntu and tried to get the Apollo Framework running. The build was successfull but i got an issue to load Dreamviewer.  When I execute 

> bash scripts/bootstrap.sh 

the error I got is 

>
> nohup: appending output to 'nohup.out'
> Launched module monitor.
> nohup: appending output to 'nohup.out'
> Launched module dreamview.
> Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information
> 

The Dreamviewer logs are as follows:

> GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
> Copyright (C) 2018 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from bazel-bin/modules/dreamview/dreamview...done.
> [New LWP 16768]
> [New LWP 16776]
> [New LWP 16773]
> [New LWP 16772]
> [New LWP 16775]
> [New LWP 16774]
> [New LWP 16770]
> [New LWP 16771]
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libsqlite3.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libcurl.so.4" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libuuid.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libatomic.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libpthread.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libm.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libdl.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libstdc++.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libgcc_s.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libc.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib64/ld-linux-x86-64.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libz.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/librt.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libv4l1.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgomp.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/liblber-2.4.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libpcre.so.3" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libutil.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libltdl.so.7" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libglapi.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libXdamage.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libxshmfence.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libdrm.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libcairo.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libpango-1.0.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libXcursor.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libXmu.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libv4l2.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libtheoradec.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libmp3lame.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libfreetype.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libkrb5.so.3" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libk5crypto.so.3" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libcom_err.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libresolv.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libsasl2.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgssapi.so.3" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libnuma.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libXdmcp.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libpixman-1.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libselinux.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libthai.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libudev.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libv4lconvert.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/liborc-0.4.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libtasn1.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libp11-kit.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libSM.so.6" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libxml2.so.2" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libgpg-error.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libkeyutils.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libheimntlm.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libkrb5.so.26" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libasn1.so.8" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libhcrypto.so.4" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libroken.so.18" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libgraphite2.so.3" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libdatrie.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libnih.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libdbus-1.so.3" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libwind.so.0" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libheimbase.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libhx509.so.5" is not at the expected address (wrong library or version mismatch?)
> 
> warning: .dynamic section for "/lib/x86_64-linux-gnu/libcrypt.so.1" is not at the expected address (wrong library or version mismatch?)
> 
> warning: Could not load shared library symbols for 114 libraries, e.g. /usr/local/apollo/libtorch_gpu/lib/libcaffe2_gpu.so.
> Use the "info sharedlibrary" command to see the complete listing.
> Do you need "set solib-search-path" or "set sysroot"?
> [New LWP 1703768736]
> 

Since I am new to the Apollo Framework, I dont know what i did wrong. I tried the following: [https://github.com/ApolloAuto/apollo/issues/6467](url) but it did not work. My issue has more to do with the system libraries.

**Comment by ycool** [comment]
Can you help to post the output of `uname -a` and `nvidia-smi`? And can you try it against the latest apollo version?

**Comment by ankitdgolatkar** [comment]
uname -a gives me: 

> Linux in_dev_docker 5.0.0-35-generic #38~18.04.1-Ubuntu SMP Mon Nov 11 09:16:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I do not have an Nvidia gfx card. I have AMD Caicos XT (Radeon HD 7470/8470 / R5 235/310 OEM). I searched online for an equivalent command for AMD but I did not find any.

My current apollo version branch is **r.5.0.0**. I guess this is the latest version. Do you want me to switch to the **master** instead?


P.S: I tried to get the Apollo framework to work on my virtual machine(16.04.5 LTS)  inside my laptop (Windows 7) on which the dreamview works. But it is very slow since I have no GFX card in my laptop.

**Comment by ycool** [comment]
Can you help to try the master version in your env? Do you have nvidia-docker installed? what's the output of `docker version` (out of docker) and `ldd /usr/local/apollo/libtorch_gpu/lib/libcaffe2_gpu.so` (inside docker) ?

**Comment by ankitdgolatkar** [comment]
Hello,

I solved my issue by following the link: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md

**Comment by ankitdgolatkar** [comment]
Hello,

When I restart my computer this issue is persisting. Is there a proper solution for this?

**Comment by winstonhong** [comment]
**System information**
    OS Platform and Distribution (Linux Ubuntu 18.04)
    Apollo version 5.0

**Resolution**: (Validated)
Execute bootstrap.sh twice.

(1) 
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information

(2)
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
Module monitor is already running - skipping.
Module dreamview is already running - skipping.

(3) Launch Firefox or Chrome to access http://localhost:8888

You can view Apollo modules.

**Comment by satheesh-kk** [comment]
> Hello,
> 
> I solved my issue by following the link: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md
> 
> The apollo version is still r5.0.0

@ankitdgolatkar you mean the docker is running with AMD gfx card?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
