### ISSUE TITLE
Measure Module Delay Using ROS topic

### ISSUE THREAD

**Issue by mkhayatian** [ApolloAuto/apollo#10191]
**Is your feature request related to a problem? Please describe.**
I want to measure the latency of each module. Right now, only the control and planning ros topics have latency.

**Describe the solution you'd like**
Read latency of each module using rospy.Subcscriber(...)

**Describe alternatives you've considered**
Right now, dreamview's frontend (Tasks) report the delay for each module but I don't know how to read it.
Also, the recorder analyzer is offline.

**Comment by Martin20** [comment]
Hello,

Have you solved this problem?

**Comment by algarni1997** [comment]
No yet honestly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Martin20** [comment]
At least can you let me know how I can find rospy.Subscriber() and how I can run it?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
