### ISSUE TITLE
What do the numbers (i.e., (X, Y) ) mean on the top of each bounding box in Apollo dreamviewer?

### ISSUE THREAD

**Issue by yl2280** [ApolloAuto/apollo#10203]
- **Apollo installed from (source )**:
- **Apollo version (3.5)**:
As the title:
What do the numbers (i.e., (X, Y) ) mean on the top of each bounding
box in Apollo dreamviewer?

**Comment by yl2280** [comment]
I mean I saw some speed or distance number on the top of the each bounding box (vehicle or other obstable) in Apollo dreamviewer. e.g. (5.0m, 1.0m/s). What do the numbers mean?

**Comment by natashadsouza** [comment]
@yl2280 the [Dreamview usage document](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/dreamview_usage_table.md) has information about various elements in Dreamview
