### ISSUE TITLE
bug in the planner's gridded_path_time_graph.cc

### ISSUE THREAD

**Issue by flewkca** [ApolloAuto/apollo#10219]
In the latest master branch, line 189 of gridded_path_time_graph.cc is:

`curr_s = static_cast<double>(dense_dimension_s_ - 1) * dense_unit_s_;`

Shouldn't it instead be: 

`curr_s = static_cast<double>(dense_dimension_s_) * dense_unit_s_;`

If you retain the current definition, then when dense_dimension_s_ is zero, you reset curr_s for the start of the sparse point set to a negative value.  If dense_dimension_s_ is not zero, then with the current definition you will create two sequential rows in the s-t matrix that have the same s value.  I would guess this is not intended.

**Comment by JasonZhou404** [comment]
@flewkca Thanks for pointing it out! 

The correct one should be 

`curr_s = static_cast<double>(dense_dimension_s_ - 1) * dense_unit_s_ +
             sparse_unit_s_`

The fix is created in #10223 
Thanks

**Comment by flewkca** [comment]
Great - thanks for the fix, which makes the gap between the two sections have size sparse_unit_s instead of dense_unit_s. 

One more comment, though.  In general I don't think the path_time_heuristic task handles the dense_dimension_s = 0 case.  The type of dense_dimension_s_ is unsigned int, so if it is set to zero in the config file, there is a problem with the following statement that appears several times in gridded_path_time_graph.cc:
`static_cast<double>(dense_dimension_s_ - 1)` 
The unsigned type can't handle subtracting 1 from 0 because the result is negative, so the cast to double will output garbage. 

Maybe it's true that the case of dense_dimension_s = 0 won't be encountered very often.  But I found this because I was running some convergence tests on the discretization of the s-t matrix, and it made sense to run with a constant s dimension by having 0 elements with the dense spacing.  And that doesn't seem to be a particularly strange use case.  It might be nicer from a robustness perspective just to eventually adjust the code to handle the case of 0 dense elements.

Again, thanks!

**Comment by flewkca** [comment]
One more thing - just a comment.  

It may be helpful for users if you add a little pseudo code mentioning that the following acceleration estimate:
`max_acceleration = unit_s / pow(unit_t, 2)`
actually serves as a constraint on the values of unit_s and unit_t that the path_time_heuristic can handle.  In my convergence tests I saw a lot of behavioral falloff when adjusting these parameters, and it took a bit of searching to find out that a violation of this constraint was defining the boundary of stable behavior.

**Comment by JasonZhou404** [comment]
It's assumed the developer's responsibility to understand and be cautious on such an internal algorithm.  But yes, it's always nice to ensure configuration setting to be correct. A Pr #10231 on this config is added. 

Thanks
