### ISSUE TITLE
Perception module does not work with AMD drivers

### ISSUE THREAD

**Issue by ankitdgolatkar** [ApolloAuto/apollo#10218]
OS Version: Ubuntu 18.04.3 LTS
Apollo Version: origin/r5.0.0
GFX card: AMD Caicos XT (Radeon HD 7470/8470 / R5 235/310 OEM)

I try to build the perception module using this link: 
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md

But when I use : 

> cyber_launch start modules/drivers/tools/image_decompress/launch/image_decompress.launch

the system does waits with the message 

> [cyber_launch_491] INFO Launch file [/apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch]
> [cyber_launch_491] INFO ========================================================================================================================
> [cyber_launch_491] INFO Load module [image_decompress] library: [mainboard_default_491] [CYBER_DEFAULT] conf: [/apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag] exception_handler: []
> [cyber_launch_491] INFO Start process [mainboard_default_491] successfully. pid: 499
> [cyber_launch_491] INFO ------------------------------------------------------------------------------------------------------------------------
> [mainboard_default_491]  WARNING: Logging before InitGoogleLogging() is written to STDERR
> [mainboard_default_491]  I1115 09:31:58.746973   499 module_argument.cc:81] [] command: mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_491 -s CYBER_DEFAULT 
> [mainboard_default_491]  I1115 09:31:58.748311   499 global_data.cc:150] [] host ip: 10.30.160.83
> [mainboard_default_491]  I1115 09:31:58.749598   499 module_argument.cc:57] [] binary_name_ is mainboard, process_group_ is mainboard_default_491, has 1 dag conf
> [mainboard_default_491]  I1115 09:31:58.749861   499 module_argument.cc:60] [] dag_conf: /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag
> 

Is there any workaround for this?

**Comment by ankitdgolatkar** [comment]
Hello,

An update:
 I am using a normal desktop PC with a USB Webcam. I want to test the framework first before I buy the components mentioned by Apollo.
I

**Comment by natashadsouza** [comment]
@ankitdgolatkar we appreciate your interest in Apollo. Internally we have not tested the GFX card you mentioned. If someone in the community has tested it out, let's wait to hear their solution.

**Comment by ankitdgolatkar** [comment]
> @ankitdgolatkar we appreciate your interest in Apollo. Internally we have not tested the GFX card you mentioned. If someone in the community has tested it out, let's wait to hear their solution.

Hello,

Keeping the issue of the GFX card aside, is it possible to test the Perception module using a normal webcam?

**Comment by ChihweiLHBird** [comment]
I am using latest AMD RX 5700 GPU and would like to see apollo perception module works with my platform.

**Comment by daohu527** [comment]
The amd team is supporting this, we will release it as soon as possible after test！
