### ISSUE TITLE
Set destination of the Ego vehicle using command line

### ISSUE THREAD

**Issue by saurabhjha1** [ApolloAuto/apollo#10233]
Is there a way to set the destination for the Ego vehicle using a command line (i.e., by providing waypoints via command line)?

We have to currently provide the destination using Dreamview which is not a scalable approach for conducting experiments.

We are using Apollo 5.0 on Ubuntu 18.04.

**Comment by jmtao** [comment]
@saurabhjha1 you can try:
https://github.com/ApolloAuto/apollo/blob/master/modules/tools/mock_routing/mock_routing_request.py

**Comment by jmtao** [comment]
Hi @saurabhjha1 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
