### ISSUE TITLE
Asking about the practices of collecting Point Cloud Data

### ISSUE THREAD

**Issue by JAckLosingHeart** [ApolloAuto/apollo#10249]
Hey guys, does anyone know how to collect point cloud data for building the localization map?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:16.04
- **Apollo installed from (source or binary)**:docker
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:5.0

**Comment by ycool** [comment]
cyber_recorder record -c point_cloud_topic -o output_record_file
