### ISSUE TITLE
DREAMVIEW RUNNING BUT CAN'T ACCESS IT

### ISSUE THREAD

**Issue by con00** [ApolloAuto/apollo#10255]
I successfully installed apollo and docker following the steps provided and then the problems listed below of which I am not able to access the dreamview. 

Please, I am now new on this platform and will appreciate a step wise guidance to fix the problem.

Thanks in advance.

### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version 5.0**:

### Steps to reproduce the issue:
git clone https://github.com/apolloauto/apollo
cd apollo
bash docker/setup_host/install_docker.sh
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash apollo.sh build
apollo.sh lint
bash scripts/bootstrap.sh

### Supporting materials (screenshots, command lines, code/script snippets):
FIRST:
apollo@in_dev_docker:/apollo$ apollo.sh lint
bash: apollo.sh: command not found
apollo@in_dev_docker:/apollo$ bash apollo.sh lint
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.

SECOND: Then the terminal displays：
apollo@in_dev_docker:/apollo$  bash scripts/bootstrap.sh start
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information
apollo@in_dev_docker:/apollo$ bash scripts/dreamview.sh start_fe
Module dreamview is already running - skipping.
apollo@in_dev_docker:/apollo$  

THEN:
Nothing shows up at http://localhost:8888
 
BUT:
Unable to connect

Firefox can’t establish a connection to the server at localhost:8888.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by natashadsouza** [comment]
@con00 as mentioned in #9927 please build Apollo using the guide mentioned in my comments and if you are unable to build Apollo, please send us a screenshot of your logs. Also, if you did not see any error messages in your terminal, please check your internet connection or try a different browser.

**Comment by con00** [comment]
> @con00 as mentioned in #9927 please build Apollo using the guide mentioned in my comments and if you are unable to build Apollo, please send us a screenshot of your logs. Also, if you did not see any error messages in your terminal, please check your internet connection or try a different browser.

@natashadsouza thank you for your comments. I have tried using chrome and firefox and I am receiving the same error message "unable to connect". However, I do have some error messages which I am sharing below. Please, I have tried different steps given from old issues and the procedures on how to build, maybe there is something that I am still not doing right. I will appreciate your help to get it right so I can get started with my project. Also, consider if it is from my internet connection as I am wondering about it too.

<<<attached logs below>>>
![Screenshot from 2019-11-20 23-29-52](https://user-images.githubusercontent.com/56773761/69284508-12e04b80-0bef-11ea-9a56-f5e979090c1f.png)
![Screenshot from 2019-11-20 23-31-05](https://user-images.githubusercontent.com/56773761/69284511-15db3c00-0bef-11ea-8408-dfb6c6d3a056.png)
![Screenshot from 2019-11-20 23-31-43](https://user-images.githubusercontent.com/56773761/69284516-183d9600-0bef-11ea-91be-cfbabb1bfc6e.png)
![Screenshot from 2019-11-20 23-32-46](https://user-images.githubusercontent.com/56773761/69284519-1b388680-0bef-11ea-8d4a-90115948aad3.png)
![Screenshot from 2019-11-20 23-35-02](https://user-images.githubusercontent.com/56773761/69284524-1d9ae080-0bef-11ea-85e8-56e8444a2fcb.png)

**Comment by con00** [comment]
@natashadsouza 
I have followed recommended steps but can see new error message as below. I wasn't seeing this error before.

![New error message](https://user-images.githubusercontent.com/56773761/69432610-56939c00-0d3a-11ea-8408-e137523754d9.png)

**Comment by winstonhong** [comment]
**Resolution**: (Validated)
Execute bootstrap.sh twice.

(1) 
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information

(2)
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
Module monitor is already running - skipping.
Module dreamview is already running - skipping.

(3) Launch Firefox or Chrome to access http://localhost:8888

You can view Apollo modules.
