### ISSUE TITLE
The difference between pnc-junction and junction

### ISSUE THREAD

**Issue by math715** [ApolloAuto/apollo#10260]
the hdmap proto, there are pnc-junction and junction. I want to known the difference between pnc-junction and junction.

**Comment by jmtao** [comment]
**junction** is a **rough** area around a junction/intersection. We mainly use it for perception ROI. 
**pnc-junction** is the junction concept specifically for Planning module. It uses the stop lines of traffic signs(traffic light, stop sign, crosswalk, and etc) as the boundary of the junction. The boundaries are used for decisions and planning in Planning module and must comply with traffic rules.

**Comment by math715** [comment]
I understand, Thank You.

**Comment by ntutangyun** [comment]
Hi, I wonder if the PNC junctions are pre-defined in the HD map files or the planning module add the PNC junctions to the HD map data at runtime?  thanks

**Comment by Guoooo** [comment]
Hi, Does anyone know where does PNC_Junctions come from? I couldn't find PNC_Junctions in Apollo xml sample data.

**Comment by Yuntianyi-Chen** [comment]
Hi, what is the meaning of pnc-junction boundary?
