### ISSUE TITLE
How to add your own component inside perception pipeline in Apollo 5.0?

### ISSUE THREAD

**Issue by ShepelIlya** [ApolloAuto/apollo#10277]
Hello, Apollo Team. I try to implement my own recognition algorithm that uses lidar data and after fuse it with obstacles segmented from velodyne output. I am publishing it's output with SensorFrameMessage into the /perception/inner/PrefusedObjects topic for fusing, but i can't see my messages in fusion component. What am i doing wrong? Is there any way to add messages from custom components inside perception pipeline?

**Comment by zhangchaoltt** [comment]
make sure the component have received upstream message

**Comment by ShepelIlya** [comment]
@zhangchaoltt which message? and I need to check it in fusion component or in my own?

**Comment by zhangchaoltt** [comment]
your own component.

**Comment by ShepelIlya** [comment]
@zhangchaoltt  Now my own component recieve point cloud and send SensorFrameMessage and i can view pointcloud messages in my component - or I need to receive specific messages?

**Comment by zhangchaoltt** [comment]
Put your component and fusion component in the same process， then check again

**Comment by ShepelIlya** [comment]
I added .dag with my component into a perception.dag and now fusion component receives my messages. Thank you for the quick response! I am closing the issue now.
