### ISSUE TITLE
ERROR: (11-22 19:29:53.238) no such package 'modules/perception/tool/offline_visualizer_tool': BUILD file not found on package path.

### ISSUE THREAD

**Issue by philipbinhu** [ApolloAuto/apollo#10299]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
I want to use the offline visualizatin tools.
But after runing the following command:
bazel build -c opt //modules/perception/tool/offline_visualizer_tool:offline_lidar_visualizer_tool

terminal shows me:
ERROR: (11-22 19:29:53.238) no such package 'modules/perception/tool/offline_visualizer_tool': BUILD file not found on package path.

**Comment by alexbuyval** [comment]
There is no '/modules/perception/tool/offline_visualizer_tool' in the master branch.

You need to use the following instead:
```
bazel build -c opt --cxxopt=-DUSE_GPU //modules/perception/lidar/tools:offline_lidar_obstacle_perception
```

**Comment by philipbinhu** [comment]
Thank you. 
I tried. But got the error:
daisylab@daisylab-Precision-Tower-7910:~/newdisk4/av/apollo-5.0$ bazel build -c opt --cxxopt=-DUSE_GPU //modules/perception/lidar/tools:offline_lidar_obstacle_perception
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/daisylab/newdisk4/av/apollo-5.0/tools/bazel.rc
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:4:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:32:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:48:1: name 'new_git_repository' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:57:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:66:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:75:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:137:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:144:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:209:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:217:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:225:1: name 'http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:253:1: name 'new_http_archive' is not defined
ERROR: /home/daisylab/newdisk4/av/apollo-5.0/WORKSPACE:274:1: name 'http_archive' is not defined
ERROR: error loading package '': Encountered error while reading extension file 'bazel/grpc_deps.bzl': no such package '@com_github_grpc_grpc//bazel': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'bazel/grpc_deps.bzl': no such package '@com_github_grpc_grpc//bazel': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.294s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

What the version fo bazel should be used?

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
