### ISSUE TITLE
How to using the dataset on offline/online simulations?

### ISSUE THREAD

**Issue by philipbinhu** [ApolloAuto/apollo#10298]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I'm trying to do the simulation work.
My objective is to modify the dataset such as LIDAR or Camera then run the simulation.
It seems that it can not be done by using online/cloud service。
So, How to do it offline. How to load the dataset(download from Baidu or KITTI) and run simulator at local?
My development environment was configured and can run the demo(3.5).
I can not find the instruction for Baidu 5.0.

Thank you.

**Comment by winstonhong** [comment]
**Resolution**: (Validated)

cd docs/demo_guide/

python rosbag_helper.py demo_3.5.record

source /apollo/scripts/apollo_base.sh

cyber_recorder play -f demo_3.5.record --loop
