### ISSUE TITLE
How can I run perception module on my PC? All launch file makes errors...

### ISSUE THREAD

**Issue by khsrhhh** [ApolloAuto/apollo#10292]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: **Linux Ubuntu 14.04**
- **Apollo installed from (source or binary)**: **source**
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: **5.0**

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Hi.
I have only 2 Leopard USB CAM sensors for **front_6mm** and **front_12mm** channel.
I referenced URL (https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) to run perception module on local pc.

While following the step on URL, I had an issue step 6.
I solved it for copy original *.yaml files and just changed the file names, referenced by error log messages.

But on step 8, all launch files make error log messages. 
I want to solve these problems and test on my desk.
Pictures on below show the error log messages.  

### Supporting materials (screenshots, command lines, code/script snippets):
1. 
**If you want to launch all modules**
in-dev-docker: /apollo$ cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch
![image](https://user-images.githubusercontent.com/39553283/69398683-abc9b080-0d2e-11ea-96ec-6df0b5f7b249.png)

2. 
**If you want to test camera-based obstacle and lane detection**
in-dev-docker: /apollo$ cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch
![image](https://user-images.githubusercontent.com/39553283/69398728-d7e53180-0d2e-11ea-8527-56d74c98e0e1.png)

3.
**If you want to test lane detection alone use**
in-dev-docker: /apollo$ mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.dag
![image](https://user-images.githubusercontent.com/39553283/69402959-b0956100-0d3c-11ea-90dc-4775a3e2836c.png)

4.
**If you want to test traffic light detection module alone use**
in-dev-docker: /apollo$ cyber_launch start /apollo/modules/perception/production/launch/perception_trafficlight.launch
![image](https://user-images.githubusercontent.com/39553283/69403380-c9524680-0d3d-11ea-8c18-676b44e2ac19.png)

How can I delete the **YAML expection:bad file** message?

**Comment by wangyixu14** [comment]
Have u guys solved this problem?

Thanks

**Comment by khsrhhh** [comment]
> Have u guys solved this problem?
> 
> Thanks

Yes We did.
But I cant tell you what I did specific because I solved the problem almost 3 month ago...

First, you should know that trafficlight component do not work if you do not have HDMap.
Second, I filled YAML files  on /apollo/modules/calibration/data/{vehicle directory what I made}/*.YAML
Third, The sequence is very important. I tried the follow step
        1. Launch transform module 
        2. Launch perception module what you want (ex. **cyber_launch start perception_camera.launch**)
        3. Replay bag file (ex. demo_3.5.record file ) because perception module needs localization information
        4. Launch camera module. You should change visualization option before launch, after this step you can see perception visualizer with camera

I hope this comment will be helpful.
Thanks.

**Comment by Chuck-Yu** [comment]
> Have u guys solved this problem?
> 
> Thanks

You should run command `source cyber/setup.bash` before going through any `cyber` command.
