### ISSUE TITLE
Converting tools in apollo

### ISSUE THREAD

**Issue by tonayw** [ApolloAuto/apollo#10294]
### System information

- **OS Platform and Distribution Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 3.0**:

### Steps to reproduce the issue
- I have data of type std_msgs/Image in rosbag by recording the camera topic. I was trying to modify the data to be visualized as I found the encoding as yuyv.
- I found a tool as modules/tools/rosbag/extract_images.py
- In the docker, I ran the command  `python modules/tools/rosbag/extract_images.py` and a warning poped up as `ImportError: No module named 'cv2'`
- I tried to install cv module using pip since this is the solution I found on this repo for some similar issues. Itfailed as some error message poped up saying the environment does not support the installation

So my question is does any one know how to use this extract_image tool and if there is any other way to convert the images from yuyv to rgb.

Please help me! Thank you!

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
