### ISSUE TITLE
NVIDIA PX2 AND JETSON TX2 SUPPORT

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#103]
I saw that the current version of the hardware is using an IPC，it used an Intel X86 Processer and it did not using the NVIDIA GPU Card. Are there any plan to prebuild an apollo software Platform on ARM and using CUDA. Then we can test it on a PX2 or jetson tx2 card

**Comment by quning78** [comment]
PX2 support has been under active development. The build file for apollo-platform and apollo already support to build on PX2. Also, we have the release binary for arm architecture for apollo-platform as link below:

https://github.com/ApolloAuto/apollo-platform/releases

However, we haven't finished all the integration testing for Apollo on PX2 yet, so that's why we didn't release the official support at this point. 

It's welcome that anyone can contribute in this direction as well so we will have the official support for PX2 sooner.

**Comment by fengjin89** [comment]
As I see, the IPC has a GPU installed inside. It could be Nvidia Geforce GTX1050 as the [IPC](http://www.neousys-tech.com/en/product/application/rugged-embedded/nuvo-5095gc-gpu-computer) shows.

**Comment by gengqx** [comment]
@fengjin89 This Apollo 1.0 does not use GPU.You can see it  use Nuvo-5095GC but not  Nuvo-5095GC-GTX1050, 
This link below shows how to install the hardware,and it tells us to remove the GPU card.
https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_hardware_system_installation_guide.md

**Comment by fengjin89** [comment]
@gengqx Thanks!

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!

**Comment by bbidault2** [comment]
@quning78 Could you give us an update on Apollo support on the Drive PX2 ? I can't seem to find documentation mentioning if it is or not supported. Thank you.

**Comment by narendahr15** [comment]
@quning78 Is there any milestones/plans to support the Nvidia PX2 officially?

**Comment by aboarya** [comment]
Any updates on this?  I have seen some links on installing the platform on Jetson TX2, which should work similarly on PX2 or the newer Pegasus/Xavier

**Comment by Andrea2202** [comment]
> 
> 
> Any updates on this? I have seen some links on installing the platform on Jetson TX2, which should work similarly on PX2 or the newer Pegasus/Xavier.
> 
> I am working through these blogs now and will update here when I have a status

Have you any update on the porting of Apollo on Xavier?

**Comment by aboarya** [comment]
@Andrea2202 There's been some [updates](https://github.com/ApolloAuto/apollo/commits/v3.1_dev) in the 3.1_dev branch for building against the TX2, but I have not yet tried them.
