### ISSUE TITLE
Error response from daemon: Container a731af09a99b260d01532abcbba57338042801f3a346caddfefc30be11bb9fd7 is not running

### ISSUE THREAD

**Issue by con00** [ApolloAuto/apollo#10314]
I need some help on how to fix the following error:
Error response from daemon: Container a731af09a99b260d01532abcbba57338042801f3a346caddfefc30be11bb9fd7 is not running

### System information

- **OS Platform and Distribution Linux Ubuntu 18.04
- **Apollo installed from source or binary
- **Apollo version 5

### Steps to reproduce the issue:
- git clone https://github.com/apolloauto/apollo
- cd apollo
- bash docker/setup_host/install_docker.sh
- bash docker/scripts/dev_start.sh

At this point, I could not go forward to:
- bash docker/scripts/dev_into.sh

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2019-11-24 22-14-41](https://user-images.githubusercontent.com/56773761/69501749-2bf73e00-0f08-11ea-8bc8-d5ee4974111b.png)

**Comment by Fadi88** [comment]
it seems that nvidia docker is not installed or that you dont have the drivers

**Comment by Fadi88** [comment]
1-do you have a nvidia graphics card in that PC ?
2- what is the output of running  "nvidia-smi" in terminal 
3- what are the related nvidia packages that are installed ? 
dpkg -l | grep nvidia

**Comment by con00** [comment]
Hi, and thanks.

Yes, its seems nvidia is not installed. Attached is the error message when “nvidia-smi” in entered in the terminal.

Please, how can I installed the nvidia graphics or the driver. I had installed it before but I  am not sure if it is the right one.

I appreciate your prompt feedback.

Best regards,
Chinwendu

**Comment by Fadi88** [comment]
Hi;
in the main project Readme [here](https://github.com/ApolloAuto/apollo/blob/master/README.md)
under getting started section follow step 2-3 (1 is already done for you i think)

**Comment by Martin20** [comment]
Hello, 

I have the same problem. When I use nvidia-smi command I see the lines below. However, when I run ./docker/script/dev_into.sh it says the docker is not running.

Error response from daemon: Container edbcb1245048bb5e525f5dfdf7faa3a4406e5e61932cbe424a8d0e24a59b3 is not running

apollo-5.0
ubuntu 18.04

![image](https://user-images.githubusercontent.com/24797708/81652661-f3311f80-93e8-11ea-921d-80970ccd9361.png)

**Comment by Fadi88** [comment]
hi @Martin20 

did you do a dev_start.sh before dev_into.sh
the first script create the container and the second one opens a terminal into it

**Comment by Martin20** [comment]
@Fadi88 
Yes I did.

**Comment by Fadi88** [comment]
lets do the following trial
1- docker container ls
2-dev_start_sh
3-docker container ls

after the script there should be more containers, please post the output of the 3 commands

**Comment by Martin20** [comment]
1:
![image](https://user-images.githubusercontent.com/24797708/81894984-faca0300-9565-11ea-9a3b-b5c853b16273.png)
2:

[sudo] password for mmehrabi:
[INFO] Start docker container based on local image : lgsvl/apollo-5.0:latest
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
docker.io/apolloauto/apollo:yolo3d_volume-x86_64-latest
8444c5cc76d0add8fcd24318c7b51222baecd00db04cbbe377286517b1738254
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:d8be22d8221c784e8a29af14a23be7fc5f2164137ec24228701e6fdcb689b088
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
docker.io/apolloauto/apollo:localization_volume-x86_64-latest
52b65f333583c700d4a03cba3f2835b90e281faf356b94722af0daee00ba00c1
paddlepaddle_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:901f110a4f13501e074f599b2c7d636a7584d290f59ef50237a7d77e66d025fb
Status: Image is up to date for apolloauto/apollo:paddlepaddle_volume-x86_64-latest
docker.io/apolloauto/apollo:paddlepaddle_volume-x86_64-latest
08d101cbd767e6cb06214c05ff4ba5117a4e1d84da95a154b93dfb1135f2ee85
local_third_party_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:b844c40ab0af0733ce69c38b220a8b14f752bd834f63343392ce8508b98b546b
Status: Image is up to date for apolloauto/apollo:local_third_party_volume-x86_64-latest
docker.io/apolloauto/apollo:local_third_party_volume-x86_64-latest
ae2e8bbc33e588e06d2aeffd71fca5049a61ad455dbb0fc3bbca01472f6ad539
[INFO] Starting docker container "apollo_dev_mmehrabi" ...
./docker/scripts/dev_start.sh: line 311: type: nvidia-docker: not found
++ local_volumes
++ volumes='-v /home/local/ASUAD/mmehrabi/apollo-5.0:/apollo              -v /home/local/ASUAD/mmehrabi/                                                 .cache:/home/mmehrabi/.cache'
++ case "$(uname -s)" in
+++ uname -s
++ volumes='-v /home/local/ASUAD/mmehrabi/apollo-5.0:/apollo              -v /home/local/ASUAD/mmehrabi/                                                 .cache:/home/mmehrabi/.cache -v /dev:/dev                                 -v /media:/media                                                                                  -v /tmp/.X11-unix:/tmp/.X11-unix:rw                                 -v /etc/localtime                                                 :/etc/localtime:ro                                 -v /usr/src:/usr/src                                                                                  -v /lib/modules:/lib/modules'
++ echo '-v /home/local/ASUAD/mmehrabi/apollo-5.0:/apollo              -v /home/local/ASUAD/mmehrabi/.ca                                                 che:/home/mmehrabi/.cache -v /dev:/dev                                 -v /media:/media                                                                                  -v /tmp/.X11-unix:/tmp/.X11-unix:rw                                 -v /etc/localtime:/e                                                 tc/localtime:ro                                 -v /usr/src:/usr/src                                 -v                                                  /lib/modules:/lib/modules'
+ docker run -it -d --privileged --gpus all --name apollo_dev_mmehrabi --volumes-from apollo_yolo3d_volu                                                 me_mmehrabi --volumes-from apollo_localization_volume_mmehrabi --volumes-from apollo_paddlepaddle_volume                                                 _mmehrabi --volumes-from apollo_local_third_party_volume_mmehrabi -e DISPLAY=:0 -e DOCKER_USER=mmehrabi                                                  -e USER=mmehrabi -e DOCKER_USER_ID=1941338658 -e DOCKER_GRP=apollo -e DOCKER_GRP_ID=1940914689 -e DOCKER                                                 _IMG=lgsvl/apollo-5.0:latest -e USE_GPU=1 -v /home/local/ASUAD/mmehrabi/apollo-5.0:/apollo -v /home/loca                                                 l/ASUAD/mmehrabi/.cache:/home/mmehrabi/.cache -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-                                                 unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host                                                  -w /apollo --add-host in_dev_docker:127.0.0.1 --add-host en4119317l:127.0.0.1 --hostname in_dev_docker                                                  --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 lgsvl/apollo-5.0:latest /bin/bash
4abca3841c41e09afa1c5efa3d8d5b200b1dc995f6de8c2d02dd442e0fa431c8
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
+ set +x
Error response from daemon: Container 4abca3841c41e09afa1c5efa3d8d5b200b1dc995f6de8c2d02dd442e0fa431c8 i                                                 s not running
[ OK ] Finished setting up Apollo docker environment. Now you can enter with:
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!


3:
![image](https://user-images.githubusercontent.com/24797708/81894937-db32da80-9565-11ea-98ce-d8155429cc47.png)

**Comment by Fadi88** [comment]
And after that still getting the same error ?

Seems interesting because there is an error message in the dev_start.sh maybe this is the cause

**Comment by Martin20** [comment]
@Fadi88 
Yes. I received the same error.

**Comment by Fadi88** [comment]
@Martin20 
i am sorry it is on me, the error was in the first log you sent
"./docker/scripts/dev_start.sh: line 311: type: nvidia-docker: not found"

you need to install nvidia-docker
the official docu refers to that page https://github.com/NVIDIA/nvidia-docker

feel free if you have problems in the installation and/or this solves your problem

**Comment by Martin20** [comment]
@Fadi88 
Thank you so much. It works.
