### ISSUE TITLE
[Apollo 5.0 - Perception Module] Load camera extrisic file  error, YAML exception:bad file

### ISSUE THREAD

**Issue by khsrhhh** [ApolloAuto/apollo#10329]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Hi.
When I type command **'cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch'**, it returns error message.
I want to know why this error message occurs.
I didn't revise contents about both of 6/12mm's in/extrinsics files in /apollo/modules/perception/production/data/perception/camera/params directory.

### Supporting materials (screenshots, command lines, code/script snippets):

daehochoi@in_dev_docker:/apollo$ cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch
[cyber_launch_5546] INFO Launch file [/apollo/modules/perception/production/launch/perception_camera.launch]
[cyber_launch_5546] INFO ========================================================================================================================
[cyber_launch_5546] INFO Load module [perception_camera] library: [mainboard_default_5546] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: []
[cyber_launch_5546] INFO Start process [mainboard_default_5546] successfully. pid: 5558
[cyber_launch_5546] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_5546] INFO Load module [motion_service] library: [mainboard_default_5546] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_motion_service.dag] exception_handler: []
[mainboard_default_5546]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_5546]  I1126 14:50:10.092977  5558 module_argument.cc:81] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag /apollo/modules/perception/production/dag/dag_motion_service.dag -p mainboard_default_5546 -s CYBER_DEFAULT 
[mainboard_default_5546]  I1126 14:50:10.093194  5558 global_data.cc:119] [] host ip: 192.168.10.222
[mainboard_default_5546]  I1126 14:50:10.093719  5558 module_argument.cc:57] [] binary_name_ is mainboard, process_group_ is mainboard_default_5546, has 2 dag conf
[mainboard_default_5546]  I1126 14:50:10.093726  5558 module_argument.cc:60] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
[mainboard_default_5546]  I1126 14:50:10.093729  5558 module_argument.cc:60] [] dag_conf: /apollo/modules/perception/production/dag/dag_motion_service.dag
[mainboard_default_5546]  [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[mainboard_default_5546]  [NVBLAS] Cannot open default config file 'nvblas.conf'
[mainboard_default_5546]  [NVBLAS] Config parsed
[mainboard_default_5546]  [NVBLAS] CPU Blas library need to be provided
[mainboard_default_5546]  E1126 14:50:24.083238  5558 **fusion_camera_detection_component.cc:88] [perception] load camera extrisic file  error, YAML exception:bad file
[mainboard_default_5546]  E1126 14:50:24.083281  5558 fusion_camera_detection_component.cc:88] [perception] load camera extrisic file  error, YAML exception:bad file**

I want to handle YAML exception:bad file message. 
Thanks.

**Comment by alexbuyval** [comment]
@khsrhhh which yaml files did you use?

**Comment by khsrhhh** [comment]
> @khsrhhh which yaml files did you use?

I used yaml files from LGSVL's Apollo git repository, and it works very well.
Thanks for reply.

**Comment by khsrhhh** [comment]
> @khsrhhh which yaml files did you use?

I used yaml files from LGSVL's Apollo git repository, and it works very well.
Thanks for reply

**Comment by wanglaotou** [comment]
> > @khsrhhh which yaml files did you use?
> 
> I used yaml files from LGSVL's Apollo git repository, and it works very well. Thanks for reply.

hello, i met the same problem, but i don't find any git repository about LGSVL's Apollo, can you share the link, thanks.
