### ISSUE TITLE
The problem of cyberRT scheduling

### ISSUE THREAD

**Issue by bst-dxy** [ApolloAuto/apollo#10345]
Are there any tools or mechanisms to evaluate the performance of the Cyber RT scheduling?
In other words，If I have configured schedulerconf.proto, how can I evaluate the configuration。

**Comment by zaxon** [comment]
tasks in apollo scheduler runs on scheduler processors, 
1/ scheduler schedule tasks via task priority configure, u can use cyber log system to debug it, tasks with higher priority will get processor resource than lower ones
2/ processor itself is based on operate system's thread, so u can use linux tools top/pidstat/taskset/nice/chrt to follow scheduler processor conf result

**Comment by bst-dxy** [comment]
非常感谢您的回答。我想问的是，如果我有一个类似与自动驾驶的项目，使用的是cyberRT框架。然后使用cyberRT的调度功能，我会对其进行配置。那怎么知道我配置的是否是最优的呢？有没有关于cyberRT调度方面的评价机制或者工具呢？

**Comment by zaxon** [comment]
generally speaking, RT framework provide preempt,task priority etc. mechanisms, users use framework based his/her own needs. cyberrt itself provided various rt confs helping users to improve e2e latency performance, but latency itself can be influenced by software environment, algorithm modules, etc. so we haven't provide a tool which can help u estimate e2e performance.

**Comment by bst-dxy** [comment]
Thanks very much.And Is there a way to evaluate the scheduling time of a task?

**Comment by daohu527** [comment]
I found the new module "sysmo" will provide a snapshot about the task.

**Comment by lovelydett** [comment]
Scheduler::CheckSchedStatus()

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
