### ISSUE TITLE
On the scheduling configuration of the Cyber

### ISSUE THREAD

**Issue by bst-dxy** [ApolloAuto/apollo#10357]
在choreography的配置中，如下图
scheduler_conf {
    policy: "choreography"

    choreography_conf {
        choreography_processor_num: 2
        choreography_affinity: "range"
        choreography_cpuset: "8-12"
        choreography_processor_policy: "SCHED_FIFO"

        pool_processor_num: 2
        pool_affinity: "range"
        pool_cpuset: "12-15"
        pool_processor_policy: "SCHED_OTHER"

        tasks: [
        {
            name: "control_/apollo/planning"
            processor: 0
        },
        {
            name: "canbus_/apollo/control"
            processor: 0
            prio: 2
        }

        {
            name: "guardian"
            processor: 1
        },
        ]
    }
}

control_/apollo/planning绑定到processor0上，就是此任务会一直在processor0上运行吗？如果是这样的话，例子中的三个任务都绑定的固定的processor上了，那为什么设置choreography_affinity: "range"，这样的话不是矛盾的吗？

**Comment by zhangchaoltt** [comment]
不矛盾，首先配置文件中两个任务在processor0上，另外一个任务在processor1上，另外此processor指的是调度框架意义的processor（可以理解为thread），并不是服务器硬件上的CPU。也就是说任务在线程0，线程1上执行。这两个线程在cpuset: 8-12号cpu上进行range

**Comment by bst-dxy** [comment]
@zhangchaoltt ，你好，谢谢你。不过我还有个疑问，就是上面三个task的配置是按照choreography配置进行的，那下面这些配置，就没有对应的task了呀？那为什么还要对它进行配置呢。

    pool_processor_num: 2
    pool_affinity: "range"
    pool_cpuset: "12-15"
    pool_processor_policy: "SCHED_OTHER"

**Comment by zhangchaoltt** [comment]
@bst-dxy 进程中存在未被编排的任务，比如有的任务没有在tasks里面，会被放进pool的配置的thread中执行。你可以看下调度配置文档了解更多详细信息。https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Scheduler_cn.md

**Comment by bst-dxy** [comment]
@zhangchaoltt 您好，谢谢提供的文档，我已经仔细阅读了。还有两个问题需要想你请教一下。
1、文档中关于choreography策略是根据任务的依赖执行关系、任务的执行时长、任务cpu消耗情况、消息频率等，对任务进行编排。那么对依据“任务的执行时长、任务cpu消耗情况、消息频率”这些的时候，哪个是主要依据关系呢？
2、例子中
 threads: [
        {
            name: "async_log"
            cpuset: "1"
            policy: "SCHED_OTHER"
            prio: 0
        }, {
            name: "shm"
            cpuset: "2"
            policy: "SCHED_FIFO"
            prio: 10
        }
    ]
为什么又有关于线程的配置呢？

**Comment by zhangchaoltt** [comment]
这个配置是支持对CyberRT框架或者算法模块里面的线程进行细粒度控制。比如调度线程在1-2cpu上执行，上述配置的线程在3-4cpu上执行，目的：可以减少配置线程与核心的调度线程之间的cpu资源抢占。更好的实现调度线程与其他线程的资源分配。

**Comment by bst-dxy** [comment]
好的，非常感谢您的耐心解答

**Comment by bst-dxy** [comment]
你好，我还有一个问题。根据我查到的资料就是调度的经典模式和编排模式的区别是
（1）经典模式支持把processor分组，不同范围的processor负责不同种类的任务。
（2）编排模式允许预留一部分processor，允许你指定某个task用哪个processor。
第一个问题是，当我把经典模式的processor的分组和编排模式的预留processor进行对应起来，感觉两种模式本质上没有区别呢。
第二个问题，编排模式为什么不支持processor分组呢。

**Comment by wutianze** [comment]
推荐一篇博客可以解答你的问题。https://blog.csdn.net/qq_25762163/article/details/103763525

**Comment by yiyibst** [comment]
@wutianze 好的谢谢
