### ISSUE TITLE
Problem of usage CyberRT with Python

### ISSUE THREAD

**Issue by jenamax** [ApolloAuto/apollo#10363]
Good afternoon!

I run into a problem when try to use CyberRT with Python. I created docker image using script cyber_start.sh. After that attached to container and try to execute some Python examples (using python3). But I get error that  module cyber_py not found "ModuleNotFoundError: No module named 'cyber_py3'". The same thing is with Python2. If I try to do it in docker container (created by dev_start.sh script) with whole Apollo built (not only CyberRT modules) everything is ok.

**Comment by fengqikai1414** [comment]
Before using python API, pleaser build Cyber RT first.

**Comment by ntutangyun** [comment]
@fengqikai1414 Hi, may i know what should be the CYBER_PATH be:  /apollo/cyber  or  /apollo/bazel-bin/cyber ?  Thanks.

**Comment by ntutangyun** [comment]
Hi, turned out the CYBER_PATH could be found by:  echo $CYBER_PATH after getting into the docker container with dev_into.sh script.

**Comment by unacao** [comment]
It looks like your issue is resolved. We will close the issue for now. If you have any additional question, please feel free to open a new issue.
