### ISSUE TITLE
cc1plus: some warnings being treated as errors

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#10361]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)16.04:
- **Apollo installed from (source or binary)source:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)master:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
 when I build ,it has errors like followed, but it should be warnings.How can I close Werror in Bazel?

ERROR: (11-29 01:37:35.922) /apollo/modules/drivers/canbus/can_client/socket/BUILD:5:1: C++ compilation of rule '//modules/drivers/canbus/can_client/socket:socket_can_client_raw' failed (Exit 1).
modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc: In member function 'virtual apollo::common::ErrorCode apollo::drivers::canbus::can::SocketCanClientRaw::Start()':
modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc:76:21: error: variable 'filter' set but not used [-Werror=unused-but-set-variable]
   struct can_filter filter[2048];
                     ^
cc1plus: some warnings being treated as errors

**Comment by Eclipsehelio** [comment]
**/apollo/tools/bazel.rc**
```txt
build --copt="-Werror=unused-variable"
build --copt="-Werror=unused-but-set-variable"
```
