### ISSUE TITLE
About ad_rss_lib  missing input file '@ad_rss_lib//:src/core/RssCheck.cpp

### ISSUE THREAD

**Issue by guchenyi** [ApolloAuto/apollo#10360]
I download the ad_rss_lib in my host because the git clone is too slow. Then revise the WORKSPACE.in as follow:
#ad-rss-lib
new_local_repository(
    name = "ad_rss_lib",
    build_file = "third_party/rss_lib.BUILD",
    #tag = "v1.1.0",
    path = "/home/linuxidc",
)
When build planning module, it reports:
____(11-28 09:58:42.773) [4,397 / 4,414] Writing file modules/planning/tasks/optimizers/piecewise_jerk_path/libpiecewise_jerk_path_optimizer.so-2.params
____(11-28 09:58:44.086) [4,412 / 4,430] Compiling modules/planning/tasks/optimizers/piecewise_jerk_speed/piecewise_jerk_speed_nonlinear_optimizer.cc
____(11-28 09:58:44.318) [4,417 / 4,439] Compiling modules/planning/tasks/optimizers/piecewise_jerk_speed/piecewise_jerk_speed_optimizer.cc
ERROR: (11-28 09:58:47.062) missing input file '@ad_rss_lib//:src/core/RssCheck.cpp'.
ERROR: (11-28 09:58:47.115) /home/linuxidc/.cache/bazel/_bazel_linuxidc/540135163923dd7d5820f3ee4b306b32/external/ad_rss_lib/BUILD.bazel:7:1: @ad_rss_lib//:ad_rss: missing input file '@ad_rss_lib//:src/core/RssCheck.cpp'.
____(11-28 09:58:47.147) Building complete.
ERROR: (11-28 09:58:47.157) /home/linuxidc/.cache/bazel/_bazel_linuxidc/540135163923dd7d5820f3ee4b306b32/external/ad_rss_lib/BUILD.bazel:7:1 1 input file(s) do not exist.
____(11-28 09:58:47.157) Elapsed time: 302.644s, Critical Path: 146.85s
============================
[ERROR] Build failed!
[INFO] Took 304 seconds
============================
The src/core/RssCheck.cpp is exist. How to fix it?
I also want to know if i can only build the perception modules? The build option build_opt_gpu still build planning!

**Comment by Eclipsehelio** [comment]
1) Would you please try this:
```txt
#ad-rss-lib
new_git_repository(
    name = "ad_rss_lib",
    build_file = "third_party/rss_lib.BUILD",
    tag = "v1.1.0",
    #remote = "https://github.com/intel/ad-rss-lib",
    remote = "/home/tmp/ad-rss-lib",
)
```
**/home/tmp/ad-rss-lib** is the location where you clone the **ad-rss-lib** repo.
2) Adjust the following command to perform single module build:
**bazel build --jobs=6 -c opt --verbose_failures --define ARCH=x86_64 --define USE_GPU=true --cxxopt=-DUSE_GPU --define CAN_CARD=fake_can --cxxopt=-DUSE_ESD_CAN=false //modules/perception/...**
According to your system and hardware, modify **ARCH**、**CAN_CARD**、**USE_ESD_CAN** options.
Hope that it will help you!

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
