### ISSUE TITLE
When running autonomous driving of Lincoln MKZ, does default calibration file works?

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#10376]
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 14.04
- **Apollo installed from (source or binary)**: Binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

Dear Apollo Team,

We're supposed to test autonomous driving of our Lincoln MKZ, real vehicle. Before doing field test, I'm concerned that default vehicle calibration file provided works or not. As for running planning, control modules, does default vehicle calibration file works for basic following way point on lane? If there is anyone who has experience doing field test with real autonomous vehicle, could you let us know whether you should do vehicle calibration or just use provided calibration file for Lincoln MKZ? I wonder if provided MKZ vehicle calibration file is enough to run real vehicle. 

I found the following calibration file. I mean this file.

Apollo 3.0: https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/calibration/data/mkz_example/calibration_table.pb.txt

Apollo 5.0:
https://github.com/ApolloAuto/apollo/blob/master/modules/control/conf/calibration_table.pb.txt

Best

**Comment by jinghaomiao** [comment]
Yes the default calibration file works.
