### ISSUE TITLE
git clone下载出错怎么办

### ISSUE THREAD

**Issue by Benjiemin1997** [ApolloAuto/apollo#10378]
* GnuTLS recv error (-110): The TLS connection was non-properly terminated.
* Closing connection 0
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed

**Comment by natashadsouza** [comment]
@Benjiemin1997 please send me a screenshot of your terminal. Thanks!

**Comment by chuang213** [comment]
try this:
git config --global http.postBuffer 1048576000

**Comment by winstonhong** [comment]
**Resolution**: (Validated)

git clone https://github.com/ApolloAuto/apollo
cd apollo/
git status
git checkout r5.0.0

**Comment by NoRomantic** [comment]
> try this:
> git config --global http.postBuffer 1048576000

Thanks for your reply, I modify postBuffer to 2G then I can clone this repository.

**Comment by unacao** [comment]
It looks like your issue is resolve. We will close the issue for now. If you have any additional question, please feel free to open a new issue.
