### ISSUE TITLE
关于横向偏差率的问题

### ISSUE THREAD

**Issue by Shaquille-Wu** [ApolloAuto/apollo#10397]
按照书上（vehicel_dynamic_and_control）的公式： 
lateral_err_dot = Vy + Vx*(theta-ref_theta)
 但是apollo给的公式是：lateral_error_dot = linear_v * std::sin(heading_error) 
有没有老师能解释一下apollo为什么这么干的
希望老师能告知相关的原理和出处

**Comment by Shaquille-Wu** [comment]
wait for replying

**Comment by kevin-y-wang** [comment]
感谢你提出的问题。apollo控制模块中此处计算的目的是: 测量lateral_error_dot每个时刻的真实值。既然没有传感器能够直接测量该值，就需要借助其他可测量进行推导
回到你问题中列出的两个公式：
（1）vehicel_dynamic_and_control中给出的动力学建模理论公式，虽然始终成立，但式中的侧向滑动速度（Vy）和纵向速度(Vx)不能直接测量得出
（2）lateral_error_dot = linear_v * std::sin(heading_error)中的linear_v是可测量的沿当前车身朝向(theta方向)的速度，近似相当于纵向（沿ref_theta）、侧向速度(垂直于ref_theta)的矢量和，所以linear_v在垂直方向上的分量可作为近似的侧向速度

**Comment by Shaquille-Wu** [comment]
还想再麻烦一下老师，照老师的意思，apollo的linear_v并不是Vx，那这个linear_v是表达的什么意思呢？是本时间点的距离和上一时间点距离的差值除以时间吗？可能我的表述不是很好，我只是想知道既然这个linear_v不是Vx，那它又是什么呢？

**Comment by kevin-y-wang** [comment]
严格来说，linear_v是Vx和Vy的矢量和；Vx是linear_v在纵向(x方向)上的分量

**Comment by schweinebauch** [comment]
> 严格来说，linear_v是Vx和Vy的矢量和；Vx是linear_v在纵向(x方向)上的分量

就着这个问题想请教一下老师，看apollo的代码意思是heading是车速度的方向，而yaw是车身车头的方向，如果车辆直线行驶那么heading和yaw是重合的，也就是速度方向和车头方向是一致的，但是当车辆转弯时，速度方向（heading）和车头方向（yaw）就会有一个夹角。所以在做控制的时候，比如说运动学模型，dx = vcos(heading), dy= vsin(heading)，而不是yaw，也就是合速度标量在x，y轴上的投影。想和老师确定一下我的理解是否正确？
