### ISSUE TITLE
Bug report: extract_data has issues while giving a whole folder as input

### ISSUE THREAD

**Issue by cuicuihaohaoxuexi** [ApolloAuto/apollo#10404]
The system information is as below:

Ubuntu 14.04
Apollo directly from GitHub source
Apollo 5.0

When using the extract_data.py in modules/tools/sensor_calibration/, they require the input path in a config file under modules/tools/sensor_calibration/config/. The default way to specify every record file as inputs but it also provides a function to input a folder. When I try to input a folder contained more than 30 files, the output pcd files and pose file have some timestamp jump. It means that the timestamp is no longer consecutive. When I decrease the file number inside the folder, the timestamp jump will get smaller. For example, when I run the extract_data.py with an input of a folder containing 33 files, the timestamp jump happened 9 times and all of the jumps are over 100 s. After I decrease the number to 10 files in the folder, the timestamp jump happened also 9 times but the jumps are about 30 s. When I decrease the file number to 3, there is no timestamp jump anymore. If I have the 33 input files written one by one in the config file, no timestamp jump happens. 

I think there is a bug in the extract_data.py. When the input is one file, it will read in the first file, parse the data and then write into an output file. Then it will close the current input file and read the next one. Repeat this process until you finish all the input files. However, if the input path is a folder, it seems like that the extract_data.py tries to read in all the files in that folder together and some data is dropped at that time.

**Comment by biaogecui** [comment]
@cuicuihaohaoxuexi Hi，have you solve this problem? Now I just want to use this tool to extract a record to pcds and odometry. But I failed .Can you give me some advice,thank you!

**Comment by cuicuihaohaoxuexi** [comment]
@biaogecui Are you using Apollo 5.0 or 5.5? The config file now has a different format in Apollo 5.5. For my previous case, reading in a whole folder still doesn't work. I have to specify all the files one by one in the folder to make it work.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
