### ISSUE TITLE
Path Smoother basics

### ISSUE THREAD

**Issue by hect1995** [ApolloAuto/apollo#10416]
I want to use the Path Smoother that you implement  but I have some doubts:

- In case I have in advance (obtained outside your platform) a path including both forward and backwards direction what would you say is the easiest way I can input it in your framework? What I mean is that I do not need the whole project but just some specific scripts to compute an optimized trajectory.

- I do not understand what is the difference between distance_approach files and iterative_anchoring_smoother.cc

- I haven’t seen where you include the direction of the vehicle into the optimization, because if you do optimization between a set of <x,y> points for a path that consisted on both forward and backward path you need it

**Comment by jinghaomiao** [comment]
On-lane planner does not support backward trajectory planning. Please refer to open space planner in planning module.

**Comment by hect1995** [comment]
Yes, my question was about the Open Space Planner

**Comment by JasonZhou404** [comment]
1. You could refer to /apollo/modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_generation.cc for more detail on how to define your own trajectory planner.

2. Two different approaches on smoothing a jerky trajectory

3. It is considered in Hybrid A* searching algorithm

Thanks

**Comment by hect1995** [comment]
3. But when you optimize you change the position of <x,y> so the kinematic relationship obtained from A* dissapears

**Comment by Capri2014** [comment]
No, it does not: https://github.com/ApolloAuto/apollo/blob/c18a5adfe3fa04009715b7ced5e1f6310091a8f0/modules/planning/open_space/trajectory_smoother/distance_approach_ipopt_relax_end_interface.cc#L771

**Comment by sjiang2018** [comment]
Hi @hect1995, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
