### ISSUE TITLE
How to use cyber_visualizer in apollo master and latest image

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#10424]
As I see,cyber_visualizer is disabled in apollo.sh build：
```
#    BUILD_TARGETS=`bazel query //modules/... union //cyber/...`
    # FIXME(all): temporarily disable modules doesn't compile in 18.04
    BUILD_TARGETS=`bazel query //modules/... union //cyber/... except //modules/tools/visualizer/... except //modules/v2x/... except //modules/map/tools/map_datachecker/... $DISABLE_CYBER_MODULES`
```
Is there any other way to use it（ such as build in r5.0.0 image and copy here），or something instead of it？

**Comment by jinghaomiao** [comment]
We are in the process of migrating more cyber RT tools with ubuntu 18.04 support. Please stay tuned.

**Comment by sinopec** [comment]
Any updates about this issue?

**Comment by zhanghming** [comment]
@jinghaomiao Dose Apollo 5.5 not build cyber_visualizer by default? I cann't find the cyber_visualizer executable after compiling.

**Comment by jinghaomiao** [comment]
@storypku Please help with this issue.

**Comment by storypku** [comment]
> @storypku Please help with this issue.

Got it.

**Comment by zhanghming** [comment]
I find the solution, we should add `graphics` option in dev_start.sh in [line 409](https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/docker/scripts/dev_start.sh#L409). And I find the `graphics` option is exist in latest Apollo master branch.

**Comment by storypku** [comment]
> I find the solution, we should add `graphics` option in dev_start.sh in [line 409](https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/docker/scripts/dev_start.sh#L409). And I find the `graphics` option is already exist in latest Apollo master branch.
> 
> BTW, I can use
> 
> ```shell
> sudo apt-get update
> sudo apt-get install qt5-default
> bazel build //modules/tools/visualizer:cyber_visualizer
> ```
> 
> to build the `cyber_visualizer` in docker, but after execute this command, I find there are so many modules are not built. So my question is how to build `cyber_visualizer` in terminal additionally without affect already built modules if I don't want to modify the `apollo.sh` file. I'm not familiar with the bazel build usages.

Try run `./apollo.sh build_cyber` inside apollo container.

**Comment by Avps1** [comment]
> > I find the solution, we should add `graphics` option in dev_start.sh in [line 409](https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/docker/scripts/dev_start.sh#L409). And I find the `graphics` option is already exist in latest Apollo master branch.
> > BTW, I can use
> > ```shell
> > sudo apt-get update
> > sudo apt-get install qt5-default
> > bazel build //modules/tools/visualizer:cyber_visualizer
> > ```
> > 
> > 
> > to build the `cyber_visualizer` in docker, but after execute this command, I find there are so many modules are not built. So my question is how to build `cyber_visualizer` in terminal additionally without affect already built modules if I don't want to modify the `apollo.sh` file. I'm not familiar with the bazel build usages.
> 
> Try running `./apollo.sh build_cyber` inside apollo container.

Hi,
The ./apollo.sh build_cyber command does not work in my machine. 
Opening cyber_visualizer still shows the same error -> 
"Could not initialize GLX
Aborted (core dumped)".

**Comment by storypku** [comment]
> > > I find the solution, we should add `graphics` option in dev_start.sh in [line 409](https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/docker/scripts/dev_start.sh#L409). And I find the `graphics` option is already exist in latest Apollo master branch.
> > > BTW, I can use
> > > ```shell
> > > sudo apt-get update
> > > sudo apt-get install qt5-default
> > > bazel build //modules/tools/visualizer:cyber_visualizer
> > > ```
> > > 
> > > 
> > > to build the `cyber_visualizer` in docker, but after execute this command, I find there are so many modules are not built. So my question is how to build `cyber_visualizer` in terminal additionally without affect already built modules if I don't want to modify the `apollo.sh` file. I'm not familiar with the bazel build usages.
> > 
> > 
> > Try running `./apollo.sh build_cyber` inside apollo container.
> 
> Hi,
> The ./apollo.sh build_cyber command does not work in my machine.
> Opening cyber_visualizer still shows the same error ->
> "Could not initialize GLX
> Aborted (core dumped)".

Hi @Avps1, this issue should have been fixed in Apollo master now.

**Comment by Alphabaijinde** [comment]
> > > > 我找到了解决方案，我们应该`graphics`在 dev_start.sh 的[第 409 行](https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/docker/scripts/dev_start.sh#L409)添加选项。而且我发现该`graphics`选项已经存在于最新的 Apollo master 分支中。
> > > > 顺便说一句，我可以使用
> > > > ```shell
> > > > sudo apt-get update
> > > > sudo apt-get install qt5-default
> > > > bazel build //modules/tools/visualizer:cyber_visualizer
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 在docker中构建`cyber_visualizer`，但执行此命令后，我发现有很多模块没有构建。`cyber_visualizer`所以我的问题是如果我不想修改`apollo.sh`文件，如何在不影响已构建模块的情况下另外构建终端。我不熟悉 bazel 构建用法。
> > > 
> > > 
> > > 尝试`./apollo.sh build_cyber`在 apollo 容器中运行。
> > 
> > 
> > 嗨，
> > ./apollo.sh build_cyber 命令在我的机器上不起作用。
> > 打开cyber_visualizer 仍然显示相同的错误-> 
> > “无法初始化GLX 
> > Aborted（核心转储）”。
> 
> 你好@Avps1，这个问题现在应该已经在 Apollo master 中修复了。

dev_start.sh    docker --net=host   可以在宿主机显示，但是为了远程调试docker 中的 apollo，--net=bridge后，cyber_visualization无法在宿主机显示。请求帮助
