### ISSUE TITLE
How to display the perception results  in the second circle when playing the demo files?

### ISSUE THREAD

**Issue by shanliang1992** [ApolloAuto/apollo#10441]
The perception result would not be shown in dreamview after the first cricle when playing the demo bag files.
What the flag of turning on/off timestamp checking in dreamview?

**Comment by vlin17** [comment]
please try clicking "Reset Backend data" from the Tasks console and/or refresh the browser.

**Comment by sjiang2018** [comment]
Hi @shanliang1992, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
