### ISSUE TITLE
MSF perception for obstacle detection(camera module not involved)

### ISSUE THREAD

**Issue by ningfeiwang** [ApolloAuto/apollo#10495]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Compile from source (lgsvl 5.0)
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: Apollo-5.0

### Steps to reproduce the issue:

I found out that in MSF perception for obstacle detection, Apollo only uses LiDAR and Radar without camera. The following is what I found.

1. I use grep -r dag_streaming_perception in modules/dreamview folder. But I found out by default, only dag_streaming_perception.dag is involved, which does not include the camera(in dag_streaming_perception.dag).

2. I try to add some logs information in probabilistic_fusion.cc, but the camera_measurements seems empty.

3. I found the documents in Apollo github, which introduce 3d obstacle perception, do not include camera. The following is the link
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception.md

It seems like that the camera module is not launched by default, which is inconsistent with the ReadMe file in the perception section. I wonder whether such settings are correct. For MSF perception, should the camera module be involved?

Thank you very much.

**Comment by jinghaomiao** [comment]
In Apollo 5.0+, camera component is not turned on by default. Apollo mainly relies on LiDAR for 3D obstacle detection. You need to turn on the camera separately with a separate dag file.

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.

**Comment by ntutangyun** [comment]
@jinghaomiao hi, please kindly help with my [issue](https://github.com/ApolloAuto/apollo/issues/11887) about Apollo pre6 branch camera + fusion. thanks.
