### ISSUE TITLE
flag provided but not defined: -u

### ISSUE THREAD

**Issue by sgong4** [ApolloAuto/apollo#105]
first when i bash pollo-master/docker/scripts/release_into.sh ,there is a Instruction error reporting.
as follows:
demo@demo-VirtualBox:~$ bash '/home/demo/Downloads/apollo-master/docker/scripts/release_into.sh' 
flag provided but not defined: -u
See 'docker exec --help'.
demo@demo-VirtualBox:~$ 

who can teach me how to solve this,Thanks

**Comment by wanglei828** [comment]
what's the version of your docker?

**Comment by sgong4** [comment]
Docker version 1.6.2 bulid 7c8fca2  @wanglei828

**Comment by startcode** [comment]
@sgong4 
This is what I have
```
% docker --version
Docker version 17.05.0-ce, build 89658be
```
Is it possible for you to update your docker version and try again?
Thank you.

**Comment by sgong4** [comment]
@startcode 
when i try update my docker version , i meet some problems.
follows:
Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)

i baidu many solutions , but it doesn't work.
so can you tell me how to do it .
thanks.
 another question is , do you run the demo successful.

**Comment by quning78** [comment]
maybe use sudo to do the update?

Best wishes,
-- 
Ning Qu

**Comment by sgong4** [comment]
now i update my docker version 
it's Docker version 1.9.1, build a34a1d5
but when i try this  "docker/scripts/release_start.sh"
there will be some errors ,like below:

 OK ] Found device: /dev/loop7.
[ OK ] Found device: /dev/loop6.
[ OK ] Found device: /dev/loop5.
[ OK ] Found device: /dev/loop4.
[ OK ] Found device: /dev/loop3.
[ OK ] Found device: /dev/loop2.
[ OK ] Found device: /dev/loop1.
[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop-control.
flag provided but not defined: --shm-size
See 'docker run --help'.
Error response from daemon: no such id: apollo_release
Error response from daemon: no such id: apollo_release
Error response from daemon: no such id: apollo_release


Can you give any advice?
@quning78 @startcode @wanglei828

**Comment by xiaoxq** [comment]
This question should have been obsolete.
Feel free to open a new issue if you meet problem on new Apollo.
