### ISSUE TITLE
Could not launch module perception. Is it already built?

### ISSUE THREAD

**Issue by chowkamlee81** [ApolloAuto/apollo#10502]
Could not launch module perception. Is it already built? Kindly help

**Comment by chowkamlee81** [comment]
Kindly help

**Comment by jinghaomiao** [comment]
Please provide more info.

**Comment by unacao** [comment]
did you build it with command "./apollo.sh build"?

**Comment by daohu527** [comment]
Yes, you need to build the perception module before run it.
