### ISSUE TITLE
cyber service discovery bug

### ISSUE THREAD

**Issue by nelsonjin** [ApolloAuto/apollo#10500]
cyber service server is using Single-value-warehouse Storage, it will replace process's local storage once 'Service' remote change message is received.  

so when a duplicated node start, it'll broadcast 'node' change msg and 'service' change msg **WITHOUT SYNCHRONIZATION** ,  the duplicated node will shutdown itself, but service client will remove local service server information, causing client's service calling timeout. but tools like cyber_service will works fine which making the service looks really wired....

**Comment by ctwfei** [comment]
Hi nelsonjin,

I have been trying to reproduce your issue for a while without any success. In your test case,  is the server started first or the client started first?

If you start the server first and then the client, the client will be closed because a node with the same name already exists in the domain. At this time, the server is working fine and cyber_service can show that the server meets the expectation.

**Comment by nelsonjin** [comment]
really sorry for ur time to reproducing this problem.  
I find out it's local update caused this problem  which meant to implement 'wait_for_service' interface. client will block if no server's service discovery information is in local single-value-warehouse storage. but service discovery logic DO works unexpectedly. 

and another problem:
1. cyber service's default qos setting is not approriate. 10 depth history will cause crashed server receive 10 history message.
2. why are you using rtps 1.5 + patch, not using rtps 1.8, is there any compatiblity problem?  because ros2 is using higher version rtps

**Comment by ctwfei** [comment]
> cyber service's default qos setting is not approriate. 10 depth history will cause crashed server receive 10 history message.

Can you provide slightly more information about you test case? According to our test, the depth of history for service is sufficient, you can change the default size to suit your needs, but this may incur some memory overhead.

> why are you using rtps 1.5 + patch, not using rtps 1.8, is there any compatiblity problem? because ros2 is using higher version rtps. 

In fact, we are considering upgrading fastrtps in the next Q.

**Comment by nelsonjin** [comment]
for service communication case,  we don't need any history message, but each message must be reliable, it can't be dropped.  history depth can't set to zero(rtps limited). so I set service qos as follows:

>  const QosProfile QosProfileConf::QOS_PROFILE_SERVICES_DEFAULT = CreateQosProfile(
>     QosHistoryPolicy::HISTORY_SYSTEM_DEFAULT,
>     QOS_HISTORY_DEPTH_SYSTEM_DEFAULT, QOS_MPS_SYSTEM_DEFAULT,
>     QosReliabilityPolicy::RELIABILITY_RELIABLE,
>     QosDurabilityPolicy::DURABILITY_VOLATILE);

but there still have a problem, messages will be dropped before service discovery complete.

so we added wait_for_service logic which triggered above problem, the wait_for_service logic itself is ok, but service discovery for `service_manager` is not right for service provider crash or duplicate service provider node scenario

**Comment by ctwfei** [comment]
Hi nelsonjin,

Kindly let me know why do you have to use duplicate node?  

If you want to wait until the server joins the topology before the client sends the request, the following code may help you：
`auto service_manager = TopologyManager::Instance()->service_manager();`
 `while (!service_manager->HasService("example_server")) {`
  `  std::this_thread::sleep_for(std::chrono::microseconds(10));`
`}`

**Comment by nelsonjin** [comment]
1. client & server communicating successfully
2. kill service server
3. start server in less than 12 seconds (or immediately)
4. your client process 's HasService("example_server") will always return false after 12 seconds. because last will message of the killed node will be received by your client process invoking method `TopologyManager::OnParticipantChange`， and local storage of service_manager is cleared.


for duplicate node:
I can't stop others from starting up the duplicate node......

**Comment by ctwfei** [comment]
Hi nelsonjin,

I don't think there's a problem, you can do a test on your machine.

The process ID is different when the server starts multiple times, so the local storage of the service information will not be matched and removed when the client detects that the server going stale.

**Comment by nelsonjin** [comment]
> Hi nelsonjin,
> 
> I don't think there's a problem, you can do a test on your machine.
> 
> The process ID is different when the server starts multiple times, so the local storage of the service information will not be matched and removed when the client detects that the server going stale.

For CRASH scenario,  you are right.  but for duplicate node, here's log for HasService(xxx) Log & Participant/Remote Change Log, the service communication is still ok just because client send to rtps without check server existence.


`E1219 20:33:34.516829 11481 client.h:278] [service_example_core] CLIENT_CALLED|service=hi, seq=11
E1219 20:33:34.517992 11508 client.h:301] [service_example_core] CLIENT_RECV|service=hi, seq=11
E1219 20:33:35.418089 11500 topology_manager.cc:128] [service_example_core] PARTICIPANT_CHANGE|msg=timestamp: 1576758815418042722 change_type: CHANGE_PARTICIPANT operate_type: OPT_JOIN role_type: ROLE_PARTICIPANT role_attr { host_name: "ubuntu" process_id: 11509 }
E1219 20:33:35.428787 11500 topology_manager.cc:128] [service_example_core] PARTICIPANT_CHANGE|msg=timestamp: 1576758815428762248 change_type: CHANGE_PARTICIPANT operate_type: OPT_JOIN role_type: ROLE_PARTICIPANT role_attr { host_name: "ubuntu" process_id: 11509 }
**HasService hi = 1**
E1219 20:33:35.518543 11481 client.h:278] [service_example_core] CLIENT_CALLED|service=hi, seq=12
E1219 20:33:35.519184 11508 client.h:301] [service_example_core] CLIENT_RECV|service=hi, seq=12
client: responese: service_test
E1219 20:33:35.549780 11502 manager.cc:198] [service_example_core] REMOTE_CHANGE|msg=timestamp: 1576758815420296367 change_type: CHANGE_NODE operate_type: OPT_JOIN role_type: ROLE_NODE role_attr { host_name: "ubuntu" host_ip: "192.168.219.235" process_id: 11509 node_name: "server" node_id: 2324657414937636682 }, from_same_process=0
E1219 20:33:35.549818 11502 node_manager.cc:97] [service_example_core] NODE_NEGLECT|node_id=2324657414937636682
E1219 20:33:35.549859 11502 manager.cc:198] [service_example_core] REMOTE_CHANGE|msg=timestamp: 1576758815428114718 change_type: CHANGE_SERVICE operate_type: OPT_JOIN role_type: ROLE_SERVER role_attr { host_name: "ubuntu" process_id: 11509 node_name: "server" node_id: 2324657414937636682 service_name: "hi" service_id: 11290347552884584064 }, from_same_process=0
E1219 20:33:35.549871 11502 service_manager.cc:107] [service_example_core] SERVICE_UP|service_id=11290347552884584064
E1219 20:33:35.623646 11502 manager.cc:198] [service_example_core] REMOTE_CHANGE|msg=timestamp: 1576758815621081466 change_type: CHANGE_NODE operate_type: OPT_LEAVE role_type: ROLE_NODE role_attr { host_name: "ubuntu" host_ip: "192.168.219.235" process_id: 11509 node_name: "server" node_id: 2324657414937636682 }, from_same_process=0
E1219 20:33:35.629529 11500 topology_manager.cc:128] [service_example_core] PARTICIPANT_CHANGE|msg=timestamp: 1576758815629484549 change_type: CHANGE_PARTICIPANT operate_type: OPT_LEAVE role_type: ROLE_PARTICIPANT role_attr { host_name: "ubuntu" process_id: 11509 }
E1219 20:33:35.725620 11500 topology_manager.cc:128] [service_example_core] PARTICIPANT_CHANGE|msg=timestamp: 1576758815725580344 change_type: CHANGE_PARTICIPANT operate_type: OPT_LEAVE role_type: ROLE_PARTICIPANT role_attr { host_name: "ubuntu" process_id: 11509 }
**HasService hi 0**
rtps write
E1219 20:33:36.520648 11481 client.h:278] [service_example_core] CLIENT_CALLED|service=hi, seq=13
E1219 20:33:36.521471 11508 client.h:301] [service_example_core] CLIENT_RECV|service=hi, seq=13
client: responese: service_test
**HasService hi 0**
rtps write
E1219 20:33:37.522266 11481 client.h:278] [service_example_core] CLIENT_CALLED|service=hi, seq=14
E1219 20:33:37.523483 11508 client.h:301] [service_example_core] CLIENT_RECV|service=hi, seq=14`

**Comment by ctwfei** [comment]
Please refer to [CyberRT_API_for_Developers](https://github.com/ApolloAuto/apollo/blob/b0833bc0d93797e91ab9d2971e4843c0b0b4c0e2/cyber/doxy-docs/source/CyberRT_API_for_Developers.md) for the precautions to create a service or a client.

Feel free to reopen if you have additional questions. Thanks!

**Comment by nelsonjin** [comment]
BUG is obvious in ABOVE IMAGE....    HasService returned false after duplicated node launched.
