### ISSUE TITLE
The coefficient of the kernel matrix in FemPosDeviationOsqp algorithm.

### ISSUE THREAD

**Issue by studentlemon** [ApolloAuto/apollo#10521]
in module of planning, the function of void FemPosDeviationOsqpInterface::CalculateKernel(....)
I don't know why the matrix of kernel : 　
With the exception of diagonal elements, all elements should be multiplied by 2．
for example : The coefficient of x1x2 should be -4X-2Y?
I think it should be  -4X-2Y, the diagonal element coefficients of the kernel matrix are all right.
  // |X+Y+Z, -2X-Y,   X,       0,       0,       0    |
  // |0,     5X+2Y+Z, -4X-Y,   X,       0,       0    |
  // |0,     0,       6X+2Y+Z, -4X-Y,   X,       0    |
  // |0,     0,       0,       6X+2Y+Z, -4X-Y,   X    |
  // |0,     0,       0,       0,       5X+2Y+Z, -2X-Y|
  // |0,     0,       0,       0,       0,       X+Y+Z |

**Comment by JasonZhou404** [comment]
@studentlemon What is your reason for that?

**Comment by JasonZhou404** [comment]
I will close this issue. If you still have the concern, feel free to reopen it
