### ISSUE TITLE
shm_dispatcher_test and shm_transceiver_test fail

### ISSUE THREAD

**Issue by CapLeo2009** [ApolloAuto/apollo#10520]
**Describe the bug**
I have tried to build Cyber RT inside docker following the [guide](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Docker.md). But two unit test failed: shm_dispatcher_test & shm_transceiver_test. It seems poll() doesn't get the ready fd number in [MulticastNotifier::Listen()](https://github.com/ApolloAuto/apollo/blob/master/cyber/transport/shm/multicast_notifier.cc).

**Screenshots**
FAIL: (12-16 12:49:10.047) //cyber/transport:shm_transceiver_test (see /home/capleo/.cache/bazel/_bazel_capleo/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-fastbuild/testlogs/cyber/transport/shm_transceiver_test/test.log).
INFO: (12-16 12:49:10.047) From Testing //cyber/transport:shm_transceiver_test:
==================== Test output for //cyber/transport:shm_transceiver_test:
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1216 20:49:09.538059 27520 global_data.cc:150] [shm_transceiver_test] host ip: 192.168.100.117
W1216 20:49:09.538161 27520 environment.h:33] [shm_transceiver_test] Environment variable [CYBER_PATH] not set, fallback to 
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from ShmTransceiverTest
[ RUN      ] ShmTransceiverTest.constructor
[       OK ] ShmTransceiverTest.constructor (0 ms)
[ RUN      ] ShmTransceiverTest.enable_and_disable
cyber/transport/transceiver/shm_transceiver_test.cc:112: Failure
      Expected: msgs.size()
      Which is: 0
To be equal to: 1
cyber/transport/transceiver/shm_transceiver_test.cc:116: Failure
      Expected: msgs.size()
      Which is: 0
To be equal to: 2
cyber/transport/transceiver/shm_transceiver_test.cc:139: Failure
      Expected: msgs.size()
      Which is: 0
To be equal to: 1
[  FAILED  ] ShmTransceiverTest.enable_and_disable (501 ms)
[----------] 2 tests from ShmTransceiverTest (501 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (501 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ShmTransceiverTest.enable_and_disable

 1 FAILED TEST

FAIL: (12-16 12:49:11.474) //cyber/transport:shm_dispatcher_test (see /home/capleo/.cache/bazel/_bazel_capleo/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-fastbuild/testlogs/cyber/transport/shm_dispatcher_test/test.log).
INFO: (12-16 12:49:11.474) From Testing //cyber/transport:shm_dispatcher_test:
==================== Test output for //cyber/transport:shm_dispatcher_test:
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1216 20:49:09.453120 27424 global_data.cc:150] [shm_dispatcher_test] host ip: 192.168.100.117
W1216 20:49:09.453228 27424 environment.h:33] [shm_dispatcher_test] Environment variable [CYBER_PATH] not set, fallback to 
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from ShmDispatcherTest
[ RUN      ] ShmDispatcherTest.add_listener
[       OK ] ShmDispatcherTest.add_listener (0 ms)
[ RUN      ] ShmDispatcherTest.on_message
cyber/transport/dispatcher/shm_dispatcher_test.cc:95: Failure
      Expected: recv_msg->message
      Which is: ""
To be equal to: send_msg->message
      Which is: "raw_message"
[  FAILED  ] ShmDispatcherTest.on_message (2000 ms)
[ RUN      ] ShmDispatcherTest.shutdown
[       OK ] ShmDispatcherTest.shutdown (5 ms)
[----------] 3 tests from ShmDispatcherTest (2005 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (2005 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ShmDispatcherTest.on_message

 1 FAILED TEST

**Desktop (please complete the following information):**
 - OS: Linux 5.3.12-1-MANJARO x86_64 GNU/Linux

**Comment by CapLeo2009** [comment]
### Debug log for shm_dispatcher_test:
og file created at: 2019/12/17 19:05:46
Running on machine: in_cyber_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1217 19:05:46.955484 22538 scheduler_factory.cc:64] [shm_dispatcher_test] No sched conf found, use default conf.
I1217 19:05:46.955749 22540 processor.cc:80] [shm_dispatcher_test] processor_tid: 22540
I1217 19:05:46.955791 22541 processor.cc:80] [shm_dispatcher_test] processor_tid: 22541
I1217 19:05:46.955855 22542 processor.cc:80] [shm_dispatcher_test] processor_tid: 22542
I1217 19:05:46.955862 22543 processor.cc:80] [shm_dispatcher_test] processor_tid: 22543
I1217 19:05:46.955871 22544 processor.cc:80] [shm_dispatcher_test] processor_tid: 22544
I1217 19:05:46.955884 22545 processor.cc:80] [shm_dispatcher_test] processor_tid: 22545
I1217 19:05:46.955936 22546 processor.cc:80] [shm_dispatcher_test] processor_tid: 22546
I1217 19:05:46.955956 22547 processor.cc:80] [shm_dispatcher_test] processor_tid: 22547
I1217 19:05:46.956005 22548 processor.cc:80] [shm_dispatcher_test] processor_tid: 22548
I1217 19:05:46.956007 22549 processor.cc:80] [shm_dispatcher_test] processor_tid: 22549
I1217 19:05:46.956053 22550 processor.cc:80] [shm_dispatcher_test] processor_tid: 22550
I1217 19:05:46.956061 22552 processor.cc:80] [shm_dispatcher_test] processor_tid: 22552
I1217 19:05:46.956068 22551 processor.cc:80] [shm_dispatcher_test] processor_tid: 22551
I1217 19:05:46.956077 22553 processor.cc:80] [shm_dispatcher_test] processor_tid: 22553
I1217 19:05:46.956094 22554 processor.cc:80] [shm_dispatcher_test] processor_tid: 22554
I1217 19:05:46.956109 22538 init.cc:104] [shm_dispatcher_test] Register exit handle succ.
I1217 19:05:46.956110 22555 processor.cc:80] [shm_dispatcher_test] processor_tid: 22555
I1217 19:05:46.956137 22538 notifier_factory.cc:40] [shm_dispatcher_test] [DEBUG] notifier type: multicast
I1217 19:05:46.956142 22538 multicast_notifier.cc:122] [shm_dispatcher_test] [DEBUG] multicast notifier ip: 239.255.0.100
I1217 19:05:46.956144 22538 multicast_notifier.cc:123] [shm_dispatcher_test] [DEBUG] multicast notifier port: 8888
I1217 19:05:46.956209 22538 notifier_factory.cc:40] [shm_dispatcher_test] [DEBUG] notifier type: multicast
I1217 19:05:46.956403 22538 dispatcher.h:106] [shm_dispatcher_test] [DEBUG] new reader for channel:
I1217 19:05:46.956465 22538 notifier_factory.cc:40] [shm_dispatcher_test] [DEBUG] notifier type: multicast
I1217 19:05:46.956636 22538 segment.cc:221] [shm_dispatcher_test] [DEBUG] open or create true.
I1217 19:05:46.956641 22538 shm_transmitter.h:114] [shm_dispatcher_test] [DEBUG] block index: 0
I1217 19:05:46.956645 22538 shm_transmitter.h:133] [shm_dispatcher_test] [DEBUG] Writing sharedmem message:  to block: 0
I1217 19:05:47.056414 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.056432 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.156553 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.156569 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.256721 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.256737 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.356889 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.356904 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.457056 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.457072 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.557191 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.557207 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.657362 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.657378 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.757521 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.757537 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.857714 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.857730 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:47.956838 22538 dispatcher.h:106] [shm_dispatcher_test] [DEBUG] new reader for channel:
I1217 19:05:47.956893 22538 shm_transmitter.h:114] [shm_dispatcher_test] [DEBUG] block index: 1
I1217 19:05:47.956910 22538 shm_transmitter.h:133] [shm_dispatcher_test] [DEBUG] Writing sharedmem message:  to block: 1
I1217 19:05:47.957871 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:47.957880 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.057999 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.058015 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.158164 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.158180 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.258347 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.258363 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.358484 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.358498 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.458648 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.458664 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.558813 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.558830 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.658973 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.658989 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.759131 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.759148 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.859336 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.859352 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.957141 22538 segment.cc:309] [shm_dispatcher_test] [DEBUG] remove success.
I1217 19:05:48.959493 22556 multicast_notifier.cc:99] [shm_dispatcher_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:48.959501 22556 shm_dispatcher.cc:106] [shm_dispatcher_test] [DEBUG] listen failed.
I1217 19:05:48.959667 22538 dispatcher.cc:29] [shm_dispatcher_test] [DEBUG] Shutdown

**Comment by CapLeo2009** [comment]
### Debug log for shm_transceiver_test:
Log file created at: 2019/12/17 19:05:32
Running on machine: in_cyber_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1217 19:05:32.296418 22513 scheduler_factory.cc:64] [shm_transceiver_test] No sched conf found, use default conf.
I1217 19:05:32.296713 22515 processor.cc:80] [shm_transceiver_test] processor_tid: 22515
I1217 19:05:32.296727 22516 processor.cc:80] [shm_transceiver_test] processor_tid: 22516
I1217 19:05:32.296783 22517 processor.cc:80] [shm_transceiver_test] processor_tid: 22517
I1217 19:05:32.296829 22518 processor.cc:80] [shm_transceiver_test] processor_tid: 22518
I1217 19:05:32.296836 22519 processor.cc:80] [shm_transceiver_test] processor_tid: 22519
I1217 19:05:32.296882 22520 processor.cc:80] [shm_transceiver_test] processor_tid: 22520
I1217 19:05:32.296885 22521 processor.cc:80] [shm_transceiver_test] processor_tid: 22521
I1217 19:05:32.296890 22522 processor.cc:80] [shm_transceiver_test] processor_tid: 22522
I1217 19:05:32.296953 22523 processor.cc:80] [shm_transceiver_test] processor_tid: 22523
I1217 19:05:32.296985 22524 processor.cc:80] [shm_transceiver_test] processor_tid: 22524
I1217 19:05:32.296993 22525 processor.cc:80] [shm_transceiver_test] processor_tid: 22525
I1217 19:05:32.297005 22526 processor.cc:80] [shm_transceiver_test] processor_tid: 22526
I1217 19:05:32.297075 22527 processor.cc:80] [shm_transceiver_test] processor_tid: 22527
I1217 19:05:32.297080 22528 processor.cc:80] [shm_transceiver_test] processor_tid: 22528
I1217 19:05:32.297098 22529 processor.cc:80] [shm_transceiver_test] processor_tid: 22529
I1217 19:05:32.297102 22513 init.cc:104] [shm_transceiver_test] Register exit handle succ.
I1217 19:05:32.297106 22530 processor.cc:80] [shm_transceiver_test] processor_tid: 22530
I1217 19:05:32.297142 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.297147 22513 multicast_notifier.cc:122] [shm_transceiver_test] [DEBUG] multicast notifier ip: 239.255.0.100
I1217 19:05:32.297148 22513 multicast_notifier.cc:123] [shm_transceiver_test] [DEBUG] multicast notifier port: 8888
I1217 19:05:32.297211 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.297358 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.297363 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.297430 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.297433 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.297446 22513 dispatcher.h:106] [shm_transceiver_test] [DEBUG] new reader for channel:
I1217 19:05:32.297654 22513 segment.cc:221] [shm_transceiver_test] [DEBUG] open or create true.
I1217 19:05:32.297659 22513 shm_transmitter.h:114] [shm_transceiver_test] [DEBUG] block index: 0
I1217 19:05:32.297665 22513 shm_transmitter.h:133] [shm_transceiver_test] [DEBUG] Writing sharedmem message:  to block: 0
I1217 19:05:32.397433 22531 multicast_notifier.cc:99] [shm_transceiver_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:32.397450 22531 shm_dispatcher.cc:106] [shm_transceiver_test] [DEBUG] listen failed.
I1217 19:05:32.397843 22513 segment.cc:148] [shm_transceiver_test] [DEBUG] shm already exist, open only.
I1217 19:05:32.398036 22513 segment.cc:298] [shm_transceiver_test] [DEBUG] open only true.
I1217 19:05:32.398046 22513 shm_transmitter.h:114] [shm_transceiver_test] [DEBUG] block index: 1
I1217 19:05:32.398084 22513 shm_transmitter.h:133] [shm_transceiver_test] [DEBUG] Writing sharedmem message:  to block: 1
I1217 19:05:32.497602 22531 multicast_notifier.cc:99] [shm_transceiver_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:32.497619 22531 shm_dispatcher.cc:106] [shm_transceiver_test] [DEBUG] listen failed.
I1217 19:05:32.498291 22513 segment.cc:329] [shm_transceiver_test] [DEBUG] destroy.
I1217 19:05:32.498309 22513 shm_transmitter.h:103] [shm_transceiver_test] [DEBUG] not enable.
I1217 19:05:32.498317 22513 notifier_factory.cc:40] [shm_transceiver_test] [DEBUG] notifier type: multicast
I1217 19:05:32.498365 22513 shm_transmitter.h:114] [shm_transceiver_test] [DEBUG] block index: 2
I1217 19:05:32.498405 22513 shm_transmitter.h:133] [shm_transceiver_test] [DEBUG] Writing sharedmem message:  to block: 2
I1217 19:05:32.597769 22531 multicast_notifier.cc:99] [shm_transceiver_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:32.597786 22531 shm_dispatcher.cc:106] [shm_transceiver_test] [DEBUG] listen failed.
I1217 19:05:32.598546 22513 segment.cc:148] [shm_transceiver_test] [DEBUG] shm already exist, open only.
I1217 19:05:32.598700 22513 segment.cc:298] [shm_transceiver_test] [DEBUG] open only true.
I1217 19:05:32.598704 22513 shm_transmitter.h:114] [shm_transceiver_test] [DEBUG] block index: 3
I1217 19:05:32.598718 22513 shm_transmitter.h:133] [shm_transceiver_test] [DEBUG] Writing sharedmem message:  to block: 3
I1217 19:05:32.697952 22531 multicast_notifier.cc:99] [shm_transceiver_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:32.697968 22531 shm_dispatcher.cc:106] [shm_transceiver_test] [DEBUG] listen failed.
I1217 19:05:32.698899 22513 shm_transmitter.h:114] [shm_transceiver_test] [DEBUG] block index: 4
I1217 19:05:32.698945 22513 shm_transmitter.h:133] [shm_transceiver_test] [DEBUG] Writing sharedmem message:  to block: 4
I1217 19:05:32.798121 22531 multicast_notifier.cc:99] [shm_transceiver_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:32.798136 22531 shm_dispatcher.cc:106] [shm_transceiver_test] [DEBUG] listen failed.
I1217 19:05:32.799119 22513 segment.cc:329] [shm_transceiver_test] [DEBUG] destroy.
I1217 19:05:32.799142 22513 segment.cc:309] [shm_transceiver_test] [DEBUG] remove success.
I1217 19:05:32.799203 22513 dispatcher.cc:29] [shm_transceiver_test] [DEBUG] Shutdown
I1217 19:05:32.898288 22531 multicast_notifier.cc:99] [shm_transceiver_test] [DEBUG] timeout, no readableinfo.
I1217 19:05:32.898304 22531 shm_dispatcher.cc:106] [shm_transceiver_test] [DEBUG] listen failed.

**Comment by ctwfei** [comment]
Hi CapLeo2009,

After ensuring that CYBER_IP is consistent with your docker container's IP address, can you help to grab the packet to see if the notification of SHM is sent?

You can refer to the command below：
**sudo tcpdump host 192.168.100.117 and udp**

**Comment by CapLeo2009** [comment]
@ctwfei Thanks for reply.
I noticed my docker container didn't have an IP address. When `docker inspect apollo_cyber_liulie`, here is the result for "NetworkSettings":
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a1f70294ed9a976b74428538e7103a8fae97cc88a8838a8d6c7521bb60d2674a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "148c1da04740790ac281dcb0039d7da7bf865acbedc1adf5c5d27507fb834113",
                    "EndpointID": "d90b03e2b0ecac6ab719943984d3148cf4d00eb3d461ed2f45eda7dd2fcb9c9d",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
```
You can see "IPAddress" is "". Is this the point to cause the test fail?

**Comment by CapLeo2009** [comment]
@ctwfei When I changed line 253 of `/apollo/docker/scripts/cyber_start.sh` from `--net host` to `--net bridge` to give the container an IP address, all the tests passed. So there maybe a issue when create docker network in `/apollo/docker/scripts/cyber_start.sh`.

**Comment by ctwfei** [comment]
Hi CapLeo2009,


Glad you got it resolved. 
Btw, If you don't need multiple hosts communication, there is no need to modify the Cyber_ip and cyber_start sh.
