### ISSUE TITLE
How to check /tf_static tree with Cyber RT?

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10538]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

Hello all,

I am using Apollo 3.5 and Apollo 5.0.
I have problems regarding that the pose cannot be get when I launch the perception module.
How I can check the tree of /tf_static or /tf with Cyber RT framework?

**Comment by unacao** [comment]
See if this is what you need https://github.com/ApolloAuto/apollo/blob/bf2b3730835fd5a98f91a5fb00f9d82ef750be9d/docs/cyber/CyberRT_Developer_Tools.md#cyber_monitor
