### ISSUE TITLE
msg_exporter can not find transform

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10539]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

What I have done so far:

cyber_launch start /apollo/modules/transform/launch/static_transform.launch

./bazel-bin/modules/perception/lidar/tools/exporter/msg_exporter /apollo/modules/perception/lidar/tools/exporter/export_msg.config

cyber_recorder play -f some_file.record

My record file has 2 topics:
/apollo/localization/pose
/apollo/sensor/velodyne64/compensator/PointCloud2

export_msg.config contains:
/apollo/sensor/velodyne64/compensator/PointCloud2 velodyne64 1
/apollo/localization/pose velodyne64 1

after playing the record file the terminal where the msg_exporter is running throws me following errors:

![error2](https://user-images.githubusercontent.com/28162524/71004079-e16d7980-20e1-11ea-87a8-3d0715dd8de4.png)

I think I might change some configs but not sure which ones and what exactly is needed to make it work

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
