### ISSUE TITLE
[BUGGY?] indexed_queue.h Clear changes fixed size queue to infinite

### ISSUE THREAD

**Issue by histfuture** [ApolloAuto/apollo#10537]
IndexedQueue in indexed_queue.h provided a fixed size queue.
The capacity is not means the size of the container but the max element number of such queue.
However when call clear to remove all elements in such queue, the clear method change the queue capacity to 0 which means this queue support inserting infinity elements into the queue.

Buggy code as follows:
![image](https://user-images.githubusercontent.com/2638853/70979518-b2d3ac80-20a9-11ea-966c-e535e1c4d465.png)

**Comment by histfuture** [comment]
@natashadsouza  Any updates?

**Comment by jmtao** [comment]
@histfuture good catch. it was fixed. 
thanks for supporting Apollo!
