### ISSUE TITLE
Add vcan support for socket_can_client_raw

### ISSUE THREAD

**Issue by james-goin** [ApolloAuto/apollo#10546]
Adding an option for 'vcan' (virtual socket can) would be very beneficial for running the system in our simulation. We currently use this and would be a great public feature. 

The update would only require changing "can" to "vcan" on line 100 shown in figure below.

![image](https://user-images.githubusercontent.com/43549783/71131018-54412800-21a8-11ea-931a-b959ddafe7ff.png)

This could either be set during the build or an additional socket client for virtual busses could be added to the component for this.

**Comment by Capri2014** [comment]
@james-goin My understanding is that you would also need to setup/bring up `vcan` as well right? Anything else you thing of that might needs a change?

**Comment by james-goin** [comment]
Correct. 

Example: 
![image](https://user-images.githubusercontent.com/43549783/71202307-ca00ce80-2250-11ea-9e58-4bf1add14479.png)

**Comment by Capri2014** [comment]
@james-goin This is a valid suggestion that can help improve the simulation with canbus module in loop! Through we did not do it this way.  -- Could you help create a PR for this one? You can add another conf in https://github.com/ApolloAuto/apollo/blob/bb72a22bd1fc461c960713cec3c3cdc370b4c53a/modules/drivers/canbus/proto/can_card_parameter.proto#L27 and use it to select between paring in "can" or "vcan" depending on the conf. The new conf can be either string type or boolean type but I would prefer boolean type with name "enable_virtual_can". 

I will see what is the best way to setup/bringup vcan in scripts. 

Or if you think there is a better way or alternative suggestion, please also post it here.

**Comment by james-goin** [comment]
@Capri2014 It appears rx filters are not supported by virtual CAN. 

https://github.com/ApolloAuto/apollo/blob/d547687f8d1e6b37c97421923aa6f507dd6b9e1c/modules/drivers/canbus/can_client/socket/socket_can_client_raw.cc#L76-L89

I am currently not setting this flag when using virtual CAN bus and the system is operating correctly with our simulator / tests. Is there any reason this is needed for vcan (or socket CAN in general)? It doesn't appear to be actually filtering anything. 

If not would you prefer it was removed or just not set during virtual CAN?

**Comment by james-goin** [comment]
@Capri2014 Any updates on adding an automated way to bring up / set up vcan? Not sure if this can be added to the docker or done with a flag somewhere?
