### ISSUE TITLE
Where is the dataset to test perception offline?

### ISSUE THREAD

**Issue by Autofoxsys** [ApolloAuto/apollo#10544]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- Follow the guide here:https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md

I'm trying to run the perception module offline on my PC.  In following the "how-to" guide there are two things that are unclear to me.

1. In Step 7: "if the image is compressed"- what _image_ are you talking about?  The term image already has numerous meanings in this context.
 2. In Step 9: "Play your recorded bag".  Ok, but I don't have any recorded bag.   I do have a folder called **/apollo/data/bag** (which presumably contains cyberrt bags and not rosbags?).  In that folder I have a number of other folders where the folder names are derived from recent dates but I honestly have no idea how they got there (did I inadvertently create these files somehow?).

In any case, if I try to "play" any of the __record__ files contained in these folders (as described in step 9) I get error messages about the timestamps.

So, if I want to run perception offline, where can I find some data to feed the Apollo pipeline?  I can play (using cyber_recorder) the file  **/apollo/docs/demo_guide/demo_3.5.record** but that doesn't contain any video data and I need video data.

I suppose one of the difficulties is that I don't see how cyberRT tools would allow me to assemble my own __record__ file that I could use to feed the pipeline.

I can't access the apollo open(ish) dataset because to do that I would need to create an account with Baidu and I need to have a mobile phone in one of number of specific countries (most of Europe is not covered)

Any info please?

**Comment by Autofoxsys** [comment]
I'm going to partially answer my own questions:
1. I believe that the "image" in question refers to the __stream of images__ (originally) generated by one or more of the on-vehicle cameras.  So it's referring to the video data in the dataset which may be stored as a sequence of compressed JPEG images.

2. The data I found in the **/apollo/data/bag** folder was generated by me when I played back the  **/apollo/docs/demo_guide/demo_3.5.record** file that I mentioned in the original post.

As for getting data to feed the **whole** Apollo pipeline (including perception) I finally found that LG's open source simulator (LGSVL) is a good option for that.  It can be run on another machine and the simulated sensor data sent via ethernet (assuming that you don't want to add too many high data rate sensors).  That way you can see exactly what you're sending to Apollo.

**Comment by jimaldon** [comment]
@Autofoxsys did you get the link between LGSVL and Apollo working? How does your pipeline work? Do you manually drive around on LGSVL and create a `.record` file which you then play in apollo using `cyber_recorder` and simply view the planning and control output on dreamviewer? Or do you run things online with the control output from Apollo sent back to LGSVL?
