### ISSUE TITLE
use_sim_time supprt in cyber

### ISSUE THREAD

**Issue by xhzzhang** [ApolloAuto/apollo#10552]
**Is your feature request related to a problem? Please describe.**
ros have rosparam 'use_sim_time' to set system time from rosbag time, now hope it in cyber.

**Describe the solution you'd like**
add new tool 'cyber_param' to set same option 'use_sim_time'.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by daohu527** [comment]
Currently supported
