### ISSUE TITLE
Is it possible to give a list of readings on which this work is based on

### ISSUE THREAD

**Issue by man-csl** [ApolloAuto/apollo#10566]
It would be great if we can get pointers to research on which the work of Apollo is based on. I can see that a reference is given for localization, but nothing much is mentioned for other areas.

**Comment by kevin-y-wang** [comment]
For the related tech background, please refer to the online free course: Self-Driving Fundamentals: Featuring Apollo by Baidu Apollo
link: https://www.udacity.com/course/self-driving-car-fundamentals-featuring-apollo--ud0419
