### ISSUE TITLE
Problem with downloading full data set 

### ISSUE THREAD

**Issue by erfanroghani** [ApolloAuto/apollo#10572]
When I click on the download button at the end of this [page](http://apollo.auto/synthetic.html) and fill out the form, downloading the sample data starts but I want the full data set and I do not get any direct download link via my Email for that,

I tried this with different emails and checked the spams. 
How can I download the full dataset?

**Comment by jinghaomiao** [comment]
@GoLancer please help with that. Thanks!

**Comment by jinghaomiao** [comment]
Thanks for using Apollo. If you have any other issues, please open new ones.
