### ISSUE TITLE
some questions about using cyber_writer and cyber_time

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#10582]
Ubuntu 16.04 apollo5.0

I find a cyberRT python API: cyber_time.Rate.But I can't find any examples in apollo. 

I find an another method to set the rate, written in `rtk_player.py`:
```python
 while not cyber.is_shutdown():
        now = cyber_time.Time.now().to_sec()
        player.publish_planningmsg()
        sleep_time = 0.1 - (cyber_time.Time.now().to_sec() - now)
        if sleep_time > 0:
            time.sleep(sleep_time)
```
My question is that can I use `cyber_time.Rate(100)` to set the rate? 
```python
rate = cyber_time.Rate(100)
while cyber.ok():
    # publish something
    rate.sleep()
```

**Comment by BigBenSure** [comment]
I also find some code in `navigator.py`,using `rospy`:
```python
r = rospy.Rate(0.5)  # 0.5hz
while not rospy.is_shutdown():
    r.sleep()
    navigation_pub.publish(navigation_info)
    r.sleep()
    break
```
Is cyberRT API completely replace the ros API ?

**Comment by lorugant04** [comment]
HI, is cyber_time.Rate() really used to set Frame ratio while logging in cyber monitor? Please let me know. Thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
