### ISSUE TITLE
Cannot read message  from channel in timer_component_example.cc

### ISSUE THREAD

**Issue by xuming7up** [ApolloAuto/apollo#10585]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04/16.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5)**:

### Steps to reproduce the issue:
In file timer_component_example.h add variable declaration:
std::shared_ptr<Reader<Driver>> driver_reader_ = nullptr;

In file timer_component_example.cc, add reader code.
bool TimerComponentSample::Init() {
  driver_writer_ = node_->CreateWriter<Driver>("/carstatus/channel");
  **+driver_reader_ = node_->CreateReader<Driver>("/carstatus/channel", [this](const 
  +std::shared_ptr<Driver>& diver)** 
  +{
     +AERROR << "Received driver data with reader.";
  +});
  
  return true;
}

bool TimerComponentSample::Proc() {
  static int i = 0;
  **+usleep(30000);//sleep 30ms**
  auto out_msg = std::make_shared<Driver>();
  out_msg->set_msg_id(i++);
  driver_writer_->Write(out_msg);
  AINFO << "timer_component_example: Write drivermsg->"
        << out_msg->ShortDebugString();
  return true;
}
In time.dag file:
interval : 10

1.add usleep(30000)
#mainboard -d cyber/examples/timer_component_example/timer.dag
receive serveral print message "Received driver data with reader", and the mainboard program no longer print any message, it looks got stuck.

2. remove usleep(30000) or change interval : 10 to 40
#mainboard -d cyber/examples/timer_component_example/timer.dag
receive print message "Received driver data with reader" continuously.

so, the question is: why reader message get stuck when proccess time > interval value.
how to resolve this issue.
Thanks ahead.

**Comment by daohu527** [comment]
You set TimerComponentSample period 10ms, which means it try to run the "proc" in 10ms period. But you add a sleep 30ms in the "proc". so there will be a error!!! **How can you guarantee that the program can be executed every 10ms after 30ms of sleep**?

Best not to add blocking operate in proc.

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
