### ISSUE TITLE
Cyber Test: file_test

### ISSUE THREAD

**Issue by wutianze** [ApolloAuto/apollo#10583]
**Describe the bug**
My environment is Ubuntu16.04, and I build a docker for cyber following CyberRT_Docker.md. When run 
```
./apollo.sh build_cyber
bazel test cyber/...
```
I met the Failed test: //cyber/common:file_test.
The detail shows:
Cyber/common/file_test.cc:75: Failure
Value of: CopyFile("message.binary","/not_exists_file")
 Actual:true
Expected:false

I think the problem is that I run the command as root, so 'cp -r message.binary /not_exists_file' can be successful. But users usually enter the container as root and when they test cyber they will fail(the docker needs root permission to run in default, so the script cyber_into.sh will log in as root).

The solution may be changing the EXPECT_FALSE to EXPECT_TRUE or just remove the case because it's meaningless. Or you may better add the requirement to run the test process as a different user from root.

**To Reproduce**
Just follow CyberRT_Docker.md steps

**Expected behavior**
One test fails

**Desktop (please complete the following information):**
 - OS: Ubuntu16.04

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
