### ISSUE TITLE
Update apollo-contrib for Linux kernel 5.0

### ISSUE THREAD

**Issue by anchans** [ApolloAuto/apollo#10586]
Ubuntu 18.04 now comes default with kernel 5.0. Please update the kernel code in apollo-contrib to fix errors encountered while building it on the new kernel.

Thanks

**Comment by hugomatic** [comment]
Is there a work around for this issue so that we can use Ubuntu 18.04 in the cars?

**Comment by hugomatic** [comment]
Pinging this issue again: how can we upgrade our cars to Ubuntu 18.04 (supported by Apollo) without kernel 5.0 support?

**Comment by storypku** [comment]
> Is there a work around for this issue so that we can use Ubuntu 18.04 in the cars?

Hi @anchans  and @hugomatic,  we have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. 

As for kernel code in Apollo-contrib, we will look into them in the next few months.

Thank you.

**Comment by storypku** [comment]
Updating basa driver for 5.x kernels is done in PR https://github.com/ApolloAuto/apollo-contrib/pull/29 . The issue here will be closed.
