### ISSUE TITLE
Cannot install Apollo in Nvidia Jetson

### ISSUE THREAD

**Issue by ankitdgolatkar** [ApolloAuto/apollo#10596]
I have a Nvidia Jetson. I have installed the Docker. When i try to execute "bash docker/scripts/dev_start.sh" I get the following error 
```

Cannot find device "can0"
Cannot find device "can0"
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.9.140-tegra
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.9.140-tegra
[INFO] Starting docker container "apollo_dev_root" ...
[WARNING] No nvidia-driver found! Use CPU.

```

I have all the drivers. I dont see what the issue is

**Comment by baofuwu** [comment]
The same error I met in AGX Xavier.
and I try run apollo in x86 base machine, it also shows me the "FATAL"error
```
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.13.0-32-generic
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.13.0-32-generic
```
I don't konw why and hope for a reply.

**Comment by storypku** [comment]
> The same error I met in AGX Xavier.
> and I try run apollo in x86 base machine, it also shows me the "FATAL"error
> 
> ```
> modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.13.0-32-generic
> modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.13.0-32-generic
> ```
> 
> I don't konw why and hope for a reply.

As a workaround, try disable `setup_device` call in `dev_start.sh`

**Comment by nhatuan84** [comment]
i am still getting this error is latest version (master). do you solve it?

**Comment by storypku** [comment]
> do you solve it?

What Jetson board are you running Apollo on? It should have been fixed for Apollo 6.0.

**Comment by nhatuan84** [comment]
I install it on PC not Xavier. Apollo 6.0 can not run but Apollo 5.5 is ok.

**Comment by storypku** [comment]
> I install it on PC not Xavier. Apollo 6.0 can not run but Apollo 5.5 is ok.

You meant you install Apollo on an arm64 PC ?

**Comment by nhatuan84** [comment]
Thank you for your reply. 
I mean x86 PC + Nvidia GTX1050

**Comment by storypku** [comment]
> hank you for your reply.
> I mean x86 PC + Nvidia GTX1050
Could you please describe your the steps you performs and the error messages ?

**Comment by nhatuan84** [comment]
Thank for you kindness. I will try again first and request the help later.

**Comment by storypku** [comment]
> Thank for you kindness. I will try again first and request the help later.

OK. Since this issue was about installing Apollo on Nvidia Jetson series, and has been resolved in the master HEAD, it is going to be closed. Please feel free to create a new issue if you have problems installing Apollo on x86_64 PC.

**Comment by nhatuan84** [comment]
I can run it now. although it shows the error dreamview is failed but actually it is running under http://ip_address:8888
