### ISSUE TITLE
关于MPC控制器自适应的问题

### ISSUE THREAD

**Issue by Shaquille-Wu** [ApolloAuto/apollo#10595]
仔细阅读了MPC部分的代码，横向控制的动力学模型是跟纵向速度（Vx）相关的。实际工况下，汽车的纵向速度是时刻变化的。这样就有一个问题，如果配置文件中设定了固定的Q和R的权重参数，可以想象的是，这个动力学模型将很难适应不同速度（Vx）的工况。我在apollo公开的源码中也没有找到相应的代码。我想请教的是，apollo的老师能不能把apollo的MPC如何自适应Vx的原理解释一下，或者这部分的源码在哪个文件中？

**Comment by kevin-y-wang** [comment]
Apollo平台没有对MPC控制器增益进行针对Vx的自适应设计，因为对于快速变化的Vx，自适应控制不能做到及时收敛
MPC控制器利用Gain_Schedule的方法对于不同速度区间（可在配置文件中设置若干个速度区间）的状态进行修正，来达到修正增益的目的。细节请见LoadMPCGainScheduler()

**Comment by Shaquille-Wu** [comment]
谢谢
