### ISSUE TITLE
there is no 

### ISSUE THREAD

**Issue by luanjinlu** [ApolloAuto/apollo#10609]
**Describe the bug**
there is no script "apollo/scripts/ndt_local_map_creator.sh" for create ndt map.

**Comment by mchmu** [comment]
where can i find the script "apollo/scripts/ndt_local_map_creator.sh"?. thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
