### ISSUE TITLE
Add flag for HMI nodes to ignore "Setup" starting the module

### ISSUE THREAD

**Issue by james-goin** [ApolloAuto/apollo#10605]
It would be great to have an option for a module to not be auto started when then the "Setup" button is pressed on the Dreamview page. This flag could be given in the HMI.

**Comment by hugomatic** [comment]
Yes, 

For example, we have a joystick control node that shouldn't autostart, but may want to have running later. Same with video encoders nodes.

**Comment by ycool** [comment]
Depending on which HMI mode you'd like to change, you can change the "Setup" button module config at https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt.
