### ISSUE TITLE
Can't transfer protobuf msg across multiple machines

### ISSUE THREAD

**Issue by e-guy** [ApolloAuto/apollo#10616]
# Protobuf msg cannot be transferred across multiple machines

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.0)**:

### Steps to reproduce the issue:
we want to run a proto msg talker / listener system across two machines, named marvin and hal
### 1. in marvin (the master machine):
```
in_dev_docker:/apollo$ export ROS_MASTER_URI=http://192.168.1.102:11311
in_dev_docker:/apollo$ export ROS_IP=192.168.1.102

in_dev_docker:/apollo$ ./scripts/roscore.sh

```
### 2. in hal
```
in_dev_docker:/apollo$ export ROS_MASTER_URI=http://192.168.1.102:11311
in_dev_docker:/apollo$ export ROS_IP=192.168.1.107

in_dev_docker:/apollo$ rosbag play chassis_data.bag
```
```
in_dev_docker:/apollo$ export ROS_MASTER_URI=http://192.168.1.102:11311
in_dev_docker:/apollo$ export ROS_IP=192.168.1.107

in_dev_docker:/apollo$ rostopic echo /apollo/canbus/chassis
(printed msg...)
```

### 3. in marvin (the master machine):
```
in_dev_docker:/apollo$ export ROS_MASTER_URI=http://192.168.1.102:11311
in_dev_docker:/apollo$ export ROS_IP=192.168.1.102

in_dev_docker:/apollo$ rostopic echo /apollo/canbus/chassis
(nothing printed out ???) ISSUE HERE
```

I wroted a chassis subscriber node to listen to this msg, the chassis callback function cannot be triggered too. 

### 2. By using wireshark, I found chassis data is transferred from machine **hal** into machine **marvin**

![Screenshot from 2020-01-11 13-48-16](https://user-images.githubusercontent.com/25145810/72199599-1b2f6700-3479-11ea-8a31-615056cfa498.png)

![Screenshot from 2020-01-11 13-51-44](https://user-images.githubusercontent.com/25145810/72199634-92fd9180-3479-11ea-9cc3-e39ac4c170b8.png)

**Comment by GerogeZero** [comment]
I encountered the same problem，
I need to transfer the pointcloud data from one computer to another computer. The rostopic list can see the node but there is no msg data

**Comment by daohu527** [comment]
If it is a local area network, this is feasible, otherwise rely on bridge
