### ISSUE TITLE
TEST_PATH

### ISSUE THREAD

**Issue by zieitokk** [ApolloAuto/apollo#10617]
When I run this 
```sh
./apollo.sh test
```
It shows that the `TEST_PATH` error.
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
./apollo.sh build_opt_gpu
./apollo.sh test

### Supporting materials (screenshots, command lines, code/script snippets):

`external/bazel_tools/tools/test/test-setup.sh: line 169: 31693 Aborted (core dumped) "${TEST_PATH}" "$@"`

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
