### ISSUE TITLE
Apollo Open Data Platform not reachable

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10622]
Hello everyone,

unfortunately http://data.apollo.auto/ is not reachable anymore.
I would like to download sensor data to test lidar perception.

**Comment by zk5580752** [comment]
Please using this url for Apollo sensor data: http://apolloscape.auto/tracking.html

**Comment by mickeyouyou** [comment]
The page is offline, you can use the link below for rosbag data `demo-sensor-demo-apollo-1.5.bag`: https://drive.google.com/file/d/1Udezr__nUzEH3Dxw2eyo6NdSqEevMoSO/view

**Comment by GabrielZZZ** [comment]
Hi @mickeyouyou 
The link you provide is no longer available. Can you kindly provide another link to download this bag? Many thanks!!!
