### ISSUE TITLE
Could anyone provide demo file which contains lidar data?

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10621]
Hi all,

I would like to test lidar perception.
Could anyone provide a demo file which contains lidar data please?

Like demo-sensor-demo-apollo-1.5.bag or demo-sensor-apollo-2.0.bag ?

Best regards

**Comment by mickeyouyou** [comment]
You can find a Temporary solution : https://github.com/ApolloAuto/apollo/issues/10622#issuecomment-575575859
