### ISSUE TITLE
Apollo 5.0 trapped in a roundabout

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10630]
**Describe the bug**
Hi team, I'm currently playing around with [LGSVL](https://github.com/lgsvl/simulator) and their [forked Apollo 5.0](https://github.com/lgsvl/apollo-5.0). In the map called [shalun](https://github.com/lgsvl/Shalun), (map file available at [here](https://github.com/lgsvl/apollo-5.0/tree/simulator/modules/map/data/shalun)) there is a roundabout. 

![apollo-trapped-in-roundabout](https://user-images.githubusercontent.com/16061105/72421472-8780d200-37bb-11ea-9ac5-2d50a91011a0.png)

As shown in above picture, when I tried to ask Apollo to enter the roundabout at road from east side and exit from the north road, Apollo planned a path including a circle in the roundabout.

This is normal since I've checked the map file (base_map and routing_map). 
there is no direct link from east lane to north lane, so Apollo needs to drive at least one circle around the roundabout.

but the issue i found is that, when Apollo completed one circle, it tends to keep driving around the roundabout again and again instead of exiting to the north lane. as shown in the video ([google drive](https://drive.google.com/file/d/1TEEXjaDbkctFtq4UuxKx4HMTeHtApBdl/view?usp=sharing))
(apologizes that the video is pretty laggy. used the ubuntu 1804 built-in screencast.)

**To Reproduce**
1. setup the lgsvl simulator and apollo 5.0 environment
2. start shalun map 
3. drive the vehicle manually to roundabout entry lane from east
4. set destination to somewhere in the north exit lane
5. submit the destination and let it drive.

**Expected behavior**
Apollo should be able to drive out of the roundabout after one circle instead of trapped in it.

**Screenshots**
please see above video and screenshot.

**Desktop (please complete the following information):**
 - OS: UBUNTU 1804
 - Browser: Chrome
 - Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
I've also recorded a bag file with cyber_recorder available here
record_1 ([google drive](https://drive.google.com/file/d/1kYfvRiSN6d-5yacJSfXAr0ffp1Nyy-qK/view?usp=sharing))
record_2 ([google drive](https://drive.google.com/file/d/1ShHE3VPYVP-vv1AdXQti6-MGMT5X1oZI/view?usp=sharing))

Please help look it up. Thanks.

**Comment by Capri2014** [comment]
Thanks for the bug report! It is related to the vehicle projection on reference line. We are working on it to have a through fix for it. @jmtao
