### ISSUE TITLE
Debugging on MacOS 

### ISSUE THREAD

**Issue by mertmerci** [ApolloAuto/apollo#10637]
Hello, 

I'm new on these Apollo Projects. I just want to debug the project on my Mac, rather than using the PCs on my workspace. I see the image on the 'https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md' webpage, that planning.cc file is opened on a Mac. 

Can I also open and debug this file on my Mac? 
What do you suggest? 

Thank you for your time.

**Comment by ycool** [comment]
Mac is not in the formal supporting platform. If you want to try, you can search for some previous community Mac practice tips for Apollo.
