### ISSUE TITLE
How does map module work? How to communicate with map module?

### ISSUE THREAD

**Issue by Wang4758** [ApolloAuto/apollo#10652]
Dear Apollo team,

We are trying to create a new module which accesses data from map engine and cut the map with a sensing range. The module can be launched without any errors. But it cannot receive any data from the map engine. Could you please tell us how to access the map data?

**Comment by Jmdavison** [comment]
I'm wondering the same thing. When do the `/apollo/relative_map/` and `/apollo/navigation` messages fire?

Do these modules act as services that require a client to query them? I'm looking for a way to query Apollo for the geographic origin of the current map.

**Comment by zeyu-zha** [comment]
Hello Apollo team,

our college are trying to access the map data by using the map engine. Could you give us some guide about the map engine to access the map data?

**Comment by Jmdavison** [comment]
@zeyu-zha I found that if you are running a separate cyber RT module (such as listener example), you need to load the HDMap data from binary yourself. Look at `CreateMap` inside `HDMapUtil`, and try to locate the binary for the HDMap you would like to use.

**Comment by zeyu-zha** [comment]
@Jmdavison Thanks for answer. 
Sorry for not making my last questions so clearly. Basiclly, my aim is to convert the hdmap of San Francisco,  which used in Apollo 3.5 as default map, to a special data format for my own simulation software. And i have also written some prototype before, which can be used for the converting of the basic elements like center line and lane width from a apollo hdmapm which is in OpenDRIVE format.
So i guess that there are two methode for me.
1. Try to find out the xml file of the apollo hdmap in OpenDRIVE format of San Francisco.
    But i have already searched the whole "apollo-r3.5.0.zip" and do not find out the hdmap xml file.
    My question here is, where can i get the used hdmap xml file for San Francisco in Apollo 3.5?
2. Try to access the map engine APIs for extracting the map information of lanewidth, center line and so on. Or even try to export the map information with map engine APIs in some other format.
But here i do not know, if the map modules already support to export a user defined map file in Apollo 3.5 ?
Could someone tell us how to deal with the two mentioned methode above?

**Comment by daohu527** [comment]
You can convert the bin to txt format. I don't know if this meets your requirements
