### ISSUE TITLE
Classification information in /apollo/perception/obstacles

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10655]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

So I have a recordfile which has these topics:
/apollo/localization/pose
/apollo/sensor/velodyne64/compensator/PointCloud2

I am launching the static transform and perception module. After that I am play the recordfile, so I get messages published to /apollo/perception/obstacles.

When I go inside the message in cyber_monitor I can see no information regarding the heading, velocity and classification information as described here:
https://github.com/ApolloAuto/apollo/tree/master/modules/perception#output

There is only:

timestamp_sec
module_name
sequence_num
lidar_timestamp
camera_timestamp
radar_timestamp

I have another demo sensor dataset which also has some other topics like:

/apollo/prediction

Inside of this message I can find more information regarding perception_obstacle
(type, polygon, velocity, etc)

Why are those informations only published in /apollo/prediction and not in /apollo/perception/obstacles?

**Comment by ycool** [comment]
/apollo/prediction depends on /apollo/perception/obstacles data. From your description, the perception module can't identify any obstacles from your sensor data. You can check perception module log for more details.
