### ISSUE TITLE
Question: Documented perception module inputs doesn't match the implementation in dag files

### ISSUE THREAD

**Issue by SenRamakri** [ApolloAuto/apollo#10668]
Apollo README for Perception here https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md#input describes that Apollo uses 2 cameras and 4 lidars as Perception input sensors. But when we look at the code(master branch) things are configured differently.
For example, in camera.dag(https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/camera/dag/camera.dag) it enables 5 CameraComponents. Again, for Lidar, in velodyne.dag(https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/velodyne/dag/velodyne.dag), we can see that it configures/instantiates 5 VelodyneDriverComponents. 
Or if I assume that its velodyne128.dag it still doesnt match the configuration.

Or is this just a dummy configuration and the Apollo users with latest version are supposed to change this configuration according to the Perception documentation.

### System information
**Apollo version 5.5**:

### Steps to reproduce the issue:
N/A

### Supporting materials (screenshots, command lines, code/script snippets):
https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md#input
https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/camera/dag/camera.dag
https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/velodyne/dag/velodyne.dag

**Comment by ycool** [comment]
These dag files are demo configurations. Different vehicles will enable different configurations.
