### ISSUE TITLE
LGSVL Apollo 3.0 Localization&DreamView Extraction

### ISSUE THREAD

**Issue by kdr193** [ApolloAuto/apollo#10665]
Hello,
I am a newbie and I want to use only the localization and dreamview modules of LGSVL Apollo 3.0. I tried to extract these modules but it is more complicated than I thought. Can you guide me or provide a version of LGSVL Apollo 3.0 with only Localization and Dreamview.
Thanks in advance.

**Comment by ntutangyun** [comment]
how about only running dreamview and localization module, with `cyber_launch start ...`, instead of `bootstrap.sh` everything ?

**Comment by unacao** [comment]
Did the suggestion above solve your question? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
