### ISSUE TITLE
Apollo's tests documentations 

### ISSUE THREAD

**Issue by salmanee** [ApolloAuto/apollo#10673]
Hi everyone, 

I'm trying to get a better understanding of how modules in Apollo are tested; how are the inputs/outputs generated, how to build an infrastructure to test a module, how to increase test coverage etc etc.

I tried looking for documentations that might assist me in this but I couldn't find anything. Is there anyway I can learn more about how Apollo is tested?

I'd really appreciate your help!

Thanks,

**Comment by ycool** [comment]
Apollo test is based on https://github.com/google/googletest. You can construct the input and output in each test case.
