### ISSUE TITLE
.vscode file does NOT automatically get downloaded under apollo-5.0 directory after git clone.

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#10675]
**Bug description**
The hidden file .vscode will NOT automatically get downloaded under apollo-5.0 directory, after installing Apollo-5.0 using `git clone --recurse-submodules https://github.com/lgsvl/apollo-5.0.git`

**To Reproduce**

1. Go to 'https://github.com/lgsvl/apollo-5.0'
2.Do all the steps till ''Cloning the Repository'' ([(https://github.com/lgsvl/apollo-5.0#cloning-the-repository)]) or even upto` ./apollo.sh build_gpu`. 
3.Check under your apollo-5.0 directory to see if you have .vscode file. 

**Expected behavior**
There should be a .vscode file under apollo-5.0 
Doing a  `ls -a| grep .vscode` should show the presence of it.

**Code snippet of correct behaviour**
```
abhi@cudus:~/apollo-5.0$ ls -a| grep vscode
.vscode
```

**Code snippet of anomolous behaviour**
```
mert@cudus:~/apollo-5.0$ ls -a| grep .vscode
mert@cudus:~/apollo-5.0$ ls -a| grep vscode
```

**Desktop :**
 - OS: Ubuntu 18.04
 - Driver Version: 430.64
 - CUDA Version: 10.1
 - Graphics Card: GeForce GTX 1080
 
**Additional context**
I think this is an important bug for Apollo-5.0, because its working fine for Apollo-3.5 (I mean .vscode gets downloaded automatically after the git clone command). In fact, it works sparingly for Apollo-5.0 as well. I said sparingly because I had installed Apollo-5.0 several times in several machines of identical configuration, and it had worked perfectly on most occasions, while on some, the .vscode was downloaded alright, but the tasks.json wasnt there under .vscode (See here:https://github.com/ApolloAuto/apollo/issues/10618).
In other cases, the .vscode wasnt there at all.

**Comment by xiaoxq** [comment]
1. We don't try to support specific-IDE as developers always have their own preference.
2. As a result, we add well-known IDE settings into gitignore: https://github.com/ApolloAuto/apollo/blob/master/.gitignore#L23
to avoid accident checking-in.

**Comment by Avps1** [comment]
Okay, thanks for your response. I was only using VSCode because of the guidelines of this page : [(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md#debugging-apollo-locally-using-vscode)] . 
So I think you are suggesting I remove .vscode from gitignore to make it work?

**Comment by xiaoxq** [comment]
Yeah, or simply "git add -f .vscode". It's OK to do it in your own fork.

**Comment by Avps1** [comment]
Thanks again. I am closing the issue now.

**Comment by Avps1** [comment]
Sorry for reopening the issue, but running `git add -f .vscode` in my own directory gave the following error : 
```
mert@cudus:~/apollo-5.0$ git add -f .vscode
fatal: pathspec '.vscode' did not match any files
```
I also commented out .vscode in the .gitignore file. Can you kindly suggest some other workaround to this problem?
