### ISSUE TITLE
Cannot run downloaded bag file to acquire lidar and radar data

### ISSUE THREAD

**Issue by alvaradoo** [ApolloAuto/apollo#10672]
When attempting to run the bag downloaded from #10622 I run into some issues. I am following the instructions on this page: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_offline_sequential_obstacle_perception_visualizer.md

The first command I run is: 
bazel build //modules/perception/tool/export_sensor_data:export_sensor_data

This command does not run and returns and error saying: 
"no such package 'modules/perception/tool/export_sensor_data': BUILD file not found on package path." is returned. 

I am unsure if this is a problem with the installed Apollo files or something else. 

Thank you!

**Comment by ycool** [comment]
This tool is deprecated in the master branch. You can find this tool at https://github.com/ApolloAuto/apollo/tree/r2.0.0/modules/perception/tool/export_sensor_data.
