### ISSUE TITLE
Real-time threads and their priorities

### ISSUE THREAD

**Issue by ahmedius2** [ApolloAuto/apollo#10680]
### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04 (without apollo-kernel)
- **Nvidia driver version**: 435.21
- **Apollo installed from**: source
- **Apollo version**: 5.0 LGSVL fork

Hi. I am trying to learn which tasks are running with real-time priority and their periods when Apollo is executing with the LGSVL simulator. I found a couple of .conf files under /apollo/cyber/conf directory which includes some information about tasks. However, I couldn't manage to learn which .conf files are being used and which threads are running with ps command. Also, I tried to analyze scheduling events by setting cyber_sched_perf=1 in the apollo_base.sh file but couldn't see any event report such as RT_CREATE with grepping all apollo directory. Could you help me to find the RT threads and their priorities when the system up and running with LGSVL simulator?

Thanks and regards.

**Comment by SenRamakri** [comment]
@ahmedius2 - I never tried LGSVL Apollo fork. But in Apollo mainline version each module runs as a separate "mainboard" processes. So, you may want to inspect all the "mainboard" processes and  look at the threads. You may also look at mainboard logs(usually present under /apollo/data/log) and see the log entries from the functions such as SetSchedAffinity/SetSchedPolicy to figure out scheduling policy/affinity for each thread-id . If this helps and if you can post your findings here, it would be helpful for others as well.

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
