### ISSUE TITLE
How to convert messages from record file in Python API ? 

### ISSUE THREAD

**Issue by RocketFlash** [ApolloAuto/apollo#10698]
I am trying to read .record file using RecordReader. It returns msg as bytes. I need to convert it to PointCloud object. How to do it in Python Cyber API  ?

**Comment by quning18** [comment]
@RocketFlash 

please checkout those examples below and see if it helps:

https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py/examples/record.py

**Comment by RocketFlash** [comment]
@quning18 Thank you!
