### ISSUE TITLE
百度是中国的公司，为何整个项目都用en？

### ISSUE THREAD

**Issue by lp276507556** [ApolloAuto/apollo#107]

**Comment by hyne-shan** [comment]
强烈要求多语言

**Comment by arrownj** [comment]
如果连英文文档都看不懂，还是改行算了吧。。。

**Comment by 303540023** [comment]
wo cai  6 年级 ，are 有  ok ？

**Comment by wunu** [comment]
手动掀桌

**Comment by lincanbin** [comment]
百度是一家在英属开曼群岛注册的美国上市公司。启动资金也主要是美资。
在中国大陆地区经营的只是特地在国内注册的一个子公司。

**Comment by lincanbin** [comment]
说是这么说，英语还是程序员必备技能，是与世界其他同行交流的通用工具，多学没坏。

**Comment by 20chase** [comment]
我同意，百度就应该用易语言编写才对嘛：)

**Comment by JakeWoki** [comment]
国内大公司的开源项目基本都有英文文档，可惜国外没人理，中文文档没写的国内也没什么人用。。。好尴尬

**Comment by catpanda** [comment]
国际公司就国际公司 你好歹搞一个中文版本 东京热都搞中文字幕了 不碍着你走向国际 把你们英文文档的中文初稿发出来可好？

**Comment by rainingmaster** [comment]
知乎观光团

**Comment by panqibao** [comment]
应该用cn

**Comment by dahwang22** [comment]
非常不理解为什么一行能写完也不长的代码非得写成两行？有谁解释一下么？

**Comment by daohu527** [comment]
现在已经有一些中文文档了，开源社区的繁荣需要大家公共建设，欢迎提交文档以及代码修改。
