### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by wangyixu14** [ApolloAuto/apollo#10700]
Hi all,

I am using google cloud computer VM with ubuntu 18.04 and Tesla T4 GPU. I successfully build the apollo 5.0 with lgsvl, but the modules seem not working for me.

![image](https://user-images.githubusercontent.com/34372413/73763193-b6dd8b80-4736-11ea-82d6-0942c94bf8b7.png).

I could successfully use nvidia-smi command in the docker, shown as:
![image](https://user-images.githubusercontent.com/34372413/73763462-0ae87000-4737-11ea-8263-6f108e35f644.png)

For the cyber_monitor:
![image](https://user-images.githubusercontent.com/34372413/73763563-323f3d00-4737-11ea-921f-f61b99afdc24.png)

For the perception.INFO shows as:
![image](https://user-images.githubusercontent.com/34372413/73763735-7a5e5f80-4737-11ea-96c3-035bdc2fcd28.png)

What should I do with error?

Thanks.

**Comment by uoonm** [comment]
how did you install nvidia driver within the docker environment??
Please Help!

**Comment by zhanghming** [comment]
@wangyixu14 Hello, how did you combine the LGSVL and Apollo 5.0 together in Ubuntu 18.04? Did you install LGSVL from source or from the binary one, I download the binary LGSVL and cann't execute it in my Ubuntu 18.04.

And I also wonder must I install the nvidia-driver in docker for run Apollo 5.0 in my local machine?

**Comment by unacao** [comment]
@rongguodong any comments from your side?

**Comment by rongguodong** [comment]
What is the error here? Perception module cannot be started? If you click "Perception" in Dreamview and it automatically goes back to grey, you can try to launch it manually using cyber_launch. It should show more error message in the console.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
