### ISSUE TITLE
Extremely low parallelism observed with Planning module

### ISSUE THREAD

**Issue by SenRamakri** [ApolloAuto/apollo#10701]
**Describe the bug**
We are observing that Planning module doesn't utilize 12-core x86 CPU as efficiently as it could.
Below is the VTune performance analyzer capture from running Planning module for 100+ seconds  using one of the pre-defined tests(Reverse Early Change Lane) in Simulation mode(Sim Control set to ON). As you can see out of 100+ seconds of test duration, for around 50+ seconds only one core was active, and then 2 cores are active for around 30 secs. Remaining time is mostly idle or may be few seconds 3 core usage and less beyond that. To me it appears 12 core CPU is not efficiently utilized by Planning module for the 80+ seconds when its not Idle. Also note that during this time system is not busy in terms of other cores not being available. Is this a known issue or as expected based on how algorithms are pipelined/sequentially executed in Planning module.

![planning_cpu_parallelization](https://user-images.githubusercontent.com/31017510/73771009-16da2f00-4743-11ea-9e1b-57c6f54d8dc6.PNG)

**To Reproduce**
1. Open Dreamview interface and run "Planning" module using Module Controller
2. Run VTune analyzer and attach to the Planning process and start the capture process( Use "Threading" or "Hotspots" analysis option ).
3. Run "Reverse Early Change Lane" in Simulation mode( Sim Control set to ON )
4. Stop the VTune capture when the test finishes.

**Expected behavior**
See the summary of VTune capture. It should show that there is not much parallelism in terms
of core usage, you could see 1-2 cores being used mostly.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox for Dreamview
 - Version: Ubuntu 18.04

**Comment by ycool** [comment]
It is expected for the current algorithm. More parallelism is in progress. Any help is welcome too.
