### ISSUE TITLE
D-kit : sample.gzip is missing for lidar calibration

### ISSUE THREAD

**Issue by zhxt** [ApolloAuto/apollo#10705]
**Describe the bug**
In D-kit document [Lidar_Based_Auto_Driving--Sensor_Calibration_cn](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Lidar_Based_Auto_Driving--Sensor_Calibration_cn.md)
Line 121:
```
下载[配置样例目录包](sample.gzip)并放置于apollo根目录下
```
The link is broken, there is no sample.gzip found under that path.

Please take a look, thx!

@lishuanghua @diegohu

**Comment by diegohu** [comment]
It was fixed in #10724
