### ISSUE TITLE
Could I use the apollo5.0 if I can't get the HDmap?

### ISSUE THREAD

**Issue by HTL2018** [ApolloAuto/apollo#10708]
First, thanks for your worderful code!   
### System information    
   
- **Linux Ubuntu 16.04**   
- **Apollo installed from source**    
- **Apollo version 5.0**    
  
### My  issue:   
- We want use the apollo5.0 in our car, but we can't get the HDmap, Could I use the Apollo5.0? And which version could do it or which version I can use it by little  change?      
      
Looking forward for your reply! Thank you very much!

**Comment by ycool** [comment]
You can either use relative map (NaviPlanning: https://github.com/ApolloAuto/apollo/blob/master/modules/planning/navi_planning.cc) or create a draft HDMap using: https://github.com/ApolloAuto/apollo/tree/master/modules/tools/create_map
