### ISSUE TITLE
How to add side cameras for a car and use them in perception module

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#10718]
We appreciate you go through Apollo documentation and search previous issues before creating a new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution: Linux Ubuntu 16.04):
- **Apollo installed from source:
- **Apollo version 5.0:

Hello all,

I just wanna add side and back cameras to a car and use their scenes in the preception module. Please help me out in this case.

Thank you so much.

**Comment by daohu527** [comment]
Adding extra cameras makes no difference in Apollo, you can try first and give feedback
