### ISSUE TITLE
Modifying the image size captured by the camera

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#10715]
### System information

- **OS Platform and Distribution: Linux Ubuntu 16.04**:
- **Apollo installed from (source or binary)**: I built Apollo 5.0
- **Apollo version **: Apollo 5.0

### Steps to reproduce the issue:
- I just need to modify the capturing image in the main camera. I want to reduce the width and height of the source image from the main camera. I do not know which file is for setting up the main camera. Is it in apollo-5.0/modules/perception/camera/lib? Which file? or a different folder?

**Comment by ycool** [comment]
You need to modify both the camera driver and perception config. Assume it is front_6mm camera, https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/camera/conf/camera_front_6mm.pb.txt and https://github.com/ApolloAuto/apollo/blob/master/modules/perception/data/params/front_6mm_intrinsics.yaml
