### ISSUE TITLE
Question about the traffic rule implementation of "keep clear"

### ISSUE THREAD

**Issue by zqzqz** [ApolloAuto/apollo#10710]
### System information

- **OS Platform and Distribution Linux Ubuntu 14.04 (Docker)**:
- **Apollo installed from source**:
- **Apollo version 5.0**:

### Steps to reproduce the issue:
I ran the simulation with `demo_2.0.record` on the map `sunnyvale_loop`. When approaching an intersection, from my understanding of the source code about keep_clear traffic rule, the AV should detect a `pnc_junction` instance and wait behind the stop line until the path ahead is clear. But from the logs, there is no `pnc_junction` instance at all. Experiments on other maps have similar results.

My question is:
Which scenario is the "keep clear" traffic rule designed for and how can I trigger the logic of "keep clear" (the related code in `planning/traffic_rules/keep_clear` and `planning/tasks/deciders/speed_decider`)?

### Supporting materials (screenshots, command lines, code/script snippets):

My log about "keep clear". (I manually change the log level from debug to warning)
```
W0202 17:56:38.474692   885 keep_clear.cc:74]  5, signal_11 60.593620267645441 61.293620255724512
W0202 17:56:38.474697   885 keep_clear.cc:89]  SIGNAL[signal_11] s[60.5936, 61.2936]
W0202 17:56:38.474706   885 keep_clear.cc:74]  2, CW_3 63.950350728766047 93.079868284002856
W0202 17:56:38.474710   885 keep_clear.cc:77]  CROSSWALK[CW_3] s[63.9504, 93.0799]
W0202 17:56:38.474714   885 traffic_decider.cc:150]  Applied rule KEEP_CLEAR
```

**Comment by jmtao** [comment]
@zqzqz pnc_junction was introduced by map in a later version. From the log you posted, I think it's not available in the map you are using.

**Comment by zqzqz** [comment]
Thanks for your reply! May I know which map supports pnc junction? Any examples?

**Comment by jmtao** [comment]
@zqzqz try map sunnyvale_big_loop or sunnyvale_with_two_offices

**Comment by zqzqz** [comment]
I decoded the maps and found that three sunnyvale maps contains "junction" instances but not "pnc_junction". San mateo map has "pnc_junction" and it works. Thanks!
