### ISSUE TITLE
Basa in apollo_contrib no longer works with Ubuntu 18

### ISSUE THREAD

**Issue by james-goin** [ApolloAuto/apollo#10720]
The basa kernel is not building / loading with Ubuntu 18. 

Open issues related to this: 
[https://github.com/ApolloAuto/apollo-contrib/issues/22](https://github.com/ApolloAuto/apollo-contrib/issues/22)
[https://github.com/ApolloAuto/apollo-contrib/issues/21](https://github.com/ApolloAuto/apollo-contrib/issues/21)

Is Ubuntu 18 currently supported? 

Thanks!

**Comment by hugomatic** [comment]
The timespec to timespec_64 is not the only issue. The compilation problem can be fixed but we then run into linking issues.

**Comment by chuang213** [comment]
more info about the system, Ubuntu, kernel and gcc?

Ubuntu 18.04.2 LTS+4.15.0-29-generic+gcc 7.4 have no problem from the tip

**Comment by storypku** [comment]
Updating basa driver for 5.x kernels is done in PR ApolloAuto/apollo-contrib#29 . The issue here will be closed.
