### ISSUE TITLE
Failed to create and run new components

### ISSUE THREAD

**Issue by ghost** [ApolloAuto/apollo#10726]
### System information

- **Ubuntu 18.04**:
- **Apollo installed from github**:
- **Apollo version 5.5**:

### Steps to reproduce the issue:
I followed this guide https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Quick_Start.md and after run the following commnad: cyber_launch start /apollo/cyber/examples/common_component_example/common.launch i ran into this errors:

[common ]  E0213 10:32:48.775310 20286 file.cc:73] [mainboard]Failed to open file /home/claudio/apollo/cyber/examples/common_component_example/common.dag in text mode.
[common ]  E0213 10:32:48.775413 20286 file.cc:99] [mainboard]Failed to open file /home/claudio/apollo/cyber/examples/common_component_example/common.dag in binary mode.
[common ]  E0213 10:32:48.775470 20286 file.cc:73] [mainboard]Failed to open file /home/claudio/apollo/cyber/examples/common_component_example/common.dag in text mode.
[common ]  E0213 10:32:48.775488 20286 file.cc:99] [mainboard]Failed to open file /home/claudio/apollo/cyber/examples/common_component_example/common.dag in binary mode.
[common ]  E0213 10:32:48.775501 20286 module_controller.cc:119] [mainboard]Get proto failed, file: /home/claudio/apollo/cyber/examples/common_component_example/common.dag
[common ]  E0213 10:32:48.775511 20286 module_controller.cc:67] [mainboard]Failed to load module: /home/claudio/apollo/cyber/examples/common_component_example/common.dag
[common ]  E0213 10:32:48.775528 20286 mainboard.cc:43] [mainboard]module start error.
[common ]  
[cyber_launch_20285] ERROR Process [common] has finished. [pid 20286, cmd mainboard -d /home/claudio/apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT].
 
Could you please help me to solve this problem?

**Comment by Martin20** [comment]
I have the same problem. Have you been able to solve it?

**Comment by quning18** [comment]
@ClaudioPedrosa @macDure 

have you guys ran "./apollo.sh build_cyber" to build  cyber rt first?

**Comment by Martin20** [comment]
@quning18 
No. Should we?

**Comment by daohu527** [comment]
Yes, the example need to build.
