### ISSUE TITLE
Messaging pipeline between cyber_topic and frontend visualization

### ISSUE THREAD

**Issue by YilmazOrkun** [ApolloAuto/apollo#10722]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hi all. I am trying to understand the messaging pipeline between the cyber_topic messages and how they are passed until the frontend.

As far as I could understand the messages from cyber_topics are gathered in the backend of dreamviews simulation_world_service.cc and transformed into protobuf messages.
https://github.com/ApolloAuto/apollo/blob/a13efb4a52e0315f54080355b368461bb4d0ad89/modules/dreamview/backend/simulation_world/simulation_world_service.cc#L266-L267

So far so good. What is the next step to go from simulation_world_service to frontend?
Maybe we can elaborate this question for the task of visualizing the obstacles from the perception module, where polygon points are published in the message?

https://github.com/ApolloAuto/apollo/blob/a13efb4a52e0315f54080355b368461bb4d0ad89/modules/perception/proto/perception_obstacle.proto#L58

**Comment by unacao** [comment]
protobuf message simulation_world.proto is retrieved by frontend via websocket https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/backend/simulation_world/simulation_world_updater.cc#L162
