### ISSUE TITLE
Getting Segmentation Fault on a Custom ROS Topic

### ISSUE THREAD

**Issue by moizsajid** [ApolloAuto/apollo#10721]
I have defined my own custom ROS topic with message type ```planning::ADCTrajectory``` in the Adapters module which I want to use inside of Apollo. The problem is whenever I call the ```UpdateWithLatestObserved()``` function (defined in ```/modules/dreamview/backend/simulation_world/simulation_world_service.h```) on this new ROS topic Adapter, I get a segmentation fault on the line where its call the ```Empty()``` function inside the definition of ```UpdateWithLatestObserved()``` function. In fact, I cannot call any other function on this ROS topic Adapter and I get the same segmentation fault error. I am able to get the messages from this newly created topic using the ```rostopic echo``` command. I think I have correctly defined the Adapter for this ROS topic inside of ```modules/common/adapters```. It would be really great if you can tell me what I am doing wrong. Thank you!

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Supporting materials (screenshots, command lines, code/script snippets):
```
  template <typename AdapterType>
  void UpdateWithLatestObserved(const std::string &adapter_name,
                                AdapterType *adapter, bool logging = true) {
    if (adapter->Empty()) {
      if (logging) {
        AINFO_EVERY(100) << adapter_name
                         << " adapter has not received any data yet.";
      }
      return;
    }

    UpdateSimulationWorld(adapter->GetLatestObserved());
  }
```

**Comment by moizsajid** [comment]
@vlin17 and @unacao Can you please help me with this issue?

**Comment by unacao** [comment]
did you register your new adapter? https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/common/adapters/adapter_manager.h#L255

**Comment by moizsajid** [comment]
Yes I have. I am successfully able to call the `Empty()` function of my adapter like this `AdapterManager::MyAdap()->Empty()`inside the `planning.cc` file. However, I cannot call any functions of my adapters inside the `/modules/dreamview/backend/simulation_world/simulation_world_service.cc` file. I get a segmentation error whenever I do so.

**Comment by xiaoxq** [comment]
You may also need a config file to declare which channels are monitored, e.g.: https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/control/conf/adapter.conf

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
