### ISSUE TITLE
build_cyber on AARCH64 doesn't work

### ISSUE THREAD

**Issue by SenRamakri** [ApolloAuto/apollo#10731]
**Describe the bug**
I'm trying to build Apollo CyberRT in a AARCH64 machine. I'm able to build the Aarch64 docker image using cyber_start/cyber_into scripts. Once inside Im trying to build the CyberRT using "./apollo.sh build_cyber". But it fails as below. 

```
[INFO] Building on aarch64...
[INFO] Building with --jobs=3 for aarch64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (02-14 23:09:03.009) Found 655 targets...
ERROR: (02-14 23:09:08.114) /apollo/modules/tools/visualizer/BUILD:27:1: C++ compilation of rule '//modules/tools/visualizer:visualizer_lib' failed (Exit 1).
In file included from modules/tools/visualizer/video_images_dialog.cc:17:0:
./modules/tools/visualizer/video_images_dialog.h:19:29: fatal error: QtWidgets/QDialog: No such file or directory
compilation terminated.
INFO: (02-14 23:09:08.222) Elapsed time: 10.865s, Critical Path: 0.53s
============================
[ERROR] Build failed!
[INFO] Took 18 seconds
============================
```

**To Reproduce**
1. Build Aarch64 Docker image using cyber_start.sh and drop into the container using cyber_into.sh
2. In the container do "./apollo.sh buil_cyber" and here the system fails as above.

**Expected behavior**
Build completes successfully.

**Screenshots**
![build_cyber_failure](https://user-images.githubusercontent.com/31017510/74575721-aeaef880-4f4d-11ea-88de-2768ff340013.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04/Aarch64

If anyone have seen this problem/had a solution please reply.

**Comment by quning18** [comment]
@SenRamakri please try to comment out the visualizer first in the build and see how it goes.

**Comment by SenRamakri** [comment]
@quning18 - Thanks for your response, I'll try that out and post the results.

**Comment by storypku** [comment]
> **Describe the bug**
> I'm trying to build Apollo CyberRT in a AARCH64 machine. I'm able to build the Aarch64 docker image using cyber_start/cyber_into scripts. Once inside Im trying to build the CyberRT using "./apollo.sh build_cyber". But it fails as below.
> 
> ```
> [INFO] Building on aarch64...
> [INFO] Building with --jobs=3 for aarch64
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
> INFO: (02-14 23:09:03.009) Found 655 targets...
> ERROR: (02-14 23:09:08.114) /apollo/modules/tools/visualizer/BUILD:27:1: C++ compilation of rule '//modules/tools/visualizer:visualizer_lib' failed (Exit 1).
> In file included from modules/tools/visualizer/video_images_dialog.cc:17:0:
> ./modules/tools/visualizer/video_images_dialog.h:19:29: fatal error: QtWidgets/QDialog: No such file or directory
> compilation terminated.
> INFO: (02-14 23:09:08.222) Elapsed time: 10.865s, Critical Path: 0.53s
> ============================
> [ERROR] Build failed!
> [INFO] Took 18 seconds
> ============================
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Build Aarch64 Docker image using cyber_start.sh and drop into the container using cyber_into.sh
> 2. In the container do "./apollo.sh buil_cyber" and here the system fails as above.
> 
> **Expected behavior**
> Build completes successfully.
> 
> **Screenshots**
> ![build_cyber_failure](https://user-images.githubusercontent.com/31017510/74575721-aeaef880-4f4d-11ea-88de-2768ff340013.PNG)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 18.04/Aarch64
> 
> If anyone have seen this problem/had a solution please reply.

```
bash apollo.sh build cyber
```
should work now as of master  3711be4317 .

**Comment by storypku** [comment]
Hi @SenRamakri , as we haven't received response for long, I am going to close this issue now. Please feel free to create another issue if you have other questions. Thanks for supporting Apollo!
