### ISSUE TITLE
YAML SegFault with Camera-Based Perception

### ISSUE THREAD

**Issue by heobu** [ApolloAuto/apollo#10734]
**Describe the bug**
Camera based perception does not work due to segmentation fault during YAML parsing. 

**To Reproduce**
1. Build Apollo with the build_opt_gpu parameter.
2. Launch bootstrap.
3. Launch static_transform. 
4. Publish camera images to the front_6mm topic.
4. Launch perception_camera.

**Expected behavior**
Perception should work based on the images being published to the front_6mm topic.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Apollo version: v5.5

**Additional context**
When perception_camera is launched with GDB, it can be seen that the error happens when LoadCameraIntrinsics function in modules/perception/common/io/io_util.cc is called by SensorManager::Init. Accessing the content of a YAML file with the following syntax seems to be problematic:
`node["width"].as<float>()`
The necessary intrinsics and extrinsics files exist, there are no issues with the loading of the files. Instead of accessing the content of the YAML with key values like this, iterating over "node" and accessing the elements inside the map as in the following case seems acceptable:
`for (auto it=node.begin(); it!=node.end(); it++){
  AINFO << "Node key: " << it->first;
  AINFO << "value: " << it->second;
}`
But even with the aforementioned method, accessing the parsed values with anything other than `as<std::string>()` seems to create an error as well. For example, you cannot directly parse them as float.

If we changed the source code to work with an iterator or gave some values embedded inside the source code, this segmentation fault disappears and more logs about the CNN layers can be seen as perception_camera works for a bit longer. But then eventually there is another error regarding the parsing of another YAML file when LoadExtrinsics is called by the FusionCameraDetectionComponent::InitCameraFrames function.

I do not particularly care for calibrating these intrinsics and extrinsics files at the moment. I just want to see perception working with the camera input.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
