### ISSUE TITLE
Build not using GPU even when using build_gpu tag

### ISSUE THREAD

**Issue by chenghanzh** [ApolloAuto/apollo#10741]
**Describe the bug**
After I ran ./apollo.sh build_gpu, it says that gpu mode is not required and ran in CPU mode.

**Expected behavior**
Run in gpu mode

**Screenshots**
![image](https://user-images.githubusercontent.com/50680244/74857221-6444c780-5311-11ea-8bae-408f9027c3f8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux 16.04
 - Version [e.g. 22] Apollo 5.0

**Comment by smahajan07** [comment]
Make sure you have the latest docker and nvidia-container-toolkit installed.
Before you build, try running nvidia-smi inside docker, if you see an output, you can proceed to build.

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
