### ISSUE TITLE
build cyber in docker fail:no such package '@boost//'

### ISSUE THREAD

**Issue by wutianze** [ApolloAuto/apollo#10755]
**Describe the bug**
When I tried to build cyber in docker container, I ran into the error:

ERROR: (02-24 11:22:17.988) /apollo/third_party/BUILD:17:1: no such package '@boost//': Expected directory at /usr/local/apollo/boost/include but it does not exist. and referenced by '//third_party:boost'.

**To Reproduce**
1. `./docker/scripts/cyber_start.sh` succeed
2. `./docker/scripts/cyber_into.sh` succeed
3. `./apollo.sh build_cyber`
See error:
![Screenshot from 2020-02-24 19-56-47](https://user-images.githubusercontent.com/13427786/75150656-d8330580-573f-11ea-912d-c1dcbc72a67a.png)

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04
 - cyber docker image: apolloauto/apollo:cyber-x86_64-18.04-20191003_1544

**Comment by quning18** [comment]
could you try to revert this commit and see how it goes?

https://github.com/ApolloAuto/apollo/commit/87f16fd8f66ef23d90f38ffce2f626849f34dba7

**Comment by wutianze** [comment]
Thanks.
The building worked without reverting. May because I need to `apollo.sh clean` first.
However, when running `apollo.sh build`(follow the complete process to build apollo not just cyber), I still meet the same problem. When dev_into the docker container, I can not find the dir `/usr/local/apollo`, does it mean I must install apollo kernel? Could you tell me how this path is created `usr/local/apollo`.

**Comment by sihanfei** [comment]
when i did this, i was blocked by the same issue.

**Comment by jixiaojie** [comment]
Try to copy directory /usr/local/apollo in the dev docker to the cyber docker /usr/local/apollo

**Comment by weiyinxie** [comment]
facing the same issue, anyone who has idea to fix it.....

**Comment by tangcy98** [comment]
Maybe it is because of the cache conflict of bazel. Try to stop the container and clean the cache.
Be careful when you use rm -rf and make sure that you have a check!
`cd ~/.cache/bazel`
`sudo rm -rf _bazel_*`
`cd ~`
`sudo rm -rf .BRANCH_*`

**Comment by tangcy98** [comment]
Maybe it is because of the cache conflict of bazel. Try to stop the container and clean the cache.
Be careful when you use rm -rf and make sure that you have a check!
`cd ~/.cache/bazel`
`sudo rm -rf _bazel_*`
`cd ~`
`sudo rm -rf .BRANCH_*`
Also, if your RAM is less than 16G, try to use -j.

**Comment by storypku** [comment]
This issue should have been fix in master HEAD.
