### ISSUE TITLE
running new component example fails

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#10757]
**Describe the bug**

I use ubuntu 16.04 and built Apollo 5.0

I went through the tutorial here:
https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Quick_Start.md

When I issue the command: cyber_launch start /apollo/cyber/examples/common_component_example/common.launch or 

mainboard -d /apollo/cyber/examples/common_component_example/common.dag

I receive the error below:

**Screenshots**

common@in_dev_docker:/apollo$ cyber_launch start /apollo/cyber/examples/common_component_example/common.launch
[cyber_launch_12573] INFO Launch file [/apollo/cyber/examples/common_component_example/common.launch]
[cyber_launch_12573] INFO ========================================================================================================================
[cyber_launch_12573] INFO Load module [common] library: [common] [CYBER_DEFAULT] conf: [/apollo/cyber/examples/common_component_example/common.dag] exception_handler: []
[cyber_launch_12573] INFO Start process [common] successfully. pid: 12581
[cyber_launch_12573] INFO ------------------------------------------------------------------------------------------------------------------------
[common ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[common ]  I0224 15:27:38.921747 12581 module_argument.cc:81] [] command: mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT
[common ]  I0224 15:27:38.923187 12581 global_data.cc:150] [] host ip: 10.218.100.22
[common ]  I0224 15:27:38.924125 12581 module_argument.cc:57] [] binary_name_ is mainboard, process_group_ is common, has 1 dag conf
[common ]  I0224 15:27:38.924409 12581 module_argument.cc:60] [] dag_conf: /apollo/cyber/examples/common_component_example/common.dag
[common ]  E0224 15:27:39.373608 12611 channel_manager.cc:340] [mainboard] newly added writer(belongs to node[prediction])'s message type[apollo.prediction.PredictionObstacles] does not match the exsited reader(belongs to node[common])'s message type[apollo.cyber.examples.proto.Driver].
[common ]  E0224 15:27:41.316292 12611 channel_manager.cc:340] [mainboard] newly added reader(belongs to node[sim_control])'s message type[apollo.prediction.PredictionObstacles] does not match the exsited reader(belongs to node[common])'s message type[apollo.cyber.examples.proto.Driver].
[common ]  E0224 15:27:41.320961 12611 channel_manager.cc:340] [mainboard] newly added writer(belongs to node[sim_control])'s message type[apollo.prediction.PredictionObstacles] does not match the exsited reader(belongs to node[common])'s message type[apollo.cyber.examples.proto.Driver].
[common ]  E0224 15:27:41.350553 12611 channel_manager.cc:340] [mainboard] newly added reader(belongs to node[simulation_world])'s message type[apollo.prediction.PredictionObstacles] does not match the exsited reader(belongs to node[common])'s message type[apollo.cyber.examples.proto.Driver].
[common ]  E0224 15:27:41.514602 12611 channel_manager.cc:340] [mainboard] newly added reader(belongs to node[planning])'s message type[apollo.prediction.PredictionObstacles] does not match the exsited reader(belongs to node[common])'s message type[apollo.cyber.examples.proto.Driver].

**Comment by hongze83** [comment]
the question is sloved？

**Comment by Martin20** [comment]
Not yet.

**Comment by daohu527** [comment]
The error message means that the reader and the message type do not match

> newly added reader(belongs to node[planning])'s message type[apollo.prediction.PredictionObstacles] does not match the exsited reader(belongs to node[common])'s message type[apollo.cyber.examples.proto.Driver].
