### ISSUE TITLE
How can I test a test file

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#10750]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

- Ubuntu 18.04
- I built Apollo 5.0
- Apollo 5.0

### Steps to reproduce the issue:
I want to test a module in general. I know for each module or even each capability, there is a test file but I do not know how to test them. For example for a general test we have "./apollo test" but how about each module? How can I call them and how I can see the result. 

For instance, there is a test file in the path below:

"apollo/modules/v2x/v2x_proxy/obu_interface/obu_interface_grpc_impl_test.cc". How can I run it?

**Comment by ycool** [comment]
inside docker, assume you have already added obu_interface_grpc_impl_test target into modules/v2x/v2x_proxy/obu_interface/BUILD file, you can run  `bazel test modules/v2x/v2x_proxy/obu_interface:modules/v2x/v2x_proxy/obu_interface/`
