### ISSUE TITLE
failed to pull docker image

### ISSUE THREAD

**Issue by MoonCake-AOV** [ApolloAuto/apollo#10756]
run: bash docker/scripts/dev_start.sh

[INFO] Start pulling docker image apolloauto/apollo:dev-18.04-x86_64-20191111_1530 ...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=apolloauto%2Fapollo&tag=dev-18.04-x86_64-20191111_1530: dial unix /var/run/docker.sock: connect: permission denied
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-18.04-x86_64-20191111_1530

**Comment by xiaoxq** [comment]
plz try `chmod 777 /var/run/docker.sock`

**Comment by MoonCake-AOV** [comment]
Thanks for your help, I tried with sudo then it works.
However one new error occurs:
Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo: dev-18.04-x86_64-20191111_1530
Would you please give me more advice?

**Comment by xiaoxq** [comment]
`sudo` is not a good practice, and that may be why you encounter permission
issue time to time with regular user.
I would suggest you to clean the workspace a little bit, reboot and retry :)

**Comment by MoonCake-AOV** [comment]
Thanks a lot:) my problems are solved.

**Comment by hawl666** [comment]
@Chunhai-Yu hello,i get the same error,how do u solve it?

**Comment by Soham1302** [comment]
> 

@Chunhai-Yu can you please help in solving this issue

**Comment by hugeshark7** [comment]
我想说用中文吧，除了初学者没人用apollo的
