### ISSUE TITLE
How To Enable Radar

### ISSUE THREAD

**Issue by NeelNarvekar** [ApolloAuto/apollo#10767]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I noticed in the perception dag files that there is a radar aspect to the perception module. However, when looking at the radar log files I see the module being initialized but then it exits. Is there any way to enable this? I am using the lgsvl simulator, could there be an issue with our sensor configuration?
Thanks!

**Comment by daohu527** [comment]
Can you provide more information, like logs and lgsvl's sensor configuration. : )
