### ISSUE TITLE
Radar perception

### ISSUE THREAD

**Issue by sarankumarb** [ApolloAuto/apollo#10775]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:16.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Is there a way to run radar perception module alone offline?

**Comment by daohu527** [comment]
Radar components can run independently, and you need to publish sensor data to make it work
