### ISSUE TITLE
如何使用apollo的仿真平台

### ISSUE THREAD

**Issue by ZhangJian322920** [ApolloAuto/apollo#10784]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:5.0

我fork了最新的apollo程序，按照dreamland的入门指南添加了一个直行道的任务。但是任务管理中的状态显示编译失败。我是直接用的fork过来的程序。我需要做什么修改吗，如果修改的话应该修改哪里可以编译通过呢。

![image](https://user-images.githubusercontent.com/50873982/75511028-c72c1200-5a27-11ea-8f1b-e6bc55a811ff.png)

**Comment by ycool** [comment]
You don't need change any code if you'd like to run a dreamland task. Can you help to update your forked code? It seems you might get an unstable commit. Thanks.

**Comment by unacao** [comment]
Did the suggestion above solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
