### ISSUE TITLE
Build cyberRT drivers face errors

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#10794]
I'm trying to build drivers on Cyber RT with [document](https://github.com/ApolloAuto/apollo/blob/1cd2e265c90d7e6170127732b138a4024729a583/cyber/doxy-docs/source/CyberRT_Docker.md). But failed in x86 and aarch64.

x86(the normal user did not have sudo permission and sudo command,and cannot su root.)
![image](https://user-images.githubusercontent.com/4536559/75671397-9ebb4680-5cb9-11ea-910a-1a495d910c8f.png)

aarch64
![image](https://user-images.githubusercontent.com/4536559/75671419-a7138180-5cb9-11ea-99a9-03ea2ef45721.png)

How to solve these problem?
Did apollo still maintains these features?

**Comment by quning18** [comment]
the changes of the dependencies have broken the cyber build script. We are working on it and should get it back pretty soon.

**Comment by quning18** [comment]
@oska874 for problem with aarch64, 

could you check if you have the file /home/tmp/proj.4-4.9.3.zip? And if it exists, could you send us the results by running:

sha256sum /home/tmp/proj.4-4.9.3.zip

Thanks!

**Comment by quning18** [comment]
@oska874 

for the first problem on x86, could you try to revert this commit and see how it goes?

https://github.com/ApolloAuto/apollo/commit/87f16fd8f66ef23d90f38ffce2f626849f34dba7

**Comment by oska874** [comment]
@quning18 
I've checked all the dependices in WORKSPACE.in, the files are all in `/home/tmp`.
I tried revert [87f16fd](https://github.com/ApolloAuto/apollo/commit/87f16fd8f66ef23d90f38ffce2f626849f34dba7),but doesnot work, it still shows no `'@opencv//'`, `'@proj4//'`.
BTW, I've a question on how to build third_party and install them by hand?

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
