### ISSUE TITLE
Typo in modules/common/time/time.h line 65

### ISSUE THREAD

**Issue by miluit01** [ApolloAuto/apollo#10797]
// The clock mode can either be a system clock time, a user mocked time (for
// test only) or read **from ROS.**

ROS is obsoleted, right? :)

**Comment by xiaoxq** [comment]
Nice catch! It's fixed in https://github.com/ApolloAuto/apollo/commit/29e6f4701644f0394c3d18618d6c1217427c262f#diff-a35a54c341e62dcb4f2d520b9c9b5e33 . Thank you!
