### ISSUE TITLE
How to train offline prediction model in 5.0 

### ISSUE THREAD

**Issue by zhouyapengzi** [ApolloAuto/apollo#10798]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.0)**:

### Steps to reproduce the issue:
- i followed the guide here https://github.com/ApolloAuto/apollo/blob/fc11a0782bd3eb037bf3a9de99392d7f198d0970/docs/howto/how_to_train_prediction_mlp_model.md and found ** feature_extraction.sh ** is deleted in 5.0. So which file should i use to train prediction model offline?

also , i tried to copy feature_extraction.sh from v3.5 to v5.0 and update several dependency, then, play demo. i got a lot error message and an empty training_data.npy 

```
"[prediction]  E0303 14:45:34.901347  5423 right_of_way.cc:110] [prediction] Null lane info pointer found.
[prediction]  E0303 14:45:34.901369  5423 right_of_way.cc:110] [prediction] Null lane info pointer found.
[prediction]  E0303 14:45:34.901387  5423 right_of_way.cc:110] [prediction] Null lane info pointer found."
```

**Comment by edmundang1994** [comment]
Hi, I am also facing the same issue, any workaround/solution?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
