### ISSUE TITLE
Can't find docs/demo_guide/demo_3.5.record

### ISSUE THREAD

**Issue by yuhengh** [ApolloAuto/apollo#10792]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (binary)**:
- **Apollo version (5.5)**:

### Steps to reproduce the issue:
- I'm following this document https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_launch_Apollo.md
but can't find docs/demo_guide/demo_3.5.record. I assumed this file should be a recorded scenario that can be played?

**Comment by MoonCake-AOV** [comment]
1. Make sure your python version is higher than 3.0, because the library urllib.request is needed in rosbag_helper.py file.
2. You can try to download the demo_3.5.record file directly: https://github.com/ApolloAuto/apollo/releases/download/v3.5.0/demo_3.5.record
Hope it helps.
