### ISSUE TITLE
Is there release mode in Apollo?

### ISSUE THREAD

**Issue by ZiwenWan** [ApolloAuto/apollo#10808]
I raised this issue to get more information about the compiler config of Apollo. I was trying to build Apollo and I noticed that there are some debug options, for example DCHECK. I was wondering whether there is a release mode which will remove all the debugging related config. If so, how to setup the release config?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0 and 5.0

### More details:
- I am curious about the DCHECK problem. I noticed in the glog/logging.h, DCHECK_IS_ON will be set if DNDEBUG is set or DCHECK_ALWAYS_ON is set. I noticed that if I used -c fastbuild mode, the DNDEBUG should be off, but the DCHECK is still enabled. Do you keep all the DCHECK even if the software is released?

**Comment by jimmyw404** [comment]
I don't know about whether fastbuild is setting NDEBUG properly, but if you run ./apollo.sh build_opt (or ./apollo.sh build_opt_gpu) it uses opt (optimized) compilation and NDEBUG is defined as true. More information can be found by running the apollo.sh script without arguments or in the following links.

https://github.com/bazelbuild/bazel/issues/4144
https://github.com/bazelbuild/bazel/issues/139
https://docs.bazel.build/versions/master/command-line-reference.html#flag--compilation_mode
