### ISSUE TITLE
Can Baidu Apollo dreamview be built and run in the cloud, e.g. google cloud?

### ISSUE THREAD

**Issue by jch458** [ApolloAuto/apollo#10807]
Hi,

May I ask if Baidu Apollo can be built and simulated in the cloud?

I have managed to run Dreamview with an RTX2080 desktop, but what about the cloud service, considering the compolsory(or not?)  Nvidia GPU driver and the GUI of Ubuntu system. Also having the concern about the latency and performance of the simulation in the cloud.

Really appreciated if anyone can make those things clear!

**Comment by vlin17** [comment]
Hi @jch458 ,

Hope the information answered your question. If you have any follow up question, please leave a comment below. If we don't not hear back from you in 72 hours, we will close the issue and we encourage you to open a new issue if you have any more questions. 

Thank you for supporting Apollo!
