### ISSUE TITLE
does apollo has open some tools for HDMap editor

### ISSUE THREAD

**Issue by HelloJK** [ApolloAuto/apollo#10806]
I want to generate apollo HDMap format xml file based on my slam occupy map, so does apollo has open this kind of tools to us?

### System information

- **Ubuntu 16.04**:

**Comment by jinghaomiao** [comment]
Thanks for using Apollo. Apollo does not provide a tool to generate HD map. If you need map service, please contact Baidu (IDG-apollo@baidu.com) if you are in China or our partner in the US (e.g. Carmera https://www.carmera.com).
