### ISSUE TITLE
Nvidia issue

### ISSUE THREAD

**Issue by miewan** [ApolloAuto/apollo#10802]
I am having problem with Nvdia failed handshake. My pc was reboot and I need to install Clang again in the Apollo Auto docker. This is Apollo 3.5 and I also have the docker with the latest docker too. Both give me the same error. This was totally fine yesterday. I can work with Clang without any problem yesterday

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5)**:

### Steps to reproduce the issue:

- I run this command 
`shifa@in_dev_docker:/apollo$ sudo bash docker/build/installers/install_clang.sh`

- And the output
`W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

Can anyone help me with this. I don't know why this happen when it works fine yesterday

**Comment by storypku** [comment]
Ubuntu 14.04 was too old.  And Apollo 3.5. 
I guess you can remove nvidia/cuda-related apt sources from `/etc/apt/sources.list.d/` and try again if you are using Apollo 3.5.
