### ISSUE TITLE
Beginner question regarding apollo sensor fusion

### ISSUE THREAD

**Issue by hadiamiri** [ApolloAuto/apollo#10819]
Hi
I am studying apollo platform, I am still a beginner in this platform. I want to investigate modules which are concerted with **sensor fusion**. 
As far as I know **localization** and **perception** modules which have sensor fusion.
How can I run and expriment sensor fusion tasks only?  Which version of apollo should I use?

I would be happy if anyone can guide me to correct doc files, Because this platform is very huge and I get lost in details.

Regards.

**Comment by unacao** [comment]
Please check if any documents here can help https://github.com/ApolloAuto/apollo/tree/master/docs/howto

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
