### ISSUE TITLE
Apollo 5.0 : Perception module keeps crashing 

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#10814]
**Describe the bug**
In Apollo 5.0, Perception module keeps crashing and car drives erratically. 
The issue is very similar to  #184,  #232, #9857,  #632, #232, #184, #206, #4233, #6916 and many more .
Here's a Youtube video I made on this issue :  'https://www.youtube.com/watch?v=w2SHCZkFSA4'

**To Reproduce**
1. Go to 'https://github.com/lgsvl/apollo-5.0#launching-apollo-alongside-the-simulator'
2. Follow the steps mentioned to start Dreamview and  bridge with lgsvl 
3. Selected Car : Lincoln2017MKZ(Apollo 5.0)
4. Selected Map : San Francisco

**Expected behavior**
In dreamview, as well as in lgsvl, the car should drive autonomously to the chosen destination .
Youtube Video of expected behaviour : https://www.youtube.com/watch?reload=9&v=19eo9ZffCKQ&feature=youtu.be

****System Description**
 - NVIDIA Driver v: 435.21
 -   CUDA Version: 10.1 
 - GPU(2) : RTX 2080
 - OS: Ubuntu 18.04

**Additional context**
LGSVL simulation seems to be using a lot of CPU resources, so I capped it using #cpulimit -e simulator -l 30 
![gdb_debug_streaming_perception_dag](https://user-images.githubusercontent.com/50120641/76144850-77cb8e80-6084-11ea-830d-cadc0c1cb5e0.png)
![gpu_test_output](https://user-images.githubusercontent.com/50120641/76144855-7f8b3300-6084-11ea-8ba0-4dc71826c300.png)
![Output_perception_dag_mainboard](https://user-images.githubusercontent.com/50120641/76144858-86b24100-6084-11ea-8fbf-6d76130dd93d.png)

**Comment by ntutangyun** [comment]
You're using an old version of LGSVL simulator. could you try out the latest version.

**Comment by Avps1** [comment]
Hi @ntutangyun . Thanks for your response.
May I ask what made you conclude that I am using an old version of lgsvl ? Was it something in the screenshots that I attached ?
I think lgsvl throws an error called ''Invalid Out of Date Asset Bundle'' : [](https://github.com/lgsvl/simulator/issues/659?email_token=AL6MPQLIW26KYDXFPUR7MYTRFH4TDA5CNFSM4K65ZK72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENMWK5Q#issuecomment-593061238)

**Comment by ntutangyun** [comment]
@Avps1 sorry my mistake. I saw the expected behavior video, in which the lgsvl simulator version was quite old. 

> I think lgsvl throws an error called ''Invalid Out of Date Asset Bundle'' : '(lgsvl/simulator#659)' if an older version of Vehicle or environment is used.
I can assure you that its not the case here, because I downloaded the most recent asset bundle for Borregas Ave env and the LIncoln 2017 vehicle, from the link mentioned in lgsvl/simulator#659 , with the issue still persisting.

That's right.

Could you put your CPU and Memory Specs.

I'm using Intel Core i7-6850K, 6 cores, 12 threads. Still when I run the full lgsvl + apollo 5.0 stack, the CPUs are almost fully occupied. This is might due to the large amount of data communication between lgsvl and Apollo Cyber RT (particularly the cameras and lidar sensors).

I've checked your recorded video. according to my experiences, the frequencies of the sensor messages are way too low. In my computer, the messages are sent about 5 - 10 times higher frequency than yours. 

I guess that's probably the issue for the perception ?

**Comment by Avps1** [comment]
Hi @ntutangyun. That could definitely be it. If the low frequency of sensor messages is indeed the reason for the Perception modules crashing, could you suggest a workaround for this? WOuld it be better if I run Apollo in 1 pc and lgsvl in another ?

**Comment by luqiang21** [comment]
@Avps1 Yes, it would be much better if you run them separately.

**Comment by Avps1** [comment]
Hi, my CPU configurations are similar to @ntutangyun. 
Running Apollo and lgsvl in 2 separate PCs still didnt give the desired result - The perception module is still crashing for GTX 2080 , which brings me to my next question - Is GTX 2080 officially supported by Apollo? I read in a lot of places that it isnt, but I dont know the current status.

**Comment by ntutangyun** [comment]
@Avps1 I've also seen information like GTX 2080 is not supported yet previously. like [here](https://github.com/ApolloAuto/apollo/issues/9857#issuecomment-545376091), [here](https://github.com/ApolloAuto/apollo/issues/8243#issuecomment-497834257) and [here](https://github.com/ApolloAuto/apollo/issues/6916).

I'm using two GTX 1080 TI SLI, and the LGSVL + Apollo stack works fine.

**Comment by Avps1** [comment]
Thanks @ntutangyun , I close the issue then, on the conclusion that the module crashes occur because RTX 2080 is not officially supported. 
However, may I ask you to kindly look into this new issue that I raised : https://github.com/ApolloAuto/apollo/issues/10882
Its about Apollo 5.0 not driving autonomously in GTX 1080 . Thanks in advance.

**Comment by Avps1** [comment]
Hi @ntutangyun , can you please tell me how many CPU cores you have in  your GTX 1080 PC?

**Comment by faysalhossain2007** [comment]
@Avps1 can you please tell me your PC configuration where you have successfully run apollo with lg simulator?
Thanks!

**Comment by ntutangyun** [comment]
@Avps1 hi sorry for late reply.  I'm using Intel Core i7-6850K CPU @ 3.60GHz. 6 cores 12 threads. 
My GPU is two GTX 1080 TI (SLI)

**Comment by Avps1** [comment]
> @Avps1 can you please tell me your PC configuration where you have successfully run apollo with lg simulator?
> Thanks!

Hey!
So my configuration is as follows : 
Ubuntu 18.04
CUDA 10.2 
Intel i5-4 cores
GPU(s) - 2 GTX 1080
Nvidia Drivers - v: 435.21 

Note : Using the right GPU made all the difference.
Also, dont forget to press the "scroll-UP" button in lgsvl. The car wont start driving autonomously in DreamView without it.

**Comment by lemketron** [comment]
@Avps1 wrote:
> I close the issue then, on the conclusion that the module crashes occur because RTX 2080 is not officially supported.

Please note that the LGSVL changes have been merged into Apollo master which should include support for the RTX 2080. We will be publishing a document describing how to set this up but you can start by cloning apollo master and building it. If this is useful we can post a link to the updated documentation as soon as it is available.

**Comment by sebautistam** [comment]
> > @Avps1 can you please tell me your PC configuration where you have successfully run apollo with lg simulator?
> > Thanks!
> 
> Hey!
> So my configuration is as follows :
> Ubuntu 18.04
> CUDA 10.2
> Intel i5-4 cores
> GPU(s) - 2 GTX 1080
> Nvidia Drivers - v: 435.21
> 
> Note : Using the right GPU made all the difference.
> Also, dont forget to press the "scroll-UP" button in lgsvl. The car wont start driving autonomously in DreamView without it.

Hello. I am not completely sure but I may be having a similar issue to yours. Could you just clarify to me what is the "scroll-up" button in LGSVL and how to press it? Thank you!

**Comment by Avps1** [comment]
> > > @Avps1 can you please tell me your PC configuration where you have successfully run apollo with lg simulator?
> > > Thanks!
> > 
> > 
> > Hey!
> > So my configuration is as follows :
> > Ubuntu 18.04
> > CUDA 10.2
> > Intel i5-4 cores
> > GPU(s) - 2 GTX 1080
> > Nvidia Drivers - v: 435.21
> > Note : Using the right GPU made all the difference.
> > Also, dont forget to press the "scroll-UP" button in lgsvl. The car wont start driving autonomously in DreamView without it.
> 
> Hello. I am not completely sure but I may be having a similar issue to yours. Could you just clarify to me what is the "scroll-up" button in LGSVL and how to press it? Thank you!

Hi,
I dont understand the question. A snapshot might be helpful.
KInd Regards

**Comment by lemketron** [comment]
> Also, dont forget to press the "scroll-UP" button in lgsvl. The car wont start driving autonomously in DreamView without it.

I'm not exactly sure what was meant by this. In the simulator window you might need to press the "play" button at the bottom of the screen to begin the simulation before sensor data will be sent to Apollo's cyber bridge. 

As for other keyboard controls, none should be needed unless you have inadvertently activated the parking brake or shifted the car out of gear. Keyboard controls are documented [here](https://www.lgsvlsimulator.com/docs/keyboard-shortcuts/).
