### ISSUE TITLE
build apollo on nvidia jetson nano face error “error: 'constexpr const size_t apollo::planning::SpiralProblemInterface::N' is private”

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#10823]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:arm64 18.04
- **Apollo installed from (source or binary)**: source，docker
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:5.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
cyber_start.sh
cyber_into.sh
./apollo.sh build_planning

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/4536559/76287742-21f32280-62e0-11ea-88e6-4036db10d16e.png)

**Comment by storypku** [comment]
Apollo for ARM64 is not officially support yet. And we suggest that you always use the latest master to reduce the chance of bugs.
