### ISSUE TITLE
Can not find perception input

### ISSUE THREAD

**Issue by Chunhai-Yu** [ApolloAuto/apollo#10824]
How can I find the perception module inputs, for example:
128 channel LiDAR data (cyber channel /apollo/sensor/velodyne128)

**Comment by daohu527** [comment]
1. Generally speaking the **DAG file** hold the channel infos and manage the topologies.

You can find perception input from "apollo/modules/perception/production/dag/dag_streaming_perception.dag".

2. Also there are some topic register in component "Init" by readers.
```
  chassis_reader_ =
      node_->CreateReader<Chassis>(chassis_reader_config, nullptr);
```

Both are needed inputs.

**Comment by MoonCake-AOV** [comment]
Thanks for your kind reply!

Would you also tell me:

1. Is that possible to include a new sensor in the localization or perception modules to collect simulated data and show it in Dreamview?

2. Are there some methods to simulate the sensors for apollo?

Best wishes!

**Comment by daohu527** [comment]
According to my understanding, I think it depends on what function you want to verify. 
1. If you need to subscribe to messages, you just need to create a new "reader" to subscribe to the corresponding topic.
2. Functional verification requires you to design it yourself. If you want to add a camera and display obstacles, this requires you to subscribe to new messages in the perception module and increase sensor fusion.

**Comment by MoonCake-AOV** [comment]
谢谢大佬回复。可能用中文能描述的更精确一些。
1. 如果我想添加新的传感器例如新的IMU或者camera，而不是apollo已有的传感器到平台上是否可行，如果可行要在哪些地方添加进去呢？
2. 我现在没有硬件，如果我想模拟出不同的传感器设备，并获得相应的数据传输到apollo，并且在dreamview中显示，该如何操作呢？
谢谢！

**Comment by daohu527** [comment]
1.I found some reference but not exactly you need [link](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/README.md#extended-modules)  
Maybe you should add the driver, and then publish the topic, you can ref the code in apollo.

2. You can use a simultor to mock the hardware. like [lgsvl](https://www.lgsvlsimulator.com/).

These two tasks may take some time, and the detailed steps may not be explained here. It is recommended that you try them first.

**Comment by MoonCake-AOV** [comment]
Super! Thanks a lot!

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
