### ISSUE TITLE
Error response from daemon: Container 2f93f03e0043512b0c462e09fbc844aee71bc607f674898d547cad8fa2921200 is not running

### ISSUE THREAD

**Issue by AAArslanbek** [ApolloAuto/apollo#10821]
System information

-OS Platform and Distribution (e.g., ): Linux Ubuntu 18.04
-Apollo installed from (source or binary): https://github.com/lgsvl/apollo-5.0.git
-Apollo version: 5.0

Steps to reproduce the issue:
I have done everything in the instructions as same as the guide.
when i write "./docker/scripts/dev_into.sh"
it says "Error response from daemon: Container 1bea57d97fc726565be4f2e4b8c607b3d07998d350afd1498ddaa78a9120f1b7 is not running"

![Screenshot_2](https://user-images.githubusercontent.com/61745541/76254988-73f36400-625e-11ea-99cb-6aad3a5af318.png)

![Screenshot_1](https://user-images.githubusercontent.com/61745541/76254993-75bd2780-625e-11ea-873c-6b7723d157a6.png)

**Comment by daohu527** [comment]
Here is some advices https://github.com/NVIDIA/nvidia-docker/issues/1034

If you didn't already make sure you've installed the nvidia-container-toolkit.
If this doesn't fix it for you, make sure you've restarted docker systemctl restart dockerd

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
