### ISSUE TITLE
Pnc_map.cc UpdateRoutingRange(int adc_index) use break or continue?

### ISSUE THREAD

**Issue by AlphaGKH** [ApolloAuto/apollo#10834]
**Describe the bug**
在UpdateRoutingRange(int adc_index)函数中，while循环中，有个if判断，判断满足条件就跳出循环了，这样的话，range_lane_ids_中岂不是只能保存route_indices_的第一个元素？按照我的理解，range_lane_ids_中保存的应该是车辆前方所有的lane的id。所以这里是不是用continue？还是我理解的有错误？

**Comment by AlphaGKH** [comment]
OK

**Comment by jmtao** [comment]
@AlphaGKH The check you were talking about is:
https://github.com/ApolloAuto/apollo/blob/master/modules/map/pnc_map/pnc_map.cc#L142

If the lane_id already exists, we break.  
This does not mean "range_lane_ids_中岂不是只能保存route_indices_的第一个元素".
It means, we do not support loop in routing.  If there's, we'll cut off up to the lanes where there's no duplicates.
