### ISSUE TITLE
gnss_struct.h file not founf

### ISSUE THREAD

**Issue by miewan** [ApolloAuto/apollo#10837]
System information

    OS Platform and Distribution (e.g., Linux Ubuntu 14.04): Linux Ubuntu 14.04
    Apollo installed from (source or binary): Source
    Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 3.5

Steps to reproduce the issue:
- Run clang with the following command:
`clang -std=c++11 -S -emit-llvm modules/localization/msf/msf_localization.cc -o modules/localization/msf/msf_localization.ll`  

- The output is:
`
In file included from modules/localization/msf/msf_localization.cc:17:
In file included from ./modules/localization/msf/msf_localization.h:41:
./modules/localization/msf/local_integ/localization_integ.h:24:10: fatal error: 
      'include/gnss_struct.h' file not found
#include "include/gnss_struct.h" 
```
Building the apollo.sh is successful. 
However when I am using clang to produce the IR through the docker I have the error mentioned above.  
And it looks like the **gnss_struct.h**file is missing. 
The only available file in local_integ/include is localization_integ.h

Are there any way I can this file?

$ ls usr/local/local_integ/include
localization_integ.h

**Comment by ycool** [comment]
It is at /usr/apollo/local_integ/include/gnss_struct.h in apollo_dev docker.

**Comment by miewan** [comment]
No, it is not. Hence the reason I am asking. The apollo build succesully
but this file is not in the folder
