### ISSUE TITLE
[cnnseg] Questions about Lidar height

### ISSUE THREAD

**Issue by kosuke55** [ApolloAuto/apollo#10840]
The point cloud looks different depending on the height of the Lidar. Therefore, when performing inference in an environment different from the training data, I think it is necessary to adjust the height of the point cloud. At what height  was the point cloud in the training data obtained ?

**Comment by hzdsdhr** [comment]
Hi, I've tried 64 cnnseg model on vlp16 which is installed at a lower place(front bumper) compared to apollo 64 lidar(roof), after adjust the height of the pointcloud, the performance is acceptable.
For now, there are three models in apollo: model fro 128beam lidar(installed on the roof), model for 64 beam lidar(installed on the roof), model for 16 beam lidar(installed on bumper)
You can try the models on data you have after adjusting the height of the pointcloud.
