### ISSUE TITLE
Is there any up-to-date dataset to test on Apollo offline using cyber-recorder?

### ISSUE THREAD

**Issue by wzjin2017** [ApolloAuto/apollo#10855]
Hi, does anyone know where to get up-to-date dataset (trace) to test (can edit the data and produce different decisions) on Apollo using cyber-recorder? The previous bag file I downloaded from Apollo Website lacks certain channels of sensor data. Thanks!

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by zhanghming** [comment]
I also want to know are there any offline test data to run Apollo 5.0. I want to run all the Apollo components without real car.

**Comment by unacao** [comment]
https://github.com/ApolloAuto/apollo/releases/download/v2.5.0/demo_2.5.bag this rosbag may contain sensor data, but it is in ros format.
