### ISSUE TITLE
 pnc  testing in azure

### ISSUE THREAD

**Issue by zjyy0820** [ApolloAuto/apollo#10854]
I want to test the control planning algorithm in azure.  I get the following error"/root/.cache/bazel/_bazel_root/a73dbdca8cb036802badd74b3e0fd726/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:71:5: no such package '@com_github_gflags_gflags//': In new_local_repository rule //external:com_github_gflags_gflags the 'build_file' attribute does not specify an existing file (/apollo-simulator/third_party/gflags.BUILD does not exist) and referenced by '//external:gflags'". How can I solve it?

**Comment by daohu527** [comment]
@zjyy0820 
Below are some advices.
> /apollo-simulator/third_party/gflags.BUILD does not exist
1. Check if the file "/apollo-simulator/third_party/gflags.BUILD" is exist

> no such package '@com_github_gflags_gflags//': In new_local_repository 

2. ref to the gflags INSTALL.md [link](https://github.com/gflags/gflags/blob/master/INSTALL.md#compiling-the-source-code-with-bazel)  
In apollo WORKSPACE.in I found
```
# gflags
new_local_repository(
    name = "com_github_gflags_gflags",
    build_file = "third_party/gflags.BUILD",
    path = "/usr/local/include/gflags",
)
```
which means the gflags is in the docker path "/usr/local/include/gflags", you should check it is exist too.

**Comment by zjyy0820** [comment]
> @zjyy0820
> Below are some advices.
> 
> > /apollo-simulator/third_party/gflags.BUILD does not exist
> 
>     1. Check if the file "/apollo-simulator/third_party/gflags.BUILD" is exist
> 
> 
> > no such package '@com_github_gflags_gflags//': In new_local_repository
> 
>     1. ref to the gflags INSTALL.md [link](https://github.com/gflags/gflags/blob/master/INSTALL.md#compiling-the-source-code-with-bazel)
>        In apollo WORKSPACE.in I found
> 
> 
> ```
> # gflags
> new_local_repository(
>     name = "com_github_gflags_gflags",
>     build_file = "third_party/gflags.BUILD",
>     path = "/usr/local/include/gflags",
> )
> ```
> 
> which means the gflags is in the docker path "/usr/local/include/gflags", you should check it is exist too.



> @zjyy0820
> Below are some advices.
> 
> > /apollo-simulator/third_party/gflags.BUILD does not exist
> 
>     1. Check if the file "/apollo-simulator/third_party/gflags.BUILD" is exist
> 
> 
> > no such package '@com_github_gflags_gflags//': In new_local_repository
> 
>     1. ref to the gflags INSTALL.md [link](https://github.com/gflags/gflags/blob/master/INSTALL.md#compiling-the-source-code-with-bazel)
>        In apollo WORKSPACE.in I found
> 
> 
> ```
> # gflags
> new_local_repository(
>     name = "com_github_gflags_gflags",
>     build_file = "third_party/gflags.BUILD",
>     path = "/usr/local/include/gflags",
> )
> ```
> 
> which means the gflags is in the docker path "/usr/local/include/gflags", you should check it is exist too.
first,thank you.second,because the azure simulation platform is encapsulated, how should I check whether that BUILD file exists?That flags file does exist, but why does it report that it does not exist? Is it because it was not downloaded?thanks

**Comment by daohu527** [comment]
It's hard to understand what you mean.  

If you download apollo onto the azure, you should check in the apollo docker. First the "third_party/gflags.BUILD" is exist, second the "/usr/local/include/gflags" is exist, and then build the apollo project.  

I wonder how you simulator apollo in azure? Is there some docment about it?

**Comment by zjyy0820** [comment]
> It's hard to understand what you mean.
> 
> If you download apollo onto the azure, you should check in the apollo docker. First the "third_party/gflags.BUILD" is exist, second the "/usr/local/include/gflags" is exist, and then build the apollo project.
> 
> I wonder how you simulator apollo in azure? Is there some docment about it?
don't run code in the apollo docker
https://azure.apollo.auto,this is the address of that simulation platform
The azure platform provides modules such as positioning, sensing, and canbus,Only need to provide control and planning modules.provide the apollo git repository address(https://github.com/ApolloAuto/apollo.git),then choose a branch or enter a commit to determine the code version tested,finally select the test scenario,the simulation platform will verify and compile the code
