### ISSUE TITLE
Apollo 5.0 Car drives autonomously in DreamView without lgsvl inputs

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#10865]
**Describe the bug**
I am not sure if this is a bug or not, but the car drives autonomously in DreamView without any input from LGSVL. By that I mean, I dont even open the lgsvl application , or choose a simulation or turn on sensors like IMU , GPU etc. I simply start Apollo and turn on DreamView, choose a route and the car drives autonomously to the location. Is this normal behavior? Should the car not take its inputs(like which sensors are turned ON) from the lgsvl simulation ?

**To Reproduce**
1. Start Apollo using bootstrap.sh and bridge.sh under Docker.
2.DONT TURN ON LGSVL
3. Open DreamView - Choose the routing destination. 
4. See the car drive autonomously to the destination.

**Expected behavior**
The car should move autonomously only when it receives its inputs from LGSVL.

**Specs :**

Ubuntu 18.04
NVIDIA-SMI 440.59.   
CUDA Version: 10.2 
GPU GTX 1080

**Comment by ntutangyun** [comment]
What's the mode selected in the mode selector ? as shown in [pic](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/images/dreamview_usage_table/header.png)

**Comment by Avps1** [comment]
Its "MKZ Standard Debug". 
I learnt that your Apollo+lgsvl stack is working fine for your GTX 1080 . Could you kindly tell me how many CPU cores you have in that PC? I think this could be a CPU issue. 
By the way, here is a Youtube video I made of the same : 
https://www.youtube.com/watch?v=cynMiAc4r94

**Comment by ntutangyun** [comment]
@Avps1 Mine is I7 6850K  6 cores 12 threads.
Could you check `cyber_monitor` and see if any thing is sending out sensor data and perception messages.

**Comment by Avps1** [comment]
Everything is working fine now. Thanks again for your inputs.

**Comment by opus23** [comment]
Hello @Avps1, I saw your video in youtube and your question very impressively. Thanks to you, I succeeded to run simulation in dreamview(without LGSVL). But still I have a question about this video.
 Do you download or make the map and moving obstacles? I can put obstacle with editing garage_perception.bash file, but It does not works well. Can I get some hint about obstacle code? Thank you!
