### ISSUE TITLE
进入docker环境后无法使用ros

### ISSUE THREAD

**Issue by Zhanghongbin-github** [ApolloAuto/apollo#1087]
进入docker环境后无法使用ros，提示没有该命令

**Comment by xiaoxq** [comment]
需要先执行 apollo.sh build

**Comment by Zhanghongbin-github** [comment]
执行过了

**Comment by xiaoxq** [comment]
详细的错误信息是什么呢？
比如执行 "which rosbag".

**Comment by Zhanghongbin-github** [comment]
正常环境执行which rosbag ,输出/opt/ros/indigo/bin/rosbag
在docker环境下没有输出

**Comment by xiaoxq** [comment]
看一下以下命令的输出？
echo $PATH
ls /home/tmp/ros/bin
ls /apollo/bazel-apollo/external/ros/bin

**Comment by Zhanghongbin-github** [comment]
echo $PATH
/opt/ros/indigo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
ls /home/tmp/ros/bin
ls: 无法访问/home/tmp/ros/bin: 没有那个文件或目录
ls /apollo/bazel-apollo/external/ros/bin
catkin_find		  rosboost-cfg	      rosmake	      rossrv
catkin_init_workspace	  rosclean	      rosmaster       rosstack
catkin_make		  rosconsole	      rosmsg	      rostest
catkin_make_isolated	  roscore	      rosmsg-proto    rostopic
catkin_package_version	  roscreate-pkg       rosnode	      rosunit
catkin_prepare_release	  rosgraph	      rospack	      rosversion
catkin_test_results	  roslaunch	      rosparam	      roswtf
catkin_topological_order  roslaunch-complete  rospbconvertor  talker
listener		  roslaunch-deps      rosrun	      tf_remap
rosbag			  roslaunch-logs      rosservice      view_frames

**Comment by ahuer2435** [comment]
如果本地没有安装ros，需要进入docker之后才可以使用ros，即需要执行bash docker/script/dev_into.sh（或者release_into.sh）.

**Comment by xiaoxq** [comment]
这个$PATH是有问题的。我们提供的docker image启动后的container里，$PATH应该包含例如：
/home/tmp/ros/bin, /apollo/bazel-apollo/external/ros/bin
而不会有/usr/games:/usr/local/games 这样的路径。因此要么没有进到docker container里，要么这个container的$PATH被你别的什么配置污染了。

**Comment by gengqx** [comment]
Indeed there is no ros path at all.
Here is the new install apollo,All follow the install step,and I did nothing about the docker and PATH,here is what I got:
```
root@in_release_docker:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@in_release_docker:/# 
```
```
root@in_dev_docker:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@in_dev_docker:/# 
```
both in the dev and release env,there is no ros.

**Comment by gengqx** [comment]
Here is the solution.
Try to find the ros folder,and run like this 
```
source /apollo/third_party/ros_x86_64/setup.bash
```
if there is no ros found,download the ros release,and run :
```
tar zxvf ros-indigo-apollo-1.0.0.x86_64.tar.gz
rsync -av ros/ /apollo/third_party/ros_x86_64
source /apollo/third_party/ros_x86_64/setup.bash
```
If you build your own ros, just source the setup.bash

**Comment by hoporluo** [comment]
In my case, just: 
source /home/tmp/ros/setup.bash
