### ISSUE TITLE
Apollo 5.0  car does NOT start driving autonomously in GTX 1080

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#10882]
Apollo 5.0 car does not start driving autonomously after following official steps : 
'https://github.com/lgsvl/apollo-5.0'

### System information

- **UBUNTU 18.04)**:
-  cuda 10.2 , GPU : GTX 1080 , nvidia-driver v: 440.59 
- **Apollo version 5.0

### Steps to reproduce the issue:
- **Kindly look at the Youtube video I made on the same :https://www.youtube.com/watch?v=pAW0ydJoLPA**:

## Expected behaviour : 
This is a video of Apollo is expected to behave : 
 https://www.youtube.com/watch?v=19eo9ZffCKQ&feature=youtu.be

**Comment by ntutangyun** [comment]
you need to give the car a little bit push manually by pressing `UP` button. then Apollo will take over and drive automatically.

**Comment by Avps1** [comment]
Thank you @ntutangyun for your input. Closing the issue now.
