### ISSUE TITLE
Will PlanningContext::Instance() cause chaos if there are two reference lines?

### ISSUE THREAD

**Issue by rrenjie** [ApolloAuto/apollo#10881]
I know that PlanningContext is a singleton class to store some persistent planning status data, like whether ADC is in lane borrowing, etc. The problem is, if there are two reference lines (in lane change road segment), two reference_line_infos will share and modify a common PlanningContext::Instance(), is this correct? Looking forward to your answers. This question has bothered me for some time.

**Comment by jmtao** [comment]
@rrenjie the status in PlanningContext is usually created and shared among traffic rules, scenario's stages, and tasks.  They are not per reference line. I don't see there's any problem in lane change or lane borrow when they use PlanningContext. 
Or if you can give a more specific example? e.g. which value in PlanningContext might be conflict because there are multiple reference lines.

**Comment by rrenjie** [comment]
> @rrenjie the status in PlanningContext is usually created and shared among traffic rules, scenario's stages, and tasks. They are not per reference line. I don't see there's any problem in lane change or lane borrow when they use PlanningContext.
> Or if you can give a more specific example? e.g. which value in PlanningContext might be conflict because there are multiple reference lines.

Thanks for your reply. For example, the front_static_obstacle_cycle_counter and front_static_obstacle_id maintained in PathAssessmentDecider, or the crosswalk_id and stop_time maintained in Crosswalk. If there are two reference lines, it is likely that these persistent values would be set/read twice in a planning cycle. I would like to make it clearer like the following:

If there are two reference lines, say A and B. The flow would go like this:
Crosswalk rule on A read and set crosswalk_id and stop_time --> Crosswalk rule on B read and set crosswalk_id and stop_time (set by A in this cycle) --> (next planning cycle) Crosswalk rule on A read and set crosswalk_id and stop_time (set by B in the previous cycle) -> ...

The problem here is that some values in planning_status are associated with reference lines, and I don't think they should be stored in PlanningContext and shared across multiple reference lines. Looking forward to your reply.

**Comment by rrenjie** [comment]
@jmtao Hi, could you kindly address my question? Thank you.

**Comment by jmtao** [comment]
@rrenjie now I see what you mean. Good catch!
There might be more than one reference lines only if there's lane changes requested by routing. Currently, we only do lane change in LANE_FOLLOW scenario. 
For all the other scenarios, we only plan for one reference line. 
And for traffic rules, we plan for all reference lines. The information used by traffic rules shall almost be the same along multiple reference lines at the same moment. 
We'll definetly need to address this issue when we support LANE_CHANGE in other scenarios. 
Thanks for supporting Apollo!

**Comment by rrenjie** [comment]
@jmtao Thanks for your reply. I think traffic rules are the same with deciders/optimizers, which are executed per reference line. So maybe it is better to store related traffic-rule status on each reference line to avoid any unpredicatable issues in LANE_CHANGE?

**Comment by jmtao** [comment]
@rrenjie sure we'll keep that in mind, and improve it in future release.  Thanks again.
