### ISSUE TITLE
Bug in bash script to enable Apollo build in GPU mode

### ISSUE THREAD

**Issue by ajay1606** [ApolloAuto/apollo#10897]
**Describe the bug**
Apollo.sh script to enable build-in GPU has a bug in line number 130.
It should be 
` **if [ "${USE_GPU}" = ="1" ] ; then**`
Instead 
` **if [ "${USE_GPU}" = "1" ] ; then**`

**Screenshots**

![Screenshot from 2020-03-27 11-37-05](https://user-images.githubusercontent.com/29722843/77715679-97b8f700-701f-11ea-8c31-a57d109823f7.png)

Regards,
Ajay

**Comment by ycool** [comment]
It is expected in bash syntax.  More details can be found at 
https://stackoverflow.com/questions/20449543/bash-equality-operators-eq
