### ISSUE TITLE
Does the apollo code not include  code of avoiding obstacle?

### ISSUE THREAD

**Issue by Jackie2016** [ApolloAuto/apollo#109]
I read the document of apollo,i find the hardwares in vechile have no two-eyes camera which generally rebuild the 3D enviroment to avoid obstacles.Could you tell me how to avoid obstacle or other vechiles on road when car embeded with apollo-1.0  is in auto-driving mode.thanks

**Comment by ycool** [comment]
Thanks for your interest in Apollo.
From the [Quit Start Guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md)
> Apollo 1.0, also referred to as the Automatic GPS Waypoint Following, works in an enclosed venue such as a test track or parking lot. It accurately replays a trajectory and the speed of that trajectory that a human driver has traveled in an enclosed, flat area on solid ground.
> At this stage of development, Apollo 1.0 cannot perceive obstacles in close proximity, drive on public roads, or drive in areas without GPS signals.

The future road map is disclosed in the Apollo Website http://apollo.auto/ 

Duplicate with #99
