### ISSUE TITLE
Proc() callback function and Reader

### ISSUE THREAD

**Issue by Kailiangdong** [ApolloAuto/apollo#10903]
Hello. I am new to Apollo 5.0.
I have a question that in some component, why some information/message stay in parameter of Proc() without creating reader, while other information read message from CyberRT by creating reader in Init().

For example, in planning component:
"prediction::PredictionObstacles, canbus::Chassis, localization::LocalizationEstimate" ,these three are set as parameter in Proc().
While, Routing, Trafficlight, PadMessage and Mapmsg create Reader.

**Comment by ycool** [comment]
The message from Proc() will be fused by CyberRT system and Proc() will be called when these data are ready. The data from Reader are called from applications and its frequency can be controlled by applications. And they are only used when needed.

**Comment by warden2018** [comment]
@ycool Hello, can I get the localization reader in Planning module? Does cyber have the function to return the reader pointer? I really want to get latest localization result by using the pointer. Thanks!
