### ISSUE TITLE
SchedulerChoreography DispatchTask processor_id issue ? 

### ISSUE THREAD

**Issue by daohu527** [ApolloAuto/apollo#10902]
https://github.com/ApolloAuto/apollo/blob/a7aedb92df6aebf60950957ae6fb4bfb00b5b088/cyber/scheduler/policy/scheduler_choreography.cc#L157-L160

The CRoutine's default processor_id = -1.  And we set the processor id from the conf file.  
```
    if (taskconf.has_processor()) {
      cr->set_processor_id(taskconf.processor());
    }
```

If we don't set the processor_id in conf file. **the processor_id will be -1.  And then we will access an invalid vector index "-1"**.
```
  // The pid will default -1 !!!!!!!!
  uint32_t pid = cr->processor_id();
  if (pid < proc_num_) {
    // Enqueue task to Choreo Policy.   Invalid index -1
    static_cast<ChoreographyContext*>(pctxs_[pid].get())->Enqueue(cr);
  } else {
```

Maybe the code should add a condition like this? add "pid >= 0" will better than "pid != -1". 
```
  if (pid < proc_num_ && pid >= 0 ) {
```

**Comment by zhangchaoltt** [comment]
pid is defined as uint32_t， so  pid >= 0

**Comment by daohu527** [comment]
Thanks for your reminder,
**This code is too vague. int to uint32_t then convert -1 to unit 4294967295 !!!**
```
inline int CRoutine::processor_id() const { return processor_id_; }
```
