### ISSUE TITLE
Cyber not receiving messages from Record File

### ISSUE THREAD

**Issue by NeelNarvekar** [ApolloAuto/apollo#10918]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
After building apollo I launched dreamview and used cyber_recorder to play a record file that I had previously captured. The record file plays, but it seems that cyber is not receiving any messages, so the pipeline doesn't run and nothing shows up in dreamview. This was working for me before so not sure what went wrong, any help would be appreciated!

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/33188523/78068735-c69bd980-734d-11ea-8024-b61974cc5fea.png)

**Comment by Avps1** [comment]
Hello, 
Could you tell me how you have captured the file ?

**Comment by NeelNarvekar** [comment]
I used the cyber_recorder api to capture the record before. I've since fixed this issue by wiping my computer and installing ubuntu fresh. I backed up my apollo version and loaded it onto fresh ubuntu and everything worked. This makes me think it may have been an issue with my firewall or some other networking issue

**Comment by Avps1** [comment]
Thanks for your comment. :)
