### ISSUE TITLE
cyber_channel info [Error] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 32: invalid continuation byte

### ISSUE THREAD

**Issue by XuehuanYang** [ApolloAuto/apollo#10923]
### System information

- **OS Platform and Distribution Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 5.0:**

### Steps to reproduce the issue:

**[Success]yxh@in_dev_docker: cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop**
**[Success]Run Offline Demo & successfully goto Dreamview and the car is moving around**
**[Success]yxh@in_dev_docker: /apollo$ cyber_channel list**
The number of channels is:  39
/apollo/canbus/chassis
/apollo/canbus/chassis_detail
/apollo/common/latency_records
/apollo/control
/apollo/control/pad
/apollo/drive_event
/apollo/guardian
/apollo/hmi/audio_capture
/apollo/hmi/status
/apollo/localization/msf_gnss
/apollo/localization/msf_lidar
/apollo/localization/msf_status
/apollo/localization/pose
/apollo/monitor
/apollo/monitor/system_status
/apollo/navigation
/apollo/perception/obstacles
/apollo/perception/traffic_light
/apollo/planning
/apollo/prediction
/apollo/relative_map
/apollo/routing_request
/apollo/routing_response
/apollo/sensor/camera/front_6mm/image
/apollo/sensor/camera/front_6mm/image/compressed
/apollo/sensor/gnss/best_pose
/apollo/sensor/gnss/corrected_imu
/apollo/sensor/gnss/gnss_status
/apollo/sensor/gnss/imu
/apollo/sensor/gnss/ins_stat
/apollo/sensor/gnss/ins_status
/apollo/sensor/gnss/odometry
/apollo/sensor/gnss/raw_data
/apollo/sensor/gnss/rtk_eph
/apollo/sensor/gnss/rtk_obs
/apollo/sensor/lidar128/compensator/PointCloud2
/apollo/storytelling
/tf
/tf_static

**[Error] yxh@in_dev_docker: /apollo$ cyber_channel info /apollo/perception/obstacles**
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 32: invalid continuation byte

**The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set**
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 408, in <module>
    _channel_cmd_info(argv)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 310, in _channel_cmd_info
    channel_info(args[0])
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 270, in channel_info
    channlesinfo_dict = cyber.ChannelUtils.get_channels_info()
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 395, in get_channels_info
    return _CYBER.PyChannelUtils_get_channels_info(sleep_s)
SystemError: <built-in function PyChannelUtils_get_channels_info> returned a result with an error set

**yxh@in_dev_docker:/apollo$ cyber_channel echo /apollo/perception/obstacles**

E0401 11:51:06.767853 12730 py_cyber.cc:654] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 233, in reader_callback
    sub[1](proto)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 351, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 364, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set
E0401 11:51:07.043089 12730 py_cyber.cc:654] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 233, in reader_callback
    sub[1](proto)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 351, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 364, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set

**yxh@in_dev_docker: /apollo$ cyber_channel list**          

Please advice. Many thanks for your kind support and assistance.

**Comment by storypku** [comment]
@changsh726 Please help check if this was already fixed.

**Comment by XuehuanYang** [comment]
Fixed with thanks.  
$source scripts/setup.bash
