### ISSUE TITLE
cyber channel info 

### ISSUE THREAD

**Issue by JianJieLin** [ApolloAuto/apollo#10924]
in apollo 5.5, by playing with demo_3.5.record, I can not output the the correct output by using cyber_channel info /apollo/control. The error message is "SystemError: <class 'UnicodeDecodeError'> returned a result with an error set"

**Comment by JianJieLin** [comment]
the full error message is
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 32: invalid continuation byte 
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
 File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 408, in <module>
    _channel_cmd_info(argv)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 310, in _channel_cmd_info
    channel_info(args[0])
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 270, in channel_info
    channlesinfo_dict = cyber.ChannelUtils.get_channels_info()
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 396, in get_channels_info
    return _CYBER.PyChannelUtils_get_channels_info(sleep_s)
SystemError: <built-in function PyChannelUtils_get_channels_info> returned a result with an error set

**Comment by storypku** [comment]
Please help check if this issue is already fixed ? @changsh726

**Comment by changsh726** [comment]
This error has been fixed in  #12364, so this issue will be closed. Thank you for your support to Apollo!
