### ISSUE TITLE
Help needed for debugging the Perception module with VSCode

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#10932]
I am trying to set breakpoints and debug the Perception module. 
The main document I am using for this is : 'https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md'. 
I have replaced the planning module wih the PID of the Perception module in .vscode/tasks.json, like so : bash docker/scripts/dev_start_gdb_server.sh (PID of Perception module) 1111". 
The debugging runs fine, but for all the breakpoints that I have set, it shows the following error : 
"Module containing this breakpoint has not yet been loaded or the breakpoint address could not be obtained". 
![Perception_Debu](https://user-images.githubusercontent.com/50120641/78295625-bc840180-752c-11ea-9450-8a6604ac5d6d.png)

The strange thing is, I have set multiple breakpoints belonging to multiple files that belong to /apollo/modules/perception, but all of these breakpoints show the same error. 

Is there a better way to debug the perception module ?

### System information
Ubuntu 18.04 
Apollo 5.0 
Debugging using VSCode

### Steps to reproduce the issue:
- **1.Follow the steps mentioned in https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md . 

2. Replace the line #bash docker/scripts/dev_start_gdb_server.sh planning 1111 in tasks.json with 
#bash docker/scripts/dev_start_gdb_server.sh (PID of perception) 1111 
![Screen Shot 2020-04-02 at 10 05 19 PM](https://user-images.githubusercontent.com/50120641/78296442-0de0c080-752e-11ea-94e0-7d774c748b8f.png)

**:
**Expected Behaviour :** 
I should be able to set breakpoints, then as the program hits those break points, step into each one of them.

**Comment by unacao** [comment]
solved in #10968

**Comment by Avps1** [comment]
@unacao Hi, Could you please look into #10968 ? Its a bug and it hasnt been resolved yet.

**Comment by vilon888** [comment]
> @unacao Hi, Could you please look into #10968 ? Its a bug and it hasnt been resolved yet.

@Avps1 , you can change line 184 to 
            env ${APOLLO_ENV} bash "${build_sh}" **_--config=dbg_** --config=gpu "$@"
 in apollo.sh, and then rebuid with command:
./apollo.sh build_gpu

then you can hit the point, that's all.
