### ISSUE TITLE
Supported GPU

### ISSUE THREAD

**Issue by faysalhossain2007** [ApolloAuto/apollo#10931]
I want to buy a new GPU for PC. Can you please confirm whether the following configuration work or not? Specially whether the GPU is compatible with APOLLO?

![Screen Shot 2020-04-02 at 2 22 06 PM](https://user-images.githubusercontent.com/1239654/78284410-5fb52680-74ed-11ea-88ae-d8316c0889e7.png)

**Comment by NeelNarvekar** [comment]
The RTX 2070 isn't currently compatible with apollo. Apollo doesn't support the turing architecture, you'll need an older GPU.

**Comment by faysalhossain2007** [comment]
Are you suggesting to buy GTX (pascal one)? Do you know when Apollo will provide support for RTX GPU?

**Comment by Avps1** [comment]
Yes. GTX 1070/80 will work. The RTX series wont.

**Comment by faysalhossain2007** [comment]
Got it. But I am not able to find any GTX 1070/80. Moreover, I am thinking if I need to have RTX in the near future, then I might also need to change the GPU. Do you know when they will provide support for RTX?

**Comment by storypku** [comment]
> Got it. But I am not able to find any GTX 1070/80. Moreover, I am thinking if I need to have RTX in the near future, then I might also need to change the GPU. Do you know when they will provide support for RTX?

We are currently working on  Apollo's GPU support improvement, covering GPU card of architecture Pascal, Volta, Turing, with compute capabilities range from 6.0/6.1 to 7.0/7.2 and 7.5.

**Comment by faysalhossain2007** [comment]
Great! Just to be sure Apollo will keep supporting the older GPU ( Specifically NVIDIA GTX 1070 ). Right?

**Comment by storypku** [comment]
> Great! Just to be sure Apollo will keep supporting the older GPU ( Specifically NVIDIA GTX 1070 ). Right?

Yeap! SM value for NVIDIA GTX 1070 cards is 6.1.

**Comment by storypku** [comment]
> Got it. But I am not able to find any GTX 1070/80. Moreover, I am thinking if I need to have RTX in the near future, then I might also need to change the GPU. Do you know when they will provide support for RTX?

As of commit master-c3768291de, Our gpu support for nvidia gpus with capabilities [6.0, 6.1, 7.0, 7.2, 7.5] has been complete.  So RTX series are supported now.

```
Pascal (CUDA 8 and later)
SM60 or SM_60, compute_60 — Quadro GP100, Tesla P100, DGX-1 (Generic Pascal)
SM61 or SM_61, compute_61 — GTX 1080, GTX 1070, GTX 1060, GTX 1050, GTX 1030, Titan Xp, Tesla P40, Tesla P4, Discrete GPU on the NVIDIA Drive PX2
SM62 or SM_62, compute_62 — Integrated GPU on the NVIDIA Drive PX2, Tegra (Jetson) TX2
Volta (CUDA 9 and later)
SM70 or SM_70, compute_70 — DGX-1 with Volta, Tesla V100, GTX 1180 (GV104), Titan V, Quadro GV100
SM72 or SM_72, compute_72 — Jetson AGX Xavier
Turing (CUDA 10 and later)
SM75 or SM_75, compute_75 — GTX Turing — GTX 1660 Ti, RTX 2060, RTX 2070, RTX 2080, Titan RTX, Quadro RTX 4000, Quadro RTX 5000, Quadro RTX 6000, Quadro RTX 8000
```
