### ISSUE TITLE
Apollo continuous lane change too slow. 

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10949]
Hi team, 

**VIDEO**
https://drive.google.com/file/d/1Hv5NYVtYywm_50mjrv4FCuUZVV-AoL4X/view?usp=sharing

**Describe the bug**

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween. 

The vehicle is spawned **near the first point of the starting lane**, and the routing destination is set **near the last point of the end lane**. 

All the videos are recorded without any obstacle. 
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

**To Reproduce**
1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo to take over.

**Expected behavior**
After the junction, Apollo is expected to perform **three continuous lane changes to the left after passing the junction.** However, Apollo takes too much distance completing each lane change, and ends up not reaching the destination point. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 1804
 - Browser Chrome

**Comment by daohu527** [comment]
The car speed is 30 km/h, and then it may not be possible to change three lanes in a short distance. Are there any planning logs indicating errors or unable to turn to the leftmost lane?

**Comment by ntutangyun** [comment]
here are JSON logs i've saved during the runtime. Can't remember which one is the correct one for the video. but they should be the same.

https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EdWb11ytVQ1InnLNIW6k_sABLBV3I741SVbinvcaRpt2fg?e=85pSiC

https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EQvieUTuGs5Cq_nJ0Ez_aIcBIShQDopQZs4oSyW83YeEvg?e=Kj14da

I think the issues is not about planning errors, it's about Apollo knows where the destination is, and still decided to now slow down for continuous lane change.

**Comment by daohu527** [comment]
> I think the issues is not about planning errors, it's about Apollo knows where the destination is, and still decided to now slow down for continuous lane change.

You ’re right, it does n’t slow down. **I think it may be a planning decision-making problem. There is no slowdown state when changing lanes**.  

There is a **lane change decider** to decide whether to change the lane.  I need to look at the code for more details.  
```
default_task_config: {
  task_type: LANE_CHANGE_DECIDER
  lane_change_decider_config {
    enable_lane_change_urgency_check: false
    enable_prioritize_change_lane: false
    enable_remove_change_lane: false
    reckless_change_lane: false
    change_lane_success_freeze_time: 1.5
    change_lane_fail_freeze_time: 1.0
  }
}
```
