### ISSUE TITLE
Apollo new Simulation

### ISSUE THREAD

**Issue by alejandroreynagit** [ApolloAuto/apollo#10956]
Hi, I am new on this Apollo world. I already installed all dependencies and was able to run the offline simulation samples in dreamview, everything works as supposed to. At the end what I have to do es to create a new custom scenario and finally put a UI on top of it, this last part is not essential now.

I have seen that I can do scenarios and so in dreamview but also through the cyber_visualizer, how should I proceed? I have been looking and trying out there but no success.

Thanks!

**Comment by ycool** [comment]
If you'd like to test custom scenario, you do it at https://azure.apollo.auto/. 
1. request access at https://azure.apollo.auto/ for your account. 
2. In the left menu bar, click Scenario Management/Scenario Editor to create your own scenario and test it.
