### ISSUE TITLE
in the Apollo how to analysis continental ARS 408-21 protocol

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#10959]
when I used continental ARS 408-21 to obtain the details(such as velocity、distance and acceleration) about obstacle. I don't know the protocol of this radar.
 so do anybody know what the  ARS 408-21's protocol is, or how obtain it.
(I have obtain the data, but didn't know how to analysis them.)
Thank you!!!

**Comment by jilinzhou** [comment]
Read the code under modules/drivers/radar/conti_radar/protocol.

**Comment by 13940267943** [comment]
> Read the code under modules/drivers/radar/conti_radar/protocol.
Thank you so much to answer my question.
Now I have seen the code under modules/drivers/radar/conti_radar/protocol.
for example.ObjectExtendedInfo60D,I know which bit respect accelerate. But I don't know what the unit of it.(m/s2 or km/h2).and also what the oritation_angle's unit is.
so I think I need a part protocol of continental ARS 408-21,to know the accurate information that continental ARS 408-21 provided.

**Comment by greenfield932** [comment]
velocity - m/s, long/lat displacement - m, acceleration m/s^2, radar cross section dbm^2,
Length/Width - m, orientation angle - degrees

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
