### ISSUE TITLE
Apollo routing module produces an inefficient route.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10950]
Hi team,

**VIDEO**
https://drive.google.com/file/d/1uaCuQAX6WS2_7tAH-PN2YtTMXb5jJorY/view?usp=sharing

**Describe the bug**

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween.

The vehicle is spawned **near the first point of the starting lane**, and the routing destination is set **near the last point of the end lane**.

All the videos are recorded without any obstacle.
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

**To Reproduce**

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo to take over.

**Expected behavior**
Apollo is expected to perform **three continuous lane changes to the left after right turning at the junction**. However, Apollo routed a very big route instead of the shorter path I believe. 

Let’s take look at the reference case:
https://drive.google.com/file/d/1g0_gRwvpX-eOBNC8ik7obM-wYDOlxuun/view?usp=sharing

This case has the same starting point, the only required to perform **two continuous lane changes to the left after right turning at the junction**. This time, Apollo actually finishes smoothly.

**Desktop (please complete the following information):**

OS: Ubuntu 1804
Browser Chrome

**Comment by daohu527** [comment]
What's you "produces an inefficient route" mean ? 

I found the bug is, if you have three lane, and you want to turn from rightest to the leftest lane. **There will be three routing path and the path is the same as the lane reference line.** 

This because the routing module will just return the lanes the car will pass, but not the real path the car will run. So the dreamview will get the lanes and draw the lane reference lines to red, this maybe a display error.

**Comment by ntutangyun** [comment]
> This because the routing module will just return the lanes the car will pass, but not the real path the car will run. 

I also noticed this. If a lane is included in one of `passage` in the route, the whole lane's reference line will be highlighted in red. But this is ok i guess.

What i mean by inefficient is that, if you check the refernce case's video (the second link). 

The only difference for two case is that, reference case requires two continuous lane change after junction, and the first case requires three lane changes. 

However, the routings is completely different where in reference case, Apollo turned at the junction, and performed two continuous lane changes as expected, but in first case, Apollo routed a very big circle, instead of simply perform one more lane change. 

I'm just curious if this is considered as inefficient?

**Comment by daohu527** [comment]
You are right.  I think you can check it by two steps.  
1. Check whether the routing lanes is connected use the tool in "apollo\modules\tools\routing\debug_topo.py", if the lane is connected in topo graph, then this is OK.

2. The routing path is generated by A* dependency on the cost of the node and edge. The node is the lane and the edge is the connected of the neighbor lanes (virtual concept). Therefore, the possible cost of a continuous left turn for a short distance will be greater than the cost after a round. I haven't found any relevant visualization tools to prove it.   

The following are the calculation methods of costs. They are based on some rules. For example, the cost of a left turn is greater than that of a right turn, the cost of a right turn is greater than that of a left turn, the speed limit is greater than that of no speed limit, and the traffic light crosses as little as possible. Apollo call them "the cost".  

* the routing conf
```
base_speed: 4.167
left_turn_penalty: 50.0
right_turn_penalty: 20.0
uturn_penalty: 100.0
change_penalty: 500.0
base_changing_length: 50.0
```

* The node cost cacl method.
```
  double cost = lane_length * ratio;
  if (lane.has_turn()) {
    if (lane.turn() == Lane::LEFT_TURN) {
      cost += routing_config.left_turn_penalty();
    } else if (lane.turn() == Lane::RIGHT_TURN) {
      cost += routing_config.right_turn_penalty();
    } else if (lane.turn() == Lane::U_TURN) {
      cost += routing_config.uturn_penalty();
    }
  }
  node->set_cost(cost);
```
In this case the cost is left turn is 50 + 50

* edge cost
```
  edge->set_cost(0.0);
  if (type == Edge::LEFT || type == Edge::RIGHT) {
    const auto& target_range =
        (type == Edge::LEFT) ? node_from.left_out() : node_from.right_out();
    double changing_area_length = 0.0;
    for (const auto& range : target_range) {
      changing_area_length += range.end().s() - range.start().s();
    }
    double ratio = 1.0;
    if (changing_area_length < routing_config.base_changing_length()) {
      ratio = std::pow(
          changing_area_length / routing_config.base_changing_length(), -1.5);
    }
    edge->set_cost(routing_config.change_penalty() * ratio);
  }
```
 You can see the ratio is pow(x,-1.5), which below.  
![1](https://user-images.githubusercontent.com/10419854/78466906-88316080-7739-11ea-99e0-eb5507e266b6.JPG)

If the changing_area_length / routing_config.base_changing_length() is less than 1, the ratio may be infinite, for example if changing_area_length is 25 and the base_changing_length is 50, the 0.5^(-1.5) = 2.8. and the change_penalty is 500.

So the above situation may exist, and also we need a debug tool to verify it.
