### ISSUE TITLE
Planning module goes crazy..

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10958]
Hi team,

***VIDEO:***
https://drive.google.com/file/d/1ppIyv_p9eRJqP1IxZoktMnN24AYzbUUt/view?usp=sharing

***Describe the bug***

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween.

The vehicle is spawned near the first point of the starting lane, and the routing destination is set near the last point of the end lane.

All the videos are recorded without any obstacle.
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

***To Reproduce***

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo to take over.

***Expected behavior***
Apollo is expected to perform a right lane change and turn right at the junction `J_90`,
but it enters the junction in the middle of two neighboring lanes and planninng suddenly goes crazy about which route to follow...

Desktop (please complete the following information):

OS: Ubuntu 1804
Browser Chrome

**Comment by ycool** [comment]
It is caused by the starting point is too close to the junction for lane change. It triggers rerouting. There are two possible solutions: 1. changing the starting point so there is enough room for lane change. 2. you can disable rerouting behavior at https://github.com/ApolloAuto/apollo/blob/master/modules/planning/conf/traffic_rule_config.pb.txt#L54

**Comment by ntutangyun** [comment]
Hi @ycool , thanks for your reply. I have two follow up questions

1. Does Apollo know that it's too short for it to perform the lane change before junction
2. With a new route path has provided, what has caused the planning module to bounce between those routed paths. 

Thanks again.

**Comment by ntutangyun** [comment]
I have another question regarding the rerouting request:

Does planning module send additional information with the rerouting request, such as which lane the vehicle actually cannot go by planning ?

In the videos it shows that, before entering the junction, planning module has sent a lot of rerouting request, but the routing module always returns the same result i.e. right lane change and turn right in junction. 

If planning module tells routing module that right lane change is not possible during rerouting module, the routing module probably would've rerouted another valid path. 

Thanks in advance.
