### ISSUE TITLE
What kind of Kalman Filter does Apollo use for multi-sensor fusion?

### ISSUE THREAD

**Issue by songyuc** [ApolloAuto/apollo#10957]
Hi, guys,
I want to know What kind of Kalman Filter  Apollo use for multi-sensor fusion?
Is it Unscented Kalman Filter (UKF)?
Your answer or idea will be appreciated!

**Comment by szykp** [comment]
不是UKF，EKF

**Comment by songyuc** [comment]
@szykp ,哦哦，你说Apollo里面用的是EKF吗？

**Comment by szykp** [comment]
是的

**Comment by songyuc** [comment]
@szykp ,谢谢你的回复；
还想请问一下，这个函数的接口具体是哪一个，你知道吗？

**Comment by szykp** [comment]
common/math/kalman_filter

**Comment by songyuc** [comment]
@szykp ,感谢你的解答！

**Comment by songyuc** [comment]
@szykp ，请问一下，您是Apollo的开发者吗？
