### ISSUE TITLE
Planning revert back in middle of lane changing without any obstacles.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10954]
Hi team,

**VIDEO**
https://drive.google.com/file/d/1S8aDeL7H_2WpytUZy4EHACvRlKeihfd8/view?usp=sharing

**Describe the bug**

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween.

The vehicle is spawned **near the first point of the starting lane**, and the routing destination is set **near the last point of the end lane**.

All the videos are recorded without any obstacle.
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

**To Reproduce**

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo to take over.

**Expected behavior**
In this case, Apollo is expected to do **a right lane change after the junction.** However, during the lane change, it changed its mind and reverted back, without any obstacle around.

**Desktop (please complete the following information):**

OS: Ubuntu 1804
Browser Chrome

**Comment by yifeijiang** [comment]
Planning has a few rules for lane change before the destination. It is possible that in the middle of the lane change, one of the rules was triggered (e.g, distance to the destination) and the lane change action was terminated.

**Comment by ntutangyun** [comment]
@yifeijiang Thanks for your reply. Shall I close the issue now or leave it open as a reference for front-line developers?
