### ISSUE TITLE
Planning module stopped in middle of junction turn

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10967]
Hi team,

***VIDEO:***
Follow view:
https://drive.google.com/file/d/1LadAKYAvzSF1CsYknMyYqpPmBFYr-FoL/view?usp=sharing

Route Editor Top View:
https://drive.google.com/file/d/1nzX-gZQFE2n0-0hl7RnTo18gcbm3_SQr/view?usp=sharing

***Describe the bug***

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween.

The vehicle is spawned near the first point of the starting lane, and the routing destination is set near the last point of the end lane.

All the videos are recorded without any obstacle.
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

***To Reproduce***

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo to take over.

***Expected behavior***
Apollo is expected to turn right at junction `J_50`. 
But in the middle of the turn, Apollo plannning module stopped planning forward. 
It seems to be due to that the turn is too sharp for Apollo. 

***Desktop (please complete the following information):***

OS: Ubuntu 1804
Browser Chrome

**Comment by yifeijiang** [comment]
Seems the road is too narrow for such a sharp turn. Planing leverages lane boundary as a constrain for path generation for most of the scenarios.

**Comment by ntutangyun** [comment]
@yifeijiang Thanks for your reply.  Shall I close the issue or leave the issues open as a reference?
