### ISSUE TITLE
Apollo driving along the lane boundaries during overtake and change lane within junction.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#10986]
Hi team,

***VIDEO:***
https://drive.google.com/file/d/1E8taQyQq_acPfMLTRmHZP1Spbq6y9PVR/view?usp=sharing

***Describe the bug***

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. I discovered some issues, which I think might relate to Apollo's routing, planning and control modules.

In the video, Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction inbetween.

The vehicle is spawned near the first point of the starting lane, and the routing destination is set near the last point of the end lane.

Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

***To Reproduce***

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video.
4. Set static NPC vehicles at the same starting lane of Apollo vehicle, but with distance offset at 30m, 60m, 90m, 120m, 150m and 180m, all the way to the end of the lane.
5. Drive a bit forward in the simulator to let Apollo to take over.

***Expected behavior***
Apollo is expected to perform a left lane change instead of keep trying to complete the overtake action, which I suppose keeps Apollo driving on the lane boundary for quite a long time. 

Also, after failed to drive back to the original lane due to obstacles BEFORE junction, Apollo then tried to drive back within junction and I suppose this is not safe to change lane within junction.

***Desktop (please complete the following information):***

OS: Ubuntu 1804
Browser Chrome

**Comment by ntutangyun** [comment]
I havn't went through the planning module source code yet. 
But may I ask what are the conditions for the planning module to request a rerouting. 

For the case in the video, I think Apollo wouldn't have the problems if it requested a rerouting after lane changing to the left lane duing the overtake...

**Comment by jmtao** [comment]
@ntutangyun routing is decided based on map. It's not changed on the fly based on driving environment. As for now, Apollo changes lanes only if routing requests to. 
So in this case, Apollo is not expected to change lane. Ego vehicle is "side-passing" those cars parked on the driving lane where the routing ls. 
I'm not sure where your destination is and why the routing became like that post junction. I need more video view on the routing itself.

**Comment by ntutangyun** [comment]
hi @jmtao , the destination is the **end of the left most lane** after the junction. 

In order to reach destination, Apollo could perform lane changes to the left then go straight or go straight first then after junction lane change to the left. 

It seems that Apollo would always perform lane change after junction in similar cases. 

there are three behaviors which i personnally consider not safe. 
1. 'side-passing' or drive along the lane boundaries for really long distance
2. enters the junction at the lane boundary instead of within road lanes
3. performed a lane change within the junction. 

Please kindly advise.

**Comment by jmtao** [comment]
@ntutangyun the routing makes sense now. We do not support lane changes if adv is inside junction or too close to junction. That's why lane changes start in routing post junction. 

And yes, all your suggestions are great. They do address safety issues. We'll add more strict checks while we do side-passing. In this driving scenario, ADV will have to be stuck I think. 
Thanks for supporting Apollo.

**Comment by ntutangyun** [comment]
@jmtao thanks for the reply. closing the issue for now.
