### ISSUE TITLE
Perception module crashes when running probabilistic fusion with both LiDAR and camera data

### ISSUE THREAD

**Issue by LeoAnnArbor** [ApolloAuto/apollo#11046]
**Describe the bug**:
Hi, there

I'm trying to go through the exercise of running the [perception offline](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) with the fusion pipeline using recorded LiDAR, front 6mm and front 12 mm data. However, whenever I tried to run both LiDAR and camera fusion pipeline in the same process via `dag_streaming_perception.dag` and `dag_streaming_perception_camera.dag`, I got a segfault in gdb as follows: 

```
Thread 6 "mainboard" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe623f700 (LWP 28326)]
0x00007fff540f5dc9 in Eigen::internal::triangular_solve_vector<float, float, long, 1, 2, false, 0>::run(long, float const*, long, float*) () from /usr/local/lib/libpcl_features.so.1.9
```

And the perception crashes thereafter. I'm wondering if anyone has any idea or insights why this is the case?

I should also mention that when running the same data with only LiDAR perception, there were no issues for perception module. Messages were published correctly via the `apollo/perception/obstacles` message.

**Specs**:

- Ubuntu 16.04 with Nvidia driver 430.50 and CUDA 10.1

- GeForce GTX 1080 GPU

- Apollo version: r5.5.0

**Comment by ideasplus** [comment]
Hi, I'm intersted in using multi-sensor data to test probabilistic fusion. But I can't find such data as you describe which include LiDAR, front 6mm and front 12 mm.How did you find or record such multi-sensor data？As for your question, can you provide more info about the bug?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
