### ISSUE TITLE
How i get the base_map.xml of San Francisco, which is used in lgsvl with Apollo 3.5? 

### ISSUE THREAD

**Issue by zeyu-zha** [ApolloAuto/apollo#11052]
### System information

- **Apollo version : 3.5

### Description:
Hello Apollo Team,
i am trying to use the lgsvl with Apollo 3.5. In the repository "lgsvl /apollo-simulator-map", i have already find out the hdmap data of San Francisco. But in that repository there are only base_map.bin file, but no base_map.xml file. I would like to ask you, could you also provide the base_map.xml file based on the existent base_map.bin file?

**Comment by ntutangyun** [comment]
@zeyu-zha You could choose your favorite language and use its protobuf library to parse the content base_map.bin file.

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
