### ISSUE TITLE
Help needed : How is 2D box(YOLO) converted to 3D in object detection in Perception Module

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#11053]
Hi, 
I was studying Object detection/tracking in the Perception Module , where I came across the 2D to 3D conversion module under detection - https://github.com/ApolloAuto/apollo/blob/master/docs/specs/perception_apollo_3.0.md#2d-to-3d-bounding-box. 
It is written that a module converts the 2D boxes output of the YOLO to 3D, but I couldn't find the corresponding code. 
It would be of great help if you could tell me the location of the code which converts the 2D YOLO boxes to 3D . 
Related issue : https://github.com/ApolloAuto/apollo/issues/5819
Thanks in advance. 

![Screen Shot 2020-04-16 at 8 17 19 PM](https://user-images.githubusercontent.com/50120641/79491811-48168b80-801f-11ea-9d7d-72b5f8370673.png)

**Comment by ideasplus** [comment]
I guass this code can convert 2d box to 3d box [https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/obstacle/transformer/multicue/multicue_obstacle_transformer.cc](url)

**Comment by Avps1** [comment]
> I guass this code can convert 2d box to 3d box [https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/obstacle/transformer/multicue/multicue_obstacle_transformer.cc](url)

Thanks a tonne for your response.
