### ISSUE TITLE
Apollo Dreamview frontend develop and rebuild

### ISSUE THREAD

**Issue by Kailiangdong** [ApolloAuto/apollo#11064]
Hello, I have a question about Apollo Dreamview(5.0)
I want to have some small change to Apollo Dreamview, after I change the backend and frontend , I rebuild apollo via ./apollo.sh build. But nothing new happen in Dreamview ,even console.log() not work.
So I suggest , besides ./apollo.sh build, there are an additional way to rebuild the frontend. If some some know and can share to me, I will be very appreciated,  Thank you very much.

**Comment by daohu527** [comment]
## build the dreamview frontend
If you want to just build the dreamview frontend, just run.
```
  cd modules/dreamview/frontend
  yarn build
```

## build the whole module
```
bazel build //modules/dreamview/...
```

**Comment by icolwell-as** [comment]
FYI, you may also need to run `yarn install` before the `yarn build`.
