### ISSUE TITLE
How can I get multi-sensor data to test apollo perception module？

### ISSUE THREAD

**Issue by ideasplus** [ApolloAuto/apollo#11061]
# System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04):Ubuntu 14.04
- **Apollo installed from (source or binary):source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0):5.0

Hi, I want to use multi-sensor data to test perception module offline. Specifically I need **recorded rosbag or record** which includes camera, lidar and radar data simultaneously to test sensor fusion. p.s. radar is optional.

Unfortunately, I can't find such multi-sensor data from apollo.  I notice other public data such as  nuScenes and Ford  include multi-sensor data, but I don't know how to convert such public data to fit apollo.

I would appreciate it if anybody can give me some suggestions.

**Comment by ntutangyun** [comment]
you could try out the simulators, like LGSVL simulator, to generate lidar and camera data for Apollo.

**Comment by ideasplus** [comment]
thanks for your reply. I know the LGSVL simulator and I don't actually used it yet, but I think it may not meet my needs bacause I want to use  controllable data as input like rosbag.

**Comment by daohu527** [comment]
What's the "nuScenes and Ford include multi-sensor data" dataset format?

 I know there is a tool to change **rosbag to apollo record**.

**Comment by zhanghming** [comment]
@daohu527 Do you know where is the `rosbag to apollo record` tool? I cann't find it.

**Comment by daohu527** [comment]
The tool is remove from 5.0, I found the 3.5 will work
https://github.com/ApolloAuto/apollo/tree/r3.5.0/modules/data/tools

**Comment by unacao** [comment]
https://github.com/ApolloAuto/apollo/releases/download/v2.5.0/demo_2.5.bag this rosbag may contain sensor data, but it is in ros format.
