### ISSUE TITLE
How can I know the control flow apollo 5.0

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#11070]
Hello everyone,

I want to see the control flow of apollo. I mean, I need to know which files are calling step by step and what is the relation between the files. Something like control flow. Is this possible?

OS Platform and Distribution: ubuntu 16.04
Apollo installed from source 
Apollo version: 5.0

**Comment by daohu527** [comment]
There are tools like **vscode** that can help you understand the calling relationship, but there are func levels instead of file levels.
As far as I know, there is no tool to tell you the file relationship

**Comment by Martin20** [comment]
Thank you @daohu527 

Does it work for Bazel?

**Comment by daohu527** [comment]
1. You can download [here](https://code.visualstudio.com/) there are both linux and windows versions.  
2. After install vscode you should install the "C/C++ for Visual Studio Code" extend in it. Then you can get the definition and refrence by "F12" "shit+F12"

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
