### ISSUE TITLE
Apollo 1.0 build error, about "rules_cc".

### ISSUE THREAD

**Issue by SamFisher940425** [ApolloAuto/apollo#11083]
IPC : Nuvo 6108GC
OS : Ubuntu 14.04.6 LTS （4.4.32-apollo-2-RT）
docker ： 18.06.3-ce
git clone from apollo， checkout v1.0.0，
as doc “quick start dev” say， “bash docker/scripts/dev_start.sh" then, "bash docker/scripts/dev_into.sh", git clone "apollo-platform" and checkout 1.0.0, build it.(passed)
then, cd APOLLO_HOME, and "bash apollo.sh build"
at this step, an error occurred.

some info as follows:

//:x86_64
//:arm64
WARNING: Running Bazel server needs to be killed, because the startup options are different.
ERROR: /home/adc/.cache/bazel/_bazel_adc/3e6945e88a09b92cd643f4d260dc4b07/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl:46:13: error loading package '@boringssl//boringssl-master-with-bazel': Encountered error while reading extension file 'cc/defs.bzl': no such package '@rules_cc//cc': error loading package 'external': The repository named 'rules_cc' could not be resolved and referenced by '//external:libssl'.
ERROR: Analysis of target '//modules/planning:lib_planning' failed; build aborted.

I have tried to debug it......but failed......beg for help

**Comment by Basti110** [comment]
Hey, i have the same problem. Could you solve it?

**Comment by storypku** [comment]
This seems to be caused by bazel version mismatch.  Apollo 1.0 used bazel 0.5.3, while boringssl used bazel 2.x or 3.x.

**Comment by Basti110** [comment]
Okay thanks :) But how can i solve this? And why only we have this problem?

**Comment by NoRomantic** [comment]
I have the same issue, don't know how to solve it. Does anyone have some ideas?

**Comment by storypku** [comment]
> Okay thanks :) But how can i solve this? And why only we have this problem?

I guess it will take a lot of pain to get it fixed, as bazel 0.5.3 is too-old as of Jun 2020, and only the `master` and `r5.5.0` branch are actively maintained at present. The Apollo team is working on  upgrading bazel support from  0.5.3 to  3.1+.  Please stay tuned.
