### ISSUE TITLE
Apollo collides with slow speed obstacle inside junction

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11104]
Hi team,

***VIDEO:***
Run 1: 
https://drive.google.com/file/d/1m-nBloJ5Z6cAIC4NsWb-USrk3QaDwVHq/view?usp=sharing

Run 2:
https://drive.google.com/file/d/1cEn-F_V_NVwyAbPRstrP1-mrOJmQILW-/view?usp=sharing

***Describe the bug***
I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. 

The Apollo vehicle is spawned on `lane_7` about 100 meters away from junction `j_10` with an initial speed about 5m/s and the routing destination is set at the begininng of `lane_47`. Thus Apollo is expected to pass through junction `J_10`.

The obstacle is spawned at the end of `lane_37`, and is set to follow the path: `lane_37` -> `J_10` -> `lane_10`, with an constant speed 0.5m/s.

Note that the obstacle perception and traffic light ground truth is fed directly to Apollo by LGSVL simulator. 

***To Reproduce***
1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Use LGSVL API to spawn Apollo at the starting point, with an initial speed.
3. Use LGSVL API to spawn the obstacle at the spawn point, set it to follow lanes, with constant speed.
4. Run the simulation. 
5. Set Apollo's routing destination.
6. Since Apollo has an initial speed, it will automatically take over and start the auto driving.

***Expected behavior***
Apollo is expected to give way to the slow obstacle in the junction, even though it's green light for Apollo.

But it seems that Apollo's prediction module did not predict any path for the obstacle, and the obstacle seems to be treated as an static obstacle which Apollo tries to rush in front of it and eventually led to collision.

***Desktop (please complete the following information):***

OS: Ubuntu 1804
Browser Chrome

**Comment by yifeijiang** [comment]
Similar to the issue at https://github.com/ApolloAuto/apollo/issues/11118, the prediction outputs for the slow obstacle was not accurate enough. Thanks.

**Comment by ntutangyun** [comment]
@yifeijiang I see. Thanks for your reply. Shall I leave the issue open for reference or close it for now?
