### ISSUE TITLE
Apollo stopped during overtake and following vehicle ahead on lane boundaries

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11109]
Hi team,

***VIDEO:***
https://drive.google.com/file/d/1YZqUUnhDFos-6Isla9tqY9Y2A9oPt4Ze/view?usp=sharing

***Describe the bug***
I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. 

The Apollo vehicle is spawned at the start of `lane_433` with an initial speed about 5m/s and the routing destination is set to the end of of `lane_433`. 

One obstacle is spawned roughly 50 meters ahead of Apollo's starting point, and is set to follow the lane at 0.5 m/s.

Note that the obstacle perception and traffic light ground truth is fed directly to Apollo by LGSVL simulator. 

***To Reproduce***
1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Use LGSVL API to spawn Apollo at the starting point, with an initial speed.
3. Use LGSVL API to spawn the obstacle at the spawn point, set it to follow lanes, with constant speed.
4. Run the simulation. 
5. Set Apollo's routing destination.
6. Since Apollo has an initial speed, it will automatically take over and start the auto driving.

***Expected behavior***
Apollo is expected to either follow slowly behind or perform an overtake. 
But as shown in the video, Apollo planned to overtake many times, and it stopped during overtaking action and started to follow the obstacle ahead slowly, but on top of the lane boundaries, instead of driving back to the lane center.

***Desktop (please complete the following information):***

OS: Ubuntu 1804
Browser Chrome

**Comment by yifeijiang** [comment]
The adv should be driving back to the lane center but slowly.   Please let us know the result if you could extend the simulation time. Thanks.

**Comment by ntutangyun** [comment]
@yifeijiang Hi, thanks for your reply. 

yes, if I run long enough, Apollo slowly drove back to the center, and then tried another overtake and successfully passed the obstacle. 

But I wonder what happened to the few initial overtaking plans.

**Comment by jmtao** [comment]
@ntutangyun The "overtake" you mentioned is called "side pass". We support "side-pass"(may cross lane boundary) static obstacles. For moving obstacles in our lane, we only "follow" or "stop".  You've seen the decisions switches between "side-pass" and "follow" probably because that slow vehicle's speed is at border line.

**Comment by ntutangyun** [comment]
@jmtao I see. Thanks for your reply. I think can close the issue for now.
