### ISSUE TITLE
perception：input of pointpillars

### ISSUE THREAD

**Issue by WSTao** [ApolloAuto/apollo#11116]
Hi, what is the coordinate system of pointpillars input point cloud in perception, what is the orientation of xyz, and the intensity range is [0,1] or [0,255], thank you very much!

**Comment by chasingw** [comment]
it seems not use intensity https://github.com/ApolloAuto/apollo/blob/51c73d32deda3f79807f482313a0d4461eee8679/modules/perception/lidar/lib/detection/lidar_point_pillars/point_pillars_detection.cc#L137-L151

**Comment by chasingw** [comment]
it seems not use intensity in `point_pillars_detection.cc`
https://github.com/ApolloAuto/apollo/blob/51c73d32deda3f79807f482313a0d4461eee8679/modules/perception/lidar/lib/detection/lidar_point_pillars/point_pillars_detection.cc#L137-L151
but in test code, it use intensity and norm to [0,1]
https://github.com/ApolloAuto/apollo/blob/51c73d32deda3f79807f482313a0d4461eee8679/modules/perception/lidar/lib/detection/lidar_point_pillars/point_pillars_test.cc#L222-L233
https://github.com/ApolloAuto/apollo/blob/51c73d32deda3f79807f482313a0d4461eee8679/modules/perception/lidar/lib/detection/lidar_point_pillars/point_pillars_test.cc#L222-L233

**Comment by jeroldchen** [comment]
@WSTao  It's a right-hand coordinate system setting lidar sensor as the origin. Positive x-axis points to the front of the car, positive y-axis to the left and positive z-axis to the top. Intensity range of the raw point cloud from lidar sensor is [0, 255], but in the preprocessing, the range is normalized to [0, 1].

**Comment by chasingw** [comment]
@jeroldchen hello, why in point_pillars_detection.cc, it seems not use intensity but use delta of timestamp which is 0 if kFuseFrames = false

**Comment by jeroldchen** [comment]
@chasingw Hi, we will update the models to include intensity in input very soon. Unit test will also be updated. Thank you for following.

**Comment by chasingw** [comment]
@jeroldchen thanks for yout quick reply

**Comment by jeroldchen** [comment]
Hi @WSTao , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
