### ISSUE TITLE
Apollo ignores slow lane changing obstacle in-front leading to collision

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11118]
Hi team,

***VIDEO:***
https://drive.google.com/file/d/1kR7ePjl4BFMPmjn4doEkxXquLGORirZ-/view?usp=sharing

***Describe the bug***
I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. 

The Apollo vehicle is spawned at the start of `lane_433` with an initial speed about 5m/s and the routing destination is set to the end of of `lane_433`. 

One obstacle is spawned roughly 75 meters ahead of Apollo's starting point, on the right neighbor lane, and the speed is set to a fixed 2 m/s. After simulation starts, the obstacle will start lane changing to left lane, which is Apollo's lane.

Note that the obstacle perception and traffic light ground truth is fed directly to Apollo by LGSVL simulator. 

***To Reproduce***
1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Use LGSVL API to spawn Apollo at the starting point, with an initial speed.
3. Use LGSVL API to spawn the obstacle at the spawn point, set it to follow lanes, with constant speed.
4. Run the simulation. 
5. Set Apollo's routing destination.
6. Since Apollo has an initial speed, it will automatically take over and start the auto driving.
7. One second after simulator starts, use LGSVL API to ask obstacle to change lane to left. 

***Expected behavior***
Apollo is expected to either bypassing the obstacle by dodging slightly to the leftside, or brake and wait for the obstacle to complete its lane change. But Apollo seems to ignore the obstacle until the obstacle blocked its planed path ahead. When it tried to brake, it was already too late. 

***Desktop (please complete the following information):***

OS: Ubuntu 1804
Browser Chrome

**Comment by Avps1** [comment]
Hi @ntutangyun ,
Can you please explain in a bit more detail how you use the LGSVL API to ask " ask obstacle to change lane to left." ?

**Comment by ntutangyun** [comment]
@Avps1 Hi, there is an API endpoint for this.
![image](https://user-images.githubusercontent.com/16061105/80226547-15077400-867f-11ea-8961-eadf9d902106.png)

here's some sample code:

```python
import os
import lgsvl

sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)
if sim.current_scene == "san_francisco":
  sim.reset()
else:
  sim.load("san_francisco")

spawns = sim.get_spawn()

egoState = lgsvl.AgentState()
egoState.transform = spawns[0]
a = sim.add_agent("Lincoln2017MKZ (Apollo 5.0)", lgsvl.AgentType.EGO, egoState)

forward = lgsvl.utils.transform_to_forward(egoState)
right = lgsvl.utils.transform_to_right(egoState)

npcState = lgsvl.AgentState()
npcState.transform.position = egoState.transform.position - 4 * right
npcState.transform.rotation = egoState.transform.rotation

npc1 = sim.add_agent("Sedan", lgsvl.AgentType.NPC, npcState)

npc1.follow_closest_lane(True, 1)

input("Press Enter to run")

sim.run(10)

npc1.change_lane(False)

sim.run(20)

```

**Comment by yifeijiang** [comment]
![image](https://user-images.githubusercontent.com/13139627/80238260-f7042a00-8612-11ea-83a8-8186b9b4ba8b.png)

Seems the predicted speed and path for front obstacle was wrong. Although the prediction outputs updated before the collision, but it was too late.

**Comment by ntutangyun** [comment]
@yifeijiang I see. Is it due to the lane gap between? if you see closely here, the prediction start point still seems to be inside obstacle's original lane, although part of its body is already within Apollo's lane
![image](https://user-images.githubusercontent.com/16061105/80269802-795d1e80-86e5-11ea-8b0c-ccf0ffe4da7e.png)

anyway, thank you for your reply. Shall I leave it open as a reference or close it for now?

**Comment by ntutangyun** [comment]
Found two similar cases to the current issue:

case 1:
https://drive.google.com/file/d/1CTIyrLgwoKpXlLyaCf8-Mvido224ipyd/view?usp=sharing

case2:
https://drive.google.com/file/d/1frjKl_nE0AcvA_YYKF17Q_YKCnFMuh6v/view?usp=sharing

**Comment by xiaozhe90** [comment]
> @Avps1 Hi, there is an API endpoint for this.
> ![image](https://user-images.githubusercontent.com/16061105/80226547-15077400-867f-11ea-8961-eadf9d902106.png)
> 
> here's some sample code:
> 
> ```python
> import os
> import lgsvl
> 
> sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)
> if sim.current_scene == "san_francisco":
>   sim.reset()
> else:
>   sim.load("san_francisco")
> 
> spawns = sim.get_spawn()
> 
> egoState = lgsvl.AgentState()
> egoState.transform = spawns[0]
> a = sim.add_agent("Lincoln2017MKZ (Apollo 5.0)", lgsvl.AgentType.EGO, egoState)
> 
> forward = lgsvl.utils.transform_to_forward(egoState)
> right = lgsvl.utils.transform_to_right(egoState)
> 
> npcState = lgsvl.AgentState()
> npcState.transform.position = egoState.transform.position - 4 * right
> npcState.transform.rotation = egoState.transform.rotation
> 
> npc1 = sim.add_agent("Sedan", lgsvl.AgentType.NPC, npcState)
> 
> npc1.follow_closest_lane(True, 1)
> 
> input("Press Enter to run")
> 
> sim.run(10)
> 
> npc1.change_lane(False)
> 
> sim.run(20)
> ```

Hi Tangyun,

Could you please explain how do you spawn the ego vehicle and the NPCs in a specific lane (in your case lane_433) like you did with lgsvl python API?

Many thanks

**Comment by xiaozhe90** [comment]
> @Avps1 Hi, there is an API endpoint for this.
> ![image](https://user-images.githubusercontent.com/16061105/80226547-15077400-867f-11ea-8961-eadf9d902106.png)
> 
> here's some sample code:
> 
> ```python
> import os
> import lgsvl
> 
> sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)
> if sim.current_scene == "san_francisco":
>   sim.reset()
> else:
>   sim.load("san_francisco")
> 
> spawns = sim.get_spawn()
> 
> egoState = lgsvl.AgentState()
> egoState.transform = spawns[0]
> a = sim.add_agent("Lincoln2017MKZ (Apollo 5.0)", lgsvl.AgentType.EGO, egoState)
> 
> forward = lgsvl.utils.transform_to_forward(egoState)
> right = lgsvl.utils.transform_to_right(egoState)
> 
> npcState = lgsvl.AgentState()
> npcState.transform.position = egoState.transform.position - 4 * right
> npcState.transform.rotation = egoState.transform.rotation
> 
> npc1 = sim.add_agent("Sedan", lgsvl.AgentType.NPC, npcState)
> 
> npc1.follow_closest_lane(True, 1)
> 
> input("Press Enter to run")
> 
> sim.run(10)
> 
> npc1.change_lane(False)
> 
> sim.run(20)
> ```

Hi @ntutangyun 

Could you please explain how do you spawn the ego vehicle and the NPCs in a specific lane (in your case lane_433) like you did with lgsvl python API?

Many thanks

**Comment by ntutangyun** [comment]
Hi, @xiaozhe90 

In Apollo HD map files, you have the waypoints for the lanes (e.g. `lane_433`). But the x, y, z are GPS values i.e. longitude, latitude, height.  Thus you need to use LGSVL python api function `map_to_gps` and `map_from_gps` to convert the GPS values to LGSVL 3d environment positions. 

Then you could use those positions to spawn your EGO vehicles or pdestrians. 

do check out this quick start: [21-map-coordinates.py](https://github.com/lgsvl/PythonAPI/blob/master/quickstart/21-map-coordinates.py)

**Comment by xiaozhe90** [comment]
Hi @ntutangyun ,

This is really helpful. Thanks a lot!
