### ISSUE TITLE
Performance of the NDT localization

### ISSUE THREAD

**Issue by MikeZhu92** [ApolloAuto/apollo#11129]
Has anyone tested the NDT localization in APOLLO ?
How's the performance compare with autoware?

I've tested it but the result was not very good. Maybe I did something wrong. Also I realize it still not an option to used directly in Apollo. Is it still under development ?

**Comment by daohu527** [comment]
> I've tested it but the result was not very good

What are the point cloud data and indicators you tested?   
As far as I know, "NDT" can be used in a production environment

**Comment by MikeZhu92** [comment]
> > I've tested it but the result was not very good
> 
> What are the point cloud data and indicators you tested?
> As far as I know, "NDT" can be used in a production environment

Yes, I have no issue with NDT algorithm. But the NDT in apollo is customized if you've checked the code.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
