### ISSUE TITLE
Apollo planning quick deviation leads to hitting the curb.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11135]
Hi team,

***VIDEO:***
https://drive.google.com/file/d/1HOtxKiAORrNwscCki74Sargea6GrLatT/view?usp=sharing

***Describe the bug***

I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. 

In the video, the Apollo vehicle is expected to drive from a starting lane to a destination lane, passing a junction in-between.

The vehicle is spawned near the first point of the starting lane, and the routing destination is set near the last point of the end lane.

There is no obstacle in this test case.
Note that the obstacle perception and traffic light ground truth is fed directly to Apollo.

***To Reproduce***

1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Manually Drive to the starting point shown in the video.
3. Set destination as shown in the video
4. Drive a bit forward in the simulator to let Apollo take over.

***Expected behavior***
Apollo is expected to follow its correctly routed path, however, a quick deviation within junction makes it deviate from the original path and eventually resulted in hitting the curb. 

This also happens in [issue](https://github.com/ApolloAuto/apollo/issues/10958) and [another issue](https://github.com/ApolloAuto/apollo/issues/10952). 
But the difference is that in the previous two issues, planning deviates towards another routed path/traffic lane, while in this new case, there is no routed path on the left. 

Desktop (please complete the following information):

OS: Ubuntu 1804
Browser Chrome

**Comment by jmtao** [comment]
@ntutangyun The routing is not long enough for ADV to complete lane changing before hitting junction.  We'll fix this in future releases. 
Thanks for supporting Apollo.

**Comment by ntutangyun** [comment]
@jmtao I see. In fact, sometimes the deviation does not happen and Apollo could actually make it by changing lane within the junction. although I believe this is still not proper to change lane within the junction.

Anyway, thanks for your reply. I think can close this issue for now.

**Comment by AlexandrZabolotny** [comment]
hello  
I have a similar problem. Help me decide.  
I noticed that the planning module builds a path that crosses the curb. I us Apollo pre6  

Below are two examples.  
1. We cross the curb when we turn right.  
![Screenshot from 2021-11-20 11-39-41](https://user-images.githubusercontent.com/61351599/142721248-24917c02-18db-4d35-a28e-ff4c17176c95.png)  

2. We cross the curb when we start from a position outside the map.   
![Screenshot from 2021-11-20 11-41-40](https://user-images.githubusercontent.com/61351599/142721253-11658ef9-4bbe-4881-9133-7d0cc61a9b12.png)
