### ISSUE TITLE
Apollo hits obstacle even though the prediction is correct.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11137]
Hi team,

***VIDEO:***
Follow view:
https://drive.google.com/file/d/19C592GGUsmhYl2NBtXxizf50uw2o274U/view?usp=sharing

Top view:
https://drive.google.com/file/d/1EZsvl5MyyBg7HLrElKgAxAWqLLWK0HRZ/view?usp=sharing

***Describe the bug***
I’ve been trying Apollo 5.0 (LGSVL forked version) out in the San Francisco Map with LGSVL simulator. 

The Apollo vehicle is expected to go straight in the junction, and one obstacle is spawned from the right side, turning left in the junction. 

Note that the obstacle perception and traffic light ground truth is fed directly to Apollo by the LGSVL simulator. 

***To Reproduce***
1. Set up LGSVL and Apollo 5.0 (forked version) according to LGSVL documentation.
2. Use LGSVL API to spawn Apollo at the starting point, with an initial speed.
3. Use LGSVL API to spawn the obstacle at the spawn point, set it to turn left in the junction, with constant speed.
4. Run the simulation. 
5. Set Apollo's routing destination.
6. Since Apollo has an initial speed, it will automatically take over and start the auto driving.

***Expected behavior***
to simulate uncommon situations, all the traffic lights are set to green all the time. 

From Apollo's point of view, it has the green light and goes straight in the junction, obviously, it has right of way with highest priority. However, the prediction module predicts the obstacle is in Apollo's way and Apollo is not braking, which resulted in a collision. 

This case is not the same as cases discussed in [issue](https://github.com/ApolloAuto/apollo/issues/11118), as in this new case, the prediction module actually provide the correct predicted path of obstacles, while in [issue](https://github.com/ApolloAuto/apollo/issues/11118), the predicted path of obstacles are incorrect.

***Desktop (please complete the following information):***

OS: Ubuntu 1804
Browser Chrome

**Comment by jmtao** [comment]
@ntutangyun looks like the moving vehicle is at low speed? Based on its speed, we've made Overtake(see the blue fence) decision. 
You can turn on PNC monitor view(Tasks menu on the left side bar, and then under "Others" column at lower side of the screen,  turn off "Lock Task Panel" and turn on "PNC Monitor")  to see how planning is making overtake/yield decision.  You want to look at ST-graph. 
Or you can post the screen recording of it, I can investigate more.

**Comment by ntutangyun** [comment]
@jmtao Hi Thanks for your reply. Here's the [recording of ST-graph](https://drive.google.com/file/d/1VxVCw9MxibtvvtL-o8JKFelu1taDJiwp/view?usp=sharing).

**Comment by jmtao** [comment]
@ntutangyun it's moving at speed of 2m/s, which is really slow. based on this speed and the speed of ADC, and ST-graph (you can see it on the right hand panel), planning module has made "Overtake" decision. Otherwise, ADC would have to STOP in order to "Yield" this car. 
There IS something wrong with this decision though.  We should have given correct buffer based on the size of this car.  So that on ST-graph, the obstacle shall appear wider along Y asis, and fail the speed solution to overtake it. 
we'll fix this in future release.  Thanks for supporting Apollo.

**Comment by ntutangyun** [comment]
@jmtao Thanks for your reply and confirm. :)
