### ISSUE TITLE
How to change the detection degree of LiDAR

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#11133]
I am looking for the right file and function where the LiDAR driver is written in Apollo 5.0. I want to reduce its 360 degrees detection to something less.

Is this possible?

I know in the JSON file we define it as "MeasurementsPerRotation" but where this file is read? I think by knowing that, I can alter the degree. Please let me know where JSON file is used.

Thanks.

- **OS Platform and Distribution ubuntu 16.04
- **Apollo installed from (source or binary)**: Apollo source 5.0
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

**Comment by daohu527** [comment]
I read the code and didn't find any configuration of lidar. Apollo only received lidar data via UDP.

I found that the lidar configuration can be set through the web UI provided by the lidar manufacturer. an example of hesai.
>4 Web Control
Web Control can be used to set Pandar64 parameters, check device info, and upgrade.
Before setting, please connect LiDAR and the computer using Ethernet cable. Set IP address to 192.168.1.25.

you can download the pdf [here](https://www.hesaitech.com/en/download)

**Comment by Martin20** [comment]
@daohu527 
Thank you for your reply. Actually, I am working on the LGSVL simulator. Therefore, I need the LiDAR component in the simulation and I asked about the simulation. Do you have a solution for such a simulation?

**Comment by daohu527** [comment]
The config is in 
Assets/Scripts/Sensors/LidarSensorBase.cs  

Lidar is done with a “Scriptable Rendering Pipeline”, you can dive into it(HDRP).

**Comment by Martin20** [comment]
@daohu527 
Where? in LGSVL or Apollo-5.0.

I looked at both I could not find.

**Comment by daohu527** [comment]
lgsvl source code

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
