### ISSUE TITLE
Error compiling Apollo system

### ISSUE THREAD

**Issue by oceanao** [ApolloAuto/apollo#11145]
I installed ubuntu on the virtual machine and successfully downloaded the Apollo source code and docker, but made an error in compiling the code:
#### INFO: (04-27 14:41:40.005) Elapsed time: 428.277s, Critical Path: 22.11s
============================
#### [INFO] Took 450 seconds

Instead of configuring cuda, I used build_cpu.
Who can help me out!!!

**Comment by changsh726** [comment]
Fixed by #11134 ，you can pull the latest apollo repo, thanks for your report.

> I installed ubuntu on the virtual machine and successfully downloaded the Apollo source code and docker, but made an error in compiling the code:
> 
> #### ERROR: (04-27 14:41:38.363) /apollo/modules/map/pnc_map/BUILD:6:1: error executing shell command: 'nvcc -arch=sm_30 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 ...' failed (Exit
> #### /usr/lib/x86_64-linux-gnu//libcuda.so: file not recognized: File truncated collect2: error: ld returned 1 exit status
> #### INFO: (04-27 14:41:40.005) Elapsed time: 428.277s, Critical Path: 22.11s
> ============================
> 
> #### [ERROR] Build failed!
> #### [INFO] Took 450 seconds
> Instead of configuring cuda, I used build_cpu.
> Who can help me out!!!

Fixed by #11134 ,you can pull the latest apollo repo, thanks for your report.
