### ISSUE TITLE
cyber_recorder：未找到命令

### ISSUE THREAD

**Issue by swj735245824** [ApolloAuto/apollo#11146]
下载了这个模拟数据，执行
cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
报了这个问题
cyber_recorder：未找到命令

根据介绍里面操作的：https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_launch_Apollo.md

不知道这是哪一步出的问题呢
大神求解呀

**Comment by daohu527** [comment]
follow this steps:
1. check the cyber_recorder in "/apollo/bazel-bin/cyber/tools/cyber_recorder"
2. run "source cyber/setup.bash"

then run the cyber_recorder cmd

**Comment by Baigt** [comment]
> 下载了这个模拟数据，执行
> cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
> 报了这个问题
> cyber_recorder：未找到命令
> 
> 根据介绍里面操作的：https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_launch_Apollo.md
> 
> 不知道这是哪一步出的问题呢
> 大神求解呀

我现在连数据包都下载不了
你的数据包还能重新下载吗？

**Comment by Baigt** [comment]
你执行命令cyber_recorder play -l -f demo_3.5.record试试

**Comment by Baigt** [comment]
我现在连数据包都下载不了
你的数据包还能重新下载吗？
