### ISSUE TITLE
F0429 08:28:25.662976  2030 lidar_obstacle_segmentation.cc:35] Check failed: config_manager->GetModelConfig(class_name, &model_config)

### ISSUE THREAD

**Issue by laukalfp** [ApolloAuto/apollo#11157]
Hi ,when i tried to run the /module/perception/lidar/app/lidar_app_lidar_pipline_test.cc
I got a error!
![Screenshot from 2020-04-29 08-39-35](https://user-images.githubusercontent.com/34259671/80551135-090c1100-89f5-11ea-8246-0e20b0547788.png)

1.I add the head file 
#include "modules/perception/lib/config_manager/config_manager.h"
2. init function
if (!lib::ConfigManager::Instance()->Init()) {
    AERROR << "Failed to init ConfigManage.";
  }
3.the deps file
deps[
"//modules/perception/lib/config_manager",
...
]
but it still doesn't work, if someone know that hope some can help me , Thank you !

**Comment by laukalfp** [comment]
I solved it by change below:
FLAGS_work_root = "/apollo/modules/perception/production";
![Screenshot from 2020-04-29 11-01-25](https://user-images.githubusercontent.com/34259671/80557249-df5ce500-8a08-11ea-8350-4f1d31b5cf57.png)

**Comment by ypbbbbb** [comment]
hi! i meet the same problem. Can you tell me whether i have to add the head file, init function and modify the deps file ? Or i just directly add the FLAGS_work_root = "/apollo/modules/perception/production" ?
I will really appreciate it If you can list  the steps i need to solve the problem.

**Comment by laukalfp** [comment]
> hi! i meet the same problem. Can you tell me whether i have to add the head file, init function and modify the deps file ? Or i just directly add the FLAGS_work_root = "/apollo/modules/perception/production" ?
> I will really appreciate it If you can list the steps i need to solve the problem.

The problem is they can't find the data in a wrong place  ~

1.I add the head file
#include "modules/perception/lib/config_manager/config_manager.h"
2. init function
if (!lib::ConfigManager::Instance()->Init()) {
AERROR << "Failed to init ConfigManage.";
}
3.the deps file
deps[
"//modules/perception/lib/config_manager",
...
]
4.FLAGS_work_root = "/apollo/modules/perception/production";

you can try it ,  i solve it longtime ago, i can't remember the detail~

**Comment by daohu527** [comment]
seems sloved!
