### ISSUE TITLE
Is the .model suffix the same as the .caffermodel suffix

### ISSUE THREAD

**Issue by benlvzi** [ApolloAuto/apollo#11151]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (5.5)**:

### Steps to reproduce the issue:
- **Is the deploy.model suffix the same as the deploy.caffermodel suffix, Do you have a tool for converting xxx.caffemodel to xxx.model ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
