### ISSUE TITLE
Can we build apollo using higher Bazel version?

### ISSUE THREAD

**Issue by bronzeMe** [ApolloAuto/apollo#11161]
**Is your feature request related to a problem? Please describe.**
Presently, we  use Bazel 0.5.3 to build apollo, but in my experiment project, I want to integrate other libraries buit by Bazel 0.22 (or higher ) into Apollo. I failed to build apollo using bazel 0.22.
So,  will apollo suport higher Bazel in the future?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by storypku** [comment]
Yes. We are making effort to upgrade bazel to 3.1.0 now. Please stay tuned.
Thanks for your attention.
