### ISSUE TITLE
How can I get data outside operation_name object

### ISSUE THREAD

**Issue by dwthien** [ApolloAuto/apollo#11177]
Hi, can you help me?
I used Apollo Client to query, but I only get data inside operation_name:
![image](https://user-images.githubusercontent.com/25741737/80920841-9c01ce00-8d9c-11ea-96cd-b500c85657e4.png)

Then I used Apollo extension dev tool of chrome and saw data outside. How can I get data outside the operation_name, I wanna get more variable at the image?
![image](https://user-images.githubusercontent.com/25741737/80920905-01ee5580-8d9d-11ea-961b-a8cbd60e44b3.png)

I tried to upgrade Apollo to v3 to get data outside the operation_name, after I tested with Apollo v2.6.
![image](https://user-images.githubusercontent.com/25741737/80920970-73c69f00-8d9d-11ea-820a-878945d924c6.png)

Did I miss something?

**Comment by unacao** [comment]
I think you are referring to another Apollo project https://github.com/apollographql/apollo-client
