### ISSUE TITLE
can not find "cmp_out_shape_floor_as_conv" in apollo caffe branch

### ISSUE THREAD

**Issue by ghy200692162** [ApolloAuto/apollo#11175]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
ubuntu 18.04
- **Apollo installed from (source or binary)**:
from source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
5.5
cuda_version:10.1
### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I search in caffe.proto in applo caffe branch
https://github.com/ApolloAuto/caffe/tree/apollo
But can not find variable named "cmp_out_shape_floor_as_conv"
But it was used in traffic light detection module.
### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2020-05-01 23-46-01](https://user-images.githubusercontent.com/1029390/80818847-76db5700-8c06-11ea-8bb1-cdedd8342e62.png)

**Comment by AMDxb548** [comment]
@ghy200692162 : Hi I am facing the same issue with traffic light recognition. Can you help me in resolving this issue ?

**Comment by Findurname** [comment]
Hi, Sorry to bother. Do you still have the https://github.com/ApolloAuto/caffe source code?
