### ISSUE TITLE
HD Map Creator

### ISSUE THREAD

**Issue by enesemre** [ApolloAuto/apollo#11181]
I want to create apollo open drive from open drive (.xodr file) . How can I do that with this package ? Any suggestion?

**Comment by daohu527** [comment]
As I know, there is a xml opendrive reader in "apollo/modules/map/hdmap/adapter/xml_parser". You can transform ".xodr" to ".xml" then use the .xml file in apollo.

**Comment by enesemre** [comment]
Yes I know but I really didnt understand how apollo convert open drive to apollo open drive. Any clear document about it?

**Comment by daohu527** [comment]
It would be better to read the code. I did not find the relevant doc.

**Comment by daohu527** [comment]
## 1. Open drive to Apollo hd map
I found a way to change open drive(.xodr) to apollo hdmap, which need a little modfiy the code.  

https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/modules/map/tools/sim_map_generator.cc#L106-L126

## 2. How to 
1. put the .xodr file into dir "/apollo/modules/map/data/demo/" 
2. rename the .xodr file to "base_map.xml" (the .xodr file is just a xml file but with different file name suffix)
3. modify the sim_map_generator.cc and remove
https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/modules/map/tools/sim_map_generator.cc#L121
4. run "./apollo.sh build " to build apollo
5. run "./bazel-bin/modules/map/tools/sim_map_generator"
6. the generate hd map file is "/tmp/sim_map.bin" and "/tmp/sim_map.txt"

**Comment by enesemre** [comment]
Thanks for your answer . I need to build apollo in docker looks like . Which release of apollo do you use for this process?

**Comment by daohu527** [comment]
The 5.5 is ok, other version will ok if have sim_map_generator

**Comment by whuxhzhang** [comment]
Is there any way to convert Apollo .xml files to .xodr format ？

**Comment by JackRen88** [comment]
Hello,everyone!
where can i get apollo opendrive sample data?

**Comment by wangzhensuo** [comment]
> 
> ## 1. Open drive to Apollo hd map
> 
> I found a way to change open drive(.xodr) to apollo hdmap, which need a little modfiy the code.
> 
> https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/modules/map/tools/sim_map_generator.cc#L106-L126
> 
> ## 2. How to
> 
>     1. put the .xodr file into dir "/apollo/modules/map/data/demo/"
> 
>     2. rename the .xodr file to "base_map.xml" (the .xodr file is just a xml file but with different file name suffix)
> 
>     3. modify the sim_map_generator.cc and remove
>        https://github.com/ApolloAuto/apollo/blob/01062c85b5c731963eff8dfdf220025f49c25c13/modules/map/tools/sim_map_generator.cc#L121
> 
>     4. run "./apollo.sh build " to build apollo
> 
>     5. run "./bazel-bin/modules/map/tools/sim_map_generator"
> 
>     6. the generate hd map file is "/tmp/sim_map.bin" and "/tmp/sim_map.txt"

base on above, how to generate "routing_map.bin" and "routing_map.txt",please?
I found below cmd that could genereate "routing_map.bin" and "routing_map.txt",but it is based on "base_map.txt".
i only have "base_map.xml(.xodr file rename)".
`./bazel-bin/modules/map/tools/sim_map_generator --map_dir ./modules/map/data/demo/`

**Comment by daohu527** [comment]
You cannot directly use a opendrive map format in apollo. The Apollo opendrive format is a bit different than normal, you can find some help in https://github.com/ApolloAuto/apollo/issues/3005

**Comment by wangzhensuo** [comment]
@daohu527 thank you for point me a correct direction.  thank you !

**Comment by daohu527** [comment]
You're welcome, I have always wanted to write a conversion tool, but time is limited, maybe you can write and publish it

**Comment by wangzhensuo** [comment]
@daohu527   I would like to write this tool,but I don't have "apollo opendrive specification" which may be useful for comparing the difference between normal opendrive file and apollo's opendrive file. I have left email on apollo's github [3005](https://github.com/ApolloAuto/apollo/issues/3005)  ,but haven't got it.  if you have it,could you send it to 814565668@qq.com,please? thank you !

**Comment by daohu527** [comment]
I also don't have the spec, I think you can just see the protobuf in `modules\map\proto`. I wrote some introduction about it [link](https://github.com/daohu527/Dig-into-Apollo/tree/master/modules/map)

**Comment by wangzhensuo** [comment]
@daohu527  I compared normal opendrive and apollo's opendrive. It is quite diffenent. The tags is not one-to-one relationship. I 've also seen your note(Dig into Apollo - Map),that's really great help. but I still have no idea about how to convert(even manually).Do you find any rule about it ? 
the below is code about generating base_map.txt ,if we could extract data from tags in normal opendrive,and call this function. maybe we could generate base_map.txt .  is it right(my idea) ? 
[gen base_map.txt](https://github.com/MaxLyubimov/MapCreator/blob/master/create_map.py)

**Comment by shandaolu** [comment]
@daohu527  Hello, thank you for your detailed answer. When I recitify my code, I meet some questions.
1. Which the version of apollo do you use? I currently use apollo 2.5. 
2. How to cite asbl header files？ 
3. Whether any xodr file can be converted to sim_map?

Your answers are very important for me. Thankyou for your help.

**Comment by daohu527** [comment]
> Which the version of apollo do you use? I currently use apollo 2.5.

apollo 5.0

> Whether any xodr file can be converted to sim_map?

I made some mistakes before. **sim_map is not a hd map**, but it is used by dreamview. The tool from xodr to hdmap needs to be adapted, because apollo's own xml_parse is apollo custom format

**Comment by shandaolu** [comment]
Yes, the base_map is hd map. When I use sim_map_generator and proto_map_generator in the tools， I meet the error. The base.xml is the file that I copy from the VTD.

`E0415 18:24:53.355163 12055 opendrive_adapter.cc:52] []fail to parse opendrive road, Error parse lane uid
F0415 18:24:53.356544 12055 sim_map_generator.cc:117] Check failed: OpendriveAdapter::LoadData(map_file, &map_pb) []
`
I also look the issue about converting Fromat. But I have no idear doing this.

**Comment by daohu527** [comment]
There is currently no good solution to this problem but do some adapt in "modules\map\hdmap\adapter\xml_parser"

**Comment by InterKnight** [comment]
Hi，@wangzhensuo
Do you have "apollo opendrive specification", could you please send it to 785202311@qq.com? thank you !

**Comment by ntutangyun** [comment]
> Hi，@wangzhensuo
> 
> Do you have "apollo opendrive specification", could you please send it to 785202311@qq.com? thank you !

the specification might be obsolete sometimes. please check the modules/map/proto for latest definition.

**Comment by InterKnight** [comment]
Hi，@ntutangyun 
Thank you for your prompt, but I still don't know how to using these .proto files. 
My final goal is creating my own HDmap which can be used in Apollo. But what I have now is standard OpenDrive HDmap, so do you konw how to change standard OpenDrive HDmap to base_map.xml or base_map.txt or base_map.bin?

**Comment by wangzhensuo** [comment]
> 
> 
> Hi，@wangzhensuo
> Do you have "apollo opendrive specification", could you please send it to [785202311@qq.com](mailto:785202311@qq.com)? thank you !

I also have not got the   "apollo opendrive specification" since several mouth passed. I joined the apollo automotie topic wechat group,and ask for the SPEC, but no one replay.  If you got it,   please share here.  thank you.

**Comment by guyanf** [comment]
> 

You can ref this one, convert osm to apollo opendrive.
https://github.com/CWGran/osm2opendrive

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
