### ISSUE TITLE
Help wanted : Is kalman filter used in "Camera Object Tracking" ?

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#11184]
Hi,
I was trying to make sense of the "Camera Object Tracking" module under the Perception module.
Kindly look at the snapshot attached : 
![Camera_Obj_Tracking](https://user-images.githubusercontent.com/50120641/81064650-5519f280-8eda-11ea-9e31-64ace89c895d.png)

Could you kindly tell me if Apollo uses Kalman filters for Camera Object tracking ? I know EKF and AKF are used for Lidar and Radar Object tracking, but cant figure out the mechanism behind Camera Object tracking.
Your help is highly appreciated.

**Comment by daohu527** [comment]
Camera use an "OMTObstacleTracker",  I'm not sure if it's "optimal mass transport"?

**Comment by Avps1** [comment]
> Camera use an "OMTObstacleTracker", I'm not sure if it's "optimal mass transport"?

Thanks for your response.
