### ISSUE TITLE
Broken Bazel cache symlinks in the current master branch Docker container

### ISSUE THREAD

**Issue by Kirkirillka** [ApolloAuto/apollo#11198]
**Description**
For the docker container image used in the master branch release, after executing `dev_into.sh`, a user logins in as "apollo" user instead of $USER variable defined at the container building stage `dev_start.sh`. This leads to Bazel cache broken symlinks, therefore after a container builds Apollo, once the container is destroyed Bazel cache is lost and the Apollo modules have to be rebuild.

**To Reproduce**
1. `git checkout master`
2. Start container environment `bash docker/scripts/dev_start.sh`, enter the environment `bash docker/scripts/dev_into.sh` and build modules
3. Let's suppose your are running your host as "user", `$USER` is defined to "user". In the container environment `whoami` will show "apollo"
4. Your symlinks in `/apollo` directory inside the dev container will be broken, because they will map to `\home\user\.cache`, and you  are under `\home\apollo`. Permission evaluation and then logging in as *user* is impossible, because it says there is no entry in `/etc/passwd`.

**Expected behavior**
Bazel cache is saved in local $HOME/.cache directory

![Screenshot at 2020-05-07 11-49-31](https://user-images.githubusercontent.com/16869366/81274404-e7480500-9058-11ea-82be-932969c36b0b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, Docker 19.03
 - Browser: Chrome
 - Version: 81

**Comment by storypku** [comment]
Thank you for reporting this. We will re-evaluate the changes we made recently on user account issues.

**Comment by storypku** [comment]
This was caused as we didn't mount $HOME directory on the host into  container. It has nothing to do with different user account  inside/outside container(`user` outside and `apollo` inside for this case).

**Comment by storypku** [comment]
See https://github.com/ApolloAuto/apollo/pull/11215
