### ISSUE TITLE
VMware build Apollo 5.5 error

### ISSUE THREAD

**Issue by Alphabaijinde** [ApolloAuto/apollo#11199]
![image](https://user-images.githubusercontent.com/22705823/81276899-38222280-9086-11ea-9d4c-b24e9a11597b.png)

**Comment by Alphabaijinde** [comment]
@weidezhang

**Comment by storypku** [comment]
Will you please run the following bazel command directly, and paste its output?

` bazel build //cyber/transport:transport_test`

**Comment by storypku** [comment]
And, maybe you should look at https://github.com/ApolloAuto/apollo/issues/7719
