### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by mkhayatian** [ApolloAuto/apollo#11203]
Is there a list for the supported GPUs? For instance, are RTX2080 and RTX5000 supported?

**Comment by storypku** [comment]
> Is there a list for the supported GPUs? For instance, are RTX2080 and RTX5000 supported?

Thank you for pointing it out. Supported GPU list is a missing chain that  Apollo should have.

**Comment by mkhayatian** [comment]
Thank you.

**Comment by storypku** [comment]
> Thank you.

We will support GPU cards with compute capabilities `5.0/5.2, 6.0/6.1, 7.0, 7.5` in the upcoming Apollo 6.0 release, which corresponds to the following nvidia gpu archs:  `Maxwell, Pascal, Volta, and Turing`.
