### ISSUE TITLE
lon_controller: remaining path length get updated twice for one case.

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#11202]
**Describe the bug**

The function GetPathRemain() computes the length of the remaining path so the standstill braking can be applied when the ego-vehicle is reaching the final destination. In one case, the remaining path in SimpleLongitudinalDebug is updated twice and here is the code snippet:

```
  if (stop_index == trajectory_message_->trajectory_point_size()) {
    --stop_index;
    if (fabs(trajectory_message_->trajectory_point(stop_index).v()) <
        kParkingSpeed) {
      ADEBUG << "the last point is selected as parking point";
    } else {
      ADEBUG << "the last point found in path and speed > speed_deadzone";
      debug->set_path_remain(10000);
    }
  }
  debug->set_path_remain(
      trajectory_message_->trajectory_point(stop_index).path_point().s() -
      debug->current_station());
```
The function should be returned right after _debug->set_path_remain(10000)_.  If it was done on purpose, there is no need to call _debug->set_path_remain(10000)_ so the path remaining always refers to the current planned path.

**Comment by kevin-y-wang** [comment]
Thanks for pointing out this issue. 
This conflict of logic will be fixed soon.

**Comment by kevin-y-wang** [comment]
Hi @jilinzhou , thanks for your contribution to improve the Apollo codes. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
