### ISSUE TITLE
where to get a .record data with online point cloud

### ISSUE THREAD

**Issue by 171930433** [ApolloAuto/apollo#11205]
like the menu, I tried demo_1.5.bag demo_2.5.bag demo3.5.record, none of them with online point cloud data
where to get the record data with online point cloud data?
http://apolloscape.auto/self_localization.html#to_dataset_href
doesn't have either

**Comment by zhanghming** [comment]
I aslo want to know how to prepare or get the offline test data for Apollo project and how to visualize the sensor input and algorithm output. In this case, we can run the whole Apollo project in our own computer to test different modules conveniently.
However, I can't find the exhaustive documents to elaborate the test data problem, and there are so many issues about this problem.
Wish the Apollo team can consider this problem, thanks in advance.

**Comment by JackFu123** [comment]
Hi, I don't think we have public data with online point clouds now. What's it used for without a point-cloud map?

**Comment by panfengsu** [comment]
Every moduel for example point cloud segmentation or detection has unit test file.You can use pcd file to test point cloud moduel,but whole record date with all channels need to being recorded by cyber with sensors.

**Comment by panfengsu** [comment]
Hope the information answered your question. If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open a new issue if you have any more questions. 
Thank you for supporting Apollo!
