### ISSUE TITLE
build failed Apollo 5.5. Exit 4

### ISSUE THREAD

**Issue by Alphabaijinde** [ApolloAuto/apollo#11201]
![image](https://user-images.githubusercontent.com/22705823/81305972-87ca1380-90b1-11ea-9177-70ced29082c5.png)

**Comment by Alphabaijinde** [comment]
@natashadsouza

**Comment by storypku** [comment]
It seems that gcc compiler was killed as a result of insufficient memory inside the docker container.

**Comment by Alphabaijinde** [comment]
> It seems that gcc compiler was killed as a result of insufficient memory inside the docker container.

my ubuntu memory  had set 16G

**Comment by storypku** [comment]
> > It seems that gcc compiler was killed as a result of insufficient memory inside the docker container.
> 
> my ubuntu memory had set 16G
I see. As far as I know, `gcc: internal error` usually means it can't find sufficient memory to get its work done.
Have you tried  running "bazel build //modules/localization/ndt:ndt_localization_component_lib" directly?

**Comment by Alphabaijinde** [comment]
I am  so sorry now!  The error of build Apollo what is from my personal laptop!

**Comment by Alphabaijinde** [comment]
> > > It seems that gcc compiler was killed as a result of insufficient memory inside the docker container.
> > 
> > 
> > my ubuntu memory had set 16G
> 
> I see. As far as I know, `gcc: internal error` usually means it can't find sufficient memory to get its work done.
> Have you tried running "bazel build //modules/localization/ndt:ndt_localization_component_lib" directly?

I tried runing above directly.
i am glad to say I had slove the issue!  Thank you very much the above you provided the direction !
