### ISSUE TITLE
When Apollo reaches the Stop Sign controlled junction, sometimes it never starts again after it stops before the white stop line.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11214]
Hi team,

I noticed that 

When Apollo reaches the Stop Sign controlled junction, sometimes it never starts again after it stops before the white stop line.

Has anyone experienced similar issues?

Thanks.

**Comment by ntutangyun** [comment]
Sorry for the late update. 
here's a [video](https://drive.google.com/file/d/1G1mFrLwghBwYrkMlIs98FaWaoKBJ3353/view?usp=sharing).

**Comment by jmtao** [comment]
@ntutangyun can you please turn on PNC monitor? (Tasks tab on left panel -> Turn off "Lock Task Panel" and turn on "PNC Monitor" on Others group at lower side of the screen), and record it again.   not guaranteed to provide enough info though. We'll see.

**Comment by ntutangyun** [comment]
Hi, @jmtao thanks for your reply. here's the [video ](https://drive.google.com/file/d/1EoijTPWJU3Dh_i82t4ORNzwl1tMvoTuL/view?usp=sharing)for the PNC monitor.

I noticed that if the **scenario library** rolls normally, the vehicle is able to engage again after a complete stop when the "CREEP" shows up. 

But somehow after a few trails, the **scenario library** freezes and does not display any more new data. Those in the video are old ones. When this happens, the vehicle will stop forever before entering the junction.

**Comment by jmtao** [comment]
@ntutangyun I don't even see scenario / stage changes in this video. hard to tell what's going on.

**Comment by ntutangyun** [comment]
@jmtao, when the **scenario library** on the top right side keeps rolling, Apollo could engage again after a complete stop and pass the junction. but sometimes when the **scenario library**  stops rolling, and the vehicle will stop forever at the junction.

**Comment by jmtao** [comment]
@ntutangyun again, it's hard to tell what's going on. If you are interested in knowing how to debug in your enviroment, ping me. thanks!

**Comment by ntutangyun** [comment]
@jmtao thanks. closing for now. If you have docs about debugging, could you please send it to ntutangyun@gmail.com. thanks again :)

**Comment by xiaozhe90** [comment]
> @ntutangyun again, it's hard to tell what's going on. If you are interested in knowing how to debug in your enviroment, ping me. thanks!

Hi, could you also please send me the docs about debugging to jxjinxiaozhe@163.com ? many thanks!

**Comment by xiaozhe90** [comment]
> @ntutangyun again, it's hard to tell what's going on. If you are interested in knowing how to debug in your enviroment, ping me. thanks!

@jmtao Hi, could you also send me a copy of the docs about debugging to jxjinxiaozhe@163.com please? many thanks!

**Comment by ntutangyun** [comment]
@xiaozhe90 yeah I haven't received the debugging instructions yet :joy:

**Comment by xiaozhe90** [comment]
> @xiaozhe90 yeah I haven't received the debugging instructions yet

Really? Haha, Thanks for your reply.

**Comment by nhatuan84** [comment]
hi @ntutangyun 

How can you make the simulation like that? I do not see any document about that.

Thanks

**Comment by ntutangyun** [comment]
> hi @ntutangyun 
> 
> How can you make the simulation like that? I do not see any document about that.
> 
> Thanks

You wanna try out the LGSVL simulator.
