### ISSUE TITLE
Can't use command " bash dev_into.sh" to enter into the docker environment.

### ISSUE THREAD

**Issue by NoRomantic** [ApolloAuto/apollo#11225]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 1.0

### Steps to reproduce the issue:
Ater installed docker, I run this command `bash docker/scripts/dev_start.sh`, got

>---@---:~/apollo$ bash docker/scripts/dev_start.sh
 /home/---/apollo/scripts/apollo_base.sh: line 105: /home/---/apollo/third_party/ros/setup.bash: No such file or directory
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:48900->[::1]:53: read: connection refused
apollo_dev
apollo_dev
[sudo] password for ---: 
/home/---/apollo/data/core/core_%e.%p
[WARNING] Failed to find device with pattern "ttyUSB*" ...
[ OK ] Found device: /dev/ttyS4.
[ OK ] Found device: /dev/ttyS31.
[ OK ] Found device: /dev/ttyS30.
[ OK ] Found device: /dev/ttyS29.
[ OK ] Found device: /dev/ttyS28.
[ OK ] Found device: /dev/ttyS27.
[ OK ] Found device: /dev/ttyS26.
[ OK ] Found device: /dev/ttyS25.
[ OK ] Found device: /dev/ttyS24.
[ OK ] Found device: /dev/ttyS23.
[ OK ] Found device: /dev/ttyS22.
[ OK ] Found device: /dev/ttyS21.
[ OK ] Found device: /dev/ttyS20.
[ OK ] Found device: /dev/ttyS19.
[ OK ] Found device: /dev/ttyS18.
[ OK ] Found device: /dev/ttyS17.
[ OK ] Found device: /dev/ttyS16.
[ OK ] Found device: /dev/ttyS15.
[ OK ] Found device: /dev/ttyS14.
[ OK ] Found device: /dev/ttyS13.
[ OK ] Found device: /dev/ttyS12.
[ OK ] Found device: /dev/ttyS11.
[ OK ] Found device: /dev/ttyS10.
[ OK ] Found device: /dev/ttyS9.
[ OK ] Found device: /dev/ttyS8.
[ OK ] Found device: /dev/ttyS7.
[ OK ] Found device: /dev/ttyS6.
[ OK ] Found device: /dev/ttyS5.
[ OK ] Found device: /dev/ttyS3.
[ OK ] Found device: /dev/ttyS2.
[ OK ] Found device: /dev/ttyS1.
[ OK ] Found device: /dev/ttyS0.
[ OK ] Found device: /dev/can0.
[WARNING] Failed to find device with pattern "ram*" ...
[ OK ] Found device: /dev/loop7.
[ OK ] Found device: /dev/loop6.
[ OK ] Found device: /dev/loop5.
[ OK ] Found device: /dev/loop4.
[ OK ] Found device: /dev/loop3.
[ OK ] Found device: /dev/loop2.
[ OK ] Found device: /dev/loop1.
[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop-control.
5c71995df7a23a1318ab2c777029b22dd5c0f412b2a07cdb080be30c2829d166
adduser: Only one or two names allowed.
usermod: user '' does not exist

Then I run `bash docker/scripts/dev_into.sh`, got 

> unable to find user -it: no matching entries in passwd file

I could enter docker environment yesterday, but when I build apollo using command `bash apollo.sh build`, I got some error information so I clean the build process using commad `bash apollo.sh clean`. But after that I just can't enter the docker environment. What may be the problem?

**Comment by NoRomantic** [comment]
It seems to be a bug of docker that when I stop the docker environment manually. Finally, I use command `sudo gedit /etc/passwd` to modify the use_name(which is incorrect, but I have no idea why), problem solved.

**Comment by fjc378209410** [comment]
Hello, how did you solve it, I have encountered the same problem now, but my "/etc/passwd" does not show anything about docker
