### ISSUE TITLE
apollo5.5 build failed, Timeout connecting to https://boringssl.googlesource.com

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#11237]
**Describe the bug**
apollo5.5 build failed.
```bash
Timeout connecting to https://boringssl.googlesource.com/boringssl/+archive/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz
```
docker image:apolloauto/apollo:dev-18.04-x86_64-latest           LAST PUSHED 18 days ago
DIGEST:sha256:bec5a5cec3c7411dac078e2b466a0283297c1daee7bd2bdc78b1cd6beffbf216

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 16.04

**Additional context**
If I use a apollo5.0-dev docker pulled 3 months ago to build apollo-5.5 source code, this error disappreared(it have another error.)

**Comment by BigBenSure** [comment]
1. I want to know which 3rd-party lib need boringssl.
2. I can download it manualy, How to use it locally? Which dir should it copied in? Do I need to change WORKSPACE.in?

**Comment by BigBenSure** [comment]
apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
```bash
if "boringssl" not in native.existing_rules():
        native.http_archive(
            name = "boringssl",
            # on the chromium-stable-with-bazel branch
            url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
        )
```
Can I install boringssl manualy? How to install boringssl so that bazel can find it?

**Comment by storypku** [comment]
> **Describe the bug**
> apollo5.5 build failed.
> 
> ```shell
> Timeout connecting to https://boringssl.googlesource.com/boringssl/+archive/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz
> ```
> 
> docker image:apolloauto/apollo:dev-18.04-x86_64-latest LAST PUSHED 18 days ago
> DIGEST:sha256:bec5a5cec3c7411dac078e2b466a0283297c1daee7bd2bdc78b1cd6beffbf216
> 
> **Desktop (please complete the following information):**
> 
> * OS: ubuntu
> * Version 16.04
> 
> **Additional context**
> If I use a apollo5.0-dev docker pulled 3 months ago to build apollo-5.5 source code, this error disappreared(it have another error.)



> apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
> 
> ```shell
> if "boringssl" not in native.existing_rules():
>         native.http_archive(
>             name = "boringssl",
>             # on the chromium-stable-with-bazel branch
>             url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
>         )
> ```
> 
> notised that in old apollo dev docker image, boringssl is stored in /home/tmp.
> Maybe it is more friendly to Chinese user...





> apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
> 
> ```shell
> if "boringssl" not in native.existing_rules():
>         native.http_archive(
>             name = "boringssl",
>             # on the chromium-stable-with-bazel branch
>             url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
>         )
> ```
> 
> notised that in old apollo dev docker image, boringssl is stored in /home/tmp.
> Maybe it is more friendly to Chinese user...

Thank you for reporting this. We will investigate the case in the next few days.

**Comment by storypku** [comment]
> apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
> 
> ```shell
> if "boringssl" not in native.existing_rules():
>         native.http_archive(
>             name = "boringssl",
>             # on the chromium-stable-with-bazel branch
>             url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
>         )
> ```
> 
> notised that in old apollo dev docker image, boringssl is stored in /home/tmp.
> Maybe it is more friendly to Chinese user...

Thank you for reporting this. We will investigate it in the next few days. Please stay tuned.

**Comment by storypku** [comment]
> 1. I want to know which 3rd-party lib need boringssl.
> 2. I can download it manualy, How to use it locally? Which dir should it copied in? Do I need to change WORKSPACE.in?

1. As you have found, grpc have a dependency over `boringssl`.
from your comment https://github.com/ApolloAuto/apollo/issues/11237#issuecomment-627789445,
we can see that the `bazel/grpc_deps.bzl` script in `grpc` checks whether `boringssl` was already specified in your workspace. If found, it will do nothing. Therefore we can
add an entry in `WORKSPACE.in` with a fixed `sha256` value like the following:

```
http_archive(
    name = "boringssl",
    sha256 = "fb236ae74676dba515e1230aef4cc69ab265af72fc08784a6755a319dd013ca6",
    url = "file:///home/tmp/boringssl-83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz",
)
```

In your case, you should substitute  the `sha256` value with that of your downloaded `boringssl` tarball, which can be obtained by running:
```
sha256sum /home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz | awk '{print $1}'
```

Change the `url` to `file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz` accordingly.

And then you can run `./apollo.sh ....` as usual.

**Comment by storypku** [comment]
> > 1. I want to know which 3rd-party lib need boringssl.
> > 2. I can download it manualy, How to use it locally? Which dir should it copied in? Do I need to change WORKSPACE.in?
> 
> 1. As you have found out, grpc have a dependency over `boringssl`.
>    from your comment [#11237 (comment)](https://github.com/ApolloAuto/apollo/issues/11237#issuecomment-627789445),
>    we can see that the `bazel/grpc_deps.bzl` script in `grpc` checks whether `boringssl` was already specified in your workspace. If found, it will do nothing. Therefore we can
>    add an entry in `WORKSPACE.in` with a fixed `sha256` value like the following:
> 
> ```
> http_archive(
>     name = "boringssl",
>     sha256 = "fb236ae74676dba515e1230aef4cc69ab265af72fc08784a6755a319dd013ca6",
>     url = "file:///home/tmp/boringssl-83da28a68f32023fd3b95a8ae94991a07b1f6c62.tar.gz",
> )
> ```
> 
> In your case, you should substitute the `sha256` value with that of your downloaded `boringssl` tarball, which can be obtained by running:
> 
> ```
> sha256sum /home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz | awk '{print $1}'
> ```
> 
> Change the `url` to `file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz` accordingly.
> 
> And then you can run `./apollo.sh ....` as usual.

Another method 

> apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
> 
> ```shell
> if "boringssl" not in native.existing_rules():
>         native.http_archive(
>             name = "boringssl",
>             # on the chromium-stable-with-bazel branch
>             url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
>         )
> ```
> 
> notised that in old apollo dev docker image, boringssl is stored in /home/tmp.
> Maybe it is more friendly to Chinese user...

Another method to fix the `boringssl` timeout issue is to use a proxy if you have one.

```
export HTTP_PROXY=http://agent.example.com:8118
export HTTPS_PROXY=https://agent.example.com:8118
```

**Comment by BigBenSure** [comment]
> > apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
> > ```shell
> > if "boringssl" not in native.existing_rules():
> >         native.http_archive(
> >             name = "boringssl",
> >             # on the chromium-stable-with-bazel branch
> >             url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
> >         )
> > ```
> > 
> > 
> > notised that in old apollo dev docker image, boringssl is stored in /home/tmp.
> > Maybe it is more friendly to Chinese user...
> 
> Another method to fix the `boringssl` timeout issue is to use a proxy if you have one.
> 
> ```
> export HTTP_PROXY=http://agent.example.com:8118
> export HTTPS_PROXY=https://agent.example.com:8118
> ```

Thank you for your reply! I will try second way, if build passed, I can try to use first way and build a docker image.

**Comment by storypku** [comment]
> > > apollo use grpc-v1.14.2. I find some code in grpc-1.14.2/bazel/grpc_deps.bzl:
> > > ```shell
> > > if "boringssl" not in native.existing_rules():
> > >         native.http_archive(
> > >             name = "boringssl",
> > >             # on the chromium-stable-with-bazel branch
> > >             url = "file:///home/tmp/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz",
> > >         )
> > > ```
> > > 
> > > 
> > > notised that in old apollo dev docker image, boringssl is stored in /home/tmp.
> > > Maybe it is more friendly to Chinese user...
> > 
> > 
> > Another method to fix the `boringssl` timeout issue is to use a proxy if you have one.
> > ```
> > export HTTP_PROXY=http://agent.example.com:8118
> > export HTTPS_PROXY=https://agent.example.com:8118
> > ```
> 
> Thank you for your reply! I will try second way, if build passed, I can try to use first way and build a docker image.

I will close this issue now. Reopen it  if  solutions above don't work any more.
