### ISSUE TITLE
Real AI models used in AVs

### ISSUE THREAD

**Issue by eds89** [ApolloAuto/apollo#11230]
Hello,
Does anyone know whether any automotive OEM has open-sourced the pre-trained AI models used in their self-driving car projects? What's the state of the art on open-sourced models? I know there are lots of different models, each for a different ADAS function, involved in the operation of a normal AV. For now, any would suffice really.

I'm checking Apollo.auto at the moment, but I'm not sure it's applicable to real self-driving scenarios.

Best regards,

**Comment by daohu527** [comment]
Yes, they can actually be used. Yes, I think the conditions of use are speed and accuracy, of course deep learning has its own flaws, but we don't have a better way
