### ISSUE TITLE
Cyber示例运行无反应

### ISSUE THREAD

**Issue by ArcheyChen** [ApolloAuto/apollo#11247]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
Ubuntu 18.04
- **Apollo installed from (source or binary)**:
git克隆后，按照说明方法，非root身份启动dock，并在内部build成功了
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
5.5
### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

根据CyberAPI教程里面的方法，书写并运行了编译出来的二进制文件。但是运行之后便处于一直卡住的状态，没有反应。
同时，根据Cyber Quick start里面的方法，编译并用cyber_launch 启动，同样没有显示。

是否是输出在了别的地方，而非命令行？
### Supporting materials (screenshots, command lines, code/script snippets):
![TIM图片20200514184736](https://user-images.githubusercontent.com/45146080/81925695-6f0eb000-9613-11ea-8f82-e1c39e1c28bd.jpg)
![TIM图片20200514184246](https://user-images.githubusercontent.com/45146080/81925710-72a23700-9613-11ea-8d32-b05a8cd011da.jpg)

**Comment by changsh726** [comment]
By default, log messages will go to log files instead of stderr. You can add a line with `FLAGS_logtostderr = true;` at the beginning of your `main` function. Recompile and rerun it, and then you will see the messages in terminal.
