### ISSUE TITLE
How could the self-created lossy map be loaded into dreamview?

### ISSUE THREAD

**Issue by weiyinxie** [ApolloAuto/apollo#11253]
i habe created a lossy map using the msf_local_map_creator.sh but couldn't load it into the dreamview. what i want is to visualize the lossy map as background in dreamview
![00004596](https://user-images.githubusercontent.com/44968424/82022733-b8b4d480-96bf-11ea-9fd7-9dd60b08c915.png)

**Comment by vlin17** [comment]
Please try the following:
1. Convert the reflection background image to jpg format and name it as `background.jpg`
2. Place your `background.jpg` to modules/map/data/<your map dir>/background.jpg
3. Setup image map info in modules/dreamview/frontend/dist/parameters.json. See [sunnyvale_big_loop](https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/frontend/dist/parameters.json#L42) as an example. Required fields are mpp (meters per pixel), xres (x-axis resolution), yres (y-axis resolution), xorigin, yorigin (the center position of this map)
4. Refresh your browser

**Comment by qwetqwe** [comment]
Hi @weiyinxie ,
Could you tell me how you create background.jpg
thanks

**Comment by apollodevcommunity** [comment]
你好，在web中对点云地图可视化可以自行改写dreamview 难度有点大。不过apollo 提供了local_map_ visualize 进行单独窗口进行可视化 ——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=270
