### ISSUE TITLE
Testing Oracles 

### ISSUE THREAD

**Issue by salmanee** [ApolloAuto/apollo#11268]
Hi everyone,

I have a question about the integration tests output files under [/planning/testdata/](https://github.com/ApolloAuto/apollo/tree/a2666b6501af64e642ed3bd1b00fb872a8843e46/modules/planning/testdata/sunnyvale_loop_test). Are those considered to be the testing oracles? Meaning that, are those the files to inspect to determine whether that ADC behavior is acceptable?

 if so, what would be the best way to inspect them? As of now, I created records of the proto messages (.pb.txt files) and viewed them in dreamview. These records produced static images though so they don't seem to provide much information about the ADC behavior. 

Thanks,

**Comment by jmtao** [comment]
@salmanee this tests are written to run planning end-to-end of one frame.  We use these test case to make sure planning's output is fixed and determined based on the same set of input. 
Because there's only one frame (for each test), you can say it's static. 
If you want to observe dynamic behavior, you can do it in Dreamview. You need to set up the scenario you want to test,  routing, obstacles and etc.

**Comment by salmanee** [comment]
Thank you for your response @jmtao .. Any documentation on how to set up a scenario to observe its behavior dynamically in DreamView?

**Comment by jmtao** [comment]
@salmanee 
(1) you can run test cases with the scenario you want, on Azure. https://azure.apollo.auto/daily-build/public?locale=en-us
(2) you can run planning locally, and watch the behavior on Dreamview
- set up routing properly which can cover the scenario you want, lane_follow, stop_sign, traffic_light and etc
- launch planning locally
- use SIM_CONTROL mode to run: https://github.com/ApolloAuto/apollo/blob/6813a9af02f957d31f258b06bba41a06b4194806/docs/FAQs/Dreamview_FAQs.md#how-do-i-turn-on-sim-control

**Comment by jmtao** [comment]
Hi @salmanee , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
