### ISSUE TITLE
SelectTrafficLightScenario() function in scenario_manager.cc 

### ISSUE THREAD

**Issue by LawranceXcl** [ApolloAuto/apollo#11276]
`  std::vector<hdmap::PathOverlap> next_traffic_lights;
  static constexpr double kTrafficLightGroupingMaxDist = 2.0;  // unit: m
  const std::vector<PathOverlap>& traffic_light_overlaps =
      reference_line_info.reference_line().map_path().signal_overlaps();
  for (const auto& traffic_light_overlap : traffic_light_overlaps) {
    const double dist =
        traffic_light_overlap.start_s - traffic_light_overlap.start_s;
    if (fabs(dist) <= kTrafficLightGroupingMaxDist) {
      next_traffic_lights.push_back(traffic_light_overlap);
    }
  }`

    const double dist =
        traffic_light_overlap.start_s - traffic_light_overlap.start_s; 
Is it error here?

**Comment by jmtao** [comment]
@LawranceXcl good catch! fixed via the above PR. 
Many thanks for supporting Apollo!
