### ISSUE TITLE
我有一个主机A在docker内运行apollo3.0，主机B是windos系统。现在使用ros通讯时，发现B可以接收到docker内的topic（使用ros的标准msg type），但是在主机B使用topic echo时看不到消息。请问是为什么？

### ISSUE THREAD

**Issue by fengyongwei** [ApolloAuto/apollo#11271]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- ** Linux Ubuntu 18.04
- **windos 7:
- **Apollo version ( 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by XinrRunChao** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> ### System information
> 
>     * ** Linux Ubuntu 18.04
> 
>     * **windos 7:
> 
>     * **Apollo version ( 3.0)**:
> 
> 
> ### Steps to reproduce the issue:
> 
>     * **Please use bullet points and include as much details as possible**:
> 
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):

请问你解决了吗？遇到同样的问题，不过我的主机B是Ubuntu系统？
