### ISSUE TITLE
How to minimize the heading error and lateral error? 

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#11277]
How to minimize the heading error and lateral error? 

I use the procedure of the file ( How to Tune Control Parameters ) , it does not work properly.
you can take a look at the lateral and heading graph. 

![Screenshot from 2020-05-18 18-20-18](https://user-images.githubusercontent.com/61130487/82202698-e787b080-9934-11ea-9763-02193ee917dc.png)

**Comment by Addi2020** [comment]
The lateral error and heading error can be minimized by tuning MPC control (matrix_q) first and third sate respectively.

**Comment by schweinebauch** [comment]
hello dude
I have a question. What are differences between heading angle and yaw angle. I saw in vehicle_state_provider.cc mentioned, the only difference is the coordinate. Could you explain in details?  Heading direction is not the direction of linear velocity?
