### ISSUE TITLE
The compatibility about Apollo 3.5 and CUDA 10.1

### ISSUE THREAD

**Issue by zeyu-zha** [ApolloAuto/apollo#11279]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5
-**NVIDIA card : GTX1070
-**CUDA Version: 10.1
-**NVIDIA-SMI: 435.21
![nvidia-smi](https://user-images.githubusercontent.com/63231844/82207964-fc4f4e80-990a-11ea-8ad5-975350ec44b2.png)
Dear Apollo team,

Currently i am trying to running apollo 3.5 on my Ubuntu PC. But the preception module is not running on my PC, because the libcuda.so.1 can not be found. But as you see in the screenshot, the nvidia gpu card and cuda are rightly installed. So i have questions here, is the apollo 3.5 also compatible to the CUDA 10.1 ? Or the apollo is only compatible to CUDA 8.0?

**Comment by HongyiSun** [comment]
Did you install the nvidia-docker (or the newer version of docker with nvidia violate).
Could you please show your result of `nvidia-smi` inside the apollo docker (after running the 'dev_into.sh')

**Comment by zeyu-zha** [comment]
To question 1: **Did you install the nvidia-docker (or the newer version of docker with nvidia violate).**
If i understand right, i have already installed the nvidia-docker on my host PC, like it shows in the screen shot.
![Screenshot_nvidia-docker_smi](https://user-images.githubusercontent.com/63231844/83167385-7b653380-a110-11ea-9b6c-db924d40cf30.png)



To question 2: **Could you please show your result of `nvidia-smi` inside the apollo docker (after running the 'dev_into.sh')**
I can not use the "nvidia-smi" in the apollo docker container. I think that the nvidia driver should also be firstly installed in the apollo docker container. But when i try to install it with commands "sudo apt-get update" and "sudo apt install nvidia-435". I got the error "the install-package of nvidia version 435 was not be found".  Could you give me some advise for the question, how can i get the install-package "nvidia-435" in apollo docker container?

Besides i have also tried to install the founded install-package nvidia-418 in the apollo docker container. I got an other problem there. 
Here is the error msg in screenshot:
![Screenshot_Errormsg_install_418](https://user-images.githubusercontent.com/63231844/83168801-5671c000-a112-11ea-8be0-c0fada55a004.png)

Could you please help me for this problem ? 

Thanks in advance!

**Comment by HongyiSun** [comment]
> et update" and "sudo apt install nvidia-435". I got th

I don't think you will need to install nvidia things inside the apollo docker, as the apollo docker itself should get the environment ready with the driver and CUDA. So was there any error when you were running `dev_start.sh`, so the docker failed to get some of the layers?

**Comment by zeyu-zha** [comment]
The reference is about " FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04"
But i got one question here, if this reference can also be used for apollo 3.5?

Here are the msg in screen shots after the conduction of dev_start.sh. The error msgs are about libcaffe2_gpu.so and libcaffe2_gpu.so.
![Screenshot_dev_start_1](https://user-images.githubusercontent.com/63231844/83642300-f2864600-a5ae-11ea-942c-d45bc880b9b1.png)
![Screenshot_dev_start_2](https://user-images.githubusercontent.com/63231844/83642314-f5813680-a5ae-11ea-83ea-2abd3936a0f6.png)

There is no msg after the execution of dev_into.sh after the execution of dev_start.sh.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
