### ISSUE TITLE
build cyber rt docker failed

### ISSUE THREAD

**Issue by ivychen0515** [ApolloAuto/apollo#11275]
I tried to build the cyber rt docker on x86 platform, it failed with the error "command 'x86_64-linux-gnu-gcc' failed with exit status 1". I installed both libaasound2-dev and apt-file but still didn't work.
    ----------------------------------------
The complete error msg:
```
 x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-UKCoZ3/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c alsaaudio.c -o build/temp.linux-x86_64-2.7/alsaaudio.o
    alsaaudio.c:28:10: fatal error: alsa/asoundlib.h: No such file or directory
     #include <alsa/asoundlib.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-szyYPO/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-R2Vk8u-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-szyYPO/pyalsaaudio/
The command '/bin/sh -c bash /tmp/installers/install_python_modules.sh' returned a non-zero code: 1
```

The apt-file search shows the following result:
```
apt-file search alsa/asoundlib.h
libasound2-dev: /usr/include/alsa/asoundlib.h
libdssialsacompat-dev: /usr/include/dssi/alsa/asoundlib.h
```

**Comment by daohu527** [comment]
It seems that there is an error when installing the python module "pyalsaaudio".  
Can you try "**pip install pyalsaaudio**" and find if there is an error message?

**Comment by storypku** [comment]
> I tried to build the cyber rt docker on x86 platform, it failed with the error "command 'x86_64-linux-gnu-gcc' failed with exit status 1". I installed both libaasound2-dev and apt-file but still didn't work.
> ----------------------------------------
> The complete error msg:
> 
> ```
>  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-UKCoZ3/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c alsaaudio.c -o build/temp.linux-x86_64-2.7/alsaaudio.o
>     alsaaudio.c:28:10: fatal error: alsa/asoundlib.h: No such file or directory
>      #include <alsa/asoundlib.h>
>               ^~~~~~~~~~~~~~~~~~
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
> 
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-szyYPO/pyalsaaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-R2Vk8u-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-szyYPO/pyalsaaudio/
> The command '/bin/sh -c bash /tmp/installers/install_python_modules.sh' returned a non-zero code: 1
> ```
> 
> The apt-file search shows the following result:
> 
> ```
> apt-file search alsa/asoundlib.h
> libasound2-dev: /usr/include/alsa/asoundlib.h
> libdssialsacompat-dev: /usr/include/dssi/alsa/asoundlib.h
> ```

On which branch or tag did you build the cyber docker ?
Steps to reproduce the bug, please.

**Comment by ivychen0515** [comment]
> Can you try "**pip2 install pyalsaaudio**" and find if there is an error message?

the pyalsaaudio can be installed, but the error still exists.

**Comment by ivychen0515** [comment]
> On which branch or tag did you build the cyber docker ?
> Steps to reproduce the bug, please.

I built on the master branch. There are only two steps shown in the instruction[ Build Cyber RT Docker Image](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Docker.md#build-cyber-rt-docker-image).
`./build_cyber.sh cyber.x86_64.dockerfile`
The command finally returns the error.

**Comment by storypku** [comment]
> > On which branch or tag did you build the cyber docker ?
> > Steps to reproduce the bug, please.
> 
> I built on the master branch. There are only two steps shown in the instruction[ Build Cyber RT Docker Image](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Docker.md#build-cyber-rt-docker-image).
> `./build_cyber.sh cyber.x86_64.dockerfile`
> The command finally returns the error.

The docker build scripts on the master branch are outdated and maybe broken. If you want to build cyber.x86_64 docker image yourself, please take a look at the docker_dev branch.

**Comment by ivychen0515** [comment]
> > > On which branch or tag did you build the cyber docker ?
> > > Steps to reproduce the bug, please.
> > 
> > 
> > I built on the master branch. There are only two steps shown in the instruction[ Build Cyber RT Docker Image](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Docker.md#build-cyber-rt-docker-image).
> > `./build_cyber.sh cyber.x86_64.dockerfile`
> > The command finally returns the error.
> 
> The docker build scripts on the master branch are outdated and maybe broken. If you want to build cyber.x86_64 docker image yourself, please take a look at the docker_dev branch.

the docker_dev branch works, thx!

**Comment by oska874** [comment]
@storypku If I want to build docker images for Apollo5.5, which version of docker_dev should I use ?

**Comment by storypku** [comment]
> @storypku If I want to build docker images for Apollo5.5, which version of docker_dev should I use ?

I am afraid Dockerfile in the `r5.5.0` branch was broken either. As `docker_dev` branch has been merged into master already,  we can build `apollo-{cyber,dev}` images from the `master` branch now.
