### ISSUE TITLE
How to build multiple versions of Apollo in the same computer

### ISSUE THREAD

**Issue by zhanghming** [ApolloAuto/apollo#11272]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **Linux Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 5.5**:

### Problems
I have installed Apollo 5.5 in my computer, and everything runs ok. But when I want to use LGSVL to test the Apollo, I found the LGSVL currently only support the Apollo 5.0, so I download the lgsvl/apollo 5.0 and compiled it.

However, the problem is the compiling results of Apollo 5.5 and Apollo 5.0 were save in the same location, it's `/home/zhanghm/.cache/bazel/_bazel_zhanghm/540135163923dd7d5820f3ee4b306b32` in my computer, after compiling lgsvl/apollo 5.0, I found I can't run Apollo 5.5 successfully, and the lgsvl/apollo 5.0 also not worked ok, throwed the error like `can't linked some libraries`.

I guess it must be the bazel build results location problems. I wonder whether can specify the results saving path when I build different Apollo version.

**Comment by storypku** [comment]
A dedicated pull request https://github.com/ApolloAuto/apollo/pull/11215 was already backported to the r5.5.0 branch.  It uses  subdirectory `./.cache/dist` of your apollo.git clone as destination of bazel's startup option `--output_user_root`.  By this way, you can differentiate Apollo 5.5 branch with Apollo 5.0 branch (which hasn't this option enabled.)

**Comment by zhanghming** [comment]
@storypku Thansks for your reply.
Dose this mean I should use the newest master r5.5.0 branch to compile to realize my purpose?

**Comment by lemketron** [comment]
@zhanghming Please refer to [LGSVL issue #614](https://github.com/lgsvl/simulator/issues/614#issuecomment-630450396) for information on using apollo master with LGSVL Simulator.

**Comment by storypku** [comment]
> @storypku Thansks for your reply.
> Dose this mean I should use the newest master r5.5.0 branch to compile to realize my purpose?

I guess so. The change was only backported in the latest r5.5.0 branch.
