### ISSUE TITLE
Which version can successfully be built ?

### ISSUE THREAD

**Issue by NoRomantic** [ApolloAuto/apollo#11291]
Hello, I'd like to know which version do you successfully build Apollo, as well as the Ubuntu version. I'm a little frustrated now, because I've tried separately to build Apollo in Ubuntu16.04 and Ubuntu14.04-desktop (Apollo 1.0 and Apollo 2.0), however, both failed. 
Each time I run the command `bash apollo.sh build`, there comes some error reports. I searched on the GitHub issue page, however, some errors like "bazel version mismatch" have not been resolved yet. So please tell me which Apollo version can be built easily in which Ubuntu version (just be able to run dreamview is great).

**Comment by storypku** [comment]
Maybe you should try the master branch or the r5.5.0 branch, both of which are currently actively maintained.

**Comment by NoRomantic** [comment]
Thanks for your reply, I'll try r5.5.0 branch later. Once I correctly install it, I'll close this issue.
