### ISSUE TITLE
apollo/scripts directory is no longer added to path for $USER_ID 1000

### ISSUE THREAD

**Issue by lemketron** [ApolloAuto/apollo#11296]
**Describe the bug**
apollo/scripts directory is no longer added to path for $USER_ID 1000

**To Reproduce**
1. docker/scripts/dev_start.sh
2. docker/scripts/dev_into.sh
3. bootstrap.sh
4. bootstrap.sh script not found in apollo master since "/apollo/scripts" not in path (for $USER_ID 1000) but worked fine in apollo 5.0

**Expected behavior**
/apollo/scripts should be in PATH and bootstrap.sh (and other scripts) should launch without full path.

In apollo, docker/scripts/dev_start.sh calls scripts/docker_adduser.sh which (besides adding the user) appears to export /apollo/scripts into the PATH.

In apollo 5.0, calling docker_adduser.sh is only skipped if $USER is "root".

In apollo master, calling docker_adduser.sh is now also skipped if $USER is "apollo" or if $USER_ID is 1000 (which is typically the user id of the first user who creates and installs the system).

This change happened in [commit a9fb059d](https://github.com/ApolloAuto/apollo/commit/a9fb059d7daa82aeb1f6956c29eef23bdcdfb3e7) to apollo master in April.

There are several other things that happen in docker_adduser.sh (setting user file ownership, setting access permissions on GPS and camera devices, etc.) that appear to also be skipped now for USER_ID 1000 so I'm curious if that might cause problems for some users.

Even if my guess as to why this is happening is wrong, the issue in the bug title (that /apollo/scripts is no longer in the PATH in apollo master) is still the main issue that I am reporting here.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by lemketron** [comment]
Another possible fix for this might be to add `/apollo/scripts` into the export PATH line in `scripts/apollo_base.sh`...?

**Comment by storypku** [comment]
> Another possible fix for this might be to add `/apollo/scripts` into the `export PATH` line in `scripts/apollo_base.sh`...?


> **Describe the bug**
> apollo/scripts directory is no longer added to path for $USER_ID 1000
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. docker/scripts/dev_start.sh
> 2. docker/scripts/dev_into.sh
> 3. bootstrap.sh
> 4. bootstrap.sh script not found in apollo master since "/apollo/scripts" not in path (for $USER_ID 1000) but worked fine in apollo 5.0
> 
> **Expected behavior**
> /apollo/scripts should be in PATH and bootstrap.sh (and other scripts) should launch without full path.
> 
> In apollo, docker/scripts/dev_start.sh calls scripts/docker_adduser.sh which (besides adding the user) appears to export /apollo/scripts into the PATH.
> 
> In apollo 5.0, calling docker_adduser.sh is only skipped if $USER is "root".
> 
> In apollo master, calling docker_adduser.sh is now also skipped if $USER is "apollo" or if $USER_ID is 1000 (which is typically the user id of the first user who creates and installs the system).
> 
> This change happened in [commit a9fb059d](https://github.com/ApolloAuto/apollo/commit/a9fb059d7daa82aeb1f6956c29eef23bdcdfb3e7) to apollo master in April.
> 
> There are several other things that happen in docker_adduser.sh (setting user file ownership, setting access permissions on GPS and camera devices, etc.) that appear to also be skipped now for USER_ID 1000 so I'm curious if that might cause problems for some users.
> 
> Even if my guess as to why this is happening is wrong, the issue in the bug title (that /apollo/scripts is no longer in the PATH in apollo master) is still the main issue that I am reporting here.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 18.04

Thank you for reporting this.  We will fix it ASAP. Please stay tuned.

**Comment by storypku** [comment]
> Another possible fix for this might be to add `/apollo/scripts` into the `export PATH` line in `scripts/apollo_base.sh`...?

Pull request #11314 aims to solve this problem. Would you please help review that? @lemketron
