### ISSUE TITLE
How to let apollo running at 80km/h in simcontrol?

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#11310]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by BigBenSure** [comment]
I set `--planning_upper_speed_limit=40.00` in `modules/planning/conf/planning.conf`,but apollo can only run at 56km/h in a straight road, rather than 50km/h.If I want to increase the speed to 80km/h, what else should I do?

**Comment by BigBenSure** [comment]
I print some AERROR in `modules/planning/tasks/deciders/speed_bounds_decider/speed_limit_decider.cc`
I see `curr_speed_limit` is 27.778m/s, but apollo can not run that so fast.

**Comment by BigBenSure** [comment]
apollo5.0

**Comment by daohu527** [comment]
Which map have you used? there's some limit ("speed_limit") in the map too.  
https://github.com/ApolloAuto/apollo/blob/07c4e7d94daf9eb53641c92f8e491fa4532b6270/modules/map/data/demo/base_map.txt#L9444-L9450

**Comment by BigBenSure** [comment]
> Which map have you used? there's some limit ("speed_limit") in the map too.
> https://github.com/ApolloAuto/apollo/blob/07c4e7d94daf9eb53641c92f8e491fa4532b6270/modules/map/data/demo/base_map.txt#L9444-L9450

thank you for your reply!  I know that  there's some limit ("speed_limit") in the map. But I comment it in `reference_line_.GetSpeedLimitFromS(reference_line_s)` , written in `modules/planning/reference_line/reference_line.cc`. I think map-speed_limit is a step to generate `curr_speed_limit`.My question is : if my curr_speed_limit is 27.778m/s(100km/h),why apollo can't run at that speed? What else `step` or `task` in LANE_FOLLOW can influence the final speed?

**Comment by BigBenSure** [comment]
Could anyone tell me the right step to increase the apollo running speed? Ignore what I have done...

**Comment by BigBenSure** [comment]
I found that: in `piecewise_jerk_speed_optimizer.cc`,I see `piecewise_jerk_problem.set_dx_bounds` is always `27.778`m/s, but the output:
`const std::vector<double>& ds = piecewise_jerk_problem.opt_dx();`
ds[i] is in the range of 8 ~ 14m/s...

**Comment by HongyiSun** [comment]
There is also a `--default_cruise_speed=11.18` in the `modules/planning/conf/planning.conf`. Where the planning optimizer will trying to keep close to that speed without violate and speed limit(from planning setup or map). 
So I guess that's the desired default speed you want to change.

**Comment by BigBenSure** [comment]
> There is also a `--default_cruise_speed=11.18` in the `modules/planning/conf/planning.conf`. Where the planning optimizer will trying to keep close to that speed without violate any speed limit(from planning setting or map).
> So I guess that's the desired default speed you want to change.

Thank you for your reply! I set `--default_cruise_speed` to maybe 25.55m/s, it is useful in apollo 3.5 but  it is useless in apollo 5.0. Maybe in apollo 5.0, they use  PUBLIC_ROAD planner instead of LATTICE planner which was used in apollo 3.5

**Comment by HongyiSun** [comment]
> > There is also a `--default_cruise_speed=11.18` in the `modules/planning/conf/planning.conf`. Where the planning optimizer will trying to keep close to that speed without violate any speed limit(from planning setting or map).
> > So I guess that's the desired default speed you want to change.
> 
> Thank you for your reply! I set `--default_cruise_speed` to maybe 25.55m/s, it is useful in apollo 3.5 but it is useless in apollo 5.0. Maybe in apollo 5.0, they use PUBLIC_ROAD planner instead of LATTICE planner which was used in apollo 3.5

it's also used in the `piecewise_jerk_speed_optimizer.cc`, so it should worked in 5.0 as well. What was the result after you changed both the default_speed and the speed_limit?

**Comment by Isaac0424** [comment]
Hi there, how is it going ?I wonder that Have you ever solved this rate limiting problem? 
I have same problem. Any help would be appreciated.
