### ISSUE TITLE
Add a global flag for CYBER time mode

### ISSUE THREAD

**Issue by rongguodong** [ApolloAuto/apollo#11317]
**Is your feature request related to a problem? Please describe.**
I am using LGSVL Simulator with Apollo. The timesamps of sensors use `simulation time` instead of real time. So they are different to the time used in Apollo modules (e.g. localization, perception, etc.).

I see Apollo's Time class has a CYBER time mode. But in current implementation, Cyber time is always system time. So the SYSTEM mode and CYBER mode are always the same.

ROS has similar ability: it can use simulation time from "/clock" topic if the global flag "use_sim_time" is true. I think Cyber should also support this useful mode.

**Describe the solution you'd like**
We can add a global flag (e.g. "USE_SIM_TIME"), and have Cyber's Time class query this flag. If this flag is set to true, Cyber::Time::Now() read the "current time" from a particular Cyber channel (e.g. /clock) and use that as the return value.

If this is added, we can simply set the global flag and publish to the clock channel from outside of Apollo (i.e. from LGSVL Simulator), and set Apollo's time mode to CYBER to have Apollo using simulation time instead of real time.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rongguodong** [comment]
@ycool I see you created the MOCK time mode. Do you have better alternative to use this MOCK mode from outside of Apollo?

**Comment by rongguodong** [comment]
In fact, I see Apollo has three time modes: SYSTEM, MOCK, and CYBER, and MOCK mode is for testing purpose. So it would be better to add a global flag in Cyber to have Cyber use simulation time.
In the current implementation, Cyber always returns system time. So the SYSTEM mode and CYBER mode in Apollo are always the same.
ROS has similar ability: it can use simulation time from /clock topic if the global flag "use_sim_time" is true. I think Cyber should also support this useful mode.

**Comment by xiaoxq** [comment]
Should have been solved with mock time util in latest master HEAD.
