### ISSUE TITLE
Using cyber_recorder to record data generate many offline record files

### ISSUE THREAD

**Issue by zhanghming** [ApolloAuto/apollo#11328]
### Systems
Apollo 5.5
Ubuntu 16.04

### Questions
When I run the following scripts by use LGSVL simulator to record offline `record` data for testing:
```
cyber_recorder record -a -o lgsvl.record
```
I found the recorded files have been saved with `lgsvl.record.00000, lgsvl.record.000001` and so on, and every file is `2.2G`, I want to know how to unset the record file size limit so that I can record the messages in one file.

And another problem is when I use the offline lgsvl data to test Apollo 5.5 perception module, I get `cann't get the pose` error due to the localization related messages delay. However, when I record these messages, I'm sure the messages frequency is normal, I don't know why.

**Comment by HongyiSun** [comment]
For your first question, you may run `cyber_recorder record --help` to see the record options.

There are options like `-i, --segment-interval <seconds>	record segmented every n second(s)
	-m, --segment-size <MB>			record segmented every n megabyte(s)` you may found useful.

**Comment by unacao** [comment]
Did the suggestion above help solve your issue? We will close the issue for now. If you have any additional question, please feel free to open a new issue.
