### ISSUE TITLE
function ComputeSTBoundary(PathDecision* path_decision) in st_boundary_mapper.cc

### ISSUE THREAD

**Issue by LawranceXcl** [ApolloAuto/apollo#11331]
`     else if (!decision.has_ignore()) {
      // 3. Ignore those unrelated obstacles.
      AWARN << "No mapping for decision: " << decision.DebugString();
    }`
I have a doubt  here.Should it be changed to `  else if (decision.has_ignore()){...}`?

**Comment by jmtao** [comment]
@LawranceXcl there's nothing wrong here. 
it is to deal with(a warning logging) longitudinal decisions other than stop/follow/yield/overtake when there is NO ignore decision. 
currently, we don't have any other longitudinal decisions besides the above, so the code never runs into here. We can keep it as a sanity check just in case we may introduce another longitudinal decision. i.e. there's a longitudinal decision but we are IGNORing it, give it a WARN log.

**Comment by jmtao** [comment]
@LawranceXcl I'll close this issue for now. Thanks for supporting Apollo!
