### ISSUE TITLE
bash: cyber_visualizer: command not found

### ISSUE THREAD

**Issue by Sun1307010608** [ApolloAuto/apollo#11333]
hello @Apollo,
I used apollo-5.5.0 in ubuntu16.04LTS， I could run the "demo_3.5.record" demo data an see the result in localhost:8888. And the command cyber_monitor can be used correctly. but the errors happened when i ran the command like “cyber_visualizer”, "rosbag_to_record" etc. And I used “sudo find / -name cyber_visualizer” cannot find any executable file as this name. Do you guys knows what's the problem.

![cyb](https://user-images.githubusercontent.com/30978405/82887165-31e2e000-9f7a-11ea-86f3-8107f4c78600.png)

**Comment by zhanghming** [comment]
The `cyber_visualizer` is not be built by default, you can refer to [this](https://apolloauto.io/t/cyber-visualizer/647/7) to built it.

**Comment by Sun1307010608** [comment]
@zhanghming Thank you very much!!! I solved this problem by your proposal.
