### ISSUE TITLE
Question about 'bool PathBoundsDecider::GetBoundaryFromLanesAndADC'

### ISSUE THREAD

**Issue by rrenjie** [ApolloAuto/apollo#11340]
`double curr_left_bound =
    std::fmax(curr_left_bound_lane, curr_left_bound_adc) - offset_to_map;`
should it be `std::fmin` here? If the left lane bound is a curb, the adc might hit the curb if curr_left_bound_adc is larger. The same problem goes with
`double curr_right_bound =
    std::fmin(curr_right_bound_lane, curr_right_bound_adc) - offset_to_map;`

**Comment by jmtao** [comment]
@rrenjie these are adjustments on path bounds based on ADC's position. 
for left bound, if adc_l is larger than left_bound, left_bound shall move further to left to fit in adc's actual position.
nothing wrong. 
thanks

**Comment by rrenjie** [comment]
@jmtao Thank for reply. The problem is, if adc is moving towards the left curb, it is possible curr_left_bound_adc is further left than left_lane_bound because there is an ADC_speed_buffer in curr_left_bound_adc. In such a situation, the left curb is no longer a hard constraint for ADC, and the ADC might hit the left curb.

**Comment by jmtao** [comment]
@rrenjie lane boundary is not necessarily road boundary, and therefore not a hard constraint. ADC_speed buffer is something we can't avoid.  you can consider curr_right_bound_adc as the position that ADC will hit for sure.

**Comment by AlexandrZabolotny** [comment]
hello
I have a similar problem. Help me decide.
I noticed that the planning module builds a path that crosses the curb. I us Apollo pre6

Below are two examples.

We cross the curb when we turn right.
Screenshot from 2021-11-20 11-39-41

We cross the curb when we start from a position outside the map.
Screenshot from 2021-11-20 11-41-40
