### ISSUE TITLE
Apollo Auto adapter_manager.h not found in Apollo 3.5

### ISSUE THREAD

**Issue by miewan** [ApolloAuto/apollo#11349]
I am trying to create IR for each files in Apollo Auto 3.5 using clang++

For files modules/tools/planning/planning_stats.cc, I get an error **_'modules/common/adapters/adapter_manager.h' file not found_**

And I look at the directory, and there is no adapter_manager.h

Can anyone please tell me why this file is missing from apollo auto 3.5?

**Comment by xiaoxq** [comment]
Yeah, the adapter_manager was retired in v3.5 while the planning_stats tool was missed to be cleaned up until v5.5. Sorry for the trouble.

**Comment by miewan** [comment]
Is this the same for terminal.cc in the tools module too? Because it’s also
use adapter_manager

**Comment by miewan** [comment]
> Yeah, the adapter_manager was retired in v3.5 while the planning_stats tool was missed to be cleaned up until v5.5. Sorry for the trouble.

Is this the same for terminal.cc in the tools module too? Because it’s also use adapter_manager
