### ISSUE TITLE
How to pause In simcontrol simulation?

### ISSUE THREAD

**Issue by LawranceXcl** [ApolloAuto/apollo#11357]
RT

**Comment by daohu527** [comment]
If you can save the chassis status, then you can pause the sim control. It seems that it does not support now

**Comment by rrenjie** [comment]
I also need pause function in simcontrol very much.

**Comment by daohu527** [comment]
1. What are the usage scenarios? Pause by stopping playing bag?
2. Can you describe this requirement in detail?

**Comment by rrenjie** [comment]
> 1. What are the usage scenarios? Pause by stopping playing bag?
> 2. Can you describe this requirement in detail?

@daohu527 
When running simcontrol (perfect control), I wish the simulation could be paused by clicking a button on dreamview (and restored by clicking the button again). Besides the pause function, it would be better if there is a step-over function such that I can run the simulation step by step.

**Comment by daohu527** [comment]
@rrenjie I will take a look at it
