### ISSUE TITLE
The installation of Apollo-5.5

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#11365]
Can I ask about the installation guide for Apollo-5.5? I want to uses it along with LGSV like the tutorial existing in the link below. Do you have any prepared tutorials?

https://github.com/lgsvl/apollo-5.0

### System information

- Linux Ubuntu 18.04,
- Apollo installed from source,
- Apollo version 5.5.

**Comment by daohu527** [comment]
There is an installation instruction [apollo_software_installation_guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md)

**Comment by Martin20** [comment]
Thanks, @daohu527  

Does it work with LGSVL simulator?

**Comment by daohu527** [comment]
Lgsvl have their own apollo branch [5.0](https://github.com/lgsvl/apollo-5.0)  

In my opinion, they mainly added the bridge code. If the original file has not been modified in apollo 5.5, you can transplant the bridge code to apollo 5.5

**Comment by michael4338** [comment]
Hi @Martin20 , hope the resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue.
