### ISSUE TITLE
Which manufacturers' lidars can be used in Apollo

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11384]
Hello!  
Help me!  
I have a **"robosense RS-Ruby"** lidar  
https://www.robosense.ai/rslidar/rs-ruby  

1. Can I use this lidar?  
2. Where can I download the driver of this lidar for Apollo?

**Comment by daohu527** [comment]
There is no default robosense's lidar driver in apollo.  

Maybe you can ask if the manufacturer has adapted to the apollo driver.

**Comment by AlexandrZabolotny** [comment]
https://github.com/ApolloAuto/apollo/pull/12346/files
