### ISSUE TITLE
Is there any cmd line tool for apollo similar to `rostopic pub`? Or, does Cyber support `pub` operations?

### ISSUE THREAD

**Issue by scienceplus** [ApolloAuto/apollo#11388]
apollo有类似rostopic pub这样的命令行工具么？或者说cyber支持pub功能么？
看了之前的版本，似乎一直缺失这个功能。

**Comment by storypku** [comment]
> apollo有类似rostopic pub这样的命令行工具么？或者说cyber支持pub功能么？
> 看了之前的版本，似乎一直缺失这个功能。

Please try as best to use English when creating issues. It's more friendly to non-Chinese speakers.

**Comment by scienceplus** [comment]
学习中文是一件很快乐的事！

**Comment by Avps1** [comment]
Hi, I have the same query - I could not find any command similar to rostopic pub in CyberRT. I want to publish some messages to the topic /apollo/perception/obstacles

**Comment by daohu527** [comment]
for now there's no similar tool, we will add it to future support features
