### ISSUE TITLE
Installing Apollo

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#11398]
- Linux Ubuntu 18.04):
- Apollo installed from source :
- Apollo version 5.5:

I was going to install Apollo in the link below:
https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#Run-Apollo-in-Ubuntu-16

However, when I run "git clone git@github.com:ApolloAuto/apollo.git" I receive the error below. Do I need special permission? If so, how can I get it?

Cloning into 'apollo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by daohu527** [comment]
You don't need any permission to clone the repository.  

Maybe you should check your ssh key in github settings. The public key in your computer " ~/.ssh/" is not set in github setting. So you don't have the permission to clone the code in any repository.

**Comment by marcusvinicius178** [comment]
Hi @daohu527 is it possible install APollo 5.0 from source? I have already downloaded the 5.0 release...I wonder how to build it without docker:


After 
`cd apollo`

`ls`

I get apollo.sh and other files, must I just run this .sh?  Or other steps are needed?

Thanks in advance

**Comment by daohu527** [comment]
No, you can't. Currently need to compile, the current releases are source code, not binary.
