### ISSUE TITLE
What's the difference between 'relative time' and 'heading time' in planning

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#11393]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution ( Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.５)**:

### Steps to reproduce the issue:
1、If ComputeReinitStitchingTrajectory function isn't called(no need to ReinitStitchingTrajectory) in trajectory_stitcher.cc, does the  prev_trajectory->header_time() will be changed?
２、prev_trajectory->StartPoint().relative_time(). What does the relative() mean?
if this means the time difference between startpoint and current point, prev_trajectory->StartPoint().relative_time() this value is always zero?

**Comment by jmtao** [comment]
@ManXiaoMi relative_time is the "relative" time compared to "current" timestamp. relative_time=0.1 means 0.1sec ahead of current time. relative_time=-0.1 means 0.1sec before current time.

**Comment by jmtao** [comment]
Hi @ManXiaoMi , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
