### ISSUE TITLE
Question about using more than one CAN interface

### ISSUE THREAD

**Issue by vkaser** [ApolloAuto/apollo#11396]
Hi folks!
Is it possible to use more than one CAN interface channel simultaneously (e.g. can0 and can1) in **canbus** module? 

### System information
- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **Apollo installed from**: source
- **Apollo version**:5.0

### Steps to reproduce the issue:
There is only one cancard parameter in canbus_conf.pb.txt file:
```
can_card_parameter {
  brand:SOCKET_CAN_RAW
  type: USB_CARD
  channel_id: CHANNEL_ID_ZERO
}
```
I want to add another channel_id. 

### Module:
- **Canbus**

**Comment by Capri2014** [comment]
yes you can, just needs to assign different channel id.  for instance, in Apollo we assign Vehicle Chassis as channel zero and Radar input as channel one.

**Comment by vkaser** [comment]
Thank you. But in this case I need to add another directory (eg. canbus2), but I want to use two can interfaces for one vehicle.

**Comment by jp12AI** [comment]
@vkaser Are you using a USB can card connection? Can you please tell me what you're using and what files you modified? I'm trying to do the same thing. I mentioned what I modified here: https://github.com/ApolloAuto/apollo/issues/13977 Information on this would be appreciated.

**Comment by vkaser** [comment]
@jp12AI I'm using Kvaser USB CAN device. Firstly set up Kvaser interface (eg, `sudo ip link set can0 type can bitrate 500000 && sudo ip link set up can0`). Test your interface with `candump can0` command (CAN messages should appear). Then you need to configure **modules/calibration/data/<your_vehicle>/cancard_params/canbus_conf.pb.txt** with the following contents:

```bash
vehicle_parameter {
  brand: <your_vehicle>
  max_enable_fail_attempt: 5
  driving_mode: COMPLETE_AUTO_DRIVE
}

can_card_parameter {
  brand: SOCKET_CAN_RAW
  type: USB_CARD
  channel_id: CHANNEL_ID_ZERO
}

enable_debug_mode: true
enable_receiver_log: true
enable_sender_log: true
```

**Comment by jp12AI** [comment]
> @jp12AI I'm using Kvaser USB CAN device. Firstly set up Kvaser interface (eg, `sudo ip link set can0 type can bitrate 500000 && sudo ip link set up can0`). Test your interface with `candump can0` command (CAN messages should appear). Then you need to configure **modules/calibration/data/<your_vehicle>/cancard_params/canbus_conf.pb.txt** with the following contents:
> 
> ```shell
> vehicle_parameter {
>   brand: <your_vehicle>
>   max_enable_fail_attempt: 5
>   driving_mode: COMPLETE_AUTO_DRIVE
> }
> 
> can_card_parameter {
>   brand: SOCKET_CAN_RAW
>   type: USB_CARD
>   channel_id: CHANNEL_ID_ZERO
> }
> 
> enable_debug_mode: true
> enable_receiver_log: true
> enable_sender_log: true
> ```

@vkaser  I appreciate the response. I followed these commands and they all execute correctly. I had already modified the config file but I double-checked. I am not using a Kvaser device. This doesn't matter just letting you know. Everything seems to work however, I get this error in apollo dreamview. I am using apollo 5.0. My can adapter needs to be plugged into car to start however it seems this needs to be configured. Do you know how I can fix this error? Thank you. Any help would be appreciated. Those commands worked.

**Comment by vkaser** [comment]
You just neet to change the config params in the dreamview module. Open 
`modules/dreamview/conf/hmi_modes/navigation.pb.txt` and change 
```bash
...
monitored_components {
  key: "ESD-CAN"
  value: {
    # Special EsdCanMonitor.
  }
}
...
```
to 
```bash
...
monitored_components {
  key: "SocketCAN"
  value: {
    # Special SocketCanMonitor.
  }
}
```

**Comment by jp12AI** [comment]
> You just neet to change the config params in the dreamview module. Open
> `modules/dreamview/conf/hmi_modes/navigation.pb.txt` and change
> 
> ```shell
> ...
> monitored_components {
>   key: "ESD-CAN"
>   value: {
>     # Special EsdCanMonitor.
>   }
> }
> ...
> ```
> 
> to
> 
> ```shell
> ...
> monitored_components {
>   key: "SocketCAN"
>   value: {
>     # Special SocketCanMonitor.
>   }
> }
> ```

I did this and it worked. Thank you for the help. @vkaser
