### ISSUE TITLE
Can not access apollo data open platform

### ISSUE THREAD

**Issue by ChantingW** [ApolloAuto/apollo#11403]
Can not access apollo data open platform to get sensor data to test perception module.
Could anyone share a goolge driver link for demo-sensor-data-apollo-2.0.tar.gz.

**Comment by hoodiney** [comment]
I have the same problem, too! The platform website always redirects to Apollo's homepage.

**Comment by JackFu123** [comment]
Hi, the data on data.apollo.auto was too old. So we retired the platform.
You could find more data here: [http://apolloscape.auto/#](http://apolloscape.auto/#)
