### ISSUE TITLE
apollocache.blob.core.windows.net is deprecated?

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#11404]
apollocache.blob.core.windows.net is not able to access.
When I try to install pcl on arm64 with script "/apollo/docker/build/installers/install_pcl.sh ", it shows `/apollo/docker/build/installers/install_pcl.sh `.

**Comment by storypku** [comment]
> apollocache.blob.core.windows.net is not able to access.
> When I try to install pcl on arm64 with script "/apollo/docker/build/installers/install_pcl.sh ", it shows `/apollo/docker/build/installers/install_pcl.sh `.

The link to `apollocache.blob.core.windows.net` seems to be broken. :-(

**Comment by storypku** [comment]
> > apollocache.blob.core.windows.net is not able to access.
> > When I try to install pcl on arm64 with script "/apollo/docker/build/installers/install_pcl.sh ", it shows `/apollo/docker/build/installers/install_pcl.sh `.
> 
> The link to `apollocache.blob.core.windows.net` seems to be broken. :-(

If your purpose is to build and install pcl on arm64, maybe you can follow the steps on the x86_64 platform, as specified in https://github.com/ApolloAuto/apollo/blob/docker_dev/docker/build/installers/install_pcl.sh

**Comment by Eclipsehelio** [comment]
@oska874 You can build PCL from source on arm64 platform, follow the command below:
```shell
$ sudo apt install libusb-1.0 libusb-dev
$ wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz
$ tar xzvf pcl-1.7.2.tar.gz
$ cd pcl-pcl-1.7.2/
$ export TASK=build
$ export CC=gcc
```
Edit file `.travis.sh` in the current directory, substitute `function build_gcc ()` content with
```txt
function build_gcc ()
{
  # A reduced build, only pcl_common
  # Configure
  mkdir $BUILD_DIR && cd $BUILD_DIR
  cmake -DCMAKE_C_FLAGS=$CMAKE_C_FLAGS -DCMAKE_CXX_FLAGS=$CMAKE_CXX_FLAGS \
        -DCMAKE_BUILD_TYPE=Release \
        -DPCL_ONLY_CORE_POINT_TYPES=ON \
        -DBUILD_2d=ON \
        -DBUILD_features=ON \
        -DBUILD_filters=ON \
        -DBUILD_geometry=ON \
        -DBUILD_global_tests=OFF \
        -DBUILD_io=ON \
        -DBUILD_kdtree=ON \
        -DBUILD_keypoints=ON \
        -DBUILD_ml=ON \
        -DBUILD_octree=ON \
        -DBUILD_outofcore=ON \
        -DBUILD_people=ON \
        -DBUILD_recognition=ON \
        -DBUILD_registration=ON \
        -DBUILD_sample_consensus=ON \
        -DBUILD_search=ON \
        -DBUILD_segmentation=ON \
        -DBUILD_stereo=OFF \
        -DBUILD_surface=ON \
        -DBUILD_tools=ON \
        -DBUILD_tracking=ON \
        -DBUILD_visualization=ON \
        $PCL_DIR
  # Build
  make -j6
}
```
Edit file `CMakeLists.txt` in the current directory, add compiler option `-std=c++11` in Line 93、100、103、108
Now ready to build with the following commands:
```shell
$ bash .travis.sh
$ cd build
$ sudo make install
```

**Comment by oska874** [comment]
build pcl on arm platform cost too much time，nearly half day or one day

**Comment by storypku** [comment]
> Almost all library related to apollo need to be manual download and translate. What's more, the verson and configuration of the libraries are NONE.
> Will apollo release a guide of how to build docker images and **libraries** ,or how to set native apollo runtime environment?

Not the case with Apollo master now. Building Apollo Docker images on x86_64 should be rather smooth now. For aarch64, building the Cyber image is OK. See updated Docker Build  README.md in PR  #12234
