### ISSUE TITLE
docker-dev branch breaks LGSVL simulator

### ISSUE THREAD

**Issue by storypku** [ApolloAuto/apollo#11423]
`modules/contrib/lgsvl_msgs/proto/BUILD` file generated by our universal  `scripts/proto_build_generator.py`  defines new `cc_proto_library` targets, which maybe imcompatible with current lgsvl simulator.  Investigation needs to be done to make it work again.

@xiaoxq @lemketron

**Comment by lemketron** [comment]
@rongguodong Can you take a look at this?

**Comment by rongguodong** [comment]
What is "scripts/proto_build_generator.py"? I cannot see this file on Apollo's github repo. 
@storypku Can you explain the problem with more details?

**Comment by storypku** [comment]
> What is "scripts/proto_build_generator.py"? I cannot see this file on Apollo's github repo. 
> 
> @storypku Can you explain the problem with more details?

This file was on the docker_dev branch.

**Comment by rongguodong** [comment]
Ah, I see. I have just tested LGSVL with Apollo's master branch, but not this docker_dev branch.

Can you explain what is this branch for, and what is this script doing?

Some general information: lgsvl_msgs just adds some new messages for 2D and 3D ground truths. If no ground truth sensor are used, this folder is not used.

**Comment by storypku** [comment]
> Ah, I see. I have just tested LGSVL with Apollo's master branch, but not this docker_dev branch.
> 
> Can you explain what is this branch for, and what is this script doing?
> 
> Some general information: lgsvl_msgs just adds some new messages for 2D and 3D ground truths. If no ground truth sensor are used, this folder is not used.

The docker_dev branch features bazel 3.x and refactored Dockerfiles with various system package upgrades.  

The script is used to autogenerate BUILD file for each of the `xxx/proto/` dirs. 
Usage: `scripts/proto_build_generator.py modules/contrib/lgsvl_msgs/proto/BUILD` in LGSVL's case.

**Comment by rongguodong** [comment]
modules/contrib/lgsvl_msgs/proto already has a BUILD file in it, why do you need to regenerate a new one?
I tested that the existing BUILD file works well. So if you really need to generate a new BUILD file to replace the current one, as long as the new BUILD file generates exactly the same result as the current one, it should works fine with LGSVL Simulator.

**Comment by storypku** [comment]
> modules/contrib/lgsvl_msgs/proto already has a BUILD file in it, why do you need to regenerate a new one?
> I tested that the existing BUILD file works well. So if you really need to generate a new BUILD file to replace the current one, as long as the new BUILD file generates exactly the same result as the current one, it should works fine with LGSVL Simulator.

Good question. In fact, we regenerate BUILD file for `proto` files/directories for a good reason: A uniform naming scheme for proto-related targets, and maximize parallelism in the build process using latest Bazel versions.

Code snippet from `scripts/proto_build_generator.py`:

```
def cc_grpc_name(protofile):
    (sketch, _) = os.path.splitext(protofile)
    return sketch + "_cc_grpc"


def cc_proto_name(protofile):
    (sketch, _) = os.path.splitext(protofile)
    return sketch + "_cc_proto"


def py_grpc_name(protofile):
    (sketch, _) = os.path.splitext(protofile)
    return sketch + "_py_pb2_grpc"


def py_proto_name(protofile):
    (sketch, _) = os.path.splitext(protofile)
    return sketch + "_py_pb2"


def proto_name(protofile):
    (sketch, _) = os.path.splitext(protofile)
    return sketch + "_proto"
```

By this convention,  a proto file named `abc.proto` will have `abc_proto` as its `proto_library` target, `abc_py_pb2` as its `py_proto_library` target, `abc_cc_proto` for its `cc_proto_library` target. If grpc service is involved, `abc_py_pb2_grpc` is for  its `py_grpc_library` target, and `abc_cc_grpc` for its `cc_grpc_library` target.  This is easier to maintain than previously handcrafted targets.

**Comment by rongguodong** [comment]
If it is just name changing for build targets, it sounds no hurt. Do you see this change causing any problems of LGSVL Simulator?
