### ISSUE TITLE
How to use custom maps in Apollo ?

### ISSUE THREAD

**Issue by AMDxb548** [ApolloAuto/apollo#11431]
Hi,
I am trying to use Apollo for Dubai location map. I have downloaded the single lane road map from LSGVL and gave it as input for Apollo but it says default_end_way_points.txt file is missing. How can I use Apollo to test a small region in Dubai ? How can I create the required files in Apollo format, if I use Openstreet maps ? Please help.

**Comment by jinghaomiao** [comment]
Put your own map folder within https://github.com/ApolloAuto/apollo/tree/master/modules/map/data, and make sure that your map follows Apollo map format with the fixed map file names in the folder.

**Comment by Dubai-Technologies** [comment]
Hi @jinghaomiao 
How can I get the apollo map format ? If you have please share the same.

**Comment by jinghaomiao** [comment]
@Dubai-Technologies Apollo map uses proto and the definitions are in https://github.com/ApolloAuto/apollo/tree/master/modules/map/proto

**Comment by sjiang2018** [comment]
Hi @AMDxb548, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
