### ISSUE TITLE
dreamview 不显示地图

### ISSUE THREAD

**Issue by ymhzzz** [ApolloAuto/apollo#11436]
别的功能模块都正常，就是不显示地图，还有我的没有routing模块
![dreamview地图](https://user-images.githubusercontent.com/51348462/84366018-dadd3c00-ac04-11ea-8973-880a7a597a36.png)

**Comment by daohu527** [comment]
Your GPS is invalid and the car cannot be located correctly. Therefore, the map will not be displayed.

**Comment by ymhzzz** [comment]
> Your GPS is invalid and the car cannot be located correctly. Therefore, the map will not be displayed.
![dream](https://user-images.githubusercontent.com/51348462/84452578-c3e02d80-ac88-11ea-8271-f56f210cd31d.png)
但是我在网上看其他人的，虽然右下角会报错，但也会显示地图啊
这是博客地址：https://blog.csdn.net/davidhopper/article/details/85097502#commentBox

**Comment by lh315936716** [comment]
上面mode-navigation 换一个

**Comment by ymhzzz** [comment]
> 上面mode-navigation 换一个

非常感谢！！！加载出了地图  走了一次 但就一次  可能是我电脑太卡了？

**Comment by vlin17** [comment]
hi @ymhzzz, seems like your problem has been resolved. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
