### ISSUE TITLE
The attribute "is_reference_line_updated_" in ReferenceLineProvider can't be recovered to be true once set false

### ISSUE THREAD

**Issue by WeAreTheDark** [ApolloAuto/apollo#11430]
**Describe the bug**
The attribute "is_reference_line_updated_" in ReferenceLineProvider could not be recovered to be true once CreateReferenceLine(&reference_lines, &segments) went wrong, which result in the problem that I had to restart planning whenever something went wrong when running simulation. I am not sure it's intended to be this way or a bug.

**Comment by sjiang2018** [comment]
Hello there. This design is intended. "is_reference_line_updated_" can only be reseted to true when planning module is restarted.  In Apollo, reference line is supposed to be updated at a regular frequency.  When "is_reference_line_updated_" is set to false, it means something unexpected happened. (To be more specific, this value is set to 'false', when ego car location is far from routing and planning module cannot generate reference line based on current routing.)For safety consideration, it is better to quit auto-driving mode and restart everything after the potential issue is resolved.
