### ISSUE TITLE
obstacle perpection use yolov3?

### ISSUE THREAD

**Issue by DaChaoXc** [ApolloAuto/apollo#11441]
when i want to deploy yolov3.prototxt, i read the file  named caffe.pt,  i don't under stand why the head of yolo-3d written like this, code as blew:
layer {
  name: "slice"
  type: "Slice"
  bottom: "conv_final_permute"
  top: "loc_pred"
  top: "obj_perm"
  top: "cls_perm"
  slice_param {
    slice_point: 64
    slice_point: 80
    axis: 3
  }
}
layer {
  name: "**cls_reshape**"
  type: "Reshape"
  bottom: "cls_perm"
  top: "cls_reshape"
  reshape_param {
    shape {
      dim: 0
      dim: 0
      dim: -1
      dim: 4
    }
  }
}
layer {
  name: "**cls_pred_prob**"
  type: "Softmax"
  bottom: "cls_reshape"
  top: "cls_pred_prob"
  softmax_param {
    axis: 3
  }
}
layer {
  name: "**cls_pred**"
  type: "Reshape"
  bottom: "cls_pred_prob"
  top: "cls_pred"
  reshape_param {
    shape {
      dim: 0
      dim: 0cls_reshape
      dim: -1
      dim: 64
    }
  }
}

as i understand, the feature-map dimension of slice layer  is:1x50x90x128, after cls_reshape layer, the feature-map dimension become 1x50x2880x4, than through the Softmax layer, not change feature-map dimension, and then it reshape the feature-map dimension again, become 1x50x180x64.

my question is if the output feature-map dimension of yolov3 is 1x13x13x24, which means 1x13x13x(4+1+3)x3, here 4 means xywh, 1 means obj_cls, 3 means class_type, and 3 anchors, **how should i write the cls_reshape, cls_pred_prob and cls_pred layers?**

code as blew is my implementation， but is seems wrong.
layer {
  name: "slice1"
  type: "Slice"
  bottom: "conv_final_permute1"
  top: "loc_pred1"
  top: "obj_perm1"
  top: "cls_perm1"
  slice_param {
    slice_point: 12
    slice_point: 15
    axis: 3
  }
}
layer {
  name: "cls_reshape1"
  type: "Reshape"
  bottom: "cls_perm1"
  top: "cls_reshape1"
  reshape_param {
    shape {
      dim: 0
      dim: 0
      dim: -1
      dim: 3
    }
  }
}
layer {
  name: "cls_pred_prob1"
  type: "Softmax"
  bottom: "cls_reshape1"
  top: "cls_pred_prob1"
  softmax_param {
    axis: 3
  }
}
layer {
  name: "cls_pred1"
  type: "Reshape"
  bottom: "cls_pred_prob1"
  top: "cls_pred1"
  reshape_param {
    shape {
      dim: 0
      dim: 0
      dim: -1
      dim: 12
    }
  }

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (5.5)**:

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
