### ISSUE TITLE
Apollo Perception  module does not work  properly without DreamView running in the background

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#11440]
Hi, 
We are trying to run stand-alone perception module following the docs :
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md. 

But we observed that the Perception module cannot send messages properly **_without DreamView running in the background._** . 
My question is this : **_Is there a way to make the Perception module run successfully, without running DreamView in the background?_**

Here is the error we receive when we try to run perception without DreamView : 
Command :  cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch
![perception_error](https://user-images.githubusercontent.com/50120641/84386892-68636080-abf2-11ea-8f6c-cab7fa040013.png)

Here is the message received from log file of Perception : 
![perception_data_log](https://user-images.githubusercontent.com/50120641/84387065-b4aea080-abf2-11ea-8897-85a0399c5aa5.png)

### System information
Ubuntu 18.04
Apollo 5.0 

### Steps to reproduce the issue:
1. Start Apollo and bridge by running bootstrap.sh and bridge.sh inside Docker. 
2. Run  cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch inside Docker. 
3.Do NOT open Dreamview in browser.

**Comment by jilinzhou** [comment]
Do you have localization running? For lidar part, the error complains about the missing transforms from world to novatel.

**Comment by Avps1** [comment]
You are right. You need to have localization running. Thank you.
