### ISSUE TITLE
Dependency of the Perception Module on DreamView

### ISSUE THREAD

**Issue by mertmerci** [ApolloAuto/apollo#11454]
I want to run the Perception Module as standalone as it's possible and I want to learn the dependency of this module with DreamView. Is DreamView a must or may I another platform instead of it? 

Thank you in advance.

**Comment by unacao** [comment]
You can run perception module with command line. Dreamview is a standalone visualization tool, not coupled with perception module.

**Comment by vlin17** [comment]
Hi @mertmerci 

Hope the information answered your question. If you have any follow up question, please leave a comment below. If we don't not hear back from you in 72 hours, we will close the issue and we encourage you to open a new issue if you have any more questions. 

Thank you for supporting Apollo!
