### ISSUE TITLE
Latest Apollo master does not work

### ISSUE THREAD

**Issue by rongguodong** [ApolloAuto/apollo#11457]
**Describe the bug**
I pulled latest Apollo master today, and build it successfully. But when I run bootstrap.sh or use cyber_launch to launch modules, it complained "mainboard" cannot be found.

**To Reproduce**
1. Clone or pull latest master
2. Enter Apollo docker (via dev_start and dev_into)
3. Run apollo.sh build_opt_gpu
4. Run bootstrap.sh or use cyber_launch to launch any module

**Expected behavior**
Both bootstrap script and module launch should work fine.

More details can be found at: https://github.com/lgsvl/simulator/issues/804

**Comment by lemketron** [comment]
I think the problem may be in this [change](https://github.com/ApolloAuto/apollo/commit/248df0e89d83c4d41308221895856def81ac8d25#diff-02c58c0f5b8de7c08afa911baca04986L3) to setup.bash

**Comment by lemketron** [comment]
This change fixes the problem in master by adding bazel-bin/cyber back into the PATH:
```
diff --git a/cyber/setup.bash b/cyber/setup.bash
index b13485d13d..e6b13662dd 100755
--- a/cyber/setup.bash
+++ b/cyber/setup.bash
@@ -15,6 +15,7 @@ bazel_bin_path="${APOLLO_ROOT_DIR}/bazel-bin"
apollo_tool_path="${bazel_bin_path}/modules/tools"
visualizer_path="${apollo_tool_path}/visualizer"

+cyber_bin_path="${bazel_bin_path}/cyber"
cyber_tool_path="${bazel_bin_path}/cyber/tools"
recorder_path="${cyber_tool_path}/cyber_recorder"
monitor_path="${cyber_tool_path}/cyber_monitor"
@@ -27,7 +28,7 @@ rosbag_to_record_path="${bazel_bin_path}/modules/data/tools/rosbag_to_record"


# TODO(all): place all these in one place and add_to_path
-for entry in "${recorder_path}" "${monitor_path}" "${launch_path}" \
+for entry in "${cyber_bin_path}" "${recorder_path}" "${monitor_path}" "${launch_path}" \
"${channel_path}" "${node_path}" "${service_path}" \
"${visualizer_path}" \
"${rosbag_to_record_path}" ; do
```
