### ISSUE TITLE
Apollo sensor calibration

### ISSUE THREAD

**Issue by singhgridecell** [ApolloAuto/apollo#11451]
Does Baidu offer Apollo extrinsic calibration service for camera-lidar, lidar-lidar and camera-radar calibration? 
There are some directions for calibration here - https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md. Are the tools referred to here maintained actively? We had some issues using the calibration executables referred to in this document.

**Comment by jinghaomiao** [comment]
The tool only works in Apollo 2.0 and won't work in later releases of Apollo. Thanks for your interests in Apollo.
