### ISSUE TITLE
lidar_perception can't work in 5.0.0

### ISSUE THREAD

**Issue by cxr1996** [ApolloAuto/apollo#11469]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution ( Ubuntu 14.04):
- **Apollo installed from (source):
- **Apollo version (5.0)*

### Steps to reproduce the issue:
when I use cyber_launch start /apollo/modules/perception/production/launch/perception.launch to run perception model,The following problems arise， i use VLP-16 and Leopard camera.
![123123123](https://user-images.githubusercontent.com/56950044/84750660-29684d00-afee-11ea-9f3c-54e07b80c585.png)

**Comment by panfengsu** [comment]
you need to ensure LidarObstacleSegmentation model_configs is in /apollo/modules/perception/production/conf/perception/lidar/modules/lidar_obstacle_pipeline.config

**Comment by cxr1996** [comment]
> you need to ensure LidarObstacleSegmentation model_configs is in /apollo/modules/perception/production/conf/perception/lidar/modules/lidar_obstacle_pipeline.config

thanks you are right ，I modified the DAG file earlier
