### ISSUE TITLE
dreamview not show maps and vehicles

### ISSUE THREAD

**Issue by GuoliangPeng** [ApolloAuto/apollo#11466]
### System information

- **OS Platform and Distribution  Linux Ubuntu 18.04)**
- **Apollo installed from git clone**
- **Apollo version 5.5**

### Steps to reproduce the issue:
Every time I open dreamiew, the map and vehicle display are missing。
run shell show
![4](https://user-images.githubusercontent.com/7499423/84721389-269c3680-afb3-11ea-9f1f-151bbab96489.png)

after run script/bootstrap, open dreamview not have map show
![1](https://user-images.githubusercontent.com/7499423/84721455-492e4f80-afb3-11ea-85be-d74fdb1b0c85.png)

after run  `cyber_recorder play -f docs/demo_guide/demo_3.5.record -l`,
There is no map or vehicle display in dreamview. Data is changing, looks normal。
![2](https://user-images.githubusercontent.com/7499423/84720998-2c454c80-afb2-11ea-98db-4a0f37d9ba0f.png)

In modules/dreamview/conf, I have navigation_mode_default_end_way_point.txt
![5](https://user-images.githubusercontent.com/7499423/84721242-cc02da80-afb2-11ea-9834-3a68ed750989.png)

**Comment by unacao** [comment]
you are in navigation mode, please use the dropdown list to select "Mkz Standard Debug" mode

**Comment by GuoliangPeng** [comment]
i did try,but still errors
![7](https://user-images.githubusercontent.com/7499423/84968230-97c12280-b148-11ea-991c-7496bd7781ee.png)
![6](https://user-images.githubusercontent.com/7499423/84968255-a3ace480-b148-11ea-9514-d2e871f66179.png)
I am ready to try the latest code from the clone clone, but it is difficult to download in China

**Comment by unacao** [comment]
Can you screenshot how your Layer Menu look like?

**Comment by GuoliangPeng** [comment]
![8](https://user-images.githubusercontent.com/7499423/84986531-4aa57680-b171-11ea-919a-28ad1275d1ce.png)

**Comment by vlin17** [comment]
1. May we know which browser you are using?
2. Can you open browser console to see if there's any error messages (Control+Shift+J for Chrome on Linux system) ?
3. Can you visit this [website](https://webglreport.com/) and see if your computer has the support for both WebGL 1 and WebGL 2?

**Comment by GuoliangPeng** [comment]
i use Google Chrome（version: 77.0.3865.120).
browser console show errors：
![10](https://user-images.githubusercontent.com/7499423/85084145-8a6a6d80-b206-11ea-83bb-2f5a94d4e3c5.png)
![11](https://user-images.githubusercontent.com/7499423/85084159-99512000-b206-11ea-8513-80d65d3d6cc3.png)
I think my browser supports WebGL 1 and 2
![image](https://user-images.githubusercontent.com/7499423/85084318-06fd4c00-b207-11ea-8387-dcdec3a340a4.png)
I think there are problems with the project related resources, some errors

**Comment by GuoliangPeng** [comment]
Today, I pulled the project from the repos again and it is running normally. The dreamview   show correctly
