### ISSUE TITLE
Can not build PCL in apollo docker

### ISSUE THREAD

**Issue by AlexKaravaev** [ApolloAuto/apollo#11461]
I have a pc, that apparently does not support FMA/FMA3 instructuions, hence I can not launch dreamview(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md). 

#9081 Suggests to build new pcl library, but I just can not not build it, because cmake can not find boost libraries. Below the error of cmake.
```
Could not find the following Boost libraries:

          boost_system
          boost_filesystem
          boost_thread
```

In #9081 somebody proposed to update cmake from 2.7, but this distrtibution of appollo is having cmake 3.10, which seems to me okay. Anyways, updating to newer cmake did not help too.

- Host system - Ubuntu 20.04 LTS
- Apollo Version 5.0

**Comment by storypku** [comment]
> I have a pc, that apparently does not support FMA/FMA3 instructuions, hence I can not launch dreamview(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md).
> 
> #9081 Suggests to build new pcl library, but I just can not not build it, because cmake can not find boost libraries. Below the error of cmake.
> 
> ```
> Could not find the following Boost libraries:
> 
>           boost_system
>           boost_filesystem
>           boost_thread
> ```
> 
> In #9081 somebody proposed to update cmake from 2.7, but this distrtibution of appollo is having cmake 3.10, which seems to me okay. Anyways, updating to newer cmake did not help too.
> 
> * Host system - Ubuntu 20.04 LTS
> * Apollo Version 5.0

So, the branch used is r5.0.0 ?

**Comment by storypku** [comment]
> I have a pc, that apparently does not support FMA/FMA3 instructuions, hence I can not launch dreamview(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md).
> 
> #9081 Suggests to build new pcl library, but I just can not not build it, because cmake can not find boost libraries. Below the error of cmake.
> 
> ```
> Could not find the following Boost libraries:
> 
>           boost_system
>           boost_filesystem
>           boost_thread
> ```
> 
> In #9081 somebody proposed to update cmake from 2.7, but this distrtibution of appollo is having cmake 3.10, which seems to me okay. Anyways, updating to newer cmake did not help too.
> 
> * Host system - Ubuntu 20.04 LTS
> * Apollo Version 5.0

Tested on the r5.0.0 branch,  pcl 1.7.2 can successfully be built.  The Boost library used is 1.54, installed via `sudo apt-get -y install libboost-all-dev`.

**Comment by storypku** [comment]
This issue is going to be closed now. 
If you have other questions, please feel free to create another issue, or just reopen this one if related. 
Thanks for using Apollo!
