### ISSUE TITLE
About CyberRT

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#11476]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Could you currently set up 2 projects in a non-Docker environment to communicate via cyberRT? Could you plz give me a  simplest example for this request?
Thanks！

**Comment by storypku** [comment]
Just follow the steps how a cyber docker image is built, and you can setup CyberRT environment without docker.  The `docker_dev` branch currently maintains full-blown CyberRT docker image support. See https://github.com/ApolloAuto/apollo/tree/docker_dev/docker/build 

CyberRT examples can be found in the `cyber/examples` directory.

**Comment by Eclipsehelio** [comment]
@yumianhuli2 If you are running  in a distributed environment, remember to export `CYBER_IP` environment variable to their respective IP addresses.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
