### ISSUE TITLE
About dockerfile

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#11470]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hello！Where is the dockerfile？Thank you！

**Comment by daohu527** [comment]
## dockerfile
apollo\docker\build\dev.x86_64.dockerfile

## build
[docker](https://github.com/ApolloAuto/apollo/blob/d494f79026817231db5e85c77461be92fe415706/docker/build/README.md)

**Comment by yumianhuli2** [comment]
> ## dockerfile
> apollo\docker\build\dev.x86_64.dockerfile
> 
> ## build
> Here is a doc about build docker [here](https://github.com/ApolloAuto/apollo/blob/d494f79026817231db5e85c77461be92fe415706/docker/build/README.md)

very nice！Thank you！
