### ISSUE TITLE
ndt_lidar_locator_test failed (Exit 4)

### ISSUE THREAD

**Issue by machar94** [ApolloAuto/apollo#11473]
### System information
Host: Windows 10
VM: Ubuntu 18.04 LTS
Apollo Version: 5.5

### Steps to reproduce
Trying to build apollo using VS Code. After running `ctrl + shift + b` I run into the following issue with the ndt localization test failing to compile. Exact error is below:
```
ERROR: (06-16 18:45:16.860) /apollo/modules/localization/ndt/ndt_locator/BUILD:38:1: C++ compilation of rule '//modules/localization/ndt/ndt_locator:ndt_lidar_locator_test' failed (Exit 4).
gcc: internal compiler error: Killed (program cc1plus)
```

### Supporting materials
![ndt_lidar_locator_test_failed](https://user-images.githubusercontent.com/4420650/84815163-a096e480-afe0-11ea-899a-4d9ad061bb13.png)

Any ideas as to the fix? Could it be possible that I need to upgrade my compiler? I am saying that as I see the gcc error.

**Comment by daohu527** [comment]
## suggestion
This maybe **your memory is lack**, If you are running on a virtual machine, you can try to increase the memory to **8G or more**.

**Comment by machar94** [comment]
Cannot confirm if that was the issue, but was able to change my dev environment to an Ubuntu 18.04 machine which has 32GB and I was able to build successfully.
