### ISSUE TITLE
Error in GridSearch::CheckConstraints

### ISSUE THREAD

**Issue by zerolover** [ApolloAuto/apollo#11487]
In function `GridSearch::CheckConstraints`, it checked a grid for collisions by distance to line:

https://github.com/ApolloAuto/apollo/blob/482e68bbe1dcb9ef7a42ab8d6684b9681866d535/modules/planning/open_space/coarse_trajectory_generator/grid_search.cc#L50

However the `Vec2d(node->GetGridX(), node->GetGridY())` is the coordinates of a node in grid map, which is mismatched with the units of the linesegment.

**Comment by JasonZhou404** [comment]
Nice catch! Related PR is at  #11524 .Thanks!

**Comment by sjiang2018** [comment]
Hi @zerolover, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
