### ISSUE TITLE
msf_simple_map_creator failed

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11483]
Hello

### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.5.0)**:

Then I run in docker
bash ./scripts/msf_simple_map_creator.sh ./map/records/ ./modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml 10 ./map/

I see this

root@in_dev_docker:/apollo# bash ./scripts/msf_simple_map_creator.sh ./map/records/ ./modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml 10 ./map/
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:46.645824 14222 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:46.646661 14222 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:46.646744 14222 pcd_exporter.cc:44] []Compensated pcd callback.
./scripts/msf_simple_map_creator.sh: line 31: 14222 Segmentation fault      (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/data_extraction/cyber_record_parser --bag_file $BAG_FILE --out_folder $OUT_FOLDER --cloud_topic $CLOUD_TOPIC --gnss_loc_topic $GNSS_LOC_TOPIC --lidar_loc_topic $LIDAR_LOC_TOPIC --fusion_loc_topic $FUSION_LOC_TOPIC --odometry_loc_topic $ODOMETRY_LOC_TOPIC
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
./scripts/msf_simple_map_creator.sh: line 44: 14223 Aborted                 (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/map_creation/poses_interpolator --input_poses_path $INPUT_POSES_PATH --ref_timestamps_path $REF_TIMESTAMPS_PATH --extrinsic_path $EXTRINSIC_PATH --output_poses_path $OUTPUT_POSES_PATH
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:47.755048 14224 lossless_map_creator.cc:164] []Pcd folders are as follows:
I0617 09:39:47.755574 14224 lossless_map_creator.cc:166] []./map//parsed_data/00000/pcd
E0617 09:39:47.755616 14224 velodyne_utility.cc:125] []Can't open file to read: ./map//parsed_data/00000/pcd/corrected_poses.txt
I0617 09:39:47.756280 14224 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:47.756561 14224 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:47.959331 14224 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:48.556890 14243 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:48.557173 14243 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:48.559199 14243 pcd_exporter.cc:44] []Compensated pcd callback.
./scripts/msf_simple_map_creator.sh: line 31: 14243 Segmentation fault      (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/data_extraction/cyber_record_parser --bag_file $BAG_FILE --out_folder $OUT_FOLDER --cloud_topic $CLOUD_TOPIC --gnss_loc_topic $GNSS_LOC_TOPIC --lidar_loc_topic $LIDAR_LOC_TOPIC --fusion_loc_topic $FUSION_LOC_TOPIC --odometry_loc_topic $ODOMETRY_LOC_TOPIC
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
./scripts/msf_simple_map_creator.sh: line 44: 14244 Aborted                 (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/map_creation/poses_interpolator --input_poses_path $INPUT_POSES_PATH --ref_timestamps_path $REF_TIMESTAMPS_PATH --extrinsic_path $EXTRINSIC_PATH --output_poses_path $OUTPUT_POSES_PATH
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:49.698890 14245 lossless_map_creator.cc:164] []Pcd folders are as follows:
I0617 09:39:49.699396 14245 lossless_map_creator.cc:166] []./map//parsed_data/00001/pcd
E0617 09:39:49.699437 14245 velodyne_utility.cc:125] []Can't open file to read: ./map//parsed_data/00001/pcd/corrected_poses.txt
I0617 09:39:49.699983 14245 base_map_config.cc:161] []Resolution: 0.125
I0617 09:39:49.700011 14245 base_map_config.cc:171] []Dataset: ./map//parsed_data/00000/pcd
I0617 09:39:49.700048 14245 base_map_config.cc:60] []Loaded the map configuration from: ./map//lossless_map/config.xml
I0617 09:39:49.700541 14245 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:49.700801 14245 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:49.907696 14245 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:50.516916 14266 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:50.517745 14266 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:50.517761 14266 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:50.517772 14266 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:50.517803 14266 location_exporter.cc:168] []Odometry location callback.
I0617 09:39:50.518045 14266 pcd_exporter.cc:44] []Compensated pcd callback.
./scripts/msf_simple_map_creator.sh: line 31: 14266 Segmentation fault      (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/data_extraction/cyber_record_parser --bag_file $BAG_FILE --out_folder $OUT_FOLDER --cloud_topic $CLOUD_TOPIC --gnss_loc_topic $GNSS_LOC_TOPIC --lidar_loc_topic $LIDAR_LOC_TOPIC --fusion_loc_topic $FUSION_LOC_TOPIC --odometry_loc_topic $ODOMETRY_LOC_TOPIC
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
./scripts/msf_simple_map_creator.sh: line 44: 14267 Aborted                 (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/map_creation/poses_interpolator --input_poses_path $INPUT_POSES_PATH --ref_timestamps_path $REF_TIMESTAMPS_PATH --extrinsic_path $EXTRINSIC_PATH --output_poses_path $OUTPUT_POSES_PATH
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:51.655009 14268 lossless_map_creator.cc:164] []Pcd folders are as follows:
I0617 09:39:51.655308 14268 lossless_map_creator.cc:166] []./map//parsed_data/00002/pcd
E0617 09:39:51.655340 14268 velodyne_utility.cc:125] []Can't open file to read: ./map//parsed_data/00002/pcd/corrected_poses.txt
I0617 09:39:51.655617 14268 base_map_config.cc:161] []Resolution: 0.125
I0617 09:39:51.655627 14268 base_map_config.cc:171] []Dataset: ./map//parsed_data/00000/pcd
I0617 09:39:51.655633 14268 base_map_config.cc:171] []Dataset: ./map//parsed_data/00001/pcd
I0617 09:39:51.655658 14268 base_map_config.cc:60] []Loaded the map configuration from: ./map//lossless_map/config.xml
I0617 09:39:51.655905 14268 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:51.663697 14268 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:51.853826 14268 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:52.470712 14287 pcd_exporter.cc:44] []Compensated pcd callback.
./scripts/msf_simple_map_creator.sh: line 31: 14287 Segmentation fault      (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/data_extraction/cyber_record_parser --bag_file $BAG_FILE --out_folder $OUT_FOLDER --cloud_topic $CLOUD_TOPIC --gnss_loc_topic $GNSS_LOC_TOPIC --lidar_loc_topic $LIDAR_LOC_TOPIC --fusion_loc_topic $FUSION_LOC_TOPIC --odometry_loc_topic $ODOMETRY_LOC_TOPIC
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
./scripts/msf_simple_map_creator.sh: line 44: 14288 Aborted                 (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/map_creation/poses_interpolator --input_poses_path $INPUT_POSES_PATH --ref_timestamps_path $REF_TIMESTAMPS_PATH --extrinsic_path $EXTRINSIC_PATH --output_poses_path $OUTPUT_POSES_PATH
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:53.497004 14289 lossless_map_creator.cc:164] []Pcd folders are as follows:
I0617 09:39:53.497714 14289 lossless_map_creator.cc:166] []./map//parsed_data/00003/pcd
E0617 09:39:53.497879 14289 velodyne_utility.cc:125] []Can't open file to read: ./map//parsed_data/00003/pcd/corrected_poses.txt
I0617 09:39:53.498436 14289 base_map_config.cc:161] []Resolution: 0.125
I0617 09:39:53.498590 14289 base_map_config.cc:171] []Dataset: ./map//parsed_data/00000/pcd
I0617 09:39:53.498731 14289 base_map_config.cc:171] []Dataset: ./map//parsed_data/00001/pcd
I0617 09:39:53.498867 14289 base_map_config.cc:171] []Dataset: ./map//parsed_data/00002/pcd
I0617 09:39:53.499033 14289 base_map_config.cc:60] []Loaded the map configuration from: ./map//lossless_map/config.xml
I0617 09:39:53.499439 14289 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:53.499760 14289 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
I0617 09:39:53.689774 14289 base_map_config.cc:48] []Saved the map configuration to: ./map//lossless_map/config.xml
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0617 09:39:54.079902 14301 base_map_config.cc:161] []Resolution: 0.125
I0617 09:39:54.080163 14301 base_map_config.cc:171] []Dataset: ./map//parsed_data/00000/pcd
I0617 09:39:54.080170 14301 base_map_config.cc:171] []Dataset: ./map//parsed_data/00001/pcd
I0617 09:39:54.080193 14301 base_map_config.cc:171] []Dataset: ./map//parsed_data/00002/pcd
I0617 09:39:54.080197 14301 base_map_config.cc:171] []Dataset: ./map//parsed_data/00003/pcd
I0617 09:39:54.080233 14301 base_map_config.cc:60] []Loaded the map configuration from: ./map//lossless_map//config.xml
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: No such file or directory: "./map//lossless_map//map"
./scripts/msf_simple_map_creator.sh: line 67: 14301 Aborted                 (core dumped) /apollo/bazel-bin/modules/localization/msf/local_tool/map_creation/lossless_map_to_lossy_map --srcdir $OUT_MAP_FOLDER/lossless_map --dstdir $OUT_MAP_FOLDER
mv: cannot move './map//lossy_map' to './map//local_map/lossy_map': Directory not empty
Done.

**Comment by alexbuyval** [comment]
It seems that the script cannot open the record file.
```
terminate called after throwing an instance of 'YAML::BadFile'
what(): bad file
```
Check your record file by cyber_record info or play

**Comment by AlexandrZabolotny** [comment]
> It seems that the script cannot open the record file.
> 
> ```
> terminate called after throwing an instance of 'YAML::BadFile'
> what(): bad file
> ```
> 
> Check your record file by cyber_record info or play

**cyber_record info**

record_file:    /apollo/map/record/20200701220844.record.00000
version:        1.0
duration:       60.003381 Seconds
begin_time:     2020-07-01 22:08:44
end_time:       2020-07-01 22:09:44
size:           111692002 Bytes (106.517792 MB)
is_complete:    true
message_number: 14594
channel_number: 22
channel_info:   
                /apollo/sensor/camera/front_6mm/image                    0 messages: apollo.drivers.Image
                /apollo/sensor/camera/front_12mm/image                   0 messages: apollo.drivers.Image
                /apollo/sensor/camera/left_fisheye/image                 0 messages: apollo.drivers.Image
                /apollo/sensor/camera/right_fisheye/image                0 messages: apollo.drivers.Image
                /apollo/sensor/camera/rear_6mm/image                     0 messages: apollo.drivers.Image
                /apollo/sensor/gnss/best_pose                          750 messages: apollo.drivers.gnss.GnssBestPose
                /apollo/sensor/gnss/odometry                           750 messages: apollo.localization.Gps
                /apollo/sensor/gnss/ins_stat                           710 messages: apollo.drivers.gnss.InsStat
                /apollo/sensor/gnss/imu                               5815 messages: apollo.drivers.gnss.Imu
                /apollo/sensor/gnss/corrected_imu                     5814 messages: apollo.localization.CorrectedImu
                /apollo/sensor/lidar128/compensator/PointCloud2        599 messages: apollo.drivers.PointCloud
                /apollo/monitor                                         48 messages: apollo.common.monitor.MonitorMessage
                /apollo/monitor/system_status                           48 messages: apollo.monitor.SystemStatus
                /apollo/localization/pose                                0 messages: apollo.localization.LocalizationEstimate
                /apollo/canbus/chassis                                   0 messages: apollo.canbus.Chassis
                /apollo/prediction                                       0 messages: apollo.prediction.PredictionObstacles
                /apollo/navigation                                       0 messages: apollo.relative_map.NavigationInfo
                /apollo/routing_request                                  0 messages: apollo.routing.RoutingRequest
                /apollo/routing_response                                 0 messages: apollo.routing.RoutingResponse
                /apollo/hmi/status                                      60 messages: apollo.dreamview.HMIStatus
                /apollo/control/pad                                      0 messages: apollo.control.PadMessage
                /apollo/drive_event                                      0 messages: apollo.common.DriveEvent

**Comment by AlexandrZabolotny** [comment]
@alexbuyval, I apologize for my perseverance
But could you explain what these topics mean?

in msf_simple_map_creator.sh

12. GNSS_LOC_TOPIC="/apollo/localization/msf_gnss"
13. LIDAR_LOC_TOPIC="/apollo/localization/msf_lidar"
14. FUSION_LOC_TOPIC="/apollo/localization/pose"
15. ODOMETRY_LOC_TOPIC="/apollo/sensor/gnss/odometry"

Should these channel be contained in the record file?

**Comment by alexbuyval** [comment]
@AlexandrZabolotny 
I am not sure, but I think it topics from different source of localization.
As I remember it is enough the "/apollo/localization/pose" topic

**Comment by AlexandrZabolotny** [comment]
The solution to this problem

https://github.com/ApolloAuto/apollo/issues/11936
