### ISSUE TITLE
bazel .cc failed!

### ISSUE THREAD

**Issue by markofan** [ApolloAuto/apollo#11485]
when I run this code, 
sudo bazel run //modules/perception/camera/tools/offline:offline_obstacle_pipeline
something went wrong！how to solve this problem?
ERROR: (06-17 09:03:17.729) /apollo/modules/perception/camera/tools/offline/BUILD:40:1: Linking of rule '//modules/perception/camera/tools/offline:offline_obstacle_pipeline' failed (Exit 1).
/usr/bin/ld: warning: libmkldnn.so.0, needed by bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so, not found (try using -rpath or -rpath-link)
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_post_ops_append_eltwise'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_get_primitive_desc'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_lrn_forward_desc_init'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_attr_destroy'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_post_ops_destroy'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_attr_set_post_ops'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_eltwise_forward_desc_init'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_destroy'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_softmax_forward_desc_init'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_create'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_desc_clone'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_deconvolution_forward_desc_init'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_stream_wait'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_memory_primitive_desc_equal'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_desc_query_memory_d'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_pooling_backward_desc_init'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_engine_destroy'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_memory_desc_init'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_memory_set_data_handle'
bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_at'

**Comment by storypku** [comment]
> when I run this code,
> sudo bazel run //modules/perception/camera/tools/offline:offline_obstacle_pipeline
> something went wrong！how to solve this problem?
> ERROR: (06-17 09:03:17.729) /apollo/modules/perception/camera/tools/offline/BUILD:40:1: Linking of rule '//modules/perception/camera/tools/offline:offline_obstacle_pipeline' failed (Exit 1).
> /usr/bin/ld: warning: libmkldnn.so.0, needed by bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so, not found (try using -rpath or -rpath-link)
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_post_ops_append_eltwise' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_get_primitive_desc'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_lrn_forward_desc_init' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_attr_destroy'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_post_ops_destroy' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_attr_set_post_ops'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_eltwise_forward_desc_init' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_destroy'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_softmax_forward_desc_init' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_create'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_desc_clone' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_deconvolution_forward_desc_init'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_stream_wait' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_memory_primitive_desc_equal'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_desc_query_memory_d' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_pooling_backward_desc_init'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_engine_destroy' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_memory_desc_init'
> bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_memory_set_data_handle' bazel-out/local-fastbuild/bin/_solib_k8/_U@paddlepaddle_S_S_Cpaddlepaddle___Uexternal_Spaddlepaddle_Slib/libpaddle_fluid.so: undefined reference to `mkldnn_primitive_at'

Which branch are you running this build on ?

**Comment by markofan** [comment]
just in the docker /apollo folder
username@in_dev_docker:/apollo$ sudo bazel test //modules/perception/camera/tools/offline:offline_obstacle_pipeline
I haven't installed paddle yet, maybe this is the reason that bazel failed?

**Comment by storypku** [comment]
> e
> I haven't installed paddle yet, maybe this is the reason that bazel failed?

paddle was not installed, it was a volume mounted when running `dev_start.sh`. 
Again, can you plz tell me the git branch you are currently on?

**Comment by markofan** [comment]
> > I haven't installed paddle yet, maybe this is the reason that bazel failed?
> 
> paddle was not installed, it was a volume mounted when running `dev_start.sh`.
> Again, can you plz tell me the git branch you are currently on?

Sorry, I don't know how to find out the "git branch"
Can you help me? Thanks a lot!

**Comment by lx18233184051** [comment]
please use git status in your apollo project. it will tell you which branch you are on.

**Comment by storypku** [comment]
> > > I haven't installed paddle yet, maybe this is the reason that bazel failed?
> > 
> > 
> > paddle was not installed, it was a volume mounted when running `dev_start.sh`.
> > Again, can you plz tell me the git branch you are currently on?
> 
> Sorry, I don't know how to find out the "git branch"
> Can you help me? Thanks a lot!
> 
> I have used this command "git rev-parse --abbrev-ref HEAD"
> But get this error:
> fatal: not a git repository (or any parent up to mount point /)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Maybe you are using a release version ?  Do you have any ideas, Xiangquan @xiaoxq ?

**Comment by markofan** [comment]
Also, I don't have a GPU in my computer, maybe this is the reason? 
Can I run the test file without a GPU?

**Comment by markofan** [comment]
When I use "git status" in the docker terminal like this:
root@in_dev_docker:/apollo$ git status
========================
It also give me this result:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by michael4338** [comment]
you need to run most git commands out of the docker and right under the correct git folder

**Comment by xiaoxq** [comment]
Close as of now. Feel free to reopen if you still have problem with it.
