### ISSUE TITLE
P is not upper triangular matrix

### ISSUE THREAD

**Issue by HubFire** [ApolloAuto/apollo#11484]
https://github.com/ApolloAuto/apollo/blob/482e68bbe1dcb9ef7a42ab8d6684b9681866d535/modules/planning/math/piecewise_jerk/piecewise_jerk_speed_problem.cc#L101

**Comment by HubFire** [comment]
When I  chang this  line to:
`
        columns[2 * n + i + 1].emplace_back(2 * n + i, -2.0 * jerk_weight / delta_s_square /
                                                (scale_factor_[2] * scale_factor_[2]));
`
The OSQP  solver will be non-convex。
I  use  default  config：
`
message PiecewiseJerkSpeedConfig {
  optional double acc_weight = 1 [default = 1.0];
  optional double jerk_weight = 2 [default = 10.0];
  optional double kappa_penalty_weight = 3 [default = 1000.0];
  optional double ref_s_weight = 4 [default = 10.0];
  optional double ref_v_weight = 5 [default = 10.0];
}
`

**Comment by JasonZhou404** [comment]
What is your exact concern and issue? Current implementation seems fine

**Comment by HubFire** [comment]
When  I run Apollo  piece_wise_jerk_speed_smooth code, I got a error "P is not upper triangular matrix"。And after  I changed  the row and  column of Kernel matrix，I  got  another error "The OSQP solver will be non-convex "。
It may be caused by version difference of OSQP，I use  0.6.0

**Comment by HubFire** [comment]
I Change  OSQP to 0.4.1，the  "P is not upper triangular matrix"  error  disappear，but i  got  another  error “failed optimization status:   primal infeasible”

**Comment by storypku** [comment]
> When I run Apollo piece_wise_jerk_speed_smooth code, I got a error "P is not upper triangular matrix"。And after I changed the row and column of Kernel matrix，I got another error "The OSQP solver will be non-convex "。
> It may be caused by version difference of OSQP，I use 0.6.0

As described in osqp 0.6.0 changelog,

```
- ... Changed syntax of osqp_setup function. It now returns an exitflag.
- osqp_setup function requires P to be upper triangular. It returns a nonzero exitflag otherwise.

```

RTFM: https://github.com/oxfordcontrol/osqp/releases/tag/v0.6.0

**Comment by jmtao** [comment]
Hi @HubFire , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
