### ISSUE TITLE
Which are the open source modules

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11490]
Hello

**Which are the open source modules?**
**And which modules are proprietary?**

**Comment by storypku** [comment]
> Hello
> 
> **Which are the open source modules?**
> **And which modules are proprietary?**

The who Apollo project is open source under the Apache 2.0 License. Third-party modules (e.g. `esdcan`) may have their own license, whether it be open source or proprietary.
