### ISSUE TITLE
What to modify for GNSS receiver Ethernet connection?

### ISSUE THREAD

**Issue by uidj1438** [ApolloAuto/apollo#11494]
Hello,

I already have Apollo running successfully with the recommended system design, and the Novatel GNSS+IMU connected via USB to the PC.  If I want to use an Ethernet connection instead of USB, which files do I need to modify and how?  I have tried changing only the physical connection from USB to Ethernet and launching Apollo, but this results in no GNSS data in cyber monitor.

Thank you.

**Comment by jinghaomiao** [comment]
You might have to modify the driver to read data from ethernet port instead of USB. GNSS driver is here: https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/gnss

Please feel free to reopen the issue if you have other questions. Thanks for using Apollo.
