### ISSUE TITLE
error install pcl in docker

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11508]
Hello

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version (5.5.0)**:

When I run in docker
bash ./docker/build/installers/install_pcl.sh 

I see this error

CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_filesystem
          boost_thread
          boost_system

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  cmake/pcl_find_boost.cmake:44 (find_package)
  CMakeLists.txt:421 (include)

**Comment by unacao** [comment]
did you try the solution in #11461 ?

**Comment by AlexandrZabolotny** [comment]
> did you try the solution in #11461 ?

When I run `sudo apt-get -y install libboost-all-dev`  

I see

![Screenshot from 2020-06-22 11-17-55](https://user-images.githubusercontent.com/61351599/85264878-0ddfc500-b47a-11ea-814b-28a6518cdc2d.png)

**Comment by storypku** [comment]
> > did you try the solution in #11461 ?
> 
> When I run `sudo apt-get -y install libboost-all-dev`
> 
> I see
> 
> ![Screenshot from 2020-06-22 11-17-55](https://user-images.githubusercontent.com/61351599/85264878-0ddfc500-b47a-11ea-814b-28a6518cdc2d.png)

What's the output of `dpkg -l |grep boost` ?

**Comment by AlexandrZabolotny** [comment]
> > > did you try the solution in #11461 ?
> > 
> > 
> > When I run `sudo apt-get -y install libboost-all-dev`
> > I see
> > ![Screenshot from 2020-06-22 11-17-55](https://user-images.githubusercontent.com/61351599/85264878-0ddfc500-b47a-11ea-814b-28a6518cdc2d.png)
> 
> What's the output of `dpkg -l |grep boost` ?

ii  libboost-all-dev                       1.65.1.0ubuntu1                    amd64        Boost C++ Libraries development files (ALL) (default version)
ii  libboost-atomic-dev:amd64              1.65.1.0ubuntu1                    amd64        atomic data types, operations, and memory ordering constraints (default version)
ii  libboost-atomic1.65-dev:amd64          1.65.1+dfsg-0ubuntu5               amd64        atomic data types, operations, and memory ordering constraints
ii  libboost-atomic1.65.1:amd64            1.65.1+dfsg-0ubuntu5               amd64        atomic data types, operations, and memory ordering constraints
ii  libboost-chrono-dev:amd64              1.65.1.0ubuntu1                    amd64        C++ representation of time duration, time point, and clocks (default version)
ii  libboost-chrono1.65-dev:amd64          1.65.1+dfsg-0ubuntu5               amd64        C++ representation of time duration, time point, and clocks
ii  libboost-chrono1.65.1:amd64            1.65.1+dfsg-0ubuntu5               amd64        C++ representation of time duration, time point, and clocks
ii  libboost-container-dev:amd64           1.65.1.0ubuntu1                    amd64        C++ library that implements several well-known containers - dev files (default version)
ii  libboost-container1.65-dev:amd64       1.65.1+dfsg-0ubuntu5               amd64        C++ library that implements several well-known containers - dev files
ii  libboost-container1.65.1:amd64         1.65.1+dfsg-0ubuntu5               amd64        C++ library that implements several well-known containers
ii  libboost-context-dev:amd64             1.65.1.0ubuntu1                    amd64        provides a sort of cooperative multitasking on a single thread (default version)
ii  libboost-context1.65-dev:amd64         1.65.1+dfsg-0ubuntu5               amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-context1.65.1:amd64           1.65.1+dfsg-0ubuntu5               amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-coroutine-dev:amd64           1.65.1.0ubuntu1                    amd64        provides a sort of cooperative multitasking on a single thread (default version)
ii  libboost-coroutine1.65-dev:amd64       1.65.1+dfsg-0ubuntu5               amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-coroutine1.65.1:amd64         1.65.1+dfsg-0ubuntu5               amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-date-time-dev:amd64           1.65.1.0ubuntu1                    amd64        set of date-time libraries based on generic programming concepts (default version)
ii  libboost-date-time1.65-dev:amd64       1.65.1+dfsg-0ubuntu5               amd64        set of date-time libraries based on generic programming concepts
ii  libboost-date-time1.65.1:amd64         1.65.1+dfsg-0ubuntu5               amd64        set of date-time libraries based on generic programming concepts
ii  libboost-dev:amd64                     1.65.1.0ubuntu1                    amd64        Boost C++ Libraries development files (default version)
ii  libboost-exception-dev:amd64           1.65.1.0ubuntu1                    amd64        library to help write exceptions and handlers (default version)
ii  libboost-exception1.65-dev:amd64       1.65.1+dfsg-0ubuntu5               amd64        library to help write exceptions and handlers
ii  libboost-fiber-dev:amd64               1.65.1.0ubuntu1                    amd64        cooperatively-scheduled micro-/userland-threads (default version)
ii  libboost-fiber1.65-dev:amd64           1.65.1+dfsg-0ubuntu5               amd64        cooperatively-scheduled micro-/userland-threads
ii  libboost-fiber1.65.1:amd64             1.65.1+dfsg-0ubuntu5               amd64        cooperatively-scheduled micro-/userland-threads
ii  libboost-filesystem-dev:amd64          1.65.1.0ubuntu1                    amd64        filesystem operations (portable paths, iteration over directories, etc) in C++ (default version)
ii  libboost-filesystem1.65-dev:amd64      1.65.1+dfsg-0ubuntu5               amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-filesystem1.65.1:amd64        1.65.1+dfsg-0ubuntu5               amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-graph-dev:amd64               1.65.1.0ubuntu1                    amd64        generic graph components and algorithms in C++ (default version)
ii  libboost-graph-parallel-dev            1.65.1.0ubuntu1                    amd64        generic graph components and algorithms in C++ (default version)
ii  libboost-graph-parallel1.65-dev        1.65.1+dfsg-0ubuntu5               amd64        generic graph components and algorithms in C++
ii  libboost-graph-parallel1.65.1          1.65.1+dfsg-0ubuntu5               amd64        generic graph components and algorithms in C++
ii  libboost-graph1.65-dev:amd64           1.65.1+dfsg-0ubuntu5               amd64        generic graph components and algorithms in C++
ii  libboost-graph1.65.1:amd64             1.65.1+dfsg-0ubuntu5               amd64        generic graph components and algorithms in C++
ii  libboost-iostreams-dev:amd64           1.65.1.0ubuntu1                    amd64        Boost.Iostreams Library development files (default version)
ii  libboost-iostreams1.65-dev:amd64       1.65.1+dfsg-0ubuntu5               amd64        Boost.Iostreams Library development files
ii  libboost-iostreams1.65.1:amd64         1.65.1+dfsg-0ubuntu5               amd64        Boost.Iostreams Library
ii  libboost-locale-dev:amd64              1.65.1.0ubuntu1                    amd64        C++ facilities for localization (default version)
ii  libboost-locale1.65-dev:amd64          1.65.1+dfsg-0ubuntu5               amd64        C++ facilities for localization
ii  libboost-locale1.65.1:amd64            1.65.1+dfsg-0ubuntu5               amd64        C++ facilities for localization
ii  libboost-log-dev                       1.65.1.0ubuntu1                    amd64        C++ logging library (default version)
ii  libboost-log1.65-dev                   1.65.1+dfsg-0ubuntu5               amd64        C++ logging library
ii  libboost-log1.65.1                     1.65.1+dfsg-0ubuntu5               amd64        C++ logging library
ii  libboost-math-dev:amd64                1.65.1.0ubuntu1                    amd64        Boost.Math Library development files (default version)
ii  libboost-math1.65-dev:amd64            1.65.1+dfsg-0ubuntu5               amd64        Boost.Math Library development files
ii  libboost-math1.65.1:amd64              1.65.1+dfsg-0ubuntu5               amd64        Boost.Math Library
ii  libboost-mpi-dev                       1.65.1.0ubuntu1                    amd64        C++ interface to the Message Passing Interface (MPI) (default version)
ii  libboost-mpi-python-dev                1.65.1.0ubuntu1                    amd64        C++ interface to the Message Passing Interface (MPI), Python Bindings (default version)
ii  libboost-mpi-python1.65-dev            1.65.1+dfsg-0ubuntu5               amd64        C++ interface to the Message Passing Interface (MPI), Python Bindings
ii  libboost-mpi-python1.65.1              1.65.1+dfsg-0ubuntu5               amd64        C++ interface to the Message Passing Interface (MPI), Python Bindings
ii  libboost-mpi1.65-dev                   1.65.1+dfsg-0ubuntu5               amd64        C++ interface to the Message Passing Interface (MPI)
ii  libboost-mpi1.65.1                     1.65.1+dfsg-0ubuntu5               amd64        C++ interface to the Message Passing Interface (MPI)
ii  libboost-numpy-dev                     1.65.1.0ubuntu1                    amd64        Boost.Python NumPy extensions development files (default version)
ii  libboost-numpy1.65-dev                 1.65.1+dfsg-0ubuntu5               amd64        Boost.Python NumPy extensions development files
ii  libboost-numpy1.65.1                   1.65.1+dfsg-0ubuntu5               amd64        Boost.Python NumPy extensions
ii  libboost-program-options-dev:amd64     1.65.1.0ubuntu1                    amd64        program options library for C++ (default version)
ii  libboost-program-options1.65-dev:amd64 1.65.1+dfsg-0ubuntu5               amd64        program options library for C++
ii  libboost-program-options1.65.1:amd64   1.65.1+dfsg-0ubuntu5               amd64        program options library for C++
ii  libboost-python-dev                    1.65.1.0ubuntu1                    amd64        Boost.Python Library development files (default version)
ii  libboost-python1.65-dev                1.65.1+dfsg-0ubuntu5               amd64        Boost.Python Library development files
ii  libboost-python1.65.1                  1.65.1+dfsg-0ubuntu5               amd64        Boost.Python Library
ii  libboost-random-dev:amd64              1.65.1.0ubuntu1                    amd64        Boost Random Number Library (default version)
ii  libboost-random1.65-dev:amd64          1.65.1+dfsg-0ubuntu5               amd64        Boost Random Number Library
ii  libboost-random1.65.1:amd64            1.65.1+dfsg-0ubuntu5               amd64        Boost Random Number Library
ii  libboost-regex-dev:amd64               1.65.1.0ubuntu1                    amd64        regular expression library for C++ (default version)
ii  libboost-regex1.65-dev:amd64           1.65.1+dfsg-0ubuntu5               amd64        regular expression library for C++
ii  libboost-regex1.65.1:amd64             1.65.1+dfsg-0ubuntu5               amd64        regular expression library for C++
ii  libboost-serialization-dev:amd64       1.65.1.0ubuntu1                    amd64        serialization library for C++ (default version)
ii  libboost-serialization1.65-dev:amd64   1.65.1+dfsg-0ubuntu5               amd64        serialization library for C++
ii  libboost-serialization1.65.1:amd64     1.65.1+dfsg-0ubuntu5               amd64        serialization library for C++
ii  libboost-signals-dev:amd64             1.65.1.0ubuntu1                    amd64        managed signals and slots library for C++ (default version)
ii  libboost-signals1.65-dev:amd64         1.65.1+dfsg-0ubuntu5               amd64        managed signals and slots library for C++
ii  libboost-signals1.65.1:amd64           1.65.1+dfsg-0ubuntu5               amd64        managed signals and slots library for C++
ii  libboost-stacktrace-dev:amd64          1.65.1.0ubuntu1                    amd64        library to capture and print stack traces - development files (default version)
ii  libboost-stacktrace1.65-dev:amd64      1.65.1+dfsg-0ubuntu5               amd64        library to capture and print stack traces - development files
ii  libboost-stacktrace1.65.1:amd64        1.65.1+dfsg-0ubuntu5               amd64        library to capture and print stack traces
ii  libboost-system-dev:amd64              1.65.1.0ubuntu1                    amd64        Operating system (e.g. diagnostics support) library (default version)
ii  libboost-system1.65-dev:amd64          1.65.1+dfsg-0ubuntu5               amd64        Operating system (e.g. diagnostics support) library
ii  libboost-system1.65.1:amd64            1.65.1+dfsg-0ubuntu5               amd64        Operating system (e.g. diagnostics support) library
ii  libboost-test-dev:amd64                1.65.1.0ubuntu1                    amd64        components for writing and executing test suites (default version)
ii  libboost-test1.65-dev:amd64            1.65.1+dfsg-0ubuntu5               amd64        components for writing and executing test suites
ii  libboost-test1.65.1:amd64              1.65.1+dfsg-0ubuntu5               amd64        components for writing and executing test suites
ii  libboost-thread-dev:amd64              1.65.1.0ubuntu1                    amd64        portable C++ multi-threading (default version)
ii  libboost-thread1.65-dev:amd64          1.65.1+dfsg-0ubuntu5               amd64        portable C++ multi-threading
ii  libboost-thread1.65.1:amd64            1.65.1+dfsg-0ubuntu5               amd64        portable C++ multi-threading
ii  libboost-timer-dev:amd64               1.65.1.0ubuntu1                    amd64        C++ wall clock and CPU process timers (default version)
ii  libboost-timer1.65-dev:amd64           1.65.1+dfsg-0ubuntu5               amd64        C++ wall clock and CPU process timers
ii  libboost-timer1.65.1:amd64             1.65.1+dfsg-0ubuntu5               amd64        C++ wall clock and CPU process timers
ii  libboost-tools-dev                     1.65.1.0ubuntu1                    amd64        Boost C++ Libraries development tools (default version)
ii  libboost-type-erasure-dev:amd64        1.65.1.0ubuntu1                    amd64        C++ runtime polymorphism based on concepts (default version)
ii  libboost-type-erasure1.65-dev:amd64    1.65.1+dfsg-0ubuntu5               amd64        C++ runtime polymorphism based on concepts
ii  libboost-type-erasure1.65.1:amd64      1.65.1+dfsg-0ubuntu5               amd64        C++ runtime polymorphism based on concepts
ii  libboost-wave-dev:amd64                1.65.1.0ubuntu1                    amd64        C99/C++ preprocessor library (default version)
ii  libboost-wave1.65-dev:amd64            1.65.1+dfsg-0ubuntu5               amd64        C99/C++ preprocessor library
ii  libboost-wave1.65.1:amd64              1.65.1+dfsg-0ubuntu5               amd64        C99/C++ preprocessor library
ii  libboost1.65-dev:amd64                 1.65.1+dfsg-0ubuntu5               amd64        Boost C++ Libraries development files
ii  libboost1.65-tools-dev                 1.65.1+dfsg-0ubuntu5               amd64        Boost C++ Libraries development tools

**Comment by storypku** [comment]
> ii libboost-all-dev 1.65.1.0ubuntu1 amd64 Boost C++ Libraries development files (ALL) (default version)

It's really strange that boost can't be found since you have only system provided boost installed. 
Two clues: 1) Write a Boost Hello World example  built with CMAKE to see if everything works OK  2) If the Boost Hello World example can't compile either, try to install a more recent cmake from [CMake Office Download Site](https://cmake.org/download/ )

**Comment by michael4338** [comment]
Did the above answer resolve your issue?  Closing now and please reopen if problem still exists

**Comment by AlexandrZabolotny** [comment]
I reinstalled cmake, boost. And now all ok.
