### ISSUE TITLE
Control: Differences between agent and submoduled control system

### ISSUE THREAD

**Issue by yukitsuji** [ApolloAuto/apollo#11526]
Could you tell me the differences/Pros/Cons between the agent based and submoduled based control modules?

Thanks,

**Comment by sjiang2018** [comment]
Hello there! 
Sub-module control system aims to make control module more user-friendly. There are two types of control sub-modules, Apollo common interface sub-modules and control-core algorithm sub-modules. The pre-processor and post-processor modules belong to Apollo common interface sub-modules and they help to integrate control module to Apollo system. Users don't need to make any changes to these two modules. Control-core algorithm modules, such as MPC_controller_submodule and lat_lon_controller_submodule, are where user can modify. Users may even write new control core algorithm submodules, as along as APIs remain the same.

**Comment by yukitsuji** [comment]
Thank you for your quick reply!
I got it. I have another question.
I think there are two types of control pipeline;
1. https://github.com/ApolloAuto/apollo/blob/master/modules/control/dag/control.dag
2. https://github.com/ApolloAuto/apollo/blob/master/modules/control/dag/mpc_module.dag

`FLAGS_use_control_submodules` is used to specify the type to run. 
1 does not use pre-processor and post-processor, but use only [controller_agent](https://github.com/ApolloAuto/apollo/blob/master/modules/control/controller/controller_agent.cc) for publising `/apollo/control`.
2 does as you mentioned and [controller_agent](https://github.com/ApolloAuto/apollo/blob/master/modules/control/controller/controller_agent.cc)  publishes only `/apollo/control/localview` to pass the environment information to Sub-module control system. 

How does this difference change the output of the controller?
Which should we use for autonomous driving?

Thanks,

**Comment by daohu527** [comment]
## Controller_agent
For now control module used controller_agent
1.  FLAGS_use_control_submodules
FLAGS_use_control_submodules default is flase
https://github.com/ApolloAuto/apollo/blob/3e691397c5a805c864ad048161e2d5c3d26f14c1/modules/control/common/control_gflags.cc#L119-L120

2. controller_agent
```c++
  // initial controller agent when not using control submodules
  ADEBUG << "FLAGS_use_control_submodules: " << FLAGS_use_control_submodules;
  if (!FLAGS_use_control_submodules &&
      !controller_agent_.Init(&control_conf_).ok()) {
    // set controller
    ADEBUG << "original control";
    monitor_logger_buffer_.ERROR("Control init controller failed! Stopping...");
    return false;
  }
```
Then use controller_agent to control the car. "active_controllers" in "control_conf.pb.txt" defines which "controller_agent" to use, for example:
```
active_controllers: LAT_CONTROLLER
active_controllers: LON_CONTROLLER
```
or
```
active_controllers: MPC_CONTROLLER
```

## Control_submodules
control_submodules's message pipeline 
```
/apollo/control/localview  ->  /apollo/control/preprocessor -> /apollo/control/controlcore -> /apollo/control
```
modules pipeline 
```
ControlComponent -> PreprocessorSubmodule -> LatLonControllerSubmodule -> PostprocessorSubmodule
```

which means you can define some method's yourself in **LatLonControllerSubmodule**

**Comment by sjiang2018** [comment]
Hi @yukitsuji, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
