### ISSUE TITLE
cyber_visualizer can't see point cloud,but the channel has data

### ISSUE THREAD

**Issue by cxr1996** [ApolloAuto/apollo#11520]
### System information

-Ubuntu 14.04
-  binary:
- Apollo5.0.0:

I used apollo5.0.0, a single VLP-16 lidar, and there was data in the channel when Connected, but only a white spot could be seen by using Cyber_Visualizer. My OpengL version was 3.0, and the host and Docker had installed NVIDIA driver (No OpengL-files). Some people said that the version of OEPNGL was too low, but when I installed NVIDIA driver, I chose to install OpengL automatically. The opengL file between the host and Docker may be incompletely linked, causing an error on "Cloud not initialize GLX", so how can we fix this problem?
![2](https://user-images.githubusercontent.com/56950044/85246884-92ccdd80-b47e-11ea-8baf-4537d0bcc6ee.png)
![3](https://user-images.githubusercontent.com/56950044/85246888-95c7ce00-b47e-11ea-8480-6a7b5d2be02c.png)

**Comment by cxr1996** [comment]
My Version of OPENGL is 3.0

**Comment by lx18233184051** [comment]
It seems nvdia has own opengl file ,so No OpengL-files optional is ok, according to what you said, I think you should guarantee your opengL version in docker, whether it's compatible with your nvdia driver  ?

**Comment by cxr1996** [comment]
> It seems nvdia has own opengl file ,so No OpengL-files optional is ok, according to what you said, I think you should guarantee your opengL version in docker, whether it's compatible with your nvdia driver ?

Thank you, I have solved this problem by going straight to version 5.5 and replacing Ubuntu with 18.04
