### ISSUE TITLE
Error in running a launch file

### ISSUE THREAD

**Issue by Martin20** [ApolloAuto/apollo#11532]
-OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
-Apollo installed from (source or binary)**: Source
-Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

I run the simulator and launch v2x by "v2x.launch". However, I received the following error. Can anyone help me?

[/apollo/bazel-bin/modules/v2x/v2x --flagfile=/apollo/modules/v2x/conf/v2x.conf] /apollo/bazel-bin/modules/v2x/v2x: error while loading shared libraries: libfastcdr.so.1: cannot open shared object file: No such file or directory

**Comment by Eclipsehelio** [comment]
@Martin20  In most cases, This is about environmental variables. Usually `libfastcdr.so.1` is located in `/usr/local/fast-rtps/lib/`, check the `LD_LIBRARY_PATH`  environment variable to see if `/usr/local/fast-rtps/lib` is in it, perhaps you may forget to execute `source cyber/setup.bash`.

**Comment by lfcarol** [comment]
Do you run the simulator and launch v2x in the docker environment?

**Comment by Martin20** [comment]
Yes, I run it inside the docket.

**Comment by Martin20** [comment]
@Eclipsehelio 
I execute source "cyber/setup"

**Comment by lx18233184051** [comment]
can you find libfastcdr.so.1 in your environment?

**Comment by Martin20** [comment]
@lx18233184051 

No, I could not find it in the apollo directory.

I made a mistake in my first message. The version of Ubuntu is 16.04.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
