### ISSUE TITLE
Error: launch   perception_camera.launch

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11539]
Hello! Please help me  

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04, RTX2070, Driver Version: 450.36.06)**:
- **Apollo installed from (source)**:
- **Apollo version (master)**:

I use lglsv_simulator for to study Apollo.

When I run 
cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch  

I can see this error

![Screenshot from 2020-06-23 17-27-11](https://user-images.githubusercontent.com/61351599/85418342-56ca7300-b579-11ea-9360-fd4761e2a19c.png)

**Comment by northeastsquare** [comment]
I also met

**Comment by AlexandrZabolotny** [comment]
> I also met

run only first mainboard

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
