### ISSUE TITLE
Cannot Generate Message by Message Type

### ISSUE THREAD

**Issue by machar94** [ApolloAuto/apollo#11536]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Sometimes I am unable to view the message content of certain channels. It is the case that sometimes, exiting cyber_monitor and starting again does populate the messages. Other times, the error is Cannot Generate Message by Message Type. Note that I am seeing a green text and so I do believe messages are being created and sent. Is there something I am perhaps not sourcing? Other messages do populate. I start dreamview by using `./scripts/bootstrap.sh`. I run cyber monitor using `cyber_monitor`.

### Supporting materials (screenshots, command lines, code/script snippets):
![perception_obstacles](https://user-images.githubusercontent.com/4420650/85412469-97a19800-b537-11ea-9b06-690dd733d298.png)

![cyber_monitor](https://user-images.githubusercontent.com/4420650/85412009-1944f600-b537-11ea-8aae-b9f81a7b2335.png)

**Comment by ntutangyun** [comment]
yeah. sometimes I'm getting this weird error also.

**Comment by ntutangyun** [comment]
wait. how did I manage to unassign anyone?

**Comment by ntutangyun** [comment]
still seeing this issue. any update ?

**Comment by machar94** [comment]
I don't see this issue anymore.

**Comment by felixf4xu** [comment]
please keep the issue open because I'm having the same issue.

If I exit cyber_monitor and run cyber_moniter again, sometimes the issue will gone but not always.

(my data is 25 fps and each data is about 6M bytes, not sure if it's related to message size)

**Comment by daohu527** [comment]
@felixf4xu Since this issue is closed, we would better open a new one, then disscuss there

**Comment by YYangjlu** [comment]
I tried 8.0, still have this isses

**Comment by daohu527** [comment]
I checked the code and guessed it was caused by message compatibility.

For example, if the path of the message changes, I will process it and give a conclusion

**Comment by valaxkong** [comment]
@daohu527 Hi, Is there any progress for a conclusion? I met this bug that can be reproduced with certainty

**Comment by daohu527** [comment]
It's fixed! Will sync to 8.0 later

**Comment by valaxkong** [comment]
> It's fixed! Will sync to 8.0 later

Great, thanks! Did you published the fix commit? I'd like to know some details. 
Besides, I met this error: "Cannot parse the raw message". Are they the same bug? Or just some illegal value are assigned to the message?
![image](https://github.com/ApolloAuto/apollo/assets/18673335/e4b983a7-4915-4eb1-b193-d65137d3a32b)

**Comment by daohu527** [comment]
This modification is not synced yet, because AMD support is not synced yet

**Comment by lix19937** [comment]
please keep the issue open because I'm having the same issue.
