### ISSUE TITLE
Does terminalc.cc retired in Apollo v3.5?

### ISSUE THREAD

**Issue by miewan** [ApolloAuto/apollo#11549]
Does terminal.cc also retired from Apollo v3.5 as this file also use adapter_manager.h which is retired in v3.5

**Comment by daohu527** [comment]
Ref to #11349 

Additionally there is a commit a224ae3806c3b34d65f10f2e35b4ce1f35a9555a about rename terminal to pad_terminal.

**Comment by jinghaomiao** [comment]
I am closing this ticket. If you have other question, please submit another ticket. Thanks for your interests in Apollo.
