### ISSUE TITLE
IMU-to-Vehicle Calibration tool not available

### ISSUE THREAD

**Issue by hb2609** [ApolloAuto/apollo#11543]
This document(https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md ) refers to a  IMU-to-Vehicle calibration tool and provides a download link(https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip). However, the download link provided has failed. I don't know where to get a valid link? Can anyone help me?

**Comment by diegohu** [comment]
For Lidar-IMU calibration, please refer to this guide https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/multiple_lidar_gnss_calibration_guide.md and you will find the download link.
However, this tool only support Apollo 3.0 which based on ROS, for Apollo 3.5+ which switched to Cyber RT, we provide cloud service for calibration, please refer to https://apollo.auto/fuel.html for details.

**Comment by sjiang2018** [comment]
Hi @hb2609 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Comment by wf1024966** [comment]
hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by wf1024966** [comment]
> This document(https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md ) refers to a IMU-to-Vehicle calibration tool and provides a download link(https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip). However, the download link provided has failed. I don't know where to get a valid link? Can anyone help me?

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!
