### ISSUE TITLE
Apollo 6.0 release date

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#11559]
Hi,

Apollo seems to have a new release every 6 months. Should we be expecting Apollo 6.0 or a major update soon? Is there a time frame?

Thanks,

Siddharth

**Comment by lfcarol** [comment]
Thank you for continuous attention to Apollo. Apollo 6.0 will be released at September.

**Comment by agarwalsid** [comment]
Thank you for the info @lfcarol @jinghaomiao
