### ISSUE TITLE
Perception module CyberRT to ROS

### ISSUE THREAD

**Issue by mertmerci** [ApolloAuto/apollo#11560]
I try to run the perception module standalone and try to change the communication framework from CyberRT to ROS due to the consistency of my own framework. I know that ROS Bridge may be a possible solution for my problem but I do not prefer it right now. Do you have any suggestions for me or any documentation helpful for my problem?

**Comment by jinghaomiao** [comment]
@mertmerci Thanks for your interests in Apollo. Starting from Apollo 3.5, ROS is not supported in Apollo. Apollo itself does not support bridging between CyberRT and ROS. I'd advise that you seek help in ROS community. Thanks again.
