### ISSUE TITLE
 sudo bash docker/scripts/dev_start.sh  fail ,looks like gpu's problem?

### ISSUE THREAD

**Issue by fantasyplus** [ApolloAuto/apollo#11612]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **Ubuntu18.04**:
- **git**:
- **Apollo version (5.5)**:

### Steps to reproduce the issue:
- **Before I setup GPU accelrate,dev_start.sh worked,but when I continue to build apollo.sh,my computer jamed.
     So I setup GPU,and then the problem occurs**:

### Supporting materials (screenshots, command lines, code/script snippets):

[INFO] Starting docker container "apollo_dev_ros" ...
[WARNING] nvidia-docker is in deprecation!
[WARNING] Please install latest docker and nvidia-container-toolkit: https://github.com/NVIDIA/nvidia-docker/blob/master/README.md
++ local_volumes
++ set +x
+ nvidia-docker run -it -d --privileged --name apollo_dev_ros --volumes-from apollo_map_volume-sunnyvale_big_loop_ros --volumes-from apollo_map_volume-sunnyvale_loop_ros --volumes-from apollo_map_volume-sunnyvale_with_two_offices_ros --volumes-from apollo_map_volume-san_mateo_ros --volumes-from apollo_yolo3d_volume_ros --volumes-from apollo_localization_volume_ros --volumes-from apollo_paddlepaddle_volume_ros --volumes-from apollo_local_third_party_volume_ros -e DISPLAY=:0 -e DOCKER_USER=ros -e USER=ros -e DOCKER_USER_ID=1000 -e DOCKER_GRP=docker -e DOCKER_GRP_ID=999 -e DOCKER_IMG=apolloauto/apollo:dev-18.04-x86_64-20200601_0507 -e USE_GPU=1 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility -v /home/ros/apollo:/apollo -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in_dev_docker:127.0.0.1 --add-host ros:127.0.0.1 --hostname in_dev_docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 apolloauto/apollo:dev-18.04-x86_64-20200601_0507 /bin/bash
5e11e1732d6793b0c06abf053668cea2363a4a8af9bcfe10e4772981e3cfe65f
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: detection error: nvml error: unknown error\\\\n\\\"\"": unknown.
+ '[' 125 -ne 0 ']'
+ error 'Failed to start docker container "apollo_dev_ros" based on image: apolloauto/apollo:dev-18.04-x86_64-20200601_0507'
+ echo -e '[\033[0;31mERROR\033[0m] Failed to start docker container "apollo_dev_ros" based on image: apolloauto/apollo:dev-18.04-x86_64-20200601_0507'
[ERROR] Failed to start docker container "apollo_dev_ros" based on image: apolloauto/apollo:dev-18.04-x86_64-20200601_0507
+ exit 1

**Comment by storypku** [comment]
Have you tried restart docker  by running `sudo systemctl restart docker` ?

**Comment by fantasyplus** [comment]
> Have you tried restart docker by running `sudo systemctl restart docker` ?

谢谢回复，我把Ｎ卡相关的都删了，用ＣＰＵ跑就行了，现在正在等编译结束呢

**Comment by Jelvon** [comment]
> > Have you tried restart docker by running `sudo systemctl restart docker` ?
> 
> 谢谢回复，我把Ｎ卡相关的都删了，用ＣＰＵ跑就行了，现在正在等编译结束呢

May I ask how do you solve this problem ? I cannot read what you said...Thank you so much!

**Comment by Jelvon** [comment]
> Have you tried restart docker by running `sudo systemctl restart docker` ?

I have tried, but it does not work.

**Comment by fantasyplus** [comment]
> > > Have you tried restart docker by running `sudo systemctl restart docker` ?
> > 
> > 
> > 谢谢回复，我把Ｎ卡相关的都删了，用ＣＰＵ跑就行了，现在正在等编译结束呢
> 
> May I ask how do you solve this problem ? I cannot read what you said...Thank you so much!

I used Nvidia-Gpu-accelrate when I meet this problem .
Look at those warning rows 
'[WARNING] nvidia-docker is in deprecation!
[WARNING] Please install latest docker and nvidia-container-toolkit: https://github.com/NVIDIA/nvidia-docker/blob/master/README.md'
So I just delete all the nvidia-related package....and use only cpu to run build,although it's slow.
Maybe not a good way for you.

**Comment by storypku** [comment]
> > Have you tried restart docker by running `sudo systemctl restart docker` ?
> 
> I have tried, but it does not work.
Have you installed `nvidia-container-toolkit`. On ubuntu, this can be done via `sudo apt-get -y install nvidia-container-toolkit`

**Comment by storypku** [comment]
This issue is going to be closed for long time no response. 
Please checkout latest `master` to see if the problem is still there.
If so, please reopen this issue. Or create a new one if you have other questions.
Thanks for supporting Apollo!
