### ISSUE TITLE
Error while starting Transform module

### ISSUE THREAD

**Issue by lh315936716** [ApolloAuto/apollo#11610]
![image](https://user-images.githubusercontent.com/23692631/86099415-078cc100-baea-11ea-8884-a666dd48bbd2.png)

The error message is shown in above pic from apollo 3.5. I could not find the files mentioned in those error msgs.
Besides,  the transform module can be turned on in dreamview but I was not sure if it worked.

It would be really appreciated if someone could provide any suggestion!

**Comment by lx18233184051** [comment]
maybe you could give more info about your system and env?

**Comment by lh315936716** [comment]
> maybe you could give more info about your system and env?
Thank you. I'm on Ubuntu 18.04 and using the image of lgsvl/apollo-3.5, nvidia graphics driver 440.33, cuda10.2. 
 As the error msg indicated some information about lidar, I don't think it was any problem with my system setup.

**Comment by jeroldchen** [comment]
Hi @lh315936716 , you can try switching to another vehicle like mkz7 on dreamview panel. Besides, you can launch transform module by either turning on the button on dreamview panel, or running `cyber_launch start /apollo/modules/transform/launch/static_transform.launch`, but not both at the same time.
