### ISSUE TITLE
Error when using laptop webcam as usb camera

### ISSUE THREAD

**Issue by dt-developer1** [ApolloAuto/apollo#11632]
I am trying to use laptop webcam as usb camera. I changed the camera dev in conf as /dev/video0. but i am getting following error when launching camera.launch

[usb_cam] E0701 12:39:26.911983 25095 usb_cam.cc:867] [mainboard]Wrong Buffer Len: 1843200,raw_image->width * raw_image->height: 2073600, dev: /dev/video0
[usb_cam] E0701 12:39:26.949627 25095 camera_component.cc:86] [camera]Running

Also am not getting video in Dreamviewer and cyber_visualizer. Is there any other configurations need to be changed for using laptop webcam?

**Comment by daohu527** [comment]
Pls try to set the camera width and height according to your camera parameters. The default parameter may be too large for your camera.  
https://github.com/ApolloAuto/apollo/blob/f7c5c113dc20313c5fe0b615fda32277a326c48d/modules/drivers/camera/conf/camera_front_12mm.pb.txt#L2-L7

**Comment by dt-developer1** [comment]
Thanks for the support. I changed the width and height  to webcamera parameters. Now it is working.

**Comment by SpeedAutonomy** [comment]
> I am trying to use laptop webcam as usb camera. I changed the camera dev in conf as /dev/video0. but i am getting following error when launching camera.launch
> 
> [usb_cam] E0701 12:39:26.911983 25095 usb_cam.cc:867] [mainboard]Wrong Buffer Len: 1843200,raw_image->width * raw_image->height: 2073600, dev: /dev/video0
> [usb_cam] E0701 12:39:26.949627 25095 camera_component.cc:86] [camera]Running
> 
> Also am not getting video in Dreamviewer and cyber_visualizer. Is there any other configurations need to be changed for using laptop webcam?

Hi, I'm trying to do something similar with webcams. Can you please clarify what you meant by "changed the camera dev in conf as /dev/video0"? What file did you change? I listed the video inputs and I have a video0 and 1. How'd you change this file. Can you tell me the name and folder the file you changed is? How does it work with a webcam. Are you seeing it on dreamview? Help and clarification on this would be very helpful. Thank you.

**Comment by jp12AI** [comment]
> I am trying to use laptop webcam as usb camera. I changed the camera dev in conf as /dev/video0. but i am getting following error when launching camera.launch
> 
> [usb_cam] E0701 12:39:26.911983 25095 usb_cam.cc:867] [mainboard]Wrong Buffer Len: 1843200,raw_image->width * raw_image->height: 2073600, dev: /dev/video0
> [usb_cam] E0701 12:39:26.949627 25095 camera_component.cc:86] [camera]Running
> 
> Also am not getting video in Dreamviewer and cyber_visualizer. Is there any other configurations need to be changed for using laptop webcam?

Hello, I'm trying something similiar with webcams. What file did you make edits to? I have video0 and 1. What did you change in the file to make it work? Did you get video input in dreamview? Help on this would be appreciated. Thank you.

**Comment by whj-cmd** [comment]
[mainboard]Wrong Buffer Len: 114264, dev: /dev/camera/front_6mm
