### ISSUE TITLE
Current status of HD map?

### ISSUE THREAD

**Issue by Doodle1106** [ApolloAuto/apollo#11631]
Hi,

I have been going through the project recently and I noticed the use of HD map in the project.
I have some HD map related questions that I hope you guys can shed some light on:

1. is HD map used during localization? If so, can localization be done only on HD map? Is this part open sourced?
2. is there an annotation tool to annotate HD map?
3. how is HD map generated? from lidar or camera?

Thanks for trying to help.
Joey

**Comment by jinghaomiao** [comment]
@Doodle1106 thanks for your interests in Apollo. 
1. HD Map is used in pereption, prediction and planning. Localization does not use HD Map.
2. We don't have annotation tool to anonatate HD map now.
3. HD map is generated by collecting both point cloud data and camera data.

**Comment by Doodle1106** [comment]
thanks @jinghaomiao
