### ISSUE TITLE
Need suggestions for camera integration with Apollo 3.0

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#11649]
Hello all,
I need to use a real camera instead of the available virtual cameras in the simulator like ColorCameraSensor, DepthCameraSensor, and SegmentationCameraSensor.
I should place this camera in front of the simulation screen. It should capture the images and send them to apollo. (just like how it is sent now from the virtual cameras). Then apollo needs to process this data to do lane detection, forward collision warning, and traffic sign recognition.
Can you suggest some real cameras, which I can integrate in the loop to Apollo for the above purpose?

The main goal of my project is to evaluate the performance of the actual camera by creating different simulation scenarios.

### System information

I am using LGSVL simulator which is interfaced by ROS bridge to Apollo 3.0

**Comment by daohu527** [comment]
Officially recommended camera model [Link](https://apollo.auto/platform/hardware_cn.html) . eg:

```
LI-USB30-AR023ZWDR
```
