### ISSUE TITLE
What

### ISSUE THREAD

**Issue by quhezheng** [ApolloAuto/apollo#11643]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by ntutangyun** [comment]
???

**Comment by sjiang2018** [comment]
Hello @quhezheng , I think this is the same issue as #11644. I am going to close this one. Thank you for your supporting Apollo.
