### ISSUE TITLE
how to change maximum speed while updating vehicle calibration table?

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#11640]
After follow the steps given in the following document the Vehicle Calibration table is updated, but maximum speed given in the table is 10 m/s. what if the vehicle speed is greater then 10 m/s? 

https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_update_vehicle_calibration.md
(How to Update Vehicle Calibration for Throttle and Brakes)

So how to increase the maximum speed in the table? and create calibration table for 30 m/s?

e.g.
    calibration {
      speed: 10.0
      acceleration: 3.00
      command: 85.0
    }

**Comment by daohu527** [comment]
When generate the calibration table, the speed range seems to be limited by 10.01m/s.   
https://github.com/ApolloAuto/apollo/blob/f7c5c113dc20313c5fe0b615fda32277a326c48d/modules/tools/vehicle_calibration/process.py#L136-L138

**Comment by Addi2020** [comment]
@daohu527 , yeah it seems to be speed range but by changing this speed range value (10.01 to 15.01 or 20.01) does not effect the calibration speed,  it still create the calibration table of max speed up to 10m/s. 

What if the car real speed is more then 10m/s, then how control module will calculate the throttle and brake cmds? That's why i want to increase the max speed of calibration table.

**Comment by daohu527** [comment]
1. I didn't find any problem at the moment. It may be that the data collected has not reached such a high speed? You can try to debug the program that generates the calibration table.

2. In my opinion, PID is more suitable for low speed and low curvature control, MPC is more suitable for high speed.

**Comment by sjiang2018** [comment]
Hello there! 
@Addi2020 
In the default calibration table, the maximum speed is 10.0m/s. But you can always generate a new calibration table with higher speed limit. 
1.	If you already have a calibration table, you can substitute the default calibration table (https://github.com/ApolloAuto/apollo/blob/master/modules/control/conf/calibration_table.pb.txt) with yours. The speed limits completely depend on the content of your calibration table. 
2.	If you don’t have a calibration table and want to use Apollo system to generate one for your vehicle.  Here are the instructions (https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md). You will need to collect manual driving data and process it with the service provided by Apollo. The maximum speed of the generated calibration table depends on the maximum speed of the collected data. 
@daohu527
I think this file (https://github.com/ApolloAuto/apollo/blob/master/modules/tools/vehicle_calibration/process.py)
is kind of obsolete and it is not a part of the latest vehicle calibration process.

**Comment by Addi2020** [comment]
@daohu527 @sjiang2018 . Thanks for your suggestion and explanation. I will create a new calibration table by the procedure given in https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_update_vehicle_calibration.md  for high speed and i will share the results here soon.

Note: I use Apollo3.5.0

**Comment by jinghaomiao** [comment]
@Addi2020 hope your question is answered. I am closing this ticket. Please feel free to raise other issues if needed. Thanks!
