### ISSUE TITLE
What's cost function behind DualVariableWarmStartOSQPInterface

### ISSUE THREAD

**Issue by quhezheng** [ApolloAuto/apollo#11644]
### System information

- **Linux Ubuntu 16.04**:
- **Apollo installed from (source )**:
- **Apollo version (5.5)**:

When doing warm startup in open-space planning task,  DualVariableWarmStartProblem is used to solve l_warm_up, n_warm_up

The objective function is norm(A' * lambda) in OSQP solver, any detailed explanation about why? 
The reference material _'Optimization-Based Collision Avoidance'_ doesn't match with code very well.

**Comment by deidaraho** [comment]
It is not the same dual warm up strategy from OBCA, generally speaking, it wraps the l2 norm constraints into the cost function, since OSQP is not good at solving QCQP.

**Comment by kevin-y-wang** [comment]
Hi, @quhezheng  thanks for your interests and contributions to improve the Apollo platform. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer teams are more than happy to help that.

Thank you for supporting Apollo!
