### ISSUE TITLE
About the gcc/g++ version required by apollo.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#11648]
Hi,

On Ubuntu 20.04, I want to install git master version of apollo on the apollo Dev-kit vehicle. I noticed that the suggested [gcc/g++ version](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E5%AE%89%E8%A3%85%E5%B9%B6%E9%99%8D%E7%BA%A7gcc%E5%92%8Cg) is 4.8. Considering that it's a rather old version, so I'm very confused on this requirement. Any hints for this problem?

Regards.

**Comment by storypku** [comment]
> Hi,
> 
> On Ubuntu 20.04, I want to install git master version of apollo on the apollo Dev-kit vehicle. I noticed that the suggested [gcc/g++ version](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E5%AE%89%E8%A3%85%E5%B9%B6%E9%99%8D%E7%BA%A7gcc%E5%92%8Cg) is 4.8. Considering that it's a rather old version, so I'm very confused on this requirement. Any hints for this problem?
> 
> Regards.

I think the main reason for gcc/g++-4.8 is to avoid possible compilation errors if compiled using higher gcc/g++ versions.

Currently we are working to fix them (if any) for ubuntu （18.04+）with gcc-7.5 & c++14. Once completed, the gcc/g++-4.8 requrements should be removed. 

Also cc @diegohu

**Comment by hongyi-zhao** [comment]
Why not try to support the latest version which shipped with 20.04:

 ```
$ g++ --version
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by storypku** [comment]
> > I think the main reason for gcc/g++-4.8 is to avoid possible compilation errors if compiled using higher gcc/g++ versions.
> 
> Which errors?
> 
> > Currently we are working to fix them (if any) for ubuntu （18.04+）with gcc-7.5 & c++14.
> 
> According to the document [here](https://gcc.gnu.org/projects/cxx-status.html#cxx14), all versions of gcc 6.1+ support c++14.
> 
> > Once completed, the gcc/g++-4.8 requrements should be removed.
> 
> OTOH, the current Ubuntu stable version is 20.04 LTS. Why not try to support the most recent version which shipped with 20.04:
> 
> ```
> $ g++ --version
> g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> $ gcc --version
> gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

1) About compilation errors: 
gcc-7.5+ was more strict than gcc-4.8.5, so many modules can't compile under gcc-7.5+.
Presently, we are working to get them all resolved.

2) About gcc-9.3 and gcc-7.5:
Ubuntu 18.04 ships gcc-7.5 while Ubuntu 20.04 ships gcc-9.3 as default gcc compiler.  We are trying hard to make sure Apollo can compile and run on them both with c++14/17 standards. And, our `arm64` support was not complete yet. All these need effort. 

Backward compatibility is important to any software systems, so do Apollo. 

Thanks for your attention to Apollo. Hope my answer helps.

**Comment by storypku** [comment]
> > Hi,
> > On Ubuntu 20.04, I want to install git master version of apollo on the apollo Dev-kit vehicle. I noticed that the suggested [gcc/g++ version](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E5%AE%89%E8%A3%85%E5%B9%B6%E9%99%8D%E7%BA%A7gcc%E5%92%8Cg) is 4.8. Considering that it's a rather old version, so I'm very confused on this requirement. Any hints for this problem?
> > Regards.
> 
> I think the main reason for gcc/g++-4.8 is to avoid possible compilation errors if compiled using higher gcc/g++ versions.
> 
> Currently we are working to fix them (if any) for ubuntu （18.04+）with gcc-7.5 & c++14. Once completed, the gcc/g++-4.8 requrements should be removed.
> 
> Also cc @diegohu

Today the master branch has been updated with **ubuntu-18.04+gcc-7.5** support.  gcc/g++-4.8 can be deleted now.

**Comment by hongyi-zhao** [comment]
Next step, I expect apollo can support up to the latest stable version of gcc/g++.

**Comment by storypku** [comment]
> Good news. Next step, I expect apollo can support up to the latest stable version of gcc/g++.

Haha, hopes that we can meet you expectation.

**Comment by hongyi-zhao** [comment]
> > Good news. Next step, I expect apollo can support up to the latest stable version of gcc/g++.
> 
> Haha, hopes that we can meet your expectation.

Should be *hope* here :-)
