### ISSUE TITLE
How to use bazel to build a module?

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#11650]
Such as : I want to modify the code in planning model, then I want to build this planning model to debug?
How to build this planning model only? 
or how to debug?
Any steps or specs links? thank you very much!

**Comment by storypku** [comment]
> Such as : I want to modify the code in planning model, then I want to build this planning model to debug?
> How to build this planning model only?
> or how to debug?
> Any steps or specs links? thank you very much!
Just run
```
bazel build -c gdb modules/planning/... 
```

where `-c dbg` means debug mode, see [bazel compilation mode](https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode).
