### ISSUE TITLE
Camera data to Perception module in Apollo 3.0

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#11656]
Hello,

How does the camera data from the LGSVL is sent as input to the perception module of Apollo 3.0? What is the mechanism? I could not find it in the documentation.
How can I use a real USB 3.0 camera (eg. LI-USB30-AR023ZWDRB) to send the captured data to the perception module of Apollo 3.0?

**Comment by daohu527** [comment]
## Processes
The whole process is like below:
```
hardware -> driver -> topic(network) -> perception module
      ↑                   ↑
    camera              lgsvl
```
1. Lgsvl capture the picture then sent the picture from network by publish the topic to perception module.  
2. Camera capture the picture by camera dirvers, and then publish the topic to perception module

**Comment by ashwinsarvesh** [comment]
Thank you for your answer
Can I use the cameras in this [link ](https://apollo.auto/platform/hardware.html) to place in front of the simulator and then send the captured data to the Apollo 3.0 perception module? Do these cameras have the drivers which you mentioned?

**Comment by daohu527** [comment]
Theoretically, the driver supports all USB cameras, in order to insure that you are best to use the specified model.

**Comment by ashwinsarvesh** [comment]
Oh, Is the driver which you mentioned is inside Apollo? and it supports USB cameras?

**Comment by ashwinsarvesh** [comment]
Is it [this ](https://github.com/ApolloAuto/apollo/tree/v3.0.0/modules/drivers/usb_cam)driver which you are talking about?

**Comment by daohu527** [comment]
Yes, it's.

**Comment by ashwinsarvesh** [comment]
Thank you
Just 1 LI-USB30-AR023ZWDRB camera is sufficient to send data to the Perception module or minimum 2 are required?

**Comment by daohu527** [comment]
Just one is OK, 6mm and 12mm cameras are used in different scenarios, usually 12mm is used for traffic lights, 6mm is used for obstacle perception.

**Comment by ashwinsarvesh** [comment]
ok, so we can use it for either traffic lights or obstacle detection at a time. Not for both simultaneously because they need different focal lengths.
Am I correct?

**Comment by ashwinsarvesh** [comment]
In this link(https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Guideline_sensor_Installation_apollo_3.0.md) it is mentioned as 3 cameras. So I was confused.
Also, 12mm is not mentioned. Only 6mm and 25mm is mentioned

**Comment by daohu527** [comment]
I'm not sure if your simulation environment can fully cover your camera. Cameras with different focal lengths have different FOV and viewing distance.

**Comment by ashwinsarvesh** [comment]
Ok. Apollo 5.0 requires 2 cameras to be synced with LiDAR frames?

**Comment by jp12AI** [comment]
@daohu527 I'm trying to configure apollo 3.0 camera settings to use my USB camera. However, the layout is much different than 5.0 to configure camera drivers. I update the .launch files to /dev/video2 but it gives me this error. It is very confusing as there are only three launch files. Is there another folder where I have to update this? What are the steps to set up the cameras correctly in 3.0? Apollo 3.0 only needs 3 cameras right since it doesn't have 360 vision? Any help would be greatly appreciated as this is very confusing. Thank you

**Comment by jp12AI** [comment]
![Screenshot from 2021-09-11 16-24-23](https://user-images.githubusercontent.com/58639429/132965869-0bbc52d8-87e2-439f-aa0e-27186eb0ae3a.png)
