### ISSUE TITLE
Is there any way to convert Apollo .xml files to .xodr format

### ISSUE THREAD

**Issue by whuxhzhang** [ApolloAuto/apollo#11653]
I have a Apollo HDMap with .xml format， now I want to thanslate it into a opendrive file.
Is there any way to convert Apollo .xml files to .xodr format?

**Comment by jinghaomiao** [comment]
@whuxhzhang thanks for your interests in Apollo. Apollo does not have the tool for the conversion. Should you have other questions, please feel free to raise issues here. Thanks!

**Comment by JackRen88** [comment]
@whuxhzhang 
Hello,how to get Apollo HDMap with .xml format,is there any  tool to convert Apollo .txt file to .xml file?
