### ISSUE TITLE
how to run a dreamland task

### ISSUE THREAD

**Issue by ZhangJian322920** [ApolloAuto/apollo#11661]
I use the latest fork code from Apollo to run the straight line task on dreamland and prompt that the compilation fails

![image](https://user-images.githubusercontent.com/50873982/86510429-1cd35980-be22-11ea-9e83-bfd8104b4077.png)

**Comment by unacao** [comment]
looks like a github timeout

**Comment by ZhangJian322920** [comment]
> 看起来像github超时
Yes,Could you tell me how to solve this

**Comment by unacao** [comment]
这不是我们能控制的，国内网络连接境外网站有时候就会有这样的问题。我们已经启用了proxy，但是没办法解决整体网络环境。可以在不同的时间尝试，或者使用我们境外的服务 https://azure.apollo.auto/
