### ISSUE TITLE
Some questions about the planning module.

### ISSUE THREAD

**Issue by LiJiangnanBit** [ApolloAuto/apollo#11662]
I have two questions about the planning module:
1. https://github.com/ApolloAuto/apollo/blob/20584e06fe6550e024e2ca5e4a52f07d876f721a/modules/planning/tasks/deciders/path_assessment_decider/path_assessment_decider.cc#L515
When checking if the path has collision, the four corner points of the vehicle are examined to see if they are inside any obstacle polygon. But what if there is a collision on the edges of the vehicle? 
2. 
When calculating the path using Piecewise Jerk Optimizer, the vehicle is considered as a point, and its position is bounded by the path bounds calculated in *PathBoundsDecider*. But if the geometry and the heading of the vehicle are neglected, I think the planned path may have collision sometimes, like the orange car below:
![image](https://user-images.githubusercontent.com/23288471/86533863-bf650880-bf06-11ea-96e8-910e5acefa19.png)
Can this happen when the vehicle is relatively large, or it's making a sharp turn?
Thanks.

**Comment by jmtao** [comment]
@LiJiangnanBit 
(1) that seems impossible.  We are checking four corner points of the ADC along the **entire path**. If the scenario you described has ever happened, that means prior to arriving that point, ADC must have hit the obstacle with its corner(s), and would return at that point. 
(2) when we calculate path bounds, we've already considered ADC width. And PieceWiseJerkPathOptimizer will consider heading of the ADC.

**Comment by LiJiangnanBit** [comment]
Thanks~
