### ISSUE TITLE
E: Unable to locate package linux-image-extra-4.4.32-apollo-2-RT

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#1169]
I installed the Ubuntu 14.04.3,and Apollo kernel.
Then I got this:
```
root@gengqx7050:/home/gengqx/apollo# bash docker/scripts/install_docker.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-extra-4.4.32-apollo-2-RT
E: Couldn't find any package by regex 'linux-image-extra-4.4.32-apollo-2-RT'
......
```
here is the bash caused this:
```
function install_docker_x86() {
  sudo apt-get -y install curl \
      "linux-image-extra-$(uname -r)" \
      linux-image-extra-virtual
```
if I install the  linux-image-extra-virtual seperatly:
```
root@gengqx7050:/home/gengqx/apollo# apt-get install linux-image-extra-virtual
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  linux-image-3.13.0-135-generic linux-image-extra-3.13.0-135-generic
  linux-image-generic
Suggested packages:
  fdutils linux-doc-3.13.0 linux-source-3.13.0 linux-tools
  linux-headers-3.13.0-135-generic
The following NEW packages will be installed:
  linux-image-3.13.0-135-generic linux-image-extra-3.13.0-135-generic
  linux-image-extra-virtual linux-image-generic
0 upgraded, 4 newly installed, 0 to remove and 478 not upgraded.
Need to get 52.1 MB of archives.
After this operation, 195 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
root@gengqx7050:/home/gengqx/apollo# 
```
Why is this kernel changed to 3.1.3,but the host kernel is 4.4.32
What is linux-image-extra-4.4.32-apollo-2-RT used for? And how Can I install it?

**Comment by quning78** [comment]
Please check the manual below about how to install kernel. 

https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_5_hardware_system_installation_guide.md#installing-the-software-for-the-ipc

For more info about Apollo Kernel, please checkout 

https://github.com/ApolloAuto/apollo-kernel

**Comment by gengqx** [comment]
@quning78 
First, I'm sorry for my ability to understand the whole apollo project.
Second,I'm sorry for my ambiguous sentence. I want to say "I have installed Ubuntu 14.4.03 and Apollo kernel' but I say 'I installed Ubuntu 14.4.03 and Apollo kernel'

But We all should admit that you are professional,and you have no problem to under standand the first  line show int the code:
```
root@gengqx7050:/home/gengqx/apollo# bash docker/scripts/install_docker.sh
```
What am I doing ??? I'm install docker !!! You got me !!! professor!!!
NO one would believe that you did understand this code in the bash code I have show,
```
"linux-image-extra-$(uname -r)" 
```
what  
```
uname -r 
```
get????
you could not belive
it got
``` 
4.4.32-apollo-2-RT
```
Then what does this mean????
Yeah, You get me again!!!

I have install Apollo kernel!!!

I'm sorry for my words again,but please Do not take all the guys as foolish. I admit that I'm foolish. I know everyone should thank you for all the work you have done for the open source ,The whole apollo team did not owe me. Due to the high price of the Baidu Stock,Robin Li would not expect that a support community would be a totally shit. I'm sorry for my bed temper,I'm not refer this to you,and Indeed I'm dispointment for the  whole community and I hope you have a wonderful day.
