### ISSUE TITLE
Perception module features of Apollo 3.0

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#11694]
Hello,

This is not an issue but it is my confusion.
This [link](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/perception_apollo_3.0.md) says the perception module does only Lane detection and Obstacle detection. Not traffic  light detection

But in this [link](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Apollo_3.0_Software_Architecture_cn.md), it says two important sub-modules in perception: obstacle detection and traffic light detection.

Can you clarify what the Perception module in Apollo 3.0 can actually do?

**Comment by jinghaomiao** [comment]
@ashwinsarvesh : Perception in Apollo 3.0 does lane detection, traffic light detection and obstacle detection as well. The lane detection only works for scenarios without HDMap. So they don't work together.

**Comment by jinghaomiao** [comment]
Hope your question is answered. Closing the ticket now. Please feel free to raise other issues if needed. Thanks for your interests in Apollo.
