### ISSUE TITLE
Perception deactivates itself after adding ros function

### ISSUE THREAD

**Issue by Basti110** [ApolloAuto/apollo#11693]
Hello,
I try to add a ROS Node to the perception Module to send the PerceptionObstacles with ROS and without bridge. Before, I tried a small Listener/Talker example with the PerceptionObstacle Type. This small example worked. So there is no problem with the ROS version. After that, i added the ROS dep "@ros//:ros_common" to the bazel build file. Until here the perception module is also working. 

But if I add the lines below to the fusion_component.cc init() function, the perception module doesnt work anymore. 

```
AINFO << "Try to init ROS";
std::string channel = "/apollo/ros/perception/obstacles";
std::map<std::string, std::string> remaps;
remaps["__name"] = "test_node";

ros::init(remaps, "ROS_Obstacles", (uint32_t)0); //<= Problem Line
```

The problem is, I cant find an error. There is no warning or crash report. Neither in the log files or in the terminal output when I start with cyber_start. In Dreamview, the module deactivates itself after a few seconds. I also cant find the print "Try to init ROS". The init function is never called. 

First questions:
How can I debug this specific problem? Why is the FusionComponent::Init() called when I add the ros::init

And my second question:
I cant find my std output and std error. Where are they piped to? 

### System information
- **Arch Linux**:
- **Apollo installed from LGSVL Repository**:
- **Apollo version 5.0**:

**Comment by jinghaomiao** [comment]
@Basti110 Thanks for using Apollo. Starting from 5.0, Apollo does not support ROS. Please seek help in ROS community.
