### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#11698]
Unable to build docker image 

### System information

- **Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 5.5**:

### Steps to reproduce the issue:
./build_dev.sh ./dev.x86_64.dockerfile 

Fails:
Step 6/35 : RUN bash /tmp/installers/install_adv_plat.sh
 ---> Running in 7ac432ae2381
--2020-07-07 20:34:41--  https://apollocache.blob.core.windows.net/apollo-cache/jsoncpp.zip
Resolving apollocache.blob.core.windows.net (apollocache.blob.core.windows.net)... failed: Name or service not known.
wget: unable to resolve host address 'apollocache.blob.core.windows.net'

Is there a newer version for install_adv_plat.sh?

**Comment by xiaoxq** [comment]
Yeah that one is kind of outdated. We are working hard on an env with a lot of upgrade:
https://github.com/ApolloAuto/apollo/blob/docker_dev/docker/build/dev.x86_64.dockerfile
It will be rolled out to master branch soon. Please stay tuned :)

**Comment by agarwalsid** [comment]
Thank you for the update @xiaoxq, looking forward to it.

**Comment by jinghaomiao** [comment]
Thanks for your interests in Apollo. Please raise new issues if you have any other questions.
