### ISSUE TITLE
About compatibility of packages for Apollo 5.5 with 5.0.

### ISSUE THREAD

**Issue by Doozua** [ApolloAuto/apollo#11707]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source or binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: Apollo 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Hi, I have two simple questions.

I'm using Apollo 5.0 (exactly r-5.0.0 what you are providing.)

Q1. Are the packages of Apollo 5.5 compatible with Apollo 5.0? like Fast-RTPS, osqp, qp-oases, pcl.

Q2. ApolloAuto had been providing packages through "apollocache.blob.core.window.net" with your '.install_~.sh' files. But I couldn't get some of packages through the site.  So I searched and I found out that ApolloAuto stopped providing the site to install packages anymore. Also, if Apollo users want to install the packages on arrch64, The only way to install the packages is using Docker.
Can you let me know how to install the dependency packages of Apolloauto 5.0 for aarch64 without docker?

Thank you in advance.

**Comment by storypku** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 16.04
> * **Apollo installed from (source or binary)**: source or binary
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: Apollo 5.0
> 
> ### Steps to reproduce the issue:
> * **Please use bullet points and include as much details as possible**:
> 
> Hi, I have two simple questions.
> 
> I'm using Apollo 5.0 (exactly r-5.0.0 what you are providing.)
> 
> Q1. Are the packages of Apollo 5.5 compatible with Apollo 5.0? like Fast-RTPS, osqp, qp-oases, pcl.
> 
> Q2. ApolloAuto had been providing packages through "apollocache.blob.core.window.net" with your '.install_~.sh' files. But I couldn't get some of packages through the site. So I searched and I found out that ApolloAuto stopped providing the site to install packages anymore. Also, if Apollo users want to install the packages on arrch64, The only way to install the packages is using Docker.
> Can you let me know how to install the dependency packages of Apolloauto 5.0 for aarch64 without docker?
> 
> Thank you in advance.
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):

The master branch has been updated recently. Maybe you can take a look on `fastrtps`, `osqp`, and `qp-oases` and `pcl`  installers in `docker/build/installers` directory and get some hint.

**Comment by Doozua** [comment]
Thank you for fast answering. And can you let me know about my first question?

For example qt, what in Apollo/auto master branch(5.5) providing is 'qt 5.12.2'.
But Apollo 5.0 is providing 'qt 5.5.1'.

If I use 'qt 5.12.2' with apollo 5.0, is it operated well?
Not only qt, but also all other packages of 5.5 including what I didn't mention are compatible with 5.0?

Please let me know which packages are compatible or which are not.

Thank you.

**Comment by storypku** [comment]
> Thank you for fast answering. And can you let me know about my first question?
> 
> For example qt, what in Apollo/auto master branch(5.5) providing is 'qt 5.12.2'.
> But Apollo 5.0 is providing 'qt 5.5.1'.
> 
> If I use 'qt 5.12.2' with apollo 5.0, is it operated well?
> Not only qt, but also all other packages of 5.5 including what I didn't mention are compatible with 5.0?
> 
> Please let me know which packages are compatible or which are not.
> 
> Thank you.

I am not familiar with apollo 5.0.  Maybe others can help on this question. @xiaoxq @ycool 

Could you plz tell me the reason  you "stick to" Apollo 5.0 ?

**Comment by Doozua** [comment]
Okay you asked me why I "stick to" Apollo 5.0, I'm gonna answer detail about it. 
So, please solve my curiosities :)

I'm just a person who is interested a lot about Autonomous Car. I studied Autoware first, but at the time, Autoware used ROS1.
However, I found that Apollo developed cyberRT for RT communication. And I made up my mind to study Apollo.(And that time, Apollo 5.0 was the latest version.)
So I studied and tested on PC in docker environment with LG-SVL simulator using Apollo 5.0.

Recently, I wanted to use Apollo out of PC. So I bought Raspberry Pi 4.
I know I can't use the full functions of Apollo providing. But the RPi 4 is the cheapest SBC.
(As I mentioned as above, I'm just a person who studying hard Apollo, So I can't buy expensive things.)

And it's aarch64 based. So I just wanna test some modules on RPi 4 without docker.

But as I asked first, Apollo 5.5 is not supporting aarch64 without docker.
Plus, some packages like Qt are not supported even with docker.

I found this in the master branch.
```
if [[ "${TARGET_ARCH}" != "x86_64" ]]; then
    error "Qt installer for ${TARGET_ARCH} not ready."
    exit 0
fi
```

In addition, Apollo 5.0 doesn't support to install some packages anymore. Because "apollocache.blob.core.window.net" is not supported.

That's why I asked 5.5 packages are compatible with 5.0.
Also, why I asked how to install packages and test Apollo 5.0 in aarch64 without docker environment.

All I want to do is to install Apollo 5.0 and run & test some modules on aarch64 with non-docker.

Could you please help me?

**Comment by storypku** [comment]
Thank you for your details. 

Recently, we have rolled out master with a lot of updates (bazel : 0.5.3 -> 3.2.0+, gcc: 4.8.5 -> 7.5 with c++ 14 support, python: 2.7 -> 3.6, clean and runable Dockerfile, enhanced gpu support, etc...). 

For aarch64, we have successfully built cyber docker images ( `cyber-aarch64-18.04-20200706_0140` for cpu-only, `cyber-x86_64-18.04-20200707_1716` for nVidia Jetson series). Although `dev.aarch64` docker image was not ready yet, installing them using installers in `docker/build/installers` will be relatively easy.

To use Apollo out of docker, just follow the steps how our cyber/dev image was built by running the installers. And this is only possible with the master branch currently.
  
Apollo use Qt only for building `cyber_visualizer`. So if you don't need cyber_visualizer, Qt is not needed.  If you do need Qt, there are system packages provided by ubuntu distribution for the `arm64` architecture. We installed higher Qt version with two things in concern: 1) some  packages provided by third_party partners need the higher Qt version 2) we don't want to install system Qt as it will introduce a lot of dependencies and thus increasing docker image size.
For aarch64, there seems no requirement for higher Qt versions previously, so we didn't see any need to prepare Qt installer for aarch64 ... Sorry about that.
Although LG-SVL simulator may not support the latest Apollo master yet, we are working on to re-bring the support back in the near future.

Besides, we are planning to build CPU and GPU versions of Apollo docker images, including {x86_64,aarch64}x{cpu,gpu}. Although it may need some time to come out, it's in our roadmap. And to build and run as many modules as possible in CPU-only mode. 

So, please stay tuned, and ask for help any time you feel the need.

Thank you for supporting Apollo! Wish you a pleasant journey.

**Comment by Doozua** [comment]
Thank you for your kind answer.

It would be helpful for me.

I will keep getting a interest in ApolloAuto.

Thank you!
