### ISSUE TITLE
how to add vehicle in dream view?

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#11709]
I did all the steps given in https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_vehicle.md to add a new vehicle but in dreamview it only shows the vehicle name "Mkz example". so how to add our own new vehicle to dream view after adding new vehicle to apollo. (which will be further used for vehicle calibration table).

NOTE: apollo 3.5

**Comment by daohu527** [comment]
## Dreamview conf
The config to select a car in dreamview is in the path "apollo/modules/dreamview/conf/hmi_modes". It is used for user-defined startup module config. For example
```
cyber_modules {
  key: "Camera"
  value: {
    dag_files: "/apollo/modules/drivers/camera/dag/camera.dag"
    dag_files: "/apollo/modules/drivers/video/dag/video.dag"
  }
}
cyber_modules {
  key: "Canbus"
  value: {
    dag_files: "/apollo/modules/canbus/dag/canbus.dag"
  }
}
cyber_modules {
  key: "Control"
  value: {
    dag_files: "/apollo/modules/control/dag/control.dag"
  }
}
...
...
```
You will see "Camera", "Canbus", "Controls" etc. tabs in Dreamview UI.

## canbus
As the car is add in canbus module. In fact, as long as the canbus module can be started, you do not need to create a new configuration.

If you want a new conf, you can follow the conf in "apollo/modules/dreamview/conf/hmi_modes" to write a new one.

**Comment by Addi2020** [comment]
@daohu527 .. got it . The car is already added in canbus module.
