### ISSUE TITLE
Docker image build fails on Step 11/18

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#11710]
**Describe the bug**
Docker image fails on Ubuntu 18.04 with recent master

Step 11/18 : RUN bash /tmp/installers/install_common_modules.sh ${INSTALL_MODE}
 ---> Running in ada2f6cffad6
[INFO] Install support for [modules/common] ...
[INFO] Install osqp ...
[INFO] Start to download osqp-0.5.0.tar.gz from https://github.com/oxfordcontrol/osqp/archive/v.tar.gz ...
--2020-07-08 15:15:42--  https://github.com/oxfordcontrol/osqp/archive/v.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/oxfordcontrol/osqp/tar.gz/v [following]
--2020-07-08 15:15:42--  https://codeload.github.com/oxfordcontrol/osqp/tar.gz/v
Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-08 15:15:43 ERROR 404: Not Found.

**To Reproduce**

Run ./build_dev.sh -f ./dev.x86_64.dockerfile -g us

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version : Apollo 5.5 recent master

**Comment by agarwalsid** [comment]
Resolution - Line 33
- DOWNLOAD_LINK="https://github.com/oxfordcontrol/osqp/archive/v${VERSION}.tar.gz"
+ DOWNLOAD_LINK="https://github.com/oxfordcontrol/osqp/archive/v${OSQP_VER}.tar.gz"

**Comment by agarwalsid** [comment]
Successfully built a docker image for x_86 on Ubuntu 18.04. The size of the new built image is 12.5 GB vs 12.7 GB of the dev-x86_64-18.04-20200707_2131 image that is provided by Apollo. Are we missing something in the build?

**Comment by storypku** [comment]
> Successfully built a docker image for x_86 on Ubuntu 18.04. The size of the new built image is 12.5 GB vs 12.7 GB of the dev-x86_64-18.04-20200707_2131 image that is provided by Apollo. Are we missing something in the build?


> Resolution - Line 33 of install_osqp.sh
> 
> * DOWNLOAD_LINK="[https://github.com/oxfordcontrol/osqp/archive/v${VERSION}.tar.gz](https://github.com/oxfordcontrol/osqp/archive/v$%7BVERSION%7D.tar.gz)"
> 
> * DOWNLOAD_LINK="[https://github.com/oxfordcontrol/osqp/archive/v${OSQP_VER}.tar.gz](https://github.com/oxfordcontrol/osqp/archive/v$%7BOSQP_VER%7D.tar.gz)"

1) Good catch of osqp version. 
2) About image size. The dev-x86_64-18.04-20200707_2131 image was built on top of another dev image with pcl re-installed. So it's image size was 0.2GB bigger. This can be seen from `docker history` output.

```
$ docker history apolloauto/apollo:dev-x86_64-18.04-20200707_2131
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6079e53b6dea        18 hours ago        /bin/sh -c rm -rf /tmp/installers/              0B                  
99ef3bd07cfa        18 hours ago        /bin/sh -c bash /tmp/installers/install_pcl.…   162MB               
afc9414a163a        18 hours ago        /bin/sh -c rm -rf /opt/apollo/sysroot/includ…   264kB               
13322490a643        18 hours ago        /bin/sh -c #(nop)  USER root                    0B                  
4edfb9fe79de        18 hours ago        /bin/sh -c #(nop) WORKDIR /apollo               0B                  
081124917836        18 hours ago        /bin/sh -c #(nop) COPY file:36f3bba3cbd51e1f…   1.14kB              
71ca7f76e019        18 hours ago        /bin/sh -c #(nop) COPY file:3d76aa8206205a9a…   3.08kB              
3eeb1c2e186d        18 hours ago        /bin/sh -c #(nop) COPY file:00e7242b0d5f0af8…   5.99kB              
66ab196b8925        18 hours ago        /bin/sh -c #(nop)  ENV DEBIAN_FRONTEND=nonin…   0B                  
4f4394821261        21 hours ago        |3 BUILD_STAGE=dev GEOLOC=us INSTALL_MODE=do…   0B                  
03da925dbdaa        21 hours ago        |3 BUILD_STAGE=dev GEOLOC=us INSTALL_MODE=do…   118MB               
```

**Comment by agarwalsid** [comment]
Thank you for the info about the error and docker image @storypku, very helpful!
