### ISSUE TITLE
apollo-kernel and its suported Ubuntu version.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#11739]
Hi,

See [here](https://github.com/ApolloAuto/apollo-kernel/issues/29) for more info on this question. Any hints will be highly appreciated.

Regards,
HY

**Comment by storypku** [comment]
we have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. Please follow these docs to install PREEMPT/PREEMPT_RT kernels for Apollo. 

Thank you.

**Comment by hongyi-zhao** [comment]
Thanks a lot. I'll try according to the latest installation guide and give feedback on any problems/comments/notes/experiences.
