### ISSUE TITLE
How Can I save the modification in dev docker

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#1174]
I found that If I modify the environment variable like PATH，When I exit the docker dev，and I into dev again，It would not be saved.How can I save it. Thank you.

**Comment by Capri2014** [comment]
@gengqx This might help answer your question, credit to stackoverflow. https://stackoverflow.com/questions/27093612/in-a-dockerfile-how-to-update-path-environment-variable

**Comment by yongyuandeyezi** [comment]
@gengqx 请问您是怎么解决这个问题的，谢谢！
