### ISSUE TITLE
spiral reference line smoother optimization failed

### ISSUE THREAD

**Issue by JackRen88** [ApolloAuto/apollo#11756]
Hello.
when I run the spiral reference line smoother  and perform ipopt optimization solution,the program terminates and dies.How to solve this problem.

**Comment by JackRen88** [comment]
That's very strange.when running  spiral reference_line_smoother_test ,everything is ok!

**Comment by jmtao** [comment]
@JackRen88 it's hard for us to reproduce it. Can you please try debugging the coredump file?

**Comment by jmtao** [comment]
Hi @JackRen88 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
