### ISSUE TITLE
Error launch rtk_localization

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11767]
When I launch localization - I get error

![Screenshot from 2020-07-13 15-15-28](https://user-images.githubusercontent.com/61351599/87303378-c057f480-c51b-11ea-836d-b16cf93e65ec.png)

**Comment by storypku** [comment]
It's a bug, and thank you for reporting.
It will be fixed in #11770 .

You can run the following command to rebuild and launch it again. It should be OK.

```
bazel build //modules/localization/rtk/...

cyber_launch start /apollo/modules/localization/launch/localization.launch
```

**Comment by AlexandrZabolotny** [comment]
I have followed your recommendations but am getting a new error

![Screenshot from 2020-07-13 17-35-53](https://user-images.githubusercontent.com/61351599/87317247-6b25de00-c52f-11ea-8bed-c70addd82f67.png)

**Comment by storypku** [comment]
Try running `bazel build //cyber/tools/cyber_launch`.

**Comment by AlexandrZabolotny** [comment]
After fixing the bug, the module starts.
But I found another similar error.

https://github.com/ApolloAuto/apollo/issues/11793
