### ISSUE TITLE
how to build on nvidia jetson AGX xavier

### ISSUE THREAD

**Issue by zhangxingjing** [ApolloAuto/apollo#11761]
#11513 # System information

- **OS Platform and Distribution **: nvidia jetson AGX xavier, ubuntu 18.04
- **Apollo installed from **: from docker image:cyber-aarch64-18.04-20200703_2150
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: apollo branch master 

### Steps to reproduce the issue:
1,run docker/script/cyber_start.sh
2,run docker/script/cyber_into.sh
3,run apollo.sh build

When I build Apollo in docker, it reminds me that it lacks many dependencies, so I installed various dependencies according to  the sh files of /apollo/docker/build/installers/ , but some libraries couldn't be installed with install_*.sh, for example, qp_oases, PCL, QT and so on, I download the source code of these libraries from the Internet to compile, and moved the compiled files into /usr/local/lib as in the sh file showed , and then compilation will still prompt can not find these dependent libraries, so I would like to ask if there is a faster or easier way to install Apollo under the arm architecture.

by the way , I can build some module singlely by use ./apollo.sh build <module name>, like contrib,data,v2x,transform,moniter,guardian,calibration,third_party_perception, but I cant build any other module by use this method, because lack of dependencies.
### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2020-07-13 18-10-07](https://user-images.githubusercontent.com/29945660/87293028-4aac5280-c534-11ea-8b12-f830aa555d2b.png)
![Screenshot from 2020-07-13 18-09-48](https://user-images.githubusercontent.com/29945660/87293037-4e3fd980-c534-11ea-8f33-121efbfa1023.png)
![Screenshot from 2020-07-13 18-09-32](https://user-images.githubusercontent.com/29945660/87293043-50099d00-c534-11ea-9c29-eee0356b2a61.png)

**Comment by storypku** [comment]
> #11513 # System information
> 
> * **OS Platform and Distribution **: nvidia jetson AGX xavier, ubuntu 18.04
> * **Apollo installed from **: from docker image:cyber-aarch64-18.04-20200703_2150
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: apollo branch master
> 
> ### Steps to reproduce the issue:
> 1,run docker/script/cyber_start.sh
> 2,run docker/script/cyber_into.sh
> 3,run apollo.sh build
> 
> When I build Apollo in docker, it reminds me that it lacks many dependencies, so I installed various dependencies according to the sh files of /apollo/docker/build/installers/ , but some libraries couldn't be installed with install_*.sh, for example, qp_oases, PCL, QT and so on, I download the source code of these libraries from the Internet to compile, and moved the compiled files into /usr/local/lib as in the sh file showed , and then compilation will still prompt can not find these dependent libraries, so I would like to ask if there is a faster or easier way to install Apollo under the arm architecture.
> 
> by the way , I can build some module singlely by use ./apollo.sh build , like contrib,data,v2x,transform,moniter,guardian,calibration,third_party_perception, but I cant build any other module by use this method, because lack of dependencies.
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):
> ![Screenshot from 2020-07-13 18-10-07](https://user-images.githubusercontent.com/29945660/87293028-4aac5280-c534-11ea-8b12-f830aa555d2b.png)
> ![Screenshot from 2020-07-13 18-09-48](https://user-images.githubusercontent.com/29945660/87293037-4e3fd980-c534-11ea-8f33-121efbfa1023.png)
> ![Screenshot from 2020-07-13 18-09-32](https://user-images.githubusercontent.com/29945660/87293043-50099d00-c534-11ea-9c29-eee0356b2a61.png)

This reason for this issue is that our `dev.aarch64` docker image was not ready. 
And cyber.{aarch64,x86_64} docker images was only used to build and test and run our CyberRT module.
As other modules (planning, prediction, planning, control) has various dependencies not available in the cyber image, the build will surely fail.

Thank you for your attention to Apollo. And hopes that our dev.aarch64 image would be ready in the next few months.

**Comment by zhangxingjing** [comment]
@storypku Thank you for your reply!I noticed that your low-speed kit is installed on TX2. Can I install the low-speed version of apollo on TX2 by myself?

**Comment by storypku** [comment]
> @storypku Thank you for your reply!I noticed that your low-speed kit is installed on TX2. Can I install the low-speed version of apollo on TX2 by myself?

You mean D-Kit ? Maybe @diegohu could help on that.

**Comment by zhangxingjing** [comment]
@storypku yap, D-kit

**Comment by diegohu** [comment]
@zhangxingjing D-KIT is installed on X86 based IPC, not TX2.

**Comment by zhangxingjing** [comment]
@diegohu Oh,I made a mistake,maybe It is low speed micro vehicle kit.

**Comment by diegohu** [comment]
> low speed micro vehicle kit.

Yeap, Micro-KIT is installed on TX2. However, It only supports navigation mode based on Apollo 3.0 and I don't think it's an open source version.

**Comment by zhangxingjing** [comment]
@diegohu Ok，thank you very much!

**Comment by storypku** [comment]
@zhangxingjing It seems that your question was resolved, and I am going to close this issue now. If you have other questions, feel free to create another issue. Thanks for supporting Apollo.
