### ISSUE TITLE
Does apollo have dependence on qt and its version?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#11762]
Hi,

Does apollo have dependence on qt? If so, what's the version requirement of qt?

**Comment by storypku** [comment]
> dence on qt? If so, what's the version requirement of qt?

Yes,  `cyber_visualizer` was dependent on Qt. And one third_party module under `third_party/camera_library` have a dependency over `Qt5.12.2`, but it was disabled by default. So, as long as cyber_visualizer can be built and runnable, any Qt version is OK.

**Comment by hongyi-zhao** [comment]
Some further questions relative to this issue: It's well known that apollo is running in docker, does this mean that all dependencies are installed in the docker container or still it needs the dependencies are installed for the host OS where the docker is running?

**Comment by storypku** [comment]
> > Yes, cyber_visualizer was dependent on Qt.
> 
> Some further questions relative to this issue: It's well known that apollo is running in docker. Does this mean that all dependencies should be installed in the docker container or still all of them need to be installed for the host OS where the docker is running? More specifically, say, gcc, python3 and qt are some dependencies, but it seems that the gcc is only needed for building the apollo and it should be enough to only install it on the host OS, while for other stuff, should I still need to install them into the docker environment also?
> 
> > And one third_party module under third_party/camera_library have a dependency over Qt5.12.2,
> 
> Why let it dependent on a so specific version instead of more general version ranges same to cyber_visualizer?
> 
> Regards,
> HY

1) Apollo should be OK running on host ubuntu systems ( 18.04 preferably) as long as you follow all the steps our docker image was built by running the installer scripts under `docker/build/installers`.
docker was only intended to provide a "clean" environment for our team to test features or reproduce bugs in a `controlled` way.

2) Qt `5.12.2` was an `LTS` version, and we provide it for two reasons:  i) We don't want to install the relatively old Qt version ubuntu provides with a lot of dependencies (which may significantly increase our docker image size)  ii) It is said that Qt versions >= 5.12.2 should be OK for that module to work.

**Comment by hongyi-zhao** [comment]
>     1. Apollo should be OK running on host ubuntu systems ( 18.04 preferably) 

I want to try Ubuntu 20.04 LTS using apollo master/current release versions on the apollo development kit hardware platform which my group has purchased. Any hints/cautions/pitfalls for this job?

Should I use docker based method or directly install it on the host Ubuntu system?

> as long as you follow all the steps our docker image was built by running the installer scripts under `docker/build/installers`.

There are so many scripts there, I really still not so clear on the correct order to use them for installation on the host Ubuntu system without bothering the docker.

>        docker was only intended to provide a "clean" environment for our team to test features or reproduce bugs in a `controlled` way.

Thanks for pointing this out, I really not realize this till I read your comments here.

**Comment by storypku** [comment]
> > ```
> > 1. Apollo should be OK running on host ubuntu systems ( 18.04 preferably) 
> > ```
> 
> I want to try Ubuntu 20.04 LTS using apollo master/current release versions on the apollo development kit hardware platform which my group has purchased. Any hints/cautions/pitfalls for this job?

1) gcc9: there may be some compilation errors. Please report issues if you encounter them.
2) adapt  `.apollo.bazelrc` (under `${APOLLO_ROOT_DIR}`) to accord with your local env

```
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda-10.2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.0,6.1,7.0,7.2,7.5"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-7"
``` 
3) Pay attention to apt sources.list  difference.

> 
> Should I use docker based method or directly install it on the host Ubuntu system?
> 

You can try them both: Use docker as the develop env to reproduce and track errors, and deploy to the host system for production.

> > as long as you follow all the steps our docker image was built by running the installer scripts under `docker/build/installers`.
> 
> There are so many scripts there, I really still not so clear on the correct order to use them for installation on the host Ubuntu system without bothering the docker.

Take a look at [cyber.x86_64.dockerfile](https://github.com/ApolloAuto/apollo/blob/master/docker/build/cyber.x86_64.dockerfile)
and [dev.x86_64.dockerfile](https://github.com/ApolloAuto/apollo/blob/master/docker/build/dev.x86_64.dockerfile).

The same applies to [cyber.aarch64.dockerfile](https://github.com/ApolloAuto/apollo/blob/master/docker/build/cyber.aarch64.dockerfile) (beta)

and dev.aarch64.dockerfile (Not ready yet).

> 
> > ```
> >    docker was only intended to provide a "clean" environment for our team to test features or reproduce bugs in a `controlled` way.
> > ```
> 
> Thanks for pointing this out, I really not realize this till I read your comments here.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your instructions. But [Set-up-the-Docker-environment](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#Set-up-the-Docker-environment) is still a required step noted in the quickstart and the [installation progress instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md#how-to-build-and-release-your-docker-container). 

I mean that I still cannot find any complete installation instructions for the non-docker based instructions in the repo's online documents.

**Comment by storypku** [comment]
> Thanks a lot for your instructions. But [Set-up-the-Docker-environment](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#Set-up-the-Docker-environment) is still a required step as noted in the quickstart and the [installation progress instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md#how-to-build-and-release-your-docker-container).
> 
> That is to say, I still cannot find any complete installation guide for the host OS only case in the repo's online documents.

I'm afraid the installation guide for the host OS  won't  be  online for the near future. Enabling it by default means we have to deal with the complexity of  our users' host environment and handle issues therefore.

**Comment by storypku** [comment]
This issue is going to be closed. Please create another issue if you have other questions.

Thanks for using Apollo!
