### ISSUE TITLE
downgrade cuda driver

### ISSUE THREAD

**Issue by yiakwy** [ApolloAuto/apollo#1178]
Hello I am using NVIDIA GTX driver of which the version is 375.51  greater than the suggested version 375.39. Hence I am reluctant to downgrade my cuda version driver partially because: 

1) I have to stop others cuda programmes from other teams before installing the old version of GPU driver
2) Old version might bring some troubles to my group.

If possible I want to install a new cuda libarary instead. Please tell me what version I need to install?

> F1109 21:07:39.868245 14279 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version

**Comment by yangkairui07** [comment]
@yiakwy  right now we use "NVIDIA-Linux-x86_64-375.39.run".

**Comment by yiakwy** [comment]
@yangkairui07 we prefer to use existing driver 375.51 in the cluster. Since the dockerfile has been removed please tell me how to uninstall cuda libraries needed in docker. I am trying to find matched version cuda lib for our driver. Thanks!

**Comment by yiakwy** [comment]
If you have some assertion to check the version of cuda, I want to try delete them and restart perception module offline.

**Comment by layssi** [comment]
@yiakwy   I also have the same problem with this version. I did everything possible to get the "NVIDIA-Linux-x86_64-375.39" to run on my machine but it seems to be incompatible with my configuration and my display will not start if I use it (even with a patch). Is there a specific reason that we can only run thus version?

**Comment by yiakwy** [comment]
@yangkairui07 @layssi  I have submit a patch perfectly solve the problem. Please review. @layssi you can check my branch/CentOS_gpu_enabled
