### ISSUE TITLE
Apollo demo has no perception?

### ISSUE THREAD

**Issue by kdheejb7** [ApolloAuto/apollo#11783]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hello, I'm a user of Apollo.
I built the demo of Apollo(r5.5.0 branch), and checked the dreamview simulation.

In the demo version, is there any real-time perception?
or the demo version just plays the record file(demo_3.5.record) without real-time perception?  

Thank you.

**Comment by kdheejb7** [comment]
Oh, I'm sorry, I found the same question in the issues.
Thank you.

**Comment by kdheejb7** [comment]
Oh, I'm sorry, I found the same question in the issues.
I knew that the demo version is the only visualization.

How can I simulate the sample(?) perception in these codes?
I want to check the real-time perception.

**Comment by Capri2014** [comment]
As of now, the demo simulation only supports the perfect perception. (No real perception-in-loop). If you want to test your own perception algorithm, you may need a record with raw sensor data. (Lidar, camera, tf, localization etc)

**Comment by kdheejb7** [comment]
Is there any raw sensor data that Apollo offers?

**Comment by daohu527** [comment]
No you can't, we will publish a new record file for perception test soon. you can follow it
