### ISSUE TITLE
Error launch perception module

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#11793]
When I run cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch
I get this error

![Screenshot from 2020-07-15 09-59-58](https://user-images.githubusercontent.com/61351599/87514015-442bf100-c682-11ea-87da-230a22183cfe.png)

**Comment by jeroldchen** [comment]
Hi @AlexandrZabolotny , for the latest code, only lidar perception module can be launched. You can launch lidar perception by running `cyber_launch start /apollo/modules/perception/production/launch/perception_lidar.launch`.

**Comment by AlexandrZabolotny** [comment]
> Hi @AlexandrZabolotny , for the latest code, only lidar perception module can be launched. You can launch lidar perception by running `cyber_launch start /apollo/modules/perception/production/launch/perception_lidar.launch`.

I have next error now  

![Screenshot from 2020-07-15 14-23-23](https://user-images.githubusercontent.com/61351599/87657073-ffc45200-c762-11ea-9948-a2c349e3e571.png)

**Comment by jeroldchen** [comment]
@AlexandrZabolotny  Have you launched transform module before perception? You can launch it by turning on the transform button on module controller of dreamview, or running `cyber_launch start /apollo/modules/transform/static_transform.launch`. And remember to select a vehicle on dreamview panel at first.
