### ISSUE TITLE
Cannot find proj4 although install and link successfully.

### ISSUE THREAD

**Issue by Doozua** [ApolloAuto/apollo#11807]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Hi.

An error occurs while build some of modules needed proj4 like gnss, routing although I installed and built well it.

I entered **sudo bazel build //modules/drivers/gnss/...** at ~/apollo

And the error message is "**ERROR: (time of pc) /home/user/apollo/modules/drivers/gnss/parser/BUILD:15:1: no such package '@proj4//': Prefix proj.4.-4.9.3 was given, but not found in the zip and referenced by '//modules/drivers/gnss/parser:data_parser**'."

I installed with proj4.sh what you providing.
(https://github.com/ApolloAuto/apollo/commit/0986060252e9457d24f93238402caf35efd00775)

I could see the message "Successfully built proj4. version=4.9.3"

Also, there are all of the output files of .sh at '/usr/local/proj4'.

Plus, I added the location of the libraries with "export" to link. (I did all of things what I can do with this .sh files - https://github.com/ApolloAuto/apollo/commit/0986060252e9457d24f93238402caf35efd00775 )

I don't know that mean of  "Prefix proj.4.-4.9.3 was given, but not found in the zip". I checked the zip file exists or not in /home/tmp, and It exists as 'proj.4-4.9.3.zip'.

How can I fix this problem without using docker?

I'm using x86 not aarch64 at this time.

**Comment by Doozua** [comment]
Then 'Permission denied' error occurs mkdir('/home/user/.cache/bazel/_bazel_apollo')

**Comment by storypku** [comment]
> Then 'Permission denied' error occurs mkdir('/home/user/.cache/bazel/_bazel_apollo')

It seems you are trying to install `proj4` with installer from branch `docker_dev`, and use it in Apollo 5.0 ?

**Comment by Doozua** [comment]
Yes I'm using Apollo 5.0. Do you have solution for it?

**Comment by storypku** [comment]
> Yes I'm using Apollo 5.0. Do you have solution for it?

For r5.0.0: please download and place [proj.4-4.9.3.zip](https://download.osgeo.org/proj/proj-4.9.3.zip) under `/home/tmp/`, and try again.

**Comment by Doozua** [comment]
I did it already. The first time I did is that... But it did't work.

My environment is x86, without docker, Ubuntu 16.04, Apollo 5.0.

**Comment by storypku** [comment]
> I did it already. The first time I did is that... But it did't work.
> 
> My environment is x86, without docker, Ubuntu 16.04, Apollo 5.0.

Sorry, we didn't provide support for Apollo outside docker. Please check out the latest `master` or the `r5.5.0` branch to see if it is already fixed.

And this issue is going to be closed.  Please create another issue if you have other questions.

Thanks for using Apollo!
