### ISSUE TITLE
traffic light detection dataset download

### ISSUE THREAD

**Issue by luqioayun** [ApolloAuto/apollo#11810]
Hello， could you please give me a link that can download traffic light detection dataset? I'm doing some research about Chinese traffic light detection, but there is no large-scale datasets. I'm from Beijing University of Posts and Telecommunications.
Thanks a lot!

E-mail: 1182102020@qq.com

**Comment by michael4338** [comment]
I'm afraid apollo does not have a particular "traffic light" dataset open for download, but you can try to dig further on datasets here http://apolloscape.auto/#

**Comment by luqioayun** [comment]
ok, i see. Thanks a lot~
1、I have scanned the introduction of apollo, and if I want to use the dataset for the object detection, what I need do?
Is the link of "https://apollo.auto/" the apollo entrance? If it is, why I don't find the dataset that can be downloaded?
2、the github link "https://github.com/ApolloAuto/apollo" is the instructions for use of apollo platform， could you please tell me the other method that can get dataset without setup apollo as the github link"https://github.com/ApolloAuto/apollo".
3、thanks your advice of the datasets&nbsp;http://apolloscape.auto/#, but it is the 3D Lidar Object Detection data.



祝您身体健康，工作顺利~


鲁巧芸
北京邮电大学
Tel：18612146135
E-mail:1182102020@qq.com
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ApolloAuto/apollo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 凌晨0:54
收件人:&nbsp;"ApolloAuto/apollo"<apollo@noreply.github.com&gt;;
抄送:&nbsp;"鲁巧芸"<1182102020@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ApolloAuto/apollo] traffic light detection dataset download (#11810)





 
I'm afraid apollo does not have a particular "traffic light" dataset open for download, but you can try to dig further on datasets here http://apolloscape.auto/#

**Comment by michael4338** [comment]
Hi, as mentioned http://apolloscape.auto/# is the place to get and download the dataset, apollo.auto or apollo github project does not provide data download services.  We may plan to open services in new channels to provide more data display/download in the future, @diegohu what do you think?
But currently I'm closing this one and please feel free to reopen if you need more information.

**Comment by diegohu** [comment]
yes @michael4338 ,you are right.
