### ISSUE TITLE
Nvidia_driver_not_detected by apollo.sh

### ISSUE THREAD

**Issue by Jelvon** [ApolloAuto/apollo#11814]
About the Nvidia-docker problem
Issue: 
We already strictly follow the tutorials to install the Nvidia-driver (430.5) in the host machine 
and also the Nvidia-docker (using the scripts in the https://github.com/ApolloAuto/apollo/tree/r5.5.0/docker/setup_host). 

when we pull the docker image, it showed like this:

[WARNING] nvidia-docker is in deprecation!
[WARNING] Please install latest docker and nvidia-container-toolkit:

and when we used nvidia-smi to check the availability of nvidia drivers both in the local and the container. They both delivered a positive result.
**➜  ~ nvidia-smi
Thu Jul 16 11:59:48 2020**       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:06:00.0  On |                  N/A |
|  0%   27C    P8     4W / 250W |    437MiB /  7974MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1706      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1736      G   /usr/bin/gnome-shell                          50MiB |
|    0      1943      G   /usr/lib/xorg/Xorg                           166MiB |
|    0      2071      G   /usr/bin/gnome-shell                          78MiB |
|    0      2394      G   /opt/teamviewer/tv_bin/TeamViewer             11MiB |
|    0      5933      G   ...quest-channel-token=7615111884222666551   108MiB |
+-----------------------------------------------------------------------------+
**root@in_dev_docker:/apollo# nvidia-smi
Thu Jul 16 12:00:47 2020**       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:06:00.0  On |                  N/A |
|  0%   26C    P8     5W / 250W |    437MiB /  7974MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1706      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1736      G   /usr/bin/gnome-shell                          50MiB |
|    0      1943      G   /usr/lib/xorg/Xorg                           166MiB |
|    0      2071      G   /usr/bin/gnome-shell                          78MiB |
|    0      2394      G   /opt/teamviewer/tv_bin/TeamViewer             11MiB |
|    0      5933      G   ...quest-channel-token=7615111884222666551   108MiB |
+-----------------------------------------------------------------------------+

But when we want to use the ./apollo_opt_gpu.sh to compile the repository. The shell could not find the gpu driver. so it showed like this: 

root@in_dev_docker:/apollo# ./apollo.sh build_opt_gpu
System check passed. Build continue ...
Running build under CPU mode. No GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC --output_user_root=/apollo/.cache/bazel
[INFO] Building on x86_64...
[INFO] Building with --jobs=8 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC --output_user_root=/apollo/.cache/bazel
INFO: (07-16 10:02:59.644) Found 7459 targets...
INFO: (07-16 10:03:12.603) From Compiling modules/bridge/common/util.cc:
modules/bridge/common/util.cc: In function 'int apollo::bridge::GetProtoSize(const char*, size_t)':

Anyone could help solve the driver_not_detected problem?

**Comment by FengIvex** [comment]
**nvidia-smi** works 
but **sudo dpkg --list | grep nvidia*** does not work.

**Comment by storypku** [comment]
> About the Nvidia-docker problem
> Issue:
> We already strictly follow the tutorials to install the Nvidia-driver (430.5) in the host machine
> and also the Nvidia-docker (using the scripts in the https://github.com/ApolloAuto/apollo/tree/r5.5.0/docker/setup_host).
> Anyone could help solve the driver_not_detected problem?
So the branch involved is `r5.5.0` ?

**Comment by FengIvex** [comment]
> > About the Nvidia-docker problem
> > Issue:
> > We already strictly follow the tutorials to install the Nvidia-driver (430.5) in the host machine
> > and also the Nvidia-docker (using the scripts in the https://github.com/ApolloAuto/apollo/tree/r5.5.0/docker/setup_host).
> > Anyone could help solve the driver_not_detected problem?
> 
> So the branch involved is `r5.5.0` ?

Yes absolutely.

**Comment by storypku** [comment]
> **nvidia-smi** works
> but **dpkg --list | grep nvidia*** does not work.

Sorry for the late response.  Does your issue still persists today? 
Have you installed nvidia-docker2 or nvidia-container-toolkit ?
