### ISSUE TITLE
paddlepaddle_volume-aarch64-latest not found

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#11812]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04 and 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue:
While running "bash docker/scripts/dev_start.sh", error encountered. therefore couldn't run dev_into.sh

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/66500271/87650115-221e9580-c78c-11ea-8074-0fbfb956ff47.png)
![error](https://user-images.githubusercontent.com/66500271/87650132-25b21c80-c78c-11ea-8057-98405b311be0.png)

**Comment by storypku** [comment]
Let's discuss this problem at https://github.com/ApolloAuto/apollo/issues/11813
