### ISSUE TITLE
local_third_party_volume-aarch64-latest not found

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#11813]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04 & 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue:
While running dev_start.sh, below error occurred.
local_third_party_volume-aarch64-latest not found
![error](https://user-images.githubusercontent.com/66500271/87651598-0caa6b00-c78e-11ea-8129-746dcd5f9975.png)

**Comment by storypku** [comment]
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04 & 18.04
> * **Apollo installed from (source or binary)**: source
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
> 
> ### Steps to reproduce the issue:
> While running dev_start.sh, below error occurred.
> local_third_party_volume-aarch64-latest not found

Apollo's arm64 support was not complete yet. currently only the CyberRT framework can be run under aarch64.

**Comment by storypku** [comment]
> > ### System information
> > 
> > * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04 & 18.04
> > * **Apollo installed from (source or binary)**: source
> > * **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
> > 
> > ### Steps to reproduce the issue:
> > While running dev_start.sh, below error occurred.
> > local_third_party_volume-aarch64-latest not found
> 
> Apollo's arm64 support was not complete yet. currently only the CyberRT framework can be run under aarch64.

There was not local_third_party volume for aarch64 as it was about `MKL` related libraries from Intel.
And `cyber_start.sh`, `dev_start.sh` should work for arm64 of the `master` branch now.
