### ISSUE TITLE
[docker error]docker: Error response from daemon: No such container: apollo_yolo3d_volume_yschung.(aarch64 machine)

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#11824]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04(aarch64)
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue:
While running dev_start.sh, error occurred.
docker: Error response from daemon: No such container: apollo_yolo3d_volume_yschung.
Because of this, couldn't run into docker.

**Comment by storypku** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04(aarch64)
> * **Apollo installed from (source or binary)**: source
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
> 
> ### Steps to reproduce the issue:
> While running dev_start.sh, error occurred.
> docker: Error response from daemon: No such container: apollo_yolo3d_volume_yschung.
> Because of this, couldn't run into docker.
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):

FYI, `dev_start.sh` can succeed for `aarch64` Jetson boards on the `master` branch as of today, although many third libraries was missing as of now.

**Comment by storypku** [comment]
The `yolo3d` volume was back in the latest `master` branch.
See https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L425.
As such, this issue is going to be closed. If you have other questions, plz feel free to create another issue. :-)
