### ISSUE TITLE
Is there a scenario to get out of the parking space

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#11821]
In apollo 5.5,valet parking scenario can make the ADC into a specific parking space, but can't get the car out of parking space. Because there is no lane guide the car out of  parking space in HDmap. in Park and Go scenarion it can only guide the off-lane car in a less than 60 degree heading error with main road. In fact parking space heading and lane heaing error is 90 degree. So is there a way to guide the car out of parking space?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by sjiang2018** [comment]
Hello, there. In park and go scenario, the planner can guide a car from a parking lot when the lane heading error is 90 degree.[Here is how](https://github.com/ApolloAuto/apollo/blob/db9097ef3b70fb11c88c449aabfccd09972c4ed3/modules/map/pnc_map/pnc_map.cc#L498)

**Comment by qwetqwe** [comment]
@sjiang2018 ,thanks for your reply ,problem has solved

**Comment by SantiniGH** [comment]
> @sjiang2018 ,thanks for your reply ,problem has solved

Hello,

I am having a similar problem with getting the car out of the parking space.

How did you solve your problem? 

Thanks in advance.
