### ISSUE TITLE
In dual ipc, how to send only part of the data to another machine?

### ISSUE THREAD

**Issue by DreamerLx** [ApolloAuto/apollo#11822]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 3.5

### Steps to reproduce the issue:

Refer to how_to_setup_dual_ipc.md, host A runs perception and other modules, host B can view the channel in cyber_monitor, but host A contains radar point cloud data, and the channel viewed by host B cyber_monitor cannot guarantee frame rate and data integrity. Is there any way to only Send part of channel of host A, don't send point cloud and other data not used for host B?

**Comment by AlexandrZabolotny** [comment]
I have a similar problem.
Have you been able to solve this?

**Comment by DreamerLx** [comment]
> I have a similar problem.
> Have you been able to solve this?

Modified the cyber_monitor tool code, you can specify certain channel display, similar to setting whitelist and blacklist, cyber_monitor is equivalent to creating a lot of readers, if you don't create those readers, cyber will not transmit those data. If you just want to confirm a certain Channel frame rate, you can use cyber_channel hz channel_name

**Comment by AlexandrZabolotny** [comment]
> > I have a similar problem.
> > Have you been able to solve this?
> 
> Modified the cyber_monitor tool code, you can specify certain channel display, similar to setting whitelist and blacklist, cyber_monitor is equivalent to creating a lot of readers, if you don't create those readers, cyber will not transmit those data. If you just want to confirm a certain Channel frame rate, you can use cyber_channel hz channel_name

thanks
this solved the problem

**Comment by AlexandrZabolotny** [comment]
Hi @DreamerLx .
i configured apollo for dual pc

On PC A, I run the Planning and Perception modules.
the framerate of the planning module is 100 Hz, and framerate of the perception module is 10 Hz.

On PC B, I subscribe to the Planning and Perception modules channels.
I am not launch cyber monitor. I launch only dreamview.
I am getting the normal framerate of the Perception module.
**But the framerate of the planning module is not stable and it is very less than 100 Hz.

Perhaps you had such a problem and you know how to solve it?**

**Comment by DreamerLx** [comment]
> Hi @DreamerLx .
> i configured apollo for dual pc
> 
> On PC A, I run the Planning and Perception modules.
> the framerate of the planning module is 100 Hz, and framerate of the perception module is 10 Hz.
> 
> On PC B, I subscribe to the Planning and Perception modules channels.
> I am not launch cyber monitor. I launch only dreamview.
> I am getting the normal framerate of the Perception module.
> **But the framerate of the planning module is not stable and it is very less than 100 Hz.**
> 
> **Perhaps you had such a problem and you know how to solve it?**

Hi ,I also encountered a similar problem. There is currently no solution, but to reduce the data transmission. I confirmed that my network bandwidth is sufficient and I have tested it with iperf. My network supports 1000Mb, but the dual pc transmits 100Mb at a rate of data loss. , And the problem of excessive delay. I also tried to modify the default fastrtps qos strategy in cyber, use RELIABILITY_BEST_EFFORT for reliability, and use 10 for depth. After the modification, the data delay is reduced, and there is basically no frame loss, but it will cause new problems. Occasionally, there will be a problem that one machine cannot receive another machine msg.
If you have any solution please share to me thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
