### ISSUE TITLE
perception module launch fail + and  perception related .so file cannot be found

### ISSUE THREAD

**Issue by FengIvex** [ApolloAuto/apollo#11849]
### System information

- **Linux Ubuntu 18.04**:
- **Apollo installed from source or binary**:
- **Apollo version 5.5**:

### Steps to reproduce the issue:
- **I try to launch the perception lidar only dag but failed**:
- **The error log showed that we lack or cannot load some .so**:
- **because I used a vlp-32c lidar and currently the imu information has not very configured, so I use the segementation component to read the convert component directly instead of reading the compensation output**:
- **anyone knows how to solve this problem?**:

### Supporting materials (screenshots, command lines, code/script snippets):
root@in_dev_docker:/apollo# cyber_launch start modules/perception/production/launch/cxx_perception_lidar.launch
[cyber_launch_3870] INFO Launch file [/apollo/modules/perception/production/launch/cxx_perception_lidar.launch]
[cyber_launch_3870] INFO ========================================================================================================================
[cyber_launch_3870] INFO Load module [perception] library: [lidar_perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_cxx_lidar.dag] exception_handler: []
[cyber_launch_3870] INFO Start process [lidar_perception] successfully. pid: 3871
[cyber_launch_3870] INFO ------------------------------------------------------------------------------------------------------------------------
[lidar_perception]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[lidar_perception]  I0718 18:43:26.032239  3871 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_cxx_lidar.dag -p lidar_perception -s CYBER_DEFAULT 
[lidar_perception]  I0718 18:43:26.036640  3871 global_data.cc:155] []host ip: 192.168.2.111
[lidar_perception]  I0718 18:43:26.037391  3871 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is lidar_perception, has 1 dag conf
[lidar_perception]  I0718 18:43:26.037782  3871 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_carvex_lidar.dag
[lidar_perception]  E0718 18:43:26.222472  3871 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libboost_filesystem.so.1.54.0: cannot open shared object file: No such file or directory
[lidar_perception]  E0718 18:43:26.222537  3871 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so
[lidar_perception]  E0718 18:43:26.222563  3871 class_loader_manager.h:70] [mainboard]Invalid class name: SegmentationComponent
[lidar_perception]  E0718 18:43:26.222584  3871 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception_cxx_lidar.dag
[lidar_perception]  E0718 18:43:26.222599  3871 class_loader_utility.cc:258] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so
[lidar_perception]  E0718 18:43:26.222615  3871 mainboard.cc:43] [mainboard]module start error.
[lidar_perception]  
[cyber_launch_3870] ERROR Process [lidar_perception] has finished. [pid 3871, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_carvex_lidar.dag -p lidar_perception -s CYBER_DEFAULT].
[cyber_launch_3870] INFO All processes has died.
[cyber_launch_3870] INFO Cyber exit.
[cyber_launch_3870] INFO All processes have been stopped.

**Comment by storypku** [comment]
Is it on branch  `r5.5.0` or `master`?

**Comment by FengIvex** [comment]
To give a summary, the error information is like this:
**[lidar_perception] E0718 18:43:26.222472 3871 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libboost_filesystem.so.1.54.0: cannot open shared object file: No such file or directory
[lidar_perception] E0718 18:43:26.222537 3871 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so
[lidar_perception] E0718 18:43:26.222563 3871 class_loader_manager.h:70] [mainboard]Invalid class name: SegmentationComponent
[lidar_perception] E0718 18:43:26.222584 3871 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception_cxx_lidar.dag
[lidar_perception] E0718 18:43:26.222599 3871 class_loader_utility.cc:258] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so
[lidar_perception] E0718 18:43:26.222615 3871 mainboard.cc:43] [mainboard]module start error.
[lidar_perception]**

**Comment by jeroldchen** [comment]
@FengIvex Which version of Apollo do you use?

**Comment by FengIvex** [comment]
> @FengIvex Which version of Apollo do you use?

5.5

**Comment by jeroldchen** [comment]
Seems that you didn't build it right. Can you post your building steps here so that we can find out what caused the errors?

**Comment by FengIvex** [comment]
> Seems that you didn't build it right. Can you post your building steps here so that we can find out what caused the errors?

I build it with "sudo bash apollo.sh build_opt_gpu"

**Comment by dymons** [comment]
The first error indicates that the libboost_filesystem library couldn't be found. Execute the command:
```
sudo find /usr/lib -iname 'libboost_filesystem*'
```
You will see the following result
```
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a
```
If not, see which library versions are available and install one of them
```
sudo apt-cache search libboost | grep filesystem
```
