### ISSUE TITLE
Is this process a correct way to configure Apollo to start on boot?

### ISSUE THREAD

**Issue by jimmyw404** [ApolloAuto/apollo#11854]
I needed to configure Apollo to start when the vehicle is powered. I've accomplished that using the following steps. I am curious to know if there are any features, scripts or documentation in place that I may have missed that could improve this process. If someone finds these instructions useful, all the better :)

This was done on Ubuntu 18.04 with Apollo 5.5 built from source.

1. I configured the computer to use Wake On Lan support and can wake it up with the etherwake tool.
2. On the computer I created a systemd service "apollo.service" with these contents:
```
[Unit]
Description=apollo script

[Service]
User=myuser
ExecStart=/home/myuser/apollo_5_5_0/docker/scripts/myrobot_start.sh

[Install]
WantedBy=multi-user.target
```

3. I ran 

`systemctl enable apollo`

to configure systemd to start the service on boot and run the myrobot_start.sh script when the OS starts.

4. I created the "myrobot_start.sh" script by copying from "dev_start.sh", removing the sections that create the /apollo link, removing the agreement prompt and setting these variables:
```
FAST_BUILD_MODE="yes"
FAST_TEST_MODE="yes"
NO_PULL_IMAGE="yes"
```
This will accelerate docker startup and avoid attempting to download docker images from the internet.

5. I added these lines to /apollo/docker/scripts/container_setup.sh:
```
/apollo/scripts/bootstrap.sh
/apollo/scripts/myrobot_startmodules.sh
```

container_setup.sh is a script run at the end of dev_start.sh / myrobot_start.sh

6. I created the myrobot_startmodules.sh script with these contents:
```
#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${DIR}/.."

source "${DIR}/apollo_base.sh"

nohup cyber_launch start /apollo/modules/dreamview/launch/myrobot.launch &
```
This will launch the myrobot.launch file in the background.

7. I created myrobot.launch file with these contents:
```
<cyber>
    <module>
        <name>Localization</name>
        <dag_conf>/apollo/modules/localization/dag/dag_streaming_rtk_localization.dag</dag_conf>
        <process_name></process_name>
        <exception_handler>respawn</exception_handler>
    </module>
    ...
</cyber>
```

When my computer is booted from my vehicle's primary PC running etherwake, the service will start the myrobot_start.sh script that starts the docker and calls the container_setup.sh script that will start dreamview, monitor and run the launch file that will start the remaining modules.

I looked into using Docker's ability to restart containers and run ENTRYPOINT/CMD scripts, but that feature didn't give me the kind of behavior I wanted and I prefer to use the dev_start.sh type script anyway. https://docs.docker.com/engine/reference/run/#restart-policies---restart https://docs.docker.com/engine/reference/builder/#entrypoint

I could not find any Apollo documentation on how to accomplish this specifically, but it makes use of existing Apollo scripts and capability without too much modification. If there is any documentation or systems that accomplish this that I missed, please let me know. Thank you.

**Comment by jinghaomiao** [comment]
@jimmyw404 Thanks for using Apollo. We have never tested start on boot feature either offline or onboard. This is a safety related figure and we do suggest that you test it with enough inspection and caution before loading it onboard. Please share your experience. This ticket is being closed and please feel free to open new issues if needed. Thanks!
