### ISSUE TITLE
Control&CAN: CAN卡安装测试与硬件连接

### ISSUE THREAD

**Issue by yufeilongyuan** [ApolloAuto/apollo#11855]
你好，请问有详细的CAN卡安装，测试指导吗，给的文档貌似不是很详细。主要是驱动安装，通信测试，以及重点CAN卡如何与车辆CAN跳线连接，有大佬指导下吗？车辆为GE3。感谢

**Comment by macDure** [comment]
pin2 CAN L，pin7 CAN H , just two wire connection
