### ISSUE TITLE
build apollo fails with the master code

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#11865]
When I build apollo-master code, it shows errors as bellow:

Code version:
![image](https://user-images.githubusercontent.com/4536559/88007727-2e667200-cb41-11ea-81be-d1cf0e96b9f0.png)

docker and images version:
![image](https://user-images.githubusercontent.com/4536559/88007776-46d68c80-cb41-11ea-8b8b-c687f674e44b.png)

build error log:

```
./apollo.sh build_opt                                                                                                 [15/491][INFO] Apollo Environment Settings:                                                                                                                          [INFO]     APOLLO_ROOT_DIR: /apollo                                                                                                                          [INFO]     APOLLO_CACHE_DIR: /apollo/.cache                                                                                                                  [INFO]     APOLLO_IN_DOCKER: true                                                                                                                            [INFO]     APOLLO_VERSION: master-2020-07-18-f7a2369315                                                                                                      [INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false USE_GPU=0                                                                                                [INFO] Running build under CPU mode on x86_64 platform.                                                                                                      [WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.                                                                                         [WARNING] If you need ESD CAN, please refer to:                                                                                                              [WARNING]   third_party/can_card_library/esd_can/README.md                                                                                                   [INFO] Build Overview:                                                                                                                                       [INFO]     Bazel Options: --config=opt --define USE_ESD_CAN=false                                                                                            [INFO]     Build Targets: //modules/... union //cyber/...  except //modules/drivers/canbus/can_client/esd/...                                                Loading: 0 packages loaded                                                                                                                                   Loading: 3 packages loaded                                                                                                                                   Loading: 3 packages loaded                                                                                                                                   (02:54:41) WARNING: The following configs were expanded more than once: [optimize]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
(02:54:41) WARNING: option '--compilation_mode' was expanded to from both option '--config=dbg' (source /apollo/tools/bazel.rc) and option '--config=opt' (source command line options)                                                                                                                                   (02:54:41) INFO: Current date is 2020-07-21
(02:54:55) INFO: Repository com_google_absl instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:                                                                                                                       /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(02:54:55) INFO: Repository eigen instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(02:54:55) WARNING: Download from https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
(02:54:55) ERROR: An error occurred during the fetch of repository 'com_google_absl':
   java.io.IOException: Error downloading [https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_absl/20200225.2.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
(02:54:55) INFO: Repository com_github_nlohmann_json instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(02:54:55) INFO: Repository remote_java_tools_linux instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(02:54:55) INFO: Repository zlib instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(02:54:58) INFO: Repository boringssl instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(02:54:58) ERROR: /apollo/modules/perception/common/io/BUILD:6:11: //modules/perception/common/io:io_util depends on @com_google_absl//absl/strings:strings in repository @com_google_absl which failed to fetch. no such package '@com_google_absl//absl/strings': java.io.IOException: Error downloading [https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_absl/20200225.2.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
(02:54:58) ERROR: Analysis of target '//modules/perception/common/io:io_util' failed; build aborted: Analysis failed
(02:54:58) INFO: Elapsed time: 17.015s
(02:54:58) INFO: 0 processes.
(02:54:58) FAILED: Build did NOT complete successfully (5 packages loaded, 519 targets configured)
```

**Comment by storypku** [comment]
> When I build apollo-master code, it shows errors as bellow:
> 
> Code version:
> ![image](https://user-images.githubusercontent.com/4536559/88007727-2e667200-cb41-11ea-81be-d1cf0e96b9f0.png)
> 
> docker and images version:
> ![image](https://user-images.githubusercontent.com/4536559/88007776-46d68c80-cb41-11ea-8b8b-c687f674e44b.png)
> 
> build error log:
> 
> ```
> ./apollo.sh build_opt                                                                                                 [15/491][INFO] Apollo Environment Settings:                                                                                                                          [INFO]     APOLLO_ROOT_DIR: /apollo                                                                                                                          [INFO]     APOLLO_CACHE_DIR: /apollo/.cache                                                                                                                  [INFO]     APOLLO_IN_DOCKER: true                                                                                                                            [INFO]     APOLLO_VERSION: master-2020-07-18-f7a2369315                                                                                                      [INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false USE_GPU=0                                                                                                [INFO] Running build under CPU mode on x86_64 platform.                                                                                                      [WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.                                                                                         [WARNING] If you need ESD CAN, please refer to:                                                                                                              [WARNING]   third_party/can_card_library/esd_can/README.md                                                                                                   [INFO] Build Overview:                                                                                                                                       [INFO]     Bazel Options: --config=opt --define USE_ESD_CAN=false                                                                                            [INFO]     Build Targets: //modules/... union //cyber/...  except //modules/drivers/canbus/can_client/esd/...                                                Loading: 0 packages loaded                                                                                                                                   Loading: 3 packages loaded                                                                                                                                   Loading: 3 packages loaded                                                                                                                                   (02:54:41) WARNING: The following configs were expanded more than once: [optimize]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
> (02:54:41) WARNING: option '--compilation_mode' was expanded to from both option '--config=dbg' (source /apollo/tools/bazel.rc) and option '--config=opt' (source command line options)                                                                                                                                   (02:54:41) INFO: Current date is 2020-07-21
> (02:54:55) INFO: Repository com_google_absl instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:                                                                                                                       /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> (02:54:55) INFO: Repository eigen instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> (02:54:55) WARNING: Download from https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> (02:54:55) ERROR: An error occurred during the fetch of repository 'com_google_absl':
>    java.io.IOException: Error downloading [https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_absl/20200225.2.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> (02:54:55) INFO: Repository com_github_nlohmann_json instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> (02:54:55) INFO: Repository remote_java_tools_linux instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> (02:54:55) INFO: Repository zlib instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> (02:54:58) INFO: Repository boringssl instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> (02:54:58) ERROR: /apollo/modules/perception/common/io/BUILD:6:11: //modules/perception/common/io:io_util depends on @com_google_absl//absl/strings:strings in repository @com_google_absl which failed to fetch. no such package '@com_google_absl//absl/strings': java.io.IOException: Error downloading [https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_absl/20200225.2.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> (02:54:58) ERROR: Analysis of target '//modules/perception/common/io:io_util' failed; build aborted: Analysis failed
> (02:54:58) INFO: Elapsed time: 17.015s
> (02:54:58) INFO: 0 processes.
> (02:54:58) FAILED: Build did NOT complete successfully (5 packages loaded, 519 targets configured)
> ```

It was caused by network issues. Just download the tarballs from the original url (e.g, https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz for abceil-cpp), and put it under `<apollo_root_dir>/.cache/distdir`. Be sure the sha256 value matches the one listed in `WORKSPACE`(or `third_party/xxx/workspace.bzl`). And try again.

**Comment by oska874** [comment]
> > When I build apollo-master code, it shows errors as bellow:
> > (02:54:58) ERROR: Analysis of target '//modules/perception/common/io:io_util' failed; build aborted: Analysis failed
> > (02:54:58) INFO: Elapsed time: 17.015s
> > (02:54:58) INFO: 0 processes.
> > (02:54:58) FAILED: Build did NOT complete successfully (5 packages loaded, 519 targets configured)
> 
> It was caused by network issues. Just download the tarballs from the original url (e.g, https://github.com/abseil/abseil-cpp/archive/20200225.2.tar.gz for abceil-cpp), and put it under `<apollo_root_dir>/.cache/distdir`. Be sure the sha256 value matches the one listed in `WORKSPACE`(or `third_party/xxx/workspace.bzl`). And try again.
> 
> Another solution would be set HTTP_PROXY and HTTPS_PROXY, like:
> 
> ```
> export HTTP_PROXY=myagent.com:8182
> export HTTPS_PROXY=myagent.com:8182
> ```

Direct download the tars with `wget` is ok, but why apollo build download tars fails?

**Comment by storypku** [comment]
> Direct download the tars with `wget` is ok, but why apollo build download tars fails?

Dependency was analyzed and fetched by `bazel` actually.  `bazel` has its own way of retrieving tarballs.
