### ISSUE TITLE
System crash when build Apollo 5.0

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#11875]
### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **Apollo installed from**: https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/
- **Apollo version**: 5.0
- **GPU**: 1080ti
- **RAM**: 32GB
- **CPU**: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz

### Steps to reproduce the issue:
Follow the instruction here: https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/

### Issue description:
When I build apollo-5.0 on Ubuntu 18.04, the system will crash and cannot build sucessfully, and the error message is shown below:

### Supporting materials (screenshots, command lines, code/script snippets):
**The error message is shown below**:

`Server terminated abruptly (error code: 14, error message: '', log file: '/home/chengjie/.cache/bazel/_bazel_chengjie/540135163923dd7d5820f3ee4b306b32/server/jvm.out')

============================
[ERROR] Build failed!
[INFO] Took 833 seconds
============================
`
Can anyone know what is the problem.

**Comment by daohu527** [comment]
Seems like your memory is lark, and cause a OOM error. [link](https://github.com/bazelbuild/bazel/issues/3020)  

Since you said that the memory is 32G, so it should not be insufficient memory. Are you running in a virtual machine, or other programs occupy too much memory.

**Comment by ForresterLu** [comment]
Thanks for your reply, it seems that my ubuntu system do not have enough swap space and after I enlarge the swap space, the issue got solved.



---Original---

**Comment by daohu527** [comment]
Good job!

**Comment by lemketron** [comment]
This worked for me as well when trying to build latest apollo master. My machine kept crashing whenever the linker ran, and the old tricks for setting a lower number of jobs didn't seem to work (even adding overrides to .apollo.bazelrc).

But following the simple steps [here](https://bogdancornianu.com/change-swap-size-in-ubuntu/) to change swap from a 1GB partition to a 16GB file worked and finally allowed my 16GB Ubuntu 18.04 gaming laptop to successfully complete the build.

This issue should probably be closed now...

**Comment by daohu527** [comment]
If the physical memory is sufficient, there is no need to swap. **I think the most fundamental reason is lark of memory**, maybe we should check the memory at that time.  

> --ram_utilization_factor= default: "67"
Specify what percentage of the system's RAM Bazel should try to use for its subprocesses. This option affects how many processes Bazel will try to run in parallel. If you run several Bazel builds in parallel, using a lower value for this option may avoid thrashing and thus improve overall throughput. Using a value higher than the default is NOT recommended. Note that Bazel's estimates are very coarse, so the actual RAM usage may be much higher or much lower than specified. Note also that this option does not affect the amount of memory that the Bazel server itself will use.

The above option is outdated, and the setting was 80.  I see that the latest code has been replaced with the latest bazel memory limit option. Is the latest version still a problem?

**Comment by lemketron** [comment]
> The above option is outdated, and the setting was 80. I see that the latest code has been replaced with the latest bazel memory limit option. Is the latest version still a problem?

Yes, I built latest Apollo-master and I tried re-starting the crashed build repeatedly but I couldn't get past one of the link steps that kept running the machine out of memory. I think this is a bazel issue more than an apollo one but I wasn't able to figure out how to get bazel to avoid crashing. I suppose it doesn't know that the link step is going to consume a ton of memory, and even if you could skip all parallelization, that would make the rest of the build take many times longer. 

I found a related question on StackOverflow: [How to specify amount of parallel link jobs bazel does, separate from build jobs?](https://stackoverflow.com/questions/57042596/how-to-specify-amount-of-parallel-link-jobs-bazel-does-separate-from-build-jobs).

My machine has six physical cores (so 12 threads) and once I bumped swap from 1GB to 16GB I was able to build (including linking) all of apollo master in 20 minutes.

**Comment by daohu527** [comment]
@lemketron 
Thank you for your feedback, I guess this may be a bazel problem on some platforms.
