### ISSUE TITLE
Question: Extract CAN BUS signals

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#11874]
Hello,

I would like to place an ADAS camera in front of the LGSVL simulation screen to create an illusion that the camera is fitted on the ego vehicle. This camera has features like Lane departure warning and forward collision warning.

For this camera to work, it needs inputs like 
- The vehicle speed,
- The vehicle ignition signal (12/24V), 
- The Vehicle CAN bus (High/Low),
- The vehicle left turn signal and right turn signal. 
Is it possible to extract this information from the ego vehicle to give it to the camera?

The attached picture contains the wiring of the camera.
![Wiring](https://user-images.githubusercontent.com/67329705/88076692-a8ffb380-cb7a-11ea-8fa8-e46fcb2ec3c9.jpg)

**Comment by ashwinsarvesh** [comment]
These wires are usually connected to the corresponding vehicle wiring. But in my case; it's the ego vehicle of the LGSVL simulator

**Comment by Capri2014** [comment]
Hh, surely you can do that, just need to fake a CAN node and need A/D, D/A converter

**Comment by ashwinsarvesh** [comment]
Thank you for your reply!
Are these data listed below given by the simulator or Apollo?
- The vehicle speed,
- The vehicle ignition signal (12/24V),
- The Vehicle CAN bus (High/Low),
- The vehicle left turn signal and right turn signal.

How do I access this data?

**Comment by ashwinsarvesh** [comment]
any help anyone?

**Comment by Capri2014** [comment]
> Thank you for your reply!
> Are these data listed below given by the simulator or Apollo?
> 
> * The vehicle speed,
> * The vehicle ignition signal (12/24V),
> * The Vehicle CAN bus (High/Low),
> * The vehicle left turn signal and right turn signal.
> 
> How do I access this data?

No, our simulation do not provide HIL simulation capability so we do not provide item 3. And you need to customize by yourself to generate adequate analogy signal so you can feed into your camera to close the whole loop, that is what I mean by the DA conversion part.

**Comment by ashwinsarvesh** [comment]
Hello,

Thank you for your reply!
Yes, I am aware of it. But I mean where do I find the data in the software on Github. The data I need are the ones mentioned in CAN bus section in this picture. (especially vehicle speed, left turn and right turn signal)

![image](https://user-images.githubusercontent.com/67329705/88426599-ba062a00-cdf1-11ea-8c9c-a7a2927bb75c.png)

**Comment by Capri2014** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/canbus/proto/chassis.proto
