### ISSUE TITLE
build apollo error, cannot "driver_types.h".

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#11871]
apollo version : f7a2369315a2bf106e473ced7392f4542f4ff3a3
build command : ./apollo.sh build_opt
error:
![image](https://user-images.githubusercontent.com/4536559/88052939-9f337b80-cb8d-11ea-9c4b-9bc4e2b36b00.png)

**Comment by storypku** [comment]
Will you please pull the latest master, and try `./apollo.sh build_opt` again ? If the error persists, please let me know.

**Comment by oska874** [comment]
> Will you please pull the latest master, and try `./apollo.sh build_opt` again ? If the error persists, please let me know.

I've updated apollo to version "194819d15f95c27",but the error still exists.

**Comment by lfcarol** [comment]
> > Will you please pull the latest master, and try `./apollo.sh build_opt` again ? If the error persists, please let me know.
> 
> I've updated apollo to version "194819d15f95c27",but the error still exists.

Please check if your "/apollo/.apollo.bazelrc : Line 4" modified to "build --config=gpu", the default is "build --config=cpu".

**Comment by oska874** [comment]
> > > Will you please pull the latest master, and try `./apollo.sh build_opt` again ? If the error persists, please let me know.
> > 
> > 
> > I've updated apollo to version "194819d15f95c27",but the error still exists.
> 
> Please check if your "/apollo/.apollo.bazelrc : Line 4" modified to "build --config=gpu", the default is "build --config=cpu".

BUT my pc has no gpu.So?

**Comment by storypku** [comment]
> > > > Will you please pull the latest master, and try `./apollo.sh build_opt` again ? If the error persists, please let me know.
> > > 
> > > 
> > > I've updated apollo to version "194819d15f95c27",but the error still exists.
> > 
> > 
> > Please check if your "/apollo/.apollo.bazelrc : Line 4" modified to "build --config=gpu", the default is "build --config=cpu".
> 
> BUT my pc has no gpu.So?

I am afraid it won't  work  for now.  Our support for CPU-only builds are not ready yet. :-( Hope we can resolve this in the next few months.

**Comment by dymons** [comment]
I got the same error. It occurred because I forgot to follow points 2 and 3 [Download Apollo Source](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#download-apollo-source). After completing these steps, the error is gone.

**Comment by storypku** [comment]
`CPU|GPU Build` was fix in PR #12282 , and this issue is going to be closed.

Please create another issue if you have other questions, or reopen this one if the error still there.

Thanks for using Apollo!
