### ISSUE TITLE
[Apollo Pre6 Branch] [Perception] - FusionComponent not receiving prefused_message from FusionCameraDetectionComponent  

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#11887]
- Ubuntu 1804
- Apollo pre6 branch
---

hi team, I'm using latest LGSVL with Apollo pre6 branch.

I launch the perception module with this [launch](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/launch/perception.launch) file.

![fusion_component_2](https://user-images.githubusercontent.com/16061105/88195338-851f9900-cc72-11ea-983b-70e28dc119d1.png)

inside which, there is camera perception
```
    <module>
        <name>perception_camera</name>
        <dag_conf>/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag</dag_conf>
        <!-- if not set, use default process -->
        <process_name>camera_perception</process_name>
        <version>1.0.0</version>
    </module>
```

However, I noticed that the Fusion Component defined in one of dag file:

```
  components {
    class_name: "FusionComponent"
    config {
      name: "SensorFusion"
      config_file_path: "/apollo/modules/perception/production/conf/perception/fusion/fusion_component_conf.pb.txt"
      readers {
          channel: "/perception/inner/PrefusedObjects"
        }
    }
```

is not receiving the `prefused_message <SensorFrameMessage>` sent by the `fusion_camera_detection_component.cc`. 

I've stopped the Lidar sensor on the LGSVL simulator, leaving only two camera sensors. Below logs are what I have:

![fusion_component_not_receiving_camera_prefused_output](https://user-images.githubusercontent.com/16061105/88195382-8fda2e00-cc72-11ea-9b0c-b8818a30b28c.png)

The bottom image shows that `fusion_ccamera_detection_component.cc` keeps sending out the `prefused_messages`. 
But the top image shows that there is no data being received by `fusion_component.cc`, otherwise, there will be logs printing out from `probabilistic_fusion.cc` i guess.

**Comment by ntutangyun** [comment]
Not I understand why fusion component cannot receive the prefused_message sent from camera detection component. 

refer to [issue ](https://github.com/ApolloAuto/apollo/issues/11892)

**Comment by ideasplus** [comment]
Hi, After reading your reference, I still can't  understand why fusion component cannot receive the prefused_message sent from camera detection component,  Could you explain it in more detail? By the way, Should the sensor fusion module fuse camera sensors? if so,  how to achiene it?  The inconsistency of apollo document and related issue #10495 confused me.

**Comment by ntutangyun** [comment]
hi @ideasplus , the reason why the fusion component cannot receive the prefused_message is that the prefused_message is communicated via shared pointers (If I'm correct about it) between all the components defined inside ONE dag file.

the prefused_message is not shared communicated via shared memory, meaning that modules defined in other dag files cannot receive it, and the cyber_monitor also cannot see it. 

Since the camera detection component is not defined within the same dag file as the fusion component, the fusion component will not be able to receive this prefused_message published by the camera detection component.

The current version of Apollo still does not support fusion of camera obstacle detections. I think it's only fusing obstacles detections by LIdar and Radar. 

The cameras are used only for traffic light detection.

**Comment by ideasplus** [comment]
@ntutangyun Thank you very much for your detailed explanation:)

**Comment by lucasnmatias** [comment]
I've managed to change the `dag_streaming_perception.dag` and add the `dag_streaming_perception_camera.dag` on the beginning of this code and the perception could start both camera and lidar detections. So I have a dag file with two `module_config {`, one configuring the camera perception and other configuring the lidar 3d perception. Still, the data doesn't seems to be fused. But in fact I could run both modules from one `.dag` file.

**Comment by lucasnmatias** [comment]
Actually an update, I've written one `.dag` file with two `module_config` which are the content of the `dag_streaming_perception_camera.dag` and `dag_streaming_perception.dag` and this actually worked. After some adjustments on my extrinsic parameters the data fusion so to fuse camera and LiDAR two main things are necessary:

1. Have the camera and LiDAR `module_config` in an unique `.dag` file
2. Have a precise extrinsic parameters, otherwise the matches between camera and LiDAR will not be good and the fusion will not happen

**Comment by duongnxptit** [comment]
> hi @ideasplus , the reason why the fusion component cannot receive the prefused_message is that the prefused_message is communicated via shared pointers (If I'm correct about it) between all the components defined inside ONE dag file.
> 
> the prefused_message is not shared communicated via shared memory, meaning that modules defined in other dag files cannot receive it, and the cyber_monitor also cannot see it.
> 
> Since the camera detection component is not defined within the same dag file as the fusion component, the fusion component will not be able to receive this prefused_message published by the camera detection component.
> 
> The current version of Apollo still does not support fusion of camera obstacle detections. I think it's only fusing obstacles detections by LIdar and Radar.
> 
> The cameras are used only for traffic light detection.

Thanks for your explanation. But as i know, lgsvl does not send radar data to perform module perception on apollo. Is there anyway  to simulate the fusing obstacle of lidar and radar? I just want to simulate how the data fused (lidar and radar, or camera and lidar).
