### ISSUE TITLE
Sharing virtual CAN network with docker container

### ISSUE THREAD

**Issue by ironWolf1990** [ApolloAuto/apollo#11883]
After creating a vcan network on the host pc 
```
$ sudo modprobe vcan
$ sudo ip link add dev vcan0 type vcan
$ sudo ip link set up vcan0
```
how can i get my docker container to interface with it.  

I tried using `--network=host`, the only problem is there is no network isolation b/w docker host and containers anymore. Is there a way to achieve the above but without sharing the host network

**Comment by gsa88** [comment]
> After creating a vcan network on the host pc
> 
> ```
> $ sudo modprobe vcan
> $ sudo ip link add dev vcan0 type vcan
> $ sudo ip link set up vcan0
> ```
> 
> how can i get my docker container to interface with it.
> 
> I tried using `--network=host`, the only problem is there is no network isolation b/w docker host and containers anymore. Is there a way to achieve the above but without sharing the host network

Yes, you can do it. Set up vcan interface into the docker container:
1. Run a network isolated docker container (without `--network=host` argument)
2. Connect to the running container
3.  Install `iproute2` package inside the container:
     `$ sudo apt install -y iproute2`
4. Set up vcan inerface:
    ```bash
    $ sudo ip link add dev vcan0 type vcan
    $ sudo ip link set up vcan0
    ```
5. Check network interfaces:
    ```bash
    $ ip a
    ...
    2: vcan0: <NOARP,UP,LOWER_UP> mtu 72 qdisc noqueue state UNKNOWN group default qlen 1000 
    link/can
    ...
    ```
