### ISSUE TITLE
The capabilities of Apollo D-kit hardware platform.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#11909]
Hi,

Our group has bought two sets of Apollo D-kits, numbered as 2020012 and 2020014. I want to know the capabilities of Apollo D-kit hardware platform with the latest git master version of ApolloAuto installed on it. Does it support up to L5 or not?

Regards
HY

**Comment by diegohu** [comment]
D-KIT officially supports the latest Apollo 5.5 release version. We also provide documents to establish an auto-driving demo based on Apollo 5.5, please refer to https://github.com/ApolloAuto/apollo/tree/r5.5.0/docs/specs/D-kit. If you have any questions about D-KIT usage on Apollo 5.5, feel free to ask questions in D-KIT feedback platform.
And master version is still in development and not officially supported by D-KIT now.

**Comment by hongyi-zhao** [comment]
@diegohu Thank you for your clarification.
