### ISSUE TITLE
About routing_response and reference_line

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#11908]
I have some confused about the relationship between routing_response and reference_line,
What I understand is that routing_response contains the information is like Segment,just contains such "start_s" and "end_s". 
And we get  reference_line_info from routing_response, reference_line_info contains some lane_way_point information, such as "SL" information. My question is how can we get points information just according to routing_response.
From hdmap or what?

Apollo生成道路的主要思想是通过在道路上撒点，点之间进行平滑生成路线。那么撒点这个步骤在哪里完成（可以具体到代码实现）？

Thank you very much for taking my question seriously.

**Comment by daohu527** [comment]
## routing_response
routing response decide which road to go, and the data store in 
https://github.com/ApolloAuto/apollo/blob/4f7fbcf8e472da72b8c196208bf10dd93edf09f0/modules/routing/proto/routing.proto#L49-L64

## reference_line
Then use the RoadSegments and hdmap to generate reference line. More details will be added later.
https://github.com/ApolloAuto/apollo/blob/3711be4317b62fffa548f91cb383269d4cc25987/modules/planning/reference_line/spiral_reference_line_smoother.cc#L169-L181

**Comment by ManXiaoMi** [comment]
Thank you for your detailed explanation. it helps me a lot.
