### ISSUE TITLE
How to obtain vehicle dynamics model parameters online 

### ISSUE THREAD

**Issue by 76328** [ApolloAuto/apollo#11929]
I just find in /module/tool/vehicle_calibration has some response data plot.Is there an algorithm that can directly use these data to identify vehicle dynamics online or offline?

**Comment by alexiskovi** [comment]
With data_collector.py you can build a calibration table for Control module. It's needed for better interpolation in acceleration commands. Also you can use frontend tools, like in these [docs](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md).

**Comment by Capri2014** [comment]
The data_collector.py and corresponding tools are really out of date and we are thinking of remove them from latest master, the latest control calibration and vehicle dynamics model has been opened as service with detailed instructions here: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md
