### ISSUE TITLE
ERROR during compiling Apollo with build_cpu

### ISSUE THREAD

**Issue by gafeng** [ApolloAuto/apollo#11945]
I installed ubuntu in hyper-v virtual machine, downloaded Apollo code, installed docker, but got ERROR during compiling the code with build_cpu:
===========================================
(06:20:42) ERROR: /apollo/modules/map/pnc_map/BUILD:7:13: error while parsing .d file: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-dbg/bin/modules/map/pnc_map/_objs/cuda_pnc_util/cuda_util.pic.d (No such file or directory)
gcc: warning: modules/map/pnc_map/cuda_util.cu: linker input file unused because linking not done
(06:20:42) INFO: Elapsed time: 41.698s, Critical Path: 40.13s
(06:20:42) INFO: 155 processes: 155 local.
(06:20:42) FAILED: Build did NOT complete successfully
===========================================
Seems it's searching for cuda stuff, but I'm using option build_cpu.

**Comment by storypku** [comment]
It's definitely a bug. We are working on fixing it.

**Comment by jayjayhee** [comment]
Hi, I met the same issue, I used build_cpu as well and it looks like CUDA is being looked for. I noticed that another friend met something similar in case #12007 but I believe he used build instead of build_cpu. Are there any updates on this bug？

**Comment by storypku** [comment]
> Hi, I met the same issue, I used build_cpu as well and it looks like CUDA is being looked for. I noticed that another friend met something similar in case #12007 but I believe he used build instead of build_cpu. Are there any updates on this bug？

The case in #12007 have GPU enabled. Currently, our build scripts have not been ready  for CPU only build yet, esp. for CUDA related targets.

**Comment by storypku** [comment]
`CPU|GPU Build` was fix in PR #12282 , and this issue is going to be closed.

Please create another issue if you have other questions, or reopen this one if the error still there.

Thanks for using Apollo!
