### ISSUE TITLE
/apollo/modules/dreamview/backend/handlers/BUILD:23:1: no such package '@opencv2//':

### ISSUE THREAD

**Issue by geiliwanghaichao** [ApolloAuto/apollo#11948]
- **OS Platform and Distribution (vmware+Ubuntu 16.04):
- **Apollo installed from (source)
- **Apollo version (2.0.0)**:

I install docker successfully, then download apollo2.0.0 source code from github
1. bash docker/scripts/dev_start.sh -C     ok
2. bash docker/scripts/dev_into.sh     ok
3.bash apollo.sh build_no_perception dbg    
     INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/dreamview/backend/handlers/BUILD:23:1: no such package '@opencv2//': Error downloading [https://github.com/opencv/opencv/archive/2.4.13.2.zip] to /home/wang/.cache/bazel/_bazel_wang/540135163923dd7d5820f3ee4b306b32/external/opencv2/2.4.13.2.zip: Tried to reconnect at offset 9,273,622 but server didn't support it and referenced by '//modules/dreamview/backend/handlers:image'
ERROR: Analysis of target '//modules/dreamview/backend/simulation_world:simulation_world_updater' failed; build aborted
INFO: Elapsed time: 564.459s
FAILED: Build did NOT complete successfully (12 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 1757 seconds
============================

how can I resolve this problem.thanks!

**Comment by storypku** [comment]
Maybe you can try to download `https://github.com/opencv/opencv/archive/2.4.13.2.zip` manually and save 
it as say, `/home/libs/opencv-2.4.13.2.zip`. And change its url in `WORKSPACE.in` as `url="file:///home/libs/opencv-2.4.13.2.zip",`.

Btw, It seems that the `r2.0.0` branch was not maintained actively. Maybe you should change to a more recent version.

**Comment by storypku** [comment]
This issue is being closed. If you have other questions, please feel free to create another issue.
