### ISSUE TITLE
I want to build docker images for apollo 5.5,which version of docker_dev should I use?

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#11950]
1. I want to build docker images for apollo 5.5,which version of docker_dev should I use?
2. In the dev.x86-64.dockerfile, it's based on apolloauto/apollo:cyber-x86_64-18.04-20200707_1716. If I want to build a same images from ubuntu base image, how to?
3. If I use dev.x86_64.dockerfile of version 4da763f to build a docker image, is it same to apolloauto/apollo:cyber-x86_64-18.04-20200629_0512?

**Comment by storypku** [comment]
> 1. I want to build docker images for apollo 5.5,which version of docker_dev should I use?
> 2. In the dev.x86-64.dockerfile, it's based on apolloauto/apollo:cyber-x86_64-18.04-20200707_1716. If I want to build a same images from ubuntu base image, how to?
> 3. If I use dev.x86_64.dockerfile of version [4da763f](https://github.com/ApolloAuto/apollo/commit/4da763fa48d285561bb748c93f7e99601e8ea817) to build a docker image, is it same to apolloauto/apollo:cyber-x86_64-18.04-20200629_0512?

Hi, 
1） There were no `docker_dev` versions. There was a `docker_dev` branch used for infra break-upgrade previously, now it has been merged into the `master` branch.  
I am afraid `Dockerfile` in the the `r5.5.0` branch was broken. 

2) See `docker/build/build_cyber.sh` for the `master` branch.  Generally, the following steps are assumed.

```
$ cd docker/build
$  ./build_cyber.sh -f cyber.x86_64.dockerfile -g us # OR
$ ./build_cyber.sh -f cyber.x86_64.dockerfile -g cn
```

Where option `-g` means using apt/pip sources for **G**eolocation. (`cn` for China, `us` for `USA`, ...)

You can type `-h` for help on how to use `./build_cyber.sh`:

```
$ ./build_cyber.sh -h
Usage:
    build_cyber.sh [-l] [-c] -f <cyber_dockerfile> [-m <build|download>] [-g <us|cn>]
    build_cyber.sh -h/--help    # Show this message
E.g.,
    build_cyber.sh -f cyber.x86_64.dockerfile -m build
    build_cyber.sh -l -f cyber.aarch64.dockerfile -m download
```

3) Of course not. As you already know, our `dev` image was based on `cyber` image. 
The script to build dev.image was `docker/build/build_dev.sh` which has almost the same usage as `build_cyber.sh`.

**Comment by wuzp986** [comment]
The problem has been solved, thank you very much!

**Comment by storypku** [comment]
> The problem has been solved, thank you very much!

U r welcome.

**Comment by storypku** [comment]
This issue is going to be closed now. If you have any further questions, please feel free to create a new issue.
Thanks for using Apollo.
