### ISSUE TITLE
RTK relative capabitity for the default hardware configuration on the Apollo D-Kit platform.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#11952]
Hi,

One of my friends told me that by default the Apollo D-Kit hardware platform doesn't include the RTK relative hardware. So, the RTK relative capability in ApolloAuto should be unavailable for the default D-Kit suit sold by Baidu. Is this true? If this feature is required for my research project, how can I achieve this aim?

Regards
HY

**Comment by diegohu** [comment]
I do not quite understand the meaning of "RTK relative capability". 
Apollo localization is based on RTK, so the navigation device in D-KIT also support RTK. Meantime, you need to setup a RTK base station or buy a RTK base station service to enable RTK. And the base station related hardware/service is not included in D-KIT's scope.

**Comment by diegohu** [comment]
Some of D-KIT users used qianxun FindCM service to get RTK capability. And you can access the service via 4G network. 
Again, I strongly recommend to use the "D-KIT feedback tool" to raise any question about D-KIT :)

**Comment by hongyi-zhao** [comment]
@diegohu Thank you very much for your suggestions and reply.
