### ISSUE TITLE
About the current implementation status of supporting for RTK, CORS, SLAM and other similar advanced techniques in ApolloAuto.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#11966]
Real-time kinematic (RTK), Continuously Operating Reference Stations (CORS) and Simultaneous localization and mapping (SLAM) are all the advanced techniques for automatic geolocation and path-tracing. 

I want to know whether all of these techniques are supported and have corresponding API interfaces implemented in ApolloAuto? Furthermore, are there other more advanced techniques for this type of job available in ApolloAuto? Any hints will be highly appreciated.

Thanks in advance.

Regards
HY

**Comment by jinghaomiao** [comment]
@hongyi-zhao thanks for using Apollo. Currently Apollo has RTK implementation (https://github.com/ApolloAuto/apollo/tree/master/modules/localization/rtk). You are welcome to implement your own localization algorithm and contribute that to our code repo. This ticket is being closed. Please feel free to raise new issues if needed. Thanks!
