### ISSUE TITLE
Failed to start can client (brand: SOCKET_CAN_RAW)

### ISSUE THREAD

**Issue by gsa88** [ApolloAuto/apollo#11980]
**Describe the bug**
According to [this patch](https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg1291984.html), the limit number of can_filter that can be set is 512, while socket_can_client_raw.cc has 2048 filters specified, which leads to an error starting the CAN client.

**To Reproduce**
I use SOCKET_CAN_RAW brand in the can_card_parameter and when I try to launch canbus module through:
```
$ mainboard -d modules/canbus/dag/canbus.dag
```
the error occurs
E0730 12:47:43.146181 15075 canbus_component.cc:140] Failed to start can client

**Expected behavior**
The module should launch without errors

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
To solve the issue either reduce the number of filters to 512 (filter[512] not filter[2048];) or exclude filters at all.

**Comment by Capri2014** [comment]
@gsa88 Thanks for reporting this issue, and the corresponding fix #12047 has been merged.
