### ISSUE TITLE
Get data from Apollo/LGSVL using cyber

### ISSUE THREAD

**Issue by UYasher** [ApolloAuto/apollo#11985]
### System information

- **OS Platform and Distribution (Linux Ubuntu 20.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.5)**:

### Steps to reproduce the issue:
We are trying to use the python3 api to listen to the output of Apollo and lgsvl. For example, there is a topic /apollo/control with type control_cmd. We are trying to figure out how to modify the listener.py example to grab and display data from that topic. In particular, it would be helpful to know how we can import the control_cmd type.

**Comment by daohu527** [comment]
## solution

1.  Compile control_cmd.proto into a python file
2. Import to python and create a cyber node to read message
3. Subscribe and write messages
