### ISSUE TITLE
[Apollo 5.5] Camera images visualization

### ISSUE THREAD

**Issue by lucasnmatias** [ApolloAuto/apollo#11984]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04 
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: Apollo 5.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I've been trying to configure my usb cameras on Apollo, I can successfully see the images on Linux (outside Apollo) but I can't see the camera images inside apollo, the cyber_visualization just shows "No Image" and with cyber_monitor the channel for the images does not receive messages. For now I don't want to start the perception I just want to correctly configure the cameras and see the images inside apollo.

### Supporting materials (screenshots, command lines, code/script snippets):
Commands to start the cameras:

`sudo bash scripts/bootstrap.sh start`
`sudo bash scripts/camera.sh start`

Log output: 
I0730 23:23:12.410158 25815 usb_cam.cc:401] Capability flag: 0x0
I0730 23:23:12.410809 25815 usb_cam.cc:409] Set framerate to be 20
I0730 23:23:12.413022 25815 usb_cam.cc:435] Trigger enable, dev:/dev/video0, fps:20, internal:0
E0730 23:23:12.413348 25815 usb_cam.cc:443] trigger failed:-1
W0730 23:23:12.420054 25815 usb_cam.cc:863] camera
E0730 23:23:12.420080 25815 usb_cam.cc:867] Wrong Buffer Len: 0, dev: /dev/video0
W0730 23:23:13.193836 25834 usb_cam.cc:863] camera
W0730 23:23:13.260486 25836 usb_cam.cc:863] camera
W0730 23:23:13.327134 25819 usb_cam.cc:863] camera
W0730 23:23:13.393828 25819 usb_cam.cc:863] camera
W0730 23:23:13.460417 25819 usb_cam.cc:863] camera
W0730 23:23:13.527061 25837 usb_cam.cc:863] camera
W0730 23:23:13.593731 25837 usb_cam.cc:863] camera
W0730 23:23:13.660394 25842 usb_cam.cc:863] camera
W0730 23:23:13.727082 25842 usb_cam.cc:863] camera
W0730 23:23:13.793670 25815 usb_cam.cc:863] camera
W0730 23:23:13.860312 25843 usb_cam.cc:863] camera
W0730 23:23:13.926947 25843 usb_cam.cc:863] camera
W0730 23:23:13.993614 25843 usb_cam.cc:863] camera
W0730 23:23:14.060297 25843 usb_cam.cc:863] camera
W0730 23:23:14.126967 25843 usb_cam.cc:863] camera
W0730 23:23:14.193544 25837 usb_cam.cc:863] camera
W0730 23:23:14.260157 25842 usb_cam.cc:863] camera
W0730 23:23:14.326840 25842 usb_cam.cc:863] camera
W0730 23:23:14.393589 25842 usb_cam.cc:863] camera
W0730 23:23:14.460108 25842 usb_cam.cc:863] camera

It seems that the camera is starting but I can't see the data neither on cyber_monitor nor in cyber_visualizer.

**Comment by jinghaomiao** [comment]
@diegohu please take a look at this issue to help with USB cam in Apollo 5.5.

**Comment by lucasnmatias** [comment]
Actually I figured out the problem. I have been setting up the docker environment with root permissions and it seems that this have "messed up" with everything. After pulling again the apollo repo and running everything without sudo, the cameras worked as a charm. I'll close the issue and this here in case anyone have a similar problem.
