### ISSUE TITLE
Flaky test: throttle_63_test

### ISSUE THREAD

**Issue by siyangy** [ApolloAuto/apollo#120]
FAIL: //modules/canbus/vehicle/lincoln/protocol:throttle_63_test (see /home/siyangy/.cache/bazel/_bazel_siyangy/9ed9c7603857b144a49c9eb873c44a13/execroot/apollo/bazel-out/local-dbg/testlogs/modules/canbus/vehicle/lincoln/protocol/throttle_63_test/test.log).
INFO: From Testing //modules/canbus/vehicle/lincoln/protocol:throttle_63_test:
==================== Test output for //modules/canbus/vehicle/lincoln/protocol:throttle_63_test:
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Throttle63Test
[ RUN      ] Throttle63Test.General
modules/canbus/vehicle/lincoln/protocol/throttle_63_test.cc:32: Failure
Value of: cd.gas().throttle_enabled()
  Actual: true
Expected: false
[  FAILED  ] Throttle63Test.General (0 ms)
[----------] 1 test from Throttle63Test (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Throttle63Test.General

 1 FAILED TEST

The failure disappeared after I rerun it. @lianglia-apollo

**Comment by lianglia-apollo** [comment]
The data in lincoln/proto tests should be fixed. Will fix this issue soon.
