### ISSUE TITLE
Request of Supporting OpenCL

### ISSUE THREAD

**Issue by VentiOvaltine** [ApolloAuto/apollo#12006]
As for now, Apollo requires a Nvidia GPU for running it, but it is the fact that many computers like MacBooks does not include a Nvidia GPU. Furthermore, Intel is about to release a new series of GPU that will not support CUDA for sure. So, it would be great to support OpenCL for Apollo to expand the accessibility of this great project.

**Comment by ChihweiLHBird** [comment]
Got the same issue here. I was working with a high-end AMD GPU, and were not able to run Apollo smoothly.

**Comment by storypku** [comment]
> As for now, Apollo requires a Nvidia GPU for running it, but it is the fact that many computers like MacBooks does not include a Nvidia GPU. Furthermore, Intel is about to release a new series of GPU that will not support CUDA for sure. So, it would be great to support OpenCL for Apollo to expand the accessibility of this great project.

Thank you for your suggestion!  Accessibility is one of  our top-priority concern since Apollo 5.5. Currently, Apollo's support for arm64 boards (e.g. Nvidia Jetson Series)  and CPU-only machines was not complete yet. In the next months, we will work on resolving this.

However, limited to the shortage of manpower and resources，we may not be able to support many features for now. We will put them in our technical roadmap, and hopes that it won't keep you waiting for long.

Also cc @xiaoxq @jinghaomiao @ycool .

**Comment by storypku** [comment]
> Got the same issue here. I was working with a high-end AMD GPU, and were not able to run Apollo smoothly.

Could you please paste your AMD machine and GPU model, and describe the issue here ?

**Comment by jinghaomiao** [comment]
@VentiOvaltine @ChihweiLHBird Thanks for using Apollo. We'll keep this in mind and let you know if there's any update on this. @ChihweiLHBird We have never tested that on GPUs other than nVidia and cannot support provide the full suppor to that.

**Comment by ChihweiLHBird** [comment]
> > Got the same issue here. I was working with a high-end AMD GPU, and were not able to run Apollo smoothly.
> 
> Could you please paste your AMD machine and GPU model, and describe the issue here ?

Thank you very much for your response. The GPU model I got is AMD RX 5700. And the perception model only support CUDA with Nvidia GPU, according to the document.

**Comment by jinghaomiao** [comment]
> > > Got the same issue here. I was working with a high-end AMD GPU, and were not able to run Apollo smoothly.
> > 
> > 
> > Could you please paste your AMD machine and GPU model, and describe the issue here ?
> 
> Thank you very much for your response. The GPU model I got is AMD RX 5700. And the perception model only support CUDA with Nvidia GPU, according to the document.

@VentiOvaltine @ChihweiLHBird This ticket is being closed. Please feel free to raise new issues if needed. You are more than welcome to let us know your experience with AMD GPUs and contribute your code. Thanks for using Apollo.

**Comment by sinopec** [comment]
any updates about this issue?  
can we use opencl or cpu only perception now?
