### ISSUE TITLE
Could I use the lattice planner without the hdmap in Apollo5.0? 

### ISSUE THREAD

**Issue by HTL2018** [ApolloAuto/apollo#12001]
I noticed that the lattice planner + relative map works in Apollo3.0 from the previous issues,  could I use the lattice planner without the hdmap in Apollo5.0?

**Comment by jinghaomiao** [comment]
@HTL2018 No you won't be able to use lattice planner without HDMap. HDMap is mandatory. Thanks again for using Apollo. This issue is being closed. Please feel free to raise new issues if needed. Thanks again for using Apollo.

**Comment by marcusvinicius178** [comment]
@yifeijiang What must be done to use the Lattice planner in Apollo 5.0 or Apollo 6.0?
The issue is here:
https://github.com/ApolloAuto/apollo/issues/13828

I still could not change the ROAD_PUBLIC to the LATTICE planner properly. 
I have done a lot of attempts:
https://youtu.be/DXmFH81SCps
