### ISSUE TITLE
apollo5.0 Invalid bazel-bin link

### ISSUE THREAD

**Issue by wuzp986** [ApolloAuto/apollo#12008]
After apollo5.0 is successfully compiled, the bazel-bin link is invalid and cannot be debugged in vscode.
![IMG_20200722_085559](https://user-images.githubusercontent.com/57422562/89119003-3a591900-d4dd-11ea-880e-09c5d96e0e22.jpg)
![IMG_20200728_094159](https://user-images.githubusercontent.com/57422562/89119010-51980680-d4dd-11ea-9d0b-94e8aad4fa73.jpg)
![IMG_20200730_102735](https://user-images.githubusercontent.com/57422562/89118984-0c73d480-d4dd-11ea-9ab7-1131aa28fd63.jpg)

**Comment by jinghaomiao** [comment]
@wuzp986 thanks for using Apollo. We have not tested debugging inside vscode. Please work with vscode team on how to do it. This ticket is being closed. Please feel free to open new issues if you have any. Thank you~~
