### ISSUE TITLE
How to generate relative map?  What's the function of Navi planner of Apollo5.0?(如何生成相对地图？以及在导航规划器在Apollo5.0中能够实现什么功能？)

### ISSUE THREAD

**Issue by HTL2018** [ApolloAuto/apollo#12004]
### System information
- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.0)**:

![image](https://user-images.githubusercontent.com/45916696/89103495-dedb4c80-d444-11ea-9c0b-380211f0b45b.png)
from the docs [docs/howto/how_to_use_apollo_2.5_navigation_mode_cn.md](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode_cn.md)

Question 0: 
What's the function of Navi planner of Apollo5.0?  
导航规划器在Apollo5.0中能够实现什么功能？

Question 1: 
How to generate a relative map?  I noticed that the code [relative map](https://github.com/ApolloAuto/apollo/tree/master/modules/map/relative_map), but the readme is very simple, any other docs about it?
如何生成相对地图？我注意到有一个相对地图的文件夹，是否是用来生成相对地图的呢？reademe文件非常简单，有没有更详细的相关文档呢？

We want to realize some simple functions such as avoiding static obstacles and making correct decisions for the traffic signs on the ground in a closed area. But **we can't get the hdmap**. 

Question 2: 
For these simple functions, Relative map + Lattice planner works or not? (for Apollo5.0)
如何生成相对地图？在Apollo中使用lattice规划器+相对地图能否实现简单的避障和交通规则判断的功能？

Thank you! Looking forward to your reply.

**Comment by HTL2018** [comment]
@yifeijiang @jmtao @lemketron @hugomatic 
Looking forward to your replay. Thank you very much.

**Comment by daohu527** [comment]
> 如何生成相对地图？在Apollo中使用lattice规划器+相对地图能否实现简单的避障和交通规则判断的功能？

导航模式没有避障和交通规则
