### ISSUE TITLE
The vehicle's heading Interface in the Dreamview

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#12014]
I got a problem when I'm testing the Apollo Develop Kit.

do you know the code interface of the vehicle's heading in the Dreamview?
and the data of the vehicle's heading comes from which sensor?

Thank you very much!

**Comment by diegohu** [comment]
Heading information came from /apollo/sensor/gnss/heading channel by navigation device.

**Comment by diegohu** [comment]
About the "code interface of the vehicle's heading in the Dreamview", @unacao, could you give some advices?

**Comment by unacao** [comment]
Dreamview reads the ego car heading from localization topic https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/backend/simulation_world/simulation_world_service.cc#L458
