### ISSUE TITLE
[sim_control][dreamview][planning] Planning module not creating trajectories on DreamView when replaying a ROS bag 

### ISSUE THREAD

**Issue by salmanee** [ApolloAuto/apollo#12024]
### System information
- **OS Platform and Distribution:** Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5

### Steps to reproduce the issue:
**Main goal:** I want to manually modify the contents of a ros bag that corresponds to a specific scenario that I created using dreamland (ex. modify the initial state of the adc in the ros bag). Then I would run this modified scenario on apollo (without going through dreamland) to observe the planning behavior after the changes made. I followed these steps:

- Download a bag file for any scenario from Dreamland 
- Use `cyber_recoder split` to keep only: `/apollo/routing_respons`, `/apollo/localization/pose`, `/apollo/perception/obstacles` and `/apollo/perception/traffic_light`. 
- I also kept only few frames of the localization messages to get the car to a starting point. 
- Turned on `sim_control` and enabled the planning, routing and prediction modules. 
- Replayed the bag file.

**Result:** The ego car stops mid way (does not complete the scenario). It seems like it moved in the first part due to the recorded localization messages.  When I checked the planning messages through `cyber_monitor` it showed the following:
<img width="509" alt="Screen Shot 2020-08-03 at 3 08 23 PM" src="https://user-images.githubusercontent.com/14792262/89231945-38558f80-d59b-11ea-95cf-d0349053d423.png">

Any idea what can cause the planning module to not generate trajectories given the routing and perception info in the ros bag?

**Comment by jmtao** [comment]
@salmanee You need to keep prediction (/apollo/prediction). It is mandatory for planning module to run.

**Comment by salmanee** [comment]
Tried keeping /apollo/prediction and still running into the same issue.

**Comment by jmtao** [comment]
@salmanee go to <apollo>/data/log folder, and take a look at most recent planning logs (INFO.*, ERROR.*).

**Comment by salmanee** [comment]
@jmtao Thanks for your response! I checked the log files and it seems like something went wrong in the reference_line_provider.cc:
`E0806 12:24:38.497555 39814 reference_line_provider.cc:538] Failed to extract segments from routing
E0806 12:24:38.497560 39814 reference_line_provider.cc:580] Failed to create reference line from routing
E0806 12:24:38.497613 39814 reference_line_provider.cc:203] Fail to get reference line`

I'm also not quite sure if the setup I mentioned above is correct. Meaning that, will the record file with missing channels still run?

**Comment by jmtao** [comment]
@salmanee is the map used by the bag, the same as the one you select from DreamView?

**Comment by salmanee** [comment]
@jmtao yes.. Sunnyvalle

**Comment by jmtao** [comment]
@salmanee please also take a look at the log files from map.

**Comment by salmanee** [comment]
1) seems like there is an error with a lane_id?
`I0812 16:52:42.398316 69644 hdmap_util.cc:78] Load HDMap success: /apollo/modules/map/data/sunnyvale_loop/base_map.bin
F0812 16:52:53.817157 69657 pnc_map.cc:83] Check failed: lane Invalid lane id: 14851_1_-3`
2) /apollo/hmi/status screenshots:
<img width="477" alt="Screen Shot 2020-08-12 at 4 57 26 PM" src="https://user-images.githubusercontent.com/14792262/90079861-e9f07100-dcbd-11ea-8c4d-180b02dbfa37.png">

3) Dreamview screenshots: 
![Uploading Screen Shot 2020-08-12 at 5.07.27 PM.png…]()

**Comment by jmtao** [comment]
@salmanee map mismatch. the bag is using "sunnyvale_loop" map.
