### ISSUE TITLE
How to locate the object around the ego vehicle?

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#12033]
Hello team,

Recently, I am working on Apollo 5.0 and I try to obtain the location(like: x, y, z) of the objects around the ego vehicle, the objects can be NPC vehicle, pedestrain, and so on. Is there any way for me to obtain the position?

**Comment by jmtao** [comment]
@ForresterLu You can get it from the message published by perception module. "/apollo/perception/obstacles".
The proto is defined at: https://github.com/ApolloAuto/apollo/blob/master/modules/perception/proto/perception_obstacle.proto#L169
You can find the location(x,y,z) for each obstacle via this field: https://github.com/ApolloAuto/apollo/blob/master/modules/perception/proto/perception_obstacle.proto#L59

**Comment by ForresterLu** [comment]
> @ForresterLu You can get it from the message published by perception module. "/apollo/perception/obstacles".
> The proto is defined at: https://github.com/ApolloAuto/apollo/blob/master/modules/perception/proto/perception_obstacle.proto#L169
> You can find the location(x,y,z) for each obstacle via this field: https://github.com/ApolloAuto/apollo/blob/master/modules/perception/proto/perception_obstacle.proto#L59

@jmtao Thanks for your reply, I have check the `perception_obstacle` [file](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/proto/perception_obstacle.proto), but I don't know how it works, and I have several questions as following?

> What I want to do is when the ego vehicle is running with Apollo, my python script can obtain the location of the objects around the ego vehicle, so can that file obtain objects location at runtime, if can, how can I get these information at runtime in my python script?

> Can you kindly give me an example to show how to obtain the location at runtime? Thanks~

**Comment by daohu527** [comment]
## Record cmd
There is already a tool "cyber_recorder" that records runtime informations, including "obstacles" and other messages. You can use it to save runtime data in a file with the suffix ".record".
```
cyber_recorder record -a
```
Then you can use below command the play the file and see the message in "cyber_monitor".  
```
cyber_recorder play -f xxx.record
```

The cyber_recorder help [doc](https://github.com/ApolloAuto/apollo/blob/bf2b3730835fd5a98f91a5fb00f9d82ef750be9d/cyber/doxy-docs/source/CyberRT_Developer_Tools.md)  

## Pyhton API
If you want to deal with by yourself you should see some example by python api [doc](https://github.com/ApolloAuto/apollo/blob/b0833bc0d93797e91ab9d2971e4843c0b0b4c0e2/cyber/doxy-docs/source/CyberRT_Python_API.md#41-read-from-channel-in-cyberpythonexampleslistenerpy)

**Comment by ForresterLu** [comment]
> ## Record cmd
> There is already a tool "cyber_recorder" that records runtime informations, including "obstacles" and other messages. You can use it to save runtime data in a file with the suffix ".record".
> 
> ```
> cyber_recorder record -a
> ```
> 
> Then you can use below command the play the file and see the message in "cyber_monitor".
> 
> ```
> cyber_recorder play -f xxx.record
> ```
> 
> The cyber_recorder help [doc](https://github.com/ApolloAuto/apollo/blob/bf2b3730835fd5a98f91a5fb00f9d82ef750be9d/cyber/doxy-docs/source/CyberRT_Developer_Tools.md)
> 
> ## Pyhton API
> If you want to deal with by yourself you should see some example by python api [doc](https://github.com/ApolloAuto/apollo/blob/b0833bc0d93797e91ab9d2971e4843c0b0b4c0e2/cyber/doxy-docs/source/CyberRT_Python_API.md#41-read-from-channel-in-cyberpythonexampleslistenerpy)

Thank you, I will try it.
