### ISSUE TITLE
Question: Usage of CAN bus data of LGSVL

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#12030]
Hello,

I use LGSVL simulator and Apollo 3.0
I want to pack the [CAN bus sensor data of the LGSVL](https://www.lgsvlsimulator.com/docs/sensor-json-options/#can-bus) into CAN messages and send it to the CAN bus using a USB-CAN adapter. How can I do this?
I know that Apollo receives this via topic /apollo/canbus/chassis.
Please help!!!!!!!

**Comment by jinghaomiao** [comment]
@ashwinsarvesh thanks for using Apollo. Please refer to https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/radar for sensors with CAN interfaces (radar, or smarteye).

**Comment by ashwinsarvesh** [comment]
Thank you
Does Apollo provide support to [socketcan ](https://en.wikipedia.org/wiki/SocketCAN )framework of Linux?
I mean can I send can messages to the can interface connected to my PC from Apollo using socketcan

**Comment by daohu527** [comment]
Seems Apollo already support socket can, you can ref to "modules/drivers/canbus/can_client/socket"

**Comment by Capri2014** [comment]
Looks like this has been resolved.
