### ISSUE TITLE
pytorch version for apollo 5.0 aarch64

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#12040]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**: apollo.sh build_cpu
error encountered.

ERROR: (08-05 15:14:55.437) /apollo/modules/prediction/evaluator/vehicle/BUILD:157:1: C++ compilation of rule '//modules/prediction/evaluator/vehicle:junction_map_evaluator' failed (Exit 1).
modules/prediction/evaluator/vehicle/junction_map_evaluator.cc: In member function 'virtual bool apollo::prediction::JunctionMapEvaluator::Evaluate(apollo::prediction::Obstacle*)':
modules/prediction/evaluator/vehicle/junction_map_evaluator.cc:95:38: error: 'torch::jit::Tuple' has not been declared
   torch_inputs.push_back(torch::jit::Tuple::create(
                                      ^

Let us know which pytorch version should be used for apollo 5.0 aarch64

**Comment by jinghaomiao** [comment]
Torch is not supported in ARM docker environment at this moment. If there's any update on ARM docker image, we'll keep you updated. This ticket is being closed. Please feel free to reaise other issues if needed. Thanks for using Apollo.
