### ISSUE TITLE
Query : Does any node inside the Perception module subscribe to the Perception Module 

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#12041]
Hi,
I have the following query regarding the Perception module of Apollo. 
Do any of the nodes like TrafficLight Detection, Lane Flow Detection, etc, which are inside the Perception module, subscribe to the final output of the Perception module (ie final traffic type and final object type, published via the trafficlights_perception_component.cc and fusion_component.cc respectively)? 

Thanks in advance.

### Supporting materials 
![Perception](https://user-images.githubusercontent.com/50120641/89387339-a2d50f80-d702-11ea-9365-bafeaefe66a4.png)

**Comment by daohu527** [comment]
As you said "Inside the Perception module subscribe to the final output of the Perception module". I haven't found it yet.

**Comment by jinghaomiao** [comment]
Nope. A cyclic subscription is not supported and not encouraged in Apollo. This ticket is being closed. Please feel free to reaise other issues if needed. Thanks for using Apollo.
