### ISSUE TITLE
Question: How To Collect Sensor Data (Camera, Localization, and Lidar) of EGO Vehicle In Cyber RT Runtime?

### ISSUE THREAD

**Issue by ChihweiLHBird** [ApolloAuto/apollo#12043]
We are working on a project, and we would like to record all the sensor data in the runtime and save it to a file. We tried a Python script:
```
from cyber.python.cyber_py3 import cyber
from modules.drivers.proto.sensor_image import CompressedImage

import numpy as np
import cv2

def on_image(image):
  print("Received image:")
  print("  format =", image.format)
  print("  data =", len(image.data), "bytes")

  arr = np.fromstring(image.data, np.uint8)
  img = cv2.imdecode(arr, cv2.CV_LOAD_IMAGE_COLOR)
  print("  size = {}x{}".format(img.shape[1], img.shape[0]))


if __name__ == '__main__':
  cyber.init()
  node = cyber.Node("MyNodeName")
  node.create_reader("/apollo/sensor/camera/front_6mm/image/compressed", CompressedImage, on_image)
  node.spin()
  cyber.shutdown()
```
But it failed to import `CompressedImage` and said `modules.drivers.proto.sensor_image` is not a module.

We also tried the developer tool, `cyber-recorder` 
https://cyber-rt.readthedocs.io/en/latest/CyberRT_Developer_Tools.html?highlight=sensor%20data#cyber-recorder
We did get a record file but it seems doesn't include any sensor data when we was re-playing the record.

I am wondering if you have a way to record the sensor data. Thank you for helping us!

### System information

- **OS Platform and Distribution Ubuntu 20.04**:
- **Apollo installed from `pre6` branch**:
- **Apollo version 6.0**:

**Comment by daohu527** [comment]
No sure what's the problem. But there is no problem with your method, I think it may be other error.  

1. Make sure there are sensor messages use "cyber_monitor"
2. Check if there is an error log when running "cyber-recorder" ?

**Comment by jmtao** [comment]
@ChihweiLHBird you can refer to these scripts as sample code:
https://github.com/ApolloAuto/apollo/blob/master/scripts/record_bag.py

**Comment by jinghaomiao** [comment]
@michael4338 can you please help?

**Comment by michael4338** [comment]
@jinghaomiao sure thing

I think @daohu527 and @jmtao made good points
1. first please make sure the topic "/apollo/sensor/camera/front_6mm/image/compressed" is present in cyber_monitor
2. second you can run https://github.com/ApolloAuto/apollo/blob/master/scripts/record_bag.py (`python record_bag.py --all`) to record it

**Comment by jinghaomiao** [comment]
@ChihweiLHBird Hope your questions are answered.  This ticket is being closed. Please feel free to raise new issues if needed. Thanks for using Apollo.
