### ISSUE TITLE
apollo 控制模块使用了 超前滞后 这个控制算法了吗

### ISSUE THREAD

**Issue by liukr001** [ApolloAuto/apollo#12044]
System information
- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version (5.5,)**:
最近在看control模块里面的内容，再commom目录下有超前滞后的控制算法，但是再controller目录下具体的控制算法代码中、并没有发现有使用它的记录。如果要使用，需要怎么配置呢

**Comment by Capri2014** [comment]
Do you mean the lead-lag filter ? No in latest master, it is been replaced by MRAC since the later one is more easier to balance agility vs robustness as well as more easier in self parameter adaption. Thus more suitable for Apollo which needs to support different vehicle platforms.
