### ISSUE TITLE
Question: Regarding changing the ADAS algorithms of Apollo

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#12056]
Hello,

I am doing a project which requires me to develop a software program. This program has to send software updates that modify the Apollo's ADAS algorithms (similar to OTA updates). And I have to validate whether the changes work using LGSVL simulator 
Can I connect with someone who has already worked on a similar topic or someone in this community can guide me?

I use Apollo 3.0

**Comment by jinghaomiao** [comment]
@ashwinsarvesh thanks for using Apollo. The funtion is not supported in Apollo yet. The team will keep you updated if there's an update on that. Thanks again. This ticket is being closed. Please feel free to raise other issues if needed.

**Comment by ashwinsarvesh** [comment]
Hello @jinghaomiao 
Thank you for your reply.
I know that it is not supported by Apollo. But I am trying to connect with people who are working on a similar topic.
If this is not the right forum to ask this question, could you tell me where to post this question :)
