### ISSUE TITLE
Install apollo in centos system

### ISSUE THREAD

**Issue by rubingLi** [ApolloAuto/apollo#12068]
Since apollo is running in a docker container, can I install docker in the centos system and then install apollo?
既然apollo是运行在docker 容器中，那么我可以在centos系统中安装docker，然后安装apollo吗

**Comment by daohu527** [comment]
It seems feasible, but I don’t think it is recommended. 

First, you need to make sure that the kernel version of the system is the same. Second, you need to pay attention to whether some library files are compatible.

**Comment by storypku** [comment]
> Since apollo is running in a docker container, can I install docker in the centos system and then install apollo?
> 既然apollo是运行在docker 容器中，那么我可以在centos系统中安装docker，然后安装apollo吗

I think It should be relatively easy to install Apollo docker on a CentOS system. But we haven't test this yet. You can have a try if you have some experience developing on Linux and using docker. Share your experience with everyone here if you would like.

**Comment by jinghaomiao** [comment]
This ticket is being closed. Please raise other issues if needed. Thanks for using Apollo.
