### ISSUE TITLE
aarch 64 map build error

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#12067]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master

### Steps to reproduce the issue:
While running a build, occurred below errors
(02:47:08) ERROR: /apollo/modules/map/pnc_map/BUILD:7:13: error while parsing .d file: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/aarch64-fastbuild/bin/modules/map/pnc_map/_objs/cuda_pnc_util/cuda_util.pic.d (No such file or directory)

looks related with cuda, do we need to install something related with cuda?

We used dev-aarch64-18.04-20200731_0916 docker

**Comment by storypku** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04
> * **Apollo installed from (source or binary)**: source
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
> 
> ### Steps to reproduce the issue:
> While running a build, occurred below errors
> (02:47:08) ERROR: /apollo/modules/map/pnc_map/BUILD:7:13: error while parsing .d file: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/aarch64-fastbuild/bin/modules/map/pnc_map/_objs/cuda_pnc_util/cuda_util.pic.d (No such file or directory)
> 
> looks related with cuda, do we need to install something related with cuda?
> 
> We used dev-aarch64-18.04-20200731_0916 docker
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):

This aarch64 image was expected to run on NVidia Jetson boards (TX2, Xavier, ...). However, as I said in other issues, our support for aarch64 was not complete yet. I personally had only tested dev.aarch64 image for building and testing the CyberRT framework. Hopes that we can make dev.aarch64 ready in the next few months. Once we are ready, we should have everyone noticed.

**Comment by storypku** [comment]
This issue should have  already been fixed in master HEAD. 
Please pull the latest master and try again. 

I'm closing this issue now. If you have other questions, feel free to create another issue or reopen this one if the problem persists.

**Comment by hello-big-world** [comment]
@storypku apollo5.5 aarch64 docker images can't be downloaded.
