### ISSUE TITLE
/apollo/cyber/BUILD:59:1: no such package '@fastrtps//'

### ISSUE THREAD

**Issue by aidenyao** [ApolloAuto/apollo#12076]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from source**:
- **Apollo version  5.5**:

### Steps to reproduce the issue:
I want to build cyber samples  outside of apollo workspace(path is: /apollo), but error happend: ".cache/bazel/_bazel_evacleanrobot/81e650e849e0396a5b493f71ce3a2522/external/apollo/cyber/BUILD:59:1: no such package '@fastrtps//': The repository could not be resolved and referenced by '@apollo//cyber:cyber_core'."。
My  test project structure:

$DOCKER_HOME/test/
                    examples/
                           BUILD
                    WORKSPACE

WORKSPACE: 
local_repository(
    name = "apollo",
    path = "/apollo",
)

#protobuf 3.3
http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.3.0",
    url = "file:///media/sz-neuron/wd/apollo_third_libs/protobuf-3.3.0.tar.gz",
)

BUILD: 
load("@apollo//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "talker",
    srcs = ["talker.cc"],
    deps = [
        "@apollo//cyber",
        "//examples/proto:examples_cc_proto",
    ],
)

cc_binary(
    name = "listener",
    srcs = ["listener.cc"],
    deps = [
        "@apollo//cyber",
        "//examples/proto:examples_cc_proto",
    ],
)

cc_binary(
    name = "paramserver",
    srcs = ["paramserver.cc"],
    deps = [
        "@apollo//cyber",
        "@apollo//cyber/parameter",
    ],
)

cc_binary(
    name = "service",
    srcs = ["service.cc"],
    deps = [
        "@apollo//cyber",
        "//examples/proto:examples_cc_proto",
    ],
)

cc_binary(
    name = "record",
    srcs = ["record.cc"],
    deps = [
        "@apollo//cyber",
        "@apollo//cyber/proto:record_cc_proto",
    ],
)

cpplint()

**Comment by storypku** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
> * **Apollo installed from source**:
> * **Apollo version  5.5**:
> 
> ### Steps to reproduce the issue:
> I want to build cyber samples outside of apollo workspace(path is: /apollo), but error happend: ".cache/bazel/_bazel_evacleanrobot/81e650e849e0396a5b493f71ce3a2522/external/apollo/cyber/BUILD:59:1: no such package '@fastrtps//': The repository could not be resolved and referenced by '@apollo//cyber:cyber_core'."。
> My test project structure:
> 
> $DOCKER_HOME/test/
> examples/
> BUILD
> WORKSPACE
> 
> WORKSPACE:
> local_repository(
> name = "apollo",
> path = "/apollo",
> )
> 
> #protobuf 3.3
> http_archive(
> name = "com_google_protobuf",
> strip_prefix = "protobuf-3.3.0",
> url = "file:///media/sz-neuron/wd/apollo_third_libs/protobuf-3.3.0.tar.gz",
> )
> 
> BUILD:
> load("@apollo//tools:cpplint.bzl", "cpplint")
> 
> package(default_visibility = ["//visibility:public"])
> 
> cc_binary(
> name = "talker",
> srcs = ["talker.cc"],
> deps = [
> "@apollo//cyber",
> "//examples/proto:examples_cc_proto",
> ],
> )
> 
> cc_binary(
> name = "listener",
> srcs = ["listener.cc"],
> deps = [
> "@apollo//cyber",
> "//examples/proto:examples_cc_proto",
> ],
> )
> 
> cc_binary(
> name = "paramserver",
> srcs = ["paramserver.cc"],
> deps = [
> "@apollo//cyber",
> "@apollo//cyber/parameter",
> ],
> )
> 
> cc_binary(
> name = "service",
> srcs = ["service.cc"],
> deps = [
> "@apollo//cyber",
> "//examples/proto:examples_cc_proto",
> ],
> )
> 
> cc_binary(
> name = "record",
> srcs = ["record.cc"],
> deps = [
> "@apollo//cyber",
> "@apollo//cyber/proto:record_cc_proto",
> ],
> )
> 
> cpplint()
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):

This was an issue on Bazel external dependencies. To use Apollo as a submodule, please use the latest `master` branch for an easy experience.

The following was an example on how to enable it.

```
workspace(name = "demo_project")

local_repository(
    name = "apollo",
    path = "/apollo",
)

new_local_repository(
    name = "cyber_record",
    build_file = "cyber_record.BUILD",
    path = "/usr/local/include/cyber",
)

load("@apollo//tools:workspace.bzl", "apollo_repositories")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

apollo_repositories()

http_archive(
    name = "bazel_skylib",
    sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz"],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

http_archive(
    name = "rules_proto",
    sha256 = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208",
    strip_prefix = "rules_proto-97d8af4dc474595af3900dd85cb3a29ad28cc313",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

http_archive(
    name = "rules_python",
    sha256 = "b5668cde8bb6e3515057ef465a35ad712214962f0b3a314e551204266c7be90c",
    strip_prefix = "rules_python-0.0.2",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.2/rules_python-0.0.2.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "419dba362eaf8f1d36849ceee17c3e2ff8ff12ac666b42d3ff02a164ebe090e9",
    strip_prefix = "grpc-1.30.0",
    urls = ["https://github.com/grpc/grpc/archive/v1.30.0.tar.gz"],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
```

**Comment by storypku** [comment]
Please refer to [Bazel: Transitive Dependencies](https://docs.bazel.build/versions/master/external.html#transitive-dependencies) for a thorough understanding.

**Comment by storypku** [comment]
This issue should be closed now as it has more to do with `Bazel` than with `Apollo`.  If you has other questions, please feel free to create another issue.
