### ISSUE TITLE
Help needed: Apollo 3.0 ADAS algorithms

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#12070]
Hello,

I am doing a project which requires me to develop a software program. This program has to change Apollo's ADAS algorithms. And I have to validate whether the changes work using the LGSVL simulator.

So the problem now is, in the [Perception folder](https://github.com/ApolloAuto/apollo/tree/v3.0.0/modules/perception), a lot of folders are there which contains a lot of files. But I do not get the flow of the perception process.(I mean which files to refer in which order).
Can someone help me to understand the perception flow and help me to find where exactly the ADAS algorithms like Obstacle detection and Lane detection are processed, so that I can modify them?

Note: I have already read the available documents on the github page!

**Comment by daohu527** [comment]
## Architecture
In general, you can refer to this process, which outlines **traffic signal detection, lane/flow detection, object detection**. [doc](https://github.com/ApolloAuto/apollo/blob/b6e75a642afba7ff9fc07bb00a4e750e17a22347/modules/perception/Perception_README_3_5.md#architecture)  

In addition, you can distinguish different modules based on the sensor. Taking camera as an example, it includes “traffic signal detection, lane/flow detection, object detection”, but Radar just includes "object detection".

## Approximate process
code process
```
production -> onboard -> camera / lidar / radar -> fusion
```
deep learning inference
```
perception/production/data (model) -> inference
```

**Comment by ashwinsarvesh** [comment]
Hello, Thank you for your reply.
I guess your answers are based on the latest Apollo.
Can you help me with Apollo 3.0?

**Comment by daohu527** [comment]
This Note will help [Apollo-Note](https://github.com/YannZyl/Apollo-Note)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
