### ISSUE TITLE
[Perception] Lidar Obstacle Detection fails to detect random shape obstacle.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12073]
Issue
---

Hi team, 

Recently I've been trying Apollo's lidar perception module with LGSVL simulator. 
I generated a bunch of random-shaped obstacles, and Apollo lidar detection fails to detect some of them. 

Here's one example.
![random_shape_not_detected_static2](https://user-images.githubusercontent.com/16061105/89735761-5a697900-da97-11ea-9b12-edd1e2680b60.png)

Steps to reproduce
---
here's a [bag file (point cloud data included)](https://drive.google.com/file/d/1r1UWwgU8ZMPvROgGwH1ePRs4eEB2CR6X/view?usp=sharing) recorded during runtime when lidar perception failed to work.

* build Apollo `pre6` branch.
* start `boostrap_lgsvl.sh`
* configure in Dreamview
    * Setup mode: `Mkz Lgsvl`
    * Vehicle: `Lincoln2017MKZ LGSVL`
    * map: `Borregas Ave`
* download and save the recording file as `xxx.rec`
* `cyber_recorder play -l -f xxx.rec`

Expected behavior
--- 
Although the shape is randomly generated, the lidar points were there and 
from a human's perspective, clearly there was something big in front of the ego vehicle. 
I believe it's proper for Apollo to **at least produce an unknown obstacle** ahead.

Configurations
---

Below is my dag file for lidar perception:

```
module_config {
  module_library : "/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so"

 components {
    class_name : "SegmentationComponent"
    config {
      name: "Velodyne128Segmentation"
      config_file_path: "/apollo/modules/perception/production/conf/perception/lidar/velodyne128_segmentation_conf_lgsvl.pb.txt"
      flag_file_path: "/apollo/modules/perception/production/conf/perception/perception_common.flag"
      readers {
          channel: "/apollo/sensor/lidar128/compensator/PointCloud2"
        }
    }
  }

  components {
    class_name : "RecognitionComponent"
    config {
      name: "RecognitionComponent"
      config_file_path: "/apollo/modules/perception/production/conf/perception/lidar/recognition_conf.pb.txt"
      readers {
          channel: "/perception/inner/SegmentationObjects"
        }
    }
  }

  components {
    class_name: "FusionComponent"
    config {
      name: "SensorFusion"
      config_file_path: "/apollo/modules/perception/production/conf/perception/fusion/fusion_component_conf.pb.txt"
      readers {
          channel: "/perception/inner/PrefusedObjects"
        }
    }
  }
}

```

Please let me know if any other resources are needed to verify this. Thanks.

**Comment by ntutangyun** [comment]
Here is the update of another run. In this case, I placed a normal vehicle aside to show that the Perception is at least doing something. 

[recording file](https://drive.google.com/file/d/1vj39Q5W8lgGbayY56F9kL7MTIWo_V67K/view?usp=sharing)

[Video](https://drive.google.com/file/d/10eEIEM3Dg6PoQXDW2n3gBg0qzO18TTKq/view?usp=sharing)

**Comment by ntutangyun** [comment]
my initial investigation is that the CNN Segmentation failed to produce a segmented object for the random-shape obstacle.

**Comment by jeroldchen** [comment]
Hi @ntutangyun , segmentation method is no longer maintained, as we have set PointPillars as perception's lidar detection method. Thank you for your interest in Apollo.
