### ISSUE TITLE
mainboard 是怎么启动模块并读取参数的？

### ISSUE THREAD

**Issue by liukr001** [ApolloAuto/apollo#12071]
启动模块的具体过程，比如用cyber_launch start  xxxx.launch 启动，
调用mainboard函数，里面是怎么解析 dag文件，并且怎么通过dag文件读取xxx.pb.txt
参数配置文件？
我在看这部分的代码的时候，层层找，最终看到的具体执行语句是：
google::SetCommandLineOption("flagfile", flag_file_path.c_str());
这个语句式检查gflag 里面定义的变量 flagfile 和  flag_file_path.c_str()  是否一致,那也就是说，
在此之前已经定义了 flagfile 变量的值，但是好像也没有看到有定义它呢？
除此之外，并没有进行读取xxx.pb.txt操作。
谢谢

**Comment by daohu527** [comment]
## Enter
Use "module_args.ParseArgument(argc, argv)" to get parameters.
https://github.com/ApolloAuto/apollo/blob/6def7aa571700b34fb4a28baa9a75d9212628b7a/cyber/mainboard/mainboard.cc#L27-L36

You are talking about the way to get "flag_file_path", but not "config_file_path". And .pb.txt is in config_file_path.  
https://github.com/ApolloAuto/apollo/blob/6ad8ef304edb14aa9b00e871dcd06f103ac95d5b/modules/planning/dag/planning.dag#L7-L9

Then use "GetProtoConfig" to read config to proto
https://github.com/ApolloAuto/apollo/blob/4c5ee6524966f8964b54cc9bbfa44dc6201e9dd3/cyber/component/component_base.h#L60-L63

**Comment by liukr001** [comment]
> ## Enter
> 
> Use "module_args.ParseArgument(argc, argv)" to get parameters.
> 
> https://github.com/ApolloAuto/apollo/blob/6def7aa571700b34fb4a28baa9a75d9212628b7a/cyber/mainboard/mainboard.cc#L27-L36
> 
> You are talking about the way to get "flag_file_path", but not "config_file_path". And .pb.txt is in config_file_path.
> 
> https://github.com/ApolloAuto/apollo/blob/6ad8ef304edb14aa9b00e871dcd06f103ac95d5b/modules/planning/dag/planning.dag#L7-L9
> 
> ## read config
> 
> Then use "GetProtoConfig" to read config to proto
> 
> https://github.com/ApolloAuto/apollo/blob/4c5ee6524966f8964b54cc9bbfa44dc6201e9dd3/cyber/component/component_base.h#L60-L63

Hi, I reviewed the content under the component file and the content in xxxcomponent.cc under each module and the inheritance relationship between them; I probably understood it.

But there is still a problem, such as
The variables in the planning.conf file should be defined in planning_gflags.h before they can be used again (or can be reassigned in the planning.conf file);
If the variables in the planning.conf file are not defined in planning_gflags.h, the program will report an error. Before doing Dkit experiments, after adding some new variables according to the tutorial, an error occurred, indicating that the serialization of the added variables failed.

**Comment by liukr001** [comment]
> ## Enter
> 
> Use "module_args.ParseArgument(argc, argv)" to get parameters.
> 
> https://github.com/ApolloAuto/apollo/blob/6def7aa571700b34fb4a28baa9a75d9212628b7a/cyber/mainboard/mainboard.cc#L27-L36
> 
> You are talking about the way to get "flag_file_path", but not "config_file_path". And .pb.txt is in config_file_path.
> 
> https://github.com/ApolloAuto/apollo/blob/6ad8ef304edb14aa9b00e871dcd06f103ac95d5b/modules/planning/dag/planning.dag#L7-L9
> 
> ## read config
> 
> Then use "GetProtoConfig" to read config to proto
> 
> https://github.com/ApolloAuto/apollo/blob/4c5ee6524966f8964b54cc9bbfa44dc6201e9dd3/cyber/component/component_base.h#L60-L63

你好，我重新看了下component文件下的内容以及各个模块下的xxxcomponent.cc中的内容和它们之间的继承关系；我大概看懂了。

但是还有个问题，比如在
planning.conf文件里面的变量，是不是都应该在planning_gflags.h里面定义后，才能在再使用（或者在planning.conf文件里面才可以重新赋值）；
如果planning.conf文件里面的变量，没有在planning_gflags.h里面定义，程序会报错吧。之前在做Dkit的实验，按照教程添加了一些新的变量之后，出现错误，提示添加的那些变量序列化失败,后来把添加的变量删除了，就没有报错。

**Comment by daohu527** [comment]
**It looks like this**, I will look at the principle in detail later.

**Comment by storypku** [comment]
> 但是还有个问题，比如在
> planning.conf文件里面的变量，是不是都应该在planning_gflags.h里面定义后，才能在再使用（或者在planning.conf文件里面才可以重新赋值）；
> 如果planning.conf文件里面的变量，没有在planning_gflags.h里面定义，程序会报错吧。之前在做Dkit的实验，按照教程添加了一些新的变量之后，出现错误，提示添加的那些变量序列化失败,后来把添加的变量删除了，就没有报错。

You are right. Every flag  in the  flagfile (`planning.conf`) should be defined in corresponding header (`planning_gflags.h`).

**Comment by storypku** [comment]
This issue is going to be closed now. Thanks for using Apollo, and D-kit. :)  If you have other questions, please feel free to open another issue.
