### ISSUE TITLE
[perception] apollo lidar obstacle detection messed up by a random shape object. 

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12085]
Issue
---

Hi team, 

Recently I've been trying Apollo's lidar perception module with LGSVL simulator. 
I've encountered the following case:
* when there is no random-shape obstacle added, the lidar perception works fine. ([recording by cyber_recorder](https://drive.google.com/file/d/1IdbZEgTKfpYpaVC4YOzzS6qne7aKzHJd/view?usp=sharing))
* when a random-shape obstacle added in front, the number of obstacles detected seemed to be messed up. ([recording by cyber_recorder](https://drive.google.com/file/d/1YVNeFOSvKPtNM5VFW4Y2G9iACjBlF70E/view?usp=sharing))

Here's a screenshot when one vehicle is detected correctly.
![norma_1obs](https://user-images.githubusercontent.com/16061105/89792846-a976e300-db57-11ea-9728-910f256e4acf.png)

Here's a screenshot when two vehicles are detected correctly.
![normal_2obs](https://user-images.githubusercontent.com/16061105/89792902-c14e6700-db57-11ea-8586-dd66b6631add.png)

Here's one vehicle plus one random-shape obstacle, detected normally.
![random_shape_normal](https://user-images.githubusercontent.com/16061105/89793014-e6db7080-db57-11ea-8bdb-37f444e5c5a2.png)

But when the second vehicle is spawned, without changing the rest, 
the lidar perception produces **5 obstacles** in the result, which by right should be **3 obstacles**.  
Two additional "ghost" obstacles appeared, where one is directly below the Apollo car and the other one behind the random-shape obstacle. 

![random_shape_abnormal](https://user-images.githubusercontent.com/16061105/89793273-3fab0900-db58-11ea-8deb-a997f3015b3f.png)

Steps to reproduce
---
* build Apollo `pre6` branch.
* start `boostrap_lgsvl.sh`
* configure in Dreamview
    * Setup mode: `Mkz Lgsvl`
    * Vehicle: `Lincoln2017MKZ LGSVL`
    * map: `Borregas Ave`
* download and save the recording files as `xxx.rec`
* `cyber_recorder play -l -f xxx.rec`

Configurations
---

Below is my dag file for lidar perception:

```
module_config {
  module_library : "/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so"

 components {
    class_name : "SegmentationComponent"
    config {
      name: "Velodyne128Segmentation"
      config_file_path: "/apollo/modules/perception/production/conf/perception/lidar/velodyne128_segmentation_conf_lgsvl.pb.txt"
      flag_file_path: "/apollo/modules/perception/production/conf/perception/perception_common.flag"
      readers {
          channel: "/apollo/sensor/lidar128/compensator/PointCloud2"
        }
    }
  }

  components {
    class_name : "RecognitionComponent"
    config {
      name: "RecognitionComponent"
      config_file_path: "/apollo/modules/perception/production/conf/perception/lidar/recognition_conf.pb.txt"
      readers {
          channel: "/perception/inner/SegmentationObjects"
        }
    }
  }

  components {
    class_name: "FusionComponent"
    config {
      name: "SensorFusion"
      config_file_path: "/apollo/modules/perception/production/conf/perception/fusion/fusion_component_conf.pb.txt"
      readers {
          channel: "/perception/inner/PrefusedObjects"
        }
    }
  }
}

```

Please let me know if any other resources are needed to verify this. Thanks.

**Comment by jeroldchen** [comment]
Please refer to #12073 .
