### ISSUE TITLE
Parse out information from demo_2.0.bag

### ISSUE THREAD

**Issue by rubingLi** [ApolloAuto/apollo#12090]
Is there any tool that can parse out information from demo_2.0.bag？

**Comment by xiaoxq** [comment]
You should check out the Apollo 2.0 version and parse it with python. For example: https://github.com/ApolloAuto/apollo/blob/r2.0.0/modules/tools/rosbag/stat_mileage.py

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
