### ISSUE TITLE
Apollo Auto adapter_manager.h not found in Apollo 3.0

### ISSUE THREAD

**Issue by miewan** [ApolloAuto/apollo#12101]
I am trying to create IR for each files in Apollo Auto 3.0 using clang++

For files modules/tools/planning/planning_stats.cc, I get an error 'modules/common/adapters/adapter_manager.h' file not found

And I look at the directory, and there is no adapter_manager.h

Can anyone please tell me why this file is missing from apollo auto 3.0?

I also have the same error with terminal.cc file too

**Comment by xiaoxq** [comment]
We do have it:
https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/common/adapters/adapter_manager.h

Please try cleaning your repo and bazel cache and then rebuild.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
