### ISSUE TITLE
Uninstall version 3.0 and install the version master

### ISSUE THREAD

**Issue by rubingLi** [ApolloAuto/apollo#12113]
I originally installed the 3.0 version, and now I plan to install the  version master. How do I uninstall the 3.0 version?
我原本安装了3.0版本，现在打算安装master版本，请问如何卸载3.0版本呢

**Comment by daohu527** [comment]
I think the process is roughly as follows:  
1. Delete the old docker.  
2. Pull the latest code and install again.

**Comment by storypku** [comment]
Can you please provide more details ?

**Comment by jinghaomiao** [comment]
@rubingLi Hope your question is answered. This ticket is being closed. Please feel free to raise new issues if needed, Thanks for using Apollo.
