### ISSUE TITLE
Not sourcing apollo_base.sh

### ISSUE THREAD

**Issue by anchans** [ApolloAuto/apollo#12115]
Missing sourcing of `/apollo/scripts/apollo_base.sh` in `/apollo/scripts/docker_start_user.sh` leading to no addition of apollo paths in environment.

**Comment by storypku** [comment]
As with this PR https://github.com/ApolloAuto/apollo/pull/12106 , many functions in `scripts/apollo_base.sh` was moved to `scripts/apollo.bashrc`. And `cyber/setup.bash` was sourced in `$HOME/.bash_aliases`.  So most of Apollo paths was added.
