### ISSUE TITLE
Is it okay to using hesai 40p in the newest  apollo?

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#12111]
As we can see, hesai40p's driver is included in apollo. Can we directly using 40p without modify apollo code ?

**Comment by diegohu** [comment]
@oska874 yes, you can use the hesai 40p's driver in Apollo directly.

**Comment by diegohu** [comment]
We had a close-loop testing in D-KIT based on Apollo5.5. It works well.

**Comment by oska874** [comment]
> @oska874 yes, you can use the hesai 40p's driver in Apollo directly.

And  the lidar  model can also be used with  hesai40p ?

**Comment by diegohu** [comment]
> lidar model

You mean perception model? It works well.

**Comment by storypku** [comment]
This issue is going to be closed now. If you have other questions, please feel free to file another issue.

Thanks for using Apollo！
