### ISSUE TITLE
Error while running tool scripts

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#12136]
**Describe the bug**
Following the instructions here - https://github.com/ApolloAuto/apollo/tree/master/modules/tools
The scripts like plot_trace.sh and rtk_recorder throw an error:

Traceback (most recent call last):
  File "./modules/tools/plot_trace/plot_trace.py", line 26, in <module>
    from modules.canbus.proto import chassis_pb2
ImportError: cannot import name 'chassis_pb2'

**To Reproduce**
1. ./apollo.sh build
2. source scripts/apollo_base.sh
3. ./scripts/plot_trace.sh 

 - OS: Ubuntu 18.04

**Comment by storypku** [comment]
Thank you for reporting.  The team will fix it ASAP.

**Comment by storypku** [comment]
> **Describe the bug**
> Following the instructions here - https://github.com/ApolloAuto/apollo/tree/master/modules/tools
> The scripts like plot_trace.sh and rtk_recorder throw an error:
> 
> Traceback (most recent call last):
> File "./modules/tools/plot_trace/plot_trace.py", line 26, in
> from modules.canbus.proto import chassis_pb2
> ImportError: cannot import name 'chassis_pb2'
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. ./apollo.sh build
> 2. source scripts/apollo_base.sh
> 3. ./scripts/plot_trace.sh
> 4. See error
> 
> * OS: Ubuntu 18.04

The scripts you mentioned here `plot_trace/vtk_recorder/vtk_player` were fixed in PR #12137 #12138 . The team is investigating other similar bugs in the `scripts` directory. Once we are ready, we shall let everyone noticed in this issue.

Thanks again for supporting Apollo!

**Comment by agarwalsid** [comment]
Thank you for quick update @storypku

**Comment by storypku** [comment]
> Thank you for quick update @storypku 

You are welcome.

**Comment by agarwalsid** [comment]
@storypku, just curious - Are the perception tools also supposed to run this way? For example in /modules/tools/perception:
python empty_prediction.py throws an error:

Traceback (most recent call last):
  File "empty_prediction.py", line 29, in <module>
    from cyber.python.cyber_py3 import cyber
ModuleNotFoundError: No module named 'cyber'

Am I running it wrong without .sh script?

**Comment by storypku** [comment]
> @storypku, just curious - Are the perception tools also supposed to run this way? For example in /modules/tools/perception:
> python empty_prediction.py throws an error:
> 
> Traceback (most recent call last):
> File "empty_prediction.py", line 29, in
> from cyber.python.cyber_py3 import cyber
> ModuleNotFoundError: No module named 'cyber'
> 
> Am I running it wrong without .sh script?

There was  a typo in `empty_prediction.py`, to be fixed in [this PR](https://github.com/ApolloAuto/apollo/pull/12181/files).

As Python codes are managed by Bazel rules in the `master` branch, You can run python binary targets in Apollo either by

```
./bazel-bin/modules/tools/perception/empty_prediction
```

Or by

```
bazel run //modules/tools/perception:empty_prediction
```

So, directly running `python empty_prediction.py` will fail, as Python related EnvVars (e.g, `PYTHONPATH`) were not setup.

Hope my answer helps.

**Comment by agarwalsid** [comment]
Thank you again @storypku

**Comment by bronzeMe** [comment]
HI, @storypku , when I run a command 
`python modules/tools/record_analyzer/main.py -f test-record/20201224165603.record.00000`, it also occurs the same errors.

`WARNING: Logging before InitGoogleLogging() is written to STDERR
I1224 18:57:21.601336  9690 py_record.cc:574] []init _cyber_record_wrapper
Traceback (most recent call last):
  File "modules/tools/record_analyzer/main.py", line 27, in <module>
    from modules.canbus.proto import chassis_pb2
ImportError: cannot import name 'chassis_pb2'
`
My experiment setting :

Apollo 6.0 (APOLLO_VERSION: master-2020-12-23-d094c1beb)
OS :ubuntu 18.04 
GPU: NVIDIA TITAN V

Could you give some tips?

**Comment by storypku** [comment]
> HI, @storypku , when I run a command
> `python modules/tools/record_analyzer/main.py -f test-record/20201224165603.record.00000`, it also occurs the same errors.
> 
> `WARNING: Logging before InitGoogleLogging() is written to STDERR I1224 18:57:21.601336 9690 py_record.cc:574] []init _cyber_record_wrapper Traceback (most recent call last): File "modules/tools/record_analyzer/main.py", line 27, in <module> from modules.canbus.proto import chassis_pb2 ImportError: cannot import name 'chassis_pb2' `
> My experiment setting :
> 
> Apollo 6.0 (APOLLO_VERSION: master-2020-12-23-d094c1beb)
> OS :ubuntu 18.04
> GPU: NVIDIA TITAN V
> 
> Could you give some tips?

Have you tried running `bazel-bin/modules/tools/record_analyzer/main -f test-record/20201224165603.record.00000`.
Don't run `python path/to/my.py` **directly**.

**Comment by bronzeMe** [comment]
Hi, @storypku , thanks for you reply, I have tried it using "bazel-bin/modules/tools/record_analyzer/main -f test-record/20201224165603.record.00000". 

But,  it shows errors: **No module named 'modules.tools.record_analyzer.commom**

` bazel-bin/modules/tools/record_analyzer/main -f test-record/20201224165603.record.00000 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1225 09:18:05.908526 15425 py_record.cc:574] []init _cyber_record_wrapper
Traceback (most recent call last):
  File "/apollo/bazel-bin/modules/tools/record_analyzer/main.runfiles/apollo/modules/tools/record_analyzer/main.py", line 33, in <module>
    from modules.tools.record_analyzer.module_control_analyzer import ControlAnalyzer
  File "/apollo/bazel-bin/modules/tools/record_analyzer/main.runfiles/apollo/modules/tools/record_analyzer/module_control_analyzer.py", line 20, in <module>
    from modules.tools.record_analyzer.common.error_msg_analyzer import ErrorMsgAnalyzer
  File "/apollo/bazel-bin/modules/tools/record_analyzer/main.runfiles/apollo/modules/tools/record_analyzer/common/error_msg_analyzer.py", line 21, in <module>
    from modules.tools.record_analyzer.commom.distribution_analyzer import DistributionAnalyzer
ModuleNotFoundError: No module named 'modules.tools.record_analyzer.commom'`

**Comment by bronzeMe** [comment]
@storypku ,thank you so much, I have tried it using `bazel-bin/modules/tools/record_analyzer/main -f test-record/20201224165603.record.00000`. It works well.

**Comment by storypku** [comment]
> @storypku ,thank you so much, I have tried it using `bazel-bin/modules/tools/record_analyzer/main -f test-record/20201224165603.record.00000`. It works well.

Really? In master HEAD, I had to made a few changes to make it work.

**Comment by bronzeMe** [comment]
@storypku , exactly, I also made a few changes as the PR [#13244 ](https://github.com/ApolloAuto/apollo/pull/13244).

**Comment by storypku** [comment]
> @storypku , exactly, I also made a few changes as the PR [#13244 ](https://github.com/ApolloAuto/apollo/pull/13244).

Next time you encounter issues and find solutions, please consider contributing to Apollo. It is highly appreciated to do so.
