### ISSUE TITLE
Error when compiling Apollo Master

### ISSUE THREAD

**Issue by rubingLi** [ApolloAuto/apollo#12132]
hello,Encountered an error when compiling Apollo
The computer configuration is:ubuntu 16.04,cuda 10.2,gcc 7.5,geforce mx150
The error message is as follows：
(16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/eight_route.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/alignment.h:22,
                 from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
                 from modules/map/tools/map_datachecker/server/eight_route.cc:16:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/static_align.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/alignment.h:22,
                 from ./modules/map/tools/map_datachecker/server/static_align.h:21,
                 from modules/map/tools/map_datachecker/server/static_align.cc:16:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/worker.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/alignment.h:22,
                 from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
                 from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
                 from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
                 from modules/map/tools/map_datachecker/server/worker.cc:23:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:30) INFO: From Compiling modules/map/tools/map_datachecker/server/worker_agent.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/alignment.h:22,
                 from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
                 from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
                 from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
                 from modules/map/tools/map_datachecker/server/worker_agent.cc:16:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:33) INFO: From Compiling modules/map/tools/map_datachecker/server/loops_verify_agent.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/laps_checker.h:24,
                 from ./modules/map/tools/map_datachecker/server/loops_verify_agent.h:25,
                 from modules/map/tools/map_datachecker/server/loops_verify_agent.cc:16:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:35) INFO: From Compiling modules/map/tools/map_datachecker/server/pose_collection_agent.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/pose_collection_agent.h:23,
                 from modules/map/tools/map_datachecker/server/pose_collection_agent.cc:16:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:35) INFO: From Compiling modules/map/tools/map_datachecker/server/laps_checker.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/laps_checker.h:24,
                 from modules/map/tools/map_datachecker/server/laps_checker.cc:16:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(16:01:44) ERROR: /apollo/modules/planning/learning_based/model_inference/BUILD:32:11: C++ compilation of rule '//modules/planning/learning_based/model_inference:trajectory_imitation_tensorrt_inference' failed (Exit 1)
modules/planning/learning_based/model_inference/trajectory_imitation_tensorrt_inference.cc:24:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
(16:03:12) INFO: Elapsed time: 618.856s, Critical Path: 173.66s
(16:03:12) INFO: 434 processes: 434 local.
(16:03:14) FAILED: Build did NOT complete successfully
************
Can anyone tell me how to solve this problem

**Comment by jinghaomiao** [comment]
Please update your code repo and pull the latest docker image. Thanks for using Apollo.

**Comment by storypku** [comment]
> hello,Encountered an error when compiling Apollo
> The computer configuration is:ubuntu 16.04,cuda 10.2,gcc 7.5,geforce mx150
> The error message is as follows：
> (16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/eight_route.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
> from modules/map/tools/map_datachecker/server/eight_route.cc:16:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/static_align.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> from ./modules/map/tools/map_datachecker/server/static_align.h:21,
> from modules/map/tools/map_datachecker/server/static_align.cc:16:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/worker.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
> from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
> from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
> from modules/map/tools/map_datachecker/server/worker.cc:23:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:30) INFO: From Compiling modules/map/tools/map_datachecker/server/worker_agent.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
> from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
> from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
> from modules/map/tools/map_datachecker/server/worker_agent.cc:16:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:33) INFO: From Compiling modules/map/tools/map_datachecker/server/loops_verify_agent.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/laps_checker.h:24,
> from ./modules/map/tools/map_datachecker/server/loops_verify_agent.h:25,
> from modules/map/tools/map_datachecker/server/loops_verify_agent.cc:16:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:35) INFO: From Compiling modules/map/tools/map_datachecker/server/pose_collection_agent.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/pose_collection_agent.h:23,
> from modules/map/tools/map_datachecker/server/pose_collection_agent.cc:16:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:35) INFO: From Compiling modules/map/tools/map_datachecker/server/laps_checker.cc:
> In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> from external/poco/boost/property_tree/json_parser.hpp:16,
> from ./modules/map/tools/map_datachecker/server/common.h:29,
> from ./modules/map/tools/map_datachecker/server/laps_checker.h:24,
> from modules/map/tools/map_datachecker/server/laps_checker.cc:16:
> external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> )
> ^
> (16:01:44) ERROR: /apollo/modules/planning/learning_based/model_inference/BUILD:32:11: C++ compilation of rule '//modules/planning/learning_based/model_inference:trajectory_imitation_tensorrt_inference' failed (Exit 1)
> modules/planning/learning_based/model_inference/trajectory_imitation_tensorrt_inference.cc:24:10: fatal error: cuda_runtime_api.h: No such file or directory
> #include <cuda_runtime_api.h>
> ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> (16:03:12) INFO: Elapsed time: 618.856s, Critical Path: 173.66s
> (16:03:12) INFO: 434 processes: 434 local.
> (16:03:14) FAILED: Build did NOT complete successfully
> 
> Can anyone tell me how to solve this problem

What's the output of `./apollo.sh config` ?

**Comment by rubingLi** [comment]
> > hello,Encountered an error when compiling Apollo
> > The computer configuration is:ubuntu 16.04,cuda 10.2,gcc 7.5,geforce mx150
> > The error message is as follows：
> > (16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/eight_route.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> > from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
> > from modules/map/tools/map_datachecker/server/eight_route.cc:16:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/static_align.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> > from ./modules/map/tools/map_datachecker/server/static_align.h:21,
> > from modules/map/tools/map_datachecker/server/static_align.cc:16:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:27) INFO: From Compiling modules/map/tools/map_datachecker/server/worker.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> > from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
> > from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
> > from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
> > from modules/map/tools/map_datachecker/server/worker.cc:23:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:30) INFO: From Compiling modules/map/tools/map_datachecker/server/worker_agent.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/alignment.h:22,
> > from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
> > from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
> > from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
> > from modules/map/tools/map_datachecker/server/worker_agent.cc:16:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:33) INFO: From Compiling modules/map/tools/map_datachecker/server/loops_verify_agent.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/laps_checker.h:24,
> > from ./modules/map/tools/map_datachecker/server/loops_verify_agent.h:25,
> > from modules/map/tools/map_datachecker/server/loops_verify_agent.cc:16:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:35) INFO: From Compiling modules/map/tools/map_datachecker/server/pose_collection_agent.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/pose_collection_agent.h:23,
> > from modules/map/tools/map_datachecker/server/pose_collection_agent.cc:16:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:35) INFO: From Compiling modules/map/tools/map_datachecker/server/laps_checker.cc:
> > In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
> > from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
> > from external/poco/boost/property_tree/json_parser.hpp:16,
> > from ./modules/map/tools/map_datachecker/server/common.h:29,
> > from ./modules/map/tools/map_datachecker/server/laps_checker.h:24,
> > from modules/map/tools/map_datachecker/server/laps_checker.cc:16:
> > external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
> > )
> > ^
> > (16:01:44) ERROR: /apollo/modules/planning/learning_based/model_inference/BUILD:32:11: C++ compilation of rule '//modules/planning/learning_based/model_inference:trajectory_imitation_tensorrt_inference' failed (Exit 1)
> > modules/planning/learning_based/model_inference/trajectory_imitation_tensorrt_inference.cc:24:10: fatal error: cuda_runtime_api.h: No such file or directory
> > #include <cuda_runtime_api.h>
> > ^~~~~~~~~~~~~~~~~~~~
> > compilation terminated.
> > (16:03:12) INFO: Elapsed time: 618.856s, Critical Path: 173.66s
> > (16:03:12) INFO: 434 processes: 434 local.
> > (16:03:14) FAILED: Build did NOT complete successfully
> > Can anyone tell me how to solve this problem
> 
> What's the output of `./apollo.sh config` ?

[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: @non-git
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200811_2001
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false USE_GPU=1

**Comment by storypku** [comment]
It seems your repo was non-git. Please pull the latest master and rerun `docker_into.sh` and try again.
