### ISSUE TITLE
[perception] a 12 meter long bicycle.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12139]
Hi team, 

I've pulled the latest master branch (`b91d67e963506de61d1522c64ca71e2e32d72e24`)
and I've switched from `SegmentationComponent` to `DetectionComponent`. 

and I found that:
* `detectionComponent` also could not detect the random shape obstacle as in [issue](https://github.com/ApolloAuto/apollo/issues/12073). 
* `detectionComponent` produced a weird 12-meter long bicycle out of nowhere as shown in the case below:  ([recording file](https://drive.google.com/file/d/1Sq1tqqS0q5xrCiXBf6dQhDLgu1Mbmcxv/view?usp=sharing))

![12_meter_long_byclce](https://user-images.githubusercontent.com/16061105/90230922-e63f2480-de4c-11ea-977e-7fa8ac210a3a.png)

Steps to reproduce
---
* build Apollo `master` branch.
* start `boostrap_lgsvl.sh`
* configure in Dreamview
    * Setup mode: `Mkz Lgsvl`
    * Vehicle: `Lincoln2017MKZ LGSVL`
    * map: `Borregas Ave`
* download and save the recording file as `xxx.rec`
* `cyber_recorder play -l -f xxx.rec`

Expected behavior
--- 
Apollo should not produce this 12-meter long bicycle out of nowhere...

Configurations
---

Below is my dag file for lidar perception:

```
module_config {
  module_library : "/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so"

 components {
    class_name : "DetectionComponent"
    config {
      name: "Velodyne128Detection"
      config_file_path: "/apollo/modules/perception/production/conf/perception/lidar/velodyne128_detection_conf_lgsvl.pb.txt"
      flag_file_path: "/apollo/modules/perception/production/conf/perception/perception_common.flag"
      readers {
          channel: "/apollo/sensor/lidar128/compensator/PointCloud2"
        }
    }
  }

  components {
    class_name : "RecognitionComponent"
    config {
      name: "RecognitionComponent"
      config_file_path: "/apollo/modules/perception/production/conf/perception/lidar/recognition_conf.pb.txt"
      readers {
          channel: "/perception/inner/DetectionObjects"
        }
    }
  }


  components {
    class_name: "FusionComponent"
    config {
      name: "SensorFusion"
      config_file_path: "/apollo/modules/perception/production/conf/perception/fusion/fusion_component_conf.pb.txt"
      readers {
          channel: "/perception/inner/PrefusedObjects"
        }
    }
  }
}
```

Please let me know if any other resources are needed to verify this. Thanks.

**Comment by jeroldchen** [comment]
@ntutangyun Thanks for the report. We are working on improving the detection model to eliminate those problems.

**Comment by jeroldchen** [comment]
@ntutangyun Did you change timestamp to 0 in https://github.com/ApolloAuto/apollo/blob/master/modules/perception/onboard/transform_wrapper/transform_wrapper.cc#L217 ?

**Comment by ntutangyun** [comment]
@jeroldchen no I didn't change this part.
