### ISSUE TITLE
有使用modules目录下的tools里面的众多工具的具体教程吗

### ISSUE THREAD

**Issue by liukr001** [ApolloAuto/apollo#12144]
请问下，modules目录下的tools里面的众多工具，比如创建地图，是建立只有车道线的地图，还是高精度地图？用户可以自己建立高精度地图吗。另外这些工具有进一步的使用说明教程吗

**Comment by jinghaomiao** [comment]
@liukr001 Thanks for the feedback. We'll evaluate it internally. 

The map generation tool only generates a map with lanes, but follows HDMap data format. We don't provide offline tools to generate HDMap. If needed, please consult @diegohu for commercial HDMap product.

**Comment by daohu527** [comment]
It seems that these tools are used to generate some demo maps. Input is the collected (x, y) coordinates, and then generate a map from these coordinates.  

You can use any of "map_gen.py / map_gen_single_lane.py / map_gen_two_lanes_right_ext.py" to generate map
```
.
├── add_signal.py        // add traffic signal like "Stop, yield"
├── extract_path.py      // extract "/apollo/localization/pose" from bag
├── map_gen.py           // generate map
├── map_gen_single_lane.py  // generate single lane
├── map_gen_two_lanes_right_ext.py  // generate two lanes
└── plot_path.py                    // visualization path
```

**Comment by kevin-y-wang** [comment]
Hi, @liukr001  thanks for your interests and contributions to improve the Apollo platform. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer teams are more than happy to help that.

Thank you for supporting Apollo!
