### ISSUE TITLE
Error when compiling bridge module

### ISSUE THREAD

**Issue by rubingLi** [ApolloAuto/apollo#12143]
Hello, I tried to send the controlCommand through udp, so I added a statement at the end of the file udp_bridge_sender_component.h  : BRIDGE_COMPONENT_REGISTER(control::ControlCommand),  and added a statement at the end of the file udp_bridge_sender_component.cc 
BRIDGE_IMPL(control::ControlCommand);then I modified the configuration file and dag file, but the compilation error

(04:41:56) ERROR: /apollo/modules/bridge/BUILD:27:11: C++ compilation of rule '//modules/bridge:udp_bridge_sender' failed (Exit 1)
In file included from ./cyber/class_loader/class_loader.h:26:0,
                 from ./modules/bridge/udp_bridge_sender_component.h:28,
                 from modules/bridge/udp_bridge_sender_component.cc:17:
./modules/bridge/udp_bridge_sender_component.h: In constructor 'apollo::bridge::{anonymous}::ProxyType2::ProxyType2()':
./modules/bridge/udp_bridge_sender_component.h:67:27: error: 'control' was not declared in this scope
 BRIDGE_COMPONENT_REGISTER(control::ControlCommand)

**Comment by storypku** [comment]
If you want to develop your own code base on Apollo, you should have some working knowledge of `Bazel` (the build tool Apollo uses) besides C++ programming.

And this link [Bazel Build Totorial for C++](https://docs.bazel.build/versions/master/tutorial/cpp.html) is a good start.
