### ISSUE TITLE
Build Only the Bridge Module

### ISSUE THREAD

**Issue by rubingLi** [ApolloAuto/apollo#12142]
apollo master
Hello, I modified the scripts  in modules/bridge, but it would take a lot of time to rebuild all of them. How can I build only the bridge module?
你好，我修改了modules/bridge里的脚本，但是全部重新build将会花大量时间，我怎么样才能只buildbridge模块呢

**Comment by storypku** [comment]
> apollo master
> Hello, I modified the scripts in modules/bridge, but it would take a lot of time to rebuild all of them. How can I build only the bridge module?
> 你好，我修改了modules/bridge里的脚本，但是全部重新build将会花大量时间，我怎么样才能只buildbridge模块呢


```
./apollo.sh build bridge
```

**Comment by ntutangyun** [comment]
@rubingLi if you only modified some scripts, Bazel will only build that relevant code. It should be quite fast also.

**Comment by rubingLi** [comment]
Thank you
