### ISSUE TITLE
Help needed for Folder structure: Perception Module Apollo 5.0

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#12153]
Hello,

Can someone guide me to understand the folder structure of [Perception ](https://github.com/ApolloAuto/apollo/tree/r5.0.0/modules/perception)module of Apollo 5.0?
Especially the folder structure of [perception/camera/](https://github.com/ApolloAuto/apollo/tree/r5.0.0/modules/perception/camera)

I find a lot of folders(like for example: lib, testdata, camera.......) but not sure of which is used for which purpose? Is it mentioned somewhere. It is very difficult for me to understand :(

Please guide!!!!!

**Comment by daohu527** [comment]
The general introduction is as follows.  
```
.
├── app        \\  main entrance
├── common     \\ common program
├── lib         \\ Library, used for traffic lights, obstacle detection and other functions
├── test        \\ test case
└── tools       \\ Tool for displaying the recognition results of lane lines and traffic lights
```

If you want to introduce in more detail, you can refer to [link](https://github.com/daohu527/Dig-into-Apollo/tree/master/perception/camera#camera_module).  This document is still being improved.

**Comment by ashwinsarvesh** [comment]
Thank you so much @daohu527 
Where should I refer to the main code for traffic lights, obstacle detection and lane detection? In App or Lib?
Because I see codes in both these folders.

**Comment by daohu527** [comment]
In "modules/perception/onboard/component", there are
```
modules/perception/onboard/component/trafficlights_perception_component.h
modules/perception/onboard/component/detection_component.h
modules/perception/onboard/component/lane_detection_component.h
```

**Comment by ashwinsarvesh** [comment]
Thank you again @daohu527 
To be more specific, if _modules/perception/onboard/component/trafficlights_perception_component.h_ is the main code, then what is _https://github.com/ApolloAuto/apollo/tree/r5.0.0/modules/perception/camera/lib/traffic_light_  ?

This folder also contains core components of implementations divided into folders like preprocessor, detector, and tracker.

**Comment by daohu527** [comment]
If you have many steps, you will eventually need an entrance. Reading the code will help you understand it.

**Comment by ashwinsarvesh** [comment]
Hello @daohu527 
I did not understand your answer. Can you explain?

**Comment by ashwinsarvesh** [comment]
@weidezhang not sure how you got unassigned :(

**Comment by panfengsu** [comment]
@daohu527 is right，modules/perception/onboard/component/ is entrance of a module, for example traffic lights, obstacle detection.modules/perception/camera/lib/traffic_light is specific functions to implement. Reading code will help more.

**Comment by ashwinsarvesh** [comment]
@panfengsu Which means "modules/perception/camera/lib/traffic_light" contains the core elements of the implementation?
What does entrance of a module mean?

I am new to Apollo, so sorry for silly questions.

**Comment by panfengsu** [comment]
an interface of a module

**Comment by ashwinsarvesh** [comment]
ok @panfengsu 
If I have to change the configurations like "min_crop_size", "crop_method", "crop_scale" ,"is_bgr" and test the traffic light detection module, then I need to change in this [file ](https://github.com/lgsvl/apollo-5.0/blob/simulator/modules/perception/production/data/perception/camera/models/traffic_light_detection/detection.pt) right?

**Comment by panfengsu** [comment]
apollo/modules/perception/production/data/perception/camera/models/traffic_light_detection/detection.pt

**Comment by ashwinsarvesh** [comment]
Thank you :)
[Testdata ](https://github.com/lgsvl/apollo-5.0/tree/simulator/modules/perception/testdata)folder contains the configurations and data for the test cases in [camera/test/](https://github.com/lgsvl/apollo-5.0/tree/simulator/modules/perception/camera/test) folder right?

**Comment by daohu527** [comment]
1. Testdata is use for function test 
2. camera/test is use for unit test

**Comment by ashwinsarvesh** [comment]
ok but I am confused why a code in camera/test has reference to Testdata
For eg below:
  init_options.conf_file = "config.pt";
  init_options.root_dir =
      "/apollo/modules/perception/testdata/"
      "camera/lib/traffic_light/detector/recognition/data/";
What is it fetching from Testdata?

Also, where the test cases in testdata folder? I can only see the conf and data defined which is used by the code in camera/test folder.

**Comment by daohu527** [comment]
You are right, camera/test is used for functional test and reads models and parameters from Testdata. Actually I haven't run the test case, you can try it first.  

Traffic light detection uses a deep learning model, you can first understand the relevant information.

**Comment by ashwinsarvesh** [comment]
ok thanks for the clarification.
Is there a procedure to run the test cases? I don't know how to do it
