### ISSUE TITLE
如何理解dreamview里面的co-driver功能?

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#12157]
apollo5.0

**Comment by BigBenSure** [comment]
英文doc里面有一些解释:The Co-Driver switch is used to detect disengagement event automatically. Once detect, dreamview will pop up the data recorder window for co-driver to enter a new drive event.
这里的disengagement event我是否能理解为需要人工干预的事件?也就是说,开启这个按钮,当出现需要人工干预的事件时,自动弹出一个数据记录框,告诉副驾驶发生了什么?

**Comment by BigBenSure** [comment]
另外希望能更新下dreamview_usage_table_cn.md 英文版有更新,中文版没有对应更新..

**Comment by daohu527** [comment]
## Process
The general process is as follows:  
1. After enabling the "co-driver", a session window will open when "Disengagement found". 
2. when you finish the record table, it will send a message to "smart_recorder". 
3. The "smart_recorder" will record the data 30s before and 5s later

**Comment by unacao** [comment]
这个是帮助副驾驶记录行车过程中出现的disengage event. 打开co-driver模式后，只要系统发现驾驶模式跳出自动驾驶了，就会自动跳出弹窗，请副驾驶记录详细信息，例如当时发生了什么

**Comment by jinghaomiao** [comment]
@BigBenSure Hope your question is answered. This ticket is being closed. Please raise new issues if needed. Thank you for using Apollo.

**Comment by BigBenSure** [comment]
Thanks! I know it~
