### ISSUE TITLE
How to clean the cache file in Apollo?

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#12156]
Hello team,

I run Apollo with LGSVL several times, and after that I found the system prompts insufficient disk space, I ran `df -h` and the result is bellow:
![df](https://user-images.githubusercontent.com/26716009/90459220-39f28c00-e133-11ea-823c-21adbbd7b1ce.png)

The apollo  in /dev/sda7 takes up most of the space, but as far as I know, the origin apollo package only a few GB in size, so is there any method to chean the apollo space and delete useless files?

**Comment by storypku** [comment]
> Hello team,
> 
> I run Apollo with LGSVL several times, and after that I found the system prompts insufficient disk space, I ran `df -h` and the result is bellow:
> ![df](https://user-images.githubusercontent.com/26716009/90459220-39f28c00-e133-11ea-823c-21adbbd7b1ce.png)
> 
> The apollo in /dev/sda7 takes up most of the space, but as far as I know, the origin apollo package only a few GB in size, so is there any method to chean the apollo space and delete useless files?

Check if coredumps are generated in the `data/core` directory. Remove if you don't need them anymore.

As you build Apollo serveral times,  the ".cache/bazel" directory can also take a lot of disk space. (~7.6G on my host).
Try `bazel clean` or `bazel clean --expunge` if that directory takes up too much space. Please note that the commands above will remove all bazel outputs (for the latter, external dependencies were also removed).

**Comment by ForresterLu** [comment]
@storypku Thanks for your reply,

These are all the files in data/core, and these files occupy about 60 GB space, do you mean I can remove them directly?
![core](https://user-images.githubusercontent.com/26716009/90462592-b5583b80-e13b-11ea-9fc9-92cae2acb03f.png)


But the way, I notice in /data/log directory, the log files occupy alomost 100GB space, can I just remove them and free the space?
![log](https://user-images.githubusercontent.com/26716009/90462855-27c91b80-e13c-11ea-803b-73222748c385.png)

thanks!

**Comment by storypku** [comment]
> @storypku Thanks for your reply,
> 
> These are all the files in data/core, and these files occupy about 60 GB space, do you mean I can remove them directly?
> ![core](https://user-images.githubusercontent.com/26716009/90462592-b5583b80-e13b-11ea-9fc9-92cae2acb03f.png)
> 
> But the way, I notice in /data/log directory, the log files occupy alomost 100GB space, can I just remove them and free the space?
> ![log](https://user-images.githubusercontent.com/26716009/90462855-27c91b80-e13c-11ea-803b-73222748c385.png)
> 
> thanks!

Yep. Just remove those coredump  and log files if you don't need them.
