### ISSUE TITLE
Question about Open Space Algorithm

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#12165]
Hello team! Help me please  

- **OS Platform and Distribution - Linux Ubuntu 18.04**:  
- **Apollo installed from source**:  
- **Apollo version - pre6**:  

**Why doesn't the [Open Space Algorithm](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Open_Space_Planner.md) work for me?**  

I am using a LGSVL simulator and Autonomus Staff map.
In Route Editing menu, I select a slot, as shown in the picture below. And click Send Routing Request.  
![Screenshot from 2020-08-18 15-33-38](https://user-images.githubusercontent.com/61351599/90513891-0b8fa380-e169-11ea-8ad3-448623815967.png)  

But the car drives up to the parking space and does not perform the parking maneuver.  
![Screenshot from 2020-08-18 15-32-39](https://user-images.githubusercontent.com/61351599/90514069-53162f80-e169-11ea-93d1-4aa75d7a4c3b.png)

**Can you please tell me what I'm doing wrong?**

**Comment by daohu527** [comment]
Seems the open space planner is combined to **public road planner**, and the park scenario is in "modules/planning/conf/scenario/valet_parking_config.pb.txt"

**Comment by Capri2014** [comment]
Sorry I am not familiar with either of the simulator or the map. We do have quite a few of open space planner application and its simulation cases for different environment available at Apollo's simulation environment: http://bce.apollo.auto, you may want to start with comparison the differences between these cases and your test environment.

**Comment by Capri2014** [comment]
As in your case, you may want to check if the  routing request you sent has the parking_id https://github.com/ApolloAuto/apollo/blob/45134948422cc8cab64d55bd83f3968fe0041d7c/modules/routing/proto/routing.proto#L23 information, if not, you may want to manually create one.

**Comment by Capri2014** [comment]
> Sorry I am not familiar with either of the simulator or the map. We do have quite a few of open space planner application and its simulation cases for different environment available at Apollo's simulation environment: http://bce.apollo.auto, you may want to start with comparison the differences between these cases and your test environment.

Sorry I was wrong about that we have some simulation cases already available in public. --- We will have a few available in the upcoming release.

**Comment by AlexandrZabolotny** [comment]
> As in your case, you may want to check if the routing request you sent has the parking_id
> 
> https://github.com/ApolloAuto/apollo/blob/45134948422cc8cab64d55bd83f3968fe0041d7c/modules/routing/proto/routing.proto#L23
> 
> information, if not, you may want to manually create one.

Yes. Indeed - I am not sending the Parking_id routing request  
![Screenshot from 2020-08-27 11-33-34](https://user-images.githubusercontent.com/61351599/91418729-365db400-e85b-11ea-8639-d506512fcf8e.png)


Could you please tell me how can I create a request manually?  
Or maybe there is an instruction for this question? I could not find.

**Comment by AlexandrZabolotny** [comment]
Hi @Capri2014   
Help me if you can!  

I want to create BOS accaunt accoding [this](https://github.com/ApolloAuto/apollo/blob/master/docs/Apollo_Fuel/apply_bos_account_cn.md)   
**But I have some questions. Can I create an account from outside China? Is there an instruction in English**  
I see this picture  
![Screenshot from 2020-11-19 11-41-26](https://user-images.githubusercontent.com/61351599/99642134-320cf580-2a5c-11eb-9bfb-c4b607cbb5a0.png)
