### ISSUE TITLE
MPC Controller about Control time domian and predict time domain

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#12173]
For MPC controller,i have several questions shown below:
1.Now, predict time domain is 10,and control time domain is 9?
2.Control frequency is 100,planning frequency is 10. So,each 0.1s,control use 1 time planning output to set control command to vehicle 10 times,use u[0], u[1], u[2]......u[9]. Is realize in apollo in such way? if it's true,please show me more details (which part code is real realization), if not, how to realize control command(just use  u[0], u[1] or something else? please show me details).

Thank you very much for taking my questions seriously. hope your reply.

**Comment by Capri2014** [comment]
https://github.com/ApolloAuto/apollo/blob/20463faa51ff92302b31b94df095944c2d6a6729/modules/control/controller/mpc_controller.cc#L399
