### ISSUE TITLE
MPC control tuning for speed control? Module: Control 

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#12171]
Ubuntu 18.04.4
Apollo 5.5

I am trying to tune MPC control (matrix_q) for speed control. The vehicle speed limit is set to 5 m/s. once the speed reached to 5 m/s, the speed of the vehicle is unstable. means the actual speed goes up and down from the desired speed value (5 m/s).
How to tune MPC control to get stabilized speed speed response. 

![Screenshot from 2020-08-19 14-55-49](https://user-images.githubusercontent.com/61130487/90602384-4575ae00-e22c-11ea-913b-2a886a63e45f.png)

**Comment by Capri2014** [comment]
Control performance, really depends on various factors from your vehicle interface, can bus resolution, actuator/sensor response time and agility as well as the parameter tuning tricks. So there is no simple answer for it. However, for MKZs, we will have autotune cloud based service to address issues like this in next release, so please stay tuned.

**Comment by AlexandrZabolotny** [comment]
Hello colleagues!
I am trying to tune a control module on a real car.

I will try to run both MPC and LQR+PID

I get the following result

In the case of LQR+PID
Good speed control (longitudinal control), but poor lateral control. When cornering, it does not follow the desired trajectory and therefore dynamically turns the steering wheel.
2.in case of MPC
It repeats the trajectory well. Smoothly turns the steering wheel. Provides a comfortable ride. But poor speed control. A very large longitudinal error, also the car does not stop at the required point.

I want to use MPC. So I have questions.

Is it possible to set up longitudinal control for MPC? If so, how?
Is it possible to use MPC for lateral control, but for longitudinal - PID ??
