### ISSUE TITLE
in which situation osqp will fail?(planning)

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#12189]
When i use apollo5.5 to tune the car. Why it always has an error about osqp method?
output following error log:
AERROR << "failed optimization status:\t" << osqp_work->info->status;

in which situation this will happen?

**Comment by jmtao** [comment]
@ManXiaoMi what's the exact status in the log? Based on that, you can check OSQP status values: https://osqp.org/docs/interfaces/status_values.html

**Comment by ManXiaoMi** [comment]
> @ManXiaoMi what's the exact status in the log? Based on that, you can check OSQP status values: https://osqp.org/docs/interfaces/status_values.html

E0819 17:19:17.444324 16591 piecewise_jerk_problem.cc:102] failed optimization status:	primal infeasible
E0819 17:19:17.444386 16591 piecewise_jerk_speed_nonlinear_optimizer.cc:462] Speed optimization by Quadratic Programming failed, st boundary is infeasible
E0819 17:19:17.444403 16591 lane_follow_stage.cc:184] Failed to run tasks[PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER], Error message: Speed Optimization by Quadratic Programming failed
E0819 17:19:17.444994 16591 lane_follow_stage.cc:388] Use last frame good path to do speed fallback
E0819 17:19:17.445003 16591 lane_follow_stage.cc:303] Speed fallback due to algorithm failure
E0819 17:19:17.445005 16591 speed_profile_generator.cc:38] Fallback using piecewise jerk speed!
W0819 17:19:17.445010 16591 speed_profile_generator.cc:41] init_v = 5.38594, init_a = 2
E0819 17:19:17.447638 16591 piecewise_jerk_problem.cc:102] failed optimization status:	primal infeasible
E0819 17:19:17.447664 16591 speed_profile_generator.cc:79] Piecewise jerk fallback speed optimizer failed!
E0819 17:19:17.447669 16591 speed_profile_generator.cc:120] Slowing down the car within a constant deceleration with fallback stopping profile.

**Comment by ManXiaoMi** [comment]
failed optimization status: primal infeasible. what's the meaning of this status?
Now my car meet the problem is the speed of the vehicle is unstable. the actual speed always go up and down.
Then i check planning output, and find the problem like osqp problem shown above. each time when occur this problem, the car will go down,and then go up.
I don't know how to solve this problem. Thank you very much for your help.

**Comment by ManXiaoMi** [comment]
failed optimization status: primal infeasible. what's the meaning of this status?
Now my car meet the problem is the speed of the vehicle is unstable. the actual speed always go up and down.
Then i check planning output, and find the problem like osqp problem shown above. each time when occur this problem, the car will go down,and then go up.
I don't know how to solve this problem. Thank you very much for your help.

**Comment by ManXiaoMi** [comment]
failed optimization status: primal infeasible. what's the meaning of this status?
Now my car meet the problem is the speed of the vehicle is unstable. the actual speed always go up and down.
Then i check planning output, and find the problem like osqp problem shown above. each time when occur this problem, the car will go down,and then go up.
I don't know how to solve this problem. Thank you very much for your help.

**Comment by ManXiaoMi** [comment]
> @ManXiaoMi what's the exact status in the log? Based on that, you can check OSQP status values: https://osqp.org/docs/interfaces/status_values.html

Still include some other failure, show below:
E0821 17:42:18.898844 17621 piecewise_jerk_speed_nonlinear_optimizer.cc:579] Solver failure case is : INFEASIBLE_PROBLEM_DETECTED
E0821 17:42:18.898869 17621 piecewise_jerk_speed_nonlinear_optimizer.cc:582] Piecewise jerk speed nonlinear optimizer failed!
E0821 17:42:18.899144 17621 lane_follow_stage.cc:184] Failed to run tasks[PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER], Error message: Piecewise jerk speed nonlinear optimizer failed!
E0821 17:42:18.899734 17621 lane_follow_stage.cc:388] Use last frame good path to do speed fallback
E0821 17:42:18.899744 17621 lane_follow_stage.cc:303] Speed fallback due to algorithm failure
E0821 17:42:18.899750 17621 speed_profile_generator.cc:38] Fallback using piecewise jerk speed!
W0821 17:42:18.899757 17621 speed_profile_generator.cc:41] init_v = 2.98199, init_a = -3.46136

**Comment by JasonZhou404** [comment]
This is the case where vehicle is out of its dynamics limits, you could share us with more detail on your testing setup
