### ISSUE TITLE
Help needed : Printing messages of Perception Module as published in its obstacle detection channel 

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#12198]
Hi, 
This is a general query about the Perception module. I am a University student and need the following information for my seminar : 

How can one print the messages published to the output channel of Perception - "/perception/obstacles" ? I want the position, velocity,  and size of 2D and 3D bounding box of the obstacles as published in the output channel of perception for obstacle detection, so that I can compare this data to the lgsvl ground-truth to evaluate the efficiency of Perception Module obstacle detection. 

Any help will be appreciated . Thanks in advance!
Kind Regards
![Screen Shot 2020-08-21 at 12 33 10 AM](https://user-images.githubusercontent.com/50120641/90832365-e60bc100-e345-11ea-9076-bc4fa692d0a1.png)
![Screen Shot 2020-08-21 at 12 34 00 AM](https://user-images.githubusercontent.com/50120641/90832416-03408f80-e346-11ea-916f-23f73d7cd5f7.png)

**Comment by jmtao** [comment]
Hi, @Avps1,  hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
