### ISSUE TITLE
Apollo3.0/perception/lidar/hungarian_matcher.cc ComputeAssociateMatrixhas issue for advice

### ISSUE THREAD

**Issue by lark-ying** [ApolloAuto/apollo#12216]
#12215 System information
Linux Ubuntu 18.04
Apollo installed from source
Apollo version 3.0

    I'm interested in your team's open autonomous driving code for the Apollo community.I would like to ask **two questions in the Apollo/ Percetion/LIdar module**:

1. The following source code, the path for "modules/perception/obstacle/lidar/tracker/hm_tracker/track_object_distance. cc" , when lidar track ComputeAssociateMatrixhas five factors, including: ****location_distance,direction_distance,bbox_size_distance,point_num_distance,histogram_distance**. I want to ask whether there is any selection basis for selecting the 5 parameters for weighting.** There are 5 default weights **s_location_distance_weight_, s_direction_distance_weight_, s_bbox_size_distance_weight_, s_point_num_distance_weight_, s_histogram_distance_weight_** are where the selection is given**?
`float TrackObjectDistance::ComputeDistance(
    ObjectTrackPtr track, const Eigen::VectorXf& track_predict,
    const std::shared_ptr<TrackedObject>& new_object) {
  // Compute distance for given trakc & object
   ......
  **float result_distance = s_location_distance_weight_ * location_distance +
                          s_direction_distance_weight_ * direction_distance +
                          s_bbox_size_distance_weight_ * bbox_size_distance +
                          s_point_num_distance_weight_ * point_num_distance +
                          s_histogram_distance_weight_ * histogram_distance;**
  return result_distance;
}`

2. In the source code, association_(i, j) <= connected_threshold==4. **What factors are considered in the selection of this connected_threshold=4?**
`void HungarianMatcher::ComputeConnectedComponents(
    const Eigen::MatrixXf& association_mat, const float connected_threshold,
    std::vector<std::vector<int>>* track_components,
    std::vector<std::vector<int>>* object_components) {
  // Compute connected components within given threshold
 ......
      **if (association_mat(i, j) <= connected_threshold) {   //connected_threshold==4**
       ......
}`

Looking forward to your reply and best wishes!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
