### ISSUE TITLE
external/uuid/cublas_api.h:72:10: fatal error: driver_types.h: No such file or directory

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12226]
Hi,

My environment is: Ubuntu 20.04, apollo-kernel 4.4.32-apollo-2-RT, and apollo git master version. In addition, gcc/g++ versions are as following:

```
$ gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
$ g++ --version
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0

```

Failed to compile apollo with the following command:

```
$ ./apollo.sh build
[...]
(05:08:20) ERROR: /apollo/modules/perception/base/BUILD:358:11: C++ compilation of rule '//modules/perception/base:syncedmem' failed (Exit 1)
In file included from external/uuid/cublas_v2.h:65:0,
                 from ./modules/perception/base/common.h:21,
                 from ./modules/perception/base/syncedmem.h:66,
                 from modules/perception/base/syncedmem.cc:63:
external/uuid/cublas_api.h:72:10: fatal error: driver_types.h: No such file or directory
 #include "driver_types.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
(05:08:21) INFO: Elapsed time: 183.508s, Critical Path: 36.60s
(05:08:21) INFO: 2278 processes: 2278 local.
(05:08:21) FAILED: Build did NOT complete successfully

```

Any hints for solving the problem?

Best regards,
HY

**Comment by storypku** [comment]
> Hi,
> 
> My environment is: Ubuntu 20.04, apollo-kernel 4.4.32-apollo-2-RT, and apollo git master version. In addition, gcc/g++ versions are as following:
> 
> ```
> $ gcc --version
> gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
> $ g++ --version
> g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
> ```
> 
> Failed to compile apollo with the following command:
> 
> ```
> $ ./apollo.sh build
> [...]
> (05:08:20) ERROR: /apollo/modules/perception/base/BUILD:358:11: C++ compilation of rule '//modules/perception/base:syncedmem' failed (Exit 1)
> In file included from external/uuid/cublas_v2.h:65:0,
>                  from ./modules/perception/base/common.h:21,
>                  from ./modules/perception/base/syncedmem.h:66,
>                  from modules/perception/base/syncedmem.cc:63:
> external/uuid/cublas_api.h:72:10: fatal error: driver_types.h: No such file or directory
>  #include "driver_types.h"
>           ^~~~~~~~~~~~~~~~
> compilation terminated.
> (05:08:21) INFO: Elapsed time: 183.508s, Critical Path: 36.60s
> (05:08:21) INFO: 2278 processes: 2278 local.
> (05:08:21) FAILED: Build did NOT complete successfully
> ```
> 
> Any hints for solving the problem?
> 
> Best regards,
> HY

It seems that this is duplicate issue for CPU/GPU builds. 
What's the output of `./apollo.sh config` from inside docker?

**Comment by hongyi-zhao** [comment]
```
[werner@in-dev-docker:/apollo]$ ./apollo.sh config
[WARNING] No nvidia-driver found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2020-08-21-d9fbebd03a
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200823_0534
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false USE_GPU=0
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] No nvidia-driver found. CPU will be used.
```

**Comment by storypku** [comment]
I guess the reason for downgrading gcc/g++ to 4.8 temporarily was to compile the (old) apollo-rt kernel. Just ignore it if you don't need to build apollo-rt kernel. cc here @diegohu 

Currently, Apollo master works not good enough with CPU only build. Many such issues had been raised, and we are expecting to resolve all these ASAP.

**Comment by hongyi-zhao** [comment]
> I guess the reason for downgrading gcc/g++ to 4.8 temporarily was to compile the (old) apollo-rt kernel. Just ignore it if you don't need to build apollo-rt kernel. cc here @diegohu

Thanks for pointing this out. I previously try to compile apollo-rt kernel by myself but failed. Seems maybe this is the reason.

> 
> Currently, Apollo master works not good enough with CPU only build. Many such issues had been raised, and we are expecting to resolve all these ASAP.

Do you mean, it works well with GPU enabled build?

**Comment by storypku** [comment]
> h GPU enabled build?

Yep. After all, we have tested Apollo extensively with GPU enabled.
