### ISSUE TITLE
Can't find LoadImages.sh at all.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12221]
Hi,

Based on the instructions [here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E8%AE%BE%E7%BD%AEapollo%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83), it told the following thing:
```
cd ~/images_r5.5.0
sudo bash LoadImages.sh
```
But I can't this directory and the corresponding bash script at all. Any hints?

Best regards,
HY

**Comment by macDure** [comment]
First of all, this shell script requires the one who has purchased the D Kit within installing software in advance. If you did not buy a D Kit, just skip this step and follow the next step please.

**Comment by hongyi-zhao** [comment]
Our group has purchased two sets of D-Kit, numbered as 2020012 and 2020014.

**Comment by diegohu** [comment]
@hongyi-zhao, the LoadImages.sh script is not part of Apollo source code, but a part of latest D-KIT pre-installed system which will facilitate the usability of D-KIT. If you don't have the script, the pre-installed system is not included in your D-KIT IPC which should be in a previous batch. 
D-KIT specific issue, please contact our customer representative to create an account and  raise questions in "D-KIT feedback" platform.

**Comment by storypku** [comment]
Thanks @diegohu for replying. 
This issue is going to be closed now. Thanks for supporting Apollo!
