### ISSUE TITLE
build cyber.aarch64 success but shows qt

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#12230]
I'm build docker under aarch64 success but qt is un-installed. Why so? Is qt not support aarch64,or Apollo think arm cannot run qt?

![image](https://user-images.githubusercontent.com/4536559/91030553-ed76e700-e631-11ea-8ba4-7baef70b7081.png)

**Comment by storypku** [comment]
> I'm build docker under aarch64 s

Just ignore that message.

Apollo uses Qt for building `cyber_visualizer`.  For aarch64, we are not ready to ship Qt5 yet, not to mention `cyber_visualizer`.

Thanks for reporting. We shall make Qt and `cyber_visualizer` ready ASAP.

**Comment by storypku** [comment]
> > I'm build docker under aarch64 s
> 
> Just ignore that message.
> 
> Apollo uses Qt for building `cyber_visualizer`. For aarch64, we are not ready to ship Qt5 yet, not to mention `cyber_visualizer`.
> 
> Thanks for reporting. We shall make Qt and `cyber_visualizer` ready ASAP.

Hi, I have just built a new cyber.aarch64 image with Qt 5.12.9 and cyber_visualizer. And it has been merged into `master`. 
However, No Jetson Nano/TX2/Xavier board with X Windows was available for our team. Could please help check if it works ?
Thank you.
