### ISSUE TITLE
Docker build script uses local ip to get library, and the image create procedure fails

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#12231]
I'm trying to build docker image for tegra hardware, but fails ,shows the error log below:

![image](https://user-images.githubusercontent.com/4536559/91031574-5e6ace80-e633-11ea-854c-9130e293d965.png)

Why apollo uses local ip to get libraries?

**Comment by storypku** [comment]
> I'm trying to build docker image for tegra hardware, but fails ,shows the error log below:
> 
> Why apollo uses local ip to get libraries?

Apollo use local HTTP cache to speed up docker build. See the updated `README.md` in this PR #12234 

As for `tegra_cyber.dockerfile`, It is still in testing stage. And I don't think it's a good idea to put third_party packages on the Internet without appropriate license.

Hope my answer meets your curiosity. :-)
