### ISSUE TITLE
Has the -l option substituted the -n option for dev_start.sh?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12241]
Hi,

For the latest git master apollo, it seems the -l option substituted the -n option for dev_start.sh. See the following:

```
$ bash docker/scripts/dev_start.sh -n
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] Unknown option: -n
$ bash docker/scripts/dev_start.sh -h | grep -e -l
[WARNING] No nvidia-driver found. CPU will be used.
    -l, --local            Use local docker image.
```

Am I right? 

Best regards,
HY

**Comment by storypku** [comment]
Yep. We combined `-l` and `-n` functionalities into the unified `-l` option for use local docker images/volumes.
