### ISSUE TITLE
Is nvidia-container-toolkit still one of the prerequisites required to setting up the docker environment for apollo master's compilation?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12249]
Hi,

[Here](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#set-up-the-docker-environment) told the steps for setting up the docker environment used by apollo. The step 4 said that:

`Install latest nvidia-container-toolkit by following the ` [official doc](https://github.com/NVIDIA/nvidia-docker).

I want to know whether this is still a prerequisite for the apollo master's docker environment configuration?

Best regards,
HY

**Comment by storypku** [comment]
> Hi,
> 
> [Here](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#set-up-the-docker-environment) told the steps for setting up the docker environment used by apollo. The step 4 said that:
> 
> `Install latest nvidia-container-toolkit by following the ` [official doc](https://github.com/NVIDIA/nvidia-docker).
> 
> I want to know whether this is still a prerequisite for the apollo master's docker environment configuration?
> 
> Best regards,
> HY

Yep. As long as you want to enable GPU build.

**Comment by ntutangyun** [comment]
I think nvidia-container-runtime is enough.
