### ISSUE TITLE
About the differences between the apollo cyber and dev images.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12252]
Hi,

[Here](https://github.com/ApolloAuto/apollo/tree/master/docker/build) told the following:

`As you may already know, Apollo was run inside Docker container, and there are two flavors of Apollo docker images, CyberRT (Cyber for short) and Dev . Cyber images were for developers who want to play with the CyberRT framework, while Dev images were for all others.`

But based on the above descriptions, I'm still not so clear on the differences between the apollo cyber and dev images. Any hints will be highly appreciated.

Best regards,
HY

**Comment by storypku** [comment]
> Hi,
> 
> [Here](https://github.com/ApolloAuto/apollo/tree/master/docker/build) told the following:
> 
> `As you may already know, Apollo was run inside Docker container, and there are two flavors of Apollo docker images, CyberRT (Cyber for short) and Dev . Cyber images were for developers who want to play with the CyberRT framework, while Dev images were for all others.`
> 
> But based on the above descriptions, I'm still not so clear on the differences between the apollo cyber and dev images. Any hints will be highly appreciated.
> 
> Best regards,
> HY

Put it shortly, the `Cyber` image was just enough to build  all libraries and tools under the `cyber` directory, while `dev` image was for building the whole Apollo project.

**Comment by storypku** [comment]
I must admit that  I am not a good technical writer with fluent English, if that confused you.
