### ISSUE TITLE
Does the ``apollo.sh build'' invoking the scripts here: https://github.com/ApolloAuto/apollo/tree/master/docker/build?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12259]
Hi,

I try to figure out the build process of the apollo docker image based on the logic of [apollo.sh](https://github.com/ApolloAuto/apollo/blob/master/apollo.sh). But it's rather complicated and I still not so clear till now. Especially, I want to know whether the apollo.sh will invoke the script located [here](https://github.com/ApolloAuto/apollo/tree/master/docker/build). 

Best regards,
HY

**Comment by storypku** [comment]
Hi HongYi,
     `apollo.sh build/test/coverage` was used to build, test, code coverage the who Apollo project. It's **not** for docker image build. To build Apollo docker images, please change to the `docker/build` directory, and follow [Apollo Docker Image Build Guide](https://github.com/ApolloAuto/apollo/blob/master/docker/build/README.md)  on how to build your own docker images.

You can then run `dev_start/dev_into` with your locally built image as follows:

```
docker/scripts/dev_start.sh -l -t dev-x86_64-18.04-20200821_1308
```

FYI: For Chinese speaking users, there is a dedicated forum named  "Apollo Developer Community" (In Chinese, "阿波罗开发者社区"). Here is the [link](https://apollo.auto/devcenter/devcenter_cn.html).

Hope my answer helps.

**Comment by hongyi-zhao** [comment]
To be frank, I don't most Chinese forum/community. Say, for the one you mentioned above, I don't find any forum/discussions there besides selling and buying.

**Comment by storypku** [comment]
> To be frank, I don't like most Chinese forums/communities. Say, for the one you mentioned above, I don't find any forum/discussions there besides selling and buying.

OK. Then continue discussions here. 

And if you are interested in knowing more of Apollo internals, tweak it to discover more!

**Comment by hongyi-zhao** [comment]
Thanks a lot.
