### ISSUE TITLE
Don't understand e2e online system

### ISSUE THREAD

**Issue by yiakwy** [ApolloAuto/apollo#1225]
I know this module provides source code to build "px2_camera_image" module, but what I don't understand is what 's relationship to the apollo end2end sample data and their expected position in perception - planning workflow.

https://console.bce.baidu.com/apollo/task/download/?_=1510542545943&locale=zh-cn#/apollo/home

Hope someone can help to clarify my concerns. Thank you very much!

**Comment by gengqx** [comment]
I think it is an independent module,it is used to collect data in Px2 environment,the ros version and the compute platform is totally different with apollo 1.5.The percetion module now just use the lidar data,So just ignore it now.

**Comment by hxdoit** [comment]
we have move data download address to http://data.apollo.auto，thanks

**Comment by linpanusst** [comment]
@yiakwy 
Hi, did you run the demo in e2e?
I am beginning to learn this modules, but I can't understand that if I can run this demo in simulation?
What the difference between e2e and the regular automatic pilot?
thank you for your reply.
