### ISSUE TITLE
Do we really need highest permission for the unix socket: sudo chmod 777 /var/run/docker.sock?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12257]
Hi,

[Here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E8%AE%BE%E7%BD%AEapollo%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83) use the following command to set the unix socket permission for docker:

`sudo chmod 777 /var/run/docker.sock`

It's well known that the higher the permission, the greater the security risk. So, do we really need the highest permission for it? 

OTOH, the corresponding [installation script](https://github.com/ApolloAuto/apollo/blob/master/docker/setup_host/install_docker.sh) don't set this permission at all.

Any hints for this problem?

Best regards,
HY

**Comment by storypku** [comment]
> Hi,
> 
> [Here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E8%AE%BE%E7%BD%AEapollo%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83) use the following command to set the unix socket permission for docker:
> 
> `sudo chmod 777 /var/run/docker.sock`
>  
> It's well known that the higher the permission, the greater the security risk. So, do we really need the highest permission for it?
> 
> OTOH, the corresponding [installation script](https://github.com/ApolloAuto/apollo/blob/master/docker/setup_host/install_docker.sh) don't set this permission at all.
> 
> Any hints for this problem?
> 
> Best regards,
> HY

Good catch. cc @diegohu

**Comment by lishuanghua** [comment]
@hongyi-zhao After several tests, we find that the OS changed the rights of the /var/run/docker.sock file to 660 when it had been reboot, and the file's rights of 660 is also the lowest rights which is satisfied to our apollo system. So the highest permission is OK. Thank you for your issue.

**Comment by hongyi-zhao** [comment]
@lishuanghua Do you mean 660 is enough for apollo system? If so, there is no need to set it with 777.

**Comment by storypku** [comment]
> I do some further testings and find that 777 is really needed, say, by the script `docker/scripts/dev_start.sh`. With the default 660 permission, the following error will occur when running this script as a normal user:
> 
> ```
> $ bash docker/scripts/dev_start.sh
> [...]
> [INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200823_0534 ...
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=apolloauto%2Fapollo&tag=dev-x86_64-18.04-20200823_0534: dial unix /var/run/docker.sock: connect: permission denied
> [ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200823_0534
> ```
> 
> Best regards,
> HY

There must be something wrong in your configurations.

See mine

```
 $ ls -l  /var/run/docker.sock 
srw-rw---- 1 root docker 0 Aug 25 16:15 /var/run/docker.sock=
```

**Comment by hongyi-zhao** [comment]
Very good, thanks a lot. I pull the apollo source code to its latest HEAD, and the problem solved. See following for detail:

```
$ git log | head -8
commit a59061afe005fcda1b6bd9c325aa054e9d8d19ff
Author: storypku <storypku@gmail.com>
Date:   Thu Aug 27 06:53:23 2020 -0700

    Scripts: add two EnvVars for CI
    
    DOCKER_IMG & USE_GPU_HOST

$ stat -c "%a" /var/run/docker.sock
660
$ ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Aug 28 11:14 /var/run/docker.sock

$ bash docker/scripts/dev_start.sh
[...]
[ OK ] Congratulations! You have successfully finished setting up Apollo Dev Environment.
[ OK ] To login into the newly created apollo_dev_werner container, please run the following command:
[ OK ]   bash docker/scripts/dev_into.sh
[ OK ] Enjoy!

```
