### ISSUE TITLE
Planning msg is not ready!

### ISSUE THREAD

**Issue by mendep** [ApolloAuto/apollo#12268]
Apollo version: 5.5
Apollo Environment Settings:
  APOLLO_ROOT_DIR: /apollo
  APOLLO_CACHE_DIR: /apollo/.cache
  APOLLO_IN_DOCKER: true
  APOLLO_VERSION: HEAD-2020-07-24-ff4f2ffb8a
  APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false USE_GPU=1

Hi, after given new routing point the car won't drive. The nohup.out has the following output:
`/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt 11:02:08.129185 11288 control_component.cc:295] [control]       planning msg is not ready!`
![apollo-planning-issue](https://user-images.githubusercontent.com/16822424/91284448-35118600-e78c-11ea-9804-b3eba831b3c8.png)
![planning-log](https://user-images.githubusercontent.com/16822424/91284645-7a35b800-e78c-11ea-87df-6e9e8c494372.png)

**Comment by mendep** [comment]
From the top of the nohup.out file it prints the following regarding the word 'planning':

- poco shared library failed: /apollo/bazel-bin/modules/planning/libplanning_component.so
- Failed to load module: /apollo/modules/planning/dag/planning.dag
- Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/planning/libplanning_component.so

**Comment by jmtao** [comment]
@mendep have you build entire apollo? have you started planning module? (click button of "Module Controller" and see if both routing and planning module is turned on). please post screenshot of that.

**Comment by mendep** [comment]
The planning module is built and started. I solved the missing libraries errors, but the main message(Planning msg is not ready!) still remains and the car does not move. 
![plan](https://user-images.githubusercontent.com/16822424/91964158-13c21400-ed0f-11ea-8e1d-ff4f91585de2.png)

**Comment by jmtao** [comment]
@mendep please take a look at the logs of planning, and post error msgs here. 
/apollo/data/log/planning.*

**Comment by mendep** [comment]
@jmtao It says;
583661 E0915 17:06:14.635815 11981 reference_line_provider.cc:538] Failed to extract segments from routing
583662 E0915 17:06:14.635829 11981 reference_line_provider.cc:580] Failed to create reference line from routing
583663 E0915 17:06:14.635895 11981 reference_line_provider.cc:203] Fail to get reference line

**Comment by jmtao** [comment]
@mendep planning modules failed to find ADC's position along routing segment. Please use map view(layer view menu on the left side panel) to take a close look to see if ADC position is within routing or not. Sometimes there's longitudinal distance. If that's not the case, you have the planning code, can you please try to debug it on your own?  we'll stand by to help.

**Comment by jmtao** [comment]
Hi @mendep , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
