### ISSUE TITLE
86867223

### ISSUE THREAD

**Issue by FAAQ36187** [ApolloAuto/apollo#12265]

**Comment by ntutangyun** [comment]
the bridge is mainly for communication with the LGSVL simulator. 

If you want to receive messages published in CyberRT channels via bridge, you probably need
* run the `bridge.sh`
* create a socket connection to the bridge
* tell the bridge which channel you want to subscribe
* then the bridge will forward the message from cyber RT to the web socket.

**Comment by Doozua** [comment]
Thanks for fast answer.

I wonder what does it mean "create a socket connection to bridge"?

Should I make a socket programming?

Also, how to tell the bridge which channel I want?

Could you give me a detail?

**Comment by BBlumi97** [comment]
Hi,
Did you found out how to do it ? 

I have to send some data from apollo to another computer via udp. So maybe you solution could help me too.

**Comment by ntutangyun** [comment]
@FAAQ36187 yes, if you want to communicate with the bridge launched by 'bridge.sh', your code needs to set up a socket connection with the network address that the bridge server is listening to. By default, it's `localhost:9090`

The `cyber_bridge` requires special binary formats during communication. You could check out the code here on how to format the binary message to be parsed by `cyber_bridge`. Messages can have different types, such as subscribing to particular channels, publishing some channels, etc.  

https://github.com/ApolloAuto/apollo/blob/f2fef8158f548399c0a309772639096c884c23e4/modules/contrib/cyber_bridge/client.cc#L47

I think bridge.sh and `cyber_bridge` modules are added to Apollo at branch pre6, thus official available from Apollo 6.0.

**Comment by FAAQ36187** [comment]
@BBlumi97 

Yes I made it already. But I didn't use bridge. Because If you use the bridge, you might be not able to send to other computer only whenever get your message.

Because the bridge sends even if there is no data.

**Comment by ntutangyun** [comment]
> Because the bridge sends even if there is no data.

what do you mean by this :question:

**Comment by BBlumi97** [comment]
> @BBlumi97
> 
> Yes I made it already. But I didn't use bridge. Because If you use the bridge, you might be not able to send to other computer only whenever get your message.

How did you do it if you don't use the bridge ?

**Comment by Thinsheep** [comment]
> @FAAQ36187 yes, if you want to communicate with the bridge launched by 'bridge.sh', your code needs to set up a socket connection with the network address that the bridge server is listening to. By default, it's `localhost:9090`
> 
> The `cyber_bridge` requires special binary formats during communication. You could check out the code here on how to format the binary message to be parsed by `cyber_bridge`. Messages can have different types, such as subscribing to particular channels, publishing some channels, etc.
> 
> https://github.com/ApolloAuto/apollo/blob/f2fef8158f548399c0a309772639096c884c23e4/modules/contrib/cyber_bridge/client.cc#L47
> 
> I think bridge.sh and `cyber_bridge` modules are added to Apollo at branch pre6, thus official available from Apollo 6.0.

Hi @ntutangyun 
Is there any document or example showing how to publish/subscribe to/from Cyber Channels?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
