### ISSUE TITLE
Cyber Channel Echo Error

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#12279]
**Describe the bug**
Error on cyber_channel echo "any topic"

**To Reproduce**
1. Build apollo
2. Launch any module/record file
3. cyber_channel echo "topic name"

E0827 00:31:55.636370 23259 py_cyber.cc:644] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/bazel-bin/cyber/tools/cyber_channel/cyber_channel.runfiles/apollo/cyber/python/cyber_py3/cyber.py", line 227, in reader_callback
    sub[1](proto)
  File "/apollo/bazel-bin/cyber/tools/cyber_channel/cyber_channel.runfiles/apollo/cyber/tools/cyber_channel/cyber_channel.py", line 347, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/bazel-bin/cyber/tools/cyber_channel/cyber_channel.runfiles/apollo/cyber/python/cyber_py3/cyber.py", line 358, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set

**Expected behavior**
Print Topic details

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by changsh726** [comment]
> **Describe the bug**
> Error on cyber_channel echo "any topic"
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Build apollo
> 
>     2. Launch any module/record file
> 
>     3. cyber_channel echo "topic name"
> 
>     4. See error
> 
> 
> E0827 00:31:55.636370 23259 py_cyber.cc:644] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
> TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "_ctypes/callbacks.c", line 234, in 'calling callback function'
> File "/apollo/bazel-bin/cyber/tools/cyber_channel/cyber_channel.runfiles/apollo/cyber/python/cyber_py3/cyber.py", line 227, in reader_callback
> sub[1](proto)
> File "/apollo/bazel-bin/cyber/tools/cyber_channel/cyber_channel.runfiles/apollo/cyber/tools/cyber_channel/cyber_channel.py", line 347, in callback
> print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
> File "/apollo/bazel-bin/cyber/tools/cyber_channel/cyber_channel.runfiles/apollo/cyber/python/cyber_py3/cyber.py", line 358, in get_debugstring_rawmsgdata
> return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
> SystemError: returned a result with an error set
> 
> **Expected behavior**
> Print Topic details
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Ubuntu 18.04

This has been fixed in #12280. Thank you for your support to Apollo!

**Comment by agarwalsid** [comment]
Thank you @changsh726
