### ISSUE TITLE
What's the differences of the functionalities between the apollo enterprise and open source versions?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12283]
Hi,

I've learned that besides the open source version, apollo also has an enterprise version which is used on some products from Baidu, say, robotaxi. Could you please give me some hints/notes on the differences of the functionalities between the apollo enterprise and open source versions?

Best regards,
HY

**Comment by jinghaomiao** [comment]
@hongyi-zhao Apollo enterprise is a production solution for enterprise users, which involves security, safety and other features in addition to autonomous driving tech stack and it's not free.

**Comment by jinghaomiao** [comment]
Hope your question is answered. Please raise other issues if needed. Thanks for using Apollo.

**Comment by hongyi-zhao** [comment]
> security, safety

What's the differences between the meanings of these 2 words in the context used here?
