### ISSUE TITLE
How Could I control the real car through the scripts  scripts/canbus_teleop.sh?

### ISSUE THREAD

**Issue by Capdavin** [ApolloAuto/apollo#12298]
When I started the Socketcan Server and make the following shell script working, 
       bash scripts/canbus_teleop.sh
down the proper key, but the real car didn't move yet. 
I‘m puzzled by what happend in the past few days.I beg for the Master to help.

**Comment by Capri2014** [comment]
yes, it is not for simulation, only used for on real vehicle.
