### ISSUE TITLE
Use relative path for symlinks generated during the compilation of apollo.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12293]
Hi,

The following symlinks are generated during the ompilation of apollo and they are created using absolute path from within the docker environment:

```
werner@X10DAi-01:~/Public/repo/github.com/ApolloAuto/apollo.git$ find . -maxdepth 1 -xtype l -exec ls -l {}  \;
lrwxrwxrwx 1 werner werner 79 Aug 28 14:48 ./bazel-out -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out
lrwxrwxrwx 1 werner werner 69 Aug 28 14:48 ./bazel-apollo -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo
lrwxrwxrwx 1 werner werner 101 Aug 28 14:48 ./bazel-testlogs -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs
lrwxrwxrwx 1 werner werner 96 Aug 28 14:48 ./bazel-bin -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/bin
```
So, when I exit the docker environment, these symlinks will be broken. For solving this problem, they can be created using the relative path w.r.t the $APOLLO_HOME

Best regards,
HY

**Comment by storypku** [comment]
> Hi,
> 
> The following symlinks are generated during the ompilation of apollo and they are created using absolute path from within the docker environment:
> 
> ```
> werner@X10DAi-01:~/Public/repo/github.com/ApolloAuto/apollo.git$ find . -maxdepth 1 -xtype l -exec ls -l {}  \;
> lrwxrwxrwx 1 werner werner 79 Aug 28 14:48 ./bazel-out -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out
> lrwxrwxrwx 1 werner werner 69 Aug 28 14:48 ./bazel-apollo -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo
> lrwxrwxrwx 1 werner werner 101 Aug 28 14:48 ./bazel-testlogs -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs
> lrwxrwxrwx 1 werner werner 96 Aug 28 14:48 ./bazel-bin -> /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/bin
> ```
> 
> So, when I exit the docker environment, these symlinks will be broken. For solving this problem, they can be created using the relative path w.r.t the $APOLLO_HOME
> 
> Best regards,
> HY

[Bazel output directory](https://docs.bazel.build/versions/master/output_directories.html) in Apollo was set by running `./apollo.sh config` to write the following into `.apollo.bazelrc`.  
 
```
startup --output_user_root="/apollo/.cache/bazel
```

See  https://github.com/ApolloAuto/apollo/blob/master/apollo.sh#L86


And this directory should be absolute path though, otherwise we will have a `.cache/bazel` dir relative to you current working directory every time you run Bazel commands like build, test, ... etc.

Those symlinks are expected to work inside docker. If you want to make them work outside docker, you can run the following command:

```
sudo ln -snf ${APOLLO_ROOT_DIR} /apollo
```

which was set by default by previous versions of Apollo. E.g., https://github.com/ApolloAuto/apollo/blob/pre6/docker/scripts/dev_start.sh#L105

However, I didn't think it's an appropriate settings to be set as default, for two reasons:

1)  It requires `sudo` privilege and the `/apollo` directory on host, a directory normal users can't write.
2) It may cause unexpected behavior for multi-user workstation.

For these reasons,  this "symlink"-ing operation was removed in the `master` branch.

cc also @xiaoxq @Capri2014 @jinghaomiao .

**Comment by hongyi-zhao** [comment]
@storypku Thanks for your detail explanations on this question.

> sudo ln -snf ${APOLLO_ROOT_DIR} /apollo

I also noticed that there are another environment variable named as `APOLLO_HOME`, and it seems that it has the same meaning as `APOLLO_ROOT_DIR`. If they are really the same, why use two variables for one thing?

Best regards,
HY

**Comment by storypku** [comment]
> H

Good catch. 

 I searched the whole repo and  found many uses of  `APOLLO_HOME` in our documents (and **only in documents**).

Both variables exist for historical reasons, and will be unified in later documentation updates except for legacy documents.
Thank you for pointing that.

Personally, I prefer the `APOLLO_ROOT_DIR` notation to mean **Apollo's root directory**,  'cause  it is more native.

Regards,

Jiaming Liu

**Comment by hongyi-zhao** [comment]
See [here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E8%AE%BE%E7%BD%AEapollo%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83), it told the following setting:

`echo "export APOLLO_HOME=$(pwd)" >> ~/.bashrc && source ~/.bashrc`

So, if I understand you correctly, it should be set like the following:

`echo "export APOLLO_ROOT_DIR=$(pwd)" >> ~/.bashrc && source ~/.bashrc`

But, I really want to know whether this variable has to be exported like the above for the latest git master version of apollo.

Best regards,
HY

**Comment by storypku** [comment]
> See [here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/D-kit/Waypoint_Following/Apollo_Installation_cn.md#%E8%AE%BE%E7%BD%AEapollo%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83), it told the following setting:
> 
> `echo "export APOLLO_HOME=$(pwd)" >> ~/.bashrc && source ~/.bashrc`
> 
> So, if I understand you correctly, it should be set like the following:
> 
> `echo "export APOLLO_ROOT_DIR=$(pwd)" >> ~/.bashrc && source ~/.bashrc`
> 
> But, I really want to know whether this variable still needs to be exported like the above for the latest git master version of apollo.
> 
> Best regards,
> HY

There seems no need.  However, we will check it next week.
Happy weekend.
