### ISSUE TITLE
About the relationship between stuff on http://apolloauto.club/mirror/ and https://github.com/ApolloAuto.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12301]
Hi,

I noted there is another [website](http://apolloauto.club/mirror/) relative to apollo. And there are so much stuff there. Could you please give me some hints on the relationship between stuff [here](https://github.com/ApolloAuto) and [there](http://apolloauto.club/mirror/).

Best regards,
HY

**Comment by storypku** [comment]
I guess the former was not maintained by the Apollo team, but a site created by some Apollo user hosting archives of Apollo-related packages, data files, etc. 

Am I right? @xiaoxq @jinghaomiao @ycool

**Comment by storypku** [comment]
This issue is going to be closed. If you have other questions, please feel free to open another issue.
Thanks for supporting Apollo!
