### ISSUE TITLE
Add demos for recent versions of apollo.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12308]
Hi,

I noticed the list of current demos in this [file](https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/rosbag_helper.py). It seems that they are too old for the current version of apollo - the last updated demo is for apollo v3.5.0.

Could you please add/create more demos for the recent apollo versions?

Best regards,
HY

**Comment by AndrewXWei** [comment]
These demo records are based on ROS. Apollo has been upgraded to Cyber after that. We currently don't have any cyber records for demo use. Sorry for any inconveniences caused.

**Comment by jinghaomiao** [comment]
Thanks for using Apollo. This issue is being closed. Please raise new issues should you have any.
