### ISSUE TITLE
Fail to run: cyber_recorder play -f demo_2.5.bag -l

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12306]
Hi,

I comipled the apollo r5.5.0 and try to play the [demo bag](https://github.com/ApolloAuto/apollo/releases/download/v2.5.0/demo_2.5.bag), but failed. See following for more info:

```
$ cyber_recorder play -f demo_2.5.bag -l   
E0829 12:43:09.813866 18690 record_file_reader.cc:67] [cyber_recorder]Check section type failed, expect: 0, actual: 1397707299
E0829 12:43:09.813889 18690 record_file_reader.cc:42] [cyber_recorder]Read header section fail, file: demo_2.5_2.bag
E0829 12:43:09.813899 18690 record_reader.cc:35] [cyber_recorder]Failed to open record file: demo_2.5_2.bag
earliest_begin_time: 18446744073709551615, latest_end_time: 0, total_msg_num: 0
E0829 12:43:09.813922 18690 play_task_producer.cc:176] [cyber_recorder]begin time are equal or larger than end time, begin_time_ns=18446744073709551615, end_time_ns=0
```
Any hints for this problem?

Regards,
HY

**Comment by macDure** [comment]
please try to run rosbag play 2.5.bag -l

**Comment by hongyi-zhao** [comment]
Don't have that command at all, see following for more info:

```
$ rosbag -h
bash: rosbag: command not found
```

**Comment by macDure** [comment]
in version apollo3.0 or below can do this

**Comment by jinghaomiao** [comment]
Starting from Apollo 3.5, rosbags are no longer supported. Please refer to earlier version of ROS based Apollo. This issue is being closed. Please feel free to raise new issues should you have any. Thanks for using Apollo.
