### ISSUE TITLE
Has cyber_recorder command substituted rosbag?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12305]
Hi,

In the [demo_guide](https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide), it told the following:

`cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop`

But [here](https://medium.com/@flaaud159/whole-process-of-baidu-apollo-offline-demo-environment-construction-d8d9e1a70bdf) told the following:

`rosbag play demo_2.0.bag --loop`

So, I want know whether the cyber_recorder command is the successor of rosbag and the rosbag command has been discarded now in the git master version?

If no, what's differences between these two commands?

Best regards,
HY

**Comment by AndrewXWei** [comment]
> whether the cyber_recorder command is the successor of rosbag and the rosbag command has been discarded now in the git master version

Yes, we have upgraded ros to cyber. Any commands of ros are unavailable. Please refer to our latest documentation. Thank you for your attention.

**Comment by hongyi-zhao** [comment]
I'm still confused on this switch. The Robot Operating System (ROS) is very famous and its current [ROS 2 LTS](https://index.ros.org/doc/ros2/Installation/Foxy/) implementation is also powerful than previous versions. So, I want to know what's the differences between ros and cyber? Are there some more excellent capabilities included in cyber which is unavailable in ros?

Regards,
HY

**Comment by storypku** [comment]
Apollo has switched to CyberRT since Apollo 3.5 release. And the migration from  ROS to CyberRT can be found [here](https://github.com/ApolloAuto/apollo/blob/master/cyber/doxy-docs/source/CyberRT_Migration_Guide.md).
