### ISSUE TITLE
OSQP solver readme 

### ISSUE THREAD

**Issue by glebkiselev** [ApolloAuto/apollo#12316]
I'm trying to figure out Apollo and want to try to write my own solver to control the behavior of the car. As far as I understand from the description, Apollo uses the OSQP library to set the conditions for moving the car. I looked in the apollo/planning/task/deciders folder and did not find an OSQP call. Could you please clarify how the call takes place and how the QP matrix is formed?
I use apollo 5.0 and LG simulator.

**Comment by glebkiselev** [comment]
I'm trying to figure out Apollo and want to try to write my own solver to control the behavior of the car. As far as I understand from the description, Apollo uses the OSQP library to set the conditions for moving the car. I looked in the apollo/planning/task/deciders folder and did not find an OSQP call. Could you please clarify how the call takes place and how the QP matrix is formed?

**Comment by jinghaomiao** [comment]
@glebkiselev :https://github.com/ApolloAuto/apollo/tree/master/modules/planning/tasks/optimizers

**Comment by jinghaomiao** [comment]
Closing this ticket now. Should you have more questions, please feel free to raise new issues. Thanks for using Apollo.
