### ISSUE TITLE
faild build :bash apollo.sh build_opt_gpu;(data_provider.cc: ...has no member named 'count')

### ISSUE THREAD

**Issue by devynliu** [ApolloAuto/apollo#12315]
**Describe the bug**
env:
 - OS: [ubuntu :18.04]
 - Browser [e.g. chrome]
 - Version [Apollo:master]
GPU:RTX2080Ti
Nvidia-smi:
Mon Aug 31 16:30:25 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   30C    P8    19W / 280W |    645MiB / 11016MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1427      G   /usr/lib/xorg/Xorg                203MiB |
|    0   N/A  N/A      1795      G   /usr/bin/gnome-shell              185MiB |
|    0   N/A  N/A      4322      G   ...AAAAAAAAA= --shared-files       31MiB |
|    0   N/A  N/A      9432      G   ...token=7462995565156544912       84MiB |
|    0   N/A  N/A     10722      G   ...AAAAAAAAA= --shared-files      135MiB |
+-----------------------------------------------------------------------------+

Question:
when i start command"bash apollo.sh build_opt_gpu",it occurs a error:
"
```bash
(08:24:59) ERROR: /apollo/modules/perception/camera/common/BUILD:27:11: C++ compilation of rule '//modules/perception/camera/common:data_provider' failed (Exit 1)
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::FillImageData(int, int, const uint8_t*, const string&)':
modules/perception/camera/common/data_provider.cc:135:50: error: 'using element_type = class apollo::perception::base::Image8U {aka class apollo::perception::base::Image8U}' has no member named 'count'
     memcpy(rgb_->mutable_cpu_data(), data, rgb_->count() * sizeof(data[0]));
                                                  ^~~~~
modules/perception/camera/common/data_provider.cc:139:50: error: 'using element_type = class apollo::perception::base::Image8U {aka class apollo::perception::base::Image8U}' has no member named 'count'
     memcpy(bgr_->mutable_cpu_data(), data, bgr_->count() * sizeof(data[0]));
                                                  ^~~~~
modules/perception/camera/common/data_provider.cc:143:52: error: 'using element_type = class apollo::perception::base::Image8U {aka class apollo::perception::base::Image8U}' has no member named 'count'
     memcpy(gray_->mutable_cpu_data(), data, gray_->count() * sizeof(data[0]));

```
"
Anyone can help me for this question?Thanks!

**Comment by storypku** [comment]
Got it. We will look into this issue right now.

**Comment by devynliu** [comment]
Thanks!
Also,this data_provider.cc once occurd other error:
"
```bash
(05:37:08) ERROR: /apollo/modules/perception/camera/common/BUILD:27:11: C++ compilation of rule '//modules/perception/camera/common:data_provider' failed (Exit 1)
In file included from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/cuda_runtime.h:95:0,
                 from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/nppdefs.h:52,
                 from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/nppi.h:60,
                 from modules/perception/camera/common/data_provider.cc:18:
bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/channel_descriptor.h:104:1: error: template with C linkage
 template<class T> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc(void)
 ^~~~~~~~
bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/channel_descriptor.h:137:1: error: template specialization with C linkage
 template<> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc<char>(void)
```
"
i fix the this question,with adding "#include <cuda_runtime.h>"
```cpp
#include <cuda_runtime.h>
#include <nppi.h>
```
在nppi.h前加入一条：cuda_runtime.h

**Comment by storypku** [comment]
> Thanks!
> Also,this data_provider.cc once occurd other error:
> "
> 
> ```shell
> (05:37:08) ERROR: /apollo/modules/perception/camera/common/BUILD:27:11: C++ compilation of rule '//modules/perception/camera/common:data_provider' failed (Exit 1)
> In file included from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/cuda_runtime.h:95:0,
>                  from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/nppdefs.h:52,
>                  from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/nppi.h:60,
>                  from modules/perception/camera/common/data_provider.cc:18:
> bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/channel_descriptor.h:104:1: error: template with C linkage
>  template<class T> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc(void)
>  ^~~~~~~~
> bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/channel_descriptor.h:137:1: error: template specialization with C linkage
>  template<> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc<char>(void)
> ```
> 
> "
> i fix the this question,with adding "#include <cuda_runtime.h>"
> 
> ```c++
> #include <cuda_runtime.h>
> #include <nppi.h>
> ```
> 
> 在nppi.h前加入一条：cuda_runtime.h

I am wondering if you haven't pull the latest `master` ... I cleaned up **everything bazel outputs**, and can't reproduce your issue.

**Comment by storypku** [comment]
> Thanks!
> Also,this data_provider.cc once occurd other error:
> "
> 
> ```shell
> (05:37:08) ERROR: /apollo/modules/perception/camera/common/BUILD:27:11: C++ compilation of rule '//modules/perception/camera/common:data_provider' failed (Exit 1)
> In file included from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/cuda_runtime.h:95:0,
>                  from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/nppdefs.h:52,
>                  from bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/nppi.h:60,
>                  from modules/perception/camera/common/data_provider.cc:18:
> bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/channel_descriptor.h:104:1: error: template with C linkage
>  template<class T> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc(void)
>  ^~~~~~~~
> bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include/channel_descriptor.h:137:1: error: template specialization with C linkage
>  template<> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc<char>(void)
> ```
> 
> "
> i fix the this question,with adding "#include <cuda_runtime.h>"
> 
> ```c++
> #include <cuda_runtime.h>
> #include <nppi.h>
> ```
> 
> 在nppi.h前加入一条：cuda_runtime.h

I noticed that you use CUDA-11.0, was that inside docker ?

**Comment by devynliu** [comment]
Yes，I tried apollo5.5 and pre6，i never meet this issue. i want pull lastest master to run simulation with lgsvl。But，lastest master haven't build successfully.

**Comment by storypku** [comment]
> Yes，I tried apollo5.5 and pre6，i never meet this issue. i want pull lastest master to run simulation with lgsvl。But，lastest master haven't build successfully.

We actually haven't tested `master` with CUDA-11.0 w/ cuDNN-8 yet. Hopes that We can make compatibility with CUDA-11.0 (w/ cuDNN8) toolkit possible in the next  few days.

Thank you for reporting this issue, and sorry for the inconvenience.

**Comment by devynliu** [comment]
1-in docker. I run nvidiasmi，it appear. but，my Ubuntu is not Rt operation system.
2- Because after I install apollo kernel ，run bash dev_start. sh，it show docker run --gpus all -it .... then ，it stop go on，my computer crashd，ubuntu no any reaction. only，strongly shutdown。
3- i also try 5.5 and pre6 in Ubuntu not RT. it can bootstrap.

**Comment by storypku** [comment]
> 1-in docker. I run nvidiasmi，it appear. but，my Ubuntu is not Rt operation system.
> 2- Because after I install apollo kernel ，run bash dev_start. sh，it show docker run --gpus all -it .... then ，it stop go on，my computer crashd，ubuntu no any reaction. only，strongly shutdown。
> 3- i also try 5.5 and pre6 in Ubuntu not RT. it can bootstrap.

Got it. Please don't install the old and seemingly unmaintained 4.4 based Apollo-RT kernel if you want to run the simulators only. 
We are planning for document upgrade and will warn users of usage for this RT/non-RT kernel case.

Thanks again for reporting.

**Comment by devynliu** [comment]
Thank you.  I look forward to seeing your  upgrade document for simulators. 
And can you give a suggest for Cuba version？I will try reinstall nvidia again. 
now the perception module of lastest master can use for lgsvl simulator？

**Comment by storypku** [comment]
> nvidia

Theoretically,  as long as NVIDIA Driver >= 440.33, it will be OK. CUDA 10.2 was pre-installed into Apollo docker images. So for CUDA toolkit out of docker, CUDA toolkit >= 10.2 will be OK.

For perception,  I will ask other members of our team for updates. @jeroldchen

**Comment by jeroldchen** [comment]
@devynliu Of course perception module supports LGSVL simulator, as we have updated the dag file for LGSVL at [https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/dag/dag_streaming_perception_lgsvl.dag](url). This is the default dag to launch perception module under LGSVL mode.

**Comment by devynliu** [comment]
Thanks. i slove this issue(build),with reinstall nivida driver 440.36 and cuda 10.2.89.

**Comment by devynliu** [comment]
@jeroldchen hello,i now run Apolloolatest master and lgsvl simulator,i can start perception moudule.
1- but the recognition quality with lidar and radar is very bad.example,when other car pass through ,the perception somtimes cannot recognize.
2- and the traffic module cannot start,the log show"Path does not exist: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so",Now ,can this question be sloved?
thanks！

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
