### ISSUE TITLE
Questions for the 32-line LiDAR in Apollo perception

### ISSUE THREAD

**Issue by ningfeiwang** [ApolloAuto/apollo#12341]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Hello,

I have a question about the 32-line LiDAR (e.g., HDL32) in Apollo perception. I found that the LiDAR-based perception models in Apollo-5.5 only support 16-, 64-, 128- line LiDAR (https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/lidar/models/cnnseg). But in the documents, it provides installation guide of the Puck Series LiDAR (and HDL32) (https://github.com/ApolloAuto/apollo/blob/ca66ba5244f9a77fa1218f3dfcf27707932b3aae/docs/specs/Lidar/VLP_Series_Installation_Guide.md). Thus, I wonder how the HDL32 works in Apollo perception without the LiDAR-based perception models and how to enable it. Could anyone help me on that? Thanks a lot!

**Comment by lucasnmatias** [comment]
I'm also interested on this. Should we use the models trained for the other LiDARs? Would it be possible to train a new model for this LiDAR?

**Comment by jeroldchen** [comment]
I have answered a similar question in #12629 .

**Comment by daohu527** [comment]
You know model's input is tensor, it doesn't know the number of lidar lines. So a 32-line model might work for a 16 or 64, but it might be worse
