### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by wzkwzk123** [ApolloAuto/apollo#12353]
Hello,  i want to run apollo code on my own cmputer and try to install it. But when i run the command -- bash docker/scripts/dev_into.sh, error occurs with there is no space left on device. i use -- df -h to check the usage of device and find that, 100% used under the /   directory. I think the reason is : apollo use the space under / to build the model. Can i change the compile directory to /usr??  Thanks!!

We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by xiaoxq** [comment]
It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.

**Comment by storypku** [comment]
> It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.

Agree.  If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.

And if your `/`  is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.

Say, `ln -s /mnt/big_disk /var/lib/docker`.

**Comment by wzkwzk123** [comment]
> It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.

udev             7.5G     0  7.5G    0% /dev
tmpfs            1.6G   11M  1.5G    1% /run
/dev/nvme0n1p6    19G   19G     0  100% /
/dev/nvme0n1p10   84G   12G   69G   15% /usr
tmpfs            7.6G  228M  7.3G    3% /dev/shm
tmpfs            5.0M  4.0K  5.0M    1% /run/lock
tmpfs            7.6G     0  7.6G    0% /sys/fs/cgroup
/dev/nvme0n1p9   9.4G   37M  8.8G    1% /tmp
/dev/nvme0n1p11  9.4G  2.4G  6.5G   27% /var
/dev/nvme0n1p8    38G   32G  3.8G   90% /home
/dev/nvme0n1p7   946M  138M  744M   16% /boot
/dev/loop0        55M   55M     0  100% /snap/core18/1880
/dev/loop1        97M   97M     0  100% /snap/core/9804
/dev/nvme0n1p1   256M   36M  221M   15% /boot/efi
/dev/loop2       126M  126M     0  100% /snap/docker/471
/dev/loop3        56M   56M     0  100% /snap/core18/1885
/dev/loop4       241M  241M     0  100% /snap/gnome-3-34-1804/24
/dev/loop6        30M   30M     0  100% /snap/snapd/8542
/dev/loop5        30M   30M     0  100% /snap/snapd/8790
/dev/loop7        63M   63M     0  100% /snap/gtk-common-themes/1506
/dev/loop8        50M   50M     0  100% /snap/snap-store/467
/dev/loop9        50M   50M     0  100% /snap/snap-store/433
/dev/loop10      256M  256M     0  100% /snap/gnome-3-34-1804/36
tmpfs            1.6G   20K  1.6G    1% /run/user/125
tmpfs            1.6G   56K  1.6G    1% /run/user/1000

I am not familiar with Linux device space. This is the situation about my computer's  device usage. Can you give me some suggestion to fix the problem? Thanks a lot.

**Comment by wzkwzk123** [comment]
> > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> 
> Agree. If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.
> 
> And if your `/` is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.
> 
> Say, `ln -s /mnt/big_disk /var/lib/docker`.

Thanks, you mean move the 

> > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> 
> Agree. If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.
> 
> And if your `/` is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.
> 
> Say, `ln -s /mnt/big_disk /var/lib/docker`.

The problem may not due to /var/lib/docker is too big. i check the space under /var directory, still a lot of free space. I am not familiar with llinux system, maybe i am wrong. My device usage information is above, can you give me more suggestion in details? Thanks a lot!

**Comment by storypku** [comment]
> > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> 
> /dev/nvme0n1p6 19G 19G 0 100% /
> /dev/nvme0n1p10 84G 12G 69G 15% /usr
> /dev/nvme0n1p11 9.4G 2.4G 6.5G 27% /var

> 
> I am not familiar with Linux device space. This is the situation about my computer's device usage. Can you give me some suggestion to fix the problem? Thanks a lot.

For your case,  I would suggest the following operations:

```
sudo mkdir -p /usr/opt/apollo /usr/opt/docker
sudo chown -R your_username:your_group_name /usr/opt/apollo
ln -s /user/opt/apollo $HOME/apollo
```


Check your current /var/lib/docker 's ownership and permission set, and set `/user/opt/docker` accordingly.

And then,

```
systemctl stop docker
sudo ln -s /user/opt/docker /var/lib/docker
systemctl start docker
```

If the stop/start docker step fails, use `sudo` to try again.

**Comment by storypku** [comment]
> > > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> > 
> > 
> > Agree. If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.
> > And if your `/` is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.
> > Say, `ln -s /mnt/big_disk /var/lib/docker`.
> 
> Thanks, you mean move the
> 
> > > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> > 
> > 
> > Agree. If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.
> > And if your `/` is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.
> > Say, `ln -s /mnt/big_disk /var/lib/docker`.
> 
> The problem may not due to /var/lib/docker is too big. i check the space under /var directory, still a lot of free space. I am not familiar with llinux system, maybe i am wrong. My device usage information is above, can you give me more suggestion in details? Thanks a lot!

There was only 9.4G for your `/var`. You can try `sudo du -sh /var/lib/docker` to see how much space has been taken by docker.

**Comment by wzkwzk123** [comment]
> It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.

I find that all the build file is in /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32.    The size under this directory is 17G, my / directory is only 20G totally. How can i do with it? Thanks

**Comment by wzkwzk123** [comment]
> > > > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > > > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> > > 
> > > 
> > > Agree. If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.
> > > And if your `/` is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.
> > > Say, `ln -s /mnt/big_disk /var/lib/docker`.
> > 
> > 
> > Thanks, you mean move the
> > > > It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> > > > With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.
> > > 
> > > 
> > > Agree. If there are too many docker images on your host, your can run `bash docker/setup_host/cleanup_resources.sh` to clean them.
> > > And if your `/` is mounted on a disk with little space, you can make `/var/lib/docker` a symlink to another disk big enough.
> > > Say, `ln -s /mnt/big_disk /var/lib/docker`.
> > 
> > 
> > The problem may not due to /var/lib/docker is too big. i check the space under /var directory, still a lot of free space. I am not familiar with llinux system, maybe i am wrong. My device usage information is above, can you give me more suggestion in details? Thanks a lot!
> 
> There was only 9.4G for your `/var`. You can try `sudo du -sh /var/lib/docker` to see how much space has been taken by docker.


I find that all the build file is in /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32.    The size under this directory is 17G, my / directory is only 20G totally. How can i do with it? Thanks

**Comment by wzkwzk123** [comment]
> It's a general Linux problem and you should guarantee enough space under `/` otherwise a lot of problems will happen.
> With current master HEAD the bazel output is actually in /apollo/.cache/bazel. So you may need to do some system-wide clean up besides apollo stuffs.

I find that all the build file is in /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32. The size under this directory is 17G, my / directory is only 20G totally. How can i do with it? Thanks

**Comment by storypku** [comment]
> I find that all the build file is in /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32. The size under this directory is 17G, my / directory is only 20G totally. How can i do with it? Thanks

Apollo don't use `/.cache/` as default cache directory. Perhaps you mean `${APOLLO_ROOT_DIR}/.cache` ?
You can try to run `./apollo.sh clean --expunge` to remove any {bazel_output,coredump,log} files.

**Comment by wzkwzk123** [comment]
> > I find that all the build file is in /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32. The size under this directory is 17G, my / directory is only 20G totally. How can i do with it? Thanks
> 
> Apollo don't use `/.cache/` as default cache directory. Perhaps you mean `${APOLLO_ROOT_DIR}/.cache` ?
> You can try to run `./apollo.sh clean --expunge` to remove any {bazel_output,coredump,log} files.

Thanks for your reply.!

when i run the command -- bash apollo.sh build. The space under /  directory is used. Then i find the biggest directory is --  /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo# . The size is 17G. Details is below.  I thought this is the reason for the error. 

root@zwu-Lenovo-Legion-R7000-2020:~/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo# ls
apollo_docker.sh  CPPLINT.cfg  MANIFESTO.md     tools
apollo.doxygen    cyber        modules          ubuntu_18.04_env
apollo.sh         data         README.md        WORKSPACE
bazel-out         docker       readthedocs.yml  WORKSPACE.in
_bin              docs         RELEASE.md
BUILD             external     scripts
CONTRIBUTING.md   LICENSE      third_party
root@zwu-Lenovo-Legion-R7000-2020:~/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo# du -sh
17G	.

And a new problem. I restart my computer tomorrow and want to skip the command -- bash docker/scripts/dev_into.sh. Yesterday the error is no space left on device, now it returns -- Error: No such container: apollo_dev_root .

Two problems!! Thanks for your help again.

**Comment by storypku** [comment]
> > > I find that all the build file is in /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32. The size under this directory is 17G, my / directory is only 20G totally. How can i do with it? Thanks
> > 
> > 
> > Apollo don't use `/.cache/` as default cache directory. Perhaps you mean `${APOLLO_ROOT_DIR}/.cache` ?
> > You can try to run `./apollo.sh clean --expunge` to remove any {bazel_output,coredump,log} files.
> 
> Thanks for your reply.!
> 
> when i run the command -- bash apollo.sh build. The space under / directory is used. Then i find the biggest directory is -- /.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo# . The size is 17G. Details is below. I thought this is the reason for the error.
> 
> root@zwu-Lenovo-Legion-R7000-2020:~/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo# ls apollo_docker.sh CPPLINT.cfg MANIFESTO.md tools apollo.doxygen cyber modules ubuntu_18.04_env apollo.sh data README.md WORKSPACE bazel-out docker readthedocs.yml WORKSPACE.in _bin docs RELEASE.md BUILD external scripts CONTRIBUTING.md LICENSE third_party root@zwu-Lenovo-Legion-R7000-2020:~/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo# du -sh
> 17G .
> 
> And a new problem. I restart my computer tomorrow and want to skip the command -- bash docker/scripts/dev_into.sh. Yesterday the error is no space left on device, now it returns -- Error: No such container: apollo_dev_root .
> 
> Two problems!! Thanks for your help again.

Just run `bash docker/scripts/dev_start.sh` before `bash docker/scripts/dev_into.sh`

**Comment by wzkwzk123** [comment]
I solve this problem through the docker's directory to bigger space. Before the directory for docker is /home/docker, i change it to /usr/docker. i will close this problem
