### ISSUE TITLE
libmsf_localization_component.so is missing

### ISSUE THREAD

**Issue by mendep** [ApolloAuto/apollo#12365]
Hi, I'm working on NVIDIA Jetson TX2 (ARM architecture) and **libmsf_localization_component.so** is missing. I know that it is proprietary but can it be found somewhere or maybe you can send it to me.

Thanks in advance.

**Comment by storypku** [comment]
As can been seen here, localization on non-x86 systems didn't get compiled.

**Comment by mendep** [comment]
But even if MSF is not the type of localization that is used, in the **nohup.out** file the error about **libmsf_localization_component.so** missing is showing and localization doesn't work.

**Comment by jinghaomiao** [comment]
@mendep MSF core algorithm (aka libmsf) is not tested on non-x86 system. We'll do further testing and make sure it works on Aarch64 or other architectures and let you know. This issue is being closed. Please feel free to raise new issues if you have any. Thanks for using Apollo.
