### ISSUE TITLE
Why is not there convert directory in velodyne directory?

### ISSUE THREAD

**Issue by kdheejb7** [ApolloAuto/apollo#12361]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: git clone
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: pre6 branch
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hi, I'm a user of Apollo pre6.

I'm wondering why the '/convert' directory is not in velodyne directory.
Regarding readme in velodyne directory, convert directory is used for cloud point generation.
However, there is no convert directory.
What is the reason? Then, where is the point cloud generation?

Thank you.

**Comment by lfcarol** [comment]
@kdheejb7   Hi! As far as I know the '/convert' don't represent directory, you can think of as 'VelodyneConvertComponent'.  The class VelodyneConvertComponent generates point cloud message and publish the '/apollo/sensor/lidarXXX/PointCloud2' topic message to downstream modules.

**Comment by kdheejb7** [comment]
Thank you for replying!
