### ISSUE TITLE
build apollo 5.5 failed due to lack of miniflann.hpp

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#12376]
I'm build apollo 5.5 on arm platform. Faced a build error:
![image](https://user-images.githubusercontent.com/4536559/92195424-8f52cb00-ee9f-11ea-92dc-c24528dc7f19.png)
I've installed libflann and opencv-flann. How to resolve this problem?

**Comment by storypku** [comment]
AArch64 support was only limited to CyberRT part on the `r5.5.0` branch.

**Comment by oska874** [comment]
But why lack of miniflann.hpp, there's no relationship between arm and x86 in opencv libraries?

**Comment by storypku** [comment]
> But why lack of miniflann.hpp, there's no relationship between arm and x86 in opencv libraries?

Can you please describe how to reproduce the issue? The commands you used for the build.

**Comment by oska874** [comment]
> > But why lack of miniflann.hpp, there's no relationship between arm and x86 in opencv libraries?
> 
> Can you please describe how to reproduce the issue? The commands you used for the build.

Command is `./apollo.sh build_opt_gpu`
And fixed with install `libopencv-dev`.
