### ISSUE TITLE
Planning Module Configurations Apollo 5.0

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#12373]
Hello,

In [planning/conf/Scenario](https://github.com/ApolloAuto/apollo/tree/r5.0.0/modules/planning/conf/scenario), for example inside
[bare_intersection_unprotected_config.pb.txt](https://github.com/ApolloAuto/apollo/blob/r5.0.0/modules/planning/conf/scenario/bare_intersection_unprotected_config.pb.txt)
In the beginning, I see the configuration values defined as 
.................................................................................................................
scenario_type: BARE_INTERSECTION_UNPROTECTED
bare_intersection_unprotected_config: {
  start_bare_intersection_scenario_distance: 25.0
  enable_explicit_stop: false
  min_pass_s_distance: 3.0
  approach_speed_limit: 6.7056  # 15 mph
  stop_distance: 0.5
  stop_timeout_sec: 8.0
  creep_timeout_sec: 10.0
}
......................................................................................................................

But my doubt here is, where are they used in the code? Can someone provide me the link of the code which uses these values?
Same doubt for all other config files inside [planning/conf/Scenario](https://github.com/ApolloAuto/apollo/tree/r5.0.0/modules/planning/conf/scenario)

**Comment by jmtao** [comment]
@ashwinsarvesh 
The path of scenario conf file is defined by gflags:
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/planning_gflags.h#L27

all the scenario conf files are assigned to scenario for loading during scenario registration method: https://github.com/ApolloAuto/apollo/blob/master/modules/planning/scenarios/scenario_manager.cc#L134

for this particular scenario conf, please see: https://github.com/ApolloAuto/apollo/blob/master/modules/planning/scenarios/bare_intersection/unprotected/bare_intersection_unprotected_scenario.cc#L46

**Comment by ashwinsarvesh** [comment]
Thank you
