### ISSUE TITLE
Can traffic light information be processed in navigation mode？

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#12387]
In navigation module, I saw we get traffic light information in flowing code:
traffic_light_overlaps =  reference_line_info->reference_line().map_path().signal_overlaps();

My question is how can we get the traffic light information from reference line? Does this mean when we try to record the navigation line,just pass traffic light,and then make the navigation line,this line contains traffic light information?
or just code write here, actually we can't get  traffic light information from navigation line?

Thank you so much for reading

**Comment by jinghaomiao** [comment]
@ManXiaoMi you obtain traffic light info through numerating traffic_light_overlaps.

**Comment by jinghaomiao** [comment]
Closing this ticket now. Should you have more questions, please feel free to raise new issues. Thanks for using Apollo.

**Comment by ManXiaoMi** [comment]
where this value "traffic_light_overlaps" come from?
