### ISSUE TITLE
Docker pull image has issue

### ISSUE THREAD

**Issue by yipinp** [ApolloAuto/apollo#124]
The pull command always failed with these log even with the http proxy setting. But the latter build command can be successful. But run the hmi.sh, many python packages are missing like glog, google-apputils and so on.

cb56c90f0b30: Pulling fs layer 
0acc551e5716: Pulling fs layer 
8956dcd35143: Pulling fs layer 
908242721214: Waiting 
b44ff14dd3bb: Waiting 
68a565a88d05: Waiting 
84198a14886c: Pulling fs layer 
d4b61997bf6f: Pulling fs layer 
fad90c9e6967: Pulling fs layer 
c3a71b8081c8: Pulling fs layer 
1b6b7f5fd058: Pulling fs layer 
59564810fdd3: Pulling fs layer 
c3cf6685d4cd: Pulling fs layer 
8ce4073e8bb7: Pulling fs layer 
fb888a093cc0: Pulling fs layer 
6bc8b4e3c140: Pull complete 
7b7fe4477995: Pull complete 
89a17d68e3e2: Pull complete 
e274af5eb115: Pull complete 
cd580452c88c: Pull complete 
f5499142713f: Pull complete 
08ef9610a2f5: Pull complete 
46e28973d034: Pull complete 
276ce7aafce3: Pull complete 
b9a2230796d7: Pull complete 
d125bdde2f39: Pull complete 
598a4b6f9275: Pull complete 
29c4a1ccdc5b: Pull complete 
1022ce674994: Pull complete 
aa9329b7dd1e: Pull complete 
0a464d8cb669: Pull complete 
587566f9fa9a: Pull complete 
57d7ecae556d: Pull complete 
ec7992419a91: Pull complete 
65a09c54e731: Pull complete 
e2f3689560f1: Pull complete 
419b3e44ef6d: Pull complete 
505679240dc6: Pull complete 
Digest: sha256:09aeb7850578a877fdb855bfe7319c857289faa1f68df3eede1a548a09783d09
Status: Downloaded newer image for apolloauto/apollo:dev-20170707_1129
Error response from daemon: No such container: apollo_dev
Error response from daemon: No such container: apollo_dev

**Comment by yipinp** [comment]
After install the missing package based on the hmi.out log, the GUI finally shows :
![2017-07-11 07-51-13](https://user-images.githubusercontent.com/17582532/28045126-e69e5bd6-660d-11e7-99bc-c1eabd17be94.png)

**Comment by gengqx** [comment]
May be You can run this bash for twice and using VPN.I solve this problem by this way 
```
bash docker/scripts/dev_start.sh
```
