### ISSUE TITLE
How to send the accurate routing destination point , instead of selecting a point on the map?

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#12411]
I need my car to route to the same destination in every test circle, but currently, I have to manually select the destination point on the map and it's not accurate.

So, How to send the precise routing destination point such as (X0, Y0) or (longitude, latitude); instead of selecting a point on the map?

do we have some scripts or modify some code or the interface to send the precise routing destination point?

**Comment by ntutangyun** [comment]
Apollo's dreamview website connects to its backend via a WebSocket. 
And it is through this WebSocket that the destination is sent to the backend. 

Below is something you could try:
* Connect to the WebSocket endpoint via your script, and mimic the request from Dreamview where you manually submit the destination. 
* The routing module subscribes to the routing request message. You could create a custom Apollo CyberRT component, using either Python API or C++, to publish message to this routing request channel.

**Comment by alexiskovi** [comment]
@WentaoWang-SH, sending routing request with Python API is quite easy. You can see how to do it [here](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41). By the way, you can add more destination points, not only start and stop.

**Comment by SeasoulChris** [comment]
you can also try to edit default_end_way_point.txt  in modules/map/data/xxx   then through **Default Routing** button  in dreamview to send the destination point

**Comment by XinrRunChao** [comment]
@WentaoWang-SH Hello, can I ask you a question, how do you achieve navigate " in every test circle"? I record a loop cricle map, but I can't navigate through the end point to the start point, for example, navigate from A to B...I really need your help, Thank you!! 
![Screenshot from 2020-09-09 17-12-16](https://user-images.githubusercontent.com/35392119/92669662-c532fc00-f344-11ea-9bc0-6d0c17fc2ab7.png)

**Comment by WentaoWang-SH** [comment]
> @WentaoWang-SH, sending routing request with Python API is quite easy. You can see how to do it [here](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41). By the way, you can add more destination points, not only start and stop.

Thank you very much!

**Comment by WentaoWang-SH** [comment]
> you can also try to edit default_end_way_point.txt in modules/map/data/xxx then through **Default Routing** button in dreamview to send the destination point

Thank you very much!

**Comment by MaisJamal** [comment]
I have made a package inside Apollo container, including the python script in [here](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41) and a build file .
but when I run the script using: bazel run and it has to launch one of the modules, I'm getting the following error and it's not launching any module, can you please help me to solve this issue?
[cyber_launch_68689] ERROR Subprocess Popen exception: [Errno 2] No such file or directory: 'mainboard': 'mainboard'
[cyber_launch_68689] ERROR Start manager [localization] failed. Stop all!

**Comment by ForresterLu** [comment]
> @WentaoWang-SH, sending routing request with Python API is quite easy. You can see how to do it [here](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41). By the way, you can add more destination points, not only start and stop.

Which version of Apollo are you running? I cannot find routing_pb2 in `modules.routing.proto.routing_pb2`
![module](https://user-images.githubusercontent.com/26716009/100241591-d1efe500-2f6e-11eb-8e77-5896b2f66a74.png)

**Comment by HUI11126** [comment]
> I have made a package inside Apollo container, including the python script in [here](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41) and a build file .
> but when I run the script using: bazel run and it has to launch one of the modules, I'm getting the following error and it's not launching any module, can you please help me to solve this issue?
> [cyber_launch_68689] ERROR Subprocess Popen exception: [Errno 2] No such file or directory: 'mainboard': 'mainboard'
> [cyber_launch_68689] ERROR Start manager [localization] failed. Stop all!

Hi, I encountered the same issue. Did you solved it?

**Comment by ssbse2021** [comment]
> > I have made a package inside Apollo container, including the python script in [here](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41) and a build file .
> > but when I run the script using: bazel run and it has to launch one of the modules, I'm getting the following error and it's not launching any module, can you please help me to solve this issue?
> > [cyber_launch_68689] ERROR Subprocess Popen exception: [Errno 2] No such file or directory: 'mainboard': 'mainboard'
> > [cyber_launch_68689] ERROR Start manager [localization] failed. Stop all!
> 
> Hi, I encountered the same issue. Did you solved it?

Yes, you can refer the [python example](https://github.com/alexiskovi/apollo-tools/blob/27793050b3365377f3d72e461092644f5feee29a/apollo-tools.py#L41)  to solve the problem.
