### ISSUE TITLE
which GPU support is required? GeForce GTX 1660 Ti is compatible? 

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#12418]
![Screenshot from 2020-09-06 19-31-21](https://user-images.githubusercontent.com/61130487/92377250-7283f500-f136-11ea-8a84-b56fa509638b.png)

Does any one know about this issue?

**Comment by storypku** [comment]
Since it seems that you are not on the `master` branch, please provide additional information like Apollo branch used, docker image as indicated by `echo "${DOCKER_IMG}"` and `nvidia-smi` output if available.

**Comment by Addi2020** [comment]
Thank you for your response. @storypku 
apollo5.5
ubantu 18.04
 docker image =apolloauto/apollo:dev-18.04-x86_64-20200507_0633

![Screenshot from 2020-09-08 09-34-01](https://user-images.githubusercontent.com/61130487/92424274-7fe0c400-f1b6-11ea-89df-a48e8c3cc9d6.png)

**Comment by storypku** [comment]
> Thank you for your response. @storypku
> apollo5.5
> ubantu 18.04
> docker image =apolloauto/apollo:dev-18.04-x86_64-20200507_0633
> 
> ![Screenshot from 2020-09-08 09-34-01](https://user-images.githubusercontent.com/61130487/92424274-7fe0c400-f1b6-11ea-89df-a48e8c3cc9d6.png)

It seems that GTX 1660 Ti was a recent  NVIDIA GPU card.  I checked out the latest r5.5.0 branch, and `bash ./apollo.sh build_opt_gpu` runs successfully.

As such, I would suggest you pull the latest `r5.5.0` branch, `dev_start.sh/dev_into.sh` and rerun `./apollo.sh build_opt_gpu` again to see if the problem persists.

**Comment by Addi2020** [comment]
thank you the problem is solved by reinstalling Nvidia drivers.
