### ISSUE TITLE
perception module can't use when appo connect to lgsvl

### ISSUE THREAD

**Issue by zhang-yaowen** [ApolloAuto/apollo#12429]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 16.04)**:
- **Apollo version (pre6)**:

I use two computers，one is used to operate lgsvl in windows，another is used to operate apollo.
But I found perception module doesn't work，I use order “cyber_launch start modules/perception/production/launch/perception.launch” .

the reported error is as follow：

[cyber_launch_3539] INFO Launch file [/apollo/modules/perception/production/launch/perception.launch]
[cyber_launch_3539] INFO ========================================================================================================================
[cyber_launch_3539] INFO Load module [perception] library: [lidar_perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception.dag] exception_handler: []
[cyber_launch_3539] INFO Start process [lidar_perception] successfully. pid: 3540
[cyber_launch_3539] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_3539] INFO Load module [perception_camera] library: [camera_perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: []
[cyber_launch_3539] INFO Start process [camera_perception] successfully. pid: 3542
[cyber_launch_3539] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_3539] INFO Load module [motion_service] library: [motion_service] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_motion_service.dag] exception_handler: []
[cyber_launch_3539] INFO Start process [motion_service] successfully. pid: 3544
[cyber_launch_3539] INFO ------------------------------------------------------------------------------------------------------------------------
[lidar_perception]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[lidar_perception]  I0908 15:34:36.657429  3540 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag -p lidar_perception -s CYBER_DEFAULT 
[lidar_perception]  I0908 15:34:36.658735  3540 global_data.cc:155] []host ip: 192.168.0.14
[lidar_perception]  I0908 15:34:36.659664  3540 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is lidar_perception, has 1 dag conf
[lidar_perception]  I0908 15:34:36.659821  3540 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception.dag
[motion_service]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[motion_service]  I0908 15:34:36.665870  3544 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion_service -s CYBER_DEFAULT 
[motion_service]  I0908 15:34:36.667338  3544 global_data.cc:155] []host ip: 192.168.0.14
[motion_service]  I0908 15:34:36.668449  3544 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is motion_service, has 1 dag conf
[motion_service]  I0908 15:34:36.668846  3544 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_motion_service.dag
[camera_perception]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[camera_perception]  I0908 15:34:36.718509  3542 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p camera_perception -s CYBER_DEFAULT 
[camera_perception]  I0908 15:34:36.719498  3542 global_data.cc:155] []host ip: 192.168.0.14
[camera_perception]  I0908 15:34:36.720176  3542 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is camera_perception, has 1 dag conf
[camera_perception]  I0908 15:34:36.720362  3542 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
[camera_perception]  E0908 15:34:36.941433  3542 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libcuda.so.1: cannot open shared object file: No such file or directory
[camera_perception]  E0908 15:34:36.941685  3542 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
[camera_perception]  E0908 15:34:36.941813  3542 class_loader_manager.h:70] [mainboard]Invalid class name: FusionCameraDetectionComponent
[camera_perception]  E0908 15:34:36.941905  3542 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
[camera_perception]  E0908 15:34:36.941987  3542 class_loader_utility.cc:258] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so
[camera_perception]  E0908 15:34:36.942075  3542 mainboard.cc:39] [mainboard]module start error.
[motion_service]  E0908 15:34:37.005131  3544 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libcuda.so.1: cannot open shared object file: No such file or directory
[motion_service]  E0908 15:34:37.005193  3544 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/perception/camera/lib/motion_service/libmotion_service.so
[motion_service]  E0908 15:34:37.005228  3544 class_loader_manager.h:70] [mainboard]Invalid class name: MotionService
[motion_service]  E0908 15:34:37.005249  3544 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_motion_service.dag
[motion_service]  E0908 15:34:37.005259  3544 class_loader_utility.cc:258] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/perception/camera/lib/motion_service/libmotion_service.so
[motion_service]  E0908 15:34:37.005267  3544 mainboard.cc:39] [mainboard]module start error.
[lidar_perception]  E0908 15:34:37.028728  3540 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libcuda.so.1: cannot open shared object file: No such file or directory
[lidar_perception]  E0908 15:34:37.029541  3540 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so
[lidar_perception]  E0908 15:34:37.029664  3540 class_loader_manager.h:70] [mainboard]Invalid class name: SegmentationComponent
[lidar_perception]  E0908 15:34:37.029711  3540 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception.dag
[lidar_perception]  E0908 15:34:37.029779  3540 class_loader_utility.cc:258] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_lidar.so
[lidar_perception]  E0908 15:34:37.029790  3540 mainboard.cc:39] [mainboard]module start error.
[camera_perception]  
[motion_service]  
[lidar_perception]  
[cyber_launch_3539] ERROR Process [lidar_perception] has finished. [pid 3540, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag -p lidar_perception -s CYBER_DEFAULT].
[cyber_launch_3539] ERROR Process [camera_perception] has finished. [pid 3542, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p camera_perception -s CYBER_DEFAULT].
[cyber_launch_3539] ERROR Process [motion_service] has finished. [pid 3544, cmd mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion_service -s CYBER_DEFAULT].
[cyber_launch_3539] INFO All processes has died.
[cyber_launch_3539] INFO Cyber exit.
[cyber_launch_3539] INFO All processes have been stopped.

**Comment by jeroldchen** [comment]
@zhang-yaowen 

> [camera_perception] E0908 15:34:36.941433 3542 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libcuda.so.1: cannot open shared object file: No such file or directory
[camera_perception] E0908 15:34:36.941685 3542 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so

Seems like you failed building Apollo. Try to run `./apollo.sh build_opt_gpu` again. Look forward to your feedback. Thank you.

**Comment by jinghaomiao** [comment]
@zhang-yaowen hope your question is answered. This issue is being closed. Please raise new issues if you have any. Thanks for using Apollo.
