### ISSUE TITLE
apollo5.5 master localization module cannot start , Reflectance map folder is invalid!

### ISSUE THREAD

**Issue by devynliu** [ApolloAuto/apollo#12435]
hello ,recengtly i run apollo  master with lgsvl,i meet a issue.
- OS Ubuntu 18.04
the log show:
Log file created at: 2020/09/08 17:16:33
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0908 17:16:33.411268 19370 scheduler_factory.cc:63] No sched conf found, use default conf.
I0908 17:16:33.411329 19372 processor.cc:41] processor_tid: 19372
I0908 17:16:33.411370 19373 processor.cc:41] processor_tid: 19373
I0908 17:16:33.411402 19374 processor.cc:41] processor_tid: 19374
I0908 17:16:33.411434 19375 processor.cc:41] processor_tid: 19375
I0908 17:16:33.411473 19376 processor.cc:41] processor_tid: 19376
I0908 17:16:33.411506 19377 processor.cc:41] processor_tid: 19377
I0908 17:16:33.411538 19378 processor.cc:41] processor_tid: 19378
I0908 17:16:33.411566 19379 processor.cc:41] processor_tid: 19379
I0908 17:16:33.411936 19380 processor.cc:41] processor_tid: 19380
I0908 17:16:33.411965 19381 processor.cc:41] processor_tid: 19381
I0908 17:16:33.415937 19382 processor.cc:41] processor_tid: 19382
I0908 17:16:33.415987 19383 processor.cc:41] processor_tid: 19383
I0908 17:16:33.416021 19384 processor.cc:41] processor_tid: 19384
I0908 17:16:33.416051 19385 processor.cc:41] processor_tid: 19385
I0908 17:16:33.416079 19386 processor.cc:41] processor_tid: 19386
I0908 17:16:33.416105 19387 processor.cc:41] processor_tid: 19387
I0908 17:16:33.416111 19370 init.cc:112] Register exit handle succ.
I0908 17:16:33.416699 19370 module_controller.cc:65] Start initialize dag: /apollo/modules/localization/dag/dag_streaming_rtk_localization.dag
I0908 17:16:33.416745 19370 class_loader.cc:37] Begin LoadLibrary: /apollo/bazel-bin/modules/localization/msf/libmsf_localization_component.so
I0908 17:16:33.510835 19370 localization_lidar.cc:61] map_path: /apollo/modules/map/data/san_francisco/local_map
I0908 17:16:33.510848 19370 base_map.cc:115] config_path: /apollo/modules/map/data/san_francisco/local_map/config.xml
F0908 17:16:33.510861 19370 localization_lidar.cc:63] Reflectance map folder is invalid!
how can i slove this?

**Comment by MaisJamal** [comment]
I have the same issue. have you find any solution?

**Comment by devynliu** [comment]
I removed all images and source code. Then I again git code and pull images. It never occurred. Hope this for your help.

**Comment by mengen100** [comment]
> I removed all images and source code. Then I again git code and pull images. It never occurred. Hope this for your help.

This is happening to me the 3rd time, the first 2 times I did this.. Just tired of deleting and redoing everything again, anyone knows the root cause?

**Comment by daohu527** [comment]
this cause by load the run so library. use rtk but load msf

**Comment by AOOOOOA** [comment]
> this cause by load the run so library. use rtk but load msf

Hi, do you have any idea of solving the problem? Thanks!
