### ISSUE TITLE
unable to find user zwu: no matching entries in passwd file.

### ISSUE THREAD

**Issue by wzkwzk123** [ApolloAuto/apollo#12438]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I want to build apollo 5.5 in ubuntu20.04. i locate at root path -- root@zwu-Lenovo-Legion-R7000-2020:/home/zwu/zwu/apollo/apollo-5.5.0# 
when i run -- bash docker/scripts/dev_start.sh, the return is:

addgroup: The group `root' already exists.
usermod: user 'zwu' does not exist
chown: invalid user: 'zwu:root'
chown: invalid user: 'zwu:root'
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
When i run -- bash docker/scripts/dev_into.sh. It returns :
unable to find user zwu: no matching entries in passwd file.

I do not know how to fix it.

**Comment by storypku** [comment]
I would suggest running `dev_start.sh/dev_into.sh` as a normal user `zwu`.

**Comment by storypku** [comment]
This issue has not reply for nearly two months and is going to be closed. Thanks for using Apollo. If you have other questions, feel free to create another issue. Or reopen this one if it persists.
