### ISSUE TITLE
There is delay between sending command and the Vehicle execute command（control module） 

### ISSUE THREAD

**Issue by ManXiaoMi** [ApolloAuto/apollo#12437]
Actually, there must be time delay between sending command and the Vehicle execute command, is there any compensation about this? 
Now, the vehicle has a big delay like following. So there is vibration about vehicle  speed.Then how to solve?
Does it need to add compensator?
![image](https://user-images.githubusercontent.com/22726277/92461033-4c745880-f1fb-11ea-8a23-31506bfae93a.png)

**Comment by ManXiaoMi** [comment]
Actually, sometime control already send throttle command to the vehicle, but the car's real speed still decrease

**Comment by Capri2014** [comment]
@ManXiaoMi May I know what is your setup environment and how did you get this plot? (On Vehicle or in Simulation). In general there are actuators latency in vehicle and by properly set the MRAC controller you should be able to largely compensate for it.

**Comment by ManXiaoMi** [comment]
Yes,I get this plot on vehicle on Wey(changcheng). Is there any compensation for MPC Controller?

**Comment by Capri2014** [comment]
> Yes,I get this plot on vehicle on Wey(changcheng). Is there any compensation for MPC Controller?

MRAC can be combined with PID, LQR or MPC, you just needs to append/combine them with existing controllers and set the right parameters for different vehicles.

**Comment by ManXiaoMi** [comment]
And I also saw MRAC controller just combine with lateral controller. now there is delay about speed and station, should we add MRAC controller on longitudinal controller？

**Comment by ManXiaoMi** [comment]
Sorry, I just saw your response. Thank you so much for your help.
