### ISSUE TITLE
error when run rtk_recorder.sh

### ISSUE THREAD

**Issue by orangejuce** [ApolloAuto/apollo#12447]
### Issue description
When i run rtk_recorder.sh try to record route, an error has occurred:  cannot import chassis_pb2
i check my apollo folder: /modules/canbus/proto, there isn't exisited a file named chassis_pb2. i wonder how can i generate chassis_pb2?

### System information
- **OS Platform: Ubuntu 18.04
- **Apollo version : 5.5
- **i start canbus, gps and localization module, then i run the following sentences:    
    ./scripts/apollo_base.sh
    ./scripts/rtk_recorder.sh setup
    ./scripts/rtk_recorder.sh start

**Comment by storypku** [comment]
Do you mean you are on the `master` branch ?

Have you run `./apollo.sh build` or `./apollo.sh build_opt_gpu` ?

**Comment by orangejuce** [comment]
I have solved this problem, the reason is the directory of my cache is not in apollo/cache, I add my cache directory in python path, then this problem is solved.

**Comment by storypku** [comment]
> I have solved this problem, the reason is the directory of my cache is not in apollo/cache, I add my cache directory in python path, then this problem is solved.

Well done.
