### ISSUE TITLE
/apollo/modules/map/data/****/default_end_way_point.txt，how does this file work?

### ISSUE THREAD

**Issue by XinrRunChao** [ApolloAuto/apollo#12448]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information
- **Apollo version (3.0)**:

### Steps to reproduce the issue:
- **As you can see the picture:
- **I want to navigate from A to B **: 
- **    The map that recorded from start to end, start at the left of red line, end at the right of red line , **
- **    But from A to B, must through the red line. **
- **    The problem is: I can navigator from A to B, because, there is a stop in the red line? **
- **    The reason is the file: default_end_way_point.txt? **
- **    Or how can I achieve this function, Thank you very much~~!!**

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2020-09-09 17-12-16](https://user-images.githubusercontent.com/35392119/92581394-3b424f00-f2c2-11ea-83fd-c4320eace450.png)

**Comment by jmtao** [comment]
@XinrRunChao 
This file is used to provide information used as pre-defined routing request. 
The proto can be found [here](https://github.com/ApolloAuto/apollo/blob/master/modules/routing/proto/poi.proto).  

Each landmark is used as one pre-defined routing request.  The waypoints inside are used as start point, passing point(s), and destination point. 

When you launch DreamView, on left hand side corner, there's a "Default Routing" button, if you click on it, DreamView will load default routing from default_end_way_point.txt of a corresponding map.  After you select a routing out of the list, a corresponding routing request will be sent to routing module who will generate a routing based on that.

**Comment by XinrRunChao** [comment]
> @XinrRunChao
> This file is used to provide information used as pre-defined routing request.
> The proto can be found [here](https://github.com/ApolloAuto/apollo/blob/master/modules/routing/proto/poi.proto).
> 
> Each landmark is used as one pre-defined routing request. The waypoints inside are used as start point, passing point(s), and destination point.
> 
> When you launch DreamView, on left hand side corner, there's a "Default Routing" button, if you click on it, DreamView will load default routing from default_end_way_point.txt of a corresponding map. After you select a routing out of the list, a corresponding routing request will be sent to routing module who will generate a routing based on that.

Thank you very much for your reply. But my finally aim is to acheive the loop circle, like [https://github.com/ApolloAuto/apollo/issues/12203](url), how can I do this? And the issue can be opened again?
