### ISSUE TITLE
Help needed: See configuration values in run time

### ISSUE THREAD

**Issue by ashwinsarvesh** [ApolloAuto/apollo#12450]
Hello,

I use Apollo 5.0 and LGSVL simulator.
I changed the configuration values in the file [traffic_rule_config.pb.txt](https://github.com/ApolloAuto/apollo/blob/r5.0.0/modules/planning/conf/traffic_rule_config.pb.txt) of the planning module.
For example, I changed the backside_lane_width from 4.0 to 3.0

How can I know in run time that the value is accepted/being used? Where can I check the current value?

**Comment by jmtao** [comment]
@ashwinsarvesh you can find the definition of the traffic_rule_config at its [proto file ](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/proto/traffic_rule_config.proto)

backside_lane_width you have modified can be found in BacksideVehicleConfig:
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/proto/traffic_rule_config.proto#L95

If you search code base, you can find it is used by: modules/planning/traffic_rules/backside_vehicle.cc

In the conf, this rule is disabled. 
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/conf/traffic_rule_config.pb.txt#L3

You'll have to enable it first, to see the impact when you modify its value.
