### ISSUE TITLE
How to get Channel messages to handle in code like string or int type.

### ISSUE THREAD

**Issue by Doozua** [ApolloAuto/apollo#12464]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Hi! I'm using Apollo 5.0 with ubuntu 16.04.

I want to print channel messages into terminal.

It means,

When I run talker and listener, I can see the data with 'cyber_monitor'

I want to get the message from the channel and print them into terminal with **'cout'** for simple test.

Please let me know how I can get it.

**Comment by jmtao** [comment]
@Doozua you can print out the message from your listener once it is received. 
Please refer to planning module: https://github.com/ApolloAuto/apollo/blob/master/modules/planning/planning_component.cc#L67
the reader to read routing_response topic received a routing_response message, and printed it to the INFO log.

**Comment by Doozua** [comment]
Thank you for answering.

I want to print with "cout". not 'INFO'

Just printing to terminal is not my main purpose.

I'd like to handle data what from channel message with variables has data type like 'string', 'char' or 'int'.

That's why I emphasize **'cout'** before.
