### ISSUE TITLE
Can Apollo3.0 route, Navigate in this juction

### ISSUE THREAD

**Issue by XinrRunChao** [ApolloAuto/apollo#12473]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **Apollo version (3.0)**:

### Steps to reproduce the issue:
- I want to know whether the Apollo3.0 can route and navigate from A to B through the juction?? I try it, but it failed, I don't know there are any problems...
![微信图片_20200910200012](https://user-images.githubusercontent.com/35392119/92726700-921e5600-f3a0-11ea-8a86-5e85524f120a.jpg)

**Comment by jmtao** [comment]
@XinrRunChao planning module doesn't support circular routing with 3.0.

**Comment by XinrRunChao** [comment]
> @XinrRunChao planning module doesn't support circular routing with 3.0.

Thank you for your reply. Can I think of the intersection as one juction? The apollo3.0 also doesn't support the juction routing?

**Comment by jmtao** [comment]
@XinrRunChao Apollo 3.0 support routing around junctions, not circular routing, which means there's a circle in the routing, something like **A**->B->C->**A**->D ...
