### ISSUE TITLE
Which proxy - os's or docker's - will be used by the scripts before entering into docker environment of apollo?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12486]
Hi,

Which proxy settings, OS's proxy or docker's, will be used by docker/scripts/dev_start.sh when downloading/pulling relevant stuff? 

More generally speaking, which proxy - os's or docker's - will be used by the scripts before entering into docker environment of apollo?

**Comment by storypku** [comment]
`dev_start.sh` didn't do any thing special for proxy settings.
Correcty me if wrong: When you set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables,  docker daemon will respect your settings.

https://docs.docker.com/engine/reference/commandline/pull/#proxy-configuration
