### ISSUE TITLE
"./docker/scripts/dev_start.sh -g cn"  will kill the docker daemon.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12485]
Hi,

Here is Ubuntu 20.04 and git master apollo. When running the following command:

`$ ./docker/scripts/dev_start.sh -g cn`

Then I meet the following window:

![image](https://user-images.githubusercontent.com/11155854/92821342-8c0a9280-f3fd-11ea-8283-aca33b8d0f31.png)

But when I input the root password, I meet the following execution results of this command:

```
$ ./docker/scripts/dev_start.sh -g cn
[INFO] GeoLocation based settings: from within China
./docker/scripts/dev_start.sh: line 166: jq: command not found
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211

```

Then I try the following:

```
$ ./docker/scripts/dev_start.sh -g us
[INFO] GeoLocation based settings for us: not ready, fallback to default
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211
$ ./docker/scripts/dev_start.sh -g auto
[INFO] GeoLocation based settings for auto: not ready, fallback to default
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211
$ ./docker/scripts/dev_start.sh 
[INFO] GeoLocation based settings: use default.
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211
```
It seems the docker daemon is killed by the first command mentioned above. 

Any hints for this problem?

Regards,
HY

**Comment by storypku** [comment]
Thank you for reporting. This is because Geo-location based setter within `dev_start.sh` used the `jq` command  to finish its task.

You can install it via `sudo apt install jq` if on Ubuntu. Or download it from https://stedolan.github.io/jq/

**Comment by hongyi-zhao** [comment]
I installed `jq` but it seems the docker daemon is dead. See following for more info:

```
$ ./docker/scripts/dev_start.sh -g cn
[INFO] GeoLocation settings for Mainland China
Existing registry mirrors in found /etc/docker/daemon.json and will be used.
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211
$ systemctl status docker.service
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-09-11 12:20:42 CST; 3min 37s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 24610 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, >
   Main PID: 24610 (code=exited, status=1/FAILURE)

Sep 11 12:20:42 X10DAi-01 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Sep 11 12:20:42 X10DAi-01 systemd[1]: Stopped Docker Application Container Engine.
Sep 11 12:20:42 X10DAi-01 systemd[1]: docker.service: Start request repeated too quickly.
Sep 11 12:20:42 X10DAi-01 systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 11 12:20:42 X10DAi-01 systemd[1]: Failed to start Docker Application Container Engine.
```

What's the reason for this problem?

Regards,
HY

**Comment by storypku** [comment]
> I installed `jq` but it seems the docker daemon is dead. See following for more info:
> 
> ```
> $ ./docker/scripts/dev_start.sh -g cn
> [INFO] GeoLocation settings for Mainland China
> Existing registry mirrors in found /etc/docker/daemon.json and will be used.
> [INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> [ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211
> 
> $ sudo systemctl restart docker
> Job for docker.service failed because the control process exited with error code.
> See "systemctl status docker.service" and "journalctl -xe" for details.
> 
> $ systemctl status docker.service
> ● docker.service - Docker Application Container Engine
>      Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Fri 2020-09-11 12:27:02 CST; 11s ago
> TriggeredBy: ● docker.socket
>        Docs: https://docs.docker.com
>     Process: 27969 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, >
>    Main PID: 27969 (code=exited, status=1/FAILURE)
> 
> Sep 11 12:27:02 X10DAi-01 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
> Sep 11 12:27:02 X10DAi-01 systemd[1]: Stopped Docker Application Container Engine.
> Sep 11 12:27:02 X10DAi-01 systemd[1]: docker.service: Start request repeated too quickly.
> Sep 11 12:27:02 X10DAi-01 systemd[1]: docker.service: Failed with result 'exit-code'.
> Sep 11 12:27:02 X10DAi-01 systemd[1]: Failed to start Docker Application Container Engine.
> 
> $ journalctl -xe
> Sep 11 12:27:07 X10DAi-01 sogouimebs-watchdog.desktop[4086]: QProcess: Destroyed while process ("kill") is still r>
> Sep 11 12:27:07 X10DAi-01 fcitx-ui-baidu-qimpanel-ln.desktop[3977]: baidu panel was already started
> Sep 11 12:27:09 X10DAi-01 sudo[28100]:   werner : TTY=pts/0 ; PWD=/home/werner/Public/anti-gfw/socks5-haproxy ; US>
> Sep 11 12:27:09 X10DAi-01 sudo[28100]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Sep 11 12:27:09 X10DAi-01 sudo[28100]: pam_unix(sudo:session): session closed for user root
> Sep 11 12:27:10 X10DAi-01 sogouimebs-watchdog.desktop[4086]: ibus-daemon:2013
> Sep 11 12:27:10 X10DAi-01 sogouimebs-watchdog.desktop[4086]: QProcess: Destroyed while process ("kill") is still r>
> Sep 11 12:27:10 X10DAi-01 fcitx-ui-baidu-qimpanel-ln.desktop[3977]: baidu panel was already started
> Sep 11 12:27:13 X10DAi-01 sogouimebs-watchdog.desktop[4086]: ibus-daemon:2013
> Sep 11 12:27:13 X10DAi-01 sogouimebs-watchdog.desktop[4086]: QProcess: Destroyed while process ("kill") is still r>
> Sep 11 12:27:13 X10DAi-01 fcitx-ui-baidu-qimpanel-ln.desktop[3977]: baidu panel was already started
> Sep 11 12:27:14 X10DAi-01 sudo[28184]:   werner : TTY=pts/0 ; PWD=/home/werner/Public/anti-gfw/socks5-haproxy ; US>
> Sep 11 12:27:14 X10DAi-01 sudo[28184]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Sep 11 12:27:15 X10DAi-01 sudo[28184]: pam_unix(sudo:session): session closed for user root
> Sep 11 12:27:16 X10DAi-01 sogouimebs-watchdog.desktop[4086]: ibus-daemon:2013
> Sep 11 12:27:16 X10DAi-01 sogouimebs-watchdog.desktop[4086]: QProcess: Destroyed while process ("kill") is still r>
> Sep 11 12:27:17 X10DAi-01 fcitx-ui-baidu-qimpanel-ln.desktop[3977]: baidu panel was already started
> Sep 11 12:27:19 X10DAi-01 sogouimebs-watchdog.desktop[4086]: ibus-daemon:2013
> Sep 11 12:27:19 X10DAi-01 sogouimebs-watchdog.desktop[4086]: QProcess: Destroyed while process ("kill") is still r>
> Sep 11 12:27:20 X10DAi-01 sudo[28223]:   werner : TTY=pts/0 ; PWD=/home/werner/Public/anti-gfw/socks5-haproxy ; US>
> Sep 11 12:27:20 X10DAi-01 sudo[28223]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Sep 11 12:27:20 X10DAi-01 sudo[28223]: pam_unix(sudo:session): session closed for user root
> Sep 11 12:27:20 X10DAi-01 fcitx-ui-baidu-qimpanel-ln.desktop[3977]: baidu panel was already started
> ```
> 
> What's the reason for this problem?
> 
> Regards,
> HY

Please paste your `/etc/docker/daemon.conf` in your reply. Back it up and remove it and try again.

**Comment by hongyi-zhao** [comment]
Strange, it doesn't exist at all: 

```
$ ls /etc/docker/daemon.conf
ls: cannot access '/etc/docker/daemon.conf': No such file or directory
```

**Comment by hongyi-zhao** [comment]
Then, I try to remove and reinstall docker, but still failed, see the following for more info:

```
$ sudo apt-get remove --purge docker-ce docker-ce-cli containerd.io
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  containerd.io docker-ce docker-ce-cli
0 upgraded, 3 newly installed, 0 to remove and 194 not upgraded.
Need to get 0 B/85.2 MB of archives.
After this operation, 381 MB of additional disk space will be used.
Selecting previously unselected package containerd.io.
(Reading database ... 313501 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.2.13-2_amd64.deb ...
Unpacking containerd.io (1.2.13-2) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a19.03.12~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce-cli (5:19.03.12~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a19.03.12~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
Setting up containerd.io (1.2.13-2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up docker-ce-cli (5:19.03.12~3-0~ubuntu-focal) ...
Setting up docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-09-12 09:01:08 CST; 10ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 63636 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 63636 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)



```

**Comment by storypku** [comment]
> Then, I try to remove and reinstall docker, but still failed, see the following for more info:
> 
> ```
> $ egrep '^deb .* https://download.docker.com/linux/ubuntu' /etc/apt/sources.list
> deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
> 
> $ sudo apt-get remove -y --purge docker docker.io containerd runc
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package 'containerd' is not installed, so not removed
> Package 'runc' is not installed, so not removed
> Package 'docker' is not installed, so not removed
> Package 'docker.io' is not installed, so not removed
> 0 upgraded, 0 newly installed, 0 to remove and 194 not upgraded.
> 1 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Setting up docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
> Job for docker.service failed because the control process exited with error code.
> See "systemctl status docker.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript docker, action "start" failed.
> ● docker.service - Docker Application Container Engine
>      Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Sat 2020-09-12 09:11:40 CST; 9ms ago
> TriggeredBy: ● docker.socket
>        Docs: https://docs.docker.com
>     Process: 71892 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
>    Main PID: 71892 (code=exited, status=1/FAILURE)
> dpkg: error processing package docker-ce (--configure):
>  installed docker-ce package post-installation script subprocess returned error exit status 1
> Errors were encountered while processing:
>  docker-ce
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 
> $ sudo apt-get install -y docker-ce docker-ce-cli containerd.io
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   containerd.io docker-ce docker-ce-cli
> 0 upgraded, 3 newly installed, 0 to remove and 194 not upgraded.
> Need to get 0 B/85.2 MB of archives.
> After this operation, 381 MB of additional disk space will be used.
> Selecting previously unselected package containerd.io.
> (Reading database ... 313501 files and directories currently installed.)
> Preparing to unpack .../containerd.io_1.2.13-2_amd64.deb ...
> Unpacking containerd.io (1.2.13-2) ...
> Selecting previously unselected package docker-ce-cli.
> Preparing to unpack .../docker-ce-cli_5%3a19.03.12~3-0~ubuntu-focal_amd64.deb ...
> Unpacking docker-ce-cli (5:19.03.12~3-0~ubuntu-focal) ...
> Selecting previously unselected package docker-ce.
> Preparing to unpack .../docker-ce_5%3a19.03.12~3-0~ubuntu-focal_amd64.deb ...
> Unpacking docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
> Setting up containerd.io (1.2.13-2) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
> Setting up docker-ce-cli (5:19.03.12~3-0~ubuntu-focal) ...
> Setting up docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
> Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
> Job for docker.service failed because the control process exited with error code.
> See "systemctl status docker.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript docker, action "start" failed.
> ● docker.service - Docker Application Container Engine
>      Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Sat 2020-09-12 09:01:08 CST; 10ms ago
> TriggeredBy: ● docker.socket
>        Docs: https://docs.docker.com
>     Process: 63636 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
>    Main PID: 63636 (code=exited, status=1/FAILURE)
> dpkg: error processing package docker-ce (--configure):
>  installed docker-ce package post-installation script subprocess returned error exit status 1
> Processing triggers for man-db (2.9.1-1) ...
> Processing triggers for systemd (245.4-4ubuntu3.2) ...
> Errors were encountered while processing:
>  docker-ce
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Trying the following commands

```
sudo systemctl stop docker
sudo apt-get -f install
```

**Comment by hongyi-zhao** [comment]
```
werner@X10DAi-01:~$ sudo systemctl stop docker
werner@X10DAi-01:~$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 194 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-09-12 20:47:09 CST; 10ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 29073 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 29073 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by storypku** [comment]
> ```
> werner@X10DAi-01:~$ sudo systemctl stop docker
> werner@X10DAi-01:~$ sudo apt-get -f install
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 0 upgraded, 0 newly installed, 0 to remove and 194 not upgraded.
> 1 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Setting up docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
> Job for docker.service failed because the control process exited with error code.
> See "systemctl status docker.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript docker, action "start" failed.
> ● docker.service - Docker Application Container Engine
>      Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Sat 2020-09-12 20:47:09 CST; 10ms ago
> TriggeredBy: ● docker.socket
>        Docs: https://docs.docker.com
>     Process: 29073 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
>    Main PID: 29073 (code=exited, status=1/FAILURE)
> dpkg: error processing package docker-ce (--configure):
>  installed docker-ce package post-installation script subprocess returned error exit status 1
> Errors were encountered while processing:
>  docker-ce
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Er, it seems a Docker problem. Have you tried removing Docker related packages and reinstall them ?

**Comment by hongyi-zhao** [comment]
> Er, it seems a Docker problem. Have you tried removing Docker related packages and reinstall them ?

I have tried this method, but can't solve the problem.

BTW, this problem is observed after I run this command: `./docker/scripts/dev_start.sh -g cn`, so I suspect that this script may do some damage operations on the system's configuration.

**Comment by hongyi-zhao** [comment]
Sigh. I finally reinstalled the OS for solving this problem.
