### ISSUE TITLE
Why the apollo 3.0 can not routing through the junction? 

### ISSUE THREAD

**Issue by XinrunChao** [ApolloAuto/apollo#12492]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information
- **Apollo version (3.0)**:

### Steps to reproduce the issue:
- The record map is as followed, I want to routing from A to B, but it failed. The reason is also followed. 
### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2020-09-11 10-46-05](https://user-images.githubusercontent.com/35392119/92853791-d6523a80-f422-11ea-8795-a7725008ebeb.png)
![Screenshot from 2020-09-11 11-28-45](https://user-images.githubusercontent.com/35392119/92853798-d81bfe00-f422-11ea-9797-09986918ab25.png)

**Comment by SeasoulChris** [comment]
I think the map you are using is virtual lane, not HD map,  junction information not contained in your virtual lane file

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
