### ISSUE TITLE
Module monitor is already running - skipping.

### ISSUE THREAD

**Issue by wzkwzk123** [ApolloAuto/apollo#12490]
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
Module monitor is already running - skipping.

I have built the project. When i use bash scripts/bootstrap.sh at the first time, everything seems good. I can see the GUI at Localhost:8888. But, when i kill all docker container , use dev_start.sh ad dev_into.sh command to enter the apollo enviroment and  
use bash scripts/bootstrap.sh, it returns -- Module monitor is already running - skipping.. Localhost:8888 can not open, i have tried firefox and google.

Thanks for help

**Comment by changsh726** [comment]
I tried it on the master head according to your steps, but failed to reproduce what you said.
You can try `bash scripts/bootstrap.sh stop` and then `bash scripts/bootstrap.sh`. Hope this helps.
Thx.
