### ISSUE TITLE
Again this problem appear: dial unix /var/run/docker.sock: connect: permission denied

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12509]
Hi,

This problem has been discussed [here](https://github.com/ApolloAuto/apollo/issues/12257#issuecomment-682305336), but it appeared once more. See following for more info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

$ stat -c "%a" /var/run/docker.sock
660

$ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

$ git log | head -6
commit 15c77cbed9d9f60dde5dc1dd0c8cd04eb6f31a51
Author: storypku <storypku@gmail.com>
Date:   Sat Sep 12 11:03:21 2020 +0800

    map: imported proto unused fix

$ ./docker/scripts/dev_start.sh 
[INFO] Use default GeoLocation settings
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-18.04-20200908_0211 ...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=apolloauto%2Fapollo&tag=dev-x86_64-18.04-20200908_0211: dial unix /var/run/docker.sock: connect: permission denied
[ERROR] Failed to pull docker image : apolloauto/apollo:dev-x86_64-18.04-20200908_0211

```

OTOH, if I run the following command, the problem will be solved:
`
$ sudo chmod 777 /var/run/docker.sock`

Regards,
HY

**Comment by storypku** [comment]
I think the main issue is that you have not setup Docker correctly.
Please follow the instructions https://github.com/ApolloAuto/apollo/blob/master/docs/specs/prerequisite_software_installation_guide.md#installing-docker-engine

for how to install and configure docker.

**Comment by hongyi-zhao** [comment]
For docker installation, I strictly based on the instructions [here](https://docs.docker.com/engine/install/ubuntu/).

**Comment by storypku** [comment]
> I don't think so, since for docker installation, I strictly based on the instructions [here](https://docs.docker.com/engine/install/ubuntu/).

You haven't followed the post-install steps as described here: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user , which was required by https://github.com/ApolloAuto/apollo/blob/master/docs/specs/prerequisite_software_installation_guide.md#installing-docker-engine .

**Comment by hongyi-zhao** [comment]
Thanks a lot. Really you're right. It does the trick.
