### ISSUE TITLE
I can't receive camera perception results for the Fusion.

### ISSUE THREAD

**Issue by laukalfp** [ApolloAuto/apollo#12503]
I want to use camera perception results with the lidar perception results in the fusion_component.cc in apollo5.5.
I had checked the fusion_camera_detection_component.cc had send the topic which type is SensorFrameMessage, but i can't receive them for fusion. the fusion module only receive the topic from lidar perception (recognition_component.cc) .
Then  I write a fusion_componenttest component and a node to send the SensorFrameMessage topic, the component can't receive, Evan i use the lidar perception topic , it still can't receive .

Can you tell me, how to use the inner topic well ? whether there have some skills ?

Ps: 我想用相机的感知结果与激光的结果进行融合，我发现融合模块只收到激光的感知结果，没有相机的。
然后我从新写了一个专门测试接受SensorFrameMessage的构件，然后自己给它发topic，接受不到，用激光
感知的给它发也接收不到。

这个要怎么玩才是正确的打开方式啊？如何能让fusion模块接受到相机的感知结果？
按理说你们都能发布出来，这个应该是可以的才对啊！

英文大家都看的懂，中文好理解。

**Comment by jinghaomiao** [comment]
@laukalfp Camera based obstracle detection is being refactored. The new change will be available to the public once it's ready. Please stay turned. This issue is being closed. Please raise new issues if needed. Thanks for using Apollo.
