### ISSUE TITLE
The init of traffic rules.

### ISSUE THREAD

**Issue by YaoQii** [ApolloAuto/apollo#12517]
Hello,
I suggest that the traffic rules in [traffic_decider.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/traffic_rules/traffic_decider.cc) can be inited only once, and the traffic_rule_configs_ will not change at all.

**Comment by YaoQii** [comment]
The init code in [on_lane_planning.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/on_lane_planning.cc) is as below:
```
 for (auto& ref_line_info : *frame_->mutable_reference_line_info()) {
    TrafficDecider traffic_decider;
    traffic_decider.Init(traffic_rule_configs_);
    auto traffic_status =
        traffic_decider.Execute(frame_.get(), &ref_line_info, injector_);
    if (!traffic_status.ok() || !ref_line_info.IsDrivable()) {
      ref_line_info.SetDrivable(false);
      AWARN << "Reference line " << ref_line_info.Lanes().Id()
            << " traffic decider failed";
    }
  }
```
So, why not only init TrafficDecider once in class's init?
Thanks for your answer.

**Comment by jmtao** [comment]
@YaoQii it's doable. but with the current implementation, (1) traffic_decider is released out of the for-loop, much cleaner? (2) can be changed to implement concurrently later?   anyway, either way is fine. no significant difference to me.
