### ISSUE TITLE
How to convert Apollo HDMap to base_map.txt/base_map.bin/base_map.xml

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#12523]
Hello apollo Team!
1 Is the base_map.bin read by the current planning algorithm generated by Apollo HDMap (xx.xml)? If it‘s the true，How can I convert Apollo HDMap(xxx.xml) to base_map.txt/base_map.bin/base_map.xml?

2 Is there any way to convert Asam Opendrive（xodr） to Apollo Opendrive（.xml）or Apollo Opendrive(.xml)  to Asam Opendrive（xodr） ?

Thanks!

**Comment by jinghaomiao** [comment]
1) Base map in binary follows the proto definitions of HDMap. You could use proto to load the file and dump it out with plain text format. XML is in opendrive format with some changes. Apollo does not provide tools to convert from proto definitions to opendrive format.
2) We don't support ASAM opendrive (.xdr) format.

Hope your questions are answered. I am closing this issue. Please feel free to raise other issues if needed. Thanks for using Apollo.
