### ISSUE TITLE
Still can't find the apollo 6.0 release here.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12549]
Intelligent of Everything-Baidu World 2020 told that today - Sep 15, 2020 - apollo 6.0 has been released out, but I still can't find the corresponding release appeared on github.

Any hints?

Regards,
HY

**Comment by ntutangyun** [comment]
It will be released on 23rd.

**Comment by jinghaomiao** [comment]
Thanks for using Apollo. Please stay tuned for the release of Apollo 6.0 on 23rd of Sept.
