### ISSUE TITLE
why so many BUILD_ files but noe BUILD files

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#12548]
and cant compile success.
Are all these dirs will be removed?

./modules/perception/inference/tensorrt/BUILD_
./modules/perception/inference/tensorrt/plugins/BUILD_
./modules/perception/inference/operators/BUILD_
./modules/perception/inference/caffe/BUILD_
./modules/perception/inference/tools/BUILD_
./modules/perception/data/BUILD_
./modules/perception/camera/lib/traffic_light/preprocessor/proto/BUILD_
./modules/perception/camera/lib/calibrator/common/BUILD_
./modules/perception/camera/lib/calibrator/laneline/BUILD_
./modules/perception/camera/lib/calibration_service/online_calibration_service/BUILD_
./modules/perception/camera/lib/lane/common/BUILD_
./modules/perception/camera/lib/lane/common/proto/BUILD_
./modules/perception/camera/lib/lane/detector/darkSCNN/BUILD_
./modules/perception/camera/lib/lane/detector/denseline/BUILD_
./modules/perception/camera/lib/lane/postprocessor/darkSCNN/BUILD_
./modules/perception/camera/lib/lane/postprocessor/darkSCNN/proto/BUILD_
./modules/perception/camera/lib/lane/postprocessor/denseline/BUILD_
./modules/perception/camera/lib/lane/postprocessor/denseline/proto/BUILD_
./modules/perception/camera/lib/lane/postprocessor/proto/BUILD_
./modules/perception/camera/lib/motion_service/BUILD_
./modules/perception/camera/lib/motion/BUILD_
./modules/perception/camera/lib/dummy/BUILD_
./modules/perception/camera/lib/obstacle/detector/yolo/BUILD_
./modules/perception/camera/lib/obstacle/detector/yolo/proto/BUILD_
./modules/perception/camera/lib/obstacle/transformer/multicue/BUILD_
./modules/perception/camera/lib/obstacle/transformer/multicue/proto/BUILD_
./modules/perception/camera/lib/obstacle/postprocessor/location_refiner/BUILD_
./modules/perception/camera/lib/obstacle/postprocessor/location_refiner/proto/BUILD_
./modules/perception/camera/lib/obstacle/tracker/common/BUILD_
./modules/perception/camera/lib/obstacle/tracker/omt/BUILD_
./modules/perception/camera/lib/obstacle/tracker/omt/proto/BUILD_
./modules/perception/camera/lib/feature_extractor/tfe/BUILD_
./modules/perception/camera/lib/feature_extractor/tfe/proto/BUILD_
./modules/perception/camera/test/BUILD_
./modules/perception/camera/app/BUILD_
./modules/perception/camera/app/proto/BUILD_
./modules/perception/camera/tools/obstacle_detection/BUILD_
./modules/perception/camera/tools/offline/BUILD_
./modules/perception/camera/tools/lane_detection/BUILD_
./modules/perception/common/image_processing/BUILD_
./modules/perception/testdata/BUILD_
./modules/perception/tool/benchmark/lidar/ctpl/BUILD_
./modules/perception/tool/benchmark/lidar/BUILD_
./modules/perception/tool/benchmark/lidar/base/BUILD_
./modules/perception/tool/benchmark/lidar/loader/BUILD_
./modules/perception/tool/benchmark/lidar/eval/BUILD_
./modules/perception/lidar/lib/scene_manager/ground_service/BUILD_
./modules/perception/lidar/lib/scene_manager/roi_service/BUILD_
./modules/perception/lidar/lib/scene_manager/BUILD_
./modules/perception/lidar/lib/object_builder/BUILD_
./modules/perception/lidar/lib/object_filter_bank/BUILD_
./modules/perception/lidar/lib/object_filter_bank/roi_boundary_filter/BUILD_
./modules/perception/lidar/lib/roi_filter/hdmap_roi_filter/BUILD_
./modules/perception/lidar/lib/roi_filter/roi_service_filter/BUILD_
./modules/perception/lidar/lib/segmentation/cnnseg/BUILD_
./modules/perception/lidar/lib/segmentation/cnnseg/spp_engine/BUILD_
./modules/perception/lidar/lib/segmentation/ncut/common/BUILD_
./modules/perception/lidar/lib/segmentation/ncut/common/graph_felzenszwalb/BUILD_
./modules/perception/lidar/lib/segmentation/ncut/BUILD_
./modules/perception/lidar/lib/dummy/BUILD_
./modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector/BUILD_
./modules/perception/lidar/lib/ground_detector/ground_service_detector/BUILD_
./modules/perception/lidar/lib/ground_detector/ground_service_detector/proto/BUILD_
./modules/perception/lidar/lib/map_manager/BUILD_
./modules/perception/lidar/tools/BUILD_
./modules/perception/lidar/tools/exporter/BUILD_

**Comment by storypku** [comment]
> and cant compile success.
> Are all these dirs will be removed?
> 
> ./modules/perception/inference/tensorrt/BUILD_
> ./modules/perception/inference/tensorrt/plugins/BUILD_
> ./modules/perception/inference/operators/BUILD_
> ./modules/perception/inference/caffe/BUILD_
> ./modules/perception/inference/tools/BUILD_
> ./modules/perception/data/BUILD_
> ./modules/perception/camera/lib/traffic_light/preprocessor/proto/BUILD_
> ./modules/perception/camera/lib/calibrator/common/BUILD_
> ./modules/perception/camera/lib/calibrator/laneline/BUILD_
> ./modules/perception/camera/lib/calibration_service/online_calibration_service/BUILD_
> ./modules/perception/camera/lib/lane/common/BUILD_
> ./modules/perception/camera/lib/lane/common/proto/BUILD_
> ./modules/perception/camera/lib/lane/detector/darkSCNN/BUILD_
> ./modules/perception/camera/lib/lane/detector/denseline/BUILD_
> ./modules/perception/camera/lib/lane/postprocessor/darkSCNN/BUILD_
> ./modules/perception/camera/lib/lane/postprocessor/darkSCNN/proto/BUILD_
> ./modules/perception/camera/lib/lane/postprocessor/denseline/BUILD_
> ./modules/perception/camera/lib/lane/postprocessor/denseline/proto/BUILD_
> ./modules/perception/camera/lib/lane/postprocessor/proto/BUILD_
> ./modules/perception/camera/lib/motion_service/BUILD_
> ./modules/perception/camera/lib/motion/BUILD_
> ./modules/perception/camera/lib/dummy/BUILD_
> ./modules/perception/camera/lib/obstacle/detector/yolo/BUILD_
> ./modules/perception/camera/lib/obstacle/detector/yolo/proto/BUILD_
> ./modules/perception/camera/lib/obstacle/transformer/multicue/BUILD_
> ./modules/perception/camera/lib/obstacle/transformer/multicue/proto/BUILD_
> ./modules/perception/camera/lib/obstacle/postprocessor/location_refiner/BUILD_
> ./modules/perception/camera/lib/obstacle/postprocessor/location_refiner/proto/BUILD_
> ./modules/perception/camera/lib/obstacle/tracker/common/BUILD_
> ./modules/perception/camera/lib/obstacle/tracker/omt/BUILD_
> ./modules/perception/camera/lib/obstacle/tracker/omt/proto/BUILD_
> ./modules/perception/camera/lib/feature_extractor/tfe/BUILD_
> ./modules/perception/camera/lib/feature_extractor/tfe/proto/BUILD_
> ./modules/perception/camera/test/BUILD_
> ./modules/perception/camera/app/BUILD_
> ./modules/perception/camera/app/proto/BUILD_
> ./modules/perception/camera/tools/obstacle_detection/BUILD_
> ./modules/perception/camera/tools/offline/BUILD_
> ./modules/perception/camera/tools/lane_detection/BUILD_
> ./modules/perception/common/image_processing/BUILD_
> ./modules/perception/testdata/BUILD_
> ./modules/perception/tool/benchmark/lidar/ctpl/BUILD_
> ./modules/perception/tool/benchmark/lidar/BUILD_
> ./modules/perception/tool/benchmark/lidar/base/BUILD_
> ./modules/perception/tool/benchmark/lidar/loader/BUILD_
> ./modules/perception/tool/benchmark/lidar/eval/BUILD_
> ./modules/perception/lidar/lib/scene_manager/ground_service/BUILD_
> ./modules/perception/lidar/lib/scene_manager/roi_service/BUILD_
> ./modules/perception/lidar/lib/scene_manager/BUILD_
> ./modules/perception/lidar/lib/object_builder/BUILD_
> ./modules/perception/lidar/lib/object_filter_bank/BUILD_
> ./modules/perception/lidar/lib/object_filter_bank/roi_boundary_filter/BUILD_
> ./modules/perception/lidar/lib/roi_filter/hdmap_roi_filter/BUILD_
> ./modules/perception/lidar/lib/roi_filter/roi_service_filter/BUILD_
> ./modules/perception/lidar/lib/segmentation/cnnseg/BUILD_
> ./modules/perception/lidar/lib/segmentation/cnnseg/spp_engine/BUILD_
> ./modules/perception/lidar/lib/segmentation/ncut/common/BUILD_
> ./modules/perception/lidar/lib/segmentation/ncut/common/graph_felzenszwalb/BUILD_
> ./modules/perception/lidar/lib/segmentation/ncut/BUILD_
> ./modules/perception/lidar/lib/dummy/BUILD_
> ./modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector/BUILD_
> ./modules/perception/lidar/lib/ground_detector/ground_service_detector/BUILD_
> ./modules/perception/lidar/lib/ground_detector/ground_service_detector/proto/BUILD_
> ./modules/perception/lidar/lib/map_manager/BUILD_
> ./modules/perception/lidar/tools/BUILD_
> ./modules/perception/lidar/tools/exporter/BUILD_

All the BUILD_ files were indicating that the corresponding functionality either can't work for now or need to be updated or should be deprecated.

**Comment by sinopec** [comment]
> All the BUILD_ files were indicating that the corresponding functionality either can't work for now or needs to be updated or should be deprecated.

will all these be fixed in official 6.0 release?

**Comment by storypku** [comment]
> > All the BUILD_ files were indicating that the corresponding functionality either can't work for now or needs to be updated or should be deprecated.
> 
> will all these be fixed in official 6.0 release?

Maybe some of them. It depends on the progress of our perception group.

**Comment by jinghaomiao** [comment]
@sinopec Perception module is now being refactored. Missing functions will return in phases. Please stay tuned. This issue is being closed. Please raise other issues if needed. Thanks for using Apollo.
