### ISSUE TITLE
Creating paths, getting dash cam views and more data

### ISSUE THREAD

**Issue by richtong** [ApolloAuto/apollo#1255]
Just starting on this project, we have successfully forked the ui for 1.5 and now the new ui 2.0 interface (it looks very nice), where is the discussion about:

1. Getting the equivalent dash cam video to the demo rosbag?
2. How do we get access to more Lidar data, I sent a request to the Apollo cloud but have not heard anything, is there someone we can contact
3. We want to integrate our own camera and other modules, I see there is a small amount of documentation on interfacing, but is there more documentation or something we can follow.

Any help appreciated!

**Comment by siyangy** [comment]
Thanks for adopting apollo 1.5 and trying out our new UI! For the first question, we are working on integrating the cam video into the rosbag and the video will also be rendered on our frontend in 2.0 release, stay tuned with that!

@ycool can probably better answer the other two questions or direct them to someone knowledge about them.

**Comment by richtong** [comment]
That is excellent. Happy to help anyway we can with this project. I will ask @ycool then. We would like to be able to show Video object classification in your system as part of our 2.0. 

Thanks,
Rich

No! Try not. Do, or do not. There is no try. Master Yoda. Star Wars Episode V: The Empire Strikes Back

http://tongfamily.com | @richtong | http://fb.me/richtong1 | +1-206-963-9029

**Comment by fyangw** [comment]
Thanks for access Apollo cloud. About the following question, 
> How do we get access to more Lidar data.
There are a 8.93GB sensor demonstration dataset and a 560MB calibration demonstration dataset in apollo open data platform. You can find Lidar sensor data in both of them download them with the following URL.
https://console.bce.baidu.com/apollo/task/download?locale=en-us#/apollo/home
If you need more Lidar data, could you describe your purpose and which kind of data you need.

Regards,
Frank

**Comment by richtong** [comment]
Hello Frank. Yes we are working to validate some classification models and wanted to see if we could get Lidar and also Video data from you. This would help calibrate our models and ensure we are on the correct track

Thanks,
Rich

**Comment by Zhenni17** [comment]
Closing the issue. Feel free to reopen the issue if I missed anything.
