### ISSUE TITLE
docker/scripts/dev_start.sh gives wrong depracation warning

### ISSUE THREAD

**Issue by javangent** [ApolloAuto/apollo#12567]
**Describe the bug**
After installing the nvidia-container-toolkit as specified [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker), running `docker/scripts/dev_start.sh` still outputs:

`
[WARNING] nvidia-docker is deprecated. Please install latest docker  and `nvidia-container-toolkit` as described by:
[WARNING]   https://github.com/NVIDIA/nvidia-docker/blob/master/README.md
`
The installation guide from NVIDIA guides the user to install `nvidia-docker2`, which installs `nvidia-container-toolkit` as a prerequisite. Thus, running 

`docker run --gpus all`

works just as well. However, `docker/scripts/dev_start.sh` finds the executable `nvidia-docker` and decides that the user doesn't have `nvidia-container-toolkit` installed, which is not true. 

The fix would be to check the existence of `nvidia-container-toolkit` first.

However, if there is a practical way to install `nvidia-container-toolkit` without `nvidia-docker2`, maybe this should be mentioned in the docs.

**To Reproduce**
1. Install nvidia-docker2 as explained in the installation guide
2. Run  `docker/scripts/dev_start.sh`
4. See warning

**Expected behavior**
This warning should not appear as running `docker run --gpus all` works.

**Comment by storypku** [comment]
Thanks for your reporting. In fact, we do have a document for that: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/prerequisite_software_installation_guide.md#installing-nvidia-container-toolkit
 
The warning was for previous nvidia-docker2 releases. If you google the following paragraph, 

```
Usage of nvidia-docker2 packages is deprecated since Nvidia GPUs are now natively supported as devices in the Docker runtime
```
Many results will prove that.

Now that nVidia have updated their documentation on `nvidia-docker2` usage recently, so do Apollo.

**Comment by storypku** [comment]
This issue is going to be closed now as the PR to remove this warning was already merged into master HEAD. Thanks for supporting Apollo. Wish we could do better.
