### ISSUE TITLE
The relationship between Cyber Message and cyberRT Framework

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#12575]
1、If I want to send Cyber messages, do I have to build cyberRT's framework first？
2、All message build to be sent must follow *.cc,*.h,*.dag,*.launch,BUILD?
3、If I will use cyberBridge communicate with apollo algorithm，How do I use this module alone （apollo/modules/bridge/）？

**Comment by ntutangyun** [comment]
1. yes if you want to communicate via cyber RT framework you need to compile it as well as the message definition.
2. if your message is defined in `proto` files, you need `.proto` and `BUILD` file, if your message is defined as C++ classes, you need '.h' and/or '.cc' and 'BUILD'.  `dag` and `launch` files are for starting components. 
3. just run `bridge.sh`.
