### ISSUE TITLE
Hello I want setup a rosgraph service so that I can visit in client machine

### ISSUE THREAD

**Issue by yiakwy** [ApolloAuto/apollo#1257]
Hello my apollo docker instance runs inside remote docker instance, and I want to expose a service so that I can see rosgraph microservices relationship through a client browser (X11 supported). Any assistance from maintainers is appreciated.

Concretely, in an X11 unsupported server rosgraph will generate a file:

```bash
 /control :
    Inbound:
      /play_1510634388173405487
      /dreamview
      /play_1510634388173405487
      /control
      /dreamview
      /localization
      /play_1510634388173405487
      /localization
      /dreamview
      /hmi_ros_bridge
    Outbound:
      /dreamview
      /control
      /record_1510634419401101894
      /record_1510634419401101894
```
I think I can plot graph using javascript do what ros plot does in front end. Hence I need to setup a service inside docker to export data to the outside.

This service can be integrated into hmi interface using python Flask or something else.

Here is the source code of rqt_graph(GUI written in Qt):
> https://github.com/yiakwy/rqt_graph/blob/master/src/rqt_graph/interactive_graphics_view.py

The expected services mesh from ROS I want is in json format (so that I can use wide first traversal to plot nodes)

**Comment by natashadsouza** [comment]
Sorry we could not get back to you on this request. Please let me know if you still need support on your request. Feel free to re-open the issue.
