### ISSUE TITLE
perception_camera.launch doesn't work

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#12571]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master version
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
cyber_launch start modules/perception/production/launch/perception_camera.launch

### Supporting materials (screenshots, command lines, code/script snippets):
[cyber_launch_2999] INFO Launch file [/apollo/modules/perception/production/launch/perception_camera.launch]
[cyber_launch_2999] INFO ========================================================================================================================
[cyber_launch_2999] INFO Load module [perception_camera] library: [mainboard_default_2999] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: []
[cyber_launch_2999] INFO Start process [mainboard_default_2999] successfully. pid: 3006
[cyber_launch_2999] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_2999] INFO Load module [motion_service] library: [mainboard_default_2999] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_motion_service.dag] exception_handler: []
[mainboard_default_2999]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_2999]  I0917 07:35:13.093334  3006 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag /apollo/modules/perception/production/dag/dag_motion_service.dag -p mainboard_default_2999 -s CYBER_DEFAULT 
[mainboard_default_2999]  I0917 07:35:13.093434  3006 module_argument.cc:120] []Found non-option ARGV-element "/apollo/modules/perception/production/dag/dag_motion_service.dag"
[mainboard_default_2999]  I0917 07:35:13.093442  3006 module_argument.cc:29] []Usage: 
[mainboard_default_2999]      mainboard [OPTION]...
[mainboard_default_2999]  Description: 
[mainboard_default_2999]      -h, --help : help information 
[mainboard_default_2999]      -d, --dag_conf=CONFIG_FILE : module dag config file
[mainboard_default_2999]      -p, --process_group=process_group: the process namespace for running this module, default in manager process
[mainboard_default_2999]      -s, --sched_name=sched_name: sched policy conf for hole process, sched_name should be conf in cyber.pb.conf
[mainboard_default_2999]  Example:
[mainboard_default_2999]      mainboard -h
[mainboard_default_2999]      mainboard -d dag_conf_file1 -d dag_conf_file2 -p process_group -s sched_name
[cyber_launch_2999] ERROR Process [mainboard_default_2999] has died [pid 3006, exit code 1, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag /apollo/modules/perception/production/dag/dag_motion_service.dag -p mainboard_default_2999 -s CYBER_DEFAULT].
[cyber_launch_2999] INFO All processes has died.
[cyber_launch_2999] INFO Cyber exit.
[cyber_launch_2999] INFO All processes have been stopped.

Don't know the reason why Error occurred

**Comment by jinghaomiao** [comment]
@younggam94 : Camera based obstracle detection is being refactored. The new change will be available to the public once it's ready. Please stay turned. This issue is being closed. Please raise new issues if needed. Thanks for using Apollo.

**Comment by sinopec** [comment]
> @younggam94 : Camera based obstracle detection is being refactored. The new change will be available to the public once it's ready. Please stay turned. This issue is being closed. Please raise new issues if needed. Thanks for using Apollo.

Will the refractor work be done in apollo 6.0 release?

**Comment by vin-cloud** [comment]
> @younggam94 : Camera based obstracle detection is being refactored. The new change will be available to the public once it's ready. Please stay turned. This issue is being closed. Please raise new issues if needed. Thanks for using Apollo.

@jinghaomiao is this fixed issue fixed? because I am getting the same error while using Apollo 6.0.
