### ISSUE TITLE
能做一个中文文档吗？

### ISSUE THREAD

**Issue by langxj** [ApolloAuto/apollo#126]
Can you make a Chinese document? After all, Baidu is an enterprise in China and should provide documentation of its mother tongue.

**Comment by ycool** [comment]
It is a very good suggestion. The Chinese version will come in near future.

**Comment by MemedaWang** [comment]
Why no chinese document?

**Comment by tangxu00** [comment]
good

**Comment by helwodlrol** [comment]
靠谱！

**Comment by feizhan66** [comment]
就应该出中文

**Comment by jinghaomiao** [comment]
README in Chinese has been uploaded.
