### ISSUE TITLE
Apollo Auto Software Architecture

### ISSUE THREAD

**Issue by miewan** [ApolloAuto/apollo#12602]
Hello,

Can anyone explain me what is the blue dash rectangle (grouping together perception, preditcion, planning, control) and yellow dash rectangle (grouping together perception, prediction, planning) stand for?

<img width="866" alt="Apollo_3_5_software_architecture" src="https://user-images.githubusercontent.com/50077014/93608222-fdaf8700-f98f-11ea-95c0-b2c47ecec93a.png">

**Comment by LiuHaolan** [comment]
That just means that yellow dashed rectangle is feeded with HD Map and the blue one is feeded with localization output
