### ISSUE TITLE
Lost some already built modules after ru

### ISSUE THREAD

**Issue by ghoulich** [ApolloAuto/apollo#12613]
### System information

- **CPU:** Intel i7-8700
- **Memory:** 32 GB
- **Video Card**: GeForce GTX 1080 Ti
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 20.04.1
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0, master branch
- **Output of `apollo.sh config` if on `master` branch**:
![image](https://user-images.githubusercontent.com/3353241/93724940-dd750780-fbdd-11ea-8f19-6217d6d0deb6.png)

### Steps to reproduce the issue:
- first, enter apollo container:
```bash
cd ~/Downloads/apollo/
./docker/scripts/dev_into.sh
```

- then, build apollo with gpu in container:
```bash
./apollo.sh build_opt_gpu
```

- when apollo build finished, check modules in bazel-bin directory:
```bash
ll bazel-bin/modules/
```
modules list as below:
![image](https://user-images.githubusercontent.com/3353241/93725059-bc60e680-fbde-11ea-8a8b-5bc529c01c00.png)

- run bootstrap.sh script, and it works well:
![image](https://user-images.githubusercontent.com/3353241/93725081-f0d4a280-fbde-11ea-90c7-e5cc152acb85.png)

- then, build python api example named talker.py with bazel build command:
```bash
bazel build //cyber/python/cyber_py3/examples:talker
```
and talker example built successfully:
![image](https://user-images.githubusercontent.com/3353241/93725129-34c7a780-fbdf-11ea-9285-a08bbbde5097.png)

- when I stop and start bootstrap.sh script again, apollo complains missing cyber_launch:
![image](https://user-images.githubusercontent.com/3353241/93725159-6cceea80-fbdf-11ea-95b6-71ae05a0f8af.png)

- check alreay built modules in bazel-bin again, I found that some modules have lost:
![image](https://user-images.githubusercontent.com/3353241/93725173-8839f580-fbdf-11ea-8107-c3ae7f5bbba4.png)
as we can see, module list is much shorter than before!

I don't know it is a bug or feature of Bazel, it may clean bazel-bin directory when perform bazel build or bazel run command, it causes I can't build and debug my own python script in apollo container!

**Comment by storypku** [comment]
> n't build and debug my own python script in apollo container!

The reason was as follows: 

When you run `./apollo.sh build_opt_gpu`, bazel runs `bazel build --config=opt --config=gpu` under the hood.
And the compilation mode is `-c opt` implied by `--config=opt`.

When you run `bazel build //path/to:your_target`, the compilation mode is `-c fastbuild` which is bazel's default configuration.

So, my suggestion would be, either use `./apollo.sh build_opt_gpu` all the time, or use

```
bazel build --config=opt --config=gpu //path/to:your_target
```
to avoid this problem.

See doc: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/apollo_build_and_test_explained.md

**Comment by ghoulich** [comment]
I have tried your solution, and it works! Thanks a lot!

**Comment by changsh726** [comment]
It seems that your problem has been solved and this issue will be closed. Please feel free to reopen it or open a new issue if you still have any other questions. Thanks for your support for Apollo!
