### ISSUE TITLE
Number of lidars for Apollo 5.0 ???

### ISSUE THREAD

**Issue by Abd0ul** [ApolloAuto/apollo#12629]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5, 5.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

hello, I would like to know if it is mandatory to use 4 lidars for Apollo 5.0? I read in the documentation more precisely on the architecture and the perception module they mention the use of 4 Lidars including one vls128 and 3 vlp16. Is it possible to use only one Lidar (vls128 or vlp32C) for this version?

Someone has already asked the question in this ticket [https://github.com/ApolloAuto/apollo/issues/10274](https://github.com/ApolloAuto/apollo/issues/10274) but was not answered. Can I use Apollo 5.0 with only one Lidar, if so should I make changes in the affected modules ???

Thank you in advance!

**Comment by jeroldchen** [comment]
Hi @Abd0ul , for perception module, it is available to use only one Lidar sensor. For the default setting, only messages from 128c lidar or 16c lidar can be processed. However, you can modify the lidar sensor setting in https://github.com/ApolloAuto/apollo/blob/r5.0.0/modules/perception/production/dag/dag_streaming_perception.dag  and related configs.

**Comment by Abd0ul** [comment]
Thank you for your feedback @jeroldchen.

Just for confirmation I must create the configs files corresponding to the model of my sensor if they do not exist, such as the velodyne128_segmentation_conf.pb.txt file which the dag_streaming_perception.dag file uses !!

I'm going to be using a velodyne VLP-32C and I have browsed the apollo 5.0 version modules a bit and I can't see some of the VLP-32C config files written for the VLS-128 and VLP-16 model. Reassure me the velodyne vls-128 can be replaced by the vlp-32c ??

**Comment by lucasnmatias** [comment]
I'm also interested on this. I'm also using the VLP-32c as far as I know Apollo doesn't have a trained model for VLP-32c, so it's recommended to use the trained model for Velodyne 64.

**Comment by jeroldchen** [comment]
Actually, the correlation between model and Lidar driver's beam number is not that strong. You can apply the models deployed for other Lidar drivers on VLP-32c nearly without any adjustment and even copy their configs with just a few modifications, more specifically, the sensor name.

**Comment by Abd0ul** [comment]
Thank @jeroldchen for your answers, I will first integrate my VLP-32c model and if everything works well with the system I would consider going to the next step by adding one or two VLP-16 models to improve the perception module.

@lucasnmatias I d'nt know where you are in the integration of your VLP-32c lidar, if you are interested we can coordinate our efforts for this task to go faster. Let me know if you are up for it !!
