### ISSUE TITLE
why use pytorch model replace onnx model in pointpillars detection

### ISSUE THREAD

**Issue by chasingw** [ApolloAuto/apollo#12621]
hi, I found the model update recently, and why use pytorch model replace onnx model in pointpillars detection, and rpn still use onnx model? Does this improve the speed? and how much? Looking forward to your reply.

**Comment by jeroldchen** [comment]
Hi @chasingw , thanks for your interest and passion in Apollo. We replace PFE onnx model with a torch model to reduce the inference time of the PFE stage for around 25ms, but not working if applying the same operation to RPN stage.

**Comment by chasingw** [comment]
@jeroldchen thanks.
