### ISSUE TITLE
yolov4 model is not updated?

### ISSUE THREAD

**Issue by WSTao** [ApolloAuto/apollo#12638]
The camera module added yolov4, but I did not find the latest model file

**Comment by changsh726** [comment]
The yolov4 model files is mounted at `/apollo/modules/perception/camera/lib/obstacle/detector/yolov4/model` as a docker volume when you run `./docker/scripts/dev_start.sh`. You can find them in the above path after entering the container.

**Comment by WSTao** [comment]
OKey, thanks

**Comment by changsh726** [comment]
It seems that your problem has been solved and this issue will be closed. Please feel free to reopen it or open a new issue if you still have any other questions. Thanks for your support for Apollo!
