### ISSUE TITLE
[FEATURE] Export .record to rosbag file

### ISSUE THREAD

**Issue by lucasnmatias** [ApolloAuto/apollo#12631]
**Is your feature request related to a problem? Please describe.**
Apollo supports converting rosbag files to .record files to be played in Cyber RT. I would like to know if exists the opposite tool, to convert .record data to rosbag data, so the data would be portable to other platforms.

**Describe the solution you'd like**
A way to convert .record data from Cyber RT to rosbag data, to be read on ROS.

**Comment by storypku** [comment]
Hi @lucasnmatias , thanks for your suggestion. Better interoperability with ROS1/ROS2 still has its value as of today, and we will look at ways to bridge Apollo Cyber and ROS1/ROS2.

**Comment by ZhenshengLee** [comment]
> Hi @lucasnmatias , thanks for your suggestion. Better interoperability with ROS1/ROS2 still has its value as of today, and we will look at ways to bridge Apollo Cyber and ROS1/ROS2.

https://github.com/AuroAi/apollo_ros_bridge may meet the needs of connecting cyber3.5 and ROS1, but it's outdated.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
