### ISSUE TITLE
Run Perception without HDMap

### ISSUE THREAD

**Issue by lucasnmatias** [ApolloAuto/apollo#12634]
**Describe the solution you'd like**
I have been studying the Apollo Perception and I noticed that for HDMap ROI Filter it's used a HDMap. I would like to know if the HDMap is mandatory for the Apollo perception or if we could run the Apollo perception without the, processing all the data without the ROI filter.

**Comment by jeroldchen** [comment]
@lucasnmatias Well, HDMap is required by traffic light perception module. Without HDMap input, traffic light detection can still be successfully launched but would have no detected traffic light output. For the other sub-modules of Perception, you can toggle off the hdmap_input flag at corresponding configs in apollo/module/perception/production/conf and shall have no abnormal results.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
