### ISSUE TITLE
Commiting conventions in Apollo

### ISSUE THREAD

**Issue by Kirkirillka** [ApolloAuto/apollo#12649]
**Is your feature request related to a problem? Please describe.**
In our team, we encountered a problem with git commit naming, because we have a quite large crew with a different background. Unfortunately, we use different approaches, and there are no rules defined so far. AutoApollo tries to use the unified way (as I see), but still commits varies. That leads you have to fill RELEASE.md manually and have CHANGELOG.md absent.

**Describe the solution you'd like**
I would like to suggest including commits conventions checking into project, for example, to use [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/). Here is a set of [tools](https://github.com/conventional-changelog/conventional-changelog) to help to enforce a specific commit template. 

Those instruments are intended to help in:

- Use a clear commit template, people can customize their own conventions
- Automate CHANGELOG.md and RELEASE.md generating 

**Describe alternatives you've considered**
Another way is to explicitly define recommended approaches for commit naming. You may create a doc with rules used so far.

**Additional context**

Useful tools I personally playing around:

- [commitizen](https://github.com/commitizen/cz-cli)
- [commitlint](https://commitlint.js.org/#/)
- [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/)

**Comment by daohu527** [comment]
Yes, we've been thinking about how to standardize code commits. We may refer to [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/) later
