### ISSUE TITLE
Other types of lidars?

### ISSUE THREAD

**Issue by Jeffvvvv** [ApolloAuto/apollo#1264]
Is here only the certain type of lidar(HDL-64ES3) that can support the whole system?

Any other types of lidars that we can use to install on the system?

**Comment by jinghaomiao** [comment]
In Apollo 1.5, only Velodyne 64 is supported. But you are free to add drivers to ROS so that it can support multiple models of lidars.

**Comment by Prasan03** [comment]
Hi,
I am kind of stuck at this point, I have an IBEO LUX 2010 LiDAR with a ROS driver and I want to include this inside Apollo and visualize the data on Dreamview on my PC and maybe try out the Perception module after that. Can someone help me with adding the ROS driver into Apollo and get the LiDAR running on Dreamview?
Thanks in advance :)

**Comment by jinghaomiao** [comment]
@Prasan03 We encourage developers to support drivers for devices that are not referenced by Apollo. All Apollo referenced hardwares are tested for compatibility with Apollo. We do not guarantee other models will work the same way though.
