### ISSUE TITLE
Where is the teleop source code of video and audio encoding?

### ISSUE THREAD

**Issue by fy2462** [ApolloAuto/apollo#12645]
Hi, guys:

I am reading the teleop source code related, But only found some status code in `dreamview/backend/teleop`, where is the other complete source code like about `remote control communication`, `video/audio encoding`

BTW， I found the `apollo-teleop` folder in `dev_start.sh#301`, How to get the code of folder?

Some scripts like `run_teleop_video_decoderX.bash`, `run_teleop_router.bash`, `run_teleop_voip_encoder.bash`
How to find them ?

Thanks, waiting for your response.

**Comment by unacao** [comment]
please check this README to see if it helps answer your question https://github.com/ApolloAuto/apollo/tree/master/modules/dreamview/backend/teleop

**Comment by fy2462** [comment]
Got it, so it just seems like a propaganda feature in V6.0.
