### ISSUE TITLE
Support for Velodyne 32L LiDAR

### ISSUE THREAD

**Issue by lucasnmatias** [ApolloAuto/apollo#12653]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0+
- **Output of `apollo.sh config` if on `master` branch**:

Hi, we have been working with Apollo to try to setup a data collection platform. We have some doubts and considerations about the LiDAR part. I know that VLP-32C is supported in Apollo but the doubt is if we can use this as the top middle LiDAR. On Apollo sensor setup it's used a top middle 128L LiDAR and two 16L LiDARs (front and rear). I would like to use only one 32L LiDAR as the top middle main LiDAR. But I'm not sure about how this would affect the full Apollo performance. The calibration, perception and localization can be done using only this 32L LiDAR? The performance would be worst? I'm trying to collect all the information to define where to go.

**Comment by Robotics010** [comment]
Hi there. We are using Velodyne VLP-32C Ultra Pack LiDAR and it is enough to ride autonomously using even lidar data only for perception. However fusing with camera perception results is recommended.
