### ISSUE TITLE
Traffic light module crashes with "out of memory"

### ISSUE THREAD

**Issue by rongguodong** [ApolloAuto/apollo#12671]
I pulled latest master on 9/23. After entered the docker, I run "bridge.sh", "bootstrap_lgsvl.sh", and then enabled "localization" and "transform" modules from Dreamview.

When I run "./scripts/perception.sh start_fe", I see both "perception" and "traffic light" modules are running, and I got both `/apollo/perception/obstacles` and `/apollo/perception/traffic_light` as green in cyber_monitor.

However, after a while, the traffic module crashes with "out of memory" from CUDA. Detailed errors are attached here at the end.

My GPU is RTX 1080 with 8GB video memory. It works fine with Apollo 5.5.

========================================

[perception_trafficlights] [E context_gpu.cu:444] Encountered following in ~CUDAContext: [enforce fail at context_gpu.h:198] . Encountered CUDA error: out of memory
[perception_trafficlights] 0: c10::ThrowEnforceNotMet(char const, int, char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7fd69e861067 in /usr/local/libtorch_gpu/lib/libc10.so)
[perception_trafficlights] 1: <unknown function> + 0x2b1d12d (0x7fd637a4f12d in /usr/local/libtorch_gpu/lib/libtorch_cuda.so)
[perception_trafficlights] 2: caffe2::CUDAContext::~CUDAContext() + 0x4b (0x7fd637a4b73b in /usr/local/libtorch_gpu/lib/libtorch_cuda.so)
[perception_trafficlights] 3: <unknown function> + 0x2ee7ef6 (0x7fd637e19ef6 in /usr/local/libtorch_gpu/lib/libtorch_cuda.so)
[perception_trafficlights] 4: <unknown function> + 0x2d106bc (0x7fd637c426bc in /usr/local/libtorch_gpu/lib/libtorch_cuda.so)
[perception_trafficlights] 5: <unknown function> + 0x2d5610c (0x7fd69bac110c in /usr/local/libtorch_gpu/lib/libtorch_cpu.so)
[perception_trafficlights] 6: <unknown function> + 0x2d11ad7 (0x7fd69ba7cad7 in /usr/local/libtorch_gpu/lib/libtorch_cpu.so)
[perception_trafficlights] 7: torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x35 (0x7fd69ba71375 in /usr/local/libtorch_gpu/lib/libtorch_cpu.so)
[perception_trafficlights] 8: <unknown function> + 0x2ce4ae2 (0x7fd69ba4fae2 in /usr/local/libtorch_gpu/lib/libtorch_cpu.so)
[perception_trafficlights] 9: torch::jit::GraphFunction::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x3a (0x7fd69bd7eb2a in /usr/local/libtorch_gpu/lib/libtorch_cpu.so)
[perception_trafficlights] 10: torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0xe0 (0x7fd69bd30950 in /usr/local/libtorch_gpu/lib/libtorch_cpu.so)
[perception_trafficlights] 11: apollo::perception::inference::TorchDet::Infer() + 0x934 (0x7fd6f2366c24 in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Sinference_Slibtorch_Slibtorch_Udet.so)
[perception_trafficlights] 12: apollo::perception::camera::TrafficLightDetection::Inference(std::vector<std::shared_ptr<apollo::perception::base::TrafficLight>, std::allocator<std::shared_ptr<apollo::perception::base::TrafficLight> > >, apollo::perception::camera::DataProvider) + 0x739 (0x7fd6f31d11d9 in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Scamera_Slib_Straffic_Ulight_Sdetector_Sdetection_Slibdetection.so)
[perception_trafficlights] 13: apollo::perception::camera::TrafficLightDetection::Detect(apollo::perception::camera::TrafficLightDetectorOptions const&, apollo::perception::camera::CameraFrame*) + 0x354 (0x7fd6f31d18f4 in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Scamera_Slib_Straffic_Ulight_Sdetector_Sdetection_Slibdetection.so)
[perception_trafficlights] 14: apollo::perception::camera::TrafficLightCameraPerception::Perception(apollo::perception::camera::CameraPerceptionOptions const&, apollo::perception::camera::CameraFrame*) + 0x34 (0x7fd7140d8564 in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Scamera_Sapp_Slibtraffic_Ulight_Ucamera_Uperception.so)
[perception_trafficlights] 15: apollo::perception::onboard::TrafficLightsPerceptionComponent::OnReceiveImage(std::shared_ptr<apollo::drivers::Image>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xa20 (0x7fd7145cda90 in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Sonboard_Scomponent_Slibperception_Ucomponent_Uinner_Ucamera.so)
[perception_trafficlights] 16: std::_Function_handler<void (std::shared_ptr<apollo::drivers::Image> const&), std::_Bind<void (apollo::perception::onboard::TrafficLightsPerceptionComponent::*(apollo::perception::onboard::TrafficLightsPerceptionComponent*, std::_Placeholder<1>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >))(std::shared_ptr<apollo::drivers::Image>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> >::_M_invoke(std::_Any_data const&, std::shared_ptr<apollo::drivers::Image> const&) + 0x50 (0x7fd714581b10 in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Sonboard_Scomponent_Slibperception_Ucomponent_Uinner_Ucamera.so)
[perception_trafficlights] 1}::operator()() const + 0x8c (0x7fd71459471c in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Sonboard_Scomponent_Slibperception_Ucomponent_Uinner_Ucamera.so)
[perception_trafficlights] 18: <unknown function> + 0xa886c (0x7fd71459486c in /apollo/bazel-bin/modules/perception/onboard/component/../../../../_solib_local/libmodules_Sperception_Sonboard_Scomponent_Slibperception_Ucomponent_Uinner_Ucamera.so)
[perception_trafficlights] 19: <unknown function> + 0x421a (0x7fd73f0ac21a in /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-opt/bin/cyber/../_solib_local/libcyber_Scroutine_Slibcroutine.so)
[perception_trafficlights]
[perception_trafficlights] terminate called after throwing an instance of 'std::runtime_error'
[perception_trafficlights] what(): The following operation failed in the TorchScript interpreter.
[perception_trafficlights] Traceback of TorchScript, serialized code (most recent call last):
[perception_trafficlights] File "code/__torch__/detectron2/export/caffe2_modeling.py", line 16, in forward
[perception_trafficlights] 5, 6, 7, 8, 9, 10, = (_2).forward(input, )
[perception_trafficlights] 11 = (1).forward(_5, 6, 7, 8, 9, im_info, )
[perception_trafficlights] 12 = (0).forward(_11, 5, 6, 7, 10, im_info, )
[perception_trafficlights] ~~~~~~~~~~~ <--- HERE
[perception_trafficlights] 13, 14, 15, = 12
[perception_trafficlights] return (13, 14, _15)
[perception_trafficlights] File "code/__torch__/detectron2/modeling/roi_heads/roi_heads.py", line 15, in forward
[perception_trafficlights] im_info: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
[perception_trafficlights] _0 = self.box_head
[perception_trafficlights] _1 = (self.box_pooler).forward(argument_1, argument_2, argument_3, argument_4, argument_5, )
[perception_trafficlights] ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
[perception_trafficlights] _2 = (self.box_predictor).forward((_0).forward(_1, ), )
[perception_trafficlights] 3, 4, = _2
[perception_trafficlights] File "code/__torch__/detectron2/export/c10.py", line 56, in forward
[perception_trafficlights] rois_idx_restore_int32 = ops._caffe2.CopyCPUToGPU(t13, None)
[perception_trafficlights] _18 = ops._caffe2.RoIAlign(argument_2, roi_fpn, "NCHW", 0.25, 7, 7, 0, True, None)
[perception_trafficlights] _19 = ops._caffe2.RoIAlign(argument_3, roi_fpn0, "NCHW", 0.125, 7, 7, 0, True, None)
[perception_trafficlights] ~~~~~~~~~~~~~~~~~~~~ <--- HERE
[perception_trafficlights] _20 = ops._caffe2.RoIAlign(argument_4, roi_fpn1, "NCHW", 0.0625, 7, 7, 0, True, None)
[perception_trafficlights] _21 = ops._caffe2.RoIAlign(argument_5, roi_fpn2, "NCHW", 0.03125, 7, 7, 0, True, None)
[perception_trafficlights]
[perception_trafficlights] Traceback of TorchScript, original code (most recent call last):
[perception_trafficlights] /home/lishaohua01/Workspace/detection/detectron2/detectron2/export/c10.py(336): forward
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): _call_
[perception_trafficlights] /home/lishaohua01/Workspace/detection/detectron2/detectron2/modeling/roi_heads/roi_heads.py(727): _forward_box
[perception_trafficlights] /home/lishaohua01/Workspace/detection/detectron2/detectron2/modeling/roi_heads/roi_heads.py(674): forward
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): _call_
[perception_trafficlights] /home/lishaohua01/Workspace/detection/detectron2/detectron2/export/caffe2_modeling.py(272): forward
[perception_trafficlights] /usr/lib/python3.6/contextlib.py(52): inner
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): _call_
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
[perception_trafficlights] /home/lishaohua01/.local/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
[perception_trafficlights] /home/lishaohua01/Workspace/detection/detectron2/detectron2/export/api.py(142): export_torchscript
[perception_trafficlights] tools/deploy/caffe2_converter.py(73): <module>
[perception_trafficlights] RuntimeError: [enforce fail at context_gpu.cu:513] error == cudaSuccess. 2 vs 0. Error at: /home/liufeng/tmp/pytorch/caffe2/core/context_gpu.cu:513: out of memory

**Comment by xiaoMrzhang** [comment]
@rongguodong It seems that some extra memory is not released during the running of the model，could you please show the memory of traffic light and obstacles before crash?

**Comment by jeroldchen** [comment]
We have optimized GPU memory usage recently. You can pull the latest master and see if it has the same problem again.
