### ISSUE TITLE
call ros commands in apollo 6 + lgsvl

### ISSUE THREAD

**Issue by glebkiselev** [ApolloAuto/apollo#12670]
Hi, 
I am currently working on Apollo and was able to setup LG simulator with Apollo 6.0. But when I start a simulator on a different PC and connect it through a cyber bridge with my apollo on my PC I meet an error of localization. I the simulator I see the vehicle on BorregasAve map in a correct start position, but in Dreamview the localization module set my vehicle to the right of the position for 10-15 meters. I tried to call rostopic info/roscore and other ros commands inside the apollo's docker to check the vehicle position, but "command not found" errors. How can I check the initial vehicle position in apollo 6.0 and are there any way to communicate with cyber in ros-style?

**Comment by alexiskovi** [comment]
@glebkiselev, Apollo has migrated from ROS to Cyber RT in version 3.0. Please use cyber_monitor to see list of channels and data inside them. You can see docs for developer tools [here](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md)

**Comment by alexiskovi** [comment]
@glebkiselev, also, the cause of mismatching in maps with simulator can be in old map assets. Try to re-download new assets from [LGSVL content website](https://content.lgsvlsimulator.com/maps/). At least, it helped in my case.

**Comment by rongguodong** [comment]
Counterpart to "rostopic" of CyberRT is "cyber_monitor", where you can see all Cyber channels (similar to ROS topics).

**Comment by AlexandrZabolotny** [comment]
Hi @glebkiselev   
Maybe this will help you
https://github.com/lgsvl/simulator/issues/954

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
