### ISSUE TITLE
Once more the question on Apollo Kernel: is it really a indispensable dependence for real-car-running-on-road test environment?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12675]
In the open course give by @storypku titled as "Apollo-6.0-Infrastructure", the following description was given:

![image](https://user-images.githubusercontent.com/11155854/94214417-1843ac00-ff0c-11ea-96c7-50bc45772335.png)

I checked the mentioned [document](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md) and the relevant ones referred by it, but can't find any descriptions on the **Apollo Kernel**. Hence, I still can't figure out the problem: is it really a Indispensable dependence for real-car-running-on-road test environment?

Any hints will be highly appreciated?

Regards,
HY

**Comment by storypku** [comment]
Hi there,
     Since Apollo kernel was based on an rather old  kernel, and many have reported errors in building it. So we removed the kernel installation section from `Apollo Software Installation Guide`. On real car running road test, RT kernel is indeed required. Am I right? @jinghaomiao @Capri2014

**Comment by storypku** [comment]
This issue is going to be closed. Should we have Apollo Kernel updated and ready, we will have everyone know. Please stay tuned.
