### ISSUE TITLE
Apollo 2.5 support Pwrpack7-E1 ???

### ISSUE THREAD

**Issue by Abd0ul** [ApolloAuto/apollo#12681]
### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0,1.5,2.0,2.5)**:

Hello
I would like to know is it possible to use a Pwrpack7D-E1 in apollo 2.5? if so what are the configurations to integrate?

Apollo 2.5 was released before the Pwrpack7 modules were manufactured, so the base architecture does not include the driver for this module, so I'm wondering if we want to use the Pwrpack7-E1 instead of the Propack6 in apollo 2.5 how I should m 'take it?

I saw the installation guide [here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Navigation/PwrPak7_Installation_Guide.md) but don't know how to integrate it into Apollo 2.5.

Thank you in advance.

Link for Pwrpack7D-E1: https://novatel.com/products/receivers/enclosures/pwrpak7d

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
