### ISSUE TITLE
Is NDT the same as lidar in MSF folder?

### ISSUE THREAD

**Issue by LiuZhenyao** [ApolloAuto/apollo#12689]
The localization folder contains three positioning methods: NDT, RTK and MSF. MSF also has positioning_ lidar.cc about lidar localization,  Is NDT the same as the method in MSF?

**Comment by guoweiwan** [comment]
The LiDAR-based localization module in MSF mode is implemented by a distribution-based matching algorithm, which is not NDT. More details please check the paper "Robust and precise vehicle localization based on multi-sensor fusion in diverse city scenes, ICRA, 2018".

**Comment by apollodevcommunity** [comment]
你好，原理上，两者是一样的。不过在msf中他的触发条件逻辑以及一些参数和单纯使用NDT是不一样的。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=168
