### ISSUE TITLE
Several questions about audio module.

### ISSUE THREAD

**Issue by rongguodong** [ApolloAuto/apollo#12684]
According to its README, it only detect "the siren sound coming from the active emergency vehicle". If that is the case, why does the result have a filed `is_siren`? Should it be always TRUE?

According to [this proto](https://github.com/ApolloAuto/apollo/blob/master/modules/audio/proto/audio.proto), `moving_result`, `position`, and `source_degree` are all "optional" instead of "repeated", which indicates there is only one vehicle reported in the result. Which one will it be if there are multiple emergency vehicles?

The README also mentioned that it can output "siren on/off status". If siren is off, how can this audio module detect the emergency vehicle's position, direction, etc.?

**Comment by daohu527** [comment]
>1. According to its README, it only detect "the siren sound coming from the active emergency vehicle". If that is the case, why does the result have a filed is_siren? Should it be always TRUE?

is_siren is not always true, It uses a deep learning model to determine whether it is a siren sound.

> 2. According to this proto, moving_result, position, and source_degree are all "optional" instead of "repeated", which indicates there is only one vehicle reported in the result. Which one will it be if there are multiple emergency vehicles?

It seems that it only supports whether there are siren, and may not support multiple.

> 3. The README also mentioned that it can output "siren on/off status". If siren is off, how can this audio module detect the emergency vehicle's position, direction, etc.?

I think the meaning expressed here may be whether there is an siren, rather than closing or opening this module.

**Comment by rongguodong** [comment]
> > 1. The README also mentioned that it can output "siren on/off status". If siren is off, how can this audio module detect the emergency vehicle's position, direction, etc.?
> 
> I think the meaning expressed here may be whether there is an siren, rather than closing or opening this module.

What I mean is: if the siren is off (i.e. there is no siren), how can you detect the emergency vehicle?

**Comment by rongguodong** [comment]
> > 1. According to this proto, moving_result, position, and source_degree are all "optional" instead of "repeated", which indicates there is only one vehicle reported in the result. Which one will it be if there are multiple emergency vehicles?
> 
> It seems that it only supports whether there are siren, and may not support multiple.
> 
If there are two or more emergency vehicles, what will be the output?

**Comment by daohu527** [comment]
> What I mean is: if the siren is off (i.e. there is no siren), how can you detect the emergency vehicle?

Maybe you can use other modules to achieve this, but the "audio" module can't, it needs sound.  

> If there are two or more emergency vehicles, what will be the output?

`is_siren` will true, but the `MovingResult`, `position` and `source_degree` will be confused. There is an example for `MovingResult`
```
enum MovingResult {
  UNKNOWN = 0;
  APPROACHING = 1;
  DEPARTING = 2;
  STATIONARY = 3;
}
```
If there are 2 cars, how do you set this value?

**Comment by rongguodong** [comment]
> > What I mean is: if the siren is off (i.e. there is no siren), how can you detect the emergency vehicle?
> 
> Maybe you can use other modules to achieve this, but the "audio" module can't, it needs sound.

Yes, this is exactly what I mean! If  there is no siren, the audio module cannot detect anything, and thus will not generate message into `/apollo/audio/audio_detection`. In other words, as long as we have messages in `/apollo/audio/audio_detection`, there is siren. So, will `is_siren` always be TRUE?

**Comment by daohu527** [comment]
We say "Audio Component" is **event based drive**. If there are sound input msg from driver `apollo::drivers::microphone::config::AudioData` there is an output msg `/apollo/audio/audio_detection`

**Comment by Capri2014** [comment]
Thanks for the discussion and interests, audio modules as of this release is just phase I of "Emergency Detection" projects, the module, used by itself only supports for single emergency vehicles, and detection only when the `siren` is on, and limits only to when below 20mph ambient wind speed.

**Comment by rongguodong** [comment]
@Capri2014 Thanks for clarification! That makes much sense. Waiting to see phase II soon. :)
