### ISSUE TITLE
Source code for training the prediction model

### ISSUE THREAD

**Issue by jyh0082007** [ApolloAuto/apollo#1268]
I am wondering whether the source code of training the model used to do evaluation will be open?
Now, the model is only available as bin format at **apollo/modules/prediction/data/mlp_vehicle_model.bin** . Is there a way to know how the model is trained. 

Thanks!

**Comment by jinghaomiao** [comment]
The training scripts are not open. Please fee free to compile your own features and labels to train your own model, and plug that into the evaluator_manager. Please refer to existing mlp_evaluator to write your own evaluator, and follow the instructions on https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_evaluator_in_prediction_module.md to activate your own evaluator.

**Comment by jinghaomiao** [comment]
@jyh0082007 we'll have the training scripts open in Apollo 2.0. Please be patient. :)

**Comment by linux-devil** [comment]
@jinghaomiao any updates on training scripts? is it open yet?
