### ISSUE TITLE
How to "visualize" /apollo/sensor/microphone channel?

### ISSUE THREAD

**Issue by rongguodong** [ApolloAuto/apollo#12682]
I am interested in the newly added "audio" module in Apollo 6.0. Is it possible to play the content of `/apollo/sensor/microphone` in `cyber_visualizer`? It would be very helpful for developers.

I see there is a "tools" folder under "modules/audio". Can you add a README for that folder to explain how to use tools in it?

**Comment by Capri2014** [comment]
@Crysple We can not 'visualize' the sound but we provided a tool to dump it to wav format for verification. Please add a README for the tool.

**Comment by rongguodong** [comment]
Understood. In the future, if would be wonderful to improve `cyber_visualizer`, so that we can choose `/apollo/sensor/microphone`, and it can play the sound out in real time and maybe also draw the sound wave for each channel. :p

**Comment by Crysple** [comment]
I just created a pr for the README. This module maybe improved in the future. You can try that for now.
#12685
