### ISSUE TITLE
possible issue with "modules/planning/math/piecewise_jerk/piecewise_jerk_path_problem.cc"

### ISSUE THREAD

**Issue by xiaozhe90** [ApolloAuto/apollo#12692]
Hi,

It seems to me that in the file "modules/planning/math/piecewise_jerk/piecewise_jerk_path_problem.cc", line 84 / 85 should be "(-1.0 * weight_dddx_ / delta_s_square) /" after I derive the matrix myself (I believe you are trying to minimize x''' here from the variable x''). But Apollo put "(-2.0 * weight_dddx_ / delta_s_square) /" instead. Am I wrong? Or is this a mistake?

btw, I found Apollo is filling the lower triangle of the kernal matrix. However, according to the osqp's offical document, it ask for the upper triangle. Seems lower triangle works as well?

thanks

**Comment by zerolover** [comment]
Apollo used osqp 5.0, it accept both complete P matrix or just the upper triangular part, you can check https://github.com/oxfordcontrol/osqp/blob/master/CHANGELOG.md
At the version of 6.0, it requires P to be upper triangular.

**Comment by xiaozhe90** [comment]
> Apollo used osqp 5.0 which accepts both complete P matrix or just the upper triangular part.
> At the version of 6.0, it requires P to be upper triangular.
> You can check https://github.com/oxfordcontrol/osqp/blob/master/CHANGELOG.md

Hi @zerolover 

Thanks for your explaination. It seems make sense now. So they put -2 (instead of -1) to form a matrix (in complete form instead of the lower triangle of a symetic matrix) which can give the same quadratic form as the original symetric matrix?

**Comment by zerolover** [comment]
Yes, P is complete form

**Comment by xiaozhe90** [comment]
@zerolover ok, thanks a lot
