### ISSUE TITLE
如何将自己写的路径规划算法加到apollo里？

### ISSUE THREAD

**Issue by lisim51** [ApolloAuto/apollo#12695]
我们自己研究了一种局部路径规划算法，想用apollo的环境做一下仿真测试，请假一下如何入手？谢谢

**Comment by ntutangyun** [comment]
You could create a custom planner inheriting `PlanningBase` class.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
