### ISSUE TITLE
Build too slow

### ISSUE THREAD

**Issue by ArmstrongWall** [ApolloAuto/apollo#127]
I add code in source code, then I use Build modules step "bash apollo.sh build",It takes 30-40 seconds,too long time. Using Cmake and make just take several seconds to build project. I learn about appllo using bazel to build,It should more quick, Does it has some else way to bulid project.

**Comment by startcode** [comment]
It is easier for us to manage the code dependencies with bazel.
It is slow when you build everything for the first time. Later bazel will only build changed targets, and that will be faster.

**Comment by siyangy** [comment]
Bazel builds the project incrementally, which means if you change one file, only itself and its downstream dependency will be rebuilt. It's expected that the first build takes longer, but after a full build, it should be sped up significantly, as long as the previously built objects are still in bazel-cache. I am not sure why you mentioned 'Using CMake and make just take several seconds to build project.', apollo doesn't have CMake build system support at the moment.

**Comment by ArmstrongWall** [comment]
I am a postgraduate student learning Robots.I want to use Apollo to develop my double wheels robot to run on the road(my tutor project). But I use usb-serial to control chasis. Can I use serial instead of canbus? I have read code days, seems I can use a fake can device (serial),then complete send recv function, like add a new can card. Can I ?

**Comment by startcode** [comment]
Your idea makes sense to me. I guess you can create a class that implements the virtual CanClient class. You can implement this part of code in the Apollo framework following this guide https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_control_algorithm.md
