### ISSUE TITLE
Cannot find multicue_obstacle_transformer.cc logs under Perception log

### ISSUE THREAD

**Issue by Avps1** [ApolloAuto/apollo#12702]
### Steps to reproduce the issue:

Hi!
I need values like "Dimension hwl", "Bbox: " etc that can be obtained from the logs of multicue_obstacle_transformer.cc , because they are printed using ADEBUG or AINFO(full path - modules/perception/camera/lib/obstacle/transformer/multicue_obstacle_transformer.cc (see the attached snapshot).
![29thSept_scrn1](https://user-images.githubusercontent.com/50120641/94528980-712b8100-0239-11eb-9056-1b07a7e7deae.png)
![29thSept_scrn2](https://user-images.githubusercontent.com/50120641/94528991-738ddb00-0239-11eb-896b-8ff7409ea5cc.png)

The problem is, I cant find these values anywhere in the log, nor can I find any entry for the multicue_obstacle_transformer.cc in the perception log.
Could anyone kindly help me with this - How can I print these values or see them in the log ?

**Comment by daohu527** [comment]
The log config is below:

https://github.com/ApolloAuto/apollo/blob/38495c70c5a28a43630bee2c7950f16302f83690/cyber/setup.bash#L37-L46

## Level control
```
export GLOG_minloglevel=0
```
Log messages at or above this level. Again, the numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively.
So the log will output INFO/WARNING/ERROR/FATAL 

## Output to screen
```
export GLOG_alsologtostderr=0
```
Logs are written to standard error as well as to files.

## VLOG
If you use ADEBUG you should enbale "export GLOG_v=4 "
Enable V-leveled logging at the specified level.

**Comment by Avps1** [comment]
> The log config is below:
> 
> https://github.com/ApolloAuto/apollo/blob/38495c70c5a28a43630bee2c7950f16302f83690/cyber/setup.bash#L37-L46
> 
> ## Level control
> 
> ```
> export GLOG_minloglevel=0
> ```
> 
> Log messages at or above this level. Again, the numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively.
> So the log will output INFO/WARNING/ERROR/FATAL
> ## Output to screen
> 
> ```
> export GLOG_alsologtostderr=0
> ```
> 
> Logs are written to standard error as well as to files.
> ## VLOG
> 
> If you use ADEBUG you should enbale "export GLOG_v=4 "
> Enable V-leveled logging at the specified level.
> ## Run
> 
> Start the program with the following command
> 
> ```
> GLOG_v=4 GLOG_logtostderr=1 ./bazel-bin/modules/perception/xxx
> ```

@daohu527 First of all, thank you for your detailed response. Its really helpful. 
I have one question regarding the last step that you mentioned - "Start the program with the following command -` GLOG_v=4 GLOG_logtostderr=1 ./bazel-bin/modules/perception/xxx`
As i mentioned before, I want to see the logs of  modules/perception/camera/lib/obstacle/transformer/multicue_obstacle_transformer.cc or print the output of this file in the terminal.
Should i run `GLOG_v=4 GLOG_logtostderr=1 ./bazel-bin/modules/perception/camera/lib/obstacle/transformer/multicue_obstacle_transformer.cc` in the terminal ?  

This gives the following error : 
abhi@in_dev_docker:/apollo$ GLOG_v=4 GLOG_logtostderr=1 ./bazel-bin/modules/perception/camera/lib/obstacle/transformer/multicue_obstacle_transformer.cc
bash: ./bazel-bin/modules/perception/camera/lib/obstacle/transformer/multicue_obstacle_transformer.cc: No such file or directory
abhi@in_dev_docker:/apollo$ 

Then I did the following but it still did not help : 
![scrnsht1](https://user-images.githubusercontent.com/50120641/94991476-b32f2c80-0583-11eb-88ad-59b799ca7f73.png)

**Comment by Avps1** [comment]
Thank you very much for your support. I close the issue now.
