### ISSUE TITLE
Can apollo  support more than 2 cameras.

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#12700]
When we try to use 5 cameras in apollo
,we found apollo code will check the number
 of cameras to be fusioned. If more than 2 cameras to make fusion, it will return false. So can apollo support 5 or more cameras?

**Comment by lucasnmatias** [comment]
I'm also interested on this, in the documentation it's said that we can use up to 5 cameras, but when we run it it says that more than 2 cameras is not supported. How can we use 5 cameras?

**Comment by oska874** [comment]
> I'm also interested on this, in the documentation it's said that we can use up to 5 cameras, but when we run it it says that more than 2 cameras is not supported. How can we use 5 cameras?

Can you run apollo with only one camera?

**Comment by Capri2014** [comment]
> I'm also interested on this, in the documentation it's said that we can use up to 5 cameras, but when we run it it says that more than 2 cameras is not supported. How can we use 5 cameras?

You need ASU (Apollo Sensor Unit) to support 5 cameras.
