### ISSUE TITLE
Problems with traffic light detection

### ISSUE THREAD

**Issue by ucmar17** [ApolloAuto/apollo#12705]
When I am trying to detect traffic light in the Cubetown simulator, it keeps detecting the yellow and red lights as green light, and I am not sure why Apollo does that. The simulator version I am running is 2020.06 and building it using Unity 2019.3.15f1. The Apollo version I am using is the lgsvl/apollo-5.0 fork which I built from source. 

However, when I run the simulator with the Borregas Avenue map, the traffic light detection seems to work perfectly fine. Does anyone else have/had this problem and some ideas on how to solve it?

OS Platform and Distribution: Linux Ubuntu 18.04
Apollo installed from: source
Apollo version (3.5, 5.0, 5.5, 6.0): 5.0

**Comment by Manoj-EK** [comment]
@ucmar17 you can look at the issue   #12998 .............it might help
