### ISSUE TITLE
Adding ultrasonic sensor for D-kit

### ISSUE THREAD

**Issue by oscarlimhk** [ApolloAuto/apollo#12703]
I'm trying to add ultrasonic sensors to D-kit for emergency braking. The sensors data can be transferred to apollo through CANBUS communication.
However, it seems the guardian module cannot work properly on D-kit with the monitored components (even I have accurate localization solution, GNSS status is still showing error), and thus I temporarily comment all the code after this line:
https://github.com/ApolloAuto/apollo/blob/31c823a44327f89ac4606933f5a271136e2107e5/modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt#L92
After this, I can use the ultrasonic sensor data as another condition to enter safety mode for braking the vehicle.
The problem is the ultrasonic module output a wrong detection result (such as minimum detection range) in every 5 - 10 seconds, which makes the vehicle cannot run smoothly.

Since I found a head file of kalman filter in apollo, my idea is applying it to ignore the sudden change of detection result.
https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/common/math/kalman_filter.h

Could anyone give me an example how to use this head file to apply filter to my sensor data or any other idea for solving this problem will be highly appreciated.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
