### ISSUE TITLE
how can i get a hdmap with apollo,our team have only a hesai 40p lidar,can we use this lidar to get data and upload to you

### ISSUE THREAD

**Issue by w634307272** [ApolloAuto/apollo#12719]
我们团队在做一个封闭园区的自动泊车项目，项目中需要高精度地图支持，想通过apollo进行建图，但是目前手里只有一个hesai40p，用这个激光雷达可以采集数据包并上传给百度官方进行制图么？

**Comment by w634307272** [comment]
Our team is working on an automatic parking project in a closed park. The project requires high-precision map support. I want to build maps through apollo, but currently there is only one hesai40p in hand. With this lidar, can data packets be collected and uploaded to Baidu's official website？

**Comment by ntutangyun** [comment]
hi, you need to contact Apollo and purchase their HD map production services.

**Comment by w634307272** [comment]
> hi, you need to contact Apollo and purchase their HD map production services.

thank you ！ Do you know jhow to contact Apollo? I sent an e-mail to the e-mail address wuzhenni01@baidu.com that mentioned in the map collection documents, but the e-mail address is now invalid.

**Comment by InterKnight** [comment]
Hi, same peoblem. Do you have any solution now?
Thank you!

**Comment by ntutangyun** [comment]
> > hi, you need to contact Apollo and purchase their HD map production services.
> 
> thank you ！ Do you know jhow to contact Apollo? I sent an e-mail to the e-mail address [wuzhenni01@baidu.com](mailto:wuzhenni01@baidu.com) that mentioned in the map collection documents, but the e-mail address is now invalid.

please contact wechat: apollo_xzs
