### ISSUE TITLE
Print values using the Python API

### ISSUE THREAD

**Issue by sbhttchryy** [ApolloAuto/apollo#12714]
Hello developers. Firstly, congratulations and thank you very much for this wonderful project. I have just started exploring this for a personal project of mine. My question is weirdly the same as #12712 with a small difference. I want to be able to do the same thing i.e. print values xmin(), ymin(), xmax() , ymax() defined under class BBox2D( ) using the Python API. Any pointers will be appreciated. Thank you very much once again.

**Comment by daohu527** [comment]
python protobuf api default implements the `__str__` method,  the `print` function/statement will give you a human-readable representation of the message.

[ref](https://stackoverflow.com/questions/33557965/print-human-friendly-protobuf-message)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
