### ISSUE TITLE
[Planning/Control] Emergency braking too soft

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12713]
OS: ubuntu 1804
Apollo: 6.0
LGSVL: release-2020.06

---

Hi team,

I encountered this scenario where Apollo needs to perform an emergency brake before entering the junction because the other vehicles waiting to cross suddenly drive forward. 

However, I noticed that the emergency braking is too soft which eventually leads to a collision.  

here's the [video](https://drive.google.com/file/d/1EcbUOoGjUaeZqQL8Vi2bd8AQS9oLsp8p/view?usp=sharing).  and here's a [cyber recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EdMStiAyf1NJkagT1BOS38IBIjUCKmzCxY_7sBCpObywIQ?e=yxpSHS)

I also tried to manually brake directly on the Simulator, right after I noticed the obstacles vehicles started to drive forward, to sort of simulating a human driver. 

Here's a [video](https://drive.google.com/file/d/1EUFhu4b18sbEqGXvk7G-qEiiEo2zz3SW/view?usp=sharing)

Clearly, if the vehicle brakes 100% right from the start, it should be able to avoid the collision later. 

I'm not sure if this is due to the planning module or control module, or if it's due to some configuration that the braking cannot reach 100% by all means. 

Please advice. Thanks.

**Comment by ntutangyun** [comment]
here's another [video](https://drive.google.com/file/d/1EdbO1kDEMkN7QvHmDfW9Rveouvl_i_RO/view?usp=sharing)

Note that in the video, the braking control output is set to 50% maximum, which is clearly not enough.

here's the [video](https://drive.google.com/file/d/1Eeokldb4Mt6CD3xBb5MyvgbCwMQfXn1g/view?usp=sharing) with manual full brake with down arrow keys for the simulator.

**Comment by randomacco** [comment]
Hi, I am trying to reproduce this issue by simply playing the cyber bag uploaded here. I am wondering whether you have made some modification on the map data since I found there are some mismatches between the cyber bag and the map data. I am wondering whether you can provide some more details which could help me resolve this issue. Thanks! And also thanks for sharing this interesting case!

Also the information of the map I used: I tried the SF map both from the docker image of LGSVL repo or directly download the map from LGSVL map store. 
![image](https://user-images.githubusercontent.com/86978656/167205922-6a7465a9-f42f-41a7-b321-9c9089b6ff1a.png)

**Comment by ntutangyun** [comment]
it's too long ago.. let' me see if i can find the map file...

**Comment by ntutangyun** [comment]
the map version here: 
https://github.com/lgsvl/apollo-5.0/tree/1b7a466ada5aa1d50a5684bd8885ccee11a71877/modules/map/data/san_francisco

is the closest that i could get...

I tried this hd map on apollo 7.0 version and there's still a little bit offset. 

But this issue has been not so serious. I think it might be due to the calibration or configuration of the control module. 

So gonna close this issue for now. :) thanks for the help anyway.

**Comment by yellinshadows** [comment]
@randomacco Hi, you mentioned that you reproduce this issue by simply playing the cyber bag uploaded here. Could you share how to reproduce a scenario by cyber bag? The original cyber bag link is not available now so I failed to figure it out by myself ... Thank you for your help in advance!
