### ISSUE TITLE
About the current Normal Distributions Transform (NDT) algorithms (implemented|supported|used|integrated) (by|in) Apollo. 

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12726]
Hi,

[Here](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/ndt-literature-review.html) gives a list of papers relating specifically to the NDT technique for point cloud scan matching.

It seems that the Semantic-Assisted 3D Normal Distributions Transform (SA-3DNDT) is the strongest and most promising NDT algorithm among them. I just want to know which NDT algorithm (implemented|supported|used|integrated) (by|in) Apollo currently?

Regards,
HY

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
