### ISSUE TITLE
[Planning] deadlock scenario still exits in 6.0

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#12724]
Hi team,

seems that the deadlock issue still exists (previous [issue](https://github.com/ApolloAuto/apollo/issues/11136)) in Apollo 6.0

[Video](https://drive.google.com/file/d/1GMZqRLDhaPXef7deYAiA1UoopBQn5K5z/view?usp=sharing)

[cyber recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EWw13j18HcNMk97QX9HTu_QB6Uo-IfmHjf6nryRxR8RVow?e=0LsfQu)

**Comment by jmtao** [comment]
@ntutangyun this is not supported in 6.0 yet.
