### ISSUE TITLE
how to identify real-time violation in CyberRT?

### ISSUE THREAD

**Issue by InitialDuan** [ApolloAuto/apollo#12722]
Hi guys,

since CyberRT owns the real-time ability, i am wondering how can i know whether a module has been executed in time and did not miss their deadline, so how can i identify the violation of real-time execution in CyberRT? Is there any existing CyberRT tools can realize that or people have to create extra nodes to observe the violation?

**Comment by ntutangyun** [comment]
is the monitor node doing this job?

**Comment by daohu527** [comment]
`ChannelMonitor` already realized this function. You can observe the delay result of the channel in dreamview.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
