### ISSUE TITLE
Planner Pad Message Stop / Resume Latch 

### ISSUE THREAD

**Issue by james-goin** [ApolloAuto/apollo#12725]
If a planner pad message to stop (DrivingAction::STOP) is sent, the vehicle successfully comes to a stop. If a resume (DrivingAction::RESUME_CRUISE) command is sent following this, the vehicle tends to not move and stay parked.  

This is due to it going into a ScenarioConfig::PARK_AND_GO scenario. When already on a path (in lane stop scenario), this gets stuck and cant plan a route about 70% of the time. We have tried this in multiple locations. We are currently using ScenarioConfig::LANE_FOLLOW scenario to avoid this for now.   

https://github.com/ApolloAuto/apollo/blob/f8bf127830ccc96f20f93414b11a78cd81c798c1/modules/planning/scenarios/scenario_manager.cc#L328-L354

**Comment by BatmanofZuhandArrgh** [comment]
Not related, but does anyone knows what "Pad Message" means? Pls help

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
