### ISSUE TITLE
5.5.0版本  apollo/modules/tools/navigator/navigator.py 

### ISSUE THREAD

**Issue by jiayisong** [ApolloAuto/apollo#12727]
5.5.0版本中  apollo/modules/tools/navigator/navigator.py 依然使用了rospy，似乎未更新到cyber_py？？希望更新一下

**Comment by storypku** [comment]
This script is rather old and is removed in Apollo 6.0. 
Does anyone need this?

**Comment by jiayisong** [comment]
导航模式的教程apollo/docs/technical_tutorial/navigation_mode_tutorial_cn.md 中使用了apollo/modules/tools/navigator/navigator.py  如果现在导航模式不需要这个脚本了的话，能否请更新一下导航模式的教程？？

**Comment by storypku** [comment]
> docs

Sorry for the inconvenience it caused you. I will ask the team to update the doc asap.

**Comment by HEUDapan** [comment]
希望能给个新版本使用啊，系统从3.0升级到5.5后，navigator.py 就不能用了，能否给操作一下，还需要继续使用@ storypku

**Comment by jp12AI** [comment]
@storypku  Do you have any update on the navigator.py script? All the other tools work for cyber_rt however, navigation.py is what is needed to send navigation line data to dreamview for navigation mode. Is there another way to send navigation line data. I saw other who are using newer apollo versions with navigation mode. Updating this script would be greatly apprecaited.  Any updates? Thank you

**Comment by jp12AI** [comment]
@storypku  UPDATE: I use rosbag extractor in 3.0 instead then I switch to 5.0 and then use the navigation.sh script to send line data after getting smoothed rosbag file from 3.0. Then it works. If these navigation mode tools could be updated that would be great. Seems like only slight modification is needed to make it all work correctly. Navigation mode only uses 3 cameras correct? Is it any different for 5.0?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
