### ISSUE TITLE
Planning module not buildable for aarch64

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#12728]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
We are trying to build planning module for aarch64 however error occurred due to libtorch.
Is there any plan to support building planning module for aarch64 or is is already supportable?

**Comment by storypku** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
> * **Apollo installed from (source or binary)**: source
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
> * **Output of `apollo.sh config` if on `master` branch**:
> 
> ### Steps to reproduce the issue:
> * **Please use bullet points and include as much details as possible**:
>   We are trying to build planning module for aarch64 however error occurred due to libtorch.
>   Is there any plan to support building planning module for aarch64 or is is already supportable?
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):

Currently, Apollo Development Docker is not ready for AArch64 yet. 
However, the team is working on this issue now. Once we are ready, we should let everyone updated.

**Comment by storypku** [comment]
BTW, can you please tell your platform about to run Apollo AArch64 ? Is it a Jetson TX2/Xavier, or something else ?

**Comment by younggam94** [comment]
Hi,

 

No, we don’t use Jetson TX2/Xavier.

We use a different platform and don’t have GPU.

 

Br,

Yunsoo

**Comment by oska874** [comment]
It's ok to build planning module under aarch64 platform with or without gpu. Post your build error.

**Comment by storypku** [comment]
Building planning on Xavier should be OK  in master HEAD. And this issue is going to be closed. Please feel free to create new issue  if you have other questions. 

Thanks for supporting Apollo.
