### ISSUE TITLE
[WARNING] No nvidia-driver found. CPU will be used.

### ISSUE THREAD

**Issue by mzl729** [ApolloAuto/apollo#12737]
when I do 'bash apollo.sh build',it something error:[WARNING] No nvidia-driver found. CPU will be used.i do many way to solved it, but it useless.i have no idea ,what shuold i do,
my friends, thanks

**Comment by ntutangyun** [comment]
have you installed the nvidia gpu driver and `nvidia-container-toolkit`

**Comment by lfcarol** [comment]
If you have GPU, check that the GPU driver is installed correctly.

**Comment by mzl729** [comment]
> If you have GPU, check that the GPU driver is installed correctly.
 Now I have installed GPU correctly, the NVIDIA version is 450.66, but i have anther question :[WARNING] Cannot access GPU from within container. Please install  latest Docker and NVIDIA Container Toolkit as described by: 
[WARNING]   https://github.com/NVIDIA/nvidia-docker/blob/master/README.md

I know i don't install the nvidia-container-toolkit,  because i false to install it
when i installed it,it occurred:错误:10 http://it-mirrors.evowise.com/ubuntu bionic-security InRelease                                                                                
  522  Origin Connection Time-out [IP: 104.22.5.179 80]

**Comment by mzl729** [comment]
> have you installed the nvidia gpu driver and `nvidia-container-toolkit`

I had installed nvidia gpu driver 450.66. I know i don't install the nvidia-container-toolkit, because i false to install it
when i installed it,it occurred:错误:10 http://it-mirrors.evowise.com/ubuntu bionic-security InRelease
522 Origin Connection Time-out[IP: 104.22.5.179 80]

**Comment by mzl729** [comment]
> have you installed the nvidia gpu driver and `nvidia-container-toolkit`

 nvidia gpu driver and `nvidia-container-toolkit' are two different thing, right?

**Comment by oska874** [comment]
try to install nvidia driver,docker without install apollo rt kernel.

**Comment by storypku** [comment]
> > have you installed the nvidia gpu driver and `nvidia-container-toolkit`
> 
> I had installed nvidia gpu driver 450.66. I know i don't install the nvidia-container-toolkit, because i false to install it
> when i installed it,it occurred:错误:10 http://it-mirrors.evowise.com/ubuntu bionic-security InRelease
> 522 Origin Connection Time-out[IP: 104.22.5.179 80]

This is a network issue, and you should resolve it first before you can use Apollo Docker containers in GPU mode. Thank you.
