### ISSUE TITLE
Is MSF broken in latest Apollo master?

### ISSUE THREAD

**Issue by rongguodong** [ApolloAuto/apollo#12736]
I see the default localization module in all Dreamview modes has been changed from MSF to RTK. For example:
https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/conf/hmi_modes/ipc1_mkz_standard_debug.pb.txt#L29
https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt#L41

Does it mean the MSF is not working now?

**Comment by tthhee** [comment]
no, if you need,  you can change the localization mode to MSF.

**Comment by storypku** [comment]
Hi @rongguodong , it seems that your issue is resolved. And I'm going to close this issue now. With you success in your new career.
