### ISSUE TITLE
adding a decider/optimizer to a planning scenario

### ISSUE THREAD

**Issue by MaisJamal** [ApolloAuto/apollo#12733]
I would like to write and test my own decider and optimizer to lane follow scenario in planning modules in order to test overtaking dynamic obstacles. 
I have tried to add it to tasks with an appropriate BUILD file, and I also added it as task_type in LANE_FOLLOW_DEFAULT_STAGE  but when building Apollo it's showing a building error.
I was wandering , is that the right way to add my own decider and call it successfully in planning code?

I have also one more question, can you please mention where exactly is it calling the tasks in scenario's stage?
As I have understood, the structure is as follows:
Public_road_planner --> scenario_manager --> Default scenario: LaneFollowScenario --> Create scenario(new LaneFollowScenario) --> New Lane Follow Stage --> Stage(Has many tasks) --> TaskFactory::Create task 
but I'm still missing the fact, that where is it calling function process() of each task.

I would appreciate any help or explanation you give.
P.s. Thanks for making this great platform open to all developers.

### System information

- **OS Platform and Distribution: Linux Ubuntu 20.04 
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

**Comment by daohu527** [comment]
For "LaneFollowScenario", it call tasks in "PlanOnReferenceLine".

https://github.com/ApolloAuto/apollo/blob/3711be4317b62fffa548f91cb383269d4cc25987/modules/planning/scenarios/lane_follow/lane_follow_stage.cc#L163-L168

**Comment by MaisJamal** [comment]
Thanks for the clear answer, I'm interested to know also please, how can I add my own decider, is the way I'm following correct?

**Comment by daohu527** [comment]
Here are some suggestions. If you have any questions, please feel free to discuss.

1. Add your own decider in "modules/planning/tasks/deciders"
2. Add config in "modules/planning/conf/scenario/lane_follow_config.pb.txt"
3. Add TaskType in "modules/planning/proto/planning_config.proto" 
4. Register your task in "TaskFactory::Init"

**Comment by MaisJamal** [comment]
I have followed your suggestions ... ,
  enum TaskType {
    //...
    MAIS_DECIDER = 29;
  };
  oneof task_config {
    // deciders
    MaisDeciderConfig mais_decider_config = 24;
  }
plus I have added my decider to dependencies of task_factory in BUILD file in planning/tasks.
But I'm getting the following error when I try to build , and the error is not fixed, can you please help me out?


ERROR: (10-09 12:19:06.930) /apollo/modules/planning/common/BUILD:270:1: Linking of rule '//modules/planning/common:frame_test' failed (Exit 1).
/usr/local/adolc/lib64/libadolc.so: undefined reference to `ColPack::BipartiteGraphPartialColoringInterface::GenerateSeedJacobian(double***, int*, int*, std::string, std::string)'
/usr/local/adolc/lib64/libadolc.so: undefined reference to `ColPack::GraphColoringInterface::GenerateSeedHessian_unmanaged(double***, int*, int*, std::string, std::string)'
/usr/local/adolc/lib64/libadolc.so: undefined reference to `ColPack::GraphColoringInterface::GenerateSeedHessian(double***, int*, int*, std::string, std::string)'
/usr/local/adolc/lib64/libadolc.so: undefined reference to `ColPack::BipartiteGraphPartialColoringInterface::GenerateSeedJacobian_unmanaged(double***, int*, int*, std::string, std::string)'

**Comment by daohu527** [comment]
Seems you add some functions in `ColPack`. Did you add the corresponding dependencies in the BUILD file? 

There is a link error means can't find the reference of the func.

**Comment by MaisJamal** [comment]
It's my mistake, I have installed libadolc2 , which caused the problem. I have uninstalled the library and now my decider works fine, and it is called by Apollo planning modules, thank you so much.
