### ISSUE TITLE
ModuleNotFoundError: No module named 'error'

### ISSUE THREAD

**Issue by mzl729** [ApolloAuto/apollo#12738]
when I do 'rosbag play -l ./docs/demo_guide/demo.bag',it something error:
Traceback (most recent call last):
  File "/apollo/third_party/ros/bin/rosbag", line 34, in <module>
    import rosbag
  File "/apollo/third_party/ros/lib/python2.7/dist-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/apollo/third_party/ros/lib/python2.7/dist-packages/rosbag/bag.py", line 51, in <module>
    import yaml
  File "/apollo/third_party/ros/lib/python2.7/dist-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'

i do many way to solved it, but it useless.i have no idea ,what shuold i do,
my friends, thanks

**Comment by daohu527** [comment]
Please at least indicate your apollo version and environment. Rosbag is no longer supported after apollo 3.5

**Comment by mzl729** [comment]
My apollo maybe the latest one apollo 6.0, I installed it recently. So if the rosbag cannot supported it, what else file can be opened in the Dreamview.

**Comment by daohu527** [comment]
Apollo use `record` file instead of `ros bag`. You can use 
```
python docs/demo_guide/record_helper.py demo_3.5.record
cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
```
Ref [link](https://github.com/ApolloAuto/apollo/blob/8145f9a570d3c3b99b6ac9e845f8af1beb9f12c3/docs/demo_guide/README_cn.md)

**Comment by mzl729** [comment]
> Apollo use `record` file instead of `ros bag`. You can use
> 
> ```
> python docs/demo_guide/record_helper.py demo_3.5.record
> cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
> ```
> 
> Ref [link](https://github.com/ApolloAuto/apollo/blob/8145f9a570d3c3b99b6ac9e845f8af1beb9f12c3/docs/demo_guide/README_cn.md)

**Comment by mzl729** [comment]
> > Apollo use `record` file instead of `ros bag`. You can use
> > ```
> > python docs/demo_guide/record_helper.py demo_3.5.record
> > cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
> > ```
> > 
> > 
> > Ref [link](https://github.com/ApolloAuto/apollo/blob/8145f9a570d3c3b99b6ac9e845f8af1beb9f12c3/docs/demo_guide/README_cn.md)

Dear friend, thank you so much. Now I can open it in the Dreamview.
