### ISSUE TITLE
Lane Detector Denseline network's output

### ISSUE THREAD

**Issue by JerrySciangula** [ApolloAuto/apollo#12747]
Hi everyone,

I'm a student at Scuola Superiore Sant'Anna in Pisa, Italy.

I'm trying to understand the output of the **Lane Detector Denseline** caffe model, in the perception module (https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/camera/models/lane_detector/denseline).

After the last layer (the conv_out layer), the network outputs a 9 x 96 x 96 tensor.  

Could anyone explain me what is it and how I can visualize the results?

**Comment by lishaohua01** [comment]
@JerrySciangula The 9-channel feature maps are further postprocessed to get the final results. For details you may refer to https://github.com/ApolloAuto/apollo/tree/master/modules/perception/camera/lib/lane/postprocessor/denseline

**Comment by JerrySciangula** [comment]
Ok thank you @lishaohua01
