### ISSUE TITLE
cyber_recorder  Could not create log file: Permission denied

### ISSUE THREAD

**Issue by wzkwzk123** [ApolloAuto/apollo#12746]
i have successfully installed apollo 5.5 and run : Could not create log file: cyber_recorder play -f /apollo/docs/demo_guide/demo_3.5.record --loop. but it returns :  Could not create log file: Permission denied.  When i run sudo cyber_recorder play -f /apollo/docs/demo_guide/demo_3.5.record --loop, it returns : sudo: cyber_recorder: command not found. How can i do?

**Comment by wzkwzk123** [comment]
Now, i have new question.

cyber_recorder: error while loading shared libraries: libfastcdr.so.1: cannot open shared object file: No such file or directory

**Comment by daohu527** [comment]
Try to initialize the environment first when entering docker, the libfastcdr.so is already install into the docker
```
source scripts/apollo_base.sh
```

**Comment by wzkwzk123** [comment]
when i run  cyber_recorder play -f /apollo/docs/demo_guide/demo_3.5.record --loop in docker environment, it still returns the error:  Could not create log file: Permission denied.

**Comment by daohu527** [comment]
Please modify the permissions of the apollo directory on the host.
```
sudo chown -R 1000:1000 /apollo
```

**Comment by wzkwzk123** [comment]
still return the same

> Please modify the permissions of the apollo directory on the host.
> 
> ```
> sudo chown -R 1000:1000 /apollo
> ```

still return the same error. what does the 1000:1000 mean? should i modify it?

**Comment by wzkwzk123** [comment]
Run --sudo chown -R 1000:1000 /apollo  -- in docker container environment. error solved. Thanks!!
