### ISSUE TITLE
open dreanmview

### ISSUE THREAD

**Issue by mzl729** [ApolloAuto/apollo#12751]
Hi friends.
Every time I open the dreamview, whether I have to do as follow:

bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh

./apollo.sh build

bash scripts/bootstrap.sh

python3 docs/demo_guide/record_helper.py demo_3.5.record
cyber_recorder play -f demo_3.5.record --loop

It cost me a lot of time to build it, do you have anther way to make dreamview easy to be open ?

**Comment by ntutangyun** [comment]
If you don't remove the built cache, you don't have to build every time you start the containers.

**Comment by mzl729** [comment]
> If you don't remove the built cache, you don't have to build every time you start the containers.

Ok, thank you very much.

**Comment by lj0919** [comment]
@mzl729 
1. bash docker/scripts/dev_start.sh at the first time，execute this script every once in a while

2../apollo.sh build at the first time
 There is no need to build apollo.sh if do not have any backend changes afterwards
