### ISSUE TITLE
Papers about the new E2E Mode or Hybrid Mode in planning

### ISSUE THREAD

**Issue by xiaozhe90** [ApolloAuto/apollo#12759]
Hi,

May I ask if there are any papers the apollo team recomends to read which can be helpful to understand the newly added E2E Mode or Hybrid Mode in planning?

thanks!

**Comment by ZiwenWan** [comment]
I am also curious about this. If there is no paper related to this, is there any document about the model?

**Comment by liouyx** [comment]
You can read about this [paper](https://arxiv.org/abs/1812.03079) for E2E Mode.

**Comment by jinghaomiao** [comment]
> I am also curious about this. If there is no paper related to this, is there any document about the model?

Thanks for your interest in Apollo. The idea came from the paper that @liouyx referred to, but we are not able to disclose too much details about model structure. We'll definitely let you know if the info can be made to public. 

This ticket is being closed. Please feel free to raise other issues, should you have any. Thank you for your support to Apollo.
