### ISSUE TITLE
No cyber monitor channel info on aarch64 platform

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#12761]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
After build with apollo.sh build_cpu on aarch64 platform, we run cyber monitor but couldn't see any channel info.
However we could see cyber monitor channel info with x86 platform, we launch cyber_monitor

In addition, tried to run setup on Dreamview, it didn't work properly.
Here is the mainboard log, could see lots of msg like "No HMIStatus was received"
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1013 13:20:06.310149 11783 scheduler_factory.cc:63] No sched conf found, use default conf.
I1013 13:20:06.338225 11860 processor.cc:42] processor_tid: 11860
I1013 13:20:06.343614 11862 processor.cc:42] processor_tid: 11862
I1013 13:20:06.345079 11863 processor.cc:42] processor_tid: 11863
I1013 13:20:06.346417 11864 processor.cc:42] processor_tid: 11864
I1013 13:20:06.347702 11865 processor.cc:42] processor_tid: 11865
I1013 13:20:06.348906 11866 processor.cc:42] processor_tid: 11866
I1013 13:20:06.350189 11868 processor.cc:42] processor_tid: 11868
I1013 13:20:06.351789 11869 processor.cc:42] processor_tid: 11869
I1013 13:20:06.352439 11870 processor.cc:42] processor_tid: 11870
I1013 13:20:06.354063 11872 processor.cc:42] processor_tid: 11872
I1013 13:20:06.358233 11876 processor.cc:42] processor_tid: 11876
I1013 13:20:06.359668 11879 processor.cc:42] processor_tid: 11879
I1013 13:20:06.360954 11880 processor.cc:42] processor_tid: 11880
I1013 13:20:06.362278 11881 processor.cc:42] processor_tid: 11881
I1013 13:20:06.364423 11882 processor.cc:42] processor_tid: 11882
I1013 13:20:06.365630 11883 processor.cc:42] processor_tid: 11883
I1013 13:20:06.368389 11783 init.cc:113] Register exit handle succ.
I1013 13:20:06.435165 11783 module_controller.cc:65] Start initialize dag: /apollo/modules/monitor/dag/monitor.dag
I1013 13:20:06.436000 11783 class_loader.cc:37] Begin LoadLibrary: /apollo/bazel-bin/modules/monitor/libmonitor.so
I1013 13:20:07.347242 11783 timer.cc:137] start timer [0]
I1013 13:20:07.852710 11919 scheduler.cc:55] create croutine: /internal/task0
I1013 13:20:07.855895 11919 scheduler.cc:55] create croutine: /internal/task1
I1013 13:20:07.856909 11919 scheduler.cc:55] create croutine: /internal/task2
I1013 13:20:07.857237 11919 scheduler.cc:55] create croutine: /internal/task3
I1013 13:20:07.857360 11919 scheduler.cc:55] create croutine: /internal/task4
I1013 13:20:07.857470 11919 scheduler.cc:55] create croutine: /internal/task5
I1013 13:20:07.857614 11919 scheduler.cc:55] create croutine: /internal/task6
I1013 13:20:07.857743 11919 scheduler.cc:55] create croutine: /internal/task7
I1013 13:20:07.857846 11919 scheduler.cc:55] create croutine: /internal/task8
I1013 13:20:07.857955 11919 scheduler.cc:55] create croutine: /internal/task9
I1013 13:20:07.858057 11919 scheduler.cc:55] create croutine: /internal/task10
I1013 13:20:07.858181 11919 scheduler.cc:55] create croutine: /internal/task11
I1013 13:20:07.858287 11919 scheduler.cc:55] create croutine: /internal/task12
I1013 13:20:07.858392 11919 scheduler.cc:55] create croutine: /internal/task13
I1013 13:20:07.858490 11919 scheduler.cc:55] create croutine: /internal/task14
I1013 13:20:07.858587 11919 scheduler.cc:55] create croutine: /internal/task15
W1013 13:20:07.863255 11919 rate.cc:96] Detect forward jumps in time
I1013 13:20:07.878255 11866 scheduler.cc:55] create croutine: monitor_/apollo/hmi/status
E1013 13:20:07.892388 11866 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:08.361491 11869 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:08.863502 11879 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:09.363525 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:09.863494 11880 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:10.363456 11868 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:10.863510 11860 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:11.363548 11883 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:11.863476 11860 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:12.363576 11880 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:12.863494 11862 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:13.363538 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:13.863463 11879 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:14.363478 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:14.863478 11860 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:15.363478 11862 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:15.863483 11860 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:16.363474 11862 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:16.863448 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:17.363523 11860 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:17.863483 11880 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:18.363514 11865 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:18.863505 11879 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:19.363400 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:19.863559 11862 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:20.363462 11879 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:20.863569 11880 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:21.363499 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:21.863554 11876 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:22.363487 11880 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:22.863570 11866 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:23.363569 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:23.863485 11880 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:24.363533 11865 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:24.863487 11872 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:25.363541 11866 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:25.863483 11879 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:26.363481 11868 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:26.863539 11865 monitor_manager.cc:52] No HMIStatus was received.
E1013 13:20:27.364100 11879 monitor_manager.cc:52] No HMIStatus was received.
W1013 13:20:27.367861 11919 rate.cc:96] Detect forward jumps in time
E1013 13:20:27.866706 11866 monitor_manager.cc:52] No HMIStatus was received.
W1013 13:20:27.869680 11919 rate.cc:96] Detect forward jumps in time
W1013 13:20:27.869976 11919 rate.cc:96] Detect forward jumps in time
E1013 13:20:28.362707 11880 monitor_manager.cc:52] No HMIStatus was received.
W1013 13:20:28.365656 11919 rate.cc:96] Detect forward jumps in time
W1013 13:20:28.365849 11919 rate.cc:96] Detect forward jumps in time
E1013 13:20:28.862758 11882 monitor_manager.cc:52] No HMIStatus was received.
W1013 13:20:28.865278 11919 rate.cc:96] Detect forward jumps in time
E1013 13:20:29.362699 11876 monitor_manager.cc:52] No HMIStatus was received.
W1013 13:20:29.365859 11919 rate.cc:96] Detect forward jumps in time
E1013 13:20:29.864784 11866 monitor_manager.cc:52] No HMIStatus was received.

It looks like that communication was not established properly.
Is this issue related with fast-rtps?
We were told that fast-rtps has some problems for aarch64.

**Comment by daohu527** [comment]
If you are not running across physical machines, cyber just uses shared memory for communication. So I don't think this is a problem for fastrtps.

Can you observe and provide more information?

**Comment by younggam94** [comment]
Thx for your comment:-). we will check it.

For your information, we built an apollo on arm64 container on top of x86 machine and run cyber monitor.
Do you think that this is a problem?
Cross compile doesn't work?

One question, we build an apollo with arm64 container on top of x86 machine and copy all libs which is required apollo module into arm64 machine and run apollo. 
Apollo can work with this use case?

**Comment by daohu527** [comment]
Can you show your gcc version in docker?
```
gcc -v
```

**Comment by younggam94** [comment]
gcc version is 7.5.0 in the docker.

**Comment by daohu527** [comment]
Could you pls print the whole info

**Comment by younggam94** [comment]
Here we go.
[yschung@in-dev-docker:/apollo]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)

**Comment by daohu527** [comment]
I don't have ideas about cross-compilation problem for now, so I suggest you check the log to see if there is more information

**Comment by younggam94** [comment]
Regarding cyber_monitor issue, which logs should I check? Do you have any idea?

**Comment by daohu527** [comment]
my suggestion is
1. Use the sample "cyber\examples\talker.cc" and "cyber\examples\listener.cc" to ensure can't receive messages.
2. If still can't receive msgs try to find some error msg in mainborad.INFO

**Comment by younggam94** [comment]
Thx for your input.

Checked talker and listener.
When I had a test, couldn't find any mainboard.INFO.

My test step.
Step 1. run talker
Step 2. run listener

Talker log
Log file created at: 2020/10/15 09:30:44
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1015 09:30:44.221801 17400 global_data.cc:153] host ip: 192.168.10.31
W1015 09:30:44.278313 17400 scheduler_factory.cc:63] No sched conf found, use default conf.
I1015 09:30:44.286744 17404 processor.cc:42] processor_tid: 17404
I1015 09:30:44.289849 17405 processor.cc:42] processor_tid: 17405
I1015 09:30:44.291539 17406 processor.cc:42] processor_tid: 17406
I1015 09:30:44.292129 17407 processor.cc:42] processor_tid: 17407
I1015 09:30:44.293061 17408 processor.cc:42] processor_tid: 17408
I1015 09:30:44.294042 17409 processor.cc:42] processor_tid: 17409
I1015 09:30:44.294667 17410 processor.cc:42] processor_tid: 17410
I1015 09:30:44.295504 17411 processor.cc:42] processor_tid: 17411
I1015 09:30:44.296382 17412 processor.cc:42] processor_tid: 17412
I1015 09:30:44.297646 17413 processor.cc:42] processor_tid: 17413
I1015 09:30:44.298421 17414 processor.cc:42] processor_tid: 17414
I1015 09:30:44.299028 17415 processor.cc:42] processor_tid: 17415
I1015 09:30:44.300446 17416 processor.cc:42] processor_tid: 17416
I1015 09:30:44.301184 17417 processor.cc:42] processor_tid: 17417
I1015 09:30:44.301800 17418 processor.cc:42] processor_tid: 17418
I1015 09:30:44.302968 17419 processor.cc:42] processor_tid: 17419
I1015 09:30:44.305274 17400 init.cc:113] Register exit handle succ.
I1015 09:30:44.416141 17400 talker.cc:43] talker sent a message! No. 0
I1015 09:30:45.416399 17400 talker.cc:43] talker sent a message! No. 1
I1015 09:30:46.414901 17400 talker.cc:43] talker sent a message! No. 2
I1015 09:30:47.414952 17400 talker.cc:43] talker sent a message! No. 3
I1015 09:30:48.414937 17400 talker.cc:43] talker sent a message! No. 4
I1015 09:30:49.414943 17400 talker.cc:43] talker sent a message! No. 5
I1015 09:30:50.414965 17400 talker.cc:43] talker sent a message! No. 6
I1015 09:30:51.414912 17400 talker.cc:43] talker sent a message! No. 7
I1015 09:30:52.414950 17400 talker.cc:43] talker sent a message! No. 8
I1015 09:30:53.414894 17400 talker.cc:43] talker sent a message! No. 9
I1015 09:30:54.414960 17400 talker.cc:43] talker sent a message! No. 10
I1015 09:30:55.414888 17400 talker.cc:43] talker sent a message! No. 11
I1015 09:30:56.414906 17400 talker.cc:43] talker sent a message! No. 12
I1015 09:30:57.414965 17400 talker.cc:43] talker sent a message! No. 13
I1015 09:30:58.414959 17400 talker.cc:43] talker sent a message! No. 14
I1015 09:30:59.414875 17400 talker.cc:43] talker sent a message! No. 15
I1015 09:31:00.414963 17400 talker.cc:43] talker sent a message! No. 16
I1015 09:31:01.414921 17400 talker.cc:43] talker sent a message! No. 17
I1015 09:31:02.414955 17400 talker.cc:43] talker sent a message! No. 18
I1015 09:31:03.414945 17400 talker.cc:43] talker sent a message! No. 19
I1015 09:31:04.414911 17400 talker.cc:43] talker sent a message! No. 20
I1015 09:31:05.414896 17400 talker.cc:43] talker sent a message! No. 21
I1015 09:31:06.414896 17400 talker.cc:43] talker sent a message! No. 22
I1015 09:31:07.414953 17400 talker.cc:43] talker sent a message! No. 23
I1015 09:31:08.414950 17400 talker.cc:43] talker sent a message! No. 24
I1015 09:31:09.414903 17400 talker.cc:43] talker sent a message! No. 25
I1015 09:31:10.414952 17400 talker.cc:43] talker sent a message! No. 26
I1015 09:31:11.414954 17400 talker.cc:43] talker sent a message! No. 27

listener log
Log file created at: 2020/10/15 09:31:43
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1015 09:31:43.466289 17809 global_data.cc:153] host ip: 192.168.10.31
W1015 09:31:43.522676 17809 scheduler_factory.cc:63] No sched conf found, use default conf.
I1015 09:31:43.531294 17820 processor.cc:42] processor_tid: 17820
I1015 09:31:43.533795 17821 processor.cc:42] processor_tid: 17821
I1015 09:31:43.535776 17822 processor.cc:42] processor_tid: 17822
I1015 09:31:43.536972 17823 processor.cc:42] processor_tid: 17823
I1015 09:31:43.538237 17824 processor.cc:42] processor_tid: 17824
I1015 09:31:43.539523 17825 processor.cc:42] processor_tid: 17825
I1015 09:31:43.540091 17826 processor.cc:42] processor_tid: 17826
I1015 09:31:43.540760 17827 processor.cc:42] processor_tid: 17827
I1015 09:31:43.542351 17828 processor.cc:42] processor_tid: 17828
I1015 09:31:43.543697 17829 processor.cc:42] processor_tid: 17829
I1015 09:31:43.544430 17830 processor.cc:42] processor_tid: 17830
I1015 09:31:43.545033 17831 processor.cc:42] processor_tid: 17831
I1015 09:31:43.546715 17832 processor.cc:42] processor_tid: 17832
I1015 09:31:43.547336 17833 processor.cc:42] processor_tid: 17833
I1015 09:31:43.548130 17834 processor.cc:42] processor_tid: 17834
I1015 09:31:43.548754 17835 processor.cc:42] processor_tid: 17835
I1015 09:31:43.551106 17809 init.cc:113] Register exit handle succ.
I1015 09:31:43.649137 17809 scheduler.cc:55] create croutine: listener_channel/chatter


With this logs, couldn't find any clue what's going wrong.:-(
Any idea?

**Comment by daohu527** [comment]
There is too little prompt information, you can open the debug log.

1. modify the "apollo/cyber/setup.bash"
```
 # for DEBUG log 
 #export GLOG_minloglevel=-1   // DO NOT ENABLE THIS!!!
 export GLOG_v=4 
```  
2. Enable environment variables
```
source cyber/setup.bash
```

Then run the example and see the debug log

**Comment by storypku** [comment]
Running aarch64 CyberRT docker image on top of x86_64 host is not recommended or supported officially by the team.
Tested playing the demo_3.5.record on Xavier, and use cyber_monitor to observe, everything seems OK.

```
python3 docs/demo_guide/record_helper.py demo_3.5.record
cyber_recorder play -f demo_3.5.record --loop
# Another terminal
cyber_monitor
```

So this issue is going to be closed. Thanks for using Apollo.



> For your information, we built an apollo on arm64 container on top of x86 machine and run cyber monitor.
> Do you think that this is a problem?
> Cross compile doesn't work?
> 
> One question, we build an apollo with arm64 container on top of x86 machine and copy all libs which is required apollo module into arm64 machine and run apollo.
> Apollo can work with this use case?

**Comment by thymbahutymba** [comment]
@younggam94 did you have solved this?
