### ISSUE TITLE
Traffic light detection problems with lgsvl

### ISSUE THREAD

**Issue by hzssean** [ApolloAuto/apollo#12766]
When I am trying to detect traffic light in Borregas Ave map in lgsvl, it keeps detecting traffic lights even when I place a truck in front of the ego vehicle to block both the 6mm and 12mm camera. 
And there is no message in `apollo/perception/traffic_light` channel when I run the simulation in CubeTown map. But after I add HD map annotation `base_map.bin` under `modules/map/data/CubeTown`, the module keeps detecting traffic lights even I block the cameras. 

Does the traffic light detection module rely on the HD map annotation and does not consider the camera input at all?

The simulator version I am running is 2020.06. The Apollo version I am using is the master branch

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 16.04.6 LTS
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2020-10-12-7978438212
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200926_1057
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- I built the Apollo 6.0 from master branch and run ./scripts/bootstrap_lgsvl.sh in the docker
- In the DreamView, I chose Mkz Lgsvl mode, Lincoln2017MKZ (Apollo 5.0) vehicle and Borregas Ave map

### Supporting materials (screenshots, command lines, code/script snippets):
normal traffic light detection
![1602548068 6444106 jpg](https://user-images.githubusercontent.com/1497027/95903928-a8c31e80-0d4b-11eb-9360-a5f2f991e7d9.png)
after blocking the cameras
![1602548068 7944105 jpg](https://user-images.githubusercontent.com/1497027/95903939-ac56a580-0d4b-11eb-8940-a15e6ac9f5fb.png)

**Comment by ntutangyun** [comment]
Hi, are u using lgsvl's groundtruth traffic light sensor ? 

The groundtruth sensor does not use the camera images to detect. It will always produce the output when there are traffic lights nearby. 

If not using the groundtruth sensor, the Apollo's traffic light module might have projected the groundtruth location of the signals onto the camera images. 

Thus it can search for the signals smaller region instead of the whole image.

**Comment by hzssean** [comment]
Thank you for the reply.
> are u using lgsvl's groundtruth traffic light sensor ?

I don't think I am using lgsvl's groundtruth traffic light sensor. My vehicle does not have "Signal Sensor" (Topic: /simulator/ground_truth/signals)  included. 
The vehicle is just publishing Main Camera (Topic: /apollo/sensor/camera/front_6mm/image/compressed) and Telephoto Camera to Apollo (Topic: /apollo/sensor/camera/front_12mm/image/compressed). 

> If not using the groundtruth sensor, the Apollo's traffic light module might have projected the groundtruth location of the signals onto the camera images.
> 
> Thus it can search for the signals smaller region instead of the whole image.

So the TrafficLightBox messages (in particular, `traffic_light_debug.projected_roi ` and `traffic_light_debug.rectified_roi`) from `/apollo/perception/traffic_light` channel are the location on the camera images, right? But I find these messages unchanged all the time (not matter the cameras can see the traffic lights or not).

**Comment by daohu527** [comment]
There is do traffic light info in hdmap, apollo will use this info(box) as a ROI. like below in base_map

But I wonder how do you draw the box in simulation, use what info to draw the box?
```
signal {
  id {
    id: "signal_0"
  }
  boundary {
    point {
      x: 587039.2205619812
      y: 4141593.0089969635
      z: 5.893528938293457
    }
    point {
      x: 587039.349533081
      y: 4141593.4983654022
      z: 5.893528938293457
    }
    point {
      x: 587039.349533081
      y: 4141593.4983654022
      z: 4.707310676574707
    }
    point {
      x: 587039.2205619812
      y: 4141593.0089969635
      z: 4.707310676574707
    }
  }
  subsignal {
    id {
      id: "0"
    }
    type: CIRCLE
    location {
      x: 587039.28505134583
      y: 4141593.2536811829
      z: 5.7004199028015137
    }
  }

```

**Comment by xiaoMrzhang** [comment]
Hi, I will try to answer this question.Apollo perception module can get the approximate position of the traffic light by Hdmap, and we crop the patch of ROI then put it to our CNN model to do detection & recognition. So if Hdmap has label of traffic light but CNN can't detection bounding box, we will show the Hdmap roi region as bounding box and traffic light recognized as UNKONWN.

**Comment by hzssean** [comment]
@daohu527 I use the TrafficLightBox message in traffic_light_debug to draw the box over the camera-captured images.

**Comment by hzssean** [comment]
@xiaoMrzhang 

> So if Hdmap has label of traffic light but CNN can't detection bounding box, we will show the Hdmap roi region as bounding box and traffic light recognized as UNKONWN.

Thank you so much. This helps a lot.

**Comment by Thinsheep** [comment]
Hi @hzssean @daohu527 @xiaoMrzhang @ntutangyun @hugomatic 
To running Apollo 6.0
What does it mean by " NVIDIA Turing GPU is strongly recommended"? Will RTX 3080/3090 (not Turing Architecture) are also good and do a better job than RTX 2080/2080 Ti? I saw other comments that said the faster GPU the better. 
If anyone knows the answer please help. I need to order a PC for my project (Apollo 6.0 + a Simulator). 
Thank you.
