### ISSUE TITLE
Differences between replaying record on Apollo 5.0 and 5.5

### ISSUE THREAD

**Issue by lucasnmatias** [ApolloAuto/apollo#12774]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0 and 5.5

So I have been working with Apollo 5.5 to work with camera and lidar perception, but also I have made some tests with Apollo 5.0 due to the LGSVL support for this version.

The issue that we are facing now is this, we have installed the sensors on a car with Apollo 5.5 and collected data using cyber_recorder. Them, since we had already configured the perception on Apollo 5.0, we tested the Apollo 5.5 recorded data on Apollo 5.0 and it worked perfectly. However, now we are trying to run the perception on Apollo 5.5 with the same recorded data and it crashes throwing this error:

`[mainboard]Can not find transform. 611.007 frame_id: world child_Frame_id: novatel Error info: Lookup would require extrapolation into the past.    Requested time 611006679000 but the earliest data is at time 160207367829999872, when looking up transform from frame [novatel] to frame [world]`

We would like to know how to overcome this error, and if there is a difference between the way that Apollo 5.5 and Apollo 5.0 deals with recorded data, because we have used exactly the same configuration and it worked on Apollo 5.0 but not on Apollo 5.5. The strangest part is that the data was recorded on Apollo 5.5, so it would be reasonable to crash on Apollo 5.0, but on Apollo 5.0 it works normally but crashes when running on Apollo 5.5.

**Comment by daohu527** [comment]
Judging from the error message, I suggest you deal with the time issue first. I found the two timestamp are not right.
```
611006679000 unit is Nanosecond？
160207367829999872 unit is Nanosecond？
```
160207367829999872 / 1e9 = 160,207,367 seems `160,207,3678` is more reasonable to `October 7, 2020 12:27:58 PM`

So, should we start from here?
