### ISSUE TITLE
Failed to build cyber image

### ISSUE THREAD

**Issue by BH1SCW** [ApolloAuto/apollo#12776]
when I try to build docker image by command:

sudo ./build_cyber.sh -f cyber.x86_64.dockerfile -m build

I got some error message as follow:

Get:25 http://us.archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Get:26 http://us.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Get:21 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages [334 kB]
Err:21 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages
  File has unexpected size (333940 != 334425). Mirror sync in progress? [IP: 60.222.11.11 443]
  Hashes of expected file:
   - Filesize:334425 [weak]
   - SHA256:368427dc3efc0befcdbcfc3927728878cde0066efea00e53edf3f126775c8149
   - SHA1:c41f40486a99db57667aafbdf2625d9930b42067 [weak]
   - MD5Sum:39e1a1818947e57e167e4f8fd4916e0b [weak]
  Release file created at: Fri, 09 Oct 2020 01:21:10 +0000
Fetched 21.3 MB in 6s (3343 kB/s)
Reading package lists...
E: Failed to fetch https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (333940 != 334425). Mirror sync in progress? [IP: 60.222.11.11 443]
   Hashes of expected file:
    - Filesize:334425 [weak]
    - SHA256:368427dc3efc0befcdbcfc3927728878cde0066efea00e53edf3f126775c8149
    - SHA1:c41f40486a99db57667aafbdf2625d9930b42067 [weak]
    - MD5Sum:39e1a1818947e57e167e4f8fd4916e0b [weak]
   Release file created at: Fri, 09 Oct 2020 01:21:10 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c bash /tmp/installers/install_cyber_deps.sh' returned a non-zero code: 100

**Comment by storypku** [comment]
Please pull the master HEAD to bypass the issue. It was caused by developer.download.nvidia.com redirect in some regions including China.  If you google "developer.download.nvidia Packages File has unexpected size Mirror sync in progress", a lot of similar cases (e.g. https://github.com/NVIDIA/nvidia-docker/issues/877) were reported. So to avoid this, we prebuilt TensorRT and other CUDA libraries before CyberRT images in PR  #12683 。

**Comment by storypku** [comment]
Hope my answer helps. And This issue is going to be closed. If you have other questions, please feel free to create another issue.
