### ISSUE TITLE
Cyber_Visualizer can not work on Apollo 6.0

### ISSUE THREAD

**Issue by CrazyTomX** [ApolloAuto/apollo#12770]
System: Ubuntu 16.04

Hi, I just download the latest version of Apollo 6.0 which is uploaded on 10.13. I just build the cyber module with the command 
```
./apollo.sh build cyber
```
It builds successfully. But when I execute the cyber_visualizer command, the following errors shows:
![image](https://user-images.githubusercontent.com/32247692/95950565-5eaf6b00-0e27-11eb-84ee-1f78cdca5efa.png)

BTW, I have checked the previous issue about the cyber_visualizer and I found that the key word **graphics** has already been added in the dev_start.sh. So could anyone help me to solve this problem?

**Comment by storypku** [comment]
> System: Ubuntu 16.04
> 
> Hi, I just download the latest version of Apollo 6.0 which is uploaded on 10.13. I just build the cyber module with the command
> 
> ```
> ./apollo.sh build cyber
> ```
> 
> It builds successfully. But when I execute the cyber_visualizer command, the following errors shows:
> ![image](https://user-images.githubusercontent.com/32247692/95950565-5eaf6b00-0e27-11eb-84ee-1f78cdca5efa.png)
> 
> BTW, I have checked the previous issue about the cyber_visualizer and I found that the key word **graphics** has already been added in the dev_start.sh. So could anyone help me to solve this problem?

You can run `./apollo.sh clean --expunge` to remove bazel output and try rebuild cyber again.

The team have tested cyber_visualizer on Ubuntu 18.04 and Ubuntu 20.04, and cyber_visualizer works fine.  Maybe this issue is as a result of incompatibilities with Ubuntu 16.04.

**Comment by CrazyTomX** [comment]
Thanks for your reply. I wonder whether the graphic card will affect the cyber_visualizer or not? Can I use cyber_visualizer in a PC without GPU?

**Comment by storypku** [comment]
cyber_visualizer did have a dependency over QT and OpenGL library.  But I don't think the graphic card (hardware) can affect it.
Since cyber_visualizer has no dependency over CUDA/cuDNN/TensorRT, cyber_visualizer should be OK running on a PC or notebook without GPU.

> Thanks for your reply. I wonder whether the graphic card will affect the cyber_visualizer or not? Can I use cyber_visualizer in a PC without GPU?

**Comment by CrazyTomX** [comment]
Thanks for your reply. I've tried apollo6.0 on another 18.04 computer with graphic card and nvidia GPU driver 418. The same problem happened when I execute cyber_visualizer.
So is there any other method to let me see the point cloud? I online connect the LiDAR, I can see the message from cyber_monitor, I just want to see the point cloud to make sure the driver is correct. Can dreamview show out the point cloud?

**Comment by storypku** [comment]
> Thanks for your reply. I've tried apollo6.0 on another 18.04 computer with graphic card and nvidia GPU driver 418. The same problem happened when I execute cyber_visualizer.
> So is there any other method to let me see the point cloud? I online connect the LiDAR, I can see the message from cyber_monitor, I just want to see the point cloud to make sure the driver is correct. Can dreamview show out the point cloud?

Please update your Nvidia driver to 440.33+ as required by https://github.com/ApolloAuto/apollo#prerequisites to see if the problem persists.

**Comment by CrazyTomX** [comment]
I've updated driver to 440.95.01, with cuda version 10.2. And the problem persists.

**Comment by CrazyTomX** [comment]
Problem solved by installing nvidia-docker2.
