### ISSUE TITLE
[Doc][FuSa][ISO26262] Request for functional safety document

### ISSUE THREAD

**Issue by KyongsuLee** [ApolloAuto/apollo#12787]
Hi Apollo developers,

I am looking for the FuSa (such as Functional Safety, ISO26262) related document of Apollo, but I can't find it in the provided thing. 
In case of AUTOSAR, ' https://www.autosar.org/fileadmin/user_upload/standards/classic/4-3/AUTOSAR_EXP_FunctionalSafetyMeasures.pdf ' is provided.
Is it possible to provide some FuSa documentations like this?

[AUTOSAR_EXP_FunctionalSafetyMeasures.pdf](https://github.com/ApolloAuto/apollo/files/5389083/AUTOSAR_EXP_FunctionalSafetyMeasures.pdf)

**Comment by KyongsuLee** [comment]
Hi Guowei Wan,

How is this request going?

**Comment by daohu527** [comment]
@KyongsuLee Sorry, we are currently unable to provide relevant documents
