### ISSUE TITLE
"/opt/apollo/sysroot/include/opencv4") but this directory does not exist.

### ISSUE THREAD

**Issue by BH1SCW** [ApolloAuto/apollo#12804]
1 git pull to latest code.
2 bash docker/scripts/dev_start.sh  no error reported.
3 bash docker/scripts/dev_into.sh no error reported

[kong@in-dev-docker:/apollo]$ bazel clean
(06:39:36) INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
[kong@in-dev-docker:/apollo]$ bash apollo.sh build
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] No nvidia-driver found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: fj_v6.0_20200921-2020-10-18-33ed75acb
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200926_1057
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] No nvidia-driver found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview:
[INFO]     USE_GPU: 0  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=cpu
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/... except //modules/perception/... except //modules/planning/open_space/trajectory_smoother:planning_block except //modules/map/pnc_map:cuda_pnc_util except //modules/map/pnc_map:cuda_util_test
(06:40:47) WARNING: The following configs were expanded more than once: [cpu]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
(06:40:47) INFO: Current date is 2020-10-19
(06:40:49) ERROR: /apollo/modules/dreamview/backend/handlers/BUILD:20:11: //modules/dreamview/backend/handlers:image_handler depends on @opencv//:imgcodecs in repository @opencv which failed to fetch. no such package '@opencv//': The repository's path is "/opt/apollo/sysroot/include/opencv4" (absolute: "/opt/apollo/sysroot/include/opencv4") but this directory does not exist.
(06:40:49) ERROR: Analysis of target '//modules/dreamview/backend/handlers:image_handler' failed; build aborted: Analysis failed
(06:40:49) INFO: Elapsed time: 2.201s
(06:40:49) INFO: 0 processes.
(06:40:49) FAILED: Build did NOT complete successfully (535 packages loaded, 1339 targets configured)
    Fetching @com_google_glog; Restarting.

Actually the path is ok,
[kong@in-dev-docker:/apollo]$ ls /opt/apollo/sysroot/include/opencv4/
opencv2

Thanks
FJ

**Comment by storypku** [comment]
Remove bazel cache by running `./apollo.sh clean --bazel` and try again.

**Comment by BH1SCW** [comment]
> Remove bazel cache by running `./apollo.sh clean --bazel` and try again.

sorry,  this doesn't work.

**Comment by storypku** [comment]
> > Remove bazel cache by running `./apollo.sh clean --bazel` and try again.
> 
> sorry, this doesn't work.

What if removing `/apollo/.cache/bazel` and retry?

**Comment by BH1SCW** [comment]
Great!, problem solved!

Thanks
