### ISSUE TITLE
关于prediction模块中localization的困惑

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#1280]
这几天在看prediction模块代码，看到prediction模块订阅话题： /apollo/localization/pose，
然后在pose_container.cc文件中的PoseContainer::Update(const localization::LocalizationEstimate& localization)函数中有obstacle_ptr_->mutable_position()->CopyFrom(position);感觉这是将这个位置当成障碍物的位置，但是 /apollo/localization/pose话题中的位置应该是自动驾驶车辆的位置吧？不明白这里，望解答，谢谢。

**Comment by jinghaomiao** [comment]
我们可以这么看：主车（自动驾驶车）也是traffic中的一个部分，因此，如果我们在预测时，如果考虑车与车之间的相互关系的时候，那么障碍车与主车之间的关系，也是一种特殊类型的障碍车与障碍车之间的关系。主车的位置和状态，也会影响与它有关的其他障碍车的行为。所以我们把主车当成一个特殊的障碍物（id = -1）。借此，我们可以全局性得考虑整个traffic的布局。但是我们不对主车的行为进行预测。

**Comment by ahuer2435** [comment]
了解了，谢谢。

**Comment by ahuer2435** [comment]
了解了，谢谢。
