### ISSUE TITLE
cyber_recorder: command not found

### ISSUE THREAD

**Issue by DLsnowman** [ApolloAuto/apollo#12818]
### System information

ubuntu18.04
apollo installed from source
apollo version: 6

after run the command:  

 ./apollo.sh build_opt_gpu
 ./scripts/bootstrap.sh
 cd docs/demo_guide/
 python3 record_helper.py demo_3.5.record

i meet the issue:
 when i run the command: 
 
cyber_recorder play -f docs/demo_guide/demo_3.5.record -l

i get:
 **bash: cyber_recorder: command not found**
 
didn't I build apollo successfully?

**Comment by DLsnowman** [comment]
root@in-dev-docker:/apollo# ./apollo.sh config
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2020-10-20-174836325
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200926_1057
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

**Comment by DLsnowman** [comment]
(04:23:29) INFO: Elapsed time: 515.456s, Critical Path: 183.82s
(04:23:29) INFO: 11198 processes: 11198 local.
(04:23:29) INFO: Build completed successfully, 26117 total actions
==============================================
[ OK ] Done building apollo. Enjoy!
==============================================

**Comment by DLsnowman** [comment]
root@in-dev-docker:/apollo# nvidia-smi
Wed Oct 21 12:28:07 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 18%   28C    P8     7W / 250W |      6MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:D9:00.0 Off |                  N/A |
| 18%   27C    P8    21W / 250W |      6MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2459      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      2459      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

**Comment by DLsnowman** [comment]
so why do cyber_recorder command not found

**Comment by DLsnowman** [comment]
hhhhhhh,   
i solved it!
source scripts/apollo_base.sh

**Comment by duongnxptit** [comment]
> hhhhhhh,
> i solved it!
> source scripts/apollo_base.sh

Hi @DLsnowman, can you run record successful in Apollo 6? I followed guide but i cant run record demo.

**Comment by DLsnowman** [comment]
> > hhhhhhh,
> > i solved it!
> > source scripts/apollo_base.sh
> 
> Hi @DLsnowman, can you run record successful in Apollo 6? I followed guide but i cant run record demo.

after running: /source scripts/apollo_base.sh
I run record successfully. can you describe your problem more detail?
