### ISSUE TITLE
GDB debug using vscode

### ISSUE THREAD

**Issue by younggam94** [ApolloAuto/apollo#12813]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I would like to set breakpoint into the code while apollo is running. and want to check whether apollo hits breakpoint or not.
Going through issues, there is a doc which is how_to_build_and_debug_using_vscode.md but doesn't seem to be available anymore.

Can somebody help me out how to build and debug using vscode or other way?

**Comment by storypku** [comment]
Since building and debugging Apollo via IDEs is not part of the Apollo project, we removed VSCode related doc from our repository since Apollo 6.0.  As always,  community support (articles, blog posts, etc.) on this issue is appreciated.
