### ISSUE TITLE
Output meaning of the yolo_obstable_detector network

### ISSUE THREAD

**Issue by JerrySciangula** [ApolloAuto/apollo#12828]
Hi everyone,

I downloaded the [prototxt](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-r4-half/deploy.pt) and [caffemodel](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-r4-half/deploy.model) files related to the Yolo obstacle detector of the Perception module. 

I'm trying to run this network locally on my PC. I can successfully load the network using Pycaffe and get the outputs.

However, i cannot understand what this output represents. These are the outputs of the network:

> loc_pred           ---->	 output_shape (1, 50, 90, 64)
> obj_pred           ---->	 output_shape (1, 50, 90, 16)
> cls_pred           ---->	 output_shape (1, 50, 90, 128)
> ori_pred            ---->	 output_shape (1, 50, 90, 32)
> dim_pred          ---->	 output_shape (1, 50, 90, 48)
> brvis_pred        ---->	 output_shape (1, 50, 90, 16)
> brswt_pred       ---->	 output_shape (1, 50, 90, 16)
> ltvis_pred         ---->	 output_shape (1, 50, 90, 16)
> ltswt_pred        ---->	 output_shape (1, 50, 90, 16)
> rtvis_pred         ----> 	 output_shape (1, 50, 90, 16)
> rtswt_pred        ---->	 output_shape (1, 50, 90, 16)
> area_id_pred    ---->	 output_shape (1, 50, 90, 16, 4)
> vis_pred           ---->	 output_shape (1, 50, 1440, 4)
> cut_pred           ---->	 output_shape (1, 50, 90, 64)

Could anyone explain me what they mean and how I can visualize them? Or if there is some documentation about this network it would be nice to have a look at it.

**Comment by panfengsu** [comment]
Obstacle detection based camera model is multi task YOLO-3D.Apollo perception engineer shared the algorithm details which   can help you to understand the outputs in https://zhuanlan.zhihu.com/p/46488972.

**Comment by JerrySciangula** [comment]
Ok thank you very much for your reply, @panfengsu!

**Comment by tabaddor** [comment]
Is there an English version? I would also like to understand what the output of the network is.

**Comment by YCC-324** [comment]
@JerrySciangula Hello, have you understood the meaning of these outputs?
