### ISSUE TITLE
Force remove all containers when stop containers with dev_start.sh

### ISSUE THREAD

**Issue by kangjie-chen** [ApolloAuto/apollo#12827]
When I use the command `bash dev_start.sh stop`, it will stop and **remove** all the containers I built.

The reason is that:
There is a following "-f" when you call the `stop_all_apollo_containers_for_user` function, which means it will **remove** all the containers about apollo. I just want to stop all containers, and do not want to remove all of them. It's very confusing for me.

https://github.com/ApolloAuto/apollo/blob/f2fef8158f548399c0a309772639096c884c23e4/docker/scripts/dev_start.sh#L212

**Comment by ntutangyun** [comment]
@kangjie-chen Hi bro. is there anything you need to save inside the container? If not, why not just rm the container and later start new ones from the images

**Comment by kangjie-chen** [comment]
> @kangjie-chen Hi bro. is there anything you need to save inside the container? If not, why not just rm the container and later start new ones from the images

For now, I do not save data inside the containers, I'm fine with removing all the containers and starting new ones. But I think it's confusing since the meaning of option `stop` is different from all the previous versions (i.e., just stop containers). It's better to use a new option to stop and remove all the containers, and keep that the `stop` just stops containers.

**Comment by storypku** [comment]
> > @kangjie-chen Hi bro. is there anything you need to save inside the container? If not, why not just rm the container and later start new ones from the images
> 
> For now, I do not save data inside the containers, I'm fine with removing all the containers and starting new ones. But I think it's confusing since the meaning of option `stop` is different from all the previous versions (i.e., just stop containers). It's better to use a new option to stop and remove all the containers, and keep that the `stop` just stops containers.

Thanks for your opinion. On considering that we didn't provide a `dev_start.sh start/stop` pair of options and  stopped Apollo containers are rarely revisited later, to cleanup the host environment, I made that **breaking change**.  And I think it may be more natural if you think `dev_start.sh` as "start Apollo development environment", and thinks `dev_start.sh stop` as "stop Apollo development environment."

**Comment by kangjie-chen** [comment]
> > > @kangjie-chen Hi bro. is there anything you need to save inside the container? If not, why not just rm the container and later start new ones from the images
> > 
> > 
> > For now, I do not save data inside the containers, I'm fine with removing all the containers and starting new ones. But I think it's confusing since the meaning of option `stop` is different from all the previous versions (i.e., just stop containers). It's better to use a new option to stop and remove all the containers, and keep that the `stop` just stops containers.
> 
> Thanks for your opinion. On considering that we didn't provide a `dev_start.sh start/stop` pair of options and stopped Apollo containers are rarely revisited later, to cleanup the host environment, I made that **breaking change**. And I think it may be more natural if you think `dev_start.sh` as "start Apollo development environment", and thinks `dev_start.sh stop` as "stop Apollo development environment."

Thanks for your reply. Now I understood your breaking change and why you need to remove all the containers with the `stop` option in the latest version. And just in case that I want to keep the data in the containers (e.g., records), I tried to use `docker stop $(docker ps --filter "name=apollo")` to stop all the apollo containers but it stops and **removes** all the volume containers except the dev container. Is there a way to stop and restart all the containers?

**Comment by storypku** [comment]
Generally speaking, only two containers need to support "start/stop/restart" operations, and they are "apollo_dev_${USER}" and "apollo_cyber_${USER}". You can run `docker stop apollo_dev_${USER}` directly.

**Comment by kangjie-chen** [comment]
> Generally speaking, only two containers need to support "start/stop/restart" operations, and they are "apollo_dev_${USER}" and "apollo_cyber_${USER}". You can run `docker stop apollo_dev_${USER}` directly.

Thanks for your help!
