### ISSUE TITLE
Replay demo record in Apollo 6.0, vehicle don't run

### ISSUE THREAD

**Issue by duongnxptit** [ApolloAuto/apollo#12822]
**System information**
**- OS Platform and Distribution:** Linux Ubuntu 18.04
**- Apollo installed from source**
**- Apollo version 6.0**
**- Output of apollo.sh config if on master branch**

I have installed Apollo version 6.0. Without hardware, i just want replay demo record _demo_3.5.record_. Data on PNC Monitor run but my vehicle dont run, the map is same problem. Some one can help me? Thanks!

**Screen shot**
![issue](https://user-images.githubusercontent.com/48410671/96697008-9e40fe80-13b5-11eb-9835-7f997a0054b9.png)

**Comment by ntutangyun** [comment]
looks like the map is not loaded correctly.

**Comment by duongnxptit** [comment]
> looks like the map is not loaded correctly.

I followed guideline step by step. Can you tell me how to fix it?

**Comment by lj0919** [comment]
@duongnxptit  can you tell me your steps?

**Comment by storypku** [comment]
This issue was the same as that of #12739 , and was fixed in PR #12862 .

Thanks all for supporting Apollo, and we hope  better Apollo documentation could be provided in the near future.
