### ISSUE TITLE
Configuration file for scheduler

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#12820]
Hi, 
I'm trying to understand what represent these files ([1](https://github.com/ApolloAuto/apollo/blob/master/cyber/conf/control_sched_classic.conf) and [2](https://github.com/ApolloAuto/apollo/blob/master/cyber/conf/control_sched_choreography.conf)). They are the configuration files of the scheduler depending on the policy, but only for the control component? If yes, why only for this component? What represent this two tasks in the file? https://github.com/ApolloAuto/apollo/blob/ce01c4ceac66c4e2c3befc60f05da69f243c8aed/cyber/conf/control_sched_classic.conf#L12-L21

**Comment by daohu527** [comment]
It will create two tasks `planning` and `control`. and both conf will make sure planning and control have there own processor, which will not be preempted by other tasks.
