### ISSUE TITLE
help wanted: How to debug protobuf  in gdb？

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#12829]
when I use gdb in vs code,it is hard to watch variable in protobuf type.Is there any good ways to watch protobuf type variable ?

**Comment by daohu527** [comment]
Use the **chassis** msg as an example.
```
printf "%s\n", chassis.ShortDebugString().c_str()
```

**Comment by BigBenSure** [comment]
> Use the **chassis** msg as an example.
> 
> ```
> printf "%s\n", chassis.ShortDebugString().c_str()
> ```

Thank you for your reply.Is there any useful GDB debug extension in VS Code?

**Comment by daohu527** [comment]
I have no good suggestions for now. I often use log to debug!

**Comment by BigBenSure** [comment]
> I have no good suggestions for now. I often use log to debug!

AERROR print everything! hahahaha:100:

**Comment by storypku** [comment]
It seems that this issue has its solution and can be closed now. Thanks all for supporting Apollo!

**Comment by MartinLi123** [comment]
Have you found a better way to debug protobuf in GDB ?
