### ISSUE TITLE
Compile control module

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#12838]
Hi, is it possible to compile the control module independently using the g++ compiler? Or anyway there is a way to compile it standalone?

**Comment by daohu527** [comment]
```
bazel build modules/control:libcontrol_component.so
```

**Comment by storypku** [comment]
> Hi, is it possible to compile the control module independently using the g++ compiler? Or anyway there is a way to compile it standalone?

This can be done by running `./apollo.sh build control` or `./apollo.sh build_opt_gpu control`. See doc here:
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/apollo_build_and_test_explained.md

**Comment by cbldlpl** [comment]
mark cue
