### ISSUE TITLE
Publisher/Subscriber Docs update

### ISSUE THREAD

**Issue by yiakwy** [ApolloAuto/apollo#1283]
Hello,

Since apollo use ROS (a distributed computing environment) to set up modules. I am especially interested in Publisher/Subscriber framework.

What I know for the moment: When a subscriber (perception module) subscribes topics published by publisher (Velodyne Lidar), a peer 2 peer (p2p) L4 level connection will be constructed based on ip address recored by the master using socket or websocket. Each time topic is ready, a callback will be fired (using Linux event?).

in ApolloApp, ros::init , ros::spin will be called. Good. But where are subsribers? Simple search shows that “apollo::common::adaptor::InternalEnable” defines such behavior. But I cannot go further. I found our project has no document about. I wish someone will help me on this topic. Thanks!

During the research, I also noticed that Mobileye adaptor has been added into the apollo::common::adpator. Since Lidar is unrealistic for car manufacturers , I am especially interested in this solution.

If we adopt this solution which means a lot of work of Lidar points preprocessing (Kalman Filter ...) be deprecated, perception module  might need a huge change

**Comment by yiakwy** [comment]
Figure it out:

ApolloApp::main => spin =>submodules::init 

For example, if the ROS node is perception module, two subjects will be published(https://github.com/ApolloAuto/apollo/blob/master/modules/common/adapters/adapter_manager.cc#52) , a node will subscribe or advertise a topic.

**Comment by yiakwy** [comment]
I think we can publish a document on Publisher/Subscriber.

**Comment by Capri2014** [comment]
@yiakwy Could you help with that? You can submit it under https://github.com/ApolloAuto/apollo/tree/master/docs/howto, for instance, "how_to_use_Publisher/Subscriber.md" ?

**Comment by yiakwy** [comment]
@Capri2014  No problem!

**Comment by yiakwy** [comment]
@Capri2014 I have submit a patch, please review.

**Comment by Zhenni17** [comment]
@yiakwy thank you for your contribution! close the issue for now. Please re-open issue if there are more questions.

**Comment by yiakwy** [comment]
Get it.

2018-04-11 14:14 GMT+08:00 Zhenni Wu <notifications@github.com>:

**Comment by zuomaidi52** [comment]
@yiakwy ，Hi, I'm very interesting for your doc "how_to_use_Publisher/Subscriber.md" , but I could not find that in Apollo.
