### ISSUE TITLE
A bug of scripts/rtk_recorder.sh

### ISSUE THREAD

**Issue by lishuanghua** [ApolloAuto/apollo#12831]
**The garage.csv is in the wrong place**
In apollo r6.0.0 branch,the `garage.csv` which is produced by `scripts/rtk_recorder.sh` file is in the `/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/bin/modules/tools/record_play/rtk_recorder.runfiles/apollo/data/log/` folder,but it is not in the default place `/apollo/data/log/` folder which is expected by the `scripts/rtk_player` file. the relative pull request is [https://github.com/ApolloAuto/apollo/pull/12138](https://github.com/ApolloAuto/apollo/pull/12138)  @diegohu @storypku 

![Screenshot from 2020-10-21 22-03-14](https://user-images.githubusercontent.com/29296459/96738431-49bb7480-13f1-11eb-8240-10626dd94385.png)

**Comment by storypku** [comment]
This issue is fixed in PR #12841
