### ISSUE TITLE
No error handling added

### ISSUE THREAD

**Issue by gsa88** [ApolloAuto/apollo#12837]
https://github.com/ApolloAuto/apollo/blob/aab16153e9e96433c57ace7f4a4d7c82827e3857/modules/canbus/vehicle/vehicle_controller.cc#L120

This statement returns an error code, but there is no action if ERROR is returned.

**Comment by changsh726** [comment]
This issue is fixed in PR #12868 and thus will be closed. Be free to open new issues or pull requests if you still have other questions. Thanks for your contribution!
