### ISSUE TITLE
Can Apollo provide the libs' versions?

### ISSUE THREAD

**Issue by oska874** [ApolloAuto/apollo#12835]
I'm working on arm platform that need to run apollo5.5 without docker.Can Apollo provide the libs' version and source address.
Like protobuf,caffe,pytorch,vtk,qt,gtest,glog,and so on.

**Comment by storypku** [comment]
> I'm working on arm platform that need to run apollo5.5 without docker.Can Apollo provide the libs' version and source address.
> Like protobuf,caffe,pytorch,vtk,qt,gtest,glog,and so on.

The scripts used to build such packages are located under `docker/build/installers/`. You can use scripts there to get those information.
