### ISSUE TITLE
Camera and lidar data fusion on Apollo 5.5

### ISSUE THREAD

**Issue by romanodanilo** [ApolloAuto/apollo#12849]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5+ 

Hi,
We are working on Apollo 5.5 Perception feeding it with Camera and Lidar data.
Currently we see no major difference on `/apollo/perception/obstacles` topic between the detections using only Lidar and using Lidar + Camera together.
Do you know how to configure the Data Fusion in order to use both Camera and Lidar detections?
Is it possible to do that? How can I check that the two detections are both used?
We made the same test on Apollo 5.0 and we experienced the same results.
Thanks a lot

**Comment by daohu527** [comment]
According to the current function
#### camera

- lane detection
- traffic light detection
- obstacles detection

#### lidar, radar and v2x
- obstacles detection


## How to fusion

If you want to fusion lidar and camera for obstacles detection, I think you may need to do some work with `fusion_camera_detection_component` and `fusion_component`, fusion of two kinds of data, there are many fusion methods you can find in papers.   

In 6.0 I also found the `fusion_camera_detection_component.cc` is not add in `BUILD`

**Comment by lucasnmatias** [comment]
@daohu527 that is the point, on the `fusion_component` we saw that there are flags to configure the use of lidar, radar and cameras to fuse the data. The lidar detection publish data directly to `/apollo/perception/obstacles`, and the camera detection publish data to `/perception/obstacles`. However, when we run both modules and the `fusion_component` it doesn't recognize the camera detection output. We were able to plot the detected obstacles position and bounding box but the output from LiDAR only and Camera+LiDAR are exactly the same, so it doesn't seems to be using the camera detections.

For the 6.0 we have known from other issues that the camera module are being refactored in this version and it currently doesn't work on Apollo 6.0, probably that is why it's not being built.

**Comment by daohu527** [comment]
I can only provide insights into the existing code.

1. `fusion_component` 's input is `SensorFrameMessage` this is some raw data but not the result. So I can't understand how you subscribe the `/perception/obstacles` in `fusion_component`?
2. where did you found the flags of camera in `fusion_component`? I found that modules are missing or the logic is not very clear

I will read later in detail

**Comment by lucasnmatias** [comment]
1. We didn't changed the original [`.conf`](https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt#L10) file regarding the cameras. So in the original file we have two parameters `output_obstacles_channel_name: "/perception/obstacles"` ([here](https://github.com/ApolloAuto/apollo/blob/ec92f87120610fd360bba37d49aead7abed4d0b5/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt#L11)) and `prefused_channel_name: "/apollo/inner/PrefusedObjects"` ([here](https://github.com/ApolloAuto/apollo/blob/ec92f87120610fd360bba37d49aead7abed4d0b5/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt#L13)) which is the same as the LiDAR configuration for the `prefused_channel_name`. So as far as I could understand the `output_obstacles_channel_name` is the output for the camera detection only, while the `prefused_channel_name` is the input for the `fusion_component` ([here](https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/perception/production/dag/dag_streaming_perception.dag)):

> components {
>         class_name: "FusionComponent"
>     config {
>       name: "SensorFusion"
>       config_file_path: "/apollo/modules/perception/production/conf/perception/fusion/fusion_component_conf.pb.txt"
>       readers {
>           channel: "/perception/inner/PrefusedObjects"
>         } } }

2. We have been using the `ProbabilisticFusion` and [here](https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/perception/production/data/perception/fusion/probabilistic_fusion.pt) are these flags:

> use_lidar: true
use_radar: true
use_camera: true
tracker_method: "PbfTracker"
data_association_method: "HMAssociation"
gate_keeper_method: "PbfGatekeeper"
prohibition_sensors: "radar_front"
>
>max_lidar_invisible_period: 0.25
max_radar_invisible_period: 0.50
max_camera_invisible_period: 0.75
>
>max_cached_frame_num: 50

**Comment by daohu527** [comment]
The process you mentioned seems to be no problem, now there is only one problem left.

How did you start the modules, you know `prefused_channel_name ` is an inner message, so you should start them in the same thread, if not, they will can't receive the messages. General speaking, you should load them in one launch file.
```
prefused_channel_name : "/perception/inner/PrefusedObjects"   // inner channel
```

**Comment by lucasnmatias** [comment]
Yes, we are starting the lidar and camera perception modules in the same launch file but still the output is the same. We are plotting the detection position and draw the bounding box using the rotation (theta) and the length, width and height information, and there is no difference between the lidar only and lidar + camera outputs.

**Comment by lucasnmatias** [comment]
We are not using Radar data at the moment, so we are using only LiDAR and Camera data, this should be a problem? I don't think so because on the `ProbabilistFusion` configuration you can set the radar input flag to false.

**Comment by daohu527** [comment]
So your question is what role does the camera play when fusing perception? Especially in obstacles detection?

I may need more time to review the code before making suggestions

**Comment by lucasnmatias** [comment]
Yes exactly. I was expecting the camera perception to help the LiDAR to adjust the bounding box. I noticed that the obstacle position estimation is more precise on the LiDAR detection, but the bounding box estimation is usually better on camera detection, so I was expecting that the fusion would give a more reliable obstacle position and bounding box estimation.

**Comment by LuoXin0826** [comment]
Hi @lucasnmatias ,
Have you solved the problem? I'm trying to fuse camera and LiDAR prefusedObjects as well, but the association doesn't seem work appropriately. I noticed that in the [ReadMe](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md) file, it says that Camera obstacle detection is not available so far. Is there a way to enable the fusion?
Thanks!

**Comment by LiuHaolan** [comment]
@LuoXin0826 You can use Apollo-5.0, whose camera pipeline at least works. I could fuse the lidar and camera results in that version.

**Comment by LuoXin0826** [comment]
> @LuoXin0826 You can use Apollo-5.0, whose camera pipeline at least works. I could fuse the lidar and camera results in that version.

Thanks! I'll try with 5.0 version.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
