### ISSUE TITLE
The nonexistent website used by record_helper.py.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12842]
Hi,

I noticed that the [record_helper.py](https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/record_helper.py) use [a nonexistent website](https://github.com/ApolloAuto/apollo/releases/download) for constructing the demo files main URL.

OTOH, even the most recent version among these demo files are very archaic/stale compared to the current version of apollo, which we have discussed some time before.

Regards,
HY

**Comment by storypku** [comment]
> archaic/stale

Although the link you mentioned is non-reachable, it didn't harm that the urls for record files remains OK. 
And since Apollo record files didn't change format since Apollo 3.5, it is not archaic.

Thanks for your info and this issue is going to be closed.
