### ISSUE TITLE
reference demand. too hard to understand

### ISSUE THREAD

**Issue by HandsomeDragon3** [ApolloAuto/apollo#12847]
reference of :   ???
cos_theta_smoother
fem_pos_deviation_smoother
QpSplineSmoother
SpiralSmoother
3Q

**Comment by daohu527** [comment]
Please at least describe your problem clearly. I don't know what problem you want to solve through your description.

**Comment by HandsomeDragon3** [comment]
I would like make my path(anchor points acknowledged) smooth by smoothers.
I wish to know the basic theory of them in Apollo. Some papers or websites are expected.
Smoothers are illustrated forward ~
