### ISSUE TITLE
How to work with different driving modes?

### ISSUE THREAD

**Issue by gsa88** [ApolloAuto/apollo#12856]
According to the following snippet:
https://github.com/ApolloAuto/apollo/blob/c431f780f0e5bb23802333abce79e4b46c63b440/modules/canbus/vehicle/vehicle_controller.cc#L107
only COMPLETE_AUTO_DRIVE mode can be used. Maybe there should be read from the configuration file **canbus_conf.pb.txt**, smth like that:  `mode = params_.driving_mode();`

**Comment by daohu527** [comment]
I don't understand why you want to read from a file.
