### ISSUE TITLE
Setting the value of a private variable whose value is already equal to this value.

### ISSUE THREAD

**Issue by gsa88** [ApolloAuto/apollo#12851]
https://github.com/ApolloAuto/apollo/blob/5a0fb9bd0ada44f7ac35323e68e9232266ae6a9d/modules/canbus/vehicle/lincoln/lincoln_controller.cc#L309-L311

**Comment by daohu527** [comment]
`chassis_error_mask_` is a variables in class LincolnController and `chassis_` is another. There are different variables both in LincolnController. `chassis_` is an protobuf msg have a parameter chassis_error_mask set by `set_chassis_error_mask`, which is a protobuf generation method. 
https://github.com/ApolloAuto/apollo/blob/5a0fb9bd0ada44f7ac35323e68e9232266ae6a9d/modules/canbus/proto/chassis.proto#L105-L107

**Comment by gsa88** [comment]
Indeed, sorry to bother you
