### ISSUE TITLE
Perception Question: Why the LidarFrame->world_cloud is defined as PointD cloud instead of PointF cloud as LidarFrame->cloud?

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#12852]
This is simply a question. What are the reason behind? Thanks.

**Comment by jeroldchen** [comment]
@jilinzhou PointD for double data type and PointF for float. World cloud has a large range for coordinates' values while `LidarFrame->cloud` stores point cloud within a relatively small range of the lidar sensor.
Thank you for your interest in Apollo!

**Comment by jilinzhou** [comment]
thanks
