### ISSUE TITLE
dreamview中如何使用自己制作的高精度地图？未连接实车

### ISSUE THREAD

**Issue by lucky-fzy** [ApolloAuto/apollo#12850]
在未连接实车的情况下，想要使用dreamview查看制作好的高精地图需要如何操作呢

![image](https://user-images.githubusercontent.com/33357456/97078795-2840cf80-1621-11eb-93d1-81d6b1ad6ca9.png)

**Comment by HTL2018** [comment]
请问方便分享一下制作高精度地图的相关文件吗？

**Comment by lj0919** [comment]
@lucky-fzy  如果是关于如何加载自己的自制地图到dreamview，之前的一个issue[issue]给出过回答(https://github.com/ApolloAuto/apollo/issues/11253#issuecomment-651371463)
