### ISSUE TITLE
Typo in code generation

### ISSUE THREAD

**Issue by gsa88** [ApolloAuto/apollo#12857]
Please change AUTO_STEER_ONLY to AUTO_SPEED_ONLY
https://github.com/ApolloAuto/apollo/blob/c431f780f0e5bb23802333abce79e4b46c63b440/modules/tools/gen_vehicle_protocol/template/controller.cc.tpl#L206

It should be done in all vehicle_specific_controller (eg, modules/canbus/vehicle/lincoln/lincoln_controller.cc) files.

**Comment by storypku** [comment]
This issue is fixed in PR #12859 and thus will be closed. Thanks for your contribution!
