### ISSUE TITLE
jam at starting docker container

### ISSUE THREAD

**Issue by Yuyn1234** [ApolloAuto/apollo#12854]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:16.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0

### Steps to reproduce the issue:
I firstly use apollo5.5 and nvidia driver430, and it is OK. And then I update to apollo6.0 and nvidia driver450, it jams at "starting docker container" when I run the script"dev_start.sh".

**Comment by storypku** [comment]
You can run `bash docker/scripts/dev_start.sh -g cn` if you are from China, or manually downloaded all the relavant docker files and run with `dev_start.sh --local` to see if the problem persists.

Besides, please also note that Ubuntu 16.04 support is going to be retired in Apollo 6.0 and onwards. Please upgrade to 18.04 to have a better experience.

**Comment by storypku** [comment]
Hi @Yuyn1234, since we haven't got your reply for 10+ days, this issue is going to be closed now. Reopen it at any time when you returns, or create another issue if you have other questions. 

Thanks for using Apollo.
