### ISSUE TITLE
Customizing release container: Unable to find image 'apolloauto/apollo:local' locally

### ISSUE THREAD

**Issue by vivianistan** [ApolloAuto/apollo#1286]
I'm trying to follow the quick start guide and have followed steps 1-7 in the "Customize Your Release Container" section. However when I get to the "Launch the Local release env Docker Image" step, running `bash docker/scripts/release_start.sh local` results in these errors: 

Unable to find image 'apolloauto/apollo:local' locally

docker: Error response from daemon: manifest for apolloauto/apollo:local not found.
See 'docker run --help'.
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release
Error response from daemon: No such container: apollo_release

Am I missing a step? Any guidance would be appreciated

link to guide: https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md](url)

**Comment by Carolina68** [comment]
hello, I have also the same problem. Have you found the solution towards this?

**Comment by xiaoxq** [comment]
Oops, I just found that the TAG name in docker/scripts/release_commit.sh has become "local_release".
To confirm, please run
```
docker images | grep apolloauto
# There should be an image named "apolloauto/apollo:local_release"
```

Then the script to start it should be
```bash
bash docker/scripts/release_start.sh local_release
```

I will make the fix. Thanks very much for reporting!

**Comment by vivianistan** [comment]
Yes, I can confirm that `bash docker/scripts/release_start.sh local_release` launches the HMI as expected. (I actually figured it out on my own but did remember to update this issue!)
