### ISSUE TITLE
GNSS using tcp ethernet doesn't work (Remote closed)

### ISSUE THREAD

**Issue by llu0120** [ApolloAuto/apollo#12869]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master 
- **Output of `apollo.sh config` if on `master` branch**:
![Selection_019](https://user-images.githubusercontent.com/41609738/97472843-a999aa00-1920-11eb-8125-9f1d431a262d.png)

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I've modified the `gnss_config.pb.txt` file (changing all the `ntrip` and `serial` part into `tcp` with only `ip address` and `port`) and I tried to use ethernet to connect the novatel PwrPak7-ED1, but when I launch the dag file with mainboard, it's not working with some error message. 
```
cd apollo/cyber 
source setup.bash
mainboard -d /apollo/modules/drivers/gnss/dag/gnss.dag
```
### Supporting materials (screenshots, command lines, code/script snippets):
![Selection_017](https://user-images.githubusercontent.com/41609738/97472033-c2ee2680-191f-11eb-9fc5-17f71e1023ac.png)
![Selection_018](https://user-images.githubusercontent.com/41609738/97472040-c4b7ea00-191f-11eb-908b-13f11e32a617.png)

Please help, thanks! 
![Selection_019](https://user-images.githubusercontent.com/41609738/97472823-a43c5f80-1920-11eb-8345-5ce697e5ba9f.png)

**Comment by daohu527** [comment]
Although I have not tested it, you can modify the following interface to tcp to adapt to it. If you still have problems, pls feel free to reopen it
```
data {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/novatel0"
        baud_rate: 115200
    }
}
```
