### ISSUE TITLE
Problem installing debugging tools in docker 

### ISSUE THREAD

**Issue by Abd0ul** [ApolloAuto/apollo#12864]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0,1.5, 2.0, 2.5)**:

Hello,
i am trying to install tools (rqt_graph ....) in docker but when i have problem for system update and install:

navette1@in_dev_docker:/apollo$ sudo apt-get update
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease                         
  
Err http://archive.ubuntu.com trusty-backports InRelease                       
  
Err http://ppa.launchpad.net trusty InRelease                                  
  
Err http://ppa.launchpad.net trusty InRelease                                  
  
Err http://ppa.launchpad.net trusty InRelease                                  
  
Err http://ppa.launchpad.net trusty InRelease                                  
  
Err http://security.ubuntu.com trusty-security InRelease                       
  
Err http://archive.ubuntu.com trusty Release.gpg                               
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg                  
  Could not resolve 'archive.ubuntu.com'
Err http://storage.googleapis.com stable InRelease                        
  
Err http://ppa.launchpad.net trusty Release.gpg                           
  Could not resolve 'ppa.launchpad.net'
Err http://ppa.launchpad.net trusty Release.gpg                           
  Could not resolve 'ppa.launchpad.net'
Err http://ppa.launchpad.net trusty Release.gpg                           
  Could not resolve 'ppa.launchpad.net'
Err http://packages.ros.org trusty InRelease                              
  
Err http://archive.ubuntu.com trusty-backports Release.gpg                
  Could not resolve 'archive.ubuntu.com'
Err http://security.ubuntu.com trusty-security Release.gpg
  Could not resolve 'security.ubuntu.com'
Err http://ppa.launchpad.net trusty Release.gpg
  Could not resolve 'ppa.launchpad.net'
Err http://packages.ros.org trusty Release.gpg
  Could not resolve 'packages.ros.org'
Err http://storage.googleapis.com stable Release.gpg
  Could not resolve 'storage.googleapis.com'
Ign https://developer.download.nvidia.com  InRelease
Ign https://dl.yarnpkg.com stable InRelease
Ign https://developer.download.nvidia.com  InRelease
Ign https://dl.yarnpkg.com stable Release.gpg
Ign https://developer.download.nvidia.com  Release.gpg
Ign https://dl.yarnpkg.com stable Release
Ign https://developer.download.nvidia.com  Release.gpg
Err https://dl.yarnpkg.com stable/main amd64 Packages
  
Ign https://developer.download.nvidia.com  Release
Err https://dl.yarnpkg.com stable/main amd64 Packages
  
Ign https://developer.download.nvidia.com  Release
Err https://dl.yarnpkg.com stable/main amd64 Packages
  
Err https://dl.yarnpkg.com stable/main amd64 Packages
  
Err https://dl.yarnpkg.com stable/main amd64 Packages
  Could not resolve host: dl.yarnpkg.com
Err https://developer.download.nvidia.com  Packages
  Could not resolve host: developer.download.nvidia.com
Err https://developer.download.nvidia.com  Packages
  Could not resolve host: developer.download.nvidia.com
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-backports/InRelease  

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://storage.googleapis.com/bazel-apt/dists/stable/InRelease  

W: Failed to fetch http://ppa.launchpad.net/keithw/glfw3/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://ppa.launchpad.net/gluster/glusterfs-3.10/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-backports/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://ppa.launchpad.net/keithw/glfw3/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Failed to fetch http://ppa.launchpad.net/gluster/glusterfs-3.10/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/Release.gpg  Could not resolve 'ppa.launchpad.net'

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'security.ubuntu.com'

W: Failed to fetch http://storage.googleapis.com/bazel-apt/dists/stable/Release.gpg  Could not resolve 'storage.googleapis.com'

W: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/trusty/Release.gpg  Could not resolve 'packages.ros.org'

W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages  Could not resolve host: dl.yarnpkg.com

W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  Could not resolve host: developer.download.nvidia.com

W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  Could not resolve host: developer.download.nvidia.com

W: Some index files failed to download. They have been ignored, or old ones used instead.
W: Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty-backports/universe amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-backports_universe_binary-amd64_Packages.gz)
W: Ignoring Provides line with DepCompareOp for package gdb-minimal
navette1@in_dev_docker:/apollo$ 

has anyone ever encountered this problem ?? how to solve it?

**Comment by storypku** [comment]
IIRC, Ubuntu 14.04 (Trusty) has been retired after its 5-year-support, and is no longer supported by the Apollo team either.

Please upgrade to a recent version of Apollo if possible. Or find ROS archives on the internet and install it manually or build it from source.

**Comment by Abd0ul** [comment]
Thanks for your feedback @storypku. 

I would like but I read in the documentation of the other versions based on CYBER that I will need an additional module the ASU? can I know if I can use another version (5.0 for example) without this module?

If so what are the changes that I should make in the system to make it work? I understood that the ASU allows to multiply the number of sensors that can be used with the Apollo system and does the data processing.

**Comment by Abd0ul** [comment]
Version 3.5 and 5.0 are also on trusty how come ??

![Capture d’écran de 2020-10-27 12-52-01](https://user-images.githubusercontent.com/60668969/97298177-586fb480-1853-11eb-9adb-b6a905ea5826.png)

**Comment by storypku** [comment]
@jinghaomiao @xiaoxq @Capri2014 Please help with this issue if possible. Thank you.

**Comment by jinghaomiao** [comment]
Docker image is using your own host OS as the base, and that's why it displays the way it is with your own host OS. You need to upgrade your host OS to 18.04 so that you can use the docker image with 5.0 and above.

**Comment by Abd0ul** [comment]
@jinghaomiao the operating system of my host machine is ubuntu 18.04 LTS on which I have installed the Apollo kernel but I still have ubuntu 14.04 in the docker of all branches

**Comment by jinghaomiao** [comment]
> @jinghaomiao the operating system of my host machine is ubuntu 18.04 LTS on which I have installed the Apollo kernel but I still have ubuntu 14.04 in the docker of all branches

You are right. My mistake. Yes 3.5 and 5.0 are based on Ubuntu 14.04 and 5.5 are based on 18.04. Thanks for making it clear.

**Comment by Abd0ul** [comment]
>  You are right. My mistake. Yes 3.5 and 5.0 are based on Ubuntu 14.04 and 5.5 are based on 18.04. Thanks for making it clear.


thanks for the confirmation, so since there is no more support for the trusty i can't update it nor do new installations of tools in docker from versions 1.0 up to 5.0?

**Comment by jinghaomiao** [comment]
> thanks for the confirmation, so since there is no more support for the trusty i can't update it nor do new installations of tools in docker from versions 1.0 up to 5.0?

No support can be provided to Ubuntu 14.04. Please upgrade to 18.04 and test new Apollo. 

But you can still play with Ubuntu 14.04 and older versions of Apollo. However, there will be no community support on new changes on 14.04. 

Thanks for your interest in Apollo.

**Comment by jinghaomiao** [comment]
This ticket is being closed. Should you have other issues, please feel free to let us know. Thanks!
