### ISSUE TITLE
Error start planning

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#12865]
Hi team!
When I run **cyber_launch start /apollo/modules/planning/launch/planning.launch**  
I get error  
![Screenshot from 2020-10-27 14-03-59](https://user-images.githubusercontent.com/61351599/97293362-9ffb3e00-185d-11eb-9332-7e1a90016d43.png)  

But before that, I run the route module  

![Screenshot from 2020-10-27 14-04-03](https://user-images.githubusercontent.com/61351599/97293465-c0c39380-185d-11eb-9bac-2cc66bf4807a.png)  

Perhaps you have any idea why the error is appearing?

After starting Sim control, the error disappears

**Comment by daohu527** [comment]
This may be an error message to prompt us, I think it can reduce the number of times this message appears.
## reason
the reason is very simple, `has_routing_` is default `false` in a **while loop**, so when first start the thread `GenerateThread` the msg will print without sleep, then it will print as many messages as possible in a short time, when the `has_routing_` set true, the messages will not appear!

https://github.com/ApolloAuto/apollo/blob/de70315b459fd53f527e342eb884099406ce7481/modules/planning/reference_line/reference_line_provider.cc#L190-L198

## improve
so maybe should add sleep in it.
```c++
  while (!is_stop_) {
    static constexpr int32_t kSleepTime = 50;  // milliseconds
    cyber::SleepFor(std::chrono::milliseconds(kSleepTime));
    const double start_time = Clock::NowInSeconds();
    if (!has_routing_) {
      AERROR << "Routing is not ready.";
      std::this_thread::sleep_for(std::chrono::milliseconds(100));    // sleep a while
      continue;
    }
```

**Comment by AlexandrZabolotny** [comment]
Hi @daohu527 
> After all, it is only a reminder when routing is not available  

The problem is that routing is not available. But I run routing and get the required channel.
The planning module starts working if I activate for a second and then deactivate Sim Control

**Comment by daohu527** [comment]
Is your focus on the error message or the reason for printing the error log?

If you start the planning module, then the error message will start output. Because the `has_routing_` is enable in `Proc`, which means after planning module receive "PredictionObstacles, Chassis, LocalizationEstimate" then it set `has_routing_` to be true.

As you said, after you need to open sim_control, this information is gone. The `has_routing_` will always true if not shutdown planning module.

I don’t know if it’s reasonable to deal with it, just describe the whole process.

**Comment by AlexandrZabolotny** [comment]
Thanks for the help!

The problem was that I did not form ChannelName: /apollo/canbus/chassis.

**Comment by nhatuan84** [comment]
hi @AlexandrZabolotny 
I run simulation mode using Dreamview and facing the same issue.
I enabled (planning and routing) in Module Controller panel of Dreamview.
The log of routing said that the routing service is running.
How did you solve it?

Thank.

**Comment by AlexandrZabolotny** [comment]
> hi @AlexandrZabolotny
> I run simulation mode using Dreamview and facing the same issue.
> I enabled (planning and routing) in Module Controller panel of Dreamview.
> The log of routing said that the routing service is running.
> How did you solve it?
> 
> Thank.

Hi @nhatuan84   
Have you selected your finishing point on the map using Route Editing?

**Comment by nhatuan84** [comment]
Thanks @AlexandrZabolotny !
I have not selected it yet. I have just tried Apollo and not fully understood the steps to run it successfully.
Hopefully there is a video about this.
I will tried your point.

**Comment by Tim0083** [comment]
![Uploading Screenshot from 2020-11-25 22-32-51.png…]()

**Comment by AlexandrZabolotny** [comment]
Hello @daohu527 
I see that you are actively developing Apollo
I am trying to run a planning module with type public_road.
But I get an error. Can't you tell me how to solve it?​



[planning]  E1203 11:37:48.856611  7845 trajectory_stitcher.cc:206] [mainboard]the distance between matched point and actual position is too large. Replan is triggered. lon_diff = 2.533971
[planning]  E1203 11:37:48.951678  7845 piecewise_jerk_speed_nonlinear_optimizer.cc:580] [planning]Solver failure case is : INFEASIBLE_PROBLEM_DETECTED
[planning]  E1203 11:37:48.951701  7845 piecewise_jerk_speed_nonlinear_optimizer.cc:583] [planning]Piecewise jerk speed nonlinear optimizer failed!
[planning]  E1203 11:37:48.952050  7845 lane_follow_stage.cc:177] [planning]Failed to run tasks[PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER], Error message: Piecewise jerk speed nonlinear optimizer failed!
[planning]  E1203 11:37:48.952694  7845 lane_follow_stage.cc:373] [planning]Use last frame good path to do speed fallback
[planning]  E1203 11:37:48.952702  7845 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning]  E1203 11:37:48.952706  7845 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!
[planning]  E1203 11:37:50.256542  7838 trajectory_stitcher.cc:206] [mainboard]the distance between matched point and actual position is too large. Replan is triggered. lon_diff = -2.525091
[planning]  E1203 11:37:50.537103  7839 piecewise_jerk_speed_nonlinear_optimizer.cc:580] [planning]Solver failure case is : INFEASIBLE_PROBLEM_DETECTED
[planning]  E1203 11:37:50.537125  7839 piecewise_jerk_speed_nonlinear_optimizer.cc:583] [planning]Piecewise jerk speed nonlinear optimizer failed!
[planning]  E1203 11:37:50.537402  7839 lane_follow_stage.cc:177] [planning]Failed to run tasks[PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER], Error message: Piecewise jerk speed nonlinear optimizer failed!
[planning]  E1203 11:37:50.537904  7839 lane_follow_stage.cc:373] [planning]Use last frame good path to do speed fallback
[planning]  E1203 11:37:50.537914  7839 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning]  E1203 11:37:50.537927  7839 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!
[planning]  E1203 11:37:51.956367  7834 trajectory_stitcher.cc:206] [mainboard]the distance between matched point and actual position is too large. Replan is triggered. lon_diff = -2.565050
[planning]  E1203 11:37:52.045127  7834 piecewise_jerk_speed_nonlinear_optimizer.cc:580] [planning]Solver failure case is : INFEASIBLE_PROBLEM_DETECTED
[planning]  E1203 11:37:52.045152  7834 piecewise_jerk_speed_nonlinear_optimizer.cc:583] [planning]Piecewise jerk speed nonlinear optimizer failed!
[planning]  E1203 11:37:52.045442  7834 lane_follow_stage.cc:177] [planning]Failed to run tasks[PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER], Error message: Piecewise jerk speed nonlinear optimizer failed!
[planning]  E1203 11:37:52.046111  7834 lane_follow_stage.cc:373] [planning]Use last frame good path to do speed fallback
[planning]  E1203 11:37:52.046128  7834 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning]  E1203 11:37:52.046133  7834 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!
[planning]  E1203 11:37:53.656141  7834 trajectory_stitcher.cc:206] [mainboard]the distance between matched point and actual position is too large. Replan is triggered. lon_diff = -2.527226

**Comment by daohu527** [comment]
I can't find the reason now. From the error log message, seems the difference between the actual arrival location and the planning location is too large gap (lon_diff = 2.533971m).

1. It may be the control module cannot control the car to the target trajectory. did you see control module errors?
2. It may be localization module publish wrong location.
3. The delay of publish messages, please check whether the topic frequency is reduced

So you should try it for more information.

**Comment by AlexandrZabolotny** [comment]
**This is the log of the trajectory planning module.
The problem appears when driving through tight turns.
The problem starts here.**

[planning] E1203 11:37:48.951678 7845 piecewise_jerk_speed_nonlinear_optimizer.cc:580] [planning]Solver failure case is : INFEASIBLE_PROBLEM_DETECTED
[planning] E1203 11:37:48.951701 7845 piecewise_jerk_speed_nonlinear_optimizer.cc:583] [planning]Piecewise jerk speed nonlinear optimizer failed!
[planning] E1203 11:37:48.952050 7845 lane_follow_stage.cc:177] [planning]Failed to run tasks[PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER], Error message: Piecewise jerk speed nonlinear optimizer failed!
[planning] E1203 11:37:48.952694 7845 lane_follow_stage.cc:373] [planning]Use last frame good path to do speed fallback
[planning] E1203 11:37:48.952702 7845 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning] E1203 11:37:48.952706 7845 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!


**At this moment, the trajectory disappears. And the control module reports that the trajectory message is empty. And sharply calls to turn the wheel in different directions**

**Comment by AlexandrZabolotny** [comment]
I also noticed that the trajectory repeatability is poor. The car is driving in the outer radius.

Perhaps you have an idea how to fix this?

**Comment by daohu527** [comment]
It seems that the planning module cannot plan a trajectory, so it can only slow down. I don’t know if your road conditions can support turning. Control parameters are important, but will not play a decisive role

**Comment by AlexandrZabolotny** [comment]
> It seems that the planning module cannot plan a trajectory, so it can only slow down. I don’t know if your road conditions can support turning. Control parameters are important, but will not play a decisive role

What do you mean by "road conditions"?

**Comment by daohu527** [comment]
Is the curvature of the road too large or the road too narrow?

**Comment by AlexandrZabolotny** [comment]
the curvature of the road is too large

**Comment by AlexandrZabolotny** [comment]
![Screenshot from 2020-12-04 13-23-50](https://user-images.githubusercontent.com/61351599/101152357-ff562600-3633-11eb-8e65-9f275fab4c07.png)

**Comment by AlexandrZabolotny** [comment]
![Screenshot from 2020-12-04 13-35-54](https://user-images.githubusercontent.com/61351599/101153565-ab4c4100-3635-11eb-911f-c9fc24dfad2f.png)

**Comment by daohu527** [comment]
I am not very sure about the length of your road. If the curvature is particularly large, the car may not pass through. This may require some debugging, because I am not so familiar with it. What function do you want to test?

**Comment by AlexandrZabolotny** [comment]
> I am not very sure about the length of your road. If the curvature is particularly large, the car may not pass through. This may require some debugging, because I am not so familiar with it. What function do you want to test?

I only want to drive autonomously along this road using a public_road planner
