### ISSUE TITLE
Different Camera Configuration

### ISSUE THREAD

**Issue by lucasnmatias** [ApolloAuto/apollo#12874]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**:

I've been working with Apollo 5.5 and LGSVL and I've built a different camera configuration on the simulation and I would like to run the camera and LiDAR perception on it. The problem at the moment is this, I could change the sensor names (LiDAR and Cameras) and run it without problem. However, when starting the fusion component to fuse both LiDAR and Camera data the fusion doesn't happen. If I maintain the original camera names (e.g. front_6mm, front_12mm) the fusion works, but when I change the cameras names (e.g. my_front_6mm, my_front_12mm) the camera detection works but the data is not fused. I've changed the names in many files already (that's why I managed to start the camera detection), but I would like to know if there is some specific configuration file for the fusion component where I should change the sensor names.

**Comment by lucasnmatias** [comment]
I've found the problem. I've changed the sensor names and I noticed that in two files from the `fusion_component` the camera `sensor_name_id` are hard coded:

1. [fusion/lib/data_association/hm_data_association/hm_tracks_objects_match.cc](https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/perception/fusion/lib/data_association/hm_data_association/hm_tracks_objects_match.cc)

> 363    if (sensor_id == "front_6mm" || sensor_id == "front_12mm") {
> ...
> 380    if (!post && (sensor_id == "front_6mm" || sensor_id == "front_12mm"))

2. [fusion/lib/gatekeeper/pbf_gatekeeper/pbf_gatekeeper.cc](https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/perception/fusion/lib/gatekeeper/pbf_gatekeeper/pbf_gatekeeper.cc)

> 177  auto iter = camera_objects.find("front_6mm");
> 178  auto iter_narrow = camera_objects.find("front_12mm");

So basically for the sensor fusion if you use a different sensor configuration (different sensor name) it will not work unless you change it on those two files. Also, we've found a way to add more than 2 cameras to the Apollo perception module and if that is the case it would be necessary to change those lines too.

A suggested solution:
I've noticed that for the `fusion_component` there are some config files in [/perception/production/data/perception/fusion](https://github.com/ApolloAuto/apollo/tree/r5.5.0/modules/perception/production/data/perception/fusion) where the sensor names are declared with some other parameters. The code could be changed to verify and gather detections from the sensors listed on these `.pt` files instead of have them hard coded. This would be a more elegant solution and of course, would facilitate the configuration and usage of the Apollo modules.

**Comment by ideasplus** [comment]
@lucasnmatias Thank you for your useful information. Could you share the way to add more that 2 cameras to the camera module? I know there is a condition and it is not reasonable. https://github.com/ApolloAuto/apollo/blob/9a1088959f70e7dcbaf3d782ebceed370ac4aa2b/modules/perception/onboard/component/fusion_camera_detection_component.cc#L158-L161

**Comment by lucasnmatias** [comment]
@ideasplus to run more than 2 cameras we didn't need to change the code, we've changed the .dag file. Basically like this, instead of having the original .dag file:

>module_config {
>  module_library : "/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so"
>  components {
>    class_name : "FusionCameraDetectionComponent"
>    config {
>      name: "FusionCameraComponent"
>      config_file_path: "/apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt"
>      flag_file_path: "/apollo/modules/perception/production/conf/perception/perception_common.flag"
>    }
> }
>}

We changed to:

>module_config {
>  module_library : "/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so"
>  components {
>    class_name : "FusionCameraDetectionComponent"
>    config {
>      name: "FusionCameraComponent"
>      config_file_path: "/apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt"
>      flag_file_path: "/apollo/modules/perception/production/conf/perception/perception_common.flag"
>   }
>  }
>  components {
>    class_name : "FusionCameraDetectionComponent"
>    config {
>      name: "FusionCameraComponent2"
>      config_file_path: "/apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component2.pb.txt"
>      flag_file_path: "/apollo/modules/perception/production/conf/perception/perception_common.flag"
>   }
>  }
> }

So we initialize a second camera module with other two pairs.

**Comment by ideasplus** [comment]
@lucasnmatias Thank you for your prompt reply. That's great.

**Comment by ningfeiwang** [comment]
@lucasnmatias Hello, I wonder how the Apollo handles multiple camera-based perceptions. Will it fuse all the camera perception results together before fusing with LiDAR? Thank you!
