### ISSUE TITLE
Simulation problem with lgsvl

### ISSUE THREAD

**Issue by duongnxptit** [ApolloAuto/apollo#12889]
I am working with:
- Apollo 6 (master latest)
- Lgsvlsimulator-2020.06
- Ubuntu 18.04
When I am trying to simulate in Borregas Ave map in lgsvl, all were good until selected Routing in Apollo then submit it. Vehicle don't run autonomous, there is only one red line that gives directions to the selected point. Its seem there is only routing module work.
My dreamview screen:
![Selection_002](https://user-images.githubusercontent.com/48410671/97770972-d0e3b780-1b6a-11eb-90ce-6115e887726f.png)

**Comment by Gricha1** [comment]
Hi. How did you solve this problem?
