### ISSUE TITLE
Not able to build cyber inside the docker

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#12888]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
1 Get into cyber docker
2. Run ./apollo.sh build cyber

### Supporting materials (screenshots, command lines, code/script snippets):

$ ./apollo.sh build cyber
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] No nvidia-driver found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2020-10-29-513e1e77f9
[INFO]     DOCKER_IMG: cyber-x86_64-18.04-20201029_0047
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=0
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] No nvidia-driver found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
[INFO] Build Overview: 
[INFO]     USE_GPU: 0  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=cpu
[INFO]     Build Targets: //cyber/... union //modules/tools/visualizer/...
[INFO]     Disabled:      
Starting local Bazel server and connecting to it...
(20:37:45) INFO: Invocation ID: a9d84160-b075-4f34-9a87-0ab8c2020c75
(20:37:45) INFO: Current date is 2020-10-30
(20:37:48) INFO: Analyzed 708 targets (101 packages loaded, 2343 targets configured).
(20:37:48) INFO: Found 708 targets...
(20:39:07) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:209:11: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Bus error): gcc failed: error executing command 
  (cd /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/opt/apollo/sysroot/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/apollo/scripts:/usr/local/qt5/bin:/apollo/bazel-bin/cyber:/apollo/bazel-bin/cyber/tools/cyber_recorder:/apollo/bazel-bin/cyber/tools/cyber_monitor:/apollo/bazel-bin/cyber/tools/cyber_channel:/apollo/bazel-bin/cyber/tools/cyber_node:/apollo/bazel-bin/cyber/tools/cyber_service:/apollo/bazel-bin/cyber/tools/cyber_launch:/apollo/bazel-bin/modules/tools/visualizer:/apollo/bazel-bin/modules/data/tools/rosbag_to_record:/apollo/modules/teleop/common/scripts \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/json_escaping.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/json_escaping.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/host/bin/external/zlib -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem external/zlib/zlib/include -isystem bazel-out/host/bin/external/zlib/zlib/include -g0 '-march=native' -g0 '-std=c++14' -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -Wno-deprecated-declarations -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/util/internal/json_escaping.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/json_escaping.o)
Execution platform: @local_config_platform//:host
(20:39:07) INFO: Elapsed time: 84.009s, Critical Path: 79.15s
(20:39:07) INFO: 0 processes.
(20:39:07) FAILED: Build did NOT complete successfully

**Comment by storypku** [comment]
Hi @jpcloud1577 , this issue is a little weird. 

1. 
```
[INFO] USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=0
[WARNING] No nvidia-driver found. CPU will be used.
[WARNING] No nvidia-driver found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
```

If `USE_GPU_HOST=1`, and the CyberRT Docker container is unchanged, there is no reason that `USE_GPU_TARGET=0`.


2. 

```
/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:209:11: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Bus error): gcc failed: error executing command
(cd /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo &&
```

You can try to cleanup bazel caches/outputs and try again to see if the problem persists:

```
./apollo.sh clean --expunge
# OR
rm -rf /apollo/.cache/bazel 
```
