### ISSUE TITLE
apollo can not recieve information from lgsvl

### ISSUE THREAD

**Issue by WXTN** [ApolloAuto/apollo#12895]
LGSVL shows it has connected with apollo, however , apollo didn't receive information and stay in initial interface. We are using the latest Apollo v6.0.0 and LGSVL 2020.06. Anyone encountered this problem before？

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: v6.0.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
```
./apollo.sh build_opt_gpu
./scripts/bootstrap_lgsvl.sh
./scripts/bridge.sh
```
### Supporting materials:
![lgsvl](https://user-images.githubusercontent.com/73725900/97831234-5fdb0600-1d0a-11eb-89e7-b6cc5de4cece.png)
![apollo2](https://user-images.githubusercontent.com/73725900/97831251-679aaa80-1d0a-11eb-8e62-d59cb55d3e39.png)
![apollo3](https://user-images.githubusercontent.com/73725900/97831259-6b2e3180-1d0a-11eb-8f14-6a63007745f9.png)

**Comment by ntutangyun** [comment]
could you open `cyber_monitor` and see if there are any message showing up?

**Comment by WXTN** [comment]
> could you open `cyber_monitor` and see if there are any message showing up?

It seems Apollo has recive information from several channels, and we can observe that simulated cars passing by from the pointcoud(using cyber_visualizer).
![cyber_monitor](https://user-images.githubusercontent.com/73725900/97858379-08548e80-1d3a-11eb-9e40-b0dd6e041ea5.png)
![CyberVisualizer1](https://user-images.githubusercontent.com/73725900/97858418-15717d80-1d3a-11eb-9386-29fcc8fb8d57.png)

**Comment by luqiang21** [comment]
@WXTN You only have `Transform` enabled, did you try enabling `Localization`?
