### ISSUE TITLE
Should the Apollo's docker environment be used for industrial grade product environment?

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12892]
Hi,

It's well known that apollo is developed and tested in a docker environment and hardware platform (D-kit). But the applications running in docker environment in nature are less efficiency than running on the hardware directly. So, I want to know whether the docker environment will also be used for industrial grade product environment?

Regards,
HY

**Comment by lx18233184051** [comment]
「industrial grade product」 means the linux system  Not in dokcer?

**Comment by hongyi-zhao** [comment]
> 「industrial grade product」 means the linux system Not in dokcer?

I mean run apollo directly on the physical host instead from the docker container for  performance and robustness.

**Comment by storypku** [comment]
> > 「industrial grade product」 means the linux system Not in dokcer?
> 
> I mean run apollo directly on the physical host instead from the docker container for performance and robustness.

@jinghaomiao @ycool Please help answer this question. Thank you.

**Comment by jinghaomiao** [comment]
> > 「industrial grade product」 means the linux system Not in dokcer?
> 
> I mean run apollo directly on the physical host instead from the docker container for performance and robustness.

Apollo is tested to be compatible with Ubuntu 18.04. A docker env is distributed to developers to minimize the confusion and inconsistency among different host machines with different kernel version, dependency library version and other discrepancies. You are encouraged to run Apollo in your host machine without Docker, though we believe that the overhead of running Apollo in a virtual container is smaller than you expected. But you have to make sure that all libraries and dependencies are installed and managed the same way that Apollo is doing in the distributed docker environment.

**Comment by storypku** [comment]
> > > 「industrial grade product」 means the linux system Not in dokcer?
> > 
> > 
> > I mean run apollo directly on the physical host instead from the docker container for performance and robustness.
> 
> Apollo is tested to be compatible with Ubuntu 18.04. A docker env is distributed to developers to minimize the confusion and inconsistency among different host machines with different kernel version, dependency library version and other discrepancies. You are encouraged to run Apollo in your host machine without Docker, though we believe that the overhead of running Apollo in a virtual container is smaller than you expected. But you have to make sure that all libraries and dependencies are installed and managed the same way that Apollo is doing in the distributed docker environment.

Thanks @jinghaomiao.  I think @hongyi-zhao's question was, whether Apollo running inside docker was less performant and less robust than running without docker?

**Comment by hongyi-zhao** [comment]
Basically, @storypku correctly stated what I mean, but @jinghaomiao's notes/explanations also deepen my understanding of apollo's running environment/performance/development flow to a greater extent.

**Comment by jinghaomiao** [comment]
> Basically, @storypku correctly stated what I mean, but @jinghaomiao's notes/explanations also deepen my understanding of apollo's running environment/performance/development flow to a greater extent.

I cannot comment on how robust a Docker container is, but Docker is widely used in various production environments in the industry.

**Comment by storypku** [comment]
Hi @hongyi-zhao, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
