### ISSUE TITLE
Is it possible to delete the dependency of the poco library?

### ISSUE THREAD

**Issue by daohu527** [ApolloAuto/apollo#12894]
## suggestion
Since apollo just uses "Poco/SharedLibrary.h" to load the dynamic library, and obviously **apollo only supports linux system**. We don't need to use **cross-platform** library `Poco/SharedLibrary.h`, which support HPUX, UNIX, VMS, VX, WIN32, WIN32U.

## solution
Implement load library depends on unix `dlfcn.h` is enough.

**Comment by storypku** [comment]
> ## suggestion
> Since apollo just uses "Poco/SharedLibrary.h" to load the dynamic library, and obviously **apollo only supports linux system**. We don't need to use **cross-platform** library `Poco/SharedLibrary.h`, which support HPUX, UNIX, VMS, VX, WIN32, WIN32U.
> 
> ## solution
> Implement load library depends on unix `dlfcn.h` is enough.

Yes, of course we can implement the dynamic library loading mechanism in Apollo directly using system library functions like `dlopen`, `dlsym`, `dlclose`, etc. However, since the Poco library already implemented it, and the original CyberRT implementors adopted it from the very beginning, there seems no need to rewrite it from scratch without much performance gain.

**Comment by daohu527** [comment]
There is no improvement in performance. But we can remove the dependency of the poco library, cyber for now need to install whole poco just for a little function, I think it can be improved.

## Current dependency
load
https://github.com/ApolloAuto/apollo/blob/c18a5adfe3fa04009715b7ced5e1f6310091a8f0/cyber/class_loader/utility/class_loader_utility.cc#L216

unload
https://github.com/ApolloAuto/apollo/blob/c18a5adfe3fa04009715b7ced5e1f6310091a8f0/cyber/class_loader/utility/class_loader_utility.cc#L268


## implement
The whole `SharedLibrary_UNIX.cpp` in poco is less than 100 lines of code, and just a simple wrapper of `dlopen` and `dlclose`, If cyber ​​**does not require cross-platform support**  

load
```c++
void SharedLibraryImpl::loadImpl(const std::string& path, int flags)
{
	FastMutex::ScopedLock lock(_mutex);

	if (_handle) throw LibraryAlreadyLoadedException(path);
	int realFlags = RTLD_LAZY;
	if (flags & SHLIB_LOCAL_IMPL)
		realFlags |= RTLD_LOCAL;
	else
		realFlags |= RTLD_GLOBAL;
	_handle = dlopen(path.c_str(), realFlags);
	if (!_handle)
	{
		const char* err = dlerror();
		throw LibraryLoadException(err ? std::string(err) : path);
	}
	_path = path;
}
```


unload
```c++
void SharedLibraryImpl::unloadImpl()
{
	FastMutex::ScopedLock lock(_mutex);

	if (_handle)
	{
		dlclose(_handle);
		_handle = 0;
	}
}
```

I think this is a **suggestion** that cyber can be improved, if we need cross-platform support later, then we can keep it, if not, why not we implement more clean code?

**Comment by storypku** [comment]
Good point. To reduce the dependency of Cyber RT can make it self-contained and finally out of Docker. Community effort is appreciated currently since the team has other more prioritized tasks to do: Ampere GPU support, RT Kernel updates, etc.

**Comment by BH1SCW** [comment]
Good point +1

**Comment by storypku** [comment]
@daohu527 Thanks for your suggestion. And this issue is going to be closed. Please feel free to create another issue if you have other questions. 
Thanks for your long time contribution to Apollo! We really appreciate it.
