### ISSUE TITLE
替代硬件的问题

### ISSUE THREAD

**Issue by XiangjiBU** [ApolloAuto/apollo#12899]
你好，我想用apollo开发在限定环境下的低速无人车，想请问是否可以使用其他价格更便宜的硬件替代官方套件？比如激光雷达换成国产品牌的，甚至单线的。

**Comment by diegohu** [comment]
你好，可以考虑Apollo D-KIT，其集成了低速小型底盘和传感器套件，并且适配了Apollo开源代码，能帮助你快速上手Apollo。
https://apollo.auto/apollo_d_kit.html 这是D-KIT的官网介绍。

**Comment by XiangjiBU** [comment]
> 你好，可以考虑Apollo D-KIT，其集成了低速小型底盘和传感器套件，并且适配了Apollo开源代码，能帮助你快速上手Apollo。
> https://apollo.auto/apollo_d_kit.html 这是D-KIT的官网介绍。

D-KIT套件里的硬件可以替换吗？比如工控机换成英伟达的 jetson AGX， 激光雷达换成其他品牌的？

**Comment by diegohu** [comment]
> D-KIT套件里的硬件可以替换吗？比如工控机换成英伟达的 jetson AGX， 激光雷达换成其他品牌的？

D-KIT集成的都是已经适配Apollo的硬件，如果替换其他硬件的话，可能有额外的适配成本。目前Apollo还不支持ARM架构，如你提到的Jetson AGX Xavier，激光雷达所支持的型号可以在这里查找 https://github.com/ApolloAuto/apollo/tree/master/modules/drivers

**Comment by diegohu** [comment]
@XiangjiBU 你好！希望我们的回答能够解决您的问题。我们现在将关闭该问题。如果您还有其他问题，请随时打开一个新问题。我们的工程师团队非常乐意为您提供帮助。

感谢您对Apollo的支持！
