### ISSUE TITLE
Planning module launch problems

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#12896]
Hi team!  

### My system information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:   Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**:  source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  6.0  

**I am trying to run the planning module on a real car. 
But after a few seconds of normal control - the steering wheel starts to rotate chaotically.  
Perhaps there are any ideas why? Below is the list of errors of the planning module.**  

[planning]  E1102 11:36:42.808028 12456 trajectory_stitcher.cc:208] [mainboard]the distance between matched point and actual position is too large. Replan is triggered. lon_diff = -2.57968
[planning]  E1102 11:36:42.816000 12456 piecewise_jerk_problem.cc:105] [planning]failed optimization status:	primal infeasible
[planning]  E1102 11:36:42.816030 12456 piecewise_jerk_path_optimizer.cc:317] [planning]piecewise jerk path optimizer failed
[planning]  E1102 11:36:42.822373 12456 piecewise_jerk_problem.cc:105] [planning]failed optimization status:	primal infeasible
[planning]  E1102 11:36:42.822407 12456 piecewise_jerk_path_optimizer.cc:317] [planning]piecewise jerk path optimizer failed
[planning]  E1102 11:36:42.822418 12456 path_optimizer.cc:49] [planning]Reference Line 0_0 is not drivable after PIECEWISE_JERK_PATH_OPTIMIZER
[planning]  E1102 11:36:42.822425 12456 lane_follow_stage.cc:177] [planning]Failed to run tasks[PIECEWISE_JERK_PATH_OPTIMIZER], Error message: Path Optimizer failed to generate path
[planning]  E1102 11:36:42.822440 12456 lane_follow_stage.cc:265] [planning]Path fallback due to algorithm failure
[planning]  E1102 11:36:42.822470 12456 path_data.cc:44] [planning]Should NOT set discretized path when reference line is nullptr. Please set reference line first.
[planning]  E1102 11:36:42.822476 12456 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning]  E1102 11:36:42.822481 12456 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!
[planning]  E1102 11:36:42.824322 12456 piecewise_jerk_problem.cc:105] [planning]failed optimization status:	primal infeasible
[planning]  E1102 11:36:42.824340 12456 speed_profile_generator.cc:79] [planning]Piecewise jerk fallback speed optimizer failed!
[planning]  E1102 11:36:42.824345 12456 speed_profile_generator.cc:120] [planning]Slowing down the car within a constant deceleration with fallback stopping profile.
[planning]  E1102 11:36:42.824362 12456 reference_line_info.cc:503] [planning]path data is empty
[planning]  E1102 11:36:42.824368 12456 lane_follow_stage.cc:203] [planning]Fail to aggregate planning trajectory.
[planning]  E1102 11:36:42.824373 12456 scenario.cc:79] [planning]Stage 'LANE_FOLLOW_DEFAULT_STAGE' returns error
[planning]  E1102 11:36:42.824381 12456 on_lane_planning.cc:547] [mainboard]planner failed to make a driving plan
[planning]  E1102 11:36:42.824394 12456 on_lane_planning.cc:372] [mainboard]Planning failed:PLANNING_ERROR: planner failed to make a driving plan
[planning]  E1102 11:36:42.912127 12464 gridded_path_time_graph.cc:519] [planning]Fail to find the best feasible trajectory.
[planning]  E1102 11:36:42.912147 12464 gridded_path_time_graph.cc:137] [planning]Retrieve best speed profile failed.
[planning]  E1102 11:36:42.912149 12464 path_time_heuristic_optimizer.cc:53] [planning]failed to search graph with dynamic programming.
[planning]  E1102 11:36:42.912155 12464 path_time_heuristic_optimizer.cc:73] [planning]SPEED_HEURISTIC_OPTIMIZER: Failed to search graph with dynamic programming.
[planning]  E1102 11:36:42.912161 12464 lane_follow_stage.cc:177] [planning]Failed to run tasks[SPEED_HEURISTIC_OPTIMIZER], Error message: SPEED_HEURISTIC_OPTIMIZER: Failed to search graph with dynamic programming.
[planning]  E1102 11:36:42.912179 12464 lane_follow_stage.cc:373] [planning]Use last frame good path to do speed fallback
[planning]  E1102 11:36:42.912184 12464 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning]  E1102 11:36:42.912186 12464 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!
[planning]  E1102 11:36:43.011121 12462 gridded_path_time_graph.cc:519] [planning]Fail to find the best feasible trajectory.
[planning]  E1102 11:36:43.011135 12462 gridded_path_time_graph.cc:137] [planning]Retrieve best speed profile failed.
[planning]  E1102 11:36:43.011139 12462 path_time_heuristic_optimizer.cc:53] [planning]failed to search graph with dynamic programming.
[planning]  E1102 11:36:43.011147 12462 path_time_heuristic_optimizer.cc:73] [planning]SPEED_HEURISTIC_OPTIMIZER: Failed to search graph with dynamic programming.
[planning]  E1102 11:36:43.011154 12462 lane_follow_stage.cc:177] [planning]Failed to run tasks[SPEED_HEURISTIC_OPTIMIZER], Error message: SPEED_HEURISTIC_OPTIMIZER: Failed to search graph with dynamic programming.
[planning]  E1102 11:36:43.011178 12462 lane_follow_stage.cc:373] [planning]Use last frame good path to do speed fallback
[planning]  E1102 11:36:43.011183 12462 lane_follow_stage.cc:288] [planning]Speed fallback due to algorithm failure
[planning]  E1102 11:36:43.011186 12462 speed_profile_generator.cc:38] [planning]Fallback using piecewise jerk speed!

**Comment by AlexandrZabolotny** [comment]
I use defalt plsnning config

**Comment by AlexandrZabolotny** [comment]
Here is the link to the record file  
https://cloud.mail.ru/public/5jsd/NmdDxCBEi  

Error you can see on 164302898  

![Screenshot from 2020-11-02 16-51-53](https://user-images.githubusercontent.com/61351599/97881461-7e092c00-1d33-11eb-9762-49ee62f51189.png)

**Comment by GabrielZZZ** [comment]
I have also encountered this problem. I remember there was an issue talked about this and it is related to CPU. You can search for it. Maybe try Modular Testing?

**Comment by AlexandrZabolotny** [comment]
> I have also encountered this problem. I remember there was an issue talked about this and it is related to CPU. You can search for it. Maybe try Modular Testing?

Can you describe the problem in more detail so that I can find issue by keywords?

**Comment by MaisJamal** [comment]
Hello, any updates on the issue? I am facing a similar problem

**Comment by AlexandrZabolotny** [comment]
> Hello, any updates on the issue? I am facing a similar problem, can you please help?

You can try to change [this](https://github.com/ApolloAuto/apollo/blob/4025df3380d4fa4ae37cd5228b019db81d13d800/modules/planning/conf/planning_config.pb.txt#L25) parameters

**Comment by starrye** [comment]
a similar problem, my apollo version: 7.0

**Comment by AlexandrZabolotny** [comment]
> hello, i have a similar problem, But I've found that it always happens on a fixed path, not just any path ，my apollo version: 7.0, Do you have any solutions? thank you

What type of planner do you use (PIECEWISE_JERK_PATH_OPTIMIZER or PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER)?

**Comment by starrye** [comment]
> > hello, i have a similar problem, But I've found that it always happens on a fixed path, not just any path ，my apollo version: 7.0, Do you have any solutions? thank you
> 
> What type of planner do you use (PIECEWISE_JERK_PATH_OPTIMIZER or PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER)?

**PIECEWISE_JERK_PATH_OPTIMIZER**   this is my planning module  log info 

E0227 18:00:43.567451 323875 lane_follow_stage.cc:203] Fail to aggregate planning trajectory.
E0227 18:00:43.567461 323875 scenario.cc:79] Stage 'LANE_FOLLOW_DEFAULT_STAGE' returns error
E0227 18:00:43.567487 323875 on_lane_planning.cc:619] planner failed to make a driving plan
E0227 18:00:43.567514 323875 on_lane_planning.cc:435] Planning failed:PLANNING_ERROR: planner failed to make a driving plan
E0227 18:00:43.681439 323874 piecewise_jerk_problem.cc:105] failed optimization status:        primal infeasible
E0227 18:00:43.681476 323874 piecewise_jerk_path_optimizer.cc:317] piecewise jerk path optimizer failed
E0227 18:00:43.687695 323874 piecewise_jerk_problem.cc:105] failed optimization status:        primal infeasible
E0227 18:00:43.687711 323874 piecewise_jerk_path_optimizer.cc:317] piecewise jerk path optimizer failed
E0227 18:00:43.687742 323874 path_optimizer.cc:49] Reference Line 0_1 is not drivable after PIECEWISE_JERK_PATH_OPTIMIZER
E0227 18:00:43.687754 323874 lane_follow_stage.cc:177] Failed to run tasks[PIECEWISE_JERK_PATH_OPTIMIZER], Error message: Path Optimizer failed to generate path
E0227 18:00:43.687790 323874 lane_follow_stage.cc:265] Path fallback due to algorithm failure
E0227 18:00:43.688119 323874 path_data.cc:44] Should NOT set discretized path when reference line is nullptr. Please set reference line first.
E0227 18:00:43.688127 323874 lane_follow_stage.cc:288] Speed fallback due to algorithm failure
E0227 18:00:43.688130 323874 speed_profile_generator.cc:38] Fallback using piecewise jerk speed!
W0227 18:00:43.688134 323874 speed_profile_generator.cc:41] init_v = 6.03612, init_a = 1.12288
E0227 18:00:43.689057 323874 reference_line_info.cc:503] path data is empty

**Comment by starrye** [comment]
> > hello, i have a similar problem, But I've found that it always happens on a fixed path, not just any path ，my apollo version: 7.0, Do you have any solutions? thank you
> 
> What type of planner do you use (PIECEWISE_JERK_PATH_OPTIMIZER or PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER)?

Excuse me , do you have any solutions?

**Comment by starrye** [comment]
> 您好，关于这个问题有任何更新吗？我面临着类似的问题，你能帮忙吗？

hello，have you solved this problem yet?

**Comment by AlexandrZabolotny** [comment]
> Excuse me , do you have any solutions?
Apollo uses the OSQP open source library for this type of planning.
The Apollo code only forms the problem, namely, it sets the initial conditions, the boundaries on the trajectory and the objective function.
Your error says that there is no trajectory for your given conditions.
Your conditions are formed
- HD map
- dynamic and kinematic characteristics of your car, which you set in the vehicle config.
- restrictions that you impose on your solver (config file I mentioned earlier)

I see several solutions
1. You can continue to try searching for the parameters of the config files that are optimal for you. This is the easiest way
2. You can change your code to change the bounds dynamically.
3. You can also change the code so that your trajectory is saved from the previous optimization step. Although this may be implemented in Apollo. I don't know

**Comment by AlexandrZabolotny** [comment]
I made a mistake last time.
I wanted to clarify about speed optimization.

task_type: PIECEWISE_JERK_SPEED_OPTIMIZER
or
task_type: PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER

It is given [here](https://github.com/ApolloAuto/apollo/blob/9537abebf3e180e8976489bab7166da6d87efaf4/modules/planning/conf/scenario/lane_follow_config.pb.txt#L18) 
Also try changing these [settings](https://github.com/ApolloAuto/apollo/blob/4025df3380d4fa4ae37cd5228b019db81d13d800/modules/planning/conf/planning_config.pb.txt#L40) for PIECEWISE_JERK_SPEED_OPTIMIZER.

Try to set
default_task_config: {
  task_type: PIECEWISE_JERK_SPEED_OPTIMIZER
  piecewise_jerk_speed_optimizer_config {
    acc_weight: 1.4 
    jerk_weight: 3.0
    kappa_penalty_weight: 100.0 
    ref_s_weight: 15
    ref_v_weight: 5
  }
}

**Comment by starrye** [comment]
> > 打扰一下，你有什么解决办法吗？
> 
> Apollo使用osqp开源库开源库此类 规划规划规划代码代码 形成 形成
> 
> * 高精地图
> * 您在车辆配置中设置车辆的动态和运动学特性。
> * 您对请求解析器施加的限制（我之前提到的配置文件）
> 
> 我看到几个解决方案
> 
> 1. 您可以继续尝试搜索最适合您的配置文件的参数。这是最简单的方法
> 2. 您可以更改代码以动态更改边界。
> 3. 您还可以更改代码，以方便从之前的优化步骤中保存您的轨道。虽然这可能会在阿波罗中实现。我不知道

I have tried to modify the parameters you mentioned, but that parameter seems to me to be used for fast merging (modify piecewise_jerk_path_optimizer_config)

**Comment by starrye** [comment]
> > Excuse me , do you have any solutions?
> 
> Apollo uses the OSQP open source library for this type of planning. The Apollo code only forms the problem, namely, it sets the initial conditions, the boundaries on the trajectory and the objective function. Your error says that there is no trajectory for your given conditions. Your conditions are formed
> 
> * HD map
> * dynamic and kinematic characteristics of your car, which you set in the vehicle config.
> * restrictions that you impose on your solver (config file I mentioned earlier)
> 
> I see several solutions
> 
> 1. You can continue to try searching for the parameters of the config files that are optimal for you. This is the easiest way
> 2. You can change your code to change the bounds dynamically.
> 3. You can also change the code so that your trajectory is saved from the previous optimization step. Although this may be implemented in Apollo. I don't know

I have tried to modify the parameters you mentioned, but that parameter seems to me to be used for fast merging (modify piecewise_jerk_path_optimizer_config)

**Comment by starrye** [comment]
> I made a mistake last time. I wanted to clarify about speed optimization.
> 
> task_type: PIECEWISE_JERK_SPEED_OPTIMIZER or task_type: PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER
> 
> It is given [here](https://github.com/ApolloAuto/apollo/blob/9537abebf3e180e8976489bab7166da6d87efaf4/modules/planning/conf/scenario/lane_follow_config.pb.txt#L18) Also try changing these [settings](https://github.com/ApolloAuto/apollo/blob/4025df3380d4fa4ae37cd5228b019db81d13d800/modules/planning/conf/planning_config.pb.txt#L40) for PIECEWISE_JERK_SPEED_OPTIMIZER.
> 
> Try to set default_task_config: { task_type: PIECEWISE_JERK_SPEED_OPTIMIZER piecewise_jerk_speed_optimizer_config { acc_weight: 1.4 jerk_weight: 3.0 kappa_penalty_weight: 100.0 ref_s_weight: 15 ref_v_weight: 5 } }

Thank you for the configuration content you gave, but it doesn't work. Is there any connection between the speed optimizer and the direction? My problem now is that even if the car goes straight, there will be a problem with the direction
![飞书20230301-135417](https://user-images.githubusercontent.com/42433161/222367717-d30338eb-de3e-4efc-8b6b-870707ae405f.png)
