### ISSUE TITLE
Install apollo6.0 with real-time kernel

### ISSUE THREAD

**Issue by Yuyn1234** [ApolloAuto/apollo#12890]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

1. Install 18.04
2.Install apollo-kernel
3.Install nvidia-driver following https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/Install_nvidia_driver_on_ubuntu_18.04.md.
The install-nvidia.sh only supports nvidia-driver-430 which is too outdated to be compatible with apollo6.0.

In fact, I try to change the nvidia-driver-430 to nvidia-driver-450 as follows.
Original:
NV_FILE="NVIDIA-Linux-x86_64-430.50.run"
NV_URL="https://us.download.nvidia.cn/XFree86/Linux-x86_64/430.50/${NV_FILE}"
Changed:
NV_FILE="NVIDIA-Linux-x86_64-450.57.run"
NV_URL="https://us.download.nvidia.cn/XFree86/Linux-x86_64/450.57/${NV_FILE}"

And I install the nvidia-driver-450 successfully. After installing the docker, I run the dev_start.sh to start. But it jams at "starting docker container ..." and the computer crashes.

I think this attributes to the install-nvidia.sh. Because all is ok when I use real-time kernel, nvidia-driver-430 and apollo5.5. Since the latest apollo6.0 can not support nvidia-driver-430, can you provide a correct install-nvidia.sh to install the nvidia-driver-450 with apollo real-time kernel?

**Comment by Yuyn1234** [comment]
GPU is 2080Ti. It jams at:
"
Starting docker container "apollo_dev_e301" ...
+ docker run --gpus all -itd --privileged --name apollo_dev_e301 -e DISPLAY=:0 -e DOCKER_USER=e301 -e USER=e301 -e DOCKER_USER_ID=1000 -e DOCKER_GRP=e301 -e DOCKER_GRP_ID=1000 -e DOCKER_IMG=apolloauto/apollo:dev-x86_64-18.04-20200914_0742 -e USE_GPU_HOST=1 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility --volumes-from apollo_map_volume-sunnyvale_big_loop_e301 --volumes-from apollo_map_volume-sunnyvale_loop_e301 --volumes-from apollo_map_volume-sunnyvale_with_two_offices_e301 --volumes-from apollo_map_volume-san_mateo_e301 --volumes-from apollo_localization_volume_e301 --volumes-from apollo_audio_volume_e301 --volumes-from apollo_yolov4_volume_e301 --volumes-from apollo_faster_rcnn_volume_e301 --volumes-from apollo_local_third_party_volume_e301 -v /home/e301/apollo:/apollo -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in-dev-docker:127.0.0.1 --add-host e301-Nuvo-6108GC:127.0.0.1 --hostname in-dev-docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 apolloauto/apollo:dev-x86_64-18.04-20200914_0742 /bin/bash
34a33fde48ac0b44af0070aba38e2a361122bfa0ad1bd8785adf03617e3a97c3
"

**Comment by Yuyn1234** [comment]
Or maybe the apollo-kernel is too old?

**Comment by SpinClown** [comment]
@jinghaomiao @storypku

**Comment by storypku** [comment]
> Or maybe the apollo-kernel is too old?

Yep. The Apollo-kernel is based on Linux 4.4 and too old today.
The team is currently investigating on how to upgrade it.

**Comment by Yuyn1234** [comment]
> > Or maybe the apollo-kernel is too old?
> 
> Yep. The Apollo-kernel is based on Linux 4.4 and too old today.
> The team is currently investigating on how to upgrade it.

Can you provide the approxiate time you do the job? I hope to combine apollo6.0 with real-time kernel but I am not sure whether I should wait for it.

**Comment by storypku** [comment]
> > > Or maybe the apollo-kernel is too old?
> > 
> > 
> > Yep. The Apollo-kernel is based on Linux 4.4 and too old today.
> > The team is currently investigating on how to upgrade it.
> 
> Can you provide the approxiate time you do the job? I hope to combine apollo6.0 with real-time kernel but I am not sure whether I should wait for it.

I think it would be OK by the end of this year for the worst case and by the end of Nov if everything goes well. Is it OK with you?

**Comment by Yuyn1234** [comment]
> > > > Or maybe the apollo-kernel is too old?
> > > 
> > > 
> > > Yep. The Apollo-kernel is based on Linux 4.4 and too old today.
> > > The team is currently investigating on how to upgrade it.
> > 
> > 
> > Can you provide the approxiate time you do the job? I hope to combine apollo6.0 with real-time kernel but I am not sure whether I should wait for it.
> 
> I think it would be OK by the end of this year for the worst case and by the end of Nov if everything goes well. Is it OK with you?

Thanks for your great team work. I will first remove the old apollo-kernel and test without it. I will use the real-time kernel again until you update it. Thanks you again！

**Comment by lishuanghua** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> ### System information
> 
>     * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
> 
>     * **Apollo installed from (source or binary)**: source
> 
>     * **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
> 
> 
> ### Steps to reproduce the issue:
> 
>     * **Please use bullet points and include as much details as possible**:
> 
> 
>     1. Install 18.04
>        2.Install apollo-kernel
>        3.Install nvidia-driver following https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/Install_nvidia_driver_on_ubuntu_18.04.md.
>        The install-nvidia.sh only supports nvidia-driver-430 which is too outdated to be compatible with apollo6.0.
> 
> 
> In fact, I try to change the nvidia-driver-430 to nvidia-driver-450 as follows.
> Original:
> NV_FILE="NVIDIA-Linux-x86_64-430.50.run"
> NV_URL="[https://us.download.nvidia.cn/XFree86/Linux-x86_64/430.50/${NV_FILE}](https://us.download.nvidia.cn/XFree86/Linux-x86_64/430.50/$%7BNV_FILE%7D)"
> Changed:
> NV_FILE="NVIDIA-Linux-x86_64-450.57.run"
> NV_URL="[https://us.download.nvidia.cn/XFree86/Linux-x86_64/450.57/${NV_FILE}](https://us.download.nvidia.cn/XFree86/Linux-x86_64/450.57/$%7BNV_FILE%7D)"
> 
> And I install the nvidia-driver-450 successfully. After installing the docker, I run the dev_start.sh to start. But it jams at "starting docker container ..." and the computer crashes.
> 
> I think this attributes to the install-nvidia.sh. Because all is ok when I use real-time kernel, nvidia-driver-430 and apollo5.5. Since the latest apollo6.0 can not support nvidia-driver-430, can you provide a correct install-nvidia.sh to install the nvidia-driver-450 with apollo real-time kernel?

Maybe you can see this and have a try below. You can change the version of the nvidia driver to your own.
[https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Waypoint_Following/apollo_installation_cn.md#%E5%AE%89%E8%A3%85GPU%E9%A9%B1%E5%8A%A8](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Waypoint_Following/apollo_installation_cn.md#%E5%AE%89%E8%A3%85GPU%E9%A9%B1%E5%8A%A8)

**Comment by lishuanghua** [comment]
> GPU is 2080Ti. It jams at:
> "
> Starting docker container "apollo_dev_e301" ...
> 
>     * docker run --gpus all -itd --privileged --name apollo_dev_e301 -e DISPLAY=:0 -e DOCKER_USER=e301 -e USER=e301 -e DOCKER_USER_ID=1000 -e DOCKER_GRP=e301 -e DOCKER_GRP_ID=1000 -e DOCKER_IMG=apolloauto/apollo:dev-x86_64-18.04-20200914_0742 -e USE_GPU_HOST=1 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility --volumes-from apollo_map_volume-sunnyvale_big_loop_e301 --volumes-from apollo_map_volume-sunnyvale_loop_e301 --volumes-from apollo_map_volume-sunnyvale_with_two_offices_e301 --volumes-from apollo_map_volume-san_mateo_e301 --volumes-from apollo_localization_volume_e301 --volumes-from apollo_audio_volume_e301 --volumes-from apollo_yolov4_volume_e301 --volumes-from apollo_faster_rcnn_volume_e301 --volumes-from apollo_local_third_party_volume_e301 -v /home/e301/apollo:/apollo -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in-dev-docker:127.0.0.1 --add-host e301-Nuvo-6108GC:127.0.0.1 --hostname in-dev-docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 apolloauto/apollo:dev-x86_64-18.04-20200914_0742 /bin/bash
>       34a33fde48ac0b44af0070aba38e2a361122bfa0ad1bd8785adf03617e3a97c3
>       "

GTX1080,RTX2060S and RTX2070S are OK.Best wishes your 2080Ti following above.

**Comment by storypku** [comment]
> > > > > Or maybe the apollo-kernel is too old?
> > > > 
> > > > 
> > > > Yep. The Apollo-kernel is based on Linux 4.4 and too old today.
> > > > The team is currently investigating on how to upgrade it.
> > > 
> > > 
> > > Can you provide the approxiate time you do the job? I hope to combine apollo6.0 with real-time kernel but I am not sure whether I should wait for it.
> > 
> > 
> > I think it would be OK by the end of this year for the worst case and by the end of Nov if everything goes well. Is it OK with you?
> 
> Thanks for your great team work. I will first remove the old apollo-kernel and test without it. I will use the real-time kernel again until you update it. Thanks you again！

Hi @Yuyn1234 , we have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. Please follow these docs to install PREEMPT/PREEMPT_RT kernels for Apollo. 

Thank you.
