### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by JayDDD** [ApolloAuto/apollo#129]
![apollo](https://user-images.githubusercontent.com/20727164/28052267-78bad14e-65f9-11e7-9903-72ee647cc582.png)

How to fix this problem?

**Comment by startcode** [comment]
which command leads to this problem? 
In which directory did you run this command?

**Comment by JayDDD** [comment]
In docker
command: rosbag play -l ./docs/demo_guide/demo.bag

**Comment by startcode** [comment]
Can you find this file `demo.bag` in your directory?
Can you show me the output of the command？
```
pwd
```
If it the file is really not there for some reason, you can download it by
```
https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/demo.bag
```
Then run 
```
rosbag play -l demo.bag
```

**Comment by JayDDD** [comment]
yes, file is there.
output of pwd: /home/nvidiapx2/Desktop/apollo/apollo-master/docker

**Comment by startcode** [comment]
You can run the command in the apollo folder. In your case, I guess you need to be in folder 
```
 /home/nvidiapx2/Desktop/apollo/apollo-master/
```

**Comment by JayDDD** [comment]
Wow, it works!!
Thank you so much.
But why is that, according to the tutorial I should run the cmd under docker, right?

**Comment by JayDDD** [comment]
It might be a misunderstanding from me.

**Comment by startcode** [comment]
I see the problem. The document is misleading.
In the [README.md](https://github.com/ApolloAuto/apollo/blob/master/README.md)
>```
# in a different terminal inside docker
rosbag play -l ./docs/demo_guide/demo.bag
```
`inside docker` means inside the docker container, not the docker directory. There is accidentally a `docker` directory.
I will update the misleading document.
Thanks for reporting this problem.
