### ISSUE TITLE
tf2_ros static_transform_publisher for Lidar 

### ISSUE THREAD

**Issue by Abd0ul** [ApolloAuto/apollo#12904]
Hello, I have a problem with the static transformation topics. The lidar needs the gnss driver for the compensation which is based on the transformation of tf coordinates.
When I launch the lidar topic the monitor does not recognize it as in image 1, however the static transformation nodes are activated.

![Capture d’écran de 2020-11-03 18-25-23](https://user-images.githubusercontent.com/60668969/98020527-68fbce00-1e03-11eb-817b-919057d38c9d.png)

But when I run the following command:
```
rosrun tf2_ros static_transform_publisher 0 0 0 0 0 0 0 world novatel 
```
there the monitor recognizes the lidar and I retrieve the data on the lidar topic:

![Capture d’écran de 2020-11-03 18-26-20](https://user-images.githubusercontent.com/60668969/98020578-7a44da80-1e03-11eb-86cf-4fe518909832.png)

Here is the procedure I use:
```
$ bash docker/scripts/dev_start.sh
$ bash docker/scripts/dev_into.sh
$ bash apollo.sh build_gpu
$ bash scripts/bootstrap.sh start
$ roslaunch gnss_driver gnss_driver.launch 
$ ./scripts/gps.sh

```
then I start the lidar module from dreamview.
Can you help me understand the cause?

**Comment by jeroldchen** [comment]
Please provide the Apollo version that you are using.

**Comment by Abd0ul** [comment]
it's ok, this solved thanks for your feedback.
