### ISSUE TITLE
Cyber_visualizer is abnormal with apollo-kernel

### ISSUE THREAD

**Issue by Yuyn1234** [ApolloAuto/apollo#12901]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.5

Cyber visualizer can not display the camera images and pointclouds normally but cyber_monitor is right. Is it related to the apollo-kernel? Camera images displayed in visualizer are the white background and pointclouds are white with lots of noise.

**Comment by storypku** [comment]
The Apollo Kernel is too old for Ubuntu 18.04 now. Please try running cyber_visualizer on Ubuntu kernels  directly with Nvidia drivers and docker-container-toolkit installed, and see if the problem persists.

**Comment by storypku** [comment]
Hi @Yuyn1234 ,  we have updated Low-Latency / Realtime Kernel Installation Guide ([English]([https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. Please follow these docs to install PREEMPT/PREEMPT_RT kernels for Apollo. 

Thank you.
