### ISSUE TITLE
Apollol 6.0 Camera perception

### ISSUE THREAD

**Issue by chinnikrishna55** [ApolloAuto/apollo#12916]
Is camera perception working in apollo 6.0? I am getting following error 

[motion ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[camera ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[motion ]  I1104 14:53:30.016518 72935 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion -s CYBER_DEFAULT 
[camera ]  I1104 14:53:30.016619 72933 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p camera -s CYBER_DEFAULT 
[motion ]  I1104 14:53:30.017052 72935 global_data.cc:153] []host ip: 192.168.1.102
[camera ]  I1104 14:53:30.017071 72933 global_data.cc:153] []host ip: 192.168.1.102
[motion ]  I1104 14:53:30.017208 72935 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is motion, has 1 dag conf
[camera ]  I1104 14:53:30.017220 72933 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is camera, has 1 dag conf
[motion ]  I1104 14:53:30.017213 72935 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_motion_service.dag
[camera ]  I1104 14:53:30.017225 72933 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
[motion ]  E1104 14:53:30.018187 72935 module_controller.cc:87] [mainboard]Path does not exist: /apollo/bazel-bin/modules/perception/camera/lib/motion_service/libmotion_service.so
[motion ]  E1104 14:53:30.018203 72935 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_motion_service.dag
[motion ]  E1104 14:53:30.018206 72935 mainboard.cc:39] [mainboard]module start error.
[motion ]  
[camera ]  E1104 14:53:30.385419 72933 class_loader_manager.h:70] [mainboard]Invalid class name: FusionCameraDetectionComponent
[camera ]  E1104 14:53:30.385435 72933 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
[camera ]  E1104 14:53:30.387018 72933 mainboard.cc:39] [mainboard]module start error.
[camera ]  
[cyber_launch_72926] ERROR Process [camera] has died [pid 72933, exit code 255, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p camera -s CYBER_DEFAULT].
[cyber_launch_72926] ERROR Process [motion] has died [pid 72935, exit code 255, cmd mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion -s CYBER_DEFAULT].

**Comment by jeroldchen** [comment]
@chinnikrishna55 Camera perception is in process of refactoring, so it is not available in Apollo 6.0 yet. Please use our former versions if you need camera perception, or look forward to our future releases. Thank you for your interest in Apollo.

**Comment by FitashUlHaq** [comment]
Hi, is there any update on this? will the camera perception available??

**Comment by InterKnight** [comment]
Is Camera perception available now in master branch? Thank you! @jeroldchen

**Comment by ravkum** [comment]
Hi, is camera perception available now in the master branch?

**Comment by InterKnight** [comment]
> Hi, is camera perception available now in the master branch?

Yes

**Comment by ravkum** [comment]
> > Hi, is camera perception available now in the master branch?
> 
> Yes

Thank you.
