### ISSUE TITLE
Publish just once using cyber_writer

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#12929]
Hi, I am working on an application where I need to publish a message just once to a channel (for example routing request). For some reason, writer doesn't work when I'm trying to do that. The same code when I run inside a while loop, it prints messages to the desired channel. Any idea what might be going wrong ?

**Comment by daohu527** [comment]
You can send a message by `writer` and it will send msg only once. If not, you should check the caller, does the caller only run once?

Especially when you call `writer` in the component proc. If proc is not triggered, then writer will not trigger either.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
