### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ydhongHIT** [ApolloAuto/apollo#12920]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Run the "mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.dag"
There is an error reported:
"
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1105 19:10:43.493423 15204 module_argument.cc:81] []command: mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.dag 
I1105 19:10:43.494010 15204 global_data.cc:155] []host ip: 192.168.1.155
I1105 19:10:43.494601 15204 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I1105 19:10:43.494617 15204 module_argument.cc:60] []dag_conf: ./modules/perception/production/dag/dag_streaming_perception_lane.dag
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[NVBLAS] Cannot open default config file 'nvblas.conf'
[NVBLAS] Config parsed
[NVBLAS] CPU Blas library need to be provided
Segmentation fault (core dumped)
"
I use the gdb to debug. The information is as follows.
"
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f94e7446030 in caffe::Caffe::RNG::generator() () from /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0
[Current thread is 1 (Thread 0x7f958eaf5340 (LWP 15204))]
"
How can I solve this problem? Please help me.

**Comment by qwetqwe** [comment]
I have the same problem

**Comment by jeroldchen** [comment]
@Yuyn1234 Could you build Apollo in debug mode by running `./apollo.sh build`? Then you can launch lane perception again using gdb debugger. Run `bt` command inside gdb after it crashes and give us the outcoming backtrace information for diagnosis.

**Comment by Yuyn1234** [comment]
I use another version of apollo5.5 and the problem disappears.

**Comment by younggam94** [comment]
> I use another version of apollo5.5 and the problem disappears.

@Yuyn1234 : I would like to have gdb debug. can you please let me know the instruction or step for using gdb?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
