### ISSUE TITLE
Can't really open the modules.

### ISSUE THREAD

**Issue by sidingxin** [ApolloAuto/apollo#12937]
I am tying to use Apollo with lgsvl.
**Version:**The docker version is apolloauto/apollo:dev-x86_64-18.04-20201029_0431.
**System:**Ubuntu18.04
but I can't open the modules actully without Sim Control. 
the modules I open below.
![open modules](https://user-images.githubusercontent.com/42139299/98465760-291f5700-2206-11eb-974f-f82f74564f32.png)
but the difference with and without Sim Control on.as below.
![simc](https://user-images.githubusercontent.com/42139299/98465783-608e0380-2206-11eb-8c2b-80af6330dd0f.png)
![no modules](https://user-images.githubusercontent.com/42139299/98465785-6257c700-2206-11eb-8037-c1f7a20c7f1b.png)

Please tell me what can I do to relsove this.very very very thanks!

**Comment by daohu527** [comment]
Why you don't enable perception and prediction module? The planning module will require two topics.

**Comment by Manoj-EK** [comment]
@sidingxin I too had similar problems even after installing as mentioned in lgsvl simulator instuctions...

I would first request you to check whether you have launched bridge inside a container...If not , navigate  inside a container and then run following command:  " ./scripts/bridge.sh " (Ref: https://www.lgsvlsimulator.com/docs/apollo-master-instructions/)

once you are done with it..now open dream view,select appropriate setup mode,vehicle and map..then in Tasks tab--->Quick start---->setup (this will automatically turn on all related modules)...Hope this helps

**Comment by sidingxin** [comment]
ths your reply!  I have done it as you say already.And I am starting the bootstrap_lgsvl.sh first and then bridge.sh. But The module delay cant show anything even if I clink the &quot;setup&quot; which almostly open all modules. but it works fine when I turn on the Sim Ctrl.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Manoj&amp;nbsp;Kumar&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月15日(星期天) 晚上11:01
收件人:&nbsp;&quot;ApolloAuto/apollo&quot;<apollo@noreply.github.com&gt;;
抄送:&nbsp;&quot;sidingxin&quot;<960094569@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ApolloAuto/apollo] Can&#39;t really open the modules. (#12937)

**Comment by Manoj-EK** [comment]
@sidingxin...Did you play the simulation in lgsvl simulator and checked for **Bridge status:connected** from connection tab as mentioned in the picture below...becoz if signals from lgsvl are not sent...it might not work

![bridge connection](https://user-images.githubusercontent.com/65737691/99190124-13111980-2765-11eb-9462-aaeef4fea885.png)

**Comment by sidingxin** [comment]
Yes,the state is connected and many topics is PUBing to the bridge. The only working module is Localization because the map is showing on the dreamview after I turn it on. The other module's log saying as: Control:No planning msg is ready. Planning:No routing is ready. And nothing show out in the routing 's log even if I send a routing request.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Manoj&amp;nbsp;Kumar&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月16日(星期一) 凌晨0:10
收件人:&nbsp;&quot;ApolloAuto/apollo&quot;<apollo@noreply.github.com&gt;;
抄送:&nbsp;&quot;sidingxin&quot;<960094569@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ApolloAuto/apollo] Can&#39;t really open the modules. (#12937)

**Comment by Manoj-EK** [comment]
@sidingxin you can look at the issue #12998 .............it might help

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
