### ISSUE TITLE
Apollo with native macOS support

### ISSUE THREAD

**Issue by shyamalschandra** [ApolloAuto/apollo#12935]
I would like Apollo with native macOS support.  Thanks!

**Comment by storypku** [comment]
> I would like Apollo with native macOS support. Thanks!

You mean running Apollo directly on macOS, or just running Apollo Docker container on top of macOS?

**Comment by storypku** [comment]
> > I would like Apollo with native macOS support. Thanks!
> 
> You mean running Apollo directly on macOS, or just running Apollo Docker container on top of macOS?

For the latter, running Apollo Docker on macOS hosts was once provided in previous Apollo releases, although with some restrictions and limitations. Hope that we can bring it back.

Please stay tuned. Once we are ready, we should let everyone noticed.
