### ISSUE TITLE
Installing NVIDIA Container Toolkit on Ubuntu 20.10 host.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#12934]
Hi,

The NVIDIA Container Toolkit is one of the prerequisites of apollo software stack as described [here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/prerequisite_software_installation_guide.md#installing-nvidia-container-toolkit). But for my case, I've just upgraded my host OS to Ubuntu 20.10 but it seems that there is no appropriate nvidia-docker version released for it yet just as I've pointed out [here](https://github.com/NVIDIA/nvidia-docker/issues/1407). Any hints for the installation of nvidia-docker on Ubuntu 20.10? 

The OS info is shown below:
```

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```
Regards,
HY

**Comment by storypku** [comment]
Experimenting with bleeding edge OS/software releases usually means that you have to and are able to manage the risks on your own, as the official support hasn't been ready yet.

For the `nvidia-docker` case, I think you can try to install it from source following the instructions available on its GitHub page.

**Comment by hongyi-zhao** [comment]
The list of [supported Linux distributions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#linux-distributions) don't include Ubuntu 20.10 at all. So, I really stuck there.

**Comment by storypku** [comment]
This issue is a `nvidia-docker` one. Please wait for the response from the `nvidia-docker` developers.
Thanks for using Apollo.

**Comment by hongyi-zhao** [comment]
Got it. See [here](https://github.com/NVIDIA/nvidia-docker/issues/1407) for more info on this problem.
