### ISSUE TITLE
Where can I download Apollo-Southbay dataset now?

### ISSUE THREAD

**Issue by lizimo061** [ApolloAuto/apollo#12948]
I can find the information here [https://data.apollo.auto/?locale=en-us&lang=en](url) but the download button is disabled I think? Would anyone provide a new link to the dataset? Thanks.

**Comment by storypku** [comment]
@jinghaomiao @ycool @Capri2014 @xiaoxq 

Please help with this issue.

**Comment by jinghaomiao** [comment]
@lizimo061 thanks for your interest in Apollo. Due to system upgrade, dataset downloads are disabled till further notice.

**Comment by jinghaomiao** [comment]
This issue is being closed. Should you have new questions, please feel free to raise issues again. Thanks for your interest in Apollo.

**Comment by cattaneod** [comment]
Hi, I can't download the Apollo-Southbay dataset, it requires a baidu account, which I can't create because it only accept registration from china.
