### ISSUE TITLE
约束检测加速度公式

### ISSUE THREAD

**Issue by HandsomeDragon3** [ApolloAuto/apollo#12951]
约束检测constraint_checker1d.cc中
横向 a = d2d_ds2 * ds_dt * ds_dt + dd_ds * d2s_dt2;
这个公式没问题把？感觉前后两部分不对称啊，有参考资料和公式推导没呀？

**Comment by zerolover** [comment]
<img src="https://render.githubusercontent.com/render/math?math=%5Cbegin%7Baligned%7D%5Cfrac%7B%5Cpartial%5E%7B2%7Dl%7D%7B%5Cpartial%20t%5E%7B2%7D%7D%20%26%20%3D%5Cfrac%7B%5Cpartial%5Cleft(%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20t%7D%5Cright)%7D%7B%5Cpartial%20t%7D%3D%5Cfrac%7B%5Cpartial%5Cleft(%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20s%7D%5Cfrac%7B%5Cpartial%20s%7D%7B%5Cpartial%20t%7D%5Cright)%7D%7B%5Cpartial%20t%7D%5C%5C%0A%20%26%20%3D%5Cfrac%7B%5Cpartial%5Cleft(%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20s%7D%5Cright)%7D%7B%5Cpartial%20t%7D%5Cfrac%7B%5Cpartial%20s%7D%7B%5Cpartial%20t%7D%2B%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20s%7D%5Cfrac%7B%5Cpartial%5E%7B2%7Ds%7D%7B%5Cpartial%20t%5E%7B2%7D%7D%5C%5C%0A%20%26%20%3D%5Cfrac%7B%5Cpartial%5Cleft(%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20s%7D%5Cright)%7D%7B%5Cpartial%20s%7D%5Cfrac%7B%5Cpartial%20s%7D%7B%5Cpartial%20t%7D%5Cfrac%7B%5Cpartial%20s%7D%7B%5Cpartial%20t%7D%2B%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20s%7D%5Cfrac%7B%5Cpartial%5E%7B2%7Ds%7D%7B%5Cpartial%20t%5E%7B2%7D%7D%5C%5C%0A%20%26%20%3D%5Cfrac%7B%5Cpartial%5E%7B2%7Dl%7D%7B%5Cpartial%20s%5E%7B2%7D%7D%5Cfrac%7B%5Cpartial%20s%7D%7B%5Cpartial%20t%7D%5Cfrac%7B%5Cpartial%20s%7D%7B%5Cpartial%20t%7D%2B%5Cfrac%7B%5Cpartial%20l%7D%7B%5Cpartial%20s%7D%5Cfrac%7B%5Cpartial%5E%7B2%7Ds%7D%7B%5Cpartial%20t%5E%7B2%7D%7D%0A%5Cend%7Baligned%7D">

**Comment by HandsomeDragon3** [comment]
3Q
