### ISSUE TITLE
ubuntu18.04 vscode terminal "bash apollo.sh build" error

### ISSUE THREAD

**Issue by ilovevision** [ApolloAuto/apollo#12956]
ubuntu18.04
https://github.com/ApolloAuto/apollo/
6.0

vscode terminal "bash apollo.sh build" error
mkdir '/apollo/.cache/bazel/' permission denied

**Comment by ilovevision** [comment]
lgsvl/apollo5.0  the same operation  is OK，"apollo.sh build" is passed.

**Comment by storypku** [comment]
> ubuntu18.04
> https://github.com/ApolloAuto/apollo/
> 6.0
> 
> vscode terminal "bash apollo.sh build" error
> mkdir '/apollo/.cache/bazel/' permission denied

What about remove /apollo/.cache from container, and try again?

**Comment by ilovevision** [comment]
It works. I have tried to remove "rm -rf /home/$USER/.cache/bazel/" ,but it didn't work. Thank you very much.
