### ISSUE TITLE
cyber_time.py

### ISSUE THREAD

**Issue by leeyuanalibaba** [ApolloAuto/apollo#12969]
** call now() to construct cyber_time.Duration, Time instance,  will return 0 while __init__ is long value  **

**To Reproduce**
1. run cyber/python/cyber_py/example/time.py , cyber_time.Time.now() will return null 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
fix given as bellow in my local,
    def __init__(self, other):
        if isinstance(other, int):
            nanoseconds = other
        elif isinstance(other, long):  #  <----------- added
            nanoseconds = other
        elif isinstance(other, float):
            nanoseconds = other * 1000000000
        elif isinstance(other, Time):
            nanoseconds = other.to_nsec()

**Comment by storypku** [comment]
> 1. cyber/python/cyber_py/example/time.py

Could you please describe the Apollo version used?

FYI, Python2 support for CyberRT was retired in Apollo 6.0 and no longer maintained.

**Comment by daohu527** [comment]
Python 2 will automatically set the type based on the size of the value. A guide of max values can be found below.
```python
>> print type(65535)
<type 'int'>
>>> print type(65536*65536)
<type 'long'>
```
In Python 3 the long datatype has been removed and all integer values are handled by the Int class

[ref](https://stackoverflow.com/questions/2104884/how-does-python-manage-int-and-long)
