### ISSUE TITLE
Please help: How do I test the operation of the system without a real car?

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#12961]
Hi guys, I am new to Apollo system. I have followed the set up instructions and all went smoothly. Since I don't have a real test car, I will test the system fully on my computer. I have downloaded and ran the demo following the command `cyber_recorder play -f docs/demo_guide/demo_3.5.record -l`, and the system worked as expected.

However, after that, I am confused about the usage of the system. I have selected other maps but nothing works. Specifically, after clicking the "Set up" button, I cannot further click the "start Auto" button, as screenshot shows. 

![Screenshot from 2020-11-11 20-57-16](https://user-images.githubusercontent.com/42797233/98814476-b1993400-2460-11eb-9cd2-9199603c7275.png)

Are there any additional maps or things like the "demo" that I need to download? I saw the "Onboard test" but I think that requires a real car to perform. So **how do I test the operation of the system without a real car?**

I am a software tester and I want to test the stability of Apollo system.

Many Thanks!!!

**Comment by ntutangyun** [comment]
you could try out LGSVL simulator

**Comment by GabrielZZZ** [comment]
Thanks for your reply@ntutangyun, actually I just moved from LGSVL Simulator to here since it seems that the simulator cannot provide perfectly support with RTX 2080ti Graphics card. Therefore I am looking for a solution without using this simulator (for now)

**Comment by daohu527** [comment]
1. If you focus on the planning module, sim_control can meet your needs.
2. If you want to do end-to-end simulation, any simulation requires a GPU card, so solve it. There are other choices like airsim and carla.

**Comment by GabrielZZZ** [comment]
Thanks. I will close this issue now.
