### ISSUE TITLE
How to use V2X?

### ISSUE THREAD

**Issue by WXTN** [ApolloAuto/apollo#12963]
Hi,  developments !
We plan to use V2X module, but wo haven't found official documentation in V2X module folder.
Is there any official documentation about V2X can tell us how to use it ?

Thanks!

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:  **Linux Ubuntu 18.04**
- **Apollo installed from (source or binary)**: **source**
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: **6.0**
- **Output of `apollo.sh config` if on `master` branch**:

**Comment by daohu527** [comment]
1. The V2X module will require hardware OBU and RSU to run, first make sure it is ready.
2. Apollo use grpc communication with OBU, you should run the client and server in both side.
3. Do some test then.

**Comment by a982865151** [comment]
**I am from OEM, doing the job about V2X algorithm.I beg for manual book too....**

**Comment by arielfly89** [comment]
Can I get more imformation about the OBU hardware?
Thanks.

**Comment by daohu527** [comment]
Apollo's v2x module and obu device have been decoupled, there're design by modules and use grpc to communication. So you can use any OBU.

So you need to provide detailed questions, broad questions are not easy to answer
