### ISSUE TITLE
apollo simulate with lgsvl, perception cannot start

### ISSUE THREAD

**Issue by Tim0083** [ApolloAuto/apollo#12977]
- **OS Platform and Distribution Linux Ubuntu 18.04
- **Apollo installed from source 
- **Apollo version  6.0
- **Output of `apollo.sh config` if on `master` branch**:

cannot start perception and traffic light on dreamview.
manual start by cyber_launch ...perception_all.launch. still cannot start 

root@in-dev-docker:/apollo# cyber_launch start modules/p
erception/production/launch/perception_all.launch
[cyber_launch_4806] INFO Launch file [/apollo/modules/perception/production/launch/perception_all.launch]
[cyber_launch_4806] INFO ========================================================================================================================
[cyber_launch_4806] INFO Load module [perception] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception.dag] exception_handler: []
[cyber_launch_4806] INFO Start process [perception] successfully. pid: 4815
[cyber_launch_4806] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_4806] INFO Load module [perception_camera] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: []
[cyber_launch_4806] INFO Load module [perception_traffic_light] library: [perception_trafficlights] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag] exception_handler: []
[cyber_launch_4806] INFO Start process [perception_trafficlights] successfully. pid: 4817
[cyber_launch_4806] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_4806] INFO Load module [motion_service] library: [motion_service] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_motion_service.dag] exception_handler: []
[cyber_launch_4806] INFO Start process [motion_service] successfully. pid: 4819
[cyber_launch_4806] INFO ------------------------------------------------------------------------------------------------------------------------
[perception]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception]  I1112 21:07:48.192126  4815 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT 
[perception]  I1112 21:07:48.193212  4815 module_argument.cc:120] []Found non-option ARGV-element "/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag"
[perception]  I1112 21:07:48.193465  4815 module_argument.cc:29] []Usage: 
[perception]      mainboard [OPTION]...
[perception]  Description: 
[perception]      -h, --help : help information 
[perception]      -d, --dag_conf=CONFIG_FILE : module dag config file
[perception]      -p, --process_group=process_group: the process namespace for running this module, default in manager process
[perception]      -s, --sched_name=sched_name: sched policy conf for hole process, sched_name should be conf in cyber.pb.conf
[perception]  Example:
[perception]      mainboard -h
[perception]      mainboard -d dag_conf_file1 -d dag_conf_file2 -p process_group -s sched_name
[motion_service]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[motion_service]  I1112 21:07:48.219610  4819 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion_service -s CYBER_DEFAULT 
[motion_service]  I1112 21:07:48.220782  4819 global_data.cc:153] []host ip: 192.168.0.110
[motion_service]  I1112 21:07:48.221784  4819 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is motion_service, has 1 dag conf
[motion_service]  I1112 21:07:48.222285  4819 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_motion_service.dag
[perception_trafficlights]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_trafficlights]  I1112 21:07:48.228976  4817 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT 
[perception_trafficlights]  I1112 21:07:48.229436  4817 global_data.cc:153] []host ip: 192.168.0.110
[perception_trafficlights]  I1112 21:07:48.229809  4817 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception_trafficlights, has 1 dag conf
[perception_trafficlights]  I1112 21:07:48.229820  4817 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag
[motion_service]  E1112 21:07:48.292135  4819 module_controller.cc:87] [mainboard]Path does not exist: /apollo/bazel-bin/modules/perception/camera/lib/motion_service/libmotion_service.so
[motion_service]  E1112 21:07:48.292213  4819 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_motion_service.dag
[motion_service]  E1112 21:07:48.292219  4819 mainboard.cc:39] [mainboard]module start error.
[motion_service]  
[perception_trafficlights]  terminate called after throwing an instance of 'std::runtime_error'
[perception_trafficlights]    what():  The following operation failed in the TorchScript interpreter.
[perception_trafficlights]  Traceback of TorchScript, serialized code (most recent call last):
[perception_trafficlights]    File "code/__torch__/detectron2/export/caffe2_modeling.py", line 14, in forward
[perception_trafficlights]      data, im_info, = argument_1
[perception_trafficlights]      input = torch.div(torch.sub(data, _4, alpha=1), _3)
[perception_trafficlights]      _5, _6, _7, _8, _9, _10, = (_2).forward(input, )
[perception_trafficlights]                                  ~~~~~~~~~~~ <--- HERE
[perception_trafficlights]      _11 = (_1).forward(_5, _6, _7, _8, _9, im_info, )
[perception_trafficlights]      _12 = (_0).forward(_11, _5, _6, _7, _10, im_info, )
[perception_trafficlights]    File "code/__torch__/detectron2/modeling/backbone/fpn.py", line 25, in forward
[perception_trafficlights]      _7 = self.fpn_output5
[perception_trafficlights]      _8 = self.fpn_lateral5
[perception_trafficlights]      _9, _10, _11, _12, = (self.bottom_up).forward(input, )
[perception_trafficlights]                            ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
[perception_trafficlights]      _13 = (_8).forward(_9, )
[perception_trafficlights]      _14 = (_7).forward(_13, )
[perception_trafficlights]    File "code/__torch__/detectron2/modeling/backbone/resnet.py", line 14, in forward
[perception_trafficlights]      _1 = self.res4
[perception_trafficlights]      _2 = self.res3
[perception_trafficlights]      _3 = (self.res2).forward((self.stem).forward(input, ), )
[perception_trafficlights]                                ~~~~~~~~~~~~~~~~~~ <--- HERE
[perception_trafficlights]      _4 = (_2).forward(_3, )
[perception_trafficlights]      _5 = (_1).forward(_4, )
[perception_trafficlights]    File "code/__torch__/detectron2/modeling/backbone/resnet.py", line 24, in forward
[perception_trafficlights]    def forward(self: __torch__.detectron2.modeling.backbone.resnet.BasicStem,
[perception_trafficlights]      input: Tensor) -> Tensor:
[perception_trafficlights]      input0 = torch.relu_((self.conv1).forward(input, ))
[perception_trafficlights]                            ~~~~~~~~~~~~~~~~~~~ <--- HERE
[perception_trafficlights]      input1 = torch.max_pool2d(input0, [3, 3], [2, 2], [1, 1], [1, 1], False)
[perception_trafficlights]      return input1
[perception_trafficlights]    File "code/__torch__/detectron2/layers/wrappers/___torch_mangle_13.py", line 10, in forward
[perception_trafficlights]      _0 = self.norm
[perception_trafficlights]      input0 = torch._convolution(input, self.weight, None, [2, 2], [3, 3], [1, 1], False, [0, 0], 1, False, False, True)
[perception_trafficlights]      return (_0).forward(input0, )
[perception_trafficlights]              ~~~~~~~~~~~ <--- HERE
[perception_trafficlights]    File "code/__torch__/detectron2/layers/wrappers/___torch_mangle_13.py", line 9, in forward
[perception_trafficlights]      input: Tensor) -> Tensor:
[perception_trafficlights]      _0 = self.norm
[perception_trafficlights]      input0 = torch._convolution(input, self.weight, None, [2, 2], [3, 3], [1, 1], False, [0, 0], 1, False, False, True)
[perception_trafficlights]               ~~~~~~~~~~~~~~~~~~ <--- HERE
[perception_trafficlights]      return (_0).forward(input0, )
[perception_trafficlights]  
[perception_trafficlights]  Traceback of TorchScript, original code (most recent call last):
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py(350): _conv_forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py(353): forward
[perception_trafficlights]  /home/lishaohua01/Workspace/detection/detectron2/detectron2/layers/wrappers.py(94): forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
[perception_trafficlights]  /home/lishaohua01/Workspace/detection/detectron2/detectron2/modeling/backbone/resnet.py(356): forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
[perception_trafficlights]  /home/lishaohua01/Workspace/detection/detectron2/detectron2/modeling/backbone/resnet.py(432): forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
[perception_trafficlights]  /home/lishaohua01/Workspace/detection/detectron2/detectron2/modeling/backbone/fpn.py(123): forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
[perception_trafficlights]  /home/lishaohua01/Workspace/detection/detectron2/detectron2/export/caffe2_modeling.py(269): forward
[perception_trafficlights]  /usr/lib/python3.6/contextlib.py(52): inner
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
[perception_trafficlights]  /home/lishaohua01/.local/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
[perception_trafficlights]  /home/lishaohua01/Workspace/detection/detectron2/detectron2/export/api.py(142): export_torchscript
[perception_trafficlights]  tools/deploy/caffe2_converter.py(73): <module>
[perception_trafficlights]  RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
[perception_trafficlights]  
[cyber_launch_4806] ERROR Process [perception] has died [pid 4815, exit code 1, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT].
[cyber_launch_4806] ERROR Process [perception_trafficlights] has died [pid 4817, exit code -6, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT].
[cyber_launch_4806] ERROR Process [motion_service] has died [pid 4819, exit code 255, cmd mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion_service -s CYBER_DEFAULT].
[cyber_launch_4806] INFO All processes has died.
[cyber_launch_4806] INFO Cyber exit.
[cyber_launch_4806] INFO All processes have been stopped.

**Comment by Manoj-EK** [comment]
@Tim0083  you can have a look at the issue #12998

**Comment by Tim0083** [comment]
@Manoj-EK ths,its worked
