### ISSUE TITLE
Please help: Apollo Dreamview not start properly

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#12978]
Hi all. I have recently encountered this issue that Apollo Dreamview cannot work with LGSVL Simulator. The Apollo version is 6.0, and system is Ubuntu 20.04. here are the screenshots:
![Screenshot from 2020-11-13 11-22-56](https://user-images.githubusercontent.com/42797233/99025179-33917600-25a3-11eb-970a-54d15567e9f5.png)
![Screenshot from 2020-11-13 11-23-04](https://user-images.githubusercontent.com/42797233/99025187-368c6680-25a3-11eb-94b8-9bf06b1c4381.png)

After I starting following the command `./scripts/bootstrap_lgsvl.sh` and `./scripts/bridge.sh`, the LGSVL simulator operates normally but there is nothing shows in the Dreamview. I have tried restart Dreamview with command `./scripts/bootstrap_lgsvl.sh restart` and also tried reboot the system, but nothing works.

This issue firstly happens today, after yesterday I running the Dreamview with the official demo. The day before yesterday the Dreamview and LGSVL simulator works fine.

Can anyone offer me some kind of solutions? Do I need to reinstall something?

**Comment by daohu527** [comment]
First, use cyber_monitor to check if you have location msg received `/apollo/sensor/gnss/odometry` `/apollo/sensor/gnss/ins_stat`.

If there are no messages check the bridge is work well then.

**Comment by GabrielZZZ** [comment]
Thanks @daohu527 . Here are the screenshots of cyber_monitor, simulator and terminal:
![Screenshot from 2020-11-13 15-38-21](https://user-images.githubusercontent.com/42797233/99041921-c1cb2380-25c6-11eb-9b1c-f045d70ac476.png)
![Screenshot from 2020-11-13 15-38-54](https://user-images.githubusercontent.com/42797233/99041923-c4c61400-25c6-11eb-9b6b-fb050e8a0e40.png)
![Screenshot from 2020-11-13 15-42-05](https://user-images.githubusercontent.com/42797233/99041950-cee81280-25c6-11eb-8750-b09ee0e060a6.png)
It seems that there are no location msg received, but the bridge looks working well.

**Comment by daohu527** [comment]
Why you use msf localization, pls check the config below 

https://github.com/ApolloAuto/apollo/blob/eac672b11ae20272f6d91f8eb119bfb942364ef5/modules/dreamview/conf/hmi_modes/mkz_lgsvl.pb.txt#L32-L37

**Comment by GabrielZZZ** [comment]
The config in my local files is the same as what you have showed:
![Screenshot from 2020-11-13 16-42-01](https://user-images.githubusercontent.com/42797233/99047517-46ba3b00-25cf-11eb-8b6c-ea5f53aa970f.png)

**Comment by daohu527** [comment]
I don’t know if you have modified the configuration, it looks like the wrong localization module was started.

To be safe, close the container and re-select the configuration and restart
```
bash docker/scripts/dev_start.sh stop
```

**Comment by GabrielZZZ** [comment]
What do you mean of "re-select the configuration"?

**Comment by daohu527** [comment]
re-select the configuration in the dreamview, drag box on the top of dreamview

**Comment by GabrielZZZ** [comment]
Sorry, I tried this step several times but the problem still exists...

**Comment by daohu527** [comment]
Based on some of the information you currently provide, I guess that the MSF localization module is activated. In fact, what you need is RTK.

And the settings in your dreamview are also RTK, so there is no clue for now, you can try to check the log or debug to see if there is progress

**Comment by GabrielZZZ** [comment]
After re-cloning the Apollo master branch, the problem was solved. Thank you @daohu527 for your help. I am closing this issue now.
