### ISSUE TITLE
(custom layers implementation) Traffic Light Detection

### ISSUE THREAD

**Issue by JerrySciangula** [ApolloAuto/apollo#12976]
Hi everyone,

I was trying to understand the neural network **_Traffic Light Detection_** in the **_Perception module_**.

Reading its [prototxt](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/camera/models/traffic_light_detection/deploy.prototxt) file, i found the custom **_RCNNProposal_** and _**DFMBPSROIAlign**_ layers.

Could someone explain me how they work or load the code that implemented them?

Thanks in advance.

**Comment by jeroldchen** [comment]
@JerrySciangula We have uploaded TensorRT implementation for custom plugins of traffic light detection in recent master code.
You can check this: https://github.com/ApolloAuto/apollo/commit/a916d039779127b2b15cb252e5fbc6e022624be2 .

**Comment by hawl666** [comment]
@jeroldchen Is it possible to use this TensorRT plugin to write python code for traffic signal detection?
