### ISSUE TITLE
Velodyne16 CNN Segmentation network input

### ISSUE THREAD

**Issue by JerrySciangula** [ApolloAuto/apollo#12975]
Hi everyone,

I was trying to understand the neural network model **_Velodyne16_** in the _**Perception module**_. [Here](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/lidar/models/cnnseg/velodyne16/deploy.prototxt) it is the deploy.prototxt description. 

This is a network that process LiDAR Velodyne16 Point Cloud Data, but reading its prototxt file, i found that the input layer has shape (N x C x H x W) = 1 x 6 x 672 x 672.

Could someone explain me what kind of input it is? 
How I can feed the network if I just have the file in .pcd format with shape _**number_of_point x 3**_?

Thanks in advance.

**Comment by jeroldchen** [comment]
@JerrySciangula Hope this document helps: [https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception.md](url) . Before sending data into CNN segmentation model, point cloud need to go through some pre-processing operations, which leads to the shape that you mentioned above. Thank you for your interest in Apollo.
