### ISSUE TITLE
How to make obstacles in Dreamview simulation environment (SimControl)?

### ISSUE THREAD

**Issue by lecoos** [ApolloAuto/apollo#12995]
Hi,

How can I add some obstacles in Dreamview simulation environment (SimControl)?

I tried to modify `modules/planning/testdata/common/sample_prediction.pd.txt` and `frame.cc`, but it seemed to have no effect.

I noticed there is a similar question (#4626), and I followed this step:
`python replay_perception.py garage_*.json`
but it reported an error:
`ModuleNotFoundError: No module named 'cyber'`.

I do not know why there is such an error because I have started Dreamview by following these steps:
`bash docker/scripts/dev_start.sh`
`bash docker/scripts/dev_into.sh`
`bash apollo.sh`
`bash scripts/bootstrap.sh`

So I want to know if I made a mistake in above operations, or there are other ways to make obstacles in SimControl.

THANKS!

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

**Comment by daohu527** [comment]
## step
You follow below step:
1. build python bin
```
bazel build modules/tools/perception:replay_perception
```
2. run bash to play
```
bash modules/tools/perception/garage_perception.bash
```

## python
Running the program with python will cause some dependency problems. I am still thinking about how to solve it.

**Comment by lecoos** [comment]
> ## step
> You follow below step:
> 
> 1. build python bin
> 
> ```
> bazel build modules/tools/perception:replay_perception
> ```
> 
> 1. run bash to play
> 
> ```
> bash modules/tools/perception/garage_perception.bash
> ```
> 
> ## python
> Running the program with python will cause some dependency problems. I am still thinking about how to solve it.

I followed these steps, and it works well. Thanks ;-)

**Comment by shusukui** [comment]
How to display the added obstacles in the Dreamview? I can only use cyber_record play record file.

**Comment by glebkiselev** [comment]
@lecoos I reworked the basic .py module and my obstacles begin to move. The main Idea of any  situation:
'''
    car_distance = 30  # required distance between cars
    num_of_obstacles = 3 # amount of obstacles from each side
    cyber.init()
    node = cyber.Node("perception")
    writer = node.create_writer('/apollo/perception/obstacles', PerceptionObstacles)
    perception_description = obstacle_crossroad_gen(start_points, num_of_obstacles, car_distance,
                                                   speed=3) # here you might create a list of dictionaries with each obstacle description. 
    perception = None
    while not cyber.is_shutdown():
        perception = generate_perception(perception_description, perception)
        # print(str(perception))
        writer.write(perception)
        time.sleep(T)
'''
generate_perception(perception_description, perception) and other basic functions you can find in replay_perception.py

**Comment by lecoos** [comment]
@shusukui Hi，
You can start _SimControl_ mode after entering _Dreamview_ page, then select _Route Editing_ on the left side of the page. Setting the route you want on the map and click _send routing request_, so that you can do your simulation.

**Comment by lecoos** [comment]
@glebkiselev 
Wow, it is very helpful for my current work, thanks a lot!

**Comment by opus23** [comment]
@lecoos  Hi,
Thanks to your advice, I can do my own dreamview simulation. But still I can't see obstacles eventhough I followed your advice. My steps are here.

- bazel build modules/tools/perception:replay_perception
- bootstrap.sh start
- bash modules/tools/perception/garage_perception.bash
- entering Dreamview page and select Route Editing

I want to see Perception obstacle module delay, but I can see all module delays except perception in Dreamview. Thanks to your help!

**Comment by lecoos** [comment]
@opus23 Hi,
Maybe your command order is wrong. I followed the below steps and can see obstacles.
- apollo.sh start
- bootstrap.sh start
- bazel build modules/tools/perception:replay_perception
- bash modules/tools/perception/garage_perception.bash
- entering Dreamview page and select Route Editing
These obstacles have fixed coordinates, so you may need to work hard to find them. You can also modify the corresponding files according to your needs.
Good luck.

**Comment by opus23** [comment]
@lecoos Thanks I found it! :)

**Comment by marcusvinicius178** [comment]
hI @opus23 , @lecoos , @daohu527 
I followed the steps above. And they "worked". I mean I did not any ERROR output while executing the files (after build them properly as you suggested). This is an advance, once I had the same error ouput in the beggining as @lecoos had (no cyber module import).
However I could not visualize the obstacles after execute the scripts. The Module Delay (on TASKS panel) returned me a Delay on PerceptionObstacle Parameter:

![image](https://user-images.githubusercontent.com/43826438/121746645-92d54b80-cadc-11eb-8b7b-94eeb61cc80a.png)

https://youtu.be/UmmTbNZg884

As consequence I was not able to switch on the Routing,Planning and Perception Tabs on Module Controller panel. They were automatically disabled, as you can check in video below:

I used the most simple scenario (SingleLaneRoad) to save computer resources...
My machine is P6000x2 (rent machine with powerful GPU). Before running these scripts to add obstacle the machine was able to execute the Routing, Planning modules (Also was able to run the Perception Module even with SVL simulator!!!). Therefore I do not understand why it was not able to run a simple addition of virtual obstacles?
Is related to some machine resource (clock frequency speed?)

Have I done something wrong? Could you please provide me a video of how to add these obstacles and visualize them? I would like to check what step is wrong or if my machine is not good enough..
Thanks in advance!

**Comment by wijdim** [comment]
@marcusvinicius178 I m having the same issue, did you success in resolving obstacle problem?
