### ISSUE TITLE
Cannot build rosbag_to_record in Apollo 6.0

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#12996]
Hi, I want to use `rosbag_to_record` to transform a old bag data into record form (`demo-sensor-demo-apollo-1.5.bag`) because I want to replicate an existing research, but when I followed the step here [Launch rosbag_to_record:](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md#install-and-run-3), the terminal showed `bash: rosbag_to_record: command not found`; I also found several issues before but the solutions included did not work...
![Screenshot from 2020-11-14 21-40-05](https://user-images.githubusercontent.com/42797233/99148314-fd96e380-26c1-11eb-8907-afa6da7345ae.png)

The Apollo version is 6.0. Can you show me the correct way to install this tool? Or can you help transform this file for me if possible and send the `.record` file here?

**Comment by GabrielZZZ** [comment]
I have used Apollo 5.0 which includes this tool to transform the bag file into record and then put the record for Apollo 6.0 to use. Closing this issue now.

**Comment by nightfuryyy** [comment]
> I have used Apollo 5.0 which includes this tool to transform the bag file into record and then put the record for Apollo 6.0 to use. Closing this issue now.

I have a problem with convert kitti dataset to rosbag. Could you please give me the rosbag file ? Thank you so much.
