### ISSUE TITLE
Object detection  and tracking not working in Apollo 6.0

### ISSUE THREAD

**Issue by Manoj-EK** [ApolloAuto/apollo#12998]
### System information

- **OS Platform and Distribution (Linux Ubuntu 20.04)**
- **Apollo version (6.0)**
- **Graphics card: TU104BM [GeForce RTX 2080 Mobile]**
- **nvidia version : 455.38**
- **CUDA version:11.1**
- **RAM: 32 GB**

Hi, 

I have cloned latest Apollo 6.0 from github as mentioned in lgsvl installation document (https://www.lgsvlsimulator.com/docs/apollo-master-instructions/) and further followed all steps like installing nvidia drivers and dockers...Everything works fine but i have problem with object detection and tracking . Perception module doesn't work..so i switched to third-party perception module and it is shown in video attached to issue. Please help me in this regard

### Steps to reproduce the issue:

-STEP 1: To launch the container navigate to the apollo directory 
                and type:     ./docker/scripts/dev_start.sh

-STEP 2: To get into the container.... type in terminal  -  ./docker/scripts/dev_into.sh

-STEP 3: Build Apollo (optimized, not debug, with GPU support)....
                type in terminal -  ./apollo.sh build_opt_gpu

-STEP 4: Launch bridge (inside docker container):
                type in terminal - ./scripts/bridge.sh

-STEP 5: Launch lgsvl simulator with appropriate apollo settings mentioned in lgsvl instruction guide and                 
                check whether bridge is connected

-STEP 6: open separate terminal. Navigate to the apollo directory 
               and type  again (to go into container) : ./docker/scripts/dev_into.sh

-STEP 7: To start Apollo, run the command : ./scripts/bootstrap_lgsvl.sh

-STEP 8: Then with local host:8888 link open dreamviewer and and select appropriate seetings....
              I chose   : setup mode -  Mkz Lgsvl
                               vehicle - Lincoln2017MKZ LGSVL
                               map (downloaded manually from github) - CUBE TOWN

 

   

### Supporting materials (screenshots, command lines, code/script snippets):

![object detection and tracking](https://user-images.githubusercontent.com/65737691/99181751-d75c5c80-2730-11eb-9a2c-fc5fd88fab9d.gif)

**Comment by daohu527** [comment]
1. I suggest you use lidar perception. Camera may have some issue in apollo 6.0? Because there are other issues mentioning this.  
2. Then check the topic if there are alright. 
3. If there are input topics but not output, check the log to see if there are error messages.

**Comment by ntutangyun** [comment]
You might also wanna run the perception manually in a terminal and take a look at its runtime print.

**Comment by Manoj-EK** [comment]
@daohu527  could you please suggest how to use lidar perception

**Comment by Manoj-EK** [comment]
@ntutangyun 

I went through the process is said and tried to run it manually after seeing steps from perception readme file ( Ref: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)

I was able to open dream view and when i went into container and run the command : **cyber_launch start /apollo/modules/transform/launch/static_transform.launch**

it shows following error:


manoj@manoj-OMEN-by-HP-Laptop-15-dh0xxx:~/apollo$ ./docker/scripts/dev_into.sh
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

[manoj@in-dev-docker:/apollo]$ cyber_launch start /apollo/modules/transform/launch/static_transform.launch
[cyber_launch_27178] INFO Launch file [/apollo/modules/transform/launch/static_transform.launch]
[cyber_launch_27178] INFO ========================================================================================================================
[cyber_launch_27178] INFO Load module [static_transform] library: [mainboard_default_27178] [CYBER_DEFAULT] conf: [/apollo/modules/transform/dag/static_transform.dag] exception_handler: []
[cyber_launch_27178] INFO Start process [mainboard_default_27178] successfully. pid: 27185
[cyber_launch_27178] INFO ------------------------------------------------------------------------------------------------------------------------
[mainboard_default_27178]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_27178]  I1116 11:07:06.829344 27185 module_argument.cc:81] []command: mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_27178 -s CYBER_DEFAULT 
[mainboard_default_27178]  I1116 11:07:06.830072 27185 global_data.cc:153] []host ip: 192.168.0.103
[mainboard_default_27178]  I1116 11:07:06.830343 27185 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default_27178, has 1 dag conf
[mainboard_default_27178]  I1116 11:07:06.830353 27185 module_argument.cc:60] []dag_conf: /apollo/modules/transform/dag/static_transform.dag
[mainboard_default_27178]  E1116 11:07:06.887687 27185 static_transform_component.cc:60] [static_transform]Extrinsic yaml file does not exist: /apollo/modules/drivers/velodyne/params/lidar16_front_up_novatel_extrinsics.yaml
[mainboard_default_27178]  E1116 11:07:06.887732 27185 static_transform_component.cc:60] [static_transform]Extrinsic yaml file does not exist: /apollo/modules/drivers/velodyne/params/lidar16_front_novatel_extrinsics.yaml
[mainboard_default_27178]  E1116 11:07:06.887742 27185 static_transform_component.cc:60] [static_transform]Extrinsic yaml file does not exist: /apollo/modules/drivers/velodyne/params/lidar16_rear_left_novatel_extrinsics.yaml
[mainboard_default_27178]  E1116 11:07:06.887749 27185 static_transform_component.cc:60] [static_transform]Extrinsic yaml file does not exist: /apollo/modules/drivers/velodyne/params/lidar16_rear_right_novatel_extrinsics.yaml
[mainboard_default_27178]  E1116 11:07:06.887993 27185 static_transform_component.cc:60] [static_transform]Extrinsic yaml file does not exist: /apollo/modules/perception/data/params/radar_rear_extrinsics.yaml
[mainboard_default_27178]  E1116 11:07:07.096344 27208 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[static_transform], please ensure that each node has a unique name.
[mainboard_default_27178]  
[cyber_launch_27178] ERROR Process [mainboard_default_27178] has finished. [pid 27185, cmd mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_27178 -s CYBER_DEFAULT].
[cyber_launch_27178] INFO All processes has died.
[cyber_launch_27178] INFO Cyber exit.
[cyber_launch_27178] INFO All processes have been stopped.
[manoj@in-dev-docker:/apollo]$ 


**Could you please suggest what might have went wrong**

**Comment by daohu527** [comment]
I check the perception file "modules/perception/production/dag/dag_streaming_perception_lgsvl.dag". It is already used Lidar, could you show the output of cyber_monitor? 

It is best to also check the log of perception.INFO under data/log too.

**Comment by Manoj-EK** [comment]
@daohu527  Here is the output of **cyber_monitor** output

![cyber_monitor](https://user-images.githubusercontent.com/65737691/99244459-69806580-2802-11eb-8659-bf4d3086b811.png)

Here is the log of **perception module:**

[perception.log.INFO.20201116-114908.txt](https://github.com/ApolloAuto/apollo/files/5545851/perception.log.INFO.20201116-114908.txt)

**Comment by daohu527** [comment]
pls check the topic is publish "/apollo/sensor/lidar128/compensator/PointCloud2" in lgsvl, there is a sample config [here](https://www.lgsvlsimulator.com/docs/apollo5-0-json-example/)

I didn’t find this topic from the cyber monitor you pasted. Have you tried to turn the page?

**Comment by Manoj-EK** [comment]
@daohu527  I checked whether the topic is published in lgsvl as advised and it's published...

![topic_publish](https://user-images.githubusercontent.com/65737691/99252306-0c3ee100-280f-11eb-9270-2225e56e8b98.png)

when i checked about the published **channelNames** using **cyber_visualizer**...it's showed the image below with information of all relevant topics published.....You can also observe detection of objects through **visualizer**

![cyber_visualizer](https://user-images.githubusercontent.com/65737691/99256963-83c43e80-2816-11eb-915a-16ad72b953ee.png)

when i checked the same in **cyber_monitor** this was the result

![cyber_monitor](https://user-images.githubusercontent.com/65737691/99257083-b79f6400-2816-11eb-9aa6-b5f847c6c292.png)

**Is there explanation possible for these outputs**

**Comment by daohu527** [comment]
Your last picture seems to be working, but the picture you posted earlier is not work, you can found the "apollo/prediction" and "apollo/perception/obstacles" then the perception and prediction module is work. 

## Next step
1. I didn't find the lidar topic published, could you pls use "→
" or "←" to see if there are "/apollo/sensor/lidar128/compensator/PointCloud2", if not try to find what's wrong. 
2. use "enter" on the topic "apollo/prediction" and "apollo/perception/obstacles" to see if there're any obstacles.

**Comment by Manoj-EK** [comment]
@daohu527 
1. I used arrows "->" and "<-"  as you advised but **cyber_monitor** shows sometimes  "/apollo/sensor/lidar128/compensator/PointCloud2"...when i restart dreamview to repeat the process it doesn't show up...Is it unstable?....Do you think is it something with respect to nvidia driver....i am presently using the one shown below which is open source:

![nvidia driver](https://user-images.githubusercontent.com/65737691/99366036-5b8d1c00-28b8-11eb-807a-2ed9cf50fb14.png)

 The linux  version i am using is 20.04...can i downgrade my version to 18.04 to have stable system response

2. i went into /apollo/prediction/perception_obstacles which was non-responsive...i got the following message:

![prediction](https://user-images.githubusercontent.com/65737691/99366475-f71e8c80-28b8-11eb-9679-7d611c9de3b8.png)

I appreciate your quick response and thank you for the advise

**Comment by daohu527** [comment]
I suggest you turn off the output of the camera and only send lidar in LGSVL. I think your focus is on the output of lidar.

Lidar does not need any processing, as long as the LGSVL simulator and Apollo are connected, I think you can try to debug, reinstalling the system may not make a big improvement.

**Comment by Manoj-EK** [comment]
@daohu527  I found out alternate way to avoid lidar,camera and use 3D truth table and signal sensor from lgsvl....
I am providing the link below so that others with the similar issue in future can look into it:

https://youtu.be/781zkzN2xMg

Thank you very much for your support...
