### ISSUE TITLE
Please help: `./cyber_record_parser.cc` not work

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#12999]
Hello. I want to extract pcd file from a record, but I cannot run the command `./cyber_record_parser.cc` correctly. Can you help me?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- After entering docker, went to `/apollo/modules/localization/msf/local_tool/data_extraction`
- Run `./cyber_record_parser.cc --help`, here is the output:
![Screenshot from 2020-11-15 21-07-59](https://user-images.githubusercontent.com/42797233/99185728-b161a700-2786-11eb-9dbf-6b37842762b8.png)

**Comment by daohu527** [comment]
Before using Apollo, **you must at least understand the difference between executable files and .cc files**

There is a doc about parsing record files into lidar, camera and radar. [link](https://github.com/ApolloAuto/apollo/tree/3711be4317b62fffa548f91cb383269d4cc25987/modules/tools/record_parse_save) , the lidar is save as a txt file, you can try to modify the suffix.
