### ISSUE TITLE
Time Synchronization between Logged data and Perception output

### ISSUE THREAD

**Issue by romanodanilo** [ApolloAuto/apollo#13009]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  5.5+

Hi all,
We are working with Apollo 5.5 and we would like to ask support for a problem we are facing.
We have recorded data using some sensors and we would like to run the Apollo perception stack on them.
The perception is working properly but we have a time synchronization problem.
The `header.timestamp_sec` field of the recorded data is relative to the moment in which the data has been collected while the `timestamp_sec` value for the perception output is relative to the moment in which the perception is ran on the logged data.
Do you know how to overcome this issue?
We saw that there should be a `use_sim_time` feature but even enabling it it seems to have no effect on the timestamp values.
Do you have any info to have the perception output to have the same timestamp axis of the recorded data?
Thanks a lot

**Comment by daohu527** [comment]
I provide a way to mock the time. It can achieve a single frame function similar to a game engine, and then next frame.
1. set the clock mode MODE_MOCK
```
    Clock::SetMode(ClockMode::MODE_MOCK);
    Clock::SetNowInSeconds(100.01);
```
2. publish the real time in topic "/clock". When the reader receives the message, the time will be set.
https://github.com/ApolloAuto/apollo/blob/0e995ae808315742db3b581fca723b4817048f7f/cyber/init.cc#L122-L128

**Comment by romanodanilo** [comment]
Thanks, the ClockMode::MODE_MOCK is the best way to tackle this problem.
