### ISSUE TITLE
What is the role od guardian module?

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#13010]
Hi,
Trying to understand the code, I want to know what the role of the guardian module is. What does it specifically do?

**Comment by daohu527** [comment]
Guardian - A new safety module that performs the function of an Action Center and intervenes should Monitor detect a failure.

[link](https://github.com/ApolloAuto/apollo/blob/f7d1f94f5342737f33b52132bbd5a98243fd820b/docs/specs/Apollo_5.5_Software_Architecture.md#guardian)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
