### ISSUE TITLE
Other high precision map download methods

### ISSUE THREAD

**Issue by shusukui** [ApolloAuto/apollo#13028]
Dreamview provides a default high-precision map. I want to know how to get other high-precision maps. Does Baidu provide this service.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  5.5
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
There are also other maps in "modules/map/data", there is also a service in [cloud](http://data.apollo.auto/hd_map_intro?locale=en-us&lang=en)

**Comment by shusukui** [comment]
thank you 👍

**Comment by diegohu** [comment]
@shusukui hope the answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
