### ISSUE TITLE
Modules and Nodes in Cyber

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13034]
### System information

- **OS Platform and Distribution - Linux Ubuntu 16.04)**:
- **Apollo installed from (source or binary)**: Source
- **Apollo version 3.5

Hi, 
I am trying to understand the architecture of cyber and have following questions
1. I understand about nodes, reader, writer, sub and pub, Module ( inherited from Component etc.,), but I am not able to tie nodes and  modules. How are the two connected? For ex : if control module has set of nodes, how does the implementation takes care of this requirement?
2. I am developing a module to plug into Apollo framework. How are the modules defined?  Can you please point me to detailed instruction on how to implement a module from scratch?
3. Equivalent to ROS2 implementation of main function and spin, how does cyber framework implement it? 

I know these are broad questions, but any input is really helpful for me

thank you

**Comment by changsh726** [comment]
1. Every module contains and communicates through the node. A module can have different types of communication by defining read/write and/or service/client in a node. If your module inherits from `Component` or `TimerComponent`, there will be a `node_` class member which you can use to create writers ,readers, etc.
2. There are some examples in [cyber examples](https://github.com/ApolloAuto/apollo/tree/master/cyber/examples) and [Cyber RT Quick Start](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Quick_Start.md).
3. The entry point of Cyber is in [mainboard.cc](https://github.com/ApolloAuto/apollo/blob/master/cyber/mainboard/mainboard.cc). A `Component` can be launched by `mainboard` of `cyber_launch` as described in [Cyber RT Quick Start](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Quick_Start.md).

Hope these notes have helped.

**Comment by jpcloud1577** [comment]
Thank you so much for your response. This is really helpful for me
Just one more follow up question : 
I would like to create a module of my own (similar to planning, perception etc.,). Besides components and associated nodes, what are other steps I should take (if at all) ? Please point me any instructions.

**Comment by changsh726** [comment]
Everything you need to do is in [Cyber RT Quick Start](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Quick_Start.md).

**Comment by jpcloud1577** [comment]
Thank you so much for your help
