### ISSUE TITLE
Dreamview 能否像 Dreamland一样，离线状态下做仿真练习。

### ISSUE THREAD

**Issue by shusukui** [ApolloAuto/apollo#13036]
我目前了解应用Dreamview的功能，只能播放rosbag 数据 ，除播放数据外Dreamview能否像Dreamland一样编辑场景，做仿真练习，请问如何实现。
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by ntutangyun** [comment]
可以试一下 LGSVL simulator

**Comment by shusukui** [comment]
好的，谢谢。
