### ISSUE TITLE
What happens if I create a Reader before to create the relative Writer?

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#13032]

**Comment by changsh726** [comment]
The order in which a Reader and a Writer are created does not matter. But a reader will not receive anything until the related Writer is created and sends the message.

**Comment by changsh726** [comment]
Hope the information answered your question. If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open a new issue if you have any more questions. 

Thank you for supporting Apollo!
