### ISSUE TITLE
rosbag_to_record

### ISSUE THREAD

**Issue by whuzs** [ApolloAuto/apollo#13035]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu18.04
- **Apollo installed from (source or binary)**: 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

why is the rosbag_to_record tools removed after 5.0? In version 5.5 and 6.0, could not find rosbag_to_record

**Comment by huahang** [comment]
同问，请问这个工具跑哪里去了？
