### ISSUE TITLE
I want to know how to creat a map and load it into Dreamview.

### ISSUE THREAD

**Issue by Gump0116** [ApolloAuto/apollo#13033]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ntutangyun** [comment]
You could check out how Apollo's HD map are formated [here](https://github.com/ApolloAuto/apollo/tree/master/modules/map/data)

They are essentially Protobuf binary files of different content for different purposes.

Once you created those files, you could place them in a folder under `/apollo/modules/map/data/`

and it will be automatically recognized by Dreamview.

**Comment by Gump0116** [comment]
> You could check out how Apollo's HD map are formated [here](https://github.com/ApolloAuto/apollo/tree/master/modules/map/data)
> 
> They are essentially Protobuf binary files of different content for different purposes.
> 
> Once you created those files, you could place them in a folder under `/apollo/modules/map/data/`
> 
> and it will be automatically recognized by Dreamview.

Thank you for answering my question!
You offered me a solution.

**Comment by daohu527** [comment]
seems sloved!
