### ISSUE TITLE
Apollo仿真开放平台的场景管理无法显示地图背景/ scenario editor of the Dreamland cannot show the background of a map

### ISSUE THREAD

**Issue by 0502tonylin** [ApolloAuto/apollo#13031]
在[Apollo仿真平台](http://bce.apollo.auto/)上，无论是在场景列表的仿真还是在场景编辑界面中，都无法显示地图的背景（也就是马路和线条），只能看到车和各种交通信号、红绿灯等。如下图所示：
In Apollo Dreamland, both sample scenarios and scenario editor cannot show the background of map, only cars, traffic signs and lights appear. As figures shown below
![image](https://user-images.githubusercontent.com/43193208/99511274-07229300-29c3-11eb-80a7-375baf255ef2.png)
![image](https://user-images.githubusercontent.com/43193208/99511317-1275be80-29c3-11eb-879a-f3fa098807e3.png)

实在找不到该去哪里反馈这个问题，只能在这边询问了。
不是我webgl的问题，我已经打开了webgl，并且在其他电脑也试过了，就是无法显示地图背景。
I really can't find where to feedback this question, so I can only ask here.
It's not my WebGL problem. I've enabled WebGL and tried it on other computers, but it cannot show the background either.

**Comment by bjackmanwit** [comment]
I have the same issue! It was working last week and then stopped working.  I reckon it's a server issue.
Hopefully they'll fix it soon as Dreamland can't be used without maps!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
