### ISSUE TITLE
Unable to launch Fusion Obstacle Visualization Tool

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#13049]
Hi team,

I want to use the Fusion Obstacle Visualization Tool described here (https://github.com/ApolloAuto/apollo/blob/r6.0.0/docs/howto/how_to_run_offline_sequential_obstacle_perception_visualizer.md), and my Apollo version is the latest. But the building process showed that it cannot find the modules and I noticed that it seems to be excluded from the current version. So **how can I use the tool and its corresponding ones (export_sensor_data:export_sensor_data) in the current version?**

Thanks.

**Comment by GabrielZZZ** [comment]
Can anyone help me please?

**Comment by daohu527** [comment]
If so, you can try the rollback 3.0.0 version. There is a related discussion here #2527

**Comment by GabrielZZZ** [comment]
Thanks @daohu527 . I have tried but it seems to have problem related to docker image that the OpenGL went wrong:
![Screenshot from 2020-11-25 20-14-59](https://user-images.githubusercontent.com/42797233/100692575-1b549000-33c6-11eb-8192-621a4218cccf.png)

Since my computer uses Nvidia 2080 GPU, it is not possible for me to roll back the driver to previous version like 3XX mentioned in other issues. Is it possible that this function will be added into the current master branch since my computer does not have such problems (OpenGL) with the latest Apollo system?
