### ISSUE TITLE
No map in scenario editor

### ISSUE THREAD

**Issue by liversonp** [ApolloAuto/apollo#13048]
**Describe the bug**
In dreamland, when I try to see a map in scenario editor, it doesn't show anything

**To Reproduce**
1. Go to Dreamland
2. Click on scenario Management -> Scenario Editor
3. Create a map
4. Nothing will be there

**Expected behavior**
It's expected to have a map in the editor.

**Screenshots**
![Captura de tela de 2020-11-22 21-59-34](https://user-images.githubusercontent.com/45077010/99922205-07e25e80-2d0e-11eb-8b45-a8808f85ffe1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox, Google Chrome

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
