### ISSUE TITLE
请问如何生成 record 文件，有没有相关的工具

### ISSUE THREAD

**Issue by shusukui** [ApolloAuto/apollo#13051]
现在通过 回放 record文件，Dreamview可以实现车辆的运行，请问这个record文件可以自己生成吗 ?  需要用到什么工具。

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by ntutangyun** [comment]
你可以用 `cyber_recorder record` 工具来录制

**Comment by shusukui** [comment]
我现在没有实车，在Dreamview里有办法录制吗？

**Comment by ntutangyun** [comment]
可以试试LGSVL simulator. 录制一般是在terminal 里面 用`cyber_recorder` 工具

**Comment by apollodevcommunity** [comment]
record 文件是记录您之前运行过的内容，然后回访时，可以将数据重现。cyber_record指令就可以记录相关channel数据，或者使用python API调用也可以。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=70
