### ISSUE TITLE
apollo使用的fastrtps版本问题，是否做了本地修改？

### ISSUE THREAD

**Issue by luy-foxit** [ApolloAuto/apollo#13052]
### System information

- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):  Linux Ubuntu 16.04
- Apollo installed from (source or binary): source
- Apollo version (3.5, 5.0, 5.5, 6.0): 6.0
- Output of `apollo.sh config` if on `master` branch: master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
尝试在本地ubuntu16搭建一套运行环境，自己编译第三方库。根据docker中fastrtps库的的名称，推测fastrtps使用的版本是v1.5.0, fastcdr使用的版本是v1.0.7。但是docker中fastrtps和fastcdr的头文件和github中fastrtps源码有差异。 请问是否对第三方库源码做了本地修改？ 如果有修改那么修改了哪些地方？

**Comment by storypku** [comment]
You can take a look at https://github.com/ApolloAuto/apollo/blob/r5.5.0/docker/build/installers/install_fast-rtps.sh .
It works well also on Apollo 6.0 and master.

**Comment by freekevinCode** [comment]
https://github.com/ApolloAuto/apollo/blob/r5.5.0/docker/build/installers/FastRTPS_1.5.0.patch
这个fastrtps的补丁（应该是百度自己的修改）
