### ISSUE TITLE
prediction问题

### ISSUE THREAD

**Issue by longjianquan** [ApolloAuto/apollo#13050]
- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version ( 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
在预测模块里面，apollo/modules/prediction/evaluator/pedestrian/pedestrian_interaction_evaluator.h行人人预测这个模块，除了测试模块，其他都没有调用它？
代码哪里体现了人交互的地方。
谢谢！

**Comment by daohu527** [comment]
`pedestrian_interaction_evaluator` is not called indeed！

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
