### ISSUE TITLE
cyber frame SwapContext crash on Xavier

### ISSUE THREAD

**Issue by buaaliyuan** [ApolloAuto/apollo#13053]
**Describe the bug**
listener crash when receive message from talker.
I am porting cyber frame to Xavier, not runing in docker. When I use listener and talker test cyber frame, I found something wrong with swap_aarch64.S.
I debug use cout, found when call CRoutine::Yield() in file routine_factory.h, It should switch to Resume() in croutine.h, but crashes(Bus error)
I compile the same code on X86_64 Ubuntu18.04, talker and listener are running ok. So is swap_aarch64.S suitable for xavier aarch64?

**Screenshots**
(gdb) bt
#0  0x0000000000000041 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

(gdb) info f
Stack level 0, frame at 0x7fbdd1b820:
 pc = 0x41; saved pc = <not saved>
 Outermost frame: previous frame identical to this frame (corrupt stack?)
 Arglist at 0x334e3daf, args:
 Locals at 0x334e3daf, Previous frame's sp is 0x7fbdd1b820

**Version**
 - OS: Xavier ubuntu18.04
 - GCC: 7.5
 - Cyber: 5.5

**Comment by storypku** [comment]
Can you please describe how to reproduce this bug?

**Comment by buaaliyuan** [comment]
@storypku  I add -fPIC to CMAKE_CXX_FLAGS and CMAKE_C_FLAGS solve this problem when I compile cyber framework. Talker and Listener run ok. Thank you!

**Comment by daohu527** [comment]
If you compile a dynamic library, you always need the `-fPIC` option, which means "Position Independent Code".
[Ref](https://stackoverflow.com/questions/966960/what-does-fpic-mean-when-building-a-shared-library)

**Comment by buaaliyuan** [comment]
> If you compile a dynamic library, you always need the `-fPIC` option, which means "Position Independent Code".
> [Ref](https://stackoverflow.com/questions/966960/what-does-fpic-mean-when-building-a-shared-library)

thank you! I later found  `--copt=-fpic` in bazel BUILD file.
