### ISSUE TITLE
Can the destination be set using python script?

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#13067]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue: 
- : Hello team, I am working on Apollo recently, I want to set the destination by using python script instead of click  on the map， after the destination is set by python script, then the vehicle will autopilot to the destination. Can we do like this?

**Comment by ntutangyun** [comment]
the way dreamview sends the destination is that it packs the routing request to the backend through a websocket connection.

You could do the same using Python.

**Comment by daohu527** [comment]
There is already a tool in apollo [mock_routing_request.py](https://github.com/ApolloAuto/apollo/blob/3711be4317b62fffa548f91cb383269d4cc25987/modules/tools/mock_routing/mock_routing_request.py)

## steps
1. You can first use dreamview to generate the routing request, and use `cyber_monitor` to view the points. For now you get two points "start point" and "end point".
2. Then substitute the two points in `mock_routing_request.py` and run it.
3. Last, use cyber_monitor to check if the routing request is published by `mock_routing_request.py`

**Comment by diegohu** [comment]
@ForresterLu  hope the answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
