### ISSUE TITLE
About the usages of other docker images than apollo:dev-x86_64-18.04, pulled by dev_start.sh script.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#13075]
I noticed that the dev_start.sh script will pull several other docker images in addition to apollo itself as shown below:

```
$ docker images | grep apollo
apolloauto/apollo        map_volume-sunnyvale_big_loop-latest                             e7b1a71d5b9d        10 days ago         440MB
apolloauto/apollo        dev-x86_64-18.04-20201110_0617                                   062e9ad3e680        2 weeks ago         10.1GB
apolloauto/apollo        yolov4_volume-emergency_detection_model-x86_64-latest            e3e249ea7a8a        2 months ago        264MB
apolloauto/apollo        faster_rcnn_volume-traffic_light_detection_model-x86_64-latest   58537bb25841        2 months ago        170MB
apolloauto/apollo        data_volume-audio_model-x86_64-latest                            17cb2a72a392        2 months ago        194MB
apolloauto/apollo        map_volume-sunnyvale_with_two_offices-latest                     93a347cea6a0        8 months ago        509MB
apolloauto/apollo        map_volume-san_mateo-latest                                      48cd73de58ba        13 months ago       202MB
apolloauto/apollo        local_third_party_volume-x86_64-latest                           5df2bf3cc4b9        18 months ago       156MB
apolloauto/apollo        map_volume-sunnyvale_loop-latest                                 36dc0d1c2551        2 years ago         906MB
```
I know that the dreamview works directly based on apollo:dev-x86_64-18.04 image. As for other images, I still not so clear on their usages/invoking methods. Could you please give me some more hints?

Regards,
HY

**Comment by daohu527** [comment]
In general, mainly save the map and model files. I am not very sure about `local_third_party_volume-x86_64-latest`, others can help!

## map
```
map_volume-sunnyvale_big_loop-latest
map_volume-sunnyvale_with_two_offices-latest
map_volume-san_mateo-latest
map_volume-sunnyvale_loop-latest
```

## YOLOV4
```
yolov4_volume-emergency_detection_model-x86_64-latest
```

## AUDIO
```
data_volume-audio_model-x86_64-latest
```

## FASTER_RCNN
```
faster_rcnn_volume-traffic_light_detection_model-x86_64-latest
```

##  third party
```
local_third_party_volume-x86_64-latest
```

**Comment by storypku** [comment]
> In general, mainly save the map and model files. I am not very sure about `local_third_party_volume-x86_64-latest`, others can help!
> 
> ## map
> ```
> map_volume-sunnyvale_big_loop-latest
> map_volume-sunnyvale_with_two_offices-latest
> map_volume-san_mateo-latest
> map_volume-sunnyvale_loop-latest
> ```
> 
> ## YOLOV4
> ```
> yolov4_volume-emergency_detection_model-x86_64-latest
> ```
> 
> ## AUDIO
> ```
> data_volume-audio_model-x86_64-latest
> ```
> 
> ## FASTER_RCNN
> ```
> faster_rcnn_volume-traffic_light_detection_model-x86_64-latest
> ```
> 
> ## third party
> ```
> local_third_party_volume-x86_64-latest
> ```

Thanks @daohu527 for clarifying. As for the  local_third_party volume, it was mounted at /usr/local/apollo/local_third_party, and currently contains the mklml and mkldnn libraries which may be deprecated in the future as currently no modules depends on them.

**Comment by daohu527** [comment]
> Intel MKL-DNN is an open source, performance-enhancing library for accelerating deep learning frameworks on IA(Intel® architecture). 

[link](https://software.intel.com/content/www/us/en/develop/articles/intel-mkl-dnn-part-1-library-overview-and-installation.html)

Self-driving cars running on GPU do not need much of this library.
