### ISSUE TITLE
Some questions about running Apollo with LGSVL simulator 

### ISSUE THREAD

**Issue by qiongwu1003** [ApolloAuto/apollo#13072]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**:source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.0
- **Output of `apollo.sh config` if on `master` branch**:yes

### Steps to reproduce the issue:

I understand the auto drive flow as below, am I right?

- LGSVL simulator side : vehicle(add GPS, camera, radar, lidar etc sensors) -> send the sensors data to Apollo
- Apollo side : receive the sensors data-> process the data in "perception" module -> modules like "control" "palnning" will use the processed data to drive the car -> send back to LGSVL simulator vehicle speed, position etc info

And have we used some data in Apollo when realize the auto drive, or all the data from LGSVL simulator?

Also I want to know the functions of the "Camera" "Radar" "GPS" ”Velodye“ modules in Apollo.
When and how I can use those modules.  Or is there some documentation about the Apollo modules?

**Comment by daohu527** [comment]
> And have we used some data in Apollo when realize the auto drive, or all the data from LGSVL simulator?
1. sensor data (GPS, lidar, radar, camera) -> apollo
2. control cmd <- apollo

> Also I want to know the functions of the "Camera" "Radar" "GPS" ”Velodye“ modules in Apollo.
When and how I can use those modules. Or is there some documentation about the Apollo modules?

There is already a readme in each file, you can find in [docs](https://github.com/ApolloAuto/apollo/tree/master/docs)

**Comment by qiongwu1003** [comment]
@daohu527 
Thanks for your reply.
I will check the docs.
