### ISSUE TITLE
When I turn on Apollo5.0 and LGSVL on my computer, the computer freezes！

### ISSUE THREAD

**Issue by Gump0116** [ApolloAuto/apollo#13070]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Ubuntu16.04
- **Apollo installed from (source or binary)**:lgsvl-apollo-5.0
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
 My CPU usage seems high！
By the way My CPU is 12 Intel(R) Core(TM)  i7-8700K CPU @3.70GHz

### Supporting materials (screenshots, command lines, code/script snippets):
![2020-11-27 13-58-23屏幕截图](https://user-images.githubusercontent.com/53608571/100420370-4aff5180-30c1-11eb-82d0-e78f6fc4c211.png)

**Comment by ntutangyun** [comment]
Could you try out the Apollo master branch instead, since the LGSVL forked Apollo 5.0 is no longer maintained.

**Comment by Gump0116** [comment]
> Could you try out the Apollo master branch instead, since the LGSVL forked Apollo 5.0 is no longer maintained.

Is it because of the version?
LGSVL and DreamView all Worked well,But the computer will freeze。

**Comment by ntutangyun** [comment]
Not sure if it's about the version. it's just that in the future if you encounter any other issues, 
it'd not likely to be answered promptly as the version is no longer maintained.

**Comment by Gump0116** [comment]
> Not sure if it's about the version. it's just that in the future if you encounter any other issues,
> it'd not likely to be answered promptly as the version is no longer maintained

THX！

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
