### ISSUE TITLE
'cyber_monitor' is not working after I build script 'mock_routing_request.py'

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#13090]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

### Steps to reproduce the issue:

1. Hello team, I have built Apollo 6.0 and it run with LGSVL sucessfully, after that I want to run script [mock_routing_request.py](https://github.com/ApolloAuto/apollo/blob/3711be4317b62fffa548f91cb383269d4cc25987/modules/tools/mock_routing/mock_routing_request.py) to send destination by python code, then I did the following steps:
- use cyber_monitor to obtain the current poisition of the vehicle, generate a desination point by dreamviewer, then I will get "start point" and "end point"
- substitute the two point in `mock_routing_request.py`.
- Then I run `bazel build //modules/tools/mock_routing:mock_routing_request` to build it
- After build sucessfully, I run `./bazel-bin/modules/tools/mock_routing/mock_routing_request` to run the script
- The output is as following:
![Kazam_screenshot_00002](https://user-images.githubusercontent.com/26716009/100712959-903bc000-33ee-11eb-91d6-6415f66e8033.png)

2. However, after I run `mock_routing_request.py`, the `cyber_mointor` command is no longer vaild, the hint says:
![Kazam_screenshot_00005](https://user-images.githubusercontent.com/26716009/100713271-00e2dc80-33ef-11eb-8a48-0b5a860a444a.png)

3. And when I stop the Apollo and rerun to the `bootstrap_lgsvl.sh`, it showed me that I need to rebuilt Apollo again.
![Kazam_screenshot_00009](https://user-images.githubusercontent.com/26716009/100717055-8452fc80-33f4-11eb-9a93-0ed167b2e75c.png)

4. Anyone knows what happened, it confuses me a lot.

**Comment by daohu527** [comment]
I encountered this problem when I **increase Linux swap**. I am not sure if this is the problem, do you have the same situation?

**Comment by ForresterLu** [comment]
> I encountered this problem when I **increase Linux swap**. I am not sure if this is the problem, do you have the same situation?

Do you mean increase swap space in Ubuntu system, I never met that question. My question may because of the order of compilation, when I build `mock_routing_request.py` first, then build the apollo, I can directly run the script without no longer building it. I am not sure whether this is the point of my problem.

**Comment by daohu527** [comment]
so when you first build `apollo` and then `mock_routing_request` it doesn't work?

**Comment by ForresterLu** [comment]
> so when you first build `apollo` and then `mock_routing_request` it doesn't work?

Yes, when I build apollo then build mock_routing_request, something wrong will occur.

**Comment by storypku** [comment]
Hi @ForresterLu, this was a typical scenario that you have changed bazel build options by running `bazel build //modules/tools/mock_routing:mock_routing_request` command without any additional flags.

If you build the project with `./apollo.sh build`, you can see the following messages:

```text
[story@in-dev-docker:/apollo]$ ./apollo.sh build cyber
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20201110_0617
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[ OK ] Running GPU build on x86_64 platform.
[INFO] Build Overview: 
[INFO]     USE_GPU: 1  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=gpu 
[INFO]     Build Targets: //cyber/... union //modules/tools/visualizer/...
```

Here, the equivalent bazel command to build `cyber` was `bazel build --config=gpu //cyber/... union //modules/tools/visualizer/...`.

So you should always use the same options for building: Either use `apollo.sh` for module-level build, or use `bazel build [bazel-options] //path/to:target` . 

Please note that `apollo.sh` will determine if `--config=cpu` or `--config=gpu` should be used if you didn't specify either of them.

**Comment by ForresterLu** [comment]
> Hi @ForresterLu, this was a typical scenario that you have changed bazel build options by running `bazel build //modules/tools/mock_routing:mock_routing_request` command without additional options.
> 
> If you build say, `cyber` with `./apollo.sh build`, you can see the following messages got printed:
> 
> ```
> [story@in-dev-docker:/apollo]$ ./apollo.sh build cyber
> [INFO] Apollo Environment Settings:
> [INFO]     APOLLO_ROOT_DIR: /apollo
> [INFO]     APOLLO_CACHE_DIR: /apollo/.cache
> [INFO]     APOLLO_IN_DOCKER: true
> [INFO]     DOCKER_IMG: dev-x86_64-18.04-20201110_0617
> [INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
> [INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
> [ OK ] Running GPU build on x86_64 platform.
> [INFO] Build Overview: 
> [INFO]     USE_GPU: 1  [ 0 for CPU, 1 for GPU ]
> [INFO]     Bazel Options: --config=gpu 
> [INFO]     Build Targets: //cyber/... union //modules/tools/visualizer/...
> ```
> 
> Here, the equivalent Bazel command to build the `cyber` module was:
> 
> ```shell
> bazel build --config=gpu //cyber/... union //modules/tools/visualizer/...
> ```
> 
> One should always use the same options for building: Either use `apollo.sh` for module-level build, or use equivalent `bazel build [bazel-options] //path/to:target` to build single targets/modules.
> 
> Please note that `apollo.sh` will determine if `--config=cpu` or `--config=gpu` should be used if you didn't specify either of them.

Thanks for your reply @storypku , I think I need to build `mock_routing_request ` then building the Apollo project.

**Comment by storypku** [comment]
Hi @ForresterLu , It seems that your issue has been resolved, and I am going to close this issue now. If you have other questions, feel free to open another issue. Our engineering team is glad to answer and help.
