### ISSUE TITLE
gtest/gtest_prod.h: No such file or directory

### ISSUE THREAD

**Issue by zwqaoy** [ApolloAuto/apollo#131]
./modules/canbus/can_comm/can_sender.h:32:30: fatal error: gtest/gtest_prod.h: No such file or directory
 #include "gtest/gtest_prod.h"

**Comment by startcode** [comment]
If you are not in docker, you might have to install the gtest package by the following command, 
```
sudo apt-get install libgtest-dev  # assume you are using ubuntu system
```

**Comment by zwqaoy** [comment]
thanks, it is solved
