### ISSUE TITLE
Parking in Apollo 6.0

### ISSUE THREAD

**Issue by glebkiselev** [ApolloAuto/apollo#13105]
Good afternoon! I decided to check the parking mode and started analyzing maps with parking spaces. On all maps built into Apollo 6, parking spaces are not displayed in the dreamviewer, except for the Sunny Vale  with 2 offices map. I reproduced the situation from the issue https://github.com/ApolloAuto/apollo/issues/12994 and my car didn't leave the parking space either. Then I created a map with Apollo 3.5 markings, indicated the parking space and the road that approached the parking space. My parking space was not displayed. Parking space I created using following code in base_map.xml file:
![parking_code](https://user-images.githubusercontent.com/16453534/100853557-f54bf000-3498-11eb-9d41-991b69077766.png)
Question - how can I add a parking space so that it is displayed and available?
![parking2](https://user-images.githubusercontent.com/16453534/100853242-98503a00-3498-11eb-86da-c6e27bd64415.png)

**Comment by glebkiselev** [comment]
Update: parking works only on Sunnyvale With Two Offices map. Can somebody email me the map's xml and routings?

**Comment by daohu527** [comment]
The map is download into the docker, you can enter apollo docker and find the map in `/apollo/modules/map/data/sunnyvale_with_two_offices`.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
