### ISSUE TITLE
Who send Chassis message?

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#13109]
Hi, when Apollo is simulated with lg simulator and use Dreamview to command Apollo, which module send the Chassis messages if the Canbus component is off?

**Comment by daohu527** [comment]
lgsvl send the Chassis

**Comment by Turi30** [comment]
In which file is sent the message?

**Comment by daohu527** [comment]
You can find in **lgsvl** in "Assets\Scripts\Sensors\CanBusSensor.cs". You can try to understand the corresponding logic

**Comment by Turi30** [comment]
Can I find it in [this](https://github.com/lgsvl/apollo-5.0) repository?

**Comment by daohu527** [comment]
https://github.com/lgsvl/simulator

**Comment by Turi30** [comment]
Ok, but in these files I noted that there is a Chassis Writer and I thought that this writer sends the Chassis message when the environment is simuleted through the simulator. https://github.com/ApolloAuto/apollo/blob/3711be4317b62fffa548f91cb383269d4cc25987/modules/dreamview/backend/sim_control/sim_control.h#L143

https://github.com/ApolloAuto/apollo/blob/3711be4317b62fffa548f91cb383269d4cc25987/modules/dreamview/backend/sim_control/sim_control.cc#L98

**Comment by daohu527** [comment]
> when Apollo is simulated with lg simulator and use Dreamview to command Apollo

sim_control is use for simulation planning module, if you use lgsvl simulator, then lg send the chassis. if you use sim_control then sim_control send the chassis.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
