### ISSUE TITLE
In navigation mode,“/apollo/sensor/gnss/corrected_imu”  channel cannot be opened

### ISSUE THREAD

**Issue by yufeilongyuan** [ApolloAuto/apollo#13107]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

In navigation mode,“/apollo/sensor/gnss/corrected_imu”  channel cannot be opened

**Comment by diegohu** [comment]
/apollo/sensor/gnss/corrected_imu is outputted by IMU device, and decoded from "corrimudata" message of novatel protocol.

btw: which IMU device and Apollo version do you choose?

**Comment by yufeilongyuan** [comment]
> /apollo/sensor/gnss/corrected_imu is outputted by IMU device, and decoded from "corrimudata" message of novatel protocol.
> 
> btw: which IMU device and Apollo version do you choose?

@diegohu Thank you for your reply. **The device used is M2**, and "corrimudata" is not parsed. Now the problem is, I'm not sure whether M2 can send the "corrimudata" protocol. Is it necessary to reconfigure the hardware device? How to do it? thank you

**Comment by yufeilongyuan** [comment]
> > /apollo/sensor/gnss/corrected_imu is outputted by IMU device, and decoded from "corrimudata" message of novatel protocol.
> > btw: which IMU device and Apollo version do you choose?
> 
> @diegohu Thank you for your reply. **The device used is M2**, and "corrimudata" is not parsed. Now the problem is, I'm not sure whether M2 can send the "corrimudata" protocol. Is it necessary to reconfigure the hardware device? How to do it? thank you

@diegohu After setting, there is already **"/apollo/sensor/gnss/corrected_imu"** channel information. However, my purpose is to get the **“localization / pose”** channel information. What should I do next? thank you
![微信图片_20201204211108](https://user-images.githubusercontent.com/23471410/101167743-5b8d6a00-3675-11eb-8fd3-14d4ecb812f2.jpg)
