### ISSUE TITLE
How to simulate V2X communications with Apollo and lgsvl simulator?

### ISSUE THREAD

**Issue by MartinaB85** [ApolloAuto/apollo#13106]
Good morning,

I'm currently performing simulations with lgsvl simulator and Apollo 5.0, both on Linux Ubuntu 18.04.
- I would need to know..is it possible to implement V2X communications with Apollo and lgsvl simulator? If yes, how can I do that?
- Right now I would need that the Apollo car let pass a priority vehicle, for example by changing lane or stopping at the edge of the lane. how can I do that? Which part of Apollo's code do I need to modify in order to do this?

Many thanks in advance for your help,

Martina

**Comment by daohu527** [comment]
This is a relatively large demand that cannot be solved in a few words. Here are some suggestions below.

As I know, v2x does not directly control the autonomous vehicles for parking or changing lanes. Your strategic choice looks like a mixed solution. You can set the priority of the road or the priority of the vehicle, just broadcast the message. As for the behavior of autonomous vehicles, it depends on the strategies adopted by autonomous vehicles.

## steps
Below is a brief summary of the process.
1. Lgsvl broadcast the vehicle priority and the position of the car to surround cars. 
2. Apollo side receive the message and get the position of the priority car, it will change lane or just slow down. It depends on the strategy of autonomous vehicles.
3. the priority vehicle drive away and the autonomous vehicle will not receive the message again.

## network 
The real network model may be simplified, but you are simulating, so why bother to simulate the network process? The real network model might be
```
priority vehicle -> RSU (broadcast) -> OBU -> autonomous vehicles
```

**Comment by MartinaB85** [comment]
Thank you very much for your reply and suggestions.

I was actually thinking to implement kind of same steps you suggested. The main issue is that I'm new to all this and I would need please, if you can, some hints regarding the parts of code I would need to modify, especially on the apollo side, because understanding all the code at first is a bit hard for me.
Hope you can help me a little.

Thanks for your patience.

**Comment by daohu527** [comment]
The implementation of Apollo is in "modules\v2x". 

It has implemented v2x traffic lights and v2x obstacles, you can use it as a reference

**Comment by MartinaB85** [comment]
Ya, but which is the script in charge of taking action according to an event?

**Comment by daohu527** [comment]
It’s hard to explain in a few words.

There are some documents in Apollo, and you can also find some notes about Apollo on internet. Then ask some specific questions
