### ISSUE TITLE
How to use remote tools（Mobarxterm） to open dreamview locally

### ISSUE THREAD

**Issue by yufeilongyuan** [ApolloAuto/apollo#13101]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I can remotely connect to the server where Apollo is installed, but I can't open dreamview locally. If I want to open it, I can only open it on the server where Apollo is installed. How can I open dreamview locally? Thank you.

**Comment by changsh726** [comment]
If you want to access Dreamview which is launched on remote server, make sure you are using <Your server IP>:8888 other than localhost:8888.

**Comment by yufeilongyuan** [comment]
> If you want to access Dreamview which is launched on remote server, make sure you are using `<Your server IP>:8888` other than `localhost:8888`.

OK,thanks
