### ISSUE TITLE
Default Routing error

### ISSUE THREAD

**Issue by FitashUlHaq** [ApolloAuto/apollo#13112]
When I select any route from default routing it gives me this error 

app.bundle.js:34 GET http://navi-env.axty8vi3ic.us-west-2.elasticbeanstalk.com/dreamview/navigation?origin=37.414892717055956,-122.01274590992917&destination=37.41534249424038,-122.01259558801958&heading=0 net::ERR_NAME_NOT_RESOLVED
app.bundle.js:34 Failed to retrieve navigation data: TypeError: Failed to fetch

How can I fix this?

**Comment by diegohu** [comment]
Please follow the issue template to provide more details about your issue.
