### ISSUE TITLE
Need some help for using Cyber RT developer tools

### ISSUE THREAD

**Issue by qiongwu1003** [ApolloAuto/apollo#13115]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**: yes

### Steps to reproduce the issue:
The follow is my situation:

- Running LGSVL simulator with Apollo 5.0.(reference [here](https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/)).
- Use Velodyne Lidar.(reference [here](https://www.lgsvlsimulator.com/docs/lidar-plugin/#running-with-apollo-50)).
- Now I want to record Velodyne lidar point cloud data. I want to use our "cyber_reccorder".

But I meet some problem.
If I run LGSVL simulator with apollo, I need to run "bridge.sh" in docker, then the "bridge.sh" hang on there. So I can not run "cyber_recorder" in the docker anymore...

Am I in wrong method? How can I solve this problem? Thanks.

**Comment by changsh726** [comment]
You can open another terminal and enter the docker container, and then run cyber_recorder.
