### ISSUE TITLE
How to get the data in cyber_monitor by python scripts?

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#13113]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

Hello team, recently I am working on Apollo with LGSVL, and I can use **cyber_monitor** to check the information in different channel, and I want to use these channel information in my python script, so anyone know how to get these information by python API?
![Screenshot 2020-12-02 17:21:05](https://user-images.githubusercontent.com/26716009/100899423-cb2c1980-34fc-11eb-9c31-2f455e8dd111.png)

Actually I want to get the information in **/apollo/routing_request** channel, can anyone kindly give me an example about how to do that? Thanks.

The following picture shows the four data I want to obtain.  **id, s, x, y**

  id: lane_752
  s: 22.362609237

  x: 552998.623370790
  y: 4182687.753112647
![Screenshot 2020-12-02 17:21:05](https://user-images.githubusercontent.com/26716009/100899755-2100c180-34fd-11eb-8776-2dea8e6f2ad6.png)

**Comment by changsh726** [comment]
1. If you want to get the information in real time, you can create a `reader` by `cyber` module to listen to the `RoutingRequest` messages. An example can be found in [cyber listener example](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/listener.py).
2. If not, you can save all information with cyber_recorder tool and then parse the generated record file using `record` module. An example can be found in [record example](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/record.py)

**Comment by ForresterLu** [comment]
> 1. If you want to get the information in real time, you can create a `reader` by `cyber` module to listen to the `RoutingRequest` messages. An example can be found in [cyber listener example](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/listener.py).
> 2. If not, you can save all information with cyber_recorder tool and then parse the generated record file using `record` module. An example can be found in [record example](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/record.py)

Thanks for your reply @changsh726 , I have solved my question by referring [`cyber listener example` ](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/listener.py).

**Comment by Yimags** [comment]
> > 1. If you want to get the information in real time, you can create a `reader` by `cyber` module to listen to the `RoutingRequest` messages. An example can be found in [cyber listener example](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/listener.py).
> > 2. If not, you can save all information with cyber_recorder tool and then parse the generated record file using `record` module. An example can be found in [record example](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/record.py)
> 
> Thanks for your reply @changsh726 , I have solved my question by referring [`cyber listener example` ](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/listener.py).

Hello, I have the same purpose with you to get data from cyberRT. When I ran the listener.py, it showed a 'No module named '_cyber_wrapper' ' problem. Could you elaborate on how you solve this? Thanks in advance!
![error_no module](https://user-images.githubusercontent.com/64920943/101967720-01177f00-3c1c-11eb-8627-c248f25c0f97.png)

**Comment by storypku** [comment]
Hi @Yimags , it seems that you are running cyber out of Docker container. Currently, the team won't  provide support for running Apollo out of Docker as it will significantly increase the complexity and our burden.

As for your issue, currently, all python binaries were managed by Bazel in Apollo 6.0, and you should set proper PYTHONPATH Environment variable.

**Comment by Yimags** [comment]
> Hi @Yimags , it seems that you are running cyber out of Docker container. Currently, the team won't  provide support for running Apollo out of Docker as it will significantly increase the complexity and our burden.
> 
> As for your issue, currently, all python binaries were managed by Bazel in Apollo 6.0, and you should set proper PYTHONPATH Environment variable. 

Thx for your quick response. Actually I am running Apollo together with lgsvl and trying to control simulation and get data with Python API.

Excuse me for being new to Apollo stack, could you point me out about what path should I append in my Python script?

**Comment by ForresterLu** [comment]
> > Hi @Yimags , it seems that you are running cyber out of Docker container. Currently, the team won't  provide support for running Apollo out of Docker as it will significantly increase the complexity and our burden.
> > As for your issue, currently, all python binaries were managed by Bazel in Apollo 6.0, and you should set proper PYTHONPATH Environment variable.
> 
> Thx for your quick response. Actually I am running Apollo together with lgsvl and trying to control simulation and get data with Python API.
> 
> Excuse me for being new to Apollo stack, could you point me out about what path should I append in my Python script?

Hello @Yimags , you can try to run your scripts following [this instruction](https://github.com/ApolloAuto/apollo/tree/master/cyber/python).

**Comment by Yimags** [comment]
Thx! This is a very educational instrction!
I have been successful in running directally `bazel run //path/to:my_demo`. But another method `./bazel-bin/path/to/my_demo` didn't work for me. It gives a 'No such file or directory error. Is it the same case for you?
![error_build record](https://user-images.githubusercontent.com/64920943/103462168-b6bd8580-4d23-11eb-89b3-bb74fc9bf28e.png)

**Comment by marcusvinicius178** [comment]
@Yimags  @ForresterLu  @storypku  @changsh726  I had the same no such file or directory error trying to parse the data from the record file. I followed this tutorial https://github.com/ApolloAuto/apollo/tree/master/modules/tools/record_parse_save
The first part to store the channels data and get info from them worked, but to parse it failed as you can check below

![channels_ok_but_parse_record_not](https://user-images.githubusercontent.com/43826438/126015753-0fd3dbff-6531-46ca-9a37-3b92d9e3279e.png)

Is the record_parse_save.py code wrong? Which lines of code must I modify?
