### ISSUE TITLE
pcl missing some header files

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#13114]
In master branch ,the  latest dev docker.  The pcl header files were not complete.
The concave_hull.h  convex_hull.h   qhull.h   in pcl/surface/ were not exist.
I wonder why these were not included in the docker.

**Comment by storypku** [comment]
> In master branch ,the latest dev docker. The pcl header files were not complete.
> The concave_hull.h convex_hull.h qhull.h in pcl/surface/ were not exist.
> I wonder why these were not included in the docker.

Hi @sinopec , I think the main reason for this is the lack of  package `libqhull-dev` when building pcl from source. Currently, qhull related pcl libraries/headers were not used by Apollo runtime. You can prepare and make `libqhull-dev` a build-dep for [PCL installer](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_pcl.sh) .
