### ISSUE TITLE
Tracking between Detection

### ISSUE THREAD

**Issue by Basti110** [ApolloAuto/apollo#13129]
Hi,
I use the fusion_camera_detection_component in the perception module for the obstacle detection. My Hardware doesnt allow to process detection in real time (higher than 20fps). If the Image frequence is to high, the images are processed with a delay. 
In the obstacle_pipeline I see there is a tracking with OMTObstacleTracker before each detection. But this tracking is only used directly before an detection and not as an approximation result. 

Usually tracking is also used for a prediction beween the real detection as an approximation, when the detection(hardware) is to slow. But this doesnt seems to be the case here. 

How I can use tracking as approximation between the detection for multiple frames in the apollo framework? Is there a setting to enable it? 

I use a gtx970. I know, this card is not supported but the framework (also the detection) runs.

**Comment by daohu527** [comment]
Seems tracker is default enbale in "modules/perception/camera/app/obstacle_camera_perception.cc" and then detection

https://github.com/ApolloAuto/apollo/blob/01cb0335534f1a8c21ccdc1f359a062b5c6e371e/modules/perception/camera/app/obstacle_camera_perception.cc#L366-L379

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
