### ISSUE TITLE
In CyberRT scheduler, what is the cpuset

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#13136]
1.In scheduler_conf, I see there is a cpuset confiured from 0 to 31.Is it the real cpu core? most pcs only have 4 cpu cores or 8 cpu cores ,why is there 32 cpus?
2. Some tasks names are set as "planning_/apollo/perception/traffic_light" ,"planning","planning_/apollo/routing_response", what is the difference between them ,in dag file there is only "planning"
scheduler_conf {
    policy: "choreography"
    process_level_cpuset: "0-7,16-23"
    threads: [
        {
            name: "lidar"
            cpuset: "1"
            policy: "SCHED_RR"
            prio: 10
        }, {
            name: "shm"
            cpuset: "2"
            policy: "SCHED_FIFO"
            prio: 10
        }
    ]
    choreography_conf {
        choreography_processor_num: 8
        choreography_affinity: "range"
        choreography_cpuset: "0-7"
        choreography_processor_policy: "SCHED_FIFO"
        choreography_processor_prio: 10

        pool_processor_num: 8
        pool_affinity: "range"
        pool_cpuset: "16-23"
        pool_processor_policy: "SCHED_OTHER"
        pool_processor_prio: 0

        tasks: [
            {
                name: "A"
                processor: 0
                prio: 1
            },
            {
                name: "B"
                processor: 0
                prio: 2
            },
            {
                name: "C"
                processor: 1
                prio: 1
            },
            {
                name: "D"
                processor: 1
                prio: 2
            },
            {
                name: "E"
            }
        ]
    }
}

**Comment by qwetqwe** [comment]
It seems that if my cpu core number is 8 and I set cpuset to 30～31，then the processor will be scheduled to any  cpu？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
