### ISSUE TITLE
Dreamview no response after clicking the button

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#13134]
I found that sometimes Dreamview looks like it's stuck, with no response when clicking the button. 
such as: when I click opening GPS, In dreamview , it looks like already opened. but actually, there is no data in the GNSS topic. the GPS module is not opened successfully.
![image](https://user-images.githubusercontent.com/24958250/101234579-a5209800-36fb-11eb-9a22-40359af027d4.png)
then, if I ran the command ./script/gps.sh , it responded : gps.sh was already running.
then I run the following command:
./script/gps.sh stoped
./script/gps.sh
the GNSS topic can receive data successfully.

so using the scripts, I can successfully open the module, but with dreamview there is no response.

here is also a test: 
before I restart the dreamview, the following picture is the screenshot. 
after stop and start the dreamview, and refresh the webpage, and select the vehicle, the dreamview was still the following picture. 
![image](https://user-images.githubusercontent.com/24958250/101234690-7e169600-36fc-11eb-92ba-adcd71dcabb6.png)

Platform: D-kit apollo 2.5 ROS.

so, anyone can help me, and give me a direction for this issue.
thank you very much!

**Comment by daohu527** [comment]
> before I restart the dreamview, the following picture is the screenshot.

If you just restart the dreamview, it will not restart the modules. and when dreamview start again, it will sync the status of the module by websocket.

So I think you should first stop the module and wait a while the start again.

**Comment by WentaoWang-SH** [comment]
> > before I restart the dreamview, the following picture is the screenshot.
> 
> If you just restart the dreamview, it will not restart the modules. and when dreamview start again, it will sync the status of the module by websocket.
> 
> So I think you should first stop the module and wait a while the start again.


the problem is that I can't close the module, because the dreamview is stuck.  when I click "Reset All" or close all modules manually, actually it doesn't work, the modules are still open.

**Comment by YuqiHuai** [comment]
@daohu527 Hi! I am wondering if this issue has been investigated further.

I have been running dreamview for a few hours in a loop following order: reset, start sim control, send routing, (waits for completion), stop sim control.

I noticed after a while dreamview completely freezes, even if I refresh nothing changes. I see there are still websocket connection and responses, but no matter what I click on nothing happens.

I checked sim control is still publishing localization and other data using cyber_monitor.

This might be similar to the original poster’s problem, somehow resetting is breaking internal mechanism. How should I go about debugging this?

**Comment by daohu527** [comment]
> From browser console I see "Received duplicate simulation_world"

That means dreamview backend don't send messages or lag, I'm not sure what's wrong, need more info

**Comment by YuqiHuai** [comment]
@daohu527 I understand. How can I get more information?

I inserted `AINFO << "CALLING SIM_WORD_SERVICE_.UPDATE. Timer ID: " << timer_->GetID();` at the first line of the function https://github.com/ApolloAuto/apollo/blob/986fe474272413fca0621b245d1c7aa6a1e75316/modules/dreamview/backend/simulation_world/simulation_world_updater.cc#L719-L721

I also inserted lines to timer's destructor hoping to catch if the timer stopped, but did not see those lines being executed.

After 2 hours of running, I stopped getting `CALLING SIM_WORD_SERVICE_.UPDATE. Timer ID: 2` from `dreaview.info.log`, so I assume that `OnTimer` function is no longer being called. I don't see the timer stop information anywhere in the log.

Is there a way to check all running timers and inspect their status?

**Comment by YuqiHuai** [comment]
I have added log statement for timer before and after calling `callback`, before and after calling `sim_world_service_.Update()`
So I got logs in the following format:
```
W0726 22:20:25.295905   291 timer.cc:83] timer [2 ] executing callback.
W0726 22:20:25.295949   291 simulation_world_updater.cc:731] CALLING SIM_WORD_SERVICE_.UPDATE. Timer ID: 2
W0726 22:20:25.297428   291 simulation_world_updater.cc:733] CALLED SIM_WORD_SERVICE_.UPDATE. Timer ID: 2
W0726 22:20:25.299073   291 timer.cc:85] timer [2 ] executed callback.
```

After another 2 hours of running, I noticed the last pattern ended at 
```
W0726 22:20:25.395844   290 timer.cc:83] timer [2 ] executing callback.
W0726 22:20:25.395884   290 simulation_world_updater.cc:731] CALLING SIM_WORD_SERVICE_.UPDATE. Timer ID: 2
```
which means the `SimWorldService.Update()` function did not return for some reason.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
