### ISSUE TITLE
Control module closed after arriving the routing point

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#13131]
Recently, I found that sometimes (not all the time) when the car arriving at the routing point, the control modulewill be closed. 

From the monitor log, we can see that control was closed at 19:27:40.  (the car's arriving time is about at 19:27:30)
![image](https://user-images.githubusercontent.com/24958250/101168988-41548b80-3677-11eb-92d2-85797bd0eb7d.png)

here are some other log:
control.out:
![image](https://user-images.githubusercontent.com/24958250/101169228-8c6e9e80-3677-11eb-916b-c786816d6c80.png)

control.INFO
![image](https://user-images.githubusercontent.com/24958250/101169317-b45e0200-3677-11eb-9438-b5f9885fb19d.png)

and what kind of reason can cause the control module to be closed, anyone, can list some reason?

My platform is apollo d-kit, based on apollo 2.5 (ROS). but I think this issue is platform-independent.

Anyone had this issue before, or anyone have some information. Thank you in advance!

Thank you!

**Comment by WentaoWang-SH** [comment]
some other info maybe help: 
I clicked the "start auto"  about at 19:27:05
![image](https://user-images.githubusercontent.com/24958250/101170667-bde86980-3679-11eb-9779-a12a9f9c1287.png)

**Comment by daohu527** [comment]
Seems planning module didn't send msg cause control module error. so may be  you should check planning module erros first.

Also, the gps is unstable, you should deal with this problem first.

**Comment by WentaoWang-SH** [comment]
> Seems planning module didn't send msg cause control module error. so may be you should check planning module erros first.
> 
> Also, the gps is unstable, you should deal with this problem first.

1. Planning module didn't send msg because control module was waiting for planning module to be ready.
2. GPS is unstable, because it's single not RTK mode. 
so I think it's not because of these two reasons.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
