### ISSUE TITLE
Selectively disable modules for build

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13133]
### System information

- **OS Platform and Distribution Linux Ubuntu 16.04)
- **Apollo installed from (source or binary)**:
- **Apollo version 5.0:

I would like to disable some of the modules and only have select modules to be built and debugged to isolate effect from them on the module I am working on. For example: I only need drivers module on and all others turned off without impacting the full function of drivers. 
How can I do this in Apollo? What do I need to modify? Please let me know

thank you

**Comment by daohu527** [comment]
Take the **camera** module as an example.

## build the module
You can compile the camera module separately
```
bazel build modules/drivers/camera:libcamera_component.so
```


## start the module
You can use cyber_launch to start the module. here is a [link](https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/camera/README_cn.md#%E5%90%AF%E5%8A%A8camera%E9%A9%B1%E5%8A%A8)
```
cd /apollo && cyber_launch start modules/drivers/camera/launch/camera.launch
```

**Comment by storypku** [comment]
Hi @jpcloud1577 , module-level build is only available in the `r6.0.0`  and `master` branch. You can build single module with command like,   `./apollo.sh build cyber`, `./apollo.sh build_opt_gpu drivers`, etc. 

Please consider switching to the two branches I mentioned above and have a try.

**Comment by jpcloud1577** [comment]
Thank you @storypku and @daohu527 . I will give it a try

**Comment by storypku** [comment]
Hi @jpcloud1577 , hopes you have already had this issue resolved, then we will close this issue now. Please feel free to create another issue if you have other questions, or reopen this one if the problem persists.

Thank you.

**Comment by jpcloud1577** [comment]
Yes. thank you
