### ISSUE TITLE
NVIDIA Ampere (30x0) support

### ISSUE THREAD

**Issue by lemketron** [ApolloAuto/apollo#13142]
Are there any plans to add support for the NVIDIA Ampere architecture in the new 30x0 series GPUs?

**Comment by storypku** [comment]
> Are there any plans to add support for the NVIDIA Ampere architecture in the new 30x0 series GPUs?

Hello @lemketron, the Ampere architecture support is already WIP in master HEAD.  Just run `dev_start.sh --dist testing` to experiment with it.

**Comment by Gump0116** [comment]
> > Are there any plans to add support for the NVIDIA Ampere architecture in the new 30x0 series GPUs?
> 
> Hello @lemketron, the Ampere architecture support is already WIP in master HEAD. Just run `dev_start.sh --dist testing` to experiment with it.

Can I understand that it has been supported?

**Comment by storypku** [comment]
> > > Are there any plans to add support for the NVIDIA Ampere architecture in the new 30x0 series GPUs?
> > 
> > 
> > Hello @lemketron, the Ampere architecture support is already WIP in master HEAD. Just run `dev_start.sh --dist testing` to experiment with it.
> 
> Can I understand that it has been supported?

Experimental support only. We haven't checked that everything works well with this testing Docker. It needs time to stablize...

**Comment by hadiTab** [comment]
@storypku would you be able to share which Ampere architecture cards you guys have tested with? I'm specifically interested in knowing if the RTX 3060Ti is able to run Apollo.

**Comment by storypku** [comment]
> @storypku would you be able to share which Ampere architecture cards you guys have tested with? I'm specifically interested in knowing if the RTX 3060Ti is able to run Apollo.

Hi @hadiTab , sorry for the late reply. I am currently running Apollo on an RTX 3090, and I believe that Apollo should work smoothly on RTX 3060Ti cards.

**Comment by fedlucchetti** [comment]
Hi there,
I am trying to build Apollo on a RTX3090 however I get the following error during the build. 


 nvcc fatal : Unsupported gpu architecture 'compute_86'

I have following driver specs

NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2

nvcc: release 10.1, V10.1.243

Thank you for your help

**Comment by fedlucchetti** [comment]
> Hi there,
> I am trying to build Apollo on a RTX3090 however I get the following error during the build.
> 
> nvcc fatal : Unsupported gpu architecture 'compute_86'
> 
> I have following driver specs
> 
> NVIDIA-SMI 460.32.03 Driver Version: 460.32.03 CUDA Version: 11.2
> 
> nvcc: release 10.1, V10.1.243
> 
> Thank you for your help

SOLVED: Even though nvidia-smi was telling me that it used CUDA 11.2, the apollo built was using  CUDA 10.0
Changed CUDA version to 11.2 and Apollo is now running on a RTX3090

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
