### ISSUE TITLE
Drivers module documentation

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13143]
### System information

- **OS Platform and Distribution Linux Ubuntu 16.04
- **Apollo installed from source 
- **Apollo version 5.0

I would like to know if there is any documentation for the 'drivers' module in the repo that I can refer to. I see there is fair documentation for other modules, but I do not see anything for drivers module. Please let me know

**Comment by qwetqwe** [comment]
Drivers components most are adapted for the specifc sensor,get sensor data and tranfer to apollo data struct.You can get sensor product specification and open source driver to learn it.
