### ISSUE TITLE
darkSCNN_lane_detector prediction got wrong result 

### ISSUE THREAD

**Issue by xiaoliangxue** [ApolloAuto/apollo#13151]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **download darkscnn caffe model and test.jpg, run test.py and imshow result mask image, but got wrong result. help check **:

### test.py attachment
[test.py.zip](https://github.com/ApolloAuto/apollo/files/5663048/test.py.zip)
 

### result here
![图片](https://user-images.githubusercontent.com/26700989/101563328-08fcd680-3a04-11eb-86fa-d2965de60b0a.png)

**Comment by xiaoMrzhang** [comment]
Maybe you should check the input first, such as image preprocess or channel order(RGB & BGR)

**Comment by xiaoliangxue** [comment]
`# define transformer
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_transpose('data', (2,0,1))  # move image channels to outermost dimension
#transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
transformer.set_channel_swap('data', (2,1,0))  # swap channels from RGB to BGR
transformer.set_mean('data', np.array([95, 99, 96]))            # subtract the dataset-mean value in each channel

# load image
image = caffe.io.load_image('test.jpg')
crop_image = image[:, 312:, :]
resize_image = caffe.io.resize_image(crop_image, [480, 640])

#print(resize_image.shape)
transformed_image = transformer.preprocess('data', crop_image)
print(transformed_image.shape)

plt.imshow(transformed_image.transpose(1, 2, 0))
plt.show()`

input image result:
![图片](https://user-images.githubusercontent.com/26700989/101565010-20898e80-3a07-11eb-8d38-341eb330db13.png)

**Comment by xiaoliangxue** [comment]
no one responce the issue? online for help

**Comment by MaybeShewill-CV** [comment]
@xiaoliangxue paddle模型测试过能正常推理:)

**Comment by xiaoliangxue** [comment]
paddle模型在Apollo库哪个位置，没找到。用caffemodel你试过么？ @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@xiaoMrzhang 模型在这里 https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/camera/models/lane_detector/darkSCNN 没试过caffemodel 但是应该也不会有问题

**Comment by xiaoliangxue** [comment]
今天解决了。是我输入数据处理少了一行
`transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]`

![图片](https://user-images.githubusercontent.com/26700989/102315863-d75daf80-3faf-11eb-8dcd-a2589540a97b.png)
