### ISSUE TITLE
Reference document for setting accurate values for vehicle parameters

### ISSUE THREAD

**Issue by smartview-ai** [ApolloAuto/apollo#13162]
I would like to know  how the vehicle parameter's values has been set , how to ( on what reference)  i should adjust these values. 
ex : apollo/modules/common/data/vehicle_param.pb.txt
       length: 4.70
        width: 2.06
        height: 2.05
        min_turn_radius: 5.05386147161
        max_acceleration: 2.0
        max_deceleration: -6.0
        max_steer_angle: 8.20304748437
        max_steer_angle_rate: 6.98131700798

It would be appreciated if you could provide any references.

**Comment by daohu527** [comment]
I found some paramter in the official website. [link](https://www.ghac.cn/vehicles/honda/accord10/components/version-details?config)

I think these parameters are already fixed when the car leaves the factory.

**Comment by ManXiaoMi** [comment]
These values are usually offered by the car manufacturer. For example, if you bought the car from the Great Wall, you can ask them to offer these values.

**Comment by smartview-ai** [comment]
@diegohu  and @ManXiaoMi , Thank you for yours valuable info.
