### ISSUE TITLE
Error of ' No module named 'cyber.proto.unit_test_pb2' ' when trying to get data from cyberRT with pythonAPI

### ISSUE THREAD

**Issue by Yimags** [ApolloAuto/apollo#13187]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **run listener.py inside docker to get data from cyberRT**:

### Supporting materials (screenshots, command lines, code/script snippets):
![error_missingmodule](https://user-images.githubusercontent.com/64920943/102128425-25f33880-3e4e-11eb-8284-90628aafee2c.png)

**Comment by storypku** [comment]
Please run `bazel-bin/cyber/python/cyber_py3/examples/listener` instead. In Apollo 6.0, all Python libraries/binaries were managed by Bazel also.

**Comment by Yimags** [comment]
> Please run `bazel-bin/cyber/python/cyber_py3/examples/listener` instead. In Apollo 6.0, all Python libraries/binaries were managed by Bazel also.

Thx for your reponse! Do you mean I could run the existing `listen.py` from the path you indicated in docker? 
Actually I have both apollo-6.0 and apollo-5.0 on my computer. And there is no bazel-bin under Apollo-6.0. I can only find following stuffs under apollo-5.0 ducument.

There is no such a `listener.py` file in this path but only `py_listener_cpplint`  in similar path.

![error_no cyber py3](https://user-images.githubusercontent.com/64920943/102226518-c433dc80-3ee8-11eb-9fa3-59f9b59bcc11.png)
