### ISSUE TITLE
mainboard multi dag list file

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#13190]
In mainboard source code, each dag file must  be placed after an "-d"  parameter.
But in cyber_launch,while multi dag files are used in s single process, cyber_launch will place all dag files after a single -d parameter.,this will cause a mainboard open error.

**Comment by daohu527** [comment]
I test below command and it realy work, so can you describe your problem in detail ?
```
mainboard -d modules/dag/1.dag modules/dag/2.dag
```

**Comment by lfcarol** [comment]
You mean 'cyber_launch' execute a command like this 'mainboard -d XXXX.dag YYYYY.dag' ?

**Comment by daohu527** [comment]
Yes, when you want to run mutil dag, you can write like `perception_all.launch`. It will final run the cmd `mainboard -d modules/dag/1.dag modules/dag/2.dag`.

I think you may write like this?
```
    <module>
        <name>motion_service</name>
        <dag_conf>/apollo/modules/perception/production/dag/dag_motion_service.dag</dag_conf>
        <dag_conf>/apollo/modules/perception/production/dag/dag_motion_service1.dag</dag_conf>
        <process_name></process_name>
        <version>1.0.0</version>
    </module>
```
