### ISSUE TITLE
General question about bazel

### ISSUE THREAD

**Issue by Yimags** [ApolloAuto/apollo#13195]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0, 5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
I have installed both apollo-6.0 and apollo-5.0 in my computer. However I notice that only in apollo-5.0 those bazel documents exist. Will that influence the functionality of apollo-6.0? And should I do something to fix this?

### Supporting materials (screenshots, command lines, code/script snippets):
![error_no bazel](https://user-images.githubusercontent.com/64920943/102211151-7d87b780-3ed3-11eb-96a8-333811a35a0f.png)

**Comment by storypku** [comment]
As a general user, you should do nothing with Bazel.

Thank you.
