### ISSUE TITLE
com.google.devtools.build.lib.shell.BadExitStatusException

### ISSUE THREAD

**Issue by zwqaoy** [ApolloAuto/apollo#132]
/home/ckt/work/apollo/modules/canbus/can_client/BUILD:39:1: Linking of rule '//modules/canbus/can_client:can_client_tool' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-dbg/bin/modules/canbus/can_client/can_client_tool '-Wl,-rpath,$ORIGIN/../../../_solib_k8/_U@ros_S_S_Cros_Ucommon___Uexternal_Sros_Slib' ... (remaining 8 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld.gold: error: cannot find -lboost_system
collect2: error: ld returned 1 exit status

**Comment by startcode** [comment]
Can you install boost and try again?
```
sudo apt-get install libboost-all-dev
```

**Comment by startcode** [comment]
It seems to me that you are building apollo outside of docker. If you really don't want to use docker,
you might want to look at file `docker/dev.dockerfile`, and install all the packages inside that file to solve your dependency problem.

**Comment by zwqaoy** [comment]
thanks
