### ISSUE TITLE
YOLO 3D Network for Object Detection 

### ISSUE THREAD

**Issue by mertmerci** [ApolloAuto/apollo#13204]
Hi,

I'm investigating the Obstacle Detection and Tracking pipeline of Apollo. As far as I see, the YOLO network, employed for the Object Detection, outputs not only 2D BB but also 3D BB dimensions and yaw angle. Is there any paper proposing this special network or did you publish any, after you implement this network? Is there any source which gathers more information about this network? 

Thank you for your support.
Sincerely Yours.

**Comment by xiaoMrzhang** [comment]
[object detection in autoomous vehicle](https://mp.weixin.qq.com/s/XdH54ImSfgadCoISmVyyVg?utm_source=wechat_session&utm_medium=social&utm_oi=46510725136384&scene=1&clicktime=1608173612&enterid=1608173612) Here is a brief introduction to yolo3d. 
And there are also some monocular obstacle detection methods published in CVPR,ECCV in recent years, you also can get them in arxiv or github.

**Comment by mertmerci** [comment]
Dear @xiaohuitu, thank you for your prompt response.

Actully the YOLO3D is not the main focus on my research. I'm searching for a publish which arranges a 3D BB dimension regression, using only monocular camera images. Almost all algorithms that I checked and read about are estimating 3D BB dimensions after the deep neural network either using some likelihood or fetching from a lookup table. I'm interested in an approach which regresses the dimensions inside the neural network, as it is in the Apollo Framework. 

Do you have any suggestions for me? 
Thank you for your support.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
