### ISSUE TITLE
a bug in point_pillars detection

### ISSUE THREAD

**Issue by zhouleidcc** [ApolloAuto/apollo#13208]
**Describe the bug**
a nan error will happe randomly caused by the variable point_mean[3] not initialized with 0 in line 30 of apollo/modules/perception/lidar/lib/detection/lidar_point_pillars/pfe_cuda.cu

**Comment by storypku** [comment]
@jeroldchen @panfengsu Please help with this issue. Thank you.

**Comment by muzi2045** [comment]
you can set the point_mean to zero like below.
```
  float point_mean[3] = {0};
//float point_mean[3];
```
but there still have bug when you are test on Xavier after pfe_cuda.cu process.

@zhouleidcc
