### ISSUE TITLE
Navigation mode for apollo3.5 above

### ISSUE THREAD

**Issue by Yuyn1234** [ApolloAuto/apollo#13212]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I want to try the autonomous vehicle but I don't have the ability to make the hdmap. I think the navigation mode is very helpful for me but it no longer be supported.

**Comment by storypku** [comment]
Duplicate issue of #12931. Will be closed.
