### ISSUE TITLE
The Bug in Hybridastar Search Main Loop(update the node)

### ISSUE THREAD

**Issue by YaoQii** [ApolloAuto/apollo#13218]
Hello，apollos.
I have a question about [hybrid_a_star.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/open_space/coarse_trajectory_generator/hybrid_a_star.cc) in Planning module. And maybe it is a bug in search algo.
In the search main loop. we use the below code to add the next_node to open_set.
```
      if (open_set_.find(next_node->GetIndex()) == open_set_.end()) {
        explored_node_num++;
        const double start_time = Clock::NowInSeconds();
        CalculateNodeCost(current_node, next_node);
        const double end_time = Clock::NowInSeconds();
        heuristic_time += end_time - start_time;
        open_set_.emplace(next_node->GetIndex(), next_node);
        open_pq_.emplace(next_node->GetIndex(), next_node->GetCost());
      }
```
We add the next_node to open_set/open_pq_ that is not already in open_set_. But how do we dea withl the problem that the next_node is already in open_set_, but the new 'next_node' cost maybe smaller than that next_node alreay in open_set_. And I think we should update the open_set_'s value with new next_node.
Here is my question, thanks for your answers.

**Comment by devynliu** [comment]
你好，源代码是正确的。你所说的需要比较代价值这个问题。其实您还未理解这个开集的定义。开集是一个有序的序列，其是按照代价值进行排序的，代价值小的在上面，代价值大的在下面，你可以看到，当前节点是开集的最上面一个。所以按照这个思路，只要把next 节点加入到开集中，开集会自动排序，每次pop出当前节点是开集中代价值最小的。因此全部pop出的节点，他们的代价值一定是到达目的的最小最优代价值。望理解。

**Comment by devynliu** [comment]
当前节点：“ // take out the lowest cost neighboring node 
   const std::string current_id = open_pq_.top().first;”

**Comment by YaoQii** [comment]
你好。
我是这样想的：如果在open_set中已经存在一个节点12_8，但是并非最优节点，现在通过别的节点扩展序列再次扩展到节点12_8，但是其cost比已经处在open_set中的节点12_8更小，是否应该用最新的12_8节点替代现有open_set中原有的12_8。
谢谢。

**Comment by armme41** [comment]
> 你好。 我是这样想的：如果在open_set中已经存在一个节点12_8，但是并非最优节点，现在通过别的节点扩展序列再次扩展到节点12_8，但是其cost比已经处在open_set中的节点12_8更小，是否应该用最新的12_8节点替代现有open_set中原有的12_8。 谢谢。

我认为你是对的，如果邻近节点已在open_set中，应该判断是否要更新代价值
