### ISSUE TITLE
Creation of a localization map (local_map) for MSF localization !!!!!

### ISSUE THREAD

**Issue by insa2020** [ApolloAuto/apollo#13214]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

Hello Apollo team,

I'm trying to create a location map for msf location with **apollo/scripts/msf_local_map_creator.sh** script. For this I used the LGSVL simulator to record a data bag containing lidar and pose data.

Then I wanted to use the **apollo/scripts/msf_simple_map_creator.sh** or **./bazel-bin/modules/localization/msf/local_tool/data_extraction/monitor_data_exporter** script to extract the groups of point cloud frames and the pose file essential for the creation of the location map but when I run the script passing the necessary arguments I get the following error:

`Read topic: /apollo/sensor/velodyne64/compensator/PointCloud2
Compensated pcd callback.
Read topic: /apollo/localization/pose
I1217 14:49:53.952533 22167 location_exporter.cc:140] Fusion location callback.
Read topic: /apollo/sensor/gnss/odometry
I1217 14:49:53.952572 22167 location_exporter.cc:174] Odometry location callback.
Read topic: /apollo/localization/pose
I1217 14:49:53.952600 22167 location_exporter.cc:140] Fusion location callback.
Read topic: /apollo/localization/pose
I1217 14:49:53.952633 22167 location_exporter.cc:140] Fusion location callback.
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
./scripts/msf_simple_map_creator.sh: line 40: 22169 Aborted                 (core dumped) $APOLLO_BIN_PREFIX/modules/localization/msf/local_tool/map_creation/poses_interpolator --input_poses_path $INPUT_POSES_PATH --ref_timestamps_path $REF_TIMESTAMPS_PATH --extrinsic_path $EXTRINSIC_PATH --output_poses_path $OUTPUT_POSES_PATH
Pcd folders are as follows:
test/pcd
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1217 14:49:54.387840 22171 velodyne_utility.cc:126] Can't open file to read: test/pcd/corrected_poses.txt
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: No such file or directory: "data/bag/2020-12-17-14-23-54/lossless_map"
./scripts/msf_simple_map_creator.sh: line 52: 22171 Aborted                 (core dumped) $APOLLO_BIN_PREFIX/modules/localization/msf/local_tool/map_creation/lossless_map_creator --use_plane_inliers_only true --pcd_folders $1 --pose_files $2 --map_folder $IN_FOLDER --zone_id $ZONE_ID --coordinate_type UTM --map_resolution_type single
Reflectance map folder is invalid!
Done.`

**Has anyone encountered this problem? how can i create the location map? I am using Apollo 3.0 with LGSVL. thanks in advance**

**Comment by mengen100** [comment]
same issue on Apollo 5 and 6 with LGSVL, able to play the record file but cannot create local_map for it.
need help!!

**Comment by InterKnight** [comment]
I notice “'YAML::BadFile" in error, maybe it can not find the yaml file. Try use absolute path when you execute msf_simple_map_creator.sh
