### ISSUE TITLE
parking scenario apollo pre6.0

### ISSUE THREAD

**Issue by glebkiselev** [ApolloAuto/apollo#13215]
Hello. I am trying to send parking request from python script on Sunnyvale With Two Offices map. The code is:
send_parking_request(587191.89, 4141422.39, park_id=11546, park_x=587204.310000000, park_y=4141412.560000000)
def send_parking_request(x_start, y_start, park_id, park_x, park_y):
    msg = RoutingRequest()
    msg.header.module_name = 'dreamview'
    msg.header.sequence_num = 0
    waypoint = msg.waypoint.add()
    waypoint.pose.x = float(x_start)
    waypoint.pose.y = float(y_start)
    parking = msg.parking_info
    import struct
    parking.parking_space_id = struct.pack('!H', park_id)
    parking.parking_point.x = park_x
    parking.parking_point.y = park_y
    time.sleep(2.0)
    routing_writer.write(msg)
what is wrong? Why the car doesn't move? When I start the default routing scenario with the same coords - car park successfully. When I send move request from 1 point to another - everything works normally. Mb I need to allow any open_space_planner scenario?

**Comment by glebkiselev** [comment]
so there are no way to create python call for parking in available slot?

**Comment by daohu527** [comment]
> When I start the default routing scenario with the same coords

did you use routing request? There is already a tool mock routing request. I suggest you compare routing messages

**Comment by glebkiselev** [comment]
> did you use routing request? There is already a tool mock routing request. I suggest you compare routing messages

I check it in cyber_monitor - the request come correctly, with all information. The code to publish is:

  def parking_mode(linenum, routing_1_x, routing_1_y, routing_2_x, routing_2_y):
      import json
      with open("./python_scripts/parking_places.json", "r") as fp:
          poses = json.load(fp)
      cyber.init()
      writer = node.create_writer('/apollo/perception/obstacles', PerceptionObstacles)
      perception_description = obstacle_parking_gen(poses[linenum])
      perception = None
      parking_msg = None
      if linenum == "11546":
          parking_msg = send_parking_request(routing_1_x, routing_1_y, routing_2_x, routing_2_y, park_id=int(linenum), park_x=587204.310000000,
                               park_y=4141412.560000000)
      elif linenum == "11543":
          parking_msg = send_parking_request(routing_1_x, routing_1_y, routing_2_x, routing_2_y, park_id=int(linenum), park_x=587196.72, park_y=4141414.82)
      while not cyber.is_shutdown():
          perception = generate_perception(perception_description, perception)
          writer.write(perception)
          routing_writer.write(parking_msg)
          time.sleep(T)
where routing_writer = node.create_writer('/apollo/routing_request', RoutingRequest)
and parking_msg is RoutingRequest() + ParkingInfo() for msg.parking_info. 
The problem is that car is spawned in the correct place, but no movement begins. I need to turn down the routing module for the movement for 11546 slot. Or there is a routing mistake for 11543 slot (car doesn't move not at all).

**Comment by daohu527** [comment]
Could you pls format you code with`insert code`, Modify on the original message, don't paste again pls!

Can you describe in detail the message you sent, is it one type or two, `parking_msg is RoutingRequest() + ParkingInfo() for msg.parking_info` I don't quite understand you, is just Routing Request or two messages?
