### ISSUE TITLE
cyber_visualizer does not work?

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#13220]
### System information
Linux Ubuntu 18.04.5

Apollo version (5.5)
![Screenshot from 2020-12-21 10-54-13](https://user-images.githubusercontent.com/61130487/102734499-e612e080-437a-11eb-8e77-0daa8ea89ab0.png)

**Comment by hxj0316** [comment]
好像要修改apollo.sh中的代码。好像需要删除两行
