### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by MuhammadUbuntu** [ApolloAuto/apollo#13227]
I have followed the instruction to play demo_3.5 but when I run it the following massages (the permission denied) appear: 
E1221 17:47:02.750720 102421 segment.cc:41] [cyber_recorder]create shm failed, can't write now.
E1221 17:47:02.750727 102421 shm_transmitter.h:110] [cyber_recorder]acquire block failed.
E1221 17:47:02.755975 102421 xsi_segment.cc:144] [cyber_recorder]get shm failed. error: Permission denied
E1221 17:47:02.755995 102421 segment.cc:41] [cyber_recorder]create shm failed, can't write now.
E1221 17:47:02.756003 102421 shm_transmitter.h:110] [cyber_recorder]acquire block failed.
E1221 17:47:02.758880 102421 xsi_segment.cc:144] [cyber_recorder]get shm failed. error: Permission denied
E1221 17:47:02.758896 102421 segment.cc:41] [cyber_recorder]create shm failed, can't write now.
E1221 17:47:02.758904 102421 shm_transmitter.h:110] [cyber_recorder]acquire block failed.
E1221 17:47:02.760190 102421 xsi_segment.cc:144] [cyber_recorder]get shm failed. error: Permission denied
E1221 17:47:02.760207 102421 segment.cc:41] [cyber_recorder]create shm failed, can't write now.
E1221 17:47:02.760215 102421 shm_transmitter.h:110] [cyber_recorder]acquire block failed.

before I was able to perform the demo but now i don't know what is the issue.

We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:

**Comment by daohu527** [comment]
Seems below error, since you don't have more error information, I guess maybe `init_ ` is false?
```
  if (!init_ && !OpenOrCreate()) {
    AERROR << "create shm failed, can't write now.";
    return false;
  }
```

**Comment by lx18233184051** [comment]
> Seems below error, since you don't have more error information, I guess maybe `init_ ` is false?
> 
> ```
>   if (!init_ && !OpenOrCreate()) {
>     AERROR << "create shm failed, can't write now.";
>     return false;
>   }
> ```

we can see the error log is from here. so the problem is located easily.  please use gbd debug here.
