### ISSUE TITLE
how to add a module in HMI instead of using script to start and stop the module? 

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#13224]
how to add a module in HMI?

I want to add one hardware in apollo.  the start script is my_lidar.sh.
**now I can start/stop my hardware through script: ./script/my_lidar.sh start    ./script/my_lidar.sh stop**

**but I want to add a module in HMI instead of using the script?
what do I need to do?**

thank you for your help in advance!

![image](https://user-images.githubusercontent.com/24958250/102758027-0f4c6480-43ad-11eb-89d3-a3ba204c9665.png)

**Comment by daohu527** [comment]
## example
you can find some config example in `modules/dreamview/conf/hmi_modes/mkz_close_loop.pb.txt`, you may need to add your own modules and debug it.
```
modules {
  key: "Recorder"
  value: {
    start_command: "/apollo/scripts/record_bag.py --start"
    stop_command: "/apollo/scripts/record_bag.py --stop"
    process_monitor_config {
      command_keywords: "cyber_recorder record"
    }
  }
}
```

## principle
1. dreamview read the config, if you open the module (The sliding button in the UI)
2. dreamview will send the cmd to backend
3. backend will run the command

**Comment by lx18233184051** [comment]
if possible, please cyber_monitor to monitor you new lidar channel data. If you insist on HMI, please keep the same channel name with original.
