### ISSUE TITLE
The Modules' rate are very lower than the normal rate.

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#13225]
Recently, when I was testing, I found that the modules' rate is very lower than the normal rate.  
sometimes, the topic didn't update, especially for the topic: /apollo/sensor/gnss/bestpose.  

Does anyone know about this issue, any reasons?

My platform is: Apollo Kit - NVIDIA TX2 

the following topic:
rostopic hz /apollo/senser/gnss/bestpose
rostopic hz /apollo/planning
rostopic hz /apollo/localization/pose 

![image](https://user-images.githubusercontent.com/24958250/102760895-1ffed980-43b1-11eb-9853-7675c273ddf9.png)

![image](https://user-images.githubusercontent.com/24958250/102760923-2db45f00-43b1-11eb-8d55-e44a9a57530b.png)

![image](https://user-images.githubusercontent.com/24958250/102761054-576d8600-43b1-11eb-9c4a-772e1bbfb8e3.png)

 At the same time, top monitor is :(I think the CPU resource is ok. right?)
![image](https://user-images.githubusercontent.com/24958250/102761817-64d74000-43b2-11eb-8bf6-e37c777441fb.png)

thank you very much in advance!

**Comment by daohu527** [comment]
The topic is published by gnss. You should check why gnss not publish such message.

**Comment by lx18233184051** [comment]
debug in planning and localization  componment, check what's the reason why not publish.
