### ISSUE TITLE
How to save DEBUG information of control module to local CSV file

### ISSUE THREAD

**Issue by liukr001** [ApolloAuto/apollo#13223]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.5)**:

**Comment by daohu527** [comment]
open below config and you can find DEBUG level log in `data/log/xx.INFO`
https://github.com/ApolloAuto/apollo/blob/cbdf1499bf7c1b6e0020eeb4937da7e34998e14b/cyber/setup.bash#L42-L43
