### ISSUE TITLE
apollo6.0 and LGSVL error:Both GNSS and Lidar Localization is invalid.

### ISSUE THREAD

**Issue by lixiyu12** [ApolloAuto/apollo#13221]
apollo6.0 and LGSVL error:Both GNSS and Lidar Localization is invalid.

![mmexport1608518916208](https://user-images.githubusercontent.com/64055663/102734521-fa56dd80-437a-11eb-9237-b10528cce59c.jpg)

**Comment by daohu527** [comment]
Because you didn't open the gps  and localizaiton module ?
