### ISSUE TITLE
cyber/component/component_base deps missing include "gflags", but build successfully

### ISSUE THREAD

**Issue by Corezcy** [ApolloAuto/apollo#13237]
### System information

- **OS Platform and Distribution**: Ubuntu 18.04
- **Apollo installed from**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
In `component_base.h` , it has included "gflags/gflags.h" .But int it's build file , dont have "@com_github_gflags_gflags//:gflags". 
Suprisingly, run `bazel build //cyber/component:component_base`, it  builds successfully. Why ???

**Comment by storypku** [comment]
In the `r6.0.0` branch / `v6.0.0` tag, `glog` was defined to depend on `gflags`. 

third_party/glog/glog.BUILD
```
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "glog",
    includes = [
        ".",
    ],
    linkopts = [
        "-L/usr/local/lib",
        "-lglog",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
    ],
)
```

So `component_base` depends on glog which in turn depends on gflags.  
However, since component_base depends **directly** on gflags, one should explicitly declare the dependency in cyber/component/BUILD file (which means r6.0.0 serves a bad example in this regard.)

**Comment by Corezcy** [comment]
> In the `r6.0.0` branch / `v6.0.0` tag, `glog` was defined to depend on `gflags`.
> 
> third_party/glog/glog.BUILD
> 
> ```
> load("@rules_cc//cc:defs.bzl", "cc_library")
> 
> package(default_visibility = ["//visibility:public"])
> 
> licenses(["notice"])
> 
> cc_library(
>     name = "glog",
>     includes = [
>         ".",
>     ],
>     linkopts = [
>         "-L/usr/local/lib",
>         "-lglog",
>     ],
>     deps = [
>         "@com_github_gflags_gflags//:gflags",
>     ],
> )
> ```
> 
> So `component_base` depends on glog which in turn depends on gflags.
> However, since component_base depends **directly** on gflags, one should explicitly declare the dependency in cyber/component/BUILD file (which means r6.0.0 serves a bad example in this regard.)
> 
> Hope my answer helps.

Thanks for answering! I see in apollo , the deps like`gflags` only uses once in top layer ,which is confusing.
