### ISSUE TITLE
How to get the trajectory information of NPC vehicle?

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#13231]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Ubuntu 18.04
- **Apollo installed from (source or binary)**:binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.0

### Main goals:
Hello team, i notice that when the ego vehicle driving in Apollo, there are also trajectories of NPC vehicles in dreamviewer. And anyone know how to get these trajectories of NPC vehicle?

**Comment by daohu527** [comment]
You can look at topic `/apollo/prediction/perception_obstacles`

The trajectories are in below format. `repeated Trajectory trajectory = 4;`
https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/prediction/proto/prediction_obstacle.proto#L38-L47

**Comment by ForresterLu** [comment]
> You can look at topic `/apollo/prediction/perception_obstacles`
> 
> The trajectories are in below format. `repeated Trajectory trajectory = 4;`
> https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/prediction/proto/prediction_obstacle.proto#L38-L47
Thank you very much, i have solved the problem with your instruction.
