### ISSUE TITLE
ndt_map_creator.cc got a bug.

### ISSUE THREAD

**Issue by MountainXiu** [ApolloAuto/apollo#13238]
file : autoapollo/modules/localization/ndt/map_creation/ndt_map_creator.cc
line: 92 to 105
```
if (fabs(single_resolution_map - 0.03125) > 1e-8 &&
      fabs(single_resolution_map - 0.0625) > 1e-8 &&
      fabs(single_resolution_map - 0.125) < 1e-8 &&
      fabs(single_resolution_map - 0.25) < 1e-8 &&
      fabs(single_resolution_map - 0.5) < 1e-8 &&
      fabs(single_resolution_map - 1.0) < 1e-8 &&
      fabs(single_resolution_map - 2.0) < 1e-8 &&
      fabs(single_resolution_map - 4.0) < 1e-8 &&
      fabs(single_resolution_map - 8.0) < 1e-8 &&
      fabs(single_resolution_map - 16.0) < 1e-8) {
    std::cerr << "map resolution can only be: 0.03125, "
              << "0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, "
              << "4.0, 8.0 or 16.0." << std::endl;
  }
```
may be change to next lines
```
if (fabs(single_resolution_map - 0.03125) < 1e-8 &&
      fabs(single_resolution_map - 0.0625) < 1e-8 &&
      fabs(single_resolution_map - 0.125) < 1e-8 &&
      fabs(single_resolution_map - 0.25) < 1e-8 &&
      fabs(single_resolution_map - 0.5) < 1e-8 &&
      fabs(single_resolution_map - 1.0) < 1e-8 &&
      fabs(single_resolution_map - 2.0) < 1e-8 &&
      fabs(single_resolution_map - 4.0) < 1e-8 &&
      fabs(single_resolution_map - 8.0) < 1e-8 &&
      fabs(single_resolution_map - 16.0) < 1e-8) {
    std::cerr << "map resolution can only be: 0.03125, "
              << "0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, "
              << "4.0, 8.0 or 16.0." << std::endl;
  }
```

**Comment by storypku** [comment]
@tthhee @zhouyao4321 Please help with this issue.

**Comment by storypku** [comment]
> file : autoapollo/modules/localization/ndt/map_creation/ndt_map_creator.cc
> line: 92 to 105
> 
> ```
> if (fabs(single_resolution_map - 0.03125) > 1e-8 &&
>       fabs(single_resolution_map - 0.0625) > 1e-8 &&
>       fabs(single_resolution_map - 0.125) < 1e-8 &&
>       fabs(single_resolution_map - 0.25) < 1e-8 &&
>       fabs(single_resolution_map - 0.5) < 1e-8 &&
>       fabs(single_resolution_map - 1.0) < 1e-8 &&
>       fabs(single_resolution_map - 2.0) < 1e-8 &&
>       fabs(single_resolution_map - 4.0) < 1e-8 &&
>       fabs(single_resolution_map - 8.0) < 1e-8 &&
>       fabs(single_resolution_map - 16.0) < 1e-8) {
>     std::cerr << "map resolution can only be: 0.03125, "
>               << "0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, "
>               << "4.0, 8.0 or 16.0." << std::endl;
>   }
> ```
> 
> may be change to next lines
> 
> ```
> if (fabs(single_resolution_map - 0.03125) < 1e-8 &&
>       fabs(single_resolution_map - 0.0625) < 1e-8 &&
>       fabs(single_resolution_map - 0.125) < 1e-8 &&
>       fabs(single_resolution_map - 0.25) < 1e-8 &&
>       fabs(single_resolution_map - 0.5) < 1e-8 &&
>       fabs(single_resolution_map - 1.0) < 1e-8 &&
>       fabs(single_resolution_map - 2.0) < 1e-8 &&
>       fabs(single_resolution_map - 4.0) < 1e-8 &&
>       fabs(single_resolution_map - 8.0) < 1e-8 &&
>       fabs(single_resolution_map - 16.0) < 1e-8) {
>     std::cerr << "map resolution can only be: 0.03125, "
>               << "0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, "
>               << "4.0, 8.0 or 16.0." << std::endl;
>   }
> ```

Hi @MountainXiu, thanks for reporting this issue to us!

The bug you pointed out did exist, however, it seems that the solution should be the following:

```
if (fabs(single_resolution_map - 0.03125) > 1e-8 &&
      fabs(single_resolution_map - 0.0625) > 1e-8 &&
      fabs(single_resolution_map - 0.125) > 1e-8 &&
      fabs(single_resolution_map - 0.25) > 1e-8 &&
      fabs(single_resolution_map - 0.5) > 1e-8 &&
      fabs(single_resolution_map - 1.0) > 1e-8 &&
      fabs(single_resolution_map - 2.0) > 1e-8 &&
      fabs(single_resolution_map - 4.0) > 1e-8 &&
      fabs(single_resolution_map - 8.0) > 1e-8 &&
      fabs(single_resolution_map - 16.0) > 1e-8) {
    std::cerr << "map resolution can only be: 0.03125, "
              << "0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, "
              << "4.0, 8.0 or 16.0." << std::endl;
  }
```

**Comment by tthhee** [comment]
yes, it is actually a bug, @storypku 's answer is right.
