### ISSUE TITLE
Why remove all onnx models and use libtorch instead in lidar_point_pillars module?

### ISSUE THREAD

**Issue by SeanZhang777** [ApolloAuto/apollo#13236]
I noticed that in recent update #13189 , you remove all onnx models and use several libtorch models instead. Does this improve the speed? And why use several separate libtorch models rather than using one single pointpillar model? Looking forward to your reply.

**Comment by panfengsu** [comment]
we update pointpillars model based Waymo dataset, because it has better performance. Some operators are not supported by onnx, so inference use libtorch temporarily. Pointpillars model is split several separate libtorch models  because of modularity, we will optimize this part later.

**Comment by SeanZhang777** [comment]
Thanks for your quick reply, and looking forward to your optimization.

**Comment by LeijieZhang001** [comment]
> Thanks for your quick reply, and looking forward to your optimization.
Would you please send an email to me? I want to establish contact with you for some consultation. You can find my email address in my blog.
