### ISSUE TITLE
PREEMPT_RT error when installing the Nvidia driver with the Apollo 1.5 Kernel

### ISSUE THREAD

**Issue by vicla** [ApolloAuto/apollo#1323]
I was following the steps in the 1.5 hardware system installation guide to install Apollo, but now I'm stuck at the [installing Nvidia GPU driver section](
https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_5_hardware_system_installation_guide.md#installing-nvidia-gpu-driver).

The previous step installed the real-time Apollo kernel which seems to be incompatible with the Nvidia driver, since the driver doesn't support real-time kernels.  Am I missing a step to get this driver to work?

Thanks!

**Comment by joekale** [comment]
I am seeing this issue as well.
After executing the run file it fails with

> ERROR: The kernel you are installing for is a PREEMPT_RT kernel! The NVIDIA driver does not support real-time kernels...

**Comment by vicla** [comment]
I think I might have solved my issue.  Instead of going through the steps listed under "Installing Nvidia GPU Driver", I think you need to run the install-nvidia.sh script that is in the same install folder as install_kernel.sh.

```
apollo@apollo-ts:~/Downloads/install$ sudo bash install-nvidia.sh
Extracting nvidia install run file...
Done to install nvidia kernel driver and user libraries.
```

**Comment by gengqx** [comment]
By this way,It only extract several used library,The display driver is still not working,When you use nvidia-smi,the screen the will be black for a few moment.

**Comment by vicla** [comment]
I think this might be the correct behavior.  The IPC that they use has a integrated graphics card in addition to the NVIDIA GPU.  The integrated graphics handles the typical display functions while the NVIDIA GPU is dedicated to Apollo.  This is my assumption based on the [Preparing the IPC](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_5_hardware_system_installation_guide.md#preparing-the-ipc) section.

**Comment by inumo** [comment]
use 
"sudo bash ./NVIDIA-Linux-x86_64-375.39.run --no-x-check -a -s --no-kernel-module"
to install the NVIDIA Drive  with specific option --no-kernel-module.
