### ISSUE TITLE
About the meaning of '*ff' used in imu.conf.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo#13249]
In the example config [file](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/sample/imu.conf) for imu, the following content are given:
```
$cmd,set,leverarm,gnss,0,-0.1,0.6*ff
$cmd,set,headoffset,0*ff
$cmd,set,navmode,FineAlign,off*ff
$cmd,set,navmode,coarsealign,off*ff
$cmd,set,navmode,dynamicalign,on*ff
$cmd,set,navmode,gnss,double*ff
$cmd,set,navmode,carmode,on*ff
$cmd,set,navmode,zupt,on*ff
$cmd,set,navmode,firmwareindex,0*ff
$cmd,output,usb0,rawimub,0.010*ff
$cmd,output,usb0,inspvab,0.010*ff
$cmd,through,usb0,bestposb,1.000*ff
$cmd,through,usb0,rangeb,1.000*ff
$cmd,through,usb0,gpsephemb,1.000*ff
$cmd,through,usb0,gloephemerisb,1.000*ff
$cmd,through,usb0,bdsephemerisb,1.000*ff
$cmd,through,usb0,headingb,1.000*ff
$cmd,set,localip,192,168,0,123*ff
$cmd,set,localmask,255,255,255,0*ff
$cmd,set,localgate,192,168,0,1*ff
$cmd,set,netipport,203,107,45,154,8002*ff
$cmd,set,netuser,qianxun1234:abc123*ff
$cmd,set,mountpoint,RTCM32_GGB*ff
$cmd,set,ntrip,enable,enable*ff
ppscontrol enable positive 1.0 10000
log com3 gprmc ontime 1 0.25
$cmd,save,config*ff
```
As you can see, there are so many lines ended with '*ff'. What's the meaning of this flag? Any hints will be highly appreciated.

Regards,
HY

**Comment by lishuanghua** [comment]
As “$cmd”, “*ff” is just a sign, they don't have any practical significance.

**Comment by hongyi-zhao** [comment]
If so, why not discard/eliminate these mysterious, puzzling, and redundant signs?

**Comment by lishuanghua** [comment]
Because we need the flags, and the flags we choosed are the above two phrases happenedly.

**Comment by hongyi-zhao** [comment]
Still not so clear on the mechanism for selecting these flags. Could you please give me some more detailed background knowledge on them?

**Comment by lishuanghua** [comment]
Their meanings are just the positions. one is beginning of the command and the other is ending.

**Comment by hongyi-zhao** [comment]
BTW, which programming language does the style belong to? I've never seen them.
