### ISSUE TITLE
Error in Building Process

### ISSUE THREAD

**Issue by jerry99s** [ApolloAuto/apollo#13247]
An error (ERROR: Config value 'cpu' is not defined in any .rc file) appeared when I entered "bash apollo.sh build".

```
root@in-dev-docker:/apollo# bash apollo.sh build
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: @non-git
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20201210_1400
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview: 
[INFO]     USE_GPU: 0  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=cpu
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/... except //modules/perception/... except //modules/planning/open_space/trajectory_smoother:planning_block except //modules/map/pnc_map:cuda_pnc_util except //modules/map/pnc_map:cuda_util_test
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/apollo/tools/bazel.rc
ERROR: Config value 'cpu' is not defined in any .rc file
```
OS: Ubuntu 16.04
Version: Apollo 6.0

Could you please tell me what should I do?

**Comment by storypku** [comment]
Try running `./apollo.sh config -n` first and then try again.

**Comment by jerry99s** [comment]
> Try running `./apollo.sh config -n` first and then try again.

This problem has been solved. Thank you! @storypku

**Comment by lcysys** [comment]
i still got the same error after following the suggestion, is there anything i missed ? the log is inserted below:

root@in-dev-docker:/apollo# ./apollo.sh config -n
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: @non-git
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210108_1105
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Configure .apollo.bazelrc in non-interactive mode
You have bazel 3.7.1 installed.
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Found CUDA 10.2 in:
    /usr/local/cuda-10.2/targets/x86_64-linux/lib
    /usr/local/cuda-10.2/targets/x86_64-linux/include
Found cuDNN 7 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include
Found TensorRT 7 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include/x86_64-linux-gnu


[ OK ] Successfully configured .apollo.bazelrc in non-interactive mode.
root@in-dev-docker:/apollo# ./apollo.sh build_opt
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: @non-git
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210108_1105
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview: 
[INFO]     USE_GPU: 0  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=cpu --config=opt
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/... except //modules/perception/... except //modules/planning/open_space/trajectory_smoother:planning_block except //modules/map/pnc_map:cuda_pnc_util except //modules/map/pnc_map:cuda_util_test
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/apollo/tools/bazel.rc
ERROR: Config value 'cpu' is not defined in any .rc file

**Comment by xqgex** [comment]
@lcysys the problem is probably with how you are running the Docker image

Try to do it like this:
```sh
xhost local:root && \
docker run --interactive \
           --env DISPLAY=$DISPLAY \
           --gpus all \
           --name <GIVE_IT_A_NAME> \
           --network=host \
           --privileged \
           --rm \
           --tty \
           --user 0:0 \
           --volume /tmp/.X11-unix:/tmp/.X11-unix \
           --volume /usr/lib32/nvidia:/usr/lib32/nvidia \
           --volume /usr/lib/nvidia:/usr/lib/nvidia \
           <THE_IMAGE_NAME>:<THE_IMAGE_VERSION> \
           /bin/bash
```
(don't forget to replace `<GIVE_IT_A_NAME>`, ` <THE_IMAGE_NAME>`, `<THE_IMAGE_VERSION>`)
