### ISSUE TITLE
Question about synchronizing data from cyberRT

### ISSUE THREAD

**Issue by Yimags** [ApolloAuto/apollo#13258]
I have noticed that like in reality the data transferred in cyberRT are of different frame ratios. So I am just wondering if there is a way to get all the data of one exact frame without any time difference? Or if I could adjust the frame ratio of different sensor to realize that?
Thx in anvance!

**Comment by daohu527** [comment]
The function you need is "time synchronization".

1. The current "cyber" data fusion method is "all_latest". If you have multiple messages, trigger based on the first message, then take the second and third latest messages, and finally you get 3 messages.

2. The current main method is hardware synchronization, not software. 

3. ROS has a fusion method based on the most recent time, I need to find it.

**Comment by Yimags** [comment]
Thanks for your explanation! I am gonna look into it further.
