### ISSUE TITLE
How to run two Apollos on one machine？

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#13255]
Hello team, I am working on Apollo recently, and i need to run 2 apollos parallely, but when i run the second apollo then the first will stop, is there any method to run two apollos parallely?

**Comment by daohu527** [comment]
It does not seem to be supported at present, which will cause some problems, such as hardware sharing.

**Comment by ForresterLu** [comment]
> It does not seem to be supported at present, which will cause some problems, such as hardware sharing.

Can i modify the host of Apollo docker and then run them parallely?

**Comment by storypku** [comment]
> It does not seem to be supported at present, which will cause some problems, such as hardware sharing.

As @daohu527 said, it **may** cause problems if you need to access hardware of the host machine. If hardware access if not needed at all, you can twist `dev_start.sh` and `dev_into.sh` to run two copies of Apollo Dev containers by 1) specifying each a unique `APOLLO_DEV` value. 2) You **may** also need to replace all [`docker_restart_volume`](https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L387) with  [`reuse_or_start_volume`]( https://github.com/ApolloAuto/apollo/blob/master/.teamcity/run_ci.sh#L167). 

To better separate the two containers,  and allow Bazel to build simultaneously, you'd better have two copies of Apollo source code on your host. 

A CyberRT (`cyber_start.sh` & `cyber_into.sh`)  container and a Dev container can run in parallel on the same HOST directory.

Please note that all the stuffs I mentioned are  **experimental** and **undocumented**, use it at your own risk.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
