### ISSUE TITLE
Apollo 6.0 docker compile,  Unsupported gpu architecture ‘compute_86‘?

### ISSUE THREAD

**Issue by fuqiankun** [ApolloAuto/apollo#13254]
Apollo6.0 docker compile  ./apollo build_opt_gpu Unsupported gpu architecture ‘compute_86’ 
```
(13:27:17) ERROR: /apollo/modules/planning/open_space/trajectory_smoother/BUILD:263:13: C++ compilation of rule '//modules/planning/open_space/trajectory_smoother:planning_block' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/modules/planning/open_space/trajectory_smoother/_objs/planning_block/planning_block.pic.d ... (remaining 56 argument(s) skipped)
nvcc fatal   : Unsupported gpu architecture 'compute_86'
(13:27:17) INFO: Elapsed time: 33.801s, Critical Path: 31.91s
(13:27:17) INFO: 341 processes: 149 remote cache hit, 115 internal, 77 local.
(13:27:17) FAILED: Build did NOT complete successfully
```

My ubuntu18 PC the CUDA environment by nvidia-smi:

![image](https://user-images.githubusercontent.com/4407654/103218333-a8532080-4955-11eb-8208-67ca6f4ca223.png)

But the docker's cuda version is 10.2, /usr/local/cuda-10.2?

**Comment by storypku** [comment]
What's your Nvidia GPU model according to https://developer.nvidia.com/cuda-gpus ？

**Comment by fuqiankun** [comment]
My nvidia device is RTX 3060 Ti, it support compute_86 arch that need cuda-11.1.  But the cuda version of our apollo's docker image is 10.2

**Comment by storypku** [comment]
> My nvidia device is RTX 3060 Ti, it support compute_86 arch that need cuda-11.1. But the cuda version of our apollo's docker image is 10.2

You can try our Testing Dev Docker which comes with CUDA-11.1/cuDNN-8/TensorRT-7.2.1 and  30x0(Ampere) GPU support.

Start it by running the following commands:

```
dev_start.sh --dist testing   # Or for users of China, dev_start.sh --dist testing -g cn 
dev_into.sh
```

You may also need to run `./apollo.sh config -n` to overwrite previous version of `.apollo.bazelrc` config.

Hope my answer helps.

**Comment by fuqiankun** [comment]
> ```
> dev_into.sh
> ```

After using the testing image you mentioned above， ./apollo build_opt_gpu , it comes some error:
```
(04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/concave_hull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
(04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/convex_hull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
(04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/impl/concave_hull.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
(04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/impl/convex_hull.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
(04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/qhull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
(04:45:44) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: not all outputs were created or valid
```
How can I solve it?

**Comment by fuqiankun** [comment]
the tesing image which include cuda-11.1， the following file is missing..
```
external/local_config_pcl/pcl/include/pcl/surface/concave_hull.h
external/local_config_pcl/pcl/include/pcl/surface/impl/concave_hull.hpp
```
@storypku  help me take a look

**Comment by storypku** [comment]
> > ```
> > dev_into.sh
> > ```
> 
> After using the testing image you mentioned above， ./apollo build_opt_gpu , it comes some error:
> 
> ```
> (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/concave_hull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/convex_hull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/impl/concave_hull.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/impl/convex_hull.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/qhull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> (04:45:44) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: not all outputs were created or valid
> ```
> 
> How can I solve it?

You should run `rm -rf .cache/{bazel,build,repos}` of previous builds and try again.

**Comment by fuqiankun** [comment]
> > > ```
> > > dev_into.sh
> > > ```
> > 
> > 
> > After using the testing image you mentioned above， ./apollo build_opt_gpu , it comes some error:
> > ```
> > (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/concave_hull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> > (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/convex_hull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> > (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/impl/concave_hull.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> > (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/impl/convex_hull.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> > (04:45:43) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: declared output 'external/local_config_pcl/pcl/include/pcl/surface/qhull.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
> > (04:45:44) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_pcl/BUILD:62:8: not all outputs were created or valid
> > ```
> > 
> > 
> > How can I solve it?
> 
> You should run `rm -rf .cache/{bazel,build,repos}` of previous builds and try again.

thanks , it works

**Comment by hadiTab** [comment]
@fuqiankun did you run into any issues with that graphics card (RTX 3060Ti) and Apollo? Were you able to run perception?

**Comment by HuangCongQing** [comment]
_third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl_

you can try !
**compute_86 -->compute_75**
![image](https://user-images.githubusercontent.com/20675770/144190787-ccd3fe7c-17b3-477f-97d5-57a8c746cfd6.png)
