### ISSUE TITLE
Blocker in the Reader.

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#13265]
Each reader has a blocker which has a message list inside. Why use a list if when publish a message push in front and when observe take the message in front?

**Comment by daohu527** [comment]
It is a queue and not a list, What do you mean by list
https://github.com/ApolloAuto/apollo/blob/11104c3d8bead0034dbf0723bf682ae4c2c97d99/cyber/blocker/blocker.h#L107-L110

**Comment by Turi30** [comment]
What policy is adopted in this queue?

**Comment by daohu527** [comment]
it's a queue, without any priority. 

I think there is no way to control the priority of the message for now, only the priority of the coroutine?

**Comment by lx18233184051** [comment]
> it's a queue, without any priority.
> 
> I think there is no way to control the priority of the message for now, only the priority of the coroutine?

NO policy, just FIFO.

**Comment by lx18233184051** [comment]
> What policy is adopted in this queue?

NO policy, just FIFO.

**Comment by Turi30** [comment]
Ok, but I have a question. For example in the code below,  in the function called at line 282 happens ` observed_msg_queue_ = published_msg_queue_;` and in the function called at the line 283 
```
if (observed_msg_queue_.empty()) {
    return dummy_msg_;
  }
  return *observed_msg_queue_.front();
```
Why I take the element in front of the queue and not in the back?

>    https://github.com/ApolloAuto/apollo/blob/55fe6dab85b48220f9f9cc2a0266fb21fc16f64f/modules/control/control_component.cc#L279-L290

**Comment by daohu527** [comment]
I was wrong before, this is indeed a `list`.
```
  using MessageQueue = std::list<MessagePtr>;
```

I search the method, seems all the modules just used `GetLatestObserved`. Then only one size buffer is enough, if we don't need old messages. 

Messages will put in front of the list, and when the buffer is full, it will pop at the back. So the latest message will always in the front.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
