### ISSUE TITLE
Ask for help with M2 equipment

### ISSUE THREAD

**Issue by yufeilongyuan** [ApolloAuto/apollo#13264]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
When I updated the code to version 6.0.0, I found that the code and configuration of M2 device were deleted. Does that mean I can't use M2? Or, with the integration of the code, the old devices are still supported. I need help. Thank you.

**Comment by lx18233184051** [comment]
what does M2 mean?

**Comment by yufeilongyuan** [comment]
> what does M2 mean?

Positioning hardware devices，Domestic manufacturers, xingwangyuda.

**Comment by yufeilongyuan** [comment]
@lx18233184051 Excuse me, how to solve this problem? thank you

**Comment by storypku** [comment]
@diegohu @jinghaomiao Do you have any ideas about this issue?

**Comment by diegohu** [comment]
Hi @yufeilongyuan , M2 is still supported in Apollo 6.0. If you encountered any issue, please let us know.

**Comment by yufeilongyuan** [comment]
@diegohu I'm glad to hear from you. According to your answer, my understanding is /modules/drivers/gnss/conf/gnss_conf.pb.txt is used by default, right? Is there no need to modify other configurations？
