### ISSUE TITLE
Online Camera-only Perception with Apollo 5.0

### ISSUE THREAD

**Issue by cjdipalma** [ApolloAuto/apollo#13268]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**: I am looking to run the perception module in Dreamview either camera-only or using camera as the main sensor to test vehicle behavior under adversarial attack. I tried changing the main sensor in fusion_component_conf.pb.txt to "front_6mm" but the Perception module stopped working when I changed that. I have also tried setting use_lidar=false in probabilistic_fusion.pt, but the system stopped detecting objects altogether since LiDAR was probably still considered the main sensor. Is there a way to make camera the main sensor in Apollo 5.0 or should I try reverting to a previous version such as Apollo 3.0?

**Comment by jeroldchen** [comment]
The related configs you need are in modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt, i.e.
```
output_final_obstacles : true
output_obstacles_channel_name : "/perception/obstacles"
```
Change the `output_obstacles_channel_name` to `"/apollo/perception/obstacles"` and launch camera-only perception module by running this command `mainboard -d modules/perception/production/dag/dag_streaming_perception_camera.dag` .

**Comment by cjdipalma** [comment]
Thank you for your reply. This worked for me.
