### ISSUE TITLE
possibly a Bug @ post process code of pointpillars

### ISSUE THREAD

**Issue by zhanggefan** [ApolloAuto/apollo#13262]
line137:
```xmax = fmaxf(xmin, offset_corners[i * 2 + 0]); ```
should be: 
```xmax = fmaxf(xmax, offset_corners[i * 2 + 0]); ```

https://github.com/ApolloAuto/apollo/blob/20e5ac08565e9df72bf3a1c8d2714bb9445ecfd8/modules/perception/lidar/lib/detection/lidar_point_pillars/postprocess_cuda.cu#L135-L138

**Comment by storypku** [comment]
Please help with this issue @jeroldchen @xiaoMrzhang , thanks.

**Comment by jeroldchen** [comment]
Thank you for reporting the bug!
