### ISSUE TITLE
some question about vehicle_calibration?

### ISSUE THREAD

**Issue by daohu527** [ApolloAuto/apollo#13278]
## question
1. Why need below logic in `publish_control`, If we need to accelerate first and then decelerate. 
* If the acceleration and deceleration are both greater than 0 then the car will continue to accelerate. 
* If the acceleration is less than 0, then the progress will never stop. 
* If the acceleration is greater than 0 and deceleration is less than 0, It will work.
https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/tools/vehicle_calibration/data_collector.py#L150-L167

2. We set `self.case ='d'` and forgot to set it back to 'a', **so we can't continue input cmd**. I try to improve it in below code.
```
        self.canmsg_received = False
        self.case = 'a'                     // set back to `a` then you can continue the progress

        while self.in_session:
            now = cyber_time.Time.now().to_sec()
            self.publish_control()
            sleep_time = 0.01 - (cyber_time.Time.now().to_sec() - now)
            if sleep_time > 0:
                time.sleep(sleep_time)
```

**Comment by liukr001** [comment]
##加速度是直接从imu定位的channel拿过来的，数值抖动比较大呢，用这个数据是不是误差大呀

**Comment by daohu527** [comment]
Your description may be misleading. The acceleration is set by yourself and sent to the canbus module

**Comment by liukr001** [comment]
> Your description may be misleading. The acceleration is set by yourself and sent to the canbus module

我的意思是，在用这个脚本来做离线标定，这个脚本是发送油门百分比，速度，制动百分比；这个脚本里面订阅了定位信号里面的加速度值，这个加速度值是从IMU里面获取的，会比较抖动吧，不平滑

**Comment by daohu527** [comment]
It was output by below code.
https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/localization/msf/local_integ/localization_integ_impl.cc#L146

which is called `msf` method, I think it should be the filtered acceleration
