### ISSUE TITLE
Extract data from udp message

### ISSUE THREAD

**Issue by BBlumi97** [ApolloAuto/apollo#13276]
I use Apollo in combination with LGSL and want to send message data to a second computer where I want to use the data. After some issues I am now able to send the message via UDP to the other mashine. Now i don't know how i read the UDP Message. when  I use netstat i only get some cryptic results.  Is there a documentation how the UDP message is structured ?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

**Comment by daohu527** [comment]
You should take a look at the serialization and deserialization of protobuf.

Here is an example.
```
cyber\examples\listener.cc
cyber\examples\talker.cc
```

**Comment by ntutangyun** [comment]
you could use the protoc tool to generate the libraries for the language you use, from the .proto files defined in apollo directory.

**Comment by BBlumi97** [comment]
Thanks for your fast help! After reading a bit to about protobuf it got even more complicated for me but maybe you have an idea. On my second machine (the one which reads the message) the data hast to be read on a matlab simulink script running on a real time machine. The interface of the real-time machine only alows me to define the length of the message and the data type of the variables in the udp message (e.g single, double, uint8).  Do you have an idea how I get access to the data on the second machine?

**Comment by daohu527** [comment]
You can use a client on the second machine and deserialization message then send it to simulink. If you can use socket in the second machine why not you can't deserialization the message?

**Comment by BBlumi97** [comment]
The second machine runs only the Matlab Simulink code you can't put something in addtion to that on the machine. My workaround for that would be to send the message to the localhost and send a non serialized message via udp. I also tried to read the message without deserialziation and received this message. Isn't it somehow possible to get the information where in the message which channel is so i can map this in Simulink ?

b'ApolloBridgeHeader\x00\n\xa8\x00\x00\x00\n\x00\x00\x00\x00:\x04\x00\x00\x00:\x00\x00\x00\x00\n\x01\x00\x00\x00:\x08\x00\x00\x00:Chassis\x00\n\x02\x00\x00\x00:\x04\x00\x00\x00:\xc6\x00\x00\x00\n\x03\x00\x00\x00:\x04\x00\x00\x00:\xb5\x00\x00\x00\n\x04\x00\x00\x00:\x04\x00\x00\x00:\x01\x00\x00\x00\n\x05\x00\x00\x00:\x04\x00\x00\x00:\xb5\x00\x00\x00\n\x06\x00\x00\x00:\x04\x00\x00\x00:\x00\x00\x00\x00\n\x07\x00\x00\x00:\x04\x00\x00\x00:\x00\x00\x00\x00\n\x08\x00\x00\x00:\x08\x00\x00\x00:\xb84a0v\xfd\xd7A\n\x18\x01%\xfe\xffGD-\xc4\x14~55\x00\x00\x00\x008\x00E\x00\x00\x00\x00M\x00\x00HB]\x00\x00\x00\x80h\x00\x98\x01\x00\xa8\x01\x01\xb8\x01\x01\xca\x01\x15\t\xb84a0v\xfd\xd7A\x12\x07chassis\x18\xc6\x01\xe2\x01m\t7U\xc4\xd6\x1b\xadB@\x11\x90\xa5n_\xf8|^\xc0\x18\x01` \xdb\x0f(\x010\x028\x10@#H/Q\x00\x00\x00\x00\x00\x80V@Y\x9a\x99\x99\x99\x99\x99\xb9?`\x00h\x00q\x00\x00\x00\x00\xc0,j\xbfy\x00\x00\x00\x00\x00\x80V@\x81\x01\x9a\x99\x99\x99\x99\x99\xb9?\x89\x01\x9a\x99\x99\x99\x99\x99\xb9?\x90\x01\x02\x98\x01\x0f\xa1\x01\x00\x00\x00\x80\x98\xc2\xaf>'

**Comment by daohu527** [comment]
I think you should separate the problem!!!

If you can deserialization an message in host machine, then you send the message to the other. If you have problem in `deserialization an message in host machine` then find why. If you send a "string" to the other and can't read it, Then solve the transmission problem.
```
host machine --------------------------------> the other(simlink)
deserialization message -> string -> socket -> the other
``` 

I am not quite sure what your problem is

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
