### ISSUE TITLE
no such package '@adv_plat//': The repository's path is "/opt/apollo/pkgs/adv_plat/include" (absolute: "/opt/apollo/pkgs/adv_plat/include") but this directory does not exist.

### ISSUE THREAD

**Issue by LeisureLei** [ApolloAuto/apollo#13275]
When I run bash /apollo/apollo.sh build, I get these:

[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2020-12-28-a36d6c5a88
[INFO]     DOCKER_IMG: cyber-x86_64-18.04-20201210_0223
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview: 
[INFO]     USE_GPU: 0  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=cpu
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/... except //modules/perception/... except //modules/planning/open_space/trajectory_smoother:planning_block except //modules/map/pnc_map:cuda_pnc_util except //modules/map/pnc_map:cuda_util_test
(10:34:44) INFO: Invocation ID: 4f147afa-d336-4627-9c4f-bdb6c2a43640
(10:34:44) INFO: Current date is 2021-01-04
(10:34:44) INFO: Repository com_github_google_glog instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:61:9: in initialize_third_party
  /apollo/third_party/glog/workspace.bzl:15:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:44) INFO: Repository com_github_gflags_gflags instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:60:11: in initialize_third_party
  /apollo/third_party/gflags/workspace.bzl:6:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:44) INFO: Repository com_google_googletest instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:62:10: in initialize_third_party
  /apollo/third_party/gtest/workspace.bzl:7:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:45) INFO: Repository eigen instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:56:10: in initialize_third_party
  /apollo/third_party/eigen3/workspace.bzl:11:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:45) INFO: Repository com_google_absl instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:47:9: in initialize_third_party
  /apollo/third_party/absl/workspace.bzl:6:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:45) INFO: Repository com_github_nlohmann_json instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:67:18: in initialize_third_party
  /apollo/third_party/nlohmann_json/workspace.bzl:11:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:45) INFO: Repository civetweb instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:55:13: in initialize_third_party
  /apollo/third_party/civetweb/workspace.bzl:11:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:45) INFO: Repository com_github_jbeder_yaml_cpp instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:91:27: in apollo_repositories
  /apollo/tools/workspace.bzl:81:13: in initialize_third_party
  /apollo/third_party/yaml_cpp/workspace.bzl:11:17: in repo
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(10:34:45) ERROR: /apollo/modules/drivers/camera/BUILD:56:11: //modules/drivers/camera:camera depends on @adv_plat//:adv_plat in repository @adv_plat which failed to fetch. no such package '@adv_plat//': The repository's path is "/opt/apollo/pkgs/adv_plat/include" (absolute: "/opt/apollo/pkgs/adv_plat/include") but this directory does not exist.
(10:34:45) ERROR: Analysis of target '//modules/drivers/camera:camera' failed; build aborted: Analysis failed
(10:34:45) INFO: Elapsed time: 0.497s
(10:34:45) INFO: 0 processes.
(10:34:45) FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @cpplint; fetching
    Fetching @local_config_cc; fetching
    Fetching @local_config_python; fetching
    Fetching ...40135163923dd7d5820f3ee4b306b32/external/cpplint; Extracting /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/cpplint/temp2404883503883570636/1.5.2.tar.gz

How can I fix this error? Before this error, I got "no such package '@opencv//': The repository's path is "/opt/apollo/sysroot/include/opencv4" (absolute: "/opt/apollo/sysroot/include/opencv4") but this directory does not exist. "

**Comment by storypku** [comment]
```
[WARNING] nvidia-smi not found. CPU will be used.
```

If you have GPU available, please checkout why `nvidia-smi` is missing from the container.
If not, or you want to perform a CPU build, run `rm -rf .cache/{bazel,build,repos}` and try again.

**Comment by storypku** [comment]
Closed as inactive for more than 1 month(s).
