### ISSUE TITLE
Recorder files for cyber_recorder

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13287]
### System information

- **OS Platform and DistributionLinux Ubuntu 18.04
- **Apollo installed from source
- **Apollo version 5

Hi, I am looking for .recorder files to play in cyber_recorder. I only have one demo file which is lacking all the cyber topics I am trying visualize, especially the camera related topics. Can you please point me to any location where I can download .record files for my analysis and debugging?

thank you

**Comment by Yimags** [comment]
If you did not specify the file path, the file will be in the root directory of apollo, and the default name is "%Y%m%d%H%M%S.record".

**Comment by ntutangyun** [comment]
you could also use simulaltor such as LGSVL to make your own recording, including lidar and camera.

**Comment by jpcloud1577** [comment]
> If you did not specify the file path, the file will be in the root directory of apollo, and the default name is "%Y%m%d%H%M%S.record".

I do not see any record files in apollo. I checked both within and outside of docker. Can you please specify the exact path? Is there a repo of previous records that I can download?

**Comment by Yimags** [comment]
It should locate initially directly under apollo/, with a format like xxxxx(time you record).record.00000, if you didn't modify the predefined save path.

**Comment by beanmoon** [comment]
> It should locate initially directly under apollo/, with a format like xxxxx(time you record).record.00000, if you didn't modify the predefined save path.

Is there any download urls from which I can fetch record files with different topics, or I have to record data by myself?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
