### ISSUE TITLE
What is the default control algorithm?

### ISSUE THREAD

**Issue by MuhammadUbuntu** [ApolloAuto/apollo#13283]
Since Apollo uses three kinds of controller:
1- Longitudinal Control: PID
2- Lateral Control: LQR
3- MPC for longitudinal and lateral

I have some questions:
1- Do the controllers PID and LQR work together and in separate mode with MPC?
2- If the answer to the first question is yes then how we can know or select the running controller i.e. "PID with LQR" or "MPC"?

**Comment by daohu527** [comment]
1. Yes, the default control mode is set by "modules/control/conf/control_conf.pb.txt"
```
active_controllers: LAT_CONTROLLER
active_controllers: LON_CONTROLLER
``` 
2. You can select control mode by different dag files
```
mpc_module.dag       -> mpc
control.dag                -> pid+lqr
lateral_longitudinal_module.dag  -> pid+lqr
```

**Comment by MuhammadUbuntu** [comment]
@daohu527 In file control_conf.pb.txt we can configure the controllers Lat,Lon , and MPC and there is the expression:
active_controllers: LAT_CONTROLLER
active_controllers: LON_CONTROLLER

But for me it is still not clear which is the default running controller. If that means the default controllers are PID and LQR for LON and LAT, then how we can set the controller to be MPC.

Actually I don't understand how we can select the control mode as you mentioned in point 2.
Thank in advance.

**Comment by daohu527** [comment]
> If that means the default controllers are PID and LQR for LON and LAT

yes

> I don't understand how we can select the control mode as you mentioned in point 2  

With dag you can choose which module to start and which configuration file to read, if you choose `mpc_module.dag` it will read the `mpc_controller_conf.pb.txt`, (you can also find `lat_controller_conf` and `lon_controller_conf` in it, I think it's an error when generating control parameters). The default config is `control.dag`

**Comment by MuhammadUbuntu** [comment]
@daohu527 where i can choose `mpc_module.dag`? I mean in which file I can mention this choice.
The default `control.dag` leads to `control.conf `which leads to` control_conf.pb.txt` in which there are the expressions 
active_controllers: LAT_CONTROLLER
active_controllers: LON_CONTROLLER
and this means the control mode is pid+lqr. Anyway here I don't know why the expression `active_controllers` is repeated twice.

OK, now in written script, how i can set the default control to be MPC? I know that i have to choose mpc_module.dag but the question is Where I have to mention? In Which file and in Which line?

My goal is to debug the control module with MPC control algorithm.

**Comment by daohu527** [comment]
You can use `cyber_launch start modules/control/launch/control_mpc_control.launch` to start mpc module.

Realizing that you are not familiar with these commands, I suggest you first learn about the cyber. Because you may encounter a series of problems such as starting modules, opening logs, receiving topics, etc.

**Comment by MuhammadUbuntu** [comment]
Thank you

**Comment by AlexandrZabolotny** [comment]
Hello colleagues!
I am trying to tune a control module on a real car.

I will try to run both MPC and LQR+PID

I get the following result
1. In the case of LQR+PID
Good speed control (longitudinal control), but poor lateral control. When cornering, it does not follow the desired trajectory and therefore dynamically turns the steering wheel.

2.in case of MPC
It repeats the trajectory well. Smoothly turns the steering wheel. Provides a comfortable ride. But poor speed control. A very large longitudinal error, also the car does not stop at the required point.

I want to use MPC. So I have questions.
1. Is it possible to set up longitudinal control for MPC? If so, how?
2. Is it possible to use MPC for lateral control, but for longitudinal - PID ??

**Comment by AlexandrZabolotny** [comment]
> @AlexandrZabolotny did you figure out how to use MPC only for lateral control? I am trying to do the same. Let me know

Unfortunately no.
But I understood how MPS works. And now I managed to set this regulator correctly for my car. In my opinion, both lateral and longitudinal control in the MPS work better
