### ISSUE TITLE
Get stuck in terminating listener.py

### ISSUE THREAD

**Issue by Yimags** [ApolloAuto/apollo#13289]
Hello all,

I modified the listener.py a bit so that I could change the pace of read message from bridge. I made the changes as follows but it stucks permanently when I press Ctrl+C to terminate. Could you help me find out the reason for this? Thx in advance!
```
def callback(data):
    print("=" * 80)
    print("py:callback msg->:")
    print(data)
    print("=" * 80)
    time.sleep(1.5)
```
![error_stuck](https://user-images.githubusercontent.com/64920943/103834831-d5ee4700-5084-11eb-876b-c1eb530d871a.png)

**Comment by ntutangyun** [comment]
never tested, but you may try to add a handler for signal "SIGINT". see if it helps.

**Comment by Yimags** [comment]
Hello! Thx for the information. I am also wondering if it is possible to trigger interruption with events instead of keyboard input. For example, interrupting `listener.py` when no data transferred in bridge (simulation stops) ?
