### ISSUE TITLE
Start autonomous driving using commands

### ISSUE THREAD

**Issue by EmptySheet** [ApolloAuto/apollo#13291]
I am now working on building an user interface for simplifying the operation of rtk playing. My question is how do I know which commands i need to execute after I successfully replaying the recorded trajectory in order to ender autonomous driving mode and start moving my vehicle? Thanks.

**Comment by daohu527** [comment]
## How to
You can refer to the following code.
https://github.com/ApolloAuto/apollo/blob/3560ac35143000e8f7911564bceedcda083fe72d/modules/dreamview/backend/hmi/hmi_worker.cc#L332-L333

## Principle
Send PAD msg to the chassis to change the vehicle's state

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
