### ISSUE TITLE
What do messages Pad and Monitor contain for control module?

### ISSUE THREAD

**Issue by MuhammadUbuntu** [ApolloAuto/apollo#13297]
It is clear that control module uses information from `planning`, `localization` and `canbus` modules to compute the control command but i need to know what is the information that functions `onPad` and `onMonitor` send to control module?

**Comment by daohu527** [comment]
The `OnPad` and `OnMonitor` are routine interactions with the PAD-based human interface and simulations. 

you can ref [link](https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/docs/specs/Apollo_3.5_Software_Architecture.md)
