### ISSUE TITLE
What is the main source file in control module?

### ISSUE THREAD

**Issue by MuhammadUbuntu** [ApolloAuto/apollo#13292]
I need to know when the control module works, what is the first source file that is called?
is it `control_component.cc` or `control_component_test.cc` or another file? and what is the difference between these two files?

**Comment by jpcloud1577** [comment]
control_component_test.cc is the test file to test control_component.cc. test file is used for only unit level testing (gtest). 
If you are specifically looking for which one starts first(?), its the component file and then the test file.
