### ISSUE TITLE
Hints on creating a custom planning behaviour

### ISSUE THREAD

**Issue by Alejandro-A-R** [ApolloAuto/apollo#13306]
I am trying to build a custom planning behaviour which I pretend to use in a merging.

I would like to know several points if possible:

**1.** Which exact scripts do I need to change/create in order to accomplish this task?
**2.** Is there any example or script that I can use as a base? 
**3.** From what I have seen, I think what I am trying to do is similar to the scenarios located in apollo/modules/planning/scenarios, in which there is a script for the scenario that manages the several stages located in other scripts. Please, correct me if I am wrong.

Note: I am using apollo with LGSVL, either 5.0 or master (6.0) seem to work fine with it, so my custom planning behaviour could be built in any of these two releases of apollo.

I know maybe this involves a lot of steps and information, but I have already tried my best to find a way of doing this, though the documentation has not been useful, and trying to figure out something just by reading scripts has been impossible for me.
Considering this, any help provided will be very appreciated, so thanks in advance.

**Comment by daohu527** [comment]
This is some related work, you can refer to https://github.com/ApolloAuto/apollo/issues/12733
