### ISSUE TITLE
Sim_control not working 

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#13307]
Hello team, sorry to bother you. I have encounterd a problem and I could really use your help. Thanks a lot!

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04 LTS
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: master branch

### Steps to reproduce the issue:
- building Apollo, enable DreamView
- start DreamView, select cars, modes, map
- enable sim_control
- send routing request

After I send the routing request, the car is freezing and nothing happens. The console shows that Planning triggers safe mode. Here is the screenshot:
![Screenshot from 2021-01-12 19-12-31](https://user-images.githubusercontent.com/42797233/104307442-2ee92f80-550a-11eb-9322-5f88359e97e4.png)

I checked the cyber_monitor, here is the info:
![Screenshot from 2021-01-12 19-07-44](https://user-images.githubusercontent.com/42797233/104307489-3dcfe200-550a-11eb-948f-3d7648d26986.png)

I also looked into the log, and here is the DreamView Log:
![Screenshot from 2021-01-12 19-23-39](https://user-images.githubusercontent.com/42797233/104308490-b8e5c800-550b-11eb-9825-9166cc4431ca.png)
![Screenshot from 2021-01-12 19-24-22](https://user-images.githubusercontent.com/42797233/104308572-db77e100-550b-11eb-94fd-1197a800d23a.png)
![Screenshot from 2021-01-12 19-24-35](https://user-images.githubusercontent.com/42797233/104308577-dca90e00-550b-11eb-813b-785b3279c66e.png)
![Screenshot from 2021-01-12 19-24-45](https://user-images.githubusercontent.com/42797233/104308579-dd41a480-550b-11eb-87b2-361a7acf8c24.png)

### Supporting materials (screenshots, command lines, code/script snippets):
What should I do? DO I have to reinstall Apollo?

* I noticed the planning module not work working properly, which outputs message:
`F0112 19:41:34.817965 483466 planning_component.cc:50] Check failed: ComponentBase::GetProtoConfig(&config_) failed to load planning config file /apollo/modules/planning/conf/planning_config.pb.txt`

**Comment by GabrielZZZ** [comment]
I also have a question: do I have to use the cyber_recorder to replay the bag before using sim_control?

**Comment by daohu527** [comment]
delete the file `/apollo/modules/planning/conf/planning_config.pb.txt` and try again. 

There are 2 ways to initialize sim_control.
1. The initial position of the vehicle without any operation
2. Use "localization_reader_" to get an initial point

**Comment by GabrielZZZ** [comment]
Thank you @daohu527 . I have solved the problem by reinstalling the Apollo master branch. I guess it is because I have made some modification to the code before that I don't remember now. 

Although now the planning module works fine, when I enable the sim_control and corresponding modules, then giving the routing command, the route can be formed but the car does not move at all. Is that because I haven't played the record file at the same time? Do I have to play a record file when using sim_control?
![Screenshot from 2021-01-13 11-01-48](https://user-images.githubusercontent.com/42797233/104455632-8c50af80-55e2-11eb-9ca9-8a3a7ec41ffe.png)

**Comment by daohu527** [comment]
Seems PerceptionObstacle topic is missing? You need to check the log and observe

**Comment by GabrielZZZ** [comment]
I have not played any record data or add obstacles, so there are no obstacles. I just click sim_control and enable planning, prediction, perception and routing modules. Is that the reason?

**Comment by daohu527** [comment]
you should just enable routing, planning and sim_control. 

sim_control will publish the mock PerceptionObstacle topic.

**Comment by GabrielZZZ** [comment]
Thank you for your reply. I have tried your way, and here is the output (the car still not move):
![Screenshot from 2021-01-13 22-00-03](https://user-images.githubusercontent.com/42797233/104461965-f66d5280-55ea-11eb-918f-d0abd36ab51d.png)
And here are the logs of planning module, and routing module:
![Screenshot from 2021-01-13 21-59-54](https://user-images.githubusercontent.com/42797233/104462077-11d85d80-55eb-11eb-91f1-1bd8ea38d089.png)
![Screenshot from 2021-01-13 22-01-02](https://user-images.githubusercontent.com/42797233/104462032-05540500-55eb-11eb-89bf-12f3425d1450.png)

Here is the log of mainboard:
![Screenshot from 2021-01-13 22-01-42](https://user-images.githubusercontent.com/42797233/104462037-06853200-55eb-11eb-8239-29b11bce2507.png)

Here is the log of DreamView:
![Screenshot from 2021-01-13 22-03-20](https://user-images.githubusercontent.com/42797233/104462187-32a0b300-55eb-11eb-98fb-c63ce66f078a.png)

Can you take a look for me? Really thanks!

**Comment by GabrielZZZ** [comment]
when I play the record file (e.g. Demo_3.5.record) , the planning module works. but after playing the record file, the planning module does not work and say no message comes, even though I have give a route

**Comment by daohu527** [comment]
You error message is "Failed to create reference line from routing". If the code has not been modified, I think there is a problem with the map or routing message sent

Planning module's input are localization, perception, and chassis. it's output is a "ADC Trajectory". sim_control will provide the above information to the planning module. 

You cannot enable sim_control and play record at the same time, I suggest you find the simplest map first like **single lane map**

**Comment by GabrielZZZ** [comment]
Thank you for your answer. Do you mean using the file `map_gen_sin_lane.py ` under `modules/tools/map_gen`?

**Comment by daohu527** [comment]
You can download map from https://content.lgsvlsimulator.com/maps/singlelaneroad/

**Comment by GabrielZZZ** [comment]
Hi, I have tried the single lane road. The car does not move and the planning module says: "Failed to update reference line after rerouting". the log of mainboard sais "detect froward jumps in time"
![Screenshot from 2021-01-14 20-38-20](https://user-images.githubusercontent.com/42797233/104592233-d56b3700-56a8-11eb-8381-17e63373a907.png)
![Screenshot from 2021-01-14 20-40-34](https://user-images.githubusercontent.com/42797233/104592235-d69c6400-56a8-11eb-94fc-03f1d0abc1b8.png)

**Comment by Yimags** [comment]
@GabrielZZZ Hello, you could use r6.0.0 instead of master branch. It works for me.

**Comment by trieuthachvu** [comment]
@GabrielZZZ 
 Is the master branch working now?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
