### ISSUE TITLE
how to load map by commands instead of select map by Dreamview?

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#13309]
My requirement  is that I don't want to select the map by drop-down list in the Dreamview.
![image](https://user-images.githubusercontent.com/24958250/104329421-d6288f80-5527-11eb-8289-105ca3c17e88.png)

1.  so do we support loading the map by some commands?  and the steps?
2. Anyone know the interface code of map drop-down list of the Dreamview?

Thank you in advance!!!

**Comment by ntutangyun** [comment]
i think when you select the map, dreamview will send a request to backend server. 

you could check out dreamview's source code and see how to forge the request

**Comment by daohu527** [comment]
As @ntutangyun said, you can ref to below code.
https://github.com/ApolloAuto/apollo/blob/3560ac35143000e8f7911564bceedcda083fe72d/modules/dreamview/backend/hmi/hmi_worker.cc#L476-L495

The main point is `SetGlobalFlag("map_dir", *map_dir, &FLAGS_map_dir);`, it change the `FLAGS_map_dir` and other modules will read it. which means if you start a module, **if you want to change the map, you should restart it**.

**Comment by lj0919** [comment]
Hi @WentaoWang-SH , This issue has gotten the correct answer, I am going to close this issue now.
If you have other questions, please feel free to open another issue.
Thanks for using Apollo.
