### ISSUE TITLE
Failure in running Module 'Planning'

### ISSUE THREAD

**Issue by Yimags** [ApolloAuto/apollo#13300]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6
- **Output of `apollo.sh config` if on `master` branch**:yes

### Steps to reproduce the issue:
- **Run apollo with lgsvl in modular testing follow the instructions**
- **Turn on the planning moduley**
- **After assigning ending point for routing, planning fails immediately, delay start to increase**

### Supporting materials (screenshots, command lines, code/script snippets):
- **`cyber_monitor` shows message but never get updated**
- **Log and cyber_monitor information shows as follows**
![errer_planning](https://user-images.githubusercontent.com/64920943/104139063-1e6d7380-53a9-11eb-8da1-8218f1682731.png)
![error_pl](https://user-images.githubusercontent.com/64920943/104138996-8a031100-53a8-11eb-8324-cb49cc806485.png)
![error_plaa](https://user-images.githubusercontent.com/64920943/104139165-bc613e00-53a9-11eb-9df1-df11204f1cfd.png)

![error_pla](https://user-images.githubusercontent.com/64920943/104138994-87082080-53a8-11eb-974c-fe71fd7737e2.png)

**Comment by daohu527** [comment]
The reason was show in "apollo/planning" topic, which is `Failed to create reference line`

**Comment by ntutangyun** [comment]
restart planning module and see if works

**Comment by Yimags** [comment]
I reset it, the problem remains.

I rebuilt Apollo from scratch for several times and didn't change any code. I am wondering what causes this problem and how I could fix this?

**Comment by daohu527** [comment]
You can check the plan log to see if there are any error messages.

**Comment by Yimags** [comment]
You could see it in the last picture I provided. It shows `routing not ready` etc..
But I check in cyber_monitor that routing works well.

**Comment by ntutangyun** [comment]
you could try to submit route request again.

**Comment by daohu527** [comment]
According to your log, you are first missing the routing message, and the check is failed.
```c++
  if (!CheckInput()) {
    AERROR << "Input check failed";
    return false;
  }
```
But after that, I can't see the log, and I don't know if the log is incomplete or just not printed. So you need to analyze or supplement logs

**Comment by GabrielZZZ** [comment]
I have also encountered the same issue.

**Comment by GabrielZZZ** [comment]
@Yimags Hello. Have you solved the problem?

**Comment by Yimags** [comment]
@daohu527  Here is the complete log for `planning`. I have checked the `routing` module in monitor and it seems to me that it works well.
![error_planning_info](https://user-images.githubusercontent.com/64920943/104652023-c7251700-56b8-11eb-953a-784f6994ddd6.png)
![error_routing](https://user-images.githubusercontent.com/64920943/104652119-ecb22080-56b8-11eb-8419-3945b160d6fe.png)

**Comment by Yimags** [comment]
> @Yimags Hello. Have you solved the problem?

Sorry, not yet.

**Comment by daohu527** [comment]
Pls ref to #12604

**Comment by Yimags** [comment]
> Pls ref to #12604

Hello, thanks for the hint. I think this solution is equivalent to resetting module manually. 
And after trying both out, the problem still remains.

**Comment by Yimags** [comment]
I checkout the v6.0 version and it works well. So I guess there is something wrong in planning module of master branch. Please check it.
