### ISSUE TITLE
apollo5.5和apollo6.0是否支持与LGSVL的联合仿真？

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13304]
已经按官方教程调试完了，接下来准备与LGSVL进行联合仿真，用LGSVL绘制高精地图。请问apollo5.5是否支持？

**Comment by peak9527** [comment]
5.5和6.0都支持的

**Comment by hxj0316** [comment]
都支持的吗？那么请问对电脑硬件的要求是什么呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "peak9527"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上9:34
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "胡新杰"<305625579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] apollo5.5和apollo6.0是否支持与LGSVL的联合仿真？ (#13304)





 
5.5和6.0都支持的

**Comment by peak9527** [comment]
5.5和6.0都支持的，你gps也配置调通了吗，我们用的是星网宇达的XW-GI5651，现在还有点问题，差分信号已经出来了，不过只输出的信息格式是GPFPD，请问这样可以吗，是apollo需要的格式吗

**Comment by hxj0316** [comment]
你们是购买的apollo的套件吗？
我们是够买的它的套件用作研究。我们直接是买的千寻的账号提供GPS信息哎






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "peak9527"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上9:41
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "胡新杰"<305625579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] apollo5.5和apollo6.0是否支持与LGSVL的联合仿真？ (#13304)





 
5.5和6.0都支持的，你gps也配置调通了吗，我们用的是星网宇达的XW-GI5651，现在还有点问题，差分信号已经出来了，不过只输出的信息格式是GPFPD，请问这样可以吗，是apollo需要的格式吗

**Comment by peak9527** [comment]
我们的不是买的套件，是用的自己的车
差分也是用千寻账号提供的GPS信息，com1给差分盒子提供输入，现在com0已经有差分信息输出，不过我们只放开了GPFPD消息格式输出，不知你们输出的是什么消息格式呢

**Comment by hxj0316** [comment]
这个我倒是没注意哎，我过几天看一下






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "peak9527"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上10:23
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "胡新杰"<305625579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] apollo5.5和apollo6.0是否支持与LGSVL的联合仿真？ (#13304)





 
我们的不是买的套件，是用的自己的车
 差分也是用千寻账号提供的GPS信息，com1给差分盒子提供输入，现在com0已经有差分信息输出，不过我们只放开了GPFPD消息格式输出，不知你们输出的是什么消息格式呢

**Comment by hxj0316** [comment]
你们在改乘用车了吗？lgsvl和apollo5.5可以联合仿真对吧？对电脑配置要求是什么呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "peak9527"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上10:23
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "胡新杰"<305625579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] apollo5.5和apollo6.0是否支持与LGSVL的联合仿真？ (#13304)





 
我们的不是买的套件，是用的自己的车
 差分也是用千寻账号提供的GPS信息，com1给差分盒子提供输入，现在com0已经有差分信息输出，不过我们只放开了GPFPD消息格式输出，不知你们输出的是什么消息格式呢

**Comment by peak9527** [comment]
可以的，

**Comment by peak9527** [comment]
可以的

**Comment by peak9527** [comment]
> 你们在改乘用车了吗？lgsvl和apollo5.5可以联合仿真对吧？对电脑配置要求是什么呢？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "peak9527"<notifications@github.com&gt;; 发送时间: 2021年1月12日(星期二) 晚上10:23 收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 抄送: "胡新杰"<305625579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [ApolloAuto/apollo] apollo5.5和apollo6.0是否支持与LGSVL的联合仿真？ (#13304) 我们的不是买的套件，是用的自己的车 差分也是用千寻账号提供的GPS信息，com1给差分盒子提供输入，现在com0已经有差分信息输出，不过我们只放开了GPFPD消息格式输出，不知你们输出的是什么消息格式呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe

可以的，

Recommended system:

4 GHz Quad Core CPU
Nvidia GTX 1080, 8GB GPU memory
Windows 10 64 Bit
可以参考其github介绍  https://github.com/lgsvl/simulator

**Comment by peak9527** [comment]
可以的，我的意思是可以联合仿真，至于绘制高精地图，没试过


**Recommended system:**

4 GHz Quad Core CPU
Nvidia GTX 1080, 8GB GPU memory
Windows 10 64 Bit
**_可以参考其github介绍 https://github.com/lgsvl/simulator_**

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
