### ISSUE TITLE
LGSVL

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13311]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by hxj0316** [comment]
打算用LGSVL与apollo做联合仿真并用LGSVL来绘制apollo支持的高精地图，请问大家有知道电脑配置需求吗？官网的配置说是NVIDIA 1080的显卡，但是这款显卡已经停售了，是只有这款显卡可以还是说配置比这个高就可以?谢谢大家

**Comment by daohu527** [comment]
You means which side, apollo or lgsvl?

**Comment by hxj0316** [comment]
你好，我是说lgsvl的配置要求

**Comment by daohu527** [comment]
Since lgsvl uses `Unity` engine, I think other types of graphics cards are also feasible, I suggest you go to lgsvl to ask some advice

**Comment by storypku** [comment]
> 这个高就可以?谢谢大家

Apollo  can support  GPU cards with compute capability ranging from 5.0 to 8.6 now. I am now running Apollo on an RTX 3090 machine.

**Comment by hxj0316** [comment]
> > 这个高就可以？谢谢大家
> 
> Apollo现在可以支持GPU，其计算能力范围从5.0到8.6。我现在在RTX 3090机器上运行Apollo。

**Comment by hxj0316** [comment]
您好，我的意思是lgsvl支持比1080高的显卡配置吗？官网说的是1080






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu Jiaming"<notifications@github.com&gt;; 
发送时间: 2021年1月14日(星期四) 下午3:18
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "胡新杰"<305625579@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] LGSVL (#13311)





  
这个高就可以?谢谢大家
  
Apollo  can support  GPU cards with compute capability ranging from 5.0 to 8.6 now. I am now running Apollo on an RTX 3090 machine.

**Comment by ntutangyun** [comment]
> 您好，我的意思是lgsvl支持比1080高的显卡配置吗？官网说的是1080

Maybe you could ask this in LGSVL repo.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
