### ISSUE TITLE
Create a thread in a component. Is it possible?

### ISSUE THREAD

**Issue by Turi30** [ApolloAuto/apollo#13318]
I want create a thread inside a component but this not works. There is a way to create a thread to execute a function inside a component. For example in the class definition I put 
```
void func_thread();
std::thread my_thread;
```
and then in the Init function of the component I make:
```
my_thread = std::thread(&component::func_thread, this);
```

Why this not work? I have to create this thread with the CreateTask function?

**Comment by daohu527** [comment]
You can use std::thread to create a new thread. What problem did you encounter?

**Comment by Turi30** [comment]
Now it works, but for example if I have a Writer initialized in the class and then in the func_thread I make writer->write(), why the message is not published?

**Comment by daohu527** [comment]
I'm not sure there is a problem with the way you use. Can you send messages through member functions?

**Comment by Turi30** [comment]
> I'm not sure there is a problem with the way you use. Can you send messages through member functions?

I tried to make a member function in which send the message and call this function in the func_thread, but this not work.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
