### ISSUE TITLE
[lidar-perception] obstacle shape tracking under lidar blindspot

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#13310]
[[Video](https://entuedu-my.sharepoint.com/:v:/g/personal/yun005_e_ntu_edu_sg/EcI_Th1rd6pNv1N0xk1bwbABtEF4vZeyF1WB1jyNIbkthg?e=hCrs6V)]
[[Recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/ERhz287UwaZLgn7ZNKfH05kBgdLSm-a3y6mpWGEbjlneEQ?e=l8xNhF)]

Note that the cubes surrounding the obstacles are ground truth, and they are only displayed in Dreamview for debugging purpose and not interfering with the prediction and planning modules.

The video is paused manually when Apollo's passing NPC for easier examination, not due to runtime lagging. 

**System**
* Simulator: LGSVL 2020.06
* Apollo version:  pre6
* Lidar Perception Module: CNN Segmentation + recognition + fusion

**Issue Description**
**The shape of the obstacle shape is not tracked by the lidar perception.** 

In the video, Apollo needs to change to the left lane with an obstacle (NPC) in front. 

When Apollo is right behind NPC, it could see the back of the NPC and the rough width of the NPC.

But when Apollo is very close to the NPC and part of NPC enters Apollo's lidar blind spot, 
the shape of the NPC gets cuts off.

And as a result, Apollo believes there is a sufficient gap between the NPC and itself while passing the NPC, while the truth is it already scratched the left side of the NPC, based on the ground truth data. 

So, if Apollo could keep track of the shape of the NPC, especially the width, it might leave more distance while passing the NPC. 

I'm not sure how to classify this kind of issue, but I believe tracking the NPC shape is also a necessary feature for safety purposes.

**Comment by hxj0316** [comment]
您好，请问你们使用LGSVL模拟器的电脑配置可以发一下吗？apollo5.5和6.0支持与LGSVL进行联合仿真吗？

**Comment by ntutangyun** [comment]
应该支持。

cpu i76850k
gpu nvidia 1080ti
ram 64GB

这个电脑跑激光雷达感知会有点卡……

**Comment by hxj0316** [comment]
你们用的是apollo6.0吗？

**Comment by ntutangyun** [comment]
pre6

**Comment by hxj0316** [comment]
好的，谢谢
你们是购买的apollo的套件吗？我们现在是购买了他们的套件然后跑完了他们官网的教程。准备在买一些上层传感器进行实车的改装，方便的话是不是可以交流一下？我刚开始接触挺多不懂得。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tang Yun"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 下午4:59
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "胡新杰"<305625579@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] [lidar-perception] obstacle shape tracking under lidar blindspot (#13310)





 
pre6

**Comment by jeroldchen** [comment]
@ntutangyun Great founding! Thank you for your advice. We will discuss about the problem and work on designing a solution. A possible solution is to predict a stable cuboid shape for an obstacle by learning class-specific domain knowledge and, by your advice, utilizing previous tracked obstacle's information.
