### ISSUE TITLE
New Module - Topics not being published and VS Code debugging

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13319]
### System information

- **OS Platform and Distribution  Linux Ubuntu 18.04
- **Apollo installed from source 
- **Apollo version 5.0,

I have created a new module under apollo/modules. It has source/header files of the component, dag, proto, config and other supporting files. My module just subscribes to apollo/control topic and publishes throttle value from the topic on apollo/intelicontrol (just the same value). I am able to build the project successfully, but the topic in module is not publishing anything when I look at it in the cyber_monitor. I can see the topic, but its not getting updated . I see that apollo/control is being updated ( I am running a simulation on LGSVL). All I am doing is subscribing to this topic and publishing. 

Here is the snapshot of the cyber_monitor. 
![image](https://user-images.githubusercontent.com/66703107/104665433-44dc2900-569f-11eb-90ef-2ec38a069fb8.png)

Please let me know how to solve this issue

I also want to debug my newly created module in VS code, but I am not able to launch this. Are there anything additional I have to take care of (I am able to debug existing modules like control, camera etc.,)

**Comment by ntutangyun** [comment]
maybe you can check if your module is getting control inputs?

**Comment by jpcloud1577** [comment]
Thanks, but how can I check that? I cant go into VS code debug nor I can see it in cyber_monitor

**Comment by jpcloud1577** [comment]
Are there any other steps I should follow to ensure
1. topics from my module are published/subscibed
2. I can debug my module in vs code using tasks and launch.json files?

**Comment by ntutangyun** [comment]
> Thanks, but how can I check that? I cant go into VS code debug nor I can see it in cyber_monitor

you could do some printing using AERROR util in the Proc() function and see if you have any messages printed
