### ISSUE TITLE
How to enable new module 

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13327]
- **OS Platform and Distribution Linux Ubuntu 18.04
- **Apollo installed from source
- **Apollo version 5.0

I have created a new module alongside standard modules of Apollo. I would like to debug it, but not sure how to enable this module. I would do this from dreamview interface thru module controller tab, but they only have standard modules. Is there anyway to enable a new module/ start the process id manually?
Would be great to know how I can add this new module into dreamview interface as well

thank you

**Comment by daohu527** [comment]
## start module
you should add launch file and dag file, and then use cyber_launch to start the module like below.
```
cyber_launch start modules/control/launch/control.launch
```

#### principle
cyber dynamic load the shared library into memory and then call the `Init` function, after that it will do the `proc` process.

## dreamview
If you want to add the modules in dreamview, you can take an example in `modules\dreamview\conf\hmi_modes`. Add the module config like below
```
cyber_modules {
  key: "YourModule"
  value: {
    dag_files: "/apollo/modules/YourModule/dag/YourModule.dag"
  }
}
```

**Comment by jpcloud1577** [comment]
Thank you. When I run cyber_launch, I am getting this error message

[cyber_launch_17176] INFO Launch file [/apollo/modules/inteli/launch/inteli.launch]
[cyber_launch_17176] INFO ========================================================================================================================
[cyber_launch_17176] INFO Load module [inteli] library: [inteli] [CYBER_DEFAULT] conf: [/apollo/modules/inteli/dag/inteli.dag] exception_handler: []
[cyber_launch_17176] INFO Start process [inteli] successfully. pid: 17184
[cyber_launch_17176] INFO ------------------------------------------------------------------------------------------------------------------------
[inteli ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[inteli ]  I0115 22:33:53.608177 17184 module_argument.cc:81] [] command: mainboard -d /apollo/modules/inteli/dag/inteli.dag -p inteli -s CYBER_DEFAULT 
[inteli ]  I0115 22:33:53.609423 17184 global_data.cc:150] [] host ip: 192.168.1.134
[inteli ]  I0115 22:33:53.610648 17184 module_argument.cc:57] [] binary_name_ is mainboard, process_group_ is inteli, has 1 dag conf
[inteli ]  I0115 22:33:53.610937 17184 module_argument.cc:60] [] dag_conf: /apollo/modules/inteli/dag/inteli.dag
[inteli ]  [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:287] Error parsing text-format apollo.cyber.proto.DagConfig: 7:12: Expected identifier, got: /
[inteli ]  E0115 22:33:53.613616 17184 file.cc:81] [mainboard] Failed to parse file /apollo/modules/inteli/dag/inteli.dag as text proto.
[inteli ]  E0115 22:33:53.614065 17184 file.cc:103] [mainboard] Failed to parse file /apollo/modules/inteli/dag/inteli.dag as binary proto.
[inteli ]  E0115 22:33:53.614403 17184 module_controller.cc:111] [mainboard] Get proto failed, file: /apollo/modules/inteli/dag/inteli.dag
[inteli ]  E0115 22:33:53.614677 17184 module_controller.cc:59] [mainboard] Failed to load module: /apollo/modules/inteli/dag/inteli.dag
[inteli ]  E0115 22:33:53.614940 17184 mainboard.cc:43] [mainboard] module start error.
[inteli ]  Could not create logging file: Permission denied
[inteli ]  COULD NOT CREATE A LOGGINGFILE 20210115-223353.17184!
[cyber_launch_17176] ERROR Process [inteli] has finished. [pid 17184, cmd mainboard -d /apollo/modules/inteli/dag/inteli.dag -p inteli -s CYBER_DEFAULT].
[cyber_launch_17176] INFO All processes has died.
[cyber_launch_17176] INFO Cyber exit.
[cyber_launch_17176] INFO All processes have been stopped.

the content of my launch file is 

`<cyber>
    <module>
        <name>inteli</name>
        <dag_conf>/apollo/modules/inteli/dag/inteli.dag</dag_conf>
        <process_name>inteli</process_name>
    </module>
</cyber>`

and dag file is 

`module_config {
    module_library : "/apollo/bazel-bin/modules/inteli/libinteli_component.so"
    timer_components {
        class_name : "InteliComponent"
        config {
            name: "inteli"
           // flag_file_path: "/apollo/modules/inteli/conf/inteli.conf"
            interval: 10
      }
   }
}`

I am not sure why I am not able to launch. Please let me know

**Comment by daohu527** [comment]
Pls ref to `modules\control\dag\control.dag`

I think you may encounter some formatting errors.

**Comment by jpcloud1577** [comment]
I corrected for the confi_file path and this is what I am getting

[cyber_launch_20992] ERROR Process [inteli] has finished. [pid 21000, cmd mainboard -d /apollo/modules/inteli/dag/inteli.dag -p inteli -s CYBER_DEFAULT].

**Comment by daohu527** [comment]
Do you have coredump or error message in log?

**Comment by MuhammadUbuntu** [comment]
@daohu527  Please note that, @jpcloud1577 asked about adding new module (in general) and when he indicated to the module controller, that doesn't mean control component (or control module) but that means the module controller in dreamview that includes all modules and not only control module.

**Comment by daohu527** [comment]
Yes, am I missing something? I explained both methods before

**Comment by jpcloud1577** [comment]
@daohu527, I do not see any file under data/core and data/log has only old files from a week back for some reason. Is this a problem? Please suggest

**Comment by jpcloud1577** [comment]
@daohu527, I added following to mkz_close_loop.pb.txt under modules\dreamview\conf\hmi_modes


cyber_modules {
  key: "Inteli"
  value: {
    dag_files: "/apollo/modules/inteli/dag/inteli.dag"
    dag_files: "/apollo/modules/control/dag/control.dag"
  }
}

rebuilt it. But I dont see Inteli as a module in Module controller page of dreamview. Please let me know what could be the issue

**Comment by daohu527** [comment]
You should check like below.
1. `class ControlComponent final : public apollo::cyber::TimerComponent`
2. `CYBER_REGISTER_COMPONENT(ControlComponent)`


## dreamview
If you need a separate button, you should add a separate module
```
cyber_modules {
  key: "Intel"
  value: {
    dag_files: "/apollo/modules/control/dag/Intel.dag"
  }
}
```
