### ISSUE TITLE
Changing Dreamview's Port Number

### ISSUE THREAD

**Issue by EricWu416** [ApolloAuto/apollo#13326]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

Is there a way to change Dreamview's port number in Apollo 6.0? I tried the method in https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md#dreamview-does-not-open-up-if-i-install-more-than-1-version-of-apollo but I could still only be able to access Dreamview through port 8888.

**Comment by daohu527** [comment]
## solution
You should add this port config in `/apollo/modules/common/data/global_flagfile.txt`

#### tips
Also, after you have modified and start the dreamview by `./scripts/bootstrap.sh`, you will notice
```
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information
```
Ignore it, or you can modify the `DREAMVIEW_URL="http://localhost:your_port"`

**Comment by EricWu416** [comment]
@daohu527 Sorry for the late reply as I couldn't access Dreamview for the past few days. I just tried your suggestion and it works great, thanks!

**Comment by hawl666** [comment]
@EricWu416 how did you modify the DREAMVIEW_URL?I want to change the port 8888.

**Comment by daohu527** [comment]
Add below config in `/apollo/modules/common/data/global_flagfile.txt`
```
--server_ports=xxxx
```

**Comment by kawashima-fj** [comment]
Hi Apollo developers,

Is this a defect of the [FAQ](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md#dreamview-does-not-open-up-if-i-install-more-than-1-version-of-apollo)? If so, the FAQ should be corrected.

Alternatively, I can also change the Dreamview's port number by the following patch.

```patch
diff --git a/modules/dreamview/conf/dreamview.conf b/modules/dreamview/conf/dreamview.conf
index 245f5bef04..32d7798a4d 100644
--- a/modules/dreamview/conf/dreamview.conf
+++ b/modules/dreamview/conf/dreamview.conf
@@ -1 +1,2 @@
---flagfile=modules/common/data/global_flagfile.txt
+--flagfile=/apollo/modules/common/data/global_flagfile.txt
+--server_ports=5555
diff --git a/modules/dreamview/launch/dreamview.launch b/modules/dreamview/launch/dreamview.launch
index 248c5b16a9..3a09b8e33a 100644
--- a/modules/dreamview/launch/dreamview.launch
+++ b/modules/dreamview/launch/dreamview.launch
@@ -4,7 +4,7 @@
         <dag_conf></dag_conf>
         <type>binary</type>
         <process_name>
-           /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt
+           /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/dreamview.conf
         </process_name>
         <exception_handler>respawn</exception_handler>
     </module>
diff --git a/scripts/bootstrap.sh b/scripts/bootstrap.sh
index b22fc4ba6b..e72c8c9ac2 100755
--- a/scripts/bootstrap.sh
+++ b/scripts/bootstrap.sh
@@ -17,7 +17,7 @@
 ###############################################################################
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-DREAMVIEW_URL="http://localhost:8888"
+DREAMVIEW_URL="http://localhost:5555"
 
 cd "${DIR}/.."
 
```

If the FAQ is the intended description and this issue is a defect of `dreamview.launch` and `dreamview.conf`, these files should be corrected, like below.

```patch
diff --git a/modules/dreamview/launch/dreamview.launch b/modules/dreamview/launch/dreamview.launch
index 248c5b16a9..3a09b8e33a 100644
--- a/modules/dreamview/launch/dreamview.launch
+++ b/modules/dreamview/launch/dreamview.launch
@@ -4,7 +4,7 @@
         <dag_conf></dag_conf>
         <type>binary</type>
         <process_name>
-           /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt
+           /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/dreamview.conf
         </process_name>
         <exception_handler>respawn</exception_handler>
     </module>
diff --git a/modules/dreamview/conf/dreamview.conf b/modules/dreamview/conf/dreamview.conf
index 245f5bef04..adc44948bb 100644
--- a/modules/dreamview/conf/dreamview.conf
+++ b/modules/dreamview/conf/dreamview.conf
@@ -1 +1 @@
---flagfile=modules/common/data/global_flagfile.txt
+--flagfile=/apollo/modules/common/data/global_flagfile.txt
```
