### ISSUE TITLE
no module named cyber_py

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13329]
如图所示，执行上述python文件显示如图所示错误，no moudel named cyber_py .请问是什么原因呢？求大佬帮忙看一下，谢谢。

**Comment by hxj0316** [comment]
![2021-01-17 09-56-00 的屏幕截图](https://user-images.githubusercontent.com/66103957/104829228-b9d07e00-58ac-11eb-9139-5272133ff760.png)

**Comment by changsh726** [comment]
Seems that you are not in the docker environment. Please follow the steps in [apollo software installation guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide_cn.md).
