### ISSUE TITLE
Subscribing to topics from other modules

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13333]
### System information

- **OS Platform and Distribution Linux Ubuntu 18.04
- **Apollo installed from source 
- **Apollo version 5.0

I have created a module that only subscribes to apollo/control topic. I have successfully built and launched my module. However, as I need control and other module to be launched as well so it publishes the topic + I can do a simulated drive, I am not able to do so crashing my module.. On dreamviewer ( I have created a separate switch on module controller of dreamview for my module), the moment I turn on other modules for a trial drive, like localization, perception etc., my module crashes although its not dependent on those modules, but only control module. Is there some kind of dependency I am missing? Appreciate your help

thank you

**Comment by ntutangyun** [comment]
could you run your module in the terminal and post the log here when it crashes.

**Comment by jpcloud1577** [comment]
Here is the log :

cyber_launch start modules/inteli/launch/inteli.launch
[cyber_launch_16008] INFO Launch file [/apollo/modules/inteli/launch/inteli.launch]
[cyber_launch_16008] INFO ========================================================================================================================
[cyber_launch_16008] INFO Load module [inteli] library: [inteli] [CYBER_DEFAULT] conf: [/apollo/modules/inteli/dag/inteli.dag] exception_handler: []
[cyber_launch_16008] INFO Start process [inteli] successfully. pid: 16016
[cyber_launch_16008] INFO ------------------------------------------------------------------------------------------------------------------------
[inteli ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[inteli ]  I0118 15:01:23.780402 16016 module_argument.cc:81] [] command: mainboard -d /apollo/modules/inteli/dag/inteli.dag -p inteli -s CYBER_DEFAULT 
[inteli ]  I0118 15:01:23.781580 16016 global_data.cc:150] [] host ip: 192.168.1.134
[inteli ]  I0118 15:01:23.782670 16016 module_argument.cc:57] [] binary_name_ is mainboard, process_group_ is inteli, has 1 dag conf
[inteli ]  I0118 15:01:23.782989 16016 module_argument.cc:60] [] dag_conf: /apollo/modules/inteli/dag/inteli.dag
[inteli ]  Could not create logging file: Permission denied
[inteli ]  COULD NOT CREATE A LOGGINGFILE 20210118-150123.16016!Could not create logging file: Permission denied
[inteli ]  COULD NOT CREATE A LOGGINGFILE 20210118-150124.16016!Could not create logging file: Permission denied
[inteli ]  COULD NOT CREATE A LOGGINGFILE 20210118-150124.16016!
[cyber_launch_16008] ERROR Process [inteli] has finished. [pid 16016, cmd mainboard -d /apollo/modules/inteli/dag/inteli.dag -p inteli -s CYBER_DEFAULT].
[cyber_launch_16008] INFO All processes has died.
[cyber_launch_16008] INFO Cyber exit.
[cyber_launch_16008] INFO All processes have been stopped.
