### ISSUE TITLE
Routing_Request Points from Dreamview

### ISSUE THREAD

**Issue by WentaoWang-SH** [ApolloAuto/apollo#13335]
if I understand correctly, the routing_request should at least has two points: the start_point, the end_point.

 **Test1:**
if I select a point and click the Send Routing Request in the dreamview,  the following is the topic of /apollo/routing_request:
waypoint1: start_point
waypoint2: end_point
![image](https://user-images.githubusercontent.com/24958250/104917946-0ca25680-59cf-11eb-9c1b-621ddbc91d03.png)

**Question 1:**  
      I think waypoint2 is the point that I selected in Dreamview. 
      But how did the apollo system get the waypoint1?    the waypoint1 should be the vehicle's localization pose? 
      **so where is the source code of getting the vehicle's localization pose to be the waypoint1?**  I can't find it in the dreamview/backend, maybe it's in the frontend?

------------------------------------------------------------------------------------------
**Test2:**
Then After the vehicle arrived, I selected another point in the dreamview:  sequence_number = 2
![image](https://user-images.githubusercontent.com/24958250/104918736-255f3c00-59d0-11eb-893f-390985e2e490.png)

**Question2:**
In my opinion, I think the waypoint1 of sequence_number2 should equal to the waypoint2 of  sequence_number1? 
the start_point of sequence_number2 should queal to the end_point of sequence_number1.

**but why actually it's not?** 

![image](https://user-images.githubusercontent.com/24958250/104920054-2f823a00-59d2-11eb-8075-bfde2396692f.png)

**Comment by daohu527** [comment]
> I think waypoint2 is the point that I selected in Dreamview.
But how did the apollo system get the waypoint1? the waypoint1 should be the vehicle's localization pose?

yes, if you only select 1 point, then the starting point is the position of the car, and the ending point is the selected point
