### ISSUE TITLE
Possibility of manipulating modules by python scripts

### ISSUE THREAD

**Issue by Yimags** [ApolloAuto/apollo#13340]
Hello all,

In addition to web based UI and cyber_launch, is that possible to manipulate modules by python scripts?

**Comment by changsh726** [comment]
Of course. In fact, `cyber_launch` is done through a [python script](https://github.com/ApolloAuto/apollo/blob/master/cyber/tools/cyber_launch/cyber_launch.py).

**Comment by Yimags** [comment]
@changsh726  Hello, it's nice to know this. Could you maybe give a simple example about how to use this Python script to turn on and off a single module? It will be of great help. Thx in advance!

**Comment by changsh726** [comment]
There is no examples, this is basically executing a shell command `mainboard -d xxx.dag` or `cyber_launch start xxx.launch` in python, which can be done through `os.system()` etc.

**Comment by Yimags** [comment]
Thx! It helps a lot!
