### ISSUE TITLE
Running Multiple Apollo Instances for Multiple users

### ISSUE THREAD

**Issue by xiafawu** [ApolloAuto/apollo#13353]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

### Question
Is it possible to run multiple Apollo instances on a single machine? When trying to run Apollo modules while other users running Apollo already on a different container, I get messages like module <module name> is already running, skipping, when I try to start modules including planning, routing, and dreamview. I could only start my modules when other apollo_dev containers are stopped. Thank you!

**Comment by storypku** [comment]
Hi @EricWu416, I think the main reason for this was that Apollo Docker containers was started  using  the `--pid=host --net=host` options for `docker run`, see: https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L540 . 

You can try to tweak this to see if it works.

**Comment by storypku** [comment]
And, please refer to #13255 for more.

**Comment by EricWu416** [comment]
@storypku Thanks for the suggestion. I tried to remove the `--pid=host` option for `docker run`, which appeared to be working as I won't observe outputs similar to "module is already running". However, when I try to run `bash scripts/planning.sh start_fe`, I noticed it complains about duplicated node of planning, and the module will stop execution afterwards automatically while other users' `apollo_dev` containers are running. Of course, when theses containers are stopped, I could successfully start my modules. 

In addition, you mentioned hardware access in the issue that you wanted me to refer to. I am not entirely sure of what can be counted as hardware access. Could you further explain what you mean by that? Thanks!

**Comment by gsa88** [comment]
Hi @EricWu416! 
In addition to removing `--pid=host`, you should also remove `--net=host`, because without this, the module's channels will be shared across all instances. But when you remove `--net=host` your network inside the docker will be isolated and you will need to expose all necessary ports (eg, 8888 for dreamview `-p 8888:8888` ).

A hardware issue can be caused by the fact that when you only have one CAN device connected to your PC and multiple instances running with one device can cause a collision.

**Comment by EricWu416** [comment]
@gsa88 Sorry for the late reply and thanks for the suggestion. I ended up running several VMs as an alternative, but I will give this solution a try! Thanks again!
