### ISSUE TITLE
traffic_light_unprotected_right_turn_scenario.pic.d (No such file or directory)

### ISSUE THREAD

**Issue by zjiek327** [ApolloAuto/apollo#13363]
Run this command: `bash apollo.sh build`    **no GPU**
```
ERROR: /apollo/modules/planning/scenarios/traffic_light/unprotected_right_turn/BUILD:7:11: error while parsing .d file: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/bin/modules/planning/scenarios/traffic_light/unprotected_right_turn/_objs/traffic_light_unprotected_right_turn_scenario/traffic_light_unprotected_right_turn_scenario.pic.d (No such file or directory)
```
Anybody can help me?
Thanks!

**Comment by daohu527** [comment]
## .d file
Many build systems add automatically detected make dependencies into the .d file. In particular, for C/C++ source files they determine what #include files are required and automatically generate that information into the .d file.

The .d files are then included by the makefile so make is aware of that information. If you look at the contents of those files they'll be make prerequisite statements, like:

```
foo.o : foo.h bar.h biz.h
```
[ref](https://stackoverflow.com/questions/19114410/what-is-d-file-after-building-with-make)  

## suggestion
It may be related to the software version, so it is recommended to clear the cache and try again
```
./apollo.sh clean
```

**Comment by storypku** [comment]
> Run this command: `bash apollo.sh build` **no GPU**
> 
> ```
> ERROR: /apollo/modules/planning/scenarios/traffic_light/unprotected_right_turn/BUILD:7:11: error while parsing .d file: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/bin/modules/planning/scenarios/traffic_light/unprotected_right_turn/_objs/traffic_light_unprotected_right_turn_scenario/traffic_light_unprotected_right_turn_scenario.pic.d (No such file or directory)
> ```
> 
> Anybody can help me?
> Thanks!

Please paste the result of `./apollo.sh config -n` first. Thank you.

**Comment by zjiek327** [comment]
@storypku  @daohu527   thanks!
`./apollo.sh clean`  is helpful.

**Comment by storypku** [comment]
Hi @zjiek327, it seems that the this issue was resolved. Thus I am going to close this issue now. Please feel free to create another issue if you have other questions. Our engineering team is willing to help.
