### ISSUE TITLE
大家都是怎么使用Apollo这个平台的？

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13361]
大家好，我是一名研一的学生。然后导师想做自动驾驶相关的项目，购买了一套Apollo的D-kite套件，现在基本上把官网的教程快全部跑完了，想问一下大家，接下来可以做哪些研究呢？是从代码角度继续借由Apollo平台研究无人驾驶的架构还是使用LGSVL绘制高精地图呢？大家有什么建议吗？谢谢大家啦~

**Comment by daohu527** [comment]
You can do it in many ways.

You know that autonomous driving systems can be divided into: localization, perception, planning, and control modules. choose anyone you are interested in and dive in it.

First, you can search on the Internet and learn about good practices and the state-of-art methods for solving problems.
Second, you can read the code and learn from it then improve it.
Last, you can do some meaningful projects. There are many open source autonomous driving small projects on the Internet. Like [carla](https://carla.org/), [dataviz](https://eng.uber.com/atg-dataviz/)

**Comment by hxj0316** [comment]
好的，很有帮助，谢谢你。昨天我还在看您那篇Dig-into-Apollo呢，写的很好，对我很有启发。

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
