### ISSUE TITLE
Where is EM Planner since Apollo 3.5?

### ISSUE THREAD

**Issue by KKevinTso** [ApolloAuto/apollo#13368]
Hi, recently I've read many materials and Official recommended paper about Apollo EM planner. But i just found that there is no EM planner since Apollo 3.5 and a new planner called Public road planner appeared since then.
so i'd like to know where is EM planner? Was it just changed name or abandoned, and why?
thanks for your time to answer me.
sincerely!

**Comment by JackFu123** [comment]
Hi, it's evolved to public_road planner.

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
