### ISSUE TITLE
where to find the robo_back/left/right_novatel_extrinsics.yaml

### ISSUE THREAD

**Issue by ypbbbbb** [ApolloAuto/apollo#13364]
**Describe the bug**
when i cyber_launch start /apollo/modules/transform/launch/static_transform.launch,it came to a error:/modules/drives/velodyne/robo_back/left/right_novatel_extrinsics.yaml doesn't exist.

**To Reproduce**
1.cyber_launch start /apollo/modules/transform/launch/static_transform.launch
2. See error

**Expected behavior**
luanch ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/49785444/105568464-6a8ac180-5d74-11eb-9935-9b8c35e30ea7.png)
![image](https://user-images.githubusercontent.com/49785444/105568465-75dded00-5d74-11eb-98c7-1b27082c411f.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version apollo 6.0

**Comment by SeasoulChris** [comment]
could you show your vehicle type selected in dreamview? I think you selected a wrong vehicle type

**Comment by ypbbbbb** [comment]
> could you show your vehicle type selected in dreamview? I think you selected a wrong vehicle type

![image](https://user-images.githubusercontent.com/49785444/105657587-adc56b80-5eff-11eb-85b8-a53b2b4db6db.png)
okay，i selectd the Mkz example. is the vehicle type effected something? and thanks for your help.

**Comment by SeasoulChris** [comment]
you can check modules/transform/conf/static_transform_conf.pb.txt， delete unnecessary config

**Comment by ypbbbbb** [comment]
> you can check modules/transform/conf/static_transform_conf.pb.txt， delete unnecessary config

thank you, i delete the config ,and the error disappeared.Thanks for your help!

**Comment by changsh726** [comment]
It seems that your problem has been solved, so this issue will be closed. Please feel free to reopen it or open a new issue if you still have other problems. Thanks for your supporting to Apollo.
