### ISSUE TITLE
如何不通过Dreamview来打开Lidar采集数据？

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13362]
您好，我们购买的是Apollo的D-kit套件，请问如何不通过Apollo的Dreamview来打开激光雷达。如何通过激光雷达来采集呢？谢谢

**Comment by daohu527** [comment]
You can use below command to start and stop record
```
    start_command: "/apollo/scripts/record_bag.py --start --all"
    stop_command: "/apollo/scripts/record_bag.py --stop --stop_signal SIGINT"
```

The record file is save in `apollo/data/bag` and named according to the acquisition time

**Comment by changsh726** [comment]
You can run `mainboard -d /apollo/modules/drivers/lidar/dag/lidar.dag` to launch the lidar.
