### ISSUE TITLE
Protoc version in docker and error in pb.h file

### ISSUE THREAD

**Issue by jpcloud1577** [ApolloAuto/apollo#13379]
The protobuf header messages generated by protoc in apollo docker is generating this

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif

However, if I check protoc version in my system it is libprotoc 3.14.0 ( which is used as GOOGLE_PROTOBUF_VERSION) while protoc in docker is 3.3.0. Hence I think I need to downgrade protoc on my system to 3.3.0 to disable this error message. So, my question is if there a dependency outside of the docker on the protoc version. If so, please let me know how to downgrade it safely
`

thanks for your help

**Comment by storypku** [comment]
> The protobuf header messages generated by protoc in apollo docker is generating this
> 
> #if GOOGLE_PROTOBUF_VERSION < 3003000
> #error This file was generated by a newer version of protoc which is
> #error incompatible with your Protocol Buffer headers. Please update
> #error your headers.
> #endif
> 
> However, if I check protoc version in my system it is libprotoc 3.14.0 ( which is used as GOOGLE_PROTOBUF_VERSION) while protoc in docker is 3.3.0. Hence I think I need to downgrade protoc on my system to 3.3.0 to disable this error message. So, my question is if there a dependency outside of the docker on the protoc version. If so, please let me know how to downgrade it safely
> `
> 
> thanks for your help

Which Apollo branch do you work on? protobuf 3.14 inside Docker was only available for master.

**Comment by jpcloud1577** [comment]
I am using Apollo 5 branch (through LGSVL fork) and the proto in the docker is 3.3.0. The proto that I have on my system ( outside of docker) is 3.14.0. I tried to downgrade to match 3.3.0, but havent been able to. It is installing 3.0.0 no matter which repo or method I use

**Comment by changsh726** [comment]
There is no need to downgrade. The environment in docker container is isolated from outside, so you don't need to care about the version of protoc in your system.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
