### ISSUE TITLE
Camera Perception Launch Error

### ISSUE THREAD

**Issue by siddhagarwal** [ApolloAuto/apollo#13377]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- Ubuntu 18.04
- **Apollo installed from (source or binary)**:
- Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- 6.0
- **Output of `apollo.sh config` if on `master` branch**:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-01-27-39572c120b
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210126_2027
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Run cyber_launch start modules/perception/production/launch/perception_camera.launch

Error:
[cyber_launch_16811] INFO Launch file [/apollo/modules/perception/production/launch/perception_camera.launch]
[cyber_launch_16811] INFO ========================================================================================================================
[cyber_launch_16811] INFO Load module [perception_camera] library: [mainboard_default_16811] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: []
[cyber_launch_16811] INFO Start process [mainboard_default_16811] successfully. pid: 16818
[cyber_launch_16811] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_16811] INFO Load module [motion_service] library: [mainboard_default_16811] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_motion_service.dag] exception_handler: []
[mainboard_default_16811]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_16811]  I0127 17:23:05.908279 16818 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag /apollo/modules/perception/production/dag/dag_motion_service.dag -p mainboard_default_16811 -s CYBER_DEFAULT 
[mainboard_default_16811]  I0127 17:23:05.908366 16818 module_argument.cc:120] []Found non-option ARGV-element "/apollo/modules/perception/production/dag/dag_motion_service.dag"
[mainboard_default_16811]  I0127 17:23:05.908372 16818 module_argument.cc:29] []Usage: 
[mainboard_default_16811]      mainboard [OPTION]...
[mainboard_default_16811]  Description: 
[mainboard_default_16811]      -h, --help : help information 
[mainboard_default_16811]      -d, --dag_conf=CONFIG_FILE : module dag config file
[mainboard_default_16811]      -p, --process_group=process_group: the process namespace for running this module, default in manager process
[mainboard_default_16811]      -s, --sched_name=sched_name: sched policy conf for hole process, sched_name should be conf in cyber.pb.conf
[mainboard_default_16811]  Example:
[mainboard_default_16811]      mainboard -h
[mainboard_default_16811]      mainboard -d dag_conf_file1 -d dag_conf_file2 -p process_group -s sched_name
[cyber_launch_16811] ERROR Process [mainboard_default_16811] has died [pid 16818, exit code 1, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag /apollo/modules/perception/production/dag/dag_motion_service.dag -p mainboard_default_16811 -s CYBER_DEFAULT].
[cyber_launch_16811] INFO All processes has died.
[cyber_launch_16811] INFO Cyber exit.
[cyber_launch_16811] INFO All processes have been stopped.

### Supporting materials (screenshots, command lines, code/script snippets):

I understand camera perception was being fixed, any updates? Thanks

**Comment by panfengsu** [comment]
you can first test with the command 'mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag'.
