### ISSUE TITLE
Planning module not working

### ISSUE THREAD

**Issue by Manoj-EK** [ApolloAuto/apollo#13381]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (6.0)**:

### Steps to reproduce the issue:
- **start Apollo Dreamview..Then select relevant modules...Set Routing....**:
- ** Planning module does not activate**

**SIMILAR TO ISSUE #13300**

**Comment by ntutangyun** [comment]
could you manually start planning module and post the error message here

**Comment by Manoj-EK** [comment]
i changed my apollo version 5.5..Its working fine now

**Comment by Manoj-EK** [comment]
@ntutangyun Thank you for your quick response....In future...if I get any issues...will surely bring to notice
