### ISSUE TITLE
Is it possible to send the GPS correction data via serial port ???

### ISSUE THREAD

**Issue by Abd0ul** [ApolloAuto/apollo#13389]
### Supporting materials (screenshots, command lines, code/script snippets):
OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
Apollo installed from (source):
Apollo version (1.0,1.5, 2.0, 2.5):

Hello, I have a question regarding the configuration of the GPS receiver. I have a base station configured to send the correction data (RTCMV3 format) to the mobile receiver via radio modems, it works but I have a small problem concerning the recovery of the correction data in Apollo. 

In the default configuration of the gnss driver the data is sent by an NTRIP server which implies the use of the server address and port but I use radio modems, which means that I must use a serial port for sending the correction data to Apollo.

```
data {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/ttyUSB0"
        baud_rate: 115200
    }
}

#rtk_from {
#    format: RTCM_V3
#    serial {
#        #device: "/dev/ttyUSB2"
#        #baud_rate: 9600
#        timeout_s: 5
#    }
#    push_location: true
#}

rtk_to {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/ttyUSB1"
        baud_rate: 115200
    }
}

command {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/ttyUSB2"
        baud_rate: 115200
    }
}
```

would it be possible to use the same serial port for sending GPS data (Novatel_Binary format) and correction data (RTCMV3) ???

**Comment by daohu527** [comment]
RTCMV3 is a network protocol, I think it cannot be transmitted through the serial port.

I know that the GPS device of the d-kit car can access the network RTK by itself. Is this the feature you want?

**Comment by Abd0ul** [comment]
Thank you for this precision, the GPS device is already accessing these data (see the two figures).

I am looking for a way to send the correction data to the apollo software because in the topics of the GNSS driver there is a topic **"/apollo/sensor/gnss/rtcm_data"** which is supposed to post this data but I can't do it through the same serial port I send the GPS data through.

![01](https://user-images.githubusercontent.com/60668969/106468061-c0aae380-649d-11eb-8854-fa3756cfe57e.PNG)

`navette1@in_dev_docker:/apollo$ rostopic echo /apollo/sensor/gnss/rtcm_data 
/use_sim_time is not set, will not subscribe to simulated time [/clock] topic`

**Comment by daohu527** [comment]
You can use the data port to receive RTK correction data. Although there are still some details to confirm, such as whether the device supports it and how to set it up
```
data {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/novatel0"
        baud_rate: 115200
    }
}
```

## reference
https://github.com/ApolloAuto/apollo/blob/3f28fa6ff73ec0d91687485e8c691326c92f994d/modules/drivers/gnss/proto/config.proto#L97-L99

**Comment by Abd0ul** [comment]
I checked this track, it is actually used to send the correction data to the port specifier.

Did you know why the topic /apollo/sensor/gnss/rtcm_data does not send anything as a return? 
I thought that this topic is used to publish the data of corrections received by the GPS device.

This data of topic are important for modules?

![Capture d’écran de 2021-02-01 17-59-59](https://user-images.githubusercontent.com/60668969/106491745-77678d80-64b7-11eb-89ab-4ecce8dd511e.png)

**Comment by daohu527** [comment]
In my opinion, `/apollo/sensor/gnss/rtcm_data` is used for gnss module only. It's used for rtk calibration, no other modules need to use it.

**Comment by Abd0ul** [comment]
Thank @daohu527, in this case no worries if I do not receive the data publications on this topic?

In dreamview apollo indicates the correct functioning of the GPS driver: 

![Capture d’écran de 2021-02-01 14-00-16](https://user-images.githubusercontent.com/60668969/106592916-6880e980-6550-11eb-9f94-98c82708296c.png)

**Comment by daohu527** [comment]
Yes, Other external modules do not need this topic. If gnss module works well, I think it's fine. : )

**Comment by Abd0ul** [comment]
Thanks, you can close this issue.
