### ISSUE TITLE
Prediction: angle average caculation bug

### ISSUE THREAD

**Issue by strongdeer** [ApolloAuto/apollo#13393]
**Describe the bug**
In Prediction module, using ComputeMean() implemented by arithmatic average to calculate the average for angle has something wrong since angle ranges in [0, 2π) or [-π, π). For example, when the angles are around -π in the case of [-π, π), e.g. a vector of [-179, 179] in degree, the result of ComputeMean() is 0 rather than -π. It is the same when the angles are around 0 in the case of [0, 2π). 
This can be resolved by decomposing the angle to x and y dimension, calculating the arithmatic average of x and y component respectively, and composing the average of x and y component to form the average of angles.

**Comment by daohu527** [comment]
Do you mean this function.
https://github.com/ApolloAuto/apollo/blob/d08f0dd680ee1da5a9605f7410d88218ef1e2ba4/modules/prediction/evaluator/vehicle/mlp_evaluator.cc#L35-L43

I think it depends, below are some suggestions
1. If all angles are [0, π] there will be no problem, so we need to check the calling function.
2. how to define the average value of the angle?

**Comment by strongdeer** [comment]
Yes. It is used to calculate the theta_mean.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
