### ISSUE TITLE
Dreamview bug: cannot enable Perception, map does not load

### ISSUE THREAD

**Issue by fedlucchetti** [ApolloAuto/apollo#13395]
### Issue
Cannot enable Perception module
Cannot start a navigation
whatever I do, Dreamview always displays 'Please send car initial position and map data.'
Below are the steps to reproduce, as well as the errors that I get. 
I tried every possible solution proposed, could no find anything that works for me.
Thank you for your support.

### System information

- **OS Platform and Distribution**:Linux Ubuntu 20.04
- **Hardware**: 
CPU: AMD® Ryzen 7 3700x 8-core processor × 16 
Memory: 32 GB
GPU: NVIDIA RTX3090
- **Apollo version**:  6.0
- **Output of `apollo.sh config` if on `master` branch**:
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-01-30-3f28fa6ff7
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210129_0240
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

### Steps to reproduce the issue:
- I installed Apollo 6.0 following the instructions https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md
- Built in docker using `./apollo.sh build_opt` -> successfully built
- Inside docker `./scripts/bootstrap.sh start`
- Visit http://localhost:8888
- Select car and map: Lincoln2017, Borregas avenue (choice doesn't influence the outcome)
- Setup mode :MKZ debug
- Run `./scripts/transform.sh` --> Ok, Transform tab in Dreamview enabled
- Run `mainboard -d modules/perception/production/dag/dag_streaming_perception.dag` or `./scripts/perception.sh`
[cyber_launch_157715] INFO ========================================================================================================================
[cyber_launch_157715] INFO Load module [perception] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception.dag] exception_handler: []
[cyber_launch_157713] INFO Launch file [/apollo/modules/transform/launch/static_transform.launch]
[cyber_launch_157713] INFO ========================================================================================================================
[cyber_launch_157713] INFO Load module [static_transform] library: [mainboard_default_157713] [CYBER_DEFAULT] conf: [/apollo/modules/transform/dag/static_transform.dag] exception_handler: []
[cyber_launch_157714] INFO Launch file [/apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch]
[cyber_launch_157714] INFO ========================================================================================================================
[cyber_launch_157714] INFO Load module [image_decompress] library: [mainboard_default_157714] [CYBER_DEFAULT] conf: [/apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag] exception_handler: []
[cyber_launch_157715] INFO Start process [perception] successfully. pid: 157734
[cyber_launch_157715] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_157715] INFO Load module [perception_traffic_light] library: [perception_trafficlights] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag] exception_handler: []
[cyber_launch_157713] INFO Start process [mainboard_default_157713] successfully. pid: 157735
[cyber_launch_157713] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_157714] INFO Start process [mainboard_default_157714] successfully. pid: 157737
[cyber_launch_157714] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_157715] INFO Start process [perception_trafficlights] successfully. pid: 157740
[cyber_launch_157715] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_157715] INFO Load module [motion_service] library: [motion_service] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_motion_service.dag] exception_handler: []
[cyber_launch_157715] INFO Start process [motion_service] successfully. pid: 157742
[cyber_launch_157715] INFO ------------------------------------------------------------------------------------------------------------------------
[mainboard_default_157714]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_157714]  I0202 11:36:28.719099 157737 module_argument.cc:81] []command: mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_157714 -s CYBER_DEFAULT 
[mainboard_default_157714]  I0202 11:36:28.719441 157737 global_data.cc:153] []host ip: 10.186.24.11
[mainboard_default_157714]  I0202 11:36:28.719897 157737 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default_157714, has 1 dag conf
[mainboard_default_157714]  I0202 11:36:28.719902 157737 module_argument.cc:60] []dag_conf: /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag
[mainboard_default_157713]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_157713]  I0202 11:36:28.724576 157735 module_argument.cc:81] []command: mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_157713 -s CYBER_DEFAULT 
[perception_trafficlights]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_trafficlights]  I0202 11:36:28.724676 157740 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT 
[mainboard_default_157713]  I0202 11:36:28.725126 157735 global_data.cc:153] []host ip: 10.186.24.11
[perception_trafficlights]  I0202 11:36:28.725133 157740 global_data.cc:153] []host ip: 10.186.24.11
[perception_trafficlights]  I0202 11:36:28.725562 157740 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception_trafficlights, has 1 dag conf
[mainboard_default_157713]  I0202 11:36:28.725571 157735 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default_157713, has 1 dag conf
[perception_trafficlights]  I0202 11:36:28.725567 157740 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag
[mainboard_default_157713]  I0202 11:36:28.725577 157735 module_argument.cc:60] []dag_conf: /apollo/modules/transform/dag/static_transform.dag
[perception]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[motion_service]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception]  I0202 11:36:28.725827 157734 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag -p perception -s CYBER_DEFAULT 
[perception]  I0202 11:36:28.726212 157734 global_data.cc:153] []host ip: 10.186.24.11
[motion_service]  I0202 11:36:28.725885 157742 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_motion_service.dag -p motion_service -s CYBER_DEFAULT 
[motion_service]  I0202 11:36:28.726213 157742 global_data.cc:153] []host ip: 10.186.24.11
[motion_service]  I0202 11:36:28.726673 157742 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is motion_service, has 1 dag conf
[perception]  I0202 11:36:28.726680 157734 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception, has 1 dag conf
[motion_service]  I0202 11:36:28.726680 157742 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_motion_service.dag
[perception]  I0202 11:36:28.726686 157734 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception.dag
[mainboard_default_157713]  E0202 11:36:28.740332 157735 static_transform_component.cc:60] [static_transform]Extrinsic yaml file does not exist: /apollo/modules/drivers/velodyne/params/velodyne16_novatel_extrinsics.yaml
[perception]  [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:319] Error parsing text-format apollo.perception.onboard.FusionCameraDetection: 28:17: Message type "apollo.perception.onboard.FusionCameraDetection" has no field named "lidar_type_name".
[perception]  E0202 11:36:29.203138 157734 file.cc:81] [mainboard]Failed to parse file /apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt as text proto.
[perception]  E0202 11:36:29.203255 157734 file.cc:103] [mainboard]Failed to parse file /apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt as binary proto.
[perception]  E0202 11:36:29.203346 157734 node_channel_impl.h:155] [perception]Can't create a writer with empty channel name!
[perception]  E0202 11:36:29.203408 157734 node_channel_impl.h:155] [perception]Can't create a writer with empty channel name!
[perception]  E0202 11:36:29.203467 157734 node_channel_impl.h:155] [perception]Can't create a writer with empty channel name!
[perception]  E0202 11:36:29.203517 157734 node_channel_impl.h:155] [perception]Can't create a writer with empty channel name!
[perception]  E0202 11:36:29.203527 157734 fusion_camera_detection_component.cc:410] [perception]invalid camera_names_.size(): 0
[perception]  E0202 11:36:29.203531 157734 fusion_camera_detection_component.cc:167] [perception]InitSensorInfo() failed.
[perception]  E0202 11:36:29.203533 157734 component.h:155] [mainboard]Component Init() failed.
[perception]  E0202 11:36:29.203565 157734 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception.dag
[perception]  E0202 11:36:29.206486 157734 mainboard.cc:39] [mainboard]module start error.
[perception]  mainboard: symbol lookup error: /usr/local/lib/libmkl_gnu_thread.so.1: undefined symbol: mkl_serv_lock
[perception_trafficlights]  E0202 11:36:29.433737 157896 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[TrafficLightsComponent], please ensure that each node has a unique name.
[mainboard_default_157714]  E0202 11:36:29.907945 157839 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[camera_front_6mm_decompress], please ensure that each node has a unique name.
[mainboard_default_157714]  E0202 11:36:29.908015 157839 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[camera_front_12mm_decompress], please ensure that each node has a unique name.
[mainboard_default_157714]  E0202 11:36:29.908037 157839 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[camera_left_fisheye_decompress], please ensure that each node has a unique name.
[mainboard_default_157714]  E0202 11:36:29.908052 157839 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[camera_right_fisheye_decompress], please ensure that each node has a unique name.
[mainboard_default_157714]  E0202 11:36:29.908071 157839 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[camera_rear_6mm_decompress], please ensure that each node has a unique name.
[mainboard_default_157713]  E0202 11:36:29.909385 157836 node_manager.cc:101] [mainboard]this process will be terminated due to duplicated node[static_transform], please ensure that each node has a unique name.
[mainboard_default_157714]  
[mainboard_default_157713]  
[cyber_launch_157713] ERROR Process [mainboard_default_157713] has finished. [pid 157735, cmd mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_157713 -s CYBER_DEFAULT].
[cyber_launch_157713] INFO All processes has died.
[cyber_launch_157713] INFO Cyber exit.
[cyber_launch_157714] ERROR Process [mainboard_default_157714] has finished. [pid 157737, cmd mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_157714 -s CYBER_DEFAULT].
[cyber_launch_157714] INFO All processes has died.
[cyber_launch_157713] INFO All processes have been stopped.
[cyber_launch_157714] INFO Cyber exit.
[cyber_launch_157714] INFO All processes have been stopped.

**Comment by daohu527** [comment]
Did you start the perception module separately without hardware or simulator? perception module have some dependency module like: localization and hardware(camera or lidar)

**Comment by fedlucchetti** [comment]
> Did you start the perception module separately without hardware or simulator? perception module have some dependency module like: localization and hardware(camera or lidar)

I am running exclusively in simulation, there is no hardware. How would I run the perception module separately without simulator?

BTW: I just ran `./scripts/apollo_test.sh` and  got the following results:

//cyber/transport/shm:condition_notifier_test                           TIMEOUT in 3 out of 3 in 60.1s
  Stats over 3 runs: max = 60.1s, min = 60.0s, avg = 60.1s, dev = 0.0s
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/cyber/transport/shm/condition_notifier_test/test.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/cyber/transport/shm/condition_notifier_test/test_attempts/attempt_1.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/cyber/transport/shm/condition_notifier_test/test_attempts/attempt_2.log
//modules/dreamview/backend/simulation_world:simulation_world_service_test FAILED in 3 out of 3 in 2.9s
  Stats over 3 runs: max = 2.9s, min = 2.5s, avg = 2.6s, dev = 0.2s
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/dreamview/backend/simulation_world/simulation_world_service_test/test.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/dreamview/backend/simulation_world/simulation_world_service_test/test_attempts/attempt_1.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/dreamview/backend/simulation_world/simulation_world_service_test/test_attempts/attempt_2.log
//modules/planning/integration_tests:sunnyvale_big_loop_test             FAILED in 3 out of 3 in 19.6s
  Stats over 3 runs: max = 19.6s, min = 16.4s, avg = 18.3s, dev = 1.4s
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/planning/integration_tests/sunnyvale_big_loop_test/test.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/planning/integration_tests/sunnyvale_big_loop_test/test_attempts/attempt_1.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/planning/integration_tests/sunnyvale_big_loop_test/test_attempts/attempt_2.log
//modules/planning/navi/decider:navi_decider_test                        FAILED in 3 out of 3 in 1.0s
  Stats over 3 runs: max = 1.0s, min = 0.7s, avg = 0.9s, dev = 0.1s
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/planning/navi/decider/navi_decider_test/test.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/planning/navi/decider/navi_decider_test/test_attempts/attempt_1.log
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-fastbuild/testlogs/modules/planning/navi/decider/navi_decider_test/test_attempts/attempt_2.log

Executed 2486 out of 2486 tests: 2482 tests pass and 4 fail locally.
(11:39:36) INFO: Build completed, 4 tests FAILED, 27323 total actions
