### ISSUE TITLE
Cyber launch Error --- third party *.SO Integration.

### ISSUE THREAD

**Issue by ZhiguoZhou** [ApolloAuto/apollo#13403]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5 and 6.0
- **Output of `apollo.sh config` if on `master` branch**:
WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-02-01-8ee6a3b86f
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210129_0240
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit
### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
1, Create a new cyber from timercomponentSample.
2, In this componentSample， I use third-party *.so, **which I use on ubuntu 2004 directly,  it works fine.**
3, after launch this module, error comes. 

### Supporting materials (screenshots, command lines, code/script snippets):
[dspace@in-dev-docker:/apollo]$ cyber_launch start modules/dspace_example/dspace_example.launch
[cyber_launch_14531] INFO Launch file [/apollo/modules/dspace_example/dspace_example.launch]
[cyber_launch_14531] INFO ========================================================================================================================
[cyber_launch_14531] INFO Load module [common] library: [dspace_example] [CYBER_DEFAULT] conf: [/apollo/modules/dspace_example/dspace_example.dag] exception_handler: []
[cyber_launch_14531] INFO Start process [dspace_example] successfully. pid: 14542
[cyber_launch_14531] INFO ------------------------------------------------------------------------------------------------------------------------
[dspace_example]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[dspace_example]  I0203 14:40:09.405783 14542 module_argument.cc:81] []command: mainboard -d /apollo/modules/dspace_example/dspace_example.dag -p dspace_example -s CYBER_DEFAULT 
[dspace_example]  I0203 14:40:09.406252 14542 global_data.cc:153] []host ip: 10.9.1.120
[dspace_example]  I0203 14:40:09.409029 14542 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is dspace_example, has 1 dag conf
[dspace_example]  I0203 14:40:09.409049 14542 module_argument.cc:60] []dag_conf: /apollo/modules/dspace_example/dspace_example.dag
**[dspace_example]  E0203 14:40:09.415439 14542 class_loader_utility.cc:218] [mainboard]LibraryLoadException: /apollo/bazel-bin/modules/dspace_example/../../_solib_k8/libmodules_Sdspace_Uexample_Slibdspace_Uexample_Ulib.so: undefined symbol: _ZN7VESIAPI17setSimManagerHostENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE**
[dspace_example]  E0203 14:40:09.415488 14542 class_loader_utility.cc:234] [mainboard]shared library failed: /apollo/bazel-bin/modules/dspace_example/dspace_example.so
[dspace_example]  E0203 14:40:09.415516 14542 class_loader_manager.h:70] [mainboard]Invalid class name: dspace_example
[dspace_example]  E0203 14:40:09.415530 14542 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/dspace_example/dspace_example.dag
[dspace_example]  E0203 14:40:09.415542 14542 class_loader_utility.cc:256] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/dspace_example/dspace_example.so
[dspace_example]  E0203 14:40:09.415550 14542 mainboard.cc:39] [mainboard]module start error.
[dspace_example]  
[cyber_launch_14531] ERROR Process [dspace_example] has died [pid 14542, exit code 255, cmd mainboard -d /apollo/modules/dspace_example/dspace_example.dag -p dspace_example -s CYBER_DEFAULT].
[cyber_launch_14531] INFO All processes has died.
[cyber_launch_14531] INFO Cyber exit.
[cyber_launch_14531] INFO All processes have been stopped.

**Comment by storypku** [comment]
Hi @ZhiguoZhou ,

It seems that you are building and running your custom module. Doing this requires enough knowledge of C++ compilation and Bazel build system. As such, we won't provide support for your case. For Bazel related parts, I suggest that you refer to https://docs.bazel.build/versions/master/external.html .
