### ISSUE TITLE
Any way to do autonomous valet parking with open space planner in dreamview or dreamland?

### ISSUE THREAD

**Issue by resolvve2** [ApolloAuto/apollo#13408]
I have done a lot of research on how to test Apollo's open space planner in virtual environment like dreamview or dreamland, but found very few related information. I have also tried to use lgsvl but encountered too many problems stopping me from running it correctly. 

Any suggestions?

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 18.04):18.04
    Apollo installed from (source or binary): source
    Apollo version (3.5, 5.0, 5.5, 6.0): 6.0
    Output of apollo.sh config if on master branch: master

Steps to reproduce the issue:

    Please use bullet points and include as much details as possible:

Supporting materials (screenshots, command lines, code/script snippets):

**Comment by daohu527** [comment]
You can try sim_control, which is used to test the planning module in dreamview.

[Ref link](https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/docs/howto/how_to_debug.md#start-the-module-that-needs-to-be-debugged)

**Comment by lj0919** [comment]
@resolvve2 Autonomous parking with open space planner is in development.
