### ISSUE TITLE
Localization module not working

### ISSUE THREAD

**Issue by fedlucchetti** [ApolloAuto/apollo#13420]
> ### Issue

Cannot enable Localization module in simulation mode using LGSVL

whatever I do, Dreamview always displays 'Please send car initial position and map data.'

Thank you for your support.
### System information
* OS Platform and Distribution**:Linux Ubuntu 20.04
* Hardware*:
 CPU: AMD® Ryzen 7 3700x 8-core processor × 16
Memory: 32 GB
GPU: NVIDIA RTX3090
* Apollo version**:  6.0

### Steps to reproduce the issue:
* I installed successfully  Apollo 6.0 following the instructions https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart
* I installed LGSVL following the guide https://www.lgsvlsimulator.com/docs/apollo-master-instructions/
* I launched LGSVL simulation  following the above guide by adding Borregas Ave and LincolnLKZ car with the sensor JSON found in https://www.lgsvlsimulator.com/docs/sensor-json-options/ and selecting CyberRT as bridge conenction
* Launched `./scripts/bridge.sh` in apollo docker --> LGSVL simulator tell me that bridge connection is established
* Launched `./scripts/bootstrap_lgsvl.sh`  and selected Mode: Mkz Lgsvl, Car: Lincoln2017MKZ LGSVL and Map: Borregas Ave
* Clicked multiple times on Localization but switches back off immediately
*Tried the following command:
`mainboard -d /apollo/modules/localization/dag/dag_streaming_rtk_localization.dag -p localization -s CYBER_DEFAULT`
and got the following error
F0205 16:26:36.832542 112165 localization_lidar.cc:63]   Reflectance map folder is invalid!
Same with 
`mainboard -d /apollo/modules/localization/dag/dag_streaming_msf_localization.dag -p localization -s CYBER_DEFAULT`
* Followed the issue https://github.com/ApolloAuto/apollo/issues/2426 but did not resolve my issue.
Thank you for your help!

**Comment by daohu527** [comment]
Could you pls check the content in `dag_streaming_rtk_localization.dag` and `rtk_localization.launch`.

Have they changed because rtk does not require lidar

**Comment by Yimags** [comment]
Maybe you could try the json sensor setting of [modular testing](https://www.lgsvlsimulator.com/docs/modular-testing/) to see if it works.

**Comment by fedlucchetti** [comment]
> Maybe you could try the json sensor setting of [modular testing](https://www.lgsvlsimulator.com/docs/modular-testing/) to see if it works.

Yes, I tried the modular testing with the following sensor configuration
[
  {
    "type": "3D Ground Truth",
    "name": "3D Ground Truth",
    "params": {
      "Frequency": 10,
      "Topic": "/apollo/perception/obstacles"
    },
    "transform": {
      "x": 0,
      "y": 1.975314,
      "z": -0.3679201,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "Signal",
    "name": "Signal Sensor",
    "params": {
      "Frequency": 10,
      "MaxDistance": 100,
      "Topic": "/apollo/perception/traffic_light"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "CAN-Bus",
    "name": "CAN Bus",
    "params": {
      "Frequency": 10,
      "Topic": "/apollo/canbus/chassis"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "GPS Device",
    "name": "GPS",
    "params": {
      "Frequency": 12.5,
      "Topic": "/apollo/sensor/gnss/best_pose",
      "Frame": "gps"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": -1.348649,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "GPS Odometry",
    "name": "GPS Odometry",
    "params": {
      "Frequency": 12.5,
      "Topic": "/apollo/sensor/gnss/odometry",
      "Frame": "gps"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": -1.348649,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "GPS-INS Status",
    "name": "GPS INS Status",
    "params": {
      "Frequency": 12.5,
      "Topic": "/apollo/sensor/gnss/ins_stat",
      "Frame": "gps"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": -1.348649,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "IMU",
    "name": "IMU",
    "params": {
      "Topic": "/apollo/sensor/gnss/imu",
      "Frame": "imu",
      "CorrectedTopic": "/apollo/sensor/gnss/corrected_imu",
      "CorrectedFrame": "imu"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": -1.348649,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "Radar",
    "name": "Radar",
    "params": {
      "Frequency": 13.4,
      "Topic": "/apollo/sensor/conti_radar"
    },
    "transform": {
      "x": 0,
      "y": 0.689,
      "z": 2.272,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
  },
  {
    "type": "Keyboard Control",
    "name": "Keyboard Car Control"
  },
  {
    "type": "Wheel Control",
    "name": "Wheel Car Control"
  },
  {
    "type": "Vehicle Control",
    "name": "Apollo Car Control",
    "params": {
      "Topic": "/apollo/control"
    }
  }
]

**Comment by fedlucchetti** [comment]
> Could you pls check the content in `dag_streaming_rtk_localization.dag` and `rtk_localization.launch`.
> 
> Have they changed because rtk does not require lidar

Here are the contents of  `dag_streaming_rtk_localization.dag` 

`module_config {
    module_library : "/apollo/bazel-bin/modules/localization/msf/libmsf_localization_component.so"

    components {
      class_name : "MSFLocalizationComponent"
      config {
        name : "msf_localization"
        flag_file_path : "/apollo/modules/localization/conf/localization.conf"
        readers: [
          {
            channel: "/apollo/sensor/gnss/imu"
            qos_profile: {
              depth : 10
            }
            pending_queue_size: 50
          }
        ]
      }
    }
}`

and `rtk_localization.launch`
`<cyber>
    <module>
        <name>localization</name>
        <dag_conf>/apollo/modules/localization/dag/dag_streaming_rtk_localization.dag</dag_conf>
        <process_name>localization</process_name>
    </module>
</cyber>`

**Comment by daohu527** [comment]
Here is the problem, I tried `mkz_lgsvl` and the `dag_streaming_rtk_localization.dag` is 

https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/localization/dag/dag_streaming_rtk_localization.dag#L2-L21

So do you choose other car in dreamview before? If you done that, dreamview will auto modify the config files by vehicle name.

**Comment by fedlucchetti** [comment]
Solved the issue by deleting all the entire apollo folder, cloning and building everything from scratch. Now everything works just fine.

Yes I might have tried to change the car in Dreamview. Dunno if that was the problem initially. Thank you for your help!

**Comment by Thinsheep** [comment]
@fedlucchetti 
Could you please support me with some information?. I saw you use the RTX 30x0 series GPU to run Apollo 6.0
I am planning to buy a PC to install Apollo 6.0 and a Simulator. Someone said only Apollo Master supports RTX 30 series.  Any potential issues when you use RTX 3090/3080 instead of RTX 2080/2080 Ti? 30X0 is faster but if it cannot do the job then better go with the other. I need this information so that I can order a PC for my project. If you know please give me some information. 
Thanks.

**Comment by fedlucchetti** [comment]
@Thinsheep Don't know about RTX 2080/2080Ti but I would guess that having the 24Gb memory of the RTX3090 will let you run both Apollo 6.0 and a Simulator on the same machine.

**Comment by Thinsheep** [comment]
@fedlucchetti 
Thanks for your information.
Yes, I guess that to run Apollo 6.0 and a Simulator on the same machine I would need at least 10 GB memory. I plan to go with RTX3080 (10GB). RTX3090 is a bit expensive for me. I also have another PC so I can also do the setup in 2 machines no problem.  Master just starts to supper RTX 30 series in January 2021.  Have you done successful the installation of Apollo 6.0 without remaining issues?

**Comment by fedlucchetti** [comment]
@Thinsheep Dont know whether 10GB will be sufficient to run both apollo and the simulator on the same machine. But yes, you can run both on separate devices. The LGSVL simulator lets you bypass the perception module so as to free up memory during simulation. Check out there modular testing tutorial.
Yes Apollo 6.0 (master) runs smoothly on my RTX3090.

**Comment by albert8202** [comment]
> > ### Issue
> 
> Cannot enable Localization module in simulation mode using LGSVL
> 
> whatever I do, Dreamview always displays 'Please send car initial position and map data.'
> 
> Thank you for your support.
> 
> ### System information
> * OS Platform and Distribution**:Linux Ubuntu 20.04
> * Hardware*:
>   CPU: AMD® Ryzen 7 3700x 8-core processor × 16
>   Memory: 32 GB
>   GPU: NVIDIA RTX3090
> * Apollo version**:  6.0
> 
> ### Steps to reproduce the issue:
> * I installed successfully  Apollo 6.0 following the instructions https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart
> * I installed LGSVL following the guide https://www.lgsvlsimulator.com/docs/apollo-master-instructions/
> * I launched LGSVL simulation  following the above guide by adding Borregas Ave and LincolnLKZ car with the sensor JSON found in https://www.lgsvlsimulator.com/docs/sensor-json-options/ and selecting CyberRT as bridge conenction
> * Launched `./scripts/bridge.sh` in apollo docker --> LGSVL simulator tell me that bridge connection is established
> * Launched `./scripts/bootstrap_lgsvl.sh`  and selected Mode: Mkz Lgsvl, Car: Lincoln2017MKZ LGSVL and Map: Borregas Ave
> * Clicked multiple times on Localization but switches back off immediately
>   *Tried the following command:
>   `mainboard -d /apollo/modules/localization/dag/dag_streaming_rtk_localization.dag -p localization -s CYBER_DEFAULT`
>   and got the following error
>   F0205 16:26:36.832542 112165 localization_lidar.cc:63]   Reflectance map folder is invalid!
>   Same with
>   `mainboard -d /apollo/modules/localization/dag/dag_streaming_msf_localization.dag -p localization -s CYBER_DEFAULT`
> * Followed the issue [Localization module init failurewith "Reflectance map folder is invalid" #2426](https://github.com/ApolloAuto/apollo/issues/2426) but did not resolve my issue.
>   Thank you for your help!

Have you solved your problem, since I confronted with a situation like yours
