### ISSUE TITLE
Is there any way I can download demo-sensor-demo-apollo-1.5.bag?

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#13432]
Hello. I want to use the demo-sensor-demo-apollo-1.5.bag, but the links I have found on other issue pages are no longer valid. Is there any other ways to download this bag?

Thanks!

**Comment by JackFu123** [comment]
@GabrielZZZ Please find it here. https://github.com/ApolloAuto/apollo/tree/r1.5.0/docs/demo_guide

**Comment by GabrielZZZ** [comment]
Thanks, @JackFu123 , but I am talking about the one with 8.9 GB size and sensor data in it. But anyway I appreciate your reply!

**Comment by JackFu123** [comment]
@GabrielZZZ Hi, could you tell us where you found it originally?
