### ISSUE TITLE
Does Apollo support height message in the HD map

### ISSUE THREAD

**Issue by qiongwu1003** [ApolloAuto/apollo#13444]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hi,
Apollo team

I run the Apollo with LGSVL simulator using our own map. I drawed the HD map using LGSVL simulator and export to the Apollo.
What I want to know is that if Apollo support height information in the HD map? Because there is a bridge in our map.

Thanks.

**Comment by jilinzhou** [comment]
It does not.

**Comment by qiongwu1003** [comment]
@jilinzhou Thank you got it.
