### ISSUE TITLE
bazel build offline_lidar_obstacle_perception: error no such package '@pcl//'

### ISSUE THREAD

**Issue by ypbbbbb** [ApolloAuto/apollo#13445]
i want to bazel build offline_lidar_obstacle_perception, and it comes to a error: no such package '@pcl//': the  repository '@pcl' 
could not be resolved and referenced  by '//modules/perception/lidar/tools:offline_lidar_obstacle_perception'

1. cd /apollo
2. bash docker/scripts/dev_into.sh
3. bazel build -c opt //modules/perception/lidar/tools:offline_lidar_obstacle_perception

**Expected behavior**
Build Ok!

![(OIMTV01HO1%AK{)KMZSCSE](https://user-images.githubusercontent.com/49785444/108583758-e9284e00-7376-11eb-8ee4-57f835b4fc9e.jpg)

**Desktop (please complete the following information):**
 - OS: ubuntu18.04
 - Version : Apollo 6.0

**Additional context**
this is the build file.
![image](https://user-images.githubusercontent.com/49785444/108583893-db26fd00-7377-11eb-96c7-fd4307172f42.png)

**Comment by storypku** [comment]
Hi @ypbbbbb , the BUILD file for offline_lidar_obstacle_perception is disabled since Apollo 6.0. 
And I don't know if the perception team has any plan to reactivate it. @jeroldchen @panfengsu

For the `pcl` part, just replace `@pcl` with `@local_config_pcl//:pcl`.

**Comment by ypbbbbb** [comment]
Thanks for your help! After  i replace @pcl ,it goes on. But it comes to another error:
![NV7W`4%U2)$MD_~)L2CPE`W](https://user-images.githubusercontent.com/49785444/108586799-a9b82c80-738b-11eb-80a7-040bf50f8547.png)
And i try to locate it :
![`M V1ROG2H%)A7WZKKK4AI9](https://user-images.githubusercontent.com/49785444/108586883-04ea1f00-738c-11eb-9f32-904a64b27902.png)
What  should i do? Maybe i need replace something again?

And "the BUILD file for offline_lidar_obstacle_perception is disabled since Apollo 6.0" ,so maybe i can build it with Apollo 5.5?

**Comment by storypku** [comment]
> Thanks for your help! After i replace @pcl ,it goes on. But it comes to another error:
> ![NV7W4%U2)$MD_~)L2CPEW](https://user-images.githubusercontent.com/49785444/108586799-a9b82c80-738b-11eb-80a7-040bf50f8547.png)
> And i try to locate it :
> ![`M V1ROG2H%)A7WZKKK4AI9](https://user-images.githubusercontent.com/49785444/108586883-04ea1f00-738c-11eb-9f32-904a64b27902.png)
> What should i do? Maybe i need replace something again?
> 
> And "the BUILD file for offline_lidar_obstacle_perception is disabled since Apollo 6.0" ,so maybe i can build it with Apollo 5.5?

I don't suggest you build it yourself in Apollo master. Reactivating this tool requires more work than just replace `pcl`. 
(You can compile with `bazel build --config=opt --config=gpu` if you want to dig into it. And maybe another problem.)

It seems that https://github.com/ApolloAuto/apollo/blob/r5.5.0/modules/perception/lidar/tools/BUILD is OK.

**Comment by ypbbbbb** [comment]
Thanks for your reply! I try to build it with apollo 5.5 and it is successful.
But when i run it ,it comes to an error:
![4HOCNLZ S~W}Z$)_6EMNCLP](https://user-images.githubusercontent.com/49785444/108597367-a9d41e80-73c3-11eb-8aae-f7eb409fae64.png)
What should i do? or maybe i need open a new issue?
I'm really appreciate you for helping me!

**Comment by ypbbbbb** [comment]
I run a command -- sudo chown 1000:1000 /apollo --，and now i can create logging file.
But the error is still existing:
![L100}UOA 2YDO1PYS8S`U~S](https://user-images.githubusercontent.com/49785444/108599688-93cb5b80-73cd-11eb-9d36-bd9d23575201.png)
And i find the cpp:
![X%$S0M7CXYOBB$~ O6(%%UC](https://user-images.githubusercontent.com/49785444/108599697-a2197780-73cd-11eb-8e6c-1a8ada86887b.png)
But i have no idea how to solve it. Can anyone help me?
