### ISSUE TITLE
potential memory leak in ncut cluster

### ISSUE THREAD

**Issue by muzi2045** [ApolloAuto/apollo#13456]
https://github.com/ApolloAuto/apollo/blob/6d1fdc530b98a18dd918a20a9410b336ae36be3d/modules/perception/lidar/lib/segmentation/ncut/ncut_segmentation.cc#L303

before push_back into outliers vector, there should be a vector clear opreator, otherwise there may be some memory leak.

**Comment by daohu527** [comment]
The **ObjectPtr is a c++ smart pointer**, and smart pointers are used to make sure that an object is deleted if it is no longer used. You don't need to delete the resource yourself then. So there's no memory leak.
```
using ObjectPtr = std::shared_ptr<Object>;
```

## example
You can assign values to smart pointers in the following ways
```
// Use make_shared function when possible.
auto sp1 = make_shared<Song>(L"The Beatles", L"Im Happy Just to Dance With You");

// Ok, but slightly less efficient. 
// Note: Using new expression as constructor argument
// creates no named variable for other code to access.
shared_ptr<Song> sp2(new Song(L"Lady Gaga", L"Just Dance"));

// When initialization must be separate from declaration, e.g. class members, 
// initialize with nullptr to make your programming intent explicit.
shared_ptr<Song> sp5(nullptr);
//Equivalent to: shared_ptr<Song> sp5;
//...
sp5 = make_shared<Song>(L"Elton John", L"I'm Still Standing");
```

Hope this helps you!

**Comment by muzi2045** [comment]
Yeah, the smart pointer is no problem.
But the definition in ncut_segmentation.h 
```
std::unique_ptr<std::vector<ObjectPtr>> _outliers;
```
it will be continue push ObjectPtr into the vector, and the resize operator
https://github.com/ApolloAuto/apollo/blob/a1f216e7bbebf19d2c120422dd15b5ff97b5c3c2/modules/perception/lidar/lib/segmentation/ncut/ncut_segmentation.cc#L380
looks like it can't resize the right object num in class vector when older Objects are no longer useful. 
(based on the setting num_threads = 1 )

@daohu527

**Comment by daohu527** [comment]
What do you mean by can't resize the correct object num ?
```
new_num_outliers = _outliers->size() + threads_outlier_pcs(0, num_threads - 1)
```
and then filled the `_outliers` array.

**Comment by muzi2045** [comment]
the new_num_outliers num will going increasing rather than maintain on a stable num. (threads = 1)

```
 std::vector<int> outlier_offset(num_threads,
                                  static_cast<int>(_outliers->size()));
 for (int i = 1; i < num_threads; ++i) {
    outlier_offset[i] = outlier_offset[i - 1] +
                        static_cast<int>(threads_outlier_pcs[i - 1].size());
 }
 int new_num_outliers =
     static_cast<int>(threads_outlier_pcs[num_threads - 1].size()) +
     outlier_offset[num_threads - 1];
 _outliers->resize(new_num_outliers);
```

**Comment by daohu527** [comment]
Let we take `threads = 1` for example 

below code will skip
```
 for (int i = 1; i < num_threads; ++i) {
    outlier_offset[i] = outlier_offset[i - 1] +
                        static_cast<int>(threads_outlier_pcs[i - 1].size());
 }
```
Then 
```
int new_num_outliers =
     static_cast<int>(threads_outlier_pcs[0].size()) + outlier_offset[0];
```
`outlier_offset[0]` size is `_outliers->size()` then the `new_num_outliers = _outliers->size() + threads_outlier_pcs[0].size() ` 


_outliers will resize to `_outliers->size() + threads_outlier_pcs[0].size()` which increase `threads_outlier_pcs[0].size()`.

Then
```

    int offset = outlier_offset[0];      // _outliers->size()
    for (size_t j = 0; j < threads_outlier_pcs[0].size(); ++j) {
      base::ObjectPtr& obj_ptr = (*_outliers)[offset + j];
      obj_ptr.reset(new base::Object);
      obj_ptr->lidar_supplement.cloud = *threads_outlier_pcs[i][j];
    }
```
It will fill `_outliers` with size `new_num_outliers `, so what's the problem???

**Comment by muzi2045** [comment]
![image](https://user-images.githubusercontent.com/12984898/108841925-7d164600-7613-11eb-86ff-5efa11142df3.png)

![Screenshot from 2021-02-23 20-12-51](https://user-images.githubusercontent.com/12984898/108842139-c9fa1c80-7613-11eb-8343-60accaecebb7.png)

![Screenshot from 2021-02-23 20-13-06](https://user-images.githubusercontent.com/12984898/108842157-d1b9c100-7613-11eb-8445-5bd59b0c4c28.png)

it will acting like below.
