### ISSUE TITLE
README.md 中硬件品牌拼写错误

### ISSUE THREAD

**Issue by LE2031** [ApolloAuto/apollo#13453]
README.md文件的Hardware Connection Overview图中，GPS Receiver品牌名称拼写为“Novotel”错误，应为「NovAtel」

<img width="876" alt="截屏2021-02-22 下午1 45 19" src="https://user-images.githubusercontent.com/25786841/108667594-88367c80-7514-11eb-8364-73c3e7503485.png">

**Comment by JackFu123** [comment]
Hi @LE2031 , we have made the change according to your advice. We will close the issue for now. If you have any additional questions, please feel free to open a new issue. Our engineer team is more than happy to help with that.

Thank you for supporting Apollo!
