### ISSUE TITLE
想问一下关于apollo里面pointpillars模型是怎么转成onnx的?apollo里面有转换脚本么?谢谢

### ISSUE THREAD

**Issue by zhangzhixiangah** [ApolloAuto/apollo#13486]
想问一下关于apollo里面pointpillars模型是怎么转成onnx的?apollo里面有转换脚本么?谢谢

**Comment by jeroldchen** [comment]
https://github.com/ApolloAuto/apollo/blob/295e13e9681c2a1776a60c6206437c61e2a176c8/modules/perception/lidar/lib/detection/lidar_point_pillars/point_pillars.cc#L470-L503
