### ISSUE TITLE
GPU for Apollo 6.0 

### ISSUE THREAD

**Issue by Thinsheep** [ApolloAuto/apollo#13488]
Hi,
It is just a basic question.
I plan to buy a new PC to install Apollo 6.0.
To running Apollo 6.0
What does it mean by " NVIDIA Turing GPU is strongly recommended"? Will RTX 3080/3090 GPUs are also good and do a better job than RTX 2080/2080 Ti?
Anyone know please give me a quick recommendation.
Thank you

**Comment by storypku** [comment]
RTX 30x0 series was only support in Apollo master.

**Comment by Thinsheep** [comment]
@storypku 
Thank you.
I plan to buy a PC for Apollo 6.0 installation. RTX 30x0 series is faster than RTX 20x0 Series. Would you recommend going with the RTX 30x0 series with Apollo Master or better go with the RTX 20x0 series? I am new to Apollo, I do not what advantages and disadvantages behind it.

**Comment by storypku** [comment]
Of course 30x0 series. Ampere support is ready in Apollo master now, and nowadays, DL models require much stronger computing power.

**Comment by Thinsheep** [comment]
There is a shortage of high end graphic cards Nvidia RTX 30x series at the moment. Does Apollo 6.0 supports AMD graphic cards also?

**Comment by storypku** [comment]
> There is a shortage of high end graphic cards Nvidia RTX 30x series at the moment. Does Apollo 6.0 supports AMD graphic cards also?

I am afraid not. The team didn't have AMD cards available.
