### ISSUE TITLE
想问一下你的pointpillars是在哪个框架下训练的以及怎么转成onnx的?谢谢

### ISSUE THREAD

**Issue by zhixiangzhangzstu** [ApolloAuto/apollo#13482]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by zhixiangzhangzstu** [comment]
就是想知道你的pointpillars是在哪个框架下训练的以及怎么转成onnx的?谢谢

**Comment by xiaoMrzhang** [comment]
@zhixiangzhangzstu 微信公众号Apollo开发者社区里面有篇文章《Apollo激光雷达感知技术解析》介绍了pointpillars模型线上部署相关信息，可以参考一下。训练框架应该是SECOND和mmdetection3D @panfengsu

**Comment by zhixiangzhangzstu** [comment]
谢谢,还是想问一下,pointpillars的模型是怎么转onnx的格式呀?
