### ISSUE TITLE
can't use cyber module,even if i source cyber/setup.bash

### ISSUE THREAD

**Issue by ypbbbbb** [ApolloAuto/apollo#13489]
can't use cyber module

bash docker/scripts/dev_into.sh
cyber_monitor
cyber_channel
both error 

**Screenshots**
![WNOHZY$@EJS0OTR7C4%LP R](https://user-images.githubusercontent.com/49785444/109407258-4c8b2f00-79ba-11eb-8329-782648ae1812.png)

**Desktop (please complete the following information):**
 - OS:ubuntu18.04
 - Version: Apollo5.5

**Comment by changsh726** [comment]
Have you build cyber?

**Comment by ypbbbbb** [comment]
i have run " bash apollo.sh build " and it displayed "build ok" . Maybe i should build again? but i am afraid of ruining some tools which have been built.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chang Songhong"<notifications@github.com&gt;; 
发送时间: 2021年3月1日(星期一) 下午2:54
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "bobo"<1714628670@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] can&#39;t use cyber module,even if i source cyber/setup.bash (#13489)





 
Have you build cyber?

**Comment by qwetqwe** [comment]
could you find bazel-bin/cyber/ in apollo directory

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
