### ISSUE TITLE
ModuleNotFoundError: No module named 'cyber'

### ISSUE THREAD

**Issue by guo-pu** [ApolloAuto/apollo#13493]
![image](https://user-images.githubusercontent.com/39380658/109477921-93a91b00-7ab3-11eb-88d9-95e3ce84855f.png)
How can we solve it?

**Comment by storypku** [comment]
Duplicate of #13187 . Please run `./bazel-bin/modules/tools/sensor_calibration/odom_publisher` instead.

**Comment by guo-pu** [comment]
thank ！！Ran successfully .

**Comment by guo-pu** [comment]
Will it compile after I modify the code of odom_publisher.py?

**Comment by guo-pu** [comment]
After I modified the code of odom_publisher.py; how to compile it?

**Comment by guo-pu** [comment]
@storypku  Thank ！！Ran successfully .
After I modified the code of odom_publisher.py; how to compile it?

**Comment by storypku** [comment]
Since `odom_publisher` is located under `modules/tools`, you can run `./apollo.sh build tools` to build all Bazel targets under `modules/tools`.

**Comment by guo-pu** [comment]
Thank！！

**Comment by guo-pu** [comment]
@storypku  Thank！！

**Comment by storypku** [comment]
Hi @guo-pu , this issue is going to be closed now. If you have other questions, feel free to open another issue. Thank you.
