### ISSUE TITLE
No module named 'std_msgs'

### ISSUE THREAD

**Issue by guo-pu** [ApolloAuto/apollo#13501]
![image](https://user-images.githubusercontent.com/39380658/109583576-0f01df80-7b3b-11eb-9346-efcf3e8dbe87.png)
from std_msgs.msg import  String     
ModuleNotFoundError: No module named 'std_msgs

How can we solve it?

**Comment by lx18233184051** [comment]
maybe you can try pip install ?

**Comment by guo-pu** [comment]
@lx18233184051  Thank!!  std_msgs is the ROS definition information type. Need me to customize the protobuf format.
