### ISSUE TITLE
Some wrong about PadMessage in teleop.cc file ?

### ISSUE THREAD

**Issue by devynliu** [ApolloAuto/apollo#13508]
hello ,i find a question in in teleop.cc 479 and 486.
code [link:](https://github.com/ApolloAuto/apollo/blob/13813a256e484ddad62fea627f127d2328d9e547/modules/dreamview/backend/teleop/teleop.cc#L486)
```
void TeleopService::SendEstopCmd() {
  AINFO << "Pull over";
  PadMessage pad_msg;
  pad_msg.set_action(DrivingAction::PULL_OVER);
  pad_message_writer_->Write(pad_msg);
}

void TeleopService::SendPullOverCmd() {
  AINFO << "EStop";
  PadMessage pad_msg;
  pad_msg.set_action(DrivingAction::STOP);
  pad_message_writer_->Write(pad_msg);
}
```

here code is right? Please tell me why?

**Comment by daohu527** [comment]
It's may be a mistake!!! Need to fix it

**Comment by daohu527** [comment]
@qilinhu Please help to fix this problem
