### ISSUE TITLE
Does the control module consider the slow response of the chassis steering mechanism?

### ISSUE THREAD

**Issue by JackRen88** [ApolloAuto/apollo#13503]
Hello,apollo team
The slow execution response of the chassis steering mechanism will affect the trajectory tracking accuracy.Does the control module in apollo consider the slow response of the chassis steering mechanism?

**Comment by qwetqwe** [comment]
May you need to change planning to generate a more slower trajectory in large curvature position. so you can change parameter and give a larger kappa_penalty_weight in speed optimizer:
default_task_config: {
  task_type: PIECEWISE_JERK_SPEED_OPTIMIZER
  piecewise_jerk_speed_optimizer_config {
    acc_weight: 1.0
    jerk_weight: 3.0
    kappa_penalty_weight: 2000.0
    ref_s_weight: 10.0
    ref_v_weight: 10.0
  }
}

**Comment by JackRen88** [comment]
Thank you for your patience.
 Our chassis steering is hydraulic, so the response of the chassis steering actuator is very slow, even if it is tracking a straight line, the vehicle will appear to travel in a serpentine manner.
Is there any content in the apollo control module that can solve this problem?

**Comment by haina0421** [comment]
Maybe you could refer MRAC controller in Apollo
