### ISSUE TITLE
IMU 2 CAR rotation matrix problem

### ISSUE THREAD

**Issue by lhcalibur** [ApolloAuto/apollo#13512]
In modules\perception\camera\tools\offline\visualizer.cc, the ex_imu2car_ matrix is rotate clockwise 90 degress, shouldn't it be counterclockwise?
I think it should be: 

     
![image](https://user-images.githubusercontent.com/13448022/109793895-31d1e800-7c50-11eb-8a3d-9d923b4171a6.png)

In code, it's:

![image](https://user-images.githubusercontent.com/13448022/109792079-1960ce00-7c4e-11eb-9570-31eec6807aa7.png)

### System information

- **Apollo version (3.5, 5.0, 5.5, 6.0)**: r6.0.0

**Comment by JeffYoung17** [comment]
In my way of understanding it, the car frame rotates **+90 degrees counterclockwise** to imu frame, so the rotation matrix of ex_imu2car is:
cos(-90) sin(-90) 0
sin(-90) cos(-90) 0
0           0            1
In code, you can think the car frame rotates **-90 degree clockwise**, so the rotation matrix also can be written as:
cos(90) sin(90)  0
-sin(90) cos(90) 0
0           0           1 
You can refer to wikipedia: https://en.wikipedia.org/wiki/Rotation_matrix#Direction

**Comment by JeffYoung17** [comment]
In your picture: the left is imu frame, the right is car frame?
In my used way of understanding it, the (base frame)car frame rotates **-90 degrees counterclockwise** to imu frame(which is called  extrinsic of imu2frame, although it is confused), so the rotation matrix of ex_imu2car is:
cos(-90) -sin(-90) 0
sin(-90) cos(-90) 0
0           0            1
In code, you can think the car frame rotates **+90 degree clockwise**, so the rotation matrix also can be written as:
cos(90) sin(90)  0
-sin(90) cos(90) 0
0           0           1 
You can refer to wikipedia: https://en.wikipedia.org/wiki/Rotation_matrix#Direction

**Comment by lhcalibur** [comment]
> In your picture: the left is imu frame, the right is car frame?
> In my used way of understanding it, the (base frame)car frame rotates **-90 degrees counterclockwise** to imu frame(which is called extrinsic of imu2frame, although it is confusing), so the rotation matrix of ex_imu2car is:
> cos(-90) -sin(-90) 0
> sin(-90) cos(-90) 0
> 0 0 1
> In code, you can think the car frame rotates **+90 degrees clockwise**, so the rotation matrix also can be written as:
> cos(90) sin(90) 0
> -sin(90) cos(90) 0
> 0 0 1
> You can refer to wikipedia: https://en.wikipedia.org/wiki/Rotation_matrix#Direction

Hi, 
Thanks for your replay, I find it's rotation of coordination system diff from rotation of object...
