### ISSUE TITLE
Multiple Planning Modules

### ISSUE THREAD

**Issue by fedlucchetti** [ApolloAuto/apollo#13517]
I would like, for purely experimental reasons, create multiple copies of the original apollo Planning module and run them in parallel. How would I proceed? Since the Planning module feeds directly to the Control module, I would then just simply average the outputs of the replicated Planning modules inside the Control module. 
Any suggestions? 

Thnak you for your help.

**Comment by lx18233184051** [comment]
You need to create some planning componment, and planning message send through cyber channel, you need to receive in control module and process them. More please read cyber doc.

**Comment by JackFu123** [comment]
The most direct method is to create another planning_copy component. For the output, you can simply filter the copied ones by changing their topic name. (Thus control won't use them.)

**Comment by fedlucchetti** [comment]
Okay thx for your suggestions. My aim here is to tell the control module to process the outputs of the two replicated Planning modules outputs (for example filter out the output that came with a delayed timestamp )

So practically speaking, I have two option:


 **Option 1: Directly modify the apollo docker image**
In the `apollo/modules/planning/` folder

- i would create `planning_component_copy.cc` with its corresponding header files
- create a new `BUILD` file that tells bazel to consider the newly created copy when building

Then, in the `apollo/modules/control/` folder (not sure how to exactly implement this part)

- I would edit come line of code in  `control_component.cc` that tells the Control module to read out the original Planning Module and the copied Planning module outputs 
- Filter one of the Planning outputs (as @JackFu123  suggested)

 **Option 2: Use CyberRT**

Following  @lx18233184051 I read the documentation, and seems to be pretty  straightforward. I managed to create multiple communication cyber channels by creating multiple nodes, however I don't know how to create multiple modules (in my case multiple Planning modules)


Thank you

**Comment by fedlucchetti** [comment]
Has anyone any suggestions on this topic? I am completely lost in trying to implement one of the options above. From the documentation alone, it's not very clear what the purpose of CyberRT is in trying to interface it with Apollo. Examples given in the documentation only reduce to simple back-and-forth messages via a particular channel between progamms (listener-talker).

At this point, could maybe somebody point me to a more practical example that would help me out in trying to understand CyberRT? For example, how would one read out the `ADCTrajectory` output by the Planning module? Following CyberRT documentation I would have to start with this template.


`int main(int argc, char* argv[]) {
  // init cyber framework
  apollo::cyber::Init(argv[0]);
  // create listener node
  auto listener_node = apollo::cyber::CreateNode("listener");
  // create listener
  auto listener =
      listener_node->CreateReader<apollo::cyber::examples::proto::Chatter>(
          "channel/chatter", MessageCallback);
  apollo::cyber::WaitForShutdown();
  return 0;
}`

I guess I would have to replace the channel name `channel/chatter` by something pointing to the Planning module channel?
