### ISSUE TITLE
Question about hardware support 

### ISSUE THREAD

**Issue by insa2020** [ApolloAuto/apollo#13514]
Hello team,

I would like to buy a laptop pc to test apollo 2.5 above and I don't really know the requirements in terms of GPU, video memory and RAM memory ....

I plan to take a gaming PC with an **RTX 2060, 16 GB RAM, 512 GB SSD** and test **Apollo 2.5** on it. 

_**Can you confirm that this machine has the characteristics necessary to run Apollo 2.5 ???**_

Thank you in advance for your answer.

**Comment by storypku** [comment]
For Apollo 6.0 and master, RTX 2060 is sufficient to run.  
I am afraid that Apollo 5.5 and below may not work well with 2060 however.

@jinghaomiao @Capri2014 @xiaoxq Do you know the GPU support status of Apollo 5.5- ?

**Comment by insa2020** [comment]
Thanks for the feedback, I suspected that the architecture is recent to work with the old versions of Apollo.

**Comment by storypku** [comment]
Hi @insa2020, I am going to close this issue for now. If you have other questions, feel free to open another issue. Thanks for supporting Apollo.
