### ISSUE TITLE
Lidar Perception Fails - cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#13522]
Lidar perception seems to be failing on recent master.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04 with Quadro M5000M GPU
- **Apollo installed from (source or binary)**:Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0
- **Output of `apollo.sh config` if on `master` branch**:

[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-03-04-6f4ea1af43
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210204_2153
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Run cyber_launch start modules/perception/production/launch/perception_lidar.launch

### Supporting materials (screenshots, command lines, code/script snippets):
[sagarw20@in-dev-docker:/apollo]$ cyber_launch start modules/perception/production/launch/perception_lidar.launch
[cyber_launch_2624] INFO Launch file [/apollo/modules/perception/production/launch/perception_lidar.launch]
[cyber_launch_2624] INFO ========================================================================================================================
[cyber_launch_2624] INFO Load module [perception_lidar] library: [perception_lidar] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag] exception_handler: []
[cyber_launch_2624] INFO Start process [perception_lidar] successfully. pid: 2631
[cyber_launch_2624] INFO ------------------------------------------------------------------------------------------------------------------------
[perception_lidar]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_lidar]  I0306 00:47:21.203963  2631 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag -p perception_lidar -s CYBER_DEFAULT 
[perception_lidar]  I0306 00:47:21.204242  2631 global_data.cc:153] []host ip: 10.0.0.91
[perception_lidar]  I0306 00:47:21.204890  2631 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception_lidar, has 1 dag conf
[perception_lidar]  I0306 00:47:21.204897  2631 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag
[perception_lidar]  terminate called after throwing an instance of 'thrust::system::system_error'
[perception_lidar]    what():  radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal
[cyber_launch_2624] ERROR Process [perception_lidar] has died [pid 2631, exit code -6, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag -p perception_lidar -s CYBER_DEFAULT].
[cyber_launch_2624] INFO All processes has died.
[cyber_launch_2624] INFO Cyber exit.
[cyber_launch_2624] INFO All processes have been stopped.

Can you please help?

**Comment by storypku** [comment]
Hi @agarwalsid , I checked from https://developer.nvidia.com/zh-cn/cuda-gpus , and find that Quadro M5000M was shipped with CUDA compute capability 5.0.  Considering that it's a rather old GPU model,  and we have shifted to CUDA 11.1 in master recently.  Does it matter? FYI, libtorch was built for SM=5.2 and above.

As far as the thrown exception is concerned, could you check where the exeception is thrown ? @panfengsu @jeroldchen

**Comment by agarwalsid** [comment]
@storypku, getting the same error with Quadro RTX 3000 which is SM>5.2. There is no .INFO file produced, making it harder to debug. Anything else we can do?

**Comment by storypku** [comment]
> @storypku, getting the same error with Quadro RTX 3000 which is SM>5.2. Anything else we can do?

Hi @agarwalsid , according to @jeroldchen , this bug was caused by upstream CUDA toolkit ( thrust included). And the team is working on this issue these days. Please stay tuned.

**Comment by agarwalsid** [comment]
@storypku @jeroldchen  thank you! Looking forward to the fix.
