### ISSUE TITLE
新的IMU型号怎么加入到apollo中？Novatel-G370N

### ISSUE THREAD

**Issue by ZMHSQ** [ApolloAuto/apollo#13531]
使用PP7D-E2组合导航，IMU型号是G370N

Could you share specific model with us ?

We currently use the following IMUs. We'll extend this list when a new IMU is introduced.
```proto
enum ImuType {
 
  IMAR_FSAS = 13;       // iMAR iIMU-FSAS
  ISA100C = 26;         // Northrop Grumman Litef ISA-100C
  ADIS16488 = 31;       // Analog Devices ADIS16488
  STIM300 = 32;         // Sensonor STIM300
  ISA100 = 34;          // Northrop Grumman Litef ISA-100
  ISA100_400HZ = 38;    // Northrop Grumman Litef ISA-100
  ISA100C_400HZ = 39;   // Northrop Grumman Litef ISA-100
  G320N = 40;           // EPSON G320N
  CPT_XW5651 = 41;      // IMU@SPAN-CPT, and XingWangYuda 5651
  UM442 = 42;           // UM442
}
```

**How to adapt PP7/new GPS/IMU model?**

if your device is a recommended PP6 or compatible PP7 Etc., you can do seamless support, modify the configuration file on,We will copy `modules/calibration/data/<vehicle>/gnss_params/gnss_conf.pb.txt` to `modules/drivers/gnss/conf/gnss_conf.pb.txt`, and then select the appropriate vehicle in Dreamview.

Then check the relevant topic output.

_Originally posted by @mickeyouyou in https://github.com/ApolloAuto/apollo/issues/4915#issuecomment-404082689_

**Comment by daohu527** [comment]
You can refer to  "modules/drivers/gnss". It is a combined navigation, you can access it through serial port or socket

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
