### ISSUE TITLE
Teleop can't get into AUTO mode, and no valid control signals in CAN bus

### ISSUE THREAD

**Issue by Shen-Kirren** [ApolloAuto/apollo#13540]
### System information

- **Linux Ubuntu 18.04
- **Apollo installed from source
- **Apollo version 5.5
- **IPC with intel CPU, and no NVIDIA GPU
- **EMUC B202 Socket CAN card

### Problem 
- when I type "m"+"1" in teleop's comand line, I can't change drive mode into AUTO, still compelete_manual 
- control has some steer and motor message, but in CAN bus, all control signals are sending 00 00 00 00 00 00 00 00

### Steps to start apollo docker:
- **After getting in the apollo docker and booting socket CAN card, I start with
- bash scripts/bootstrap.sh
- bash scripts/canbus.sh
- bash scripts/canbus_teleop.sh
- **Then I creat a new terminator, get into apollo docker, type below for show chassis_detail
- source cyber/setup.bash
- cyber_monitor

### Supporting materials :
start vehicle and check response for vcu/eps/esp_online
![image](https://user-images.githubusercontent.com/53684432/110732817-d9a67180-825f-11eb-879f-7c28c5d68093.png)
recieve feedback signals
![image](https://user-images.githubusercontent.com/53684432/110733506-0a3adb00-8261-11eb-92be-4811276c4995.png)

**Comment by daohu527** [comment]
seems you need to check the canbus config in
https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/canbus/conf/canbus_conf.pb.txt#L7-L12

there're four types
```
    FAKE_CAN
    ESD_CAN
    SOCKET_CAN_RAW
    HERMES_CAN
```

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
