### ISSUE TITLE
camera/tools/obstacle_detection:obstacle_detection: Get instance YoloObstacleDetector failed.

### ISSUE THREAD

**Issue by lhcalibur** [ApolloAuto/apollo#13553]
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: r5.5.0

I build with **bazel build -c opt //modules/perception/camera/tools/obstacle_detection:obstacle_detection** and run **bazel-bin/modules/perception/camera/tools/obstacle_detection/obstacle_detection**

Got E0314 23:08:50.629729 224473 base_obstacle_detector.h:60] []Get instance YoloObstacleDetector failed.:
![image](https://user-images.githubusercontent.com/13448022/111073585-48165880-851a-11eb-815f-ba8cf57aecb9.png)

**Comment by Egozjuer** [comment]
I have the same question.who can tell me how to do?

**Comment by Egozjuer** [comment]
@storypku

**Comment by daohu527** [comment]
we will fix it soon
