### ISSUE TITLE
./docker/scripts/dev_start.sh 出错

### ISSUE THREAD

**Issue by xhaoAI** [ApolloAuto/apollo#13557]
what should I do？
I have installed  nvdia-driver（450.102），docker，nvidia-docker，nvidia-container-toolkit
But， when typing ./docker/scripts/dev_start.sh ， errors occurs below：
![apollo](https://user-images.githubusercontent.com/59948978/111162577-3ba40580-85d7-11eb-8ff4-1eb62e4c6304.jpg)

**Comment by xhaoAI** [comment]
> Your Nvidia driver is not high enough to run CUDA 11.1 based Docker images.
> 
> Please upgrade Nvidia driver >= 455.32. Generally, the higher, the better.

Thanks！This really helps me out!

**Comment by storypku** [comment]
Hi @xhaoAI， this issue is going to be closed now. Don't hesitate to open another issue if you have other questions. 
Thanks for supporting Apollo!
