### ISSUE TITLE
Can't run perception module on local computer as expected

### ISSUE THREAD

**Issue by lhcalibur** [ApolloAuto/apollo#13552]
Version: r5.5.0
I follow this instruction: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md
I set enable_visualization:true and write_visual_img:true in **modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt**
![image](https://user-images.githubusercontent.com/13448022/111069542-8571ea80-8508-11eb-950a-4b9ad529bf2e.png)

After I lanuch perception module use command: **cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch** , and run: **cyber_recorder play -f demo_3.5.record -r 0.2** , I can't find anything in folder: "debug_output/" 

I find that in "demo_3.5.record", there is no data in channel "/apollo/sensor/camera/front_12mm/image", Is this the problem why no camera perception algorithm is running? Can  Apollo supply a sample record with raw input?
![image](https://user-images.githubusercontent.com/13448022/111071241-2ca65000-8510-11eb-91e3-f1e4fe387dbb.png)

![image](https://user-images.githubusercontent.com/13448022/111069396-dc2af480-8507-11eb-951d-bcd67f1216cc.png)
![image](https://user-images.githubusercontent.com/13448022/111069521-62dfd180-8508-11eb-8674-cdf863b43514.png)
![image](https://user-images.githubusercontent.com/13448022/111069783-a0912a00-8509-11eb-9370-5f2f6af0759f.png)

**Comment by HUI11126** [comment]
Hello. Have you solved the problem?  

I use front_6mm.  The debug_output folder is empty after I run the camera perception.

**Comment by rzr900ipl** [comment]
hi  @lhcalibur
Did you solve the problem ?

**Comment by daohu527** [comment]
demo_3.5.record is just for display, which don't have camera and lidar raw data
