### ISSUE TITLE
Segmentation fault (core dumped) then run NDT localization

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#13558]
Hi team!  

Help me if you can. 

I am trying to run ndt localization.
But I get the following error **Segmentation fault (core dumped)**.
It looks like it appears in this [place]( https://github.com/ApolloAuto/apollo/blob/4be3522b627f8d6b6084d7df398ff1823836242b/modules/localization/msf/local_pyramid_map/base_map/base_map_node.cc#L288)  
**Maybe someone has some ideas?**

**Comment by AlexandrZabolotny** [comment]
But to be more precise, the error occurs at this [function](https://github.com/ApolloAuto/apollo/blob/4be3522b627f8d6b6084d7df398ff1823836242b/modules/localization/msf/local_pyramid_map/ndt_map/ndt_map_matrix.cc#L48). Probably my file format is not correct.
Can anyone suggest how to check the correctness of the map ??

**Comment by blacksheep0303** [comment]
@AlexandrZabolotny 
I'm sorry to bother you. I'd like to ask you that did you solve this problem?
I use apollo6.0 and run "cyber_launch start ndt_localization.launch ".And I get the same error "Segmentation fault (core dumped)".
I think maybe it's not the problem of the map , because I use the same ndt_map in apollo5.0 and ndt_localization works well .
My situation is the process stop every time when the callback func is executed. 
So can you use ndt_localization in apollo 6.0 now ? If you can ,could you please tell me how to use it ?
I'm really appreciate for your help!

**Comment by marf-cn** [comment]
@AlexandrZabolotny @blacksheep0303 
I also got same issue, any suggestion for it?
Appreciate for your help!

**Comment by daohu527** [comment]
It looks like a format problem, have you tried to regenerate the map in version 6.0?

**Comment by AlexandrZabolotny** [comment]
> It looks like a format problem, have you tried to regenerate the map in version 6.0?

I am creating a map in pre6 version.
And get next errors

shatl@in_dev_docker:/apollo$ mainboard -d /apollo/modules/localization/dag/dag_streaming_ndt_localization.dag
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1012 14:43:26.930702 12437 module_argument.cc:81] []command: mainboard -d /apollo/modules/localization/dag/dag_streaming_ndt_localization.dag 
I1012 14:43:26.931145 12437 global_data.cc:155] []host ip: 10.152.1.30
I1012 14:43:26.931326 12437 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I1012 14:43:26.931335 12437 module_argument.cc:60] []dag_conf: /apollo/modules/localization/dag/dag_streaming_ndt_localization.dag
E1012 14:43:27.996141 12437 base_map.cc:102] [mainboard]/apollo/modules/localization/map/ndt_map/map/config.xml
E1012 14:43:28.990384 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.990486 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.990543 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.990602 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.996131 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.996186 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.996245 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.996290 12447 base_map.cc:142] [mainboard]Preload map node failed!
E1012 14:43:28.996345 12447 base_map.cc:142] [mainboard]Preload map node failed!

**Comment by AlexandrZabolotny** [comment]
@daohu527 
Is there a way to use [this](https://github.com/daohu527/ndt_mapping) tool to build a map in Apollo?

**Comment by AlexandrZabolotny** [comment]
> @AlexandrZabolotny I'm sorry to bother you. I'd like to ask you that did you solve this problem? I use apollo6.0 and run "cyber_launch start ndt_localization.launch ".And I get the same error "Segmentation fault (core dumped)". I think maybe it's not the problem of the map , because I use the same ndt_map in apollo5.0 and ndt_localization works well . My situation is the process stop every time when the callback func is executed. So can you use ndt_localization in apollo 6.0 now ? If you can ,could you please tell me how to use it ? I'm really appreciate for your help!

I have the same problem for Apollo 5

**Comment by gunsand** [comment]
亲们 我想问下关于ndt localization 哪个版本是好用的？ 我适配一下。msf那个定位地图离线怎么制作呢？ 感觉基本没有解决阿。
