### ISSUE TITLE
How to measure perception module delay

### ISSUE THREAD

**Issue by opus23** [ApolloAuto/apollo#13550]
Hello apollo team, I want to measure perception module delay with obstacle.
Because I use remote server, I can use dreamview only. (it is hard to use LGSVL.)

1. what is the difference between Module Delay and Latency in PNC monitor? In demo_3.5.record, they have different values. Even in my simulation, PNC monitor has not been printed.
<img width="844" alt="cant_print_latency" src="https://user-images.githubusercontent.com/59497518/110909665-b3fa9480-8353-11eb-9dbf-d7d67f6f772c.PNG">

2. PerceptionObstacle in Module Delay is printed if I turn on 'third party perception module', not 'perception module'. But isn't the third party perception module are the module of the old version? How to measure the delay of perception module?

3. If I follow this steps, the obstacles appear. But they are gone if I turn on the third party perception module. I followed this steps. How to set obstacle at the same time that the perception module delay is measured?
- bazel build modules/tools/perception:replay_perception
- bash modules/tools/perception/garage_perception.bash

4. If my way is wrong, is there another way to find perception module delay? How would I run the perception module separately without simulator? Thanks!

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: git clone https://github.com/ApolloAuto/apollo.git
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- bootstrap.sh start
- bridge.sh

- select vehicle and map in dreamview(Lincoln2017MKZ LGSVL, Borregas Ave)

(in another terminal)
- bazel build modules/tools/perception:replay_perception
- bash modules/tools/perception/garage_perception.bash

- toggle sim_control and modules.

**Comment by opus23** [comment]
I found it :)

**Comment by kontonpuku** [comment]
Hi, have you figured out what is the difference between Module Delay and Latency in PNC monitor? And how are the module delays monitored in CyberRT?

**Comment by daohu527** [comment]
They describe different things
- Module Delay shows the delay of the module
- Latency is an indicator of the control module

**Comment by kontonpuku** [comment]
Thanks a lot for the reply. 
But according to https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/docs/specs/dreamview_usage_table.md, 
It seems that the module delay refers to message delay while the latency corresponds to actual module latency.  

Some sentences from that link:
"Module Delay: the time delay between two messages for each topic;"
"The graph displays the difference in time when the module receives sensor input data to when it will publish this data."

**Comment by daohu527** [comment]
Yeah, I see!

They are the same indicator.
