### ISSUE TITLE
How to find out which runtime-deps needed after installing a package?

### ISSUE THREAD

**Issue by gsa88** [ApolloAuto/apollo#13560]
From this snippet:
https://github.com/ApolloAuto/apollo/blob/8744690cddcf1c74d1c088d3f5f2dd28b069f78d/docker/build/installers/install_pcl.sh#L143
how to find out which runtime-deps are required for pcl?

**Comment by storypku** [comment]
> From this snippet:
> https://github.com/ApolloAuto/apollo/blob/8744690cddcf1c74d1c088d3f5f2dd28b069f78d/docker/build/installers/install_pcl.sh#L143
> 
> 
> how to find out which runtime-deps are required for pcl?

Apollo differentiate build-deps and runtime-deps of package installation. After the package has been installed into the system,  system packages which belong to build-deps were removed first.  Then `ldd` was run on the package's binaries and shared libraries to find missing  `*.so` deps.  Eg. `ldd /opt/apollo/sysroot/bin/pcl_* | grep "Not found"`.
You can then use `dpkg`/`apt`  from another Docker image with build-deps to locate the packages which provides the missing shared libraries, or just some google-fu.

The idea of build-deps and runtime-deps was borrowed from Linux distros like Debian/Ubuntu and Fedora, which provided `mypkg` and `mypkg-dev` (or `mypkg-devel`).


Hope my answer helps.

**Comment by gsa88** [comment]
> > From this snippet:
> > https://github.com/ApolloAuto/apollo/blob/8744690cddcf1c74d1c088d3f5f2dd28b069f78d/docker/build/installers/install_pcl.sh#L143
> > 
> > how to find out which runtime-deps are required for pcl?
> 
> Apollo differentiate build-deps and runtime-deps of package installation to reduce Docker image size. After the package has been installed into the system, system packages which belong to build-deps were removed first. Then `ldd` was run on the package's binaries and shared libraries to find missing `*.so` deps. Eg. `ldd /opt/apollo/sysroot/bin/pcl_* | grep -i "not found"`.
> You can then use `dpkg`/`apt` from another Docker image with build-deps to locate the packages which provides the missing shared libraries, or just some google-fu.
> 
> The idea of differentiating build-deps and runtime-deps was borrowed from Linux distros like Debian/Ubuntu and Fedora, which provided `mypkg` and `mypkg-dev` (or `mypkg-devel`).
> 
> Hope my answer helps.

Thanks, your answer helped me understand.
