### ISSUE TITLE
Failed to compile Apollo  6 in docker

### ISSUE THREAD

**Issue by JIANGZhengm** [ApolloAuto/apollo#13564]
I installed apollo 6 according to the official website tutorial. The docker environment has been configured and can be accessed, but when executing the compilation command “./apollo.sh build”, the following error is prompted:

![2021-03-16 18-10-36 的屏幕截图](https://user-images.githubusercontent.com/38940634/111292228-ede4d700-8682-11eb-8545-780e03024b47.png)
How can i fix it？, thanks

**Comment by storypku** [comment]
Download  the `go1.12.5.linxu-amd64.tar.gz` package manually, and put it under <APOLLO_ROOT_DIR>/.cache/distdir.

**Comment by storypku** [comment]
Duplicate issue closed.
