### ISSUE TITLE
关于激光雷达使用问题

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#1356]
您好，
  我们现在有一些单线激光雷达，想问下是否可以在apollo系统中使用，也就是代替原64线的；然后如果可以的话，除了驱动需要修改之外，还需要修改哪些？

**Comment by quning78** [comment]
目前只有Velodyne 64线和16线的支持，如果需要加入其他的单线雷达，需要保证对外的 interface 一致，同时加入相应的外参文件

**Comment by ahuer2435** [comment]
如果配置做好后，然后将z轴数据填充0，再保持话题/apollo/sensor/velodyne64/VelodyneScanUnified 接口不变，是否就可以使用了？

**Comment by ahuer2435** [comment]
了解，问下如果采用其他厂家16线雷达，然后也能发出[sensor_msgs/PointCloud2]结构的数据，除了驱动和硬件配置修改之外，apollo后续的模块是否不需要修改就可以使用？后续的模块是指perception，prediction，planning等。

**Comment by gengqx** [comment]
我个人觉得percetion模块看似可以正常运行，但是由于其使用了FCN的网络，当64线被替换成16线时，线会变得稀疏，特征可能会发生变化，导致检测效果变差，但尚未测试。

**Comment by ahuer2435** [comment]
@gengqx 应该是的。我们现阶段是想先把系统跑起来，所以首先要把各个数据接口对上，所以暂时先不考虑效果和性能。

**Comment by XiangjiBU** [comment]
> @gengqx 应该是的。我们现阶段是想先把系统跑起来，所以首先要把各个数据接口对上，所以暂时先不考虑效果和性能。

请问用你用单线的激光雷达可行吗？
