### ISSUE TITLE
How to do Apollo valet parking

### ISSUE THREAD

**Issue by qiongwu1003** [ApolloAuto/apollo#13571]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

### Steps to reproduce the issue:
- **LGSVL simulator(2020.06) + Apollo + AutonomousStuff Parking lot map**
- **Generate a route to an open parking space**

The up steps do not work. Could someone tell me how to do the valet parking thing or if there is some instructions?
I have searched for "parking" in the issues, but I did not find how to solve the problem. 

Thank you in advance.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
