### ISSUE TITLE
Apollo

### ISSUE THREAD

**Issue by hxj0316** [ApolloAuto/apollo#13572]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by hxj0316** [comment]
系统信息Linux Ubuntu 18.04）：
阿波罗版本：5.5
具体问题：
再执行官方教程中的显卡驱动安装时，执行完cat /proc/driver/nvidia/version，显示有430.50的字样；但是接着执行sudo dpkg --list | grep nvidia*，却没有任何输出，且在终端输入nvidia-smi，最下面一行出现出现No running processes found的相关字样，且输入nvidia-settings也无法调出显卡驱动安装界面。我已经反复试过很多次了，一直如此，希望大家能帮助我。谢谢~
![QQ图片20210317093304](https://user-images.githubusercontent.com/66103957/111401729-d1897e80-8704-11eb-947b-ca6d1b22aa4e.jpg)
![QQ图片20210317093252](https://user-images.githubusercontent.com/66103957/111401734-d3ebd880-8704-11eb-8cbd-4900a658a3c2.jpg)
![QQ图片20210317093258](https://user-images.githubusercontent.com/66103957/111401741-d77f5f80-8704-11eb-8881-9605d66e17d9.jpg)

**Comment by diegohu** [comment]
您参考的是Apollo开发套件产品文档，如果您购买了该产品，可以通过以下入口获取技术支持 http://ufo.baidu.com/listen/myhistory?type=commonQA&product_line=90965&appid=240308#?qid=186
