### ISSUE TITLE
An error occurred during the fetch of repository 'remotejdk11_linux'

### ISSUE THREAD

**Issue by frindexzeng9032** [ApolloAuto/apollo#13582]
**Describe the bug**
I've successfully start Apollo Development Docker Container and enter, but while I execute the script of './apollo.sh build',  I met an error of remotejdk11_linux.

I doubt this issue is caused by network connection or checksum error mentioned in the error report, but I can't find the answer on the web. Please help!

**To Reproduce**
1. bash docker/scripts/dev_start.sh
2. bash docker/scripts/dev_into.sh
3. ./apollo.sh build
then met error and stop building.

**Screenshots**
![2021-03-18 23-43-49 的屏幕截图](https://user-images.githubusercontent.com/80774975/111655069-4adbbb00-8844-11eb-988a-edb3f9ba264a.png)

**Comment by storypku** [comment]
You can download the package from the url manually, and put it under `.cache/distdir`. Please refer to https://github.com/ApolloAuto/apollo/blob/master/docs/specs/bazel_in_apollo_an_overview.md.
