### ISSUE TITLE
Control MPC solve method

### ISSUE THREAD

**Issue by lycismail** [ApolloAuto/apollo#13589]
I wonder why use osqp method to solve the MPC matrix without build QP problem like before which used QPOASES and made an H & f with reference to matrix A and B. Now we just use matrix Q & P to solve. I can not understand the QP progress. Could u give me a reference, like a paper or something? Very appreciate！

**Comment by lycismail** [comment]
I comprehend it already. The solve method with osqp build the QP problem with x & u together. And make the A & B matrix into the equality constraint. The qpoases method before build the QP problem just with the input matrix u as the optimize variable.

**Comment by schweinebauch** [comment]
> I comprehend it already. The solve method with osqp build the QP problem with x & u together. And make the A & B matrix into the equality constraint. The qpoases method before build the QP problem just with the input matrix u as the optimize variable.

I encountered  the same question. In apollo mpc I could not find any code about prediction, in controller only matrix_ad_ and matrix_bd_ were calculated at time k, but no prediction future action and pass inot osqp.  Did you get the ider of these codes?

**Comment by DrShIkIgAmy** [comment]
> > I comprehend it already. The solve method with osqp build the QP problem with x & u together. And make the A & B matrix into the equality constraint. The qpoases method before build the QP problem just with the input matrix u as the optimize variable.
> 
> I encountered the same question. In apollo mpc I could not find any code about prediction, in controller only matrix_ad_ and matrix_bd_ were calculated at time k, but no prediction future action and pass inot osqp. Did you get the ider of these codes?

You may take a look at mpc_solver. It contains equality constraint matrix by which the relation Xk+1 = A*Xk+B*U is stated.

**Comment by lycismail** [comment]
> > > I comprehend it already. The solve method with osqp build the QP problem with x & u together. And make the A & B matrix into the equality constraint. The qpoases method before build the QP problem just with the input matrix u as the optimize variable.
> > 
> > 
> > I encountered the same question. In apollo mpc I could not find any code about prediction, in controller only matrix_ad_ and matrix_bd_ were calculated at time k, but no prediction future action and pass inot osqp. Did you get the ider of these codes?
> 
> You may take a look at mpc_solver. It contains equality constraint matrix by which the relation Xk+1 = A_Xk+B_U is stated.

That's the truth.
