### ISSUE TITLE
how to deploy my yolo obstacle detector 

### ISSUE THREAD

**Issue by MaxLin86** [ApolloAuto/apollo#13597]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: u1804
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I haved trained my yolo obstacle detector using Darknet framework.
But config in 'ApolloAuto/apollo/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector' make me confused.
How can I get 'deploy.pt' and 'deploy.model'? Are they Caffe format file?
If any model convert tools in the repo? 
THX!

**Comment by syn66** [comment]
Have you solved it？

**Comment by MaxLin86** [comment]
> Have you solved it？

no...

**Comment by daohu527** [comment]
You can follow this doc to add your models. https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README_paddle3D_CN.md
