### ISSUE TITLE
What is the vehicle center? how to find  front_edge_to_center & back_edge_to_center?

### ISSUE THREAD

**Issue by tanmoy-sabir** [ApolloAuto/apollo#13591]
How to calculate the following values? How is the centre defined for the vehicle?

  front_edge_to_center: 1.385
  back_edge_to_center: 0.405
  left_edge_to_center: 0.430
  right_edge_to_center: 0.430

**Comment by alexiskovi** [comment]
@tanmoy-sabir, the center here means the center of mass of your vehicle

**Comment by haina0421** [comment]
Center of the vehicle could be defined as you want. You just need to compensate the difference into your calibration.
The most often used center:
IMU; center of rear axle; Mass(hard to find)

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
