### ISSUE TITLE
Verbose information during the build process

### ISSUE THREAD

**Issue by lecoos** [ApolloAuto/apollo#13596]
Hi Experts

I am new to Apollo and I would like to know how to extract the detail build commands for each object.  I searched a lot of related documents. However, I didn't find the solution.

In other words, I would like to know the linked library, the compiling option, the optimization flags, etc. during the compiling process for each object (Like the verbose information in GCC/Clang).

Anyone know how to extract this information. Many Thanks

**Comment by daohu527** [comment]
It is auto generated by bazel, you can find the compile command in `xx.params` file. for example

```
bazel-bin/modules/control/control_component_test-2.params
```
