### ISSUE TITLE
Read ADC trajectory

### ISSUE THREAD

**Issue by fedlucchetti** [ApolloAuto/apollo#13599]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

From the documentation alone, it's (to mee) not very clear what the purpose of CyberRT is in trying to interface it with Apollo. Examples given in the documentation only reduce to simple back-and-forth messages via a particular channel between progamms (listener-talker).

At this point, could maybe somebody point me to a more practical example that would help me out in trying to understand CyberRT? For example, how would one read out the ADCTrajectory output by the Planning module? Following CyberRT documentation I would have to start with this template.

int main(int argc, char* argv[]) { // init cyber framework apollo::cyber::Init(argv[0]); // create listener node auto listener_node = apollo::cyber::CreateNode("listener"); // create listener auto listener = listener_node->CreateReader<apollo::cyber::examples::proto::Chatter>( "channel/chatter", MessageCallback); apollo::cyber::WaitForShutdown(); return 0; }

I guess I would have to replace the channel name channel/chatter by something pointing to the Planning module channel?
Any help would be appreciable.\

F>

**Comment by daohu527** [comment]
Yes, you need to modify both the topic and message type
1. modify the topic to "/apollo/planning"
2. modify the message type to "apollo::planning::ADCTrajectory"

```
DEFINE_string(planning_trajectory_topic, "/apollo/planning",
              "planning trajectory topic name");
```

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
