### ISSUE TITLE
Why doesn't it mention how to connect IPC's CAN to MKZ's CAN bus?

### ISSUE THREAD

**Issue by fengjin89** [ApolloAuto/apollo#136]
Hi,

I read the [Hardware Installation Guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_hardware_system_installation_guide.md#in-the-vehicle) but failed to find information how to connect IPC's CAN to MKZ's CAN bus. As far as I know, the vehicle should have a CAN bus interface to allow outside unit to control its brake and throttle system. I suppose that Apollo's IPC should connect to the vehicle's CAN bus then the algorithm on IPC can control vehicle. But I failed to find this.

And in this section [c. Connect the DB9 cable to the IPC to talk to the CAN (as shown):](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_hardware_system_installation_guide.md#in-the-vehicle), it shows IPC's CAN is connected to one CAN bus, but it doesn't show any more details. Is this the vehicle's ECU(engine control unit)'s CAN bus?

Thanks!

**Comment by aiguo159** [comment]
As stated in the Prerequisites section under "In the Vehicle":
The vehicle must be modified for “drive-by-wire” technology by a professional service company. Also, a CAN interface hookup must be provided in the trunk where the IPC will be mounted.

It is recommended to hire a "professional" to do this type of modification to enable controlling the vehicle via CAN interface. As part of the modification, CAN interface will be provided; you will then be able to connect it to the IPC. An example of such is the installation of an ADAS kit made by dataspeed (and their power distribution panel).

Currently we do NOT provide information on how to modify cars.

**Comment by fengjin89** [comment]
@aiguo159 I just want to verify if Apollo 1.0 realizes the simple ADAS which needs algorithm to control the vehicle. If the MKZ's CAN bus is connected to IPC's, it's possible that Apollo 1.0 has simple ADAS function. If no, I suppose like this, according to below information from [Overview of Apollo](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md)

*Apollo 1.0, also referred to as the Automatic GPS Waypoint Following, works in an enclosed venue such as a test track or parking lot. It accurately replays a trajectory and the speed of that trajectory that a human driver has traveled in an enclosed, flat area on solid ground.*

so does Apollo 1.0 just have replaying trajectory function and have no control of the vehicle's dynamics?

Thanks!

**Comment by Capri2014** [comment]
@fengjin89 1.0 is merely waypoint follower, meaning we record a trajectory, and replay it back so vehicle can drive exact same trajectory as the recorded one. And we do have control of vehicle's dynamics during this process.
