### ISSUE TITLE
How to add 3rd-party libs in apollo?

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#13605]
### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (6.0)**:
### Steps to reproduce the issue:
for example:
I wan
t to add `libA.so` in apollo,lib path is `/AA/libs/libA.so`,include path is `/AA/include/A.h`.
I make a dir in `/apollo/third_party`:`/apollo/third_party/a`. there are three files in dir a:`BUILD`,`a.BUILD`,`workspace.bzl`.
`BUILD`:
```bash
package(
    default_visibility = ["//visibility:public"],
)

```
`a.BUILD`:
```bash
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "a",
    includes = [
        "A.h",
    ],
    linkopts = [
        "-L/AA/libs",
        "-lA",
    ],
    linkstatic = False,
)
```
`workspace.bzl`:
```bash
"""Loads the a library"""
def clean_dep(dep):
    return str(Label(dep))


def repo():
    # a
    native.new_local_repository(
        name = "a",
        build_file = clean_dep("//third_party/a:a.BUILD"),
        # include path
        path = "/AA/include",
    )
```
in my component's BUILD file:
```bash
...
deps = [
        "//cyber",
        "@a",
    ],
...
```
in my `.cc` file:
```c++
#include "a/A.h"
```
build:`./apollo.sh build_cpu`
output:
```bash
no such package '@a//': The repository '@a' could not be resolved and referenced by '//modules/my_component:my_component_lib'
(09:39:49) ERROR: Analysis of target '//modules/my_component:my_component_lib' failed; build aborted: Analysis failed
```

**Comment by BigBenSure** [comment]
so, I want to know what I should do next...

**Comment by BigBenSure** [comment]
what doc should I read?

**Comment by MaxLin86** [comment]
maybe you can try gitee.

for example, replace my caff lib

`
# Caffe
#new_local_repository(
new_git_repository(
    name = "caffe",
    build_file = "third_party/caffe.BUILD",
    #path = "/usr/include/caffe",
    tag = "v0.0.1",
    remote = "https://gitee.com/maxlin86/caffe-apollo-yolo",
)`

**Comment by BigBenSure** [comment]
> maybe you can try gitee.
> 
> for example, replace my caff lib
> 
> #Caffe
> #new_local_repository(
> new_git_repository(
> name = "caffe",
> build_file = "third_party/caffe.BUILD",
> #path = "/usr/include/caffe",
> tag = "v0.0.1",
> remote = "https://gitee.com/maxlin86/caffe-apollo-yolo",
> )

thank you for your reply~ I use `cc_import`  to solve this problem.
