### ISSUE TITLE
How does QpSplineReferenceLineSmoother work?

### ISSUE THREAD

**Issue by ixanezis** [ApolloAuto/apollo#1360]
I've visualized what happens inside the `modules/planning/reference_line/qp_spline_reference_line_smoother_test.cc`:
https://plot.ly/~ixanezis/169/

The result looks suspicious: the original reference line is at least straight where it should have been straight. The smoothed version is very wavy and goes too far away from the original reference line. How can a car be driving along such line?

(I've used the `QpSplineReferenceLineSmoother` with values from `modules/planning/conf/planning_config.pb.txt`)

**Comment by lianglia-apollo** [comment]
The reference line smoother is to provide a parameterized function that in each direction the third order derivative is minimized. It is true that the smoothed line is wavy when the original one is straight --- but the smoothed one has larger curvature at the turning point.

**Comment by ixanezis** [comment]
For me, that looks unnatural. I wouldn't be turning left so much in advance, just to reduce the curvature at the turning point. Moreover, it would be strange to swing the car left-right on the straight line just in order to have a smaller curvature at the turning point.
I just can't imagine how this smoothing can be used in real world if it "smoothes" a pure straight piece of lane into a wavy road.

**Comment by lianglia-apollo** [comment]
It is true that a trade-off exists when we decide whether to pay more attention to smaller curvature or less deviation from driving straight. The deviation can be adjusted based on constraints.

**Comment by lianglia-apollo** [comment]
This link (https://www.kartworldbelmont.com.au/uncategorized/how-to-choose-the-best-driving-line/) might be helpful. The lines are for F-1 racing, and smoothness is the only target. Of course, we need to make trade-offs.
