### ISSUE TITLE
cyber的CyberRT_Quick_Start_cn.md

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#13606]
https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Quick_Start_cn.md
dag文件和launch文件里面的例子已经是错的了。

**Comment by daohu527** [comment]
I tested it and found no errors, Can you point out where is wrong?

**Comment by BigBenSure** [comment]
in dag file sample:
if I use `component_config`,`component_library`, when I run `mainboard -d XXX.dag`,error is:
`[libporotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:310] Error parsing text-format apollo.cyber.proto.DagConfig: 1:18: Mesasge type "apollo.cyber.proto/DagConfig" has no field named "component_config".`
if I use `module_config` and 'module_library', the error disappeared.

**Comment by storypku** [comment]
Hi @BigBenSure , thanks for your report. The issue should be fixed in PR #13720. 

Thanks for your contribution!
