### ISSUE TITLE
Apollo5.5无法使用摄像头进行感知

### ISSUE THREAD

**Issue by geekfuns** [ApolloAuto/apollo#13616]
Ubuntu 18.04
Apollo version , 5.5, D-kit套件

在根据D-kit的文档，https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md，进行摄像头感知测试的时候，打开Camera Perception模块之后，网页上并没有障碍物出现，使用Lidar感知则正常。在cyber_monitor里两个摄像头都有数据，之后根据文档https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md
中的命令
cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch
进行操作的时候，报如下的错误：
[mainboard_default_8273] E0325 17:09:48.275676 8282 transform_wrapper.cc:222] [mainboard]Can not find transform. 597.085 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the past. Requested time 597084678000 but the earliest data is at time 1616663378220000000, when looking up transform from frame [novatel] to frame [world]
[mainboard_default_8273] E0325 17:09:48.275704 8282 fusion_camera_detection_component.cc:653] [perception]failed to get camera to world pose, ts: 597.085 camera_name: front_6mm
[mainboard_default_8273] E0325 17:09:48.275728 8282 fusion_camera_detection_component.cc:269] [perception]InternalProc failed, error_code: 4001
[mainboard_default_8273] E0325 17:09:48.319952 8284 transform_wrapper.cc:222] [mainboard]Can not find transform. 597.126 frame_id: world child_frame_id: novatel Error info: Lookup would require extrapolation into the past. Requested time 597126020000 but the earliest data is at time 1616663378269999872, when looking up transform from frame [novatel] to frame [world]
[mainboard_default_8273] E0325 17:09:48.319981 8284 fusion_camera_detection_component.cc:653] [perception]failed to get camera to world pose, ts: 597.126 camera_name: front_12mm

请问一下这个问题是什么原因导致的呢？感激不尽！

**Comment by HUI11126** [comment]
朋友，你解决了吗？我也遇到了同样的问题。

只是，我的cyber_monitor不输出sensor/camera/front_12mm的数据，只输出sensor/camera/front_6mm的数据

**Comment by daohu527** [comment]
Please migrate to the new version and try

**Comment by whj-cmd** [comment]
[mainboard]Wrong Buffer Len: 114264, dev: /dev/camera/front_6mm
