### ISSUE TITLE
Traffic light stopping issue

### ISSUE THREAD

**Issue by BBlumi97** [ApolloAuto/apollo#13638]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: Docker
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:
(standard_in) 1: syntax error
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /home/----/Apollo/apollo
[INFO]     APOLLO_CACHE_DIR: /home/----/Apollo/apollo/.cache
[INFO]     APOLLO_IN_DOCKER: false
[INFO]     APOLLO_VERSION: master-2021-03-29-abf6d99a23
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1
[INFO] Usage: /home/kleer/Apollo/apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- run apollo in combination with lgsvl  Version 2020.06
- use the modular testing function from lgsvl

Issues:
- The Car detects the state of the traffic light is really incosistent. The car somtimes stops at the stopping line from the traffic light but when the light is green the car doesn't start driving. In addition to that  sometimes the car doesn't stop at a red light even if it detects the red light.

### Supporting materials (screenshots, command lines, code/script snippets):

![Ampel](https://user-images.githubusercontent.com/67870208/112965813-e83ec500-9149-11eb-839c-6f0353ad73b0.PNG)

**Comment by daohu527** [comment]
There are two questiones, I suggest you solve them case by case, and you need to analyze the following reasons in advance, the direct display of the results is not more helpful to the solving the problem.

**Comment by BBlumi97** [comment]
Okay so i removed the object detection part from this post and do a seperate one for it. what would you suggest to look into ?

**Comment by daohu527** [comment]
You can first confirm whether the messages under this "/apollo/perception/traffic_light" topic are correct

**Comment by BBlumi97** [comment]
The messages are correct and the traffic light and it is shown in dreamview as you can see in the pictures. It also shows a stopping point until it is close to the stopping line (picture 3). 
![Traffic_light_ Detection](https://user-images.githubusercontent.com/67870208/113839170-bbb12b80-978f-11eb-93ba-d4a1652ba785.PNG)
![detected red light](https://user-images.githubusercontent.com/67870208/113839189-c23fa300-978f-11eb-946d-6a1c77219ba5.PNG)
![redlight overdrive](https://user-images.githubusercontent.com/67870208/113839425-f6b35f00-978f-11eb-882d-ed94f155ad46.PNG)

**Comment by BBlumi97** [comment]
I could see the same issue with the stopping sign  as shown here.
![stopping error](https://user-images.githubusercontent.com/67870208/113839724-3b3efa80-9790-11eb-8f65-b3fd99eb91bd.PNG)

I have the same issue sometimes with cars. in Dreamview there is shown the stopping notification at the vehicle in front but the car continues to drive instead of stopping behind the car. As shown here. I think these issues are linked together.
![objects detected](https://user-images.githubusercontent.com/67870208/113840006-86590d80-9790-11eb-816a-4fc299845704.PNG)

**Comment by daohu527** [comment]
Pls check the config in 
https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/planning/conf/traffic_rule_config.pb.txt#L69-L76

If this config is true then you need to do some simple analysis to see if there is any error message in the log "data/log/planning.INFO"

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
