### ISSUE TITLE
Possible ways to connect Apollo to Vires VTD (Virtual Test Drive) simulator?

### ISSUE THREAD

**Issue by trieuthachvu** [ApolloAuto/apollo#13663]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: Master

What is the possible ways to connect Apollo to Vires VTD (Virtual Test Drive) simulator? and what I need to consider to build the bridge? is it possible to reference the other bridge which is already available for other simulators?

**Comment by daohu527** [comment]
Yes, you can ref to modules/contrib/cyber_bridge
