### ISSUE TITLE
Wrong output of LiDAR-based perception module triggers undesired behavior

### ISSUE THREAD

**Issue by ideasplus** [ApolloAuto/apollo#13669]
I have encountered a problem that has been bothering me for a long time. When I run the lidar-based perception module and other downstream modules with simulator, perception module sometimes output the **_non-existent_** obstacle that is located very close in front of the ego car, which will trigger the braking decison as shown in the figure.

![Screenshot from 2021-04-06 22-17-01](https://user-images.githubusercontent.com/24294571/113953591-bebd2200-984a-11eb-9494-e415eda0c7fe.png)

Please look through the scenarios with recording video for more details.
https://drive.google.com/file/d/1Ludax7yI0vAHVgIo04G1q2nsrmPpiwMj/view?usp=sharing

Note that I'm using Apollo 6.0 master and LGSVL Simulator 2020.06. I can also see the same phenomenon in other old versions of apollo such as Apollo 5.5.

I’m not sure if it’s the problem of the model itself or the simulator and look forward to the solution.

**Comment by panfengsu** [comment]
Ego vehicle seems to be detected as an obstacle. The lidar cloud of ego vehicle is not completely filtered in CyberVisualizer.
