### ISSUE TITLE
problems with the lidar driver robosens128

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#13666]
hello team

I am using **lidar robosense_128**
When I start the driver, after a while I get a scan with a delay. Over time, this delay increases. And when I disconnect the cable from the lidar, the data still comes in.
That is, a buffer is accumulated.

Before that, I patched ubuntu according to the [instructions](https://docs.ros.org/en/foxy/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2.html)

Maybe someone had a similar problem and there is a way to solve it?

**Comment by storypku** [comment]
@pkuwangjia Please help with this issue. Thank you.

**Comment by AlexandrZabolotny** [comment]
if additional information is needed, then I am ready to provide it

**Comment by pkuwangjia** [comment]
the driver 'lidar robosense' is used for 16-line lidar, not for 128

**Comment by AlexandrZabolotny** [comment]
> the driver 'lidar robosense' is used for 16-line lidar, not for 128

I us this driver 
https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/lidar/robosense/conf/rs128.pb.txt

If you do not patch ubuntu (not real-time kernel), then the driver works with very lower delays

**Comment by AlexandrZabolotny** [comment]
Hi guys

I see that Apollo 7.0 is coming soon.
Will the problem of the robosens-128 driver be solved in this version?
