### ISSUE TITLE
udp communication abnormal

### ISSUE THREAD

**Issue by zhaohongweicl** [ApolloAuto/apollo#13667]
When I try to communicate with an application outside the docker environment for udp communication with an application inside the docker environment, an exception occurs. The udp server program was running in the apollo docker container. At first, the server can receive  data  from outside the docker environment. After running for a few seconds, the server  program appears to no longer receive data.any help will be appreciated

**Comment by daohu527** [comment]
Is your network in the same network segment? If not, you need to pay attention to **NAT**
