### ISSUE TITLE
How to understand laneoverlapinfo and regionoverlapinfo？

### ISSUE THREAD

**Issue by lh-120357** [ApolloAuto/apollo#13670]
**How to understand laneoverlapinfo and regionoverlapinfo？**

**How to understand is_merge and region_overlap_id?**

message LaneOverlapInfo {
  optional double start_s = 1;  // position (s-coordinate)
  optional double end_s = 2;    // position (s-coordinate)
  optional bool is_merge = 3;

  optional Id region_overlap_id = 4;
}

message RegionOverlapInfo {
  optional Id id = 1;
  repeated Polygon polygon = 2;
}

**Comment by qwetqwe** [comment]
It is the overlap between lane and elements(signals,signs,crosswalk) .It shows where the elements is in the position of lane

**Comment by lh-120357** [comment]
> It is the overlap between lane and elements(signals,signs,crosswalk) .It shows where the elements is in the position of lane
Thank you very much for your answer！But I still don't understand **is_merge**?
How to understand **is_merge** ?
How to judge its value?

**Comment by daohu527** [comment]
My understanding is as follows
```
   overlap
----==---  lane A 
  /
 /
lane B
```

Lane B merge into lane A, and they have some region overlapped. The overlap lane is "==" and it can tell people which region lane A and lane B are merged.
