### ISSUE TITLE
validate calibration sensor

### ISSUE THREAD

**Issue by TranThanh96** [ApolloAuto/apollo#13678]
I am trying to validation extrinsic matrix between sensors. Can you provide the code to validate like this: 
https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md

I really appreciate if you provide that!

**Comment by haina0421** [comment]
I think it may not be hard to simply write some codes to validation your calibration result. You only need to process some matrix multiplication to transform your original sensor data to target sensor coordinate. Then evaluations such as avg_distance of features in camera_camera calibration or simple visualization might help you.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
