### ISSUE TITLE
Receiving raw data from the specified sensor.

### ISSUE THREAD

**Issue by YuriSilenok** [ApolloAuto/apollo#13672]
Ultimately, I want to collect a dataset from the sensors into a table. For this I will use the Python language. I know that the cyber_recorder tool can write sensor data to a *.record.* file. Please tell me how I can read this data from a file using Python, is there a package for this or are there other tools for converting data from this file to other formats?

**Comment by daohu527** [comment]
You can ref the code in "modules/tools/record_parse_save", it parse the camera,lidar and radar data.

**Comment by YuriSilenok** [comment]
Thank you, it worked. I was able to get the data from the radar in JSON format.
