### ISSUE TITLE
Fusion image and radar in apollo5.5, unable to receive the message from image and radar 

### ISSUE THREAD

**Issue by hello-big-world** [ApolloAuto/apollo#13674]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by hello-big-world** [comment]
in  fusion_component.cc  ,  Proc() can't receive SensorFrameMessage

**Comment by daohu527** [comment]
We need more information to find the problem, Please observe whether the module starts normally and there is no error message
