### ISSUE TITLE
How can I view the record file which only including the trafficlight info

### ISSUE THREAD

**Issue by qiongwu1003** [ApolloAuto/apollo#13673]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- Running Apollo5.0 and LGSVL simulator 202006
- Using "cyber_recorder record -o data/bag/xxxx.record -c /apollo/perception/traffic_light" get the traffic lights information

I only want to know the traffic lights detection result per frame. And the cyber_monitor can not show it. What I want to know is if
 there are other ways to view the xxxx.record file?

**Comment by daohu527** [comment]
You can follow the "modules/tools/record_parse_save" to export the data. You need to create a new script to export **apollo::perception::TrafficLightDetection**

**Comment by qiongwu1003** [comment]
@daohu527 thank your reply. According to your method I got the traffic light info. 
In addition, I have three more questions. Looking forward to your answer.

1.  Dose the cyber recorder records the message frame by frame?
     After investigation, I know that apollo uses camera pictures to detect traffic lights(Am I right?). So I try to check the traffic light detection result by the image info. But I found that the message numbers are different between traffic light and camera. 
     
![image](https://user-images.githubusercontent.com/65001214/114355319-e93c1180-9ba1-11eb-90fb-af06bab326b1.png)


2.  In the traffic light channel, I found "timestamp_sec" and "camera_timestamp", I think that the "camera_timestamp" correspond to the "timestamp_sec" in the camera channel. 
     
![image](https://user-images.githubusercontent.com/65001214/114355752-6ebfc180-9ba2-11eb-9e79-42ed61a15b0e.png)

   But when parse the camera info, it uses the "measurement_time" in the script code. Otherwise, the accuracy of "timestamp_sec" and "measurement_time" are not the same. What is the "measurement_time"?
    
![image](https://user-images.githubusercontent.com/65001214/114356125-d4ac4900-9ba2-11eb-96ed-596cad44d899.png)


   What I want to know is that how can I pick the right camera picture?

3.  I found that the 4 traffic lights result are all the same in the record file.
     
![image](https://user-images.githubusercontent.com/65001214/114356211-ee4d9080-9ba2-11eb-9e49-63c763a65b93.png)


   But the detection results are not the same when running the detection. Is it correct?
    
![image](https://user-images.githubusercontent.com/65001214/114356300-045b5100-9ba3-11eb-8c2e-98b56f0c9c0f.png)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
