### ISSUE TITLE
Can't create a writer with empty channel name!

### ISSUE THREAD

**Issue by DeepCollision** [ApolloAuto/apollo#13683]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:  Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I am running Apollo following these steps:
`./docker/scripts/dev_start.sh`
`./docker/scripts/dev_into.sh`
`bootstrap.sh`
When i want to enable the cyber bridge by typing:
`bridge.sh`
there came an error saying 'E0411 21:16:49.980556  8788 node_channel_impl.h:154] [cyber_bridge] Can't create a writer with empty channel name!'
![image](https://user-images.githubusercontent.com/78254341/114305965-dd524000-9b0c-11eb-8c10-4ebc49ee3f9f.png)

Anyone know what's the problem?

**Comment by daohu527** [comment]
I think the design does not allow **empty topics**, why do you need this feature?

**Comment by DeepCollision** [comment]
> I think the design does not allow **empty topics**, why do you need this feature?

I just followed the origin design of Apollo, and I did not do any change. And the previous run was fine.

**Comment by DeepCollision** [comment]
> I think the design does not allow **empty topics**, why do you need this feature?

**Comment by daohu527** [comment]
I’m afraid I can’t find any code for "cyber_bridge" in 5.0.0. I suggest you double check your topic settings.

```c++
 auto talker = talker_node->CreateWriter<Chatter>("channel/chatter");
```

**Comment by DeepCollision** [comment]
> I’m afraid I can’t find any code for "cyber_bridge" in 5.0.0. I suggest you double check your topic settings.
> 
> ```c++
>  auto talker = talker_node->CreateWriter<Chatter>("channel/chatter");
> ```

Thank you, i just realized this featureis specified for LGSVL.

**Comment by DeepCollision** [comment]
> > I’m afraid I can’t find any code for "cyber_bridge" in 5.0.0. I suggest you double check your topic settings.
> > ```c++
> >  auto talker = talker_node->CreateWriter<Chatter>("channel/chatter");
> > ```
> 
> Thank you, i just realized this featureis specified for LGSVL.

I solved the problem, the sensor deployed on the vehicle need to have a channel name! I will close the issue.
