### ISSUE TITLE
How is the camera feed connected with the self driving software(perception module) installed in the IPC?

### ISSUE THREAD

**Issue by Jobhdez** [ApolloAuto/apollo#13681]
Hello,

I have read your documentation so I learned about the IPC and how I have to connect to cameras, and so on.

But how does the live camera feed get fed into the self driving software(perception module) to steer the car?

Its my understanding that the self driving software is installed in the IPC.

I will appreciate it if someone explains this. thanks

**Comment by daohu527** [comment]
which camera do you use? If your camera support usb uvc, you can derectly use it with apollo.

**Comment by Jobhdez** [comment]
> which camera do you use? If your camera support usb uvc, you can derectly use it with apollo.

Well I’m curious as to how I can write code to get the video feed from the camera(once it’s installed in the car).

So how is the code that you write connected to the camera feed? 

Thanks

**Comment by daohu527** [comment]
This is a big problem. Simply put, automatic driving is divided into several modules. The data of the camera is read through the driver, and after the specific results are obtained through the perception module, it is sent to the planning module and then the car is controlled.
```
camera driver -> perception -> planning -> control -> canbus -> vehicle
```

**Comment by Jobhdez** [comment]
Thanks!

which file of the perception module is linked to the camera driver?

if you were to make an end to end neural network(eg imitation learning, CNN) you would have:
camera-driver -> end to end model-> can bus -> vehicle.
Is that correct?
Could you in theory use the same IPC and cameras that Apollo uses for an end to end self driving car?
Thanks

**Comment by daohu527** [comment]
Yes, you are right. There was an end-to-end module `modules/contrib/e2e`, but now it is disabled.

**Comment by Jobhdez** [comment]
> Yes, you are right. There was an end-to-end module `modules/contrib/e2e`, but now it is disabled.

That’s interesting.

Does the CANBUS module in Apollo use any libraries? For example in Linux there’s can-utils. There’s also libraries in Python which makes me think I could write the camera driver, the end to end model, and the Can bus module in Python. Could you write these modules(the whole self driving system) in Python? Thanks

**Comment by daohu527** [comment]
There's a canbus tools in "modules\drivers\canbus".

Refactoring end-to-end with python seems feasible

**Comment by Jobhdez** [comment]
Thank you for answering all my questions.

is there a more comprehensive guideline/tutorial of the hardware setup other than the one in the Apollo docs? 

I’m aware that if I want to work on a project my self I will need the IPC, camera. What else? Do I need the ASU? CAN card?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
