### ISSUE TITLE
How to use mapshow.py in the docker ?

### ISSUE THREAD

**Issue by shandaolu** [ApolloAuto/apollo#13688]
When I use the mapshow.py in the docker, I meet the question. Hope that someone can help me to solve this. Thankyou.

root@in-dev-docker:/apollo# source scripts/apollo_base.sh 
root@in-dev-docker:/apollo# python3 modules/tools/mapshow/mapshow.py -m /apollo/modules/map/data/sunnyvale_big_loop/base_map.bin 
Traceback (most recent call last):
  File "modules/tools/mapshow/mapshow.py", line 23, in <module>
    from modules.tools.mapshow.libs.localization import Localization
ModuleNotFoundError: No module named 'modules'

**Comment by storypku** [comment]
In Apollo 6.0 and master, Python scripts was managed by Bazel.
Please refer to the [How to Build and Run Python Applications in Apollo](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_run_python_app.md).

In your case, please run
```
./apollo.sh build tools
./bazel-bin/modules/tools/mapshow/mapshow
```
instead.

**Comment by shandaolu** [comment]
Thank you. The issue can be closed.

**Comment by EthanCodesss** [comment]
Hi, bro. I do the same thing. But I get the message:
`/apollo/./bazel-bin/modules/tools/mapshow/mapshow.runfiles/apollo/modules/tools/mapshow/mapshow.py:119: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()`

What should i do?

**Comment by Wangsir-sir** [comment]
> Hi, bro. I do the same thing. But I get the message:
> `/apollo/./bazel-bin/modules/tools/mapshow/mapshow.runfiles/apollo/modules/tools/mapshow/mapshow.py:119: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. plt.show()`
> 
> What should i do?

I have the same problem. Do you have any idea to solve this? thanks

**Comment by Wangsir-sir** [comment]
> Hi, bro. I do the same thing. But I get the message:
> `/apollo/./bazel-bin/modules/tools/mapshow/mapshow.runfiles/apollo/modules/tools/mapshow/mapshow.py:119: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. plt.show()`
> 
> What should i do?

I found a solution, which can be referred to here
#13933

**Comment by EthanCodesss** [comment]
> > Hi, bro. I do the same thing. But I get the message:
> > `/apollo/./bazel-bin/modules/tools/mapshow/mapshow.runfiles/apollo/modules/tools/mapshow/mapshow.py:119: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. plt.show()`
> > What should i do?
> 
> I found a solution, which can be referred to here
> #13933


I'll try, thanks!

**Comment by streamwill** [comment]
When i run :
`./bazel-bin/modules/tools/mapshow/mapshow -m modules/map/data/sample/sim_map.txt` IN DOCKER!!!!!!!!!!!
I got eroor:
`UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()`
what should i do?
Thanks very much.

**Comment by TLSheep** [comment]
> When i run :  当我运行： `./bazel-bin/modules/tools/mapshow/mapshow -m modules/map/data/sample/sim_map.txt` IN DOCKER!!!!!!!!!!!   `./bazel-bin/modules/tools/mapshow/mapshow -m modules/map/data/sample/sim_map.txt` 在 Docker 中！！！！！！ I got eroor:  我得到了错误： `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. plt.show()` what should i do?我该怎么办？ Thanks very much.  非常感谢。

You can comment out the `plt.show()`
and use `plt.savefig("{}.png".format(args.map),dpi=600)`  as an alternative
referenced from [here](https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so)
