### ISSUE TITLE
How to saves images from cyber-rt

### ISSUE THREAD

**Issue by eyadshak** [ApolloAuto/apollo#13689]
### System information

- **Ubuntu 18/04**:
- **Apollo 5.0**:

I have installed RGB, depth, and segmentation cameras on the ego vehicle, and will drive around with Apollo. How do I export/save these images into jpegs or any image format?

Thank you

**Comment by ntutangyun** [comment]
I'm no expert but perhaps you could save the image before publishing to cyber RT or create a separate cyber RT component, subscribing those camera channels, and save the images upon receiving the messages.

**Comment by eyadshak** [comment]
Turns out there is a tool for extracting sensor information in /apollo/modules/tools/record_parse_save/
It didn't work with the latest master for some reason but it worked on the 5.0 branch. There are multiple sample python parsers and you can edit them to extract the exact data needed from a cyber record file.

**Comment by marcusvinicius178** [comment]
Hi @eyadshak I need to extract the channels data as I described here: https://github.com/ApolloAuto/apollo/issues/13958

However not just for camera, lidar or radar. But all the channels:
![channels_messages](https://user-images.githubusercontent.com/43826438/126406288-077779fd-7c74-48cb-a745-43ea892d6016.png)

The parser tool also did not work for me. Do you have some idea how to get these data? I need to plot them.
