### ISSUE TITLE
bash apollo.sh build error

### ISSUE THREAD

**Issue by 1624715047** [ApolloAuto/apollo#13682]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **Linux Ubuntu 14.04
- **Apollo installed from source 
- **Apollo version 1.0;
- **Output of `apollo.sh config` if on `apollo1.0.0` branch**:

### Steps to reproduce the issue:
- **bash apollo.sh build **:

### Supporting materials (screenshots, command lines, code/script snippets):
WARNING: Running Bazel server needs to be killed, because the startup options are different.
ERROR: /apollo/modules/planning/planner/BUILD:3:1: no such package '@eigen//': Error downloading [https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz] to /home/apollo/.cache/bazel/_bazel_apollo/540135163923dd7d5820f3ee4b306b32/external/eigen/3.2.10.tar.gz: GET returned 404 Not Found and referenced by '//modules/planning/planner:lib_planner'.
ERROR: Analysis of target '//modules/planning/planner:lib_planner' failed; build aborted.
INFO: Elapsed time: 125.440s
============================
[ERROR] Build failed!
[INFO] Took 495.772 seconds
============================

**Comment by daohu527** [comment]
You have error download the "Error downloading [https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz", Pls check the network is ok first.

**Comment by 1624715047** [comment]
> 你有错误下载"错误下载[https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz"，请先检查网络是否正常。

网络方面应该是没有问题的，会不会是该网站撤销了这个文件包

**Comment by storypku** [comment]
> > 你有错误下载"错误下载[https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz"，请先检查网络是否正常。
> 
> 网络方面应该是没有问题的，会不会是该网站撤销了这个文件包

You are correct, access to  https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz returns 404 now.

**Comment by Flaoting** [comment]
The same case, I try to build Apollo1.0 and met a number of errors. About the eigen, it can be found on gitlab, but if you replace the url directly, 406 error code returned, maybe gitlab unsupport http_archive. I pull the eigen-repo to my own github-repo, then release the proj and use the new url, problem gone. By the way, the newest boringssl master-with-bazel can't build with old version bazel in apollo docker image. I slove all problems about build, but dreamview can't run correctly. wuwuwuwu~~~
