### ISSUE TITLE
Issue: cyber_launch error of Common Component Example of the CyberRT framework

### ISSUE THREAD

**Issue by Morven-X** [ApolloAuto/apollo#13686]
### System information

- Linux Ubuntu 18.04；
- Apollo version 3.5；

### Steps to reproduce the issue:
I am trying to repeat the step of  'cyber/examples/common_component_example/README.md' , but there are some warnings as follows：

(1) Documents of "cyber/examples/common_component_example" from Apollo 3.5  

(2) Steps:
- $ sudo passwd
- $ su root
- $ cd apollo
- $ bash docker/scripts/dev_start.sh
- $ bash docker/scripts/dev_into.sh
- $ bash apollo.sh clean
- $ bazel build //cyber/examples/common_component_example/...
- $ export GLOG_alsologtostderr=1
- $ source cyber/setup.bash
- $ cyber_launch start cyber/examples/common_component_example/common.launch

(3) warning:
- ……
root@in_dev_docker:/apollo# source cyber/setup.bash
root@in_dev_docker:/apollo#  cyber_launch start cyber/examples/common_component_example/common.launch
[cyber_launch_9302] INFO Launch file   [/apollo/cyber/examples/common_component_example/common.launch] 
[cyber_launch_9302] INFO 
[cyber_launch_9302] INFO Load module [common] library: [common] [CYBER_DEFAULT] conf: [/apollo/cyber/examples/common_component_example/common.dag] exception_handler: []
[cyber_launch_9302] ERROR Subprocess Popen exception: [Errno 2] No such file or directory
[cyber_launch_9302] ERROR Start manager [common] failed. Stop all!

**Comment by storypku** [comment]
Hi @Morven-X , Apollo versions prior to 5.5 was not actively maintained, please consider switching to Apollo 6.0+ or master if possible.

**Comment by Morven-X** [comment]
> Hi @Morven-X , Apollo versions prior to 5.5 was not actively maintained, please consider switching to Apollo 6.0+ or master if possible.

 Hi @storypku，Thanks for your reminding,  Apollo 6.0 is ok.
