### ISSUE TITLE
Apollo HD map Specification?

### ISSUE THREAD

**Issue by shandaolu** [ApolloAuto/apollo#13695]
Hello, Apollo does not product the tool to convert the map format  from xodr to xml. I also check the contents in #3005, but there is no mention of how to convert. Hope Apollo can send me a HD map Specification. By this document, I want to solve this problem.  
email: shandaolu@gmail.com

**Comment by Thinsheep** [comment]
I also need this specification
sgttrieu@gmail.com

**Comment by blacksheep0303** [comment]
Could you send me this specification？ Thanks a lot!
fyqbuaa@163.com

**Comment by AM055** [comment]
Hi can you email me the Apollo OpenDrive specification please ? thanks. email: mekniamal166@gmail.com

**Comment by daohu527** [comment]
duplicated #3005

**Comment by YanBC** [comment]
`.xodr` and `.xml` files are the same thing.
