### ISSUE TITLE
Start bridge failed

### ISSUE THREAD

**Issue by 201520906050** [ApolloAuto/apollo#13692]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
![Screenshot from 2021-04-15 11-53-57](https://user-images.githubusercontent.com/54359641/114811982-af594e00-9de1-11eb-9396-4eb32be16dc4.png)

- **Please use bullet points and include as much details as possible**:

**Comment by storypku** [comment]
Hi @201520906050 , Apollo versions prior to 5.5 was not actively maintained, please consider switching to Apollo 6.0+ or master if possible.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
