### ISSUE TITLE
ImportError: No module named modules.common.util.testdata.simple_pb2

### ISSUE THREAD

**Issue by sonnv174** [ApolloAuto/apollo#13702]
I got `ImportError: No module named modules.common.util.testdata.simple_pb2` when run the read record file example
`python cyber/python/examples/record.py out.record `

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (5.0)**:

**Comment by mengen100** [comment]
You might have missed out the command at the beginning of the file:
For apollo 5:
`Run with:`
`bazel run //cyber/python/cyber_py3/examples:record`

Or for your case should be:
`Run with:`
`bazel run //cyber/python/examples:record`

**Comment by storypku** [comment]
Hi @sonnv174, @mengen100's answer was right.
Furthermore, to make the build consistent,  build with the same set of bazel configurations if possible.

```
./apollo.sh build cyber
./bazel-bin/cyber/python/examples/record
```
