### ISSUE TITLE
What chassis data are required? 

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13706]
We are trying to link the new vehicle to the apollo.
There are no throttle_percentage and brake_percentage values in our vehicle.
1. Are there any other values to substitute?
2. Among Chassis.proto, which value must be present for apollo operation?

Answers I'll wait. Thank you.

**Comment by daohu527** [comment]
> Are there any other values to substitute?

Is there a percentage of torque and acceleration output? It can be converted to a percentage based on the maximum value

> Among Chassis.proto, which value must be present for apollo operation?

`Chassis.proto` has very little news, Except for turn signal lights and wipers, everything else is needed.

**Comment by phs4530** [comment]
Thank you for reply!
