### ISSUE TITLE
Can I get the information in dreamview?

### ISSUE THREAD

**Issue by ssbse2021** [ApolloAuto/apollo#13718]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
Hello team, I want to get the information from the dreamview web UI in a format of picture. For example, i want to get the current position of the vehicle in the map by a picture.
![image](https://user-images.githubusercontent.com/78254341/115517750-0b2c4700-a2ba-11eb-8140-e0bcd4ff904d.png)
Is there any way to get the picture like this?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
