### ISSUE TITLE
How to modify the following distance?

### ISSUE THREAD

**Issue by Alejandro-A-R** [ApolloAuto/apollo#13710]
I want to reduce the distance that the ADV keeps from the vehicles it follows (the ones in front of it), so is it possible to modify this distance by changing, for example, a parameter? In case it is possible, what do I have to do to change it?

**Comment by daohu527** [comment]
You can try below parameter and have a try. **Please do limit the maximum speed before testing**!!!
https://github.com/ApolloAuto/apollo/blob/a29a563e95944b603ab9be338cce46e6486a89be/modules/planning/common/planning_gflags.cc#L236-L237

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
