### ISSUE TITLE
Message type "apollo.planning.ADCTrajectory" has no field named "adc_trajectory_point".

### ISSUE THREAD

**Issue by ssbse2021** [ApolloAuto/apollo#13719]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- I am running the python example in **modules/tools/planning/plot_trajectory**, and I ran the main function by the following command in docker:
`python main.py 1_planning.pb.txt 1_localization.pb.txt`
- And the error message is below:
![image](https://user-images.githubusercontent.com/78254341/115549917-cf09de00-a2db-11eb-9b21-8dc8b72d5467.png)

- I checked the eror message, i thought it was the message type is wrongly defined, i located the **ADCTrajectory** message in **modules/planning/proto**, and i modify trajectory_point to adc_trajectory_point and re-ran the command. But i sitll output the error message as before
![image](https://user-images.githubusercontent.com/78254341/115550348-52c3ca80-a2dc-11eb-89eb-b1f3bf58eb9a.png)

- Anyone know what's the problem? I am using Apollo 5.0, is this a bug in this version?

**Comment by daohu527** [comment]
I think it's outdated now. Both the python code and "1_planning.pb.txt" need to be modified. As you can see, the following code cannot match any messages. It replaced by `apollo.common.TrajectoryPoint`.
```
adc_trajectory_point {
  x: -124.367072419
  y: 364.831849142
  z: -31.332377322

  speed: 1.62222218513
  acceleration_s: 0.786162598236
  curvature: -0.00252617800322
  curvature_change_rate: 0
  relative_time: -0.089999914169311523
  theta: -1.81237826921
  accumulated_s: 0
}
```

I think it needs to be updated before it can work

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
