### ISSUE TITLE
How to feed images to lane detection module properly?

### ISSUE THREAD

**Issue by tandf** [ApolloAuto/apollo#13723]
I'm trying to feed images from the KAIST data set to the lane detection module.

My procedure is like this:
1. Build a cyber record file. First, create a `\tf` message. Then, resize KAIST images from 1280x560 to 1920x1080, and create `/apollo/sensor/camera/front_6mm/image` messages. Pack them as a cyber record file.
2. Play the record file while running the lane detection module. The lane detection module is run as indicated in [this page](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)

The lane detection module is running without reporting any error, and the detected lanes match the lanes in the picture very well. But in the BEV, the detected lanes are not parallel while they should be (see the picture below).
My guess is that the camera location of the KAIST data set is not the same as Apollo's default camera location, but I couldn't find a way to correct it.

So my question is, how should I properly feed images to the lane detection module so that it can yield parallel lanes? Thanks a lot.

![screenshot of lane detection module](https://user-images.githubusercontent.com/25607777/115823692-5751c580-a439-11eb-8fdd-00da418695fa.png)
*In the right part of the screenshot, the detected lanes are not parallel.*

**Comment by qwetqwe** [comment]
You need to change extrinsics and intrinsics in modules/perception/data/params/front_6mm_intrinsics.yaml

**Comment by tandf** [comment]
> 
> 
> You need to change extrinsics and intrinsics in modules/perception/data/params

Thank you for your reply!
I use the correct camera height but it helps just a little. But later I figure out how to change the pitch of the camera. After some trial and error I find the correct rotation params and the results seem right.

**Comment by ideasplus** [comment]
@tandf Hello, Could you give more details on how to generate the cyber record  based on the benckmark datasets such as KAIST image dataset? I can't find the relevant reference and have been troubled by this problem for a long time. Thank you in advance!

**Comment by tandf** [comment]
@ideasplus 
First I used cyber rt's Python API to write cyber messages based on KAIST image, see [this link](https://cyber-rt.readthedocs.io/en/latest/CyberRT_API_for_Developers.html)

At the same time, you can record Apollo's output to record files for future use. You can use [cyber-recorder](https://cyber-rt.readthedocs.io/en/latest/CyberRT_Developer_Tools.html#cyber-recorder) or write a script to do this.

Note that KAIST images are not in RGB format and you may need to read them like this
```python
    byr = cv2.imread(input_file, cv2.IMREAD_ANYDEPTH)
    rgb = cv2.cvtColor(byr, cv2.COLOR_BayerRG2RGB)
```

I make a demo from my script. Note that this is just an example and it's not guaranteed to work.  You need to change it according to your situation
```
from cyber_py import cyber
from cyber_py import record
from modules.drivers.proto.sensor_image_pb2 import Image
import cv2

def read_kaist_stereo(input_file):
    byr = cv2.imread(input_file, cv2.IMREAD_ANYDEPTH)
    #  rgb = cv2.cvtColor(byr, cv2.COLOR_BayerRG2RGB)
    # You may need to use 48 instead of cv.COLOR_BayerRG2RGB with older version
    # of opencv
    rgb = cv2.cvtColor(byr, 48)
    resized = cv2.resize(rgb, (1920, 1080))
    return resized

cyber.init()

# Prepare cyber writers
image_node = cyber.Node("image_writer_node")
image_writer = image_node.create_writer(
        "/apollo/sensor/camera/front_6mm/image", Image)
tf_writer = image_node.create_writer( "/tf", TransformStampeds)

# Read image file
image_file = read_kaist_stereo(image_file_path)
videoHeight, videoWidth, _ = image_file.shape

image_msg = Image()

# Set up header
image_msg.header.sequence_num = sequence_num
image_msg.header.lidar_timestamp = lidar_timestamp
image_msg.header.radar_timestamp = radar_timestamp
image_msg.header.version = version
image_msg.header.frame_id = frame_id

# Frame_id
image_msg.frame_id = frame_id
            
# Image metadata
image_msg.height = videoHeight
image_msg.width = videoWidth
image_msg.encoding = "rgb8"
image_msg.step = videoWidth * 3

# Image data
image_msg.data = image_file.tobytes()

# Write image and tf cyber message
image_msg.header.camera_timestamp = camera_timestamp
image_msg.header.timestamp_sec = timestamp_sec
image_msg.measurement_time = measurement_time
image_writer.write(image_msg)

# Also make a tf message
tf_msg = TransformStampeds()
tf_msg.transforms.add()
tf_msg.transforms[0].header.frame_id = 'world'
tf_msg.transforms[0].child_frame_id = 'localization'
tf_msg.transforms[0].transform.translation.x = 0
tf_msg.transforms[0].transform.translation.y = 0
tf_msg.transforms[0].transform.translation.z = 0
tf_msg.transforms[0].transform.rotation.qx = -0.5
tf_msg.transforms[0].transform.rotation.qy = 0.5
tf_msg.transforms[0].transform.rotation.qz = -0.5
tf_msg.transforms[0].transform.rotation.qw = 0.5
tf_msg.transforms[0].header.timestamp_sec = timestamp
tf_writer.write(tf_msg)

cyber.shutdown()
```

**Comment by ideasplus** [comment]
> @ideasplus
> First I used cyber rt's Python API to write cyber messages based on KAIST image, see [this link](https://cyber-rt.readthedocs.io/en/latest/CyberRT_API_for_Developers.html)
> 
> At the same time, you can record Apollo's output to record files for future use. You can use [cyber-recorder](https://cyber-rt.readthedocs.io/en/latest/CyberRT_Developer_Tools.html#cyber-recorder) or write a script to do this.
> 
> Note that KAIST images are not in RGB format and you may need to read them like this
> 
> ```python
>     byr = cv2.imread(input_file, cv2.IMREAD_ANYDEPTH)
>     rgb = cv2.cvtColor(byr, cv2.COLOR_BayerRG2RGB)
> ```
> 
> I make a demo from my script. Note that this is just an example and it's not guaranteed to work. You need to change it according to your situation
> 
> ```python
> from cyber_py import cyber
> from cyber_py import record
> from modules.drivers.proto.sensor_image_pb2 import Image
> import cv2
> 
> def read_kaist_stereo(input_file):
>     byr = cv2.imread(input_file, cv2.IMREAD_ANYDEPTH)
>     #  rgb = cv2.cvtColor(byr, cv2.COLOR_BayerRG2RGB)
>     # You may need to use 48 instead of cv.COLOR_BayerRG2RGB with older version
>     # of opencv
>     rgb = cv2.cvtColor(byr, 48)
>     resized = cv2.resize(rgb, (1920, 1080))
>     return resized
> 
> cyber.init()
> 
> # Prepare cyber writers
> image_node = cyber.Node("image_writer_node")
> image_writer = image_node.create_writer(
>         "/apollo/sensor/camera/front_6mm/image", Image)
> tf_writer = image_node.create_writer( "/tf", TransformStampeds)
> 
> # Read image file
> image_file = read_kaist_stereo(image_file_path)
> videoHeight, videoWidth, _ = image_file.shape
> 
> image_msg = Image()
> 
> # Set up header
> image_msg.header.sequence_num = sequence_num
> image_msg.header.lidar_timestamp = lidar_timestamp
> image_msg.header.radar_timestamp = radar_timestamp
> image_msg.header.version = version
> image_msg.header.frame_id = frame_id
> 
> # Frame_id
> image_msg.frame_id = frame_id
>             
> # Image metadata
> image_msg.height = videoHeight
> image_msg.width = videoWidth
> image_msg.encoding = "rgb8"
> image_msg.step = videoWidth * 3
> 
> # Image data
> image_msg.data = image_file.tobytes()
> 
> # Write image and tf cyber message
> image_msg.header.camera_timestamp = camera_timestamp
> image_msg.header.timestamp_sec = timestamp_sec
> image_msg.measurement_time = measurement_time
> image_writer.write(image_msg)
> 
> # Also make a tf message
> tf_msg = TransformStampeds()
> tf_msg.transforms.add()
> tf_msg.transforms[0].header.frame_id = 'world'
> tf_msg.transforms[0].child_frame_id = 'localization'
> tf_msg.transforms[0].transform.translation.x = 0
> tf_msg.transforms[0].transform.translation.y = 0
> tf_msg.transforms[0].transform.translation.z = 0
> tf_msg.transforms[0].transform.rotation.qx = -0.5
> tf_msg.transforms[0].transform.rotation.qy = 0.5

> 
>

 tf_msg.transforms[0].transform.rotation.qz = -0.5
> tf_msg.transforms[0].transform.rotation.qw = 0.5
> tf_msg.transforms[0].header.timestamp_sec = timestamp
> tf_writer.write(tf_msg)
> 
> cyber.shutdown()
> ```

Thank you for your generous help and detailed answers. It's really helpful! I will try to get it work based on your scripts.

**Comment by rzr900ipl** [comment]
Hi

I'm a beginner in Apollo, and I am working in a project to test the perception module, in this case lane detection. So I would like to know what I have to do to have the same result has yours. I appreciate if you can give me a lite help

**Comment by tandf** [comment]
Hi @rzr900ipl 
You can learn the basics of Apollo and cyber first. After that, you should be able to understand and run the code. If you have any questions, please be specific so that I can help.

**Comment by rzr900ipl** [comment]
Hi @tandf
Thank you for the advice, I will do it. But just a question, where and how you call the image or video file on your code?

**Comment by tandf** [comment]
@rzr900ipl I read each video frame and send them as cyber messages to the topic Apollo requires, and the perception module handles the rest. You can do this using the script I provided above.

**Comment by rzr900ipl** [comment]
@tandf
First thank you for you fast answer, I appreciate that very must
Second, is possible put the perception module lane detection in a simple image of a Road? What I have to replace  in your code?
Third, if /apollo/sensor/camera/front_6mm/image already exists, I only need to create the /tf massages to see the lane detection? I obtain the image and the topic from the SVL Simulator.

Sorry for the amount of questions, but I need to understand this the fast that a can. Thank you again

**Comment by tandf** [comment]
> Second, is possible put the perception module lane detection in a simple image of a Road? What I have to replace in your code?

Do you mean you want to run the perception module on just one image? I think you should first run the perception module, then send the cyber message containing the image with some necessary tf messages, and the perception module should output the result.

> Third, if /apollo/sensor/camera/front_6mm/image already exists, I only need to create the /tf massages to see the lane detection? I obtain the image and the topic from the SVL Simulator.

Actually, I think the svl simulator will produce everything necessary for the module. When I first tried to run the perception module, I ran Apollo 2.5 perception module as told in [this doc](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) and connect it with the svl simulator. I remember I didn't modify anything except enabling visualization and it worked fine. I think this also applies to later versions of Apollo with dreamviewer.

**Comment by rzr900ipl** [comment]
> Do you mean you want to run the perception module on just one image? I think you should first run the perception module, then send the cyber message containing the image with some necessary tf messages, and the perception module should output the result.

Yes. I say that because I don't working with KAIST, and I don't understand where you call the video in the code. The Apollo have a test images, and I would like to work with [them](https://github.com/ApolloAuto/apollo/tree/master/modules/perception/testdata/camera/app/lane_images). I don't know if apollo use them for test the componentes, or if is for the developers test de componentes

> Actually, I think the svl simulator will produce everything necessary for the module. When I first tried to run the perception module, I ran Apollo 2.5 perception module as told in this doc and connect it with the svl simulator. I remember I didn't modify anything except enabling visualization and it worked fine. I think this also applies to later versions of Apollo with dreamviewer.

I already do it, but it don't work. I have create this issue #13976.

**Comment by tandf** [comment]
> I don't know if apollo use them for test the componentes, or if is for the developers test de componentes

@rzr900ipl 
I don't know if Apollo provides any test program for these images. If not, you can try my code above. The image is read like this:
```python
# Read image file
image_file = read_kaist_stereo(image_file_path)
videoHeight, videoWidth, _ = image_file.shape

image_msg = Image()

# ...

image_msg.height = videoHeight
image_msg.width = videoWidth
image_msg.encoding = "rgb8"
image_msg.step = videoWidth * 3

# Image data
image_msg.data = image_file.tobytes()
```
You may need to change the read_kaist_stereo() function according to the image format

**Comment by rzr900ipl** [comment]
@tandf 
But in the read_kaist_stereo() function, how do i call de image in the [folder](https://github.com/ApolloAuto/apollo/tree/master/modules/perception/testdata/camera/app/lane_images) I told you above?

And for use this code need a spesific version of Apollo?

**Comment by tandf** [comment]
Something like this
```python
def read_your_image(input_file_path):
    img = cv2.imread(input_file_path)
    resized = cv2.resize(img, (1920, 1080))
    return resized
```
Specify the image path like
```
read_your_image(/apollo/modules/perception/testdata/camera/app/lane_images/1525854441139346413.jpg)
```
I don't think this needs a specific version of Apollo. It simply makes cyber messages from some images and sends them to Apollo. But there are indeed some differences between these versions when using cyber, like python2 or 3...

**Comment by rzr900ipl** [comment]
@tandf
I tried to run the code, but I got a erro. 

`@in_5_0_dev_docker:/apollo$ python project/project.py` 
`WARNING: Logging before InitGoogleLogging() is written to STDERR`
`I0824 23:24:03.164288 13386 cyber_record_wrap.cc:562] [] init _cyber_record`
`I0824 23:24:03.224678 13386 global_data.cc:150] [cyber_py] host ip: 192.168.11.106`
`Traceback (most recent call last):`
`  File "project/project.py", line 17, in <module>`
`    tf_writer = image_node.create_writer( "/tf", TransformStampeds)`
`NameError: name 'TransformStampeds' is not defined`


I have create a python folder, and put the code you provide with the changes for the image.
Can you help me. Thank you

**Comment by rzr900ipl** [comment]
@tandf
I understood what you said, but how do I pass throng the erro? I need to define the `camera_timetamp`? I am asking that because the TF massagens have a `timetamp` as well, and the the image have a `timestamp_sec` and `measurement_time` that is not define as well

**Comment by tandf** [comment]
Try this `camera_timestamp = int(filename.split('.')[0])` with `filename` being for example `1525854441139346413.jpg`
The timestamps are also confusing to me. You can set all of them to be `int(filename.split('.')[0])`, and see if anything goes wrong.

**Comment by rzr900ipl** [comment]
@tandf
I did what you said an i got this
`WARNING: Logging before InitGoogleLogging() is written to STDERR`
`I0828 13:59:27.512753  4573 cyber_record_wrap.cc:562] [] init _cyber_record`
`I0828 13:59:27.571147  4573 global_data.cc:150] [cyber_py] host ip: 192.168.11.106`

It is right?

**Comment by tandf** [comment]
@rzr900ipl  Looks like nothing is wrong.

**Comment by rzr900ipl** [comment]
@tandf
So i created `/apollo/sensor/camera/front_6mm/image` and `/tf` massagens and were are they recorded, or what need i do more for see the lane detection?

**Comment by tandf** [comment]
@rzr900ipl  You can run the lane detection module and play the messages at the same time. Then you should see the results.

**Comment by rzr900ipl** [comment]
@rzr900ipl
Like first I do this [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) and then i run the python?

**Comment by rzr900ipl** [comment]
@rzr900ipl
Like first I do this [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) and then i run the python?

**Comment by tandf** [comment]
The last step in this doc is playing the recorded bag, which means to offer data to Apollo. So yes, you can replace this step with running python to offer data that's necessary to Apollo.

**Comment by rzr900ipl** [comment]
@tandf
But in dreamview what setup mode do I select?

**Comment by tandf** [comment]
The default one should work

**Comment by rzr900ipl** [comment]
Hi @tandf
I did the python for the image, and I think it works fine. I can't tell if if it work because of the same problem if issue #13976.
But one question, if y I want to put a video in the position of the image, I need to change, or what changes for it works?

thank you again for all support you gave me

**Comment by tandf** [comment]
@rzr900ipl I haven't tried videos before. But I think you may take each frame of the video and send them to Apollo just like how you work with images. I don't know if the frame_id field is necessary. You can try it and see if it works.

**Comment by rzr900ipl** [comment]
Hi @tandf
I have results, but the result is showing in a very little box.  It is a issue of configuration or what can be?
![Screenshot_2021-09-03_15-39-16](https://user-images.githubusercontent.com/78313843/132023987-a5c2ed4c-854e-4cc0-93dd-0d3f2785ab84.png)

**Comment by Eternal-Br** [comment]
> @tandf
> First thank you for you fast answer, I appreciate that very must
> Second, is possible put the perception module lane detection in a simple image of a Road? What I have to replace in your code?
> Third, if /apollo/sensor/camera/front_6mm/image already exists, I only need to create the /tf massages to see the lane detection? I obtain the image and the topic from the SVL Simulator.
> 
> Sorry for the amount of questions, but I need to understand this the fast that a can. Thank you again

Hi guy, I have the same situation with you, and I'm not familiar with Apollo as well. Do you mind giving a brief introduction about how to use the test image for perception module lane detection?  I will appriciate very much.
