### ISSUE TITLE
How to add custom map

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13722]
## System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18:04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**: 5.5 gpu build

### Supporting materials (screenshots, command lines, code/script snippets):

I have opendrive format map but I don have Apollo opendrive format map.
My opendrime map causes an error.
How to convert opendrive format map to Apollo opendrive formap map?

E0422 19:02:08.503065 21882 hdmap_util.cc:40] [map]No existing file found in modules/map/data/custom/routing_map.bin|routing_map.txt. Fallback to first candidate as default result.
E0422 19:02:08.515142 21882 opendrive_adapter.cc:52] []fail to parse opendrive road, Error parse lane uid
E0422 19:02:08.516661 21882 graph_creator.cc:67] [routing]Failed to load base map file from modules/map/data/custom/base_map.xml

**Comment by yumianhuli2** [comment]
> ## System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18:04
> * **Apollo installed from (source or binary)**: source
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
> * **Output of `apollo.sh config` if on `master` branch**: 5.5 gpu build
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):
> I have opendrive format map but I don have Apollo opendrive format map.
> My opendrime map causes an error.
> How to convert opendrive format map to Apollo opendrive formap map?
> 
> E0422 19:02:08.503065 21882 hdmap_util.cc:40] [map]No existing file found in modules/map/data/custom/routing_map.bin|routing_map.txt. Fallback to first candidate as default result.
> E0422 19:02:08.515142 21882 opendrive_adapter.cc:52] []fail to parse opendrive road, Error parse lane uid
> E0422 19:02:08.516661 21882 graph_creator.cc:67] [routing]Failed to load base map file from modules/map/data/custom/base_map.xml

Also have the question below:
Apollo5 opendrive format map = base_map.txt or basemap.bin ?(apollo5.0 5.5 6.0)?
Apollo3 opendrive format map = base_map.txt or basemap.bin?(apollo5.0 5.5 6.0)?
Is there a tool to convert OpenDrive maps to basemap.txt or basemap.bin?
Thanks!

**Comment by phs4530** [comment]
@yumianhuli2 
I don't have Apollo OpenDRIVE only OpenDRIVE

**Comment by yumianhuli2** [comment]
> @yumianhuli2
> I don't have Apollo OpenDRIVE only OpenDRIVE

Yes,I also want to know how to convert OpenDrive maps to basemap.txt or basemap.bin

**Comment by daohu527** [comment]
You can use `modules/tools/create_map/convert_map_txt2bin.py` to  convert Apollo OpenDrive maps basemap.txt to basemap.bin.

Apollo don't support OpenDrive maps.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
