### ISSUE TITLE
How to add a SVL Simulator map

### ISSUE THREAD

**Issue by BBlumi97** [ApolloAuto/apollo#13724]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.047
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /home/kleer/apollo
[INFO]     APOLLO_CACHE_DIR: /home/kleer/apollo/.cache
[INFO]     APOLLO_IN_DOCKER: false
[INFO]     APOLLO_VERSION: master-2021-04-04-eb1ca541eb
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1
[INFO] Usage: /home/kleer/apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- I downloaded the Highway101GLE base_map.bin form SVL Cloud and want to use it with Apollo.Auto
- i copied the base_map.bin file into the modules/map/data/demo folder and followed the documentation to create the routing_map
`dir_name=modules/map/data/demo`
`./scripts/generate_routing_topo_graph.sh --map_dir ${dir_name}`
 The following error was the result of my code:
`ERROR: unknown command line flag 'alsologtostderr'`

![image](https://user-images.githubusercontent.com/67870208/115834552-a2f27800-a415-11eb-99c2-9f5fe0e6b424.png)

**Comment by daohu527** [comment]
This is the detailed map generation step.

## sim_map
```
./bazel-bin/modules/map/tools/sim_map_generator -map_dir=/apollo/modules/map/data/your_map_dir -output_dir=/apollo/modules/map/data/your_map_dir
```

## routing_map
```
/apollo/bazel-bin/modules/routing/topo_creator/topo_creator -map_dir=/apollo/modules/map/data/your_map_dir --flagfile=modules/routing/conf/routing.conf
```

Need to be modified before testing "vi modules/common/data/global_flagfile.txt"，disable "--log_dir/--use_navigation_mode"
```
--map_dir=/apollo/modules/map/data/your_map_dir
```

## finally
You get
```
base_map.bin  // use for hd map
sim_map.bin  // use for dreamview
routing_map.bin // use for routing module
```

**Comment by ntutangyun** [comment]
BTW. 

> * ERROR: unknown command line flag 'alsologtostderr'

looks like a flag issue. 

this flag by its name should be related to the logging and may be irrelevant to the main function. 

You could comment it out and try again.

**Comment by BBlumi97** [comment]
Thanks a lot @daohu527 your manual helped me a lot!
