### ISSUE TITLE
[Planning] traffic rules -> reference_line_end

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#13732]
Hi team,

I noticed that in [reference_line_end.h]
https://github.com/ApolloAuto/apollo/blob/f02eda58ca1abf939c567fc8db3a461fcbcbc95a/modules/planning/traffic_rules/reference_line_end.h#L31-L34

It says that this traffic rule is related to rerouting requests. 

However, in file [reference_line_end.cc]
https://github.com/ApolloAuto/apollo/blob/f02eda58ca1abf939c567fc8db3a461fcbcbc95a/modules/planning/traffic_rules/reference_line_end.cc#L39-L92

there is nothing related to the rerouting request. 

Also, the stop reason at line 80 is set to "DESTINATION", instead of "REFERENCE_END": 

https://github.com/ApolloAuto/apollo/blob/f02eda58ca1abf939c567fc8db3a461fcbcbc95a/modules/planning/traffic_rules/reference_line_end.cc#L80

Please check. thanks.

**Comment by qwetqwe** [comment]
It seems engineer copy it from https://github.com/ApolloAuto/apollo/blob/ecece0da431c82cd1b52129ec1b0bb58323331a2/modules/planning/traffic_rules/rerouting.h#L31-L32
•ᴗ•

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
