### ISSUE TITLE
How to change sim_control start point?

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13734]
![image](https://user-images.githubusercontent.com/18480213/116210164-948dbe80-a77d-11eb-8c62-84e12a9bf690.png)

Hello.
I use Apollo master branch.
I tried putting a variable like the picture above, but it was not changed.
I want change start point.
Where can I change the variable to change the starting point?

**Comment by daohu527** [comment]
You can modify the following code and try
```
*start_point = lane->GetSmoothPoint(10.0)  // start at 10m
```

**Comment by phs4530** [comment]
@daohu527 Thanks for reply! I solved the problem.
I have to one more question.
How to change sim_control speed?
The speed is only 4-5km/h at the maximum.

**Comment by daohu527** [comment]
Your maximum speed is dependent on the planning module "modules/planning/conf/planning.conf"
```
--planning_upper_speed_limit=20.00
--default_cruise_speed=11.18
```

Considering that your speed is too low, I think there may be other problems, you may need to check the log to analyze

**Comment by phs4530** [comment]
Changing the maximum speed solved it.
There is a problem that does not completely terminate after using sim control.
How should this be solved?
I'm using the following command:
./script/bootstrap.sh stop

![image](https://user-images.githubusercontent.com/18480213/116337051-86d74800-a814-11eb-91c3-07c0fb5cc028.png)

**Comment by daohu527** [comment]
1. sim_control don't need control module
2. ./script/bootstrap.sh stop just stop dreamview but not planning and routing
3. The strange thing is that you have so many control modules. Normally, you cannot start multiple control modules. Do you modify some codes?

**Comment by qwetqwe** [comment]
I can give you some advice. You can change the sim control like https://github.com/ApolloAuto/apollo/pull/13727. Then you make a tool to publish localization message. 
Before you open sim control, you need to use the tool to publish the localization where you want. Then after open sim control, it will publish the latest localization as start point

**Comment by InterKnight** [comment]
> I can give you some advice. You can change the sim control like #13727. Then you make a tool to publish localization message.
> Before you open sim control, you need to use the tool to publish the localization where you want. Then after open sim control, it will publish the latest localization as start point

Hi, Thank you for your PR! 
I tried to publish /apollo/localization/pose message with playing a bag, but the start point is still a dummy point, not the point I published. That means `localization_reader_->empty() ` in sim_control.cc is still true, Do you konw what's the problem? Thank you very much!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
