### ISSUE TITLE
Apolo how to use self-generated HD maps with apollo format for  autonomous driving ?

### ISSUE THREAD

**Issue by peak9527** [ApolloAuto/apollo#13737]
there is a HD map for our factory  with apollo format ,but  now  ,i want to know how to use for  autonomous driving , apolo don't seem to have a document on how to use it?

**Comment by qwetqwe** [comment]
you need to generate base_map.bin sim_map.bin and routing_map.bin to modules/map data
and tools are here: https://github.com/ApolloAuto/apollo/tree/master/modules/map/tools
then you need to change to your map in dreamview
the map_dir will change to your map
 https://github.com/ApolloAuto/apollo/blob/ecece0da431c82cd1b52129ec1b0bb58323331a2/modules/common/data/global_flagfile.txt#L14

**Comment by peak9527** [comment]
> you need to generate base_map.bin sim_map.bin and routing_map.bin to modules/map data
> and tools are here: https://github.com/ApolloAuto/apollo/tree/master/modules/map/tools
> then you need to change to your map in dreamview
> the map_dir will change to your map
> https://github.com/ApolloAuto/apollo/blob/ecece0da431c82cd1b52129ec1b0bb58323331a2/modules/common/data/global_flagfile.txt#L14

Glad  for your answer !
