### ISSUE TITLE
Which Apollo version works with Nvidia agx Xavier and Ubuntu 18.04?

### ISSUE THREAD

**Issue by Maxcode19** [ApolloAuto/apollo#13742]
Hello,

I am interested in working with Apollo and I need to do it on a **Nvidia agx Xavie**r and with **Ubuntu 18.04**. Looking at the already present issues, it seems that some people have succeeded in doing it and I am wondering which version should I use to do the same. Here is what I have done up to now:

1.  I started building version **6**, but, when I run **bash docker/scripts/dev_start.sh**, it fails reporting the very same error of #13557. Reading at the answer of that issue, it seems that the problem is the lack of **CUDA 11.1**. However, I have read that the Nvidia agx Xavier does not support CUDA 11.1 yet (it should stop at **CUDA 10.2**, https://developer.nvidia.com/embedded/jetpack), so I suppose that version 6 does not work.
2. For this reason, I tried to install **Apollo 5.5** that, as far as I got, is the only remaining version compatible with Ubuntu 18.04. When I run **bash docker/scripts/dev_start.sh**, I get this error:

          Error response from daemon: manifest for apolloauto/apollo:paddlepaddle_volume-aarch64-2.0.0 not found: manifest unknown: manifest unknown
          [Error] Failed to pull docker image : apolloauto/apollo:paddlepaddle_volume-aarch64-2.0.0

    Moreover there are several warnings like:
    
          WARNING: The requested image's platform (linux/amd64) does not match the detected host platform(linux/arm64/v8) and no specific platform was requested.
    
    Given these errors and warnings, I suppose that also version 5.5 is not the correct one.

Is there a solution to overcome the problem?

Thanks in advance for any hint.

**Comment by jdcllh** [comment]
same issue happened with my macOS with virtual machine sys, do you fix it now?

**Comment by Maxcode19** [comment]
Hi. No, I did not. I do not know if something has changed since May 2021, but the answer I found at the time is that there is not an Apollo version for the AGX. I think that all people who have succeeded in installing Apollo on the AGX have done a huge and great job because a lot of operarations are required to make it work

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
