### ISSUE TITLE
Can't access Route Editing tab in Dreamview

### ISSUE THREAD

**Issue by ekalvan** [ApolloAuto/apollo#13744]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:  Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source Apollo (master) and LGSVL-2020.06
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:
  [INFO] Apollo Environment Settings:
  [INFO]     APOLLO_ROOT_DIR: /home/apollo/apollo
  [INFO]     APOLLO_CACHE_DIR: /home/apollo/apollo/.cache
  [INFO]     APOLLO_IN_DOCKER: false
  [INFO]     APOLLO_VERSION: HEAD-2020-09-21-e79f9d6765
  [INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
  [INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1
  [INFO] Usage: /home/apollo/apollo/scripts/apollo_config.sh [Options]
  [INFO] Options:
  [INFO]     -i|--interactive      Run in interactive mode
  [INFO]     -n|--noninteractive   Run in non-interactive mode
  [INFO]     -h|--help             Show this message and exit 

### Steps to reproduce the issue:
**Please use bullet points and include as much details as possible**:

- ./docker/scripts/dev_start.sh
- ./docker/scripts/dev_into.sh
- ./scripts/bootstrap_lgsvl.sh
- ./scripts/bridge.sh
- In LGSVL, Simulation uses: BorregasAve Lincoln2017MKZ localhost:9090
- In Dreamview, select: MKz Lgsvl, Lincoln2017MKZ LGSVL, Borregas
- Then select modules in order: Localization, Transform, Planning, Prediction, Routing, and Control
- Route Editing is unavailable

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/16006156/116461759-7ecfd600-a81d-11eb-87e1-9a799cab2306.png)

**Comment by daohu527** [comment]
If you have not received the localization topic, you will not be able to select the routing UI

**Comment by ekalvan** [comment]
Any idea why localization isn't being received?

**Comment by daohu527** [comment]
You could check it by `cyber_monitor` or use chrome's debug tool `F12` to provide more information

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
