### ISSUE TITLE
Setup mode,  Vehicle model and HD map

### ISSUE THREAD

**Issue by Thinsheep** [ApolloAuto/apollo#13749]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: Master

Hi,
I build the communication bridge between apollo and a simulator (not LGSVL).
In Apollo's, we have three selection options:
1. Setup mode: how to write a setup mode to talk with the simulator? for example in the LGSVL's bridge, we select the "Mkz LGSVL". For other simulators, are there any existing modes, we can use to run the simulation?
2. Vehicle: when I run the Apollo modular test without selecting Lincoln2017MKZ LGSVL, the simulation is still working fine.
There are documents showing how to add a new vehicle to Apollo and another for LGSVL.
I want to know how important is it for both apollo and a simulator to use the same vehicle model?
3. Convert Open Drive map to Apollo Open Drive map
I found the answer below ticket.
#11181
.xodr => .XML => sim_map.bin then routing_map.bin and routing_map.txt
Is this still the best way to do it?

**Comment by daohu527** [comment]
The above two configurations are related to the vehicle and the sensors.

> Convert Open Drive map to Apollo Open Drive map

You can .xodr => base_map.bin, means opendrive map to apollo map
