### ISSUE TITLE
ROS to Cyber sensor data conversion

### ISSUE THREAD

**Issue by Thinsheep** [ApolloAuto/apollo#13743]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: master

Hi,
1. I am trying to build the communication bridge between Apollo and VTD simulator.
The simulator has a ROS interface so my ideas to utilize the apollo_to_ros project to convert ROS sensor data to Cyber sensor
https://github.com/AuroAi/apollo_ros_bridge
There are existing conversions of ROS Point cloud to Cyber Point cloud and ROS IMU to Cyber IMU.
I want to add ROS Camera to Cyber camera and ROS radar to Cyber Radar.
Adding new sensor conversion to the bridge is ok but for the message's data conversion is a hard part to me.
Has anyone done it before or any reference for this implementation?

 2. I have heard about the LGSVL bridge, where can I find the source code of the LGSVL bridge to Apollo?

**Comment by daohu527** [comment]
> I have heard about the LGSVL bridge, where can I find the source code of the LGSVL bridge to Apollo?

LGSVL bridge is private data to cyber.

Actually you don't really care about cyber, you just need to convert the data format, and then send the data to the bridge. 
So there are 2 parts of work
1. convert the data format
2. use bridge to send the data to apollo

You really need is `convert the data format`, and bridge is there

**Comment by Thinsheep** [comment]
@daohu527 
Thanks. Is there any example to understand how to use the bridge to send the data to Apollo and receive the vehicle command from Apollo?

**Comment by daohu527** [comment]
You can ref to LGSVL's **c# code**. c++ currently seems to have no end-to-end examples.

You can try to ask more detailed questions

**Comment by Thinsheep** [comment]
1. May I know where is the source code of the bridge? without understanding it I do not know how to send data to the bridge.
is the below link is correct?
https://github.com/ApolloAuto/apollo/tree/master/modules/bridge

**Comment by Thinsheep** [comment]
@daohu527 
Could you please support me to check if my understanding is correct?
Setup: 1 pc to run Apollo and 1 pc to run VTD (simulator)
https://github.com/ApolloAuto/apollo/tree/master/modules/contrib/cyber_bridge
I got nothing to do with the cyber bridge just launching it in Apollo PC

https://github.com/ApolloAuto/apollo/tree/master/cyber/python/cyber_py3/examples
I guess with this is the example package, I can publish and subscribe topics to Cyber channels 
Can I develop and run this package on the simulator pc? I plan to convert VTD sensor data to cyber data
and use this package to publish the sensor data to the cyber channels. In the other direction, I will use this package
to subscribe the vehicle control data from apollo and convert it to VTD control data.
In this case, to work across the different machines, I will create a TCP socket to connect to the cyber bridge server (IP:9090).
Is my understanding correct?

On the simulator's side, I am using C++
I probably prefer c++ I found another example here in C++
https://github.com/ApolloAuto/apollo/tree/master/cyber/examples
Can I use this package instead of python's package which I mention above? do they do the same job?

**Comment by daohu527** [comment]
Yes you can use 
```
https://github.com/ApolloAuto/apollo/tree/master/modules/bridge
```

and simultor and apollo communicate via socket

**Comment by Thinsheep** [comment]
Hi @daohu527 
I have some concern may you help me to clarify:
1. As default: By running the bridge, the bridge's sender will send out 
ADCTrajectory is sent to 127:0.0.1:8900
LocalizationEstimate is sent to 127:0.0.1:8900
Is that correct I just need to write a server in Simulator's side, binding to 127:0.0.1:8900 I will receive the ADCTrajectory's data?
All I need to do is to parse data to what Simulator needs.

2. Is that bridge/test folder written only to test the brigde?
https://github.com/ApolloAuto/apollo/tree/master/modules/bridge/test
In the test file, it sends the Chasis's data (bridge_sender_test.cc) to 127:0.0.1:8900. How can this be when the default 127:0.0.1:8900 is to send ADCTrajectory not Chasis.

Just made sure I have correct understanding of the bridge/test module, does bridge_sender_test.cc send Chasis's message to the bridge (simulator to bridge) or out of the bridge (to port for simulator getting message)? (port:127:0.0.1:8900)

**Comment by daohu527** [comment]
If you are using LGSVL, you can directly use their bridge and apollo branches for testing.

Going back to your question, I think you can try to run it, the principle is relatively simple is to send a message to apollo through the socket, and then publish the message in apollo (cyber)

> In the test file, it sends the Chasis's data (bridge_sender_test.cc) to 127:0.0.1:8900. How can this be when the default 127:0.0.1:8900 is to send ADCTrajectory not Chasis.

A port can publish various messages, and the port is a concept in the socket

**Comment by Thinsheep** [comment]
Yes, a port can publish various messages but the Chasis channel is not configured to send out the message in 127:0.0.1:8900.
There is no configuration of Chasis in bridge_sender.dag and udp_bridge_sender_chasis.pb.txt is not available.

Probably, just to make it simple please let me know what is the role of bridge_sender_test.cc and bridge_receiver_test.cc in this package?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
