### ISSUE TITLE
Apollo 5.0 libtorch version

### ISSUE THREAD

**Issue by thymbahutymba** [ApolloAuto/apollo#13740]
Hi guys, I'm trying to compile Apollo 5.0 outside the docker environment and I cannot figure out which version of libtorch I have to use. I cannot use the latest one since the torch:jit:Load is changed with respect the one that was used in the libtorch version used by Apollo 5.0. Moreover in the dockerfile and installers' directory there is not sign of what installs libtorch. Any help? Thanks in advance!

**Comment by daohu527** [comment]
I'm not very sure if `install_conda.sh` install the libtorch.so, then you can link the dynamic library.

I did not find a way to check the version of c++ api, so this question needs further confirmation

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
