### ISSUE TITLE
cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch 提示错误load extrisic file error,YAML exception:bad file

### ISSUE THREAD

**Issue by Li-xy11** [ApolloAuto/apollo#13753]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by jeroldchen** [comment]
@Li-xy11  Could you please post the snapshot of error message?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
