### ISSUE TITLE
No speed message shown in modules.control.proto.control_cmd.proto

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#13752]
**Describe the bug**
When getting the message from the channel `/apollo/control`, it does not show the speed value.

**To Reproduce**
There is the speed attribute in `ControlCommand` message, but when parsing it to string it is missing (by using `RecordReader`):
* Definition in the proto:
![Screenshot from 2021-05-05 15-23-34](https://user-images.githubusercontent.com/42797233/117108629-0d140100-adb6-11eb-9f36-f627029fbb7f.png)
* Used in the code:
![Screenshot from 2021-05-05 15-27-24](https://user-images.githubusercontent.com/42797233/117108891-6b40e400-adb6-11eb-85a6-54dcf87c7533.png)
* Output:

> ================================================================================
read [342] messages
channel_name -> /apollo/control
msgtime -> 1620182274178138589
msgnum -> 2634
msgtype -> apollo.control.ControlCommand
***After parse(if needed),the message is ->
header {
  timestamp_sec: 1620182274.1778834
  module_name: "control"
  sequence_num: 8718479
  lidar_timestamp: 1620182267181144832
  camera_timestamp: 0
  radar_timestamp: 0
  status {
    error_code: OK
  }
}
throttle: 39.10915995817429
brake: 0.0
steering_rate: 100.0
steering_target: -0.06347336173587831
acceleration: 1.5562662041293684
gear_location: GEAR_DRIVE
debug {
  simple_lon_debug {
    station_reference: -0.21777487008534857
    station_error: 0.4897856130825693
    station_error_limited: 0.4897856130825693
    preview_station_error: 1.6093243895356213
    speed_reference: 5.384371751538408
    speed_error: -0.145165615948061
    speed_controller_input_limited: -0.04720849333154713
    preview_speed_reference: 5.775615032449311
    preview_speed_error: 0.24607766496284178
    preview_acceleration_reference: 1.8979706051601024
    acceleration_cmd_closeloop: -0.34170440103073396
    acceleration_cmd: 1.5562662041293684
    acceleration_lookup: 1.5562662041293684
    speed_lookup: 5.529537200927734
    calibration_value: 39.10915995817429
    throttle_cmd: 39.10915995817429
    brake_cmd: 0.0
    is_full_stop: false
    slope_offset_compensation: -0.00016343699918443898
    current_station: -0.7075604831679179
    path_remain: 62.79051606656276
    pid_saturation_status: 0
    speed_offset: 0.09795712261651386
    current_speed: 5.529537200836042
    acceleration_reference: 2.0
    current_acceleration: 0.0
    acceleration_error: 2.0
    jerk_reference: 0.0
    current_jerk: 0.0
    jerk_error: 0.0
    current_matched_point {
      path_point {
        x: 587071.6035621514
        y: 4141462.572670841
      }
    }
    current_reference_point {
      path_point {
        x: 587071.6040481732
        y: 4141463.0624555927
      }
    }
    preview_reference_point {
      path_point {
        x: 587071.605246781
        y: 4141464.1819905792
      }
    }
  }
  simple_lat_debug {
    lateral_error: -0.00012828438860794367
    ref_heading: 1.5696882461512862
    heading: 1.5698408716604897
    heading_error: 0.0001526255092034745
    heading_error_rate: 0.0006288771531676729
    lateral_error_rate: 0.0008439484276745847
    curvature: -0.000110340511105544
    steer_angle: -0.06347336173587831
    steer_angle_feedforward: -0.029053152330131293
    steer_angle_lateral_contribution: 0.004599812552741785
    steer_angle_lateral_rate_contribution: -0.001130555097643681
    steer_angle_heading_contribution: -0.03368318795823802
    steer_angle_heading_rate_contribution: -0.004965382914795466
    steer_angle_feedback: -0.035179313417935384
    steering_position: -0.07225602120161057
    ref_speed: 5.529537200927734
    steer_angle_limited: -0.06423246574806668
    lateral_acceleration: 0.0
    lateral_jerk: 0.0
    ref_heading_rate: -0.0006288771531676729
    heading_rate: 0.0
    ref_heading_acceleration: 0.0
    heading_acceleration: 0.0
    heading_error_acceleration: 0.0
    ref_heading_jerk: 0.0
    heading_jerk: 0.0
    heading_error_jerk: 0.0
    lateral_error_feedback: -0.00012828438860794367
    heading_error_feedback: 0.0001526255092034745
    current_target_point {
      path_point {
        x: 587071.6049958749
        y: 4141463.9517052053
      }
    }
    steer_angle_feedback_augment: 0.0
    steer_mrac_enable_status: false
  }
  input_debug {
    localization_header {
      timestamp_sec: 1620182274.1339664
      module_name: "localization"
      sequence_num: 9750
    }
    canbus_header {
      timestamp_sec: 1620182267.2811449
      module_name: "chassis"
      sequence_num: 27
    }
    trajectory_header {
      timestamp_sec: 1620182274.1022925
      module_name: "planning"
      sequence_num: 6996
      lidar_timestamp: 1620182267181144832
      camera_timestamp: 0
      radar_timestamp: 0
    }
    latest_replan_trajectory_header {
      timestamp_sec: 1620182270.997513
      module_name: "planning"
      sequence_num: 6977
      lidar_timestamp: 1620182264281147648
      camera_timestamp: 0
      radar_timestamp: 0
    }
  }
}
signal {
  turn_signal: TURN_NONE
}
latency_stats {
  total_time_ms: 2.652708
  controller_time_ms: 1.9273757934570312
  controller_time_ms: 0.13947486877441406
  total_time_exceeded: false
}
engage_advice {
  advice: READY_TO_ENGAGE
}

**Expected behavior**
It should show speed value in each message.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] master

**Additional context**

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
