### ISSUE TITLE
Porting Webviz to Apollo

### ISSUE THREAD

**Issue by Alevs2R** [ApolloAuto/apollo#13773]
Apollo needs a feature-rich and easy-to-use visualization tool for developers.

I suggest to integrate [Webviz](https://webviz.io/) into Apollo as a separate module. Backend needs to be swapped from ROS to Cyber RT.

We have cyber visualizer, but it is very basic. We also have Dreamview, but it is not very flexible, all topics are hardcoded, there is no "windowed" system.

Who also wants this?

**Comment by daohu527** [comment]
Currently, we don't have the staff to do this. Your PR submissions are welcome.
