### ISSUE TITLE
How to get lidar reflection information?

### ISSUE THREAD

**Issue by JinRanYAO** [ApolloAuto/apollo#13777]
Hello, I run Apollo on LGSVL, but I can't get reflection information from lidar, only can get(x, y, z) , as a result I can't see something such as lanes. How can I solve it?
the lidar information I get(can't see lanes):
<img width="389" alt="11" src="https://user-images.githubusercontent.com/73015431/118385537-39dfd800-b642-11eb-89c4-051009115a23.png">
the videos on the Internet by others(can see lanes):
<img width="281" alt="123" src="https://user-images.githubusercontent.com/73015431/118385540-42d0a980-b642-11eb-9946-d9b8dc2cce51.png">
Look forward to your reply!

**Comment by daohu527** [comment]
You should first check lgsvl's lidar message pass intensity info. The pcd file have intensity info should be this type
```
pcl::PointCloud<pcl::PointXYZI>
```
if the point type is only 
```
pcl::PointCloud<pcl::PointXYZ>
```
which lose the intensity information

**Comment by JinRanYAO** [comment]
> You should first check lgsvl's lidar message pass intensity info. The pcd file have intensity info should be this type
> 
> ```
> pcl::PointCloud<pcl::PointXYZI>
> ```
> 
> if the point type is only
> 
> ```
> pcl::PointCloud<pcl::PointXYZ>
> ```
> 
> which lose the intensity information

Thank you for your reply. Could you tell me where can I set this setting?
Look forward to your reply!

**Comment by daohu527** [comment]
You can confirm the lidar message first, if not, then you need to check the configuration of lgsvl

**Comment by JinRanYAO** [comment]
> You can confirm the lidar message first, if not, then you need to check the configuration of lgsvl

OK, thank you for your reply!

**Comment by Juntu-hub** [comment]
Hello, I have come across this problem too. Did you fix it? @JinRanYAO

**Comment by JinRanYAO** [comment]
> Hello, I have come across this problem too. Did you fix it? @JinRanYAO

Hello, I haven't fixed it yet.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
