### ISSUE TITLE
Use case for v6.0.0 and v5.5.0 

### ISSUE THREAD

**Issue by tajinder96** [ApolloAuto/apollo#13784]
Hi, I noticed that v6.0.0 does not mention a particular use case. For example, v5.5.0 specifically targets the urban ODD. 
(1) Is v6.0.0 aimed at a specific ODD? 
(2) Currently the camera obstacle detection is not available in v6.0.0. When is the camera obstacle detection likely to be available for v6.0.0? 
(3) I see a mention in the [release notes of v5.5.0 ](https://github.com/ApolloAuto/apollo/releases/tag/v5.5.0) stating"PLEASE AVOID DRIVING THE VEHICLE ON THE HIGHWAY OR AT SPEEDS THAT ARE ABOVE OUR SUPPORTED THRESHOLD." What is the driving speed threshold for v5.5.0 and v6.0.0? 

Thank you!

**Comment by daohu527** [comment]
It is strongly recommended that you switch to the new version.

> (2) Currently the camera obstacle detection is not available in v6.0.0. When is the camera obstacle detection likely to be available for v6.0.0?

I don't know why 6.0 doesn't work, but the new version has been verified

> (3) I see a mention in the [release notes of v5.5.0 ](https://github.com/ApolloAuto/apollo/releases/tag/v5.5.0)stating"PLEASE AVOID DRIVING THE VEHICLE ON THE HIGHWAY OR AT SPEEDS THAT ARE ABOVE OUR SUPPORTED THRESHOLD." What is the driving speed threshold for v5.5.0 and v6.0.0?

You can find it in the config file, I'm not sure, but it's usually 60km/h
