### ISSUE TITLE
HD map

### ISSUE THREAD

**Issue by trieuthachvu** [ApolloAuto/apollo#13780]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: Master

I know HD map plays an important role in some modules like Localization, Perception and Planning. 
1. I would like to know if we need an HD map to run Apollo on the vehicle? If yes, then is that we have to create
the HD map in the area we perform the test?

2. Is it possible to run Apollo with simulator on a PC without HD map? Is yes then how we can set the destination point? Can we set the destination point through the navigation setup mode?

**Comment by daohu527** [comment]
> I would like to know if we need an HD map to run Apollo on the vehicle? If yes, then is that we have to create
the HD map in the area we perform the test?

Yes, there is a hd map service [link](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md)

>Is it possible to run Apollo with simulator on a PC without HD map? Is yes then how we can set the destination point? Can we set the destination point through the navigation setup mode?

no, if you want to run apollo, you do need a hd-map. you can work apollo with lgsvl, which is already have some hd-map in it.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
