### ISSUE TITLE
Fail to pull docker image of Apollo 6.0

### ISSUE THREAD

**Issue by MaisJamal** [ApolloAuto/apollo#13789]
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0 / master

### Steps to reproduce the issue:
- git clone https://github.com/ApolloAuto/apollo.git
- cd apollo
- bash docker/scripts/dev_start.sh

I was working with the branch "pre6" and everything works fine, then I wanted to upgrade and work with the release 6.0 or upper. I have tried many times to install the master or the 6th release, but I cannot run Apollo. It always fails to pull the docker image:  apolloauto/apollo:dev-x86_64-18.04-20210517_1712 . Can you please help me to solve the issue?

![Screenshot (262)](https://user-images.githubusercontent.com/17913075/118870771-93b8fa00-b8ef-11eb-9b7d-8a630f15273c.png)

**Comment by MaisJamal** [comment]
I managed to solve the issue. It was irrelevant to Apollo itself. It was a problem with the synchronization of my system local time, universal time, and RTC time.

**Comment by hyuwuhan** [comment]
Could you share how to solve the synchronization  problem, I am encountering same issue as well.
