### ISSUE TITLE
A camera perception bug 

### ISSUE THREAD

**Issue by HUI11126** [ApolloAuto/apollo#13788]
I use mainboard to load the camera perception module. This bug sometimes appears. But if I wait some time to play my record file, it disappears. 

mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -d /apollo/modules/perception/production/dag/dag_motion_service.dag
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0519 19:35:00.978008  4610 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -d /apollo/modules/perception/production/dag/dag_motion_service.dag 
I0519 19:35:00.978348  4610 global_data.cc:155] []host ip: 192.168.0.103
I0519 19:35:00.978479  4610 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 2 dag conf
I0519 19:35:00.978487  4610 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
I0519 19:35:00.978490  4610 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_motion_service.dag
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[NVBLAS] Cannot open default config file 'nvblas.conf'
[NVBLAS] Config parsed
[NVBLAS] CPU Blas library need to be provided
E0519 19:35:01.962169  4610 transform_wrapper.cc:119] [mainboard]one__param novatel  world  novatel front_6mm
E0519 19:35:01.962194  4610 transform_wrapper.cc:119] [mainboard]one__param novatel  world  novatel front_12mm
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
WARNING: The Permute Plugin is being deprecated and will be removed in the next TensorRT release. Please use the TensorRT Shuffle layer for Permute operation
E0519 19:35:46.428511  4612 transform_wrapper.cc:178] [mainboard] here world  novatel
E0519 19:35:46.428562  4612 transform_wrapper.cc:181] [mainboard]the transform before 801123 2.48959e+06 2.79142 -0.802161 -0.0116769 -0.00616972 -0.596962
E0519 19:35:46.428586  4612 transform_wrapper.cc:184] [mainboard] there
E0519 19:35:46.428598  4612 transform_wrapper.cc:214] [mainboard]Get pose timestamp: 1.60085e+09, pose: 
0000.287196 0-0.0238395 00-0.957575 00000801122
0000.957863 000.0113673 0000.286999 2.48959e+06
00.00404312 00-0.999651 000.0260997 00004.51511
00000000000 00000000000 00000000000 00000000001novatel2world 
0000.287196 00-0.957575 000.0238395 00000801123
0000.957863 0000.286999 0-0.0113673 2.48959e+06
00.00404312 000.0260997 0000.999651 00002.79142
00000000000 00000000000 00000000000 00000000001 sensor2world 
0000.287196 0-0.0238395 00-0.957575 00000801122
0000.957863 000.0113673 0000.286999 2.48959e+06
00.00404312 00-0.999651 000.0260997 00004.51511
00000000000 00000000000 00000000000 00000000001
Gtk-Message: 19:35:46.663: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:35:46.666: Failed to load module "canberra-gtk-module"
E0519 19:35:46.715886  4612 transform_wrapper.cc:178] [mainboard] here world  novatel
E0519 19:35:46.715900  4612 transform_wrapper.cc:181] [mainboard]the transform before 801121 2.48959e+06 2.77789 -0.801926 -0.0146188 -0.00706289 -0.597202
E0519 19:35:46.715911  4612 transform_wrapper.cc:184] [mainboard] there
E0519 19:35:46.715919  4612 transform_wrapper.cc:214] [mainboard]Get pose timestamp: 1.60085e+09, pose: 
0000.286599 0-0.0287887 00-0.957618 00000801120
0000.958031 000.0150105 0000.286271 2.48959e+06
00.00613298 00-0.999473 000.0318824 00004.50697
00000000000 00000000000 00000000000 00000000001novatel2world 
0000.286599 00-0.957618 000.0287887 00000801121
0000.958031 0000.286271 0-0.0150105 2.48959e+06
00.00613298 000.0318824 0000.999473 00002.77789
00000000000 00000000000 00000000000 00000000001 sensor2world 
0000.286599 0-0.0287887 00-0.957618 00000801120
0000.958031 000.0150105 0000.286271 2.48959e+06
00.00613298 00-0.999473 000.0318824 00004.50697
00000000000 00000000000 00000000000 00000000001

(Apollo Visualizer:4610): Gdk-ERROR **: 19:35:46.801: The program 'Apollo Visualizer' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 265 error_code 2 request_code 130 (MIT-SHM) minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

**Comment by daohu527** [comment]
I don't know if you solved the problem, please switch to the new version and try
