### ISSUE TITLE
Why did lgsvl use tcp communication?

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13795]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**:

Why did lgsvl use tcp communication?
I know there was udp communication first in Apollo.
When I tried to use lgsvl, it was using tcp communication.
I think udp communication is better when considering the speed of camera images and data. Is there a reason for using tcp communication?

Thank you.

**Comment by daohu527** [comment]
If it is an internal network, why not use tcp?

If you are a remote application and the network quality cannot be guaranteed, it is good to use udp

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
