### ISSUE TITLE
about cyber_recourder command

### ISSUE THREAD

**Issue by ghost** [ApolloAuto/apollo#13796]
I want to know how to use this tool to store the recorded data directly into the external hard disk，Because the hard disk of IPC is too small.I don't know how to execute this command:**cyber_recorder -a -o**......thanks.

**Comment by daohu527** [comment]
You can mount the external disk to the container and save it to the corresponding path with cyber_recorder

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
