### ISSUE TITLE
CANBus and vehicle chassis adaptation?

### ISSUE THREAD

**Issue by Abd0ul** [ApolloAuto/apollo#13793]
<div align="justify">
Hello the apollo team I have a few questions about the adaptation of the CANBus and the chassis. 

I would like to use a car that is not referenced on [the Apollo certification platform](https://apollo.auto/vehicle/certificate_en.html) but I don't have a list of essential/necessary signals to control a vehicle.

I noticed that this adaptation is done with a **DBC file** which contains the characteristics of the signals (ID, sizes, format, unit ....). To concervoir this DBC file we must be based on the chassis of the vehicle on which we have the motors, actuator and variators ... 

Can you give me some tracks or models of equipment compatible with the DBC file format (For example an inverter which forns signals in DBC file format?).

**What does Apollo use as equipment on DevKit vehicle chassis?**

Thanks in advance for the help.
</div>

**Comment by daohu527** [comment]
I don’t know how the DBC file is generated. 

But if you want to adapt to the chassis, you can directly write the code according to the vehicle type in the canbus to adapt.

**Comment by Abd0ul** [comment]
Hello @daohu527 thanks for your feedback but what are you talking about when you say **to write the code according to the type of vehicle in the canbus to adapt ??**

Apollo wants us to use the DBC file first to generate the communication protocol and the canbus adaptation code, then we need to modify the vehicle controller to get better results.

I don't have the DBC file for my vehicle, I would like to buy equipment (motor, variators .....) and mount it on a tricycle to make it work with Apollo. Any help/ideas are welcome

**Comment by daohu527** [comment]
You can write the code yourself, if there is no dbc file, it is actually not very difficult.

You ref to "modules/canbus/vehicle" and have a try

**Comment by daohu527** [comment]
Even if you use dbc, you can only generate protocol files. The files in these directories are used to read chassis information from canbus. 

You have also need to complete some code by yourself, for example "zhongyun_controller.h zhongyun_message_manager.h".

This is difficult to explain clearly in a few words, I suggest you look at the code first, and then ask for help! Because there is no detailed tutorial at the moment

**Comment by Abd0ul** [comment]
Exactly it's not easy to explain it in a few words as you say but I need a little help regarding the generation of the protocol files for reading the informations on the canbus.

Then I will develop the part of the code for the control logic (control logic, activation control signal, control signal function ...) in the corresponding directories.

**Comment by RANYABING** [comment]
Hello, I am also engaged in chassis adaptation of non officially certified vehicles recently. May I ask you some questions?
