### ISSUE TITLE
Convert .xml to Apollo HD map

### ISSUE THREAD

**Issue by Thinsheep** [ApolloAuto/apollo#13798]
We appreciate you go through Apollo documentation and search previous issues before creating a new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:Master

I try to convert .XML (Open Drive to Apollo HD map) following the instruction
https://github.com/ApolloAuto/apollo/tree/master/modules/map/data#difference-between-base_map-routing_map-and-sim_map

./bazel-bin/modules/map/tools/sim_map_generator --map_dir=/apollo/modules/map/data/demo/In --output_dir=/apollo/modules/map/data/demo/Out

./scripts/generate_routing_topo_graph.sh --map_dir modules/map/data/demo

I got the below error:

E0522 18:12:34.117038 196440 opendrive_adapter.cc:44] []fail to parse opendrive header, Error parsing header attributes
E0522 18:12:34.122706 196440 graph_creator.cc:67] [routing]Failed to load base map file from modules/map/data/demo/base_map.xml
F0522 18:12:34.122728 196440 topo_creator.cc:38] Check failed: creator.Create() [routing]Create routing topo failed!

Some other people were getting the same error before I do not know if someone knows solution #5012

**Comment by devynliu** [comment]
hello，this issue must be created by your . xml fill. Please check the xml file format. maybe you miss some label.

**Comment by Thinsheep** [comment]
Hi @devynliu 

I tried to use sanfrancisco.xodr map from LGSVL but I got the same error.

I follow these steps:
- Change the name of sanfrancisco.xodr to base_map.xml and put it to data/demo folder.
- Run ./apollo.sh build in docker
then run ./bazel-bin/modules/map/tools/proto_map_generator --map_dir=/apollo/modules/map/data/demo/In --output_dir=/apollo/modules/map/data/demo/Out
I got the same error.
Do I miss anything here?

**Comment by Zivecho** [comment]
hello, the content format of apollo HDmap (.xml file) is very different from that of standard opendrive (.xodr file). so you cannot convert sanfrancisco.xodr to apollo hdmap using proto_map_generator. you may try maptool in  LGSVL or roadrunner. may you succeed.

**Comment by Thinsheep** [comment]
Hi @Zivecho,
Thanks for your information.
I would like to inport an opendrive (.xodr) map and export Apollo HD map? I also also have 3D world graphic in openscenegraph (.osg and .ive)
1. Roadrunner require the license so I cannot use it. As I read the documents, it requires two inputs file (.xodr/.xml) and .fbx file.
I do not have .fbx file. I am not sure if .xodr file alone is enough to export Apollo HD map? (I would like to know it first before trying to get license somewhere).

2. The second option is Maptool in LGSVL, I guess it is Unity. I got it installed but I have no idea how to import (.xodr) file into Unity? I saw may people asked for the same question on the internet but no once got the answer.  Do you know how to import this file to Unity?

**Comment by InterKnight** [comment]
Hi, @Thinsheep ，
Thses links describe how to import/export  HDmap to/from LGSVL
https://www.svlsimulator.com/docs/simulation-content/map-annotation/#export-map-annotations
https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/#adding-an-hd-map

But fristly, you need build LGSVL from source
https://www.svlsimulator.com/docs/installation-guide/build-instructions/

**Comment by Thinsheep** [comment]
@InterKnight,
Thanks for your information. 
#11181
I have tried the method in this post but I got exactly errror like other person mentioned on the post.
As I understand it is because Standard OpenDrive (.xodr/.xml) is different from Apollo (.xml). I guess that is the reason why a lot of people request Apollo HD map specification to modify it. I tried to request this file in many different posts but not successful. 
look like Apollo no longer shares this spec. #3005

Regarding links which you provided about import/export HD map. HD map is a .bin file. I only have standard OpenDrive (.xodr).
Import HD map means importing .bin files. I do not have it. 

Did you successful convert standard OpenDrive(.xodr) to HD map (.bin)? Did you try this method #11181?
Please correct me if something wrong and give me better understanding ?
Thank you.

**Comment by InterKnight** [comment]
Hi @Thinsheep 
If you only want a Apollo HDmap of sanfrancisco, LGSVL has provided it : https://content.lgsvlsimulator.com/maps/sanfrancisco/
What's more, you can import xodr file into LGSVL and export Apollo HDmap. I tried this precess and got a Apollo HDmap of sanfrancisco. But in the same time, I notice the bin file which I exchanged from xodr is different from the one I download from above link. 
What's I'm not sure now is: if the bin file which exchanged from xodr is useable? And How to use this bin file in Apollo? 
These are two bin files of  Apollo HDmap of sanfrancisco, base_map.bin is provided by offical and base_map_1.bin is exchanged from xodr.
 
[bin_file.zip](https://github.com/ApolloAuto/apollo/files/6646061/bin_file.zip)

<img width="757" alt="Snipaste_2021-06-14_11-21-59" src="https://user-images.githubusercontent.com/48618733/121849209-a3283900-cd1d-11eb-94be-d6fa3f30d991.png">

**Comment by Thinsheep** [comment]
@InterKnight 
You are right, thank you.  Sorry, my bad, yes I am able to convert it to Apollo HD map but like you said I have not tried if the file really works. Sanfrancisco is just an example because I want to use (.xodr) file from another source and the problem is that this tool only supports OpenDrive version 1.4. My (.xodr) version is 1.5.

**Comment by InterKnight** [comment]
Hi @Thinsheep
this is the difference between OpenDrive 1.4 and 1.5, but it is regrettable that I can't find a tool to exchange opendrive 1.5 to 1.4.
https://www.asam.net/index.php?eID=dumpFile&t=f&f=3789&token=46b9988f99a65f7bcd4261825e618610c31c18a6

maybe you can try Roadrunner. As far as I know, fbx file is 3D model file, it may not necessary.

I appreciate it if you can post any progress of this problem!

**Comment by Zivecho** [comment]
Hi @Thinsheep
last year, I spent about one week trying to development a tool that converting from .xodr to apollo HDmap. But failed. I found that:
1. content of .xodr file is different from apollo HDmap. e.g. no junction polygon data that apollo HDmap has in .xodr file; no left and right boundries in .xodr file so that you have to calculate by yourself; and so on.
2. After importing .xodr file into LGSLV, you have to edit map such as draw junctions. I tried but failed too.
maybe you can try Roadrunner but as you mentioned Roadrunner require the license. However, you can apply for a education license.

**Comment by InterKnight** [comment]
Hi @Zivecho 
Do you have the Apollo HDmap spec? Can you plesae send to lanmolingyue@live.com? Thank you!

**Comment by MaisJamal** [comment]
Hello @InterKnight 
if you got the Apollo HDmap spec, can you please send it to me mayssjamal@gmail.com, I have alos requested it on #3005 but they haven't sent it.

**Comment by Zivecho** [comment]
> Hi @Zivecho
> Do you have the Apollo HDmap spec? Could you plesae send to [lanmolingyue@live.com](mailto:lanmolingyue@live.com)? Thank you!

Sorry I have no apollo HDmap spec.  I reviewed code in apollo HDmap parser, read spec of Opendrive, compared them and finally got the conclusion.

**Comment by trieuthachvu** [comment]
@InterKnight 
Thanks for your information.
I am not sure if Roadruner do the better job. I am now a bit busy and can not test it now. I will come back later.

@Zivecho 
Thank you for sharing your experience

@MaisJamal 
I did leave my email in different posts but I have not received any reply. Look like only few people from early days got the spec but Apollo did recommend not sharing the spec. I was trying to contact many people who left their email in the post earlier but the result was not positive.

**Comment by trieuthachvu** [comment]
I try with both Unity LGSVL and RoadRuner.
Unity LGSVL: as we already know. We can only use OpenDrive 1.4 not 1.5. Luckily, I have one file in 1.4 to test
@Zivecho right, no junctions, left and right boundary. Only left and right lane of main road are remained.

RoadRuner: 
Steps:
1.Import xodr file
2. convert to RoadRunner standard format (I try not convert and directly go to export HD map, it normally ends up with error)
3. Export Apollo HD map (either .xml or .bin)

- Some xodr files cannot be imported, just nothing showing when I drag it into the editor
- some xodr files with large routing network and junctions cannot be converted to standard RoadRunner and normally end up with software crashing.
- Some simple road maps pass the conversion step but it reports Apollo HD map conversion is successfully created with some errors and warnings.
- I use these Apollo HD maps to create sim_map and routing_map and check them in Apollo. The position of ego vehicle is set away from initial position (just somewhere on the boundary of the road)

Most of the maps, I take from VTD simulator. It seems to be that you need to edit the map after importing to get it working correct in Apollo.

**Comment by YanBC** [comment]
Here is the Apollo 3.0 opendrive spec. I don't know if it's changed since then.
[EN_APOLLO_HDMap_OpenDrive_Specs_A3.0.1.pdf](https://github.com/ApolloAuto/apollo/files/7653613/EN_APOLLO_HDMap_OpenDrive_Specs_A3.0.1.pdf)

**Comment by InterKnight** [comment]
> Here is the Apollo 3.0 opendrive spec. I don't know if it's changed since then. [EN_APOLLO_HDMap_OpenDrive_Specs_A3.0.1.pdf](https://github.com/ApolloAuto/apollo/files/7653613/EN_APOLLO_HDMap_OpenDrive_Specs_A3.0.1.pdf)

Thank you very much！

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
