### ISSUE TITLE
does the ros in apollo is the ROS-Comm: (Bare Bones)？

### ISSUE THREAD

**Issue by Jackie2016** [ApolloAuto/apollo#138]
hi,expert
i want to know what package of indigo the ros in apollo is?it is a Desktop-Full Install or Desktop Install or ROS-Comm: (Bare Bones) ?i know ros in apollo must be added something in traditional ROS,but what is  original source package from ROS indigo?thanks

**Comment by quning78** [comment]
The rule is, we try to include the minimum set of ros packages to support Apollo 1.0 release. So it's neither full desktop distribution or just ros-comm. It's more like full ros-comm and a bunch of necessary packages from ROS.

To get more details, we have include almost everything from ros-comm under 

https://github.com/ApolloAuto/apollo-platform/tree/master/ros/ros_comm

which you will see the modifications with our features inside there as well.

For all the other packages included other than ros_comm, you will see the list from this directory:

https://github.com/ApolloAuto/apollo-platform/tree/master/ros

Let me know if you have any other questions.

**Comment by fengqikai1414** [comment]
Additional, the package [ros_comm](https://github.com/ApolloAuto/apollo-platform/tree/master/ros/ros_comm) in [ApolloAuto/apollo-platform](https://github.com/ApolloAuto/apollo-platform) is base on the tag [ros-comm 1.11.21](https://github.com/ros/ros_comm/tree/1.11.21). So you can compare the difference between each version.

**Comment by niise** [comment]
any document about how to add other ros package in the apollo-platform ?

**Comment by quning78** [comment]
You can add your own package based on:

https://github.com/ApolloAuto/apollo-platform

And then build up your own release package from there.

**Comment by Zhenni17** [comment]
This issue appears to be resolved. I am closing the issue, and feel free to re-open it if I missed anything.
