### ISSUE TITLE
pb_msgs/InsStatus message definitions

### ISSUE THREAD

**Issue by sisaha9** [ApolloAuto/apollo#13800]
I was reviewing the pb_msgs and came across this: https://perceptionengine.jp/blog/apollo/apollo-messages/

I know this platform is no longer in ROS and a lot of this does not hold true anymore. But I was wondering where could I see the message definitions and see what each message stand for. In particular I wanted to understand pb_msgs/InsStat and what the different integer values in ins_status and pos stand for. Again I know this is not supported anymore but a project requires using topics defined in pb_msgs so I am trying to recreate them using the ROS standard messages

**Comment by daohu527** [comment]
@sisaha9 It is recommended to migrate to the new version. sorry, I can't provide effective help with this question!
