### ISSUE TITLE
Apollo5.5与LGSVL桥接后，如何使用Apollo的路径规划？

### ISSUE THREAD

**Issue by lbm7926** [ApolloAuto/apollo#13802]
Apollo5.5与LGSVL桥接后，使用Apollo的路径规划功能添加点位后，点击发送点位信息，apollo中的车未按照点位规划移动，LGSVL中车辆也没有移动

**Comment by daohu527** [comment]
You can provide more effective information under observation to solve the problem more conveniently.

Here are some ideas
1. check the apollo log in `data\log` to find if some error messages
2. check the lgsvl config
3. check the network and so on

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
