### ISSUE TITLE
apollo::localization::Gps message type is not available

### ISSUE THREAD

**Issue by trieuthachvu** [ApolloAuto/apollo#13804]
Hi,
I want to publish message type: apollo::localization::Gps to cyber channel /apollo/sensor/gnss/odometry
I use the package ApolloToRos (using Apollo 3.5)
https://github.com/AuroAi/apollo_ros_bridge

However, it reports: fatal error: modules/localization/proto/gps.pb.h: No such file or directory
![image](https://user-images.githubusercontent.com/53098029/119556062-db7fcb80-bd9e-11eb-8034-f912da7b4509.png)

I check the bazel-out/local-fastbuild/genfile/modules/localization/proto
I could not find gps.pb.cc and gps.pb.h there.

![image](https://user-images.githubusercontent.com/53098029/119556842-c48da900-bd9f-11eb-86f9-6b912ad28bf4.png)

#include "modules/localization/proto/gps.pb.h" report error
Does anyone know what is missing from my package? and how to add Gps to apollo:localization.
Currently, only apollo::localization::LocalizationEstimate and apollo::localization::Pose are valid.

**Comment by daohu527** [comment]
apollo 3.5 do have the "gps.proto", so please check if you compile correctly

**Comment by Thinsheep** [comment]
@daohu527 
Yes, it does have gps.proto
The compilation is successfully. Is there any chance to work around it?
![image](https://user-images.githubusercontent.com/52489127/119872857-342ca100-bf24-11eb-9803-65721d415fd5.png)

**Comment by daohu527** [comment]
I found the file in "bazel-genfiles/modules/localization/proto",  although I don't quite understand your code logic!

**Comment by Thinsheep** [comment]
@daohu527 
I build this package only:
https://github.com/AuroAi/apollo_ros_bridge

gps.proto is available but not gps.pb.h and gps.pb.cc.
I am thinking about copying gps.pb.h and gps.pb.cc files from Apollo 3.5 and put them in this package's folder?
Can I get these files (version 3.5) from somewhere? my PC GPU does not support building Apollo 3.5.

**Comment by trieuthachvu** [comment]
@daohu527 
I build this package only:
https://github.com/AuroAi/apollo_ros_bridge

gps.proto is available but not gps.pb.h and gps.pb.cc.
I am thinking about copying gps.pb.h and gps.pb.cc files from Apollo 3.5 and put them in this package's folder?
Can I get these files (version 3.5) from somewhere? my PC GPU does not support building Apollo 3.5.

**Comment by daohu527** [comment]
apollo 3.5 can build only with cpu, you can try it, anyway this does not belong to this project

**Comment by trieuthachvu** [comment]
Hi @daohu527 
I can build apollo 3.5 only with cpu. 
I found the solution by adding gps.proto to build file
I try to convert GPS Cyber to ROS
![image](https://user-images.githubusercontent.com/53098029/120921508-4e087980-c6c4-11eb-88d2-972f258aef75.png)
And I got an error as below
![image](https://user-images.githubusercontent.com/53098029/120921546-7bedbe00-c6c4-11eb-98f3-a18e78a977f6.png)
I do not some researches about this error and it looks like I assign const to non-const. I have tried to modify the code in many different way to fix the error but not successfully.
If you know something about this could you please give me some suggestion?

**Comment by daohu527** [comment]
"gps_apollo->localization" should not be const, if you want to modify it

**Comment by trieuthachvu** [comment]
> "gps_apollo->localization" should not be const, if you want to modify it

Yes, you are right.
Thank you, I got it working. 
I have a question regarding camera sensor. Normally, we have two messages are camerainfo and Image (compressedImage)
However, I  find only one topic(Cyber channel) to write these camera sensor data
/apollo/sensor/camera/front_6mm/image/compressed
Is it possible? (two different message types may be not possible to write to one topics)
Normally, camerainfo will not change. I am think about write Image data to this channel. If I do not provide any information about camerainfo. Will Apollo use the default values?

**Comment by daohu527** [comment]
> two different message types may be not possible to write to one topics

Yes, one topic corresponds to one message type. If you want two send two or more messages, you should publish two or more topics

By the way, if you add a question that is not related to this issue, I suggest you to open a new one.

**Comment by trieuthachvu** [comment]
@daohu527 
Yes, it is such a long topic, thanks for your support. I created another topic for the image/

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
