### ISSUE TITLE
Transform error at hesai(Pandar64)

### ISSUE THREAD

**Issue by rlaehddls9** [ApolloAuto/apollo#13806]
env : ubuntu 18.04, apollo v6.0

I want to run the hesai(Pandar64). 
Specifically, I want to visualize the environment around the hesai lidar(Pandar64).
However, the following error occurs.

When I run this code ('cyber_launch start /apollo/modules/drivers/lidar/hesai/launch/hesai64.launch') in docker below problems are happened. 

[hesai  ]  E0526 20:40:07.985287  8025 compensator.cc:34] [velodyne]Can not find transform. 946699271142493952 frame_id:hesai64 Error info: canTransform: target_frame world does not exist. canTransform: source_frame hesai64 does not exist.:timeout

Even if the above error occurs, cyber_visualizer visualizes the point cloud data received by hesai as shown in the picture below. 

![image](https://user-images.githubusercontent.com/79086973/119669876-5fa38300-be73-11eb-996b-88516f763baf.png)

However, the data in this picture does not properly visualize the surrounding environment. 
It seems that transform should be done, but if I go to the apollo/modules/transform path, velodyne's transform launch file exists, but hesai's transform launch file does not seem to exist.

Question 
I would like to ask for advice on how to perfrom the transform of hesai(pandar64) so that the surrounding environment cat be well visualized with a compensator.

**Comment by rlaehddls9** [comment]
> env : ubuntu 18.04, apollo v6.0
> 
> I want to run the hesai(Pandar64).
> Specifically, I want to visualize the environment around the hesai lidar(Pandar64).
> However, the following error occurs.
> 
> When I run this code ('cyber_launch start /apollo/modules/drivers/lidar/hesai/launch/hesai64.launch') in docker below problems are happened.
> 
> [hesai ] E0526 20:40:07.985287 8025 compensator.cc:34] [velodyne]Can not find transform. 946699271142493952 frame_id:hesai64 Error info: canTransform: target_frame world does not exist. canTransform: source_frame hesai64 does not exist.:timeout
> 
> Even if the above error occurs, cyber_visualizer visualizes the point cloud data received by hesai as shown in the picture below.
> 
> ![image](https://user-images.githubusercontent.com/79086973/119669876-5fa38300-be73-11eb-996b-88516f763baf.png)
> 
> However, the data in this picture does not properly visualize the surrounding environment.
> It seems that transform should be done, but if I go to the apollo/modules/transform path, velodyne's transform launch file exists, but hesai's transform launch file does not seem to exist.
> 
> Question
> I would like to ask for advice on how to perfrom the transform of hesai(pandar64) so that the surrounding environment cat be well visualized with a compensator.

**Comment by lxa199709** [comment]
excuse me ,can you tell me do you solve the problem at the end?
