### ISSUE TITLE
About the usage of lgsvl.

### ISSUE THREAD

**Issue by lbm7926** [ApolloAuto/apollo#13810]
First of all, in the SIM control mode of Apollo dreamview, I can realize the path planning and start the vehicle running normally.

When lgsvl is bridged with dreamview, using keyboard to control vehicle in lgsvl can also realize synchronous operation.

Now there is a problem, when lgsvl is bridged with dreamview, how to realize path planning in lgsvl to make vehicles run automatically.

**Comment by daohu527** [comment]
Pls ref to the lgsvl doc [link](https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
