### ISSUE TITLE
How can I trigger avoiding an obstacle function in apollo master?

### ISSUE THREAD

**Issue by shandaolu** [ApolloAuto/apollo#13825]
Hello:
How to configure planning_config.txt and planning_config_pb.txt to achieve obstacle avoidance in Sim simulation mode. 
Current step: 
1.Place a static obstacle 100 meters in front of the ego vehicle;
2.Choose a path that can pass through an obstacle;
3.The vehicle stopped at a distance of 26.8 from the obstacle and did not realize the lane-changing function.
How can I trigger avoiding an obstabcle function?

**Comment by daohu527** [comment]
could you pls check the config in "modules/planning/conf/planning.conf"
```
--prioritize_change_lane
--min_length_for_lane_change=5.0
```

**Comment by shandaolu** [comment]
Thank you for your reply very much. I check the config  in "modules/planning/conf/planning.conf" again.  
Config file default configuration.
`--prioritize_change_lane
--min_length_for_lane_change=5.0`
I also restart apollo‘s Planning and Routing modules.  But the vehicle stopped 27 meters away from the obstacle.  How can I achieve automatic obstacle avoidance? Is it because of the lack of a reference line? Look forward to your reply. Thank you.

![Screenshot from 2021-06-07 10-24-52](https://user-images.githubusercontent.com/35679679/120952411-8b7d0d80-c77d-11eb-9cfa-5daee04e1ca3.png)

**Comment by shandaolu** [comment]
Thank you for your reply very much. I check the config  in "modules/planning/conf/planning.conf" again.  
Config file default configuration.
`--prioritize_change_lane
--min_length_for_lane_change=5.0`
I also restart apollo‘s Planning and Routing modules.  But the vehicle stopped 27 meters away from the obstacle.  How can I achieve automatic obstacle avoidance? Is it because of the lack of a reference line? Look forward to your reply. Thank you.

![Screenshot from 2021-06-07 10-24-52](https://user-images.githubusercontent.com/35679679/120952411-8b7d0d80-c77d-11eb-9cfa-5daee04e1ca3.png)

**Comment by daohu527** [comment]
1. Then could you pls check the lane. Lanes adjacent to the current lane are allowed to change lanes
2. Check whether the lane change decision is triggered

**Comment by shandaolu** [comment]
Thank you for your  reply. @daohu527 
1.How could I check the lane? By base_map.txt? Could you give me more hints?
I choose  the left lane as my destination through the apollo's routing. Vehicles can change lanes on this map. Is it proof that is it that the left lane adjacent to the current lane is allowed to change lane. Just like below.
![Screenshot from 2021-06-07 14-41-38](https://user-images.githubusercontent.com/35679679/120971102-d8bda700-c79e-11eb-9187-8eb05137199d.png)

2.According to your instructions, I check the planning module by cyber.  The decision gives a stop command. The chang_lane_type is forward. No lane change command is given. Can I set out to avoid obstacles automatically in this scene? 
![Screenshot from 2021-06-07 14-57-00](https://user-images.githubusercontent.com/35679679/120972771-af9e1600-c7a0-11eb-84d5-7e85d1a3ffb7.png)

**Comment by daohu527** [comment]
I need to test it and feedback then

**Comment by shandaolu** [comment]
@daohu527 Thank you. Looking forward to your reply. I don't know how to trigger the lane change function automatically. My apollo's version is master. The os is ubuntu 18.04.

**Comment by GabrielZZZ** [comment]
Hi @shandaolu, can you tell me how to read the data of the obstacle distance from cyber_monitor? My planning module interface does not contain as much information as yours. Thank you

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
