### ISSUE TITLE
Valet Parking doesn't work on different maps

### ISSUE THREAD

**Issue by MaisJamal** [ApolloAuto/apollo#13822]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

I have build a scene in RoadRunner (mathworks) which includes many parking spots, and parking lot, exported them to base_map.bin and generated the routing and sim files, but in Dreamview the parking spots are not showing.

![Screenshot from 2021-06-02 13-56-21](https://user-images.githubusercontent.com/17913075/120473901-32456080-c3b0-11eb-8f89-ad1fe69990d5.png)

![Screenshot from 2021-06-02 13-55-19](https://user-images.githubusercontent.com/17913075/120473934-396c6e80-c3b0-11eb-89e6-955417364da4.png)

I am trying to understand how Apollo finds parking spots information, and in which files, so I can add a parking spot manually. Can you please guide me, how to add a parking spot manually? should I add it to the base_map.xml or, base_map.txt or default_end_way_point.txt? and where can I find an example file including a parking spot in the map. I have checked of course all the available public Apollo maps with parking, but all of them are provided in .bin format so I can't understand how it works.

**Comment by daohu527** [comment]
> I am trying to understand how Apollo finds parking spots information, and in which files, so I can add a parking spot manually. Can you please guide me, how to add a parking spot manually? should I add it to the base_map.xml or, base_map.txt or default_end_way_point.txt?

You can ref to [map_parking_space.proto](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/map/proto/map_parking_space.proto) for parking space format. You should check the sim_map.txt, because sim_map.txt is used for dreamview. 

In fact, sim_map is generated by base_map, so you add to base_map and then generate sim_map.


> and where can I find an example file including a parking spot in the map. I have checked of course all the available public Apollo maps with parking, but all of them are provided in .bin format so I can't understand how it works.


you can ref to "san_mateo" and "sunnyvale_with_two_offices", below is an example you should add "parking_space" and "parking_space_overlap_info"

```
parking_space {
  id {
    id: "11544"
  }
  polygon {
    point {
      x: 587198.6538108855
      y: 4141416.6057218537
      z: 0
    }
    point {
      x: 587201.24532293412
      y: 4141415.9138005795
      z: 0
    }
    point {
      x: 587200.11132028769
      y: 4141410.9443679708
      z: 0
    }
    point {
      x: 587197.50218934589
      y: 4141411.6283384813
      z: 0
    }
  }
  overlap_id {
    id: "overlap_2659"
  }
  overlap_id {
    id: "overlap_4399"
  }
  heading: 1.345454
}

overlap {
  id {
    id: "overlap_2659"
  }
  object {
    id {
      id: "11564dup1_1_-1"
    }
    lane_overlap_info {
      start_s: 0
      end_s: 0
      is_merge: false
    }
  }
  object {
    id {
      id: "11544"
    }
    parking_space_overlap_info {
    }
  }
}
```

**Comment by MaisJamal** [comment]
Thanks for the quick response and the example. I have added a parking spot to the base_map.txt file and generated the sim file. I have also added default_end_way_point to test the parking. Now I can see the spot in Dreamview, but when I choose the point of interest, the ego follows the routing request and doesn't park in the spot. Can you please tell me how to turn on the open space planner to perform the parking?
![Screenshot (276)](https://user-images.githubusercontent.com/17913075/120817575-7bd1af00-c55a-11eb-8e7a-033b592f016c.png)
![Screenshot (277)](https://user-images.githubusercontent.com/17913075/120817579-7d02dc00-c55a-11eb-87a7-2fd458ef6f56.png)

**Comment by daohu527** [comment]
Pls ref to https://github.com/ApolloAuto/apollo/issues/12165 first. I will check it later

**Comment by MaisJamal** [comment]
I have checked the link, I've sent a parking request manually, everything is as suggested, but still, the open space planner is not triggered, can you please tell me where exactly in the planning module, the open space planner is triggered? I have checked planning_component.cc , it has only two cases: NaviPlanning and OnLanePlanning.
Also, I have checked all parking/open_space_planner related issues, I couldn't find a single person who succeded to run the parking on any map other than "san_mateo" and "sunnyvale_with_two_offices", which are both not available for the public, would you please consider providing a parking scenario tutorial or a public map XML file that includes it.

**Comment by ntutangyun** [comment]
maybe you could try out this example: 
https://content.lgsvlsimulator.com/maps/autonomoustuff/

**Comment by yufeilongyuan** [comment]
> I have checked the link, I've sent a parking request manually, everything is as suggested, but still, the open space planner is not triggered, can you please tell me where exactly in the planning module, the open space planner is triggered? I have checked planning_component.cc , it has only two cases: NaviPlanning and OnLanePlanning.
> Also, I have checked all parking/open_space_planner related issues, I couldn't find a single person who succeded to run the parking on any map other than "san_mateo" and "sunnyvale_with_two_offices", which are both not available for the public, would you please consider providing a parking scenario tutorial or a public map XML file that includes it.

Hello, I have the same problem. Have you solved it? thank you

**Comment by MaisJamal** [comment]
@ntutangyun 
I have checked all parking spots on this map, it's always performing the LANE_FOLLOW scenario, and never turning on the Valet parking scenario. However, the same way of sending a parking request is working in sunnyvale_with_two_offices, so I think the problem is in the parking definition in base_map.txt, can you please tell me, is it enough to declare parking_space and overlap with the closest lane, for representing the parking space correctly to invoke the open space planner? 
or can you please tell me where in the code, it's checking for conditions to invoke the open space planner, so I can compare the conditions in the two maps?

**Comment by MaisJamal** [comment]
@yufeilongyuan Hello, not yet, as you can see, I'm still struggling with the problem :(

**Comment by daohu527** [comment]
## finite state machine
First, enter various scenarios through a finite state machine. I don't think it will be a problem in this function and the main entry is `ScenarioManager::ScenarioDispatchNonLearning`.
https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/planning/scenarios/scenario_manager.cc#L906-L908



## condition
Then you can find `IsTransferable` will return `ScenarioConfig::VALET_PARKING`, so maybe you should check this deeply.
https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/planning/scenarios/scenario_manager.cc#L725-L730

Hope this will help you!

**Comment by yufeilongyuan** [comment]
I didn't encounter the unrealistic problem of parking space in dreanview, but I don't know whether the parking function is normal. Recently, I'm studying the related functions of parking. I hope I can communicate more.
![2021-06-17 09-24-29屏幕截图](https://user-images.githubusercontent.com/23471410/122316591-bb32cf00-cf4e-11eb-888d-3eb812fdecf2.png)

**Comment by MaisJamal** [comment]
@daohu527 Thanks a lot. 
By tracking the function IsTransferable, I figured out that it's not able to find the near path (lane). The problem was that I haven't defined the overlap in the lane specifications in base_map.txt because I'm not quite familiar with Apollo HDmap specifications. For people who want to add a parking spot manually, here is what you should do with the file base_map.txt:
1. add the parking spot details including 4 points of the polygon, overlap_id with the near lane and heading, ex:
```txt
parking_space {
  id {
    id: "11543"
  }
  polygon {
    point {
      x: 388037.50218934589
      y: 221149.6057218537
      z: 0
    }
    point {
      x: 388041.24532293412
      y: 221149.6057218537
      z: 0
    }
    point {
      x: 388041.24532293412
      y: 221143.9443679708
      z: 0
    }
    point {
      x: 388037.50218934589
      y: 221143.9443679708
      z: 0
    }
  }
  overlap_id {
    id: "overlap_3"
  }
  heading: 1.570796
}
```
2. add overlap details , ex:
```txt
overlap {
  id {
    id: "overlap_3"
  }
  object {
    id {
      id: "0_0_-1"
    }
    lane_overlap_info {
      start_s: 0
      end_s: 0
      is_merge: false
    }
  }
  object {
    id {
      id: "11543"
    }
    parking_space_overlap_info {
    }
  }
}
```
3. add overlap_id to the near lane:
lane {
  id {
    id: "0_0_-1"
  }
  ...
  length: 111.58001708984375
  speed_limit: 97.221951484680176
  overlap_id {
    id: "overlap_3"
  }
  ...
  direction: FORWARD
  ...
}
4. make sure the heading is set correctly in the direction of the near lane.


![Screenshot (283)](https://user-images.githubusercontent.com/17913075/122568638-a2abdd00-d052-11eb-8792-f9de74da9909.png)

**Comment by daohu527** [comment]
Good job! :+1: 

The overlap is the bridge connecting lane and other objects like traffic light, stop sign, parking lot and so on. There is a small question about overlap, which may not have an impact at the moment.

`start_s` and `end_s` should be the parking lot's position on the lane, for example (100, 105)

```
overlap {
  id {
    id: "overlap_3"
  }
  object {
    id {
      id: "0_0_-1"
    }
    lane_overlap_info {
      start_s: 0                  // start_s is the parking lot's start position on the lane
      end_s: 0                   // end_s is the parking lot's end position on the lane
      is_merge: false
    }
  }
  object {
    id {
      id: "11543"
    }
    parking_space_overlap_info {
    }
  }
}

```

**Comment by yufeilongyuan** [comment]
Well done. It seems that you have solved the problem. Yes, I guess these problems are not Apollo's, but Roadrunner's. Because, I use LGSVL to draw HD-maps, and you do not have these problems.
