### ISSUE TITLE
[Dreamview] ADC driving outside the boundaries of the map 

### ISSUE THREAD

**Issue by salmanee** [ApolloAuto/apollo#13830]
### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **Apollo installed from**: Source 
- **Apollo version**: 6.0

### Steps to reproduce the issue:
- Launch dreamview and select borregas ave as the map
- Enable sim control 
- Send a routing request message with the adc initial and end location (selected randomly from the map)

### Supporting materials (screenshots, command lines, code/script snippets):
The adc drives outside the boundaries of the map as shown in the screenshots below:

<img width="986" alt="Screen Shot 2021-06-02 at 1 30 13 PM" src="https://user-images.githubusercontent.com/14792262/120754282-4b8a0200-c4c1-11eb-8dc0-b5976feb883f.png">
<img width="651" alt="Screen Shot 2021-06-02 at 1 57 37 PM" src="https://user-images.githubusercontent.com/14792262/120754286-4cbb2f00-c4c1-11eb-91a0-75619bd42f01.png">

**Comment by daohu527** [comment]
I am really confused by this question, I check the map, there is no road outside the map. So you may not success to send the routing request!

**Comment by salmanee** [comment]
@daohu527 That's the issue. In produced few driving scenarios with different routing  information and I came across this issue. I noticed that the planning in some cases produces a path outside the map boundaries. Not sure if this is a bug.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
