### ISSUE TITLE
Apollo 3.0 ros bridge NOT WORK

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#13836]
Hi I am using Ubuntu 18.04 on docker. I am using Apollo 3.0

### Steps to reproduce the issue:
I followed this tutorial: https://www.svlsimulator.com/docs/system-under-test/apollo3-0-instructions/

I am trying to build Apollo 3.0 alongside the SVL simulator. I have already set the Apollo 3.0 custom ROS Apollo bridge inside SVL according to @hadiTab:

![image](https://user-images.githubusercontent.com/43826438/120858344-07e2d700-c559-11eb-899c-6b42cfebdda0.png)

Following this tutorial: https://www.svlsimulator.com/docs/archive/2020.01/apollo-instructions/

Speciffically in step:
`git clone --recurse-submodules https://github.com/lgsvl/apollo.git`

If I clone this repo I am going to have just the cyber folder/ cyber briged, and not the ros_pkgs folder and the rosbridge which is required later for a subsequent step present in his tutorial:

![image](https://user-images.githubusercontent.com/43826438/120858571-585a3480-c559-11eb-93ae-ab4625c21688.png)

I have found in @hadiTab repo the ros_pkgs folder: https://github.com/lgsvl/apollo-3.0
This repo is different from the tutorial repo: https://github.com/ApolloAuto/apollo

Then I have cloned both repo inside my Apollo 3.0 created folder:

![image](https://user-images.githubusercontent.com/43826438/120858740-98b9b280-c559-11eb-82b2-111a87231ca4.png)

However to start the images:

`./docker/scripts/dev_start.sh` 

I must be inside **apollo or apollo-3.0-simulator** folder. And as the first does not contain the ros bridge and the second does not contain the cyber bridge. I ask myself w**hich one I must run this command, in order to have a correct connection on Dreamview- SVL simulation ?**

Trying the first option (start sh from apollo folder) Dreamview does not receive info from the simulator
Trying the second option (start sh from apollo-.0-simulator folder)  I get the error below:

![image](https://user-images.githubusercontent.com/43826438/120859411-8b50f800-c55a-11eb-8a83-6c190af76c45.png)

**"Linking CXX executable  /apolloros_pkgs/devel/rosauth/ros_mac_authentication**

**rosbridge_websocket.launch is neither a launch file in package (rosbridge_server) nor is (rosbridge_server) a launch file name.**

I guess that should exist **just one repo** (merged of apollo and apollo3-0-simulator) to be cloned and used.
Could someone assist me how to propely build apollo 3.0 along SVL? 
As a solution could I copy and past the **ros_pkgs** folder from this repo https://github.com/lgsvl/apollo-3.0 to this repo folder https://github.com/ApolloAuto/apollo ? Would this work?

**The tutorial is wrong and need to be updated!**

**If is not an error which Tag, release must I dowload from github to make this work?**

The files inside the ros_pkgs folder are not dowloaded automatically for some reason:
https://github.com/lgsvl/apollo-3.0/tree/simulator/ros_pkgs/src

The **folders rosbridge_suit and lgsvl_msgs come empty** . Then I needed to dowload them manually from repo. Afterwards I have built the workspace again with catkin_make. Now ROS says that I do not have the geometry_msgs pkg installed. However it is not possible install anything inside Apollo container.
Always when I issue some cmd line, such as "sudo apt-get install ros-indigO-..." I get errors...
**Is not possible to install ROS pkgs inside Apollo Docker?**

Thanks in advance

**Comment by Abd0ul** [comment]
Hello @marcusvinicius178 I advise you to review your approach/execution procedure with the first link **https://www.svlsimulator.com/docs/system-under-test/apollo3-0-instructions/** because it is the same one I used and it works for me. 

You should also know that the docker image used by LGSVL is not the same as that of apollo, so you cannot copy and paste the **rosbridge_suit and lgsvl_msgs packages** into the Apollo repo to try to make it work. 

Follow the procedure, download the LGSVL repo **git clone --recurse-submodules https://github.com/lgsvl/apollo.git** and execute the instructions of the LGSVL simulation platform.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
