### ISSUE TITLE
hdmap 

### ISSUE THREAD

**Issue by shunyuoptical** [ApolloAuto/apollo#13847]
Q 1： 在 Apollo/modules/map/proto/ 下的  map_overlap.proto文件 ，   这块的overlap是怎么定义的？  对于人行横道 停止线 红绿灯等交叠区域怎么填充字段？  或者说怎么表征交叠区域这个字段信息。 有木有示意图或者示例说明。  ？

**Comment by daohu527** [comment]
It is a bridge between the lane and others(lane, traffic light, stop sign). You can find the overlap ids in the lane, and then find its associated objects according to the overlap.

below is an example, you should also add overlap id in the associated objects `287a_1_-1` and `3038`
```
overlap {
  id {
    id: "overlap_3794"
  }
  object {
    id {
      id: "287a_1_-1"
    }
    lane_overlap_info {
      start_s: 20.5262
      end_s: 20.8895
      is_merge: false
    }
  }
  object {
    id {
      id: "3038"
    }
    crosswalk_overlap_info {
    }
  }
}
```

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
