### ISSUE TITLE
how to run perception module with raw pointcloud data ?

### ISSUE THREAD

**Issue by rlaehddls9** [ApolloAuto/apollo#13840]
System information
OS Platform and Distribution: Linux Ubuntu 18.04
Apollo installed from: Source
Apollo version: 6.0

I'm trying to run the perception module in Apollo with the data recorded directly by hesai(pandar64) with the cyber recorder. 

This data is raw point cloud data obtained by cyber_recorder using hesai lidar.

![image](https://user-images.githubusercontent.com/79086973/121139601-e3963b80-c873-11eb-8570-9c10b260221f.png)

(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)
/docker/scripts/dev_into.sh 
./apollo.sh build_opt_gpu
bootstrap.sh
cyber_launch start /apollo/modules/transform/launch/static_transform.launch
cyber_launch start modules/drivers/tools/image_decompress/launch/image_decompress.launch
cyber_launch start /apollo/modules/perception/production/launch/perception_lidar.launch 
cyber_recorder play -f 20210607171544.record.00000 

I tried to run it step by step according to the link above, but there was no change in dreamview.
how can I run perception module with above raw pointcloud data ?

**Comment by blacksheep0303** [comment]
I'm sorry to bother you.Did you solve the problem?
And could you please tell me how to run perception module with only pointcloud data?
Thanks a lot for your help!
