### ISSUE TITLE
Publish Camera sensor to Cyber channel

### ISSUE THREAD

**Issue by trieuthachvu** [ApolloAuto/apollo#13844]
Hi,
As I know, Camera sensor has two different messages camerainfo and image.
We have the Cyber channel
/apollo/sensor/camera/front_6mm/image/compressed
This can be considered as a topic
My question is that 
1. how can we publish two messages to one topic? Is there any other topic to publish camera sensor data.?

2. If I publish only Image data to /apollo/sensor/camera/front_6mm/image/compressed channel (topic)
What is the vaues of camerainfo in Apollo Cyber? Does it have default values or nothing? (As I understand, camerainfo will not 
change)

3. I want to convert Compressedimage data from ROS to Cyber RT
ROS message
```
Header header
string format 
uint8[] data     # Compressed image buffer
```
Cyber RT message
```
optional apollo.common.Header header = 1;
optional string frame_id = 2;
optional string format = 3;
optional bytes data = 4; // Compressed image buffer
optional double measurement_time = 5;
optional uint32 frame_type = 6;

```
My code:
![image](https://user-images.githubusercontent.com/53098029/121595040-2b68be80-ca3e-11eb-9e80-bf0c931df377.png)

I got below error for wrong data type conversion
![image](https://user-images.githubusercontent.com/53098029/121595218-59e69980-ca3e-11eb-9665-df51f0886212.png)

I probably have to use some functions from some library to do this conversion but I do not know how
If you know please support me this case.
Thanks in advanced.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
