### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by unyxs281** [ApolloAuto/apollo#13841]
System information
OS Platform and Distribution: Linux Ubuntu 18.04.5 LTS
Apollo installed from: Source
Apollo version: 6.0

when install apollo software, build Apollo inside Container, the following error occurred, How to solve this problem?
![image](https://user-images.githubusercontent.com/74952328/121168501-9b801480-c885-11eb-97c9-b723071253ee.png)

**Comment by unyxs281** [comment]
this problem has been solved. 
install libpython3.7-dev.

**Comment by changsh726** [comment]
It appears that you did not build in the container. The dependencies have already installed in the docker image.
