### ISSUE TITLE
Does apollo lidar object Detection trained using 3D Lidar Object Detection and Tracking dataset of ApolloScape?

### ISSUE THREAD

**Issue by peak9527** [ApolloAuto/apollo#13862]
### There's some  questions about 3D Lidar Object Detection and Tracking dataset of ApolloScape?

1.  does apollo lidar object Detection trained using 3D Lidar Object Detection and Tracking dataset of ApolloScape?
2. 3D Lidar Object Detection and Tracking dataset  Is collected with  HDL-64E S3,Can the training results be used for the vlp-16 lidar?

**Comment by daohu527** [comment]
> does apollo lidar object Detection trained using 3D Lidar Object Detection and Tracking dataset of ApolloScape?

Not all, at least some are trained on kiiti

> 3D Lidar Object Detection and Tracking dataset Is collected with HDL-64E S3,Can the training results be used for the vlp-16 lidar?

If the model has preprocessing, I think it is supported
