### ISSUE TITLE
Add new vehicle in branch r5.5.0

### ISSUE THREAD

**Issue by Xxfore** [ApolloAuto/apollo#13863]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**: N/A

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
We have already implement canbus related code by follow below docs: 
https://github.com/ApolloAuto/apollo/blob/master/docs/technical_tutorial/apollo_vehicle_adaption_tutorial_cn.md
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_vehicle_cn.md

Could you give us some advice about  below points?
 1. Is there any other part need to be implement? such as dreamview and so on ?
 2. Does it have any guide about adapt new vehicle?
Thanks a lot.

### Supporting materials (screenshots, command lines, code/script snippets):
N/A

**Comment by daohu527** [comment]
#### Q1
> Is there any other part need to be implement? such as dreamview and so on ?

Generally speaking, **no!** You only need to deal with the canbus module. 

By the way, if you want to replace the model of the vehicle in dreamview, you can change it in `modules/dreamview/frontend/assets/models/car.obj`.

#### Q2
> Does it have any guide about adapt new vehicle?

The above document looks very detailed, I think I have nothing to add

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
