### ISSUE TITLE
Write Radar data to Cyber channel

### ISSUE THREAD

**Issue by Thinsheep** [ApolloAuto/apollo#13865]
Hi,

I want to take Radar sensor data and write it to Radar Cyber Channel
This is the radar sensor data I have from Simulator
unint32_t objected
float distance
float radialVelocity
float azimuthAngle
float elevationAngle

For the Radar Cyber channel: /apollo/sensor/conti_radar
There is conti_radar.proto message. There are huge differences in data. Any hints on how can I convert the simulator radar
data to Apollo Radar data (C++)?
![image](https://user-images.githubusercontent.com/52489127/122594203-02ac7e80-d067-11eb-892e-6776f9ffcc28.png)

![image](https://user-images.githubusercontent.com/52489127/122594136-e7da0a00-d066-11eb-8e85-5d169bb7de63.png)
![image](https://user-images.githubusercontent.com/52489127/122594178-f7f1e980-d066-11eb-9e18-3cd12d60ddd8.png)

Thank you.

**Comment by daohu527** [comment]
There're two steps
## Coordinate conversion
According to your description, the acquired data is in the polar coordinate system, and you have to convert it to the Cartesian coordinate system.

If you lack the corresponding information, then you need the simulator to provide more information

## protobuf
Fill the information to the protobuf format message and publish. If you are passing through a socket, please refer to `modules/bridge`

**Comment by Thinsheep** [comment]
@daohu527 
Thanks for your information,
As you can see, 
ContiRadarObs Apollo's message requires a lot of information. Simulator may have a different way to define their radar sensor data and not all required information is available. Is it important that each parameter of protobuf message must be filled with some values? let take obstacle probability of existence (proexist) or obstacle radar cross-section (rcs) as an example. If we fill nothing in these parameters, do they have the default values? what may be the impact?

**Comment by daohu527** [comment]
I don't think all fields need to be filled. As for which fields are needed, you need to look at the logic of the code.  You can ref to `modules\drivers\radar\conti_radar`

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
