### ISSUE TITLE
How should I do to run the Apollo platform with real environment datasets. such as  https://apollo.auto/southbay_cn.html 

### ISSUE THREAD

**Issue by luogyu7** [ApolloAuto/apollo#13867]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**:  source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  5.0
- **Output of `apollo.sh config` if on `master` branch**:   null

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

I have run the apollo 5.0 version   with the demo_3.5_record. And I got a display  with the demo_3.5_record. 

### Supporting materials (screenshots, command lines, code/script snippets):
I run the command lines in turn.

1. run the command "bash docker/scripts/dev_start.sh" ;
2. run the command "bash docker/scripts/dev_into.sh"  to  into the contain ;
3. run the command "./apollo.sh build"  ,to  build the apollo source files;
4. run the command :"./scripts/bootstrap.sh";
5. Open the website with "http://localhost:8888" ,I can see the initial web page like this .

![screen](https://user-images.githubusercontent.com/67385330/122666854-5a232980-d1e2-11eb-93c5-fce2e448dc85.png)
6.  at least ，I   run  the command  :" cyber_recorder play -f docs/demo_guide/demo_3.5.record -l"   .And get the result like the following picture.
![res1](https://user-images.githubusercontent.com/67385330/122667032-45936100-d1e3-11eb-85cd-a760e84169b4.png)

so, now I can found the car runing  at the scenario. 

BUT， It is a record file ,right?    it is not the really that apollo platform is running.

So, what should I do to run the apollo platform really, and not just run a record file with the command :"cyber_recorder play -f docs/demo_guide/demo_3.5.record -l".

I have the apollo autopilot dataset.  the website is : https://apollo.auto/southbay_cn.html ,But I do't  know how to use them .
 
I want  the platform could  look like the website(https://apollo.auto/southbay_cn.html) video. 
Let me explain my current set up situation:
I set up the Apollo platform at the Ubuntu 18.04;
The Apollo version is 5.0,
And just perform the document:   quichstart /apollo_software_installation_guide.md .  
what I do is the following steps:

1. run the command "bash docker/scripts/dev_start.sh" ;
2. run the command "bash docker/scripts/dev_into.sh"  to  into the contain ;
3. run the command "./apollo.sh build"  ,to  build the apollo source files;
4. run the command :"./scripts/bootstrap.sh";
5. Open the website with "http://localhost:8888" ,I can see the initial situation with the record file .

So,what should I do to run the platform with autopilot datasets. https://apollo.auto/southbay_cn.html

Thanks for your help.

**Comment by ntutangyun** [comment]
You probably need a simulator for this.

check out https://www.svlsimulator.com/

**Comment by luogyu7** [comment]
I  really have  considered  the GLSVL simulator to build to environmont. But the simulator's scenario is Simulation , that is to say it is not the real scenario 's  state.

I need to simulate the real environment . so need to find some real scenario  data to build the real scenario , for example the webset datasets( dataset https://apollo.auto/southbay_cn.html).   But the problem is that  I donot know  how to run the simulate with the real environment datasets.

On the another hand . Could I use the  simulator to set up the real world environment  for apollo platform. And if it is not.  Where is the tutorial to teach me to set up the apollo platform with real environment dataset .How should I use them to simulate the environment?

Thanks for your reply.
Thanks for your help.

> You probably need a simulator for this.
> 
> check out https://www.svlsimulator.com/

**Comment by ntutangyun** [comment]
for Apollo to run, you'll need the sensor data. 

you can 
1. use the LGSVL to simulate the sensor data
2. reply the sensor data recorded during the real life. 

for option 1, LGSVL has built-in support for Apollo. so it's easy, just follow their documentation.
For option 2, you may need to make sure the data is compatible to Apollo. not just the format, but also the sensor configuration etc. and you need to reply the data in time order to the cyber RT channel. so this is doable, but a bit tricky.

**Comment by luogyu7** [comment]
Thanks for your reply.  Through  I haven't understood it completely ,I will research your reply carefully.

For cyber RT , I am researching its working mechanism to know how to load the real life data. I am in a induction phase . But it is clearly that if I want to realize loading the real life data to Apollo and running Apollo platform , I need do some research in two directions. 

first , that is the LGSVL's sensor configuration.  this can be built by LGSVL built-in  support for Apollo 。
second，that  is the way of  cyber RT 's  data reply . cyber RT  can realize  real life data reply .  what I know about the Apollo real life data is that it can adapt the Apollo to load. BUT ,I don't know if it can be adapt the sensor configuration( I still don't know what the sensor configuration refers to. but,I will research the LGSVL and Apollo's Cyber RT  carefully.)  I will research the two directions carefully.

Thanks for your help.    


> for Apollo to run, you'll need the sensor data.
> 
> you can
> 
> 1. use the LGSVL to simulate the sensor data
> 2. reply the sensor data recorded during the real life.
> 
> for option 1, LGSVL has built-in support for Apollo. so it's easy, just follow their documentation.
> For option 2, you may need to make sure the data is compatible to Apollo. not just the format, but also the sensor configuration etc. and you need to reply the data in time order to the cyber RT channel. so this is doable, but a bit tricky.

**Comment by luogyu7** [comment]
I have a question about  the building progress  with apollo and lgsvl. The question is about the perception module.

If I build the simulate progress  with apollo and lgsvl. Did the  prediction object progress(I want to test the progress of prediction algorithms) is the same completely between using simulator to  simulate the real life environment and  using the real device  (D-Kit)   vehicle.  Because  I need to test the  perception module in simulator state first ,and test the  perception module  in real device state(use the D-kit tools ) at last.  

**What the question is  if I run the predict procedure , whose prediction algorithm I will use?  It is apollo's  or it is lgsvl's ?(I hope  it is apollo's.)**

**So , are the test results same(recognition algorithm)  when I test the prediction obstacle object(beside prediction time , prediction distance , etc.) using simulator(apollo+lgsvl) and using  real device ?**

I want to test the perception mechanism .  I want to know if  the predict the obstructions results of perception module are the same between in simulator state and  real device (D-Kit ) .  This will make it meaningful in using simulator platform. I need test the prediction object result in  real device at last. 

Are they the same completely?  If the results of the prediction in two states(in simulator and in real life device D-kit)  are not the same (It is what I am very worried about. I need the the results of the two states no difference. ), I have to search other strategies to realize simulate progress . 

Thanks for your reply.
Thanks for your help.

**Comment by luogyu7** [comment]
The 3D box of the target vehicle shown in Apollo belongs to the detection result of Apollo or the detection result of LGSVL?Could any experts reply me? Many thanks.

**Comment by luogyu7** [comment]
![approach 3d bounding box](https://user-images.githubusercontent.com/67385330/124689691-87264a80-df0b-11eb-9314-9c39ccd6667d.png)
> for Apollo to run, you'll need the sensor data.
> 
> you can
> 
> 1. use the LGSVL to simulate the sensor data
> 2. reply the sensor data recorded during the real life.
> 
> for option 1, LGSVL has built-in support for Apollo. so it's easy, just follow their documentation.
> For option 2, you may need to make sure the data is compatible to Apollo. not just the format, but also the sensor configuration etc. and you need to reply the data in time order to the cyber RT channel. so this is doable, but a bit tricky.

many thanks for your guiding suggestion. that help me complete the first step. the realize result is following the picture:
![approach 3d bounding box](https://user-images.githubusercontent.com/67385330/124689691-87264a80-df0b-11eb-9314-9c39ccd6667d.png)

 BUT For  loading real life data approach I 'm still not clearly .  Did I need to learn the perception module completely. Did the issue's solve way can be got by reading the perception code. Could you give me some suggestions for solving this issue more quickly ? 

Now I have run the Apollo with the simulator like the picture:
![vx](https://user-images.githubusercontent.com/67385330/124688173-e9ca1700-df08-11eb-8e88-162cc3d6e979.png)

AND,The need is urgent .
I need to learn how to carry out the second step. Could you give me some guiding suggestions? Now ,I'm learn the perception module's  code for learning the module's theoretical basis of coding. BUT, it is difficult to learn the theoretical logic.
Could you give me some papers  about the perception's  realization  for guiding  study. 

Except that,could you give me some directly suggestions  about the way to load real life data use for apollo‘s running environment(Are there any papers help me?)and which real life data's loading the logic document  or code module  should I follow?Hope for your reply.

Thank you very much.

**Comment by luogyu7** [comment]
could any apollo experts reply me? @ntutangyun 
Many thanks.

**Comment by RedBlack888** [comment]
@luogyu7 Did you find the right way to generate the original sensor data into record format file ?

**Comment by Addi2020** [comment]
@luogyu7  @RedBlack888 @ntutangyun 
I am also struggling with the same issue. I am using Apollo-6.0 with lgsvl simulator(version 2021.2.2). I can connect dremview with LGSVL simulator. i am having two issues.
1. It works fine to to move the car with keyboard control but it can not work with autopilot while using routing. I use the following setup.
![Screenshot from 2022-01-28 21-38-02](https://user-images.githubusercontent.com/61130487/151625135-c4acaf76-2a91-4f5d-b2bc-ca1c3f5945a1.png)


2. The same issue that how to upload our real time car data to LGSVL simulator for testing. for example, how to upload HD map (base_map.bin) file or import .pcd file, this HD map is created by improting .pcd file to UNITY and create base_map.bin file. So how to upload it to LGSVL and run the recording file that consist of all the sensor data and then test with LGSVL simulator. I can run the real time data in dremview and also connect dremview with LGSVL simulator with but do not know how to load my map.

If anyone can help. Thanks.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
