### ISSUE TITLE
How to update my docker image with ros2?

### ISSUE THREAD

**Issue by utopia42** [ApolloAuto/apollo#13869]
Hi All, Here is my issue description:
     i want to run ROS2 program in my apollo docker container,  i pulled  the newest apollo docker and built it successfully, and i directly install ros2 in this container successfully too, but when i want so save this system Env(both has ros and cyber) by **docker commit -m**, it created an extremely large docker image (more than 200G), Then i try to follow the same structure that apollo used for building container by pulling different images from docker hub and combine them in local, so i choosed a ROS2 image(foxy) which i had checked, it works fine in its standalone image, but when i try to merge this image to apollo images by **docker run -v** like the way apollo used in docker/scripts/dev_start.sh to mount different volume from different images , i found out The ROS2 project has so many dependencies and libraries that located more than one folder /opt/ros2/**,  so it seems i can't merge ros image by only mount one folder which like dev_start.h, **So How can i create a stable container or image that as small as possible?**  
ps: i am new to docker and apollo , if this is a stupid question  i apologies for my ignorance,  but i have struggling for this problem almost a  whole day , if anyone can help i will be very appreciated.  Thx .

Here is my system info:
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (6.0)**:

**Comment by daohu527** [comment]
## question
`docker run -v` does not achieve the effect you want. The -v (or --volume) argument to docker run is for creating storage space inside a container that is separate from the rest of the container filesystem. 

## suggestion
 You should use docker build to generate a docker image, so that you can keep the package as small as possible. Because your operation will bring some problems, such as library conflicts. I can't guarantee you will succeed.

Why don't you communicate through sockets?

**Comment by utopia42** [comment]
> ## question
> `docker run -v` does not achieve the effect you want. The -v (or --volume) argument to docker run is for creating storage space inside a container that is separate from the rest of the container filesystem.
> 
> ## suggestion
> You should use docker build to generate a docker image, so that you can keep the package as small as possible. Because your operation will bring some problems, such as library conflicts. I can't guarantee you will succeed.
> 
> Why don't you communicate through sockets?

Hi ! Thank for your reply and suggestion, actually i mean to create a stable system Env which include Cyber and ros, if Socket works it will be an option, but Even i  use socket to communication between them i still need to install ros on my system, because the ros is also for developing  (part of my auto system), **Another question ** if you don't mind, i don't see any Dockfile in apollo about how to build a container  in  docker/scripts/dev_start.sh. and i also pulled a minim-ros2-image from docker hub, Any suggestion about how to combine my ros2 image with apollo images to generate a container? Thx  :)

**Comment by daohu527** [comment]
Apollo's docker build file is `docker\build\dev.x86_64.dockerfile`. 

I don’t think merge the dockers you mentioned is a good idea, if you want to try, I have no good suggestions!

**Comment by utopia42** [comment]
> Apollo's docker build file is `docker\build\dev.x86_64.dockerfile`.
> 
> I don’t think merge the dockers you mentioned is a good idea, if you want to try, I have no good suggestions!

Thx a lot ! i will try to use dockerfile to generate container. Have a good day !

**Comment by utopia42** [comment]
> Apollo's docker build file is `docker\build\dev.x86_64.dockerfile`.
> 
> I don’t think merge the dockers you mentioned is a good idea, if you want to try, I have no good suggestions!

I tried to build a minim cyber_ros docker-image from apollo base image by Dockefile, it worked ! Thanks very much !
Here is my Dockerfile: 
------------------------------------------------------------------Dockerfile------------------------------------------------------------------
```
FROM apolloauto/apollo:dev-x86_64-18.04-20210517_1712
# install process will insta;ll tzdata which require interactive 
# fix this by THIS:
ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \ 
# fixed cmd end here
  && echo $TZ > /etc/timezone \
  && sudo apt update \
	&& sudo apt install locales \ 
	&& sudo locale-gen en_US.UTF-8 \
	&& update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
	&& LANG=en_US.UTF-8 \
	&& sudo apt update \
	&& sudo apt install curl gnupg2 lsb-release -y \
	&& sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg \ 
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null \
	&& sudo apt update && sudo apt install -y \
      build-essential \
      cmake \
      git \
      libbullet-dev \
      python3-colcon-common-extensions \
      python3-flake8 \
      python3-pip \
      python3-pytest-cov \
      python3-rosdep \
      python3-setuptools \
      python3-vcstool \
      wget \
  && sudo python3 -m pip install -U \
      argcomplete \
      flake8-blind-except \
      flake8-builtins \
      flake8-class-newline \
      flake8-comprehensions \
      flake8-deprecated \
      flake8-docstrings \
      flake8-import-order \
      flake8-quotes \
      pytest-repeat \
      pytest-rerunfailures \
      pytest \
  && sudo apt install --no-install-recommends -y \
      libasio-dev \
      libtinyxml2-dev \
  && sudo apt install --no-install-recommends -y \
      libcunit1-dev \
  && mkdir -p ~/ros2_foxy/src && cd ~/ros2_foxy \
  && wget https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos \  
  && vcs import src < ros2.repos \
  # install ros-depencies
  && sudo rosdep init \
  && rosdep update \
  && cd ~/ros2_foxy \
  && rosdep install --from-paths src --ignore-src --rosdistro foxy -y --skip-keys "console_bridge fastcdr fastrtps rti-connext-dds-5.3.1 urdfdom_headers" \
  # build ros Env
  && cd ~/ros2_foxy/ && colcon build --symlink-install
```
-------------------------------------------------------------------------------------end---------------------------------------------------------------------
i test ros2 in this container, everying is fine, but this image is still 22G , do you have any suggestion to make it smaller?

**Comment by daohu527** [comment]
**Topics about docker is not in the support of this project**, There are a lot of good practices about docker build file on the Internet.

I just give a little suggestion, you should delete the source code when builded success. Because the source code takes up space, but it is not used
`wget https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos \`

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
