### ISSUE TITLE
Vision only Apollo system (Apollo Lite) 

### ISSUE THREAD

**Issue by SpeedAutonomy** [ApolloAuto/apollo#13866]
Where is apollo lite? Has it been released? Will it get released on GitHub? Currently, you can't run apollo on cameras alone correct? Just curious, Thank you. Can you run 6.0 on cameras and ultrasonic only?

**Comment by SpeedAutonomy** [comment]
Looks like someone already asked this. Thanks

**Comment by armuren** [comment]
What was the answer to that question?
