### ISSUE TITLE
What does the transform module?

### ISSUE THREAD

**Issue by thymbahutymba** [ApolloAuto/apollo#13874]
As the title say, I would like to know of what is in charge the transform module, how it is interconnected with the others and anything that could be useful for the understaing of such module (a brief explanation). Thanks in advance.

**Comment by daohu527** [comment]
In short, transform module is use for coordinate conversion. Through this module, we can convert the points in the A coordinate to the B coordinate, which is very useful in robots systems.

The corresponding module in ROS is TF (not the abbreviation of tensorflow), you can refer to http://wiki.ros.org/tf

**Comment by thymbahutymba** [comment]
Thanks, who needs this module? (just perception?)

**Comment by daohu527** [comment]
It is mainly needed for localization and perception modules

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
