### ISSUE TITLE
Map Converter Tools

### ISSUE THREAD

**Issue by enishettyr1** [ApolloAuto/apollo#13875]
Hallo Team,

I am looking for some tools to convert Open Drive Maps to Apollo Open Drive Map format?

1. Are there any tools available to convert the map?
2. Which coordination reference system is used inside Apollo (eg:- WGS84)?

Thanks in Advance.

Regards,
Rahul

**Comment by daohu527** [comment]
## Q1
> Are there any tools available to convert the map?

I have no good suggestions

## Q2
> Which coordination reference system is used inside Apollo (eg:- WGS84)?

Yes, apollo use WGS84 coordinate system

**Comment by enishettyr1** [comment]
Hallo daohu527,

I have been using Dreamview to Visualize the Maps. The Coordinate Reference System does not match with WGS84. 

Could you please tell me, which coordinate system  it refers to ?

Regards,
Rahul

**Comment by daohu527** [comment]
I was wrong before, WSG84 is for GPS, while apollo uses UTM coordinate.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
