### ISSUE TITLE
Error when using cyber_visualizer

### ISSUE THREAD

**Issue by lucywang-NI** [ApolloAuto/apollo#13873]
Got below error information when trying to launch cyber_visualizer following the instructions.

root@in-dev-docker:/apollo# source cyber/setup.bash
root@in-dev-docker:/apollo# cyber_visualizer
No protocol specified
qt.qpa.xcb: could not connect to display :10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)

### System information

- **OS Platform and Distribution **: Linux Ubuntu 20.04.2
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master branch
- **Output of `apollo.sh config` if on `master` branch**:
-[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-06-11-ec30ae63c8
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

**Comment by kontonpuku** [comment]
It's probably that your docker is running in root mode.

**Comment by fjc378209410** [comment]
Hello, have you solved this problem? I encountered the same problem, how did you solve it

**Comment by kontonpuku** [comment]
> Hello, have you solved this problem? I encountered the same problem, how did you solve it

Running apollo_dev_ docker in normal user mode instead of root user might solve this problem. Bash `docker/scripts/dev_into.sh` can enter into docker in normal user space. Or add an parameter "--user <your_user_name>" to "docker exec" command.

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by yqw11** [comment]
> I have met this problem, but I can't resolve it. Could you please describle the solution more clearly?
