### ISSUE TITLE
Questions about installation guide of Velodyne HDL64E-S3

### ISSUE THREAD

**Issue by ningfeiwang** [ApolloAuto/apollo#13879]
Hello, I have a question about installation guide of Velodyne HDL 64 LiDAR. In the instruction documents Connecting the Power Source section (https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Lidar/HDL64E_S3_Installation_Guide.md), it seems it has a hub and some green connectors. I wonder whether it is necessary to install the LiDAR to the vehicle. Also, I wonder what the name of them and where I can buy them. Could you please provide more instructions on that? Thanks a lot!

**Comment by daohu527** [comment]
@ningfeiwang You can find them in the electronics market, I think they are very commonly used
