### ISSUE TITLE
IPC Mechanisms

### ISSUE THREAD

**Issue by enishettyr1** [ApolloAuto/apollo#13876]
1.	Is there an documentation available for public sw interface in Apollo to 
    a.	   Feed in raw sensor data (e.g. camera image, radar data)
    b.	   Receive vehicle control information (steering, acceleration, braking etc.)
2.	What IPC is used for sending data as input and for receiving the output from Apollo (e.g. ROS, TCP/IP sockets etc.)?

**Comment by changsh726** [comment]
Apollo communicates based on the Cyber RT framework. You can pass messages through writer/reader in Cyber. There are some examples in [CyberRT_API_for_Developers](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_API_for_Developers.md).

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
