### ISSUE TITLE
why is the vehicle dynamic model  different in different gear（drive and reverse）?

### ISSUE THREAD

**Issue by Mol2017** [ApolloAuto/apollo#13887]
gear in drive mode: 
    A matrix (Gear Drive)
    [0.0, 1.0, 0.0, 0.0;
     0.0, (-(c_f + c_r) / m) / v, (c_f + c_r) / m,
     (l_r * c_r - l_f * c_f) / m / v;
     0.0, 0.0, 0.0, 1.0;
     0.0, ((lr * cr - lf * cf) / i_z) / v, (l_f * c_f - l_r * c_r) / i_z,
     (-1.0 * (l_f^2 * c_f + l_r^2 * c_r) / i_z) / v;]

gear in drive mode: 
    A matrix (Gear Reverse)
    [0.0, 0.0, 1.0 * v 0.0;
     0.0, (-(c_f + c_r) / m) / v, (c_f + c_r) / m,
     (l_r * c_r - l_f * c_f) / m / v;
     0.0, 0.0, 0.0, 1.0;
     0.0, ((lr * cr - lf * cf) / i_z) / v, (l_f * c_f - l_r * c_r) / i_z,
     (-1.0 * (l_f^2 * c_f + l_r^2 * c_r) / i_z) / v;]

could you help me with the derivation process?
tks a lot!

**Comment by daohu527** [comment]
Can you point out which part of your code in apollo module, MPC or PID

**Comment by DrShIkIgAmy** [comment]
I believe, author has mentioned lat_controller. Compute control command method exactly.
P.S. Mol2017, I think it was useful for you to check out the book Rajesh Rajamani Vehicle Dynamics

**Comment by cmlaughing** [comment]
> Can you point out which part of your code in apollo module, MPC or PID

I guess the code is in lat_controller.cpp
![image](https://user-images.githubusercontent.com/30388183/148414651-bd5dda26-119e-4690-b882-3383e7bc61cc.png)

I also have some questions about reverse dynamic model ?
(1) why Cf and Cr are negative when reverse driving;
![image](https://user-images.githubusercontent.com/30388183/148415391-a5bc122a-9140-47c8-96e7-ae3a015255d8.png)

(2) why heading error is heading_direction + pi - ref_direction ?
![image](https://user-images.githubusercontent.com/30388183/148416053-0984a777-dd77-4415-b029-d2f72d194265.png)
in code above, theta is driving direction which equals to heading + pi  when reverse driving

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
