### ISSUE TITLE
How to add new *.proto for LGSVL

### ISSUE THREAD

**Issue by joeking11829** [ApolloAuto/apollo#13885]
OS version: Ubuntu 18.04
Apollo version: 6.0 (master)
LGSVL version: 2021.1.1

I want to create a *.proto that defind my own data structure in Apollo.
And I want to use the data structure to communicate with LGSVL's  Cyber Bridge.

How can I add my own data structure to LGSVL.
BTW, which version of protobuf should i use to compile the *.proto to csharp file.

**Comment by daohu527** [comment]
The work on Apollo is very simple, the main work is in lgsvl. You can find some guides in the issue list of lgsvl, I think you can try it first

## apollo side
add a proto file, you can take any proto as an example, it's proto2.

## lgsvl side
1. You should first transform c++ proto to c# (I found that proto3 now supports c#, but unfortunately proto2 does not support), you can use this lib https://github.com/protobuf-net/protobuf-net for proto2, it works well.
2. If it is lgsvl bridge, you need to do some adaptations in lgsvl bridge

Hope this helps you!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
