### ISSUE TITLE
I want to add a single line lidar, but I don't know how to do it

### ISSUE THREAD

**Issue by wxq1117** [ApolloAuto/apollo#13890]
I want to add a single line lidar, but I don't know how to do it,

Do I need to create a new component or use the original one of Apollo.
How can I get Apollo to receive lidar data, and where do I need to change Apollo

Are there any specific steps？
thank you！

**Comment by daohu527** [comment]
Generally broad questions are difficult to answer, you can look at the documentation first.

## suggestions
If you need to add a single-line lidar, here are some suggestions.
1. Add single-line lidar driver in `modules\drivers\lidar`
2. Add function in perception module

In fact, the workflow of the single-line radar may need to be adapted to some other modules, depending on your usage scenario

**Comment by panfengsu** [comment]
This document https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_lidar_driver_cn.md explains in detail how to add a new lidar.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
