### ISSUE TITLE
USB webcam Perception Module issue. 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#13896]
I got a usb camera to work with apollo. The webcam light flashes on and off. However, there is no video feed in dreamview and I get this error: 

![Screenshot from 2021-06-28 16-19-09](https://user-images.githubusercontent.com/58639429/123715189-9c74e800-d82c-11eb-9a32-7706928ef3e0.png)

I changed everything to /dev/video2 because that's what my camera channel is on not video0 (I'm on a laptop) and it kind've works. Any ideas on how to fix this issue? I looked at usb_cam.cc to find a solution but there is no camera /dev/ to configure. Also, I was curious if you could get apollo running on cameras only (such as apollo lite) I see how much it relies on lidar so I'm going to assume no. Also, can I just test the perception module with this camera until I can get it connected into a vehicle?  Help on this issue would be appreciated. Thank you

**Comment by jp12AI** [comment]
![Screenshot from 2021-06-29 13-04-31](https://user-images.githubusercontent.com/58639429/123860355-a8b77e80-d8da-11eb-93de-f58548be5181.png)
UPDATE: I deleted the duplicated nodes and changed/configured them to run with /dev/video2. I'm only using one webcam. I will use others later. However, I'd like to test the perception module before I get a vehicle to test apollo on. How can I test perception live through my webcam? What mode do I need to be on? Also can someone please explain to me what nav mode is? I read the read me and instructions on 2.5 but It's quite confusing. Can I enter a destination on the map and have it navigate there. Do I need to drive that route for it to go there? Thank you.

**Comment by daohu527** [comment]
It may be a problem related to the linux device driver, you can try to binding the device number.


You can ref to [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md#%E6%91%84%E5%83%8F%E5%A4%B4%E8%A7%84%E5%88%99%E6%96%87%E4%BB%B6%E7%9A%84%E9%85%8D%E7%BD%AE)
```
SUBSYSTEM=="video4linux", SUBSYSTEMS=="usb", KERNELS=="2-1:1.0", ATTR{index}=="0", MODE="0666", SYMLINK+="camera/front_6mm", OWNER="apollo", GROUP="apollo"
SUBSYSTEM=="video4linux", SUBSYSTEMS=="usb", KERNELS=="2-2:1.0", ATTR{index}=="0", MODE="0666", SYMLINK+="camera/front_12mm", OWNER="apollo", GROUP="apollo"
```

**Comment by jp12AI** [comment]
> It may be a problem related to the linux device driver, you can try to binding the device number.
> 
> You can ref to [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md#%E6%91%84%E5%83%8F%E5%A4%B4%E8%A7%84%E5%88%99%E6%96%87%E4%BB%B6%E7%9A%84%E9%85%8D%E7%BD%AE)
> 
> ```
> SUBSYSTEM=="video4linux", SUBSYSTEMS=="usb", KERNELS=="2-1:1.0", ATTR{index}=="0", MODE="0666", SYMLINK+="camera/front_6mm", OWNER="apollo", GROUP="apollo"
> SUBSYSTEM=="video4linux", SUBSYSTEMS=="usb", KERNELS=="2-2:1.0", ATTR{index}=="0", MODE="0666", SYMLINK+="camera/front_12mm", OWNER="apollo", GROUP="apollo"
> ```

Thank you for the quick response. I'll try to configure the settings some more. Is it possible to run perception without any connection to the car as a live test? Also, after I get everything working will I be able to run apollo on vision only. HD Maps are definitely a requirement it seems unless another mode such as navigation is used. Thank you

**Comment by daohu527** [comment]
## Q1
> Is there an English version of that document?

Seems not, you can try to translate the docs

## Q2
> Is it possible to run perception without any connection to the car as a live test with webcams?

Yes, but you may encounter some problems. And it is recommended to use the version below 5.5

**Comment by jp12AI** [comment]
> ## Q1
> > Is there an English version of that document?
> 
> Seems not, you can try to translate the docs
> 
> ## Q2
> > Is it possible to run perception without any connection to the car as a live test with webcams?
> 
> Yes, but you may encounter some problems. And it is recommended to use the version below 5.5
> 

Hi, thank you for the quick response again. How can I use an older version of apollo? Let me configure the settings correctly for my usb camera and then get the perception module. Thank you
