### ISSUE TITLE
How does apollo dreamview get data from all the other modules?

### ISSUE THREAD

**Issue by dheerajakula** [ApolloAuto/apollo#13895]
Hi I need to read output from the apollo perception module (cyber channel /apollo/perception/obstacles) in real time. I know this can be done by using cyber rt listeners, but which needs to be build with bazel. However dreamview is getting data from a already built node. So how do I get this data just by using network and not building any cpp source code?

**Comment by lj0919** [comment]
> You can try to use chrome debug tools to display the dreamview data about obstacles. If you don't find it then we will continue the question.
