### ISSUE TITLE
Must have hardware

### ISSUE THREAD

**Issue by Jobhdez** [ApolloAuto/apollo#13891]
Hello —

what is the must have hardware for a self driving project that doesn’t use the Apollo self driving software?

IPC is a must have as well as the camera, the processor, gpu etc. A monitor as well. 

what else?

I will appreciate it if you reply.

**Comment by daohu527** [comment]
Pls ref to to

 [What hardware is needed for Apollo?](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/docs/FAQs/Hardware_FAQs.md#what-hardware-is-needed-for-apollo)
