### ISSUE TITLE
Failed to create reference line from routin error

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13894]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I am going to create a new map and apply it to Apollo for autonomous driving.
When trying to put a map through DreamView and control the vehicle. A problem occurs in the Planning modules. 
I'll attach a picture of the error.

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2021-06-28 17-12-35](https://user-images.githubusercontent.com/18480213/123603767-2b85fe00-d835-11eb-9c3a-bc03f7726827.png)
![Screenshot from 2021-06-28 17-13-49](https://user-images.githubusercontent.com/18480213/123603772-2c1e9480-d835-11eb-86a3-1917cc525836.png)
![Screenshot from 2021-06-28 17-21-54](https://user-images.githubusercontent.com/18480213/123604056-6ee06c80-d835-11eb-98ca-4c157d353259.png)

**Comment by daohu527** [comment]
Except for the first failure, the next two succeeded. But you paste the successful log?

You can use `modules/tools/routing/debug_route.py` to debug the routing on your map. It’s usually a map problem!

Hope this helps you!
