### ISSUE TITLE
parser_cli test case

### ISSUE THREAD

**Issue by dingjiangang** [ApolloAuto/apollo#13905]
when i run ./parser_cli "novatel.bin" "bin" ， but something wrong happens， just like this
E0630 14:38:18.776397  4696 file.cc:81] [parser_cli]Failed to parse file /apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt as text proto.
E0630 14:38:18.776433  4696 file.cc:103] [parser_cli]Failed to parse file /apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt as binary proto.
F0630 14:38:18.784852  4696 data_parser.cc:109] [parser_cli]Failed to create data parser.
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by dingjiangang** [comment]
i have sole this problem， thanks

**Comment by daohu527** [comment]
If you can, please point out the problem to help others. Thx!
