### ISSUE TITLE
Is there any example of sensor fusion ? 

### ISSUE THREAD

**Issue by bittuh** [ApolloAuto/apollo#13909]
Hi, I'm trying to do some fusion of camera and lidar stream.

The first thing comes to my mind is sensor fusion in perception module, but according to [README](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md), it's not available yet.

Is there any other self-contained example that shows how to do the tf part between different sensors for fusion?
(C++ is OK, python prefered)

Thanks!

**Comment by jeroldchen** [comment]
@bittuh Sorry, we don't have the tutorials for sensor data fusion.
