### ISSUE TITLE
What vehicle frame system are you using?

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#13914]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: mater
- **Output of `apollo.sh config` if on `master` branch**:

https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination.pdf

https://github.com/ApolloAuto/apollo/blob/master/modules/planning/planner/navi/navi_planner.h

If you look at the documentation, the two are defined as a mixture. Which one is correct?
RFU or FLU, which vehicle frame system is correct?

**Comment by daohu527** [comment]
I think this one is right we used

https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination.pdf
