### ISSUE TITLE
cyber_channel echo 

### ISSUE THREAD

**Issue by BufuZhou** [ApolloAuto/apollo#13915]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

 Ubuntu 18.04)

Apollo 6.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

cyber_channel echo /apollo/sensor/gnss/best_pose
没有任何输出

**Comment by daohu527** [comment]
There may be many reasons for this, You can go to'data/log' and try to analyze

**Comment by Tcloser** [comment]
给的信息能不能再全面一点...  目的 操作步骤 结果
