### ISSUE TITLE
Segmentation fault on writing GPS data to Cyber channel. 

### ISSUE THREAD

**Issue by trieuthachvu** [ApolloAuto/apollo#13910]
Hi,
I want to write ROS GPS data  to Cyber Channel.
Output_Topic_Name: /apollo/sensor/gnss/odometry
msg_type: apollo::localization::Gps 
Apollo 3.5

`void cyber_ros_bridge::ROSGpsToApolloGps(const nav_msgs::Odometry::ConstPtr &gps_msg, std::shared_ptr<apollo::localization::Gps> &gps_apollo)
{
      // initialize the header
    auto header = gps_apollo->mutable_header();

    // set headers, width and height
    header->set_timestamp_sec(gps_msg->header.stamp.toSec());
    header->set_frame_id(gps_msg->header.frame_id);
    header->set_sequence_num(gps_msg->header.seq);

    gps_apollo->mutable_localization()->mutable_position()->set_x(gps_msg->pose.pose.position.x);
    gps_apollo->mutable_localization()->mutable_position()->set_y(gps_msg->pose.pose.position.y);
    gps_apollo->mutable_localization()->mutable_position()->set_z(gps_msg->pose.pose.position.z);

    gps_apollo->mutable_localization()->mutable_orientation()->set_qx(gps_msg->pose.pose.orientation.x);
    gps_apollo->mutable_localization()->mutable_orientation()->set_qy(gps_msg->pose.pose.orientation.y);
    gps_apollo->mutable_localization()->mutable_orientation()->set_qz(gps_msg->pose.pose.orientation.z);
    gps_apollo->mutable_localization()->mutable_orientation()->set_qw(gps_msg->pose.pose.orientation.w);

    gps_apollo->mutable_localization()->mutable_linear_velocity()->set_x(gps_msg->twist.twist.linear.x);
    gps_apollo->mutable_localization()->mutable_linear_velocity()->set_y(gps_msg->twist.twist.linear.y);
    gps_apollo->mutable_localization()->mutable_linear_velocity()->set_z(gps_msg->twist.twist.linear.z);

    gps_apollo->mutable_localization()->mutable_angular_velocity()->set_x(gps_msg->twist.twist.angular.x);
    gps_apollo->mutable_localization()->mutable_angular_velocity()->set_y(gps_msg->twist.twist.angular.y);
    gps_apollo->mutable_localization()->mutable_angular_velocity()->set_z(gps_msg->twist.twist.angular.z);

    // AINFO << pc_apollo->DebugString(); */
}
`
I got error "Segmentation fault" (just simply this error with no more details)
Usually, Segmentation fault means that I try to use memory which has not been allocated. 
Anyone who experience this problem please help.

**Comment by daohu527** [comment]
Maybe `gps_apollo` or `gps_msg` is nullptr.

**Comment by Thinsheep** [comment]
You are right, it was gps_apollo. 
thank you.

**Comment by trieuthachvu** [comment]
You are right. It was gps_apollo.
Thank you.
