### ISSUE TITLE
How do I use an older version of apollo (5.5)? 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#13918]
Hello, looking to use apollo 5.5. However, can't seem to figure out a way to use the older version. How can I use apollo 5.5 or any other version besides 6.0? Do I need to rebuilld with a different docker image? Thank you.

**Comment by daohu527** [comment]
You do not need to do any additional processing, because "dev_start.sh" will automatically handle these differences. 

You only need to checkout 5.5 code and start "dev_start.sh".

**Comment by jp12AI** [comment]
> You do not need to do any additional processing, because "dev_start.sh" will automatically handle these differences.
> 
> You only need to checkout 5.5 code and start "dev_start.sh".

Hi, thank you for the response. Can you tell me what the checkout 5.5 code is? What CMD should I type to switch versions? Thank you.

**Comment by daohu527** [comment]
You should learn some operations of git so that you can better manage the code.  

```
 git checkout r5.5.0
```

**Comment by jp12AI** [comment]
> You should learn some operations of `git`so that you can better manage the code.
> 
> ```
>  git checkout r5.5.0
> ```

Ok, I'm relatively familiar with git. Thank you for the help. Closing the issue.
