### ISSUE TITLE
Visualize HD map in Dreamview

### ISSUE THREAD

**Issue by trieuthachvu** [ApolloAuto/apollo#13916]
Hi,

As I understand, with IMU sensor and GPS sensor data from LGSVL. When we turn on the localization module on the dreamview
the HD map will be visualized with the ego vehicle on it.
I want to do the same for another simulator. Below are my IMU and GPS sensor data I have
![image](https://user-images.githubusercontent.com/53098029/124302635-c0546880-db61-11eb-888d-c9146fef1e82.png)

IMU
![image](https://user-images.githubusercontent.com/53098029/124302880-090c2180-db62-11eb-84a3-8595d4f99437.png)

GPS
![image](https://user-images.githubusercontent.com/53098029/124302978-2b05a400-db62-11eb-8438-a89753153e4b.png)

My questions:  
1. With above data, is that enough to get the localization module working and HD map visualization on Dreamview?
2. Which setup mode can I use? is it possible to use Mkz Standard Debug? is Mkz lgsvl only built for LGSVL simulator?
My setup:
I feed IMU sensor data and GPS sensor data to Cyber channels like above. 
Loading the dreamview then selecting my testing HD map. I chose Mkz Standard Debug for setup mode.
However, every time I drag the localization module on it automatically switches back to off?
Do I have to build my own setup mode? I saw the files of setup mode somewhere before but I do not remember where is it
in the apollo directory. 
Anyone know please help.

**Comment by daohu527** [comment]
## suggestion
You don't need to modify `setup mode`, use `Mkz lgsvl` will work. You only need to modify the gps message

You need three below topic
```
/apollo/sensor/gnss/corrected_imu
/apollo/sensor/gnss/odometry
/apollo/sensor/gnss/ins_stat
```

**Comment by trieuthachvu** [comment]
Thanks for your information.
Could you please give me some hint regarding topic ins_stat
`message InsStat {
  optional apollo.common.Header header = 1;
  optional uint32 ins_status = 2;
  optional uint32 pos_type = 3;
}`
I fail to understand  ins_status and pos_type. From Cyber_monitor, I capture data from LGSVL, ins_status = 3 and pos_type = 56.
These data do not change when the ego vehicle moves. Where these data come from?
![image](https://user-images.githubusercontent.com/53098029/124366773-70090380-dc52-11eb-9d56-dccba83a8499.png)

**Comment by daohu527** [comment]
which apollo version do you use, I found above 5.0 the message is below type
https://github.com/ApolloAuto/apollo/blob/259756578b4c01ee07b98f72ab9f874818bee200/modules/drivers/gnss/proto/gnss_status.proto#L19-L34

so the `type` is a enum, for example `type = 2` is `GOOD`

**Comment by trieuthachvu** [comment]
I use apollo 6.0, I thought messgage InsStat have nothing relating to message InsStatus
Anyways, I set it as 2 "GOOD" to perform the test.
This is my localization pole
![image](https://user-images.githubusercontent.com/53098029/124377213-2993c300-dcab-11eb-9651-39e4469f7ec1.png)
The dreamview is now visible but the HD map is not there
![image](https://user-images.githubusercontent.com/53098029/124377272-77103000-dcab-11eb-9859-94a716239f6c.png)

I am not sure if the problem is because of HD map. I try to figure out where is the problem come from
If I turn on the Sim Control. It is able to load HD map. I also set the destination and run the simulation. It works fine.
does it mean the HD map working fine? if so then maybe something wrong or missing with IMU and GPS data. 
![image](https://user-images.githubusercontent.com/53098029/124377534-a4a9a900-dcac-11eb-9276-f758eea88258.png)

![image](https://user-images.githubusercontent.com/53098029/124377498-82179000-dcac-11eb-8cb1-45a8ab8ea7a2.png)

**Comment by daohu527** [comment]
Yes, `sim_control` will automatically find nearby road and load it, I think you need to check the location of the gps

**Comment by trieuthachvu** [comment]
Yes, it is right. I take the position data from Sim Control and feeding it to localization module. I am able to see the HD map.
I try to  change my simulator to different coordinates but still not able to get similar position as Sim Control.

I have a question regarding the system coordinates (Inertial/GPS(Geo)/Vehicle coordinates).
My simulator supports to output data in different coordinates.
In apollo Cyber message
apollo::drivers::gnss::Imu, look like it is in vehicle coordinates
![image](https://user-images.githubusercontent.com/53098029/124397083-01897b80-dd0e-11eb-87cc-f06774dafed3.png)

apollo::localization::Gps and apollo::localization::CorrectedImu look like it is in Inertial coordinates.

![image](https://user-images.githubusercontent.com/53098029/124397150-7c529680-dd0e-11eb-9e8b-126d46821680.png)

Does it have to be like GPS (must be in Geo Co-ordinates) and IMU (in Inertial)?

I found in Apollo documents, y axis point out the front of vehicle.
![image](https://user-images.githubusercontent.com/53098029/124397417-fa636d00-dd0f-11eb-87df-cc92d3304edd.png)

but in my simulator systems, it is x axis pointing out the front of vehicle
![image](https://user-images.githubusercontent.com/53098029/124397486-575f2300-dd10-11eb-83f9-fb432b4dbf14.png)

In addition, is there any chance that when I convert standard OpenDrive to Apollo HD map, the coordinates and origin are also changed ?

**Comment by daohu527** [comment]
I think the car body coordinate affects the perception module but not localization.

localization is an UTM coordinate, so I think you should check the simulation is output UTM but not gps. Here is a [doc](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/docs/specs/coordination_cn.md)

**Comment by trieuthachvu** [comment]
You are right, it does not impact on GPS location.
If x, y & z positions on HD map have the same unit as meter (m)
then I found there is a mismatch on the map location between the map on simulator and the HD map

![image](https://user-images.githubusercontent.com/53098029/124415112-68318800-dd54-11eb-8b55-352fcbb8e1cd.png)
![image](https://user-images.githubusercontent.com/53098029/124415317-e68e2a00-dd54-11eb-8973-31f38a5040c7.png)

**Comment by daohu527** [comment]
## mismatch
1. apollo use UTM coordinate, and it have a map we call `apollo-hd-map`.
2. simulation have a model map. It is usually a relative position map, so the simulator will add rotation and translation and convert it into gps coordinates

So I guess there is no good match between the two. I don't know how the map in your simulator and the map of Apollo are generated. There may be a problem!!!

**Comment by trieuthachvu** [comment]
Yes, my simulator use cartesian xyz then I got to convert it to UTM.
look like I got to convert cartesian to lat long (geo) then to UTM by using proj4 string. 
although I do not really understand proj4.

**Comment by ntutangyun** [comment]
Hi, check out this website. 

https://ntutangyun.github.io/apollo-hd-map-viewer/ 

you may simply upload the base_map.bin to visualize it.
