### ISSUE TITLE
Lack of initialization of variables.

### ISSUE THREAD

**Issue by randomacco** [ApolloAuto/apollo#13921]
Dear Apollo team, thanks for creating this wonderful tool!   
**Describe the bug**
We recently find a bug via our automated tool. This bug is located in lane_change_decider.cc IsPerceptionBlocked (https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/planning/tasks/deciders/lane_change_decider/lane_change_decider.cc#L368). We found that the necessary initialization are missing in IsPerceptionBlocked function. To be more specific, right_most_found, right_most_angle, and left_most_angle are variables maintained for each obstacle and they are not initialized when processing a new obstacle. The following figure is an example we discovered that can trigger the vulnerability. All the lanes are clear except the front blocking obstacle we put to create a lane borrow scenario. The ego vehicle makes a stop decision for this side-pass. After more investigation, we found that this could be caused by uninitialized variables. When the beam scanning first scans the left side obstacle, it will get updated left_most_angle and right_most_angle. Also, the right_most_found is set to be true. When processing the 2nd obstacle, as long as the obstacle does not have intersection with the first beam, the statement “left_most_angle = beam_heading - search_angle;” will be executed. As a result, left_most_angle will be set with “adv_heading - 0.5 search_range” due to the right_most_found being uninitialized. As long as the difference between right_most_angle of the first obstacle and the current left_most_angle is larger than the predefined threshold (0.5), the ego vehicle will make a stop decision on side-pass.

**To Reproduce**
Here is a setup of a driving scenario that trigger this bug. 
We first set up a lane borrow scenario with a vehicle blocking the lane. Then we put two small boxes off the road. The requirements for the boxes are very easy to be satisfied. We can put the first box on the left side of the road to make sure the right_most_angle of this box is large enough. The second box just needs to be visible to the ego vehicle. As a result, the ego vehicle will stop there permanently. 

**Expected behavior**
The Apollo should finish lane borrow successfully since no obstacle is on the road.
**Screenshots**

![image](https://user-images.githubusercontent.com/86978656/124504267-f79e6180-dd7b-11eb-95c2-ac07d30c3d23.png)

**Comment by daohu527** [comment]
The same question https://github.com/ApolloAuto/apollo/issues/13882
