### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.

### ISSUE THREAD

**Issue by hgrn71** [ApolloAuto/apollo#13929]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Ubuntu 20.04
- **Apollo installed from (source or binary)**:git zip
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0
- **Output of `apollo.sh config` if on `master` branch**:

after install docker,the execute cmd:
dev_start.sh
show some errors output:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.

I am new to Apollo,I do not know why.

**Comment by daohu527** [comment]
It might be a docker permission problem, you can try to confirm if this is the issue
