### ISSUE TITLE
Overly large lateral buffer for static obstacles

### ISSUE THREAD

**Issue by randomacco** [ApolloAuto/apollo#13922]
Hi Apollo team, thanks for creating this great project. When I analyze the code recently, I found that when deciding whether it is clear (considering the static obstacles) for the ego car to pass, Apollo's code uses a lateral buffer 0.4m (https://github.com/ApolloAuto/apollo/blob/master/modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc#L1550).

However, this lateral buffer is too big such that if there exist two static boxes off the lane (one on left side and the other one on right side), the car will still stop even if the lane is empty. In our setup, the car width is 2.11m, the lane width is 2.7m, and the lat_buffer is 0.4m. After adding lat_buffer to the obstacles, the remaining space is (2.7- 2*0.4 ) 1.9m, there is no enough space for the vehicle to pass. 

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04 LTS
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**: master

**Comment by daohu527** [comment]
These parameters are about safety settings. You cannot guarantee that vehicles will pass, especially at high speeds.

And the size of obstacles recognized by perception may not be completely reliable
