### ISSUE TITLE
bash docker/scripts/dev_start.sh 

### ISSUE THREAD

**Issue by hgrn71** [ApolloAuto/apollo#13923]
### System information

- ubuntu 20.04.2
- https://github.com/ApolloAuto/apollo
- r6.0.0:
run cmd :
bash docker/scripts/dev_start.sh
...
[INFO] Starting docker container "apollo_dev_huangrun" ...
+ docker run -itd --privileged --name apollo_dev_huangrun -e DISPLAY=:0 -e DOCKER_USER=huangrun -e USER=huangrun -e DOCKER_USER_ID=1000 -e DOCKER_GRP=huangrun -e DOCKER_GRP_ID=1000 -e DOCKER_IMG=apolloauto/apollo:dev-x86_64-18.04-20200914_0742 -e USE_GPU_HOST=0 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility --volumes-from apollo_map_volume-sunnyvale_big_loop_huangrun --volumes-from apollo_map_volume-sunnyvale_loop_huangrun --volumes-from apollo_map_volume-sunnyvale_with_two_offices_huangrun --volumes-from apollo_map_volume-san_mateo_huangrun --volumes-from apollo_localization_volume_huangrun --volumes-from apollo_audio_volume_huangrun --volumes-from apollo_yolov4_volume_huangrun --volumes-from apollo_faster_rcnn_volume_huangrun --volumes-from apollo_local_third_party_volume_huangrun -v /home/huangrun/Git_Project/apollo_6_0:/apollo -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in-dev-docker:127.0.0.1 --add-host huangrun-HP-EliteBook-830-G8-Notebook-PC:127.0.0.1 --hostname in-dev-docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 apolloauto/apollo:dev-x86_64-18.04-20200914_0742 /bin/bash
e90e31cba1d85e67a644a9273a49da5d740c71a73b9d09825b713e9d773bd622
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.
+ '[' 125 -ne 0 ']'
+ error 'Failed to start docker container "apollo_dev_huangrun" based on image: apolloauto/apollo:dev-x86_64-18.04-20200914_0742'
+ echo -e '[\033[0;31mERROR\033[0m] Failed to start docker container "apollo_dev_huangrun" based on image: apolloauto/apollo:dev-x86_64-18.04-20200914_0742'
[ERROR] Failed to start docker container "apollo_dev_huangrun" based on image: apolloauto/apollo:dev-x86_64-18.04-20200914_0742
+ exit 1

**Comment by daohu527** [comment]
Are you a nested container, which means to start the container in the container

Then try below cmd , [ref](https://discuss.linuxcontainers.org/t/having-trouble-using-docker/383)
```
lxc launch ubuntu:16.04 -c security.nesting=true
```

**Comment by hgrn71** [comment]
i just first time to do the cmd, for prepare to build apollo project
bash docker/scripts/dev_start.sh

how to resolve the nested container

thank u

**Comment by daohu527** [comment]
Do you really understand nested containers, you must first check this!

**Comment by hgrn71** [comment]
how to check it？
