### ISSUE TITLE
roadshow.py dosen't work

### ISSUE THREAD

**Issue by Wangsir-sir** [ApolloAuto/apollo#13933]
**Describe the bug**
I get an error when I use the roadshow script to display the map.

**To Reproduce**
1.Run the script
```bash
./bazel-bin/modules/tools/mapshow/roadshow -m modules/map/data/demo/base_map.txt
```
2. See error:
```
/apollo/./bazel-bin/modules/tools/mapshow/roadshow.runfiles/apollo/modules/tools/mapshow/roadshow.py:39: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
```
**solution**
1. Download the necessary dependencies
```bash
sudo apt-get update
sudo apt-get install tcl-dev tk-dev python3-tk
```
2.Problem solved, run the script
```bash
./bazel-bin/modules/tools/mapshow/roadshow -m modules/map/data/demo/base_map.txt
```
The  solution also applies to MapShow.py

**Comment by daohu527** [comment]
I tested that the current version does have this problem.
```
Apollo version: 6.0
Ubuntu 18.04
```

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
