### ISSUE TITLE
How to load real data with apollo software platform?

### ISSUE THREAD

**Issue by luogyu7** [ApolloAuto/apollo#13932]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: ubuntu 18.04
- **Apollo installed from (source or binary)**:  source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  5.0
- **Output of `apollo.sh config` if on `master` branch**:  

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I need run Apollo software platform on ubuntu system(not on hardware vehicle , not the demo_3.5_record file), So What should I do to realize the apollo  platfom running in real life data.    Whether I need to record files by myself,and run it on apollo? Is there any other way to make sure I'm running Apollo in real life  
### Supporting materials (screenshots, command lines, code/script snippets):
I can currently run in a simulation environment. BUT I need run in real life data.What are some ways to make cars run in the real world(or real world data)  on Apollo software platform?
I have the real life data at https://apollo.auto/southbay_cn.html .  Can I  use them on apollo platform? Any tutorial or document?

![1](https://user-images.githubusercontent.com/67385330/125147711-8f76c380-e15f-11eb-8761-8fc4e1b5be4e.png)

![3](https://user-images.githubusercontent.com/67385330/125147900-2ee88600-e161-11eb-80af-9ef8895d79b5.png)

Except that I have run the Apollo platform independently with the demo file  demo_3.5_record ,and the state picture  such as :
![4](https://user-images.githubusercontent.com/67385330/125149264-8a6b4180-e16a-11eb-83d9-7520fb4f1460.png)

Thanks for your reply.
Many thanks for your help.

**Comment by daohu527** [comment]
The best way is to test on the dataset. If you want real data, you can collect it yourself, as far as I know, no one else is sharing real data other than public datasets
