### ISSUE TITLE
virtual_lane_generation

### ISSUE THREAD

**Issue by Wangsir-sir** [ApolloAuto/apollo#13935]
Hi Apollo team.Recently I noticed a [document](https://hub.fastgit.org/ApolloAuto/apollo/blob/master/docs/D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md#3-%E8%8E%B7%E5%8F%96%E8%99%9A%E6%8B%9F%E8%BD%A6%E9%81%93%E7%BA%BF%E5%B9%B6%E6%B7%BB%E5%8A%A0%E5%88%B0apollo%E4%B8%AD) that explains how to make virtual lane lines, and I also noticed that the resulting virtual lane lines file has the same file type as Apollo's HD map file. I have some questions I don't understand：
1.What is the relation between virtual lane lines and HD maps? Do virtual lane lines also belong to a simplified version of HD maps?
2.What do virtual lanes line do? HD map plays a important role in the perceptual module, decision module and planning module. Do virtual lane lines play a similar role?
3.Is virtual lane line essential in real environment?

**Comment by daohu527** [comment]
The doc is [here](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md) which is used for d-kit in park or some where. 

I think it's a hd-map. You know that some parks do not have lane lines, then we use virtual lane lines to replace lane lines.
