### ISSUE TITLE
Missing shared libraries from Docker

### ISSUE THREAD

**Issue by VEWOXIC** [ApolloAuto/apollo#13947]
We used to use the test file 
`./modules/perception/camera/test/camera_app_traffic_light_camera_perception_test.cc`
which works perfectly about 2 months ago. But this week it reports missing shared libraries error and I cannot find the mkldnn.so on the Internet. 
Is the docker file changed? 

### System information

- **OS Platform and Distribution  Linux Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 5.5**:

### Steps to reproduce the issue:
- Pull Apollo5.5.0 from github
- run 'dev_start' and 'dev_into'
- We want to run the test file in the following path
`./modules/perception/camera/test/camera_app_traffic_light_camera_perception_test.cc`
so we uncomment the BUILD lines for this file, it look like this 
`cc_test(
    name = "camera_app_traffic_light_camera_perception_test",
    srcs = ["camera_app_traffic_light_camera_perception_test.cc"],
    linkopts = [
        "-lnvinfer_plugin",
    ],
    deps = [
        "//modules/perception/camera/app:traffic_light_camera_perception",
        "//modules/perception/inference:inference_factory_lib",
        "//modules/perception/inference/operators:perception_inference_operators",
        "@caffe",
        "@com_google_protobuf//:protobuf",
        "@opencv",
        "@tensorrt",
        "@gtest//:main",
        "@yaml_cpp//:yaml",
    ],
)`
The file is uploaded below.
- run 'bash ./apollo.sh build_opt_gpu' in docker, and this can compile successfully
- run 
`./bazel-bin/modules/perception/camera/test/camera_app_traffic_light_camera_perception_test`
and report
`./bazel-bin/modules/perception/camera/test/camera_app_traffic_light_camera_perception_test: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory`

- following the instruction in issue #10873, [https://github.com/ApolloAuto/apollo/issues/10873](url), run
`sudo apt-get install libboost-system1.54.0 libboost-filesystem1.54.0 libboost-program-options1.54.0 libboost-thread1.54.0 libboost-signals1.54.0`
in the docker
- try again
`./bazel-bin/modules/perception/camera/test/camera_app_traffic_light_camera_perception_test`
- report error:
`./bazel-bin/modules/perception/camera/test/camera_app_traffic_light_camera_perception_test: error while loading shared libraries: libmkldnn.so.0: cannot open shared object file: No such file or directory`

**Comment by VEWOXIC** [comment]
Place these files under 
`./modules/perception/camera/test/camera_app_traffic_light_camera_perception_test.cc`
[modified files.zip](https://github.com/ApolloAuto/apollo/files/6829000/modified.files.zip)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
