### ISSUE TITLE
Can I add a GPS other than Novatel? 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#13949]
### System information
Ubuntu 20.04 

I'm trying to add a new GPS to apollo. However, after looking at the documentation on how to add a new GPS it seems like apollo specifically looks for a Novatel GPS.  How do I add a GPS that isn't Novatel? Does a USB connection work? How do I configure? How do I find out the format of my GPS? I'm using U blox GPS. Do I need to change anything for 5.0?https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_gps_receiver.md (Step 2).

**Comment by jp12AI** [comment]
I found out how to use u-blox gps. No need for help

**Comment by wijdim** [comment]
@jp12AI I m working on the same subject, I added a ubx_parser class and now trying to send a ublox files (.ubx) using nc in udp protocol, did you had this issue?  what changes did you make for configuration to ublox?

**Comment by wijdim** [comment]
@jp12AI ??

**Comment by daohu527** [comment]
So what's you problem now? You can open a new issue then we can discuss there.
