### ISSUE TITLE
Parser  Recorder file

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#13948]
Hi My System information is below:

- OS: Ubuntu 18.04
- Apollo installed from binary. I mean I am using Docker. Installed using this tutorial to clone the repo, etc: https://www.svlsimulator.com/docs/archive/2020.06/apollo-master-instructions/
- Apollo version: Apollo.Auto 6.0

### Steps to reproduce the issue:
Hi I am trying to plot data from a simulation. I need to compare different planners. For that I need to take for example:
- Odometry data 
- GNSS data
- Control Data
- Planning Data
- etc

At first I have recorded the channels using the cyber_record tool, through the command below:

`cyber_recorder record -all`

Or just triggering the record tab on Dreamview panel. Then I got all the recorded channels data stored on this folder:

![image](https://user-images.githubusercontent.com/43826438/126016606-1a3c614d-95b4-4456-a7e3-d67327a4e8dc.png)

Afterwards I followed this tutorial https://github.com/ApolloAuto/apollo/tree/master/modules/tools/record_parse_save
to get info from the recorded data and finally parse this data to .txt format. My idea is later get this .txt data convert to .csv or DataFrames to plot the data. However unfortunately I got the error: **NO SUCH FILE OR DIRECTORY** below after following the tutorial commands:

![channels_ok_but_parse_record_not](https://user-images.githubusercontent.com/43826438/126016701-f0868bc2-77a6-4c33-a560-925a8f937b39.png)

The record file was stored successfully and the info from the messages recorded from multiple channels can also be vizualized above. However the r**ecord_parse_save**.**py cannot find the parser_params.yaml** **file,** which exist and is located in the correct folder, as you can check below:

![file_exist](https://user-images.githubusercontent.com/43826438/126016747-093ba764-a103-4af9-b0d1-9990e7a175bb.png)

I do not know what is wrong and why the module record_parse_save.py cannot  open the folder and find the parser_params.yaml file.

Is this code wrong?  Can someone from Apollo team check this for me, what should I do to get this module working and take the parsed data that I need?

Thanks in advance

**Comment by daohu527** [comment]
1. You should modify the input path in func `read_parameters`. The latest code has fixed this bug!
2. Also if you want to parse lidar you should modify the config in `parser_params.yaml`, seems can't parse all message type once.

**Comment by marcusvinicius178** [comment]
Hi @daohu527 thanks very much for the answer. You mean I should replace the input path by the one you shared above or other? Which path specifically?

No I don't wish lidar data. I wish to parse other days recorded, such as Odometer, IMU, control, planning, time 
I will compare 2 different path planners and I need to plot this data and compare graphically against each other. Considering the listener option and plot functions available on Apollo Dreamview are just online I believe the only way to plot these data is:
1- Record Channels
2- Use the parser tool to getting this parsed data with .txt format 
3- Convert to CSV or Data frames to plot them more easily.

Or is another way to plot this data easily for further presentation on my master Thesis.
I would like to get those plots available on PNC monitor in Dreamview. They are pretty good. How is it possible?

Thanks in advance

**Comment by daohu527** [comment]
1. No, it use for parse the recording package.
2. If you want to parse other message, you should write new code.

**Comment by marcusvinicius178** [comment]
@daohu527  I understand but the recorded package contains the other channels Data (Odometer, IMU, Planning, Control, etc). When the parser tool parses a recorded file for the Radar, lidar or camera data do These other data channels come parsed together in .txt format?

I could not check the parser tool functionality as I have displayed you I had an error NO MODULE NAMED MODULE DRIVERS when I executed the parser command. 

1 - Why do I get this error and how to fix it?
Again: I don't got data from real sensor (camera, lidar or radar) but the data is coming from LG SVL simulator. Is this the error related to or not? Other error in Code?

I would like to see a parsed recorded data...how it comes, maybe the other channels Data I wish come along with it.


Finally if you can really assure me that the other channels Data ( Odometer, IMU, etc) do not come after parse the .record file, how can get these other channels Data (Odometer, IMU, control, planning, etc) to plot it ?

Thanks in advance

**Comment by marcusvinicius178** [comment]
@daohu527  a last addition of the previous question. As I am not sure if the Parser tool will be enough to get the channels data, I took a look into the plot tools from Apollo:

A - realtime_plot.py : This module is the responsible to plot the graphics available on PNC monitor on Dreaview, corrcet?
It subscribes chassis, ADCTrajectory and other data. As far as I understood it get the car speed, steer angle, curvature and updates this data, and plot this data dynamically syncronized with the running time on the simulation side. It contains the callback functions required to get this data and the matplotlib is responsible to create the axis, labels, the plot design...while the cyber monitor is not shutdow,, in other words, a dynamic plot.

I have also checked the modules:

B) plot_trace: plot_planning_result.py and plot_trace.py: https://github.com/ApolloAuto/apollo/tree/master/modules/tools/plot_trace
C) plot_control: plot_control.py and realtime_test.py : https://github.com/ApolloAuto/apollo/tree/master/modules/tools/plot_control

D) plot_planning: https://github.com/ApolloAuto/apollo/tree/master/modules/tools/plot_planning

They are composed of numerous valuable modules, that subscribe the channels data and plot these channels dynamically:

![plot_planning](https://user-images.githubusercontent.com/43826438/126072476-0be54acd-4e43-4fdb-acb3-4812e49eaf18.png)

I wish to know how to plot this data for specific window/amount of time. Let me say I wish to plot from:

The beginning of the simulation: Time = 0
End of the simulation: Time = 45 Seconds 

I wish to plot then for example data for the imu channel, that as we can check in figure above is defined on imu_speed.py for example. But I wish a STATIC data, have a LIST of all the IMU data in each second (TimeStamp), therefore I would have 45 points of IMU data to plot against the Time (45 seconds) or against other parameter (acc_jerk for example).

At the end I wish plot a graphic like this:

![image](https://user-images.githubusercontent.com/43826438/126072692-282073e5-d667-4075-990f-28d75f9db660.png)


I need to copy this graphic to put on the thesis, therefore the dynamic graphics feature does not work for me but STATIC.

Which snippet of code from these modules must I change to make these modules plot static data?
Do you have an example or other modules that get and plot static data to provide me please?


Thanks in advance

**Comment by daohu527** [comment]
there is a [cyber record](https://github.com/daohu527/cyber_record) parser tool for now. 

Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
