### ISSUE TITLE
TimeSynchronizer like ROS

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#13943]
Did cyber have TimeSynchronizer function like ROS, so We can receive msg in a syncronized timestamp when different sensor have little timestamp shift.?
When I use Component to receive msg from two channles  in the  Proc function, It seems we can only get the latest msg of the second msg channle when the 1st channle  got a msg.

**Comment by daohu527** [comment]
You're right, the cyber message fusion always use `all_latest_fusion`. Seems ros have another way of data fusion.

## temporary plan
You can subscribe the two message use `cyber::Reader` and deal with yourself

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
