### ISSUE TITLE
Build did NOT complete successfully

### ISSUE THREAD

**Issue by AMEKNI** [ApolloAuto/apollo#13945]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04):  Ubuntu 18.04.5 LTS
- **Apollo installed from (source or binary): source
- **Apollo version (3.5, 5.0, 5.5, 6.0): 2.5

### Steps to reproduce the issue:
- **when building Apollo inside Container with ./apollo.sh build, i have the Following Error " fatal error: localization_msf/gnss_struct.h: No such file or directory"

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/87365572/125806142-3579fbd2-6417-4715-ad37-928b6ca0d8f5.png)

**Comment by daohu527** [comment]
Pls check the file in `apollo\third_party\localization_msf`

**Comment by AMEKNI** [comment]
Hi, I checked that file and find it, 
![image](https://user-images.githubusercontent.com/87365572/125909242-dd5464e8-1977-4554-900f-e53201a85628.png)
!!!!!!!!!!

**Comment by AMEKNI** [comment]
Hi, I find only the BUILD file!!!!!!!!!!!!! why i can't find the gnss_struct.h file?????
![image](https://user-images.githubusercontent.com/87365572/125910363-577cc8cc-020a-47a3-99ba-ab2ad5593aa8.png)

**Comment by AMEKNI** [comment]
I find the gnss_struct.h file in apollo/third_party/localization_msf/x86_64/include
![image](https://user-images.githubusercontent.com/87365572/125910996-292f59a1-e1da-4ea6-8d30-7790928f3bfb.png)

**Comment by AMEKNI** [comment]
I Need help !!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by daohu527** [comment]
Yes, the file is already exist!

then we should look for other reasons

**Comment by AMEKNI** [comment]
do you have any idea about other reasons?

**Comment by daohu527** [comment]
You can recompile and have a try then.
