### ISSUE TITLE
Extract the Channels Messages To further Plot. How ? 

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#13958]
Hi My System information is below:

- OS: Ubuntu 18.04
- Apollo installed from binary. I mean I am using Docker. Installed using this tutorial to clone the repo, etc: https://www.svlsimulator.com/docs/archive/2020.06/apollo-master-instructions/
- Apollo version: Apollo.Auto 6.0

### Steps to reproduce the issue:

Hi Apollo Team. 
**I need to extract the messages contained inside the Apollo Channels**:

![channels_messages](https://user-images.githubusercontent.com/43826438/126404589-a16d5ae2-c976-4387-bf89-d924d2b0650f.png)

I have already tried to:

1. **Record the Channels** data using the cyber recorder tool: 

`cyber_recorder record -all`

2. **Parse the recorded files** using the parser tool, to get the data on .txt format:

`./bazel-bin/modules/tools/record_parse_save/record_parse_save`

However this did not work as already discussed in this issue: https://github.com/ApolloAuto/apollo/issues/13948

My attempt resulted in this error: 
**from modules.drivers.proto.conti_radar_pb2_import ContiRadar
ModuleNotFoundError: No module named "modules.drivers"**

A similar error appears when modifying the parser_params.yaml file for just extract for the camera or just the lidar.

The issue is that I DO NOT WISH  GET  THE MESSAGES DATA JUST for these PERCEPTION SENSORS.
**I WISH TO EXTRACT THE MESSAGES FOR ALL THE OTHER CHANNELS AS I DISPLAYED IN THE FIGURE ABOVE.**

Actually I need the channels data **TO PLOT CHARTS** using MATPLOTLIB or other tool...
I need this data in .**csv or .txt or even in other programatic structure, such a list, dictionary or Dataframe**. 
I just need this messages data in someway that is possible to Plot.

I took a look already in the realtime_plot.py and the other plots from documentation:

- https://github.com/ApolloAuto/apollo/blob/master/modules/tools/realtime_plot/realtime_plot.py
- https://github.com/ApolloAuto/apollo/tree/master/modules/tools/plot_trace
- https://github.com/ApolloAuto/apollo/tree/master/modules/tools/plot_control
- https://github.com/ApolloAuto/apollo/tree/master/modules/tools/plot_planning

All these modules code plot the data dynamically, However I **do Not wish A Dynamic Plot, as the PNC Monitor provides on Dreamview**. 
I need a s**tatic Plot, plotted from a specific size of an array of messages,** in order to put on my research project.

Could you please assist me on this issue?

Thanks in advance

**Comment by daohu527** [comment]
Your question is usually too long, I think we should focus on the problem. Your question is very simple, **it is to decompress the data**.

## steps
1. You can decompress lidar and camera data first, If you have any problems, then we solve this problem first!!!
2. Next, we will solve the problem of radar or other sensors

Therefore, we do not have to merge these two problems. Before solving the first problem, I suggest you not consider others. I have tried version 5.0 and it is ok, I will try version 6.0 later

**Comment by marcusvinicius178** [comment]
Hi thanks very much again for your patience and support! 

> Your question is usually too long, I think we should focus on the problem. Your question is very simple, **it is to decompress the data**.
> 
Hi. Actually I tried to give as much detailed information as recommended (print screen and the step-by-step to reproduce the error). But I will try to shrink the question next time.
I believe the issue is decompress or desserialize the data, you are right! I just am not having success for some reason :(

> ## steps
> 1. You can decompress lidar and camera data first, If you have any problems, then we solve this problem first!!!

Ok would be nice! The error I had regarding camera, lidar or radar is:

**from modules.drivers.proto.conti_radar_pb2_import ContiRadar
ModuleNotFoundError: No module named "modules.drivers"**

after executing:

`./bazel-bin/modules/tools/record_parse_save/record_parse_save`

It would be nice have this data too. However I am really not interested on these perception data decompressing, **but the other channels data (Odometry, Localization, Planning, Control,** etc)  as I have red highlighted  below:

![channels_messages](https://user-images.githubusercontent.com/43826438/126404589-a16d5ae2-c976-4387-bf89-d924d2b0650f.png)

It is **really important to me get this messages** in .txt or .csv or a list, array or other programatic format in which **I can plot**.

> 2. Next, we will solve the problem of radar or other sensors
If you think it is the most proper way to follow, I agree.  But as I said for me **the camera, lidar or radar data does not matter too much**.... it does not say too much for path planners benchmark comparison... 


> Therefore, we do not have to merge these two problems. Before solving the first problem, I suggest you not consider others. I have tried version 5.0 and it is ok, I will try version 6.0 later

I did not understand your suggestion? I can totally agree and follow this suggestion as soon as I get the other channels messages...

Regarding the **5.0 version I tested today in 2 different machines**: My notebook and a more powerful rented server. However **I had some issues** with it (that I did not have with Apollo 6.0). If you could help me to fix it I will be very grateful:

1. The cyber_visualizer is not working, after issue the cmd I get:
`/apollo$ cyber_visualizer
Could not initialize GLX
Aborted (core dumped)
`

2. Then I tried to install the pyyaml module and also got an error:

`apollo$ sudo pip install pyyaml
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python2.7/dist-packages
Cleaning up...
`

3. In addition the record_parse_save folder and module does not exist inside the path:

`./bazel-bin/modules/tools/record_parse_save/record_parse_save`

So when I runned the command above I got the error: **No such file or directory**


The complete tests and steps can be visualized on youtube videos:

1 - On my notebook: https://youtu.be/fgZSQ-mlxF8

2 - On the rented server machine: https://youtu.be/otFF6e52R_E


For this reason it **was not possible to check** if the cyber_visualizer displayed the channels data and make the parser tool work, unfortunately. 

In both machines I tested, I had previously Apollo6.0 release installed. I imagined that some versions conflict could be leading this errors. Then I have removed the docker images, and purged every cache I could, to see if this was the issue of the core dumped problem and the other errors. Starting from "scratch" system these errors persist. 

I used this tutorial to build apollo 5.0 along SVL simulator: https://www.svlsimulator.com/docs/system-under-test/apollo5-0-instructions/

Do you believe this forked repository does not contain the proper code to launch cyber_visualizer, pyyaml, and the record_parse_save folder? Or is another issue? 

I accept any recommantion to **clean the system properly, if be the cause of this error**. Because months ago I believe have used the Apollo 5.0 and I believe the cyber_visualizer was working if I am not wrong....but now does not...

Sorry to describe the problem a lot. But I like to detail what is going on and my goals to make it more clear.

Thanks in advance.

**Comment by daohu527** [comment]
Then we focus on apollo 5.0. We only do one thing at a time!!!

You can try the following steps to get lidar data
## steps
1. modify `record_parse_save.py` in apollo5.0 to below code
https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/record_parse_save.py#L134 
2. modify the path below
https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/parser_params.yaml#L2
3. modify the topic
https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/parser_params.yaml#L11
4. run cmd
```
python modules/tools/record_parse_save/record_parse_save.py
```

**Comment by marcusvinicius178** [comment]
> Then we focus on apollo 5.0. **We only do one thing at a time**!!!
Ok I agree
> You can try the following steps to get lidar,camera and radar data
> 
> ## steps
> 1. modify `record_parse_save.py` in apollo5.0 to below code
>    https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/record_parse_save.py#L134
Ok I have done
> 2. modify the path below
>    https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/parser_params.yaml#L2
Ok I have done and replace by:
filepath: /apollo/data/bag/
Where I am putting my recorded data from cyber_recorder

> 3. modify the topic
>    https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/parser_params.yaml#L11

Modify for which Topic? For my car Lincoln MKZ configuration I have the ones available below:

![image](https://user-images.githubusercontent.com/43826438/126717551-89b4195d-adf5-4bcb-bf53-bbe3b007ef0d.png)

It seems I do not have radar or velodyne data, just the camera topics...Should I create a new car configuration on SVL simulator? To add radar and Lidar?

> 4. run cmd
> 
> ```
> python modules/tools/record_parse_save/record_parse_save.py
> ```
I runned unfortunately I am having this error:

sudo pip install pyyaml
`

Afterwards I remembered from tutorial: https://github.com/ApolloAuto/apollo/tree/master/modules/tools/record_parse_save
That I must install the pyyaml:

`sudo pip install pyyaml`

And here is a big issue that I raised when I executed the command above:

`ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python2.7/dist-packages
Cleaning up...
`

Then I imagined that this issue was regarding some conflict of Apollo Versions Installed on my Notebook. Because I have already runned the previous command, when I was using Apollo 6.0.
To fix it I followed a tutorial that suggested to issue the commands:

`sudo pip install pyyaml`
My output:
`ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python2.7/dist-packages
Cleaning up...
`
And the command: 
`sudo easy_install pip`
My output:
`ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Searching for pip
Best match: pip 1.5.4
Adding pip 1.5.4 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin
Using /usr/lib/python2.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip
`

Then I concluded that I needed to remove the PYYAML module and reinstall. And I did:

`pip list`

Output was the list of python packages installed:

`pyparsing (2.0.1)
pypcd (0.1.1)
pyproj (1.9.5.1)
python-apt (0.9.3.5ubuntu3)
python-dateutil (1.5)
python-gflags (3.1.2)
python-lzf (0.2.4)
pytz (2012c)
PyYAML (3.13)
requests (2.2.1)
rospkg (1.1.7)
scipy (0.13.3)
`

And then I have removed the PyYAML:

`sudo pip uninstall pyYAML`

I think this was a big error, because now I cannot install it anymore. And I got a lot of errors:

![image](https://user-images.githubusercontent.com/43826438/126718460-4a1f8ef7-cf21-423a-a92b-ae98877511d0.png)


I tried to solve but have found no solution...
How should I proceed?

**Comment by marcusvinicius178** [comment]
Hi Mr. @daohu527 I have **installed python3-pip** again on my notebook host ( I am using Ubuntu 20.04 on my notebook and ubuntu 18.04 in another rented cloud machine).
And then exited and login again inside the docker image. Afterwards reinstalled the pyYaml module and tried to run the parser. The output is below:

![image](https://user-images.githubusercontent.com/43826438/126720709-c8993edf-f0dc-4359-84dc-f2407a9b795f.png)

I am not a computer science/software engineer/linux expert...however I believe that I am facing a Python version compatibility error:

![python_Version_error](https://user-images.githubusercontent.com/43826438/126721200-f3acd947-4aad-4bdb-a841-5f5bb202976b.png)


 It seems I have inside the docker image the 2.7 python version installed, but the code requires python 3....from cyber.python.cyber_**py3** import cyber 
And on my host I have the python 3.8 installed. I know the docker is an isolated environment...so I a little bit confuse. 
What should I do? Upgrade the python version inside docker? Could you kindly provide the right steps (commands lines) to fix this issue, please?

Then we can go further on channels data extraction..

Thanks in advance

**Comment by marcusvinicius178** [comment]
In a summarize I am facing the errors below:

When Running 

`python modules/tools/record_parse_save/record_parse_save.py`

I have the error:

![image](https://user-images.githubusercontent.com/43826438/126724584-2bbb759e-a21a-4e3d-8e76-ea66905af045.png)



When Running 

`sudo pip install pyyaml`

The error:

![image](https://user-images.githubusercontent.com/43826438/126724553-cc6731d3-5df5-4ab4-9bb0-70d9215cd7ad.png)

**Comment by daohu527** [comment]
Are you really running in **5.0**? I personally tested 5.0 and there is no problem.

I think you have complicated the problem. If the yaml file is not found, I don’t think you need to reinstall the yaml library.

**Comment by marcusvinicius178** [comment]
Yes Mr. @daohu527 I am running Apollo 5.0 I have followed the tutorial from LG Svl Simulator: https://www.svlsimulator.com/docs/archive/2020.06/apollo5-0-instructions/

Did you cloned other repository or branch? I mean is it necessary to git branch?

I have gave permissions for the yaml file be executed as program, but the error kept. This File was located on the path you told me to change. I took a look accessing manually the folders. Therefore I do not understand why the parser does not find it.

That's why I asked you if the error is related to some python version issue or because I have installed different Apollo versions on the same machine?

Which is the best way to fix, could you suggest?
I am really in a hurry with my master Thesis Deadline and need to plot these charts. 

Thanks for your attention

**Comment by daohu527** [comment]
I use the official version apollo r5.0.0, I have not tested https://github.com/lgsvl/apollo-5.0.

I think the difference between them is not big, I think we should check the environment to find the reason why the file cannot be found. Did you modify the wrong repository? I can't think of any reason

Frankly speaking, too many tests seem to work hard, but they fail to grasp the **essence of the problem**. This is my personal suggestion.

**Comment by marcusvinicius178** [comment]
Mr @daohu527 I am sorry sometimes I answer a little bit late because of fuse. It is night for me.  I do not know if it is possible for you to assist me by TeamViewer or other means? 
I was living in Germany last year this is my what's app number: 0178 8728 609 and my email: marcusvini178@gmail.com

I am willing to pay for some support on this regard if necessary. Really need the plots...

 I do not know if you're an Apollo employee or if you also do this support paid assistance?

Regarding the error, I worked a lot with ROS. And this error raised when the filename was wrong or the path, or if I didn't source the correct setup.bash...
But I checked the path, the filename and sourced...

Regarding the repo. Currently I have just the Apollo5.0 installed on my machine, so it is not possible to have done the modification in the wrong repo.
BUT one time an Apollo user helped me on other issues with TeamViewer and he told me that when we accesses the branch (git branch tag/ r5.0) some command like that.... Then in this way the repo will have all the modules needed....He told me that the LGSVL repo has a kind of "general" modules and funcionalities but not all of them....

So how could we keep working on this topic? Exchanging messages here or a more dynamic connection is possible?

**Comment by daohu527** [comment]
You could check you branch with
```
git branch
git checkout -f r5.0.0
```

I’m just a contributor to this project. I don’t provide any paid services. I understand your situation very well, but basically all problems are solved by yourself. Even if you solve this problem, I am very worried in view of your previous tasks. You can't finish it.

If you want to solve your problem as soon as possible, I suggest you add logs and print it out!

**Comment by marcusvinicius178** [comment]
@daohu527 I understood no worries.

You mean that get the channels data is not possible so easily with the parser tool? I infer that saying that you tell me that the parser will return a .txt just for the camera, lidar or radar channel right? Not the other ones I need (Odometry, planning, IMU, etc)? 

I really don't understand why it is so hard to get this data. Because the rosbag worked so easily is just to rosbag record and later rosbag_to_csv command or choose the output format and Voila the topics data you wish is available! 

Please what do you mean by get the logs and print out? The logs contain the channels Data? If they have I could take a shortcut... Right? These logs are accessible by text editor?  They are those ones located inside the logs folder or are other ones?

Thanks for the support and hints again!

**Comment by marcusvinicius178** [comment]
@daohu527 I took a look in each log file inside the folder /data/logs

Any of them contain the messages of any cyber channels, unfortunately.

The parser tool is the only way to extract the Channels data? 

I took a look into the record_viewer.cpp file and it seems it was created for the goal I need, that is convert the channels Data to string to visualize it. This code is used inside the parser tool?

As I asked you, I ask again the parser tool if works will just extract data for camera, lidar or radar? The other channels Data will not come after run this command with success? What was your output file when you executed in Apollo 5.0. Could you share it with me please?

**Comment by marcusvinicius178** [comment]
@daohu527  I have installed the Apollo5 from a fresh system (New cloud rented machine).

I reproduced these steps:

> Then we focus on apollo 5.0. **We only do one thing at a time**!!!
> 
> You can try the following steps to get lidar,camera and radar data
> 
> ## steps
> 1. modify `record_parse_save.py` in apollo5.0 to below code
>    https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/record_parse_save.py#L134
> 2. modify the path below
>    https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/parser_params.yaml#L2
> 3. modify the topic
>    https://github.com/ApolloAuto/apollo/blob/1b2d76e193616f55c1ed4abfbceca6da0d6ca6e6/modules/tools/record_parse_save/parser_params.yaml#L11
> 4. run cmd
> 
> ```
> python modules/tools/record_parse_save/record_parse_save.py
> ```


Then I keep having Import error issues. Please take a look:

If I run the last command using:

`python modules/tools/record_parse_save/record_parse_save.py`
or 
`python2 modules/tools/record_parse_save/record_parse_save.py`

I have the error:

![image](https://user-images.githubusercontent.com/43826438/126849977-50c71b55-13cd-4f23-8b56-0761173869b2.png)

However I I run the command with Python3. I have other error:

`python2 modules/tools/record_parse_save/record_parse_save.py`

![image](https://user-images.githubusercontent.com/43826438/126850009-6e63fcec-ccde-4661-9dd6-3d896a4e1cd1.png)


I have already installed the PyYaml inside the docker:

`sudo pip install pyyaml`

The output of "pip list"

![PyYAML](https://user-images.githubusercontent.com/43826438/126850146-046eef70-ebf0-410e-863f-f2dcb13c20b5.png)


Therefore I conclude this cyber_py3 module is missing or I am still facing Python versions issue?
Do not you really have this problem? Or the repository I have dowloaded from LG SVL is missing some modules or what is going on? 

Thanks in advance

**Comment by marcusvinicius178** [comment]
> I use the official version apollo r5.0.0

How to work with this repo? 

1- Did you clone the master repo: https://github.com/ApolloAuto/apollo
2 - And afterwards checkout to the r5.0.0 branch?

Or is needed to git clone from other repo?

It is not possible to me to:

git branch
git checkout -f r.5.0.0

I had error of **Not a valid object name: 'r5.0.0**

Because after git branch command, it returns I am on 
*simulator
And there are no branches from this repository, when I type git branch (TAB)

**Comment by marcusvinicius178** [comment]
I have also done the same steps after exit, stop the container, checkout to the 5.0 branch, start docker, enter docker, build, and repeated the same steps: install pyyaml, record all channels and run the parser...

![git_checkout_5 0](https://user-images.githubusercontent.com/43826438/126853614-0cd5ebc2-cbb9-4709-bdf8-2841d0084841.png)

The same error of **from cyber.python.cyber_py import cyber   ImportError: No module named python cyber_py3**

![image](https://user-images.githubusercontent.com/43826438/126855309-357e5e82-5ff5-40ec-89a1-647a8da7f330.png)

**Comment by marcusvinicius178** [comment]
To fix that I tried to change the module name:

from cyber.python.cyber_py3 to cyber.python.cyber_py2 and later to cyber.python.cyber_py3 and also to cyber.python3.cyber_py3

Any from these modifications worked. It does not find the module.

If I run  **python modules/tools/record_parse/record_parse_save.py**   With the modifications above I still get the error:

![image](https://user-images.githubusercontent.com/43826438/126855495-3fa50b60-501d-4eca-9403-a2797eef08b6.png)


or if I run  **python3 modules/tools/record_parse/record_parse_save.py** 

I also get another import error from python3, that seems conflicts with python2.7 library installed on /usr/local/lib

![image](https://user-images.githubusercontent.com/43826438/126855503-5f6e6491-91ba-40b3-ae11-5722254e3322.png)

I cannot imagine how you could run this command without these errors. I tired all possible manners to install and run it...

**Comment by daohu527** [comment]
I don't know what's the problem, you can add print to finish your work

Still the previous suggestion, only do things at a time, and solve it

## print

You can ref to the code `cyber/examples/listener.cc`, then subscribe to the topics you need, below is a print example
```
#include "cyber/examples/proto/examples.pb.h"

#include "cyber/cyber.h"

void MessageCallback(
    const std::shared_ptr<apollo::cyber::examples::proto::Chatter>& msg) {
  std::string str;
// print out the whole msg
  msg->SerializeToString(&str);
  AINFO << "msg: " << str;
}

int main(int argc, char* argv[]) {
  // init cyber framework
  apollo::cyber::Init(argv[0]);
  // create listener node
  auto listener_node = apollo::cyber::CreateNode("listener");
  // create listener
  auto listener =
      listener_node->CreateReader<apollo::cyber::examples::proto::Chatter>(
          "channel/chatter", MessageCallback);
  apollo::cyber::WaitForShutdown();
  return 0;
}
```
If you need CSV format, you can adjust the print format yourself

## IMU for example
```
#include "cyber/cyber.h"
#include "modules/localization/proto/imu.pb.h"

void MessageCallback(
    const std::shared_ptr<apollo::localization::CorrectedImu>& msg) {
  std::string str;
  msg->SerializeToString(&str);
  AINFO << str;
}

int main(int argc, char* argv[]) {
  // init cyber framework
  apollo::cyber::Init(argv[0]);
  // create listener node
  auto listener_node = apollo::cyber::CreateNode("listener");
  // create listener
  auto listener =
      listener_node->CreateReader<apollo::localization::CorrectedImu>(
          "/apollo/sensor/gnss/imu", MessageCallback);
  apollo::cyber::WaitForShutdown();
  return 0;
}
```
BUILD file
```
cc_binary(
    name = "listener",
    srcs = ["listener.cc"],
    deps = [
        "//cyber",
        "//modules/localization/proto:imu_proto",
    ],
)
```

**Comment by marcusvinicius178** [comment]
Hi Mr @daohu527  thanks for the suggestion.

I tried to execute the already implemented "Listener.cc" and Talker.cc" inside the folder apollo-50/cyber/examples.
I followed these steps: https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_API_for_Developers.md

However I got the errors:

![image](https://user-images.githubusercontent.com/43826438/127027295-75326d2b-eaa7-4af9-a30a-aa1080c23af2.png)

Then I tried to execute the same examples implemented in Python, inside the folder apollo5-0/cyber/python/examples:

And got the errors:

![image](https://user-images.githubusercontent.com/43826438/127027884-5bf80e19-92f9-4434-990c-9be6efbb1eae.png)

Then following the hints found here https://github.com/ApolloAuto/apollo/issues/13113 by @ForresterLu @storypku @Yimags 
and try to execute the .record files and .python files using the bazel // command:
I have repeated all the steps tutorial from here: https://github.com/ApolloAuto/apollo/tree/master/cyber/python

But got the error:

![image](https://user-images.githubusercontent.com/43826438/127029622-f3c10e97-5541-42a7-8f64-93e57873b29b.png)

It seems that it is missing something into the BUILD file.

I still did not find a way to run the talker and the listener command properly...
Could you please provide me the right steps, command lines?

- Build
- Bazel run or python command ? (Both failed)
- ./bazel-bin ( Issue here because after Build the package, the folder where the code is does not appear after issue this command) 

I am using Apollo 5.0

Thanks in advance

**Comment by daohu527** [comment]
**Do only one thing at a time**!!! You need to compile c++ no python!!!

1. Replace the build code in
```
cyber\examples\BUILD
```

2. build the whole cyber module
```
./apollo.sh build_cyber // or you can use -h to see how to build cyber
```

**Comment by marcusvinicius178** [comment]
Hi Thanks for the suggestion!!! 
However I have used Python I am not that good in C++, switched back to Apollo 6.0 which provides to build Python Binary modules... But I will try later the steps above, I am interested to make that work in C++ too!

About the issue:
I have solved and provided the tutorial here on my branch in apollo forked repo, if someone be interested:
https://github.com/marcusvinicius178/apollo/tree/extract_chan_data/cyber/python/cyber_py3/channels_data_extraction

I am going to create the code to convert csv to DataFrame and afterwards plot the graphs....then I will update this branch soon.
