### ISSUE TITLE
Is that possible to transfer msg between dockers on the same machine by shm?

### ISSUE THREAD

**Issue by BobDLA** [ApolloAuto/apollo#13951]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:  ubuntu 16.04
- **Apollo installed from (source or binary)**:  commit(9120b75d4acd5ad4673eb59ede1657ec8ea82804) almost latest
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
 Start with the talker and listener examples. And they are working good when in the same docker with shm.
But when I seperate the two program in two docker. Listner can't get message any more.
Here is piece of logs. 

talker
I0719 15:12:34.758060 24388 participant.cc:121] [talker][DEBUG] cyber ip: 192.168.1.161
I0719 15:12:34.760936 24388 notifier_factory.cc:40] [talker][DEBUG] notifier type: condition
I0719 15:12:34.760948 24388 condition_notifier.cc:34] [talker][DEBUG] condition notifier key: 360705043
I0719 15:12:34.760952 24388 condition_notifier.cc:126] [talker][DEBUG] shm already exist, open only.
I0719 15:12:34.760962 24388 condition_notifier.cc:184] [talker][DEBUG] open true.
I0719 15:12:34.760967 24388 condition_notifier.cc:43] [talker][DEBUG] next_seq: 50
I0719 15:12:34.760982 24388 notifier_factory.cc:40] [talker][DEBUG] notifier type: condition
I0719 15:12:34.761096 24388 rtps_transmitter.h:102] [talker][DEBUG] not enable.
I0719 15:12:34.761103 24388 intra_transmitter.h:80] [talker][DEBUG] not enable.
I0719 15:12:34.761108 24388 shm_transmitter.h:103] [talker][DEBUG] not enable.
I0719 15:12:34.761113 24388 talker.cc:43] [talker]talker sent a message! No. 0
I0719 15:12:34.967481 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:35.174782 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:35.382293 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:35.589768 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:35.761191 24388 rtps_transmitter.h:102] [talker][DEBUG] not enable.
I0719 15:12:35.761215 24388 intra_transmitter.h:80] [talker][DEBUG] not enable.
I0719 15:12:35.761224 24388 shm_transmitter.h:103] [talker][DEBUG] not enable.
...............
I0719 15:12:57.761297 24388 shm_transmitter.h:133] [talker][DEBUG] Writing sharedmem message: channel/chatter to block: 0
I0719 15:12:57.761307 24388 talker.cc:43] [talker]talker sent a message! No. 23
I0719 15:12:57.968267 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:58.176523 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:58.383553 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:58.590566 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:58.761152 24388 rtps_transmitter.h:102] [talker][DEBUG] not enable.
I0719 15:12:58.761168 24388 intra_transmitter.h:80] [talker][DEBUG] not enable.
I0719 15:12:58.761178 24388 shm_transmitter.h:114] [talker][DEBUG] block index: 1
I0719 15:12:58.761221 24388 shm_transmitter.h:133] [talker][DEBUG] Writing sharedmem message: channel/chatter to block: 1
I0719 15:12:58.761226 24388 talker.cc:43] [talker]talker sent a message! No. 24
I0719 15:12:58.967343 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:59.174103 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:59.381358 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:59.588680 24412 shm_dispatcher.cc:106] [talker][DEBUG] listen failed.
I0719 15:12:59.761165 24388 rtps_transmitter.h:102] [talker][DEBUG] not enable.
I0719 15:12:59.761184 24388 intra_transmitter.h:80] [talker][DEBUG] not enable.
I0719 15:12:59.761193 24388 shm_transmitter.h:114] [talker][DEBUG] block index: 2

Listener
I0719 15:12:57.661450 24425 participant.cc:121] [listener][DEBUG] cyber ip: 192.168.1.161
I0719 15:12:57.664635 24425 scheduler.cc:55] [listener]create croutine: listener_channel/chatter
I0719 15:12:57.664655 24425 notifier_factory.cc:40] [listener][DEBUG] notifier type: condition
I0719 15:12:57.664661 24425 condition_notifier.cc:34] [listener][DEBUG] condition notifier key: 360705043
I0719 15:12:57.664667 24425 condition_notifier.cc:126] [listener][DEBUG] shm already exist, open only.
I0719 15:12:57.664680 24425 condition_notifier.cc:184] [listener][DEBUG] open true.
I0719 15:12:57.664686 24425 condition_notifier.cc:43] [listener][DEBUG] next_seq: 0
I0719 15:12:57.664705 24425 notifier_factory.cc:40] [listener][DEBUG] notifier type: condition
I0719 15:12:57.871004 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:57.874853 24447 dispatcher.h:135] [listener][DEBUG] new reader for channel:channel/chatter
I0719 15:12:57.874873 24447 segment_factory.cc:42] [listener][DEBUG] segment type: xsi
I0719 15:12:58.077986 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:58.287431 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:58.494613 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:58.702178 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:58.908249 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:59.115301 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:59.321903 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:59.529387 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:59.736400 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:12:59.943540 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:00.151196 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:00.358778 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:00.565693 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:00.772621 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:00.979806 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:01.187049 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:01.394140 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.
I0719 15:13:01.601145 24449 shm_dispatcher.cc:106] [listener][DEBUG] listen failed.

### Supporting materials (screenshots, command lines, code/script snippets):
Is that possible to transfer msg between dockers on the same machine by shm?

**Comment by daohu527** [comment]
This is caused by the cyber mechanism. If the node ip address is different, then they will use the network communication by default.

In theory, docker is used for isolation, and the socket method is more reasonable.

You can refer to the following implementation
https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/cyber/transport/receiver/hybrid_receiver.h#L291-L305

**Comment by BobDLA** [comment]
@daohu527 
I have set the same IP in the two docker cyber config file.  It should not caused by IP configure.
Another configure I changed  is the shm_type, but even after I change it from  xsi to posix, msg still can't get from the listener docker.
Seems, the cyber implement condition method by xsi which can't cross docker, and it caused the issue.

**Comment by daohu527** [comment]
I'm not sure, does docker support containers with 2 host mode?

Container technology is used for isolation, I am not sure if the operating system has other restrictions

**Comment by BobDLA** [comment]
The default apollo docker command already set "--net=host" that means no network isolation between the container to host.
refer to https://docs.docker.com/search/?q=run

**Comment by daohu527** [comment]
yes, one docker is host mode is ok, but I'm doubt about two. Will there be a port conflict?

**Comment by kangleorc** [comment]
如果本地订阅和远端都订阅 A topic，当本地发布A topic的时候，会不会 shm 发送一次给本地的订阅，rtps同时发送给远端和本地，这样 同一个消息 本发送了两次给本地。

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
