### ISSUE TITLE
When I run "./apollo.sh build ",    get the error report from terminal in  ubuntu18.04 "Error :An error occurred during the fetch of repository 'six'" (I 'm in China)

### ISSUE THREAD

**Issue by luogyu7** [ApolloAuto/apollo#13952]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
When I run the command ”./apollo.sh build “  in docker   ,the  terminal  report the error about six repository:

**Error :An error occurred during the fetch of repository 'six'**

I install the apollo software  with the Tutorial :https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md 
### Supporting materials (screenshots, command lines, code/script snippets):
the screenshots of terminal as follow:
![1](https://user-images.githubusercontent.com/67385330/126119871-af61a991-44c3-4645-8b82-59ddf83a1d37.png)

What I have tried as follow:
1. many times exit docker and enter  'in-dev-docker' docker;
2. delete the bazel file in /apollo/.cache ,and rebuild with command "./apollo.sh build", and the errors  persist.
3. reboot the ubuntu operating system .
4. set network to  over the wall(I am in China ).    I use the over the wall productions are expressvpn and  astrill.  They can visit the external network independently (such as www.google.com ,https://en.wikipedia.org/, https://youtube.com   and so on. ) 

BUT , It doesn't work for the build system and report the errors as the picture.
main errors are :

![2](https://user-images.githubusercontent.com/67385330/126121891-54b188b9-1bb9-4e50-a20b-2bf560183ea0.png)

SO,What's the problem I'm not aware of? 
Any experts could help me?
Thanks.

**Comment by luogyu7** [comment]
any expert meet this error?

**Comment by CycloneC** [comment]
I've met the question as you too,and i fix it by change the dns to 8.8.8.8 
    
you can also refer to https://blog.csdn.net/lgyuwt/article/details/119250815

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
