### ISSUE TITLE
Running Apollo modular testing with LGSVL sim does not work sometimes

### ISSUE THREAD

**Issue by krtt** [ApolloAuto/apollo#13953]
I'm a beginner with Apollo. I have read the Apollo documentation [here](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/dreamview_usage_table.md) and the Dreamview API [here](https://www.svlsimulator.com/docs/python-api/dreamview-api/). I have also read several issues in Apollo about some modules not running but none of them really helped me to find a solution.

I want to run Apollo modular testing with the (LG) SVL sim Python API custom test scenarios with our custom map and with our custom vehicle configuration. The end goal is to run everything from a script and have no manual interference (for example in Dreamview user interface). I created a simple SVL Python API test scenario script, for the start with the default Lincoln2017MKZ ego car and our own custom map. It worked and run fine with Apollo several times. Then, without any changes, it sometimes did not run correctly (the ego car did not start driving sometimes). And then, without any changes, it stopped working at all (ego did not start driving at all). I found seemingly 2 problems related to Apollo:

First problem. When it sometimes did not run, it appeared to be because of Apollo's Planning module. The planning module looks enabled but it gets somehow stuck and even while showing that it is enabled, it is actually not working properly. The only workaround for this was to manually turn the Planning module in Apollo Dreamview OFF and back ON. Then the car immediately started driving. Other attempts to restart Planning module did not work ([disabling it via api command](https://www.svlsimulator.com/docs/python-api/dreamview-api/#disable_module) and [enabling it again via api command](https://www.svlsimulator.com/docs/python-api/dreamview-api/#enable_module)). But the goal is to automate the test scenarios and there should be no manual interference.

Second problem. When it stopped working at all, it appeared to be because of all Apollo's modules. None of the modules are enabled any more eventhough I have not changed anything in how I run Apollo, how I run the sim, any assets, and anything in my python script.

What should I do to correctly launch the Apollo modules so they don't need any manual interference? And if they are unable to launch correctly once, how to restart them so the result is solid and works as expected?

### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

`
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-06-03-4ab8fc8d53
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
`

### Steps to reproduce the issue:
- Run Apollo docker container, go into the container, start bootstrap_lgsvl and bridge
- Run the SVL pre-built executable (download the [v2021.1.1 from SVL](https://github.com/lgsvl/simulator/releases))
- Start the SVL sim API Only mode from the browser
- Run the python script
- Observe the car driving / not driving in the simulator
- Observe the Apollo Dreamview
- (If you have not set up or used SVL Python API before, the quickstart guide is [here](https://www.svlsimulator.com/docs/python-api/python-api/).)

### Supporting materials (screenshots, command lines, code/script snippets):
 - Py script attached [test_0_cleanedshort.zip](https://github.com/ApolloAuto/apollo/files/6840195/test_0_cleanedshort.zip)
 - Our custom map files for Apollo attached 
[tartu_map_v2.zip](https://github.com/ApolloAuto/apollo/files/6840203/tartu_map_v2.zip)

**Comment by ntutangyun** [comment]
Basically when you manually turn the modules on in the Dreamview website. the website sends commands to the backend and the backend starts the module process.

If you want to automate this, you can create a websocket connection directly to Apollo's Dreamview's backend server. and send the similar commands, such as "setup all modules", "reset all modules", or turn on/off any particular modules you want.

**Comment by krtt** [comment]
Sorry if by beginner understanding is not fully there yet, but isn't it what the Dreamview API calls [enable_apollo](https://www.svlsimulator.com/docs/python-api/dreamview-api/#enable_apollo), [enable_module](https://www.svlsimulator.com/docs/python-api/dreamview-api/#enable_module), [disable_module](https://www.svlsimulator.com/docs/python-api/dreamview-api/#disable_module) are supposed to do?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
