### ISSUE TITLE
About Valet Parking Scenario Test（Dbug）

### ISSUE THREAD

**Issue by ghost** [ApolloAuto/apollo#13950]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:20.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- 
Problem Description: I'm testing the valet parking scenario, but I have some problems. 
1. I use LGSVL tool to draw the following HD map: 
![1111111111111](https://user-images.githubusercontent.com/23471410/126093210-dae4ec2a-ae38-408e-842c-3db7fd5b90f2.png)
2. I open all relevant modules and edit routing, as shown in the following figure: 
![777788888](https://user-images.githubusercontent.com/23471410/126111444-df53d013-6634-4630-9f16-1b6a3b44fb8b.png)
![22222222222222](https://user-images.githubusercontent.com/23471410/126093277-ce892ec6-e0e4-405d-8221-bc4b3e7c392f.png)
3. But the vehicle only stops at the "end of the red line", and does not working. After debugging the code, I found that there was something wrong with this Code: (/modules/planning/scenarios/park/valet_parking/valet_parking_scenario.cc,100~101lines)
![3333333333333](https://user-images.githubusercontent.com/23471410/126093381-f6567817-7e48-4cfb-b24a-0e8cf6dcce73.png)
"IF" the condition does not.
4. I guess it was a map related problem, but I don't know how to continue to look for it.And maybe routing module does not send parking information to Apollo.
5. My map structure is like this：
![999999999999](https://user-images.githubusercontent.com/23471410/126094004-b69faff1-e6ba-4969-bd26-b05a3c582ad1.png)
But I see some maps with default_ end_ way_ point.txt file：
![6666666666](https://user-images.githubusercontent.com/23471410/126094770-ca65c7a5-38cf-4f9a-99c1-9703b3e12e36.png)
I don't know if it has an impact, but I don't know how to generate it.
6. I checked my sim_map.txt file (this file is created by base_map.bin file), Parking information available:
![001](https://user-images.githubusercontent.com/23471410/126094738-1498b394-bcc7-4d2b-93b2-a26ecdcd2d14.png)
![002](https://user-images.githubusercontent.com/23471410/126094751-946ee01f-2631-4a3e-a1fb-225078ec1f47.png)
7.Routing：
![001](https://user-images.githubusercontent.com/23471410/126112021-224a1738-2e72-4d78-9b5a-de6845ade109.png)
![002](https://user-images.githubusercontent.com/23471410/126112025-f3942695-780f-448c-967a-9b7e45644cc7.png)

Finally, I don't know if there is any problem with my operation, or I need some extra work.I hope to get help from the community. Thank you very much！

**Comment by daohu527** [comment]
Can you send the map to my mail daohu527@gmail.com, I will test it then

**Comment by yufeilongyuan** [comment]
Mail to send to the mailbox provided, please have time to check, thank you. @daohu527

**Comment by daohu527** [comment]
The following are similar questions, so summarize
#13215 #13105 #13571 #13822

I finally tried your map and it succeeded in some cases

## Howto
1. modify the code in 
https://github.com/ApolloAuto/apollo/blob/ac8cb200899af38e1f510c518dc038421fc4c6a6/modules/tools/mock_routing/mock_routing_request.py#L48-L58

to 
```
    waypoint.pose.x = 315331.29302964138
    waypoint.pose.y = 5068397.6949539529
    waypoint.id = 'lane_0'
    waypoint.s = 0.87790916161304278

    waypoint = routing_request.waypoint.add()
    waypoint.pose.x = 315311.573527921
    waypoint.pose.y = 5068382.853662604
    waypoint.id = 'lane_0'
    waypoint.s = 24.884630810

    routing_request.parking_info.parking_space_id="PS_0"
```
2. enable sim_control
3. start routing and planning module
4. run the cmd `python modules/tools/mock_routing/mock_routing_request.py`, if above apollo 6.0, run `./bazel-bin/modules/tools/mock_routing/mock_routing_request`

Then the car will park in the parking lot. I found that the designated routing point **needs to be a little ahead of the parking space**, otherwise it will cause the parking lot to be impossible

## remain questions
1. routing in dreamview cannot found the parking lot, need to add the feature
2. routing outof the parking lot need to fixed, seems can't success find routing path
3. need to check the restriction conditions of the routing endpoint and parking plot

**Comment by yufeilongyuan** [comment]
Thank you very much for your prompt reply. I have realized the simulation of this problem on the computer, and there is no problem. But there is still a small question to ask, that is, I'm passing cyber_monitor tool looks at the punctuation information, only one waypoint [0] can be seen, and others can't be seen, but I have selected several points. Have you encountered this problem?
![78963](https://user-images.githubusercontent.com/23471410/126919550-bc39811f-cac8-4d9d-89bd-41e649e24727.png)

**Comment by daohu527** [comment]
this not a bug, you can use keyboard `n` to turn up and down the messages.

**Comment by daohu527** [comment]
## remain questions
1. routing in dreamview cannot found the parking lot, need to add the feature

## Solution
I finally checked, if you want to park, you should add the following information in the file `default_end_way_point.txt`, then the routing request will contain `parking_info`
```
landmark {
    name: "Route: parking space PS_0",
    parking_info {
        parking_space_id: "PS_0",
        parking_point {
            x: 315315.28
            y: 5068387.31
        }
    },
    waypoint {
      pose {
        x: 315331.44
        y: 5068397.49
      }
    }
    waypoint {
      pose {
        x: 315317.66
        y: 5068381.19
      }
    }
}
```

below is a example for send `Default Routing`
![Snipaste_2021-07-26_11-39-31](https://user-images.githubusercontent.com/10419854/126930003-bba4869c-8f80-4ff7-8cbb-2d4560501dce.png)

**Comment by yufeilongyuan** [comment]
OK, thank you very much. I will test it as soon as possible. If there are results, send them up as soon as possible to let more people know.

**Comment by yufeilongyuan** [comment]
I tested successfully in apollo-r6.0.0, but version 5.5.0 failed. I don't know why. Tried several times, but failed. Do you know why? Which version of code are you testing? thank you @daohu527

**Comment by daohu527** [comment]
I was tested with 6.0, need to check the code why 5.5 not work!

**Comment by jaycc666** [comment]
Hello, I am currently a graduate student who is very interested in  path planning, but it is always difficult to do something at the beginning. So I hope someone can help me if you want to, please contact me at 598351944 ，this is my q q .i am in Chengdu
