### ISSUE TITLE
aarch64/lib/liblocalization_msf.so : input file(s) do not exist

### ISSUE THREAD

**Issue by AMEKNI** [ApolloAuto/apollo#13969]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- ** during apollo building of master branch, i had that error " /apollo/third_party/localization_msf/BUILD:8:11: //third_party/localization_msf:localization_msf: missing input file '//third_party/localization_msf:aarch64/lib/liblocalization_msf.so'
(10:28:28) ERROR: /apollo/third_party/localization_msf/BUILD:8:11 1 input file(s) do not exist" 
_** I can't find aarch64 folder in localization_msf???? 
Some one can help me thank you!!!!!!!!!!!!!!

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/87365572/126779023-afda224b-a2f2-40c5-92c7-ef633251dc5f.png)

**Comment by AMEKNI** [comment]
Some one can help me thank you!!!!!!!!!!!!!!

**Comment by yufeilongyuan** [comment]
This package does not implement the code or dynamic library of aarch64 architecture. If it is not necessary, please use version 6.0.0.

**Comment by AMEKNI** [comment]
Hi again, I need this library to build localization module (liblocalization_msf.so)

**Comment by yufeilongyuan** [comment]
This is a third-party code library, which may not be necessary. For you, you can delete this library without compiling, so as to eliminate this error. For the function of location service, use the official one. A third-party code library is convenient for you to realize functions, but it is not necessary. But I guess the official source code should be available, but it hasn't been released for some reasons. I hope it can help you.

**Comment by AMEKNI** [comment]
sorry but MY PROBLEM : i can't find this library, so how can I delete it? should i change the BUILD file?

**Comment by yufeilongyuan** [comment]
Yes, remove aarch64 related compilation options.

**Comment by AMEKNI** [comment]
hi, thank you, but I have an another error  related to library (libmsf_localization_component.so), do have any idea about that?
![image](https://user-images.githubusercontent.com/87365572/128201054-f20e5ab3-8c36-4d14-ab26-4edc2762d8e1.png)

**Comment by yufeilongyuan** [comment]
I suggest you change the 6.0.0 code. I told you at the beginning, but you stick to the "master" version. Version 6.0.0. that does not have this library and still works well.
