### ISSUE TITLE
cc1plus: some warnings being treated as errors after adding new vehicle 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#13967]
Ubuntu 20.04 
Apollo 5.0 
I added a new vehicle and used the adaptation tool. I try to rebuild after configuring the other files and I get this error. I changed the werror file but it gives me the same issue. 
![Screenshot from 2021-07-22 10-44-08](https://user-images.githubusercontent.com/58639429/126684741-6bf384e6-c4fb-4fd5-bf1d-fc3bdd334948.png)
Honda is the new vehicle I added. Just need to get past warning so it can build

**Comment by daohu527** [comment]
The error message is clear. You should check if you forgot the return type.

> This warning is similar to the warning described in Return with no value. If control reaches the end of a function and no return is encountered, GCC assumes a return with no return value. However, for this, the function requires a return value. At the end of the function, add a return statement that returns a suitable return value, even if control never reaches there.

**Comment by jp12AI** [comment]
> The error message is clear. You should check if you forgot the return type.
> 
> > This warning is similar to the warning described in Return with no value. If control reaches the end of a function and no return is encountered, GCC assumes a return with no return value. However, for this, the function requires a return value. At the end of the function, add a return statement that returns a suitable return value, even if control never reaches there.

Yes, I already fixed this issue. It wasn't the return function. I had to uncomment some tings. Can you please tell me what channel_id for canbus is? I'm using a usb can adapter. Does that show where the device port is on? What does channel_id mean? I know this is off topic but help on this would be greatly appreciated. Thank you. My device is on /dev/bus/usb/002.

**Comment by daohu527** [comment]
As you say this is off topic, We need to keep the issue tidy and focused.

I check the code, for now apollo does not support USB card, you need the driver of usb canbus. currently only supports pci card, socket card.

Because I have never used a usb card, I suggest you debug the relevant driver in `modules\drivers\canbus`

**Comment by jp12AI** [comment]
> As you say this is off topic, We need to keep the issue tidy and focused.
> 
> I check the code, for now apollo does not support USB card, you need the driver of usb canbus. currently only supports pci card, socket card.
> 
> Because I have never used a usb card, I suggest you debug the relevant driver in `modules\drivers\canbus`

It seems that usb connection can be used. #4935. I just need to know what channel_id is. How can apollo tell which port the device is on? My device is on /dev/bus/usb/002. Is that channel_id? What is channel_id? Thank you

**Comment by daohu527** [comment]
This type is not useful, at least it is not used in the code, if you think it is possible, you can try it

**Comment by jp12AI** [comment]
> This type is not useful, at least it is not used in the code, if you think it is possible, you can try it

@daohu527 https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/canbus/proto/can_card_parameter.proto (In line 15). Does this mean it can use usb card? Where do I change the drivers to my usb adapter driver? Which file? I get this error in dreamview: 
![Screenshot from 2021-07-23 20-32-19](https://user-images.githubusercontent.com/58639429/126876636-8c9f18ff-b002-41a8-92c2-7e619867fa09.png)
Are you in the apollo wechat?
