### ISSUE TITLE
How to create a writer for the /apollo/cotrol channel to achieve remote control

### ISSUE THREAD

**Issue by Czl0223** [ApolloAuto/apollo#13974]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I am using apollo6.0 and SVL for co-simulation. I currently want to try remote control. I plan to use the writer to directly send corresponding control commands to the /apollo/control channel, and then receive the corresponding control commands in SVL. What should I do?

**Comment by alexiskovi** [comment]
Hi, @Czl0223. Please see the examples in [cyber docs](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_API_for_Developers.md#Talker-Listener), especially how to create a talker in Cyber RT.  To send control message you must include control_cmd proto like [here](https://github.com/ApolloAuto/apollo/blob/fc7facf7de2e294f59dfc0aa32a36e8c48c423af/modules/control/control_component.h#L28). SVL will automatically see your messages through bridge, if you will send them to /apollo/control.
Also you can see simple python [example](https://github.com/ApolloAuto/apollo/blob/r6.0.0/modules/tools/vehicle_calibration/data_collector.py), where writer (talker) are created for sending simple control commands for calibration process.

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
