### ISSUE TITLE
How to load the environment dataset with  ApolloScape ?

### ISSUE THREAD

**Issue by luogyu7** [ApolloAuto/apollo#13975]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 180.4
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0 
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- Recently I can run the demo_3.5.record file on  Apollo software. But I want to set up with environment dataset. I found the dataset ApolloScape http://apolloscape.auto/.   how did I operate the  Apollo to load the dataset .
- and except that could I run the Apollo platform without demo_3.5.record?
- could any expert give me some suggestion?
- Thanks. 

### Supporting materials (screenshots, command lines, code/script snippets):

Currently I could run the demo_3.5.record file. But I want to run the Apollo completely without demo_3.5.record. Is there any suggestion to realize this point? 
![4](https://user-images.githubusercontent.com/67385330/126963821-48472c53-147f-4c37-90aa-c30b4beb1693.png)

**Comment by daohu527** [comment]
@luogyu7 It doesn't seem to work at the moment, apollo relies on the record package to run. We will try to fix the offline process, but importing datasets may not be supported yet
