### ISSUE TITLE
How can I see lane detection from a camera in SVL

### ISSUE THREAD

**Issue by rzr900ipl** [ApolloAuto/apollo#13976]
Hi, I'm trying to see lane detection from a camera in SVL simulator, and I trying to do as is specified in this [document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md).

First I create a record file from de SVL. Next I do point 1,2,3,4,5,6,7. In the point 8, I chose "If you want to test lane detection alone use" using the command mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.dag. To see the lane results, I mark enable_visualization: true in modules/perception/production/conf/perception/camera/lane_detection_component.config before executing the point 1 form the document. I play de recorded file from SVL using cyber_record play -f and I got this erros:

![Screenshot_2021-07-26_16-25-18](https://user-images.githubusercontent.com/78313843/127015498-9fa62b6c-da4c-4634-ad95-993fc76f5043.png)

How can I fix that? Thank you

**Comment by tandf** [comment]
@rzr900ipl 
In the top-left window, the static transform component cannot find yaml files. You can try to choose the vehicle model in dreamviewer, and Apollo should copy the yaml files of that vehicle to the directory needed.

**Comment by rzr900ipl** [comment]
@tandf 
Thank you for you answer. I did what you said, but the results were the same.
![Screenshot_2021-08-24_10-57-45](https://user-images.githubusercontent.com/78313843/130597707-e3ef234a-bbcd-414a-84fb-a443925f1fe6.png)

I'm using Apollo 6.0

**Comment by rzr900ipl** [comment]
I found that in the folder [/apollo/modules/drivers/lidar/velodyne/params/](https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/lidar/velodyne/params/) don't exist the folders that static transform said. Is that normal?

**Comment by tandf** [comment]
@rzr900ipl  Sorry I can't help. I tried [lgsvl's apollo 5](https://github.com/lgsvl/apollo-5.0) and it worked fine.

**Comment by rzr900ipl** [comment]
@tandf
I will instal [LGSVL's Apollo 5](https://github.com/lgsvl/apollo-5.0). So you can tell me set by set, since the record until the visualization, for I try to do it and see if it works. I appreciate if you are specific for I don't miss nothing or do any mistake

**Comment by rzr900ipl** [comment]
@tandf
But you used a cyber record, or with LGSVl in real time? Iam asking that because de LGSVL need a lot of GPU memorie, and the perception module need it as well.

**Comment by tandf** [comment]
I did both. I have two laptops both with lousy GPU, and I ran LGSVL and Apollo on each one. It's also viable to record the LGSVL output first and play it later with Apollo running. Or craft and send cyber messages while running Apollo. You can try and choose one that suits you the best.

**Comment by rzr900ipl** [comment]
@tandf 
When you say "craft and send cyber messages while running Apollo", is to use `cyber_recorder record -a`? 
I try to use `cyber_recorder record -a` and the run it like in said in this [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)
and a got an erro for` cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch`
![Self](https://user-images.githubusercontent.com/78313843/131217695-5215b718-d67a-4dea-9a95-bd4547722460.png)

An the modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt folder are lake this
`camera_names: "front_6mm,front_12mm"`
`input_camera_channel_names : "/apollo/sensor/camera/front_6mm/image,/apollo/sensor/camera/front_12mm/image"`
`timestamp_offset : 0.0`
`camera_obstacle_perception_conf_dir : "/apollo/modules/perception/production/conf/perception/camera"`
`camera_obstacle_perception_conf_file : "obstacle.pt"`
`frame_capacity : 20`
`image_channel_num : 3`
`enable_undistortion : false`
`enable_visualization : true`
`output_final_obstacles : true`
`output_obstacles_channel_name : "/perception/obstacles"`
`camera_perception_viz_message_channel_name : "/perception/inner/camera_viz_msg"`
`prefused_channel_name : "/perception/inner/PrefusedObjects"`
`default_camera_pitch : 0.0`
`default_camera_height : 1.5`
`lane_calibration_working_sensor_name : "front_6mm"`
`calibrator_method : "LaneLineCalibrator"`
`calib_service_name : "OnlineCalibrationService"`
`run_calib_service : false`
`output_camera_debug_msg : false`
`camera_debug_channel_name : "/perception/camera_debug"`
`ts_diff : 0.1`
`visual_debug_folder : "/apollo/debug_output"`
`visual_camera : "front_6mm"`
`write_visual_img : true`
`enable_cipv: true`

when i run `mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.dag` i got 
![Self_2](https://user-images.githubusercontent.com/78313843/131217778-7c50d5c3-3ca1-478f-be17-b9ace6f0e025.png)

and the modules/perception/production/conf/perception/camera/lane_detection_component.config folder are like this
`camera_names: "front_6mm,front_12mm"`
`input_camera_channel_names : "/apollo/sensor/camera/front_6mm/image,/apollo/sensor/camera/front_12mm/image"`
`timestamp_offset : 0.0`
`camera_lane_perception_conf_dir : "/apollo/modules/perception/production/conf/perception/camera"`
`camera_lane_perception_conf_file : "lane.pt"`
`frame_capacity : 20`
`image_channel_num : 3`
`enable_undistortion : false`
`enable_visualization : true`
`output_lanes_channel_name : "/perception/lanes"`
`default_camera_pitch : 0.0`
`default_camera_height : 1.5`
`lane_calibration_working_sensor_name : "front_6mm"`
`calibrator_method : "LaneLineCalibrator"`
`calib_service_name : "OnlineCalibrationService"`
`run_calib_service : false`
`ts_diff : 0.1`
`visual_debug_folder : "/apollo/debug_output"`
`visual_camera : "front_6mm"`
`write_visual_img : true`

I have already do the `export NVBLAS_CONFIG_FILE=/usr/local/cuda` and `./apollo.sh build_opt_gpu` again before do the `cyber_recorder play `

**Comment by tandf** [comment]
> When you say "craft and send cyber messages while running Apollo", is to use cyber_recorder record -a?

I mean using a python script to craft messages based on the lane images.

Sorry, I'm not familiar with the cudnn error...

**Comment by rzr900ipl** [comment]
> > Quando você diz "criar e enviar mensagens cibernéticas enquanto executa o Apollo", é usar cyber_recorder record -a?
> 
> Quero dizer, usar um script Python para criar mensagens com base nas imagens da pista.

@tandf
Sorry for the question, but who I do it? I think I only need to create run lgsvl, run the bridge and run this [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)

**Comment by rzr900ipl** [comment]
@daohu527

**Comment by tandf** [comment]
@rzr900ipl  I mean you can either generate data from lgsvl, or craft your own data. You won't need a python script if you're using lgsvl.

**Comment by rzr900ipl** [comment]
@tandf
Right, but how do i record the cyber messages? I do it with cyber_recorded, is it right?
You can't remember anything that is needed to do for it work, because I see that perception module of Apollo 5.0 only works with a GTX-1080 GPU, but you did it with a GTX950m.

**Comment by tandf** [comment]
Yes you can use cyber_recorder.
I do know that it's suggested to run Apollo 5.0 with at least 1080, but I just don't have one, so I did it with my 950m. Yes it's painful, but it worked.

**Comment by rzr900ipl** [comment]
@tandf
I think I don have cudnn installed. Is it necessarie?

**Comment by tandf** [comment]
I guess you need cudnn. Please refer to Apollo's doc. I used cyber bridge.

**Comment by rzr900ipl** [comment]
@tandf
In this [doc](https://www.svlsimulator.com/docs/archive/2020.06/apollo5-0-instructions/#prerequisites) says that "The current version of Apollo does not support Volta and Turing architectures", in this case version 5.0, and mine GTX1650 ti have a Turing architecture. However, your GTX950m have a Maxwell architecture, so that is the reason that you can see the results.
Apollo 6.0, I think the perception camera don't work or don't show the results, in this case lane detection. Am I right?
What do you think? Is this the problem?

**Comment by tandf** [comment]
@rzr900ipl 
> In this doc says that "The current version of Apollo does not support Volta and Turing architectures", in this case version 5.0, and mine GTX1650 ti have a Turing architecture. However, your GTX950m have a Maxwell architecture, so that is the reason that you could see the results.

I didn't know that. Thanks for the information.

> Apollo 6.0, I think the perception camera don't work or don't show the results, in this case lane detection. Am I right?
What do you think? Is this the problem?

What do you? I guess your translation tool is not working correctly and I cannot get it...

**Comment by rzr900ipl** [comment]
> What do you? I guess your translation tool is not working correctly and I cannot get it...

I said that in Apollo 6.0 perception camera don't work

I used another computer with a GTX1050 with Apollo 5.0 and it works
Thank you for the help
Closing the issue
