### ISSUE TITLE
Build fails in docker

### ISSUE THREAD

**Issue by badd0ge** [ApolloAuto/apollo#1398]
When I execute dev_start.sh, I get a bunch of 'chown: changing ownership of '/apollo/modules': Operation not permitted' type of messages

If I then try to build inside the image:

@in_dev_docker:/apollo$ ./apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
WARNING: Output base '/home/pmurthy/.cache/bazel/_bazel_pmurthy/540135163923dd7d5820f3ee4b306b32' is on NFS. This may lead to surprising failures and undetermined behavior.
...........
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
WARNING: Output base '/home/pmurthy/.cache/bazel/_bazel_pmurthy/540135163923dd7d5820f3ee4b306b32' is on NFS. This may lead to surprising failures and undetermined behavior.
ERROR: /apollo/modules/third_party_perception/common/BUILD:31:1: no such package '@google_styleguide//': Error cloning repository: https://github.com/google/styleguide.git: cannot open git-upload-pack caused by https://github.com/google/styleguide.git: cannot open git-upload-pack caused by github.com and referenced by '//modules/third_party_perception/common:third_party_perception_gflags_cpplint'
ERROR: Analysis of target '//modules/third_party_perception/common:third_party_perception_gflags_cpplint' failed; build aborted
INFO: Elapsed time: 1.454s
FAILED: Build did NOT complete successfully (5 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 12 seconds
============================

**Comment by yiakwy** [comment]
You can check out new docker image published yesterday!

**Comment by badd0ge** [comment]
Thanks.  I get the following issue:

root@in_dev_docker:/apollo# bash ./apollo.sh build
System check passed. Build continue ...
./apollo.sh: line 61: WORKSPACE: Permission denied
sed: couldn't open temporary file ./sedEQBwxP: Permission denied
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Error: mkdir('/root/.cache/bazel/_bazel_root'): (error: 13): Permission denied
============================
[ERROR] Build failed!
[INFO] Took 0 seconds
============================
root@in_dev_docker:/apollo#

I ran dev_start.sh and dev_into.sh as sudo.  If I don't do it as sudo but do dev_start.sh and dev_into.sh as myself, I get a bunch of messages like

chown: changing ownership of '/apollo/modules/tools/planning_traj_plot/main.py': Operation not permitted
 for everything

How can I solve this issue?  Where/which permission is it looking for?

Thanks

**Comment by badd0ge** [comment]
BTW, I can run docker without sudo. I don't need sudo to run docker

**Comment by xiaoxq** [comment]
Please follow the official docker installation guide as well as the "post installation steps" to avoid using "sudo" with docker. It would be risky.
