### ISSUE TITLE
How to transform the orignal sensor data such as .jpg, .pcd and IMU data into .record format which can cyber_record play in Apollo.

### ISSUE THREAD

**Issue by RedBlack888** [ApolloAuto/apollo#13989]
Dear, 
How to transform the orignal sensor data such as .jpg .pcd and IMU data into .record format which can cyber_record play in Apollo.
We want to run apollo on local computer, however we are lack of the measured data. Thanks for apollo opendataset (https://apollo.auto/daoxianglake_cn.html), we can download the raw sensor data which contains gt_pose_data, image_data, imu_data, params and pcd_data. Apollo support to transform rosbag file into record format by  rosbag_to_record. Does Apollo support transform the original data into record, if not, how to use the original data to run on local computer?

Best

**Comment by daohu527** [comment]
You can use 2 api interfaces to achieve this function, the `RecordWriter` c++ version  or [cyber_record](https://github.com/daohu527/cyber_record) python version
