### ISSUE TITLE
Error while run Apollo_5.0? docker/scripts/dev_start.sh: line 335: type: nvidia-docker: not found

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#13995]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0 && 5.5
- **Output of `apollo.sh config` if on `master` branch**: 

### Steps to reproduce the issue:
https://www.svlsimulator.com/docs/archive/2020.06/apollo5-0-instructions/

1. docker pull lgsvl/apollo-5.0
2. git clone --recurse-submodules https://github.com/lgsvl/apollo-5.0.git
3. ./docker/scripts/dev_start.sh

### Supporting materials (screenshots, command lines, code/script snippets):
Before i was working on Apollo_5.5 but it is not compatible with LGSVL simulator so I am trying to run Apollo_5.0 on the same PC. can we run Apollo5.0 and Apollo5.5 on same PC? 

**Apollo_5.5 works fine but Apollo_5.0 gives an error.** 

**OUTPUT Apollo_5.0:**
docker/scripts/dev_start.sh: line 335: type: nvidia-docker: not found

Error response from daemon: Container 3b75262142b5493f95d8d5aa7d03cdfb6d136feb418ab2750e1dc1ec312b188d is not running

![Screenshot from 2021-07-29 10-35-28](https://user-images.githubusercontent.com/61130487/127438834-e653ae50-0de6-412a-a3b4-e21f3bf89931.png)

**OUTPUT Apollo_5.5:**
![Screenshot from 2021-07-29 10-43-41](https://user-images.githubusercontent.com/61130487/127438768-5d3209e2-89fd-46ff-8a66-dc3e71209ce6.png)

**Comment by roshambo919** [comment]
I received the same error initially on Apollo 5.0 (I didn't try 5.5). As I saw in the console text (and you have the same), "type: nvidia-docker" not found. You did not state an install of nvidia-docker in your steps, so maybe this will fix it. 

1. Install nvidia-docker, as stated in https://www.svlsimulator.com/docs/archive/2020.06/apollo5-0-instructions/#setup

Note that you still have to install nvidia-docker even if your `nvidia-smi` call works which is what I missed on a quick skim of the instructions the first go-around.

![image](https://user-images.githubusercontent.com/20426598/131363790-950f6329-879b-4b2b-abfb-b4923792229a.png)


2. Even after doing this, I received an nvidia-runtime error. I fixed that by reinstalling nvidia-container-runtime.

![image](https://user-images.githubusercontent.com/20426598/131364397-6621920b-360a-4ec1-9100-c9a7301dceea.png)


See:
https://forums.developer.nvidia.com/t/docker-container-nvidia-l4t-ml-wont-run/146534/12

**Comment by Addi2020** [comment]
@roshambo919  thanks. I did the same to install nvidia drivers. It works fine.
But now I use Apollo_6.0 and every time when I go inside Docker, I need to install Nvidia drivers otherwise it gives error . Why every time I need to install nvidia again and again.
