### ISSUE TITLE
Is it normal ?   Thare are two vehicles  in the pull-down  list.    

### ISSUE THREAD

**Issue by luogyu7** [ApolloAuto/apollo#13997]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

why  the vehicle  pull-down list   show  just two vehicles ? just following picture :
![1](https://user-images.githubusercontent.com/67385330/127628827-b8b2cc09-f5a1-4194-915f-160b5d7c7573.png)
I pull the source code from :
the pull address:   https://github.com/ApolloAuto/apollo.git

I excute commands as follows step by step:

1.bash docker/scripts/dev_start.sh
2.bash docker/scripts/dev_into.sh
3. ./apollo.sh build
4. bash scripts/bootstrap.sh
5. input the address to the address bar with  'localhost:8888'

The question is :  Thare are just two vehicles in the pull-down list.
Is it normal ?
![1](https://user-images.githubusercontent.com/67385330/127629569-fedd34fa-dd0a-4171-86dd-ac3dfa99dae4.png)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:     - **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:   6.0
- **Output of `apollo.sh config` if on `master` branch**: 

1. bash scripts/bootstrap.sh

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
![1](https://user-images.githubusercontent.com/67385330/127629641-6324c599-0a27-4ad5-9432-c04722cd456b.png)

**Comment by daohu527** [comment]
Yes, you can select the car in the drop down box, which corresponds to different vehicle configurations
