### ISSUE TITLE
Apollo (5.0, 5.5, 6.0, master) and SVL simulator

### ISSUE THREAD

**Issue by tajinder96** [ApolloAuto/apollo#13999]
Hi, 

I wanted to ask a question about working with Apollo and Lgsvl. 

Do you know if recording simulator data using the bridge in Apollo master as CyberRT messages and then replaying the data to run open-loop simulation with Apollo 5.5 / Apollo 5.0 will work well? I want to work with camera-based object detection in Apollo.

Also looking at previous issues, it seems that building two different versions of Apollo on the same computer may cause issues. Could someone please confirm that? 

Thanks a lot!

**Comment by rzr900ipl** [comment]
@tajinder96 
Hi
Did you see the object detection or lane detection from the camera in LGSVL working with the perception module?  I am asking that because I run what is said in this [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) and I don't work

Thank you

**Comment by tajinder96** [comment]
Hey @rzr900ipl,

Which version of Apollo are you using? 

I could not get it to work with v5.5 (v6.0 does not have camera perception as far as i understand). 
However, it works with Apollo-master using the SMOKE camera object detection pipeline. I only checked the object detection, not lane detection. The camera object detection output is not stable for me though unfortunately. 

Hope that helps you!

**Comment by styj5** [comment]
> 

Hi, when you ran such replay simulation, did Apollo react totally the same? I met some issues when trying to reproduce some cases but the **_apollo performs differently_** in each run even **_all the other settings in the environment keeps the same*_*.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
