### ISSUE TITLE
what is full name of rsu?

### ISSUE THREAD

**Issue by amelia278** [ApolloAuto/apollo#14006]
what does map_rsu.proto define, what is full name of rsu
thx

**Comment by daohu527** [comment]
It is used for V2X communication, the full name is roadside units (RSUs).

The device paired with it is in the car, called platform for onboard (OBUs)

```
(road side)RSU <-> OBU(car side)
```

**Comment by amelia278** [comment]
> It is used for V2X communication, the full name is roadside units (RSUs).
> 
> The device paired with it is in the car, called platform for onboard (OBUs)
> 
> ```
> (road side)RSU <-> OBU(car side)
> ```

thanks
