### ISSUE TITLE
Error launch rtk_localization

### ISSUE THREAD

**Issue by AMEKNI** [ApolloAuto/apollo#14007]
### System information

- **OS Platform and Distribution :18.04
- **Apollo installed from : source
- **Apollo version *: master

### Steps to reproduce the issue:
- in order to launch rtk localization module I did:
bazel build //modules/localization/rtk/...
cyber_launch start /apollo/modules/localization/launch/localization.launch

- the build completed successfully but for launch It stays at this level and nothing happens afterwards. Some have any idea ?

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/87365572/128151756-91c56cf2-8cb1-41b3-84c0-a8c9fa16f933.png)

**Comment by daohu527** [comment]
It looks like there is no error, you can try the next step!

**Comment by AMEKNI** [comment]
Hi, i can't do the next step without pressing ctrl+c , this step is not completed

**Comment by daohu527** [comment]
Yes, it's a while loop, you can use dreamview to start the mode which will run in the backend.

**Comment by AMEKNI** [comment]
sorry I can do these steps inside Apollo Docker container OR It should be done inside Cyber Docker container

**Comment by AMEKNI** [comment]
> Yes, it's a while loop, you can use dreamview to start the mode which will run in the backend.

a while loop, so it will never stop. sorry how can i continue the other steps?

**Comment by daohu527** [comment]
open a new shell windows and do the same steps as before

**Comment by AMEKNI** [comment]
Hi, I did that and left it 1 hour, but nothing is changed.  Do you have any idea why it still there?
![image](https://user-images.githubusercontent.com/87365572/128342322-68fc7c0e-c5e6-44e4-b9be-ae64eaf6cbd4.png)

**Comment by daohu527** [comment]
I mean open a new shell windows and do the same steps as before to enter the docker **not run the command.**

by the way, what do you want to happen? run a while and give you some result print out? In fact, the localization module will always work, because localization is always required during the automatic driving process.

Its output is topic, and it uses a **publish and subscribe system**. I think you should search for relevant information to understand it.

Hope this helps you!

**Comment by AMEKNI** [comment]
Thank you very much, yes now I could understand you.
I documented myself on the publish and subscribe system. But, for my case, i want to start by studying the localization module separately from the other modules. ie testing the localization module with different inputs without having to test the other modules (planning, ect ...). So I can't do this?

**Comment by daohu527** [comment]
Of course you can, all you need is a printed result, so I think you still don’t know the input and output of the module.

The localization module accepts GPS, IMU, etc. information, and the output is the current position (UTM coordinates) both by topics. If you want to run it. Then you need the relevant input, and then look at the relevant output

You can view the information of these channels through cyber_monitor
