### ISSUE TITLE
Perception modules won't stay on

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#14004]
Apollo: 5.0
System: 20.04 
I am in navigation mode but the perception module won't stay on. Do I need to have all the cameras connected for perception module to work? I currently on have one camera connected. I looked in cyber_monitor and the perception module isn't active. I also checked the logs. Any suggestions? Thank you. Do I need the other cameras connected? Do I need to be in a specific mode? 
![Screenshot from 2021-08-02 20-19-29](https://user-images.githubusercontent.com/58639429/127952671-cc2e12cf-6d1d-40c3-b65c-19db51ec30b9.png)

**Comment by jp12AI** [comment]
![Screenshot from 2021-08-02 22-03-36](https://user-images.githubusercontent.com/58639429/127960672-456f5386-3eac-4bf6-a83b-6725165e7ffc.png)

**Comment by jp12AI** [comment]
Issue is solved. I had to install dependencies and then rebuild docker image

**Comment by rzr900ipl** [comment]
@jp12AI 
What dependencies do you installed? 
Thank you
