### ISSUE TITLE
Perception module won't stay on 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#14009]
Apollo version: 5.0 
Apollo Mode: Navigation 
Ubuntu version: 20.04 
I'm using apollo navigation mode, I have most of the modules configured. However, apollo perception module will not stay on. I checked the perception log and cyber_monitor but nothing shows. I tested the perception module with a demo bag and it works. Here is what I see. 
![Screenshot from 2021-08-04 19-01-18](https://user-images.githubusercontent.com/58639429/128289519-ec0ad1ac-f2f0-4a30-8241-11d6b24cb0fb.png)
![Screenshot from 2021-08-04 19-01-51](https://user-images.githubusercontent.com/58639429/128289533-f4c74887-4477-4642-8b90-788269a0d98e.png)
![Screenshot from 2021-08-03 20-43-24 (1)](https://user-images.githubusercontent.com/58639429/128289536-0425bc9f-6c67-4fa1-b10e-97f02236237f.png)
![Screenshot from 2021-08-03 20-39-44 (1)](https://user-images.githubusercontent.com/58639429/128289541-a28c3b27-ccd4-4e32-8045-e3086b992035.png)
![Screenshot from 2021-08-04 19-37-25](https://user-images.githubusercontent.com/58639429/128289583-cd8a1059-da77-4250-bb4a-c7e37008f945.png)
Nothing seems wrong or incorrect. Do I need to enable certain modules before perception? It takes localization as input but this is navigation mode. Do I need to send line data of a recorded drive first? Should I plug in the IMU and GPS? What is the issue that is preventing the perception module from starting? Do I need to be in a specific mode? Please note I'm using apollo 5.0 and navigation mode. I am also running on a camera only system. Any help/input would be appreciated. Thank you.

**Comment by xiaoMrzhang** [comment]
 These warnings are normal as long as the process does not exit. If you don't want to see this, you can add line "--half_vehicle_width=0.43" in file "modules/common/data/global_flagfile.txt" .
