### ISSUE TITLE
apollo air 想进一步了解 有什么途径？

### ISSUE THREAD

**Issue by TronYY** [ApolloAuto/apollo#14012]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
You can get more information on the official website  https://www.apollo.auto/its/lu/zhlk
