### ISSUE TITLE
Call Cyber libraries and compile 'listener' in CMake

### ISSUE THREAD

**Issue by ycs134470** [ApolloAuto/apollo#14011]
Hi, I want to call cyber libraries and compile 'listener' in cmake project, however failed to compile it.

![image](https://user-images.githubusercontent.com/84226401/128312222-f25c65cc-ac23-40e8-951d-af7aaa590a56.png)

![image](https://user-images.githubusercontent.com/84226401/128314462-551f14fd-b300-4db1-b538-1d37c14c4d7c.png)

**Comment by ycs134470** [comment]
Any help will be appreciated. Thank you in advance!

**Comment by daohu527** [comment]
@ycs134470  At present, cmake compilation is not supported. We have received your suggestion. If cmake will be supported in the future, we will notify you as soon as possible.
