### ISSUE TITLE
Using logging statements in module methods [help]

### ISSUE THREAD

**Issue by marifdemirtas** [ApolloAuto/apollo#14014]
Hi, I want to see which methods get called during execution. I tried inserting AINFO and ADEBUG statements into functions but they are not defined in some of the files under modules/ . Is there a way to use these statements project-wide or is there any other way of debugging?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:
```[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-06-11-ec30ae63c8
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

**Comment by daohu527** [comment]
You do can use log to debug. 

## INFO or DEBUG
if you want to print out debug level log you should follow below  steps
1. modify the "apollo/cyber/setup.bash"
``` 
# for DEBUG log 
 export GLOG_v=4 
```
2. Enable environment variables
```
source cyber/setup.bash
```

## Log file
you can find log in `data\log`. Basically every module has a log file corresponding to its name. For example, the log of the planning module is in `planning.INFO`

**Comment by marifdemirtas** [comment]
Thanks for the answer @daohu527 .
INFO / DEBUG was undefined for me, but so I am using AINFO / ADEBUG. However, I cannot use these to add logging to all files under the modules directory, because it says they are not declared.
```
(20:26:17) ERROR: /apollo/modules/perception/base/BUILD:205:11: C++ compilation of rule '//modules/perception/base:object' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/modules/perception/base/_objs/object/object.pic.d ... (remaining 68 argument(s) skipped)
modules/perception/base/object.cc: In constructor 'apollo::perception::base::Object::Object()':
modules/perception/base/object.cc:24:1: error: 'ADEBUG' was not declared in this scope```

Some other files that raised the same error was:
```
modules/drivers/canbus/common/byte.cc
modules/map/hdmap/adapter/coordinate_convert_tool.cc
modules/map/hdmap/adapter/coordinate_convert_tool.cc
modules/common/math/search.cc
modules/common/math/angle.cc
```

How should I fix this?

**Comment by daohu527** [comment]
You should include the `.h` file, also you should add the `deps` in BUILD file
```
#include "cyber/common/log.h"
```

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
