### ISSUE TITLE
Build failed , run apollo on agx xavier

### ISSUE THREAD

**Issue by Xavierlo1** [ApolloAuto/apollo#14013]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Ubuntu 18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**6.0
- **Output of `apollo.sh config` if on `master` branch**:master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
 i'm trying to start the docker/scripts/dev_start.sh but the build is failed .
This is the error:
Failed to start the docker container based on image:apolloauto/apollo:dev-aarch64-18.04-20201218_0030

**Comment by QS-L-1992** [comment]
My personal guess is that there is a problem with nvidia-docker, version or installation, which is different from the PC.

**Comment by Sal-96** [comment]
I resolved the frist problem but now the Apollo build is failed, when I try to build Apollo with . /apollo.sh build_opt_gpu I see this error, there are many of them 
![IMG_20210901_130952](https://user-images.githubusercontent.com/71519726/131661717-f6a2a951-30c7-423f-9e07-c7cbfb171ec4.jpg)

**Comment by daohu527** [comment]
We will support the arm platform in the future, which is still under discussion. : )
