### ISSUE TITLE
Help wanted :  多激光融合点云topic输出只有主雷达点云信息，并不是融合后点云信息？

### ISSUE THREAD

**Issue by peak9527** [ApolloAuto/apollo#14028]
车型是dev_kit_advanced_sne-r ， 使用对应的速腾16线3个激光雷达， 主雷达为后， 配置未做任何改动， fusion topic只有主雷达后雷达的点云信息， **并不是3个融合后点云**， **请问fusion topic只是用来可视化的吗， 激光感知算法的输入的是融合后的topic， 还是每个激光分别的topic， 比如left， right， back？**
![1](https://user-images.githubusercontent.com/26620832/129292548-91b79f88-4159-4663-893f-c6351965715f.png)
![2](https://user-images.githubusercontent.com/26620832/129292552-41266ab8-e2ce-4e87-b8c6-15ced006fd82.png)
![4CA076F1-F249-4abd-B2E0-D093312C71D7](https://user-images.githubusercontent.com/26620832/129292554-2d7c87e1-3375-4b91-9823-a6cd37a21167.png)
![vi](https://user-images.githubusercontent.com/26620832/129292558-7db80387-779f-4f43-9531-45e7e3dc50a5.png)

**Comment by daohu527** [comment]
You have not turned on the conversion module

you need to confirm there are "/apollo/sensor/lidar16/left/PointCloud2" and "/apollo/sensor/lidar16/right/PointCloud2". Then you can see the whole fusion lidar pointcloud
