### ISSUE TITLE
请问如何求解Path boundary生成凸空间的？

### ISSUE THREAD

**Issue by Bekasas** [ApolloAuto/apollo#14035]
请问如何求解Path boundary生成凸空间的？

在Optimal Vehicle Path Planning Using Quadratic Optimization for Baidu Apollo Open Platform论文中，
描述的方法是用回溯法遍历每个障碍物可能的绕行方向，生成几个候选的凸空间。

然而在4.8日的直播中，提到是用Sliding window来做的。请问这个滑动窗口是如何实现的呢？和上面的回溯法是替代关系还是互相结合呢？

### Supporting materials (screenshots, command lines, code/script snippets):
4.8日直播原文：
Q:
最新的EM算法，在piecewise jerk path optimizer中实现了qp，是取消了dp过程吗？qp结果直接输出为各个点的l，dl，ddl，不再采用多项式的形式是吗？
A:
l，dl，ddl，是代码率的变量，piecewise jerk path optimizer是用qp求解的，求解的结果是l，dl ，ddl，这也是多项式的形式。dp原来是用来求解Path boundary的，而不是用来求解piecewise jerk path optimizer，是两个东西。用dp来求解Path boundary的效果不太好，后来已经改成Sliding window 这种方式了。dp求解当时会有一些Path boundary抖动的问题，已经做过了优化。

原文链接：
https://mp.weixin.qq.com/s?__biz=MzI1NjkxOTMyNQ==&mid=2247494825&idx=1&sn=38837d6ac38402c5339cddcbb06ed9d9&chksm=ea1dfedbdd6a77cded18e38c668a45865352c5f465ab386086ebd0a94113fada0f161f5f41df&mpshare=1&scene=1&srcid=0817AXiplnXEpo9ogsklK15N&sharer_sharetime=1629168321587&sharer_shareid=ca71452cbb27481374be2157f92c3dd9&key=35a48c236ffb37da64f475258bf1415d1e1e93f35b7fb504bc382254f06919fdf83dd900fe429e83fa6ae3af7936ecc2825d35a5c67769ea269afd8250f1bc7f6ed21249b375beb55629168f56d2daa32048e39336abef1f658fac63a4c26d7bf87f538c01b5b44ca00f7692624983b449d2ab6b92786da535d50e7005c96d71&ascene=1&uin=NDA1MDE2NjU1&devicetype=Windows+Server+2012+R2+x64&version=62090538&lang=zh_CN&exportkey=AVuAdOOzQn88aQl0saEuFJU%3D&pass_ticket=HCPi9WMML5RcOk3cMKyJVO3IVQF%2BWh2htFmAg47%2FE9LBvcC9d9j2l%2FtO9uHIFy%2Bl&wx_header=0

**Comment by Tcloser** [comment]
有关凸空间生成可以参考这一部分：

https://github.com/ApolloAuto/apollo/blob/b5bd74112e2ec5d7c65cad6bea592353de566156/modules/planning/tasks/deciders/path_bounds_decider/path_bounds_decider.cc#L58

**Comment by Tcloser** [comment]
请问这个问题可以关闭了吗？？
