### ISSUE TITLE
Generate topics/ Create records offline

### ISSUE THREAD

**Issue by AM055** [ApolloAuto/apollo#14031]
System information
*OS Platform and Distribution: Linux Ubuntu 18.04
*Apollo installed from: source
**Apollo version: master

Steps to reproduce the issue:
***  I don't have the required hardware, but i have txt files containing IMU and GPS information. And i want to test  localization module. How can I generate topics? Is it possible to create records offline from txt files?

**Comment by daohu527** [comment]
Repeat with #14019
