### ISSUE TITLE
[ERROR] Build failed!

### ISSUE THREAD

**Issue by SDKPARAMAN** [ApolloAuto/apollo#14033]
### System information

- **OS Platform and Distribution 
-  Linux Ubuntu 18.04
- **Apollo version (1.0):
- **Output of r1.0.0

### Steps to reproduce the issue:

ERROR: /apollo/modules/planning/planner/BUILD:3:1: no such package '@eigen//': Error downloading [https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz] to /home/james/.cache/bazel/_bazel_james/540135163923dd7d5820f3ee4b306b32/external/eigen/3.2.10.tar.gz: GET returned 404 Not Found and referenced by '//modules/planning/planner:lib_planner'.
ERROR: Analysis of target '//modules/planning:lib_planning' failed; build aborted.

![Uploading 7E6E5CB6-0A38-4E3A-8ECD-5036B4E704CE.jpeg…]()

**Comment by daohu527** [comment]
Version 1.0 is currently not expected to be maintained

**Comment by SDKPARAMAN** [comment]
Yeah,ty bro I installed Apollo 3.0。 it's good

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
