### ISSUE TITLE
3D目标检测的疑问

### ISSUE THREAD

**Issue by FortuneStar** [ApolloAuto/apollo#14036]
yolo_camera_dector代码中为什么读取模型的路径是yolo-2d，我在docker中没找到yolo-2d这个文件夹，有知道的大佬帮忙解答下吗？

**Comment by xiaoMrzhang** [comment]
模型路径相关的配置文件在"/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/config.pt"下，具体可以参考"modules/perception/production/conf/perception/camera/obstacle.pt"文件。

**Comment by FortuneStar** [comment]
> 模型路径相关的配置文件在"/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/config.pt"下，具体可以参考"modules/perception/production/conf/perception/camera/obstacle.pt"文件。
Apollo3.0找不到production/conf/perception/camera/obstacle.pt，没有production/conf/perception/camera/路径，也没有obstacle.pt。怎么办呀

**Comment by FortuneStar** [comment]
已经解决
