### ISSUE TITLE
EM and Dp

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#1403]
Hi Apollo team,

I would like to ask two questions. What is the role of EM(Expectation Maximization) here? I couldn't find its implementation in planning layer. Also, it seems that DP(Dynamic Programming) is being used in planning, what is the problem that DP is used to solve?
Thank you!

**Comment by lianglia-apollo** [comment]
The current algorithm is composed of two DP and two QP(quadratic programming). The two DPs are used as a decision provider and QPs are used to generate smooth trajectories based on the decision results. The results of one planning cycle can be feed into the next planning cycle, and that is what EM refers to.

**Comment by wckorealsh** [comment]
Thanks. I assume the result of current planning cycle is a trajectory and next planning cycle utilizes that (history). Initially, I thought there might be some stochastic formulation regarding the expectation but perhaps not. Thanks anyway!
