### ISSUE TITLE
How to assure two component consumes at the same frequency?

### ISSUE THREAD

**Issue by bittuh** [ApolloAuto/apollo#14034]
Hi Apollo team,

Two detectors are assigned to two components but they are actually doing the same image source, as below
```
image source  ----------> component A -------------------> visualization
                 |                              ^
                 v                              |
                 --------> component B ---------|
```
If allowing both to spin as fast as possible and implement [`message_filter`](https://answers.ros.org/question/361664/syncingmerging-camera-and-lidar-data-for-a-detected-object/) stuff in visualization, the merged result can't be guaranteed to be consistent with the same image source. AFAIK, `message_filter` can only ensure they are close enough, but not definitely from the identical source.

Since we want to visualize consistent detection from the same image,
how can we ensure they are processing the same image and produce results at the same frequency? (which means the faster one will have to wait for the slower)

**Comment by daohu527** [comment]
If you think of this as two threads, you need a synchronization primitive, I think you can achieve it by `sequence_num`.

For example, **put the message in 2 queues, read the id from 1 queue, look for it in the other queue, and wait or discard if it is not found**. This type of message fusion is currently not supported, so you can try to implement it yourself

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
