### ISSUE TITLE
ROUTING crash

### ISSUE THREAD

**Issue by AM055** [ApolloAuto/apollo#14046]
### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **Apollo installed from**: source
- **Apollo version**: master

### Steps to reproduce the issue:
- **I am testing routing module : 
- I build module + build and run routing_tester (apollo/modules/routing/tools/routing_tester);
- I had this error! Does anyone have any idea on this?

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/87365572/130038365-0ed99328-57b6-4cfc-ad58-2c6cdcdb1caa.png)
![image](https://user-images.githubusercontent.com/87365572/130038428-ce820694-d0ab-4108-8890-2beed0d5ab32.png)

**Comment by ntutangyun** [comment]
looks like the error is related to the width of the lane.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
