### ISSUE TITLE
How to stop the dreamview

### ISSUE THREAD

**Issue by ustbzjf1** [ApolloAuto/apollo#14043]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution**:18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- when I run the scripts/bootstrap.sh, the dreamview is start, but after view the results, how can I stop the running of dreamview?

**Comment by daohu527** [comment]
`bash scripts/bootstrap.sh stop`

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
