### ISSUE TITLE
how to increase bestpose topic rate from 1 hz to 5hz

### ISSUE THREAD

**Issue by brycheng** [ApolloAuto/apollo#14048]
The bestpose topic rate is 1 hz
![image](https://user-images.githubusercontent.com/45783325/130177292-09eb9ff2-7792-4f47-87d5-133c509732a9.png)
while heading topic rate is 5hz
How can I increase bestpose topic rate to 5hz?

**Comment by AlexandrZabolotny** [comment]
This parameter is set in the Novatel receiver

**Comment by AlexandrZabolotny** [comment]
Or you can uncomment [this line](https://github.com/ApolloAuto/apollo/blob/c5a2e202087edb6d86e84399d11977975c5aa635/modules/drivers/gnss/conf/gnss_conf.pb.txt#L62) and put parameter 0.2 instead of 1

**Comment by brycheng** [comment]
> Or you can uncomment [this line](https://github.com/ApolloAuto/apollo/blob/c5a2e202087edb6d86e84399d11977975c5aa635/modules/drivers/gnss/conf/gnss_conf.pb.txt#L62) and put parameter 0.2 instead of 1

**Comment by brycheng** [comment]
> Or you can uncomment [this line](https://github.com/ApolloAuto/apollo/blob/c5a2e202087edb6d86e84399d11977975c5aa635/modules/drivers/gnss/conf/gnss_conf.pb.txt#L62) and put parameter 0.2 instead of 1

thanks, I will try it later.
