### ISSUE TITLE
V2X

### ISSUE THREAD

**Issue by ZZG5220** [ApolloAuto/apollo#14042]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

How does the OBU communicate with the V2X module?

**Comment by daohu527** [comment]
They communicate through the network and the interface used is `grpc`

**Comment by ZZG5220** [comment]
我在https://github.com/ApolloAuto/apollo-contrib/tree/master/obu上找到了OBU端的代码实现，但是安装grpc需要3.0以上版本的protobuff，而该https://github.com/ApolloAuto/apollo-contrib/tree/master/obu中指定的protobuf是2.6的，多次进行了尝试，还是没有交叉编译好，需要实现OBU端向apollo的v2x收发数据，该怎么去解决呢，谢谢！

**Comment by daohu527** [comment]
Are you compiling on arm, what is the apollo version and operating system you use?
