### ISSUE TITLE
cutecom软件基础配置发送命令行后没有返回配置OK的字样是什么问题

### ISSUE THREAD

**Issue by 1079658109** [ApolloAuto/apollo#14058]

**Comment by Eclipsehelio** [comment]
There are usually three possibilities.

1. Connect a wrong serial port. 
2. Serial port baudrate mismatch.
3. Bad ending characters.
![image](https://user-images.githubusercontent.com/3960012/133556713-aaabf7b5-c639-4733-886b-40c7cfef2093.png)

**Comment by denyz** [comment]
1.write the CMD into a file .
2. send file
