### ISSUE TITLE
Perception camera Apollo 5.5 won't run

### ISSUE THREAD

**Issue by tajinder96** [ApolloAuto/apollo#14056]
Hi, I am trying to run camera perception in Apollo 5.5 but I cannot get it to start. Please find details below including the gdb and bt output, thanks a lot! 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**: n/a

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

- start other modules (localization, transform, ...) using dreamview
- gdb --args mainboard -d modules/perception/production/dag/dag_streaming_perception_camera.dag

### Supporting materials (screenshots, command lines, code/script snippets):
![SIGABRT_perception_camera](https://user-images.githubusercontent.com/65403236/130752947-7cf48b21-87d1-4d31-8529-1fa1ab7667e6.png)
![bt](https://user-images.githubusercontent.com/65403236/130753012-6985b543-a0d4-41d4-b28c-a5852b21303b.png)

**Comment by daohu527** [comment]
It is recommended to migrate to the new version and have a try!
