### ISSUE TITLE
Apollo r5.5.0 docker内编译出错 

### ISSUE THREAD

**Issue by tianrking** [ApolloAuto/apollo#14051]
Ubuntu20.04 
Apollo r5.5.0 docker内编译出错

ERROR: (08-24 04:11:03.913) /apollo/modules/planning/scenarios/traffic_light/protected/BUILD:42:1: C++ compilation of rule '//modules/planning/scenarios/traffic_light/protected:stage_approach_test' failed (Exit 1).

**Comment by tianrking** [comment]
ERROR: (08-24 04:14:55.421) /apollo/modules/planning/scenarios/traffic_light/protected/BUILD:31:1: C++ compilation of rule '//modules/planning/scenarios/traffic_light/protected:traffic_light_protected_scenario_test' failed (Exit 1).

**Comment by ntutangyun** [comment]
seems to be a test: 

you could comment the following out and try again. 

cc_test(
    name = "traffic_light_protected_scenario_test",
    size = "small",
    srcs = ["traffic_light_protected_scenario_test.cc"],
    data = ["//modules/planning:planning_conf"],
    deps = [
        ":traffic_light_protected_scenario",
        "@gtest//:main",
    ],
)

cc_test(
    name = "stage_approach_test",
    size = "small",
    srcs = ["stage_approach_test.cc"],
    data = [
        "//modules/planning:planning_conf",
    ],
    deps = [
        ":traffic_light_protected_scenario",
        "@gtest//:main",
    ],
)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
