### ISSUE TITLE
Error with bridge.sh using Apollo 5.0 with LGSVL

### ISSUE THREAD

**Issue by WhoAmI-kai** [ApolloAuto/apollo#14053]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**: Sorry , I don't know what is ' master' branch, this is my output of 'apollo.sh config'
![2021-08-24 14-58-22 的屏幕截图](https://user-images.githubusercontent.com/74713558/130572137-e9ce2809-0172-47e3-a9c5-8ea492759192.png)

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I've been trying to run the simulator with Apollo 5.0 and when I execute` bridge.sh`, I get the following error message:
`scripts/bridge.sh: line 6: bazel-bin/cyber/bridge/cyber_bridge: No such file or directory`

Any ideas on what I'm doing wrong? One error message I also see in the previous step (I don't know if it's related or not) is that when I execute `bootstrap.sh`, it says:
```
nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
Could not launch module monitor. Is it already built?
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information
```

### Supporting materials (screenshots, command lines, code/script snippets):
![2021-08-24 15-00-24 的屏幕截图](https://user-images.githubusercontent.com/74713558/130572221-e67cbd5d-2afd-421f-b90f-375ce729eb82.png)

**Comment by ntutangyun** [comment]
have you built the apollo yet? 

if not, try to build with bash apollo.sh build_opt_gpu first.

**Comment by WhoAmI-kai** [comment]
I have used` ./apollo.sh build_opt_gpu` before running `bootstrap.sh`, but only the first time it can run。
When I restart the container or restart the machine and ran `bootstrap.sh`, I get the following error message:
```
nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
Could not launch module monitor. Is it already built?
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information
```
Then, when I executed `bridge.sh`,  I get the following error message:
`scripts/bridge.sh: line 6: bazel-bin/cyber/bridge/cyber_bridge: No such file or directory`

**Comment by ntutangyun** [comment]
normally when you exit the containers, even restart the computer, the built apollo will be saved and no need to build again. 

you could check the bazel-cache folder for this.

**Comment by WhoAmI-kai** [comment]
Sorry, I can't find the bazel-cache folder. 
Could you tell me how can I check the bazel-cache folder for this?
