### ISSUE TITLE
ERROR: Config value 'gpu' is not defined in any .rc file

### ISSUE THREAD

**Issue by hongze83** [ApolloAuto/apollo#14063]
root@in-dev-docker:/apollo# ./apollo.sh build
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-08-27-a3f5f72
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210426_0123
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[ OK ] Running GPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview: 
[INFO]     USE_GPU: 1  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=gpu
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/...
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/apollo/tools/bazel.rc
ERROR: Config value 'gpu' is not defined in any .rc file

**Comment by daohu527** [comment]
could you pls try ` ./apollo.sh build --config=cpu`

**Comment by fzd9752** [comment]
Missing the file https://github.com/ApolloAuto/apollo/blob/master/.bazelrc. You could create and copy file under apollo folder.

**Comment by Hgsil** [comment]
> root@in-dev-docker:/apollo# ./apollo.sh build [INFO] Apollo Environment Settings: [INFO] APOLLO_ROOT_DIR: /apollo [INFO] APOLLO_CACHE_DIR: /apollo/.cache [INFO] APOLLO_IN_DOCKER: true [INFO] APOLLO_VERSION: master-2021-08-27-a3f5f72 [INFO] DOCKER_IMG: dev-x86_64-18.04-20210426_0123 [INFO] APOLLO_ENV: STAGE=dev USE_ESD_CAN=false [INFO] USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1 [ OK ] Running GPU build on x86_64 platform. [WARNING] ESD CAN library supplied by ESD Electronics doesn't exist. [WARNING] If you need ESD CAN, please refer to: [WARNING] third_party/can_card_library/esd_can/README.md [INFO] Build Overview: [INFO] USE_GPU: 1 [ 0 for CPU, 1 for GPU ] [INFO] Bazel Options: --config=gpu [INFO] Build Targets: //modules/... union //cyber/... [INFO] Disabled: except //modules/drivers/canbus/can_client/esd/... WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files: /apollo/tools/bazel.rc ERROR: Config value 'gpu' is not defined in any .rc file

I have also encountered the same problem, how to can i sovle this problem?
