### ISSUE TITLE
About SVL sensor extrinsics

### ISSUE THREAD

**Issue by Xxfore** [ApolloAuto/apollo#14069]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:20.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:any
- **Output of `apollo.sh config` if on `master` branch**:N/A

### Steps to reproduce the issue:
when i run svl simulator and check /tf_static,
frame velodyne128 to frame novatel shows like

     **frame_id: novatel
   child_frame_id: velodyne128
   transform:
     translation:
       x: 0.2579201
       y: 0.980728924
       z: 2.31200003623962**

but as i check sensor configuration of Lincoln2017MKZ(Apllo5.0), 
Lidar :  x : 1.0510799 , y : 0 , z : 1.96
the center of rear axle offset : x : 0 , y : 0.35199999809265137 z: -1.4190000295639038 (baselink coordinate )
IMU :  x: 0.070351 , y : 0 , z: 0

So i have below confusion:
1. why x translation value is 0.2579201, how to compute this value?
2. i think z translation value should be 1.96 not 2.31200003623962

Hope your kindly reply.
Thanks a lot.

**Comment by daohu527** [comment]
> when i run svl simulator and check /tf_static,

If you run the svl simulator, the vehicle is in the simulator, so what you need is the parameters of the car in the game, not the MKZ!

When choosing the vehicle type, you can choose MKZ_LGSVL，then check the config in MKZ LGSVL whether it's right or not!

**Comment by Xxfore** [comment]
> > when i run svl simulator and check /tf_static,
> 
> If you run the svl simulator, the vehicle is in the simulator, so what you need is the parameters of the car in the game, not the MKZ!
> 
> When choosing the vehicle type, you can choose MKZ_LGSVL，then check the config in MKZ LGSVL whether it's right or not!

I means the sensor configuration in SVL assets bundle named "Lincoln2017MKZ " , it config z value "1.96" for Lidar sensor ,
But why the lidar was config as "    z: 2.31200003623962 " under folder modules/calibration/data/Lincoln2017MKZ_LGSVL??

**Comment by beanmoon** [comment]
> if so, then it may be a mistake

Can the extrinsic error in modules/calibration/data/Lincoln2017MKZ_LGSVL be fixed? Is there anyone who is responsible for this?

**Comment by daohu527** [comment]
Honestly, you can modify these configs to see if it's wrong. I'm still unclear on the reason for this difference
