### ISSUE TITLE
Adapt Rs-Lidar-M1 to Apollo

### ISSUE THREAD

**Issue by xuzhangjing** [ApolloAuto/apollo#14068]
### System information

- **Linux Ubuntu 18.04
- **Apollo version: 5.5

### Issue:

The title contains my question. In Apollo's lidar driver, cyber-based robsense has been adapted. But I can't find the relevant configuration about Rs-Lidar-M1. 
Can anyone help me solve this problem? Each of your suggestions will be of great significance to me. Thank you.

<img width="404" alt="1630287990(1)" src="https://user-images.githubusercontent.com/47742066/131274268-c9604907-77a0-41e0-bb6b-c54f747d1bcc.png">

**Comment by daohu527** [comment]
I saw that ROS supports all models but cyber not. https://github.com/RoboSense-LiDAR/rs_driver
