### ISSUE TITLE
apollo5.5 版本，编译通过后，bazel-bin中module的v2x模块没有生成相对应的二进制文件，该怎么处理

### ISSUE THREAD

**Issue by ZZG5220** [ApolloAuto/apollo#14065]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by Eclipsehelio** [comment]
By default, `apollo.sh` would exclude `v2x` module at compile time. You will modify `generate_build_targets` function in `apollo.sh`.
![image](https://user-images.githubusercontent.com/3960012/131945879-c67f256d-2f2f-416d-8c81-2b5c1c2ab375.png)

**Comment by ZZG5220** [comment]
谢谢，我在apollo.sh中修改了generate_build_tar，没有编译成功（可能是网络的原因），还在进一步尝试中。

**Comment by Eclipsehelio** [comment]
Indeed it is about network unreachable. `v2x` module depends on `grpc` which is built from source,  `grpc` depends on `boringssl` which will be downloaded from `googlesource.com`, you can change an alternatives url in `/apollo/.cache/bazel/xxxxxxxxxxxxxxxx/external/com_github_grpc_grpc/bazel/grpc_deps.bzl`

**Comment by ZZG5220** [comment]
我修改了grpc_deps.bzl中boringssl的url,修改为https://github.com/google/boringssl/archive/refs/heads/chromium-stable-with-bazel.tar.gz，下载没有问题，但之后出现了“grpc_deps.bzl:21:5:no such package '@boringssl//':BUILD file not found path and referenced by '//extern:libssl '”问题，使得编译失败，这需要该怎么做呢？是不是下载的boringssl版本不对？还是说需要在外部安装libssl?

**Comment by ZZG5220** [comment]
> 
> 
> Indeed it is about network unreachable. `v2x` module depends on `grpc` which is built from source, `grpc` depends on `boringssl` which will be downloaded from `googlesource.com`, you can change an alternatives url in `/apollo/.cache/bazel/xxxxxxxxxxxxxxxx/external/com_github_grpc_grpc/bazel/grpc_deps.bzl`

谢谢，修改后我多次进行尝试，其中将grpc_deps.bzl中boringssl的url,修改为https://github.com/google/boringssl/archive/refs/heads/chromium-stable-with-bazel.tar.gz，下载没有问题，但之后出现了“grpc_deps.bzl:21:5:no such package '@boringssl//':BUILD file not found path and referenced by '//extern:libssl '”问题，使得编译失败，这需要该怎么做呢？是不是下载的boringssl版本不对？还是说需要在外部安装libssl?

**Comment by Eclipsehelio** [comment]
https://github.com/google/boringssl/archive/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz
Have a try! Good luck!

**Comment by ZZG5220** [comment]
谢谢，还是没有编译成功，url换成了 https://github.com/google/boringssl/archive/dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz 这个，连接下载之后，错误"no such package '@boringssl//':BUILD file not found path and referenced by '//extern:libssl '”依然存在，多次尝试，依然编译不通过，还有其他的解决方法么？麻烦了，谢谢！

**Comment by Eclipsehelio** [comment]
Sorry for the late reply! Hope that you have solved it! Download `boringssl-dcd3e6e6ecddf059adb48fca45bc7346a108bdd9.tar.gz`and then unzip the compressed file. Check whether the `BUILD` file exists.
![image](https://user-images.githubusercontent.com/3960012/133249812-b6b727f1-8d21-4fc1-99b6-a696c9d28421.png)

**Comment by ZZG5220** [comment]
INFO: (10-09 07:34:14.130) Found 4225 targets...
ERROR: (10-09 07:34:37.392) /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/BUILD:388:1: C++ compilation of rule '@com_github_grpc_grpc//:grpc_plugin_support' failed (Exit 1).
In file included from external/com_github_grpc_grpc/src/compiler/php_generator.cc:24:0:
external/com_github_grpc_grpc/src/compiler/php_generator_helpers.h: In function 'grpc::string grpc_php_generator::GetPHPServiceFilename(const FileDescriptor*, const ServiceDescriptor*, const string&)':
external/com_github_grpc_grpc/src/compiler/php_generator_helpers.h:51:23: error: 'const class google::protobuf::FileOptions' has no member named 'has_php_namespace'
   if (file->options().has_php_namespace()) {
                       ^
external/com_github_grpc_grpc/src/compiler/php_generator_helpers.h:52:39: error: 'const class google::protobuf::FileOptions' has no member named 'php_namespace'
     oss << ReplaceAll(file->options().php_namespace(), "\\", "/");
                                       ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: At global scope:
external/com_github_grpc_grpc/src/compiler/php_generator.cc:26:40: error: 'google::protobuf::compiler::php::GeneratedClassName' has not been declared
 using google::protobuf::compiler::php::GeneratedClassName;
                                        ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: In function 'grpc::string grpc_php_generator::{anonymous}::PackageName(const FileDescriptor*)':
external/com_github_grpc_grpc/src/compiler/php_generator.cc:49:23: error: 'const class google::protobuf::FileOptions' has no member named 'has_php_namespace'
   if (file->options().has_php_namespace()) {
                       ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc:50:28: error: 'const class google::protobuf::FileOptions' has no member named 'php_namespace'
     return file->options().php_namespace();
                            ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: In function 'void grpc_php_generator::{anonymous}::PrintMethod(const MethodDescriptor*, grpc::protobuf::io::Printer*)':
external/com_github_grpc_grpc/src/compiler/php_generator.cc:74:58: error: 'GeneratedClassName' was not declared in this scope
       MessageIdentifierName(GeneratedClassName(input_type), input_type->file());
                                                          ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: In function 'grpc::string grpc_php_generator::{anonymous}::PackageName(const FileDescriptor*)':
external/com_github_grpc_grpc/src/compiler/php_generator.cc:54:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: (10-09 07:34:37.454) Elapsed time: 25.616s, Critical Path: 7.99s
==============================================
[ERROR] Build failed!
[INFO] Took 27 seconds
