### ISSUE TITLE
Apollo-master Lgsvl Radar perception

### ISSUE THREAD

**Issue by tajinder96** [ApolloAuto/apollo#14071]
Hi, I am getting a segmentation error in the radar perception module when working with SVL 2021.2 and simulating radar data. Could you please tell me if you have an idea of the problem? Thanks!  

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: Apollo-master 
- **Output of `apollo.sh config` if on `master` branch**: 
Apollo Environment Settings:
  APOLLO_ROOT_DIR: /apollo
  APOLLO_CACHE_DIR: /apollo/.cache
  APOLLO_IN_DOCKER: true
  APOLLO_VERSION: master-2021-08-20-b5bd74112e
  DOCKER_IMG: dev-x86_64-18.04-20210517_1712
  APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
  USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

- cyber.pb.conf clock_mode set as MODE_MOCK
- Launch Apollo (bootstrap_lgsvl, bridge) 
- Launch SVL simulator (start simulation)
- In dreamview, switch on localization and transform 
- Made a change in /modules/perception/production/dag/dag_streaming_perception_lgsvl.dag: channel in readers for component "FrontRadarDetection" changed to match the channel in SVL (/apollo/sensor/conti_radar) 
- Run gdb --args mainboard -d modules/perception/production/dag/dag_streaming_perception_lgsvl.dag

### Supporting materials (screenshots, command lines, code/script snippets):
![radarError](https://user-images.githubusercontent.com/65403236/131397688-359df813-a71f-4965-9cd1-ee7c85c06a80.png)

**Comment by daohu527** [comment]
Although I am not sure, can you synchronize the time of the two, and do not use `MODE_MOCK`. 

According to the error message, the time provided by the transform is inconsistent with the local time. I will confirm these soon, you can also try not to use the `MOCK_MODE`!

**Comment by tajinder96** [comment]
I had previously tried without using ``mock mode`` as well, but it gives the same errors. Do you have any suggestions on how I can better synchronize the time? 

Thanks a lot!

**Comment by daohu527** [comment]
The easiest way is to use ntp server to synchronize the time of 2 machines
