### ISSUE TITLE
No module named '_cyber_record_py3'

### ISSUE THREAD

**Issue by brycheng** [ApolloAuto/apollo#14074]
when run "python3 record.py" in apollo/cyber/python/cyber_py3/examples
ModuleNotFoundError: No module named '_cyber_record_py3'
how to fix this problem,many thanks.

**Comment by plumewind** [comment]
hello,

how to solved it ?

I get this:
![image](https://user-images.githubusercontent.com/25976399/215310167-23f24fb4-6b0b-4993-a520-f34de2911292.png)
