### ISSUE TITLE
Perception module : canTransform: target_frame world does not exist. :timeout

### ISSUE THREAD

**Issue by blacksheep0303** [ApolloAuto/apollo#14075]
- OS Platform and Distribution : Ubuntu 18.04
- Apollo installed from source 
- Apollo version 6.0
- Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: @non-git
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

**Question:** 
I want to use Apollo's lidar perception to detect obstacles. And there are four channels I have:
/apollo/sensor/lidar128/compensator/PointCloud2         /tf       /tf_static      /apollo/localization/pose
I use RTK_localization to get vehicle's location.And my /tf is  as below:
header:
    timestamp_sec: 1630402419.385713339
    frame_id: world
  child_frame_id: localization
  transform:
    translation:
      x: 591004.517646484
      y: 4138011.885366211
      z: 2.068305969
    rotation:
      qx: -0.031352293
      qy: 0.042867292
      qz: 0.578523278
      qw: 0.813935101
Then when I started the perception_lidar.launch , I got the error : "Can not find transform. 1630394586.933794022 frame_id: world child_frame_id: novatel Error info: canTransform: target_frame world does not exist.:timeout."

I'm very confused because  /tf  contains the tf from world to localization  and  /tf_static contains the tf from localization to novatel. But the error said  frame world does not exist.
Does anyone know what may cause this problem? I think I have the world frame.
Thanks a lot for your help!!!

**Comment by lxa199709** [comment]
hello，excuse me ,have you resolved this issue? I have the same problem!

**Comment by denyz** [comment]
I have same problem.My apollo version is r5.5.0.
-------------------------------------------------------
E0624 18:50:08.821683 20099 compensator.cc:34] Can not find transform. 1656096669313738000 frame_id:lidar16 Error info: canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.canTransform: target_frame world does not exist. canTransform: source_frame lidar16 does not exist.

**Comment by daohu527** [comment]
We should enable the tf module before running the perception module. The tf module will publish the sensor coordinate transformation matrix required for perception
