### ISSUE TITLE
Apollo 2.5: Failed to start docker container "apollo_dev" based on image

### ISSUE THREAD

**Issue by songwenhuang** [ApolloAuto/apollo#14088]
When running bash docker/scripts/dev_start.sh, I encountered the following issue:

[INFO] Starting docker container "apollo_dev" ...
926d5ac0392cd16c859bf1dddb63847a77c96d583aa506ee6c8fd115cf37cda2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/984414f238cbf3ac82299f7708b8beeeb437ccf536d869ae728c55cadeb68550/merged/dev/nvidia-uvm: input/output error: unknown.
[ERROR] Failed to start docker container "apollo_dev" based on image: apolloauto/apollo:dev-x86_64-20180906_2002

### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04.
- **Apollo installed from (source or binary)**: source.
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 2.5.
- **Output of `apollo.sh config` if on `master` branch**: N/A. (Must run apollo.sh in dev docker or release docker)

### Steps to reproduce the issue:

- bash docker/scripts/dev_start.sh

### Supporting materials (screenshots, command lines, code/script snippets):

[INFO] Starting docker container "apollo_dev" ...
926d5ac0392cd16c859bf1dddb63847a77c96d583aa506ee6c8fd115cf37cda2
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/984414f238cbf3ac82299f7708b8beeeb437ccf536d869ae728c55cadeb68550/merged/dev/nvidia-uvm: input/output error: unknown.
[ERROR] Failed to start docker container "apollo_dev" based on image: apolloauto/apollo:dev-x86_64-20180906_2002

**Comment by songwenhuang** [comment]
No change to the PC's settings and codes. When I tried "$bash docker/scripts/dev_start.sh" today, the issue disappeared and the codes were built within the docker successfully.

**Comment by davisliuu** [comment]
Hi，Have you found out exactly reason? I meet the same issue with you.

**Comment by songwenhuang** [comment]
Hi, Please try to bash docker/scripts/dev_start.sh for downloading updated images again. Sometimes, the servers' connections are not stable enough, so it will fail on downloading the docker images.
