### ISSUE TITLE
Does 3D obstacle perception not use a camera sensor?

### ISSUE THREAD

**Issue by kdheejb7** [ApolloAuto/apollo#14089]
We appreciate you go through Apollo documentation and search previous issues before creating a new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: master branch

### Steps to reproduce the issue:

Hello, 
I have no problem with Apollo implementation, but I have a question about 3D obstacle perception.
I wonder whether the camera is used for 3d obstacle perception or not.
These figures said that cameras are used for object detection. ([link](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md))
But this document said that Lidars and Radars are used for 3d obstacle perception. ([link](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception.md))

**Therefore, my main question is "Does 3D object perception use or not a camera sensor?"**
Thank you for your attention :) 

### Supporting materials (screenshots, command lines, code/script snippets):
These shows that cameras are used for 3d obstacle detection as well as traffic light detection. 
![image](https://user-images.githubusercontent.com/39160667/132449385-fcb68d01-93bd-4b86-9273-121bb6db0313.png)
![image](https://user-images.githubusercontent.com/39160667/132449400-adde4331-25c1-4248-b6a0-cee5f0a359e5.png)

But this shows that cameras are not used for 3d obstacle detection(perception)
![image](https://user-images.githubusercontent.com/39160667/132449496-9f14fe97-9958-405c-bea5-40a9ad2bc0f4.png)

**Comment by GiantSeaweed** [comment]
[#10495](https://github.com/ApolloAuto/apollo/issues/10495)
[#11887](https://github.com/ApolloAuto/apollo/issues/11887)

I guess these two issues might be helpful to you.

Please correct me if I understand something wrong!

**Comment by daohu527** [comment]
The earliest method uses monocular depth estimation, the new method uses smoke 3d method, and recently we are updating the model
