### ISSUE TITLE
Is it possible to add API for destroying Reader/Writer in Cyber bridge?

### ISSUE THREAD

**Issue by GooVincent** [ApolloAuto/apollo#14087]
I just did a test with LGSVL and cyber bridge. From the capture internet log, I found the cyber node still kept reading a certain channel when the TCP session closed. Is it reasonable?

And I checked modules/contrib/cyber_bridge/node.cc, didn't find any function like dele_reader or dete_writer, I wonder if it is possible to add this kind of API for destroying Reader/Write in Cyberdge.

**Comment by daohu527** [comment]
reader has a `shutdown` method.
```
  /**
   * @brief Shutdown Reader
   */
  void Shutdown() override;
```

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
