### ISSUE TITLE
怎么在Apollo5.5中添加Robosense M1固态激光雷达呢？

### ISSUE THREAD

**Issue by xuzhangjing** [ApolloAuto/apollo#14086]
### System information

- **Ubuntu 18.04
- **Apollo 5.5

我在Apollo5.5中看到有Robosense的机械式激光雷达的驱动配置，但是我找不到关于固态激光雷达Rs-Lidar-M1的相关驱动配置。请问有人实现过适配M1吗？这对我很重要，谢谢！

**Comment by daohu527** [comment]
duplicate with https://github.com/ApolloAuto/apollo/issues/14068

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
