### ISSUE TITLE
自动驾驶路侧感知数据集&&仿真

### ISSUE THREAD

**Issue by yyqgood** [ApolloAuto/apollo#14084]
你好，请问下：
1. 百度有开源的路侧感知数据集吗？
2. 百度开源的仿真软件支持路侧的测试吗？
期待你的回复，谢谢！

**Comment by daohu527** [comment]
It looks like this is a V2X scene, I suggest you refer to apollo air

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
