### ISSUE TITLE
problems about building  apollo3.5 in Jetson

### ISSUE THREAD

**Issue by fjc378209410** [ApolloAuto/apollo#14093]
**Describe the bug**
I tried to build apollo 3.5 on Jetson. After entering the docker, I executed the compilation command "bash apollo.sh build", and the following error occurred.

**Expected behavior**

**Screenshots**
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
Extracting Bazel installation...
............................................................
ERROR: error loading package '': Encountered error while reading extension file 'bazel/grpc_deps.bzl': no such package '@com_github_grpc_grpc//bazel': Error downloading [file:/home/tmp/v1.14.2.tar.gz] to /home/uvs/.cache/bazel/_bazel_uvs/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/v1.14.2.tar.gz: /home/tmp/v1.14.2.tar.gz (No such file or directory).
============================
[ERROR] Build failed!
[INFO] Took 17 seconds
============================

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Equipment: Jetson NX
 - Version Apollo 3.5

**Additional context**
I don’t know how to solve this problem. If there are results that have digged into this problem or have ideas, please leave a message, thank you

**Comment by daohu527** [comment]
Seems failed to download `com_github_grpc_grpc`. You should check the network first!

**Comment by Eclipsehelio** [comment]
You should download `https://github.com/grpc/grpc/archive/refs/tags/v1.14.2.tar.gz` and put the file under `/home/tmp/` in docker container.

**Comment by fjc378209410** [comment]
> Seems failed to download `com_github_grpc_grpc`. You should check the network first!

The network is ok, and maybe other problems.

**Comment by fjc378209410** [comment]
> You should download `https://github.com/grpc/grpc/archive/refs/tags/v1.14.2.tar.gz` and put the file under `/home/tmp/` in docker container.

I tried the method of copying, but found that not only this file is missing. Finally, I had to choose to give up the 3.5 version. Its files were developed for x86 and lacked a lot of arm64 configuration files.
