### ISSUE TITLE
How to visualize the map data?

### ISSUE THREAD

**Issue by NobushigeHaraki** [ApolloAuto/apollo#14090]
Is there a way to visualize the "base_map.bin" file?
There is no record file.

**Comment by Eclipsehelio** [comment]
There are several ways!
1)Create a directory under `/apollo/modules/map/data/`, move your hdmap files into the directory; browse dreamview frontend page, select your map, toggle `Sim Control` button
if you only have `base_map.bin`, you should generate `sim_map.bin` by yourself, use python scripts under `/apollo/modules/tools/map_gen`
2)Use `mapshow.py` under `/apollo/modules/tools/mapshow`
3)Use thirdparty tools, eg: LGSVL/Mathworks Roadrunner

**Comment by NobushigeHaraki** [comment]
Thank you for your help!
 I was able to visualize the map!
