### ISSUE TITLE
Apollo6.0如何限制编译线程数

### ISSUE THREAD

**Issue by Loong1512** [ApolloAuto/apollo#14099]
内存不够导致编译出错，暂时没法增加内存，请问有什么办法可以限制编译的线程数吗，应该修改哪里？

**Comment by ntutangyun** [comment]
you can use the bazel command to build apollo directly, then you can adjust the parallel tasks.

**Comment by Eclipsehelio** [comment]
You can change bazel command line arguments in `/apollo/scripts/apollo_build.sh`.
![image](https://user-images.githubusercontent.com/3960012/133252092-54cc89be-08eb-4e58-bff6-53ef14ddbe56.png)
