### ISSUE TITLE
When is the tentative release date of Apollo 7.0?

### ISSUE THREAD

**Issue by ravkum** [ApolloAuto/apollo#14098]
Hi,

I see that many modules already have Apollo 7.0 read me files. Please let me know when is Apollo 7.0 releasing?

Regards,
Ravi

**Comment by AIasd** [comment]
Following this question I wonder will 7.0 support traffic light detection? The camera detection seems to not work ever since 5.5.

**Comment by daohu527** [comment]
Apollo 7.0 has been released. @AIasd If you have any other questions, please open a new issue and we can discuss their
