### ISSUE TITLE
【紧急】虚拟机安装Apollo6.0开发环境-构建失败-[ERROR] Build failed!

### ISSUE THREAD

**Issue by pakakco** [ApolloAuto/apollo#14096]
(06:50:46) INFO: From Compiling modules/map/tools/map_datachecker/server/worker.cc:
In file included from external/poco/boost/property_tree/json_parser/detail/parser.hpp:7:0,
                 from external/poco/boost/property_tree/json_parser/detail/read.hpp:13,
                 from external/poco/boost/property_tree/json_parser.hpp:16,
                 from ./modules/map/tools/map_datachecker/server/common.h:29,
                 from ./modules/map/tools/map_datachecker/server/alignment.h:22,
                 from ./modules/map/tools/map_datachecker/server/eight_route.h:24,
                 from ./modules/map/tools/map_datachecker/server/alignment_agent.h:27,
                 from ./modules/map/tools/map_datachecker/server/worker_agent.h:26,
                 from modules/map/tools/map_datachecker/server/worker.cc:23:
external/poco/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
(06:53:41) INFO: From Compiling external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp:
bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp:139752:1: warning: 'void __Pyx_PyAsyncGen_Fini()' defined but not used [-Wunused-function]
 __Pyx_PyAsyncGen_Fini(void)
 ^~~~~~~~~~~~~~~~~~~~~
(06:58:37) ERROR: /apollo/modules/dreamview/backend/simulation_world/BUILD:7:11: C++ compilation of rule '//modules/dreamview/backend/simulation_world:simulation_world_service' failed (Exit 4): gcc failed: error executing command 
  (cd /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-7 \
    LD_LIBRARY_PATH=/usr/local/libtorch_cpu/lib:/usr/local/libtorch_cpu/lib:/usr/local/libtorch_cpu/lib:/usr/local/libtorch_cpu/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/opt/apollo/sysroot/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/apollo/scripts:/usr/local/qt5/bin:/apollo/bazel-bin/cyber:/apollo/bazel-bin/cyber/tools/cyber_recorder:/apollo/bazel-bin/cyber/tools/cyber_monitor:/apollo/bazel-bin/cyber/tools/cyber_channel:/apollo/bazel-bin/cyber/tools/cyber_node:/apollo/bazel-bin/cyber/tools/cyber_service:/apollo/bazel-bin/cyber/tools/cyber_launch:/apollo/bazel-bin/modules/tools/visualizer:/apollo/bazel-bin/modules/data/tools/rosbag_to_record:/apollo/modules/teleop/common/scripts \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF_CUDA_COMPUTE_CAPABILITIES=3.7,5.2,6.0,6.1,7.0,7.2,7.5 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/modules/dreamview/backend/simulation_world/_objs/simulation_world_service/simulation_world_service.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/modules/dreamview/backend/simulation_world/_objs/simulation_world_service/simulation_world_service.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/com_google_glog -iquote bazel-out/k8-fastbuild/bin/external/com_google_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-fastbuild/bin/external/zlib -iquote external/fastrtps -iquote bazel-out/k8-fastbuild/bin/external/fastrtps -iquote external/fastcdr -iquote bazel-out/k8-fastbuild/bin/external/fastcdr -iquote external/poco -iquote bazel-out/k8-fastbuild/bin/external/poco -iquote external/uuid -iquote bazel-out/k8-fastbuild/bin/external/uuid -iquote external/com_google_absl -iquote bazel-out/k8-fastbuild/bin/external/com_google_absl -iquote external/eigen -iquote bazel-out/k8-fastbuild/bin/external/eigen -iquote external/osqp -iquote bazel-out/k8-fastbuild/bin/external/osqp -iquote external/com_google_googletest -iquote bazel-out/k8-fastbuild/bin/external/com_google_googletest -iquote external/com_github_nlohmann_json -iquote bazel-out/k8-fastbuild/bin/external/com_github_nlohmann_json -iquote external/proj -iquote bazel-out/k8-fastbuild/bin/external/proj -iquote external/tinyxml2 -iquote bazel-out/k8-fastbuild/bin/external/tinyxml2 -iquote external/boost -iquote bazel-out/k8-fastbuild/bin/external/boost -Ibazel-out/k8-fastbuild/bin/external/osqp/_virtual_includes/osqp -isystem external/com_google_glog -isystem bazel-out/k8-fastbuild/bin/external/com_google_glog -isystem external/com_github_gflags_gflags -isystem bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags -isystem external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src -isystem external/zlib/zlib/include -isystem bazel-out/k8-fastbuild/bin/external/zlib/zlib/include -isystem external/fastrtps -isystem bazel-out/k8-fastbuild/bin/external/fastrtps -isystem external/fastcdr -isystem bazel-out/k8-fastbuild/bin/external/fastcdr -isystem external/poco -isystem bazel-out/k8-fastbuild/bin/external/poco -isystem external/uuid -isystem bazel-out/k8-fastbuild/bin/external/uuid -isystem external/eigen -isystem bazel-out/k8-fastbuild/bin/external/eigen -isystem external/osqp -isystem bazel-out/k8-fastbuild/bin/external/osqp -isystem external/com_google_googletest/googlemock -isystem bazel-out/k8-fastbuild/bin/external/com_google_googletest/googlemock -isystem external/com_google_googletest/googlemock/include -isystem bazel-out/k8-fastbuild/bin/external/com_google_googletest/googlemock/include -isystem external/com_google_googletest/googletest -isystem bazel-out/k8-fastbuild/bin/external/com_google_googletest/googletest -isystem external/com_google_googletest/googletest/include -isystem bazel-out/k8-fastbuild/bin/external/com_google_googletest/googletest/include -isystem external/com_github_nlohmann_json/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_nlohmann_json/include -isystem external/proj -isystem bazel-out/k8-fastbuild/bin/external/proj -isystem external/tinyxml2 -isystem bazel-out/k8-fastbuild/bin/external/tinyxml2 -isystem external/boost -isystem bazel-out/k8-fastbuild/bin/external/boost '-Werror=sign-compare' '-Werror=unused-variable' '-Werror=unused-but-set-variable' '-Werror=switch' '-march=native' '-fdiagnostics-color=always' '-Werror=reorder' '-std=c++14' '-DMODULE_NAME="dreamview"' '-Werror=return-type' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c modules/dreamview/backend/simulation_world/simulation_world_service.cc -o bazel-out/k8-fastbuild/bin/modules/dreamview/backend/simulation_world/_objs/simulation_world_service/simulation_world_service.pic.o)
Execution platform: @local_config_platform//:host
modules/dreamview/backend/simulation_world/simulation_world_service.cc: In member function 'void apollo::dreamview::SimulationWorldService::SetObstacleInfo(const apollo::perception::PerceptionObstacle&, apollo::dreamview::Object*)':
modules/dreamview/backend/simulation_world/simulation_world_service.cc:616:56: warning: 'bool apollo::perception::PerceptionObstacle::has_confidence() const' is deprecated [-Wdeprecated-declarations]
   world_object->set_confidence(obstacle.has_confidence() ? obstacle.confidence()
                                                        ^
In file included from bazel-out/k8-fastbuild/bin/modules/dreamview/proto/simulation_world.pb.h:41:0,
                 from ./modules/dreamview/backend/simulation_world/simulation_world_service.h:43,
                 from modules/dreamview/backend/simulation_world/simulation_world_service.cc:17:
bazel-out/k8-fastbuild/bin/modules/perception/proto/perception_obstacle.pb.h:4681:13: note: declared here
 inline bool PerceptionObstacle::has_confidence() const {
             ^~~~~~~~~~~~~~~~~~
modules/dreamview/backend/simulation_world/simulation_world_service.cc:616:80: warning: 'double apollo::perception::PerceptionObstacle::confidence() const' is deprecated [-Wdeprecated-declarations]
   world_object->set_confidence(obstacle.has_confidence() ? obstacle.confidence()
                                                                                ^
In file included from bazel-out/k8-fastbuild/bin/modules/dreamview/proto/simulation_world.pb.h:41:0,
                 from ./modules/dreamview/backend/simulation_world/simulation_world_service.h:43,
                 from modules/dreamview/backend/simulation_world/simulation_world_service.cc:17:
bazel-out/k8-fastbuild/bin/modules/perception/proto/perception_obstacle.pb.h:4691:15: note: declared here
 inline double PerceptionObstacle::confidence() const {
               ^~~~~~~~~~~~~~~~~~
modules/dreamview/backend/simulation_world/simulation_world_service.cc: In member function 'void apollo::dreamview::SimulationWorldService::UpdateDecision(const apollo::planning::DecisionResult&, double)':
modules/dreamview/backend/simulation_world/simulation_world_service.cc:857:38: warning: 'int apollo::planning::MainDecision::target_lane_size() const' is deprecated [-Wdeprecated-declarations]
   if (main_decision.target_lane_size() > 0) {
                                      ^
In file included from bazel-out/k8-fastbuild/bin/modules/planning/proto/planning_internal.pb.h:46:0,
                 from bazel-out/k8-fastbuild/bin/modules/dreamview/proto/simulation_world.pb.h:42,
                 from ./modules/dreamview/backend/simulation_world/simulation_world_service.h:43,
                 from modules/dreamview/backend/simulation_world/simulation_world_service.cc:17:
bazel-out/k8-fastbuild/bin/modules/planning/proto/decision.pb.h:9060:12: note: declared here
 inline int MainDecision::target_lane_size() const {
            ^~~~~~~~~~~~
modules/dreamview/backend/simulation_world/simulation_world_service.cc:858:55: warning: 'const apollo::planning::TargetLane& apollo::planning::MainDecision::target_lane(int) const' is deprecated [-Wdeprecated-declarations]
     world_.set_speed_limit(main_decision.target_lane(0).speed_limit());
                                                       ^
In file included from bazel-out/k8-fastbuild/bin/modules/planning/proto/planning_internal.pb.h:46:0,
                 from bazel-out/k8-fastbuild/bin/modules/dreamview/proto/simulation_world.pb.h:42,
                 from ./modules/dreamview/backend/simulation_world/simulation_world_service.h:43,
                 from modules/dreamview/backend/simulation_world/simulation_world_service.cc:17:
bazel-out/k8-fastbuild/bin/modules/planning/proto/decision.pb.h:9078:46: note: declared here
 inline const ::apollo::planning::TargetLane& MainDecision::target_lane(int index) const {
                                              ^~~~~~~~~~~~
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
(07:00:32) INFO: Elapsed time: 636.151s, Critical Path: 192.08s
(07:00:32) INFO: 216 processes: 216 local.
(07:00:35) FAILED: Build did NOT complete successfully

**Comment by suilaiji** [comment]
方法1：试试增加虚拟机内存，我编译的时候内存是8G，也会遇到这个错误。

方法2：分模块编译，例如：

只编译cyber
```shell
$ bash apollo.sh build cyber
```

只编译planning模块
```shell
$ bash apollo.sh build planning
```

只编译planning模块里的common目录
```shell
$ bash apollo.sh build planning/common
```

如此挨个编译所有modules目录下的所有子目录。
然后再运行一次总编译，确保所有模块都编译了。
```shell
$ bash apollo.sh build
```

注：原理是bazel会缓存编译结果，编译过某个子目录后，再编译它的上级目录，就不编译那个子目录了。
通过分模块编译，就让那些占内存比较大的进程分开运行，就不担心内存不够了。

**Comment by suilaiji** [comment]
方法3：参考 #14099 Apollo6.0如何限制编译线程数
尝试减少编译线程数，直到不再报同样错误。

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
