### ISSUE TITLE
请问Apollo 6.0 各个模块的单元测试文件怎么编译，编译之后的生成的可执行文件路径是哪里？

### ISSUE THREAD

**Issue by Eternal-Br** [ApolloAuto/apollo#14104]
目前我使用 ./apollo.sh build_dbg 可以顺利完成编译，但是编译生成的目标路径中并没找到 单元测试（test模块）相关的文件。以感知模块中的路面感知单元测试（perception/camera/test）为例，它的目标路径应当是： /apollo/bazel-bin/modules/perception/camera/test，但在 /apollo/bazel-bin/modules/perception/camera/ 路径下并没有找到 单元测试 test 相关的内容.
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: master

**Comment by Eclipsehelio** [comment]
When you explore apollo's directory structure, you will find that `/apollo/modules/perception/camera/test` doesn't contain a valid `BUILD` file, that would explain why you can't find UT binary file under `/apollo/bazel-bin/modules/perception/camera/`.
