### ISSUE TITLE
Please help: Calculate the distance between obstacle and EGO

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#14107]
Hello. Can anyone tell me how to calculate the distance betwwen the obstacle and EGO Vehicle? I can read the position data from the `cyber_monitor` of NPC and EGO, but calculate the Euclidean distance between this two points seems wrong.
![Screenshot from 2021-07-31 10-17-53](https://user-images.githubusercontent.com/42797233/133718958-a95b8bcc-13a0-49d6-bc46-d3f7b7ea32f4.png)
![Screenshot from 2021-07-31 10-16-54](https://user-images.githubusercontent.com/42797233/133718970-0474207d-46fd-4a9e-83d0-759256558f3e.png)

Thanks.

**Comment by daohu527** [comment]
There is no problem in calculating Euclidean distance in theory. What's the problem?

**Comment by GabrielZZZ** [comment]
@daohu527 The result I calculated is different to the value showed in DreamView, so I wonder **is my way of calculation is wrong or not:**
`distance = sqrt((perception_obstacle_position_x - localization_position_x)^2 + (perception_obstacle_position_y - localization_position_y)^2 + (perception_obstacle_position_z - localization_position_z)^2)`

I did not put any other data but position value into the calculation. Do I need to perform any forms of transformation between coordinate system or I can directly grab the values in perception and localization modules and subtract them together?

Thanks.

**Comment by daohu527** [comment]
The obstacle is running. Therefore, the data on the two sides may be inconsistent in time.

I check the distance calculation method, although the z coordinate of the obstacle is a bit strange, you can try it
```
(ego.x, ego.y, 0) -> (obstacle.x, obstacle.y, 0.5)
```


## obstacles.js
The relevant code can be found below
```js
      const position = coordinates.applyOffset(
        new THREE.Vector3(obstacle.positionX,
          obstacle.positionY,
          (obstacle.height || DEFAULT_HEIGHT) / 2),
      );
```

**Comment by GabrielZZZ** [comment]
Thank you for your reply! @daohu527 

Can you explain a bit more about this formula `(ego.x, ego.y, 0) -> (obstacle.x, obstacle.y, 0.5)`?

Is this the same as what I put before?
`distance = sqrt((perception_obstacle_position_x - localization_position_x)^2 + (perception_obstacle_position_y - localization_position_y)^2 + (0.5 - 0)^2)`

**Comment by daohu527** [comment]
Yes, you can try, remember the time synchronization problem.

**Comment by GabrielZZZ** [comment]
Speaking of that…… Any hints for solving the synchronization problem? My existing solution is to choose the timestamp of one point for EGO, and then look for the point of obstacle with the nearest timestamp, and then calculate the difference between these two points.

**Comment by daohu527** [comment]
Seems like this is the only way to do!
