### ISSUE TITLE
Test lane detection with Invalid class name & Failed to load module error.

### ISSUE THREAD

**Issue by Eternal-Br** [ApolloAuto/apollo#14109]
Hi guy! I've successfully build Apollo 6.0 with nvidia GPU. I've read  [how_to_run_perception_module_on_your_local_computer.md](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) 
 and I want to reproduce lane detection on my computer. 
I want to test lane detection alone, use: 
`mainboard -d modules/perception/production/dag/dag_streaming_perception_lane.dag`

But it seems that it does not work. Logs are as follow:

`
root@in-dev-docker:/apollo# mainboard -d modules/perception/production/dag/dag_streaming_perception_lane.dag
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0917 18:27:34.042076 23452 module_argument.cc:81] []command: mainboard -d modules/perception/production/dag/dag_streaming_perception_lane.dag 

I0917 18:27:34.042321 23452 global_data.cc:153] []host ip: **.**.**.**

I0917 18:27:34.043138 23452 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf

I0917 18:27:34.043157 23452 module_argument.cc:60] []dag_conf: modules/perception/production/dag/dag_streaming_perception_lane.dag

E0917 18:27:34.657850 23452 class_loader_manager.h:70] [mainboard]Invalid class name: LaneDetectionComponent

E0917 18:27:34.657883 23452 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/perception/production/dag/dag_streaming_perception_lane.dag

E0917 18:27:34.659308 23452 mainboard.cc:39] [mainboard]module start error.
`

I've checked this path  /apollo/modules/perception/production/dag/dag_streaming_perception_lane.dag  and it does exist !
My Nvidia and CUDA vertion: NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: yes

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
After enter Apollo docker container and start bootstrap, now we can browse dreamview on http://localhost:8888, then in Apollo docker container terminal, put:
`mainboard -d modules/perception/production/dag/dag_streaming_perception_lane.dag`

**Comment by daohu527** [comment]
It seems that the code has been updated. You can switch to the previous version. 

I am aslo not sure which version it is? : (

**Comment by Eclipsehelio** [comment]
Please check the following things:
1) Execute 
`ldd /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so | grep inner`, make sure the output contains `libmodules_Sperception_Sonboard_Scomponent_Slibperception_Ucomponent_Uinner_Ucamera.so`;
2) Excute 
`objdump -T /apollo/bazel-bin/modules/perception/onboard/component/libperception_component_inner_camera.so | grep  LaneDetectionComponent`
there would be a couple of `LaneDetectionComponent` related output.
3) If you didn't get any output, you should check `/apollo/modules/perception/onboard/component/BUILD` to make sure `perception_component_inner_camera` does exists.

![image](https://user-images.githubusercontent.com/3960012/134614459-69187151-55e3-41df-b9be-780a528b89d3.png)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
