### ISSUE TITLE
build 错误

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [ApolloAuto/apollo#14105]
你好！
当我安装Apollo 使用sudo ./apollo.sh build产生了如下错误，请问我该如何解决呢？

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- Ubuntu 18.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- Apollo v6.0
- **Output of `apollo.sh config` if on `master` branch**:
- (02:11:13) WARNING: Download from https://github.com/bazelbuild/rules_swift/releases/download/0.12.1/rules_swift.0.12.1.tar.gz failed: class java.io.IOException connect timed out
(02:11:13) ERROR: An error occurred during the fetch of repository 'build_bazel_rules_swift':
   Traceback (most recent call last):
	File "/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.12.1/rules_swift.0.12.1.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/build_bazel_rules_swift/temp11293974715659360049/rules_swift.0.12.1.tar.gz: connect timed out
(02:11:13) ERROR: /apollo/modules/v2x/proto/BUILD:95:16: //modules/v2x/proto:_v2x_service_car_to_obu_cc_grpc_grpc_codegen depends on @com_github_grpc_grpc//src/compiler:grpc_cpp_plugin in repository @com_github_grpc_grpc which failed to fetch. no such package '@build_bazel_rules_swift//swift': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.12.1/rules_swift.0.12.1.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/build_bazel_rules_swift/temp11293974715659360049/rules_swift.0.12.1.tar.gz: connect timed out
(02:11:13) ERROR: Analysis of target '//modules/v2x/proto:_v2x_service_car_to_obu_cc_grpc_grpc_codegen' failed; build aborted: Analysis failed
(02:11:13) INFO: Elapsed time: 75.534s
(02:11:13) INFO: 0 processes.
(02:11:13) FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_github_grpc_grpc//src/compiler ... (3 packages)

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/68255669/133538357-c19f98e5-3509-4f26-b301-8f6fa4b73586.png)

**Comment by HuangCongQing** [comment]
@Yuanzhuo-Liu 请问如何解决的呢？

**Comment by OrangeSoda1** [comment]
@Yuanzhuo-Liu 您好，请问您是如何解决的呢？

**Comment by HuangCongQing** [comment]
> @Yuanzhuo-Liu 您好，请问您是如何解决的呢？

我现在又重新运行来一遍,又没问题了,感觉可以多试下,可能是网络问题

**Comment by chasingw** [comment]
+1, Manually download and copy to the correct path can fix temporary

**Comment by chasingw** [comment]
network problem.
add proxy setup to `dev_into.sh` can solve
```
-e HTTP_PROXY="http://[yourproxyip]:[port]" \
-e HTTPS_PROXY="http://[yourproxyip]:[port]" \
```

**Comment by c0y0h** [comment]
@OrangeSoda1 请问您现在解决了吗

**Comment by c0y0h** [comment]
@Meta-YZ 请问最后怎么解决的，救救孩子

**Comment by POPCharlyn** [comment]
此问题已困扰几日，救救孩子

**Comment by Meta-YZ** [comment]
> 此问题已困扰几日，救救孩子

不好意思，兄弟们，才看见，我没有解决这个问题。
刚看到，竟然有这么多人有相同的问题。统一回复大家吧：我记得之前查相关资料，错误原因好像是显卡太旧了，所以放弃了。。。

**Comment by PhoenixZhong** [comment]
修改电脑上DNS，看图片，应该是要从GitHub下载文件，但是出现 connect  timeout  ,连接GitHub失败，
