### ISSUE TITLE
apollo 6.0  dreamview <defunct>

### ISSUE THREAD

**Issue by hyzhoo** [ApolloAuto/apollo#14103]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
      Ubuntu 18.04.5 LTS \n \l
     NVIDIA Jetson Xavier NX
- **Apollo installed from (source or binary)**:  source 
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  6.0
- **Output of `apollo.sh config` if on `master` branch**: 

### Steps to reproduce the issue:

   1、  ./apollo.sh build_opt_gpu
      (02:38:50) INFO: Elapsed time: 92.950s, Critical Path: 9.60s
      (02:38:50) INFO: 29832 processes: 11681 remote cache hit, 18151 internal.
      (02:38:50) INFO: Build completed successfully, 29832 total actions
      ==============================================
      [ OK ] Done building apollo. Enjoy!
      ==============================================

   2、  ./scripts/bootstrap.sh start
          dreamview process is not running!
          monitor process is not running!
          nohup: appending output to 'nohup.out'
          Launched module monitor.
          nohup: appending output to 'nohup.out'
          Launched module dreamview.
          http_status is 000
          Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information

- **Please use bullet points and include as much details as possible**:

 [bambo@in-dev-docker:/apollo]$ ./scripts/bootstrap.sh restart
dreamview process is not running!
monitor process is not running!
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
http_status is 000
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information

dbg：
gdb ./bazel-out/aarch64-opt/bin/modules/dreamview/dreamview ./data/core/core\ 30070\ 11\ 18446744073709551615\ 1\ 30070\ \!apollo\!.cache\!bazel\!540135163923dd7d5820f3ee4b306b32\!execroot\!apollo\!bazel-out\!aarch64-opt\!bin\!modules\!dreamview\!dreamview
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bazel-out/aarch64-opt/bin/modules/dreamview/dreamview...(no debugging symbols found)...done.
[New LWP 30080]
[New LWP 30105]
[New LWP 30070]
[New LWP 30104]
[New LWP 30111]
[New LWP 30102]
[New LWP 30112]
[New LWP 30110]
[New LWP 30114]
[New LWP 30079]
[New LWP 30145]
[New LWP 30115]
[New LWP 30082]
[New LWP 30122]
[New LWP 30118]
[New LWP 30078]
[New LWP 30120]
[New LWP 30081]
[New LWP 30121]
[New LWP 30125]
[New LWP 30119]
[New LWP 30142]
[New LWP 30087]
[New LWP 30117]
[New LWP 30085]
[New LWP 30116]
[New LWP 30143]
[New LWP 30113]
[New LWP 30123]
[New LWP 30136]
[New LWP 30084]
[New LWP 30088]
[New LWP 30135]
[New LWP 30127]
[New LWP 30141]
[New LWP 30124]
[New LWP 30126]
[New LWP 30129]
[New LWP 30091]
[New LWP 30128]
[New LWP 30144]
[New LWP 30131]
[New LWP 30086]
[New LWP 30090]
[New LWP 30130]
[New LWP 30146]
[New LWP 30133]
[New LWP 30092]
[New LWP 30089]
[New LWP 30094]
[New LWP 30095]
[New LWP 30098]
[New LWP 30132]
[New LWP 30093]
[New LWP 30140]
[New LWP 30097]
[New LWP 30096]
[New LWP 30139]
[New LWP 30101]
[New LWP 30100]
[New LWP 30134]
[New LWP 30099]
[New LWP 30108]
[New LWP 30109]
[New LWP 30107]
[New LWP 30083]
[New LWP 30106]
[New LWP 30103]
[New LWP 30138]
[New LWP 30137]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000055857d4a68 in apollo::cyber::croutine::RoutineFactory apollo::cyber::croutine::CreateRoutineFactory<apollo::common::monitor::MonitorMessage, std::function<void (std::shared_ptr<apollo::common::monitor::MonitorMessage> const&)> >(std::function<void (std::shared_ptr<apollo::common::monitor::MonitorMessage> const&)>&&, std::shared_ptr<apollo::cyber::data::DataVisitor<apollo::common::monitor::MonitorMessage, apollo::cyber::NullType, apollo::cyber::NullType, apollo::cyber::NullType> > const&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const ()
[Current thread is 1 (Thread 0x7fa9a04ed0 (LWP 30080))]
(gdb) Quit
(gdb)
(gdb) info auxv
33   AT_SYSINFO_EHDR      System-supplied DSO's ELF header 0x7fb720a000
16   AT_HWCAP             Machine-dependent CPU capability hints 0x7ff
6    AT_PAGESZ            System page size               4096
17   AT_CLKTCK            Frequency of times()           100
3    AT_PHDR              Program headers for program    0x5585516040
4    AT_PHENT             Size of program header entry   56
5    AT_PHNUM             Number of program headers      10
7    AT_BASE              Base address of interpreter    0x7fb71de000
8    AT_FLAGS             Flags                          0x0
9    AT_ENTRY             Entry point of program         0x55855fa994
11   AT_UID               Real user ID                   1000
12   AT_EUID              Effective user ID              1000
13   AT_GID               Real group ID                  1000
14   AT_EGID              Effective group ID             1000
23   AT_SECURE            Boolean, was exec setuid-like? 0
25   AT_RANDOM            Address of 16 random bytes     0x7fd967a818
31   AT_EXECFN            File name of executable        0x7fd967bfca "/apollo/bazel-bin/modules/dreamview/dreamview"
15   AT_PLATFORM          String identifying platform    0x7fd967a828 "aarch64"
0    AT_NULL              End of vector                  0x0
(gdb) q

### Supporting materials (screenshots, command lines, code/script snippets):
how can i fix this？ thanks ！

**Comment by Eclipsehelio** [comment]
Maybe you can build apollo without optimization! Have a try! Good luck!

**Comment by hyzhoo** [comment]
@Eclipsehelio thank your tips。   But ，without optimization， the planning can not to keep with calculations。

**Comment by daohu527** [comment]
We found that you are testing on the arm platform, we are considering to focus on solving the problem of the arm platform later. thank you for your feedback!
