### ISSUE TITLE
Please reply: How to extract the obstacle distance from Dreamview?

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#14100]
Hi all, I have one question. I want to extract the obstacle distance information shown in dreamview, like this:
![Screenshot from 2021-09-13 10-38-22](https://user-images.githubusercontent.com/42797233/133015891-5d553356-d81d-4dac-a41c-e102474ee2c3.png)
I cannot find the corresponding data in either `cyber_monitor` or `inspect the page element of the dreamveiw (since it is in canvas)`. Are there any ways of how extract the data? 

Thanks a lot.

**Comment by alexiskovi** [comment]
@GabrielZZZ in `cyber_monitor` you should choose `perception_obstacle` section (in `/apollo/perception/obstacles` channel). There you will find all info about detected obstacles

**Comment by GabrielZZZ** [comment]
Hello. Thanks for the reply. The `cyber_monitor` does not contain the obstacle distance information, which is specifically what I need...

**Comment by alexiskovi** [comment]
Seems to me you are right, Dreamview calculating this data by itself, sorry for wrong prompt. I think that if you want to get this by `cyber` only, you should calculate distance by yourself with `localization` and `perception` channels. I didn't find any distance info in `perception` and `prediction` proto files.

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
