### ISSUE TITLE
What trim or features are required for Lincoln MKZ? Does Hybrid Model work? 

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#14108]
Apollo 5.0 
Ubuntu 20.04 
I am ready for a field test. I know the default MKZ configuration files work on the MKZ however, I was wondering if the hybrid version of the MKZ also works. Only MKZ's optioned with adaptive cruise control and lane-keep assist can work for canbus files it seems is this correct? Also what model year is the best or works with the default config files? Can the 2016 before the redesign work or only 2016-present? Thank you. Any information on the best MKZ configuration would be appreciated. I want to use already existing config file for my testing.

**Comment by daohu527** [comment]
You mean which parameter? 
1. Usually there are parameters of the vehicle itself, such as wheelbase, length, width, steering angle, etc.
2. Kinetic parameters, usually obtained from the calibration table

**Comment by jp12AI** [comment]
> You mean which parameter? 
> 1. Usually there are parameters of the vehicle itself, such as wheelbase, length, width, steering angle, etc.
> 2. Kinetic parameters, usually obtained from the calibration table

Hi, thanks for response. However, what I meant was that there are multiple trims or versions of the Lincoln MKZ car. I was asking which model year car I should purchase. A 2017-2020 Lincoln model year? Does it need to have a particular option package (i.e. technology package)? Which Lincoln Mkz is best? Options, Year, etc. The specifics of the mkz since there are multiple options. Any response on these specifics of the recommended Lincoln mkz to use is appreciated. Thank you.

**Comment by daohu527** [comment]
I think it's best to check with the manufacturer!

Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
