### ISSUE TITLE
apollo/third_party/localization_msf目录下缺少aarch64架构的文件

### ISSUE THREAD

**Issue by Loong1512** [ApolloAuto/apollo#14102]
编译的时候报错
ERROR: /apollo/third_party/localization_msf/BUILD:8:11: //third_party/localization_msf:localization_msf: missing input file '//third_party/localization_msf:aarch64/lib/liblocalization_msf.so'
ERROR: /apollo/third_party/localization_msf/BUILD:8:11 1 input file(s) do not exist

localization_msf下的build文件区分了x86_64和aarch64架构，但是文件目录却只有x86_64的文件

当我尝试单独编译localization时也会报错
./modules/localization/msf/local_integ/gnss_msg_transfer.h:24:10: fatal error: localization_msf/gnss_struct.h: No such file or directory
 #include "localization_msf/gnss_struct.h"

找不到localization_msf/gnss_struct.h这个头文件

不知道是不是都是aarch64架构的原因，有什么解决办法吗？

**Comment by daohu527** [comment]
localization_msf is not support arm64 for now. as @fjc378209410 said, you can disable the localization_msf module and then build the project. 

It is recommended to wait for the official support of the arm version, currently cyber is supported

**Comment by Loong1512** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hardybbs123** [comment]
编辑 modules/localization/BUILD
删除此行:
        "//modules/localization/msf:install",

**Comment by Loong1512** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
