### ISSUE TITLE
HDMap format - extracting road length

### ISSUE THREAD

**Issue by marifdemirtas** [ApolloAuto/apollo#14116]
Hi,
I want to learn the total length of all roads in a given map. Is there a simple way to extract this information or any script that parses HDMap that can be used for this purpose?

For example, in [modules/map/data/demo/garage_routing.pb.txt](https://github.com/ApolloAuto/apollo/blob/master/modules/map/data/demo/garage_routing.pb.txt) there is a distance measurement. Is it the length of the road and how it is obtained?

Thanks,

**Comment by daohu527** [comment]
Simply speaking, you can traverse all lanes and add up their lengths.

https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/map/proto/map_lane.proto#L55

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
