### ISSUE TITLE
The possibility of stereo 3D object detection for autonomous driving

### ISSUE THREAD

**Issue by yyqgood** [ApolloAuto/apollo#14118]
Hello, may I ask: Can stereo 3D object detection be used for autonomous driving? What are the difficulties in the actual landing?
In addition, does Baidu have any plans in this regard?

**Comment by daohu527** [comment]
> Can stereo 3D object detection be used for autonomous driving?

Yes, we have now used 3d object detection in perception module, both for camera and lidar.
