### ISSUE TITLE
Build Apollo 3.0ARM failed on NVIDIA JETSON AGX XAVIER

### ISSUE THREAD

**Issue by xuhaitao1988** [ApolloAuto/apollo#14121]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:14.04 in docker env.
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:3.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible：

docker env（ubuntu14.04， bazel 0.5.3， cuda10.0， cudnn 7，python2.7.6，gcc4.8.4，tensorrt6.0）

/apollo/modules/perception/BUILD:40:1: Linking of rule '//modules/perception:perception' failed (Exit 1)./usr/lib/aarch64-linux-gnu/libnvinfer.so.6: undefined reference to `NvMediaDlaLoadFromMemory'；

**Comment by daohu527** [comment]
It is strongly recommended that you switch to the new version which will support arm. Of course there are still some problems, but at least we are a step forward
