### ISSUE TITLE
Cannot login - Error 504

### ISSUE THREAD

**Issue by MrShelton** [ApolloAuto/apollo#14127]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: iOS 15.0
- **Apollo installed from (source or binary)**: Apple App Store
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 1.11.2

### Steps to reproduce the issue:
- Downloaded app to new iPhone 13 Pro Max
- Installed Apollo from App Store
- Click "account" button in bottom navigation bar
- Enter username and password click "login"
- Review Apollo permissions and click "accept"
- After a minute a page from Reddit appears stating "we took too long to make this page for you. Error 504"

### Supporting materials (screenshots, command lines, code/script snippets):
Screenshot of error page
![thumbnail_IMG_0010](https://user-images.githubusercontent.com/91702243/135536440-3525772d-3069-440d-b19f-774a2312034c.jpg)

**Comment by daohu527** [comment]
I'm afraid this is not the problem you want, this is an autonomous driving software: )
