### ISSUE TITLE
GNSS UBLOX PARSER OFFICIAL SUPPORT/ Failed to create parser help

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#14128]
Apollo 5.0 
Ubuntu 20.04 
GNSS UBLOX PARSER 
I have a GNSS device that has a ublox GPS and nmea format. I modified my configuration files, however, if I change binary to UBLOX (which I need) from NOVATEL_BINARY it says failed to create the parser. I tried implementing the UBLOX parser by following these instructions however, the instructions lack detail and are confusing. Parts of the parser are integrated into config.proto. https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_gps_receiver.md Here are some screenshots of the errors I recieve. I do get raw data in cyber_monitor but nothing else. Any help or parser that is provided would be greatly appreciated. Thank you
![Screenshot from 2021-10-02 11-50-15](https://user-images.githubusercontent.com/58639429/135729931-ce380759-ff72-4764-a725-4007592d438f.png)
![Screenshot from 2021-09-29 20-38-47](https://user-images.githubusercontent.com/58639429/135730016-2662d968-6c28-49ae-9d71-c3e6ab96d472.png)
(With current configuration file) 
![Screenshot from 2021-09-28 22-07-33](https://user-images.githubusercontent.com/58639429/135730025-3dc14b08-bf74-4229-9ce4-8c042a313cd7.png)

**Comment by daohu527** [comment]
According to the error message, UBLOX does not seem to be supported currently.

By the way, can you adjust the question format, it's hard to read!

https://github.com/ApolloAuto/apollo/blob/b106c7e552b6cca68838a4f275edb953f88fbfce/modules/drivers/gnss/parser/data_parser.cc#L55-L63

**Comment by jp12AI** [comment]
@daohu527 It's very difficult to implement the parser mentioned here: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_gps_receiver.md  Most of the code is provided however, the instructions for steps 1 & 2 are not detailed. It also seems that support for the ublox parser is implemented in certain parts of the codebase: https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/gnss/proto/config.proto (underlines 7-16) Can you please provide the parser file for me to add to the parser folder so I can avoid following these instructions? The instructions contain everything but is difficult to understand where and how to place everything in the codebase. The file put together for this parser or help better understanding these instructions would be greatly appreciated.Thank you

**Comment by daohu527** [comment]
The document is only part of the example, you still need to implement the specific data analysis process

**Comment by daohu527** [comment]
Generally speaking, yes, because I do not represent the official reply, if you want to support, you can wait for the official reply whether to support

**Comment by wijdim** [comment]
@jp12AI I am also working on the integration of the ublox parser in apollo and i have the same issue. Did you manage to find the implemented file for ublox class?

**Comment by jp12AI** [comment]
@wijdim Hi, unfortunately I've shifted my work focus on a different level 2 software and I'm no actively developing Apollo any more. For the ublox parser you'll need a lot of experience. Apollo doesn't provide the parser so you'll have to code your own C++ paser following the format of the other parsers and then compile the code.

**Comment by wijdim** [comment]
@jp12AI Thank you for your answer, do you still have the new conf file for UBX_BINARY format?

**Comment by jp12AI** [comment]
@wijdim  Don't @ me across multiple issues. No, I don't have the config file for Ublox which is why I told you you'll have to code it yourself following the other parsers. Thanks

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by daohu527** [comment]
Although it seems a bit late, I made it clear that to support ublox, you only need to implement a parser class with reference to `modules/drivers/gnss/parser/novatel_parser.cc`
