### ISSUE TITLE
Apollo OpenDrive specification

### ISSUE THREAD

**Issue by AM055** [ApolloAuto/apollo#14124]
### System information

- **OS Platform and Distribution**:  Linux Ubuntu 18.04
- **Apollo installed from **: source
- **Apollo version **: master

### Steps to reproduce the issue:
- **I want to create my ow hdmap which can be used in Apollo. I need to know the apollo map format?
- **Can you email me the Apollo OpenDrive specification please ? thanks.

**Comment by daohu527** [comment]
duplicated #3005

**Comment by AM055** [comment]
> duplicated #3005
@daohu527 even in #3005, no specification mentionned and  there are many people who demand to send it.

**Comment by AM055** [comment]
> duplicated #3005
@daohu527 Can you send me the Apollo OpenDrive specification please

**Comment by daohu527** [comment]
Sorry I don’t have this file, you can refer to the format under the map path `modules\map\proto`

**Comment by AM055** [comment]
> Sorry I don’t have this file, you can refer to the format under the map path `modules\map\proto`

thank you @daohu527

**Comment by YanBC** [comment]
Check this out https://github.com/ApolloAuto/apollo/issues/13798#issuecomment-985991711
