### ISSUE TITLE
Questions about camera obstacle detection with the yolo model

### ISSUE THREAD

**Issue by kdheejb7** [ApolloAuto/apollo#14129]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- 
Hello, I have some questions about object detection using a camera in Apollo.

I understand camera obstacle detection now uses SMOKE model as a 3d object detection model.
However, before Apollo6.0, camera obstacle detection used Yolo model (2d object detection model).

I wanted to do camera obstacle detection with the yolo model provided by Apollo, so I modified some files like .dag files.
Then, I confirmed that my Apollo works with camera obstacle detection with the yolo model. 

During my modification, I have questions, and I want to ask some questions about Apollo's yolo model. 

My questions are, 
1) What version is Apollo's yolo used in Apollo 3.5 ~ 5.5? 
2) Is the yolo model that has not undergone any in-house modifications?
3) Can other 2d object detection models like basic yolov2, yolov3, and yolov4 replace Apollo's yolo model without any special process for getting 3d bboxes? 

Thank you for your consideration!

**Comment by daohu527** [comment]
We will upgrade the perception module in the near future, will support more models, and open model files then. pls follow the latest releases!
