### ISSUE TITLE
 ERROR: /apollo/modules/prediction/evaluator/BUILD:6:11: C++ compilation of rule '//modules/prediction/evaluator:evaluator_manager' failed (Exit 4): gcc failed: error executing command    (cd /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo && \

### ISSUE THREAD

**Issue by BillZHOU110** [ApolloAuto/apollo#14137]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution ( Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version ( 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
When I enter the cmd "./apollo.sh build." it build faild.
- **Please use bullet points and include as much details as possible**:
 ERROR: /apollo/modules/prediction/evaluator/BUILD:6:11: C++ compilation of rule '//modules/prediction/evaluator:evaluator_manager' failed (Exit 4): gcc failed: error executing command 
  (cd /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-7 \
    LD_LIBRARY_PATH=/usr/local/libtorch_cpu/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/apollo/modules/teleop/common/scripts:/apollo/bazel-bin/modules/tools/visualizer:/apollo/bazel-bin/cyber/tools/cyber_launch:/apollo/bazel-bin/cyber/tools/cyber_service:/apollo/bazel-bin/cyber/tools/cyber_node:/apollo/bazel-bin/cyber/tools/cyber_channel:/apollo/bazel-bin/cyber/tools/cyber_monitor:/apollo/bazel-bin/cyber/tools/cyber_recorder:/apollo/bazel-bin/cyber/mainboard:/usr/local/cuda/bin:/opt/apollo/sysroot/bin:/usr/local/nvidia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF_CUDA_COMPUTE_CAPABILITIES=3.7,5.2,6.0,6.1,7.0,7.2,7.5 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/modules/prediction/evaluator/_objs/evaluator_manager/evaluator_manager.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/modules/prediction/evaluator/_objs/evaluator_manager/evaluator_manager.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags -iquote external/com_github_google_glog -iquote bazel-out/k8-fastbuild/bin/external/com_github_google_glog -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-fastbuild/bin/external/zlib -iquote external/com_google_absl -iquote bazel-out/k8-fastbuild/bin/external/com_google_absl -iquote external/eigen -iquote bazel-out/k8-fastbuild/bin/external/eigen -iquote external/osqp -iquote bazel-out/k8-fastbuild/bin/external/osqp -iquote external/proj -iquote bazel-out/k8-fastbuild/bin/external/proj -iquote external/tinyxml2 -iquote bazel-out/k8-fastbuild/bin/external/tinyxml2 -iquote external/com_google_googletest -iquote bazel-out/k8-fastbuild/bin/external/com_google_googletest -iquote external/uuid -iquote bazel-out/k8-fastbuild/bin/external/uuid -iquote external/fastrtps -iquote bazel-out/k8-fastbuild/bin/external/fastrtps -iquote external/fastcdr -iquote bazel-out/k8-fastbuild/bin/external/fastcdr -iquote external/opencv -iquote bazel-out/k8-fastbuild/bin/external/opencv -iquote external/libtorch_cpu -iquote bazel-out/k8-fastbuild/bin/external/libtorch_cpu -iquote external/local_config_python -iquote bazel-out/k8-fastbuild/bin/external/local_config_python -Ibazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -Ibazel-out/k8-fastbuild/bin/external/com_github_google_glog/_virtual_includes/glog -Ibazel-out/k8-fastbuild/bin/ext

**Comment by zyq476916822** [comment]
You are definitely not the one meeting this issue. 
We are in the same platform Ubuntu 18.04 and Apollo 6.0.

However, our errors are a little bit different. My error occurs in the perception module when I tried to compile Apollo.

**Comment by daohu527** [comment]
According to your log, I can't see where the error message is, need to provide more information.

Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
