### ISSUE TITLE
Build apollo erro ：error: inlining failed in call to always_inline

### ISSUE THREAD

**Issue by lshaiou** [ApolloAuto/apollo#14134]
Hi all ,
    I am a newer here. I have tried to compile the newest version of Apollo 6.0 and ubuntu 20.04 LTS . But when I build apollo using"bash apollo.sh build",it was interrupted by an error ：  _error: inlining failed in call to always_inline '__m256i _mm256_loadu_si256(const __m256i_u*)': target specific option mismatch _mm256_loadu_si256 (__m256i_u const *__P)_
    I don't know how to solve it.Please help me 
![error](https://user-images.githubusercontent.com/31858109/136662352-62640eac-28bc-4742-839d-950ee39dc3ac.jpg)
!

**Comment by daohu527** [comment]
It seems that this problem is related to the cpu, the processor's AVX instruction set is not compatible. Can you check your cpu model? 

## Possible attempt
you can try to add `copt` option in build file and try again
https://github.com/ApolloAuto/apollo/blob/b106c7e552b6cca68838a4f275edb953f88fbfce/modules/drivers/camera/BUILD#L103-L110
to 
```
        },
        no_match_error = "Please Build with an ARM or Linux x86_64 platform",
    ),
   copts = [
      '-msse4.1'
    ],
    deps = [
        "//cyber",
        "//modules/drivers/camera/proto:config_cc_proto",
        "@ffmpeg//:avcodec",
    ] + if_x86_64(
```

**Comment by lshaiou** [comment]
> It seems that this problem is related to the cpu, the processor's AVX instruction set is not compatible. Can you check your cpu model?
> 
> ## Possible attempt
> you can try to add `copt` option in build file and try again
> 
> https://github.com/ApolloAuto/apollo/blob/b106c7e552b6cca68838a4f275edb953f88fbfce/modules/drivers/camera/BUILD#L103-L110
> 
> 
> to
> ```
>         },
>         no_match_error = "Please Build with an ARM or Linux x86_64 platform",
>     ),
>    copts = [
>       '-msse4.1'
>     ],
>     deps = [
>         "//cyber",
>         "//modules/drivers/camera/proto:config_cc_proto",
>         "@ffmpeg//:avcodec",
>     ] + if_x86_64(
> ```

OK。Thanks！~

**Comment by MrZhangmc** [comment]
> It seems that this problem is related to the cpu, the processor's AVX instruction set is not compatible. Can you check your cpu model?
> ## Possible attempt
> 
> you can try to add `copt` option in build file and try again
> 
> https://github.com/ApolloAuto/apollo/blob/b106c7e552b6cca68838a4f275edb953f88fbfce/modules/drivers/camera/BUILD#L103-L110
> 
> to
> 
> ```
>         },
>         no_match_error = "Please Build with an ARM or Linux x86_64 platform",
>     ),
>    copts = [
>       '-msse4.1'
>     ],
>     deps = [
>         "//cyber",
>         "//modules/drivers/camera/proto:config_cc_proto",
>         "@ffmpeg//:avcodec",
>     ] + if_x86_64(
> ```

I meet the same issue, and I add some flags according to the website: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#expand=3828,301,2553&text=_mm256_loadu_si256&ig_expand=4660,4370,4370
If you have some other functions, you also can search in the website, and add flags.
`copts = [
    '-mavx',
    '-mavx2'
 ]`
