### ISSUE TITLE
Sensors sequence received by fusion module is uncertain.

### ISSUE THREAD

**Issue by chexiaoyu** [ApolloAuto/apollo#14133]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:3.5

### Steps to reproduce the issue:
When I run "cyber_recorder play", I print the timestamp of sensors which send message to perception fusion modules. I noticed that the sequence of sensors is uncertain. Why it occurs? How to ensure "cyber _recorder play" can replay the same sequence as "cyber _recorder record"?
(Sensors timestamp sequences comparing after running two times)
### Supporting materials (screenshots, command lines, code/script snippets):
![screenshot-20211009-155046](https://user-images.githubusercontent.com/29246650/136649542-5aee0bee-aa5c-4b6f-8d0d-bc66dcb04ca4.png)

**Comment by chexiaoyu** [comment]
At the beginning of ` ObstacleMultiSensorFusion::Process()`add code:
```
std::ofstream outfile("/apollo/data/timestamp", std::ios::app);
outfile << frame->sensor_info.name <<": " << std::to_string(frame->timestamp) << std::endl;
outfile.close();
```
Yes, the problem is that order is wrong.

**Comment by daohu527** [comment]
It seems to be related to the coroutine scheduling, not sure whether it can be kept in order

**Comment by hugepig8** [comment]
It's not a problem. The replayer can't guarentee that the consumers can received the right data at the right time. so, you can put the every input sensor sample data when you cooking these data and put them into the resulat data's header. when you replay , you can found what the real data be fiiled at that time.

**Comment by daohu527** [comment]
In general, we can't fully control the timing, which is related to the system scheduling, but this may not have a great impact because the time is short
