### ISSUE TITLE
Apollo6.0 module Camera is not running

### ISSUE THREAD

**Issue by WhoAmI-kai** [ApolloAuto/apollo#14135]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  6.0
- **Output of `apollo.sh config` if on `master` branch**:
![image](https://user-images.githubusercontent.com/74713558/136719839-9eff50e3-f772-46ef-bf4f-bdc8056acc51.png)

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
  - `./docker/scripts/dev_start.sh`
  - `./docker/scripts/dev_into.sh`
  - `./apollo.sh build_opt_gpu`
  - `./scripts/bootstrap_lgsvl.sh`
  - `./scripts/bridge.sh`
  -  Run the LGSVL simulator with Apollo 6.0 use **Example** in `https://www.svlsimulator.com/docs/python-api/dreamview-api/`
  ![image](https://user-images.githubusercontent.com/74713558/136719625-816104f0-b68e-4a60-93af-ab206c1db1db.png)

 
### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/74713558/136726209-600a5286-d4ea-4367-86e4-baae2db47271.png)
![image](https://user-images.githubusercontent.com/74713558/136726253-74f50904-dfb1-4239-b5a3-ea2287667c13.png)

**Comment by Tcloser** [comment]
```
dv.set_hd_map('Borregas Ave')
dv.set_vehicle('Lincoln2017MKZ')
```

You can check `Lincoln2017MKZ` is Apollo 6.0 (modular testing) or Apollo 5.0 (full analysis), Apollo 6.0 (modular testing)  has no Camera.

**Comment by daohu527** [comment]
In general, we can't fully control the timing, which is related to the system scheduling, but this may not have a great impact because the time is short
