### ISSUE TITLE
How to receive CyberRT messages in docker from other machine via Ethernet port

### ISSUE THREAD

**Issue by songwenhuang** [ApolloAuto/apollo#14138]
How to set up the docker for receiving CyberRT messages transmitted from other machine via Ethernet port?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu18.04.
- **Apollo installed from (source or binary)**: source in docker.
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

[@in-dev-docker:/apollo]$ ./apollo.sh config
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: r6.0.0-2021-07-06-91dd437248
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200914_0742
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- **record CyberRT messages**: $cyber_recorder record -a

 [@in-dev-docker:/apollo]$ cyber_recorder record -a
[RUNNING]  Record Time: 0    Progress: 2 channels, 0 messages

- **Channel name**: configured.
- **Message**: cannot be received.

### Supporting materials (screenshots, command lines, code/script snippets):

Have modified the CYBER_IP in the setup.bash.
The IP address of PC and other machine locates in the same subnetwork, while docker's IP is different, listed as follows:

PC (receiver): 192.168.1.124
Other machine (transmitter): 192.168.1.119
docker0's IP address: 172.17.0.1

**Comment by songwenhuang** [comment]
Both publisher and subscriber use Cyber environment.

CYBER_IP has exported to their respective IP addresses.

However, still only channel's name can be configured, but messages cannot be received.

Is it due to the following reasons?

1. Proto files to be included for decoding CyberRT messages.
2. Different CyberRT version.

**Comment by daohu527** [comment]
You can check them, and then feedback

**Comment by songwenhuang** [comment]
1. I modified the proto files in the receiver side to be consistent with those in the transmitter. Then, the CyberRT messages can be correctly decoded at the receiver.
2. They are different CyberRT versions, while I only use the communication part, so this does not result in creating issues.
