### ISSUE TITLE
How does Apollo parse raw radar/lidar CAN messages to construct point cloud data?

### ISSUE THREAD

**Issue by AminoACID123** [ApolloAuto/apollo#14146]
Hello, I'm currently studying Apollo source code. I would like to understand how Apollo parses raw radar/lidar CAN messages to construct point cloud data. Which part of the source code should I pay attention to?
Sorry for this boring question, I'm only a green hand for the moment...

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
