### ISSUE TITLE
Documentation for improving the overall Apollo project using Sphinx and sphinx-intl.

### ISSUE THREAD

**Issue by xinetzone** [ApolloAuto/apollo#14149]
## 问题

1. 项目文档很混乱
2. 项目占用空间很大，不利于维护

## 提议
1. 整合项目文档的目录结构，便于 Sphinx 使用 glob 构建文档。
2. 将模型参数单独剥离出来（如放置于  `ApolloAuto/params`），并且也可以考虑把图片资源放置于一个单独的项目下，如 `ApolloAuto/images`。

## 针对提议2的解决方案

使用 Sphinx 的插件 `sphinx.ext.extlinks`，设置 `conf.py` 的一个变量：

```python
extlinks = {
    'images': ('http://apollo.auto', 'images'),
    'params': ('http://apollo.auto', 'params'),
}
```

这样处理，便可以直接在 `.rst` （或者 `.md` 文件）中使用角色 `:images:` 和 `:params:` 自动引用对应的资源。

## 初步解决方案

- [daobook/apollo](https://github.com/daobook/apollo) 的 `sphinx` 分支，修复了大量原文档的目录结构 bug。

最终，使用 GitHub Actions 实现自动化部署，可以预览当前文档：[apollo web](https://daobook.github.io/apollo/)。

**注意**：由于文档的目录结构很混乱，需要进一步改善。

**Comment by daohu527** [comment]
谢谢你的建议，目前modules目录的文档确实有点乱，我们近期会优化文档，如果文档上线我们会第一时间通知你，再次感谢！
