### ISSUE TITLE
How to offline camera calibration?

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#14144]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:

Calibration is attempted using the camera.
I tried obstacle detection through the command below.
"mainboard -d modules/perception/production/dag/dag_streaming_obstacle_detection.dag"
but like the picture below
I got an error saying "Calibration service is not available".
I think this is due to Online Calibration.
I want to do Offline Calibration.
I don't know how to do it because the documentation doesn't explain it. Please help.

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2021-10-21 09-20-57](https://user-images.githubusercontent.com/18480213/138249208-f58cae6d-6db5-43e2-89a5-e222f4f2499c.png)

**Comment by phs4530** [comment]
@daohu527 Yes, I use master branch.

**Comment by PeterJaq** [comment]
If you want to calibration your camera with IMU or Lidar offline. You can check the calibration part in [this repo](https://github.com/PeterJaq/Autonomous-Driving-101).

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
