### ISSUE TITLE
Wrong location on Apollo 5.0

### ISSUE THREAD

**Issue by peter0617ku** [ApolloAuto/apollo#14143]
Hi,

I downloaded Apollo from the following URL and used the `san_francisco` map.
https://github.com/ApolloAuto/apollo/tree/r5.0.0

When I am using **LGSVL** and **Apollo 5.0**, the location information cannot be synchronized, as shown in the figure below.

However, I did not encounter this situation when I simulated some maps such as `borregas_ave` and `go_mentum`.

How can I solve the problem of location synchronization? Thank you all for your answers in advance!

![Screenshot from 2021-10-21 14-50-43](https://user-images.githubusercontent.com/43951316/138226249-c4a147c0-2cfb-4335-9112-8a5025a8e1d5.png)

**Comment by Tcloser** [comment]
> ## time sync
> The error message is that the time of the IMU is not syn chronized. If it is two machines, make sure that the time is consistent.

It's the same machine and it's doesn't matter. Because I also meet this error and it also works well.

**Comment by MingfeiCheng** [comment]
> > ## time sync
> > The error message is that the time of the IMU is not syn chronized. If it is two machines, make sure that the time is consistent.
> 
> It's the same machine and it's doesn't matter. Because I also meet this error and it also works well.

Hi, I also meet this problem. Did you find a solution for that?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
