### ISSUE TITLE
The Apollo HD map built by Roadrunner reports an error when generating sim_map 

### ISSUE THREAD

**Issue by crasher32** [ApolloAuto/apollo#14155]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:20.04
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0

Hello, I'm currently studying Apollo and I want to build a scene in Roadrunner (mathworks). However, whether I use the sample scene that comes with Roadrunner or build a very simple scene by myself, I will get an error when I convert the exported base_map to sim_map using the script provided by Apollo.(Routing_map can be generated successfully)

- script
`dir_name=modules/map/data/demo # example map director`
`bazel-bin/modules/map/tools/sim_map_generator --map_dir=${dir_name} --output_dir=${dir_name}`

- error
`[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/repeated_field.h:1728] CHECK failed: (index) < (current_size_): `
`terminate called after throwing an instance of 'google::protobuf::FatalException'`
`  what():  CHECK failed: (index) < (current_size_): `
`Aborted (core dumped)`

![2021-10-29 22-16-07 的屏幕截图](https://user-images.githubusercontent.com/77274198/139453317-c142bd50-88fd-401a-a11b-e8d35098650c.png)

I don't know how to solve it.
I will be so grateful if anyone could help with this.

**Comment by wycrystal** [comment]
Excuse me, have you solved this problem? I have the same problem.

**Comment by wycrystal** [comment]
![image](https://user-images.githubusercontent.com/81356719/158749898-bbbc634a-64bb-446a-9e05-9d6770764676.png)

**Comment by ntutangyun** [comment]
you can just duplicate the base_map.bin file and name it sim_map.bin. 

the sim_map.bin is a simplified version of base_map.bin. The two can be the same.

**Comment by jdcllh** [comment]
hello guys, do you fix this issue? almost similar problem, and I try with just duplicate the base_map.bin to sim_map.bin, it's not work.
![roadrunner_to_apollo](https://user-images.githubusercontent.com/82990435/161392012-d7707c3e-4f36-4211-a561-25ebb49fed49.png)

**Comment by daohu527** [comment]
As far as I know, roadrunner has some bugs, which are related to the version. You can try to analyze the generated map file or confirm the version of roadrunner.

Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
