### ISSUE TITLE
Cyber_bridge error: A file with this name is already in the pool

### ISSUE THREAD

**Issue by kdheejb7** [ApolloAuto/apollo#14164]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Hello, I'm having trouble with the cyber_bridge part.
When I start Apollo and the lgsvl simulator, traffic light module, and perception module are off.
I took a look at error message in "cyber_bridge.log.INFO.2021xxxxxx", 
the file said "**cyber_bridge.log.INFO.20211102-113321.11488:57:W1102 11:33:42.502216 11488 protobuf_factory.cc:218] [modules/common/proto/error_code.proto] A file with this name is already in the pool.**"

What should I do to fix this error?  

Rebuild and restarted, the same error occurs :( 

Thank you!

**Comment by daohu527** [comment]
Can you describe your problem in detail and how to reproduce it？

According to your current information, there may be some problems with protobuf itself

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
