### ISSUE TITLE
What does it mean if there are more than one sequence_num in log?

### ISSUE THREAD

**Issue by 1Jyfc** [ApolloAuto/apollo#14162]
### System information

- **OS Platform and Distribution**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- Hello Apollo! I'm working on Planning module recently, and I use LGSVL simulator to connect to Apollo 6.0 to run simulations. After I read `planning.INFO` in `data/log` I found that sometimes there are more than one `sequence_num: x` in that file. Normally only `sequence_num: 0` in one simulation. I try to search in code but cannot find where Apollo generate this log. Could you tell me where it is generated and what it means? I'm working on stage switch of planning module, and I found after `sequence_num: x` the stage will be set default, which causes confusion. Hope for your reply, thanks a lot!

### Supporting materials:
[planning_info.zip](https://github.com/ApolloAuto/apollo/files/7453512/planning_info.zip)

**Comment by daohu527** [comment]
Generally speaking, `sequence_num` used to number messages.
If there are 100 messages, then sequence_num = 100. The `PlanningBase` has its own counted sequence_num, and the message header also includes sequence_num, so you'd better send out the print log then we continue to analyze it. : )

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
