### ISSUE TITLE
no cuda build for perception

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#14165]
Can we  build perception in an platform without  nvidia devices, So wo can port Apollo to intel openvino  or  any other hardware acceleration device..
Can we Do it now? 
Is there any plan to do this?

**Comment by daohu527** [comment]
@sinopec No, currently we don't  plan to do this. You know that Apollo is an end-to-end self-driving framework that can actually be used in production environments.

Adding cpu support may be helpful for learning, we will consider this in the future, thank you for your suggestion
