### ISSUE TITLE
Data to execute the perception module.

### ISSUE THREAD

**Issue by m-alcon** [ApolloAuto/apollo#14175]
I am trying to execute the perception module in Apollo 6 (branch r.6.0.0) to measure the impact it has on my machine. As discussed [here](https://github.com/ApolloAuto/apollo/issues/12916), in this branch, the camera node is in the process of refactoring, so I'm using the module with lidar (launch file */apollo/modules/perception/production/launch/perception_lidar.launch*).

The problem is that, after launching perception with the **unique** record file you provide for Apollo using CyberRT (*demo_3.5.record*, downloaded by the script */apollo/docs/demo_guide/record_helper.py*), I have noticed the main process of the module was not running. Then, I realized there are no messages from lidar (nor camera, nor radar) topics on the *record* file. Hence, I am not able to make the perception module process any of this data, so I cannot measure the impact it has on my machine.

Are there more *record* files somewhere with data from the camera or lidar sensors? Is there some way to generate these data (apart from recording real runs on real autonomous cars)?

Thank you in advance.

**Comment by daohu527** [comment]
You can try to use the simulator(lgsvl,carla) to publish sensor information, there is currently no recorded bag.

**Comment by daohu527** [comment]
@m-alcon there is a test record here for now [demo_sensor_data_for_vision](https://apollo-system.cdn.bcebos.com/dataset/6.0_edu/demo_sensor_data_for_vision.tar.xz)
