### ISSUE TITLE
Full analysis Sensor Configuration of Apollo 6.0 on SVL Simulator

### ISSUE THREAD

**Issue by ShisatoYano** [ApolloAuto/apollo#14176]
Hello, I'm Shisato Yano, autonomous driving system engineer in Japan.  
I've been trying to simulate by connecting between Apollo 6.0 and SVL Simulator.  
Simulation by 6.0 (modular testing) and SVL Simulator was fine and next, I want to simulate as full analysis sensor configuration like 5.0.  

I added a configuration same as 5.0 (full analysis) and confirmed that 6.0 and SVL Simulator were connected successfully and each topic of sensor was being updating on SVL Simulator.  (Radar, LiDAR and Camera and etc.)  
But, on DreamView, any object detection bouding box was not displayed and the vehicle didn't start driving.  

Could you tell me that only 5.0 is allowed to connect and simulate with SVL Simulator 
for full analysis testing currently? If I want to try simulating by 6.0 as not only modular testing but also other configurations (including Radar, LiDAR and any other sensors), how shoud I do?  

Best Regards,

Shisato Yano 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

### Steps to reproduce the issue:
1. Open SVL Simulator browser and download a JSON file of Apollo 5.0 (full analysis) configuration.  
2. Copy the JSON file and rename to Apollo 6.0 (full analysis).json.  
3. Start Apollo 6.0 by dev_start.sh -> dev_into.sh -> bootstrap_lgsvl.sh -> bridge.sh.  
4. Run Simulation using the above Apollo 6.0 (full analysis) configuration and confirm that Connection status each other.  
5. Connection status will be OK and each topic of sensor will be updated.  
6. Open DreamView.  
7. Make each module enable (Localization, Transform, LiDAR, Radar, GPS, Camera, Planning, Prediction, Routing). And then, Radar, Camera and GPS were made disable immediately...  
8. On DremView, you should be able to confirm that there is no object bounding box and you can just selecting destination point but the vehicle doesn't start driving.

**Comment by Tcloser** [comment]
Hi Shisato Yano, 
   I happen to be doing the simulation of Apollo v6.0.0 and lgsvl today. I just want to test planning and control so 6.0 (modular testing) is enough.

> 2. Copy the JSON file and rename to Apollo 6.0 (full analysis).json.

I tried to make 5.0 (full analysis) and apollo6.0 work together, but It's true that the performance of lateral control is terrible. You can try to copy  LiDAR, Radar, Camera part from 5.0 (full analysis) to 6.0 (full analysis).

**Comment by ShisatoYano** [comment]
Hi @Tcloser,
Thank you for replying.  
I have already tried to copy LiDAR, Radar, Camera part from 5.0 (full analysis) to 6.0 (full analysis) but it didn't work well. I could run simulator and connect with 6.0 (full analysis) but the vehicle did not start driving to destination point.. (It looked like the system entered to Auto mode)  

How about connecting between LV Simulator (5.0 full analysis) and Apollo 5.0?
Should I build 5.0 and try again connecting with LV Simulator (5.0 full analysis)?

**Comment by Tcloser** [comment]
Hi @ShisatoYano ,
If you want to build 5.0 you can download [lgsvl for apollo5.0](https://github.com/devynliu/lgsvl_apollo-5.0) and have a try. It's true that the support for apollo6.0 is not good enough.

**Comment by ShisatoYano** [comment]
Hi @Tcloser,
Thank you for helping me and I will try building 5.0.  
By the way, my own PC has the following prerequisites for building 6.0 now. Can 5.0 be built in the same environment?

![image](https://user-images.githubusercontent.com/40762735/144436149-35964b38-dc7e-4672-b73a-fc113336a93e.png)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
