### ISSUE TITLE
Failed when run 'yarn install' under '/apollo/module/dreamview/frontend' inside Apollo Dev Docker container

### ISSUE THREAD

**Issue by GaoPenghao** [ApolloAuto/apollo#14178]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**: source, docker
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:
- [INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-10-25-a67d9ca9d6
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- I made a small modification to some models in dreamview. When I recompile the front end of dreamview according to the instructions, the following are the specific commands:
cd /apollo/modules/dreamview/frontend/
rm -rf node_modules
yarn install
cd /apollo
bash apollo.sh build_fe
When I executed yarn install, an error occurred, reminding me that python2 was not installed.The specific error is as follows:
error /apollo/modules/dreamview/frontend/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /apollo/modules/dreamview/frontend/node_modules/node-sass
Output:
Building: /usr/local/bin/node /apollo/modules/dreamview/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/apollo/modules/dreamview/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.18.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/apollo/modules/dreamview/frontend/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/apollo/modules/dreamview/frontend/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/apollo/modules/dreamview/frontend/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /apollo/modules/dreamview/frontend/node_modules/which/which.js:89:16
gyp verb `which` failed     at /apollo/modules/dreamview/frontend/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /apollo/modules/dreamview/frontend/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/apollo/modules/dreamview/frontend/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/apollo/modules/dreamview/frontend/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/apollo/modules/dreamview/frontend/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /apollo/modules/dreamview/frontend/node_modules/which/which.js:89:16
gyp verb `which` failed     at /apollo/modules/dreamview/frontend/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /apollo/modules/dreamview/frontend/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Linux 5.4.0-90-generic
gyp ERR! command "/usr/local/bin/node" "/apollo/modules/dreamview/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /apollo/modules/dreamview/frontend/node_modules/node-sass
gyp ERR! node -v v12.18.1

**Comment by daohu527** [comment]
node-sass needs python2 which is out of life. It seems that this is a problem of some version matching. You can install python2 to solve this problem.
You can ref to [link](https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp)

**Comment by GaoPenghao** [comment]
thanks a lot! After installing python2, it worked.

**Comment by POPCharlyn** [comment]
I also encountered this problem. I try to use the command "sudo apt install python2", but I can't install python2 in the docker of Apollo. What should I do?
