### ISSUE TITLE
Dreamview is blank in browser 

### ISSUE THREAD

**Issue by IvanYe1** [ApolloAuto/apollo#14189]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**:
- source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- master
- **Output of `apollo.sh config` if on `master` branch**:
- [INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-11-16-a379b21230
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

1.when run bash ./scripts/bootstrap.sh start in docker, the output is as follow. 
dreamview module is launched，but when open localhost:8888 in browser, it's blank.

nohup: appending output to 'nohup.out'
[ OK ] Launched module monitor.
nohup: appending output to 'nohup.out'
[ OK ] Launched module dreamview.

2. acording to FAQ of dreamview, I change server_ports to 5555， but dreamview is still blank，

3. when run "ps aux | grep dreamview" in docker, the output is

/usr/bin/python3 /apollo/bazel-bin/cyber/tools/cyber_launch/cyber_launch.runfiles/apollo/cyber/tools/cyber_launch/cyber_launch.py start /apollo/modules/dreamview/launch/dreamview.launch；
/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt；

4. when run "lsof -i :8888" in localhost, it display:

COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
dreamview 18356 ****    3u IPv4 3020969 0t0 TCP *:8888 (LISTEN)

5. And the building of cyber_visualizer is failed, so I comment out it.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
