### ISSUE TITLE
 I am using the release version, how can I load Sunnyvale with Two Offices Map in lgsvl-release-2021.3

### ISSUE THREAD

**Issue by liuyuguang86** [ApolloAuto/apollo#14186]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
In fact, you can’t. LGSVL doesn’t have a Sunnyvale with Two Offices map. 

If you want to generate the map in the simulator based on the high-precision map, you need to build the model yourself

**Comment by AaronWaxson** [comment]
> how should I build the model ? Is there any instruction?

**Comment by daohu527** [comment]
LGSVL actually supports the generation of game maps (models) based on high-precision maps. 

You can refer to the mesh in the game and some other knowledge, or you can directly use the functions provided by lgsvl

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
