### ISSUE TITLE
How to run apollo on Xavier?

### ISSUE THREAD

**Issue by OrangeSoda1** [ApolloAuto/apollo#14190]
I tried to run apollo after install docker and Nvidia Container Toolkit. But I can't run it.
Is my docker version wrong?Should I reinstall the Docker?
![微信图片_20211119152204](https://user-images.githubusercontent.com/57565503/142581875-71a677b9-dbb1-4b3d-9e64-da05eadb7d1b.jpg)

**Comment by kontonpuku** [comment]
You need to build the Apollo container at first. The command `./apollo.sh build` is used to build the Apollo system inside the container. More detailed steps can be found here: https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
