### ISSUE TITLE
Camera Perception core dump

### ISSUE THREAD

**Issue by Xxfore** [ApolloAuto/apollo#14199]
**Describe the bug**
Camera Perception module has core dump sometimes.

**To Reproduce**
1. Enter Docker 
2. Build 
3. Open DreamView and start "GPS, Localization, Transform, Camera , Camera Perception"

**Expected behavior**
No Core dump.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] NA

**Additional context**
use D-kit hardware and run v6.0_edu branch version, and Enable Debug information 
Camera Perception sometimes has below core dump

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
btCore was generated by `mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _mm256_load_pd (__P=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:862
862      return *(__m256d *)__P;
[Current thread is 1 (Thread 0x7f9abdffb700 (LWP 26700))]
(gdb) bt
#0  _mm256_load_pd (__P=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:862
#1  Eigen::internal::pload<double __vector(4)>(Eigen::internal::unpacket_traits<double __vector(4)>::type const*) (from=<optimized out>) at external/eigen/Eigen/src/Core/arch/AVX/PacketMath.h:215
#2  Eigen::internal::ploadt<double __vector(4), 32>(Eigen::internal::unpacket_traits<double __vector(4)>::type const*) (from=<optimized out>) at external/eigen/Eigen/src/Core/GenericPacketMath.h:463
#3  Eigen::internal::evaluator<Eigen::PlainObjectBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >::packet<32, double __vector(4)>(long, long) const (this=<optimized out>, col=<optimized out>, row=<optimized out>)
    at external/eigen/Eigen/src/Core/CoreEvaluators.h:197
#4  Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::assign_op<double, double>, 0>::assignPacket<32, 32, double __vector(4)>(long, long) (this=<synthetic pointer>, this=<synthetic pointer>, col=<optimized out>, row=<optimized out>)
    at external/eigen/Eigen/src/Core/AssignEvaluator.h:652
#5  Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::assign_op<double, double>, 0>::assignPacketByOuterInner<32, 32, double __vector(4)>(long, long) (outer=0, inner=0, this=<synthetic pointer>) at external/eigen/Eigen/src/Core/AssignEvaluator.h:666
#6  Eigen::internal::copy_using_evaluator_innervec_CompleteUnrolling<Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::assign_op<double, double>, 0>, 0, 4>::run (kernel=<synthetic pointer>...) at external/eigen/Eigen/src/Core/AssignEvaluator.h:274
#7  Eigen::internal::dense_assignment_loop<Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::internal::assign_op<double, double>, 0>, 2, 2>::run (kernel=<synthetic pointer>...) at external/eigen/Eigen/src/Core/AssignEvaluator.h:468
#8  Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::internal::assign_op<double, double> > (func=..., src=..., dst=...)
    at external/eigen/Eigen/src/Core/AssignEvaluator.h:741
#9  Eigen::internal::Assignment<Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::internal::assign_op<double, double>, Eigen::internal::Dense2Dense, void>::run (func=...,
    src=..., dst=...) at external/eigen/Eigen/src/Core/AssignEvaluator.h:879
#10 Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::internal::assign_op<double, double> > (func=..., src=..., dst=...)
    at external/eigen/Eigen/src/Core/AssignEvaluator.h:836
#11 Eigen::internal::call_assignment<Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::internal::assign_op<double, double> >(Eigen::Matrix<double, 4, 1, 0, 4, 1>&, Eigen::Matrix<double, 4, 1, 0, 4, 1> const&, Eigen::internal::assign_op<double, double> const&, Eigen::internal::enable_if<!Eigen::internal::evaluator_assume_aliasing<Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::internal::evaluator_traits<Eigen::Matrix<double, 4, 1, 0, 4, 1> >::Shape>::value, void*>::type) (func=..., src=..., dst=...) at external/eigen/Eigen/src/Core/AssignEvaluator.h:804
#12 Eigen::internal::call_assignment<Eigen::Matrix<double, 4, 1, 0, 4, 1>, Eigen::Matrix<double, 4, 1, 0, 4, 1> > (src=..., dst=...) at external/eigen/Eigen/src/Core/AssignEvaluator.h:782
#13 Eigen::PlainObjectBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >::_set<Eigen::Matrix<double, 4, 1, 0, 4, 1> > (other=..., this=0x7f991a3fea80) at external/eigen/Eigen/src/Core/PlainObjectBase.h:714
#14 Eigen::Matrix<double, 4, 1, 0, 4, 1>::operator= (other=..., this=0x7f991a3fea80) at external/eigen/Eigen/src/Core/Matrix.h:208
#15 Eigen::QuaternionBase<Eigen::Quaternion<double, 0> >::operator= (other=..., this=0x7f991a3fea80) at external/eigen/Eigen/src/Geometry/Quaternion.h:490
#16 Eigen::Quaternion<double, 0>::operator= (other=..., this=0x7f991a3fea80) at external/eigen/Eigen/src/Geometry/Quaternion.h:240
#17 apollo::perception::onboard::StampedTransform::operator= (this=0x7f991a3fea60) at ./modules/perception/onboard/transform_wrapper/transform_wrapper.h:39
#18 apollo::perception::onboard::TransformCache::QueryTransform (this=this@entry=0x55d934ed7b48, timestamp=timestamp@entry=1637306695.0115578, transform=transform@entry=0x7f991a3fea60,
    max_duration=<optimized out>) at modules/perception/onboard/transform_wrapper/transform_wrapper.cc:111
#19 0x00007f9a2c92a896 in apollo::perception::onboard::TransformWrapper::GetSensor2worldTrans (this=0x55d934ed7ab0, timestamp=timestamp@entry=1637306695.0115578,
    sensor2world_trans=sensor2world_trans@entry=0x7f991a3fedc0, novatel2world_trans=novatel2world_trans@entry=0x0) at modules/perception/onboard/transform_wrapper/transform_wrapper.cc:196
#20 0x00007f9abc345cb5 in apollo::perception::onboard::FusionCameraDetectionComponent::InternalProc (this=this@entry=0x55d9375fa7e0,
    in_message=std::shared_ptr<const apollo::drivers::Image> (use count 4, weak count 0) = {...}, camera_name="left_front", error_code=error_code@entry=0x7f991a3ff04c, prefused_message=0x7f9aa40037a0,
    out_message=0x7f98e000d870) at modules/perception/onboard/component/fusion_camera_detection_component.cc:684
#21 0x00007f9abc348050 in apollo::perception::onboard::FusionCameraDetectionComponent::OnReceiveImage (this=0x55d9375fa7e0, message=std::shared_ptr<apollo::drivers::Image> (use count 4, weak count 0) = {...},
    camera_name="left_front") at modules/perception/onboard/component/fusion_camera_detection_component.cc:302
#22 0x00007f9abc2fb0cc in std::function<void (std::shared_ptr<apollo::drivers::Image> const&)>::operator()(std::shared_ptr<apollo::drivers::Image> const&) const (
    __args#0=std::shared_ptr<apollo::drivers::Image> (use count 4, weak count 0) = {...}, this=0x55d95024a430) at /usr/include/c++/7/bits/std_function.h:706
#23 apollo::cyber::croutine::RoutineFactory apollo::cyber::croutine::CreateRoutineFactory<apollo::drivers::Image, std::function<void (std::shared_ptr<apollo::drivers::Image> const&)> >(std::function<void (std::shared_ptr<apollo::drivers::Image> const&)>&&, std::shared_ptr<apollo::cyber::data::DataVisitor<apollo::drivers::Image, apollo::cyber::NullType, apollo::cyber::NullType, apollo::cyber::NullType> > const&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const (__closure=0x55d95024a420) at ./cyber/croutine/routine_factory.h:61
#24 0x00007f9abc2fb21c in std::_Function_handler<void (), apollo::cyber::croutine::RoutineFactory apollo::cyber::croutine::CreateRoutineFactory<apollo::drivers::Image, std::function<void (std::shared_ptr<apollo::drivers::Image> const&)> >(std::function<void (std::shared_ptr<apollo::drivers::Image> const&)>&&, std::shared_ptr<apollo::cyber::data::DataVisitor<apollo::drivers::Image, apollo::cyber::NullType, apollo::cyber::NullType, apollo::cyber::NullType> > const&)::{lambda()#1}::operator()() const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#25 0x00007f9ae72a421a in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/7/bits/std_function.h:706
#26 apollo::cyber::croutine::CRoutine::Run (this=<optimized out>) at ./cyber/croutine/croutine.h:143
#27 apollo::cyber::croutine::(anonymous namespace)::CRoutineEntry (arg=<optimized out>) at cyber/croutine/croutine.cc:40
#28 0x0000000000000000 in ?? ()
(gdb) f 18
#18 apollo::perception::onboard::TransformCache::QueryTransform (this=this@entry=0x55d934ed7b48, timestamp=timestamp@entry=1637306695.0115578, transform=transform@entry=0x7f991a3fea60,
    max_duration=<optimized out>) at modules/perception/onboard/transform_wrapper/transform_wrapper.cc:111
111        (*transform) = transforms_.back();
(gdb) l
106        return false;
107      }
108      AINFO << "wpwp - transform -- tag 1";
109      int size = static_cast<int>(transforms_.size());
110      if (size == 1) {
111        (*transform) = transforms_.back();
112        transform->timestamp = timestamp;
113        AINFO << "wpwp - use transform at " << transforms_.back().timestamp << " for "
114              << timestamp;
115      } else {
(gdb) p *transform
$1 = {timestamp = 1637306694.944916, translation = {
    m_coeffs = {<Eigen::PlainObjectBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::MatrixBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = {array = {
              435855.19397680881, 4436081.3530986561, 35.193619416984589}}}}, <No data fields>}},
  rotation = {<Eigen::QuaternionBase<Eigen::Quaternion<double, 0> >> = {<Eigen::RotationBase<Eigen::Quaternion<double, 0>, 3>> = {<No data fields>}, <No data fields>},
    m_coeffs = {<Eigen::PlainObjectBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<Eigen::MatrixBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<Eigen::DenseBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = {array = {
              6.9315210096659843e-310, 4.7430302000759668e-322, 1.5662907526462278e-313, 3.4584595208887258e-323}}}}, <No data fields>}}}
(gdb)

**Comment by daohu527** [comment]
Fixed in new version
