### ISSUE TITLE
Test actual sensor hardware with Apollo 6.0 in local computer

### ISSUE THREAD

**Issue by lhakim85** [ApolloAuto/apollo#14201]
It is possible to test actual sensor hardware such as lidar/camera/radar in local computer?
We manage to run Apollo6.0 in Lgslv simulator and manage to see all the sensor feed thru cyber_visualizer.
So can we test actual sensor also and see the feed thru cyber_visualizer?

Thanks

**Comment by daohu527** [comment]
Of course you can, but there are some differences between directly connecting the sensor and the simulator.

## diff

- **simulator** sends data to the computer by simulating the hardware, and the communication interface is socket.
- **Sensor** requires hardware driver to connect to computer. It reads and publishes messages through the corresponding bus. The good news is that apollo has already integrated these. The bad news is that you need to do some device adaptations. You can refer to the d-kit manual to complete these.

**Comment by lhakim85** [comment]
> Of course you can, but there are some differences between directly connecting the sensor and the simulator.
> 
> ## diff
> * **simulator** sends data to the computer by simulating the hardware, and the communication interface is socket.
> * **Sensor** requires hardware driver to connect to computer. It reads and publishes messages through the corresponding bus. The good news is that apollo has already integrated these. The bad news is that you need to do some device adaptations. You can refer to the d-kit manual to complete these.

thanks daohu527 for replying.
Can u point me the link to the d-kit manual.

Thanks alot

**Comment by daohu527** [comment]
Yes, you can treat the industrial computer as your own computer and pay attention to the linux device driver number.

**Comment by lhakim85** [comment]
> Yes, you can treat the industrial computer as your own computer and pay attention to the linux device driver number.

Yes, this is what we do here. We try to setup all the hardware in the lab first before install it in the actual car.

We try to follow this guide [https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md](url)

But cannot found setting for vehicle like in the guide (pic in the guide below)
![apollo setup](https://user-images.githubusercontent.com/10070989/142968654-c3ad1bc6-b91f-477d-8ba5-79739fb24cc8.png)

This is my seting(my Apollo seting)
![camera_setup1](https://user-images.githubusercontent.com/10070989/142968730-91910620-fdd1-418b-a588-0bebd363c67f.png)


Can u advice which part that I'm left

Thanks alot

**Comment by daohu527** [comment]
In fact, this is a bit complicated, because the vehicle configuration will affect multiple modules, I think you can choose `mkz_example` first, and then see if it works

**Comment by lhakim85** [comment]
Thanks @daohu527 for the reply.

We already try several setting in the Apollo6, but still cannot up the camera. The Camera toggle button in the Module Controller cannot turn On. 

On the other part, when refer to the D-kit manual for sensor hardware testing, GNSS is the compulsory hardware for other hardware to turn on (except Camera). Am I right?

Is there any way to test for example Lidar/radar without the GNSS?

**Comment by daohu527** [comment]
You should do it step by step, preferably focusing on a certain sensor.

For example, you can first determine whether the driver can work, and then start the function of the module. Even without GNSS, I think it should work. You'd better focus on specific problems and narrow the scope.

**Comment by lhakim85** [comment]
thanks @daohu527 for the reply.

For lidar, here the step that we do

1. check the data port and telemetry port for velodyne16_front_center
2. run mainboard -d modules/drivers/lidar/velodyne/dag/vedyne16.dag
3. see the feed thru cyber_visualizer

We manage to see the topic in cyber_visualizer, but no output 

![no output](https://user-images.githubusercontent.com/10070989/143373801-bbf1443d-6d15-4f1c-b627-0816c26eb5f7.png)

**Comment by daohu527** [comment]
## steps
there are several things need to check.
1. Do you use velodyne lidar, if true go to step 2
2. Check the scan_channel , in other words check whether the topic of `/apollo/sensor/lidar16/front/center/Scan` has output. Then check `/apollo/sensor/lidar16/front/center/PointCloud2` which parses the raw data of the point cloud into a Cartesian coordinate system
3. Enable the tf module, otherwise the lidar will not be able to perform motion compensation

## your case
seems you can't find `/apollo/sensor/lidar16/front/center/PointCloud2` in step2, check `/apollo/sensor/lidar16/front/center/Scan` if not. Then check the pcap with lidar, or find if there are some error in log `data/log`

**Comment by lhakim85** [comment]
> ## steps
> there are several things need to check.
> 
> 1. Do you use velodyne lidar, if true go to step 2
> 2. Check the scan_channel , in other words check whether the topic of `/apollo/sensor/lidar16/front/center/Scan` has output. Then check `/apollo/sensor/lidar16/front/center/PointCloud2` which parses the raw data of the point cloud into a Cartesian coordinate system
> 3. Enable the tf module, otherwise the lidar will not be able to perform motion compensation
> 
> ## your case
> seems you can't find `/apollo/sensor/lidar16/front/center/PointCloud2` in step2, check `/apollo/sensor/lidar16/front/center/Scan` if not. Then check the pcap with lidar, or find if there are some error in log `data/log`

How to check topic of /apollo/sensor/lidar16/front/center/Scan has output?
In our vizualiser, the topic is there, but in the pointcloud2, only  2 topic (refer pic)

![image](https://user-images.githubusercontent.com/10070989/143380370-cf6ff05a-ff15-4322-8071-952c10621657.png)


We also do tcp dump, and the packet received
![image](https://user-images.githubusercontent.com/10070989/143380459-b5e4c45e-62e0-4a35-824f-c57847770cd6.png)

when we check the log, still basetime is zero although we already make the use_gps_time:false
![image](https://user-images.githubusercontent.com/10070989/143380557-da6bf460-8177-4315-957b-c87ce6afe778.png)

**Comment by daohu527** [comment]
you can use `cyber_monitor` to check the both message, maybe just a problem with the visualization I mean `cyber_visualizer`

**Comment by lhakim85** [comment]
> you can use `cyber_monitor` to check the both message, maybe just a problem with the visualization I mean `cyber_visualizer`


Seem that /lidar16/front/center/Scan has output, only when we make false on gps and poll_sync, but still no output at pointcloud
![image](https://user-images.githubusercontent.com/10070989/143387793-b4788666-52d5-4c33-8c0a-0b2c6ab4519a.png)

**Comment by lhakim85** [comment]
Update:
Manage to feed camera and lidar thru mainboard
For lidar, need to edit on use_gps_time & use_poll_sync to false if no GPS,
and edit on velodyne.16dag line 22 to **readers {channel: "/apollo/sensor/lidar16/front/center/Scan"}**

For camera, we copy driver from Apollo5 because we unsuccessfully debug it.

Now need to know how to run this module on Apollo dashboard

Thanks @daohu527

**Comment by daohu527** [comment]
1. The config below should be `/apollo/sensor/lidar16/front/center/Scan` which set in `velodyne16_front_center_conf.pb.txt`'s scan_channel
https://github.com/ApolloAuto/apollo/blob/673e9585ebdd97005e2fb1707ffcc4aff0abac12/modules/drivers/lidar/velodyne/dag/velodyne16.dag#L22

2. I don’t know what is the use of setting the camera module like this, and there are some problems with the 6.0 vision module for now. I think you can start by reading the image.

**Comment by lhakim85** [comment]
> 1. The config below should be `/apollo/sensor/lidar16/front/center/Scan` which set in `velodyne16_front_center_conf.pb.txt`'s scan_channel
>    https://github.com/ApolloAuto/apollo/blob/673e9585ebdd97005e2fb1707ffcc4aff0abac12/modules/drivers/lidar/velodyne/dag/velodyne16.dag#L22

After we change this config, then we get the output.

> 2. I don’t know what is the use of setting the camera module like this, and there are some problems with the 6.0 vision module for now. I think you can start by reading the image.

Noted, but any different between camera module 6.0 and 5.0? 

And, can u point me where is the script/backend that generate the dashboard?

**Comment by daohu527** [comment]
The dashboard of the camera is configured in `modules\dreamview\conf\hmi_modes`

**Comment by lhakim85** [comment]
@daohu527, how to visualize the output for example if we run 

`mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag` 

Can we see the realtime output in the screen

**Comment by daohu527** [comment]
@lhakim85 I need to check it. I am not very sure about this function, there are 2 questions.
1. Camera module after 5.5 may need some adaptations and modifications then can work
2. Whether the detection frame of the picture is displayed needs to be confirmed, but the lidar will definitely

**Comment by lhakim85** [comment]
Thanks @daohu527 

> Camera module after 5.5 may need some adaptations and modifications then can work

Yes, that's why we take camera module 5.0, and run with Apollo6.0, so that we can test our custom perception dataset

> Whether the detection frame of the picture is displayed needs to be confirmed, but the lidar will definitely

For lidar, yes we manage to see the output display.
So currently we try to see the detection frame of the perception camera and trafficlight perception

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
