### ISSUE TITLE
build error    ERROR: An error occurred during the fetch of repository 'local_config_cuda':

### ISSUE THREAD

**Issue by KinkangLiu** [ApolloAuto/apollo#14200]
### System information
Linux Ubuntu 18.04
- **Apollo installed from (source)
- **Apollo version ( 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I have installed CUDA 10.2 and can find cuda.h in the usr / local / cuda-10.2/include directory. But whether I use build or build_ GPU will report the same error.    ERROR: An error occurred during the fetch of repository 'local_config_cuda'

### Supporting materials (screenshots, command lines, code/script snippets):

[@in-dev-docker:/apollo]$ ./apollo.sh build # 编译apollo源代码
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-11-19-ae651cbb0d
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210517_1712
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[ OK ] Running GPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview: 
[INFO]     USE_GPU: 1  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=gpu
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
(03:20:15) WARNING: The following configs were expanded more than once: [gpu, cuda, using_cuda, tensorrt]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
(03:20:15) INFO: Current date is 2021-11-21
(03:20:18) INFO: Repository local_config_cuda instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:83:19: in apollo_repositories
Repository rule cuda_configure defined at:
  /apollo/third_party/gpus/cuda_configure.bzl:1266:33: in <toplevel>
(03:20:18) ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 1237, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 836, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 530, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 507, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 501, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/apollo/tools/platform/common.bzl", line 166, column 13, in execute
		fail(
Error in fail: Repository command failed
Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/usr/local/cuda-10.2'
(03:20:18) ERROR: no such package '@local_config_cuda//cuda': Repository command failed
Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/usr/local/cuda-10.2'
(03:20:18) INFO: Elapsed time: 4.685s
(03:20:18) INFO: 0 processes.
(03:20:18) FAILED: Build did NOT complete successfully (18 packages loaded)
    currently loading: modules/drivers/canbus/can_client/esd ... (146 packages\
)

**Comment by KinkangLiu** [comment]
I have solved!  I running `./apollo.sh config -n` in the apollo container, then build apollo successfully.

**Comment by McGrady-175** [comment]
> I have solved! I running `./apollo.sh config -n` in the apollo container, then build apollo successfully. But I dont know why.

Thank u so so so so much !  good bro !!!!

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
