### ISSUE TITLE
How can get rotated camera extrinsic?

### ISSUE THREAD

**Issue by Linsha350** [ApolloAuto/apollo#14202]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I just add extra camera which look both sides with 30 degree
Same Position, Same Camera, just yaw is different.
![Screenshot from 2021-11-23 14-07-54](https://user-images.githubusercontent.com/81678524/142974179-8b729c51-0ca9-4fa5-b2be-f5433f144c74.png)

However, the extrinsic calibration is really hard.
First, I copy yaml extrinsic files
/apollo/modules/perception/data/params/front_6mm_extrinsics.yaml
![Screenshot from 2021-11-23 14-14-31](https://user-images.githubusercontent.com/81678524/142974618-9828421f-4e9f-4f23-87b4-304fa603a6d5.png)
![Screenshot from 2021-11-23 14-14-53](https://user-images.githubusercontent.com/81678524/142974622-b8685ba1-a8a9-42c4-bfe1-6f86caae0031.png)
But, the above result (front camera) and below result (side camera) shows different position with same cars

I think it needs to just rotate... But the extrinsic value change is really hard.

![Screenshot from 2021-11-23 14-18-37](https://user-images.githubusercontent.com/81678524/142974780-dc454074-440a-44cf-89e7-0611a917ca2d.png)
Almost, when I just change the extrinsic value, the transformer gives error...

How can I get extrinsic for just rotated 30 degree camera?

**Comment by daohu527** [comment]
Can you point out how you set the external camera parameters? This can better detect problems

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
