### ISSUE TITLE
Module Localization and Perception build failed on Nvidia Xavier paltform

### ISSUE THREAD

**Issue by OrangeSoda1** [ApolloAuto/apollo#14214]
I have successfully built other modules on Xavier,but can't built Localization and Perception modules.
Localization part says " localization_msf/gnss_strtct.h: No such file or directory "
As for Perception part is some  compile error.
What solution should I take to build these two modules?

Localization module failed:
![localization build失败](https://user-images.githubusercontent.com/57565503/144374798-3aea8744-bd36-4bb2-9718-8c33690ef09e.png)

Perception module failed:
![perception build失败](https://user-images.githubusercontent.com/57565503/144374879-5d39ca8b-9458-4de5-876d-2d3646abffce.png)

**Comment by daohu527** [comment]
* What msf provides is the "so" file, so I think it seems not feasible to recompile
* The perception module contains a large number of third-party libraries, so there may be some compatibility issues.

I suggest case by case to complete this task
