### ISSUE TITLE
Cuda Error in allocate: 2 (GPU memory allocation failed during allocation of workspace. Try decreasing batch size.)

### ISSUE THREAD

**Issue by HuangCongQing** [ApolloAuto/apollo#14216]
![image](https://user-images.githubusercontent.com/20675770/144747318-788a14b5-9959-4cc4-b2f8-312b1e7b1941.png)

Where should I modify **batch_size** ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
