### ISSUE TITLE
Apollo collides with a bus while turning left in SVL

### ISSUE THREAD

**Issue by AIasd** [ApolloAuto/apollo#14212]
We tested Apollo(master branch) in the map Borregas Ave in SVL2021.3 with generated traffic.

From the recording(see supporting materials), the ego car's prediction on the school bus was wrong initially and it seems too late to be correct later which resulted in a collision. 

We wonder if this is more like a simulation artifact or a potential Apollo's perception/prediction issue. Thank you!

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- Follow the [SVL official instruction on "Running latest Apollo with SVL Simulator" ](https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/).
- Run SVL in API only mode.
- Run a python script generating traffic in SVL.

### Supporting materials (screenshots, command lines, code/script snippets):
[video](https://vimeo.com/651400405)

**Comment by ntutangyun** [comment]
seems to be a perception issue with the truck. I think the predicted trajectory being incorrect probably due to the inconsistent perception results.
