### ISSUE TITLE
Enable perception with a single VLP-16 LiDAR

### ISSUE THREAD

**Issue by rshnvjy** [ApolloAuto/apollo#14215]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux, Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:  APOLLO_VERSION: master-2021-11-01-539839c714

### Steps to reproduce the issue:
- I am trying to connect a physical Velodyne VLP-16 LiDAR in order to enable perception. All of the config files suggest that the VLP-16 alone is not used (or at least recommended) for perception as the configuration files have been preset to use the VLS-128 as the main LiDAR along with multiple VLP-16s surrounding it. Is it possible to use just a single VLP-16 for perception without any sensor fusion (and by bypassing the fusion compensator modules entirely)?
- There is limited documentation available on the usage of the VLP-16 standalone or even on the usage of slightly different sensor configurations other than what is officially supported. It would be great if there is some guide or documentation detailing how the LiDAR drivers work and steps to enable our own custom sensor configuration (either a single LiDAR or more).

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
