### ISSUE TITLE
write function in socket_can_client_raw.cc

### ISSUE THREAD

**Issue by NianchenSHEN** [ApolloAuto/apollo#14227]
### System information

- Linux Ubuntu 18.04:
- Apollo installed from source:
- Apollo version r5.5.0:

### Supporting materials:

- I met an issue about 'send msg failed' in canbus module, and located the error info was from the following function, but I actually don't know how to understand it, especially the 'write' function:
` int ret = static_cast<int>(
        write(dev_handler_, &send_frames_[i], sizeof(send_frames_[i])));
    if (ret <= 0) {
      AERROR << "send message failed, error code: " << ret;
      return ErrorCode::CAN_CLIENT_ERROR_BASE;`

any supports to learn about this function? than I can go deeper to analyze the further cause.

**Comment by daohu527** [comment]
The `write` function will send data to socket. You can ref to [link](https://www.ibm.com/docs/en/zos/2.2.0?topic=functions-write-write-data-file-socket) and [man write](https://man7.org/linux/man-pages/man2/write.2.html)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
