### ISSUE TITLE
Starting a module in a Script

### ISSUE THREAD

**Issue by julian-r** [ApolloAuto/apollo#14228]
I am looking for a way to start modules via script.

**Comment by AIasd** [comment]
You can check out [Dreamview API](https://www.svlsimulator.com/docs/python-api/dreamview-api/) for that purpose.

**Comment by daohu527** [comment]
there is already some example in the code. for example

https://github.com/ApolloAuto/apollo/blob/master/scripts/control.sh

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
