### ISSUE TITLE
E: Package 'gdbserver' has no installation candidate

### ISSUE THREAD

**Issue by EthanCodesss** [ApolloAuto/apollo#14225]
Inside the docker, 'sudo apt-get install gdbserver'.
Get the error message:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gdbserver is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gdbserver' has no installation candidate`

Why is it? Please give me some instructions, thanks in advance!!

**Comment by daohu527** [comment]
You shold first update apt database
```
sudo apt-get update
```
