### ISSUE TITLE
Traffic light stop line issue

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#14221]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:

![Screenshot from 2021-12-07 08-37-27](https://user-images.githubusercontent.com/18480213/145000807-e3ad8be8-7b0a-4848-97b5-08bbee37e11e.png)

As shown in the picture above, there is an issue where the stop line of the traffic light does not stop normally.

Traffic light stop line is x:834083, y:185
![Screenshot from 2021-12-07 08-27-06](https://user-images.githubusercontent.com/18480213/145001408-60c543e0-05c8-4bbb-93f0-218339d93a25.png)

But Decision stop_point is x:834080 y:214
Why is it different?
Isn't the stop line of a traffic light a reference on the map?
In the opposite direction, it normally stops at the stop line.

![Screenshot from 2021-12-07 09-16-01](https://user-images.githubusercontent.com/18480213/145001096-0b7e815d-603b-4e14-9b98-4c63a3d7ab82.png)

Thanks you.

**Comment by cicelprg** [comment]
您好,已经收到您的来信,我会尽快与您取得联系。

**Comment by Jackie-Bai888** [comment]
@phs4530 Have you solved the problem that Apollo does not stop at the stop line?

**Comment by phs4530** [comment]
@Jackie-Bai888 Hello, It didn't work. The conversion tool provided by Apollo had problems 3 years ago, but it may work fine now.
The problem with the stop line not working properly was caused by the map not being converted properly when converted from RoadRunner to Apollo map.
