### ISSUE TITLE
"Failed to start can client" when adapt the CAN matrix to a new vehicle 

### ISSUE THREAD

**Issue by NianchenSHEN** [ApolloAuto/apollo#14223]
### System information

- Ubuntu 18.04
- installed from source
- based on Apollo r5.5.0

### Steps to reproduce the issue:
- follow the Apollo official guide to generate the new vehicle's protocol and folder
- change the controller.cc to adapt the different CAN ID and messages
- compile the binary
- compile pass
- launch SocketCAN
- launch scripts/canbus.sh or scripts/bootstrap.sh
- launch cyber_monitor to check the chassis and chassis_details messages

### Supporting materials (screenshots, command lines, code/script snippets):
- IPC: Nuvo-8108GC
- CAN CARD: EMUC-B202
- CAN Driver: SocketCAN

1. I used the can-utils to make sure there was chassis message output from the can0 device;

2. after launching the bootstrap.sh and cyber_monitor, I found that there was no chassis_details options after I enable the "enable_chassis_detail_pub" under the ~apollo/modules/canbus/conf/canbus.conf
Do I need to do further changes to enable the "chassis_detail" channel in cyber_monitor based on r5.5.0?  

3. I exported the canbus.log from the ~apollo/data/log, then found the error:

> Running on machine: in_dev_docker
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> I1209 14:08:41.914945 10550 class_loader_utility.h:78] registerclass:CanbusComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/canbus/libcanbus.so
> I1209 14:08:41.918735 10550 canbus_component.cc:47] The canbus conf file is loaded: /apollo/modules/canbus/conf/canbus_conf.pb.txt
> I1209 14:08:41.918745 10550 canbus_component.cc:58] Can client is successfully created.
> I1209 14:08:41.918756 10550 vehicle_factory.cc:78] successfully created vehicle factory with brand: VV6
> max_enable_fail_attempt: 5
> driving_mode: COMPLETE_AUTO_DRIVE
> I1209 14:08:41.918771 10550 canbus_component.cc:74] Message manager is successfully created.
> I1209 14:08:41.918772 10550 canbus_component.cc:81] The can receiver is successfully initialized.
> I1209 14:08:41.918773 10550 canbus_component.cc:88] The can sender is successfully initialized.
> I1209 14:08:41.918776 10550 canbus_component.cc:95] The vehicle controller is successfully created.
> I1209 14:08:41.918789 10550 canbus_component.cc:103] The vehicle controller is successfully initialized with canbus conf as : brand: VV6 max_enable_fail_attempt: 5 driving_mode: COMPLETE_AUTO_DRIVE
> E1209 14:08:41.931571 10550 canbus_component.cc:140] Failed to start can client

Located the error from the canbus_component.cc, and the function was:

>   if (can_client_->Start() != ErrorCode::OK) {
>     AERROR << "Failed to start can client";
>     return false;
>   }
>   AINFO << "Can client is started.";

Find the can_client_ function from the ~modules/drivers/canbus/can_client/socket_can_client_raw.cc, however, there was no further log for me to debug deeper in this module, where can I find the log from socket_can_client_raw.cc? 

Any other suggestions to debug this issue?

**Comment by xjhsummer1024** [comment]
i have the same issue!!!!!

**Comment by daohu527** [comment]
You can check the error message in `data\log\mainboard.info`

**Comment by NianchenSHEN** [comment]
> You can check the error message in `data\log\mainboard.info`

hello, thank u for your reply, after checking the log of mainboard.info, I found the new error about the "ioctl error", but I am not familiar with the ioctl function, any suggestions about this issue?
The mainboard error log is:

> E1210 13:55:43.327481  8165 socket_can_client_raw.cc:117] ioctl error

> E1210 13:55:43.327934  8165 module_controller.cc:67] Failed to load module: /apollo/modules/canbus/dag/canbus.dag

> E1210 13:55:43.328281  8165 mainboard.cc:43] module start error.

Located the function is:

> 
>   const std::string can_name = absl::StrCat(interface_prefix, port_);
>   std::strncpy(ifr.ifr_name, can_name.c_str(), IFNAMSIZ);
>   if (ioctl(dev_handler_, SIOCGIFINDEX, &ifr) < 0) {
>     AERROR << "ioctl error";
>     return ErrorCode::CAN_CLIENT_ERROR_BASE;
>   }

**Comment by Xxfore** [comment]
> > You can check the error message in `data\log\mainboard.info`
> 
> hello, thank u for your reply, after checking the log of mainboard.info, I found the new error about the "ioctl error", but I am not familiar with the ioctl function, any suggestions about this issue? The mainboard error log is:
> 
> > E1210 13:55:43.327481  8165 socket_can_client_raw.cc:117] ioctl error
> 
> > E1210 13:55:43.327934  8165 module_controller.cc:67] Failed to load module: /apollo/modules/canbus/dag/canbus.dag
> 
> > E1210 13:55:43.328281  8165 mainboard.cc:43] module start error.
> 
> Located the function is:
> 
> > const std::string can_name = absl::StrCat(interface_prefix, port_);
> > std::strncpy(ifr.ifr_name, can_name.c_str(), IFNAMSIZ);
> > if (ioctl(dev_handler_, SIOCGIFINDEX, &ifr) < 0) {
> > AERROR << "ioctl error";
> > return ErrorCode::CAN_CLIENT_ERROR_BASE;
> > }

Did you probe emuc2socketcan kernel module and enable the can card connection?

**Comment by Xxfore** [comment]
> > You can check the error message in `data\log\mainboard.info`
> 
> hello, thank u for your reply, after checking the log of mainboard.info, I found the new error about the "ioctl error", but I am not familiar with the ioctl function, any suggestions about this issue? The mainboard error log is:
> 
> > E1210 13:55:43.327481  8165 socket_can_client_raw.cc:117] ioctl error
> 
> > E1210 13:55:43.327934  8165 module_controller.cc:67] Failed to load module: /apollo/modules/canbus/dag/canbus.dag
> 
> > E1210 13:55:43.328281  8165 mainboard.cc:43] module start error.
> 
> Located the function is:
> 
> > const std::string can_name = absl::StrCat(interface_prefix, port_);
> > std::strncpy(ifr.ifr_name, can_name.c_str(), IFNAMSIZ);
> > if (ioctl(dev_handler_, SIOCGIFINDEX, &ifr) < 0) {
> > AERROR << "ioctl error";
> > return ErrorCode::CAN_CLIENT_ERROR_BASE;
> > }

Did you check the can interface name which used for ioctl?
`const std::string can_name = absl::StrCat(interface_prefix, port_);
std::strncpy(ifr.ifr_name, can_name.c_str(), IFNAMSIZ);
if (ioctl(dev_handler_, SIOCGIFINDEX, &ifr) < 0) {`

**Comment by daohu527** [comment]
> I used the can-utils to make sure there was chassis message output from the can0 device;

I check the config in modules\canbus\conf\canbus_conf.pb.txt and the ifr.ifr_name is already `can0`, you can check it again. 

and you can use below code print out the error msg, [link](https://man7.org/linux/man-pages/man2/ioctl.2.html)
```c++
  if (ioctl(dev_handler_, SIOCGIFINDEX, &ifr) < 0) {
    AERROR << "ioctl error: " << strerror(errno);
    return ErrorCode::CAN_CLIENT_ERROR_BASE;
  }
```

**Comment by NianchenSHEN** [comment]
@daohu527 @Xxfore 
I found that in r5.0.0 branch, ~apollo/modules/canbus/conf/canbus_conf.pb.txt, it didn't check the interface in "can_card_parameter", only "branc, type and channel_id"

> vehicle_parameter {
>   brand: VV6
>   max_enable_fail_attempt: 5
>   driving_mode: COMPLETE_AUTO_DRIVE
> }
> 
> can_card_parameter {
>   brand: SOCKET_CAN_RAW
>   type: USB_CARD
>   channel_id: CHANNEL_ID_ZERO
> }
> 
> enable_debug_mode: false
> enable_receiver_log: false
> enable_sender_log: false

but in r5.5.0 branch, they add the interface check:

> vehicle_parameter {
>   brand: VV6
>   max_enable_fail_attempt: 5
>   driving_mode: COMPLETE_AUTO_DRIVE
> }
> 
> can_card_parameter {
>   brand: SOCKET_CAN_RAW
>   type: USB_CARD
>   channel_id: CHANNEL_ID_ZERO
>   interface: SLCAN
> }
> 
> enable_debug_mode: false
> enable_receiver_log: false
> enable_sender_log: false

So I remove the interface in canbus_conf.pb.txt, and test again, the "ioctl error" disappeared, that was quite strange!
It means that canbus.sh can run properly without check CAN interface?

**Comment by Xxfore** [comment]
> @daohu527 @Xxfore I found that in r5.0.0 branch, ~apollo/modules/canbus/conf/canbus_conf.pb.txt, it didn't check the interface in "can_card_parameter", only "branc, type and channel_id"
> 
> > vehicle_parameter {
> > brand: VV6
> > max_enable_fail_attempt: 5
> > driving_mode: COMPLETE_AUTO_DRIVE
> > }
> > can_card_parameter {
> > brand: SOCKET_CAN_RAW
> > type: USB_CARD
> > channel_id: CHANNEL_ID_ZERO
> > }
> > enable_debug_mode: false
> > enable_receiver_log: false
> > enable_sender_log: false
> 
> but in r5.5.0 branch, they add the interface check:
> 
> > vehicle_parameter {
> > brand: VV6
> > max_enable_fail_attempt: 5
> > driving_mode: COMPLETE_AUTO_DRIVE
> > }
> > can_card_parameter {
> > brand: SOCKET_CAN_RAW
> > type: USB_CARD
> > channel_id: CHANNEL_ID_ZERO
> > interface: SLCAN
> > }
> > enable_debug_mode: false
> > enable_receiver_log: false
> > enable_sender_log: false
> 
> So I remove the interface in canbus_conf.pb.txt, and test again, the "ioctl error" disappeared, that was quite strange! It means that canbus.sh can run properly without check CAN interface?

I cant find the canbus_conf.pb.txt file for VV6, im not sure if it's added by yourself.
As check the interface select logic, if not specified interface , it should use "can" as default.
How about change field "interface: " from "SLCAN" to "NATIVE" ?

**Comment by NianchenSHEN** [comment]
> > @daohu527 @Xxfore I found that in r5.0.0 branch, ~apollo/modules/canbus/conf/canbus_conf.pb.txt, it didn't check the interface in "can_card_parameter", only "branc, type and channel_id"
> > > vehicle_parameter {
> > > brand: VV6
> > > max_enable_fail_attempt: 5
> > > driving_mode: COMPLETE_AUTO_DRIVE
> > > }
> > > can_card_parameter {
> > > brand: SOCKET_CAN_RAW
> > > type: USB_CARD
> > > channel_id: CHANNEL_ID_ZERO
> > > }
> > > enable_debug_mode: false
> > > enable_receiver_log: false
> > > enable_sender_log: false
> > 
> > 
> > but in r5.5.0 branch, they add the interface check:
> > > vehicle_parameter {
> > > brand: VV6
> > > max_enable_fail_attempt: 5
> > > driving_mode: COMPLETE_AUTO_DRIVE
> > > }
> > > can_card_parameter {
> > > brand: SOCKET_CAN_RAW
> > > type: USB_CARD
> > > channel_id: CHANNEL_ID_ZERO
> > > interface: SLCAN
> > > }
> > > enable_debug_mode: false
> > > enable_receiver_log: false
> > > enable_sender_log: false
> > 
> > 
> > So I remove the interface in canbus_conf.pb.txt, and test again, the "ioctl error" disappeared, that was quite strange! It means that canbus.sh can run properly without check CAN interface?
> 
> I cant find the canbus_conf.pb.txt file for VV6, im not sure if it's added by yourself. As check the interface select logic, if not specified interface , it should use "can" as default. How about change field "interface: " from "SLCAN" to "NATIVE" ?

- the default VV6 vehicle was the "WEY" module in the code, but it was for 2020 version, I just have the the 2019 version in hand;
- I had changed the interface from the three choices (SLCAN, NATIVE and VIRTUAL), none of them worked.

**Comment by denyz** [comment]
I have the same issue!!!!!
I found this https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Waypoint_Following/localization_configuration_cn.md
why “imu->ttyACM0” ? Newton-M2 imu need the CAN connection?

**Comment by denyz** [comment]
have a try
https://github.com/ApolloAuto/apollo/issues/11980

**Comment by denyz** [comment]
try
https://github.com/ApolloAuto/apollo/issues/11980
