### ISSUE TITLE
GNSS Ublox parser - Udp stream/ failed to create parser

### ISSUE THREAD

**Issue by wijdim** [ApolloAuto/apollo#14226]
- Linux Ubuntu 18.04
- **Apollo installed from source 
- **Apollo version master
==>
I want to send ubx file data in udp protocol as input to the localization module. For That I followed the indicated steps in this link https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_gps_receiver.md 
These instructions are not complete and i need to implement the ubx_parser class as done for novatel. Any help or parser that is provided would be greatly appreciated. 
Also I need to know how could i send the data (ubx file ) by udp protocol unstead of having the data from the connecting device? 

Thank you.

**Comment by wijdim** [comment]
Please answer.
Thank you

**Comment by wijdim** [comment]
???

**Comment by daohu527** [comment]
What is your real problem then? 
Through your description, your needs are very unique, you may need to do some experiments, it is best to ask **specific questions**. 

For example, if you need to send a file, you can check the UDP socket related information, and if you encounter an error, ask again. At least I know that no one will complete the code for you directly!

Hope this helps you！

**Comment by wijdim** [comment]
@daohu527 Thank you for your answer,  My question precisely is How can i send data in localization module using Udp protocole, Can you share with me the related information of UDP socket?

**Comment by daohu527** [comment]
There are many examples of socket communication. for examle [link](https://www.geeksforgeeks.org/udp-server-client-implementation-c/)

**Comment by wijdim** [comment]
Thank you for your answer, I did the necessary changes on gnss in apollo but still fail while creating the stream (can't receive the data sent in udp protocol) and i have this error in launch : 
![Capture-git](https://user-images.githubusercontent.com/96061375/147461729-d40bb516-6ab8-460e-a8c7-ee65b3cf382d.PNG)

**Comment by daohu527** [comment]
The error message reminds you that there are duplicate nodes.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
