### ISSUE TITLE
How to select vechile and open modules automaticlly in dreamview by ./bootstrap.sh

### ISSUE THREAD

**Issue by ryanncheng** [ApolloAuto/apollo#14231]
hello, i want to know how to select vechile and open modules automaticlly in dreamview by ./bootstrap.sh. instead of click on the web

**Comment by daohu527** [comment]
Doesn’t seem to support it at the moment. Although there are some ways to achieve it, such as passing in parameters, or through default configuration

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
