### ISSUE TITLE
How to run darkscnn lane detector test.cc

### ISSUE THREAD

**Issue by sychou11** [ApolloAuto/apollo#14234]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: opt_gpu
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**: 

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- 
1.  `bash docker/scripts/dev_start.sh`
2.  `bash docker/scripts/dev_into.sh`
3.  `bash apollo.sh build_opt_gpu`
4.   `bazel test //modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test`
5.  turned out ERROR: no such package 'modules/perception/camera/test': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
6.  I found there is no file named BUILD in the path /modules/perception/camera/test/ actually. But there is file named BUILD_. So I renamed it to BUILD.
7.  `bash apollo.sh build_opt_gpu`
8.  turned out 
(06:42:13) ERROR: /apollo/modules/perception/camera/test/BUILD:6:8: no such package '@caffe//': The repository '@caffe' could not be resolved and referenced by '//modules/perception/camera/test:camera_app_obstacle_camera_perception_test'
(06:42:13) ERROR: /apollo/modules/perception/camera/test/BUILD:6:8: no such target '@opencv//:opencv': target 'opencv' not declared in package '' defined by /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/opencv/BUILD.bazel and referenced by '//modules/perception/camera/test:camera_app_obstacle_camera_perception_test'
(06:42:13) ERROR: Analysis of target '//modules/perception/camera/test:camera_app_obstacle_camera_perception_test' failed; build aborted: Analysis failed

How can I fill this problem and run camera_lib_lane_detector_darkscnn_lane_detector_test.cc ?

**Comment by Xxfore** [comment]
You should correct the build script compatibility for camera unit test after rename BUILD_ to BUILD.
As you mentioned , 
   "no such target '@opencv//:opencv': target 'opencv' not declared in package "
You can try to modify dependency from "@opencv" to specified opencv lib which used by unit test, such as "@opencv//:core", "@opencv//:videoio" and so on.

thx.

**Comment by sychou11** [comment]
> You should correct the build script compatibility for camera unit test after rename BUILD_ to BUILD. As you mentioned , "no such target '@opencv//:opencv': target 'opencv' not declared in package " You can try to modify dependency from "@opencv" to specified opencv lib which used by unit test, such as "@opencv//:core", "@opencv//:videoio" and so on.
> 
> thx.

Hi, Thank for your reply. I just modify this code as you say:
`cc_test(
    name = "camera_lib_lane_detector_darkscnn_lane_detector_test",
    size = "medium",
    srcs = ["camera_lib_lane_detector_darkscnn_lane_detector_test.cc"],
    deps = [
        "//cyber",
        "//modules/perception/base",
        "//modules/perception/camera/lib/lane/detector/darkSCNN:darkSCNN_lane_detector",
        "//modules/perception/common/io:io_util",
        "@com_google_googletest//:gtest_main",
        "@opencv//:core",
    ],
)`

Then I run:
`bazel test --config=unit_test //modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test`

However, it turned out to be the same.
(03:00:15) INFO: Invocation ID: 1a7b44e4-9f97-4646-a91b-5573ab99f865
(03:00:15) INFO: Current date is 2021-12-21
(03:00:15) ERROR: /apollo/modules/perception/camera/test/BUILD:320:8: no such target '@opencv//:opencv': target 'opencv' not declared in package '' defined by /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/opencv/BUILD.bazel and referenced by '//modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test'
(03:00:15) ERROR: Analysis of target '//modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test' failed; build aborted: Analysis failed
(03:00:15) INFO: Elapsed time: 0.145s
(03:00:15) INFO: 0 processes.
(03:00:15) FAILED: Build did NOT complete successfully (0 packages loaded, 0 t\
(03:00:15) FAILED: Build did NOT complete successfully (0 packages loaded, 0 t\
argets configured)

It seems nothing has changed.

**Comment by Xxfore** [comment]
> > You should correct the build script compatibility for camera unit test after rename BUILD_ to BUILD. As you mentioned , "no such target '@opencv//:opencv': target 'opencv' not declared in package " You can try to modify dependency from "@opencv" to specified opencv lib which used by unit test, such as "@opencv//:core", "@opencv//:videoio" and so on.
> > thx.
> 
> Hi, thanks for your reply. I just modify this code as you say: `cc_test( name = "camera_lib_lane_detector_darkscnn_lane_detector_test", size = "medium", srcs = ["camera_lib_lane_detector_darkscnn_lane_detector_test.cc"], deps = [ "//cyber", "//modules/perception/base", "//modules/perception/camera/lib/lane/detector/darkSCNN:darkSCNN_lane_detector", "//modules/perception/common/io:io_util", "@com_google_googletest//:gtest_main", "@opencv//:core", ], )`
> 
> Then I run: `bazel test --config=unit_test //modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test`
> 
> However, it still turned out to be the following ERROR:
> 
> (03:00:15) INFO: Invocation ID: 1a7b44e4-9f97-4646-a91b-5573ab99f865 (03:00:15) INFO: Current date is 2021-12-21 (03:00:15) ERROR: /apollo/modules/perception/camera/test/BUILD:320:8: no such target '@opencv//:opencv': target 'opencv' not declared in package '' defined by /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/opencv/BUILD.bazel and referenced by '//modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test' (03:00:15) ERROR: Analysis of target '//modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test' failed; build aborted: Analysis failed (03:00:15) INFO: Elapsed time: 0.145s (03:00:15) INFO: 0 processes. (03:00:15) FAILED: Build did NOT complete successfully (0 packages loaded, 0 t (03:00:15) FAILED: Build did NOT complete successfully (0 packages loaded, 0 t argets configured)
> 
> It seems nothing has changed.

You should confirm whether you make correct modification about it, 
From build log, it shows that "camera_lib_lane_detector_darkscnn_lane_detector_test" also use "@opencv//:opencv" as dependency.

By the way , i never use "bazel test" command for unit test. you can try to build with `bash apollo.sh build_opt_gpu`, 
and then run executable binary under bazel-bin folder.

thx.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
