### ISSUE TITLE
nvidia-smi not found. CPU will be used.

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#14236]
Hello！
I can get the following screen indicating that the driver is installed successfully

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8     7W /  N/A |      6MiB /  5944MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2827      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

 but WHEN I want to enter Apollo Docker to compile, I get the following prompt：
[WARNING] nvidia-smi not found. CPU will be used.

So did I install the driver successfully or not？

**Comment by L-Net-1992** [comment]
This can only say that your host machine has successfully installed the NVIDIA graphics card driver, but it is not installed in docker. You should install nvidia-docker tool to compile GPU.You can find the installation script at this address：**https://github.com/ApolloAuto/apollo/blob/r5.5.0/docker/setup_host/install_nvidia_docker.sh**,This script is also applicable to 6.0.0 version or later.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by FishBlanche** [comment]
> This can only say that your host machine has successfully installed the NVIDIA graphics card driver, but it is not installed in docker. You should install nvidia-docker tool to compile GPU.You can find the installation script at this address：**https://github.com/ApolloAuto/apollo/blob/r5.5.0/docker/setup_host/install_nvidia_docker.sh**,This script is also applicable to 6.0.0 version or later.

the link is unreacheable now,do u have one?

**Comment by i-kj** [comment]
I am also getting the same error. Did anyone manage to sort the issue?

root@in-dev-docker:/apollo# ./apollo.sh build_gpu
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: guardstrike/apollo_carla_bridge-2022-11-23-653b3e953
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210914_1336
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] USE_GPU=1 without GPU can't compile. Exiting ...


The above shared link could not be accessed. Please help
