### ISSUE TITLE
获取原始点云数据。

### ISSUE THREAD

**Issue by shusukui** [ApolloAuto/apollo#14233]
Apollo中如何获取激光雷达的原始点云数据，并保存成文件。

**Comment by daohu527** [comment]
You can ref to [link](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/tools/record_parse_save/README.md).

`parse_lidar.py` can used to parse lidar data as a pcd file.

**Comment by shusukui** [comment]
Thank you.
