### ISSUE TITLE
How to use a sub-module as an individual functional module in my own project

### ISSUE THREAD

**Issue by guanhuankang** [ApolloAuto/apollo#14230]
I have followed the Installation Guideline to setup the Apollo project. But I want to use one of sub-modules (/modules/planning/reference_line) as an individual functional modules in my own project. What should I do?

If I need to load some .so or .a files, which one should I add and what other packages/libraries/headers should I include? Thank you for any help!

**Comment by daohu527** [comment]
In view of your situation, you can introduce the reference_line module as SO into your module, of course you need to deal with some dependencies, which need to be done by yourself

**Comment by guanhuankang** [comment]
Thank you for your reply! I will have a try on it.
