### ISSUE TITLE
How to use a launch file instead of a dag file in HMI? 

### ISSUE THREAD

**Issue by IDovgopolik** [ApolloAuto/apollo#14232]
Hi to all!
I want to use a launch file instead of dag file when I run the modules. Is it possible and how can I do this? What do I need to write in the "value" field?
![Screenshot from 2021-12-17 19-23-27](https://user-images.githubusercontent.com/63422436/146576136-ad212c29-d54d-4876-8387-3d91b69f608d.png)

**Comment by daohu527** [comment]
You use a `Module` to start a module use script. 
```
modules {
  key: "Recorder"
  value: {
    start_command: "/apollo/scripts/record_bag.py --start"
    stop_command: "/apollo/scripts/record_bag.py --stop"
    process_monitor_config {
      command_keywords: "cyber_recorder record"
    }
  }
}
```

start_command will called to start the module and stop_command to stop it.  
> Module is usually used to start a binary file, not a cyber module

## addition
But since it is a launch file, it is actually no different from DAG

**Comment by IDovgopolik** [comment]
> 

Thank you for answer, @daohu527 !
Which commands need I to write in "start_command" and "stop_command" for start and stop launch file?

**Comment by daohu527** [comment]
You should write a shell script to start the startup file
```
#! /usr/bin/env bash
cyber_launch start xxx.launch
```

**Comment by IDovgopolik** [comment]
Got it, @daohu527 . And the last question, what does field "command_keywords" mean?

**Comment by daohu527** [comment]
Dreamview will read the configuration of this field and run the corresponding script. You can understand it as the configuration file name

**Comment by IDovgopolik** [comment]
So, in my case it's a launch file?

**Comment by daohu527** [comment]
The system reads start_command and executes it, you can replace this script as needed

**Comment by IDovgopolik** [comment]
I wrote a simple bash script for the control module. There is:
![Screenshot from 2021-12-23 11-22-49](https://user-images.githubusercontent.com/63422436/147210929-5d2805fb-db58-4a78-8e4b-84bb3460d3ca.png)
And made the button in hmi:
![Screenshot from 2021-12-23 11-23-56](https://user-images.githubusercontent.com/63422436/147211057-10501136-6a14-489b-89c6-8a115458404a.png)
When I run the dreamview, the Control1 button activates without my participation (by default):
![Screenshot from 2021-12-23 11-25-55](https://user-images.githubusercontent.com/63422436/147211409-70887c8e-92de-4941-afa0-4c1ebe05fd04.png)
But the Control module doesn't work (topic control is empty). Can you, please, help me with this trouble?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
