### ISSUE TITLE
请问有modules/map/tools目录下各脚本功能的详细介绍吗？

### ISSUE THREAD

**Issue by wycrystal** [ApolloAuto/apollo#14244]
请问有modules/map/tools目录下各脚本功能的详细介绍吗？

**Comment by L-Net-1992** [comment]
If you want to know something about HD-Map, please read this document，**/modules/map/data/README.md**.This document will help you make some simple HD maps and complete your algorithm test. If you want to know more about maps, you can come to the official website(**https://apollo.auto/developer/index_cn.html#/**) to learn more, thank you.

**Comment by daohu527** [comment]
Thanks for your advice. We're happy to tell you that this feature is on our roadmap and will be released in the next version.
