### ISSUE TITLE
#apolloauto IRC channel is now alive! (unofficial)

### ISSUE THREAD

**Issue by zhxt** [ApolloAuto/apollo#1424]
#apolloauto on Freenode

Come and say hello!  :-)

(BTW, Sorry, this is not an issue.)

**Comment by zhxt** [comment]
For peoples who don't familiar with IRC:
(Ignore this if you've already know it)

1. What is IRC?
Simply, IRC is a tool for communicating with folks from all over the world.(from ref[1]) 

2. Basics guide:
https://fedoramagazine.org/beginners-guide-irc/

(Replace the installation command:
"su -c 'dnf install hexchat'"
in this post with
"sudo apt-get install hexchat"
for ubuntu users.
)

(You also can use other clients like Quassel, irssi, Konversation, WeeChat, or web based access from browser, etc.
Just choose the one you like.)

Enjoy!

References:
[1] http://www.ircbeginner.com/ircinfo/ircclass.html
[2] https://help.ubuntu.com/community/InternetRelayChat
[3] https://opensource.com/life/16/6/irc-quickstart-guide
[4] https://code.tutsplus.com/tutorials/irc-is-back-heres-your-starter-guide--net-31369
[5] https://opensource.com/life/15/11/top-open-source-irc-clients
[6] https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients

**Comment by richtong** [comment]
Nice thanks!

**Comment by zhxt** [comment]
@richtong Yeah, I just registered it a few days ago, only me and a log bot there(logs is at ip of bot/logs, when my domain is ready, I will update the channel topic). I have saw your hello message from logs in the morning, at that time you joined I was probably in a dream :P 

I have noticed that peoples here not use IRC much, but many open source project like Qt, Sailfish, Mer, KDE, ROS, openSUSE, Ubuntu, kernel, android, and many many other projects have IRC channels, some of them are very active. It‘s convenient for community collaboration, hope you will like it. :-)

**Comment by richtong** [comment]
Thanks very much for doing. Many other projects use slack for the same purpose. Excellent to have a place to discuss. I see the core Apollo team there as well

Thanks,
Rich

Sent from my iPhone X
http://tongfamily.com | @richtong | https://fb.me/richtong1

**Comment by zhxt** [comment]
close

**Comment by zhxt** [comment]
closed #1424
