### ISSUE TITLE
Data Collection from sensor

### ISSUE THREAD

**Issue by JANE0015** [ApolloAuto/apollo#14246]
Hi, currently I have uploaded the apollo program to a car. May I know how can I extract the data of the sensors( continental radar) in this case from the code to a file? Which code and file contains this information? Thank you

**Comment by L-Net-1992** [comment]
You can find out, cyber_ recorder, detailed instructions are here:/apollo/docs/cyber/CyberRT_Developer_Tools.md,I hope I can help you, thank you.

**Comment by JANE0015** [comment]
Hi thank you for the suggestion. But may I know which kind of data am I collecting, frequency, motion etc? Is the data directly from the radar or has been processed in the Industrial Computer?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
