### ISSUE TITLE
When I compile on Xiaver, I find some files are not provided，eg localization_msf/gnss_struct.h

### ISSUE THREAD

**Issue by lhenin** [ApolloAuto/apollo#14251]
When I compile on Xiaver, I find some files are not provided
eg: compile apollo v7.0 Something went wrong

（04:40:05) ERROR: /apollo/modules/localization/msf/local_integ/BUILD:6:11: C++ compilation of rule '//modules/localization/msf/local_integ:local_integ' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/aarch64-fastbuild/bin/modules/localization/msf/local_integ/_objs/local_integ/gnss_msg_transfer.pic.d ... (remaining 140 argument(s) skipped)
In file included from modules/localization/msf/local_integ/gnss_msg_transfer.cc:17:0:
./modules/localization/msf/local_integ/gnss_msg_transfer.h:24:10: fatal error: localization_msf/gnss_struct.h: No such file or directory
 #include "localization_msf/gnss_struct.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
(04:40:06) INFO: Elapsed time: 4077.533s, Critical Path: 343.03s
(04:40:06) INFO: 9245 processes: 6647 internal, 2598 local.
(04:40:06) FAILED: Build did NOT complete successfully

**Comment by ZeusJupiter** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已经收到。我会尽快给您回复。
谢谢。

**Comment by daohu527** [comment]
duplicated #14252
