### ISSUE TITLE
How to communicate with modules running in docker container from outside world? 

### ISSUE THREAD

**Issue by wijdim** [ApolloAuto/apollo#14256]
### System information

**Linux Ubuntu 18.04
**Apollo installed from source
**Apollo version master

###Question 

I m using docker/scripts/dev_start.sh to create the container. 
I need to communicate with the container from the outside world ( send data ) . but the container does not publish any of its ports so still can't receive any messages in the server apollo. 
I tried to add this option "-p 8080:8080/udp" but still can't resolve the problem.
![image](https://user-images.githubusercontent.com/96061375/148405032-e13bd727-9edb-4b83-8e68-dfbfdc5adf29.png)

How can i active communication between modules running in docker container and the outside world? 
Thank you?

**Comment by wijdim** [comment]
?????

**Comment by wijdim** [comment]
,,,,

**Comment by daohu527** [comment]
sorry for late reply, you can delete the invalid comment and come back to your question.

You can use the **bridge module** (modules/bridge) to communicate with another machine, You can look at the readme and examples first and then try something

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
