### ISSUE TITLE
Does ReferenceLine::HasOverlap(...) have the same function with ReferenceLine::IsOnLane(..) ?

### ISSUE THREAD

**Issue by GaoPenghao** [ApolloAuto/apollo#14250]
When I read "modules/planning/reference_line.cc", there are some question confusing me. And I hope someone can help me.

- Does ReferenceLine::HasOverlap(...) have the same function with ReferenceLine::IsOnLane(..) ?
- Is there a logic error in the ReferenceLine::HasOverlap(...) ？ 
  bool ReferenceLine::HasOverlap(...) {
    ...
    if (sl_boundary.start_l() * sl_boundary.endl() < 0) {
      return false;       // I think there should be " return true "
    }
    ...
  }

**Comment by diaokaitian** [comment]
it seems that you are  right
