### ISSUE TITLE
When I test the planning module in r6.0.0, the trajectory can't generate. 

### ISSUE THREAD

**Issue by yangshaoqing1996** [ApolloAuto/apollo#14255]
The bag  which I runned  is "demo_3.5.record.np.record". The following is the log information:
planning.log.INFO：
`W0106 22:03:20.365231  6731 reference_line_provider.cc:266] Reference line is NOT ready.
E0106 22:03:20.365247  6731 reference_line_provider.cc:268] Failed to use reference line latest history
E0106 22:03:20.365263  6731 on_lane_planning.cc:150] Failed to create reference line
E0106 22:03:20.365341  6731 on_lane_planning.cc:378] PLANNING_ERROR: Failed to create reference line
E0106 22:03:20.366436  6731 pnc_map.cc:560] Failed to find nearest point: x: 587680.18864937837 y: 4141255.6259027235 z: -32.164357560153995
E0106 22:03:20.366511  6731 pnc_map.cc:167] Failed to get waypoint from routing with point: (587680, 4.14126e+06, -32.1644).
E0106 22:03:20.366520  6731 pnc_map.cc:421] Failed to update vehicle state in pnc_map.
E0106 22:03:20.366524  6731 reference_line_provider.cc:547] Failed to extract segments from routing
E0106 22:03:20.366541  6731 reference_line_provider.cc:589] Failed to create reference line from routing
E0106 22:03:20.366554  6731 reference_line_provider.cc:212] Fail to get reference line
E0106 22:03:20.424512  6726 pnc_map.cc:560] Failed to find nearest point: x: 587680.18864937837 y: 4141255.6259027235 z: -32.164357560153995
E0106 22:03:20.424602  6726 pnc_map.cc:167] Failed to get waypoint from routing with point: (587680, 4.14126e+06, -32.1644).
E0106 22:03:20.424612  6726 pnc_map.cc:421] Failed to update vehicle state in pnc_map.
E0106 22:03:20.424615  6726 reference_line_provider.cc:547] Failed to extract segments from routing
E0106 22:03:20.424619  6726 reference_line_provider.cc:589] Failed to create reference line from routing
E0106 22:03:20.424634  6726 reference_line_provider.cc:212] Fail to get reference line
W0106 22:03:20.457450  6720 reference_line_provider.cc:266] Reference line is NOT ready.
E0106 22:03:20.457470  6720 reference_line_provider.cc:268] Failed to use reference line latest history
E0106 22:03:20.457484  6720 on_lane_planning.cc:150] Failed to create reference line
E0106 22:03:20.457541  6720 on_lane_planning.cc:378] PLANNING_ERROR: Failed to create reference line
E0106 22:03:20.476773  6730 pnc_map.cc:560] Failed to find nearest point: x: 587680.38447166176 y: 4141256.4473173078 z: -32.164357560153995
E0106 22:03:20.476855  6730 pnc_map.cc:167] Failed to get waypoint from routing with point: (587680, 4.14126e+06, -32.1644).
E0106 22:03:20.476862  6730 pnc_map.cc:421] Failed to update vehicle state in pnc_map.
E0106 22:03:20.476866  6730 reference_line_provider.cc:547] Failed to extract segments from routing
E0106 22:03:20.476869  6730 reference_line_provider.cc:589] Failed to create reference line from routing
E0106 22:03:20.476883  6730 reference_line_provider.cc:212] Fail to get reference line
E0106 22:03:20.534444  6722 pnc_map.cc:560] Failed to find nearest point: x: 587680.38447166176 y: 4141256.4473173078 z: -32.164357560153995
E0106 22:03:20.534524  6722 pnc_map.cc:167] Failed to get waypoint from routing with point: (587680, 4.14126e+06, -32.1644).
E0106 22:03:20.534535  6722 pnc_map.cc:421] Failed to update vehicle state in pnc_map.
E0106 22:03:20.534538  6722 reference_line_provider.cc:547] Failed to extract segments from routing
E0106 22:03:20.534543  6722 reference_line_provider.cc:589] Failed to create reference line from routing
E0106 22:03:20.534557  6722 reference_line_provider.cc:212] Fail to get reference line
W0106 22:03:20.564430  6734 reference_line_provider.cc:266] Reference line is NOT ready.
E0106 22:03:20.564452  6734 reference_line_provider.cc:268] Failed to use reference line latest history
E0106 22:03:20.564465  6734 on_lane_planning.cc:150] Failed to create reference line
E0106 22:03:20.564520  6734 on_lane_planning.cc:378] PLANNING_ERROR: Failed to create reference line`

map.log.INFO:
`Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0106 22:03:04.369930  6763 hdmap.cc:24] Loading HDMap: /apollo/modules/map/data/sunnyvale_loop/base_map.bin ...
E0106 22:03:05.015200  6763 hdmap_common.cc:149] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].
E0106 22:03:05.015599  6763 hdmap_common.cc:149] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787105] is too small. It should be larger than half vehicle width[1.05].
E0106 22:03:05.015662  6763 hdmap_common.cc:149] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787116] is too small. It should be larger than half vehicle width[1.05].
E0106 22:03:05.015671  6763 hdmap_common.cc:149] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787127] is too small. It should be larger than half vehicle width[1.05].`

I am a novice with Apollo. I don't know what the problem is. Sincerely hope to get your help.

**Comment by daohu527** [comment]
If you want to test the planning module, I recommend you to use **sim_control**

## reason
Because the recorded bag is on a certain map, and you are not actually using the map at that time, the gps position is incorrect, causing problems

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
