### ISSUE TITLE
Compiling Module/perception using Nvidia xavier with Apollo6.0

### ISSUE THREAD

**Issue by ranzhichao** [ApolloAuto/apollo#14257]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information
using apollo/modules/perception：bazel build ...
***Error issue***:
(03:04:18) INFO: Analyzed 1079 targets (0 packages loaded, 0 targets configured).
(03:04:18) INFO: Found 1079 targets...
(03:04:19) ERROR: /apollo/modules/perception/lidar/lib/detector/point_pillars_detection/BUILD:119:13: error while parsing .d file: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/aarch64-fastbuild/bin/modules/perception/lidar/lib/detector/point_pillars_detection/_objs/preprocess_points_cuda/preprocess_points_cuda.pic.d (No such file or directory)
gcc: warning: modules/perception/lidar/lib/detector/point_pillars_detection/preprocess_points_cuda.cu: linker input file unused because linking not done
(03:04:19) INFO: Elapsed time: 1.547s, Critical Path: 0.50s
(03:04:19) INFO: 68 processes: 34 remote cache hit, 31 internal, 3 local.
(03:04:19) FAILED: Build did NOT complete successfully

**Comment by daohu527** [comment]
Currently apollo does not fully support arm, we will consider this requirement in the future
