### ISSUE TITLE
Compiling Module/perception using Nvidia xavier (cpu 8-core carmel arm V8.2 64-bit)with Apollo6.0

### ISSUE THREAD

**Issue by ranzhichao** [ApolloAuto/apollo#14258]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution ( Nvidia jetson agx xavier  Linux Ubuntu 18.04)**:
-CPU: 8-core carmel arm v8.2 64-bit cpu,8mb l2+4mb l3
GPU:512-core volta gpu with 64 tensor
- **Apollo version ( 6.0)**:
- *`master` branch**:
- ./apollo.sh build canbus --config=cpu

### Supporting 
![微信图片_20220110103607](https://user-images.githubusercontent.com/89329514/148712759-64177706-a1b3-40d5-8fdf-98af4a0838e4.png)
materials (screenshots, command lines, code/script snippets):

**Comment by daohu527** [comment]
Currently apollo does not fully support arm, we will consider this requirement in the future
