### ISSUE TITLE
【No such target "boost" or opencv】

### ISSUE THREAD

**Issue by shandaolu** [ApolloAuto/apollo#14254]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hello, when I build obstacle_detection:obstacle_detection. I meet the question. Please give me instructions. Thanks.

![Screenshot from 2022-01-05 17-49-44](https://user-images.githubusercontent.com/35679679/148197238-7cb77fa5-7c53-43c6-91b4-a867cef74306.png)
The build file below. Do I need to modify?
![Screenshot from 2022-01-05 17-51-24](https://user-images.githubusercontent.com/35679679/148197439-4a1aab6f-af01-457e-84e5-8d6149ce513b.png)

**Comment by Xxfore** [comment]
you should specify opencv library which used in Unit Test.
Such as @opencv//:core , @opencv//:highgui ,and so on.

**Comment by shandaolu** [comment]
@Xxfore Thankyou for your reply. I solve this problem, but I meet another problem when I build 


`root@in-dev-docker:/apollo# bazel build  modules/perception/camera/tools/obstacle_detection:obstacle_detection
(00:57:56) INFO: Current date is 2022-01-07
(00:57:56) INFO: Analyzed target //modules/perception/camera/tools/obstacle_detection:obstacle_detection (0 packages loaded, 0 targets configured).
(00:57:56) INFO: Found 1 target...
(00:57:58) ERROR: /apollo/modules/perception/camera/common/BUILD:27:11: C++ compilation of rule '//modules/perception/camera/common:data_provider' failed (Exit 1)
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::Init(const apollo::perception::camera::DataProvider::InitOptions&)':
modules/perception/camera/common/data_provider.cc:34:7: error: 'cudaSetDevice' was not declared in this scope
   if (cudaSetDevice(device_id_) != cudaSuccess) {
       ^~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:34:36: error: 'cudaSuccess' was not declared in this scope
   if (cudaSetDevice(device_id_) != cudaSuccess) {
                                    ^~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:34:36: note: suggested alternative: 'euidaccess'
   if (cudaSetDevice(device_id_) != cudaSuccess) {
                                    ^~~~~~~~~~~
                                    euidaccess
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::FillImageData(int, int, const uint8_t*, const string&)':
modules/perception/camera/common/data_provider.cc:118:7: error: 'cudaSetDevice' was not declared in this scope
   if (cudaSetDevice(device_id_) != cudaSuccess) {
       ^~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:118:36: error: 'cudaSuccess' was not declared in this scope
   if (cudaSetDevice(device_id_) != cudaSuccess) {
                                    ^~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:118:36: note: suggested alternative: 'euidaccess'
   if (cudaSetDevice(device_id_) != cudaSuccess) {
                                    ^~~~~~~~~~~
                                    euidaccess
modules/perception/camera/common/data_provider.cc:136:50: error: 'using element_type = class apollo::perception::base::Image8U {aka class apollo::perception::base::Image8U}' has no member named 'count'
     memcpy(rgb_->mutable_cpu_data(), data, rgb_->count() * sizeof(data[0]));
                                                  ^~~~~
modules/perception/camera/common/data_provider.cc:140:50: error: 'using element_type = class apollo::perception::base::Image8U {aka class apollo::perception::base::Image8U}' has no member named 'count'
     memcpy(bgr_->mutable_cpu_data(), data, bgr_->count() * sizeof(data[0]));
                                                  ^~~~~
modules/perception/camera/common/data_provider.cc:144:52: error: 'using element_type = class apollo::perception::base::Image8U {aka class apollo::perception::base::Image8U}' has no member named 'count'
     memcpy(gray_->mutable_cpu_data(), data, gray_->count() * sizeof(data[0]));
                                                    ^~~~~
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::GetImageBlob(const apollo::perception::camera::DataProvider::ImageOptions&, apollo::perception::base::Blob<unsigned char>*)':
modules/perception/camera/common/data_provider.cc:227:3: error: 'NppiSize' was not declared in this scope
   NppiSize roi;
   ^~~~~~~~
modules/perception/camera/common/data_provider.cc:228:3: error: 'roi' was not declared in this scope
   roi.height = image.rows();
   ^~~
modules/perception/camera/common/data_provider.cc:228:3: note: suggested alternative: 'atoi'
   roi.height = image.rows();
   ^~~
   atoi
modules/perception/camera/common/data_provider.cc:230:61: error: no matching function for call to 'apollo::perception::base::Blob<unsigned char>::Reshape(<brace-enclosed initializer list>)'
   blob->Reshape({1, roi.height, roi.width, image.channels()});
                                                             ^
In file included from ./modules/perception/camera/common/data_provider.h:21:0,
                 from modules/perception/camera/common/data_provider.cc:16:
./modules/perception/base/blob.h:107:8: note: candidate: void apollo::perception::base::Blob<Dtype>::Reshape(int, int, int, int) [with Dtype = unsigned char]
   void Reshape(const int num, const int channels, const int height,
        ^~~~~~~
./modules/perception/base/blob.h:107:8: note:   candidate expects 4 arguments, 1 provided
./modules/perception/base/blob.h:123:8: note: candidate: void apollo::perception::base::Blob<Dtype>::Reshape(const std::vector<int>&) [with Dtype = unsigned char]
   void Reshape(const std::vector<int>& shape);
        ^~~~~~~
./modules/perception/base/blob.h:123:8: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const std::vector<int>&'
modules/perception/camera/common/data_provider.cc:232:5: error: 'nppiCopy_8u_C1R' was not declared in this scope
     nppiCopy_8u_C1R(image.gpu_data(), image.width_step(),
     ^~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:236:5: error: 'nppiCopy_8u_C3R' was not declared in this scope
     nppiCopy_8u_C3R(image.gpu_data(), image.width_step(),
     ^~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::to_gray_image()':
modules/perception/camera/common/data_provider.cc:282:5: error: 'NppiSize' was not declared in this scope
     NppiSize roi;
     ^~~~~~~~
modules/perception/camera/common/data_provider.cc:283:5: error: 'roi' was not declared in this scope
     roi.height = src_height_;
     ^~~
modules/perception/camera/common/data_provider.cc:283:5: note: suggested alternative: 'atoi'
     roi.height = src_height_;
     ^~~
     atoi
modules/perception/camera/common/data_provider.cc:286:7: error: 'Npp32f' was not declared in this scope
       Npp32f coeffs[] = {0.114f, 0.587f, 0.299f};
       ^~~~~~
modules/perception/camera/common/data_provider.cc:286:7: note: suggested alternative: 'exp2f'
       Npp32f coeffs[] = {0.114f, 0.587f, 0.299f};
       ^~~~~~
       exp2f
modules/perception/camera/common/data_provider.cc:289:37: error: 'coeffs' was not declared in this scope
                                roi, coeffs);
                                     ^~~~~~
modules/perception/camera/common/data_provider.cc:289:37: note: suggested alternative: 'cosf64'
                                roi, coeffs);
                                     ^~~~~~
                                     cosf64
modules/perception/camera/common/data_provider.cc:287:7: error: 'nppiColorToGray_8u_C3C1R' was not declared in this scope
       nppiColorToGray_8u_C3C1R(bgr_->gpu_data(), bgr_->width_step(),
       ^~~~~~~~~~~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:292:7: error: 'Npp32f' was not declared in this scope
       Npp32f coeffs[] = {0.299f, 0.587f, 0.114f};
       ^~~~~~
modules/perception/camera/common/data_provider.cc:292:7: note: suggested alternative: 'exp2f'
       Npp32f coeffs[] = {0.299f, 0.587f, 0.114f};
       ^~~~~~
       exp2f
modules/perception/camera/common/data_provider.cc:295:37: error: 'coeffs' was not declared in this scope
                                roi, coeffs);
                                     ^~~~~~
modules/perception/camera/common/data_provider.cc:295:37: note: suggested alternative: 'cosf64'
                                roi, coeffs);
                                     ^~~~~~
                                     cosf64
modules/perception/camera/common/data_provider.cc:293:7: error: 'nppiColorToGray_8u_C3C1R' was not declared in this scope
       nppiColorToGray_8u_C3C1R(rgb_->gpu_data(), rgb_->width_step(),
       ^~~~~~~~~~~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::to_rgb_image()':
modules/perception/camera/common/data_provider.cc:307:5: error: 'NppiSize' was not declared in this scope
     NppiSize roi;
     ^~~~~~~~
modules/perception/camera/common/data_provider.cc:308:5: error: 'roi' was not declared in this scope
     roi.height = src_height_;
     ^~~
modules/perception/camera/common/data_provider.cc:308:5: note: suggested alternative: 'atoi'
     roi.height = src_height_;
     ^~~
     atoi
modules/perception/camera/common/data_provider.cc:313:7: error: 'nppiSwapChannels_8u_C3R' was not declared in this scope
       nppiSwapChannels_8u_C3R(bgr_->gpu_data(), bgr_->width_step(),
       ^~~~~~~~~~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:318:7: error: 'nppiDup_8u_C1C3R' was not declared in this scope
       nppiDup_8u_C1C3R(gray_->gpu_data(), gray_->width_step(),
       ^~~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc: In member function 'bool apollo::perception::camera::DataProvider::to_bgr_image()':
modules/perception/camera/common/data_provider.cc:331:5: error: 'NppiSize' was not declared in this scope
     NppiSize roi;
     ^~~~~~~~
modules/perception/camera/common/data_provider.cc:332:5: error: 'roi' was not declared in this scope
     roi.height = src_height_;
     ^~~
modules/perception/camera/common/data_provider.cc:332:5: note: suggested alternative: 'atoi'
     roi.height = src_height_;
     ^~~
     atoi
modules/perception/camera/common/data_provider.cc:336:7: error: 'nppiSwapChannels_8u_C3R' was not declared in this scope
       nppiSwapChannels_8u_C3R(rgb_->gpu_data(), rgb_->width_step(),
       ^~~~~~~~~~~~~~~~~~~~~~~
modules/perception/camera/common/data_provider.cc:341:7: error: 'nppiDup_8u_C1C3R' was not declared in this scope
       nppiDup_8u_C1C3R(gray_->gpu_data(), gray_->width_step(),
`

**Comment by daohu527** [comment]
Have you changed the file in `data_provider`? the error indicates that the declaration of `cudaSetDevice` is missing.

"nppi.h" implicitly includes `cuda_runtime.h`, so I don't know if you changed anything and cause this problem.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by GabrielZZZ** [comment]
@shandaolu Hi, I have encountered the same problem. Did you solve it?

**Comment by hkyee** [comment]
Hi @shandaolu , I am facing the same issue, was wondering, did you manage to solve it?
