### ISSUE TITLE
Compiling Module/drivers using Nvidia xavier (cpu 8-core carmel arm V8.2 64-bit)with Apollo6.0

### ISSUE THREAD

**Issue by ranzhichao** [ApolloAuto/apollo#14260]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **Platform Nvidia jetson agx xavier  OS：Linux Ubuntu 18.04)**:
- **Apollo version (6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:
- **On module: bazel build ...
![canbus_compile_err](https://user-images.githubusercontent.com/89329514/148739123-93b73573-ffbc-437d-8da9-a3639b9a86b3.png)
![modules_drives](https://user-images.githubusercontent.com/89329514/148739135-299769d6-dd30-4567-87f9-d86870f62b15.png)

**Comment by daohu527** [comment]
you can first complie "modules/drivers/canbus" to identify the problem

I guess the problem is caused by the third party canbus library
