### ISSUE TITLE
单步调试smoke算法模块，调试不了

### ISSUE THREAD

**Issue by lincaiming** [ApolloAuto/apollo#14263]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:
  master
### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

执行命令行：
/apollo/bazel-bin/cyber/mainboard/mainboard   -d   /apollo/modules/perception/production/dag/dag_streaming_obstacle_detection.dag

出现报错
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0111 00:56:58.041225  8279 module_argument.cc:81] []command: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-dbg/bin/cyber/mainboard/mainboard -d /apollo/modules/perception/production/dag/dag_streaming_obstacle_detection.dag 
I0111 00:56:58.041805  8279 global_data.cc:153] []host ip: 192.168.8.104
I0111 00:56:58.048014  8279 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I0111 00:56:58.048048  8279 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_obstacle_detection.dag
E0111 00:58:10.952896  8279 obstacle_detection_camera.cc:182] [mainboard]Calibraion service is not available
E0111 00:58:10.960386  8279 obstacle_detection_camera.cc:193] [mainboard]Calibraion service is not available

**Comment by ycdhqzhiai** [comment]
+1

**Comment by dahwang22** [comment]
+1

**Comment by WeiJunREN** [comment]
解决了嘛

**Comment by daohu527** [comment]
@lincaiming @ycdhqzhiai @dahwang22 @WeiJunREN The error message below is normal.
```
E0111 00:58:10.952896 8279 obstacle_detection_camera.cc:182] [mainboard]Calibraion service is not available
```

Did you encounter any other error messages?

**Comment by dahwang22** [comment]
add below code in line 724:

`
camera_obstacle_pipeline_->GetCalibrationService(
      &camera_frame.calibration_service);
`

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
