### ISSUE TITLE
adapter_manager.h中函数调用时如何运作的？

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#1426]
您好，
    想问下在adapter_manager.h文件中name##_.get()调用后续会怎么走？假设从Planning.cc中AdapterManager::GetLocalization()开始，我的理解流程如下：
AdapterManager::GetLocalization()------>static name##Adapter *Get##name()------>
instance()->InternalGet##name()------>name##_.get() 然后我就找不到后续的步骤了，直觉上应该会回到localization模块，应该调用的是localization_.get()函数，但是没有找到这种形式的函数，而且localization模块好像也没有get()成员函数，还请帮忙解惑，谢谢。

**Comment by startcode** [comment]
AdapterManager.cc 中
https://github.com/ApolloAuto/apollo/blob/ea32174987afad01e335b026b5d20e18267326f2/modules/common/adapters/adapter_manager.h#L96  
```
std::unique_ptr<name##Adapter> name##_;                                      \
```
name##.get() 调用的是uniqure_ptr 的 get 函数，返回一个指向 LocalizationAdapter 的 raw 指针。
LocalizationAdapter 定义在这里
https://github.com/ApolloAuto/apollo/blob/ea32174987afad01e335b026b5d20e18267326f2/modules/common/adapters/message_adapters.h#L60
它是一个 Adapter 模版类。

**Comment by ahuer2435** [comment]
多谢，再问下LocalizationAdapter是在哪里实例化的？ @startcode

**Comment by startcode** [comment]
https://github.com/ApolloAuto/apollo/blob/e2001d465c39cde9397d00a8a92ed9480a9f9697/modules/common/adapters/adapter_manager.h#L102

**Comment by ahuer2435** [comment]
了解了，谢谢。 @startcode
