### ISSUE TITLE
How can I create an HDMap from sensor data?

### ISSUE THREAD

**Issue by josh-wende** [ApolloAuto/apollo#14268]
Hi,

I would like to create an HDMap of a new area using recorded sensor data (recorded using cyber_recorder). I have found references to this possibility in the documentation, but haven't been able to find any instructions about how to do it. What do I have to do/where can I find the instructions?

Thanks,
Josh

**Comment by L-Net-1992** [comment]
A simple method is to generate a simple hdmap in this directory “/apollo/modules/map/data/README.md”， but it is not flexible enough. Another way is to collect the original point cloud file, synthesize the point cloud through some slam algorithms, and then import lgsvl as a tool to draw the map manually. You can output the map in Apollo format. Of course, you should pay attention to some coordinate conversion. These two methods are only applicable to algorithm testing and small-scale road testing. Good luck. If you don't understand, welcome to write.

**Comment by josh-wende** [comment]
Thank you for the help!

What if I needed to create a larger HD Map? I have used the LGSVL map annotation tool and it is very slow and tedious. I found [this](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md) which apparently outlines how to use Baidu's cloud service to generate an HD Map from lidar/pose information, but I am not in China so I cannot create a Baidu account (and I don't speak Chinese so the documentation is a bit tough to understand). Is there no other simple way to generate an Apollo HD Map?

I suppose I could try to collect all of the needed LiDAR and camera data, then run all of the lane/object/sign detection neural networks myself to get that information and then manually create the base map from that. I think I would still need to use LGSVL to add some annotations for things like junctions and sidewalks and crosswalks though, right? And ensure that all of the intersections and turn lanes and yield lanes are set up correctly. I am not sure how confident I would be in the quality of this map.

**Comment by qwetqwe** [comment]
There are some simple tools to create hdmap
https://github.com/ApolloAuto/apollo/tree/master/modules/tools/map_gen
First you need to generate a point cloud map, and calibration  coordinate of every element.
Then you need to develop some tools to organize these coordinates like map_gen tools

**Comment by josh-wende** [comment]
Okay, I was hoping to be able to use pre-existing software, but I guess I'll just have to make my own HD Map creation tool then. It is frustrating that Baidu's cloud service (and thus Apollo Fuel) is only open to people/companies licensed in China, but I suppose it is what it is. Thanks for your help!

**Comment by daohu527** [comment]
There are also map dealers abroad, you can get the map in opendrive format and convert it to apollo, if your job is not to make maps. : )
