### ISSUE TITLE
How to let apollo running over 100km/h in lgsvl

### ISSUE THREAD

**Issue by yuchendoudou** [ApolloAuto/apollo#14265]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **Linux Ubuntu 20.04**:
- **Apollo installed from source**:
- **Apollo version 7.0**:
- **Output of `apollo.sh config` if on `master` branch**:
    [INFO] Apollo Environment Settings:
    [INFO]     APOLLO_ROOT_DIR: /apollo
    [INFO]     APOLLO_CACHE_DIR: /apollo/.cache
    [INFO]     APOLLO_IN_DOCKER: true
    [INFO]     APOLLO_VERSION: master-2021-12-28-463fb82f9e
    [INFO]     DOCKER_IMG: dev-x86_64-18.04-20210914_1336
    [INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
    [INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
    [INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
    [INFO] Options:
    [INFO]     -i|--interactive      Run in interactive mode
    [INFO]     -n|--noninteractive   Run in non-interactive mode
    [INFO]     -h|--help             Show this message and exit

- Map:
    Highway101GLE

- Vehicle:
   Lincoln2017mkz

Hello, I set --planning_upper_speed_limit=34.0 and `--default_cruise_speed=33.0` in the `modules/planning/conf/planning.conf`. But apollo can only run at 68km/h in a stringht road. Is there a way to increase  the apollo running speed further. And the map's speed_limit is 31.29m/s.

![1d0f68130ecfdea7fd94d329b2e08c0](https://user-images.githubusercontent.com/52199768/148911386-9ff4d468-b081-4a99-8c7d-c7ed94242f17.png)

**Comment by daohu527** [comment]
Considering there may be acceleration limits, Is your road long enough to accelerate

**Comment by diaokaitian** [comment]
you should also check the speed limit from map

**Comment by daohu527** [comment]
He has confirmed that the speed of the map is `31.29m/s`.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
