### ISSUE TITLE
Send binary / ubx file in udp protocole to gnss server

### ISSUE THREAD

**Issue by wijdim** [ApolloAuto/apollo#14276]
System information
**Linux Ubuntu 18.04
**Apollo installed from source
**Apollo version master

###Question
I m trying to send data using nc with udp protocol to gnss server. I receive data when it's a simple text file but when i try when novatel.bin or any other binary file i get this exception? 
![image](https://user-images.githubusercontent.com/96061375/149801363-db8fb8ca-aa6c-4ebb-9956-69f20c64c6e4.png)

**Comment by hearto1314** [comment]
UnicodeDecodeErrror caused by encode and decode are not the same encoder usually, try adding encoding="utf-8" when opening the file please.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
