### ISSUE TITLE
UPLOAD CARLA Simulator Town maps to Dreamview? How?

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#14274]
Hi I am using Ubuntu 20.04 OS, Docker, Apollo 5.0 and trying to connect Apollo5.0 with CARLA 0.9.6 , using this tutorial: https://github.com/AuroAi/carla_apollo_bridge.

I have done all the steps successfully. However in usage, I was **not able to visualize the Carla town03 ** or any other CARLA Town map in the Dreamview maps tab. For this reason I could not see the data coming from the simulator.

In the tutorial the Town03 is showed (the tutorial does not say about additional steps to upload the map there):

![image](https://user-images.githubusercontent.com/43826438/149394584-5004f33d-b95d-45b3-9d64-da6eba2d6b08.png)

In my case just these maps have appeared:

![image](https://user-images.githubusercontent.com/43826438/149394620-d958a959-4ed9-4085-ac0b-f07e503ddc35.png)

As far as I know these are LGSVL simulator maps, not from CARLA simulator. **So how do I put the CARLA maps in APollo?**

I know that these maps are put into the **apollo/modules/map/data** but the CARLA map format seems different, where do I find these maps from CARLA, and how to add them in this folder to build this map module again?

Thanks in advance

**Comment by marcusvinicius178** [comment]
I have solved partially this issue dowloading the Town06 and Town07 maps from here: 

And I have copied them and pasted to this folder inside Apollo folder repo: **apollo/modules/map/data**

![image](https://user-images.githubusercontent.com/43826438/149407126-72a0f47a-6aa4-4ba3-a7ed-7a7ad4622f9e.png)

Afterward, the maps have appeared in Dreamview:
![image](https://user-images.githubusercontent.com/43826438/149407197-bc04cc12-d492-4205-9eb1-e902903daee5.png)

**However** I was not able to add the Town03 map in Dreamview (From tutorial). Where do I get and download the code folder from  **CARLA Town03** map?

Thanks in advance

**Comment by daohu527** [comment]
If you update the map, please restart dreamview, this will re-read the map dir

The program only reads the map at startup, it doesn't know that you copied the file into the dir : )

**Comment by marcusvinicius178** [comment]
Thanks @daohu527 I have already fixed this issue, just reinstalling (pulling Apollo docker images from scratch). I was using LGSVL simulator but in this project I need to use CARLA....then I guess it used just SVL cache and pulled the old maps, not the CARLA town...now is fixed.

@daohu527 I am running this tutorial now:https://github.com/AuroAi/carla_apollo_bridge


However I am facing a harsh issue with driver-docker-libGl communication. I am getting the error these guys had: https://github.com/AuroAi/carla_apollo_bridge/issues/11


I am trying all this week to solve this issues. Have you already used Apollo 5.0 with CARLA 0.9.6 inside docker ? I ma struggling in this issue. Have already reinstalled nvidia-drivers, installed clang compilers, ninja-build, nvidia-container toolkit, nvidia-docker2, libvulkan, mesa-grip driver, have also added ENV Nvidia_capabilities, display in Docker image, have exported paths, set symbolic links to libGl versions, restarted docker,daemon and gdm, etc, etc but nothing worked.


Could you please help me to fix this issue?

In addition do you know which Apollo version and which CARLA version are the most stable and working in this moment? Please tell me if you know, and also if they are using docker or from source, and if is there a tutorial?

Thanks very much in advance! If you wish I can open other issue to talk about this error.

**Comment by daohu527** [comment]
@marcusvinicius178 well done, glad your problem is solved!

I see your question about carla-apollo-bridge. Apparently this is another docker that just runs with `cyber`. In my opinion, it just publish the messages, your know that you can use `cyber` to communicate with other machine in **docker bridge mode**.

I have used the lgsvl remote python script to start the simulation and it works without a graphical interface. Carla also has such a function. opengl error is related to graphical interface. So I thought it would be possible to see how the script starts the GUI.

Actually I suggest you to ask questions in the carla_apollo_bridge repository. we can discuss there : )

**Comment by marcusvinicius178** [comment]
Sure @daohu527 I will be very grateful if you could help me there, I am struggling for weeks to fix this..... 
I have created a new issue here: https://github.com/AuroAi/carla_apollo_bridge/issues/30

Thanks for your attention again :)

**Comment by JasonBourne1998** [comment]
@marcusvinicius178 Hi marcus, do you know how to convert the base_map.bin to base_map.txt?

**Comment by daohu527** [comment]
```
source scripts/apollo_base.sh

protoc --decode apollo.hdmap.Map modules/map/proto/map.proto < modules/map/data/sunnyvale_loop/base_map.bin > base_map.txt
```

**Comment by JasonBourne1998** [comment]
> I have solved partially this issue dowloading the Town06 and Town07 maps from here:
> 
> And I have copied them and pasted to this folder inside Apollo folder repo: **apollo/modules/map/data**
> 
> ![image](https://user-images.githubusercontent.com/43826438/149407126-72a0f47a-6aa4-4ba3-a7ed-7a7ad4622f9e.png)
> 
> Afterward, the maps have appeared in Dreamview: ![image](https://user-images.githubusercontent.com/43826438/149407197-bc04cc12-d492-4205-9eb1-e902903daee5.png)
> 
> **However** I was not able to add the Town03 map in Dreamview (From tutorial). Where do I get and download the code folder from **CARLA Town03** map?
> 
> Thanks in advance

Hi @marcusvinicius178, where did you find the town03,06,07 map resources? I couldn't find it, could you plz provide the links?

**Comment by YHao29** [comment]
> I have solved partially this issue dowloading the Town06 and Town07 maps from here:
> 
> And I have copied them and pasted to this folder inside Apollo folder repo: **apollo/modules/map/data**
> 
> ![image](https://user-images.githubusercontent.com/43826438/149407126-72a0f47a-6aa4-4ba3-a7ed-7a7ad4622f9e.png)
> 
> Afterward, the maps have appeared in Dreamview: ![image](https://user-images.githubusercontent.com/43826438/149407197-bc04cc12-d492-4205-9eb1-e902903daee5.png)
> 
> **However** I was not able to add the Town03 map in Dreamview (From tutorial). Where do I get and download the code folder from **CARLA Town03** map?
> 
> Thanks in advance

thanks for your answer that makes me feel hopeful. But there is no any links after your description ：```I have solved partially this issue dowloading the Town06 and Town07 maps from here:```. And I have no idea about the detail operation. It will be great if you can release them. thank you.

**Comment by daohu527** [comment]
Since this issue is still under discussion. Here I make a summary.

## map
The map is divided into 2 sides, the simulation side and the apollo side
- simulation map, in carla, used for rendering, usually some 3d models. The formats are fbx, gltf, obj, max, Maya, can be imported into the simulation.
- apollo map, in apollo, used for autonomous driving, which we call `base_map.bin`

## apollo map
then we want to know how to get apollo map, The apollo map is optimized based on the opendrive format, and the lanes can be better represented by sampling.
If you have an opendrive map, you can use the [imap-box](https://github.com/daohu527/imap) to convert it to an apollo map

When the map conversion is complete, you should generate other 3 map types.
- base map. generate by imap, and put it in `modules/map/data/your_map_dir/base_map.bin`
- sim map. 
```
./bazel-bin/modules/map/tools/sim_map_generator -map_dir=/apollo/modules/map/data/your_map_dir -output_dir=/apollo/modules/map/data/your_map_dir
```
- routing map
```
/apollo/bazel-bin/modules/routing/topo_creator/topo_creator -map_dir=/apollo/modules/map/data/your_map_dir --flagfile=modules/routing/conf/routing.conf
```

Then restart the dreamview
```
./scripts/bootstrap.sh restart
```
