### ISSUE TITLE
Documentation for getting ML models input and output

### ISSUE THREAD

**Issue by ayu15031** [ApolloAuto/apollo#14278]
Hi,

I am very new to Apollo and want to work on Machine Learning model testing. I am able to successfully build and run Apollo dreamview using quickstart demo. However I am unable to understand how can I do module to module testing and in general getting Machine Learning model inputs and outputs and/or inputs and outputs at each step. Could you help me with how can I log the inputs and outputs before and after each model inference. Any documentation would be helpful. I tried using cyber_monitor but it just gives result for a particular module.

I want to:

1. Get instructions on running each module and each model independently.
2. Get the structure of input and output using logging.

I also tried using ADEBUG in the code and then run the recording using cyber_recorder play -f demo_3.5.record --loop
Then I checked the /apollo/data/logs folder however no logs for the module were found where I used ADEBUG.

Any documentation regarding this would be helpful. Thanks a lot.

**Comment by daohu527** [comment]
Your needs are a big project : )

First, I usually recommend narrowing down and specifying the problem, if you're just testing a deep learning model, what are you testing?
1. If you want to implement the functions of openai, usually you need to use it in conjunction with the simulator. 
2. If you want to debug the module, you can use the log AINFO or AERROR, If you want to use ADEBUG, you should open the 
https://github.com/ApolloAuto/apollo/blob/463fb82f9e979d02dcb25044e60931293ab2dba0/cyber/setup.bash#L41-L42
then enable it use, you can found the logs in `data\log`
```
source cyber/setup.bash
```
