### ISSUE TITLE
cgroup problem? Fail to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-xxxxxxx

### ISSUE THREAD

**Issue by lovelydett** [ApolloAuto/apollo#14275]
I was trying to install latest Apollo on an x86_64 machine with Ubuntu 21.10 and CUDA_11.5  .
Docker and NVIDIA Container Toolkit were installed.
```bash docker/scripts/dev_start.sh``` and all images were successfully pulled, but one of the containers seems unable to be created. Could someone help me with it? Thanks!

### System information

- **OS Platform and Distribution**: Ubuntu 21.10
- **Apollo installed from**: source
- **Apollo version**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:  
[INFO]     APOLLO_ROOT_DIR: /home/tt/Codes/apollo
[INFO]     APOLLO_CACHE_DIR: /home/tt/Codes/apollo/.cache
[INFO]     APOLLO_IN_DOCKER: false
[INFO]     APOLLO_VERSION: master-2021-12-28-463fb82f9e
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1

### Supporting materials (screenshots, command lines, code/script snippets):
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: container error: cgroup subsystem devices not found: unknown.
...
[ERROR] Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-x86_64-18.04-20210914_1336   + exit 1

**Comment by daohu527** [comment]
Instead of starting docker with root user, you can add your user to the docker group

**Comment by lovelydett** [comment]
I solve the problem by disabling cgroup i guess according to [this](https://github.com/NVIDIA/nvidia-docker/issues/1447#issuecomment-817293281)
