### ISSUE TITLE
routing has already provided a reference line but the planning module still failed to extract segments from routing

### ISSUE THREAD

**Issue by styj5** [ApolloAuto/apollo#14273]
### System information

- **OS Platform and Distribution Linux Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 6.0**:

### Steps to reproduce the issue:
- I'm connecting the apollo with LGSVL 20.06. I can see through dreamview that routing has already provided a reference line but the planning module still failed to extract segments from routing. However, this framework runs smoothly one day before. Is there anything unstable in apollo 6.0 that could raise such error?

Thanks in advance. 

### Supporting materials (screenshots, command lines, code/script snippets):
below are parts of the `nohup.output`
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.841025 36746 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.841032 36746 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.841039 36746 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.841058 36746 reference_line_provider.cc:203] [planning]Fail to get reference line
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.907341 36754 pnc_map.cc:175] [map]Cannot find waypoint: id = lane_13  s = 47.5889
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.907416 36754 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.907428 36754 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.907444 36754 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:16.907467 36754 reference_line_provider.cc:203] [planning]Fail to get reference line
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.123008 36744 pnc_map.cc:175] [map]Cannot find waypoint: id = lane_13  s = 47.5889
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.123064 36744 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.123073 36744 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.123082 36744 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.123102 36744 reference_line_provider.cc:203] [planning]Fail to get reference line
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.326292 36747 pnc_map.cc:175] [map]Cannot find waypoint: id = lane_13  s = 47.5889
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.326331 36747 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.326340 36747 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.326350 36747 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.326367 36747 reference_line_provider.cc:203] [planning]Fail to get reference line
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.841080 36745 pnc_map.cc:175] [map]Cannot find waypoint: id = lane_13  s = 47.5889
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.841140 36745 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.841156 36745 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.841167 36745 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.841189 36745 reference_line_provider.cc:203] [planning]Fail to get reference line
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.907457 36750 pnc_map.cc:175] [map]Cannot find waypoint: id = lane_13  s = 47.5889
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.907518 36750 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.907527 36750 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.907537 36750 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:17.907557 36750 reference_line_provider.cc:203] [planning]Fail to get reference line
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:18.123378 36744 pnc_map.cc:175] [map]Cannot find waypoint: id = lane_13  s = 47.5889
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:18.123428 36744 pnc_map.cc:421] [map]Failed to update vehicle state in pnc_map.
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:18.123438 36744 reference_line_provider.cc:538] [planning]Failed to extract segments from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:18.123447 36744 reference_line_provider.cc:580] [planning]Failed to create reference line from routing
[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0113 14:37:18.123466 36744 reference_line_provider.cc:203] [planning]Fail to get reference line

**Comment by Tcloser** [comment]
1. Please check whether the planning module starts normally.

2. Is the map used driveable?

3. I use the latest version of lgsvl and apollo6.0 several days ago，only a few maps were found to have elegant positioning.

**Comment by styj5** [comment]
Thanks a lot for the info!!! It's quite useful to me. 

I have one more question. I tried to generate some collision scenarios for apollo. But even if I keep all the settings the same, apollo will not always collide with the NPC every time I ran it. Why is apollo simulator not stable? Is there any way to improve it?

Thanks in advance and looking forward to your reply!

**Comment by LordonCN** [comment]
Hello @styj5 ,
There may be some bugs with the sensor data in the simulation. TBH Lgsvl and Apollo can only do some basic tests. 
Here is a bad news: https://www.svlsimulator.com/news/2022-01-20-svl-simulator-sunset/

**Comment by styj5** [comment]
Hello @LordonCN ,

thanks for the timely reply :smiley:
But in my case, apollo has perfect perception ability - i.e. directly feed it with the ground truth information. In my opinion, the bugs of sensor data shouldn't be a problem. What do you think?
And also thank you so much for forwarding me this news, it's really sad. :sob: Maybe I need to search for another simulation framework later. 

Have a nice day! :sunny:

**Comment by AkshayDesaiSDCE** [comment]
@styj5 did you find a solution to the problem? I am seeing a similar issue with the planner module failing.

**Comment by styj5** [comment]
@AkshayDesaiSDCE If you mean failed to generate reference line, you can turn to https://github.com/ApolloAuto/apollo/issues/12604; for reproduction the cases, my answer is no :(

**Comment by chenxiaoying21** [comment]
This issue is closed since the problem is solved.
