### ISSUE TITLE
Instruction to import pretrained modules to code

### ISSUE THREAD

**Issue by AdirRahamim** [ApolloAuto/apollo#14284]
Hi,

As part of a research project, I need to use the perception, prediction, and planner modules separately and as one pipeline, thus I need a way to import them as PyTorch modules to python code. 
I saw recent work of Baidu: https://arxiv.org/pdf/2106.09249.pdf where you imported the perception module as PyTorch module and gave a download link to pretrained model, however, I couldn't find the same models for prediction and planner(or any other module). I mean, I can find in you git pretrained modules for perception, however for other parts I can't find those.
I will appreciate any help regarding importing pretrained Apollo modules. 
Thanks in advance.

**Comment by daohu527** [comment]
@AdirRahamim I don't think it's possible to import the whole module as a python module, but you can try sending input and output to the module.

But what does this have to do with pytorch？If you need the source code of the model, currently only part of it is open in paddle3d
