### ISSUE TITLE
How to monitor different component running on different host?

### ISSUE THREAD

**Issue by rebornczs** [ApolloAuto/apollo#14286]
Using Cyber RT on different host (A/B) , Perception component on host B :

Can Monitor Module work with both component/channel on host A and B? 
Can I start or stop Perception component on host A dreamview while this component is runned on host B?

**Comment by ntutangyun** [comment]
Component running in different host may need to use the bridge to communicate. 

I think current implementation of dreamview does not allow you to shut down remote components. 

For this to work, you may need to update the dreamview backend... Or write your own event handler detecting the module switch and send this event to the remote host to command it start any component...

**Comment by daohu527** [comment]
@rebornczs Some additions, they don't need bridge unless across network segments

> Can Monitor Module work with both component/channel on host A and B?

Yes, cyber can work in different machines in a subnet, be sure they are on the same network segment

>  Can I start or stop Perception component on host A dreamview while this component is runned on host B?

Yes, but be sure dreamview service is running on `host B`, and the dreamview UI is on host A, then you can operate through dreamview.
