### ISSUE TITLE
gnss launch :  send data ubx file via udp, no data out 

### ISSUE THREAD

**Issue by wijdim** [ApolloAuto/apollo#14281]
System information
**Linux Ubuntu 18.04
**Apollo installed from source
**Apollo version master

###Question
I m trying to test localization module with some data in input , I made changes in modules/drivers/gnss in order to receive data via udp in UBX_BINARY format 
I receive my data in the gnss udp server. But the data can't achieve to ubx_parser and by cyber_monitor, the topic /apollo/sensor/gnss/stream_status is published with the following message : 
![image](https://user-images.githubusercontent.com/96061375/150345763-6820b364-16e0-458f-bb0b-fdcb8d3a2b73.png)
Ins_stream_type is still DISCONNECTED. 

==>
The data is sent to 4444 port and the new conf file is : 
![image](https://user-images.githubusercontent.com/96061375/150346214-3adb818e-74d7-41a0-bede-b2eb9fe70f86.png)

 ==> The log file is : 
![image](https://user-images.githubusercontent.com/96061375/150346476-52b24c06-e6cb-4c1b-85c9-7c302d63d937.png)

 *The server keep waiting to receive data, is there any other changes i should do or any explications? 

Thank you

**Comment by daohu527** [comment]
Are you now receiving data via udp and can't parse it? 

If you think the problem is "Ins_stream_type is still DISCONNECTED." then you can detect this state in your code first

**Comment by wijdim** [comment]
@daohu527 thank you for your answer.
 Yes I am now receiving data via udp but the process is interrupted  with an exception right after updating data_parser in DataParser::parseRawdata. cyber_launch unable to read the binary packet. 
![image](https://user-images.githubusercontent.com/96061375/151148493-1e2deea0-16dc-4ca5-adbb-b6381438d21d.png)

**Comment by daohu527** [comment]
There is already an error message, you can solve this problem first!

invalid start type
