### ISSUE TITLE
Car is very unstable and swerves from side to side as it tries to follow routing path.

### ISSUE THREAD

**Issue by josh-wende** [ApolloAuto/apollo#14282]
Hi,

Using the current master branch of Apollo with SVL simulator, my car exhibits the same behavior as shown in the video in issue #14142. I have `clock_mode` set to `MODE_MOCK` in `apollo/cyber/conf/cyber.pb.conf` and my car has a clock sensor publishing to the `/clock` channel.

When I put a 3D ground truth sensor on my car, which publishes the ground truth obstacle information, and run everything with perception switched off, the problem is greatly reduced or vanishes completely. This is why I figured it was a clock issue and tried to change to simulation time, but it doesn't seem to have worked. Is there something else I need to do?

**Comment by daohu527** [comment]
clock_mode MODE_MOCK is a nice feature, but I'm not sure if it always works.

I know it will provide a mock system time, but the sensor time is come from hardwares, this part of the time I am not sure if it will also be mocked, so there are some details waiting to be confirmed : )

**Comment by josh-wende** [comment]
@daohu527 Thank you for the response! I will mark this as closed now and make do. I think a fully-working MODE_MOCK would be a very useful feature though, the latency from running many modules (especially perception) is debilitating for many machines.
