### ISSUE TITLE
Planner "Fails to Update reference line after rerouting"

### ISSUE THREAD

**Issue by AkshayDesaiSDCE** [ApolloAuto/apollo#14292]
I am using Apollo 6.0 and I have an issue with the Planner. Once I get the route on the map successfully, I see that the planner gives me a "Failed to update reference line after rerouting" error if it is a little further away from the start of the route. Please see the attachment for the error details. My question is: 
1. Does the Planner depend on a distance/heading threshold within which it plans a path to the route? If so, where in the code is this? 
2. If for some reason, the planner dies and needs to be restarted, is it necessary to resend the route in order for the planner to continue on the path? 

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source or binary)*
- **Apollo version (6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2022-02-04 10-16-33](https://user-images.githubusercontent.com/39247736/152554963-9a9185ea-cc85-4086-b5ce-910a7218b584.png)

**Comment by AkshayDesaiSDCE** [comment]
Hi @daohu527 thanks for the comment. I however still see the issue being persistent. Consider the scenario below where the vehicle is a few meters away from the route (red line). I see that the planner goes to a "failed to update reference line after rerouting" state and stays there because a static variable "failed_to_update_reference_line" goes to true and stays true leading to the planner module shutting down.

Do you know where in the code the distance and heading thresholds are set for the planner to continue planning a valid trajectory in the presence of a route, albeit the route starting point being a few meters away? 

Also, I tried to add code that would restart the planner automatically but the error just converts to a 'Failed to create reference line". 

Any help with this would be greatly appreciated :) 

![Apollo_Planner_Start_Issue](https://user-images.githubusercontent.com/39247736/156049138-5192d736-8259-4044-9da5-4de08e4557da.png)

**Comment by daohu527** [comment]
there be two questions:
1. "the vehicle is a few meters away from the route (red line)", How could this happen? You deliberately constructed it, or after a similar emergency stop occurs, you need to continue driving
2. I noticed that this is at the intersection, you can try to manually give routing, if it still fails, then the high probability is a map related problem

**Comment by AkshayDesaiSDCE** [comment]
@daohu527 : 
1. The vehicle is at the start of the route. In the current state the planner seems to be too sensitive to being within a certain distance of the start point of the route. The route ofcourse is defined by me. But is there a way I can make the planner more flexible to start planning even when it is, say 10 meters away from the start of the route? I was not able to find which part of the code handles this. 
2. The planner is active when the vehicle is on the red line at the start of the route. When I move the vehicle away from that red line, the planner goes into a "Failed to update reference line after rerouting" error and the module needs to be restarted completely which is not the desired behavior.

**Comment by daohu527** [comment]
I don't quite understand what is your intention in doing this.  

1. You have planned a route, and then constructed it to keep the car away from this position. Then from the current position to the starting point of the route, who will plan the route? And you need to ensure that the vehicle is reachable, that is to say, the support of the map is required. The vehicle cannot travel to the starting point without a road

2. If you are testing the need for rerouting when the location changes, which I think it is reasonable, and the vehicle needs to re-route the path to start at new position.
