### ISSUE TITLE
Apollo6.0 and lgsvl simulator gives error in planing module while modular testing autopilot. 

### ISSUE THREAD

**Issue by Addi2020** [ApolloAuto/apollo#14297]
linux Ubuntu 20.04.3 LTS
Apollo6.0 

svlsimulator-linux64-2021.2.2

steps to follow:

1. bridge connection between apollo6.0 and simulator
#############################################
bash docker/scripts/dev_start.sh -l -t apollo_6.0
bash docker/scripts/dev_into.sh

./apollo.sh clean
./apollo.sh build_opt_gpu

bash scripts/bootstrap_lgsvl.sh
bash scripts/bridge.sh
################################################
![Screenshot from 2022-02-08 12-29-10](https://user-images.githubusercontent.com/61130487/152989001-b2a407f6-eac1-4f4c-a133-695cd9099422.png)

![Screenshot from 2022-02-08 12-29-16](https://user-images.githubusercontent.com/61130487/152989010-40a55e9f-33a5-40f5-814f-d9c350ebc419.png)
![Screenshot from 2022-02-08 12-29-49](https://user-images.githubusercontent.com/61130487/152989062-725f0e01-2117-440d-ba1c-d647050d7334.png)

#########################################################
2. Run LGSVL simulator with apollo6.0 and modular testing

![Screenshot from 2022-02-08 12-32-06](https://user-images.githubusercontent.com/61130487/152988876-de466214-6aa4-4e40-8098-89f1ad034859.png)
##################################################################
3. turn on localization, planing, prediction, routing, traffic lights, transform and at the end when turn on Control module the car break at 10% and cannot move according to routing.  
##############################################################
4. All log files are correct except planning log. as shows 

![Screenshot from 2022-02-08 12-30-50](https://user-images.githubusercontent.com/61130487/152988927-fb91a251-e326-43d2-83c9-38092e0d4fd2.png)
![Screenshot from 2022-02-08 12-31-03](https://user-images.githubusercontent.com/61130487/152988950-82c36119-d8ca-4014-8a61-5a4209aff1e9.png)
![Screenshot from 2022-02-08 12-31-11](https://user-images.githubusercontent.com/61130487/152988972-93de848b-aa7f-45d5-aa57-dd8e26808ef7.png)

**Comment by daohu527** [comment]
You should check routing messages, you can use `cyber_monitor` in cmd and check the `/apollo/routing_response` msg

Or, simply, choose another destination to try

**Comment by Addi2020** [comment]
@daohu527 I also upload screenshort of cyber_monitor. I have tried may different routing point but the car do not move.
![Screenshot from 2022-02-08 12-29-49](https://user-images.githubusercontent.com/61130487/153572912-3c6c185c-76e8-4ce5-936d-58e43662634c.png)

**Comment by daohu527** [comment]
You can check the routing module log for errors and then feedback

**Comment by Addi2020** [comment]
log file for control, routing and planing. only planing modules have errors.
![Screenshot from 2022-02-11 15-29-44](https://user-images.gith
![Screenshot from 2022-02-11 15-26-57](https://user-images.githubusercontent.com/61130487/153620131-58b67210-440f-4a45-8037-065b310c1101.png)
ubusercontent.com/61130487/153620075-6817b970-d4b0-48ed-9aa9-f35172591d81.png)
![Screenshot from 2022-02-11 15-27-22](https://user-images.githubusercontent.com/61130487/153620097-733534fe-45fa-4d92-b012-d867019886ba.png)
![Screenshot from 2022-02-11 15-27-52](https://user-images.githubusercontent.com/61130487/153620147-da71c02b-072b-48ea-bc0d-9f0068f760b9.png)

![Screenshot from 2022-02-11 15-27-42](https://user-images.githubusercontent.com/61130487/153620139-f869b67a-ea0f-4540-8038-7701faabdaf5.png)

**Comment by daohu527** [comment]
You should debug this function `GetRouteSegments` and find what's wrong

**Comment by gaohongfein** [comment]
I have the same problem

**Comment by daohu527** [comment]
You can add a debug message to help with debugging, at least to find where it failed, then we can discuss the reason, from your description, it is difficult to confirm the problem at the moment

**Comment by Addi2020** [comment]
@daohu527  According to log files, routing works fine as you can see above routing log file but the planning module have issues creating reference line due to which the control module applied break and the car do not move. If any one can help?

E0221 15:34:12.404063 13470 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.454237 13476 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.504894 13468 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.556433 13472 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.616994 13477 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.667268 13470 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.726668 13466 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.786689 13465 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.848915 13463 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.908339 13465 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.961871 13464 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:12.968705 13463 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:12.969012 13463 planning_component.cc:157] Input check failed
E0221 15:34:13.018165 13465 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.070691 13476 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.106557 13463 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:13.106628 13463 planning_component.cc:157] Input check failed
E0221 15:34:13.129710 13470 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.179800 13478 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.205310 13463 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:13.205363 13463 planning_component.cc:157] Input check failed
E0221 15:34:13.234984 13465 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.285073 13473 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.286598 13464 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:13.286659 13464 planning_component.cc:157] Input check failed
E0221 15:34:13.342861 13469 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.375805 13473 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:13.375869 13473 planning_component.cc:157] Input check failed
E0221 15:34:13.400177 13464 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.452632 13469 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.482096 13472 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:13.482156 13472 planning_component.cc:157] Input check failed
E0221 15:34:13.508338 13464 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.562202 13469 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.584287 13475 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:13.584367 13475 planning_component.cc:157] Input check failed
E0221 15:34:13.623659 13464 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.682899 13469 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:13.705551 13471 planning_component.cc:246] routing not ready; skip the planning cycle.
4:31.053089 13467 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:31.110962 13472 reference_line_provider.cc:196] Routing is not ready.
E0221 15:34:31.131552 13473 planning_component.cc:246] routing not ready; skip the planning cycle.
E0221 15:34:31.131621 13473 planning_component.cc:157] Input check failed
E0221 15:34:31.169167 13467 reference_line_provider.cc:196] Routing is not ready.
I0221 15:34:31.171778 13474 planning_component.cc:67] Received routing data: run routing callback.timestamp_sec: 1645457666.640734
module_name: "routing"
sequence_num: 0
E0221 15:34:31.232051 13463 reference_line_provider.cc:196] Routing is not ready.
W0221 15:34:31.255803 13468 reference_line_provider.cc:257] Reference line is NOT ready.
E0221 15:34:31.255827 13468 reference_line_provider.cc:259] Failed to use reference line latest history
E0221 15:34:31.288705 13477 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.288720 13477 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.288750 13477 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.342316 13465 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.342329 13465 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.342350 13465 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.405269 13476 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.405283 13476 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.405314 13476 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.457254 13473 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.457268 13473 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.457294 13473 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.513119 13476 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.513130 13476 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.513154 13476 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.572556 13473 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.572571 13473 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.572597 13473 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.626756 13474 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.626770 13474 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.626808 13474 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.685940 13473 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.685956 13473 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.685986 13473 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.739964 13467 reference_line_provider.cc:538] Failed to extract segments from routing
E0221 15:34:31.739997 13467 reference_line_provider.cc:580] Failed to create reference line from routing
E0221 15:34:31.740029 13467 reference_line_provider.cc:203] Fail to get reference line
E0221 15:34:31.796655 13465 reference_line_provider.cc:538] Failed to extract segments from routing

**Comment by daohu527** [comment]
could you pls check the `vehicle_state`, and print it out?

**Comment by Addi2020** [comment]
@daohu527 @gaohongfein 
I have upgrade from Apollo6.0 to Apollo7.0 and it works fine for Apollo7.0 but there is a some issue with localization of Apollo7.0 because to start working autopilot the vehicle need a small push using keyboard control to get localization and the after words it works fine.  I hope it helps for others.
