### ISSUE TITLE
How can I get a record with sensor data (lidar, camera, IMU, GPS...)

### ISSUE THREAD

**Issue by lovelydett** [ApolloAuto/apollo#14294]
I've been trying Apollo with demo_3.5.record with all modules on, but I noticed none of them is really doing calculation since there are already "results" (perception results, localization results, planning results, etc.) in that .record but no raw sensor data (lidar, camera). Therefore I assume this demo is more like playing a movie rather than auto-driving. I wonder whether or not I could extract pure sensor data from this .record file to get those calculation modules working, or if I could get them elsewhere, thanks!

Best,
Yuting

**Comment by lovelydett** [comment]
bd

**Comment by lovelydett** [comment]
bdbdbd

**Comment by daohu527** [comment]
Yes, there's no raw sensor data. 

There is currently no ready bag to share, and the best way to publish these messages is through an simulator.
Of course, it is also feasible to make a ROSbag to apollo bag and then use the existing data.

I suggest you can try the simulator first

**Comment by lovelydett** [comment]
> 

Thanks, try LGSVL and it works.
But I still wonder could any open real-world data-set be fed to Apollo, like KITTI. Any method would you recommend to compose a .record with KITTI raw data?

**Comment by daohu527** [comment]
Yes, your proposal is very good, it needs to do a conversion tool. There are actually several tools that are very necessary
1. opendrive to apollo map
2. rosbag to apollo bag
3. any lidar slam algorithm to cyber rt

**Comment by lovelydett** [comment]
> Yes, your proposal is very good, it needs to do a conversion tool. There are actually several tools that are very necessary
> 1. opendrive to apollo map
> 2. rosbag to apollo record
> 3. any lidar slam algorithm to cyber rt
> 
> I'll improve some of it when I have time

Thank you so much!
