### ISSUE TITLE
Multi sensor fusion details

### ISSUE THREAD

**Issue by AdirRahamim** [ApolloAuto/apollo#14290]
Hi,
Is there any source of information(paper preferably) that describes how the camera-lidar fusion is performed? i.e. from the perception pipeline, I can see that apollo runs two separate detection networks on the camera and lidar inputs, but I couldn't find any technical information about how the fusion on the two detection networks is performed. I'll appreciate any details you can provide. Thanks.

**Comment by daohu527** [comment]
@AdirRahamim There are currently no papers covering sensor fusion, we will add some documentation in the future. Thank you for your attention!
