### ISSUE TITLE
Compressed_image can not be displayed by cyber_visualizer

### ISSUE THREAD

**Issue by songwenhuang** [ApolloAuto/apollo#14296]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04.
- **Apollo installed from (source or binary)**: source in the docker.
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0.
- **Output of `apollo.sh config` if on `master` branch**:

[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: r6.0.0-2021-07-06-91dd437248
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20200914_0742
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- The compressed_image is transmitted with the proto format as apollo.drivers.compressedImage.
- In the tool cyber_visualizer, click on "Add Image": the channel section is empty, i.e., the channel for compressed_image cannot be selected for visualization.

**Comment by songwenhuang** [comment]
The channel for the compressed image can be selected after modifying the naming to include "camera."

However, after clicking on "Play," the window for displaying compressed_image was still in a white window and nothing was streamed by the cyber_visualizer.

Anyone has any clue for this? Thanks.

**Comment by songwenhuang** [comment]
I am using v6.0.0. The image still cannot be displayed by the cyber_visualizer. The issue as in [#8022](https://github.com/ApolloAuto/apollo/issues/8002) still exists in the master branch.

**Comment by daohu527** [comment]
@songwenhuang You can use modules/tools/record_parse_save/parse_camera.py to parse Compressed_image. And I will check cyber_visualizer later
