### ISSUE TITLE
Apollo v7.0 camera perception model smoke

### ISSUE THREAD

**Issue by umiskky** [ApolloAuto/apollo#14305]
### System information
- **Linux Ubuntu 18.04**
- **Apollo v7.0**

### Steps to reproduce the issue:
- I get smoke weight file ***smoke_libtorch_model.pth*** from latest docker image.
- I try to run this model in python environment using codes as follows:
```python
    smoke = SmokeInference((1920, 1080))
    model_path = "../data/smoke_libtorch_model.pth"
    model = torch.jit.load(model_path)
    model.eval()

    input_feature_data = np.zeros([1, 3, smoke.shape_map['data'][1], smoke.shape_map['data'][2]], dtype=np.float32)
    input_feature_tensor = torch.from_numpy(input_feature_data).cuda(0)
    tensor_down_ratio = torch.tensor([8.0, 8.0], device='cuda', dtype=torch.float32).view(smoke.shape_map['ratio'])
    tensor_K = torch.tensor([[[1.0, 0, 0], [0, 1.0, 0], [0, 0, 1.0]]], dtype=torch.float32).cuda(0)

    output = model.forward(input_feature_tensor, (tensor_K, tensor_down_ratio))
    print(output.shape)
```
- I always get a same error(fig1)  no matter how I change the input_feature_data shape (I guessed at first that it might be the input size mismatch).
- Since I'm not very familiar with torchscript and libtorch, I'm not quite sure if this model can only run under c++ environment or because of other issues.
- I’ll appreciate it if anyone could help me.

### Supporting materials
fig1
![image](https://user-images.githubusercontent.com/77867922/153735626-3b10581b-b47d-413d-a419-9433f86e9676.png)

**Comment by umiskky** [comment]
- 有没有一种可能是libtorch版本不匹配

**Comment by tabaddor** [comment]
How did you resolve this issue?

**Comment by umiskky** [comment]
I find the input shape of the smoke model is 640*960.

**Comment by umiskky** [comment]
> How did you resolve this issue?

I find the input shape of the smoke model is 640*960.

**Comment by umiskky** [comment]
> > > How did you resolve this issue?
> > 
> > 
> > I find the input shape of the smoke model is 640*960.
> 
> Hello, were you able to properly generate 3D BBOX? I was able to generate 2D BBOX but 3D BBOX doesn't fit properly when compared to ground truth

https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/3d_vision/SMOKE may help you

**Comment by umiskky** [comment]
![image](https://user-images.githubusercontent.com/77867922/172031927-42d2e748-a696-4059-974d-79f1e21cc543.png)
alpha SMOKE论文中的 alpha z
3D Box预测信息有3D Box大小以及Box下平面的中心点(注意并不是Box的中心点)

**Comment by rodhw** [comment]
I get the same error simply by running Apollo Perception Camera Module with all default settings. How did you solve it?
