### ISSUE TITLE
PIDBCController should multiply a factor on integral term?

### ISSUE THREAD

**Issue by lycismail** [ApolloAuto/apollo#14308]
File modules/controll/common/pid_BC_controller.cc
line num 57

integral_ += kaw_ * aw_term + error * dt;

Here the aw_term will work after the system into the saturation state. Before that, this term will be equal to zero.
So the integral_ will lose the feature of Ki parameter, the later part should be like "error * dt * ki_" here ?

**Comment by daohu527** [comment]
It seems you are right.

**Comment by chenxiaoying21** [comment]
This issue is closed due to long time no reply.
