### ISSUE TITLE
libc10.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by defuZhu** [ApolloAuto/apollo#14307]
when i debug the Apollo 6.0's planning module code in VSCode  in Ubuntu18.04,  there are an error " [mainboard]poco LibraryLoadException: libc10.so: cannot open shared object file: No such file or directory ", this error result in the program failed. How to solve this problem?

when  "args": ["-d","/apollo/modules/planning/dag/planning.dag"],   changed 
              "args": ["-d","/apollo/modules/localization/dag/dag_streaming_msf_localization.dag"],
there are no errors. 

In VSCode ,the launch.json is:
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "/apollo/bazel-bin/cyber/mainboard",
            **"args": ["-d","/apollo/modules/planning/dag/planning.dag"],**

            "stopAtEntry": false,
            "cwd": "/apollo",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",

            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            // "preLaunchTask": "C/C++: g++ 生成活动文件",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}

The errors in terminator are :
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0213 20:56:13.039528 11365 module_argument.cc:81] []command: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-dbg/bin/cyber/mainboard -d /apollo/modules/planning/dag/planning.dag 
I0213 20:56:13.039855 11365 global_data.cc:153] []host ip: 192.168.3.8
W0213 20:56:13.039862 11365 environment.h:33] []Environment variable [CYBER_PATH] not set, fallback to 
I0213 20:56:13.040624 11365 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I0213 20:56:13.040634 11365 module_argument.cc:60] []dag_conf: /apollo/modules/planning/dag/planning.dag
E0213 20:56:27.844175 11365 class_loader_utility.cc:220] [mainboard]poco LibraryLoadException: libc10.so: cannot open shared object file: No such file or directory
E0213 20:56:27.844211 11365 class_loader_utility.cc:236] [mainboard]poco shared library failed: /apollo/bazel-bin/modules/planning/libplanning_component.so
E0213 20:56:27.844233 11365 class_loader_manager.h:70] [mainboard]Invalid class name: PlanningComponent
E0213 20:56:27.844249 11365 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/planning/dag/planning.dag
E0213 20:56:27.844255 11365 class_loader_utility.cc:258] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/planning/libplanning_component.so
E0213 20:56:27.844259 11365 mainboard.cc:39] [mainboard]module start error.

**Comment by daohu527** [comment]
I found `libc10.so` is used by pytorch, The latest planning does use torch, are you sure the code and container version match?

**Comment by defuZhu** [comment]
Thanks.  
The Apollo code version is  **r 6.0.0** ,   
the container version is 

$ bash docker/scripts/dev_start.sh
[INFO] Use default GeoLocation settings
[INFO] Start pulling docker image apolloauto/apollo:**dev-x86_64-18.04-20200914_0742** ...
dev-x86_64-18.04-20200914_0742: Pulling from apolloauto/apollo
Digest: sha256:f5724a46510d64edd5f23c55eeab664ee1196480de49ed3818a8513469b69f82
Status: Image is up to date for apolloauto/apollo:dev-x86_64-18.04-20200914_0742
docker.io/apolloauto/apollo:dev-x86_64-18.04-20200914_0742

I don't know are they matched.   if I want to debug the code in 6.0, how to add the libc10.so ?  Thank you!

**Comment by daohu527** [comment]
Seems they are match, pls run below cmd to init env first
```
source scripts/apollo_base.sh
```

**Comment by defuZhu** [comment]
Thank you !!! 
It's work now!  There are no the` /libtorch_cpu/ `directory in `/usr/local/ `before, i download `libtorch `from website.   when before pushing `F5` to debug in VSCode ,   need to execute  `source scripts/apollo_base.sh` .

**Comment by Leason-ly** [comment]
> Thank you !!! It's work now! There are no the`/libtorch_cpu/`directory in `/usr/local/ `before, i download `libtorch `from website. when before pushing `F5` to debug in VSCode , need to execute `source scripts/apollo_base.sh` .

hello,i am confronted with the same proplem as you. can you describle your approach more detailly? should i download libtorch outside the docker and remake the new folder named "/libtorch_cpu/"?

**Comment by daohu527** [comment]
I found libc10.so is already in `ls /usr/local/libtorch_cpu/lib/`, it should be found by the `ld` linker
