### ISSUE TITLE
Conecpt: TEST vs COVERAGE. Difference?

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#14301]
Hi I was following this tutorial: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/apollo_build_and_test_explained.md

To test and coverage Apollo Modules. At first I have issued on terminal:

` bash apollo.sh test cyber`

I had this output:

![image](https://user-images.githubusercontent.com/43826438/153478136-ab47ed99-3b53-48eb-87e0-ff73d8ea1a1d.png)

Afterwards, I have issued:

`bazel coverage modules/planning/…`

Anmd I had a very similar output:

![image](https://user-images.githubusercontent.com/43826438/153478356-f38de23e-3977-408a-8043-d9950e178e21.png)

In both cases I have a lot of information displayed on terminal and at the end **"PASSED** or **FAILED** info.

Then I do not understand the **difference** to use "**test**" and use "**coverage**" commands. Would somebody know to explain me which is ?

**Comment by daohu527** [comment]
These are the bazel commands, according to the office manual.

> [Coverage Options](https://docs.bazel.build/versions/0.25.0/command-line-reference.html#coverage-options) Inherits all options from [test](https://docs.bazel.build/versions/0.25.0/command-line-reference.html#test).

so they're the same

**Comment by marcusvinicius178** [comment]
I understand the fact that **coverage** inherits all options from **test**, as well as **test** inherits from **build**, however the last ones are not the same. When building apollo I do not have the same output messages: "PASSED OR FAILED" as I have issuing **test**. 

Therefore I would like to understand if **coverage** has more commands or different goal as **test**.... I mean, I think that **coverage** is a different **approach** of **test**. And I would like to know this difference, if is there difference? Because if is not any difference, any additional info given by **coverage** command, why should it exist, besides **test**...it would be a redundant command right? Are these commands really the same?

**Comment by daohu527** [comment]
I was wrong, This option is inherited from test, But they function differently

coverage | Generates code coverage report for specified test targets.
test | Builds and runs the specified test targets.

**Comment by marcusvinicius178** [comment]
Hi @daohu527 thanks very much for the clarification. Just one last question before closing this issue (is not related). Does Apollo offers an own simulator to run along Apollo stack? I have watched this video: https://youtu.be/-47b4UQMblM

It seems pretty cool, I have also requested to test the simulation in Apollo commercial website, sending my e-mail. I have read the Dreamland section, Apollo Studio Premium Features (Cloud Services), scenarios edition....etc.

Then I ask myself if this Apollo Game Simulator is already available? Is it free or is it a premium feature?

Could you please share this info? If Premium how to request access? Our research team have interest...thanks in advance

**Comment by daohu527** [comment]
Yes, there are related products but need to apply, you'd better contact the relevant personnel by email

The following is the simulation of the cloud platform
https://apollo.auto/platform/simulation.html

**Comment by KAndHisC** [comment]
I am the same as you here, and the `bash apollo.sh coverage` does not output any report. After printing a lot of PASSED and FAILED, the script ends by itself, and the subsequent commands in the script are not actually executed.

Does anybody know how to fix it?
