### ISSUE TITLE
Perception module on local computer

### ISSUE THREAD

**Issue by aborzagit** [ApolloAuto/apollo#14303]
Followed the steps described in https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md.

1. Bags aren't supported by cyber_recorder. Is there a way to use bags with master?
2. When playing demo_3.5.record, does Apollo stack actually drive the car or the recording embeds the control as well? It looks like the car follows same route even if /apollo/perception/obstacles /apollo/perception/traffic_light /apollo/prediction /apollo/planning channels were removed from the record.

Thanks

**Comment by daohu527** [comment]
Bags aren't supported by cyber_recorder. Is there a way to use bags with master?

> Ros bag is not supported by apollo. There are currently no ready bags to use

When playing demo_3.5.record, does Apollo stack actually drive the car or the recording embeds the control as well? It looks like the car follows same route even if /apollo/perception/obstacles /apollo/perception/traffic_light /apollo/prediction /apollo/planning channels were removed from the record.

> Playing the bag causes the car to copy the behaviour, which was the previous behaviour record pack. So you should only play raw sensor data if you want the system to work in real time. Except the demo_3.5.record has no raw sensor data, you should try some simulation(lgsvl, carla) then

**Comment by aborzagit** [comment]
This makes sense.
Thank you!
