### ISSUE TITLE
Load Apollo Pre-trained Obstacle Detector Model into PyTorch

### ISSUE THREAD

**Issue by tabaddor** [ApolloAuto/apollo#14311]
### System information

- **Linux Ubuntu 20.04**:
- **Apollo installed from (source)**:
- **Apollo version (7.0)**:

Hello, 

I would like to use Apollo's obstacle detector model on its own, however, I have not found much documentation on loading Apollo's pre-trained models into PyTorch. I am able to successfuly convert 3d-r4-half's `deploy.pt` and `deploy.model` to PyTorch via a method like [this](https://github.com/ASGuard-UCI/MSF-ADV), however, I cannot do the same for [3d-yolo](https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-yolo)'s `deploy.pt` and `deploy.model` due to errors regarding the blobs.

More precisely, my questions are:

1. How may I go about loading Apollo's obstacle detector model to use independently offline (if there is a more streamlined way)? 
2. Aside from [this .pth file](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/smoke-config.pt), where can I find the model and weight files for the SMOKE?
3. And finally, when running Apollo, how may I select which model to be used for camera obstacle detection?

**Comment by josh-wende** [comment]
I tried doing this also, but I don't know if PyTorch supports every type of layer that appears in some of the Caffe prototxt, though I don't remember the exact problems I came across. I found it easier to use OpenCV, which has functions to load a neural network from the Caffe files which worked well. If you want to run the models on a GPU (I'm sure you do) you'll have to build OpenCV from source with GPU support, as the OpenCV binaries do not include this functionality.

**Comment by tabaddor** [comment]
Apollo maintainers, can the [deploy.model](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-yolo/deploy.model) be updated for [3d-yolo](https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-yolo)? It is currently an empty file.

**Comment by umiskky** [comment]
Smoke model file in docker image is a libtorch model, and I have been able to load it in pytorch using `torch.jit.load()`.

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by YCC-324** [comment]
@tabaddor Hello, I have some questions about the outputs of the model in 3d-r4-half. After loading 3d-r4-half's deploy.pt and deploy.model in MSF-ADV, which outputs can be used for further processing. There are too many outputs for the model. Thanks very much.
