### ISSUE TITLE
MSF localization thinks the vehicle is always slowly spinning

### ISSUE THREAD

**Issue by josh-wende** [ApolloAuto/apollo#14312]
Hi,

I'm trying to get MSF localization running with LGSVL simulator. I made a local map of their CubeTown level, but the localization results are generally way off. I have attached a video that shows this behavior, you can see that once the vehicle is remaining stationary, the fusion localization result hones in on the correct position (but the orientation is still off due to the spinning). I have tried to figure out the source of the erroneous angular velocity, but have been unable to track it down. Do you have any ideas what might be causing this?

The possible sources of the issue that I have thought of are:
1. Nothing is published to the `/apollo/sensor/gnss/heading` topic, which the MSF localization component subscribes to.
2. Could it be an issue with the extrinsic calibration of the lidar on the vehicle?
3. The sins functions, but these are not open source. I don't know how it tries to remove bias from the sensor readings.

Any insight would be appreciated. Thanks in advance for the help!

https://user-images.githubusercontent.com/93289658/154392378-91cc585e-e1d4-4631-941f-71c28def8be3.mp4

**Comment by daohu527** [comment]
How did you create the local map and visualization, actually this part is not open source.

**Comment by josh-wende** [comment]
Hi @daohu527, I used the `msf_simple_map_creator.sh` script to create the local map from a cyber record recorded in LGSVL. I didn't record too much data, so the resulting local map is a bit fuzzy, but that doesn't seem like the issue here.

**Comment by daohu527** [comment]
As mentioned before, you can mock the location and tf, just send the corresponding message

**Comment by BlackChg** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
