### ISSUE TITLE
Show obstacle bounding boxes in Dreamview

### ISSUE THREAD

**Issue by aborzagit** [ApolloAuto/apollo#14310]
System information

-  Linux Ubuntu 18.04
- Apollo installed from source 
- [INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2021-12-28-463fb82f9e
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210914_1336
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

Is it possible to show obstacles bounding boxes in Dreamview or other tools?
I'm running in reality mode, feeding data to Apollo using /dev/video0. Yolo obstacle detection and lane detection work properly (as seen in logs). Can I visualize the obstacles bounding boxes?

![image](https://user-images.githubusercontent.com/41903399/154279125-93c8bffa-14e9-4506-bc1f-9dcdf18f5138.png)

Thanks!

**Comment by ntutangyun** [comment]
is the dreamview main screen not showing obstacles ? or you wish to show the obstacle bounding boxes in the camera view ?

**Comment by aborzagit** [comment]
![image](https://user-images.githubusercontent.com/41903399/154907422-32835eab-5596-4716-bea7-f7c2ef5dc027.png)

Dreamview main screen is not showing obstacles, it doesn't build the virtual environment based on the video input. Can this be done based on video input alone? The image shown in dreamview main screen was activated when I ticked _**Sim Control**_.
So, yes, I'd like either to see the obstacles in dreamview main screen or in camera view.
I started the following modules:
- /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
- /apollo/modules/perception/production/dag/dag_streaming_perception_lane.dag
- a custom version of: modules/drivers/camera/dag/camera.dag
- video input is coming from /dev/video0
In dreamview I ticked _**Sim Control**_ so I could then enable _**Camera Sensor**_ which in turn enabled _**Camera View**_.

**Comment by lhakim85** [comment]
> is the dreamview main screen not showing obstacles ? or you wish to show the obstacle bounding boxes in the camera view ?

@ntutangyun, is there a way to show the bounding boxe in the camera view?

**Comment by diaokaitian** [comment]
you can check if the prediction module pulish the obstacle message correctly

**Comment by LuoXin0826** [comment]
To show the obstacle in dreamview, you need to have prediction running

**Comment by LuoXin0826** [comment]
To show the obstacle in dreamview, you need to have prediction running. And make sure /apollo/prediction channel shows up appropriately as @diaokaitian mentioned

**Comment by aborzagit** [comment]
Thanks for the replies. 
This ticket can be closed now.
Cheers!
