### ISSUE TITLE
does apollo 6.0 has active  lane chage algorithm to pass the car ahead（just in  a relatievely low speed）  in the lane follow  scenario ？

### ISSUE THREAD

**Issue by diaokaitian** [ApolloAuto/apollo#14316]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version (6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
You mean `relatievely low speed` ? Then how can we keep the car following? If this function on, the car always wants to overtake or slow down

**Comment by chenxiaoying21** [comment]
You can refer to "PathLaneBorrowDecider" for this function. The ego vehicle need decide if it can borrow the lane first and then calculate the bypassing path.

**Comment by chenxiaoying21** [comment]
This issue is closed due to long time no reply.
