### ISSUE TITLE
Configs for valet parking work

### ISSUE THREAD

**Issue by IDovgopolik** [ApolloAuto/apollo#14319]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0

### Steps to reproduce the issue:
Hello to all! I'm trying to run valet parking. I created the parking space as described in [#13822](https://github.com/ApolloAuto/apollo/issues/13822) and I'm sending the routing request manually via mock_routing_request as described in [#13950](https://github.com/ApolloAuto/apollo/issues/13950) but this doesn't work for me. The valet parking scenario starts, but crashes on the approach parking spot stage. I'm using the default configs for apollo 6.0. Do I need to change configs for turning on the valet parking? And if yes, which configs do I need to change?

**Comment by daohu527** [comment]
The required configuration and steps have been explained in detail #13950 , you can see where the problem is, and then solve the specific problem.

**Comment by IDovgopolik** [comment]
@daohu527 thank you for the quick answer! So I don't need to change any configs in files such as planning_gflags or planning.conf for turning on the open space planner and another necessary functions/modules? Is everything enabled by default?

**Comment by daohu527** [comment]
Please pay attention to the map, I think you better have a successful map to try

**Comment by IDovgopolik** [comment]
@daohu527 , you are right! The problem was in the type of a lane boundary. Valet parking works with default settings of apollo planning module. Thanks for help!
