### ISSUE TITLE
[planning] failed to make a driving plan during a junction turn

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#14327]
Hi, found this planning bug in sim control mode.

![failed_to_make_a_driving_plan](https://user-images.githubusercontent.com/16061105/155718095-5627e1c3-b191-42f3-af02-eba3f7ed3b1b.png)

[video](https://entuedu-my.sharepoint.com/:v:/g/personal/yun005_e_ntu_edu_sg/EbfYM9l0syZOtONKlPlhFHcBPj9pRqoaY7a7X0pJ54S47g?e=a4x57a)

[recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EctRPOTh9PREkdEB6ev16sUBhE4kCK1iVRGm9rw9FKxW-A?e=7eWazT)

[HD Map](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EeyN0nJVdEFBtP0VMwApJTEBSixUkwylK5PsFM8wiHp-1Q?e=tmjhKH)

To Reproduce
please see the video.

Expected behavior
Planning should be able to navigate the junction smoothly.

Desktop (please complete the following information):

OS: ubuntu 1804

**Comment by xli149** [comment]
@ntutangyun 
Hi, I'm facing the same issue. Trying figure out what is happening behind it. Could you please provide some suggestions? 

Best

**Comment by ntutangyun** [comment]
I'm not quite sure. Maybe because the turning angle is too sharp...
