### ISSUE TITLE
Duang! HMI has been integrated with Dreamview. Please have a try and help us improve :) 

### ISSUE THREAD

**Issue by matchon** [ApolloAuto/apollo#1432]
I can Access localhost:8887, It shows Duang! HMI has been integrated with Dreamview. Please have a try and help us improve :) , but i can't accesss localhost:8888

**Comment by xiaoxq** [comment]
When you start HMI with scripts/hmi.sh, it should also notify that
"Please use scripts/bootstrap.sh to start the system."

So if you'd like to try the new workflow, please run
`
# Stop HMI.
./scripts/hmi.sh stop

# Start Dreamview and other facilities.
./scripts/bootstrap.sh start
`

**Comment by fartisan** [comment]
That 's what I meet today, updated src and rebuild success ,but fail when run bootstrap:

fire@in_dev_docker:/apollo$ scripts/bootstrap.sh start
Start roscore...
/apollo/scripts/apollo_base.sh: line 224:   462 Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/monitor/monitor --flagfile=modules/monitor/conf/monitor.conf --log_dir=/apollo/data/log monitor monitor < /dev/null > /apollo/data/log/monitor.out 2>&1
Could not launch module monitor. Is it already built?
/apollo/scripts/apollo_base.sh: line 224:   470 Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --log_dir=/apollo/data/log dreamview dreamview < /dev/null > /apollo/data/log/dreamview.out 2>&1
Could not launch module dreamview. Is it already built?
Dreamview is running at http://localhost:8888

**Comment by xiaoxq** [comment]
Could you check if these binaries exist?
/apollo/bazel-bin/modules/monitor/monitor
/apollo/bazel-bin/modules/dreamview/dreamview

They should be available if the build is a success.

**Comment by xiaoxq** [comment]
The old version of HMI has been retired.
Please run bootstrap.sh directly. Feel free to create another issue if you meet problem.

**Comment by kkyiss** [comment]
Hey @fartisan  @xiaoxq 
I've met the same problem, after i successfully build ok
`bash apollo.sh build`

And the both binaries are existed (monitor, dreamview)
Any hints to solve this problem?

**Comment by xiaoxq** [comment]
Not sure if it's a recent bug which I'm fixing in https://github.com/ApolloAuto/apollo/pull/1765
Please have a try with the newest code when it's merged.

**Comment by linux-devil** [comment]
Is it fixed ? I am facing similar issue in Apollo 2.5

**Comment by xiaoxq** [comment]
Which issue? Are the binaries available?

**Comment by linux-devil** [comment]
@xiaoxq ignore above , "Not sure if it's a recent bug which I fixed in #1765" hepled. Thanks
