### ISSUE TITLE
How to examine /perception/inner/* channels in cyber_monitor?

### ISSUE THREAD

**Issue by lovelydett** [ApolloAuto/apollo#14323]
I am working with LGSVL and bridge, with these modules on:

![Screenshot from 2022-02-23 16-14-54](https://user-images.githubusercontent.com/32383645/155282297-233b5086-eb16-4c77-9d55-4afefa36efc4.png)

When I check cyber_monitor and cyber_node for detailed channels/nodes information, I notice node SensorFusion only has writer channels but no readers:

![Screenshot from 2022-02-23 16-14-19](https://user-images.githubusercontent.com/32383645/155282229-108760a3-74eb-4f39-a6f3-d164c6ec98af.png)

And also node RecognitionComponent:
![Screenshot from 2022-02-23 16-26-11](https://user-images.githubusercontent.com/32383645/155283781-92fe4a2c-ccad-4cd1-82c3-f7602ddae6c8.png)

So I check the implementation and .dag files for SensorFusion and ReconitionComponent and notice they both are set to read some  
/perception/inner/* channels but none of them are seen in cyber_monitor or cyber_node info:
![Screenshot from 2022-02-23 16-28-15](https://user-images.githubusercontent.com/32383645/155284806-fa76a97c-07ff-4ff5-a8af-2047e6c60c74.png)
![Screenshot from 2022-02-23 16-28-24](https://user-images.githubusercontent.com/32383645/155284823-d9feae32-1b37-4be5-a30e-7ed8679bcf5e.png)

The SensorFusion and RecognitionComponent did function as expected since the car auto-pilots itself in the simulator, however, I wonder why these channels are hidden and how am I supposed to get details of them.

Thanks in advance!

**Comment by daohu527** [comment]
Yes, internal messages are inter-thread communication, There may be a switch that can be forwarded to the outside, I will confirm it and feedback then

**Comment by lovelydett** [comment]
> Yes, internal messages are inter-thread communication, There may be a switch that can be forwarded to the outside, I will confirm it and feedback then

Ok, thank you so much! 
BTW I am interested in the DNN tasks running in apollo and wanna know which components are submitting tasks involving DNN models, but in nvidia-smi I could only see "mainboard" processes rather than actual components since components are loaded by mainboard. Wonder which parts of the source codes to read about this topic or other tools you may recommend (like any CUDA kernel monitor tool?), thank you!

**Comment by daohu527** [comment]
but in nvidia-smi I could only see "mainboard" processes rather than actual components since components are loaded by mainboard. 

> Yes, can you find more information about this process, such as process ID, parameters, etc. Then we can find out which process do the job

**Comment by daohu527** [comment]
Because the inner message does not need serialization and deserialization, so it cannot be used directly.You can refer to this example to convert internal messages to external messages, 
https://github.com/ApolloAuto/apollo/blob/ce565859475c6614e9d3de4f9779642a44f2a7cc/modules/perception/onboard/component/fusion_camera_detection_component.cc#L819-L829

**Comment by lovelydett** [comment]
> Because the inner message does not need serialization and deserialization, so it cannot be used directly.You can refer to this example to convert internal messages to external messages,
> 
> https://github.com/ApolloAuto/apollo/blob/ce565859475c6614e9d3de4f9779642a44f2a7cc/modules/perception/onboard/component/fusion_camera_detection_component.cc#L819-L829

Got it Thank you so much!
