### ISSUE TITLE
你好，linux preempt-rt 内核安装nvidia驱动绕开了驱动的实时检查，使用的时候没有问题么，毕竟nvidia不支持实时内核

### ISSUE THREAD

**Issue by gaopan19** [ApolloAuto/apollo#14320]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
It depends on whether the nvidia runtime reports an error or not. This problem may be relatively difficult to identify, if you have questions, we can continue to follow up : )

**Comment by gaopan19** [comment]
你好，我们使用工具对rt-linux进行检测的时候遇到了一些问题，希望可以一起探讨下。具体如下：


问题：BUG: scheduling while atomic: irq/62-s-nvidia/2544/0x00000002


硬件环境：
显卡： nvidia geforce 1660
        主机： x10/x11 (x86结构)
软件环境：
1. kernel 4.4.245 + rt patch (CONFIG_PREEMPT_RT_FULL=y)
            Index of /pub/linux/kernel/projects/rt/4.4/older/patch-4.4.245-rt211.patch.gz
            https://mirror.tuna.tsinghua.edu.cn/kernel/v4.x/linux-4.4.245.tar.xz
2. nvidia-driver 440.82
            NVIDIA - 驱动下载
        3. 使用独立显卡，kernel编译依赖 /usr/src/nvidia-xxx


问题复现过程：
        添加内核测试配置kmemleak、kasan，安装新的内核，启动后dmesg发现如下bug


Call Trace：
BUG: scheduling while atomic: irq/62-s-nvidia/2544/0x00000002
Modules linked in: tcp_lp sunrpc dm_mirror dm_region_hash dm_log nls_iso8859_1 nvidia_drm(PO) snd_hda_codec_realtek snd_hda_codec_generic nvidia_modeset(PO) iTCO_wdt nvidia(PO) iTCO_vendor_support i915 snd_hda_codec_hdmi dell_wmi sparse_keymap ipmi_msghandler coretemp dcdbas dell_smm_hwmon kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd psmouse pcspkr snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_seq snd_seq_device snd_pcm input_leds snd_timer joydev snd soundcore i2c_i801 shpchp mei_me mei ioatdma 8250_fintek mac_hid sch_fq_codel ip_tables x_tables xfs libcrc32c hid_generic serio_raw nouveau mxm_wmi ttm uas video usbmouse usbkbd igb drm_kms_helper syscopyarea ptp sysfillrect pps_core
sysimgblt fb_sys_fops dca usbhid i2c_algo_bit usb_storage hid drm ahci pata_acpi libahci wmi fjes autofs4
Preemption disabled at:[<ffffffffc14f4cdf>] nv_post_event+0x3f/0x1a0 [nvidia]
CPU: 0 PID: 2544 Comm: irq/62-s-nvidia Tainted: P        W  O    4.4.245-rt211-kmemleak-kasan- #1
Hardware name: Dell Inc. Precision 7920 Tower/060K5C, BIOS 2.14.0 07/27/2021
ffff88085e21f9c0 1db3cb38f948d5eb ffff880832baf758 ffffffff8164a175
ffff8808329dc800 0000000080000002 ffff880832baf778 ffffffff81110bd2
ffff88085e21f9c0 000000000001f9c0 ffff880832baf7d8 ffffffff81d5367f
Call Trace:
[<ffffffff8164a175>] dump_stack+0x6f/0x9a
[<ffffffff81110bd2>] __schedule_bug+0x82/0xe0
[<ffffffff81d5367f>] __schedule+0x8ff/0x980
[<ffffffff81d58d3f>] ? _raw_spin_unlock+0x1f/0xa0
[<ffffffff81d53780>] schedule+0x80/0x150
[<ffffffff81d565fa>] rt_spin_lock_slowlock+0x23a/0x3f0
[<ffffffff81d563c0>] ? __rt_mutex_slowlock+0x290/0x290
[<ffffffff81d591c8>] __rt_spin_lock+0x38/0x40
[<ffffffff81d5938e>] rt_write_lock_irqsave+0xe/0x20
[<ffffffff8133b6d0>] create_object+0x290/0x500
[<ffffffff8133b440>] ? kmemleak_disable+0x70/0x70
[<ffffffff813232c1>] ? memset+0x31/0x40
[<ffffffff81d4b73e>] kmemleak_alloc+0x4e/0xb0
[<ffffffff8131e883>] kmem_cache_alloc_trace+0x103/0x270
[<ffffffffc14f4d0d>] nv_post_event+0x6d/0x1a0 [nvidia]
[<ffffffffc1c51617>] _nv030949rm+0x147/0x180 [nvidia]
[<ffffffffc18276b6>] ? _nv027760rm+0x86/0x110 [nvidia]
[<ffffffffc1a10c8d>] ? _nv011148rm+0xed/0x180 [nvidia]
[<ffffffffc1a10c6a>] ? _nv011148rm+0xca/0x180 [nvidia]
[<ffffffffc1b7f401>] ? _nv024567rm+0x251/0x3e0 [nvidia]
[<ffffffffc180cd51>] ? _nv024521rm+0x21/0xf0 [nvidia]
[<ffffffffc17f57db>] ? _nv014841rm+0x9b/0x240 [nvidia]
[<ffffffffc19fb278>] ? _nv027074rm+0x768/0x9f0 [nvidia]
[<ffffffffc19f9b6d>] ? _nv007421rm+0x17d/0x260 [nvidia]
[<ffffffffc19fa0ad>] ? _nv027081rm+0x8d/0x180 [nvidia]
[<ffffffffc1c5596e>] ? _nv000911rm+0x10e/0x180 [nvidia]
[<ffffffffc14f0f90>] ? nvidia_isr_common_bh+0x70/0x70 [nvidia]
[<ffffffffc1c59f5c>] ? rm_isr_bh+0x1c/0x60 [nvidia]
[<ffffffffc14f0f80>] ? nvidia_isr_common_bh+0x60/0x70 [nvidia]
[<ffffffffc14f0fa1>] ? nvidia_isr_kthread_bh+0x11/0x20 [nvidia]
[<ffffffff81169672>] ? irq_thread_fn+0x42/0xa0
[<ffffffff81169a3f>] ? irq_thread+0x23f/0x320
[<ffffffff81d5327d>] ? __schedule+0x4fd/0x980
[<ffffffff81169630>] ? irq_forced_thread_fn+0xd0/0xd0
[<ffffffff81169800>] ? wake_threads_waitq+0x30/0x30
[<ffffffff811179b2>] ? finish_task_switch+0xc2/0x350
[<ffffffff81d53271>] ? __schedule+0x4f1/0x980
[<ffffffff81d5327d>] ? __schedule+0x4fd/0x980
[<ffffffff81d532c0>] ? __schedule+0x540/0x980
[<ffffffff81169b20>] ? irq_thread+0x320/0x320
[<ffffffff81111ce8>] ? preempt_count_sub+0x18/0xe0
[<ffffffff81169800>] ? wake_threads_waitq+0x30/0x30
[<ffffffff81107d10>] ? kthread+0x190/0x1b0
[<ffffffff81107b80>] ? kthread_worker_fn+0x2d0/0x2d0
[<ffffffff8128b57f>] ? hracct_ret_from_fork+0x2f/0x40
[<ffffffff81107b80>] ? kthread_worker_fn+0x2d0/0x2d0
[<ffffffff81d5a145>] ? ret_from_fork+0x55/0x80
[<ffffffff81107b80>] ? kthread_worker_fn+0x2d0/0x2d0




参考网上分析过程：(备注：nvidia-driver官方配置说不支持full preempt rt)
        参考链接：https://forums.developer.nvidia.com/t/real-time-patch-set-linux-driver-bug/147865 

        The actual final callsite is likely nv_post_event:

        objdump -r ./kernel/nvidia/nv-kernel.o_binary | grep 704893

        0000000000704893 R_X86_64_PC32 nv_post_event-0x0000000000000004 # call to nv_post_event

        nv_post_event from the open source component of the driver is as follows:        


       

        On PREEMPT_RT_FULL, NV_SPIN_LOCK_IRQSAVE cannot block (as it is a raw_spin_lock), so it’s very likely the call to wake_up_interruptible is to blame.

        The core of wake_up_interruptible immediately contains a call to spin_lock_irq. On PREEMPT_RT_FULL kernels, spin locks are replaced

         with blocking priority inheriting mutexes. The last part of the stack trace shows blocking on just that:

        [ 5493.745534] rt_spin_lock_slowlock_locked+0x108/0x2d0

        [ 5493.745536] rt_spin_lock_slowlock+0x50/0x80

        [ 5493.745541] __wake_up_common_lock+0x61/0xb0

Are there any modifications that can be made to the open source layer to avoid the call to wake_up_interruptible? Can the call be deferred to a preemptable context with rcu? Can nvidia change binary component of the kernel driver to avoid calls to nv_post_event in non-preemptable contexts? 













At 2022-02-24 08:50:25, "zero" ***@***.***> wrote:

It depends on whether the nvidia runtime reports an error or not. This problem may be relatively difficult to identify, if you have questions, we can continue to follow up : )

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daohu527** [comment]
Thanks for share, looks like nvidia support is needed, we can keep track of this issue

**Comment by gaopan19** [comment]
好的，有进展了分享给我们，我们这边也继续跟进




--
发自我的网易邮箱手机智能版



在 2022-03-08 15:04:28，zero ***@***.***> 写道：


Thanks for share, looks like nvidia support is needed, we can keep track of this issue

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
