### ISSUE TITLE
Perception not Working with AuroAI bridge.

### ISSUE THREAD

**Issue by marcusvinicius178** [ApolloAuto/apollo#14338]
Hi I am using Apollo 5.0 with CARLA simulator 0.9.6, with AUROAI bridge: https://github.com/AuroAi/carla_apollo_bridge
 

System:
Docker
Ubuntu: 20;04
GPU: Tesla T4
RAM: 124 Gi

The ground truth obstacle sensor works. However, the Perception module is not working when activating Transform + Perception in **Module Controller** tab.

I have already read some git issues, which indicates that Apollo 5.0 on that time (2020) was not working with other GPUs architectures different from GTX2080: https://github.com/AuroAi/carla_apollo_bridge/issues/13

It seems there was a lot of working around this issue:

https://github.com/ApolloAuto/apollo/issues/6916

https://github.com/ApolloAuto/apollo/issues/12088

I would like to understand how to fix this issue and enable perception in apollo 5.0 with CARLA simulator. 
What must I do?

Thanks in advance

@daohu527 , @storypku

**Comment by daohu527** [comment]
It looks like a big project. I need to think about whether to recommend you to upgrade the version, or other methods : )

**Comment by marcusvinicius178** [comment]
Thanks for the reply mr @daohu527 can you please add this issue in your thoughts: https://github.com/AuroAi/carla_apollo_bridge/issues/19

Unfortunately AUROAI company is not working in this project anymore (they have officially informed me by e_mail). For this reason I get no more answers on their git. 

Do you have some idea to **activate** localization tab and get the sensors data instead using the ground truth as they did. I have no idea how to modify their codes to achieve that. I am grateful for some hint in this regard also, if possible. :)
