### ISSUE TITLE
If you don't have a GPU, what versions' Apollo can you run

### ISSUE THREAD

**Issue by mhzhou2021** [ApolloAuto/apollo#14337]

**Comment by mhzhou2021** [comment]
> You can use cpu mode and most of the modules will work fine except for perception
Thanks for your reply. There is no relevant tutorial or demo introduction？

**Comment by mhzhou2021** [comment]
> You can use cpu mode and most of the modules will work fine except for perception

Thanks for your reply. There is no relevant tutorial or demo introduction？

**Comment by daohu527** [comment]
You can refer to the following [documentation](https://github.com/ApolloAuto/apollo/tree/master/docs) first.

**Comment by mhzhou2021** [comment]
@daohu527 thanks!
