### ISSUE TITLE
Localisation msf arch64 build

### ISSUE THREAD

**Issue by andreimestereaga** [ApolloAuto/apollo#14333]
I did a fresh build using arch64 docker dev environment and I hitting this error:

Execution platform: @local_config_platform//:host
In file included from ./modules/localization/msf/msf_localization.h:42:0,
                 from modules/localization/msf/msf_localization.cc:17:
./modules/localization/msf/local_integ/localization_integ.h:24:10: fatal error: localization_msf/gnss_struct.h: No such file or directory
 #include "localization_msf/gnss_struct.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Checking on third party directory seems like it lacks the localization_msf includes and libs for  arch64 (only x86_64 dir is in place).
Any idea why this is not present for arch64 and how I should install it or is there any way to avoid this ?

**Comment by yulong88888** [comment]
I also had the same problem，i use jetson nx

**Comment by a-chong-chong** [comment]
I also had the same problem,have you solved it

**Comment by WildBeast114514** [comment]
locailization msf component currently only support x86_64

**Comment by WildBeast114514** [comment]
locailization msf component currently only support x86_64. If you don't need locailization msf component, remove msf dir in localization, and try to build again to avoid this
