### ISSUE TITLE
launching perception_camera.launch does not publish lane detections

### ISSUE THREAD

**Issue by josh-wende** [ApolloAuto/apollo#14339]
According to `docs/howto/how_to_run_perception_module_on_your_local_computer.md`, running `cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch` should run obstacle and lane detection. And indeed, both objects and lanes are drawn in the visualization debug image. However, the `FusionCameraDetectionComponent` alone does not publish to the `/perception/lanes` channel, and has no writer configured to do so.

What does the `FusionCameraDetectionComponent` do with lanes and why does it run the images through the lane detector NN if it does not output the final results? If I run `mainboard -d ./modules/perception/production/dag/dag_streaming_perception_lane.dag`, lanes are published, but if both are running then is the same image getting sent through the NN twice? If so, is there a way to remove this redundancy?

**Comment by liouyx** [comment]
You'd better use `cyber_launch start /apollo/modules/perception/production/launch/perception_camera.launch`, in perception_camera.launch, there are two dag files launched, [dag_streaming_obstacle_detection.dag](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/dag/dag_streaming_obstacle_detection.dag) and [dag_motion_service.dag](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/production/dag/dag_motion_service.dag).

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
