### ISSUE TITLE
apollo can not detect my GPU

### ISSUE THREAD

**Issue by Jorge2091** [ApolloAuto/apollo#14336]
im in linux Ubuntu made recently from windows
i downloaded apollo using the git clone inside the website and then using terminal commands seen in the lgsvl simulator instruction. i was not able to download using the git clone in terminal due to error, something about long package. i am trying to use the apollo 6.0.

For some reason when i enter the code 
`./docker/scripts/dev_start.sh`
it doesnt detect my GPU which i am using is a RTX 2080. it just continues with the cpu. in lgsvl the code the continues and uses the code after dev_into
`./apollo.sh build_opt_gpu`
but does work as the gpu is not detected. i take out the _gpu and it continues with the cpu but when i go to cyber monitor after the bridge creation, it doesnt send the camera as seen in the image belower
https://prnt.sc/9LMJruQTIids
i think this may be due to gpu not being used but i do have a driver install with the newest version a week ago. i tried again with a older version but the same thing even done `nvidia-smi` gives me the result as below
https://prnt.sc/ahlQsn2ZMopU
i am not sure why it can not detect my GPU or why it doesnt send cameras or lidars

**Comment by daohu527** [comment]
so we should focus on why the nvidia card is not found.
```
./docker/scripts/dev_start.sh
```
any error messages when run above command?

**Comment by WildBeast114514** [comment]
To use gpu in docker container, you must install nvidia-docker2.
