### ISSUE TITLE
Demo map not show up

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#1433]
Hello,

I am playing demo_1.5, (in dev docker) everything looks fine but the map is not showing up.
Do I need to do run something else than rosbag?
Thank you!

**Comment by Capri2014** [comment]
Did you choose the map from the right top bar of dreamview?

**Comment by xiaoxq** [comment]
This issue is closed as it becomes stale. Please file a new one if it's not figured out.
