### ISSUE TITLE
The relationship between pnc-junction boundary and stop-fence of stop sign

### ISSUE THREAD

**Issue by yuntianyi-chen** [ApolloAuto/apollo#14332]
Hi,

I noticed a bug fix in pull request [#8270](https://github.com/apolloauto/apollo/pull/8270), and I'm trying to reproduce this bug. What is the relationship between pnc-junction boundary and stop-fence of stop sign? What does pnc-junction boundary mean?

Thanks

**Comment by qwetqwe** [comment]
It is a junction polygon for PNC use，you can see PNC junction and stop sign line by dreamview
