### ISSUE TITLE
How to correctly play record files in loop? use_sim_time?

### ISSUE THREAD

**Issue by lovelydett** [ApolloAuto/apollo#14344]
Suppose I want to play a record file in **loop** with the all typical modules on.

Only sensor data (images, lidar, radar, Gps, Imu ...) are in the record.

As expected, everything works fine in the first loop but from the start of second loop some computational jobs get stuck (e.g., fusion) since the timestamps go back.

I assume there are some flags to turn off such check but how?

I noticed the **use_sim_time** flag in _global_flagfile.txt_ but I am not sure how to set it to true and is it for this purpose?
Thank you!

![Screenshot from 2022-03-09 17-37-15](https://user-images.githubusercontent.com/32383645/157414435-c6c8a374-a1e7-4f98-b186-7b9e63d3a144.png)

**Comment by daohu527** [comment]
`use_sim_time` is used to mock the system time.

In your case, we need to be accumulating sensor time, it looks like this is a new feature

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
