### ISSUE TITLE
apollo5.5  aarch64-docker images can't be downloaded,How can I get it

### ISSUE THREAD

**Issue by hello-big-world** [ApolloAuto/apollo#14349]
The apollo5.5  aarch64-docker  image of version 5.5 cannot be downloaded, but I use apollo5.5 aarch64 libtorch. How can I get the image

**Comment by daohu527** [comment]
how did you pull the apollo5.5 aarch64 docker?

**Comment by hello-big-world** [comment]
@daohu527  change ARCH in dev_start.sh to Arrch64,then run bash docker/scripts/dev_start.sh

**Comment by daohu527** [comment]
The dev docker not support arm for now, but cyber. you can try `bash docker/scripts/cyber_start.sh`

By the way I can success pull dev_arm docker, but I'm not sure if it works.
