### ISSUE TITLE
Dreamview can't open file xxxx.txt in text mode

### ISSUE THREAD

**Issue by MR-hyj** [ApolloAuto/apollo#14342]
Environments:

- Carla Server 0.9.13
- Carla Cient 0.9.13
- Carla Python API 0.9.13
- Carla_apollo_bridge
- Apollo 5

I'm trying build Apollo 5 with upgraded Carla modules. Since the default Carla version in Apollo 5 is Carla 0.9.6, I modified several `sh` files in `docker/scripts/` to use Carla 0.9.13.

> My expectation:  The Carla Server keeps sends clean RGB images to the carla-apollo (so called bridge) where the clean images will be noised. The carla-apollo keeps sends noised images to apollo AI who keeps generating control messages. The control messages still will be noised in carla-apollo and finally get to Carla Server. 

![d7041453acf0a3710c93a15c81c1fd4](https://user-images.githubusercontent.com/46344518/156991586-28fe93d7-0b64-4454-9018-e070f581b454.jpg)

But in apollo docker, I keep getting this error.

![7235871134c3240559506077b998a17](https://user-images.githubusercontent.com/46344518/156990794-85088cea-c75a-4816-9c43-1c23d1fd2ad1.png)

Besides, I'm not getting a camera view of the target vehicle in dreamview even if I clicked the `camera sensor` button

**Comment by lovelydett** [comment]
For me I would first check channels to see whether carla bridge is sending them into channels, if so at least bridge and carla server are working, problem may be caused by Apollo module launches

**Comment by MR-hyj** [comment]
> 

All the logger.debug in bridge are printed correctly except for the errors encountered in dreamview. The problem is dreamview is not so easy to track, I'm still searching the source of the error.
Did you ever encounter any problems with Apollo or dreamview?

**Comment by lovelydett** [comment]
> 

how ab cyber_monitor

**Comment by daohu527** [comment]
You can see that the error message in dreamview is fatal! It killed all the modules so how can you run well then.

You should check why this error occurs

**Comment by MR-hyj** [comment]
> 

Thanks for your reply. I've been working on tracking this error for days, still making little progress. But I'm keeping trying :(

**Comment by MR-hyj** [comment]
> You can see that the error message in dreamview is fatal! It killed all the modules so how can you run well then.
> 
> You should check why this error occurs

Thanks for your reply. I've been working on tracking this error for days, still making little progress. But I'm keeping trying :(

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
