### ISSUE TITLE
apollo 6.0 perception_lidar.launch doesn't work

### ISSUE THREAD

**Issue by jojaeyoun** [ApolloAuto/apollo#14345]
* Enviroment

> OS Platform and Distribution : Ubuntu 18.04 with GPU(GTX 980)
> Apollo installed from (source or binary) : Source
> Apollo version : 6.0

* Describe 

> I want to run Apollo perception_lidar.launch (path : /apollo/modules/perception/production/launch/perception_lidar.launch) with my robosense 16ch lidar in docker

> but, i can't execute the launch file,
> I try execute the perception_lidar.launch just following step

> 1. edit file /apollo/modules/perception/production/conf/perception/lidar/velodyne128_detection_conf.pb.txt
> enable_hdmap: true -> **false (change)**

> 2. enter command line 
> cyber_launch start modules/perception/production/launch/perception_lidar.launch

* Error message
[a@in-dev-docker:/apollo]$ cyber_launch start modules/perception/production/launch/perception_lidar.launch
[cyber_launch_23581] INFO Launch file [/apollo/modules/perception/production/launch/perception_lidar.launch]
[cyber_launch_23581] INFO ========================================================================================================================
[cyber_launch_23581] INFO Load module [perception_lidar] library: [perception_lidar] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag] exception_handler: []
[cyber_launch_23581] INFO Start process [perception_lidar] successfully. pid: 23588
[cyber_launch_23581] INFO ------------------------------------------------------------------------------------------------------------------------
[perception_lidar]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_lidar]  I0310 18:30:07.964733 23588 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag -p perception_lidar -s CYBER_DEFAULT 
[perception_lidar]  I0310 18:30:07.965099 23588 global_data.cc:153] []host ip: 192.168.10.15
[perception_lidar]  I0310 18:30:07.967234 23588 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception_lidar, has 1 dag conf
[perception_lidar]  I0310 18:30:07.967243 23588 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag
[cyber_launch_23581] ERROR Process [perception_lidar] has died [pid 23588, exit code -11, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag -p perception_lidar -s CYBER_DEFAULT].
[cyber_launch_23581] INFO All processes has died.
[cyber_launch_23581] INFO Cyber exit.
[cyber_launch_23581] INFO All processes have been stopped.

Can you please help?

**Comment by lovelydett** [comment]
try `mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag`

**Comment by jojaeyoun** [comment]
I succeeded in executing the perception lidar module by executing **static_transform.launch**.

The reason for the failure was that there was no proper tf.

If someone experiences a similar problem, it is recommended to configure an appropriate tf through static_trasnform launch.
