### ISSUE TITLE
C++  grammar

### ISSUE THREAD

**Issue by Aikengit** [ApolloAuto/apollo#14346]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/73151525/157655708-943ab18a-552e-4922-8bcc-5122a27c64c1.png)
[apollo](https://github.com/ApolloAuto/apollo)/[cyber](https://github.com/ApolloAuto/apollo/tree/master/cyber)/[node](https://github.com/ApolloAuto/apollo/tree/master/cyber/node)/node_channel_impl.h
Auto NodeChannelImpl::CreateWriter(const std::string& channel_name) -> std::shared_ptr<Writer<MessageT>> {  … The function use "->"between CreateWriter  and shared_ptr,how to explain this grammar,thank you！

**Comment by daohu527** [comment]
It's `Placeholder type specifiers`, you can ref [link](https://en.cppreference.com/w/cpp/language/auto)
