### ISSUE TITLE
RTK base station

### ISSUE THREAD

**Issue by josh-wende** [ApolloAuto/apollo#14343]
Hi,

I am looking to get RTK localization working with the same equipment laid out in [this doc](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Navigation/PwrPak7_Installation_Guide.md). I see from the documentation that Apollo's localization has been designed for and tested with NovAtel's PwrPak7 in the trunk of the car. However, to use RTK with the PwrPak7, there should be an external base station, right? How was this handled in testing, and how can I easily replicate the setup to use RTK localization?

Thanks

**Comment by daohu527** [comment]
You can buy services from `qianxun` or other service providers instead of building base stations yourself
