### ISSUE TITLE
[Planning] Angle calculation while an obstacle blocking ADV perception in certain range

### ISSUE THREAD

**Issue by tuanngokien** [ApolloAuto/apollo#14353]
### System information

- **OS Platform and Distribution:** Linux Ubuntu 18.04
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0

### Steps to reproduce the issue:

I want to ask about the formula in function`IsPerceptionBlocked`. 

https://github.com/ApolloAuto/apollo/blob/b9e9020f734cb0540301b4a015d12121a2e96ed5/modules/planning/tasks/deciders/lane_change_decider/lane_change_decider.cc#L368

I'm imaging that Apollo calculating the `left_most_angle` and `right_most_angle` as visualized in attached XY-plane figure. But when I see in the actual code, I still cannot figure out how `left_most_angle` is calculated like this.

```
const double beam_heading = common::math::NormalizeAngle(
          adv_heading - 0.5 * search_range + search_angle);
...

left_most_angle = beam_heading - search_angle;
```

And this infers `left_most_angle = adv_heading - 0.5 * search_range` which is a difference of 2 constant values, and consequently the result of `left_most_angle` is constant and does not depend on `search_angle`.  How this could be correct because `left_most_angle` and `right_most_angle` need to vary dynamically based on both sides of specific obstacle. 

***In my opinion,***  `left_most_angle = beam_heading;` is the correct one.

### Supporting materials
![124408122-20bcf300-dd78-11eb-8c52-16e653595fd9](https://user-images.githubusercontent.com/26508575/158204778-664a428e-4919-4cd1-b013-bf0d8cf9a08c.jpeg)
Image credit: @daohu527

**Comment by qwetqwe** [comment]
The problem has been solved in https://github.com/ApolloAuto/apollo/pull/14351. Is this change what you want？

**Comment by tuanngokien** [comment]
Yes it is, I will close this issue. Thank you @qwetqwe.
