### ISSUE TITLE
How to shutdown all (or specific) nodes?

### ISSUE THREAD

**Issue by lovelydett** [ApolloAuto/apollo#14352]
If I `cyber_launch start xxx.launch`, sometimes it couldn't be shutdown by Ctrl+C, and the session just remains dead with the nodes still running.
How could I shutdown them? Thanks.

**Comment by daohu527** [comment]
Usually we can use `cyber_launch stop` to stop the module in another window.

It might be some bug use `ctrl+c`, we can be specific to which modules, then fixed it.

**Comment by daohu527** [comment]
I have also encountered such a problem, this may need to be analyzed, I forgot whether it is planning or other modules

**Comment by lovelydett** [comment]
> 

For me, it seems any module could be in this headless status, with probability. So weird

**Comment by Corezcy** [comment]
> > 
> 
> For me, it seems any module could be in this headless status, with probability. So weird

here is my shell command to close these modules.
```shell
ps -ef | grep -E 'planning|routing|prediction|control' | grep -v 'grep' | awk '{print $2}' | xargs kill -9
```

**Comment by lovelydett** [comment]
> 

Cool!

**Comment by lovelydett** [comment]
> > > 
> > 
> > 
> > For me, it seems any module could be in this headless status, with probability. So weird
> 
> I have the same question, especially closing the planning module.
> 
> For me , here is shell command to close all these modules.
> 
> ```shell
> ps -ef | grep -E 'planning|routing|prediction|control' | grep -v 'grep' | awk '{print $2}' | xargs kill -9
> ```

Cool!
