### ISSUE TITLE
Question about playing back a manually created record file

### ISSUE THREAD

**Issue by corjstout** [ApolloAuto/apollo#14358]
I am having trouble using record.py (at cyber/python/cyber_py3) to create record files "from scratch" i.e. by manually constructing and adding messages. I am able to run the demo for it (cyber/python/cyber_py3/examples/record.py) and the demo successfully creates a simple record file and then reads from it. However, when I try to play it back using `cyber_recorder play -l -f /tmp/test_writer.record` the playback never starts. It just hangs at zero progress.

Is there a way to use the record.py utility to create record files that can be played back?

Thanks,
Corwin

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 20.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:
```
[cstout16@in-dev-docker:/apollo]$./apollo.sh config 
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: develop
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20211122_1608
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit
```

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
1. Run the example record.py file at cyber/python/cyber_py3/examples to produce a simple record file from scratch
2. Run `cyber_recorder play` on the record file produced in step 1. Notice that the record file does not play.

```
[cstout16@in-dev-docker:/apollo]$python3 cyber/python/cyber_py3/examples/record.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0317 14:17:24.056216 172914 py_record.cc:574] []init _cyber_record_wrapper
Begin to write record file: /tmp/test_writer.record
W0317 14:17:24.068033 172914 record_file_writer.cc:46] []File exist and overwrite, file: /tmp/test_writer.record
+++ Begin to writer +++
apollo.common.util.test.SimpleMessage
apollo.cyber.proto.Chatter
Begin to read record file: /tmp/test_writer.record
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++ Begin to read +++
================================================================================
read [1] messages
channel_name -> simplemsg_channel
msgtime -> 990
msgnum -> 2
msgtype -> apollo.common.util.test.SimpleMessage
message is -> b'\x12\x06AAAAAA'
***After parse(if needed),the message is ->
text: "AAAAAA"

================================================================================
read [2] messages
channel_name -> simplemsg_channel
msgtime -> 991
msgnum -> 2
msgtype -> apollo.common.util.test.SimpleMessage
message is -> b'\x12\x06AAAAAA'
***After parse(if needed),the message is ->
text: "AAAAAA"

================================================================================
read [3] messages
channel_name -> chatter_a
msgtime -> 992
msgnum -> 2
msgtype -> apollo.cyber.proto.Chatter
message is -> b'\x08\x9f\x8d\x06\x10d\x18\x01'
***After parse(if needed),the message is ->
timestamp: 99999
lidar_timestamp: 100
seq: 1

================================================================================
read [4] messages
channel_name -> chatter_a
msgtime -> 993
msgnum -> 2
msgtype -> apollo.cyber.proto.Chatter
message is -> b'\x08\x9f\x8d\x06\x10d\x18\x02'
***After parse(if needed),the message is ->
timestamp: 99999
lidar_timestamp: 100
seq: 2

[cstout16@in-dev-docker:/apollo]$cyber_recorder play -l -f /tmp/test_writer.record 
file: /tmp/test_writer.record, chunk_number: 1, begin_time: 990 (1969-12-31-16:00:00), end_time: 993 (1969-12-31-16:00:00), message_number: 4
earliest_begin_time: 990, latest_end_time: 993, total_msg_num: 4

Please wait 3 second(s) for loading...
Hit Ctrl+C to stop, Space to pause, or 's' to step.

[RUNNING] Record Time: 0.000    Progress: 0.000 / 0.000
play finished.
[cstout16@in-dev-docker:/apollo]$
```

### Supporting materials (screenshots, command lines, code/script snippets):
Somewhat related issue: https://github.com/ApolloAuto/apollo/issues/13178

![image](https://user-images.githubusercontent.com/21263575/158897991-9e683529-4043-4f34-9fd1-6de586ed7d47.png)

**Comment by ntutangyun** [comment]
the begin time and end time does not seem right...

You may check out my open source tool:

CyberRecordViewer ([website](https://ntutangyun.github.io/cyber-recorder-viewer/), [source code](https://github.com/ntutangyun/cyber-recorder-viewer)) for validating the record files.

and use the tool CyberRecordParser([source code](https://github.com/ntutangyun/CyberRecordParser)) to help create the record files manually.

**Comment by corjstout** [comment]
Thanks for the links to your work, ntutangyun. I don't immediately see a way to construct record files from scratch like I'm trying to do, it looks like your tool is more for taking existing records/messages and altering them. But I'll look more into it.

However, I would like to find a solution within stock Apollo if it exists. Or if it doesn't, I would prefer to make changes within the C++ or Python code rather than add Javascript into the mix.

**Comment by daohu527** [comment]
@corjstout  you can try `pip install cyber_record`. It can use to both read, parse and write a record file. below is the example you can ref to.

```python
def write_message():
  pb_map = map_pb2.Map()
  pb_map.header.version = 'hello'.encode()

  with Record(write_file_name, mode='w') as record:
    record.write('/apollo/map', pb_map, int(time.time() * 1e9))
```

https://github.com/daohu527/cyber_record#3-write-messages

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
