### ISSUE TITLE
reference_line_provider.cc:253  Reference line is NOT ready.

### ISSUE THREAD

**Issue by Gabriel-Lv258** [ApolloAuto/apollo#14354]
- **OS Platform and Distribution ( Linux Ubuntu 18.04)
- **Apollo version : 5.0
_________________________________________________________________________________________________________

Hi, I built the apollo without docker since i just want to study the public road planner. So, i manually input the routing, location, chassis information which get from /modules/planning/testdata/sunnyvale_loop_test/ folder and use the base_map.txt. Not pretty sure why i would get this error. Could you please kindly give me some comments for this ?  Thank you for the help.

________________________________________________________________________________________________________
**log file as shown below:**
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0315 19:55:13.287912  5283 environment.h:33]  Environment variable [CYBER_PATH] not set, fallback to 
W0315 19:55:13.287932  5283 scheduler_factory.cc:64]  No sched conf found, use default conf.
W0315 19:55:13.287942  5283 environment.h:33]  Environment variable [CYBER_PATH] not set, fallback to 
I0315 19:55:13.288081  5287 processor.cc:80]  processor_tid: 5287
I0315 19:55:13.288087  5286 processor.cc:80]  processor_tid: 5286
I0315 19:55:13.288084  5285 processor.cc:80]  processor_tid: 5285
I0315 19:55:13.288084  5288 processor.cc:80]  processor_tid: 5288
I0315 19:55:13.288100  5289 processor.cc:80]  processor_tid: 5289
I0315 19:55:13.288112  5290 processor.cc:80]  processor_tid: 5290
I0315 19:55:13.288129  5291 processor.cc:80]  processor_tid: 5291
I0315 19:55:13.288223  5295 processor.cc:80]  processor_tid: 5295
I0315 19:55:13.288236  5296 processor.cc:80]  processor_tid: 5296
I0315 19:55:13.288244  5293 processor.cc:80]  processor_tid: 5293
I0315 19:55:13.288239  5292 processor.cc:80]  processor_tid: 5292
I0315 19:55:13.288239  5297 processor.cc:80]  processor_tid: 5297
I0315 19:55:13.288266  5298 processor.cc:80]  processor_tid: 5298
I0315 19:55:13.288277  5294 processor.cc:80]  processor_tid: 5294
I0315 19:55:13.288285  5299 processor.cc:80]  processor_tid: 5299
I0315 19:55:13.288311  5283 init.cc:104]  Register exit handle succ.
I0315 19:55:13.288321  5300 processor.cc:80]  processor_tid: 5300
I0315 19:55:13.290560  5283 hdmap.cc:24]  Loading HDMap: /apollo/modules/map/data/demo/base_map.txt ...
W0315 19:55:13.295192  5283 hdmap_common.cc:631]  stop sign 2has no overlap with any junction.
I0315 19:55:13.295773  5283 hdmap_util.cc:77]  Load HDMap success: /apollo/modules/map/data/demo/base_map.txt
I0315 19:55:13.296051  5283 scheduler.cc:55]  create croutine: /internal/task0
W0315 19:55:13.296085  5283 environment.h:33]  Environment variable [cyber_trans_perf] not set, fallback to 
W0315 19:55:13.296093  5283 environment.h:33]  Environment variable [cyber_sched_perf] not set, fallback to 
I0315 19:55:13.296109  5283 scheduler.cc:55]  create croutine: /internal/task1
I0315 19:55:13.296125  5283 scheduler.cc:55]  create croutine: /internal/task2
I0315 19:55:13.296142  5283 scheduler.cc:55]  create croutine: /internal/task3
I0315 19:55:13.296154  5283 scheduler.cc:55]  create croutine: /internal/task4
I0315 19:55:13.296167  5283 scheduler.cc:55]  create croutine: /internal/task5
I0315 19:55:13.296180  5283 scheduler.cc:55]  create croutine: /internal/task6
I0315 19:55:13.296191  5283 scheduler.cc:55]  create croutine: /internal/task7
I0315 19:55:13.296202  5283 scheduler.cc:55]  create croutine: /internal/task8
I0315 19:55:13.296216  5283 scheduler.cc:55]  create croutine: /internal/task9
I0315 19:55:13.296227  5283 scheduler.cc:55]  create croutine: /internal/task10
I0315 19:55:13.296240  5283 scheduler.cc:55]  create croutine: /internal/task11
I0315 19:55:13.296253  5283 scheduler.cc:55]  create croutine: /internal/task12
I0315 19:55:13.296264  5283 scheduler.cc:55]  create croutine: /internal/task13
I0315 19:55:13.296277  5283 scheduler.cc:55]  create croutine: /internal/task14
I0315 19:55:13.296288  5283 scheduler.cc:55]  create croutine: /internal/task15
I0315 19:55:13.296998  5283 scenario.cc:61]  [DEBUG] init stage LANE_FOLLOW_DEFAULT_STAGE
I0315 19:55:13.297185  5283 on_lane_planning.cc:194]  [DEBUG] Get localization:header {
  timestamp_sec: 1498682801.33
  module_name: "localization"
  sequence_num: 168770
}
pose {
  position {
    x: 586387.203263
    y: 4140676.21271
    z: -29.1851183716
  }
  orientation {
    qx: -0.00551346339344
    qy: 0.0363995342758
    qz: -0.620280830689
    qw: -0.783515390216
  }
  linear_velocity {
    x: 0.00149997781434
    y: 0.000880812599767
    z: -0.00122802127571
  }
  linear_acceleration {
    x: -0.00582869976263
    y: 0.0100514010432
    z: 0.0235518746941
  }
  angular_velocity {
    x: 0.000998771709994
    y: 0.000154125122251
    z: 1.03917169376e-05
  }
  heading: 2.90890211889
  linear_acceleration_vrf {
    x: 0.00994229889291
    y: 0.00712407897059
    z: 0.0232399095739
  }
  angular_velocity_vrf {
    x: 0.000377985098552
    y: -0.000936068612645
    z: -4.80654498315e-05
  }
}
I0315 19:55:13.297263  5283 on_lane_planning.cc:198]  [DEBUG] Get chassis:engine_started: true
engine_rpm: 0
speed_mps: 0
odometer_m: 0
fuel_range_m: 0
throttle_percentage: 15.2391853
brake_percentage: 13.607996
steering_percentage: 5.65957451
steering_torque_nm: -0.3125
parking_brake: false
driving_mode: COMPLETE_MANUAL
error_code: NO_ERROR
gear_location: GEAR_NEUTRAL
header {
  timestamp_sec: 1498682801.33
  module_name: "chassis"
  sequence_num: 169202
}
signal {
  turn_signal: TURN_NONE
  horn: false
}
I0315 19:55:13.297299  5283 on_lane_planning.cc:201]  [DEBUG] Get routingheader {
  timestamp_sec: 1234.5
  module_name: "routing"
  sequence_num: 1
}
road {
  passage {
    segment {
      id: "1_-1"
      start_s: 0
      end_s: 153
    }
    can_exit: true
  }
}
measurement {
  distance: 153
}
routing_request {
  waypoint {
    id: "1_-1"
    s: 0
    pose {
      x: 586392.84003
      y: 4140673.01232
    }
  }
  waypoint {
    id: "1_-1"
    s: 153
    pose {
      x: 586367.70649
      y: 4140785.357946
    }
  }
}
I0315 19:55:13.297356  5283 ego_info.cc:46]  [DEBUG] param: brand: LINCOLN_MKZ
vehicle_id {
  other_unique_id: "mkz7"
}
front_edge_to_center: 3.89
back_edge_to_center: 1.043
left_edge_to_center: 1.055
right_edge_to_center: 1.055
length: 4.933
width: 2.11
height: 1.48
min_turn_radius: 5.05386147161
max_acceleration: 2
max_deceleration: -6
max_steer_angle: 8.20304748437
max_steer_angle_rate: 8.55211
min_steer_angle_rate: 0
steer_ratio: 16
wheel_base: 2.8448
wheel_rolling_radius: 0.335
max_abs_speed_when_stopped: 0.2
brake_deadzone: 15.5
throttle_deadzone: 18
W0315 19:55:13.297407  5283 reference_line_provider.cc:253]  Reference line is NOT ready.
E0315 19:55:13.297415  5283 reference_line_provider.cc:255]  Failed to use reference line latest history
E0315 19:55:13.297432  5283 on_lane_planning.cc:270]  PLANNING_ERROR: Failed to create reference line

**Comment by diaokaitian** [comment]
may be you can print out the segments information and find out why 
step by step inside the reference_line_provider

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
