### ISSUE TITLE
[planning] [sim-control] lane change interrupted.

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#14362]
![image](https://user-images.githubusercontent.com/16061105/159147725-5a87df9c-94b3-4fc9-a3d8-d823a0b7eb31.png)

**Describe the bug**
Apollo runs on a single-direction multi-lane road, trying to make a lane change maneuver to the second lane. 

An NPC vehicle is ahead of Apollo and gradually slows down to a complete stop. This happens to interrupt Apollo's lane change maneuver and makes Apollo stuck on top of the lane boundaries. 

**To Reproduce**
The NPC vehicle is driven manually :)
As shown in the video. 

**Expected behavior**
Maybe need to drive back to the original lane and try again instead of waiting on top of the lane boundaries. 

** attachments **
[map](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EVirDVg1bCVGk5WPDunfYW8BtLokPtIzyGm8C4sgyje_Ig?e=HWQjaC)
[recording](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EReJHx8I651DtaS5-ulW60EBDoRxWt36Z_sqhbQEShKgZw?e=dBSNrv)
[video](https://entuedu-my.sharepoint.com/:v:/g/personal/yun005_e_ntu_edu_sg/ERpXJ-0TNmdPlQecXUaXNRkB2El1LlpL7YafotiUgIeNxA?e=MfqMLb)

**Comment by diaokaitian** [comment]
i also find this problem,when there is a obstacle on the neighbour reference line，the ego car will stop by the side of the obstacle
![2022-04-08 14-25-43屏幕截图](https://user-images.githubusercontent.com/22146168/162377168-234e2dae-01f2-46eb-a30c-37dc48dbee91.png)

**Comment by Yuchen413** [comment]
> The NPC vehicle is driven manually :)

Could you please tell me how to drive NPC manually? Thanks

**Comment by ntutangyun** [comment]
@Yuchen413 you may add me on wechat: XX_101n374i1_XX for further discussions.

**Comment by yellinshadows** [comment]
> @Yuchen413 you may add me on wechat: XX_101n374i1_XX for further discussions.

Hi Tang Yun,

I'm quite interested in this reproduction, but I wasn't able to contact you via the WeChat ID you provided as it seems it might have changed. And the links of video above are no longer available.

Would it be possible for you to share an alternative way to get in touch, if you're open to a conversation? Thank you!
