### ISSUE TITLE
creating real-time thread may failed and not handled

### ISSUE THREAD

**Issue by aachenxiaosong** [ApolloAuto/apollo#14360]
**Describe the bug**
function SetSchedPolicy() in pin_thread.cc. 
If the input param "spolicy" is SCHED_FIFO or SCHED_RR while sched_priority is set to 0, calling pthread_setschedparam will failed and the policy would not be changed without any warning (keep SCHED_OTHER by default).

**To Reproduce**
1. modify cyber/conf/mainboard_default.conf to add a processor with process_policy=SCHED_FIFO and processor_prio=0
2. create tasks and bind them with the processor in a group
3. run the task
4. to check policy and priority with "top" command (like top -Hp $(pid of mainboard)), which does not take effect

**Expected behavior**
print error log and stop running the module, or at least output a warning msg like:
"
if (0 != pthread_setschedparam(thread->native_handle(), policy, &sp)) {
      AWARN << "thread " << tid << " set sched_policy: " << spolicy << " failed";
}
"

**Screenshots**
non

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser 
 - Version 18.04

**Smartphone (please complete the following information):**
 non

**Additional context**
non

**Comment by daohu527** [comment]
Yes, a check will be good, as to the `sched_setscheduler ` man page, you should not set sched_priority to 0 in SCHED_FIFO or SCHED_RR mode. 

> For each of the above policies, param->sched_priority specifies a
       scheduling priority for the thread.  This is a number in the
       range returned by calling [sched_get_priority_min(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_min.2.html) and
       [sched_get_priority_max(2)](https://man7.org/linux/man-pages/man2/sched_get_priority_max.2.html) with the specified policy.  On Linux,
       these system calls return, respectively, 1 and 99.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
