### ISSUE TITLE
vse simulation failed to connect to cyber bridge

### ISSUE THREAD

**Issue by yangjiale1995** [ApolloAuto/apollo#14364]
I create a vse scenario and run simulation(lgsvl2021.3), but cannot receive message in apollo(r6.0.0) docker container, 
then I added log in contrib folder and found that acceptor.async_accept(socket, boost::bind(&Server::end_accept, shared_from_this(), boost::asio::placeholders::error)) blocked。how should i do to solve it ?

**Comment by daohu527** [comment]
lgsvl has stopped maintenance at present, your problem is either a network problem, or the client and server are not connected.
