### ISSUE TITLE
What is a TL_QUADRATE_CLASS traffic light?

### ISSUE THREAD

**Issue by boyang9602** [ApolloAuto/apollo#14366]
Hi, 
I have a question about the `quadrate` traffic light. What kind of traffic light does it mean exactly? [As the code shows](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L337), it is detected by the deep learning model in the traffic light detection step. There is an enumerate type in code
```
enum class TLDetectionClass {
  TL_UNKNOWN_CLASS = -1,
  TL_VERTICAL_CLASS = 0,
  TL_QUADRATE_CLASS = 1,
  TL_HORIZONTAL_CLASS = 2
};
```
Since this step is just detecting the bounding boxes of the traffic light, I think these enumerated types means the layout of the traffic lights. 
So in my opinion, VERTICAL means 
![image](https://user-images.githubusercontent.com/30889920/154525150-c521e865-546d-477c-9e9e-3545249bf23c.png)
HORIZONTAL means
![image](https://user-images.githubusercontent.com/30889920/154525603-17746121-4866-4e8f-b802-7fbf98eae771.png)
And QUADRATE probably means a single light, like 
![image](https://user-images.githubusercontent.com/30889920/154525961-ef198725-be3f-4740-a57c-01ba89829b9e.png)

Is my understanding correct?

So is this a case you are going to handle?
![image](https://user-images.githubusercontent.com/30889920/154526244-8aec6409-f63a-4b63-a8e0-fbf38a73a3b3.png)
If so, what type of this one should be? 
In the detection (I'm using Apollo v5.5.0), its bounding boxes are detected and the scores for the `TLDetectionClass` are 
```
I0215 23:08:37.515722 22558 detection.cc:323] []result_data 0.437532  # UNKNOWN
I0215 23:08:37.515745 22558 detection.cc:323] []result_data 0.559215  # VERTICAL
I0215 23:08:37.515763 22558 detection.cc:323] []result_data 0.000870899  # QUADRATE
I0215 23:08:37.515781 22558 detection.cc:323] []result_data 0.00238272  # HORIZONTAL
```
Then it is sent to the selection part with other bounding boxes.

Thanks!

**Comment by daohu527** [comment]
Yes, you're righht. @boyang9602 QUADRATE means a single traffic light.

![image](https://user-images.githubusercontent.com/10419854/191300413-b246cd04-5ffd-44c1-ac92-f15366fd16db.png)

As far as I know, the traffic light countdown is currently unrecognized.

**Comment by boyang9602** [comment]
Thank you very much @daohu527 !
