### ISSUE TITLE
It failed to connect to cyber bridge（apollo6.0) when I use the  visual scenario editor in lgsvl.

### ISSUE THREAD

**Issue by hailonghu** [ApolloAuto/apollo#14372]
VSE(visual scenario editor) simulation failed to connect to cyber bridge.I have run bridge.sh in apollo docker container.However,when I use random traffic in lgsvl, I can receive emulation data with cyber bridge in apollo.

**Comment by daohu527** [comment]
You should describe your problem in detail, what's the difference between them?

**Comment by Muxindawang** [comment]
> You should describe your problem in detail, what's the difference between them?

I plan the path of the NPC vehicle through VSE and run the simulation, but my cyber_bridge cannot be connected, cyber_montior cannot monitor any sensor channels, but when I choose random traffic, everything is normal;
My goal is to collect data for some specific scenarios. Can this idea be done with VSE?

![Snipaste_2022-11-30_09-38-26](https://user-images.githubusercontent.com/48120360/204686444-19480342-5734-486b-b3ed-5d1c9f8ba007.jpg)

**Comment by daohu527** [comment]
I have not used this feature for now. I'm afraid we can only analyze what the problem is first.
