### ISSUE TITLE
zlib-1.2.11.tar.gz is not found on official

### ISSUE THREAD

**Issue by cjinhang** [ApolloAuto/apollo#14374]
when i build the apollo-v7.00 the   zlib-1.2.11.tar.gz is not found on official ,because the zlib-1.2.12 is updated

**Comment by cjinhang** [comment]
(06:44:35) WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
(06:44:35) ERROR: An error occurred during the fetch of repository 'zlib':
   Traceback (most recent call last):
	File "/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/zlib/temp12804174087090804178/zlib-1.2.11.tar.gz: GET returned 404 Not Found
(06:44:35) INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:131:6: in <toplevel>
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(06:44:35) INFO: Repository boringssl instantiated at:
  /apollo/WORKSPACE:64:10: in <toplevel>
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:130:21: in grpc_deps
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(06:44:35) INFO: Repository remote_java_tools_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:237:6: in <toplevel>
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
(06:44:35) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:210:11: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/zlib/temp12804174087090804178/zlib-1.2.11.tar.gz: GET returned 404 Not Found
(06:44:35) ERROR: Analysis of target '//modules/v2x/v2x_proxy/proto_adapter:proto_adapter' failed; build aborted: Analysis failed
(06:44:35) INFO: Elapsed time: 0.849s
(06:44:35) INFO: 0 processes.
(06:44:35) FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by senjary** [comment]
I have the same problem, then edit two files:
apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/io_bazel_rules_go/go/private/repositories.bzl 
line 95 - 101
`
        http_archive(
            name = "net_zlib",
            build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
            sha256 = "91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9",
            strip_prefix = "zlib-1.2.12",
            urls = ["https://zlib.net/zlib-1.2.12.tar.gz"],
        )
`

apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/rules_proto/proto/private/dependencies.bzl
line 31-38
`
    "zlib": {
        "sha256": "91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9",
        "build_file": "@com_google_protobuf//:third_party/zlib.BUILD",
        "strip_prefix": "zlib-1.2.12",
        "urls": [
            "https://zlib.net/zlib-1.2.12.tar.gz",
        ],
    },
`

then build again

**Comment by w23215** [comment]
It works. thanks!

**Comment by cjinhang** [comment]
nice！thankyou！！

**Comment by POPCharlyn** [comment]
Under the error reporting path prompted，change link https://zlib.net/zlib-1.2.11.tar.gz to https://zlib.net/fossils/zlib-1.2.11.tar.gz.

**Comment by anhtu96** [comment]
> 

Thanks a lot! It works!

**Comment by anhtu96** [comment]
> I have the same problem, then edit two files: apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/io_bazel_rules_go/go/private/repositories.bzl line 95 - 101 `http_archive( name = "net_zlib", build_file = "@com_google_protobuf//:third_party/zlib.BUILD", sha256 = "91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9", strip_prefix = "zlib-1.2.12", urls = ["https://zlib.net/zlib-1.2.12.tar.gz"], )`
> 
> apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/rules_proto/proto/private/dependencies.bzl line 31-38 `"zlib": { "sha256": "91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9", "build_file": "@com_google_protobuf//:third_party/zlib.BUILD", "strip_prefix": "zlib-1.2.12", "urls": [ "https://zlib.net/zlib-1.2.12.tar.gz", ], },`
> 
> then build again

Thanks a lot! Works like a charm.

**Comment by lx18233184051** [comment]
Thanks for solutions, editting .cache file is a temp method, I have commit this bug fix.

**Comment by IDovgopolik** [comment]
Hi to all! I'm using the apollo 6.0 and I have the same problem. Editing .cache file is not good solution for me and the fix by @lx18233184051 doesn't work for me. Are there any ideas how to fix it in apollo 6.0?

**Comment by fei4xu** [comment]
> Thanks for solutions, editting .cache file is a temp method, I have commit this bug fix. detail: #14387

please backport it to r7.0.0

**Comment by daohu527** [comment]
I think we should fix the previous version by the way

**Comment by felixf4xu** [comment]
> Thanks for solutions, editting .cache file is a temp method, I have commit this bug fix. detail: #14387

#14387 does not work anymore, the link is changed again.

**Comment by daohu527** [comment]
In apollo 6.0, We should move the configuration to the front

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "629380c90a77b964d896ed37163f5c3a34f6e6d897311f1df2a7016355c45eff",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://github.com/madler/zlib/archive/v1.2.11.tar.gz"],
)

**Comment by Sirius-1110** [comment]
> move the configuration to the front

apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/io_bazel_rules_go/go/private/repositories.bzl
apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/rules_proto/proto/private/dependencies.bzl
Does "move the configuration to the front" mean to add this code to the front of the two files above?

**Comment by Sirius-1110** [comment]
> Under the error reporting path prompted

I can't find 'zlib' related fields under the error reporting path prompted.
