### ISSUE TITLE
How Fusion_conmponet  gets target object data?

### ISSUE THREAD

**Issue by Amazingmum** [ApolloAuto/apollo#14371]
In the code ,no related reader functions are seen,and how does it get the target data

**Comment by liouyx** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/perception/onboard/component/fusion_component.cc#L54
```c++
bool FusionComponent::Proc(const std::shared_ptr<SensorFrameMessage>& message) {
  if (message->process_stage_ == ProcessStage::SENSOR_FUSION) {
    return true;
  }
```
When the fusion module is started, the proc function always waits for the message to come in. Fusion module gets data from SensorFrameMessage. SensorFrameMessage comes from all sensor perception result.

**Comment by Amazingmum** [comment]
> https://github.com/ApolloAuto/apollo/blob/master/modules/perception/onboard/component/fusion_component.cc#L54
> 
> ```c++
> bool FusionComponent::Proc(const std::shared_ptr<SensorFrameMessage>& message) {
>   if (message->process_stage_ == ProcessStage::SENSOR_FUSION) {
>     return true;
>   }
> ```
> 
> When the fusion module is started, the proc function always waits for the message to come in. Fusion module gets data from SensorFrameMessage. SensorFrameMessage comes from all sensor perception result.

Sorry ,I don't understand the Proc(const std::shared_ptr<SensorFrameMessage>& message) ,and Where is the "const std::shared_ptr<SensorFrameMessage>& message"  comes from? 
 I don't see reader function to  subscribe to that msg in the code.

**Comment by dreamholy** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/perception/onboard/component/fusion_component.h#34
FusionComponent is an inherited class of cyber::Component, it gets target data in the cyber framework.

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
