### ISSUE TITLE
Yolo Obstacle Detection Normalization

### ISSUE THREAD

**Issue by tabaddor** [ApolloAuto/apollo#14385]
Where can I find the normalization (mean, std values) applied prior to obstacle detection for Yolov3 [3d-r4-half](https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-r4-half)?

### System information

- **OS Platform and Distribution (Linux Ubuntu 20.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.0)***

**Comment by liouyx** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/utils/resize.h#L32
Normalization is here.

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
