### ISSUE TITLE
How to trigger the lack of overlap?

### ISSUE THREAD

**Issue by 1Jyfc** [ApolloAuto/apollo#14397]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
Hello Apollo team, I'm working on Apollo recent days, and I need some help.

I'm working on testing Planning module, and I try to trigger some stage special transitions. For example, in scenario `STOP_SIGN_UNPROTECTED`, normally the stage should transfer like this:

```
LANE_FOLLOW_DEFAULT_STAGE
-> STOP_SIGN_UNPROTECTED_PRE_STOP
-> STOP_SIGN_UNPROTECTED_STOP
-> STOP_SIGN_UNPROTECTED_CREEP
-> STOP_SIGN_UNPROTECTED_INTERSECTION_CRUISE
-> LANE_FOLLOW_DEFAULT_STAGE
```

Normally if an ego enters this scenario and finishes it, these steps are necessary. So I am trying to trigger transitions which start from any stage except `STOP_SIGN_UNPROTECTED_INTERSECTION_CRUISE` and target to `LANE_FOLLOW_DEFAULT_STAGE`. For example, in `scenarios/stop_sign/unprotected/stage_pre_stop.cc`:

```
  scenario_config_.CopyFrom(GetContext()->scenario_config);

  bool plan_ok = ExecuteTaskOnReferenceLine(planning_init_point, frame);
  if (!plan_ok) {
    AERROR << "StopSignUnprotectedStagePreStop planning error";
  }

  const auto& reference_line_info = frame->reference_line_info().front();

  std::string stop_sign_overlap_id = GetContext()->current_stop_sign_overlap_id;

  // get overlap along reference line
  if (!scenario::util::GetOverlapOnReferenceLine(reference_line_info,
                                                stop_sign_overlap_id,
                                                ReferenceLineInfo::STOP_SIGN)) {
    return FinishScenario();
  }
```

Due to the lack of overlap, `STOP_SIGN_UNPROTECTED_PRE_STOP` will return to `LANE_FOLLOW_DEFAULT_STAGE`. I tried so hard but cannot create a test case that can trigger this transition, so could you tell me how to trigger such lack of overlap? I am using LGSVL as the simulator, and PythonAPI to carry on simulations. Thanks a lot!

**Comment by daohu527** [comment]
if you just want a condition to trigger the exit to STOP SIGN UNPROTECTED, you should add a test code. it's strange to use `GetOverlapOnReferenceLine ` to achieve your purpose

**Comment by 1Jyfc** [comment]
Thanks for your reply!

Sorry that I did not describe clearly. Here I did not change the code logic. My purpose is to trigger the uncommon exit of all scenario not by `GetOverlapOnReferenceLine` but by creating a scene by LGSVL, but it did not work. Is there any way to trigger it directly by test code? I did not find the docs, hope for your help. Thanks!

**Comment by daohu527** [comment]
> trigger the uncommon exit of all scenario
how do you achieve that?  Do you means by create a special scenario which will cause apollo planning can't work? How do you know that the scene you created meets this requirement?

I don't quite understand your method!

**Comment by 1Jyfc** [comment]
After reading codes of Planning, I think it may be efficient to trigger the exit by affecting overlap. In `STOP_SIGN_UNPROTECTED` normally it will run stage by stage, until `STOP_SIGN_UNPROTECTED_INTERSECTION_CRUISE` and then exit the scenario. But in the code it seems that when something is wrong with overlap (that is, `GetOverlapOnReferenceLine` gets nothing), the scenario `STOP_SIGN_UNPROTECTED`  will stop immediately. My goal is to create such cases, so I tried to figure out when the overlap will disappear or be detected incorrectly, but failed. If my understanding is wrong or there are some easier ways to achieve this, please point out. Thanks!

**Comment by qwetqwe** [comment]
Sorry we can‘t give you more advice to trigger this condition， maybe you need to change other code （for example scenario_manager.cc）to make overlap lack
