### ISSUE TITLE
[planning] planner failed to make a driving plan before entering the ramp

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#14390]
**Describe the bug**
Apollo planning encounters the "planner failed to make a driving plan" error before entering the ramp on a highway scenario. 

**To Reproduce**
Please replay the recording attached below.

**Expected behavior**
Very few times Apollo is able to enter the ramp without any issue. but most of the time it just pops up the planner error as shown in the screenshot below:

![highway_3d_planning_error-2022-04-01_16 29 37 mp4](https://user-images.githubusercontent.com/16061105/161226891-fd9a881b-2cea-458c-9e48-0768c2c50058.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 1804
 - Browser chrome

Attachments: 
* [3D highway map file](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/EX-ngVaAVshHoaBvTXtk0vEBAyTPZp6b0vU3SvzMUDBPvg?e=SZk9jy) 
* [video recording](https://entuedu-my.sharepoint.com/:v:/g/personal/yun005_e_ntu_edu_sg/Ec3YOu2zslhDneXYqAmJJZwBk_h1sTZgFlNKbBJq1o4pRQ?e=h7646j)
* [cyber record file](https://entuedu-my.sharepoint.com/:u:/g/personal/yun005_e_ntu_edu_sg/ESzBrsY-wRNLnVgi64echa8BNBA97QuRq7lVVUKifz3r2w?e=1th2rG)

**Comment by ntutangyun** [comment]
Note that I've modified some of the dreamview code including backend and frontend so that the visualization could display in 3D instead of 2D by default. But I don't think that will affect the normal function of the planning module :)

**Comment by qwetqwe** [comment]
In fact, apollo planning does not support referenceline intersection，even in 2d world. You can open PNC Monitor to see whether reference intersection， which will cause sl-projection fault
