### ISSUE TITLE
Ubuntu 20.04 LTS build.sh error: looking for nonexistent cyber_bridge file inside cyber_bridge folder 

### ISSUE THREAD

**Issue by rZapp11** [ApolloAuto/apollo#14396]
* I successfully built apollo 5.5 on ubuntu. I am able to run dreamview and the dreamview demo. However, I wanted to see if I could run apollo with LGSVL, but when I type `bootstrap.sh` I get the error `apollo/modules/contrib/cyber_bridge/cyber_bridge` does not exist. When I look at the cyber_bridge folder on github, it mentions this issue, but it does not seem to provide a clear solution. What is strange to me is that my computer never complained when I ran `bridge.sh` on WSL2, but now that I am using apollo on my Linux PC, it is having this issue. I am not the greatest with computers, so this might just be an easy fix that I am missing, but I would greatly appreciate any help.

### System information

- **OS Platform and Distro: Linux on Ubuntu 20.04 LTS:
- **Apollo installed from (source or binary): Source
- **Apollo version: 5.5
### Steps to reproduce the issue:
- Successfully install apollo by following the software installation guide
- Start dreamview by typing `bootstrap.sh` in terminal
- go into scripts folder by typing `cd scripts` from the apollo root folder
- type `bootstrap.sh`

### Supporting materials (screenshots, command lines, code/script snippets):'
I did not think code snippets were necessary as I followed everything in the software installation guide to the T.

**Comment by daohu527** [comment]
It is recommended that you use the latest version, we prefer to maintain new versions.
