### ISSUE TITLE
What caffe do you use ?

### ISSUE THREAD

**Issue by JohnGithub917** [ApolloAuto/apollo#14405]
Hello, what caffe does apollo model use ?
Thanks.

**Comment by POPCharlyn** [comment]
caffe？

**Comment by JohnGithub917** [comment]
> 

yes, this model uses caffe, right ?

**Comment by daohu527** [comment]
The model has been converted to a format supported by tensorrt. Since caffe has been merged into pytorch, caffe will not be supported separately in the future.
