### ISSUE TITLE
Apollo exports from mathworks roarunner don't include the objects of my scene

### ISSUE THREAD

**Issue by siomari** [ApolloAuto/apollo#14400]
Hello,

I'm using Mathworks Roadrunner 2021b to create a scene and export it to Apollo. When I export the scene the information regarding the objects is not in the exported XML file. Is there a way that I can resolve this issue? 

My scene 
![drivepark](https://user-images.githubusercontent.com/24621551/161923228-67beab2d-3f39-4c2b-a485-375bc77540b0.png)

The exported xml(in txt so I can upload it):
[drivepark.txt](https://github.com/ApolloAuto/apollo/files/8424733/drivepark.txt)

**Comment by daohu527** [comment]
You can also export a file in `bin` format, which is recommended

**Comment by siomari** [comment]
@daohu527 Thank you for your answer!

 I need it in the xml format in order to convert it to another xml format so I want a human readable file. Is there a way to have that information in the exported xml?

**Comment by daohu527** [comment]
If you export the bin, for example, basemap.bin, there will be also an basemap.text, which is readable.

Although I don't know if this can meet your requirements, If you want to export xml format, what object can't be exported?
