### ISSUE TITLE
How fast can monocular 3D detection code SMOKE reach in apollo?

### ISSUE THREAD

**Issue by FangJingYunner** [ApolloAuto/apollo#14409]
Apollo is a very great work，but l still have some question.
l have run monocular 3D detection code SMOKE on 2080Ti GPU but only got 10fps.
So l wonder can SMOKE in libtorch reach real-time(20fps)?
Thank you so much for reply!

**Comment by daohu527** [comment]
We haven't tested it directly, it depends on torch's optimization speed.
