### ISSUE TITLE
Obstacle::BuildLaneGraphFromLeftToRight()  What does this function mean? 

### ISSUE THREAD

**Issue by hello-big-world** [ApolloAuto/apollo#14401]
Why this function  ObstacleClusters::GetLaneGraphWithoutMemorizing use the lane_s of the  feature->lane().lane_feature()? 
for (const std::string& lane_id : lane_ids_ordered) {
    // Construct the local lane_graph based on the current lane_segment.
    bool vehicle_is_on_lane = (lane_id == center_lane_info->lane().id().id());
    std::shared_ptr<const LaneInfo> curr_lane_info =
        PredictionMap::LaneById(lane_id);
    LaneGraph local_lane_graph =
        ObstacleClusters::GetLaneGraphWithoutMemorizing(
            **feature->lane().lane_feature().lane_s()**, road_graph_search_distance,
            true, curr_lane_info);

**Comment by hello-big-world** [comment]
@ApolloDeveloper

**Comment by liouyx** [comment]
![pic1](https://user-images.githubusercontent.com/68633892/185578632-5fb302a4-c878-49d4-8854-f345c7c7bab0.png)
The lane sequence is the path composed of the current lane and the subsequent lanes. 
BuildLaneGraphFromLeftToRight() means building lane sequences from left to right.
