### ISSUE TITLE
Did someone add the car model successfully? When I add a new car model, it is always incomplete, like the picture:

### ISSUE THREAD

**Issue by POPCharlyn** [ApolloAuto/apollo#14407]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:  Linux Ubuntu 20.04
- **Apollo installed from (source or binary)**:
 **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by POPCharlyn** [comment]
![xRxQ-CyhHXM_80BqA_424_255](https://user-images.githubusercontent.com/82887976/162662493-2c19183e-b5ab-4c22-828a-d41b4eb160cb.png)

**Comment by daohu527** [comment]
This might be a problem with the model itself. You also need the `mtl` file.
