### ISSUE TITLE
apollo dreamview frontend：yarn install 报错

### ISSUE THREAD

**Issue by Niceyaa** [ApolloAuto/apollo#14408]
node版本：12.18.1 (14.15.1也是报错)
安装报错具体如下：
[6/19] ⠄ sharp
[11/19] ⡀ cwebp-bin
[9/19] ⡀ optipng-bin
[8/19] ⡀ mozjpeg
warning Error running install script for optional dependency: "/home/nvidia/newApollo/apollo/modules/dreamview/frontend/node_modules/optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /home/nvidia/newApollo/apollo/modules/dreamview/frontend/node_modules/optipng-bin
Output:
⚠ connect ECONNREFUSED 0.0.0.0:443
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c make install
pngrtran.c:99:1: warning: ‘png_rtran_ok’ defined but not used [-Wunused-function]
 png_rtran_ok(png_structrp png_ptr, int need_IHDR)
 ^~~~~~~~~~~~
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
pngxmem.c: In function ‘pngx_malloc_rows_extended’:
pngxmem.c:38:34: warning: comparison is always false due to limited range of data type [-Wtype-limits]
        (pngx_alloc_size_t)height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
                                  ^
ar: `u' modifier ignored since `D' is the default (see `U')
../libpng/libpng.a(pngrutil.o): In function `png_read_filter_row':
pngrutil.c:(.text+0x20c4): undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
make[1]: *** [optipng] Error 1
make: *** [install] Error 2

**Comment by wdhxs** [comment]
It's been solved

**Comment by Nocpprr** [comment]
How did you solve the problem? I have the same troubles

**Comment by Nocpprr** [comment]
> It's been solved

@wdhxs
