### ISSUE TITLE
How do you make SMOKE trained on the waymo dataset work in a real environment?

### ISSUE THREAD

**Issue by yukkysaito** [ApolloAuto/apollo#14410]
@xiaoMrzhang 
Thanks for the very nice software.

In Apollo 7.0, SMOKE is described as trained using waymo's open dataset.
However, since SMOKE calculates depth, it even learns the intrinsic parameters of the camera, which makes it seem unusable with other cameras.
How do you make SMOKE trained on the waymo dataset work in a real environment?
https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/README.md

### System information

- **Apollo version (7.0)**:

**Comment by liouyx** [comment]
During training, we resize images of waymo dataset to keep consistent with our own camera, and use the intrinsic parameters of our own camera when deploying SMOKE model.
Monocular camera detection is inaccurate, we mainly use lidar detection in real environment.

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
