### ISSUE TITLE
why use multithreading in pad_terminal.cc

### ISSUE THREAD

**Issue by diaokaitian** [ApolloAuto/apollo#14411]
![微信截图_20220412114228](https://user-images.githubusercontent.com/22146168/162876016-a00905e6-8780-409d-8782-11074d025616.png)

**Comment by daohu527** [comment]
could you please describe your question more clearly, this is useful to solve the problem

**Comment by daohu527** [comment]
@diaokaitian I finally understand your idea. Single thread is also feasible in this scenario, but if you need interaction and background playback, then multi-threading is better. A classic example is a music player.
