### ISSUE TITLE
Build Failed-An error occurred during the fetch of repository 'zlib'

### ISSUE THREAD

**Issue by iJeju** [ApolloAuto/apollo#14412]
### System information
- **Linux Ubuntu 18.04**:
- **Apollo installed from source or binary**:
- **Apollo version 6.0**:
- **Output of `FAILED: Build did NOT complete successfully‘ config` if on `./ apollo.sh build**:

### Steps to reproduce the issue:
(10:00:55) WARNING: Download from https://github.com/madler/zlib/archive/v1.2.11.tar.gz failed: class java.io.IOException connect timed out
(10:00:55) ERROR: An error occurred during the fetch of repository 'zlib':
   Traceback (most recent call last):
	File "/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/madler/zlib/archive/v1.2.11.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/zlib/temp7086323404372143817/v1.2.11.tar.gz: connect timed out
(10:00:55) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:210:11: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://github.com/madler/zlib/archive/v1.2.11.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/zlib/temp7086323404372143817/v1.2.11.tar.gz: connect timed out
(10:00:55) ERROR: Analysis of target '//modules/dreamview/backend/hmi:hmi' failed; build aborted: Analysis failed
(10:00:55) INFO: Elapsed time: 57.603s
(10:00:55) INFO: 0 processes.
(10:00:55) FAILED: Build did NOT complete successfully (686 packages loaded, 16826 targets configured)
``

I have downloaded the tar. document and change the workspace,  but still have the problem and cython also have the same problem.

**Comment by iJeju** [comment]
Question done！

**Comment by Gricha1** [comment]
could you please provide the answer?????

**Comment by Gricha1** [comment]
here is solution for me:
