### ISSUE TITLE
Double Check on Requirement to Install Apollo Version 6

### ISSUE THREAD

**Issue by JANE0015** [ApolloAuto/apollo#14414]
I have encountered some issues which caused BUILD to not complete successfully. Therefore, I would like to check if the pre-requisite is still valid, and if my system is compatible with Apollo V6?
I am having:

Graphics card: NUVO-8108GC-RTX2070S-i9-9900K
Memory: SSD 512GB
RAM: DDR4-32GB-ECC

Kindly advise.
Thank you!

**Comment by diaokaitian** [comment]
just have a look at your posted information, there is no problem about your system. 
i think you should paste out the detail error information,then other one can help you.

**Comment by JANE0015** [comment]
Alright thank you. I have made anither post on the issue
