### ISSUE TITLE
How to auto restart modules when encountering problems such as crashes

### ISSUE THREAD

**Issue by xixioba** [ApolloAuto/apollo#14420]
I use the following command to run
`cyber_launch start *.launch`
**But when a mainboard crashes, how does it automatically recover?**
In addition, 
is it possible for me to **run different modules in the same process**, currently I use a lot of mainboard processes

**Comment by daohu527** [comment]
it's not recommended to restart module when crash. If you want to run all the modules in one process, you should add them in one dag, and then they will run in the same process, but it's not recommended too.

**Comment by xixioba** [comment]
I found the relevant configuration in the source code, and it can take effect, only as an answer to this question
Only need to configure launch like this
```
<cyber>
    <module>
        <name>any</name>
        <dag_conf>***.dag</dag_conf>
        <process_name>any</process_name>
        <exception_handler>respawn</exception_handler> # or [exit], which will exit all process
    </module> 
<cyber>
```
