### ISSUE TITLE
Prediction module bug : no obstacle trajectory prediction

### ISSUE THREAD

**Issue by fedlucchetti** [ApolloAuto/apollo#14427]
Dear all,

I was running Apollo toether with LGSVL for a while now without any issues. Today, when launching the prediction module, i noticed that apollo is not able to predict the trajectory of other obstacle anymore. When I am launching the prediction module with the CMD I get the following errors:

1. Upon initialization,"Ego vehicle not inserted", although i selected th correct one in the dreamview interface
2. While processing, "older timeframe does not math the currect one". No idea why this happens

I build a fresh apollo with `./apollo.sh build_opt_gpu` which did not solved the issue. Here is the raw output

Thank you

`[cyber_launch_57041] INFO Launch file [/apollo/modules/prediction/launch/prediction.launch]`
`[cyber_launch_57041] INFO `
`[cyber_launch_57041] INFO Load module [prediction] library: [prediction] [CYBER_DEFAULT] conf:` `[/apollo/modules/prediction/dag/prediction.dag] exception_handler: []`
`[cyber_launch_57041] INFO Start process [prediction] successfully. pid: 57048`
`[cyber_launch_57041] INFO ------------------------------------------------------------------------------------------------------------------------`
`[prediction]  WARNING: Logging before InitGoogleLogging() is written to STDERR`
`[prediction]  I0425 16:01:27.700965 57048 module_argument.cc:81] []command: mainboard -d /apollo/modules/prediction/dag/prediction.dag -p prediction -s CYBER_DEFAULT` 
`[prediction]  I0425 16:01:27.701236 57048 global_data.cc:153] []host ip: 10.186.24.22`
`[prediction]  I0425 16:01:27.701787 57048 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is prediction, has 1 dag conf`
`[prediction]  I0425 16:01:27.701793 57048 module_argument.cc:60] []dag_conf: /apollo/modules/prediction/dag/prediction.dag`
`[prediction]  E0425 16:01:34.225422 57060 obstacles_prioritizer.cc:109] [prediction]Ego obstacle nullptr found`
`[prediction]  E0425 16:01:34.225468 57060 obstacles_container.cc:305] [prediction]Ego vehicle not inserted`
`[prediction]  E0425 16:01:34.225472 57060 obstacles_prioritizer.cc:185] [prediction]Ego vehicle not found`
`[prediction]  E0425 16:01:34.225476 57060 interaction_filter.cc:104] [prediction]Ego vehicle not found`
`[prediction]  E0425 16:01:34.279670 57064 obstacles_container.cc:92] [prediction]Invalid timestamp curr [1.6509e+09] v.s. prev [1.6509e+09].`                                                                                                                                  
`[prediction]  E0425 16:01:34.373211 57057 obstacle.cc:150] [prediction]Obstacle [-1] received an older frame [1650895287.0424380302] than the most recent timestamp [ 1650895294.324968338].`

**Comment by liouyx** [comment]
You can run cyber_monitor to see if the /apollo/perception/obstacles and /apollo/localization/pose are correct, and check whether the hd-map is loaded correctly.

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
