### ISSUE TITLE
Segmentation fault(core dump) & huge data/core generated 

### ISSUE THREAD

**Issue by klaus99815** [ApolloAuto/apollo#14429]
Use Apollo 5 0 and lgsvl are jointly simulated. After LG end repeatedly connects Apollo, the Apollo end will produce segmentation error. Due to the huge data / core generated, there is insufficient memory and Apollo segmentation error. The generated data / core file will reach more than 40 g, because the memory of home is about more than 40 G. What is the reason? Is there a way not to generate core files. In the end, it is because the huge core file is generated that leads to the segmentation error, the bridge end is broken, or the bridge is broken that leads to the segmentation error..

Ubantu 18.04
Apollo 5.0
LGSVL 2021.1

**Comment by daohu527** [comment]
Below command sets the core dump file size to unlimited to ensure that the core dump file is complete. The core dump contains the full image of the application's address space, including code, stack and heap (malloc'd objects etc.) so the size will be large.
https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/scripts/bootstrap.sh#L24-L26

## disable coredump
you can use below cmd to disable coredump
```
ulimit -c 0
```
