### ISSUE TITLE
Traffic light module is inconsistent that causes planner failed to make decision on intersection 

### ISSUE THREAD

**Issue by tuanngokien** [ApolloAuto/apollo#14432]
### System information

- **OS Platform and Distribution:** Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0 (master branch - commit #13620)

**Describe the bug**
When EV stopped at an intersection and was waiting for traffic light, the decision fence was blinking then completely disappeared (19s in video), seems like the planner no longer works anymore.  

*Note: simulated on Apollo & LGSVL. Traffic light perception results were ground-truth data provided by LGSVL.

**To Reproduce**
The video and CyberRT recording were given on the attachments for reproduction.

**Expected behavior**
EV planner received traffic light information and processed green/red status to move the car through the intersection.

**Demo Video**

https://user-images.githubusercontent.com/26508575/165276049-25e3ab35-d2b7-4b43-b35d-02bcec55664b.mp4

**Attachments**
[Video recording](https://drive.google.com/file/d/19I2FvkfUzv5os-37so3PIlpRin89z-8o/view?usp=sharing)
[CyberRT recording](https://drive.google.com/file/d/1k49llrXVgYfqFH0J2GXvRCDrCecR6Aos/view?usp=sharing)

**Comment by daohu527** [comment]
According to the video, no more effective information can be obtained, unless it can be effectively analyzed, we will not deal with such problems for the time
