### ISSUE TITLE
dreamview: Change the shape of polygon to rectangle

### ISSUE THREAD

**Issue by POPCharlyn** [ApolloAuto/apollo#14433]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**: 
-  **Like the following figure: when the recorder is played, the detected results are displayed as polygons, but I want to replace them with rectangles. I don't know where to start. Does anyone know?**

### Supporting materials (screenshots, command lines, code/script snippets):
![20220427-150347](https://user-images.githubusercontent.com/82887976/165460569-97fc6c64-5c5f-4c25-9847-abc95231f692.png)

**Comment by diaokaitian** [comment]
you can chage the message in the recorded pb.txt file 
the raw  perception_obstacle layout is just iike the fellow  style, you can change it to what you want
```txt
perception_obstacle {
    id: 3843
    position {
      x: 587231.51479980431
      y: 4141538.4187665051
      z: -31.788609421753417
    }
    theta: 1.8273884765711224
    velocity {
      x: -20
      y: 8
      z: 0
    }
    length: 3.323319673538208
    width: 0.27527374029159546
    height: 0.89608645439147949
    polygon_point {
      x: 587231.51479980431
      y: 4141540.4187665051
      z: -31.788609421753417
    }
    polygon_point {
      x: 587231.51479980431
      y: 4141538.4187665051
      z: -31.788609421753417
    }
    polygon_point {
      x: 587227.87920228334
      y: 4141540.4187665051
      z: -31.788609421753417
    }
    tracking_time: 11.806291103363037
    type: VEHICLE
    timestamp: 1518648377.2048476
  }
```

**Comment by POPCharlyn** [comment]
![image](https://user-images.githubusercontent.com/82887976/185046332-5b5bad53-a525-4fe9-8597-b2e5e32295b2.png)
Thank you very much for your answer, but I don't think that's a long-term plan. I tried to modify the graphics and succeeded. Thank you anyway.
