### ISSUE TITLE
about hesai timestamp parser

### ISSUE THREAD

**Issue by whuzs** [ApolloAuto/apollo#14435]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/38743240/165670589-2ad572f0-af65-48ca-986a-168fbd5bdbd7.png)
should keep 'timestamp' stay same? or '-=' ?
这里不应该'-='吧,是否存在问题

**Comment by liouyx** [comment]
您好，-=是没有问题的。
Driver中的用是机械式的lidar。Lidar扫描一圈之后有多个block，把所有block数据打包，然后打上一个时间戳，即最新时间。
所以拿到的时间是最新的时间，需要知道点在哪个block、点由40线中的哪个线的激光头发射得到，从而得到时间差。通过最新时间减去时间差，就得到了当前点的时间戳。

**Comment by whuzs** [comment]
> 
用最新时间减去时间差这个是没问题的,但是这里使用的是"-=",每次操作后就不是最新时间了,不应该保持最新时间不变吗,然后再减去时间差

**Comment by liouyx** [comment]
我们咨询了lidar公司的人，这个-=是没有问题的。
某通道的时间戳等于点云包的绝对时间戳减去block offset，再减去通道offset。激光器按次序发光，所有block的激光发完之后，再把数据汇总打包，初始时间是打包时间。

**Comment by liouyx** [comment]
如果是120ms，你们的hesai激光雷达帧率是多少？

**Comment by whuzs** [comment]
我们用的是hesai40p激光雷达,10hz

**Comment by liouyx** [comment]
你们用的hesai40p、10hz，但是用"-="计算得到的一帧数据的时间差是120ms，修改了这块代码之后得到时间差是100ms？

**Comment by whuzs** [comment]
是的,我们当时是这样做的,但不是完全确定是不是由这一块的原因导致的

**Comment by liouyx** [comment]
那我建议你们和hesai人员沟通下，驱动的代码是hesai提供的。

**Comment by whuzs** [comment]
好的,谢谢

**Comment by liouyx** [comment]
好的，如果您有其他问题就随时开一个issue。

**Comment by whuzs** [comment]
好的,非常感谢你的回答

**Comment by Gatsby23** [comment]
> We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
> * **Apollo installed from (source or binary)**:
> * **Apollo version (3.5, 5.0, 5.5, 6.0)**:
> * **Output of `apollo.sh config` if on `master` branch**:
> 
> ### Steps to reproduce the issue:
> * **Please use bullet points and include as much details as possible**:
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):
> ![image](https://user-images.githubusercontent.com/38743240/165670589-2ad572f0-af65-48ca-986a-168fbd5bdbd7.png) should keep 'timestamp' stay same? or '-=' ? 这里不应该'-='吧,是否存在问题

您好，不好意思，有些小事需要麻烦你哈。我现在也需要对我的小车更换禾赛的激光雷达，是直接把硬件换上就可以了吗？还是哪里需要做一些额外的操作？

**Comment by whuzs** [comment]
> > We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> > ### System information
> > 
> > * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
> > * **Apollo installed from (source or binary)**:
> > * **Apollo version (3.5, 5.0, 5.5, 6.0)**:
> > * **Output of `apollo.sh config` if on `master` branch**:
> > 
> > ### Steps to reproduce the issue:
> > 
> > * **Please use bullet points and include as much details as possible**:
> > 
> > ### Supporting materials (screenshots, command lines, code/script snippets):
> > ![image](https://user-images.githubusercontent.com/38743240/165670589-2ad572f0-af65-48ca-986a-168fbd5bdbd7.png) should keep 'timestamp' stay same? or '-=' ? 这里不应该'-='吧,是否存在问题
> 
> 您好，不好意思，有些小事需要麻烦你哈。我现在也需要对我的小车更换禾赛的激光雷达，是直接把硬件换上就可以了吗？还是哪里需要做一些额外的操作？

你得保证有对应激光雷达的驱动代码

**Comment by Gatsby23** [comment]
> > > We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.
> > > ### System information
> > > 
> > > * **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
> > > * **Apollo installed from (source or binary)**:
> > > * **Apollo version (3.5, 5.0, 5.5, 6.0)**:
> > > * **Output of `apollo.sh config` if on `master` branch**:
> > > 
> > > ### Steps to reproduce the issue:
> > > 
> > > * **Please use bullet points and include as much details as possible**:
> > > 
> > > ### Supporting materials (screenshots, command lines, code/script snippets):
> > > ![image](https://user-images.githubusercontent.com/38743240/165670589-2ad572f0-af65-48ca-986a-168fbd5bdbd7.png) should keep 'timestamp' stay same? or '-=' ? 这里不应该'-='吧,是否存在问题
> > 
> > 
> > 您好，不好意思，有些小事需要麻烦你哈。我现在也需要对我的小车更换禾赛的激光雷达，是直接把硬件换上就可以了吗？还是哪里需要做一些额外的操作？
> 
> 你得保证有对应激光雷达的驱动代码，首先保证通信没有问题，然后运行对应的驱动程序

这个我是有的，但应该在哪里替换呢
