### ISSUE TITLE
I want the interface request of dreamview

### ISSUE THREAD

**Issue by eternalsilencer** [ApolloAuto/apollo#14430]
I am researching the dreamview function. I want to see the interface between the front-end and the back-end. I want to know where I can view the interface and data structure of these interactions. It is similar to the rest request of OpenApi. Can someone help me solve it? ,Grateful

**Comment by diaokaitian** [comment]
i suggest you refer to the follow video 
https://live.baidu.com/m/media/pclive/pchome/live.html?room_id=4186435259&source=h5pre

**Comment by daohu527** [comment]
Briefly speaking, the front-end and back-end communicate through websocket.

Therefore, it can be considered as an http request. At present, this interface will transmit basically all sensor data to the front-end display. If you want more detailed documents, we may need to summarize it.
