### ISSUE TITLE
Heading difference threshold for Lane Follow Planner

### ISSUE THREAD

**Issue by AkshayDesaiSDCE** [ApolloAuto/apollo#14443]
Where in the code is the heading limit/threshold set for the difference in heading between the ego vehicle s heading and the reference line heading. For instance, if the vehicle is angled at 90 deg to the reference line does the planner still try to plan a path to the reference line? This is in the lane follow scenario. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by qwetqwe** [comment]
Is this line what you need?
https://github.com/ApolloAuto/apollo/blob/9e1edfcc2baf102a69c2998ce5118443945d53ac/modules/map/pnc_map/pnc_map.cc#L499-L500
