### ISSUE TITLE
Is it normal to have a communication delay of 3-4 secs? 通信延迟3-4秒正常吗

### ISSUE THREAD

**Issue by MR-hyj** [ApolloAuto/apollo#14459]
I encountered a communication delay between carla server and apollo which is a bit toublesome. It always caused collisions when routing to destination point. Especially, the ego travels too fast to perform a successful turning.

Carla Server 和 apollo之间的延迟有点高, 导致在导航时总是发生碰撞, 尤其在入弯的时候, 过快的速度导致不能及时完成转弯的动作.

### System information

- **Linux Ubuntu 20.04)**
- **Apollo 5.0**:
- **carla apollo([here](https://github.com/MR-hyj/Fault-Injection-Carla-Apollo))**
- both **carla 0.9.13** and **carla 0.9.11**

### Steps to reproduce the issue:
- **Follow the [README here](https://github.com/MR-hyj/Fault-Injection-Carla-Apollo)**:

### Supporting materials (screenshots, command lines, code/script snippets):

![f369ee95d0421b7eb9da5d5f6804e8c](https://user-images.githubusercontent.com/46344518/168224471-909efda3-23c3-42b4-9717-93d644bbe86d.png)

**Comment by daohu527** [comment]
This doesn't seem to work, 3-4s is a long delay. You should check if network latency or high cpu load rate is causing the problem

**Comment by MaisJamal** [comment]
@MR-hyj Can you please tell me , do you face any problem running the control module? it not working fine when I run it with Carla and I don't know how to fix the problem

**Comment by MR-hyj** [comment]
> @MR-hyj Can you please tell me , do you face any problem running the control module? it not working fine when I run it with Carla and I don't know how to fix the problem

I don't think I've met any similar problems like this... But sometimes it does take me several restarts to get the apollo working..

**Comment by MaisJamal** [comment]
@MR-hyj 
Can you please give me your email, I would like to ask you some questions regarding Carla and Apollo, if you don't mind.

**Comment by MR-hyj** [comment]
> @MR-hyj Can you please give me your email, I would like to ask you some questions regarding Carla and Apollo, if you don't mind.

Sure. It's hengyujiang@njust.edu.cn
