### ISSUE TITLE
Request: build Apollo without docker

### ISSUE THREAD

**Issue by fei4xu** [ApolloAuto/apollo#14457]
**Is your feature request related to a problem? Please describe.**

docker is required to build Apollo, which increased the complexity for non-docker users.
When docker provide the dev environment with many 3rd party libraries, it also hide them: no one cares or can't do anything about them, like to upgrade 3rd party libraries versions.
For example: Fast-RTPS is v1.5.0 in the docker, which is 5 years old now.

**Describe the solution you'd like**

Describe the list of 3rd party libraries and their installations if there is special need for Apollo, then Build Apollo without docker

**Additional context**

I have tried to do it by myself, it turns out to be very easy
1) remove the docker check from `apollo_build.sh`
2) install fast-rtps (installation prefix needs to be same as in Apollo docker), uuid, libncurses5
3) build it with existing bazel build

I successfully built cyber now, will try dreamview later, which needs boost.

If this feature is interesting for anyone, I would like to create a pull request.

Thanks.

**Comment by felixf4xu** [comment]
all build scripts are at: [apollo](https://github.com/ApolloAuto/apollo)/[docker](https://github.com/ApolloAuto/apollo/tree/master/docker)/[build](https://github.com/ApolloAuto/apollo/tree/master/docker/build)/[installers](https://github.com/ApolloAuto/apollo/tree/master/docker/build/installers)/install_fast-rtps.sh

**Comment by diaokaitian** [comment]
there has someone do this job  you can refer to this video [https://www.bilibili.com/video/BV1Br4y1i73E?spm_id_from=333.999.0.0](url)

**Comment by daohu527** [comment]
Currently compiling without docker is not supported, but you can try to install the whole environment ref the docker file
