### ISSUE TITLE
Can't enter docker the second time by `bash docker/scripts/dev_into.sh`

### ISSUE THREAD

**Issue by fei4xu** [ApolloAuto/apollo#14456]
### System information

- **Linux Ubuntu 18.04, arm64 (jetson)**:
- **Apollo installed from (source)**:
- **Apollo version (7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:
```
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /home/f/github/apollo
[INFO]     APOLLO_CACHE_DIR: /home/f/github/apollo/.cache
[INFO]     APOLLO_IN_DOCKER: false
[INFO]     APOLLO_VERSION: r7.0.0-2021-12-28-463fb82f9e
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1
[INFO] Usage: /home/f/github/apollo/scripts/apollo_config.sh [Options]
```
### Steps to reproduce the issue:

I'm trying to run Apollo with docker (on a Jetson device)

- 1. bash docker/scripts/dev_start.sh
- 2. bash docker/scripts/dev_into.sh

OK and I can enter the docker to check if Apollo files exist.

Then I exit docker and commit my change:
```
f@nano:~/github/apollo$ sudo docker ps
CONTAINER ID   IMAGE                                               COMMAND       CREATED         STATUS         PORTS     NAMES
898b36639e8b   apolloauto/apollo:dev-aarch64-18.04-20201218_0030   "/bin/bash"   3 minutes ago   Up 2 minutes             apollo_dev_root
```
```
f@nano:~/github/apollo$ sudo docker commit -a "f" -m "install" 898b36639e8b   apolloauto/apollo:dev-aarch64-18.04-20201218_0030
sha256:bc3382907cdd3a51e5f7bfde9fae79065f39406ea392db807fd60b84906d6191
```
Then I power off my jetson and power on it again.

For the second time, I assume I should enter the docker by `bash docker/scripts/dev_into.sh` but I have this error:
>Error response from daemon: Container 898b36639e8ba572e62aafd2b1fc0e65c248c9220a45e5ddcca494b76b4906c2 is not running

I guess I might run `bash docker/scripts/dev_start.sh` again, but my docker commit is lost.

I also tried the `-f -l` flags, but no luck. I also trid `-t` flag with `bc3382907cdd3a51e5f7bfde9fae79065f39406ea392db807fd60b84906d6191` but I still can't enter the docker with my committed change.

### Question:

What's the designed way to enter the docker after some change/commit?

Thanks,
Fei

**Comment by ntutangyun** [comment]
I'm not an expert, but maybe you can use the `docker images` to check if the apollo image has been updated after the commit.

also note that 

> The commit operation will not include any data contained in volumes mounted inside the container.

**Comment by diaokaitian** [comment]
if you have run   bash docker/scripts/dev_start.sh before ,you should try the following comands:
1、docker ps -a    
_if will return the  DOCKER_ID_
2、docker start DOCKER_ID
3、bash docker/scripts/dev_into.sh

**Comment by daohu527** [comment]
@fei4xu  the method above will work!
