### ISSUE TITLE
apollo dreamview可以单独拿出来用吗？怎么用？

### ISSUE THREAD

**Issue by zhangbowei** [ApolloAuto/apollo#14451]
apollo dreamview可以单独拿出来用吗？怎么用？

**Comment by ntutangyun** [comment]
可以。比如说我整的这个 hd map viewer :)

https://ntutangyun.github.io/apollo-hd-map-viewer/

**Comment by zhangbowei** [comment]
赞。
有sim_map.bin文件可以看下效果吗？
如果想做成实时的可以不？（走5G外网）

**Comment by ntutangyun** [comment]
add me on wechat, and we can discuss: 

XX_101n374i1_XX
