### ISSUE TITLE
How to create a JSon compilation database?

### ISSUE THREAD

**Issue by alexdeba** [ApolloAuto/apollo#14468]
With Bazel it is possible to create a compilation database in JSon format using tools like, for example:

https://github.com/grailbio/bazel-compilation-database

Apollo being based on Bazel, it should be possible to generate this compilation database. But these tools are not working with Apollo. Is there a way to create this database?

**Comment by daohu527** [comment]
As you said bazel-compilation-database itself provides a bazel rule to generate the database, you can implement it by adding the rule in your build file following the example.

By the way, this will be a big job, maybe you can use some tools to do it

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
