### ISSUE TITLE
How to use Caffe environment

### ISSUE THREAD

**Issue by xueyingliu** [ApolloAuto/apollo#14460]
I want to run lidar cnn_seg , which use caffe in an old version of apollo, and the link is out of date:

wget [https://apollocache.blob.core.windows.net/apollo-docker/caffe_x86.tar.gz](https://apollocache.blob.core.windows.net/apollo-docker/caffe_x86.tar.gz)

can you update the link, or give some advice to install the caffe environment? I install caffe by following the official network, but that does not work.

**Comment by oooooverflow** [comment]
I have encountered the same problem. Have you ever solved it ?
