### ISSUE TITLE
r7.0&r6.0:  lattice path_time_graph: max_t() and min_t() are used in function GetPathBlockingIntervals, but they are not initialized

### ISSUE THREAD

**Issue by liyong2019** [ApolloAuto/apollo#14467]
- Version r6.0.0 & r7.0.0
 - File: path_time_graph.cpp
 - Function: std::vector<std::pair<double, double>> PathTimeGraph::GetPathBlockingIntervals(const double t) const
 - Bug:
  for (const auto& pt_obstacle : path_time_obstacles_) {
    if (t > pt_obstacle.max_t() || t < pt_obstacle.min_t()) {
      continue;
    }
max_t() and min_t() are used but they are not initialized

**Comment by diaokaitian** [comment]
you can check if the where is the member variable are updated, there is no need for the member function to be initialized

**Comment by liyong2019** [comment]
max_t() and min_t() returns min_t_ and  max_t_ respectively. min_t_ and  max_t_ are updated only in Constructor "STBoundary::STBoundary(
    const std::vector<std::pair<STPoint, STPoint>>& point_pairs,
    bool is_accurate_boundary)"
However, this Constructor is not called. the default Constructor “STBoundary() = default;”  is called in path_time_graph.h.

**Comment by diaokaitian** [comment]
may be you can write a test case to prove your point

**Comment by chenxiaoying21** [comment]
@liyong2019 It seems you are right. The default constructor of "STBoundary" is called in path_time_graph.cpp. And in this case min_t_ and max_t_ is the default values: std::numeric_limits<double>::max() and std::numeric_limits<double>::lowest().
