### ISSUE TITLE
vehicle in EMERGENCY_MODE after canbus.sh lauched #Canbus

### ISSUE THREAD

**Issue by ZYuqiYuqi** [ApolloAuto/apollo#14466]
System information

    Ubuntu 18.04
    installed from source
    based on Apollo r5.5.0

Steps to reproduce the issue:

    follow the Apollo official guide to generate the new vehicle's protocol and folder
    change the controller.cc to adapt the different CAN ID and messages
    compile the binary
    compile pass
    launch SocketCAN
    launch scripts/canbus.sh or scripts/bootstrap.sh
    launch teleop.sh

Supporting materials (screenshots, command lines, code/script snippets):

    IPC: Nuvo-8108GC
    CAN CARD: EMUC-B202
    CAN Driver: SocketCAN

After I lauched teleop script, I‘ve found the vehicle stuck in emergency mode and it only responses to reset command.

Here is the mainboard log:

[time and locate] Can Client is successfully created.
[time and locate] successfully created vehicle factory with brand: VV6 max_enable_fail_attempt: 5 driving_mode:
[time and locate] COMPLETE_AUTO_DRIVE
........
[time and locate] Can client sender thread starts

[time and locate] Canbus received pad msg: action:START
[time and locate] veihcle in EMERGENCY_MODE, only response to COMPLETE_MANUAL mode.
[time and locate] only response to RESET ACTION.
......(loop)

How could I found the reason led to EMERGENCY_MODE and solve it?

**Comment by daohu527** [comment]
I suggest you to check the following 2 functions.
1. In `EnableAutoMode`, check if `CheckResponse` have no response.
2. In `SecurityDogThreadFunc`, check `CheckChassisError` if true.

when meet an error, it will enter emergency mode. So please check above 2 points and see if you can find any problem!

**Comment by ZYuqiYuqi** [comment]
> I suggest you to check the following 2 functions.
> 
>     1. In `EnableAutoMode`, check if `CheckResponse` have no response.
> 
>     2. In `SecurityDogThreadFunc`, check `CheckChassisError` if true.
> 
> 
> when meet an error, it will enter emergency mode. So please check above 2 points and see if you can find any problem!

I have found the no responser error from 'CheckResponse':  the signals: has_is_eps_online, has_is_esp_online and has_is_vcu_online are all 0. This led to Cheresponse_fail. How could I solve it?

**Comment by daohu527** [comment]
Different vehicles may differ slightly, general speaking, vehicle should support autonomous mode then we can enter fully autonomous driving mode.

after send the autonomous cmd to the car, it will send a response whether it's in autonomous mode by set eps and vcu on. so we should check eps and vcu are on, if not, then it means that the car is not in autonomous mode.

* EPS - Electric power steering
* VCU - Vehicle Control Units 

## reason
1. check the car received then enable autonomous cmd. And the cmd is right
2. check the can bus module receive the response, and you set it to the `chassis_detail`

This may require you to check the car's canbus protocol manual and the canbus module in apollo

**Comment by ZYuqiYuqi** [comment]
> Different vehicles may differ slightly, general speaking, vehicle should support autonomous mode then we can enter fully autonomous driving mode.
> 
> after send the autonomous cmd to the car, it will send a response whether it's in autonomous mode by set eps and vcu on. so we should check eps and vcu are on, if not, then it means that the car is not in autonomous mode.
> 
>     * EPS - Electric power steering
> 
>     * VCU - Vehicle Control Units
> 
> 
> ## reason
> 
>     1. check the car received then enable autonomous cmd. And the cmd is right
> 
>     2. check the can bus module receive the response, and you set it to the `chassis_detail`
> 
> 
> This may require you to check the car's canbus protocol manual and the canbus module in apollo

In trace I've found the enable autonomous command was successfully sent, but the vehicle didn't react to it. Is this the problem of the test vehicle?

**Comment by daohu527** [comment]
I'm not sure, but the car needs to meet some conditions to enter autopilot, such as braking state, aeb state, etc. Some cars require braking to enter autopilot for safety

**Comment by ZYuqiYuqi** [comment]
> I'm not sure, but the car needs to meet some conditions to enter autopilot, such as braking state, aeb state, etc. Some cars require braking to enter autopilot for safety.
> 
> you should contact the vehicle manufacturer

After I checked the trace file, I've found that after the enable autonomous driving commend sent was the vehicle in automatic driving mode set and last for about 0.3s. Then the automatic driving_mode was exited and the vehicle came back to manuel mode. I have conducted with the vehicle manufacturer. They gave me a document about the exit mechanism of the vehicle but the vehicle hasn't fulfilled the exit condition and exited from autonomous mode.

**Comment by daohu527** [comment]
then have you confirmed that the vehicle can enter the conditions for autonomous driving? as i said before, for safety, entering autonomous driving requires the vehicle to meet certain conditions

**Comment by ZYuqiYuqi** [comment]
> then have you confirmed that the vehicle can enter the conditions for autonomous driving? as i said before, for safety, entering autonomous driving requires the vehicle to meet certain conditions

I've solved this issue, and great thanks to you!
