### ISSUE TITLE
Can localization module run without RTK account?

### ISSUE THREAD

**Issue by asef18766** [ApolloAuto/apollo#14470]
I've been wondering if there is a possibility to use only the IMU device without RTK account to bring up localization module.
### System information
- **OS Platform and Distribution: Linux Ubuntu 18.04**
- **Apollo installed from: source**
- **Apollo version: 5.5**

### Steps to reproduce the issue:
follow all the instruction from [D-kit user manual](https://github.com/ApolloAuto/apollo/tree/master/docs/D-kit) until the step [循迹搭建--定位模块配置](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Waypoint_Following/localization_configuration_cn.md)

**Comment by daohu527** [comment]
What is your use case? No RTK output will result in inaccurate localization. Therefore, accurate localization is the premise, If you just want to validate the flow, you can use mock localization instead.

**Comment by asef18766** [comment]
My objective is to render point cloud and obstacle perception in dreamview by using VLP16. However, it seems not to be working due to the transformation from **novetal** to **world** being missing(from the log of lidar compensator by using static transform publisher).  Currently, I am working on setting up a whole localization system without an RTK account. Is there exist a method to mock localization module and publish valid ```/tf``` topic for compensator? please let me know, thanks.

**Comment by daohu527** [comment]
As mentioned before, you can mock the location and tf, just send the corresponding message

**Comment by fanyueqiao** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
