### ISSUE TITLE
What's the meaning of avg_drift

### ISSUE THREAD

**Issue by gumpcarl** [ApolloAuto/apollo#14473]
https://github.com/ApolloAuto/apollo/blob/e076feecb46232bacdf08490c5ff213832e6bdd8/modules/prediction/container/obstacles/obstacle.cc#L1346

![image](https://user-images.githubusercontent.com/49071814/170177092-3e9cb910-815f-456a-b4f2-9c7abdc6595f.png)

**Comment by daohu527** [comment]
@gumpcarl  Could you pls describe your question in detail so that it may be easier for others to answer.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
