### ISSUE TITLE
Any open source make shift simulator to run Apollo AV stack?

### ISSUE THREAD

**Issue by satheesh-kk** [ApolloAuto/apollo#14472]
Hi All,
As LGSVL going to be sunset, any make shift open source simulator to run Apollo AV stack?
Can we run the SVL itself in any of the offline mode, which could help for faster development?

Help suggest some inputs. Appreciate your guidance.

**Comment by daohu527** [comment]
lgsvl just doesn't develop new features anymore, you can keep using it.

At present, the mainstream simulators are carla and lgsvl. By the way, apollo has a lightweight simulator called sim control in dreamview.

At present, the mainstream simulators are carla and lgsvl. By the way, apollo has a lightweight simulator called sim control in dreamview. I'm afraid I can't make it clear in a few words.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
