### ISSUE TITLE
Which Localization Folder Does Apollo Use By Default to Obtain Position of Vehicle

### ISSUE THREAD

**Issue by OG-ChefBoyardee** [ApolloAuto/apollo#14477]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution: Linux - Ubuntu 20.04 LTS
- **Apollo installed from - Source
- **Apollo version - 5.5

### Steps to reproduce the issue:
- **Under the modules/localization folder of apollo, there are 3 localization subfolders: nsf, msf, and rtx. I know that each folder represents a different type of localization. However, I am really struggling to figure out which of these three methods (folders) apollo defaults to using. If someone is willing to inform me, I would greatly appreciate it.
My second question is: Which file in the folder is the one that actually computes the coordinates of the car? I ask because my goal here is to write the coordinates of the vehicle to a text file during a simulation in LGSVL. Any responses are greatly appreciated.

**Comment by daohu527** [comment]
If you use the LGSVL, the default config is `rtk`, you can subscribe to the LocalizationEstimate message, then write to a file, for example just write to the log.

## how to check which module is use 
1. In dreamview you will first to choice a car, the config files is all in `modules/dreamview/conf/hmi_modes`.
2. if you choice the `mkz_lgsvl`, then you should look for modules/dreamview/conf/hmi_modes/mkz_lgsvl.pb.txt
3. search the localization dag config really use which is
```
cyber_modules {
  key: "Localization"
  value: {
    dag_files: "/apollo/modules/localization/dag/dag_streaming_rtk_localization.dag"
  }
}
```
