### ISSUE TITLE
This ApplyNMS in detection.cc seems not necessary [Traffic Light detection]

### ISSUE THREAD

**Issue by boyang9602** [ApolloAuto/apollo#14476]
Hi,

I am reading the traffic light detection module's code. I found [this code](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) weird. There's already [an NMS ](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/tensorrt/plugins/rcnn_proposal_plugin.cu#L345)being applied in the RCNN layer of the detection model, and the overlap_ratio is lower. So I think [the NMS in `detection.cc`](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) is unnecessary. 

Besides, there is [a loop over the batch_num in detection.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L166), which means the code can detect traffic lights for multiple pictures. So why NMS is outside the loop (i.e., only apply NMS for the traffic lights detected from the last picture)? I feel it is weird. 

Thank you.

**Comment by liouyx** [comment]
> I am reading the traffic light detection module's code. I found [this code](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) weird. There's already [an NMS ](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/tensorrt/plugins/rcnn_proposal_plugin.cu#L345)being applied in the RCNN layer of the detection model, and the overlap_ratio is lower. So I think [the NMS in detection.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) is unnecessary.

The parameters and data formats of the two methods are different，It's better to use two methods.

> Besides, there is [a loop over the batch_num in detection.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L166), which means the code can detect traffic lights for multiple pictures. So why NMS is outside the loop (i.e., only apply NMS for the traffic lights detected from the last picture)? I feel it is weird.

In a normal way, each data is processed in the loop, and all the batch data are processed outside the loop.

**Comment by qilinhu** [comment]
I am reading the traffic light detection module's code. I found [this code](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) weird. There's already [an NMS ](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/tensorrt/plugins/rcnn_proposal_plugin.cu#L345)being applied in the RCNN layer of the detection model, and the overlap_ratio is lower. So I think [the NMS in detection.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) is unnecessary.
hi! I think [the NMS in detection.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) is necessary.The role of the ApplyNMS function is to eliminate duplicate detection boxes in Crop ROIs with overlapping regions.

**Comment by boyang9602** [comment]
I just re-read the code. Here is my understanding of the entire process:
1. There are multiple traffic light pictures to be detected by `bool TrafficLightDetection::Inference(std::vector<base::TrafficLightPtr> *lights, DataProvider *data_provider)`.
2. Because of the network limitation, only one image could be processed each time. 
3. So there is a [loop](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L166) to do the inference for each image by the network. 
4. During the inference, at the last layer of the network, there is [a NMS to eliminate the duplicated traffic lights](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/tensorrt/plugins/rcnn_proposal_plugin.cu#L345). 
5. After each inference, there is a [selection process](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L224) to select valid traffic lights for each traffic light image and the valid traffic light[ is pushed to the vector `detected_bboxes_`](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L374). **_Here is my first doubt: why are the detected traffic lights for different images put into one vector together?_**
6. After all the images are processed, there is [another NMS](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/traffic_light/detector/detection/detection.cc#L228) to eliminate the duplicated boxes of detected boxes from multiple traffic lights. _**Here is my next doubt: what is the meaning to do so?**_

Or maybe this way, what is the relationship between these different traffic light images and why are their detection results merged and processed together?

**Comment by daohu527** [comment]
## 1. NMS
@boyang9602 I think they're different levels
1. Just for detection, which is a process in rcnn network
2. Perform NMS on the detection results

You know the traffic lights are close to each other, I think they might have duplicate parts in crop picture, so I think the 2rd NMS is to remove duplicate results.

![tf](https://user-images.githubusercontent.com/10419854/195795816-92cfa5a8-48be-446f-a3f7-5bbff4ae4e0d.jpg)

## 2. why are the detected traffic lights for different images put into one vector together?
As you said, the network can just process 1 pic at a time, not support batch, the use one vector is just like a batch result output.
