### ISSUE TITLE
How to do automatic search for free parking spaces around and parking? 

### ISSUE THREAD

**Issue by minorikawafuso** [ApolloAuto/apollo#14483]
System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

I am doing valet parking, I want let car find a free parking space automatically and park it by itself, I know that I need to find a parking space first, and then send the parking space info to the routing module. But now I don't know how to find the parking space without any other cars, does Apollo have this method?

**Comment by diaokaitian** [comment]
[https://www.bilibili.com/video/BV1p94y1m7ms?spm_id_from=333.337.search-card.all.click](url)

**Comment by qwetqwe** [comment]
apollo needs to specify parking space，does not support detect which parking space is empty. You can realize one
