### ISSUE TITLE
sim_obstacle 崩溃，是因为avx指令集的原因吗？

### ISSUE THREAD

**Issue by jedz5** [ApolloAuto/apollo#14486]
**Describe the bug**
![image](https://user-images.githubusercontent.com/10917512/173235944-0ede7d9c-2a4b-4123-930c-8dea5b648060.png)

![image](https://user-images.githubusercontent.com/10917512/173235973-13a42a4e-bdcc-4707-a7d8-6b00422f1a26.png)

**Comment by daohu527** [comment]
Did you compile and run locally? Looks like a problem with protobuf

**Comment by ntutangyun** [comment]
这个sim_obstacle 是哪个branch的模块：）

**Comment by jedz5** [comment]
> Did you compile and run locally? Looks like a problem with protobuf

这个是edu_challenge_sim 分支 城市道路自动驾驶虚拟仿真赛 要用的障碍物模块，是编译好的，我确认是avx指令集的问题，可以提供源码重新编译吗？

**Comment by jedz5** [comment]
> 这个是edu_challenge_sim 分支 城市道路自动驾驶虚拟仿真赛 要用的障碍物模块

这个是edu_challenge_sim 分支 城市道路自动驾驶虚拟仿真赛 要用的障碍物模块

**Comment by jedz5** [comment]
> 这个sim_obstacle 是哪个branch的模块：）

这个是edu_challenge_sim 分支 城市道路自动驾驶虚拟仿真赛 要用的障碍物模块
