### ISSUE TITLE
planning module start error.

### ISSUE THREAD

**Issue by Forrest-Z** [ApolloAuto/apollo#14488]
### System information

- **Linux Ubuntu 20.04**:
- **Apollo installed from source**:
- **Apollo version 7.0**:
- **Output of `apollo.sh config` if on `7.0` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- 1.run `./docker/scripts/dev_start.sh` start container
- 2.run `./docker/scripts/dev_into.sh` into container
- 3.use vscode remote container
- 4.start debug planning module

### Supporting materials (screenshots, command lines, code/script snippets):
I try to debug planning module use vecode, but it start fail when output this log (PS: debug control module success):
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0615 14:27:32.142376 12989 module_argument.cc:81] []command: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/k8-dbg/bin/cyber/mainboard/mainboard -d /apollo/modules/planning/dag/planning_navi.dag 
I0615 14:27:32.142632 12989 global_data.cc:153] []host ip: 172.17.8.112
W0615 14:27:32.142642 12989 environment.h:33] []Environment variable [CYBER_PATH] not set, fallback to 
I0615 14:27:32.146597 12989 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I0615 14:27:32.147459 12989 module_argument.cc:60] []dag_conf: /apollo/modules/planning/dag/planning_navi.dag
E0615 14:27:32.331519 12989 class_loader_utility.cc:218] [mainboard]LibraryLoadException: libc10.so: cannot open shared object file: No such file or directory
E0615 14:27:32.331575 12989 class_loader_utility.cc:234] [mainboard]shared library failed: /apollo/bazel-bin/modules/planning/libplanning_component.so
E0615 14:27:32.338169 12989 class_loader_manager.h:70] [mainboard]Invalid class name: PlanningComponent
E0615 14:27:32.338222 12989 module_controller.cc:67] [mainboard]Failed to load module: /apollo/modules/planning/dag/planning_navi.dag
E0615 14:27:32.338238 12989 class_loader_utility.cc:256] [mainboard]Attempt to UnloadLibrary lib, but can't find lib: /apollo/bazel-bin/modules/planning/libplanning_component.so
E0615 14:27:32.338248 12989 mainboard.cc:39] [mainboard]module start error.

**Comment by daohu527** [comment]
https://github.com/ApolloAuto/apollo/issues/14307#issuecomment-1168866423

1. check if libc10.so is exist use `ls /usr/local/libtorch_cpu/lib/` or `ls /usr/local/libtorch_gpu/lib/`
2. if exist use `sudo ldconfig` to add the path to runtime dynamic library search path
