### ISSUE TITLE
ubuntu20.04/apollo7.0 build ERROR: Config value 'gpu' is not defined in any .rc file

### ISSUE THREAD

**Issue by zl1234zl** [ApolloAuto/apollo#14481]
ubuntu20.04/apollo7.0 build ERROR: Config value 'gpu' is not defined in any .rc file

**Comment by daohu527** [comment]
what your build command looks like？

**Comment by WildBeast114514** [comment]
bazel use .rc file to define some behavior of config.
The following files shall be provided in Apollo:
.bazelrc
.apollo.bazelrc
tools/bazel.rc
if you haven't seen these files, i suggest you download Apollo again or clone again
