### ISSUE TITLE
Apollo's traffic light module not work

### ISSUE THREAD

**Issue by JasonBourne1998** [ApolloAuto/apollo#14485]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: Apollo 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
When I have open the traffic light module, the module did not work. And I use the cyber_launch command, it shows no error in the panel. But the traffic light module still not work.

![image](https://user-images.githubusercontent.com/51346614/172980662-b9cb0b66-4aa4-4df1-b085-2fa4bc7a6aec.png)
![image](https://user-images.githubusercontent.com/51346614/172980707-c7f284a0-6bee-427b-8b90-84cf6cd7c1d8.png)
![image](https://user-images.githubusercontent.com/51346614/172980552-9097a70c-694f-4a5a-9958-1335723774d6.png)
I refer to the /apollo/data/log, and I guess it maybe caused by these?
W0610 10:16:12.447165 54040 tl_preprocessor.cc:94] sync_image failed - find close enough projection,but camera_name not match.
W0610 10:16:12.434821 54040 buffer.cc:214] BufferCore::canTransform failed: canTransform: target_frame world does not exist.
W0610 09:27:45.925873 48285 protobuf_factory.cc:218] [modules/perception/proto/traffic_light_detection.proto] A file with this name is already in the pool.

Any idea to solve this?

**Comment by JasonBourne1998** [comment]
@daohu527 Sorry to bother you, but could you give me any suggestions? It seem that there is no error in the perception log, and the module works well, just no output.
![image](https://user-images.githubusercontent.com/51346614/173002489-2ddbb8ec-ef87-4b26-bd32-c3213f80a8e7.png)

log attachments. [perception.zip](https://github.com/ApolloAuto/apollo/files/8876194/perception.zip)

**Comment by daohu527** [comment]
How do you run it? Simulation or actual driving test. In general, we should start to check step by step.

## check steps
In simple terms, we check the following 3 steps
1. the input
2. the process (modules/perception/onboard/component/trafficlights_perception_component.h)
3. the output (result)

First we check if we receive the input camera image, then check the processing, or you can skip to the last step to see if the detection result is output.

So we should work step by step and see if we can find the problem!

**Comment by JasonBourne1998** [comment]
> 
Thanks for reply,  I use lgsvl simulator
firstly, I think the input is the camera? I think the camera part gets correct in the cyber_visualizer
and I think there is no output corresponding to the cyber_monitor.
![image](https://user-images.githubusercontent.com/51346614/173167903-44f4fed4-ec64-4721-843a-302062921c33.png)
![image](https://user-images.githubusercontent.com/51346614/173167929-56f85149-7143-4994-88e6-72bcd65c4f6d.png)

so could you tell me the next step I need to check?

**Comment by daohu527** [comment]
the main entry point is

https://github.com/ApolloAuto/apollo/blob/49647ab0f8ff0e8349f7099b8487f5245a10e293/modules/perception/onboard/component/trafficlights_perception_component.cc#L310

You can try to debug from it, find or add some log will help you to debug.

**Comment by JasonBourne1998** [comment]
> the main entry point is
> 
> https://github.com/ApolloAuto/apollo/blob/49647ab0f8ff0e8349f7099b8487f5245a10e293/modules/perception/onboard/component/trafficlights_perception_component.cc#L310
> 
> You can try to debug from it, find or add some log will help you to debug.

**Comment by JasonBourne1998** [comment]
@daohu527 Thanks, I have solved this problem, but there comes the new one, I found that the Apollo would get down when turning a corner, and the planning module does not work. Do you know if there is a way to fix it?
This is the screenshot:
![08b5b7193cfa32e9e0d6d894cbbd14e](https://user-images.githubusercontent.com/51346614/173195456-5a40e6dc-bac9-4a65-abcb-a3a68b13d1d6.png)

**Comment by daohu527** [comment]
according to you screenshot, it may cause by the routing path is not correct, the root cause is a problem with the map, you can try another place  in the map. 

By the way, we should keep the issue focused and consistent with the title, if there is a new issue, we'd better open a new issue to discuss. 

If you can, you can write the reason for this issue to help others. The prosperity of the community requires everyone to work together!
