### ISSUE TITLE
How to set the acceleration for an obstacle?

### ISSUE THREAD

**Issue by Beanocean** [ApolloAuto/apollo#14497]
https://github.com/ApolloAuto/apollo/blob/9e1edfcc2baf102a69c2998ce5118443945d53ac/modules/prediction/container/obstacles/obstacle.cc#L551

Could someone help explain why the acceleration of the obstacle is computed as lin 551? Is the obstacle assumed in Uniformly accelerated linear motion?

**Comment by liouyx** [comment]
The acceleration is in the X and Y direction.
https://github.com/ApolloAuto/apollo/blob/master/modules/prediction/container/obstacles/obstacle.cc#L535
Acceleration is calculated by velocity over a short period of time.

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by Beanocean** [comment]
> The acceleration is in the X and Y direction. https://github.com/ApolloAuto/apollo/blob/master/modules/prediction/container/obstacles/obstacle.cc#L535 Acceleration is calculated by velocity over a short period of time.

In my mind, I think the value of acc should be:
``` c++
acc = std::hypot(acc_x, acc_y);
```
Could you please provide a further explanation?

**Comment by liouyx** [comment]
The calculation of acceleration is similar to the addition of two vectors. 
Your calculation is incorrect because the acceleration cannot always be greater than zero. When the vehicle decelerates, the acceleration is negative.
