### ISSUE TITLE
Problems of Apollo in lane change and turn

### ISSUE THREAD

**Issue by JasonBourne1998** [ApolloAuto/apollo#14493]
**Describe the bug**
When Apollo changes lanes in the **SanFrancisco** map of **lgsvl**, there are some bugs. Sometimes it caused by turning in a corner, and sometimes it cannot change lanes correctly due to the problem of the planning module

**To Reproduce**
1. Go to lgsvl only api mode
2. Run the simulation
3. Set the destination which needs turn or lane-change

**Expected behavior**
Apollo should turn and change lanes smoothly

**Screenshots**
https://drive.google.com/file/d/1fEnc3QfGBnQauBeWARo4l5F8y3sH0xLf/view?usp=sharing
https://drive.google.com/file/d/1FsQNRuAvRucTcFJjdj38pLqP4G0SpuEC/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version Apollo 6.0

**Comment by qwetqwe** [comment]
Is planning frequency normal? It seems that your cpu overloads with apollo and lgsvl
