### ISSUE TITLE
cv::VideoCapture can not open .mp4 or .avi videos when using docker

### ISSUE THREAD

**Issue by wiki-love** [ApolloAuto/apollo#14491]
c++:
 cv::VideoCapture vinput("vtest01.avi");
 vinput.isOpened()  will return false.

python:
import cv2
vinput= cv2.VideoCapture("vtest01.avi")
 vinput.isOpened()  returns false too.

but both  can open open usb camera, such as 
 cv::VideoCapture vinput(0);
 vinput.isOpened()  will return true.

**Comment by daohu527** [comment]
According to the VideoCapture api [docs](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html#a949d90b766ba42a6a93fe23a67785951), VideoCapture will use the `apiPreference` in backend. 

So we first need to confirm that the compilation of opencv contains these options. [link](https://docs.opencv.org/3.4/d0/da7/videoio_overview.html)

![image](https://user-images.githubusercontent.com/10419854/176076227-edf2e709-2150-48dd-92ff-5cb52962c7f0.png)

**Comment by wiki-love** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wiki-love** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hdm8809** [comment]
@wiki-love 
Hello, i also have this problem.
I want to add a ip camera wiht rtsp protocol.
It work well in apollo6.0, and wrong in apllo6.0_edu, apollo7.0.
Can you solve this problem?

**Comment by wiki-love** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
