### ISSUE TITLE
how to create NDT map in apollo 

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#14492]
![image](https://user-images.githubusercontent.com/1448987/174214921-1f4d591f-a73b-4b2f-aa5e-49213abffd09.png)
I found the description [here](https://github.com/ApolloAuto/apollo/tree/master/modules/localization/ndt)，but I cant found this file "(apollo/scripts/ndt_local_map_creator.sh"

**Comment by daohu527** [comment]
It looks like this script doesn't exist. In fact, we can use "modules/localization/ndt/map_creation/ndt_map_creator.cc" to create ndt map, I will add the detailed process later.
https://github.com/ApolloAuto/apollo/issues/10609
