### ISSUE TITLE
Camera cannot get fotos or video: leopard AR023ZWDR

### ISSUE THREAD

**Issue by ZYuqiYuqi** [ApolloAuto/apollo#14501]
- OS Platform and Distribution Linux Ubuntu 18.04:
- Apollo installed from source:
- Apollo version 5.5,:
- Camera: leopard AR023ZWDR (usb3.0);

there is a strange issue that I can get the camera information through "udevadm info --attribute-walk --name=/dev/video* " command. And the soft link with the cameras exist. But the node dies after throwing an error called [ERROR] : select timeout.
I used cheese to access the camera, but it showed nothing.

How could I solve it?

**Comment by lykling** [comment]
How did you launch the camera module?
please post the content of dag file(`modules/drivers/camera/dag/camera.dag`) and output of `udevadm info --attribute-walk --name=/dev/video*` and `ls -al /dev/camera`

**Comment by lykling** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
