### ISSUE TITLE
About Xilinx Zynq UltraScale MPSOC XCZU5EV

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#14508]
1 我从http://www.eepw.com.cn/article/202008/416745.htm得知百度apollo可以在Xilinx  FPGA上进行部署，能确认下是
 Xilinx Zynq UltraScale MPSOC XCZU5EV这款FPGA芯片吗？

2 支持的范围有多大?比如是泊车还是行泊一体，行车是低速还是中高速？

3 能否给一些Xilinx Zynq UltraScale MPSOC XCZU5EV部署Apollo算法相关的文档或者资料

谢谢哈！

**Comment by daohu527** [comment]
@yumianhuli2 Thank you for your attention, detailed information about ACU can refer to [link](https://developer.apollo.auto/platform/hardware.html)  

The soc is "**Xilinx ZU5/ Aurix TC297**", and the operating system is "Linux/QNX & AUTOSAR". For detailed business, you can consult more on the above website!
