### ISSUE TITLE
no such package '@eigen//'

### ISSUE THREAD

**Issue by fergcd** [ApolloAuto/apollo#14504]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution : Linux Ubuntu 20.04**
- **Apollo installed from : source**
- **Apollo version : 5.5**
- **branch : r5.5.0**

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
1. (From the ${APOLLO_ROOT_DIR} directory)
2. git checkout -t origin/r5.5.0
3. ./docker/scripts/dev_start.sh
4. ./docker/scripts/dev_into.sh
5. touch WORKSPACE
6. bazel build //modules/perception/lidar/tools:offline_lidar_obstacle_perception

I want to use LiDAR 3D Object Detection in perception module.
I followed this reply (https://github.com/ApolloAuto/apollo/issues/13445#issuecomment-782576120)
but it doesn't work.

Error occurs like this.
![image](https://user-images.githubusercontent.com/13186723/176426409-4065a0b3-198e-488f-9d37-19766c96faba.png)

What should I do now???

**Comment by fergcd** [comment]
> you can post you BUILD file ,may be there are some syntax error of your build file

@diaokaitian Here is my BUILD file.

`load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "offline_lidar_obstacle_perception",
    srcs = ["offline_lidar_obstacle_perception.cc"],
    deps = [
        "//cyber",
        "//modules/drivers/proto:sensor_proto",
        "//modules/map/proto:map_proto",
        "//modules/perception/base",
        "//modules/perception/common:perception_gflags",
        "//modules/perception/common/io:io_util",
        "//modules/perception/common/point_cloud_processing",
        "//modules/perception/common/sensor_manager",
        "//modules/perception/lidar/app",
        "//modules/perception/lidar/lib/classifier/fused_classifier",
        "//modules/perception/lidar/lib/classifier/fused_classifier:ccrf_type_fusion",
        "//modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector",
        "//modules/perception/lidar/lib/object_builder",
        "//modules/perception/lidar/lib/object_filter_bank/roi_boundary_filter",
        "//modules/perception/lidar/lib/roi_filter/hdmap_roi_filter",
        "//modules/perception/lidar/lib/scene_manager/ground_service",
        "//modules/perception/lidar/lib/scene_manager/roi_service",
        "//modules/perception/lidar/lib/segmentation/cnnseg:cnn_segmentation",
        "//modules/perception/lidar/lib/tracker/multi_lidar_fusion:mlf_engine",
        "//modules/perception/lidar/lib/tracker/multi_lidar_fusion:mlf_track_object_matcher",
        "//modules/perception/lidar/lib/tracker/multi_lidar_fusion:mlf_tracker",
        "//modules/perception/proto:perception_config_schema_proto",
        "@eigen",
        "@pcl",
    ],
)

cpplint()
`

**Comment by dreamholy** [comment]
it seems that "eigen" package not found, 
[Apollo version : 5.5] 
![image](https://user-images.githubusercontent.com/6008287/180359996-26ff10e1-fffa-4184-9c5b-d5b9687625bc.png)
I suggest you check this local path.
