### ISSUE TITLE
perception::lidar::CNNSegmentation inference abnormal after upgrade TensorRT to 8.4.1.5

### ISSUE THREAD

**Issue by lygbuaa** [ApolloAuto/apollo#14514]
**Describe the bug**
I was developing on Apollo v6.0 since 2021.10, based on the docker image apolloauto/apollo:dev-x86_64-18.04-20210517_1712, I can run all the perception model correctly.
The TensorRT preinstalled was 7.2.1, the module **perception::lidar::CNNSegmentation** can detect obstacles smoothly, infer time is about 11ms on my GPU.
Now I upgrade TensorRT to 8.4.1.5, **perception::lidar::CNNSegmentation** inference time increased abnormally to about **80ms**, and more seriously, **nothing can be detected**.
I suppose the CNNSegmentation model should be modified on TensorRT-8.4.1.5, please help.

**To Reproduce**
1. upgrade  TensorRT to 8.4.1.5
2. run the module perception::lidar::CNNSegmentation

**Expected behavior**
the module **perception::lidar::CNNSegmentation** can detect obstacles smoothly, infer time is about 11ms 

**Screenshots**

**enviroment:**
 - OS: ubuntu 21.10
 - docker: apolloauto/apollo:dev-x86_64-18.04-20210517_1712
 - GPU: NVIDIA RTX A4000
 - CUDA: 11.1
 - TensorRT: 8.4.1.5
 - cudnn: 8.0.4.30

**Comment by liouyx** [comment]
We recommend you not to upgrade, continue to use tensorRT 7.2.1. Upgrading tensorRT may cause other problems.

**Comment by lygbuaa** [comment]
@liouyx Thx for reply, do you have the plan of upgrading TensorRT?

**Comment by liouyx** [comment]
@lygbuaa Thanks for reply. We will add it to requirement lists, and evaluate whether to upgrade. Please remain concern.
