### ISSUE TITLE
ComposeMapCells in ndt map locator

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#14517]
When I try to use ndt locate.  I am really confused about the ComposeMapCells function in [lidar_locator_ndt.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/localization/ndt/ndt_locator/lidar_locator_ndt.cc)。Why we should split a cell into several small areas, but not use the whole cell?  And it seems some small area exceed the cell ranges . so we got negative x y values, which will be filtered next.
And finnally how many cells we really used to do the NDT align? —— It seems the code only one will be used

**Comment by daohu527** [comment]
Simply put, the ndt map is divided into some grids.

when the car is running on the road we take the current car as the center and load a grid within a certain range (for example 10m), that is why ComposeMapCells is needed.


![example](https://user-images.githubusercontent.com/10419854/178489343-27d8cbb3-0128-4586-a3ce-c48293a6a1c5.jpg)
