### ISSUE TITLE
Apollo Development Docker Container

### ISSUE THREAD

**Issue by mshah72** [ApolloAuto/apollo#14512]
On executing the following code, I am getting the below issue
~/apollo$ bash docker/scripts/dev_start.sh

Please help me to resolve it.

![image](https://user-images.githubusercontent.com/99901107/177122745-d798843a-ac26-4e23-b08c-bbb4adf13e74.png)

**Comment by daohu527** [comment]
What is your operating system and Apollo version, please provide the following information run below cmds
```
whoami
id
```

**Comment by mshah72** [comment]
I am using Linux (Ubuntu). I am new to Linux. I am yet to build Apollo. I have just cloned the Apollo repository. I would liķe to use every versions of Apollo. So please also guide me through it.

**Comment by daohu527** [comment]
The above error may be caused by `addgroup`.

To be honest, I have not encountered the above problem, so we have to find the problem step by step, you can try to check the problem from this aspect

**Comment by mshah72** [comment]
I too think it is due to addgroup.

I am checking out with one of my friends. If we get any solution, I will comment it over here.

Thanks a lot @daohu527 for the help.
