### ISSUE TITLE
预测地图相关询问

### ISSUE THREAD

**Issue by detectiveli** [ApolloAuto/apollo#1452]
您好：

我在使用预测模块时，看到函数调取了map_lane.proto中的两个参数，predecessor_id和left_neighbor_forward_lane_id,请问一下这两个参数在地图部分哪里赋值的？

非常感谢！

**Comment by detectiveli** [comment]
find it

**Comment by XiaoHongZuLiao** [comment]
您好！请问这个高精度地图该怎么使用啊，是不是先必须把平台搭起来
