### ISSUE TITLE
All the hardware

### ISSUE THREAD

**Issue by imty1000** [ApolloAuto/apollo#14522]
**Is your feature request related to a problem? Please describe.**
Where can i buy all the hardware with build apollo system, to set with car and test?

**Comment by imty1000** [comment]
Where can i buy all the hardware with build apollo system, to set with car and test?

**Comment by daohu527** [comment]
@imty1000  The current experimental platform is mainly **D-kit**. You can find more details at https://developer.apollo.auto/apollo_d_kit.html
