### ISSUE TITLE
ERROR: no such package '@local_config_cuda//cuda': Repository command failed No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1

### ISSUE THREAD

**Issue by lwbdegit** [ApolloAuto/apollo#14528]
[sti@in-dev-docker:/apollo]$ ./apollo.sh build_opt
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: HEAD-2020-09-21-e79f9d6765
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210914_1336
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[ OK ] Running GPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview: 
[INFO]     USE_GPU: 1  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=gpu --config=opt
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/...
(09:46:38) INFO: Current date is 2022-07-21
(09:46:39) INFO: Repository local_config_cuda instantiated at:
  /apollo/WORKSPACE:6:20: in <toplevel>
  /apollo/tools/workspace.bzl:89:19: in apollo_repositories
Repository rule cuda_configure defined at:
  /apollo/third_party/gpus/cuda_configure.bzl:1243:33: in <toplevel>
(09:46:39) ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 1214, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 913, column 27, in _create_local_cuda_repository
		cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 463, column 21, in _find_libs
		_check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
	File "/apollo/third_party/gpus/cuda_configure.bzl", line 365, column 28, in _check_cuda_libs
		checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
	File "/apollo/tools/platform/common.bzl", line 166, column 13, in execute
		fail(
Error in fail: Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
(09:46:39) WARNING: Download from https://apollo-platform-system.cdn.bcebos.com/archive/6.0/bazel-skylib-1.0.3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: apollo-platform-system.cdn.bcebos.com
(09:46:39) WARNING: Download from https://apollo-platform-system.cdn.bcebos.com/archive/6.0/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: apollo-platform-system.cdn.bcebos.com
(09:46:39) WARNING: Download from https://apollo-platform-system.cdn.bcebos.com/archive/6.0/rules_python-0.0.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: apollo-platform-system.cdn.bcebos.com
(09:46:39) WARNING: Download from https://apollo-platform-system.cdn.bcebos.com/archive/6.0/v1.30.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: apollo-platform-system.cdn.bcebos.com
(09:46:39) WARNING: Download from https://apollo-platform-system.cdn.bcebos.com/archive/6.0/v3.12.3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: apollo-platform-system.cdn.bcebos.com
(09:46:39) ERROR: no such package '@local_config_cuda//cuda': Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
(09:46:39) INFO: Elapsed time: 0.381s
(09:46:39) INFO: 0 processes.
(09:46:39) FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: modules/map/pnc_map ... (5 packages)

[sti@in-dev-docker:/apollo]$ ls /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so
->Tab

libcudart.so          libcudart.so.11.0     libcudart.so.11.1.74  

There is only libcudart.so.11.0 ,not libcudart.so.11.1 needed.
How to do? Thanks!

By the way, my environments:
ubuntu 18.04
cuda 10.2
docker 20.10.17
Nvidia 470 driver

**Comment by lwbdegit** [comment]
[sti@in-dev-docker:/apollo]$ git branch
* (HEAD detached at v6.0.0)
  master

**Comment by daohu527** [comment]
When cuda compiles, it will check whether the same is as expected. You can check it with the following command

```shell
ls /usr/local/cuda-11.1/targets/x86_64-linux/lib/ -ll | grep libcudart
```
