### ISSUE TITLE
 Failed to run ApolloAuto dreamview on Ubuntu 20.04.4 LTS on Windows 10 x86_64 using WSL2

### ISSUE THREAD

**Issue by pbarac00** [ApolloAuto/apollo#14520]
### System information

- **OS Platform and Distribution**:  Ubuntu 20.04.4 LTS on Windows 10 x86_64 using WSL2
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:
- [INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /home/pbarac/apollo
[INFO]     APOLLO_CACHE_DIR: /home/pbarac/apollo/.cache
[INFO]     APOLLO_IN_DOCKER: false
[INFO]     APOLLO_VERSION: master-2022-06-21-9e1edfcc2b
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1
[INFO] Usage: /home/pbarac/apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
* Installed all pre-requisites following https://github.com/ApolloAuto/apollo/blob/master/docs/specs/prerequisite_software_installation_guide.md
* Installed software following https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md
* Done two changes to the bash scripts following this comment https://github.com/ApolloAuto/apollo/issues/14329#issuecomment-1073571799
* Restarted PC for changes to take effect, Run ...cd apollo
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
run ./apollo.sh build, ./apollo.sh build_opt
* Then get following message:
[ OK ] Done building apollo. Enjoy!
* But when I open page where ApolloAuto dreamview should be run I get: This page isn’t working 172.23.47.143 didn’t send any data.
ERR_EMPTY_RESPONSE
### **Can somebody help me solve this or have some alternative solution for running this project on win10?**
 Installing Ubuntu isn't solution for me, because of drivers incompatibility.
### Supporting materials (screenshots, command lines, code/script snippets):

![Screenshot (15)](https://user-images.githubusercontent.com/101290371/179216323-86ccec51-f337-4872-b941-ce75946d54b8.png)

**Comment by daohu527** [comment]
As @orangetcy said in https://github.com/ApolloAuto/apollo/issues/14329

> normally, it should be the same with wsl2.
Maybe you can try this command in apollo dev docker to test if dreamview is working:
curl http://localhost:8888
If get html code as output, maybe dreamview is working then try to solve docker/wsl2 network configuration problem. Otherwise, make sure your dreamview is working.

You can try the above method first.

**Comment by pbarac00** [comment]
Thank you for the tip. It lead me to fixing problem!
