### ISSUE TITLE
Borregas Avenue HD Map Bug - Lanes Missing Predecessor/Successor

### ISSUE THREAD

**Issue by YuqiHuai** [ApolloAuto/apollo#14529]
**Describe the bug**
Lanes defined in Apollo's HD Map has predecessor and successor relation, which is used for routing to generate navigation data.
https://github.com/ApolloAuto/apollo/blob/9e1edfcc2baf102a69c2998ce5118443945d53ac/modules/map/proto/map_lane.proto#L63-L64

However, some lanes in `borregas_ave/base_map.bin` are missing predecessor/successor.
More specifically: 
1. `lane_17` should have `lane_41` as successor, `lane_41` should have `lane_17` as predecessor 
2. `lane_26` should have `lane_48` as successor, `lane_48` should have `lane_26` as predecessor. 

Because of these missing relationship, some routing requests can fail.

The fixed version of Borregas Avenue HD Map can be downloaded at 
[borregas_ave_fix.zip](https://github.com/ApolloAuto/apollo/files/9163203/borregas_ave_fix.zip)

**To Reproduce**
1. Launch Dreamview.
3. Enable SimControl.
4. Enable Planning and Routing modules.
5. Send Routing request from `lane_17` to `lane_7` or `lane_26` to `lane_22`. (See screenshots for illustration)
6. See error in `routing.log.INFO`
```
I0721 15:21:33.791806  3769 navigator.cc:38] Way point:	lane id: lane_26 s: 12.2408 x: 586975 y: 4.1413e+06 length: 52.4317
I0721 15:21:33.791837  3769 navigator.cc:38] Way point:	lane id: lane_22 s: 3.11054 x: 586945 y: 4.14125e+06 length: 15.8343
I0721 15:21:33.792021  3769 a_star_strategy.cc:229] Start A* search algorithm.
E0721 15:21:33.792049  3769 a_star_strategy.cc:323] Failed to find goal lane with id: lane_22
E0721 15:21:33.792060  3769 navigator.cc:187] Failed to search route with waypoint from lane_26 to lane_22
E0721 15:21:33.792089  3769 navigator.cc:80] Failed to find route with request!
E0721 15:21:33.792094  3769 routing.cc:193] Failed to search route with navigator.
```
```
I0721 15:38:03.949762  4914 navigator.cc:38] Way point:	lane id: lane_17 s: 2.03021 x: 587057 y: 4.14163e+06 length: 24.9836
I0721 15:38:03.949795  4914 navigator.cc:38] Way point:	lane id: lane_7 s: 28.8597 x: 587011 y: 4.1416e+06 length: 32.1364
I0721 15:38:03.950064  4914 a_star_strategy.cc:229] Start A* search algorithm.
E0721 15:38:03.950119  4914 a_star_strategy.cc:323] Failed to find goal lane with id: lane_7
E0721 15:38:03.950130  4914 navigator.cc:187] Failed to search route with waypoint from lane_17 to lane_7
E0721 15:38:03.950170  4914 navigator.cc:80] Failed to find route with request!
E0721 15:38:03.950174  4914 routing.cc:193] Failed to search route with navigator.
```

**Expected behavior**
Expect routing to find valid route from `lane_26` to `lane_22`, and from `lane_17` to `lane_7`

**Screenshots**
Left: Lane 26 -> 48 -> 22.
Right: Lane 17 -> 41 -> 7.
![Illustration of the 2 expected routes](https://user-images.githubusercontent.com/34195403/180326512-b27a7314-d7b7-4213-b0ba-acf023aa08ed.png)

Routing success from `lane_26` to `lane_22` after applying the fix.
![Illustration of expected route from 26->48->22](https://user-images.githubusercontent.com/34195403/180326632-97c6f036-6952-4ad7-8318-89b12a76c061.png)

Routing success from `lane_17` to `lane_7` after applying the fix.
![Illustration of expected route from 17-41-7](https://user-images.githubusercontent.com/34195403/180326694-feb44c56-1863-4f1e-8988-68439d163f6d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**

When using `Lane.central_curve` to determine whether 2 lanes are connected, we can see:
1. `lane_17` 's ending coordinate is exactly the same as `lane_41`'s starting coordinate. This should indicate successor/predecessor relationship.
2. `lane_26`'s ending coordinate is **not** the same as `lane_48`'s starting coordinate, but the distance between those coordinates is less than 0.01 (meters I assume): 6.823937919616058e-05. Such difference is small enough to indicate successor/predecessor relation. This might be an accuracy error and I am not sure whether we need to make those 2 coordinates same.

```
==========
lane_17 successor Mismatch
Specified: []
Expected: ['lane_41']
  lane_17.end    (587051.448507309,4141607.2285346985)
  lane_41.start  (587051.448507309,4141607.2285346985)
        diff=0.0
==========
lane_26 successor Mismatch
Specified: []
Expected: ['lane_48']
  lane_26.end    (586962.5288085938,4141261.273864746)
  lane_48.start  (586962.5288391113,4141261.2739257812)
        diff=6.823937919616058e-05
==========
lane_41 predecessor Mismatch
Specified: []
Expected: ['lane_17']
  lane_41.start  (587038.5950508118,4141596.128929138)
  lane_17.end    (587057.8305244446,4141631.3723106384)
        diff=0.0
==========
lane_48 predecessor Mismatch
Specified: []
Expected: ['lane_26']
  lane_48.start  (586948.0023498535,4141252.490509033)
  lane_26.end    (586980.1530151367,4141310.4951782227)
        diff=6.823937919616058e-05
```

**Comment by ntutangyun** [comment]
you should ask this question at the LGSVL Simulator repo.

**Comment by daohu527** [comment]
@YuqiHuai Seems you are correct, the lane is indeed missing the predecessor_id. Glad you can fix it, can we confirm the modification process in detail as they are all binary files

**Comment by YuqiHuai** [comment]
Hi, thanks for confirming!

The process is relatively simple, seems like Github doesn't like uploading python files, so I changed extension to txt.

[map_fixer.txt](https://github.com/ApolloAuto/apollo/files/9174494/map_fixer.txt)

To summarize the process:
- For every lane, use central curve to identify expected predecessor and successor (`get_expected_lane`)
- Since there is a slight error for lane_26 to lane_22 (less than 0.001 meters), I used  `get_distance(p1, p2) < 0.001` to determine whether 2 lanes are supposed to be connected.
- Then, read into protobuf data to see if the specified predecessor/successor matches the expected.
- For every missing relationship, add the lane id to successor_id/predecessor_id (line 86, 96)

Script output ('FIX: ' represents what is changed): 
```
==========
lane_17 successor Mismatch
Specified: []
Expected: ['lane_41']
  lane_17.end    (587051.448507309,4141607.2285346985)
  lane_41.start  (587051.448507309,4141607.2285346985)
        diff=0.0
FIX: added lane_41 to lane_17.successor
==========
lane_26 successor Mismatch
Specified: []
Expected: ['lane_48']
  lane_26.end    (586962.5288085938,4141261.273864746)
  lane_48.start  (586962.5288391113,4141261.2739257812)
        diff=6.823937919616058e-05
FIX: added lane_48 to lane_26.successor
==========
lane_41 predecessor Mismatch
Specified: []
Expected: ['lane_17']
  lane_41.start  (587038.5950508118,4141596.128929138)
  lane_17.end    (587057.8305244446,4141631.3723106384)
        diff=0.0
FIX: added lane_17 to lane_41.predecessor
==========
lane_48 predecessor Mismatch
Specified: []
Expected: ['lane_26']
  lane_48.start  (586948.0023498535,4141252.490509033)
  lane_26.end    (586980.1530151367,4141310.4951782227)
        diff=6.823937919616058e-05
FIX: added lane_26 to lane_48.predecessor
```

**Comment by YuqiHuai** [comment]
Update:
I took a look at the Borregas Avenue HD Map provided by LGSVL at https://github.com/lgsvl/apollo-5.0/tree/simulator/modules/map/data/borregas_ave and found they also have this bug.

**Comment by daohu527** [comment]
So you mean you iterate over the start of each lane and the end of the other to see if they are close enough?

So how do you modify the binary map file and generate others like (routing_map, sim_map)

**Comment by YuqiHuai** [comment]
@daohu527 Yes. I iterate over each lane to check if they are actually connected. I didn't intend to use "close enough" as judgment. I initially used conditions like `start = end`, but since one of the missing relationships in Borregas was less than 0.001 meters off, probably due to an export error again, I had to use "close enough".

To modify the binary map file, I loaded the original one into Python, made a copy and added missing line ids, and exported that copy. You can see it from those lines in the script attached in the earlier comment.
```
# fix
...
  for v in [self.lanes[x].id for x in expected_predecessor if x not in specified_predecessor]:
      print(
          f'FIX: added {v.id} to {fixedlane.id.id}.predecessor')
      nv = fixedlane.predecessor_id.add()
      nv.id = v.id
```

To generate routing_map, sim_map, I followed the instruction here https://github.com/ApolloAuto/apollo/tree/master/modules/map/data
```
dir_name=modules/map/data/demo # example map directory 
./scripts/generate_routing_topo_graph.sh --map_dir ${dir_name}
bazel-bin/modules/map/tools/sim_map_generator --map_dir=${dir_name} --output_dir=${dir_name}
```
