### ISSUE TITLE
规划和决策功能

### ISSUE THREAD

**Issue by zhu61577542** [ApolloAuto/apollo#14526]
请问apollo中的路线规划决策功能只能使用c++实现么？
如果使用python可能对车辆的控制功能进行开发么？

**Comment by zhu61577542** [comment]
对车辆行驶的控制都在planning中处理的么？

**Comment by SteveCruise** [comment]
超级想买apollo rt6，什么时候开卖啊

**Comment by daohu527** [comment]
@zhu61577542 

> 请问apollo中的路线规划决策功能只能使用c++实现么？

是的最好使用c++，也可以使用matlab开发然后生成c++

> 如果使用python可能对车辆的控制功能进行开发么？

当然可以，语言只是工具，但是python的效率偏低，用于验证可能更好

> 对车辆行驶的控制都在planning中处理的么？

规划模块是生成轨迹，而控制模块则是通过油门、刹车和方向盘来保证车辆按照预定的轨迹形式，所以严格来说对车辆的控制包括规划和控制2个模块。

**Comment by daohu527** [comment]
@SteveCruise 
> 超级想买apollo rt6，什么时候开卖啊

具体时间我不知道，但咱是不打算考驾照了？
