### ISSUE TITLE
distance approach ipopt cuda report segmentation fault

### ISSUE THREAD

**Issue by armme41** [ApolloAuto/apollo#14536]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
I run the parking code, and use distance approach ipopt cuda interface.
**config:**
`distance_approach_mode: DISTANCE_APPROACH_IPOPT_CUDA`
The distance approach problem fails with segmentation fault.

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2022-07-26 11-00-03](https://user-images.githubusercontent.com/22172840/180914860-f40a8e6b-8bdf-4a57-81f1-f6c53ad679a5.png)

### nvidia-smi output
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA Quadro R...  On   | 00000000:01:00.0  On |                  Off |
| 34%   33C    P8    20W / 230W |    629MiB / 16116MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1759      G   /usr/lib/xorg/Xorg                500MiB |
|    0   N/A  N/A      2302      G   /usr/bin/gnome-shell               68MiB |
|    0   N/A  N/A      4169      G   ...AAAAAAAAA= --shared-files       14MiB |
|    0   N/A  N/A     76421      G   ...393890526685167208,131072       33MiB |
|    0   N/A  N/A   2689706      G   .../ros/noetic/lib/rviz/rviz        8MiB |
+-----------------------------------------------------------------------------+

**Comment by daohu527** [comment]
Can you provide more information, check the coredump, there is no segmentfault from the log
