### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by a1wj1** [ApolloAuto/apollo#14538]
你好，我想请问一下，我们可以使用Apollo里面的规划部分的一些代码移植到我们自己的ros平台，并进行收益吗？想问一下开源代码是否有代码移植的限制？

**Comment by daohu527** [comment]
apollo uses apache license 2.0, which means you can modify or use it commercially. But to **add a copyright notice** in the file you use, you can also add your own copyright notice in the file.

For more details, please refer to apache license 2.0
