### ISSUE TITLE
pulling failed

### ISSUE THREAD

**Issue by EMBALCI** [ApolloAuto/apollo#1453]
emre@emre-Latitude-E5520:~/apollo-platform/apollo$ bash docker/scripts/dev_start.sh
[sudo] password for emre: 
/apollo/data/core/core_%e.%p
Type 'y' or 'Y' to pull docker image from China mirror or any other key from US mirror.
y
dev-x86_64-20171122_1537: Pulling from apolloauto/apollo
cb56c90f0b30: Pulling fs layer 
0acc551e5716: Pulling fs layer 
8956dcd35143: Pulling fs layer 
908242721214: Waiting 
b44ff14dd3bb: Waiting 
4e68297aef7a: Waiting 
f2e60cbbc46b: Waiting 
4def827f3388: Pulling fs layer 
d7024597d4d3: Pulling fs layer 
886213b9c3ba: Pulling fs layer 
4def827f3388: Waiting 
d7024597d4d3: Waiting 
d505646e6e5b: Pulling fs layer 
886213b9c3ba: Waiting 
8f0fa8c34222: Waiting 
bb8e16126598: Pulling fs layer 
f3b7c5d69675: Waiting 
1aedc3a0410b: Waiting 
33c030e7093a: Waiting 
da48ec85ed49: Pulling fs layer 
24852ac95ef0: Pulling fs layer 
fe4e65935e53: Pulling fs layer 
4779c4c9cb2e: Pulling fs layer 
27f6eba23a1a: Waiting 
15ab83019eb2: Waiting 
199e339073f8: Waiting 
3ae09dace98d: Waiting 
d09a647016dd: Waiting 
a7cb11a41e97: Waiting 
3e7686bdef0b: Waiting 
78198803f767: Pulling fs layer 
78198803f767: Waiting 
74c48b5e54a2: Pulling fs layer 
9b76be8176e0: Waiting 
ce47e44da8ce: Pulling fs layer 
74c48b5e54a2: Waiting 
200abc1adefd: Waiting 
9b76be8176e0: Download complete 
efc4bc9b4119: Download complete 
4e46d20fcf03: Download complete 
2b448e40506a: Download complete 
d12c8cf5699d: Download complete 
f2ba7ad4cfc7: Download complete 
351ecb254b60: Download complete 
dd1b1bafa413: Download complete 
8a5e2bea418d: Download complete 
7e610bf57646: Download complete 
32a374005d6c: Download complete 
1307670d704c: Download complete 
e43cb256c38c: Download complete 
353dcb25c39c: Downloading [=====================================>             ]  333.9MB/447MB
52e15f6717a2: Download complete 
a1d13a7f5398: Download complete 
1208b862d4c9: Download complete 
21f3dfc7fc87: Download complete 
85ae4b0dd353: Download complete 
042b5ae882da: Download complete 
707d68e96343: Download complete 
268269a5caca: Download complete 
45dfbd87c718: Download complete 
94f5779d4af0: Download complete 
82ccbf80d7fa: Download complete 
86315e78db66: Download complete 
06bc6911f9d4: Download complete 
26637a5d7bcf: Download complete 
2b8610ad644b: Download complete 
e07c96625704: Download complete 
8c7b2e11d4bd: Download complete 
e19a886efafb: Download complete 
76a96bcddfb9: Download complete 
eca8c00b150c: Download complete 
cebb627b586b: Download complete 
18107c0ddc3f: Download complete 
bf89e5c82131: Download complete 
08868fe92128: Downloading [=================================================> ]  117.6MB/119.9MB
7475105e49a7: Download complete 
b648e96d3179: Downloading 
dial tcp 106.14.228.109:443: i/o timeout
[sudo] password for emre: 
Sorry, try again.
[sudo] password for emre: 
modprobe: FATAL: Module nvidia not found.
modprobe: FATAL: Module nvidia-uvm not found.
[WARNING] Failed to find device with pattern "ttyUSB*" ...
[ OK ] Found device: /dev/ttyS31.
[ OK ] Found device: /dev/ttyS30.
[ OK ] Found device: /dev/ttyS29.
[ OK ] Found device: /dev/ttyS28.
[ OK ] Found device: /dev/ttyS27.
[ OK ] Found device: /dev/ttyS26.
[ OK ] Found device: /dev/ttyS25.
[ OK ] Found device: /dev/ttyS24.
[ OK ] Found device: /dev/ttyS23.
[ OK ] Found device: /dev/ttyS22.
[ OK ] Found device: /dev/ttyS21.
[ OK ] Found device: /dev/ttyS20.
[ OK ] Found device: /dev/ttyS19.
[ OK ] Found device: /dev/ttyS18.
[ OK ] Found device: /dev/ttyS17.
[ OK ] Found device: /dev/ttyS16.
[ OK ] Found device: /dev/ttyS15.
[ OK ] Found device: /dev/ttyS14.
[ OK ] Found device: /dev/ttyS13.
[ OK ] Found device: /dev/ttyS12.
[ OK ] Found device: /dev/ttyS11.
[ OK ] Found device: /dev/ttyS10.
[ OK ] Found device: /dev/ttyS9.
[ OK ] Found device: /dev/ttyS8.
[ OK ] Found device: /dev/ttyS7.
[ OK ] Found device: /dev/ttyS6.
[ OK ] Found device: /dev/ttyS5.
[ OK ] Found device: /dev/ttyS4.
[ OK ] Found device: /dev/ttyS3.
[ OK ] Found device: /dev/ttyS2.
[ OK ] Found device: /dev/ttyS1.
[ OK ] Found device: /dev/ttyS0.
[ OK ] Found device: /dev/can2.
[ OK ] Found device: /dev/can1.
[ OK ] Found device: /dev/can0.
[ OK ] Found device: /dev/ram15.
[ OK ] Found device: /dev/ram14.
[ OK ] Found device: /dev/ram13.
[ OK ] Found device: /dev/ram12.
[ OK ] Found device: /dev/ram11.
[ OK ] Found device: /dev/ram10.
[ OK ] Found device: /dev/ram9.
[ OK ] Found device: /dev/ram8.
[ OK ] Found device: /dev/ram7.
[ OK ] Found device: /dev/ram6.
[ OK ] Found device: /dev/ram5.
[ OK ] Found device: /dev/ram4.
[ OK ] Found device: /dev/ram3.
[ OK ] Found device: /dev/ram2.
[ OK ] Found device: /dev/ram1.
[ OK ] Found device: /dev/ram0.
[ OK ] Found device: /dev/loop7.
[ OK ] Found device: /dev/loop6.
[ OK ] Found device: /dev/loop5.
[ OK ] Found device: /dev/loop4.
[ OK ] Found device: /dev/loop3.
[ OK ] Found device: /dev/loop2.
[ OK ] Found device: /dev/loop1.
[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop-control.
[ OK ] Found device: /dev/nvidia-uvm-tools.
[ OK ] Found device: /dev/nvidia-uvm.
[ OK ] Found device: /dev/nvidiactl.
[ OK ] Found device: /dev/nvidia0.
[ OK ] Found device: /dev/video0.
Unable to find image 'apolloauto/apollo:dev-x86_64-20171122_1537' locally
dev-x86_64-20171122_1537: Pulling from apolloauto/apollo
cb56c90f0b30: Pulling fs layer 
0acc551e5716: Pulling fs layer 
8956dcd35143: Pulling fs layer 
908242721214: Waiting 
b44ff14dd3bb: Waiting 
4e68297aef7a: Waiting 
f2e60cbbc46b: Waiting 
4def827f3388: Waiting 
d7024597d4d3: Waiting 
886213b9c3ba: Pulling fs layer 
b1ac6ddbc6b7: Waiting 
6d28c630a322: Pulling fs layer 
d505646e6e5b: Waiting 
7968bcb3836a: Waiting 
8f0fa8c34222: Waiting 
bb8e16126598: Waiting 
f3b7c5d69675: Waiting 
1aedc3a0410b: Pulling fs layer 
33c030e7093a: Waiting 
da48ec85ed49: Pulling fs layer 
24852ac95ef0: Waiting 
fe4e65935e53: Waiting 
4779c4c9cb2e: Waiting 
27f6eba23a1a: Waiting 
15ab83019eb2: Waiting 
199e339073f8: Waiting 
3ae09dace98d: Waiting 
da48ec85ed49: Waiting 
a7cb11a41e97: Waiting 
3e7686bdef0b: Waiting 
78198803f767: Waiting 
9b76be8176e0: Waiting 
74c48b5e54a2: Waiting 
200abc1adefd: Waiting 
1aedc3a0410b: Waiting 
8e863c5dfee2: Waiting 
85b9d775f6a6: Waiting 
6d28c630a322: Downloading 
efc4bc9b4119: Waiting 
4e46d20fcf03: Waiting 
2b448e40506a: Waiting 
d12c8cf5699d: Waiting 
f2ba7ad4cfc7: Waiting 
351ecb254b60: Waiting 
dd1b1bafa413: Waiting 
8a5e2bea418d: Waiting 
7e610bf57646: Waiting 
32a374005d6c: Waiting 
1307670d704c: Waiting 
e43cb256c38c: Waiting 
353dcb25c39c: Waiting 
52e15f6717a2: Waiting 
a1d13a7f5398: Waiting 
1208b862d4c9: Waiting 
21f3dfc7fc87: Waiting 
85ae4b0dd353: Waiting 
042b5ae882da: Waiting 
707d68e96343: Waiting 
268269a5caca: Waiting 
45dfbd87c718: Waiting 
94f5779d4af0: Waiting 
82ccbf80d7fa: Waiting 
86315e78db66: Waiting 
06bc6911f9d4: Waiting 
26637a5d7bcf: Waiting 
2b8610ad644b: Waiting 
e07c96625704: Waiting 
8c7b2e11d4bd: Waiting 
e19a886efafb: Waiting 
76a96bcddfb9: Waiting 
eca8c00b150c: Waiting 
cebb627b586b: Waiting 
18107c0ddc3f: Waiting 
bf89e5c82131: Waiting 
08868fe92128: Waiting 
7475105e49a7: Waiting 
b648e96d3179: Waiting 
docker: dial tcp: lookup auth.docker.io on 127.0.1.1:53: read udp 127.0.0.1:50764->127.0.1.1:53: i/o timeout.
See 'docker run --help'.
Error response from daemon: No such container: apollo_dev

**Comment by gengqx** [comment]
Maybe You download it while using VPN，If you type y，it means that you download the image from China Server，So Do not Use  VPN，it would be very fast
