### ISSUE TITLE
Is there a scene setting button that the car hitting obstacles?

### ISSUE THREAD

**Issue by 28753t03** [ApolloAuto/apollo#14535]
### 
In the simulation environment (free version), where is the scene setting button that the car will not stop and hit obstacles?_
1. Is there a ready-made scene setting button or need the developer write addtional code?
2. if it need the developer write addtional code, where's the conresponding interface from the apollo source code?_

**Comment by daohu527** [comment]
> Is there a ready-made scene setting button or need the developer write addtional code?

no, you need to develop by yourself

> if it need the developer write addtional code, where's the conresponding interface from the apollo source code?

Actually, I don't quite understand `the car hitting obstacles`, the code of dreamview is in `modules/dreamview`

**Comment by 28753t03** [comment]
> > Is there a ready-made scene setting button or need the developer write addtional code?
> 
> no, you need to develop by yourself
> 
> > if it need the developer write addtional code, where's the conresponding interface from the apollo source code?
> 
> Actually, I don't quite understand `the car hitting obstacles`, the code of dreamview is in `modules/dreamview`

Simulate the scene tha the car's sensor is broken and the car will hit the obstacle instead of  detecting the obstacle and then crash into it.

**Comment by daohu527** [comment]
In short, you can achieve your effect by sending a fake obstacle to display on the dreamview, but this has no physics engine, so it traverses past

Note that the planning module also accepts perception topics, so you need to publish perception messages for another topic, You can modify the topic of the following readers and publish a mock obstacle
https://github.com/ApolloAuto/apollo/blob/6db2a1bc66ca3d564c18545c8ff8ebd0762249e7/modules/dreamview/backend/simulation_world/simulation_world_service.cc#L381

**Comment by 28753t03** [comment]
> In short, you can achieve your effect by sending a fake obstacle to display on the dreamview, but this has no physics engine, so it traverses past
> 
> Note that the planning module also accepts perception topics, so you need to publish perception messages for another topic, You can modify the topic of the following readers and publish a mock obstacle
> 
> https://github.com/ApolloAuto/apollo/blob/6db2a1bc66ca3d564c18545c8ff8ebd0762249e7/modules/dreamview/backend/simulation_world/simulation_world_service.cc#L381
Thanks for your patiently reply. It sounds great.
Howerver, I want another way to simulate the adverarial attack on the sensor so that the sensor is conntrolled by the hacker. The obstacle is produced by the hacker to misled the  driving sensor cannot detect the obstacle instead of a simple fake obstacle.

**Comment by daohu527** [comment]
I recommend you to use an simulator to fake the sensor, like lgsvl or carla

**Comment by 28753t03** [comment]
> I recommend you to use an simulator to fake the sensor, like lgsvl or carla

How does the apollo combine with the simulator like lgsvl or carla?
