### ISSUE TITLE
Is planning module deterministic?

### ISSUE THREAD

**Issue by YuqiHuai** [ApolloAuto/apollo#14533]
Hi!

I want to ask about **whether the output of the planning module is deterministic: given the same input, we always get the same output**.

I found @jmtao 's comment at https://github.com/ApolloAuto/apollo/issues/11268#issuecomment-646842161 
> We use these test cases to make sure planning's output is fixed and determined based on the same set of input.

and I noticed some of those tests are actually disabled since 2019 https://github.com/ApolloAuto/apollo/commit/d524204e82927c384b555004f01c5293504d4de8
https://github.com/ApolloAuto/apollo/blob/986fe474272413fca0621b245d1c7aa6a1e75316/modules/planning/integration_tests/BUILD#L26

I ran the only enabled test `sunnyvale_big_loop_test` for a couple times and had same results. I could not run other tests because I do not know how to solve those undefined references. 

**Questions**:
1. Is the output of planning module supposed to be deterministic?
2. In the current version, is planning module deterministic?
3. Will those disabled tests be fixed and enabled sometime soon?

**Additional Question**:
1. How can I check coverage information of a test case? I tried 
```bazel coverage --instrument_test_targets --combined_report=lcov //modules/planning/integration_tests:sunnyvale_big_loop_test``` 
and got 
`error: cannot open bazel-out/k8-fastbuild/bin/modules/planning/lattice/trajectory_generation/_objs/piecewise_braking_trajectory_generator/piecewise_braking_trajectory_generator.pic.gcno`
I am not very familiar with Bazel and I am not sure about what I am missing.

**Comment by qwetqwe** [comment]
1. Some parameters are related with time, like stitching trajectory. Even if input message is same, but in different time planning start point is different.
2. No. the reason is like before.
3. We do not have this plan now. You can integrate test by Sim Control simulation.

**Comment by YuqiHuai** [comment]
@qwetqwe Hi! Thanks for responding. I guess from your answer 1, planning is non-deterministic.

Is there additional resource I can use to understand how to get coverage report for the planning module given a test?
