### ISSUE TITLE
core-js@3.24.1 removed features folder and breaks apollo client:codegen

### ISSUE THREAD

**Issue by xinghul** [ApolloAuto/apollo#14546]
**Describe the bug**
As described by the title, here's the error when I was trying to run `apollo client:codegen`:

```
Error: Cannot find module 'core-js/features/array/flat'
```

Install core-js@3.24.0 fixes the issue, but I think the package should not have `core-js@^3.0.1` as deps.

**Comment by daohu527** [comment]
I'm afraid you're asking the wrong repository. [Apollo](http://apollo.auto/) is a high performance, flexible architecture which accelerates the development, testing, and deployment of Autonomous Vehicles.

May be you want to know https://github.com/apollographql

**Comment by xinghul** [comment]
@daohu527 oh sorry my mistake, closing this.
