### ISSUE TITLE
cyber module support record same timestamp and msg from origin cyber log

### ISSUE THREAD

**Issue by guqiangwei** [ApolloAuto/apollo#14547]
**Is your feature request related to a problem? Please describe.**
not found

**Describe the solution you'd like**
Can cyber_recorder tools support users record new msg with the same timestamp from origin cyber log.
Now I can only record msg with system timestamp

**Describe alternatives you've considered**
Yes,I can write a new cyber msg with 'create_writer' and set timestamp which I want. 
And I think a simple interface is better.

**Comment by daohu527** [comment]
cyber already support a mode name `MODE_MOCK`, which can modify the time. 

But it is fixed after setting, unless you go to set it again to a new value, I don't know if this meets your requirements

**Comment by guqiangwei** [comment]
MODE_MOCK is not enough I think >=<
May I have a simple command such as "cyber_recorder record -* " to  record new msg with the same timestamp?
Thank you for your suggestion。

**Comment by daohu527** [comment]
> new msg with the same timestamp

I don't quite understand, why the timestamp of the message is the same, which doesn't exist in real environment. cyber_record records the time when the message was sent. 

If you want to read the message from the file and write it as a record file. you can use `apollo::cyber::record::Recorder`c++ interface, or you can use a python tool [cyber_record](https://github.com/daohu527/cyber_record)

**Comment by guqiangwei** [comment]
> If you want to read the message from the file and write it as a record file. you can use `apollo::cyber::record::Recorder`c++ interface, or you can use a python tool [cyber_record](https://github.com/daohu527/cyber_record)

Actually, I achieve this function in this way. I suggess that 'Cyber Module' would provide a simple tool to achieve this.


> I don't quite understand, why the timestamp of the message is the same, which doesn't exist in real environment. cyber_record records the time when the message was sent.

when transcribe a small record file from a large record file

And thank you for your suggestion

**Comment by daohu527** [comment]
You can use above tools to convert record files. Currently, the command-line tool `cyber_recorder` is not so flexible. Do you mean to merge the functionality of the edit record file into the mainline?

**Comment by guqiangwei** [comment]
> Do you mean to merge the functionality of the edit record file into the mainline?

Sorry, I'm not ready to submit 'pull request'.

> apollo::cyber::record::Recorderc++ interface, or you can use a python tool [cyber_record](https://github.com/daohu527/cyber_record)

And this Issue can be closed, problem has been solved in this way

**Comment by daohu527** [comment]
I don't think splitting the file by publishing and then subscribing is a good idea. You can edit the file directly!!!

apollo::cyber::record::Recorder c++ interface can meet our needs, maybe we need to add more editing interfaces?
