### ISSUE TITLE
Parking boundary bug

### ISSUE THREAD

**Issue by armme41** [ApolloAuto/apollo#14540]
https://github.com/ApolloAuto/apollo/blob/0e3f5265ce89dae91789aad6cb6ab590abb97fd9/modules/planning/tasks/deciders/open_space_decider/open_space_roi_decider.cc#L1308

When parking space on the left of ADC, parking boundary is like this:
![Screenshot from 2022-07-27 20-49-25](https://user-images.githubusercontent.com/22172840/181251254-ad2fcd84-8642-499f-9169-ee8ed75f837d.png)

Found that
```
// reinsert the initial point to the back to from closed loop
boundary_points.push_back(right_lane_boundary.front());
```
should be
```
// insert the initial point of left lane boundary to the back to form closed loop
boundary_points.push_back(left_lane_boundary.front());
```

**Comment by chenxiaoying21** [comment]
I think the vector "boundary_points" starts with the first point of "right_lane_boundary", so letting it end with the same point seems reasonable to form a closed loop.

**Comment by chenxiaoying21** [comment]
Close this issue due to long time no reply.
