### ISSUE TITLE
怎么在apollo上部署新的检测模型？比如yolov5的onnx模型如何部署到apollo上去？是否有相关的资料参考

### ISSUE THREAD

**Issue by zmmhz** [ApolloAuto/apollo#14548]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- 怎么在apollo上部署新的检测模型？比如yolov5的onnx模型如何部署到apollo上去？是否有相关的资料参考

**Comment by SeasoulChris** [comment]
你好，目前添加新的检测模型，需要用户添加一个新的Detector，在Detector中进行调用模型对应的推理框架及前处理后处理，可以参考  https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_camera_detector_algorithm.md
