### ISSUE TITLE
distance_approach_problem

### ISSUE THREAD

**Issue by zhangjian-v** [ApolloAuto/apollo#14541]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary) source:
- **Apollo version (3.5, 5.0, 5.5, 6.0) 7.0:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- when run the parking code, the Hybrid A star's result is correct but OptimizeTNLP(problem) (in distance_approach_problem.cc) return "Infeasible_Problem_Detected", how can i solve it?

**Comment by chenxiaoying21** [comment]
DistanceApproachProblem is used to smooth the hybrid A result. You can check the constraint of the problem to see if they are not appropriate.
