### ISSUE TITLE
Pointpillars detection not working properly before the update #13189"Perception:update pointpillars network and models"

### ISSUE THREAD

**Issue by bismack163** [ApolloAuto/apollo#14559]
I am trying dreamview lidar perception practice on several Apollo version builds following this guide [使用Dreamview调试Apollo激光雷达感知实践](https://developer.apollo.auto/document_cn.html?target=/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/)
In this change #13189, pointpillar detection removes onnx models and use 5 libtorch models instead.

My test found that after this change [#13189](https://github.com/ApolloAuto/apollo/pull/13189), the dreamview lidar perception runs normally and obstacles shown in the dreamview. But before this change #13189, there is no obstacles shown in the dreamview. From cyber_monitor, channel /apollo/perception/obstacles output continuously at some rate but the message is empty (no obstacles). Looks like the lidar perception is running "normally" but no obstacles detected.

Add debug print in point_pilliars_detection.cc to print out the objects detected and found that:
1. in the good case (those after change #13189), 10 ~ 20+ objects detected in each time with type of CAR, BUS, etc
2. in the NG case (those before #13189), most of the time 0 object detected, occasionally there are 1~2 objected with type of UNKNOWN or CAR

Also run the test suite of pointpillars detection, and the test result shows PASS for both cases. The output objects are somewhat different but looks acceptable. (after #13189 it detected 17 objects in the data while before it detected 16 objects)

1. Is this an expected/known result for lidar perception before the change #13189?
2. Is this [lidar perception practice guide](https://developer.apollo.auto/document_cn.html?target=/Apollo-Homepage-Document/Apollo_Doc_CN_6_0/) (and the data record used in it) suitable for the versions before this change #13189? If not can you suggest the correct guide and data record for test?
3. Any other steps or configuration I missed here?

**Comment by daohu527** [comment]
@bismack163 we'll check it, it needs more time. We are going to upgrade the perception module, if you don't mind, I suggest you adopt `CenterPoint` and have a try. You can find detail in [docs](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README_paddle3D_CN.md)

**Comment by liouyx** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
