### ISSUE TITLE
用Rust重写

### ISSUE THREAD

**Issue by cnmade** [ApolloAuto/apollo#14558]
虽然CPP作为工业性编程语言非常通用。但是但是，指针，内存安全，是非常大的问题，随处可见。自动驾驶系统，是不能容忍崩溃，或者意外的。你的车正在高速140km/h速率行驶，系统突然崩了，内存溢出。。。
GG思密达，车子跟人一起升天。

建议用Rust重写，至少内存安全这块能控制和收敛一下。
否则你不知道哪里的指针没回收。。。内存收不住。。

**Comment by daohu527** [comment]
谢谢你的建议，用Rust可能是个好主意，重构整个代码面临很大的工作，特别是一些第三方库，如果可以你可以尝试重构一部分代码，目前我们还是会尽可能的用c++做的更好。

**Comment by cnmade** [comment]
了解思密达。

**Comment by heliping** [comment]
用rust封装几个接口也好啊。

**Comment by lurenhua0122** [comment]
对的，一个模块一个模块做

**Comment by felixf4xu** [comment]
It's better to use rust if you are going to start a new project **completely**.
