### ISSUE TITLE
About ADCtrajectory heading angle in r7.0

### ISSUE THREAD

**Issue by zhuiyuehun** [ApolloAuto/apollo#14553]
The heading angle in the trajectory sent by the planning module uses the angle of the vehicle axis or the direction angle of the vehicle speed？

### System information

- **OS Platform and Distribution ( Ubuntu 20.04)**:
- **Apollo installed from (source)**:
- **Apollo version (7.0)**:

**Comment by qwetqwe** [comment]
It represents vehicle axis angle
