### ISSUE TITLE
Single-module compiling

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#14566]
After entering the Docker image on Apollo, If I will select specific single-module to compile, such as planning or control,Is there such a script or detailed command? Thank you!

**Comment by yumianhuli2** [comment]
> After entering the Docker image on Apollo, If I will select specific single-module to compile, such as planning or control,Is there such a script or detailed command? Thank you!

**Comment by daohu527** [comment]
You can try
```
./apollo.sh build planning 
# or
./apollo.sh build control 
```

**Comment by yumianhuli2** [comment]
> You can try
> 
> ```
> ./apollo.sh build planning 
> # or
> ./apollo.sh build control 
> ```

Thanks!
