### ISSUE TITLE
Tutorial for Apollo on Petalinux

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#14564]
Is there a tutorial or any resources for Apollo on Petalinux？
Please post a link if exists,Thank you very much!

**Comment by daohu527** [comment]
No, there is currently no docs about Petalinux, but feedback is welcome!

The current system tested by apollo is ubuntu, others may be OK, but there may be some problems that need to be dealt with by yourself

**Comment by yumianhuli2** [comment]
> @yumianhuli2 No, there is currently no docs about Petalinux, but feedback is welcome!
> 
> The current system tested by apollo is ubuntu, others may be OK, but there may be some problems that need to be dealt with by yourself

ok，thank you
