### ISSUE TITLE
Question about velocity of ADC when stopped

### ISSUE THREAD

**Issue by tuanngokien** [ApolloAuto/apollo#14565]
### System information

- **OS Platform and Distribution:** Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0 (master branch - commit #14556)

### Context:
When analyzing CyberRT record of a specific scenario, sometimes even when seeing ADC completely stopped in stop line (with STOP fence) does not mean that the corresponding `linear_velocity` extracted from messages in channel `/apollo/localization/pose` would be `0.0` (the `linear_velocity` values are decreased really small but never be absolute `0.0`). 

Meanwhile, Apollo source code has several code snippets to check if ADC is completely stopped. Actually, they do not compare the `linear_velocity` with `0.0`, instead comparing it with a configured threshold `max_adc_stop_speed` (as `0.2` for the car model Lincoln MKZ).

https://github.com/ApolloAuto/apollo/blob/b09259f8be3ae85b3b3471d45d301175d46c2a8f/modules/planning/scenarios/stop_sign/unprotected/stage_pre_stop.cc#L233-L240

### Questions

1. Why is it sometimes ADC's `linear_velocity` cannot reach absolute `0.0` at a stop sign, as it is supposed to be?
2. What is `max_adc_stop_speed` and how is it considered for checking if ADC is stopped or not?
3. Is that somehow related to the `rolling stop` mechanism? Does Apollo decide in each specific scenario to have a complete stop or a rolling stop? 

### Supporting materials (screenshots, command lines, code/script snippets):
**Demo** CyberRT Record: https://drive.google.com/file/d/1noE5XO8GPisnOMoaYH_820OGLckKwajC/view

**Comment by qwetqwe** [comment]
vehicle speed from wheel speed sensor may have error
