### ISSUE TITLE
开放平台：3.2.16 分页获取配置项接口，报"Request method 'GET' not supported"

### ISSUE THREAD

**Issue by Botreechan** [ApolloAuto/apollo#14560]
**Describe the bug**
3.2.16 分页获取配置项接口，报"Request method 'GET' not supported"

**To Reproduce**
文档地址：https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_3216-%e5%88%86%e9%a1%b5%e8%8e%b7%e5%8f%96%e9%85%8d%e7%bd%ae%e9%a1%b9%e6%8e%a5%e5%8f%a3

**Screenshots**
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/23278447/184080834-8f36e306-bafe-4123-b4ae-1d0997c42899.png">

**Comment by daohu527** [comment]
[Apollo](http://apollo.auto/) is a high performance, flexible architecture which accelerates the development, testing, and deployment of Autonomous Vehicles.

You should ask in https://www.apolloconfig.com/#/en/README but not here
