### ISSUE TITLE
Adding New Controller Error -> "controller" is not defined 

### ISSUE THREAD

**Issue by AkshayDesaiSDCE** [ApolloAuto/apollo#14569]
I followed the steps given in the docs->howto-> how_to_add_a_new_control_algorithm.md to add a new controller. 

I still however get the following error message. 
![Error_message](https://user-images.githubusercontent.com/39247736/186731694-2d338379-5389-4cbf-bc8e-56ec1a825f50.png)

I am not sure how to proceed on debugging this error. 

Any suggestions in this regard would be super helpful. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
The error prompts that the configuration file `LonMPCControllerConf` is missing. If this is defined by yourself, you need to create this configuration
