### ISSUE TITLE
Lattice算法进行横向轨迹规划时如何保证能达到停车点

### ISSUE THREAD

**Issue by breezygogo** [ApolloAuto/apollo#14572]
您好，我参考的是最新的apollo lattice算法的代码，想问一下，我现在知道的是lattice算法在做横向规划的时候，有两种方式，一个是撒点采样然后5次多项式，另一个是用piecewise jerk 二次规划。想问一下如果有停车点这两种方法分别是用什么方式使得横向规划对应的轨迹可以保证能到达停车点。

**Comment by qwetqwe** [comment]
建议您采用优化方法进行横向规划，撒点采样采样点数量较少无法准确采样到停车点。优化方法可以在终点位置l施加约束
