### ISSUE TITLE
如何制作安装包

### ISSUE THREAD

**Issue by liujiayu2** [ApolloAuto/apollo#14579]
我看到官网有提供安装包，这个是比开发环境体积小很多，怎么制作有相关教程吗？

**Comment by dreamholy** [comment]
包的管理方式还正在开发中，目前是测试试用阶段，会逐步放出来各个模块的包。
暂时还没有开放包的制作能力，请问能分享下您的具体需求场景是什么吗？谢谢~

**Comment by liujiayu2** [comment]
请教一下，./apollo.sh可以跟很多参数，比如./apollo build。有一个./apollo release 这个是干什么用的呢？

**Comment by liujiayu2** [comment]
> 包的管理方式还正在开发中，目前是测试试用阶段，会逐步放出来各个模块的包。 暂时还没有开放包的制作能力，请问能分享下您的具体需求场景是什么吗？谢谢~

请教一下，./apollo.sh可以跟很多参数，比如./apollo build。有一个./apollo release 这个是干什么用的呢？他生成了一个output文件夹，这个文件夹是用来做什么的呢？
