### ISSUE TITLE
msf_local_map_creator Does not create a localization map

### ISSUE THREAD

**Issue by Ladanovasv** [ApolloAuto/apollo#14581]
### System information

- **OS Platform and Distribution Linux Ubuntu 20.04**:
- **Apollo installed from source**:
- **Apollo version 7.0**:
- **Output of `master` branch**:

I want to create a local_map for online_vizualizator.
![image](https://user-images.githubusercontent.com/47398458/188660623-f19b89e8-aea4-4fab-94ed-1eab0cba4232.png)
Throws the following error
![image](https://user-images.githubusercontent.com/47398458/188665970-3964da73-f7a6-4945-b4a9-c509a5bad1cf.png)
How else can you create a lidar map for apollo?

**Comment by daohu527** [comment]
Are you trying to create a point cloud map?

**Comment by Ladanovasv** [comment]
Yes, for online_vizualizator and ndt_localization

**Comment by daohu527** [comment]
While I'm not sure, there's a difference, location maps don't currently offer visualizations. You can try any slam algorithm to make a visual map.

I wrote a simple tool use [ndt](https://github.com/daohu527/ndt_mapping), it may be optimized in the near future

**Comment by Ladanovasv** [comment]
@daohu527 Thanks, can you give instructions on how to run it NDT localization with a map built by your algorithm?

**Comment by daohu527** [comment]
You can follow the readme first
