### ISSUE TITLE
How to connect Apollo with Carla?

### ISSUE THREAD

**Issue by AminoACID123** [ApolloAuto/apollo#14588]
Hi, I am new to Apollo and I want to use Carla as the simulator to run Apollo. Is there any tutorial I can get start with?

**Comment by CesarLiu** [comment]
https://github.com/AuroAi/carla_apollo_bridge, @daohu527 may refer to this one.
@AminoACID123 when you have time, please try it out. I planned to bridge apollo 5.5 to the latest carla but haven't yet time to try it out.

**Comment by daohu527** [comment]
@CesarLiu Thanks for your attention, actually I'm going to write a carla_bridge based on https://github.com/carla-simulator/ros-bridge because we already have `pycyber`.

we can use carla.client to communicate with carla and use pycyber to communicate with apollo
