### ISSUE TITLE
./apollo.sh build  error 22

### ISSUE THREAD

**Issue by zhangbowei** [ApolloAuto/apollo#14586]
root@in-dev-docker:/apollo# ./apollo.sh build
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: @non-git
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20210914_1336
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=0 USE_GPU_TARGET=0
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[WARNING] nvidia-smi not found. CPU will be used.
[ OK ] Running CPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview:
[INFO]     USE_GPU: 0  [ 0 for CPU, 1 for GPU ]
[INFO]     Bazel Options: --config=cpu
[INFO]     Build Targets: //modules/... union //cyber/...
[INFO]     Disabled:      except //modules/drivers/canbus/can_client/esd/... except //modules/perception/... except //modules/planning/open_space/trajectory_smoother:planning_block except //modules/map/pnc_map:cuda_pnc_util except //modules/map/pnc_map:cuda_util_test
WARNING: Output base '/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32' is on NFS. This may lead to surprising failures and undetermined behavior.
Extracting Bazel installation...
FATAL: failed to sync '/apollo/.cache/bazel/install/a09e0625770ce552a4233ba64ff13907.tmp.TvJZ7u/embedded_tools/jdk': (error: 22): Invalid argument

**Comment by daohu527** [comment]
> Output base '/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32' is on NFS

According to the error, it is better to compile on local disk and try again
