### ISSUE TITLE
Try to build 3d perception model SMOKE, bug got error: no such package '@caffe//

### ISSUE THREAD

**Issue by clw5180** [ApolloAuto/apollo#14580]
I use the apollo 7.0, and mv BUILD_ to BUILD, and use the command:  bazel test --config=unit_test //modules/perception/camera/test:camera_app_obstacle_camera_perception_test 

but I got error below:
(07:16:40) ERROR: /apollo/modules/perception/camera/test/BUILD:6:8: no such package '@caffe//': The repository '@caffe' could not be resolved and referenced by '//modules/perception/camera/test:camera_app_obstacle_camera_perception_test'
How to solve this problem? Thx!

**Comment by daohu527** [comment]
@clw5180 caffe is remove from apollo long time ago, These test cases are broken, we will fix these soon. So please wait some time!

**Comment by JichenFang** [comment]
@daohu527   If I want to use caffe in apollo7.0, What should I do?
