### ISSUE TITLE
Does Apollo 7.0 support RTX3080ti?

### ISSUE THREAD

**Issue by ForresterLu** [ApolloAuto/apollo#14587]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04.4 LTS
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0

I have a RTX 3080ti graphic card, can I install Apollo 7.0 with it?

**Comment by YuqiHuai** [comment]
I was able to use Apollo 7.0 with RTX 3090 and 3090Ti. I think you should be able to use 3080Ti.

**Comment by WildBeast114514** [comment]
In general, Apollo 7.0 can run on 10, 20, 30 series Nvidia graphics cards.
I recommend using the 470.63.01 version of the driver and nvidia-docker2 to enable gpu in container.

**Comment by AmRepo** [comment]
I have another question, Does Apollo r5.5.0 support RTX3090? Please help to check this one, thanks

**Comment by WildBeast114514** [comment]
> I have another question, Does Apollo r5.5.0 support RTX3090? Please help to check this one, thanks

No, the driver version which RTX3090 can install is conflicted with Apollo r5.5.0

**Comment by AmRepo** [comment]
Thanks for your quick response. I have adapt environment  and calibration in the vehicle based on r5.5.0. So if i want to replay record in the office, i also need do it based on r5.5.0, right? So which version could be used for r5.5.0？



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/28/2022 20:07 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [ApolloAuto/apollo] Does Apollo 7.0 support RTX3080ti? (Issue #14587) |

I have another question, Does Apollo r5.5.0 support RTX3090? Please help to check this one, thanks

No, the driver version which RTX3090 can install is conflicted with Apollo r5.5.0
