### ISSUE TITLE
[ERROR] The build operation must be run from within docker container

### ISSUE THREAD

**Issue by QiTianDaShengMaoHuiFei** [ApolloAuto/apollo#14596]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)** : ubuntu 20.04
- **Apollo installed from (source or binary)**:
- **Apollo version ** : 7.0
- **Output of `apollo.sh config` if on `master` branch**:

**

~/apollo$ sudo bash apollo.sh build_gpu drivers/camera
[sudo] password for movex: 
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /home/movex/apollo
[INFO]     APOLLO_CACHE_DIR: /home/movex/apollo/.cache
[INFO]     APOLLO_IN_DOCKER: false
[INFO]     APOLLO_VERSION: HEAD-2021-12-28-463fb82f9e
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST= USE_GPU_TARGET=1
[INFO] Configure .apollo.bazelrc in non-interactive mode
Cannot find bazel. Please install bazel first.
[ OK ] Successfully configured .apollo.bazelrc in non-interactive mode.
[ERROR] The build operation must be run from within docker container

I wanted to remove Docker and compile Camera module separately, but the following error occurred

**Comment by daohu527** [comment]
Removing the container is not tested, you need to install the environment required by the entire perception module.

**Comment by CesarLiu** [comment]
> Removing the container is not tested, you need to install the environment required by the entire perception module.

@daohu527 how to identify the specific running environment for perception? or just install te dependencies for whole apollo?

**Comment by daohu527** [comment]
We will release the perception package in the near future, which means that the perception module can be run separately, but it still need docker
