### ISSUE TITLE
how to add new camera?

### ISSUE THREAD

**Issue by zmmhz** [ApolloAuto/apollo#14591]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- 在视觉检测模块中所有的默认初始化话模块都限定只能两个摄像头，如int FusionCameraDetectionComponent::InitCameraFrames()中进入就判断是否是两个摄像头，是否去除此限制就可以直接添加第三个摄像头进行测试？还需要其他修改吗？

### Supporting materials (screenshots, command lines, code/script snippets):
  if (camera_names_.size() != 2) {
    AERROR << "invalid camera_names_.size(): " << camera_names_.size();
    return cyber::FAIL;
  }

**Comment by daohu527** [comment]
Currently only 2 cameras are supported. In fact, if you add multiple cameras, you have to consider whether it is panorama or pure redundancy. In case of redundancy with multiple cameras, I think this may require detailed process design
