### ISSUE TITLE
can I use cyber_visualizer through remote access?

### ISSUE THREAD

**Issue by ywangwxd** [ApolloAuto/apollo#14599]
The cyber_visualizer need a Linux desktop env. It is common that we install apollo docker in a linux server. If I can run cyber_visualizer on my local Linux box (with desktop env) and access the cyber channel data through remote access to the server, that will be very helpful.

Can I do this now?

**Comment by CesarLiu** [comment]
try this https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_setup_dual_ipc.md

**Comment by YCC-324** [comment]
> try this https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_setup_dual_ipc.md

Hello, the link cannot be opened now

**Comment by daohu527** [comment]
update here
https://github.com/ApolloAuto/apollo/blob/master/docs/01_Installation%20Instructions/how_to_setup_dual_ipc.md

**Comment by YCC-324** [comment]
> update here https://github.com/ApolloAuto/apollo/blob/master/docs/01_Installation%20Instructions/how_to_setup_dual_ipc.md

Thanks very much
