### ISSUE TITLE
请问支持aarch64版本的apollo 7.0的docker镜像出来了吗

### ISSUE THREAD

**Issue by QiTianDaShengMaoHuiFei** [ApolloAuto/apollo#14594]
请问支持aarch64版本的apollo 7.0的docker镜像出来了吗？有没有完整详细的配置教程呢

**Comment by daohu527** [comment]
请问你是需要哪部分的arm版本，如果是cyber目前是支持的，其它模块还没有ready，还需要部分适配。

**Comment by SmallElectron** [comment]
请问其他模块支持arm版本的啥时候可以发布呢？

**Comment by daohu527** [comment]
目前并没有详细的计划，如果支持该功能，我们将第一时间通知你。
