### ISSUE TITLE
testing  traffic light perception module fail 

### ISSUE THREAD

**Issue by ywangwxd** [ApolloAuto/apollo#14606]
I am using SVL simulation with Apollo latest branch,  Ubuntu 18.04.

I tested lidar obstable perception, camera perception. They all work well. 
But when I tried this one:
`cyber_launch start /apollo/modules/perception/production/launch/perception_trafficlight.launch`

It failed, the error message are:

 hdmap_input.cc:396] Failed to call HDMap::get_signal. point: x: 0 y: 0 z: 0

There are a lot of lines of message like the above.  I checked the log of map,  I have not seen any error message. I am using the 
[Lincoln2017MKZ] veichle and BorregasAve map. The sonsor configuration is cloned from Apollo 5.0 (fully analysis). It has lidar and two front cameras. 

I  checked the channels, I found there gnss related channels has data streaming:

/apollo/sensor/conti_radar                              9.41
/apollo/sensor/gnss/best_pose                           12.37
/apollo/sensor/gnss/corrected_imu                       86.53
/apollo/sensor/gnss/imu                                 87.27
/apollo/sensor/gnss/ins_stat                            9.38
/apollo/sensor/gnss/odometry                            12.37

I do not know what this error message means.  Does it mean the localization is wrong? It always get position 0,0,0.

**Comment by SeasoulChris** [comment]
If /apollo/localization/pose or /tf has data   ?

**Comment by qilinhu** [comment]
It is recommended that you check whether there is high-precision map channel data. This problem seems to be that there is no map data. You can check whether there is normal data output in the /localization and /tf channels.
