### ISSUE TITLE
Apollo6.0 docker compile ./apollo build_opt_gpu Unsupported gpu architecture ‘compute_86’

### ISSUE THREAD

**Issue by fah870599552** [ApolloAuto/apollo#14605]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:ubuntu 20.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
![image](https://user-images.githubusercontent.com/83059615/191474348-c12f1c90-d4dc-41ae-aef5-a601f1fa3a94.png)

### Supporting materials (screenshots, command lines, code/script snippets):
outside of the docker, my CUDA version is 11.6, however inside of the docker my cuda is 10.2
![image](https://user-images.githubusercontent.com/83059615/191474697-2a6c085e-7532-48bf-b401-b9051a8924ba.png)

**Comment by WildBeast114514** [comment]
In your posted information, current cuda version in container is 10.2. NVCC of this version is too old to support compute_86.

Since nvcc and cuda is already installed in images, we recommend to reset "TORCH_CUDA_ARCH_LIST" parameter.

First input the following command:
`nvcc --help | grep sm` 

to check the appropriate value of your nvcc supported. You may see the following output:
`'sm_35','sm_37','sm_50','sm_52','sm_53','sm_60','sm_61',
        'sm_62','sm_70','sm_72','sm_75', ...`

then choose a value. In the example above, assuming we choose sm75.

Finally reset the environment variables:
`unset TORCH_CUDA_ARCH_LIS`
`export TORCH_CUDA_ARCH_LIST="7.5"`

**Comment by fah870599552** [comment]
![image](https://user-images.githubusercontent.com/83059615/192530333-d5184b7c-4195-4908-9867-168fdd26771e.png)

I followed your advice, but I till got this problem. BTW, my GPU is 3090, is there any way to upgrade the CUDA version inside the docker?
> In your posted information, current cuda version in container is 10.2. NVCC of this version is too old to support compute_86.
> 
> Since nvcc and cuda is already installed in images, we recommend to reset "TORCH_CUDA_ARCH_LIST" parameter.
> 
> First input the following command: `nvcc --help | grep sm`
> 
> to check the appropriate value of your nvcc supported. You may see the following output: `'sm_35','sm_37','sm_50','sm_52','sm_53','sm_60','sm_61', 'sm_62','sm_70','sm_72','sm_75', ...`
> 
> then choose a value. In the example above, assuming we choose sm75.
> 
> Finally reset the environment variables: `unset TORCH_CUDA_ARCH_LIS` `export TORCH_CUDA_ARCH_LIST="7.5"`

**Comment by IvDmNe** [comment]
I met the same problem, and this issue (https://github.com/ApolloAuto/apollo/issues/13254) has a workaround to compile modules and use ones that don't require GPU (AFAIK, only perception and prediction use gpu). Support for 3000 series of RTX was added in apollo 7.0 . After few tries of cherry-picking several commits related to CUDA upgrade from 7.0 branch to 6.0 I wasn't able to  provide support for newer GPUs. So, the only way, I suppose, is to use apollo 7.0.
