### ISSUE TITLE
Evaluators in prediction module 

### ISSUE THREAD

**Issue by JichenFang** [ApolloAuto/apollo#14609]
In prediction module,there are many evaluators. where are their trainning projects?  and how can I know what method they used such as "vectornet_evaluator","semantic_lstm_evaluator","lane_scanning_evaluaor" and so on.

**Comment by daohu527** [comment]
@JichenFang There is currently no open training code.
We have received your feedback We have opened the training code of the perception part, and we will see if the prediction part is opened later
