### ISSUE TITLE
about "MODE_MOCK"

### ISSUE THREAD

**Issue by Shaquille-Wu** [ApolloAuto/apollo#14619]
Hi, apollo experts
I found planning module cannot work correctly because of "MODE_MOCK"
In modules/planning/on_lane_planning.cc, row 296,
I found the "start_timestamp" always is 0, so, "DCHECK_GE" always raise the "assert"
I found this behavior is decided by the clock mode, we should setNow in "MODE_MOCK", but, I just found it is executed in initialization, so, it is always 0!
how can I enable my planning work correcty? 

another confue about this "MODE_MOCK", in cyber/proto/run_mode_conf.proto, there are some definitions as following:
syntax = "proto2";

package apollo.cyber.proto;

enum RunMode {
  MODE_REALITY = 0;
  MODE_SIMULATION = 1;
}

enum ClockMode {
  MODE_CYBER = 0;
  MODE_MOCK = 1;
}

message RunModeConf {
  optional RunMode run_mode = 1 [default = MODE_REALITY];
  optional ClockMode clock_mode = 2 [default = MODE_CYBER];
}

"clock_mode" should be 1? because MODE_CYBER is 0

**Comment by daohu527** [comment]
@Shaquille-Wu Do you want to use `MODE_MOCK ` or `MODE_MOCK ` have some error?

Why does planning enter MODE_MOCK mode?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
