### ISSUE TITLE
record_parse_save.py -> parse_camera.py: Cannot parse image from demo recording file

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#14615]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: master
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- The recording file channel information:
![image](https://user-images.githubusercontent.com/42797233/192324794-97b391fc-8324-433f-a989-ea5889d59123.png)

- Modify [parser_params.yaml](https://github.com/ApolloAuto/apollo/blob/master/modules/tools/record_parse_save/parser_params.yaml) to parse camera data
![image](https://user-images.githubusercontent.com/42797233/192323635-13a69daf-a0d3-4f48-baa5-5cd15acd18d4.png)
- Modify [parse_camera.py](https://github.com/ApolloAuto/apollo/blob/master/modules/tools/record_parse_save/parse_camera.py): changing `msg_camera = CompressedImage()` to `msg_camera = Image()`
![image](https://user-images.githubusercontent.com/42797233/192324204-4a8edb96-2d69-4a52-9fe8-511ea813252d.png)
- **Encountering error:** `File "/apollo/modules/tools/record_parse_save/parse_camera.py", line 43, in parse_data
    msg_camera.ParseFromString(str(msg))
TypeError: a bytes-like object is required, not 'str'
`
![image](https://user-images.githubusercontent.com/42797233/192324965-0fd60b72-fff7-48f7-b901-5d9c6d4f68f5.png)

**Comment by daohu527** [comment]
There is a bug! change `msg_camera.ParseFromString(str(msg))` to `msg_camera.ParseFromString(msg)`

by the way
- CompressedImage. You can get the image
- Image. The data is a matrix, so you need to do some transform
