### ISSUE TITLE
[buildtool] ERROR Build and install package planning-dev failed! You should checkout the BUILD file.

### ISSUE THREAD

**Issue by Loine08** [ApolloAuto/apollo#14612]
(14:50:37) WARNING: Download from https://github.com/bazelbuild/bazel-skylib/archive/6e30a77347071ab22ce346b6d20cf8912919f644.zip failed: class java.net.ConnectException Connection refused (Connection refused)
(14:50:37) ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
	File "/home/loin/.cache/bazel/_bazel_loin/679551712d2357b63e6e0ce858ebf90e/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/archive/6e30a77347071ab22ce346b6d20cf8912919f644.zip] to /home/loin/.cache/bazel/_bazel_loin/679551712d2357b63e6e0ce858ebf90e/external/bazel_skylib/temp11806552525600762727/6e30a77347071ab22ce346b6d20cf8912919f644.zip: Connection refused (Connection refused)
(14:50:37) ERROR: /apollo_workspace/WORKSPACE:22:30: fetching http_archive rule //external:bazel_skylib: Traceback (most recent call last):
	File "/home/loin/.cache/bazel/_bazel_loin/679551712d2357b63e6e0ce858ebf90e/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/archive/6e30a77347071ab22ce346b6d20cf8912919f644.zip] to /home/loin/.cache/bazel/_bazel_loin/679551712d2357b63e6e0ce858ebf90e/external/bazel_skylib/temp11806552525600762727/6e30a77347071ab22ce346b6d20cf8912919f644.zip: Connection refused (Connection refused)
(14:50:37) ERROR: no such package '@bazel_skylib//': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/archive/6e30a77347071ab22ce346b6d20cf8912919f644.zip] to /home/loin/.cache/bazel/_bazel_loin/679551712d2357b63e6e0ce858ebf90e/external/bazel_skylib/temp11806552525600762727/6e30a77347071ab22ce346b6d20cf8912919f644.zip: Connection refused (Connection refused)
(14:50:37) INFO: Elapsed time: 13.050s
(14:50:37) INFO: 0 processes.
(14:50:37) FAILED: Build did NOT complete successfully (0 packages loaded)
(14:50:37) FAILED: Build did NOT complete successfully (0 packages loaded)
[buildtool] ERROR Build and install package planning-dev failed! You should checkout the BUILD file.

**Comment by qilinhu** [comment]
@Loine08 hi！The reason for this problem is because of the network, you can try to switch the network to download and install again, which should solve this problem.
