### ISSUE TITLE
How to add new camera instances?

### ISSUE THREAD

**Issue by ywangwxd** [ApolloAuto/apollo#14625]
I want to test a configuration with two new camera instances, e.g, a left front camera and right front camera.
I am working with SVL simulator and ApolloAuto.

At this moment, I have already done these:
1, Add two new camera instances in the SVL simulator. Change the rotation angle parameters of the two cameras.
2, Add new toppic pubslished to ApolloAuto, and create all the other config files needed.
3, Launch the obstacle detection pipeline (SMOKE algorithm) and enable debug. From the debug output, I can see the two images are in the right viewpoint and the algorithm is working fine.

The intrinsic parameters of these two camera instances are copied from the front camera, this should be fine.
The big question is the extrinsic parameters. I do not know how to get it. But the make the pipeline run, I have just copied them from the front camera. I know these configs are not correct, they are just in correct format. 

So how should I get them?

Another question, I found that both the extrinsic and intrinsic parameter file of the default front camera has been changed after I launched a camera module pilepline. Does this mean some internal process has modified these parameters automatically? Does this mean I do not need to specify them manually? What is underline logic they are modifed?

**Comment by daohu527** [comment]
@ywangwxd 

Another question, I found that both the extrinsic and intrinsic parameter file of the default front camera has been changed after I launched a camera module pilepline. Does this mean some internal process has modified these parameters automatically?

> when you choose the vehicle in dreamview. it will auto modify the config according to the vehicle type. It actually copies the corresponding configuration to the corresponding path, so you need to confirm whether these internal and external parameters are what you want
