### ISSUE TITLE
apollo_canbus&chassis&teleop  adaption bug report

### ISSUE THREAD

**Issue by RANYABING** [ApolloAuto/apollo#14620]
最近负责Apollo与小车底盘适配工作，在调试过程中遇到一些问题。
大概情况描述如下:我们根据<Apollo车辆适配教程>完成了CAN协议设计，DBC转换等工作。测试时使用Apollo自带的底盘联调工具teleop（用键盘按键生成控制命令），发现控制命令无法下发给底盘。根据打印的调试日志来看，应该是canbus模块没有成功调用onControlCommand回调函数，初步猜测是控制命令不符合回调函数要求，导致调用不了回调函数。
请问有大佬可以帮忙看看什么问题吗？

Recently, I was responsible for the adaptation of Apollo and trolley chassis, and encountered some problems during the commissioning process.
The general situation is as follows: We have completed the CAN protocol design, DBC conversion and other work according to the<Apollo Vehicle Adaptation Tutorial>. During the test, Teleop, the chassis joint debugging tool provided by Apollo, was used to generate control commands with the keyboard keys. It was found that the control commands could not be issued to the chassis. According to the printed debug log, it should be that the canbus module failed to call the onControlCommand callback function. The initial guess is that the control command did not meet the requirements of the callback function, resulting in the failure to call the callback function.
Excuse me, can you help me to see what the problem is?

**Comment by daohu527** [comment]
鉴于你提供的信息，大概率是没有添加相应的注册函数，你可以参考以下文档。

[Apollo车辆适配教程](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/docs/technical_tutorial/apollo_vehicle_adaption_tutorial_cn.md)

**Comment by macDure** [comment]
1、有没有将新的车辆controller添加到工厂模式？
2、message manager上有没有sender message？
3、具体的执行接口（转向、驱动、制动）等有没有写具体实现；
4、checkresponse 是检查底盘在自动驾驶，如果使能后底盘是否进入自动驾驶？
