### ISSUE TITLE
Error  Map folder is invalid

### ISSUE THREAD

**Issue by Ladanovasv** [ApolloAuto/apollo#14626]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version 7.0**:
- **Output of `apollo.sh config` if on `master` branch**:

I tried NDT localization. But there was an error.
![image](https://user-images.githubusercontent.com/47398458/193520757-a4ffb751-62ed-43a4-92ba-f938cd124c23.png)
The map was built using ndt_map_creator.cc

**Comment by Ladanovasv** [comment]
It may seem an example of a card on which NTD localization worked.

**Comment by daohu527** [comment]
You can follow below steps
1. the ndt map is create in `/apollo/modules/localization/map/ndt_map/local_map`
```
ndt_map_creator --pcd_folders=/apollo/data/pcd --pose_files=/apollo/data/pcd/poses.txt --resolution_type=single --resolution=1 --zone_id=50 --map_folder=/apollo/modules/localization/map/ndt_map/local_map
```

2. set map directory
```
vi /apollo/modules/common/data/global_flagfile.txt

--map_dir=/apollo/modules/localization/map
```
