### ISSUE TITLE
[Planning Bug] Apollo did not brake in time and rear-ended a vehicle.

### ISSUE THREAD

**Issue by AV-Security** [ApolloAuto/apollo#14629]
**Describe the bug**
The ego had enough braking space but did not brake in time and rear-ended the NPC vehicle in front. 
*Note: Simulator platform was LGSVL and the perception results were ground-truth data provided by LGSVL.

**System information**
OS Platform and Distribution: Ubuntu 18.04
Apollo installed from (source or binary): source
Apollo version : 6.0 (master branch - commit b5bd74112e2ec5d7c65cad6bea592353de566156)

**To Reproduce**
The video corresponding to the collision scenario is in the attachment.

**Expected behavior**
The ego should increase the braking effort to avoid the collision.

**Additional context**
It seems that the planning module has designed an emergency stop scenario, but it did not implement the logic to switch to this scenario automatically.
We manually switched to the emergency stop scenario through an external command when the simulation started then the ego stopped in time without rear-ending the front NPC vehicle.

**Demo Video**
Before switching to the emergency stop scenario.

https://user-images.githubusercontent.com/87695978/193574798-d944ef2e-8c9c-4c94-b325-7767db472542.mp4

After switching to the emergency stop scenario.

https://user-images.githubusercontent.com/87695978/193575050-ab8c75a8-c258-46be-b671-a3ce991b1833.mp4

**Attachments**

[Collision Video](https://drive.google.com/file/d/1T3XNnRybeKqs2F80ZSKtdLMfrFbG1KK4/view?usp=sharing)
[Not-Collision Video](https://drive.google.com/file/d/1Me_y1v6tfEuMM3e5Awvpcyt9mny0WIOW/view?usp=sharing)

**Comment by ntutangyun** [comment]
By switching to the emergency stop scenario, do you mean by pressing the down arrow button in the simulator?

BTW, this is known issue a long time ago. 
I'm not entirely sure, but there may be two possibilities. 1: calibration is not right 2. they limit the braking power such that to avoid sudden braking (comfortness)..

**Comment by AV-Security** [comment]
@ntutangyun thanks for your comments. The planning module already implements an emergency stop scenario mode, but it only can be applied by an external command through `planning_pad_topic`("/apollo/planning/pad”). So by switching to the emergency stop scenario, I mean to provide a `STOP` command to `planning_pad_topic` making the Apollo switch to the emergency stop scenario to perform the stop planning. So I think the main problem is that Apollo is capable of stopping in this scenario, but it does not select the reasonable scenario mode to make the stop planning.

**Comment by ntutangyun** [comment]
Yes, the `pad` message channels if I recall correctly are sent from remote controllers carried with human testers.. @daohu527 Hi, kindly correct me if I'm wrong lol.

Hence, by design Apollo doesn't switch to the emergency brake during its normal operation. 

One more question, I remember Apollo's configured (default) maximum navigation speed is about 10m/s, which is about 36km/h.  Did you increase this default configuration to 55km/h or did you setup this emergency braking scenario by manually setting its initial speed higher than its default configuration?

**Comment by AV-Security** [comment]
@ntutangyun thanks for pointing out this problem. The initial speed of the ego in the scenario is indeed higher than the default configuration. I'll try to change the initial speed to a reasonable range later to see if there exists a similar problem.

**Comment by qwetqwe** [comment]
The distance may exceed stop distance of maximum deceleration in planning.
