### ISSUE TITLE
What is coordinate of the corner?

### ISSUE THREAD

**Issue by phs4530** [ApolloAuto/apollo#14631]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

I am making an apollo map.
Apollo_HDMap_OpenDrive_Specs_A3.0.1 is referred to.
I'm trying to link a traffic light to the map, but I don't know what the description of the traffic light means.

![image](https://user-images.githubusercontent.com/18480213/193718259-d7af85ac-17fb-4789-a853-d7ce52c46731.png)

**Comment by daohu527** [comment]
@phs4530 A traffic light is usually a rectangle with 4 corners corresponding to 4 coordinates. There're already some map in `modules/map/data` you can ref to.
