### ISSUE TITLE
two questions about Configuration Parameters in apollo.

### ISSUE THREAD

**Issue by researcherzxd** [ApolloAuto/apollo#14638]
Hi, 
I'm a researcher in SMU, Singapore, focusing on ADS safety.
I have two questions on the configuration parameters in ADS modules.
1.Do the configuration parameters (e.g., gear_shift_period_duration in planning module) affect the driving status of ego vehicle?
2.Are the current configuration parameters fixed? or Can we tune them to adapt more scenarios?

Thanks.

**Comment by ntutangyun** [comment]
hello from NTU. Looks like we are working on the same topic. If you're keen, you may add my WeChat: XX_101n374i1_XX and we can discuss on this further :)

back to your questions: 
1. by a quick full source code source, the `gear_shift_period_duration` in the planning module is only used in the open space trajectory partition optimizer, which may affect scenarios such as dead-end turn, park and go, pull over, valet parking etc.
2. Yes by all means you can change the parameters however you want. But be sure you know what you're doing:)

**Comment by researcherzxd** [comment]
> 

Great. 
Added you.

**Comment by daohu527** [comment]
seems solved! if you still have questions, feel free to reopen it
