### ISSUE TITLE
[Planning Bug] Apollo was unable to avoid a rear-ending vehicle.

### ISSUE THREAD

**Issue by AV-Security** [ApolloAuto/apollo#14633]
**Describe the bug**

There exists an NPC that accelerates forward behind the ego, and the ego has space to accelerate forward, but it did not accelerate in time to avoid tailgating.

*Note: Simulator platform was LGSVL and the perception results were ground-truth data provided by LGSVL.

**System information**
OS Platform and Distribution: Ubuntu 18.04
Apollo installed from (source or binary): source
Apollo version : 6.0 (master branch - commit b5bd74112e2ec5d7c65cad6bea592353de566156)

**To Reproduce**

The video corresponding to the collision scenario is in the attachment.

**Expected behavior**

The ego should accelerate according to the predicted trajectory of the NPC.

**Additional context**

It seems that `STObstaclesProcessor` will ignore the predicted trajectories of NPCs behind ego when calculating the ST bounds for speed planning, resulting in ego not reacting to such tailgating NPCs.

**Demo Video**

https://user-images.githubusercontent.com/87695978/193734712-c66cb977-d74a-4f41-9f5c-e1a6a7745729.mp4

**Attachments**

[Collision Video](https://drive.google.com/file/d/1eQ1S4JsqCAfJr4m51uCqf4OzBc_Zw4KL/view?usp=sharing)

**Comment by ntutangyun** [comment]
I believe the vehicle behind is fully responsible for the collision instead...

**Comment by AV-Security** [comment]
@ntutangyun thanks for your comments. I understand that the rear-ending NPC is responsible for this collision.  However, my main concern in this scenario is that there is reasonable room for ego to avoid this collision. The predicted trajectory of the NPC can tell that the NPC is about to collide with the ego, but there are no corresponding decisions.  For this reason, I analyzed the code of the planning module and found that the following code in `STObstaclesProcessor` will ignore the predicted trajectories of all NPCs behind the ego.
- commit id:b5bd74112e2ec5d7c65cad6bea592353de566156
- modules/planning/tasks/deciders/st_bounds_decider/st_obstacles_process.cc::185
- STObstaclesProcessor::MapObstaclesToSTBoundaries
    
![image](https://user-images.githubusercontent.com/87695978/194741110-d3c97f63-fdf0-4321-af86-1370cdba6dcb.png)

Therefore, I wonder whether there is a safer way to deal with such NPCs, or adjust the ego trajectories and speeds according to their predicted trajectories in specific dangerous situations, rather than completely ignoring them.

**Comment by ntutangyun** [comment]
it only took two seconds for the truck to crash into Apollo. slowing down apparently cannot avoid the collision.  even if Apollo decides to change lane to give way. there is still no time for this...

Maybe Apollo should do something if for example there is an emergency vehicle (an ambulance) behind. but ambulance won't crash into Apollo deliberately....

**Comment by AV-Security** [comment]
@ntutangyun In fact, I only capture a few seconds of this scenario and there are many more cases like this.  More importantly, we can see from the code that even if the ego has enough time to respond, the current Apollo will not consider this case for now. I understand that this is perhaps too much to ask of Apollo, but I think it is necessary to point out that such problems exist in Apollo.

**Comment by ntutangyun** [comment]
So basically it's a potential new feature that is nice to have in the future. 
You may refer to them as bugs, but I just don't think so as Apollo is not responsible for this type of collision and this is most likely not the Apollo developers' priority to implement this feature. 

I think it's just a subjective call whether you wish to call it a bug or problem considering the current implementation.
cos Apollo itself does not publish or have a detailed list of functions or features it is designed to work for our reference.
