### ISSUE TITLE
How to do park and go?

### ISSUE THREAD

**Issue by setra2014** [ApolloAuto/apollo#14639]
Hello! I try to start park and go scenario, but I don't know conditions of its launch and can't find any documentation about this scenario. I will grateful if someone tell about this scenario or show code to start it.

**Comment by YuqiHuai** [comment]
I found this which might be helpful to you https://daobook.github.io/apollo/docs/technical_documents/parking_scenario.html?highlight=park%20go#park-and-go-scenario
