### ISSUE TITLE
How to tune the values of the config parameters if they are not suitable for current driving requirement?

### ISSUE THREAD

**Issue by researcherzxd** [ApolloAuto/apollo#14636]
For example, how to judge whether a parameter is relevant to a collision?

manual trial-and-error, or something else?

**Comment by daohu527** [comment]
@researcherzxd There are so many parameters, and we have to analyze case by case, I think it is difficult to have a unified standard.

For example, the effect of localization parameters is used to measure the stability of positioning, and the planning parameters are used to measure the safety and efficiency of planning paths.

Glad to be able to share some of your insights！
