### ISSUE TITLE
Out of memory error when running self-trained CenterPoint

### ISSUE THREAD

**Issue by ideasplus** [ApolloAuto/apollo#14646]
Hello, team

I recently met an issue when I try to run the CenterPoint model trained from Paddle3D on KITTI data. The GPU memory usage will over 10G and makes the perception module crash as the picture shows.  
<img width="677" alt="image" src="https://user-images.githubusercontent.com/24294571/194773324-c2badd0c-bda1-4a51-8016-4ec0c515be7e.png">
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/24294571/194774312-f83d4eb2-a2e9-4fab-b61c-8310bb474395.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/24294571/194773555-dad98857-04fc-4db4-a9fd-0fdec71ef194.png">

However, when I test the CenterPoint model file from this repository, the perception works very well and the GPU memory usage is stable at around 4G.  

Note that I have modified the config of CenterPoint  according to the KITTI data. But I can't make the trained model work as expected. Could anyone help me to solve the problem?

**Comment by FlyingQianMM** [comment]
> when I test the CenterPoint model file from this repository, the perception works very well and the GPU memory usage is stable at around 4G.

The training config for CenterPoint on kitti train set is opened on Paddle3D repo:  https://github.com/PaddlePaddle/Paddle3D/tree/develop/configs/centerpoint, can you supply your training config file? The difference between yours and the kitti baseline (https://github.com/PaddlePaddle/Paddle3D/blob/develop/configs/centerpoint/centerpoint_pillars_016voxel_kitti.yml) maybe the cause why your gpu consumtion is !10G but the Paddle3D kitti baseline is ～4G.

**Comment by ideasplus** [comment]
@FlyingQianMM 

Hi, Thank you for your reply!

In fact, I train the CenterPoint model using the config file from Paddle3D repo as you mentioned https://github.com/PaddlePaddle/Paddle3D/blob/develop/configs/centerpoint/centerpoint_pillars_016voxel_kitti.yml

There is more another question about your answer.  The CenterPoint model file (https://github.com/ApolloAuto/apollo/tree/master/modules/perception/production/data/perception/lidar/models/detection/center_point) provided by Apollo is trained on KITTI dataset? According to [modules/perception/lidar/lib/detector/center_point_detection/params.h](https://github.com/ApolloAuto/apollo/blob/12ab9e94891cfd2ef5a001f6e18bf56422402e42/modules/perception/lidar/lib/detector/center_point_detection/params.h), I think the model is trained on nuscenes dataset. Please correct me if I misunderstand it.

**Comment by btryq** [comment]
I got the same issue while running the perception module with the model file from this repo. Downsampling pointclouds and disabling frame-fusing works for me, but I don't think it solves the underlying problem.

**Comment by ideasplus** [comment]
> I got the same issue while running the perception module with the model file from this repo. Downsampling pointclouds and disabling frame-fusing works for me, but I don't think it solves the underlying problem.

Hi, what's the GPU configuration of your machine? It works for me when running the model file from this repo with the default configs.

@SeasoulChris @FlyingQianMM Any updates on this issue?

**Comment by ideasplus** [comment]
@SeasoulChris

Thanks for your advise!
