### ISSUE TITLE
Are there unit test file available for camera on SMOKE model?

### ISSUE THREAD

**Issue by GabrielZZZ** [ApolloAuto/apollo#14649]
Hi, I wonder if there is any unit test file available for the SMOKE model of the perception-camera module, like this unit test file of Yolo model: [camera_lib_obstacle_detector_yolo_yolo_obstacle_detector_test.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/test/camera_lib_obstacle_detector_yolo_yolo_obstacle_detector_test.cc)?

I found no test file in folder` /modules/perception/camera/test` about the SMOKE model, and the `/modules/perception/camera/tools/offline/offline_obstacle_pipline.cc` is not working right now #14621

**Comment by daohu527** [comment]
These features may be temporarily unavailable, we will fix it in the near future.

**Comment by GabrielZZZ** [comment]
Good to know. Thanks.
