### ISSUE TITLE
The Vehicle is Swaying in LGSVL simulation test！

### ISSUE THREAD

**Issue by sixiaixixiya** [ApolloAuto/apollo#14645]
Recently, I deployed a co-simulation environment on a server computer with the following configuration, but the vehicle shook during execution.
![Screenshot from 2022-10-09 10-27-23](https://user-images.githubusercontent.com/104459086/194734975-b336f3ba-165b-495c-9070-c514b2ea0903.png)
I suspect it is the delay of planning module！！！But I cannot find the resolution.
![Screenshot from 2022-10-09 10-15-29](https://user-images.githubusercontent.com/104459086/194735021-090e9fea-27a2-4cd6-ae94-06367c5cc346.png)
![Screenshot from 2022-10-09 10-22-05](https://user-images.githubusercontent.com/104459086/194735031-0fcda806-fbde-4601-9b91-c8fc6c9b460f.png)
![Screenshot from 2022-10-09 10-12-42](https://user-images.githubusercontent.com/104459086/194735050-813464ca-2bdb-479c-8cad-6bcca0660d4f.png)
![Screenshot from 2022-10-09 10-11-58](https://user-images.githubusercontent.com/104459086/194735053-8222897e-6d25-47f3-b869-954f4273f377.png)
Therefore, I  ask for your help sincerely！

**Comment by ntutangyun** [comment]
looks like the planning module is quite laggy. 

This might be due to your CPU frequency is too low ... You probably need a faster CPU instead of so many cores...

nice server BTW lol.

**Comment by sixiaixixiya** [comment]
> looks like the planning module is quite laggy.
> 
> This might be due to your CPU frequency is too low ... You probably need a faster CPU instead of so many cores...
> 
> nice server BTW lol.

Thanks for your reply. But I met this situation on my Game notebook. 
CPU：Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 
GPU：NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OS：Ubuntu 18.04.6 LTS
I find the planning module is still quite laggy. But the vehicle in lgsvl test is not swaying at all!
![2022-10-09 17-33-25屏幕截图](https://user-images.githubusercontent.com/104459086/194749694-371d50b5-de37-4fbf-a96d-bb809971a0d9.png)
Maybe the issue is more than just about CPU.

**Comment by sixiaixixiya** [comment]
> 

Thanks for your comment. I just doubt LGSVL too! But I didn't have any method to delve into the problem. I just use the release of LGSVL 2021.03 without it's source code. It would be great if you had more ideas with the issue!

**Comment by daohu527** [comment]
I don't have good suggestions, in light of that, I'll close this issue then.
