### ISSUE TITLE
ComputeCameraCamera function

### ISSUE THREAD

**Issue by sunjia0909** [ApolloAuto/apollo#14648]
Hello everyone,
Recently, I'm studying the fusion module of Apollo, and when reading the code of ComputeCameraCamera function in track_object_distance.cc file, I find it directly returns the maximum value so that the fusion between cameras can not happen. Does anyone know how to extend this function when I want to fuse objects from different cameras? Thanks.

**Comment by daohu527** [comment]
I think this function is a reserved interface, which is not currently called.

**Comment by sunjia0909** [comment]
ok，will this function be completed in the future or keep unchanged? And if I want to fuse objects from two cameras, such as front_6mm and front_12mm, could you give me any suggestion about how to calculate their distance? Does projection from one to the other work? Thanks.

**Comment by daohu527** [comment]
In short, you can do it. If this interface is to be completed, a detailed design is required.

**Comment by sunjia0909** [comment]
OK, do you have any advice on it? For now, I'm thinking about extending it based on the function ComputeLidarCamera, do you think it's feasible? Thanks.

**Comment by daohu527** [comment]
I currently have no ideas about this, maybe we need more time to deal with it.
