### ISSUE TITLE
Apollo Sensor Unit (APU) email, apollo-hw@baidu.com, is not functioning. 

### ISSUE THREAD

**Issue by wrightpt** [ApolloAuto/apollo#14651]
The email to learn more about aquiring Apollo Sensor Unit (APU) is not working.

https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Apollo_Sensor_Unit/Apollo_Sensor_Unit_Installation_Guide.md

"The Apollo Sensor Unit is currently only provided to our Partners and certain developers. Questions regarding the availability and access to ASU should be directed to [apollo-hw@baidu.com](mailto:apollo-hw@baidu.com)"

Any thoughts on who to contact in order to learn more about the Apollo Sensor Unit?

Thank you,

Patrick

**Comment by daohu527** [comment]
@wrightpt you can try to connect in https://developer.apollo.auto/platform/hardware_cn.html. If there is no response, it is recommended to ask questions in the community
