### ISSUE TITLE
Outside container communication By cyberRT 

### ISSUE THREAD

**Issue by kakuhin1984** [ApolloAuto/apollo#14653]
Are there any complete examples or links to documentation on using cyberBridge to communicate with an outside container pure C++ program?
Thank you！

**Comment by kakuhin1984** [comment]
> The bridge need cyber module to run. so if you want use bridge module, you need cyber in both side.
> 
> If you want pure tcp clinet/server, you can ref to `modules/contrib/cyber_bridge`

Yes, I want to use pure client/server mode ，But it still seems to be communicating in cyber way. Any examples of external communication using traditional pure TCP? Or only through cyber way?

Thank you!

**Comment by daohu527** [comment]
- At least one side must rely on cyber. 
- Another side can be separated from cyber, but also depends on the message format in apollo.

Simply put, one end only needs to send the message according to the message type, and the other end parses and publishes it through cyber

**Comment by kakuhin1984** [comment]
> * At least one side must rely on cyber.
> * Another side can be separated from cyber, but also depends on the message format in apollo.
> 
> Simply put, one end only needs to send the message according to the message type, and the other end parses and publishes it through cyber

Here's what's going on

One docker container with cyber (talker and listener can communicate with each other in the container), the other one is cyber on the host (talker and listener can communicate with each other in the host).

In setup.bash, export CYBER_IP=127.0.0.1 for both side

However, if the cyber talker on the host and cyber listener in the docker container are enabled, messages cannot be received

How do I set it and solve it?

Thank you very much!

**Comment by daohu527** [comment]
This situation cannot be resolved. This is due to docket limitations

**Comment by kakuhin1984** [comment]
> This situation cannot be resolved. This is due to docket limitations

If normal tcp/udp does, this also seems to be a cyber limitation . ^_^

**Comment by daohu527** [comment]
cyber works on docker bridge mode, but not host mode. Everything needs to follow the rules, not omnipotence

**Comment by kakuhin1984** [comment]
> cyber works on docker bridge mode, but not host mode. Everything needs to follow the rules, not omnipotence

OK,Got it.But Could you plz give me a  example of bridge mode for client and server?
