### ISSUE TITLE
CyberRT docker image

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#14650]
Hello!
1 I need apollov7 docker env containing only  with cyberRT/bazel or cmake (without apollo algs) and necessary libraries and components to communicate with apollov7 algorithm. Is there a corresponding docker link or method? 
2 Could cyberRT be used to communicate between two containers on the same host?

Thanks a lot!

**Comment by daohu527** [comment]
> 1 I need apollov7 docker env containing only with cyberRT/bazel or cmake (without apollo algs) and necessary libraries and components to communicate with apollov7 algorithm. Is there a corresponding docker link or method?

You can build the docker yourself with https://github.com/ApolloAuto/apollo/blob/master/docker/build/cyber.x86_64.dockerfile, there is no official docker for cyber.

> 2 Could cyberRT be used to communicate between two containers on the same host?

Yes, but the docker need to be set to bridge mode, but not host mode. by default, apollo docker is host mode.

**Comment by yumianhuli2** [comment]
> > 1 I need apollov7 docker env containing only with cyberRT/bazel or cmake (without apollo algs) and necessary libraries and components to communicate with apollov7 algorithm. Is there a corresponding docker link or method?
> 
> You can build the docker yourself with https://github.com/ApolloAuto/apollo/blob/master/docker/build/cyber.x86_64.dockerfile, there is no official docker for cyber.
> 
> > 2 Could cyberRT be used to communicate between two containers on the same host?
> 
> Yes, but the docker need to be set to bridge mode, but not host mode. by default, apollo docker is host mode.

Bridge mode is suitable for communication between two Dockers and communication between one docker and one host, right?

Further, how to fit bridge mode instead of host mode, have detailed documentation, thank you very much!

**Comment by yumianhuli2** [comment]
> > 1 I need apollov7 docker env containing only with cyberRT/bazel or cmake (without apollo algs) and necessary libraries and components to communicate with apollov7 algorithm. Is there a corresponding docker link or method?
> 
> You can build the docker yourself with https://github.com/ApolloAuto/apollo/blob/master/docker/build/cyber.x86_64.dockerfile, there is no official docker for cyber.
> 
> > 2 Could cyberRT be used to communicate between two containers on the same host?
> 
> Yes, but the docker need to be set to bridge mode, but not host mode. by default, apollo docker is host mode.

您好！不是太理解如何与cyber bridge通信，消息topic和类型应该如何去体现，有一个详细的例子或者文档链接展示从client到cyber bridge再到apollo的某个特定节点的吗？
3Q！！

**Comment by daohu527** [comment]
Sorry there is currently no documentation for now. There're some example in `cyber/examples`, You can refer to it first.
