### ISSUE TITLE
void CheckLaneChangeUrgency(Frame* const frame); error logic

### ISSUE THREAD

**Issue by zhaofuxie** [ApolloAuto/apollo#14655]
```c++
  for (auto &reference_line_info : *frame->mutable_reference_line_info()) {
    // Check if the target lane is blocked or not
    if (reference_line_info.IsChangeLanePath()) {
      is_clear_to_change_lane_ = LaneChangeDecider::IsClearToChangeLane(&reference_line_info);
      is_change_lane_planning_succeed_ = reference_line_info.Cost() < kStraightForwardLineCost;
      continue;
    }
    // If it's not in lane-change scenario || (target lane is not blocked &&
    // change lane planning succeed), skip
    if (frame->reference_line_info().size() <= 1 || (is_clear_to_change_lane_ && is_change_lane_planning_succeed_)) {
      continue;
    }
```
It is not clear logic for this function.If we step into lanechange scenario and check whether block, we should not use the var is_clear_to_change_lane_,which is continue before use this var.

**Comment by zhaofuxie** [comment]
for (auto &reference_line_info : *frame->mutable_reference_line_info()) {
    // Check if the target lane is blocked or not
      is_clear_to_change_lane_ = LaneChangeDecider::IsClearToChangeLane(&reference_line_info);
      is_change_lane_planning_succeed_ = reference_line_info.Cost() < kStraightForwardLineCost;
    if (reference_line_info.IsChangeLanePath()&& (is_clear_to_change_lane_ && is_change_lane_planning_succeed_)_) {
      continue;
    }
    // If it's not in lane-change scenario || (target lane is not blocked &&
    // change lane planning succeed), skip
    if (frame->reference_line_info().size() <= 1) {
      continue;
    }
----------------------------------------------------------------
Maybe above  code is reasonable.

**Comment by daohu527** [comment]
@zhaofuxie Thanks for your feedback, but we need to improve the expression, first of all your font is too big and it doesn't point out where the problem is. Clear presentation helps us solve problems!
