### ISSUE TITLE
zlib-1.2.11.tar.gz is not found on 2022 Oct.

### ISSUE THREAD

**Issue by seokkilee** [ApolloAuto/apollo#14652]
I have a solution, let`s edit two files:
apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/io_bazel_rules_go/go/private/repositories.bzl
line 95 - 101
http_archive( name = "net_zlib", build_file = "@com_google_protobuf//:third_party/zlib.BUILD", sha256 = "b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30", strip_prefix = "zlib-1.2.13", urls = ["https://zlib.net/zlib-1.2.13.tar.gz"], )

apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/rules_proto/proto/private/dependencies.bzl
line 31-38
"zlib": { "sha256": "b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30", "build_file": "@com_google_protobuf//:third_party/zlib.BUILD", "strip_prefix": "zlib-1.2.13", "urls": [ "https://zlib.net/zlib-1.2.13.tar.gz", ], },

then build again

**Comment by YYangjlu** [comment]
1.2.11 and 12 do work, change to 13
