### ISSUE TITLE
apollo start configuration

### ISSUE THREAD

**Issue by joseph16388** [ApolloAuto/apollo#14661]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (official docker)**:
- **Apollo version (7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

HI! I am a new user of the apollo open source platform and I have the following question

1. I want to input some custom perception signals and only test the planning module of the system without apollo perception modular for modular testing.. Do I need to independently start some modules, such as prediction modular(What are the inputs, what are the data structures, and what are the topic names?) and planning modular...? Are there any other modules I need to start?

2. What are the launch methods, such as launch or whether the dreamViewer can be used to launch these modules?

3. Which hd map is currently used in latest apollo version? Does this module need to be started, or can it be started automatically along with other modules?

4. Do you have a demo experiment similar to tutorial based on the perception result cyber record package of the above map?

Thank you very much!

**Comment by daohu527** [comment]
first of all, we recommend that you read the relevant documentation first. These questions are hard to answer with Q&A, you know, space is limited and everyone has different questions

> I want to input some custom perception signals and only test the planning module of the system without apollo perception modular for modular testing.. Do I need to independently start some modules, such as prediction modular(What are the inputs, what are the data structures, and what are the topic names?) and planning modular...? Are there any other modules I need to start?

You can use sim_control to test planning module, and you just need to publish planning's input.

> What are the launch methods, such as launch or whether the dreamViewer can be used to launch these modules?

the launch file is to start modules, you can use `./scripts/bootstrap.sh` to start dreamview. You can start these modules by ui in dreamview. It is detailed in the documentation of dreamview

> Which hd map is currently used in latest apollo version? Does this module need to be started, or can it be started automatically along with other modules?

A prerequisite for running apollo is a map, there are currently some maps under the map path `modules/map/data`, you can choose the map in dreamview and then start the other modules.

> Do you have a demo experiment similar to tutorial based on the perception result cyber record package of the above map?

Currently we have a detailed Chinese tutorial waiting to be published. [docs](https://apollo.baidu.com/community/Apollo-Homepage-Document/Apollo_Doc_CN_8_0)
