### ISSUE TITLE
 [dynamic calibration] question about calibration？ data_collection_table.pb.txt

### ISSUE THREAD

**Issue by MAD-dee** [ApolloAuto/apollo#14663]
apollo version ：6.0 edu

[apollo](https://github.com/ApolloAuto/apollo)/[modules](https://github.com/ApolloAuto/apollo/tree/master/modules)/[dreamview](https://github.com/ApolloAuto/apollo/tree/master/modules/dreamview)/[conf](https://github.com/ApolloAuto/apollo/tree/master/modules/dreamview/conf)/data_collection_table.pb.txt

I delete the range of 10mps-20mps and >= 20mps, only left 0-10mps, and i done the calibration by the apollo studio.
Is it correct?
I delete the follow code in this file.
range {
        name: "Speed 10 ~ 20mps"
        criterion {
          field: "speed_mps"
          comparison_operator: GREATER_THAN_OR_EQUAL
          value: 10
        }
        criterion {
          field: "speed_mps"
          comparison_operator: LESS_THAN
          value: 20
        }
      }
      range {
        name: "Speed >= 20mps"
        criterion {
          field: "speed_mps"
          comparison_operator: GREATER_THAN_OR_EQUAL
          value: 20
        }
      }

**Comment by macDure** [comment]
you need two condition ，such as  speed >= 5m/s， and speed ＜ 5m/s
