### ISSUE TITLE
[planning]Routing is not ready

### ISSUE THREAD

**Issue by kakuhin1984** [ApolloAuto/apollo#14662]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (6.0,7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Dreamview shows that routing is successful, but  I opened apollo and the planning module  shows that Routing is not ready Therefore, the planning module cannot be fully started normally ,What is the reason for this?thank you!

![routing success](https://user-images.githubusercontent.com/102957855/199204559-bade9b73-a454-41c8-813f-55ddd8dffaf4.png)

![Routing is not ready](https://user-images.githubusercontent.com/102957855/199204558-09451fe2-82f3-4c55-b20b-43e75ba5746e.png)

**Comment by daohu527** [comment]
@kakuhin1984 This error is normal, because this check will be done after planning starts, and routing has not been sent at this time. This error is only in the startup phase, so the real error may be later, you need to look at the last output of the log

**Comment by kakuhin1984** [comment]
> @kakuhin1984 This error is normal, because this check will be done after planning starts, and routing has not been sent at this time. This error is only in the startup phase, so the real error may be later, you need to look at the last output of the log

hello!I did this experiment with only the routing (dreamview launch) and planning (cyber_lauch launch in docker) module, so how could I do this without starting simctl(simctl is ok no errors)? Could planning not report the error of no routing after sending routing?thx!

**Comment by daohu527** [comment]
> [planning]Routing is not ready appeared, so how could I do this without starting simctl(simctl is ok no errors)

So what is the purpose of starting the planning module?

> Could planning not report the error of no routing after sending routing?

Yes, It will stop report error when routing is ready, but I believe your hands are not that fast!!!

**Comment by kakuhin1984** [comment]
I would like to see a routing request set in dreamview so planning should not report an error,Because I did give a request to routing for planning requirement..

**Comment by kakuhin1984** [comment]
> > [planning]Routing is not ready appeared, so how could I do this without starting simctl(simctl is ok no errors)
> 
> So what is the purpose of starting the planning module?
> 
> > Could planning not report the error of no routing after sending routing?
> 
> Yes, It will stop report error when routing is ready, but I believe your hands are not that fast!!!

I would like to see a routing request set in dreamview so planning should not report an error,Because I did give a request to routing for planning requirement..

**Comment by daohu527** [comment]
planing---------------routing not ready----------------->|------------------------routing ready----------------->
routing------------------------------------------------------->routing request--------------------------------------->
----------------------------error-------------------------------|-------------------------error gone-------------------->

if you start planning the error message will always print, after you send routing request then it will go. there is a gap between start planning and send routing request, this is why you see the error message.
