### ISSUE TITLE
Some questions about apollo monocular ranging

### ISSUE THREAD

**Issue by ycdhqzhiai** [ApolloAuto/apollo#14664]
I read the blog about apollo monocular ranging, which mentioned building a hash table to query the distance according to the obstacle size.But after reading the Apollo code, I found that it was made by using the original pinhole imaging.I would like to ask how to query the distance of obstacles using a hash table. Is there any related article

**Comment by daohu527** [comment]
Yes, there is a car size template. Then you can use the size prior and camera intrinsics to calculate the depth information

https://github.com/ApolloAuto/apollo/blob/aa0c5eb66189b86a724206305712cfb337c07619/modules/perception/production/data/perception/camera/common/object_template/object_template.pt#L15-L32

**Comment by ycdhqzhiai** [comment]
ok,thanks
