### ISSUE TITLE
proto: File not found.

### ISSUE THREAD

**Issue by joseph16388** [ApolloAuto/apollo#14666]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0,7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

Hello!
I have imported all proto files related to planning ADCTrajectory and put them into the same directory. I have removed all import relative paths from these proto files, but after using XXX/protoc -I=XXX/proto/ --cpp_out=XXX/proto/ XXX/proto/*.proto to generate pb.h pb.cc, but protoc tool still go to the original modules(e.g.modules/map/proto/) relative path find related proto files. What's the reason for this? thx!!

![proto file not found](https://user-images.githubusercontent.com/117060507/199875214-9e6aec98-66aa-4f28-8152-8a76748f3a20.png)

![proto import error](https://user-images.githubusercontent.com/117060507/199875225-a1b94e6a-0574-4e12-9093-7ec717e0e673.png)

plz see map_geometry.proto ,I've already removed all the "import" relative path!

**Comment by daohu527** [comment]
I think it's very likely that your file has not been modified completely, in fact it is not recommended to generate proto in this way.

**Comment by joseph16388** [comment]
> I think it's very likely that your file has not been modified completely, in fact it is not recommended to generate proto in this way.

Dear @daohu527 ,Thank you for your reply and ask further

1. Do you think there are any changes that may cause such problems? Indeed, I just deleted the relative path of import

2. What method do you think I should use to generate proto? (ps: I created another project in docker, using cyberRT, proto files were copied from the apollo code, two completely different projects)

THX!

**Comment by daohu527** [comment]
You can ref below shell function, which is generate python proto.
```shell
function build_py_proto() {
  if [ -d "./py_proto" ];then
    rm -rf py_proto
  fi
  mkdir py_proto
  PROTOC='./bazel-out/host/bin/external/com_google_protobuf/protoc'
  find modules/ cyber/ -name "*.proto" \
      | grep -v node_modules \
      | xargs ${PROTOC} --python_out=py_proto
  find py_proto/* -type d -exec touch "{}/__init__.py" \;
}
```

**Comment by joseph16388** [comment]
> You can ref below shell function, which is generate python proto.
> 
> ```shell
> function build_py_proto() {
>   if [ -d "./py_proto" ];then
>     rm -rf py_proto
>   fi
>   mkdir py_proto
>   PROTOC='./bazel-out/host/bin/external/com_google_protobuf/protoc'
>   find modules/ cyber/ -name "*.proto" \
>       | grep -v node_modules \
>       | xargs ${PROTOC} --python_out=py_proto
>   find py_proto/* -type d -exec touch "{}/__init__.py" \;
> }
> ```

Thank you

**Comment by joseph16388** [comment]
> I think it's very likely that your file has not been modified completely, in fact it is not recommended to generate proto in this way.

By the way, how do I check the version information that apollo depends on such as protobuf and other versions such as gflags and glog? Is there a corresponding list?e.g. apollov7 protobuf3.1.1 ...apollov5 glog2.3.2
THX!

**Comment by daohu527** [comment]
for now there is currently no such documentation, you can found the version in `docker/build/installers`. There is software version information in the installation script

**Comment by joseph16388** [comment]
> for now there is currently no such documentation, you can found the version in `docker/build/installers`. There is software version information in the installation script

THX!

**Comment by joseph16388** [comment]
I successfully generated Apollo-related pb file, thank you very much, but there is a new problem.

When Apollo bazel will directly to the output in the reconstruction of such as (# include "modules/canbus/proto/chassis. Pb. H") modules directory to find the header files, And the include references to these files are #include "modules/XXX/XXX"

I use the find modules/cyber / -name "*. Proto |" ${PROTOC} - python_out = py_proto xargs

The generated pb files are all modules/XX/XX. The directory above include_directories modules will report an error , for example fatal error: modules/audio/proto/audio.pb.h: No such file or directory, of course, just #include "audio.pb.h" is fine, but if I don't want to remove the relative path modules/XX/XX, how do I write cmakelist?

Thank you!!
