### ISSUE TITLE
NAVI Planer for Apollo 7.0 (help wanted)

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#14670]
Hello colleagues
I am trying to run navi_planning for apollo 7.0 version
I want Apollo7.0 to work like in Apollo2.5
Namely, for the navi_planning module (Apollo2.5), the Onroad type is used
Link is [here](https://github.com/ApolloAuto/apollo/blob/7461c419f708ac166bb2407f06d537ac92c48cdd/modules/planning/planner/navi_planner_dispatcher.cc#L25).
Onroad launch scenario_type lane_following

What do I need to do so that in Apollo 7.0 for the navi_planning module PUBLIC_ROAD starts with its own scenarios?

**Comment by daohu527** [comment]
You can follow this [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/D-kit/Waypoint_Following/start_waypoint_following_cn.md) and have a try
