### ISSUE TITLE
Which configuration file records the starting point of vehicle in default apollo hdmap (help wanted)

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#14671]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (5.0, 5.5, 6.0,7.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
hello！
How can I get the apollo default map like the starting coordinates of borregas ave, which is probably in some configuration file?Please tell me the location of the configuration file, thank you!

**Comment by 20210401Yao** [comment]
Hello, I see that you asked about chrono two years ago. Are you still using this engine? I have some questions to ask you, can you give me the contact information, thank you.

**Comment by daohu527** [comment]
As far as I know there is no such configuration. the start point is set by routing or localization

**Comment by YuqiHuai** [comment]
Are you referring to where the ego vehicle starts when you start up SimControl? If so, by taking a look at the source code of SimControl. Here are some relevant parts in the source code
```c++
// sim_control.cc
  // Use the latest localization position as start point,
  // fall back to a dummy point from map
```
```c++
// map_service.cc
bool MapService::GetStartPoint(apollo::common::PointENU *start_point) const {
  // Start from origin to find a lane from the map.
  double s, l;
  LaneInfoConstPtr lane;
  if (!GetNearestLane(0.0, 0.0, &lane, &s, &l)) {
    return false;
  }

  *start_point = lane->GetSmoothPoint(0.0);
  return true;
}
```
You can also manually publish some localization messages, then turn on SimControl. SimControl will see that there are existing localization messages and use them as the starting point.
