### ISSUE TITLE
git clonning for apolloauto pytorch doesn't work

### ISSUE THREAD

**Issue by jumogehn** [ApolloAuto/apollo#14673]
Hello,

"git clone --recursive --single-branch --branch apollo --depth 1 https://github.com/ApolloAuto/pytorch.git" fails with my github id and key code.

```
$ git clone --recursive --single-branch --branch apollo --depth 1 https://github.com/ApolloAuto/pytorch.git
Cloning into 'pytorch'...
Username for 'https://github.com': my-id
Password for 'https://my-id@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/ApolloAuto/pytorch.git/' not found

```

The command above is on here : https://github.com/ApolloAuto/apollo/blob/pre6/docker/build/installers/install_libtorch.sh
And the very url was mentioned here : https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/docker/build/installers/install_libtorch.sh

The url was introduced for users to be able to install libtorch for jetson board.

I am now trying to setup apollo 7.0 on jetson Orin AGX devkit.
OS : Ubuntu 20.04
cuda : 11.04

Latest libtorch in apolloauto for arm64 uses cuda 10.2 but the GPU in Orin doesn't seem to work with cuda 10.2. So I am trying to rebuild libtorch myself. Isn't there a recommeded guide possible? Can't I compile libtorch myself?

Thanks

**Comment by daohu527** [comment]
You can use the new install_libtorch.sh which already support arm and x86, the old one not supported for now!
