### ISSUE TITLE
Record and store perception data from the simulation on LGSVL

### ISSUE THREAD

**Issue by mshah72** [ApolloAuto/apollo#14672]
Is there any way in which I can record the data from the perception module if the simulation is ran on  LG SVL simulator? I want to record the dimension of the bounding boxes created around the vehicles in the simulation and the velocity of vehicles detected in the perception. 

### System information

- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):
- Apollo installed from (source):
- Apollo version (6.0):

**Comment by daohu527** [comment]
You can use `cyber_recorder` to record the published messages in to a file. Then you can parse the file and this will do what you want

**Comment by mshah72** [comment]
Can you please guide me how to use cyber_recorder?

**Comment by daohu527** [comment]
You can refer to the command prompt by
```
cyber_recorder -h
```
