### ISSUE TITLE
有人知道红绿灯检测如何使用faster rcnn模型吗

### ISSUE THREAD

**Issue by QiTianDaShengMaoHuiFei** [ApolloAuto/apollo#14677]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: x86 Ubuntu 20.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:apollo 7.0

默认是使用的caffe模型。我该如何修改成faster rcnn呢
`min_crop_size: 270
crop_method: 0
mean_r: 122.7717
mean_g: 115.9465
mean_b: 102.9801
is_bgr:true
crop_scale: 2.5
input_blob_name : "img"
im_param_blob_name : "im_info"
output_blob_name : "bboxes"
model_name: "./"
model_type: "RTNet"
proto_file:"deploy.prototxt"
weight_file: "baidu_iter_140000.caffemodel"
max_batch_size: 1  # only support 1 so far`

**Comment by QiTianDaShengMaoHuiFei** [comment]
'''
min_crop_size: 270
crop_method: 0
mean_r: 122.7717
mean_g: 115.9465
mean_b: 102.9801
is_bgr:true
crop_scale: 2.5
input_blob_name : "img"
im_param_blob_name : "im_info"
output_blob_name : "bboxes"
model_name: "./"
model_type: "RTNet"
proto_file:"deploy.prototxt"
weight_file: "baidu_iter_140000.caffemodel"
max_batch_size: 1  # only support 1 so far
'''

**Comment by QiTianDaShengMaoHuiFei** [comment]
![5aee97c9632b43849938fddeca303198](https://user-images.githubusercontent.com/34533687/201817348-ab3a7b4b-0bf1-4341-bbb4-6e376c32f961.png)

**Comment by daohu527** [comment]
Do you mean to replace the existing model with fast rcnn?
