### ISSUE TITLE
[Question]-Apollo source code build, deployed  and test in Hardware environment like Renesas environment

### ISSUE THREAD

**Issue by anilbommareddy** [ApolloAuto/apollo#14689]
Is Apollo source code can build on Ubuntu - deployed  and test in Hardware environment like Renesas environment(CPU-multi core) or Imx Processor?
example : In Renesas board connected-camera sensors or simulation like Canoe environment + Apollo-build source code- flash binaries to the Renesas board -check the runtime behavior like pedestrian or obstacle detection-may be performance will slow as no usage of GPU-parallel processing ?
is it feasible to deployed and test in Hardware environment ?if yes kindly what are steps need to be followed 
Reference link-https://www.openmp.org/blog/openmp-api-speeds-up-autonomous-driving-codes/

**Comment by daohu527** [comment]
This may need to consider hardware compatibility issues. You need to see if the hardware is x86 architecture, if so then consider replacing the GPU

**Comment by daohu527** [comment]
except the perception module, other modules will work well. Also you can do `inference` in cpu, but it will slow.

**Comment by anilbommareddy** [comment]
@daohu527  Able to build Apollov5 in the CPU environment and  launch Dream view.
Kindly let me know how to test each modules like planning,localization ,routing as independent  by using some test data or Dream view (simulation without using Hardware) .It gives the better understanding on the modules and the dependency's.

PS-I have environment issues in my workstation with Apollov6 and ApolloV7 branches So i checked with ApolloV5-branch. ,

**Comment by daohu527** [comment]
In general, you can simulate the input to test these modules, you can check the examples on the official website. https://apollo.baidu.com/community/Apollo-Homepage-Document/Apollo_Doc_CN_8_0
