### ISSUE TITLE
remote executor not work

### ISSUE THREAD

**Issue by csh2022** [ApolloAuto/apollo#14686]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: ubuntu18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: apollo6.0
- **Output of `apollo.sh config` if on `master` branch**:
![image](https://user-images.githubusercontent.com/24428215/202979450-2cc01bfc-4b37-4df2-a4fe-d31649a1d686.png)

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Hi, I add `--remote_executor` and `--remote_cache` address, but only `--remote_cache` woks, all action was built locally, can anyone give me some suggestions? thanks a lot!

- Here is a command sample. `bazel build --remote_executor=grpc://<ip1>:port1 --remote_cache=grpc://<ip2>:port2 //modules/audio/common:audio_gflags`

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/24428215/202980600-a0b38cfe-d55f-4ab0-a344-dccefd510846.png)

**Comment by daohu527** [comment]
I think you can ask the bazel repo first
