### ISSUE TITLE
LGSVL CAN NOT SUB /apollo/control！！！！！

### ISSUE THREAD

**Issue by sixiaixixiya** [ApolloAuto/apollo#14688]
Recently I had a problem that the LGSVL can not sub the topic /apollo/control. And the car can not move during the simulation test with apollo. I want to check the connection between Apollo and LGSVL. But I didn't find the right approach. Therefore, I need your help sincerely to solve or to go deep the problem.
![control](https://user-images.githubusercontent.com/104459086/203021670-33c72753-155d-4042-beab-bd3ceef37aec.png)
使用的是Apollo7.0，但是我在Apollo源码上修改了namespace apollo->namespace sixi以及Proto文件中的packege名字apollo.xxx->sixi.xxx，然后就无法与lgsvl软件联合仿真了。显示control模块的消息没有被接受到，apollo代码都没什么问题，可以编译并通过单元测试。希望有大佬可以指点一二！谢谢。

**Comment by daohu527** [comment]
You can't change the namespace, if you do, you need to modify both sides, apollo and lgsvl

**Comment by sixiaixixiya** [comment]
> You can't change the namespace, if you do, you need to modify both sides, apollo and lgsvl
Thanks for your comment, I already modified the namespaces on both sides but the problem still exits. I just changed the namespace apollo--->namespace sixi in the source code of LGSVL. And I built it with Unity3d 2020.3.41f1c1.

**Comment by daohu527** [comment]
then you should check if don't modify the namespace works, if it works then you should check step by step
