### ISSUE TITLE
[planning] How to bend a ADC trajectory

### ISSUE THREAD

**Issue by HyeonseopLim** [ApolloAuto/apollo#14696]
Hello, I am Vicky in Korea.
I am really thanks to Apollo team for sharing these amazing codes.
But I have some question while I use and edit some codes.
Please read this and help me how to handle it.

First, I use this code at Ubuntu 18.04 and this is 7.0 version, main branch.
The problem is that I want to make ADC trajectory bend but it's not work.
I thought that if I edit path bound and ADC trajectory will bend along the path bound because 
path bound is the width that ADC can pass inside but it didn't work at all.

What should I do if I want to make ADC trajectory bend in self lane?
I edited path bound in 'GenerateRegularPathBound' like this.

`GetBoundaryForNudge(reference_line_info, path_bound)`;
I added this function after '`GetBoundaryFromLanesAndADC`'

and the function that I made is this..

=============================================================
```
auto* nudge_status = injector_->planning_context()
                                ->mutable_planning_status()
                                ->mutable_nudge();

for (size_t i = 0; i < path_bound->size(); ++i) {
      double curr_s = std::get<0>((*path_bound)[i]);
      // if (curr_s > lane_change_start_s) {
      //   break;
      // }
      double curr_lane_left_width = 0.0;
      double curr_lane_right_width = 0.0;
      double offset_to_map = 0.0;
      reference_line.GetOffsetToMap(curr_s, &offset_to_map);
      if (reference_line.GetLaneWidth(curr_s, &curr_lane_left_width,
                                      &curr_lane_right_width)) {
        double offset_to_lane_center = 0.0;
        reference_line.GetOffsetToMap(curr_s, &offset_to_lane_center);
        curr_lane_left_width += offset_to_lane_center;
        curr_lane_right_width -= offset_to_lane_center;
      }
      curr_lane_left_width -= offset_to_map;
      curr_lane_right_width += offset_to_map;

      std::get<1>((*path_bound)[i]) = adc_frenet_l_ - 0.1;
      std::get<2>((*path_bound)[i]) = curr_lane_left_width;
}
```
================================================================
(At this time, I wanted to make ADC trajectory bend to left.)

**Comment by jilinzhouas** [comment]
1. Call RecordDebugInfo() function after your function
2. Enable PNC Monitor in dreamview, then you should be able to see to two dashed lines around the planned trajectory. Those two dashed lines represent left and right path boundary. You can get some ideas from there why the final trajectory does not change as you expected.
![Screenshot from 2022-12-02 09-55-11](https://user-images.githubusercontent.com/54330460/205321070-1755d4cf-3cda-4f3c-b2ca-45df251bb475.png)

**Comment by HyeonseopLim** [comment]
Should I handle reference line? because It seems like be in the middle of trajectory..

**Comment by HyeonseopLim** [comment]
> 1. Call RecordDebugInfo() function after your function
> 2. Enable PNC Monitor in dreamview, then you should be able to see to two dashed lines around the planned trajectory. Those two dashed lines represent left and right path boundary. You can get some ideas from there why the final trajectory does not change as you expected.
>    ![Screenshot from 2022-12-02 09-55-11](https://user-images.githubusercontent.com/54330460/205321070-1755d4cf-3cda-4f3c-b2ca-45df251bb475.png)

Should I handle reference line? because It seems like be in the middle of trajectory..

**Comment by HyeonseopLim** [comment]
I think I need to edit reference point. because the path points which are optimized at the end will be fit to certain value and I think the value is the reference points. we have to calculate cost between optimized value and expected value. so, the expected value is the reference point.
When I move the reference point to left, I think trajectory move to left too.

**Comment by HyeonseopLim** [comment]
I have solved it finally!
