### ISSUE TITLE
关于单目相机障碍物检测3D center坐标计算

### ISSUE THREAD

**Issue by ycdhqzhiai** [ApolloAuto/apollo#14692]
请教下，查阅了相关2DBox计算3D 坐标相关代码，在计算center X方向坐标时候，使用以下方法，
https://github.com/ApolloAuto/apollo/blob/aa0c5eb66189b86a724206305712cfb337c07619/modules/perception/common/i_lib/geometry/i_util.h#L165

我想问下，当depth距离比较大时，2Dbox在图像中位置变化很小，这就导致x[0] - K[2]基本没变化，所以当障碍物距离自车比较远时候，这个方法计算的center X 方向误差会很大，请教下各位有什么方法可以提高精度

**Comment by daohu527** [comment]
No, there seems to be no good solution, the error will indeed increase with the distance.
