### ISSUE TITLE
[Planning] ADC speed when It is on the lane bend a lot.

### ISSUE THREAD

**Issue by HyeonseopLim** [ApolloAuto/apollo#14695]
**Is your feature request related to a problem? Please describe.**
ADC has too low speed when it turns.

**Describe the solution you'd like**
Decrease kappa weight in planning_config.pb.txt when it has low speed.
make a variable and make it changable along the ADC velocity.
the variable will be 1.0 at high speed of ADC and it will be between 0.5~1.0 when ADC has low speed.
multiple the variable and kappa weight.
and then, kappa weight will be low a little bit when ADC has low speed.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by qwetqwe** [comment]
You can change kappa weight in speed optimizer. what's more, you can also increase speed limit when turning (max_centric_acceleration_limit in planning_config.pb.txt)
