### ISSUE TITLE
[Question]Autoware deployed in Autosar on yocto or QNX? 

### ISSUE THREAD

**Issue by ashkildighin** [ApolloAuto/apollo#14707]
Autoware source can deployed in Autosar(like Adaptive Autosar;https://www.autosar.org/standards/adaptive-platform/) build on Yocto or QNX build-run on Hardware on QUALCOMM boards .to test ADAS features like object detection?

**Comment by daohu527** [comment]
I'm afraid you should ask in the autoware community
