### ISSUE TITLE
多个物理机通过CYBER_IP进行socket通信

### ISSUE THREAD

**Issue by hailonghu** [ApolloAuto/apollo#14708]
多个物理机通过CYBER_IP进行socket通信时，如何限制本机向另一个物理机发送的channel，使部分channel仅在本机内可见，避免过多的网络带宽占用？

**Comment by daohu527** [comment]
如果你不订阅这些消息，那么就不会占用带宽

**Comment by hailonghu** [comment]
> 如果你不订阅这些消息，那么就不会占用带宽

如果我使用cyber_monitor，是不是意味着所有消息都会被订阅？因为我在一台物理机内发布数据，另一台物理机使用cyber_monitor时发现所有数据都被接收了，网络带宽占用很大，谢谢。

**Comment by fengmao31** [comment]
这个需要底层封装不同的域接口。但是apollo是个老项目了。fastdds才到15。现在已经29了。其实很难去改动了。即时ros2也没有提供这样的域封装。

**Comment by daohu527** [comment]
The subscription publishing mechanism is far more complicated than imagined, and this is not a new technology. There were various implementations 20 years ago.

fastrtps is an implementation of dds protocol, we will continue to optimize cyber to update the performance and experience of autonomous driving
