### ISSUE TITLE
Is the Apollo 1.0 version still supported ?

### ISSUE THREAD

**Issue by Flaoting** [ApolloAuto/apollo#14701]
### System information

- **Linux Ubuntu 20.04**:
- **Apollo installed from source**:
- **Apollo version 1.0**:

### Steps to reproduce the issue:
- **I want to use Apollo 1.0, but met a number of errors while build from source, Is the Apollo 1.0 version still supported?**:
- Now the main obstacle is can't use dreamview in chrome.

**Comment by daohu527** [comment]
No, I guess no one is familiar with this version for now!

**Comment by Flaoting** [comment]
> No, I guess no one is familiar with this version for now!
Thanks for your reply! All errors resolved finally! I run successfully on Ubuntu with 32GB memory.

**Comment by daohu527** [comment]
good news! Then I will close this issue
