### ISSUE TITLE
About Apollo’s V2X module 

### ISSUE THREAD

**Issue by MarioAlmelaUMH** [ApolloAuto/apollo#14709]
I’ve seen that Apollo has a V2X module that can communicate with an RSU (according to: [https://developer.apollo.auto/v2x/index.html](https://urldefense.com/v3/__https://developer.apollo.auto/v2x/index.html__;!!D9dNQwwGXtA!TDA85GUOwt6xnY97baONVAsOflYbF4H-ILFfhUZiz8hN8SHiTflScyzvbGlh78k6BwH686znaVslQSrjRdh-_g$)). However I can’t find any documentation or guide to set up and use this V2X module in Apollo. Where could I find it (if it exists)?

I assume that the V2X module is a software component that interfaces with an external V2X hardware (radio unit). Am I right? Is there a list of compatible V2X radio units? Would it be possible to somehow simulate or emulate the V2X radio unit?

Finally, I’ve seen the V2X object struct at [https://github.com/ApolloAuto/apollo/blob/master/modules/v2x/fusion/libs/common/v2x_object.h](https://urldefense.com/v3/__https://github.com/ApolloAuto/apollo/blob/master/modules/v2x/fusion/libs/common/v2x_object.h__;!!D9dNQwwGXtA!TDA85GUOwt6xnY97baONVAsOflYbF4H-ILFfhUZiz8hN8SHiTflScyzvbGlh78k6BwH686znaVslQSpT9CNfjg$), and also the V2X Fusion Component at [https://github.com/ApolloAuto/apollo/blob/master/modules/v2x/fusion/apps/v2x_fusion_component.cc](https://urldefense.com/v3/__https://github.com/ApolloAuto/apollo/blob/master/modules/v2x/fusion/apps/v2x_fusion_component.cc__;!!D9dNQwwGXtA!TDA85GUOwt6xnY97baONVAsOflYbF4H-ILFfhUZiz8hN8SHiTflScyzvbGlh78k6BwH686znaVslQSro6a0H8w$), with writers and listeners that remind me of ROS nodes. However, I am not sure about how the V2X module interacts with the Perception module. Are they connected via ROS? Are the V2X objects used (fused) in the perception pipeline so that the control module reacts to the received V2X objects?

Thank you in advance.

**Comment by lurenhua0122** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by daohu527** [comment]
> I’ve seen that Apollo has a V2X module that can communicate with an RSU (according to: [https://developer.apollo.auto/v2x/index.html](https://urldefense.com/v3/__https://developer.apollo.auto/v2x/index.html__;!!D9dNQwwGXtA!TDA85GUOwt6xnY97baONVAsOflYbF4H-ILFfhUZiz8hN8SHiTflScyzvbGlh78k6BwH686znaVslQSrjRdh-_g$)). However I can’t find any documentation or guide to set up and use this V2X module in Apollo. Where could I find it (if it exists)?

No, apollo is just communicate with OBU, it not contain RSU.

> I assume that the V2X module is a software component that interfaces with an external V2X hardware (radio unit). Am I right? Is there a list of compatible V2X radio units? Would it be possible to somehow simulate or emulate the V2X radio unit?

v2x is a standard, you can install any device that meets this standard

> However, I am not sure about how the V2X module interacts with the Perception module. Are they connected via ROS? Are the V2X objects used (fused) in the perception pipeline so that the control module reacts to the received V2X objects?

apollo use cyber to communicate, the perception module fuses the data from v2x and then sends the message to the planning module.
