### ISSUE TITLE
how to merge cyber dynamic libraries (so many .so) built by bazel

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#14706]
I have some app linked on cyber. But if cyber internally changed, I have to rebuild my app again and again. Because cyber have divided into so many dynamic libraries.

**Comment by daohu527** [comment]
Yes, you can use a workaround to generate a single so.


There is a example in beta
https://github.com/ApolloAuto/apollo/blob/6b5b344c90b285956fec5b4e08aa70b5b8aa5cc6/cyber/BUILD#L100-L108

**Comment by WildBeast114514** [comment]
Actually in Apollo beta version, cyber dynamic libraries have been packed into a singel share library:

**Comment by WildBeast114514** [comment]
Actually in Apollo beta version, cyber dynamic libraries have been packed into a singel share library:
```
cc_library(
    name = "cyber_core",
    srcs = ["libcyber_core.so"],
    hdrs = ["cyber.h"],
    linkopts = ["-lrt"],
    visibility = ["//visibility:public"],
    deps = [ all target in cyber... ]
)

cc_binary(
    name = "libcyber_core.so",
    srcs = glob([
        "cyber.cc",
        "cyber.h",
        ]),
    linkshared = True,
    linkstatic = True,
    linkopts = ["-lrt"],
    deps = [ all target in cyber... ]
)
```
in your project, you can simply depend on this target: "cyber_core" can resolve your problem.

btw, Apollo beta provide a new way to depend the specify modules of module, which call package manager. You can chekout the detail if you are interesting in it: https://apollo.baidu.com/community/Apollo-Homepage-Document/Apollo_Doc_CN_8_0?doc=%2F%25E5%25AE%2589%25E8%25A3%2585%25E8%25AF%25B4%25E6%2598%258E%2F%25E8%25BD%25AF%25E4%25BB%25B6%25E5%258C%2585%25E5%25AE%2589%25E8%25A3%2585%2FQuickStart-%25E8%25BD%25AF%25E4%25BB%25B6%25E5%258C%2585%25E6%2596%25B9%25E5%25BC%258F
