### ISSUE TITLE
AdjustRelativeTimeAndS error in open_space_trajectory_partition.cc

### ISSUE THREAD

**Issue by congleetea** [ApolloAuto/apollo#14715]
https://github.com/ApolloAuto/apollo/blob/aa0c5eb66189b86a724206305712cfb337c07619/modules/planning/tasks/optimizers/open_space_trajectory_partition/open_space_trajectory_partition.cc#L750

when FLAGS_use_iterative_anchoring_smoother == true， not call  *InterpolateTrajectory()* function, so should be changed to :

```  if (!FLAGS_use_iterative_anchoring_smoother) {
    const size_t interpolated_pieces_num =
        open_space_trajectory_partition_config_.interpolated_pieces_num();
    index_estimate /= interpolated_pieces_num;
  }
````

**Comment by qwetqwe** [comment]
it is used for distance approach algorithm
