### ISSUE TITLE
cyberRT error

### ISSUE THREAD

**Issue by zhoujixiang** [ApolloAuto/apollo#14716]
hello everyone! I have a connection problem with apollo and lgsvl

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 7.0
- **Output of `apollo.sh config` if on `master` branch**: master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
when i use pythonapi communication, there was such a problem,and my cyber_monitor did not show control signal, i encountered it suddenly, i was running fine yesterday.

### Supporting materials (screenshots, command lines, code/script snippets):
![2022-12-09 20-50-41 的屏幕截图](https://user-images.githubusercontent.com/50269643/206706701-5c2af11d-2615-4ad5-b961-06b04b22cf86.png)
![2022-12-09 20-50-28 的屏幕截图](https://user-images.githubusercontent.com/50269643/206706713-e7760b96-8048-41cd-be76-f9a09da1e07c.png)

**Comment by daohu527** [comment]
This error appears to be a message mismatch, lgsvl is no longer maintained.
