### ISSUE TITLE
IMU measurement time not matching timestamp

### ISSUE THREAD

**Issue by rtzu6** [ApolloAuto/apollo#14717]
**Describe the bug**
In cyber_monitor, when investigating IMU data (/apollo/sensor/gnss/imu) produced by lgsvl, the measurement time does not match the timestamp. The timestamp starts with 167058 (epoch here), the measurement time starts with 135462. 

**To Reproduce**
1. Create an lgsvl simulation. I used `Borregas Ave` map, `Lincoln2017MKZ` car and I tried both `Apollo 6.0 (modular testing)` as well as `Apollo R7.0 - full-analysis - ty` configs.
2. Run it on your machine and enable the bridge.
3. Check the cyber_monitor. All timestamps are epoch, except IMU.

**Expected behavior**
This should also probably be epoch.

**Screenshots**
![imu](https://user-images.githubusercontent.com/69627720/206737320-ed23115e-3d28-47c3-bdc9-0fd9374f5c83.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
I stumbled across this problem while trying to setup [MSF](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md) on my machine. Currently, I am facing the same problem as in #13027, whose screenshots also show the time discrepancy for `best_pos`. Could this problem stem from the aforementioned time discrepancy? Otherwise, how should I proceed to debug this problem, as, according to #5969 , there is no plan to open source this component?

**Comment by rtzu6** [comment]
After checking a bit more, this seems to be a difference in time encoding on the simulator side. The timestamp is in epoch, the measurement time in GPS time. For more information see [here](https://github.com/lgsvl/simulator/issues/437).

**Comment by boyang9602** [comment]
In the code comment, it mentioned that 
[`// The time of IMU measurement, seconds since the GPS epoch (Jan 6, 1980).` ](https://github.com/ApolloAuto/apollo/blob/master/modules/common_msgs/sensor_msgs/imu.proto#L13), so I think it is different from the timestamp in header.
