### ISSUE TITLE
Code quality is of great concern.

### ISSUE THREAD

**Issue by SushiStar** [ApolloAuto/apollo#14712]
I've noticed that a lot of code in planning just works functionally, but redundant and of low efficiency.
E.g.: https://github.com/ApolloAuto/apollo/blob/master/modules/planning/planner/rtk/rtk_replay_planner.cc#L80
If you've got extra time, developers and reviewers, please be more careful about the code you merged into main branch.
Appreciate your hard work and time!

**Comment by daohu527** [comment]
Yes, we do need to ensure code quality. But I didn't understand your example, what's wrong here

**Comment by SushiStar** [comment]
` complete_rtk_trajectory_.size() < 2` will suffice, there’s no need for the first condition right? There’re some things like this in the code.

**Comment by daohu527** [comment]
You are right, but it doesn't affect much. Strictly speaking, empty and size < 2 are not the same.
