### ISSUE TITLE
Is it possible to publish not all channels, but selective channels between two PCs?

### ISSUE THREAD

**Issue by hailonghu** [ApolloAuto/apollo#14711]
Hi all!
I am using Apollo pre6  
I am running Apollo on two parallel PCs according to this [instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_setup_dual_ipc.md).  
But I notice the following peculiarity. The frequency of published channels by computer # 1 does not match the frequency of this channel on computer # 2. For example, if the frequency of the channel "/ apollo / sensor / lidar128 / compensator / PointCloud2" on PC1 is 10 Hz, then the frequency on PC2 can be 6 Hz. I also noticed a feature that big data channels slow down the work of another PC.  

So I have a question.  
Is it possible to publish not all channels, but selective channels between two PCs?

_Originally posted by @AlexandrZabolotny in https://github.com/ApolloAuto/apollo/issues/7995#issuecomment-892779799_

**Comment by daohu527** [comment]
Actually if you don't subscribe to the message, it won't send. Big messages do take up bandwidth, but I don't think it should be as slow as you say.

For example, if your network cable is 100M Byte/s, then to achieve 10Hz, you need to limit the data to 10M

**Comment by ryanyej** [comment]
same experience here,  pc1 normal frenquency, pc2 sometimes can show 0 hz in few seconds around same channel. very confusing
