### ISSUE TITLE
Question about modules\planning\open_space\coarse_trajectory_generator\hybrid_a_star.cc

### ISSUE THREAD

**Issue by InterKnight** [ApolloAuto/apollo#14720]
Thank you for great job!

I am new in digging into apollo and have a question about modules\planning\open_space\coarse_trajectory_generator\hybrid_a_star.cc.

1. 
I found you defined step_size_ from configuration file which is 0.25 By default
`step_size_ = planner_open_space_config_.warm_start_config().step_size();
`
but it should be V*dt which is not a constant value
So might I assume you think V*dt = 0.25 ？

2.
In function HybridAStar::CalculateNodeCost , why just calculate holonomic-with-obstacles (from dp map), but no non-holonomic-without-obstacles (may use reeds shepp) ?

3.
In function HybridAStar::GenerateSpeedAcceleration,  you used 3 points (i-1, i, i+1) to calculate discrete_v, but only use 2 points (i, i+1) to calculate discrete_a, why?

**Comment by qwetqwe** [comment]
1. what do you mean vdt?
2. HybridAStar::CalculateNodeCost  is used as a heuristic function, obstacles should be considered. In hybrid A* we use  non-holonomic model to extend point.
3. in hybrid A star just generate a coarse trajectory and as a warm start for smooth algorithm

**Comment by InterKnight** [comment]
> 1. what do you mean vdt?
> 2. HybridAStar::CalculateNodeCost  is used as a heuristic function, obstacles should be considered. In hybrid A* we use  non-holonomic model to extend point.
> 3. in hybrid A star just generate a coarse trajectory and as a warm start for smooth algorithm

sorry, it's  v * dt

**Comment by qwetqwe** [comment]
Generally, hybrid a* only plans a coarse path, not considering speed. and the path will be resampled and speed will be planned in iterative anchoring smooth algorithm.
