### ISSUE TITLE
How to convert carla map to apollo format?

### ISSUE THREAD

**Issue by JasonBourne1998** [ApolloAuto/apollo#14728]
Is there any way to convert the opendrive map format like carla's town06.xodr to apollo's HD map format (base_map.bin)?

**Comment by daohu527** [comment]
You can try [imap](https://github.com/daohu527/imap), or use roadrunner do the convert

**Comment by JasonBourne1998** [comment]
> You can try [imap](https://github.com/daohu527/imap), or use roadrunner do the convert

Thanks for your advice, and I used Unity to convert it, it works temporarily.

**Comment by WilliaJing** [comment]
> 

@JasonBourne1998 What is Unity? Can you use Unity to convert maps and run them on Apollo? Can you tell me the address

**Comment by MeYuChen** [comment]
+1
