### ISSUE TITLE
[Question]-Apollo modules ported and test in Hardware like Qualcomm boards?

### ISSUE THREAD

**Issue by ashkildighin** [ApolloAuto/apollo#14726]
Apollo has logical or core modules(https://github.com/ApolloAuto/apollo/tree/master/modules) for autonomously driving i.e modules "perception(GPU), prediction, routing, localization, Map, Planning, Control, CanBus".
Is this module can be ported (one by one based on module dependency wise-without the docker envirnoment ) and test in the Hardware Qualcomm board?

(a) it will help in Performance Measurement or HotSpot Analysis-ADAS use cases (focused on the CPU side).
(b) Based on Performance analysis results how many cores need to be required or memory upgrade- for the sample use case of ADAS like objection detection or lane warning? 
Kindly recommend which Apollo version is helpful for this exercise on the Hardware Qualcomm board

**Comment by daohu527** [comment]
The arm platform is currently only partially supported, and may require further adaptation by the user.
