### ISSUE TITLE
Can't enter Apollo 7.0

### ISSUE THREAD

**Issue by JasonBourne1998** [ApolloAuto/apollo#14722]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:Linux Ubuntu 20.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- Can't enter Apollo 7.0, I have downloaded the latest Apollo package, but the date displays its version is still 6.0. 

### Supporting materials (screenshots, command lines, code/script snippets):
![1670922574266](https://user-images.githubusercontent.com/51346614/207275296-34926e4f-9794-46e7-9fa7-375f586f4452.png)

**Comment by daohu527** [comment]
According to the picture, the download of the map docker volume is not successful, you can use the -f command to skip downloading some containers and speed up it

**Comment by JasonBourne1998** [comment]
> According to the picture, the download of the map docker volume is not successful, you can use the -f command to skip downloading some containers and speed up it

Got your point, but my Apollo version is still 6.0 with the -f suff.
![1670925960978](https://user-images.githubusercontent.com/51346614/207288538-c5ab52a6-8d78-4051-a185-f9cbed92d270.png)

**Comment by daohu527** [comment]
You should check you code is newer or check the `dev_start.sh` script with apollo 7.0

**Comment by JasonBourne1998** [comment]
> You should check you code is newer or check the `dev_start.sh` script with apollo 7.0

1. Thanks so much for your guidance, but I have compared my script with the official source code Apollo 7.0 script. I didn't find there  is a difference. 
2. And I am so curious about how to classify the Apollo version is 6.0 or 7.0.
ps: I have attached my script. I would appreciate for it if you could take a look at it.
[dev_start.zip](https://github.com/ApolloAuto/apollo/files/10223503/dev_start.zip)

**Comment by daohu527** [comment]
@JasonBourne1998 Apollo code is managed by git, you can use git checkout to switch versions
