### ISSUE TITLE
The meaning of the Yolo's outputs: lof_data, lor_data

### ISSUE THREAD

**Issue by YCC-324** [ApolloAuto/apollo#14724]
Hello, I couldn't find the meaning of lof_data, lor_data? 
Also, for the model in [3d-r4-half](https://github.com/ApolloAuto/apollo/tree/29bdcbe5d10ea73ee223aeaa5c81ec384f1c11fa/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-r4-half), it doesn't output these two elements. How could I draw the detection box using the outputs?

**Comment by daohu527** [comment]
You can use `det1_obj_blob: "obj_pred"`
