### ISSUE TITLE
Cost Effective HD Map Production; Apollo partner contact Information

### ISSUE THREAD

**Issue by jp12AI** [ApolloAuto/apollo#14736]
Hello everyone, 

I have developed software that uses satellite imagery to generate highly detailed HD maps. This method of HD map production has multiple benefits including lower costs ($28 per square mile) and more scalability for map-based self-driving technology. As a result of this innovation, I have formed a company called AVSmaping (Autonomous Vehicle Systems) based in Sacramento, California that provides HD mapping services to self-driving companies looking to expand their service area for autonomous taxi users in the United States. Our software currently produces satisfactory unannotated results. I have closely tracked the progress of the open-source apollo self-driving car project since v5.0. I also was an early contributor to openpilot another open-source level 2 software. I think the Apollo project and testing operations would benefit from my software. I am looking for contact information to contact the U.S. apollo operation/testing center or HQ. Can someone provide me with a phone number and e-mail address that is appropriate for this specific inquiry? Guidance on contact information is appreciated. Thank you.

**Comment by daohu527** [comment]
In view of your business needs, it is recommended that you contact the official website contact information https://www.apollo.auto/contactus
