### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by Luna86** [ApolloAuto/apollo#1473]
When I follow the instructions here [https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide](url) the maps and vehicles are not showing up in the dreamviewer. Only an empty dashboard with a line of text saying 

> Please send car initial position and map data.

**Comment by ahuer2435** [comment]
有执行"rosbag play -l ./docs/demo_guide/demo_1.5.bag"？执行正常吗？

**Comment by lianglia-apollo** [comment]
I apologize for this issue. It seems that there is something wrong with the demo bag and we will fix it asap.

**Comment by Luna86** [comment]
@ahuer2435  Yes, I can play the rosbag without any problem. @lianglia-apollo Thanks please keep me updated.

**Comment by lianglia-apollo** [comment]
The documents have been updated. @Luna86 @ahuer2435
