### ISSUE TITLE
Failed to start Dreamview

### ISSUE THREAD

**Issue by huigang39** [ApolloAuto/apollo#14730]
### System information

- **OS Platform and Distribution**: WSL2 Ubuntu 18.04
- **Apollo installed from**: aem
- **Apollo version**: 8.0

### Steps to reproduce the issue:

Executing `aem bootstrap start` reports an error

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/63324254/209980943-ceaa3830-46a7-404f-b35d-99dad3106168.png)

**LOG:**
/opt/apollo/neo/data/log/dreamview.log: 
```
Log file created at: 2022/12/29 21:39:42
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1229 21:39:42.809520 16333 hmi_worker.cc:178] Loaded HMI config: modes {
  key: "Camera-Lidar Sensor Calibration"
  value: "/apollo/modules/dreamview/conf/hmi_modes/camera-Lidar_sensor_calibration.pb.txt"
}
modes {
  key: "Car Teleop"
  value: "/apollo/modules/dreamview/conf/hmi_modes/car_teleop.pb.txt"
}
modes {
  key: "Console Teleop"
  value: "/apollo/modules/dreamview/conf/hmi_modes/console_teleop.pb.txt"
}
modes {
  key: "Dev Kit Close Loop"
  value: "/apollo/modules/dreamview/conf/hmi_modes/dev_kit_close_loop.pb.txt"
}
modes {
  key: "Dev Kit Debug"
  value: "/apollo/modules/dreamview/conf/hmi_modes/dev_kit_debug.pb.txt"
}
modes {
  key: "Ipc1 Mkz Close Loop"
  value: "/apollo/modules/dreamview/conf/hmi_modes/ipc1_mkz_close_loop.pb.txt"
}
modes {
  key: "Ipc1 Mkz Standard Debug"
  value: "/apollo/modules/dreamview/conf/hmi_modes/ipc1_mkz_standard_debug.pb.txt"
}
modes {
  key: "Ipc2 Mkz Close Loop"
  value: "/apollo/modules/dreamview/conf/hmi_modes/ipc2_mkz_close_loop.pb.txt"
}
modes {
  key: "Ipc2 Mkz Standard Debug"
  value: "/apollo/modules/dreamview/conf/hmi_modes/ipc2_mkz_standard_debug.pb.txt"
}
modes {
  key: "Lidar-IMU Sensor Calibration"
  value: "/apollo/modules/dreamview/conf/hmi_modes/lidar-IMU_sensor_calibration.pb.txt"
}
modes {
  key: "Map Collection"
  value: "/apollo/modules/dreamview/conf/hmi_modes/map_collection.pb.txt"
}
modes {
  key: "Mkz 64beam"
  value: "/apollo/modules/dreamview/conf/hmi_modes/mkz_64beam.pb.txt"
}
modes {
  key: "Mkz Close Loop"
  value: "/apollo/modules/dreamview/conf/hmi_modes/mkz_close_loop.pb.txt"
}
modes {
  key: "Mkz Lgsvl"
  value: "/apollo/modules/dreamview/conf/hmi_modes/mkz_lgsvl.pb.txt"
}
modes {
  key: "Mkz Standard Debug"
  value: "/apollo/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt"
}
modes {
  key: "Mkz Standard Debug Hesai"
  value: "/apollo/modules/dreamview/conf/hmi_modes/mkz_standard_debug_hesai.pb.txt"
}
modes {
  key: "Mkz Standard Debug Smart Recorder"
  value: "/apollo/modules/dreamview/conf/hmi_modes/mkz_standard_debug_smart_recorder.pb.txt"
}
modes {
  key: "Navigation"
  value: "/apollo/modules/dreamview/conf/hmi_modes/navigation.pb.txt"
}
modes {
  key: "Rtk"
  value: "/apollo/modules/dreamview/conf/hmi_modes/rtk.pb.txt"
}
modes {
  key: "Vehicle Calibration"
  value: "/apollo/modules/dreamview/conf/hmi_modes/vehicle_calibration.pb.txt"
}
maps {
  key: "Apollo Virutal Map"
  value: "/apollo/modules/map/data/apollo_virutal_map"
}
maps {
  key: "Borregas Ave"
  value: "/apollo/modules/map/data/borregas_ave"
}
maps {
  key: "Demo"
  value: "/apollo/modules/map/data/demo"
}
maps {
  key: "San Mateo"
  value: "/apollo/modules/map/data/san_mateo"
}
maps {
  key: "Sunnyvale"
  value: "/apollo/modules/map/data/sunnyvale"
}
maps {
  key: "Sunnyvale Big Loop"
  value: "/apollo/modules/map/data/sunnyvale_big_loop"
}
maps {
  key: "Sunnyvale Loop"
  value: "/apollo/modules/map/data/sunnyvale_loop"
}
maps {
  key: "Sunnyvale With Two Offices"
  value: "/apollo/modules/map/data/sunnyvale_with_two_offices"
}
vehicles {
  key: "Apollo Perception Test Bev"
  value: "/apollo/modules/calibration/data/apollo_perception_test_bev"
}
vehicles {
  key: "Lincoln2017MKZ LGSVL"
  value: "/apollo/modules/calibration/data/Lincoln2017MKZ_LGSVL"
}
vehicles {
  key: "Mkz Example"
  value: "/apollo/modules/calibration/data/mkz_example"
}
vehicles {
  key: "Perception Test V1"
  value: "/apollo/modules/calibration/data/perception_test_v1"
}
```

/opt/apollo/neo/data/log/monitor.log: 
```
Log file created at: 2022/12/29 21:39:42
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1229 21:39:42.801025 16333 class_loader_utility.h:79] registerclass:Monitor,apollo::cyber::ComponentBase,/opt/apollo/neo/packages/monitor-dev/latest/lib/libmonitor.so
E1229 21:39:43.313028 16351 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:43.811604 16338 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:44.313585 16342 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:44.813650 16340 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:45.313628 16343 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:45.813591 16342 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:46.313592 16347 monitor_manager.cc:54] No HMIStatus was received.
E1229 21:39:46.813617 16350 monitor_manager.cc:54] No HMIStatus was received.
......
```

**Comment by WildBeast114514** [comment]
At present, apollo in wsl2 has not been tested, and it may cause problems in operation. We recommend that you install apollo under the following two conditions:
1. Install ubuntu system natively
2. Use a virtual machine to install ubuntu system in windows

**Comment by huigang39** [comment]
> At present, apollo 8.0 in wsl2 has not been tested, and it may have some problems in operation. We recommend that you install apollo under the following two conditions:
> 
> 1. Install ubuntu system natively
> 2. Use a virtual machine to install ubuntu system in windows
> 
> if you really want to use apollo in wsl2, you can try the following steps:
> 
> 1. vim /opt/apollo/neo/packages/env-manager-dev/latest/scripts/dev_start_neo.sh
> 2. replace "--net host" with "-p 8888:8888"
> 3. vim /opt/apollo/neo/packages/env-manager-dev/latest/scripts/bootstrap_neo.sh
> 4. replace DREAMVIEW_URL="http://localhost:8888" with DREAMVIEW_URL="http://0.0.0.0:8888"
> 5. exit the container
> 6. run "aem start -f" to delete the current container and start a new one
> 7. use "aem enter" to enter this new container
> 8. install dreamview and start it to check if it works

Just replace `--net host` with `-p 8888:8888`, which is supposed to be the reason why Docker Desktop does not support host networks.

![image](https://user-images.githubusercontent.com/63324254/210033805-d0ae8e8d-3dec-4ab1-ba2a-09a0348be67e.png)

**Comment by alhezmi72** [comment]
I installed Apollo 8.0 in an Ubuntu virtual machine and tried going through the   [https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/apollo_8_0_quick_start.md](Apollo 8.0 Quick Start Guide) and updated the ports and DreamView IP:Port as per the recommendation stated above, but I got the same error message:
`[ERROR] Failed to start Dreamview. Please check /opt/apollo/neo/data/log/dreamview.log or /opt/apollo/neo/data/log/monitor.log for more information
` 
<img width="1418" alt="image" src="https://github.com/ApolloAuto/apollo/assets/34920993/23814d0c-fc72-4e47-a1ea-a3bae766f5f5">

Output of the log file: /opt/apollo/neo/data/log/dreamview-dev.log 

`[ESC[1;32mcyber_launch_23165ESC[0m] ESC[1;32mINFO Launch file [/opt/apollo/neo/packages/dreamview-dev/latest/launch/dreamview.launch]ESC[0m
[ESC[1;32mcyber_launch_23165ESC[0m] ESC[1;32mINFO ========================================================================================================================ESC[0m
[ESC[1;32mcyber_launch_23165ESC[0m] ESC[1;32mINFO Load module [dreamview] binary: [dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt] [CYBER_DEFAULT] conf: [] exception_handler: [respawn]ESC[0m
[ESC[1;32mcyber_launch_23165ESC[0m] ESC[1;32mINFO Start process [dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt] successfully. pid: 23167ESC[0m
[ESC[1;32mcyber_launch_23165ESC[0m] ESC[1;32mINFO ------------------------------------------------------------------------------------------------------------------------ESC[0m
 `

Output of the log file: /opt/apollo/neo/data/log/monitor-dev.log

`[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO Launch file [/opt/apollo/neo/packages/monitor-dev/latest/launch/monitor.launch]ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO ========================================================================================================================ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO Load module [monitor] library: [monitor] [CYBER_DEFAULT] conf: [/apollo/modules/monitor/dag/monitor.dag] exception_handler: []ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO Start process [monitor] successfully. pid: 23178ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO ------------------------------------------------------------------------------------------------------------------------ESC[0m
[ESC[1;31mcyber_launch_23176ESC[0m] ESC[1;31mERROR Process [monitor] has died [pid 23178, exit code -4, cmd mainboard -d /apollo/modules/monitor/dag/monitor.dag -p monitor -s CYBER_DEFAULT].ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO All processes has died.ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO Cyber exit.ESC[0m
[ESC[1;32mcyber_launch_23176ESC[0m] ESC[1;32mINFO All processes have been stopped.ESC[0m
`

**Comment by yaobaishen** [comment]
> > At present, apollo 8.0 in wsl2 has not been tested, and it may have some problems in operation. We recommend that you install apollo under the following two conditions:
> > 
> > 1. Install ubuntu system natively
> > 2. Use a virtual machine to install ubuntu system in windows
> > 
> > if you really want to use apollo in wsl2, you can try the following steps:
> > 
> > 1. vim /opt/apollo/neo/packages/env-manager-dev/latest/scripts/dev_start_neo.sh
> > 2. replace "--net host" with "-p 8888:8888"
> > 3. vim /opt/apollo/neo/packages/env-manager-dev/latest/scripts/bootstrap_neo.sh
> > 4. replace DREAMVIEW_URL="http://localhost:8888" with DREAMVIEW_URL="http://0.0.0.0:8888"
> > 5. exit the container
> > 6. run "aem start -f" to delete the current container and start a new one
> > 7. use "aem enter" to enter this new container
> > 8. install dreamview and start it to check if it works
> 
> Just replace `--net host` with `-p 8888:8888`, which is supposed to be the reason why Docker Desktop does not support host networks.
> 
> ![image](https://user-images.githubusercontent.com/63324254/210033805-d0ae8e8d-3dec-4ab1-ba2a-09a0348be67e.png)

To whom encounter this issue with apollo 9.0, just do as the solution above: replace `--net host` with `-p 8888:8888`. In my case I have to "aem start -f", "aem enter", and **build the core again** "buildtool build -p core", and then then dreamview plus can be used by "aem bootstrap start --plus"
