### ISSUE TITLE
Lattice算法借道绕行咨询

### ISSUE THREAD

**Issue by ycdhqzhiai** [ApolloAuto/apollo#14740]
场景：
双向直行车道，前方出现障碍物，需要借道绕行

在调试过程发现，由于routing结果不存在变道，只会生成一条参考线，而Lattice算法生成轨迹的过程中，是基于参考线来实现的，也就是说在绕行障碍物过程中，都是基于障碍物所在车道进行绕行的，这样就不存在借道了，是否可以这样理解

**Comment by qianwanlee** [comment]
前面障碍物block了，肯定还是得借道啊，参考线不变，但是bound会变。对应lattice的话就是横向采样的范围扩大了。
