### ISSUE TITLE
How to extract obstacles info from cyber_record outputs?

### ISSUE THREAD

**Issue by Creling** [ApolloAuto/apollo#14745]
Hi,

It seems that ~`cyber_record`~ `cyber_recorder` could record per frame obstacles informations to bag files. Is it possible to extract these informations? if not, how dose ~`cyber_record`~ `cyber_recorder` organizes these informations and what should I do if I want to write a parser?

**Comment by Creling** [comment]
https://github.com/ApolloAuto/apollo/issues/14100

**Comment by daohu527** [comment]
Yes, the tool is `cyber_recorder`. You can use 3 method to parser the record file.

1. use c++ api, there is a example in `modules/localization/msf/local_tool/data_extraction`
2. use python api, there is a example in `modules/tools/record_analyzer/tools/dump_message.py`
3. or use `cyber_record` python tool.

In general, the python version of the tool is more convenient to use, c++ api is more efficient, and `cyber_record` is an independent tool that can be run directly on the computer.
```
cyber_record echo -f example.record.00000 -t /apollo/canbus/chassis
```
more info you can found [here](https://github.com/daohu527/cyber_record)

**Comment by Creling** [comment]
@daohu527  Well, amazing! Thank you for your tips. I will dig into it.
