### ISSUE TITLE
how to visualize the localization result in Apollo(like ROS rviz tool)

### ISSUE THREAD

**Issue by jdcllh** [ApolloAuto/apollo#14744]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0): 6.0

**Comment by daohu527** [comment]
The current position and orientation of the car is the display for localization. 

We may support detailed display of localization information in the future, such as trajectory, confidence, etc. Of course, we currently do not support display these info.
