### ISSUE TITLE
What is new about PnC simulation Service?

### ISSUE THREAD

**Issue by YuqiHuai** [ApolloAuto/apollo#14757]
From the [Apollo v8.0.0 release](https://github.com/ApolloAuto/apollo/releases/tag/v8.0.0) document it says
> Upgraded PnC Simulation Service
> - Provide PnC debug tool by integrating local simulator in Dreamview
> - Support scenario editing online and download in Dreamview

Questions:
1. Is the PnC Simulation Service referring to SimControl?
2. SimControl existed in previous versions of Apollo, is there anything that is newly integrated?
3. Is "scenario edition" referring to editing the routing requests?

Apologies in advance if I missed any important documentation, but so far I only saw the [quick start guide](https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/apollo_8_0_quick_start.md), it gave some instruction of running SimControl and editing routes, but these did exist before v8.0.0.

**Comment by daohu527** [comment]
Is the PnC Simulation Service referring to SimControl?
SimControl existed in previous versions of Apollo, is there anything that is newly integrated?

> Yes, and it add set obstacles and vehicle dynamics model, which you can set dynamic and static obstacles, simulate dynamic models, etc.

Is "scenario edition" referring to editing the routing requests?

> No, scenario is not just the route, it includes surrounding obstacles, maps, and the purpose of the vehicle, etc. You can refer to related specifications, such as OpenSCENARIO to create scenario.

**Comment by YuqiHuai** [comment]
Thanks! I'll check out setting dynamic and static obstacles, and simulate dynamic models.
