### ISSUE TITLE
[Question] stitching trajactory & relative time in TrajectoryPoint

### ISSUE THREAD

**Issue by InterKnight** [ApolloAuto/apollo#14750]
Thank you for great job!

I am new in digging into apollo and have some questions about open_space_trajectory_provider.cc.

1，why this two “planning_cycle_time” are different？

https://github.com/ApolloAuto/apollo/blob/b00c030ac02c54f98579d3d3e879dbf52f0d1d53/modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_provider.cc#L120

https://github.com/ApolloAuto/apollo/blob/b00c030ac02c54f98579d3d3e879dbf52f0d1d53/modules/planning/tasks/optimizers/open_space_trajectory_generation/open_space_trajectory_provider.cc#L131

2，why relative_time is not 0 in follow file ？it is the first point in trajectory
https://github.com/ApolloAuto/apollo/blob/b00c030ac02c54f98579d3d3e879dbf52f0d1d53/modules/planning/common/trajectory_stitcher.cc#L54

**Comment by jilinzhou** [comment]
1. They have the same value of 0.1s.
2. Take a look of this commit: https://github.com/ApolloAuto/apollo/commit/b9e8a2698df813d9d99a4ae644e3a773e2737ea
