### ISSUE TITLE
Robosense driver update

### ISSUE THREAD

**Issue by IvDmNe** [ApolloAuto/apollo#14751]
Hello!. In new 8.0 version Robosense driver was fully replaced by another one. And as I see from config files and source files there is no more support for RS32, RS128 and RSBPearl lidars. Is it true? Do I need to replace new driver with the old one in order to use RS Ruby and BPearl?

**Comment by SeasoulChris** [comment]
We tested previous version of RoboSense driver, sometimes it didnt't work well, so we changed a new version robosense driver in 8.0。The new version only support rs16、rs-helios16，so if you wanna use other robosense lidar, you can try to use the previous version driver for now

**Comment by IvDmNe** [comment]
> sometimes it didnt't work well,
Was it similar to issue #13666 ? 

And was new driver written from scratch or you use some third-party driver?

**Comment by SeasoulChris** [comment]
1. the previous lidar driver, you can find [previous robosense lidar driver](https://github.com/ApolloAuto/apollo/tree/r7.0.0/modules/drivers/lidar/robosense)

**Comment by IvDmNe** [comment]
thanks for the link, but my question was about driver used in Apollo 8.0. As this driver supports so few models, I thought that your team either wrote it from scratch with support only for lidars you work with, or you take the driver from some third-party project, removing code related to unused lidars. In the second case if third-party driver is open-source and originally supports more models than you adapted to Apollo project, I can try to add them to use with Bpearl.

**Comment by daohu527** [comment]
Yes, we will continue to add more hardware support. Others are also welcome to contribute!

**Comment by IvDmNe** [comment]
Okay, I got it. Thank you for the answers!
