### ISSUE TITLE
no libtorch gpu in apollo 8.0 env docker

### ISSUE THREAD

**Issue by johnnyleeRH** [ApolloAuto/apollo#14754]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

-  linux ubuntu 20.04
-  Apollo 8.0

### Steps to reproduce the issue:
- buildtool build prediction with gpu
- error happen as below
`(08:46:42) ERROR: /apollo_workspace/modules/prediction/evaluator/BUILD:7:11: no such package '@libtorch_gpu//': The repository '@libtorch_gpu' could not be resolved: Repository '@libtorch_gpu' is not defined and referenced by '//modules/prediction/evaluator:evaluator_manager'
(08:46:42) ERROR: Analysis of target '//modules/prediction:install' failed; build aborted: `

**Comment by daohu527** [comment]
Not sure if it is caused by the installation package. What command did you use to install the prediction module?

**Comment by johnnyleeRH** [comment]
> n mod

just follow the 《03_Package Management》docs

- install aem
- aem start_gpu
- buildtool install prediction-dev
- buildtool build -p modules/prediction --gpu

**Comment by WildBeast114514** [comment]
Thank you for reporting this issue. This issue is caused by Incomplete package dependencies in cyberfile.

You can modify the cyberfile to fix this issue: `vim modules/prediction/cyberfile.xml`
remove the following content: 
```<depend repo_name="libtorch_cpu" lib_names="libtorch_cpu">3rd-libtorch-cpu-dev</depend>```
and add the following content:
`<depend repo_name="libtorch_cpu" lib_names="libtorch_cpu" condition="not gpu">3rd-libtorch-cpu-dev</depend>
<depend repo_name="libtorch_gpu" lib_names="libtorch_gpu" condition="gpu">3rd-libtorch-gpu-dev</depend>`

Also, we will update the prediction package to fix this problem.

**Comment by johnnyleeRH** [comment]
> Thank you for reporting this issue. This issue is caused by Incomplete package dependencies in cyberfile.
> 
> You can modify the cyberfile to fix this issue: `vim modules/prediction/cyberfile.xml` remove the following content: `<depend repo_name="libtorch_cpu" lib_names="libtorch_cpu">3rd-libtorch-cpu-dev</depend>` and add the following content: `<depend repo_name="libtorch_cpu" lib_names="libtorch_cpu" condition="not gpu">3rd-libtorch-cpu-dev</depend> <depend repo_name="libtorch_gpu" lib_names="libtorch_gpu" condition="gpu">3rd-libtorch-gpu-dev</depend>`
> 
> Also, we will update the prediction package to fix this problem.

another problem, libtorch_cuda.so depend on libmagma.so，but libmagma.so not found

**Comment by WildBeast114514** [comment]
> > Thank you for reporting this issue. This issue is caused by Incomplete package dependencies in cyberfile.
> > You can modify the cyberfile to fix this issue: `vim modules/prediction/cyberfile.xml` remove the following content: `<depend repo_name="libtorch_cpu" lib_names="libtorch_cpu">3rd-libtorch-cpu-dev</depend>` and add the following content: `<depend repo_name="libtorch_cpu" lib_names="libtorch_cpu" condition="not gpu">3rd-libtorch-cpu-dev</depend> <depend repo_name="libtorch_gpu" lib_names="libtorch_gpu" condition="gpu">3rd-libtorch-gpu-dev</depend>`
> > Also, we will update the prediction package to fix this problem.
> 
> another problem, libtorch_cuda.so depend on libmagma.so，but libmagma.so not found

well, it looks like we also miss this package.
add the following content:
```<depend>3rd-magma-dev</depend>```

**Comment by johnnyleeRH** [comment]
it works, thanks
