### ISSUE TITLE
Make predictions using only for CPU

### ISSUE THREAD

**Issue by joseph16388** [ApolloAuto/apollo#14773]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0,7.0,8.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

May the prediction module make predictions using only for CPU at runtime? What is the command to compile the module?
Thank you!

**Comment by daohu527** [comment]
No, Prediction need deep learning model for inference, so it deps on pytorch, use cpu can also work, but it need modify the torch::Device(torch::kCUDA)
