### ISSUE TITLE
[Question] simulation_msgs and modules/simulation

### ISSUE THREAD

**Issue by YuqiHuai** [ApolloAuto/apollo#14772]
There are some files under [`modules/common_msgs/simulation_msgs/`](https://github.com/ApolloAuto/apollo/tree/v8.0.0/modules/common_msgs/simulation_msgs)  that seem to represent a virtual scenario somehow runnable in Dreamview.

Based on the protobuf files it looks like we will be able to run scenarios that simulate traffic light with various behavior, agents that follow points and even avoid rear end collision.

The message when these files were committed (https://github.com/ApolloAuto/apollo/commit/77f52d876c1fcd9cd1c46bb6f7018b3ff1ce2558) says: " move modules/simulation to modules/common_msgs/simulation_msgs "
But `modules/simulation` was neither in the previous version of Apollo ([v7.0.0](https://github.com/ApolloAuto/apollo/tree/v7.0.0)), nor in the current version of Apollo ([v8.0.0](https://github.com/ApolloAuto/apollo/tree/v8.0.0))

Question:
Is there a built-in simulator for Apollo that is currently in progress? If it is already completed, where can I find it?

Thank you in advance for the answers.

**Comment by lj0919** [comment]
@YuqiHuai  At present, Apollo does not have a complete built-in simulator, but dreamview has a plugin that can expand the ability to simulate obstacles and traffic lights. You can read [document](https://apollo.baidu.com/community/Apollo-Homepage-Document/Apollo_Doc_CN_8_0?doc=%2F%25E5%25BA%2594%25E7%2594%25A8%25E5%25AE%259E%25E8%25B7%25B5%2F%25E4%25BD%25BF%25E7%2594%25A8Apollo%25E8%25BF%259B%25E8%25A1%258CPlanning%25E6%2589%25A9%25E5%25B1%2595%25E5%25BC%2580%25E5%258F%2591%2F%25E6%259C%25AC%25E5%259C%25B0%25E8%25B0%2583%25E8%25AF%2595%25E4%25BB%25BF%25E7%259C%259F) try to download the plugin on the local Apollo and use the obstacle simulation capability to perform local simulation.For complete simulation capabilities, welcome to the [website](https://apollo.baidu.com/workspace) experience

**Comment by YuqiHuai** [comment]
Thank you @lj0919 for the response, and thank you for sharing the URLs! Was this “Apollo Studio” called “Dreamland” for a while?

**Comment by lj0919** [comment]
@YuqiHuai Yes,Apollo Studio used to call Dreamland. Those parts of Apollo Studio always intend to close source.

**Comment by YuqiHuai** [comment]
Thanks for the information!
