### ISSUE TITLE
Demo guide is not working

### ISSUE THREAD

**Issue by zillur-av** [ApolloAuto/apollo#14787]
I wanted to replay the demo record of gps waypoint navigation. But the recorded data download script ```/docs/demo_guide/helper_function.py``` does not exist. My built was successful and dreamviewer is also working. Just followed the [demo_guide](https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/demo_guide/README.md#download-and-play-the-demo-record).

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source)**:
- **Apollo version (1.0)**:
- **Output of `apollo.sh config` if on `master` branch**: 
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR: /apollo
[INFO]     APOLLO_CACHE_DIR: /apollo/.cache
[INFO]     APOLLO_IN_DOCKER: true
[INFO]     APOLLO_VERSION: master-2023-02-14-9537abebf3
[INFO]     DOCKER_IMG: dev-x86_64-18.04-20221124_1708
[INFO]     APOLLO_ENV:  STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU: USE_GPU_HOST=1 USE_GPU_TARGET=1
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

**Comment by daohu527** [comment]
we will check and feedback soon!

**Comment by zillur-av** [comment]
Solved it. Just that in [demo_guide](https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/demo_guide/README.md#download-and-play-the-demo-record), it should be ```python3 docs/demo_guide/02_Quick Start/record_helper.py demo_3.5.record```
