### ISSUE TITLE
Can Apollo 8.0 be installed on Raspberry Pi?

### ISSUE THREAD

**Issue by koking0** [ApolloAuto/apollo#14789]
I want to use Raspberry Pi to make a self-driving car, is it possible to install Apollo 8.0 on Raspberry Pi? Or maybe Jetson Nano and Jetson Xavier?

**Comment by daohu527** [comment]
The raspberry pi needs some optimization as it has limited computing power. But I think it's a good project and you can learn a lot from it
Jetson Nano or Jetson Xavier will much easy.

They all need arm support and are currently under development. We can discuss it in the community, I think it will be a good project

**Comment by koking0** [comment]
Thank you very much for your reply, I decided to learn about this project and start by buying a Jetson Nano. 😀

**Comment by YuqiHuai** [comment]
I was also curious about running Apollo on a cluster of raspberry pis! Glad to see others have the same interested and guess I’ll be getting a Jetson Nano as well!

@daohu527 just for clarification, arm support is currently under development, when do you think it will be available for us to run it on Jetson Nano?

**Comment by daohu527** [comment]
> Q1: arm support is currently under development, when do you think it will be available for us to run it on Jetson Nano?

Work completed in Q2, but release schedule may be discussed. You can pay attention to community releases

> Q2: do you think a single raspberry pi is able to run just prediction + planning + SimControl?

I have run the traffic light program on the Raspberry Pi, but the prediction may be more difficult, and the planning should not be a big problem. prediction use a lot of models, it may be feasible to simplify it with traditional algorithms.

Docker is not necessary to run, we can install the environment directly on the host. This is another topic : )

**Comment by YuqiHuai** [comment]
@daohu527 those are very helpful information! I plan to test Apollo's planning module on Raspberry Pi later.

Where can I find documentation to directly install Apollo on the host? I am only aware of [this guide](https://github.com/ApolloAuto/apollo/blob/master/docs/01_Installation%20Instructions/apollo_software_installation_guide_package_method.md) that talks about docker. If I just run `./apollo.sh build` I'll get `The build operation must be run from within docker container`
