### ISSUE TITLE
The same stages in camera detection pipeline

### ISSUE THREAD

**Issue by IvDmNe** [ApolloAuto/apollo#14785]
Good day! I wonder why in camera detection pipeline a stage ```OMT_OBSTACLE_TRACKER``` is repeated 4 times and with identical parameters? Trying to get rid of any of them leads to crush of detection module. And why a tracking stage goes before detection stage?

https://github.com/ApolloAuto/apollo/blob/9537abebf3e180e8976489bab7166da6d87efaf4/modules/perception/pipeline/config/camera_detection_pipeline.pb.txt#L1-L7

**Comment by daohu527** [comment]
Yeah, this implementation is ugly and pluzz! We will refactor it soon

## reason
The reason why need 4 tracker is we use a pipeline to organize the camera object detection process. Each process we call a stage, each stage is a class that can be easily replaced with similar functionality, like a plugin mechanism.

then we go to tracker
The reason why it is special is that the previous camera object detection is to detect 2D bounding box in the image first, and then estimate the depth.

So we track 2d bounding box first, then 3d. we also use tracking to help to predict the next location of the target to help detect which is called `detection by tracking`

so there're 3 tracker! the last tracker is empty and no use for now.

## Summarize

OMT_OBSTACLE_TRACKER   // detection by tracking
OMT_OBSTACLE_TRACKER  // 2d tracking
OMT_OBSTACLE_TRACKER  // 3d tracking
OMT_OBSTACLE_TRACKER  // no use

why need 4 is the data is shared between the trackers, we cannot split it in the existing structure, so we may consider refactoring in the future!

you know good design is simple and easy to understand : )

**Comment by IvDmNe** [comment]
Thank you, @daohu527 . It makes sense now. I also was confusing about 4 identical sets of parameters for theese stages, and found that there is a flag inside ```Process``` function that checks a state of detection results:

https://github.com/ApolloAuto/apollo/blob/9537abebf3e180e8976489bab7166da6d87efaf4/modules/perception/camera/lib/obstacle/tracker/omt/omt_obstacle_tracker.cc#L539-L559
