### ISSUE TITLE
core dumped when starting perception module 

### ISSUE THREAD

**Issue by btcreater** [ApolloAuto/apollo#14792]
### System information

- **Linux Ubuntu 20.04**
- **Apollo installed from source**
- **Apollo version 8.0**

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- Apollo 8.0 + carla-apollo bridge
- Tests perception multi-sensor fusion module(LiDAR, front_6mm camera, front_12mm camera)
when I use front_6mm camera+ LiDAR, in all 2 sensors, the perception module runs OK, and the perception function works as well.
But when I add a front_12mm camera based on 6mm camera + LiDAR, the perception module can't start and the mainboard logs were below:
```
root@in-dev-docker:/apollo# mainboard -d modules/perception/production/dag/dag_streaming_perception.dag 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0227 15:42:27.109186 3931696 module_argument.cc:81] []command: mainboard -d modules/perception/production/dag/dag_streaming_perception.dag 
I0227 15:42:27.109346 3931696 global_data.cc:122] []host ip: 172.17.0.1
I0227 15:42:27.112176 3931696 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I0227 15:42:27.112200 3931696 module_argument.cc:60] []dag_conf: modules/perception/production/dag/dag_streaming_perception.dag
rm: cannot remove '/apollo/debug_output/*.jpg': No such file or directory
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

What's the problem ? Is there any configuration I should pay attention to ? 
Or is there any ways to let mainboard to print more concrete line code information?
Any advice would be appreciate. Thanks!

**Comment by qilinhu** [comment]
@btcreater hi，
I tested the code of the master branch and did not reproduce your problem. The error message you have appears to be a problem with the camera module.You can start the dag file of the camera module separately to see if this error still occurs.
Use the following command：
`mainboard -d modules/perception/production/dag/dag_streaming_perception_camera.dag`

**Comment by qilinhu** [comment]
@btcreater Hi,
The branch where you have the above problem has not been fixed. It is recommended that you use the latest master branch code.
In addition, the channel `/apollo/perception/obstacles` has no obstacle result, you can check the `/apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt` file, where the `output_final_obstacles` configuration option should be set to `true`, hope can help you.

**Comment by btcreater** [comment]
> @btcreater Hi, The branch where you have the above problem has not been fixed. It is recommended that you use the latest master branch code. In addition, the channel `/apollo/perception/obstacles` has no obstacle result, you can check the `/apollo/modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt` file, where the `output_final_obstacles` configuration option should be set to `true`, hope can help you.

Thanks! It helps.

**Comment by KAndHisC** [comment]
which repo of `carla-apollo bridge` are you using?
