### ISSUE TITLE
How to visualize trafficlight in apollo?

### ISSUE THREAD

**Issue by 181860153** [ApolloAuto/apollo#14799]
Hello everyone,
I am trying to test the trafficlight perception part of apollo7.0. So I would like to visualize the detection box of the trafficlight. I read [https://github.com/ApolloAuto/apollo/issues/4262](https://github.com/ApolloAuto/apollo/issues/4262) but I couldn't find the conf file it mentioned in apollo 7.0. Could anyone help me with it? Many thanks!

**Comment by qilinhu** [comment]
@181860153 Hi,
The visualization code in apollo 7.0 has been merged into trafficlights_perception_component.cc, and the images output by traffic lights will be stored in the /apollo/debug_vis/ directory.[https://github.com/ApolloAuto/apollo/blob/463fb82f9e979d02dcb25044e60931293ab2dba0/modules/perception/onboard/component/trafficlights_perception_component.cc#L1022](url)
