### ISSUE TITLE
cyber_monitor cannot show the whole infomation

### ISSUE THREAD

**Issue by zhangyi6** [ApolloAuto/apollo#14794]
I cannot see the whole information in cyber_monitor. Should I make some changes to the configuration files?
As showing below, "left samples" has 153 items, but it only shows first item.

![20230228-102814](https://user-images.githubusercontent.com/38745125/221738319-09efb8b5-df44-495e-b159-19b59cc70b16.png)
![20230228-102821](https://user-images.githubusercontent.com/38745125/221738322-3047a63b-0722-4c6d-90fd-a92e1fc7b379.png)

**Comment by qilinhu** [comment]
@zhangyi6 Hi,You can use N and M on the keyboard to view list information.

**Comment by zhangyi6** [comment]
@qilinhu thanks! but is there any way to show all at one time?

**Comment by daohu527** [comment]
No, displaying arrays at the same time is currently not supported, you can view them by writing python code
