### ISSUE TITLE
dreamview which built from source cannot be launched by "aem bootstrap start"

### ISSUE THREAD

**Issue by zhangyi6** [ApolloAuto/apollo#14804]
**Description**
I want to modify the dreamview's code, so I built source code by running `buildtool build --packages modules/dreamview`. 
When I run `aem bootstrap start`, I received the error: `[ERROR] Failed to start Dreamview. Please check /opt/apollo/neo/data/log/dreamview.log or /opt/apollo/neo/data/log/monitor.log for more information`
![1](https://user-images.githubusercontent.com/38745125/222401062-aad9d4a8-da2e-423d-b7f8-005b1373031a.png)
![2](https://user-images.githubusercontent.com/38745125/222401095-f014356a-d55b-45b4-b4f2-53586fcfcc8c.png)

Then I checked /opt/apollo/neo/packages/dreamview-dev/latest/launch/dreamview.launch:
![3](https://user-images.githubusercontent.com/38745125/222401760-6b0d73b9-4b96-4367-ba1b-c068aaa25e56.png)
Then I modified dag file as follow, but another error occured
![4](https://user-images.githubusercontent.com/38745125/222402186-bc9a68e9-ab18-4bd8-856f-694182c9898f.png)
![5](https://user-images.githubusercontent.com/38745125/222402737-a49faa07-5766-44c3-9536-56e4d814d7d0.png)

I think that I got the wrong way to build dreamview from source code, So is there any document to apply the right way, I really need it. Thanks!

**version**
apollo8.0

**commit**
The source code came from "apollo-master.zip", I extracted dreamview directory and put it under `apollo_workspace/modules`
![6](https://user-images.githubusercontent.com/38745125/222405157-94219912-d1ad-4426-9e31-a37decf6c8d9.png)

**Comment by WildBeast114514** [comment]
The source from github master branch actually is not the latest one. It may have some different with the latest dreamview package which may caused some errors.
To use verified source of dreamview, you can use the following command:
```
cd /apollo_workspace && buildtool install dreamview-dev
```
And you will find the source of dreamview which have been downloaded automatically at /apollo_workspace/module/dreamview
