### ISSUE TITLE
Is there a way to compile Incrementally

### ISSUE THREAD

**Issue by zhangyi6** [ApolloAuto/apollo#14807]
I am working on dreamview, and when I compiled dreamview source code, it would take a long time.
Is there a way to compile Incrementally.

For example, dreamview depends on map module, so when I modify /modules/map/hdmap/hdmap_common.h, what I expected was the compiler only compile the modified part, instead of compiling the whole module and it's dependence. 
It's convenient to debug. Thanks!

**Comment by WildBeast114514** [comment]
This is actually a limitation of bazel. When you compile a target, such as the target in the map module you mentioned, bazel will recompile all the targets that depend on that target.

**Comment by JunLFang** [comment]
I also meet the same issue , what a pity

**Comment by daohu527** [comment]
The current compilation is indeed cached! It will only compile the modified part, so I am not sure whether your problem is like this
