### ISSUE TITLE
apollo 7.0镜像在部分电脑上运行出现illegal instruction问题

### ISSUE THREAD

**Issue by liufuda** [ApolloAuto/apollo#14811]
版本:apollo-7.0
我们将代码拷贝到容器中并编译，形成新的镜像。
新的镜像在部分电脑上运行出现illegal instruction问题，如下图
![4IVzdXE476](https://user-images.githubusercontent.com/20452101/223610061-64d72198-ba37-41a6-89b3-fcdeb7869d08.jpg)

搜索猜测是CPU指令集原因，并作以下尝试：
- 1.我们尝试将tools/bazel.rc的build:optimize 注释掉，编译无法通过。
![img_v2_b9a77571-559c-4c35-adc5-bd508574fabg](https://user-images.githubusercontent.com/20452101/223610536-d13065e7-4f16-42b3-a33d-61ee39490d55.jpg)
![image](https://user-images.githubusercontent.com/20452101/223611518-0a1044fb-cf43-41be-a2f8-8a8f86405d07.png)

- 2.将march=native替换成march=core2也无法编译通过。
![img_v2_33ee54a3-3230-444d-9082-5b55de9be19g](https://user-images.githubusercontent.com/20452101/223610880-7e0e5c39-ecaf-4d5f-840e-1c5d4384474f.jpg)
![image](https://user-images.githubusercontent.com/20452101/223611587-f564ee7e-a6a7-4d60-8114-969ddb0f9111.png)

请问如何解决打的镜像，在部分机器指令不兼容的问题（运行程序出现illegal instruction core dump）？

期待回复，感谢！

**Comment by WildBeast114514** [comment]
将march=native替换成mavx2，即：
build:optimize --copt=-mavx2
build:optimize --host_copt=-mavx2
