### ISSUE TITLE
使用apollov8.0，启动感知模块出现core dumped的情况

### ISSUE THREAD

**Issue by cherishTMYY** [ApolloAuto/apollo#14819]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:ubuntu 18.04
- **Apollo installed from (source or binary)**:buildtool install --legacy perception-dev
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:v8.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- buildtool install --legacy perception-dev
- aem bootstrap start
-  mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_lidar.dag

### Supporting materials (screenshots, command lines, code/script snippets):
*** Check failure stack trace: ***
    @     0x7f4bb68d067d  google::LogMessage::Fail()
    @     0x7f4bb68d2b3a  google::LogMessage::SendToLog()
    @     0x7f4bb68d008d  google::LogMessage::Flush()
    @     0x7f4bb68d3ae9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4b66e6f123  apollo::perception::lidar::CNNSegmentation::Init()
    @     0x7f4b66bf8ed0  apollo::perception::pipeline::Pipeline::CreateStage()
    @     0x7f4b66bf7d51  apollo::perception::pipeline::Pipeline::Initialize()
    @     0x7f4b66a15387  apollo::perception::lidar::LidarObstacleDetection::Init()
    @     0x7f4b6695dd59  apollo::perception::onboard::LidarDetectionComponent::InitAlgorithmPlugin()
    @     0x7f4b6695d6d2  apollo::perception::onboard::LidarDetectionComponent::Init()
    @     0x7f4b669a7603  apollo::cyber::Component<>::Initialize()
    @     0x55800b80ed2a  (unknown)
    @     0x55800b80f5db  (unknown)
    @     0x55800b80fd15  (unknown)
    @     0x55800b809267  (unknown)
    @     0x7f4bb5eaec87  __libc_start_main
    @     0x55800b80a1fa  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by yongjay** [comment]
I have the same issue , any solution?

**Comment by yongjay** [comment]
E0313 16:48:52.811875  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.953654] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811887  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.950962] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811898  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.949981] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811908  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.950611] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811918  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.957626] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811926  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.964367] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811937  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.97335] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811949  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[0.997895] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:52.811961  4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1"
]. sampled_right_width_[1.03294] is too small. It should be larger than half vehicle width[1.05].
E0313 16:48:53.238080  4930 file.cc:76] [mainboard]Failed to open file /apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf in text mode.
E0313 16:48:53.238102  4930 file.cc:102] [mainboard]Failed to open file /apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf in binary mode.
F0313 16:48:53.238114  4930 cnn_segmentation.cc:165] Check failed: GetProtoFromFile(cnnseg_config_.engine_file(), &spp_engine_config_) [mainboard]Failed to parse SppEngine config file./apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf
*** Check failure stack trace: ***
    @     0x7fb57cdae67d  google::LogMessage::Fail()
    @     0x7fb57cdb0b3a  google::LogMessage::SendToLog()
    @     0x7fb57cdae08d  google::LogMessage::Flush()
    @     0x7fb57cdb1ae9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb52ee6f123  apollo::perception::lidar::CNNSegmentation::Init()
    @     0x7fb52ebf8ed0  apollo::perception::pipeline::Pipeline::CreateStage()
    @     0x7fb52ebf7d51  apollo::perception::pipeline::Pipeline::Initialize()
    @     0x7fb52ea15387  apollo::perception::lidar::LidarObstacleDetection::Init()
    @     0x7fb52e95dd59  apollo::perception::onboard::LidarDetectionComponent::InitAlgorithmPlugin()
    @     0x7fb52e95d6d2  apollo::perception::onboard::LidarDetectionComponent::Init()
    @     0x7fb52e9a7603  apollo::cyber::Component<>::Initialize()
    @     0x55db9d7bfd2a  (unknown)
    @     0x55db9d7c05db  (unknown)
    @     0x55db9d7c0d15  (unknown)
    @     0x55db9d7ba267  (unknown)
    @     0x7fb57c38cc87  __libc_start_main
    @     0x55db9d7bb1fa  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)


add some log to locate problems

**Comment by cherishTMYY** [comment]
> E0313 16:48:52.811875 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.953654] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811887 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.950962] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811898 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.949981] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811908 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.950611] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811918 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.957626] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811926 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.964367] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811937 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.97335] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811949 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.997895] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811961 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[1.03294] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:53.238080 4930 file.cc:76] [mainboard]Failed to open file /apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf in text mode. E0313 16:48:53.238102 4930 file.cc:102] [mainboard]Failed to open file /apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf in binary mode. F0313 16:48:53.238114 4930 cnn_segmentation.cc:165] Check failed: GetProtoFromFile(cnnseg_config_.engine_file(), &spp_engine_config_) [mainboard]Failed to parse SppEngine config file./apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/engine.conf *** Check failure stack trace: *** @ 0x7fb57cdae67d google::LogMessage::Fail() @ 0x7fb57cdb0b3a google::LogMessage::SendToLog() @ 0x7fb57cdae08d google::LogMessage::Flush() @ 0x7fb57cdb1ae9 google::LogMessageFatal::~LogMessageFatal() @ 0x7fb52ee6f123 apollo::perception::lidar::CNNSegmentation::Init() @ 0x7fb52ebf8ed0 apollo::perception::pipeline::Pipeline::CreateStage() @ 0x7fb52ebf7d51 apollo::perception::pipeline::Pipeline::Initialize() @ 0x7fb52ea15387 apollo::perception::lidar::LidarObstacleDetection::Init() @ 0x7fb52e95dd59 apollo::perception::onboard::LidarDetectionComponent::InitAlgorithmPlugin() @ 0x7fb52e95d6d2 apollo::perception::onboard::LidarDetectionComponent::Init() @ 0x7fb52e9a7603 apollo::cyber::Component<>::Initialize() @ 0x55db9d7bfd2a (unknown) @ 0x55db9d7c05db (unknown) @ 0x55db9d7c0d15 (unknown) @ 0x55db9d7ba267 (unknown) @ 0x7fb57c38cc87 __libc_start_main @ 0x55db9d7bb1fa (unknown) @ (nil) (unknown) Aborted (core dumped)
> 
> add some log to locate problems

修改 lidar_detection_pipeline.pb.txt
 vim /apollo/modules/perception/pipeline/config/lidar_detection_pipeline.pb.txt
讲128修改为64，因为他启动是找不到128的文件
修改后的内容如下：
stage_config: {
  stage_type: CNN_SEGMENTATION
  enabled: true

  cnnseg_config: {
    sensor_name: "velodyne128"
    param_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg64_param.conf"
    proto_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg64_caffe/deploy.prototxt"
    weight_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg64_caffe/deploy.caffemodel"
    engine_file: "/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg64_caffe/engine.conf"
  }
}
}

**Comment by yongjay** [comment]
> 

按照你的修改还是会有错
E0313 16:48:52.811875 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.953654] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811887 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.950962] is too small. It should be larger than half vehicle width[1.05].
你修改之后启动成功了吗？是否有其他修改？

**Comment by cherishTMYY** [comment]
> > 
> 
> 按照你的修改还是会有错 E0313 16:48:52.811875 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.953654] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811887 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.950962] is too small. It should be larger than half vehicle width[1.05]. 你修改之后启动成功了吗？是否有其他修改？

这个错误不影响功能

**Comment by yongjay** [comment]
> > > 
> > 
> > 
> > 按照你的修改还是会有错 E0313 16:48:52.811875 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.953654] is too small. It should be larger than half vehicle width[1.05]. E0313 16:48:52.811887 4930 hdmap_common.cc:158] [map]lane[id = id: "7657a_1_-1" ]. sampled_right_width_[0.950962] is too small. It should be larger than half vehicle width[1.05]. 你修改之后启动成功了吗？是否有其他修改？
> 
> 这个错误不影响功能
可以了！感谢！
