### ISSUE TITLE
apollo8.0 docker Dreamview 安装完成后没有可选择的/sunnyvale map

### ISSUE THREAD

**Issue by rainaider** [ApolloAuto/apollo#14812]
请问如何获取sunnywale 地图
![apollo](https://user-images.githubusercontent.com/47803962/224266262-818e5e2f-2f47-4426-96b0-30051eeed371.png)

**Comment by WildBeast114514** [comment]
如果你使用的是包管理版本，可以使用以下命令：
```sudo apt remove apollo-neo-map-dev && sudo apt install apollo-neo-dreamview-dev ```
来重新安装dreamview和map模块获取地图数据

**Comment by rainaider** [comment]
apollo-neo-dreamview-dev is already the newest version (1.0.0.5).
按照您的操作重装了 这个版本依然没有

**Comment by rainaider** [comment]
感谢大佬
