### ISSUE TITLE
Cyber RT的CYBER_IP如何设置，可以使得发布者和订阅者同时支持共享内存和跨机通信。

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#14817]
apollo v7.0.0
在设置CYBER_IP为127.0.0.1时，可以使用共享内存。
在设置CYBER_IP为192.168.0.130时，可以使用跨机dds通信。但是这种设置下本地两个发布者订阅者之间无法共享内存通信，表现为发布者正常发布，但是订阅者持续无接受。

**Comment by daohu527** [comment]
Make sure the two hosts(or more) are under the same network segment of the local area network, Like `192.168.10.6` and `192.168.10.7`.

You just need to modify `CYBER_IP` of `/apollo/cyber/setup.bash`

```bash
export CYBER_IP=127.0.0.1
```

Suppose you have two hosts A and B，the ip of A is `192.168.10.6`, and the ip of B is `192.168.10.7`. Then set `CYBER_IP` to `192.168.10.6` on host A, and set `CYBER_IP` to `192.168.10.7` on host B. Now host A can communicate with host B.

**Comment by fengmao31** [comment]
我设置发布者CYBER_IP=192.168.0.130的时候可以和另一台电脑的CYBER_IP=192.168.0.130的订阅者通信。但是本地的订阅者无法通信。现在是三个节点的通信。一个发布者，一个订阅者在物理机A。另一个订阅者在物理机B。
如果设置 CYBER_IP=192.168.0.130，物理机A发布者和物理机B的订阅者可以正常通信，但是物理机A的订阅者无法订阅到消息。

**Comment by fengmao31** [comment]
it can be supported. at first, check your ip. maybe the router change your ip. secondly, maybe you need create a new node. in this part, apollo have a bug, it don't show you a error message about same node is be used in another device. it only show the message when you try to run same node in local device.
