### ISSUE TITLE
apollo8.0安装quick start 编译报错buildtool build --packages planning_customization

### ISSUE THREAD

**Issue by rainaider** [ApolloAuto/apollo#14825]
![planning](https://user-images.githubusercontent.com/47803962/224863371-325f7e7c-ee25-4c61-8ce3-053896e27dcf.png)

**Comment by windmakeppcool** [comment]
我编译自己得组件，依赖于perception-dev也会报同样错误。无论是3060ti + cuda11.1，还是3090ti+11.4
