### ISSUE TITLE
data下的bag文件太大，请问是什么文件？可以删除吗？

### ISSUE THREAD

**Issue by looles** [ApolloAuto/apollo#14828]

**Comment by daohu527** [comment]
Yes, can be deleted if you don't need it.

## files
The `data` directory mainly includes the following types of files
1. Bag package recorded by `cyber_recorder`, In most cases the recording is manually triggered
2. In the case of automatic driving takeover, the data automatically saved by the system

**Comment by looles** [comment]
thank you!

**Comment by AOOOOOA** [comment]
> Yes, can be deleted if you don't need it.
> 
> ## files
> The `data` directory mainly includes the following types of files
> 
> 1. Bag package recorded by `cyber_recorder`, In most cases the recording is manually triggered
> 2. In the case of automatic driving takeover, the data automatically saved by the system

Hi, may I ask how to turn off the automatic record function in automatic driving mode?

**Comment by daohu527** [comment]
This depends on how you start the autopilot module. Normally, record files will not be recorded actively.

@AOOOOOA This issue will be closed. If you have questions about recording, please create a new one.
