### ISSUE TITLE
Apollo8.0按照buildtool build --packages planning_customization仿真失败

### ISSUE THREAD

**Issue by rainaider** [ApolloAuto/apollo#14827]
按照buildtool build --packages planning_customization编译完成后设置完点不走，貌似报GPS错误，请问怎么解决
![fangzhen](https://user-images.githubusercontent.com/47803962/224879517-748ba1aa-69ce-4a69-8aa9-c5bb0af93bce.png)

**Comment by daohu527** [comment]
If there is no actual vehicle, it is recommended that you turn on `sim_control` to simulate gps and vehicle information
