### ISSUE TITLE
Question about v8.0 CameraBevDetectionComponent

### ISSUE THREAD

**Issue by ycdhqzhiai** [ApolloAuto/apollo#14837]
`CameraBevDetectionComponent`模块重写了基类的`Proc`接口，但是代码里面发现存在着`OnReceiveImage`，如果上游sensor发送过来数据，调试发现初始化完成之后，执行的是`Proc`接口，数据过来之后为什么执行`Proc`而`OnReceiveImage`没有执行，我看代码好像两个接口都能完成detector，是这样的吗
https://github.com/ApolloAuto/apollo/blob/b4a1556b203d17018de59bcc9fd741015e4ab8a9/modules/perception/onboard/component/camera_bev_detection_component.cc#L248
https://github.com/ApolloAuto/apollo/blob/b4a1556b203d17018de59bcc9fd741015e4ab8a9/modules/perception/onboard/component/camera_bev_detection_component.cc#L385

**Comment by daohu527** [comment]
camera bev use 6 cameras mounted around the car and tested on the nuscenes dataset.

Given that we have 6 cameras, how to time align this data is critical. Our current solution is to use one camera as a trigger, and then get the latest data from the other five cameras.
so `Proc` is the trigger, and we get the other 5 image data use a callback funciton called `OnReceiveImage `.
```
camera1 --> trigger
                -->get latest data (camera2, camera3, camera4, camera5, camera6)
```

**Comment by ycdhqzhiai** [comment]
好像更加疑惑了，`Proc`初始化完成之后就会执行，实时获取6个摄像头数据，完成所有数据接收之后，传入detector检测器里面，然后按照地址顺序依次取值，完成检测，这是`Proc`功能，好像传入检测器的是6个摄像头的数据，并不是你前面提到的camer1
```C++
  dataframe_ptrs_ = {data_frame_camf, data_frame_camfr, data_frame_camfl,
                     data_frame_camb, data_frame_cambl, data_frame_cambr};

  if (!camera_obstacle_pipeline_->Process(&dataframe_ptrs_[0])) {
    AERROR << "bev_obstacle_pipeline_->Process() failed";
    return cyber::FAIL;
  }

bool BEVObstacleDetector::Process(DataFrame *data_frame) {
  static int cnt_1 = 0;
  DataProvider::ImageOptions image_options;
  image_options.target_color = base::Color::RGB;
  std::vector<float> images_data;
  std::vector<float> k_data;
  Timer timer;
  float scale = 1.0f;
  for (int i = 0; i < 6; ++i) {
    const auto camera_frame_temp = (data_frame + i)->camera_frame;
```
这里调用detector的是第一个camera地址，后续进行了遍历取后面5个camera
而`OnReceiveImage `好像也不是执行的剩余5个camera，
```C++
int CameraBevDetectionComponent::InitCameraListeners() {
  for (size_t i = 0; i < camera_names_.size(); ++i) {
    const std::string &camera_name = camera_names_[i];
    const std::string &channel_name = input_camera_channel_names_[i];
    const std::string &listener_name = camera_name + "_fusion_camera_listener";
    AINFO << "listener name: " << listener_name;

    typedef std::shared_ptr<apollo::drivers::Image> ImageMsgType;
    std::function<void(const ImageMsgType &)> camera_callback =
        std::bind(&CameraBevDetectionComponent::OnReceiveImage, this,
                  std::placeholders::_1, camera_name);
    auto camera_reader = node_->CreateReader(channel_name, camera_callback);
  }
  return cyber::SUCC;
}
```
这里6个camera都绑定了一个回调函数，有消息就会执行`OnReceiveImage `，而每次输入的数据都是当前camera数据

所以我感觉这个`OnReceiveImage `是不是多余的

**Comment by daohu527** [comment]
Yes, I check the code and `InitCameraListeners` is commented, The flow that actually works is `InitBevCameraListeners`.

We are refactoring this module and will remove dead code, thanks for your feedback
