### ISSUE TITLE
How could I let the car drive with desired speeds on Sim Control?

### ISSUE THREAD

**Issue by JfortissJ** [ApolloAuto/apollo#14838]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Dear Sir or Madam,

I'm using open source Apollo 5.5 on my Ubuntu 18.04 system for developing.

I had tried to simulate a scenario of driving on expressway up to 80 km/h (about 23 m/s) on Sim Control. I used map_gen.py to generate the apollo map for Sim Control by using the .record files I collected from the real-time test drive. I not only set "lane.speed_limit" as 23. Then I reset the parameters "planning_upper_speed_limit" as 23 and "default_cruise_speed" as 23 in planning.conf file, but also reset the corresponding variables including "speed_limit" or "cruise_speed" in Apollo stack, as 23. Nevertheless, the maximum speed that the car could reach was only 18km/h (about 5 m/s) when I ran the simulation in Sim Control.

I also tried to search for the other users who also had the similar problems (like issues #9917, #11310, and #13738), but the results seem like these similar problems were also not solved.

So I am wondering if it could be a problem with Sim Control itself? Thank you very much for your help and support!

**Comment by HyeonseopLim** [comment]
Hello sir, Did you solve this problem? I have reached this problem and struggling for many days but I still coundn't find a solution.

**Comment by JfortissJ** [comment]
> Hello sir, Did you solve this problem? I have reached this problem and struggling for many days but I still coundn't find a solution.

Hi, thanks for the ask. You have to “bash apollo.sh build” again after resetting the speed limit. 😉
