### ISSUE TITLE
apollo8.0尝试编译自己得component失败

### ISSUE THREAD

**Issue by windmakeppcool** [ApolloAuto/apollo#14830]
![image](https://user-images.githubusercontent.com/53427316/224924282-ed9ec91b-40a3-425a-aff9-ef094bf5477f.png)

对应测cyberfile.xml文件内容如下
![image](https://user-images.githubusercontent.com/53427316/224924540-2932ef64-3c3b-4fbc-a00d-a7bd75b3818c.png)

平台3060ti + driver522.30 + cuda11.1

**Comment by WildBeast114514** [comment]
编译的模块依赖perception的话，需要指定 --gpu 参数，即:
```
buildtool build --gpu -p $YOUR_COMPONENT_PATH
```

**Comment by windmakeppcool** [comment]
> buildtool build --gpu -p

问题解决，感谢
