### ISSUE TITLE
 fatal error: glog/logging.h: No such file or directory

### ISSUE THREAD

**Issue by 812406210** [ApolloAuto/apollo#14848]
Execution platform: @local_config_platform//:host
In file included from ./cyber/state.h:29:0,
                 from cyber/state.cc:17:
./cyber/common/log.h:27:10: fatal error: glog/logging.h: No such file or directory
 #include "glog/logging.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
(14:09:59) INFO: Elapsed time: 0.439s, Critical Path: 0.13s
(14:09:59) INFO: 5 processes: 5 internal.
(14:09:59) FAILED: Build did NOT complete successfully

**Comment by daohu527** [comment]
The reason for the error is that glog cannot be found. 

By default glog has been installed, what version do you use, you can try to restart the container.

**Comment by LordonCN** [comment]
Have u solved it? Pls reopen this issue If restart the container doesn't work.

**Comment by TroyeFun** [comment]
I met the same problem when building cyber docker following the instruction in https://github.com/ApolloAuto/apollo/blob/master/docs/04_CyberRT/CyberRT_Docker.md. Can anyone help?

**Comment by gaodechao** [comment]
I met the same problem and run the following command to resolve：
```
sudo apt-get update
sudo apt-get install libgoogle-glog-dev
```
