### ISSUE TITLE
what is the relationship between node，task，scheduler？

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#14849]
I read the source code of node and publish part. but I don't find the code about task，scheduler in this part. but when I run the example talker . it log that it cannot find the conf file, so it use the default conf to manage it. 
the scheduler looks like only  manage the task in the process. If I run many example process, it cannot mange them and run the most important process at first. And I also don't know how to give the task and use scheduler in the process. maybe I need create some threads to take some nodes as tasks and give them to scheduler?

**Comment by fengmao31** [comment]
I found I can new a thread and give to to cyber rt to manage in a process.

what the defualt priority for the main thread?

**Comment by daohu527** [comment]
Threads have no priority and only two strategies: FIFO and RR

**Comment by fengmao31** [comment]
OK. Thank you.
