### ISSUE TITLE
Provide more details on how can we using CyberRT,for example building CyberRT for Android 

### ISSUE THREAD

**Issue by FranzKafkaYu** [ApolloAuto/apollo#14856]
Hello developers：

Now I am seeking to migrate CyberRT to Android System and I found the documents in CyberRT section are broken(404 not found) and there are not enough build guides for how can we build CyberRT for other  Systems,Can you provide such guides for users?

THANKS IN ADVANCE.

**Comment by YuqiHuai** [comment]
Hi, the CyberRT documentations are actually in the repository its just the URLs are broken. I've tried my best to fix it in my fork https://github.com/YuqiHuai/apollo/tree/fix/docs/

CyberRT's documentation can also be found at https://cyber-rt.readthedocs.io/en/latest/

I am not sure if there is any documentation regarding Android system though.

**Comment by FranzKafkaYu** [comment]
> Hi, the CyberRT documentations are actually in the repository its just the URLs are broken. I've tried my best to fix it in my fork https://github.com/YuqiHuai/apollo/tree/fix/docs/
> 
> CyberRT's documentation can also be found at https://cyber-rt.readthedocs.io/en/latest/
> 
> I am not sure if there is any documentation regarding Android system though.

Thanks for reply,I followed your link and found there was no building guide for Android System.I also searched in ISSUES but nothing helps.

**Comment by daohu527** [comment]
cyber is use c++ and build with bazel, I don't know much about android, but I'm afraid you need technologies where java depends on c++, such as JNI.

https://developer.android.com/studio/projects/add-native-code

**Comment by FranzKafkaYu** [comment]
@daohu527  Hello Developer,I have tried to migrate Cyber to Android Platform but I found here in cyber/transport/shm/posix_segment.cc will use system call:shm_open/shm_unlink etc while in Android System these APIs not availabe while mmap/munmap realized,So it's impossible to migrate CyberRT to Android.
