### ISSUE TITLE
apollo build failed,Error: file '//third_party/gpus:cuda_configure.bzl' does not contain symbol 'make_copy_files_rule'

### ISSUE THREAD

**Issue by fajingt** [ApolloAuto/apollo#14852]
**Describe the bug**
apollo build failed, Error: file '//third_party/gpus:cuda_configure.bzl' does not contain symbol 'make_copy_files_rule'

**To Reproduce**
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR:   /apollo
[INFO]     APOLLO_CACHE_DIR:  /apollo/.cache
[INFO]     APOLLO_IN_DOCKER:  true
[INFO]     APOLLO_VERSION:    master-2023-03-25-cd510fe5c4
[INFO]     DOCKER_IMG:        dev-x86_64-18.04-20221124_1708
[INFO]     APOLLO_ENV:        STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU_HOST:      1
[INFO]     USE_GPU_TARGET:    1
[INFO]     GPU_PLATFORM:      NVIDIA
[INFO] Configure .apollo.bazelrc in non-interactive mode
[INFO] You have bazel 3.7.1 installed.
[INFO] Found possible Python library paths:
       /usr/lib/python3/dist-packages
       /usr/local/lib/python3.6/dist-packages
[INFO] Found CUDA 11.1 in:
       /usr/local/cuda-11.1/targets/x86_64-linux/lib
       /usr/local/cuda-11.1/targets/x86_64-linux/include
[INFO] Found cuDNN 8 in:
       /usr/lib/x86_64-linux-gnu
       /usr/include
[INFO] Found TensorRT 7 in:
       /usr/lib/x86_64-linux-gnu
       /usr/include/x86_64-linux-gnu
[ OK ] Successfully configured .apollo.bazelrc in non-interactive mode.
[ OK ] Running NVIDIA GPU build on x86_64 platform.
[WARNING] ESD CAN library supplied by ESD Electronics doesn't exist.
[WARNING] If you need ESD CAN, please refer to:
[WARNING]   third_party/can_card_library/esd_can/README.md
[INFO] Build Overview:
[INFO]     USE_GPU:           1  [ 0 for CPU, 1 for GPU ]
[INFO]     GPU arch:          NVIDIA
[INFO]     CROSSTOOL_VERBOSE: 0  [ 0 for no verbose, 1 for verbose]
[INFO]     NVCC_VERBOSE:      0  [ 0 for no verbose, 1 for verbose]
[INFO]     Bazel Options:     --config=gpu --config=nvidia
[INFO]     Build Targets:     //modules/... union //cyber/...
[INFO]     Disabled:          except //modules/drivers/canbus/can_client/esd/...
+ bazel build --config=gpu --config=nvidia --copt=-mavx2 --host_copt=-mavx2 --jobs=20 '--local_ram_resources=HOST_RAM*0.7' -- //modules/... //cyber/... -//modules/drivers/canbus/can_client/esd/...
(03:02:13) INFO: Invocation ID: 4a5d1bb6-f140-41cd-8333-29c0d638f8ef
(03:02:13) INFO: Current date is 2023-03-26
(03:02:13) ERROR: Traceback (most recent call last):
	File "/apollo/third_party/tensorrt/tensorrt_configure.bzl", line 13, column 6, in <toplevel>
		"make_copy_files_rule",
Error: file '//third_party/gpus:cuda_configure.bzl' does not contain symbol 'make_copy_files_rule'
(03:02:13) ERROR: error loading package '': in /apollo/tools/workspace.bzl: Extension file 'third_party/tensorrt/tensorrt_configure.bzl' has errors
(03:02:13) INFO: Elapsed time: 0.050s
(03:02:13) INFO: 0 processes.
(03:02:13) FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by daohu527** [comment]
which version do you use, I merge the AMD support this week.

**Comment by fajingt** [comment]
> which version do you use, I merge the AMD support this week.

the latest apollo source，I update this morning.

**Comment by daohu527** [comment]
Got it, we'll fix it before this monday

**Comment by TongShuo-Demon** [comment]
how  to fix it

**Comment by YongLi000** [comment]
If it is fixed, how do I know this news?   And how can I successfully compile the source code?  thank u.

**Comment by daohu527** [comment]
@TongShuo-Demon @YongLi000 @fajingt fixed in #14857

**Comment by YongLi000** [comment]
I'm sorry to bother you again, but I modified the code according to your method and made another error.
when running "bash apollo.sh build" code, I find the following error:

(13:29:20) ERROR: /apollo/third_party/libtorch/BUILD:7:11: no such package '@libtorch_gpu//': The repository '@libtorch_gpu' could not be resolved and referenced by '//third_party/libtorch:libtorch'
(13:29:21) ERROR: Analysis of target '//modules/prediction/predictor:predictor_manager_test' failed; build aborted: Analysis failed
(13:29:21) INFO: Elapsed time: 5.639s
(13:29:21) INFO: 0 processes.
(13:29:21) FAILED: Build did NOT complete successfully (708 packages loaded, 1\
1774 targets configured)

thank u

**Comment by daohu527** [comment]
Pls check the file `third_party/libtorch/3rd-libtorch-gpu.BUILD`

Please make sure the code is consistent with master, I have tested it

**Comment by YongLi000** [comment]
I download the code again just now, and rebuild it. 
when running "bash apollo.sh build", it display "Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/server/jvm.out')".
so I guess that it may be due to a problem with system resources.
Then I run "bash apollo.sh build --local_resources 2048,1.0,1.0", but still display "[ERROR] Directory <APOLLO_ROOT_DIR>/modules/--local_resources not found. Exiting ...".

I cannot help it. And directly run "bash scripts/bootstrap.sh", then display :
root@in-dev-docker:/apollo# sudo bash scripts/bootstrap.sh
[INFO] No rocm-smi found.
[INFO] NVIDIA GPU device found.
nohup: appending output to 'nohup.out'
nohup: failed to run command 'cyber_launch': No such file or directory
[ERROR] Could not launch module monitor. Is it already built?
nohup: appending output to 'nohup.out'
nohup: failed to run command 'cyber_launch': No such file or directory
[ERROR] Could not launch module dreamview. Is it already built?

plz, thank u. @daohu527

**Comment by daohu527** [comment]
You can adjust the resource here

https://github.com/ApolloAuto/apollo/blob/cd07f3fd6d4ffb215f4a477355b41e928d3b0d7b/scripts/apollo_base.sh#L704

> --local_resources will be deprecated in Bazel 3.0.

ref https://github.com/bazelbuild/rules_nodejs/issues/1614

**Comment by YongLi000** [comment]
thank u.thank u. @daohu527 .  I run it successfully.

**Comment by daohu527** [comment]
Good news, can you tell me how many cores and memory your computer has? 

The memory limit of bazel is sometimes not very strict, so I am looking for a better solution

**Comment by YongLi000** [comment]
Is there any literature(papers) available on algorithms about Apollo such as the planning algorithm module, pls?  thank u.

**Comment by daohu527** [comment]
Here is one [Baidu Apollo EM Motion Planner](https://arxiv.org/abs/1807.08048).

I'm going to close this issue, because i problem has been solved

**Comment by YongLi000** [comment]
ok, thank u
