### ISSUE TITLE
Can Amazon and Google computing cloud services support Apollo 8.0 E2E?

### ISSUE THREAD

**Issue by mgcho0608** [ApolloAuto/apollo#14867]
I purchased an RTX 4090 to run Apollo 8.0, but I found out that its ada architecture is not supported by CUDA 11.1 in the Apollo 8.0 docker(#14858 , #14836 ). I tried various methods, but I learned that upgrading the CUDA, TensorRT, and CUDNN versions in the docker is the only solution (which, as @WildBeast114514 mentioned, requires a lot of work).

So my question is, while searching for alternative solutions before upgrading the versions, I discovered that Amazon and Google offer computing cloud services that include high-quality GPU. Therefore, I would like to ask about whether the GPU environments provided by these cloud services are able to run Apollo 8.0 E2E.

Here is a list of GPUs offered by Amazon and Google cloud services:
Amazon: NVIDIA A100, NVIDIA Tesla V100, NVIDIA K80, NVIDIA A10G, NVIDIA T4G, NVIDIA T4, AMD Radeon Pro V520, NVIDIA Tesla M60
Google: NVIDIA A100, NVIDIA Tesla T4, NVIDIA Tesla V100, NVIDIA Tesla P100, NVIDIA Tesla P4, NVIDIA Tesla K80

**Comment by qilinhu** [comment]
@mgcho0608 Hi！
We have deployed the apollo project on NVIDIA Tesla V100, you can try to test it on NVIDIA Tesla V100.
