### ISSUE TITLE
cyber rt混合使用了协程和线程，是否存在调度风险？

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#14865]
cyber rt使用了协程来调度程序。但是根据调试和代码阅读，发现cyber rt混合使用了协程和线程。这个对于调度会有什么样的风险。cyber rt无法操纵dds的线程。

如果引入更多的库默认创建的线程，调度系统的可靠性是怎么样的。

**Comment by daohu527** [comment]
We can only do what we can do.

**Cyber can only schedule coroutines**, the operating system can schedule threads, and apollo or cyber creates some threads and sets the priority, but we cannot control those not created by apollo and cyber.

Cyber is not operate system, if you create task use cyber::async then cyber can schedule it, but it is still restricted by the operating system, for example, it cannot control threads.

**Comment by fengmao31** [comment]
OK. Thanks.

**Comment by freekevinCode** [comment]
mark
