### ISSUE TITLE
cyber/data/cache_buffer.h useless using 

### ISSUE THREAD

**Issue by DieYoungWsn** [ApolloAuto/apollo#14879]
Recently, I was learning code related to Cyber and found that Cyber/data/cache_ buffer.h.
 The two lines of code in the file are useless, it is recommended to delete them.

32: using value_ type = T;
33: using size_ type = std::size_ t;

**Comment by DieYoungWsn** [comment]
As I delved deeper into my studies, I found that there was too much useless code, so let's forget it!

**Comment by daohu527** [comment]
Thanks for your suggestions, we will continue to optimize these codes
