### ISSUE TITLE
How to create a custom HD Map?

### ISSUE THREAD

**Issue by Yang2581** [ApolloAuto/apollo#14888]
### System information

- **OS Platform and Distribution windows11(roadrunner) Ubuntu22.04(Apollo)**:
- **Apollo installed from source **:
- **Apollo version 7.0**:

### Steps to reproduce the issue:
Hey dalaos, I'm wondering how the apollo hd map built. When I search "how to generate an apollo map", there is always the answer that using bag data.....

- But I want to know if there is a software or platform which support editing the map like prescan, VTD or roadrunner and it can generate the map file which Apollo can use.
- I trying to use roadrunner for editing map and export it as base_map.txt(it can be used in apollo), but it always lost some assets like triffic light and stop sign. So in dreamview, I can see nothing but a bare map(without any traffic light or crosswalk which I have defined in roadrunner).

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/37030670/232377317-61132b61-f2f2-402a-a1c0-976543ba59af.png)

**Comment by Yang2581** [comment]
Is that I must choose the certain assets which is compatible to Apollo?

**Comment by daohu527** [comment]
Apollo does not need these objects, which are model files used by roadrunner. The normal process is to add traffic lights in roadrunner, and then export to apollo format.

So we first need to solve the problem of the first step. this answer might help
https://www.mathworks.com/matlabcentral/answers/525457-placing-pedestrian-and-bicycle-traffic-light-in-roadrunner

**Comment by YongLi000** [comment]
@daohu527 @Yang2581 Sorry to bother you, how to get this software (roadrunner) ?  thanks, pls.

**Comment by daohu527** [comment]
roadrunner is integrated in matlab, if you are a student you can apply for a free trial.

**Comment by YongLi000** [comment]
excuse me, if I want to build my school's map. this map does not contain elements such as traffic lights. What is the most convenient way for me to build? or which software? pls, thanks

**Comment by YongLi000** [comment]
sorry, Is there a way to build a map for my own use without uploading it to the official site? The simpler my operation, the better. For example, a school map is constructed by some software and then exported in the file format corresponding to Apollo. thanks!!

**Comment by daohu527** [comment]
For now, apollo don't have such tools, you can make maps from recorded tracks, but it can't make a more complicated map. If there is a tool, then it is roadrunner.

A corresponding mapping tool is under consideration, but I'm not sure when it will be ready.

**Comment by YongLi000** [comment]
@daohu527 ok, thank you very much
