### ISSUE TITLE
CyberRT:同一个物理主机上的不同docker之间怎么通过FastRTPS通信

### ISSUE THREAD

**Issue by Jiangkui12** [ApolloAuto/apollo#14892]
Apollo version (8.0)

**Comment by daohu527** [comment]
You should first set docker network from host mode to bridge mode, then, use the same setting method as cross-host.

docker host mode do not support communication between dockers

**Comment by Jiangkui12** [comment]
不好意思，还有一个问题是我还需要与其他物理主机之间通过CyberRT进行通信，这个应该怎么设置?

**Comment by daohu527** [comment]
In this case you should use a bridge `modules/bridge`

**Comment by jilinzhouas** [comment]
Change `CYBER_IP` in cyber/setup.bash and restart the docker.
