### ISSUE TITLE
Question about converting recording files

### ISSUE THREAD

**Issue by AlexandrZabolotny** [ApolloAuto/apollo#14916]
Hello everybody
I have a couple questions. Perhaps someone has faced.

1) How can I convert an .mp4 video file to a record channel?
2) If there is a solution, how can it be done for 6 different video?

**Comment by daohu527** [comment]
To put it simply, first get pictures from video, sample them, and then publish these pictures

## steps
1. create a component, which include create 6 writers
2. create a function call `void SamplingVideo(const std::string& video_file)`, which responsible for sampling pictures from the video. You can use opencv `cap = cv2.VideoCapture('chaplin.mp4')` [ref link](https://learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/)
3. use writers to publish the images
