### ISSUE TITLE
预测数据结构查询

### ISSUE THREAD

**Issue by fpeanut** [ApolloAuto/apollo#14927]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version8.0**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **我播放demo3.5，然后运行prediction组件，cyber_monitor查看预测通道数据时，翻页翻不过去是什么原因。**:

**Comment by LordonCN** [comment]
You can use 'pageUp' and 'pageDown' to do that, at the same time 'ctrl + d' and 'ctrl + u' can also make it.
