### ISSUE TITLE
预测模块protobuf的数据结构问题

### ISSUE THREAD

**Issue by fpeanut** [ApolloAuto/apollo#14921]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version 8.0**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **我cyber_record demo3.5并打开预测组件时，用cyber_monitor查看预测的protobuf数据跟apollo官网的预测数据的数据结构不一样，少了很多信息，这是为什么。下图，第一个是我的查看，第二个是官网的实例结果。**:

### Supporting materials (screenshots, command lines, code/script snippets):
![1683256569570](https://user-images.githubusercontent.com/58199989/236388372-0af614f1-c793-4f26-ae58-78b7ae9ac89a.jpg)
![1683267270481](https://user-images.githubusercontent.com/58199989/236388460-d60bb3e7-f081-466f-b9dd-398093da2661.jpg)

**Comment by YuqiHuai** [comment]
![image](https://user-images.githubusercontent.com/34195403/236395348-81299c35-8767-4ee7-a0b9-4ab9943c7c07.png)

```
PgDn | ^d -- show next page
PgUp | ^u -- show previous page
```
@fpeanut 是不是需要在cyber_monitor里翻页？

**Comment by fpeanut** [comment]
> ![图像](https://user-images.githubusercontent.com/34195403/236395348-81299c35-8767-4ee7-a0b9-4ab9943c7c07.png)
> 
> ```
> PgDn | ^d -- show next page
> PgUp | ^u -- show previous page
> ```
> 
> @fpeanut是不是需要在cyber_monitor里翻页？

好的谢谢
