### ISSUE TITLE
apollo8.0 carla联合仿真

### ISSUE THREAD

**Issue by fpeanut** [ApolloAuto/apollo#14928]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version8.0**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **请问有没有对apollo8.0和carla联合仿真的更新，apollo8.0现在可以用Carla仿真吗？如果不能，是否有推荐的付费仿真软件？**:

**Comment by daohu527** [comment]
We have not tested the simulation of 8.0 and carla at present, I guess we will wait until q4 this year!

**Comment by YongLi000** [comment]
pls, I want to display value on terminal by "cout <<---", not in folder path "apollo/data/log". how to do? thanks

**Comment by qilinhu** [comment]
@YongLi000 you can print logs using "AINFO << ---".

**Comment by YongLi000** [comment]
@qilinhu I want to print it at terminal, "AINFO << ---" donot work. thanks,pls.

**Comment by IvDmNe** [comment]
@YongLi000 By default you have suppressed AINFO, AWARN and ADEBUG messages. AERROR is always displayed ,you can use it. Or to enable suppressed messages, add environment variables to your bash session:
```
GLOG_v=4 
GLOG_logtostderr=1
```

**Comment by meua** [comment]
> We have not tested the simulation of 8.0 and carla at present, I guess we will wait until q4 this year!

The project https://github.com/guardstrikelab/carla_apollo_bridge is also starting to support apollo 8.0 and Carla 0.9.14, and now we need the support of the apollo team very much, looking forward to your help.
