### ISSUE TITLE
How to reset car initial position and orientation by using SimControl on Dreamview

### ISSUE THREAD

**Issue by JfortissJ** [ApolloAuto/apollo#14934]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Dear Sir or Madam,

I'm using Apollo version 5.5 for virtual simulation and I met a problem about reset car initial position and orientation by using SimControl on Dreamview.

In the following pictures you can see I use a converted apollo map for the simulation, but the initial position and orientation of the ego car is wrong. I searched for some solutions online and got a suggestion like:

1. Open the Apollo Dreamview interface and go to the "Map" page by clicking on the "Map" button on the left-hand side of the screen.
2. Locate the car on the map and right-click on the car icon. This will bring up a menu.
3. Select "Set Start Pose" from the menu. A dialog box will appear.
4. In the dialog box, you can manually enter the new position and orientation of the car or click on the map to select the new position and orientation.
5. Click the "OK" button to confirm the new starting position and orientation. The car will move to the new starting point and restart path planning.

But I could not right-click on the car icon to bring up a menu.

I don't know if there is a difference for the steps on different Apollo versions. If I did wrong, please correct me. And if I should do it in another way, please tell me. Thank you very much for your support in advance!

Best regards

![1](https://github.com/ApolloAuto/apollo/assets/103105931/3b643909-bec5-4831-8766-fa5a8b964f66)
![Screenshot from 2023-05-11 22-22-08](https://github.com/ApolloAuto/apollo/assets/103105931/58e8b530-b8a6-413e-8e8a-476530558c72)
![Screenshot from 2023-05-11 22-22-25](https://github.com/ApolloAuto/apollo/assets/103105931/eed24d4f-c527-4dd0-95e0-76e88b16277a)

**Comment by YuqiHuai** [comment]
> Problem about reset the car's initial position and orientation when using SimControl on Dreamview

There are 2 ways of doing it.
1. You can take a look at https://cyber-rt.readthedocs.io/en/latest/CyberRT_API_for_Developers.html#writer-api and write a script that publishes localization messages. If you publish some localization messages before you turn on SimControl, SimControl be initialized at the location you published.

2. A bit hacky. You can send a routing request that starts and ends at the same location, and SimControl will "move" the car there. To do this, you click "Route Editing", find where you want the car to be, click on that location twice, and send the routing request.

I am not aware of the solution you posted here.

**Comment by YongLi000** [comment]
pls, I want to display value on terminal by "cout <<---", not in folder path "apollo/data/log". how to do? thanks

**Comment by YuqiHuai** [comment]
@YongLi000 is your question related to the post? Are you specifically asking for simcontrol?

**Comment by YongLi000** [comment]
@YuqiHuai ok,thanks

**Comment by JfortissJ** [comment]
Hi Yuqi! Thanks a lot for the help!

When I tried to use your 2. method, I met a new situation. I successfully moved the ego car to the desired position, but I also need to turn the direction of the car, I don't know how to do this?

![1](https://github.com/ApolloAuto/apollo/assets/103105931/b1e90bd0-f013-4c46-a653-6940572f434a)
![2](https://github.com/ApolloAuto/apollo/assets/103105931/9863564a-adbb-45c4-8ea2-a93674ab067d)

Thanks for the support!

**Comment by YuqiHuai** [comment]
Hi @JfortissJ , I am glad I can help.

1. `Sim-Control` looks at the coordinate and sets the car's heading according to the lane's direction ([citation](https://github.com/ApolloAuto/apollo/blob/446c9c6d481fef9853ab9f167a0e934092058244/modules/dreamview/backend/sim_control/sim_control.cc#L271)), why do you want to change the heading of the car?
2. If you want absolute control over `Sim-Control`, I am going to advertise my [`sim_control_standalone`](https://github.com/YuqiHuai/sim_control_standalone) to you. I extracted `Sim-Control` from Dreamview and created a `main` for it, so once you put it under `/apollo/modules` and compile it, you can do something like `/apollo/bazel-bin/modules/sim_control_standalone/main [x] [y] [heading]` and you will be supplying the `x`, `y`, `heading`. The repo currently supports both Apollo 7.0 and 8.0, and I am making changes to `r7.0.0` branch trying to fix #14918.

**Comment by JfortissJ** [comment]
Hi @YuqiHuai !

Thanks a lot for the support! I think I temporarily find out the solution with your help! 

Thanks again and best regards.

**Comment by YuqiHuai** [comment]
@JfortissJ grrat! If you find any bug/issue with the standalone version let me know and I’ll try my best to fix it.
