### ISSUE TITLE
about apollo cyber image

### ISSUE THREAD

**Issue by newwj** [ApolloAuto/apollo#14931]
Hi,
 I just want to find the image of Apollo CyberRT. Is it provided by the official? I couldn't find it in the Docker Hub
thanks

**Comment by fpeanut** [comment]
> 嗨， 我只是想找到 Apollo Cyber​​RT 的图像。是官方提供的吗？我在 Docker Hub 找不到它， 谢谢

We built a version of apollo8.0 cyber by ourselves, do you want to try it

**Comment by daohu527** [comment]
The official cyber docker image is here https://hub.docker.com/r/apolloauto/apollo/tags?page=1&name=cyber
