### ISSUE TITLE
How to convert the coordinates of obstacles from the world coordinate system to the car coordinate system（RFU）

### ISSUE THREAD

**Issue by yongjay** [ApolloAuto/apollo#14930]
hi all:

The Obstacle coordinates are defined as follows：

perception_obstacle.proto 
![image](https://github.com/ApolloAuto/apollo/assets/29766807/0c6f63be-08e1-49fb-9f8b-ac6cdcae18dc)

As you can see, the position is defined in world coordinates. 
My Question is:
How to convert the coordinates of obstacles from the world coordinate system to the car coordinate system（RFU）.

[Apollo Coordination Definition](https://github.com/ApolloAuto/apollo/blob/master/docs/05_Localization/coordination_cn.md)

**Comment by daohu527** [comment]
Simply put, you need to know the conversion relationship of **world2imu**. You can subscribe to the message output by tf, or calculate it through ego pose.
