### ISSUE TITLE
mainboard -d modules/perception/production/dag/dag_streaming_perception_camera.dag mainboard启动感知模块失败

### ISSUE THREAD

**Issue by suoni** [ApolloAuto/apollo#14949]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
输入命令后显示如下错误：
I0524 14:49:36.999063 71705 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I0524 14:49:36.999071 71705 module_argument.cc:60] []dag_conf: modules/perception/production/dag/dag_streaming_perception_camera.dag
E0524 14:49:38.494364 71705 file.cc:76] [mainboard]**Failed to open file /apollo/modules/perception/pipeline/config/camera_detection_pipeline_bev.pb.txt in text mode.**
E0524 14:49:38.494419 71705 file.cc:102] [mainboard]**Failed to open file /apollo/modules/perception/pipeline/config/camera_detection_pipeline_bev.pb.txt in binary mode.**
F0524 14:49:38.494429 71705 camera_obstacle_detection_component.cc:461] Check failed: cyber::common::GetProtoFromFile(camera_obstacle_perception_conf_file, &camera_obstacle_detection_config_) [perception]failed to load camera obstacle perception config file /apollo/modules/perception/pipeline/config/camera_detection_pipeline_bev.pb.txt
*** Check failure stack trace: ***
    @     0x7fc9f924a67d  google::LogMessage::Fail()
    @     0x7fc9f924cb3a  google::LogMessage::SendToLog()
    @     0x7fc9f924a08d  google::LogMessage::Flush()
    @     0x7fc9f924dae9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc9a636de79  apollo::perception::onboard::CameraObstacleDetectionComponent::InitConfig()
    @     0x7fc9a636bae0  apollo::perception::onboard::CameraObstacleDetectionComponent::Init()
    @     0x556d19cf5f3e  apollo::cyber::Component<>::Initialize()
    @     0x556d19cf9b5c  apollo::cyber::mainboard::ModuleController::LoadModule()
    @     0x556d19cf9fa2  apollo::cyber::mainboard::ModuleController::LoadModule()
    @     0x556d19cf95b0  apollo::cyber::mainboard::ModuleController::LoadAll()
    @     0x556d19cf6238  apollo::cyber::mainboard::ModuleController::Init()
    @     0x556d19cf4f7f  main
    @     0x7fc9f8103c87  __libc_start_main
    @     0x556d19cf4d6a  _start
    @              (nil)  (unknown)
Aborted

**Comment by flyflyfly0120** [comment]
do you solved it?

**Comment by rodhw** [comment]
Having the same issue. Did you solve it?
