### ISSUE TITLE
is there a resource where I can find more demo record files

### ISSUE THREAD

**Issue by barrykidney** [ApolloAuto/apollo#14942]
Apologies if this is not the right place to post a question like this. I'm a final year AI student and my dissertation will involve Apollo. I'm new to Apollo and I have been unable to find a community where I can ask beginner questions (please let me know if one exists). I could use a more extensive demo file than than (demo_3.5.record) one provided, I need one with a few lane changes. Is there a resource where I can find different demo files of the Sunnyvale loop? Thanks

**Comment by daohu527** [comment]
Here is one 
```
wget https://apollo-system.bj.bcebos.com/dataset/6.0_edu/sensor_rgb.tar.xz
```

There is currently a developer community, but it may not be friendly to English developers. https://apollo.baidu.com/
We have WeChat group and some online sharing.

I think the mailing group or Q&A community may be more suitable for global developers. We're building the community, until then please feel free to ask questions here, we'll try to help, you know the open source community needs everyone's participation

**Comment by barrykidney** [comment]
Thanks for the response and the file, but there aren't any lane changes in that file is it possible to get one with a few lane changes? 2 or 3 would be perfect.

**Comment by YuqiHuai** [comment]
@barrykidney I can generate some demo record files for you.
1. Which version of Apollo do you use? 
2. Do you just want the ego car (Apollo) move forward while changing lanes?

**Comment by barrykidney** [comment]
@YuqiHuai That would be great thank you, The lane changes are the main thing I need, but if there was a few other vehicles and one or two turns that would be perfect. I'm using Apollo 8. Thanks again

**Comment by YuqiHuai** [comment]
@barrykidney I am traveling at the moment but I should be able to get you some records within 24 hrs.

**Comment by YuqiHuai** [comment]
@barrykidney I got 2 scenarios for you [here](https://drive.google.com/drive/folders/1VGpMBeVXPrnnNrJBEM_-bhexUX_Ej2c8?usp=sharing). Here are the steps to create scenarios like this:
1. Launch Dreamview via `bash scripts/bootstrap.sh`
2. Make sure you fixed the manual traffic light following instructions [here](https://github.com/ApolloAuto/apollo/issues/14860#issuecomment-1487860852)
3. In Dreamview (`http://localhost:8888`), select Sunnyvale Loop on the top right, and turn on SimControl (Tasks > Other > SimControl)
4. Start controlling traffic lights via `bash scripts/manual_light.sh`, make sure the signal is green when the ego car reaches the junction.
5. Now in Dreamview, turn on Planning and Routing from `Module Controller`
6. Again in Dreamview, select 2 points on the map, SimControl will move the ego car from the first point (initial location) to the second point (final location) following the output of the planning module.
---
Adding a few other vehicles isn't that easier so it will take me a bit longer, but I'll share some with you later today as well.

**Comment by barrykidney** [comment]
@YuqiHuai Thanks for those files, I'm really only starting out so I can switch to Apollo 7 no problem.
