### ISSUE TITLE
可以不可以创建个做无谓的，或者有可以用的发个链接

### ISSUE THREAD

**Issue by Huwenbo-git** [ApolloAuto/apollo#14959]
可以不可以开发个中文文档，或者有没有已经有的

**Comment by YuqiHuai** [comment]
类似这样的吗 https://github.com/ApolloAuto/apollo/blob/master/modules/planning/README_cn.md, https://github.com/ApolloAuto/apollo/blob/master/modules/prediction/README_cn.md

**Comment by daohu527** [comment]
There are already some Chinese documents [here](https://apollo.baidu.com/), you know that there are not only Chinese users on github, so we suggest that it is best to use English.
