### ISSUE TITLE
CyberRT 适配的 fastdds 是哪个版本？

### ISSUE THREAD

**Issue by RelaxOne** [ApolloAuto/apollo#14969]
目前想使用 CyberRT 集成 fastdds，但是目前不知道适配的版本是哪个，求解答！！！

**Comment by nagareru** [comment]
CyberRT使用的是很早的一个版本，fastrtps-1.5.0

**Comment by yongjay** [comment]
[这里](https://github.com/minhanghuang/CyberRT/issues/20)或许能提供一些参考
