### ISSUE TITLE
Wonder if still the dreamview can not launch on two different systems at the same time

### ISSUE THREAD

**Issue by jumogehn** [ApolloAuto/apollo#14979]
On [this page](https://github.com/ApolloAuto/apollo/blob/master/docs/01_Installation%20Instructions/how_to_setup_dual_ipc.md), the Future work (to do) was making the dreamview runnable on multiple systems at the same time.
I wonder if this plan still on going or already acomplished. If it is complished already, I'd like to know how to setup the dreamview for running on multiple systems.

**Comment by daohu527** [comment]
dreamview already support cross host!

If I understand correctly, you want to start apollo on one machine, and start dreamview on another machine. you can change the ip from localhost to real ip adress(eg: 192.168.1.20) of the computer running apollo.
```
localhost:8888 -> your_ip:8888
```

**Comment by jumogehn** [comment]
Hello, @daohu527 ,

I think I need to explain what we want more.

We'd like to utilize two systems. Suppose we have system A and system B.
On each systems, different sensors are attached - some sensors on system A, the other sensors on system B.
System A and system B are in a same ipv4 subnet.
There is only one cyber channel across system A and system B. Publisher and subscribers on system A and system B can communicate via the same cyber channel.

The dreamview webservers run on each systems. So there exist two dreamview webservers - one on system A and the other on system B.

- The subnet can be 192.168.10.0 / 24
- ip address of system A can be 192.168.10.1 / 24
- ip address of system B can be 192.168.10.2 / 24
- the web page for dreamview on system A can be accessed via http://192.168.10.1:8888
- the web page for dreamview on system B can be accessed via http://192.168.10.2:8888

Is this already accomplished?

**Comment by daohu527** [comment]
I didn't find problem. In theory, there is a node in the backend of dreamview, and there may be a duplicate name error.

Dreamview uses websocket to communicate with the backend, so I think for dreamview it only cares about itself

**Comment by jumogehn** [comment]
Hello, @daohu527 ,

You are right!
We made it work!
Number of node names we had to change was 6 or 7 from the dreamview.
Thank you!
