### ISSUE TITLE
build dreamview error

### ISSUE THREAD

**Issue by cherishTMYY** [ApolloAuto/apollo#14978]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:openEuler
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:8.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
bash apollo.sh build_cpu dreamview

### Supporting materials (screenshots, command lines, code/script snippets):

(20:05:13) INFO: Invocation ID: b87064bb-52e5-48d7-8400-f7730f5dc6ef
(20:05:15) INFO: Current date is 2023-06-05
(20:05:16) INFO: Analyzed 159 targets (0 packages loaded, 0 targets configured).
(20:05:16) INFO: Found 159 targets...
(20:05:31) ERROR: /apollo/apollo-v8.0.0/modules/dreamview/backend/BUILD:43:10: Linking modules/dreamview/backend/libbackend.so failed: (Exit 1): gcc failed: error executing command
  (cd /apollo/apollo-v8.0.0/.cache/bazel/6703445324e57066f8e9637d3f3146a3/execroot/apollo && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/fast-rtps/lib/:/usr/local/lib64:/opt/apollo/sysroot/lib64 \
    PATH=/apollo/bazel-bin/modules/tools/visualizer:/apollo/bazel-bin/cyber/tools/cyber_launch:/apollo/bazel-bin/cyber/tools/cyber_service:/apollo/bazel-bin/cyber/tools/cyber_node:/apollo/bazel-bin/cyber/tools/cyber_channel:/apollo/bazel-bin/cyber/tools/cyber_monitor:/apollo/bazel-bin/cyber/tools/cyber_recorder:/apollo/bazel-bin/cyber/mainboard:/home/openeuler/java/dragonwell-11.0.18.14+9-GA/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib64/python3.9/site-packages \
  /usr/bin/gcc @bazel-out/riscv64-fastbuild/bin/modules/dreamview/backend/libbackend.so-2.params)
Execution platform: @local_config_platform//:host
/usr/bin/ld: error: /usr/lib64: read: Is a directory
collect2: error: ld returned 1 exit status
(20:05:32) INFO: Elapsed time: 19.181s, Critical Path: 13.89s
(20:05:32) INFO: 20 processes: 1 remote cache hit, 14 internal, 5 local.
(20:05:32) FAILED: Build did NOT complete successfully

**Comment by cherishTMYY** [comment]
@daohu527 
Do you know how bazel generates the libbackend. so 2. params file? I found that there is a syntax error in this file.

**Comment by daohu527** [comment]
it's auto generate by bazel rule, the `copts` will pass param to gcc
https://github.com/ApolloAuto/apollo/blob/446c9c6d481fef9853ab9f167a0e934092058244/modules/dreamview/backend/BUILD#L10-L15

**Comment by cherishTMYY** [comment]
> it's auto generate by bazel rule, the `copts` will pass param to gcc
> 
> https://github.com/ApolloAuto/apollo/blob/446c9c6d481fef9853ab9f167a0e934092058244/modules/dreamview/backend/BUILD#L10-L15

Thank you for your reply. The problem has been resolved
