### ISSUE TITLE
apollo8.0 怎么检验多传感器融合算法，能在dreamview体现吗

### ISSUE THREAD

**Issue by 1121085292** [ApolloAuto/apollo#14980]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by daohu527** [comment]
you need to run lidar and camera detection module and fusion moudle. Then you can see the result on dreamview or cyber_monitor.

**Comment by Castle-Boy** [comment]
你好，我按照apollo8.0文档进行场景四：感知激光雷达功能测试时，直接按教程不能启动激光雷达模块，提示未找到/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/内文件，我在对/apollo/modules/perception/pipeline/config/lidar_detection_pipeline.pb.txt文件进行如下更改后，
![Picture4](https://github.com/ApolloAuto/apollo/assets/109893032/79c9860e-85f9-47a3-be28-ef51f2f42a91)
启动激光雷达检测模块后，卡在这个界面是什么问题？
![Picture2](https://github.com/ApolloAuto/apollo/assets/109893032/d0715bff-01df-4fd7-b096-7bcbdcb9fff3)
是更改文件需要使用buildtool build --gpu --packages modules/perception命令重新编译吗？但编译报错
![Picture3](https://github.com/ApolloAuto/apollo/assets/109893032/507b3e81-3914-4efb-a78c-cd3487b16cc8)

**Comment by yongjay** [comment]
> 你好，我按照apollo8.0文档进行场景四：感知激光雷达功能测试时，直接按教程不能启动激光雷达模块，提示未找到/apollo/modules/perception/production/data/perception/lidar/models/cnnseg/cnnseg128_caffe/内文件，我在对/apollo/modules/perception/pipeline/config/lidar_detection_pipeline.pb.txt文件进行如下更改后， ![Picture4](https://user-images.githubusercontent.com/109893032/244583634-79c9860e-85f9-47a3-be28-ef51f2f42a91.png) 启动激光雷达检测模块后，卡在这个界面是什么问题？ ![Picture2](https://user-images.githubusercontent.com/109893032/244583620-d0715bff-01df-4fd7-b096-7bcbdcb9fff3.png) 是更改文件需要使用buildtool build --gpu --packages modules/perception命令重新编译吗？但编译报错 ![Picture3](https://user-images.githubusercontent.com/109893032/244583630-507b3e81-3914-4efb-a78c-cd3487b16cc8.png)

这个错误不影响功能，直接播放数据就可以在dreamview中看到数据了
