### ISSUE TITLE
有没有关于Apollo自定义的高精地图标准的说明文档呀？

### ISSUE THREAD

**Issue by Wokening** [ApolloAuto/apollo#14993]
目前想自己制作用于无人驾驶的高精地图，但是没有找到关于Apollo自定义高精地图标准的完善的说明文档，有无大佬可以提供一些参考？

**Comment by YuqiHuai** [comment]
I read through https://github.com/ApolloAuto/apollo/tree/master/modules/common_msgs/map_msgs to understand the definition of HDMap. If there is no additional documentation, these protobuf definitions should be the best way to learn about HDMaps.
