### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by adrianhust** [ApolloAuto/apollo#15]
excute bash apollo.sh build, then throw this error:

ERROR: /home/work/apollo/modules/planning/BUILD:3:1: no such package 'third_party/ros': BUILD file not found on package path and referenced by '//modules/planning:lib_planning'.
ERROR: Analysis of target '//modules/planning:lib_planning' failed; build aborted.

**Comment by andrewraharjo** [comment]
You may want to pull the docker first. Apollo runs on the custom ROS framework. It seems the error because it is looking for `docker` installed third party ROS package.

**Comment by ycool** [comment]
@adrianhust  Do you still have a problem after installing docker?

```
bash docker/scripts/install_docker.sh
# logout and login to make sure to run docker command without sudo
docker ps  # to verify docker works without sudo
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash apollo.sh build # inside docker
```

If not, we will close this issue.  

Thanks.

**Comment by Creemli** [comment]
Mac is not supported?
```[ERROR] Please use Linux, we recommend Ubuntu 14.04.```

**Comment by ycool** [comment]
@Creemli  Yeah. Currently, it mainly works in Linux env. Mac needs some extra development. Track at #47 .  please vote it up. If it has high demand, we can bump up its priority. Thanks.
