### ISSUE TITLE
How to set the lane follow distance when there is a special vehicle in front of ego car?

### ISSUE THREAD

**Issue by 2378822760** [ApolloAuto/apollo#15017]
In some scenarios, keep safe distance from some special vehicles is necessory, but I can't find an easy way to reach this goal. I have almost read all codes of planning module but still can't solve this problem. Can you offer me some suggestions? I know it may be in speed planning module.

### System information

- **Linux Ubuntu 18.04**:
- **Apollo installed from binary**:
- **Apollo version 8.0**:

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/ApolloAuto/apollo/assets/90468784/fc1979cc-71fd-40bc-a288-b8912db740d2)

**Comment by ycraurora** [comment]
Here it is:

In nonlinar optimizer: https://github.com/ApolloAuto/apollo/blob/d5f88cb390d01cc15bc11d9af484d8e5a34d218f/modules/planning/tasks/optimizers/piecewise_jerk_speed/piecewise_jerk_speed_nonlinear_optimizer.cc#L286C69-L286C69

In linar optimizer:
https://github.com/ApolloAuto/apollo/blob/d5f88cb390d01cc15bc11d9af484d8e5a34d218f/modules/planning/tasks/optimizers/piecewise_jerk_speed/piecewise_jerk_speed_optimizer.cc#L114

**Comment by 2378822760** [comment]
Thanks!
