### ISSUE TITLE
apollo支持cv::videowriter

### ISSUE THREAD

**Issue by windmakeppcool** [ApolloAuto/apollo#15021]
我想将感知结果保存成视频，但使用时会报undefined symbol: _ZN2cv11VideoWriter5writeERKNS_11_InputArrayE错误，请问apollo在编三方库得时候是没有添加video支持吗？如果没有添加如何添加呢？

**Comment by fpeanut** [comment]
> 我想将感知结果保存成视频，但使用时会报undefined symbol: _ZN2cv11VideoWriter5writeERKNS_11_InputArrayE错误，请问apollo在编三方库得时候是没有添加video支持吗？如果没有添加如何添加呢？

没有添加，我试过了，不能用videocapture
