### ISSUE TITLE
planning模块发布数据的设置

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#1504]
您好，
    现在在看planning模块，大体执行流程可以看得明白，大体如下：
    超时时执行Planning::OnTimer---> Planning::RunOnce在这里定义了trajectory_pb--->Planning::Plan()--->EMPlanner::Plan()--->optimizer->Execute()在这里调用各个task。

  看到trajectory_pb在Planning::RunOnce()中定义之后，然后在Planning::Plan函数中设置其中的debug，latency_stats和decision项，然后调用planner_->Plan(stitching_trajectory.back(), frame_.get(),
                            &reference_line_info);
在此函数中trajectory_pb并没有作为参数，其主要的数据成员trajectory_point和path_point是在哪里设置的？
还有stitching_trajectory的作用是什么？感觉planning模块难度比较大，有没有比较详细些的资料介绍？谢谢。

**Comment by xiaoxq** [comment]
1. 正如你所见，planner_->Plan() 接收了reference_line_info，而且其实它也是 frame_ 的成员之一。完成一轮计算后会调用 Frame::FindDriveReferenceLineInf() 找到一条cost最小的reference line, 调用PopulateTrajectoryProtobuf(trajectory_pb)填入进去。

2. stitching_trajectory是为了缝合上一帧trajectory 与当前帧，使过渡平滑。参考TrajectoryStitcher::ComputeStitchingTrajectory

**Comment by lianglia-apollo** [comment]
You can refer docs/specs/qp_spline_path_optimizer.md, docs/specs/qp_spline_st_speed_optimizer.md, and docs/specs/reference_line_smoother.md for the major algorithms in planning module. We will try our best to complete a full document for planning in a near future.

**Comment by yiakwy** [comment]
@xiaoxq thumb up

**Comment by yiakwy** [comment]
Router will return a response containing road segments searched by A*star, an a planner will digest it to generate fine tuned trajectory data. @ahuer2435 was asking where trajectory_pb come from. I guest it populated by the planner algorithm for publish. Am I right?

**Comment by lianglia-apollo** [comment]
The "trajectory_pb" comes from the plan function in planning.cc.

Status Planning::Plan(const double current_time_stamp,
                      const std::vector<TrajectoryPoint>& stitching_trajectory,
                      ADCTrajectory* trajectory_pb);
