### ISSUE TITLE
version 8.0 huge load of cpu because of openmp (iomp)

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#15058]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: ubuntu20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 8.0
- **Output of `apollo.sh config` if on `master` branch**: 

After upgrade from 7.0.0  to 8.0.0 , when I run perception lidar (surely I add some custom code), the cpu usage is unnormally high (comparing to version 7.0.0), Then I use intel vTune to profile the whole system, I found __kmp_lanuch_thread & __kmp_fork_barrier cost too much . I dont know what's the difference between 7.0 and 8.0 when refer to OpenMP

here is the vtune result:

![截图 2023-07-27 19-12-43](https://github.com/ApolloAuto/apollo/assets/1448987/a57af1dd-e0b8-472f-ab31-465fd926c559)

**Comment by sinopec** [comment]
it seems the "paddleinference" package bring in libiomp depends, instead of libgomp,while libiomp cost too much .

**Comment by sinopec** [comment]
In someplace of  my custom code, i use opencv's cvtColor to change colorspace from RBG2BGR, after i comment this line ,everything will be fine just like apollo 7.0.0.
I am wondering how can this happed, anything updated about opencv?

**Comment by daohu527** [comment]
No, opencv not updated. We will check the reason, can you provide more steps to reproduce?

**Comment by sinopec** [comment]
> 

after rebuild opencv with intel TBB on ,  The CPU load has dropped to a normal level.
