### ISSUE TITLE
Register new vehicle according to instruction

### ISSUE THREAD

**Issue by CesarLiu** [ApolloAuto/apollo#15056]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 18.04
- **Apollo installed from (source)**: source
- **Apollo version (8.0 or master branch)**: master branch
- **Output of `apollo.sh config` if on `master` branch**:
- [INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR:   /apollo
[INFO]     APOLLO_CACHE_DIR:  /apollo/.cache
[INFO]     APOLLO_IN_DOCKER:  true
[INFO]     APOLLO_VERSION:    merge_from_fortiss-2023-07-25-96dd2a68ef
[INFO]     DOCKER_IMG:        dev-x86_64-18.04-20221124_1708
[INFO]     APOLLO_ENV:        STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU_HOST:      1
[INFO]     USE_GPU_TARGET:    1
[INFO]     GPU_PLATFORM:      NVIDIA
[INFO] Configure .apollo.bazelrc in non-interactive mode
[INFO] You have bazel 3.7.1 installed.
[INFO] Found possible Python library paths:
       /usr/local/lib/python3.6/dist-packages
       /usr/lib/python3/dist-packages
[INFO] Found CUDA 11.1 in:
       /usr/local/cuda-11.1/targets/x86_64-linux/lib
       /usr/local/cuda-11.1/targets/x86_64-linux/include
[INFO] Found cuDNN 8 in:
       /usr/lib/x86_64-linux-gnu
       /usr/include
[INFO] Found TensorRT 7 in:
       /usr/lib/x86_64-linux-gnu
       /usr/include/x86_64-linux-gnu
[ OK ] Successfully configured .apollo.bazelrc in non-interactive mode.
[INFO] Usage: /apollo/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- To register our own vehicle I checked this tutorial: https://github.com/ApolloAuto/apollo/blob/master/docs/11_Hardware%20Integration%20and%20Calibration/%E8%BD%A6%E8%BE%86%E9%80%82%E9%85%8D/how_to_add_a_new_vehicle.md#register-the-new-vehicle
- However in the master branch or 8.0.0 there is no more vehicle_factory.cc to call this "RegisterVehicleFactory"
- Is this a bug of the current version, or we don't need it anymore? Do you have a new tutorial to add new vehicles?

**Comment by HandsomeAIccx** [comment]
Hi there. I am also trying to register a new vehicle and faced the same problem with the vehicle_factory.cc file missing. May I check if you have managed to resolve this issue and successfully registered a new vehicle on the latest Apollo release?  I'd really appreciate if you could share how you got it working. If you also haven't found a solution yet, we could continue to discuss in this thread and try to figure it out together. Thanks!

**Comment by CesarLiu** [comment]
In the current version of apollo, they change the module structure and made vehicle integration more independent. I personally like this but adaptation of the old setting and proto files need to be adapted. Honestly, I haven't yet finish the adaption at my side. But if you have already go through the apollo_vehicle_adaption_tutorial, just try to imitate the available vehicles in apollo: https://github.com/ApolloAuto/apollo/tree/master/modules/canbus_vehicle should work
