### ISSUE TITLE
[Bug Report]some abnormal situations in the operation of the vehicle

### ISSUE THREAD

**Issue by zsan2023** [ApolloAuto/apollo#15061]
**I found seven abnormal situations in the operation of the vehicle. I will discribe them with videos.(run with carla-apollo bridge)**

**Operating environment:**
 **·** OS : Ubuntu 18.04.6 LTS
 **·** Browser : Edge and Firefox
 **·** Carla : Version 0.9.14
 **·** Apollo : Version 7.0
 **·** Bridge : https://github.com/guardstrikelab/carla_apollo_bridge

**Comment by zsan2023** [comment]
**situation1.**
The vehicle can not reverse.

https://github.com/ApolloAuto/apollo/assets/87601573/69185f7a-23b8-4f2b-8307-8a387b73e36f

**Comment by zsan2023** [comment]
**situation2**
ignored the bicycle(Bicycle detected but no respond)

https://github.com/ApolloAuto/apollo/assets/87601573/4cd3c475-b2e9-4d14-adb9-807e6186683f

**Comment by zsan2023** [comment]
**situation3**
The responsibility lies with the rear-end collision. But the control of the speed is clearly  imperfect.


https://github.com/ApolloAuto/apollo/assets/87601573/b438445b-5c07-4ec7-ae89-bbe81e952e12

**Comment by zsan2023** [comment]
**situation4**
Lack of alertness to road conditions（maybe prediction?）

https://github.com/ApolloAuto/apollo/assets/87601573/d496132f-02fd-4b4c-8d96-fe3f15011f71

**Comment by zsan2023** [comment]
**situation5**
Unexpected retrograde


https://github.com/ApolloAuto/apollo/assets/87601573/5f69033b-6560-4cc5-b64d-e2a2732bc93e

**Comment by zsan2023** [comment]
**situation6**
Serious problem in vehicle steering


https://github.com/ApolloAuto/apollo/assets/87601573/ebf3f514-12f7-4f16-8508-7a252c26113c

**Comment by zsan2023** [comment]
**situation7**
Losing control while driving


https://github.com/ApolloAuto/apollo/assets/87601573/f6071f09-77d6-47ac-aa50-f9967a8dbbfc

**Comment by zsan2023** [comment]
I wonder how these happening. Which modules do the problems come from? Looking forward to an answer.

**Comment by daohu527** [comment]
We cannot analyze the problem from the video. You know that these problems may involve various aspects, so I suggest that you can analyze the general cause of the problem before we accept it.

While this may seem a bit harsh, the comprehensive question of autopilot requires logs, records, context at the time, etc., so it's unlikely we'll be able to analyze all of them, and we'll prioritize our own tests unless you can provide something more robust evidence of

**Comment by zsan2023** [comment]
I have some bugs with records(which can be replayed by carla python api).**You can reproduce the bug using the following steps.**I will report the bug along with the corresponding record.

**Operating environment:**
· OS : Ubuntu 18.04.6 LTS
· Browser : Edge and Firefox
· Carla : Version 0.9.14
· Apollo : Version 7.0
· Bridge : https://github.com/guardstrikelab/carla_apollo_bridge

1.You can install the required environment using this link:https://github.com/guardstrikelab/carla_apollo_bridge
2.Place the .log file in the /home/xxx/.config/Epic/CarlaUE4/saved folder.
3.Then, enter the container for carla_cyber 0.9.14 and execute the following commands:
       **cd /apollo/cyber/carla_bridge/carla_python/examples**
       **python start_replaying.py -f name_of_logfile**
   Alternatively, you can execute the command on your local machine in the path **carla_apollo_bridge/src/carla_python/examples**:
          **python start_replaying.py -f name_of_logfile**
4.At this moment, you can simultaneously observe the complete reproduction of the bug in Dreamview and Carla.

Due to my limited capabilities, I'm unable to provide specific attribution analysis for these bugs. Incorrect analysis could potentially mislead your work.Please accept my apologies for any inconvenience caused.

**Comment by zsan2023** [comment]
I will be reporting a total of five bugs. They are: unstable steering, scraping at T-junctions, failure to respond to detected bicycles, congestion at T-junctions, and collisions at T-junctions. 
**All of the bugs can be fully reproduced using the corresponding records.**


bug1:The vehicle exhibits unstable behavior during turns.
record : https://drive.google.com/file/d/1E_fPYUFZ4RuveVKYDpzgeP6nj900qpZH/view?usp=drive_link

Video from the perspective of Dreamview：

https://github.com/ApolloAuto/apollo/assets/87601573/d7aacb0c-3a96-440e-8971-758f28d0ea09

Video from the perspective of Carla：

https://github.com/ApolloAuto/apollo/assets/87601573/02881682-bda3-421d-9d61-036cbe32a1a8

**Comment by zsan2023** [comment]
bug2: The vehicle failed to yield correctly at a T-junction, resulting in a scrape (similar to the fifth bug).
record : https://drive.google.com/file/d/1OIyt8dTHdTxS47FdqordbF1tizCSQ2-1/view?usp=drive_link

Video from the perspective of Dreamview：

https://github.com/ApolloAuto/apollo/assets/87601573/240cb196-7132-44e2-bbbc-9f1ebd81c439

Video from the perspective of Carla：

https://github.com/ApolloAuto/apollo/assets/87601573/2c528959-a15f-4380-a6e9-1a4b9cb51eb3

**Comment by zsan2023** [comment]
bug3: The vehicle accurately detected the bicycle ahead but failed to respond, resulting in a collision.
record: https://drive.google.com/file/d/1Za_cRsi04Z4X8SmmcG9olovlD8yeMlWn/view?usp=drive_link

Video from the perspective of Dreamview：

https://github.com/ApolloAuto/apollo/assets/87601573/b00266b7-b907-41e8-a5bd-8cfad2b34cf8

Video from the perspective of Carla：

https://github.com/ApolloAuto/apollo/assets/87601573/717bceff-e097-4697-9410-0f13b4e940e0

**Comment by zsan2023** [comment]
bug4 : The vehicle failed to adjust its driving state correctly while turning, leading to congestion.
record : https://drive.google.com/file/d/1QHKtV6zusLiKcfFKVEwptzllInp8E8ZC/view?usp=drive_link

Video from the perspective of Dreamview:

https://github.com/ApolloAuto/apollo/assets/87601573/75359e86-3a1e-467d-ac21-dcb0154d471b

Video from the perspective of Carla：

https://github.com/ApolloAuto/apollo/assets/87601573/05e23326-ef65-4143-b843-45d59d43fa31

**Comment by zsan2023** [comment]
bug5 : The vehicle crashed at a T-junction
record : https://drive.google.com/file/d/1HSCpazoiDf0PzM8j1gvUdbewUQGVSQHD/view?usp=drive_link

Video from the perspective of Dreamview:

https://github.com/ApolloAuto/apollo/assets/87601573/8eae6205-ad45-4bd0-918d-e999a9fcd4e4

Video from the perspective of Carla:

https://github.com/ApolloAuto/apollo/assets/87601573/3754ccd8-75e5-4222-b0ce-bfefc57ff631

**Comment by zsan2023** [comment]
> We cannot analyze the problem from the video. You know that these problems may involve various aspects, so I suggest that you can analyze the general cause of the problem before we accept it.
> 
> While this may seem a bit harsh, the comprehensive question of autopilot requires logs, records, context at the time, etc., so it's unlikely we'll be able to analyze all of them, and we'll prioritize our own tests unless you can provide something more robust evidence of

Perhaps you could take a look at the new bug I've submitted. All of them have records and are reproducible.

**Comment by YuqiHuai** [comment]
Hi @zsan2023 , I took a look at some of your videos, I don't think there is sufficient evidence for most of these recordings to be considered bugs from Apollo.

---
For example, if a bicyclist is detected, a blue 3D bounding box should appear in Dreamview (as documented [here](https://github.com/ApolloAuto/apollo/blob/master/docs/13_Apollo%20Tool/%E5%8F%AF%E8%A7%86%E5%8C%96%E4%BA%A4%E4%BA%92%E5%B7%A5%E5%85%B7Dremview/dreamview_usage_table.md)). But from your video, we can see a heading symbol is drawn without any bounding box, which is abnormal. I am leaning toward believing this is a Carla-Apollo bridge problem, more specifically the 3D perception ground truth being incorrect. Since I observed the bounding box for other cars are perfect cuboids,my guess is you are using ground truth perception, and the bicyclist is sent to Apollo without dimensions (i.e., height, width, length).

|From Your Video|Expected Visual in Dreamview|
|---------------|------------------|
|<img width="224" alt="image" src="https://github.com/ApolloAuto/apollo/assets/34195403/3e71eaec-5d49-442e-84ac-35261c6f29f1">|<img width="489" alt="image" src="https://github.com/ApolloAuto/apollo/assets/34195403/be898b13-838d-4aa7-aa8e-cdc1e7d7f2b4">|

---
In all the other videos you have uploaded in the comment section, I observed the delay of the planning module being unreasonably high. This might be a recording issue, but if the planning module is running and actively making decisions, the delay of the planning module should be similar to the delay of the prediction module, no matter if you are replaying/recording a record file or running a simulation.
<img width="277" alt="image" src="https://github.com/ApolloAuto/apollo/assets/34195403/3f26507e-d02d-4169-80aa-b1110c027dde">

---
I do agree there might be some control issues when using Apollo with Carla especially when turning, as there are also issues submitted by others talking about this, but it is still unclear if it is a bug in Apollo or just an interfacing issue between Apollo and Carla.

**Comment by zsan2023** [comment]
> Hi @zsan2023 , I took a look at some of your videos, I don't think there is sufficient evidence for most of these recordings to be considered bugs from Apollo.
> 
> For example, if a bicyclist is detected, a blue 3D bounding box should appear in Dreamview (as documented [here](https://github.com/ApolloAuto/apollo/blob/master/docs/13_Apollo%20Tool/%E5%8F%AF%E8%A7%86%E5%8C%96%E4%BA%A4%E4%BA%92%E5%B7%A5%E5%85%B7Dremview/dreamview_usage_table.md)). But from your video, we can see a heading symbol is drawn without any bounding box, which is abnormal. I am leaning toward believing this is a Carla-Apollo bridge problem, more specifically the 3D perception ground truth being incorrect. Since I observed the bounding box for other cars are perfect cuboids,my guess is you are using ground truth perception, and the bicyclist is sent to Apollo without dimensions (i.e., height, width, length).
> 
> From Your Video	Expected Visual in Dreamview
> <img alt="image" width="224" src="https://user-images.githubusercontent.com/34195403/259264392-3e71eaec-5d49-442e-84ac-35261c6f29f1.png">	<img alt="image" width="489" src="https://user-images.githubusercontent.com/34195403/259264478-be898b13-838d-4aa7-aa8e-cdc1e7d7f2b4.png">
> In all the other videos you have uploaded in the comment section, I observed the delay of the planning module being unreasonably high. This might be a recording issue, but if the planning module is running and actively making decisions, the delay of the planning module should be similar to the delay of the prediction module, no matter if you are replaying/recording a record file or running a simulation. <img alt="image" width="277" src="https://user-images.githubusercontent.com/34195403/259265031-3f26507e-d02d-4169-80aa-b1110c027dde.png">
> 
> I do agree there might be some control issues when using Apollo with Carla especially when turning, as there are also issues submitted by others talking about this, but it is still unclear if it is a bug in Apollo or just an interfacing issue between Apollo and Carla.

Thank you for your reply! It is helpful.
