### ISSUE TITLE
How to change TrafficLight Detection model?

### ISSUE THREAD

**Issue by JKLEE-up** [ApolloAuto/apollo#15068]
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: ubuntu 18.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:  7.0.0

I want to replace the traffic light detection model. Our country's traffic light system is different and needs replacement.

In apollo, it was confirmed that the caffe framework was used, and I wonder what learning model was used when training.

**Comment by LordonCN** [comment]
You can export Pytorch or onnx(Apollo9.0) model to load in Apollo after model training.
