### ISSUE TITLE
Point Cloud Extraction - (cyber_record_parser)

### ISSUE THREAD

**Issue by hootan-a** [ApolloAuto/apollo#15075]
### System information

- **Linux Mint 21**:
- **Apollo installed with docker**:
- **Apollo version 8.0**:
- **Output of `cyber_record_parser \--bag_file demo_3.5.record \--out_folder data/bag/output \--cloud_topic /apollo/sensor/lidar128/compensator/pointcloud2`**:

### Steps to reproduce the issue:
- **when I run this command for extracting point clouds from demo_3.5.record file I am getting this error**:
Segmentation fault (core dumped)

![image](https://github.com/ApolloAuto/apollo/assets/141530653/297b8dc2-ea63-4d50-a8c8-f67d16f759f9)

**Comment by daohu527** [comment]
There are two errors
1. the command
```
cyber_record_parser --bag_file=data/bag/xx.record  --out_folder=data --cloud_topic=/apollo/sensor/velodyne64/compensator/PointCloud2
```
2. The record
`demo_3.5.record` does not contain point cloud data. You should try `sensor_rgb.tar.xz`
https://github.com/ApolloAuto/apollo/discussions/15025

## How to view the content in the record?
You can use below command to view the record info. It will display the basic information of the record and the data it contains
```
cyber_recorder info xx.record
```

**Comment by hootan-a** [comment]
> 

Thank you so much "daohu", I extracted and used sensor_rgb data as parameter, but yet I'm getting the same error. I'm running apollo in docker with "aem" command maybe that's the reason I'm getting error.

**Comment by daohu527** [comment]
I'm not sure what's the problem. In fact, I recommend decompressing the record without docker, of course you can continue to solve the current problem

You can try python tool [cyber_record](https://github.com/daohu527/cyber_record), It's standalone, you can run it on any computer

**Comment by hootan-a** [comment]
> There are two errors
> 
>     1. the command
> 
> 
> ```
> cyber_record_parser --bag_file=data/bag/xx.record  --out_folder=data --cloud_topic=/apollo/sensor/velodyne64/compensator/PointCloud2
> ```
> 
>     2. The record
>        `demo_3.5.record` does not contain point cloud data. You should try `sensor_rgb.tar.xz`
>        [How to find apollo records? #15025](https://github.com/ApolloAuto/apollo/discussions/15025)
> 
> 
> ## How to view the content in the record?
> 
> You can use below command to view the record info. It will display the basic information of the record and the data it contains
> 
> ```
> cyber_recorder info xx.record
> ```

Thanks for your quick response, I'm trying to fix cyber_record_parser output error, but I had another question. How this "sensor_rgb" file is being generated? suppose I want to extract point clouds from another apollo map.

**Comment by daohu527** [comment]
> I want to extract point clouds from another apollo map

How could you do this???
