### ISSUE TITLE
日志模块在modules下面无法在终端中打印。

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#15079]
在开发module现在新模块的时候，使用apollo自带的日志打印。
使用bin启动方式，发现在module现在终端无法打印出东西。
使用bin启动方式，同样的BUILD文件和cc文件放到cyber的examples下面编译运行可以打印出东西。

![image](https://github.com/ApolloAuto/apollo/assets/19343842/2193fed5-e48e-4204-bda6-c8ad70e9bf29)

![image](https://github.com/ApolloAuto/apollo/assets/19343842/3993e432-ae9f-415e-852a-3feefc681129)

**Comment by daohu527** [comment]
Nothing to do with these, if you want to output INFO logs to the terminal, which by default only outputs warn and error levels.

## steps
1. set `GLOG_alsologtostderr=1`
https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/cyber/setup.bash#L35
2. `source cyber/setup.bash`

Then the log will output to the terminal too.

**Comment by fengmao31** [comment]
在开发module现在新模块的时候，使用apollo自带的日志打印。
使用bin启动方式，发现在module现在终端无法打印出东西。
使用bin启动方式，同样的BUILD文件和cc文件放到cyber的examples下面编译运行可以打印出东西。

**Comment by fengmao31** [comment]
你可以看到那个图里面，bin在modules下面终端打印不出东西的。在cyber下面是可以的。下午又试了试，写成component，用mainboard才可以终端上面显示打印日志。

**Comment by daohu527** [comment]
You can init glog like below.
```c++
int main(int argc, char** argv) {
  google::InitGoogleLogging(argv[0]);
```

**Comment by fengmao31** [comment]
今天运行一切正常。同样的代码。我初始化了cyber所以包括了google::InitGoogleLogging(argv[0]);可能是apollo的docker有点问题。
