### ISSUE TITLE
感知的后处理：是假设Camera大概与地面平行的前提条件吗

### ISSUE THREAD

**Issue by benlvzi** [ApolloAuto/apollo#15077]
具体代码在LocationRefinerObstaclePostprocessor类， 函数调用关系 PostProcessObjWithGround->PostRefineCenterWithGroundBoundary->GetDxDzForCenterFromGroundLineSeg 中 关于3dBBox下面4个角点的转换 好像就是假设camera 的pitch 角是 0

**Comment by benlvzi** [comment]
引用apollo的文档 1.【The orientation of all three cameras should be all zeros. When the camera is installed, it is required to record a rosbag by driving a straight highway. By the replay of rosbag, the camera orientation should be re-adjusted to have pitch, yaw, and roll angles to be zero degree. When the camera is correctly installed, the horizon should be at the half of image height and not tilted. The vanishing point should be also at the center of the image. Please see the image below for the ideal camera setup.】
2.【 All the cameras should face forward to the driving direction. The field of view (FOV) should be kept free from obstructions as much as possible.】
从以上判断 相机主轴必须与地面平行

**Comment by daohu527** [comment]
Yes, we temporarily do not consider the situation where the vehicle is not parallel to the ground. But that doesn't necessarily mean the camera has to be mounted horizontally
