### ISSUE TITLE
buildtool build --dbg后怎么进行代码调试？

### ISSUE THREAD

**Issue by 1121085292** [ApolloAuto/apollo#15087]
你好，我利用apollo8.0的Cyber-dev新开发Component，buildtool build 成功编译，但mainborad -d启动失败，报错如下：

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0810 21:26:42.922199 11995 module_argument.cc:84] []command: mainboard -d cipv_fusion_component/cipv.dag 
I0810 21:26:42.922384 11995 global_data.cc:153] []host ip: 192.168.1.3
I0810 21:26:42.923015 11995 module_argument.cc:59] []binary_name_ is mainboard, process_group_ is mainboard_default, has 1 dag conf
I0810 21:26:42.923027 11995 module_argument.cc:62] []dag_conf: cipv_fusion_component/cipv.dag
Segmentation fault (core dumped)

想利用buildtool build --dbg 命令进行编译，成功编译后要怎么对代码进行debug呢？

**Comment by WTSRUVF** [comment]
After you compile with --dbg, you can debug with the following steps
" a. Start cyber_launch xxx.launch or mainborad -d to run the module, and dump the core file;
   b. Under /apollo, gdb mainboard ./data/core/core.xxx to debug gdb;
   c. Use bt to view stack information in gdb;
   d. Use up and down to adjust the stack layer, or directly use frame n to locate the nth layer;
   e. After locating to a certain layer, enter the command l to view the corresponding code”
