### ISSUE TITLE
message_type的作用是什么?

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#15088]
我发现在录包写入的时候程序从message里面得到message_type并写入包中。在发布者write也有生成这个message_type，然后用message_type生成proto_desc的动作。
但是在录包写入包例子中，message_type和proto_desc都是随便填写的数值？

如果没有message_type影不影响使用readr以rawmessage的方式订阅examples.Chatter，然后再次以rawmessage发布出去，然后另一个订阅者订阅后可以反序列化examples.Chatter成功？

**Comment by daohu527** [comment]
The advantage of writing information is that it can be self-parsed, which means you can deserialize messages directly from the `proto_desc` in the package.

If not you need to include message.h and then instantiate.
