### ISSUE TITLE
camera perception test - [mainboard]Failed to get number of anchors!

### ISSUE THREAD

**Issue by cool1114** [ApolloAuto/apollo#15099]
I started the dreamview and the following command was executed for the camera perception test.

cyber_launch start modules/perception/production/launch/perception_camera.launch
After that, the error below occurs, do you know what's wrong?
E0817 10:43:04.385648 13973 util.cc:37] [mainboard]Failed to get number of anchors!

cyber_recorder was executed as below.
cyber_recorder play -f ./data/bag/sensor_rgb.record -k /perception/vehicle/obstacles /apollo/perception/obstacles /apollo/perception/traffic_light /apollo/perception

**Comment by cool1114** [comment]
After amodel install (3d-r4-half_caffe), it work fine.

**Comment by DingZhiKun66** [comment]
how to install 3d-r4-half_caffe ,could you please provide a step-by-step guide ? thank you very much
