### ISSUE TITLE
关于dreamview上主车icon倾斜问题

### ISSUE THREAD

**Issue by fpeanut** [ApolloAuto/apollo#15095]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version 8.0**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **你好，我们在用自己的雷达录制数据时，发现主车的航向偏角总是偏38度，在dreamview的改哪个参数可以把航向摆正**:

### Supporting materials (screenshots, command lines, code/script snippets):
![格式工厂 屏幕录像20230815_164302 00_00_33-00_01_00](https://github.com/ApolloAuto/apollo/assets/58199989/95a8f80e-1d19-4933-8232-eb18e91e81e4)

**Comment by daohu527** [comment]
There may be two reasons for this

- vehicle heading
- point cloud pose

The following perspective may deceive you, so you can judge the direction of movement of the vehicle from the top-down perspective, so as to determine whether the heading is correct

## vehicle heading
```
heading = orientation + PI/2
```
orientation is the pose of vehicle, Its coordinate is **(x)East, (y)North, (z)Sky**

## point cloud pose
This is related to the coordinate system of the lidar, you can refer to the apollo coordinate



![image](https://github.com/ApolloAuto/apollo/assets/10419854/f380289e-05c5-43f1-9a52-88a0c3c1c640)

**Comment by fpeanut** [comment]
> orientation

好的，谢谢指导
