### ISSUE TITLE
How to test if LIDAR is working? 

### ISSUE THREAD

**Issue by vivianistan** [ApolloAuto/apollo#1509]
Hi, I installed the apollo code and the apollo kernel code on my machine and have gotten the following to build successfully:

- `apollo.sh build`
- `apollo.sh build_velodyne`

I connected a Velodyne VLP-16 LIDAR to my computer and attempted to run `bash /apollo/scripts/velodyne.sh` after configuring the velodyne driver, but I get errors like this: 

 `/apollo/modulesdrivers_velodyne/velodyne_pointcloud/src/lib/online_calibration.cpp:41 drivers::velodyne::OnlineCalibration::decode() [ERROR] [511992314.301616191]: unit count less than 2, maybe lost packets`

Any advice? I just want to see if the LIDAR is communicating with the Apollo software. 

I have attempted to follow the instructions in these links: 
- https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/velodyne
- https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/lidar_calibration/FAQ0.md

**Comment by fengqikai1414** [comment]
In the script `velodyne.sh`, the default launch file is used for velodyne HDL64E_S3. If you want work with VLP-16, please follow steps as below:
1. Modify the script `/apollo/scripts/velodyne.sh`
    ```c++
    //  file:  /apollo/scripts/velodyne.sh
    function start() {
        LOG="${APOLLO_ROOT_DIR}/data/log/velodyne.out"
        // CMD="roslaunch velodyne start_velodyne.launch"  // for HDL64E_S3
        CMD="roslaunch velodyne start_velodyne_16.launch"  // for VLP16
        NUM_PROCESSES="$(pgrep -c -f "velodyne_nodelet_manager")"
        if [ "${NUM_PROCESSES}" -eq 0 ]; then
           eval "nohup ${CMD} </dev/null >${LOG} 2>&1 &"
        fi
    }
    ```
2. Modify the topic name in `/apollo/modules/common/adapters/adapter_gflags.cc`
    ```c++
    // DEFINE_string(pointcloud_topic, "/apollo/compensator/pointcloud","pointcloud topic name");
    DEFINE_string(pointcloud_topic, 
    // Should be same with the topic name defined in launch file
    "/apollo/sensor/velodyne16/compensator/PointCloud2,"pointcloud topic name");
    ```
Any more, we will update the documents to provide more details about lidar.
If you have any other questions about velodyne driver in apollo，let me know.

**Comment by vivianistan** [comment]
Thank you for the reply. I modified the `velodyne.sh` and `adapter_gflags.cc ` like you said, but when I run `bash /apollo/scripts/velodyne.sh` nothing seems to happen. 

When I run `roslaunch velodyne velodyne_check.launch` I still get this: 

`cpp:41 drivers::velodyne::OnlineCalibration::decode() [ERROR] [1512251735.280539033]: unit count less than 2, maybe lost packets`

I also tried running `roslaunch velodyne start_velodyne_16.launch` directly and I get these errors: 

`[velodyne_nodelet_manager-2] process has died [pid 16978, exit code -11, cmd /home/tmp/ros/lib/nodelet/nodelet manager __name:=velodyne_nodelet_manager __log:=/home/teamapollo/.ros/log/d4de172e-d7aa-11e7-a9a2-0242cffce468/velodyne_nodelet_manager-2.log].
log file: /home/teamapollo/.ros/log/d4de172e-d7aa-11e7-a9a2-0242cffce468/velodyne_nodelet_manager-2*.log`

and 

`[sensor_velodyne16_driver-3] process has died [pid 17160, exit code 255, cmd /home/tmp/ros/lib/nodelet/nodelet load velodyne_driver/DriverNodelet velodyne_nodelet_manager __name:=sensor_velodyne16_driver __log:=/home/teamapollo/.ros/log/d4de172e-d7aa-11e7-a9a2-0242cffce468/sensor_velodyne16_driver-3.log].
log file: /home/teamapollo/.ros/log/d4de172e-d7aa-11e7-a9a2-0242cffce468/sensor_velodyne16_driver-3*.log`



Any advice?

**Comment by fengqikai1414** [comment]
1. You can run `rosed velodyne velodyne_check.launch` to verify all the configures.  Default only for HDL64E_S3.
2. Our velodyne driver relies on GPS signals to get the GPS time, but you can cut the code related to timestamp yourself，and i believe it will work as well.

**Comment by vivianistan** [comment]
Just to clarify, are you saying that `rosed velodyne velodyne_check.launch` defaults are only for HDL64E_S3? Would that mean that if I wanted to check the VLP-16 configuration I would have to modify `velodyne_check.launch` or make something like `velodyne_check_16.launch`?

And to modify the velodyne driver to cut the timestamp out is there a particular file/group of files I should look at within `/apollo/modules/drivers/velodyne`? I was thinking maybe `/apollo/modules/drivers/velodyne/velodyne_driver/input.h` but wasn't sure.

**Comment by fengqikai1414** [comment]
> ust to clarify, are you saying that rosed velodyne velodyne_check.launch defaults are only for HDL64E_S3? Would that mean that if I wanted to check the VLP-16 configuration I would have to modify velodyne_check.launch or make something like velodyne_check_16.launch?

Yes, default only for HDL64E_S3. Configures of VLP16 reference to `velodyne_check_16.launch`

> And to modify the velodyne driver to cut the timestamp out is there a particular file/group of files I should look at within /apollo/modules/drivers/velodyne? I was thinking maybe /apollo/modules/drivers/velodyne/velodyne_driver/src/lib/input.cpp but wasn't sure.

We didn't think about a scene without GPS time when implementing the driver, so you have to try yourself. Additional ,If you just want to test LIDAR, and don't want to change code, i suggest you use this driver [http://wiki.ros.org/velodyne](http://wiki.ros.org/velodyne).

**Comment by vivianistan** [comment]
Ok, thanks for your help. May try to connect a GPS later and see if that helps with the timestamp issue.
