### ISSUE TITLE
has any docker image support jetson tx2 --> jetpack 32.7.2?

### ISSUE THREAD

**Issue by CesarLiu** [ApolloAuto/apollo#15116]
**Is your feature request related to a problem? Please describe.**
I' try to build an docker image based on nvidia jetpack 32.7.2, which has ubuntu 18.04 and cuda 10.2 on jetson tx2. Are there any tested docker image.

**Describe the solution you'd like**
I have adjusted one based on apollo 9.x_alpha: https://github.com/CesarLiu/apollo/tree/9.x_alpha, but still has problem with nvcc unsupported compute_86. And also the libtorch provided by apollo does not work on this platform.

**Comment by usrn1** [comment]
Hello,did you pull the docker images successfully on orin？

**Comment by CesarLiu** [comment]
https://github.com/CesarLiu/apollo/commit/1cf03e2da9c8a2d1e4d66e7b2feea39083f27450
a usable version on jetson tx2, currently tested demo_guide.
