### ISSUE TITLE
预测模块dag启动是怎么修改加载的地图

### ISSUE THREAD

**Issue by fpeanut** [ApolloAuto/apollo#15123]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **我再运行 mainboard -d modules/prediction/dag/prediction.dag时，初始化加载的地图始终是sunnyvale_big_loop，怎么修改默认加载的地图**:

### Supporting materials (screenshots, command lines, code/script snippets):
<img width="842" alt="1693903998920" src="https://github.com/ApolloAuto/apollo/assets/58199989/7d422ddb-0531-4d83-a1b1-6e7c518bf3dc">

**Comment by nagareru** [comment]
修改modules/common/data/global_flagfile.txt里的map_dir

**Comment by fpeanut** [comment]
> map_dir

但是我看到modules/common/data/global_flagfile.txt里有好多map_dir，我怎么改才能生效

**Comment by nagareru** [comment]
flagfile的规则应该是写在后边的会覆盖前面的，所以改最后那个就可以吧
