### ISSUE TITLE
How to pull the docker images on jetson orin?

### ISSUE THREAD

**Issue by usrn1** [ApolloAuto/apollo#15128]
Describe the bug:Failed to start docker container.

Error: Error response from daemon:failed to create task for container: failed to create shim task:OCI runtime create failed: failed to create NVIDIA Container Runtime:failed to construct OCI spec modifier:requirements not met:unsatisfied condition:cuda>=11.4(cuda=10.2): unknown.

But I also upgrade the cuda->11.4, there are also same error.

**Comment by Eyobagithub** [comment]
Use the "docker image ls" command
sudo docker image ls [OPTIONS][REPOSITORY[:TAG]]

**Comment by usrn1** [comment]
there are the apollo images,but don't start the docker container successfully.

**Comment by Eyobagithub** [comment]
Try the docker run command

sudo docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]

**Comment by usrn1** [comment]
![c8a095abdeb7c0160ecfe3b9223c2c5](https://github.com/ApolloAuto/apollo/assets/130576156/1587b6fe-8118-4638-9137-ac44f12178f9)

**Comment by usrn1** [comment]
I tried running docker run, but nothing happens。

**Comment by Eyobagithub** [comment]
So you are trying to run the docker image using it's id only. Okay try running the docker container under a certain name. If you want to specify a name use --name attribute and run it using docker container run --name [container_name] [docker_image]. To check whether you have successfully set a container name use docker ps -a

**Comment by usrn1** [comment]
![9e0bcece52a569316a07fa825785b0f](https://github.com/ApolloAuto/apollo/assets/130576156/420ff4b6-d525-42f0-8540-2b8b700672a1)
I try many kinds of ways, don't start successfully. always warm the cuda don't satisfied. would you met this problem,hou do you solve the problem . thank you !

**Comment by Eyobagithub** [comment]
https://github.com/rbonghi/jetson_stats/releases/tag/4.0.0rc2
