### ISSUE TITLE
Planning module buildtool error

### ISSUE THREAD

**Issue by chiragr15** [ApolloAuto/apollo#15138]
Error thrown while building the application-demo folder for planning module.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04.6 LTS on VirtualBox
- **Apollo installed from (source or binary)**: as per installation document
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 8.0

### Steps to reproduce the issue:
- In the 8.0 Quickstart document, followed exact instructions for installation and setup.
- downloaded the application-demo.git folder as per instructions
- Run the buildtool command

I am getting the following error upon running the build command:

"chirag@in-dev-docker:/apollo_workspace$ buildtool build --packages example_components
[buildtool] INFO try to search plugin in local...
[buildtool] INFO plugin search complete:
/opt/apollo/neo/packages/buildtool-dev/1.0.0.12/pkg_maker/action
[buildtool] INFO Gpu is not available, using cpu instead
[buildtool] INFO Reconfigure apollo enviroment setup
[buildtool] WARNING Package in /apollo_workspace/example_components is invalid: cyberfile not found or can not import as src type!
[buildtool] ERROR Encounter ErrCode.ParamErr
[buildtool] ERROR hint: Can't find any package in workspace /apollo_workspace
ErrCode.ParamErr
[buildtool] INFO apollo build tool exit."

**Comment by WTSRUVF** [comment]
Based on your question, I have executed it once and there are no issues as you mentioned. Please be strict“ https://github.com/ApolloAuto/apollo/blob/master/docs/02_Quick%20Start/apollo_8_0_quick_start.md ”Operate on 'Scenario 2: Cyber Component Extensions' under the address.

**Comment by chiragr15** [comment]
I have followed the exact steps from the Quickstart guide and face the same issue. Scenario 1 is working properly, when I follow the steps till buildtool command as well it works. But upon running the buildtool command, I am getting the same error.

[buildtool] WARNING Package in /apollo_workspace/example_components is invalid: cyberfile not found or can not import as src type!
[buildtool] ERROR Encounter ErrCode.ParamErr
[buildtool] ERROR hint: Can't find any package in workspace /apollo_workspace
ErrCode.ParamErr
[buildtool] INFO apollo build tool exit.

**Comment by WTSRUVF** [comment]
May I ask if you are executing Scenario 2 in the directory of Scenario 1? Please ensure that the code for Scenario 2 is in a directory that is independent of Scenario 1. After Git Clone, enter application demo and re execute "aem start", "aem enter", and "buildtool build -- packages example_components".
If it still doesn't work, you can try to view the container ID through "docker ps", stop the container with "docker stop ID", delete the container with "docker rm ID", and then perform a series of operations such as "aem start" again.

**Comment by chiragr15** [comment]
This worked, thank you for your reply
