### ISSUE TITLE
aem安装完执行aem start命令的时候，报错：[ERROR] Failed to pull docker image : registry.baidubce.com/apollo/apollo-env-gpu:latest

### ISSUE THREAD

**Issue by wszzzx** [ApolloAuto/apollo#15156]
错误信息如下：
(base) ThinkPad-T480:~/application-demo$ aem start
[INFO] Determine whether host GPU is available ...
[INFO] USE_GPU_HOST: 1
[INFO] Start pulling docker image registry.baidubce.com/apollo/apollo-env-gpu:latest ...
Error response from daemon: Get "https://registry.baidubce.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[ERROR] Failed to pull docker image : registry.baidubce.com/apollo/apollo-env-gpu:latest

**Comment by doghcf** [comment]
maybe you can try with 'sudo aem start'

**Comment by WTSRUVF** [comment]
It seems that your network cannot stably connect to the external network.

**Comment by WildBeast114514** [comment]
it should be the network problem, checkout your network condition.

**Comment by 1205gur** [comment]
I want to know wheather you had solved this question.If YES and tell me the solution,i
will apprecitate it.
