### ISSUE TITLE
apollo单目测距代码重复

### ISSUE THREAD

**Issue by ycdhqzhiai** [ApolloAuto/apollo#15172]
https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/perception/camera/app/obstacle_detection_camera.cc#L325

https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/perception/camera/app/obstacle_detection_camera.cc#L335

@daohu527 您好，关于上面两个接口内部object-center的计算是不是重复的啊，最近好像增加了比较多的代码，但是感觉好像还是重复的，去除L335好像结果还是一样的

**Comment by daohu527** [comment]
They have different uses, you know Apollo has two kinds monocular 3d object detection algorithms.

## monocular 3d object detection (one stage)
Export 3D object center, size and type directly from the image. Already integrated algorithms include
- SMOKE
- CaDDN

## monocular 3d object detection (two stage)
First output the target's center on the image, size and direction in the world, Then compute depth information through geometric constraints.

#### compute depth
we use `transformer_->Transform` to compute depth information. That is, the 3D estimated depth is projected onto the 2D image frame to see if the best match can be achieved, thereby optimizing the depth information.
https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/perception/camera/app/obstacle_detection_camera.cc#L325

#### refine depth
Next, we will further optimize the depth through the ground, get more accurate depth.
https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/perception/camera/app/obstacle_detection_camera.cc#L335

## refence
You can refer to "3D Bounding Box Estimation Using Deep Learning and Geometry" for more relevant information
