### ISSUE TITLE
编译失败 Remote host terminated the handshake

### ISSUE THREAD

**Issue by nxydyxsj123456** [ApolloAuto/apollo#15174]
(14:52:40) ERROR: /apollo/modules/perception/lidar/lib/detector/center_point_detection/BUILD:7:11: //modules/perception/lidar/lib/detector/center_point_detection:center_point_detection depends on @centerpoint_infer_op//:centerpoint_infer_op in repository @centerpoint_infer_op which failed to fetch. no such package '@centerpoint_infer_op//': java.io.IOException: Error downloading [https://apollo-system.bj.bcebos.com/archive/v8.0_bev/centerpoint_infer_op.tar.gz] to /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/centerpoint_infer_op/temp5371379806002136948/centerpoint_infer_op.tar.gz: Remote host terminated the handshake
(14:52:40) ERROR: Analysis of target '//modules/perception/onboard/component:perception_component_inner_lidar' failed; build aborted: Analysis failed
(14:52:40) INFO: Elapsed time: 41.530s
(14:52:40) INFO: 0 processes.
(14:52:40) FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by daohu527** [comment]
could you pls check you can download https://apollo-system.bj.bcebos.com/archive/v8.0_bev/centerpoint_infer_op.tar.gz
