### ISSUE TITLE
没有硬件设备，怎么生成和发送gps坐标数据

### ISSUE THREAD

**Issue by wqklihbf** [ApolloAuto/apollo#15173]
### System information

- **OS Platform and Distribution: Ubuntu 23.04
- **Apollo installed from: 软件包安装
- **Apollo version: 8.0

### Steps to reproduce the issue:

I don't have the hardware, how do I generate GPS data and send them?
I want to know how the GPS data is transmitted.

**Comment by daohu527** [comment]
Your question is a good start to understanding autonomous driving, which most of us are starting to understand without hardware.

## Solution
There are several methods:
- **Log sim** - You can play record to simulate sensor data, which include lidar, camera, radar, gnss. You can find apollo record files here  https://github.com/ApolloAuto/apollo/discussions/15025
- **World sim** - Log sim is very convenient, but it cannot interact with the world, and world sim can solve this problem. You can use apollo `sim_control` or use carla or other simulation to work with Apollo.

**Comment by wqklihbf** [comment]
> Your question is a good start to understanding autonomous driving, which most of us are starting to understand without hardware.
> 
> ## Solution
> There are several methods:
> 
> * **Log sim** - You can play record to simulate sensor data, which include lidar, camera, radar, gnss. You can find apollo record files here  [How to find apollo records? #15025](https://github.com/ApolloAuto/apollo/discussions/15025)
> * **World sim** - Log sim is very convenient, but it cannot interact with the world, and world sim can solve this problem. You can use apollo `sim_control` or use carla or other simulation to work with Apollo.

Thank you for your response. I have already tried both methods, but I want to know how GPS data is transmitted in the Apollo system. For example, if I want to send a GPS coordinate now, what should I do? Is there any tutorial that I can refer to?

**Comment by daohu527** [comment]
The simplest way is to read gps from file and then write a writer to sending gps messages. There is a [example](https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/localization/rtk/rtk_localization_test.cc) you can try

complie the localizaiton module and run 
```
./apollo.sh build localization

./bazel-bin/modules/localization/rtk/rtk_localization_test
```

**Comment by wqklihbf** [comment]
> The simplest way is to read gps from file and then write a writer to sending gps messages. There is a [example](https://github.com/ApolloAuto/apollo/blob/a3c851fc5844e0684b9c5108231fcc2c15cebb8e/modules/localization/rtk/rtk_localization_test.cc) you can try
> 
> complie the localizaiton module and run
> 
> ```
> ./apollo.sh build localization
> 
> ./bazel-bin/modules/localization/rtk/rtk_localization_test
> ```

I try to run the command:
```
bazel build modules/localization/rtk/rtl_localization_test.cc
``` 
and get this:
![image](https://github.com/ApolloAuto/apollo/assets/128605713/ca7f4083-597d-456b-a3f6-822250220719)
Does this mean that Apollo received the GPS coordinates? Where can I see the performance from?
And I changed the coordinate values in 3_gps_1.pb.txt, but running the command again still gave me the same result. What does this mean?

**Comment by daohu527** [comment]
bazel is a build tool, which is used to compile rtk_localization_test. and then you can run rtk_localization_test for test.

You need to look at the code to understand the principles and format
