### ISSUE TITLE
aem profile

### ISSUE THREAD

**Issue by Tabbleman** [ApolloAuto/apollo#15171]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (binary)**:
- **Apollo version (8.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
After I installed apollo according to the pnc-competetion installation method, I started to try to do cloud platform experiments locally, but when I used `aem profile`, the prifile option did not appear, and the same was true for buildtool.

**Comment by WildBeast114514** [comment]
it may caused by the older version of aem, you can try the following command to upgrade aem in host:
```
sudo apt update && sudo apt install --only-upgrade apollo-neo-env-manager
```
then remove the container and create new one:
```
cd application-core
aem remove 
aem start
```

**Comment by Tabbleman** [comment]
> it may caused by the older version of aem, you can try the following command to upgrade aem in host:可能是aem版本较旧造成的，您可以尝试使用以下命令在主机中升级aem：
> 
> ```
> sudo apt update && sudo apt install --only-upgrade apollo-neo-env-manager
> ```
> 
> then remove the container and create new one:然后删除容器并创建新容器：
> 
> ```
> cd application-core
> aem remove 
> aem start
> ```

nope, it doesn't work at all.
```
┌💁  z @ 💻  z in 📁  ~
└❯ sudo apt install apollo-neo-env-manager-dev 
Display all 95632 possibilities? (y or n)

┌💁  z @ 💻  z in 📁  ~
└❯ sudo apt install apollo-neo-env-manager-dev --only-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apollo-neo-env-manager-dev is already the newest version (1.0.0.6).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

┌💁  z @ 💻  z in 📁  pnc-competition on 🌿  main •1 ⌀15 ✗
└❯ aem start 
[INFO] Determine whether host GPU is available ...
[INFO] USE_GPU_HOST: 1
[INFO] Start pulling docker image registry.baidubce.com/apollo/apollo-env-cpu:latest ...
latest: Pulling from apollo/apollo-env-cpu
Digest: sha256:120c82913d408ac94baaa0e593e69b4997a74138e140e02c7acfbd4cd3b8b249
Status: Image is up to date for registry.baidubce.com/apollo/apollo-env-cpu:latest
registry.baidubce.com/apollo/apollo-env-cpu:latest
[INFO] apollo_neo_dev_z is down, try to restart.
apollo_neo_dev_z
[ OK ] apollo_neo_dev_z successfully restart, please run the following command:
[ OK ]     aem enter
[ OK ] Enjoy!

┌💁  z @ 💻  z in 📁  pnc-competition on 🌿  main •1 ⌀15 ✗
└❯ aem enter 
z@in-dev-docker:/apollo_workspace$ aem profile

Usage:
    aem [OPTION]

Options:
    build : build package in workspace.
    stop : stop all apollo development container.
    create : create a new container with apollo development image.
    install : install source code of specified package to workspace.
    start : start the created container.
    init : init single workspace.
    bootstrap : run dreamview and monitor module.
    enter : enter into the apollo development container.
    update : update core modules of apollo.
    setup_host : setup host
    start_gpu : start a created gpu container.
z@in-dev-docker:/apollo_workspace$ 

``` 
actually it doesn't work at all, i don't know which version of apollo in your cloud environment, the lab i follow is [here](https://apollo.baidu.com/community/course/25). thx for your early reply:)

**Comment by WildBeast114514** [comment]
According to your log, It looks like you're installing aem using the apt repository for apollo 8.0, rather than 9.0.
You can refer to this document [apollo 9.0 docs](https://apollo.baidu.com/docs/apollo/latest/md_docs_2installation__instructions_2essential__software__installation__guide__cn.html) or follow the step to upgrade your aem:
1. delete `deb https://apollo-pkg-beta.cdn.bcebos.com/neo/beta bionic main` of file `/etc/apt/sources.list`
2. install 9.0 aem:
```
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://apollo-pkg-beta.cdn.bcebos.com/neo/beta/key/deb.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/apolloauto.gpg
sudo chmod a+r /etc/apt/keyrings/apolloauto.gpg
 
echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/apolloauto.gpg] https://apollo-pkg-beta.cdn.bcebos.com/apollo/core"\
    $(. /etc/os-release && echo "$VERSION_CODENAME") "main" | \
    sudo tee /etc/apt/sources.list.d/apolloauto.list
sudo apt-get update
```

**Comment by Tabbleman** [comment]
thank you, problem fixed;-)
