### ISSUE TITLE
bash docker/scripts/dev_start.sh

### ISSUE THREAD

**Issue by askari01** [ApolloAuto/apollo#1518]
Type 'y' or 'Y' to pull docker image from China mirror or any other key from US mirror.
y
dev-x86_64-20171129_1427: Pulling from apolloauto/apollo
cb56c90f0b30: Already exists 
0acc551e5716: Already exists 
8956dcd35143: Already exists 
908242721214: Already exists 
b44ff14dd3bb: Already exists 
4e68297aef7a: Pulling fs layer 
f2e60cbbc46b: Pulling fs layer 
4def827f3388: Pulling fs layer 
d7024597d4d3: Waiting 
886213b9c3ba: Waiting 
b1ac6ddbc6b7: Waiting 
6d28c630a322: Waiting 
d505646e6e5b: Waiting 
7968bcb3836a: Waiting 
8f0fa8c34222: Waiting 
bb8e16126598: Waiting 
f3b7c5d69675: Waiting 
1aedc3a0410b: Waiting 
33c030e7093a: Waiting 
da48ec85ed49: Waiting 
24852ac95ef0: Waiting 
fe4e65935e53: Waiting 
4779c4c9cb2e: Waiting 
27f6eba23a1a: Waiting 
15ab83019eb2: Waiting 
199e339073f8: Waiting 
3ae09dace98d: Waiting 
d09a647016dd: Waiting 
a7cb11a41e97: Waiting 
3e7686bdef0b: Waiting 
78198803f767: Waiting 
9b76be8176e0: Waiting 
74c48b5e54a2: Waiting 
200abc1adefd: Waiting 
ce47e44da8ce: Waiting 
8e863c5dfee2: Waiting 
85b9d775f6a6: Waiting 
618a1ac568c6: Waiting 
efc4bc9b4119: Waiting 
4e46d20fcf03: Waiting 
2b448e40506a: Waiting 
d12c8cf5699d: Waiting 
f2ba7ad4cfc7: Waiting 
351ecb254b60: Pulling fs layer 
dd1b1bafa413: Waiting 
8a5e2bea418d: Waiting 
7e610bf57646: Waiting 
32a374005d6c: Waiting 
1307670d704c: Waiting 
e43cb256c38c: Waiting 
353dcb25c39c: Waiting 
52e15f6717a2: Pulling fs layer 
a1d13a7f5398: Waiting 
1208b862d4c9: Waiting 
21f3dfc7fc87: Waiting 
85ae4b0dd353: Pull complete 
042b5ae882da: Pull complete 
707d68e96343: Pull complete 
268269a5caca: Pull complete 
45dfbd87c718: Pull complete 
94f5779d4af0: Pull complete 
82ccbf80d7fa: Pull complete 
86315e78db66: Pull complete 
06bc6911f9d4: Pull complete 
26637a5d7bcf: Pull complete 
2b8610ad644b: Pull complete 
e07c96625704: Pull complete 
8c7b2e11d4bd: Pull complete 
e19a886efafb: Pull complete 
76a96bcddfb9: Pull complete 
eca8c00b150c: Pull complete 
cebb627b586b: Pull complete 
18107c0ddc3f: Pull complete 
bf89e5c82131: Pull complete 
08868fe92128: Pull complete 
7475105e49a7: Pull complete 
b648e96d3179: Pull complete 
5c5c05b88a7a: Pull complete 
Digest: sha256:9df5a2a6da7abb8658b3cafad87a784292f510140d11f34446da4d3a3795ef0b
Status: Downloaded newer image for registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20171129_1427
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.13.0-17-generic
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.13.0-17-generic
[WARNING] Failed to find device with pattern "ttyUSB*" ...
[ OK ] Found device: /dev/ttyS31.
[ OK ] Found device: /dev/ttyS30.
[ OK ] Found device: /dev/ttyS29.
[ OK ] Found device: /dev/ttyS28.
[ OK ] Found device: /dev/ttyS27.
[ OK ] Found device: /dev/ttyS26.
[ OK ] Found device: /dev/ttyS25.
[ OK ] Found device: /dev/ttyS24.
[ OK ] Found device: /dev/ttyS23.
[ OK ] Found device: /dev/ttyS22.
[ OK ] Found device: /dev/ttyS21.
[ OK ] Found device: /dev/ttyS20.
[ OK ] Found device: /dev/ttyS19.
[ OK ] Found device: /dev/ttyS18.
[ OK ] Found device: /dev/ttyS17.
[ OK ] Found device: /dev/ttyS16.
[ OK ] Found device: /dev/ttyS15.
[ OK ] Found device: /dev/ttyS14.
[ OK ] Found device: /dev/ttyS13.
[ OK ] Found device: /dev/ttyS12.
[ OK ] Found device: /dev/ttyS11.
[ OK ] Found device: /dev/ttyS10.
[ OK ] Found device: /dev/ttyS9.
[ OK ] Found device: /dev/ttyS8.
[ OK ] Found device: /dev/ttyS7.
[ OK ] Found device: /dev/ttyS6.
[ OK ] Found device: /dev/ttyS5.
[ OK ] Found device: /dev/ttyS4.
[ OK ] Found device: /dev/ttyS3.
[ OK ] Found device: /dev/ttyS2.
[ OK ] Found device: /dev/ttyS1.
[ OK ] Found device: /dev/ttyS0.
[ OK ] Found device: /dev/can2.
[ OK ] Found device: /dev/can1.
[ OK ] Found device: /dev/can0.
[WARNING] Failed to find device with pattern "ram*" ...
[ OK ] Found device: /dev/loop7.
[ OK ] Found device: /dev/loop6.
[ OK ] Found device: /dev/loop5.
[ OK ] Found device: /dev/loop4.
[ OK ] Found device: /dev/loop3.
[ OK ] Found device: /dev/loop2.
[ OK ] Found device: /dev/loop1.
[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop-control.
[ OK ] Found device: /dev/nvidia-uvm-tools.
[ OK ] Found device: /dev/nvidia-uvm.
[ OK ] Found device: /dev/nvidiactl.
[ OK ] Found device: /dev/nvidia0.
[WARNING] Failed to find device with pattern "video*" ...
Unable to find image 'apolloauto/apollo:dev-x86_64-20171129_1427' locally
dev-x86_64-20171129_1427: Pulling from apolloauto/apollo
Digest: sha256:9df5a2a6da7abb8658b3cafad87a784292f510140d11f34446da4d3a3795ef0b
Status: Downloaded newer image for apolloauto/apollo:dev-x86_64-20171129_1427
c0ad88830bb15b792ad11096c394cdbd2f6af4ea361149d47746dbb97c6bc832

i receive the following error

**Comment by gengqx** [comment]
I think it is not a big deal，you have succuss in download the docker image,and you can run the bash
```
bash docker/scripts/dev_into.sh
```
to build and develop your system.
If you not sure if the docker is start correctly, you can run 
```
docker ps
```
to check the running docker container.
