### ISSUE TITLE
[V9.0.0-alpha]error,'modules': no such package '@local_config_tensorrt//': key "TENSORRT_VERSION" not found in dictionary

### ISSUE THREAD

**Issue by tedelon** [ApolloAuto/apollo#15183]
![tensorrt](https://github.com/ApolloAuto/apollo/assets/49553101/95630ca0-d87e-40f0-ab71-d358dbe8aeb6)

### System information
NVIDIA orign 
Ubuntu 20.04
Apollo version (V9.0.0-alpha]

### Steps to reproduce the issue:
In the Apollo container,executive command" sudo bash ./appollo.sh build "
fendback info dispaly : somthing wrong with local_config_tensorrt'

My check shows that the library has been installed.
Where do I need to change my ENV profile?

**Comment by daohu527** [comment]
The reason for the error is that the environment variable "TENSORRT_VERSION" cannot be found. You can confirm using the following command
```shell
echo $TENSORRT_VERSION
```

This is strange because this environment variable is specified in the container. It is recommended that you restart the container and try again.

**Comment by tedelon** [comment]
I hare already restarted the container,but it also not resolved.
I have confirmed that $TENSORRT_VERSION="8.5.2"
root@in-dev-docker:/apollo# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Sun_Oct_23_22:16:07_PDT_2022
Cuda compilation tools, release 11.4, V11.4.315
Build cuda_11.4.r11.4/compiler.31964100_0

How can I fix it???

**Comment by daohu527** [comment]
You add below code and can print out environ

```python
print(repository_ctx.os.environ)
```

https://github.com/ApolloAuto/apollo/blob/ffa0765b2b7f6b831d4c2ede6834d6d5ba2f77f6/third_party/tensorrt/tensorrt_configure.bzl#L129-L138

**Comment by tedelon** [comment]
The code exits for files in this directory
![Screenshot from 2023-11-09 12-27-02](https://github.com/ApolloAuto/apollo/assets/49553101/7befbdbf-203d-4005-a323-77dd60b688d8)
but also unable to print out the info.
root@in-dev-docker:/apollo# print(repository_ctx.os.environ)
bash: syntax error near unexpected token `repository_ctx.os.environ'

**Comment by tedelon** [comment]
sorry .I misunderstand .
maybe that's what you wanted
![image](https://github.com/ApolloAuto/apollo/assets/49553101/dce86fe0-9096-455d-a138-a128118a2a04)

**Comment by WildBeast114514** [comment]
In Apollo container, a env variable TENSORRT_VERSION should be set:
```
[apollo@in-dev-docker:/apollo]$ env | grep TENSORRT
TENSORRT_VERSION=7.2.1
```
please checkout your env variables, if missing this variable, considering restart a new container
```
bash docker/scripts/dev_start.sh
```

**Comment by kaikaikai1206** [comment]
请问该问题如何解决了？
