### ISSUE TITLE
为啥没有人回复，大佬们，虚心求教，这个锁我个人觉得影响整个运行的性能

### ISSUE THREAD

**Issue by lobmoo** [ApolloAuto/apollo#15184]
template <typename MessageT> bool Writer<MessageT>::Write(const MessageT& msg) { RETURN_VAL_IF(!WriterBase::IsInit(), false); auto msg_ptr = std::make_shared<MessageT>(msg); return Write(msg_ptr); } 
 bool IsInit() const { std::lock_guard<std::mutex> g(lock_); return init_; }
In the “IsInit()”
I believe the presence of this lock is unnecessary and greatly impacts performance. Allowing only one thread to write at a time creates a bottleneck. Removing the lock or replacing it with a reader-writer lock would likely yield better results.

**Comment by daohu527** [comment]
@lobmoo Pls format code and explain the specific reasons. It is best to have test data. Then we will discuss later

**Comment by nagareru** [comment]
我觉得对性能的影响可能不大，因为只是在判断IsInit()内部加了锁，而并不是阻塞了整个write过程。不过退一步来说IsInit应该确实不需要加锁，用atomic<bool>判断就足够了。

**Comment by lobmoo** [comment]
并且我认为这里写应该具有原子性，这个锁，会导致写在同一时刻触发时，去互斥等待

**Comment by nagareru** [comment]
首先write的底层实现就是阻塞的，对于一个writer实例来说同时只能write一条msg。在cyber里writer是和node以及channel绑定的，即不同node的不同channel的writer本就都各不相同，不同writer各自同时写当然不会有问题，而不同的线程同时调用同一个writer去写的情况应该并不多见。即使出现，当前的写法只会在判断init与否时候造成阻塞，对init_的读取完成后锁就被释放了，所以这个地方应该不会造成 bottleneck。但是加锁的操作应该也确实不是必要的。

**Comment by lobmoo** [comment]
感谢为我解答疑惑，由于刚开始阅读源码，，对于底层还没有完全了解，就提出了这个问题。再次感谢大家

**Comment by daohu527** [comment]
duplicated https://github.com/ApolloAuto/apollo/issues/15177

We have received your question and need time to confirm. Closed this issue and discuss https://github.com/ApolloAuto/apollo/issues/15177
