### ISSUE TITLE
nvidia orin version v9.0.0-alpha, ERROR " bazel: command not found"

### ISSUE THREAD

**Issue by tedelon** [ApolloAuto/apollo#15181]
![bazel](https://github.com/ApolloAuto/apollo/assets/49553101/ecc37b7c-ac50-47ff-8873-d5bffebe47bf)

When I enter apollo container,  exexute the command "sudo bash ./apollo.sh build"
The info remind me that bazel need to be installed ""
But I have already installed it.
What should I do?

**Comment by HandsomeAIccx** [comment]
Did you grant execute permissions to bazel, for example by running 'chmod +x bazel'?

**Comment by tedelon** [comment]
> Did you grant execute permissions to bazel, for example by running 'chmod +x bazel'?

Only execute command "sudo bash docker/build/installers/install_bazel.sh"
then update the config " ~/.bashrc"

**Comment by HandsomeAIccx** [comment]
make sure your bazel is located at /usr/local/bin/bazel and has execute permissions

**Comment by tedelon** [comment]
> make sure your bazel is located at /usr/local/bin/bazel and has execute permissions

How did you install bazel??

**Comment by HandsomeAIccx** [comment]
https://github.com/bazelbuild/bazel/releases/download/5.2.0/bazel-5.2.0-linux-arm64

**Comment by daohu527** [comment]
Apollo docker installs bazel by default, did you do anything special?

**Comment by Hgsil** [comment]
我也有存在这个问题，我使用相同的orin环境，在使用sudo bash docker/scripts/dev_start.sh后使用sudo bash docker/scripts/dev_into.sh进入容器，但是调用apollo.sh时无法找到bazel；
尝试调用bash docker/build/installers/install_bazel.sh并显示成功之后，bazel依旧无法找到，并且/usr/local/bin/目录下没有bazel

**Comment by tedelon** [comment]
> 我也有存在这个问题，我使用相同的orin环境，在使用sudo bash docker/scripts/dev_start.sh后使用sudo bash docker/scripts/dev_into.sh进入容器，但是调用apollo.sh时无法找到bazel； 尝试调用bash docker/build/installers/install_bazel.sh并显示成功之后，bazel依旧无法找到，并且/usr/local/bin/目录下没有bazel

you can try that: maybe you can change the bazel version from the url
`wget -O /usr/local/bin/bazel https://mirrors.huaweicloud.com/bazel/6.4.0/bazel-6.4.0-linux-arm64
sudo chmod +x /usr/local/bin/bazel`

**Comment by Hgsil** [comment]
将installer_base.sh中的export SYSROOT_DIR修改为"/usr/local"，重新执行install_bazel脚本可解决问题。并可将/opt/apollo/sysroot/bin/ 下安装的全部包cp到 "/usr/local/bin" 目录中。

**Comment by WildBeast114514** [comment]
when enter apollo container, make sure you are using non-root role
