### ISSUE TITLE
why use new in this part rather than smart pointer?

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#15186]
![image](https://github.com/ApolloAuto/apollo/assets/19343842/7949756a-aa33-4902-9490-0e2cc1ff9bef)
![image](https://github.com/ApolloAuto/apollo/assets/19343842/c17f0593-0d22-4644-9e14-b103a58be559)
![image](https://github.com/ApolloAuto/apollo/assets/19343842/e947aa52-3278-46b0-b8b1-de5e8882927f)

**Comment by nagareru** [comment]
![image](https://github.com/ApolloAuto/apollo/assets/49864495/39e7300f-11e1-4381-9c4e-05a502e2c7cc)
because transport::Participant need a raw pointer in constructor ？

**Comment by daohu527** [comment]
We'd better paste the code instead of the picture. Seems the problem solved
