### ISSUE TITLE
Successfully building Apollo v9.0, but encountering errors when running camera_detection_single_stage.dag.

### ISSUE THREAD

**Issue by Hgsil** [ApolloAuto/apollo#15196]
### System information

- **OS Platform and Distribution **: orin
- **Apollo version **:9.0

### Steps to reproduce the issue:
After successfully building the perception module, I attempted to test the effect of the smoke. I used the command
"mainboard -d modules/transform/dag/static_transform.dag -d modules/perception/camera_detection_single_stage/dag/camera_detection_single_stage.dag -d modules/perception/camera_location_estimation/dag/camera_location_estimation.dag -d modules/perception/camera_location_refinement/dag/camera_location_refinement.dag -d modules/perception/camera_tracking/dag/camera_tracking.dag -d modules/perception/multi_sensor_fusion/dag/multi_sensor_fusion.dag"
to launch the modules. However, the "/apollo/perception/obstacles" topic consistently had no information. Upon inspecting the logs, I found that it was stuck in the tracker module. The logs indicated that the detection, location_estimation, and location_refinement modules were producing output normally, but the tracker module only output the following message once::
"I1116 16:05:16.286335 48529 camera_tracking_component.cc:71] Enter Tracking component, message timestamp: 1513807824.641768 current timestamp: 1700121916.286372."
Could you please advise me on how to debug the camera tracker module?

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/ApolloAuto/apollo/assets/22257928/88f4ce8e-03a3-4cd5-900d-3eadfbbbea06)

![image](https://github.com/ApolloAuto/apollo/assets/22257928/bff467b8-4be9-4541-a387-bfd697208210)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/50d1001b-1e97-49f7-9251-9e0b165d5acf)

**Comment by Hgsil** [comment]
I am outputting the content of the 'track' line by line to identify the problem. Currently, it is confirmed that the entire process is stuck in the
**”OMTObstacleTracker::Associate2D“**
method when calling
**“OMTObstacleTracker::CreateNewTarget”**
Upon further output, it can be observed that the code is stuck at
**“auto &min_tmplt = kMinTemplateHWL.at(sub_type);”**
At the moment, I cannot find a solution. The log outputs information indicating the successful initialization of **“object_template_manager”**

![image](https://github.com/ApolloAuto/apollo/assets/22257928/1d2751a2-2d92-4a9c-89e5-0fe3175f0a7a)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/af4bcd8d-132a-4bf7-845e-397c034675c2)

**Comment by LordonCN** [comment]
> I am outputting the content of the 'track' line by line to identify the problem. Currently, it is confirmed that the entire process is stuck in the **”OMTObstacleTracker::Associate2D“** method when calling **“OMTObstacleTracker::CreateNewTarget”** Upon further output, it can be observed that the code is stuck at **“auto &min_tmplt = kMinTemplateHWL.at(sub_type);”** At the moment, I cannot find a solution. The log outputs information indicating the successful initialization of **“object_template_manager”**
> 
> ![image](https://user-images.githubusercontent.com/22257928/284531376-1d2751a2-2d92-4a9c-89e5-0fe3175f0a7a.png) ![image](https://user-images.githubusercontent.com/22257928/284531442-af4bcd8d-132a-4bf7-845e-397c034675c2.png)

Thanks for your work, it's true that `sub_type` keeps 0 in omt tracking stage.
Main reason is vector types_ in `modules/perception/camera_detection_3d/detector/smoke/smoke_obstacle_detector.h` file is empty, your can change InitParam function like this:
```
void SmokeObstacleDetector::InitParam(const smoke::ModelParam &model_param) {
  // min 2d height
  min_dims_ = model_param.min_dims();
  // confidence threshold
  confidence_threshold_ = model_param.confidence_threshold();
  // ori cycle
  ori_cycle_ = model_param.ori_cycle();
  // border ratio
  border_ratio_ = model_param.border_ratio();
  
  // add these
  types_.push_back(base::ObjectSubType::CAR);
  types_.push_back(base::ObjectSubType::VAN);
  types_.push_back(base::ObjectSubType::TRUCK);
  types_.push_back(base::ObjectSubType::BUS);
  types_.push_back(base::ObjectSubType::PEDESTRIAN);
  types_.push_back(base::ObjectSubType::CYCLIST);
  types_.push_back(base::ObjectSubType::TRAFFICCONE);
}
```
We will fix this and other omt bugs in next version.

**Comment by LordonCN** [comment]
> ### System information
> * **OS Platform and Distribution **: orin
> * **Apollo version **:9.0
> 
> ### Steps to reproduce the issue:
> After successfully building the perception module, I attempted to test the effect of the smoke. I used the command "mainboard -d modules/transform/dag/static_transform.dag -d modules/perception/camera_detection_single_stage/dag/camera_detection_single_stage.dag -d modules/perception/camera_location_estimation/dag/camera_location_estimation.dag -d modules/perception/camera_location_refinement/dag/camera_location_refinement.dag -d modules/perception/camera_tracking/dag/camera_tracking.dag -d modules/perception/multi_sensor_fusion/dag/multi_sensor_fusion.dag" to launch the modules. However, the "/apollo/perception/obstacles" topic consistently had no information. Upon inspecting the logs, I found that it was stuck in the tracker module. The logs indicated that the detection, location_estimation, and location_refinement modules were producing output normally, but the tracker module only output the following message once:: "I1116 16:05:16.286335 48529 camera_tracking_component.cc:71] Enter Tracking component, message timestamp: 1513807824.641768 current timestamp: 1700121916.286372." Could you please advise me on how to debug the camera tracker module?
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):
> ![image](https://user-images.githubusercontent.com/22257928/283398963-88f4ce8e-03a3-4cd5-900d-3eadfbbbea06.png)
> 
> ![image](https://user-images.githubusercontent.com/22257928/283399467-bff467b8-4be9-4541-a387-bfd697208210.png) ![image](https://user-images.githubusercontent.com/22257928/283399814-50d1001b-1e97-49f7-9251-9e0b165d5acf.png)

You can use following command to start smoke:
1. Modify readers channel in `modules/perception/camera_tracking/dag/camera_tracking.dag` to smoke output channel in `modules/perception/camera_detection_single_stage/conf/camera_detection_single_stage_config.pb.txt`
2. launch it
```bash
cyber_launch start modules/perception/launch/perception_camera_single_stage.launch
```
You can use following command to gdb:
```
gdb mainboard
>> set args -d /apollo/modules/perception/msg_adapter/dag/msg_adapter.dag -d /apollo/modules/perception/camera_detection_single_stage/dag/camera_detection_single_stage.dag -d /apollo/modules/perception/camera_tracking/dag/camera_tracking.dag -p camera -s CYBER_DEFAULT
>> run
>> bt
```

**Comment by LordonCN** [comment]
Please reopen this issue if you have any other question.
