### ISSUE TITLE
no such package '@remotejdk11_linux//'

### ISSUE THREAD

**Issue by wqklihbf** [ApolloAuto/apollo#15195]
### System information

- **OS Platform and Distribution: Linux Ubuntu 20.04
- **Apollo installed from: 软件包
- **Apollo version :8.0

### Steps to reproduce the issue:
When I run the command:
`bazel test //modules/localization/rtk:rtk_localization_test`
I meet the error:
![2023-11-15 10-29-58 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/128605713/762500fb-383e-4b6e-9f9d-785bdd2d175b)
`ERROR: /apollo_workspace/.cache/bazel/679551712d2357b63e6e0ce858ebf90e/external/bazel_tools/tools/jdk/BUILD:490:6: no such package '@remotejdk11_linux//': BUILD file not found in directory '' of external repository @remotejdk11_linux. Add a BUILD file to a directory to mark it as a package. and referenced by '@bazel_tools//tools/jdk:remote_jdk11'`

**Comment by wqklihbf** [comment]
I check the `/apollo_workspace/.cache/bazel/679551712d2357b63e6e0ce858ebf90e/external/bazel_tools/tools/jdk/BUILD' file：
![2023-11-15 11-59-35 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/128605713/6ef23131-be2b-460c-9243-8ec25e1ad586)
and I find them in the `/apollo_workspace/.cache/bazel/679551712d2357b63e6e0ce858ebf90e/external` directory：
![2023-11-15 12-35-26 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/128605713/f4ceb921-0140-4cc4-8ed1-c79654748382)
but there is no linux_x86_64.
Is this causing the error? If so, how do I fix it?

**Comment by WildBeast114514** [comment]
same as #15176, you can discuss the issue in there
