### ISSUE TITLE
bazel编译报错cuda

### ISSUE THREAD

**Issue by Anoqu0n** [ApolloAuto/apollo#15192]
![WeChat93bada7b0c12b6847579781130b07a78](https://github.com/ApolloAuto/apollo/assets/88700202/35f59395-5b27-4063-aad3-1cdc559003b3)

**Comment by WildBeast114514** [comment]
Apollo只支持兼容以下cuda算力的显卡：
```
_DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.7,5.2,6.0,6.1,7.0,7.2,7.5,8.6,8.7'
```
sm_20当前不被支持，请考虑切换更高算力的gpu或者不编译使用gpu的模块，仅使用cpu模式编译：
```
bash apollo.sh build_cpu
```

**Comment by Anoqu0n** [comment]
> Apollo只支持兼容以下cuda算力的显卡：
> 
> ```
> _DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.7,5.2,6.0,6.1,7.0,7.2,7.5,8.6,8.7'
> ```
> 
> sm_20当前不被支持，请考虑切换更高算力的gpu或者不编译使用gpu的模块，仅使用cpu模式编译：
> 
> ```
> bash apollo.sh build_cpu
> ```



> Apollo只支持兼容以下cuda算力的显卡：
> 
> ```
> _DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.7,5.2,6.0,6.1,7.0,7.2,7.5,8.6,8.7'
> ```
> 
> sm_20当前不被支持，请考虑切换更高算力的gpu或者不编译使用gpu的模块，仅使用cpu模式编译：
> 
> ```
> bash apollo.sh build_cpu
> ```
我的物理机系统是unbuntu18.04、显卡3090

**Comment by Anoqu0n** [comment]
> Apollo只支持兼容以下cuda算力的显卡：
> 
> ```
> _DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.7,5.2,6.0,6.1,7.0,7.2,7.5,8.6,8.7'
> ```
> 
> sm_20当前不被支持，请考虑切换更高算力的gpu或者不编译使用gpu的模块，仅使用cpu模式编译：
> 
> ```
> bash apollo.sh build_cpu
> ```

**Comment by Anoqu0n** [comment]
> Apollo只支持兼容以下cuda算力的显卡：
> 
> ```
> _DEFAULT_CUDA_COMPUTE_CAPABILITIES = '3.7,5.2,6.0,6.1,7.0,7.2,7.5,8.6,8.7'
> ```
> 
> sm_20当前不被支持，请考虑切换更高算力的gpu或者不编译使用gpu的模块，仅使用cpu模式编译：
> 
> ```
> bash apollo.sh build_cpu
> ```

我的物理机是unbuntu18.04，显卡是3090

**Comment by WildBeast114514** [comment]
看截图你是使用root账户进入容器的，可能会丢失部分需要的环境变量，请使用非root账户重新启动容器再进入试下

**Comment by Anoqu0n** [comment]
> 看截图你是使用root账户进入容器的，可能会丢失部分需要的环境变量，请使用非root账户重新启动容器再进入试下

我尝试建立docker群组进入，另外师傅你有用llvm编译Apollo的经验吗，可能还有其他的问题方便加个联系方式吗

**Comment by Anoqu0n** [comment]
> 看截图你是使用root账户进入容器的，可能会丢失部分需要的环境变量，请使用非root账户重新启动容器再进入试下

你好，root权限是指物理机的权限吗？不使用sudo进入 docker exec.. 我应该怎么进入呢

**Comment by WildBeast114514** [comment]
在宿主机使用非root用户运行docker/scripts/dev_start.sh启动容器，再运行docker/scripts/dev_into.sh进入
