### ISSUE TITLE
[9.0.0-beta] failed "buildtool build -p core"

### ISSUE THREAD

**Issue by tedelon** [ApolloAuto/apollo#15205]
### System information

- **ORIN Ubuntu 20.04**:
- **Apollo installed pnc**:
- **Apollo version  9.0.0-beta**:

### Steps to reproduce the issue:
- **enter container**:
- **aem update**:
- **buildtool build -p core**:

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/ApolloAuto/apollo/assets/49553101/180e784a-87fe-4d9c-8a54-7e3c322428b5)

**Comment by WildBeast114514** [comment]
please use latest application-core-arm repo: 
```
cd application-core-arm && aem start && aem enter
```
