### ISSUE TITLE
The module can not be turned on in dreamview plus

### ISSUE THREAD

**Issue by YHao29** [ApolloAuto/apollo#15218]
## When I try to turn on some modules in dreamview plus dashboard, some error alerts.
![2023-12-05 17-17-28 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/33367415/8228abd2-1f5a-41f3-b3a7-527f700781fe)

![2023-12-05 17-15-41 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/33367415/9bf40f36-4dee-4186-b4ae-784bf282a4d5)
## I have try to rebuild the corresponding module but it doesn't work.

**Comment by WildBeast114514** [comment]
It looks like your environment is missing the libopenblas-dev dependency.
```
sudo apt install libopenblas-dev
```

**Comment by WildBeast114514** [comment]
this issue should be fixed in current packages version
If you still encounter the same problem, please start a new issue or reopen this issue
