### ISSUE TITLE
pfe_cuda.pic.d(no such file or directory)

### ISSUE THREAD

**Issue by wqklihbf** [ApolloAuto/apollo#15222]
### System information

- **OS Platform and Distribution: Ubuntu 20.04
- **Apollo installed from: 软件包安装
- **Apollo version: 8.0

### Steps to reproduce the issue:
When I tried to practice the case study in 'Apollo Cyber RT Module Detailed Explanation and Practical Application', I used the command：
`buildtool build --packages examples/communication`
but encountered this error:
![2023-12-06 23-22-31 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/128605713/6eb9f082-16c2-4c41-85b3-cfcff5c7ddc7)

**Comment by daohu527** [comment]
It seems that buildtool compiles the perception module, which is the cause of the problem.

**Comment by wqklihbf** [comment]
> It seems that buildtool compiles the perception module, which is the cause of the problem.

I use the command:
`buildtool build --gpu -p test/communication`
and it compiles successfully. But I don't find the executable file in the directory `bazel-bin`

**Comment by wqklihbf** [comment]
目录结构：
/apollo_workspace/
  |﻿--test
  |   |﻿--communication
  |   |  |﻿--BUILD
      |  |﻿--talker.cc
      |  |﻿--listener.cc
      |﻿--proto 
         |﻿--BUILD
         |﻿--car.proto

`BUILD
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//tools/install:install.bzl", "install", "install_src_files")
load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "talker",
    srcs = ["talker.cc"],
    deps = [
        "//cyber",
        "//test/proto:car_cc_proto",
    ],
    linkstatic = True,
)
cc_binary(
    name = "listener",
    srcs = ["listener.cc"],
    deps = [
        "//cyber",
        "//test/proto:car_cc_proto",
    ],
    linkstatic = True,
)`

`talker.cc
#include "examples/proto/car.pb.h" 
#include "cyber/cyber.h"
#include "cyber/time/rate.h"

using apollo::cyber::examples::proto::Car;

int main(int argc, char *argv[]) {

  apollo::cyber::Init(argv[0]);

  auto talker_node = apollo::cyber::CreateNode("talker"); 

  auto talker = talker_node->CreateWriter<Car>("car_speed");
  AINFO << "I'll start telling you the current speed of the car.";

  uint64_t speed = 0;
  while (apollo::cyber::OK()) {
      auto msg = std::make_shared<Car>();
      msg->set_speed(speed);
      speed += 5;
      talker->Write(msg);
      sleep(1);
  }
  return 0;`

`listener.cc
#include "examples/proto/car.pb.h"
#include "cyber/cyber.h"

using apollo::cyber::examples::proto::Car;

void message_callback(
        const std::shared_ptr<Car>& msg) {
    AINFO << "now speed is: " << msg->speed();
}

int main(int argc, char* argv[]) {

    apollo::cyber::Init(argv[0]);

    auto listener_node = apollo::cyber::CreateNode("listener");

    auto listener = listener_node->CreateReader<Car>(
            "car_speed", message_callback);
    apollo::cyber::WaitForShutdown();
    return 0;
}`

`BUILD
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_cc//cc:defs.bzl", "cc_proto_library")
load("//tools:python_rules.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "car_proto",
    srcs = ["car.proto"],
)

cc_proto_library(
    name = "car_cc_proto",
    deps = [":car_proto"],
)`

`car.proto
syntax = "proto2";

package apollo.cyber.test.proto;

message Car{
    optional string plate = 1; 
    optional string type = 2;
    optional string owner = 3;
    optional uint64 kilometers = 4;
    optional uint64 speed = 5;
};
`

**Comment by wqklihbf** [comment]
I have solved the problem. Thanks!
