### ISSUE TITLE
IS 9.x_alpha supported xavier agx（ubuntu 18.04）

### ISSUE THREAD

**Issue by wusx** [ApolloAuto/apollo#15228]
runing dev_start.sh and pulling docker image return error info:

```
unexpected EOF
[ERROR] Failed to pull docker image : registry.baidubce.com/apolloauto/apollo:dev-aarch64-20.04-20231024_1054

```
then run dev_start.sh again

`[INFO] Start pulling docker image registry.baidubce.com/apolloauto/apollo:dev-aarch64-20.04-20231024_1054 ...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ERROR] Failed to pull docker image : registry.baidubce.com/apolloauto/apollo:dev-aarch64-20.04-20231024_1054
`
show error  docker was killed ?????? what happend??

**Comment by daohu527** [comment]
It seems that pulling the container failed, which has nothing to do with the hardware platform.

**Comment by wusx** [comment]
> It seems that pulling the container failed, which has nothing to do with the hardware platform.

how to fix it?

**Comment by wusx** [comment]
re-install jetpack

**Comment by Motor789** [comment]
can you run 9.0.0 version success on jetson AGX xavier platform？I have the following question:WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
91101c235702708fe0f228567b6939be86fb71f54ae673e98e4209d55868ec27
[INFO] Starting docker container "apollo_dev_root" ...

docker run -itd --privileged --name apollo_dev_root -e DISPLAY=:0 -e DOCKER_USER=root -e USER=root -e DOCKER_USER_ID=0 -e DOCKER_GRP=root -e DOCKER_GRP_ID=0 -e DOCKER_IMG=apolloauto/apollo:dev-aarch64-18.04-20200915_0106 -e USE_GPU_HOST=0 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility --volumes-from apollo_map_volume-sunnyvale_big_loop_root --volumes-from apollo_map_volume-sunnyvale_loop_root --volumes-from apollo_map_volume-sunnyvale_with_two_offices_root --volumes-from apollo_map_volume-san_mateo_root --volumes-from apollo_localization_volume_root --volumes-from apollo_audio_volume_root --volumes-from apollo_yolov4_volume_root --volumes-from apollo_faster_rcnn_volume_root -v /mnt/ssd/Apollo_6/apollo:/apollo -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in-dev-docker:127.0.0.1 --add-host movex:127.0.0.1 --hostname in-dev-docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 apolloauto/apollo:dev-aarch64-18.04-20200915_0106 /bin/bash
docker: Error response from daemon: No such container: apollo_audio_volume_root.
See 'docker run --help'.
'[' 125 -ne 0 ']'
error 'Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-aarch64-18.04-20200915_0106'
echo -e '[\033[0;31mERROR\033[0m] Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-aarch64-18.04-20200915_0106'
[ERROR] Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-aarch64-18.04-20200915_0106
exit 1`
