### ISSUE TITLE
Launching Dreamview+

### ISSUE THREAD

**Issue by YuqiHuai** [ApolloAuto/apollo#15233]
I am interested in trying out Dreamview 2.0 (Dreamview+), and noticed documentation suggests starting it using `aem`

```
aem bootstrap start --plus
```

Is there a way to launch Dreamview 2.0 without `aem`? For example, in older versions we do
```
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
# Now we are in the container
bash scripts/bootstrap.sh
```

Can we do something similar to launch the newest version of Dreamview?

I tried `bash scripts/bootstrap.sh --plus` according to the [documentation](https://github.com/ApolloAuto/apollo/tree/master/modules/dreamview_plus) in `dreamview_plus` but it looks like the original Dreamview.

Looks like the correct command should be `bash scripts/bootstrap.sh start_plus`

**Comment by wk19921225** [comment]
Thank you for your interest in Apollo and Dreamview 2.0. This issue might be due to an oversight by our documentation writers. When you need to launch Dreamview 2.0 (Dreamview+) in a source code environment, you should execute the command `bash scripts/bootstrap.sh start_plus`.
