### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Zhiyu-h** [ApolloAuto/apollo#15238]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

Ubuntu20.04 显卡4060 编译apollo报错

### Steps to reproduce the issue:
(09:52:34) WARNING: /apollo/modules/planning/tasks/lane_change_path/proto/BUILD:17:15: runfiles symlink modules/planning/tasks/lane_change_path/proto/install_src -> bazel-out/k8-fastbuild/bin/modules/planning/tasks/lane_change_path/proto/install_src obscured by modules/planning/tasks/lane_change_path/proto -> modules/planning/tasks/lane_change_path/proto
(09:52:34) WARNING: /apollo/modules/storytelling/proto/BUILD:12:15: runfiles symlink modules/storytelling/proto/install_module_src -> bazel-out/k8-fastbuild/bin/modules/storytelling/proto/install_module_src obscured by modules/storytelling/proto -> modules/storytelling/proto
(09:52:39) WARNING: /apollo/modules/common_msgs/planning_msgs/BUILD:89:15: runfiles symlink modules/common_msgs/planning_msgs/install_src -> bazel-out/k8-fastbuild/bin/modules/common_msgs/planning_msgs/install_src obscured by modules/common_msgs/planning_msgs -> modules/common_msgs/planning_msgs
(09:52:39) WARNING: /apollo/modules/planning/tasks/lane_borrow_path/BUILD:27:15: runfiles symlink modules/planning/tasks/lane_borrow_path/install_src -> bazel-out/k8-fastbuild/bin/modules/planning/tasks/lane_borrow_path/install_src obscured by modules/planning/tasks/lane_borrow_path -> modules/planning/tasks/lane_borrow_path
(09:52:39) WARNING: /apollo/modules/routing/BUILD:183:15: runfiles symlink modules/routing/install_module_src -> bazel-out/k8-fastbuild/bin/modules/routing/install_module_src obscured by modules/routing -> modules/routing
(09:52:39) WARNING: /apollo/modules/control/controllers/lon_based_pid_controller/proto/BUILD:16:15: runfiles symlink modules/control/controllers/lon_based_pid_controller/proto/install_src -> bazel-out/k8-fastbuild/bin/modules/control/controllers/lon_based_pid_controller/proto/install_src obscured by modules/control/controllers/lon_based_pid_controller/proto -> modules/control/controllers/lon_based_pid_controller/proto
(09:52:46) INFO: From Compiling modules/drivers/lidar/robosense/component/component.cpp:
In file included from external/boost/boost/signals2/detail/null_output_iterator.hpp:14:0,
                 from external/boost/boost/signals2/connection.hpp:22,
                 from external/boost/boost/signals2/signal.hpp:22,
                 from external/boost/boost/signals2.hpp:19,
                 from bazel-out/k8-fastbuild/bin/external/local_config_pcl/_virtual_includes/pcl_headers/pcl/io/boost.h:64,
                 from bazel-out/k8-fastbuild/bin/external/local_config_pcl/_virtual_includes/pcl_headers/pcl/io/file_io.h:42,
                 from bazel-out/k8-fastbuild/bin/external/local_config_pcl/_virtual_includes/pcl_headers/pcl/io/pcd_io.h:44,
                 from ./modules/drivers/lidar/robosense/component/component_convert.h:23,
                 from modules/drivers/lidar/robosense/component/component.cpp:17:
external/boost/boost/function_output_iterator.hpp:14:72: note: #pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
                                                                        ^
(09:52:54) ERROR: /apollo/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/local_config_tensorrt/BUILD:43:8: Executing genrule @local_config_tensorrt//:tensorrt_lib failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
cp: cannot stat '/usr/lib/x86_64-linux-gnu/libnvinfer.so.7': No such file or directory
(09:52:54) INFO: Elapsed time: 139.223s, Critical Path: 33.67s
(09:52:54) INFO: 3915 processes: 3225 internal, 690 local.
(09:52:54) FAILED: Build did NOT complete successfully

**Comment by arayzhou** [comment]
您好 请问您解决了吗？我用4060遇到了同样的问题
