### ISSUE TITLE
Apollo9.0 Build Faild In Orin

### ISSUE THREAD

**Issue by Hgsil** [ApolloAuto/apollo#15237]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Orin Arrch64 Linux Ubuntu 20.04 
- **Apollo installed from (source or binary)**: source 
- **Apollo version**: 9.0

### Steps to reproduce the issue:

After you create a container with **dev_start.sh** and enter the container. Compiling the source code with **./apollo.sh build_opt** yields an error, and compiling the perception module with **./apollo.sh build_gpu perception** yields several different errors with similar formats.

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/ApolloAuto/apollo/assets/22257928/8ad4c509-f182-4dd0-9650-a34ea99ca966)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/21aeb2c2-286e-466a-80de-b086cf5d09d2)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/e79708ae-6fb7-4595-bf2f-6304b6c85309)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/28e12a27-ce6d-4a6c-a89c-3379735ccfb7)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/87f51c5c-186c-4c97-b1cf-f1906102074e)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/0fcce114-c61a-457a-b2f0-ba347b10514b)
![image](https://github.com/ApolloAuto/apollo/assets/22257928/e9e9ef45-7988-4313-8580-90760f5f154b)

**Comment by WildBeast114514** [comment]
This may be due to environment variables not being set correctly, confirm the following environment variables:
`TF_NEED_CUDA`, `GPU_PLATFORM`
If they were not set or equal with 0, please running the following command:

```
export TF_NEED_CUDA=1
export GPU_PLATFORM=NVIDIA
```

and recompile

**Comment by Hgsil** [comment]
The problem persists and remains the same as before.
![image](https://github.com/ApolloAuto/apollo/assets/22257928/ef216746-fa60-4b41-90f6-59cd833d27dd)
the enviroment is like this.
![image](https://github.com/ApolloAuto/apollo/assets/22257928/8fd5ab52-7169-4910-9a7f-6899f4b55668)

**Comment by WildBeast114514** [comment]
rm -f .apollo.bazelrc

**Comment by WildBeast114514** [comment]
according to the log, the gpu arch is UNKNOWN.
make sure GPU_PLATFORM is equal with "NVIDIA"
and remove the bazelrc file
```
rm -f .apollo.bazelrc
```
and recompile

**Comment by WildBeast114514** [comment]
We have updated the code in the master branch and verified that the problem is no longer there, you can try the following actions to recompile:
```
# exit the container
git pull
# remove rc files generated by the wrong environment variable
rm -f .apollo.bazelrc
# restart a new container
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```
and recompile
