### ISSUE TITLE
error: undefined reference to 'cudaFree'

### ISSUE THREAD

**Issue by wusx** [ApolloAuto/apollo#15242]
you can solve this erro by following this work.
![image](https://github.com/ApolloAuto/apollo/assets/22257928/ec8ac192-8938-4d4d-b505-3ab32b6d7bfa)

_Originally posted by @Hgsil in https://github.com/ApolloAuto/apollo/issues/15240#issuecomment-1865855280_

thx ur solution and fix the issue，but there is a new problem
![image](https://user-images.githubusercontent.com/8363113/292235391-f2440981-c0b1-4f33-b291-1b9d16da61dd.png)

**Comment by wusx** [comment]
close

**Comment by WildBeast114514** [comment]
We have updated the code in the master branch and verified that the problem is no longer there, you can try the following actions to recompile:
```
# exit the container
git pull
# remove rc files generated by the wrong environment variable
rm -f .apollo.bazelrc
# restart a new container
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```
and recompile

**Comment by wusx** [comment]
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/cuda-11.4/targets/aarch64-linux/include/
export TF_NEED_CUDA=1
export GPU_PLATFORM=NVIDIA
