### ISSUE TITLE
Apollo9.0 Build Faild In Orin, can't find dependence library of libcudla.so

### ISSUE THREAD

**Issue by EmrysChe** [ApolloAuto/apollo#15249]
System information
OS Platform and Distribution Orin Arrch64 Linux Ubuntu 20.04
Apollo installed from (source or binary): source
Apollo version: 9.0

run bash command in docker : bash apollo.sh build_opt_nvidia

error in linking modules/perception/common/inference/tensorrt/argmax_plugin_test, I can't find libnvdla_runtime.so and libnvdla_compiler.so in container which is needed by libcudla.so.1

![微信图片_20231228134735](https://github.com/ApolloAuto/apollo/assets/25098417/f6cb900d-54d5-48cc-bf8c-2e4d81d37715)

**Comment by EmrysChe** [comment]
I also have ran
```bash
export TF_NEED_CUDA=1
export GPU_PLATFORM=NVIDIA
export CPLUS_INCLUDE_PATH=$$CPLUS_INCLUDE_PATH:/usr/local/cuda-11.4/targets/aarch64-linux/include
```

**Comment by ScottDeng114514** [comment]
Try this,out of docker:
sudo docker cp /usr/lib/aarch64-linux-gnu/tegra [container_id]:/usr/lib/aarch64-linux-gnu/

**Comment by Ybt-1** [comment]
> Try this,out of docker: sudo docker cp /usr/lib/aarch64-linux-gnu/tegra [container_id]:/usr/lib/aarch64-linux-gnu/

Tegra cannot be found in the /usr/lib/aarch64-linux-gnu/ folder. How should I solve this problem?

**Comment by hlhtddx** [comment]
`bash docker/script/dev_into.sh` to enter dev env.

`sudo apt install nvidia-l4t-cuda nvidia-l4t-core` to install missing dependencies
