### ISSUE TITLE
Apollo9.0 Build Faild In Orin TOO

### ISSUE THREAD

**Issue by wusx** [ApolloAuto/apollo#15240]
System information
OS Platform and Distribution  Orin Arrch64 Linux Ubuntu 20.04
Apollo installed from (source or binary): source
Apollo version: 9.0

run bash command in docker : bash apollo.sh build_opt_nvidia
return error info 
![2023-12-21_13-42](https://github.com/ApolloAuto/apollo/assets/8363113/37d6fb46-80a4-415d-a18a-e67b3bcc36c3)

and this is cuda info
![2023-12-21_13-44](https://github.com/ApolloAuto/apollo/assets/8363113/a181bb45-1ac8-48cf-ab22-c9f20c531f40)

**Comment by Hgsil** [comment]
you can solve this erro by following this work.
![image](https://github.com/ApolloAuto/apollo/assets/22257928/ec8ac192-8938-4d4d-b505-3ab32b6d7bfa)

**Comment by wusx** [comment]
> you can solve this erro by following this work. ![image](https://private-user-images.githubusercontent.com/22257928/292143533-ec8ac192-8938-4d4d-b505-3ab32b6d7bfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzA0NDksIm5iZiI6MTcwMzE3MDE0OSwicGF0aCI6Ii8yMjI1NzkyOC8yOTIxNDM1MzMtZWM4YWMxOTItODkzOC00ZDRkLWI1MDUtM2FiMzJiNmQ3YmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE0NDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGM2YTgzNTM0ZTdjODAxZDI0MjFiNWRkNGZhMzYwMDljNzMzZTI0MWU3MjViNjA4NzZkODRmYmFhNDc3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dLcN1J5trd8q1anIh0Nwc4e5-wpkNuKFR0nd7BekOjc)

thx ur solution and fix the issue，but there is a new problem
![image](https://github.com/ApolloAuto/apollo/assets/8363113/d5060e01-a2f3-45c2-9834-c21c39dcb366)

**Comment by WildBeast114514** [comment]
This may be due to environment variables not being set correctly, confirm the following environment variables:
`TF_NEED_CUDA`, `GPU_PLATFORM`
If they were not set or equal with 0, please running the following command:
```
export TF_NEED_CUDA=1
export GPU_PLATFORM=NVIDIA
```
and recompile

**Comment by ScottDeng114514** [comment]
> This may be due to environment variables not being set correctly, confirm the following environment variables: `TF_NEED_CUDA`, `GPU_PLATFORM` If they were not set or equal with 0, please running the following command:
> 
> ```
> export TF_NEED_CUDA=1
> export GPU_PLATFORM=NVIDIA
> ```
> 
> and recompile

The problem still exist after set the environment variables...
![Screenshot from 2023-12-28 14-06-17](https://github.com/ApolloAuto/apollo/assets/96806352/f938d2dd-c490-4284-8975-aa30c263e17e)

**Comment by ScottDeng114514** [comment]
I made it. Modify the "/apollo/scripts/apollo.bashrc" line 122, add
`need_cuda=1
 gpu_platform="NVIDIA"`
![Screenshot from 2023-12-28 16-02-23](https://github.com/ApolloAuto/apollo/assets/96806352/11c33ff4-da55-45f3-b79e-adabc973c96a)

**Comment by WildBeast114514** [comment]
> > This may be due to environment variables not being set correctly, confirm the following environment variables: `TF_NEED_CUDA`, `GPU_PLATFORM` If they were not set or equal with 0, please running the following command:
> > ```
> > export TF_NEED_CUDA=1
> > export GPU_PLATFORM=NVIDIA
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and recompile
> 
> The problem still exist after set the environment variables... ![Screenshot from 2023-12-28 14-06-17](https://private-user-images.githubusercontent.com/96806352/293147844-f938d2dd-c490-4284-8975-aa30c263e17e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTEwMDEsIm5iZiI6MTcwMzc1MDcwMSwicGF0aCI6Ii85NjgwNjM1Mi8yOTMxNDc4NDQtZjkzOGQyZGQtYzQ5MC00Mjg0LTg5NzUtYWEzMGMyNjNlMTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA4MDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NmFjNDI2ZDQ0MTFlYmVhNzMxNzMzMjY4YjYzZDM4MTM2NmQ4MGY5MmM2YThjY2QwZTBjOGQ4OTczN2QyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GWI4U-5Cm9B4EisvCRITmaob9P89LTmEn41jbCave1w)

We have updated the code in the master branch and verified that the problem is no longer there, you can try the following actions to recompile:
```
# exit the container
git pull
# remove rc files generated by the wrong environment variable
rm -f .apollo.bazelrc
# restart a new container
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```
and recompile

**Comment by yaobaishen** [comment]
> I made it. Modify the "/apollo/scripts/apollo.bashrc" line 122, add `need_cuda=1 gpu_platform="NVIDIA"` ![Screenshot from 2023-12-28 16-02-23](https://github.com/ApolloAuto/apollo/assets/96806352/11c33ff4-da55-45f3-b79e-adabc973c96a)

To whom try to build tag/v9.0.0 on Nvidia Orin, have already added the **need_cuda=1 gpu_platform="NVIDIA"** as the link above, but still run into error as below:
`
aarch64-linux-gnu-gcc-9: error: unrecognized command line option ‘-mavx2’
`
Please also modify the scripts/apollo_base.sh like below:

```
# original lines 
job_args="--copt=-mavx2 --host_copt=-mavx2 --jobs=${count} --local_ram_resources=HOST_RAM*0.7"

# modified lines
  if [[ $(uname -m) == "x86_64" ]]; then
    job_args="--copt=-mavx2 --host_copt=-mavx2 --jobs=${count} --local_ram_resources=HOST_RAM*0.7"
  else
    job_args="--copt=-march=native --host_copt=-march=native --jobs=${count} --local_ram_resources=HOST_RAM*0.7  --copt=-fPIC --host_copt=-fPIC"
  fi
```
