### ISSUE TITLE
Apollo 9.0 Failed Build Perception in x86(4090).

### ISSUE THREAD

**Issue by Hgsil** [ApolloAuto/apollo#15243]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: ubuntu 22.04
- **Apollo installed from (source or binary)**: source
- **Apollo version **: 9.0 release

### Steps to reproduce the issue:
I compiled apollo9.0 in 4090 as described in the [url ](https://apollo.baidu.com/community/article/1212) and the following error was output.

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/ApolloAuto/apollo/assets/22257928/4280c750-1519-4f81-843f-32962dce35c7)

**Comment by ScottDeng114514** [comment]
![2023-12-22 17-38-55 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/96806352/efd8d890-ee5b-423b-a5f3-7e7230cffa71)
Emm, I've just built apollo-9.0.0 on my 4090 x86 machine, but I didn't meet any problem. What's the output of command "bash /apollo/apollo.sh config -n" in your docker?

**Comment by Hgsil** [comment]
the output is like this.
![image](https://github.com/ApolloAuto/apollo/assets/22257928/4a9edd11-5135-4e01-82b7-d455decd47b8)

**Comment by ScottDeng114514** [comment]
Then how about "lscpu"?
By the way, my hardware:
cpu: 12th Gen Intel® Core™ i7-12700 × 20
gpu: NVIDIA GeForce RTX 4090
And os: ubuntu 20.04.1

**Comment by Hgsil** [comment]
the output is like this.
![image](https://github.com/ApolloAuto/apollo/assets/22257928/4a9edd11-5135-4e01-82b7-d455decd47b8)


> lscpu
my hardware:
cpu: Intel(R) Xeon(R) Platinum 8336C CPU
gpu: NVIDIA GeForce RTX 4090 * 4
And os: ubuntu 22.04.1
Could the difference in Ubuntu version be the cause of this problem?
The output of "lscpu" is :
![image](https://github.com/ApolloAuto/apollo/assets/22257928/506faed9-35cb-48fc-8724-3670eb416609)

**Comment by ScottDeng114514** [comment]
Seems nothing wrong, and I don't think the ubuntu version matters.
Try disable the c option "--copt=-mavx2 --host_copt=-mavx2" in /apollo/scripts/apollo_base.sh, line 744
and then clean and rebuild:
./apollo.sh clean -a
./apollo.sh build_opt_gpu perception
Hope this work...

**Comment by Hgsil** [comment]
Unfortunately, this problem still exists, so please ask if you have changed it according to the  [url ].(https://apollo.baidu.com/community/article/1212)

**Comment by Hgsil** [comment]
> Seems nothing wrong, and I don't think the ubuntu version matters. Try disable the c option "--copt=-mavx2 --host_copt=-mavx2" in /apollo/scripts/apollo_base.sh, line 744 and then clean and rebuild: ./apollo.sh clean -a ./apollo.sh build_opt_gpu perception Hope this work...

Unfortunately, this problem still exists, so please ask if you have changed it according to the [url ](https://apollo.baidu.com/community/article/1212).

**Comment by ScottDeng114514** [comment]
No, I just download 9.0, unzip, dev_start and dev_into and modified files as that url indicates, then build.

**Comment by Hgsil** [comment]
> No, I just download 9.0, unzip, dev_start and dev_into and modified files as that url indicates, then build.

If I don't make changes, using the 9.0 release version will give the following error.

![image](https://github.com/ApolloAuto/apollo/assets/22257928/6379458a-39de-495e-97ca-00d816d5fbbc)

**Comment by Hgsil** [comment]
> No, I just download 9.0, unzip, dev_start and dev_into and modified files as that url indicates, then build.

Thank you very much for your help, have you encountered this problem?
![image](https://github.com/ApolloAuto/apollo/assets/22257928/a61c32cd-0ae3-4fdf-89d4-63978ec430f4)
 
I tried using the use of find / -name "libnvinfer" but I didn't find it.

**Comment by Hgsil** [comment]
> > No, I just download 9.0, unzip, dev_start and dev_into and modified files as that url indicates, then build.
> 
> Thank you very much for your help, have you encountered this problem? ![image](https://private-user-images.githubusercontent.com/22257928/292719129-a61c32cd-0ae3-4fdf-89d4-63978ec430f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODY0NjQsIm5iZiI6MTcwMzQ4NjE2NCwicGF0aCI6Ii8yMjI1NzkyOC8yOTI3MTkxMjktYTYxYzMyY2QtMGFlMy00ZmRmLTg5ZDQtNjM5NzhlYzQzMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA2MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiODYxOTQ5MWRhYWFhZDNjZmU5ZWJiZDM2ZjI0YmY1NWU4YmEzZjhmZTljOWMxN2Y3NjY4MWM4MTg4YjU3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqtHlx90VEsspyvesXhHGtc2KE7uQNt8AIfaE55Wlio)
> 
> I tried using the use of find / -name "libnvinfer" but I didn't find it.


> No, I just download 9.0, unzip, dev_start and dev_into and modified files as that url indicates, then build.

I managed to solve this problem, thank you very much for your help.
