### ISSUE TITLE
dev_start进不去

### ISSUE THREAD

**Issue by yy7410** [ApolloAuto/apollo#15246]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., WSL Ubuntu 20.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version 9.0**:
4070ti显卡，使用默认的20230831的那个版本能正常进docker，但编译报错，更改了镜像版本VERSION_X86_64="dev-x86_64-18.04-20231128_2222"，进不去docker，dev_start.sh报错：
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/2a3ff18f66d28484f1c43cdc5086a2cb78b6b6153b81162557dcbd6e7f56c16b/merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown.

**Comment by johnny710vip** [comment]
使用默认的20230831的那个版本能正常进docker，但编译报错，这个报啥错呢

**Comment by johnny710vip** [comment]
重新装一下nvidia-docker试试

**Comment by johnny710vip** [comment]
可以参考这个文档：https://apollo.baidu.com/community/Apollo-Homepage-Document?doc=BYFxAcGcC4HpYIbgPYBtXIHQCMEEsATAV0wGNkBbWA5UyRFdZWVBEAU0hFgoIH0adPgCY%2BADwCiAVnEBBCeIAcATnETFcgMxKZkgGxKAwkoDsa3YoAi45WdH7xAIVk2ADGrNjZ7sYoCM5nIKvqqkenrCwgjY7MpSmsqartjCfrYI7OEEAGauCFJ%2BBKQEmKAUqEA

**Comment by johnny710vip** [comment]
https://apollo.baidu.com/community/Apollo-Homepage-Document?doc=BYFxAcGcC4HpYIbgPYBtXIHQCMEEsATAV0wGNkBbWA5UyRFdZWVBEAU0hFgoIH0adPgCY%2BADwCiAVnEBBCeIAcATnETFcgMxKZkgGxKAwkoDsa3YoAi45WdH7xAIVk2ADGrNjZ7sYoCM5nIKvqqkenrCwgjY7MpSmsqartjCfrYI7OEEAGauCFJ%2BBKQEmKAUqEA 可以参考这个文档，安装 Nvidia container toolkit：
为了在容器内获得 GPU 支持，在安装完 docker 后需要安装 NVIDIA Container Toolkit。 运行以下指令安装 NVIDIA Container Toolkit：

distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get -y update
sudo apt-get install -y nvidia-docker2
安装完毕后，需要手动重启下docker：

sudo systemctl restart docker

**Comment by yy7410** [comment]
> https://apollo.baidu.com/community/Apollo-Homepage-Document?doc=BYFxAcGcC4HpYIbgPYBtXIHQCMEEsATAV0wGNkBbWA5UyRFdZWVBEAU0hFgoIH0adPgCY%2BADwCiAVnEBBCeIAcATnETFcgMxKZkgGxKAwkoDsa3YoAi45WdH7xAIVk2ADGrNjZ7sYoCM5nIKvqqkenrCwgjY7MpSmsqartjCfrYI7OEEAGauCFJ%2BBKQEmKAUqEA 可以参考这个文档，安装 Nvidia container toolkit： 为了在容器内获得 GPU 支持，在安装完 docker 后需要安装 NVIDIA Container Toolkit。 运行以下指令安装 NVIDIA Container Toolkit：
> 
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID) curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list sudo apt-get -y update sudo apt-get install -y nvidia-docker2 安装完毕后，需要手动重启下docker：
> 
> sudo systemctl restart docker

卸载并重新安装nvidia-docker2，dev_start.sh还是报同样的错误。
nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/.../merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown.

**Comment by ScottDeng114514** [comment]
更新下gpu驱动吧

**Comment by qilinhu** [comment]
@yy7410 
According to the reference you provided, when you started the container, a "docker:Error response from daemon:failed to create task for container'" error occurred. this
The error is usually caused by a problem with a previously running container trying to start. You can try the following two methods to solve this problem:
1 Delete the previously running container and re-execute the script.
2 Modify the DEV_CONTAINER_PREFIX name in the dev_start.sh script, modify the DEV_CONTAINER_PREFIX name in the dev_into.sh script to keep it consistent with the name in the dev_start.sh script, and restart.

**Comment by yy7410** [comment]
谢谢大家，目前问题已经解决，解决办法如下：
1、使用sudo docker run --rm -ti <镜像名>进入镜像内；
2、使用rm /usr/lib/x86_64-linux-gnu/libnvidia-*
           rm /usr/lib/x86_64-linux-gnu/libcuda.so*
          rm /usr/lib/x86_64-linux-gnu/libnvcuvid.so.*，删除镜像内NVIDIA相关内容；
3、使用docker commit把此时的容器打包为镜像。
通过以上操作dev_start.sh可正常运行，在docker内使用nvidia-smi可显示显卡信息，并且编译无报错。
