### ISSUE TITLE
9.0 perception launch error, Failed to load camera intrinsic: .../onsemi_obstacle_intrinsics.yaml

### ISSUE THREAD

**Issue by ScottDeng114514** [ApolloAuto/apollo#15248]
\### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 9.0

### Steps to reproduce the issue:
- perception launch error

### Supporting materials (screenshots, command lines, code/script snippets):
`[camera ]  E1225 10:39:06.371878 2028624 sensor_manager.cc:79] [mainboard]Failed to load camera intrinsic:/apollo/modules/perception/data/params/onsemi_obstacle_intrinsics.yaml
[camera ]  E1225 10:39:06.371891 2028624 sensor_manager.cc:93] [mainboard]Failed to add sensor_info: onsemi_obstacle
[camera ]  F1225 10:39:06.371898 2028624 sensor_manager.cc:37] Check failed: this->Init() == true (0 vs. 1) `

**Comment by Hgsil** [comment]
哥们你找到在哪下载yolox的权重了么，你的感知模型用的是以前给过权重的模型么

**Comment by ScottDeng114514** [comment]
> 哥们你找到在哪下载yolox的权重了么，你的感知模型用的是以前给过权重的模型么

https://github.com/ApolloAuto/apollo/discussions/15212
你说这个吗

**Comment by Hgsil** [comment]
> > 哥们你找到在哪下载yolox的权重了么，你的感知模型用的是以前给过权重的模型么
> 
> #15212 你说这个吗

谢谢！！！我前两天没看到

**Comment by qilinhu** [comment]
@ScottDeng114514 
看你发的报错，应该是找不到相关的内外参文件，你选择的车型是什么，建议选择mkz_121车型文件，应该能解决你上述出现的问题。

**Comment by ScottDeng114514** [comment]
> @ScottDeng114514 看你发的报错，应该是找不到相关的内外参文件，你选择的车型是什么，建议选择mkz_121车型文件，应该能解决你上述出现的问题。

我直接注释掉了这个参数文件emmm

**Comment by persistisok** [comment]
这个问题解决了吗
