### ISSUE TITLE
Error with docker/scripts/release_start.sh

### ISSUE THREAD

**Issue by vivianistan** [ApolloAuto/apollo#1525]
Before when I ran the release_start.sh script it would work fine, but for some reason now I get this error: 

`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/apollo/scripts/bootstrap.sh\": stat /apollo/scripts/bootstrap.sh: no such file or directory"`

Any idea what might be causing this error?

**Comment by JKTesla** [comment]
Suggest you execute **git pull** in your Apollo repository to update your files;

or maybe you can also **restsart docker**.hope they do work.

**Comment by vivianistan** [comment]
A git pull fixed the problem, thanks!

**Comment by JKTesla** [comment]
You are welcome.Maybe There are many problems to be solved,best wishes to you.
