### ISSUE TITLE
apollo 9.0 in Orin ,cyber_monitor Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ScottDeng114514** [ApolloAuto/apollo#15252]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: jetson orin ubuntu20.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:9.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
-  After running ./scripts/bootstrap.sh, cyber_monitor crashed

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2023-12-29 14-45-01](https://github.com/ApolloAuto/apollo/assets/96806352/05fbcbee-0ee8-41ca-9fdb-c0b1ea9d0910)

**Comment by wusx** [comment]
I have the same problem,how to fix it?

**Comment by wusx** [comment]
it's OK after recompile cyber_monitor !!!

bazel build cyber/tools/cyber_monitor/...

**Comment by WildBeast114514** [comment]
This problem is caused by the arm architecture does not specify the fPIC compilation options, the latest master branch has solved this problem, please pull the code to recompile.
