### ISSUE TITLE
编译apollo 报错

### ISSUE THREAD

**Issue by 1416524962** [ApolloAuto/apollo#15260]
![0106](https://github.com/ApolloAuto/apollo/assets/74476678/9a0a4b6e-bdd3-4e00-8618-70256dd828a8)

**Comment by freekevinCode** [comment]
相应BUILD文件中先注释掉报错部分的target

**Comment by lykling** [comment]
fixed on https://github.com/ApolloAuto/apollo/commit/bda6d118db3dc5d5f3fffa8b68e09711ec1a4d1f
