### ISSUE TITLE
orin tensorrt crash on apollo 9.0 docker

### ISSUE THREAD

**Issue by xhzzhang** [ApolloAuto/apollo#15281]
**Describe the bug**
As the title, I have a nvidia jetson orin 32G device, use apollo 8.0 source code, upgrade to 9.0 docker(dev-aarch64-20.04-20231024_1054) and related source code(such dev_start.sh, third_party/gpus and third_party/tenssort), and I tested deviceQuery.cu, it works on docker, and I success to build tenssort compenent, but when I run cyber_launch start this tenssort compenent, it crashes.

**To Reproduce**
1. use orin 32G and installed ubuntu 20.04
2. use apollo 8.0 source code, and install docker dev-aarch64-20.04-20231024_1054
3. upgrade apollo code  dev_start.sh, third_party/gpus and third_party/tenssort,etc.. like apollo master.

**Expected behavior**
success to run tensorrt code.

**Screenshots**
please see the log message.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 20.04
 - Browser [e.g. chrome, safari] firefox

**Additional context**
Here is log message:

[robot@in-dev-docker:/apollo]$ mainboard -d /apollo/modules/perception_robot/dag/perception.dag -p perception_robot -s CYBER_DEFAULT
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0119 20:54:13.818738 18242 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception_test/dag/perception.dag -p perception_robot -s CYBER_DEFAULT 
I0119 20:54:13.819470 18242 global_data.cc:153] []host ip: 192.168.1.156
I0119 20:54:13.820633 18242 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception_robot, has 1 dag conf
I0119 20:54:13.820655 18242 module_argument.cc:60] []dag_conf: /apollo/modules/perception_robot/dag/perception.dag
...
[I] [TRT] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 481, GPU 6903 (MiB)
[I] [TRT] [MemUsageChange] Init builder kernel library: CPU +302, GPU +285, now: CPU 805, GPU 7208 (MiB)
Illegal instruction (core dumped)

[robot@in-dev-docker:/apollo]$ ls data/core/
core_mainboard.18242
[robot@in-dev-docker:/apollo]$ which mainboard
/apollo/bazel-bin/cyber/mainboard/mainboard
[robot@in-dev-docker:/apollo]$ gdb /apollo/bazel-bin/cyber/mainboard/mainboard data/core/core_mainboard.18242
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /apollo/bazel-bin/cyber/mainboard/mainboard...
(No debugging symbols found in /apollo/bazel-bin/cyber/mainboard/mainboard)
[New LWP 18242]
[New LWP 18253]
[New LWP 18245]
[New LWP 18247]
[New LWP 18244]
[New LWP 18250]
[New LWP 18260]
[New LWP 18249]
[New LWP 18254]
[New LWP 18252]
[New LWP 18263]
[New LWP 18262]
[New LWP 18251]
[New LWP 18264]
[New LWP 18255]
[New LWP 18256]
[New LWP 18265]
[New LWP 18257]
[New LWP 18267]
[New LWP 18259]
[New LWP 18258]
[New LWP 18268]
[New LWP 18246]
[New LWP 18243]
[New LWP 18266]
[New LWP 18248]
[New LWP 18261]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `mainboard -d /apollo/modules/perception_test/dag/perception.dag -p perception_'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x0000ffff321a16b0 in ?? ()
   from /apollo/bazel-bin/modules/perception_test/../../_solib_local/_U@local_Uconfig_Utensorrt_S_S_Ctensorrt___Uexternal_Slocal_Uconfig_Utensorrt_Stensorrt_Slib/libnvinfer.so.8
[Current thread is 1 (Thread 0xffff894ab040 (LWP 18242))]
(gdb) bt
#0  0x0000ffff321a16b0 in ?? ()
   from /apollo/bazel-bin/modules/perception_test/../../_solib_local/_U@local_Uconfig_Utensorrt_S_S_Ctensorrt___Uexternal_Slocal_Uconfig_Utensorrt_Stensorrt_Slib/libnvinfer.so.8
#1  0x0000aaaafb31b290 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) quit

**Comment by WildBeast114514** [comment]
According to the log, this coredump is not caused by tensorrt, but by running a binary that has an instruction that is not supported by orin (Illegal instruction)
The arm arch has been supported in apollo since 9.0.
Compiling 8.0 code on arm can have a number of problems, such as the sense module directly using an instruction set not supported by orin. you can use 9.0 code for compilation instead
