### ISSUE TITLE
Reflectance map folder is invalid! and Localization Status Is Missing

### ISSUE THREAD

**Issue by wqklihbf** [ApolloAuto/apollo#15284]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution: Linux Ubuntu 20.04
- **Apollo installed from : source
- **Apollo version: 8.0

### Steps to reproduce the issue:
When I was using [carla_apollo_bridge](https://github.com/guardstrikelab/carla_apollo_bridge), the localization module failed to start. 
When I used the command `cyber_launch start module/localization/launch/msf_localization.launch`, I encountered an error: `Reflectance map folder is invalid!`. 
After changing msf to rtk, the localization module was able to start, but the Dreamview interface showed a warning: `Current Localization Status Is Missing`

### Supporting materials (screenshots, command lines, code/script snippets):
![映射的地图错误](https://github.com/ApolloAuto/apollo/assets/128605713/313734b3-bb49-4731-bc72-a458a5e9a766)
![image](https://github.com/ApolloAuto/apollo/assets/128605713/227e5355-f68e-4e0d-abf1-6e20a4308ae0)
![image](https://github.com/ApolloAuto/apollo/assets/128605713/b559c6f5-5d63-4264-8bd1-f7f93147a3c3)

**Comment by daohu527** [comment]
I'm not too clear about msf_localization.launch, but rtk localization will be ok. This error prompts that there is no Localization status. You need to check whether the gnss driver topic is normal.

**Comment by wqklihbf** [comment]
> I'm not too clear about msf_localization.launch, but rtk localization will be ok. This error prompts that there is no Localization status. You need to check whether the gnss driver topic is normal.

Thanks for your reply. How do I know if they're normal? Do you mean the `FrameRatio` ? I found that the `FrameRatio` of these gnss driver topic is 20 and the topic `/apollo/localization/pose` is also 20.

**Comment by daohu527** [comment]
The following is the code that prints the error
https://github.com/ApolloAuto/apollo/blob/3859bee50e92d81e94f64ec4a3b3d4241978e8f5/modules/localization/rtk/rtk_localization.cc#L206-L211

which means `drivers::gnss::InsStat` is missing `pos_type`
https://github.com/ApolloAuto/apollo/blob/3859bee50e92d81e94f64ec4a3b3d4241978e8f5/modules/common_msgs/sensor_msgs/ins.proto#L8-L12

You can confirm whether carla sends these messages through cyber monitor.

**Comment by wqklihbf** [comment]
> The following is the code that prints the error
> 
> https://github.com/ApolloAuto/apollo/blob/3859bee50e92d81e94f64ec4a3b3d4241978e8f5/modules/localization/rtk/rtk_localization.cc#L206-L211
> 
> which means `drivers::gnss::InsStat` is missing `pos_type`
> 
> https://github.com/ApolloAuto/apollo/blob/3859bee50e92d81e94f64ec4a3b3d4241978e8f5/modules/common_msgs/sensor_msgs/ins.proto#L8-L12
> 
> You can confirm whether carla sends these messages through cyber monitor.

I check the topic `/apollo/sensor/gnss/ins_stat` and it is:
![2024-02-02 13-45-19 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/128605713/4960ff46-92fc-4fa6-bf05-2ab351af8f21)
Is the error `ins_status`?

**Comment by wqklihbf** [comment]
When I launch the `rtk` in the terminal, it will report this error: `Cannot find Matching IMU. IMU messages too old. Newest timestamp[1.70685e+09], GPS timestamp[1.70685e+09]`. Is it related to this error?
