### ISSUE TITLE
why cyber rt use for (;;)  here?

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#15286]
why cyber rt use for (;;)  here? it looks like that it cannot run loop here because the "if, else" cover all the conditions in this loop.
Also I found only this part and io part use yeild code, it is looks like that the coroutines is designed for these two parts. Maybe coroutines not necessary for cyber rt.
![image](https://github.com/ApolloAuto/apollo/assets/19343842/059cbde4-46ce-4d04-933e-30cb3cee397c)

**Comment by daohu527** [comment]
Actually, I didn't understand your question. The for loop will wait for data and execute. If there is no data, it will sleep. There is no problem with this.

You can describe your problem in detail for better discussion

**Comment by DieYoungWsn** [comment]
In the classic scheduler, multiple processors compete for access to a thread-safe coroutine queue (protected by a mutex) where coroutines are prioritized based on their priority levels, with higher-priority coroutines being selected for execution after the competition.

**Comment by fengmao31** [comment]
I test it one moth age. If delete the for (;;), the CRoutine will be finished. 

This keep the life of the CRoutine. The yeild make the thread jump from the for (;;) to other CRoutine.
