### ISSUE TITLE
reeds_shepp_path  cost computation bug

### ISSUE THREAD

**Issue by jjKeyLite** [ApolloAuto/apollo#15298]
tag v9.0.0，modules/planning/planning_base/open_space/coarse_trajectory_generator/reeds_shepp_path.cc,
line 124&127: cost += cost + traj_gear_switch_penalty_;
cost added two times.

**Comment by chenjian88888** [comment]
有点意思，好像是有问题

**Comment by daohu527** [comment]
@jjKeyLite @chenjian88888 Thank you for your contribution 😄 , the error has been fixed!
