### ISSUE TITLE
[buildtool] ERROR hint: planning-gpu-dev have been occupied

### ISSUE THREAD

**Issue by hkyee** [ApolloAuto/apollo#15296]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: Using Package Method
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: Apollo 8.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- aem start_gpu
- aem enter
- buildtool build --gpu

### Supporting materials (screenshots, command lines, code/script snippets):

[buildtool] INFO Import depends...
[buildtool] INFO Preprocess planning-gpu-dev
[buildtool] ERROR Encounter ErrCode.OccupiedErr
[buildtool] ERROR hint: planning-gpu-dev have been occupied
[buildtool] ERROR solution: If you really need this package, add or Modify 'src_path' attribute in depend label to fix this issue.
[buildtool] INFO apollo build tool exit.

May I know what does this mean?

**Comment by WildBeast114514** [comment]
checkout the path `modules/planning`, this message means the path of `modules/planning` is not the source code of planning.

**Comment by hkyee** [comment]
Thanks for the response @WildBeast114514. It appears that for planning_gpu to be built, I need to build it with --gpu flag. This issue has been solved.
