### ISSUE TITLE
apollo/docs/quickstart Chinese version

### ISSUE THREAD

**Issue by ycool** [ApolloAuto/apollo#153]
[apollo/docs/quickstart](https://github.com/ApolloAuto/apollo/tree/master/docs/quickstart)

**Comment by AllenLyu** [comment]
ok I translate it ASAP, maybe it still have some mistake but I thought it`s can make some help

**Comment by ycool** [comment]
@AllenLyu  thanks a lot for your great help!

**Comment by AllenLyu** [comment]
is other docs need Chinese ver ? if they need I would translate them asap.

**Comment by ycool** [comment]
It will be great if you can help. No need to rush and take your time. Thanks a lot 👍
