### ISSUE TITLE
ERROR hint:coud not find cyber_launch, is cyber already installed?

### ISSUE THREAD

**Issue by syang94** [ApolloAuto/apollo#15305]
使用包管理安装方式，aem start 和aem enter均无报错，执行aem bootstrap --plus，报错：ERROR hint:coud not find cyber_launch, is cyber already installed?

已按照官方文档中的包管理安装方式一步一步执行安装，请问问题出在哪里？谢谢

**Comment by Dennis-Chen2021** [comment]
[buildtool] 2024-04-20 16:53:22 INFO Reconfigure apollo enviroment setup
[buildtool] 2024-04-20 16:53:22 ERROR Encounter ErrCode.ModuleIsNotInstallErr
[buildtool] 2024-04-20 16:53:22 ERROR hint: Could not find cyber_launch. Is cyber already installed?
[buildtool] 2024-04-20 16:53:22 INFO Reconfigure apollo enviroment setup
[buildtool] 2024-04-20 16:53:22 ERROR Encounter ErrCode.ModuleIsNotInstallErr
[buildtool] 2024-04-20 16:53:22 ERROR hint: Could not find cyber_launch. Is cyber already installed?
[ERROR] Failed to start Dreamview. Please check /opt/apollo/neo/data/log/dreamview.log or /opt/apollo/neo/data/log/monitor.log for more information
请问解决了吗？一样的，也碰到了这个问题

**Comment by Luxru** [comment]
不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户

**Comment by 1091205886** [comment]
> 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户

可以解决

**Comment by lsm2842035890** [comment]
> 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户

具体命令是什么呀~~

**Comment by lsm2842035890** [comment]
> 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
file:///home/lms/Pictures/Screenshots/Screenshot%20from%202024-09-06%2020-05-06.png
这个路径是没有文件的，怎么回事

**Comment by lsm2842035890** [comment]
> 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
sudo chown -R lms:lms /opt/apollo/neo/data/log/
chown: cannot access '/opt/apollo/neo/data/log/': No such file or directory
这是怎么回事

**Comment by 1091205886** [comment]
> > 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
> 
> 具体命令是什么呀~~

使用`echo $USER`命令查看当前用户名；然后使用`chown`指令对`/opt/apollo/neo/data/log`目录修改拥有者就可以了

**Comment by ysy200187** [comment]
> > 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
> > sudo chown -R lms:lms /opt/apollo/neo/data/log/
> > chown: cannot access '/opt/apollo/neo/data/log/': No such file or directory
> > 这是怎么回事

你好 请问解决了吗

**Comment by chesongling123** [comment]
> > > 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
> > > sudo chown -R lms:lms /opt/apollo/neo/data/log/
> > > chown: cannot access '/opt/apollo/neo/data/log/': No such file or directory
> > > 这是怎么回事
> 
> 你好 请问解决了吗

你好，请问你们有出现这个问题吗？我在图片中这个错误之后出现了和你们相同的错误
<img width="853" alt="截屏2024-12-15 10 07 42" src="https://github.com/user-attachments/assets/ccd3f24e-c157-4547-89e7-5abeabcc167a" />

**Comment by xli-li** [comment]
> > > 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
> > > sudo chown -R lms:lms /opt/apollo/neo/data/log/
> > > chown: cannot access '/opt/apollo/neo/data/log/': No such file or directory
> > > 这是怎么回事
> 
> 你好 请问解决了吗

你好，请问解决了吗

**Comment by 1091205886** [comment]
> > > > 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
> > > > sudo chown -R lms:lms /opt/apollo/neo/data/log/
> > > > chown: cannot access '/opt/apollo/neo/data/log/': No such file or directory
> > > > 这是怎么回事
> > 
> > 
> > 你好 请问解决了吗
> 
> 你好，请问解决了吗

已经解决了

**Comment by xli-li** [comment]
> > > > > 不要用sudo运行aem bootstrap start --plus，把/opt/apollo/neo/data/log/的拥有者变为自己的用户
> > > > > sudo chown -R lms:lms /opt/apollo/neo/data/log/
> > > > > chown: cannot access '/opt/apollo/neo/data/log/': No such file or directory
> > > > > 这是怎么回事
> > > 
> > > 
> > > 你好 请问解决了吗
> > 
> > 
> > 你好，请问解决了吗
> 
> 已经解决了

怎么解决的，可以加一下qq(1641626319)咨询一下吗
