### ISSUE TITLE
What is map engine, what does it do, and how it do it? 

### ISSUE THREAD

**Issue by Shadow-Haund** [ApolloAuto/apollo#15330]
Hi.
Sorry about this, probably, stupid question, but I couldn't find any documentation about map engine in this repo or any other resources other than this sentence: 
**Map engine**, which provides structured information regarding the road network.
from [this](https://mediatum.ub.tum.de/doc/1578933/cz9q0x5ejsf61nrc2f6bpbnoz.Paper_Template_FISITA2020.pdf) document. Probably I'm missing something that is right in front of my eyes, but still. I want to understand:
1) What is Map Engine?
2) How it works?
3) What it do in apollo?
Appreciate, if you describe it yourself or provide a link or few links with required information.

**Comment by daohu527** [comment]
## What is Map Engine?
The map engine provides a set of API interfaces through which you can obtain any information about the map, including some extended functions.

For example, get the lane the current car is in, get the traffic lights in front, and get the current traffic rules. 

## How it works?

In most cases, its implementation relies on computer graphics.

## Implementation of Apollo

Apollo's map api is in the following file
https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/hdmap.h

**Comment by Shadow-Haund** [comment]
Thank you for your help.
