### ISSUE TITLE
Questions about adding Scenario

### ISSUE THREAD

**Issue by chh0901** [ApolloAuto/apollo#15333]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (9.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

After I installed it through package management according to the tutorial, I wanted to add the scene (lanefollowscenario) and follow the scene related documentation:

##### 配置加载 LaneFollowScenario 插件
- 在`modules/planning/planning_component/conf/planning_config.pb.txt`文件中增加`standard_planning_config`的配置，配置使用当前场景插件。
  ``` shell
  # modules/planning/planning_component/conf/planning_config.pb.txt

  standard_planning_config {
    planner_type: ......
    planner_public_road_config {
      ......
      scenario {
        name: "LANE_FOLLOW"
        type: "LanefollowScenario"
      }
      ......
    }
  }


When I follow the above steps to add some code to planning_config.pb.txt, the planning module in dreamview cannot be started, and after running bag, an error is displayed:

E0312 20:04:22.025444 12098 file.cc:84] [mainboard]Failed to parse file /apollo/modules/planning/planning_component/conf/planning_config.pb.txt as text proto.
E0312 20:04:22.025497 12098 file.cc:106] [mainboard]Failed to parse file /apollo/modules/planning/planning_component/conf/planning_config.pb.txt as binary proto.
F0312 20:04:22.025518 12098 planning_component.cc:49] Check failed: ComponentBase::GetProtoConfig(&config_) [planning]failed to load planning config file /apollo/modules/planning/planning_component/conf/planning_config.pb.txt


As long as I don't add part of the code in the tutorial, the planning module can run. Is it because I am missing the relevant package installation or there is a problem in the tutorial.




### Supporting materials (screenshots, command lines, code/script snippets):
![2024-03-12 21-12-27 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/99582868/f57fd4f9-3790-4ea3-accc-0d955a90833b)

**Comment by leizi111** [comment]
大佬你好，我按照官方文档添加planning场景的时候也遇到了同样的问题，请问大佬你是如何解决的？

**Comment by chh0901** [comment]
现在Apollo9.0更新了，不用自己添加这个场景，在planning_component的conf文件中已经写好了stand_planning_config，自己手动添加会导致于proto文件声明不一致。不用管这个，正常使用就好

**Comment by leizi111** [comment]
好的，谢谢大佬
