### ISSUE TITLE
buildtool编译问题

### ISSUE THREAD

**Issue by lh9171338** [ApolloAuto/apollo#15345]
### System information

- **Linux Ubuntu 18.04**:
- **Apollo installed from binary**:
- **Apollo version 9.0**:

进入Apollo容器环境执行buildtool build -p core报下面的错误：
[buildtool] 2024-03-19 19:03:13 ERROR Encounter ErrCode.FileIoErr
[buildtool] 2024-03-19 19:03:13 ERROR hint: please use offline mode after initialize metadata

**Comment by WildBeast114514** [comment]
出现这个提示说明网络不可用，使用buildtool第一次编译时需要构建各个软件包的依赖关系，需要在有网络的情况下运行
