### ISSUE TITLE
What visual parts of a roads in freamview stands for?

### ISSUE THREAD

**Issue by Shadow-Haund** [ApolloAuto/apollo#15359]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: 22.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 8.0

Hi.
Can you please clarify for me what is thin green, dotted white, solid white and solid yellow lines on Pic 1 and what yellow rectangle on Pic 2 mean? 

I can suggest, that thin green line is possible navigation route to follow along this lane, and dotted white line is lane boundaries with similar direction and yellow one is dividing line between different directions.
Appreciate any help.

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/ApolloAuto/apollo/assets/43119772/08e0ddfe-9d28-4224-870a-a3deb26b86b4)
Pic 1.
![image](https://github.com/ApolloAuto/apollo/assets/43119772/d0ba0a47-e873-4808-839f-343ab93a2430)
Pic 2.

**Comment by YuqiHuai** [comment]
Most of the definition of Apollo's HD Map can be found near https://github.com/ApolloAuto/apollo/blob/master/modules/common_msgs/map_msgs/map.proto

The green line should be the [central curve](https://github.com/ApolloAuto/apollo/blob/e373b206a0dc0360af826152132a61c85cab295c/modules/common_msgs/map_msgs/map_lane.proto#L48)

Boundary types can be found at https://github.com/ApolloAuto/apollo/blob/e373b206a0dc0360af826152132a61c85cab295c/modules/common_msgs/map_msgs/map_lane.proto#L8

I am not too sure about the yellow area in Pic 2 but I think they are clear area. https://github.com/ApolloAuto/apollo/blob/master/modules/common_msgs/map_msgs/map_clear_area.proto

**Comment by Shadow-Haund** [comment]
Thank you for your help.
