### ISSUE TITLE
Apollo仿真平台可订阅的topic

### ISSUE THREAD

**Issue by JKTesla** [ApolloAuto/apollo#1536]
想尝试在Apollo在线仿真平台测试规划程序，我查看了《Apollo仿真平台开发者接口标准》文档，所列开发者可订阅topic不包含**车道信息：诸如车道X,Y坐标、宽度、限速、航向、曲率、坡度、道路属性**等。

导致针对结构化道路开发的规划程序不方便在平台做测试，请问有什么解决方案吗？^o^

**Comment by yiakwy** [comment]
As far as I am concerned, you are trying to commit your own planner module to Online Stimulation Engine trough baiduCloud. As indicated by https://github.com/ApolloAuto/apollo/blob/master/modules/planning/conf/adapter.conf,
the planner should digest info from Location, RoutineResponse(astar route segments), traffic light, prediction(optional) for fine tuned TRAJECTORY.

You might want to check out Perception (end2end learning), Prediction. Am I right?

**Comment by JKTesla** [comment]
As you say,I want to use Online Stimulation Engine trough baiduCloud[http://apollo.auto/platform/simulation_cn.html](url)

![2017-12-03 20-15-52](https://user-images.githubusercontent.com/29981476/33525268-15547a5c-d867-11e7-8ce2-ca883dfabaac.png)

I need refer to information **Including but not limited** to what you say.Maybe,I ignore somethings important in Apollo repository.Thanks brother.
