### ISSUE TITLE
Build Error: in lat_controller_test.cc

### ISSUE THREAD

**Issue by 2460707925** [ApolloAuto/apollo#15375]
**Describe the bug**
build error in lat_controller_test.cc

**To Reproduce**
1. Go to './apollo.sh build'
2. See error
(15:38:30) ERROR: /apollo/modules/control/controllers/lat_based_lqr_controller/BUILD:39:15: Compiling modules/control/controllers/lat_based_lqr_controller/lat_controller_test.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 163 arguments skipped)
modules/control/controllers/lat_based_lqr_controller/lat_controller_test.cc: In member function 'void apollo::control::LatControllerTest::ComputeLateralErrors(double, double, double, double, double, double, const apollo::control::TrajectoryAnalyzer&, apollo::control::SimpleLateralDebug*)':
modules/control/controllers/lat_based_lqr_controller/lat_controller_test.cc:54:77: error: no matching function for call to 'apollo::control::LatControllerTest::ComputeLateralErrors(const double&, const double&, const double&, const double&, const double&, const double&, const apollo::control::TrajectoryAnalyzer&, apollo::control::SimpleLateralDebug*&)'
                                         linear_a, trajectory_analyzer, debug);

![2024-04-15 23-48-45 的屏幕截图](https://github.com/ApolloAuto/apollo/assets/51702343/a3941431-ec89-402a-b735-8625fefb8e5c)

**Comment by HandsomeAIccx** [comment]
I also met this error.The error is from v9.0.0-rc-r10. But you can change the tags to v9.0.0.
![image](https://github.com/ApolloAuto/apollo/assets/25932765/789ad6d0-f8bd-417a-a682-244b63ceab50)

**Comment by WildBeast114514** [comment]
latest commit have fixed this issue: https://github.com/ApolloAuto/apollo/commit/22cb4d8f98ebef1d73be4b1b614e8153fb41f03f
