### ISSUE TITLE
ERROR: /apollo/modules/audio/proto/BUILD:7:14: Generating Descriptor Set proto_library //modules/audio/proto:_audio_conf_proto failed: (Illegal instruction): protoc failed: error executing command

### ISSUE THREAD

**Issue by ZhanghaoLee** [ApolloAuto/apollo#15382]
![image](https://github.com/ApolloAuto/apollo/assets/150681705/d468b715-31d4-4d90-b3dc-9737ddaf2212)
How to solve this problem when entering the build command

OS: Ubuntu 20.04 in VirtualBox
Apollo: v9.0

**Comment by cherishTMYY** [comment]
I have also encountered this problem. Have you resolved it on your end?

**Comment by ZhanghaoLee** [comment]
> I have also encountered this problem. Have you resolved it on your end?

I just install a Linux OS with Ubuntu 20.04 and solve the problem. There may be something wrong with VirtureBox.
