### ISSUE TITLE
Are are any papers tell us the main idea or some details about apollo?

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#154]
We can see apollo is a very good software platform,There are some algorithms used，Like LQR-based Lateral Controller, etc.When I see the code,I can see a lot a matrix, makes me a little confused.If there are some papers are related,could anyone list them?

**Comment by Capri2014** [comment]
@gengqx , this document https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_tune_control_parameters.md
can give you some basic idea about LQR-based controller. if you want to dive into the math details behind it, you can refer to "Vehicle dynamics and control." Rajamani, Rajesh. Springer Science & Business Media, 2011."  Thanks.

**Comment by startcode** [comment]
@Capri2014 Can you also add the paper you mentioned in the source code? It will be easier to find for the readers.
Thanks

**Comment by gengqx** [comment]
@Capri2014 I saw that document writes that In a PID control ,most of the time,set kd = 0,and did nothing about the derivative.Is this code really used in the car,or just give us a software platform to add our own control algorithm.

**Comment by Capri2014** [comment]
@gengqx Yes, this is the actual control algorithm used in the car, same code for the trajectory following demo on 07/05 (with only minor calibration changes to compensate for vehicle differences for those three demo cars used that day). It should give you pretty decent speed/station tracking accuracy and lateral tracking for relative low speed ( < 30 kmh ). thought at the start stage, we sacrificed the tacking accuracy a bit in exchange for smoother start.
