### ISSUE TITLE
Apollo9.0编译报错

### ISSUE THREAD

**Issue by xjllhy** [ApolloAuto/apollo#15405]
**Describe the bug**
Apollo9.0在arm下编译报错.

**To Reproduce**
1. git clone https://github.com/ApolloAuto/apollo.git
2. cd apollo
git checkout master
3. bash docker/scripts/dev_start.sh
4. bash docker/scripts/dev_into.sh
5. ./apollo.sh build_opt_gpu
6. 报错没有找到bazel，部署bazel4.2.2后再次执行./apollo.sh build_opt_gpu
7. 报错Error: no native function or rule 'subpackages'

**Expected behavior**
期望编译成功通过.

**Screenshots**
![21716007128_ pic_hd](https://github.com/ApolloAuto/apollo/assets/40352794/3820bb48-2715-464e-85de-14853a6ec082)

**Desktop :**
 - Jetson AGX Orin 
 - Ubuntu20.04

**Comment by xjllhy** [comment]
Bazel use version 7.1.2 is ok. 
ps:build bazel 7.1.2 need jdk11+.

But build still error.

<img width="803" alt="image" src="https://github.com/ApolloAuto/apollo/assets/40352794/aa5c65f7-d56f-47bd-bf03-c8c102a68c9d">

**Comment by xjllhy** [comment]
Bazel version 5.4.0 is ok.
查了一下，貌似bazel6.0以上对platforms做了修改，而之前用的4.2.2又没有native.subpackages。

**Comment by Ariel-0228** [comment]
我在Orin上使用jetPack5.1.2的环境编译Apollo9.0.0  解决bazel的问题后，报TesorrtVersion这个变量找不到的错误，不知你们的Orin环境是怎么配置的 能不能分享一下

**Comment by Ariel-0228** [comment]
> Bazel version 5.4.0 is ok. 查了一下，貌似bazel6.0以上对platforms做了修改，而之前用的4.2.2又没有native.subpackages。 所以，为啥不能把这东西集成进去呢。
我在Orin上使用jetPack5.1.2的环境编译Apollo9.0.0 解决bazel的问题后，报TesorrtVersion这个变量找不到的错误，不知你们的Orin环境是怎么配置的 能不能分享一下
