### ISSUE TITLE
Failed to load default routing. Please make sure the file exists at /apollo/modules/map/data/demo_default_cycle_routing.txt

### ISSUE THREAD

**Issue by fengmao31** [ApolloAuto/apollo#15423]
Failed to load default routing. Please make sure the file exists at /apollo/modules/map/data/demo_default_cycle_routing.txt
![image](https://github.com/ApolloAuto/apollo/assets/19343842/a4b69f7d-bb20-4ef7-ad07-7e6dc6828ad1)

**Comment by YuqiHuai** [comment]
I did not encounter this error message when I launched Dreamview. I noticed once you use `Route Editing` (4th option on the left) and use `Add Default Routing` (5th option on the top), then a file named `demo_default_cycle_routing.txt` would appear in `modules/map/data`. Filename is defined here, I am not sure why they choose `_` over `/` when concatenating ... 

https://github.com/ApolloAuto/apollo/blob/03e6dddcc065355281af2e7c4eb27fa8db4d919f/modules/common/configs/config_gflags.cc#L34-L36

https://github.com/ApolloAuto/apollo/blob/03e6dddcc065355281af2e7c4eb27fa8db4d919f/modules/map/hdmap/hdmap_util.h#L64-L70

I manually created a file named `demo_default_cycle_routing.txt` with the following content

```
landmark {
  name: "default"
  waypoint {
    pose {
      x: 586392.840030000
      y: 4140673.012320000
    }
  }
  waypoint {
    pose {
      x: 586365.33
      y: 4140777.35
    }
  }
}
```
and now I can see this "default routing" when clicking the bottom left

![image](https://github.com/ApolloAuto/apollo/assets/34195403/52749629-10df-4df0-9bb8-76a7e0b93519)

Also looks like you would create one default routing for each map you want to use.

**Comment by fengmao31** [comment]
Let's make a conclusion.
IF you lack some map, please delete the container.
IF you failed to load default routing, manually create the file or create default routing file in route editing. It is 5th option on the top.
IF you can see nothing in module controller，please delete the container and reclone apollo repository, and rebuild the project. The last two will happen togther. I don't know whether module controller problem is caused by missing default route file.

**Comment by fengmao31** [comment]
![image](https://github.com/ApolloAuto/apollo/assets/19343842/12fecfed-7ff9-4e4c-80b3-5c22da9acc37)
