### ISSUE TITLE
apollo map shift

### ISSUE THREAD

**Issue by 1012327963** [ApolloAuto/apollo#15420]
![image](https://github.com/ApolloAuto/apollo/assets/62838381/59819333-58b3-450d-8e29-438985332f64)

您好，我通过shift扩了左侧车道，但是在终点和起点相连的情况下，会出现这样的情况，但是原来的车道确不会，这是为什么呢

**Comment by daohu527** [comment]
We do not currently support extending lanes in this way. This year we developed tools for collecting and mapping, ref [link](https://apollo.baidu.com/community/company-solution)

**Comment by daohu527** [comment]
Looks like the problem has been solved! closed.
