### ISSUE TITLE
使用apollo官方脚本安装docker时报错curl download.docker.com/linux/ubntu/gpg 链接超时

### ISSUE THREAD

**Issue by wsy957** [ApolloAuto/apollo#15430]
使用脚本安装docker时报错，尝试使用了国内的源也无法解决，看上去是curl时访问不到这个download.docker.com/linux/ubntu/gpg链接；
ubuntu版本：22.04

![eb746f6805501bf68a453d03696888f](https://github.com/ApolloAuto/apollo/assets/99071793/f3b27c5f-1aa1-4f10-a4e2-27fdbc8e254c)

**Comment by 1012327963** [comment]
国内的源不能下载了，具体问下百度怎么解决 
![db1b70c8208a005fc6576951f241fdf](https://github.com/ApolloAuto/apollo/assets/62838381/6ca29a45-c4f7-45db-bd2c-017d4724fda2)

**Comment by wsy957** [comment]
> 国内的源不能下载了，具体问下百度怎么解决 ![db1b70c8208a005fc6576951f241fdf](https://private-user-images.githubusercontent.com/62838381/338404615-6ca29a45-c4f7-45db-bd2c-017d4724fda2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTQ5NTksIm5iZiI6MTcxODE1NDY1OSwicGF0aCI6Ii82MjgzODM4MS8zMzg0MDQ2MTUtNmNhMjlhNDUtYzRmNy00NWRiLWJkMmMtMDE3ZDQ3MjRmZGEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYWMzOTc1NWFhZWI3OWFmYTQzNmI4YTA2ZjlmZDdiODE3Y2VlNTNlZTZmYzAxMTYyZjY5NDE4NmFhNDdiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dVVzaXMPvBN6KooDzNzNxPgyLuTsEWyq9CnVGqmpF_A)

好的，感谢
