### ISSUE TITLE
Could not open dreamview

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#1543]
I download the latest apollo,and i could not open dreamview,here is what I do
```
bash scripts/bootstrap.sh
tail /data/log/dreamview.out
```
and then I got
```
E1204 14:45:12.613981  8238 hdmap_util.cc:36] No existing file found in modules/map/data/sunnyvale_loop/base_map.bin|base_map.xml|base_map.txt. Fallback to first candidate as default result.
E1204 14:45:12.614317  8238 file.h:139] Failed to open file modules/map/data/sunnyvale_loop/base_map.bin in binary mode.
E1204 14:45:12.614334  8238 file.h:96] Failed to open file modules/map/data/sunnyvale_loop/base_map.bin in text mode.
E1204 14:45:12.614341  8238 hdmap_util.cc:62] Failed to load HDMap modules/map/data/sunnyvale_loop/base_map.bin
E1204 14:45:12.614367  8238 hdmap_util.cc:36] No existing file found in modules/map/data/sunnyvale_loop/sim_map.bin|sim_map.txt. Fallback to first candidate as default result.
E1204 14:45:12.614403  8238 file.h:139] Failed to open file modules/map/data/sunnyvale_loop/sim_map.bin in binary mode.
E1204 14:45:12.614419  8238 file.h:96] Failed to open file modules/map/data/sunnyvale_loop/sim_map.bin in text mode.
E1204 14:45:12.614425  8238 hdmap_util.cc:62] Failed to load HDMap modules/map/data/sunnyvale_loop/sim_map.bin
```

**Comment by xiaoxq** [comment]
Did you run it within docker?

**Comment by gengqx** [comment]
Yes @xiaoxq

**Comment by gengqx** [comment]
I could open it use an older version,when the hmi.sh are still usefull,after it is update to bootstrap.sh,I could never open it.

**Comment by xiaoxq** [comment]
Can you see the map data at "/apoll0/modules/map/data/sunnyvale_loop/"?

**Comment by gengqx** [comment]
No,as you can see in the master of apollo
```
https://github.com/ApolloAuto/apollo/tree/master/modules/map/data
```
only a demo data with txt file.

**Comment by xiaoxq** [comment]
The sunnyvale map is in docker image only, because it's too large to host in github repo.
So you can try starting a new container. Hopefully the data will appear.

**Comment by gengqx** [comment]
The docker history is just like this:
```
dev-x86_64-20171103_2113
dev-x86_64-20171103_2113-ci
dev-x86_64-20171114_1011
dev-x86_64-20171114_1011-ci
dev-x86_64-20171115_1105
dev-x86_64-20171115_1105-ci
dev-x86_64-20171115_2103
dev-x86_64-20171115_2103-ci
dev-x86_64-20171120_1254
dev-x86_64-20171120_1254-ci
dev-x86_64-20171122_1537
dev-x86_64-20171122_1537-ci
dev-x86_64-20171129_1427
dev-x86_64-20171129_1427-ci
```
I have run the newest docker image.Aparrently,There is no hope.
Accully,I have solved this problem,By just change the default map.But I realy hope you could release the data.

**Comment by ycool** [comment]
I tried dev-x86_64-20171129_1427 and dev-x86_64-20171206_1627. Both of them have sunnyvale_loop map data at modules/map/data/sunnyvale_loop/. If you can not find the map, can you check if your env has /home/tmp/modules_data/map/data/sunnyvale_loop/ ? docker start script will copy this map data into modules/map/data/. 

Thanks.

**Comment by Martin20** [comment]
I have the same problem. Have you been able to solve it?

**Comment by baijun-jiang** [comment]
I also have same problem.

**Comment by Martin20** [comment]
Even its developers do not know how to solve it. :)

**Comment by baijun-jiang** [comment]
upon debugging dreamview, I found out that the test data file structure doesn't match with those dreamview test cases. I'll create a new issue, hopefully they can realize that dreamview cannot be bootstrapped on their MASTER BRANCH : (
