### ISSUE TITLE
fatal error: vanjee_driver/api/lidar_driver.hpp: No such file or directory

### ISSUE THREAD

**Issue by xinxindream** [ApolloAuto/apollo#15444]
### System information
- **OS Platform and Distribution Linux Ubuntu 22.04**:
- **Apollo installed from source**:
- **Apollo version 9.0**:

### Supporting materials (screenshots, command lines, code/script snippets):
- bash apollo.sh build meets an error
```
ERROR: /apollo/modules/drivers/lidar/vanjeelidar/BUILD:8:17: Compiling modules/drivers/lidar/vanjeelidar/src/vanjeelidar_component.cpp failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 116 arguments skipped)
In file included from modules/drivers/lidar/vanjeelidar/src/vanjeelidar_component.cpp:18:0:
./modules/drivers/lidar/vanjeelidar/src/vanjeelidar_component.h:20:10: fatal error: vanjee_driver/api/lidar_driver.hpp: No such file or directory
 #include <vanjee_driver/api/lidar_driver.hpp>
```

**Comment by Franncys** [comment]
I'm having the same problem, what was the solution ?

**Comment by daohu527** [comment]
@Franncys You should update the new container because the lidar dependencies will be installed in the container.

**Comment by Franncys** [comment]
With the new container I can no longer compile with an rtx 40 series gpu, did I do something wrong or is it not possible ?
