### ISSUE TITLE
您好， 请问当前搭载apollo的无人车上需要的高精地图能描述多大范围内的地况？hd map是定期更新的么，在网络好情况下是多长时间更新呢？以及比如北京市的高清地图有多大，几十M，还是几十G，或者是T级别？

### ISSUE THREAD

**Issue by judyfish** [ApolloAuto/apollo#1544]

**Comment by msbeta** [comment]
apollo搭载的高精地图的地理范围依赖实际运行场景而定，已经开放的apollo模块中HDMap尚不具备在线OTA功能

**Comment by gengqx** [comment]
根据百度深圳高清地图采集部门的一个负责人的陈述，其大小要根据不同的场景而定，城市路况大概50kb～100kb 每公里

**Comment by msbeta** [comment]
Hi @judyfish , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open an new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
