### ISSUE TITLE
Apollo 与显卡问题

### ISSUE THREAD

**Issue by gitLongjie** [ApolloAuto/apollo#1545]
我的显卡是gtx1050ti 安装显卡驱动和Apollo内核出现冲突，导致在系统登陆界面无限循环进入不了系统，请问一下，有解决方案么？

**Comment by JKTesla** [comment]
这应该是显卡驱动和本机硬件的冲突吧……
建议上网找“系统登陆界面无限循环”的帖子，看能否解决？如果不是在英伟达组件上跑的话，可以考虑不装Apollo内核。

**Comment by gitLongjie** [comment]
您说的英伟达组件是英伟达的计算板子？？

**Comment by JKTesla** [comment]
是的,比如TX2开发套件。因为我之前在自己电脑上（暗影精灵3）也装过Apollo内核，但它与我Linux内核会冲突（当然也可能是我操作有什么问题），所以最后放弃装Apollo内核了。

但TX2板子不一样，Apollo程序有支持其arm内核的设计[Apollo build](https://github.com/ApolloAuto/apollo/blob/35e8b9e5567ba1e4a91aa798176408b534c60f78/tools/platforms/BUILD) （AArch64是ARMv8 架构的一种执行状态）

且板子只用来跑程序，不像PC还要处理其他任务。如果运行Apollo内核出了问题，板子牵扯的问题较少，解决成本也降低很多。

**Comment by gitLongjie** [comment]
受教了，谢谢，我在apollo build过程中，出现了很多no action runing 这个是代表的什么，是我里面的模块没有运行么？？

**Comment by JKTesla** [comment]
朋友你提问前，我建议**先搜历史解答**，你遇到的问题很可能别人已经遇到甚至已经被解决了。

![2017-12-05 15-32-51](https://user-images.githubusercontent.com/29981476/33595136-cc0ddcf0-d9d1-11e7-9d51-eeeef3ad916c.png)

**Comment by gitLongjie** [comment]
好的 再次感谢
