### ISSUE TITLE
question about speed_bounds_decider

### ISSUE THREAD

**Issue by dajiba6** [ApolloAuto/apollo#15465]
why the speed_bounds_decider is used twice in lane follow secnario?
What is the significance of adding a SPEED_BOUNDS_FINAL_DECIDER?

**Comment by ycraurora** [comment]
The SPEED_BOUNDS_PRIORI_DECIDER initially generates approximate speed boundaries for DP process, which serve to create a 'reference line' for QP. Conversely, the SPEED_BOUNDS_FINAL_DECIDER produces more precise speed boundaries for the QP process, culminating in the final speed profile. The primary distinction between the two deciders lies in their level of accuracy. In Apollo 8.0, you can compare the default configurations for both deciders within the modules/planning/conf/planning/config.pb.txt file. However, in Apollo 9.0, the configurations appear to be consolidated, leading to ambiguity as there seems to be no discernible difference between the two deciders.

**Comment by dajiba6** [comment]
thank you, my friend.

> The SPEED_BOUNDS_PRIORI_DECIDER initially generates approximate speed boundaries for DP process, which serve to create a 'reference line' for QP. Conversely, the SPEED_BOUNDS_FINAL_DECIDER produces more precise speed boundaries for the QP process, culminating in the final speed profile. The primary distinction between the two deciders lies in their level of accuracy. In Apollo 8.0, you can compare the default configurations for both deciders within the modules/planning/conf/planning/config.pb.txt file. However, in Apollo 9.0, the configurations appear to be consolidated, leading to ambiguity as there seems to be no discernible difference between the two deciders.
