### ISSUE TITLE
Ubuntu 16.04 LTS for Apollo?

### ISSUE THREAD

**Issue by Prasan03** [ApolloAuto/apollo#1546]
We are planning to install Apollo on a PC which already has Ubuntu 16.04 LTS and ROS Kinetic Kame.
And I can see in the docs that recommended Ubuntu version to use is Ubuntu 14.04.3.

But, can I still use Ubuntu 16.04 LTS?
And is it ok to install on top of already installed ROS?

**Comment by JKTesla** [comment]
Of course you can.I just run apollo in the Ubuntu16.04.
Ubuntu 14.04.3 just was recommended not unique.Maybe Ubuntu16.04 will be added to context in the future.

**Comment by Prasan03** [comment]
Thanks! That helped.

**Comment by Iqbalparvi** [comment]
i need help to build apollo envoroment ist time in my pc as i installed ubuntu 16.04 on it and i dont know any other things and how these  all are  install through terminal ..iqbal.parvi@yahoo.com ,pleses ,mail me all the procedure
