### ISSUE TITLE
Headlight and turn signal 

### ISSUE THREAD

**Issue by joon5283** [ApolloAuto/apollo#15476]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**: Ubuntu 22.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.0 and 6.0
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Hello, everyone.

First, thank you so much for providing such great software.
I am playing with the software to understand how the autonomous vehicle reacts using LGSVL.
To resolve the alignment problem of the San Francisco map, I utilized the 'Sanfrancisco_correct' map for the simulation.
And I have two problems right here.
1) Simulation is not aligned with the time (12:00 PM is dark in the simulation).
2) Even if the scenario is dark, the headlight of a vehicle does not turn on. Also, the turn signal does not turn on when the vehicle tries to turn left or right. 

Could you suggest how to resolve this problem? Any suggestions will be appreciated. Thank you.
I hope you have a wonderful day.

**Comment by daohu527** [comment]
@joon5283 This is related to the vehicle model of the simulator. Since lgsvl is no longer maintained, I suggest you use other simulators, such as carla.

We don't have the extra energy to deal with the lgsvl problem now.
