### ISSUE TITLE
Questions regarding to `imu_coord_rfu` flag

### ISSUE THREAD

**Issue by boyang9602** [ApolloAuto/apollo#15481]
Hi,

This comment does not look correct. It is not intuitive that `--imu_coord_rfu=true` means `flu` is used but `false` for `rfu` is used. Could someone confirm this?  

https://github.com/ApolloAuto/apollo/blob/6edbb1f8fcee5ad2e75109b89de799236971548e/modules/localization/conf/localization.conf#L142-L145

The corresponding code also indicates that `--imu_coord_rfu=true` means `rfu` is used:
https://github.com/ApolloAuto/apollo/blob/6edbb1f8fcee5ad2e75109b89de799236971548e/modules/localization/msf/msf_localization.cc#L217-L221

**Comment by daohu527** [comment]
below is right
```
imu coordinate, true->Rfu, false->Flu
```

we can always believe the code.
