### ISSUE TITLE
The error "class apollo::perception::base::Image8U has no member named 'count'" was encountered during compilation.

### ISSUE THREAD

**Issue by windzu** [ApolloAuto/apollo#15498]
### System information

- **OS Platform and Distribution**: Ubuntu 20.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 9.0
- **Output of `apollo.sh config` if on `master` branch**: release 9.0

### Steps to reproduce the issue:
- error position : perception/common/camera/common/data_provider.cc:133 memcpy(rgb_->mutable_cpu_data(), data, rgb_->count() * sizeof(data[0])); meet this build problem
- i have check perception/common/base/image_8u.h code , have not found class Image8U have `count()` function

**Comment by daohu527** [comment]
Yes, seems cpu mode have this error, I should be

```
rgb_->blob()->count()
```
