### ISSUE TITLE
[aem] How to use aem start while mapping port

### ISSUE THREAD

**Issue by Tumb1eweed** [ApolloAuto/apollo#15496]
Apollo version：9.0
My workspace is WSL2, and I run application-core by using aem, so I need to map port 8888 to 8888 in order to get dreamviewer to work, I don't know how to achieve that using aem...

**Comment by daohu527** [comment]
Could pls use below method and have a try



### Directly Access WSL's IP Address

1. **Get WSL's IP Address**: You can obtain the IP address of WSL by running the following command in WSL:
   ```bash
   ip addr | grep eth0
   ```
   Or more specifically:
   ```bash
   ip addr show eth0 | grep inet
   ```
   You will get an output like `inet 172.24.187.2/20`, where `172.24.187.2` is the IP address of WSL.

2. **Access in Windows**: Open a web browser or any network tool on Windows and access `http://<WSL_IP>:8888`, for example, `http://172.24.187.2:8888`.
