### ISSUE TITLE
D-Kit Support in Singapore

### ISSUE THREAD

**Issue by Yanxin97** [ApolloAuto/apollo#15494]
### System information

- **OS Platform and Distribution Linux Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 6.0-EDU **:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **I can not ping the GNSS sensor IP: 192.168.0.123, however the device info is ok. Besides, does this kind of sensor supports RTK service in Singapore?**:

### Supporting materials (screenshots, command lines, code/script snippets):
ttyS0 Reading:
![Screenshot 2024-08-06 234106](https://github.com/user-attachments/assets/e9f898f9-2102-4935-b61c-cb3bbe5d889c)

Ping Result:
![Screenshot 2024-08-06 233950](https://github.com/user-attachments/assets/4e4d2427-8285-4db7-bc89-8289f5f96d97)

**Comment by daohu527** [comment]
Yes, Qianxu supports Singapore, here are the supported regions https://www.qxwz.com/map-cover

The D-kit gnss sensor already support RTK.

**Comment by Yanxin97** [comment]
Thanks for your reply. And any sugguestions on pinging GNSS module?  In the screenshots, the host pc can not access it.

**Comment by Yanxin97** [comment]
Thanks, now it works. And can I test IMU only using the GNSS installed on D-Kit?

**Comment by daohu527** [comment]
what do you mean by test IMU? just use IMU message for some develop or test? 

By the way could send me a email daohu527@gmail.com We would like to know about your dkit and autonomous driving situation
