### ISSUE TITLE
How can I use Python code or terminal command to reset backend data just like in the DreamView?

### ISSUE THREAD

**Issue by AOOOOOA** [ApolloAuto/apollo#15497]
Hi, 
Is there any way to use code or terminal command to reset the backend data just like the button does in the DreamView? Thanks!

**Comment by daohu527** [comment]
Currently, DreamView adopts front-end and back-end architecture and is submitted through **Websocket**.

## interface
There is no standard interface yet, but if necessary we may consider adding one. The following code shows the websocket registering the "HMIAction" message handler

https://github.com/ApolloAuto/apollo/blob/ba32187d4f1879fb0a9b941ca501cd5717c680df/modules/dreamview/backend/hmi/hmi.cc#L81-L84

## another solution

Kill all processes started with `cyber_launch`

```shell
ps -eLo pid,cmd | grep cyber_launch | awk '{print $1}' | xargs ps -T | awk '$1 != "PID" {print $2}' | xargs sudo kill -9

```

**Comment by YuqiHuai** [comment]
You can check this out as well.
https://github.com/lgsvl/PythonAPI/blob/master/lgsvl/dreamview/dreamview.py

**Comment by daohu527** [comment]
The lgsvl mock the communication to Apollo, it looks like it works.

**Comment by YuqiHuai** [comment]
> The lgsvl mock the communication to Apollo, it looks like it works.

I think this implements works for Apollo 7.0 but not for 8.0 because the web socket messages changed slightly. Anyone can use the developer tool from the browser to extract the appropriate messages to be sent to the backend.
