### ISSUE TITLE
IMU reference system

### ISSUE THREAD

**Issue by boyang9602** [ApolloAuto/apollo#15500]
Hi,

For IMU, it specifies that the directions of the measurements are forward/left/up, is it referenced to the earth or the device? For example, does "forward" point to the north or just forward of the device?

More specifically, I want to clarify the correspondence with KITTI's data. KITTI has the measurements to xyz (referenced to the earth) and flu (referenced to the vehicle/device). I wonder if Apollo's flu corresponds to KITTI's flu. 

Thanks! 

```
syntax = "proto2";

package apollo.drivers.gnss;

import "modules/common_msgs/basic_msgs/geometry.proto";
import "modules/common_msgs/basic_msgs/header.proto";

// Measurements from an inertial measurement unit (IMU). The solution is with
// respect to the IMU by default.
message Imu {
  optional apollo.common.Header header = 1;

  // The time of IMU measurement, seconds since the GPS epoch (Jan 6, 1980).
  optional double measurement_time = 2;  // In seconds.

  // When measurement_span is non-zero, the gyroscope and accelerometer
  // measurements are averaged for the period from
  // (measurement_time - measurement_span) to measurement_time. Usually,
  //      measurement_span = 1 / sampling_frequency.
  //
  // When measurement_span is 0, angular_velocity and linear_acceleration are
  // instantaneous at measurement_time.
  optional float measurement_span = 3 [default = 0.0];  // In seconds.

  // Forward/left/up in meters per square second.
  optional apollo.common.Point3D linear_acceleration = 4;

  // Around forward/left/up axes in radians per second.
  optional apollo.common.Point3D angular_velocity = 5;
}
```

**Comment by daohu527** [comment]
The Apollo vehicle_coordinate_system, more details can find here [link](https://apollo-1000-questions.readthedocs.io/zh/latest/answers/transform/001.html)

![image](https://github.com/user-attachments/assets/ac47c7d5-f283-491f-8097-b73d1a566fe4)
