### ISSUE TITLE
bash dev_start.sh error

### ISSUE THREAD

**Issue by kawasaki94year** [ApolloAuto/apollo#15517]
hello everyone, I run the **dev_start.sh** file on **ubuntu 22.04 LTS** use this code `bash dev_start.sh`,It shows that `docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "true": executable file not found in $PATH: unknown.`my docker version is` Docker version 27.2.0, build 3ab4256`,so how can I resolve this problem?

**Comment by daohu527** [comment]
This may be due to a variety of reasons, such as Docker not having permissions, graphics card driver version, etc.



# docker permissions
```
sudo usermod -aG docker $USER
```

# cuda version
```
nvidia-smi
```

**Comment by hinstru00** [comment]
ℹ solved the problem by giving docker permission

**Comment by yaobaishen** [comment]
I have gave docker permission but the issue still exist.
Mark the same issue here: https://github.com/ApolloAuto/apollo/issues/15045
