### ISSUE TITLE
Apollo9.0.0 can't launch module Control and Planning

### ISSUE THREAD

**Issue by MH798968733** [ApolloAuto/apollo#15543]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (9.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

![apollo](https://github.com/user-attachments/assets/27473c58-955c-4385-91b9-11e80f772b6c)
After I turned on the switch for a while, it reverted back to its original state，and there is no any log on terminal

**Comment by daohu527** [comment]
Please describe the information in detail, such as whether there is location information

**Comment by MH798968733** [comment]
Localization module has been turned on and there are msgs in channel /apollo/localization/pose
![localization](https://github.com/user-attachments/assets/3559d689-daa2-4b52-817d-f3ccceee6252)
![1111](https://github.com/user-attachments/assets/a8b3236f-93da-4c80-9cae-3340aa9b4497)



And here are the differences in files between v8.0(left) and v9.0(right), I found that there is no directory named launch and dag which is used to start module in past version, Is there a new way to start module?or this is the cause of the problem 
![control](https://github.com/user-attachments/assets/204dc496-5908-4d31-bd0b-73527d3faea6)
![planning](https://github.com/user-attachments/assets/0ae59a51-004e-48d8-810b-b135bc45e15f)

**Comment by YuqiHuai** [comment]
@MH798968733 If I remember correctly Apollo 9.0 does not have "Routing" launch button in Dreamview. The launch file for planning was indeed moved to a different place (module/planning/planning_component/launch).

**Comment by MH798968733** [comment]
> @MH798968733 If I remember correctly Apollo 9.0 does not have "Routing" launch button in Dreamview. The launch file for planning was indeed moved to a different place (module/planning/planning_component/launch).
Thanks! I used the conf file of hmi-modes in v 6.0 directly so the  path of dag is incorrect, it works after I correct the file path
