### ISSUE TITLE
有关cyber_recorder record 数据落盘的问题

### ISSUE THREAD

**Issue by MarioUncle-Wang** [ApolloAuto/apollo#15567]
您好：
  请问如果我使用cyber_recorder录制数据，是将数据落在docker环境中？但是由于设备自带存储空间有限，无法存储大量数据，那么如果我现在给设备外接一个移动硬盘，如何让数据直接落在外接移动硬盘中？

**Comment by daohu527** [comment]
Yes, records are stored in the container, but Docker supports mounting external storage, so we can use this method to save data to disk.

## method
1. Create directory in `apollo`

```shell
cd apollo
mkdir -p data/bag
```

2. Mount the external hard disk to local
```
# /dev/sdb1 is your external hard disk
sudo mount /dev/sdb1 data/bag
```

3. Run `cyber_recorder` and specify the save path
```
cyber_recorder record -a -o=data/bag
```
