### ISSUE TITLE
docker run error,Help!

### ISSUE THREAD

**Issue by luckdsfy** [ApolloAuto/apollo#156]
I use ubuntu 14.04 in vmware.
follow the quick start doc.
1  bash docker/scripts/install_docker.sh  .                this step run succ
 but run  “ docker ps “  fail.
as follow:
root@ubuntu:/opt/APOLLO/apollo-master/docker/scripts# docker ps
FATA[0000] Get http:///var/run/docker.sock/v1.18/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

why???

**Comment by luckdsfy** [comment]
maybe because i forget to set    APOLLO_HOME

**Comment by lubaogui** [comment]
maybe you forgot to startup docker service.

**Comment by wanglei828** [comment]
After you install the docker, please log out and then log in again.
