### ISSUE TITLE
apollo 10.0源码编译成功后，各模块都无法启动，提示找不到so, dreamview+中也无法正常启动

### ISSUE THREAD

**Issue by vilon888** [ApolloAuto/apollo#15608]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution**:Linux Ubuntu 22.04
- **Apollo installed from**:source
- **Apollo version **: 10.0 tag v10.0.0
- **Output of `apollo.sh config`  on tag  `v10.0.0` **:

[vilon888@in-dev-docker:/apollo_workspace]$ ./apollo.sh config         
[INFO] Apollo Environment Settings:
[INFO]     APOLLO_ROOT_DIR:   /apollo
[INFO]     APOLLO_CACHE_DIR:  /apollo/.cache
[INFO]     APOLLO_IN_DOCKER:  true
[INFO]     APOLLO_VERSION:    @non-git
[INFO]     DOCKER_IMG:        
[INFO]     APOLLO_ENV:        STAGE=dev USE_ESD_CAN=false
[INFO]     USE_GPU_HOST:      0
[INFO]     USE_GPU_TARGET:    1
[INFO]     GPU_PLATFORM:      NVIDIA
[INFO] Usage: /apollo_workspace/scripts/apollo_config.sh [Options]
[INFO] Options:
[INFO]     -i|--interactive      Run in interactive mode
[INFO]     -n|--noninteractive   Run in non-interactive mode
[INFO]     -h|--help             Show this message and exit

### Steps to reproduce the issue:
- bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
./apollo.sh build_gpu
cyber_launch start  modules/perception/launch/perception_all.launch

### Supporting materials (screenshots, command lines, code/script snippets):
E1211 11:19:34.523952 150450 module_controller.cc:81] [mainboard]no module library [modules/perception/camera_detection_multi_stage/libcamera_detection_multi_stage_component_camera.so] found!
E1211 11:19:34.523958 150450 module_controller.cc:69] [mainboard]Failed to load module: /apollo/modules/perception/camera_detection_multi_stage/dag/camera_detection_multi_stage_front.dag
E1211 11:19:34.523964 150450 mainboard.cc:90] [mainboard]module start error.
[cyber_launch_150449] ERROR Process [perception] has died [pid 150450, exit code 255, cmd mainboard -d modules/perception/camera_detection_multi_stage/dag/camera_detection_multi_stage_front.dag -d modules/perception/camera_location_estimation/dag/camera_location_estimation_front.dag -d modules/perception/camera_location_refinement/dag/camera_location_refinement_front.dag -d modules/perception/camera_tracking/dag/camera_tracking_front.dag -d modules/perception/camera_detection_multi_stage/dag/camera_detection_multi_stage_rear.dag -d modules/perception/camera_location_estimation/dag/camera_location_estimation_rear.dag -d modules/perception/camera_location_refinement/dag/camera_location_refinement_rear.dag -d modules/perception/camera_tracking/dag/camera_tracking_rear.dag -d modules/perception/pointcloud_preprocess/dag/pointcloud_preprocess.dag -d modules/perception/pointcloud_map_based_roi/dag/pointcloud_map_based_roi.dag -d modules/perception/pointcloud_ground_detection/dag/pointcloud_ground_detection.dag -d modules/perception/lidar_detection/dag/lidar_detection.dag -d modules/perception/lidar_detection_filter/dag/lidar_detection_filter.dag -d modules/perception/lidar_tracking/dag/lidar_tracking.dag -d modules/perception/radar_detection/dag/radar_detection_front.dag -d modules/perception/multi_sensor_fusion/dag/multi_sensor_fusion.dag -p perception -s CYBER_DEFAULT].

![1733887405799](https://github.com/user-attachments/assets/bc71185f-d6c5-4e3b-b477-2b7bbebdf7f1)

**Comment by hearto1314** [comment]
参考官网文档，更新aem到最新版本，清理之前的容器环境，然后aem start，进入容器后 buildtool build 再试试，至少dv应该能正常启动，再试其他模块。

**Comment by vilon888** [comment]
> 参考官网文档，更新aem到最新版本，清理之前的容器环境，然后aem start，进入容器后 buildtool build 再试试，至少dv应该能正常启动，再试其他模块。

hi @hearto1314 , 
感谢回复，按照你说的，我aem remove清楚apollo git下的缓存，bash docker/scripts/dev_into.sh重新进入docker后执行：

./apollo.sh build_gpu
成功编译后，运行，
cyber_launch start /apollo/modules/perception/launch/perception_camera_multi_stage.launch
可以正常启动，，

另一个窗口进入docker 执行, 
source cyber/setup.bash
bash scripts/bootstrap.sh start_plus

如图：
![Screenshot from 2024-12-15 11-00-18](https://github.com/user-attachments/assets/5ed5a44a-ed03-4d3e-9915-e69f50fd38ed)

这个界面无法通过界面启动Transform, 
docker 命令行中启动transform ：
cyber_launch start /apollo/modules/transform/launch/static_transform.launch

错误如下图，提示找不到modules/transform/libstatic_transform_component.so：
![Screenshot from 2024-12-15 11-02-46](https://github.com/user-attachments/assets/927d3412-21d7-414f-881c-191307ad3a0b)

请问这个是不是那个地方路径设置的有问题？
源码编译文档，我是参考https://github.com/ApolloAuto/apollo/blob/v10.0.0/docs/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97/%E6%BA%90%E7%A0%81%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F.md

**Comment by hearto1314** [comment]
可能是环境变量别修改了，exit退出容器再aem enter进入容器后试试，
如果还不行，buildtool reinstall transform 试试

**Comment by vilon888** [comment]
> 可能是环境变量别修改了，exit退出容器再aem enter进入容器后试试， 如果还不行，buildtool reinstall transform 试试

是环境变量被其它脚本修改了，

另一个窗口进入docker 执行,
source cyber/setup.bash
bash scripts/bootstrap.sh start_plus
“source cyber/setup.bash” 会改变环境变量，如果不执行这个脚本，monitor启动失败，

我现在是使用aem bootstrap start --plus , 就可以正常启动组件了

@hearto1314 谢谢了
