### ISSUE TITLE
lidar2gnss calibration

### ISSUE THREAD

**Issue by pedestrain123** [ApolloAuto/apollo#15603]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
您好，请问lidar2gnss外参标定的原理是什么？可以公开一下源码吗？

**Comment by hearto1314** [comment]
你好，工具类的不开放源码，使用遇到的问题可以随时反馈，谢谢！
