### ISSUE TITLE
How to Prevent Dreamview from Auto-loading Historical Routes during Apollo Relaunch?

### ISSUE THREAD

**Issue by AOOOOOA** [ApolloAuto/apollo#15609]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution Linux Ubuntu 18.04**:
- **Apollo installed from: source**:
- **Apollo version : 8.0**:
- **Output of `apollo.sh config` if on `master` branch**: master:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I am working with Apollo 8.0 and Carla 0.9.14 using the carla_apollo_bridge (https://github.com/guardstrikelab/carla_apollo_bridge). My task involves launching Apollo multiple times with identical starting points and destinations to ensure experimental consistency.

During the replay process, I encountered an issue. To maintain route consistency, I recorded and saved the data from both routing_request and routing_response topics, which I then replay in subsequent runs. However, I discovered that when relaunching the Apollo agent, Dreamview automatically sends a historical routing information that overwrites my saved route data. This automatic routing from Dreamview uses an incorrect historical route, different from my intended path.

Is there a way to disable this automatic routing functionality in Dreamview? This would allow me to maintain consistent routing across multiple experimental runs.

Below is the info I got when monitoring the topic /apollo/routing_request:

header {
  timestamp_sec: 1733889302.854115
  module_name: "routing_request"
  sequence_num: 0
}
waypoint {
  id: "road_6_lane_0_1"
  s: 0
  pose {
    x: 232.20021057128906
    y: 326.60372924804688
  }
}
waypoint {
  id: "road_8_lane_0_-1"
  s: 10.329359054565449
  pose {
    x: 396.34597778320312
    y: 308.20986938476562
  }
}

**header {
  timestamp_sec: 1730362508.4838064
  module_name: "dreamview"
  sequence_num: 52
}
waypoint {
  id: "road_1_lane_0_-1"
  s: 32.342216982273072
  pose {
    x: 293.288818359375
    y: 1.9600721597671509
  }
}
waypoint {
  id: "road_1_lane_0_1"
  s: 128.74917893116415
  pose {
    x: 296.82999897313073
    y: -0.044337310916503725
  }
}**

header {
  timestamp_sec: 1733889302.854115
  module_name: "routing_request"
  sequence_num: 0
}
waypoint {
  id: "road_6_lane_0_1"
  s: 0
  pose {
    x: 232.20021057128906
    y: 326.60372924804688
  }
}
waypoint {
  id: "road_8_lane_0_-1"
  s: 10.329359054565449
  pose {
    x: 396.34597778320312
    y: 308.20986938476562
  }
}

**Comment by simpleKang** [comment]
You can generate your desired routing results by setting up multiple waypoints instead of just a start and end point.

**Comment by AOOOOOA** [comment]
> You can generate your desired routing results by setting up multiple waypoints instead of just a start and end point.

I have solved it. Thanks!
