### ISSUE TITLE
Apollo-vision-Net 模型训练下载代码?

### ISSUE THREAD

**Issue by SSSS-q** [ApolloAuto/apollo#15601]
There is not link in this section?

下载代码

git clone xxx

**Comment by hearto1314** [comment]
文档过两天会更新，请先参考这个。

模型下载
\| 6f83169d067343658251f72e1dd17dbc \| http://apollo-perception.bj.bcebos.com/nuscenes_occ_records/6f83169d067343658251f72e1dd17dbc.record?authorization=bce-auth-v1%2FALTAKr8RyUUttStVHwGaOsvJyP%2F2024-12-02T08%3A12%3A56Z%2F-1%2Fhost%2F15500778f03ba45f19e6a7818b3af88952a739cbd53761f166d8bd542347821b \|
--
  | \| 2fc3753772e241f2ab2cd16a784cc680 \| https://apollo-perception.bj.bcebos.com/nuscenes_occ_records/2fc3753772e241f2ab2cd16a784cc680.record?authorization=bce-auth-v1/ALTAKg5yEiU4seODUEbcZVtvIv/2024-10-28T06%3A46%3A06Z/-1/host/c71f5b47abfe012a352d4ce4cd959f10579063ebcff5acecf965353f183bdb8f \| |   | \| 2fc3753772e241f2ab2cd16a784cc680 \| http://apollo-perception.bj.bcebos.com/nuscenes_occ_records/2fc3753772e241f2ab2cd16a784cc680.record?authorization=bce-auth-v1%2FALTAKr8RyUUttStVHwGaOsvJyP%2F2024-12-02T08%3A11%3A30Z%2F-1%2Fhost%2Fb7b99869a804ed08c7f6804d8b724e15aebc3e1c13fde45b18b61e459b1b7ae5 \|
  | \| bebf5f5b2a674631ab5c88fd1aa9e87a \| https://apollo-perception.bj.bcebos.com/nuscenes_occ_records/bebf5f5b2a674631ab5c88fd1aa9e87a.record?authorization=bce-auth-v1/ALTAKg5yEiU4seODUEbcZVtvIv/2024-10-28T06%3A46%3A28Z/-1/host/85f5300f9a26a7642ca6e1dc19a91634b90e9e271798a1e7d19dbae92c333543 \| |   | \| bebf5f5b2a674631ab5c88fd1aa9e87a \| http://apollo-perception.bj.bcebos.com/nuscenes_occ_records/bebf5f5b2a674631ab5c88fd1aa9e87a.record?authorization=bce-auth-v1%2FALTAKr8RyUUttStVHwGaOsvJyP%2F2024-12-02T08%3A13%3A18Z%2F-1%2Fhost%2F1c25a91e913f512b8f188dc6e54bd07ffcbb301e1be2d92a3cc7b686e1456d80 \|

代码库：
git clone https://github.com/ApolloAuto/Apollo-Vision-Net
git clone https://github.com/ApolloAuto/Apollo-Vision-Net-Deployment.git

**Comment by hearto1314** [comment]
官方文档已更新
