### ISSUE TITLE
Cant access Nuscenes record for vision object detection walkthrough

### ISSUE THREAD

**Issue by MesaMitch** [ApolloAuto/apollo#15602]
{"code":"SignatureDoesNotMatch","message":"The request signature we calculated does not match the signature you provided. Check your Secret Access Key and signing method. Consult the service documentation for details.","requestId":"a94a4abc-208b-4f40-aa22-6f6a8d71507f"}

**Comment by hearto1314** [comment]
ref： https://github.com/ApolloAuto/apollo/issues/15601#issuecomment-2522084339
