### ISSUE TITLE
apollo 10.0 3rd-fastdds-wrap

### ISSUE THREAD

**Issue by mr-d-self-driving** [ApolloAuto/apollo#15607]
在哪能找到这个源码？谢谢!
3rd-fastdds-wrap

**Comment by minhanghuang** [comment]
> 在哪能找到这个源码？谢谢! 3rd-fastdds-wrap

@mr-d-self-driving 同学, 有源码吗👋

**Comment by minhanghuang** [comment]
Ubuntu22.04有
![image](https://github.com/user-attachments/assets/c765b1b6-1108-4918-8e58-f7798d5d5650)
