### ISSUE TITLE
Apollo10 occupancy network's occ output is not forwarded to Planning

### ISSUE THREAD

**Issue by arnoldfychen** [ApolloAuto/apollo#15605]
Hello,
In Apollo10, GetOccResults() in modules/perception/camera_detection_occupancy/detector/bevformer/bevformer_obstacle_detector.cc only stores occ data into a .bin file, doesn't forward it down by frame and message like frame_ptr_->detected_objects, why?   
Will this code be completed in the coming days ?  
How can I forward occupancy data to Planning and use it  in Planning high efficiently?
Thanks.

P.S. 

bool BEVFORMERObstacleDetector::GetOccResults(CameraFrame *frame,
                                              const float *outputs_occupancy) {
  if (frame == nullptr) {
    return false;
  }
  occ_results_.clear();
  int valid_occ_point = 0;
  for (int voxel_index = 0; voxel_index < num_voxels_; voxel_index++) {
    float max_prob = 0.0;
    int class_pred = num_classes_occ_ + 1;
    for (int class_index = 0; class_index < num_classes_occ_; class_index++) {
      float class_prob =
          outputs_occupancy[voxel_index * num_classes_occ_ + class_index];
      if (class_prob > max_prob) {
        max_prob = class_prob;
        class_pred = class_index;
      }
    }
    if (max_prob >= occ_threshold_) {
      occ_results_.push_back(std::make_pair(voxel_index, class_pred));
      valid_occ_point += 1;
    }
  }
  AINFO << "number of valid occ voxels: " << valid_occ_point;

  if (access(model_param_.occ_save_path().c_str(), 0) == -1) {
    system(("mkdir " + model_param_.occ_save_path()).c_str());
  }
  std::string out_file = model_param_.occ_save_path() + '/' +
                          std::to_string(frame->timestamp) + ".bin";
  std::ofstream out_stream;
  out_stream.open(out_file);
  for (int i = 0; i < occ_results_.size(); i++) {
    out_stream << occ_results_.at(i).first << " " << occ_results_.at(i).second
                << " ";
  }
  out_stream.close();

  return true;
}

**Comment by Jonathans575** [comment]
Yes，the occupancy detection results only support offline visualization.

**Comment by Jonathans575** [comment]
There are several ways to use the results of occupancy detection, and you can choose by yourself:
1. The results of occupancy detection can be used through point cloud clustering into background obstacles.
2. The detection results of the occupancy can be sent to the planning network in an end-to-end manner.
An appropriate approach that we'll add to Apollo later on.
