### ISSUE TITLE
mainboard -d camera_detection_occupancy_nus.dag can't find detection result in Camera View window 

### ISSUE THREAD

**Issue by pily1** [ApolloAuto/apollo#15610]
**Describe the bug**
apollo10.0 build in ubuntu20.04 os,gpu is 2080 ti,cuda is 11.8,
has set save_occ_result as true in occ_det_nus.pb.txt file.
I can't find detection result in Camera View, the following image is the result
![111](https://github.com/user-attachments/assets/0b7dd797-7f3d-4e00-9771-8f5147936923)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jonathans575** [comment]
The 3d detection results can be seen in the **vehicle visualization window**.
Bev+Occ detection is carried out in bev and 3d space without additional detection on 2d images, and the detection results are not backprojected onto the Camera View for visualization.

**Comment by pily1** [comment]
think you,I  will close this issues
