### ISSUE TITLE
Encountering ‘cuda error (804)’ when running the perception module on a RTX3060 laptop

### ISSUE THREAD

**Issue by xudooo** [ApolloAuto/apollo#15613]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution: 22.04**:
- **Apollo installed from: AEM**:
- **Apollo version: 10.0**:
- **output of nvidia-smi: NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.8**

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
1. gdb mainboard
2. set args -d /apollo/modules/perception/pointcloud_preprocess/dag/pointcloud_preprocess.dag -d /apollo/modules/perception/pointcloud_map_based_roi/dag/pointcloud_map_based_roi.dag -d /apollo/modules/perception/pointcloud_ground_detection/dag/pointcloud_ground_detection.dag -d /apollo/modules/perception/lidar_detection/dag/lidar_detection.dag -d /apollo/modules/perception/lidar_detection_filter/dag/lidar_detection_filter.dag -d /apollo/modules/perception/lidar_tracking/dag/lidar_tracking.dag -d /apollo/modules/perception/lidar_output/dag/lidar_results_output.dag -p perception_lidar_debug -s CYBER_DEFAULT
3. run

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://github.com/user-attachments/assets/68dbe785-bca7-4217-8862-3776396596fc)

**Comment by Jonathans575** [comment]
Please upgrade the nvidia driver version.
You can refer to:
https://apollo.baidu.com/community/Apollo-Homepage-Document?doc=BYFxAcGcC4HpYIbgPYBtXIHQCMEEsATAV0wGNkBbWA5UyRFdZWVBEAU0hFgoIH0adPgCY%2BADwCiAVnEBBCeIAcATnETFcgMxKZkgGxKAwkoDsa3YoAi45WdGTd8paskaxs7WMW6JBr8a8zByVrMVtMUApUIA

**Comment by xudooo** [comment]
Works!
but dreamview_plus main vehicle view shows "Component error, try refresh it" , edge and chrome  both work wrong @Jonathans575 
![image](https://github.com/user-attachments/assets/ef01d70a-36c2-43e5-8c2d-f488eebb47e7)

**Comment by xudooo** [comment]
![image](https://github.com/user-attachments/assets/5ed79a1a-d4d9-477a-a5ce-7c0312a9178a)

**Comment by xudooo** [comment]
Thank you!
