### ISSUE TITLE
camera_detection_single_stage can't detect object using apollo10.0

### ISSUE THREAD

**Issue by pily1** [ApolloAuto/apollo#15612]
**Describe the bug**
ubuntu20.04 os,2080ti gpu,apollo10.0 version
camera_detection_single_stage can't detect object using apollo10.0,I write a log print the objects's score,the score is very small,it is less 0.5,the following images are the dreamviewer and the log
![Uploading 333.jpg…]()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pily1** [comment]
![333](https://github.com/user-attachments/assets/e13dd383-78f4-4a14-a67e-df593029401b)
![3333](https://github.com/user-attachments/assets/d1f76213-4abf-4ee7-8632-46356cd58f64)

**Comment by Jonathans575** [comment]
Please run "cyber_launch start /apollo/modules/perception/launch/perception_camera_single_stage.launch" or "cyber_launch start /apollo/modules/perception/launch/perception_camera_multi_stage.launch"

**Comment by pily1** [comment]
@Jonathans575 yes,I use the following command:
1、cyber_launch start /apollo/modules/transform/launch/static_transform.launch
2、cyber_launch start /apollo/modules/perception/launch/perception_camera_single_stage.launch
3、I can't find the detect objects
4、it use the smoke model
5、I write a log print the objects's score,the score is very small

**Comment by Jonathans575** [comment]
![2024-12-13 19-33-49 的屏幕截图](https://github.com/user-attachments/assets/1693d6c3-460a-462c-83e7-08b07aea0678)
Although the smoke detection algorithm is not good, but the vehicles can be detected as shown in the figure.
The sensor rgb record has been renamed in apollo 10.0 and cannot be downloaded. How do you get this record?

**Comment by pily1** [comment]
@Jonathans575 the sensor rgb record is from apollo 9.0,where can I download the correct record in apollo 10.0 ?

**Comment by pily1** [comment]
@Jonathans575 I download it from apollo 10.0 online document,refer to the following image
![555](https://github.com/user-attachments/assets/ad8a6e65-ee8a-44ec-8b24-5b1925b1ae97)

**Comment by pily1** [comment]
@Jonathans575 think you,I changed the "output_obstacles_channel_name" ,now it can detect car.I have test the perception-camera-detection-multi-stage and the perception-camera-detection-occupancy,they are ok, these two can detect car.
