### ISSUE TITLE
in Apollo 10.0 container, cannot build the new component of lidar-cluster-component

### ISSUE THREAD

**Issue by lisa0501** [ApolloAuto/apollo#15611]
base on the manual of [https://apollo.baidu.com/docs/apollo/10.x](https://apollo.baidu.com/docs/apollo/10.x/md_docs_2_xE5_xBA_x94_xE7_x94_xA8_xE5_xAE_x9E_xE8_xB7_xB5_2_xE5_xBC_x80_xE5_x8F_x91_xE8_xB0_x83_bc852499f727816f671837cee7e10749.html), when i am tring to develop a new component of lidar-cluster-component, build fails:

11:48:08) ERROR: /apollo_workspace/modules/perception/lidar_cluster/BUILD:16:17: in deps attribute of filter_proto_library rule //modules/perception/lidar_cluster:libDO_NOT_IMPORT_lidar_cluster_component.so_filter: rule '//modules/perception/lidar_cluster:apollo_perception_lidar_cluster' does not exist. Since this rule was created by the macro 'apollo_component', the error might have been caused by the macro implementation
(11:48:08) ERROR: /apollo_workspace/modules/perception/lidar_cluster/BUILD:16:17: in apollo_src_deps attribute of filter_proto_library rule //modules/perception/lidar_cluster:libDO_NOT_IMPORT_lidar_cluster_component.so_filter: rule '//modules/perception/lidar_cluster:apollo_perception_lidar_cluster' does not exist. Since this rule was created by the macro 'apollo_component', the error might have been caused by the macro implementation
(11:48:08) ERROR: /apollo_workspace/modules/perception/lidar_cluster/BUILD:16:17: Analysis of target '//modules/perception/lidar_cluster:libDO_NOT_IMPORT_lidar_cluster_component.so_filter' failed

i used this command:

 buildtool build --gpu -p modules/perception/lidar_cluster/

what does it mean "filter_proto_library" and "lib**DO_NOT_IMPORT_**lidar_cluster_component.so**_filter**: rule '//modules/perception/lidar_cluster:apollo_perception_lidar_cluster' does not exist."

**Comment by vilon888** [comment]
这个环境太难了，一堆问题

**Comment by lisa0501** [comment]
"rule '//modules/perception/lidar_cluster:apollo_perception_lidar_cluster' does not exist", so in deps, delete ":apollo_perception_lidar_cluster" will works.

i guess apollo 10.0 is clipped from another higher version, but apollo 10.0 is not maintained well right now.
