### ISSUE TITLE
Unable to find bvar package on Ubuntu 20.04+

### ISSUE THREAD

**Issue by minhanghuang** [ApolloAuto/apollo#15614]
**System information**
- OS Platform and Distribution: Ubuntu 20.04(x86_64)
- Apollo installed from: source
- Apollo version: master(v10)

**Describe the bug**

hi @daohu527, I am encountering an issue where I am unable to install the bvar package on Ubuntu 20.04+ systems using APT. The package is available and installable on Ubuntu 18.04, but on newer versions (such as Ubuntu 20.04 and 22.04), the package is not found in the repository.

![image](https://github.com/user-attachments/assets/0703903c-6627-4ab5-8f14-67ebbec38246)

1. [Add Apollo's APT repository to the system](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_pkg_repo.sh#L28)

```shell
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://apollo-pkg-beta.cdn.bcebos.com/neo/beta/key/deb.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/apolloauto.gpg
sudo chmod a+r /etc/apt/keyrings/apolloauto.gpg

echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/apolloauto.gpg] https://apollo-pkg-beta.cdn.bcebos.com/apollo/core"\
    $(. /etc/os-release && echo "$VERSION_CODENAME") "main" | \
    sudo tee /etc/apt/sources.list.d/apolloauto.list
sudo apt-get update
```

2. Attempt to install the bvar package

```shell
sudo apt install bvar
```

3. Expected behavior:
bvar package should be installed successfully on Ubuntu 20.04+.

4. Actual behavior:
The package cannot be found in the repository on Ubuntu 20.04+ (but it is available on Ubuntu 18.04).

Could you please assist with making bvar available for newer Ubuntu versions, or provide guidance on how to install it on Ubuntu 20.04+?

Thank you for your help.

**Comment by minhanghuang** [comment]
> bvar is a component of [bRPC](https://github.com/apache/brpc). The source code can be found at the provided reference link, and it can be built from source. To build only bvar, the directories src/butil and src/bvar are required. These components depend on protobuf, gflags, and libssl-dev.

What version of bvar is used in Apollo?

**Comment by ycraurora** [comment]
I'm not certain about that. I believe the latest version should be fine. I don't recall making any modifications while introducing the latest bvar, but I'm not entirely sure about it.

**Comment by HanyuWu** [comment]
@minhanghuang , I finally build libcyber.so and examples upon your cmake-built version (tag: V10rc1) , as previously discussed, butil and bvar are needed, and we should choose the exact files we need in butil, or compile errors will show up. Here is my SRCs setup (just ignore the third_party_src path-prefix...):

```CMakeLists.txt
set(BUTILS_SRCS 
    third_party_src/third_party/var/butil/third_party/dmg_fp/g_fmt.cc
    third_party_src/third_party/var/butil/third_party/dmg_fp/dtoa_wrapper.cc
    third_party_src/third_party/var/butil/third_party/dynamic_annotations/dynamic_annotations.c
    third_party_src/third_party/var/butil/third_party/icu/icu_utf.cc
    third_party_src/third_party/var/butil/third_party/superfasthash/superfasthash.c
    third_party_src/third_party/var/butil/third_party/modp_b64/modp_b64.cc
    third_party_src/third_party/var/butil/third_party/symbolize/demangle.cc
    third_party_src/third_party/var/butil/third_party/symbolize/symbolize.cc
    third_party_src/third_party/var/butil/third_party/snappy/snappy-sinksource.cc
    third_party_src/third_party/var/butil/third_party/snappy/snappy-stubs-internal.cc
    third_party_src/third_party/var/butil/third_party/snappy/snappy.cc
    third_party_src/third_party/var/butil/third_party/murmurhash3/murmurhash3.cpp
    third_party_src/third_party/var/butil/arena.cpp
    third_party_src/third_party/var/butil/at_exit.cc
    third_party_src/third_party/var/butil/atomicops_internals_x86_gcc.cc
    third_party_src/third_party/var/butil/base64.cc
    third_party_src/third_party/var/butil/base64url.cc
    third_party_src/third_party/var/butil/big_endian.cc
    third_party_src/third_party/var/butil/cpu.cc
    third_party_src/third_party/var/butil/debug/alias.cc
    third_party_src/third_party/var/butil/debug/asan_invalid_access.cc
    third_party_src/third_party/var/butil/debug/crash_logging.cc
    third_party_src/third_party/var/butil/debug/debugger.cc
    third_party_src/third_party/var/butil/debug/debugger_posix.cc
    third_party_src/third_party/var/butil/debug/dump_without_crashing.cc
    third_party_src/third_party/var/butil/debug/proc_maps_linux.cc
    third_party_src/third_party/var/butil/debug/stack_trace.cc
    third_party_src/third_party/var/butil/debug/stack_trace_posix.cc
    third_party_src/third_party/var/butil/environment.cc
    third_party_src/third_party/var/butil/files/file.cc
    third_party_src/third_party/var/butil/files/file_posix.cc
    third_party_src/third_party/var/butil/files/file_enumerator.cc
    third_party_src/third_party/var/butil/files/file_enumerator_posix.cc
    third_party_src/third_party/var/butil/files/file_path.cc
    third_party_src/third_party/var/butil/files/file_path_constants.cc
    third_party_src/third_party/var/butil/files/memory_mapped_file.cc
    third_party_src/third_party/var/butil/files/memory_mapped_file_posix.cc
    third_party_src/third_party/var/butil/files/scoped_file.cc
    third_party_src/third_party/var/butil/files/scoped_temp_dir.cc
    third_party_src/third_party/var/butil/file_util.cc
    third_party_src/third_party/var/butil/file_util_posix.cc
    third_party_src/third_party/var/butil/guid.cc
    third_party_src/third_party/var/butil/guid_posix.cc
    third_party_src/third_party/var/butil/hash.cc
    third_party_src/third_party/var/butil/lazy_instance.cc
    third_party_src/third_party/var/butil/location.cc
    third_party_src/third_party/var/butil/memory/aligned_memory.cc
    third_party_src/third_party/var/butil/memory/ref_counted.cc
    third_party_src/third_party/var/butil/memory/ref_counted_memory.cc
    third_party_src/third_party/var/butil/memory/singleton.cc
    third_party_src/third_party/var/butil/memory/weak_ptr.cc
    third_party_src/third_party/var/butil/posix/file_descriptor_shuffle.cc
    third_party_src/third_party/var/butil/posix/global_descriptors.cc
    third_party_src/third_party/var/butil/process_util.cc
    third_party_src/third_party/var/butil/rand_util.cc
    third_party_src/third_party/var/butil/rand_util_posix.cc
    third_party_src/third_party/var/butil/fast_rand.cpp
    third_party_src/third_party/var/butil/safe_strerror_posix.cc
    third_party_src/third_party/var/butil/sha1_portable.cc
    third_party_src/third_party/var/butil/strings/latin1_string_conversions.cc
    third_party_src/third_party/var/butil/strings/nullable_string16.cc
    third_party_src/third_party/var/butil/strings/safe_sprintf.cc
    third_party_src/third_party/var/butil/strings/string16.cc
    third_party_src/third_party/var/butil/strings/string_number_conversions.cc
    third_party_src/third_party/var/butil/strings/string_split.cc
    third_party_src/third_party/var/butil/strings/string_piece.cc
    third_party_src/third_party/var/butil/strings/string_util.cc
    third_party_src/third_party/var/butil/strings/string_util_constants.cc
    third_party_src/third_party/var/butil/strings/stringprintf.cc
    third_party_src/third_party/var/butil/strings/utf_offset_string_conversions.cc
    third_party_src/third_party/var/butil/strings/utf_string_conversion_utils.cc
    third_party_src/third_party/var/butil/strings/utf_string_conversions.cc
    third_party_src/third_party/var/butil/synchronization/cancellation_flag.cc
    third_party_src/third_party/var/butil/synchronization/condition_variable_posix.cc
    third_party_src/third_party/var/butil/synchronization/waitable_event_posix.cc
    third_party_src/third_party/var/butil/threading/non_thread_safe_impl.cc
    third_party_src/third_party/var/butil/threading/platform_thread_posix.cc
    third_party_src/third_party/var/butil/threading/simple_thread.cc
    third_party_src/third_party/var/butil/threading/thread_checker_impl.cc
    third_party_src/third_party/var/butil/threading/thread_collision_warner.cc
    third_party_src/third_party/var/butil/threading/thread_id_name_manager.cc
    third_party_src/third_party/var/butil/threading/thread_local_posix.cc
    third_party_src/third_party/var/butil/threading/thread_local_storage.cc
    third_party_src/third_party/var/butil/threading/thread_local_storage_posix.cc
    third_party_src/third_party/var/butil/threading/thread_restrictions.cc
    third_party_src/third_party/var/butil/threading/watchdog.cc
    third_party_src/third_party/var/butil/time/clock.cc
    third_party_src/third_party/var/butil/time/default_clock.cc
    third_party_src/third_party/var/butil/time/default_tick_clock.cc
    third_party_src/third_party/var/butil/time/tick_clock.cc
    third_party_src/third_party/var/butil/time/time.cc
    third_party_src/third_party/var/butil/time/time_posix.cc
    third_party_src/third_party/var/butil/version.cc
    third_party_src/third_party/var/butil/logging.cc
    third_party_src/third_party/var/butil/class_name.cpp
    third_party_src/third_party/var/butil/errno.cpp
    third_party_src/third_party/var/butil/find_cstr.cpp
    third_party_src/third_party/var/butil/status.cpp
    third_party_src/third_party/var/butil/string_printf.cpp
    third_party_src/third_party/var/butil/thread_local.cpp
    third_party_src/third_party/var/butil/thread_key.cpp
    third_party_src/third_party/var/butil/unix_socket.cpp
    third_party_src/third_party/var/butil/endpoint.cpp
    third_party_src/third_party/var/butil/fd_utility.cpp
    third_party_src/third_party/var/butil/files/temp_file.cpp
    third_party_src/third_party/var/butil/files/file_watcher.cpp
    third_party_src/third_party/var/butil/time.cpp
    third_party_src/third_party/var/butil/zero_copy_stream_as_streambuf.cpp
    third_party_src/third_party/var/butil/crc32c.cc
    third_party_src/third_party/var/butil/containers/case_ignored_flat_map.cpp
    third_party_src/third_party/var/butil/iobuf.cpp
    third_party_src/third_party/var/butil/iobuf_profiler.cpp
    third_party_src/third_party/var/butil/binary_printer.cpp
    third_party_src/third_party/var/butil/recordio.cc
    third_party_src/third_party/var/butil/popen.cpp
    third_party_src/third_party/var/butil/file_util_linux.cc
    third_party_src/third_party/var/butil/threading/platform_thread_linux.cc
    third_party_src/third_party/var/butil/strings/sys_string_conversions_posix.cc
)
```
 
 I haven't installed google-perftools yet, so I ignored the sub-directory mainboard and tools. 
 
 
![1734352696_grim](https://github.com/user-attachments/assets/bc04547f-dfb2-4e15-a2b1-7da4e41ce73c)

 
By the way, eProsima namespace and eProsima_wrap is tricky too, I work-around a bit by rewriting some source codes in Cyber to make it compiled.

**Comment by minhanghuang** [comment]
> Hi @minhanghuang ，we recommend using Ubuntu 22.04 in host mode，and you can use docker container mode on ubuntu 20.04, please use aem start without -b host hava a try.
> 
> https://apollo.baidu.com/community/Apollo-Homepage-Document?doc=BYFxAcGcC4HpYIbgPYBtXIHQCMEEsATAV0wGNkBbWA5UyRFdZWVBEAU0hFgoIH0adPgCY%2BADwCiAVnEBBCeIAcATnETFcgMxKZkgGxKAwkoDsa3YoAi45WdGTd8paskaxs7WMW6JBr8a8zByVrMVtMUApUIA

@hearto1314 Thank you very much! This is a great solution. However, I hope to use Cyber standalone on different versions of Ubuntu

**Comment by minhanghuang** [comment]
> @minhanghuang , I finally build libcyber.so and examples upon your cmake-built version (tag: V10rc1) , as previously discussed, butil and bvar are needed, and we should choose the exact files we need in butil, or compile errors will show up. Here is my SRCs setup (just ignore the third_party_src path-prefix...):
> 
> ```
> set(BUTILS_SRCS 
>     third_party_src/third_party/var/butil/third_party/dmg_fp/g_fmt.cc
>     third_party_src/third_party/var/butil/third_party/dmg_fp/dtoa_wrapper.cc
>     third_party_src/third_party/var/butil/third_party/dynamic_annotations/dynamic_annotations.c
>     third_party_src/third_party/var/butil/third_party/icu/icu_utf.cc
>     third_party_src/third_party/var/butil/third_party/superfasthash/superfasthash.c
>     third_party_src/third_party/var/butil/third_party/modp_b64/modp_b64.cc
>     third_party_src/third_party/var/butil/third_party/symbolize/demangle.cc
>     third_party_src/third_party/var/butil/third_party/symbolize/symbolize.cc
>     third_party_src/third_party/var/butil/third_party/snappy/snappy-sinksource.cc
>     third_party_src/third_party/var/butil/third_party/snappy/snappy-stubs-internal.cc
>     third_party_src/third_party/var/butil/third_party/snappy/snappy.cc
>     third_party_src/third_party/var/butil/third_party/murmurhash3/murmurhash3.cpp
>     third_party_src/third_party/var/butil/arena.cpp
>     third_party_src/third_party/var/butil/at_exit.cc
>     third_party_src/third_party/var/butil/atomicops_internals_x86_gcc.cc
>     third_party_src/third_party/var/butil/base64.cc
>     third_party_src/third_party/var/butil/base64url.cc
>     third_party_src/third_party/var/butil/big_endian.cc
>     third_party_src/third_party/var/butil/cpu.cc
>     third_party_src/third_party/var/butil/debug/alias.cc
>     third_party_src/third_party/var/butil/debug/asan_invalid_access.cc
>     third_party_src/third_party/var/butil/debug/crash_logging.cc
>     third_party_src/third_party/var/butil/debug/debugger.cc
>     third_party_src/third_party/var/butil/debug/debugger_posix.cc
>     third_party_src/third_party/var/butil/debug/dump_without_crashing.cc
>     third_party_src/third_party/var/butil/debug/proc_maps_linux.cc
>     third_party_src/third_party/var/butil/debug/stack_trace.cc
>     third_party_src/third_party/var/butil/debug/stack_trace_posix.cc
>     third_party_src/third_party/var/butil/environment.cc
>     third_party_src/third_party/var/butil/files/file.cc
>     third_party_src/third_party/var/butil/files/file_posix.cc
>     third_party_src/third_party/var/butil/files/file_enumerator.cc
>     third_party_src/third_party/var/butil/files/file_enumerator_posix.cc
>     third_party_src/third_party/var/butil/files/file_path.cc
>     third_party_src/third_party/var/butil/files/file_path_constants.cc
>     third_party_src/third_party/var/butil/files/memory_mapped_file.cc
>     third_party_src/third_party/var/butil/files/memory_mapped_file_posix.cc
>     third_party_src/third_party/var/butil/files/scoped_file.cc
>     third_party_src/third_party/var/butil/files/scoped_temp_dir.cc
>     third_party_src/third_party/var/butil/file_util.cc
>     third_party_src/third_party/var/butil/file_util_posix.cc
>     third_party_src/third_party/var/butil/guid.cc
>     third_party_src/third_party/var/butil/guid_posix.cc
>     third_party_src/third_party/var/butil/hash.cc
>     third_party_src/third_party/var/butil/lazy_instance.cc
>     third_party_src/third_party/var/butil/location.cc
>     third_party_src/third_party/var/butil/memory/aligned_memory.cc
>     third_party_src/third_party/var/butil/memory/ref_counted.cc
>     third_party_src/third_party/var/butil/memory/ref_counted_memory.cc
>     third_party_src/third_party/var/butil/memory/singleton.cc
>     third_party_src/third_party/var/butil/memory/weak_ptr.cc
>     third_party_src/third_party/var/butil/posix/file_descriptor_shuffle.cc
>     third_party_src/third_party/var/butil/posix/global_descriptors.cc
>     third_party_src/third_party/var/butil/process_util.cc
>     third_party_src/third_party/var/butil/rand_util.cc
>     third_party_src/third_party/var/butil/rand_util_posix.cc
>     third_party_src/third_party/var/butil/fast_rand.cpp
>     third_party_src/third_party/var/butil/safe_strerror_posix.cc
>     third_party_src/third_party/var/butil/sha1_portable.cc
>     third_party_src/third_party/var/butil/strings/latin1_string_conversions.cc
>     third_party_src/third_party/var/butil/strings/nullable_string16.cc
>     third_party_src/third_party/var/butil/strings/safe_sprintf.cc
>     third_party_src/third_party/var/butil/strings/string16.cc
>     third_party_src/third_party/var/butil/strings/string_number_conversions.cc
>     third_party_src/third_party/var/butil/strings/string_split.cc
>     third_party_src/third_party/var/butil/strings/string_piece.cc
>     third_party_src/third_party/var/butil/strings/string_util.cc
>     third_party_src/third_party/var/butil/strings/string_util_constants.cc
>     third_party_src/third_party/var/butil/strings/stringprintf.cc
>     third_party_src/third_party/var/butil/strings/utf_offset_string_conversions.cc
>     third_party_src/third_party/var/butil/strings/utf_string_conversion_utils.cc
>     third_party_src/third_party/var/butil/strings/utf_string_conversions.cc
>     third_party_src/third_party/var/butil/synchronization/cancellation_flag.cc
>     third_party_src/third_party/var/butil/synchronization/condition_variable_posix.cc
>     third_party_src/third_party/var/butil/synchronization/waitable_event_posix.cc
>     third_party_src/third_party/var/butil/threading/non_thread_safe_impl.cc
>     third_party_src/third_party/var/butil/threading/platform_thread_posix.cc
>     third_party_src/third_party/var/butil/threading/simple_thread.cc
>     third_party_src/third_party/var/butil/threading/thread_checker_impl.cc
>     third_party_src/third_party/var/butil/threading/thread_collision_warner.cc
>     third_party_src/third_party/var/butil/threading/thread_id_name_manager.cc
>     third_party_src/third_party/var/butil/threading/thread_local_posix.cc
>     third_party_src/third_party/var/butil/threading/thread_local_storage.cc
>     third_party_src/third_party/var/butil/threading/thread_local_storage_posix.cc
>     third_party_src/third_party/var/butil/threading/thread_restrictions.cc
>     third_party_src/third_party/var/butil/threading/watchdog.cc
>     third_party_src/third_party/var/butil/time/clock.cc
>     third_party_src/third_party/var/butil/time/default_clock.cc
>     third_party_src/third_party/var/butil/time/default_tick_clock.cc
>     third_party_src/third_party/var/butil/time/tick_clock.cc
>     third_party_src/third_party/var/butil/time/time.cc
>     third_party_src/third_party/var/butil/time/time_posix.cc
>     third_party_src/third_party/var/butil/version.cc
>     third_party_src/third_party/var/butil/logging.cc
>     third_party_src/third_party/var/butil/class_name.cpp
>     third_party_src/third_party/var/butil/errno.cpp
>     third_party_src/third_party/var/butil/find_cstr.cpp
>     third_party_src/third_party/var/butil/status.cpp
>     third_party_src/third_party/var/butil/string_printf.cpp
>     third_party_src/third_party/var/butil/thread_local.cpp
>     third_party_src/third_party/var/butil/thread_key.cpp
>     third_party_src/third_party/var/butil/unix_socket.cpp
>     third_party_src/third_party/var/butil/endpoint.cpp
>     third_party_src/third_party/var/butil/fd_utility.cpp
>     third_party_src/third_party/var/butil/files/temp_file.cpp
>     third_party_src/third_party/var/butil/files/file_watcher.cpp
>     third_party_src/third_party/var/butil/time.cpp
>     third_party_src/third_party/var/butil/zero_copy_stream_as_streambuf.cpp
>     third_party_src/third_party/var/butil/crc32c.cc
>     third_party_src/third_party/var/butil/containers/case_ignored_flat_map.cpp
>     third_party_src/third_party/var/butil/iobuf.cpp
>     third_party_src/third_party/var/butil/iobuf_profiler.cpp
>     third_party_src/third_party/var/butil/binary_printer.cpp
>     third_party_src/third_party/var/butil/recordio.cc
>     third_party_src/third_party/var/butil/popen.cpp
>     third_party_src/third_party/var/butil/file_util_linux.cc
>     third_party_src/third_party/var/butil/threading/platform_thread_linux.cc
>     third_party_src/third_party/var/butil/strings/sys_string_conversions_posix.cc
> )
> ```
> 
> I haven't installed google-perftools yet, so I ignored the sub-directory mainboard and tools.
> 
> ![1734352696_grim](https://private-user-images.githubusercontent.com/42722733/396097974-bc04547f-dfb2-4e15-a2b1-7da4e41ce73c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDAwNTAsIm5iZiI6MTczNDM5OTc1MCwicGF0aCI6Ii80MjcyMjczMy8zOTYwOTc5NzQtYmMwNDU0N2YtZGZiMi00ZTE1LWEyYjEtN2RhNGU0MWNlNzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAxNDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MWQxOWIzNDI4YzM1OGUwMDAwNmI4NjcxZjY3MTlkNWFkYmFmZDAyZDBlZTgwZjU3N2EyOTM5MGYwOGY3MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FbDmDuni_vwloXWMDx95JtjEQwMwq9nbsz2jyi9A8lQ)
> 
> By the way, eProsima namespace and eProsima_wrap is tricky too, I work-around a bit by rewriting some source codes in Cyber to make it compiled.

@HanyuWu , That's a good idea. I'm not sure about the version of bvar used in Apollo.

**Comment by hearto1314** [comment]
> > Hi @minhanghuang ，we recommend using Ubuntu 22.04 in host mode，and you can use docker container mode on ubuntu 20.04, please use aem start without -b host hava a try.
> > https://apollo.baidu.com/community/Apollo-Homepage-Document?doc=BYFxAcGcC4HpYIbgPYBtXIHQCMEEsATAV0wGNkBbWA5UyRFdZWVBEAU0hFgoIH0adPgCY%2BADwCiAVnEBBCeIAcATnETFcgMxKZkgGxKAwkoDsa3YoAi45WdGTd8paskaxs7WMW6JBr8a8zByVrMVtMUApUIA
> 
> @hearto1314 Thank you very much! This is a great solution. However, I hope to use Cyber standalone on different versions of Ubuntu

the bvar package is stored in apollo apt repo, build from https://github.com/apache/brpc/blob/master/docs/en/bvar.md , it seems that the package is missing in apollo focal(ubuntu 20.04) amd64 repo,  we are mainly testing on ubuntu 22.04  recently, so  we recommend using Ubuntu 22.04 in host mode.

**Comment by freeterfei** [comment]
diff --git a/cyber/base/macros.h b/cyber/base/macros.h
index 96442a3..e98a8c8 100644
--- a/cyber/base/macros.h
+++ b/cyber/base/macros.h
@@ -20,7 +20,7 @@
 #include <cstdlib>
 #include <new>
 
-#define eprosima eprosima_wrap
+//#define eprosima eprosima_wrap

eProsima namespace and eProsima_wrap

**Comment by minhanghuang** [comment]
> freeterfei

@freeterfei, after compiling and installing `fastdds v2.14.3` from source, can the `cyber_example_talker` and `cyber_example_listener` run properly?

**Comment by pangxiansen123** [comment]
请问您解决了ERROR hint: Can not find bvar in any apt repository这个问题了吗？ @minhanghuang

**Comment by minhanghuang** [comment]
> 请问您解决了ERROR hint: Can not find bvar in any apt repository这个问题了吗？ @minhanghuang

解决了,下载Apollo提供的bvar.deb包,完后解压安装

**Comment by minhanghuang** [comment]
hi, @hearto1314 Could you provide the source code for 3rd-fastdds-wrap? I compiled CyberRT with fastdds v2.14.3, but it doesn't work.

**Comment by zhaizhc** [comment]
> hi, [@hearto1314](https://github.com/hearto1314) Could you provide the source code for 3rd-fastdds-wrap? I compiled CyberRT with fastdds v2.14.3, but it doesn't work.

请问您拿到源码了吗 @minhanghuang

**Comment by minhanghuang** [comment]
> > hi, [@hearto1314](https://github.com/hearto1314) Could you provide the source code for 3rd-fastdds-wrap? I compiled CyberRT with fastdds v2.14.3, but it doesn't work.
> 
> 请问您拿到源码了吗 [@minhanghuang](https://github.com/minhanghuang)

打个补丁就可以了[patch](https://github.com/minhanghuang/CyberRT/commit/bca7c59c7956fc020279ca6772f1f1c0f1b383ab)

**Comment by zhaizhc** [comment]
> > > hi, [@hearto1314](https://github.com/hearto1314) Could you provide the source code for 3rd-fastdds-wrap? I compiled CyberRT with fastdds v2.14.3, but it doesn't work.
> > 
> > 
> > 请问您拿到源码了吗 [@minhanghuang](https://github.com/minhanghuang)
> 
> 打个补丁就可以了[patch](https://github.com/minhanghuang/CyberRT/commit/bca7c59c7956fc020279ca6772f1f1c0f1b383ab)

感谢！
