### ISSUE TITLE
what's the performance comparison between apollo 8.0 with apollo 9.0 or apollo 10.0

### ISSUE THREAD

**Issue by pily1** [ApolloAuto/apollo#15620]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5, 5.0, 5.5, 6.0)**:
- **Output of `apollo.sh config` if on `master` branch**:
- I understand that in Apollo 8.0 and earlier versions, the perception module operates through a pipeline, with functions communicating via parameter passing .
- In Apollo 9.0 and 10.0, the perception module's components communicate using cyber::Writer.
- I want to know whether communicating using cyber::Writer is slower than passing parameters through functions.
- Are there any performance comparison indicators？

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by ycraurora** [comment]
Just for CyberRT perfomance between Apollo10.0 and Apollo 9.0
[CyberRT Performance Report](https://github.com/ApolloAuto/apollo/blob/master/docs/%E9%99%84%E5%BD%95/CyberRT%20Performance%20Report.md)

**Comment by pily1** [comment]
I want to know whether communicating using cyber::Writer is slower than passing parameters through functions

**Comment by hearto1314** [comment]
these two are not in the same dimension. 
cyber document:  https://github.com/ApolloAuto/apollo/blob/master/cyber/README.md
