### ISSUE TITLE
Error response from daemon: no such id: apollo_release

### ISSUE THREAD

**Issue by sgong4** [ApolloAuto/apollo#157]
now i update my docker version
it's Docker version 1.9.1, build a34a1d5
but when i try this "docker/scripts/release_start.sh"
there will be some errors ,like below:

OK ] Found device: /dev/loop7.
[ OK ] Found device: /dev/loop6.
[ OK ] Found device: /dev/loop5.
[ OK ] Found device: /dev/loop4.
[ OK ] Found device: /dev/loop3.
[ OK ] Found device: /dev/loop2.
[ OK ] Found device: /dev/loop1.
[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop-control.
flag provided but not defined: --shm-size
See 'docker run --help'.
Error response from daemon: no such id: apollo_release
Error response from daemon: no such id: apollo_release
Error response from daemon: no such id: apollo_release

Can anyone help me?

**Comment by quning78** [comment]
Did you install the docker by apollo's script?

https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/install_docker.sh

The installed docker is supposed to be:

$docker -v
Docker version 17.05.0-ce, build 89658be

**Comment by wanglei828** [comment]
This error message is coming from "docker rm -f apollo_release", because your system does not have this container before. We add a conditional statement to fix this issue.

**Comment by wanglei828** [comment]
This issue has been fixed.  Please update your code repo.

**Comment by sgong4** [comment]
you mean i have to download the new code from https://github.com/ApolloAuto/apollo.git.
And try again.

@wanglei828

**Comment by startcode** [comment]
@sgong4 you only have to update your code by
```
git pull origin master
```

**Comment by sgong4** [comment]
when i  git pull origin master 
like below:
sgong4@sgong4-X550DP1:~/下载/apollo-master$ git pull origin master
来自 https://github.com/ApolloAuto/apollo
 * branch            master     -> FETCH_HEAD
Already up-to-date.

but it's the same error.

[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop-control.
flag provided but not defined: --shm-size
See 'docker run --help'.
Error response from daemon: no such id: apollo_release
Error response from daemon: no such id: apollo_release
Error response from daemon: no such id: apollo_release
@startcode @wanglei828   can give me any advise.

**Comment by startcode** [comment]
@sgong4 which docker version are you using?
`--shm-size` is docker command's option. In my docker,
```
% docker --version
Docker version 17.05.0-ce, build 89658be
```
This option is supported.

**Comment by sgong4** [comment]
@startcode @quning78 @wanglei828 
i have updated the version . now it's ok for no such id: apollo_release.
but there is another problem :some command not found , what should i do next.

# error information :
sgong4@in_dev_docker:/apollo$ docker/scripts/release_start.sh
APOLLO_ROOT_DIR=/apollo
docker/scripts/release_start.sh: line 72: docker: command not found
docker/scripts/release_start.sh: line 74: docker: command not found
tee: /proc/sys/kernel/core_pattern: Read-only file system
/apollo/data/core/core_%e.%p
[WARNING] Failed to find device with pattern "ttyUSB*" ...
[ OK ] Found device: /dev/ttyS0.
[ OK ] Found device: /dev/ttyS1.
[ OK ] Found device: /dev/ttyS2.
[ OK ] Found device: /dev/ttyS3.
[ OK ] Found device: /dev/ttyS4.
[ OK ] Found device: /dev/ttyS5.
[ OK ] Found device: /dev/ttyS6.
[ OK ] Found device: /dev/ttyS7.
[ OK ] Found device: /dev/ttyS8.
[ OK ] Found device: /dev/ttyS9.
[ OK ] Found device: /dev/ttyS10.
[ OK ] Found device: /dev/ttyS11.
[ OK ] Found device: /dev/ttyS12.
[ OK ] Found device: /dev/ttyS13.
[ OK ] Found device: /dev/ttyS14.
[ OK ] Found device: /dev/ttyS15.
[ OK ] Found device: /dev/ttyS16.
[ OK ] Found device: /dev/ttyS17.
[ OK ] Found device: /dev/ttyS18.
[ OK ] Found device: /dev/ttyS19.
[ OK ] Found device: /dev/ttyS20.
[ OK ] Found device: /dev/ttyS21.
[ OK ] Found device: /dev/ttyS22.
[ OK ] Found device: /dev/ttyS23.
[ OK ] Found device: /dev/ttyS24.
[ OK ] Found device: /dev/ttyS25.
[ OK ] Found device: /dev/ttyS26.
[ OK ] Found device: /dev/ttyS27.
[ OK ] Found device: /dev/ttyS28.
[ OK ] Found device: /dev/ttyS29.
[ OK ] Found device: /dev/ttyS30.
[ OK ] Found device: /dev/ttyS31.
[ OK ] Found device: /dev/can0.
[WARNING] Failed to find device with pattern "ram*" ...
[ OK ] Found device: /dev/loop-control.
[ OK ] Found device: /dev/loop0.
[ OK ] Found device: /dev/loop1.
[ OK ] Found device: /dev/loop2.
[ OK ] Found device: /dev/loop3.
[ OK ] Found device: /dev/loop4.
[ OK ] Found device: /dev/loop5.
[ OK ] Found device: /dev/loop6.
[ OK ] Found device: /dev/loop7.
docker/scripts/release_start.sh: line 111: docker: command not found
docker/scripts/release_start.sh: line 136: docker: command not found
docker/scripts/release_start.sh: line 137: docker: command not found
docker/scripts/release_start.sh: line 139: docker: command not found

**Comment by ycool** [comment]
release_start.sh is to run out of docker env.  Currently, you run it inside dev docker. 

`sgong4@in_dev_docker:/apollo$ docker/scripts/release_start.sh`
