### ISSUE TITLE
您好，请问Apollo docker直接rviz图形显示化工具吗，我在doker安装rivz运行会报Error: BadDrawble (invalid Pixmap or Window parameter) 9)

### ISSUE THREAD

**Issue by luo2880399** [ApolloAuto/apollo#1572]

**Comment by fengqikai1414** [comment]
我们暂时没有在apollo的docker环境里对rviz进行适配，所以可能存在一些兼容性问题。

**Comment by luo2880399** [comment]
已经解决，只要在dev_start.sh中加-e QT_X11_NO_MITSHM=1 就能成功在docker里面运行rviz

**Comment by xiaoxq** [comment]
@luo2880399 Thanks for figuring it out and share it with the community!
