### ISSUE TITLE
can not find time.pb.h' install error , please help me, thanks!!!

### ISSUE THREAD

**Issue by fireflychh** [ApolloAuto/apollo#158]
when I installed the apollo_platform_master on a ubuntu 16.04, I got the error, what is the problem, does it need some dependence or someelse.Thank you very much.

make[2]: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: Command not found
CMakeFiles/pb_msgs_proto.dir/build.make:61: recipe for target '/home/fire/program/Apollo/apollo-platform-master/ros/devel_isolated/pb_msgs/include/time.pb.h' failed
make[2]: *** [/home/fire/program/Apollo/apollo-platform-master/ros/devel_isolated/pb_msgs/include/time.pb.h] Error 127
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pb_msgs_proto.dir/all' failed
make[1]: *** [CMakeFiles/pb_msgs_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 60%] Built target pb_msgs_generate_messages_lisp
[ 60%] Generating Python from proto pb_msgs/time.proto
[ 60%] Generating C++ code from pb_msgs/time.proto
make[2]: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: Command not found
make[2]: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: Command not found
CMakeFiles/pb_msgs_generate_messages_py.dir/build.make:60: recipe for target '/home/fire/program/Apollo/apollo-platform-master/ros/install/ros_x86_64/lib/python2.7/dist-packages/pb_msgs/msg/time_pb2.py' failed
make[2]: *** [/home/fire/program/Apollo/apollo-platform-master/ros/install/ros_x86_64/lib/python2.7/dist-packages/pb_msgs/msg/time_pb2.py] Error 127
CMakeFiles/pb_msgs_generate_messages_cpp.dir/build.make:60: recipe for target '/home/fire/program/Apollo/apollo-platform-master/ros/devel_isolated/pb_msgs/include/time.pb.h' failed
make[2]: *** [/home/fire/program/Apollo/apollo-platform-master/ros/devel_isolated/pb_msgs/include/time.pb.h] Error 127
CMakeFiles/Makefile2:168: recipe for target 'CMakeFiles/pb_msgs_generate_messages_py.dir/all' failed
make[1]: *** [CMakeFiles/pb_msgs_generate_messages_py.dir/all] Error 2
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/pb_msgs_generate_messages_cpp.dir/all' failed
make[1]: *** [CMakeFiles/pb_msgs_generate_messages_cpp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'pb_msgs': 
  Command '['/home/fire/program/Apollo/apollo-platform-master/ros/install/ros_x86_64/env.sh', 'make', '-j8', '-l8']' returned non-zero exit status 2

**Comment by lubaogui** [comment]
it seems there's no protobuf installed in your system or the env is not properly set.
 make[2]: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: Command not found

**Comment by GoLancer** [comment]
we provide a build docker image which include all dependencies.
You can download and use docker with the following commands:
```bash
git clone https://github.com/ApolloAuto/apollo.git apollo
cd apollo
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
