### ISSUE TITLE
No Py3 support and not support PEP8？

### ISSUE THREAD

**Issue by Allianzcortex** [ApolloAuto/apollo#16]
e.g.:https://github.com/ApolloAuto/apollo/blob/master/modules/tools/control_info/control_info.py

1.use `print "Showing Lateral"` rather than `print ("Showing Lateral")`;I expect many `from __future__ import xx` lines

2.And import order:`import sys` is **system library**,appear on first line;`import threading` is also **system library**,appear on second line from bottom;including **third-part library** and **module-part library** between them;I don't konw whcih coding-style support such writing?

**Comment by xiaoxq** [comment]
Thanks for the advice.

1. We stick to py2 currently.
2. We will do the code clean ASAP. Or you may also help on it :)

**Comment by Allianzcortex** [comment]
@xiaoxq 
for the 1st issue,it's a pity/(ㄒoㄒ)/~~ mainly because I don't find some gevent-like-python2-only-library in use,so I just think compatibility with python3 won't be very difficult？(⊙﹏⊙) even Tensorflow supports both version,so......～～
and the 2nd,thanks for your appreciation～~Now I'll try to see how C++ code is writen,Python is just a wrapper and plot toolkit :)
