### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by jingleFun** [ApolloAuto/apollo#1602]
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception_cn.md 中间应该是直方分布，写成脂肪分布了

**Comment by lianglia-apollo** [comment]
Thank you for pointing out this error. We have updated this document (https://github.com/ApolloAuto/apollo/commit/97ad22aa4800648eeacb590956525f90cdc5caab).

Also, you are very welcome to make a pull request directly if you found other issues.
