### ISSUE TITLE
DP boundary conditions ?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#1614]
Hello,

I have a question about EM planner.
What I understood is that some boundary conditions are found by solving some optimization problem using Dynamic Programming. What exactly those boundary conditions? Are they speed limits and lane boundaries? 
Thank you!

**Comment by lianglia-apollo** [comment]
The concept of boundary conditions is used for quadratic programming (QP).
The boundaries come from the road (such as road speed limits, lane boundaries), vehicle dynamics (e.g. curvature, acceleration of a trajectory), and other obstacles.

**Comment by lianglia-apollo** [comment]
One more thing. There is another kind of boundary -- regions in S-T graph that represent the mapping of obstacles in a path - time coordinate system. In a DP process, the distance between a point (s, t) and the obstacle s-t boundaries are calculated and a cost is assigned based on the distance.

**Comment by wckorealsh** [comment]
Thanks, I am trying to understand the process. Please take a look at attached screen shot

![apollo](https://user-images.githubusercontent.com/7061502/33715080-5757d9ac-db1f-11e7-80a5-7364897f9830.png)

Can you please explain dotted line from DpStSpeedOptimizer and dotted lines in QpSplineStSpeedOptimizer? I am familiar with S-T graph.

Thank you again!

**Comment by lianglia-apollo** [comment]
DpStSpeedOptimizer: the dotted line is the optimization results from dynamic programming.
QpSplineStSpeedOptimizer: the dotted lines are some reference lines calculated in task/qp_spline_st_speed/qp_spline_st_graph.cc (line 337 and line 391).

**Comment by wckorealsh** [comment]
Thank you and sorry for keep bugging you.
Yes, the line of DpStSpeedOptimizer must be the optimization result of DP. Can you please provide its physical meaning? Thank you!

**Comment by lianglia-apollo** [comment]
The result is a list of (s,t) points, meaning at some time t, we would lime the vehicle to travel a distance s (starting from the current position) on the generated path.
