### ISSUE TITLE
the system always return to the login menu

### ISSUE THREAD

**Issue by gazige1981** [ApolloAuto/apollo#1637]
Hi
I have a question
the system always return to the login menu when i enter the right password.

the system include 
operating system:ubuntu 14.04.5 LTS
kernel version:4.4.32-apollo-2-RT
nvidia gpu driver:nvidia-linux-x86_64-375.39
apollo source code：git clone git@github.com:ApolloAuto/apollo.git
docker:bash docker/scripts/install_docker.sh

anybody have a similar problem? and how to solve it?

thanks

**Comment by zhxt** [comment]
hi gazige1981,
Acturally , this is about the "love and hate" between Ubuntu and Nvidia graphic driver :P 
There is a lot of results when you search the keyword "ubuntu login loop nvidia".

FYI:
https://askubuntu.com/questions/721633/nvidia-graphics-card-driver-installed-led-to-login-loop
https://askubuntu.com/questions/624966/cant-login-after-nvidia-driver-install-v-14-04
https://askubuntu.com/questions/862943/login-infinite-loop-after-installing-an-nvidia-driver
https://devtalk.nvidia.com/default/topic/878117/cuda-setup-and-installation/-solved-titan-x-for-cuda-7-5-login-loop-error-ubuntu-14-04-/

**Comment by gazige1981** [comment]
thank you for you help , I have reinstall the system without nvidia driver update.
