### ISSUE TITLE
Queries regarding Offline Simulation Engine, Startup with external hardware and its visualization on Dreamviewer

### ISSUE THREAD

**Issue by Prasan03** [ApolloAuto/apollo#1649]
I recently started using Apollo on my laptop and everything went well with the initial Demo part. I was able to access Dreamview and saw the vehicle moving.
The "How to understand architecture and workflow" document helped a lot in getting a broader picture of the software. Thank you!
But, I did not understand the concept of Offline Simulation Engine, as the above-mentioned document claims that we can start development immediately without a car or hardware. I even tried playing around on Dreamview by changing parameters listed but did not go any further. Please find the image attached. Please help me in getting started with the offline simulation engine.

Also, I am very much interested in going ahead with the software as I have access to some sensors like OxTS RT3000 (GNSS+Inertial), IBEO LUX Lidar and Hella 5G1 Radar, how can I integrate them with Apollo and can I visualize them in Dreamviewer?

Any help in this direction will be really appreciated. Thanks in advance!

![dreamview](https://user-images.githubusercontent.com/34156395/33728060-84573538-db79-11e7-915c-79c77ed5c330.png)

**Comment by ycool** [comment]
First you can write or find drivers for these sensors OxTS RT3000 (GNSS+Inertial), IBEO LUX Lidar and Hella 5G1 Radar. After the system is able to read these sensor data, localization module can be integrated with OxTS RT3000 (GNSS+Inertial) sensor output by adding new config/codes.  perception module can be integrated with IBEO LUX Lidar and Hella 5G1 Radar sensor output by adding new configs/codes. After that, dreamview will visualize the output from new localization and perception modules. 

Good luck, feel free to ping back if need more information and keep us updated if any progress. 

Thanks.

**Comment by Prasan03** [comment]
Thank you @ycool!

As I am very new to this I would like to go step by step. I am planning to kickstart with localization module so just configuring the IMU is enough to visualize localization on dreamview?
Also, I found the ROS driver for OxTS RT3000 on ROS Wiki can I directly use that?
And can you please guide me through the adding the config/codes part, may be a reference would be really helpful.

And about the offline simulation engine, do you have any details?

Thanks in advance!

**Comment by unacao** [comment]
Simulation Dreamview is a visualization tool to help understand the output of each module (e.g. perception, localization, planning etc.). If you have a rosbag with the relevant topics, you can replay the bag along with real-time running of your updated binary module. For example, you can reuse the perception data in the rosbag, and generate new planning data based on your updated code. The Dreamview should be able to show the original perception along with the updated planning. An easier way would be to run the simulation with your own git repo on https://azure.apollo.auto

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.

**Comment by cdemirsoy** [comment]
> Simulation Dreamview is a visualization tool to help understand the output of each module (e.g. perception, localization, planning etc.). If you have a rosbag with the relevant topics, you can replay the bag along with real-time running of your updated binary module. For example, you can reuse the perception data in the rosbag, and generate new planning data based on your updated code. The Dreamview should be able to show the original perception along with the updated planning. An easier way would be to run the simulation with your own git repo on https://azure.apollo.auto

I do not understand exactly. People say that it is a platform that helps to monitor the output of Autonomous Driving modules. But, referring to provided demo rosbag, it can be seen that there are already perception, control and localization output, which means that Autonomous Driving modules are not doing anything at all because what we are doing is just visualizing already recorded data. 

Am I correct?
Thanks so much in advance!

**Comment by unacao** [comment]
@cdemirsoy Data can come from different sources, e.g. from replaying recorded data or from real-time output of the binary modules. For example, if we would like to test our own planning module, we may choose to replay perception data from a recorded file, but exclude/filter the recorded planning data. Instead we generate planning data from our real-time binary module, and enable sim_control to update the localization based on the new planning data. In all the use cases, Dreamview is a visualization tool regardless of the data sources.
