### ISSUE TITLE
Could you share the parameter configure of Delphi ESR Radar？

### ISSUE THREAD

**Issue by AjackZhao** [ApolloAuto/apollo#1650]
I have some trouble while using the ESR. Maybe my parameter config of radar is wrong. the data that the radar detect is always not good enough especially the tracking performance. Thank you very much!

**Comment by jinghaomiao** [comment]
Currently Apollo uses Continental radar as a reference hardware only.

**Comment by lijiong123** [comment]
can you use ros driver for delphi successful?

**Comment by CCodie** [comment]
@AjackZhao Hi, I'm trying to use my own radar.
Could you tell me how you verify your radar performance ? Is there any tools ?
I would really appreciate it if you give me the reply. Thanks !
