### ISSUE TITLE
Could it have more comments in code，more readme file and  docs to explain the idea of apollo

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#1684]
Most of time，just code，code，code，code，code，code，code，code，code，code，
could we give a little more explanation and reference material about the model and algorithm

**Comment by Capri2014** [comment]
@gengqx  Sorry we have a lot of new features need to add  and validate recently, and are really short in hands for more detailed explanations and documentations as what we should do.  Will definitely do that!

BTW, here is a meetup call next Tues that you might be interested if you want to really get hands on with Apollo. :)   https://www.meetup.com/ApolloAuto/events/245651758/

**Comment by gengqx** [comment]
I’m sorry this meetup is in American，and Now I’m in China.
And I could see the main topic is tell us how to start up with apollo,indeed I have run the run the docker and the dreamview for a long time a ago. The main concern of my is to understand the whole workflow，to debug the module ，to modify the module，and run in a real car，so document would be great help.

Even this, I still wonder if you can make it online,webinars would be great benifit for the developers all over the world.
@Capri2014

**Comment by lianglia-apollo** [comment]
Will the hands-on session be recorded? We can record it so that people outside of the bay area can watch.

**Comment by ahuer2435** [comment]
@gengqx 如果感兴趣可以看下：https://github.com/ahuer2435/apollo/tree/master/docs/howto下arch和modules目录，是自己学习apollo的笔记，也可能有一些理解不对之处，仅供参考；也可以看下里面的代码部分，也有一些注释，不过代码没有跟随主干更新，因为想加入代码注释，所以就没有请求提交到主干。
本来想把文档部分提交到apollo主干上，但是没找到提交单笔request的方法。

**Comment by ycool** [comment]
@ahuer2435 
Sending a pull request is simple. 
* fork apollo repo into your github
* create a dev branch in your repo
* commit your change in your dev branch
* send  the pull request from your github repo web page 

More details can be found at  https://help.github.com/articles/creating-a-pull-request-from-a-fork/
Looking forward to your contribution! 

Thanks.

**Comment by ahuer2435** [comment]
我理解的pull request是需要自己的仓库中有一个分支与upstream保持一致，然后在本地修改之后，提交到自己仓库的这个分支中，然后pull request把分支修改申请加入upstream。
目前我仓库是很久前fork，中间做过很多修改，一直没有与upstream同步，所以现在找不到办法在自己的仓库中创建一个和upstream一致的分支，所以不知道怎么提交request。

**Comment by zhxt** [comment]
@ahuer2435 

If I understand you correctly:
1. add upstream as a new remote for your fork;
    * cmd may looks like :
git remote add  upstream https://github.com/ApolloAuto/apollo.git
(let's just call the new remote name "upstream")
2. git fetch upstream;
3. git checkout  -b new_branch upstream/master

Now you get what you want, the branch new_branch(same as upstream/master) is now in your fork. 

Notice: After your PR has been accepted, your commit id may be changed in upstream branch base on upstream merge strategy.Some more attention should be paid for next PR.

More:
https://help.github.com/articles/syncing-a-fork/
https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

BTW, do we need to make the comments as doxygen type ?

**Comment by ycool** [comment]
doxygen style is preferred. Apollo doxygen link is at https://apolloauto.github.io/doxygen/apollo/

**Comment by zhxt** [comment]
Agree，even though I like qdoc more than deoxygen :-P

**Comment by Capri2014** [comment]
@ahuer2435 I went through your commits roughly and I believe your commits would help the community to better understand the code. --- Since we ourselves always have blank spot and did not explain to code into details as what we should have done.  

Look forward to your contributions!

**Comment by ahuer2435** [comment]
@zhxt thanks for your detail guide.
@Capri2014 @ycool I have send a pull request.

**Comment by JonathanJones92** [comment]
please  more comments !!!!!!!!!!!! Otherwise none will contribute to Apollo

**Comment by lxbeyond** [comment]
@ahuer2435  good job, your work help me a lot, thanks .

**Comment by natashadsouza** [comment]
Closing this issue as it has been inactive for a while. Feel free to open it should you have additional questions.
