### ISSUE TITLE
Apollo Meetup @ Sunnyvale, CA

### ISSUE THREAD

**Issue by Capri2014** [ApolloAuto/apollo#1685]
https://www.meetup.com/ApolloAuto/events/245651758/

To REALLY get hands on with Apollo ! XD:)

**Comment by gengqx** [comment]
Could you make it online,a webinar would be great for the developer all over the world .

**Comment by wckorealsh** [comment]
Yes, I think tons of developers are very interested in that, please open online access.

**Comment by Zhenni17** [comment]
hi @gengqx,  thank you for your question! For the upcoming meetup, we are not doing streaming and video recording. However, we are fully aware the need for more documentations and video tutorials and this will be one of our big initiatives for 2018. Please be patient with us, and we are working on some high quality content for you and the rest of the community and hopefully it will be helpful!
