### ISSUE TITLE
[How to Run Offline Perception Visualizer] CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by Durant35** [ApolloAuto/apollo#1687]
+ After successfully building `/apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool` following  [How to Run Offline Perception Visualizer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_offline_perception_visualizer.md) and https://github.com/ApolloAuto/apollo/issues/1683 ...
+ Running error
```sh
xxxxx@in_dev_docker:/apollo$ /apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool
....
....
I1208 14:23:26.679039 23459 net.cpp:94] Creating Layer input
I1208 14:23:26.679080 23459 net.cpp:402] input -> data
F1208 14:23:26.680850 23459 syncedmem.hpp:18] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
Aborted (core dumped)
```
### I need to install the CUDA driver?

**Comment by gengqx** [comment]
The cuda have install in the docker but the driver are not,so you need to install driver,the version recommended would be  375.39

**Comment by Durant35** [comment]
Thanks. Yes, follow here [How to Run Perception Module on Your Local Computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)
> **3.** Download the official Nvidia driver installation file which should be the exactly same version as the one installed in your host machine. We recommand the version of 375.39:

### need I also install the driver in my host machine???

**Comment by Capri2014** [comment]
@wanglei828 @jzhuucla

**Comment by gengqx** [comment]
In your host mochine ,you did not need to install cuda,but you need to install nvidia driver.I have not test whether if the host driver is 375.39 would make any difference.But I think most of the time,the host have installed nvidia driver,then you could just install a driver in docker,and use devicequery to test if it works well.

**Comment by jzhuucla** [comment]
That's right! It requires to install Nvidia driver in host machine. And for
the docker, by default we didn't install the driver but the CUDA is
pre-installed. You may install the driver as the same version of your
host's in docker. That's all. Please see the detailed steps on how to
install the Nvidia driver in docker from the doc:
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md

**Comment by gengqx** [comment]
Indeed,After I install apollo kernel,I have never success install driver by this code.
```
./NVIDIA-Linux-x86_64-375.39.run --no-opengl-files -a -s
```
this woul give that the driver did not support the realtime kernel.
@jzhuucla

**Comment by jzhuucla** [comment]
That's right! Because this installation method does not support the
customized Apollo Linux RT kernel. Actually, it can be installed with
standard linux kernel on your local computer. The Apollo RT kernel is
optimized for the hardware on the car. But it is good enough to use a
standard kernel for offline simulation on your local computer.

**Comment by Durant35** [comment]
### I think the root of the problem: too low version of gcc in **released dev docker image**
+ It's better to install the GPU driver by downloading corresponding _xxx.run_ driver according to your Nvidia GPU Model
+ **Step 1**: install Nvidia driver on your host machine
    + I installed it following [Ubuntu16.04+Cuda+Caffe安装](http://blog.csdn.net/u014593748/article/details/76528111)
    ```sh
    sudo ./NVIDIA-Linux-x86_64-384.98.run -no-x-check -no-nouveau-check -no-opengl-files
    ```
    + Check installation succeed?
    ```sh
    $ nvidia-smi
    # or (need to install CUDA) 
    $ cd /usr/local/cuda/samples/1_Utilities/deviceQuery
    # maybe need to make
    xxx@xxx:/usr/local/cuda/samples/1_Utilities/deviceQuery$ ./deviceQuery
    ./deviceQuery Starting...

     CUDA Device Query (Runtime API) version (CUDART static linking)

    Detected 1 CUDA Capable device(s)
    ...
    ```
+ **Step 2**: install Nvidia driver in the **released dev docker**
    + Using the same **xxx.run**, following [How to Run Perception Module on Your Local Computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)
    ```sh
    sudo ./NVIDIA-Linux-x86_64-384.98.run --no-opengl-files -a -s
    ```
    + Meet install error **cc: error: unrecognized command line option ‘-fstack-protector-strong’**: upgrade the gcc from `4.8.4` to `4.9.4` following [Ubuntu 14.04 LTS 下升级 gcc 到 gcc-4.9、gcc-5 版本](http://www.cnblogs.com/BlackStorm/p/5183490.html)
    + Check installation succeed? as mentioned above.

**Comment by GeorgeMD** [comment]
I get the exact same error, but I don't have an nVidia GPU. Is there anything I can do to make this work?

**Comment by Durant35** [comment]
I think，no...
