### ISSUE TITLE
Any idea to finish a technical paper about ApplloAuto??

### ISSUE THREAD

**Issue by chibai** [ApolloAuto/apollo#17]
So when we use your tool in the paper, we can cite it.

**Comment by lyuwenyu** [comment]
It is a good suggestion. Waiting for a paper

**Comment by pxlong** [comment]
+1

**Comment by startcode** [comment]
Now we don't have a technical paper yet. However, now you are welcome to cite the Apollo by the URL.
Here are citation examples:

-------for latex-------
@misc{apollo,
  title = {{Apollo: An open autonomous driving platform}},
  howpublished = "\url{https://github.com/ApolloAuto/apollo}",
  year = {2017}
}
---- for MS Word--------
Apollo: An open autonomous driving platform. https://github.com/ApolloAuto/apollo

**Comment by startcode** [comment]
Hi, 
Thanks for your interest in Apollo.
Right now we don't have technical paper, but you are welcome to cite Apollo through the link.
Here are citation examples:
 ----For Latex with BibTex----
@misc{apollo,
  title = {{Apollo}: an open autonomous driving platform},
  howpublished  ={\url{https://github.com/ApolloAuto/apollo}},
  year={2017}
}
---- For MS Word----
Apollo: An open autonomous driving. https://github.com/ApolloAuto/apollo
