### ISSUE TITLE
how Can I set the log level to output ADEBUG information.

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#1702]
I see a lot of code are using log "ADEBUG',
I can find "INFO","WARNING","ERROR","FATAL",but no “DEBUG”，and I Could not find anything in log related to ADEBUG

**Comment by lianglia-apollo** [comment]
Please use - -v=4 for DEBUG

**Comment by lianglia-apollo** [comment]
It is defined in apollo/modules/common/log.h

**Comment by gengqx** [comment]
I'm sorry I still don't understand how to use it or define it.

**Comment by ycool** [comment]
e.g. if you want to see ADEBUG in planning module, modify modules/planning/conf/planning.conf and add one line: --v=4, it will print out all ADEBUG. You can set --vmodule=filename=4 to print just ADEBUG in that filename.

**Comment by fanghaos2014** [comment]
Hi, I  change the --v in the conf. But still, I haven't got any output for the ADEBUG. Thank you.

**Comment by glebkiselev** [comment]
Hi! How do I add Debug info to log files in Apollo 6? I have already add 
# --debug level
--vmodule=piecewise_jerk_path_optimizer=4 
In bottom of planning.conf fileinside the docker, but nothing happened. I tried to restart the docker and run apollo in debug mode, but there are still no debug info inside planning.
