### ISSUE TITLE
Install Nvidia driver in docker failed ! [ How to Run Perception Module on Your Local Computer ]

### ISSUE THREAD

**Issue by FightStone** [ApolloAuto/apollo#1704]
ERROR: An NVIDIA kernel module 'nvidia-drm' appears to already be loaded in your kernel.  This may be because it is in use (for example, by an X server, a CUDA program, or the NVIDIA Persistence Daemon), but this may also happen if your kernel was configured without support for module unloading.  Please be sure to exit any programs that may be using the GPU(s) before attempting to upgrade your driver.  If no GPU-based programs are running, you know that your kernel supports module unloading, and you still receive this message, then an error may have occured that has corrupted an NVIDIA kernel module's usage count, for which the simplest remedy is to reboot your computer.

ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

What should i do ? 
Thanks !

**Comment by FightStone** [comment]
Prepare PCD and pose data ! 
When I play the bag ,there are some problems as follow : 

[velodyne_nodelet_manager-2] process has died [pid 17470, exit code -4, cmd /home/tmp/ros/lib/nodelet/nodelet manager __name:=velodyne_nodelet_manager __log:=/home/stone/.ros/log/bb0eddb2-de65-11e7-87cd-e0cb4eb812b6/velodyne_nodelet_manager-2.log].
log file: /home/stone/.ros/log/bb0eddb2-de65-11e7-87cd-e0cb4eb812b6/velodyne_nodelet_manager-2*.log
/tmp/apollo-platform/ros/nodelet_core/nodelet/src/nodelet.cpp:341 main() [ INFO] [1512991558.996374281]: Bond broken, exiting
/tmp/apollo-platform/ros/nodelet_core/nodelet/src/nodelet.cpp:341 main() [ INFO] [1512991559.249598201]: Bond broken, exiting
[sensor_velodyne64_convert-3] process has finished cleanly
log file: /home/stone/.ros/log/bb0eddb2-de65-11e7-87cd-e0cb4eb812b6/sensor_velodyne64_convert-3*.log
[sensor_velodyne64_compensator-4] process has finished cleanly
log file: /home/stone/.ros/log/bb0eddb2-de65-11e7-87cd-e0cb4eb812b6/sensor_velodyne64_compensator-4*.log
[pcd_exporter_nodelet-5] process has finished cleanly
log file: /home/stone/.ros/log/bb0eddb2-de65-11e7-87cd-e0cb4eb812b6/pcd_exporter_nodelet-5*.log



What would i do? Thanks .
Please!

**Comment by ytzhao** [comment]
@FightStone Hi, I've also met the same problem you've mentioned about the NVIDIA driver installation on docker, how do you address this problem? Thank you very much! :)

**Comment by Durant35** [comment]
@FightStone Have you solved this problem? and how? Thanks a lot!

**Comment by basser2** [comment]
@FightStone Have you solved this problem? and how? Thanks a lot!
![image](https://user-images.githubusercontent.com/42443887/54613396-97ddf880-4a95-11e9-9d8a-f5aad7361152.png)
