### ISSUE TITLE
run demo: docker/scripts/release_start.sh but  blocked (运行阻塞了)

### ISSUE THREAD

**Issue by luckdsfy** [ApolloAuto/apollo#171]
i use vmware, ubuntu14.04.
I have successfully install docker. then follow the docs in the demo_guide directory.
when run docker/scripts/release_start.sh
It can successfully download many files.  then run to tell me type 'y' to agree licence. when i type 'y' , it block（ 阻塞在那里了）
then I quit by CTRL_C  and run   "docker/scripts/release_start.sh but  blocked"   again.
AS follow:
root@ubuntu:/opt/APOLLO/apollo-master# bash docker/scripts/release_start.sh
APOLLO_ROOT_DIR=/opt/APOLLO/apollo-master
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)_
apollo_release
apollo_release
/opt/APOLLO/apollo-master/data/core/core_%e.%p
[WARNING] Failed to find device with pattern "ttyUSB*" ...
[ OK ] Found device: /dev/ttyS31.
[ OK ] Found device: /dev/ttyS30.
[ OK ] Found device: /dev/ttyS29.

why?

**Comment by luckdsfy** [comment]
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

how to resolve?

**Comment by startcode** [comment]
@wanglei828 can you help double check the "BLOCK" issue?
@luckdsfy your second problem looks like a network connection problem.

**Comment by wanglei828** [comment]
This problem has been fixed. please pull the latest code.

**Comment by luckdsfy** [comment]
@wanglei828   I down the latest code and It runs ok now.
but:
when i run:
  rosbag play docs/demo_guide/demo.bag --loop   
fail msg:  bash: rosbag: command not found

how to resolve?

**Comment by wanglei828** [comment]
Are you running the rosbag command in docker or not? If in docker, the rosbag command should work fine. I just tried in my machine.

**Comment by startcode** [comment]
If you are not in docker, you can try source the `ros/setup.bash` by
```
source bazel-apollo/external/ros/setup.bash
```
And see if command `rosbag` works or not.

**Comment by luckdsfy** [comment]
@wanglei828   I follow　the readme in   apollo-master\apollo-master\docs\demo_guide  step by step?

how to  running the rosbag command in docker ?
any tip in the readme?
 why rosbag command not founded?

**Comment by wanglei828** [comment]
You can follow these steps:
1) ./docker/scripts/dev_start.sh
2) ./docker/scripts/dev_into.sh
3) rosbag play docs/demo_guide/demo.bag --loop

**Comment by luckdsfy** [comment]
I run the demo, follow the readme in apollo-master\apollo-master\docs\demo_guide:
./docker/scripts/release_start.sh
./docker/scripts/release_into.sh
rosbag play docs/demo_guide/demo.bag --loop

**Comment by luckdsfy** [comment]
@wanglei828 
I try  

./docker/scripts/dev_start.sh
./docker/scripts/dev_into.sh
rosbag play docs/demo_guide/demo.bag --loop

the same fail message:  bash: rosbag: command not found

Is  something i have not install ?
how to install rosbag command ?

**Comment by wanglei828** [comment]
@luckdsfy  In dev docker, If you have never built apollo repo,  ros package will not be downloaded into your environment.  
Please follow this way:
1. ./docker/scripts/dev_start.sh
2. ./docker/scripts/dev_into.sh
3. ./apollo.sh build
4.  source scripts/apollo_base.sh

**Comment by Trinivox** [comment]
^ This works. Thanks
