### ISSUE TITLE
"apollo.sh release" error without related driver

### ISSUE THREAD

**Issue by chucklqsun** [ApolloAuto/apollo#1717]
when ran "apollo.sh release" on master branch, got below copy errors.

It seems delphi_esr and mobileye drivers are not included in master branch. Is there any solution or plan w.r.t merging branch "mobileye_radar" to "master" ?
-------------------------------------------------------------------------
cp: cannot stat 'bazel-bin/modules/drivers/delphi_esr/delphi_esr': No such file or directory
cp: cannot stat 'modules/drivers/delphi_esr/conf': No such file or directory
cp: cannot stat 'bazel-bin/modules/drivers/mobileye/mobileye': No such file or directory
cp: cannot stat 'modules/drivers/mobileye/conf': No such file or directory

**Comment by gengqx** [comment]
This did not report errors,and if you did not run in a real car,it would have no influence,you still can realease a new version and gen a new docker.

**Comment by chucklqsun** [comment]
got it. thx!
