### ISSUE TITLE
undefined reference to 'tls13_server_handshake'

### ISSUE THREAD

**Issue by zwqaoy** [ApolloAuto/apollo#174]
ERROR: /apollo/modules/hmi/ros_node/BUILD:3:1: Linking of rule '//modules/hmi/ros_node:ros_node_service' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-dbg/bin/modules/hmi/ros_node/ros_node_service '-Wl,-rpath,$ORIGIN/../../../_solib_k8/_U@ros_S_S_Cros_Ucommon___Uexternal_Sros_Slib' ... (remaining 8 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/boringssl/boringssl-master-with-bazel/src/ssl/handshake_server.cc:778: error: undefined reference to 'tls13_server_handshake'

**Comment by siyangy** [comment]
duplicate of #166

**Comment by zwqaoy** [comment]
duplicate of #166
