### ISSUE TITLE
Some libraries are only inside docker

### ISSUE THREAD

**Issue by Eddy-W** [ApolloAuto/apollo#1751]
I have found two dependencies are only in docker, not in github repo.
1. liblocalization_msf_local_integ.so referenced by bazel external dep local_integ.
2. libcaffe.so.1.0 referenced by light detection in perception module.  This version is not offical caffe version, and implemented additional layers, e.g. `caffe/layers/pyramid_layers.hpp` etc.

Are those dependencies not open source? If not,  where can I find those and build from source code. Thanks.

**Comment by mickeyouyou** [comment]
@startcode

**Comment by startcode** [comment]
@yellowpoplar  can you help share the open-source plan of liblocalization_msf_local_integ.so?
@ghdawn can you help share the open-source plan of libcaffe.so.1.0 
Thank you all

**Comment by yellowpoplar** [comment]
liblocalization_msf_local_integ.so is related to multi-sensor fusion localization algorithm and is not open-source in Apollo 2.0 unfortunately.

**Comment by Eddy-W** [comment]
Thank you .

**Comment by yongyuandeyezi** [comment]
@Eddy-W Do you find a solution of open-source libcaffe.so.1.0
I have the same question of you
I couldn't find the file"caffe/layers/pyramid_layers.hpp"

**Comment by cjjsaic** [comment]
@yongyuandeyezi @Eddy-W Some for me. Why not open source the caffe module?

**Comment by ghdawn** [comment]
We're not ready to open source the caffe module in Apollo 2.0. Please wait for the Apollo 2.5 :)
