### ISSUE TITLE
Preparing Image for simulation

### ISSUE THREAD

**Issue by LunaAmour** [ApolloAuto/apollo#1752]
I am a little unclear on the workflow to correctly generate a docker image and upload to the Dreamland simulation platform. Following the guidance in the How To Build and Release, I believe I have correctly generated a release image.

On the Dreamland user manual there is a process described to commit a new docker image. In the directions, it describes logging into a specific Apollo docker registry and pulling down the base docker image, then modifying it with a "sim_op" directory and a few other items, and then doing a commit of that modified image.

Given this, it is confusing to me how I would upload my own generated image. Also, while the user manual describes the main elements that need to be modified to get an image to run in Dreamland I can't seem to find a full example of the modifications (even when I pull the base image from the server referred to in the user manual it does not contain these folders/files). I'm relatively new to both Apollo and docker so if anyone can help walk me through the process to even take an unmodified image of the Apollo release and just download, generate, and upload to Dreamland for testing it would be very helpful.

**Comment by timboilermaker** [comment]
Hi LunaAmour, thank you for using dreamland.  We are going to release a new version of dreamland at the beginning of Jan, 2018, which allows you to deploy your code by entering a github url and a branch name.  So it would be much more convenient then and no image or binary is needed.

**Comment by LunaAmour** [comment]
Hi Tim,


  That is fantastic news, and should be very useful for our further development. I will look forward to seeing the new version. Will there be an official announcement when it is released and a readme on how to use the new options?


Cheers,


Alex

________________________________

**Comment by Zhenni17** [comment]
Hi Alex,

There will be an official announcement. New update will be announced during Baidu AI Create at Las Vegas on Jan 8th, 2018. If you and your colleagues will go to CES 2018, we would love to extend our invite to Apollo developers like you.

Here is the link to the event registration if you are interested in attending: [https://www.eventbrite.com/e/baidu-ai-create-at-las-vegas-tickets-41091507806]

Please let me know if you have any additional question about the event. Hope we can see you there!

Best,
Zhenni

Community Manager of Apollo

**Comment by LunaAmour** [comment]
Thanks for the link! I'll see if I can personally make it and will certainly check if we will have a rep there.

**Comment by Zhenni17** [comment]
Sounds good! Feel free to share the link to your colleagues or any other Apollo developers that might be interested! :)
