### ISSUE TITLE
bash docker/scripts/dev_start.sh install error

### ISSUE THREAD

**Issue by shophome** [ApolloAuto/apollo#176]
michah@michah:~/下载/apollo$ bash docker/scripts/dev_start.sh

THE APOLLO OPEN PLATFORM (“PLATFORM”) FOR AND ON BEHALF OF ITSELF AND ITS SUBSIDIARIES AND AFFILIATES UNDER COMMON CONTROL, IS WILLING TO LICENSE THE SOFTWARE TO YOU ONLY UPON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS CONTAINED IN THIS LICENSE AGREEMENT ("AGREEMENT"). PLEASE READ THE AGREEMENT CAREFULLY. BY SELECTING THE "ACCEPT LICENSE AGREEMENT" (OR THE EQUIVALENT) BUTTON AND/OR BY USING THE SOFTWARE YOU ACKNOWLEDGE THAT YOU HAVE READ THE TERMS AND AGREE TO THEM. IF YOU ARE AGREEING TO THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO BIND THE LEGAL ENTITY TO THESE TERMS. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT WISH TO BE BOUND BY THE TERMS, THEN SELECT THE "DECLINE LICENSE AGREEMENT" (OR THE EQUIVALENT) BUTTON AND YOU MUST NOT USE THE SOFTWARE ON THIS SITE OR ANY OTHER MEDIA ON WHICH THE SOFTWARE IS CONTAINED.
1. DEFINITIONS. "Software" means the software identified above in binary form that you selected for download, install or use (in the version You selected for download, install or use) from Baidu or its authorized licensees, any other machine readable materials (including, but not limited to, libraries, source files, header files, and data files), any updates or error corrections provided by Baidu, and any user manuals, programming guides and other documentation provided to you by Baidu under this Agreement.
2. LICENSE GRANT: Subject to the terms and conditions of this Agreement, with the exception of different license terms and license grants for separate, individual third-party components as set forth below, the Software is licensed to you under the terms of the Apache 2.0 license available at:  https://www.apache.org/licenses/LICENSE-2.0.  You agree to these terms with respect to the Software.
3. THIRD PARTY CODE:  Additional copyright notices and license terms applicable to portions of the Software are set forth below in Appendix A.  You expressly agree to the license terms associated with third party code set forth in Appendix A.  In addition to any terms and conditions of any third party license identified in Appendix A, the disclaimer of warranty and limitation of liability provisions in paragraphs 4 and 5 of this License Agreement shall apply to all Software in this distribution.  YOU EXPRESSLY AGREE THAT YOU HAVE REVIEWED THE TERMS OF THE AGREEMENTS LINKED TO AND RESTATED IN APPENDIX A TO THIS AGREEMENT, AND THAT YOU AGREE TO THE TERMS OF THOSE AGREEMENTS.
4. DISCLAIMER OF WARRANTY. THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. BAIDU FURTHER DISCLAIMS ALL WARRANTIES, EXPRESS AND IMPLIED, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
5. LIMITATION OF LIABILITY. IN NO EVENT SHALL BAIDU BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, DATA OR DATA USE, INCURRED BY YOU OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT, EVEN IF BAIDU HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. BAIDU’S ENTIRE LIABILITY FOR DAMAGES HEREUNDER SHALL IN NO EVENT EXCEED ONE ONE CENT (U.S. $0.01).

Copyright (c) 2017 Various License Holders. All Rights Reserved

Apollo software is built on top of various other open source software packages, a complete list of licenses are located at https://github.com/ApolloAuto/apollo/blob/master/third_party/ACKNOWLEDGEMENT.txt

You agree to the terms of all the License Agreements.

Type 'y' or 'Y' to agree to the license agreement above, or type any other key to exit

**Comment by startcode** [comment]
What is the error detail?
Thank you.

**Comment by shophome** [comment]
@startcode  yes

**Comment by startcode** [comment]
I don't know what is the issue.

**Comment by rajibahmed** [comment]
press Y or y when you see the screen and press enter.

**Comment by shophome** [comment]
@rajibahmed think you
