### ISSUE TITLE
[Question] switch "use_full_cloud" for CNN segmentation in 3D Obstacle Perception

### ISSUE THREAD

**Issue by chucklqsun** [ApolloAuto/apollo#1767]
The switch "use_full_cloud", which default value is True, are used for "If it is set by true, all the points of the original point cloud will be used for extracting channel features. Otherwise only the points of input point cloud (i.e., the points after HDMap ROI filter) are used."

My question is, why use True as default value? Does that mean HDMap ROI is totally useless under this setting? (To my understanding, in this module, ROI is only used for extracting channel feature)

**Comment by natashadsouza** [comment]
Sorry we could not get back to you on this request. Please let me know if you still need support on your request. Feel free to re-open the issue.
