### ISSUE TITLE
bootstrap cannot launch module monitor & dreamview

### ISSUE THREAD

**Issue by kkyiss** [ApolloAuto/apollo#1768]
I just clone the newest code this morning and started the build command in dev docker
`kkyiss@in_dev_docker:/apollo$ bash apollo.sh build`

it showed build passed!
but with some info
`apollo.sh: line 108: 5508 Illegal instruction  (core dumped) bazel-bin/modules/data/util/update_task_info --commit_id=$(git rev-parse HEAD)`

Then when i run 
`bash scripts/bootstrap.sh`

it shows:
`Start roscore...`
`Could not launch module monitor. Is it already built?`
`Could not launch module dreamview. Is it already build?`
`Dreamview is running at http://localhost:8888`

but the webpage shows unable to connect
anyone have the same problem?
any hints will be appreciate
tks

**Comment by xiaoxq** [comment]
The build looks incomplete.
There should be some abnormal logs when you run "apollo.sh build". Would you please post it here?

**Comment by kkyiss** [comment]
@xiaoxq  tks for the quick reply
![1](https://user-images.githubusercontent.com/33953348/33977846-ceef09be-e0d7-11e7-9e79-f9ba3c2c526c.PNG)

in /data/log directory, there are three logs (dreamview.out, monitor.out, roscore.out)
but they are all empty

**Comment by xiaoxq** [comment]
Could you check if the file bazel-bin/modules/data/util/update_task_info exists?
And plz show the output of "git status".

**Comment by kkyiss** [comment]
Yes, the update_task_info do exists

![1](https://user-images.githubusercontent.com/33953348/33978500-ff6a2ac6-e0da-11e7-9fdd-6aa66453e397.PNG)

**Comment by xiaoxq** [comment]
Then could you show me the output of
```bash
git status
git rev-parse HEAD
./bazel-bin/modules/data/util/update_task_info --commit_id=1
```

**Comment by kkyiss** [comment]
it tells

> error while loading shared libraries: libactionlib.so: cannot open shared object file:
No such file or directory

![1](https://user-images.githubusercontent.com/33953348/33979653-51ab2bc8-e0e0-11e7-91c8-74d7d49db005.PNG)

**Comment by gazige1981** [comment]
restart your pc , and rebuild the apollo.sh , then it will work ok

**Comment by xiaoxq** [comment]
It's a library from ROS, located at /home/tmp/ros/lib/libactionlib.so
Then I guess you are running new code on an old docker image. They don't match.

Just start a new container with ./docker/scripts/dev_start.sh

**Comment by kkyiss** [comment]
@gazige1981 : tks  I restart my pc, but it's not working
@xiaoxq : I just remove the old docker container by
> docker rm contain-id

and starting a new one
> bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash apollo.sh build
bash scripts/bootstrap.sh

and the build info still show the same, also bootstrap not running dreamview

I found the libactionlib.so on docker path /home/tmp/ros/lib
Since i am running a new docker image, is there any ways to know how to match them?

**Comment by xiaoxq** [comment]
Then how about the env $LD_LIBRARY_PATH?
In my system it contains "/home/tmp/ros/lib", which makes the "libactionlib.so" findable.

**Comment by kkyiss** [comment]
my system contains "/home/tmp/ros/lib" too

`kkyiss@in_dev_docker:/apollo$ echo $LD_LIBRARY_PATH`
`/usr/local/cuda-8.0/lib64: /home/tmp/ros/lib: /apollo/lib: /apollo/bazel-genfiles/external/caffe/lib`

that the "libactionlib.so" file is under the directory "/home/tmp/ros/lib/"

**Comment by xiaoxq** [comment]
Well, that's really weird. To my knowledge it couldn't happen like that.
Thank you for your report and we'll keep investigating. If you have any findings please also let us know!

**Comment by kkyiss** [comment]
tks @xiaoxq  being patient
Ill try in another PC too

**Comment by gengqx** [comment]
I have the same issue，It very simple to deal with it,but I have not found the reason
```
bash apollo.sh clean
bash apollo.sh build
```

**Comment by kkyiss** [comment]
@gengqx 
i've already tried but the same result
Would you mind to tell me which commit version you are using
tks

**Comment by gengqx** [comment]
@kkyiss  I you did not do too much code in your workspace, I stronglly suggest that you pull a newest master version ,build ,and open it .it should work.
I have try many version,but the same issue show in
```
Commit: f6f0cf0e3845e649183963541e53a8b6a03f5368
Date: Thu Dec 14 19:55:10 2017 -0600
```

**Comment by mickeyouyou** [comment]
Compile time is too short, does not meet the normal situation. **Just delete the container is not enough, you also need to delete the Image**， Follow these steps to perform, you can properly solve this problem:

- docker rm [container id]
- docker rmi [image id]
- git pull origin master
- bash docker/scripts/dev_start.sh
- bash docker/scripts/dev_into.sh
- bash apollo.sh build

**Comment by kkyiss** [comment]
Thanks @gengqx  
with apollo.sh clean & build
now I can launch the module & dreamview

But  like #1907 
I cannot access 
`http://localhost:8888`


@mickeyouyou 

> Compile time is too short, does not meet the normal situation.

because i have already compiled before i screenshot the result.
The first compile time is 1317 seconds
and yes i did remove the docker images & container
but somehow still have problem about accessing localhost:8888
tks

**Comment by mickeyouyou** [comment]
If your situation is the same as #1907, using the above steps can be solved. can you try again ？

**Comment by kkyiss** [comment]
@mickeyouyou 
I tried but the problem is not solved.
weird

**Comment by JKTesla** [comment]
@kkyiss 
**Where** did you clone the newest Apollo's code in your folder？
And ... **how** did you deal with your old Apollo's code?

**Comment by kkyiss** [comment]
@JKTesla  I created a directory named /work under /home/user/
just deleted the old apollo directory

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved. Feel free to open it if the issue persists.

**Comment by 1024zp** [comment]
this issue is due to monitor  does not build  in the modules directory, in this case, can not find the dynamic file (libmonitor.so) when dreamview launch modules. One solution is  'bazel build //path/to:monitor', then you got it.
