### ISSUE TITLE
Going to CES? Join us at Baidu AI Create at Las Vegas - Jan 8th, Mandarin Oriental Hotel

### ISSUE THREAD

**Issue by Zhenni17** [ApolloAuto/apollo#1799]
You are cordially invited to join us at Baidu’s launch event at 2pm on January 8 in Las Vegas. Qi Lu, Baidu’s COO and Group President, will take the stage at the event to showcase amazing new technology innovations and unveil the latest open autonomous driving platform by Baidu. 

Beyond this event, Baidu will also have two booths (25308 and 7913) at Tech East exhibiting its latest voice-enabled products and autonomous driving technologies. 

Location:

Mandarin Oriental at City Center Las Vegas

3752 Las Vegas Boulevard South Las Vegas, NV, USA

Time:

2:00-4:00pm, Jan 8, 2018 (Registration starts at 1pm)

To register this free event: [https://apolloauto20.eventbrite.com]

See you there!

**Comment by chucklqsun** [comment]
Cannot fly to US. Expect live video.

**Comment by Zhenni17** [comment]
Just in case you are still looking for the event's recording video, here is the link: https://www.youtube.com/watch?v=4HCkGDouwLY&t=2s. Follow us on Twitter @ApolloPlatform for more Apollo updates!
