### ISSUE TITLE
How to Run Offline Perception Visualizer

### ISSUE THREAD

**Issue by gazige1981** [ApolloAuto/apollo#1831]
hi
I want to run offline perception visualizer on VMware,but it stay at line
et::onInit() [ INFO] [1513393804.984149107]: Point cloud nodelet init
and cannot go forward

![visualizer](https://user-images.githubusercontent.com/33610173/34066967-34876384-e254-11e7-950b-b2bab1b19e57.png)

the command looks follow:
cd apollo
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
roslaunch velodyne export_pcd_offline.launch

and the file
how_to_run_offline_perception_visualizer.md
doesn't update
the file export_pcd.launch
doesn't exist

**Comment by chucklqsun** [comment]
Were you running rosbag to play demo without point cloud data ? such as Apollo1.5_demo.bag from apollo auto website.

**Comment by gazige1981** [comment]
I haven't running rosbag
![lidar](https://user-images.githubusercontent.com/33610173/34067539-a1b995f8-e263-11e7-94b5-6138c399c4c7.png)

**Comment by gazige1981** [comment]
I haven't running the rosbag yet
![image](https://user-images.githubusercontent.com/33610173/34067569-78ccc4f2-e264-11e7-9af6-c1a89c8d8149.png)

**Comment by chucklqsun** [comment]
You can open a new terminal and get into the dev dock and run the rosbag. It will go forward after receiving the message from rosbag.

**Comment by gazige1981** [comment]
ok thanks . it works 
but there is another problem as follows
![lidar0](https://user-images.githubusercontent.com/33610173/34068316-9735e842-e273-11e7-8d24-97ab9301e5bf.png)
 there is no PCD files be dumped to the export directory (defalut: /apollo/data/pcd)

the rosbag lidar_calib.bag is downloaded from apollo open data platform
![lidar1](https://user-images.githubusercontent.com/33610173/34068327-eacf99ee-e273-11e7-85a3-39c8c389b7ac.png)

**Comment by chucklqsun** [comment]
PCD is point cloud data. You can use the “传感器样例数据”(~8.93G), which includes the LiDAR data (point cloud data).

**Comment by Durant35** [comment]
https://github.com/ApolloAuto/apollo/issues/1682

**Comment by gazige1981** [comment]
ok , thanks
