### ISSUE TITLE
Failed to get into dreamview, how to deal with it??

### ISSUE THREAD

**Issue by Jasonsun1993** [ApolloAuto/apollo#1840]
Build passed, the monitor module and dreamview module loaded. But cannot connect to localhost:8888. What can I do with it?

**Comment by gengqx** [comment]
first check dreamview.error in the data/log to see if there is anything wrong.

**Comment by Jasonsun1993** [comment]
`/apollo/scripts/apollo_base.sh: line 220:   307 Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/monitor/monitor --flagfile=modules/monitor/conf/monitor.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/monitor.out 2>&1
/apollo/scripts/apollo_base.sh: line 220:   312 Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/dreamview.out 2>&1`
@gengqx The above appeared in the log file. What is the problem?

**Comment by mickeyouyou** [comment]
Compile time is too short, does not meet the normal situation. **Just delete the container is not enough, you also need to delete the Image**， Follow these steps to perform, you can properly solve this problem:

- docker rm [container id]
- docker rmi [image id]
- git pull origin master
- bash docker/scripts/dev_start.sh
- bash docker/scripts/dev_into.sh
- bash apollo.sh build

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while.
