### ISSUE TITLE
libGL error while running offline_lidar_visualizer_tool

### ISSUE THREAD

**Issue by MEIXuYan** [ApolloAuto/apollo#1844]
1 I'm trying apollo on my desktop,which has ubuntu 16.04.3 along with Win 10.

2 After updating gcc from v4.8.4 to v4,9.4,I successfully installed Nvidia driver on docker dev container and host machine,run nvidia-smi:(my another issue #1750 ）
```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.82                 Driver Version: 375.82                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 0000:01:00.0     Off |                  N/A |
| N/A   42C    P0    N/A /  N/A |      0MiB /  4041MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

3 I have downloaded the Apollo1.5_demo.bag(9.6G),translated them into PCD and generated pose files

4 When I run `/apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool`,some error occured:

```
I1218 22:03:31.135429   242 kalman_filter.cc:38] use adaptive of KalmanFilter is 1
I1218 22:03:31.135432   242 kalman_filter.cc:45] association score maximum of KalmanFilter is 4
I1218 22:03:31.135437   242 kalman_filter.cc:90] measurment noise of KalmanFilter is 0.4
I1218 22:03:31.135440   242 kalman_filter.cc:91] initial velocity noise of KalmanFilter is 5
I1218 22:03:31.135443   242 kalman_filter.cc:93] propagation noise of KalmanFilter is
10 00 00
00 10 00
00 00 10
I1218 22:03:31.135478   242 kalman_filter.cc:57] breakdown threshold maximum of KalmanFilter is 10
I1218 22:03:31.135484   242 lidar_process.cc:284] Init algorithm plugin successfully, tracker: HmObjectTracker
I1218 22:03:31.135499   242 glfw_viewer.cc:64] GLFWViewer::initialize()
libGL error: pci id for fd 33: 8086:591b, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: i965
I1218 22:03:31.322856   242 opengl_visualizer.cc:44] Initialize OpenglVisualizer successfully
I1218 22:03:31.322890   242 offline_lidar_visualizer_tool.cc:77] starting to run
I1218 22:03:31.608429   242 offline_lidar_visualizer_tool.cc:80]  pose size 3473
I1218 22:03:31.608448   242 offline_lidar_visualizer_tool.cc:81]  pcd size 3475
E1218 22:03:31.608449   242 offline_lidar_visualizer_tool.cc:83] pcd file number does not match pose file number

```
Does someone know how to solve this?

**Comment by gengqx** [comment]
I think the main reason is the pcd_exporter have some issue that it would not guarantee that the pose txt file write appropriately. So here we just delete the last three pcd  files and the last one pose files. This would make the numbers of files match,then let‘s see what happened.

**Comment by xiaohuitu** [comment]
First make sure the numbers of pose and pcd files are equal, and each pose and pcd file are matched. Then try to run `/apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool` again.

**Comment by MEIXuYan** [comment]
@gengqx @xiaohuitu Thank you for your advice,it solves my problem.But base on the picture showing below,it seems that the pcd files and the pose files do not match very well.
![image](https://user-images.githubusercontent.com/16874175/34154213-aa794862-e4ef-11e7-8555-3c0227db7f13.png)
 Do you guys know what cause the  numbers of pose and pcd files not equal?

**Comment by xiaohuitu** [comment]
@MEIXuYan You can have a look at the timestamp recorded in the pcd and pose file to see if they are matched. Ps, how do you solve the libGL error you met before?

**Comment by Prasan03** [comment]
Hi everyone,

Is it possible to run the offline-Perception-visualizer as per [this](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_offline_perception_visualizer.md) without a Nvidia GPU but just on a normal laptop with Intel HD Graphics?

Regards,
Prasan

**Comment by xiaohuitu** [comment]
@Prasan03 You can build the tool without GPU by the command `bazel build -c opt //modules/perception/tool/offline_visualizer_tool:offline_lidar_visualizer_tool` , then run it.

**Comment by xiaohuitu** [comment]
And the libGL error could be solved by reinstalling the NVIDIA driver with the command `./NVIDIA-Linux-x86_64-375.39.run --no-opengl-files -a -s`. Note `--no-opengl-files -a -s` is necessary for fix the libGL error. Please refer to #2362

**Comment by JonathanJones92** [comment]
@Prasan03 Hi dude,
running the off-line perception without GPU, have you ever been successful?
Iḿ working on it rit-now.

regards,
John

**Comment by techoe** [comment]
Xiaohuitu's solution should work. If the problem still exist please let us know.  Thank you.
