### ISSUE TITLE
The NVIDIA driver does not support real-time kernels.

### ISSUE THREAD

**Issue by Wsine** [ApolloAuto/apollo#1872]
I follow the [apollo_1_5_hardware_system_installation_guide.md](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_5_quick_start.md) to install apollo with both apollo-kernel and nvidia-driver.

```
wsine@hostname:~/Downloads$ ls
linux-4.4.32-apollo-1.5.0.tar.gz  NVIDIA-Linux-x86_64-375.39.run 
wsine@hostname:~/Downloads$ uname -a
Linux sensetime-MS-7A71 4.4.32-apollo-2-RT #2 SMP PREEMPT RT Wed Sep 20 11:45:34 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
wsine@hostname:~/Downloads$ sudo bash ./NVIDIA-Linux-x86_64-375.39.run --no-x-check -a -s
[sudo] password for weizhengyuan: 
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 375.39.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

ERROR: The kernel you are installing for is a PREEMPT_RT kernel!
       
       The NVIDIA driver does not support real-time kernels. If you 
       are using a stock distribution kernel, please install 
       a variant of this kernel that does not have the PREEMPT_RT 
       patch set applied; if this is a custom kernel, please 
       install a standard Linux kernel.  Then try installing the 
       NVIDIA kernel module again.


ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver
       download page at www.nvidia.com.

```

**Comment by gengqx** [comment]
If you did not run in real car,I suggest that there no need to install real-time kernel.
But if you really need it ,try this file.
```
https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/install-nvidia.sh
```

**Comment by Wsine** [comment]
i do run in a real car, thus i need it. it works, thanks very much. recommend to update the installation guide.

**Comment by Jasonsun1993** [comment]
@gengqx @Wsine Is the NVIDIA-Linux-x86_64-375.39.run in the file install-nvidia.sh you recommended above only matched with 1080Ti? If it is, how to install other Nvidia drivers(like GTX1050) in Apollo real-time kernels?

**Comment by gengqx** [comment]
No，it works on others cards. My card is GTX1050Ti

**Comment by Wsine** [comment]
@Jasonsun1993 I tested on both 1050 and 1080 cards. they works.

**Comment by turinglife** [comment]
here is my another solution to this problem.
https://github.com/ApolloAuto/apollo/issues/2595

**Comment by Capri2014** [comment]
@turinglife Could you create a PR and checkin your solution in Q&A section like in here ? https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md Thanks.

**Comment by qianyichen1987** [comment]
@gengqx 
My laptop has GT540M(a little bit of old), after installed nvidia driver the following script based on RT kernel:
https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/install-nvidia.sh

The display resolution is not correct, the nvidia driver  390.25 is working fine before upgrade the RT kernel,  is it normal with wrong display resolution?

BR,
Thanks.

**Comment by qianyichen1987** [comment]
My laptop has GT540M(a little bit of old), after installed nvidia driver the following script based on RT kernel:
https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/install-nvidia.sh

The display resolution is not correct, the nvidia driver  390.25 is working fine before upgrade the RT kernel,  is it normal with wrong display resolution?

BR,
Thanks.

**Comment by linux-devil** [comment]
@gengqx bit off topic , can you recommend any laptop that will be good to run apollo in the real car environment ?

**Comment by zhangtianzi** [comment]
Hi, @gengqx @Wsine ,my card is 1050ti, I use the " install-nvidia.sh " and the terminal print: "successfully install" , but the screen resolution is still very very slow

**Comment by zhangtianzi** [comment]
Hi, @gengqx @Wsine ,my card is 1050ti, I use the " install-nvidia.sh " and the terminal print: "successfully install" , but the screen resolution is still very very slow（the nvidia card still does not work）.how should  I do?

**Comment by zhangtianzi** [comment]
After executing "nvidia-smi", the terminal showed "failed to initialize NVML: Driver/library version mismatch".

**Comment by zhangtianzi** [comment]
Hi, @gengqx @Wsine ,my card is 1050ti, I use the " install-nvidia.sh " and the terminal print: "successfully install" , but the screen resolution is still very very slow（the nvidia card still does not work）.
After executing "nvidia-smi", the terminal showed "failed to initialize NVML: Driver/library version mismatch". how should I do?

 Looking forward to your reply.

**Comment by zhangtianzi** [comment]
Hi guys,I have solved this problem. my Youdao Yun Note: [solution](https://note.youdao.com/share/?id=f1f44a10594d9134281b917e3923a3e4&type=note#/)

**Comment by shutom001** [comment]
Hi guys, I got the same error(not support real-time kernel) when installing NVIDIA RTX 2080Ti on ubuntu 18.04 with Apollo kernel(1.5.5),  do you have any idea about this issue?  thank you very much!

after running the command "sudo ./install-nvidia.sh", it printed "Done to install nvidia kernel driver and user libraries."  then I ran "nvidia-smi" , but still didn't work. anybody have any suggestions?

**Comment by EduardC96** [comment]
Hey guys, I tried to install the NVIDIA Driver 450.102.04 for the Quadro P920 (on the RT Kernel 5.4.84-rt47, Ubuntu 18.04) using the script that was mentioned above (install-nvidia.sh). As I'm not using the apollo-kernel I made some changes in the script as described [here](https://www.programmersought.com/article/47743808166/). 

I always end up getting the same error when I try to run "nvidia-smi": "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

Is there anybody who managed to get their NVIDIA-Driver working without using the apollo-kernel?

**Comment by storypku** [comment]
> Hey guys, I tried to install the NVIDIA Driver 450.102.04 for the Quadro P920 (on the RT Kernel 5.4.84-rt47, Ubuntu 18.04) using the script that was mentioned above (install-nvidia.sh). As I'm not using the apollo-kernel I made some changes in the script as described [here](https://www.programmersought.com/article/47743808166/).
> 
> I always end up getting the same error when I try to run "nvidia-smi": "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."
> 
> Is there anybody who managed to get their NVIDIA-Driver working without using the apollo-kernel?

See https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md for the updated docs on kernel.

`Nvidia-smi can't communicate with nvidia driver` was a common seen problem when installing Nvidia driver. 

Try to disable all `multiverse` settings in `/etc/apt/sources.list`:

```bash
deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe # multiverse
```

**Comment by EduardC96** [comment]
> > Hey guys, I tried to install the NVIDIA Driver 450.102.04 for the Quadro P920 (on the RT Kernel 5.4.84-rt47, Ubuntu 18.04) using the script that was mentioned above (install-nvidia.sh). As I'm not using the apollo-kernel I made some changes in the script as described [here](https://www.programmersought.com/article/47743808166/).
> > I always end up getting the same error when I try to run "nvidia-smi": "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."
> > Is there anybody who managed to get their NVIDIA-Driver working without using the apollo-kernel?
> 
> See https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md for the updated docs on kernel.
> 
> `Nvidia-smi can't communicate with nvidia driver` was a common seen problem when installing Nvidia driver.
> 
> Try to disable the `multiverse` distribution component in `/etc/apt/sources.list`:
> 
> ```shell
> sudo add-apt-repository --remove multiverse
> ```

Thank you very much, it's finally working now!
