### ISSUE TITLE
GPS devices detect problems in Apollo, what needs to be done?

### ISSUE THREAD

**Issue by silverland79** [ApolloAuto/apollo#1882]
GPS devices detect  in linux no problem, it can receive satellite data and RTK-GPS data. However, the Apollo HMI GPS detection error, the following is the configuration information and error log. I want to know what else needs to be done to make GPS device pass the “Setup”.
1.localization.INFO:
Log file created at: 2017/12/19 15:47:45
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1219 15:47:45.412098  5828 rtk_localization.cc:79] GPS message buffer is empty.
E1219 15:47:45.421730  5828 rtk_localization.cc:79] GPS message buffer is empty.
E1219 15:47:45.449895  5828 rtk_localization.cc:79] GPS message buffer is empty.
E1219 15:47:45.449975  5828 rtk_localization.cc:79] GPS message buffer is empty.
E1219 15:47:45.464756  5828 rtk_localization.cc:79] GPS message buffer is empty.

2.gnss_driver.launch:
<launch>
    <arg name="gnss_conf" default="$(find gnss_driver)/conf/gnss_conf_mkz.txt" />
    <arg name="proj4_text" default="+proj=utm +zone=51 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs " />

    <node pkg="nodelet" type="nodelet" name="gnss_nodelet_manager"
        args="manager" output="screen">
        <param name="proj4_text" value="$(arg proj4_text)" />
    </node>

    <node pkg="nodelet" type="nodelet" name="stream_nodelet"
        args="load gnss_driver/StreamNodelet gnss_nodelet_manager" output="screen">
        <param name="gnss_conf" value="$(arg gnss_conf)" />
    </node>

    <node pkg="nodelet" type="nodelet" name="parser_nodelet"
        args="load gnss_driver/ParserNodelet gnss_nodelet_manager" output="screen">
        <param name="gnss_conf" value="$(arg gnss_conf)" />
        <param name="proj4_text" value="$(arg proj4_text)" />
    </node>
</launch>

3.gnss_conf_mkz.txt:
data {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/ttyUSB0"
        baud_rate: 115200
    }
}

rtk_from {
    format: RTCM_V3
    ntrip {
        address:rtk.ntrip.qxwz.com
        port:8002
        mount_point:RTCM30_GG
        user:qxmfj002
        password:cb55ed2
        timeout_s: 5
    }
}

rtk_to {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/ttyUSB1"
        baud_rate: 115200
    }
}

rtk_solution_type: RTK_RECEIVER_SOLUTION

login_commands: "UNLOGALL THISPORT\r\n"
login_commands: "LOG COM2 GPRMC ONTIME 1.0 0.25\r\n"
login_commands: "EVENTOUTCONTROL MARK2 ENABLE POSITIVE 999999990 10\r\n"
login_commands: "EVENTOUTCONTROL MARK1 ENABLE POSITIVE 500000000 500000000\r\n"
login_commands: "LOG NCOM1 GPGGA ONTIME 1.0\r\n"

login_commands: "log bestgnssposb ontime 0.5\r\n"
login_commands: "log bestgnssvelb ontime 0.5\r\n"
login_commands: "log bestposb ontime 0.5\r\n"
login_commands: "log INSPVASB ontime 0.01\r\n"
login_commands: "log CORRIMUDATASB ontime 0.01\r\n"
login_commands: "log INSCOVSB ontime 1\r\n"
login_commands: "log mark1pvab onnew\r\n"

login_commands: "log imutoantoffsetsb once\r\n"
login_commands: "log vehiclebodyrotationb onchanged\r\n"

logout_commands: "EVENTOUTCONTROL MARK2 DISABLE\r\n"
logout_commands: "EVENTOUTCONTROL MARK1 DISABLE\r\n"

**Comment by silverland79** [comment]
I grab some serial data，for example:
/dev/ttyUSB0:
$GPFPD,0,5787.500,0.000,1.443,-0.805,0.0000000,0.0000000,0.00,0.000,0.000,0.000,0.000,0,0,00*5D
$GPHPD,0,5785.000,0.000,0.000,0.000,0.0000000,0.0000000,0.00,0.000,0.000,0.000,0.000,0,0,00*76

**Comment by silverland79** [comment]
My GPS device chip is OEM617D.Manufacturers can only change INSPVAS = 508, RAWIMUSX = 1462, GPGGA = 218, these three Message agreements,Please Help to see if it works?

**Comment by bbidault2** [comment]
Hey @silverland79, I'm sorry I cannot help you with your problem but I have noticed you set an url as the address, is that what's required ? I expected it would be an IP address. Thanks.
