### ISSUE TITLE
[Proposal] Merge and convert control::PathPoint and planning::PathPoint to proto.

### ISSUE THREAD

**Issue by xiaoxq** [ApolloAuto/apollo#189]
The structs in
  modules/control/common/base_types.h
  modules/planning/common/base_types.h
are sort of redundant. They can be merged and converted to proto IMO.

I can do the refactoring. Please let me know if there is any concern.

**Comment by lianglia-apollo** [comment]
I also think they are redundant. Actually, those points are defined again in planning/proto/planning.proto.

**Comment by Capri2014** [comment]
Please go ahead and make the changes.
