### ISSUE TITLE
GPS device problem

### ISSUE THREAD

**Issue by silverland79** [ApolloAuto/apollo#1935]
If my GPS device supports the following Novatel protocols， can it operate in the default Novatel driver module？
1.choose one
BESTGNSSPOS:1429
BESTPOS:42
PSRPOS:47
2.choose one
BESTGNSSVEL:1430
BESTVEL:99
PSRVEL:100
3.choose one
CORRIMUDATA:
CORRIMUDATAS:
4.choose one
INSCOV:
INSCOVS:
5.choose one
INSPVA:
INSPVAS:
6.choose one
RAWIMUX:
RAWIMUSX:
7.GPGGA:

**Comment by Capri2014** [comment]
Not sure, what is your GPS model type?
