### ISSUE TITLE
How to access the training data?

### ISSUE THREAD

**Issue by Marketos-Damigos** [ApolloAuto/apollo#1941]
The baidu cloud page when you try to download the files of trafic lights it gives you only a sample download with just 100 photos. 

How can we download the full training data?

**Comment by Marketos-Damigos** [comment]
Should i download the End-to-End training data? (155.95GB)

**Comment by chucklqsun** [comment]
I think you cannot download the training data from cloud simulation platform. The only way to access them is using simulation on which you upload your module to train and test.

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.
