### ISSUE TITLE
Some thoughts about commit message

### ISSUE THREAD

**Issue by zhxt** [ApolloAuto/apollo#1942]
As you may know, there are some basic rules for git commit message.

From: Pro Git 2nd Edition - [5.2 Commit Guidelines](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project)
`------------------------------`
The last thing to keep in mind is the commit message. Getting in the habit of creating quality commit messages makes using and collaborating with Git a lot easier. As a general rule, your messages should start with a single line that’s no more than about 50 characters and that describes the changeset concisely, followed by a blank line, followed by a more detailed explanation. The Git project requires that the more detailed explanation include your motivation for the change and contrast its implementation with previous behavior — this is a good guideline to follow. It’s also a good idea to use the imperative present tense in these messages. In other words, use commands. Instead of “I added tests for” or “Adding tests for,” use “Add tests for.” Here is a [template originally written by Tim Pope:](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
~~~
Short (50 chars or less) summary of changes

More detailed explanatory text, if necessary.  Wrap it to
about 72 characters or so.  In some contexts, the first
line is treated as the subject of an email and the rest of
the text as the body.  The blank line separating the
summary from the body is critical (unless you omit the body
entirely); tools like rebase can get confused if you run
the two together.

Further paragraphs come after blank lines.

  - Bullet points are okay, too

  - Typically a hyphen or asterisk is used for the bullet,
    preceded by a single space, with blank lines in
    between, but conventions vary here
~~~

If all your commit messages follow this model, things will be much easier for you and the developers with whom you collaborate. The Git project has well-formatted commit messages — try running git log --no-merges there to see what a nicely-formatted project-commit history looks like.
`------------------------------`

Other discussions: 
[A Note About Git Commit Messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
[Writing good commit messages](https://github.com/erlang/otp/wiki/writing-good-commit-messages)
[On commit messages](http://who-t.blogspot.com/2009/12/on-commit-messages.html)
[How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/)  ([CN version](https://blog.louie.lu/2017/03/21/%E5%A6%82%E4%BD%95%E5%AF%AB%E4%B8%80%E5%80%8B-git-commit-message/))

It's not necessary to follow all those rules strictly, but it's a good practice to pay a little more attention.

JUST FYI.

**Comment by Capri2014** [comment]
@zhxt Thanks!

**Comment by zhxt** [comment]
@Capri2014 :-)

**Comment by zhxt** [comment]
Added a script to deploy [Sanity Check tool](http://wiki.qt.io/Early_Warning_System) in this [change](https://github.com/zhxt/apollo/commit/6b9be54fa526c4c4b2a252145aab2822dafe2ab6), it checks and reports after you run "git commit".

For example, the report may look like:
```
***
*** Suspicious changes in commit HEAD (scritps: add a script to deploy sanity check tool.):
***
***   commit message:
***     - Summary ends with period (key "log")
***
***   scripts/deploy_local_sanity_check.sh:
***     - Missing copyright header (key "copyright")
***     - Style issues (key "style")
***       21: Trailing whitespace
***
***   See http://wiki.qt.io/Early_Warning_System for explanations.
[dev d9f9a8a7] scritps: add a script to deploy sanity check tool.
 Date: Tue Dec 26 00:50:08 2017 +0800
 1 file changed, 51 insertions(+)
 create mode 100755 scripts/deploy_local_sanity_check.sh
```
Feel free to try :D
