### ISSUE TITLE
cannot adjust screen brightness after install apollo_kernel and apollo platform

### ISSUE THREAD

**Issue by jenechina** [ApolloAuto/apollo#198]
Hi! I found i cannot adjust the screen brightness by Fn key (other method neither) after installing apollo_kernel and platform as per install guides. Does anyone get the same issue? My PC is Lenovo T560 with ubuntu 14.04.5.

**Comment by ArmstrongWall** [comment]
I also have same problem.My CPU is Celeron J1900 with ubuntu 14.04.5.

**Comment by Fibonacci43** [comment]
I've ever had the same problem. I found the cause and fix it partly. My PC is lenovo savior with Ubuntu 16.04 and I finally found the linux kernel , which is apollo-kernel,  caused this problem. You can fix this problem by changing to another original kernel, but when you need to use apollo, you must change back to apollo-kernel.

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
