### ISSUE TITLE
HOW CAN  I SET IT UP?DOSE IT NEED SOMETHING EXTRA?

### ISSUE THREAD

**Issue by lzzzzzzzzz** [ApolloAuto/apollo#199]
I START A NEW ubuntu-lts on vmw and get update，then i start the commd 
# bash docker/scripts/install_docker.sh
and it runs like there is no problem，then i continue。
# bash docker/scripts/dev_start.sh
and the err inf like  **Permission _denied**
so i try to add **sudo** ，and the download speed is so slow。
and another question is do i need to set up apollo-kernel and apollo-platform？？
AND what about DOCKER??DO i need to set up and use a docker image？？
and my english is not good，i feel sorry about Syntax error and i will appreciate you can help me！

**Comment by GoLancer** [comment]
Duplicate with #201
