### ISSUE TITLE
rostopic echo shows nothing ??

### ISSUE THREAD

**Issue by huiyi1990** [ApolloAuto/apollo#20]
when running the rosbag, rostopic echo messages shows nothing ? Does it right ?

**Comment by qiankunzhu** [comment]
What's the rostopic list output, can u show the info?

**Comment by ycool** [comment]
@huiyi1990 Which docker image do you run?  dev docker image or release docker image?  Can you help to post your whole rostopic echo command?

Thanks.

**Comment by aiguo159** [comment]
Make sure you are running rostopic inside the docker environment. If you run you host-installed rostopic, it won't recognize the message formats used by Apollo.

**Comment by huiyi1990** [comment]
@ycool  hi, dev-latest are being used. 
 rostopic echo /apollo/control
  
  ERROR: Cannot load message class for [pb_msgs/ControlCommand]. Are your messages built?

I think it has some problem about build the message ??

**Comment by huiyi1990** [comment]
by 
bash apollo.sh build # inside dev docker
the abovemensioned command. it works
