### ISSUE TITLE
Error encountered during appollo.build

### ISSUE THREAD

**Issue by sonisk** [ApolloAuto/apollo#200]
Hi,
I'm encountering an error (please refer to error log at the end) when executing the command - "bash apollo.sh build". Am I missing something? appreciate your much needed help.
Thanks.

Background:
Followed the below steps:-
Installed Ubuntu 14.04.3 LTS on an Intel 3rd gen machine.
sudo apt-get update; sudo apt-get upgrade
apt-get install linux-generic-lts-xenial #This installed Kernel 4.4.0-83-generic
Next, followed the apollo-kernel installation procedure #successfully installed kernel 4.4.32-apollo-1-1RT, verified using uname -a.

While executing the command,
bash docker/scripts/install_docker.sh
encountered an error in line
sudo apt-get -y install linux-image-extra-$(uname -r) #couldn't download linux-image-extra-4.4.32-apollo-1-RT
To resolve this replaced the line as below,
sudo apt-get -y install linux-image-extra-4.4.0-83-generic #Hope this change is OK?
After this install_docker.sh was successful. # logout and login

docker ps # verified without sudo
bash docker/scripts/dev_start.sh #no errors
bash docker/scripts/dev_into.sh #no errors
bash apollo.sh build #gives error

-----------------Error Log---------------

test@in_dev_docker:/apollo$ bash apollo.sh build

System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Start building, please wait ...
.
____Loading package: modules/dreamview/backend
____Loading package: @eigen//
____Loading package: @google_styleguide//
____Loading package: @gtest//
____Loading package: @ros//
____Loading package: @com_github_grpc_grpc//
____Loading package: @com_github_google_protobuf//
____Loading package: @glog//
____Loading package: @curlpp//
____Loading package: @civetweb//
____Loading package: @websocketpp//
Building on x86_64, with targets:
//tools/platforms:x86_64
//tools/platforms:aarch64
//modules/prediction:prediction
//modules/prediction:prediction_lib
//modules/prediction/common:prediction_common
//modules/planning/conf:planning_trajectory_adapter_manager_config
//modules/planning:planning_testdata
//modules/planning:planning
//modules/planning:lib_planning
//modules/planning/planner:lib_planner
//modules/planning/common:lib_planning_common
//modules/perception:perception
//modules/perception/conf:perception_adapter_manager_config
//modules/perception:perception_lib
//modules/perception/common:perception_common
//modules/monitor/common:platform_common_lib
//modules/monitor/common:interface
//modules/localization/proto:localization_config_proto_pylib
//modules/localization/proto:imu_proto_pylib
//modules/localization/proto:gps_proto_pylib
//modules/localization/proto:camera_proto_pylib
//modules/localization/proto:camera_parameter_proto_pylib
//modules/localization:localization
//modules/localization/conf:localization_adapter_manager_config
//modules/localization:localization_app
//modules/localization/rtk:rtk_localization
//modules/localization/camera:camera_localization
//modules/localization/proto:localization_config_proto
//modules/localization/proto:localization_config_proto.pb
//modules/localization/proto:camera_parameter_proto
//modules/localization/proto:camera_parameter_proto.pb
//modules/localization:localization_base
//modules/hmi/ros_node:ros_node_service
//modules/hmi/proto:runtime_status_proto_pylib
//modules/hmi/proto:ros_node_proto_pylib
//modules/hmi/proto:ros_node_proto
//modules/hmi/proto:ros_node_proto.pb
//modules/hmi/proto:config_proto_pylib
//modules/dreamview/proto:simulation_world_proto_pylib
//modules/planning/proto:planning_proto_pylib
//modules/localization/proto:localization_proto_pylib
//modules/localization/proto:pose_proto_pylib
//modules/dreamview/conf:dreamview_adapter_manager_config
//modules/dreamview:dreamview
//modules/dreamview/backend:backend
//modules/dreamview/backend:websocket
//modules/dreamview/backend:simulation_world_service
//modules/dreamview/backend:trajectory_point_collector
//modules/dreamview/proto:simulation_world_proto
//modules/dreamview/proto:simulation_world_proto.pb
//modules/dreamview:frontend
//modules/decision/proto:decision_proto_pylib
//modules/prediction/proto:prediction_proto_pylib
//modules/perception/proto:perception_proto_pylib
//modules/decision/conf:localization_adapter_manager_config
//modules/decision:decision
//modules/decision:lib_decision
//modules/decision/common:decision_common
//modules/control/tools:pad_terminal
//modules/control/tools:control_tester
//modules/control/proto:control_proto_pylib
//modules/control/integration_tests:control_test_base
//modules/control/filters:filters
//modules/control:lib_pad_terminal
//modules/control:control_testdata
//modules/control:control
//modules/control:lib_control
//modules/control/controller:controller
//modules/control/controller:controller_agent
//modules/control/controller:lon_controller
//modules/control/controller:lat_controller
//modules/control/filters:mean_filter
//modules/control/filters:digital_filter
//modules/control/filters:digital_filter_coefficients
//modules/control/controller:controller_interface
//modules/control/common:common
//modules/control/common:trajectory_analyzer
//modules/control/common:pid_controller
//modules/control/common:interpolation_2d
//modules/control/common:hysteresis_filter
//modules/control/common:control_gflags
//modules/control/common:base_types
//modules/control/common:definitions
//modules/localization:localization_testdata
//modules/common/vehicle_state:vehicle_state
//modules/localization/common:localization_common
//modules/common/util/testing:simple_proto
//modules/common/util/testing:simple_proto.pb
//modules/common/proto:gnss_status_proto
//modules/common/proto:gnss_status_proto.pb
//modules/common/monitor/proto:monitor_proto_pylib
//modules/common/configs/proto:vehicle_config_proto_pylib
//modules/common/configs:vehicle_config_helper
//modules/common/data:vehicle_config_data
//modules/common/configs/proto:vehicle_config_proto
//modules/common/configs/proto:vehicle_config_proto.pb
//modules/common/configs:config_gflags
//modules/common/adapters/proto:adapter_config_proto_pylib
//modules/canbus/tools:teleop
//modules/canbus/tools:canbus_tester
//modules/canbus/proto:canbus_proto_pylib
//modules/common/proto:common_proto_pylib
//modules/canbus/can_client:can_client_tool
//modules/canbus:canbus_testdata
//modules/canbus:canbus
//modules/canbus:canbus_lib
//modules/common/monitor:monitor
//modules/common/adapters:adapter_manager
//modules/common/adapters/proto:adapter_config_proto
//modules/common/adapters/proto:adapter_config_proto.pb
//modules/common/adapters:message_adapters
//modules/planning/proto:planning_proto
//modules/planning/proto:planning_proto.pb
//modules/localization/proto:localization_proto
//modules/localization/proto:localization_proto.pb
//modules/localization/proto:imu_proto
//modules/localization/proto:imu_proto.pb
//modules/localization/proto:gps_proto
//modules/localization/proto:gps_proto.pb
//modules/localization/proto:camera_proto
//modules/localization/proto:pose_proto
//modules/localization/proto:pose_proto.pb
//modules/localization/proto:camera_proto.pb
//modules/decision/proto:decision_proto
//modules/prediction/proto:prediction_proto
//modules/prediction/proto:prediction_proto.pb
//modules/perception/proto:perception_proto
//modules/perception/proto:perception_proto.pb
//modules/decision/proto:decision_proto.pb
//modules/common/monitor/proto:monitor_proto
//modules/common/monitor/proto:monitor_proto.pb
//modules/common/adapters:adapter
//modules/common/adapters:adapter_gflags
//modules/common:apollo_app
//modules/hmi/utils:hmi_status_helper
//modules/hmi/utils:restful_client
//modules/hmi/proto:runtime_status_proto
//modules/hmi/proto:runtime_status_proto.pb
//modules/common/status:status
//modules/canbus/vehicle:vehicle_factory
//modules/canbus/vehicle:lincoln_vehicle_factory
//modules/canbus/vehicle/lincoln:lincoln_controller
//modules/canbus/vehicle/lincoln:lincoln_message_manager
//modules/canbus/vehicle/lincoln/protocol:canbus_lincoln_protocol
//modules/canbus/vehicle:abstract_vehicle_factory
//modules/canbus/vehicle:vehicle_controller_base
//modules/canbus/can_comm:can_sender
//modules/canbus/can_comm:can_receiver
//modules/canbus/vehicle:message_manager_base
//modules/control/proto:control_proto
//modules/control/proto:control_proto.pb
//modules/canbus/can_client:can_client_factory
//modules/common/util:factory
//modules/canbus/can_client/fake:fake_can_client
//modules/canbus/can_client:can_client
//modules/common/util:util
//modules/common/time:time
//modules/common/math:math
//modules/common/math:search
//modules/common/math:quaternion
//modules/common/math:lqr
//modules/common/math:linear_interpolation
//modules/common/math:kalman_filter
//modules/common/math:matrix_operations
//modules/common/math:integral
//modules/common/math:euler_angles_zxy
//modules/common/math:box2d
//modules/common/math:polygon2d
//modules/common/math:line_segment2d
//modules/common/math:angle
//modules/common/math:sin_table
//modules/common/math:aaboxkdtree2d
//modules/common/math:aabox2d
//modules/common/math:math_utils
//modules/common/math:vec2d
//modules/canbus/common:canbus_common
//modules/canbus/proto:canbus_proto
//modules/common/proto:common_proto
//modules/common/proto:header_proto
//modules/common/proto:header_proto.pb
//modules/common/proto:error_code_proto
//modules/common/proto:error_code_proto.pb
//modules/common/proto:common_proto.pb
//modules/common:common
//modules/common:macro
//modules/common:log
//modules/canbus/proto:canbus_proto.pb
//:x86_64
//:arm64
WARNING: Running Bazel server needs to be killed, because the startup options are different.
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD:20:5: file ':BUILD.generated.bzl' does not contain symbol 'ssl_c_sources' (did you mean 'ssl_sources'?).
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD:74:22: Traceback (most recent call last):
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 73
select({":linux_x86_64": crypto_sources...": []})
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 74, in select
crypto_sources_linux_x86_64
name 'crypto_sources_linux_x86_64' is not defined.
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD:95:12: Traceback (most recent call last):
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 93
cc_library(name = "crypto", srcs = crypto_sou..., <5 more arguments>)
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 95, in cc_library
crypto_sources
name 'crypto_sources' is not defined.
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD:108:12: Traceback (most recent call last):
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 106
cc_library(name = "ssl", srcs = ssl_c_sources..., <5 more arguments>)
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 108, in cc_library
ssl_c_sources
name 'ssl_c_sources' is not defined.
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD:118:12: Traceback (most recent call last):
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 116
cc_library(name = "ssl_cc", srcs = ssl_cc_sou..., <4 more arguments>)
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 118, in cc_library
ssl_cc_sources
name 'ssl_cc_sources' is not defined.
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD:127:12: Traceback (most recent call last):
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 125
cc_binary(name = "bssl", srcs = tool_sources..., <3 more arguments>)
File "/home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD", line 127, in cc_binary
tool_sources
name 'tool_sources' is not defined.
ERROR: /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl:46:13: no such target '@boringssl//boringssl-master-with-bazel:ssl': target 'ssl' not declared in package 'boringssl-master-with-bazel' defined by /home/test/.cache/bazel/_bazel_test/540135163923dd7d5820f3ee4b306b32/external/boringssl/boringssl-master-with-bazel/BUILD and referenced by '//external:libssl'.
ERROR: Analysis of target '//modules/common/proto:error_code_proto.pb' failed; build aborted.
INFO: Elapsed time: 3.108s

[ERROR] Build failed!
[INFO] Took 18 seconds

**Comment by siyangy** [comment]
We have updated the boringssl to a stable version: https://github.com/ApolloAuto/apollo/pull/187. Looks like your local bazel cache are still referring to the old (and problematic) one: boringssl-master-with-bazel. You can clear the cache by ./apollo.sh clean and retry building.

**Comment by sonisk** [comment]
Sorry for delayed response, the build is now successful with the latest apollo package. Thanks a ton!

**Comment by TheBlueShy** [comment]
1111
