### ISSUE TITLE
how can i slav the problen

### ISSUE THREAD

**Issue by lzzzzzzzzz** [ApolloAuto/apollo#201]
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/create?name=apollo_dev: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/apollo_dev/exec: dial unix /var/run/docker.sock: connect: permission denied

**Comment by GoLancer** [comment]
Did you log out and back in after installing docker?
> Logging out and logging back in is required because the group change will not have an effect unless your session is closed.

I hope this helps you.

**Comment by xiaoxq** [comment]
Please refer to the "Docker post-installation doc" to fix permission issues.
https://docs.docker.com/engine/installation/linux/linux-postinstall/
