### ISSUE TITLE
demo bag url not exists

### ISSUE THREAD

**Issue by binliu-base** [ApolloAuto/apollo#2073]
In ./docs/demo_guide/rosbag_helper.sh, I see the following info.

DEMO_BAG_URL="https://github.com/ApolloAuto/apollo/releases/download/v1.5.0/demo_1.5.np.bag";

But the URL is not exists, which will cause the command of replay demo rosbag fail. Please fix it with correct URL.

**Comment by lianglia-apollo** [comment]
I tried this link just now, it works on my computer.

**Comment by binliu-base** [comment]
Close the issue due to not a bug
