### ISSUE TITLE
yesterday i have done it well ，but today something wrong ，i can't start docker

### ISSUE THREAD

**Issue by lzzzzzzzzz** [ApolloAuto/apollo#212]
**lz@ubuntu:~/apollo-master$ service docker start 
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.**
**-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun starting up.
Jul 15 23:20:43 ubuntu systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Jul 15 23:20:43 ubuntu systemd[1]: docker.service: Start request repeated too qu
Jul 15 23:20:43 ubuntu systemd[1]: Failed to start Docker Application Container 
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Jul 15 23:20:43 ubuntu systemd[1]: docker.socket: Unit entered failed state.**

**Comment by xiaoxq** [comment]
Setting up Docker could be a very complicated and independent topic.
You can always have a try with
```
sudo docker run hello-world
```
to check if your docker is functioning well.

Otherwise you may have to fix it by reading the Docker doc (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/) and researching on the internet before playing with Apollo.

**Comment by wanglei828** [comment]
I think you need to run "sudo service docker restart", then use "docker ps" to verify you docker service start correctly.
If everything looks good, you can use our docker image to start a dev container.
