### ISSUE TITLE
您好，最近在研究Velodyne用GPS时间做时间同步时遇到一个问题，velodyn上提供的gps接口串口的波特率是9600，而gps由于传输数据大波特率必须要设置为115200，现在两个波特率都是不能改的，想请教下这个问题是怎么解决的呢

### ISSUE THREAD

**Issue by luo2880399** [ApolloAuto/apollo#2123]

**Comment by carlin314** [comment]
Your GPS should have multi com, for example com 1 is for output for common use , com2 or com3 is for lidar gps sync, com2 can be baurdrate can be set seperately, ex: input command : com com2 115200 for novatel receiver.
