### ISSUE TITLE
'bootstrap.sh' file is not found after dev_start.sh, dev_into and apollo.sh build

### ISSUE THREAD

**Issue by paleyweng** [ApolloAuto/apollo#2129]
Issue:
Can't find 'bootstrap.sh' in /scripts, after below commands are executed completely and successfully.
bash docker/scripts/install_docker.sh
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh

find / -name bootstrap.sh       
-> not found.
building result:
root@in_dev_docker:/apollo# bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 882 targets (12 packages loaded).
INFO: Found 882 targets...
INFO: Elapsed time: 554.409s, Critical Path: 25.05s
INFO: Build completed successfully, 922 total actions
============================
[ OK ] Build passed!
[INFO] Took 580 seconds
============================

List of scripts/
-rw-r--r--  1 root root 3540 Sep 20 04:36 AGREEMENT.txt
-rwxr-xr-x  1 root root 7429 Sep 20 04:36 apollo_base.sh*
-rwxr-xr-x  1 root root  968 Sep 20 04:36 canbus.sh*
-rwxr-xr-x  1 root root  896 Sep 20 04:36 canbus_teleop.sh*
-rwxr-xr-x  1 root root  957 Sep 20 04:36 canbus_tester.sh*
-rwxr-xr-x  1 root root  946 Sep 20 04:36 configurator.sh*
-rwxr-xr-x  1 root root  955 Sep 20 04:36 control.sh*
-rwxr-xr-x  1 root root  942 Sep 20 04:36 control_info.sh*
-rwxr-xr-x  1 root root  972 Sep 20 04:36 decision.sh*
-rwxr-xr-x  1 root root  936 Sep 20 04:36 diagnostics.sh*
-rwxr-xr-x  1 root root 2494 Sep 20 04:36 docker_adduser.sh*
-rwxr-xr-x  1 root root  973 Sep 20 04:36 dreamview.sh*
-rwxr-xr-x  1 root root  999 Sep 20 04:36 dreamview_sim_control.sh*
-rwxr-xr-x  1 root root  930 Sep 20 04:36 dumpbag.sh*
-rwxr-xr-x  1 root root 1104 Sep 20 04:36 env.sh*
-rwxr-xr-x  1 root root 1029 Sep 20 04:36 generate_routing_topo_graph.sh*
-rwxr-xr-x  1 root root 1673 Sep 20 04:36 generate_ssl_keys.sh*
-rwxr-xr-x  1 root root 1443 Sep 20 04:36 gps.sh*
-rwxr-xr-x  1 root root 1311 Sep 20 04:36 gps_sunnyvale.sh*
-rwxr-xr-x  1 root root 1889 Sep 20 04:36 hmi.sh*
-rwxr-xr-x  1 root root 1339 Sep 20 04:36 hw_check.sh*
-rwxr-xr-x  1 root root 4170 Sep 20 04:36 lidar_calibration.sh*
-rwxr-xr-x  1 root root  960 Sep 20 04:36 localization.sh*
-rwxr-xr-x  1 root root  946 Sep 20 04:36 mock_routing_request.sh*
-rwxr-xr-x  1 root root 1158 Sep 20 04:36 pad.sh*
-rwxr-xr-x  1 root root  958 Sep 20 04:36 perception.sh*
-rwxr-xr-x  1 root root  956 Sep 20 04:36 planning.sh*
-rwxr-xr-x  1 root root  937 Sep 20 04:36 plot_planning.sh*
-rwxr-xr-x  1 root root  938 Sep 20 04:36 plot_trace.sh*
-rwxr-xr-x  1 root root  958 Sep 20 04:36 prediction.sh*
-rwxr-xr-x  1 root root  951 Sep 20 04:36 realtime_plot.sh*
-rwxr-xr-x  1 root root 1984 Sep 20 04:36 record_bag.sh*
-rwxr-xr-x  1 root root  934 Sep 20 04:36 replay.sh*
-rwxr-xr-x  1 root root  955 Sep 20 04:36 routing.sh*
-rwxr-xr-x  1 root root 1039 Sep 20 04:36 run_rtk_player.sh*
-rwxr-xr-x  1 root root 1133 Sep 20 04:36 run_rtk_recorder.sh*
-rwxr-xr-x  1 root root  814 Sep 20 04:36 stop_rtk_player.sh*
-rwxr-xr-x  1 root root  816 Sep 20 04:36 stop_rtk_recorder.sh*
-rwxr-xr-x  1 root root 1447 Sep 20 04:36 velodyne.sh*

**Comment by startcode** [comment]
first, update the code to the latest commit
then check if you accidentally made any local changes.

If nothing works, simply download the following file to your scripts/ directory
https://github.com/ApolloAuto/apollo/blob/master/scripts/bootstrap.sh

**Comment by paleyweng** [comment]
I didn't see this file in branch 1.5.0, So I have to use package from master instead of release 1.5.0. Right?

**Comment by gengqx** [comment]
If you use branch 1.5.0 ,it did not have bootstrap.sh ,you should see the docs and helps in your branch on your disk.  In apollo 1.5,The right way is:
```
bash scripts/hmi.sh   
```

**Comment by paleyweng** [comment]
Ok. Got it. Thanks for your help. And pls. resolve this ticket.
