### ISSUE TITLE
bash apollo.sh build error！

### ISSUE THREAD

**Issue by teldyc** [ApolloAuto/apollo#218]
yc@ubuntu:~/Desktop/yc/git/apollo$ bash docker/scripts/dev_into.sh 
yc@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Start building, please wait ...
Extracting Bazel installation...
......................................................
____Downloading https://github.com/pubref/rules_protobuf/archive/v0.7.1.tar.gz via codeload.github.com: 13,693 bytes
____Downloading https://github.com/pubref/rules_protobuf/archive/v0.7.1.tar.gz via codeload.github.com: 41,265 bytes
____Downloading https://github.com/pubref/rules_protobuf/archive/v0.7.1.tar.gz via codeload.github.com: 97,435 bytes
____Downloading https://github.com/pubref/rules_protobuf/archive/v0.7.1.tar.gz via codeload.github.com: 158,861 bytes
____Downloading https://github.com/pubref/rules_protobuf/archive/v0.7.1.tar.gz via codeload.github.com: 258,647 bytes
____Loading package: 
____Loading package: modules/canbus/vehicle
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 32,095 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 73,005 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 122,082 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 138,441 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 154,800 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 171,159 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 187,518 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 203,877 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 236,595 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 252,954 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 269,313 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 285,672 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 318,390 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 334,749 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 351,108 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 367,467 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 383,826 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 400,185 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 416,544 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 432,903 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 449,262 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 465,621 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 481,980 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 498,339 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 514,698 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 531,057 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 547,416 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 563,775 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 580,134 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 596,493 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 612,852 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 629,211 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 645,570 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 678,288 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 711,006 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 727,365 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 743,724 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 760,083 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 776,442 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 792,801 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 809,160 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 825,519 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 841,878 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 858,237 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 874,596 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 890,955 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 907,314 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 923,673 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 940,032 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 972,750 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,005,468 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,038,186 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,054,545 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,070,904 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,087,263 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,103,622 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,119,981 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,136,340 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,152,699 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,169,058 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,185,417 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,201,776 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,218,135 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,250,853 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,267,212 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,283,571 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,316,289 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,349,007 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,381,725 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,414,443 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,447,161 bytes
____Downloading https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz: 1,496,238 bytes
____Loading package: @eigen//
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
____Unknown host: github.com
Building on x86_64, with targets:
//tools/platforms:x86_64
//tools/platforms:aarch64
//modules/prediction:prediction
//modules/prediction:prediction_lib
//modules/prediction/common:prediction_common
//modules/planning/conf:planning_trajectory_adapter_manager_config
//modules/planning:planning_testdata
//modules/planning:planning
//modules/planning:lib_planning
//modules/planning/planner:lib_planner
//modules/planning/common:lib_planning_common
//modules/perception:perception
//modules/perception/conf:perception_adapter_manager_config
//modules/perception:perception_lib
//modules/perception/common:perception_common
//modules/monitor/common:platform_common_lib
//modules/monitor/common:interface
//modules/localization/proto:localization_config_proto_pylib
//modules/localization/proto:imu_proto_pylib
//modules/localization/proto:gps_proto_pylib
//modules/localization/proto:camera_proto_pylib
//modules/localization/proto:camera_parameter_proto_pylib
//modules/localization:localization
//modules/localization/conf:localization_adapter_manager_config
//modules/localization:localization_app
//modules/localization/rtk:rtk_localization
//modules/localization/camera:camera_localization
//modules/localization/proto:localization_config_proto
//modules/localization/proto:localization_config_proto.pb
//modules/localization/proto:camera_parameter_proto
//modules/localization/proto:camera_parameter_proto.pb
//modules/localization:localization_base
//modules/hmi/ros_node:ros_node_service
//modules/hmi/proto:runtime_status_proto_pylib
//modules/hmi/proto:ros_node_proto_pylib
//modules/hmi/proto:ros_node_proto
//modules/hmi/proto:ros_node_proto.pb
//modules/hmi/proto:config_proto_pylib
//modules/dreamview/proto:simulation_world_proto_pylib
//modules/planning/proto:planning_proto_pylib
//modules/localization/proto:localization_proto_pylib
//modules/localization/proto:pose_proto_pylib
//modules/dreamview/conf:dreamview_adapter_manager_config
//modules/dreamview:dreamview
//modules/dreamview/backend:backend
//modules/dreamview/backend:websocket
//modules/dreamview/backend:simulation_world_service
//modules/dreamview/backend:trajectory_point_collector
//modules/dreamview/proto:simulation_world_proto
//modules/dreamview/proto:simulation_world_proto.pb
//modules/dreamview:frontend
//modules/decision/proto:decision_proto_pylib
//modules/prediction/proto:prediction_proto_pylib
//modules/perception/proto:perception_proto_pylib
//modules/decision/conf:localization_adapter_manager_config
//modules/decision:decision
//modules/decision:lib_decision
//modules/decision/common:decision_common
//modules/control/tools:pad_terminal
//modules/control/tools:control_tester
//modules/control/proto:control_proto_pylib
//modules/control/integration_tests:control_test_base
//modules/control/filters:filters
//modules/control:lib_pad_terminal
//modules/control:control_testdata
//modules/control:control
//modules/control:lib_control
//modules/control/controller:controller
//modules/control/controller:controller_agent
//modules/control/controller:lon_controller
//modules/control/controller:lat_controller
//modules/control/filters:mean_filter
//modules/control/filters:digital_filter
//modules/control/filters:digital_filter_coefficients
//modules/control/controller:controller_interface
//modules/control/common:common
//modules/control/common:trajectory_analyzer
//modules/control/common:pid_controller
//modules/control/common:interpolation_2d
//modules/control/common:hysteresis_filter
//modules/control/common:control_gflags
//modules/localization:localization_testdata
//modules/common/vehicle_state:vehicle_state
//modules/localization/common:localization_common
//modules/common/util/testing:simple_proto
//modules/common/util/testing:simple_proto.pb
//modules/common/proto:path_point_proto
//modules/common/proto:path_point_proto.pb
//modules/common/proto:gnss_status_proto
//modules/common/proto:gnss_status_proto.pb
//modules/common/monitor/proto:monitor_proto_pylib
//modules/common/configs/proto:vehicle_config_proto_pylib
//modules/common/configs:vehicle_config_helper
//modules/common/data:vehicle_config_data
//modules/common/configs/proto:vehicle_config_proto
//modules/common/configs/proto:vehicle_config_proto.pb
//modules/common/configs:config_gflags
//modules/common/adapters/proto:adapter_config_proto_pylib
//modules/canbus/tools:teleop
//modules/canbus/tools:canbus_tester
//modules/canbus/proto:canbus_proto_pylib
//modules/common/proto:common_proto_pylib
//modules/canbus/can_client:can_client_tool
//modules/canbus:canbus_testdata
//modules/canbus:canbus
//modules/canbus:canbus_lib
//modules/common/monitor:monitor
//modules/common/adapters:adapter_manager
//modules/common/adapters/proto:adapter_config_proto
//modules/common/adapters/proto:adapter_config_proto.pb
//modules/common/adapters:message_adapters
//modules/planning/proto:planning_proto
//modules/planning/proto:planning_proto.pb
//modules/localization/proto:localization_proto
//modules/localization/proto:localization_proto.pb
//modules/localization/proto:imu_proto
//modules/localization/proto:imu_proto.pb
//modules/localization/proto:gps_proto
//modules/localization/proto:gps_proto.pb
//modules/localization/proto:camera_proto
//modules/localization/proto:pose_proto
//modules/localization/proto:pose_proto.pb
//modules/localization/proto:camera_proto.pb
//modules/decision/proto:decision_proto
//modules/prediction/proto:prediction_proto
//modules/prediction/proto:prediction_proto.pb
//modules/perception/proto:perception_proto
//modules/perception/proto:perception_proto.pb
//modules/decision/proto:decision_proto.pb
//modules/common/monitor/proto:monitor_proto
//modules/common/monitor/proto:monitor_proto.pb
//modules/common/adapters:adapter
//modules/common/adapters:adapter_gflags
//modules/common:apollo_app
//modules/hmi/utils:hmi_status_helper
//modules/hmi/utils:restful_client
//modules/hmi/proto:runtime_status_proto
//modules/hmi/proto:runtime_status_proto.pb
//modules/common/status:status
//modules/canbus/vehicle:vehicle_factory
//modules/canbus/vehicle:lincoln_vehicle_factory
//modules/canbus/vehicle/lincoln:lincoln_controller
//modules/canbus/vehicle/lincoln:lincoln_message_manager
//modules/canbus/vehicle/lincoln/protocol:canbus_lincoln_protocol
//modules/canbus/vehicle:abstract_vehicle_factory
//modules/canbus/vehicle:vehicle_controller_base
//modules/canbus/can_comm:can_sender
//modules/canbus/can_comm:can_receiver
//modules/canbus/vehicle:message_manager_base
//modules/control/proto:control_proto
//modules/control/proto:control_proto.pb
//modules/canbus/can_client:can_client_factory
//modules/common/util:factory
//modules/canbus/can_client/fake:fake_can_client
//modules/canbus/can_client:can_client
//modules/common/util:util
//modules/common/time:time
//modules/common/math:math
//modules/common/math:search
//modules/common/math:quaternion
//modules/common/math:lqr
//modules/common/math:linear_interpolation
//modules/common/math:kalman_filter
//modules/common/math:matrix_operations
//modules/common/math:integral
//modules/common/math:euler_angles_zxy
//modules/common/math:box2d
//modules/common/math:polygon2d
//modules/common/math:line_segment2d
//modules/common/math:angle
//modules/common/math:sin_table
//modules/common/math:aaboxkdtree2d
//modules/common/math:aabox2d
//modules/common/math:math_utils
//modules/common/math:vec2d
//modules/canbus/common:canbus_common
//modules/canbus/proto:canbus_proto
//modules/common/proto:common_proto
//modules/common/proto:header_proto
//modules/common/proto:header_proto.pb
//modules/common/proto:error_code_proto
//modules/common/proto:error_code_proto.pb
//modules/common/proto:common_proto.pb
//modules/common:common
//modules/common:macro
//modules/common:log
//modules/canbus/proto:canbus_proto.pb
//:x86_64
//:arm64
WARNING: Running Bazel server needs to be killed, because the startup options are different.
ERROR: /home/yc/.cache/bazel/_bazel_yc/540135163923dd7d5820f3ee4b306b32/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl:46:13: no such package '@com_github_madler_zlib//': Error cloning repository: SSL peer shut down incorrectly caused by SSL peer shut down incorrectly caused by SSL peer shut down incorrectly and referenced by '//external:zlib'.
ERROR: Analysis of target '//modules/dreamview:dreamview' failed; build aborted.
INFO: Elapsed time: 5062.985s
============================
[ERROR] Build failed!
[INFO] Took 5135 seconds
============================

what should  i do？

**Comment by wanglei828** [comment]
Please run "bash apollo.sh clean first",  then run "bash apollo.sh build"

**Comment by teldyc** [comment]
//modules/common:macro
//modules/common:log
//modules/canbus/proto:canbus_proto.pb
//:x86_64
//:arm64
WARNING: Running Bazel server needs to be killed, because the startup options are different.
INFO: Found 189 targets...
INFO: Elapsed time: 887.676s, Critical Path: 309.19s
============================
[ OK ] Build passed!
[INFO] Took 903 seconds
============================

Thank you so much！
