### ISSUE TITLE
Docker Error:unauthorized: authentication required.

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#2262]
I have following error when I run `bash docker/scripts/dev_start.sh`
Do we need docker username in apollo2.0?
```
4d233f0f8483: Waiting 
6e03bccc2355: Waiting 
docker: unauthorized: authentication required.
See 'docker run --help'.
Error response from daemon: No such container: apollo_dev
```

**Comment by zhxt** [comment]
Seems no need, works fine for me. 
Please re-try with -C option to see what will happen.

**Comment by westeast** [comment]
@zhxt Do you mean `bash docker/scripts/dev_start.sh -C`

**Comment by zhxt** [comment]
@westeast yeah, since I have seen that you're from Beijing, too :-)

ps, you can find me at #apolloauto channel on freenode IRC. (AD :-D)

**Comment by westeast** [comment]
@zhxt Thanks so much , -C solved my problem~
