### ISSUE TITLE
MPC formulation

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#2308]
Hello Apollo team,

I just saw MPC is introduced in the controller in Apollo 2.0! Is there any documentation about MPC, such as optimization formulation and so on? Or it official 2.0 documentation coming soon?
Excited!
Thank you.

**Comment by Capri2014** [comment]
@wckorealsh YES, we will, there would be linear MPC formular introductions as well as tuning instructions.

**Comment by wckorealsh** [comment]
Can you also include EM planner equation as well? I know it solves some problem using the dynamic programming, but this is a solution method and I would like to know problem formulation. That would be AWESOME!
Thank you!

**Comment by natashadsouza** [comment]
@wckorealsh thank you for your support and suggestions!
Hope that your support continues! :)

**Comment by BrianChanCN** [comment]
> @wckorealsh YES, we will, there would be linear MPC formular introductions as well as tuning instructions.

Hey, friend. Could you tell me where can i find these docutments? I can not find turning instruction about MPC. Thanks!

**Comment by BrianChanCN** [comment]
@Capri2014
