### ISSUE TITLE
[ERROR] Build failed!, no such package '@ros//'

### ISSUE THREAD

**Issue by harderthan** [ApolloAuto/apollo#2321]
Hello.
I'm follow script on this [link](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md#docker).
But, I can't build modules of the docker.

`` [ERROR] Build failed! ``

**How can I build clearly?**

I tried this on below env.

OS: Ubuntu 16.04
Kernel : 4.10.0-42-generic

```bash
YSystem check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Extracting Bazel installation...
........
... License Agreement...
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/third_party_perception/BUILD:24:1: no such package '@ros//': Expected directory at /home/tmp/ros but it does not exist. and referenced by '//modules/third_party_perception:third_party_perception'
ERROR: Analysis of target '//modules/third_party_perception:third_party_perception' failed; build aborted
INFO: Elapsed time: 1.386s
FAILED: Build did NOT complete successfully (5 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 525 seconds
============================
```

**Comment by mickeyouyou** [comment]
You could download the latest release ros in directory 
` /home/tmp/`
and run this
```
wget https://github.com/ApolloAuto/apollo-platform/releases/download/2.0.0/ros-indigo-apollo-2.0.0-x86_64.tar.gz
tar zxvf ros-indigo-apollo-2.0.0-x86_64.tar.gz
rsync -av ros/ /apollo/third_party/ros_x86_64
source /apollo/third_party/ros_x86_64/setup.bash
```

**Comment by harderthan** [comment]
Thanks you.
I can have solved by your help.

By the way, Why was not this way written on document of upper link? 
Is it a optional way to install the Apollo project?

**Comment by lxbeyond** [comment]
i do as you suggested ,but there is still a proble ,
/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1204 targets (8 packages loaded).
INFO: Found 1204 targets...
ERROR: /apollo/modules/common/BUILD:31:1: undeclared inclusion(s) in rule '//modules/common:apollo_app':
this rule is missing dependency declarations for the following files included by 'modules/common/apollo_app.cc':
  '/apollo/ros/include/ros/ros.h'
INFO: Elapsed time: 45.481s, Critical Path: 9.02s
FAILED: Build did NOT complete successfully
============================
[ERROR] Build failed!
[INFO] Took 47 seconds
============================
how to solve the proble ?@mickeyouyou

**Comment by mickeyouyou** [comment]
We have built in ros in image, you can try the latest version。

**Comment by harderthan** [comment]
@mickeyouyou Thank you.
When I tried the latest version, It was working.
I closed this issue.
