### ISSUE TITLE
Request for more details, Other types of Lidar - Hardware FAQs 

### ISSUE THREAD

**Issue by Prasan03** [ApolloAuto/apollo#2330]
![image](https://user-images.githubusercontent.com/34156395/34520857-010feacc-f08b-11e7-8e6c-84fdb3c73c94.png)

Can someone give me more details on how to go about [this](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Hardware_FAQs.md)? I am still a beginner in ROS and Apollo.
I have an IBEO LUX Lidar along with a ROS driver so, does it mean I have to install [apollo-platform](https://github.com/ApolloAuto/apollo-platform) and install LUX ROS driver inside it? 
But, I don't understand how it is communicating with the main [Apollo](https://github.com/ApolloAuto/apollo) modules so that I can visualize Lidar output on Dreamview or Perception Visualizer.

I will be grateful for any help you can provide.

Regards,
Prasan

**Comment by kcpinnaka** [comment]
https://apolloauto.github.io/doxygen/apollo/inherits.html
this might provide some high level info on interfaces btw modules.

**Comment by will1991** [comment]
apollo run in the docker can communicate with ros outside the docker. may be you can try install ros outside docker, using rviz to visualize  the point cloud topic in docker.

**Comment by YangHan101** [comment]
Closing ticket. Feel free to reopen.
