### ISSUE TITLE
Is it possible to setup only perception module on desktop?

### ISSUE THREAD

**Issue by 1duo** [ApolloAuto/apollo#2331]
Hi,

I'm playing around with Apollo, nice clean and modularized framework!  
I'm wondering if I could setup/develop only `Perception module` that:

- runs on a desktop (with NVIDIA GPUs).
- takes in video (e.g. mp4 file / camera) as input (how should I fit in?).
- output perception results (obstacles/traffic lights). Logs would be good enough, better if there's way to connect to DreamView and see how the car interact. 

**Is this feasible?** If so, other than follow [these steps](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md), **what else should I do?** Thank you!

**Comment by chucklqsun** [comment]
@1duo perception module also needs other sensors, such as LiDAR, GPS/Inertial System for localisation in HDMap.

**Comment by techoe** [comment]
Thank you for the question. However, currently we are not supporting it.
