### ISSUE TITLE
How to connect to the canbus

### ISSUE THREAD

**Issue by bbidault2** [ApolloAuto/apollo#2350]
Hello,

I have used the _how to add a new vehicle_ documentation ([docs/howto/how_to_add_a_new_vehicle.md](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_new_vehicle.md)) and the _gen vehicle protocol tool_ ([modules/tools/gen_vehicle_protocol](https://github.com/ApolloAuto/apollo/tree/master/modules/tools/gen_vehicle_protocol)) to generate the necessary files to use Apollo with my vehicle. I have used a DBC file with the steering angle and the brake and throttle pedals positions identified. After correcting several linking errors, etc., my project is able to build.

Now, my question is, how do you actually use Apollo ? I was able to run the demo using the guidelines like everyone else but there is a lack of documentation regarding concrete use of the platform.
As an example, a goal I would like to achieve is to record the steering angle and pedals positions sent through the canbus via the obd port. I can connect to the obd port using a Kvaser Leaf-light, then, it seems like the `apollo_base.sh` script includes the method to connect to a CAN device, so I believe the solution is somewhere in the scripts.
I guess my question in a broad sense is, how do I connect to the canbus/how do I record data (CAN data in my case) with Apollo ?

I have tried to use the HMI UI by following the quickstart guide ([docs/quickstart/apollo_1_0_quick_start.md](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md)), although, I encounter the same problem described in #105 and #157, `Error response from daemon: No such container: apollo_release`.
Since the UI runs scripts in the background, I believe there is a way to use Apollo from the command lines.

 ```
$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
```
```
$ docker -v
Docker version 17.05.0-ce, build 89658be
```
Please feel free to ask for details if my question is not clear enough. Thank you.

**Comment by gengqx** [comment]
The device apollo used to communicate with a car is an ESD PCIE Can Card,the driver is under module/driver/canbus, so first you need to refer how to add a new can card,it would tell you how to implent a new CanClient that make sure the send and receive works. Second,apollo is use lincoln mkz,so you need implent your own car, the code is under modules/canbus/vehicle ,that makes sure that you send a percent number to out a right brake or throttle.
Most meterial could be found in docs/howto

**Comment by bbidault2** [comment]
Thank you for the answer @gengqx, I'll look into that, and I already implemented my vehicle. 
Is there a way to implement a new can interface ? I am not looking into commanding the vehicle, only receiving vehicle status like steering angle and pedals positions. Since it's easy to catch diagnostics data with a Kvaser Leaf-light and `candump`, I wonder if Apollo integrates a way to see that data flowing through a ROS topic. Thank you.

**Comment by bbidault2** [comment]
Ok, so I've figured it out by enabling my own platform to send `apollo::canbus::chassis` type messages to be recorded by Apollo.

**Comment by bbidault2** [comment]
@AshleyRoth For reading vehicle data, you can probably connect to the OBD connector of your vehicle with an OBD to DB9 cable + Kvaser. For writing commands (for steering, throttle and brake control) I am using a platform named PolySync OSCC with another tool for ROS integration named PolySync ROSCCO.

**Comment by AshleyRoth** [comment]
@bbidault2

Thanks for your answer
Did I understand correctly? you connected to odb, get data in PolySinc on in Apollo?
I apologize for the stupid questions, I myself wanted to connect to the Apollo via Kvaser Leaf Light 2 car CAN. in apollo created a new CAN client according to the instructions, but nothing is displayed. status unknown
