### ISSUE TITLE
apollo build error

### ISSUE THREAD

**Issue by kejingjing88212** [ApolloAuto/apollo#2376]
today i accord the readme to install , build,and run apollo  demo ,i get into some error such as: 
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Extracting Bazel installation...
.......................................................
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running

i have try apollo 1.0 and apollo 2.0 meet the same probleam ,someone can help me and give some opinion, thks

**Comment by kejingjing88212** [comment]
I according to the  can_card_library/esd_can official website could not find the can_card_lib. maybe someone provide can_card lib information.  thks a lot

**Comment by mickeyouyou** [comment]
run 
```
bazel query //...
```

then try 
```
bash apollo.sh build
```

**Comment by zhxt** [comment]
Actually, I haven't saw an "error",  it's just a "[WARNING] ",
If you don't really need it, just ignore it would be fine :-P

**Comment by zhxt** [comment]
For "Building: no action running",  Please take a look at  #398
