### ISSUE TITLE
error loading package

### ISSUE THREAD

**Issue by liangzcamg** [ApolloAuto/apollo#2388]
ubun@in_dev_docker:/apollo$ sudo bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Extracting Bazel installation...
.....................
ERROR: error loading package '.cache/bazel/_bazel_root/install/5b1e8be5d1d6766f635a7db5967707e9/_embedded_binaries/embedded_tools/third_party/checker_framework_dataflow': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path
============================
[ERROR] Build failed!
[INFO] Took 19 seconds

**Comment by zhxt** [comment]
It seems some dependency are missing for bazel installation: [checker_framework_dataflow](https://github.com/bazelbuild/bazel/blob/master/third_party/checker_framework_dataflow/BUILD#L20)

And I'm a little curious that where did you learned to build Apollo with "sudo"?

**Comment by natashadsouza** [comment]
Currently closing this issue as there has been no response in a while.
