### ISSUE TITLE
apollo.sh build    ERRoR

### ISSUE THREAD

**Issue by chilihua** [ApolloAuto/apollo#2389]
chi@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Extracting Bazel installation...
...........................
Building: no action running
Building: no action running
Building: no action running
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/dreamview/backend/handlers/BUILD:23:1: no such package '@opencv2//': Error extracting /home/chi/.cache/bazel/_bazel_chi/540135163923dd7d5820f3ee4b306b32/external/opencv2/2.4.13.2.zip to /home/chi/.cache/bazel/_bazel_chi/540135163923dd7d5820f3ee4b306b32/external/opencv2: Zip file '2.4.13.2.zip' is malformed. It does not contain an end of central directory record. and referenced by '//modules/dreamview/backend/handlers:image'
ERROR: Analysis of target '//modules/dreamview/backend:backend' failed; build aborted

**Comment by zhxt** [comment]
It seems bazel dependency opencv2 is missing.

try to update with:
```
bazel fetch //...
```
and rebuild again.

**Comment by VinchinYang** [comment]
I have the same problem.
The Operation system I use is ubuntu 14.04 on Parallel of mac.

**Comment by chilihua** [comment]
Thanks for your help!
Today I did these:
    1.  bash apollo.sh clean
    2. bash apollo.sh build

[ OK ] Build passed!
