### ISSUE TITLE
Why planning in demo off from the lane center?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#2392]
Hi Apollo team,

In demo_2_0, I have seen that the planning trajectory is off from the lane center, especially when the vehicle making a corner. Is this intended?
Thank you.

**Comment by lianglia-apollo** [comment]
Yes, it is intended to keep a smoother trajectory.

**Comment by wckorealsh** [comment]
Thanks, can you please comment on these?


![curve1](https://user-images.githubusercontent.com/7061502/34689207-b83ecb6e-f482-11e7-8a6b-c08e942f9e58.png)
This looks trajectory is on the boundary?

![curve2](https://user-images.githubusercontent.com/7061502/34689206-b8307492-f482-11e7-9ebb-046415e015ee.png)
This looks like the vehicle made unintended lane change

![center1](https://user-images.githubusercontent.com/7061502/34689208-b84cf4b4-f482-11e7-8b47-1b3c5ac9473d.png)
Even in the straight lane, still offset is visible

**Comment by lianglia-apollo** [comment]
(1) The trajectory is possible to overlap with virtual lane boundaries.
(2) The lane change is determined in routing. Routing will provide a "lane change" area that encourages the vehicle to change lanes. The routing in this bag has two lane changes in this area for demonstration purposes.
(3) It is possible to off the center if the straight lane is connected with some turns.

**Comment by Zhenni17** [comment]
Hi @wckorealsh, I am the Community manager for Apollo project. I would love to connect with you to get some direct feedback from you about Apollo. Would you mind send me an email at wuzhenni01@baidu.com? Many thanks!

**Comment by jmtao** [comment]
@wckorealsh Hope @lianglia-apollo has answered your question. If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open an new issue if you have any more questions. 

Thank you for supporting Apollo!
