### ISSUE TITLE
Build error when execute bash apollo.sh build

### ISSUE THREAD

**Issue by lakeprince** [ApolloAuto/apollo#2399]
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 190 targets...
ERROR: /apollo/modules/control/tools/BUILD:31:1: C++ compilation of rule '//modules/control/tools:control_tester' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g '-std=c++0x' '-DUSE_ESD_CAN=false' -MD -MF ... (remaining 96 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 50.103s, Critical Path: 40.15s
============================
[ERROR] Build failed!

**Comment by Grayhu07** [comment]
This may be because that you don't have enough memory, you can try to add another memory card or try the build with less thread (which may take really long time to build) using this command: _$bash apollo.sh build -j 3_ . The number can be changed to whatever you want.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while.
