### ISSUE TITLE
bash apollo.sh build  error

### ISSUE THREAD

**Issue by szm88** [ApolloAuto/apollo#2403]
RROR: /apollo/modules/common/math/BUILD:138:1: no such package '@eigen//': Error downloading [https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz] to /home/szm/.cache/bazel/_bazel_szm/540135163923dd7d5820f3ee4b306b32/external/eigen/3.2.10.tar.gz: GET returned 500 Internal Server Error and referenced by '//modules/common/math:quaternion'
ERROR: Analysis of target '//modules/common/math:math' failed; build aborted

**Comment by alexiskovi** [comment]
@szm88, so, how did you solve this? Got the same problem, but with package @adv_plat//
