### ISSUE TITLE
What are variables cf,  cr means?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#2409]
In `mpc_controller_conf.proto`, what are `cf` and `cr` ?
If these are the variables with vehicle dynamics, can you include vehicle modeling to the upcoming documentation, please?
Thank you!

**Comment by hzdsdhr** [comment]
I guess cr means  center to rear distance, cf means center to front distance

**Comment by Capri2014** [comment]
@wckorealsh @hzdsdhr  It is vehicle corning stiffness, front wheels and rear wheels.

**Comment by wckorealsh** [comment]
Ah, great. Thank you!
