### ISSUE TITLE
Localization module init failurewith "Reflectance map folder is invalid"

### ISSUE THREAD

**Issue by louietsai** [ApolloAuto/apollo#2426]
Hi 
I built the Apollo v2.0.0 release, and tried to run it.
I can't run localization module and it failed at init state.
I saw a failure log "Reflectance map folder is invalid".
Do I miss anything to run localization module with msf mode?

thanks

**Comment by louietsai** [comment]
attached some error logs below.

E0111 15:59:00.154547  1618 msf_localization.cc:167] map: modules/map/data/sunnyvale_loop/local_map
E0111 15:59:00.154779  1618 msf_localization.cc:168] lidar_extrin: modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml
E0111 15:59:00.154788  1618 msf_localization.cc:169] lidar_height: modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
E0111 15:59:00.154805  1618 msf_localization.cc:198] Ant imu lever arm file: modules/localization/msf/params/gnss_params/ant_imu_leverarm.yaml
F0111 15:59:00.158637  1618 velodyne_locator_omp_alt_align.cc:170] Reflectance map folder is invalid!
*** Check failure stack trace: ***
^[[33m/apollo/rrrrrr/apollo-platform/ros/ros_comm/roscpp/src/libros/init.cpp:660 configParse() [ WARN] [1515715139.335782363]: transport file: /home/tmp/ros/etc/ros/transport_mode.yaml is not map^[[0m
^[[33m/apollo/rrrrrr/apollo-platform/ros/ros_comm/roscpp/src/libros/init.cpp:349 start() [ WARN] [1515715139.335892487]: Parse transport_mode file failed^[[0m

**Comment by startcode** [comment]
I guess the Lidar reflection map is missing.
Can you use RTK localization method for now?
in `modules/localization/conf//localization_config.pb.txt`, change `MSF` to `RTK`

We will add reflection map in docker asap.

**Comment by louietsai** [comment]
thank you! will change to RTK for now. 
how do we update the docker with new reflection map?
can we update by "docker/scripts/dev_start.sh" or using docker pull manually?

thanks!

**Comment by yellowpoplar** [comment]
http://data.apollo.auto/help?name=sensor%20data&data_key=multisensor&data_type=1&locale=en-us&lang=en
You can download reflection map and rosbags from this link.

**Comment by louietsai** [comment]
thanks!
after I got the data, and put the under folder /apollo/modules/map/data.
I can run msf localization module successfully when I select "demo" map.

regards
Louie

**Comment by YYimingWang** [comment]
> thanks!
> after I got the data, and put the under folder /apollo/modules/map/data.
> I can run msf localization module successfully when I select "demo" map.
> 
> regards
> Louie

hello,i also encountered this problem when i run the msf_localization modules.I download the data in http://data.apollo.auto/help?name=sensor%20data&data_key=multisensor&data_type=1&locale=en-us&lang=en 
and put the folder in apollo/data/
and then operated  according to this tutorial---https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer_cn.md
i copy the params to the corresponding folder and modify the path of map in localizaiton.conf to--map_dir=/apollo/data/data.
but i also encountered this problem as follows when i input command ./scripts/localization.sh start_fe.

`E0925 13:59:35.263833  2486 msf_localization.cc:150] map: /apollo_baidu/apollo/data/data//local_map
E0925 13:59:35.264330  2486 msf_localization.cc:151] lidar_extrin: modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml
E0925 13:59:35.264369  2486 msf_localization.cc:152] lidar_height: modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
W0925 13:59:35.264410  2486 msf_localization.cc:160] Can't load utm zone id from map folder, use default value.
I0925 13:59:35.264436  2486 msf_localization.cc:163] utm zone id: 10
I0925 13:59:35.264461  2486 msf_localization.cc:179] Vehile imu file: modules/localization/msf/params/vehicle_params/vehicle_imu_extrinsics.yaml
I0925 13:59:35.265157  2486 msf_localization.cc:190] imu_vehicle_quat: 0 0 0 1
E0925 13:59:35.265215  2486 msf_localization.cc:217] Ant imu lever arm file: modules/localization/msf/params/gnss_params/ant_imu_leverarm.yaml
I0925 13:59:35.265882  2486 msf_localization.cc:229] 0 0.71 1.08 0.05 0.05 0.08
F0925 13:59:35.266727  2486 localization_lidar.cc:58] Reflectance map folder is invalid!
`

can you help me?than you!

**Comment by mengen100** [comment]
I can't download the dataset from this link... 
http://data.apollo.auto/help?name=sensor%20data&data_key=multisensor&data_type=1&locale=en-us&lang=en
After I click on download, it shows me the "NoSuchKey"
![ss2](https://user-images.githubusercontent.com/62421236/111417181-b47c8d80-86bb-11eb-8c44-0e6ba9cf46d2.png)

![ss1](https://user-images.githubusercontent.com/62421236/111417353-13420700-86bc-11eb-88b3-3eb3e1e4a523.png)


Could anyone help me, else I can't run the msf localization module... Thanks in advance

**Comment by lovelydett** [comment]
The link [http://data.apollo.auto](http://data.apollo.auto)  is invalid now.
