### ISSUE TITLE
[planning module]What is the default planner of planning module?

### ISSUE THREAD

**Issue by hzdsdhr** [ApolloAuto/apollo#2429]
rtk planner or EM planner? I check the conf file(modules/planning/conf/planning_config.pb.txt), there is only configs for EM planner, does this mean the planner being used is the EM planner? If I want to use rtk planner, what should I add to the conf file?

**Comment by lianglia-apollo** [comment]
yes, the default is EM. You can change the conf file to use rtk planner according to the proto (apollo/modules/planning/proto/planning_config.proto).

**Comment by hzdsdhr** [comment]
@lianglia-apollo Thank you! Should I just change planner_type from EM to RTK and leave everything else the same? . I simply want to make the car do the waypoint following
