### ISSUE TITLE
how to get liblocalization_msf_local_integ.so outside docker environment???

### ISSUE THREAD

**Issue by jianglinchun** [ApolloAuto/apollo#2430]
Due to this issue:
https://github.com/ApolloAuto/apollo/issues/1751
The .so library is not open source.
So which way is the best way to build apollo outside docker??
* Official offer a mock implement of this ???
* Open the header file and we guys write one mock implement??
* Contact your BD mates? and the email address???

Whiteout the source code it's impossible to cross-compile on the other platform??....

So flowing the readme??? Anyone had done the FooLocalization???

---------------------------------------

# Localization

## Introduction
  This module provides localization service. There are two methods provided by default. One is RTK(Real Time Kinematic) based method which incorporates GPS and IMU information, the other is multi-sensor fusion method which incorporates GPS, IMU, and LiDAR information.

## Input
  In the provided RTK localization method, there are two inputs:
  * GPS - The Global Position System.
  * IMU - Inertial Measurement Unit.
  
  In the provided multi-sensor fusion localization method, there are three inputs:
  * GPS - The Global Position System.
  * IMU - Inertial Measurement Unit.
  * LiDAR - Light Detection And Ranging Sensor.
  For more information, refer to [multi-sensor fusion localizaiton](https://github.com/ApolloAuto/apollo/tree/master/modules/localization/msf/README.md).

## Output
  * An object instance defined by Protobuf message `LocalizationEstimate`, which can be found in file `localization/proto/localization.proto`.

## Add localization implementation
  Currently the RTK based localization is implemented in class `RTKLocalization`. If a new localization method need to be implemented with a name such as `FooLocalization`, you can follow the following steps:

  1. In `proto/localization_config.proto`, add `FOO` in the `LocalizationType` enum type.

  1. Go to the `modules/localization` directory, and create a `foo` directory. In the `foo` directory, implement class `FooLocalization` following the `RTKLocalization` class in the `rtk` directory. `FooLocalization` has to be a subclass of `LocalizationBase`. Also create file foo/BUILD following file `rtk/BUILD`.

  1. You need to register `FooLocalizatoin` class in function `Localization::RegisterLocalizationMethods()`, which is located in cpp file `localization.cc`. You can register by inserting the following code at the end of the function:
  
  ```
  localization_factory_.Register(LocalizationConfing::FOO, []()->LocalizationBase* { return new FooLocalization(); });
  ```
  
  Make sure your code can be compiled by including the header files that defines class `FooLocalization`.

  1. Now you can go back to the `apollo` root directory and build your code with command `bash apollo.sh build`.

---------------------------------------

**Comment by zhxt** [comment]
Copy the header and lib  files out from docker would be one option.
With docker running:
```
docker cp  apollo_dev:/usr/local/local_integ/ /path/to/save/
```

**Comment by jianglinchun** [comment]
@zhxt Thank you for your advice.
But what I mean is cross compile.
The docker is working under ubuntu x86_64
I's trying to port apollo to other platform such as nvidia tegra tk1
So it's very important to build without docker.

**Comment by wallr1985** [comment]
@jianglinchun , Thank you for your interests in our msf localization module. This module is not open source, but open capability. We shipped the binary library in a docker, so that the user can test it. We also provide a simple map building tool. The user can test the localization module with this own data. We don't have technical support for each individual user. But if you are an Apollo partner, we can help you by providing a binary in your platform. The formal request can be sent to idg-apollo@baidu.com. Thank you.

**Comment by songshiyu01** [comment]
@jianglinchun Thank you for your interests in our msf localization module. The module is not open source, but open capability. We shipped the module in a docker, and provided a simple mapping tool with it. The user can test it with their own data. We don't have technical support for individual user, but if you are an Apollo partner, we can help you by providing a compiled binary in your platform. The formal request could be sent to idg-apollo@baidu.com.

**Comment by natashadsouza** [comment]
Closing this issue as the issue seems to be resolved.
