### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by zhaohuijun** [ApolloAuto/apollo#2431]
when I run  /apollo/bazel-bin/modules/dreamview/dreamview
got  **Illegal instruction**  and process killed.

stack: 
Program received signal SIGILL, Illegal instruction.
0x0000000000c81172 in std::_Hashtable<std::string, std::string, std::allocator<std::string>, std::__detail::_Identity, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_Hashtable (this=0x161ea88, __bucket_hint=10, __h1=..., __h2=..., __h=..., __eq=..., __exk=..., __a=...) at /usr/include/c++/4.8/bits/hashtable.h:828
828           _M_rehash_policy()

#0  0x0000000000c81172 in std::_Hashtable<std::string, std::string, std::allocator<std::string>, std::__detail::_Identity, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_Hashtable (this=0x161ea88, __bucket_hint=10, __h1=..., __h2=..., __h=..., __eq=..., __exk=..., __a=...) at /usr/include/c++/4.8/bits/hashtable.h:828
#1  0x0000000000c79cb3 in std::_Hashtable<std::string, std::string, std::allocator<std::string>, std::__detail::_Identity, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_Hashtable (this=0x161ea88, __n=10, __hf=..., __eql=..., __a=...) at /usr/include/c++/4.8/bits/hashtable.h:397
#2  0x0000000000c73205 in std::unordered_set<std::string, google::protobuf::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> >::unordered_set (
    this=0x161ea88, __n=10, __hf=..., __eql=..., __a=...) at /usr/include/c++/4.8/bits/unordered_set.h:136
#3  0x0000000000c6da58 in google::protobuf::hash_set<std::string, google::protobuf::hash<std::string>, std::equal_to<std::string> >::hash_set (this=0x161ea88)
    at external/com_google_protobuf/src/google/protobuf/stubs/hash.h:388
#4  0x0000000000c43708 in google::protobuf::DescriptorPool::Tables::Tables (this=0x161ea70) at external/com_google_protobuf/src/google/protobuf/descriptor.cc:778
#5  0x0000000000c4513a in google::protobuf::DescriptorPool::DescriptorPool (this=0x161e9d0, fallback_database=0x161e910, error_collector=0x0)
    at external/com_google_protobuf/src/google/protobuf/descriptor.cc:1203
#6  0x0000000000c454a1 in google::protobuf::(anonymous namespace)::InitGeneratedPool () at external/com_google_protobuf/src/google/protobuf/descriptor.cc:1265
#7  0x0000000000da0c85 in google::protobuf::internal::FunctionClosure0::Run (this=0x7fffffffe2b0) at external/com_google_protobuf/src/google/protobuf/stubs/callback.h:129
#8  0x0000000000da27ce in google::protobuf::GoogleOnceInitImpl (once=0x14aa6b0 <google::protobuf::(anonymous namespace)::generated_pool_init_>, closure=0x7fffffffe2b0)
    at external/com_google_protobuf/src/google/protobuf/stubs/once.cc:83
#9  0x00000000004adfb5 in google::protobuf::GoogleOnceInit (once=0x14aa6b0 <google::protobuf::(anonymous namespace)::generated_pool_init_>,
    init_func=0xc4545a <google::protobuf::(anonymous namespace)::InitGeneratedPool()>) at external/com_google_protobuf/src/google/protobuf/stubs/once.h:128
#10 0x0000000000c4550d in google::protobuf::(anonymous namespace)::InitGeneratedPoolOnce () at external/com_google_protobuf/src/google/protobuf/descriptor.cc:1272
#11 0x0000000000c4554b in google::protobuf::DescriptorPool::InternalAddGeneratedFile (
    encoded_file_descriptor=0xdda800 <apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::AddDescriptorsImpl()::descriptor>, size=1236)
    at external/com_google_protobuf/src/google/protobuf/descriptor.cc:1313
#12 0x00000000004a2dcc in apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::AddDescriptorsImpl ()
    at bazel-out/local-dbg/genfiles/modules/dreamview/proto/hmi_config.pb.cc:282
#13 0x0000000000da0c85 in google::protobuf::internal::FunctionClosure0::Run (this=0x7fffffffe3e0) at external/com_google_protobuf/src/google/protobuf/stubs/callback.h:129
#14 0x0000000000da27ce in google::protobuf::GoogleOnceInitImpl (
    once=0x13fa070 <apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::AddDescriptors()::once>, closure=0x7fffffffe3e0)
    at external/com_google_protobuf/src/google/protobuf/stubs/once.cc:83
#15 0x00000000004adfb5 in google::protobuf::GoogleOnceInit (
    once=0x13fa070 <apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::AddDescriptors()::once>,
    init_func=0x4a2db2 <apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::AddDescriptorsImpl()>)
    at external/com_google_protobuf/src/google/protobuf/stubs/once.h:128
#16 0x00000000004a2e0a in apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::AddDescriptors ()
    at bazel-out/local-dbg/genfiles/modules/dreamview/proto/hmi_config.pb.cc:290
#17 0x00000000004af7a7 in apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::StaticDescriptorInitializer::StaticDescriptorInitializer (
    this=0x13f9f98 <apollo::dreamview::protobuf_modules_2fdreamview_2fproto_2fhmi_5fconfig_2eproto::static_descriptor_initializer>)
    at bazel-out/local-dbg/genfiles/modules/dreamview/proto/hmi_config.pb.cc:295
#18 0x00000000004ada09 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at bazel-out/local-dbg/genfiles/modules/dreamview/proto/hmi_config.pb.cc:297
#19 0x00000000004ada1e in _GLOBAL__sub_I_hmi_config.pb.cc(void) () at bazel-out/local-dbg/genfiles/modules/dreamview/proto/hmi_config.pb.cc:3427
#20 0x0000000000dcf70d in __libc_csu_init ()
#21 0x00007ffff24b7ed5 in __libc_start_main (main=0x45f2cd <main(int, char**)>, argc=1, argv=0x7fffffffe598, init=0xdcf6c0 <__libc_csu_init>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe588) at libc-start.c:246
#22 0x000000000045f209 in _start ()

**Comment by louietsai** [comment]
got similar error when I compiled/ran on Intel Atom CPU, but work fine on Intel Core CPU.

**Comment by natashadsouza** [comment]
Please refer to the updated Apollo documentation in Github to resolve the issue.
