### ISSUE TITLE
./docker/script/dev_start.sh  apollo_2    提示：Warning: Unknown option: apollo_2

### ISSUE THREAD

**Issue by lhh0916** [ApolloAuto/apollo#2432]
idriver@idriver-System:~/apollo-master-2$ **./docker/scripts/dev_start.sh apollo_2**
Warning: Unknown option: apollo_2

idriver@idriver-System:~/apollo-master-2$ **./docker/scripts/dev_start.sh **-image** apollo_2**
[INFO] Start pulling docker image apolloauto/apollo:apollo_2 ...
Error response from daemon: manifest for apolloauto/apollo:apollo_2 not found
[ERROR] Failed to pull docker image.

我确定已经执行了docker commit xxxxx apolloauto/apollo：apollo_2，但是无法pull
请教各位大神，非常感谢！

**Comment by zhxt** [comment]
@lhh0916 Could you please paste the output of "docker image ls" ?

**Comment by lhh0916** [comment]
@zhxt 谢谢你回答我的问题，以下是'docker image ls' 的输出：
REPOSITORY                                                                TAG                               IMAGE ID            CREATED             SIZE
apolloauto/apollo                                                         apollo_2.0                        65c79a253ae6        2 days ago          12.1GB
<none>                                                                    <none>                            b937b3fd273f        2 days ago          12.1GB
apolloauto/apollo                                                         apollo_2                          e0aab297d798        2 days ago          12.1GB

我又下载apollov2.0版本的github源码，是可以pull的，./docker/scripts/dev_start.sh -image apollo_2命令是可以进去的；但是master版的github源码就会提示上述的错误，应该是dev_start.sh脚本问题，但我不确定具体原因。你可以帮我解答吗？谢谢啦☺

**Comment by zhxt** [comment]
@lhh0916 
Did you push your image to docker hub?  
猜测你是本地提交了，但是没有push到docker hub上。

**Comment by xiaoxq** [comment]
Commit是保存image到本地，名字是 apolloauto/apollo:apollo_2，并没有推送到docker hub上。（当然，这是你的私人image，不需要推送上去，也没有权限推送。）

当执行 ./docker/scripts/dev_start.sh apollo_2 时，脚本会先去docker hub上寻找这个tag，发现不存在，打印了一条error信息，但是它还是会以这个tag来启动container，所以当你执行“docker ps”时应该可以看到apollo_dev容器的image确实是"apolloauto/apollo:apollo_2".

**Comment by zhxt** [comment]
@lhh0916 就是@xiaoxq 同学说的这样。 我知道是为什么了，当pull失败时，后面的步骤就不再执行了。我挖的坑我来填吧【允悲】， 你先把[dev_start.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L105)第105行注释掉，应该就可以了。 

考虑加一个 -l  （local) 参数跳过pull的步骤，可以么? @xiaoxq 
或者就改成和原来一样，pull失败继续执行？

**Comment by zhxt** [comment]
如果明确知道是本地镜像docker hub上不存在, 无需再等pull失败再继续。

**Comment by zhxt** [comment]
hmm, considering using -t|--tag to replace -image @.@

**Comment by lhh0916** [comment]
ok，已经成功解决问题了。抱歉各位，最近工作比较忙，现在才跟apollo这块。github上apollo v2.0版本是提示pull失败，但进去是成功pull之后的docker内容。apollo-master版本需要注释到 exit 1（105行），using -t|--tag to replace -image 没有尝试成功，不过问题解决，Thank you！ @zhxt @xiaoxq

**Comment by zhxt** [comment]
@lhh0916
哈哈，tag那个我还没有提交。
现在可以不用注释第105行了，加一个-l参数就可以了。
