### ISSUE TITLE
Missing a setter function for boolean member variable integrator_hold_ in class PIDController

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#2437]
The member variable **integrator_hold_** is set to be **false** when its instance is created. There is one getter function defined
```
bool PIDController::IntegratorHold() const {
    return integrator_hold_;
}
```
but not a setter. The PidConf proto as shown below does not have an attribute to config it.
```
syntax = "proto2";

package apollo.control;

message PidConf {
  optional bool integrator_enable = 1;
  optional double integrator_saturation_level = 2;
  optional double kp = 3;
  optional double ki = 4;
  optional double kd = 5;
  optional double kaw = 6 [default = 0.0];
  optional double output_saturation_level = 7;
}
```
Two inherited classes PIDCBController and PIDICController do not use it either.

**Comment by jilinzhou** [comment]
missed the integrator_enable defined in PidConf.

**Comment by lianglia-apollo** [comment]
I think it is used in pid_controller.cc line 42 - 54.

**Comment by jilinzhou** [comment]
Sorry I didn't make it clear. Since its value cannot be changed (being false after the instance is created),  the condition check in the code always returns true. Therefore, there is no need of the variable.

**Comment by jilinzhou** [comment]
Sorry I didn't make it clear. Since its value cannot be changed (being false after the instance is created),  the condition check in the code always returns true. Therefore, there is no need of the variable.

**Comment by lianglia-apollo** [comment]
Yes, you are correct. It is indeed redundant. We will remove it, or you can submit a pull request if interested.

**Comment by Capri2014** [comment]
You are right. There should be corespondent setter function for it. With intension to hold integrator when saturate. I will submit the code once get back or feel free to create pull request for the corrections.
