### ISSUE TITLE
How to run Apollo docker on Mac OS?

### ISSUE THREAD

**Issue by livc** [ApolloAuto/apollo#244]
I'm sorry that I don't understand why there ere so many scrips to run docker...

**Comment by a627938936** [comment]
The author has not been tested yet. It would be best if you could help with the test

**Comment by garyaiki** [comment]
install_docker.sh looks to be Linux only. Is there a way to install on OS X?

**Comment by jinghaomiao** [comment]
@garyaiki It is not designed to run on Mac. Even the docker images are not built to run on Mac OS yet.

**Comment by xiaoxq** [comment]
Duplicate with #47 

BTW, we have added basic support for Mac. Have fun!
https://github.com/ApolloAuto/apollo/tree/master/docker/scripts/mac

**Comment by tarsh** [comment]
what's this error, when building in MacOS as suggested.

[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/localization/msf/BUILD:5:1: no such package '@local_integ//': Expected directory at /usr/local/apollo/local_integ but it does not exist. and referenced by '//modules/localization/msf:msf_localization'
ERROR: Analysis of target '//modules/localization:localization_lib' failed; build aborted
INFO: Elapsed time: 7.567s
FAILED: Build did NOT complete successfully (11 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 124 seconds

**Comment by tarsh** [comment]
should change the directory in the docker env make build to find it as below:

# Local-integ
new_local_repository(
    name = "local_integ",
    build_file = "third_party/local_integ.BUILD",
    path = "/usr/local/local_integ",
)

**Comment by zhxt** [comment]
@tarsh  I think the docker image is out of date, so at this time,  please re-try to add a parameter "dev-x86_64-20180130_1338" when you run the script "dev_start.sh".

**Comment by jagjotsinghparry** [comment]
@zhxt Even after this, I am having the same issue when trying to build it 😞
