### ISSUE TITLE
Failed to start HMI?

### ISSUE THREAD

**Issue by zgliuwen** [ApolloAuto/apollo#245]
如题所述，请问该如何操作？

**Comment by xiaoxq** [comment]
请仔细描述问题。
比如是否执行了文档中要求的步骤，在docker中执行了
`bash apollo.sh build`
以及HMI报错时的输出等。

**Comment by zgliuwen** [comment]
谢谢你的回复。我已经把命令运行时的图片截图，上传到百度云里了，你这边可以通过这个链接看下，谢谢
链接: https://pan.baidu.com/s/1mhNLgFm 密码: k3fr

**Comment by siyangy** [comment]
You can just upload your screenshot here or just paste the error message on your terminal.

**Comment by xiaoxq** [comment]
![build_failure](https://user-images.githubusercontent.com/6193298/28546963-86fca3f8-7081-11e7-89ba-68864624501a.png)

@siyangy I picked an image from the pan.baidu.com. Looks like a bazel build failure. Sometimes the build fails while still reports "Build passed!", which is confusing.

@zgliuwen 这个apollo.sh build的执行是失败的（见上），请重新启动一个docker container尝试一下编译。正确的输出应该是“Found 1xx targets...”并且"build passed"，而不是“Found 0 targets”，这样是bazel出了问题。

**Comment by siyangy** [comment]
@xiaoxq This is a known issue and has been fixed by https://github.com/ApolloAuto/apollo/pull/248.

**Comment by xiaoxq** [comment]
Great! Let's wait for @zgliuwen 's feedback of re-building.

**Comment by siyangy** [comment]
@zgliuwen Please check your network connection. The issues is that your machine was unable to connect to the remote host to pull one of the dependencies build needs. I am not sure restarting a docker container can solve this.
