### ISSUE TITLE
Guide for bash settings

### ISSUE THREAD

**Issue by VAMANACHARYA** [ApolloAuto/apollo#2450]
Please guide me to do bash settings in Windows 7

**Comment by xiaoxq** [comment]
We use Linux-based docker container for development and release. So on Windows you may have to run a virtual machine.

**Comment by jianglinchun** [comment]
have you had tried wsl(windows subsystem for linux)??? @xiaoxq

**Comment by xiaoxq** [comment]
Yes, I tasted a bit last year, but didn't try Apollo on it. Please kindly let us know if it works, or not :)

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while.
