### ISSUE TITLE
Inconsistency in between comments and actual code in class Control::Start()

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#2459]
Here is the code inside control.cc
```
Status Control::Start() {
  // set initial vehicle state by cmd
  // need to sleep, because advertised channel is not ready immediately
  // simple test shows a short delay of 80 ms or so
  AINFO << "Control resetting vehicle state, sleeping for 1000 ms ...";
  std::this_thread::sleep_for(std::chrono::milliseconds(1));
...
```
The log suggests to sleep 1000ms but the code sleeps for 1ms. Of course, the actual sleep time depends on the thread scheduling during runtime.

**Comment by jilinzhou** [comment]
As a side discussion, are there any special reasons to have _class ControllerAgent_ defined since it is simply a wrapper for _common::util::Factory<ControlConf::ControllerType, Controller> controller_factory__ from the perspective of functionalities? How about move its declaration of controller_factory_ inside _class Controller_ directly to be consistent with other other modules such as _class Canbus_ and _class Localization_?

**Comment by lianglia-apollo** [comment]
For the sleep time, it is a very common misunderstanding ... ...

Please note that 1ms is 1 'micro' second, or 0.001 'milli' second.

**Comment by jilinzhou** [comment]
aha!  I often use 'us' to represent microsecond and 'ms' for millisecond (https://en.wikipedia.org/wiki/Microsecond).
