### ISSUE TITLE
NVIDIA driver installation error because of Nouveau kernel driver is in use.

### ISSUE THREAD

**Issue by WelfredJiang** [ApolloAuto/apollo#2466]
After installed Apollo Kernel,  i am going to install NVIDIA driver in dev_docker, but this error `occurs:`

ERROR: The Nouveau kernel driver is currently in use by your
       system.  This driver is incompatible with the NVIDIA
       driver, and must be disabled before proceeding.  Please
       consult the NVIDIA driver README and your Linux
       distribution's documentation for details on how to
       correctly disable the Nouveau kernel driver.

ERROR: Installation has failed.  Please see the file
       '/var/log/nvidia-installer.log' for details.  You may find
       suggestions on fixing installation problems in the README
       available on the Linux driver download page at
       www.nvidia.com.

**Comment by WelfredJiang** [comment]
Outside docker
+ uname -a
Linux jwf-HP 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
+ docker --version
Docker version 17.05.0-ce, build 89658be
+ docker images
+ grep apollo
apolloauto/apollo                          local_release           d3ae4a47449a        18 hours ago        7.19GB
registry.docker-cn.com/apolloauto/apollo   release-x86_64-v2.0.0   7475cf7a955c        2 weeks ago         7.19GB
apolloauto/apollo                          release-x86_64-v2.0.0   7475cf7a955c        2 weeks ago         7.19GB
apolloauto/apollo                          dev-x86_64-v2.0.0       532e2c8a3925        2 weeks ago         11.8GB
+ echo -----------env---------------
-----------env---------------
+ env
XDG_VTNR=7
XDG_SESSION_ID=c8
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/jwf
CLUTTER_IM_MODULE=xim
SESSION=ubuntu
GPG_AGENT_INFO=/home/jwf/.gnupg/S.gpg-agent:0:1
VTE_VERSION=4205
XDG_MENU_PREFIX=gnome-
TERM=xterm-256color
SHELL=/bin/bash
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
WINDOWID=69206026
GNOME_KEYRING_CONTROL=
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/10055
GTK_MODULES=gail:atk-bridge:unity-gtk-module
USER=jwf
QT_ACCESSIBILITY=1
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
SESSION_MANAGER=local/jwf-HP:@/tmp/.ICE-unix/10275,unix/jwf-HP:/tmp/.ICE-unix/10275
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
DESKTOP_SESSION=ubuntu
PATH=/home/jwf/bin:/home/jwf/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
QT_QPA_PLATFORMTHEME=appmenu-qt5
QT_IM_MODULE=fcitx
PWD=/home/jwf/apollo/scripts
JOB=unity-settings-daemon
XDG_SESSION_TYPE=x11
XMODIFIERS=@im=fcitx
LANG=zh_CN.UTF-8
GNOME_KEYRING_PID=
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
GDM_LANG=zh_CN
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
GDMSESSION=ubuntu
GTK2_MODULES=overlay-scrollbar
SESSIONTYPE=gnome-session
SHLVL=2
XDG_SEAT=seat0
HOME=/home/jwf
LANGUAGE=zh_CN:zh
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
UPSTART_INSTANCE=
LOGNAME=jwf
XDG_SESSION_DESKTOP=ubuntu
UPSTART_EVENTS=xsession started
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-BXz2mSxbeE
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
QT4_IM_MODULE=fcitx
APOLLO_HOME=/home/jwf/apollo
LESSOPEN=| /usr/bin/lesspipe %s
UPSTART_JOB=unity7
INSTANCE=
DISPLAY=:0
XDG_RUNTIME_DIR=/run/user/1000
GTK_IM_MODULE=fcitx
XDG_CURRENT_DESKTOP=Unity
LESSCLOSE=/usr/bin/lesspipe %s %s
XAUTHORITY=/home/jwf/.Xauthority
_=/usr/bin/env

**Comment by lianglia-apollo** [comment]
I also noticed this error when installing nvidia driver. You can try install cuda 8.0 without nvidia drivers, and it will automatically find and install a driver for you.

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
