### ISSUE TITLE
[complier]third_party/CoinIpotp/ThirdParty need fortran 90 complier ???

### ISSUE THREAD

**Issue by jianglinchun** [ApolloAuto/apollo#2467]
Will you please give us a list of your complier environment setup?? I mean the official of Baidu:
Such as fortran complier? gcc version?
CC
FC
……
Or there has some complier are commercial ?? such as:
https://www.absoft.com/products/osx-fortran-compiler-suite/
https://www.nag.com/nag-compiler
……

**Comment by startcode** [comment]
This is my compile script on ubuntu, hope it helps :-)

```
set -e

sudo apt-get install libblas-dev liblapack-dev gfortran

package="Ipopt-3.12.8.zip"

if [ ! -f $package ]; then
    wget https://www.coin-or.org/download/source/Ipopt/$package -O $package
fi

package_dir=${package%.*}

rm -rf $package_dir
unzip $package

# run get.Mumps
cd $package_dir
cd ThirdParty/Mumps && bash get.Mumps && cd ../../

HOST=""
if [ $(uname -m) == "aarch64" ]; then
    HOST="arm"
elif [ $(uname -m) == "x86_64" ]; then
    HOST="x86_64"
else
    echo "Unknown Host $(uname -m)"
    exit 0


./configure --build=$HOST

make all

make install
```

**Comment by jianglinchun** [comment]
Thank you so much. @startcode 
I'm working on Mac OS X El captain.
https://github.com/coin-or/Ipopt/issues/17
