### ISSUE TITLE
ros-indigo-catkin not available

### ISSUE THREAD

**Issue by rishi8313** [ApolloAuto/apollo#247]
I am trying the non-docker way to setup the environment

I was able to do everything from start to the point where I need to install ros-indigo-catkin.

Has the package name changed.?

**Comment by startcode** [comment]
You can install by `sudo apt-get install ros-indigo-catkin`, if you are using Ubuntu.

The following files have some install and configuration clues

https://github.com/ApolloAuto/apollo/blob/master/WORKSPACE.in
https://github.com/ApolloAuto/apollo/blob/master/docker/dev.x86_64.dockerfile

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
