### ISSUE TITLE
I can not start module monitor in apollo 2.0. Help~

### ISSUE THREAD

**Issue by jinpingfan** [ApolloAuto/apollo#2471]
By the end of the 1.5 version, it can all run perfectly......
I update the update in order 1.5.1；1.5.2..........2.0.0 but I can not start DEMO module monitor in apollo 2.0
（I don't understand why the kernel version still stays in 1.5.......
![image](https://user-images.githubusercontent.com/31611582/34976198-60c95792-fad0-11e7-9188-9d8348d87207.png)
）
and I can not download 2.0 Demo bag on line......
![image](https://user-images.githubusercontent.com/31611582/34976233-92ff9d16-fad0-11e7-8878-2b43b8674420.png)
Please help me.......I don't know where the problem is.

**Comment by startcode** [comment]
Can you try to download the 2.0 bag by this command?
```
wget https://github.com/ApolloAuto/apollo/releases/download/v2.0.0/demo_2.0.bag
```

**Comment by jinpingfan** [comment]
yap......But what is more important is command “bash scripts/bootstrap.sh” 
Cannot be executed

**Comment by startcode** [comment]
The bootstrap.sh is in the latest repo. Somehow it is not in your local file system.
```
https://github.com/ApolloAuto/apollo/blob/master/scripts/bootstrap.sh
```

My guess is that you are still using apollo 1.5 code.
Can you double check the `git branch` and `git log` output?

**Comment by jinpingfan** [comment]
Thank you, sir. You're right, I'm still running the 1.5 version of the program, but I've updated the Platform to 2.0.0 according to the instructions.......

**Comment by startcode** [comment]
@jinpingfan can you let me know which instruction has confused you? I think we should correct them. Thanks

**Comment by jinpingfan** [comment]
![Uploading image.png…]()

**Comment by jinpingfan** [comment]
![image](https://user-images.githubusercontent.com/31611582/34977453-80915d4a-fad5-11e7-9bfa-cd5b8c944361.png)

**Comment by jinpingfan** [comment]
On the basis of 1.5：
Download：ros-indigo-apollo-2.0.0-x86_64.tar.gz：
https://github.com/ApolloAuto/apollo-platform/releases

tar zxvf ros-indigo-apollo-1.0.0.x86_64.tar.gz
rsync -av ros/ ~/apollo/third_party/ros_x86_64
source ~/apollo/third_party/ros_x86_64/setup.bash

2.bash docker/scripts/dev_start.sh

3.bash docker/scripts/dev_into.sh

4.bash apollo.sh build

5.bash scripts/bootstrap.sh

**Comment by richtong** [comment]
Is the build step now required for Apollo 2.0?

**Comment by lianglia-apollo** [comment]
Yes, it is required to run bash apollo.sh build before calling bootstrap.sh

**Comment by richtong** [comment]
You might want to update the Readme which is unclear. I can fix this and issue a PR if you like. Also have outstanding work to allow logo and skinning changes to dreamview which we need for integration into our systems. Thanks for the great work!

Thanks,
Rich

Sent from my iPhone X
http://tongfamily.com | @richtong | https://fb.me/richtong1

**Comment by richtong** [comment]
I think part of the problem is the README.md is a little unclear for new people like me. We have fixed the instructions in our fork, would the main project be interested in a PR on this, might help as I see lots of folks struggling with how to make this work.

**Comment by xiaoxq** [comment]
That is great!

Please send the PR. Thanks!

**Comment by richtong** [comment]
Sending now. Hopefully will visit with you all soon in your sunnyvale Office :-)

Thanks,
Rich

Sent from my iPhone X
http://tongfamily.com | @richtong | https://fb.me/richtong1

**Comment by richtong** [comment]
Just sent

**Comment by jinpingfan** [comment]
@richtong @xiaoxq Thank you for your stronly support~ Looking forward to a detailed description of the document for the update~ THX~

**Comment by richtong** [comment]
Thank you very much for working on such a terrific product.

Thanks,
Rich

Sent from my iPhone X
http://tongfamily.com | @richtong | https://fb.me/richtong1

**Comment by Zhenni17** [comment]
Bug resolved and PR was accepted. Closed the issue.
