### ISSUE TITLE
LaneSegment 中的lane的起始点和结束点问题

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#2474]
在routing.proto中LaneSegment消息中的lane point起始点和结束点为什么是用一个标量类型double描述，而不是用二维坐标表示？

**Comment by startcode** [comment]
```
message LaneSegment {
    optional string id = 1;
    optional double start_s = 2;
    optional double end_s = 3;
  }
```
In this proto, `id` is actually the lane's id. Once the id has been specified, we only need to specify the start_s and end_s on the lane.

**Comment by ahuer2435** [comment]
了解了，谢谢。
