### ISSUE TITLE
modprobe: FATAL: Module nvidia not found. 

### ISSUE THREAD

**Issue by liangzcamg** [ApolloAuto/apollo#2484]
liangzc@ubuntu:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
liangzc@ubuntu:~$ bash docker/scripts/dev_start.sh
bash: docker/scripts/dev_start.sh: No such file or directory
liangzc@ubuntu:~$ cd apollo
liangzc@ubuntu:~/apollo$ bash docker/scripts/dev_start.sh
[sudo] password for liangzc: 
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20180103_1300 ...
dev-x86_64-20180103_1300: Pulling from apolloauto/apollo
Digest: sha256:257b4864ea7c4d865b9674fba2a2cf9b3865d6298b1aa26c7fda09990d2f23e4
Status: Image is up to date for apolloauto/apollo:dev-x86_64-20180103_1300
modprobe: FATAL: Module nvidia not found.
modprobe: FATAL: Module nvidia-uvm not found.
[INFO] Starting docker container "apollo_dev" ...
bbe700d7db22da4e70423fb23132867efdb1173184886c1bbccece9c3a96d42f
bash: /apollo/scripts/docker_adduser.sh: Permission denied
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
liangzc@ubuntu:~/apollo$

**Comment by quning78** [comment]
Please follow the instructions of  "Installing NVIDIA GPU Driver" in the manual below:

https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
