### ISSUE TITLE
docker environment set: logout and login back can't make the docker run command without sudo 

### ISSUE THREAD

**Issue by WelfredJiang** [ApolloAuto/apollo#2488]
while running the following code:
```
bash docker/scripts/install_docker.sh
# logout and login back in the system to make sure to run docker command without sudo
docker ps  # to verify docker works without sudo
# in case you forgot to logout and login back, do so, remove ~/.docker/config.json
# and check again with `docker ps`
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
```
after i run the code 
`bash docker/scripts/install_docker.sh`
and reboot my computer,
it shows this code also need sudo command:`bash `docker/scripts/dev_start.sh``
```
jwf@jwf-HP:~$ cd $APOLLO_HOME
jwf@jwf-HP:~/apollo$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
jwf@jwf-HP:~/apollo$ bash docker/scripts/dev_start.sh
[sudo] jwf 的密码： 
jwf@jwf-HP:~/apollo$ bash docker/scripts/dev_into.sh
unable to find user jwf: no matching entries in passwd file
```
is that correct?

**Comment by wfgsy101** [comment]
also meet error : unable to find user xxx: no matching entries in passwd file, 
you need to add  user to docker, try below two command 
sudo groupadd docker
sudo usermod -aG docker $USER
next , you need to restart the docker by below 2 command 
sudo service docker stop
sudo service docker start
and now you could follow below step without sudo command
bash docker/scripts/dev_start.sh  -C
bash scripts/bootstrap.sh
