### ISSUE TITLE
Running perception module on CPU

### ISSUE THREAD

**Issue by kikacaty** [ApolloAuto/apollo#2489]
Is it possible? I can change the rosbag time stamp to resolve the latency issue.

**Comment by lianglia-apollo** [comment]
The default apollo.sh build is CPU version. It should work except the lower speed.

**Comment by kikacaty** [comment]
@lianglia-apollo I tried to run perception node in both dreamview and through scripts but it failed, even if I replay the messages from the sensors. Is it possible to find the error log somewhere? Thanks!

**Comment by lianglia-apollo** [comment]
The error log is placed under data/log/perception.xxxx

**Comment by kikacaty** [comment]
@lianglia-apollo Thanks! I found the log but it turns out to have been caught by core dumped error of Illegal instruction. Any clue on that?

**Comment by lianglia-apollo** [comment]
Could you post the core information? Meanwhile, let me ask someone in perception team to help.

**Comment by kikacaty** [comment]
@lianglia-apollo 
I am running the following script extracted from `apollo_base.sh`

```
nohup /apollo/bazel-bin/modules/perception/perception --flagfile=modules/perception/conf/perception.conf  --log_dir=/apollo/data/log perception perception </dev/null >/apollo/data/log/perception.out 2>&1 &
```

And the error would be 

``` [1]+  Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/perception/perception --flagfile=modules/perception/conf/perception.conf --log_dir=/apollo/data/log perception perception < /dev/null > /apollo/data/log/perception.out 2>&1```

Thanks!

**Comment by xiaohuitu** [comment]
@kikacaty I recommend you follow the howto document [How to Run Perception Module on Your Local Computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) to run the perception module. Then let's see what will happen.

**Comment by kikacaty** [comment]
@xiaohuitu I tried that before and perception module is not initiated when I run `rosnode list`.

**Comment by kikacaty** [comment]
@xiaohuitu I actually tried that before but failed since we cannot install Nvidia driver without such device.

**Comment by JonathanJones92** [comment]
@kikacaty  The answer is no, Baidu team tend to ignore this issue every time. 
They tend use 'Just follow the guide' as a trick. @xiaohuitu 

This guide says you can't launch the visulizer without a GPU driver even if you build with CPU mode. 
I can percept that if Baidu team continue ignoring those fatal issues, Apollo platform will become a burning house eventually.
As it's obvious that over 10 months there were only 150 issues reported and most of them stay unsolved -- not so many team are insisting on Apollo and not so many team can understand Apollo because of it's lacking proper documentation.

Team apollo, if you decide to put it open source, you should open all the documentation to us instead of hiding from our challenge on the code.

That's it.

**Comment by Capri2014** [comment]
@JonathanJones92 Please behave in a proper manner. There are indeed some documents that might be outdated or need to be improved. We are working on it and as you can see in the thread the team is really trying to help. It just take us sometime to re-produce or debug each individual specific problem. And I believe  contributing back or helping update the documents are more beneficial ways of improving the community and help people with similar questions to resolve the issue faster next time. Like this one https://github.com/ApolloAuto/apollo/commit/3ef3cf4966a6e66b8e8ea269252d20371a78263c
Thanks

**Comment by JonathanJones92** [comment]
@Capri2014  Hi Luo,

I would say I neither curse nor swear in my comments above. If you feel offend. Please accept my sincerely apologize.

I contributed in many ways. As I'm based in the UK, I made many translations from mandarin to English for Apollo and promote Apollo in my community. 

Most of my colleagues feel disappointing for Apollo community as there are a barrier between non-Baidu developers and Baidu Team. Many issues were not closed for a certain answer, it's hard for us to get a solution from the blog! And most of all, it's time-wasting.

Dear Mr Luo, can we just go back to our issues with Apollo platform and kindly check with the issues I reported. If you can give me a clear answer, I would make a commitment to the documentations hopefully.





Regards,
John

**Comment by kikacaty** [comment]
@xiaohuitu Now I have switched to a server with GPU support. I found the tutorial for running perception module locally has several incorrect instructions. First, nvidia requires the version of driver to be consistent (the most updated version is 384). Second, the command  ```./docker/scripts/dev_start.sh NEW_DOCKER_IMAGE_TAG``` seems to be deprecated? 

Now that even I have installed the correct version of driver inside the docker, it prompts that the installation needs a reboot to finish. I don't have a clue of how to do that in docker (I tried restart docker and reboot the host, neither worked). Then I found this [nvidia docker](https://github.com/NVIDIA/nvidia-docker) which might help. I will post follow up if I have any progress on that.

Thanks!

**Comment by lianglia-apollo** [comment]
@kikacaty Please try to install driver version 384.111 for both inside and outside docker. It works on my computer. We will update driver versions soon.

**Comment by kikacaty** [comment]
@lianglia-apollo Good to know it works. Would you mind sharing how did you reboot the docker after the installation of the driver? Did you install it through binary (as in the tutorial) or through apt-get? Thanks!

**Comment by JonathanJones92** [comment]
@lianglia-apollo  I'm also desired to know more details on installing GPU driver inside docker. Also, there is a conflict between the driver and Apollo kernel

**Comment by kikacaty** [comment]
Successfully start the perception module but with failure shown below running with the sensors demo:
```
E0129 21:32:23.468047 26714 transform_input.cc:69] Cannot transform frame: world to frame localization , err: . canTransform returned after 1.0472e-05 timeout was 0.1.. canTransform returned after 0.100667 timeout was 0.1.. 
```
Any idea about the timing out?

**Comment by kikacaty** [comment]
I found it is due to not initiating Localization module.
