### ISSUE TITLE
is EM plannner using the qp Spline Path Optimizer?

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#2510]
1. in the function of EMPlanner::RegisterTasks(), the qp Spline Path Optimizer is not be registered, is that the qp Spline Path Optimizer is unnecessary？

2. since QpSplineStSpeedOptimizer is used, why are PolyStSpeedOptimizer used again?

Thank you for reply.

**Comment by startcode** [comment]
We found that DpPolyPath's result is good enough on road. In addition, the QP-OASES solver may not always return a valid solution, therefore, we skipped the QpSplinePath step. Road driving tests have proved that DpPolyPath is really good.

PolyStSpeedOptimizer is used to make speed decisions for obstacles, and QpSplineStSpeedOptimizer can further optimize the driving speed based on the obstacle decisions

**Comment by ipatient-zju** [comment]
I can not understand how the two tasks work completely. How do the speed decisions made by PolyStSpeedOptimizer exert  influence on the QpSplineStSpeedOptimizer? or the two part is independent?

**Comment by lianglia-apollo** [comment]
The dp_st_speed will use dynamic programming to find the min cost speed profile, which is used to determine whether we will overtake or yield a vehicle (represented as a st-region on the st graph). Then, those decisions will be treated as hard limits (inequality constraints) in qp_st_speed.

**Comment by lianglia-apollo** [comment]
You can ignore poly_st_speed for now, it is still under development. qp_st_speed is the second speed optimizer after using dp_st_speed. You can find the task sequence in modules/planning/conf/planning_config.pb.txt

**Comment by histfuture** [comment]
@lianglia-apollo 
In dp_st_speed  module , I did not found any constraints on current vehicle speed. 
Does that mean dp_st_speed module **only** provide those so-called min-cost speed profile for making obstacle decisions, but such STPoints (in speed profile) of dp_st_speed do not affect the the speed calculation in later qp_st_speed module. 

In summary, dp_st_speed -> only for making obstacle decisions.

AM I RIGHT?
