### ISSUE TITLE
Potentialy bug  ¨How to Run the Fusion Obstacle Visualization Tool¨

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#2527]
Hi,

I was putting effort to run the perception visualizer in my computer, here is my computer configuration:
![Uploading 2018-01-19 10:05:17屏幕截图.png…]()

I followed the instructions from :https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_offline_sequential_obstacle_perception_visualizer.md

In the end, it failed with some errors regarding graphic card as shown below:
![default](https://user-images.githubusercontent.com/16748704/35131357-9fc0ab62-fd00-11e7-8696-0877d623114f.png)

Can somebody tell me how to solve this?

And, from the step "  Run the data exporter using this command:¨
I input the scripts, but it never stop? Is there someone facing the same issue as [me?]

**Comment by JonathanJones92** [comment]
configuration:

![2018-01-19 10 05 17](https://user-images.githubusercontent.com/16748704/35131414-04f25b7a-fd01-11e7-815e-12309ed40f96.png)

**Comment by JonathanJones92** [comment]
the script that never stop is:


    Run the data exporter using this command:

/apollo/bazel-bin/modules/perception/tool/export_sensor_data/export_sensor_data

I put manually interrupt

**Comment by JonathanJones92** [comment]
can someone help me?

**Comment by startcode** [comment]
Hi @JonathanJones92  
Your first problem seems to be a cuda driver problem. But if you follow the readme, you should be able to build a cpu-only version by clean the previous build
```bash apollo.sh clean```, 
and run command
```
bazel build //modules/perception/tool/export_sensor_data:export_sensor_data
```
To build again.

**Comment by JonathanJones92** [comment]
@startcode  thanks let me have a shot :)

**Comment by JonathanJones92** [comment]
@startcode  Hi,

I clean the previous build but I still have one question regarding following steps:

    Run the data exporter using this command:

/apollo/bazel-bin/modules/perception/tool/export_sensor_data/export_sensor_data

    Play the ROS bag.

​ The default directory of the ROS bag is /apollo/data/bag. ​ In the following example, the file name of ROS bag is example.bag.

​ Use these commands:

cd /apollo/data/bag
rosbag play --clock example.bag --rate=0.1


when I run the data exporter, shall I open the rosbag parallely ?
Is there any other config should I make?

**Comment by JonathanJones92** [comment]
Apollo reported 2 warnings in step ´Run the data exporter´, can you have a look?
@startcode 

![2018-01-19 14 56 01](https://user-images.githubusercontent.com/16748704/35138474-b98054d4-fd29-11e7-939d-333bb8edd856.png)

**Comment by xiaohuitu** [comment]
@JonathanJones92 when you run the exporter, you should see something like:
![temp_apollo](https://user-images.githubusercontent.com/16402620/35138596-544042a4-fd2a-11e7-89fb-621b3a10a78d.png)
as you paste above, which indicates waiting for the ros message. 
Following the README, next you should play the rosbag.

**Comment by JonathanJones92** [comment]
@xiaohuitu  shall I ignore the warnings? from this step?  for the rosbag, shall I open a new terminal and get into docker? 

thanks for your help.
![2018-01-19 14 56 01](https://user-images.githubusercontent.com/16748704/35138724-d1c06196-fd2a-11e7-89c5-d5302a901ec8.png)

**Comment by xiaohuitu** [comment]
yes, you could ignore the warning, and open another terminal, then play the rosbag following the README.

**Comment by JonathanJones92** [comment]
@startcode @xiaohuitu  Hi,

Thanks for your timely reply :)

when I trying to get into  the docker dev_enviroment using another terminal, the original one got closed automaticlly. can you offer some advise on that? 
Thanks again

**Comment by xiaohuitu** [comment]
I guess you start another docker container in the other terminal, so the original one closed. You just need to get into it when you have started in one terminal, which means you should get into it directly when you open another terminal, but not start then get into it.

**Comment by JonathanJones92** [comment]
@xiaohuitu  Yes, 
Itś getting work now but another issue came across: 
![2018-01-19 15 49 45](https://user-images.githubusercontent.com/16748704/35140066-d335d942-fd30-11e7-8923-ca403039bac4.png)


can you help me to check ?

Thank you for your help :)

**Comment by JonathanJones92** [comment]
@startcode @xiaohuitu  There are more errors coming in this step as below:
![2018-01-19 16 11 42](https://user-images.githubusercontent.com/16748704/35140797-8c70697a-fd33-11e7-9125-02d80e0a574c.png)

Any ideas my friend :)

**Comment by xiaohuitu** [comment]
@JonathanJones92 Did you create the data path? You should create the data paths for lidar and radar, i.e. lidar_path and radar_path in the configuration file.

**Comment by JonathanJones92** [comment]
@xiaohuitu  it seems working fantastic :) thank you

**Comment by JonathanJones92** [comment]
@startcode @xiaohuitu  I created the radar and lidar folder. The lidar data was successfully dumped but nothing exist in radar folder. 
![2018-01-19 17 05 35](https://user-images.githubusercontent.com/16748704/35142978-fd913812-fd3a-11e7-9372-2c002faf0c9c.png)

Can you help me to analyse?

With the Lidar data, I jumped to the final step, the same error occurs:
![default](https://user-images.githubusercontent.com/16748704/35143042-2fdfb1d6-fd3b-11e7-85a3-6972bfcc088e.png)

 
I build without GPU but why it come across? Iḿ really confused, please help me.

cheers !

**Comment by JonathanJones92** [comment]
@xiaohuitu @xiaohuitu @bigwhite @zhxt @startcode  Hi 
I just want to be humble to all the apollo developers but is there any detailed instructions on how to run the perception visualizer without a GPU/GPU driver? Please help me.
Cheers!

**Comment by JonathanJones92** [comment]
With only the lidar data, I progress to the next step in the fusion mode from [here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_offline_sequential_obstacle_perception_visualizer.md)

I build 
bazel build -c opt //modules/perception/tool/offline_visualizer_tool:offline_sequential_obstacle_perception_test

and run with 
/apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_sequential_obstacle_perception_test  

The results were :
![2018-01-20 21 02 40](https://user-images.githubusercontent.com/16748704/35183695-45428af4-fe25-11e7-8263-a2544c41d413.png)

Still driver issue or maybe lacking the radar data.
Can you help me to check ?

@startcode @xiaohuitu @bigwhite @weidezhang @zhxt 
**# Otherwise I think this is a bug**

Regards,
Jonathan

**Comment by gmhuili** [comment]
I'm facing the same issue. There is no GPU installed on my setup, and I have tried to build with CPU_ONLY and still failed at checking CUDA version.

I0402 13:21:08.735582 22570 layer_factory.hpp:79] Creating layer input
I0402 13:21:08.736299 22570 net.cpp:94] Creating Layer input
I0402 13:21:08.736336 22570 net.cpp:402] input -> data
F0402 13:21:08.736694 22570 syncedmem.hpp:18] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by techoe** [comment]
Please use the same Nvidia driver for your linux and docker.
