### ISSUE TITLE
is there any document that show us the execution logic of apollo? for example, how the perception module get data from camera and gps sensor in the same time while the camera and gps sensor send data in different frequency ?

### ISSUE THREAD

**Issue by lxbeyond** [ApolloAuto/apollo#2534]

**Comment by JonathanJones92** [comment]
@Prasan03  Have you tried offline virtualizer without GPU ? Has it been successful?

**Comment by Prasan03** [comment]
@JonathanJones92 Hey! Ya, I tried and the build was successful but faced the 'CUDA version insufficient' error when I tried to run the visualizer!

**Comment by JonathanJones92** [comment]
@Prasan03  Hi Thanks for your reply :+1: 
I already reported this issue to Apollo Team @zhxt @bigwhite  and I think they are working on it.
The reality is that I'm Mac User, Unfortunately, Mac doesn't have nVidia GPU...

**Comment by Prasan03** [comment]
@JonathanJones92 Thanks for raising the issue. I also have the same issue my laptop does not have a nVidia GPU!

**Comment by zhxt** [comment]
@JonathanJones92
hey，sorry, this may disappointing you but there must  be some misunderstanding that I'm not from Apollo Team, I am just a community developer,  and I only have limited spare time on this project. 

I had tried last night but failed with other issue.
So,no progress on my side:(

**Comment by natashadsouza** [comment]
Currently closing this issue as there has been no communication for a while. Please re-open it should you still be facing the same issue.
