### ISSUE TITLE
驱动模块和感知等模块通信问题

### ISSUE THREAD

**Issue by will1991** [ApolloAuto/apollo#2538]
驱动模块和感知等模块是通过共享内存实现通讯的吗？？？？

**Comment by quning78** [comment]
Yes, they use sharemem transport to communicate.

**Comment by will1991** [comment]
共享内存是默认的模式吗？不需要用nodelet mananger 吗？

**Comment by Peter9606** [comment]
curious about this too

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication for a while. Please feel free to open it if you are still facing the same issue.
