### ISSUE TITLE
Help required ! Where are the exported radar data??? 

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#2541]
Hi Team @zhxt @startcode @xiaohuitu @bigwhite @teknolog2000 @weidezhang @xczhanjun @weidezhang,

I'm strictly following the [guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_offline_sequential_obstacle_perception_visualizer.md) to run the offline perception visualizer on my local computer(with out nVidia GPU). 

The data I download from Baidu platform were include Lidar and radar data according to per user manual:
![2018-01-20 20 25 57](https://user-images.githubusercontent.com/16748704/35183394-43fe4548-fe20-11e7-8797-1ea1ea2d8cfd.png)

I use bag:

demo-sensor-demo-apollo-1.5.bag | 8.93GB |  from [here](http://data.apollo.auto/help?name=data-sensor%20demostration-user%20guide&data_key=sensor&data_type=1&locale=en-us&lang=en)

However, when I was trying to extract data from Ros bag, there were only lidar data appears in corresponding folder.  I created 'lidar' and 'radar' folder correctly as instructed from #2527 .
The radar data still not coming out.
During the process, everything seems working fine:
![2018-01-20 20 30 17](https://user-images.githubusercontent.com/16748704/35183420-c7f12e9c-fe20-11e7-8349-515cfead7ad9.png) 

except this one:
![2018-01-20 20 42 26](https://user-images.githubusercontent.com/16748704/35183493-8100d63e-fe22-11e7-92ea-d4ee333fc550.png)
 
But I reckon that this is nothing related to radar.

# **So, that's my 1st question, where are the radar data?**

I decided to move forward, I can run the perception using only lidar because it's been proved from apollo 1.5.
The generated pose & pcd files were mixed and saved in apollo/data/lidar folder
I copied them separately to apollo/data/pose and pcd folder and tried to get it run with

cd /apollo

bazel build -c opt //modules/perception/tool/offline_visualizer_tool:offline_lidar_visualizer_tool

and 
/apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool

I already checked with the configs and I'm sure it's correct
Sadly, it's still not working  : ( as you see:

![2018-01-20 20 56 27](https://user-images.githubusercontent.com/16748704/35183638-738c88ac-fe24-11e7-9337-24a446f926d7.png)
![2018-01-20 20 56 39](https://user-images.githubusercontent.com/16748704/35183642-79c78794-fe24-11e7-9123-836b01b9ffa2.png)
![2018-01-20 20 56 44](https://user-images.githubusercontent.com/16748704/35183644-7fb8fd2c-fe24-11e7-8b69-432cd1c2307e.png)

I have put lots of efforts on this.. 
# My 2nd question is: can you give me more detailed guidance on how to run this? It will make a difference on my progress on Apollo.

Thanks Team.

Regards,
John

**Comment by JonathanJones92** [comment]
@bigwhite @weidezhang @zhxt @xczhanjun @teknolog2000 @apollo-jingaowang @xczhanjun 
Hi Team,

I'm still confused that ## **Can I use offline virtualizer without a nVidia GPU?**

I have tried many times but still facing this error. According to your demo guide
**Please note that the Nvidia driver should be installed appropriately as shown above even if the perception module is running in Caffe CPU_ONLY mode **

Could the team make some comments on that?

regards,
Jonathan

**Comment by JonathanJones92** [comment]
@Capri2014  Thanks team :+1:

**Comment by JonathanJones92** [comment]
@yellowpoplar @xiaohuitu  Any updates dears?

**Comment by chucklqsun** [comment]
@JonathanJones92 I use  demo-sensor-apollo-2.0.tar.gz/2018-01-03-19-37-16.bag from apollo official site and get both radar and lidar output. You can use "rosbag info xxxx.bag" to check and find that no "radar" related topics in 1.5.bag. I am not familar with ROS bag but maybe that's why no radar output.

**Comment by linux-devil** [comment]
I cannot find /apollo/data/lidar or apollo/data/radar folder , I see the config file and default path looks similar , I am able to run export sensor data and it runs fine with one of the line which I am posting below:
I0606 12:00:01.150476 56326 export_sensor_data.cc:252] localization timestamp:1505249900.008391619

**Comment by natashadsouza** [comment]
Currently closing the issue as it seems to be resolved.
