### ISSUE TITLE
the problem about the data synchronization for sensors like cameras and gps

### ISSUE THREAD

**Issue by lxbeyond** [ApolloAuto/apollo#2543]
because the perception module needs data from sensors like  LiDAR and camera etc, but these sensors may produce data in different frequency, which may lead to a situation that perception algorithm is dealing with camera images which produced in time t1 and gps data which produced in time t2, and t1 may be later than t2, as we know , car runs so fast that image in t1 and images in t2 may be greatly different  . I wonder how the apollo solve this problem ?  what's more, the same problem may happen to prediction module which need data from localiztion module and perception module.

**Comment by Capri2014** [comment]
@lxbeyond Thanks for pointing out, the sensor sync part is not covered in the scope of 2.0, stay tuned and be patient . :)

**Comment by lxbeyond** [comment]
ok, i see, thanks @Capri2014

**Comment by YangHan101** [comment]
@lxbeyond As we increase the testing speed, the synchronization between sensors will be included in Apollo in the future. :)

**Comment by Zhenni17** [comment]
Closing the issue, and feel free to open new issue if there are more questions.
