### ISSUE TITLE
交通信号灯识别模块caffe net的输入与输出层问题

### ISSUE THREAD

**Issue by yongyuandeyezi** [ApolloAuto/apollo#2547]
apollo-2.0.0\modules\perception\traffic_light\rectify\detection.h中
#include "caffe/layers/pyramid_layers.hpp"
安装编译caffe后，在caffe/layers中找不到/pyramid_layers.hpp
请问，pyramid_layers.hpp是否是apollo自己定义的，在哪里能够找到呢

**Comment by lianglia-apollo** [comment]
Are you running the program in docker?

**Comment by yongyuandeyezi** [comment]
我没有在docker中运行
我只是把detect这部分代码单独拿出来，自己新建了一个工程，cmake后make

**Comment by zhxt** [comment]
@yongyuandeyezi 据我所知，caffe这部分现在是不开源的。

**Comment by lianglia-apollo** [comment]
for your info: 
Some libraries are only inside docker. https://github.com/ApolloAuto/apollo/issues/1751

My suggestion is that if you would like to play around without docker environment as a developer, you can build your own network layers.

**Comment by ghdawn** [comment]
caffe in docker is different from origin version and is not open source in Apollo 2.0. If you want to use outside docker please copy caffe's *.h and *.so to your environment. Or wait for Apollo 2.5

**Comment by yongyuandeyezi** [comment]
Thank you very much!

**Comment by cjjsaic** [comment]
seemed still no open source plan for traffic light module in Apollo 2.5 @ghdawn

**Comment by Peter9606** [comment]
Are all neural networks not open sourced ?

**Comment by techoe** [comment]
The caffe code is all open source now.

**Comment by breakisx** [comment]
@techoe where is caffe code that is open source in apollo?

**Comment by xiaoxq** [comment]
Hi @breakisx , the code is in another repo: https://github.com/ApolloAuto/caffe
We build it and put the output into Apollo docker container: https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_gpu_caffe.sh

**Comment by shanliang1992** [comment]
> Hi @breakisx , the code is in another repo: https://github.com/ApolloAuto/caffe
> We build it and put the output into Apollo docker container: https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_gpu_caffe.sh

Hi，the pyramid_layers.hpp couldn‘t be found in the apollo/caffe.

**Comment by hawl666** [comment]
@xiaoxq the caffe code link is not available now.
