### ISSUE TITLE
mac os system build error

### ISSUE THREAD

**Issue by bianheshan** [ApolloAuto/apollo#2548]
i have installed the docker， and execute the dev_start.sh,  while show the error message: bash: /apollo/scripts/docker_adduser.sh: No such file or directory

and if continue execute the dev_into.sh it will show the error message: unable to find user apollo: no matching entries in passwd

**Comment by xiaoxq** [comment]
Sorry that it looks outdated. I have a fix by
https://github.com/ApolloAuto/apollo/pull/2558

**Comment by bianheshan** [comment]
thanks, i have resolved this error, by change the 
-APOLLO_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )" 
to
 +APOLLO_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"

**Comment by askari01** [comment]
bash apollo.sh build 
is now at :
Building: no action running
