### ISSUE TITLE
localhost not accessible , but it says Running on MAC

### ISSUE THREAD

**Issue by askari01** [ApolloAuto/apollo#2551]
$ bash docker/scripts/mac/dev_start.sh 
it tells me that container is running but the IP is still not accessible.

"Your container is running at 192.168.99.100,
while not localhost or 127.0.0.1. Use the IP to access tools such as
Dreamview."

**Comment by askari01** [comment]
running 
bash scripts/bootstrap.sh

it says "Dreamview is running at http://localhost:8888"

**Comment by xiaoxq** [comment]
As we need a Linux-based docker container, so the container actually runs inside a virtual machine in VirtualBox. So the IP address is different from your host machine (saying MacOS).

As a result, when it says "Dreamview is running at http://localhost:8888", the "localhost" means the virtual machine. On your MacOS, you have to visit it with it's real IP.

As we noted in the README (https://github.com/xiaoxq/apollo/blob/master/docker/scripts/mac/README.md ), the Mac version is a hack. It may not function well. We always recommend to work on Ubuntu, and also really welcome contributions that help maintain and improve the Mac version :)

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.
