### ISSUE TITLE
Build apollo error! execute apollo.sh build

### ISSUE THREAD

**Issue by bianheshan** [ApolloAuto/apollo#2565]
this is error info

//modules/common:log
//:x86_64
//:arm64
apollo@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1269 targets (12 packages loaded).
INFO: Found 1269 targets...
**ERROR: /apollo/modules/planning/planner/rtk/BUILD:29:1: C++ compilation of rule '//modules/planning/planner/rtk:rtk_replay_planner_test' failed (Exit 1)**
INFO: Elapsed time: 4244.333s, Critical Path: 64.41s
FAILED: Build did NOT complete successfully
[ERROR] Build failed!

**Comment by Capri2014** [comment]
@bianheshan not sure, which version are you using?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while.
