### ISSUE TITLE
apollo1.0循迹功能的record 代码有开放吗？

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#2566]
您好，
  看到RTK算法是实现replay功能的，即读取data/log/garage.csv文件，判断位置，计算轨迹点，然后设置参考路径。
然后想问下生成data/log/garage.csv文件的代码有开放吗？

**Comment by xiaoxq** [comment]
请见 https://github.com/ApolloAuto/apollo/blob/master/modules/tools/record_play/rtk_recorder.py
