### ISSUE TITLE
Question about controllers in control module

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#2576]
Dear Apollo designers, 

Based on my investigation of the source code for control module in Apollo 2.0, some key control parameters for the lat_controller and lon_controller (consisting of 2 PID controllers, speed_pid_controller and station_pid_controller) will be reset (as indicated by a condition check inside _Control::ProduceControlCommand_, line 171-174 of _control.cc_) when receiving a Chassis message with COMPLETE_MANUAL driving mode. I am wondering if the reset of some controller (e.g., speed_pid_controller), for example, when the driving mode of a moving autonomous vehicle suddenly changes from COMPLETE_AUTO_DRIVE to COMPLETE_MANUAL, can cause any transient effect or disturbance to the movement of the vehicle or the speed control loop (excuse for my unfamiliarity with the control system theory). Is there any safety guideline for changing the driving mode in practice (e.g., better not change when the vehicle is moving)?

Thanks very much for your reply and clarification!

**Comment by natashadsouza** [comment]
Sorry we did not get back to you on this issue. Please let us know if you were able to resolve it at your end.
