### ISSUE TITLE
typo error on prediction module

### ISSUE THREAD

**Issue by zezhou** [ApolloAuto/apollo#2584]
HI
I'm learning apollo project.
I find one typo error on modules/prediction/evaluator/vehicle/rnn_evaluator.cc
I think the "break" at "line 228" should be puted after line  224. 

https://github.com/ApolloAuto/apollo/blob/a7786714eda6d4ac5593bfa43a0e6fdf61557f67/modules/prediction/evaluator/vehicle/rnn_evaluator.cc#L228

https://github.com/ApolloAuto/apollo/blob/a7786714eda6d4ac5593bfa43a0e6fdf61557f67/modules/prediction/evaluator/vehicle/rnn_evaluator.cc#L224

**Comment by lianglia-apollo** [comment]
I think you are correct. Will you be interested in submitting a pull request?

**Comment by jinghaomiao** [comment]
@zezhou good catch! Actually the logic is correct as only ONE previous frame of history from the most current frame is needed for setting up features for RNN model. Please pay attention to line 184 that "num" is set to to be <= 3. So the goal is not to iterate the entire history, but seek the previous one from the most recent observation. Of course the code can be more straightforward. If you are interested, please feel free to make your modification and we'd be happy to see if you can contribute to our code repo. Thanks!
