### ISSUE TITLE
questions about the roadmap of nvidia/CUDA/GPU etc.

### ISSUE THREAD

**Issue by jianglinchun** [ApolloAuto/apollo#2585]
I had found that your guys had add CUDA build file recently.
And Baidu had announce corperation in Apollo project late 2017. Here comes the questions:

1. Any roadmap/timetable about CUDA support? next release?
2.which module will you trying to improved by CUDA????
3. When will Baidu/nvidia give a newer apollo reference hardware(former apollo reference hardware kit is too expensive..

**Comment by lianglia-apollo** [comment]
Currently, the perception module can run with GPU by "bash apollo.sh build_opt_gpu".
We are actively working on cuda (8.0) support. Some initial files to support cuda compilation were merged several days ago. More changes are necessary to compile cuda code, for example, installation of clang.

We can use cuda for all modules as long as it provides computational benefits. You are very welcome to contribute.

**Comment by jianglinchun** [comment]
@lianglia-apollo thank you so much for your sharing.
I'm trying to follow up and make some contribute.
