### ISSUE TITLE
A forum for Apollo users?

### ISSUE THREAD

**Issue by wandadars** [ApolloAuto/apollo#2586]
Is there a public website for users of Apollo to discuss their work with using the platform? If not, I think it would be a helpful for getting the Apollo community together. Even something like a Google Group would be helpful. I have so many questions, but currently I see no vector available to direct these questions to.

For example, the open source chemical kinetics software "Cantera" has a fantastic and lively Google Group where expert users and Cantera developers can interact directly with the community. The community can also work together by helping each other understand and learn Cantera.

https://groups.google.com/forum/#!forum/cantera-users

**Comment by lianglia-apollo** [comment]
You are welcome to post your questions here.

**Comment by wandadars** [comment]
@lianglia-apollo Is the issues tab of the Github page appropriate for user-to-user interaction about Apollo?  Is there any particular reason for keeping all discussion within the Issues tab? I believe a Google Group is completely free, and most people have a Google account, so registration is painless. A location for community discourse is a common feature of open-source communities. I'm a fan of the Apollo project, and I just want to see it succeed.

**Comment by natashadsouza** [comment]
@wandadars we have one created #7464

**Comment by natashadsouza** [comment]
Closing this issue. Feel free to reopen if you have additional questions. Thanks!
