### ISSUE TITLE
Ubuntu login loop problem after installing pre-built Apollo Kernel.

### ISSUE THREAD

**Issue by turinglife** [ApolloAuto/apollo#2595]
https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md

When I use this link to install software system on Nuvo-6108GC with GPU GTX1080, i got a problem.

After installing the pre-built Apollo Kernel and rebooting the system, I can not login Ubuntu system any more. 

It always be the status of login loop. At this moment, I checked my GPU using 'nvidia-smi', and it told me that 'Failed to initialize NVML: Driver/library version mismatch'. so i removed and purged all the 'nvidia*' in the Ubuntu, and used the 'sudo bash ./NVIDIA-Linux-x86_64-375.39.run --no-x-check -a -s' which mentioned by the link to reinstall nvidia driver. Yes, it prompted that it was successfully installed in the system, but when i type 'nvidia-smi' command again, it still told me that 'Failed to initialize NVML: Driver/library version mismatch' and still can not login successfully.

Is there anyone encounters this problem? Would you please share some ideas to fix this problem.

Thanks.

**Comment by lianglia-apollo** [comment]
We had the login issue when "stop lightdm" before installation of nVidia drivers. Currently we don't have a solution on this issue because it might be related to a bug on the driver. 

What I did is to use ubuntu 16.04, install 384.111 driver (it will be automatically installed when you install cuda 8.0) both inside and outside docker.

You can try to run the deviceQuery program provided by /usr/local/lib/cuda-8.0/samples/... It the result is success, the driver should be working correctly.

**Comment by turinglife** [comment]
I think when installing nvidia driver, performing the command ‘sudo service lightdm stop’ is a necessary procedure.

Thanks your recommendation about using ubuntu 16.04 instead of 14.04 to bypass the problem. I was just wondering that Ubuntu 14.04.3 is the recommended one, why other people did not encounter this problem when installing 'pre-built Apollo Kernel'.

Thanks.

**Comment by turinglife** [comment]
Finally, I fixed this problem using the following solution.

1. reboot system; enter grub menu; choose a generic images, and do not choose apollo image.
2. in this case, ctrl+alt+f1, and then install nvidia driver 'NVIDIA-Linux-x86_64-375.39.run'. after that, you can use 'nvidia-smi' to display the usage of GPU.
3. reboot again, and then you can login.

**Comment by turinglife** [comment]
it also can refer to this link which is another method to solve this problem.
https://github.com/ApolloAuto/apollo/issues/1872
