### ISSUE TITLE
Does anyone know how to get the Hadmap.xml?

### ISSUE THREAD

**Issue by csuDavid** [ApolloAuto/apollo#2596]
the data of Hadmap is stored in the file named Hadmap.xml,but i do not know the meaning of the data in it and how to get those data.If you know about it,help me please! And I'll appreciate it if you leave your contact information.

**Comment by startcode** [comment]
A sample map is packed in development docker, not in the git repository.
You can find it by start dev docker and cd to directory `/apollo/modules/map/data/`

For more details, refer to: 
https://github.com/ApolloAuto/apollo/tree/master/modules/map/data

**Comment by msbeta** [comment]
We can provide the HDMap specification to you, which describe the meaning of data in hdmap.xml, you can leave your email here, and we will email to you as soon as possible. 
You can get more infomation from here: https://github.com/ApolloAuto/apollo/issues/3005, Please feel free to let me know if you have other problems, thanks!

**Comment by natashadsouza** [comment]
Closing this issue as there has been no responses in a while.

**Comment by ArtistZhou** [comment]
> the data of Hadmap is stored in the file named Hadmap.xml,but i do not know the meaning of the data in it and how to get those data.If you know about it,help me please! And I'll appreciate it if you leave your contact information.

can you mail me the hadmap.xml? I have the spec of it ? 282339273@qq.com

**Comment by JackRen88** [comment]
Hello, everyone.
Could you please email me the Apollo OpenDrive specification please ?
My email is 2541123296@qq.com
I really appreciate it.

**Comment by Mingkun-wxc** [comment]
Hello, everyone.
Could you please email me the Apollo OpenDrive specification please ?
My email is 1457569105@qq.com
I really appreciate it.

**Comment by AM055** [comment]
Hello, everyone.
Could you please email me the Apollo OpenDrive specification please ? I really appreciate it.
