### ISSUE TITLE
Demo载入问题

### ISSUE THREAD

**Issue by CedarYang** [ApolloAuto/apollo#2614]
运行rosbag play -l ./docs/demo_guide/demo_2.0.bag
提示bash: rosbag: command not found
是因为我ros没启动吗？
但是我访问localhost：8888没有问题

**Comment by lianglia-apollo** [comment]
Have you compiled the code inside docker?

**Comment by CedarYang** [comment]
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh进入docker
./apollo.sh build_no_perception dbg 编译的 提示成功了

**Comment by lianglia-apollo** [comment]
Please try "bash apollo.sh build" and then play the demo bag.

**Comment by CedarYang** [comment]
我 bash apollo.sh build 成功,运行rosbag play -l ./docs/demo_guide/demo_2.0.bag
还是提示bash: rosbag: command not found 
已经是root@in_dev_docker：下了

**Comment by CedarYang** [comment]
我是在ubunutu14.04上搭建的 16.04build不成功

**Comment by startcode** [comment]
command `rosbag` should be in `/home/tmp/ros/bin/` inside docker. First, confirm `/home/tmp/ros/bin/rosbag` does exist.

If it does exist, `source scripts/apollo_base.sh` should be able to add the path `/home/tmp/ros/bin` to your $PATH variable.

If it does not exist, your docker image seems broken or polluted.
