### ISSUE TITLE
when using qpOASES to solve the qp problem, what's the difference between hotstart and init?

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#2621]
I have learned that the qp problem is solved by the qpOASES, but what is difference between function hotstart() or init() to solve the problem.  When hotstart() have no SUCCESSFUL_RETURN, why we use init() to solve it again?
Thanks for reply.

**Comment by jmtao** [comment]
Hope @startcode has answered your question. 
If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open an new issue if you have any more questions. 
Thank you for supporting Apollo!
