### ISSUE TITLE
Where is the differential GPS base station?

### ISSUE THREAD

**Issue by Wsine** [ApolloAuto/apollo#2622]
it makes me confused that, apollo gnss receiver does not connect to a rtk gps base station. how about the errors without a base station? 

below it is a documentation about how to connect propak6, imu and ipc, while com1 or com2 doesnt connect to any device(like base station)

![](https://raw.githubusercontent.com/ApolloAuto/apollo/master/docs/quickstart/images/wiring.png)

questions2: are there necessary with 4G router to connect to ipc?
ipc runs a hmi backend and ipad requests the frontend pages. it seems that a network switch is enough.
am I wrong?

**Comment by bbidault2** [comment]
Hello @Wsine,
You need to contact a local rtk network provider. They will provide you with an IP address, a port, a mount point a username and a password so that you can connect to their network by modifying the gnss configuration file (`apollo/modules/drivers/gnss/conf/gnss_conf_mkz.txt`).
I cannot answer you second question.

**Comment by YangHan101** [comment]
Hello @Wsine,
As @bbidault2 pointed out. You would need at least one RTK base station. You can build one yourself or use publicly available stations, or subscribe to paid RTK services. 
As to your 2nd question, we need internet to update the software when we launch Apollo. Also, we need internet to communicate with our base station for RTK correction. You can also set up the base station with radio transceivers if you don't need extensive range for testing.

**Comment by Zhenni17** [comment]
Closing the issue. Feel free to open new issues if you have more questions.
