### ISSUE TITLE
Do Apollo have method or tools that can transfer .nds, .mid, .mif format HDMAP into the format of Apollo hdmap is using?

### ISSUE THREAD

**Issue by hzdsdhr** [ApolloAuto/apollo#2623]
I got HDMAP in standard hdmap format like .mif+.mid or .nds, does Apollo have a method or tools that can transfer this kind of standard hdmap format map into the map that Apollo is using?

**Comment by msbeta** [comment]
sorry，apollo has no tools and method to transfer mid/mif or nds to apollo hdmap format now.

**Comment by hzdsdhr** [comment]
Thank you for your answer.
