### ISSUE TITLE
Record and Play tool

### ISSUE THREAD

**Issue by bbidault2** [ApolloAuto/apollo#2634]
Hello, 

I have been able to record a waypoint file (`garage.csv`) using the `rtk_recorder` tool.
Now, when using the `rtk_player` tool, I see that the script publishes messages of type `apollo::planning::ADCTrajectory` through the topic `/apollo/planning`. These messages include informations like speed, acceleration, curvature and curvature change rate, while my vehicle would expect commands like throttle and brake percentage and steering torque.

My questions are, 

1. Is the data published by `rtk_player` the **desired** state (desired position, speed, acceleration, curvature, curvature change rate, etc.) ? Does the curvature (kappa) stands for the curvature radius ? What would be the units ? 

2. Am I supposed to design and implement a set of controllers to apply the desired commands or does Apollo include such controllers ? Is there a control layer that should come on top of the planning layer that I am missing ?

Please feel free to ask for details if my question is not clear enough. Thank you.

**Comment by ahuer2435** [comment]
apollo 里面的控制模块，可以将/apollo/planning话题转为控制指令，也就是包含steer，brake和throttle话题数据。

**Comment by bbidault2** [comment]
Thank you @ahuer2435, after rebooting the control module (`./script/control.sh stop` & `./script/control.sh`) I was able to see the full dataset. Although the control command for the steering is a steering angle target so I had to design and implement a controller to get a torque output.
