### ISSUE TITLE
Questions about LiDar & Quanergy Systems like liDar solutions ...

### ISSUE THREAD

**Issue by jianglinchun** [ApolloAuto/apollo#2643]
I had found that Quanergy Systems will gona to offer a much cheaper LiDar solutions for ADAS.
And here is the questions:
1. How many types/model of liDar you had tested? Will you please give us some examples??
2. Which one is the most likely to be a replacement to Velodyne???
3. Do you have any suggestion about the hardware offer a slow auto driving system? such as less than 30km/h??

**Comment by Capri2014** [comment]
This is out of the scope of Apollo 2.0 yet, stay tuned. :)

**Comment by jianglinchun** [comment]
@Capri2014 Thank you so much. And looking forward to next release. :)
