### ISSUE TITLE
定位模块使用的是什么算法

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#2652]
请问下，定位模块使用的是什么算法？ekf？

**Comment by lianglia-apollo** [comment]
You can find the algorithm details in "Robust and Precise Vehicle Localization based on Multi-sensor Fusion in Diverse City Scenes" (https://arxiv.org/abs/1711.05805).

**Comment by ahuer2435** [comment]
论文中似乎是采用imu+gps+激光雷达+高精地图，然后使用卡尔曼滤波进行数据融合，然后给出位置信息。
不过看localization模块时，感觉只是用了imu+gps数据；虽然apollo1.5加入的高精地图和激光雷达，不过似乎其作用主要是感知、路由和规划，并没有参与定位，不知道理解的是否有误。

**Comment by zhouyao4321** [comment]
在apollo2.0中我们有两种定位模式：RTK和MSF。你所说的imu+gps应该是RTK模式，在MSF模式中我们提供了论文中的定位能力。MSF定位模式的反射值地图部分目前已开源，在/modules/localization/msf目录下。定位算法部分目前是以动态链接库的形式提供，在docker环境中该动态库在/usr/local/apollo/local_integ目录下.

**Comment by ahuer2435** [comment]
@zhouyao4321 谢谢，我看的是1.5的版本，2.0确实还没有看。想问下RTK模式下，定位算法部分是否有文档介绍。

**Comment by zhouyao4321** [comment]
RTK模式实际是对GPS/INS设备(例如NovAtel)的定位结果进行转发，具体实现的代码还是比较清晰明了的。

**Comment by roaddy** [comment]
请问定位算法部分什么时候可以源码开放呢？ @zhouyao4321

**Comment by natashadsouza** [comment]
Closing this issue as there has been no further communication.

**Comment by daohu527** [comment]
> 请问定位算法部分什么时候可以源码开放呢？ @zhouyao4321

don't follow
