### ISSUE TITLE
apollo 1.5 build error on arm64

### ISSUE THREAD

**Issue by GitBubble** [ApolloAuto/apollo#2654]
hi , guys .

it seems not so comptible under arm64 platform compared with x86_64 when building apollo in docker, a error will indicated that  lack of  thirdpart/protobuf build file. 

as far as i know, the protobuf is already loaed into bazel workspace.  

apollo 1.5 was built under Ubuntu 16.04, constantly report following error.

> ERROR: /apollo/modules/prediction/proto/BUILD:66:1: every rule of type proto_library implicitly depends upon the target '//third_party/protobuf:protoc', but this target could not be found because of: no such package 'third_party/protobuf': BUILD file not found on package path.
> ERROR: Analysis of target '//modules/prediction/container/obstacles:obstacle' failed; build aborted.

anyone solved this kind of problem?

**Comment by GitBubble** [comment]
root@in_dev_docker:/apollo# bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
____Loading package:
____Loading package: modules/common/configs
____Loading package: @google_styleguide//
____Loading package: @curlpp//
____Loading package: @glog//
____Loading package: @gtest//
____Loading package: @ros//
____Loading package: @eigen//
____Loading package: @civetweb//
____Loading package: @glew//
____Loading package: @glfw//
____Loading package: @opencv2//
____Loading package: @opengl//
____Loading package: @proj4//
____Loading package: @tinyxml2//
____Loading package: @qp_oases//
Building on aarch64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/routing/proto/BUILD:10:1: every rule of type proto_library implicitly depends upon the target '//third_party/protobuf:protoc', but this target could not be found because of: no such package 'third_party/protobuf': BUILD file not found on package path.
ERROR: Analysis of target '//modules/routing/proto:routing_proto_lib' failed; build aborted.
INFO: Elapsed time: 15.277s
============================
[ERROR] Build failed!
[INFO] Took 18 seconds

**Comment by tevenfeng** [comment]
Same problem too. Seems that they didn't provide the build for bazel to build protbuf package. I'm still trying to figure it out.

**Comment by siyangy** [comment]
As I mentioned in https://github.com/ApolloAuto/apollo/issues/2661, the 1.5 release doesn't support ARM64 yet, you need to checkout to https://github.com/ApolloAuto/apollo/commit/f04901f9d33970e15a6da52d881e25d5974ecc37 onwards and run ./apollo.sh build_no_perception to compile.

**Comment by HouYuu** [comment]
Have you fixed this problem? @GitBubble

**Comment by natashadsouza** [comment]
Closing this issue as there is no response.

**Comment by natashadsouza** [comment]
Closing this issue as there has no communication.
