### ISSUE TITLE
bazel: Permission denied when executing 'bash apollo.sh clean' in docker

### ISSUE THREAD

**Issue by tevenfeng** [ApolloAuto/apollo#2661]
I'm trying to build Apollo 1.5 on the nvidia Jetson TX1(Ubuntu 16.04, arm64, kernel patched so docker can be supported), so I downloaded Apollo1.5 source code and followed the instructions in README.md. There was no problem when I executed 'dev_start.sh' and 'dev_into.sh'. But I failed to build the Apollo because it told me the following error when I executed 'bash apollo.sh clean':

    apollo.sh: 346: bazel clean: Permission Denied
    
So I'm just wondering anyone could help me with it. Thanks a lot!

**Comment by siyangy** [comment]
You can try to remove the bazel cache directory outside of the docker container. Normally it resides in ~/.cache/bazel/

**Comment by tevenfeng** [comment]
Thanks for your help! I did remove that bazel directory but it seems that there's nothing to do with the bazel outside of the container, it keeps telling me that it is the bazel inside the container that caused this: /usr/local/bin/bazel: Permission denied.

**Comment by siyangy** [comment]
do you mean you don't have permission to run /usr/local/bin/bazel? if so just do a chmod +x.

**Comment by tevenfeng** [comment]
Nope, I do a 'bash apollo.sh clean', and it tells me 'apollo.sh: 346: /usr/local/bin/bazel: Permission denied', and actually I can't do a chmod +x to /usr/local/bin/bazel because it told me that operation is not permitted(I think this is because that I dont have root access to /usr/local/bin/bazel in the container).

**Comment by siyangy** [comment]
hmm that's weird, are you just using the 1.5 release branch to test this? Just to confirm if you do a `ls -l /usr/local/bin/bazel`, do you see you have execute permission or not? Also a `sudo chmod +x to /usr/local/bin/bazel` should work.

**Comment by tevenfeng** [comment]
Yes, permission string is 'lrwxrwxrwx' so I think I do have execute permission. But it simply can not be executed though. And about sudo chmod +x told me that sudo: command not found.

**Comment by tevenfeng** [comment]
And I'm using tar package under the realease page, maybe I  should just clone branch 1.5 directly from the repository?

**Comment by tevenfeng** [comment]
Well, I clone directly from the repository and it keep telling me the same error...so I dont know what to do know...

**Comment by tevenfeng** [comment]
Well, I've tried to add a new line to the dev.aarch64.dockerfile so I can run sudo in the container, however, that dockerfile defines that it installs all dependencies from ubuntu 16.04, but actually ros-indigo does not support ubuntu 16.04 and the building of image failed, so I changed the dockerfile to 14.04 and re-built the docker image, but it told me that  package shellcheck can not be located(this may mean that this package is removed from repo of ubuntu 14.04). So I'm just wondering how the developer team of Apollo solve this.

**Comment by GitBubble** [comment]
@tevenfeng 

I was also building apollo 1.5 under aarch64 paltform. the apollo.sh could run after chmod 777 to bazel binary. but , the whole build scheme under arm64 is not fully supported yet by apollo team . this is not open source but half-opened source project. not a good choice for this company

**Comment by siyangy** [comment]
@tevenfeng I just double checked, you need to do a chmod +x /usr/local/bin/bazel-aarch64 to make bazel executable. Also, note that we don't officially support ARM for 1.5 release. You can checkout to a commit after https://github.com/ApolloAuto/apollo/commit/f04901f9d33970e15a6da52d881e25d5974ecc37 and run `./apollo.sh build_no_perception` to compile though.

**Comment by tevenfeng** [comment]
Yep， I do rebuild of docker image based on the dockerfile provided but add sudo package into the image and then I can solve this problem. So thanks for your help. I will have a try on what've you provided. This issue can be closed now.
