### ISSUE TITLE
what is dev-x86_64-20170707_1129?

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#268]
when i ran 
bash docker/scripts/dev_start.sh 
then the program started to download as followed 
dev-x86_64-20170707_1129: Pulling from apolloauto/apollo
It was too large and speed was too slow. what is it? 
Can I download from another way?

**Comment by ycool** [comment]
It is the dev docker image. Unfortunately, there is no another way to download.

**Comment by mickeyouyou** [comment]
you can try some accelerate method. example if you are in China, you can try:
```
docker pull registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20170707_1129
```

dev-x86_64-20170926_1848 is the latest version .

and then execute script dev_start.sh

at last, this script  has supported option to pull docker image from China mirror. you can pull the lastest codes to try.

**Comment by xiaoxq** [comment]
Now we support "bash docker/scripts/dev_start.sh -C" which uses china mirror of docker registry.
