### ISSUE TITLE
障碍检测中数据融合的卡尔曼滤波的算法变形的依据是什么？

### ISSUE THREAD

**Issue by yuan-ji** [ApolloAuto/apollo#2682]
数据融合上，我有两个问题
1. perception 模块 障碍检测中的融合部分用到了卡尔曼滤波，但这里对卡尔曼滤波的公式作了变形。在更新噪声协方差时
标准卡尔曼： P=（I-K * H） * P_
Apollo：P=(I-K * H) * P_ * (I- K * H).transpose + K * R * K.transpose
其余四个公式未做任何变化，请问能给出变形的依据或者论文么？
2. 该融合用得是标准卡尔曼。对 lidar 和 radar 的数据处理貌似使用了相同的观察矩阵 H。那 radar 模块中应该对数据进行了从非线性到线性的变换。 这样提前处理优势显而易见，方便了滤波器的程序的编写。
 我的问题是，这样对滤波器的最终效果会带来怎样的影响呢？
谢谢。

**Comment by huiyujiang** [comment]
q1: please refer to Wikipedia: https://en.wikipedia.org/wiki/Kalman_filter. If K is the optimal kalman gain, this can be simplified.
q2: the conti radar we use have provide original location(x, y) and relative velocity information(x, y), you may find some details in radar module, or see the conti radar document.  For the sake of expansibility, we get same state from sensor detector and use same H. 

If you have more questions, don't be shy.

**Comment by yuan-ji** [comment]
感谢回复。针对第一个问题，我看了下wiki上时这么说的，

>  If arithmetic precision is unusually low causing problems with numerical stability, or if a non-optimal Kalman gain is deliberately used, this simplification cannot be applied;

按wiki 上说，简化版的P求法会比较省算力，一般在两种情况下会使用非简化版的。
1. 算法精度特别低会造成数值稳定性方面的问题
2. 使用得是非最优K

Apollo 求解K使用的是标准的最优求解的方式。那么你们使用非简化版的P的求法，是出于第一个原因么？还是觉得计算稍复杂一些也无关紧要？还是有其他的原因呢？

**Comment by huiyujiang** [comment]
You are right, the first reason is that we think about. Actually, the standard kalman filter is not a time-consuming sub-module in our system. By the way, if you understand the states from sensor detectors very well, you can try to use the  simplified one.

Hope my answer will help you!

**Comment by yuan-ji** [comment]
Thanks for your answer， it helps a lot!
