### ISSUE TITLE
A question regarding bazel build system

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#2688]
I am modifying the configuration file _CROSSTOOL_ in the bazel tool chain for the Apollo project (i.e., _.cache/bazel/_bazel_david/install/5b1e8be5d1d6766f635a7db5967707e9/_embedded_binaries/embedded_tools/tools/cpp/CROSSTOOL_). But I am encountering the follow errors when I tried to build after the modification. Anyone knows what is the proper way to reconfigure the bazel tool chain for Apollo project? Thanks!

```
$ bazel build --crosstool_top=//tools/cpp:toolchain --cpu=llvm modules/monitor:all
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Error: corrupt installation: file '/home/david/.cache/bazel/_bazel_david/install/5b1e8be5d1d6766f635a7db5967707e9/_embedded_binaries/embedded_tools/tools/cpp/CROSSTOOL' modified.  Please remove '/home/david/.cache/bazel/_bazel_david/install/5b1e8be5d1d6766f635a7db5967707e9' and try again.
```

**Comment by natashadsouza** [comment]
Sorry we could not get back to you on this request. Please let me know if you still need support on your request. Feel free to re-open the issue.

**Comment by jaloo2018** [comment]
> I am modifying the configuration file _CROSSTOOL_ in the bazel tool chain for the Apollo project (i.e., _.cache/bazel/_bazel_david/install/5b1e8be5d1d6766f635a7db5967707e9/_embedded_binaries/embedded_tools/tools/cpp/CROSSTOOL_). But I am encountering the follow errors when I tried to build after the modification. Anyone knows what is the proper way to reconfigure the bazel tool chain for Apollo project? Thanks!
> 
> ```
> $ bazel build --crosstool_top=//tools/cpp:toolchain --cpu=llvm modules/monitor:all
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
> Error: corrupt installation: file '/home/david/.cache/bazel/_bazel_david/install/5b1e8be5d1d6766f635a7db5967707e9/_embedded_binaries/embedded_tools/tools/cpp/CROSSTOOL' modified.  Please remove '/home/david/.cache/bazel/_bazel_david/install/5b1e8be5d1d6766f635a7db5967707e9' and try again.
> ```

then how to solve the CROSSTOOL configuration problem?
