### ISSUE TITLE
Duplicates of gnss_status.proto

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#2700]
```
jilzhou@MacBook-Pro apollo (r2.0.0) $ find . | grep gnss_status.proto
./modules/common/proto/gnss_status.proto
./modules/drivers/gnss/proto/gnss_status.proto
```

They are exactly the same.

```
jilzhou@MacBook-Pro apollo (r2.0.0) $ diff ./modules/common/proto/gnss_status.proto ./modules/drivers/gnss/proto/gnss_status.proto
jilzhou@MacBook-Pro apollo (r2.0.0) $
```

From apollo.sh, we can see that _./modules/drivers/gnss/proto/gnss_status.proto_ is used when build gnss ros node. It is still better to keep just one copy.

**Comment by lianglia-apollo** [comment]
The file under drivers/gnss has a "package apollo.common.gnss_status", and it looks like that file is not being compiled. I guess someone put it there for reference but forgot to delete it when making the pull request...

I made a pull request to delete it (https://github.com/ApolloAuto/apollo/pull/2735).

**Comment by jilinzhou** [comment]
sound good!

**Comment by lianglia-apollo** [comment]
Here is a better solution: https://github.com/ApolloAuto/apollo/pull/2736
