### ISSUE TITLE
static_assert failure in modules/common/time/time.h

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#2702]
I am trying to port apollo onto QNX SDP7. The static_assert call in _modules/common/time/time.h_ fails during compiling stage

```
...
using Duration = std::chrono::nanoseconds;
...
static_assert(std::is_same<int64_t, Duration::rep>::value,
              "The underlying type of the microseconds should be int64.");
...
```
with the following error:
```
...
error: static assertion failed: The underlying type of the microseconds should be int64.
static_assert(std::is_same<int64_t, Duration::rep>::value,
...
```

The only requirement of std::chrono::nanoseconds is that it is an integral type of at least 64bits (http://en.cppreference.com/w/cpp/chrono/duration) . In our qnx implementation, it is actually type "long long int", which is a distinct type from int64_t (although they are both 64-bit ints).

To make it more portable, how about modify this assertion to something like this:

`(sizeof(std::chrono::nanoseconds) >= sizeof(int64_t)`

If it is OK, I can create a PR for that.

**Comment by lianglia-apollo** [comment]
Good catch! Please make a pull request. It looks good to me.
