### ISSUE TITLE
controller developement

### ISSUE THREAD

**Issue by Real-Ying** [ApolloAuto/apollo#2706]
Hola Apollo experts:
       I have a question about how to develop controller : 
       I want to using Apollo's trajectory、 vehicle status and HMI as input, then i want to  process these   parameter using myself designed controller.But I do not know in what software environment to develop and simulate. I had tried to use simulink + carsim,but inside is a drag-and-drop algorithm block，It does not look like a well control algorithm development environment. So,I hope teams provide some selection and advice of developing controller to me.
                                                                                                                                         Thank you!

**Comment by Capri2014** [comment]
Hi Real, the development environment is totally different from the simluink+carsim development ( I assume in window development environment as well). 

If you want to develop control algorithm in C++ environment, either connect your controller to https://www.carsim.com/products/supporting/vehiclesim/vs_api.php (might need some effort), or re-implement vehicle dynamics in C++ format, like  MS, Udacity, gazebo and torcs do

**Comment by Real-Ying** [comment]
Thank you for your answer Capri2014 @Capri2014 
 If I use C++ and Python to develop algorithms and vehicle models，What software do I need separately to develop control algorithms, vehicle models and  simulata my models＋algorithm,thanks!

**Comment by lianglia-apollo** [comment]
A possible way is to (1) develop control algorithms on some software with vehicle dynamic models; (2) migrate the algorithm manually onto Apollo.
Currently, we do not have a control developing software platform with dynamic models.

**Comment by Peter9606** [comment]
I think it's a common question from the guy who come from car maker, like myself. I rather like to know how flexibility the Apollo could provide, such as which modules are replacable by third part's.

**Comment by natashadsouza** [comment]
@Peter9606 is there a particular module you'd like to learn more about?
Unfortunately, not all modules are completely replaceable, but we can discuss this further if you have a more specific design idea.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while.
@Peter9606 that's a great question, because of the modular approach taken by Apollo, you could easily replace any or all of the modules if you'd like as long as you maintain the module connectors, input and output.
