### ISSUE TITLE
bash docker/scripts/dev_start.sh

### ISSUE THREAD

**Issue by GerberaTetra1991** [ApolloAuto/apollo#271]
bash docker/scripts/dev_start.sh
.................................
...................................
Adding new user `amax' (1000) with group `gerbera' ...
The home directory `/home/gerbera' already exists.  Not copying from `/etc/skel'.

End here    
Not error 
It is right？

help me ，thanks ！

**Comment by wanglei828** [comment]
Yes, it is correct. docker container has successfully  launched.

**Comment by GerberaTetra1991** [comment]
Thanks for your help！ @wanglei828
