### ISSUE TITLE
Control : Any paper to refer about MPC?

### ISSUE THREAD

**Issue by Hoonyyhoon** [ApolloAuto/apollo#2710]
Hello Apollo team,

I saw MPC is introduced in the controller in Apollo system, which is very wonderful. About MPC, Is there any paper or material to refer when understanding the controller, solver code? 
Thank you.

**Comment by Capri2014** [comment]
@Hoonyyhoon Not yet, both controller and solver are developed in house ( and of course still a lot of room to be improved!), I know I still owe the community a detailed document/paper...

**Comment by natashadsouza** [comment]
Currently closing this issue as there has been no communication in a while. @Hoonyyhoon if you have additional requests in documentation, please reach out to us and re-open this issue!
