### ISSUE TITLE
TF Frame Init

### ISSUE THREAD

**Issue by kikacaty** [ApolloAuto/apollo#2725]
Where are the tf frames (such as localization, novatel and velodyne64) initiated? I encountered this error when running perception module some times
```
E0202 14:29:44.976615  6543 transform_input.cc:55] Exception: "velodyne64" passed to lookupTransform argument source_frame does not exist. 
```
Therefore, I would like to know the logic of how they are initiated and make sure they are initiated before the testing procedures. Thanks!

**Comment by lianglia-apollo** [comment]
Some example code:

110   ros::Time query_stamp(query_time);
111   const auto& tf2_buffer = AdapterManager::Tf2Buffer();
112   const double kTf2BuffSize = 10 / 1000.0;  // buff size
113   std::string err_msg;
114   if (!tf2_buffer.canTransform(to_frame, from_frame, query_stamp,
115                                ros::Duration(kTf2BuffSize), &err_msg)) {
116     AERROR << "Cannot transform frame from " << from_frame << " to frame "
117            << to_frame << " , err: " << err_msg
118            << ". Frames: " << tf2_buffer.allFramesAsString();
119     return false;
120   }

**Comment by kikacaty** [comment]
@lianglia-apollo I found that piece of code where the exceptions were thrown. I was wondering where those frames were initiated so that I could avoid such "* frame not exists" error. Thanks!

**Comment by lianglia-apollo** [comment]
I didn't do other initializations beyond these. Are you playing a rosbag with both velodyne and localization outputs?

**Comment by kikacaty** [comment]
Yes, I was planning to remove the publishing logic in localization module. Is that the reason of the failures?

**Comment by lianglia-apollo** [comment]
I guess we need the ROS transform messages. 

Here is some code in adapter:

static tf2_ros::Buffer &Tf2Buffer() {
200     static tf2_ros::Buffer tf2_buffer;
201     static TransformListener tf2Listener(&tf2_buffer,
202                                          instance()->node_handle_.get());
203     return tf2_buffer;
204   }

**Comment by kikacaty** [comment]
It seems to be due to low speed of initiation, though I still have not found the code initiate those tf frames.
