### ISSUE TITLE
relative_time check in DiscretizedTrajectory::Evaluate(const double relative_time)

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#2738]
Here is code snippet for the function:

```
TrajectoryPoint DiscretizedTrajectory::Evaluate(
    const double relative_time) const {
  CHECK(!trajectory_points_.empty());
  CHECK(trajectory_points_.front().relative_time() <= relative_time &&
        trajectory_points_.back().relative_time() <= relative_time)
      << "Invalid relative time input!";

...
}
```
Considering  trajectory_points_.front().relative_time() **<=**  trajectory_points_.back().relative_time(), is the first part of compare **trajectory_points_.front().relative_time() <= relative_time** needed? I can be wrong about this: should the input relative_time in between front().relative_time and back().relative_time to be valid?

BTW, what is minimum number of trajectory points to form a valid trajectory? Is a single point trajectory meaningful ( **CHECK(!trajectory_points_.empty());**)?

**Comment by startcode** [comment]
The minimum number of points should be at least 2.
I guess it should be `front().relative_time() > relative_time`
I will create a fix
