### ISSUE TITLE
Lidar calibration with VLP-16

### ISSUE THREAD

**Issue by cxia30** [ApolloAuto/apollo#2742]
Hello,
I have only a vlp-16, can I still use the calibration tool? 
Thanks,

**Comment by MadoRui** [comment]
Sorry, in current version (Apollo 2.0) we only support the Velodyne HDL-64 calibration.
We now plan to update the LiDAR calibration in a few months when it should support VLP-16.

**Comment by agneevguin** [comment]
Are there any updates regarding the VLP-16 support?
