### ISSUE TITLE
Please talk about the development and debugging methods

### ISSUE THREAD

**Issue by silverland79** [ApolloAuto/apollo#2746]
I have learned to use bazel, but previously used to do windows development use IDE（visual studio）, so I do not know how apollo tracking debugging code, please talk about the basic configuration and use of the development environment.

**Comment by lianglia-apollo** [comment]
Usually, we filter out some topic in rosbag, and generate the topic from our own program. The log files (apollo/data/log/) and gdb are helpful for debugging.

**Comment by silverland79** [comment]
@lianglia-apollo Thank you very much.

**Comment by zhangjun-xyz** [comment]
@lianglia-apollo As for debugging using gdb, how do you control rosbag? While a debug session is running, a bag is also running, how do you let the two pause at the same time and step in to the code you are interested in?
