### ISSUE TITLE
What is the intended output/result of roslaunch velodyne velodyne_check_16.launch?

### ISSUE THREAD

**Issue by vivianistan** [ApolloAuto/apollo#2749]
I have a VLP-16 and was wondering how should `roslaunch velodyne velodyne_check_16.launch` finish?

Right now I do this: 
* `bash apollo/docker/scripts/dev_start.sh`
* `bash apollo/docker/scripts/dev_into.sh`
* `bash apollo.sh build_velodyne` (completes successfully)
* `rosluanch velodyne velodyne_check_16.launch`

Note: I have modified the `input.cpp` code in the velodyne driver to use system time instead of NMEA time from a gps. This was to avoid the error that says no gps is connected. 

`/apollo/modules/drivers/velodyne/velodyne_driver/src/lib/input.cpp:70 drivers::velodyne::Input::exract_nmea_time_from_packet() [ERROR] [1512254471.338525751]: Invalid GPS time: 65008-65008-65008 65008:65008:65008, make sure have connected to GPS device`

After substituting the timestamp andwhen the VLP-16 is properly connected I get this warning over and over: 

`/apollo/modules/drivers/velodyne/velodyne_pointcloud/src/compensator.cpp:162 drivers::velodyne::Compensator::query_pose_affine_from_tf2() [ WARN] [1517260079.659715356]: Can not find transform. 980780611.303532 Error info: . canTransform returned after 0.100851 timeout was 0.1.`

We think this transform error might be from a mismatch in the timestamps between the lidar and the computer.

We are still looking into this warning, but has anyone else run into this problem before? If we do fix this, how should `roslaunch velodyne velodyne_check_16.launch` terminate? 

Thanks!

**Comment by fengqikai1414** [comment]
@vivianistan compensator nodelete must work with gnss and tf2, you can comment the lines between 37 and 45  in  `/apollo/modules/drivers/velodyne/velodyne/start_velodyne_16.launch`, then 
* bash apollo.sh build_velodyne 
* bash roslaunch velodyne start_velodyne_16.launch
* rostopic hz /apollo/sensor/velodyne16/PointCloud2

**Comment by vivianistan** [comment]
I made the modifications you suggested in `/apollo/modules/drivers/velodyne/velodyne/start_velodyne_16.launch`, but when I run 
`roslaunch velodyne start_velodyne_16.launch` I get this warning: 

`/apollo/modules/drivers/velodyne/velodyne_driver/src/driver/driver.cpp:103 drivers::velodyne::VelodyneDriver::update_gps_top_hour() [ WARN] [1517856203.446391428]: Currrnt stamp:1951523247 less than previous statmp:2603000000. GPS time stamp maybe incorrect!`

Then some text and then nothing appears after that.

**Comment by vivianistan** [comment]
I took out the lines you specified, but then when I run `roslaunch velodyne start_velodyne_16.launch` I just get a warning 
`/apollo/modules/drivers/velodyne/velodyne_driver/src/driver/driver.cpp:103 drivers::velodyne::VelodyneDriver::update_gps_top_hour() [ WARN] [1517856203.446391428]: Currrnt stamp:1951523247 less than previous statmp:2603000000. GPS time stamp maybe incorrect!`

Then some other text then nothing prints after that. 

What does rostopic hz /apollo/sensor/velodyne16/PointCloud2 do?

**Comment by natashadsouza** [comment]
@vivianistan do you still have the same error message. Our apologies that we have not responded about it.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no questions in a while. Feel free to reopen if the issue persists.
Thanks!
