### ISSUE TITLE
how to use the  ublox.bin

### ISSUE THREAD

**Issue by zwqaoy** [ApolloAuto/apollo#275]
hello
how to use the ublox.bin (path: modules/drivers/gnss/test_data/ublox.bin)
thanks

**Comment by hillbrook** [comment]
ublox.bin is not used since we do not have  ublox parser now. 
We use novatel.bin to test NovAtel parser offline.
You can try it with following commands:  
```
$ parser_cli novatel.bin n
```

**Comment by zwqaoy** [comment]
thanks
