### ISSUE TITLE
[planning_module] lattice planner 和 em planner

### ISSUE THREAD

**Issue by zjuhitljx** [ApolloAuto/apollo#2768]
lattice planner和em planner各自有什么优点和缺点?
em planner在高速行驶（６0kph~120kph）时会遇到什么问题吗?

// 谢谢解答

**Comment by lianglia-apollo** [comment]
The EM planner has been tested to work at 0 - 105 kmh (0 - 65 mph). 

The lattice planner is still under development.

**Comment by KevinYuk** [comment]
> The EM planner has been tested to work at 0 - 105 kmh (0 - 65 mph).
> 
> The lattice planner is still under development.

Is there any official DOC to introduce the detail of EM planner?
