### ISSUE TITLE
运行dev_start.sh无法docker pull apollo_localization_volume?

### ISSUE THREAD

**Issue by qljsjy** [ApolloAuto/apollo#2769]
基于aarch64架构，pull dev-aarch64-20170927_1111后，提示：Error response from daemon:manifest for apolloauto/apollo:localization_volume-aarch64-latest not found.                                                                        请问是哪里的问题？我的git branch 是arm64_dev

**Comment by natashadsouza** [comment]
@qljsjy do you still encounter the error?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. Feel free to open it if the issue persists. Thanks!
