### ISSUE TITLE
How to debug code in Clion？

### ISSUE THREAD

**Issue by renzhuli** [ApolloAuto/apollo#2770]
Apollo Demo I have run through, I want to debug Apollo code, I now have the Bazel plugin installed in Clion, but I import Apollo Project can not be successful, do you know how to import Apollo in Clion? Thanks

**Comment by xiaoxq** [comment]
Sorry that we don't cover specific IDE issues.

Personally, I ever tried Clion's Bazel plugin and it doesn't work for me.
