### ISSUE TITLE
How can I get these configuration(mkz_config.pb.txt)?

### ISSUE THREAD

**Issue by turinglife** [ApolloAuto/apollo#2771]
How can I get these value of parameters? from lincoln_mkz's manual? or other source?

Thanks!

'modules/common/data/mkz_config.pb.txt'
vehicle_param {
  front_edge_to_center: 3.89
  back_edge_to_center: 1.043
  left_edge_to_center: 1.055
  right_edge_to_center: 1.055

  length: 4.933
  width: 2.11
  height: 1.48
  min_turn_radius: 5.05386147161
  max_acceleration: 2.0
  max_deceleration: -6.0
  max_steer_angle: 8.20304748437
  max_steer_angle_rate: 6.98131700798
  steer_ratio: 16
  wheel_base: 2.8448
  wheel_rolling_radius: 0.335
}

**Comment by startcode** [comment]
Some are from the specification (length, width, height, etc). Some are from measurements and it might depend on your own configuration (front_edge_to_center, etc.).

**Comment by turinglife** [comment]
@startcode 
How to measure this kind of parameters like 'front_edge_to_center'? Using a tape to measure? How to ensure the precision of measurement?

Many thanks!

**Comment by YangHan101** [comment]
@turinglife 
Measuring tape should do the job in most cases. If you would like to be safe, you can also leave some margin. 

If you aim to achieve higher precision, CAD model should give the better answer. I doubt the car manufacturers would provide them to public. Another way to achieve high precision is to use a theodolite to measure the positions of reference points on the car.

**Comment by turinglife** [comment]
@YangHan101 
so many thanks

**Comment by natashadsouza** [comment]
Closing as the issue seems to be resolved.
