### ISSUE TITLE
`/apollo/` directory structure overview

### ISSUE THREAD

**Issue by lyletbjohnson** [ApolloAuto/apollo#2773]
Hello,

To properly use, troubleshoot, and extend the system developers need to understand the directory structure. Is there existing documentation describing how the `/apollo/` code base is structured? 

I also have a specific question about the purpose of the `/apollo/data/core/` directory. Within my docker container, there are numerous large binary files (~1GB) for various modules, and in some cases numerous files for each module (for example `core_planning.1781` and `core_planning_1849`). 

These large files are polluting the file system, though I'm not sure what they're used for so I cannot properly clean them up. 

Please help with:

1. defining what binary files in `/apollo/data/core/` are used for, and 
2. pointing me to existing directory structure overview documentation

**Comment by lianglia-apollo** [comment]
You can safely delete the files under /apollo/data/core. They are not used for the main system.

**Comment by natashadsouza** [comment]
Closing as this issue seems to be resolved.

**Comment by pancumtneu** [comment]
I've got the same trouble these files occupied too many space.When I delete them ,they recover instantly! As a result there is insufficient disk for me .The system got jam.The DreamViem page has not changed.
