### ISSUE TITLE
Bazel command not found

### ISSUE THREAD

**Issue by lyletbjohnson** [ApolloAuto/apollo#2776]
While attempting to build Apollo modules, I experience the following error: 

```
$ source ./scripts/apollo_base.sh
$ ./apollo.sh build_opt_gpu
System check passed. Build continue ...
[INFO] Start building, please wait ...
./apollo.sh: line 90: bazel: command not found
============================
[ERROR] Build failed!
[INFO] Took 0 seconds
============================
```

There have been no explicit changes to the environment that would interact with bazel, however the system is clearly not happy. 

The command `which bazel` returns an empty string, indicating the tool doesn't exist.

Is there a way to source the bazel environment manually? At what step in Apollo installation is bazel installed / configured? 

Please post commands / troubleshooting steps and I'll follow up with information about my system.

**Comment by jinghaomiao** [comment]
Please make sure you are building inside a docker container. Please refer to README for docker environment setup.

**Comment by lyletbjohnson** [comment]
Thank you, this was my issue. 

I kindly request that startup documentation is updated to explicitly call out when commands are run within the host, or within the docker container.

**Comment by Zhenni17** [comment]
@lyletbjohnson thank you for your request! We will integrate your request and revising our startup documentation.
