### ISSUE TITLE
apollo-adminservice apollo-configservice 报错如下？

### ISSUE THREAD

**Issue by hexulin-miaomiao** [ApolloAuto/apollo#2788]
Caused by: java.lang.IllegalArgumentException: Host name may not be null。。。。

这个怎么解决啊

**Comment by ycool** [comment]
Any more contexts?

**Comment by Zhenni17** [comment]
Hi @hexulin-miaomiao , 

Is the issue still relevant? If not, please provide more context for the issue. If there is no more additional comment within next 72 hours, we will close the issue.

你的问题解决了吗？如果还没有的话，请告诉我们你是在哪个情况下遇到这个error message? 如在未来72小时我们没有收到更多回复，这个issue会被关掉。如还有问题，你可以随时再开新的issue。

谢谢使用Apollo。

Best,
Zhenni - Apollo Community Manager
