### ISSUE TITLE
head file in directory

### ISSUE THREAD

**Issue by martinfong** [ApolloAuto/apollo#279]
Some head files(modules/canbus/proto/canbus_conf.pb.h modules/canbus/proto/chassis.pb.h etc.)were included in the file lincoln_controller.h, and there are no mentioned files in directory modules/canbus/proto

**Comment by startcode** [comment]
These header files (e.g., `modules/canbus/proto/canbus_conf.pb.h`) are generated by [Protobuf](https://developers.google.com/protocol-buffers/docs/overview). The proto definitions are in `modules/canbus/proto/canbus_conf.proto`. 
If you really want  to see these generated `pb.h` files,  build apollo first following the [README](https://github.com/ApolloAuto/apollo/blob/master/README.md), and you will see them in the `bazel-genfiles/modules/canbus/proto/` directory.
