### ISSUE TITLE
Dreamview localhost isn't working

### ISSUE THREAD

**Issue by Hadar96** [ApolloAuto/apollo#2791]
HI!
Im working on an Oracle VirtualBox that runs Ubuntu64 17.04 on my windows10 computer.
I've installed apollo on the VB and everything worked fine (the docker, building and bootstrap) until I got the address of localhost:8888, which I can't connect to. 
I don't know why I can't connect to the address (in firefox).
I tried to change "localhost" to "1.0.2.2" but still it doesn't help.

please help me :)

**Comment by startcode** [comment]
Can you check if the dreamview process is there?
Run the following command in your Ubuntu.
```
ps -ef | grep dreamview
```

Also check the logs and see if there is any error. Logs are located in
/apollo/data/log/dreamview.*

**Comment by pninoh** [comment]
If u run ff on you win10, the "localhost" route to the ip of win10.
You can try it  use the VB's ip.

**Comment by Hadar96** [comment]
@startcode I checked the logs and I only have apollo/data/log/roscore.out (which is attached here as .txt).
[roscore.txt](https://github.com/ApolloAuto/apollo/files/1711179/roscore.txt)


Also when I tried "ps -ef | grep dreamview" I got 
"osboxes (my username)   318   48   0   15:25   pts/3   00:00:00   grep   - -color=auto   **dreamview**"

**Comment by siyangy** [comment]
Try running `./scripts/dreamview.sh start_fe` to run dreamview in foreground to see what log it spits out.

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.
