### ISSUE TITLE
Should I change the parameter of "--hostname" to "${LOCAL_HOST}" in line 102 of "dev-start.sh" ?

### ISSUE THREAD

**Issue by 349516385** [ApolloAuto/apollo#28]
After I do that,I build successfully,otherwise faild ( "invalid hostname format: in_dev_docker").

**Comment by ycool** [comment]
dev-start.sh line 102
    --hostname in_dev_docker \

It is to temporarily set hostname to in_dev_docker inside the docker env. It makes easier to tell if it is inside a docker or not. Changing hostname to other name is fine. 

Btw, what's the ouput of `docker --version` ? 

Thanks.

**Comment by 349516385** [comment]
@ycool  The ouput of docker --version is    "Docker version 1.12.3, build 6b644ec" . Thanks :-D

**Comment by startcode** [comment]
It is likely the Docker's version problem. On my box, it is 

`% docker --version`
`Docker version 17.05.0-ce, build 89658be`

Can you try to install or update Docker with the provided script, and try again?
`bash docker/scripts/install_docker.sh`
