### ISSUE TITLE
Why The Apollo does not open all the source code?  Fox example in the docker environment there are some compiled dependent libraries.

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#2837]
And we can see that in fact the core of the algorithmic code are open source, these non-open source code instead is a number of tool libraries, such as deep learning framework, some tools classes and so on.
Why not open all the code? For partners to use it more flexible ~

**Comment by startcode** [comment]
We are working relentlessly to open-source the self-driving related code. But there are still a lot of work need to do, including non-technical work, before releasing the source code. Please be patient and keep tuned. Thank you.
