### ISSUE TITLE
Can not see HMI 

### ISSUE THREAD

**Issue by martinfong** [ApolloAuto/apollo#284]
_After executing bash apollo.sh build
and the result  as show below_ 
......
____Timeout connecting to https://github.com/ApolloAuto/apollo-platform/releases/download/1.0.0/ros-indigo-apollo-1.0.0.x86_64.tar.gz
____Timeout connecting to https://github.com/ApolloAuto/apollo-platform/releases/download/1.0.0/ros-indigo-apollo-1.0.0.x86_64.tar.gz
ERROR: query interrupted.
Building on x86_64, with targets:

### WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 0 targets...
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-out -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out:  /apollo/bazel-out (Read-only file system)
  cannot create symbolic link bazel-out -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out:  /apollo/bazel-out (Read-only file system)
  cannot create symbolic link bazel-apollo -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo:  /apollo/bazel-apollo (Read-only file system)
  cannot create symbolic link bazel-bin -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin:  /apollo/bazel-bin (Read-only file system)
  cannot create symbolic link bazel-testlogs -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs:  /apollo/bazel-testlogs (Read-only file system)
  cannot create symbolic link bazel-genfiles -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/genfiles:  /apollo/bazel-genfiles (Read-only file system).
INFO: Elapsed time: 7.943s, Critical Path: 0.02s
============================
[ OK ] Build passed!
[INFO] Took 3693.013 seconds
============================
find: `bazel-genfiles/*': No such file or directory

_and then execut  bash scripts/hmi.sh_
_The result as show below_
Start roscore...
HMI ros node service running at localhost:8887
HMI running at http://localhost:8887

_Finally, I access the address http://localhost:8887 with chrome
and the result show below_

localhost refused connectiong request

My questions are :
1.Is it OK in bulding the apollo project?
2. How to show HMI with chrome?

**Comment by martinfong** [comment]
reexecution with command bash apollo.sh build
and get the result as following:

_......
//modules/canbus/proto:canbus_proto.pb
//:x86_64
//:arm64
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 190 targets...
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-out -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out:  /apollo/bazel-out (Read-only file system)
  cannot create symbolic link bazel-out -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out:  /apollo/bazel-out (Read-only file system)
  cannot create symbolic link bazel-apollo -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo:  /apollo/bazel-apollo (Read-only file system)
  cannot create symbolic link bazel-bin -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin:  /apollo/bazel-bin (Read-only file system)
  cannot create symbolic link bazel-testlogs -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs:  /apollo/bazel-testlogs (Read-only file system)
  cannot create symbolic link bazel-genfiles -> /home/fxy/.cache/bazel/_bazel_fxy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/genfiles:  /apollo/bazel-genfiles (Read-only file system).
ERROR: /apollo/modules/control/proto/BUILD:6:1: C++ compilation of rule '//modules/control/proto:control_proto' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g '-std=c++0x' '-DUSE_ESD_CAN=false' -MD -MF ... (remaining 87 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from bazel-out/local-dbg/genfiles/modules/control/proto/control_cmd.pb.h:31:0,
                 from bazel-out/local-dbg/genfiles/modules/control/proto/control_cmd.grpc.pb.cc:5:
./modules/canbus/proto/chassis.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
./modules/canbus/proto/chassis.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
./modules/canbus/proto/chassis.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from bazel-out/local-dbg/genfiles/modules/control/proto/control_cmd.pb.h:31:0,
                 from bazel-out/local-dbg/genfiles/modules/control/proto/control_cmd.grpc.pb.cc:5:
./modules/canbus/proto/chassis.pb.h:25:60: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
 #include <google/protobuf/generated_message_table_driven.h>
                                                            ^
compilation terminated.
INFO: Elapsed time: 416.427s, Critical Path: 347.29s
============================
[ERROR] Build failed!
[INFO] Took 572.626 seconds
============================
fxy@in_dev_docker:/apollo$_

**Comment by xiaoxq** [comment]
Could you run the following command:
  bazel clean
  bazel build //modules/control/proto/...
  bazel build //modules/canbus/proto/...
They should pass, or else your docker container might be unhealthy.

**Comment by martinfong** [comment]
execute the command "bazel build //modules/control/proto/..."
It reported error and the result as show below.
My OS is ubuntu-14.04.5-desktop-amd64.iso


fxy@in_dev_docker:/apollo$ bazel build //modules/control/proto/...
INFO: Found 3 targets...
ERROR: /apollo/modules/canbus/proto/BUILD:6:1: C++ compilation of rule '//modules/canbus/proto:canbus_proto' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 87 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from bazel-out/local-fastbuild/genfiles/modules/canbus/proto/chassis.pb.cc:5:0:
./modules/canbus/proto/chassis.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
./modules/canbus/proto/chassis.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
./modules/canbus/proto/chassis.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from bazel-out/local-fastbuild/genfiles/modules/canbus/proto/chassis.pb.cc:5:0:
./modules/canbus/proto/chassis.pb.h:25:60: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
 #include <google/protobuf/generated_message_table_driven.h>
                                                            ^
compilation terminated.
INFO: Elapsed time: 0.799s, Critical Path: 0.41s
fxy@in_dev_docker:/apollo$ protoc --version
libprotoc 3.1.0
fxy@in_dev_docker:/apollo$

**Comment by xiaoxq** [comment]
Hi martinfong, are you still there?

Would you please confirm if you still meet compiling errors?
