### ISSUE TITLE
Are there more reference documents for planning part? Such as blogs, papers

### ISSUE THREAD

**Issue by KarlRong** [ApolloAuto/apollo#2844]
It's quite hard to comprehensive the code directly and it will be great if you may show me more reference papers. Thanks a lot

**Comment by lianglia-apollo** [comment]
The planning part is not based on existing papers, so it might be hard to understand. I suggest you start from reading the documents "https://github.com/ApolloAuto/apollo/blob/master/docs/specs/qp_spline_st_speed_optimizer.md" and "https://github.com/ApolloAuto/apollo/blob/master/docs/specs/reference_line_smoother.md".

We are developing a self-driving car intro course with Udacity. Stay tuned!
 (https://www.udacity.com/apollo)

**Comment by KarlRong** [comment]
Thanks a lot!  Sorry for I didn't check docs first.
