### ISSUE TITLE
how to define topic

### ISSUE THREAD

**Issue by martinfong** [ApolloAuto/apollo#286]
I want to know what topics were be published or subscribed by a node and  found a  topic named as FLAGS_chassis_topic. But I don't know this topic's real position with format /XX/XXX.  I want to know how to define the FLAGS_chassis_topic

**Comment by ycool** [comment]
Default value is at https://github.com/ApolloAuto/apollo/blob/master/modules/common/adapters/adapter_gflags.cc

You can override it at https://github.com/ApolloAuto/apollo/blob/master/modules/canbus/conf/canbus.conf

**Comment by martinfong** [comment]
@ycool 
Thank you  for your help.
There included a file "gflags/gflags.h" in head file "modules\common\adapters\adapter_gflags.h"
I could't find it in  modules directory and it's sub-directories 
Where can i find the file gflags.h?

**Comment by ycool** [comment]
gflags comes from external google gflags package: https://gflags.github.io/gflags/. Its dependency is pulled by bazel.

**Comment by martinfong** [comment]
Thanks
