### ISSUE TITLE
Replace Protocol Buffers with more memory & computation efficient FlatBuffers

### ISSUE THREAD

**Issue by futurely** [ApolloAuto/apollo#288]
http://google.github.io/flatbuffers/flatbuffers_benchmarks.html

**Comment by quning78** [comment]
We know there are a couple of alternatives around and they each have their
own advantages. It's welcome if you wanna contribute to this direction.

thanks!

Best wishes,
-- 
Ning Qu

**Comment by quning78** [comment]
Btw, we also find this comparison is interesting:

https://discuss.dgraph.io/t/comparison-of-protocol-buffers-v-s-flatbuffers/1085/5

Best wishes,
-- 
Ning Qu

**Comment by futurely** [comment]
The above benchmark you found was written with Go while this project is written with C++. The workload used in the benchmark is not representative of real data. What data did you use to benchmark the communication throughput and CPU utilization? What are the alternatives you considered?

https://baijiahao.baidu.com/po/feed/share?context=%7B"nid"%3A"news_3591946182007127550"%2C"sourceFrom"%3A"bjh"%7D&fr=bjhauthor&type=news
![image](https://user-images.githubusercontent.com/9004594/29546955-d5ed2cbc-8729-11e7-950f-4e085b3acaea.png)

**Comment by quning78** [comment]
Could you share more details when you said:  "The workload used in the benchmark is not representative of real data".

The data test setup we used is simply showed in the slides you posted.

For alternatives, we see the advantage from different solutions  by using different test sets.

**Comment by futurely** [comment]
Real data means data actually sent when a car is running on the road. Since your tests did not show any solution win consistently, you may want to record and replay the real data to see which one works best in practice.

**Comment by lxbeyond** [comment]
@quning78 could you provide the test code in the slides that shows the shared memory performance ?

**Comment by natashadsouza** [comment]
Sorry we could not get back to you on this request. Please let me know if you still need support on your request. Feel free to re-open the issue.
