### ISSUE TITLE
Get routing data loading .bag files

### ISSUE THREAD

**Issue by rseibane** [ApolloAuto/apollo#2880]
Hi,

We are running Apollo just by loading .bag files. Using the ros topics, we have been able to get data from prediction, localization and planning but we cannot get the data from the routing module. A few questions about this trouble: 

- Is it possible to find this data just by loading .bag files? Which is the right topic to find this messages?
- Should this data be published in the topics _/apollo/routing_response_?

Thanks in advance,

**Comment by startcode** [comment]
This data should be in topic: `/apollo/routing_response`
If it is not there in the rosbag, you can create it by yourself.
First, make sure the routing module has been enabled in "Module Controller" on the left side of Dreamview;
Then use the 'Route Editing' button on the left side of Dreamview.
Click at least two points on the map, then click 'Send Routing Request", you should be able to see new red routing lines in Dreamview.

**Comment by rseibane** [comment]
Thanks, we got it. I also was wondering about the software design decisions you have made in Apollo.

- The `/apollo/routing` request are send periodically from the `planning` to the `routing`, including the current location and the target location. Correct me if I'm wrong. So, why is not the `routing` module subscribed to a `localization` topic directly?
- Why there is no topic for the `HD-Map`?

Thanks in advance!

**Comment by maziqiqi** [comment]
Dear Rseibane,
How to get the data of localization?

Thanks in advance!

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. Feel free to open it if you have any more questions.
