### ISSUE TITLE
Cannot record rosbag

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#2902]
I am not able to record rosbags successfully. I tried running 'rosbag record -a' but it halts while subscribing to 'rosout' and then doesn't continue. If I run 'rosbag record /topicNameA /topicNameB' then I am able to generate a rosbag. But when I play it back, 'rostopic list' doesnt show any topics. I tried the 'scripts/record_bag_local.sh' but that also didn't help.
Any idea what is happening ?

**Comment by xiaoxq** [comment]
Is roscore running? Is there any output from "rostopic echo"?

**Comment by ankitvora7** [comment]
Turns out, my terminal was in a weird state! Doing this in a new terminal solved. But I still don't understand why don't we record /rosout ? The record_rosbag script also doesn't subscribe to /rosout
