### ISSUE TITLE
Open loop testing?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#2914]
Hello Apollo team

I am curious if Apollo platform comes with open loop testing application that allows one to observe the vehicle response to the manual input (throttle/steering wheel angle).
If not, what will be the good way to test this?

Thank you!

**Comment by xiaoxq** [comment]
Generally speaking, you'd better get a *physical* switch which could connect/disconnect the software layer with vehicle. In that way you can record the data safely and analyze later.

Other than that, you can also shut down the canbus module, which is sort of *soft* switch. In this way, you can collect data from higher level modules such as planning and control.

**Comment by Zhenni17** [comment]
Hi @wckorealsh, 

Hope @xiaoxq answered your question. If not, please leave additional question or feedback below. Otherwise, the issue will be closed in 72 hours.

Thank you for changing the future of mobility with us by using Apollo! :)

Best,
Zhenni - Apollo Community Manager
