### ISSUE TITLE
Localhost:8888  can't be reached. 

### ISSUE THREAD

**Issue by GooGators** [ApolloAuto/apollo#2916]
Hi Apollo Team 

I followed the steps to access DreamView, but the localhost cannot be reached.
everything seems good except two errors as following:

%-------------------------------------------------------------------------
gogators@gogators:~/apollo$ docker/scripts/dev_start.sh
[sudo] password for gogators: 
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20180130_1338 ...
dev-x86_64-20180130_1338: Pulling from apolloauto/apollo
Digest: sha256:c4c153fa44480e284d3d843819e6ad367452e922dd665e3970a3e6972c3879fc
Status: Image is up to date for apolloauto/apollo:dev-x86_64-20180130_1338
modprobe: ERROR: could not insert 'nvidia': No such device
modprobe: ERROR: could not insert 'nvidia_uvm': No such device
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:b56b7526484aa4e70f9e6c9f7df028c7560d7a3d8df0fee7de984b5f43fad14e
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
ff1c652d640618720b924ad0cc632e377573fe00bea751067778301d8c233768
[INFO] Starting docker container "apollo_dev" ...
c8d740f8639f0c5e319348374a2ec406957e02e6a8f4e34b68cb48b9c9f56764
Adding group `gogators' (GID 1000) ...
Done.
Adding user `gogators' ...
Adding new user `gogators' (1000) with group `gogators' ...
The home directory `/home/gogators' already exists.  Not copying from `/etc/skel'.
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
%-----------------------------------------------------------------------------------------------------------

Hope you guys can help me to fix it, Thanks a lot.

**Comment by xiaoxq** [comment]
Did you build successfully? After that you should also run "scripts/bootstrap.sh start".

**Comment by GooGators** [comment]
Yes,built successfully. and then run "./scripts/bootstrap.sh" as the introduction. Finally, shows:
Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888

But the localhost cannot be reached...

**Comment by ytzhao** [comment]
Hi Apollo team,
I've also met the same problem. I run Apollo version 2.0 on docker 17-12.0-ce.
```bash
walle-dl@in_dev_docker:/apollo$ bash scripts/bootstrap.sh run
Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888
```
And then I opened a the page `http://localhost:8888` with firefox, but it shows that `Unable to connect...`

Hope you guys can help me to address this problem, thank you :)

**Comment by ytzhao** [comment]
@GooGators Hi, did you do build the apollo from source after you first step into the docker?
``` bash
# To get a list of build commands
./apollo.sh
# To make sure you start clean
./apollo.sh clean
# This will build the full system and requires that you have an nVidia GPU with nVidia drivers loaded
bash apollo.sh build
```
After you build the source apollo code, have another try! Good luck to you :)

**Comment by GooGators** [comment]
@ytzhao Yes, it has been built successfully. Do you have any idea to fix this problem?

**Comment by drwnz** [comment]
I'm having similar issues. I am running Apollo on two computers, both build and run fine. On one computer, dreamview also is accessed successfully. On the other, while everything seems OK and the `Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888`
messgae appears after running bootstrap.sh. But http://localhost:8888 can not be accessed. I have looked into the "supervisord.log" and see the following:
`2018-03-06 15:42:55,042 INFO RPC interface 'supervisor' initialized
2018-03-06 15:42:55,042 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-03-06 15:42:55,043 INFO daemonizing the supervisord process
2018-03-06 15:42:55,043 INFO supervisord started with pid 99
2018-03-06 15:42:55,148 INFO spawned: 'monitor' with pid 103
2018-03-06 15:42:56,150 INFO success: monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-03-06 15:42:56,268 INFO spawned: 'dreamview' with pid 152
2018-03-06 15:42:56,641 INFO exited: dreamview (terminated by SIGILL (core dumped); not expected)
2018-03-06 15:42:57,645 INFO spawned: 'dreamview' with pid 243
2018-03-06 15:42:57,830 INFO exited: dreamview (terminated by SIGILL (core dumped); not expected)
2018-03-06 15:42:59,837 INFO spawned: 'dreamview' with pid 245
2018-03-06 15:43:00,020 INFO exited: dreamview (terminated by SIGILL (core dumped); not expected)
2018-03-06 15:43:03,025 INFO spawned: 'dreamview' with pid 247
2018-03-06 15:43:03,234 INFO exited: dreamview (terminated by SIGILL (core dumped); not expected)
2018-03-06 15:43:07,241 INFO spawned: 'dreamview' with pid 249
2018-03-06 15:43:07,432 INFO exited: dreamview (terminated by SIGILL (core dumped); not expected)`

Any ideas or help much appreciated!

**Comment by xiaoxq** [comment]
Supervisor is not a good way for development. In recent change (https://github.com/ApolloAuto/apollo/commit/67fad1f572b3f1973b695af5bab093546ee7fa0d), I have removed it from debugging mode.
However, if you are using Apollo for some production scenarios, Supervisor could provide a second chance to recover the modules, which makes the more robust. Pass "--prod_mode" when starting dreamview for such use case.

You should see more detailed information at data/log/dreamview.out if you still encounter this problem.

**Comment by HongKunD** [comment]
@GooGators hi guys,I have the same problem,did you find any way to fix it?I tried my best to fix it,but failed
