### ISSUE TITLE
Can Apollo support VSCode?

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#2927]
VSCode is a good development environment in Linux and it supports Docker. I think you can do some work and give a solution to compile and debug the Apollo project in VSCode. If you are familiar with VSCode, it may not be a complicated task.Thanks for your efforts.

**Comment by davidhopper2003** [comment]
I figured it out. Please refer to my blog: http://blog.csdn.net/davidhopper/article/details/79349927

**Comment by xiaoxq** [comment]
Excellent! Please feel free to submit a pull-request. Or we can do that following your blog :)

Thank you a lot!

**Comment by davidhopper2003** [comment]
@xiaoxq You can update the Apollo project with reference to my blog. You can also modify my codes if necessary.

**Comment by Capri2014** [comment]
@davidhopper2003 Thanks!

**Comment by Zhenni17** [comment]
@davidhopper2003 thank you for your blog! 👍

**Comment by kk2491** [comment]
@Zhenni17 @davidhopper2003 ... Could you please let me know if the procedure has been updated in the Apollo repository .. Also kindly give me the location... I hope it is updated in English .. Sorry I was not able to understand the original blog post as it is in Chinese language ..

**Comment by davidhopper2003** [comment]
@kk2491 You can open the hidden directory `.vscode` in the `apollo` root directory and view contents of the `tasks.json` and `launch.json` configuration files. Hope you can find the answer soon. 
Best regards.
