### ISSUE TITLE
Missing include of standard header files

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#2930]
I encountered them during x-compile onto qnx.

1.   "#include <sys/time.h>" is missing from modules/canbus/vehicle/lincoln/protocol/steering_65.h for reference to "struct timeval"

2.  "#include <sys/time.h>" is missing from modules/canbus/vehicle/lincoln/protocol/wheelspeed_6a.h for reference to "struct timeval"

3. "#include \<array>" is missing from modules/common/math/integral for reference to "std::array"

**Comment by Capri2014** [comment]
@jilinzhou thanks for the feedback, commit has been submitted to resolve this issue, please feel free to create a PR directly in the future. https://github.com/ApolloAuto/apollo/pull/2931/files
