### ISSUE TITLE
apollo 百度云服务

### ISSUE THREAD

**Issue by zuoshaobo** [ApolloAuto/apollo#294]
https://console.bce.baidu.com/apollo/

# 输入用户名和密码，用户名和密码请到入门指南页查询
username: {USERNAME}
password: {PASSWORD}

找不到用户名密码，在哪里呢？

**Comment by judyfish** [comment]
同问！

**Comment by Zhenni17** [comment]
@judyfish @zuoshaobo ， thank you for your question! I just checked the link again, and i no longer see the message that says "用户名和密码请到入门指南页查询". At the current version, you can register an new account on the page with Baidu Cloud and use that registered account to access the Baidu cloud service.

I am closing the issue for now, and please feel free to re-open the issue if I missed anything.
