### ISSUE TITLE
how to run *test.cc  quickly

### ISSUE THREAD

**Issue by slam4code** [ApolloAuto/apollo#296]
There are many *_test.cc in modules.for example: **modules/control/common/interpolation_1d_test.cc**
questions:
1), how can we  run these test manually，such as interpolation_1d_test.cc ?
2), how can we **build** （compile）new  test.cc **quickly?**.for example:modules/control/my_test.cc

**Comment by startcode** [comment]
You can try the following command to compile and test a particular unit test inside dev docker.
```
bazel test --config=unit_test //modules/control/common/interpolation_1d_test
```

**Comment by zuomaidi52** [comment]
bazel run  //modules/control/common/interpolation_1d_test

**Comment by zuomaidi52** [comment]
**Compile**
`bazel test --config=unit_test //modules/control/common/interpolation_1d_test`
**Run**
`bazel run --config=unit_test //modules/control/common/interpolation_1d_test`

**Comment by cheerudeep** [comment]
Update
Looks like there is a change in syntax for the latest version of bazel 

bazel test --config=unit_test //modules/control/common:interpolation_1d_test
