### ISSUE TITLE
Can we get the docker/dev.x86_64.dockerfile for Apollo v2.0.0?

### ISSUE THREAD

**Issue by louietsai** [ApolloAuto/apollo#2962]
Hi 
Want to build a docker image for a new platform.
the docker/dev.x86_64.dockerfile file in Apollo v1.5.0 seems to work for our case.

however, I can't find the dockerfile or the dev_create.sh script in Apollo v2.0.0.

Can you help me to find a dockerfile for Apollo v2.0.0?

thanks

**Comment by xiaoxq** [comment]
May I know what is your platform and host environment?
You know, in most cases the docker image should be reusable.

**Comment by louietsai** [comment]
Hi Xiaoxq
I used Intel Atom platform which may have different instruction sets from Intel Core i7/i5 platforms.
the compiler is the same, but some compilation flags may generate different binary according to platforms.
for example, "gcc -03 ...." may generate binaries with AVX2 instruction which Intel Atom doesn't support.

I faced some illegal instructions by using Apollo V2.0.0 docker image, so would like to re-generate for Intel Atom.

thanks
Louie

**Comment by louietsai** [comment]
Hi Xiaoxq
most modules should be able to run on Intel Atom by changing opt flag for bazel.
however, still have architecture dependency for pre-compiled liblocalization_msf_local_integ.so file.

in short, I can run most of the modules of Apollo v2.0.0 on Intel Atom now.
thanks
