### ISSUE TITLE
Load specific terrain

### ISSUE THREAD

**Issue by magick93** [ApolloAuto/apollo#2968]
Hello

Is it possible to load a custom terrain/map into Apollo/Dreamview?

My specific use-case is that Im looking at developing an autonomous offer road vehicle, and would like to run simulations using the specific terrain.

Thanks

**Comment by natashadsouza** [comment]
Sorry we did not get back to you on this request. Are you still looking to add terrain to Dreamview?

**Comment by magick93** [comment]
Yes. That would be of great interest.

Thanks

**Comment by natashadsouza** [comment]
We are unfortunately not going to be adding terrain as part of Dreamview any time soon. It is definitely something on our future scope list. @magick93 if you do have some ideas, we would love to hear them.
