### ISSUE TITLE
hadmap中pointset点的是指什么？

### ISSUE THREAD

**Issue by maziqiqi** [ApolloAuto/apollo#2997]
问一下数据开放平台里自定位模块的演示数据里的hadmap中pointset点的是指什么？我在OpenDrive地图格式中没有找到相应内容。
![_20180224200800](https://user-images.githubusercontent.com/36752345/36627948-79ec24a6-199e-11e8-95c4-c31e5cb09355.png)

**Comment by msbeta** [comment]
HDMap中的PointSet是表示点的集合，它的子节点是一系列的坐标点。百度高精地图OpenDrive格式对标准的OpenDrive格式基础上做了扩展，所以部分元素和属性是标准OpenDrive所不具有的。

**Comment by maziqiqi** [comment]
从百度ego localization system流程图上看，这些点应该是高精地图中的 Pre-stored location feature, 用来和real-time  location feature 进行matching。 而且real-time  location feature应该是照相机拍摄的照片中的点。那么高精地图和照片中的特征点是如何提取的，有照片特征点的相关数据吗？
![flowchart](https://user-images.githubusercontent.com/36752345/36629271-d9750fc4-19a7-11e8-9260-2675a6abdfde.jpg)

**Comment by mickeyouyou** [comment]
抱歉，这些特征点属于高精地图的细节内容，未在开源之列。
