### ISSUE TITLE
Do we have a script to restart apollo?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#300]
I start HMI bash scripts/hmi.sh
 and some nodes are runing behind the scenes.

how can I shutdown them , and I must use kill cmd ?

**Comment by xiaoxq** [comment]
As you know, the system is container-based. So if you are using a release
image, simply restart the container.

If you are using dev image and don't want to start from scratch, you have
two choices:
1. Run all the modules' stop-command, e.g.:
./scripts/control.sh stop
2. Switch on all modules on HMI. If the module is already in running, the
operation will not affect it. Then you can switch it off, which actually
does the same thing as #1.


Xiangquan Xiao | 肖祥全
Senior Software Engineer, Baidu USA LLC.
(650) 279-2727

**Comment by xiaoxq** [comment]
Forget to mention that there is also a "Reset All" button on top right of HMI, which will kill all running modules. It should be the thing you want!
