### ISSUE TITLE
unable to connect local:8888, supervisorctl: command not found

### ISSUE THREAD

**Issue by ytzhao** [ApolloAuto/apollo#3003]
Hi everyone,
I'm a freshman to Apollo. I failed to access Dreamview when I run Apollo version 2.0 in docker.
```
walle-dl@in_dev_docker:/apollo$ bash scripts/bootstrap.sh run
Start roscore...
Started supervisord with dev conf
scripts/bootstrap.sh: line 36: supervisorctl: command not found
scripts/bootstrap.sh: line 41: supervisorctl: command not found
Dreamview is running at http://localhost:8888
```

Then I opened a the page `http://localhost:8888` with firefox, but it shows that `Unable to connect`...

| other information | |
| --- | --- |
| Operating system |  ubuntu 16.04 |
| Docker version | docker 17-12.0-ce |
| Apollo version | 2.0 (master branch - 2018.02.24) | 
| other | pre-installed ROS-indigo on ubuntu |

Hope you guys can help me to address this problem, thank you very much :)

**Comment by startcode** [comment]
Seems `supervisor` is not intalled.
Try
```
sudo pip install supervisor
echo_supervisord_conf > supervisord.conf
sudo mv supervisord.conf /etc/
```

**Comment by ytzhao** [comment]
Thank you, I've already solve the problem. :+1:
