### ISSUE TITLE
 apollo中 高精度地图

### ISSUE THREAD

**Issue by ydl1986** [ApolloAuto/apollo#3004]
高精度地图在定位、感知、决策中都具有重要作用，如果要实车搭建apollo 2.0系统， 高精度地图如何制作？

**Comment by msbeta** [comment]
高精地图的制作是一项非常复杂的技术，现在的技术方案也很多，主流的基本是通过激光雷达或者视觉Camera制图。
Apollo中对地图的制作方式没有限制，只要能把制作的地图转换成Apollo的地图格式，都可以使用Apollo的所有服务。
