### ISSUE TITLE
./apollo.sh build_no_perception dbg --> build msf_localization failed

### ISSUE THREAD

**Issue by scorpionfish** [ApolloAuto/apollo#3009]
apollo@in_dev_docker:/apollo$ ./apollo.sh build_no_perception dbg
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
[INFO] Skip building perception module!
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/localization/msf/BUILD:5:1: no such package '@local_integ//': Expected directory at /usr/local/apollo/local_integ but it does not exist. and referenced by '//modules/localization/msf:msf_localization'
ERROR: Analysis of target '//modules/localization/msf:msf_localization' failed; build aborted
INFO: Elapsed time: 6.276s
FAILED: Build did NOT complete successfully (5 packages loaded)
    currently loading: @bazel_tools//tools/test
============================
[ERROR] Build failed!
[INFO] Took 10 seconds
============================

**Comment by scorpionfish** [comment]
root error:

apollo@in_dev_docker:/apollo/modules/localization$ bazel build :localization_lib
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed target //modules/localization:localization_lib (0 packages loaded).
INFO: Found 1 target...
ERROR: /apollo/modules/localization/BUILD:23:1: C++ compilation of rule '//modules/localization:localization_lib' failed (Exit 1)
In file included from modules/localization/localization.cc:23:0:
./modules/localization/msf/msf_localization.h:42:40: fatal error: include/localization_integ.h: No such file or directory
 #include "include/localization_integ.h"
                                        ^
compilation terminated.
Target //modules/localization:localization_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.728s, Critical Path: 7.01s
FAILED: Build did NOT complete successfully

**Comment by zhouyao4321** [comment]
This command "./apollo.sh build_no_perception dbg" works well on my computor. Does the folder path "/usr/local/apollo/local_integ" exist? If it doesn't exist, maybe you should update the docker environment by "./docker/scripts/dev_start.sh".

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication for a while. Feel free to open it up if you have additional questions.
