### ISSUE TITLE
how can we use ros service in  apollo?

### ISSUE THREAD

**Issue by MonkeyTang** [ApolloAuto/apollo#302]
http://wiki.ros.org/roscpp/Overview/Services, we know, the service is defined by srv file, I want to know how can I use protobuf to define a service，how can I use ros service in this apollo?

**Comment by fengqikai1414** [comment]
We don't have the pb support for the service part, since we don't rely on that feature. I know they are both based on msg, however, service with pb support is not integrated yet.

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
