### ISSUE TITLE
ImportError: No module named apputils.app

### ISSUE THREAD

**Issue by GerberaTetra1991** [ApolloAuto/apollo#303]
bash scripts/hmi.sh
.................................
...................................
Start roscore...
HMI ros node service running at localhost:8887
Failed to start HMI.
Traceback (most recent call last):
  File "modules/hmi/web/hmi_main.py", line 21, in <module>
    import google.apputils.app
ImportError: No module named apputils.app

I  can run the HMI  before lasttime！

**Comment by xiaoxq** [comment]
Are you in docker?

It's a python library named google-apputils, which should be already contained in docker image.

Or else you need to install the python libraries with "pip install -r py27_requirements.txt"
https://github.com/ApolloAuto/apollo/blob/master/modules/tools/py27_requirements.txt
