### ISSUE TITLE
how to mount /apollo/data folder to another disk

### ISSUE THREAD

**Issue by ytzhao** [ApolloAuto/apollo#3033]
Hi everyone,

I'm just starting using apollo 2.0 on my desktop. There is the problem I met. My desktop has 2 disks, one is about 200G ssd, and another disk is 1T hdd. I installed the Ubuntu1604 and apollo 2.0 on ssd. At the beginning, I did not pay attention to the disk usage on ssd. This morning, after I reboot the computer, I failed to access into the system with this message 
```bash
Low disk space: The volume "Filesystem root" has only 0 bytes disk space remaining...
````
I force deleted some documents and enter into the system. I mentioned that apollo occupies 150G on the disk. The folder `apollo/data` takes about 135G.       

Therefore, is it ok that I move the `apollo/data` out of the apollo root folder to a hdd disk, and make a link back to it? Or maybe there's a solution that I could modify the data configuration settings, but how? ( I find a `recorder.global.yaml` under `apollo/modules/data/conf` folder, only need to modify this file or anything else?)

Thank you smart guys and have a nice day!

**Comment by startcode** [comment]
The quick and easy way is to create a softlink for apollo/data, and link it to your HDD.
I guess the majority of the data is the log. 
You can use glog's default '--log_dir' setting to point it to your HDD. You have to change it for each module in the 'conf/xxx.conf' file.

**Comment by ytzhao** [comment]
Thank you, I've done with the soft link way, it seems work well till now. :+1:
