### ISSUE TITLE
What's the difference between base_map,routing_map and sim_map?

### ISSUE THREAD

**Issue by hyx007** [ApolloAuto/apollo#3038]
I think that the base_map,routing_map and sim_map are different layers of the map, what kind of objects belongs to base_map or others? I glance over this three files but does not find the rules to differentiate them, could you give a brief introduction? Thanks a lot!

**Comment by startcode** [comment]
I added some document to explain the different map formats in this pull-request.
https://github.com/ApolloAuto/apollo/pull/3074/files
