### ISSUE TITLE
different mode for share memory and socket

### ISSUE THREAD

**Issue by nmhx** [ApolloAuto/apollo#306]
I select different mode for share memory and socket by edit $ROS_ETC_DIR/transort_mode.yaml inside of docker. I select the socket but the config is no effect.

**Comment by bjtulynn** [comment]
Please confirm whether communication type for the topic is intraprocess, you can get the information by executing the command "rostopic info topic_name". According to our design, intraprocess topic will not communicate based shm mode.

**Comment by nmhx** [comment]
$ rostopic info chatter
Type: pb_msgs/perf
Publishers: 
 * /talker (http://in_dev_docker:44125/)
Subscribers: 
 * /listener (http://in_dev_docker:33207/)

**Comment by nmhx** [comment]
I do the test transport time about share memory and socket.but I get different result inside of docker and outside of docker.
inside of docker

data | share memory | socket
-- | -- | --
5m | 23ms | 26ms
10m | 47ms | 90ms
15m | 71ms | 1461ms
20m | 95ms | 4570ms

outside of docker

data | share memory | socket
-- | -- | --
5m | 21ms | 23ms
10m | 45ms | 46ms
15m | 69ms | 69ms
20m | 92ms | 92ms

**Comment by bjtulynn** [comment]
Would you pack the complete test program and provide for us? my email address is "bjtulynn@163.com". If convenient, please tell us the detailed test process, thank you!

**Comment by nmhx** [comment]
@bjtulynn  thanks you! I has been sent an mail

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
