### ISSUE TITLE
How to calibrate a car?

### ISSUE THREAD

**Issue by codespjw** [ApolloAuto/apollo#307]
Can anyone explain, why we need to calibrate the car and how to calibrate it?

Thanks.

**Comment by lianglia-apollo** [comment]
Please be more specific on what kind of calibration you are referring to. In general, we need to calibrate a car because every component (including those add-on devices for autonomous driving purpose) is made or positioned slightly different. For example, the GPS, lidar, camera, as well as control parameters need to be adjusted based on their ideal values according to real world conditions.

**Comment by ubercool2** [comment]
I will make this question then specific. I am looking for a camera-2-lidar calibration. The calibration tool should:
1. capture PointCloud2 from e.g. any of the velodyne sensors
1. capture rgb Image message
1. take in approximate 6DOF transform between lidar origin and camera optical frame
1. output:
    1. camera intrinsics  (plumb_bob distortion)
    1. exact 6DOF transform between lidar origin and camera optical frame


I am also looking for a lidar-2-lidar calibration for sensors that overlap at least 30% of points. The calibration tool should:
1. capture PointCloud2 from at least 2 e.g. velodyne sensors
1. take in approximate 6DOF transform between 2 lidar origins
1. output:
    1. exact 6DOF transform between lidar origins

Do you have any such tools and if yes is there any documentation on how to use them?

**Comment by jinghaomiao** [comment]
Please follow the document: https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md

**Comment by ubercool2** [comment]
@jinghaomiao does above described process also work for VLP16 or VLP16HighRes?

**Comment by jinghaomiao** [comment]
@weidezhang can you please help?

**Comment by natashadsouza** [comment]
@ubercool2 there has been additional documentation written on the VLP16 series. Please refer to the Specs section of our documentation. 
Please let me know if you still need support on your request. Feel free to re-open the issue.
