### ISSUE TITLE
HELP:  fail to bash apollo.sh build!!

### ISSUE THREAD

**Issue by zhangxiao696** [ApolloAuto/apollo#3072]
when I run 'bash apollo.sh build', but it goes as follows:

> apollo@apollo:~/apollo/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
ERROR: /home/apollo/.cache/bazel/_bazel_apollo/d6837147e2620415556c758a4a31a788/external/com_google_protobuf/BUILD:441:1: Traceback (most recent call last):
	File "/home/apollo/.cache/bazel/_bazel_apollo/d6837147e2620415556c758a4a31a788/external/com_google_protobuf/BUILD", line 441
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "/home/apollo/.cache/bazel/_bazel_apollo/d6837147e2620415556c758a4a31a788/external/com_google_protobuf/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /home/apollo/.cache/bazel/_bazel_apollo/d6837147e2620415556c758a4a31a788/external/com_google_protobuf/BUILD:742:1: Traceback (most recent call last):
	File "/home/apollo/.cache/bazel/_bazel_apollo/d6837147e2620415556c758a4a31a788/external/com_google_protobuf/BUILD", line 742
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "/home/apollo/.cache/bazel/_bazel_apollo/d6837147e2620415556c758a4a31a788/external/com_google_protobuf/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: Evaluation of query "//..." failed due to BUILD file errors
============================
[ERROR] Build failed!
[INFO] Took 398 seconds
============================
### 
Any help?
thanks!

**Comment by startcode** [comment]
Your bazel version is too high. The version Apollo used is 0.5.3
But you still can make the following change to make it pass
https://github.com/google/protobuf/commit/4fc93044a5de018527ec027dbee6a882012e0d9d

I noticed that you are not building insider the provided dev docker, and  in this case,  the build process will be very challenging task.

**Comment by zhangxiao696** [comment]
@startcode yeah！so it is. 

another question: why 'bazel query //... && ./apollo.sh build' so slow, and always interrupted. I don't success for once.

thank you for your answer!

**Comment by startcode** [comment]
Can you post the detailed error message?

Unfortunately, I cannot provide further support if you are not building inside the provided dev docker.

**Comment by zhangxiao696** [comment]
@startcode 

now, it is this:

> root@in_dev_docker:/apollo# ./apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/perception/lib/config_manager/BUILD:5:1: no such package '@undistort//': Expected directory at /usr/local/apollo/undistort but it does not exist. and referenced by '//modules/perception/lib/config_manager:config_manager'
ERROR: Analysis of target '//modules/perception/lib/config_manager:config_manager' failed; build aborted
INFO: Elapsed time: 3.280s
FAILED: Build did NOT complete successfully (4 packages loaded)
    currently loading: @bazel_tools//tools/zip
============================
[ERROR] Build failed!
[INFO] Took 4 seconds
============================

**Comment by startcode** [comment]
This issue happened yesterday, but we fixed it now. Can you restart docker by
```
bash docker/scripts/dev_start.sh
```

**Comment by zhangxiao696** [comment]
@startcode 

no, it doesn't work, and the error info is same as above.

**Comment by ycool** [comment]
@zhangxiao696  
outside docker, run `docker ps` 
What's the dev docker version in your env?

Sorry for this trouble.

**Comment by zhangxiao696** [comment]
@ycool @startcode 
i have used the latest version, it's 0228.
another important question want to ask you: where can i find  *.bin file of novatel or gps? 

Thanks for your answer!
