### ISSUE TITLE
Could not set Resolution of the Screen after install apollo-kernel

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#3089]
I follow the step and have success install apollo-kernel ，using
```
uname -r
```
I would get 
```
4.4.32-apollo-2-RT
```
The resolution would be a fix at 800*640
the way I installed nvidia driver is by 
```
bash apollo-kernel/linux/install-nvidia.sh
```
which extract some libs of driver version 375.39
If I use
```
xrandr -q
```
I would get
```
xrandr: Failded to get size of gamma of for output default
...
```
I have try to change the default starting resolution by  modify the grub cfg.and update the grub cfg,But is still not work. How Can I solve this problem.

**Comment by quning78** [comment]
What's the configuration of your workstation, e.g. CPU, GPU?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication for a while.
