### ISSUE TITLE
error with sudo ./apollo.sh build_no_perception dbg

### ISSUE THREAD

**Issue by askari01** [ApolloAuto/apollo#3096]
no such package '@google_styleguide//': Error cloning repository: https://github.com/google/styleguide.git: cannot open git-upload-pack caused by https://github.com/google/styleguide.git: cannot open git-upload-pack caused by java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by the trustAnchors parameter must be non-empty and referenced by '//modules/prediction/common:road_graph_cpplint'

i have updated the certificates but still no luck

**Comment by natashadsouza** [comment]
Sorry that we have not responded to your request, are you still seeing the issue?
