### ISSUE TITLE
catkin_make not working

### ISSUE THREAD

**Issue by pooluut** [ApolloAuto/apollo#311]
I run the dev docker image First.
I built a catkin workspace in the image, but is goes as follows:

```
yc@in_dev_docker:/apollo/catkin_ws$ catkin_make
Base path: /apollo/catkin_ws
Source space: /apollo/catkin_ws/src
Build space: /apollo/catkin_ws/build
Devel space: /apollo/catkin_ws/devel
Install space: /apollo/catkin_ws/install
####
#### Running command: "cmake /apollo/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/apollo/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/apollo/catkin_ws/install -G Unix Makefiles" in "/apollo/catkin_ws/build"
####
CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /apollo/catkin_ws/src): Traceback (most recent call last):

    File "/usr/local/bin/catkin_find_pkg", line 9, in <module>
      load_entry_point('catkin-pkg==0.3.5', 'console_scripts', 'catkin_find_pkg')()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
      return ep.load()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
      entry = __import__(self.module_name, globals(),globals(), ['__name__'])

  ImportError: No module named cli.find_pkg


-- Configuring incomplete, errors occurred!
See also "/apollo/catkin_ws/build/CMakeFiles/CMakeOutput.log".
Invoking "cmake" failed
```

Any help?

**Comment by westeast** [comment]
@pooluut have you solve the problem? I have the same problem

**Comment by startcode** [comment]
Are you trying to build Apollo?, if so, you can run the following command inside dev docker.
```
bash apollo.sh build
```

**Comment by pooluut** [comment]
@startcode 
Thanks for your reply.
I'm not building apollo.
I'm trying to start a catkin_workspace in the docker.

**Comment by pooluut** [comment]
@westeast 
No, still problem in the lastest release.

**Comment by pooluut** [comment]
@startcode 
please take the following step to recurrent the problem:
1. bash docker/scripts/dev_into.sh
2. mkdir -p catkin_ws/src
3. cd catkin_ws
4. catkin_make

**Comment by startcode** [comment]
@pooluut I have forwarded your question to ROS team.

**Comment by startcode** [comment]
@pooluut @westeast I have forwarded your question to ROS team. 

Not sure about your purpose of using catkin_make here. The official build method is using bazel BUILD file, even when you want to create a new module under apollo/modules

**Comment by sukibean163** [comment]
i have the same problem

**Comment by seanM29** [comment]
does this problem solve?

**Comment by lxbeyond** [comment]
the same problem，so  how to build a project in the apollo docker ?  is there any demo ?

**Comment by lxbeyond** [comment]
@sukibean163  @seanM29  I have build the project in apollo docker, do as follows:
bazel query //...
bash apollo.sh build
mkdir -p mytest/src
cd mytest/src
...add your project
cd ..
catkin_make_isolated 
  i have test my talker/listener demo, it works ,and I help this will help your guys.

**Comment by sukibean163** [comment]
@lxbeyond thanks, it works
