### ISSUE TITLE
failed to register layer

### ISSUE THREAD

**Issue by lz199144** [ApolloAuto/apollo#3113]
`[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20180130_1338 ...
dev-x86_64-20180130_1338: Pulling from apolloauto/apollo
cb56c90f0b30: Already exists 
0acc551e5716: Pulling fs layer 
8956dcd35143: Pulling fs layer 
908242721214: Pulling fs layer 
b44ff14dd3bb: Waiting 
4e68297aef7a: Waiting 
f2e60cbbc46b: Waiting 
4def827f3388: Waiting 
d7024597d4d3: Waiting 
886213b9c3ba: Waiting 
b1ac6ddbc6b7: Waiting 
6d28c630a322: Waiting 
d505646e6e5b: Waiting 
7968bcb3836a: Waiting 
8f0fa8c34222: Waiting 
bb8e16126598: Waiting 
f3b7c5d69675: Waiting 
1aedc3a0410b: Waiting 
33c030e7093a: Pulling fs layer 
da48ec85ed49: Waiting 
24852ac95ef0: Waiting 
fe4e65935e53: Waiting 
4779c4c9cb2e: Waiting 
27f6eba23a1a: Pulling fs layer 
15ab83019eb2: Waiting 
199e339073f8: Waiting 
3ae09dace98d: Waiting 
d09a647016dd: Waiting 
a7cb11a41e97: Waiting 
3e7686bdef0b: Waiting 
33c030e7093a: Waiting 
9b76be8176e0: Waiting 
74c48b5e54a2: Pulling fs layer 
200abc1adefd: Waiting 
ce47e44da8ce: Pulling fs layer 
8e863c5dfee2: Waiting 
85b9d775f6a6: Waiting 
618a1ac568c6: Waiting 
efc4bc9b4119: Waiting 
4e46d20fcf03: Waiting 
2b448e40506a: Waiting 
d12c8cf5699d: Waiting 
f2ba7ad4cfc7: Waiting 
351ecb254b60: Waiting 
dd1b1bafa413: Waiting 
8a5e2bea418d: Waiting 
7e610bf57646: Waiting 
32a374005d6c: Waiting 
1307670d704c: Waiting 
e43cb256c38c: Waiting 
353dcb25c39c: Waiting 
52e15f6717a2: Waiting 
a1d13a7f5398: Waiting 
1208b862d4c9: Waiting 
21f3dfc7fc87: Waiting 
85ae4b0dd353: Waiting 
042b5ae882da: Pulling fs layer 
707d68e96343: Waiting 
268269a5caca: Pulling fs layer 
45dfbd87c718: Waiting 
94f5779d4af0: Pulling fs layer 
82ccbf80d7fa: Pulling fs layer 
86315e78db66: Pulling fs layer 
06bc6911f9d4: Pulling fs layer 
26637a5d7bcf: Pulling fs layer 
2b8610ad644b: Waiting 
e07c96625704: Pulling fs layer 
8c7b2e11d4bd: Waiting 
e19a886efafb: Pulling fs layer 
76a96bcddfb9: Waiting 
eca8c00b150c: Waiting 
cebb627b586b: Waiting 
353dcb25c39c: Download complete 
bf89e5c82131: Download complete 
08868fe92128: Download complete 
7475105e49a7: Download complete 
b648e96d3179: Download complete 
5c5c05b88a7a: Download complete 
9b5af117a430: Download complete 
b3fdca3369ce: Download complete 
0bca68339510: Download complete 
94032661a096: Download complete 
700cbca3e5d6: Download complete 
d1e5db4cac4a: Download complete 
f0592134e176: Download complete 
7a19213b0cd2: Download complete 
d1ac977ce7a2: Download complete 
892c4672348b: Download complete 
d915e8a8d8cb: Download complete 
4d233f0f8483: Download complete 
6e03bccc2355: Download complete 
ec8486d7401c: Download complete 
759dfabf9e8d: Download complete 
8b84e79eccd5: Download complete 
0bbe2e963266: Download complete 
failed to register layer: open /var/lib/docker/aufs/layers/327de9af8ef420621704b0c0b0d3c2b76620e351c72f4e7fad5a71f4dc89f79b: no such file or directory
[ERROR] Failed to pull docker image`

Second times, what wrong?

**Comment by wlbksy** [comment]
```shell
tee: /proc/sys/kernel/core_pattern: Read-only file system
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
ff3a5c916c92: Extracting [==================================================>]  2.066MB/2.066MB
9d7b1995ab1d: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted
Unable to find image 'apolloauto/apollo:map_volume-sunnyvale_big_loop-latest' locally
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
ff3a5c916c92: Extracting [==================================================>]  2.066MB/2.066MB
9d7b1995ab1d: Download complete
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted.
See 'docker run --help'.
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
7ee37f181318: Extracting [==================================================>]  67.11MB/67.11MB
df5ffabe5e97: Download complete
ae2040ed51a1: Download complete
3ce7010d244b: Download complete
2538b201d2a6: Download complete
de601066203a: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted
Unable to find image 'apolloauto/apollo:map_volume-sunnyvale_loop-latest' locally
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
7ee37f181318: Extracting [==================================================>]  67.11MB/67.11MB
df5ffabe5e97: Download complete
ae2040ed51a1: Download complete
3ce7010d244b: Download complete
2538b201d2a6: Download complete
de601066203a: Download complete
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted.
See 'docker run --help'.
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20180320_1118 ...
dev-x86_64-20180320_1118: Pulling from apolloauto/apollo
286b175c283f: Extracting [==================================================>]  2.809GB/2.809GB
01ff24a32906: Download complete
a1a601a05071: Download complete
baa11bb80080: Download complete
481b7b6a0535: Download complete
39bb3ff41a5b: Download complete
133c02592fd3: Download complete
d0dd998b15f8: Download complete
812877fefe39: Download complete
b4d443b5ade3: Download complete
cd27e0317998: Download complete
87f0ec12eef9: Download complete
fe5a872a7f1b: Download complete
922a475dfe27: Download complete
8057ed981ae1: Download complete
133cdb28630d: Download complete
02b265bf90b4: Download complete
940f1805e4f0: Download complete
9d46c6ce503b: Download complete
ee63b043510d: Download complete
b75f1cff3401: Download complete
420883ba84f2: Download complete
8afecd8a5b64: Download complete
f6581db08701: Download complete
151610eb1e1f: Download complete
2cd3bb011f3d: Download complete
bf5c8ac23d3d: Download complete
d14f758b1e97: Download complete
82e68e5a0f55: Download complete
21759bbf577b: Download complete
7fab12d9471e: Download complete
b1a72f26c56a: Download complete
8d03371a8ecc: Download complete
ac1e2b360f10: Download complete
3bd498af354b: Download complete
864311fb9c50: Download complete
ab0ee1921042: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted
[ERROR] Failed to pull docker image.
```

**Comment by natashadsouza** [comment]
@lz199144 @wlbksy could you tell us about the problem a little more and give us your machine configuration to help troubleshoot your request.

**Comment by natashadsouza** [comment]
Closing this issue as there has no responses. Feel free to reopen if the issue persists.
