### ISSUE TITLE
elo compile error

### ISSUE THREAD

**Issue by leadorzf** [ApolloAuto/apollo#3127]
单独编译elo模块，出现这个错误，我的系统是16.04，请问是什么原因呢
[ 50%] Building CXX object CMakeFiles/localization_test.dir/localization_test.cc.o
[100%] Linking CXX executable localization_test
../lib/libcamera_localization.so: error adding symbols: File in wrong format

**Comment by htabani** [comment]
I have the same problem, The error: 

[ 50%] Building CXX object CMakeFiles/localization_test.dir/localization_test.cc.o
[100%] Linking CXX executable localization_test
../lib/libcamera_localization.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/localization_test.dir/build.make:141: recipe for target 'localization_test' failed
make[2]: *** [localization_test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/localization_test.dir/all' failed
make[1]: *** [CMakeFiles/localization_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by maziqiqi** [comment]
你好，这个localization_test 是要自己写的算法吗？

**Comment by leadorzf** [comment]
localization_test 是百度提供的，我是想先运行跑起来看看

在 2018-03-09 14:17:05，"maziqiqi" <notifications@github.com> 写道：


你好，这个localization_test 是要自己写的算法吗？

**Comment by maziqiqi** [comment]
请问安装成功了吗？我也想安装，不过很多地方不明白。

**Comment by leadorzf** [comment]
我换了Ubuntu 14.04 和 indigo的环境，但是还是同样的错误；不太明白arrach64平台具体是什么要求

在 2018-03-12 11:17:10，"maziqiqi" <notifications@github.com> 写道：


请问安装成功了吗？我也想安装，不过很多地方不明白。

**Comment by natashadsouza** [comment]
Please refer to the latest documentation to resolve the issue.
Closing this issue as there has been no communication in a while. Please feel free to open it if you have additional questions.
