### ISSUE TITLE
关于apollo工程中的ros问题

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#315]
apollo工程中，docker环境下的ros是否已经包含了apollo-platform？如果包含了，为啥没有在third_party目录下看到ros_x86_64目录，如何验证是否包含了？

**Comment by quning78** [comment]
please take a look at WORKSPACE file below. ROS release has been included in the build.

https://github.com/ApolloAuto/apollo/blob/master/WORKSPACE.in

Also, for release docker, it's part of the environment instead of the sub directory of apollo.

**Comment by ahuer2435** [comment]
嗯，如何验证，就是有没有测试case，看下在包含apollo-platform环境和原生的测试对比下？

**Comment by quning78** [comment]
Apollo ROS is under /apollo/ros with release docker. You can test the apollo ros vs official ros using your own benchmarks.

**Comment by wyqhnr** [comment]
怎么在docker内写一个使用apollo ros库的程序，然后用bazel 编译，给个简单的例子，非常感谢

**Comment by wyqhnr** [comment]
编译完apollo之后，ROS 环境变量都指向.cache 文件内部，如下所示
ROS_ROOT=/home/ubuntu/.cache/bazel/_bazel_ubuntu/540135163923dd7d5820f3ee4b306b32/external/ros/share/ros
ROS_PACKAGE_PATH=/home/ubuntu/.cache/bazel/_bazel_ubuntu/540135163923dd7d5820f3ee4b306b32/external/ros/share:/home/ubuntu/.cache/bazel/_bazel_ubuntu/540135163923dd7d5820f3ee4b306b32/external/ros/stacks:/apollo/bazel-apollo/external/ros/share:/apollo/bazel-apollo/external/ros/stacks

那为什么还要下载apollo ros，然后拷贝到/apollo/third_party/ros_x86_64/这个目录下呢

**Comment by quning78** [comment]
目前应该已经不需要下载到ros_x86_64了，你是看到那个 manual 还有提及这个吗？

**Comment by ahuer2435** [comment]
https://github.com/ApolloAuto/apollo-platform/blob/master/README.md  @quning78  这个链接中的“How to Install” 似乎有提到

**Comment by quning78** [comment]
这里可能写的是不太清楚，目前 Apollo 自己的 build 过程是可以自动下载 platform 也就是 ros 的 release
package，

但是如果需要单独使用 ros release package 的，可以自行下载，然后 source 相关的script，但是具体位置其实不是很相关了。

Best wishes,
-- 
Ning Qu

**Comment by zezhou** [comment]
One example for using bazel to compile module (in docker):

# lauch dev environment first
./docker/scripts/dev_start.sh
./docker/scripts/dev_into.sh

# compile from source code to bin file
bazel build //module/prediction:prediction

# compile lib
bazel build //modules/prediction:prediction_lib

Wish it helps.

**Comment by lxbeyond** [comment]
请问找到了在apollo docker中使用ros的demo了吗？

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
