### ISSUE TITLE
apollo.sh build_prof error with -lprofiler

### ISSUE THREAD

**Issue by ytzhao** [ApolloAuto/apollo#3208]
Hi every, I'm trying to build apollo with argument `build_prof`

```bash
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1204 targets (12 packages loaded).
INFO: Found 1204 targets...
ERROR: /apollo/modules/calibration/lidar_ex_checker/common/BUILD:5:1: Linking of rule '//modules/calibration/lidar_ex_checker/common:lidar_ex_checker_common' failed (Exit 1)
/usr/bin/ld: cannot find -lprofiler
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 36.152s, Critical Path: 8.27s
FAILED: Build did NOT complete successfully
============================
[ERROR] Build failed!
[INFO] Took 52 seconds
```

Thank you guys.

**Comment by startcode** [comment]
Can you try install it?
`sudo apt-get install google-perftools`
Check what library is installed:
`ldconfig -p | grep profiler`
if `libprofiler.so` is not there, but `libprofiler.so.x` exist, create a softlink:
`sudo ln -rs /path/to/libprofiler.so.x /path/to/libprofiler.so

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. Please feel free to open it if you have additional questions.
