### ISSUE TITLE
What is the Pre-stored location feature？ 

### ISSUE THREAD

**Issue by maziqiqi** [ApolloAuto/apollo#3276]
**As shown in the flow chart, what is the pre-stored location feature? Where can find it in the HD map? And how can we obtain it when we produce HD map by ourselves?**
![36629271-d9750fc4-19a7-11e8-9260-2675a6abdfde](https://user-images.githubusercontent.com/36752345/37135082-b57ae070-22ef-11e8-8a46-846c1d038530.jpg)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
