### ISSUE TITLE
apollo1.0中 planning_node.cc文件 问题

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#3310]
请教apollo1.0中planning_node.cc文件第88行：
 bool res_planning = planning_.Plan(vehicle_state, is_on_auto_mode, execution_start_time, planning_trajectory);
中的planning_是在哪里设置的？

**Comment by lianglia-apollo** [comment]
planning_ is a private variable defined in planning_node.h. It is instantiated when a planning_node instance is made.

**Comment by lianglia-apollo** [comment]
@ahuer2435 Sorry for the late reply. Please feel free to ping us if you don't get an answer in a few days.

**Comment by ahuer2435** [comment]
@lianglia-apollo  多谢，了解了，重新梳理下流程，大致如下：
main()函数：
planning_node.Run()--->void PlanningNode::RunOnce()--->planning_.Plan(vehicle_state, is_on_auto_mode,execution_start_time, &planning_trajectory)，说明这时planning_应该包含了的RTK planner。
planning_node.h文件中：
PlanningNode类包含了一个planning_，planning_是类Planning的一个实例。 
类Planning包含了std::unique_ptr<Planner> ptr_planner_，ptr_planner_是一个指向Planner类的指针，在Planning::Planning() 构造函数中，ptr_planner_指向一个rtk planner。所以此时planning_已与RTK planner建立了联系。

**Comment by ahuer2435** [comment]
已解决，关闭issue。
