### ISSUE TITLE
不使用docker环境搭建的apollo，如何发布不依赖docker的版本

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#334]
您好，
   我尝试搭建不依赖docker的apollo环境，目前已经ok；现在遇到一个问题，就是如何发布不依赖docker的版本？  我有看到apollo_1_0_quick_start_developer.md下的release部分，其中还是以docker image形式发布的。

**Comment by quning78** [comment]
Please reference the dockerfile under https://github.com/ApolloAuto/apollo/tree/master/docker.

You will be able to tell how we setup the docker environment. However, we still suggest using our release/dev docker image to save everyone's time.

**Comment by quning78** [comment]
You need to tell how to release from the apollo.sh. 

However, we still strongly suggest using our release/dev docker image to save everyone's time.

**Comment by ahuer2435** [comment]
嗯，应为考虑工控机平台资源可能不是很充裕，所以打算不安装docker以节省资源

**Comment by xiaoxq** [comment]
我觉得有两个选择：
1. 理解我们制作release image的过程（./apollo_docker.sh gen_docker），在本机上完成。
2. 借助boot2docker（http://boot2docker.io/）等工具来节省工控机操作系统的开销。

这两个其实都有一定的技术成本，可能升级硬件资源才是最简单、最廉价的解决办法。当然，如果你们探索出了解决方案，非常欢迎反馈给我们！

**Comment by ahuer2435** [comment]
能否利用ros 本身的发布版本方法：catkin_make install 的方式实现？

**Comment by xiaoxq** [comment]
脱离docker环境之后，多个环节都可能会有问题，比如依赖库的安装路径，各个部分的版本对齐，甚至文件的读写权限配置。
虽然肯定是可以实现脱离的，但我们仍然强烈推荐使用docker。而且据我所知docker不同于虚拟机，它所带来的性能损耗是十分有限的，参考：
https://www.zhihu.com/question/29027322
https://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container

**Comment by ahuer2435** [comment]
嗯，好的，了解了，我们也是想做一个工作量的评估，谢谢了。

**Comment by mayulin22** [comment]
> 您好， 我尝试搭建不依赖docker的apollo环境，目前已经ok；现在遇到一个问题，就是如何发布不依赖docker的版本？ 我有看到apollo_1_0_quick_start_developer.md下的release部分，其中还是以docker image形式发布的。

请问是如何实现的呢
