### ISSUE TITLE
Failed to start HMI

### ISSUE THREAD

**Issue by qianyichen1987** [ApolloAuto/apollo#3343]
Apollo already build success, the log 
andy@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1410 targets (12 packages loaded).
INFO: Found 1410 targets...
Slow read: a 138139927-byte read from /apollo/modules/dreamview/frontend/dist/assets/map_data/sunnyvale_big_loop/background.png took 5495ms.
Slow read: a 250471543-byte read from /apollo/modules/map/data/sunnyvale_big_loop/base_map.xml took 5083ms.
INFO: Elapsed time: 667.802s, Critical Path: 42.53s
INFO: Build completed successfully, 1423 total actions
============================
[ OK ] Build passed!
[INFO] Took 690 seconds
============================
andy@in_dev_docker:/apollo$ bash scripts/bootstrap.sh
Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888

But when we try to access the dreamview through firefox browser, fail to access, please give me a hint to fix this, thanks.

**Comment by qianyichen1987** [comment]
dreamview and bootstrap all could run sucess, but the localhost:8888 still not access.

andy@in_dev_docker:/apollo$ bash scripts/dreamview.sh 
Launched module monitor.
Launched module dreamview.
andy@in_dev_docker:/apollo$ ps aux | grep dream
andy     14651  0.0  0.0   8888   748 pts/29   S+   20:57   0:00 grep --color=auto dream
andy@in_dev_docker:/apollo$ bash scripts/bootstrap.sh 
Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888
andy@in_dev_docker:/apollo$ ifconfig

**Comment by davidhopper2003** [comment]
You may be using a proxy, which prevents you from accessing the local server.

**Comment by qianyichen1987** [comment]
i didn't set thw proxy in my laptop, also what's the difference between dev docker and release docker? why does the dreamvie process doesn't exist when execute bootstrap? 

thanks.

**Comment by davidhopper2003** [comment]
There are two more possibilities. First, you did not log off the current user after installing the docker. Second, you used the "root" privilege when installing the docker, and entered the docker with a normal user, causing permission problems. The difference between the "dev" and "release" editions is that the former is used for the development, and the latter is used for the release. At the present, Apollo does not maintain the release image.

**Comment by qianyichen1987** [comment]
i install the docker following the docs with on root, after i log out the system and use dokcer ps to verify,  after build the apollo, i run the dev docker start and info shell, then the issue happens, it's wird, and no relative log occur in data diretory, any more suggestion for this?

**Comment by qianyichen1987** [comment]
is there any way i remove the docker and all the relative apollo? and restart again?

**Comment by qianyichen1987** [comment]
does it need to install extra tomcat ?

**Comment by apollo-evangelist** [comment]
fixed. 
just try again.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be fixed. If this issue persists, please refer to [How to debug the Dreamview start problem](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md) or go through the Dreamview FAQs. Thanks!
