### ISSUE TITLE
how to setup multiple apollo dockers evn

### ISSUE THREAD

**Issue by adderllyer** [ApolloAuto/apollo#3344]
is there are some documents for steps to setup multiple apollo dockers and run appilcation on them?

Thanks
Kidd

**Comment by wanglei828** [comment]
I think you can refer to docker user documents.

**Comment by adderllyer** [comment]
i am a newbee for docker, is there some instruction for apollo how to work on two or more apollo docker?
thanks

**Comment by slivingston** [comment]
@adderllyer did you try to read and work through https://docs.docker.com/get-started/ ?

**Comment by slivingston** [comment]
Then, enter the commands to create a Docker container described in [the root Apollo README](https://github.com/ApolloAuto/apollo/tree/83ce01433fd84dec6e619322b9b9c6ad8e5f1713#the-docker-environment-can-be-set-by-the-commands-below). If some error occurs, then show us here.

**Comment by adderllyer** [comment]
maybe i didn't describe my question clear,

**Comment by xiaoxq** [comment]
To my knowledge, it's hard to do so, if not impossible. Because the container uses some fixed resources such as host port, log file, etc, which will cause conflict.

**Comment by slivingston** [comment]
no, you can remap ports.

@adderllyer I will try to do it and report on my findings.

**Comment by ubercool2** [comment]
How does apollo container share resources such as network and device files (`/dev/*) with the host operating system?  Do you expose them or not?

**Comment by natashadsouza** [comment]
Currently closing this issue as there has been no communication in a while. Feel free to open it should you have additional questions on how to run multiple Apollo docker instances.
