### ISSUE TITLE
traffic_light模块问题

### ISSUE THREAD

**Issue by lhh0916** [ApolloAuto/apollo#3377]
大家好，最近我在docker内调试traffic_light模块，采用百度APOLLO官网提供的数据（下载的是一个tar的压缩包约3.2G）去跑demo，在调试中std::cout lights的数据，发现lights的size从头到尾一直都是0，没数据，请问这是怎么回事？感谢大家的帮忙。 
具体数据有：2018-01-03-19-37-16.bag，long_camera_extrinsics.yaml，long_camera_intrinsics.yaml，short_camera_extrinsics.yaml，short_camera_intrinsics.yaml
bag包的topic：
path:        2018-01-03-19-37-16.bag
version:     2.0
duration:    1:00s (60s)
start:       Jan 03 2018 19:37:30.31 (1514979450.31)
end:         Jan 03 2018 19:38:31.21 (1514979511.21)
size:        5.4 GB
messages:    49717
compression: none [1528/1528 chunks]
types:       pb_msgs/Chassis              [d6a21658031a6a4615858d76f8b5178e]
             pb_msgs/ContiRadar           [cc92608f43dabc2a96119eaca0c19535]
             pb_msgs/EpochObservation     [6d088c32c2d00b8a760974f0c580dfb7]
             pb_msgs/GnssBestPose         [c4465e2257bee53c91729e53c69bf7c5]
             pb_msgs/GnssEphemeris        [aa53419c1014e11a3b4604e3c54daf7b]
             pb_msgs/GnssStatus           [6ab9bfa7e56e2724f6d30280b731fef2]
             pb_msgs/Gps                  [8fad5985ce947d3b6854fd093a59c429]
             pb_msgs/Imu                  [bdef0ba51869607ed95736d41e80c1f5]
             pb_msgs/InsStat              [36306149a641468d85afa4cf44de7141]
             pb_msgs/LocalizationEstimate [503c8e75900db180bc61534806a37cfb]
             sensor_msgs/Image            [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/PointCloud2      [1158d486dd51d683ce2f1be655c3c181]
             tf2_msgs/TFMessage           [94810edda583a504dfda3829e70d7eec]
topics:      /apollo/canbus/chassis                               5851 msgs    : pb_msgs/Chassis             
             /apollo/localization/pose                            5856 msgs    : pb_msgs/LocalizationEstimate
             /apollo/sensor/camera/traffic/image_long              471 msgs    : sensor_msgs/Image           
             /apollo/sensor/camera/traffic/image_short             469 msgs    : sensor_msgs/Image           
             /apollo/sensor/conti_radar                            789 msgs    : pb_msgs/ContiRadar          
             /apollo/sensor/gnss/best_pose                          59 msgs    : pb_msgs/GnssBestPose        
             /apollo/sensor/gnss/corrected_imu                    5838 msgs    : pb_msgs/Imu                 
             /apollo/sensor/gnss/gnss_status                        59 msgs    : pb_msgs/GnssStatus          
             /apollo/sensor/gnss/imu                             11630 msgs    : pb_msgs/Imu                 
             /apollo/sensor/gnss/ins_stat                          118 msgs    : pb_msgs/InsStat             
             /apollo/sensor/gnss/odometry                         5848 msgs    : pb_msgs/Gps                 
             /apollo/sensor/gnss/rtk_eph                            49 msgs    : pb_msgs/GnssEphemeris       
             /apollo/sensor/gnss/rtk_obs                           352 msgs    : pb_msgs/EpochObservation    
             /apollo/sensor/velodyne64/compensator/PointCloud2     587 msgs    : sensor_msgs/PointCloud2     
             /tf                                                 11740 msgs    : tf2_msgs/TFMessage          
             /tf_static                                              1 msg     : tf2_msgs/TFMessage

**Comment by lhh0916** [comment]
大家有调通traffic_light模块的吗？最终能得到检测结果和分类结果的相关输出吗?求指导，非常感谢！

**Comment by ghdawn** [comment]
能确认你用的地图版本，和bag里跑的地方是匹配的吗？ bag里的车在哪里跑，就需要配哪里的地图 ，否则是查不到红绿灯的：）

**Comment by ghdawn** [comment]
刚发现你下的那个包里,只有开头3s有红绿灯,后面就是没有.
这里有人问了类似的问题
https://github.com/ApolloAuto/apollo/issues/4170

**Comment by natashadsouza** [comment]
Closing this issue as there has no communication in a while. Feel free to open it if the issue persists.
Thank you @ghdawn for referencing the duplicate issue!
