### ISSUE TITLE
GOTURN as an object tracker

### ISSUE THREAD

**Issue by htabani** [ApolloAuto/apollo#3412]
As Apollo 2.0 released in late 2017, I assume you consider state-of-the-art algorithms for different modules. 

Have you considered GOTURN as an object tracker (which is based on DNNs)? How do you compare your current algorithms vs that in terms of accuracy?

and regarding the Object Detection, can we integrate YOLO in Apollo? 

Thanks.

**Comment by xiaoxq** [comment]
For Yolo part, yes, we are doing that.

https://github.com/ApolloAuto/apollo/tree/master/modules/perception/obstacle/camera/detector/yolo_camera_detector

**Comment by weidezhang** [comment]
we have did linear cascading tracker which combines multiple tracking features (including deep learning features). we haven't tried GOTURN yet. For yolo detector, as mentioned by xiaoxq, we are doing it for apollo 2.5. stay tuned.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while.
