### ISSUE TITLE
View velodyne pointcloud on Dreamviewer

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#3413]
I was able to view velodyne point cloud data once while playing the demo-sensor-data-2.0 bag. But I'm not able to get that option again. I think I used build_gpu which enabled that option. But I can't do it again. Any idea how to get it ?

**Comment by siyangy** [comment]
Can you elaborate on 'But I'm not able to get that option again.'? Are you on the latest code? The Dreamview frontend should have that option from the 'layer menu' tab on the left, and the build_gpu option doesn't affect that.

**Comment by ankitvora7** [comment]
I meant the enable/disable button on the layer menu! I saw and enabled that option once but I can't see it on the layer menu anymore. Let me check few more things on my end.

**Comment by ankitvora7** [comment]
@siyangy - you were right! I had the old code. Thanks :)
