### ISSUE TITLE
About End-to-End,Will you release the pre-trained model?

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#342]
Thank you guys for doing so wonderful job.I see that you provided 155GiB data to train the network.I wonder if it be possible to release a pre-trained model. I could train the network use the code provided.But the data is still limited. I want to compare the result of my training and yours. 

I have a little bit concern of the robustness of  this kind of end-to-end control model,Do you guys have any ideals about it, Does end-to-end model is the trend of the autonomous driving car.

**Comment by yanys1** [comment]
The pre-trained model temporarily not open, if there is a high requirement, we will open it. About the robustness, we are also handle it , and we will continuously update, making e2e more robust.
