### ISSUE TITLE
How to visualize the lossy map or lossless map created by msf_local_map_creator?

### ISSUE THREAD

**Issue by JinglinZhang** [ApolloAuto/apollo#3439]
I tried to visualize the lossy map by localization_online_visualizer, and met this error
```
zjl@in_dev_docker:/apollo$ bash scripts/localization_online_visualizer.sh 
Load lidar extrinsic succeed.
Resolution: 0.125
Dataset: data/map_data/pcds
Loaded the map configuration from: /apollo/modules/map/data/zgc_map/local_map/config.xml.
Load map config succeed.
E0314 20:30:58.551286   236 visualization_engine.cc:683] Open params file failed.
E0314 20:30:58.551441   236 visualization_engine.cc:140] Init other params failed.
Gtk-Message: Failed to load module "canberra-gtk-module"
[ WARN] [1521030658.565491675]: transport file: /home/tmp/ros/etc/ros/transport_mode.yaml is not map
[ WARN] [1521030658.565573869]: Parse transport_mode file failed


```
I set the `map_dir` to `/apollo/modules/map/data/zgc_map` which contains `local_map` which renamed from `lossymap`.

`--map_visual_dir=data/map_visual` in `localization.conf` caused this error, but how to create the folder and the `param.txt`?

Is there any standalone node to visualize the map?

**Comment by HaoLi-China** [comment]
@JinglinZhang ，For error in localization_online_visualizer，I think you can check the online_local_visualizer.INFO in /apollo//data/log to get more info about  the error. It seems that /apollo/data/map_visual is not be created correctly. It will be more clear if you can list the tree structure in your local_map folder and map_visual folder here.

For visualization tool for map, we haven't developed such tool so far. But we will add this tool later. Anyway，we generated all map node images in your map folder(local_map/image). You can just open the .png files to check the quality of the map. Moreover, you can write a simple code to combine all of these images together to show a completed map if you are willing to to this.

**Comment by natashadsouza** [comment]
Currently closing this issue as there has been no response in a while. Feel free to open it, if you are still facing the issue.

**Comment by weiyinxie** [comment]
hi i'm using dreamview do to some visualization staffs but facing a issue. I have created  my own lossy map via ./scripts/msf_local_map_creator.sh but couldn't find a way to load it into the dreamviewer.....Does someone has a idea?
