### ISSUE TITLE
FATAL error: "planning" module can't fetch the observation data and exit automatically. 

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#3440]
When the "planning" module is loaded in Dreamview, whether using simulated data or actually testing in a Lincoln MKZ car, it often happens that observation data can't be fetched and thus cause the module being exited (the error message is shown as follows. **In fact, my chassis state is OK**). We have to repeatedly click the "planning" option in Dreamview to make the module work normally. What's the problem on earth? Thank you.
``` log
Log file created at: 2018/03/16 13:54:14
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0316 13:54:14.908344 11469 adapter.h:237] Check failed: !observed_queue_.empty() The view of data queue is empty. No data is received yet or you forgot to call Observe():/apollo/canbus/chassis
```
The relevant code that caused the problem may be shown as follows: 
``` cpp
void Planning::RunOnce() {
  // ...
  // chassis
  const auto& chassis = AdapterManager::GetChassis()->GetLatestObserved();
  ADEBUG << "Get chassis:" << chassis.DebugString();
 // ...
}
```

**Comment by davidhopper2003** [comment]
Sometimes, the error message is shown as follows. In fact, my localization state is also OK. 
``` cpp
Log file created at: 2018/03/18 09:31:07
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0318 09:31:07.759959 23038 adapter.h:237] Check failed: !observed_queue_.empty() The view of data queue is empty. No data is received yet or you forgot to call Observe():/apollo/localization/pose
```

**Comment by wqqn** [comment]
I also meet this problem. I can see the localization message with "rostopic echo". But Apollo modules can not capture the message.

**Comment by davidhopper2003** [comment]
@wqqn Glad to see that you also met the same problem as me.

**Comment by wqqn** [comment]
I met the problem because I switched ros transport mode to socket. After I switch the ros transport mode to shared memory, the problem is gone.

**Comment by lianglia-apollo** [comment]
This seems to be an issue that not related to planning module. @Zhenni17

**Comment by natashadsouza** [comment]
@davidhopper2003 has this issue been resolved at your end?

**Comment by natashadsouza** [comment]
Thanks @davidhopper2003 I am currently closing this issue. If you have any additional questions please feel free to reopen the issue.
