### ISSUE TITLE
Issue with estop_ state in modules/control/control.cc

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#3446]
Should there be a "estop_ = false" statement added inside the else block (line 164~165) of function _Status Control::ProduceControlCommand(ControlCommand *control_command)_ in _apollo/modules/control/control.cc_? It seems that the vehicle will remain in estop state indefinitely until _Control::OnPad_ is invoked, if estop_ was set true due to some non-ok status in the last control cycle but everything works fine in the current cycle. Is this the expected semantic?

**Comment by lianglia-apollo** [comment]
I believe this is the expected behavior when we handle estop now.

**Comment by hongkedavid** [comment]
@lianglia-apollo Thanks for your reply! That means for the current design, once an estop happens, the vehicle will stop until some human intervention happens (e.g., sending a pad message with DrivingAction::RESET)?

**Comment by lianglia-apollo** [comment]
Yes, that is correct.
