### ISSUE TITLE
What's the difference between dev docker & release docker ?

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#3466]
Hi, guys.

I'm following Apollo guide steps.

And now, I wonder about there are two dockers (dev docker & release docker).

Q. What's the difference between dev & release ? (dev means develop..?)

Q. If I want to test my own algorithm on Dreamview, is it right to run dev docker ?

Below are the scripts for docker.
![image](https://user-images.githubusercontent.com/37093857/37581924-e9246ecc-2b8d-11e8-9e37-237c1203f367.png)

Thanks...

**Comment by apollo-evangelist** [comment]
A1.Dev is development environment.Dev docker need you build apollo after install docker and pull docker images, Release docker don't.

A2.yes you can change the codes, build and test  in dev docker.
