### ISSUE TITLE
error pulling image configuration

### ISSUE THREAD

**Issue by icesit** [ApolloAuto/apollo#3483]
when i run 
> bash docker/scripts/dev_start.sh

i got
> map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
> ff3a5c916c92: Pulling fs layer 
> 9d7b1995ab1d: Pulling fs layer 
> error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/80/80aca30fa08aa8877eef5d1ae11772f810927e1eb634c74c5f37e7d61a1a6196/data?Expires=1521553731&Signature=H5r8qD5qSf8aTTC1Z6j3u7SvkH5msQEK2Vp6rVFvWknJTNGrnFm-5HKirqwcq7xA8a-BzMs0khIjOtHz8MkWXKeXx9aQCjOwaboVAC4kjA7bnVDOiDKMfO7vOTBaEVICD~wbVe9ccyw6U8Nxfyc7tN0BBofj39IpRUvVNW0nQzQ_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
> Unable to find image 'apolloauto/apollo:map_volume-sunnyvale_big_loop-latest' locally

how can i solve this problem? thank you.

**Comment by apollo-evangelist** [comment]
please try 
```bash 
bash docker/scripts/dev_start.sh -C 
``` 

pull docker images from `registry.docker-cn.com` quickly

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved!
