### ISSUE TITLE
Perception Module error : "Perception process stopped"

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#3556]
Hi, guys.

I encountered a problem while running Dreamview.

I use Dreamview in SimControl Mode for some simulations.

In Console table for the below picture, "Perception process stopped" messages are continuously notified.
![image](https://user-images.githubusercontent.com/37093857/37805769-94a4edd2-2e7f-11e8-85c7-f9a298ed8de5.png)

And here is my perception log. (file in /apollo/data/log/ )

> Log file created at: 2018/03/20 17:37:03
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0320 17:37:03.037178 7016 hdmap_common.cc:177] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:03.037622 7016 hdmap_common.cc:177] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787105] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:03.037658 7016 hdmap_common.cc:177] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787116] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:03.037688 7016 hdmap_common.cc:177] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787127] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:03.037717 7016 hdmap_common.cc:177] lane[id = id: "2652_1_-1"
]. sampled_right_width_[0.787289] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:06.294057 7016 hdmap_common.cc:186] lane[id = id: "2652_1_-1"
]. sampled_right_width_[0.787301] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:06.294073 7016 hdmap_common.cc:186] lane[id = id: "2652_1_-1"
]. sampled_right_width_[0.787312] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:06.294091 7016 hdmap_common.cc:186] lane[id = id: "2652_1_-1"
]. sampled_right_width_[0.787324] is too small. It should be larger than half vehicle width[1.05].
E0320 17:37:06.294124 7016 hdmap_common.cc:186] lane[id = id: "2652_1_-1"
]. sampled_right_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].
F0320 17:37:06.646378 7016 common.cpp:151] Check failed: error == cudaSuccess (38 vs. 0) no CUDA-capable device is detected

**Q1. What's the problem with perception module?**

**Q2. When I run Dreamview, I also get fail message "Failed to create can client".
I follow the install guide about CAN Card, but why is this failure occurring?
Do I need to install a CAN Card in my PC board to solve this problem?**

Thanks!!

**Comment by weidezhang** [comment]
Check failed: error == cudaSuccess (38 vs. 0) no CUDA-capable device is detected. most likely, it's the reason ?

**Comment by CCodie** [comment]
@weidezhang Thank you for replying!
I'm using GEFORCE GTX TITAN Z as my graphic card, and I installed it's driver.
Is there anything else I need to do?

**Comment by jzhuucla** [comment]
Did you install the nVidia driver in both the host machine and the docker? And the version installed in them should be the version.

**Comment by zuomaidi52** [comment]
Should I install a Nvidia driver in docker? I guess there is a Nvidia driver in docker image.So, there must have the same version of host driver and docker driver?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication for a while. Feel free to open it should you see any further errors.
Feel free to reopen if you have additional questions.
