### ISSUE TITLE
dp_st_graph

### ISSUE THREAD

**Issue by JohnQii** [ApolloAuto/apollo#3562]
I find a little problem in [dp_st_graph.cc](https://github.com/ApolloAuto/apollo/blob/c3300d409dab44931906d8a32a874752c295fbe4/modules/planning/tasks/dp_st_speed/dp_st_graph.cc):
in line 218:  
```
const double delta_s_upper_bound =
      v0 * unit_t_ + vehicle_param_.max_acceleration() * speed_coeff;//vt + at^2
```
Is that should be $\frac{vt + at^2}{2}$?

**Comment by lianglia-apollo** [comment]
In our finite element method, we are using the assumption that the speed between each time points is constant, and speed can make an abrupt change between segments. So the estimated delta_s_upper_bound is represented as the function as in line 218. It doesn't need to be divided by 2.

**Comment by JohnQii** [comment]
Thanks a lot.
And I have another question also in  dp_st_graph.cc:
in line 228:
```
  *next_lowest_row += static_cast<int32_t>(delta_s_lower_bound / unit_s_);//init *next_lowest_row = 0
```
why not this is:
```
*next_lowest_row = point.index_s() - static_cast<int32_t>(delta_s_lower_bound / unit_s_)
```

**Comment by lianglia-apollo** [comment]
@JohnQii It seems that we made a bug. https://github.com/ApolloAuto/apollo/pull/3584
