### ISSUE TITLE
docker/scripts/Install_docker.sh

### ISSUE THREAD

**Issue by yfzhang** [ApolloAuto/apollo#3573]
By executing `Install_docker.sh`, the previously installed nvidia-docker in the test machine will be removed. I suppose this is something undesired.

**Comment by WalesPeng** [comment]
I execute `Install_docker.sh` and stacked , then failed !! why?

**Comment by xiaoxq** [comment]
The script is simply a shortcut for the official guide:
https://docs.docker.com/install/linux/docker-ce/ubuntu/

Please follow it according to your environment, and don't forget the last step:
https://docs.docker.com/install/linux/linux-postinstall/
