### ISSUE TITLE
请求提供nmea_msgs/Sentence 格式rosbag数据

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#3576]
您好，目前我们想使用原生ros，基于差分gps，实现循迹导航系统，因为现在还没有设备，能否帮忙提供一个nmea_msgs/Sentence格式的rosbag，非常感谢。

**Comment by ahuer2435** [comment]
@lianglia-apollo 可以帮忙提供下不？

**Comment by lianglia-apollo** [comment]
@ahuer2435 Sorry that we don't support nmea_msgs/Sentence rosbag at this moment.

**Comment by ahuer2435** [comment]
ok，thank you. @lianglia-apollo
