### ISSUE TITLE
what does the "heuristic_speed_data" mean in the function trajectory_cost?

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#3577]
For the dp_poly_path, which mode provide heuristic_speed_data  in the [trajectory_cost.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/tasks/dp_poly_path/trajectory_cost.cc). In line 206  `heuristic_speed_data_.EvaluateByTime(time_stamp, &speed_point)` why we can use the heuristic_speed_data_'s to get the ego_box?

**Comment by lianglia-apollo** [comment]
As we are doing path and speed optimization separately, we don't know about speed at dp_poly_path. As a result, we use heuristic_speed_data and imagine it is the speed profile our car will drive. The heuristic speed can be a speed profile from last cycle.
