### ISSUE TITLE
prediction/conf/prediction_conf.pb.txt

### ISSUE THREAD

**Issue by tingfengqi** [ApolloAuto/apollo#3578]
In [prediction_conf.pb.txt](https://github.com/ApolloAuto/apollo/files/1846890/prediction_conf.pb.txt)
 , Why not use RNN_EVALUATOR in evaluator_type?

**Comment by lianglia-apollo** [comment]
Those "hot" names sometimes don't mean best performance, especially when robustness/reliability are the first priority, as for self driving cars. RNN evaluator is still under development so that it is not set by default.

**Comment by tingfengqi** [comment]
Thanks a lot!
