### ISSUE TITLE
LOG: How to check all logs, info, debug, error logs of any module ?

### ISSUE THREAD

**Issue by srikara123** [ApolloAuto/apollo#3597]
Hi

once can module is up, the logs can be seen in  **/apollo/data/log/canbus.out**  but only error logs are being shown, how to check all logs ?
Thanks,
Srikar

**Comment by lianglia-apollo** [comment]
It follows glog. You can set -v=4 to output debug information.

**Comment by srikara123** [comment]
set at run time / Compile time ?

**Comment by lianglia-apollo** [comment]
Please set at run time.
For example:
/apollo/bazel-bin/modules/planning/planning --flagfile=modules/planning/conf/planning.conf --log_dir=/apollo/data/log --use_navigation_mode --v=4

**Comment by gengqx** [comment]
Normally，if you launch planning module，you could find log in the directory apollo/data/log. It would have planning.INFO，planning.ERROR，etc.if you want to see the DEBUG，you add one line --v=4  into file planning.conf.You canfind DEBUG in the planning.INFO.
