### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by yongyuandeyezi** [ApolloAuto/apollo#3614]
I want to separate the module of traffic light detection , and  recompile in Apollo Docker, 
I make a new project and write a CMakeList.txt, then cmake and make 
But there are two errors when excuted make.
Could anyone give me a template of CMakeList.txt

**Comment by yongyuandeyezi** [comment]
errors are as follows:
 error: 'PyramidImageOnlineDataLayer' in namespace 'caffe' does not name a type
  caffe::PyramidImageOnlineDataLayer<float> *refine_input_layer_ = nullptr;

error: 'ROIOutputSSDLayer' in namespace 'caffe' does not name a type
  caffe::ROIOutputSSDLayer<float> *refine_output_layer_ = nullptr;

My CMakeLists.txt is as follow:
cmake_minimum_required(VERSION 2.8)

 project(traffic_light_detection)

 find_package( OpenCV REQUIRED )

 add_executable( traffic_light_detection main.cpp light_detect.cpp hungarian_bigraph_matcher.cpp utils.cpp)

 include_directories(/usr/include)
 include_directories(/usr/local/cuda-8.0/include)

 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -std=c++0x")

 target_link_libraries(traffic_light_detection  
    /usr/lib/x86_64-linux-gnu/libcaffe.so
    /usr/lib/x86_64-linux-gnu/libcaffe.so.1
    /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0
    ${OpenCV_LIBS}  
    ${PATH}
    ${LD_LIBRARY_PATH}
    )

**Comment by zhxt** [comment]
Could you please check if you have "pyramid_layers.hpp" included somewhere?

**Comment by zhxt** [comment]
@lianglia-apollo yeah, I was wondering if he include "caffe/layers/pyramid_layers.hpp" in his source file.

**Comment by yongyuandeyezi** [comment]
Thank you very much. It is my fault that I forgot include ""caffe/layers/pyramid_layers.hpp" in my source file.
But I was wondering if it is necessary to include directories and libraries of  caffe cuda and opencv in my CMakeLists. 
I removed 
include_directories(/usr/include)
include_directories(/usr/local/cuda-8.0/include)
target_link_libraries(traffic_light_detection
/usr/lib/x86_64-linux-gnu/libcaffe.so
/usr/lib/x86_64-linux-gnu/libcaffe.so.1
/usr/lib/x86_64-linux-gnu/libcaffe.so.1.0
${OpenCV_LIBS}
${PATH}
${LD_LIBRARY_PATH}
)

There are no errors of missing files.

@zhxt @lianglia-apollo
