### ISSUE TITLE
bash docker/scripts/install_docker.sh，err

### ISSUE THREAD

**Issue by lishirui** [ApolloAuto/apollo#3627]
I am trying to install Apollo on my VM VirtualBox on Mac. The OS in VirtualBox is Ubuntu 14.04.3 LTS. When I was running  
$ bash  docker/scripts/install_docker.sh
I got those issues:
Err https://apt.dockerproject.org ubuntu-trusty/main amd64 packages
   gnults_handshake() failed: A TLS packet with unexpected length was received. 
w: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages gnutls_handshake() failed: A TLS packet with unexpected length was received._

**Comment by jmtao** [comment]
@lishirui we don't support installing docker via "scipts/install_docker.sh" any more. That script has been removed from code base. 
Please refer to the latest document for docker setup. 
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md

Hope the information answered your question. If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open an new issue if you have any more questions. 

Thank you for supporting Apollo!

**Comment by slivingston** [comment]
note that scripts/install_docker.sh is still in the instructions [in the root README](https://github.com/ApolloAuto/apollo/blob/8e8a4bbba0a668727d77795e391eb062d395a3d9/README.md#the-docker-environment-can-be-set-by-the-commands-below).

**Comment by xiaoxq** [comment]
Thanks! Fixed with https://github.com/ApolloAuto/apollo/pull/3653.
