### ISSUE TITLE
common module: string_util.h can not found google/protobuf/stubs/stringprintf.h

### ISSUE THREAD

**Issue by LEEluoman** [ApolloAuto/apollo#3628]
Hi, guys

I want to use some codes from the [common module](https://github.com/ApolloAuto/apollo/tree/master/modules/common), but how can I install protobuf with a "stringprintf.h" or "strutil.h" file in usr/local/include directory?

My computer system is Ubuntu 14.04, and both protobuf version 3.5.1 and 2.7.0 have been tried.

Thanks.

https://github.com/ApolloAuto/apollo/blob/9a68e20bc310b48e0e32fce0721ca9d581e718de/modules/common/util/string_util.h#L32

**Comment by lianglia-apollo** [comment]
Are you working inside docker? The dependencies should have been installed already.

**Comment by LEEluoman** [comment]
@lianglia-apollo 
Thanks for the reply. I did not build my project in docker environment, that's why I need to install the correct version of protobuf. Actually, I have tried to change the "MakeFile" generated by "./autogen.sh", but it doesn't work.

**Comment by xiaoxq** [comment]
You need to make the protobuf library visible for your bazel workspace, and make sure the header file can be found correctly.

**Comment by LEEluoman** [comment]
Hi, @xiaoxq. Many thanks.
My project is based on cmake, and except for the error mentioned, everything is normal.
From my perspective, the key to this problem is how can i got the same environment with apollo.

**Comment by jilinzhou** [comment]
Just copy missing header files over. I also noticed there are a few apollo referenced protobuf header files which are not installed by default protobuf install.

**Comment by xiaoxq** [comment]
We reference the protobuf as a bazel dependency. You should see it at like
~/.cache/bazel/_bazel_<USER>/<MD5>/external/com_google_protobuf/src/google/protobuf/stubs/stringprintf.h

But if you are not working with apollo docker, it will take some effort to figure things out.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be fixed.

**Comment by sudhanva-s** [comment]
Hi,

I am facing the same issue. I am trying to integrate HD maps to my ROS node.

##### Protobuf version 3.3.0

##### Error:
```
cc1plus: warning: /usr/lib/libprotobuf.so: not a directory [enabled by default]
<command-line>:0:15: warning: ISO C99 requires whitespace after the macro name [enabled by default]
In file included from /apollo/catkin_ws/src/my_localization/../../../modules/common/util/file.h:38:0,
                 from /apollo/modules/map/hdmap/hdmap_impl.cc:23:
/apollo/catkin_ws/src/my_localization/../../../modules/common/util/string_util.h:31:48: fatal error: google/protobuf/stubs/stringprintf.h: No such file or directory
 #include "google/protobuf/stubs/stringprintf.h"
                                                ^
compilation terminated.
```
