### ISSUE TITLE
Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected

### ISSUE THREAD

**Issue by yongyuandeyezi** [ApolloAuto/apollo#3637]
在Apollo的docker中运行编译好（cmake）的文件，出现错误Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected

运行cuda的sample（./ /usr/local/cuda-8.0/samples/1_Utilities/deviceQuery/deviceQuery）也出现以上错误

请问怎么解决，需要我在docker中重装NVIDIA驱动或者是CUDA吗？

**Comment by zuomaidi52** [comment]
那么说，最后你解决了么？

**Comment by Utipu** [comment]
遇到同样的问题，是ubuntu16，apollo3.0版本，请问有已经解决了的吗

**Comment by Utipu** [comment]
我也遇到同样的问题，buntu16，apollo3.0版本，已解决
思路：
1）在apollo3.0的docker中默认是使用ubuntu14系统，首先建议统一系统（docker里外）
2）docker中安装了CUDA和Caffe库。但是发布的dev docker映像中未安装Nvidia GPU驱动程序。解决方案：Docker中安装与主机中安装的版本完全相同的Nvidia驱动程序版本。
比如是apollo3.0 CUDA版本是8.0  要安装对应的GPU驱动版本（375）
docker里或外面都要安装GPU驱动，而其最好统一
