### ISSUE TITLE
Can not run Dreamview after build a module

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#3639]
I was able to run Dreamview with no problem.
After make some change in planning module and build using
`bazel build modules/planning:all`

Build run success with no problem, but after this, I can not access http://localhost:8888/ to run Dreamview.
I have to rebuild everything again `bash apollo.sh build`   in order to run Dreamview.

Is there anyway faster to compile? I don't want to spend almost 1 hour to build after just making a little change.

**Comment by lianglia-apollo** [comment]
bash apollo.sh build won't rebuild everything. It will only build files you have modified.

**Comment by lesun90** [comment]
I just figure it out too.
I was clean before rebuid so it take long time.
Thank you.

**Comment by lianglia-apollo** [comment]
Great!
