### ISSUE TITLE
Is there any examples beyond the demo/demo_2.0 to learn Apollo?

### ISSUE THREAD

**Issue by kwailamchan** [ApolloAuto/apollo#3660]
Is there any examples beyond the demo/demo_2.0 to learn Apollo, for example, loading the data and simulating on Dreamview? Customizing the modules? Or building a self-driving car step by step? 

I red some docs provided inside the source codes, however, it is a bit confused. Is there any tutorial?

Thanks.

**Comment by kwailamchan** [comment]
Found an article from the Apollo developer community that published today.

**Comment by abhisheknaik96** [comment]
Could you point other to that article?

**Comment by kwailamchan** [comment]
@abhisheknaik96 

It is an Chinese article that written by Apollo team.

- [Apollo“云+端”研发迭代新模式实战](https://mp.weixin.qq.com/s/027QogNXtW2NPIDVcGQGzw)

**Comment by abhisheknaik96** [comment]
Thank you so much @kwailamchan!

**Comment by Zhenni17** [comment]
Hi @kwailamchan @abhisheknaik96 , thank you for your interests in Apollo! We are actively working on new materials that ranging from technical articles to short video-tutorials to help developers like you to learn more about Apollo.

I'd love to learn more about the topics that you want to learn more about, and the format that you preferred to learn with. On my end, I will work with our team to launch some of those learning materials for everyone here.

At the meantime, we are launching a blog soon that will feature technical articles every month (http://medium.com/apollo-auto). Please subscribe!

Best,
Zhenni 
Community Manager | Apollo Platform

**Comment by kwailamchan** [comment]
Hi @Zhenni17, thank you for open sourcing Apollo for all developers that are interested in self-driving car and other autonomous systems, reading the codes and resources provided by the team, I found that the architecture of the system is good, and the community is developing and supportive.

From a developer's perspective, what I am concerning on are:

- getting started (practical): how we could build a custom self-driving car step by step using Apollo, for example, from choosing a car and the specific sensors, installing Apollo on the car, feeding the custom data, to letting it run on the road. A real dummy self-driving car is created step by step using Apollo;

- intermediate (practical + theory): how we could custom the modules and develop the new algorithms and features on Apollo, then we could apply Apollo to various of industry, application and scenarios;

- advanced (customisation): perhaps not only for the cars, it could be customised to be other autonomous systems like self-driving bicycle/ truck/..., we could create some modules or delete them, we could deploy some new algorithms, or optimise the computing platform on software or hardware level etc.

Regarding the format, materials like online articles or the courses on Udacity would be friendly, offline-event and developer community would be supportive too.

Thanks for open sourcing!

Best,
Kelly
