### ISSUE TITLE
运行perception_offline_visualizer.sh脚本无图像显示

### ISSUE THREAD

**Issue by young1024** [ApolloAuto/apollo#3662]
先假设Apollo环境都已经搭建好（自己认为应该是已经搭建好，而且Apollo代码原封不动，只是编译）。
我是如下操作：
1、运行perception_offline_visualizer.sh脚本；
bash scripts/perception_offline_visualizer.sh
2、运行数据包；
rosbag play -l docs/demo_guide/2018-01-03-19-37-16.bag
3、坐等程序显示检测结果，可是不管等多久都不出现（应该会有图像显示，同事们的都能正常显示）。

请问各位大侠、大仙、大佬们，这是为什么，该如何解决？
整个过程并未产生ERROR日志，只有INFO和WARNING日志
WARNING日志：
![2018-04-02 21 29 20](https://user-images.githubusercontent.com/25336944/38197963-4aa11a94-36bd-11e8-8c1b-d915b001a016.png)
W0402 21:10:58.402288   239 yolo_camera_detector.cc:133] YoloCameraDetector options.intrinsic is nullptr. Use default
W0402 21:11:00.431316   239 visualization_subnode.cc:168] Failed to find radar_event_id_: vis_driven_event_id:1008;camera_event_id:1008
W0402 21:11:00.431334   239 visualization_subnode.cc:176] Failed to find fusion_event_id_: vis_driven_event_id:1008;camera_event_id:1008
W0402 21:11:00.431337   239 visualization_subnode.cc:184] Failed to find cipv_event_id_: vis_driven_event_id:1008;camera_event_id:1008
W0402 21:11:00.431340   239 visualization_subnode.cc:192] Failed to find motion_event_id_: vis_driven_event_id:1008;camera_event_id:1008
W0402 21:11:00.431342   239 visualization_subnode.cc:200] Failed to find lane_event_id_: vis_driven_event_id:1008;camera_event_id:1008

INFO日志：
![2018-04-02 21 24 16](https://user-images.githubusercontent.com/25336944/38197974-599326b4-36bd-11e8-97f7-39945c027ef8.png)
最后输出日志为：
I0402 21:11:00.431360   239 dag_streaming.cc:183] DAGStreaming load 2 subnodes, 1 events.
I0402 21:11:00.431363   239 dag_streaming.cc:81] DAGStreaming Init success.
I0402 21:11:00.431607   285 dag_streaming.cc:92] DAGStreaming start to schedule...

**Comment by xinwf** [comment]
这个问题是怎么解决的啊，我现在和你是一样的情况
