### ISSUE TITLE
dp_st_graph, what is the difference of max_acceleration from vehicle_param and dp_st_speed_config?

### ISSUE THREAD

**Issue by histfuture** [ApolloAuto/apollo#3682]
In dp_st_graph, I found it is weird  in:

![image](https://user-images.githubusercontent.com/2638853/38227207-c3a63a1a-372f-11e8-8a0b-0d41369d71c1.png)

and 

![image](https://user-images.githubusercontent.com/2638853/38227221-d3d8cd9e-372f-11e8-84e4-2aa3b865f643.png)

Why read acceleration limits from two different configurations?

**Comment by lianglia-apollo** [comment]
The first one is the physical limit of a vehicle, while the second one is what we used in dp st graph as an acceleration limit. The two may or may not be identical, where the second one is usually smaller, as used in our config files.
