### ISSUE TITLE
Some Questions About Sensor Calibration

### ISSUE THREAD

**Issue by dengyuchenkit** [ApolloAuto/apollo#3684]
Hi, I am having some problems with the sensor calibration and wondering would you help? 
1. About Lidar. Is lidar-camera calibration tool specific to _HDL64_? I have a velodyne lidar, but it's of different model instead of _HDL64_. I am wondering if using the same message and topic, does the lidar-camera calibration tool still work? 

2. About Lidar. The English version of calibration manual in Apollo 2.0 says the new calibration **replace** the original ones, so is the lidar-imu online service task in Apollo 1.5 still in use? Besides, since the lidar-imu calibration tool is also very important but I assume right now Apollo only supports _HDL64_, is it?

3. About camera. Similar to question1, is the camera-camera calibration tool specific to the model in Apollo(_Leopard Imaging LI-USB30-AR023ZWDR_)?

4. About Novatel. When configuring the Novatel toolkit, how can we measure the lever arm? The manual given by Novatel indicates that `leverarmcalibrate` is not available for _IMU-IGM_, does that mean we need to measure it manually? Do you have any suggestions?

Looking forward to hearing from you. Thanks a lot!

**Comment by weidezhang** [comment]
Here is my answer to the questions:
1. it should work as long as your lidar data is dense enough s.t. features extracted from the tools should match well from both camera and lidar. otherwise, manual tuning might be required.
2. you are right. lidar-imu is still required for apollo 2.0. it should support multiple layers of lidar as low as vlp16.
3. no it shouldn't. you can try it with other cameras as wells. 
4. yes, you need to measure it manually.

**Comment by dengyuchenkit** [comment]
@weidezhang Thank you for the reply! 
For question 2 just want to make sure, does that mean the online calibration currently supports Velodyne model other than HDL64? I have a VLP32C lidar, will it work with this model? Thanks!

**Comment by homography** [comment]
@dengyuchenkit Currently, the online service only supports scan data from HDL64. Though it would not be hard to adapt to other LiDARs, the LiDAR-IMU calibration tool provided in 2.5 running on the car would be more efficient and versatile.

**Comment by dengyuchenkit** [comment]
@homography Got it! Thank you for the message!
