### ISSUE TITLE
release_commit.sh

### ISSUE THREAD

**Issue by yongyuandeyezi** [ApolloAuto/apollo#3704]
请问，运行release_into.sh进入docker后，在里面做了修改，如安装vim等软件、新建项目等，我怎么提交这些修改？
我尝试了以下步骤提交修改，但并未成功。请各位高手指点，谢谢！
1. 在docker中安装vim
2. esc退出docker
3. 执行release_commit.sh
4. 执行release_start.sh, release_into.sh，重新进入docker
5. 修改未保存，仍无法找到vim命令

**Comment by gengqx** [comment]
不要使用release了，使用dev

**Comment by yongyuandeyezi** [comment]
使用dev，dev_commit后也未在docker中保存修改

**Comment by natashadsouza** [comment]
@yongyuandeyezi is this an issue you still face?

**Comment by yongyuandeyezi** [comment]
@natashadsouza It has been solved. Thanks!
