### ISSUE TITLE
How to satisfy the vehicle nonhonomic contraints

### ISSUE THREAD

**Issue by JohnQii** [ApolloAuto/apollo#3706]
After I read the code in [Dp-planning](https://github.com/ApolloAuto/apollo/blob/1a172dbd4c80aa33e9448cc45e589fd54d52bdc3/modules/planning/tasks/dp_poly_path/dp_road_graph.cc), I hava some questions:
1.In the dp planning modules, how to satisfy the vehicle contraints? I find that the dp-planning uses the `QuinticPolynomialCurve1d` to generate the path between two points which get from dynamic planning, but how can we know the curve's curvature is smaller than the max curvature of vehicle?
2.If all the curve in Dp-planning is out of boundary, it will also choose a curve, but actually, this curve(path) will go out of road. And is there a good way to solve this?
Also, I want to ask something about ReferenceLineSmoother, exspacially in [`QpSplineReferenceLineSmoother`](https://github.com/ApolloAuto/apollo/blob/1a172dbd4c80aa33e9448cc45e589fd54d52bdc3/modules/planning/reference_line/qp_spline_reference_line_smoother.cc), Do this has contraint of vehicle nonholonomic in qp problem?

Thanks.

**Comment by lianglia-apollo** [comment]
(1) No, it is not guaranteed. We need to check the curvature at the end of planning cycle to make sure it is smaller than the max curvature.
(2) We need to sample enough points to make the possibility that all paths are out of boundary low enough. We can check again at the end of path generation to make sure the path is valid.
(3) No, it has no constraints from vehicle.

**Comment by JohnQii** [comment]
Thanks for your answers. 
And I think this will cause the planning path can't pass the right angle or other bend. Or maybe it will be near to the lane boundary when pass the right angle which I think it is not safe. But why not use the QP to optimize the path after DP planning in apollo 2.0?
