### ISSUE TITLE
lidar-based tracker as standalone application

### ISSUE THREAD

**Issue by ubercool2** [ApolloAuto/apollo#3726]
@lianglia-apollo I see that you authored code in https://github.com/ApolloAuto/apollo/tree/2f79d67e8937fd2d15fffd87622338741718ae70/modules/perception/obstacle/lidar/tracker/hm_tracker.

Do you know if this tracker can be ran as standalone by e.g. just having it take PointCloud2 data as an input? I would like to benchmark it against our own implementation.

**Comment by weidezhang** [comment]
Hi please take a look the related tools, which takes input (pcds and pose files from rosbags) that invokes the lidar perception process offline and let you save object tracking info. Feel free to modify based on your own needs. 
 
https://github.com/ApolloAuto/apollo/tree/2f79d67e8937fd2d15fffd87622338741718ae70/modules/perception/tool/offline_visualizer_tool

**Comment by ubercool2** [comment]
@weidezhang couple of more questions:
1. does the tracking happen inside this function: https://github.com/ApolloAuto/apollo/blob/2f79d67e8937fd2d15fffd87622338741718ae70/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool.cc#L108? 

I looked at the [public header](https://github.com/ApolloAuto/apollo/blob/4cffaffed140d1a57d227858b3762919db53213e/modules/perception/obstacle/onboard/lidar_process.h) but no documentation.

2. In terms of [pose](https://github.com/ApolloAuto/apollo/blob/2f79d67e8937fd2d15fffd87622338741718ae70/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool.cc#L39) what kind of pose do you expect: 
    1. vehicle in map frame
    1. pointcloud in map frame
    1. pointcloud in vehicle frame
    1. ...

3. Does the tracker work on the **raw** pointclouds or does it expect some pre-processing (e.g. extraction of bounding boxes)

4. Finally, does the tracker also work on the data from vlp16 or only with vlp64?

**Comment by JWhitleyAStuff** [comment]
@ubercool2 - You might also want to check out https://autonomoustuff.com/product/astuff-lidar-object-processing/.

**Comment by ubercool2** [comment]
@weidezhang I tried to extract tracker from the test program as well as from above suggested visualization tools but couldn't get it to compile after an hour so I gave up. In addition you guys provided no answers to https://github.com/ApolloAuto/apollo/issues/3726#issuecomment-379300158.  You can close this issue as `wont fix`.

@JWhitleyAStuff thanks for sharing. The product information you linked is very scarce, e.g.:
- does you algorithm use an actual tracker implementation. If yes which one?
- which motion model you use?
- which association algorithm do you use?
- is your code Apollo/research quality or automotive grade?
- do you have any benchmark data for your algorithm against e.g. ground truth?

**Comment by natashadsouza** [comment]
@ubercool2 please let us know if you are still looking for the answers to [the questions here](https://github.com/ApolloAuto/apollo/issues/3726#issuecomment-379300158).
