### ISSUE TITLE
What is "passage" in the map

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#3750]
Hi,

What "passage" means on the map?
Is that mean single lane?  all lanes in one direction of the road, something like that?
Thank you!

**Comment by startcode** [comment]
You can think 'passage' as a list of connected lanes. The vehicle can just drive forward without change lane in a passage

**Comment by wckorealsh** [comment]
So, the passage is updated real-time? What if the passage is blocked by other vehicles?

**Comment by startcode** [comment]
Passage is a map and routing concept.
 It does not consider other obstacles.
If the passage is blocked, planning can either find a new passage to bypass, or wait in current passage. In current logic, the vehicle will simply wait.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be fixed.
