### ISSUE TITLE
NTCAN_NET_NOT_FOUND - CAN device not present

### ISSUE THREAD

**Issue by lyletbjohnson** [ApolloAuto/apollo#3755]
I'm working with the up-to-date repo and have issues with the `canbus` module. I'm experiencing another issue, detailed in #2779 which may be related. 

## Background

This vehicle has successfully run Apollo 2.0 in recent past (~2 months). Due to updates to the repo, or an unintentional bump to the configuration the `canbus` module reports the errors detailed below.

I'm using the recommended / default hardware and software; no additional components.

## Troubleshooting

1. Both the host machine and docker container show that the ESD CAN channels, enumerated as `/dev/can*`

```
$ ls -l /dev/can*
crw-rw-rw- 1 root root 52, 0 Apr  6 16:03 /dev/can0
crw-rw-rw- 1 root root 52, 1 Apr  6 16:03 /dev/can1
crw-rw-rw- 1 root root 52, 2 Apr  6 16:03 /dev/can2
crw-rw-rw- 1 root root 52, 3 Apr  6 16:03 /dev/can3

```

**Question 1.1**: Is it possible for the Apollo system to create these device handles without the hardware being present? 

When I check `lspci`, there are no entries with the string `esd` or `ESD`. **Question 1.2**: Is this expected?

2. CAN libraries exist within `third_party/can_card_library/esd_can`; here's the directory tree, per the README.
```
.
├── BUILD
├── esd_can.tar
├── include
│   └── ntcan.h
├── lib
│   ├── libntcan.so
│   ├── libntcan.so.4 -> libntcan.so
│   └── libntcan.so.4.0.1 -> libntcan.so
└── README.md
```

Can someone please confirm the symbolic links point to the correct location? I find it strange that they both point to the `libntcan.so` library. 

3. Upon starting the `canbus` module with `./scripts/canbus.sh start`, I receive the following in the `data/log/canbus.INFO` log
```
$ tail -f  data/log/canbus.INFO 
I0406 18:23:09.857515  3765 canbus.cc:93] The vehicle controller is successfully created.
I0406 18:23:09.857519  3765 can_sender.h:352] Add send message:60
I0406 18:23:09.857524  3765 can_sender.h:352] Add send message:62
I0406 18:23:09.857528  3765 can_sender.h:352] Add send message:64
I0406 18:23:09.857532  3765 can_sender.h:352] Add send message:66
I0406 18:23:09.857537  3765 can_sender.h:352] Add send message:68
I0406 18:23:09.857540  3765 lincoln_controller.cc:117] Controller is initialized.
I0406 18:23:09.857543  3765 canbus.cc:99] The vehicle controller is successfully initialized.
E0406 18:23:09.858793  3765 esd_can_client.cc:63] open device error code [19]: NTCAN_NET_NOT_FOUND - CAN device not present
E0406 18:23:09.885854  3765 apollo_app.cc:64] canbus Start failed: CANBUS_ERROR: Failed to start can client
```

**Comment by lyletbjohnson** [comment]
Note: I'm also using this public guide to aid in troubleshooting, though I haven't been able to find any inconsistencies between my Apollo 2.0 instance and this documentation: 

- http://www.esd-electronics-usa.com/shared/handbooks/CAN-API_Part2_Installation_Manual.pdf

**Comment by lyletbjohnson** [comment]
## Troubleshooting update

On my host machine, I find the following in the `/var/log/dmesg` log: 

```
./dmesg:[    7.844778] esdcan_pcie402: module license 'Proprietary' taints kernel.
./dmesg:[    7.845035] esd CAN driver: init start
./dmesg:[    7.845074] esd CAN driver: Version: 0x00003A03
./dmesg:[    7.845075] esd CAN driver: No esd CAN card found!
./dmesg.0:[    7.859051] esdcan_pcie402: module license 'Proprietary' taints kernel.
./dmesg.0:[    7.859406] esd CAN driver: init start
./dmesg.0:[    7.859448] esd CAN driver: Version: 0x00003A03
./dmesg.0:[    7.859449] esd CAN driver: No esd CAN card found!
```

I located the kernel module to further troubleshoot. 

`/lib/modules/4.4.32-apollo-3-RT/kernel/drivers/esdcan/esdcan-pcie402.ko`

When I try to load the module, it complains that there is `No such device`. 

```
$ sudo insmod /lib/modules/4.4.32-apollo-3-RT/kernel/drivers/esdcan/esdcan-pcie402.ko
insmod: ERROR: could not insert module /lib/modules/4.4.32-apollo-3-RT/kernel/drivers/esdcan/esdcan-pcie402.ko: No such device
```

Have there been reports of the ESD CAN cards failing? 

Has this been seen by the Apollo team?

**Comment by lyletbjohnson** [comment]
Hey @Capri2014, I'll go ahead and test with a new card. 

Can you / Apollo team still confirm the following open questions? (1.1), 1.2), (2), (5), (6), and (7) need to be answered.

**Comment by quning78** [comment]
Seems more like a hardware issue, have you tried different can card?

**Comment by YangHan101** [comment]
1.1 I believe the can* are created by mknod command, they will be there even if there is no actually CAN devices.
1.2 lspci, you should see a device from ESD
2. that seems to be the same as what I have
5. We have observed issues "the CAN card cannot be found" happened before. We fixed it when we got a BIOS update from Neousys(our IPC vendor). Are you using Nuvo6108GC? If so, can you tell us the BIOS version (hit F2 while starting up the IPC)?

**Comment by lyletbjohnson** [comment]
I'll have an update for this thread soon -- I'm awaiting new hardware to validate our findings. 

Thanks for the continued support!

**Comment by Zhenni17** [comment]
@lyletbjohnson Do you have any update on the thread? :)

**Comment by YangHan101** [comment]
@chexiaoyu, maybe you should open a separate issue. 

Do you have an Esd can card installed? Do you have the driver installed as well? Can you post the result of "lspci -tv"?

**Comment by chexiaoyu** [comment]
Well，I change “CHANNEL_ID_ONE” to “CHANNEL_ID_ZERO” ,and solve the problem.Thank you.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Yang Han <notifications@github.com>
发送时间: 星期五, 七月 27, 2018 07:56
收件人: ApolloAuto/apollo
抄送: chexiaoyu; Mention
主题: Re: [ApolloAuto/apollo] NTCAN_NET_NOT_FOUND - CAN device not present (#3755)


@chexiaoyu<https://github.com/chexiaoyu>, maybe you should open a separate issue.

Do you have an Esd can card installed? Do you have the driver installed as well? Can you post the result of "lspci -tv"?

―

**Comment by YangHan101** [comment]
@chexiaoyu Thanks for the update.
@lyletbjohnson I am closing the ticket. If you have more update, please feel free to reopen.
