### ISSUE TITLE
what do I need to do if I use gnss receiver 'iMAR' instead of 'Novatel SPAN-IGM-A1'

### ISSUE THREAD

**Issue by STX321** [ApolloAuto/apollo#3758]
what do I need to do if I use gnss receiver 'iMAR' instead of 'Novatel SPAN-IGM-A1'

**Comment by YangHan101** [comment]
Hello @STX321,

I have not used or evaluated iMAR, so I am not completely sure how different it is from Novatel's SPAN-IGM-A1. I am going to try to answer based on my understanding of what data the A1 module is currently providing.

1. positioning
2. accelerometer and gyro
3. satellite observation and range measurements (GNSS, GLONASS and BEIDOU if available) for mapping

Currently, the information from the receiver is processed by gnss driver. The driver assumes message format the same as Novatel's convention. Unless iMAR output is following the same format, you probably need to make some modification to the gnss driver to parse iMAR's output.

Please feel free to let us know if you have more questions on this. 

BTW, if you could, it would be nice if you can educate me on how to interface with iMAR products. Then I can have a better understanding of this receiver and have a better idea of what needs to be done.

**Comment by Zhenni17** [comment]
Closing the issue, and feel free to reopen the issue if I missed anything.
