### ISSUE TITLE
Still buggy  in speed_limit_decider.cc

### ISSUE THREAD

**Issue by histfuture** [ApolloAuto/apollo#3764]
#3687 
In path_data.cc (line 191 to 196),  the "s" grows along the trajectory(i.e discretized_path) which means "path_s + adc_s" should be a point at the discretized_path.  However, the PerceptionSLBoundary is calculated by frenet coordinate that refers to the "referenceline".  Why not the value here is "frenet_point_s"?

![image](https://user-images.githubusercontent.com/2638853/38284859-f8af08ac-37ef-11e8-9451-8a42069d9616.png)

An other question is also in speed_limit_decider.cc, 

![image](https://user-images.githubusercontent.com/2638853/38285224-d402bc72-37f1-11e8-937c-459180c0de2f.png)

should line(147-152) be something like "(adc_boundary.start_l() - const_path_obstacle->PerceptionSLBoundary().end_l() > -kRange)"

**Comment by lianglia-apollo** [comment]
The code of first issue seems correct. The second one is fixed at https://github.com/ApolloAuto/apollo/pull/3771
