### ISSUE TITLE
about to compute whether the object is on one side of the reference line or not in the mode of planning

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#3769]
to be honest, I cannot entirely understand the function BuildTrajectoryStBoundary() which is to deal with obstacle prediction trajectory.
 first, for GetApproximateSLBoundary(object_moving_box, start_s, end_s, &object_boundary), I can understand that the box is rotated to align the reference line and get the sl_boundary, but what's the piurpose?

second, how to understand the part code at line 182 to 194 in [path_obstacle.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/path_obstacle.cc)
why we use the object_boundary‘s  longitudinal separation: (end_s - start_s) * kSkipLDistanceFactor to judge the object is on one side of the reference line which is a lateral separation. And why the factor "kSkipLDistanceFactor" is set to 0.4, is a experienced parameter?
` // skip if object is entirely on one side of reference line.
    constexpr double kSkipLDistanceFactor = 0.4;
    const double skip_l_distance =
        (object_boundary.end_s() - object_boundary.start_s()) *
            kSkipLDistanceFactor +
        adc_width / 2.0; 
    if (std::fmin(object_boundary.start_l(), object_boundary.end_l()) >
            skip_l_distance ||
        std::fmax(object_boundary.start_l(), object_boundary.end_l()) <
            -skip_l_distance) {
      continue;
    }`

third, what's meaning when has_low and has_high is set to true and polygon_points is emplaced back?
`has_low = object_moving_box.HasOverlap(
            {low_ref, low_ref.heading(), adc_length, adc_width});`
`has_high = object_moving_box.HasOverlap(
            {high_ref, high_ref.heading(), adc_length, adc_width});` 

Thank for your reply!

**Comment by lianglia-apollo** [comment]
(1) For each obstacle, we are building an SL bounding box, where s, l are defined relative to the reference line. The definition of SLBoundary is at ```modules/planning/proto/sl_boundary.proto```.
(2) It means we are having more nudge distance for larger vehicles.
(3) These code are used to map the obstacles to S-T graph. Each obstacle will be represented as a region on S-T graph, where a point (s, t) in the region means that the obstacle will be at a distance s on ego vehicle's path at time t.

**Comment by histfuture** [comment]
@lianglia-apollo What is the difference between GetApproximateSLBoundary and GetSLBoundary?

**Comment by lianglia-apollo** [comment]
Get approximate SL boundary will run faster but not as accurate as GetSLBoundary.

**Comment by histfuture** [comment]
@lianglia-apollo Does that means I can replace all GetApproximateSLBoundary to  GetSLBoundary, if I do not concern much about efficiency
