### ISSUE TITLE
UpdateNode中生成curve的问题

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#3781]
在[dp_road_graph.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/tasks/dp_poly_path/dp_road_graph.cc)中UpdateNode函数中242至253行中，注释为

> // try　to connect the current point with the first point directly，only do this at lane change; 
>    if (level >= 2) {
      init_dl = init_frenet_frame_point_.dl();
      init_ddl = init_frenet_frame_point_.ddl();
      QuinticPolynomialCurve1d curve(init_sl_point_.l(), init_dl, init_ddl,
                                     cur_point.l(), 0.0, 0.0,
                                     cur_point.s() - init_sl_point_.s());
      if (!IsValidCurve(curve)) {
        continue;
      }
      const auto cost = trajectory_cost->Calculate(
          curve, init_sl_point_.s(), cur_point.s(), level, total_level);
      cur_node->UpdateCost(front, curve, cost);
    }

我理解为只有当切换车道时才生成初始sl_point到每一个level上采样点生成五阶多项式的l(s)，否则均是两相邻node中的point生成l(s)，即第226-238行的内容。但是该函数并无切换车道的逻辑判断，也就是当level>2时首先进行一次相邻node中的point生成l(s),然后再做一次初始sl_point到该node的l(s)，如此计算的意义是什么，是否冗余？

**Comment by startcode** [comment]
please ignore 'only do this at lane change'. I will delete this comment soon.
It turns out that this technique can also be applied in non-change lane cases
