### ISSUE TITLE
Overlap_id in the hdmap

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#3822]
I was going through the base_map.txt file and the various map proto files. I couldn't understand what exactly was the overlap proto and how is it used in the code. Also, Lanes, roads, junction etc all have overlap_id. Want to know how is this used by the modules.

**Comment by startcode** [comment]
Overlaps are used to associate road element (such as junction, crosswalk, traffic light) and lanes. It can be used to identify their geometry relation.
For example, a crosswalk overlap with a lane, then the there will be a ` LaneOverlapInfo` and a `CrosswalkOverlapInfo` in `Overlap.object`. Here is an example
```
overlap {
  id {
    id: "overlap_3814"
  }
  object {
    id {
      id: "1725a_1_-1"
    }
    lane_overlap_info {
      start_s: 16.7282
      end_s: 20.5728
      is_merge: false
    }
  }
  object {
    id {
      id: "11128"
    }
    crosswalk_overlap_info {
    }
  }
}
```

**Comment by KitFung** [comment]
Is there any document define the meaning of the components in the hdmap?

**Comment by natashadsouza** [comment]
@KitFung we have the map document that you could request using [the following link ](https://www.surveymonkey.com/r/DXWK3Q6). Thanks!

**Comment by donlindon** [comment]
@natashadsouza the link you provide is SurveyMonkey, a website for people to do survey, does the HD map document can be found on that site?

**Comment by natashadsouza** [comment]
@donlindon no you can request it there by sending us your email address. You could also send us your email on #3005 and the team will share it with you. Thanks! Currently closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
