### ISSUE TITLE
Who triggers the change of the reference line?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#3843]
Hello,

What event makes the switch of the reference line?
It is perhaps related to `main_decision` but not quite follow.
Thank you!

**Comment by startcode** [comment]
Reference line was mainly derived from routing and map. 
It changes when it expands on the road or change lane.
Most of the logic is in https://github.com/ApolloAuto/apollo/blob/master/modules/map/pnc_map/pnc_map.cc and https://github.com/ApolloAuto/apollo/blob/master/modules/planning/reference_line/reference_line_provider.cc

**Comment by wckorealsh** [comment]
Thank you @startcode,

By just looking at demo_2_0 play, I see the reference line is switched to the target lane. So, I was wondering lane change event triggers the switching reference line or some other event (rules?) triggers switching the reference line and hence lane change happens.

Can you elaborate little more on lane change algorithm? What triggers lane change?
For example, perception sees obstacle->traffic_rule->lane change decision made-> reference line is changed-> planning to change lane.

I see lane change related potions in several places,  main_decision, change_lane_decision, pnc_map and so on.

Thank you for the great help!

**Comment by startcode** [comment]
Lane change is a planning option given by routing.
When there is a change lane region in routing, we will create two reference lines, one on current lane, and another on the target lane. The planning algorithm will try to make one planning trajectory on each reference line, and it will eventually select one based on traffic rules and cost functions.

**Comment by wckorealsh** [comment]
I see, thank you for the quick response.
Just to clarify, the presence of the obstacle is not related to lane change in current version, correct?

**Comment by startcode** [comment]
That's not true.
The presence of obstacle does not affect how to create passage and reference line,
but the obstscles does affect how planning making change lane decisions.

**Comment by wckorealsh** [comment]
@startcode ,
Thank you for update! That's great, would you say the following is true?
 - lane change triggered either route from pnc map, or presence of obstacle on the lane
 - In obstacle case, perception sees obstacle->traffic_rule->lane change decision made-> reference 
     line is changed-> planning to change lane.

Thank you again!

**Comment by startcode** [comment]
Basically true but not accurate.
* lane change triggered either route from pnc map, or presence of obstacle on the lane (this feature not supported yet). Obstacle does not trigger change lane, but may affect change lane decision.
* reference line is changed is not accurate. I would say "reference line is selected". Reference line is more like a static information derived from route and map. Multiple reference line in a frame indicates change lane is an option in current frame. Planning selects reference line based on traffic condition and obstacle.

**Comment by wckorealsh** [comment]
I see, thank you. One last just to clearfy. Please correct me if I am wrong.

When there are multiple lanes (n number of lanes), n number of reference lines are considered and the one that maximizes the cost is selected. This selection is effected by the presence of the obstacle. This could result in lane change.

**Comment by startcode** [comment]
This is exactly Apollo's current planning apporach. In Apollo, n <= 2 now.

**Comment by wckorealsh** [comment]
Awesome!!

**Comment by KevinYuk** [comment]
> Lane change is a planning option given by routing.
> When there is a change lane region in routing, we will create two reference lines, one on current lane, and another on the target lane. The planning algorithm will try to make one planning trajectory on each reference line, and it will eventually select one based on traffic rules and cost functions.

@startcode Could you please show a picture for these two reference lines?

**Comment by warden2018** [comment]
@startcode @wckorealsh Currently, I am also working on routing and planning. After routing, dreamview will show just one reference line. But the driving road has two lanes. Is it working correctly?
![Screenshot from 2019-08-01 18:42:18](https://user-images.githubusercontent.com/48422255/62287280-22932300-b48c-11e9-828e-4a0e6ec3f0c9.png)
