### ISSUE TITLE
Question about docker images

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#3863]
Hi guys,

Apollo uses Docker platform to implement certain functions.

User pulls image from registry. And I want to know about each Docker image.

When I run `dev_start.sh`, it seems that below docker images are pulled.

- **docker images**
dev-x86_64-20180320_1118
localization_volume-x86_64-latest
map_volume-sunnyvale_big_loop-latest
map_volume-sunnyvale_loop-latest
yolo3d_volume-x86_64-latest

Q1. Can I get some information about these docker images one by one? I also wonder if there is any ways about it. (e.g. To refer to something)

Q2. Is the image 'map_volume-sunnyvale_big_loop-latest' about map sunnyvale big loop?
If I want to add map near my office, do I have to create docker image for that map like apollo's way?

Thanks!

**Comment by CCodie** [comment]
Hi @xiaoxq , thank you for reply!

I want to know more about your Answer 1.

What I understood about Docker, Docker Volume is a concept for persisting data because it is out of container storage. And Apollo used Docker Volume by mounting some source code files to "Dev Container". Is this the right way to understand?

Then I wonder about role of these docker-volume containers and relation with "Dev Container". 
For example, does container for localization volume make some information and Dev Container use it?
If it is right, does function of localization stop when I stop the localization container?

Thanks :)

**Comment by xiaoxq** [comment]
Yes, our docker volumes act like a part of source code, or more specifically, some required data such as HDMaps. They are supposed to be always live with dev_container.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
