### ISSUE TITLE
What is the purpose of the opendrive_adapter.cc file located in modules/map/hdmap/adapter?

### ISSUE THREAD

**Issue by antonfrigard** [ApolloAuto/apollo#3864]
Is it used to convert files written in the standard opendrive format to the apollo opendrive format? If not, are there any other scripts that do this? 

Best regards

**Comment by msbeta** [comment]
Opendrive Adapter is used to convert  Apollo Opendrive format into Apollo internal application format. there is no script to convert standard Opendrive format to the apollo Opendrive format now.

**Comment by antonfrigard** [comment]
Thank you!
