### ISSUE TITLE
Did Apollo docker build upon Nvidia-docker? resulting in failed to install nvidia-driver by *.run

### ISSUE THREAD

**Issue by Durant35** [ApolloAuto/apollo#3911]
Even I just run the apollo docker and enter, some modules related to nvidia-driver exist
```sh
xxx@in_dev_docker:/apollo$ lsmod | grep nvidia
nvidia_drm             49152  7 
nvidia_modeset        860160  5 nvidia_drm
nvidia              13144064  339 nvidia_modeset
drm_kms_helper        155648  2 i915_bpo,nvidia_drm
drm                   364544  6 i915_bpo,drm_kms_helper,nvidia_drm
```
which are almost the same as the host!!!
```sh
xxx@xxx-ThinkPad-T460:~$ lsmod | grep nvidia
nvidia_uvm            675840  0
nvidia_drm             49152  7
nvidia_modeset        860160  5 nvidia_drm
nvidia              13144064  340 nvidia_modeset,nvidia_uvm
drm_kms_helper        155648  2 i915_bpo,nvidia_drm
drm                   364544  6 i915_bpo,drm_kms_helper,nvidia_drm
```
Actually, I had successfully run the offline perception demo but failed after system upgrade nvidia-driver, replacing that installed through `NVIDIA-Linux-x86_64-384.98.run` related to my `GeForce 940MX`, as mentioned in: 
+ [How to Run Offline Perception Visualizer] CUDA driver version is insufficient for CUDA runtime version https://github.com/ApolloAuto/apollo/issues/1687
+ Fail to Install Nvidia Driver inside docker https://github.com/ApolloAuto/apollo/issues/2787

**Comment by xiaoxq** [comment]
May I know the image version?

Current apollo container is ubuntu 14.04 + manually installed Nvidia Driver / Cuda 8 / Cudnn 7. But we are trying to migrate to nvidia/cuda:8.0-cudnn7-devel-ubuntu14.04 as the base, as shown in the dockerfile: https://github.com/ApolloAuto/apollo/blob/master/docker/build/dev.x86_64.dockerfile

Maybe you can try building you own image from the dockerfile and play with it. One thing I know is that nvidia-docker v1 is preferred for our situation.
https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-1.0)

Please share with us about your progress :)

**Comment by Durant35** [comment]
Thanks! My image is `dev-x86_64-20171204_1625` during Apollo1.5, almost 4 months ago since I tried.
```sh
$ docker image ls
REPOSITORY                                 TAG                        IMAGE ID            CREATED             SIZE
apolloauto/apollo                          dev-Nvidia-driver          e67f10db2e7c        43 minutes ago      12.4GB
apolloauto/apollo                          dev-Nvidia                 6c26075ad2b0        17 hours ago        12.4GB
apolloauto/apollo                          dev-x86_64-20171204_1625   282c24a8f78f        4 months ago        11.5GB
registry.docker-cn.com/apolloauto/apollo   dev-x86_64-20171204_1625   282c24a8f78f        4 months ago        11.5GB
```

**Comment by xiaoxq** [comment]
Sorry for the delay.

I'm developing a canary version of docker scripts which are still in testing. Here is the document: https://github.com/ApolloAuto/apollo/blob/master/docker/canary/README.md

**Comment by alexbuyval** [comment]
@xiaoxq Thank you for canary version. This version solved the issue with nvidia drivers for me.
However, I cannot run any [visualizer ](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_perception_visualizer.md)there. 
It seems that there is no OpenGL library in your docker. I found this [issue](https://github.com/NVIDIA/nvidia-docker/issues/534) and I would like to try to build new docker container based on [nvidia:opengl containers](https://hub.docker.com/r/nvidia/opengl/).
What do you think it makes sense?
And could you share docker file which you used for canary version?

Thanks,
Alex

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
