### ISSUE TITLE
Code Review on Localisation Module 

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#3914]
Hi, Team. 

I just read new demonstration for Localisation module in Apollo. 
It explains that in Localisation, Apollo use three information source:
Lidar
MTK
GPS. 
For this part, is it possible for the team to share some brief structure about the code regarding on each .c file as well as the items like "GetPlaneFeaturePoint" 

![1801523955036_ pic](https://user-images.githubusercontent.com/16748704/38868544-f517a048-4279-11e8-98e9-223b4d5e21c8.jpg)

![1821523955071_ pic](https://user-images.githubusercontent.com/16748704/38868550-ff04e4da-4279-11e8-87d4-46ccee3849ac.jpg)

**Comment by lianglia-apollo** [comment]
The function GetPlaneFeaturePoint is in extract_ground_plane.h, line 128 - line 180.

**Comment by JonathanJones92** [comment]
@lianglia-apollo Hi I reviewed the localisation module code again. However, I still can't find the core algo. Regarding the blog from "Hello Apollo/深度解析Apollo2.0 定位技术 ". Localisation module fuses information from sensors， IMU，GPS etc. May I ask where are those fusion algos/data process algos? Where can I find them？ Could you help me to list those func names as well as where they exist?

Great thanks.

**Comment by zhouyao4321** [comment]
For the meaning of PointXYZIRT,XYZITd and XYZIT, you can see this link http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while.
