### ISSUE TITLE
What does SimControl do?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#3915]
Hi Apollo team,

There is a "SimControl" toggle switch in the dream viewer. I can enble/disable it.
What does this do? I am guessing we can simulate with dream viewer, if so, how do I run?
Please let me know, thank you.

Regards.

**Comment by lianglia-apollo** [comment]
SimControl will receive results from planning and move the car according to the planning trajectory.

**Comment by wckorealsh** [comment]
Hi @lianglia-apollo,

So it sounds like control module is not used in the simulation, correct?
Is there any way to run planning module (command line maybe?) so we can see vehicle operating in the dream view?
Thank you.

Regards

**Comment by siyangy** [comment]
After enabling SimControl, in order to use it, you can also start routing and planning modules. Then the planning module can drive the car in Dreamview after a routing is given. The routing request can be issued from Dreamview as well.

**Comment by wckorealsh** [comment]
Thanks, how to run routing and planning modules?

**Comment by siyangy** [comment]
There's a model controller panel that you can open from sidebar.
