### ISSUE TITLE
GUI version of  rosbag in Apollo?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#3916]
Hi Apollo team,

Are you planning to include GUI version of rosbag so we can easily rewind/fast forward log data?
If you are not, can you provide a recommendation for navigating log data?
Thank you!

**Comment by startcode** [comment]
http://wiki.ros.org/rosbag/Commandline

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while.
