### ISSUE TITLE
Difference between `path_obstacle` and `path_decision'

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#3918]
Hi team Apollo,

There are two similar looking classes `path_obstacle' and 'path_decision`.
Can you please explain what are these two classes for?
Thank you again!

**Comment by startcode** [comment]
`path_obstacle` is an obstacle's projected properties on a particular path
`path_decision` is the decision made for obstacles on a particular path.

**Comment by wckorealsh** [comment]
Hi @startcode again,

I am confused because `path_obstacle` has `AddLongitudinalDecision` and `AddLateralDecision` as a member function and `path_decision` also has  `AddLongitudinalDecision` and `AddLateralDecision`  as well. Looks like both decisions about the obstacle are made in both?

Thank you!

**Comment by startcode** [comment]
Decisions about obstacle are made somewhere else, e.g., by different tasks.
PathObstacle and PathDecision are classes to help organize and to manage the properties, and object decision is just one of such properties.
