### ISSUE TITLE
HD map coordinate frame ?

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#3931]
In the coordinate system document, it is mentioned that the HD map uses Global coordinates (lat, lon, ele). But the base_map.xml (which I assume is the HD map) and base_map.txt have points in Local frame. Can you clarify ?

**Comment by msbeta** [comment]
We use the WGS-84 coordinate system in the OpenDrive format of HDMap，and use the UTM coordinate system in Internal system，they are all global coordinate systems.

**Comment by ankitvora7** [comment]
That answers my question. Thanks!
