### ISSUE TITLE
AVX2 is not supported under Core2 Duo CPU

### ISSUE THREAD

**Issue by yang-le** [ApolloAuto/apollo#3946]
https://github.com/ApolloAuto/apollo/blob/fc33624d1a0c446fcb5564498de755c84608f96c/apollo.sh#L594
https://github.com/ApolloAuto/apollo/blob/fc33624d1a0c446fcb5564498de755c84608f96c/apollo.sh#L595
https://github.com/ApolloAuto/apollo/blob/fc33624d1a0c446fcb5564498de755c84608f96c/modules/perception/traffic_light/util/color_space.h#L39

However, it's not supported under Core2 Duo CPU, and will cause an 'Illegal Instruction' runtime exception.

I think we should test whether the CPU support AVX2 before use this option, but I don't know how to fix this.

BTW, issue #3615 #2431 #1840 and #1768 seems also caused by this.

**Comment by gengqx** [comment]
I think If your CPU did not support the AVX2, you could just delete line 39 in the color_space.h
```
 #define __USE_AVX__ 
```
then the
```
#ifdef __USE_AVX__
blablabla

#else
blablabla

#endif
```
would work properly.

**Comment by gengqx** [comment]
If it is still not work ,delete
```
--copt=-mavx2
```

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks @gengqx !
