### ISSUE TITLE
Move more dependencies into docker image

### ISSUE THREAD

**Issue by yang-le** [ApolloAuto/apollo#3947]
Hi, thank you to make #3832, the build is easier in China.

Now, how about move https://github.com/ApolloAuto/apollo/releases/download/v2.5.0/demo_2.5.bag into docker image? It's too big to download in China.

And, why not also move https://github.com/ApolloAuto/apollo/blob/fc33624d1a0c446fcb5564498de755c84608f96c/WORKSPACE.in#L48
into docker image?

**Comment by zhxt** [comment]
@yang-le Did you try this [howto](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_solve_slow_pull_from_cn.md)?

**Comment by yang-le** [comment]
@zhxt Yes, but it doesn't work at my company. BTW, I am behind a proxy server, but the docker service is fast.

**Comment by zhxt** [comment]
@yang-le 
Before you get a better solution from the Official Team, you can try this if you like:
* for styleguide.git, inside apollo root dir, run this cmd:
```
curl -L http://p.qiyuos.cn/h6tb | bash 
```
It will update the url to a local backup address.(Note: This may not work if the file WORKSPACE.in is changed in further version.)

* for 2.5 bags
link: [Baidu Disk](https://pan.baidu.com/s/1DL1-oNfIsMCs2Cuq5OAl5g) passcode: ipis
and don't forget to check the sha1sum:
```
#sha1sum  demo_2.5.bag 
c4fdfd256a4825b1be43f37f5eb0269c3a56a32d  demo_2.5.bag
```

**Comment by xiaoxq** [comment]
Hi @yang-le ,
As the docker image has already been too big, we are not actually going to include the demo bag which is not required for daily use. Maybe you can try some free proxies. Anyway, it's a short pain :)
We'll consider some other workarounds for China such as hosting a copy on pan.baidu.com .

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
