### ISSUE TITLE
Cannot access camera data

### ISSUE THREAD

**Issue by rgunjala-as** [ApolloAuto/apollo#3949]
I cannot see the camera data. I tried going into the usb_cam package and running the _start_one_leopard.launch_ file. It keeps throwing an error called `camera is offline` and the node dies. I've looked for this error on the internet and I found suggestions to change the pixel_format, camera_timeout parameters but it did not help.

I have even tried using this camera on a different computer running regular ROS (not inside Apollo) using the usb_cam package and varying the parameters. I can't seem to get it to run. The node dies after throwing an error called `[ERROR] [1524068705.650099517]: select timeout`. No one seems to have encountered this problem here, do you have any advice?

**Comment by CCodie** [comment]
@rgunjala93 @quning78 @Zhenni17 
Hi, did you solve this problem? I have the same issue.
I'm trying to run usb camera using usb_cam package and want to see the camera data.
There are some contents about usb camera,
`bash apollo.sh build_usbcam` or `/apollo/scripts/usb_camera.sh` but I still do not know how to run the usb camera.

**Comment by apollodevcommunity** [comment]
First check that the driver is installed.Second check that your USB camera can read data   you can use ls /dev/video*.Third check data path.——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=695

**Comment by apollodevcommunity** [comment]
First check that the driver is installed.Second check that your USB camera can read data   you can use ls /dev/video*.Third check data path.——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=695
