### ISSUE TITLE
Perception/third_party_perception ID expansion && ID offset

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#3959]
I have some questions regarding ID expansion and ID offset.

From "third party perception " conversion.cc all the obj ID's from Radar and Camera were added a ID offset. I'm curious about why it should be done and what's inside this trick.
From "perception" also I read in Obstacles ContiRadar part, they were functions named "conti radar id expansion.cc". The same to above, could you help me to analyse what's inside those functions?

Thanks team :) 👍 

@mickeyouyou

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
