### ISSUE TITLE
demo_2.5.bag issue

### ISSUE THREAD

**Issue by yuconglin** [ApolloAuto/apollo#3963]
Did anyone try to run rosbag play with the demo_2.5.bag? The dreamview said GPS unstable and the car was not on the map.

**Comment by zhouDearman** [comment]
How did you run 'demo_2.5.bag'?I can't run 'rosbag play -l ./docs/demo_guide/demo_2.5.bag' this command in the docker,it hints me 'rosbag command not found'.I also run this command on my own ros not in the docker,but I can't see anything on the dreamView?Could you tell me how to run this command?

**Comment by zhouDearman** [comment]
Thank you for your response.I have solved this problem.I just use 'source scripts/bootstrap.sh' to run apollo,not 'bash scripts/bootstrap.sh'.Now I can see the demo on dreamview,but i have encountered the same problem with yours,the GPS is unstable.

**Comment by jmtao** [comment]
@zhouDearman It's great you've made it work. 
"GPS is unstable" was recorded and therefore comes with the bag. You can ignore it if you just want to play with the bag. 
We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
