### ISSUE TITLE
Where can I get the ROS bag file for Offline Perception Visualizer tool playing?

### ISSUE THREAD

**Issue by fatqi** [ApolloAuto/apollo#3976]
I noticed Apollo provides the offline perception visualizer tool to see how the perception module works, and the PCD and Pose Data which extracted from a ROS bag file are needed at first. 
I want to know does Apollo provide some test ROS bag file for this offline perception visualizer?
If yes where can I get them? 
If no how can I generate a ROS bag file without any Autonomous vehicle hardware?
I'm waiting for your response, thank you!

**Comment by yuconglin** [comment]
try the vehicle system demo data from apollo data platform. http://apollo.auto/opendata.html

**Comment by techoe** [comment]
We will add ROS bag with images soon.
