### ISSUE TITLE
Buggy in path_obstacle.cc?

### ISSUE THREAD

**Issue by histfuture** [ApolloAuto/apollo#3977]
Should the following code 
![image](https://user-images.githubusercontent.com/2638853/39036683-dc302e9a-44b0-11e8-9257-137ce31957f4.png)

be something like
`double high_s =std::min(object_boundary.end_s() + adc_half_length, FLAGS_st_max_s+low_s);`

 'object_boundary.end_s() + adc_half_length' is related to reference_line which means this should be value in the range of [0,referenceline.length], but 'FLAGS_st_max_s' is a constant value which is set to '100' by default

**Comment by lianglia-apollo** [comment]
I think we are trying to limit the high_s to be at most 100.
