### ISSUE TITLE
Apollo 1.5 Build Error

### ISSUE THREAD

**Issue by zhangjun-xyz** [ApolloAuto/apollo#398]
I've set up the docker environment in my Ubuntu. However when I ran the following command, 
`bash apollo.sh build
`
It gave me an error as an output:
`ERROR: query interrupted
`
Can anyone give me some suggestions?
The full output is as follows:
`System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
ERROR: query interrupted

[ERROR] Build failed!
[INFO] Took 2315 seconds
`

**Comment by xiaoxq** [comment]
We met this issue in some bad networking environment, too.
It seems that bazel is trying to download dependencies but failed.

You can run "bazel query //..." first to see the procedure, and then continue to run "apollo.sh build".

**Comment by zhangjun-xyz** [comment]
Thanks  for your fast reply. I'll try it again.

**Comment by fy2462** [comment]
I cost a lost of to download "Building: no action running Fetching https://github.com/.../apollo-platform/releases/download/1.5.0/ros-indigo-apollo-1.5.0-x86_64.tar.gz;", do you have any package mirrors or agent to download these dependence ?

**Comment by zhangjun-xyz** [comment]
@fy2462 I had the same issue as yours. Hope others can help.

**Comment by pooluut** [comment]
same, not working...

**Comment by xiaoxq** [comment]
Thank you all for report!

It looks very slow to download tar ball from Github in China. We are working hard to release the pain.

**Comment by xiaowatongxue** [comment]
It tooks me at least 7 hours at this issue。

**Comment by coldrainy** [comment]
the same problem.no action running...then failed.

**Comment by zhangaigh** [comment]
@xiaoxq Is the problem solved?

**Comment by xiaoxq** [comment]
For now you can still run "bazel query //..." first to see the dependency pulling progress. And then run "apollo.sh build".

We are thinking of hosting dependencies in docker image, and users in China could download image from docker-cn.com. It's promising, but sorry that we still need some time to verify technical and policy issue.

**Comment by gk1115** [comment]
no action running...
have this problem been solved?

**Comment by xiaoxq** [comment]
Generally it's because of the slow data connection to pull dependencies from github. We have moved most stuffs into the docker image. Please sync your code and try again to see if it works.
