### ISSUE TITLE
When do I need apollo kernel?

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#3981]
I have a few scenarios which I'm not sure requires apollo kernel or not. Can you please comment on them?

1. Playing a bag file and running various modules on only my laptop?
2. Make a release docker image of my modified version of apollo and run it on the car. I understand that the car would need the apollo kernel but do I also have to have it on my laptop for it to finally work on the car?

**Comment by Grayhu07** [comment]
From what I understand, if you want to play bag file and test some modules only on your laptop, it is not necessary to install Apollo kernel. However, if you want to run Apollo with an actual car, it is recommended to install kernel. Also I believe it would be better if you can test code with kernel before run it on the car.

**Comment by natashadsouza** [comment]
Closing this issue as there has no communication in a while. Feel free to open it if you still have additional questions.
