### ISSUE TITLE
Ubuntu 14.04 vs 16.04 ?

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#3983]
The Apollo 2.5 hardware installation guide recommends/requires users to install 14.04 on the IPC. But there's no such requirement for the development laptop. So say I have 16.04 on my development laptop. Will there be a problem when I try to create a release docker with it and run on the vehicle ?

**Comment by lianglia-apollo** [comment]
It should work well on your 16.04 laptop.

**Comment by xiaoxq** [comment]
Yes. I myself did that, too. And there is no problem.
