### ISSUE TITLE
Request for documentation to understand and test motion service in perception module

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#3985]
Dear Apollo developers, 

I am studying the implementation of perception module for Apollo 2.5 and find there is a new component called motion service. However, I see LanePostProcessingSubnode is using the motion service but do not well understand its high-level role and idea after reading the source code. I checked the [README](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md) of perception module and [documentation](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/perception_apollo_2.5.md) of the perception algorithm, but did not find details about this new component. 
Would it be possible to share some documentation about the design of motion service or provide some some reference to the key algorithms in motion service?

Also, is there any convenient way to test the algorithms of motion service with some pre-defined message input in Apollo? I saw stress test for motion service mentioned in this [commit log](https://github.com/ApolloAuto/apollo/pull/3956). Could you share some information about that? I am interested in testing the motion service algorithms by fuzzing some message input.

**Comment by techoe** [comment]
We will share more information about motion service later. Thank you for asking
