### ISSUE TITLE
How to properly stop Apollo?

### ISSUE THREAD

**Issue by rcywongaa** [ApolloAuto/apollo#3991]
Is there a script that properly stops all running apollo containers and dreamview?  Thanks

**Comment by jinghaomiao** [comment]
Please use the "Reset All" on DreamView to stop all modules.

**Comment by rcywongaa** [comment]
Thx for the response!  It appears that after pressing Reset All, the dreamview and the associated docker containers are still running, as shown when issuing the `ps aux | grep dreamview` and `docker ps`

    CONTAINER ID        IMAGE                                                    COMMAND             CREATED             STATUS              PORTS               NAMES
f11d54caf3d7        apolloauto/apollo:dev-x86_64-20180419_1510               "/bin/bash"         2 days ago          Up 2 days                               apollo_dev
e8cb19f79c8d        apolloauto/apollo:yolo3d_volume-x86_64-latest            "/bin/sh"           2 days ago          Up 2 days                               apollo_yolo3d_volume
605a431559fe        apolloauto/apollo:localization_volume-x86_64-latest      "/bin/sh"           2 days ago          Up 2 days                               apollo_localization_volume
b851bd043ae3        apolloauto/apollo:map_volume-sunnyvale_loop-latest       "/bin/bash"         3 days ago          Up 3 days                               apollo_map_volume-sunnyvale_loop
76f8591c6d0c        apolloauto/apollo:map_volume-sunnyvale_big_loop-latest   "/bin/sh"           3 days ago          Up 3 days                               apollo_map_volume-sunnyvale_big_loop

Also

**Comment by gengqx** [comment]
If you want to stop dreamview ,you should use 
```
bash scripts/bootstrap.sh stop
```
this would shudown  ros master node and dreamview.
if you think have done your work and commit the images ,or just think nothing to save and want to stop all the contrainners,you should use
```
docker stop $(docker ps -aq)
```
I don't know if it is proper due to it stop containers ,indeed all the containers.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to open if you have additional questions.
