### ISSUE TITLE
Do I need to install the apollo kernel?

### ISSUE THREAD

**Issue by meteor0530** [ApolloAuto/apollo#3992]
Hi,
I'm using apollo 2.0.0 dev version and want to have an onboard test . I install it following the guide on the github. Do I need to install the apollo kernel?
I want to drive my car manually and record the path using rtk_recorder module, and then drive automatically using rtk_replay module. Can I achieve it only with GPS and CAN? My GPS is novatel with IMU, does the GPS need some configurations or use directly after connect?

**Comment by Grayhu07** [comment]
It is not necessary to install Apollo kernel. In non-production environment, it will be ok that you do not install Apollo kernel. However, in production environments, it is recommended that you install Apollo kernel follow the [Apollo software installation guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md)

**Comment by Zhenni17** [comment]
Closing the issue due to there is no response in a while. Please feel to reopen the issue if I missed anything.
