### ISSUE TITLE
How to add default route in my own map

### ISSUE THREAD

**Issue by hzdsdhr** [ApolloAuto/apollo#3997]
I can see  many default routes in sunny_vale_big_loop map, how to add these kinds of default routes in my own map for sim_Control?

**Comment by unacao** [comment]
If you have already prepared your own map data including a base_map and a routing_map, and you are able to load and visualize your map in Dreamview, you can use 'Layer Menu'->'Point of View'->'Map' to drag and zoom the map, and get the x,y-coordinates of your mouse pointer. These x,y-coordinates can be used to construct the waypoint in the default_end_way_point.txt which is in turn read by default routing.

**Comment by hzdsdhr** [comment]
@unacao Thank you for your help, really appreciate it.

**Comment by zeyu-zha** [comment]
> If you have already prepared your own map data including a base_map and a routing_map, and you are able to load and visualize your map in Dreamview, you can use 'Layer Menu'->'Point of View'->'Map' to drag and zoom the map, and get the x,y-coordinates of your mouse pointer. These x,y-coordinates can be used to construct the waypoint in the default_end_way_point.txt which is in turn read by default routing.

@unacao : I have one more question here, could i use the upper methode to get the coordinate of the lane boundary and center line of the lane ?

**Comment by unacao** [comment]
In map view, you can get any coordinates reading from the mouse pointer.
