### ISSUE TITLE
How to measure the execution time for an entire frame in the perception module

### ISSUE THREAD

**Issue by htabani** [ApolloAuto/apollo#3998]
Hi, 

I am analyzing the execution of Apollo with the recent release (2.5). What is the best approach to measure the timing of processing one frame of input video? Do you also consider the overheads of ROS?

**Comment by techoe** [comment]
Please use apollo/scripts/diagnostics.sh to check the processing time of each module.

**Comment by htabani** [comment]
Thank you very much

**Comment by lianglia-apollo** [comment]
You can also set a timer at the beginning and end of the code section to measure time.
