### ISSUE TITLE
Apollo Demo 1.5 crash

### ISSUE THREAD

**Issue by fy2462** [ApolloAuto/apollo#400]
I run the demo 1.5 well, but it crashed when I open the browser with the address "localhost:8888" on chrome and firefox.

**Comment by siyangy** [comment]
Can you provide more information on how it crashed?

**Comment by fy2462** [comment]
@siyangy I snapshot the chrome browser status for this problem.
![image](https://user-images.githubusercontent.com/7626394/30781358-3ef5a446-a0e3-11e7-853e-313d16472ac5.png)

**Comment by fy2462** [comment]
it seem that backend works well, but browser openGL API invoke failed.

**Comment by siyangy** [comment]
This is most likely a browser compatibility issue. We have tested that dreamview can run in Firefox/Chrome/Safari, but not yet in Chromium. You can take a look at https://askubuntu.com/questions/299345/how-to-enable-webgl-in-chrome-on-ubuntu to check your browser's support to WebGL.
