### ISSUE TITLE
Update Vehicle Calibration ，Convert Results to Protobuf

### ISSUE THREAD

**Issue by mqqq1024** [ApolloAuto/apollo#4004]
大家好，由于我们采用的车平台无法按照apollo/blob/master/docs/howto/how_to_update_vehicle_calibration.md
这个文件更新 Vehicle Calibration。
所有想问一下 Convert Results to Protobuf 这一步的原理是什么？

**Comment by lianglia-apollo** [comment]
You can use anyway to fill the calibration table. The proto is defined as:
```calibration_table.proto                                                                                              [buffers] 
  1 syntax = "proto2";
  2 
  3 package apollo.control.calibrationtable;
  4 
  5 message ControlCalibrationTable {
  6   repeated ControlCalibrationInfo calibration = 1;
  7 }
  8 
  9 message ControlCalibrationInfo {
 10   optional double speed = 1;
 11   optional double acceleration = 2;
 12   optional double command = 3;
 13 }```

**Comment by mqqq1024** [comment]
@lianglia-apollo 谢谢。
我想再问一下，
 optional double speed = 1;
 optional double acceleration = 2;
 optional double command = 3;
这三个数值是如何获得的？或者是通过什么公式算出来的？

**Comment by lianglia-apollo** [comment]
I think the speed and acceleration are from localization; you can find the details in data_collector.py.

**Comment by mqqq1024** [comment]
@lianglia-apollo 
 Thank you for your answer。  
command与speed and acceleration有什么关系么？谢谢

**Comment by lianglia-apollo** [comment]
In the proto, command means the throttle and brake commands in percentiles; and the (command, speed, acceleration) tuple means that with command (brake or throttle) at the given speed, an acceleration can be produced.
