### ISSUE TITLE
 http://localhost:8888 can not connetcted after I installed two version of apollo.

### ISSUE THREAD

**Issue by fatqi** [ApolloAuto/apollo#4006]
1. I installed apollo 2.0 in docker container named apollo_dev, and the  http://localhost:8888 can be connected.
2. Then I pull apollo 2.5 to a new document, and change dev_start.sh and dev_into.sh to make a new docker container named apollo_dev_2.5. Build the apollo and start dreamview in the new docker, http://localhost:8888 can be connected properly.
3. Now I want to run apollo 2.0 dreamview again, so I exit apollo_dev_2.5 and into apollo_dev(for 2.0), run "bash scripts/bootstrap.sh", I can see dream view start but  http://localhost:8888 can not be connected.
Why?
4. Because  http://localhost:8888(started by apollo 2.0) can not be connected, I have to clean and build apollo 2.0 again. After rebuild, run "bash scripts/bootstrap.sh" in apollo 2.0, http://localhost:8888 can be connected, but the UI looks like it is still apollo 2.5 dreamview.

Is only one apollo can run in the same docker, even the docker container name is not same?

**Comment by vlin17** [comment]
Even though you setup two different docker env, both of them are using port 8888 on your machine, it is a port conflict issue. If you'd like to run both versions at the same time, please make sure different ports are set. 

To do so, 
1. open dreamview.conf file under modules/dreamview/conf
2. add "--server_ports=<PORT_NUMBER>" to the end of the file. 
Ex: 
> 
    --flagfile=modules/common/data/global_flagfile.txt
    --server_ports=5555
> 
3. restart apollo

This way, dreamview can be accessed from http://localhost:<PORT_NUMBER> (http://localhost:5555 from the example)

**Comment by vlin17** [comment]
Seems like no more question is raised, closing this issue for now. Please feel free to reopen or create a new one if you have any additional questions.

**Comment by hawl666** [comment]
@vlin17 i add the '--server_ports=5555' to  modules/dreamview/conf,but Dreamview is still running at http://localhost:8888
