### ISSUE TITLE
Switching lanes in custom created map

### ISSUE THREAD

**Issue by lunden16** [ApolloAuto/apollo#4008]
Hi! I've created a map according to the modified opendrive standards of Apollo and want to run it in dreamview. Everything works except the car can't route between lanes, eg. all I want it to do is to change from lane -1 to lane -2. I've tried adding them as neighbours and in different constellations of laneOverlapGroups but nothing has worked thus far. The road is a 100m long straight. Any tips?

Cheers!

**Comment by antonfrigard** [comment]
I also have problems with this. Do sampleAssociations/sampleAssociates have something to do with it? Would be grateful for a nudge in the right direction.

**Comment by lianglia-apollo** [comment]
Please check the results of routing and verify "ChangeLaneType" is marked correctly.

**Comment by antonfrigard** [comment]
If I put a start and an end point on different lanes and echo the routing_response topic I get this (the bit that regards ChangeLaneType):
passage {
    segment {
      id: "r1_1_-1"
      start_s: 27.9878144234
      end_s: 151.903990194
    }
    change_lane_type: RIGHT
  }
  passage {
    segment {
      id: "r1_1_-2"
      start_s: 27.9878144234
      end_s: 151.903990194
    }
    can_exit: true
    change_lane_type: FORWARD
  }

I get a routing success and the car moves, but only in the lane in which I choose the starting point. I get one red routing line in each lane. In the base_map.xml file I have two identical laneOverlapGroups, one roughly at the end of the first lane declaration and one roughly at the end of the second lane declaration. The road is a 1000 meter long straight and the overlap stretches the entire distance. When I generate the routing and sim map, there seems to be no error and the number of overlaps is 3.

**Comment by kk2491** [comment]
@antonfrigard @lunden16 Guys, were you able to fix this issue ? Even I am stuck at the same point.

Thank you,
KK
