### ISSUE TITLE
Apollo Demo 1.5 can't select profile and can't open Dreamview

### ISSUE THREAD

**Issue by Gavin2318** [ApolloAuto/apollo#401]
I have built the Apollo successfully,  and able to open http://localhost:8887/. 
It pops up profile section as the picture below:

<img width="1621" alt="screen shot 2017-09-24 at 11 17 46" src="https://user-images.githubusercontent.com/9253996/30779125-114adade-a11a-11e7-9002-62b45a86dbcf.png">

<b>But I am not able to select anything in these 2 dropdown.</b>
I have to skip the selection and click ok.  Then when I click Dreamview to start, <b>the Dreamview page can't be open</b>:

<img width="1605" alt="screen shot 2017-09-24 at 10 55 38" src="https://user-images.githubusercontent.com/9253996/30779040-f049b0a6-a116-11e7-85ff-5faa6f6114fe.png">

**Comment by xiaoxq** [comment]
Could you post your data/log/hmi.out?
It will show information about what goes wrong. Generally it's because of data missing or writing permission issue.

**Comment by Gavin2318** [comment]
@xiaoxq Hi, I checked the data/log/hmi.out, there is no content inside. 
But I think it might be the writing permission issue as you mentioned, because I can't run `docker ps` without sudo.
What should I do to fix this? Thanks!

**Comment by xiaoxq** [comment]
It's a common problem. Please refer to
https://docs.docker.com/engine/installation/linux/linux-postinstall/

We also provide a helpful script:
https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/install_docker.sh

**Comment by fy2462** [comment]
@Gavin2318 you can select the profile with chrome browser, but it does't work well in dreamView simulator now. My chrome version is "Version 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit)".

**Comment by Gavin2318** [comment]
@xiaoxq I am able to run` docker ps` without sudo successfully now. But the issue remains same. 
But when I run `bash scripts/hmi.sh`, I still need to use sudo.
p.s. There is no content inside data/log/hmi.out also

**Comment by xiaoxq** [comment]
What did it say when you run without sudo?

For the sake of security we never run HMI with sudo.

**Comment by westeast** [comment]
@fy2462 run it on chrome not chromium.  I have the same problem on chromium but no problem on  chrome

**Comment by xiaoxq** [comment]
This issue is closed as it becomes stale. Please file a new one if it's not figured out.
