### ISSUE TITLE
How to execute the IMU calibration?

### ISSUE THREAD

**Issue by meteor0530** [ApolloAuto/apollo#4020]
Hi,
My apollo is 2.0.0 version.
I use NovAtel SPAN® ProPak6™ with IMU-CPT, so I change the configuration in [https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md](url) from `CONNECTIMU COM3 IMU_ADIS16488` to `CONNECTIMU COM3 IMU_KVH_COTS`, and the INS led on NOVATEL changes to constant amber, it seems that the IMU need have a alignment.
I look at the scripts/sensor_calibration.sh and do not find `imu_vehicle` option as the guide say.
I download the calibration tool and don't know how to use.

Looking forward to help, thanks!

**Comment by bbidault2** [comment]
Hello @meteor0530, 

I believe you need to initialize your IMU azimuth by adding the following commands to your `gnss_conf_mkz.txt` file.

```
login_commands: "SETINITAZIMUTH X 10\r\n"
```

With X the angle (in degrees) the y axis of your IMU is pointing toward. 0 degrees being north.

**Comment by meteor0530** [comment]
@bbidault2 Thanks, I will have a try.

**Comment by meteor0530** [comment]
@bbidault2 I use SETINITATTITUDE instead of SETINITAZIMUTH, and it seems work well, the GPS light turns green. But I cant start the localization module.

**Comment by meteor0530** [comment]
@bbidault2 Thanks for the help, I have solved it.
