### ISSUE TITLE
How to add a python subnode?

### ISSUE THREAD

**Issue by lengly** [ApolloAuto/apollo#4022]
We know how to add a c++ subnode, but some of our model is based on python. Is it possible to add a python subnode? Do you have any docs?

**Comment by lianglia-apollo** [comment]
Please see the examples in ROS tutorials: http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29

**Comment by lengly** [comment]
@lianglia-apollo   I think it's python node, not subnode. I mean use python to communicate with c++ through shared memory, just like what c++ subnode does

**Comment by natashadsouza** [comment]
@lengly we do not presently support using python to communicate using shared memory. If it is something you are presently working on, it would be great to share your progress. Thank you!

**Comment by quning78** [comment]
Closed. Reopen if you still have questions.
