### ISSUE TITLE
There is no traffic lanes in Appollo 1.5 demo.

### ISSUE THREAD

**Issue by Eddy-W** [ApolloAuto/apollo#404]
I have built apollo v1.5 successfully. But when I ran the command
```bash
rosbag play ./docs/demo_guide/demo_1.5.bag --loop
```
There were still no road or no lane in the Dreamview used Firefox as the figure shows below, rather than the [dv_trajectory_1.5.png](https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/images/dv_trajectory_1.5.png) that we expect to show all information including traffic lanes and signals.
Please tell me did I play a wrong bag file or run a wrong command? Thanks.
![](https://user-images.githubusercontent.com/7567546/30789858-f8636dd0-a1da-11e7-83af-86d08fb691c3.png)

**Comment by siyangy** [comment]
Take a look at this file: https://github.com/ApolloAuto/apollo/blob/master/modules/common/data/global_flagfile.txt. You might be using a wrong map data file.

**Comment by Eddy-W** [comment]
But I didn't find the map data file "modules/map/data/sunnyvale_loop" in the apollo github repository.
In my case, I loaded demo map as the /apollo/data/log/dreamview.INFO shows
```
pnc_map.cc:85] map loaded, Map file: modules/map/data/demo/base_map.txt
```

**Comment by startcode** [comment]
@Eddy-W  "modules/map/data/sunnyvale_loop" is not in github repo. It is loaded by docker. You should be able to see this folder inside docker.

**Comment by Eddy-W** [comment]
It works. Thanks.
