### ISSUE TITLE
CNN segmentation run on PX2

### ISSUE THREAD

**Issue by Yanzqing** [ApolloAuto/apollo#4044]
We have tested the cnn segmentation model on PX2, but it costs more than 500ms per frame.
Maybe the cnn segmentation model needs to be optimized on PX2?

**Comment by hzdsdhr** [comment]
Hi @Yanzqing , I also try to run cnn segmentation on PX2, and found the same case(cost more 600ms) for one frame). Have you figured why and any solution for this?

**Comment by hzdsdhr** [comment]
I'm thinking if it's a CPU problem or GPU problem. By checking using "top", I found that the cpu usage is almost 100% all the time. Maybe the cpu is not strong enough? I'm not sure.
