### ISSUE TITLE
track driving

### ISSUE THREAD

**Issue by Lewis1992** [ApolloAuto/apollo#4045]
If I want to drive track, how to operate on Dreamviewer?

**Comment by unacao** [comment]
Could you elaborate a bit more on what you would like to achieve?

**Comment by unacao** [comment]
After switching to the "RTK Record/Replay" mode, you can focus on the "Tasks"->"Quick Start" panel.
Click "Setup" button to start the required modules. You can double check the "Modules" status in "Module Controller". They should be turned on.
Drive your car to the desired starting point and click "Record"->"Start" to start recording the geo data points. Click "Record"->"Stop" after reaching your destination. The data points will be saved in a file.
Go back to your starting point, and click "Replay"->"Start" to allow auto-driving based on the previous track. The location and heading of your car should be as close to the previous starting pose as possible to avoid undesirable behavior such as sudden swerve or unable to find a close geo point.

Here is a doc from previous release for your reference. The UI may look different but the functionality is similar. https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.
