### ISSUE TITLE
localhost/Dreamview not working

### ISSUE THREAD

**Issue by SyedShaQutub** [ApolloAuto/apollo#4047]
I tried looking at older threads about the same issue but nothing solves mine. 

-> **Build process says "success" except some errors like :** 
  INFO: From Executing genrule //modules/drivers/pandora:pandora_genrule:
CMake Error at cmake_install.cmake:54 (FILE):
  file INSTALL cannot copy file
  "/tmp/build_isolated/pandora_driver/catkin_generated/installspace/_setup_util.py"
  to "/home/tmp/ros/_setup_util.py".

-> **Also my dreamview.out file is empty to trace the issue it has.**

-> **"ps -ef | grep dreamview" - gives me** 
    $user   15865    50  0 16:33 pts/19   00:00:00 grep --color=auto dreamview

-> **"./scripts/dreamview.sh" start_fe throws** 
    /apollo/scripts/apollo_base.sh: line 305: 15873 Illegal instruction     /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --alsologtostderr --log_dir=/apollo/data/log

Help is really appreciated :)

**Comment by vlin17** [comment]
Hi @SyedShaQutub,

With the given information, it seems like a ROS installation issue. Are you using the docker env we provide? 

Could you run "ps -ef | grep ros" to see if your roscore and rosmater processes are running? If not, we need to see why, and according to the CMOS error you posted, maybe this [one](https://answers.ros.org/question/263120/ros-kinetic-catkin_make-install-fails/) or this [one](https://github.com/ros/catkin/issues/500) can help.

**Comment by SyedShaQutub** [comment]
Hi @vlin17,

Yes the ros cores are running perfectly fine.  


120     1  1 08:17 pts/19   00:00:00 /usr/bin/python /home/tmp/ros/bin/roscore

157   120  2 08:17 ?        00:00:00 /usr/bin/python /home/tmp/ros/bin/rosmaster --core -p 11311 -w 3 __log:=/home/user/.ros/log/8419c094-4dd0-11e8-b84f-d4ae52c072a6/master.log

188   120  1 08:17 ?        00:00:00 /home/tmp/ros/lib/rosout/rosout __name:=rosout __log:=/home/user/.ros/log/8419c094-4dd0-11e8-b84f-d4ae52c072a6/rosout-1.log

 243    50  0 08:18 pts/19   00:00:00 grep --color=auto ros

**Comment by SyedShaQutub** [comment]
And please confirm is this normal. Normally it should be running without exiting the Dreamview, right ?


**qutub@in_dev_docker:/apollo$ bash scripts/bootstrap.sh**
Started supervisord with dev conf
Start roscore...
voice_detector: started
Dreamview is running at http://localhost:8888
**qutub@in_dev_docker:/apollo$**

**Comment by zhxt** [comment]
@SyedShaQutub Hi, could you please paste:
1. the gdb backtrace of dreamview;
2. the output of  `grep flags /proc/cpuinfo  | uniq`.

since you've got the error: `Illegal instruction`.
Simply you can get gdb backtrace with:
```
source scripts/apollo_base.sh
start_gdb dreamview
```
Once gdb is launched, press `r` and `enter` key to run,  if dreamview is crashed, then get the backtrace with `bt`.

If you find something related with lib pcl in the backtrace, you may want [this](https://github.com/zhxt/apollo/wiki/FAQ) and #3615 and [logs from IRC](https://apolloauto.io/logs/%23apolloauto.2018-05-02.log.html).

**Comment by zhxt** [comment]
@vlin17 Eventually, I have found some clues about `Illegal instruction`, I have put them in the comment of issue #3615.

And how do you think about to removing the log redirection in:
https://github.com/ApolloAuto/apollo/blob/8be5f938c594b115d7ec30a57965504d67273fc4/scripts/bootstrap.sh#L41

Then, the developers can get the errors immediately if dreamview fails to start.

**Comment by SyedShaQutub** [comment]
Hi all,

Continued the process, and now stuck with this issue

`terminate called after throwing an instance of 'CivetException'
  what():  null context when constructing CivetServer. Possible problem binding to port.
`

The issue is explained in the page 

 [(https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md  )]

but this doesn't solve my issue. A direction to solve this is much helpful to me at this stage.

PS : 
I have edited the TCP listening port to 8888 (docker.service) as suggested by Apollo - the post installation of docker

**Comment by SyedShaQutub** [comment]
Hey, its working... happiest person right now.

Thanks guys for all your support. Cheers

May be this could be useful to others. 

Lesson learnt : 
follow the post installation steps of docker for linux except don't edit the daemon.json or docker.service file. This could be different with other users if they have changed the local server listening port in other packages.

**Comment by zhxt** [comment]
@SyedShaQutub Great, you got it worked.

@vlin17  Okay, I will update the docs.

**Comment by zhxt** [comment]
PR created #4088 .

**Comment by vlin17** [comment]
Thank you all for the contribution. Since the issue has been resolved and documented, we will close the issue for now. If you have any additional question, please feel free to open a new issue.
