### ISSUE TITLE
Obtaining the Apollo OpenDrive specifications

### ISSUE THREAD

**Issue by popeyedpanther** [ApolloAuto/apollo#4048]
Is there a more official way of receiving the Apollo OpenDrive specifcations other than posting in #3005? 
Thanks

**Comment by natashadsouza** [comment]
Please use the link mentioned [here](https://github.com/ApolloAuto/apollo/issues/3005#issuecomment-415837922) to request for the Apollo OD specification document.
Thanks!

**Comment by akn9017** [comment]
@natashadsouza and @Zhenni17 I have submitted the survey to request for the specifications several times, but have not yet received the specifications. Are you still using the link to provide for the specs? Else, can you please send the Apollo OpenDrive spec document to [akn902017@gmail.com](mailto:akn902017@gmail.com)?

**Comment by daohu527** [comment]
Here is the Apollo OpenDrive specification https://github.com/ApolloAuto/apollo/discussions/15117
