### ISSUE TITLE
running apollo 2.0 perception module with rosbag?

### ISSUE THREAD

**Issue by yuconglin** [ApolloAuto/apollo#4050]
Is it possible to run apollo 2.0 perception module with replaying a bag file like in apollo 2.5 instead of generating pcd and pose files?

**Comment by gengqx** [comment]
by this link you could dowload apollo1.5 and apollo2.0 data ,the total data would be 12.1GB. the apollo 2.0 data would be 3.2GB
[apollo data open platform](http://data.apollo.auto/help?name=data-sensor%20demostration-user%20guide&data_key=sensor&data_type=1&locale=zh-cn&lang=en)

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
