### ISSUE TITLE
apollo build take a long time，have some problems in my environment ?

### ISSUE THREAD

**Issue by 854619267** [ApolloAuto/apollo#4055]
I build the project in ubuntu 16.04 lts at VMWARE.  here is console disp:

INFO: Analysed 1468 targets (12 packages loaded).
INFO: Found 1468 targets...
[1,289 / 1,294] 2 actions running
    Compiling .../common/transform_listener/transform_listener.cc; 3872s local
    Compiling  modules/common/adapters/adapter_manager,cc; 3872s local

**Comment by Mohamed-BB** [comment]
I am having the same issue, does it usually take long to build @Zhenni17

**Comment by 854619267** [comment]
in my case，the reason is hard disk is full
