### ISSUE TITLE
[Announcement] Apollo's official blog is launching on Medium.com! Subscribe it today! 

### ISSUE THREAD

**Issue by Zhenni17** [ApolloAuto/apollo#4056]
Dear Apollo Developers,

We are proud to announce that Apollo's official blog is launching on Medium today at **medium.com/apollo-auto**. Read our first blog post: Deep Dive on Apollo 2.5. Subscribe us if you'd like to be notified for future posts!

We start this blog to better serve our developer community. New articles will be posted 1-2 times per month, and it will focus on various technical topics that will help our developers to better understand and use Apollo. Please leave a comment here if you have particular topics that you would like us to cover, and vote for your favorite topics!

Yours,
Zhenni 
Community Manager | Apollo Platform

**Comment by poutyface** [comment]
I want apollo team to have a meet up in Japan.

**Comment by Zhenni17** [comment]
Hi @poutyface ， can you please send me an email at wuzhenni01@baidu.com where we can connect and discuss the potential of possibly doing a meet up in Japan? :)

**Comment by Peter9606** [comment]
Happy to see there are more and more activities both online and offline. 
@Zhenni17 , you might know that from PRC, we cannot access medium.com, so could you also have a counterpart of that for PRC local users?

**Comment by Zhenni17** [comment]
Hi @Peter9606 , thank you for pointing out that information. I actually was not aware of that issue. I will work with our China team to publish the blog on our official WeChat account. Hope that will help! Please let me know if you have any additional question.
