### ISSUE TITLE
problem in building "elo" module

### ISSUE THREAD

**Issue by EthanYee** [ApolloAuto/apollo#406]
Hi, I'm interesting in your "elo" module, but problems came across when I try to build the project, which says "../lib/libcamera_localization.so: error adding symbols: File in wrong format". I've installed the required dependencies. Would you help to fix the problem?

**Comment by startcode** [comment]
These *.so files in elo are built for aarch64 platforms.

**Comment by EthanYee** [comment]
Can you build another dynamic library for x86 platforms?

**Comment by startcode** [comment]
I will forward your question to elo guys and update in this thread when we have a solution. Thanks.

**Comment by startcode** [comment]
Our ELO team will support X86 architecture soon. Keep tuned.

**Comment by ankitvora7** [comment]
Any updates on this ? When do you think you guys will come out with support on x86 architecture ??

**Comment by natashadsouza** [comment]
Sorry we could not get back to you on this request. Please let me know if you still need support on your request. Feel free to re-open the issue.
