### ISSUE TITLE
I'm interested in adding SDR capabilities to Apollo or Vice-Versa

### ISSUE THREAD

**Issue by WindyCitySDR** [ApolloAuto/apollo#4060]
Hello,

I just came back from "Silicon Valley" where I have the interest of a Automobile Manufacturer and would like to add Software Defined Radio capabilities to Apollo's Autonomous Open Vehicle System  as a SDR device can either generate and/or receive GOS signals and some other stuff already implemented in your code.

Do you have instructions on installing your software WITHOUT DOCKER 🤔?

Docker just is too heavy and again, I •think• I can "blend" some of Apollos features into the SDR stuff I've been doing for awhile now as you can see here:  http://twitter.com/WindyCitySDR

Please assist.

Sincerely,

WindyCitySDR

**Comment by xiaoxq** [comment]
Yes, it's possible, though not recommended.

You can follow the Dockerfile to build up your environment step by step:
https://github.com/ApolloAuto/apollo/blob/master/docker/build/dev.x86_64.dockerfile

**Comment by WindyCitySDR** [comment]
Xiaoxq,


Thank you for replying!
