### ISSUE TITLE
Can not start the localization module.

### ISSUE THREAD

**Issue by meteor0530** [ApolloAuto/apollo#4062]
Hi,
I'm using apollo 2.0.0 version. My GPS is  NovAtel SPAN® ProPak6™ with IMU-CPT. After some configurations, the GPS module light turned green. Then i try to start the localization module but failed. I check rostopic and find data in `/apollo/sensor/gnss/corrected_imu`. But i cant find data in `/apollo/sensor/gnss/imu` using `rostopic echo`.
Is that the problem why I cant start the localization module?
Need some help, thank you.

**Comment by gengqx** [comment]
you can try 
```
bash scripts/llocalization.sh
```
if you have build it success,even if it failed,you could find the failed log in the data/log.

**Comment by meteor0530** [comment]
@gengqx thank you for your response.
I used script to start, and it failed again. I looked at localization.WARING, localization.FATAL, localization.ERROR, localization.INFO and they all show
 `F0503 10:08:57.974390  1530 velodyne_locator_omp_alt_align.cc:170] Reflectance map folder is invalid!`
How can I solve it?

**Comment by gengqx** [comment]
Due to the new apollo 2.5,it use MSF location method as default,so you need modify modules/localization/conf/localization_config.pb.txt
Replace MSF with RTK

**Comment by meteor0530** [comment]
@gengqx thanks a lot for your help.
I have solved it.
