### ISSUE TITLE
Question: Why need two speed optimizers in planning_config.pb.txt

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#4069]
In file /apollo/modules/planning/conf/planning_config.pb.txt, it includes two speed optimizers:
```
...
    task : DP_ST_SPEED_OPTIMIZER

    task : SPEED_DECIDER

    task : QP_SPLINE_ST_SPEED_OPTIMIZER
...
```
If we remove QP_SPLINE_ST_SPEED_OPTIMZER, the car does not move.

**Comment by jilinzhou** [comment]
It is also noticed that QP_SPLINE_PATH_OPTIMIZER is not registered with any planner.

**Comment by lianglia-apollo** [comment]
The DP_ST_SPEED_OPTIMIZER is for decision purposes. QP_SPLINE_ST_SPEED_OPTIMIZER will generate the quantitative trajectory.

Currently, we don't use QP_SPLINE_PATH_OPTIMIZER. Only poly_path is used.
