### ISSUE TITLE
不同的ros node运行在不同的电脑上的通信问题

### ISSUE THREAD

**Issue by kuangjx** [ApolloAuto/apollo#4080]
将不同的ros node运行在不同的电脑上，无法收到对方的信息，将ROS_DOMAIN_ID设成一样，也无法收到对方信息，请问要如何配置ROS，才能解决问题。

**Comment by berthu** [comment]
可能要提供一下代码才好说问题在哪

**Comment by chaii** [comment]
Can you share the details of your set up that we can investigate the issue? Are you trying to start Apollo containers in different hosts and try to make Apollo modules between different hosts to communicate across hosts?

**Comment by natashadsouza** [comment]
Closing this issue as ROS is no longer supported and also the thread has been inactive in a while. Thanks!
