### ISSUE TITLE
Frame::CreateDestinationObstacle() is called in every loop once the ego_vehicle is on the last route segment

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#4082]
In _bool Frame::CreateReferenceLineInfo()_, _Frame::CreateDestinationObstacle()_ is called in every loop once the ego_vehicle is on the last route segment as the following:

```
bool Frame::CreateReferenceLineInfo() {
...

  reference_line_info_.clear();
  bool near_destination = false;
  auto ref_line_iter = reference_lines.begin();
  auto segments_iter = segments.begin();
  while (ref_line_iter != reference_lines.end()) {
    if (segments_iter->StopForDestination()) {
      near_destination = true;
    }
    reference_line_info_.emplace_back(vehicle_state_, planning_start_point_,
                                      *ref_line_iter, *segments_iter);
    ++ref_line_iter;
    ++segments_iter;
  }
  if (near_destination && CreateDestinationObstacle() < 0) {
    AERROR << "Failed to create the destination obstacle";
    return false;
  }
...
}
```

In _CreateDestinationObstacle()_, it checks the newest routing response and creates a 2d box to represent a virtual obstacle object.

```
int Frame::CreateDestinationObstacle() {
  const auto &routing =
      AdapterManager::GetRoutingResponse()->GetLatestObserved();
  if (routing.routing_request().waypoint_size() < 2) {
    ADEBUG << "routing_request has no end";
    return -1;
  }
  const auto &routing_end = *routing.routing_request().waypoint().rbegin();
  const auto lane = hdmap_->GetLaneById(hdmap::MakeMapId(routing_end.id()));
  if (!lane) {
    AERROR << "Failed to find lane for destination : "
           << routing_end.ShortDebugString();
    return -2;
  }

  double dest_lane_s =
      std::max(0.0, routing_end.s() - FLAGS_virtual_stop_wall_length -
                        FLAGS_stop_distance_destination);
  auto dest_point = lane->GetSmoothPoint(dest_lane_s);
  double left_width = 0.0;
  double right_width = 0.0;
  lane->GetWidth(dest_lane_s, &left_width, &right_width);
  // check if destination point is in planning range
  Box2d destination_box{{dest_point.x(), dest_point.y()},
                        lane->Heading(dest_lane_s),
                        FLAGS_virtual_stop_wall_length,
                        left_width + right_width};
  // add destination's projection to each reference line info
  AddStaticVirtualObstacle(FLAGS_destination_obstacle_id, destination_box);
  return 0;
}
```

If the destination is not changed, there is no need to create this virtual object in every loop. In fact, the newly created object is not going to be added to the static virtual obstacle list anyway (_AddStaticVirtualObstacle()_) if it is already existed with the same id. It is better to  remember what the current destination is and update the virtual obstacle only when it is changed.

**Comment by jilinzhou** [comment]
The code snippet was from r.2.0.0 branch. It seems the current master branch behaviors pretty much the same.

**Comment by jmtao** [comment]
@jilinzhou this is as designed. Each frame, we'd set up all the obstacles (physical ones based on perception, and virtual ones based on our rules and logic) from scratch. We may remember some info about obstacles from previous frame, just to smooth unexpected and unwanted perception jumps.  But all the obstacles are created fresh in each frame. 

If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open a new issue if you have any more questions. 

Thank you for supporting Apollo!

**Comment by jilinzhou** [comment]
It is fine if by design. However, the final destination is not something changing all time (very different from those on-route dynamic objects).  It can save some computation cycles to create the axis-aligned bounding box every frame for this virtual obstacle.
