### ISSUE TITLE
Different `clazz` with the same `name` will compile failed 

### ISSUE THREAD

**Issue by wlwu92** [ApolloAuto/apollo#4089]
https://github.com/ApolloAuto/apollo/blob/846f4adb5ceb8424f3e289ec55ec4d19cd8518ab/modules/perception/lib/base/registerer.h#L178

**Comment by eugenegx** [comment]
@wlwu92 Can you explain more about this issue? This is a macro for object factory, so it's correct that only one unique "Object Factory [name]" can exist

**Comment by eugenegx** [comment]
Closed
