### ISSUE TITLE
Multiple-LiDAR GNSS Calibration

### ISSUE THREAD

**Issue by changduanyu** [ApolloAuto/apollo#4092]
Hi there,

I was trying the new released Multiple-LiDAR GNSS Calibration guide with my own data. Unfortunately, I got a problem, the data export suceeds but the calibration fails. 

* The terminal gives: ![apollo_calibration](https://user-images.githubusercontent.com/18718496/39672142-23120aa6-5157-11e8-99e5-4eaf25369b54.png) It seems that the point cloud data is empty, but when I checked the *.pcd file in the export, it actually shows the point cloud, which means the calibration tool can not read the data.

* This is how i did it:
    * the type of the published odometry topic is pb_msgs/Gps, therefore, I converted my odometry into pb_msgs/Gps format in the docker.
    * and the type of published point cloud is the standard sensor_msgs/PointCloud2. However, a new point struct is used in the point cloud 
struct PointXYZIT {
  PCL_ADD_POINT4D
  uint8_t intensity;
  double timestamp;
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW  // make sure our new allocators are aligned
} EIGEN_ALIGN16;  
I convert my pointcloud into this format and set intensity to zero.
    * then I just follow the guide here https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/multiple_lidar_gnss_calibration_guide.md   it gives this problem

Does anyone knows why?

a lot thanks!

**Comment by changduanyu** [comment]
Hi,

1. When we do multi-lidar gnss calibration, there is config file multi_lidar_gnss_calibrator_config.yaml containing initia extrinsic guess as shown in the pic
![initialextrinsics](https://user-images.githubusercontent.com/18718496/40286990-163e5c94-5cdd-11e8-9ae5-4a40cdd9d996.png)

Does anyone know how to get the initial guess and how the initial guess affect the performance of the calibration?

2. the multi-lidar gnss calibration uses hand-eye algorithm followed by GICP. A question here is: how to get the pose using point cloud, using point cloud slam?

I would appreciate it if anyone could answer my question!!!

**Comment by xiaoxq** [comment]
Please check https://apollo.auto/ for our cloud service of calibration.
