### ISSUE TITLE
What data is the CNN model trained with?

### ISSUE THREAD

**Issue by JoaquinBur** [ApolloAuto/apollo#4098]
Is the CNN trained using data from the USA?
Would the CNN model work on a 32 channel lidar instead of a 64?

**Comment by JoaquinBur** [comment]
@techoe

**Comment by JoaquinBur** [comment]
@techoe What framework (Caffe or Caffe2) was used to train the neural net? 
Thanks.

**Comment by techoe** [comment]
US data is not included in the current training data. We will add more data from US soon.
