### ISSUE TITLE
how to launch planning and control module?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4106]
Hi Apollo team,

I see there are scripts in /apollo/script/planning.sh and /apollo/script/control.sh.
I also see binary files in bazel-bin
How do I run modules?

**Comment by lianglia-apollo** [comment]
You can use the following script for planning:
/apollo/bazel-bin/modules/planning/planning --flagfile=modules/planning/conf/planning.conf --log_dir=/apollo/data/log --v=4

**Comment by wckorealsh** [comment]
I got this error
`/apollo/bazel-bin/modules/planning$ ./planning --flagfile=/apollo/modules/planning/conf/planning.conf --log_dir=/apollo/data/log --v=4
modules/common/data/global_flagfile.txt: No such file or directory
`

Looks like it does not know `modules/planning/` but it knows `/apollo/modules/planning`. Dut to similar reason, it cannot find global_flagfile.txt. How do set path correctly?

**Comment by wckorealsh** [comment]
Got it fixed, thank you!

**Comment by lianglia-apollo** [comment]
--v=4 is for glog (output debug level logs).
