### ISSUE TITLE
Bug maybe: Image left/up_idx mismatch left/up_val

### ISSUE THREAD

**Issue by Gvain** [ApolloAuto/apollo#4108]
https://github.com/ApolloAuto/apollo/blob/dd67f7b5a3aa9d760123e9b0f49f6e791378be1a/modules/perception/obstacle/camera/lane_post_process/common/connected_component.cc#L758

Maybe exchange between left_val & up_val as corresponding to left/up_idx.
left_val = prev_p[x];
up_val = cur_p[x-1];

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
