### ISSUE TITLE
implementation question about integrating Apollo's path planning into a VISSIM simulation

### ISSUE THREAD

**Issue by popeyedpanther** [ApolloAuto/apollo#4112]
I am looking to integrate Apollo’s decision making/path planning into a VISSIM simulation. The result should be similar to Apollo’s simulator but the focus is on the traffic rather than the vehicle’s performance.

http://vision-traffic.ptvgroup.com/en-us/products/ptv-vissim/

VISSIM provides a driving simulator API that returns a vehicle list (pedestrians list also if wanted) and then waits for position, speed and orientation data from the driving simulator before calculating the next iteration of the VISSIM simulation.

 I see there is a mock clock in Apollo that allows you to manually set the time. Does Apollo’s modules support this kind of discrete stepping in time? Will using the mock clock to increment time after each VISSIM return work? 

Any advice?

Thanks

**Comment by startcode** [comment]
I think you might want to take a look at the `sim_control` module.
 https://github.com/ApolloAuto/apollo/tree/master/modules/dreamview/backend/sim_control
It simulates the movement of the AV based on planning trajectory.

**Comment by popeyedpanther** [comment]
Thanks @startcode. I think that will come in handy.

**Comment by Zhenni17** [comment]
@popeyedpanther hope @startcode answered your question. Close the issue for now, and please start an new issue if you have any additional questions. Good luck with your project! :)
