### ISSUE TITLE
SimControl runs without running control module. Why?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4113]
Hi Apollo team,

I've been playing around with Dream Viewer SimControl. 
I found that simulation running by enabling the routing module and planning module without enabling the control module. But I see that the control signal is generated somehow. Can you please explain what makes the vehicle move when the control module was not enabled?

Thank you!

**Comment by lianglia-apollo** [comment]
It receives output from planning and simulate a perfect control according to the planning trajectory.

**Comment by wckorealsh** [comment]
Thank you @lianglia-apollo 

Then how do we test control in SimControl mode?

**Comment by lianglia-apollo** [comment]
We currently cannot test control in simulation. The control module needs to be tested on vehicles.

**Comment by wckorealsh** [comment]
I see, thank you!
