### ISSUE TITLE
What is the difference between base_map.txt and base_map.xml?

### ISSUE THREAD

**Issue by ImCabbage** [ApolloAuto/apollo#4121]
I see there are both base_map.txt and base_map.xml in the map folder. And I see there is one python script which translates between txt and bin files.  So what is the difference between txt file and xml file. Does apollo routing module only recognize the xml file or it can do both? Or maybe the xml file is generated using base_map.txt and routing_map.txt? I am a little bit confused.
Does any one know?

**Comment by jinghaomiao** [comment]
base_map.txt is in proto format and base_map.xml is in opendrive data format.

**Comment by ImCabbage** [comment]
Hi, Calvin
Thanks for your reply. But my question is either base_map.txt or
base_map.xml should be enough on your platform, right? Or we have to have
the xml version of the map file?
Because I see that you have opened your base_map.txt generation method but
the xml version map is still in private.

Best Wishes,
Hao

**Comment by startcode** [comment]
> But my question is either base_map.txt or
base_map.xml should be enough on your platform, right?

Right

**Comment by msbeta** [comment]
base_map.xml is HDMap with Baidu OpenDrive format, base_map.bin and base_map.txt are HDMaps with the Apollo internal data format, base_map.txt is a visualization of the contents of the base_map.bin binary file. so far, this three files are consistent in the content,but in different formats, so you can use any of these three files in the whole project.
