### ISSUE TITLE
Failed to create CAN checker

### ISSUE THREAD

**Issue by Qdriving** [ApolloAuto/apollo#4125]
Hi all,

      After run apollo successful I cannot reach localhost:8888, then I checked the log in /data/log see that there are 2 ERROR logs, and get the information as 
   "E0509 09:05:04.986534   344 can_checker_factory.cc:48] Failed to create CAN checker with parameter: brand: ESD_CAN
type: PCI_CARD", 
I know that I need a ESD CAN card, but here I just want to simulate it, how can I skip this?

     Help is really appreciated :)
Thanks!

**Comment by jinghaomiao** [comment]
@Qdriving you don't need to check CAN if you want to launch dreamview. The failure to launch dreamview has nothing to do with the failure to  create a CAN checker.

**Comment by Qdriving** [comment]
@jinghaomiao ,thanks for your support. I know what you mean, but how can I disable the CAN checker or can I ignore it?

Thanks.

**Comment by natashadsouza** [comment]
@Qdriving you can ignore it if you are not testing the code on a Car. Thanks!
