### ISSUE TITLE
Does Dreamview visualized the vehicle position from planning or control?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4126]
Hello Team Apollo,

It looks like the vehicle visualized in Dreamview is from the output of the planning module (position and heading) not from the control module (position and heading computed by control). Is this in SimControl mode only or always?
Thank you

**Comment by siyangy** [comment]
Yes, this is SimControl only, if you take a closer look, it publishes localization/chassis messages to give Dreamview input about where the car is. While in a real car, control module will actually control the car and thus affect localization/chassis messages published to Dreamview.

**Comment by wckorealsh** [comment]
Thank you, can you please advice on how to test controller without the real vehicle if there is any?
I would like to test my controller before running into the vehicle. Otherwise, it does not really make sense.

**Comment by siyangy** [comment]
Loop in @Capri2014 for help as I am not a control expert.

**Comment by lianglia-apollo** [comment]
I think we haven't open sourced the offline method to test control module. You will need to test control directly on a vehicle or implement your own method.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. If you have additional questions @wckorealsh feel free to open this thread. Thanks!
