### ISSUE TITLE
Unused member variable vehicle_state_ in class ReferenceLineInfo

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#4128]
Here is the constructor:

```
ReferenceLineInfo::ReferenceLineInfo(const common::VehicleState& vehicle_state,
                                     const TrajectoryPoint& adc_planning_point,
                                     const ReferenceLine& reference_line,
                                     const hdmap::RouteSegments& segments)
    : vehicle_state_(vehicle_state),
      adc_planning_point_(adc_planning_point),
      reference_line_(reference_line),
      lanes_(segments) {}
```

The member variable _vehicle\_state\__ is initialized but never referenced anywhere in the class.

**Comment by jmtao** [comment]
@jilinzhou If you search: 
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/reference_line_info.cc
vehicle_state_ is used by this method:
`
void ReferenceLineInfo::ExportEngageAdvice(EngageAdvice* engage_advice) const ();
`

**Comment by jilinzhou** [comment]
Sorry, my mistake. I am still in r2.0.0 branch.
