### ISSUE TITLE
Can we install ros package inside Apollo dev container?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4139]
Hi Apollo team,

I have installed some ros packages(rqt_plot)  in apollo_dev container.
It look like it is installed correctly 
```
sudo apt-get install ros-indigo-rqt-plot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-indigo-rqt-plot is already the newest version.
```

But I am not able to run `rqt_plot`(`bash: rqt_plot: command not found
`) , and  it does not show up in `rospack list`.
It is not in `home/tmp/ros/share` either. 
Is it possible to install ros package in apollo_dev? If so, what am I missing?

Thank you!!

**Comment by layssi** [comment]
Did you source "source /opt/ros/indigo/setup.bash"?

**Comment by GPrathap** [comment]
Any update on this?

**Comment by gladijos** [comment]
Same issue but with package with custom messages. I have to build it inside docker with catkin_make, after this copy headers to /home/tmp/ros/include and after this run source ~/catkin_ws/devel/setup.bash.
It works up to relaunch docker container.

**Comment by quning78** [comment]
Closed. Reopen if you still have questions.
