### ISSUE TITLE
building issue-in visual studio code

### ISSUE THREAD

**Issue by billzhj** [ApolloAuto/apollo#4140]
when building the project in visual studio code,  here is the problem. Terminal's printing as follows:

Executing task: bash apollo_docker.sh build <

System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
Building: no action running
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Loading:
Loading: 0 packages loaded
Analyzing: 2091 targets (0 packages loaded)
Analyzing: 2091 targets (4 packages loaded)
Analyzing: 2091 targets (5 packages loaded)
Analyzing: 2091 targets (5 packages loaded)
Analyzing: 2091 targets (5 packages loaded)
Analyzing: 2091 targets (11 packages loaded)
Analyzing: 2091 targets (12 packages loaded)
ERROR: /apollo/bazel-apollo/modules/tools/manual_traffic_light/BUILD:21:1: in py_test rule //bazel-apollo/modules/tools/manual_traffic_light:manual_traffic_light_cpplint: paths to Python packages may not contain '-'
ERROR: Analysis of target '//bazel-apollo/modules/tools/manual_traffic_light:manual_traffic_light_cpplint' failed; build aborted
INFO: Elapsed time: 12.159s
FAILED: Build did NOT complete successfully (12 packages loaded)
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Loading:
Loading: 0 packages loaded
Analyzing: 845 targets (0 packages loaded)
ERROR: /apollo/bazel-apollo/modules/map/pnc_map/BUILD:114:1: in py_test rule //bazel-apollo/modules/map/pnc_map:path_cpplint: paths to Python packages may not contain '-'
ERROR: Analysis of target '//bazel-apollo/modules/map/pnc_map:path_cpplint' failed; build aborted
INFO: Elapsed time: 1.738s
FAILED: Build did NOT complete successfully (0 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 181 seconds
============================
The terminal process terminated with exit code: 255

**Comment by Grayhu07** [comment]
Is it because that you did not install docker or the docker did not work as expect? For building in VScode, the pre-request is that you already have a properly working docker, you can download docker [here](https://www.docker.com/). And for detailed information in build in VScode, you can check out [this](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_apollo_in_vscode_cn.md)

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. @billzhj if you have not resolved the build issue, feel free to reopen it. Thanks!
