### ISSUE TITLE
[Non-technical question] May printscreens of Dreamview be used freely?

### ISSUE THREAD

**Issue by antonfrigard** [ApolloAuto/apollo#4142]
I apologize for posting this here, but I found no other place to ask the question. I am currently working on a bachelor thesis report in which we use pictures of the car in Dreamview. May we use them as we like or do we need to be careful about picture rights?

Best regards

**Comment by Zhenni17** [comment]
Hi @antonfrigard , please don't apologizing. Github issue is where you can ask any questions about Apollo Platform. If you want to use pictures of the car in DreamView, you can cite Apollo like any other public info. Hope that helps! 

In the future, if you have a question that you don't think it fits at Github, feel free to email me directly at wuzhenni01@baidu.com. :)
