### ISSUE TITLE
Want to use 'visualization_msgs' of ros in Apollo

### ISSUE THREAD

**Issue by nulungzi2001** [ApolloAuto/apollo#4159]
I would like to use 'visualization_msgs' of ros inside Apollo. Could anyone let me know how to do it?

For example, I knew that we are already using 'sensor_msgs::PointCloud2' in Apollo. Similarly, I would like to use 'visualization_msgs::Marker' in Apollo.

Thanks!

**Comment by fengqikai1414** [comment]
Since ros msg only contains header files, you can put folder `visualization` directly into `/home/tmp/ros` in the docker.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @nulungzi2001 we currently use our own framework Apollo Cyber RT. Do check it out!
