### ISSUE TITLE
Questions about simulation in Apollo. Is ROSBAG enough? 

### ISSUE THREAD

**Issue by sjtugjy** [ApolloAuto/apollo#4166]
Hi everyone,

**Question-1:**
How to test each module (**correctness and performance**) in apollo?

Leveraging ROSBAG to replay the recorded messages cannot test the modules.
For example, "rosbag play demo_2.5.bag" actually does not launch the modules. 

**Question-2:**
I am wondering if it is possible to run some **open source data set** (e.g., the data from Udacity) on apollo.

Thanks in advance!

--
Jinyu

**Comment by jinghaomiao** [comment]
Apollo has it's own data format stored as rosbags. Open source data set won't work in Apollo before you convert them into Apollo compatible data format which is protobuf defined in each module.

**Comment by sjtugjy** [comment]
@jinghaomiao Thank you for your reply.

For the first question, is it necessary to start each module **manually**?
And again, ROSBAG replaying just resends the recorded data no matter the correctness of other modules. Do I misunderstand?

**Comment by jinghaomiao** [comment]
@sjtugjy The provided demo bag has all related topics of data to be able to replay and visualized in dreamview. If you wanna launch your desired modules, you need to filter out the corresponding topics so that they won't interference with the existing topics in the original demo bag.

**Comment by sjtugjy** [comment]
However, even if I filter all the topics except sensors and can, the rosbag will only replay the recorded sensor data no matter where the car is. 
Is this correct? If so, some bugs may be hidden. So, how to do "real" simulation?
