### ISSUE TITLE
Is there any way to speed up the build inside docker container using bazel?

### ISSUE THREAD

**Issue by kwailamchan** [ApolloAuto/apollo#4172]
It cost a lot of time on running ``./apollo.sh build/test/lint/check``, is there any way to speed up the build process using bazel?

I tried to increase the share memory or # of cpu on ``docker run xxx``, it didn't work.

**Comment by gengqx** [comment]
Bazel need more cpu core to speed up,the shared memory would have a slight help on speed up .
I test on a 8 core cpu ,it need 1200s to build,but only need 900s on a 12 core cpu.
If you have build the project before,only modified a few line of code,it would only cost under 100s.

**Comment by kwailamchan** [comment]
@gengqx Thanks for your reply. 

It cost 606s using default settings on ``docker/scripts/dev_start.sh``, perhaps default system settings (28 cpus).
If applying ``--cpuset-cpus 24 \`` (is the setting correct?), it would be mush slower than default settings.

My question is - is there any way to speed up on software level if we don't upgrade a cpu with higher performance? We are expecting building in 100-200s, rather than 600s.

```
 Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                28
On-line CPU(s) list:   0-27
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
Stepping:              2
CPU MHz:               1205.340
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              3998.08
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-27
```

**Comment by kwailamchan** [comment]
It is already running on SSD disk.
CPU usage was up to 50-65%, there might be some room to be improved, for example, configuring some performance settings for bazel or docker container? I will do more search.

**Comment by natashadsouza** [comment]
@kwailamchan thank you so much for your suggestions and work to help improve Apollo's efficiency. If you have any additional suggestions, please get in touch with us. :)
