### ISSUE TITLE
Version 2.0 Lidar obstacle detection training protocol

### ISSUE THREAD

**Issue by ymshao** [ApolloAuto/apollo#4178]
I am trying to figure out how to train the Lidar obstacle detection model in Apollo version 2.0, with external  datasets, for example, KITTI.  However, I did not find the training protocol in the perception module.

Can you please provide the training program? If not, can you clarify the definition of objectness/posotiveness, how to label the ground truth data with these definition?

Thanks

**Comment by ymshao** [comment]
Can anyone help? Thanks.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
