### ISSUE TITLE
heading() and yaw() definition

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4182]
Hi Apollo team,

Can you please clarify  `heading()` and `yaw()`? Are these in global (ENU) frame or vehicle (RFU) frame? From which axis measured from?

Also, it looks like `VehicleStateProvider` provided `linear_velocity`. Is this in vehicle (RFU) frame, a.k.a `longitudinal speed`? If so, how do I get `lateral speed`?

Thank you.

**Comment by Capri2014** [comment]
heading in global (ENU) frame and yaw angle read in vehicle (RFU) fame from IMU and internally converted into FLU.

linear_velocity can also be of 3 coordinate systems, for now, linear_velocity has only one dimension which is longitudinal direction. The so called "lateral speed" can always be assumed to be zero when assume no drifting or skidding.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
