### ISSUE TITLE
Delphi radar in third party perception

### ISSUE THREAD

**Issue by rogern27** [ApolloAuto/apollo#4186]
Hi,
In /modules/third_party_perception/conversion.cc :
For Conti radar, id  is correctly set (`rob.set_id(contiobs.obstacle_id());`).  

But for Delphi radar, the id is set to the index (`rob.set_id(index);`). Further, the corresponding obstacle from last_radar_obstacles is found using that id and velocity is calculated based on that (` const auto iter = last_radar_obstacles.radar_obstacle().find(index);`). 

Could you please clarify why index is used for Delphi radar? 

Why do not we have id in DelphiESR message? Is it because we only get detections from Delphi radar here and not tracks?

**Comment by rogern27** [comment]
@techoe : Could you please answer this question?

**Comment by techoe** [comment]
Hi @rogern27, I am sorry for the late reply. We will answer you ASAP. Thank you!
@weidezhang, Could you answer this question?

**Comment by natashadsouza** [comment]
@rogern27 we do not currently support Delpi Radar. If you would have made any progress on this topic do let us know.
