### ISSUE TITLE
camera image timestamps

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#4187]
In the code, the usb_cam driver publishes images with local timestamp. By local I mean it's the time since camera started on the vehicle. So it's values range between 0 to 1000 and so on. But the other messages are have a universal time stamp like GPS or ros::Time.now() which have values like 1544678430s and so on. Even in demo-sensor bag provided, the camera images have timestamps consistent with other sensor messages. So do you guys modify the timestamps in the code?

**Comment by xiaohuitu** [comment]
@fengqikai1414 This might be an issue for camera driver module.

**Comment by Peter9606** [comment]
@xiaohuitu  By "an issue for camera driver module", did you mean the camera driver module should publish image with a universal time stamp like GPS ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
