### ISSUE TITLE
Inconsistency in coordinate frame definition in Apollo documents

### ISSUE THREAD

**Issue by nulungzi2001** [ApolloAuto/apollo#4188]
I found that the definition of the vehicle frame is different in the two documents:

1) https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination.pdf
   --> y is pointing out the front of vehicle
2) https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Guideline_sensor_Installation_apollo_2.5.md
  --> x is pointing out the front of vehicle

could you clarify which one is right?

Thanks,

**Comment by wckorealsh** [comment]
@nulungzi2001 It looks like the first document is general vehicle coordinate (R-F-U), the one in the second document refers only sensor coordinate according to the sensor manufacture's definition. I think probably perception module performs the coordinate transformation from the sensor coordinate to vehicle coordinate.

Please correct me if I am wrong Apollo team.

**Comment by natashadsouza** [comment]
@wckorealsh you are correct. Thank you for providing the explanation :)
Currently closing this issue as it has been resolved.
