### ISSUE TITLE
How to subscribe acceleration command

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4189]
Hi Apollo team,

I recognized that the control signal is throttle, braking, and steering wheel. But I want to get acceleration signal generated by the control, not from the localization. So, I don't think I can simply register an adapter for the controller.
How to get this signal?
Thank you.

**Comment by Capri2014** [comment]
could you elaborate more on this? If you are looking for the control acceleration command SENT to the vehicle, it is in the command proto, debug information.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while.
