### ISSUE TITLE
apollo的数据是如何标定的？

### ISSUE THREAD

**Issue by NEUdeep** [ApolloAuto/apollo#4193]
您好，我在github上面看到您的apollo的项目，我想请问您一些问题，apollo的数据是如何标定的？相机和雷达之间的坐标关系是如何转换的？data对应的标签是怎么得到的？我看您文档里是给了一些标定的工具，可以运行在车上，这个是主要参考了那篇文章的标定思路吗？感谢您的解答——来自国内的小白

**Comment by changduanyu** [comment]
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/lidar_calibration_cn.pdf 这里介绍了如何多激光雷达跟gnss的标定原理， 就我所知， 是基于手眼标定获得一个初始值， 然后再优化， 相机和雷达应该也相同原理

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
