### ISSUE TITLE
How to make my own's image which can be uploaded to simulation platform?

### ISSUE THREAD

**Issue by YafeiWangAlice** [ApolloAuto/apollo#4194]
I referred the instructions on this page: [https://console.bce.baidu.com/apollo_sim/getStart?locale=zh-cn]

There are 3 questions here:
1. The page above said, users must have this two files under the fixed path: /home/apollo/data/config.json, /apollo/sim_op/metainfo.
   I searched the whole apollo project and didn't find these two files, is that means I need to creat them by myself?
2. Are there only two folders, "modules" and "sim_op", incldued in the package I want to upload to test?
3. I am confused by "start_planning.sh" and "start_planning.bash", what is the difference? I need to make both of them?

At last, if there is a document or any sample about how to make the module image to upload to simulaiton platform?

Thanks.

**Comment by ygcn** [comment]
Hi there,

Thanks for your interest in the Apollo simulation service. I will forward your questions to my colleagues who specialize in the Baidu Cloud deployment. In the meantime, you may want to take a look at https://azure.apollo.auto/, a similar deployment on Microsoft Azure with more streamlined operations.

Please feel free to let us know should you have further questions.

Best regards,

-Guang

**Comment by YafeiWangAlice** [comment]
Hi,

I reviewed the  web https://azure.apollo.auto/, but still I didn't get the answer of my questions.
The info inclued in this page is even less than https://console.bce.baidu.com/apollo_sim/getStart?locale=zh-cn

I am looking forward for the instruction about how to make the image which can be tested on simulaiton paltform.
If there are any progress, please let me know.

Thanks very much!

**Comment by siyangy** [comment]
@YafeiWangAlice If you sign in into https://azure.apollo.auto, you can click the 'Task Management' section to submit your own task. There's one permission you might need to apply for and after that It should be pretty straightforward.

**Comment by Albert-FanYang** [comment]
I have the same issue with you @YafeiWangAlice , did you find a solution yet? I push the docker image to the apollo sim repo, but i can't select as an upload image. there must be something wrong with the configuration files, however there are no hints about how to set them up.  @siyangy I try to use https://azure.apollo.auto, it seems simple to use, but i don't have the access to task management, LOL..

**Comment by Qdriving** [comment]
Up! I have the same doubt. ......

**Comment by unacao** [comment]
Hi All,
https://azure.apollo.auto is the most updated simulation platform. The "Get Started" tab will describe briefly the procedure. The main difference from https://console.bce.baidu.com/apollo_sim/getStart?locale=zh-cn is that you don't need to upload any docker image or binary; instead you just specify your forked apollo repository (e.g. https://github.com/konyhl/apollo.git) and the git commit/branch you would like to test. We will pull your code and compile, then the simulation test will be run, which means the 3 questions in the original post is no longer relevant. Just follow the notice on the "Task Management" and send us an email about account activation to create new tasks. Hope this clarifies your doubt.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
