### ISSUE TITLE
Dreamview under what circumstances will be killed?

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4201]
when  I am running apollo,  open the gps driver and lidar on the computer (ps: the computer have not the two modules). then Dreamview is killed and " rosbag play -l " still running.

**Comment by vlin17** [comment]
@breakisx how do you open the gps driver and lidar? is it through dreamview switches from Module Controller? Dreamview shouldn't be killed by starting these two modules.  Try taking a look at logs under data/log/dreamview* and/or core under data/core to investigate the issue.

**Comment by natashadsouza** [comment]
Closing this issue as there has no communication in a while. Feel free to open it should the issue persist.
