### ISSUE TITLE
about build st_boundary

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#4203]
Since we get path_decision from dp_st_speed and already build st boundary , why we erase st boundaries and rebuild again in qp_spline_st_speed at [line 87 ](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/tasks/qp_spline_st_speed/qp_spline_st_speed_optimizer.cc)
and what does the func " BuildFromPoints() " at [line 58](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/speed/st_boundary.cc) in st_boundary.cc mean?
Expect for your reply, thanks

**Comment by startcode** [comment]
st_boundary  is a concept based on a driving path. Different path corresponds to different st boundaries. 
Previously, the ADC is assumed to drive following reference line,
but in qp_spline_st_speed, the ADC is assumed to drive the path created by DP PATH stage. Therefore, the st_boundary need to be refreshed.
