### ISSUE TITLE
Question: comments in spline_2d_seg.h

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#4204]
Is the comment "Order represent the number of parameters (not the highest order)" right?

```
class Spline2dSeg {
 public:
  // order represent the number of parameters (not the highest order);
  explicit Spline2dSeg(const uint32_t order);
```

```
Spline2dSeg::Spline2dSeg(const uint32_t order)
    : spline_func_x_(order), spline_func_y_(order) {
  derivative_x_ = PolynomialXd::DerivedFrom(spline_func_x_);
  derivative_y_ = PolynomialXd::DerivedFrom(spline_func_y_);
  second_derivative_x_ = PolynomialXd::DerivedFrom(derivative_x_);
  second_derivative_y_ = PolynomialXd::DerivedFrom(derivative_y_);
  third_derivative_x_ = PolynomialXd::DerivedFrom(second_derivative_x_);
  third_derivative_y_ = PolynomialXd::DerivedFrom(second_derivative_y_);
}
```

Here is one of constructors for PolynomialXd:

```
PolynomialXd::PolynomialXd(const std::uint32_t order)
    : params_(order + 1, 0.0) {
  CHECK_GE(order, 0);
}
```

For instance

f(x) = a_2*x^2 + a_1x^1 + a_0,

order = 2 and number of parameters = 3.

Should it be " number of parameters = order + 1" because of additional intercept a_0?

**Comment by lianglia-apollo** [comment]
Thanks. The comments are outdated and we need to update them.

**Comment by Zhenni17** [comment]
@jilinzhou thank you for pointing out the outdated comment. Our engineer team is working on getting that updated. I'm closing the issue for now. If you see more issues like this, please file another issue to let us know. Thank you! :)
