### ISSUE TITLE
Error in building custom release image

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#4209]
Hi,

I follow the following steps to make a release image from current apollo master:

**bash docker/scripts/dev_start.sh**
**bash docker/scripts/dev_into.sh**

**bash apollo.sh build**

**bash apollo.sh release**

**bash apollo_docker.sh gen** - executed outside docker

This creates a release image - release-x86_64-20180518_1555

Now I load this image - **bash docker/scripts/release_start.sh release-x86_64-20180518_1555**

I get the following error:

/apollo/data/core/core_%e.%p
Type 'y' or 'Y' to pull docker image from China mirror or any other key from US mirror.

Error response from daemon: manifest for apolloauto/apollo:release-x86_64-20180518_1555 not found
3d5f290eaaba5f725b6616d57636eda1197d973b3775e73804ddb7c6db11048f
Adding group `apollo' (GID 1000) ...
Done.
Adding user `apollo' ...
Adding new user `apollo' (1000) with group `apollo' ...
The home directory `/home/apollo' already exists.  Not copying from `/etc/skel'.
/apollo/scripts/apollo_base.sh: line 82: /apollo/ros/setup.bash: No such file or directory
Started supervisord with release conf
Start roscore...
voice_detector: started
dreamview: ERROR (spawn error)

Am I not following the right steps to create the release image?

**Comment by xiaoxq** [comment]
Could you tell us the reason to run release image? Generally, running dev container will be much more developer-friendly.
Actually we are going to retire the release process, which has already been a little out of maintenance. If there is still strong need, we'll continue to support it.

**Comment by agarwalsid** [comment]
Thanks for the update @xiaoxq , I was just testing it out, will continue working with dev images.

**Comment by Zhenni17** [comment]
Seems like OP's issue is resolved at the moment. Closing the issue, and feel free to reopen it if I missed anything.
