### ISSUE TITLE
Report： confusing height/width paramters in camera intrinsics yaml files

### ISSUE THREAD

**Issue by songhanchen** [ApolloAuto/apollo#4211]
Parameters are declared as:
    image_width: 1080
    image_**height: 1920**
in files:
    modules/drivers/usb_cam/params/*.yaml
    modules/perception/traffic_light/projection/test/data/projection/camera.yaml
while in other files, it's  "image_width" instead of "image_height" be initialized as 1920.  
How are these width/height parameters in yaml act? It's confusing.

**Comment by techoe** [comment]
@songhanchen, Thank you for pointing out the issue. It seems that the camera is rotated 90 degrees. I agree that it is confusion. Rather than switching width and height, 90 degree rotation matrix should be applied. We will change it accordingly. Thank you!
