### ISSUE TITLE
Matrix Exponential?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4214]
How do you compute matrix exponential in Apollo? Looks like math util does not provide this functionality.

**Comment by Capri2014** [comment]
@wckorealsh the Eigen lib has already have similar functions implemented, please refer to : https://eigen.tuxfamily.org/dox/unsupported/group__MatrixFunctions__Module.html

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
