### ISSUE TITLE
system running low-graphic mode when install apollo kernel

### ISSUE THREAD

**Issue by ynfei** [ApolloAuto/apollo#4215]
Hello ,thank you for your outstanding work,when i installing  the apollo in Intel NUC5CPYH according to the Apollo 2.0 Quick Start , after installing the apollo kernel and reboot ,the computer can not restart and shows the "ubuntu system is running in low-graphics mode " then couldn't log in both the graphics mode and the commond mode, how could  i fix this problem,thank you very much!

**Comment by natashadsouza** [comment]
Hi @ynfei sorry for the delay in response. Is it possible to provide your system specifications?
Thanks!

**Comment by storypku** [comment]
Hi @ynfei , another late response. 

We have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. Please follow these docs to install PREEMPT/PREEMPT_RT kernels for Apollo. 

Thank you.
