### ISSUE TITLE
Run Offline Perception LowCost Visualizer on TX2

### ISSUE THREAD

**Issue by Zoltan3057** [ApolloAuto/apollo#4217]
Hi, as far as I know, "offline perception lowcost visualizer" requires we installed the same version of nvidia driver on both host and docker. However, TX2 seems to have its own nvidia driver version, which is based on tegra. Does this mean "offline perception lowcost visualizer" cannot work on TX2?

**Comment by techoe** [comment]
Hi @Zoltan3057, 
I think you can install the same nvidia driver in your TX2 after purging the default nvidia driver. Please let us know if you have an issue.

Thank you,
Tae Eun
