### ISSUE TITLE
Report: bazel() HeapDumpOnOutOfMemoryError 

### ISSUE THREAD

**Issue by songhanchen** [ApolloAuto/apollo#4218]
ubuntu 1404  4.2.0-27-generic , NV375.39
Apollo2.5.0, It runs well.   But each time  I had built with "bash apollo.sh build_gpu", I got the HeapDumpOnOutOfMemoryError of bazel. As following:
![bazelmemoryerror0514](https://user-images.githubusercontent.com/37654046/40287317-12067376-5cdf-11e8-9307-e0e5b8a50987.jpg)
![bazelmemoryerror0521](https://user-images.githubusercontent.com/37654046/40287319-1729cd58-5cdf-11e8-938d-e209cec98db8.jpg)

**Comment by xiaoxq** [comment]
Could you tell us about the host machine information?
Maybe it's just because of memory shortage.

**Comment by songhanchen** [comment]
song@songPC:~$ cat /proc/cpuinfo | grep 'model name' |uniq
model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
song@songPC:~$ cat /proc/cpuinfo | grep "cpu cores" | uniq
cpu cores	: 4
song@songPC:~$ cat /proc/meminfo
MemTotal:        8036060 kB
MemFree:         5437792 kB
MemAvailable:    6688796 kB
Buffers:          309516 kB
Cached:           924108 kB
SwapCached:            0 kB
Active:          1771000 kB
Inactive:         527140 kB
Active(anon):    1065748 kB
Inactive(anon):    73436 kB
Active(file):     705252 kB
Inactive(file):   453704 kB
Unevictable:          64 kB
Mlocked:              64 kB
SwapTotal:       8249340 kB
SwapFree:        8249340 kB
Dirty:               216 kB
Writeback:             0 kB
AnonPages:       1064604 kB
Mapped:           413628 kB
Shmem:             74664 kB
Slab:             174704 kB
SReclaimable:     134240 kB
SUnreclaim:        40464 kB
KernelStack:        8976 kB
PageTables:        34616 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12267368 kB
Committed_AS:    5251244 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      125524 kB
VmallocChunk:   34359537660 kB
HardwareCorrupted:     0 kB
AnonHugePages:    382976 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      155944 kB
DirectMap2M:     3899392 kB
DirectMap1G:     4194304 kB

**Comment by natashadsouza** [comment]
@songhanchen sorry for the delay in responding to your request. It does seem like you do not have enough memory to install and build Apollo. We recommend 6GB of free memory (maybe slightly more). This is what is causing the error.

**Comment by KitFung** [comment]
Actually, IT IS NOT AN ERROR or WARNING.
It is just an argument passed to bazel.
It tell bazel to dump it heap when out of memory error happen.

**Comment by KitFung** [comment]
Related Information: https://www.oracle.com/technetwork/java/javase/tech/vmoptions-jsp-140102.html
