### ISSUE TITLE
Wifi Connection with apollo kernel

### ISSUE THREAD

**Issue by Zoltan3057** [ApolloAuto/apollo#4219]
Hi,
I download the apollo kernel but find that I cannot find wifi connection tab.

**Comment by xiaoxq** [comment]
The kernel should have nothing to do with Wifi. I guess it's a problem of the origin Ubuntu 14 installation.

**Comment by jinghaomiao** [comment]
@Zoltan3057 please make sure your Linux environment is workable before start working on Apollo docker. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.
