### ISSUE TITLE
bash docker/scripts/dev_start.sh -C docker error

### ISSUE THREAD

**Issue by NEUdeep** [ApolloAuto/apollo#4221]
iebsn@ubuntu:~/apollo-master$ bash docker/scripts/dev_start.sh -C
[sudo] password for iebsn: 
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:c94b6b76e8551bb2ae924f40756fe153c5c8e60f8ec730572397b566d6c173eb
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
docker: Error response from daemon: Conflict. The name "/apollo_map_volume-sunnyvale_big_loop" is already in use by container 7b98e3cefba3d25486ab4ee9f4edba3e6f670a80384dba4edfe0e8d69d68a347. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_loop-latest
d5f88d30abf59e2d1ace5755947cd854d11ddfcd8974144e36b01cef2421053e
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"\n".

how to  deal with this error? thanks.

**Comment by mickeyouyou** [comment]
**The name "/apollo_map_volume-sunnyvale_big_loop" is already in use by container 7b98e3cefba3d25486ab4ee9f4edba3e6f670a80384dba4edfe0e8d69d68a347. You have to remove (or rename) that container to be able to reuse that name..**

this image have be used in exist container, you need to stop or remove the container firstly, then run dev_start.sh

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
