### ISSUE TITLE
Error to Build with ./apollo.sh build_gpu (Apollo 2.0)

### ISSUE THREAD

**Issue by eros-ck** [ApolloAuto/apollo#4227]
**Ubuntu 16.04 + Apollo 2.0 + Nvidia Driver installed in local**

When I ran ` ./apollo.sh build_gpu` in the docker container created by released docker image, it reported this error. I checked in the container by `lsmod | grep nvidia` and it displayed all the processes of nvidia as the host did. Could anyone have an idea how to fix it?
Thanks! 

```
ERROR: /apollo/modules/perception/lib/config_manager/BUILD:5:1: no such package 'modules/perception/cuda_util': BUILD file not found on package path and referenced by '//modules/perception/lib/config_manager:config_manager'
ERROR: Analysis of target '//modules/perception/lib/config_manager:config_manager' failed; build aborted
```

**Comment by xiaoxq** [comment]
Looks like cuda_util building error. Could you check if the following file exists:
modules/perception/cuda_util/BUILD

Then run "bazel build modules/perception/cuda_util/..." and make sure it works.

**Comment by eros-ck** [comment]
Thanks a lot. The "BUILD" file was missing. It has been fixed by adding it.

Issue closed.
