### ISSUE TITLE
Compiled apollo the following error, I thought it was a compiler problem, later found not, but I do not know how to deal with the following error, please help me check this question, thank you！

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4230]
INFO: Found 882 targets...
ERROR: /apollo/modules/planning/common/BUILD:190:1: C++ compilation of rule '//modules/planning/common:frame' failed (Exit 1).
In file included from /usr/include/aarch64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/memory:63,
                 from ./modules/planning/common/frame.h:25,
                 from modules/planning/common/frame.cc:20:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Args = {const std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<apollo::planning::PathObstacle, std::default_delete<apollo::planning::PathObstacle> > >&}; _Tp = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >]':
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from 'static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Args = {const std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<apollo::planning::PathObstacle, std::default_delete<apollo::planning::PathObstacle> > >&}; _Tp = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >]'
/usr/include/c++/5/bits/hashtable_policy.h:1955:37:   required from 'std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type* std::__detail::_Hashtable_alloc<_NodeAlloc>::_M_allocate_node(_Args&& ...) [with _Args = {const std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<apollo::planning::PathObstacle, std::default_delete<apollo::planning::PathObstacle> > >&}; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >, true> >; std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type = std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >, true>]'
/usr/include/c++/5/bits/hashtable.h:1116:49:   required from 'std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(const std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>&)::<lambda(const __node_type*)> [with _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type = std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >, true>; typename _Traits::__hash_cached = std::integral_constant<bool, true>]'
/usr/include/c++/5/bits/hashtable.h:1115:4:   required from 'struct std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(const std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>&) [with _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>]::<lambda(const __node_type*)>'
/usr/include/c++/5/bits/hashtable.h:1114:16:   required from 'std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(const std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>&) [with _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>]'
/usr/include/c++/5/bits/unordered_map.h:172:7:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/5/bits/stl_uninitialized.h:126:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = apollo::planning::ReferenceLineInfo*; _ForwardIterator = apollo::planning::ReferenceLineInfo*]'
/usr/include/c++/5/bits/stl_uninitialized.h:281:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = apollo::planning::ReferenceLineInfo*; _ForwardIterator = apollo::planning::ReferenceLineInfo*; _Tp = apollo::planning::ReferenceLineInfo]'
/usr/include/c++/5/bits/stl_uninitialized.h:303:2:   required from '_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = apollo::planning::ReferenceLineInfo*; _ForwardIterator = apollo::planning::ReferenceLineInfo*; _Allocator = std::allocator<apollo::planning::ReferenceLineInfo>]'
/usr/include/c++/5/bits/vector.tcc:422:8:   required from 'void std::vector<_Tp, _Alloc>::_M_emplace_back_aux(_Args&& ...) [with _Args = {const apollo::hdmap::PncMap*&, const apollo::planning::ReferenceLine&, apollo::common::TrajectoryPoint&, apollo::planning::ReferenceLineSmootherConfig&}; _Tp = apollo::planning::ReferenceLineInfo; _Alloc = std::allocator<apollo::planning::ReferenceLineInfo>]'
/usr/include/c++/5/bits/vector.tcc:101:23:   required from 'void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {const apollo::hdmap::PncMap*&, const apollo::planning::ReferenceLine&, apollo::common::TrajectoryPoint&, apollo::planning::ReferenceLineSmootherConfig&}; _Tp = apollo::planning::ReferenceLineInfo; _Alloc = std::allocator<apollo::planning::ReferenceLineInfo>]'
modules/planning/common/frame.cc:110:78:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: use of deleted function 'constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<apollo::planning::PathObstacle>]'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/5/memory:62,
                 from ./modules/planning/common/frame.h:25,
                 from modules/planning/common/frame.cc:20:
/usr/include/c++/5/bits/stl_pair.h:127:17: note: 'constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<apollo::planning::PathObstacle>]' is implicitly deleted because the default definition would be ill-formed:
       constexpr pair(const pair&) = default;
                 ^
/usr/include/c++/5/bits/stl_pair.h:127:17: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = apollo::planning::PathObstacle; _Dp = std::default_delete<apollo::planning::PathObstacle>]'
In file included from /usr/include/c++/5/memory:81:0,
                 from ./modules/planning/common/frame.h:25,
                 from modules/planning/common/frame.cc:20:
/usr/include/c++/5/bits/unique_ptr.h:356:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^
INFO: Elapsed time: 785.389s, Critical Path: 753.34s
============================
[ERROR] Build failed!
[INFO] Took 802 seconds

**Comment by jinghaomiao** [comment]
Please do a bazel clean and rebuild it.

**Comment by breakisx** [comment]
@jinghaomiao   This error occurs on the arm compile apollo1.5, I have bazel clean, or will this error, what good solution do you have?

**Comment by breakisx** [comment]
INFO: Found 882 targets...
ERROR: /apollo/modules/planning/common/BUILD:190:1: C++ compilation of rule '//modules/planning/common:frame' failed (Exit 1).
In file included from /usr/include/aarch64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/memory:63,
                 from ./modules/planning/common/frame.h:25,
                 from modules/planning/common/frame.cc:20:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Args = {const std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<apollo::planning::PathObstacle, std::default_delete<apollo::planning::PathObstacle> > >&}; _Tp = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >]':
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from 'static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Args = {const std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<apollo::planning::PathObstacle, std::default_delete<apollo::planning::PathObstacle> > >&}; _Tp = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >]'
/usr/include/c++/5/bits/hashtable_policy.h:1955:37:   required from 'std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type* std::__detail::_Hashtable_alloc<_NodeAlloc>::_M_allocate_node(_Args&& ...) [with _Args = {const std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<apollo::planning::PathObstacle, std::default_delete<apollo::planning::PathObstacle> > >&}; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >, true> >; std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type = std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >, true>]'
/usr/include/c++/5/bits/hashtable.h:1116:49:   required from 'std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(const std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>&)::<lambda(const __node_type*)> [with _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type = std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >, true>; typename _Traits::__hash_cached = std::integral_constant<bool, true>]'
/usr/include/c++/5/bits/hashtable.h:1115:4:   required from 'struct std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(const std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>&) [with _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>]::<lambda(const __node_type*)>'
/usr/include/c++/5/bits/hashtable.h:1114:16:   required from 'std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(const std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>&) [with _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::unique_ptr<apollo::planning::PathObstacle> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>]'
/usr/include/c++/5/bits/unordered_map.h:172:7:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/5/bits/stl_uninitialized.h:126:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = apollo::planning::ReferenceLineInfo*; _ForwardIterator = apollo::planning::ReferenceLineInfo*]'
/usr/include/c++/5/bits/stl_uninitialized.h:281:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = apollo::planning::ReferenceLineInfo*; _ForwardIterator = apollo::planning::ReferenceLineInfo*; _Tp = apollo::planning::ReferenceLineInfo]'
/usr/include/c++/5/bits/stl_uninitialized.h:303:2:   required from '_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = apollo::planning::ReferenceLineInfo*; _ForwardIterator = apollo::planning::ReferenceLineInfo*; _Allocator = std::allocator<apollo::planning::ReferenceLineInfo>]'
/usr/include/c++/5/bits/vector.tcc:422:8:   required from 'void std::vector<_Tp, _Alloc>::_M_emplace_back_aux(_Args&& ...) [with _Args = {const apollo::hdmap::PncMap*&, const apollo::planning::ReferenceLine&, apollo::common::TrajectoryPoint&, apollo::planning::ReferenceLineSmootherConfig&}; _Tp = apollo::planning::ReferenceLineInfo; _Alloc = std::allocator<apollo::planning::ReferenceLineInfo>]'
/usr/include/c++/5/bits/vector.tcc:101:23:   required from 'void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {const apollo::hdmap::PncMap*&, const apollo::planning::ReferenceLine&, apollo::common::TrajectoryPoint&, apollo::planning::ReferenceLineSmootherConfig&}; _Tp = apollo::planning::ReferenceLineInfo; _Alloc = std::allocator<apollo::planning::ReferenceLineInfo>]'
modules/planning/common/frame.cc:110:78:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: use of deleted function 'constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<apollo::planning::PathObstacle>]'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/5/memory:62,
                 from ./modules/planning/common/frame.h:25,
                 from modules/planning/common/frame.cc:20:
/usr/include/c++/5/bits/stl_pair.h:127:17: note: 'constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<apollo::planning::PathObstacle>]' is implicitly deleted because the default definition would be ill-formed:
       constexpr pair(const pair&) = default;
                 ^
/usr/include/c++/5/bits/stl_pair.h:127:17: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = apollo::planning::PathObstacle; _Dp = std::default_delete<apollo::planning::PathObstacle>]'
In file included from /usr/include/c++/5/memory:81:0,
                 from ./modules/planning/common/frame.h:25,
                 from modules/planning/common/frame.cc:20:
/usr/include/c++/5/bits/unique_ptr.h:356:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^
INFO: Elapsed time: 785.389s, Critical Path: 753.34s
============================
[ERROR] Build failed!
[INFO] Took 802 seconds

**Comment by natashadsouza** [comment]
@breakisx is this an issue you are still facing? We apologize for the delay in responding to your question.

**Comment by natashadsouza** [comment]
Closing this issue currently as there has been no communication in a while. Feel free to reopen if you have additional questions. Thanks!
