### ISSUE TITLE
Laplacian smoothing inside create_map.py smoothies out the actual curvature of the lane

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#4235]
This is more of a documentation issue. There is a smooth_center_width() function in the script as the following:

```
def smooth_dimension(data, dim):
    """
    smooth dimension 'dim' of 'data'
    """

    extracted_data = extract_data(data, dim)
    if dim == 'width':
        laplacian_smooth(extracted_data, 1.0, 1000)
    else:
        laplacian_smooth(extracted_data, 1.0, 1000)
    update_data(data, dim, extracted_data)

def smooth_center_width(data):
    """
    smooth centers and widths of data
    """

    smooth_dimension(data, 'center_x')
    smooth_dimension(data, 'center_y')
    smooth_dimension(data, 'width')
```

We noticed that it changes the center lane path quite bit when there are noticeable curvature changes. Therefore, the car tends to hit the right curb during playback in these lane segments. The following figure might help illustrate what I mean:

![lane_smooth](https://user-images.githubusercontent.com/6865725/40373951-06879d68-5db6-11e8-8fb8-2caae0af1fa4.png)

**Comment by yifeijiang** [comment]
This approach of map creation has been upgraded  to relative map in Apollo 2.5. Please refer to the documentation that is contributed by @davidhopper2003  [here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode.md)  or the [Chinese version](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode_cn.md). @Zhenni17 will update the old approach documentation to avoid confusion.
