### ISSUE TITLE
Can I test Apollo platform with a LiDAR Sensor alone?

### ISSUE THREAD

**Issue by BenBaek** [ApolloAuto/apollo#4240]
Hi I'm a student studying an autonomous vehicle and a beginner to use Ubuntu and Github for the first time.

I have LiDAR sensors(HDL-64E S2, VLP-16) and would like to develop an path planning algorithm on the apollo platform, but it's hard to know how to use it

I already installed the apollo kernel with apollo-git guidance and tried to connect LiDAR HDL-64E, but there's no image on DreamViewer and Velodyne module message with timeout() stamp.
If I press the Setup button in the Dream Viewer while only LiDAR is connected, will the obstacle recognition module run?

If I need all the reference hardware, I will buy it. Does it work by pressing the setup button and the Start Auto button while all the reference hardware is connected?

**Comment by YangHan101** [comment]
Hi,

It seems your lidar is not sync to gps time. If you could connect the gps module that velodyne provides with the lidar the time out issue should be solved.

Yang

**Comment by jinghaomiao** [comment]
@BenBaek please follow the hardware installation guide: https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md

**Comment by Zhenni17** [comment]
@BenBaek , seems like @YangHan101 & @jinghaomiao answered your question here. I'm closing the issue for now. If you have any additional questions, please feel free to open another issue. Good luck with your LiDAR setup, and thank you for using Apollo!
