### ISSUE TITLE
Downloading demo bags

### ISSUE THREAD

**Issue by LunaAmour** [ApolloAuto/apollo#4242]
I noticed that there seems to be a conflict between the demo bag download README and the actual process. After running the commands release_start.sh and release_into.sh as specified in the readme, I noted that in the demo_guide folder there did not exist a rosbag_helper.py file. Instead there is a rosbag_helper.sh file, which actually didn't seem to complete the downloading process when run. Is this simply a result of the README not being up to date or is there a separate usage being done in the release docker via bash script?

I was able to download the demo bag files outside of docker using the rosbag_helper.py file that was in my local directory.

**Comment by startcode** [comment]
Seems you are not using the latest code. In the master branch, there is a downloader script: 
https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/rosbag_helper.py

**Comment by LunaAmour** [comment]
I did pull the most recent code from the repository (thus the reason I have the python file locally), but I am unable to see it in the docker release environment. Perhaps I need to reset my release image?

**Comment by jinghaomiao** [comment]
@LunaAmour we are in the process of retiring release docker images. Please build your system inside a dev docker following README and you should be able to download the appropriate bag.

**Comment by LunaAmour** [comment]
Ok great thank you for the clarification. I suppose then it's just the README documentation that needs to be updated to utilize the dev docker rather than release.

**Comment by Zhenni17** [comment]
Hi @LunaAmour , we apologize for the confusion from our readme page. I will pass down this info to our technical writer to update the readme. Thank you for pointing out this issue. I am closing the issue for now and please file another issue if there is additional question. Thank you for using Apollo! :)
