### ISSUE TITLE
Mock Topic Publishers

### ISSUE THREAD

**Issue by LunaAmour** [ApolloAuto/apollo#4244]
I'd like to do some publishing of hand-crafted data in topics for debugging purposes. I've noticed a basic sample functionality at https://github.com/ApolloAuto/apollo/blob/master/modules/tools/mock_routing/mock_routing_request.py. Are there similar tools for other topics, or do you have other recommendations for how to handle providing inputs for specific modules?

**Comment by startcode** [comment]
Maybe this script can help https://github.com/ApolloAuto/apollo/blob/master/modules/tools/replay/replay_file.py

**Comment by apollodevcommunity** [comment]
there are many other topic tools in modules/tools folder   such as perception_obstacle_sender.py   you may search \"cyber.init\" for all topic sender files;for the specific topic which you need   you shall learn the apollo cyber mechanism first    and try to test some tool examples later.——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=690
