### ISSUE TITLE
The officially recommended GPS/IMU scheme is too expensive. Do you have a cheaper solution?

### ISSUE THREAD

**Issue by HangHuang** [ApolloAuto/apollo#4251]
hello
We're going to develop a commercial product based on Apollo, so we need to control the cost, but the officially recommended GPS/IMU scheme is too expensive. Do you have a cheaper solution?

祝身体健康，工作愉快！

H.Huang (黄航) 2846440252@qq.com
Distributed & Embedded System Lab
School of Information Science and Engineering,Lanzhou University
South Tianshui Road 222, Lanzhou City, 730000

**Comment by YangHan101** [comment]
Hi,

Of course, there are other options available. From what we know so far, there are quite a few GPS/INS vendors out there. However, each vendor doesn't necessarily generate the output with NovAtel's format. That would require change on the driver side. 
On top of that please evaluate the precision of the device to make sure that fits your need in your system. 

Best regards,
Yang

**Comment by HangHuang** [comment]
thanks
