### ISSUE TITLE
Cannot do ./apollo.sh build

### ISSUE THREAD

**Issue by kentasakurai** [ApolloAuto/apollo#4253]
Environment:
Ubuntu 17.10 with virtualbox 5.2.12
docker-ce 18.03.1

I can't solve the problem related proxy.

after do dev_into.sh, 
I set the container's env about proxies like this:
http_proxy=http://userID:passwd@-----:--- (also set HTTP_PROXY)

in this container, I can do wget, curl, apt-get, and so on.
However, if try the command ".apollo.sh build", error messages are returned.

ERROR: /apollo/modules/tools/manual_traffic_light/BUILD:21:1: no such package '@google_styeguide//':
Error cloning repository: https://github.com/google/styleguide.git: 407 Proxy Authorization Required
caused by http://github.com/google/styleguide.git: 407 407 Proxy Authorization Required and referenced by '//modules/tools/manual_traffic_light:manual_traffic_light_cpplint'

i can't understand how to pass the proxy in buzel's enviroment.

please tell me the method to solve this.
Thank you.

**Comment by mickeyouyou** [comment]
Can you have a try without proxy?

**Comment by hzdsdhr** [comment]
I think because your connection to github is unstable. Apollo has provided the solution, check the tutorial in apollo/docs/howto/how_to_solve_slow_pull_from_github.cn

**Comment by natashadsouza** [comment]
@kentasakurai were you able to resolve this issue? If not please let us know. Thanks!

**Comment by wanting73** [comment]
I also meet this problem. Please help.

**Comment by LOMORyan** [comment]
> I also meet this problem. Please help.

My solution:
download package manual
copy package to container
modify the package path at WORKSPACE and WORKSPACE.in file

**Comment by wanting73** [comment]
Thanks a lot! Sorry I'm not familiar with docker. Which package do you mean?

**Comment by wanting73** [comment]
Thanks a lot for you information! Could I maybe add your wechat to discuss our work with apollo? My wechat: 619454748
