### ISSUE TITLE
module/map

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4254]
In the module/map directory there are two directories hdmap and pncmap, hdmap I know what it means, pncmap what does that mean? Thank you!

**Comment by breakisx** [comment]
@jinghaomiao Thank you.  Is the file in this directory （modules/map/hdmap/adapter/xml_parser/）parsing base_map.xml to generate base_map.bin for apollo?

**Comment by jinghaomiao** [comment]
@breakisx Apollo can use map files in xml in opendrive format as well as .bin and .txt in proto format. You don't have to convert them and all these types of files can be loaded.

**Comment by wangzhensuo** [comment]
> 
> 
> @breakisx Apollo can use map files in xml in opendrive format as well as .bin and .txt in proto format. You don't have to convert them and all these types of files can be loaded.

Hello, I found that below cmd is based on "base_map.txt " to generate. if i only have "base_map.xml", I could not generate below files.
so, how to convert "base_map.txt "  to "base_map.xml",please?   thank you .
`generate routing_map.bin  routing_map.txt
./scripts/generate_routing_topo_graph.sh   --map_dir ./modules/map/data/demo/
sim_map.bin sim_map.txt
./bazel-bin/modules/map/tools/sim_map_generator   --map_dir ./modules/map/data/demo/`
