### ISSUE TITLE
Update "How to" w.r.t Apollo 2.5

### ISSUE THREAD

**Issue by linux-devil** [ApolloAuto/apollo#4255]
I was going through documentation and found "How to" section needs to be updated w.r.t new Apollo 2.5

**Comment by Zhenni17** [comment]
hi @linux-devil , thank you for pointing out this. We will get it cracking now! If you see any other incorrect section, please open more issues direct it to me.

**Comment by linux-devil** [comment]
Sure , I am still evaluating the code and docs. Thanks !

**Comment by natashadsouza** [comment]
Hi @linux-devil we added some documentation in the Howto and Quickstart that was initially missing. Take a look and let us know if you still have any questions. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as the documentation has been updated.
