### ISSUE TITLE
Some questions about the authenticity of dynamic environment in simulation

### ISSUE THREAD

**Issue by david87v5** [ApolloAuto/apollo#4257]
Whether the huge amount of real data collected on the road which is used for the reconstruction of dynamic scenes in the simulation is real-time uploaded in the real driving process. If so, how to ensure its real-time performance?In addition, where is the real data stored, the cloud or the on-board IPC?

**Comment by siyangy** [comment]
I'm not sure I understand your question. What does real data mean?

**Comment by david87v5** [comment]
@siyangy  Real data refers to the data collected by sensing devices used to build the dynamic environment in the simulation. These sensing devices in hardware corresponding to the perception module in software  is usually installed on the autonomous vehicle. What I want to know is whether the data is uploaded in real time, and where are they stored? Thanks for considering my questions and I am looking forward to your reply.

**Comment by david87v5** [comment]
@siyangy Real data refers to the data collected by sensing devices and used to build the dynamic environment in the simulation. These sensing devices in hardware corresponding to the perception module in software is usually installed on the autonomous vehicle. What I want to know is whether the data is uploaded in real time, and where are they stored? Thanks for considering my questions and I am looking forward to your reply.

**Comment by jinghaomiao** [comment]
@david87v5 The onboard data collection is being developed and tested. Please stay tuned.

Thanks!

**Comment by ygcn** [comment]
@david87v5 

The short answer to your question is "no". Large chunks of onboard data are not uploaded in real time; it would clog the wireless connection and wouldn't be necessary anyway. As @jinghaomiao mentioned you can record "bags" onboard and later archive them where you prefer. Creating scenarios from recorded bags and uploading to the Apollo simulator on Azure is an advanced feature currently not open to the general community; contact us if your organization is interested. Hope this helps.

-Guang

**Comment by david87v5** [comment]
@jinghaomiao  thanks for your reply.

**Comment by david87v5** [comment]
@ygcn Thanks for your reply.

**Comment by david87v5** [comment]
@jinghaomiao Thanks for your reply.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
