### ISSUE TITLE
The visualizer for traffic light perception module doesn't pop out anything?

### ISSUE THREAD

**Issue by aseelam** [ApolloAuto/apollo#4262]
Hello everyone,
I am trying to use the tl_visualizer.cc under modules/perception/traffic_light/visualizer to visualize traffic lights. I wanted to know the procedure to use the visualizer given a map which was already run on a testing car.

I tried to load the map into apollo's map folder and tried to check the topics which are being published upon when that particular map was selected while apollo was running. Then, I tried to run the executable(perception traffic light visualizer) which is in bazel bin. Can someone confirm if it is the same procedure?

**Comment by ghdawn** [comment]
visualizer will show image when a light can be queried from map. May be you're not in the map zone or no signal is in front of you

**Comment by ghdawn** [comment]
There's another way to see the visualization:
vim modules/perception/conf/perception.conf
find --output_debug_img
set to true
rerun perception , when querying hdmap successful,you will see the video

**Comment by aseelam** [comment]
Thanks. That worked.
