### ISSUE TITLE
How to find out base_map.xml?

### ISSUE THREAD

**Issue by DrGabor** [ApolloAuto/apollo#4275]
Hi. I had ran the apollo demo_guide to observe lane-level map, but I cannot find out base_map.xml in apollo/modules/map/data/sunny_vale_big_loop, this folder is just empty (the size of folder is also zero). How can I find out base_map.xml?

**Comment by startcode** [comment]
The map is loaded in your docker environment folder `modules/map/data/sunny_vale_big_loop`

**Comment by mickeyouyou** [comment]
if you have more questions, you can reopen it at any time.
