### ISSUE TITLE
change "poll_result == RECIEVE_FAIL" to "poll_result == RECEIVE_FAIL"?

### ISSUE THREAD

**Issue by hushuitian** [ApolloAuto/apollo#4276]
Hi,R&D Team, Do we need to change "poll_result == RECIEVE_FAIL" to "poll_result == RECEIVE_FAIL" in the following source code files?
(1)modules/drivers/velodyne/velodyne_driver/src/driver/driver64.cpp
(2)modules/drivers/velodyne/velodyne_driver/src/driver/driver32.cpp
(3)modules/drivers/velodyne/velodyne_driver/src/driver/driver16.cpp

**Comment by apollodevcommunity** [comment]
well   it\'s really spelling mistakes in driver/input.h and video/socket_input.h——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=689

**Comment by storypku** [comment]
Hi @hushuitian, sorry for the delay in response. This will be closed in PR #13525
