### ISSUE TITLE
What is the algorithm used in prediction module？Are there any papers or detailed introduction for developers？

### ISSUE THREAD

**Issue by bssung** [ApolloAuto/apollo#4278]
What is the algorithms used in prediction module？Is there any paper or detailed introduction for developers？

**Comment by htabani** [comment]
You can read the docs for the perception available at: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/perception_apollo_2.5.md

Also, note that the object detection in Apollo 2.5 now uses YOLO which you can read their papers.

**Comment by linux-devil** [comment]
@htabani As per the document , lane detection is taking place in deep network module , but lane information is extracted from HD maps , any explanations ?

**Comment by JonathanJones92** [comment]
@kechxu are there any papers related to prediction module?

**Comment by natashadsouza** [comment]
@JonathanJones92 we do not currently have papers related to our Prediction module. However, it is a great suggestion and we will definitely work on having some documentation released on it. Thanks!

**Comment by yanbec** [comment]
Are there any news on this? I would really appreciate a (citable) paper on this and other algorithms Apollo ships with.

**Comment by natashadsouza** [comment]
@yanbec while we do not have papers released yet, we do have a description of how the module works [here](https://github.com/ApolloAuto/apollo/tree/master/modules/prediction). Please let me know if you have any additional questions. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as we have not heard back in a while. Feel free to reopen if you have additional questions. Thanks!
