### ISSUE TITLE
Add support for alternate IMU

### ISSUE THREAD

**Issue by joekale** [ApolloAuto/apollo#428]
We currently use a ProPak6 with a KVH 1750 IMU. We would like support for alternate IMU types to allow us to use our current set up without modification.

We have tried to check GPS status with our current setup but have not been able to get Apollo to recognize our GPS setup.

**Comment by lianglia-apollo** [comment]
My understanding is that you are using your own localization. If it is the case, you can follow the instructions at “modules/localization/README.md” to add your own method.

**Comment by YangHan101** [comment]
Apollo communicates with the novatel propak 6 only for the localization result and Inertial measurements. The type of IMU used should not matter as long as it is properly configured to work with the propak 6. Could you describe more about what your problem is?

**Comment by joekale** [comment]
This issue occurred many months ago, but I must have had some outdated information. It is good to know that different IMUs will not cause an issue. We were under the assumption that the hardware guide instructing the use of the ProPak6 with an IMU-IGM-A1 was a requirement. Is there any configuration that will need to be changed in the launch files to accommodate the different IMU data rates or will it work "out of the box" with any ProPak6 IMU combination?

**Comment by YangHan101** [comment]
Novatel's Propak6 has a list of supported IMU's, as you can see following the link below
https://docs.novatel.com/OEM7/Content/SPAN_Commands/CONNECTIMU.htm
As long as you are using IMU's on that list, Novatel should be able to communicate with it. As for your other question on the data rate, I am told that the GPS receiver can send imu data to us(or the computer) at any rate not exceeding the data rate at which the actual imu is sending data to the GPS receiver.

**Comment by Zhenni17** [comment]
Closing the issue.
