### ISSUE TITLE
As a developer, what can I do with localization? Or can I add something to the localization module? Apollo's algorithm for this module is provided in the form of a dynamic library. There is no explanation about the interface in this dynamic library. thank you！

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4282]

**Comment by apollodevcommunity** [comment]
the interface is in /usr/local/apollo/local_integ/include/lidar_locator.h and sins.h in docker. lidar_locator.h is lidar locator that input map and pointcloud and output pose. sins.h is like GNSS and IMU fuion localization. you can unit test  it and see modules/localization/msf/local_integ\\localization_lidar.cc to learn how to use.——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=688
