### ISSUE TITLE
 WebSocket connection to 'ws://192.168.31.134:8888/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by Answer27** [ApolloAuto/apollo#4285]
when i start the Apollo，i launch http://192.168.31.134:8888/，and connect to the homepage , but
 the demo doesn‘t work and is empty，why?

the chrome console says:
app.bundle.js:11 WebSocket connection to 'ws://192.168.31.134:8888/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404

how to solve that?

**Comment by mickeyouyou** [comment]
network ok ?
is there some errors in /apollo/data/log directory ?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response for a while. Feel free to write back if the issue persists.
