### ISSUE TITLE
Frames of reference

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#4286]
Looking at the document for reference frames, I understand that there is global/local frame (world) and the body frame (vehicle). Other than that, there is Lidar (velodyne64), IMU (imu), Camera (short_camera, long_camera) and Radar (radar) frames. The localization module outputs a transform from 'localization' to world. Now which frame is 'localization' ? Technically it should be vehicle to world. Which physical entity does 'localization' frame represent ?

**Comment by zhouyao4321** [comment]
Currently, frame "localization" refers a transform from IMU to world.

**Comment by natashadsouza** [comment]
Closing this issue as we have not heard back in a while. Feel free to reopen if you have additional questions. Thanks!
