### ISSUE TITLE
关于apollo2.5感知模块，是否可以选择使用lidar来做感知？

### ISSUE THREAD

**Issue by kxhlp** [ApolloAuto/apollo#4297]
关于apollo2.5感知模块，是否可以选择使用lidar来做感知，而不是目前的低成本方案？代码里面是否有选择的开关？

**Comment by jinghaomiao** [comment]
@kxhlp you can still use lidar to do obstacle detection and tracking like Apollo 2.0. Same code base for lidar based perception.

**Comment by kxhlp** [comment]
@jinghaomiao 请问一下，代码里面怎么做切换？代码改变大吗？还是说只要改变一个宏定义就可以了？文档里面没有看到相关的信息

**Comment by xiaohedu** [comment]
同问@kxhlp @jinghaomiao
