### ISSUE TITLE
Lattice planner implemetnation

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#4298]
Hi,

I want to understand the Lattice planner's implementation in Apollo. I understand the Lattice algorithm but it seems confused when I look into the implementation in Apollo. 
Can you provide some explanation of your approach or the paper publication of your implementation?

Thank you in advance

**Comment by YajiaZhang** [comment]
Hello,

Thanks for your interest. The lattice planner is based on the following paper with significant modifications. 
https://pdfs.semanticscholar.org/0e4c/282471fda509e8ec3edd555e32759fedf4d7.pdf

You can check out the paper first and let us know if you are interested in further discussion. 

Thanks
