### ISSUE TITLE
Running perception and prediction on the demo_2.5 bag file

### ISSUE THREAD

**Issue by hadiTab** [ApolloAuto/apollo#4307]
The demo_2.5 bag file has the output topic from the different modules recorded and simply plays them back in Dreamview. I want to replicate the results by actually running the modules. To do this I removed these two topics from the bag file: /apollo/perception/obstacles and /apollo/prediction and run the perception and prediction nodes manually by running:

`./scripts/perception_lowcost.sh start`
`./scripts/prediction.sh`

I would expect this to replicate the results we see from playing the bag files, it only detects the lane markers and does not detect the oncoming traffic. Is there something that I'm doing wrong?

Also, is there a way to visualize the images in /apollo/sensor/camera/obstacle/front_6mm ?
I tried to visualize them in rqt_image_view but it does not recognize the encoding (yuyv encoding?).

**Comment by linux-devil** [comment]
"it only detects the lane markers and does not detect the oncoming traffic" How did you manage to see the results ? Any pointers?

**Comment by hadiTab** [comment]
@linux-devil it may not actually be "seeing" those, but those are the only items published in the output topics for those two modules (/apollo/perception/obstacles and /apollo/prediction).

I'm also not able to run the perception lowcost visualizer as described [here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_perception_visualizer.md). Nothing happens after I launch it.

**Comment by snuffysasa** [comment]
@linux-devil @hadiTab 

Same problem here.  I also cannot run the perception lowcost visualizer and I also cannot view the  images in /apollo/sensor/camera/obstacle/front_6mm.

anyone figure this out?

I toggle camera view, then a small rectangle appears in top left corner doesn't appear to show anything...

Have you guys tried this fix ? https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md

**Comment by alexbuyval** [comment]
@hadiTab @linux-devil  @snuffysasa 
I have the same issue. I don't see any pop-up windows with the visualizer.
Did you manage the issue?
Thanks!

**Comment by hadiTab** [comment]
@alexbuyval  and @snuffysasa I have not been able to solve the issue yet.

**Comment by snuffysasa** [comment]
@alexbuyval @hadiTab @linux-devil 

I have not figured it out yet either.

Any updates?

**Comment by hadiTab** [comment]
@weidezhang @eugenegx @techoe @kechxu @gchen-apollo have any of you had a chance to check this out yet? Thanks.

**Comment by snuffysasa** [comment]
@hadiTab @linux-devil @alexbuyval 

@weidezhang @eugenegx @techoe @kechxu @gchen-apollo 

I solved my issues with these.  I had a couple. Posting for other people

First, there seems to be a bug in launching the perception module, it never initializes the gl frame viewer.   I did some debugging... and found a fix.

this is a quick trace

visualization_subnode.cc  ProcEvents() hangs on line 374:
---> if (!SubscribeEvents(event_meta, &events)) {

which causes it to never reach the important line 400:
--->frame_visualizer_->init();


The SubscribeEvents function hangs on line 219:
--->    while (event_manager_->Subscribe(event_meta.event_id, &event, true)) {

moving over to event_manager.cc function Subscribe on line 83.

This function creates an EventQueue, which seems to be defined in event_manger.h and seems to implement class ConcurrentQueue in modules/perception/lib/base/concurrent_queue.h

I am not sure if its a problem with the class or a glitch with the event manager..

But anyways, the first time the subscribe Queue is called the queue size is 0... (seems odd it should be 1, for the current item??)

but this results in 
-->queue->pop(event);
being called when the queue is empty... which causes it to just stall.

!!TLDR: I fixed this problem by simply adding:

-->  if (queue->size() ==  0)
-->    	return true;

before -->queue->pop(event);


This seems to make the gl visualizer initialize now, but I am worried I am doing other harm.

**Comment by techoe** [comment]
Matthew,
Thank you so much for digging into it! We will fix the issue ASAP.

Tae Eun

**Comment by mickeyouyou** [comment]
**How to show the front_image(`/apollo/sensor/camera/obstacle/front_6mm`) when play the demo_2.5.bag ?**

by default, Dreamview handler the topic `camera/image_raw` when  `FLAGS_use_navigation_mode` is true and `/apollo/sensor/camera/traffic/image_short` when `FLAGS_use_navigation_mode` is false ,like codes:
```cpp
if (FLAGS_use_navigation_mode) {
    AdapterManager::AddCompressedImageCallback(&ImageHandler::OnImage, this);
  } else {
    AdapterManager::AddImageShortCallback(&ImageHandler::OnImage, this);
  }
```

so Now Dreamview NOT support the topic `/apollo/sensor/camera/obstacle/front_6mm`  recorded in  demo_2.5.bag. if you want to show this topic, you need to add the configuration and code like :

Configuration: add 
```conf apollo/modules/dreamview/conf/adapter.conf
config {
  type: FRONT_IMAGE
  mode: RECEIVE_ONLY
  message_history_limit: 1
}
```
Code:
```cpp
if (FLAGS_use_navigation_mode) {
    AdapterManager::AddCompressedImageCallback(&ImageHandler::OnImage, this);
  } else {
    AdapterManager::AddImageFrontCallback(&ImageHandler::OnImage, this);
  }
```

then play the bag, you will see :
![image](https://user-images.githubusercontent.com/3821311/42496653-5773f284-8459-11e8-9fc1-591ad488ccc9.png)

**Comment by mickeyouyou** [comment]
siyang have enhanced the topic (`/apollo/sensor/camera/obstacle/front_6mm`) show in the Dreamview   #4920.

**Comment by liuyangly25** [comment]
I didn't see the pop up visualizer either on my ubuntu 16.04. Any updates?

**Comment by techoe** [comment]
Dreamview should be able to visualize camera topics. @hadiTab, If you still have an issue please let us know.

**Comment by techoe** [comment]
I am closing it since there is no update after last answer.
