### ISSUE TITLE
Problem of  Install Nvidia driver in docker libcudnn7 

### ISSUE THREAD

**Issue by c-xyli** [ApolloAuto/apollo#4311]
I was following the script of [run_perception_module on_your_local_computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)

In step 5 After download, install cuDNN by
`sudo dpkg -i libcudnn7-dev_7.1.1.5-1+cuda8.0_amd64.deb 
`
[Error:]

> (Reading database ... 191546 files and directories currently installed.)
> Preparing to unpack libcudnn7-dev_7.1.1.5-1+cuda8.0_amd64.deb ...
> Unpacking libcudnn7-dev (7.1.1.5-1+cuda8.0) over (7.1.1.5-1+cuda8.0) ...
> dpkg: dependency problems prevent configuration of libcudnn7-dev:
>  libcudnn7-dev depends on libcudnn7 (= 7.1.1.5-1+cuda8.0); however:
>   Package libcudnn7 is not installed.
> 
> dpkg: error processing package libcudnn7-dev (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  libcudnn7-dev

I have tried the solution of changing other type of installation package / exporting environment path / change it to local machine rather than docker image, all not working.

Please help me with the correct installation setting of the **libcudnn7**

**Comment by snuffysasa** [comment]
thanks this helped

**Comment by somubenz** [comment]
Change you current path to your downloaded folder then try to install.
It works for me.
