### ISSUE TITLE
official image is different from the image generated from dockerfile?

### ISSUE THREAD

**Issue by ImCabbage** [ApolloAuto/apollo#4312]
Hi, Apollo team,
I tried to build a new docker image using the dockerfile provided in the Apollo package. However, it seems that the supervisor version in the new docker image I build is 3.0b which is different from that I pull from the server (3.3.3). So I wonder if there is any difference between the dockerfile I pulled from your server and I built myself using your dockerfile. 
I think the problem is in the install file, you use apt install cmd which only brings 3.0b version. The problem of supervisor will lead to dreamviewer start problem.

Thanks.

**Comment by Zhenni17** [comment]
Hi @ImCabbage thank you for your interest in Apollo. To resolve the issue, please install Docker and then run the build an release, which you can also follow the steps listed here: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md

We will look into the dockerfile provided and will update soon.

**Comment by xiaoxq** [comment]
We don't rebuild everything from scratch every time, which might make our users pull a lot of data for a trivial change.
Instead, we just add an incremental layer on top of the old image. For example:
```
FROM <last_image>
RUN apt-get install -y <a new lib>
```
We also keep updating the Dockerfile, so it does cause some differences between the pulled image and the local built image.

Besides that, we are refactoring the Dockerfile to leverage the nvidia-docker base image. This effort is still in progress, which would also bring differences. We try to make the migration smooth, but please do let us know if you found anything not working well.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
