### ISSUE TITLE
Planning and Prediction maintained disapeared obstacles, BUG?

### ISSUE THREAD

**Issue by johanfong** [ApolloAuto/apollo#4317]
![image](https://user-images.githubusercontent.com/5377909/40778464-d49d3b96-6503-11e8-80e9-6e874d95135f.png)
如上图，这个障碍物是我用脚本模拟进去的，模拟脚本停掉后，topic: /apollo/perception/obstacles中已经没有障碍物，但是DreamView中还显示，planning还是会停止。
疑似是个BUG，Prediction返回了last prediction（timestamp和当前时间比，已经过去很久远），这种情况下，策略应该是丢弃这种很久前的障碍物吧？

**Comment by johanfong** [comment]
是在Apollo的2.5分支中跑的。

**Comment by jinghaomiao** [comment]
@johanfong prediction is triggered by perception. If perception is paused/stopped, prediction will be suspended. As planning is always use the latest frame from prediction (GetLatest()) and that's why the obstacle is still seen in dreamview and planning will still have the stop fence for this vehicle.

**Comment by johanfong** [comment]
@jinghaomiao 非常感谢！topic: /apollo/perception/obstacles输出只有Header的空Message，是不是表示Perception正常？
Perception是 paused/stopped，还是正常、只是没有障碍物，这两种情况怎么区分呢？

**Comment by johanfong** [comment]
尝试了一下，给topic: /apollo/perception/obstacles输出只有Header的空Message，可以清理last frame；但是如果Perception模块突然挂掉，这个last还存在。

**Comment by jinghaomiao** [comment]
@johanfong true.

**Comment by qianwenchao123** [comment]
@johanfong How did you add the purple obstacle into the scenario? Can you teach me how to do that? Thanks a lot.

**Comment by YafeiWangAlice** [comment]
@johanfong  @qianwenchao123, I am wondering aboout how did you add an obstacle into the dreamview too. Can you share this to me?
Thanks.

**Comment by johanfong** [comment]
@qianwenchao123 @YafeiWangAlice write some code：1、obstacles simulation 2、play them to the topic
apollo‘s source code has some tools（modules/tools/..）, but some has bugs，you need modify

**Comment by qianwenchao123** [comment]
@johanfong Can you give me some more details, such as which script you used for adding an obstacle into the dreamview? I am a beginner on Apollo. Thanks a lot for the help.

**Comment by YafeiWangAlice** [comment]
@johanfong hi，可以分享一下你在dreamview中模拟障碍物的脚本吗？或者这个脚本是什么原理，网站上查了各种资料，没有找到相应的方法。多谢！~

**Comment by johanfong** [comment]
@YafeiWangAlice apollo/moudles/tools/perceptions 里有个基本的脚本，有bug，你可以改改用

**Comment by johanfong** [comment]
@qianwenchao123 @YafeiWangAlice apollo/moudles/tools/perceptions 里有个基本的脚本，有bug，可以改改用；我写的是公司程序...

**Comment by YafeiWangAlice** [comment]
@johanfong ok~~多谢了~~

**Comment by Iqbalparvi** [comment]
@YafeiWangAlice @johanvon  can you please give me some idea to write  or modify code to test and find the bugs in prediction modules...it will be great help for me
thanks
