### ISSUE TITLE
Difference between navigation_lincoln.pb.txt and lincoln.pb.txt

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4318]
Hi,

I see two similar looking config file in `/module/control/conf`. They look like a loop up table.
What are the purposes/differences of `navigation_lincoln.pb.txt ` and `lincoln.pb.txt` ?

**Comment by Capri2014** [comment]
@wckorealsh They are serving for different purposes : navigation_lincoln is more for highway and Lincoln is for L4 level urban road.

**Comment by Capri2014** [comment]
@wckorealsh : First one assumes relative position and second one assumes absolute position

**Comment by wckorealsh** [comment]
Thank you. Sounds like two different sets of a look-up table.
But, can you please explain what did you mean by relative and absolute position? The position of what? relative to what?

Thank you!

**Comment by Capri2014** [comment]
@wckorealsh Navigation mode is for 2.5 which we only assume we have relative position information of vehicle information (with respect to lane markers) in control while in the other one we still use the absolute position (from GPS/IMU) in control

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
