### ISSUE TITLE
Query : Can I create my own HDmap using Mobileye kit and Lidar

### ISSUE THREAD

**Issue by linux-devil** [ApolloAuto/apollo#4319]
Q1. Will it be possible to generate map using hardware?
I can see Apollo/scripts/create_map_from_mobileye.sh , what will be the output of this script given all the necessary hardware is available? Will it generate HD map for localization and route planning?

Q2.  Is it possible to run and replay any other rosbag data in apollo dreamviewer? if no, is it possible to convert any other ros data into apollo compatible mode?

**Comment by linux-devil** [comment]
Q2. Is it possible to run and replay any other rosbag data in apollo dreamviewer? if no, is it possible to convert any other ros data into apollo compatible mode?

**Comment by apollodevcommunity** [comment]
Q1   you can use modules/tools/map_gen to generate map with trajectory.Q2   apollo3.0 and below support ros. apollo 3.5+ only support cyber. In apollo5.0 there is a rosbag_to_record tool to help you convert.——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=687
