### ISSUE TITLE
只有一台电脑，可以用百度的样例数据测试吗？

### ISSUE THREAD

**Issue by jec1key** [ApolloAuto/apollo#432]
想学习障碍物识别检测，手头就一台笔记本，从哪开始呢？github上的教程不够详细啊！

**Comment by lianglia-apollo** [comment]
You can start from https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md.

**Comment by westeast** [comment]
@jec1key 可以的，我就在win7 virtualbox中的ubuntu虚拟机里运行的：可参考这里https://zhuanlan.zhihu.com/p/29722428  百度Apollo1.5 自动驾驶编译运行及效果展示

**Comment by jec1key** [comment]
@westeast 我想弄清楚感知功能perception是如何运行的，代码里一个注释都没有，而且代码量又多，有关于这方面的讲解嘛？

**Comment by jzhuucla** [comment]
You may do the offline simulation and testing for perception on a laptop with GPU. Please see the document of "how_to_run_perception_module_on_your_local_computer.md" in docs/howto. We also provide a document "3d_obstacle_perception.md" to introduce the idea and algorithm details of each perception sub-modules in docs/specs. In addition, we provide a specific visualizer tool for offline simulation of the perception module's result with point cloud visualization. Please refer to "how_to_run_offline_perception_visualizer.md" in docs/howto.
