### ISSUE TITLE
Why does Apollo1.5 delete module decision

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#433]
apollo1.0 module decision : https://github.com/ApolloAuto/apollo/tree/r1.0.0/modules/decision
but apollo1.5 has no this module: https://github.com/ApolloAuto/apollo/tree/r1.5.0/modules

And I can not find a file that explains the change。。。。

**Comment by xiaoxq** [comment]
It's just moved into planning module, because they two are highly coupled for now.
See https://github.com/ApolloAuto/apollo/blob/master/modules/planning/proto/decision.proto

**Comment by westeast** [comment]
ok ,thanks~~
