### ISSUE TITLE
BUILD GPU error,  **cannot find -lgfortran**

### ISSUE THREAD

**Issue by c-xyli** [ApolloAuto/apollo#4331]
I was following the script of run_perception_module on_your_local_computer

After finished all the steps, In step 8  when I run
`./apollo.sh build_opt_gpu
`

> ERROR: /apollo/modules/planning/tools/BUILD:5:1: Linking of rule '//modules/planning/tools:planning_stats' failed (Exit 1)
> /usr/bin/ld: **cannot find -lgfortran**

> collect2: error: ld returned 1 exit status

Can someone help me how to solve it?

**Comment by zhxt** [comment]
@c-xyli This usually happened when the linker can not find the desire lib(libgfortran.so in this case).
So you can:
1. Check if it's installed inside docker with `apt-cache policy libgfortran-4.8-dev` or `dpkg -L  libgfortran-4.8-dev` (The answer could be yes if you're using the latest docker image)

2. If it's installed, then the reason could be the path of that lib is not in the default search path.  Maybe there are something goes wrong with the build env. You can try to clean and rebuild  again.  Or you can try to add a "linkopts" to the BUILD file to specify the lib path with '-L' option, but normally this is NO NEED to do it manually.

**Comment by Xiaoyang-Rebecca** [comment]
The libgfortran is located in the folder libgfortran/4.8, rather than libgfortran-4.8, see more 
https://askubuntu.com/questions/276892/cannot-find-lgfortran

**Comment by techoe** [comment]
@zhxt, Thank you for answering the question. @c-xyli, please let us know if you still have this issue. Thank you, Tae Eun

**Comment by c-xyli** [comment]
Problem solved , thx.

**Comment by natashadsouza** [comment]
Currently closing this issue as it is resolved.
