### ISSUE TITLE
How is "objectness" annotated in cnnseg in the 3d obstacle module ?

### ISSUE THREAD

**Issue by yzhou-saic** [ApolloAuto/apollo#4332]
There is "objectness" generated from the cnnseg network module.

1) What's the detailed definition of the "objectness", i.e., how is it different from the positiveness ?

2) how is "objectness" annotated in cnnseg in the 3d obstacle module ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
