### ISSUE TITLE
Custom Caffe framework is not open source

### ISSUE THREAD

**Issue by sap03cws** [ApolloAuto/apollo#4333]
The Caffe framework shipped with Docker ([download](https://apollocache.blob.core.windows.net/apollo-docker/caffe_x86.tar.gz); [installer](https://github.com/ApolloAuto/apollo/blob/r2.5.0/docker/build/installers/install_gpu_caffe.sh)) is not open source. It would be massively helpful should the source code be released. Improvements to perception modules like traffic light detection are only possible if the custom C++ layers can be modified.

Moreover, the [license](https://github.com/BVLC/caffe/blob/master/LICENSE) of Caffe expressly states that

> Redistributions in binary form must reproduce the above copyright notice [...] in the documentation and/or other materials provided with the distribution. 

of which the "copyright notice" includes

> Caffe uses a shared copyright model: each contributor holds copyright over their contributions to Caffe.

This is blatantly violated by the statement "_Copyright 2018 The Apollo Authors_" at the top of the [installer](https://github.com/ApolloAuto/apollo/blob/r2.5.0/docker/build/installers/install_gpu_caffe.sh). The ApolloAuto team is strongly urged to either amend the license accordingly, or release the source code as an explicit modification to the original Caffe framework.

**Comment by lianglia-apollo** [comment]
Copyrigth statement is added in perception documents. See https://github.com/ApolloAuto/apollo/pull/4341.
