### ISSUE TITLE
BUILD ERROR: /apollo/modules/common/adapters/BUILD:18:1

### ISSUE THREAD

**Issue by HITszzzc** [ApolloAuto/apollo#4334]
parallels@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] System memory [0.96G] is lower than minimum required memory size [2.0G]. Apollo build could fail.
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1501 targets (12 packages loaded).
INFO: Found 1501 targets...
ERROR: /apollo/modules/common/adapters/BUILD:18:1: C++ compilation of rule '//modules/common/adapters:adapter_manager' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 20.808s, Critical Path: 9.47s
FAILED: Build did NOT complete successfully
============================
[ERROR] Build failed!
[INFO] Took 35 seconds
============================
parallels@in_dev_docker:/apollo$

**Comment by lianglia-apollo** [comment]
Is it due to too few memory of the system? Notice the warning "System memory [0.96G] is lower than minimum required memory size [2.0G]. Apollo build could fail."
