### ISSUE TITLE
What are the advantages do one get being partner with Apollo?

### ISSUE THREAD

**Issue by linux-devil** [ApolloAuto/apollo#4335]
I wanted to understand the advantage of becoming partner with apollo over building apollo and making changes in the source code.

**Comment by linux-devil** [comment]
Any pointers?

**Comment by mickeyouyou** [comment]
From hardware, Apollo recommended reference hardware can be purchased at Baidu's channel price, with a guaranteed delivery period.

On data resources, full Apollo data open platform data can be used. Apollo Data Open Platform url : http://data.apollo.auto/?locale=zh-cn&lang=en

**Comment by linux-devil** [comment]
@mickeyouyou Can partner use this data to train models for commercial usage?

**Comment by mickeyouyou** [comment]
Yeah, of course.

Apollo advocates openness, so we also hope that everyone using the data can also contribute some other data to the Apollo community.

**Comment by linux-devil** [comment]
I
