### ISSUE TITLE
query: localization modules

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4336]
in directory modules/localization/msf  there are three directory that I don't know what's means or what's the use: 
They are : 
  common:
  local_map:
  local_tool:
  in directory local_map there are three directory(base_map,lossless_map,lossy_map)，what's means?
  in directory local_tool there are three directory(data_extraction,local_visualization,map_creation)，what's means?
   I  WANT TO KNOW, Please help me ! Thank you!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
