### ISSUE TITLE
When building st_boundary map, why 'forward_distance = vehicle_param_.length()+vehicle_param_.width() + obs_box.length() + obs_box.width();'?

### ISSUE THREAD

**Issue by Aidous** [ApolloAuto/apollo#4339]

**Comment by Aidous** [comment]
For safety?

**Comment by startcode** [comment]
This is an upper bound when estimating the overlap range between adc and obstacle box.

**Comment by Aidous** [comment]
@startcode Yeah, i understand what you mean, but why add width? Isn't it OK when only satisfy the longitudinal?

**Comment by Aidous** [comment]
@jilinzhou Ok, i understand. Thank you.
