### ISSUE TITLE
How to draw somthing in dreamview?

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#4340]
Hi,
I want to visualize some information when running Dreamview (like draw an arrow in front of the car).
Can you guys show me how to do that.
Thank you all.

**Comment by siyangy** [comment]
Dreamview uses https://github.com/mrdoob/three.js as graphics library. You can modify the frontend code to draw an arrow using the corresponding API of the library. After that you need to run a ./apollo.sh build_fe to compile.

**Comment by natashadsouza** [comment]
Closing this issue currently as it appears to be resolved.
