### ISSUE TITLE
How to load test targets in yolo_camera_detector?

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [ApolloAuto/apollo#4360]
Hi, 
I am able to build_gpu for the whole project. Now I need to test the module of perception independently.
I followed the instruction from [how to run *test.cc quickly  by ](https://github.com/ApolloAuto/apollo/issues/296) @zuomaidi52, but have problem of loading test image.  

`amba@in_dev_docker:/apollo
$ bazel test --config=unit_test //modules/perception/obstacle/camera/detector/yolo_camera_detector`

> 
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
> INFO: Analysed target //modules/perception/obstacle/camera/detector/yolo_camera_detector:yolo_camera_detector (0 packages loaded).
> INFO: **Found 1 target and 0 test targets**...
> Target //modules/perception/obstacle/camera/detector/yolo_camera_detector:yolo_camera_detector up-to-date:
>   bazel-bin/modules/perception/obstacle/camera/detector/yolo_camera_detector/libyolo_camera_detector.a
>   bazel-bin/modules/perception/obstacle/camera/detector/yolo_camera_detector/libyolo_camera_detector.so
> INFO: Elapsed time: 0.238s, Critical Path: 0.00s
> INFO: Build completed successfully, 1 total action
> **ERROR: No test targets were found, yet testing was requested**

How can I replace the test.image with my own images?
Or where could I load the folder path of my own test images?

**Comment by techoe** [comment]
@Xiaoyang-Rebecca , 
Please take a look at the test code at 
apollo/modules/perception/obstacle/camera/detector/yolo_camera_detector/yolo_camera_detector_test.cc
You can change the test procedures as you want. 

To test your own image, either change the image name (test.jpg) in yolo_camera_detector_test.cc to your own image
or replace your image with 
apollo/modules/perception/data/yolo_camera_detector_test/test.jpg 

Thank you,
Tae Eun

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.

**Comment by Xiaoyang-Rebecca** [comment]
Thanks！

**Comment by mryao57** [comment]
> Thanks！

can you help me what to do with "No test targets were found, yet testing was requested."Thanks very much!
