### ISSUE TITLE
typo in apollo/modules/localization/msf/README.md

### ISSUE THREAD

**Issue by muare** [ApolloAuto/apollo#4361]
in file apollo/modules/localization/msf/README.md

There is a typo.

"Gnerate Localization Map"

It should be Generate Localization Map

**Comment by mickeyouyou** [comment]
Feel free if you pull a request for that.

**Comment by Zhenni17** [comment]
Hi @muare, thank you for pointing that out! The typo has been fixed. Please let us know if you came across more issues. :)

**Comment by muare** [comment]
cool

**Comment by Zhenni17** [comment]
closing the issue.
