### ISSUE TITLE
请确认车辆定位状态为56，否则标定程序不会开始采集数据，56具体为什么意思？

### ISSUE THREAD

**Issue by NEUdeep** [ApolloAuto/apollo#4363]
请确认车辆定位状态为56，否则标定程序不会开始采集数据，这个56具体为什么意思？是定位的车身状态的那个参数？麻烦了？

**Comment by jinghaomiao** [comment]
@NEUdeep Position type 56 tells that the pose info for the ego vehicle is in good state and achieves the desired precision.

**Comment by NEUdeep** [comment]
Duplicate of #thank you,man.

**Comment by Zhenni17** [comment]
Seems OP's issue has resolved. Closing the issue and feel free to open an new issue you have other question!

**Comment by xinwf** [comment]
56是卫星数据包中的一个值，为56时表示是rtk::fixed定位模式，最精确的定位模式，具体哪个包忘了
