### ISSUE TITLE
Problem of unit test

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [ApolloAuto/apollo#4370]
$ code
Open project Apollo
  Tasks -> Run Build Task

> ============================
> [ OK ] Build passed!
> [INFO] Took 17 seconds
> ============================

  Tasks -> Run Test -> Selet Unit Test

>external/bazel_tools/tools/test/test-setup.sh: line 169: 12429 Illegal instruction     (core dumped) "${TEST_PATH}" "$@"

**Comment by jinghaomiao** [comment]
Please run the unit test with ./apollo.sh test

**Comment by Xiaoyang-Rebecca** [comment]
The results are the same @jinghaomiao

**Comment by jinghaomiao** [comment]
17 seconds are definitely too short for building Apollo. Please do a bazel clean and rebuild the system. Are you doing it inside docker?

**Comment by Xiaoyang-Rebecca** [comment]
It works! 
Insider docker , ./apollo.sh test, thanks!
