### ISSUE TITLE
GEM vehicle setting?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4377]
Hi team Apollo,

I have noticed that there is a canbus config for GEM vehicle.
Are there controller (lateral and longitudinal motion) for GEM vehicle too?

What are the necessary changes to test Apollo in the GEM vehicle?

Thank you.

**Comment by jinghaomiao** [comment]
@wckorealsh motion planning is the same for all vehicles. GEM has it's own dedicated controller though.

**Comment by wckorealsh** [comment]
Thank you @jinghaomiao ,

So, to run GEM, 
1)  Change 'canbus_conf_file=modules/canbus/conf/canbus_conf.pb.txt' to `canbus_conf_gem.pb.txt` 
      in `module/canbus/confcanbus.conf` 
2)  Change '--control_conf_file=modules/control/conf/lincoln.pb.txt' in `modules/control/conf' to something else?

Does step 2 necessary?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
