### ISSUE TITLE
Problem of ContiRadarCanbus

### ISSUE THREAD

**Issue by Brox0931** [ApolloAuto/apollo#4387]
HI Apollo,

我們在Trace ContiRadarCanbus時, 有個困惑就是關於ContiRadarCanbus::PublishSensorData()這個Function什麼時候會被呼叫?
從ContiRadarCanbus.cc 中並未發現任何呼叫PublishSensorData()的程式碼

而整個Apollo唯一有呼叫到PublishSensorData()卻是在SensorCanbus 
ContiRadarCanbus和SensorCanbus也沒有繼承關係, 因為我們對於ContiRadarCanbus如何publish Radar Data 感到不解

麻煩大家協助解惑

謝謝

**Comment by Brox0931** [comment]
Hi @Capri2014 , @jinghaomiao,

Could you help me to clear something up for ContiRadarCanbus?

Thanks.

**Comment by jinghaomiao** [comment]
@Brox0931 Please refer to https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/radar/conti_radar/conti_radar_message_manager.cc to see how ContiRadarMessage is published.

**Comment by Brox0931** [comment]
@jinghaomiao Thanks, very clear.
