### ISSUE TITLE
How to deal with unix:///tmp/supervisor.sock refused connection when start the HMI?

### ISSUE THREAD

**Issue by JoelinChee** [ApolloAuto/apollo#4388]
After I install the docker and build the apollo, I met the problem 
Started supervisord with dev conf
Start roscore...
voice_detector: started
unix:///tmp/supervisor.sock refused connection
when start the HMI.
Does anyone met this problem and how to deal with it? 
THX

**Comment by Fred159** [comment]
I got a error like 
voice_detector : started
dreamview: ERROR (spawn error)

I don't know why it happens. 
And the localhost:88888 can't open either

**Comment by JoelinChee** [comment]
Thank you for your reply, but when I followed the what startcode's instruction, the results are as follows. There are still some problems.
**************************************************************************************************************************
root@st-HP-Z840-Workstation:/etc# echo supervisord.conf > supervisord.conf && sudo mv supervisord.conf /etc/
root@st-HP-Z840-Workstation:/etc# supervisord -c /apollo/modules/tools/supervisord/dev.conf
The program 'supervisord' is currently not installed. You can install it by typing:
apt-get install supervisor
************************************************************************************************************************
root@st-HP-Z840-Workstation:/etc# apt-get install supervisor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-meld3
The following NEW packages will be installed:
  python-meld3 supervisor
0 upgraded, 2 newly installed, 0 to remove and 342 not upgraded.
Need to get 283 kB of archives.
After this operation, 1,624 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe python-meld3 amd64 0.6.10-1 [39.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe supervisor all 3.0b2-1ubuntu0.1 [244 kB]
Fetched 283 kB in 4s (61.9 kB/s)     
Selecting previously unselected package python-meld3.
(Reading database ... 183725 files and directories currently installed.)
Preparing to unpack .../python-meld3_0.6.10-1_amd64.deb ...
Unpacking python-meld3 (0.6.10-1) ...
Selecting previously unselected package supervisor.
Preparing to unpack .../supervisor_3.0b2-1ubuntu0.1_all.deb ...
Unpacking supervisor (3.0b2-1ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Setting up python-meld3 (0.6.10-1) ...
Setting up supervisor (3.0b2-1ubuntu0.1) ...
Starting supervisor: supervisord.
Processing triggers for ureadahead (0.100.0-16) ...
*************************************************************************************************************************
root@st-HP-Z840-Workstation:/etc# supervisord -c /apollo/modules/tools/supervisord/dev.conf
*************************************************************************************************************************
root@st-HP-Z840-Workstation:/etc# supervisorctl status
Traceback (most recent call last):
  File "/usr/bin/supervisorctl", line 9, in <module>
    load_entry_point('supervisor==3.0b2', 'console_scripts', 'supervisorctl')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py", line 1113, in main
    options.realize(args, doc=__doc__)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1497, in realize
    Options.realize(self, *arg, **kw)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 305, in realize
    self.process_config()
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 313, in process_config
    self.process_config_file(do_usage)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 344, in process_config_file
    self.read_config(self.configfile)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1511, in read_config
    config.readfp(fp)
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: supervisord.conf, line: 1
'supervisord.conf\n'
****************************************************************************************************************************

**Comment by zhxt** [comment]
@JoelinChee hi, 1:  You need do this inside docker.  2: That command is "echo_supervisord_conf" , NOTE there are two underscores.

**Comment by zhxt** [comment]
@Fred159 Please refer to [FAQ Q2](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md). You may probably need to rebuild pcl lib if your CPU does not support FMA3.

**Comment by JerryOpenix** [comment]
Still failed, I follow below steps:
1. root@in_dev_docker:/apollo# echo_supervisord_conf > supervisord.conf && sudo mv supervisord.conf /etc/
2. supervisord -c /apollo/modules/tools/supervisord/dev.conf
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
For help, use /usr/local/bin/supervisord -h
3. root@in_dev_docker:/apollo# sudo supervisorctl status
unix:///tmp/supervisor.sock no such file

**Comment by zhxt** [comment]
try to run supervisorctl cmd with parameter '
-c /apollo/modules/tools/supervisord/dev.conf '

**Comment by JoelinChee** [comment]
st@in_dev_docker:/apollo$ echo_supervisord.conf > supervisord.conf && sudo mv supervisord.conf /etc/
bash: echo_supervisord.conf: command not found

it says: command not found.

**Comment by JoelinChee** [comment]
Worse still....
root@in_dev_docker:/apollo# echo_supervisord.conf > supervisord.conf && sudo mv supervisord.conf /etc/
bash: echo_supervisord.conf: command not found

**Comment by Fred159** [comment]
So how can I build PCL library in docker container?
`
sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
sudo apt-get update
sudo apt-get install libpcl-all`
Should I run these code in linux docker container?

**Comment by zhxt** [comment]
@Fred159 no, please find the answer in #3615

**Comment by zhxt** [comment]
@JoelinChee I had wrote a NOTE there. But it seems no people cares :D

**Comment by zhxt** [comment]
@JoelinChee Please check if you have multiple supervisord running.  If yes, kill them and run bootstrap.sh again.

**Comment by balazon** [comment]
I encountered this issue too. When I make a fresh build (build_gpu/build_opt_gpu), the build ran successfully but the bootstrap fails. First it starts with the "no such file" for the sock, then following some of your suggestions it will instead change to the "refused connection", but I could not get rid of that. 
I deleted the supervisor, and installed it again ( + echo_supervisord_conf > /etc/supervisord.conf)
I tried to add the config to these lines in bootstrap.sh:
```
supervisorctl start monitor > /dev/null
supervisorctl start dreamview
```
-->
```
supervisorctl -c /apollo/modules/tools/supervisord/dev.conf start monitor > /dev/null
supervisorctl -c /apollo/modules/tools/supervisord/dev.conf start dreamview
```
Tried to change the path to /var/run instead of /tmp in dev.conf
Tried to add  --tmpfs /var/run/ to docker run command
like suggested [here](https://github.com/Supervisor/supervisor/issues/654#issuecomment-230530075)
Unfortunately none of these worked.

If there were multiple supervisord running how would I check that, and kill those services? Can they be found with ps command, or do I have to kill them with service stop command?

specs: ubuntu 14.04, mostly followed this tutorial:
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md
I skipped step 1, since that looked like it was already included in dev_start, I used nvidia-384.130 driver, which looked good, since nvidia-smi worked inside docker. Don't know if it's relevant, but I have installed nvidia-docker on host.

I could start dreamview with this command:
bash scripts/dreamview.sh
But the full perception is probably not working properly when playing back the demo 2.5 rosbag (for eg. I have no camera picture on top-left side)

I don't really know what to try next, any suggestions are welcome

**Comment by snuffysasa** [comment]
I am having all the same problems as @balazon 

unix:///tmp/supervisor.sock refused connection

but I cannot launch dreamview with scripts/dreamview.sh

Also, I just got done reinstalling Ubunutu,  and also used the guide that you linked about running perception module locally.

but before reinstall I was also having issues with getting demo 2.5 rosbag to play and get the camera picture to show up

**Comment by simon750324** [comment]
@balazon 
I met the same problem like yours. I cannot run dreamview successfully by "bash scripts/bootstrap.sh". However I can run dreamview successfully "bash scripts/dreamview.sh".

You mention that "But the full perception is probably not working properly when playing back the demo 2.5 rosbag (for eg. I have no camera picture on top-left side)". If you just want to see the camera view, you can try to play other rosbag(apollo_2.0_camera_sample.bag).

**Comment by artyfarty** [comment]
Well you can avoid this issue by not using sock files. Remove `[unix_http_server]` section and use this combo:

```
[inet_http_server]
port:9007
[supervisorctl]
serverurl=http://127.0.0.1:9007
```

**Comment by simon750324** [comment]
@artyfarty Thanks, it works.

**Comment by wfgsy101** [comment]
I also meet the issues " unix:///tmp/supervisor.sock refused connection" these few days, 
after rebuild some modules , when running command 'bash scripts/bootstrap.sh' , this issue come up, 
but we can ignore this error, and run command ' bash scripts/dreamview.sh ' to launch the dreamview to  go on to next step

**Comment by simon750324** [comment]
@wfgsy101 
You can try @artyfarty 's suggestion to use "inet_http_server" instead of "unix_http_server".

**Comment by xiaoxq** [comment]
Supervisor is not a good way for development. In recent change (https://github.com/ApolloAuto/apollo/commit/67fad1f572b3f1973b695af5bab093546ee7fa0d), I have removed it from debugging mode.
However, if you are using Apollo for some production scenarios, Supervisor could provide a second chance to recover the modules, which makes the more robust. Pass "--prod_mode" when starting dreamview for such use case.

**Comment by wfgsy101** [comment]
you can ignore it ，go on to run bash scripts/dreamview.sh to launch the dreamview.sh




| |
吴福刚
邮箱：18286115070@163.com
|

签名由 网易邮箱大师 定制

On 08/16/2018 15:20, jt387 wrote:

@artyfarty I got the same error, which file is to be modified? Is it modules/tools/supervisord/dev.conf?
I modified the dev.conf, but still got the error

**Comment by artyfarty** [comment]
@jt387 no idea, i'm not related to this project and have no idea what it is. This discussions pops in top search results regarding supervisor sockfile problem.

**Comment by jt387** [comment]
@wfgsy101 @artyfarty Thanks!    I tried the method, it worked, @wfgsy101.   And I tried the xiaoxq's method later, it also worked. Thank you, guys!

**Comment by CCodie** [comment]
@jt387 Hi, I exactly got the same problem.
Can you please explain more detail how you solved this problem??
I installed --branch r3.0.0 and I changed both of `/apollo/modules/tools/supervisord/dev.conf` and `/etc/supervisord.conf` like below.
```
;[unix_http_server]
;file=/tmp/supervisor.sock   ; the path to the socket file
;chmod=0700                 ; socket file mode (default 0700)
;chown=nobody:nogroup       ; socket file uid:gid owner
;username=user              ; default is no username (open server)
;password=123               ; default is no password (open server)

[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; ip_address:port specifier, *:port for all iface
;username=user              ; default is no username (open server)
;password=123               ; default is no password (open server)

...

[supervisorctl]
;serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
serverurl=http://127.0.0.1:9001 ; use an http:// url to specify an inet socket
;username=chris              ; should be same as in [*_http_server] if set
;password=123                ; should be same as in [*_http_server] if set
;prompt=mysupervisor         ; cmd line prompt (default "supervisor")
;history_file=~/.sc_history  ; use readline history if available
```
But when I'm trying to run bash scripts/bootstrap.sh the error occurs.
```
@in_dev_docker:/apollo$ bash scripts/bootstrap.sh 
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: ERROR (spawn error)
```
I would really appreciate it if you could help. Thanks !
