### ISSUE TITLE
how to use modules/tools/mapshow/mapshow.py

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#4391]
can you give me an example of how to use that tool?
I read the readme it says 
```bash
python mapshow.py -m /path/to/map/file
```
but I dont know what is path to map file

Thank you.

**Comment by startcode** [comment]
The path is 
`/apollo/modules/map/data/sunnyvale_big_loop/base_map.bin`
But you will only be able to see this file in docker environment.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
