### ISSUE TITLE
SL coordinate intial point?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4414]
Hi, 

Where is the origin of SL coordinate? Is this the closest point on the reference line from the current vehicle position or the beginning of the reference curve?
Thank you.

**Comment by jinghaomiao** [comment]
The origin of SL coordinate is the center point at a starting point of a lane.

**Comment by lesun90** [comment]
I have one related question, the lattice planner use x-y coordinate to check for collision, is it correct?
I see there are 3 coordinate systems used in Apollo: x-y,s-l, and Frenet, and it begins the confusion now, can you make a summary of what system should be used in what case? 
Thank a lot.

**Comment by kk2491** [comment]
@lesun90 @jinghaomiao ... Hi Guys.. I have the same confusion.

**Comment by liujiwei777** [comment]
@lesun90 @kk2491 
            Frenet coordinates and SL coordinates are the same thing. SL coordinates can be converted to XY coordinates. Apollo's SL is used for path planning, ST is used for velocity planning, and ST is used for collision detection.

**Comment by natashadsouza** [comment]
Closing this issue as we have not heard back in a while. Feel free to reopen if you have additional questions. Thanks!
