### ISSUE TITLE
How does co-train network work? [Question of Perception Module]

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [ApolloAuto/apollo#4416]
Hello,

In the algorithm description, it mentioned the [perception module](https://github.com/ApolloAuto/apollo/blob/5606407263886b0019cd1de1b5b1f3a3deff1614/docs/specs/perception_apollo_2.5.md) implements a **co-trained task** for deep learning using a same YOLO_V2 network. From my understanding,it means one single network of YOLO detects the lane and vehicle objects at the same time.

However, in the class type file found in, [yolo.proto](https://github.com/ApolloAuto/apollo/blob/111a7b2e2d00f989d6e52c0ecfdea1a828e6869b/modules/perception/obstacle/camera/detector/yolo_camera_detector/proto/yolo.proto#L19) after build, only 4 types of vehicle are provided:
       
- **vehicle, bicycle, pedetrain,unknown**

So where is the land detection class? Does it means land detection are implemented in another network?

**Comment by techoe** [comment]
seg_blob is the segmentation output of lane line. It is a co-trained network.
