### ISSUE TITLE
Changing the compiler to GCC6.1 or above

### ISSUE THREAD

**Issue by gulshan216** [ApolloAuto/apollo#4421]
I am trying to use certain external libraries which are supported only with the C++14 standard. Unfortunately the default GCC v4.8.4 from Apollo doesn’t support C++14. Hence i run into compilation issues while trying to use these external libraries. Could someone please let me know how to update the compiler to the most recent GCC compiler version in Apollo?

**Comment by jinghaomiao** [comment]
Docker provides a universal build environment for all developers. We encourage developers to use the provided docker and research the possibilities of upgrading from existing docker environment on their own.

**Comment by freeHackOfJeff** [comment]
Btw, to acclerate the progress Apollo deployment as well as run it smoothly, it's better to use C++0x11 rather than C++14 or even C++17 in terms of the compatibility upon the language syntax, etc...

**Comment by johnmcfarlane** [comment]
> research the possibilities of upgrading from existing docker environment on their own

Is that not what the OP is doing?

**Comment by storypku** [comment]
This issue should have been fixed now in master HEAD, where full C++ 14 support has been made possible.
Sorry for the long overdue.
