### ISSUE TITLE
how to check imutoantoffset saved in device

### ISSUE THREAD

**Issue by qwzju0222** [ApolloAuto/apollo#4427]
The method you descript is too difficult for me to understand. Could you write it more specifically？I have no idea about the commands "screen" and "log". Are they linux commands?

**Comment by YangHan101** [comment]
If you are using NovAtel's pp6 or A1 modules. You can go to their website and download their connect program and usb driver and install them on a windows PC. Try this link https://www.novatel.com/support/info/documents/926

Open the "NovAtel Connect"program, and connect to the GPS receiver through USB or serial port. You should see a console where you can communicate with the GPS receiver. 

"LOG" command is NovAtel's build-in command. For more info, there is a very thorough document. https://www.novatel.com/assets/Documents/Manuals/om-20000129.pdf
Using LOG command, you can ask the receiver to output the system status, settings and solutions to the console or to specific communication ports (COM, ICOM, NCOM, USB and so on)

Screen is a linux package from my understanding. But I could be wrong.

**Comment by YangHan101** [comment]
Also if you prefer work on linux, you can install a software called "minicom". Through minicom, you can talk to the serial/USB ports on the receiver. Once you launch 'sudo minicom -D /dev/[port you connected with cable]', you can also use LOG command to output the GPS receiver's status, settings, and solutions.

**Comment by YangHan101** [comment]
If you would like to see the IMUTOANTOFFSETS setting in the receiver. 
Establish the connection as above and type "LOG IMUTOANTOFFSETS"

**Comment by qwzju0222** [comment]
thx for your help
