### ISSUE TITLE
 http://localhost:8888/ not found

### ISSUE THREAD

**Issue by vingtfranc** [ApolloAuto/apollo#4428]
Hello

I would like to compile and run Apollo from a fresh Ubuntu 14.04. Everything seems to build properly but I have no access to the Dreamview web page.

Here's what I have tried:
```
bash docker/setup_host/install_docker.sh
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
./apollo.sh clean
./apollo.sh build_no_perception dbg # I don't have a GPU
bash scripts/bootstrap.sh
```

build seems to run fine:
```
...
INFO: Elapsed time: 815.158s, Critical Path: 47.84s
INFO: Build completed successfully, 6211 total actions
============================
[ OK ] Build passed!
[INFO] Took 835 seconds
```

and Dreamview is supposed to have started:
```
$ bash scripts/bootstrap.sh
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: started
Dreamview is running at http://localhost:8888
```

However, when I try to open http://localhost:8888 on firefox, I get a page not found error.
Is there anything I did wrong?

Also, note that I was able to access the dreamview by using a release:
`bash docker/scripts/release_start.sh`
(but I would like to modify Apollo's code so it is not what I want)

Thank you

**Comment by mickeyouyou** [comment]
Generally, running dev container will be much more developer-friendly.
Actually we are going to retire the release process, which has already been a little out of maintenance.

**Comment by zhxt** [comment]
@vingtfranc hi, [here](https://github.com/zhxt/apollo/wiki/FAQ) are some thoughts on how to solve this kind of problems.  You can also find some hints in [FAQ Q2](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md) .
Hope this will help.

**Comment by vingtfranc** [comment]
Thank you. It was indeed an issue with PCL
https://github.com/ApolloAuto/apollo/issues/3615#issuecomment-380133923 solved my problem
