### ISSUE TITLE
Radar data fail to write using export_sensor_data

### ISSUE THREAD

**Issue by linux-devil** [ApolloAuto/apollo#4429]
Steps followed :
1 . Run export sensor data using command:
/apollo/bazel-bin/modules/perception/tool/export_sensor_data/export_sensor_data

2. Play ROS bag :
rosbag play -l demo_2.5.bag 

3. I get the following error :

![screen shot 2018-06-07 at 11 43 10 am](https://user-images.githubusercontent.com/307810/41081397-4f60bed6-6a48-11e8-9454-97ef01eaa79b.png)

`I0607 06:05:21.639255 59273 export_sensor_data.cc:201] FRAME_STATISTICS:Radar:Start:msg_time[1514497059.449670076]:cur_time[1528351521.639252901]:cur_latency[13854462189.582824707]
I0607 06:05:21.639360 59273 export_sensor_data.cc:230] get radar trans pose succ. pose: 
0000.561109 0000.827742 00.00086714 00000587505
00-0.827233 0000.560726 000.0356905 4.14068e+06
000.0290563 0-0.0207435 0000.999363 000-29.3781
00000000000 00000000000 00000000000 00000000001
I0607 06:05:21.639434 59273 export_sensor_data.cc:243] radar file pre: /apollo/data2/radar/1514497059.3796701
E0607 06:05:21.639641 59273 export_sensor_data.cc:89] Failed to write radar msg.
I0607 06:05:21.639664 59273 export_sensor_data.cc:101] Failed to write pose.
I0607 06:05:21.639684 59273 export_sensor_data.cc:119] Failed to write velocity.
I0607 06:05:21.645853 59272 export_sensor_data.cc:252] localization timestamp:1514497059.522963285
I0607 06:05:21.645922 59271 export_sensor_data.cc:252] localization timestamp:1514497059.523327351
I0607 06:05:21.646903 59273 export_sensor_data.cc:252] localization timestamp:1514497059.532790661`

**Comment by linux-devil** [comment]
Had to create directory and its resolved .

**Comment by willsiriusAD** [comment]
I am having the same issue. which directory that you had to create?  Thank you.
