### ISSUE TITLE
apollo can not record data when set transort_mode is 1

### ISSUE THREAD

**Issue by echotor** [ApolloAuto/apollo#4432]
我在apollo docker中将transort_mode设置为非共享内存模式，如下：

```
############################################################
#
# ### transport_mode ###
# Choose transport mode, in which nodes communicate with each other.
#
# 0: shared memory, default
# 1: socket
#
# ### topic_white_list ###
# Exclude some topics, which will be transported in socket mode.
# This key takes effect only when transport_mode is 0.
#
############################################################

transport_mode: 1

topic_white_list: ["/shm_sample1", "/shm_sample2"]
```

在Apollo框架下运行各个模块，发现rostopic echo能够出来数据，但是用rosbag record无法录数据。
请问这是一个bug吗？

**Comment by echotor** [comment]
增加下其他测试情况（都是在设置transport_mode为1的情况下）：
1、启动Apollo模块，比如monitor，通过rostopic echo能够看到类似/apollo/monitor/system_status的数据，但是rosbag record记录不了对应topic数据
2、使用标准ros开发一个全新的package，直接发布protobuf或者标准ros message类型数据，通过rostopic echo或者rosbag record都能够得到数据

**Comment by echotor** [comment]
最终发现docker系统的yaml-cpp和apollo bazel编译使用的yaml-cpp版本不一致导致的，前者为0.5.1,后者采用0.5.3,这样直接导致修改transort_mode配置文件不生效

这应该是一个bug吧

**Comment by quning78** [comment]
Yes, it seems the incompatibility between docker and bazel. I will let our tools and integration team know about this.

**Comment by natashadsouza** [comment]
@echotor please clone the latest version of Apollo. The issue should be resolved. Thanks!

**Comment by echotor** [comment]
@natashadsouza OK. Thanks!

**Comment by xinwf** [comment]
@echotor, 你是如何获得apollo编译使用的版本的，我这边运行感知的时候也报了和transport_mode相关的错误，但错误内容是：
```
[33m[ WARN] [1545890041.519856091]: transport file: /home/tmp/ros/etc/ros/transport_mode.yaml is not map[0m
[33m[ WARN] [1545890041.519992122]: Parse transport_mode file failed[0m
```
我很奇怪，为什么会认为这是一个map

**Comment by echotor** [comment]
@xinwf apollo编译时的版本通过WORKSPACE文件能看出来的

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
