### ISSUE TITLE
RTK player in python and cc file difference?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4434]
Hi Apollo team,

I saw two similar files `rtk_player.py` and `rtk_replay_player.cc`.  What is their purpose and how they different each other?

Thank you.

**Comment by jinghaomiao** [comment]
Same algorithms coded in different languages.

**Comment by YajiaZhang** [comment]
We developed a python version firstly. The C++ version is developed later to cover the major functionalities of the python version and best fits our current framework.

**Comment by wckorealsh** [comment]
@jinghaomiao @YajiaZhang ,
Thank you. Would you recommend to use c++ version then?

**Comment by jilinzhou** [comment]
Much more configuration parameters or setup are needed to start the c++ planning module. If you just want a simple rtk playback, python version is way to go.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved. Thanks @jilinzhou!
