### ISSUE TITLE
rosbag_helper.py can not be executed

### ISSUE THREAD

**Issue by hlchen1043** [ApolloAuto/apollo#4442]
I'm trying to use rosbag_helper.py to fetch the off-line demo file while it has the following message:
  File "./docs/demo_guide/rosbag_helper.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Seems like something wrong with the rosbag_helper file?

**Comment by jinghaomiao** [comment]
I don't see any issues on my side. Please double check.

**Comment by startcode** [comment]
Probably because of this issue: https://github.com/ApolloAuto/apollo/pull/4456
