### ISSUE TITLE
Clarification for Projection Matrix - intrinsic camera calibration?

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo#4444]
Hi,

I followed the steps in you calibration [guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md)

I used the MATLAB tool box to generate the intrinsic parameters. I successfully get the K matrix and Distortion parameters. How do I generate the Projection matrix needed in the intrinsic.yaml files? It doesn't look like a direct transformation of P = K*[R|T]. How is the matrix being used for a mono camera? Can someone please clarify? It is not very clear from the documentation

**Comment by techoe** [comment]
You don't have to put anything for the projection matrix. The example file is old. Any value in projection matrix will be ignored.

**Comment by agarwalsid** [comment]
thanks @techoe, will do so.
