### ISSUE TITLE
may i know if there is a document that explains the architecture/design of this SW ?

### ISSUE THREAD

**Issue by kcpinnaka** [ApolloAuto/apollo#446]

**Comment by Zhenni17** [comment]
Hi @kcpinnaka ,

We are working on a blog that explains the architecture of Apollo SW stack. Please stay tuned.

Thank you for using Apollo!

Best,
Zhenni - Apollo Community Manager

**Comment by natashadsouza** [comment]
@kcpinnaka there is one for Apollo 3.0 that can be found here: [link](https://github.com/natashadsouza/apollo/blob/master/docs/specs/Apollo_3.0_Software_Architecture.md)
Please let me know if you have any questions! Thanks!
