### ISSUE TITLE
Docker command not found

### ISSUE THREAD

**Issue by JihyunYoon** [ApolloAuto/apollo#4464]
Hi I followed all instruction and no problem,when I tried to type command 
bash apollo_docker.sh gen
got these errors. Any Ideas?
apollo_docker.sh: line 49: docker: command not found
/apollo/docker/scripts/restart_map_volume.sh: line 32: docker: command not found
/apollo/docker/scripts/restart_map_volume.sh: line 33: docker: command not found
/apollo/docker/scripts/restart_map_volume.sh: line 32: docker: command not found
/apollo/docker/scripts/restart_map_volume.sh: line 33: docker: command not found
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20180530_1312 ...
docker/scripts/dev_start.sh: line 210: docker: command not found
[ERROR] Failed to pull docker image.
apollo_docker.sh: line 78: docker: command not found
apollo_docker.sh: line 82: docker: command not found
apollo_docker.sh: line 87: docker: command not found
apollo_docker.sh: line 96: docker: command not found
apollo_docker.sh: line 115: docker: command not found
apollo_docker.sh: line 116: docker: command not found
apollo_docker.sh: line 117: docker: command not found
apollo_docker.sh: line 118: docker: command not found

**Comment by bohell** [comment]
Have you installed docker?

**Comment by Grayhu07** [comment]
For previous release of Apollo, there is a script called install_docker.sh. But some developers found that the script did not work sometimes, so the only way to install docker now is through it's official website to install [DOCKER CE](www.docker.com) and follow the official install guide.

**Comment by Capri2014** [comment]
`bash docker/setup_host/install_docker.sh` as in https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/README.md

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
