### ISSUE TITLE
How to delete all the obstacles in demo_2.0.bag and add some new obstacles into the scenario in Dreamview

### ISSUE THREAD

**Issue by qianwenchao123** [ApolloAuto/apollo#4475]
Currently, I can successfully run demo_2.0.bag on Apollo. I am wondering how to delete all the obstacles in demo_2.0.bag and add some new obstacles into the scenario in Dreamview?
The questions can be detailed as follows:
1. how to delete all the obstacles in demo bag? I filtered the prediction topic, and there is not any obstacles in Dreamview. But I'm not sure if it is correct.
2. How to add a new obstacle (with its initial and target positions, and its motion control method) into the scenario?
3. How to set the initial position and target position for the autonomous vehicle?

Thanks a lot!

**Comment by jinghaomiao** [comment]
What you described is the simulation, which is not supported now.

**Comment by siyangy** [comment]
1. Rosbag filter sounds okay to me.
2. There's a similar question that you can refer to: https://github.com/ApolloAuto/apollo/issues/4338
3. Similar as 2, you can do so by publishing a dummy localization topic. Or you can use the SimControl mode and send a routing request to do so. I recommend using that with the latest code or Apollo 2.5 release.

**Comment by Zhenni17** [comment]
@qianwenchao123  hope @siyangy provided the answers to your question. Closing the issue now and please feel free to re-open the issue if I missed anything.
