### ISSUE TITLE
Where is the driver module for Mobileye? How can Mobileye messages be published?

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#4483]
I do not find any source file that implements Mobileye driver in the latest Apollo code base. So how can [Mobileye messages](https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/proto/mobileye.proto) get published? I do not find any implementation of _PublishMobileye_ but I do notice that there is a subscriber callback [ThirdPartyPerception::OnMobileye](https://github.com/ApolloAuto/apollo/blob/d3fc477256ac9e77cb0143a0abd7b3c922b2a9cc/modules/third_party_perception/third_party_perception.cc#L85) in third_party_perception module that takes into a Mobileye message.

**Comment by mickeyouyou** [comment]
you can find Mobileye driver in this branch `https://github.com/ApolloAuto/apollo/tree/mobileye_radar/modules/drivers/mobileye`.

**Comment by Capri2014** [comment]
@mickeyouyou Oh that one needs to be completely removed, and the one there is out-dated... @hongkedavid We can not open source this part due to license issue.

**Comment by hongkedavid** [comment]
@mickeyouyou @Capri2014 Got it. Thanks!
