### ISSUE TITLE
ARM-based processors support

### ISSUE THREAD

**Issue by htabani** [ApolloAuto/apollo#4485]
Hello,

Firstly, I thank the Apollo team for their impressive work and improvement since I am following your work very closely. I would like to know your plan whether or not you will support Apollo running on ARM-based processors. I know some of your libraries are only for x86 (e.g. elo module).

**Comment by jinghaomiao** [comment]
It's not in the roadmap yet. You are encouraged to explore on your own and share your experience. Thanks!

**Comment by Zhenni17** [comment]
closing the issue.
