### ISSUE TITLE
Timestamp correction in conti_radar

### ISSUE THREAD

**Issue by rogern27** [ApolloAuto/apollo#4492]
Hi,
In radar_process_subnode.cc, timestamp is modified as follows `timestamp -= 0.07;`. Could you please let me know why it is required and how did you come-up with 0.07?

**Comment by Capri2014** [comment]
@jinghaomiao radar_process_subnode.cc is under perception modules.

**Comment by techoe** [comment]
@rogern27 , Thank you for pointing out the issue. 0.07 comes from the radar frame rate (15 Hz -> 1/15 = 0.06666) to find the most recent radar output. We will replace it with a parameter (e.g. RADAR_DELAY_TIME_IN_MS = 0.06667) later. Thank you!

**Comment by techoe** [comment]
I hope your question is answered. If you have more question, please reopen this issue. Thank you, Tae Eun
