### ISSUE TITLE
Centos support

### ISSUE THREAD

**Issue by mingminzhen** [ApolloAuto/apollo#45]
It seems it doesn't support centos.

**Comment by ycool** [comment]
Can you help to post your running commands and the error msg?  Thanks. 

We only tested in Ubuntu so any help in CentOS is very welcome. :)

**Comment by AuspeXeu** [comment]
I also tried running it on centos. The first hurdle is that centos operates on `yum` instead of `apt-get`. The installation script could check which of the two is available and then execute the respective commands.

**Comment by quning78** [comment]
We haven't tested on centos yet. So that's why we can't officially support
it.

It's welcome to try it on different OS and you can even send your patches
if you get it up and running.

Best wishes,
-- 
Ning Qu

**Comment by AuspeXeu** [comment]
Any reason why this has been closed?

**Comment by ycool** [comment]
Re-open to track the progress.

**Comment by mickeyouyou** [comment]
Currently only support running on `Ubuntu` because `ros` can only run on `Ubuntu`?

**Comment by chsahit** [comment]
According to the [REP](http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021)  ROS is required to support Ubuntu but can also support Debian and Fedora. ROS could possibly be built from source on CentOS and other Operating Systems, but that would be relatively more involved of a process than just replacing apt-get with yum.

**Comment by juanlvo** [comment]
I will try to installed in CentOS and let see what happened

**Comment by juanlvo** [comment]
Well, I was checking the script of installation and I found the line `  sudo add-apt-repository \
      "deb https://apt.dockerproject.org/repo/ \
         ubuntu-$(lsb_release -cs) \
         main"`

Going deep about this address, this is related to a project called Moby, they have an experimental implementation for CentOS, even me I am not 100% sure how to implement a command which can replace the line before, I guess should be something like 

`sudo yum-config-manager --add-repo https://yum.dockerproject.org/repo/experimental/centos/$(lsb_release -cs)/repodata`

But I am not sure... If someone can give me some advises it will be helpful

**Comment by xiaoxq** [comment]
CentOS is not officially supported. Please refer to the docker document to install docker-ce.
If you got any progress please share it with us :)
Thanks!
