### ISSUE TITLE
Pandar40P_internal: code consolidation

### ISSUE THREAD

**Issue by freeHackOfJeff** [ApolloAuto/apollo#4502]
1. isolate variable scope
2. use bit shift inside loop for performance benefits

**Comment by mickeyouyou** [comment]
we have received you pull request. thank you so much.

**Comment by Zhenni17** [comment]
@freeHackOfJeff can you please clarify your question about this issue?

**Comment by natashadsouza** [comment]
Closing this issue as we have received a pull request for the same. Thanks!
