### ISSUE TITLE
Is the Lattice planner implementation complete?

### ISSUE THREAD

**Issue by gulshan216** [ApolloAuto/apollo#4504]
Hi,

I am studying a bit on Lattice planning from the reference paper "Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame". Based on one of the older comments from one of previous issues, i got to know that the Lattice planner implementation was still under development. Is it still the case? 

If it works, how do i use it instead of the em_planner or rtk_planner? I am looking to implement my own version of the lattice planner with few optimized libraries and try to integrate it with Apollo. In the end I would like to compare the performance of my planning module with the existing implementation in Apollo.

**Comment by lianglia-apollo** [comment]
We are continuously upgrading both em and lattice planners. Please feel free to implement any of them with your own libraries. You just need to make a new name for your planner, and make a pull request. We will be glad to review it. Thanks!

**Comment by gulshan216** [comment]
@YajiaZhang Thanks a lot for your response. Could you please provide me some info on the functionality of the various modules in apollo/modules/planning/lattice/behavior,  trajectory_generation and trajectory1d. I know that in general, lattice planner implements Optimal Trajectory Generation in a Frenet Frame and uses certain cost functions to find the best trajectory and i have read the reference paper and seen few sample implementations online. But the implementation here is a deeply modified version of that, so i would like to better understand the flow here.

I would like to initially implement a very basic version of the lattice planner with the optimized libraries and then try to improve upon it. It would really help to know the functionality of these modules so that I can carry over a few things to my planner as well and implement it using my libraries.

**Comment by zqsh** [comment]
looking forward some info on the organization of module and function of these modules

**Comment by marcusvinicius178** [comment]
Hi @YajiaZhang I have tried to use the Lattice planner insted the standard ROAD_Public defined in the **planning_config.pb.txt** as you and this post https://github.com/ApolloAuto/apollo/issues/13650 suggested. However the planner did not work. I mean the planning module is disabled on dreamview when I turn it on, as you can check here:
 https://www.youtube.com/watch?v=bApS6gzyo7s&list=PL_d_YiRmUA3nnTRmF8QJKyPoEQhrdvpP2&index=3&t=253s

Then after this I also attempt to change the code below from file **planning_config.proto**:

![image](https://user-images.githubusercontent.com/43826438/120565311-2626c680-c3e3-11eb-89ab-40481f27c957.png)

I changed from 1 (Public_Road planner type) to 3 (Lattice planner) and compiled the workspace again with success.
However the planning module keeps being disabled.

What am I doing wrong? Is it possible to swich **Apollo 6.0** planners?
I wish to do a test one by one of them (NAVI, ROAD_PUBLIC, LATTICE, OPEN_SPACE) to include in my master thesis.
**Could you please provide a step-by-step to how to change the planners? Which files I need to modify the code and which lines?**

Thanks a lot for some reply!
