### ISSUE TITLE
some questions about BlackBox ?

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4505]
Hi . Apollo. 
       Is there any introduction to the black box? such as Is the hardware not customizable?What has been done on the software?

**Comment by breakisx** [comment]
where is dir for BlackBox ？？？why not to say that is open ? just add this module in apollo. but it is not to open ?

**Comment by breakisx** [comment]
Please ask.   this dir(apollo/modules/data/tools/recorder/) is ready for BlackBox ？？？

**Comment by mickeyouyou** [comment]
hi  @breakisx  The first to note is that the Black Box is a reference hardware product that contains data logging, reading, secure OTA upgrade kits, and more. This is a commercial product that can be customized.

The data collection module ((apollo/modules/data/tools/recorder/), as Readme said, is just a functional module that helps Apollo partners record data.

**Comment by breakisx** [comment]
@mickeyouyou. Thank you very much. As you say, the Black box is reference hardware product, so the apollo system must communicate with the it to use code, where is the code ? such as the hardware about Lidar or camera, there is some code about it in apollo. I can't find the code  about Black box.
Please tell me some information. thank you !

**Comment by breakisx** [comment]
@mickeyouyou. Thank you very much. The Black Box could store data what size is ?　such as min size or max size or according to customer'customization who want how much size, that is  size who want...... smiling face.....

**Comment by breakisx** [comment]
@mickeyouyou.  you said that is a commercial product, it is also to say that  the code for black box only open to customers? Or open only customers can be customized according to needs, apollo support this feature. If necessary, please purchase it?

**Comment by mickeyouyou** [comment]
@breakisx thank you for you attention Black Box.

Answer 1. we have released the hardware, the software for security reasons, we did not release; black box mainly serves Apollo self-driving cars, there is no external sales, there are a variety of products, the cost is not convenient to disclose.

Answer 2. The storage size of the Black Box depends on the capacity of the selected SD card. The larger the capacity, the longer the information is stored.

Answer 3. The current main objective of the black box is to design the traffic accident, so the data is collected and stored mainly around this purpose. The specific additional data depends on whether it is relevant to the purpose and requires detailed communication with the technical staff.

**Comment by breakisx** [comment]
@mickeyouyou Your answer is very comprehensive and detailed. Thank you. But there are two questions, one is: use SD card to store data, SD card is reliable? For example, it can withstand the impact force, high temperature and so on. Second: Is the file system used for storage the fat or ext4 or something else? Of course, the data is certainly encrypted and encrypted. This is a secret.

**Comment by mickeyouyou** [comment]
Additional Answer 1 . The SD card is a test plan. The black box is designed by the car class. The mass production plan is a car-level chip plan, and there is a complete data security plan and data backup plan.

Additional Answer 2 . We are an embedded file system.

**Comment by breakisx** [comment]
@mickeyouyou OK! you are so handsome! Thank you very much !
