### ISSUE TITLE
Execute script modules/tools/perception/garage_perception.bash failed.

### ISSUE THREAD

**Issue by YafeiWangAlice** [ApolloAuto/apollo#4507]
The script was executed in apollo docker and the log is as belows:
root@in_dev_docker:/apollo# bash modules/tools/perception/garage_perception.bash 
Traceback (most recent call last):
  File "modules/tools/perception/replay_perception.py", **line 14**, in <module>
    from modules.perception.proto.perception_obstacle_pb2 import PerceptionObstacle
ImportError: No module named modules.perception.proto.perception_obstacle_pb2

(**For the garage_perception.bash only just execute replay_perception.py, the error is actually in modules/tools/perception/replay_perception.py**)

As I found there is no file perception_obstacle_pb2.py under modules/perception/proto/.
But py_proto/modules/perception/proto/perception_obstacle_pb2.py can be found.
So I changed the **line 14** to py_proto.modules.perception.proto.perception_obstacle_pb2, still the ImportError.

The file py_proto/modules/perception/proto/perception_obstacle_pb2.py said, "Generated by the protocol buffer compiler.  DO NOT EDIT!".

Does anyone who had tested or fixed the error in script modules/tools/perception/garage_perception.bash?

**Comment by hashim19** [comment]
@YafeiWangAlice Have you found the solution to this issue. I am having a very similar error when I try to run garage_perception.bash file
thanks in advance!

**Comment by changsh726** [comment]
Have you run `apollo.sh build` before executing the script?

**Comment by apollodevcommunity** [comment]
It seems that your python did not find py_proto. Does your environment variable PYTHONPATH have /apollo/py_proto. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=680
