### ISSUE TITLE
Sensor calibration

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#4511]
I have few questions regarding the calibration executables. I was trying it out when I faced some issues.
1. There are 5 different types of calibrations required. a) Camera - camera b) Camera - lidar c) Radar - camera d) Lidar - imu e) IMU - vehicle. Is the order important at all ? Can I do IMU - vehicle before radar - camera ?
2. Why does the imu - vehicle calibration depend on the radar and camera extrinsics/intrinsics ? 
3. During the radar - camera calibration, the terminal kept on outputting 'vehicle is on turn' even though I was going dead straight. To support my arguement, the imu - vehicle calibration worked on the same straight path.
4. Are you going to release the source code for the calibration tools ?

**Comment by ankitvora7** [comment]
@weidezhang @eugenegx @techoe @gchen-apollo - Can you guys help out here. Thanks!

**Comment by ankitvora7** [comment]
Any help appreciated :)

**Comment by natashadsouza** [comment]
@ankitvora7 take a look at our [calibration guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md) and let us know if you have any additional questions. You should find the link to download our tool within the document itself.
Thank you for your patience.

**Comment by ankitvora7** [comment]
@natashadsouza I have gone through the guide many times. It does not answer specific questions which I have posted above. It would be great if you/your team could help out with it.

**Comment by natashadsouza** [comment]
@ankitvora7 I have the answers to only 2 of those questions:

1. There are 5 different types of calibrations required. a) Camera - camera b) Camera - lidar c) Radar - camera d) Lidar - imu e) IMU - vehicle. Is the order important at all ? Can I do IMU - vehicle before radar - camera ? Yes, the order is important, but you could do IMU - Vehicle first.
3. Are you going to release the source code for the calibration tools ? No we currently only provide the executable

**Comment by techoe** [comment]
Thank you @natashadsouza! @ankitvora7, do you still have questions?

**Comment by natashadsouza** [comment]
@ankitvora7 the imu - vehicle calibration is independent of radar/camera extrinsics/intrinsics.

**Comment by layssi** [comment]
@natashadsouza.

I've been scratching my head as how u can mathematically do full calibration (translation and rotation) between two frames (IMU->Vehicle) and looking at the sample results, I noticed that your translation is 0,0,0. 

Driving straight, I believe that it is not possible to derive translation based on odometery only.  Maybe if you do figure 8s and u have some vehicle dimensions,  Maybe.

Are you 100% sure that your calibration is
a) Independent of other sensor measurements 
b) Can provide translation driving straight.

**Comment by natashadsouza** [comment]
@layssi calibration is independent with some sensors. 
For IMU -> vehicle calibration, the origin (translation) is the IMU position, and the calibration tool then estimates orientation (3 angles). This process is independent with any other sensors. 
Let me know if you need additional clarification.

**Comment by wf1024966** [comment]
> I have few questions regarding the calibration executables. I was trying it out when I faced some issues.
> 
> 1. There are 5 different types of calibrations required. a) Camera - camera b) Camera - lidar c) Radar - camera d) Lidar - imu e) IMU - vehicle. Is the order important at all ? Can I do IMU - vehicle before radar - camera ?
> 2. Why does the imu - vehicle calibration depend on the radar and camera extrinsics/intrinsics ?
> 3. During the radar - camera calibration, the terminal kept on outputting 'vehicle is on turn' even though I was going dead straight. To support my arguement, the imu - vehicle calibration worked on the same straight path.
> 4. Are you going to release the source code for the calibration tools ?

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by AlexandrZabolotny** [comment]
> > I have few questions regarding the calibration executables. I was trying it out when I faced some issues.
> > 
> > 1. There are 5 different types of calibrations required. a) Camera - camera b) Camera - lidar c) Radar - camera d) Lidar - imu e) IMU - vehicle. Is the order important at all ? Can I do IMU - vehicle before radar - camera ?
> > 2. Why does the imu - vehicle calibration depend on the radar and camera extrinsics/intrinsics ?
> > 3. During the radar - camera calibration, the terminal kept on outputting 'vehicle is on turn' even though I was going dead straight. To support my arguement, the imu - vehicle calibration worked on the same straight path.
> > 4. Are you going to release the source code for the calibration tools ?
> 
> hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

I have a symilar problem
