### ISSUE TITLE
What's the function of sim_control in the backend of dreamview

### ISSUE THREAD

**Issue by STX321** [ApolloAuto/apollo#4527]
Hi,Apollo developers:
   What's the function of sim_control in the backend of dreamview

**Comment by startcode** [comment]
It simulates a SDC's control module, and moves the car based on planning result. This is a really convenient way to visualize and test planning module.

**Comment by vlin17** [comment]
We have added sim control related information to [dreamview doc](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md). Closing this issue for now, please reopen or create a new one if you have any further questions.
