### ISSUE TITLE
How to completely remove all the apollo relevant packages

### ISSUE THREAD

**Issue by hxlee309** [ApolloAuto/apollo#4535]
After deleting the whole apollo folder, there are still many apollo related files that use lots of storage places: 
/usr/src/linux-headers-4.10.0-42/arch/m68k/apollo
/usr/src/linux-headers-4.13.0-43/arch/m68k/apollo
/usr/src/linux-headers-4.10.0-40/arch/m68k/apollo
/usr/src/linux-headers-4.10.0-35/arch/m68k/apollo
/usr/share/terminfo/a/apollo
/var/lib/docker/aufs/mnt/564517ca4699ef6becb85ea4858792ab9e9bdf0079ee913cce52feec0d50a778/apollo
/var/lib/docker/aufs/mnt/564517ca4699ef6becb85ea4858792ab9e9bdf0079ee913cce52feec0d50a778/home/apollo
/var/lib/docker/aufs/diff/d8bd59a32b8c876984beb3e0e4d56780fedac98cb1b23f9b2817b1fa2338cb45/apollo
/var/lib/docker/aufs/diff/ee21139f6604b53792307fa14eb0776ab64fce3ae963f08b2044cacecd1bdd24/home/apollo
/var/lib/docker/aufs/diff/ee21139f6604b53792307fa14eb0776ab64fce3ae963f08b2044cacecd1bdd24/apollo
/var/lib/docker/aufs/diff/d4e2c083bf3e5b2ea0150378fda51a3b5b12122e5f030fd37f25fd78dd06dee6/apollo
/var/lib/docker/aufs/diff/435fb900404e59d91bfdd34ba1ab445b6762166316232389800ae137b93a7c88/apollo
Is there any convenient and safe method to delete all of them without affecting my computers' other functionalities? 
Any help will be appreciated.

**Comment by Xiaoyang-Rebecca** [comment]
Remove all the docker ps and images: 

```
bazel clean
sudo docker stop $(sudo docker ps -a -q)
sudo docker rm $(sudo docker ps -a -q)
sudo docker rmi $(sudo docker images -a -q)
```

**Comment by natashadsouza** [comment]
@hxlee309 were you able to resolve your request?
