### ISSUE TITLE
Using custom hardware to run the perception module

### ISSUE THREAD

**Issue by vingtfranc** [ApolloAuto/apollo#4542]
Hi,

I would like to use an experimental accelerator to offload the NN processing from the perception module (in place of a GPU). Since this is a bit tricky, I am wondering what would be the easiest way to do so. Especially:
- Is it possible to first run the perception module on the CPU, so I could implement the offloading part by part?
- Or is it possible to disable parts I have not implemented yet? would I still be able to test each part?
 
Thank you

**Comment by vingtfranc** [comment]
So I was able to advance quite a lot on this matter. I have now a CPU version of the perception module I use for my experimentation. However, I am stuck at runtime because the libcaffe.so you provide requires to have a GPU anyway. Why is that so? Did you implement your custom caffe layers only for GPU?

Also, at some point, I will need to implement an equivalent of your custom caffe layers on my accelerator. However, I can't find any information about these layers. Some of them have explicit names, so it is rather easy to understand what they do. But some others are rather cryptic to me :(

Do you plan to release the source of your caffe? 
Or at least, would it be possible to have a rough description of these custom layers?

**Comment by techoe** [comment]
@vingtfranc , Caffe is open source and you can download it from https://github.com/BVLC/caffe. The current libcaffe.so was compiled for caffe. If you make the original caffe work with your H/W you may able to run some codes. However there are more places we are using Nvidia CUDA which should be replaced for your purpose. Please let me know if you could make it!

**Comment by natashadsouza** [comment]
Closing this issue as there has not been any communication in a while. Feel free to reopen the same if you have any additional questions.
