### ISSUE TITLE
About apollo2.5 perception, how to use Lidar?

### ISSUE THREAD

**Issue by chucklqsun** [ApolloAuto/apollo#4543]
In Apollo 2.5,  it supports vision based perception with obstacle and lane mark detections. However, in non-highway scenario, such as city, how to enable Lidar for perception module ?

I cannot find any instruction in readme.

**Comment by mickeyouyou** [comment]
you can refer the configure file like `modules/perception/conf/perception.conf`

**Comment by chucklqsun** [comment]
@mickeyouyou I saw perception.config, perception_lowcost.config, ... From my understanding, we can use Lidar or Radar+Camera solution by different perception*.config. Am I right ?

Another confusion. How can I setup to choose one of them ? modules/perception/conf/config_manager.config is missing in master branch after all.

**Comment by mickeyouyou** [comment]
Answer 1. yeah, you are right;
Answer 2. you can execute bash like this :`scripts/perception_lowcost.sh` or `scripts/perception.sh`

**Comment by chucklqsun** [comment]
@mickeyouyou Got it. Thanks mate!
