### ISSUE TITLE
bootstrap.sh does not start dreamview (crash?)

### ISSUE THREAD

**Issue by vingtfranc** [ApolloAuto/apollo#4544]
Hi,

I am able to install, build, run apollo. However, dreamview is not started when I use bootstrap.sh (or crashes instantly). However, I have no issue when I use start_gdb to start dreamview manually.
I used to have the PCL library issue, so I recompiled the library. Since then I don't have any issue running dreamview with gdb.

Here's roughly what I do:
```
$ # dev_start.sh, dev_into.sh
$ # compile and replace PCL
$ ./apollo.sh clean
    [...]
./apollo.sh build_no_perception dbg
    [...]
    ============================
    [ OK ] Build passed!
    [INFO] Took 779 seconds
    ============================
$ ps
      PID TTY          TIME CMD
       50 pts/10   00:00:00 bash
    18084 pts/10   00:00:00 ps
$ ./scripts/bootstrap.sh
    Started supervisord with dev conf
    Start roscore...
    voice_detector: started
    Dreamview is running at http://localhost:8888
$ ps
      PID TTY          TIME CMD
       50 pts/10   00:00:00 bash
    18103 pts/10   00:00:00 roscore
    18116 pts/10   00:00:00 python
    18180 pts/10   00:00:00 ps
--> firefox give me a page not found for http://localhost:8888
$ source scripts/apollo_base.sh; start_gdb dreamview
--> dreamview runs without issue
--> I can open http://localhost:8888 and run the rosbag demo
```
Note that it also works when I start the dreamview with ./scripts/dreamview.sh without gdb.

Isn't the dreamview supposed to be started with bootstrap.sh? or is there anything I don't do properly?

Regards

**Comment by siyangy** [comment]
Dreamview can be started by either ./scripts/bootstrap.sh or ./scripts/dreamview.sh. I recommend taking a peek at dreamview logs under /apollo/data/log/dreamview* to see what happened. You can also do a ./scripts/dreamview.sh start_fe to see how it crashed.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @vingtfranc if you have any additional questions, feel free to reopen this issue. Thanks!
