### ISSUE TITLE
Failed to start docker container "apollo_dev" based on image: registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20180530_1312

### ISSUE THREAD

**Issue by IveTian** [ApolloAuto/apollo#4545]
How to solve"Failed to start docker container "apollo_dev" based on image: registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20180530_1312"

**Comment by mickeyouyou** [comment]
Can you give more detail information?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. Feel free to reopen it if you have any additional questions.
