### ISSUE TITLE
Problem with Ubuntu 16 fix

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#4554]
Hello,

I am trying this guide here: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md

And when I try to add the fix it suggests, then compile..

I get this error:

error: 'GLFW_CONTEXT_CREATION_API' was not declared in this scope
   glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);

What would I need to include to declare this?

thanks

**Comment by snuffysasa** [comment]
@techoe @jinghaomiao 

Any thoughts?

**Comment by techoe** [comment]
Please take a look this report from glfw.
http://www.glfw.org/docs/latest/window_guide.html#window_hints_ctx

**Comment by alexbuyval** [comment]
@snuffysasa 
I have the same issue. Did you find a solution?
Thanks!

**Comment by snuffysasa** [comment]
never found a solution, switched to ubuntu 14, but still have issues there

**Comment by techoe** [comment]
@snuffysasa ,We do not recommend to use Ubuntu 16 but the one suggestion is provided in the document. If your code does not work with ubuntu 14, some other things may cause the problem.

**Comment by alexbuyval** [comment]
@snuffysasa 

Finally, I have found the solution. I have installed the GLFW v. 3.2.1
See attached file

[install_glfw3_2.sh.txt](https://github.com/ApolloAuto/apollo/files/2175029/install_glfw3_2.sh.txt)

**Comment by techoe** [comment]
@alexbuyval @snuffysasa . Yes. Installing GLFW is the solution as described  in https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md

**Comment by kk2491** [comment]
@alexbuyval .. I have followed the procedure given by you.
But the error remains the same.

```
ERROR: /apollo/modules/perception/obstacle/camera/visualizer/BUILD:5:1: C++ compilation of rule '//modules/perception/obstacle/camera/visualizer:visualizer' failed (Exit 1)
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc: In member function 'bool apollo::perception::lowcostvisualizer::GLFWFusionViewer::window_init()':
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc:281:18: error: 'GLFW_CONTEXT_CREATION_API' was not declared in this scope
   glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
                  ^
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc:281:45: error: 'GLFW_EGL_CONTEXT_API' was not declared in this scope
   glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
                                             ^
```

Could you please let me know the procedure followed to fix this issue.

Thank you,
KK

**Comment by kk2491** [comment]
@alexbuyval @techoe . I was able to get rid of the error I updated in previous comment.

Now while running all unit tests for apollo project I am getting the below error.

```
//modules/perception/traffic_light/recognizer:unity_recognize_test       FAILED in 1.6s
//modules/perception/traffic_light/rectify:perception_traffic_light_rectify_test FAILED in 1.3s
```

I have already installed libglfw3-dev 3.2.1-1.

Kindly let me know if I need to open new case for this query.

Thank you,
KK

**Comment by CCodie** [comment]
@alexbuyval 

Hi, I have the same GLFW issue.
And I'm trying to solve the problem with your solution.
Did you mean that execute the `install_glfw3_2.sh` file inside the docker? or both in PC and Docker?

Thanks!
