### ISSUE TITLE
Any ROS bag input sample for third-party perception module?

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#4565]
Hi Apollo developers, is it possible to provide any ROS bag input sample for testing the third-party perception module (v2.5)? It seems that the provided demo rosbag files here do not contain Mobileye messages (defined in [mobileye.proto](https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/proto/mobileye.proto)).

**Comment by jinghaomiao** [comment]
@hongkedavid we currently don't have that per regulation/license from mobileye.

**Comment by hongkedavid** [comment]
@jinghaomiao I see. Thanks for your information.
