### ISSUE TITLE
perception(Track)

### ISSUE THREAD

**Issue by lijiong123** [ApolloAuto/apollo#4581]
In the function of  UpdateWithObject , what's the coordinates of tracks and objects?

**Comment by songhanchen** [comment]
In navigation mode: vehicle coordinates. origin of coordinate on vehicle center(imu), refer to 
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination.pdf

**Comment by lijiong123** [comment]
Thanks for your answer ! But I also have a question .vehicle coordinates is different at different time .If In the function of UpdateWithObject ,the coordinates of tracks and objects is vehicle coordinates . Objects  cannot be in the same coordinate system at different time. Then how  to compute velocity using anchor_point in different coordinate system.

**Comment by techoe** [comment]
The world coordinate can be changed to ego-centric coordinate by setting the current car as the origin. The velocity can be computed by ego-vehicle's speed (using IMU and CAN bus signal from EPS) and other vehicles' relative speed (from tracking of objects).

**Comment by techoe** [comment]
I am closing it since there is no update after last answer.
