### ISSUE TITLE
Apollo generate many core_perception

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#4583]
Hi,

When I turn on perception module, Apollo generates many core_perception files in data/core and it makes my disk full, I have 1TB HDD.
Anyway to prevent that?

Thank you.

**Comment by hzdsdhr** [comment]
The core files are for debuging, it's no use if your modules work well and no need to debug.

**Comment by hzdsdhr** [comment]
Just delete them all.

**Comment by techoe** [comment]
Thank you @hzdsdhr

**Comment by pancumtneu** [comment]
I've got the same trouble these files occupied too many space.When I delete them ,they recover instantly! As a result there is insufficient disk for me .The system got jam.The DreamView page has not changed. @hzdsdhr
