### ISSUE TITLE
Vehicle frame orientation

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#4584]
What is the orientation of the vehicle/body frame ? Is it RFU or FLU ? There is inconsistency in the documentation. What convention do modules like localization, perception and planning follow ?

**Comment by ireeX** [comment]
It is FLU. I think what you want is in the https://github.com/ApolloAuto/apollo/blob/master/modules/planning/planner/navi/navi_planner.h

**Comment by ankitvora7** [comment]
The problem is it is inconsistent. What about localization and perception ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
