### ISSUE TITLE
5  containers running - is that normal ?

### ISSUE THREAD

**Issue by whatdhack** [ApolloAuto/apollo#4589]
I see the  following containers running after I executed "bash scripts/bootsrap.sh".  Is that normal ? 

$ sudo docker container ls
CONTAINER ID        IMAGE                                                    COMMAND             CREATED             STATUS              PORTS               NAMES
a3ffb62392d9        apolloauto/apollo:dev-x86_64-20180530_1312               "/bin/bash"         11 hours ago        Up 11 hours                             apollo_dev
5c7bbeec3f1f        apolloauto/apollo:yolo3d_volume-x86_64-latest            "/bin/sh"           11 hours ago        Up 11 hours                             apollo_yolo3d_volume
55bea3efd614        apolloauto/apollo:localization_volume-x86_64-latest      "/bin/sh"           11 hours ago        Up 11 hours                             apollo_localization_volume
f18d54e91ff9        apolloauto/apollo:map_volume-sunnyvale_loop-latest       "/bin/bash"         11 hours ago        Up 11 hours                             apollo_map_volume-sunnyvale_loop
d857e80c9d8c        apolloauto/apollo:map_volume-sunnyvale_big_loop-latest   "/bin/sh"           11 hours ago        Up 11 hours                             apollo_map_volume-sunnyvale_big_loop

**Comment by xiaoxq** [comment]
Yes, we bring up HDMaps and some other large data as docker volumes.

**Comment by whatdhack** [comment]
I see , is this also  the recommended  way to play back recorded data ?

**Comment by mickeyouyou** [comment]
It is also a solution. If you are playing recorded data, you can use the device to mount it. The docker has already mounted the `/dev` directory and can use it directly.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. If you have additional questions, feel free to reopen this issue. Thanks!
