### ISSUE TITLE
About support PC

### ISSUE THREAD

**Issue by amiltonwong** [ApolloAuto/apollo#46]
Hi, authors,

According to the HW/SW installation readme, Neousys Nuvo-5095GC are only supported. However , this machine only provide nvidia 1050 GPU card, which is quite limited. Could we consider other PC spec. which support high-end  GPU card such as 1080TI / Titan X?

**Comment by ycool** [comment]
Good suggestion! Nuvo-5095GC is tested here. Please feel free to try it in other high end platforms. In the future, more platforms will be added.  Thanks.

**Comment by aiguo159** [comment]
For offline testing, you can use any PC you want. However, for on-car deployment, you are recommended to use an IPC similar to Nuvo-5095GC which can operate with ambient (environment) temperature up to 60 degree C. GTX 1050 is the GPU officially supported by Nuvo-5095GC, but you can replace it with a more powerful GPU which has the same 75W TDP such as Tesla P4, or lower TDP.

Apollo 1.0 release doesn't use GPU acceleration yet, but future release will.

**Comment by Zhenni17** [comment]
Hi @amiltonwong ,

Hope @aiguo159 and @ycool answered your question. We are closing this issue. If you have additional question, please open an new issue.

Thank you for supporting Apollo.

Best,
Zhenni - Apollo Community Manager
