### ISSUE TITLE
How does the car move one point to another in Dreamview?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#460]
I remove the topic '/apollo/planning' /apollo/control /apollo/chasis  and the start planing control can_bus modules,  but the car run normally not following the planned trajectory??

Does the car move by receiving control_cmd by some motion model?

**Comment by lianglia-apollo** [comment]
Dreaview show the car's position based on /apollo/localization/pose.

To test a new planning algorithm, we usually filter out '/apollo/planning', then start the new planning from another terminal and watch the generated planning results, which is called "open loop" test.

To move the car on dreamview, you will need to generate your own "/apollo/localization/pose" to do so.

**Comment by westeast** [comment]
ok thanks

**Comment by siyangy** [comment]
To move the car with only planning info, you can enable the SimControl module of dreamview by starting dreamview with `./scripts/dreamview_sim_control.sh`. It generates the `/apollo/localization/pose` data based on the planning trajectory.
