### ISSUE TITLE
Apollo transfer data to cloud 

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#4607]
Does Apollo have the ability to upload data and download data to the cloud in real time? If so, is it open? For example, the interface to the caller.

**Comment by mickeyouyou** [comment]
Considering the large amount of data generated during the auto driving and the limited network bandwidth, Apollo does not currently have such capabilities;

**Comment by edious** [comment]
Is there any plan to make Apollo communicate with baidu-cloud or other cloud provider？
such as transfer some essential-data to cloud

**Comment by natashadsouza** [comment]
@edious we are working towards making Apollo as seamless as possible. It is definitely on our roadmap, and we will let you know if we decide to use a cloud provider.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
