### ISSUE TITLE
ROS: can't communicate with master

### ISSUE THREAD

**Issue by hlchen1043** [ApolloAuto/apollo#4617]
To whom it may concern,
This is what I get when trying to run ros for Apollo:

hlchen@in_dev_docker:/apollo$ uname -a
Linux in_dev_docker 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
hlchen@in_dev_docker:/apollo$ bash scripts/bootstrap.sh 
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: started
Dreamview is running at http://localhost:8888
hlchen@in_dev_docker:/apollo$ cat /tmp/supervisor.star.log
cat: /tmp/supervisor.star.log: No such file or directory
hlchen@in_dev_docker:/apollo$ cat /apollo/data/log/roscore.out 
hlchen@in_dev_docker:/apollo$ roscore
... logging to /home/hlchen/.ros/log/72f01358-74c8-11e8-83a7-f859714f8422/roslaunch-in_dev_docker-20185.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://in_dev_docker:37347/
ros_comm version 1.11.21

SUMMARY

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

roscore cannot run as another roscore/master is already running. 
Please kill other roscore/master processes before relaunching.
The ROS_MASTER_URI is http://in_dev_docker:11311/
The traceback for the exception was written to the log file
hlchen@in_dev_docker:/apollo$ bash scripts/bootstrap.sh stop
dreamview: stopped
voice_detector: stopped
monitor: stopped
roscore: stopped
hlchen@in_dev_docker:/apollo$ roscore
... logging to /home/hlchen/.ros/log/f0950fac-74c8-11e8-9b2b-f859714f8422/roslaunch-in_dev_docker-20272.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://in_dev_docker:44337/
ros_comm version 1.11.21

SUMMARY

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

auto-starting new master
process[master]: started with pid [20290]
ROS_MASTER_URI=http://in_dev_docker:11311/

setting /run_id to f0950fac-74c8-11e8-9b2b-f859714f8422
process[rosout-1]: started with pid [20310]
started core service [/rosout]

=====Start a new terminal=====
hlchen@hlchen-Lenovo:~/apollo$ bash docker/scripts/dev_into.sh
hlchen@in_dev_docker:/apollo$ rosnode list
ERROR: Unable to communicate with master!
hlchen@in_dev_docker:/apollo$ rosnode list;rostopic list
ERROR: Unable to communicate with master!
ERROR: Unable to communicate with master!

Does anyone know why this happens?

Thank you!

**Comment by ankitvora7** [comment]
bootstrap.sh already runs roscore. You don't need to run it again. I think something would have cause roscore to crash. Try it again and it should work.

**Comment by quning78** [comment]
Closed due to question has been answered. Reopen if you still have question on this.
