### ISSUE TITLE
Any example for making obstacles in Dreamview simulation environment?

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#4626]
Hi, guys.

I want to simulate some algorithms with Dreamview simulation environment (SimControl mode).

I wonder about how can I make obstacles in Dreamview. 

I found out that there's previous similar question (#4338), but I'm not sure how to add new obstacles.

From that question (#4338), @unacao said user have to follow 2 steps.
1. Fill in the obstacle information according to the proto (perception_obstacle.proto).
2. Publish the messages.

I want to know there's any examples for following the steps.

Also, it looks like there's some example files for filling the obstacle information.
[config.pb.txt](apollo/modules/perception/tool/data_generator/conf/config.pb.txt) or [1_perception_obstacles.pb.txt](apollo/modules/third_party_perception/testdata/simple_fusion/1_perception_obstacles.pb.txt)

Can I use these files or is there any reference case for using it?

**Comment by mickeyouyou** [comment]
hi  @CCodie , in directory  `module/tools/perception`, you can find some scripts like `replay_perception.sh` that can mock some obstacle and publish the message `/apollo/perception/obstacles` that descrbed in files  `garage_*.json` files, you can execute like :
```
# in modules/tools/perception
python replay_perception.sh garage_onroad_vehicle_3.json
```
that will publish vehicle to topic `/apollo/perception/obstacles` per  100ms.

or execute `python replay_perception.sh garage_*.json`, that will publish different obstable on or off road.

**Comment by CCodie** [comment]
hi @mickeyouyou , I'm really thanks for you reply!

Do you mean that type below text after I run Apollo(bash scripts/bootstrap.sh inside the docker) ?
`# in modules/tools/perception
python replay_perception.sh garage_onroad_vehicle_3.json`

**Comment by mickeyouyou** [comment]
right  you can have a try

**Comment by CCodie** [comment]
Thanks @mickeyouyou  , now I can make a obstacle in Dreamview simulationworld.
I have two additional questions below.
### Q1. How can I make several obstacles ?
I tried to make several obstacles. So I opened some terminal windows and executed the following commands.
```
# Terminal 1 (in modules/tools/perception)
python replay_perception.sh static_obstacle_1.json
```
```
# Terminal 2 (in modules/tools/perception)
python replay_perception.sh static_obstacle_2.json
```
I set id_value and x,y_coordinate_values for the two json files differently.
But it seems that they do not work properly.
Can you tell me how to fix it?

### Q2. Is there any tools for creating path(_trace value_ in json file) for the obstacle ?
In example file `garage_onroad_vehicle_3.json`, there are trace values and obstacle in dreamview simulationworld moves along that path. I wonder about how Apolloteam made that trace values. (using rosbag file..?)

**Comment by mickeyouyou** [comment]
Cool 👍

**Comment by fanghaos2014** [comment]
I  have the same question. In terminal, I find replay_perception.py, but when I run python replay_perception.sh garage_onroad_vehicle_3.json. It said can't open file "replay_perception.sh.

**Comment by unacao** [comment]
@fanghaos2014 this comment may be helpful. https://github.com/ApolloAuto/apollo/issues/4822#issuecomment-412465605

**Comment by SanduIrina** [comment]
After running this, and let's say sending a routing request for the car in dreamview, is it supposed to avoid the obstacles it detects on the road?

**Comment by Iqbalparvi** [comment]
@CCodie can you please help me to generate obstacles in dreamview ,

**Comment by apollodevcommunity** [comment]
You can use modules\\tools\\perception\\garage_perception.bash to publish perception obstaclesAlso you can also use modules\\tools\\replay\\replay_file.py to publish pb.txt file. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=675

**Comment by marcusvinicius178** [comment]
Hi I wish to the same. However I am using Apollo6.0. The files I have into apollo/modules/tools/perception folder however has not the .sh extension, but .py extension. The files are below:

![image](https://user-images.githubusercontent.com/43826438/121740594-ad56f700-cad3-11eb-992f-d73d28c13653.png)

The I tried to execute all the files, as you can check on this video:
https://youtu.be/ZpnG7zKQXU0

To reproduce what I have done:

`./docker/scripts/dev_start.sh
./docker/scripts/dev_into.sh`
Then inside the Docker Environment:
`./apollo.sh build_opt_gpu
./scripts/bootstrap.sh`
Then Finally I have accessed the folder To Spawn these virtual obstacles on Dreamview:
`cd modules/tools/perception
python replay perception.py garage_cross_vehicle_2.json` 

I have also tried to run all the other scripts (enabled clicking twice the TAB keyboard):

![image](https://user-images.githubusercontent.com/43826438/121741389-d88e1600-cad4-11eb-8d6d-45b7a50b4ba2.png)

All the scripts returns me the error:

![image](https://user-images.githubusercontent.com/43826438/121741519-05dac400-cad5-11eb-98a7-59ba3900c78e.png)

Python Returns that it cannot import the cyber module. Okay but where is this cyber module?? This cyber module:

1 -  was not included inside docker folders?
2 - Is inside the docker folder, but these scripts cannot import it due some root permission, or wrong path, cannot access it by other reason?
3- I must source some .bash file to enable this module be tracked?
4- This file is not present in master version, so I must dowload this cyber module from somewhere else, Apollo Version or Tag, etc?

If someone has added these obstacles with sucess, please let me know the steps needed :)
 @apollodevcommunity , @CCodie , @mickeyouyou , @daohu527 , @AndrewXWei , @shusukui , @lecoos, @opus23, @SanduIrina , @unacao 

Thanks in advance
