### ISSUE TITLE
camera perception module

### ISSUE THREAD

**Issue by ktxu1224** [ApolloAuto/apollo#4627]
hi, thx a lot for opening source code. I learn that yolo based camera perception module can detection both dynamic and static obstacles, but i m puzzled by ignore label, whether that means this network can detect all kinds of obstacles besides the types listed in the label?

**Comment by techoe** [comment]
@ktxu1224 , Currently 4 types of objects and lane lines are detected by the Yolo network. We do not identify every brand and model of every vehicle using the current model. Thank you!
