### ISSUE TITLE
apollo-2.0.0 build ERROR on TX2: /apollo/modules/common/BUILD:31:1 && missing dependency declarations && ros.h

### ISSUE THREAD

**Issue by pomelody** [ApolloAuto/apollo#4628]
I had met this issue, and didn't have any solution for it.

`ERROR: /apollo/modules/common/BUILD:31:1: undeclared inclusion(s) in rule '//modules/common:apollo_app':
this rule is missing dependency declarations for the following files included by 'modules/common/apollo_app.cc':
  '/apollo/ros/include/ros/ros.h'.
INFO: Elapsed time: 19.523s, Critical Path: 9.98s
============================
[ERROR] Build failed!
[INFO] Took 23 seconds
`
Can someone offer advice? Thank you very much!!!

**Comment by jinghaomiao** [comment]
Apollo open source software stack is running in a docker container on Intel x86 system only. Thanks!

**Comment by xyang65** [comment]
I have same issue. Cannot find ros every time I want to build. Any comments are appreciated. BTW, I am x64

**Comment by yaohuxiaohui** [comment]
@xyang65 Do you have copy folder ros/ to /home/temp/?

**Comment by yaohuxiaohui** [comment]
@jinghaomiao Thank you! However, someone has achieved Apollo on TX2 successfully. We run it on TX2 step by step with his tutorial, but he didn't give specific solutions.
I have another question: if the issue above on x86, how to deal with it?
Thanks!

**Comment by lylcore** [comment]
@yaohuxiaohui   someone has achieved Apollo on TX2 successfully: can you give me address ?

**Comment by storypku** [comment]
Stale issue closed.
