### ISSUE TITLE
Rosbag for multiple apollo2.0 machines

### ISSUE THREAD

**Issue by levuphuong** [ApolloAuto/apollo#4630]
Hi all,
I have 2 machines with apollo and apollo platform 2.0 setup. 
Machine 1: roscore, dreamview
Machine 2: rosbag play demo_2.0.bag

They are connected together. 
I can get data from machine 1 with rosptopic echo command. 

But problem is dreamview on machine 1 cannot receive any data. 
Thank you

**Comment by siyangy** [comment]
Can you try running `./scripts/dreamview.sh start_fe` to see if Dreamview starts correctly on your machines 1? You can take a look at https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md for troubleshooting guidance.

**Comment by levuphuong** [comment]
Hi SiYangy,

I already check with your command to start dreamview.
The output like this.

I believe dreamview has started well. Because I can load http:local:8888 page and see background image website. But no data or simulation works.
One more thing, if then I run rosbag play from machine 1. Data and simulation work fine.

I don't know if rosbag play has special communication with dreamview beside publish and subscribe message or not?
or does rosbag support play bag for multiple machines?
 
Thanks so much

`
@in_dev_docker:/apollo$ cat data/log/dreamview.out
0621 16:29:52.361416  6501 hdmap_util.cc:36] No existing file found in modules/map/data/sunnyvale_big_loop/base_map.bin|base_map.xml|base_map.txt. Fallback to first candidate as default result.
E0621 16:29:52.361852  6501 file.h:139] Failed to open file modules/map/data/sunnyvale_big_loop/base_map.bin in binary mode.
E0621 16:29:52.361881  6501 file.h:96] Failed to open file modules/map/data/sunnyvale_big_loop/base_map.bin in text mode.
E0621 16:29:52.361897  6501 hdmap_util.cc:62] Failed to load HDMap modules/map/data/sunnyvale_big_loop/base_map.bin
E0621 16:29:52.361930  6501 hdmap_util.cc:36] No existing file found in modules/map/data/sunnyvale_big_loop/sim_map.bin|sim_map.txt. Fallback to first candidate as default result.
E0621 16:29:52.361973  6501 file.h:139] Failed to open file modules/map/data/sunnyvale_big_loop/sim_map.bin in binary mode.
E0621 16:29:52.361990  6501 file.h:96] Failed to open file modules/map/data/sunnyvale_big_loop/sim_map.bin in text mode.
E0621 16:29:52.362004  6501 hdmap_util.cc:62] Failed to load HDMap modules/map/data/sunnyvale_big_loop/sim_map.bin
E0621 16:29:55.620630  6527 file.h:96] Failed to open file modules/map/data/sunnyvale_big_loop/default_end_way_point.txt in text mode.
E0621 16:29:59.626375  6527 json_util.cc:70] The json has no such key: lane
E0621 16:29:59.626452  6527 json_util.cc:70] The json has no such key: crosswalk
E0621 16:29:59.626471  6527 json_util.cc:70] The json has no such key: junction
E0621 16:29:59.626488  6527 json_util.cc:70] The json has no such key: signal
E0621 16:29:59.626507  6527 json_util.cc:70] The json has no such key: stopSign
E0621 16:29:59.626523  6527 json_util.cc:70] The json has no such key: yield
E0621 16:29:59.626538  6527 json_util.cc:70] The json has no such key: overlap
`

**Comment by siyangy** [comment]
I believe this is due to by default ROS uses shared memory as communication channel instead of network. It might be configurable to use network though. @quning78, can you help answer this?

**Comment by levuphuong** [comment]
I changed to socket mode then they work fine. 
I have some confusion about how come the rostopic echo on machine 1 can get data from machine 2 with share memorry mode in default when dreamview cannot get. 

Thanks so much

**Comment by alexbuyval** [comment]
@levuphuong I have the same issue. Could you tell me how have you changed to socket mode? 
Thanks!

**Comment by levuphuong** [comment]
You can change mode in /home/tmp/ros/etc/ros/transport_mode.yaml

**Comment by apollodevcommunity** [comment]
One possible solution is that both machines should register their IP address in the ROS network. More precisely   machine 1 should append the following command to its .bashrc file:export ROS_IP=< IP address of machine. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=674
