### ISSUE TITLE
Apollo simulation use problem

### ISSUE THREAD

**Issue by Fitz-liu** [ApolloAuto/apollo#4631]
Hi! Well, I took part in the unmanned global challenge of the big data industry, and now I have a lot of data at that time (including the PCD cloud image of a lidar scan, etc.) because we were using the autoware frame at the time, so now I want to run these numbers with Apollo, but I don't understand it very well. Apollo the usage of this simulation platform is always wrong. Is there anyone who has such experience to share?

**Comment by hao944624028** [comment]
For example: I have PCD cloud point map data and some other road data, I want to use Apollo dreamview to implement a real-time relative map, and can be displayed in the simulator, similar to the example of the planning module, what should I do
