### ISSUE TITLE
yolo_detection CNN optimization

### ISSUE THREAD

**Issue by chybhao666** [ApolloAuto/apollo#4632]
Currently, your visual perception neural network in release 2.5 is based on YOLO. As you mentioned, TensorRT may be used to optimize the network. I saw your Baidu USA meetup video, currently the inference throughput is about 70fps on GTX1080Ti. So some questions here:

1. After reviewing the source code, yolo_detection module is not optimized yet. Right?
2. More cameras will be added in apollo in the future. The computational requirements will increase. Do you have a roadmap on CNN optimization?

**Comment by techoe** [comment]
1. Yes the current 2.5 codes were not optimized by TensorRT. To use TensorRT, we have to upgrade the OS to Ubuntu 16.
2. We will let you know our sensor optimization and scheduling when we add more sensors in the future.

**Comment by myih** [comment]
@techoe @chybhao666 
Did you test the inference time after optimized by tensorRT? 
I got 14ms on 1080ti which is almost the same as before optimization. It convert 95 layers to 57 layers. Could be that my pluging layers are too slow.
