### ISSUE TITLE
How to  add a new planner?

### ISSUE THREAD

**Issue by schietau** [ApolloAuto/apollo#4634]
hi, i want to add my own planner to apollo planning module, is there some help documents about how to add new planner?

**Comment by jinghaomiao** [comment]
Currently two planners are supported in planning module. Please refer to how lattice planner is added.

**Comment by pramodswainn** [comment]
@schietau  Hi ,Do you have any reference document to understand how to add new planner ?

**Comment by marcusvinicius178** [comment]
Hi @pramodswainn  and @jinghaomiao how to enable the Lattice planner on Apollo 6.0? or 5.0? 
I have done a lot of attempts: https://github.com/ApolloAuto/apollo/issues/13828

Is it possible to use the Lattice Planner in Apollo 3.0 more easily? I could not set Apollo 3.0 to work with SVL:
https://github.com/lgsvl/simulator/issues/1475
