### ISSUE TITLE
control simulation 

### ISSUE THREAD

**Issue by schietau** [ApolloAuto/apollo#4635]
hi, it is seem that at present there is no simulation tools for simulating the control algorithm in apollo. so how can we validate our control algorithm in simulation environment?

**Comment by Capri2014** [comment]
@schietau We do not have it yet open to public due to resource limitation/ lag of needs. But are internally we are discussing about working towards it.

**Comment by natashadsouza** [comment]
Currently closing this issue. @schietau thank you for your request. Do write to us if you have any additional suggestions.

**Comment by cdemirsoy** [comment]
Hi there,

Is there any update on that? It would be nice to make some contribution at this point. Do you think that using Gazebo simulator can be helpful to create a closed-loop simulation platform for the testing of Apollo?

Thanks and best of all,
Canberk Demirsoy
