### ISSUE TITLE
Planning algorithms test offline.

### ISSUE THREAD

**Issue by Yangshell** [ApolloAuto/apollo#4637]
I wonder that if it is possible to test my own planning algorithm without other modules like control, prediction, location etc. That means I do not have enough environment of vihicle. I only want to test if my algorithm is effective.

**Comment by jinghaomiao** [comment]
Use dreamview and enable sim_control on dreamview to test your planning algorithm.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. @Yangshell feel free to open it if you have additional questions.
