### ISSUE TITLE
Planning Module Automatically Stop and Restart

### ISSUE THREAD

**Issue by yuqijin** [ApolloAuto/apollo#4646]
Hi Apollo developers, I want to play with the SimControl you provided,  but when I try running the planning module, it always stop automatically and then restart. I am using apollo_2.5 (dev) on linux.
Here are the commands I execute, hope it will be helpful for you to find the problems:
`./apollo.sh build_no_perception dbg`
`bash scripts/bootstrap.sh`
`supervisorctl start routing`
(I chose Sunnyvale Loop as the map and used Default Routing to send the routing request from Dreamview UI)
`supervisorctl start planning`

Unfortunately, each time the planning module will soon stop automatically and then restart. By observing the log file it produced, the module has entered into its `Runonce` function, and stops after it enters into its `PublishPlanningPb `function, here is the error msg I got before it stopped:
`I0621 23:01:29.953886 50137 frame.cc:331] [DEBUG] Enabled align prediction time ? : false`   
`W0621 23:01:29.954303 50137 reference_line_provider.cc:221] Reference line is NOT ready. `                                                  
`E0621 23:01:29.954679 50137 frame.cc:131] Failed to create reference line `                                                             
`E0621 23:01:29.955137 50137 frame.cc:357] Failed to init reference line info `                                                            
`E0621 23:01:29.955513 50137 planning.cc:78] failed to init frame `                                                                       
`E0621 23:01:29.959810 50137 planning.cc:360] Failed to init frame`     

I am wondering why the module will automatically restart, which is really strange since I did not find any related code which can restart it. Furthermore, the MSF localization module will also restart soon after it has been launched by `supervisorctl` cmd. My current speculation is you have set 'respawn = true' for the module, so it will restart after it encountered some segmentation fault, but I am not sure.

I will be really grateful if you can help me debug this problem and let me know what mistake I made. Thank you for your help!

**Comment by lianglia-apollo** [comment]
Yes, you are correct. The auto restart is triggered by supervisorctl.

**Comment by yuqijin** [comment]
Thank you for your reply! But I am still confused about how to get rid of this error message and let the planning module runs normally when I replay some demo bag. Can you provide me some help? Thanks!

**Comment by GeorgeMD** [comment]
@yuqijin I'm facing the same problem. I found the exact same error. Did you find any fix for it?

**Comment by lianglia-apollo** [comment]
We don't use supervisorctl in the most recent code. Please reopen this issue if it appears again.
