### ISSUE TITLE
QNX OS support & Function Safety framework support

### ISSUE THREAD

**Issue by zmsunnyday** [ApolloAuto/apollo#4647]
Apollo is a perfect Autonomous Driving frameworks. Thanks a lot for your hard work to make it.

When it comes to mass production, I don't think Ubuntu is not qualified for safety regulations.
And FuSa(such as Functional Safety, ISO26262)， ENCAP, CNAP are required for new vehicles. I would like to know your FuSa framework roadmap, do  it also open to developers?

**Comment by lianglia-apollo** [comment]
Thanks for your question. Some developers have successfully migrated Apollo to QNX OS, and Nvidia OS for self-driving vehicles.

**Comment by zhxt** [comment]
FYI. There will be an open course named "Porting Apollo Autonomous Driving Platform to the QNX Safety-Certified Real-Time OS"  presented by Weiyu Liang from BlackBerry during Baidu's AI Developer Conference 2018.  Find more info from the [conference agenda](http://create.baidu.com/agenda/).

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @zhxt thank you for recommending the course.
