### ISSUE TITLE
FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by liyubang** [ApolloAuto/apollo#4649]
Here is my bugreport
From: lee
To: file:///usr/share/doc/gcc-4.8/README.Bugs
Subject: [50 character or so descriptive subject here (for reference)]

Configuration Information [Automatically generated, do not change]:
Machine: x86_64
OS: linux-gnu
Compiler: gcc
Compilation CFLAGS:  -DPROGRAM='bash' -DCONF_HOSTTYPE='x86_64' -DCONF_OSTYPE='linux-gnu' -DCONF_MACHTYPE='x86_64-pc-linux-gnu' -DCONF_VENDOR='pc' -DLOCALEDIR='/usr/share/locale' -DPACKAGE='bash' -DSHELL -DHAVE_CONFIG_H   -I.  -I../. -I.././include -I.././lib  -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall
uname output: Linux in_dev_docker 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Machine Type: x86_64-pc-linux-gnu

Bash Version: 4.3
Patch Level: 11
Release Status: release

Description:
        [Detailed description of the problem, suggestion, or complaint.]

Repeat-By:
        [Describe the sequence of events that causes the problem
        to occur.]

Fix:
        [Description of how to fix the problem.  If you don't know a
        fix for the problem, don't include this section.]
~                                                                                                
~                                                                                                
~                                                                                                
"/tmp/bbug.3032/bbug1" 26L, 1106C                                              1,1           All

how can I repair this?

**Comment by liyubang** [comment]
sorry,here is the message:
ERROR: /apollo/modules/perception/obstacle/onboard/BUILD:23:1: C++ compilation of rule '//modules/perception/obstacle/onboard:lidar_process' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 2282.004s, Critical Path: 2072.30s
FAILED: Build did NOT complete successfully

**Comment by natashadsouza** [comment]
@liyubang were you able to resolve the Build issue? Which version of Ubuntu are you using currently?

**Comment by liyubang** [comment]
@natashadsouza My computer's Memory is too small.And now Apollo needs 6GB memory minimum.
