### ISSUE TITLE
请问如何把apollo module一个模块单独放在本地用catkin_make编译？

### ISSUE THREAD

**Issue by kxhlp** [ApolloAuto/apollo#4650]
我想把apollo module里面的某一个模块单独放在本机上用ros的catkin_make编译，里面的adapters依赖了很多东西，导致编译失败，另外还有protobuf,请问一下有没有好的办法？

**Comment by ahuer2435** [comment]
个人感觉需要理解下模块大体架构，然后重写，把ros中没有的东西删除或者替换掉，直接移植不大现实，apollo本身是有一套自己的框架的。

**Comment by jilinzhou** [comment]
Create a workspace and make a symlink to the module. I suggest to try **catkin tools** which I found is easier to build ros packages.

**Comment by storypku** [comment]
Stale issue closed.
