### ISSUE TITLE
Issue to understand docker while build

### ISSUE THREAD

**Issue by Grayhu07** [ApolloAuto/apollo#4651]
I currently tried to build Apollo in variety machines, and found out that in some of the machines, build is just fine, everything looks good. However, sometimes, the dreamview couldn't start properly, so I followed the [document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md) to try to fix this issue (still doing it). Since I use the same docker and images, they should all have the same environment right? Why some of the machines appeared to have this kind of issue?
Please help me to get more understanding about docker and environment, thanks.

**Comment by natashadsouza** [comment]
It depends heavily on your Ubuntu version, system setup and memory capabilities. It can also depend upon your internet connection strength. Please share the error messages you receive to help us identify the exact cause for Dreamview start failure. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
