### ISSUE TITLE
Frames configuration

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#4653]
![apollo sensor frame](https://user-images.githubusercontent.com/9420343/41779170-f687d98a-75fe-11e8-8c8d-90127d1538e1.png)
Does this look right with what you guys have ? I used the files in demo-sensor-2.0 rar file to get the extrinsics.

**Comment by ImCabbage** [comment]
Hi, I installed rviz in the apollo docker, but it seems that I cannot see any topic using it. How could you do that? I did not see any frame in the rviz. @ankitvora7

**Comment by snehagn** [comment]
@ankitvora7 - Hi, can you help confirm the individual sensor frames within Apollo? What I am seeing from the image: Radar and LiDAR - FLU, Novatel - RFU and Cameras - z forward, x right and y down?

**Comment by ankitvora7** [comment]
@snehagn - Yes you're right! This is what I obtained from the calibration files available with the 'demo-sensor-2.0' bag.

**Comment by snehagn** [comment]
@ankitvora7 - Thank you, Ankit.

@techoe, @YangHan101, @weidezhang : 
1. Can you guys please confirm the reference frames used in the conf files for the calibration tools? What we have so far: camera-camera RFU, camera-lidar FLU, radar-camera RFU, IMU-vehicle RFU, multi-lidar-gnss RFU. 
2. Are the values in the YAML files output by the calibration tools in the same frame as the inputs?

**Comment by XinrRunChao** [comment]
> ![apollo sensor frame](https://user-images.githubusercontent.com/9420343/41779170-f687d98a-75fe-11e8-8c8d-90127d1538e1.png)
> Does this look right with what you guys have ? I used the files in demo-sensor-2.0 rar file to get the extrinsics.

how do you install rviz in apollo docker? What's your version of the apollo?

**Comment by XinrRunChao** [comment]
> Hi, I installed rviz in the apollo docker, but it seems that I cannot see any topic using it. How could you do that? I did not see any frame in the rviz. @ankitvor
how do you install rviz in apollo docker? What's your version of the apollo? Can you help me? Thank you

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
