### ISSUE TITLE
Request for usage documentation of third_party_perception

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#4655]
Hi Apollo developers, is it possible to provide some README or documentation on how the third_party_perception module is intended to be used in the Apollo system? Is it an add-on to the perception module and both will run concurrently? Or is it an alternative to the perception module and either of the two will run for perception functionality?

**Comment by Capri2014** [comment]
Please see this one. https://github.com/ApolloAuto/apollo/pull/4659

**Comment by hongkedavid** [comment]
@Capri2014 Thanks for your reply! Regarding the statement "this module was only intend to serve for the Prediction/Planning/Control algorithm in real vehicle before perception modules fully ready" in the README, dose it mean that at the current stage, we should run both the third-party perception (if there exists the hardware support) and the perception module concurrently on a real vehicle for safety consideration? Or we should disable the currently developing perception module and only run the third-party perception module? Is there any guideline for the current deployment of perception functionality on a real vehicle that runs Apollo's self-driving modules?

**Comment by Capri2014** [comment]
@hongkedavid No, I should have said "This was used before Apollo 2.5 perception was ready", now the perception module is ready, so we recommend use perception module instead of this third_party_perception.

**Comment by hongkedavid** [comment]
@Capri2014 I see. Thanks for your clarification!
