### ISSUE TITLE
How to understand apollo::routing::SubTopoGraph::InitSubNodeByValidRange?

### ISSUE THREAD

**Issue by zdsoi** [ApolloAuto/apollo#4666]
In apollo::routing::SubTopoGraph::InitSubNodeByValidRange(const TopoNode* topo_node, const std::vector<NodeSRange>& valid_range)

  ```
// Attention: no matter topo node has valid_range or not,

  // create map value first;

  auto& sub_node_vec = sub_node_range_sorted_map_[topo_node];

  auto& sub_node_set = sub_node_map_[topo_node];
```

What is value and meaning of the sub_node_range_sorted_map_&& sub_node_map_?And they are both not initialized.

**Comment by apollodevcommunity** [comment]
hello   please see the define\"  std::vector<std::shared_ptr<TopoNode>> topo_nodes_;  std::vector<std::shared_ptr<TopoEdge>> topo_edges_;  std::unordered_map<const TopoNode*   std::vector<NodeWithRange>>     ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=672
