### ISSUE TITLE
在apollo感知模块中为什么要用cnnseg分割出具体的障碍物信息(如人、大车、小车等)，分割出的障碍物信息在后续的规划、预测中有具体的应用吗？

### ISSUE THREAD

**Issue by yueshukun** [ApolloAuto/apollo#4672]

**Comment by yueshukun** [comment]
在apollo感知模块中为什么要用cnnseg分割出具体的障碍物信息(如人、大车、小车等)，分割出的障碍物信息在后续的规划、预测中有具体的应用吗？

**Comment by lianglia-apollo** [comment]
The classification of objects is one of the most important tasks that perception needs to perform for autonomous driving. That information is used in all other modules including tracking, prediction, decision making, and planning.

**Comment by jinghaomiao** [comment]
Yes prediction and planning will use that info.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
