### ISSUE TITLE
What's the difference between rtk planner, em planner, and lattice planner?

### ISSUE THREAD

**Issue by lntsh854** [ApolloAuto/apollo#4674]
What's the difference between rtk planner, em planner, and lattice planner?

**Comment by Abelteklu** [comment]
same question

**Comment by yangydavid** [comment]
RTK: it records the historical data (GPS, IMU) when you drive along a certain trajectory. Then, when you replay it using IPC online, your car will just followed the trajectory previously recorded through RTK system. 

EM: it follows the DP-QP optimization sequence for the path and speed profile 

Lattice: it decompose the kinematics into lateral and longitudinal directions. however, it follows the similar optimization strategies but pick different penalized items. 

Hope it helps. :)

**Comment by liujiwei777** [comment]
RTK Planner started at Apollo 1.0, which is used to plan the pre-set trajectory for the follow-through algorithm.

EM planner started in Apollo 1.5 and has been abandoned in 3.5. Based on dynamic planning and quadratic planning, it first carries out path planning and then speed planning, which is suitable for complex scenarios.

Lattice planner started with Apllo 2.5, and it also carries out path planning and speed planning, which is suitable for simple scenarios.

**Comment by daohu527** [comment]
> RTK Planner started at Apollo 1.0, which is used to plan the pre-set trajectory for the follow-through algorithm.
> 
> EM planner started in Apollo 1.5 and has been abandoned in 3.5. Based on dynamic planning and quadratic planning, it first carries out path planning and then speed planning, which is suitable for complex scenarios.
> 
> Lattice planner started with Apllo 2.5, and it also carries out path planning and speed planning, which is suitable for simple scenarios.

Why EM planner abandoned in 3.5, since it works for complex scenes. What is the replacement?

**Comment by mpostl** [comment]
> 
> 
> > RTK Planner started at Apollo 1.0, which is used to plan the pre-set trajectory for the follow-through algorithm.
> > EM planner started in Apollo 1.5 and has been abandoned in 3.5. Based on dynamic planning and quadratic planning, it first carries out path planning and then speed planning, which is suitable for complex scenarios.
> > Lattice planner started with Apllo 2.5, and it also carries out path planning and speed planning, which is suitable for simple scenarios.
> 
> Why EM planner abandoned in 3.5, since it works for complex scenes. What is the replacement?

Any information to that? Would be interesting why the em planner was removed.

**Comment by YingjieLu** [comment]
> > > RTK Planner started at Apollo 1.0, which is used to plan the pre-set trajectory for the follow-through algorithm.
> > > EM planner started in Apollo 1.5 and has been abandoned in 3.5. Based on dynamic planning and quadratic planning, it first carries out path planning and then speed planning, which is suitable for complex scenarios.
> > > Lattice planner started with Apllo 2.5, and it also carries out path planning and speed planning, which is suitable for simple scenarios.
> > 
> > 
> > Why EM planner abandoned in 3.5, since it works for complex scenes. What is the replacement?
> 
> Any information to that? Would be interesting why the em planner was removed.

As far as I noticed, it is not replaced, instead it got name changed, and become the planner that by default being applied. Lattice planner still exists in the code in 3.5, but it is not used anymore.

**Comment by marcusvinicius178** [comment]
Hi @YingjieLu is it still possible to use the Lattice planner on Apollo 6.0? I could not enable it: https://github.com/ApolloAuto/apollo/issues/13828

Besides that I tied to use it on Apollo 3.0. However I was not able to run this Apollo release with SVL simulator? 
https://github.com/lgsvl/simulator/issues/1475

Thanks for some feedback
