### ISSUE TITLE
Loading my own PCD, PLY or PNG Map files to Apollo.

### ISSUE THREAD

**Issue by zoidzilla** [ApolloAuto/apollo#4697]
Hello Apollo developers. I am basically completely new to Apollo and I have question. If I somehow have obtained some large Geo-referenced maps in either PCD, PLY or PNG format, is there a way to upload these maps to Apollo for later usage? If yes, could you please provide me with an example of how to do that?

Thank you in advance!

**Comment by jinghaomiao** [comment]
Currently Apollo map follows the opendrive data format.

**Comment by zoidzilla** [comment]
Hello and thank you for your reply. After finding the following topic: https://github.com/ApolloAuto/apollo/issues/3005 , I realized that Apollo implements an augmented/altered version of OpenDrive format.Ccould I have the Apollo OpenDrive Map specification please? Thank you so much! kondaxakis@gmail.com

**Comment by natashadsouza** [comment]
@zoidzilla please use: [the following link ](https://www.surveymonkey.com/r/DXWK3Q6) to send us your details. Once we have it, we will send you the format. Thanks!

**Comment by daohu527** [comment]
Here is the Apollo OpenDrive specification https://github.com/ApolloAuto/apollo/discussions/15117
