### ISSUE TITLE
Safety / ISO 26262 ASIL-D coverage of Apollo.Auto

### ISSUE THREAD

**Issue by jonny07** [ApolloAuto/apollo#4698]
Apollo.Auto makes it possible to build a self driving car. However I could not find any safety information about the software. Is safety taken into account during SW development / does the SW fulfill ASIL-D if an appropriate OS is used (e.g. QNX)? Or is the Apollo.Auto SW currently only a working prototype and SW will be reworked/rewritten later for safety?

**Comment by jilinzhou** [comment]
We have ported Apollo 2.0 over QNX recently including apollo_platform and apollo. Certainly a lot of work need to be done to meet ISO 26262 ASIS-D.

**Comment by jonny07** [comment]
Ok, thanks a lot for your quick answer!
