### ISSUE TITLE
Mac Support.

### ISSUE THREAD

**Issue by hua3505** [ApolloAuto/apollo#47]
I run script install_docker.sh but found need apt-get. Could you adapt scripts for mac? Thanks very much.

**Comment by huijian222** [comment]
You need install Docker first.

**Comment by ycool** [comment]
steps to install docker in Mac: https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac

**Comment by bucaixiaot** [comment]
我安装了docker， 然后还是报错 @ycool

**Comment by ycool** [comment]
@bucaixiaot  what's the commands you run and what's the error msg? 

Right now only Ubuntu is tested here. So other platforms definitely need some helps :)

**Comment by bucaixiaot** [comment]
@ycool 
Environmental:mac pro 
I have installed docker.My last mistake was  Unsupported system.

I have switched to the source directory,   What do I do now?
manmans-MacBook-Pro:apollo-master manman$

**Comment by ycool** [comment]
Currently, Mac platform is not supported yet. Some extra developments are required. Help is very welcome :)

In case you need run Apollo in Mac platform, please vote it up. If it has high demand, we can bump up its priority.

**Comment by StanleyTian** [comment]
Really looking forward for the Mac edition.

**Comment by qiankunzhu** [comment]
Hi guys, if you are familiar to docker and urgent to build with mac, you can install docker for mac first, and check the hello world docker test can work, then you can follow the ./docker/scripts/dev_start.sh, dev_into.sh scripts  steps: pull img, start the docker (there is some work to do replace some command with mac's), and the same with the into scripts. Hope your help and response.

**Comment by ordram** [comment]
真正期待Mac版。

**Comment by 312362115** [comment]
`"Please use Linux, we recommend Ubuntu 14.04."`  -- `apollo.sh`
holy shit

**Comment by schromotion** [comment]
+1 for Mac Support. Thanks for opening up the project guys!

**Comment by xiaoxq** [comment]
Personally I ever tried to work on Mac. The hack is, running a Linux-based VM which provides docker service.

```
brew install docker docker-machine
brew cask install virtualbox
docker-machine create --driver virtualbox default
eval $(docker-machine env default)
```

Besides that, edit the docker/scripts/..._start.sh to skip mounting the HOME directory to docker container, as there is some difference between the structures of Mac HOME dir and Linux HOME.

It's hacky. Feel free to play with it, and of course, at your own risk :)

**Comment by cly** [comment]
+1 for mac support

**Comment by astromme** [comment]
@ycool Can you give a high-level overview of the work required to add mac support? Might be helpful for someone who decides to take on the work.

**Comment by ycool** [comment]
Basically we need make sure the following scripts work in Mac platform. 

https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh
https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_into.sh
https://github.com/ApolloAuto/apollo/blob/master/scripts/apollo_base.sh

Thanks.

**Comment by xiaoxq** [comment]
Added basic support for Mac. Have fun!
https://github.com/ApolloAuto/apollo/tree/master/docker/scripts/mac
