### ISSUE TITLE
What's the connection between EM algorithm and EMPlanner?

### ISSUE THREAD

**Issue by ireeX** [ApolloAuto/apollo#4710]
As the documents says, 

> In the EM planner, driving decisions and driving trajectory will be calculated based on map, routing and obstacles. DP (dynamic programming) based methods are used first to determine a raw path and speed profile, and then QP (quadratic programming) based methods are used to futher optimize the path and speed profile to get a smooth trajectory.

I can't find the implementation of EM algorithm in the code either.

**Comment by jinghaomiao** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/planner/em/em_planner.cc
Please start from this piece of code and follow the logic.

**Comment by osaman88** [comment]
You can see a description of the Planner algorithm here including relation to EM algorithm:
https://arxiv.org/abs/1807.08048

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @ireeX please let us know if you have additional questions. Thanks!
