### ISSUE TITLE
release docker images do not have ROS 

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#4715]
I want to build and gen my own release docker images.
I found that if I gen docker image, the image name begins with "run".
Here is the list I got:
```
run-x86_64-20171219_2028
run-x86_64-20171223_1308
run-x86_64-20171223_1501
run-x86_64-20171227_1352
run-x86_64-20171229_0957
run-x86_64-20180103_1300
run-x86_64-20180111_1409
run-x86_64-20180123_1329
run-x86_64-20180130_1338
run-x86_64-20180302_1123
run-x86_64-20180315_1337
run-x86_64-20180319_1154
run-x86_64-20180320_1118
run-x86_64-20180418_1942
run-x86_64-20180508_1647
run-x86_64-20180530_1312
run-x86_64-v2.0.0
```
When I use run-x86_64-20180302_1123 it would *not* have ros in /apollo/ros diretory. But if use run-x86_64-20180418_1942 it would have. Now I want to release master code, so I think I should use run-x86_64-20180530_1312, but it does not have ros.
Also if I release_into my own images, dreamview reports an error:
```
/apollo/scripts/apollo_base.sh: line 82: /apollo/ros/setup.bash: No such file or directory
Started supervisord with release conf
Start roscore...
voice_detector: started
dreamview: ERROR (spawn error)
gengqx@in_release_docker:/apollo$ ll ros 
total 12
drwxr-xr-x 3 root root 4096 Jun 27 15:54 ./
drwxrwxrwx 1 root root 4096 Jun 27 15:54 ../
drwxr-xr-x 6 root root 4096 Jun 27 15:54 share/

```
if I run with run-x86_64-20180418_1942,I would get
```
Started supervisord with release conf
Start roscore...
voice_detector: started
Dreamview is running at http://localhost:8888
gengqx@in_release_docker:/apollo$ ll ros/
total 68
drwxr-xr-x  1 gengqx gengqx  4096 Apr  3 10:43 ./
drwxrwxrwx  1 root   root    4096 Jun 27 10:19 ../
-rwxr-xr-x  1 gengqx gengqx     0 Apr  3 10:43 .catkin*
-rw-r--r--  1 gengqx gengqx    53 Apr  3 10:43 .rosinstall
-rwxr-xr-x  1 gengqx gengqx 12431 Apr  3 10:43 _setup_util.py*
drwxr-xr-x  2 gengqx gengqx  4096 Apr  3 10:43 bin/
-rwxr-xr-x  1 gengqx gengqx   506 Apr  3 10:43 env.sh*
drwxr-xr-x  4 gengqx gengqx  4096 Apr  3 10:43 etc/
drwxr-xr-x 69 gengqx gengqx  4096 Apr  3 10:43 include/
drwxr-xr-x  1 gengqx gengqx  4096 Apr  3 10:43 lib/
-rw-r--r--  1 gengqx gengqx     6 Apr  3 10:43 meta.txt
-rw-r--r--  1 gengqx gengqx   260 Apr  3 10:43 setup.bash
-rw-r--r--  1 gengqx gengqx  2598 Apr  3 10:43 setup.sh
-rw-r--r--  1 gengqx gengqx   270 Apr  3 10:43 setup.zsh
drwxr-xr-x  1 gengqx gengqx  4096 Apr  3 10:43 share/
```
So I want to know what's the difference between those images. Is there any way I can build "run" images by myself.

**Comment by freeHackOfJeff** [comment]
Hence, as per your try out, the new release with ROS enabled and works just fine. Could you please kindly try another higher release version to verify if that is also built with ROS?  If so, this issue might
caused because we failed to add ROS in build procedure of older release IMHO.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by liutgnu** [comment]
Problem still remains, I'm currently using apolloauto/apollo:run-x86_64-20181127_1530, no ros in /apollo/ros, same as apolloauto/apollo:run-x86_64-20180906_2002. but as mentioned by gengqx, apolloauto/apollo:run-x86_64-20180418_1942 works fine. Also, I list those 3 images' history by command: docker history <img>, run-x86_64-20180418_1942 seems compeletly different from the other 2. Could you please solve this problem or tell us the reason of the differences? Thanks!

**Comment by natashadsouza** [comment]
@liutgnu which version of Apollo are you trying to run? 
Also, as @freeHackOfJeff mentioned earlier, could you try running a higher version as we do not see the same issue on our end. Let me know your progress. Thanks!
