### ISSUE TITLE
third_party_perception 模块中全局坐标转换有bug

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#4717]
在第三方感知里，全局坐标转换用了如下函数：
![_20180627171617](https://user-images.githubusercontent.com/16748704/41964903-d4652a0a-7a2d-11e8-860f-38118cd0ec71.png)

这个函数接收相对左边x，y和相对偏航角。 输出全局坐标，但是实际出来的结果是 在测试的时候，本车车头转多少角度，对应的追踪目标就绕本车转多少角度，只有在目标物与本车在一条线上时才准确。

**Comment by JonathanJones92** [comment]
@zhxt @bigwhite @xczhanjun FYI

**Comment by JonathanJones92** [comment]
![0ae20ddd-f7d9-4afa-8176-81c900d278f6](https://user-images.githubusercontent.com/16748704/42080814-6c59b572-7bb6-11e8-814b-fd141a91f520.jpg)
![Uploading 02987098-1d22-46ea-bc47-83ad600610e5.jpg…]()
障碍物会随主车转向时前后平移。

**Comment by JonathanJones92** [comment]
@jinghaomiao @all2one

**Comment by zhxt** [comment]
@JonathanJones92 Sorry, I have no idea about this. But I think @rongqiqiu may know since this module is added by him.

**Comment by Capri2014** [comment]
@JonathanJones92 So how exactly did you use this one for ? After 2.5, third_party_perception only support : third_party_perception + relative map + navigation planning/control for 2.5 in Navi mode.  It looks like you still have HD map along with third_party_perception?

**Comment by JonathanJones92** [comment]
@Capri2014  Yes, I’m using HD map mode and I turned  off the navigation mode in third party perception. From the code, it’s clear it has 2 modes which can be switched from gflags.

**Comment by JonathanJones92** [comment]
@rongqiqiu  can you help me to check this issue ?

**Comment by JonathanJones92** [comment]
@zhxt @Capri2014 @richtong   Dear colleagues,

I believing that this is a bug instead of question. As per discussion above, the coordinate system trans function has problems in transfering latitude distance .
The related functions are SLTOXY and GetAngleFromQuaternion. The 1st one responsible for rotating the the coordinate system and the 2nd one is to find the rotating angle. 

I have been stuck in this problem for 2 weeks, I would appreciate if Baidu colleagues can help me to solve this.

Thanks,
Jonathan

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
