### ISSUE TITLE
How does Apollo distinguish between multiple traffic lights in the ROI? Also does apollo recognize a flashing red and yellow light?

### ISSUE THREAD

**Issue by aseelam** [ApolloAuto/apollo#4718]
Dear Contributors and Apollo community,
I am working on traffic light detection module in Apollo and observed a few limitations in the module. Can you share information regarding these:
1) Does Apollo recognize a flashing red light and flashing yellow light as STOP and YIELD signs respectively? If NO, in which version of Apollo do you plan to include the feature. Is anyone currently working on that aspect? 
2) How does Apollo distinguish between multiple traffic lights in the region of interest? As far as I have observed, a statement in the docs mentioned that it chooses it based on input lights position and shape. However, this is still unclear of how it decides in the event of a non-reliable localization message. Do we have a fault tolerant system ?

Looking forward for your replies.

Best,
Aniketh Reddy.

**Comment by techoe** [comment]
Hi @aseelam , 
Thank you for showing an interest in Apollo. 
1. We do not recognize the flashing red light yet. Each country has different meaning for flashing lights. For example, in China there is no flashing red or yellow lights. We will plan to support them later.
2. We use the HD map for traffic light detection. All 3D localization of traffic lights are saved in the HD map.
Thank you,
Tae Eun
