### ISSUE TITLE
Test cases in Predictor

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4727]
Hi All,

I have recently started working on Apollo. 

Can anybody please tell me how to use then test cases in predictor?

Update: I have noticed many test programs in the apollo which uses gtest to perform unit testing. Could you please let me know the procedure to use these test cases?

Thank you,
KK

**Comment by freeHackOfJeff** [comment]
Hello,

Thanks for your passion and that's more than welcome to work on Apollo!

I'd recommend you get familer to gtest as a beginning, then look through those test cases in each directory. i.e, free_move, lane_sequence, etc... to find out how the existing test is wrote. Build Apollo, run those test cases, find issues, add new test cases to improve the test coverage.

Thanks,
-Jie Liu(Jeff)

**Comment by kk2491** [comment]
Hi @freeHackOfJeff Thanks for the reply..  I have been going through the gflags... Will go through and let you know..

**Comment by kk2491** [comment]
@freeHackOfJeff Yes, I was able to get the test cases' executable files. The files were inside bazel-bin. 
I am trying to analyze the test case programs, will update here if I face any issues. 

Thank you,
KK

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen it if you have additional questions. Thanks!
