### ISSUE TITLE
Calibration tools complain about INS_STAT even when it is 56

### ISSUE THREAD

**Issue by rgunjala93** [ApolloAuto/apollo#4732]
I am trying to run the extrinsic sensor calibration tools and they seem to complain about the INS_STAT not being 56. But when I echo the /apollo/sensor/gnss/ins_stat topic I can see that the position type is 56. Can someone help me with this problem? 
![screenshot from 2018-06-19 15_20_35 1](https://user-images.githubusercontent.com/32493745/42059797-265c4f1e-7b14-11e8-9979-c68fcebcba2b.png)

The vehicle I am trying to work with does not have a drive-by-wire system, but I don't see the calibration nodes subscribing to any of the CAN topics so I am assuming that should not be a problem?

**Comment by hzdsdhr** [comment]
Have check your conf file for camera_camera_calibrator? You can set the ins_stat topic name, you need to check if it's the same topic you are using. If this can't fix your problem try to connect to the novatel receiver in different ways, like using usb instead of internet cable.

**Comment by techoe** [comment]
The error log occurs (stat=-1) whenever the tool have not receive any gnss message or the image stamp is not correct. Please check the topic of GNSS message or image stamp.

**Comment by YangHan101** [comment]
You can try the time_sync.sh script under /apollo/scripts. 
It could also be the UVCVideo is using the relative time setting. If that is the case, try with root access:
```
rmmod uvcvideo; modprobe uvcvideo clock=realtime
```
