### ISSUE TITLE
Whether the speed-acc-brake/throttle calibration table only applicable to the control of small turning angle?

### ISSUE THREAD

**Issue by follow123** [ApolloAuto/apollo#4739]
I have uesd the apollo's lon_control to control vehicle. According to the logic of longitudinal control, 
I need to update the speed-acc-brake/throttle calibration table, but after updating the calibration table according to the documented document, I found it doesn't work. 

Because I want ues the controller to achive the Automatic Parking, which with a low speed and a big turning angle, so I modified the method of calibration: change the vehicle along a straight line to travel at a fixed angle. After do this, the calibration table can worked.

So, I have a geuss that Apollo's code is not very suitable for Automatic Parking scenes， is it? Or the calibration moudle only applicable to the control of small turning angle?

**Comment by Capri2014** [comment]
@follow123 Thanks for playing with it and let us know. -- The short answer for your questions is No. It is not specifically tailing for "Automatic Parking" when it is really really small speed. (~0.2 m/s when chassis resolution itself it not good). Secondly, I am glad that you modified the code and made it work. But the longitudinal table was purposely designed to be decoupled from steering control so they wont mix and interfere with each other. -- I would personally make changes in lateral controller to handle this situation.

**Comment by follow123** [comment]
@Capri2014  Thanks for your reply.

I'll find where my problem really is, and still look forward to your update.

**Comment by follow123** [comment]
Another question：
In longitudinal controller, why the station error is:

> debug->set_station_error(reference_point.path_point().s() - s_matched);
> (apollo\modules\control\controller\lon_controller.cc              line:347)

the same as `debug->set_speed_error(reference_point.v() - s_dot_matched)`

Read the paper :`Optimal trajectory generation for dynamic street scenarios in a  FrenÃ©t Frame, Moritz Werling, Julius Ziegler, SÃ¶ren Kammel and Sebastian Thrun, ICRA 2010`, I know how to calculate the `s_dot_matched`, but I still not very clear why the station_error is the station found by time

> TrajectoryPoint reference_point =
>       trajectory_analyzer->QueryNearestPointByAbsoluteTime(
>           current_control_time);
> (apollo\modules\control\controller\lon_controller.cc              line:337)

to minus the `s_dot_matched ` ranther than the station found by  

> auto matched_point = trajectory_analyzer->QueryMatchedPathPoint(
>       VehicleStateProvider::instance()->x(),
>       VehicleStateProvider::instance()->y());
> (apollo\modules\control\controller\lon_controller.cc              line:323)

to minus the current station, I am not very clear, can you answer it for me? Thanks very much.

**Comment by follow123** [comment]
@Capri2014  I know the longitudinal table was purposely designed to be decoupled from steering control, but when I ues the calibration table
 ( calibrated by straight line, and I just use the lon_controller without the lat_controller, steering control was achieved by directly setting the steering wheel angle by time in my simulation environment(Carsim + Simulink). ) , 
the vehicle does not running, maybe the brake_cmd too big. Because with a  front wheel drift angle or not(Vehicle is a front-drive car), the power required by the vehicle, or the acceleration of the vehicle, and the maximum speed achieved are different. 
So I changed the methon, when update the table, I set the front wheel drift angle to 30° (my max Ackerman's corner) to produce a new table, after do this, the vehicle can running depend on this table. But do this, lon_controller and lat_controller have produced coupling, contrary to the original intention of your design.

**Comment by follow123** [comment]
@Capri2014  your means is let me to change corning stiffness and slip ratio, to make the car can run in the table calibrated by straight line, is it? I will try and give you feedback whether this method is effective.

Thanks for your reply.
