### ISSUE TITLE
gen_pose_file.py: rewrote the file

### ISSUE THREAD

**Issue by freeHackOfJeff** [ApolloAuto/apollo#4770]
1) Argument checking up is invalid and not user friendly
2) Don't use print to write file
3) Rename pcd_file to captical letter since it is iteral, myabe I would refactor a couple of files to consolidate this kind of stuff to another generic file in the future.
4) Rename main() to meaningful method name.

**Comment by natashadsouza** [comment]
Please submit a pull request for the changes you would like to make. Currently closing this issue. Thanks!
