### ISSUE TITLE
mono camera - *(sensor) calibration - suggestions for external calibration tools.

### ISSUE THREAD

**Issue by snehagn** [ApolloAuto/apollo#4779]
Hi everyone,

We have had several issues with the camera-camera and camera-lidar calibration tools provided on the Github page. I would really like to move away from this for extrinsic calibration until there is an update. 

Any suggestions on open source tools (ROS or otherwise) for mono camera-camera and mono camera - lidar calibrations?

Thanks,
Sneha

**Comment by freeHackOfJeff** [comment]
Hey Sneha,

Would you please kindly to report those issues regarding calibration tools or get involved in the development is more than welcome and appreciated!

Since I said that, I'd like to help from the technical point of view.

Thanks,
-Jeff

**Comment by snehagn** [comment]
Hey Jeff,

Please see #4732, #4241 and #4511. We have been trying other calibration tools, but trying to land on a good pattern that works simultaneously for the 6mm and 25mm camera setup in Apollo. 

Thanks,
Sneha
