### ISSUE TITLE
Build Stboundary , what is the difference between PathObstacle with StBoundaryMapper?

### ISSUE THREAD

**Issue by histfuture** [ApolloAuto/apollo#4785]
@lianglia-apollo Hey  I m not quite understand what is the difference between BuildTrajectoryStBoundary in path_obstacle.cc and CreateStBoundary in st_boundary_mapper?  In both, they set stboundary to a given path_obstacle. So what is the differenece?

**Comment by lianglia-apollo** [comment]
They are similar. Build Stboundary in path obstacle uses reference line to pre-build approximate st boundaries.
