### ISSUE TITLE
Time difference between ROS and Apollo

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4793]
Hi Guys,

Recently I have started working on Apollo. I see that Apollo time is not same as ROS time.
Could anybody please let me know difference and also the relation between ROS and Apollo time.

Thank you,
KK

**Comment by kk2491** [comment]
Thank you for the response... Having hard time in understanding.. when I run apollo using bash scripts/bootstrap.sh, it would run based on ROS time or is there any difference. ?

**Comment by follow123** [comment]
The three kinds of clocks in Apollo is different in time. Your Apollo time maybe the system time, because your project maybe workede in the Linux or other system, it's not the true ROS system.

**Comment by kk2491** [comment]
@follow123 Thank you so much for the explanation .. :-) I got it working now..

**Comment by kk2491** [comment]
Thanks for the help guys.. I will be closing this issue ...
