### ISSUE TITLE
How can I get the localization data for MSF localizaiton in China?

### ISSUE THREAD

**Issue by fenglupeter** [ApolloAuto/apollo#4796]
I can't download the data
"Download localization data from [Apollo Data Open Platform](http://data.apollo.auto/?name=sensor%20data&data_key=multisensor&data_type=1&locale=en-us&lang=en)（US only."

**Comment by zhouyao4321** [comment]
Maybe you can visit this web site use a US IP.
Or try this link: http://data.apollo.auto/help?name=sensor%20data&data_key=multisensor&data_type=1&locale=en-us&lang=en

**Comment by natashadsouza** [comment]
@fenglupeter were you able to download the data?

**Comment by storypku** [comment]
Closed as no response for too long.
