### ISSUE TITLE
where is the source code of modified caffe used by the perception module.

### ISSUE THREAD

**Issue by csukuangfj** [ApolloAuto/apollo#4797]
The readme.md (https://github.com/ApolloAuto/apollo/tree/master/modules/perception)
says a modified caffe is used, but no link to the source code of the modified version is available.

**Comment by xiaoshuliu** [comment]
@csukuangfj I don't think this part is open-sourced.

**Comment by csukuangfj** [comment]
@xiaoshuliu
thank you for the comment.

Many open source projects are used inside Apollo including caffe. Are there any reasons to make Apollo open sourced but not the modified caffe ?

**Comment by xiaoshuliu** [comment]
@csukuangfj I'm sorry I don't know the reason...

**Comment by lianglia-apollo** [comment]
Current the modified caffe is not open sourced. It is provided as a .so library.

**Comment by cedricxie** [comment]
@lianglia-apollo Hi Liangliang, I have two questions now regarding this issue.

1. Is there any plan to open source this part right now?
2. The .so library is compiled using gcc 4.8. Is it possible to request .so file complied using gcc 5+?

Thanks for your answer!

Yuesong

**Comment by xiaoxq** [comment]
It's retired in master HEAD.
