### ISSUE TITLE
Proto file for moving obstacle of type VEHICLE

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4800]
Hi All,

I am trying to publish a moving obstacle of type VEHICLE to the Prediction module.

Could anybody please suggest me what are the mandatory fields in proto buffer file for the moving obstacle.

The below test_data is given in apollo.

     header {
       timestamp_sec: 1501183430.161906
       module_name: "perception"
       sequence_num: 15839
     }
     perception_obstacle {
       id: 1
       position {
       x: -458.941,
       y: -159.240,
       z: 0.0
      }
      theta: -0.349
      velocity {
      x: 18.794
      y: -6.839
      z: 0
      }
      length: 4
      width: 2
      height: 1
      tracking_time: 1
      type: VEHICLE
      timestamp: 1501183430.1619561
    }

Thank you,
KK

**Comment by kk2491** [comment]
@jinghaomiao Thank you for the input.. I was able to get it done .. :)

**Comment by jinghaomiao** [comment]
@kk2491 I am closing the ticket.
