### ISSUE TITLE
Question about making obstacles in Dreamview Simulation Mode

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#4822]
Hi guys, I get great help every time on this board. Thanks!

I'm trying to make some obstacles in Dreamview Simulation Mode and I have some questions about it.

I opened issue (#4626) and @mickeyouyou gave me the answer thankfully, so now I can make one obstacle in Dreamview Simulation Mode.

I have two more questions below about making obstacles.

### Q1. How can I make several obstacles ?
I tried to make several obstacles. So I opened some terminal windows and executed the following commands.
```
# Terminal 1 (in modules/tools/perception)
python replay_perception.sh static_obstacle_1.json
```
```
# Terminal 2 (in modules/tools/perception)
python replay_perception.sh static_obstacle_2.json
```
I set id_value and x,y_coordinate_values for the two json files differently.
But it seems that they do not work properly.
Can you tell me how to fix it?

### Q2. Is there any tools for creating path(_trace value_ in json file) for the obstacle ?
In example file `garage_onroad_vehicle_3.json`, there are trace values and obstacle in dreamview simulationworld moves along that path. I wonder about how Apolloteam made that trace values. (using rosbag file..?)

Thanks!

**Comment by siyangy** [comment]
Looks like @xiaoxq authored replay_perception.py, can you take a look at the two questions?

**Comment by xiaoxq** [comment]
Sorry that I just did the migration to make it work in Apollo, while with little knowledge about the logic. It's kind of outdated. I'll forward to the perception team to take a look.

**Comment by xiaoxq** [comment]
These modules/tools/perception tools staled for more than a year and were retired in https://github.com/ApolloAuto/apollo/pull/5204.

**Comment by hashim19** [comment]
@CCodie Were you able to generate two or more obstacles? I couldn't even find replay_perception.sh file in modules/tools/perception.
@xiaoxq can you help me with this?
Thanks in advance

**Comment by CCodie** [comment]
@hashim19 Hi, replay_perception.sh file has been removed from master branch as @xiaoxq mentioned above. You can find that file in r3.0.0 branch.
I made two obstacles by following command line after running Dreamview.
```
(in dev docker, /apollo/modules/tools/perception)
python replay_perception.sh garage_onroad_static_4.json garage_onroad_vehicle_3.json
```
You can run replay_perception.sh file with arguments(e.g. garage_onroad_static_4.json , garage_onroad_vehicle_3.json, ...) which you want to generate.
Further, you can make your own json files.

**Comment by hashim19** [comment]
@CCodie Thank you for your response. But when I try to run this above line. It gives me an error like below:
Traceback (most recent call last):
  File "replay_perception.py", line 14, in <module>
    from modules.perception.proto.perception_obstacle_pb2 import PerceptionObstacle
ImportError: No module named modules.perception.proto.perception_obstacle_pb2

Do you have any idea, what could be the problem?

**Comment by Iqbalparvi** [comment]
@CCodie @hashim19 can you solve the problem successfully ,is it necessary to write our own  code to generate obstacles in the dreamview around the car in simulation or we have to modify and use the code given by Apollo inside like 1_perception.pb.txt etc .
I am stuck here ..How to test the specific module?
How to change the direction of moving car?
please any one can help

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
