### ISSUE TITLE
如何在docker image下使用rqt_graph

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#483]
您好，
   在docker image下，我想使用rqt_graph，但是提示找不到命令，想问下如何才能在docker image下使用此命令？

**Comment by fengqikai1414** [comment]
@ahuer2435 在apollo项目中，我们只选取了ros的一个运行支持最小集，rqt_graph没有包含在其中。后续我们会尝试集成更多ros工具，方便大家使用。

**Comment by ahuer2435** [comment]
请问，现在可以单独安装使用rqt_graph？

**Comment by jinpingfan** [comment]
你可以试一下 $ rosrun rqt-graph rqt-graph

**Comment by ahuer2435** [comment]
提示错误，找不到包：
[rospack] Error: package 'rqt-graph' not found

**Comment by layssi** [comment]
Here is the workaround:

To view the nodes. Follow the following Steps:

Add the following line after line 100 in docker/scripts/dev_start.sh: 
“ -e DISPLAY=unix$DISPLAY \” 

Enter your docker container and run:  

sudo apt-get update 
sudo apt-get install ros-indigo-rqt ros-indigo-rqt-common-plugins
source /opt/ros/indigo/setup.bash 

You can new run rqt

**Comment by sscit** [comment]
Unfortunately, this workaround does not work for me:

Even after modifying _dev_start.sh_ according to your description, _sudo apt-get install ros-indigo-rqt_ just returns

```
/apollo$ sudo apt-get install ros-indigo-rqt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-indigo-rqt
```
Does anybody know why apt-get cannot find the corresponding package?

**Comment by layssi** [comment]
Try running sudo apt-get update, or add the keys (http://wiki.ros.org/indigo/Installation/Ubuntu)

Alternatively, you can run rqt on your local machine using your existing installation (if you have ros).

Also, Keep in mind that rqt does not recognize pb messages.

**Comment by sscit** [comment]
Thanks for your reply, adding the repos and keys of ROS worked for me.

> Alternatively, you can run rqt on your local machine using your existing installation (if you have ros).

Yes, I will try this, too, because apt-get does not update the ros version within folder "apollo" anyway, it creates a "fresh" checkout in /opt/ros/<distro> .

**Comment by Zoltan3057** [comment]
solution:  #1572
