### ISSUE TITLE
咨询RTK模式的算法

### ISSUE THREAD

**Issue by EthanGD** [ApolloAuto/apollo#4836]
想请问一下，RTK模式的算法，是基于什么原理呢，有没有什么论文可以参考。
目前只根据R. Mahony的论文，了解解决了姿态解算部分，位置解算暂时没有头绪。
可以介绍一些论文百度一下吗，谢谢。

**Comment by zhouyao4321** [comment]
RTK模式实际是转发了GNSS设备给出的 RTK + IMU 的组合导航结果。
对于RTK定位算法本身：在基于测站误差相关的前提下，利用毫米级的载波相位观测，在固定对应模糊度后，实现高精度的动、静态定位的gnss技术，叫RTK。参考论文：Precise robust positioning with inertial/GPS RTK，

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
