### ISSUE TITLE
Traffice decider tasks 

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4838]
Hi All,

Can anybody please give me some insights on how the traffic decider tasks are formulated.

If you could provide me a document with the explanation of each tasks would be great. 

Directory: apollo/modules/planning/tasks/traffic_decider/

Thank you,
KK

**Comment by lianglia-apollo** [comment]
The traffic decider tasks are to make rule-based decisions on ego vehicle and obstacles. It is highly scenario related so that you can find multiple deciders in the folder. I suggest reading codes in that folder for details. It is complex, but not complicated.

**Comment by kk2491** [comment]
@jmtao  .. Thanks for the response. I have tried the tasks. In case of Cyclist, the autonomous car doesn't follow the obstacle even if the speed of the cyclist is higher than the threshold. It does stop and go. 
Could you please let me know if there is any other conditions?

**Comment by jmtao** [comment]
@kk2491 can you be more specific or post screen shot of your DreamViewer? ADC follows the bicycle if the bicycle running along ADC's current reference line. If the bicycle stops ADC would stop.

**Comment by kk2491** [comment]
@jmtao .
1. When I try the follow behavior with "vehicle" as moving obstacle, I would see the follow behavior working as expected (I could see the green follow sign)
2. Even in the case of unknown moving obstacle it works normal.

But in the case of cyclist instead of seeing a follow behavior (with green follow sign) I could see "stop behavior" (read sign). However car doesnt come to stop it keeps on moving.

Thank you,
KK

**Comment by jmtao** [comment]
@kk2491 hope our answer resolved your question. If you still see this issue with a latest version, please post a screen shot. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Comment by hongkedavid** [comment]
> The traffic decider tasks are to make rule-based decisions on ego vehicle and obstacles. It is highly scenario related so that you can find multiple deciders in the folder. I suggest reading codes in that folder for details. It is complex, but not complicated.

@lianglia-apollo @jmtao Are these rules based on the US traffic law? Is there any standard that is followed?
