### ISSUE TITLE
Issues using compressed images

### ISSUE THREAD

**Issue by hadiTab** [ApolloAuto/apollo#4842]
The image handler for dreamview seems to support both sensor_msgs/Image and sensor_msgs/compressedImage as seen [here](https://github.com/ApolloAuto/apollo/blob/bfb0a00e160d1a7751425789a5e1abe28df66ad1/modules/dreamview/backend/handlers/image_handler.cc#L63).

However, compressed images seem to be only used if the use_navigation_mode flag is set to true as seen [here](https://github.com/ApolloAuto/apollo/blob/bfb0a00e160d1a7751425789a5e1abe28df66ad1/modules/dreamview/backend/handlers/image_handler.cc#L81).

However, I cannot get Apollo to accept compressed images even when I set the default value of the flag to true [here](https://github.com/ApolloAuto/apollo/blob/8a1108f80d41d16861213b11c05fff1d42e8302d/modules/common/configs/config_gflags.cc#L48) and recompile.

For reference, I have built a rosbridge node inside the apollo container which is publishing a compressed image on the topic: /apollo/sensor/camera/traffic/image_short. I was hoping to be able to view the image in the top left corner of the dreamview page when in navigation mode.

I get the following error: 
`[ERROR] [WallTime: 1530832638.823090] [Client 0] publish: Message type sensor_msgs/Image does not have a field format`

The message is, however, of type sensor_msgs/CompressedImage but Apollo seems to be subscribing to sensor_msgs/Image.

How can I get it to use compressed images? Thanks.

**Comment by mickeyouyou** [comment]
ROS topic to message need to be transform, like `cv_bridge::toCvCopy(image);` 

Are you sure you have this part of the operation?

**Comment by mickeyouyou** [comment]
Hi @hadiTab, as you said above，compressed images is subscribe by `AdapterManager::AddCompressedImageCallback(&ImageHandler::OnImage, this)`,but this function is designed for topic `camera/image_raw`

**Comment by hadiTab** [comment]
@mickeyouyou I had assumed that the topic name remains the same. Publishing my image on camera/image_raw does solve the problem of receiving the error. However the only way I'm able to get apollo to subscribe to compressed images is by changing[ this](https://github.com/ApolloAuto/apollo/blob/bfb0a00e160d1a7751425789a5e1abe28df66ad1/modules/dreamview/backend/handlers/image_handler.cc#L80) function so that it always uses `AddCompressedImageCallback()` and ignores the flag. How do I get the flag to switch to true?

**Comment by siyangy** [comment]
@hadiTab You can just change this flag file: https://github.com/ApolloAuto/apollo/blob/master/modules/common/data/global_flagfile.txt#L14 w/o recompiling.

**Comment by hadiTab** [comment]
Thanks!
