### ISSUE TITLE
How to Access apollo ros messages from outside of docker container?

### ISSUE THREAD

**Issue by jpkuta** [ApolloAuto/apollo#4844]
I want to be able to access ROS messages published in the Apollo docker container with the rosmaster running in the Apollo docker container...

but be able to subscribe to these messages from the host outside of the docker container.

How can I do this?

Also How can I run RVIZ from INSIDE with docker container?

**Comment by startcode** [comment]
This use case is not supported in Apollo

**Comment by snuffysasa** [comment]
Any work around?  To send ros messages to nodes that run outside of the docker container?

**Comment by mickeyouyou** [comment]
you can refer the solution #4892 .

**Comment by snuffysasa** [comment]
@mickeyouyou 

thanks, I found this too.   And it works for me. Can close this issue.

**Comment by mickeyouyou** [comment]
You are welcome, open a new issue if you have another question.
