### ISSUE TITLE
关于新的CAN卡的添加——如何将新的CAN卡头文件（二次开发函数加入到apollo）

### ISSUE THREAD

**Issue by linpanusst** [ApolloAuto/apollo#4846]
查看了apollo的框架，没有找到ntcan.h，遂猜想此头文件是添加到其他路径下了，不在主代码里面。那么问题来了，我应该如何添加其他的CAN卡信息？

**Comment by Capri2014** [comment]
@linpanusst  please refer to https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/canbus/can_client for detailed information.

**Comment by linpanusst** [comment]
I have solve this problem. I need to add the ***.so in BUILD. For example:
in the folder of   apollo/modules/drivers/canbus/can_client/ . and in the file : BUILD 
add  code like this:
`cc_library(
    name = "usb_can_client",
    srcs = [
        "usb_can_client.cc",
        "lib/libcontrolcan.so",
    ],
    hdrs = [
        "usb_can_client.h",
        "usbcan.h",
        "controlcan.h",
    ],
    deps = [
        "//modules/drivers/canbus/can_client",
    ],
)`
the most important thing is the ***.so file. 
if you have problems, leave the massage.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved.
