### ISSUE TITLE
Cost functions for Lattice Planner

### ISSUE THREAD

**Issue by chybhao666** [ApolloAuto/apollo#4847]
In your lattice planner module, you are using 6 cost functions to contribute the whole planner cost:

  // Costs:
  // 1. Cost of missing the objective, e.g., cruise, stop, etc.
  // 2. Cost of logitudinal jerk
  // 3. Cost of logitudinal collision
  // 4. Cost of lateral offsets
  // 5. Cost of lateral comfort
  // 6. Cost of centripetal acceleration

Total cost = weighted sum of the costs above, weight of each cost function is defined manually:

// Lattice Evaluate Parameters
DEFINE_double(weight_lon_objective, 10.0, "Weight of longitudinal travel cost");
DEFINE_double(weight_lon_jerk, 1.0, "Weight of longitudinal jerk cost");
DEFINE_double(weight_lon_collision, 5.0,
              "Weight of logitudinal collision cost");
DEFINE_double(weight_lat_offset, 2.0, "Weight of lateral offset cost");
DEFINE_double(weight_lat_comfort, 10.0, "Weight of lateral comfort cost");
DEFINE_double(weight_centripetal_acceleration, 1.5,
              "Weight of centripetal acceleration");

My question is that in real world, there are many scenarios. How do you pick up the best weight array?
1. run apollo sdk in apollo Simulation. traverse all the scenarios as many as possible?
2. Empiricalism based on large-scale road testing?

 **If some developers are facing totally different scenarios from yours, how can they set the weights? Do you have any roadmap or insights to develop a learning-based approach to get your cost function more robust?**

**Comment by YajiaZhang** [comment]
Currently these parameters are determined empirically, based on our daily urban and highway testing. In future, we expect to develop a more advanced approach that can dynamically determine the weights according to scenarios.

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Please re-open the issue if you have follow up question.
