### ISSUE TITLE
Minimum speed for moving obstacle

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4850]
Hi Guys,

I am trying to generate a moving obstacle in the dreamview interface by publishing message to the Prediction module. 

However if I give a speed below 2.5 looks like it is considering it as static obstacle. Could you please let me know if there is a minimum speed for the moving obstacle. And I hope the units are in Km/h.

Note: I define the speed and heading of the obstacle then calculate the speed in X and Y co-ordinates. 

Thank you,
KK

**Comment by startcode** [comment]
Can you share the content of the file?

**Comment by kk2491** [comment]
@jinghaomiao   Thank you for the suggestion... 
I guess I found the point where the minimum speed is defined for an obstacle to consider it as moving.

```
DEFINE_double(static_obstacle_speed_threshold, 2.0,
              "obstacles are considered as static obstacle if its speed is "
"less than this value (m/s)");
```

Correct me if I am wrong.

**Comment by jinghaomiao** [comment]
@kk2491 please also refer to modules/prediction/container/obstacles/obstacle.cc:SetMotionStatus() for details.

**Comment by kk2491** [comment]
@jinghaomiao .. Thanks for the information. I am going through the code to get some insight. Meanwhile could you please also let me know whether similar kind of condition defined for bike/bicycles?

```
DEFINE_double(still_pedestrian_speed_threshold, 0.5,
              "Speed threshold for still pedestrians");
```

Also what would be the behavior of the car when there is Bicycle going in front of it ?
Follow or Stop and go ?

If needed I will raise a new case for this question.

**Comment by kk2491** [comment]
@jinghaomiao .. Could you please provide me clarification on this?

**Comment by apollodevcommunity** [comment]
You can configure gflag parameter \"--still_obstacle_speed_threshold=2.5\" in prediction.conf as you like. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=669
