### ISSUE TITLE
该怎么卸载阿波罗呢？

### ISSUE THREAD

**Issue by EdwinIZ8** [ApolloAuto/apollo#4852]
我现在需要安装阿波罗2.0.可是之前已经安装了阿波罗2.5.按照说明文档的描述，只能先装低版本，再装高版本。那么问题来了：
**怎样才能卸载阿波罗呢？**

**Comment by startcode** [comment]
I want to first clarify a few things:

* Apollo 2.5 has all features in Apollo 2.0, with many bugfix. Therefore, I recommend you keep using Apollo 2.5

* If you really only want to use Apollo 2.0, you also can simply check out Apollo 2.0 branch code `git checkout r2.0.0`. I think that's all you need to do.

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Feel free to re-open the issue if you have any additional question.
