### ISSUE TITLE
Add a Module to Apollo Modules

### ISSUE THREAD

**Issue by DevMohamedMI** [ApolloAuto/apollo#4855]
I want to be able to create my own module which would be built along with the other modules when I run $./apollo.sh build

Does that module have to have a script that calls it? What exactly makes a module and how can I create my own?

**Comment by startcode** [comment]
You can just add your module in `modules/` folder. You can use `modules/routing` as an example, which is a relatively simple module. Write the `BUILD` files properly and `apollo.sh` will build your module automatically

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Feel free to re-open if there is follow up questions.
