### ISSUE TITLE
Build Apollo in Visual Studio Code

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4871]
Hi Guys,

I am an autonomous vehicle enthusiast who recently started working on Apollo. My question/doubt is as follows.

I have successfully built the Apollo code using command line and ran the simulation as well. However to get better understanding on the control flow of the code I would want to build the code in Visual Studio code and run unit tests. 

I followed the procedure  given in  apollo/docs/howto/how_to_build_and_release.md. But when I run build in VS code I am getting the below error.

*[ERROR] Failed to start docker container "apollo_dev" based on image: apolloauto/apollo:dev-x86_64-20180130_1338
apollo_docker.sh: line 140: docker: command not found
The terminal process terminated with exit code: 127*

Does that mean even VS code should be run inside the docker. Currently I am running it in my host machine outside docker.

Excuse me the question looks silly.

Thank you,
KK

**Comment by kk2491** [comment]
@xiaoxq Thanks for the response..
I just build the code in another machine, and it worked fine. I wonder what was wrong in the old machine .. !! 
Now build is completed, is there any way I can do unit testing or debug each module to understand the logic better..?

**Comment by xiaoxq** [comment]
We provide `apollo.sh test` for unit testing, which is also recommended to run time to time even when you just work on a single module. Bazel will do the magic to cache most results and skip re-building.

**Comment by davidhopper2003** [comment]
@kk2491 
If you read documents with Chinese, you can view my blog `https://blog.csdn.net/davidhopper/article/details/79819587` and you may find answers for the questions you mentioned.
Otherwise, you can open the hidden directory `.vscode` in the `apollo` directory and view contents of the `tasks.json` and `launch.json` configuration files. Hope you can find the answer soon.
Best regards.

**Comment by davidhopper2003** [comment]
@kk2491 I really want to write this blog in English, but English is not my native language. It will take a lot of time for me to translate it. I do have a lot of things to do now, so I don't have time to do it.

**Comment by kk2491** [comment]
@davidhopper2003  .. Not a problem... I will try to translate and update you...

**Comment by kk2491** [comment]
@natashadsouza  Thanks for the explanation. Let me try and get back to you.

**Comment by kk2491** [comment]
@natashadsouza @davidhopper2003 .. 
After updating the glfw_fusion_viewer.cc as mentioned in the given document, I am getting the below error.

ERROR: /apollo/modules/perception/obstacle/camera/visualizer/BUILD:5:1: C++ compilation of rule '//modules/perception/obstacle/camera/visualizer:visualizer' failed (Exit 1)
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc: In member function 'bool apollo::perception::lowcostvisualizer::GLFWFusionViewer::window_init()':
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc:285:18: error: 'GLFW_CONTEXT_CREATION_API' was not declared in this scope
   glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
                  ^
modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc:285:45: error: 'GLFW_EGL_CONTEXT_API' was not declared in this scope
   glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);

Thank you,
KK

**Comment by kk2491** [comment]
@natashadsouza Could you please let me know how to proceed with this.

**Comment by kk2491** [comment]
@natashadsouza Thank you for the response.  
Do we need to install it manually inside the docker ? or does it come along with the docker ?

**Comment by kk2491** [comment]
@natashadsouza I have done a fresh installation of the glfw library. Seems like the error in the declaration while building apollo is resolved. 

But this resulted in a new error while running all the unit tests for apollo project. Error message given below.

```
//modules/perception/traffic_light/recognizer:unity_recognize_test       FAILED in 1.7s
//modules/perception/traffic_light/rectify:perception_traffic_light_rectify_test FAILED in 1.6s
```

Hope this latest update is helpful in finding the fix.

Thank you,
KK

**Comment by kk2491** [comment]
@natashadsouza .. Did you get chance to look at the issue.?

**Comment by natashadsouza** [comment]
@kk2491 send me a screenshot of the error message. I could not replicate your error message. You could send it to natashadsouza@baidu.com. Thanks!

**Comment by kk2491** [comment]
@natashadsouza .. Will send the error screen shot shortly.

**Comment by kk2491** [comment]
@natashadsouza I have sent you the details, kindly check.

**Comment by Arjun911** [comment]
Hi @natashadsouza 
I am also getting same error. I checked another thread https://github.com/ApolloAuto/apollo/issues/4554

My build is successful after doing required changes from https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md

but test cases are still not passing. One is failing as below

Platform : Ubuntu 16
below is the build logs 
`
  /home/infy-av/.cache/bazel/_bazel_infy-av/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/integration_tests/sunnyvale_big_loop_test/test.log

Executed 3 out of 222 tests: 221 tests pass and 1 fails locally.
============================
[ERROR] Test failed!
[INFO] Took 3 seconds
============================
The terminal process terminated with exit code: 255
`
Please suggest some help.

**Comment by kk2491** [comment]
@Arjun911 You are running apollo in system with GPU or without GPU ? 
If with GPU, then please check if you have the GPU drivers installed correctly.

**Comment by Arjun911** [comment]
@kk2491 I am using Nvidia TITAN Xp. I have installed driver and cuda. I am able to run Carla simulator on my machine. I believe drivers are installed perfectly. is there any way to check all GPU dependency for apollo?

**Comment by natashadsouza** [comment]
@Arjun911 please confirm if you have CUDA installed correctly: 
sudo NVIDIA-Linux-x86_64-375.xx.run --no-opengl-files -a -s
Also, please send me a screenshot of your error messages to help me understand the nature of your error. My email ID is contained in the thread.

**Comment by Arjun911** [comment]
@natashadsouza I am able to run now. Thanks for your support. Problem i was facing is posted on #5450 

Please check, it may be helpful for any fix.

**Comment by natashadsouza** [comment]
Thank you @kk2491 currently closing this issue as it is resolved.
