### ISSUE TITLE
gl_camera_visualzier is really slow

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#4872]
I finally got the apollo 2.5 perception lowcost visualizer to run on my PC and the visualizer to show up.

I am running using a GTX 1080 and am confused why the visualizer is so slow

I notice the actual perception CNN is running really fast and in realtime... as I can see by rostopic echo /apollo/perception/obstacle... so the actual perception is running well.

However, the visualizer gl_camera_visualizer that shows the bounding boxes... runs very slow and is almost 3 seconds behind. If I lower the resolution of my screen it runs faster.

Any ideas why the GLFW viewer would be so slow?

I am also wondering about cudnn, however, I am not sure this is related to this problem because I believe the DNN inferencing is happening fast enough.  

But I notice the perception module (running on GPU) seems to run the same and have the same performance whether I have cuDNN installed or not.

**Comment by techoe** [comment]
Visualization is currently only for debugging. However obviously it is too slow. It seems that reading the rosbag takes the most of time. Later we will provide an option to save and load compressed images.

**Comment by snuffysasa** [comment]
@techoe 

Okay I understand. However, it is also slow when using a camera feed in real-time, which isn't using rosbag. and this is also slow. Could there be another reason for this?

**Comment by snuffysasa** [comment]
@techoe 

Can you confirm that even with real-time camera feed, playing slow / delayed... is expected behavior currently?

**Comment by liuyangly25** [comment]
Hi @snuffysasa , what change did you make to make lowcost visualizer to work? Mine never show up.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
