### ISSUE TITLE
Synchronize messages from Adapters

### ISSUE THREAD

**Issue by cxia30** [ApolloAuto/apollo#4874]
Hello Apollo Team and developers,

I am wondering how to synchronize messages from different adapter managers? Message_filter can be used for the original ROS, but compiled with subscriber mechanism. Is there anyone know how to synchronize messages from adapters just like message_filter?

Thanks!

**Comment by siyangy** [comment]
You can either put message filters somehow in AdapterManager so that you can use subscriber mechanism or synchronize by yourself with multiple callbacks in your application level code.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @cxia30 if you have any additional questions, feel free to reopen it. Thanks!
