### ISSUE TITLE
velodyne_uitility

### ISSUE THREAD

**Issue by sudhanvakudlapur** [ApolloAuto/apollo#4880]
if (pt3d[0] == pt3d[0] && pt3d[1] == pt3d[1] && pt3d[2] == pt3d[2])

What is the significance of the above condition in velodyne_utility.cc at line 53?

**Comment by muleisheng** [comment]
Ii seems a defect for it is always true. Perhaps just for debugging.  Please let me know if I am not right

**Comment by zhouyao4321** [comment]
I guess this line is used to check NaN. For a float or double f, f != f will be true only if f is NaN.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks!
