### ISSUE TITLE
Is delta_s lower bound in dp_st_graph.cc  correct?

### ISSUE THREAD

**Issue by sandrobusse** [ApolloAuto/apollo#4881]
Hello,

in dp_st_graph.cc

> *next_lowest_row = point.index.s() - static_cast<int>(delta_s_lower_bound / unit_s_);

I was wondering why you substract  and do not add the static casted value.
I think s can only increasewhen driving forward and the performance of the dp_st_speed algorithm would be better if the 
number of reachable nodes is smaller.

Greetings

**Comment by lianglia-apollo** [comment]
It is fixed in #4921
