### ISSUE TITLE
how to run qp_spile_path_optimizer during em_planner execution?

### ISSUE THREAD

**Issue by MoonSeongJoo** [ApolloAuto/apollo#4884]
Hello.
 In the reviewing em_planner.cc, there are many tasks in the RegisterTasks().
 But, this function did not take qp_spline_path_optimizer.
 where is it? and how could run this QpSplinePathOptimizer in running time?
 After path decider module execution,  this path decision data send to qp_spline_path_optimizer
(Ignore/stop/nudge). but qp_spline_path_optimizer is missing in the run time.
please support this question.
thanks.

`void EMPlanner::RegisterTasks() {
  task_factory_.Register(DP_POLY_PATH_OPTIMIZER,
                         []() -> Task* { return new DpPolyPathOptimizer(); });
  task_factory_.Register(PATH_DECIDER,
                         []() -> Task* { return new PathDecider(); });
  task_factory_.Register(DP_ST_SPEED_OPTIMIZER,
                         []() -> Task* { return new DpStSpeedOptimizer(); });
  task_factory_.Register(SPEED_DECIDER,
                         []() -> Task* { return new SpeedDecider(); });
  task_factory_.Register(QP_SPLINE_ST_SPEED_OPTIMIZER, []() -> Task* {
    return new QpSplineStSpeedOptimizer();
  });
  task_factory_.Register(POLY_ST_SPEED_OPTIMIZER,
                         []() -> Task* { return new PolyStSpeedOptimizer(); });
}`

**Comment by douqian** [comment]
It seems we only implement QpSplinePathOptimizer, but not invoke in running time for less elapsed time.  If I'm not right ,please correct me @jiangtao and liangliang

**Comment by MoonSeongJoo** [comment]
@jiangtao 
Hello.
In the reviewing em_planner.cc, there are many tasks in the RegisterTasks().
But, this function did not take qp_spline_path_optimizer.
where is it? and how could run this QpSplinePathOptimizer in running time?
After path decider module execution, this path decision data send to qp_spline_path_optimizer
(Ignore/stop/nudge). but qp_spline_path_optimizer is missing in the run time.
please support this question.
thanks.
void EMPlanner::RegisterTasks() { task_factory_.Register(DP_POLY_PATH_OPTIMIZER, []() -> Task* { return new DpPolyPathOptimizer(); }); task_factory_.Register(PATH_DECIDER, []() -> Task* { return new PathDecider(); }); task_factory_.Register(DP_ST_SPEED_OPTIMIZER, []() -> Task* { return new DpStSpeedOptimizer(); }); task_factory_.Register(SPEED_DECIDER, []() -> Task* { return new SpeedDecider(); }); task_factory_.Register(QP_SPLINE_ST_SPEED_OPTIMIZER, []() -> Task* { return new QpSplineStSpeedOptimizer(); }); task_factory_.Register(POLY_ST_SPEED_OPTIMIZER, []() -> Task* { return new PolyStSpeedOptimizer(); }); }

**Comment by lianglia-apollo** [comment]
Currently we are not using qp_spline_path_optimizer so that you don't see it in the config file.

**Comment by Zhenni17** [comment]
Closing the issue due to no communication. Feel free to re-open the issue if there is follow up questions.
