### ISSUE TITLE
How to make up navotel

### ISSUE THREAD

**Issue by ytgcljj** [ApolloAuto/apollo#4885]
I have a novatel, I do not know how to access Apollo, please tell me one, make that file, start the file, thank you.

**Comment by muleisheng** [comment]
the quick start documents may have the answer. First you should install docker-ce. Then excuse following scripts one by one .
sudo  docker/scripts/dev_start.sh
sudo docker/scripts/dev_into.sh
./apollo.sh build

scripts/bootstrap.sh

Apollo is started successfully if there is no any errors.

**Comment by ytgcljj** [comment]
I know, I have started, and I have already connected novatel. How do I do this?

**Comment by mickeyouyou** [comment]
What is your specific model?

**Comment by ytgcljj** [comment]
PwrPak7-E1
![_20180710153425](https://user-images.githubusercontent.com/27713475/42495821-c5e3fae6-8456-11e8-9dd6-24c873b0dfae.jpg)

**Comment by mickeyouyou** [comment]
**How to adapt PP7/new GPS/IMU model?**

We will copy `modules/calibration/data/<vehicle>/gnss_params/gnss_conf.pb.txt` to `modules/drivers/gnss/conf/gnss_conf.pb.txt`, so if your device is a recommended PP6 or compatible PP7 Etc., you can do seamless support, modify the configuration file on, and then select the appropriate vehicle in Dreamview.

Then check the relevant topic output.
