### ISSUE TITLE
你好，我可以只是用你们的红绿灯检测模块不使用其他的模块吗？

### ISSUE THREAD

**Issue by gavinbai** [ApolloAuto/apollo#4886]
您好，我现在打算用一下Apollo的红绿灯检测模块，但是不打算使用障碍物检测模块和其他的模块，想问一下我只输入两个摄像头的数据可以吗？ 各个模块之间是否可以独立使用呢？还是说输入数据必须也得输入lidar和radar的数据？麻烦解答一下。

**Comment by gavinbai** [comment]
我是刚接触apollo，不大懂。

**Comment by muleisheng** [comment]
（1）可以只用两个摄像头的数据，
（2）各模块之间本来就是独立的进程，但是要注意各模块运行是需要相应的输入信息（文件）
（3）输入数据没必要一起输入Lidar和Radar的数据
这些应该可以通过配置去控制的

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
