### ISSUE TITLE
docker starting very slow

### ISSUE THREAD

**Issue by DeepakVellampalli** [ApolloAuto/apollo#4899]
Hi All,

When I type  `./docker/scripts/dev_start.sh` most of the times it starts docker quickly, however sometimes it delays a lot and won't attempt to start it. Is this to be considered as a problem? 
It will be great if someone can suggest me a way to fix this!

Thank you :)

**Comment by Grayhu07** [comment]
I think it is probably just internet connection problem, since it checks the image through internet and sometimes it may delay a little. If you are in China, maybe you can try `./docker/scripts/dev_start.sh -C`.

**Comment by natashadsouza** [comment]
Closing this issue as I believe it is resolved. @Grayhu07 thank you for your response.
