### ISSUE TITLE
aarch64构架环境下docker image获取失败

### ISSUE THREAD

**Issue by kingdouustc** [ApolloAuto/apollo#4903]
1.我在qemu中模拟了ubuntu aarch64的环境.
2.运行了 bash docker/scripts/dev_start.h, 报错如下
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
ff3a5c916c92: Already exists 
35d9a7f5de96: Pull complete 
Digest: sha256:68ab11db001d315fcd896a06d9100e6fa6ac0f2d578b6988a4e194b02cee62da
Status: Downloaded newer image for apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
08706b16f6fae3444cab785064b4bf798f4b2934f68cddfe11676c14cb6e0b6c
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_loop-latest
eec3aab3b621f410a3d11e18b4b29a41fa2f2c9fa2cc8995bba0eec85a4c26a1
[INFO] Start pulling docker image apolloauto/apollo:dev-aarch64-20170927_1111 ...
dev-aarch64-20170927_1111: Pulling from apolloauto/apollo
Digest: sha256:10fc9daa7699f30650df05b9f3aff9762a236433e089e8755dcb0f6cfb7baab0
Status: Image is up to date for apolloauto/apollo:dev-aarch64-20170927_1111
Cannot find device "can0"
Cannot find device "can0"
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.4.0-116-generic
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.4.0-116-generic
Error response from daemon: manifest for apolloauto/apollo:localization_volume-aarch64-latest not found
Unable to find image 'apolloauto/apollo:localization_volume-aarch64-latest' locally
docker: Error response from daemon: manifest for apolloauto/apollo:localization_volume-aarch64-latest not found.
See 'docker run --help'.
Error response from daemon: manifest for apolloauto/apollo:yolo3d_volume-aarch64-latest not found
Unable to find image 'apolloauto/apollo:yolo3d_volume-aarch64-latest' locally
docker: Error response from daemon: manifest for apolloauto/apollo:yolo3d_volume-aarch64-latest not found.
See 'docker run --help'.
[INFO] Starting docker container "apollo_dev" ...
docker: Error response from daemon: No such container: apollo_map_volume-sunnyvale_big_loop.
See 'docker run --help'.
[ERROR] Failed to start docker container "apollo_dev" based on image: apolloauto/apollo:dev-aarch64-20170927_1111

**Comment by mickeyouyou** [comment]
We have not maintained the image of the arm platform for a long time, and the subsequent versions (>1.5) have a lot of changes. The release of the image will mislead the developer. So,we suggest you adapt it according to the Dockerfile.

**Comment by mickeyouyou** [comment]
We will promote Apollo's adaptation on the arm platform in future, and if you have a better solution, you are welcome to contribute.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved.
