### ISSUE TITLE
Overtake behavior in Apollo

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4904]
Hi Guys,

I am trying to understand the overtake behavior of the autonomous vehicle in Apollo. Kindly help me in getting clearing my doubts.

Please find the below points
1.  Minimum speed for the obstacle to be considered as moving is 2 m/s
2.  If I test on an obstacle with speed less than 2 m/s the autonomous car would stop and go rather than following it
3.  If I test on an obstacle with speed greater than 2 m/s the autonomous car would follow
4.  I am curious to know in which cases the autonomous car would overtake the moving obstacle. What are parameters (speed, type etc) should be considering to test the overtake behavior.

Thank you,
KK

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Feel free to re-open if there are any follow up questions.
