### ISSUE TITLE
Lincoln MKZ must be hybrid?

### ISSUE THREAD

**Issue by sbhamad** [ApolloAuto/apollo#4908]
Lincoln MKZ reference vehicle must be hybrid to run apollo?

what is the detailed specifics of the car? minimum year of model and hybrid or not?

**Comment by natashadsouza** [comment]
@sbhamad to answer your questions:
- Lincoln MKZ reference vehicle must be hybrid to run apollo? Yes, hybrid cars offer better support for drive-by-wire systems.
- what is the detailed specifics of the car? minimum year of model and hybrid or not? There is no detailed specifics except the car being drive-by-wire capable and hybrid. However, from my experience and dataspeed's website:
* Lincoln MKZ, 2013 or newer
* Ford Fusion/Mondeo, 2017 or newer
* Hybrid model
(required for electronic brakes)
* Active Park Assist feature
(required for steering control)

Hope this helps! Let me know if you have any additional questions.

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Feel free to re-open the issue if there are any follow up questions.
