### ISSUE TITLE
使用IMU+GPS+RTK一体机如何加入apollo使用？

### ISSUE THREAD

**Issue by 263868161** [ApolloAuto/apollo#4915]
IMU+GPS+RTK一体机直接输出的就是经过处理的精确定位，如何加入apollo使用？谢谢

**Comment by mickeyouyou** [comment]
Could you share specific model with us ?

We currently use the following IMUs. We'll extend this list when a new IMU is introduced.
```proto
enum ImuType {
 
  IMAR_FSAS = 13;       // iMAR iIMU-FSAS
  ISA100C = 26;         // Northrop Grumman Litef ISA-100C
  ADIS16488 = 31;       // Analog Devices ADIS16488
  STIM300 = 32;         // Sensonor STIM300
  ISA100 = 34;          // Northrop Grumman Litef ISA-100
  ISA100_400HZ = 38;    // Northrop Grumman Litef ISA-100
  ISA100C_400HZ = 39;   // Northrop Grumman Litef ISA-100
  G320N = 40;           // EPSON G320N
  CPT_XW5651 = 41;      // IMU@SPAN-CPT, and XingWangYuda 5651
  UM442 = 42;           // UM442
}
```

**How to adapt PP7/new GPS/IMU model?**

if your device is a recommended PP6 or compatible PP7 Etc., you can do seamless support, modify the configuration file on,We will copy `modules/calibration/data/<vehicle>/gnss_params/gnss_conf.pb.txt` to `modules/drivers/gnss/conf/gnss_conf.pb.txt`, and then select the appropriate vehicle in Dreamview.

Then check the relevant topic output.

**Comment by 263868161** [comment]
@mickeyouyou 百度apollo高精度定位输入IMU、GPS以及RTK，然后apollo集成了算法处理，输出为高精度定位结果，我所使用的是IMU+GPS+RTK一体机，高精度定位算法集成在一体机中，直接通过串口输出高精度定位结果，具体IMU型号不详（因为这封装在一体机中），这种情况apollo如何处理？

**Comment by jilinzhou** [comment]
Take a look of localization module and replace the code which parses the current gnss driver published data to your own.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved. @263868161 if you have any additional questions, please feel free to reopen it. Thanks!

**Comment by ZMHSQ** [comment]
> 您可以与我们分享特定的型号吗？
> 
> 我们目前使用以下IMU。引入新的IMU时，我们将扩展此列表。
> 
> ```protobuf
> 枚举 ImuType {
>  
>   IMAR_FSAS = 13 ;       // iMAR iIMU-FSAS 
>   ISA100C = 26 ;         //诺斯罗普·格鲁曼公司Litef ISA-100C 
>   ADIS16488 = 31 ;       // Analog Devices ADIS16488 
>   STIM300 = 32 ;         // Sensonor STIM300 
>   ISA100 = 34 ;          //诺斯罗普·格鲁曼公司Litef ISA-100 
>   ISA100_400HZ = 38 ;    //诺斯罗普·格鲁曼公司Litef ISA-100 
>   ISA100C_400HZ = 39 ;   //诺斯罗普·格鲁曼公司Litef ISA-100 
>   G320N = 40;           // EPSON G320N 
>   CPT_XW5651 = 41 ;      // IMU @ SPAN-CPT和
>   XingWangYuda 5651 UM442 = 42 ;           // UM442 
> }
> ```
> 
> **如何适应PP7 /新型GPS / IMU模型？**
> 
> 如果您的设备是推荐的PP6或兼容的PP7等，则可以进行无缝支持，在上修改配置文件，我们将复制`modules/calibration/data/<vehicle>/gnss_par

> Could you share specific model with us ?
> 
> We currently use the following IMUs. We'll extend this list when a new IMU is introduced.
> 
> ```protobuf
> enum ImuType {
>  
>   IMAR_FSAS = 13;       // iMAR iIMU-FSAS
>   ISA100C = 26;         // Northrop Grumman Litef ISA-100C
>   ADIS16488 = 31;       // Analog Devices ADIS16488
>   STIM300 = 32;         // Sensonor STIM300
>   ISA100 = 34;          // Northrop Grumman Litef ISA-100
>   ISA100_400HZ = 38;    // Northrop Grumman Litef ISA-100
>   ISA100C_400HZ = 39;   // Northrop Grumman Litef ISA-100
>   G320N = 40;           // EPSON G320N
>   CPT_XW5651 = 41;      // IMU@SPAN-CPT, and XingWangYuda 5651
>   UM442 = 42;           // UM442
> }
> ```
> 
> **How to adapt PP7/new GPS/IMU model?**
> 
> if your device is a recommended PP6 or compatible PP7 Etc., you can do seamless support, modify the configuration file on,We will copy `modules/calibration/data/<vehicle>/gnss_params/gnss_conf.pb.txt` to `modules/drivers/gnss/conf/gnss_conf.pb.txt`, and then select the appropriate vehicle in Dreamview.
> 
> Then check the relevant topic output.

新的IMU型号怎么加入到apollo中？Novatel-G370N
