### ISSUE TITLE
localhost:8888 unable to connect in release container

### ISSUE THREAD

**Issue by lygincn** [ApolloAuto/apollo#4917]
Hi guys, 

I have recently started with apollo and followed the instructions below to try to run the demobag in dreamview in the release container:
https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide
here are the steps I've done:
1. installed docker 
2. cloned apollo source code 
3. started and entered release container
4. ran the demobag
Everything worked out fine and I got the following logs:

```
yige@yige-ThinkPad-E480:~/apollo$ bash docker/scripts/release_start.sh
[sudo] password for yige: 
/apollo/data/core/core_%e.%p
Type 'y' or 'Y' to pull docker image from China mirror or any other key from US mirror.
y
release-x86_64-v2.0.1: Pulling from apolloauto/apollo
Digest: sha256:4c77b79bbf8ecbcf9b07a5180d7eb1ca9eb4b0f0984d7b61db597887e12f26fe
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:release-x86_64-v2.0.1
modprobe: FATAL: Module nvidia not found.
modprobe: FATAL: Module nvidia-uvm not found.
b9bf9d4466e85533109841727e3ff3076448aa81d964f798f30d11cc2b226d26
Adding group `yige' (GID 1000) ...
Done.
Adding user `yige' ...
Adding new user `yige' (1000) with group `yige' ...
The home directory `/home/yige' already exists.  Not copying from `/etc/skel'.

Start roscore...
Started supervisord with release conf
Dreamview is running at http://localhost:8888
yige@yige-ThinkPad-E480:~/apollo$ bash docker/scripts/release_into.sh
yige@in_release_docker:/apollo$ cd docs/demo_guide
yige@in_release_docker:/apollo/docs/demo_guide$ rosbag play demo.bag
/tmp/apollo-platform/ros/ros_comm/rosbag/src/player.cpp:125 Player::publish() [ INFO] [1531234653.155823547]: Opening demo.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
 [PAUSED]   Bag Time: 1497125296.137357   Duration: 26.994878 / 38.393816     
```

So it's supposed that I can see dreamview when I go to localhost:8888, right?
But the truth is the firefox browser shows this error(have already tried with chrome, the same):

![screenshot from 2018-07-10 22 54 00](https://user-images.githubusercontent.com/40354939/42519337-68d988c6-8496-11e8-8241-aabc8a867b08.png)
![screenshot from 2018-07-10 23 08 53](https://user-images.githubusercontent.com/40354939/42519351-72595390-8496-11e8-9f0c-7ce448394c68.png)

Has anyone met this problem before? As my understanding it's unnecessary to build apollo or do anything else, when I use the release container and just want to try to run the demobag, am I right about this?
I'm still pretty new about apollo, so it could be very nice that you guys give me some suggestion and instructions here. Thank you very much!!

**Comment by lianglia-apollo** [comment]
We had some bugs that can cause this issue recently. Please update your code. It should be fixed in the newest version.

**Comment by MirrorLakr** [comment]
I build the Apollo3.0, and I also met this question. What should I do?

**Comment by lygincn** [comment]
@lianglia-apollo Thank you for answering. I have already updated my code and tried again. Unfortunately the problem is the same. Can the reason be like, that docker container can not set up a connection with my local computer to use my local port 8888?

**Comment by jinghaomiao** [comment]
@lygincn please use the dev docker. We plan to retire release docker soon.

**Comment by Zhenni17** [comment]
Closing the issue due to no further communication. Feel free to re-open it if there are any follow up questions.
