### ISSUE TITLE
Create a Custom Message of ROS type and Not a Protobuffer

### ISSUE THREAD

**Issue by DevMohamedMI** [ApolloAuto/apollo#4918]
I want to create a custom message bla.msg type that can usually be made in a ROS catkin workspace, and compiled into an easy to include header file. How would I do this with Apollo?

**Comment by snuffysasa** [comment]
I am also wondering this.  How to compile a custom msg in apollo that is not a proto msg.

How to add a my_custom_message.msg to the bazel BUILD file and so that I can include these custom classes in the Apollo .cc files

**Comment by snuffysasa** [comment]
Update: Compiling msg files into c++ header files with catkin outside of docker container, then copying the header files into apollo and including them worked.

**Comment by gladijos** [comment]
I has same issue. I need to use inside apollo module ackermann_msgs/AckermannDrive ROS message. 
I copied from my own ROS kinetic installation folder ros/include/ackermann_msgs/*.h files to bazel-out/local-dbg/bin/external/ros/_virtual_includes/ros_common/ros/include/ackermann_msgs/*.h and I got this error from bazel-build:

> ERROR: /apollo/modules/canbus/vehicle/new_vehicle/BUILD:35:1: undeclared inclusion(s) in rule '//modules/canbus/vehicle/new_vehicle:new_vehicle_controller':
this rule is missing dependency declarations for the following files included by 'modules/canbus/vehicle/new_vehicle/new_vehicle_controller.cc':
  'bazel-out/local-dbg/bin/external/ros/_virtual_includes/ros_common/ros/include/ackermann_msgs/AckermannDrive.h'

What I missed?

**Comment by gladijos** [comment]
Oh I got! My fault. I have copy to /home/tmp/ros/include directory inside docker. Have I cope content of ROS "share" folder to apollo docker  /home/tmp/ros/share directory?

**Comment by fengqikai1414** [comment]
> Have I cope content of ROS "share" folder to apollo docker /home/tmp/ros/share directory?
No, just copy the header files to /home/tmp/ros/include will be ok.

**Comment by fengqikai1414** [comment]
@DevMohamedMI

**Comment by gladijos** [comment]
It works. After adding header files to /home/tmp/ros/include I can include them with 
#include "ackermann_msgs/AckermannDrive.h".

An issue can be closed I think.

**Comment by gladijos** [comment]
I have to build with catkin_make package with my messages, copy them  in directory /home/tmp/ros/include and type in bash source ~/catkin_ws/devel/setup.bash.
It works until container was relaunched.

**Comment by natashadsouza** [comment]
@gladijos were you able to resolve your issue?

**Comment by lemonriver** [comment]
How to make python script works with customized msg ? @natashadsouza

**Comment by quning18** [comment]
Closed for now, Please reopen if anyone has updates on this thread
