### ISSUE TITLE
Are you planning to update a docker image of canary version in DockerHub?

### ISSUE THREAD

**Issue by poutyface** [ApolloAuto/apollo#4929]
I use Canary version docker script.
Docker image tag does not seem to be updated.

**Comment by xiaoxq** [comment]
Yep. I paused that updating for a while, but keep updating the build scripts, so you can still build your own image from scratch. The canary version may become official along with next Apollo release.

**Comment by poutyface** [comment]
Thank you for your reply.
That's good news 👍
