### ISSUE TITLE
Dreamview ：ERROR （spawn error）

### ISSUE THREAD

**Issue by ZK-Zhou** [ApolloAuto/apollo#4932]
hello, I change the source code from apollo2.5 to 3.0. Everything is ok before the HMI. but there is an error as follow:
zk_zhou@in_dev_docker:/apollo$ sudo bash scripts/bootstrap.sh 
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: ERROR (spawn error)

watting for help;Thanks  #:)

**Comment by ZK-Zhou** [comment]
I didnot install apollo kernel. I install apollo 3.0 directly.

**Comment by siyangy** [comment]
There was a bug that could cause this introduced by a recent commit, but it should be fixed now. Can you try pulling the last and see if it persists?

**Comment by LunaAmour** [comment]
I have encountered this same issue, and pulling the latest commits does not seem to provide a fix. Thanks for any help.

**Comment by siyangy** [comment]
Looks like the problem has been resolved, closing.

**Comment by CCodie** [comment]
@LunaAmour , @siyangy 
I also met the same problem. Are there any related issues? Please give me some further guide.
My Apollo environment : Ubuntu 16.04 with apollo-kernel installed , cuDNN installed, nvidia-driver-version(375.39) installed inside & outside docker
```
apollo@in_dev_docker:/apollo$ bash scripts/bootstrap.sh 
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: ERROR (spawn error)

```
Thanks...

**Comment by LunaAmour** [comment]
@CCodie In my case I was running on a new system and had not realized I hadn't yet built the Apollo code on that system. Have you run `bash apollo.sh build`? Is the build successful?

**Comment by siyangy** [comment]
@CCodie You can take a look at https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md for common problems that could cause this.

**Comment by CCodie** [comment]
@LunaAmour @siyangy 
Thank you for the reply! It was occurred in the build process.
I installed Apollo system again and now I solved the problem.
