### ISSUE TITLE
Node graph 

### ISSUE THREAD

**Issue by Zoltan3057** [ApolloAuto/apollo#4933]
Hi.
Where can I find the nodes/topics graph of apollo.
For example, if I want to use cameras which differ from the default ones, I need to connect cameras' topics to the apollo system. But how can I determine the relations between cameras' topics and other modules of apollo. Any suggestions? Thanks.

**Comment by jinghaomiao** [comment]
As long as your publish your message in the same format defined in traffic light proto in the same topic, you should be fine.  Please refer to https://github.com/ApolloAuto/apollo/blob/master/modules/common/adapters/adapter_gflags.cc for all the topic names.

**Comment by Zoltan3057** [comment]
@jinghaomiao 

Thanks for your reply.

My meaning is that how can I determine which node subscribeds which topics. Do you have a comprehensive graph which shows the connections between every nodes and topics. What I need is similar to Autoware manuals, pages 11-16. I know maybe I ask too much, but I think a graph likes this will helps a lot to everyone. 

https://github.com/CPFL/Autoware-Manuals/blob/master/en/Autoware_UsersManual_v1.1.pdf

**Comment by osaman88** [comment]
As you can see from the Autoware manuals, there is a disclaimer that that these graphs need to be updated, so I would not rely on them anyway. 

I think you can easily get the info you need by using simple ROS queries. If you wish, you can then parse the output using a script and create a dot graph or other form to view it graphically. E.g.

osama@in_dev_docker:/apollo$ rosnode info /control
Node [/control]
Publications: 
 * /rosout [rosgraph_msgs/Log]
 * /apollo/monitor [pb_msgs/MonitorMessage]
 * /apollo/control [pb_msgs/ControlCommand]

Subscriptions: 
 * /apollo/planning [pb_msgs/ADCTrajectory]
 * /apollo/control/pad [pb_msgs/PadMessage]
 * /apollo/monitor [pb_msgs/MonitorMessage]
 * /apollo/canbus/chassis [pb_msgs/Chassis]
 * /apollo/localization/pose [pb_msgs/LocalizationEstimate]

Services: 
 * /control/get_loggers
 * /control/set_logger_level

and so on.

**Comment by Zoltan3057** [comment]
@osaman88 
Thanks, I will give it a try
