### ISSUE TITLE
Questions about hardware and installing

### ISSUE THREAD

**Issue by AshleyRoth** [ApolloAuto/apollo#4935]
Hello. I found your wonderful repository. In the process of reading the instructions, I had some questions. Could you please answer them? Thank you in advance:
1. IMU necessary? I do not have such a device unfortunately, can I work without it?
2. I have only vlp16, can I work with it? the instructions say about 64
3. should be two pc? PC with a powerful video card on the car and a regular PC in the office?
4. ESD CAN Driver. If I do not have a CAN card from ESD Electronics. And can i connect CAN to the computer in another way. In this case, what about the kernel? In instruction says about build with drivers from ESD. (i don't have CAN cart, it's real build with vector or something like?)
5. where is the apollo itself (mean https://github.com/ApolloAuto/apollo/) ? the kernel of the apollo is put on the PC which will be on the machine if I understood correctly, but himself apollo?

Thanks!

**Comment by YangHan101** [comment]
I will try to answer your questions to my best knowledge. I am sure your questions could apply to many developers.
1. Without IMU, the localization would depend on GPS system which only updates once per second. On top of that, you wouldn't have velocity and heading information of your vehicle. That is probably not a good idea unless you have other solutions. If you can solve the problem without it, I would love to learn more about your solution.
2. HDL64 provides a much denser point cloud than VLP-16 can. It gives a further detection range for obstacles. That is why we recommend it in the reference design. Whether VLP-16 works for your project, you will need to find out. We are not sure of your application scenario.
3. We only use one PC on the vehicle to handle all the calculations right now. 
4. You can, of course, explore the usage of other CAN interfaces. But then you will also need to handle the integration effort.
5. Apollo should be installed onto the PC in the vehicle. Apollo-kernel is just a RT patch on Ubuntu 14.04

**Comment by AshleyRoth** [comment]
@YangHan101 Thanks for your answers!
1. So i can use without IMU?
2. I know about the cloud of points, in 16 it will be less. Since now I have only 16 wanted to clarify, can I connect to the program 16?
4. I would like to know if I can connect CAN via vector or stm? What to advise if I do not have a card from esd?
5. If I use ubuntu 16.04 I also need to install apollo kernel?

**Comment by AshleyRoth** [comment]
@YangHan101 Hello again! In addition to the previous questions, I had another question. Can I connect to apollo using a CAN2USB device (for example, from Kvaser) CAN? I apologize for the huge number of questions and will be waiting for answers from you soon! Thanks in advance!

**Comment by YangHan101** [comment]
Hi @AshleyRoth,
The answer to the 2nd batch of questions:
1. I wouldn't recommend that. But you can try to look up possible solutions in the literatures. I am sure someone did some research on it.
2. The VLP-16 driver is included in the Apollo platform and it should work. 
3. Other CAN interface devices should work as well if you can set up the drivers correctly. But I personally don't recommend USB-CAN devices. They are good for diagnostics. But if you want to have a reliable connection, you should try other connectors than USB.
4. We have not tested 16.04 extensively. Perhaps use 14.04? If you want to try 16.04 out of curiosity, I am very interested whether that would work for you.
5. From my humble knowledge of the code, I believe the CAN clients and CANClientFactory are here. https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/canbus/can_client
under the folders with brand names. You will need to make a new folder and implement your own driver inside. @jinghaomiao please correct me if I am giving out wrong information.

**Comment by AshleyRoth** [comment]
@YangHan101 

I am very grateful to your detailed response. now I decided to install apollo on my laptop, because the laptop is more suitable for system requirements. I turn back to the same question about CAN, I have a device from Kvaser (https://www.kvaser.com/product/kvaser-leaf-light-hs-v2/) can I use it as a device to create a connection between my laptop and car? Can you give an answer to this question? At the moment, it's a little difficult for me to ask questions about CAN

Once again, thank you very much for your answers.

**Comment by YangHan101** [comment]
We used Kvaser's USB can interface for CAN diagnostics before. But I am not sure how to use it under Ubuntu.

**Comment by AshleyRoth** [comment]
@YangHan101 In this case, what can you advise? As I said, I'll try on a laptop, how can I connect CAN? I have stm and vector, I already wrote about them. but I want to clarify again, can I connect them with their help?

**Comment by YangHan101** [comment]
Do you have the model number of your device? I can have a look at the data sheet.

**Comment by YangHan101** [comment]
I assume you have modified your car with something like [this](http://dataspeedinc.com/wp-content/uploads/2016/11/adas-kit.pdf) for the vehicle control, right?

**Comment by AshleyRoth** [comment]
Hello

 Thank you so much! let me clarify, did I understand correctly, specifically kvaser equipment without problems will allow connecting CAN if adjusted?

**Comment by YangHan101** [comment]
1. Kvaser CAN interface, I believe so. But you'll have to test it. My experience with it is limited.
2. GNSS, that is correct.

**Comment by AshleyRoth** [comment]
@YangHan101 Thanks for answers!

I tried adding a new CAN device as written in the instructions. I took the following steps:
1. create file example_can_client.cc using the code from step 1 and put in folder "apollo/modules/drivers/canbus/can_client"
2. make step 2 and step 3

![conff](https://user-images.githubusercontent.com/37982453/42987163-f5d36712-8c00-11e8-9c5f-50fdf1668300.png)
got this message
![conf](https://user-images.githubusercontent.com/37982453/42987167-f8edc2a8-8c00-11e8-87f5-914435d23c70.png)

Can you help me please? I think I'm doing something wrong

**Comment by AshleyRoth** [comment]
@Capri2014 @YangHan101 
Hello, again! 
Does apollo support these PCI CAN cards:
- https://esd.eu/en/products/can-pci402
- https://www.peak-system.com/PCAN-PCI.207.0.html?&L=1

Will wait for your answer. Early thanks

**Comment by YangHan101** [comment]
Please check the official website for supported hardware.
http://apollo.auto/platform/hardware.html

**Comment by YangHan101** [comment]
Closing the ticket. Feel free to reopen if you have more questions
