### ISSUE TITLE
Navigation mode usage

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#4937]
Hello apollo team!
I need start apollo algorithms and launch my own in apollo's sandbox. Also I need send simulated data from outside apollo docker container.
I follow [https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode.md](url). While doing step2 (2. Collect navigation line raw data) of manual I sent simulated positions and orientations from my simulation workspace throw custom localization module. I fill only positions and orientations of vehicle.
I face a problem. I don't see navigation lines on main window. The car stand at (0,0). Planning horizon and point on map are moving.
![screenshot from 2018-07-11 16-56-26](https://user-images.githubusercontent.com/28844865/42567901-ffea52ea-8513-11e8-9c34-057ecfc030a2.png)
I think that I need feel more data when I store data to bag.

**Comment by yifeijiang** [comment]
You need to fill the heading information too in your localization data. Some modules that depend on localization use heading instead of orientation.

**Comment by gladijos** [comment]
@yifeijiang Thx a lot, I'll try it soon

**Comment by gladijos** [comment]
@yifeijiang Thx a lot, I feel position, orientation and heading information of localization/pose by my own localization module that's work instead of apollo's localization module. Also I see this information in dreamview backend inside function calling UpdateWithLatestObserved("Localization", AdapterManager::GetLocalization()), auto_driving_car is setted correctly with my generated position. But it isn't work.
May be I need to fill some other information, or send positioning data corresponded with HDMap information? I mean in dreamview by default one HDMap file is loaded and it includes coordinates. May be I have to generate coordinates near base HDMap coordinates.

**Comment by gladijos** [comment]
It works on Standard Dreamview mode, but still does not work in Navigation mode. I think virtual car behavior in Dreamview should be equal in this to modes if I send equal localization information.

**Comment by natashadsouza** [comment]
@gladijos I see that the issue was resolved at #5372 please feel free to reopen if you have any additional questions.
