### ISSUE TITLE
Map not showing up in Dreamview

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#4938]
Hi Guys,

I just created a new map using .xml (for testing purpose My_Map.xml) and followed the below procedure given in apollo github to generate dependent files.

routing_map has the topology of the lanes in base_map. It can be generated by command:
         ```
          dir_name=modules/map/data/demo # example map directory
         ./scripts/generate_routing_topo_graph.sh --map_dir ${dir_name}
          ```

sim_map is a light weight version of base_map for dreamview visualization. It has reduced data density for better runtime performance. It can be generated by command:
           ```
            dir_name=modules/map/data/demo # example map directory
            bazel-bin/modules/map/tools/sim_map_generator --map_dir=${dir_name} --output_dir=${dir_name}
            ```

Previously I had some 2 maps which I was selecting to test the behavior of the car.

But after generating the new map I am not able to see other maps. Seems like only the new map is working now. If I select the remaining maps it is showing blank.

Could anybody please help me to fix this issue.

**Update**
I did not perform the 3 steps mentioned in the sub heading **Use a different map**
Is this mandatory ? 

Thank you,
KK

**Comment by mickeyouyou** [comment]
what's the name of your map  in directory `modules/map/data/`?

**Comment by kk2491** [comment]
I created a new folder "My_Map" inside /apollo/modules/map/data directory. And updated the script path for routing_map and sim_map generation.

**Comment by kk2491** [comment]
@mickeyouyou Could you please let me know how can I revert back the changes ?

**Comment by mickeyouyou** [comment]
“Previously I had some 2 maps which I was selecting to test the behavior of the car.”
1. what are these two maps？

**Comment by kk2491** [comment]
@mickeyouyou  .. Default ones Sunnywale_big_loop and sunnywale_loop ...

**Comment by kk2491** [comment]
@mickeyouyou  Yes. I have restarted my system as well. I am not able to understand what went wrong.

**Comment by mickeyouyou** [comment]
Could `tail` the directory`/apollo/data/log` and different level log  find some errors ? 
like :
```bash
tail -f /apollo/data/log/*
```

**Comment by kk2491** [comment]
There are many errors actually. I grep the given command with Error

```
E0704 15:53:58.972952  1824 navigator.cc:86] Error encountered when reading request point!
E0704 14:48:45.412448  1696 apollo_app.cc:69] routing Start failed: ROUTING_ERROR: Navigator not ready
```

And many more.

**Comment by kk2491** [comment]
@mickeyouyou .. I was able to fix the issue by regenerating the bin files for the older map files. However it would be great if I can find the cause for the issue.
