### ISSUE TITLE
EM dp_road_graph

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#4943]
Hi,
This is what I understand about EM.
EM planner generates bundle trajectory and then calculate the cost of each trajectory, and then select the best trajectory by calculating the trajectory cost. After that EM generate the speed profile for that trajectory.
My question is: in trajectory_cost.cc I saw you use some SpeedData to calculate the cost with Dynamic Obstacle.
Base on my understanding, at this step, EM does not generate speed profile yet, so where SpeedData come from? 

Thank you.

**Comment by Ivesss** [comment]
From the last cycle, remember this is a iteratively planning
