### ISSUE TITLE
Apollo Perception - How to include the CIPV subnode in DAG

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#4946]
I want to include the CIPV subnode.  apollo/modules/perception/obstacle/onboard/cipv_subnode.cc

None of the config files here  seem to include the CIPV subnode as an option. apollo/modules/perception/conf/

**Comment by snuffysasa** [comment]
I started trying to make my own config file: 
/apollo/modules/perception/conf/dag_camera_obstacle_cipv_lane_vis.config

# Nvidia Driver on host is required for this config
subnode_config {
    #Camera node. publish pb with non-zero int
    subnodes {
        id: 3
        name : "CameraProcessSubnode"
        type : SUBNODE_IN
    }

    #Lane Post Processing node
    subnodes {
        id: 5
        name: "LanePostProcessingSubnode"
        reserve : "device_id:camera;publish:2;"
        type: SUBNODE_NORMAL
    }

    #CIPV node
    subnodes {
        id: 99
        name: "CIPVSubnode"
        type: SUBNODE_NORMAL
    }

    #Visualization node
    subnodes {
        id: 41
        name : "VisualizationSubnode"
        reserve : "vis_driven_event_id:1010;camera_event_id:1008;lane_event_id:1010"
    }
}

################################################################## #
#Define all edges which link nodes.
edge_config {
    # CameraDetectorSubnode -> LanePostProcessingSubnode
    edges {
        id: 106
        from_node: 3
        to_node: 5
        events {
            id: 1004
            name: "lane_postprocessing"
        }
    }

    #CameraProcessSubnode->VisualizationSubnode
    edges {
        id: 108
        from_node : 3
        to_node : 41
        events {
            id: 1008
            name : "camera_visualization"
        }
    }

    # LanePostProcessingSubnode -> VisualizationSubnode
    edges {
        id: 109
        from_node: 5
        to_node: 41
        events {
            id: 1010
            name: "lane_visualization"
        }
    }

    #CameraProcessSubnode-> CIPV
    edges {
        id: 110
        from_node : 3
        to_node : 99
        events {
            id: 1099
            name : "cipv_processing"
        }
    }

}

#Shared Data
data_config {
    datas {
        id: 5
        name : "CameraObjectData"
    }
    datas {
        id: 8
        name: "LaneSharedData"
    }
    datas {
        id: 7
        name : "CameraSharedData"
    }
    datas {
	id: 9
	name: "CIPVObjectData"
    }
}



I get this error: cipv_subnode.cc:77] Failed to parse reserve string:

Which makes sense, I have not added an include string.  
I do not know what I am supposed to put for reserve string for cipv subnode, none of the examples show that node.

**Comment by snuffysasa** [comment]
``# Nvidia Driver on host is required for this config
subnode_config {
    #Camera node. publish pb with non-zero int
    subnodes {
        id: 3
        name : "CameraProcessSubnode"
        type : SUBNODE_IN
    }

    #Lane Post Processing node
    subnodes {
        id: 5
        name: "LanePostProcessingSubnode"
        reserve : "device_id:camera;publish:2;"
        type: SUBNODE_NORMAL
    }

    #CIPV node
    subnodes {
        id: 99
        name: "CIPVSubnode"
        type: SUBNODE_NORMAL
	reserve : "camera_event_id:1099;lane_event_id:1100"
    }

    #Visualization node
    subnodes {
        id: 41
        name : "VisualizationSubnode"
        reserve : "vis_driven_event_id:1010;camera_event_id:1008;lane_event_id:1010"
    }
}

################################################################## #
#Define all edges which link nodes.
edge_config {
    # CameraDetectorSubnode -> LanePostProcessingSubnode
    edges {
        id: 106
        from_node: 3
        to_node: 5
        events {
            id: 1004
            name: "lane_postprocessing"
        }
    }

    #CameraProcessSubnode->VisualizationSubnode
    edges {
        id: 108
        from_node : 3
        to_node : 41
        events {
            id: 1008
            name : "camera_visualization"
        }
    }

    # LanePostProcessingSubnode -> VisualizationSubnode
    edges {
        id: 109
        from_node: 5
        to_node: 41
        events {
            id: 1010
            name: "lane_visualization"
        }
    }

    #CameraProcessSubnode-> CIPV
    edges {
        id: 110
        from_node : 3
        to_node : 99
        events {
            id: 1099
            name : "cipv_object_processing"
        }
    }

    #LanePostProcessingSubnode-> CIPV
    edges {
        id: 111
        from_node : 5
        to_node : 99
        events {
            id: 1100
            name : "cipv_lane_processing"
        }
    }

}

#Shared Data
data_config {
    datas {
        id: 5
        name : "CameraObjectData"
    }
    datas {
        id: 8
        name: "LaneSharedData"
    }
    datas {
        id: 7
        name : "CameraSharedData"
    }
    datas {
	id: 9
	name: "CIPVObjectData"
    }
}

**Comment by snuffysasa** [comment]
[dag_camera_obstacle_lane_motion_vis.txt](https://github.com/ApolloAuto/apollo/files/2186485/dag_camera_obstacle_lane_motion_vis.txt)

**Comment by techoe** [comment]
Now CIPV is called at fusion_subnode. We are still keeping cipv_subnode in case we don't use fusion_subnode but we may remove cipv_subnode to reduce such confusion.

**Comment by snuffysasa** [comment]
Excellent thank you.

I am just wondering what else is the fusion mode responsible for, when the only input is camera ? (Obstacles/lanes)

**Comment by snuffysasa** [comment]
I tired creating a DAG with camera, lanes, fusion, and w and w/o visualization... but with no radar.

And I have not been able to get this to work.  No errors to debug, the program just seems to hang / stall.

Is there a way to run, camera, obstacles/lanes, and fusion/cipv, but without radar?

**Comment by techoe** [comment]
The module need a radar. To run w/o radar, you have to manually remove all code related to radar.

**Comment by techoe** [comment]
I am closing it since there is no update after last answer.
