### ISSUE TITLE
Minimal output to be published by the planning module for the control to work

### ISSUE THREAD

**Issue by gulshan216** [ApolloAuto/apollo#4947]
Hi, I am working on implementing my own version of the Lattice Planner in Apollo.
I am confused about what minimal data fields in the ADCTrajectory message needs to set by the Planning module for the control to work. Are just the x,y points not enough?

I want to start off first with implementing simple plans, like moving at a constant speed, moving at a constant speed in the center of the lane, following the vehicle in front and then move on towards my final implementation.

**Comment by lianglia-apollo** [comment]
Control will need a list of (x, y t) points to follow.

**Comment by gulshan216** [comment]
Thanks for clarifying this.
