### ISSUE TITLE
Visualizing Build With Bazel

### ISSUE THREAD

**Issue by willsiriusAD** [ApolloAuto/apollo#4950]
I am trying to show the build structure using bazel query command under directory /apollo with the following command:

`sudo bazel query --noimplicit_deps 'deps(//modules/perception)' --output graph`

The error that I got:

`/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/external/gtest/BUILD.bazel:56:1: no such package '@com_google_absl//absl/types': The repository could not be resolved and referenced by '@gtest//:gtest'`
`ERROR: Evaluation of query "deps(//modules/perception)" failed: errors were encountered while computing transitive closure`

**Comment by natashadsouza** [comment]
@willsiriusAD were you able to resolve this issue. Unfortunately it is a third party issue which we are not sure how to resolve. Your help will be appreciated.
