### ISSUE TITLE
Run Offline Perception Visualizer

### ISSUE THREAD

**Issue by Zoltan3057** [ApolloAuto/apollo#4960]
Hi,

When I run the offline perception visualizer, I successfully got the pop-up window. But it seems that it cannot recognize obstacles. Any suggestions? Thanks. 
![screenshot from 2018-07-12 15-41-46](https://user-images.githubusercontent.com/37650678/42619372-7318fd6c-85ea-11e8-9e7c-199587737d4b.png)
![screenshot from 2018-07-12 15-42-08](https://user-images.githubusercontent.com/37650678/42619370-729a1858-85ea-11e8-9ff4-f9f31df783a4.png)

**Comment by techoe** [comment]
It seems lidar was not processed. Please debug where it cannot go thru.

**Comment by techoe** [comment]
I am closing it since there is no update after last answer.
