### ISSUE TITLE
Calibration from IMU to vehicle

### ISSUE THREAD

**Issue by Blanksan3** [ApolloAuto/apollo#4961]
When I took a calibration from IMU to vehicle, the terminal displayed "Begin to calibration..." and "Drive speed must greater than 2m/s for at least 10s". And when I finished the calibration according to the requirement and press 'Ctrl + C' to exit, there is nothing in the .yaml file which only displayed "#ieout imu_vehicle_calibration.ieout". Please help solve this issue. Thanks.

**Comment by xiaoxq** [comment]
Please check https://apollo.auto/ for our cloud service of calibration.

**Comment by wf1024966** [comment]
> When I took a calibration from IMU to vehicle, the terminal displayed "Begin to calibration..." and "Drive speed must greater than 2m/s for at least 10s". And when I finished the calibration according to the requirement and press 'Ctrl + C' to exit, there is nothing in the .yaml file which only displayed "#ieout imu_vehicle_calibration.ieout". Please help solve this issue. Thanks.

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by wf1024966** [comment]
> Please check https://apollo.auto/ for our cloud service of calibration.

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!
