### ISSUE TITLE
How planning module decide emergency stop or not?

### ISSUE THREAD

**Issue by levuphuong** [ApolloAuto/apollo#4964]
Hi

I have a check in modules/planning/planning.cc
And I see it will publish planning topic with PublishPlanningPb(&estop, start_timestamp); in some emergency cases.
But I don't know how planning make decision for estop reason or not.
Can anyone tell me how to reproduce that case?

Thank you.

**Comment by jmtao** [comment]
@levuphuong Hope the information answered your question. If you have any follow up question, please leave a comment below. If we did not hear back from you in 72 hours, we will close the issue and we encourage you to open a new issue if you have any more questions. 

Thank you for supporting Apollo!
