### ISSUE TITLE
Bug maybe? In modules/map/hdmap/hdmap_common.cc

### ISSUE THREAD

**Issue by Grayhu07** [ApolloAuto/apollo#4971]
In hdmap_common.cc line 52 to 62, this is a function to check whether a point is valid or not, 

> `bool IsPointValid(const PointENU &point) {
  /* if (point.x() > kMaxXCoordinate || point.x() < kMinXCoordinate) {
    return false;
  }
  if (point.y() > kMaxYCoordinate || point.y() < kMinYCoordinate) {
    return false;
  } */
  return true;
}
`

But I found that the function only return true( since all the check have been commented) and there are other functions using it. Is this a bug or it is intended to be this way? It confuses me a little bit.

**Comment by changsh726** [comment]
Thank you for reporting the issue. This function has been removed in #12409, and thanks again for your support for Apollo!
