### ISSUE TITLE
imu类型在配置文件中修改了，但是不起作用，是怎么回事？

### ISSUE THREAD

**Issue by alorli** [ApolloAuto/apollo#4972]
我简单描述以下使用的环境：使用的apollo3.0：dev版本，惯导是诺瓦泰pp7-e1，里面集成了EPSON-G320N的imu，串口，ntrip，imu类型等相关信息都在modules/calibration/data/<vehicle>/gnss_params/gnss_conf.pb.txt做了修改，惯导能输出差分定位信息，并显示在dreamview上。
1. imu_type:G320N，在modules/calibration/data/<vehicle>/gnss_params/gnss_conf.pb.txt修改了，但是没有在程序里用到，程序里面用的还是星网宇达的cpt_xw5651，下面截图是gnss.log信息：
![493345657](https://user-images.githubusercontent.com/15199599/42670959-5b0f37f8-8690-11e8-9331-9aa9de8b9d61.jpg)
2. 下面这个是惯导输出的/Apollo/sensor/gnss/imu消息，加表信息也是不对的：
![390818577](https://user-images.githubusercontent.com/15199599/42670993-766cb638-8690-11e8-9626-85ecc6e27de5.jpg)
3. 我把modules/drivers/gnss/parse/novatel_messages.h的549行对应的CPT_XW5651的sacle信息换成了G320N的信息，如下面截图所示：
![1625765093](https://user-images.githubusercontent.com/15199599/42671130-23b6e07a-8691-11e8-96f8-ed33d3272b7a.jpg)
4. 然后再看惯导输出的/Apollo/sensor/gnss/imu消息，加表信息就是对的了：
![1981388667](https://user-images.githubusercontent.com/15199599/42671329-0b7d87a6-8692-11e8-97c4-d04d3eede81e.jpg)

**Comment by hillbrook** [comment]
找到原因了，虽然在配置文件里面配置了imu的类型，但是在 driver 里面依然是根据NovAtel里面识别到的imu类型来获取的参数，如下
```
bool NovatelParser::HandleRawImuX(const novatel::RawImuX* imu) {
  if (imu->imu_error != 0) {
    AWARN << "IMU error. Status: " << std::hex << std::showbase
          << imu->imuStatus;
  }
  if (is_zero(gyro_scale_)) {
    config::ImuType imu_type = static_cast<config::ImuType>(imu->imu_type);
```
我们修改一下，统一按照配置的imu类型来获取imu的参数。多谢指出，

**Comment by alorli** [comment]
更改过来了，谢谢！
