### ISSUE TITLE
Question about ASU (Apollo Sensor Unit)

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#4975]
Hi Apollo Team.

In Apollo 3.0, the new hardware ASU(Apollo Sensor Unit) is added. And I have some questions about ASU.

Q1. When developers use ASU, is there a change in data(sensor data from LiDAR, Camera, ...) flow or data format ? If so, can I see the code about it ?
Because it is for specific developers only, not included in open source ..?

Q2. Does ASU send Control Command to actuators ?
> The communication between the ASU and the IPC is through PCI Express Interface. ASU collects sensor data and passes to IPC via PCI Express Interface, and the IPC uses the ASU to send out Vehicle Control commands in the Controller Area Network (CAN) protocol.

With the contents written on the page 'Apollo Sensor Unit Guide', ASU seems to not only collect data from sensors, but also send control commands to actuators. Is it right?
If so, IPC also have CAN port and why IPC does not send control commands directly ?

Thanks !

**Comment by YangHan101** [comment]
Hi,
I will try to answer your questions.
1. When ASU is designed, we intended to provide a unified data format to the computing unit eventually. At the current stage, it is not yet fully functional. You can expect the same kind of data format as before. NOTE that the USB cameras have been replaced by FPD-link cameras. The needed driver changes have been made in the camera drivers. So you can use it almost the same as before. 
2. Yes. The sensor box has a built-in CAN interface. So it can send and receive with the messages from vehicle CAN bus. If you have the sensor box, CAN card is not necessary anymore, unless you need more than 4 CAN connections.

**Comment by YangHan101** [comment]
I'm gonna close for now. Feel free to reopen if you have further questions.
