### ISSUE TITLE
How to communicate with own simulator

### ISSUE THREAD

**Issue by alexbuyval** [ApolloAuto/apollo#4976]
Hi Apollo Community,

I need an advice. I have got an own simulator based on Unity. This simulator uses standard ROS messages to communicate with other software. Now I am trying to integrate this simulator with apollo stack.

Since the apollo uses protobuf messages for some ROS topic I need to convert them. So I am looking for the best way how to implement it.

I see two ways now.

The first is to implement a separate module which will be a bridge between apollo messages and standard ROS messages.

The second is to add new adapters and corresponded callbacks into existed modules. 

What is best way? Maybe there are some examples similar communication already?

Best,
Alex

**Comment by gladijos** [comment]
You can follow my way. [https://github.com/ApolloAuto/apollo/issues/4892](url)
If you have to throw a little amount of ROS messages I think you do it same way.
In general best solution I think will be writing extra adapters because you will avoid extra copying.

**Comment by alexbuyval** [comment]
@gladijos Thanks for advice!

**Comment by GeorgeMD** [comment]
@gladijos the link you provided is broken. I would like to see your way if it's possible.

**Comment by jimaldon** [comment]
@gladijos That link no longer exists

**Comment by natashadsouza** [comment]
Here is the updated link: https://github.com/ApolloAuto/apollo/issues/4892

**Comment by jimaldon** [comment]
Thanks @natashadsouza!

**Comment by jimaldon** [comment]
Oops, the URL was just missing the issue number. Thanks @natashadsouza

**Comment by natashadsouza** [comment]
Closing this issue currently. Feel free to reopen if you have additional questions.
Thank you!
