### ISSUE TITLE
unix:///tmp/supervisor.sock refused connection

### ISSUE THREAD

**Issue by youluexx** [ApolloAuto/apollo#4986]
When I run the command 'sh scripts/bootstrap.sh', I got the result 'unix:///tmp/supervisor.sock refused connection'
```
xxxx@in_dev_docker:/apollo$ ./scripts/bootstrap.sh 
Started supervisord with dev conf
Start roscore...
voice_detector: started
unix:///tmp/supervisor.sock refused connection
```
I tried to config the '/etc/superviser.conf' or '/apollo/modules/tools/supervisord/dev.conf', but it did't work.

Does anyone get the same problem?

**Comment by songhanchen** [comment]
https://github.com/ApolloAuto/apollo/issues?utf8=%E2%9C%93&q=refused+connection

if not help, try:
1: exit the docker and dev_into again, ensure the user and group of /home/tmp/ros/* to be your docker user.  then bootstrap.
2: use `roscore` instead of bootstrap, perhaps need sudo. No dreamview support

**Comment by youluexx** [comment]
@songhanchen Thank you for reply. I solved the problem in an imperfect way. I thought it might be caused by permission, thus I changed the supervisor.sock path from '/tmp/' to '/apollo/tmp' in the file '/apollo/modules/tools/supervisor/dev.conf' and '/etc/supervisor.conf'. It really worked. 
I don't know why this happened. I added the user to the docker group. I will make sure about it.
Is there anything else which might cause the problem?

**Comment by xiaoxq** [comment]
Supervisor is not a good way for development. In recent change (https://github.com/ApolloAuto/apollo/commit/67fad1f572b3f1973b695af5bab093546ee7fa0d), I have removed it from debugging mode.
However, if you are using Apollo for some production scenarios, Supervisor could provide a second chance to recover the modules, which makes the more robust. Pass "--prod_mode" when starting dreamview for such use case.
