### ISSUE TITLE
Predicton::Common::validication_Checker.cc::validationchecker::ProbabilityByCentripedalAcceleration

### ISSUE THREAD

**Issue by chunyanmao** [ApolloAuto/apollo#4987]
`double ValidationChecker::ProbabilityByCentripedalAcceleration(

    const LaneSequence& lane_sequence, const double speed) {

  double centripetal_acc_cost_sum = 0.0;

  double centripetal_acc_cost_sqr_sum = 0.0;

  for (int i = 0; i < lane_sequence.path_point_size(); ++i) {

    const PathPoint& path_point = lane_sequence.path_point(i);

    double centripetal_acc = speed * speed *path_point.kappa(); 

    double centripetal_acc_cost =

        centripetal_acc / FLAGS_centripedal_acc_threshold;

    centripetal_acc_cost_sum += centripetal_acc_cost;

    centripetal_acc_cost_sqr_sum += centripetal_acc_cost * centripetal_acc_cost;

  }

  double mean_cost = centripetal_acc_cost_sqr_sum /

                     (centripetal_acc_cost_sum + FLAGS_double_precision);

  return std::exp(-FLAGS_centripetal_acc_coeff * mean_cost);

}'
Q: 1,Could you give me an specific explanation about the motion of this code,like the physical or math meaning?I hope you can use chinese if you like.

**Comment by kk2491** [comment]
Even I am looking for the explanation on this bit of programming.

Thank you,
KK

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
