### ISSUE TITLE
为什么每次运行指令＂bash docker/scripts/dev_start.sh -C＂时，硬盘存储会少１~2Ｇ？

### ISSUE THREAD

**Issue by zjuhitljx** [ApolloAuto/apollo#4989]
//谢谢解答

**Comment by willsiriusAD** [comment]
同问

**Comment by linpanusst** [comment]
您好，你不能每次dev_start.sh，这样每次都重新加载下载安装一次docker下的apollo，也就是说你运行一次安装一次。每次进入apollo文件夹下，运行如下代码：
`docker ps -a`
你将会得到docker对应的ID
然后运行
`docker start DOCKER_ID`
然后运行
`bash docker/script/dev_into.sh`
建议去入门一下docker环境

**Comment by gengqx** [comment]
docker的分层文件存储方式导致了启动后一些tmp文件被存储下来，同时如果你更新了代码，images的version可能会更新，会重新下载一个新的images。可以执行
```
docker images
```
查看本地现有的images，删除无用的images
执行
```
docker volume prune
```
删除不必要的文件层。

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
