### ISSUE TITLE
Definition of "WatchVehicles"?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#4993]
Hi Apollo team,

There are WatchVehicles in  In `stop_sign.cc`.
Are these include stops in different directions (e.g. 4-way intersection) to the ego vehicle or the same stop sign (obstacles in front of ego vehicles)?

**Comment by jmtao** [comment]
@wckorealsh these are the queues, one per each stop sign related to the stop sign ADC is stopping for, to monitor the vehicles that has arrived ta stop sign before ADC does and therefore ADC shall wait for. 
More specifically, e.g. for 4-way stop signs at an intersection, there are stop sign A,B,C,D, and ADC is at stop sign A, we'll have 3 queues for stop sign B, C, D, monitoring vehicles at each stop sign respectively. 

Hope the information answered your question. 
Thank you for supporting Apollo!

**Comment by wckorealsh** [comment]
@jmtao Thank you for the explanation, that is very helpful!
