### ISSUE TITLE
Where/what is the prediction module output?

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#4999]
What topics should the prediction module should be outputting?

I can see in prediction.cc it publishes prediction_obstacles, which appears to use the prediction_obstacle.proto.

But I am wondering where does the prediction module output the tracked lane information that would get sent to planning.  I see there is a schema for lane_graph.proto,  but I do not see anywhere this information is published from the prediction module.

**Comment by douqian** [comment]
Hi snuffysasa,
In prediction.cc, we can see prediction module publish prediction_obstacles like this "Publish(&prediction_obstacles)" and does't publish lane_graph.  lane_graph is used in evaluator.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @snuffysasa please reopen it if you have additional questions.
