### ISSUE TITLE
Conflict with hosting newest-version ROS?

### ISSUE THREAD

**Issue by Durant35** [ApolloAuto/apollo#50]
```sh
$ bash docker/scripts/dev_start.sh
ROS_DISTRO was set to 'kinetic' before. Please make sure that the environment does not mix paths from different distributions.
```
+ It seems that there is no ROS environment
![image](https://user-images.githubusercontent.com/6770853/27894548-623b843a-623f-11e7-85ae-3c9dc48271b9.png)

**Comment by startcode** [comment]
In the latest code,  ROS environment will be pulled and created when you start to build with command
`bash apollo.sh build`

**Comment by quning78** [comment]
in dev docker,  it won't be able to find the ros distribution installed outside docker. So the rosversion output is expected in your screenshot. As @startcode mentioned, with latest apollo code, you should be able to pull the ROS release package automatically during build process.

**Comment by quning78** [comment]
Close this one for now, please reopen it if you still have any questions.
