### ISSUE TITLE
release_start.sh error

### ISSUE THREAD

**Issue by cibon** [ApolloAuto/apollo#5004]
mac 10.11.6
elease-x86_64-v2.0.1: Pulling from apolloauto/apollo
Digest: sha256:4c77b79bbf8ecbcf9b07a5180d7eb1ca9eb4b0f0984d7b61db597887e12f26fe
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:release-x86_64-v2.0.1
Not on Linux, skip mapping devices.
c12ffbf5f923429ddf02b9686e75e5139fb57f408a1d2442494da4202aa4ad70
docker: Error response from daemon: Mounts denied: 
The path /etc/localtime
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
Error response from daemon: Container c12ffbf5f923429ddf02b9686e75e5139fb57f408a1d2442494da4202aa4ad70 is not running

**Comment by cibon** [comment]
if I remove "-v /etc/localtime:/etc/localtime:ro \" from release_start.sh
localhost:apollo admin$ bash docker/scripts/release_start.sh
Password:
tee: /proc/sys/kernel/core_pattern: No such file or directory
/apollo/data/core/core_%e.%p
Type 'y' or 'Y' to pull docker image from China mirror or any other key from US mirror.
y
release-x86_64-v2.0.1: Pulling from apolloauto/apollo
Digest: sha256:4c77b79bbf8ecbcf9b07a5180d7eb1ca9eb4b0f0984d7b61db597887e12f26fe
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:release-x86_64-v2.0.1
Not on Linux, skip mapping devices.
588fe0ef123dc6ce68a79ed0ba84d41f2d92de2aa8da23f9f39f4f7ce984a706
addgroup: The group `staff' already exists.
Adding user `admin' ...
Adding new user `admin' (501) with group `dialout' ...
The home directory `/home/admin' already exists.  Not copying from `/etc/skel'.

/apollo/ros/setup.bash: line 7: /dev/null: Permission denied
/apollo/ros/setup.bash: line 8: /setup.sh: No such file or directory
Start roscore...
/apollo/scripts/bootstrap.sh: line 28: /dev/null: Permission denied
Started supervisord with release conf
/apollo/scripts/bootstrap.sh: line 36: /dev/null: Permission denied
/apollo/scripts/bootstrap.sh: line 37: /dev/null: Permission denied
Dreamview is running at http://localhost:8888

but I can not get Dreamview in my chrome

**Comment by cibon** [comment]
build failure 
./apollo.sh build_no_perception dbg
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
[INFO] Skip building perception module!
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1366 targets (12 packages loaded).
INFO: Found 1366 targets...
ERROR: /apollo/modules/dreamview/backend/simulation_world/BUILD:5:1: C++ compilation of rule '//modules/dreamview/backend/simulation_world:simulation_world_service' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 3020.909s, Critical Path: 882.18s
FAILED: Build did NOT complete successfully
============================
[ERROR] Build failed!
[INFO] Took 3054 seconds
============================

**Comment by natashadsouza** [comment]
Please use "dev" container for all purposes. We are currently working on improving the Release container and will get back to you once it has been updated. The documents have also been updated in the Master branch with this change.

**Comment by 7chenko** [comment]
Is the above still the case? Use 'dev' container only? This page talks about the release container: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md

**Comment by natashadsouza** [comment]
@7chenko yes we do recommend that you continue to use "dev" docker for all purposes. The document includes steps to build Apollo and release binaries. Let me know if you have any additional questions. Thank you!
