### ISSUE TITLE
配置地址变成了服务器的内外ip

### ISSUE THREAD

**Issue by stoneLee81** [ApolloAuto/apollo#5009]
我现在的环境是，开发连接到腾讯的apollo dev配置服务器,在apollo-env.pro文件里面dev的配置如下：
dev.meta=http://dev.conf.xxxx.cn
当启动服务时，在打印里面发现连接的是云服务器的内外ip
http://172.16.16.6:8080/configs/2601/default/application?ip=192.168.2.41
但如果我用http://dev.conf.xxxx.cn/configs/2601/default/application?ip=192.168.2.41是可以访问的，请教下，这个是什么原因？

**Comment by JaredTan95** [comment]
I think you're asking the wrong question,You should go to [ctrip/apollo](https://github.com/ctripcorp/apollo).
