### ISSUE TITLE
why dreamview frontend interface isn't update when I change some code in local?

### ISSUE THREAD

**Issue by Yfling** [ApolloAuto/apollo#5013]
**current situation:**
docker has been installed 
Apollo normal operation

**my question:**
I want to modify the front-end code, but I don't know why there is no change in localhost:8888 after i change the code and restart the service.

**Comment by lesun90** [comment]
you need to re-complie dreamview front end
`#Install Dreamview front end dependent package. Note: you only need to execute it once, not every time.
cd /apollo/modules/dreamview/frontend/
yarn install
# Compile Dreamview front end
cd /apollo
bash apollo.sh build_fe`

https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode.md

**Comment by Yfling** [comment]
@lesun90  

does the docker need to be restarted after run `bash apollo.sh build_fe`  ?

there is a strange questions  that I modified the dreamview code locally and ran it, the app.bundle.js is update, but when I restarted docker, there was still no change in the front end.

**Comment by lesun90** [comment]
no need to restart docker.
You just need to clear the cache of browser after rebuild front end, use control-F5

**Comment by Yfling** [comment]
@lesun90 
It works!
It's my carelessness. Thank you for your patience so much!  ^_^

**Comment by Yfling** [comment]
@lesun90  

Sorry, I still have a question that has nothing to do with the issue.

**How can I debug front-end js code?**

Does the front-end js debug need to use gdb? I write `debugger` in this code, but it didn't work.
