### ISSUE TITLE
how do you define smoothness cost in trajectory.cc

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#5017]
Hi, 

I'm reading apollo's code for the planning module, however got stuck on figuring out how you properly define the trajectory cost, especially smoothness cost. could you share some academic paper to refer to? 

Thanks so much for your help, really appreciate it. 

Best

**Comment by muleisheng** [comment]
Here are two books I have learned, one is "Learning with Kernels: Support Vector Machines, Regularization, Optimization, and Beyond", the other is "kernel methods for pattern analysis".

Hope this would help you:)

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved. Thank you @muleisheng for your suggestions.
