### ISSUE TITLE
vector map conversion

### ISSUE THREAD

**Issue by SanduIrina** [ApolloAuto/apollo#5026]
Is there a way to convert a vector map from the carla simulator to apollo?

**Comment by natashadsouza** [comment]
@SanduIrina unfortunately this is not something we have tried at our end. If it worked out for you, we would love if you could share your experience with us.

**Comment by daohu527** [comment]
@SanduIrina Currently roadrunner supports opendrive to apollo, also there're other tools can do the same job.
