### ISSUE TITLE
What is the reference frame used while calculation of Yaw angle

### ISSUE THREAD

**Issue by gulshan216** [ApolloAuto/apollo#5032]
I would like to use the Yaw Angle information in the **Frame->vehicle_state** for my implementation in the planning module. I would like to know the reference frame used for calculating this and more specifically how does it relate to the global x-y position information in the **Frame->vehicle_state**.

**Comment by cmas1** [comment]
> The yaw angle is the angle in between car's longitudinal axis and the global x axis.

Is that so? My understanding is that the longitudinal direction of the vehicle is the y-axis (the Novatel frame of reference), so the yaw would be the angle between the longitudinal direction and the y-axis in the ENU frame (north). In other words, when the car is pointing north the yaw should be zero.

**Comment by apollodevcommunity** [comment]
The attitude angle   pitch angle   roll angle and yaw angle of the carrier are the azimuth angles of the carrier coordinate system relative to the navigation coordinate system.So  the reference system used in calculating. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=664
