### ISSUE TITLE
Trajectory stitching, why?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#5033]
Hi Team Apollo,

Can you please explain what is the purpose of stitching trajectories in planning?
Is stitching between lastly published trajectory and something else?
Thank you.

**Comment by lesun90** [comment]
You dont want the car change trajectory every time planner run -> car will change direction frequently
So you keep a portion of previous plan trajectory and stitch it to new trajectory.

**Comment by kk2491** [comment]
@lesun90 .. I have a similar query. Could you please let me know the length of generated trajectory ? Is it same as length of the car ?
Whenever I try print of the values for adc_sl_boundary end_s and start_s, I could see the difference which is approximately equal to the length of the car.

I would be glad, if you could clarify my doubt.

Thank you,
KK

**Comment by lianglia-apollo** [comment]
Trajectory is much longer than the length of the ego car.
