### ISSUE TITLE
关于高精地图制作，为什么无法申请合作权限

### ISSUE THREAD

**Issue by alorli** [ApolloAuto/apollo#5043]
有两个问题请求解答：
  1. 我现在使用诺瓦泰组合惯导+veloddyne16线激光能制作高精地图吗，需要注意什么。
  2. 我现在按照高精地图制作的文档录制了诺瓦泰组合惯导+veloddyne16线激光的bag数据，想使用百度的高精地图制作服务，但在数据权限申请那一步，有个加入我们的按钮是灰色的，点不了，请问是什么原因呢？
![1254751587](https://user-images.githubusercontent.com/15199599/42916249-dde062b0-8b36-11e8-951e-8592e3b03f1e.jpg)

**Comment by alorli** [comment]
![964942084](https://user-images.githubusercontent.com/15199599/42916284-0cd965a8-8b37-11e8-80fb-539bf06f2458.jpg)

**Comment by mickeyouyou** [comment]
本次的合作项目仅对境外开发者有限制的开放，按钮底下已经有提示说明的。

**Comment by alorli** [comment]
哦哦，是我理解错了，我理解的是仅对境外的开放有限制，对国内是完全开的呢，谢谢！
