### ISSUE TITLE
关于apollo3.0的RTK record and replay 功能

### ISSUE THREAD

**Issue by alorli** [ApolloAuto/apollo#5044]
我现在使用的是apollo3.0：dev版本，惯导是诺瓦泰pp7-e1，惯导能输出差分定位信息，并显示在dreamview上。在导航模式上上选择RTK record and replay模式，我的理解只要诺瓦泰能正确输出定位信息，录制轨迹和播放导航功能就是可以用的，但是当我准备录制轨迹时点record的start和stop都没有任何反映。这是什么问题呢，谢谢。
![327009074](https://user-images.githubusercontent.com/15199599/42916543-5fd434bc-8b38-11e8-8841-46cfc33a510f.jpg)
![288950423](https://user-images.githubusercontent.com/15199599/42916550-65061f72-8b38-11e8-9991-8cbdc5e487fd.jpg)

**Comment by diegohu** [comment]
It might be a bug of HMI, we are investigating on it. Thanks for open this issue.
