### ISSUE TITLE
关于相对地图制作过程中遇到的问题。

### ISSUE THREAD

**Issue by alorli** [ApolloAuto/apollo#5045]
1. 关于相对地图制作我参考的是apollo/docs/howto/how_to_use_apollo_2.5_navigation_mode_cn.md这篇文档。gps使用的诺瓦泰pp7-e1组合惯导，并且工作正常，参考线原始数据采集时，打开了GPS、Localization模块，并且都能正常输出信息，录制数据时。record bag 按钮启动不了，一打开就自动关闭，并且在/apollo/data/bag找不到对应的bag文件。
![835431089](https://user-images.githubusercontent.com/15199599/42917302-8ff78506-8b3b-11e8-8a95-ae000db56bdd.jpg)
2. 所以使用了手动录制方式，录制了/apollo/localization/pose和/apollo/sensor/gnss/odometry的bag，在执行提取裸数据的时候没报错，但在执行平滑的时候提示没有点，看一下数据文件和平滑文件，都没有数据。请问这是什么原因呢，录制的topic不对还是不够？
谢谢！

**Comment by hzdsdhr** [comment]
可以尝试使用脚本， 在scripts下record_bag.sh, 其中要记录的话题名可以修改脚本来配置。

**Comment by alorli** [comment]
1. rostopic echo /apollo/localization/pose 都有数据输出，修改了record_bag.sh, 在命令行中直接录制topic，可以录制出轨迹数据，使用extractor.py可以提取数据如下：
![658501813](https://user-images.githubusercontent.com/15199599/43765798-61f38b50-9a63-11e8-91c6-26b202c91ac9.jpg)
2. viewer_raw.py工具无法使用，提示找不到matplotlib包。
3.平滑工具也无法正常使用， bash smooth.sh ./path_2018-08-06-15-04-08_0.bag.txt 200，提示错误如下：
![6508176](https://user-images.githubusercontent.com/15199599/43765957-daea4df0-9a63-11e8-9596-654b807816e6.jpg)
4. 请问平滑后的文件格式是什么格式的，我能否不平滑直接，使用python navigator.py ./path_2018-08-06-15-04-08_0.bag.txt工具将参考线数据直接发布出去？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
