### ISSUE TITLE
关于组合惯导和velodyne16线激光外参的标定问题

### ISSUE THREAD

**Issue by alorli** [ApolloAuto/apollo#5046]
1. 组合惯导使用的是使用的apollo3.0：dev版本，惯导是诺瓦泰pp7-e1，激光使用的是velodyne16线激光，标定方法和标定工具参考的是apollo/docs/quickstart/multiple_lidar_gnss_calibration_guide_cn.md。由于没有64线激光，所以在配置文件中去掉了64线激光相应的部分。按照文档中的方法采集了bag数据，修改了yaml文件中的外参估计值，下面的图是标定过程中输出的点云拼接图，看图中显示的结果，标定结果十分不理想，请问可能是什么原因呢，标定过程需要注意什么问题呢
![2018-07-19 10-25-12](https://user-images.githubusercontent.com/15199599/42917888-0b2de358-8b3e-11e8-9f4f-fe6a303f64e7.png)

**Comment by xinwf** [comment]
你好，能问下你的点云拼接图是怎么得出来的吗，我也是Velodyne16激光雷达，也是按照这个教程，可是就是在最后一步无法得到输出结果，提示我[Too few clouds to optimize extrinsics](https://github.com/ApolloAuto/apollo/issues/5241)。

**Comment by xinwf** [comment]
如果方便的话，可以加下微信联系方式吗？

**Comment by homography** [comment]
Hi, you could first check the localization status, whether the GNSS is in RTK_FIX status and the ins solution is good. If it's ok, make sure the initial guess of the extrinsics is correct. For the default configuration, IMU coordinate frame is supposed to be Right-Forward-Up w.r.t the vehicle.

**Comment by JonathanJones92** [comment]
@alorli  标定前保证两点，1  /apollo/sensor/gnss/best_pose 中 各项derivations 小于0.02 要把车子驾驶到开阔地带进行标定
2. GPS状态 code 56 状态正常

**Comment by JonathanJones92** [comment]
@alorli  能够共享一下你们的calib tool 么，我看改了哪些参数，谢谢。 我的QQ 273575732 我们可以深入交流一下。

**Comment by xiaoxq** [comment]
Please check https://apollo.auto/ for our cloud service of calibration.

**Comment by pedestrain123** [comment]
> 1. 组合惯导使用的是使用的apollo3.0：dev版本，惯导是诺瓦泰pp7-e1，激光使用的是velodyne16线激光，标定方法和标定工具参考的是apollo/docs/quickstart/multiple_lidar_gnss_calibration_guide_cn.md。由于没有64线激光，所以在配置文件中去掉了64线激光相应的部分。按照文档中的方法采集了bag数据，修改了yaml文件中的外参估计值，下面的图是标定过程中输出的点云拼接图，看图中显示的结果，标定结果十分不理想，请问可能是什么原因呢，标定过程需要注意什么问题呢

您好可以加你QQ交流一下标定问题吗？2985782675
