### ISSUE TITLE
How to build and run 2 apollo versions in same machine?

### ISSUE THREAD

**Issue by levuphuong** [ApolloAuto/apollo#5051]
Hi,

I try to build apollo 3.0 and apollo 2.0 in same machine.
Problem is they share some working directories like /home/username/.cache or /usr/lib/. Then it will replace prior installation.

So could anyone have any suggestion to keep 2 installation apollo versions in the machine? Change docker name, container id or something.
Sorry I am newbie with docker environment.

Thank you.

**Comment by natashadsouza** [comment]
@levuphuong why would you like to build out both versions of Apollo within the same machine? If we understand your reasoning, we would be able to assist you better.

**Comment by levuphuong** [comment]
Because I have some customize apollo 2.0. In that time I also want to try apollo 3.0 to check what is new and what is different. 
Even if I create new ubuntu account user. But It still has come conflict. 
Thanks

**Comment by natashadsouza** [comment]
It is not currently possible to run two versions of Apollo on your system. I'd recommend testing Apollo 2.0 out and then install Apollo 3.0.
Please let me know if you have additional questions.
