### ISSUE TITLE
Why is bazel rebuilding whole project when I change one source file?

### ISSUE THREAD

**Issue by vladpaunescu** [ApolloAuto/apollo#5054]
Hello,

I changed a couple of lines in `/apollo/modules/dreamview/backend/handlers/image_handler.cc` to allow for RGB preview in dreamview. When I build with `./apollo.sh build_gpu` , bazel builds a lot of source files unrelated to the change.

![screenshot from 2018-07-19 12-51-26](https://user-images.githubusercontent.com/1523071/42935511-7c179d7a-8b52-11e8-9674-47f0962f1a28.png)

Many thanks,
Vlad

**Comment by siyangy** [comment]
So bazel relies on a lot of inputs (macros, env variables, etc) to decide whether it needs to recompile. In your case, if you did an `apollo.sh build` then `apollo.sh build_gpu`, bazel will have to recompile because in gpu mode there are some macros changed to allow the code to be run on GPU.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved. @vladpaunescu if you have additional questions, feel free to open it.
