### ISSUE TITLE
Question about adding new CAN

### ISSUE THREAD

**Issue by RushNuts** [ApolloAuto/apollo#5076]
Hello. Could you please explain how can I add a new CAN device? Specifically, 1 step in the instructions, I could not figure it out. Do I need to create a separate folder with the files or create a .cc file with the code from step 1 in the instructions in a folder. in step 1, is it necessary to supplement? Explain please how to add me correctly

Thanks!

**Comment by linpanusst** [comment]
I have the same problem. However I have a idea how to deal with it. It may help.
When we add a new can card. We do exactly as what the file in github says, except one thing they don't explain in detail, the .so files.  I think we can add  the .so files in the build files. I did that and it build successfully. But I didn't check out if the can was in apollo and if I can get data through this new can card.

**Comment by RushNuts** [comment]
@linpanusst hi! Thanks for your answer! and how do you connect CAN? I have in mind equipment

**Comment by AshleyRoth** [comment]
I am also interested in this issue. I think this question is relevant. Dear developers, please respond, help us

**Comment by linpanusst** [comment]
@RushNuts  
hi! I just successfully build in apollo. However, when I open the dreamview I can't see my hardware which should be a usbcan. 
I think that if it is possible to change the ESC_CAN parameters. So, I write the codes which is focus on  usbcan. I add the libcontrolcan.so(if you use another kind of cancard you need to download the .so files which match your card) in build files.
But in conclusion, I haven't successfully add a cancard in the condition that the dreamview can recognize it.
If you have any suggestion, contact me plz.

**Comment by RushNuts** [comment]
@linpanusst, hello! 
what usb can the device you use?
at the moment I stopped on the fact that I created a folder in the can_client directory in the same way as the esd folder, now I'm trying to figure out how to make my device apollo recognize

**Comment by gengqx** [comment]
@linpanusst ,you need to re implement the code in monitor about can hardware.

**Comment by AshleyRoth** [comment]
@gengqx Hello! Can you help me? With CAN connection. I have a lot of questions about the connection. unfortunately I only have USB2CAN devices Kvaser and PEAK. I'm having connection problems, I can not connect CAN .. (

**Comment by linpanusst** [comment]
@gengqx 
Hi, the suggestion you give is confused. Can you locate the code in files?

**Comment by jp12AI** [comment]
@linpanusst @RushNuts I'm using apollo 5.0. I have drivers for my can device. I'd like to use a USB can device. Have you had any success getting a USB CAN device working. It seems as if it is supported but I'm unsure of what to config besides config.txt file. Help on this would be great. Thank you

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
