### ISSUE TITLE
QP-Spline-Path Optimizer

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#5078]
Hi there, 

I have a question regarding to the QP-Spline-Path Optimizer. For each lane segment, we have 3 initial conditions and 3 end point conditions, which is enough to determine the coefficients of a 5th order polynomial, then how do we optimize our cost since the program is already over constrained? 

I understand that the smoothness constraints was used to smooth out the joint, however, it is essentially the same thing as the initial constraint for the following lane segment. I'm wondering why should we still bring up the smoothness joint constraint in this context? 

Thanks so much, I'm looking forward to your reply.

**Comment by waverider995** [comment]
Hi,

Only when you already know the exact value of the 3 initial + 3 end conditions, a 5d polynomial is determined. But here you only have the smooth condition: y0=y1, dy0=dy1... without knowing their value. You can use a qp-solver to find the exact value.

**Comment by yifeijiang** [comment]
@yangydavid  Hope the answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
