### ISSUE TITLE
how to engage autonomous mode?

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#5092]
Hi Team Apollo,

Always appreciated your comments on here.
I am wondering how you actually engage autonomous mode.
I was thinking of following steps, please correct me if I am wrong.

1. Run perception/canbus/localization modules(+others) as needed.
2. Give it a route (the first point of routing should be where the vehicle is currently).
3.  run planning module -> trajectory will be visualized in dream view
4. Set gear in "D"
5. Run control module.
6. Press "Start Auto" button in Dream view 
7. The vehicle should start to move.

Thank you!

**Comment by douqian** [comment]
Please reference this quick start doc:
https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_3_0_quick_start.md

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @wckorealsh if you are still unable to engage autonomous mode, please let us know.
