### ISSUE TITLE
Failed on compiling velodyne

### ISSUE THREAD

**Issue by VigiZhang** [ApolloAuto/apollo#5093]
New added blocking_queue.h has problem in `take` function argument `std::vector<T>* v` which will lead to error:
./modules/common/util/blocking_queue.h:98:8: error: member reference base type 'std::vector<T> *' is not a structure or union

**Comment by lianglia-apollo** [comment]
We fixed this issue at https://github.com/ApolloAuto/apollo/commit/f12c3891fe29479e530860b6c6304515c752fc80.
