### ISSUE TITLE
Questions in e2e.

### ISSUE THREAD

**Issue by linpanusst** [ApolloAuto/apollo#5094]
How can I use the e2e structure? 
I found that there is no algorithms in e2e. Does it mean that I have to write the algorithms by myself?
Is there any one have some experience in this field?
If you can give a demo to run, plz contact me.

**Comment by gengqx** [comment]
If you really need to run it,you could checkout to branch r1.5.0,that branch would have a demo code to run it.
But Why apollo team delete that code? I think it only a demo,you could not get more insight about it.
So, Don't waste your time.

**Comment by linpanusst** [comment]
hi, thanks for your reply.
what do you mean about r1.5? 
Does it mean that apollo 1.5 ?
you said some code was deleted, do you have any code about this?

**Comment by mickeyouyou** [comment]
You can find apollo e2e codes in here `https://github.com/ApolloAuto/apollo/tree/r1.5.0/modules/e2e`

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @linpanusst please let us know if you have any additional questions.
