### ISSUE TITLE
如何在Apollo 3.0開啟支援lidar的perception module

### ISSUE THREAD

**Issue by simon750324** [ApolloAuto/apollo#5095]
在apollo 2.5之後似乎都使用只有radar和camera的perception_low_cost的配置。
如果想使用只支援lidar的perception module，請問有現成的script嗎? 或是需要修改那些conf文件才能做到?

**Comment by mickeyouyou** [comment]
In fact, you only need to start the default `scripts/perception.sh` script, which loads the configuration `/modules/conf/perception.conf` file, which describes the nodes that are processed for the lidar topic.

**Comment by simon750324** [comment]
@mickeyouyou Thanks.
