### ISSUE TITLE
remote access to offline demo through hostname: 8887

### ISSUE THREAD

**Issue by DarrenWong** [ApolloAuto/apollo#51]
I have installed the apollo docker to one ubuntu machine and running the offline demo according to 
https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/README.md,
It might add `bash scripts/hmi.sh` before` rosbag play docs/demo_guide/demo.bag --loop` will work for me when i access to localhost:8887.

Can we remote access the system without considering the safety issue? Coz sometimes the team want to access the same machine to debug or somehow would be better before production env, thanks

**Comment by ycool** [comment]
Remote access HMI through hostname:8887 should work. What's the problem you met?

Thanks.

**Comment by DarrenWong** [comment]
I can use X windows to login localhost:8887, but seems cannot use hostname:8887 by others company in the internet. Is that my pc config instead of apollo docker's config?

**Comment by DarrenWong** [comment]
I mean use browser to login like 193.168.1.150:8887, it shows no response

**Comment by ycool** [comment]
apollo docker config doesn't apply this restriction. So I guess either is your pc config or your intranet router restricts some port range access. Can your local machine reach the server by `ping 192.168.1.150` ?

**Comment by DarrenWong** [comment]
okay，so might be the pc's config, I try again. thanks a lot
