### ISSUE TITLE
how to make some changes during using the azure simulation platform

### ISSUE THREAD

**Issue by lygincn** [ApolloAuto/apollo#5104]
Hi guys,

I have recently started to learn about the azure simulation platform. In the user guide is written, that the only thing I need to do is to upload my own .git data to the platform and run it. So I forked the apollo repository to my own and made some small changes then committed it. 

what i have done is:
1.changed the vehicle parameters (length and width) in vehicle_param.pb.txt

vehicle_param {
  front_edge_to_center: 3.89
  back_edge_to_center: 1.043
  left_edge_to_center: 1.055
  right_edge_to_center: 1.055

  length: 10 #changed 
  width: 6 #changed
  height: 1.48
  min_turn_radius: 5.05386147161
  max_acceleration: 2.0
  max_deceleration: -6.0
  max_steer_angle: 8.20304748437
  max_steer_angle_rate: 6.98131700798
  steer_ratio: 16
  wheel_base: 2.8448
  wheel_rolling_radius: 0.335
}
2. committed changes
3. give the URL of my repository in the simulation platform and ran the simulation

and after several times of changing, I noticed that the simulation results are all the same.(by observing the replay video of the simulation result) So I start wondering is this enough just doing the steps above? what I except is like the size changing of the blue car in the simulation and something like that. But nothing happens. Or what I have done has actually no affects on the simulation? If so, what should I do to make some difference?

I know what I am asking is very primary question, because I am pretty new about apollo. So any suggestions and thoughts are very much appreciated. Thank you!

**Comment by vlin17** [comment]
@lygincn thanks for trying out the simulation platform. 

Regarding the change of vehicle size, it certainly affects the calculation in other modules. For visualization, the ego-car size on Dreamview is fixed to the default (the Lincoln MKZ car) so far. We can certainly make code changes to reflect the defined vehicle size. 

The platform does not simulate the perception module at the moment, so there's no need to calibrate the sensor parameters.

**Comment by apollodevcommunity** [comment]
Maybe you can change the speed limit in planning.conf:--planning_upper_speed_limit=2--default_cruise_speed=1to see if the speed changed. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=661
