### ISSUE TITLE
The missing declaration of "use_navigation_mode" in third_party_perception_flags.h causes the module build failure.

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#5120]
The modules/third_party_perception/conversion.cc has references to FLAGS_use_navigation_mode but it is neither declared or defined in modules/third_party_perception/common/third_party_perception_flags.h/third_party_perception_flags.cc. After adding the declaration and definition, the module can be built successfully.

**Comment by mickeyouyou** [comment]
Thanks so much for mention that , could you pull a request

**Comment by lianglia-apollo** [comment]
We will revert the change as this flag has already been defined in other places. Please build apollo as a whole rather than building a single module.

**Comment by jilinzhou** [comment]
Agreed. I just noticed it is defined in the global flag config file and it does make sense.
