### ISSUE TITLE
rtk correction signal?

### ISSUE THREAD

**Issue by STX321** [ApolloAuto/apollo#5131]
Dear Apollo:
     Apollo can use rtk+gps+imu to realize precise positioning, but I don't know where Apollo obtain the rtk correction signal, what's the principle of Apollo uses rtk?   
    Thank you!

**Comment by gengqx** [comment]
the gnss conf file would have rtk_from and rtk_to,then we can use ntrip method to obtain rtk signal

**Comment by lygincn** [comment]
I'm also wondering about this. As my understanding, the correction signal is from base stations. So how apollo get the access to the base station signal? How does the whole thing work?

**Comment by daohu527** [comment]
> So how apollo get the access to the base station signal?

Use network, you can ref to rtk conf in `modules/drivers/gnss/conf/gnss_conf.pb.txt`
