### ISSUE TITLE
Vehicle does not stop at the routing end point

### ISSUE THREAD

**Issue by gulshan216** [ApolloAuto/apollo#5137]
Hi,

I am using Apollo 2.5, when trying to add my own route and sending the routing request, but the vehicle does not seem to stop at the routing endpoint. In Dreamview it shows the vehicle keeps on going forward after the routing endpoint for a while and then shows the vehicle stopped at the routing endpoint itself. Seems weird. Can someone explain why?
Also which function in planning module handles this?

**Comment by douqian** [comment]
Hi gulshan,
Vehicle has its Inertia according to its speed and weight, so it isn't perfect control.
In planning, destination.cc, build pull-over decision upon arriving at destination,  
int Destination::PullOver(common::PointENU* const dest_point) {
  auto* planning_state = GetPlanningStatus()->mutable_planning_state();
  if (!planning_state->has_pull_over() ||
      !planning_state->pull_over().in_pull_over()) {
    planning_state->clear_pull_over();
    auto pull_over = planning_state->mutable_pull_over();
    pull_over->set_in_pull_over(true);
    pull_over->set_reason(PullOverStatus::DESTINATION);
    pull_over->set_status_set_time(Clock::NowInSeconds());

    if (dest_point) {
      pull_over->mutable_inlane_dest_point()->set_x(dest_point->x());
      pull_over->mutable_inlane_dest_point()->set_y(dest_point->y());
    }
  }

**Comment by gulshan216** [comment]
This function is not there in Apollo 2.5. It is only included in Apollo 3.0 i guess. So do you think i need to port this functionality from 3.0 or upgrade completely to 3.0 to get the desired functionality.

**Comment by gulshan216** [comment]
@douqian

**Comment by douqian** [comment]
Suggest you to upgrade the project to 3.0, because it includes the latest bug fix and new feature.

**Comment by gulshan216** [comment]
Yes updating to 3.0 solved the problem. Thanks!!
