### ISSUE TITLE
How to add a new point of interest permanently in the Dreamview interface

### ISSUE THREAD

**Issue by gulshan216** [ApolloAuto/apollo#5139]
Hi,

I am trying to add a new point of interest through the Route Editing panel available in Dreamview. I first select the start and end routing point and then click on "Add Point of Interest" but it just shows me the window for the already existing Points of Interest and need to select one of the existing ones.
What is the procedure to add a new point of interest? And also how to add it permanently so that i can reuse the same route whenever i want in the future.
Thanks in Advance.

**Comment by siyangy** [comment]
There's a default_end_way_point file for each map to specify point of interest, you can refer to: https://github.com/ApolloAuto/apollo/blob/master/modules/map/data/demo/default_end_way_point.txt.

**Comment by apollodevcommunity** [comment]
Hi Just need to select one end point and click \"send rouint request\" you can add permanent POI at modules/map/data/your_map/default_end_way_point.txt ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=658
