### ISSUE TITLE
How to enter the docker offline / with no network

### ISSUE THREAD

**Issue by jpkuta** [ApolloAuto/apollo#5150]
Could someone explain the steps I would need to take to be able to launch and enter the apollo docker offline. I would like to be able to enter the docker and perform tests without having an internet connection. Thanks very much!

**Comment by muleisheng** [comment]
you could reference following command:
sudo <Apollo dir>/docker/scripts/dev_start.sh -l <your local image>.

Hope this could help you:)

**Comment by zhxt** [comment]
Yeah, @muleisheng is right, there is an -l option to start docker locally. This may work well for early version,  for the latest version, the new added docker images are not handle the -l option, so some additional work need to be done to achieve this.

Simply, you may need to find all the 'docker pull' command(except the main docker, handled already) and comment it out in dev_start.sh and restart_map_volume.sh .

Hope it helps.

**Comment by jpkuta** [comment]
Thank you, the steps @zhxt  mentioned on commenting out the 'docker pull' commands in both dev_start.sh and restart_map_volume.sh has done the trick!

**Comment by gladijos** [comment]
I think you can use -l option but you have to fix /docker/scripts/dev_start.sh. You need to change name "local_dev" to existing docker image like dev-x86_64-20180702_1140
