### ISSUE TITLE
velodyne VLP-16激光雷达坐标系转换问题

### ISSUE THREAD

**Issue by XinWenfei** [ApolloAuto/apollo#5160]
系统是在docker中运行的，雷达和GPS已经连在一起了，运行之后报如下错误，这个错误是在canTransform中报的错误，坐标系转换失败，打印出的child_frame_id是velodyne16，我在另外一个终端手动发布了一个空白的转换后，Error info就变了，缺少什么信息，所以问题应该是激光雷达没有发布自己的坐标系，而且奇怪的是，也没有世界坐标系，这个错误应该怎么解决呢，我在gnss模块中看到有个单独的tf文件夹去实现坐标系发布，那velodyne雷达是不是也需要这些东西，如果需要的话，是要自己实现吗？
（velodyne的问题很多，建议开个velodyne的标签）
![2018-07-28 15-01-05](https://user-images.githubusercontent.com/14092833/43354532-90bd88b8-9280-11e8-90e0-542456e91a35.png)
运行出错的代码位置
![2018-07-28 16-04-27](https://user-images.githubusercontent.com/14092833/43354547-c2df577c-9280-11e8-8271-d18cb7bb62c5.png)
未发布转换前
![default](https://user-images.githubusercontent.com/14092833/43354619-5a0f9e62-9282-11e8-9a7c-2b6a73794bc3.png)
发布转换后
![default](https://user-images.githubusercontent.com/14092833/43354621-6153c842-9282-11e8-93bc-0657474f1abd.png)

**Comment by XinWenfei** [comment]
这个在另外一个机器上运行是没有问题的，看来不是坐标系转换的问题

**Comment by carlin314** [comment]
I find the same problem, have you figure out what is going on?

**Comment by carlin314** [comment]
[ WARN] [1534328321.423415020, 1534269296.698309739]: Can not find transform. 1534238407.364357 Error info: Lookup would require extrapolation into the past.  Requested time 1534238407.364357471 but the earliest data is at time 1534240500.599999905, when looking up transform from frame [velodyne16] to frame [map].

**Comment by xinwf** [comment]
@carlin314 , it is the time problem, you should use a unified time from GPS

**Comment by carlin314** [comment]
Thx,dude, but I have sync the gps with lidar and check this in the web, but the velodyne driver from apollo just not work. 

And I check the topic header, /apollo/sensor/velodyne16/PointCloud2/header ,it's different from the gps time.
![image](https://user-images.githubusercontent.com/16414165/44198696-a87f6680-a174-11e8-8a68-c36f1da52939.png)

What's more, I run the velodyne official driver, the lidar time is exactly same with gps time, so I conclude that the apollo vlp-16 have a bug?

Do you have some ideas?

**Comment by carlin314** [comment]
And I open an issue here,https://github.com/ApolloAuto/apollo/issues/5360

**Comment by carlin314** [comment]
@XinWenfei

**Comment by carlin314** [comment]
@xinwf

**Comment by carlin314** [comment]
Any update in this @xinwf

**Comment by xinwf** [comment]
We haven't met this problem any more.
