### ISSUE TITLE
steer_single_direction_max_degree_ in mpc_controller.cc

### ISSUE THREAD

**Issue by turinglife** [ApolloAuto/apollo#5165]
in mpc_controller.cc, #88 line.

  steer_single_direction_max_degree_ =
      vehicle_param_.max_steer_angle() / steer_transmission_ratio_ / 180 * M_PI;

I was wondering whether the formulation is wrong. Since the unit of vehicle_param_.max_steer_angle() is rad, so we should use *180/M_PI instead of 180 * M_PI.

Thanks.

@Capri2014

**Comment by Capri2014** [comment]
@turinglife thanks for pointing this out and you are right.

**Comment by Capri2014** [comment]
fix created via https://github.com/ApolloAuto/apollo/pull/5167 @turinglife

**Comment by turinglife** [comment]
Maybe, we also need to remove term of steer_transmission_ratio_ in the formula. 

steer_single_direction_max_degree_ = vehicle_param_.max_steer_angle() * 180 / M_PI;

@Capri2014

**Comment by Capri2014** [comment]
@turinglife Yep, it is slightly modified.

**Comment by Zhenni17** [comment]
Closed as the issue seems to be fixed.
