### ISSUE TITLE
How can we perform responsible disclosure about security problems with Apollo

### ISSUE THREAD

**Issue by analyzerav** [ApolloAuto/apollo#5177]
Hi Apollo developers, is there any channel (e.g., email, website) for us to report security problems or attacks on Apollo? Could you let us know how to perform such responsible disclosure in Apollo? Thanks.

**Comment by mickeyouyou** [comment]
Hi @analyzerav 
if you have some security problems you can send mail to our security team by email or website.

**Email**
You can report security problems to our security team apollo-anquan@baidu.com, they will make a professional response.

**Security Website**
http://apollo.auto/platform/security_cn.html

**Comment by analyzerav** [comment]
@mickeyouyou Thanks for your information!
