### ISSUE TITLE
Cannot use map.yield.add

### ISSUE THREAD

**Issue by SanduIrina** [ApolloAuto/apollo#5182]
Hello there, I'm working in python on creating my own map and when I try to add generate the sim map with /bazel-bin/modules/map/tools/sim_map_generator it downsamples way too much. Is there a way to change the downsampling factor? I only saw the binary file and couldn't find the script itself

**Comment by muleisheng** [comment]
You could refer the source code in apollo/modules/map/tools/sim_map_generator.cc. Hope this could help you:)

**Comment by SanduIrina** [comment]
Thanks, I found it in the end. For some reason I was only looking for .py files....

**Comment by Zhenni17** [comment]
Closing as the issue seems to be fixed.
