### ISSUE TITLE
Eigen alignment problem

### ISSUE THREAD

**Issue by MonkeyTang** [ApolloAuto/apollo#5210]
Why we can't see EIGEN_MAKE_ALIGNED_OPERATOR_NEW in Apollo code.
this MARCO from https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html.
In other words: you have a class that has as a member a fixed-size vectorizable Eigen object, and then you dynamically create an object of that class.

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
