### ISSUE TITLE
Clarification needed - traffic_decider change_lane.cc 

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5211]
Hi Guys,

I have been going through different traffic_decider tasks. 

Given below is the condition checked in change_lane.cc line number 57.

```
if (path_obstacle->PerceptionSLBoundary().end_s() <
        adc_sl_boundary.start_s() -
            std::max(config_.change_lane().min_overtake_distance(),
                     obstacle->Speed() * min_overtake_time)) {
      overtake_obstacles_.push_back(path_obstacle);
    }
```

Lets consider max(config_.change_lane().min_overtake_distance(), obstacle->Speed() * min_overtake_time)) is config_.change_lane().min_overtake_distance() which is 10 m.

In the idea case, condition has to check if the obstacle is in front of ADC and has min overtake distance. But as per the condition it is checking if the obstacle is behind the ADC as shown in the below pictorial representation.

![image](https://user-images.githubusercontent.com/38481564/43588436-204b91a2-968a-11e8-82cb-c465b8f47d1a.png)

Could you please provide clarity on this and also please correct me if my understanding is wrong.

Thank you,
KK

**Comment by kk2491** [comment]
Hi Guys,

Anybody had looked into this ?

Thank you,
Kishor

**Comment by kk2491** [comment]
@weidezhang @techoe Did you guys get chance to look at this.?

**Comment by kk2491** [comment]
@weidezhang @techoe Did you guys get chance to look at the issue ? 
adc_sl_boundary is with respect to the ego vehicle or with respect to the car?
]

**Comment by kk2491** [comment]
@weidezhang @techoe requesting you to kindly clarify my doubt...

**Comment by kk2491** [comment]
@natashadsouza Could you please help me with this.

**Comment by kk2491** [comment]
@chasingw Thanks for the response. I have drawn the above representation after going through the code. So as per the code in overtake case the obstacle would be behind ADC. In ideal case if ADC has to perform overtake behavior, obstacle should be in front of ADC.

**Comment by chasingw** [comment]
I think this overtake not mean adc want to perform overtake behavior, But when ego want to change lane, we should consider the obstacles that want to overtake the ego vehicle.The case you described is considered in the file [front_vehicle.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/toolkits/deciders/front_vehicle.cc)

**Comment by kk2491** [comment]
@chasingw Thanks for the clarification. Now this is much more clear to me.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen should you have additional questions. Thanks!
