### ISSUE TITLE
Confidence Values Not Showing up in Lane Post Processing

### ISSUE THREAD

**Issue by DevMMI** [ApolloAuto/apollo#5212]
Hello, I am trying to access lane confidence values from lane objects in the lane_post_processing_subnode, for some reason confidence values are all 0 while all other fields on the LaneObjects are filled with data. I am accessing lane objects from within the PublishPerceptionPb method in the LanePostProcessingSubnode. Can someone explain why confidence values are zero for all lanes?

**Comment by DevMohamedMI** [comment]
I see that in /perception/obstacle/camera/lane_post_process/common/type.h guys on line 244 - method ToLaneMarkerProto(), are assigning LaneMarker protobuf message to have a hardcoded quality of 1.0. With a comment '// set a constant quality value 1.0 as temporary use'. Does that indicate on Apollo 3.0 that confidence values for lanes have not been included?

**Comment by xiaoshuliu** [comment]
@DevMohamedMI You are right. Currently we are not using confidence for lane lines.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
