### ISSUE TITLE
ImportError: No module named em

### ISSUE THREAD

**Issue by drliebe** [ApolloAuto/apollo#5216]
After successfully running `./docker/scripts/dev_start.sh`, `./docker/scripts/dev_into.sh`, and `./scripts/apollo.sh build_gpu`, I attempted `./scripts/apollo.sh build_velodyne` ...
![build_error](https://user-images.githubusercontent.com/12840070/43608547-2f7a98fa-9656-11e8-9ced-07cd17be1b8e.png)
As you can see that did not work. I was using docker image dev-x86_64_20180702_1140.

If I change `./docker/scripts/dev_start.sh` to pull docker image dev-x86_64-20180629_1650 this problem goes away. (The problem is present if I use dev-x86_64-20180702_1030 or dev-x86_64-20180702_1140.)

Alternatively, instead of rolling back docker images, running `sudo pip install empy --upgrade` before I build_velodyne seems to fix the issue so far.

Any chance we can get this fixed and a new docker image released? I don't want to be running a 3-version obsolete docker image. I would also prefer not to have to remember to run `sudo pip install empy --upgrade` unless absolutely necessary.

**Comment by xiaoxq** [comment]
It's due to python version pollution by conda. Should have been fixed in latest code.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @drliebe feel free to reopen the same if you have additional questions.
