### ISSUE TITLE
Compute Distance Between Radar Object and Tarcked Radar Object (Probabilistic Fusion)

### ISSUE THREAD

**Issue by willsiriusAD** [ApolloAuto/apollo#5219]
In file '/modules/perception/obstacle/fusion/probabilistic_fusion/pdf_track_object_distance.cc',  in the 'float PbfTrackObjectDistance::Compute' function:

` 
     } else if (radar_object != nullptr) {
        distance = std::numeric_limits<float>::max();
        //    distance = compute_radar_radar(fused_object, sensor_object,
        //    *ref_point);
      }
`

I don't quite understand why the distance is set to max when comparing radar object with tracked radar object. Won't this cause big problem when calculating the association matrix? 

Thank you very much!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
