### ISSUE TITLE
Using History to Extend Lane in Perception disabled?

### ISSUE THREAD

**Issue by DevMMI** [ApolloAuto/apollo#5231]
Hello, I noticed that in modules/perception/obstacle/camera/lane_post_process/cc_lane_post_processor.h that the flag '#define USE_HISTORY_TO_EXTEND_LANE false' disables any extension of lanes by using history. After forcing this flag to be true, the module begins extending the lanes further. Is this feature disabled in 3.0? Will it be enabled in a future version of Apollo? Is there some stability issue with using extended lanes?

**Comment by xiaoshuliu** [comment]
@DevMohamedMI Hi, thank for your feedback. We just tested and updated the new model, so we disabled some features to see the single frame performance. It will be enabled in future version, and it should be more stable using extended lanes.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
