### ISSUE TITLE
callibrated is an error word

### ISSUE THREAD

**Issue by ttkk1024** [ApolloAuto/apollo#5239]
"Apollo 3.0 is loaded with new modules and features, but needs to be callibrated and configured perfectly before you take it for a spin. " the word "callibrated" should be changed "calibrated".

**Comment by lianglia-apollo** [comment]
Thanks! The fix is at https://github.com/ApolloAuto/apollo/commit/f25910f557162f9550f5b11d6cf03339dbe5e9b7
