### ISSUE TITLE
how do the vehicle parameters affect the planning algorithmus?

### ISSUE THREAD

**Issue by lygincn** [ApolloAuto/apollo#5240]
hi guys,

I have one basic question here, can anyone tell me if the vehicle parameters affect the performance of the planning module? 

vehicle_param {
  front_edge_to_center: 3.89
  back_edge_to_center: 1.043
  left_edge_to_center: 1.055
  right_edge_to_center: 1.055

  length: 4.933
  width: 2.11
  height: 1.48
  min_turn_radius: 5.05386147161
  max_acceleration: 2.0
  max_deceleration: -6.0
  max_steer_angle: 8.20304748437
  max_steer_angle_rate: 6.98131700798
  steer_ratio: 16
  wheel_base: 2.8448
  wheel_rolling_radius: 0.335
}

how are these parameters used during the whole process? thank you all.

**Comment by gladijos** [comment]
You are needed in general explanation or concrete connections to algorithm. In general there are dynamic limitations and dependencies that affect on planning and control. But I have no idea deeper, sorry :)
