### ISSUE TITLE
读取本地bag包cmakelist的相关配置问题

### ISSUE THREAD

**Issue by Renzhongchao111** [ApolloAuto/apollo#5243]
我用ros读取bag的时候，只需要在cmakelist里面的findpackge添加rosbag还有packagelist里面添加rosbag就可以了，但是apollo里面不行，需要怎么解决这个问题。

**Comment by chaii** [comment]
Are you trying to use rosbag play to read bag or you are trying to write a ros node to read rosbag inside apollo docker?

**Comment by storypku** [comment]
Stale issue closed.
