### ISSUE TITLE
How to enable Velodyne HDL-32E lidar in apollo 3.0.0?

### ISSUE THREAD

**Issue by simon750324** [ApolloAuto/apollo#5244]
I find the start_velodyne_hdl32e.launch in launch files and try to enable the velodyne lidar.
`roslaunch velodyne start_velodyne_hdl32e.launch`

After I launch the launch file, I got below error messages.

Log:
[ INFO] [1533541081.140923031]: Initializing nodelet with 8 worker threads.
[ INFO] [1533541081.164144151]: Loading nodelet /sensor_velodyne32_driver of type velodyne_driver/DriverNodelet to manager velodyne32_nodelet_manager with the following remappings:
[ INFO] [1533541081.187929096]: Velodyne driver nodelet init
[ERROR] [1533541081.192347935]: invalid model, must be 64E_S2|64E_S3S|64E_S3D_STRONGEST|64E_S3D_LAST|64E_S3D_DUAL|VLP16
[ INFO] [1533541081.198084189]: Loading nodelet /sensor_velodyne32_convert of type velodyne_pointcloud/ConvertNodelet to manager velodyne32_nodelet_manager with the following remappings:
[FATAL] [1533541081.201277832]: Failed to load nodelet '/sensor_velodyne32_driver` of type `velodyne_driver/DriverNodelet` to manager `velodyne32_nodelet_manager'
[FATAL] [1533541081.201770230]: Failed to load nodelet '/sensor_velodyne32_convert` of type `velodyne_pointcloud/ConvertNodelet` to manager `velodyne32_nodelet_manager'
[ INFO] [1533541081.232417625]: Loading nodelet /sensor_velodyne32_compensator of type velodyne_pointcloud/CompensatorNodelet to manager velodyne32_nodelet_manager with the following remappings:
[ INFO] [1533541081.234772212]: waitForService: Service [/velodyne32_nodelet_manager/load_nodelet] could not connect to host [in_dev_docker:43557], waiting...
[velodyne32_nodelet_manager-2] process has died [pid 13364, exit code -11, cmd /home/tmp/ros/lib/nodelet/nodelet manager __name:=velodyne32_nodelet_manager __log:=/home/sensor/.ros/log/a49d1f70-994b-11e8-9ffb-c07cd1fba006/velodyne32_nodelet_manager-2.log].
log file: /home/sensor/.ros/log/a49d1f70-994b-11e8-9ffb-c07cd1fba006/velodyne32_nodelet_manager-2*.log
[sensor_velodyne32_driver-3] process has died [pid 13368, exit code 255, cmd /home/tmp/ros/lib/nodelet/nodelet load velodyne_driver/DriverNodelet velodyne32_nodelet_manager __name:=sensor_velodyne32_driver __log:=/home/sensor/.ros/log/a49d1f70-994b-11e8-9ffb-c07cd1fba006/sensor_velodyne32_driver-3.log].
log file: /home/sensor/.ros/log/a49d1f70-994b-11e8-9ffb-c07cd1fba006/sensor_velodyne32_driver-3*.log
[sensor_velodyne32_convert-4] process has died [pid 13378, exit code 255, cmd /home/tmp/ros/lib/nodelet/nodelet load velodyne_pointcloud/ConvertNodelet velodyne32_nodelet_manager __name:=sensor_velodyne32_convert __log:=/home/sensor/.ros/log/a49d1f70-994b-11e8-9ffb-c07cd1fba006/sensor_velodyne32_convert-4.log].
log file: /home/sensor/.ros/log/a49d1f70-994b-11e8-9ffb-c07cd1fba006/sensor_velodyne32_convert-4*.log

How should I enable the velodyne hdl32e lidar?

**Comment by simon750324** [comment]
After I enter docker and build velodyne, the above errors are missing.
However it would keep showing below error message now.

log:
[ERROR] [1533543291.524296702]: NAV receiver warning, GPS info is invalid

**Comment by douqian** [comment]
From the description in http://apollo.auto/platform/hardware_cn.html, it seems Apollo doesn't support HDL-32E.  ULTRA Puck VLP-32C is supported in Apollo.

**Comment by simon750324** [comment]
@douqian 
But I find the launch for velodyne hdl-32e lidar in apollo 3.0. It is weird.

**Comment by YangHan101** [comment]
@simon750324 @douqian 
I just had a look at the code. Yes you are right, the current code can support hdl32e directly. However, with some changes, I am sure you can process VLP-32C data as well.
As you know, the data are sent over the ethernet cable with UDP protocol. For HDL32e and VLP32C the structure of the packages are the same. What is different is the calibration file will be different. I suggest to try modifying the calibration file and give it a try.
The changes when we added hdl32e support is [here](https://github.com/ApolloAuto/apollo/commit/df37d2c79129434fb90353950a65671278a4229e#diff-cb9767ab272f7dc5b3e0d870a324be51). This could be a good reference to you. Let me know if you have more questions.

**Comment by simon750324** [comment]
@YangHan101 
Yes, I connect the Garmin GPS receiver to the lidar. And I also setup below settings for HDL-32E lidar.

[PPS Qualifier]
Require GPS Receiver Valid: On
Require PPS Lock: On

[GPS Qualifire]
Require GPS Receiver Valid: On

But I still repeat getting the error logs(NAV receiver warning, GPS info is invalid!)

**Comment by YangHan101** [comment]
@simon750324 That error means Velodyne lidar is receiving the GPRMC signal but not the PPS. Please check the wiring and configuration.

**Comment by mickeyouyou** [comment]
Hi there. may this method would help you.

If version before 3.1 you need to re-compile the lidar driver like this `bash apollo.sh build_velodyne_vls128 ` that will replace the driver in ros share directory. then you can run the launch(`roslaunch velodyne_vls 32e_points.launch`) you HDL32E.

**Comment by SolarDriftSolutions** [comment]
Hi
I am using Apollo3.0.0 and I have re added all the velodyne 32 sections for the driver.

Also, checked that data packets are coming through outside of the docker container.

I then run the hdl32e launch file and get:
Velodyne port 8308 poll() timeout

socket_input.c file is set to connect ANY ip, is there something I need to tell the docker container to let it access that port?

Thanks
Paul
