### ISSUE TITLE
Bug in ObjectCameraFilter::Filter

### ISSUE THREAD

**Issue by csukuangfj** [ApolloAuto/apollo#5246]
See the code
https://github.com/ApolloAuto/apollo/blob/026e99d0792d08b2f2a135182ebf9f98b6ae42a1/modules/perception/obstacle/camera/filter/object_camera_filter.cc#L32-L34
https://github.com/ApolloAuto/apollo/blob/026e99d0792d08b2f2a135182ebf9f98b6ae42a1/modules/perception/obstacle/camera/filter/object_camera_filter.h#L71

`tracked_filters_` is never updated.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
