### ISSUE TITLE
[need help] "rosbag" is not found after building the software

### ISSUE THREAD

**Issue by ironsuperdev** [ApolloAuto/apollo#5257]
After building the apollo software in docker successfully, I ran 

`bash scripts/bootstrap.sh ` I can get dreamview in browser started. But if I insert 

```
root@in_dev_docker:/apollo# rosbag play demo_1.5.bag --loop
bash: rosbag: command not found
```
Did I do something wrong?  Thanks

**Comment by DongAi** [comment]
Hi,ironsuperdev. I am wondering why you are running container as a `root `user, that's not correct firstly. When execture `dev_start.sh` and `dev_into.sh`, do not add `sudo `parameter. The user in container should be the one that you use on your PC, pay attention to it. 
Below is a way to check where `rosbag `is.
Normally, `rosbag `is in directory `/home/tmp/ros/bin/`, this directory and `rosbag `truely exist without any doubts, but you system environment `PATH `may not contain `/home/tmp/ros/bin/` when running as root. Shift to normal user, check `PATH `again, it should container `/home/tmp/ros/bin/` and then that's right.

use `which rosbag` to see where it is.
use `echo $PATH` to show the value of `PATH`.

**Comment by zhxt** [comment]
There is a similar issue #4468 that may helpful.

PS：It would be a good practice to search existing issues before opening a new one :-)

**Comment by whuzxy** [comment]
@ironsuperdev before run ROSBAG,you should run "bash /apollo/scripts/apollo_base.sh“to add ros path.Then rosplay will be worked.Or you can "cd /home/tmp/ros/bin/",then you can find the executable file rosbag

**Comment by natashadsouza** [comment]
Closing this issue as it is similar to an existing issue. If you still have questions. Feel free to reopen this issue. Thanks!
