### ISSUE TITLE
Build the Apollo project in VSCode 

### ISSUE THREAD

**Issue by liangzcamg** [ApolloAuto/apollo#5259]
Use the keyboard shortcut (Ctrl+Shift+B) to build the Apollo project.

Failed to pull docker image.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/apollo_dev/json: dial unix /var/run/docker.sock: connect: permission denied

**Comment by gladijos** [comment]
You make smth with sudo or from su. But you shouldn't do that. 
I think you have to remove all containers and images  and also grant permissions or ownership of your apollo directory to your user.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response. Feel free to open it if you have additional questions.
