### ISSUE TITLE
Inconsistent format for serializing VisualObject to files

### ISSUE THREAD

**Issue by csukuangfj** [ApolloAuto/apollo#5264]
See the code for writing
https://github.com/ApolloAuto/apollo/blob/4f79a4fd0bf3551dda1eb262b5f539b25a1f6d40/modules/perception/obstacle/camera/common/util.cc#L100-L106

and the code for reading
https://github.com/ApolloAuto/apollo/blob/4f79a4fd0bf3551dda1eb262b5f539b25a1f6d40/modules/perception/obstacle/camera/common/util.cc#L68-L72

`trunc_height` and `trunc_width` are not written to the file but they are read from the file.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
