### ISSUE TITLE
关于相对地图制作

### ISSUE THREAD

**Issue by alorli** [ApolloAuto/apollo#5267]
rostopic echo /apollo/localization/pose 都有数据输出，修改了record_bag.sh, 在命令行中直接录制topic，可以录制出轨迹数据，使用extractor.py可以提取数据如下：
![658501813](https://user-images.githubusercontent.com/15199599/43767433-bc3b5170-9a67-11e8-84bb-ad379f3afed1.jpg)

viewer_raw.py工具无法使用，提示找不到matplotlib包。
3.平滑工具也无法正常使用， bash smooth.sh ./path_2018-08-06-15-04-08_0.bag.txt 200，提示错误如下：
![6508176](https://user-images.githubusercontent.com/15199599/43767438-bf84ed50-9a67-11e8-8f81-e2ebc96ed6a5.jpg)

请问平滑后的文件格式是什么格式的，我能否不平滑直接，使用python navigator.py ./path_2018-08-06-15-04-08_0.bag.txt工具将参考线数据直接发布出去？

**Comment by yifeijiang** [comment]
你先试试把extractor出来的数据中重复的数据过滤掉再试试。

**Comment by apollodevcommunity** [comment]
参考文档中这一部分方法:从原始数据包提取裸数据在Docker内部，使用如下命令从原始数据包提取裸数据：cd /apollo/modules/tools/navigatorpython extractor.py /apollo/data/bag/2018-04-01-09-58-00.bag上述命令会在当前目录（易知我们在/apollo/modules/tools/navigator目录中）生成一个提取后的裸数据文件：path_2018-04-01-09-58-00.bag.txt。为了验证裸数据的正确性，可以使用如下命令查看：python viewer_raw.py ./path_2018-04-01-09-58-00.bag.txt对裸数据进行平滑处理如果录制数据时，车辆行驶不够平顺，提取的裸轨迹数据可能会不光滑，有必要对其进行平滑处理。继续在Docker内部使用如下命令完成平滑处理：bash smooth.sh ./path_2018-04-01-09-58-00.bag.txt 200注意：上述命令中200是平滑处理的长度，该值一般为150-200，如果执行失败，可尝试调整该参数，再次进行平滑。为了验证平滑结果的正确性，可以使用如下命令查看：python viewer_smooth.py ./path_2018-04-01-09-58-00.bag.txt ./path_2018-04-01-09-58-00.bag.txt.smoothed其中，第一个参数./path_2018-04-01-09-58-00.bag.txt是裸数据，第二个参数./path_2018-04-01-09-58-00.bag.txt.smoothed是平滑结果。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=651
