### ISSUE TITLE
::adu::perception::OnlineCalibrationService  is not found

### ISSUE THREAD

**Issue by csukuangfj** [ApolloAuto/apollo#5268]
See the comment
https://github.com/ApolloAuto/apollo/blob/4f79a4fd0bf3551dda1eb262b5f539b25a1f6d40/modules/perception/obstacle/camera/cipv/cipv.h#L58

`::adu::perception::OnlineCalibrationService ` cannot be found.

Is `adu` short for apollo baidu ?

**Comment by techoe** [comment]
Thank you for the comment! WIll remove the line.
