### ISSUE TITLE
ObjectCameraExtendedKalmanFilter is not registered

### ISSUE THREAD

**Issue by csukuangfj** [ApolloAuto/apollo#5271]
See the file
https://github.com/ApolloAuto/apollo/blob/master/modules/perception/obstacle/camera/filter/object_camera_extended_kalman_filter.h

The following line
```.cpp
REGISTER_CAMERA_FILTER(ObjectCameraExtendedKalmanFilter);
```
is missing.

**Comment by csukuangfj** [comment]
In addition,

https://github.com/ApolloAuto/apollo/blob/4f79a4fd0bf3551dda1eb262b5f539b25a1f6d40/modules/perception/obstacle/camera/common/visual_object.h#L95-L96

is not set.

https://github.com/ApolloAuto/apollo/blob/4f79a4fd0bf3551dda1eb262b5f539b25a1f6d40/modules/perception/obstacle/camera/filter/object_camera_extended_kalman_filter.cc#L45-L47

The covariances for (x, v_x) and (y, v_y) are missing.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
