### ISSUE TITLE
misleading name ObjectCameraExtendedKalmanFilter::UpdateTransitionMatrix

### ISSUE THREAD

**Issue by csukuangfj** [ApolloAuto/apollo#5272]
See the code
https://github.com/ApolloAuto/apollo/blob/4f79a4fd0bf3551dda1eb262b5f539b25a1f6d40/modules/perception/obstacle/camera/filter/object_camera_extended_kalman_filter.cc#L174-L182

It simply computes a Jacobian matrix and should not be called a transition matrix.

**Comment by freshnewegg** [comment]
I agree, this is just the jacobian -> I propose to change it to 

"GetTransitionalModelJacobian" or "GetTransitionalUpdateMatrix"

I prefer the former. If agreed upon, I can do pr

**Comment by apollodevcommunity** [comment]
you shall concern about where the caller use the return value matrix.acturally   this function is not used now. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=649
