### ISSUE TITLE
Run all unit tests for the Apollo project in VSCode

### ISSUE THREAD

**Issue by liangzcamg** [ApolloAuto/apollo#5273]
Executed 4 out of 223 tests: 221 tests pass and 2 fail locally.
============================
[ERROR] Test failed!
[INFO] Took 6 seconds
============================

**Comment by kk2491** [comment]
@liangzcamg Can you try with this please.

https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md

This was updated in Apollo repository. 

Please check and let me know if you are able to fix the issue. I tried but in my case I was not able to fix the error.

Thank you,
KK

**Comment by liangzcamg** [comment]
@kk2491 我在Ubuntu16.04上弄过，遇到了这个问题，用您说的方法也没解决。但是这次是在ubuntu14.04上弄的，还是有这个问题

**Comment by natashadsouza** [comment]
Closing this issue as there has no communication in a while. Feel free to reopen it if the issue persists. Thanks!
