### ISSUE TITLE
How to add an obstacle in the based on the Demo?

### ISSUE THREAD

**Issue by fanghaos2014** [ApolloAuto/apollo#5274]
I want to add an obstacle based on the demo.My question is that I can not find the original data files or demo source code.They are all bag files. So how do I add an obstacle and let it show in the dreamview!
Thank you

**Comment by siyangy** [comment]
There are a few similar questions regarding to your requirement, like this: https://github.com/ApolloAuto/apollo/issues/4822. Feel free to check them out!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @fanghaos2014 feel free to reopen the same if you have additional questions. Thanks!
