### ISSUE TITLE
Where is the origin of the coordinates of the whole system?(整个系统的坐标原点在哪)

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#5275]
Is it fixed at the center of the rear wheel or is centered on the IMU‘s position？
是固定在后轮中心还是以IMU所在位置为原点？

**Comment by natashadsouza** [comment]
Hi @xinwf 
The origin is always at the centre of the rear axle of the vehicle. 
This document should help better explain it: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination.pdf
Let me know if you need additional information.

**Comment by xinwf** [comment]
Thank you for your reply. I have just read this document you mentioned. In the driverless car tested by Baidu, the origin of the coordinate system is indeed defined in the center of the rear axle. The initial step is to execute calibration from velodyne lidar to GNSS,  we need to set the offset matrix and rotation matrix of the lidar to the IMU (ie, inertial navigation) in velodyne external parameter configuration(`/apollo/modules/calibration/lidar_gnss_calibrator/conf/multi_lidar_gnss_calibrator_config.yaml`) when carrying out the final step of calibration( [calibration tutorial](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/multiple_lidar_gnss_calibration_guide.md)). And in the file `/apollo/modules/calibration/data/mkz8/vehicle_param.pb.txt`, it also sets the center of the car at the position where the IMU is placed.The coordinate data used later is also corrected_imu output from IMU device. It looks like that IMU is the origin of the whole system ,so I am thinking whether the coordinate origin of the entire system is defined by the location of the IMU? If according to your understand about the origin of the coordinate, it is always at the center of the rear axle, then, when I put the IMU in other positions of the vehicle, I need to carry out a transformation from the IMU's coordinate to the center of the rear axle(ie, the origin of the coordinate), am I right? Because this involves the control behaviors of the vehicle. Are you sure you are right about your understanding of the origin of the coordinate system? If you are or you are one employee working for Apollo, I need to do some coding work for this. I think Apollo shouldn't fix the origin of the coordinate to a specific place.

**Comment by techoe** [comment]
Yes, IMU should be installed at the center of rear axle. If you move the IMU to other place, please change the translation value of IMU to the moved position w.r.t. the center of rear axle.

**Comment by xinwf** [comment]
@techoe , ok, thank you. 
Is there a configuration file that I can modify by myself about the translation value of the IMU's moved position relative to the center of the rear axle, or I need to do this by myself in the code of the apollo project.
