### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by DrIncredible** [ApolloAuto/apollo#5279]
In file `st_boundary_mapper.cc`, in function `MapWithoutDecision`, for the static obstacle(obstacle with no trajectory from prediction moduel), first we retrieve the adc position `curr_point_on_path`, where there's an overlap between adc and obstacle by calling function `CheckOverlap`. Then we define two variables:

```
        const double backward_distance = -vehicle_param_.front_edge_to_center();
        const double forward_distance = vehicle_param_.length() + vehicle_param_.width() +obs_box.length() + obs_box.width();
```
But this seems makes no sense, `curr_point_on_path.s()+backward_distance` is twice the `front_edge_to_center` distance, while the width in the forward_distance makes no sense at all. Can anyone elaborate why do we do this, or is there any details I get wrong? Thanks!

**Comment by DrIncredible** [comment]
Anyone can tell me what is the current status for this issue?

**Comment by lianglia-apollo** [comment]
I think it is a rough estimate when the detailed numbers are not important.
