### ISSUE TITLE
NVIDIA Driver installation failed

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5290]
Hi guys,

I had an error in NVIDIA Driver Installation.

I'm installing Apollo 3.0 on Ubuntu 14.04.5 with NVIDIA GTX Titan Z, following the steps in [Software_and_Kernel_Installation_guide.md](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Software_and_Kernel_Installation_guide.md).

After I installed Apollo Kernel, I'm trying to install NVIDIA GPU Driver with below commands.
`wget http://us.download.nvidia.com/XFree86/Linux-x86_64/375.39/NVIDIA-Linux-x86_64-375.39.run`
`sudo bash ./NVIDIA-Linux-x86_64-375.39.run --no-x-check -a -s`

And then, this error occured. How can I fix it ?
![image](https://user-images.githubusercontent.com/37093857/43810851-b76411d6-9af4-11e8-94dc-4f8c193cc1cd.png)

My Linux info is
`4.4.32-apollo-2-RT #2 SMP PREEMPT RT Wed Sep 20 11:45:34 CST 2017 x86_64 x86_64 x86_64 GNU/Linux`.

Thanks!

**Comment by lianglia-apollo** [comment]
Yes, 14.04 has the infinite login error issue. We also had it when we were using 14.04. 
You can use 16.04 instead.

**Comment by wardenLL** [comment]
@CCodie  Hi, recently I also have infinite login error in Ubuntu14 after install the GPU dirvier with pre-install Apollo kernel. Do you have the solution right now? I really want to use Apollo with Ubuntu 14.
