### ISSUE TITLE
questions about add a new gpsreciever

### ISSUE THREAD

**Issue by ZK-Zhou** [ApolloAuto/apollo#5291]
Hi apolloers
   I use a domestic GPS reciever called DH7D10, and I followed the file "how_to_add_a_gps_receiver.md". But I saw that there is an another file : "moudles/drivers/gnss/parser/novatel_message.h". Should I write a file like this for my new hardware? What should I do for details?
 Thanks.

**Comment by gladijos** [comment]
You should add new folder in modules/drivers/gnss/src/impl directory with new files like DH7D10_parser.cpp and in modules/drivers/gnss/include - DH7D10_parser.h. Also I should modify some other source and config files, that noticed in md-file.

**Comment by natashadsouza** [comment]
Closing this issue as there has no communication in a while. Feel free to reopen it if the issue persists. Thanks!
