### ISSUE TITLE
RelativeMap warning in Standard Dreamview mode

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#5293]
I switch to Standard mode, where I cannot use RelativeMap module and 
I see message in Dreamview log: RelativeMap adapter has not received any data yet.

**Comment by siyangy** [comment]
Are you on the latest code? I just tried this but didn't see the warning log.

**Comment by siyangy** [comment]
yep, r3.0 has the fix.

**Comment by gladijos** [comment]
Thanks a lot @siyangy I can't right now switch to 3.0 and check this but I think issue can be closed
