### ISSUE TITLE
Apollo lowcost perception module requires localization?

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#5295]
Apollo: "Apollo 3.0 aims for Level-2 autonomous driving with low cost sensors. An autonomous vehicle will stay in the lane and keep a distance with a closest in-path vehicle (CIPV) using a single front-facing camera and a frontal radar. Apollo 3.0 supports high-speed autonomous driving on highway without any map"

This is clear.

However, in analyzing Apollo perception module, the motion service, which is necessary for simply Lane detection/tracking.. requires localization as an input, in order to get the vehicle velocity....

Angular velocity could come from IMU, and X lineal velocity could come from wheel speed.  However, no place to get lateral (Y) linear velocity.   This input is necessary for the lane tracking.

If one is suppose to get this data from the MSF localization with 64-line Lidar and an HD map.... than this directly contradicts "Level-2 autonomous driving with low cost sensors without any map".

**Comment by techoe** [comment]
Low cost solution will allow to drive a car w/ or w/o localization. Indeed, motion service is getting information from localization output. However, the information we use is only IMU output (yawrate and velocity) not a GPS output. Yawrate and velocity can be received from the EPS if your car supports it.
