### ISSUE TITLE
Someting wrong with ROS: modules/common/adapters/adapter_manager.cc

### ISSUE THREAD

**Issue by howtocodewang** [ApolloAuto/apollo#53]
When I run the command `bash apollo.sh build`, I have an ERROR.
`modules/prediction/main.cc:23: error: undefined reference to 'ros::init(int&, char**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
external/ros/include/ros/publisher.h:107: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
external/ros/include/ros/publisher.h:107: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
external/ros/include/ros/publisher.h:107: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
external/ros/include/ros/publisher.h:113: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
modules/common/adapters/adapter_manager.cc:48: error: undefined reference to 'ros::NodeHandle::NodeHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
`

So I think maybe ROS leads to this error, and I don't install ROS in my PC. What should I do? or Need I to install ROS and which version? 

Any help? Thanks!

**Comment by ycool** [comment]
Are you running `bash apollo.sh build` inside apollo dev docker image?  apollo.sh build will pull ROS dependency for you. So no need to install ROS by yourself. 

bash docker/scripts/install_docker.sh # if no docker installed before 
# logout and login to make sure to run docker command without sudo
docker ps  # to verify docker works without sudo
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash apollo.sh build # inside dev docker

**Comment by howtocodewang** [comment]
@ycool 

I have run this command but I still have this error.

This is my result.
`bash docker/scripts/dev_into.sh
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/apollo_dev/exec: dial unix /var/run/docker.sock: connect: permission denied`

Need I other command lines?

**Comment by ycool** [comment]
It looks like you have some problems about docker installment. 
Do you logout and login again after installing docker?

What's the output of `docker ps`?

**Comment by siyangy** [comment]
This seems to be a docker issue, make sure you have docker properly installed by checking something like docker info. A quick googling gave me this that might be a solution: https://github.com/moby/moby/issues/5314.

**Comment by howtocodewang** [comment]
@siyangy @ycool 
Thank you, guys! I have solved this error. I should reboot the computer.

However, there are still several errors during running the command `bash apollo.sh build`.
The output of `bash apollo.sh build`:
`ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:217:1: //bazel-apollo-master/external/bazel_tools/tools/android:poison_pill_android_sdk: missing value for mandatory attribute 'apkbuilder' in 'android_sdk' rule.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:217:1: //bazel-apollo-master/external/bazel_tools/tools/android:poison_pill_android_sdk: missing value for mandatory attribute 'jack' in 'android_sdk' rule.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:217:1: //bazel-apollo-master/external/bazel_tools/tools/android:poison_pill_android_sdk: missing value for mandatory attribute 'jill' in 'android_sdk' rule.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:250:1: name 'config_feature_flag' is not defined.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:256:1: //bazel-apollo-master/external/bazel_tools/tools/android:always_true: no such attribute 'flag_values' in 'config_setting' rule.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:256:1: //bazel-apollo-master/external/bazel_tools/tools/android:always_true: missing value for mandatory attribute 'values' in 'config_setting' rule.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:263:1: //bazel-apollo-master/external/bazel_tools/tools/android:always_false: no such attribute 'flag_values' in 'config_setting' rule.
ERROR: /apollo/bazel-apollo-master/external/bazel_tools/tools/android/BUILD:263:1: //bazel-apollo-master/external/bazel_tools/tools/android:always_false: missing value for mandatory attribute 'values' in 'config_setting' rule.
ERROR: error loading package 'bazel-apollo-master/external/bazel_tools/tools/build_defs/pkg': Extension file not found. Unable to load package for '//tools/build_defs/pkg:pkg.bzl': BUILD file not found on package path.`

Thank you.

**Comment by ycool** [comment]
Out of docker, what's the output of `uname -a` ?

**Comment by howtocodewang** [comment]
@ycool 

I'm sorry. I found that when I run the `bash docker/scripts/dev_start.sh` and I got this error which may lead to my other errors:
`26f19af9b8da: Pull complete 
Digest: sha256:e4911b638abd7457a6ac1ca7b090e228866d73b4fc0a17f4722ae93497a5367f
Status: Downloaded newer image for apolloauto/apollo:dev-latest
Error response from daemon: No such container: apollo_dev
Error response from daemon: No such container: apollo_dev
`

What should I do? Thank you.

**Comment by ycool** [comment]
@howtocodewang can you pull the latest code, run `bash scripts/env.sh >& env.txt`  and provide the content of env.txt in your post. 

Thanks.

**Comment by huangwen0907** [comment]
@howtocodewang  I may know your problems. Do you first build/set the appolo environment?
If not, you can follow the command below, it may work. I have a try and it can work for me.
>bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash apollo.sh build # inside dev docker
bash scripts/hmi.sh
opening your favorite browser, e.g. Chrome, go to http://localhost:8887, click Dreamview to start. 

 /# in a different terminal, in the apollo directory
>bash docker/scripts/dev_into.sh # jump into the docker container
rosbag play -l ./docs/demo_guide/demo.bag

**Comment by howtocodewang** [comment]
@huangwen0907 Thank you for your reply, I will try it again and find out if it could work for me.

**Comment by huangwen0907** [comment]
@howtocodewang  ah... what I want to ask is that:
how can I re-simulate or reopen the apollo simulation when I update the apollo code from the github. Thank you. 
FYI: When I set/install the simulation environment, it will create much file in the apollo folder, I am not git a commit or merge them. So should I reserve there files? Thank you again

**Comment by quning78** [comment]
Please cleanup your env and re-run those command in the manual again. 

By cleaning up, you can remove the apollo directory and re-pull from github.

Please reopen if you have any other quesitons. @huangwen0907
