### ISSUE TITLE
Apollo Perception Poor Dashed Lane Line Detection

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#5312]
In Testing the Apollo low-cost perception module,

We are discovering very accurate lane detection and tracking performance when the lane lines are solid.

However, quite poor performance with dashed lane lines, even when they are quite visible.  I was expecting it to have higher performance with this.   Any ideas / comments?

And most of the highway driving is dashed lane lines... so this seems pretty important. Any ideas / comments?

**Comment by csukuangfj** [comment]
@snuffysasa 
could you please upload some detection results to visually compare the solid and dashed lane markings?

**Comment by snuffysasa** [comment]
@csukuangfj

What would be best, I make a video and upload an mp4?

Or record a rosbag with the images and detection results ?

**Comment by techoe** [comment]
The image will be also fine. We have recently updated our lane line detection module. Please try it and see if you still have an issue.

**Comment by techoe** [comment]
I am closing it since there is no further question after last answer.
