### ISSUE TITLE
Apollo Object Tracking question

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#5313]
From the Apollo Readme:

"The object tracking sub-module utilizes multiple cues such as 3D position, 2D image patches, 2D boxes, or deep learning ROI features. The tracking problem is formulated as multiple hypothesis data association by combining the cues efficiently to provide the most correct association between tracks and detected object, thus obtaining correct ID association for each object."

I am wondering what is the object tracking sub-module?  Is that camera_process_subnode.cc or fusion_subnode.cc ?

where is this tracking taking place?

Thanks

**Comment by techoe** [comment]
object tracking is at camera_process_subnode.cc. Thank you.
