### ISSUE TITLE
Question about realtime_plot.py 

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#5319]
Hi, I have a question regarding to the usage of scripts in the folder `/modules/tools/realtime_plot/realtime_plot.py `. I'm running it while playing rosbag demo_2.0.bag. However, the following error occurs. I am wondering if I am running the script in the correct manner? Thanks for your help and I really appreciate your help. 

`Traceback (most recent call last):
  File "realtime_plot.py", line 267, in <module>
    main(sys.argv)
  File "realtime_plot.py", line 247, in main
    ax1.draw_artist(ax1.patch)
  File "/home/yangydavid/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2620, in draw_artist
    raise AttributeError("draw_artist can only be used after an "
AttributeError: draw_artist can only be used after an initial draw which caches the renderer
`

**Comment by Capri2014** [comment]
@yangydavid We intend to deprecate the realtime_plot since most of the functions now available in dreamview PnC monitor

**Comment by kk2491** [comment]
@yangydavid .. Could you please let us know how to make use of the dreamview PnC monitor. I was searching for the procedure but could not find any.

Thank you,
KK

**Comment by unacao** [comment]
In the default page of dreamview, turn off "Lock Task Panel" and turn on "PNC Monitor", the related charts will show and update on the right panel.

**Comment by marcusvinicius178** [comment]
Hi @Capri2014 I wish to get the plots available on Dreamview to present in my master Thesis. However these plots are Dynamic and is not possible to download from PNC monitor.

How can I get data of a simulation trip that lasted 45 seconds, for example, and plot the 45 data points against time 

I mean I wish to get the channels Data (IMU, speed, control, Odometer, actuators, etc) in lists and then plot. Similar to what PNC provides but I wish "Static" graphics to put in Power Point presentation....

How is this possible? I am using Apollo 6.0 in Ubuntu 18.04 in docker.

Thanks in advance

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
