### ISSUE TITLE
dreamview: ERROR (no such file)

### ISSUE THREAD

**Issue by Triangle001** [ApolloAuto/apollo#5320]
After I built the Apollo successfully,I launch Apollo with the command "bash scripts/bootstrap.sh",it show a dreamview error like this:
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: ERROR (no such file)

How do i solve the problem?

**Comment by xinwf** [comment]
You need to give us more details about this. Before this, you can look at the bootstrap.sh first.

**Comment by DongAi** [comment]
Hi, Triangle001. You can scan directory `/bazel-bin/modules/dreamview` to see if there is `dreamview` exectuable file. If it doesnot exist, use instruction `bazel build //modules/dreamview` to build it again.

**Comment by Triangle001** [comment]
@DongAi Thank you for your reply.The issue has been solved.

**Comment by guofengpeng** [comment]
Hello, i have meet the same problem, i hope you can tell me how to salve this problem, thank you much
