### ISSUE TITLE
how to get AdapterManager::GetRoutingResponse()->GetLatestPublished()

### ISSUE THREAD

**Issue by lesun90** [ApolloAuto/apollo#5326]
Hi,

I make a small program to visualize the routing. However, I could not use the  AdapterManager::GetRoutingResponse()->GetLatestPublished() to get the routing response, it always return a null pointer.
I replace GetLatestPublished() with GetLatestObserved() and my program works,but  GetLatestObserved()  only shows the previous result of routing request.

Any suggestion, or please tell me where I wrong.
Thank you.

this piece of code show that GetLatestPublished() always return a nullptr
```
  while (ros::ok()) {
    AdapterManager::FillRoutingRequestHeader("routing", &routing_request);
    AdapterManager::PublishRoutingRequest(routing_request);
    // AINFO << "Sending routing request:" << routing_request.DebugString();
    // AINFO << "RoutingResponse noy received";
    AINFO << (AdapterManager::GetRoutingResponse()->GetLatestPublished() ==
              nullptr);

    ros::spinOnce();  // yield
    loop_rate.sleep();
  }
```

**Comment by xiaoxq** [comment]
GetRoutingResponse()0->GetLatestPublished() only works in the same process where PublishRoutingResponse() is called, i.e, the publisher.

On the receiver side, you always need to call Observe() and then GetLatestObserved().
