### ISSUE TITLE
Using lidar obstacle detector without calling the ROI filter

### ISSUE THREAD

**Issue by hadiTab** [ApolloAuto/apollo#5330]
[A comment](https://github.com/ApolloAuto/apollo/blob/63a138dc8f1004ace61b9c6cf6f4228a97938195/modules/perception/obstacle/lidar/roi_filter/hdmap_roi_filter/hdmap_roi_filter.h#L46) suggests that the use of the ROI filter is optional. Does that mean it is possible to use the lidar obstacle detection in areas where there is no HD map?
I tried disabling HD map input by changing [this](https://github.com/ApolloAuto/apollo/blob/63a138dc8f1004ace61b9c6cf6f4228a97938195/modules/perception/conf/perception.conf#L41) to false in the config file but it results in an [error](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/obstacle/onboard/lidar_process_subnode.cc#L153) in the roi filter.

Is there any possible work-around?

Thanks.

**Comment by techoe** [comment]
Lidar obstacle detector can be runned without HD map or ROI filter. You can run it by commenting out the error part and other parts causing the break.

**Comment by hzdsdhr** [comment]
What you should change is :
# candidate: DummyROIFilter, HdmapROIFilter
--onboard_roi_filter=HdmapROIFilter
change it to DummyROIFilter, DummyROIFilter means the perception will detect everything in certain range, no hdmap needed.

**Comment by hadiTab** [comment]
@hzdsdhr thank you! That solved my problem.

**Comment by Tamme** [comment]
@hadiTab, could you spare some information on the accuracy of the detector without hdmap or roi? Lets say compared to some other open source lidar detection networks.

**Comment by hadiTab** [comment]
The accuracy is OK. It does a good job detecting obstacles but it doesn't do a great job classifying obstacles that aren't on the road. The classification errors can become an issue for prediction. Some static obstacles get classified as moving obstacles and the prediction module will predict a trajectory for them which can cause problems for motion planning.
