### ISSUE TITLE
Where can I get more details about the security features for Apollo?

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#5333]
Dear Apollo developers, I see Apollo is building new security features presented [here](http://apollo.auto/platform/security.html), including intrusion detection, car firewall and secure OTA kits, but I do not find the implementation of these features except secure OTA in the latest version of Apollo's code base. Is there any plan to integrate the intrusion detection and firewall feature into the current Apollo code base? Or where can I find the relevant source code or documentations for these features? Thanks for your information!

**Comment by jinghaomiao** [comment]
@hongkedavid many of security features are not in the open source platform, but available in solutions that we built for our partners.

**Comment by hongkedavid** [comment]
@jinghaomiao Got it. Thanks for your information!

**Comment by hongkedavid** [comment]
@jinghaomiao I see. Thanks!
