### ISSUE TITLE
Missunderstanding in QP_Spline_Path_Optimizer Documents

### ISSUE THREAD

**Issue by waverider995** [ApolloAuto/apollo#5338]
In section 2.2, Combine the init point and end point:

Should init point and end point take the same coefficient vector? Normally they shouldn't in the same spline segment

**Comment by lianglia-apollo** [comment]
There are some equality constraints. The coefficients are calculated based on the mathematical formula. The coefficient vector are different as you can find from the matrix.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @waverider995 feel free to reopen if you have additional questions. Thanks!
