### ISSUE TITLE
Debug grivers/gnss

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#5339]
I can't start debug drivers/gnss module cause there are some issues inside apollo's starts scripts.
In two words, in some cases there we need use <module_path> they use <module_name>.
For example in /apollo/docker/scripts/start_gdb_server.sh line 71 (apollo 2.5) call run but not run_customized_path.
source line in apollo 3.0 may be another but behavior is the same

**Comment by jilinzhou** [comment]
Starting them manually from the console is a better choice. This is especially important if you want to debug some modules alone. 

1. start roscore
2. start nodelet_manager
3. start streamer nodelet
4. start parser nodelet
5. start transformer nodelet

Here is what I did (create launch file for each nodelet first)

- roslaunch gnss_driver qnx_nodelet_manager.launch &
- roslaunch gnss_driver qnx_stream.launch & 
- roslaunch gnss_driver qnx_parser.launch &
- roslaunch gnss_driver qnx_tf_broadcaster.launch &

**Comment by gladijos** [comment]
@jilinzhou Thanks a lot for answer. I have debugged it by attaching to proccesses in VSCode. But I hope there is some way for regular debugging.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
