### ISSUE TITLE
将鼎汇 DH7D10GPS接收机接入apollo平台的疑问

### ISSUE THREAD

**Issue by ZK-Zhou** [ApolloAuto/apollo#5346]
1.	我们已经参照阿波罗docs/howto/how_to_add_a_gps_receiver.md，对代码进行了修改，2,3,4步骤已经完成，但在第1 步继承基类时有一些问题：
（1）.按照文档中的代码，我们编写了dh_parser.cc继承基类parser，文件中声明了很多类方法，这些方法在我们的文件中应该如何实现？
（2）.对比novatel_parser.cc文件，代码中包含了novatel_messages.h，我们是否需要对应的编写一个dh_messages.h？如果是，要如何编写？
2.另外，除了docs/howto/how_to_add_a_gps_receiver.md中提到的四个步骤，加入一个新的GPS接收机还有没有其他地方需要完善和修改？

**Comment by LiuZhenyao** [comment]
@ZK-Zhou 请问您那边的问题解决了吗？我也遇到了类似的问题

**Comment by ZK-Zhou** [comment]
Dear Zhenyao,
&nbsp;I ve finished the project one year ago, the solution is that, if i am not mistaken,&nbsp; creat an inter-intepreter for the GPS.
Best regards.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiuZhenyao"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 下午2:37
收件人: "ApolloAuto/apollo"<apollo@noreply.github.com&gt;; 
抄送: "FARN"<2200246371@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ApolloAuto/apollo] 将鼎汇 DH7D10GPS接收机接入apollo平台的疑问 (#5346)





 
@ZK-Zhou 请问您那边的问题解决了吗？我也遇到了类似的问题

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
