### ISSUE TITLE
preception_lowcost.sh turns off

### ISSUE THREAD

**Issue by SanduIrina** [ApolloAuto/apollo#5348]
Hey there, when I run the perception_lowcost.sh script the perception button in dreamview turns on for a few seconds then it turns back off. Any idea why this is happening?

**Comment by techoe** [comment]
Please check if you installed the CUDA correctly in the docker by typing  
nvidia-smi

**Comment by SanduIrina** [comment]
It worked on a clean linux install

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @SanduIrina feel free to reopen the same if you have additional questions. Thanks!
