### ISSUE TITLE
OnLocalization callback in prediction module

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#5350]
We have started to test prediction module on a target (4 cores) running QNX and noticed the node consistently consumes about 20% of cpu time. After some debugging, we found the high cpu usage is caused by OnLocalization callback. On our target, each loop of this callback takes about 7ms averagely but sometimes can be as high as 30ms. Since the localization topic is published in 100 Hz, this callback function is running all the time and accordingly consumes a lot of cpu time. 
On the other side, the prediction module (RunOnce callback) is running at 10 Hz by default. Is it necessary to update localization in 100Hz? Can we actively poll the vehicle state in RunOnce callback instead to avoid onLocalization callback?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
