### ISSUE TITLE
Can't access the Dreamview web, please help

### ISSUE THREAD

**Issue by jt387** [ApolloAuto/apollo#5359]
After executing the three commands sucessfully :"bash apollo.sh build; bash apollo.sh release;bash scripts/bootstrap.sh", I use the firefox to acess the http://localhost:8888, but the firefox display "Firefox can’t establish a connection to the server at localhost:8888." .  The snapshot is as below:
 
![image](https://user-images.githubusercontent.com/6219009/44143319-e26f4c76-a0b5-11e8-9efe-245ed07ca0cb.png)

 - OS: ubuntu14.04
 - Browser: firefox 61.0.1
 - apollo: 3.0

How to fix the problem? Thanks！

**Comment by natashadsouza** [comment]
@jt387 Could you try to pull the latest code, and check again?

1. Exit docker
2. Pull the latest code
3. Restart docker
4. Get into docker
5. Run apollo.sh build

Let me know if you get any errors along the way.

**Comment by siyangy** [comment]
You can also refer to https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md for troubleshooting.

**Comment by jt387** [comment]
@natashadsouza @siyangy Thanks, they are very useful！ I find that the problem is the same with [https://github.com/ApolloAuto/apollo/issues/4388](url), and I solve the problem following the advices.Thanks again!

**Comment by jt387** [comment]
changing the command "supervisorctl start dreamview  >  /dev/null" to "supervisorctl start dreamview" in the bootstrap.sh file, and run "bash scripts/bootstrap.sh",  the error "unix:///tmp/supervisor.sock refused connection"  is showed.
