### ISSUE TITLE
VLP-16 /apollo/sensor/velodyne16/PointCloud2/header Timestamp is not GPS Time

### ISSUE THREAD

**Issue by carlin314** [ApolloAuto/apollo#5360]
VLP-16 /apollo/sensor/velodyne16/PointCloud2/header Timestamp is not GPS Time

cause

[ WARN] [1534337139.532238124]: Can not find transform frame: velodyne16. 1534337850.896429 Error info: Lookup would require extrapolation into the future.  Requested time 1534337850.896429062 but the latest data is at time 1534337139.200000048, when looking up transform from frame [velodyne16] to frame [map]. canTransform returned after 0.101808 timeout was 0.1
@all2one @mbinna @bigwhite @weidezhang @poutyface 

![image](https://user-images.githubusercontent.com/16414165/44149598-43bb0eac-a0cf-11e8-9a0d-7f705d9301ff.png)
![image](https://user-images.githubusercontent.com/16414165/44149616-554dc010-a0cf-11e8-8b0d-dfd79e2c60bd.png)

**Comment by carlin314** [comment]
Left is the /apollo/sensor/velodyne16/PointCloud2/header's Time,Right is novatel inspva time

**Comment by YangHan101** [comment]
Is the GPS connected to the VLP-16?

**Comment by carlin314** [comment]
Yes, I have checked in the web

**Comment by carlin314** [comment]
I also used the official velodyne driver, the lidar time is correct,same with inspva time

**Comment by carlin314** [comment]
@snehagn @YangHan101 Thx dude,the screenshot is as follows
![image](https://user-images.githubusercontent.com/16414165/44374353-5ea1d200-a520-11e8-88a5-dca55ed4fd4a.png)

I really dont know,what could be wrong, the header time is from the packet time? 

Do your guys have any ideas?

**Comment by YangHan101** [comment]
It seems your gps is working and sending the sync signal to the lidar properly. Have you brought up the GPS driver part of the code?

**Comment by carlin314** [comment]
Any update in this @xinwf

**Comment by xinwf** [comment]
We haven't met this problem any more. 

You can do two following things:
1. Make sure the processing of IMU time is right. Once one of my colleagues treats the `us` as `ms` when dealing with IMU's time, it caused this problem.
2. Make sure the apollo is broadcast extrinsic all the time from velodyne16 to world frame. 
Besides these two reasons, if the machine runs very slowly especially the disk has an very high I/O ratio, it will also cause this problem, but this is not the apollo's problem.

Good luck.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
