### ISSUE TITLE
How are  /apollo/modules/perception/model/yolo_camera_detector/lane2d_* generated?

### ISSUE THREAD

**Issue by vladpaunescu** [ApolloAuto/apollo#5361]
Hello!

When cloning the repo `/apollo/modules/perception/model/yolo_camera_detector/lane2d_0612/deploy_lane_high.pt` is not there. Even when they are generated inside `docker`, the contents of `/apollo/modules/perception/model/yolo_camera_detector/lane2d_*/` are not visible from the host machine.

I have a problem when I start `./scripts/perception_lowcost.sh`

```
File not found: /apollo/modules/perception/model/yolo_camera_detector/lane2d_0612/deploy_lane_high.pt
```

It complains of empty directory inside `lane2d_0612`. Current git master has different config for `yolo_camera_detector`, namely 
`/home/vlad/apollo/modules/perception/model/yolo_camera_detector/lane.pt`

`model_name: "lane13d_0716"`

My git checkout had a different name called: `lane2d_0612`
My questions are:
1. Are these networks the same?
2. How are the these model directories being created and populated?
3. Why are the files only visible inside `docker` and not inside host OS?

Many thanks,
Vlad

**Comment by techoe** [comment]
Please restart docker. The files were replaced by new one but old script still try to access it. There are several docker only files which is not accessible outside.

**Comment by apollodevcommunity** [comment]
it exists in other docker containers，when you run dev_start.sh   the model container will open and combine with dev container. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=643
