### ISSUE TITLE
1080ti run apollo kernel mismatch

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#5372]
请教：
我们使用1080ti显卡，ubuntu14.04，安装apollo-kernel时遇到不兼容问题，具体就是先装apollo-kernel，再装显卡驱动，驱动提示不支持RT OS；先装显卡驱动，再装apollo-kernel，装完kernel之后，驱动无效，表现为分辨率只有一个，无法更改，且nvidia-smi命令，提示Failed to initialize NVML: Driver/library version mismatch。

参考了不少issues，尝试其中的方法，始终无法解决。

**Comment by freeHackOfJeff** [comment]
Hello,
First of all, can you please ensure that you have download the related driver of 1080 ti, i,e,
http://www.geforce.cn/drivers/results/115056

Secondly, please make sure you have disable the default driver, e,g, 
sudo gedit /etc/modprobe.d/blacklist.conf

blacklist nouveau  
options nouveau modeset=0

Reboot the os, then check the result via:

lsmod | grep nouveau

Good luck!

**Comment by ahuer2435** [comment]
@freeHackOfJeff  
我是参考：http://www.bubuko.com/infodetail-2356927.html安装，nvidia驱动和cuda的版本也是参考上述链接，上述设置都有做过，驱动安装之后，使用nvidia-smi命令检查过，是可以的，而且分辨率正常且可以选择，所以驱动本身安装应该没有问题。

之后在安装apollo-kernel，使用uname -a，发现kernel安装了，但是此时nvidia驱动无效了，使用nvidia-smi，提示Failed to initialize NVML: Driver/library version mismatch。分辨率也不对，且不可更改。

**Comment by freeHackOfJeff** [comment]
I do hope this article can help you out. :)
https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch

**Comment by pengpingliang** [comment]
@ahuer2435  Did you resolve it ? I met the same problem~
Card  : 1080ti
OS : ubuntu14.04
Driver : 378.13

@freeHackOfJeff  
PS : If no install the apollo the kernel, the all is OK!  Has any crash between Apollo RT kernel and Nvidia Driver kernel ?

**Comment by storypku** [comment]
Install Nvidia driver on an PREEMPT_RT kernel will fail with the following message, which is the reason of the incompatibility. This issue hasn't been solved by Nvidia as of this writing.

```
The NVIDIA driver does not support real-time kernels. If you 
are using a stock distribution kernel, please install 
a variant of this kernel that does not have the PREEMPT_RT 
patch set applied; if this is a custom kernel, please 
install a standard Linux kernel.  Then try installing the 
NVIDIA kernel module again.
```
