### ISSUE TITLE
Pad message

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#5374]
I use Apollo 2.5 with my own simulator. I realize localization and canbus protocols (module algorithm realizations). They communicate with simulator and transfer INS, chassis and ControlCommand data. I launched dreamview, chose standard mode (according to #4937 I can't use navigation mode right now), start modules  canbus, localization, routing, planning, control. Also I adjust with map_offset help coordinates of my simulator floor-field to SunnyvaleLoop map. It helps me with sending routeRequests and start planning. I see planning trajectory, Control Command is generated by Control module but Canbus module (VehicleController class) didn't call     
`    Gear(control_command.gear_location());
    Throttle(control_command.throttle());
    Brake(control_command.brake());
    SetEpbBreak(control_command);`
cause control_command.has_pad_msg() == false and driving mode is COMPLETE_MANUAL.
How can I produce and send Pad Message to Control module. I find out generating Pad message available just from voice command but I hope I'm wrong.
Please help :)

**Comment by mickeyouyou** [comment]
you can run `./scripts/pad.sh` send different action for apollo : 
```bash 
apollo@in_dev_docker:/apollo$ ./scripts/pad.sh
I0816 19:14:35.949422 28683 terminal.cc:49] COMMAND:
I0816 19:14:35.949604 28683 terminal.cc:50] 	0: reset to manual drive mode.
I0816 19:14:35.949615 28683 terminal.cc:51] 	1: auto drive mode.
I0816 19:14:35.949620 28683 terminal.cc:52] 	ctrl + c: exit.
I0816 19:14:35.949625 28683 terminal.cc:53] 	other: print help.
0
I0816 19:14:36.744787 28709 terminal.cc:60] sending reset action command.
I0816 19:14:36.745098 28709 terminal.cc:67] send pad_message OK
```

**Comment by gladijos** [comment]
got it! It works. Also I can launch ./bazel-bin/modules/control/tools/pad_terminal inside docker. I hope it works similar.
Thanks a lot!

**Comment by Zhenni17** [comment]
Closing the issue since the issue was resolved.
