### ISSUE TITLE
UDP packets can not be obtained in custom gnss driver

### ISSUE THREAD

**Issue by cvbn127** [ApolloAuto/apollo#5375]
I'm writing a custom gnss driver.
 1. In your how_to_add_a_gps_receiver nothing is said about the need to change the file apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt.
 2. My gnss driver does not receive udp packets. UdpStream does not report any problems, its status is CONNECTED. But the data is not received. Data comes (checked via netcat), the problem is with getting this data. After I changed the protocol from udp to tcp(both in gnss_conf.pb.txt and on the device sending the data), i was able to receive them in my gnss driver. But I would like to receive them via udp.
Could you help me?

OS: Ubuntu 16.04.4 LTS
Apollo version: 3.0

**Comment by YangHan101** [comment]
On your 2nd question, I wonder if you are using the ethernet to feed rtcm data to the receiver? Did you configure your receiver to take udp data through the ethernet port? Do you have specific reason to use UDP?

**Comment by cvbn127** [comment]
Yes, i configure my receiver.
My receiver does not send all the data I need through one data stream. I need to either send data via TCP (1 ip, two ports, two streams to receive data), or via UDP (1 ip, 1 port, 1 data stream). udp is more convenient for me.

**Comment by YangHan101** [comment]
Well, it seems you are not following the recommended design of Apollo. I am afraid it is beyond my knowledge. I am going to loop in a few other people and see if they have an answer for you.

**Comment by apollodevcommunity** [comment]
you use udp send/recv or multicasting or broadcasting? I think it\'s a networking programming problem   not just apollo issue. you may check your network configuration   is the networking cross routing   is there any static routing between the sendor and receiver? ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=642

**Comment by cvbn127** [comment]
In my case, I was able to receive udp packets after I added the code for socket binding [at this line](https://github.com/ApolloAuto/apollo/blob/778724720d8153e5f48ef2dd5145f854f5c48bd9/modules/drivers/gnss/stream/udp_stream.cc#L131).

something like that:
```c++
struct sockaddr_in peer_sockaddr;
socklen_t socklen = sizeof(peer_sockaddr);
bzero(&peer_sockaddr, sizeof(peer_sockaddr));
peer_sockaddr.sin_family = AF_INET;
peer_sockaddr.sin_port = peer_port_; 
peer_sockaddr.sin_addr.s_addr = peer_addr_;

if (bind(fd, (struct sockaddr *)&peer_sockaddr, socklen) == -1) {
  AERROR("bind fail");
  ::close(sockfd_);
  return;
}
```
