### ISSUE TITLE
can't connect to http://localhost:8888

### ISSUE THREAD

**Issue by johndoe95** [ApolloAuto/apollo#5376]
I have successfully run dreamviewer with "bash bootstrap.sh", but when I try to run "rosbag play demo_1.5.bag --loop", my firefox shows Unable to connect .
So who can tell me the reason. Thank you very much !
BTW, I know there will be an error" rosbag: command not found" if I run Apollo with root user, but I don't know how to run it without root ( because terminal will show " get permission" ).

**Comment by DongAi** [comment]
Hi johndoe95, it's not a good idea to run with root user. The error implys that something hasn't been set correctly, please refer to [a similar issue](https://github.com/ApolloAuto/apollo/issues/5257) to check if it's useful.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
