### ISSUE TITLE
what about the way for the data stream of apollo ? 

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5383]
Hello, Excuse me. when the apollo is running, the camera 、lidar and others device will gather data to keep the car is normal operation. So I want to know, The camera、lidar and others device need to gather how much data ? and how does the data flow ?For example from the description on the bus device, or from the kernel, rtos, apollo. and what is the standard of camera、lidar and others device ? such as How many frames per second per camera？How much data does the laser radar produce per second?
  
Best regards！Thank you!

**Comment by breakisx** [comment]
call apollo...

**Comment by daohu527** [comment]
@breakisx 

a late reply!

> such as How many frames per second per camera？How much data does the laser radar produce per second?

It depends on the camera, usually 30Hz, radar are usually 100Hz, and lidar 10hz
