### ISSUE TITLE
Technical Paper on Planning module

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5386]
Hi Guys,

Is there any Technical paper to understand "Planning module" deeper. 
Specifically in the case of Planner and Trajectory generation for the autonomous vehicle.

Thank you,
KK

**Comment by gladijos** [comment]
I saw some paper for old version of planning algorithm but can't find this again.

**Comment by kk2491** [comment]
After doing some research I found one paper - Baidu Apollo EM Motion Planner. 
https://arxiv.org/pdf/1807.08048.pdf
Kindly let me know if this is the right one.

**Comment by natashadsouza** [comment]
@kk2491 yes that is the right paper. Thanks!

**Comment by kk2491** [comment]
@natashadsouza Thank you for the clarification. You can close the issue.
