### ISSUE TITLE
Is there API to add a sign into HDmap in runtime

### ISSUE THREAD

**Issue by alexbuyval** [ApolloAuto/apollo#5389]
Hi,

I am developing a sign detection module for the apollo. I am wondering if there is a way to add a sign into the loaded hdmap in the runtime mode.

Thank you for any advice!

**Comment by daohu527** [comment]
There is no corresponding interface yet, but I think it's easy to add, since most high-resolution maps have dynamic layers.

Adding a dynamic layer requires designing a new module and then providing a unified interface.
