### ISSUE TITLE
Offline Perception LowCost Visualizer Not Showing

### ISSUE THREAD

**Issue by liuyangly25** [ApolloAuto/apollo#5392]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 2.5

### Steps to reproduce the issue:
- follow the guide [how_to_run_apollo_2.5_perception_visualizer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_perception_visualizer.md)
- `cd /apollo`
- `./apollo.sh build_opt_gpu`
- change config `--dag_config_path=conf/dag_camera_obstacle_offline_fusion_sync.config`
- `./scripts/bootstrap.sh`
- `./scripts/perception_lowcost_vis.sh`
- `rosbag play demo_2.5.bag`

### Supporting materials (screenshots, command lines, code/script snippets):
[screenshot](https://ibb.co/kMdE3K)
dreamviewer works fine but popup window not showing
Did I miss any steps?

**Comment by techoe** [comment]
Thank you for using Apollo!

Ubuntu 16 and glfw in docker may not match. Please take a look at this document
apollo/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md
Please let us know if you still have the issue.

**Comment by liuyangly25** [comment]
Hello @techoe , thank you for replying. I installed GLFW 3.2.1 and added `glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);` in `glfw_fusion_viewer.cc`. But the pop up still now showing.

**Comment by liuyangly25** [comment]
Hi @techoe , I switched to ubuntu 14.04.3. But still, I can't see the popup. Did I miss anything?

**Comment by sinopec** [comment]
I am in ubuntu 14.03,and I rebuild glfw 3.2.1 both in docker&host. But I have the same problem.

**Comment by xiaoshuliu** [comment]
@liuyangly25 @sinopec Hi, could you please check the /apollo/data/log/perception.INFO and perception.ERROR to see if there is an error? There are many possibilities that stop the visualizer from poping up.

**Comment by liuyangly25** [comment]
Hello @xiaoshuliu , thank you for replying. I do have errors in perception.ERROR files. seems like glfw is not working. But I already installed glfw 3.2.1 in docker.

Log file created at: 2018/08/28 15:45:27
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0828 15:45:27.712261  5318 glfw_fusion_viewer.cc:180]  Failed to initialize the window !

**Comment by natashadsouza** [comment]
@liuyangly25 for Ubuntu 14, you do not need to separately download the glfw file. Please follow the download steps for Ubuntu 14 from the start and let us know if you are getting any errors. Thanks!

**Comment by liuyangly25** [comment]
@natashadsouza , I also tried running apollo on ubuntu 14.4 with NVIDIA driver installed on both host and docker. But I didn't get luck on it. From perception.out file, I got `F0824 11:03:26.991583 13256 cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR`

I guess it is building the graph but suddenly a cudnn internal error occurred.

More details here:

I0824 11:03:26.990317 13256 layer_factory.hpp:79] Creating layer SCNN_D_27/relu
I0824 11:03:26.990327 13256 net.cpp:94] Creating Layer SCNN_D_27/relu
I0824 11:03:26.990337 13256 net.cpp:428] SCNN_D_27/relu <- SCNN_D_27/message
I0824 11:03:26.990348 13256 net.cpp:389] SCNN_D_27/relu -> SCNN_D_27/message (in-place)
F0824 11:03:26.991583 13256 cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: **

**Comment by natashadsouza** [comment]
@liuyangly25 did the build changes not resolve the CUDA error you are currently facing?

**Comment by liuyangly25** [comment]
@natashadsouza , no,  the build changes is for glfw 3.2.1 on ubuntu 16.04. On ubuntu 14.04, I didn't change anything, just used the default glfw in docker. I don't know where the cudnn internal error comes from. googling gives me few information.

**Comment by yg13** [comment]
@liuyangly25 @techoe  Sorry to ask about this old issue. Could I ask if anyone find a solution at last?

**Comment by ccyinlu** [comment]
@liuyangly25 , Did you solve the problem? I was fronted with the same problem, not know why failed to initialize the window!

**Comment by hzdsdhr** [comment]
@liuyangly25 hi, have you solved it? I am having the same problem, the visualizer is not showing and I also installed the glfw in host and docker.

**Comment by mayankdhingra02** [comment]
Hi, I have installed GLFW 3.2.1 in UBUNTU 16.04. But I am not able to find glfw_fusion_viewer.cc file to make the required change mentioned in "https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md" even after a lot of searches. Could someone please guide me on this?

**Comment by wardenLL** [comment]
> Hi, I have installed GLFW 3.2.1 in UBUNTU 16.04. But I am not able to find glfw_fusion_viewer.cc file to make the required change mentioned in "https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md" even after a lot of searches. Could someone please guide me on this?

@mayankdhingra02 you can find the file here : modules/perception/obstacle/camera/visualizer/glfw_fusion_viewer.cc

**Comment by sjiang2018** [comment]
Hope our answer resolved your questions. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
