### ISSUE TITLE
RTK 定位问题

### ISSUE THREAD

**Issue by Triangle001** [ApolloAuto/apollo#5393]
您好。我使用RTK定位，怎样知道apollo接收到GPS的信号，需要修改什么配置文件吗，定位成功的是什么现象，dreamview上需要什么操作吗？请不吝赐教，谢谢。

**Comment by wfgsy101** [comment]
定位成功后，rostopic echo 会出现x,y,z相关定位坐标信息，需要gps相关配置

**Comment by apollodevcommunity** [comment]
第一个问题，需要修改配置文件，包括localization各个参数、GNSS航向配置、导航模式配置、USB接口输出配置、网口配置、天线杆臂设置等等都需要根据自己实际情况修改为自己的配置。第二个问题，输入命令bash scripts/localization.sh后打开localization模块可以查看各个topic的状态/apollo/sensor/gnss/best_pos 和/apollo/localization/pose，还可以指令查看接收卫星数量等等，输出正常代表有定位。最后，Dreamview上也要设置比如打开GPS、Localization的模块。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=639
