### ISSUE TITLE
Depth prediction in Apollo

### ISSUE THREAD

**Issue by funkydvd** [ApolloAuto/apollo#5394]
Hi, I'm new to this framework, we work in a project involving autonomous driving and I am curious if there is any depth prediction made if you don't have a lidar or a radar, and if there is a depth prediction where is the prediction made (what file). I have searched in the code for "depth" and I didn't find any good results.
Thank you for your pacience and sorry if it is a stupid question.

**Comment by funkydvd** [comment]
Has anybody any idea? I found that there is computed an Euclidean distance but I still don't know how are mapped the coordinates directly from the camera, if you don't know any real distance (just the pixel). I would really appreciate if anybody helps us with the depth prediction based only on the camera (I saw that is possible only with the camera).

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
