### ISSUE TITLE
Navigator planning issue

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5396]
code version：apollo 3.0
about module：Location 、Planning（navigator pattern）、Driver

issue description&&phenomenon：
1. about apollo 3.0 Planning moudule,when we use RTK planning scripts to record and replay vehicle track,in the dreamview window ,we can find that the direction of the vehicle head is inconsistent with the planning path.such as :
![01](https://user-images.githubusercontent.com/19250516/44277758-37c47100-a27e-11e8-948c-95754f49f023.jpg)

some times ,we don't move the GPS and IMU sensor ,we also can find that  the direction of the front is opposite to the planning path.

so ,there are some question:
1. in the dreamview window,such as the picture,is the green line vehicle head? if yes ,at present,
    a.we use RTK location and navigator planning pattern.
    b. we use IMU   quaternions  （x,y,z,w）to set  /apollo/sensor/gnss/corrected_imu ros topic
    c.we use Zhong Hai Da Gnss，so we add ZHD device driver in dirver moudle, because this Gnss device don't have IMU ,so we use another IMU to set /apollo/sensor/gnss/odometry topic.
when location moudle in RTK location pattern, location moudle received /apollo/sensor/gnss/corrected_imu and /apollo/sensor/gnss/odometry rostopic , can location moudle correct the vehicle head?
if not，how can we make the vehicle head and record track is the same direction?
![03](https://user-images.githubusercontent.com/19250516/44277916-e5378480-a27e-11e8-98fc-427cf8e7a4bc.jpg)
2、when use Navigator planning pattern, we use Gnss and IMU sensor,need all of these sensor calibration？

**Comment by yifeijiang** [comment]
You mentioned "we use RTK planning scripts to record and replay vehicle track". Can you illustrate the process and which scripts are used? did you follow the steps in https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode.md ? It seems that the heading of vehicle was incorrect in the first image. Or was the vehicle facing the road in that way at the time you capture the image?

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while. @freeclouds feel free to reopen this issue if you have any further questions. Thanks!
