### ISSUE TITLE
localization 问题

### ISSUE THREAD

**Issue by Triangle001** [ApolloAuto/apollo#5405]
您好。我接入GPS，使用“bash scripts/bootstrap.sh”命令启动apollo，进入dreamview的Module Controller中Hardware的GPS项为“WARN”，然后检查gnss.INFO发现：
I0818 17:45:43.668114 124405 gnss.cc:42] The adapter manager is successfully initialized.
E0818 17:45:43.668725 124405 file.h:105] Failed to parse file /apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt as text proto.
E0818 17:45:43.668892 124405 file.h:144] Failed to parse file /apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt as binary proto.
E0818 17:45:43.669067 124405 apollo_app.cc:59] gnss Init failed: DRIVER_ERROR_GNSS: Unable to load gnss conf file: /apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt

检查localization.INFO发现：
E0818 17:05:34.202730 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.211760 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.221827 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.231798 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.241870 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.252522 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.262867 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.271986 119480 rtk_localization.cc:84] GPS message buffer is empty.
E0818 17:05:34.281957 119480 rtk_localization.cc:84] GPS message buffer is empty.

请问这定位过程中出现的问题怎样解决，谢谢。

**Comment by wfgsy101** [comment]
/apollo/modules/drivers/gnss/conf/gnss_conf.pb.txt
modules/calibration/data/vehicle_name/gnss_params/gnss_conf.pb.txt
都需要修改

**Comment by mickeyouyou** [comment]
默认的配置文件是不能直接使用的，请按照情况配置成合适的内容之后重启再次尝试，有问题可以随时reopen。
