### ISSUE TITLE
Newbie questions:Contributing to Apollo software

### ISSUE THREAD

**Issue by SohamGhormade** [ApolloAuto/apollo#5406]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Linux Ubuntu 18.04.1 LTS
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:If there is a file or query I can run to find the Apollo version I am running please let me know.I followed the instructions to install without hardware.

 Question 1
- Can I contribute to the software without having a vehicle?
   - If yes, I was wondering if there are issues which I can look at as a newbie to this repository.
      - The Help Wanted tag appears to mostly be other developers having questions like me.
      - Are there other tags I can search for ?A module you can recommend for beginners?   
   - If not,other than Lincoln MKZ ,is there a list of other vehicles you recommend?

  NOTE:
-I found the read me docs in the repository useful and also took a look at open issues before opening this issue.
-I have installed Apollo on my machine and am able to build it as well run unit tests.
- Not expecting a lot of handholding but would appreciate if you had some getting started advice.
 
###About me(info if needed)
 - 3 years of professional experience in C#/.NET development.
 - Familiar with Machine learning basics and interested in perception.
 - Currently enrolled in Udacity's course for Apollo.

### Supporting materials (screenshots, command lines, code/script snippets):
`[How to contribute.md](https://github.com/ApolloAuto/apollo/blob/ca66ba5244f9a77fa1218f3dfcf27707932b3aae/CONTRIBUTING.md)`

**Comment by SohamGhormade** [comment]
Question 2
- What are the recommended computer specifications to build locally?

   - I have a 8GB RAM and ~45 GB memory with i5 processor.It took around 90 minutes to build the code 
   locally.
   - But my pull request took only 20 minutes to build!
   - It is possible that the server build machines have better specs so wanted to check with you what your recommendations were.

Kindly reply when you get  a chance.Thanks in advance for your time.

**Comment by SohamGhormade** [comment]
Question 3
- I am having trouble with getting  DreamView to start .
  - After building all modules in debug mode ,I see a build passed message,when I run the script for 
    DreamView,I get the error stating that dreamview module has not been built.Does it have to be built in release ?

**Comment by freeHackOfJeff** [comment]
Hey Soham,

It's more than welcome to contribute to Apollo! About your question, please see the following:

1) 14.04 release it recommend to run with Apollo, but you can try 16.04 or even newer.
    Execute 'git branch -a' could find out the details upon every release or other developement target,
    and write code against the master as the newest code base.
    Yes, you can contribute without an vehicle, like add the test cases to enlarge the test coverage.
2) It sounds good in terms of your development machine, please build it within docker. :)
3) Could you please kindly show your error message of Q3?

**Comment by muleisheng** [comment]
Hi SohamGhormade.
Q1: This is an abnormal phenomenon.Please check your path.
Q2: I think you should install cuda-8.0. Otherwise, you may not use your GPU
