### ISSUE TITLE
Add global variables into DreamView for visualization

### ISSUE THREAD

**Issue by ironsuperdev** [ApolloAuto/apollo#5416]
Is there a tutorial/way showing how to add global variables into DreamView for its visualization? Thanks

**Comment by vlin17** [comment]
Could you elaborate more about the request? What types of global variables, and how you want to visualize them?

**Comment by ironsuperdev** [comment]
@vlin17 
For example, the input variables for control module are:

![image](https://user-images.githubusercontent.com/34617951/44380344-5dcb6900-a53d-11e8-87eb-8aa5806e2547.png)

I would like to see the x, y, z values in format of time graph in Dreamview

**Comment by gladijos** [comment]
I think the easiest way is throw them to pnc monitor that can do same with another data

**Comment by vlin17** [comment]
Yes, the easiest way is to throw them to pnc monitor. Some graphs that have been provided for control module are: 
![control_monitor](https://user-images.githubusercontent.com/2775888/44482883-6df74d00-a5fe-11e8-93a7-9456b7db9f35.png)

Trajectory graph shows ego-vehicle's x position, y position, heading, steer curve in the past 8 sec. If this not what you want, to add a desired graph, please 
1. construct/update graph data in dreamview/frontend/src/store/control_data.js
2. config graph options/properties (e.g. line color, x-axis, y-axis) in dreamview/frontend/src/store/config/ControlGraph.yml
3. add the graph to the monitor in dreamview/frontend/src/components/PNCMonitor/ControlMonitor.js
4. compile frontend: bash apollo.sh build_fe. (Note: make sure all npm packages are installed first. if not, run "yarn install" under modules/dreamview/frontend directory)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
