### ISSUE TITLE
testing data for perception

### ISSUE THREAD

**Issue by Zhongen** [ApolloAuto/apollo#5417]
I wanna individually run perception module on my my local machine that test the ability to detect obstacles or traffic lights recognition then visualize the simulation process on Dreamviewer. But, where I could get sensor data or testing data feed into perception module?
Any helpful answer is appreciated!

**Comment by freeHackOfJeff** [comment]
Hi Zhonggen,

At modules/perception/README.md, you can see more details information about that. We have opened data set which could be found at http://data.apollo.auto.

Also, Please check up the related staff from modules/perception/data/

**Comment by Zhongen** [comment]
Hi Jie,

Thanks for your response. Your prompts are very useful. I got better understood about perception module and data platform. 
But for files under modules/perception/data/, I have no clue about those and is there any docs for this folder. 

Thanks in advance.

**Comment by apollodevcommunity** [comment]
you can get the usage example in apollo/docs/demo_guide/README.md```python3 docs/demo_guide/record_helper.py demo_3.5.recordcyber_recorder play -f demo_3.5.record --loop```get demo_3.5.record first and then play it. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=636
