### ISSUE TITLE
PnC monitor elements

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5418]
Hi Guys,

I have just enabled the PnC monitor in Dreamview to visualize and better understand the code. 

After enabling the PnC monitor, I could see 2 more lines (1 trajectory + 2 new ones) in the dreamview interface. I believe blueish green line is the reference line but I am not sure about the other one (sky blue line). 

![image](https://user-images.githubusercontent.com/38481564/44323260-b849c400-a46e-11e8-96c4-77ba3057a8ca.png)

Can anybody please explain what these lines signify.

Thick green    - Trajectory
Blueish green - ?
Sky blue         - ?

Thank you,
KK

**Comment by startcode** [comment]
The red line: routing line
The slimmest blue line: reference line
The medium width blue belt: dp path line
The  widest belt: planning's final trajectory

**Comment by kk2491** [comment]
@startcode Thank you so much for the quick reply.
