### ISSUE TITLE
Faild to build_velodyne

### ISSUE THREAD

**Issue by IneverStop** [ApolloAuto/apollo#5419]
Hi!
When I try "bash apollo.sh build_velodyne", it shows follows:

......
-- Up-to-date: /home/tmp/ros/share/velodyne/launch/start_velodyne_16.launch
-- Installing: /home/tmp/ros/share/velodyne/scripts
-- Up-to-date: /home/tmp/ros/share/velodyne/scripts/start_velodyne.sh
CMake Error at gtest/cmake_install.cmake:42 (FILE):
  file INSTALL cannot find
  "/apollo/modules/build_isolated/velodyne/gtest/libgtest.so".
Call Stack (most recent call first):
  cmake_install.cmake:142 (INCLUDE)

make: *** [install] Error 1
<== Failed to process package 'velodyne':
  Command '['make', 'install']' returned non-zero exit status 2
Reproduce this error by running:
==> cd /apollo/modules/build_isolated/velodyne && make install

It seems like that I don`t have the require file.
I will be very appreciate if anyone help me!
Thank you very much!

**Comment by IneverStop** [comment]
Problem seems in there:  
catkin_make_isolated --install --source drivers/velodyne \
    --install-space "${ROS_PATH}" -DCMAKE_BUILD_TYPE=Release \
    --cmake-args --no-warn-unused-cli

**Comment by lianglia-apollo** [comment]
(1) Please make sure you are inside docker.
(2) before building drivers, please run "bash apollo.sh build" for ros.
