### ISSUE TITLE
Changing frame per second 

### ISSUE THREAD

**Issue by hmdt** [ApolloAuto/apollo#5420]
Hello, 

According to the Apollo documentation and its architecture, Apollo modules may start to process an input at certain points (using a timer) and/or after receiving a package from their predecessor module in the pipeline.
1) Can we change the timer to reduce the frame per second (FPS) in such a way that the entire pipeline follows this slowdown? 
2) Can it be applied to a recorded ROS file that you are providing as a demo?

Thanks.

**Comment by hmdt** [comment]
@mickeyouyou Do you have any update on this?

**Comment by jilinzhou** [comment]
Which modules and which messages do you want to slow down? Each ros node has its own message callback thread.

**Comment by hmdt** [comment]
Thanks for the reply. 

I mainly want to slowdown the perception and the inputs that are coming from the inputs (e.g. camera). Accordingly, subsequent modules that are waiting for the perception data should slowdown. 
Moreover, modules such as localization and planning that are also triggered based on a timer, I need to change this timer so that I can manage the whole slowdown.
The main purpose for this is that we want to give enough time to each module to finish its job in order not to overlap with any other running modules.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
