### ISSUE TITLE
Question about apollo.sh build options.

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5421]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: From source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: Version 3.0

Hi Apollo team,
I have a question about `apollo.sh` build options.
![image](https://user-images.githubusercontent.com/37093857/44332997-79d0fb00-a4a8-11e8-8edc-b7973b74c901.png)
It seems that there are several build options when user execute the `apollo.sh` file.

**Q1. If I want to build entire Apollo system, is it right to build with `./apollo.sh build` ?**

**Q2. And do I have to run `./apollo.sh clean` every time before I build a new one?**
For example when I want to run `./apollo.sh build_gpu` after `./apollo.sh build`,
is it okay to run `./apollo.sh build_gpu` after `./apollo.sh build` without `./apollo.sh clean`?
(`./apollo.sh clean` seems to initialize the build environment.)

Thanks!

**Comment by mickeyouyou** [comment]
A1: Absolutely right

A2:that's ok, that will update build result.

**Comment by CCodie** [comment]
@mickeyouyou 
Thanks for the reply!
I want to use my GPU and I installed Nvidia GPU Driver both in host & docker.
If I run `./apollo.sh build`, then is it not necessary to run `./apollo.sh build_gpu` additionally?

**Comment by natashadsouza** [comment]
@CCodie apologies for the delay in responding. One build is more than sufficient you do not need to run the second build command. Also, if this issue has been resolved, could we close it?

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
