### ISSUE TITLE
RTK planning 实车测试问题

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5423]
使用code版本：apollo 3.0
相关模块：planning 、control
在使用apollo 3.0 RTK planning这种路径循迹方式实车测试时，
1、我们先用rosbag record -a录制好机器人运行的数据包
2、使用rtk_recorder.py录制garage.csv文件
3、使用rtk_player.py播放录制的轨迹
4、启动control模块
       进行到步骤4时出现一个问题即我们的车停在录制轨迹的起始点但是rtk_player.py脚本已经开始播放轨迹，在control模块里面寻找最近轨迹时中间已经有一些轨迹播放过了，此时控制车无法正确到下一个点。但是若先启动control模块后，后运行rtk_player.py control模块又无法启动。
        我想请教一下，在实车测试RTK planning时，到底是怎样一个步骤？我们可以使用dreamview 进行RTK planning实车测试吗？这方面有相关详细文档吗？该如何保证播放录制轨迹时能够让control模块控制车从起点到录制的第一个点，而不是运行control模块时播放的轨迹此时的点？

**Comment by mickeyouyou** [comment]
A1、使用RTK的步骤？
大致分为录制估计，播放轨迹，进入自动驾驶，三个步骤：
1、录制轨迹（点击屏幕的Record Start 或者 `bash  ./scripts/rtk_recorder.sh`）
2、规划轨迹（点击屏幕的Replay Start 或者  `bash  ./scripts/rtk_player.sh`）启动一个节点，下发planning msg 进而让Control 下发控制指令给Canbus 模块。
3、（主驾驶位确保有人，踩住刹车）点击进入自动驾驶（点击屏幕 StartAuto），缓慢松开刹车。

A2、RTK测试当然可以在Dreamview中进行，比如选择mode 为RTK Record and Replay，然后选择对应的操作均是跟对应的启停脚本绑定的。

A3、该如何保证播放录制轨迹时能够让control模块控制车从起点到录制的第一个点，而不是运行control模块时播放的轨迹此时的点？
逻辑是查找最近的点。

**Comment by freeclouds** [comment]
@mickeyouyou 非常感谢你的回复，我们目前用RTK这种方式已经完成了实车测试，前面是我们自己写的脚本问题。目前我们的测试方式是：
1、定点测试
修改moudle/tools/navigator/rtk_player.py python脚本中发布的轨迹点，设置为一固定点，测试车在固定点间运动。
2、录轨迹测试寻迹
a、用bash ./scripts/rtk_recorder.sh录制garage.csv文件
b、开启location moudle、gps、control moudle
c、运行bash ./scripts/rtk_player.sh脚本，车开始运行
