### ISSUE TITLE
Question about how to decode the canbus message.CAN消息解码问题

### ISSUE THREAD

**Issue by DogLi07** [ApolloAuto/apollo#5430]
您好！
我在学习代码的过程中，一直没有找到如何将CAN消息按照一定的格式解码。据我所知，一般用像dbc文件这种方式进行解码。但我在整个工程内，没有找到类似的功能代码。请问是否有这个功能的代码？我该在哪查看？
Hello!
During the process of code learning, I can't find the code that can decode the message from CANBUS. As I known,  normally, dbc file is used to decode the CAN message. Is there any simular code to achieve such function? Please tell me.

**Comment by hzdsdhr** [comment]
查看代码：apollo/modules/canbus/vehicle/lincoln/protocol
这里面的所有源文件都是通过解析林肯车的dbc得到的，使得你可以使用这些源文件里的类来解析和发送can报文，apollo还提供了工具，利用dbc文件生成这些源文件，/home/gwm/apollo3.0/apollo/modules/tools/gen_vehicle_protocol

**Comment by DogLi07** [comment]
@hzdsdhr
您好！谢谢您的建议！我还有一些疑问。
你说的 /lincoln/protocol里面的文件，我之前已经大概看了。我知道这个是对应某些Message的解析，但是，据我所知，应该需要精确到某些bit，例如一个message的长度是2个byte，从1bit到16。我在protocol文件里面没有发现这种，proto里面基本是对byte进行操作。是我漏掉什么吗？
另外，你说的工具/home/gwm/apollo3.0/apollo/modules/tools/gen_vehicle_protocol，这个我之前也看了，请问是不是extract_dbc_meta.py，根据说明文件
* `extract_dbc_meta.py`: extract dbc info to a internal generator tool used yaml config, which will include a protocol name, id, how many vars in a protocol, every var's name, type, byte start, bit_start, bit_len etc. When we have these info, we can automitally generate code as we wish.
这里说会包含name, type, byte start, bit_start, bit_len等等，但是我跑不通这个py文件，请问是不是需要自己提供一个yml文件才能跑? Apollo有自带yml作为参考吗？

**Comment by hzdsdhr** [comment]
不好意思，我没仔细看过这个解析代码，但我的理解是代码里的byte是uint8类型的指针，相当于can报文64位（8个字节）中一个字节，通过索引[]就可以得到每一位。关于这个解析工具，因为没用过，所以没有概念

**Comment by DogLi07** [comment]
@hzdsdhr 
没事，十分感谢。我还是获益不少！

**Comment by apollodevcommunity** [comment]
DBC文件以及经过CANOE等工具验证没有问题，其中包含Apollo所需要的控制信号、反馈 信号、耗时要求等内容。文档参见：http://apollo-homepage.bj.bcebos.com/Apollo_by_wire_requirement.xlsx ——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=634
