### ISSUE TITLE
Show rostopic  Error

### ISSUE THREAD

**Issue by Triangle001** [ApolloAuto/apollo#5434]
Hello.
After using the command "scripts/bootstrap.sh" to launch apollo，I want to see some data about a topic so execute the command "rostopic echo /apollo/localization/pose" , the result shows that:
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
ERROR: Cannot load message class for [pb_msgs/LocalizationEstimate]. Are your messages built?

### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo version (3.0)**:

Can you help me please? Thanks.

**Comment by mickeyouyou** [comment]
1, Did you execute commads(`rostopic echo /apollo/localization/pose` ) in docker?

2. Inadditional, if you just start Bootstrarp, that will setup monitor and dreamview module, `apollo / localization / pose'doesn't have data, you need to `rosplay`, or configure and start GNSS module.

**Comment by Triangle001** [comment]
yes ,I  execute commads(rostopic echo /apollo/localization/pose ) in docker.You suggest me :

**Comment by Triangle001** [comment]
yes , I execute commads(rostopic echo /apollo/localization/pose ) in docker.You suggest me ：
1.into docker
2.start Bootstrap.sh
3.start localization modules
4.rostopic echo /apollo/localization/pose

**Comment by jilinzhou** [comment]
1. Check whether those class definitions are under /apollo/py_proto
2. Double check your environment variable PYTHONPATH to include the path to the msg class definition.

**Comment by wfgsy101** [comment]
whether the localization module work well also depends on the gps module , you may need run :
bash roscore.sh start
bash gps.sh start

**Comment by robocary** [comment]
I also have this problem, how did you solve this problem, thank   @Triangle001

**Comment by ZiwenWan** [comment]
Hi, I also got the same question when I want to record all the ros messages. Have you solved the problem?
BTW, how can I start all the nodes manually?

**Comment by storypku** [comment]
Stale issue closed. ROS based Apollo is no longer supported.
