### ISSUE TITLE
Is there the link of the source code of the modified caffe?

### ISSUE THREAD

**Issue by youluexx** [ApolloAuto/apollo#5435]
I want to get the source code and modify the code. But I could't find the download link.

Is the source code of modified caffe opened? 

If I want to define new layers and train my own data, how shoulde I do?

I found #4797 had the same question, but had no results.

**Comment by lianglia-apollo** [comment]
Current the modified caffe is not open sourced. It is provided as a .so library.

**Comment by youluexx** [comment]
Thank you for reply. 
Is there any plan to open the modified caffe? when? 
If no plans, how to add new layers? Should I compile my own .so library? I am a little confused. Hope your replay @lianglia-apollo  or others'.

**Comment by storypku** [comment]
Stale issue closed.
