### ISSUE TITLE
Weakness in instruction "How to Debug the Dreamview Start Problem"

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#5436]
**Describe the bug**
Weakness in instruction "How to Debug the Dreamview Start Problem".

**To Reproduce**
Follow the instruction. After typing 

> cmake ..

instruction tell 

> #backup pcl lib
> mkdir -p /usr/local/lib/pcl.origin
> mv /usr/local/lib/libpcl* /usr/local/lib/pcl.origin
> 
> #replace with our build
> cp -a lib/* /usr/local/lib/

**Expected behavior**

Obviously instruction 

> make

is forgotten.

**Desktop :**
 - OS: [Ubuntu 16.04 LTS]
 - Browser [Chrome]
 - Version [Apollo 3.0 (r.3.0.0)]

**Comment by zhxt** [comment]
@gladijos Yeah, you're right, good catch! 
And would you like to submit a PR for this? All contributions are welcome!

**Comment by gladijos** [comment]
@zhxt  thanks for answer! I never did it, but I'll try soon!

**Comment by zhxt** [comment]
@gladijos Great!  You can refer to [How to Contribute to Apollo](https://github.com/ApolloAuto/apollo/blob/master/CONTRIBUTING.md) and  [How to create a pull request](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_create_a_pull.md).

Feel free to let us know if you have any questions.

**Comment by storypku** [comment]
Stale issue closed.
