### ISSUE TITLE
Vehicle_Calibration

### ISSUE THREAD

**Issue by Leonardo092** [ApolloAuto/apollo#5449]
Hello there,
I am using the vehicle calibration procedure to obtain my personal "control_conf.pb.txt" (please refer to this [link](https://github.com/ApolloAuto/apollo/blob/master/modules/calibration/data/mkz_example/calibration_table.pb.txt)). What is obscure to me is the methodology behind its creation. As far as I understood, I am supposed to give commands "acceleration, speed limit, deceleration" after running 
`python modules/tools/calibration/data_collector.py`. I have two questions mainly:
1) What is the way to select reasonable values for the above variables?
2) It is mentioned in your [guide](https://github.com/ApolloAuto/apollo/blob/35e8b9e5567ba1e4a91aa798176408b534c60f78/docs/howto/how_to_update_vehicle_calibration.md) that I am supposed to run each command multiple times. What does it mean? Why?

Thanks for the attention.

**Comment by Addi2020** [comment]
I have same questions, do you know the answers now? 
Apollo 3.5.0

**Comment by apollodevcommunity** [comment]
The calibration table is speed   gas/brake ratio  acceleration   so you need to speed up and down in different acceleration. then you can get the relationship of three value. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=632
