### ISSUE TITLE
Errors in data_collector.py

### ISSUE THREAD

**Issue by Leonardo092** [ApolloAuto/apollo#5451]
Hello there,
I run into some unexpected behaviour (a bug, maybe. Not sure) when dealing with the update of vehicle calibration (please refer to [this guide](https://github.com/ApolloAuto/apollo/blob/35e8b9e5567ba1e4a91aa798176408b534c60f78/docs/howto/how_to_update_vehicle_calibration.md) ). To be concise:
1) In [file](https://github.com/ApolloAuto/apollo/blob/master/modules/tools/calibration/data_collector.py)  the variable `self.in_session` appears to be not initialized. The error displays:

**File "modules/tools/calibration/data_collector.py", line 132, in callback_canbus
    if self.in_session:
AttributeError: 'DataCollector' object has no attribute 'in_session'** 

2)Still in the same file, the variable I had the following error:

**File "modules/tools/calibration/data_collector.py", line 147, in publish_control
    if self.case == 'a':
AttributeError: 'DataCollector' object has no attribute 'case'**

I solved by adding the following piece of code at line 147:
```
        if self.vehicle_speed >= self.cmd[1]:
           self.case = 'd'
        else:
           self.case = 'a' 
```
Did I miss something before running the script or are my considerations worthy?

**Comment by freeHackOfJeff** [comment]
Hi, Could you please add try...(related exception) in this case as well, then submit a patch to fix that?

**Comment by gladijos** [comment]
Hi @Leonardo092 ! I have same issue. I fix it by adding 
`        self.case = 'a'`
`        self.in_session = False`
into data_collector.py in method:
`class DataCollector(object):`
`    def __init__(self):`

**Comment by gladijos** [comment]
Also there is one issue in sending deceleration command. I fix it with:
`        if self.case == 'a':`
`            if self.cmd[0] > 0:`
`                self.controlcmd.throttle = self.cmd[0]`
`                self.controlcmd.brake = 0`
`            else:`
`                self.controlcmd.throttle = 0`
`                self.controlcmd.brake = -self.cmd[0]`
`            if self.vehicle_speed >= self.cmd[1]:`
`                self.case = 'd'`
`        if self.case == 'd':`
`            if self.cmd[2] > 0:`
`                self.controlcmd.throttle = self.cmd[2]`
`                self.controlcmd.brake = 0`
`            else:`
`                self.controlcmd.throttle = 0`
`                self.controlcmd.brake = -self.cmd[2]`
`            if self.vehicle_speed == 0:`
`                self.in_session = False`
into data_collector.py in method:
`class DataCollector(object):`
`def publish_control(self):`

**Comment by freeHackOfJeff** [comment]
I gone through the file, looks your solution is good.  Also, this file could be refactored by isoldate usage into a method, a few code is written without following the pythonic style.

**Comment by Leonardo092** [comment]
Thanks @gladijos! My solution works as well but I will try yours in addition(especially that regarding deceleration).

**Comment by apollodevcommunity** [comment]
you shall use try..catch to check is there any exception raised in DataCollector construct.if DataCollector init successfully   shall not get these error print. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=631
