### ISSUE TITLE
Fail planning module when it got default routing request

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#5452]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04 LTS
- **Apollo installed from (source or binary)**: binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- launch dreamview with canbus, planning, routing, localization;
- choose SynnuvaleLoop map;
- start car simulator which take ControlCommand message and produce Chassis, Gps and Imu  messages;
- put car in simulator those way that car position is set on the road;
![screenshot from 2018-08-22 16-46-56](https://user-images.githubusercontent.com/28844865/44467277-21763680-a62b-11e8-9e80-375c0d868686.png)
- send default routing request POI: 1195 office

### Expectations:
- generation and visualization planning trajectory;
- generation ControlCommand;
- car movement;

### Real behaviour:
- in planning.ERROR:

> E0822 14:29:35.645706 22723 frame.cc:137] Failed to create reference line
E0822 14:29:35.645731 22723 frame.cc:361] Failed to init reference line info
E0822 14:29:35.646157 22723 planning.cc:85] failed to init frame:PLANNING_ERROR: failed to init reference line info
E0822 14:29:35.650450 22723 planning.cc:378] PLANNING_ERROR: failed to init reference line info

- in attached to planning VSCode debugger:
![screenshot from 2018-08-22 16-47-30](https://user-images.githubusercontent.com/28844865/44467284-263aea80-a62b-11e8-90b6-3f408a2585e7.png)
- crash planning module

### Additional information:
ApolloAuto is started on CPU Intel(R) Core(TM) i7-3610QE CPU @ 2.30GHz.
PCL library is recompiled according to [instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md). Also I had to fix some compilation issues in PCL branch 1.7.2.

**Comment by lianglia-apollo** [comment]
Are you using sim_control? If not, you will need to provide some localization information to the ego vehicle in some way, for example, by playing a rosbag.

**Comment by gladijos** [comment]
@lianglia-apollo I'm not using simcontrol. I'm using my own software for simulation. I provide Gps, Imu, Chassis messages and waiting for ControlCommand. Gps, Imu, Chassis data is accepted by apollo's modules fine.

**Comment by lianglia-apollo** [comment]
My suggestion is to provide localization information, add and check the output of planning logs to debug.

**Comment by gladijos** [comment]
@lianglia-apollo, you mean I should provide localization info right here? I can go step-by-step in VSCode debugging up to line with error and everything looks good in debugger.
Also I reproduce this situation on PC with CPU Intel i7-8700 CPU @ 3.20GHz and  everything works fine.

**Comment by jilinzhou** [comment]
To provide proper Gps and Imu msg for the localization module is very tricky. Take a look of data_parser.cpp, and make sure you set orientation properly. Currently the code is hard-coded to follow Novotel body frame definition somehow. To my understanding, the quaternion is constructed incorrectly (yaw angle should from East instead of North). The interesting thing is that the 90 degree is re-considered in computing heading from quaternion in common::math::quaternion.

**Comment by gladijos** [comment]
@jilinzhou Thanks a lot, I will check my quaternion math. Actually I provide not gnss driver but replace localization module cause I generate data in ros in binary format and I have no idea to place this into gnss driver scheme.

**Comment by yimzhou** [comment]
Hi @gladijos, have you solved this problem?

**Comment by Hershey988** [comment]
@lianglia-apollo I am having a similar issue when I am using SimControl. 

Running Apollo 3.0 on Ubuntu 14.04.

**Here are the steps I am taking:**
1. Start dreamview using bootstrap.sh script.
2. Choose the Mkz example vehicle.
3. Turn on SimControl. I see Localization and Chasis modules running.
4. I turn on the Planning module.
5. I turn on the Routing Module.
6. From default routing I click on the Reverse Early lane change POI.
7. The vehicle doesn't move and I see the planning module run for 7 seconds and reset and this continues.

**The planning module gives me the same errors:**
E0822 14:29:35.645706 22723 frame.cc:137] Failed to create reference line
E0822 14:29:35.645731 22723 frame.cc:361] Failed to init reference line info
E0822 14:29:35.646157 22723 planning.cc:85] failed to init frame:PLANNING_ERROR: failed to init reference line info
E0822 14:29:35.650450 22723 planning.cc:378] PLANNING_ERROR: failed to init reference line info

ApolloAuto is started on Intel® Core™ i7-2600 CPU @ 3.40GHz

**Comment by yifeijiang** [comment]
@gladijos Hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue.

**Comment by XinrRunChao** [comment]
> @lianglia-apollo I am having a similar issue when I am using SimControl.
> 
> Running Apollo 3.0 on Ubuntu 14.04.
> 
> **Here are the steps I am taking:**
> 
> 1. Start dreamview using bootstrap.sh script.
> 2. Choose the Mkz example vehicle.
> 3. Turn on SimControl. I see Localization and Chasis modules running.
> 4. I turn on the Planning module.
> 5. I turn on the Routing Module.
> 6. From default routing I click on the Reverse Early lane change POI.
> 7. The vehicle doesn't move and I see the planning module run for 7 seconds and reset and this continues.
> 
> **The planning module gives me the same errors:**
> E0822 14:29:35.645706 22723 frame.cc:137] Failed to create reference line
> E0822 14:29:35.645731 22723 frame.cc:361] Failed to init reference line info
> E0822 14:29:35.646157 22723 planning.cc:85] failed to init frame:PLANNING_ERROR: failed to init reference line info
> E0822 14:29:35.650450 22723 planning.cc:378] PLANNING_ERROR: failed to init reference line info
> 
> ApolloAuto is started on Intel® Core™ i7-2600 CPU @ 3.40GHz

Have you solved your problem? I met the same problem, helping!
