### ISSUE TITLE
IMU Calibration Tool doesnt provide results- Suspect missing code in sensor_calibration.sh

### ISSUE THREAD

**Issue by nandita05** [ApolloAuto/apollo#5472]
### System information

OS Platform and Distribution : Linux Ubuntu 14.04
Apollo installed from source
Apollo version: 3.0 (Code cloned from Master branch)

### Steps to reproduce the issue:
- Download the calibration tool : https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip
- Inside docker, start Apollo HMI using command:
**bash scripts/bootstrap.sh**
- Turn on GPS, CAN, Velodyne, Camera, Radar sensors from Module Controller in Dreamview HMI
- Inside docker terminal, start IMU-Vehicle calibration tool using command:
**cd /apollo
bash scripts/sensor_calibration.sh imu_vehicle**

Observations:
Apollo starts executing all extrinsic calibrations in following series:

1. Camera-Camera Calibration
2. Lidar-Camera Calibration
3. Radar-Camera Calibration
4. Radar-Lidar Visualizer

All the calibrations run successfully with relevant output images generated in validation folder & extrinsics.yaml files updated in relevant folder under "/apollo/modules/calibration/data/mkz_/". But,no modification or changes are made to vehicle_imu_extrinsics.yaml file. 

### Supporting materials (screenshots, command lines, code/script snippets):

Here's code from sensor_calibration.sh script which doesn't have anything related to imu in the code:

[sensor_calibration.sh.txt](https://github.com/ApolloAuto/apollo/files/2315760/sensor_calibration.sh.txt)

[imu-cal-issue.zip](https://github.com/ApolloAuto/apollo/files/2315770/imu-cal-issue.zip)

**Comment by nandita05** [comment]
I tried using the new sensor_calibration.sh script which was updated to master branch 3 days ago, but on running the imu_vehicle calibration, following error message is seen on terminal:
/apollo/modules/calibration/imu_car_calibrator/imu_car_calibrator: error while loading shared libraries: libceres.so.1: cannot open shared object file: No such file or directory

Is there any update on this issue ?

**Comment by xinwf** [comment]
@nandita05 hi, where to download the newest calibration tool?

**Comment by jinxiao1231** [comment]
So, have you solved the problem? @nandita05  I have met the same with you.

**Comment by snehagn** [comment]
@CCodie @jinxiao1231 Try giving executable permissions to the lidar_imu_callibrator binary and running it with the --flagfile=/../../conf/vehicle_imu_calibrator.conf" parameter, if using "bash sensor_calibration.sh" fails. You should install libceres in the docker environment and run the calibrations: "sudo apt-get install libceres-dev".

**Comment by devynliu** [comment]
hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by wf1024966** [comment]
hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by wf1024966** [comment]
> hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by jay80253504** [comment]
> > hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!
> 
> hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
