### ISSUE TITLE
Question about Radar calibration

### ISSUE THREAD

**Issue by daviduhm** [ApolloAuto/apollo#5479]
From the [calibration documentation](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md), the required topics for Radar-to-Camera calibration are camera and ins, but there is no radar topic needed. 

1. How does the Radar-to-Camera calibration get the extrinsics for the radar relative to the camera without radar message? 

2. Who's responsible for generating radar_front_extrinsics.yaml (extrinsic parameter of the radar relative to the lidar) ? The radar-to-camera calibration tool outputs radar_extrinsics.yaml, but not radar_front_extrinsics.yaml. Do we just manually create this file based on the extrinsic parameter of the radar relative to the lidar and the extrinsic value of the radar relative to the camera?

Thanks!

**Comment by johndoe95** [comment]
@daviduhm Hi，I have the same trouble, have you solved it ?

**Comment by daviduhm** [comment]
No, haven't heard of any responses back yet. Sadly, hard to find out because Apollo only provides calibration toolkit as binaries. We don't have source code to look into..

**Comment by johndoe95** [comment]
Hi @daviduhm 
Have you successfully ran the toolkit and got the extrinsics. 
BTW, do you have any other method to calibrate radar and camera, thank you !

**Comment by CCodie** [comment]
Hi @daviduhm @johndoe95 , I'm now trying to calibrate Camera & Radar sensors.
But Radar-to-Camera calibration tool from [Apollo 2.0 Sensor Calibration Guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md) seems that doesn't work for me. Do you guys run that tool or find any other method for Radar/Camera calibration? Thanks !

**Comment by JonathanJones92** [comment]
@natashadsouza @weidezhang @techoe  Our team also pending on this issue, 2.0 sensor calib is not working.

**Comment by mc-android-developer** [comment]
Hi Apollo team,
I'd like to attract attention to this issue as it's matters for a number of people.
According to [calibration guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md) Radar-to-Camera Calibration tool only consumes camera images (/apollo/sensor/camera/traffic/image_short) and odometry (/apollo/sensor/gnss/odometry,ins_stat). So no reading input from Radar required as of guide.
How is that possible to calibrate between Camera/Radar without using Radar data at all?

**Comment by mc-android-developer** [comment]
@daviduhm As of your 2nd question my guess is that we are supposed to get configuration(tf/extrinsics) between lidar and camera at first as result of Camera-to-LiDAR Calibration process (as explained [here](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md)). After that we get configuration(tf/extrinsics) between radar and camera as result of Radar-to-Camera Calibration process. If we have them both, we have camera as common reference frame and tf between Lidar and Radar should be easy to get.
This is how I see it. It'd be great to get confirmation from Apollo team on that?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
