### ISSUE TITLE
LiDAR标定服务可以支持更多的型号吗？比如hesai pandar系列的。

### ISSUE THREAD

**Issue by zhanyifei** [ApolloAuto/apollo#5482]

**Comment by freeHackOfJeff** [comment]
We have already support Pandora of Hesaitech for camera and Lidar with calibration enabled by default.

**Comment by apollodevcommunity** [comment]
可以的，因为不同的LiDAR采集到的数据会转换成统一的格式用来做标定。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=627
