### ISSUE TITLE
sensor and ros

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5484]
Hello everyone. Excuse me
     请问在apollo中，对于摄像头、激光雷达等设备来说，其驱动程序是在ros里吗？然后每个设备会作为ros里的一个节点来发布采集到的数据，这些数据是共享的吗？如果是共享的，什么时候才会丢弃呢？如果不是共享的，那是处理数据的模块拿走之后就丢弃了吗？
      还是说具体的设备驱动程序如.ko，都是动态安装到RTOS里的呢？这样的话，这些设备驱动程序是设备生产厂商给的吗？

**Comment by breakisx** [comment]
@poutyface @weidezhang @bigwhite @mbinna @all2one @ Thank you !

**Comment by breakisx** [comment]
在apollo 3.0中提到了ASU（Apollo传感器单元），如果有ASU,那是不是摄像头、激光雷达、gps等都直接接到ASU上？没有的话就要接到IPC上呢？

**Comment by quning78** [comment]
> 请问在apollo中，对于摄像头、激光雷达等设备来说，其驱动程序是在ros里吗？然后每个设备会作为ros里的一个节点来发布采集到的数据，这些数据是共享的吗？如果是共享的，什么时候才会丢弃呢？如果不是共享的，那是处理数据的模块拿走之后就丢弃了吗？

通过topic发送出来的消息，所有感兴趣的node都可以subscribe。共享这个词不太准确，请参考原生ROS本身的pub/sub传输模式。

> 还是说具体的设备驱动程序如.ko，都是动态安装到RTOS里的呢？这样的话，这些设备驱动程序是设备生产厂商给的吗？

多数的设备都不需要额外的ko，如果有特殊需求的，确实需要厂商提供

> 在apollo 3.0中提到了ASU（Apollo传感器单元），如果有ASU,那是不是摄像头、激光雷达、gps等都直接接到ASU上？没有的话就要接到IPC上呢？

如果有ASU的话，建议所有的sensor都连接到ASU上，但不是强制的要求。
