### ISSUE TITLE
offline_lidar_visualizer_tool failed

### ISSUE THREAD

**Issue by IneverStop** [ApolloAuto/apollo#5485]
### System information
- **OS Platform and Distribution **: Linux Ubuntu 18.04
- **Apollo installed from **: source
- **Apollo version **: 3.0

Hello.
I am goint to use offline perception module.Here is my operating:
- roslaunch velodyne export_pcd_offline.launch
- rosbag play --clock demo-sensor-demo-apollo-1.5.bag
       It generate many pcd files but also report some [ERROR] [.......]: two unit distance is wrong, and some [WARN] [.......]: Can not find transform. ...... Error info: Lookup would require extrapolation into the future. Requested time xxxx but the latest data is at time xxxxx, when looking up transform from frame [velodyne64] to frame [world]. canTransform returned after 0.101546 timeout was 0.1.
      Most pcd files had been created.Only some of them report these ERROR or WARN.
- python gen_pose_file.py /apollo/data/pcd
- bazel build -c opt //modules/perception/tool/offline_visualizer_tool:offline_lidar_visualizer_tool
- /apollo/bazel-bin/modules/perception/tool/offline_visualizer_tool/offline_lidar_visualizer_tool

Here is staff that shows on the command line:

> [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[NVBLAS] Cannot open default config file 'nvblas.conf'
[NVBLAS] Config parsed
[NVBLAS] CPU Blas library need to be provided
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0824 10:51:09.435104 20265 lidar_process.cc:51] I
E0824 10:51:09.435174 20265 lidar_process.cc:59] II
I0824 10:51:09.435192 20265 lidar_process.cc:247] get and Init hdmap_input succ.
E0824 10:51:09.435196 20265 lidar_process.cc:65] III
I0824 10:51:09.435367 20265 lidar_process.cc:268] Init algorithm plugin successfully, roi_filter_: HdmapROIFilter
E0824 10:51:09.440587 20265 common.cpp:113] Cannot create Cublas handle. Cublas won't be available.
E0824 10:51:09.445430 20265 common.cpp:120] Cannot create Curand generator. Curand won't be available.
.
.
.  #some thing like caffe layers.
.
I0824 10:51:09.449973 20265 layer_factory.hpp:79] Creating layer input
I0824 10:51:09.450042 20265 net.cpp:94] Creating Layer input
I0824 10:51:09.450070 20265 net.cpp:402] input -> data
F0824 10:51:09.456082 20265 syncedmem.hpp:18] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
Aborted (core dumped)

Help wanted.

**Comment by techoe** [comment]
It seems the CUDA was not installed correctly. Apollo supports Ubuntu 14
