### ISSUE TITLE
utilize proto file in c++

### ISSUE THREAD

**Issue by hlchen1043** [ApolloAuto/apollo#5488]
To whom it may concern,
We are trying to utilize Apollo protobuf topic in C++. When including the header file for protobuf we used the following script:
```#include <ros/ros.h>
#include <modules/canbus/proto/chassis.pb.h>
#include <modules/localization/proto/localization.pb.h>
#include <modules/perception/proto/perception_obstacle.pb.h>
#include <string>
#include <math.h>
```
When I run the cmake file for C++, it returns the following error:
```
hlchen@in_dev_docker:/apollo/catkin_ws/src/DSRC/build$ make
[  1%] Building CXX object CMakeFiles/openAV_DSRC.dir/bsm/CID_BSM_Receiver.cpp.o
In file included from /apollo/catkin_ws/src/DSRC/bsm/CID_BSM_Receiver.cpp:23:0:
/apollo/catkin_ws/src/DSRC/bsm/dsrc_apollo.h:2:45: fatal error: modules/canbus/proto/chassis.pb.h: No such file or directory
 #include <modules/canbus/proto/chassis.pb.h>
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/openAV_DSRC.dir/bsm/CID_BSM_Receiver.cpp.o] Error 1
make[1]: *** [CMakeFiles/openAV_DSRC.dir/all] Error 2
make: *** [all] Error 2

```

Which by theory I thought it shouldn't happen. According to the protobuf documentation, it says when using protobuf file with c++, just replace `.proto` with `.pb.h` and it should work.

Does anyone have any suggestions?

Thank you!

**Comment by lianglia-apollo** [comment]
bazel build is the only method we currently support. For general questions on how to make protobuf, I suggest post on protobuf community for questions.

**Comment by hlchen1043** [comment]
Hi lianglia,
Thanks for the reply! Does that mean that I need to build Apollo first then build my code?

Thank you!

**Comment by lianglia-apollo** [comment]
My suggestion is to use bazel build your added files. You can find examples in other folders on how defined protos are used as dependent libraries, for example `https://github.com/ApolloAuto/apollo/blob/master/modules/planning/BUILD`.

**Comment by jilinzhou** [comment]
My guess: The error msg shows that the path to the header files are not configured properly in your CMakeList.txt. Configure cmake build in verbose mode and check "-I" flag in the console output. You can figure it out.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
