### ISSUE TITLE
Cannot Launch Dreamview on 3.0

### ISSUE THREAD

**Issue by yimzhou** [ApolloAuto/apollo#5499]
Hello Apollo developers, 

- Linux Ubuntu 16.04
- Apollo installed from source
- Apollo version 2.0

- I am new to Apollo and I want to upgrade Apollo from version 2.0 to 3.0. I followed the following steps mentioned in #1768 :
`$ git pull origin master`
`$ docker rm [container id]`
`$ docker rmi [image id]`
`$ bash docker/scripts/dev_start.sh`
`$ bash docker/scripts/dev_into.sh`
`$ cd /apollo`
`$ bash apollo.sh clean`
`$ bash apollo.sh build_no_perception dbg`

The build passed successfully, with `bazel-bin/modules/dreamview/dreamview` and `bazel-bin/modules/monitor/monitor` existing. When I first ran `$ bash scripts/bootstrap.sh start`, the output was 
`Start roscore...`
`Module monitor is already running - skipping.`
`Launched module dreamview.`
`Dreamview is running at http://localhost:8888`
with the output `CMD` of `$ ps` including `roscore`, `monitor`, `dreamview`. But after opening the page at `http://localhost:8888` once, which indicateed unable to connect, the output `CMD` of `$ ps` only included `roscore` and `monitor`. And when I run `$ bash scripts/bootstrap.sh stop`, it showed
`Module dreamview is not running - skipping.`
`Successfully stopped module monitor.`
`roscore: stopped`
And I run `$ bash scripts/bootstrap.sh start` again, the error information was
`Start roscore...`
`Launched module monitor.`
`/apollo/scripts/apollo_base.sh: line 224: 28872 Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/dreamview.out 2>&1
Could not launch module dreamview. Is it already built?`

Could anyone help me to solve this problem? Thanks!

**Comment by zhxt** [comment]
Since you got the error 'Illegal instruction', you may need to have a look at [this](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md) or issue #3615 .

PS: If your local copy was cloned from your own fork, you may need to rebase upstream master branch to get the latest code.

**Comment by yimzhou** [comment]
@zhxt I tried [this](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md) and compiled pcl from source, but the command `bash scripts/dreamview.sh` got the output `Could not launch module dreamview. Is it already built?
` and when I ran `bash scripts/dreamview.sh start_fe`, it was shown `/apollo/scripts/apollo_base.sh: line 302: /apollo/modules/dreamview/dreamview: No such file or directory
`. Could you please give me any other suggestion?

**Comment by zhxt** [comment]
Please try to rebuild apollo and check again.

**Comment by yimzhou** [comment]
@gladijos I made it by following [this](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md) instruction.

**Comment by Iqbalparvi** [comment]
@in_dev_docker:/apollo$ cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0211 14:36:33.015163 24090 global_data.cc:153] [cyber_recorder] host ip: 10.9.29.35
E0211 14:36:33.035611 24090 record_file_reader.cc:33] [cyber_recorder] File not exist, file: docs/demo_guide/demo_3.5.record
E0211 14:36:33.035670 24090 record_reader.cc:32] [cyber_recorder] Open record file failed, file: docs/demo_guide/demo_3.5.record
earliest_begin_time: 18446744073709551615, latest_end_time: 0, total_msg_num: 0
E0211 14:36:33.035727 24090 play_task_producer.cc:176] [cyber_recorder] begin time are equal or larger than end time, begin_time_ns=18446744073709551615, end_time_ns=0
can any give solution for me please..............

**Comment by xiaoxq** [comment]
Could you check if the file exists? **/apollo/docs/demo_guide/demo_3.5.record**
If not, please try "git lfs fetch" to pull it from remote LFS.

**Comment by Iqbalparvi** [comment]
@xiaoxq yes I solve that issue on my laptop thanks...but in my lab PC I faced problem that localhost:8888 OR Dreamview cannot run on browser but cyber_recorder run  the inform is below
@in_dev_docker:/apollo$ bash scripts/bootstrap.sh start
**nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information**
mi759@in_dev_docker:/apollo$ cyber_recorder play -f demo_3.5.record 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0218 16:39:18.184017  5147 global_data.cc:153] [cyber_recorder] host ip: 10.9.29.35
file: demo_3.5.record, chunk_number: 3, begin_time: 1546888377338834894 (2019-01-08 06:12:57), end_time: 1546888422886740928 (2019-01-08 06:13:42), message_number: 61615
earliest_begin_time: 1546888377338834894, latest_end_time: 1546888422886740928, total_msg_num: 61615

Please wait 3 second(s) for loading...
Hit Ctrl+C to stop, Space to pause, or 's' to step.

[RUNNING] Record Time: 1546888422.887    Progress: 45.548 / 45.548
play finished.
.....

**Comment by apollodevcommunity** [comment]
dreamview alreay launched at the first time.you shall check dreamview.out information to debug the core dump reason. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=626
