### ISSUE TITLE
bash: /apollo/third_party/ros/setup.bash: No such file or directory

### ISSUE THREAD

**Issue by iweey** [ApolloAuto/apollo#55]
when i run bash docker/scripts/dev_into.sh
i get the error:
bash: /apollo/third_party/ros/setup.bash: No such file or directory

**Comment by qiankunzhu** [comment]
You can ignore it if the first time. just try 'bash apollo.sh build' which will automatic pull the ros dependency (https://github.com/ApolloAuto/apollo/blob/master/WORKSPACE.in ,line 180) .  If after that this happens again, please describe your operation steps, we can check it together.

**Comment by wanglei828** [comment]
I think @iweey run the command "bash docker/scripts/dev_into.sh" with "root" user. This issue has been fixed in new dev image.
