### ISSUE TITLE
There was a problem running to the last step：ros play demo_2.5.bag

### ISSUE THREAD

**Issue by JustWannaHugU** [ApolloAuto/apollo#5502]
Hello Apollo developers,

Linux Ubuntu 14.04

Apollo installed from source

Apollo version 3.0

I am new to Apollo and I want to run Apollo using docker-ce on my camputer，I have successfully installed the software---DOCKER already

`amber@amber-ThinkPad-S3-S440:~/apollo$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
amber@amber-ThinkPad-S3-S440:~/apollo$ 
`
I followed the  Tutorial 【 Apollo without hardware】steps continue input the command  :

`
$ bash docker/scripts/release_into.sh
$ rosbag play demo_2.5.bag

`
But the screen shows：

amber@amber-ThinkPad-S3-S440:~/apollo$ bash docker/scripts/release_into.sh
amber@in_release_docker:/apollo$ rosbag play demo_2.5.bag
/tmp/apollo-platform/ros/ros_comm/rosbag/src/player.cpp:125 Player::publish() [ INFO] [1535266466.031615240]: Opening demo_2.5.bag
/tmp/apollo-platform/ros/ros_comm/rosbag/src/play.cpp:176 main() [FATAL] [1535266466.032106787]: Error opening file: demo_2.5.bag
amber@in_release_docker:/apollo$ 

After querying the previous question, I ran the following three lines of instructions.
1                 ./docker/scripts/dev_start.sh
2                `./docker/scripts.dev_into.sh`
3                `./apollo.sh build`(error appear)

`amber@amber-ThinkPad-S3-S440:~$ cd apollo
amber@amber-ThinkPad-S3-S440:~/apollo$ ./docker/scripts/dev_start.sh
[sudo] password for amber: 
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20180806_1111 ...
dev-x86_64-20180806_1111: Pulling from apolloauto/apollo
Digest: sha256:dc7daeb9bf1b18097dd39ce72840e18eb382c35a25109adea0da2c425e09be9e
Status: Image is up to date for apolloauto/apollo:dev-x86_64-20180806_1111
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:68ab11db001d315fcd896a06d9100e6fa6ac0f2d578b6988a4e194b02cee62da
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
e0ae94de2c3496a153f0044daf54b2974a135d54b08802a913c9f71eb69c4ef7
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_loop-latest
6a52ee08da643b6680df728cf042e5a6a041897fbd5e1a66dd609a22ebb7c65d
modprobe: FATAL: Module nvidia not found.
modprobe: FATAL: Module nvidia-uvm not found.
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:c9d98694aa3ff68d069d05308ad1562b96c2f069bf17e949e3b26772fb2023b9
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
db2e65d4aa4cfd36bb878ebdf6f9b28b9eb971d67b54bc2e3305119f84fe47ae
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
bc874e0e656324cd15d2056167904d9a8ca735eb5b0324fb35d22844b398dee8
[INFO] Starting docker container "apollo_dev" ...
8142c17caa998020c0e061a0e6ccdad9d6b6c8bcf08474d1e815aeb12f6d6c36
Adding group `amber' (GID 1000) ...
Done.
Adding user `amber' ...
Adding new user `amber' (1000) with group `amber' ...
The home directory `/home/amber' already exists.  Not copying from `/etc/skel'.
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
amber@amber-ThinkPad-S3-S440:~/apollo$ 
`
`amber@amber-ThinkPad-S3-S440:~/apollo$ ./docker/scripts/dev_into.sh

amber@in_dev_docker:/apollo$ 
`
`amber@in_dev_docker:/apollo$ ./apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
WARNING: Failed to get information about path, for bazel-apollo, skipping: /root/.cache (Permission denied)
ERROR: /root/.cache (Permission denied)
============================
[ERROR] Build failed!
[INFO] Took 11 seconds
============================
amber@in_dev_docker:/apollo$ 
`

I 'll appreciate if you could help me ！thank you read this！！！

**Comment by mickeyouyou** [comment]
`ERROR: /root/.cache (Permission denied)`
in build step, scripts try to access root directory `/root/.cache`, It is recommended that you clear the cache （`bazel clean`）and try to compile again.
