### ISSUE TITLE
Apollo 3.0 多传感器标定指南

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#5503]
在Apollo 3.0里，包含了超声波雷达，激光雷达（VLP16 HSE64 etc..） USB_CAM， Conti Radar。 这些传感器都需要将 local coordinate转为world coordinate。通过已知的资料，Apollo以 车顶上的HSE64 为基准，其他的传感器转到HSE64 再到IMU 到world，HSE64直接转到world。开发过程中遇到的几点问题希望百度的同事能够帮忙解答一下：

1. 如果仅使用VLP16 并且把VLP16当做 HSE64来用，将其他传感器的坐标系转为VLP16坐标系再转到world，那么想问一下VLP16的旋转参数放在哪里呢？ 同时我也没有找到从哪里调用了激光雷达的旋转参数。只是看到了radar和USB_CAM的旋转参数。
2.把所有的坐标系转为IMU坐标系后，IMU坐标系是怎么转为世界坐标系的呢？这部分代码和旋转矩阵也没有找到，还想问一下百度的同事和其他开发者。

**Comment by JonathanJones92** [comment]
@bigwhite @weidezhang @all2one   THX

**Comment by xmyqsh** [comment]
@JonathanJones92 
这个问题解决了吗？

apollo的坐标系统应该是这样的

world --- novatel/imu/rear axle/localization(base_link) --- | ---- velodyne64/lidar ---- camera
                                                                                                | ---- radar

novatel/imu 到 world的坐标转换 是通过localization定位模块得到的 car 的 pose 确定的，imu 被定义在 vehicle reference point(VRP) 上。这个位姿即车辆位姿是随运动变化的。
其他坐标关系通过外参标定得到（当然也可以通过结构关系估一个大概值），相机有额外内参。并且这些位姿关系属于结构位姿，是保持不变。 

在localization定位过程中，gnss ant 和 lidar map 匹配都可以获得世界坐标，并配合imu提供的加速度和角速度信息，实现融合定位，具体定位算法见paper，核心算法没有开源，只提供了动态链接库。

其中，gnss ant, novatel/imu, velodyne64 的坐标系定义以及位置关系在配置文件[param](https://github.com/ApolloAuto/apollo/tree/r3.0.0/modules/localization/msf/params)里，具体数值需要calibration，也可以根据结构关系粗略估计。

另外，elo模块提供了另一种基于camera和imu/gps融合的低成本高精定位方案，也没有开源。

换成自己硬件的话，标定好内外参配置文件就可以了。



如果我理解有误的话，请帮我指出来

**Comment by mickeyouyou** [comment]
thanks @xmyqsh
