### ISSUE TITLE
Why concrete radat data structure used? Abstract one should be better

### ISSUE THREAD

**Issue by deanyanqing** [ApolloAuto/apollo#5504]
Currently not easy to integrate radar other than Conti because Perception module relay on the concrete type. Actually there is abstract radar data structure in drivers., but neither conti_radar nor racobit_radar use it.  Is there  any good reason to design like that? Or anything I misunderstood?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
