### ISSUE TITLE
Any bag file with topic radar & lidar ?

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5506]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: From source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: ver 3.0

Hello Apollo team,
I'm trying to run Fusion Obstacle Visualization Tool after running the Offline Perception Visualizer.

It seems that Fusion Obstacle Visualization Tool needs the bag file with lidar and radar data.
**Can I get some example bag file with lidar and radar data?**

I have two bag files (demo-sensor-demo-apollo-1.5.bag , demo_2.5.bag) but these do not seem to have both lidar & radar data in the same file.

Thanks!

**Comment by mickeyouyou** [comment]
you can find radar data from topic `/apollo/sensor/conti_radar` in bag `demo_2.5.bag`. lidar data is huge.

**Comment by fanghaos2014** [comment]
I have the same question with you. Have you solved yet?

**Comment by CCodie** [comment]
@fanghaos2014 I didn't solved yet. If you solve it, I would appreciate it if you let me know.
@mickeyouyou 
Thank you for the reply!
I have the two files, one with the radar (`demo_2.5.bag`) and one with the LiDAR (`demo-sensor-demo-apollo-1.5.bag`).
But can I get a bag file that contains both topics at the same time?

**Comment by techoe** [comment]
Since we changed OS to Cyber RT in Apollo 3.5, we will provide different bag with multiple sensor data.

**Comment by pedroexenberger** [comment]
> Since we changed OS to Cyber RT in Apollo 3.5, we will provide different bag with multiple sensor data.

Hi! Is there any of such bag files with multiple sensor data already? Apparently, demo_3.5.record (the only .record file mentioned for apollo > 3.5 I could find in the repo) does not have multiple sensor data. I'm really struggling into start using dreamview and the apollo software stack without a simple and complete dataset.

Thank you in advance

**Comment by daohu527** [comment]
Thanks for your advice. We will evaluate whether to add this feature and feedback soon.
