### ISSUE TITLE
Types of map in modules/map/data directory

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5507]
Hi Guys,

I generated a new map base_map.xml and created the sim and routing map using the scripts given in the [map generation link](https://github.com/ApolloAuto/apollo/tree/master/modules/map/data).

I was able to successfully get the generated map on the dreamview interface. 

However I would like to know the role of each file inside the map/data directory.

Can anybody please give me a brief or any documentation explaining the role of each file. 

Thank you,
KK

**Comment by gladijos** [comment]
@kk2491 there is "Difference between base_map, routing_map and sim_map"  section in [Map Data Readme](https://github.com/ApolloAuto/apollo/tree/master/modules/map/data) that you linked. Is it clear for you?

**Comment by kk2491** [comment]
@gladijos I have gone through the Map Data Readme, however some of the points are not clear to me.

base_map.xml - complete map used to generate sim_map and routing_map - Is there any script to convert base_map.xml to base_map.txt file. 

routing_map.bin - Gives the topology of the lane. routing_map.txt - readable version of routing_map.bin ?

sim_map.bin - Used for dreamview visualization. I believe sim_map.txt is the readable version of sim_map.txt?

Thank you,
KK

**Comment by gladijos** [comment]
@kk2491 
1. as I know apollo can you base_map.xml map instead of base_map.txt. I saw this in one issue's answer
2. I hope yes. Everything sign on it
3. same as 2.

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
