### ISSUE TITLE
About Perception moudle question

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5508]
Dear apollo developer,
we have a question about perception module,
platform:
os: ubuntu 16.04
apollo version: 3.0
about module : perception

question description:
we have use RTK planning mode to make our vechile run on the record way,
now ,we want to use only one Camera as our perception sensor and HDmap to complete perception module,and output right information as prediction and planning module's input data.
we know that in apollo 3.0, perception module input data is  Radar data and Image data,

we read the documents learn that ,
1.radar data+image fusion to make trajectory estimation as prediction input
2.image data create lane + tailgating to make lane as prediction module input
document address:https://github.com/ApolloAuto/apollo/blob/master/docs/specs/perception_apollo_3.0.md
perception module framework:
<img width="1065" alt="perception_flow_chart_apollo_3 0" src="https://user-images.githubusercontent.com/19250516/44646601-23b30900-aa0e-11e8-8b9c-bc6c86e3ee92.png">

we just want to know，can we just use one Camera sensor and HDmap to run perception module successfully?
that means,
1.image data to make trajectory estimation as prediction input
2.image data to create lane as prediction module input

if Yes, when use one camera sensor, Can the perception module output  the 3D obstacle tracks with the heading, velocity and classification information? can we set the DGA file to just use camera node? 
DGA file: apollo-master/modules/perception/conf/dag_streaming_lowcost.config

**Comment by techoe** [comment]
Thank you for the question! Need more features (such as visual SLAM, more accurate object and road estimation) for the single camera autonomous driving with restricted functions (no lane change, turns).
