### ISSUE TITLE
How can I use my usb_cam?

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5509]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: From source (branch --r3.0.0)
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Issue
Hello guys, I have a usb camera and I want to know how to use it in Apollo.

The Apollo platform seems to support usb camera.
(e.g. In `apollo.sh` build option, there is `build_usbcam`. But I don't know  what to do after I build it.)

Could you explain step-by-step how to install usb camera and how to use it (viewing video on Dreamview or any tool) ?
Or is there anything I can refer to this ?

Thanks !

**Comment by CCodie** [comment]
Add,

This is my rostopic list while I run dreamview in simcontrol mode.
And there is no topic about usb camera, additional steps seem necessary.
```
apollo@in_dev_docker:/apollo$ rostopic list
/apollo/canbus/chassis
/apollo/canbus/chassis_detail
/apollo/control
/apollo/control/pad
/apollo/drive_event
/apollo/guardian
/apollo/hmi/voice_detection_request
/apollo/hmi/voice_detection_response
/apollo/localization/msf_gnss
/apollo/localization/msf_lidar
/apollo/localization/msf_sins_pva
/apollo/localization/msf_status
/apollo/localization/pose
/apollo/monitor
/apollo/monitor/static_info
/apollo/monitor/system_status
/apollo/navigation
/apollo/perception/lane_mask
/apollo/perception/obstacles
/apollo/perception/traffic_light
/apollo/planning
/apollo/prediction
/apollo/relative_map
/apollo/routing_request
/apollo/routing_response
/apollo/sensor/camera/obstacle/front_6mm
/apollo/sensor/camera/traffic/image_long
/apollo/sensor/camera/traffic/image_short
/apollo/sensor/conti_radar
/apollo/sensor/delphi_esr
/apollo/sensor/gnss/best_pose
/apollo/sensor/gnss/corrected_imu
/apollo/sensor/gnss/gnss_status
/apollo/sensor/gnss/imu
/apollo/sensor/gnss/ins_stat
/apollo/sensor/gnss/ins_status
/apollo/sensor/gnss/odometry
/apollo/sensor/gnss/raw_data
/apollo/sensor/gnss/rtk_eph
/apollo/sensor/gnss/rtk_obs
/apollo/sensor/mobileye
/apollo/sensor/velodyne16/compensator/PointCloud2
/apollo/sensor/velodyne64/PointCloud2
/apollo/sensor/velodyne64/VelodyneScanUnified
/apollo/sensor/velodyne64/compensator/PointCloud2
/rosout
/rosout_agg
/tf
/tf_static
/velodyne_nodelet_manager/bond
```

**Comment by mickeyouyou** [comment]
these three topics are from usb_cam 
```bash
/apollo/sensor/camera/obstacle/front_6mm
/apollo/sensor/camera/traffic/image_long
/apollo/sensor/camera/traffic/image_short
```

**Comment by rgunjala93** [comment]
Hey @CCodie When you plug in the cameras to the IPC and in a terminal run `$ ls /dev/video` what do you see?

**Comment by CCodie** [comment]
@mickeyouyou Thanks for the reply! Can I get some information for how to use usb_camera?
First, I want to make sure that it is installed properly and I want to see some videos using it.

@rgunjala93 Hi, the contents are shown below.
```
apollo@apollo:~$ ls /dev/video*
/dev/video0
```
I previously received image data from my usb camera with ROS outside the apollo image. So I think my usb camera can works with ROS.

**Comment by gladijos** [comment]
@CCodie I think you shouldn't you your camera outside from apollo's container. But if you have to you can refer to #4892

**Comment by rgunjala93** [comment]
@CCodie If this is the recommended IPC and there is no webcam on the computer, then the computer is picking up the camera. Inside the Apollo docker, you can roscd to _usb_cam_ package and look at the launch file. I think there's a launch file called _start_one_leopard.launch_ that you can use to test the camera inside Apollo docker.  Inside the launch file make sure that the device it is trying to open is _/dev/video0_. I think the launch file by default tries to open something like _/camera/short_ or _/camera/long_. In order for this to work, udev rules need to be set but try changing the camera name to _/dev/video0_ inside _start_one_leopard.launch_ and launch it like you would launch a ROS launch file i.e. `$ roslaunch usb_cam start_one_leopard.launch`

**Comment by CCodie** [comment]
Hi @gladijos . It seems to be very helpful when I try to use the camera outside the docker image. But now I'm trying to run inside the docker. Anyway thanks for the reply :)

Hi, @rgunjala93 . I'm appreciate for your detail reply! I'm actually installing the apollo kernel and platform for the test on my personal PC, not the reference IPC. But until now it seems to be okay to install without problems.
For the usb camera, it seems that there's no problem for the computer to recognize the camera. As you have mentioned, I'll take a closer look at the launch files and then I'll tell you about the progress.

**Comment by CCodie** [comment]
@johndoe95 Hi, I solved that problem with modifying the launch file.
I'm now using `one Leopard camera` with modified launch file.
The most simple solution is **match your device with device param in launch file**.
e.g. If your usb camera is `/dev/video0`, you can modify your launch file param to `/dev/video0`.

**Comment by johndoe95** [comment]
Hi, @CCodie, thank you very match!

**Comment by dt-developer1** [comment]
I am trying to use laptop webcam  as usb camera. I changed the camera dev in conf as /dev/video0. but i am getting folowwing error when launching camera.launch 

[usb_cam]  E0701 12:39:26.911983 25095 usb_cam.cc:867] [mainboard]Wrong Buffer Len: 1843200,raw_image->width * raw_image->height: 2073600, dev: /dev/video0
[usb_cam]  E0701 12:39:26.949627 25095 camera_component.cc:86] [camera]Running

Also am not getting video in Dreamviewer and cyber_visualizer. Is there any other configurations need to be changed for using laptop webcam?

**Comment by whj-cmd** [comment]
[mainboard]Wrong Buffer Len: 114264, dev: /dev/camera/front_6mm
