### ISSUE TITLE
How to use change the prediction.cc files to change the input from perception?

### ISSUE THREAD

**Issue by RamboRick** [ApolloAuto/apollo#5514]
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I want to change the function to make the perception don't have the ability detect the obstacles.
The prediction.cc files have the a function of inserting obstacle. I have delete this function but the simulation in the cloud is still success. I want to know the relation between these two. And what module ( cc files) could make a effect about failure to detect obstacle.

**Comment by gladijos** [comment]
@fanghaos2014 please concrete what you change in sources. Usually there are a lot of checks in apollo's modules. If you delete one of them another will work :)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
