### ISSUE TITLE
What's the average computation time to solve a qp_spline_referenceline_smoother

### ISSUE THREAD

**Issue by waverider995** [ApolloAuto/apollo#5528]
Hi,

To smooth a reference line, normally how many knots you have and what's the average computation time with qpOASES?

Thanks a lot

**Comment by jilinzhou** [comment]
1. The number of knots depends on the max length of each spline.
2. The average computation time depends on your hardware (number of cores, cpu speed, memory, etc.)

**Comment by waverider995** [comment]
Thanks for the reply.

For instance, a 100m curve with 100 splines, running on your AVs, it takes dozens of milliseconds or seconds?

I have tried cvxopt in python as well as qpOASES in c++. Cvxopt takes 50 ms while qpOASES takes 5s to solve the same question.

**Comment by lianglia-apollo** [comment]
If you can run it on cvxopt, please let us know the time consumption. Thanks! @waverider995

**Comment by waverider995** [comment]
cvxopt converts automatically a QP to a SCOP, which might be faster in this case

**Comment by lianglia-apollo** [comment]
Yes, it could be faster. CXVOPT has an c interface api (https://cvxopt.org/userguide/c-api.html). If you are interested in improving the optimization performance, please feel free to add a cvxopt-based solver into Apollo.

**Comment by lianglia-apollo** [comment]
According to a reference here (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.720.6815&rep=rep1&type=pdf), qpOases performs better than cvxgen.
