### ISSUE TITLE
Request to move the `math` submodule of the `planning` module to the `common` module

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#5543]
@YajiaZhang @lianglia-apollo @startcode  
Request to move the `math` submodule of the `planning` module to the `common` module. Many of the mathematical solutions in this submodule may be useful for other modules such as the `map` module.

**Comment by lianglia-apollo** [comment]
Sure, if some math functions are used more than one module, we can move it to common folder.

**Comment by davidhopper2003** [comment]
@lianglia-apollo You are wonderful. Thanks a lot.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @davidhopper2003 if you have additional questions, please reopen the issue.
Thanks!
