### ISSUE TITLE
HD Map Data upload Error:Upload association failed!

### ISSUE THREAD

**Issue by nandita05** [ApolloAuto/apollo#5550]
### System information

- **OS Platform and Distribution: Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version: 3.0**:

### Steps to reproduce the issue:

1. Go to Apollo's HDMap data management website:
http://data.apollo.auto/hd_map/manage/details?locale=en-us
2. Enter details in Data Overview 
3. Click on "Upload New Data" under Collection Data List and download the generated config file
Please refer image below:
![image](https://user-images.githubusercontent.com/36015387/44800138-a90bfa00-ab83-11e8-9155-fa32738a3721.png)
4. Go to link: 
http://data.apollo.auto/help?name=apollo_hdmap_upload_guide&locale=en-us
and follow steps for Ubuntu platform
5. Copy downloaded config file in ApolloDataUpload directory
5. In a terminal enter commands:
$ **cd ApolloDataUpload**
$ **python ApolloDataUpload.py -c config.json /apollo/data/bag/folder-name**
6. Executing the command for a 78kb bag file show the following message on terminal:
**[1] object uploaded.**
**upload association failed: 请确认使用最新版本客户端**
7. Even on uploading the files, status of uploaded data does not change/update on the website:
![image](https://user-images.githubusercontent.com/36015387/44800659-f76dc880-ab84-11e8-8654-67483998d0a6.png)

### Supporting materials (screenshots, command lines, code/script snippets):
[ApolloHdmapDataUpload.tar.gz](https://github.com/ApolloAuto/apollo/files/2332871/ApolloHdmapDataUpload.tar.gz)
[configtest.zip](https://github.com/ApolloAuto/apollo/files/2332875/configtest.zip)

**Comment by Zhenni17** [comment]
HI @nandita05 , thank you for raising the issue. Our Map team informed me last night that the bug should be resolved. I'm closing the issue now and please feel free to open new issues if there are any follow up questions.
