### ISSUE TITLE
A segmentation fault inside caffe for running perception module (v2.5)

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#5553]
I have my Apollo docker container (v2.5 release) set up with CUDA to run perception module (built by "./apollo.sh build"), but have been having issues with a segfault in the perception module every time I run it. I also tried building with "./apollo.sh build_opt_gpu", but that did not work either. 

I also ran it inside valgrind to see what was causing the segfault but did not find anything meaningful for fix.
Here's the gdb backtrace:

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /apollo/bazel-bin/modules/perception/perception...done.
(gdb) r
Starting program: /home/david/.cache/bazel/_bazel_david/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/perception/perception --flagfile=/apollo/modules/perception/conf/perception.conf --stderrthreshold=3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff8c4a6700 (LWP 27686)]
[New Thread 0x7fff8bca5700 (LWP 27687)]
[New Thread 0x7fff8b4a4700 (LWP 27688)]
[New Thread 0x7fff88ca3700 (LWP 27689)]
[New Thread 0x7fff864a2700 (LWP 27690)]
[New Thread 0x7fff83ca1700 (LWP 27691)]
[New Thread 0x7fff814a0700 (LWP 27692)]
[New Thread 0x7fff7ec9f700 (LWP 27693)]
[New Thread 0x7fff7a49e700 (LWP 27694)]
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[NVBLAS] Cannot open default config file 'nvblas.conf'
[NVBLAS] Config parsed
[NVBLAS] CPU Blas library need to be provided
[ WARN] [1532976597.468363307]: transport file: /home/tmp/ros/etc/ros/transport_mode.yaml is not map
[ WARN] [1532976597.468494169]: Parse transport_mode file failed
[New Thread 0x7fff79a92700 (LWP 27696)]
[New Thread 0x7fff79291700 (LWP 27697)]
[New Thread 0x7fff78a90700 (LWP 27698)]
[New Thread 0x7fff73fff700 (LWP 27699)]
[New Thread 0x7fff737fe700 (LWP 27700)]
[New Thread 0x7fff72ffd700 (LWP 27701)]
[New Thread 0x7fff727fc700 (LWP 27702)]
[New Thread 0x7fff71ffb700 (LWP 27703)]
[New Thread 0x7fff717fa700 (LWP 27706)]
[New Thread 0x7fff70ff9700 (LWP 27707)]
[New Thread 0x7fff47fff700 (LWP 27709)]
[New Thread 0x7fff477fe700 (LWP 27746)]
[New Thread 0x7fff46ffd700 (LWP 27747)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffaa61cb09 in std::string::compare(std::string const&) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007fffaa61cb09 in std::string::compare(std::string const&) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000051473c in std::operator< <char, std::char_traits<char>, std::allocator<char> > (__lhs="ImageDistort", 
    __rhs=<error reading variable: Cannot access memory at address 0x0>)
    at /usr/include/c++/4.8/bits/basic_string.h:2571
#2  0x000000000051a77b in std::less<std::string>::operator() (this=0x2354480, 
    __x="ImageDistort", 
    __y=<error reading variable: Cannot access memory at address 0x0>)
    at /usr/include/c++/4.8/bits/stl_function.h:235
#3  0x0000000000575daa in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)>, std::_Select1st<std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)> >, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)> > >::_M_lower_bound (this=0x2354480, __x=0x2354fb0, 
    __y=0x2354488, 
    __k=<error reading variable: Cannot access memory at address 0x0>)
    at /usr/include/c++/4.8/bits/stl_tree.h:1157
#4  0x00000000005754fb in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)>, std::_Select1st<std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)> >, std::less<std::string>, std::allocator<---Type <return> to continue, or q <return> to quit---
std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)> > >::find (this=0x2354480, 
    __k=<error reading variable: Cannot access memory at address 0x0>)
    at /usr/include/c++/4.8/bits/stl_tree.h:1805
#5  0x000000000057466f in std::map<std::string, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&), std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<caffe::Layer<float> > (*)(caffe::LayerParameter const&)> > >::count (this=0x2354480, 
    __x=<error reading variable: Cannot access memory at address 0x0>)
    at /usr/include/c++/4.8/bits/stl_map.h:849
#6  0x00000000005738e6 in caffe::LayerRegistry<float>::CreateLayer (param=...)
    at /usr/include/caffe/layer_factory.hpp:83
#7  0x00007fffe8dc6bdc in caffe::Net<float>::Init(caffe::NetParameter const&)
    () from /usr/lib/x86_64-linux-gnu/libcaffe.so.1
#8  0x00007fffe8dc9378 in caffe::Net<float>::Net(std::string const&, caffe::Phase, caffe::Net<float> const*) () from /usr/lib/x86_64-linux-gnu/libcaffe.so.1
#9  0x0000000000789036 in apollo::perception::CNNSegmentation::Init (
    this=0x2a79b00)
    at modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation.cc:71
#10 0x00000000006bdfa9 in apollo::perception::LidarProcessSubnode::InitAlgorithmPlugin (this=0x2a5d620)
    at modules/perception/obstacle/onboard/lidar_process_subnode.cc:315
---Type <return> to continue, or q <return> to quit---
#11 0x00000000006bb4a7 in apollo::perception::LidarProcessSubnode::InitInternal
    (this=0x2a5d620)
    at modules/perception/obstacle/onboard/lidar_process_subnode.cc:64
#12 0x0000000000d22990 in apollo::perception::Subnode::Init (this=0x2a5d620, 
    subnode_config=..., sub_events=std::vector of length 0, capacity 0, 
    pub_events=std::vector of length 1, capacity 1 = {...}, 
    event_manager=0x7fffffffe010, shared_data_manager=0x7fffffffe078)
    at modules/perception/onboard/subnode.cc:62
#13 0x0000000000d11e46 in apollo::perception::DAGStreaming::InitSubnodes (
    this=0x7fffffffdff0, dag_config=...)
    at modules/perception/onboard/dag_streaming.cc:173
#14 0x0000000000d11231 in apollo::perception::DAGStreaming::Init (
    this=0x7fffffffdff0, 
    dag_config_path="modules/perception/./conf/dag_streaming.config")
    at modules/perception/onboard/dag_streaming.cc:76
#15 0x00000000004ebc95 in apollo::perception::Perception::Init (
    this=0x7fffffffdfe0) at modules/perception/perception.cc:57
#16 0x000000000050542f in apollo::common::ApolloApp::Spin (this=0x7fffffffdfe0)
    at modules/common/apollo_app.cc:57
#17 0x00000000004eb292 in main (argc=1, argv=0x7fffffffe1c8)
    at modules/perception/main.cc:23

**Comment by hongkedavid** [comment]
@jrqdevb Thanks for your information. Let me try that to see if it can fix the segfault.

**Comment by daohu527** [comment]
It is strongly recommended that you switch to the new version.
