### ISSUE TITLE
Issue running offline demo

### ISSUE THREAD

**Issue by happyx123** [ApolloAuto/apollo#5566]
Hi there!

I am new to Apollo. I was following the steps on running the offline demo at https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide. Everything looks fine until the final step. I was able to play the demo_2.0.bag loop in my terminal and was able to start Dreamview in my Mozilla. But no vehicle was shown and I got an error msg in my terminal:
[ERROR] [1535613845.882991023]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.

Has anyone got any idea what is the issue? Thanks a lot.

Best,
Kai

**Comment by natashadsouza** [comment]
@happyx123 which version of Ubuntu are you working on?

**Comment by natashadsouza** [comment]
That's great feedback. Thank you @happyx123 :)
Currently closing this issue as it has been fixed.
