### ISSUE TITLE
Error While Running Localization on Localization demo data 

### ISSUE THREAD

**Issue by Jyothikumar-b** [ApolloAuto/apollo#5568]
Hi,

I am running Localization demo offline. I am following the commands given at [link](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md).

While playing Rosbag following error is coming:
```
$ rosbag play *.bag
[ INFO] [1535630577.277322062]: Opening 000.bag
[ INFO] [1535630577.315954598]: Opening 001.bag
[ INFO] [1535630577.414806626]: Opening 002.bag
[ INFO] [1535630577.529829252]: Opening 003.bag
[FATAL] [1535630577.530225819]: Error reading from file: wanted 4 bytes, read 0 bytes
```
So we decided to run ros bags one by one but we get the following error:
```
$ rosbag play 000.bag
[ INFO] [1535630840.956989545]: Opening 000.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
[ERROR] [1535630841.215605037]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
 [PAUSED]   Bag Time: 1514423656.648570   Duration: 4.375880 / 59.870157 
```  

It Looks like a mismatch between published msg type and subscribed msg type for Imu.
Please help!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
