### ISSUE TITLE
How to rebuild the ROS workspace in apollo

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5591]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

Can anybody help me to rebuild the ROS workspace in Apollo.

Thank you,
KK

**Comment by gladijos** [comment]
change current directory to your ros workspace (if it isn't exist inside docker make volume)
run catkin_make

**Comment by muleisheng** [comment]
You could also run _./build.sh build_ in your Apollo-platform workspace.

**Comment by kk2491** [comment]
@gladijos @muleisheng Thanks for the step. I will implement the same and update you the findings.

**Comment by SS6141** [comment]
@muleisheng @kk2491 I could not find build.sh. Kindly enlighten me how to execute the script.

**Comment by storypku** [comment]
Stale issue closed.
