### ISSUE TITLE
RVIZ and publishing messages to Apollo modules

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5594]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

- Go inside the docker and run **rviz**

### Supporting materials (screenshots, command lines, code/script snippets):

Hi Guys,

I am trying to visualize the Proto buffer messages from the module. When I used rviz inside the docker it is giving and error **bash: rviz: command not found**

How would I install the rviz inside the docker ?

And also is it possible to Publish the ROS messages to apollo related ROS topics from outside the docker.

Thank you,
KK

**Comment by bhaskarsuper9000** [comment]
@kk2491 For your first question, yes! In fact, something really useful is to have an indigo installation outside and tun your favorite tools :) , which brings us to your second question.

Answer to second question is no. Unfortunately, rviz doesn't understand protobuf, and hence cannot deserialize these messages. Also, most of the qt based diagnostic tools should just work fine, unless they attempt to parse the messages. I might look into rviz on a fine day and try to fix that. My suggestion is either use command line tools. Another option is to explore the collection of in house plotting and debugging tools that Apollo provides and see if it can suit your needs.

**Comment by apollodevcommunity** [comment]
你好，ros topic 和cyber channel 是不通的。如果你想在rviz中看到channel 信息，请使用cyber python api 监听channel 数据，同时使用ros格式，ros python api 创建节点，从这个节点将收到的channel转发出去。发送ros 给apollo 道理同样。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=615
