### ISSUE TITLE
dreamview error msg and rosbag play error msg

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#5614]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source )**:
- **Apollo version (3.0)**:  but use rosbag2.5demo.bag

### Steps to reproduce the issue:
- ** do it as the howto launch apollo doc**:

### Supporting materials (screenshots, command lines, code/script snippets):
rosbag error:
```
/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790343.963925255]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790348.383386328]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790353.204104335]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790356.219694375]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790359.635422385]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790452.683335385]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1535790461.753895375]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
```

dreamview error msg 
Hardware GPS triggers safety mode: No INS status message.

**Comment by zhxt** [comment]
The demo bag file may be outdated since codes are changed version to version.

As the error tells: `
/localization` wants topic `/apollo/sensor/gnss/corrected_imu` to have datatype/md5sum :
`[pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7]` 
but the bag file provides:
`[pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. `

when you examine the bag file with ` rosbag info `, you will find:
```
...type: ...
pb_msgs/Imu                  [bdef0ba51869607ed95736d41e80c1f5]
...topics: ...
/apollo/sensor/gnss/corrected_imu          2000 msgs    : pb_msgs/Imu
...
```
but with Apollo 3.0, the message type of IMU has been changed to:
https://github.com/ApolloAuto/apollo/blob/6ed059981e76818de711d92fec9dbab3b67e1897/modules/localization/proto/imu.proto#L8

from (2.5 branch):
https://github.com/ApolloAuto/apollo/blob/6533b39b32d0d1da6d279b0ed7d846fb55b94be3/modules/localization/proto/imu.proto#L8

So, this could be the answer, I guess.

PS: ` git log -p modules/localization/proto/imu.proto` tells the story :-P

**Comment by westeast** [comment]
@zhxt thanks very much , but where is the demo3.0.bag?

**Comment by zhxt** [comment]
@westeast Sorry, I do not know either, I didn't see there was a demo bag released along with Apollo 3.0.
Maybe you can contact the Official Team to make sure if there is a  demo bag for 3.0.

**Comment by natashadsouza** [comment]
There was no 3.0 demo bag as there was no major addition to the core software modules from Apollo 2.5. Hence you could successfully use Demo Bag 2.5

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
