### ISSUE TITLE
How to use files inside bazel-apollo outside the docker

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5615]
Hi Guys,

I am trying to access the protobuf generated files (.h and .cc) files which are inside the bazel-apollo/modules/common/proto from outside the docker.

Could you please let me know is this feasible ? If yes, how would I access and use those files in a C++ code outside the docker ?

Thank you,
KK

**Comment by natashadsouza** [comment]
@kk2491 it is best practice not to try and access those files from outside the container. Is there any reason behind you trying to accomplish it?

**Comment by kk2491** [comment]
@natashadsouza I am trying write a code which uses the generated protobuf .h and .cc and communicate with the apollo through ROS.
