### ISSUE TITLE
Why add ultrasonic radar?

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5617]
Already have other radars, is it to reduce costs?Or, it has better performance.

**Comment by muleisheng** [comment]
Ultrasonic radar used in emergency cases. In these cases, we don't need to identify an obstacle. We just check if there is obstacle in the front of vehicle. On the other hand, indeed considering the cost

**Comment by natashadsouza** [comment]
Closing this issue as it seems to resolved.
