### ISSUE TITLE
Nvidia driver installed failed, nvidia-smi doesnot work.

### ISSUE THREAD

**Issue by IneverStop** [ApolloAuto/apollo#5620]
Hello guys.

### System information

- **OS Platform and Distribution**: Ubuntu 14.04
- **Apollo installed from**: source
- **Apollo version**: 3.0

### Steps to reproduce the issue:
- Install cuda and nvidia driver succeed in *host*.
`nvcc -V` got:
>root@matrix:/# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

   `nvidia-smi` got correct output.

- As supplyed docker image has installed cuda,so I don't need to install cuda again. Just add cuda path `/usr/local/cuda-8.0/bin` to `PATH` enviroment variables and `/usr/local/cuda-8.0/lib64` to 'LD_LIBRARY_PATH'  in docker.
 `nvcc -V` got same output as host.
- Installed same version nvidia driver in docker,but `nvidia-smi` got:
>Failed to initialize NVML:Function Not Found.

Can not find same problem on Internet, so I will be very appreciate if someone help me.

**Comment by muleisheng** [comment]
Apollo needs libcudnn6 and libcudnn6-dev. You could check if these two packages were installed.

**Comment by hmdt** [comment]
You don't need to install CUDA again in the docker, you only have to install the GPU driver again. Make sure that you install the same driver in both your host machine and in your docker environment.

**Comment by IneverStop** [comment]
@muleisheng @hmdt Thank you!
I installed the same  version of Nvidia driver in my docker as the host.Both nvidia-384.130.
My docker version is `docker-ce`, it`s not from official, but from aliyun, cause we can not achieve docker official website. Is the `docker-ce` correct version apollo need?

**Comment by muleisheng** [comment]
Also, you could verify the directory /usr/local/cuda/bin if it exists. Then echo $PATH and check if it includes /usr/local/cuda/bin. And you may need to check LD_LIBRARY_PATH if it includes cuda libraries directory.

**Comment by IneverStop** [comment]
@muleisheng Thankyou! This problem has been solved. It`s a network problem. I have tried any solution to install nvidia-driver but failed, util I use my mobile phone's wifi instead of company's network.
It seems need to download some files but my company's network is horrible bad.
