### ISSUE TITLE
Access to data page goes through Chinese-language only portal

### ISSUE THREAD

**Issue by osaman88** [ApolloAuto/apollo#5639]
**Describe the bug**
I am based in the USA and don't speak or read Chinese characters. The page below does not have option of English.

**To Reproduce**
Trying to follow the directions here:
https://github.com/ApolloAuto/apollo/blob/r2.0.0/modules/perception/README.md 
Step #5 directs you to:
https://console.bce.baidu.com/apollo/task/download 
Which has a choice of English or Chinese, and a login with SMS, but after I login with SMS (actually works here, no problems like map), I end up at:
https://console.bce.baidu.com/iam/#/iam/user/v2/activate~hideBar=1 
and this particular page is only in Chinese.

**Expected behavior**
English translation or option.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by natashadsouza** [comment]
Hi @osaman88 please refer to the documentation in the master branch: [Perception data document](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/README.md)
If you are still unable to access the data for download, please let me know. Thanks!

**Comment by osaman88** [comment]
Thanks Natasha. So here is the detailed version of the Q then. The previous document was a very specific pointer to data that had all the data necessary to run perception node as per description. The latest pointer is the collection of all the various bags, some are in MBs, some are in GBs. It is not immediately clear which we should download to get the ROS bag (inputs) with all topics needed by perception node. Do you know which one we need? 
Thanks!

**Comment by natashadsouza** [comment]
@osaman88 
The previous link pointed you to a login page that would ultimately redirect you to the link added to the new document version. The only difference is that previously we required everyone to have an account to use the data, however, it is now available without requiring you to login.

**Comment by techoe** [comment]
Please select English for english description
