### ISSUE TITLE
radar rostopic question 

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5660]
code version: apollo 3.0
about module: radar perception
Dear apollo developer,
      we want to use other measuring distance sensor ,such as camera,to substitute  continental ARS408-21 77GHz radar,
     we print radar topic:  /apollo/sensor/conti_radar
such as:
contiobs {
  header {
    timestamp_sec: 1523917535.98
    module_name: "conti_radar"
    sequence_num: 16614
  }
  clusterortrack: false
  obstacle_id: 1
  longitude_dist: 227.4
  lateral_dist: -4.8
  longitude_vel: -19.75
  lateral_vel: -0.5
  rcs: 7.0
  dynprop: 2
  longitude_dist_rms: 0.616
  lateral_dist_rms: 1.317
  longitude_vel_rms: 0.478
  lateral_vel_rms: 1.697
  probexist: 1.0
  meas_state: 2
  longitude_accel: -0.78
  lateral_accel: 0.0
  oritation_angle: -3.2
  longitude_accel_rms: 1.023
  lateral_accel_rms: 0.005
  oritation_angle_rms: 0.471
  length: 4.4
  width: 1.8
  obstacle_class: 1
}
     we find the topic include "obstacle_class",trace the source code we find that in protobuf have define seven obstacle class,such as: 
// 0: point; 1: car; 2: truck; 3: pedestrian; 4: motorcycle; 5: bicycle; 6: wide; 7: unknown
  optional int32 obstacle_class = 24;
     the radar topic:  /apollo/sensor/conti_radar contain obstacle class ,
     is continental ARS408-21 77GHz radar output obstacle class?

**Comment by jilinzhou** [comment]
Take a look of this: http://www.compotrade.ru/i/pdf/ARS404-21_ARS408-21_en_V1.03.pdf

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
