### ISSUE TITLE
激光雷达校准结果有重影现象是什么问题(what's the problem when lidar calibration result has an ghosting phenomenon)

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#5661]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (2.5)**:

我按照官方的文档说明对激光雷达到GNSS进行校准，但是校准的结果发生了重影的现象，先看校准结果。
I calibrated the lidar to GNSS according to the official documentation, but the calibration results were ghosting, first look at the calibration results.
![screenshot from 2018-09-05 21_13_16](https://user-images.githubusercontent.com/41889613/45097268-004a3580-b155-11e8-828c-ae7c08322187.png)

在校准结果的右侧下方是一个物体形成的多个斜线，看起来像是在一个方向上进行多次平移或叠加形成的。如果没有发生这个现象，这个校准结果是正常的。现在我也不知道问题出在哪里了。
Below the right side of the calibration result is a plurality of oblique lines formed by an object, which appear to be formed by multiple translations or superpositions in one direction. If this does not happen, the calibration result is normal. Now I don't know where the problem is.
![qq 20180905215132](https://user-images.githubusercontent.com/41889613/45097625-db09f700-b155-11e8-8822-b36daa3378e7.png)

**官方文档和数据。(Official documents and data.)**
[一种典型的传感器安装方式](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/lidar_calibration_cn.pdf)。([A classical installtion of sensors](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/lidar_calibration.pdf).)
雷达坐标系与系统坐标系示意图。(Lidar coordinate and system coordinate)
![screenshot from 2018-09-05 22_22_30](https://user-images.githubusercontent.com/41889613/45100062-4bffdd80-b15b-11e8-9a06-84e264300142.png)

[官方64线激光雷达外参(Official apollo platform extrinsics data of Velodyne 64)](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/multiple_lidar_gnss_calibration_guide.md)
![qq 20180905223545](https://user-images.githubusercontent.com/41889613/45100674-756d3900-b15c-11e8-845b-ec3aac781d56.png)
我用 [欧拉角与四元组在线转换工具](https://quaternions.online/)知道这是绕z轴旋转90°，如果按照官方的激光雷达安装方式和外参，那最终旋转后的坐标系与GPS/IMU的坐标系的关系图我认为应该是这样的。
I use [Euler angle and quad online conversion tool](https://quaternions.online/) to know that this is rotated 90° around the z axis. If the official lidar installation method and external parameters are used, then after the final rotation The relationship between the coordinate system and the GPS/IMU coordinate system I think should be like this.
```

                                                              /\ X
                                                              |
                                                              |
                                                              |
                                                              |
lidar                                                GPS/IMU  |
Z(UP)----------------->Y                 Y<-------------------Z(UP)
 |                                                                                       
 |                                                                                       
 |                                                                                       
 |                                                                                       
\/ X                                                                                     
```

**我们的实验平台和外参设置(Our testbed and extrinsics setting)**
雷达的坐标系与IMU坐标系示意图(The coordinate figure of lidar and IMU)。
```

                   /\X                                        /\ X
                   |                                          |
                   |                                          |
                   |                                          |
                   |                                          |
lidar              |                                 GPS/IMU  |
Y<-----------------Z(UP)                 Y<-------------------Z(UP)

```
雷达、GPS天线、IMU安装位置示意图及距离标注，侧视图(Lidar, GPS antenna, IMU installation location diagram and distance labeling, side view)。
```
       /\(Z)
        |
        |
Y<------X
                         *****(Lidar)                     ----
                            |                               |
 (Pri ant)                  |                (Sec ant)      |  h=0.185m
    *****                   |                  *****      ----
      |---------0.5m--------|---------0.5m-------|          |
                            |                               |  h=0.335m
                            |-0.105m-|                      |
                                   *****(IMU)             ----
```
height:  lidar - imu  0.52m
Horizontal distance：lidar - imu 0.105m
height:  lidar - PriAnt  0.185m
我以为我们在安装雷达时让雷达的坐标系和IMU的坐标系一致，这样在进行校准时就不需要旋转了，于是设置校准外参如下(所有设备的中心都在x轴上，所以平移矩阵中x的值为0)。
I thought that we do not need to do rotation when calibrating if we make the coordinate system of the lidar and the coordinate system of the IMU consistent, so that we set the calibration external parameters as follows(The center of all equipment is on the x-axis, so the value of x in the translation matrix is 0.).
![qq 20180906002253](https://user-images.githubusercontent.com/41889613/45107657-e7e61500-b16c-11e8-9b33-577190be32c3.png)

但是结果是这样的(But the result is like this)
![screenshot from 2018-09-05 21_56_18](https://user-images.githubusercontent.com/41889613/45107433-27f8c800-b16c-11e8-9945-aa2c12ebd6b1.png)

从数据包中提取出来的单个点云图是这样的
(The single point cloud image extracted from the packet is like this)
![screenshot from 2018-09-06 00_30_10](https://user-images.githubusercontent.com/41889613/45107469-43fc6980-b16c-11e8-84bd-9f1a50800acc.png)

校准结果与我们的场景非常不符合
(The calibration results are very inconsistent with our scenario)。
于是我又修改了外参如下：
![qq 20180906002253](https://user-images.githubusercontent.com/41889613/45107901-a86bf880-b16d-11e8-95ef-c42dd93d03fb.png)

Z = 1 表示绕Z轴旋转180°，这样我们的激光雷达坐标系和IMU的关系也就变成这样了
(Z = 1 means 180° around the Z axis, so the relationship between our lidar coordinate system and IMU becomes like this.)
```

                                                              /\ X
                                                              |
                                                              |
                                                              |
                                                              |
lidar                                                GPS/IMU  |
Z(UP)----------------->Y                 Y<-------------------Z(UP)
 |                                                                                       
 |                                                                                       
 |                                                                                       
 |                                                                                       
\/ X                                                                                     
```

得到了如下结果(I got the following result)
![screenshot from 2018-09-06 00_42_57](https://user-images.githubusercontent.com/41889613/45108617-b02c9c80-b16f-11e8-9730-fc5c7313b65d.png)
放大一些的图，就像你在开始看到的那样(Magnified image, as you saw it at first)
![screenshot from 2018-09-06 00_43_13](https://user-images.githubusercontent.com/41889613/45108639-c20e3f80-b16f-11e8-8139-fa4313748816.png)

单个点云图与校准结果图对比
(Comparison of single point cloud map and calibration result graph)
![qq 20180906010220](https://user-images.githubusercontent.com/41889613/45108893-8f187b80-b170-11e8-8980-4df595ee514a.png)
![qq 20180906010032](https://user-images.githubusercontent.com/41889613/45108903-9475c600-b170-11e8-93fc-cbe91d966e4b.png)

看起来这有个平移的问题，但是我不知道外参应该怎么设了。除此之外，我想知道在平移矩阵中的x, y, z表示的是激光雷达到IMU的距离还是激光雷达在IMU坐标系中的坐标。
It seems that this has a translation problem, but I don't know how the external parameters should be set. In addition, I want to know whether x, y, z in the translation matrix represents the distance from the lidar to the IMU or the coordinates of the lidar in the IMU coordinate system.

pcd文件下载：
00000.pcd:  激光雷达原始扫描图(origin pcd file)
velodyne16_result.pcd: z = 1
velodyne16_result_2.pcd:  w = 1
[pcd.zip](https://github.com/ApolloAuto/apollo/files/2353845/pcd.zip)

**Comment by homography** [comment]
The configuration translation=(0,  0.105, 0.52), q=(0, 0, 0, 1) is the right choice according to your sketch. Before going into the calibration, make sure the differential GPS is functional and also the gps-imu is well aligned. These conditions can be verified from some state-code according to the calibration manual. If  the result is still noisy even if the localization seems good, please check the GNSS/INS settings such as lever-arm, and also check the integration such as sync-cable and antenna connection.

**Comment by xinwf** [comment]
@homography, what's the translation matrix if the installtion of lidar and IMU is like this?
1.translation = (0,  0.5,  0.185)   // x, y, z stand for the distance from lidar to IMU.
2.translation = (0, -0.5, 0.185)  // x, y, z stand for the coordinate of the lidar in IMU's coordinate system
3.translation = (0, 0.5, -0.185)  // x, y, z stand for the change of the lidar's coordinate if it is translated to IMU's position.

which one is right if the relative postion of lidar and IMU is like this?

__side view__
```
       /\(Z)
        |
        |
Y<------(X)
                         *****(Lidar)                     ----
                            |                               |
    (Imu)                   |                (Sec ant)      |  h=0.185m
    *****                   |                  *****      ----
      |---------0.5m--------|---------0.5m-------|

```

**Comment by xinwf** [comment]
The problem is to convert the coordinates of the IMU to RFU.
