### ISSUE TITLE
/apollo/sensors/gnss/imu  coordinate?

### ISSUE THREAD

**Issue by yuconglin** [ApolloAuto/apollo#5668]
Hi everyone: 
   I am confused about apollo's coordinate definition for IMU. From https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md#global-positioning-system-(gps)-and-inertial-measurement-unit-(imu), it looks like it uses right-front-up convention. 
  but when I played the demo_2_0.bag and did a "rostopic echo /apollo/sensor/gnss/imu", I found the output is:
  ---
header {
  timestamp_sec: 1514497070.98
}
measurement_time: 1198532288.97
measurement_span: 0.00499999988824
linear_acceleration {
  x: -0.406950712204
  y: 0.759772956371
  z: 9.945333004
}
angular_velocity {
  x: 0.00417809403439
  y: -0.0102860695989
  z: 0.0226752302286
}

---
header {
  timestamp_sec: 1514497070.99
}
measurement_time: 1198532288.97
measurement_span: 0.00499999988824
linear_acceleration {
  x: -0.37208199501
  y: 0.884849578142
  z: 10.1518444717
}
angular_velocity {
  x: -0.00308266097663
  y: -0.0105845048871
  z: 0.0220807003212
}

---
header {
  timestamp_sec: 1514497070.99
}
measurement_time: 1198532288.98
measurement_span: 0.00499999988824
linear_acceleration {
  x: -0.469535589218
  y: 0.647213310003
  z: 10.0661814213
}
angular_velocity {
  x: -0.00666388443468
  y: -0.0120485933008
  z: 0.0225722407959
}

the linear acceleration tells that the z direction facing downward.

So, how the coordinate is defined from the message  /apollo/sensors/gnss/imu?

Thanks

**Comment by xinwf** [comment]
the Z's value is greater than zero, so the direction is toward up, why do you think the z direction is facing downward?

**Comment by yuconglin** [comment]
The gravity acceleration is facing downward. Since the acceleration in z
direction is positive, I infer that z direction is same as the gravity
direction, which faces downward.
reference http://www.starlino.com/imu_guide.html

**Comment by yuconglin** [comment]
If z coordinate points up, and gravity points downward. Why do we have
positive gravity measurement? Measurement of acceleration is nothing more
than its projection on a coordinate frame.

**Comment by cmas1** [comment]
If I may chime in, everything seems fine to me. Accelerometers do not measure the total acceleration but rather the specific force, that is (over simplifying) the acceleration minus the gravitational acceleration.

This means that an accelerometer in free fall measures zero along the z-axis, whereas when it is placed on the ground it measures the reaction force exerted from the ground (-g).

**Comment by yuconglin** [comment]
That will explain it, thanks a lot.

**Comment by apollodevcommunity** [comment]
that is raw IMU data which means the force direction IMU gets. IMU get a support force from vehicle which is equal to its gravity. And its force is up. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=612
