### ISSUE TITLE
ERROR: /apollo/modules/dreamview/backend/BUILD:5:1: C++ compilation of rule '//modules/dreamview/backend:backend' failed (Exit 4)

### ISSUE THREAD

**Issue by lvxin0805** [ApolloAuto/apollo#5675]
Hi guys,
Now I install ubuntu16.04 virtual machine on Mac, and do the software installation followings Appllo docs, then I try to build apollo sourcecodes  and encounter build failed as follow : 
bash apollo.sh build --local_resources 2048,1.0,1.0

�
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Extracting Bazel installation...
.
____Loading package: modules/prediction/container/obstacles
____Loading package: modules/control
____Loading package: modules/perception/obstacle/camera/detector/common
____Loading package: modules/perception/obstacle/camera/interface
____Loading package: third_party/can_card_library/hermes_can
____Loading package: modules/planning/toolkits/optimizers/qp_spline_path
____Loading package: modules/localization/msf/local_tool/data_extraction
____Loading package: modules/monitor/hardware/can
____Loading package: modules/perception/tool/offline_visualizer_tool
____Loading package: modules/planning/common
____Loading package: modules/perception/traffic_light/reviser
____Loading package: modules/drivers/camera/common
____Loading package: modules/planning/toolkits/optimizers
____Loading package: modules/guardian/common
____Loading package: modules/perception/proto
____Loading package: modules/planning/planner/navi
[INFO] Building on x86_64...
[INFO] Building with --jobs=2 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Found 1811 targets...
ERROR: Error during action cache initialization: Failed to load filename index data. Corrupted files were renamed to '/home/lx/.cache/bazel/_bazel_lx/540135163923dd7d5820f3ee4b306b32/action_cache/*.bad'. Blaze will now reset action cache data, causing a full rebuild.
ERROR: /apollo/modules/dreamview/backend/BUILD:5:1: C++ compilation of rule '//modules/dreamview/backend:backend' failed (Exit 4).
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 1054.926s, Critical Path: 56.50s
============================
[ERROR] Build failed!
[INFO] Took 1082 seconds
============================
lx@in_dev_docker:/apollo$ cd modules/dreamview/backend/

**Comment by muleisheng** [comment]
try to replace  --local_resources 2048,1.0,1.0 with --local_resources 2048,.5,1.0

**Comment by lvxin0805** [comment]
@muleisheng 
Thanks for your help, build successed by your suggestion
