### ISSUE TITLE
Does it really need to install Apollo by the order: 1.0 > 1.5 > 2.0 > 2.5 > 3.0?

### ISSUE THREAD

**Issue by jamchen1025** [ApolloAuto/apollo#5677]
Hi Apollo Team,

I read the [Prerequisites](https://github.com/ApolloAuto/apollo#prerequisites), and it mention that: "Please note, it is recommended that you install the versions of Apollo in the following order: 1.0 > 1.5 > 2.0 > 2.5 > 3.0."

My Question is:
1. I want to know can I just install Apollo versions 3.0 once and for all. And then confirm all individual hardware components and modules are functioning correctly on Apollo 3.0?
2. If I test GPS(for example) and it works fine on Apollo1.0, do I need to check GPS again on Apollo 3.0?

Any comments will be appreciated~

**Comment by natashadsouza** [comment]
@jamchen1025 it is a recommended practice to install Apollo 1.0 to test whether all the sensors are compatible, calibrated correctly and working without any bugs, before installing a more advanced version of Apollo. You could choose to install to install Apollo 3.0 directly, however, if you go through the setup guide, especially the basic hardware setup, ultimately, it would point you back to Apollo 1.0. Once the sensor is setup, you would not need to retest it. Hope this helps!

**Comment by jamchen1025** [comment]
@natashadsouza ,
I will try the second method:
Install Apollo software 3.0 directly, and go through the hardware installation guide by the order 1.0>...>3.0.
Thanks for your valuable advice~

**Comment by natashadsouza** [comment]
Closing this issue @jamchen1025 
Feel free to open it if you have any additional questions :)
