### ISSUE TITLE
关于Apollo RTK几个问题请教

### ISSUE THREAD

**Issue by Triangle001** [ApolloAuto/apollo#5678]
Apollo 开发者，您好！
   几个关于定位的问题请教：
1.通过接收解算方式：rtk_solution_type: RTK_RECEIVER_SOLUTION，
rtk_to {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/ttyUSB0"
        baud_rate: 115200
    }
}    这里配置把rtcm差分数据发送到接收器，接收器解算后，
Apollo怎样接收解算后的精确定位数据，修改那个配置文件呢？

2.启动localization模块后，代码rtk_localization.cc中的83行：
if (AdapterManager::GetGps()->Empty()) {
成立。请问是什么原因导致AdapterManager::GetGps()->Empty()？该怎么操作使AdapterManager::GetGps()返回不为空？

谢谢。

**Comment by jilinzhou** [comment]
Gps messages are published by gnss driver. Take a look data_parser.cc where both Gps and Imu messages are published.

**Comment by Triangle001** [comment]
in data_parser.cc line 135： if (type == Parser::MessageType::NONE) break;  done，what should i do ? Thanks.

**Comment by Triangle001** [comment]
apollo提供了将NMEA-0183 格式的数据解析成proto类型的代码吗？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
