### ISSUE TITLE
corrected_imu incomplete

### ISSUE THREAD

**Issue by yuconglin** [ApolloAuto/apollo#5680]
I was trying to inspect the corrected_imu message from demo_2.0.bag. The message from rostopic echo seems incomplete:

---
header {
  timestamp_sec: 1514497067.05
}

---
header {
  timestamp_sec: 1514497067.06
}

---
header {
  timestamp_sec: 1514497067.07
}

---
header {
  timestamp_sec: 1514497067.08
}

---
header {
  timestamp_sec: 1514497067.09
}

---
header {
  timestamp_sec: 1514497067.1
}

the following is the output from the diagnostic.sh script:
Module         Topic                              Period    Max       Min       Delay
CHASSIS        /apollo/canbus/chassis             10.21     13.90     6.23      21758012.74
CHASSIS_DETAIL /apollo/canbus/chassis_detail      0.00      0.00      inf       0.00
CONTROL        /apollo/control                    10.48     35.10     0.58      21758012.74
LOCALIZATION   /apollo/localization/pose          0.70      170.21    -34901.26 21758012.74
MONITOR        /apollo/monitor                    0.00      0.00      inf       0.00
PLANNING       /apollo/planning                   93.31     152.71    32.57     21758020.19
PERCEPTION     /apollo/perception/obstacles       62.25     163.34    39.79     21758012.74
PREDICTION     /apollo/prediction                 60.70     209.83    20.17     21758012.75
PAD            /apollo/control/pad                0.00      0.00      inf       0.00
ODOMETRY       /apollo/sensor/gnss/odometry       10.00     30.00     -34890.00 21758012.74
IMU            /apollo/sensor/gnss/corrected_imu  10.00     40.00     -34890.00 21758012.74
ROUTING_RES    /apollo/routing_response           0.00      0.00      inf       0.00
ROUTING_REQ    /apollo/routing_request            0.00      0.00      inf       0.00
MOBILEYE       /apollo/sensor/mobileye            0.00      0.00      inf       0.00
DELPHI_ESR     /apollo/sensor/delphi_esr          0.00      0.00      inf       0.00
CONTI_RADAR    /apollo/sensor/conti_radar         76.82     94.86     55.30     21758012.85
SIGNAL_LIGHT   /apollo/perception/traffic_light   287.38    1004.12   108.51    21758012.74
DRIVE_EVENT    /apollo/drive_event                0.00      0.00      inf       0.00
SYSTEM_STATUS  /apollo/monitor/system_status      0.00      0.00      inf       0.00
NAVIGATION     /apollo/navigation                 0.00      0.00      inf       0.00
RELATIVE_MAP   /apollo/relative_map               0.00      0.00      inf       0.00

a similar issue was closed recently.

Any help? thanks

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
