### ISSUE TITLE
导航模式问题

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5692]
平台：ubuntu 16.04
code 版本： apollo v3.0
相关模块： relative map、planning module
问题：
       目前我们想使用相对地图这种方式实现汽车在既定道路上自动行驶，我们采用的方式是：
       1、开启perception module，只是使用camera 作为感知模块的输入
       2、开启prediction module
       3、使用relative_map.sh 打开realtive map模块，用navigator.py播放录制的轨迹。
       4、开启planning module
       5、开启control module
       在第step 4时我们需要选择一个路径规划的模式，目前在：apollo-master\apollo-master\modules\planning\planner 这个路径规划方式下面有：RTK、EM、Lattice、navi这几种方式，我们想使用Lattice这种规划方式可以在配置文件里面设置吗？
        在dramview里面仿真时，在如下所示的选项中只有RTK、Navigation、Standard几种方式可以选择，此处的Navigation是前面讲的路径规划方式：RTK、EM、Lattice、navi中的navi这种方式吗？在dreamview里面可以选择其他规划方式吗？
![image](https://user-images.githubusercontent.com/19250516/45196589-9c785780-b28f-11e8-9fa9-eacb84852a14.png)

**Comment by freeclouds** [comment]
@yifeijiang,我们在户外用相对地图测试,代码版本 apollo 3.0,
我们把:
apollo-master/modules/planning/conf/planning_config.pb.txt
中planner_type : EM改成了NAVI,
问题１：
这个planner_type是改变了ｐｌａｎｎｉｎｇ模块具体使用哪种规划算法，这个ｐｌａｎｎｅｒ_type和ｄｒｅａｍｖｉｅｗ里面Ｎavigation有什么区别？或者讲我想使用ａｐｏｌｌｏ　３．０的相对地图方式必须要在ｄｒｅａｍｖｉｅｗ里面选择Ｎａｖｉｇａｔｉｏｎ模式吗？这个Ｎａｖｉｇａｔｉｏｎ模式和ｐｌａｎｎｅｒ里面的ｎａｖｉ规划方式是什么样的关系？
我们参考了这篇文档
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode_cn.md

问题２：
在相对地图介绍中有３中模式，这个是在哪个配置文件中设置？能麻烦告知一下吗？谢谢！

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
