### ISSUE TITLE
Logic behind not updating center or anchor_point in PerformMotionFusion

### ISSUE THREAD

**Issue by rogern27** [ApolloAuto/apollo#5698]
Hi,
My question refers to the following [code](https://github.com/ApolloAuto/apollo/blob/25049cb4bdfd932fb78df1cb18224bd4fdd612e3/modules/perception/obstacle/fusion/probabilistic_fusion/pbf_track.cc#L307) in perception/obstacle/fusion/probabilistic_fusion/pbf_track.cc)
```
        motion_fusion_->UpdateWithObject(obj, time_diff);
        Eigen::Vector3d anchor_point;
        Eigen::Vector3d velocity;
        motion_fusion_->GetState(&anchor_point, &velocity);
        fused_object_->object->velocity = velocity;
```
In last line, `fused_object_->object->velocity` is replaced by `velocity`, but `anchor_point` is not used to update 
the `center` or `anchor_point` of the `fused_object_->object`. Could you please explain why is it so?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
