### ISSUE TITLE
Dreamview shows nothing

### ISSUE THREAD

**Issue by zhixuan-wei** [ApolloAuto/apollo#57]
I have followed the following guide https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/README.md

I got the hmi running but dreamview shows nothing.

![8887](https://user-images.githubusercontent.com/18064647/27905541-d0acfc04-6272-11e7-9173-a9fdea0a89dd.png)
![8888](https://user-images.githubusercontent.com/18064647/27905551-d59deb6a-6272-11e7-8369-ac69369ed27b.png)

meta.txt of mine is:
`root@in_release_docker:/apollo# cat /apollo/meta.txt `
`Git commit: 0264461`
`Build time: 20170704_1141`

**Comment by YuehChuan** [comment]
this is related to #14
