### ISSUE TITLE
low volume REST API call in Apollo cloud simulation

### ISSUE THREAD

**Issue by drchangliu** [ApolloAuto/apollo#5702]
We are interested in performing low volume REST API calls to the outside world within the Apollo cloud simulation. This will enable us to perform inter-vehicle communication for our research project. The calls will low-volume (e.g. less than a dozen for the entire session, each only a few KB in size) and infrequent ( < 1 Hz). Could this be enabled? If an alternative way to communicate to the outside world can be enabled, that will work, too. Thanks!

**Comment by natashadsouza** [comment]
@drchangliu thank you for your request. We do not currently support REST API calls in our cloud simulation platform for a number of reasons. If you have any suggestions on how to best set up V2X, we would love to hear your thoughts and findings. Thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
