### ISSUE TITLE
Launch planning module issue 

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5719]
platform: ubuntu 16.04+apollo 3.0
about module: planning 
issue:
when build pass lanunch planning module ,will failed:

alan@in_dev_docker:/apollo$ bash scripts/planning.sh start
/apollo/scripts/apollo_base.sh: line 234: 26879 Segmentation fault      (core dumped) nohup /apollo/bazel-bin/modules/planning/planning --flagfile=modules/planning/conf/planning.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/planning.out 2>&1
Could not launch module planning. Is it already built?

we have three PC  to run this module, All computers have meet this issue,
Is there some meet the same question?

**Comment by muleisheng** [comment]
You could try to execute _/apollo/bazel-bin/modules/planning/planning_ to check if planning could crash when starting it.

**Comment by freeclouds** [comment]
issue have fixed,we find in apollo  master branch latest code have a bug,
file path:  apollo-master\apollo-master\modules\planning\planning_base.h

**Comment by lianglia-apollo** [comment]
@freeclouds Hi, could you let us know more details on the bug? Thanks!

**Comment by freeclouds** [comment]
we use gdb tools find in planning_dispatcher.cc, 
std::string Name() const override { return planning_base_->Name(); } 
=》“return planning_base_->Name()”;
will cause core dump,
because planning_base_ this class don't have Name（）function，
we return a string ,this core dump issue don't occur.

**Comment by lianglia-apollo** [comment]
@freeclouds Thanks for pointing this out. We will fix it.

**Comment by poutyface** [comment]
It seems that this problem has occurred since the following commit.

https://github.com/ApolloAuto/apollo/commit/28cd780499342ab7b5dc906dd1d7d497e03a6da6

Because Name() func is called before Init(), the planning_base_ in Name() is NULL.

**Comment by lianglia-apollo** [comment]
We will fix it in the next release soon.
