### ISSUE TITLE
lattice 算法细节问题

### ISSUE THREAD

**Issue by zhuzd12** [ApolloAuto/apollo#5728]
在复现lattice算法中发现了一个问题想请教一下：假设车体在当前时刻位置与上一时刻规划出的轨迹有一定偏离，在当前时刻选取了纵向距离40m横向偏差为0的终点生成轨迹，但是这条轨迹的初始段几乎对横向没有纠偏，而是很平稳的过渡到终点，这样到下一时刻，横向偏差几乎没有改善，又重复之前的过程，偏差无法收敛。请问这种问题应该如何解决？

**Comment by zhuzd12** [comment]
感谢回复，这两种方式理论上都可以缓解在这种场景下我所描述的问题。不过这里我还想表述另一层疑惑：对于控制而言，特别是基于MPC的控制方法，需要保证一定时域内（比如2到3秒）轨迹的稳定性和一致性，可能最好在不紧急的场景里规划出的轨迹在这个时间创窗口内保持不变；而lattice算法在每一帧都进行重规划，选取的横向偏差收敛的终点位置（如果每次都选取40m或者某一个评分最高的s_terminal）不断往前推进，而非之前规划确定的收敛点，本质上感觉还是无法回避收敛稳定性的问题。请问这样的观点是否正确和需要考虑？

**Comment by zhuzd12** [comment]
还有另外一个小问题：车道参考线的起点的更新频率和规划的更新频率是不是不一致？ 如果车道参考线起点更新较慢（比如1s），原理上能够一定程度保证更新周期内轨迹生成的稳定性。

**Comment by YajiaZhang** [comment]
如果每次都选取固定距离（比如一直是40m）回到指引线，我看可能的原因有如下几个：1. 控制模块在一个轨迹规划周期中没有作出适当相应进而改变车辆状态，2. 设计的代价函数不合理，导致没有选取尽快回到指引线的轨迹。3. 纵向上的参数太稀疏，导致相邻参数的轨迹代价差别太大。比如我们设置了10m, 20m, 30m, 40m等几个横向轨迹的纵向距离参数，某一个周期选择了40m回到路中心的轨迹，下一个周期可能最优解是39m回到路中心，但是我们没有设置这个参数，而选择30m回到路中心的轨迹可能横向速度加速度又太大，所以一直选用40m回到中心的轨迹。

对于可能原因1, 确实是需要考虑您提到的原因， “对于控制而言，特别是基于MPC的控制方法，需要保证一定时域内（比如2到3秒）轨迹的稳定性和一致性，可能最好在不紧急的场景里规划出的轨迹在这个时间创窗口内保持不变”。 对应到解决方案，可以查看TrajectoryStitcher中的代码，调节forward_rel_time, 这样会调节和上一周期轨迹一致的时间。

对于可能原因2,需要具体分析代价函数，作出修改。

对于可能原因3,一个简单的解决方案是记录上一周期相应的回到中心的相对位置，将它作为一个参数生成横向轨迹。

**Comment by YajiaZhang** [comment]
车道参考线（指引线）对于规划算法是不变的，对轨迹的产生应该没有影响。

**Comment by zhuzd12** [comment]
感谢对第一个问题的耐心回复！目前也在尝试记录上一周期的切入点，并加入相似性指标来保证轨迹稳定性。

另外一个问题我可能没有表述清楚。想问询的是每一帧lattice规划时参考建立frenet坐标系的车道参考线的起点（对应于s=0）是不是也是随着车的定位而确定的，比方说起点固定在本车实时在车道上沿着后方20m的固定距离。又或者不是这样，而是在本车行驶一段时间（1s）或距离（1m）内，车道参考线（一系列离散点）是不变的，也就是frenet参考系也不变。之所以问这样一个问题是觉得可以通过设置一个时间窗口稳定的车道参考线也即起点固定的frenet坐标系，可以保证在这个窗口内的收敛点/终点"40m"不会发生变化（空间上仍旧是同一个点）。这样上一时刻的40m对应的还是当前时刻的40m，而不是39m。请问目前车道参考线的起点是我刚刚所描述的哪种方式（依据本车实时位置的动态值 or 一定时空边界内的相对稳定值），以及如果是后者是否能够一定程度上解决轨迹一致性的问题。

**Comment by katie3000** [comment]
您好，我好像遇到了一样的困惑。从代码上看，貌似动态轨迹的生成频率是10Hz，控制器的控制频率是100Hz，是否意味着对于每条动态轨迹控制器要做到在10个周期内收敛？我试验了，效果很差，可能是因为控制器的问题。关键的是，每10个周期都要重新收敛，转向动作会十分频繁。而且如你所说，lattice总是规划一条柔和的动态轨迹，10个周期只用到了轨迹前端很短的一部分，横向误差太小，如此循环，不足以引导车辆向参考线运动。并且，由于每10个周期重新收敛引起的转向动作导致车辆航向变化，反而会导致lattice生成的动态轨迹偏离参考线，造成恶性循环。
这是我试验过程中遇到的困惑，和您的问题很相似，一起探讨。

**Comment by quhezheng** [comment]
个人感觉这个lattice算法现在根本无法使用, 逻辑前后不一致,很多数据如kappa, dkappa 等都没有设置. 尤其没有考虑前后周期的连贯性. 理论上, 上一周期还在变道阶段, 下一个周期就立即选择了规划跟车的路径

**Comment by katie3000** [comment]
mark

**Comment by yifeijiang** [comment]
We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.
