### ISSUE TITLE
请问lattice_planner里面的Auto Tuning是用来干什么的?

### ISSUE THREAD

**Issue by yiyiyi4321** [ApolloAuto/apollo#5730]

**Comment by YajiaZhang** [comment]
Auto Tuning部分的目的是通过机器学习的方式来给代价函数的参数调优，现在相关工作还在开发之中。

**Comment by yiyiyi4321** [comment]
这种学习可以理解为根据场景自动为那六个代价函数分配权值吗？

**Comment by HermanZYZ** [comment]
按照我的理解，Auto-tuning是学习如何根据场景来评估规划出来的trajectory，从中选择出一条最优的。它并不是去学习如何分配权重，而是学习如何给出一个cost

**Comment by yifeijiang** [comment]
We will close the issue for now. If you have any additional question, please feel free to open a new issue.
