### ISSUE TITLE
Planning: avoiding obstacles

### ISSUE THREAD

**Issue by SanduIrina** [ApolloAuto/apollo#5732]
I tried testing the planner's capability of avoiding obstacles using the /apollo/modules/tools/perception/replay_perception.py script (which is on branch 3.0) and what I found is that:
- the prediction module must also be turned on(if I don't, the car just goes through obstacles)
- it detects the obstacles and it stops when it gets near enough
- if the obstacle takes only a small part of the lane, the car sometimes goes by it, other times it completely stops
I couldn't see quite clearly that the car does any categoric evasive maneuvres to avoid the obstacle. Is it maybe because the lane is not wide enough? Also, will the car switch lane in order to avoid obstacles?
I'm not sure how obstacle avoidance work and which planner I should use. I tested with EM. Could you check that what I found is true or not and maybe provide a little more insight? 
Thank you

**Comment by kk2491** [comment]
@SanduIrina .. I would like to give some points here as I have tested some of the behaviors of the Car.

1. Car would stop if the lane is completely blocked or blocked more than half of the lane.
2. Car would nudge the obstacle if lane is partially blocked and there is sufficient room in the same lane to pass through.
3. Car would change the lane if the obstacle covers less than half of the lane and there exists a right or left neighboring lane. There is a wait time, car comes to stop and waits for that amount of time and then changes the lane.

Thank you,
KK

**Comment by SanduIrina** [comment]
> @SanduIrina Hi Sandulrina, How did you add obstacles to the dreamview? Thank you.

Hello, I ran /apollo/modules/tools/perception/replay_perception.py from docker after starting dreamview. Inside the script you can find the coordinates and adjust them as you like

**Comment by fanghaos2014** [comment]
Thank you for your answer. You mean inside the script, is garage script in the perception/tools or just replay_perception.py? Thank you very much.

**Comment by SanduIrina** [comment]
Hi, the command should look similar to this:
python replay_perception.sh garage_onroad_vehicle_3.json
You can edit the coordinates and size of the obstacles in the garage_onroad_vehicle_3.json file.
Sorry for the late response.

**Comment by fanghaos2014** [comment]
Thank you.

**Comment by SanduIrina** [comment]
Yes, that's the one.

**Comment by fanghaos2014** [comment]
Thank you really appreciate it. 
And I am really curious before running this command, do we need to run the Demo bag? Or just running this command after we run script/bootstrap. Because I didn't see the object after I run the script/bootstrap. Thank you.

**Comment by SanduIrina** [comment]
I didn’t run it with a demo bag. I just modifyed the coordinates in the
garage script so that the obstacle will be located on my vector map and I
activated the planning and routing modules to route my car. I don’t know if
it would work with a bag because I think the obstacles will be taken either
from the bag or from the script.

**Comment by SanduIrina** [comment]
By car I mean the car in dreamview, I didn’t test on a physical car ( sorry
for the misunderstanding)

**Comment by fanghaos2014** [comment]
Thank you really appreciate it.

**Comment by fanghaos2014** [comment]
Hi Sandulrina, sorry to bother you and  I have one more question. After I type the ./scripts/bootstrap.sh. The dreamview shows "please send car initial position and map data". I don't see any vehicle in the dreamview. And when I run the python replay_perception.py .... there is nothing in the dreamview, no vehicle and obstacle.  Do you know anything about it?  Thank you very much.

**Comment by fanghaos2014** [comment]
Thank you. The car in the dreamview is running? So the button you selected is simcontrol, planning and routing? And after that, you run the replay_perception.py? Thank you for your help.

**Comment by SanduIrina** [comment]
Yes

**Comment by fanghaos2014** [comment]
Thank Sandulrina. Really appreciate it. When I added obstacle through scripts, I didn't see the car stop or avoid obstacles. Do you have this problem? The car just passes through it. Thank you.

**Comment by SanduIrina** [comment]
Yes, you can see all I found out about this in my Issue(up top) and in the first reply. Try turning on the prediction module as well.

**Comment by fanghaos2014** [comment]
Thank you for your reply. I will take a look.
