### ISSUE TITLE
This repo can run in Ubuntu18 or not?

### ISSUE THREAD

**Issue by hahanigehaha233** [ApolloAuto/apollo#5734]
I sorry asking for that because my taptop can't install nvidia driver in ubuntu14 but 18.

**Comment by lesun90** [comment]
yes. I am using it in unbuntu 18.

**Comment by natashadsouza** [comment]
Please reference #4636

**Comment by hahanigehaha233** [comment]
I was install yesterday and no error in compiling time or test demo time.
