### ISSUE TITLE
Can't use the dreamview : connection issue between frontend and backend ?

### ISSUE THREAD

**Issue by LucasMahieu** [ApolloAuto/apollo#5735]
Hi,
I am facing an issue with apollo 2.5 in this configuration : 
### System information
- **OS Platform and Distribution **: Linux Ubuntu 14.04
- **Apollo installed from **: docker + github sources
- **Apollo version **: 2.5

My issue is that the connection between the dreamview in the browser seems to be disconnected when data are publish on topics.
Let's me explain a bit more in details : 
- I use `./docker/scripts/dev_start.sh` and `./docker/scripts/dev_into.sh` to go into the docker
- When I start up the dreamview with `./scripts/bootstrap.sh start` all seems to be fine
  I can the the dreamview ready in my browser, I can change the view to "Module Controller" or "Tasks".
- Then, I want to visualize the demo_2.5.bag for example.
  So, I launch the rosbag with `rosbag play --clock demo_2.5.bag` (with or without the --clock option is the same).
And at this time the dreamview make appear the car, the "Module Delay", the "Quick Start" ,etc ...
But immediately, the dreamview is freezing... Nothing appends any more in the dremview.
- When I it F12 to see the "console" of Firefox, I can see this log : 
```
THREE.WebGLRenderer 84 app.bundle.js:1
fonts/gentilis_bold.typeface.json20.18610295725669% loaded app.bundle.js:25
fonts/gentilis_bold.typeface.json100% loaded app.bundle.js:25
OBJLoader: 78ms app.bundle.js:52
OBJLoader: 20ms app.bundle.js:52
OBJLoader: 2ms app.bundle.js:52
OBJLoader: 61ms app.bundle.js:52
The connection to ws://localhost:8888/websocket was interrupted while the page was loading. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/pointcloud. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/map. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/websocket. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/pointcloud. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/map. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/websocket. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Offset is set to x:0, y:0 app.bundle.js:25
Loading failed for the <script> with source “http://localhost:8888/0.bundle.js”. localhost:8888:1
WebSocket connection closed, close_code: 1006 app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/websocket. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/pointcloud. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/map. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/websocket. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/pointcloud. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Last sim_world_update took 13101ms app.bundle.js:25
using grid as ground image... app.bundle.js:25
rendering ground image... app.bundle.js:25
The connection to ws://localhost:8888/map was interrupted while the page was loading. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/websocket. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/pointcloud. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/map. app.bundle.js:25
WebSocket connection closed with code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888/websocket. app.bundle.js:25
WebSocket connection closed, close_code: 1006 app.bundle.js:25
Firefox can’t establish a connection to the server at ws://localhost:8888
```

If I hit F5 to refresh I get the "Unable to connect" page of firefox which said : 
> Firefox can't establish a connection to the server at localhost:8888

- Then, when the rosbag play command finished, I get back the apollo page on my browser with F5 !!

- So the dreamview process seems to be healthy, and does not output any issues.
in data/log/dreamview.out, I have only a lot of : 
> E0911 16:10:09.481050   261 hdmap_util.cc:120] RelativeMap is empty

- I have also noticed that I have strange error in : /home/myname/.ros/log/61869e6c-b5cc-11e8-8465-40167e28e95a/master.log : 
[master.log](https://github.com/ApolloAuto/apollo/files/2371532/master.log)
The error seems to be the same I the error I can see in the browser's console... 

- If it could help, here is the dump of `ps aux` : 
[dump_ps.log](https://github.com/ApolloAuto/apollo/files/2371596/dump_ps.log)

I really don't understand what could be the problem ...
Does someone have any idea to help ?
Thanks

**Comment by mickeyouyou** [comment]
Have you ever tried other browsers, such as chrome?

**Comment by LucasMahieu** [comment]
Thanks for the reply :
1 - Yes, I did, I got exactly the same issue with other browsers
2 - Yes, I have the `rostopic list` as I should have

**Comment by magicalwz** [comment]
seem to me that you should execute
`git lfs fetch
git lfs checkout`
or
`git lfs pull`

according to https://zzz.buzz/zh/2016/04/19/the-guide-to-git-lfs/

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks @liushijiu0 :)
