### ISSUE TITLE
dev_start.sh requires root access

### ISSUE THREAD

**Issue by geoffviola** [ApolloAuto/apollo#5736]
**Describe the bug**
Running `docker/scripts/dev_start.sh` puts files in `/apollo`, which requires root access.

**To Reproduce**
`docker/scripts/dev_start.sh`

**Expected behavior**
Put the folder in the home current user's directory.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] n/a
 - Version [e.g. 22] 28cd780499342ab7b5dc906dd1d7d497e03a6da6

**Comment by gengqx** [comment]
When start a container,It would set up host device,make some soft link to the hardware device,so Current it need root access.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
