### ISSUE TITLE
Lane Change in Custom created map

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5739]
Hi Guys,

This is with respect to issue #4008.

I have created a custom created map with 2 lanes in same direction to test the lane change and overtake behavior. Below are the details.

a) Length - 320 m
b) Lane IDs 98_1_-1 and 98_1_-2
c) right neighbor and left neighbor has been updated as well.

The autonomous vehicle still doesn't do the lane change behavior. 

Can anybody please explain me what is missing in here ?

Thank you,
KK

**Comment by lesun90** [comment]
What planner you use.
if you use the EM, tune the parameter in planning_config.pb
also in planning_gflags (look for lane change parameter)

Good luck

**Comment by kk2491** [comment]
@lesun90 Thanks for the reply. Yes, I am using EM planner. 

I will check for the parameters need to be changed.

Thank you,
KK

**Comment by lesun90** [comment]
remember to restart planning modules, otherwise, the changes won't take effect.

**Comment by kk2491** [comment]
@lesun90 .. restart planning modules means restart bootstrap ??

**Comment by lesun90** [comment]
turn off and turn on again the planning module in dream view

**Comment by kk2491** [comment]
@lesun90 Got it. Thank you.

**Comment by CCodie** [comment]
Hi @kk2491 , can you please tell me how you made your custom created map ?
Did you use `Apollo Data Open Platform - Map Open Service` as described in this site ? [apollo_2_5_map_collection_guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_5_map_collection_guide.md)
Or did you use other tools to make your own HD Map ? (I also wonder there's other tools.)
Thanks ! :)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
