### ISSUE TITLE
Standard mode usage (start, stop, pause, continue, restart)

### ISSUE THREAD

**Issue by gladijos** [ApolloAuto/apollo#5740]
### System information

- **OS Platform and Distribution**:  (e.g., Linux Ubuntu 16.04)
- **Apollo installed from**: binary 
- **Apollo version**: 3.0

### Steps to reproduce the issue:
- switch on standard mode in dreamview
- switch on Canbus, Gps, control, planning, routing, localization
- "Start Auto" button  is inactive.

1. Why so? 
2. How can I start, pause and stop current routing session?
3. How can I apply routing request after completed another one? (Now I have to restart planning module)

**Comment by mickeyouyou** [comment]
A1. Some modules don't start or there is some exceptions throwed , like perception or not ?

A2&A3.  There is no need to restart planning, When you are in auto mode ,you can send another routing.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
