### ISSUE TITLE
相对地图与导航模式问题

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#5741]
- apollo 3.0

- ubuntu 16.04

- 相关模块 relative_map

- 问题

1、我们在调试apollo 3.0导航模式中参考了如下这份资料
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_use_apollo_2.5_navigation_mode_cn.md
     在文档中介绍了使用apollo 2.5的导航模式的步骤，这个相对地图的导航模式和相对地图的模式0、模式 1、模式2是什么关系？要使用导航模式需要在哪些配置文件进行配置？
2、从code中分析使用导航模式不需要Routing模块，将车开到录制参考线的起点，然后用navigator.py播放制作的参考线，如果不人为停止车，车会将沿着参考线一直行驶直至参考线终点？即导航模式无法设置终点吗？
3、我在apollo-master\apollo-master\scripts文件夹下看到了关于导航模式的脚本文件，
![1536766841 1](https://user-images.githubusercontent.com/19250516/45436542-9b0ebb00-b6e5-11e8-9709-c44901f0c9c9.png)
这几个脚本都是在开启各个module 同时将module配置成导航模式，所以这几个脚本和问题1中我们参考的文档里面列的使用dreamview开启各个模块(如下图)功能是一样的吗？如果是那么navigation_routing.sh关于导航模式的routing该如何使用？在dreamview上没有找到对应的routing按钮进行设置
![drive_car_in_navigation_mode](https://user-images.githubusercontent.com/19250516/45436765-16706c80-b6e6-11e8-8798-4ffb7f53cc7e.png)

上面是我们在调试中遇到想到的一些问题，有知道的小伙伴，非常感谢能提供一些帮助！

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
