### ISSUE TITLE
Is it possible build protobug messages outside docker?

### ISSUE THREAD

**Issue by alexbuyval** [ApolloAuto/apollo#5742]
Hi all!

For some reasons I would like to analyse Apollo ROS bag files on host machine under original ROS. 
However, there are no protobuf messages outside the docker. So if I am trying to listen such messages I got the error like the following:
```
ERROR: Cannot load message class for [pb_msgs/Chassis]. Are your messages built?
```
Is it possible to build theses messages on host machine? If so, how can I do it?

Thank you

Alex,

**Comment by jilinzhou** [comment]
Building those messages is straightforward using protoc tool.  But it is not going help you with standard ROS. The core ros libs have been modified to provide support protobuf msgs inside ROS. As my understanding, you can run apollo modified ROS on your host for sure but it takes some efforts to figure out all the dependancies and folders required to copy from docker to your host.

**Comment by alexbuyval** [comment]
I see.

Thank you!
