### ISSUE TITLE
用vscode进行debug时报错

### ISSUE THREAD

**Issue by Mushekwi** [ApolloAuto/apollo#5744]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.0

### Steps to reproduce the issue:
1.启动vscode，打开apollo目录，进行编译
   Ctrl+Shift+B
   编译成功
2.进入docker,启动Dreamview后台服务程序
   bash docker/scripts/dev_into.sh
   bash scripts/bootstrap.sh
   Dreamview成功启动
3.启动要调试的planning模块
   Dreamview分别点击“SimControl”，“Routing”，“Planning”以及“Route: Reverse Early Change Lane”
   成功生成全局导航路径
4.vscode进行debug
  单击F5
  debug窗口有如下提示
![screenshot from 2018-09-13 19 53 28](https://user-images.githubusercontent.com/25722327/45487058-bdf5a980-b78f-11e8-94a9-487f05a19701.png)
 在planning.cc添加个断点，则会报错
ERROR: Error while trying to enter break state. Debugging will now stop. Failed to find thread 1 for break event
 有时候也会报这个错误
 Unable to open 'syscall-template.S': File not found

求助！！！！！

**Comment by kk2491** [comment]
Did you try restarting the debug ?

**Comment by WangZhongjian** [comment]
@kk2491 试了，不好用啊

**Comment by lianglia-apollo** [comment]
We don't officially support vscode debug for now.

**Comment by natashadsouza** [comment]
@Mushekwi try using [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_apollo_in_vscode_cn.md) to help you get VSCode up and running. Let us know if you face any challenges.

**Comment by natashadsouza** [comment]
Closing as there has been no further communication on this topic.
