### ISSUE TITLE
关于汽车标定的问题

### ISSUE THREAD

**Issue by ZK-Zhou** [ApolloAuto/apollo#5745]
通过阅读“如何标定车辆油门和制动”我受益匪浅，可是依然有几个疑问：
1.输入x，y，z的值分别是x代表了加速的控制指令, y 代表了限制速度(mps), z 是减速指令,正值标识油门量，负值标识刹车量，那么x的具体物理量是？
2.数据处理之后输出的标定结果是油门和制动百分比吗？具体是怎么转化的呢？

**Comment by ZK-Zhou** [comment]
Hi old steel @mickeyouyou 
我按照您说的在moudels/canbus中寻找油门、刹车、转向具体转化过程，发现例如brake_60中的updatedata中制动踏板（pedal）的数值取值依然为百分比，而且通过x = pedal / 1.52590218966964e-05转化为可以用十六位表示的数值，0-65535是否可以认为就是最终转化结果呢？林肯车底盘会直接使用这个数值嘛？还是会在车底盘或者车ECU里进一步处理？
期待您的解答。

**Comment by wfgsy101** [comment]
底层会处理为制动力矩来控制车辆
