### ISSUE TITLE
Incorrect planning behaviour

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#5748]
The zip file attached herewith contains the video that explains the planning behaviour. In a nutshell, the vehicle skips intermediate segments to reach the destination. Instead of taking few right turns and then reaching its destination, it directly goes straight towards the destination. The segments/checkpoints are numbered 1 through 6. Instead of going in the order 1->2->3->4->5->6, it does from 1->5->2->6-> in a straight line. Please see the attached image as well.
[planning_issue.mp4.zip](https://github.com/ApolloAuto/apollo/files/2381176/planning_issue.mp4.zip)
![oie_8s7gw6m4v69d](https://user-images.githubusercontent.com/9420343/45519357-b976c400-b782-11e8-9378-84f3a8abc2ca.png)

**Comment by jmtao** [comment]
@ankitvora7 how did you define "intermediate segments" in your routing request? Can you send us your routing request, or the routing topic? thx

**Comment by ankitvora7** [comment]
@jmtao - Here's the routing request topic output

' header
 {
  timestamp_sec: 1538665197.79
  module_name: "dreamview"
  sequence_num: 1
}
waypoint {
  id: "800_1_-3"
  s: 17.9693358945
  pose {
    x: 586228.000258
    y: 4141126.35741
  }
}
waypoint {
  id: "1564_1_-5"
  s: 0.472174329836
  pose {
    x: 586303.574944
    y: 4141424.84706
  }
}
waypoint {
  id: "791_1_-1"
  s: 41.5642531516
  pose {
    x: 586443.990548
    y: 4141450.82704
  }
}
waypoint {
  id: "248_1_-2"
  s: 35.1322842063
  pose {
    x: 586376.875601
    y: 4141254.74004
  }
}
waypoint {
  id: "1559_1_-3"
  s: 6.30513082162
  pose {
    x: 586285.945672
    y: 4141354.32997
  }
}
waypoint {
  id: "49_1_-3"
  s: 34.1903740618
  pose {
    x: 586332.958858
    y: 4141542.37059
  }
}

---
'

**Comment by lianglia-apollo** [comment]
I think routing will ignore the intermediate circle in the current version. We can add the support for loops in a future release.

**Comment by jmtao** [comment]
@ankitvora7 we've logged this issue, and it will be supported in future release. 
we'll close this issue for now.

Thanks for supporting Apollo!
