### ISSUE TITLE
in StdPlanning::RunOnce() ,no status returned by EgoInfo::instance()->Update() call but check status after that.

### ISSUE THREAD

**Issue by kennethyu2017** [ApolloAuto/apollo#5753]
version: master 2018.09.10
file: modules/planning/std_planning.cc
function:  StdPlanning::RunOnce() 
description:
line 252: call EgoInfo::instance()->Update(), but that function returns 'true' other than status object.
but in the following line261 we check the status object:
 if (!status.ok()) {......
}.

at now, this will not cause running error , but just logical misleading.

**Comment by lianglia-apollo** [comment]
status is returned by init frame. Maybe it is better to put it closer to avoid confusion.

**Comment by kennethyu2017** [comment]
actually, right after init frame,  the  returned status is already immediately checked and will exit RunOnce due to error. And the following  Line261 status check I think should belong to EgoInfo::instance()->Update().

Line241:  status = InitFrame(frame_num, stitching_trajectory.back(), start_timestamp,
                     vehicle_state);
  if (!frame_) {
     ...
    return;
  }
...

Line252: EgoInfo::instance()->Update(stitching_trajectory.back(), vehicle_state,
                              frame_->obstacles());
...
Line261:if (!status.ok()) {
...

**Comment by lianglia-apollo** [comment]
I don't think there is an error. The status check at Line 261 is not for EgoInfo.

**Comment by kennethyu2017** [comment]
yes, the EgoInfo->Update() will always return true as success.
maybe put the status check and !frame check together is better.
thanks for reply.

**Comment by lianglia-apollo** [comment]
Yes, thanks, we will make modifications in a new release soon.
