### ISSUE TITLE
Routing/Reference curve

### ISSUE THREAD

**Issue by wckorealsh** [ApolloAuto/apollo#5754]
**Describe the bug**
If routing request includes circling around a block of the map, then it simply skips some route. See the example below. 

-- is the horizontal lane, | is the vertical lane, all connected geometrically.
--1--|--2--3--|--5--\
------|----4---|
If the request is 1-2-3-4-2-3-5, then it goes 1-2-3-5 by skipping waypoint 4

**To Reproduce**
1. Open Sunnyvale big loop map
2. Request routing as follows
(586253.58, 4141222.81) - starting point  
(586291.00, 4141379.19),
(586414.53, 4141458.25),
(586459.02, 4141194.94),
(586303, 4141423.60),
(586340.30, 4141572.62) - end point
3. Start the car in autonomous mode

**Expected behavior**
Middle waypoints are skipped 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16]
 - Browser [Chrome]

**Additional context**

**Comment by apollodevcommunity** [comment]
首先，routing 是寻找从起点到终点的最优路径，它的一个优化目标就是路径最短，一般都是使用A*算法。对于闭环的路线，routing 时偏向于寻找总路线长度比较短的，所以最后就会跳过闭环路线的一部分。那么怎么解决呢？一个简单但是实践性强的做法是，你可以把闭环路拆分，插入一个终点；你先加载第一段路线，车辆即将到达第一个终点后，你再加载下一段的路线。以你的为例，原来的路线是 1-2-3-4-2-3-5， 你可以以修改为  起点1-1-2-3-4-终点1；起点2-4-2-5-终点2。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=600
