### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by TifferPelode** [ApolloAuto/apollo#5755]
**Describe the bug**
When I run `bash apollo.sh build`  on my PC, it show me this:
```
tiffer@in_dev_docker:/apollo$ bash apollo.sh build       
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
[INFO] Building on x86_64...
[INFO] Building with --jobs=8 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Found 1802 targets...
ERROR: /apollo/modules/canbus/common/BUILD:5:1: undeclared inclusion(s) in rule '//modules/canbus/common:canbus_common':
this rule is missing dependency declarations for the following files included by 'modules/canbus/common/canbus_gflags.cc':
  'bazel-out/local-dbg/genfiles/external/com_github_gflags_gflags/gflags/gflags.h'
  'bazel-out/local-dbg/genfiles/external/com_github_gflags_gflags/gflags/gflags_declare.h'
  'bazel-out/local-dbg/genfiles/external/com_github_gflags_gflags/gflags/gflags_google.h'.
INFO: Elapsed time: 4.682s, Critical Path: 0.91s
============================
[ERROR] Build failed!
[INFO] Took 6 seconds
============================
```
I just  follow the step in README file, and I compile this passed before.
After I re-download it and compile again, it show me this.

Can someone tell me how to debug this problem??

**Comment by hahanigehaha233** [comment]
Maybe you should read [this](https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide).

**Comment by lianglia-apollo** [comment]
Please delete folder {HOME}/.cache/bazel/_bazel_{USER}, and run ```bazel clean```.

**Comment by DiarmuidMccarthy** [comment]
I had the same issue, with same errors
It turn out I had a directory called apollo , with a directory called apollo.
I went into apollo/apollo/ then went into docker

**Comment by lookcat** [comment]
我也遇到这个问题了， 执行delete folder {HOME}/.cache/bazel/bazel{USER}, run bazel clean后。
bash apollo.sh build --local_resources 2048,1.0,1.0sed: 1: "WORKSPACE": invalid command code W
Must run apollo.sh in dev docker or release docker

**Comment by TifferPelode** [comment]
Thx.
After tried lianglia's suggest, I solved this problem.
Just delete the bazel folder & rebuild.

**Comment by arappazzo** [comment]
Same issue, see attached file for complete log of command _bash apollo.sh build_.
Please reopen this issue.

**Comment by arappazzo** [comment]
[log2.txt](https://github.com/ApolloAuto/apollo/files/3767672/log2.txt)

Same issue, see attached file for complete log of command bash apollo.sh build.
Please reopen this issue.
