### ISSUE TITLE
Issue regarding lane post-processing

### ISSUE THREAD

**Issue by sopXx** [ApolloAuto/apollo#5757]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- Run cc_lane_post_processor_test from module/perception/obstacle/camera/lane_post_process using sample data provided in modules/perception/data/cc_lane_post_processor_test
-The resulting image looks like:
![test_lane_objects_image](https://user-images.githubusercontent.com/21326200/45577342-62c7c380-b830-11e8-80a3-43f835d1b334.jpg)

Only lane mask is showing in the resulting image. **There is no lane marking**. 
I tried to debug the issue. It turns out:
the lane object is never found(=0) -> because the graph_size is 0 -> because the connected component is 0.
Looks like the problem originated from connected component generator, possibily some bug in GreedyGroupConnectAssociation(). Could somebody help clarify what is going on? Thanks!

**Comment by techoe** [comment]
Please use Apollo 3.0 for the new lane line detection.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
