### ISSUE TITLE
bash scripts/localization.sh start problem

### ISSUE THREAD

**Issue by joon5283** [ApolloAuto/apollo#5758]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Hello. I am trying to test localization module individually. So, i did filter /apollo/localization/pose topics from demo_2.0.bag file. And I command bash scripts/localization.sh start and rosbag play my new bag file. (Probably it is right way to test my own localization code) And below error message is happened. I saw that this error message is happened because one of the message name is changed when Apollo version is going to be 3.0. And is there any method to solve this problem? Do I have to use Apollo 2.5 version?

In advance, thank you for reading my issue and helping me.

### Supporting materials (screenshots, command lines, code/script snippets):
/apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1536953554.999248115]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.

**Comment by zhouyao4321** [comment]
The message type of topic /apollo/sensor/gnss/corrected_imu has been changed in apollo3.0. You can try to filter /apollo/sensor/gnss/corrected_imu topic from demo_2.0.bag. And I recommand this tutorial if you want to try localization module. https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md

**Comment by natashadsouza** [comment]
Closing this issue as there has been no follow up.

**Comment by flnlucifer** [comment]
> The message type of topic /apollo/sensor/gnss/corrected_imu has been changed in apollo3.0. You can try to filter /apollo/sensor/gnss/corrected_imu topic from demo_2.0.bag. And I recommand this tutorial if you want to try localization module. https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md

@zhouyao4321 Hi , I suffer a same issue #7077 , could you help to check it ? thanks!
