### ISSUE TITLE
Connect roads on a junction

### ISSUE THREAD

**Issue by LyubimovMaxim** [ApolloAuto/apollo#5759]
Hi Guys,
Can anybody please explain me how I can connect roads on a junction ? I tried co use connection record for it, but I haven't any results. 

Thank you

**Comment by LyubimovMaxim** [comment]
Now I have this map:
![screenshot from 2018-09-17 12-51-20](https://user-images.githubusercontent.com/27014132/45616597-9dbc3800-ba78-11e8-930f-2d6fabdee7d0.png)
and this file base_map.txt
[base_map.txt](https://github.com/ApolloAuto/apollo/files/2388063/base_map.txt)
Can anybody explain me  how connect lines or, if it's possible send example of junction

**Comment by SanduIrina** [comment]
as far as I know, you have to create a road for each connection in the junction. Lets say your roads are left, right, up and down. You would have to define roads for the following connections: L-R, L-U, L-D, U-D, U-R and R-D. This is how it looks like for a 3 road junction:
![screenshot from 2018-09-19 12-39-43](https://user-images.githubusercontent.com/37019001/45745321-47323380-bc09-11e8-8e46-0b0939b2ce1e.png)

**Comment by LyubimovMaxim** [comment]
Thank you for answer, I thought it possible to achieve automatic connection. Now I create lane  for each connections  on junction and it's working!
![screenshot from 2018-09-25 08-55-25](https://user-images.githubusercontent.com/27014132/45995471-d7a4c400-c0a0-11e8-9efe-f55acdec19bc.png)
