### ISSUE TITLE
Is there any change to release a caffe library with CUDA 9.0?

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#5763]
We want to use apollo in a new graph card device,Old Cuda8.0 and GTX1080 could not satisfy our demand, I would be great to release the internal caffe code. Otherwise if can release a caffe with CUDA9.0,It would be great help

**Comment by hmdt** [comment]
All the new GPUs are capable of running previous CUDA versions. There is no need to have a caffe with CUDA 9.0. Just install the compatible driver, exactly the same as in your host machine, inside the docker. It will work!
