### ISSUE TITLE
Running Apollo Azure Scenarios Locally

### ISSUE THREAD

**Issue by saurabhjha1** [ApolloAuto/apollo#5765]
Hi, 

I want to validate some of my algorithms with respect to security, safety, resiliency of autonomous vehicles and want to inject various kinds of faults while Apollo is running. 

Plan of injection: AVFI: Fault Injection for Autonomous Vehicles
Link: http://sjha8.web.engr.illinois.edu/resources/DSN-FA-2018.pdf

To successfully show that my created algorithms are fault-tolerant and provide defence against adversarial examples, I want to be able to run a closed-loop simulation  (either on cloud or locally) and inject faults in GPUs and CPUs while running Apollo (locally) as I require low-level driver access to inject faults/attacks into the hardware. 

I looked at the following two previously opened issues
https://github.com/ApolloAuto/apollo/issues/4626
https://github.com/ApolloAuto/apollo/issues/4822

I do not think this suffices, as they are not closed-loop simulation. I want the vehicle to react to new situation created by my faults and this way I get access to only demo scenarios. Those 100 scenarios on Azure are complete (in some sense) and represent real-world situations. 

I would really appreciate any help with this.

**Comment by unacao** [comment]
Hi,

The Apollo simulation cloud service mainly simulates the different behaviors of prediction and planning modules based on perception output given in the scenarios. https://azure.apollo.auto/getStart?locale=en-us You can register and activate your account to give it a try and see if it fits your needs. If you want to change something on the hardware driver level, it may not be able to help.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
