### ISSUE TITLE
How to keep offline_visualizer_tool on the monitor?

### ISSUE THREAD

**Issue by IneverStop** [ApolloAuto/apollo#5766]
Hello guys!
I want to change a single pcd file to see what will happen, here is my steps:
- I move the pcd file and pose file to another place, together with pose.txt and stamps.txt(Only have information of this pcd file)
- Then change `/apollo/modules/perception/tool/offline_visualizer_tool/conf/offline_lidar_perception_test.flag` ,reset `--pcd_path` and `--pose_path`
- Run offline_visualizer_tool

Seems works, but visualizer monitor just stay a few seconds, because there is only one pcd file.

My questions  how to keep the monitor stay more time?Is there a command like `..../offline_lidar_visualizer_tool -stay`? 

I will be very appreciate if someone help me!

Good good study!

**Comment by techoe** [comment]
Thank you for using Apollo! In Apollo 3.5, we added cyber_visualizer to visualize all sensor output. Please use it and let us know if you have any question.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
