### ISSUE TITLE
how to driver Lidar imu and camera  on software?

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5769]
Hi  Apollo team:
      you know, when we use the keyboard or mouse and so on, they always have themselves'drivers. so 
I want to know where is lidar 、camera、imu、gps and radar‘driver ? where is lib to use for us about them ? in dir(apollo/module/drivers)，this  seems is different with linux'driver, so  I  can't understand, Please introduce.  Thank  you !   you!

**Comment by breakisx** [comment]
thank  you !

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
