### ISSUE TITLE
Significance of Evaluator and Predictor - Prediction module

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5770]
Hi Guys,

Could anybody please explain the functions of Evaluator and Predictor in Prediction module.I have been going through the prediction module code and need help in clarifying the below doubts. 

1. Functionalities of Evaluator and Predictor.
2. As per Apollo architecture, there are 2 types of methods used in predicting the obstacle trajectory. Model based and Data driven. 
a. Does model based have a trained neural network model ?
b. Whether both methods work in parallel or it depends on the scenario.?
c. If it is selected based on the scenario, kindly help me with some examples.
3. What is the method used in case of Lane sequence based prediction ? Model based or Data driven ?
4. Could you please provide me the reference paper for the Prediction module ?
 
Thank you,
KK

**Comment by kk2491** [comment]
@kechxu Hi . Could you please clarify my doubt

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
