### ISSUE TITLE
Add a new module in dreamview

### ISSUE THREAD

**Issue by SanduIrina** [ApolloAuto/apollo#5771]
Hi, can you give some hints as to how can I add a new module in Dreamview? I want to add a module that will activate a steering network that will contribute to the decisions made by the planner. I want to be able to turn it on and off like any other module.

**Comment by natashadsouza** [comment]
@SanduIrina it is not currently possible to do so in Dreamview. But I have included it as a feature request and is definitely something the team will review. Thank you for your request.

**Comment by SanduIrina** [comment]
@natashadsouza Thank you, this worked fine. I have other questions about how to add my own steering network to the planner but I think I should open another issue for this.

**Comment by natashadsouza** [comment]
Great! I am glad it worked out. Feel free to open another issue for your planner.
Currently closing this one!
