### ISSUE TITLE
sensor_calibration.sh doesn't work

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#5773]
I want to do the calibration work from camera to lidar, I have confirmed that all topics can output right data, but when I begin to calibrate with param lidar_camera, there is nothing output, no error, no tips, no warning, just nothing output.  
During our calibration work, the topic frequency is a little different, while the official specified configuration is in the following

    |   传感器      |  Topic名称                                 | Topic发送频率（Hz）|
	| ------------ | ----------------------------------------- | ----------------- |
	| Short_Camera |  /apollo/sensor/camera/traffic/image_short | 9                 |
	| LiDAR        |  /apollo/sensor/velodyne64/compensator/PointCloud2  | 10                |
	| INS          |  /apollo/sensor/gnss/odometry              | 100               |
	| INS          |  /apollo/sensor/gnss/ins_stat              | 2                 |

Our topic's frequency is 

    |   传感器     | Topic名称                                 |Topic发送频率（Hz）|
	| ------------ | ----------------------------------------- | ----------------- |
	| Short_Camera | /apollo/sensor/camera/traffic/image_short | 30                 |
	| LiDAR  | /apollo/sensor/velodyne64/compensator/PointCloud2  | 10                |
	| INS          | /apollo/sensor/gnss/odometry              | 50               |
	| INS          | /apollo/sensor/gnss/ins_stat              | 50                 |

I think the calibration should work normally if the topic frequency is faster than the requested, but if it is lower, will it affect the calibration work?
Another problem is that when we do the calibration work, the speed of the vehicle is about 7-8km/h, does this will also affect the calibration work?
Does the calibration have a request about time or distance?

**Comment by xinwf** [comment]
All param doesn't work, does this have a relation with the distance or time ?

**Comment by xinwf** [comment]
@weidezhang  @techoe

**Comment by CCodie** [comment]
@xinwf Hi, I'm now trying to do radar to camera calibration and I got a problem.
Did you executed any calibration tool ?
I also wonder that you got an output file(radar extrinsic file as `.yaml` file) after you executed `bash sensor_calibration.sh radar_camera`.

**Comment by xinwf** [comment]
@CCodie , it does create the output file, but there is no any content in it. Now, I'm still doing the calibration between lidar and camera, have you finished this procedure? If you do, which calibration tool do you use?

**Comment by CCodie** [comment]
@xinwf , I'm planning to do radar to camera calibration first. And I'll leave the comment when I'm doing the LiDAR-Camera Calibration.

**Comment by xinwf** [comment]
@CCodie ,ok,waiting for your good news，about the lidar-camera calibration, I recommend you to use the official version of ros, it does work, although I haven't got the result.

**Comment by natashadsouza** [comment]
@xinwf the Hz of his sensor looks good. and driving speed is OK. but based on this information, the team cannot diagnose the issue. Can they provide more information? for example, about the driving scenarios, the data collection time length, even the simulation logs. Thanks!

**Comment by JonathanJones92** [comment]
Our team provided all the topics that required. However, there is nothing coming out, no log and results. The  only thing happen is that the empty folders were created. The scripts were keep running and running .... @natashadsouza @CCodie @techoe @weidezhang   Sincerely asking for help from Apollo team as multiple dev teams are pending on this issue. THX

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
