### ISSUE TITLE
Doubt about CalculatePathCost 

### ISSUE THREAD

**Issue by ipatient-zju** [ApolloAuto/apollo#5782]
since the total_level =  path_waypoints.size() at line 149 of [dp_road_graph.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/toolkits/optimizers/road_graph/dp_road_graph.cc), the level is always less than total_level, the logic at line 150-154 of [trajectory_cost.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/toolkits/optimizers/road_graph/trajectory_cost.cc) is never used?

**Comment by jilinzhou** [comment]
http://www.cplusplus.com/reference/vector/vector/size/

size_type size() const noexcept;

Return size
Returns the number of elements in the vector.

This is the number of actual objects held in the vector, which is not necessarily equal to its storage capacity.
