### ISSUE TITLE
Why is Radar commented out in the dag_streaming_camera_lidar_radar.config?

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#5783]
Why is Radar commented out in the dag_streaming_camera_lidar_radar.config?

Is there something wrong with it?  Not ready yet?

Thanks

**Comment by weidezhang** [comment]
it haven't been tested yet for radar.  we are still working on that.

**Comment by snuffysasa** [comment]
So LiDAR + Radar works  and Radar + Camera works

but all 3 has not yet been tested / implemented?

**Comment by techoe** [comment]
In Apollo 3.5, we fused all three sensors. Thank you.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks!
