### ISSUE TITLE
./apollo.sh build FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by sudhanvakudlapur** [ApolloAuto/apollo#5784]
I followed the steps to create my own localization module as in https://github.com/ApolloAuto/apollo/blob/master/modules/localization/README.md

### System information

- Ubuntu 16.04LTS
- **Apollo installed from source**
- **Apollo version 2.0**

I am getting the following error when I build using $./apollo.sh build.

ERROR: /apollo/modules/localization/BUILD:23:1: C++ compilation of rule '//modules/localization:localization_lib' failed (Exit 1)
modules/localization/localization.cc: In member function 'void apollo::localization::Localization::RegisterLocalizationMethods()':
modules/localization/localization.cc:48:27: error: expected initializer before '.' token
 void localization_factory_.Register(LocalizationConfig::KA, []()->LocalizationBase* { return new KALocalization(); });
                           ^
modules/localization/localization.cc:48:119: error: expected primary-expression before ')' token
 void localization_factory_.Register(LocalizationConfig::KA, []()->LocalizationBase* { return new KALocalization(); });
                                                                                                                       ^
modules/localization/localization.cc:48:119: error: expected ';' before ')' token
INFO: Elapsed time: 5.096s, Critical Path: 2.94s
FAILED: Build did NOT complete successfully
============================
[ERROR] Build failed!
[INFO] Took 6 seconds
============================

**Comment by lianglia-apollo** [comment]
It looks like some c++ language issues. Please check your implementation of localization.
