### ISSUE TITLE
Dreamview at offlineview mode

### ISSUE THREAD

**Issue by levuphuong** [ApolloAuto/apollo#5787]
I am testing apollo 2.0 dreamview at offline view mode.
Actually I have built frontend with below command. everything is fine. It created dreamview/dist_offline folder.
`yarn build_offline`
But when I go http://localhost:8888 .Then console show "ERROR: missing required parameter(s)"
The error is from websocket_offline.js
It checks some params on http query string. 
` params && params.url && params.id && params.map`
So what is correct query string we need to go to offlineview mode.

Thanks.

**Comment by vlin17** [comment]
May we know the reason of using the offline view? offline view is for playing back scenarios frame by frame, which requires special server to feed the frame data. If you want to playback rosbag, normal dreamview is enough.

**Comment by levuphuong** [comment]
I just wonder what's going with offline view. And how to set up to run at offline view.
Thanks

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
