### ISSUE TITLE
A bug with included header file location in lidar_velodyne module?

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#5789]
In modules/drivers/lidar_velodyne/common/socket_input.h, this [included header file](https://github.com/ApolloAuto/apollo/blob/23b726544d268e969bca4a3955ca65c91cc4c84a/modules/drivers/lidar_velodyne/common/socket_input.h#L25) seems a bug. Should it be `#include "modules/drivers/lidar_velodyne/driver/input.h"` instead?

**Comment by lianglia-apollo** [comment]
It will be fixed in the next release. Thanks!
