### ISSUE TITLE
Data Module

### ISSUE THREAD

**Issue by jiwonjoung** [ApolloAuto/apollo#5793]
I am having trouble understanding data collection in Apollo. 
What is the difference between the 'data module' and the 'e2e module'? 
Can I activate these in simulation only mode? 

I am interested in collecting data from raw sensor source for analysis. Is there a way to do this in Apollo?

**Comment by xiaoxq** [comment]
Please just ignore there two modules, which are not commonly used.

For data collection, we simply call "./scripts/record_bag.py".

**Comment by jiwonjoung** [comment]
Is there a way to extract the data in the bag to csv?
