### ISSUE TITLE
Delphi ESR Driver removed?

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#5794]
I see tons of references to modules:drivers:delphiESR,

However, I cannot find delphiESR driver anywhere in /modules/drivers?

I only see Conti, ultrasonic, and racobit

was it removed?

**Comment by natashadsouza** [comment]
@snuffysasa yes we do not currently support Delphi Radar currently. Here are the 2 radars we [support](http://apollo.auto/platform/hardware.html). The references will be removed from both documentation and code soon. Thank you for your patience.

**Comment by snuffysasa** [comment]
@natashadsouza 

Okay Thank you, will try to manually convert the Delphi data to similar format as the Conti and feed that into the radar processing subside and see what kind of results I get.

**Comment by natashadsouza** [comment]
Thanks @snuffysasa ... Do let us know if you are able to successfully run Apollo with the Delphi radar and please share your findings with the rest of the community.

**Comment by zhuangli1987** [comment]
i think we do have a internal version driver for Delphi ESR  :)

**Comment by snuffysasa** [comment]
Cool, we are still getting the Delphi ESR set up.  

The general plan was to use the autonomouStuff driver to get tracked object ros messages, then try to build a converter to reformat that data to be in ContiRadar msg format:

https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/proto/conti_radar.proto

and then send to the radar_process_subnode

**Comment by snuffysasa** [comment]
The AStuff Delphi messages does not appear to have a probability of existence score.. And it appears the radar_subnode does use "probexist" value in the radar object builder. I am wondering how important is this value? What would happen to the fusion if I leave this score blank or put all to 100% or something?
