### ISSUE TITLE
diagnostics 觀察到的Delay 現象

### ISSUE THREAD

**Issue by Brox0931** [ApolloAuto/apollo#5799]
### System information

- **OS Platform and Distribution Linux Ubuntu 16.04**:
- **Apollo installed from source**:
- **Apollo version 3.0)**:

我們將Apollo 提供的bag  過濾Planning Topic,
透過EM Planner 從新計算新的Planning Path

從diagnostics 觀察到Planning 的 Interval 是符合configure的100 ms 
但是Delay 卻高達60 ms 
ROS 不是改用Share memory 的方式達到Real Time 的效果嗎?
想請問會有這麼高的Delay 是什麼原因造成的呢?

謝謝

**Comment by jmtao** [comment]
@Brox0931 Apollo doesn't use ROS since 3.5 (released Jan 2019).  Please test with latest code. 

We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
