### ISSUE TITLE
I have a big question. does it CAN network Support vehicle?

### ISSUE THREAD

**Issue by SUNDREAM2018** [ApolloAuto/apollo#5800]
Hello. 
I am a self-driving Korea researcher.
We will not use  NVIDIA drive PX2 anymore.
I want to use it as an Apollo system.

Is there a specific set of vehicles that support CAN communication in the Apollo system? 
and I wonder if your existing high-performance PC works well.

also, We have Hyundai 2019 Santafe in our lab. 
Is CAN communication supported? 
If so, I wonder if the accelerator, brake, and steering of the handle are all supported.

I would like to have a list of supported vehicles.

thanks

**Comment by hzdsdhr** [comment]
Or you can buy a vehicle which apollo supports, check: http://apollo.auto/vehicle/certificate_cn.html

**Comment by SUNDREAM2018** [comment]
Thanks to Reply. :)
You said vehicle control is possible through by-wire control.
So. What equipment should I use? By-wire control or Communication
One company says we should use a Vector canoe, right?

**Comment by wfgsy101** [comment]
CANOE would be very helpful, some power module related devices and wire connecting may need

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
