### ISSUE TITLE
URL_LIST init error in rosbag_helper.py 

### ISSUE THREAD

**Issue by taoxianfeng** [ApolloAuto/apollo#5815]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

this website is not exist?

![image](https://user-images.githubusercontent.com/21098212/46246898-93b21600-c436-11e8-95c0-f77d63d4d048.png)

**Comment by taoxianfeng** [comment]
sorry , my mistake , it's exist

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
