### ISSUE TITLE
vs code can't go to definition with F12 in apollo.

### ISSUE THREAD

**Issue by hahanigehaha233** [ApolloAuto/apollo#5816]
When I want to use F12 to find a function definition, I set IncludePath in c_cpp_properties,But I have no idea to set the virtual docker image dir to where I read dir.

**Comment by hahanigehaha233** [comment]
I run `gcc -v -E -x c++ -` in docker contianr
```
/home/tmp/ros/include
 /usr/local/cuda-8.0/include
 .
 /usr/include/c++/4.8
 /usr/include/x86_64-linux-gnu/c++/4.8
 /usr/include/c++/4.8/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
```

But it doesn't work.

**Comment by natashadsouza** [comment]
@hahanigehaha233 I am not sure we understand your question. Could you clarify what you are trying to achieve here.
