### ISSUE TITLE
use version 2.0 & version 2.5

### ISSUE THREAD

**Issue by TZVIh** [ApolloAuto/apollo#5817]
Hey,
I am new with apollo.

- Does the 2.5 version have the ability of urban driving?

- If I have a car with hardware installed for 2.0 version, can I upgrade the software to 2.5 version and it will work?

- If I want urban and highway driving, what should I do? (maybe move between the versions?  does it possible?)

Thanks!

**Comment by natashadsouza** [comment]
@TZVIh thank you for your interest in Apollo.

- Does the 2.5 version have the ability of urban driving?
       A. Yes Version 2.5 is an upgrade from Version 2.0. It can navigate on simple urban scenarios.
- If I have a car with hardware installed for 2.0 version, can I upgrade the software to 2.5 version and it will work?
        A. Please take a look at our [ReadMe](https://github.com/ApolloAuto/apollo/blob/master/README.md) for all the additional requirements
- If I want urban and highway driving, what should I do? (maybe move between the versions? does it possible?)
         A. Yes as mentioned in A1. Version 2.5 is an upgrade

Thanks!

**Comment by TZVIh** [comment]
Thanks for your answer.
I saw this blog: https://medium.com/apollo-auto/deep-dive-on-apollo-2-5-1e716ec94617
can you tell me what is the other differences between 2.0 & 2.5?

**Comment by natashadsouza** [comment]
@TZVIh our [ReadMe](https://github.com/ApolloAuto/apollo/blob/master/README.md) will give you the best insight into the differences.

**Comment by TZVIh** [comment]
Thanks!
I am confuse.
q1: can I use version 2.5 without the lidar and it will work in urban?
q2: the Hd map is not relevant in 2.5 version and higher?

**Comment by apollodevcommunity** [comment]
-As far as I know   Apollo 2.5 support highway driving where may be in some limited area.-You can get 2.5 version from https://github.com/ApolloAuto/apollo ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=585
