### ISSUE TITLE
Is the system incompatible? with Radar, Camera, GNSS

### ISSUE THREAD

**Issue by SUNDREAM2018** [ApolloAuto/apollo#5818]
Hello. I am a self-driving Korea researcher.
We will not use NVIDIA drive PX2 anymore. 
I want to use it as an Apollo system.

Anyway, I have a few question.

Q1. Does Apollo System not support Ellipse2-D INS?
Q2. Dose Apollo System not support continental ARS441, continental ARS510?
Q3. How many cameras can I install? and Which Hardware compatible? 
EX) I have a  continental MFS430, MFS430 cameras

thank you.

**Comment by YangHan101** [comment]
The compatible hardware devices that we know of are listed on [this web page](http://apollo.auto/platform/hardware.html). The other ones we have not tested yet. If you have the sample and time to explore please let us know what you find.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks!
