### ISSUE TITLE
Linker issue or missing external files while compiling the modules independently.

### ISSUE THREAD

**Issue by shifakhan4892** [ApolloAuto/apollo#5820]
Hi,
I am trying to build modules independently just like how @xiaoxq @hongkedavid suggested using "bazel build ", however i am getting the following error :

ERROR: missing input file '@ros//:include/kdl_conversions/kdl_msg.h'.
ERROR: /home/shifa/.cache/bazel/_bazel_shifa/540135163923dd7d5820f3ee4b306b32/external/ros/BUILD.bazel:5:1: @ros//:ros_common: missing input file '@ros//:include/kdl_conversions/kdl_msg.h'.
ERROR: /home/shifa/.cache/bazel/_bazel_shifa/540135163923dd7d5820f3ee4b306b32/external/ros/BUILD.bazel:5:1 1 input file(s) do not exist.
INFO: Elapsed time: 232.921s, Critical Path: 12.12s

Can anyone please guide me of why it has this dependency issue ? Also to use Clang++ as the compiler for this should I set CC and CXX variables or is there a better method ?

**Comment by xiaoxq** [comment]
Hi Shifa,
Actually we didn't test clang extensively in this version, which is still an ongoing effort.

**Comment by natashadsouza** [comment]
@shifakhan4892 thank you for your interest in Apollo. If you were able to test Clang and were successful, do share it with the community. 
Currently closing this issue.
