### ISSUE TITLE
Question about lane-change behaviors using EM planner and LATTICE planner

### ISSUE THREAD

**Issue by luqiang21** [ApolloAuto/apollo#5824]
### System information

- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **Apollo built from (source)**:
- **Apollo version (3.0)**:

Hi there,

I tried to use both planners for lane-change. I found that EM planner takes a very long distance to complete and the trajectory is very smooth. However, the LATTICE can complete the lane-change in a very short distance while the speed was almost not decreased. Can you tell me the reason behind this? Is that true LATTICE planner is not considering passenger comfort?

Thank you so much.

**Comment by lianglia-apollo** [comment]
In general, the lane change behaviors are controlled by a list of parameters. We believe both algorithm will achieve similar behavior if those parameters are adjusted properly. Please refer to the actual code for details.

**Comment by luqiang21** [comment]
@marcusvinicius178 I don't remember clearly. But it seems you can only use it in navigation mode. You can follow document [here](https://github.com/ApolloAuto/apollo/blob/master/modules/tools/navigation/config/README.md) to see how to change planner type for navigation mode.
