### ISSUE TITLE
How can I generate routing_map from xml file?

### ISSUE THREAD

**Issue by fukushi0294** [ApolloAuto/apollo#5825]
Hello.

I want to use my own opendrive map in Apollo. 

So I have tried generate routing_map by using base_map.xml in apollo/modules/map/data/sunnyvale_loop as a trial.
I made new directory named Mymap and I have only placed base_map.xml in this directory.
After then, I used following commands.
```
dir_name=modules/map/data/Mymap # example map directory
./scripts/generate_routing_topo_graph.sh --map_dir ${dir_name}
```
But it does not go well.

> `./scripts/generate_routing_topo_graph.sh: line 27: 10604 Segmentation fault`

How can I generate routing_map from xml file?

**Comment by xiaochao00** [comment]
@guoweiwan 关于这个问题有更新吗

**Comment by daohu527** [comment]
@fukushi0294 Apollo simplifies the opendrive format, so it does not support generating sim maps directly from opendrive format maps.

You can try to convert the map in opendrive format to apollo and then convert.
