### ISSUE TITLE
clone of old version

### ISSUE THREAD

**Issue by TZVIh** [ApolloAuto/apollo#5826]
Hey,
How can I clone old version(e.g. 2.0)?
If mutual bug  (e.g. from version 3.0 & version 2.0) have found, do you fix the old version ?
Thanks!

**Comment by lianglia-apollo** [comment]
We suggest using the latest version to minimize the possibility of facing bugs.

**Comment by TZVIh** [comment]
Thanks! 
if I dont have some of the hardware that version 3.0 need (ASU etc.) can I use the monitor and guardian moduls?

**Comment by storypku** [comment]
Stale issue closed.
