### ISSUE TITLE
Apollo 2.0 doesn't work anymore ..!!!!

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5829]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 2.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Download the apollo version 2.0 and run `bash apollo.sh build'
Error details given below <br /> 
```
include/localization_integ.h: No such file or directory
```
### Supporting materials (screenshots, command lines, code/script snippets):

    [INFO] Building on x86_64...
    INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
    INFO: Analysed 1325 targets (12 packages loaded).
    INFO: Found 1325 targets...
    ERROR: /apollo/modules/localization/msf/BUILD:5:1: C++ compilation of rule '//modules/localization/msf:msf_localization' failed (Exit 1)
    In file included from modules/localization/msf/msf_localization.cc:17:0:
    ./modules/localization/msf/msf_localization.h:44:40: fatal error: include/localization_integ.h: No such file or directory
     #include "include/localization_integ.h"
                                        ^
    compilation terminated.
    INFO: Elapsed time: 31.381s, Critical Path: 7.14s
    FAILED: Build did NOT complete successfully
    ============================
    [ERROR] Build failed!
    [INFO] Took 101 seconds
    ============================
    kishor@in_dev_docker:/apollo$ cd 

I am trying to build Apollo 2.0 version but now I am getting the error mentioned above. It was working fine before. 

Could you please let me know if there is any changes made to the docker. Apollo 3.0 version works fine without any issues. 

Thank you,
KK

**Comment by zhxt** [comment]
It seems that the header file was removed from the latest docker image(localization_volume-x86_64-latest) .  Which is now in the source directory from the latest source tree `modules/localization/msf/local_integ/localization_integ.h` ([being open sourced?](https://github.com/ApolloAuto/apollo/commit/412a5ecd0df58cfb263fa324db58442fb81d3b16)). 

I think you can hack the dev_start.sh to use a early version data volume `localization_volume-x86_64-weekly` as a workaround till you got a solution from the official team.
```
# in image localization_volume-x86_64-weekly :
#ls /usr/local/apollo/local_integ/include/
gnss_solver.h         gnss_struct.h         lidar_locator.h       localization_integ.h  pose_forcast.h        sins.h                sins_data_transfer.h  sins_struct.h

# in image localization_volume-x86_64-latest: 
# ls /usr/local/apollo/local_integ/include/
euler_tf.h            gnss_solver.h         gnss_struct.h         lidar_locator.h       pose_forcast.h        sins.h                sins_data_transfer.h  sins_struct.h
/ # 
```

**Comment by kk2491** [comment]
@zhxt Thanks for the input. I will try if I can get the earlier version of images by modifying `dev_start.sh` script.

**Comment by kk2491** [comment]
@zhxt I was able to get Apollo 2.0 working. Thank you.

**Comment by zhxt** [comment]
@kk2491 That's great. My pleasure.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks @zhxt :)
