### ISSUE TITLE
How to create HD map

### ISSUE THREAD

**Issue by TZVIh** [ApolloAuto/apollo#5830]
Hey,
Can I create HD map by myself?

**Comment by LitoNeo** [comment]
Hi, have you found the method yet ?

**Comment by hect1995** [comment]
I am interested as well in creating my own map

**Comment by apollodevcommunity** [comment]
你好，我所知目前自己制作高精地图创建有3个方法：1、自己开车记录pose lidar等数据，提交给apollo map 云服务。（开题云服务请联系apollo），2、使用roadrunner 倒车pose gis 路径，导入点云，创建3维场景，导出apollo 格式的高精地图，详见roadrunner doc。3、使用lgsvl unity 开源工程，基于unity 开源的3维仿真地图创建，可以支持pose、点云导入，输出apollo 格式高精地图。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=577
