### ISSUE TITLE
manual mode

### ISSUE THREAD

**Issue by jiwonjoung** [ApolloAuto/apollo#5833]
Hello! 
I have some questions about the apollo auto manual mode. 

How do I activate manual mode from the dreamview interface? 
If I override my car system while it is running Apollo auto, can it detect and acknowledge my override? 
If so, how sensitive is the override detection system?

**Comment by vlin17** [comment]
The mode displayed on dreamview is controlled by chassis's [DrivingMode](https://github.com/ApolloAuto/apollo2/blob/master/modules/canbus/proto/chassis.proto#L12).  As long as your follow the protocol of chassis's DrivingMode correctly, dreamview will be able to "detect" and display it.

**Comment by jiwonjoung** [comment]
So there is no way I test the vehicle's behavior in manual mode through the Dreamview interface?

**Comment by vlin17** [comment]
Unfortunately, Dreamview doesn't support this function. 

The good news is that our [hmi_worker](https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/backend/hmi/hmi_worker.cc#L325 ) can trigger different driving modes. And, Dreamview has the ["Start Auto" button](url) to trigger COMPLETE_AUTO_DRIVE. Hence, you can do the same to Dreamview by adding a button that triggers HMI's DISENGAGE action to change driving mode to COMPLETE_MANUAL.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
