### ISSUE TITLE
velodyne 16

### ISSUE THREAD

**Issue by TZVIh** [ApolloAuto/apollo#5835]
Hey,
I saw that I need velodyne 16.
Do I need it only for map creating or even for regular urban driving?

**Comment by XuanweiGou** [comment]
I think it might work for the whole urban driving because it might work for the whole map scan for some unseen stuff detection

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by YangHan101** [comment]
Up to 3.0, 16 line is only for map creation, since the HDL-64 doesn't have much of an angle looking up to cover the traffic lights.

Best regards,
Yang

**Comment by apollodevcommunity** [comment]
It is necessary to create a map   and it is also necessary in the perception stage. PNC needs to sense obstacles in real time and do obstacle avoidance processing. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=573
