### ISSUE TITLE
gdb debug issue: error while loading shared libraries

### ISSUE THREAD

**Issue by RamboRick** [ApolloAuto/apollo#5839]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:  14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I am using gdb to debug some specific module (prediction and perception module). The question is that when I run gdb bazel-bin/modules/perception/perception. And add a breakpoint using gdb. It will always show the "error while loading shared libraries: libactionlib.so: cannot open shared object file: No such file or directory". 

I am really confused about that. I have followed steps in https://github.com/ApolloAuto/apollo/issues/4803. But after I add set args --flagfile=/apollo/modules/perception/conf/perception_lowcost.conf --stderrthreshold=3 --use_navigation_mode. It is still the same problem. 

Thank you. 

## Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/28414290/46633971-61cb3e80-cb1d-11e8-8797-0dbe9386aab9.png)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
