### ISSUE TITLE
Control Module could not start 

### ISSUE THREAD

**Issue by hlchen1043** [ApolloAuto/apollo#5840]
Bug: Control Module could not start by running ./script/control.sh

**To Reproduce**
```
cd apollo
and run the following code:
./docker/scripts/dev_start.sh
./docker/scripts/dev_into.sh
./apollo.sh build
./apollo.sh build_gnss
./scripts/apollo_base.sh
./scripts/gps.sh
./scripts/localization.sh
./scripts/canbus.sh
./scripts/control.sh
```
**Expected behavior**
Previously(right before this morning) the control module is working fine as we expected. If control module was successfully launched(like localization module), then the output should be:
```
$./scripts/control.sh
Launched module control.
$./scripts/control.sh
Module control is already running - skipping.
./scripts/control.sh stop
Successfully stopped module control.

```
However, this morning we noticed that, after running the control script right after launching the script for the first time, and trying to stop the script right after it started, we get:
```
$ ./scripts/control.sh
Launched module control.
$ ./scripts/control.sh
Launched module control.
$ ./scripts/control.sh stop
Module control is not running - skipping.
```

**Screenshots**
![screenshot from 2018-10-08 19-46-20](https://user-images.githubusercontent.com/40038153/46639357-7a465380-cb33-11e8-923d-4c668af5582c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - branch: r2.0.0
 - Version:v2.0.0

**Comment by alexbuyval** [comment]
There are a lot of reasons why the control module is stopped.
First of all, check the /data/core directory. If the module is crashed you will find a dump file there.
Also try to enable the debug mode for the control module. You need to add the following line into control.conf file:
```
--v=4
```
After this you will be able to study a detailed log 'control.INFO' into /data/log directory.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
