### ISSUE TITLE
RTK Planner

### ISSUE THREAD

**Issue by kargarisaac** [ApolloAuto/apollo#5841]
Hi,
How can I know more about RTK planner and EM planner? Any document or paper or ...
Thanks in advance

**Comment by lesun90** [comment]
RTK planner is just a waypoint following. It will follow pre-recorded points.
EM planner: you can check the paper publication here https://arxiv.org/pdf/1807.08048.pdf

Good luck

**Comment by yifeijiang** [comment]
We will close the issue for now. If you have any additional question, please feel free to open a new issue.
