### ISSUE TITLE
Hardware setup ethernet issue

### ISSUE THREAD

**Issue by lopeztel** [ApolloAuto/apollo#5845]
Hi, we're requesting help to solve a problem with the initial setup

- **OS Platform and Distribution: Linux Ubuntu 14.04.5**:
We've installed ubuntu 14.04.5 on IPC Nuvo-7160GC (https://www.neousys-tech.com/Resource/Product_Document/Nuvo-7160GC/Nuvo-7160GC_8th-Gen_GTX1060_GPU-computing_datasheet.pdf) but we've had problems with the wired internet connection, the system doesn't recognize the cable as plugged in (we've alredy verified the cable and the fact that the wired connection works in other systems)

So far we tried the following :
1.installed ubuntu without internet access and then tried to manually install drivers (e1000e from https://www.intel.com/content/www/us/en/support/articles/000005480/network-and-i-o/ethernet-products.html or http://faq.aslab.com/support/kb/231.html), in this case the port was recognized but the system keeps trying to connect without success

2. installing ubuntu and then the apollo kernel (since it already includes the driver as mentioned here: https://github.com/ApolloAuto/apollo-kernel), in this case nothing happens

we  can't seem to find the problem and it is confusing since there is a very similar hardware reference in the installation guide material (https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_hardware_system_installation_guide.md#installing-the-software-for-the-ipc), Nuvo-5095GC seems to have the same ethernet ports... (more information here: https://www.neousys-tech.com/Resource/Product_Document/Nuvo-5095GC/Nuvo-5095GC_Datasheet.pdf )

Any pointers or help would be greatly appreciated

**Comment by YangHan101** [comment]
Could you check the IP of that ethernet port and the IP of the devices of the connected device? The ethernet settings are tricky to answer without all the information. Could you describe your system with more details?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
