### ISSUE TITLE
a small question about Box2d::HasOverlap function

### ISSUE THREAD

**Issue by shaenchenLi** [ApolloAuto/apollo#5847]
Hi, I've been studying r3.0.0 codes recently. I have a small question about Box2d::HasOverlap function in modules\common\math\box2d.cc. 

bool Box2d::HasOverlap(const LineSegment2d &line_segment) const {
  if (line_segment.length() <= kMathEpsilon) {
    return IsPointIn(line_segment.start());
  }
  if (std::fmax(line_segment.start().x(), line_segment.end().x()) < min_x() ||
      std::fmin(line_segment.start().x(), line_segment.end().x()) > max_x() ||
      std::fmax(line_segment.start().y(), line_segment.end().y()) < min_x() ||
      std::fmin(line_segment.start().y(), line_segment.end().y()) > max_x()) {
    return false;
  }
  return DistanceTo(line_segment) <= kMathEpsilon;
}

why is std::fmax(line_segment.start().y(), line_segment.end().y()) compared with min_x() but not min_y() ? And why std::fmin(line_segment.start().y(), line_segment.end().y()) compared with max_x() but not max_y() ?

**Comment by lianglia-apollo** [comment]
This bug will be fixed in the next release. Thanks.

**Comment by nhatuan84** [comment]
hi @shaenchenLi @lianglia-apollo 

I am reading the code and have a doubt about why Apollo treats the obstacle as line (LineSegment2d). I think it should be bounding box?

Thnks
