### ISSUE TITLE
How to train the MLP Deep Learning Model

### ISSUE THREAD

**Issue by BoChang11** [ApolloAuto/apollo#5854]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
  I have recently started working on Apollo project. I am following the link https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_train_prediction_mlp_model.md to train my own MLP model to predict the trajectory of Obstacles. There seems to be an error in the document and I am not able to get the expected output as given in the procedure. 

Steps Followed. 
I have completed **Install Dependencies** steps assuming that these need to be done outside the docker.  
I created a folder/directory inside /apollo/data/prediction.
Started docker using ```bash docker/scripts/dev_start.sh```
Entered docker using ```bash docker/scripts/dev_into.sh```
Compiled the apollo code ```bash apollo.sh build```
Downloaded the demo ROSbag by python docs/demo_guide/rosbag_helper.py demo_2.0.bag
Started prediction module : ```bash scripts/prediction.sh start_fe```
In new terminal inside docker started rosbag play demo_2.0.bag
After the rosbag play is completed and old terminal is terminated with Ctrl+C **I am not able to see **feature.0.bin** under the folder ```/apollo/data/prediction/```

Could you please check and let me know if I am missing any steps. 

### Supporting materials (screenshots, command lines, code/script snippets):

BR, Chang

**Comment by BoChang11** [comment]
Update 1:

Surprisingly it started working when I tried the same steps today. However there is an issue here and started getting new error. Kindly help me in fixing the issue. Details given below.
 
I was able to generate the ```feature.0.label.bin```. When I try to convert that into h5 file by running python generate_h5.py -f /apollo/data/prediction/feature.0.label.bin I am getting the below error.

```
Chong@in_dev_docker:/apollo/modules/tools/prediction/mlp_train$ python generate_h5.py -f /apollo/data/prediction/feature.0.label.bin
Traceback (most recent call last):
  File "generate_h5.py", line 25, in <module>
    import h5py
  File "/usr/local/lib/python2.7/dist-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
ImportError: /usr/local/lib/python2.7/dist-packages/h5py/h5t.so: undefined symbol: PyFPE_jbuf
Chong@in_dev_docker:/apollo/modules/tools/prediction/mlp_train$ 
Chong@in_dev_docker:/apollo/modules/tools/prediction/mlp_train$ 
```

Thank you very much. 
BR, Chong

**Comment by BoChang11** [comment]
@natashadsouza Issue is fixed now. I will be closing thi case.

**Comment by bssung** [comment]
@BoChang11  Can you share how do you solve the feature.0.label.bin problem?
