### ISSUE TITLE
Planning: pull over problem.

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#5857]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04 
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0
- **Simulator**: LG Simulator https://github.com/lgsvl/simulator

### Steps to reproduce the issue:
I'm working on Apollo planning module with customized simulator. I'm trying to make ego vehicle pulling over the curbside of the road shown in right side of it in picture 1. But this curbside is drivable by manual operation. Our HDmap doesn't have information of curbside shown in Picture 2. I checked that BuildPullOverStop() function (shown in picture 3) was called. The vehicle doesn't go to curbside and just stop on the reference line. 

1.Do I need to add map info on HDMap to make pull over working? I also tried to reduce some parameters like reducing `pull_over_plan_distance` 55.00 to 15.00, `plan_distance` from 55.0 to 15.0 and `operation_length` from 50.0 to 10.0 to make pull over working but failed.
 
2.What is the expected pull over behavior? Does the vehicle stop near to the curbside?
In the planning.INFO log message, I could see message like the follow.
[DEBUG] pull_over_status: in_pull_over: true

3.Whenver the vehicle pulls over, `inlane_dest_point` is set. Does this mean that the vehicle doesn't stop near to curbside but stop on the reference line?

Picture 1:
![image](https://user-images.githubusercontent.com/14055939/46773465-637a3b00-ccb2-11e8-879e-43135350d270.png)
Picture 2:
![image](https://user-images.githubusercontent.com/14055939/46773504-9f150500-ccb2-11e8-8b49-1334c81a71ce.png)
Picture 3:
![image](https://user-images.githubusercontent.com/14055939/46773653-45f9a100-ccb3-11e8-8e9e-d59e29c7b6a4.png)

Thank you so much.

**Comment by lesun90** [comment]
I think you should create a route for the curbside.
Right now, planner module in Apollo heavily depends on ref line, so consider the curbside as another lane.

Btw, your simulator look very nice, what tool are you using?

**Comment by mohamednasrallah** [comment]
^ Also curious. Which simulator project is that? Looks based on Unreal Engine. AirSim? Lidar representation looks nice.

**Comment by cyberphysicalrobotics** [comment]
This simulation is using Unity.
Project video: https://youtu.be/4gstgiW04Xw
Github repository: https://github.com/lgsvl/simulator

**Comment by cyberphysicalrobotics** [comment]
I checked that there is P symbol on the virtual obstacle for pull over like the following. The P virtual obstacle shows with the offset of lateral but the vehicle doesn't have lateral offset designated for virtual obstacle at the destination. The vehicle just stops the way it does at the normal virtual obstacle. 
![image](https://user-images.githubusercontent.com/14055939/47538894-7419dc00-d882-11e8-85b8-28fbb67be2d4.png)

In order to have pull over behavior, what else do I need to have on hdmap?
I made the lane_0 which is dummy lane for parking. But it doesn't work.
![image](https://user-images.githubusercontent.com/14055939/47539283-6d8c6400-d884-11e8-807c-5e32584f93e3.png)


lane[**lane_0**] length[63.222848] type[PARKING] turn[NO_TURN] speed_limit[0.000000] predecessor[] successor[] left_forward[**lane_32**] right_forward[] left_reverse[] right_reverse[], Left Boundary: [ virtual?:true, Type: [s: 0.000000->CURB, ]; Right Boundary: [ virtual?:true, Type: s: 0.000000->CURB, ] overlap[]; start point(x,y,heading):552746.415192,4182622.481049,0.789150 end point(x,y,heading):552790.952568,4182667.353653,0.789150 left_width:1.750000 right_width:1.750000

lane[**lane_32**] length[144.431911] type[CITY_DRIVING] turn[NO_TURN] speed_limit[20.000000] predecessor[lane_275, lane_279] successor[lane_285] left_forward[lane_31] right_forward[**lane_0**] left_reverse[] right_reverse[], Left Boundary: [ virtual?:true, Type: [s: 0.000000->CURB, ]; Right Boundary: [ virtual?:true, Type: s: 0.000000->CURB, ] overlap[]; start point(x,y,heading):552721.960068,4182602.329224,0.789983 end point(x,y,heading):552823.619495,4182704.925217,0.789983 left_width:1.750000 right_width:1.750000

My question:
Should the addtional reference line be derived from the original lane (lane_32) so there are two reference lines on lane_32?
![image](https://user-images.githubusercontent.com/14055939/47539200-ffe03800-d883-11e8-8e3c-2fd93dade7f2.png)

**Comment by lesun90** [comment]
Ref_lines do not work as you think. in each lane, there is a one ref_line. When change lane, the car will use the ref_line in the target lane.

Turn on PNC monitor (in tasks)
While running the planner, can you see any reference line in your parking lane? if not, planner did not create any ref_line in that lane, that why car does not move there.

**Comment by cyberphysicalrobotics** [comment]
After testing a lot of cases, I made conclusions like the followings:
(If you have some feedback on this, let me know that.)
1.Even if there is virtual obstacle wall is on the other lane, pull over doesn't activate the lane change. 
This is because routing destination on same lane doesn't make reference line on the other lane. 
Only if there is destination on the other lane, there are more than one reference line. 

In my test, I was setting -3.8 as buffer_buffer_to_boundary.

2.Pull over task is not a lot different with normal stop at the destination.
 
Figure 1: Virtual obstacle wall has lateral offset on the reference line on original lane.
![image](https://user-images.githubusercontent.com/14055939/47686164-f95d0380-db96-11e8-93e3-38c7a476b5f3.png)
Figure 2: As the ADC moves forward, the virtual obstacle wall changes onto the original lane, which makes no difference with normal stop at the destination.
![image](https://user-images.githubusercontent.com/14055939/47686170-ffeb7b00-db96-11e8-8216-a8a24e6a388a.png)

**Comment by lesun90** [comment]
check if the lanes have a correct neighbor. If they are not neighbor, the car could not make a lane change.

**Comment by cyberphysicalrobotics** [comment]
I set the lane_23 as SIDEWALK to make lane_22 right-most-lane. 

Lane change:
When the destination is on the other lane, there are two lanes where lane change is working (Figure4). When the destination is on the same lane, only one lane has route unlike Figure 4. Even if there is virtual obstacle wall is on the 1st lane, there is only one red line.

Pull over:
When planning modules starts, the virtual obstacle wall is on the 1st lane. As the ADC is moving, the virtual obstacle wall moves to the 2nd lane. It seems that the ADC is not pulling over to the 2nd lane.

Conclusion:
Pull over is not activating lane change and stops at the same lane started from the starting lane. 

Figure1. When I set destination at 1st lane, virtual obstacle wall is on the 2nd lane but lane change doesn't happen.
![image](https://user-images.githubusercontent.com/14055939/47756014-b154e400-dc5d-11e8-885d-98bb38df047f.png)

lane[**lane_23**] length[255.464990] type[**SIDEWALK**] turn[NO_TURN] speed_limit[20.000000] predecessor[lane_301, lane_306] successor[lane_228, lane_237] **left_forward[lane_22]** right_forward[] left_reverse[] right_reverse[], Left Boundary: [ virtual?:true, Type: [s: 0.000000->DOTTED_WHITE, ]; Right Boundary: [ virtual?:true, Type: s: 0.000000->DOTTED_WHITE, ] overlap[]; start point(x,y,heading):553030.875198,4182656.029800,-2.351326 end point(x,y,heading):552851.115683,4182474.511543,-2.351326 left_width:1.750000 right_width:1.750000

**lane[lane_22]** length[255.464985] type[**CITY_DRIVING**] turn[NO_TURN] speed_limit[20.000000] predecessor[lane_300] successor[lane_227, lane_238, lane_239] left_forward[] **right_forward[lane_23]** left_reverse[lane_21] right_reverse[], Left Boundary: [ virtual?:true, Type: [s: 0.000000->DOTTED_WHITE, ]; Right Boundary: [ virtual?:true, Type: s: 0.000000->DOTTED_WHITE, ] overlap[]; start point(x,y,heading):553033.661514,4182653.272507,-2.351326 end point(x,y,heading):552853.902006,4182471.754249,-2.351326 left_width:1.750000 right_width:1.750000

Figure2.Virtual obstacle wall is on the 1st lane 
![image](https://user-images.githubusercontent.com/14055939/47757471-ca609380-dc63-11e8-9487-19cd667af7d5.png)

Figure3.Virtual obstacle wall moves from 1st lane to 2nd lane.
![image](https://user-images.githubusercontent.com/14055939/47757493-e3694480-dc63-11e8-98be-95fee64a0acc.png)

Figure4. When I set destination on 2nd lane, lane change is working.
![image](https://user-images.githubusercontent.com/14055939/47757030-b4ea6a00-dc61-11e8-85a3-e83019d1102a.png)

**Comment by lesun90** [comment]
Ah, i think i know why, you are using the em planner, right? Standar apollo em planner could not make such a short lane change. You can tune the parameter of em planner to make that happen. Try to change the step_length_max and step_length_min to smaller value.
Let me know the result.

**Comment by cyberphysicalrobotics** [comment]
I'm using em planner. I tuned the parameter path_l_cost to 65 so the lane change could work in short distance. I tested with smaller step_length_min like 10.0, 2.0, 0.2, 0.02 (default: 20.0) The result was same with the previous. That's why pull over is not activating lane change task. Lane change doesn't work unless you set the destination on the other lane. Let me know what you think about the result. 

Figure 1-1.I set buffer_to_boundary to -5.0 to make virtual obstacle wall on the 2nd lane.
![image](https://user-images.githubusercontent.com/14055939/47819407-9f377c00-dd17-11e8-9541-7a2c857f47a5.png)
Figure 1-2.The ADC stops on the same lane after virtual obstacle wall moves to 1st lane.
![image](https://user-images.githubusercontent.com/14055939/47819442-bfffd180-dd17-11e8-8907-1ff9214e6472.png)

Figure 2. When I set the destination on 2nd lane, lane change works. There is blue reference line on 2nd lane.
![image](https://user-images.githubusercontent.com/14055939/47819515-fccbc880-dd17-11e8-81ac-e14f33a32cbc.png)

**Comment by lesun90** [comment]
**Lane change doesn't work unless you set the destination on the other lane**
yes, I think you are correct.

**Also I have one question. See the Figure 3. Default value of buffer_to_boundary is 0.5 to make virtual obstacle wall is biased to the left of the ADC, which is not intuitive. Because pulling over the car should be to the curb of the road, which is right of the ADC.**
I think right now apollo does not really care about exact stop location, in S-L coordinate, it only cares if the car can reach the stop point in S direction, but not in L direction.

Anyone from apollo please correct me if I am wrong here.

**Comment by marcusvinicius178** [comment]
Hi @cyberphysicalrobotics , @lesun90 I checked here you selected the EM planner.
How do you change the planners in Apollo?
Could you assist me quickly please here: https://github.com/ApolloAuto/apollo/issues/13763
