### ISSUE TITLE
planning算法测试和调试

### ISSUE THREAD

**Issue by freeyyc** [ApolloAuto/apollo#5858]
没有硬件设备的前提下，怎么测试和调试apollo现有的planning算法？

**Comment by freeyyc** [comment]
thinks for your reply.  can you tell me more detail?

The following is my step：

bash scripts/bootstrap.sh

bash scripts/filter_planning.sh -np demo_2.0.bag

in the Dreamview window, 
1 check the Planning and Routing checkbox in Module Controller panel.
2 in the Default Routing panel, press the “Route:Sunnyvale Loop Reverse” button

then, run the command
rosbag play demo_2.0.np.bag

but in the log file tells me "Routing is not ready"

![default](https://user-images.githubusercontent.com/8959497/47502267-eea22600-d899-11e8-9d76-5caf8d5f1e90.PNG)

**Comment by lianglia-apollo** [comment]
It seems that no prediction is provided (and no perception is provided). Planning will rely on prediction output.

**Comment by jmtao** [comment]
Hi @freeyyc , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
