### ISSUE TITLE
 ros/include/ros/ros.h: No such file or directory  #include "ros/include/ros/ros.h"                                  ^

### ISSUE THREAD

**Issue by MNaseerSubhani** [ApolloAuto/apollo#5860]
![capture](https://user-images.githubusercontent.com/39435854/46823160-e7adea80-cda6-11e8-96e4-3510bbfafb10.JPG)

I got this error when building on Ubuntu 14.04 .. I manually installed the ros package but still the error occurs.

**Comment by kk2491** [comment]
@MNaseerSubhani Are you building the code using docker ?

**Comment by MNaseerSubhani** [comment]
Yes...

**Comment by shifakhan4892** [comment]
I am facing the same issue.

**Comment by MNaseerSubhani** [comment]
I think there is some dependencies issue .. Apollo is working well on google VM on Ubuntu 14.04.

**Comment by MNaseerSubhani** [comment]
I got this warning when update  the host .
![screenshot from 2018-10-15 11 04 18](https://user-images.githubusercontent.com/39435854/46932924-528f4800-d06b-11e8-8771-407b33a1a191.png)

**Comment by storypku** [comment]
Stale issue closed.
