### ISSUE TITLE
利用相对地图和lattice planner进行规划

### ISSUE THREAD

**Issue by shaenchenLi** [ApolloAuto/apollo#5864]
您好，
code 版本： apollo v3.0
相关模块： relative map、planning module
问题：
1、之前看到过V3.0版本支持在相对地图下的lattice planning，请问应该怎么修改代码，https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/planning/proto/planning_config.proto 中只将planner_type改为NAVI，https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/planning/conf/planning_config_navi.pb.txt中的planner_type改为Lattice就可以了么？
2、代码中并没有看到navi planner调用em planner或者lattice planner中的代码，怎么看到lattice planner使用的是相对地图呢？
谢谢

**Comment by freeclouds** [comment]
我的理解
相对地图+lattice在planning的调用关系是：
/home/alan/apollo/modules/planning/navi_planning.cc
调用planner里面的规划算法，这里面的规划算法有Lattice、Em、NAVI
planner规划算法的位置：
/home/alan/apollo/modules/planning/planner
所以你只要在前面的文档里面设置了LATTICE，同时最好用dreamview里面navigation 模式下的界面进行操作，因为这个界面调用的脚本里面有设置--use_navigation_mode这个模式的参数，设置完
就会运行相对地图+Lattice模式，可以在navi_planning.cc和/home/alan/apollo/modules/planning/planner/lattice/lattice_planner.cc加log查看。

**Comment by shaenchenLi** [comment]
> 
> 
> 我的理解
> 相对地图+lattice在planning的调用关系是：
> /home/alan/apollo/modules/planning/navi_planning.cc
> 调用planner里面的规划算法，这里面的规划算法有Lattice、Em、NAVI
> planner规划算法的位置：
> /home/alan/apollo/modules/planning/planner
> 所以你只要在前面的文档里面设置了LATTICE，同时最好用dreamview里面navigation 模式下的界面进行操作，因为这个界面调用的脚本里面有设置--use_navigation_mode这个模式的参数，设置完
> 就会运行相对地图+Lattice模式，可以在navi_planning.cc和/home/alan/apollo/modules/planning/planner/lattice/lattice_planner.cc加log查看。

所以planning.cc最终调用的是lattice_planner.cc中的代码，只是用navigation mode生成的地图来作为规划过程中的地图么？

**Comment by HTL2018** [comment]
请问相关的问题解决了吗？我们现在也有同样的想法？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
