### ISSUE TITLE
Problem with bidirection road

### ISSUE THREAD

**Issue by LyubimovMaxim** [ApolloAuto/apollo#5865]
System information:
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0
Issue: 
 Hi, I'm creating map for Apollo and I want to create bidirection road.  Into documentation I found attributes direction, but I haven't any result when I change it. I can create route only in the direction of sequence of points set.  
It's simplest example of my base_map.txt 
[base_map.txt](https://github.com/ApolloAuto/apollo/files/2472055/base_map.txt)
 Thank you for help

**Comment by alexbuyval** [comment]
Which behavior are you expecting from Apollo when you change the direction attribute?
I mean how did you test roads with the different attribute?

**Comment by LyubimovMaxim** [comment]
I want to be able to create route in different directions. For test I try to do it with all values of attribute direction, but I haven't any changes in routing. I cannot create a route in a direction other than direction of point set

**Comment by Iqbalparvi** [comment]
@LyubimovMaxim  can you successfully create the route in different direction?
i need details how is will done

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
