### ISSUE TITLE
Build issue for Apollo 3.0 in Build and Release your Docker Container step

### ISSUE THREAD

**Issue by deepaktalwardt** [ApolloAuto/apollo#5866]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information
Dell XPS 15
Intel Core i7 7700 HQ
16 GB RAM
GTX 1050 4GB

- **OS Platform and Distribution : Linux Ubuntu 16.04 LTS on VMWare Player on Windows**:
- **Apollo installed from source**:
- **Apollo version trying to install: 3.0**:

### Steps to reproduce the issue:
I am trying to follow instructions to Build and Release as on this page: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md

And at the `bash apollo.sh build` command I receive the following error:
```
ERROR: /apollo/modules/calibration/lidar_ex_checker/BUILD:5:1: C++ compilation of rule '//modules/calibration/lidar_ex_checker:lidar_ex_checker_lib' failed (Exit 4).
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 132.634s, Critical Path: 119.60s
```
I have also tried the other two commands `bash apollo.sh build_cpu` and `bash apollo.sh build --local_resources 2048,1.0,1.0` and gotten the same error.

Can someone help me with this? I have not installed Apollo ever before. Do I need to install the previous versions first before I can go to 3.0

Also, I'm installing without hardware. Thank you
### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/7192506/46855731-5d22b680-cdb9-11e8-8f60-15989fe3ca16.png)

**Comment by zhxt** [comment]
Please try to give more memory to your VM(8G would be better for -j4, the more, the better) or reduce the job number to save memory usage.

**Comment by hahanigehaha233** [comment]
How to reduce the job number?

**Comment by hahanigehaha233** [comment]
@natashadsouza
