### ISSUE TITLE
Question about Radar-to-Camera Calibration

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5867]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: branch r3.0.0

### Question:
Hello Apollo team, I have a question about **Radar-to-Camera Calibration**.
I'm trying to calibrate Radar and Camera sensors with Apollo's calibration tool.

In document [Apollo 2.0 Sensor Calibration Guide](https://github.com/ApolloAuto/apollo/blob/a32e52d3b2f207c2f7c7fe1980c3257f4942df44/docs/quickstart/apollo_2_0_sensor_calibration_guide.md) , there're required topics for Radar-to-Camera Calibration.

1. /apollo/sensor/camera/traffic/image_short
2. /apollo/sensor/gnss/odometry
3. /apollo/sensor/gnss/ins_stat

I wonder why Topic about odometry necessary, and can you please explain more detail about it ?

And also, are there any documents or websites for the reference?
I can't analyze Apollo's calibration tools because they're provided in execution files (.exe).

Thanks !

**Comment by sinopec** [comment]
> Our team provided all the topics that required. However, there is nothing coming out, no log and results. The scripts were keep running .... @natashadsouza

The Same issue for me . Just Show
"Start to calibrate Radar-Camera extrinsics"

**Comment by JonathanJones92** [comment]
Yes, there is nothing coming out. No log and results. @natashadsouza

**Comment by sinopec** [comment]
No log and results. Need help

**Comment by natashadsouza** [comment]
@JonathanJones92 @sinopec the most likely issue is that the configuration of the system differs from that when tools were built. Besides that, erroneous timestamps of sensors also cause similar issue. For example, if stamps of images are not UTC format, the data collection process will fail to find the corresponding car motion status, so the tool will not go to the next step. The way to identify this problem is checking the stamps. Let me know if you have additional questions.

**Comment by JonathanJones92** [comment]
> @JonathanJones92 @sinopec the most likely issue is that the configuration of the system differs from that when tools were built. Besides that, erroneous timestamps of sensors also cause similar issue. For example, if stamps of images are not UTC format, the data collection process will fail to find the corresponding car motion status, so the tool will not go to the next step. The way to identify this problem is checking the stamps. Let me know if you have additional questions.

Thank you, I'll try to check then update the status :)

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thank you for your interest in Apollo!
