### ISSUE TITLE
Velodyne 32

### ISSUE THREAD

**Issue by TZVIh** [ApolloAuto/apollo#5868]
Can I replace the velodyne 64 with the velodyne 32?
How will be the results of the mapping and localization?
Thanks!

**Comment by YangHan101** [comment]
I don't have a quantitative answer to your question. If you are switching to 32 line, I recommend collect the data again and label them, train the model and recollect the map to achieve the best performance.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. If you have additional questions feel free to reopen this issue. Thank you!

**Comment by lucasnmatias** [comment]
> I don't have a quantitative answer to your question. If you are switching to 32 line, I recommend collect the data again and label them, train the model and recollect the map to achieve the best performance.

There is any documentation about the training pipeline? How could I retrain the model?
