### ISSUE TITLE
base_map.txt file for sunnyvale_big_loop and sunnyvale_loop

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#5870]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.00

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

- base_map.txt and base_map.bin for sunnyvale big loop and sunny vale is not available inside the modules/map/data/<map_name> directory. 

- Could you please let me know if these files are openly available ? 

### Supporting materials (screenshots, command lines, code/script snippets):

Thank you,
KK

**Comment by alexbuyval** [comment]
You need to open this directory inside the docker.

**Comment by kk2491** [comment]
@alexbuyval Thanks for the solution. I am able to find the base_map.txt file.

**Comment by kk2491** [comment]
@alexbuyval Have you tried to run ```mapshow``` tool on sunnyvale big loop and sunnyvale loop maps ?

**Comment by kk2491** [comment]
Yea.. I got it too. I was pointing to different folder. :D Thank you.

**Comment by kk2491** [comment]
@natashadsouza .. Yes. I was able to get the ```mapshow``` working. However I would like to know if the ```base_map.txt``` of ```base_map.xml``` file of sunnyvale_big_loop is openly available. 

Thank you,
KK

**Comment by natashadsouza** [comment]
@kk2491 sorry for the delay in responding. We will not be opening the .txt file unfortunately. Let me know if you have any other questions. Closing this thread currently as it appears to be resolved.
