### ISSUE TITLE
For Apollo 3.1,  the module/tool/perception has been removed compared with previous version? 

### ISSUE THREAD

**Issue by fanghaos2014** [ApolloAuto/apollo#5871]
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:14.04
- **Apollo installed from (source or binary)**:Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.0 above

I checked the new version and want to find the script files in module/tools/perception. But when I updated my version, I can not find this file and all it subfiles in Apollo. Then I search all its subfiles, I can not find anyone. Because I want to add my own obstacle in the dreamview, and I saw most of them were using the scripts in module/tools/perception to add their own obstacle. But right now, I can not find it. I want to double check this module has been removed or not. If it has been removed, is there any other scripts have the same function like that module? Please give me some hints. Thank you.
The issue what I referenced 
https://github.com/ApolloAuto/apollo/issues/4317

**Comment by natashadsouza** [comment]
@fanghaos2014 Apollo is constantly being modified based on our roadmap. If you would like to reference old files, please refer to the version stable branches of Apollo. You could find the files you are looking for [here](https://github.com/ApolloAuto/apollo/tree/r3.0.0/modules/tools/perception). Let me know if you have any questions.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
