### ISSUE TITLE
 gnss driver module for parsing

### ISSUE THREAD

**Issue by apycii** [ApolloAuto/apollo#5872]
Hi, Apollo team.

Apollo has two ways to receive GPS data. One is received via CAN, and the other is received by apollo/modules/drivers/[gnss](https://github.com/ApolloAuto/apollo/tree/master/modules/drivers/gnss).
It seems to be enough to get through CAN like a radar, but why use DRIVER module for parsing?

**Comment by ycool** [comment]
Driver module can isolate the hardware differences and makes it easier for other modules to use GPS data.
