### ISSUE TITLE
Apollo.control模块运行后，无有效数据输出

### ISSUE THREAD

**Issue by HNwangjiaxing** [ApolloAuto/apollo#5873]
**System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04):
- **Apollo installed from (source ):
- **Apollo version ( 2.5):

我们目前在做基于apollo平台的低成本的无人车驾驶，主要是结合生成的离线参考线、摄像头、毫米波雷达及GPS惯导,实现车辆的自动驾驶。但是在控制模块调试时，出现下面的问题：

首先已经给出控制模块的输入：底盘（chassis)、定位(localization)、行驶轨迹(planning)等信息后，（下图是监控模块显示目前运行的topics ）。
![qq 20181016095019](https://user-images.githubusercontent.com/41990400/46987963-00acf780-d129-11e8-8b22-60346488f4c3.jpg)

然后在终端上运行控制模块：./scripts/navigation_control.sh，虽然在终端上显示”Launched module control. ”,但没有输出相应的控制信息。
而且查看control.INFO打印的信息，显示如下：
![qq 20181016095010](https://user-images.githubusercontent.com/41990400/46988042-5aadbd00-d129-11e8-83c4-a8749209abea.jpg)

我现在不知道问题出在哪里，希望大家可以指点在下一下，谢谢！

**Comment by HNwangjiaxing** [comment]
> 从输入上看，control订阅的话题：定位/规划/底盘都是有的，输入感觉没什么问题。猜想是用来init的配置文件有问题，你需要查看下data/log下control.FATAL 或者control.ERROR等log文件，看具体报错是什么

您好，谢谢您的答复。我查看了log下的日志，没有发现control.FATAL 或者control.ERROR文件，关于control的文件，只有control.out 、 control INFO、和control flags。目前出错原因还未找到。

**Comment by HNwangjiaxing** [comment]
> 确认下输入control的消息是否都有值，如果正常都有值。
> 然后开启debug模式，代码里应该有不少debug调试信息，看下debug日志，仅供参考，另问下监控模块显示 的信息，怎么看的
您好，您说的监控模块，我是直接用scripts下的关于监控模块的脚本打开的。

**Comment by HNwangjiaxing** [comment]
> 确认下输入control的消息是否都有值，如果正常都有值。
> 然后开启debug模式，代码里应该有不少debug调试信息，看下debug日志，仅供参考，另问下监控模块显示 的信息，怎么看的

您好，想请问一下您，你说的debug模式，如何开启呢？我找了一下，是不是在control.conf 文件中加入--v=4呢，然后开启control模块？但查看日志，还是无任何发现，恳请有时间进行解答，谢谢！

**Comment by judyqiu1996** [comment]
想请问下每个module的period, max, min这些数据你是怎么得到的？（第一张图是通过run哪些command得到）

**Comment by HNwangjiaxing** [comment]
您好，我已经收到您的来信，我会尽快给您回复，谢谢！
