### ISSUE TITLE
Velodyne vlp 32c driver

### ISSUE THREAD

**Issue by TZVIh** [ApolloAuto/apollo#5874]
Hey,
Does Apollo velodyne driver works with vlp 32c?
I saw HDL32e but maybe I missed it..

Thanks!

**Comment by YangHan101** [comment]
vlp-32c has the same data structure with hdl-32e. But the angular spacing between two "lines" are different. So you can use it with different calibration files.

**Comment by mickeyouyou** [comment]
we will adapt the vlp-32c in branch v3.1-dev.

**Comment by mickeyouyou** [comment]
please check the branch master and v3.1dev to use driver. thank you.
