### ISSUE TITLE
How can I add new layers into caffe?

### ISSUE THREAD

**Issue by pooluut** [ApolloAuto/apollo#5876]
I want to add my own layer into caffe.
Any docs for this?

**Comment by techoe** [comment]
Since we provide the source code of modified caffe now, you can easily add new layers now.

**Comment by swdev1202** [comment]
@techoe when you say you provide the source code of modified caffe, are you referring to this repo (https://github.com/ApolloAuto/caffe)?

**Comment by techoe** [comment]
Yes

**Comment by hawl666** [comment]
@techoe the source code link is not available

**Comment by icolwell-as** [comment]
Does anyone know what happened to the Apollo caffe source code? Does anyone have a fork by chance?
It would be useful to those of us who are still running older versions of Apollo with caffe.
Thanks.

**Comment by daohu527** [comment]
It is strongly recommended that you switch to the new version, we have added some new models and will open the training code

**Comment by mikeklm** [comment]
I'd also be interested in finding this source code. For certain reasons, I need to convert one of the Caffe models used by the perception module to a different format (ONNX). I keep getting unsupported operator errors.

I don't have the option of switching to a later version as there is already a physical vehicle that has been built. Its hardware/sensors have already been integrated with  the Apollo 5.5 stack.
