### ISSUE TITLE
Planning/Control issue: right turn is not working right

### ISSUE THREAD

**Issue by luqiang21** [ApolloAuto/apollo#5879]
### System information

- **OS Platform and Distribution, Linux Ubuntu 16.04**:
- **Apollo installed from source **:
- **Apollo version 3.0**:

When the vehicle is turning right, the planned trajectory looks fine which is not overlapping with the curb as shown below:
![screenshot from 2018-10-16 17-37-23](https://user-images.githubusercontent.com/9755042/47055095-a16fd700-d16a-11e8-9f08-bf9ab4edb4b3.png)

However, when we let the vehicle turn from the rightmost lane, almost every time the vehicle will drive on the curb. 
![screenshot from 2018-10-16 17-37-01](https://user-images.githubusercontent.com/9755042/47055142-e8f66300-d16a-11e8-8c15-0d8c7d4d0c59.png)

Through the turning, seems that the front wheel is following the planned trajectory. Why is the center of the vehicle not following the trajectory? I am not sure the problem is from planning or control or the parameter of the car?

Thank you so much for your help.

**Comment by lesun90** [comment]
I faced the same issued when playing with the simulator. I think it may come from several sources.
- Mapping from the simulator to Apollo map has an offset.
- Perception did not detect the pole.
- Delay between Apollo and simulator which may cause the controller delay -> sim car could not follow trajectory.
These are what I could think the problem come from. Need further investigation to verify.

**Comment by luqiang21** [comment]
@lesun90 Thank you so much for your answer. I was thinking about how Apollo will react in reality if there is such a corner to turn right. 

I agree that the delay might be the reason since we observed that the car's longitudinal motion has a delay and you are right the pole may not be detected by Apollo. I am not very clear about mapping, so I need to read more about HDmap.

**Comment by lianglia-apollo** [comment]
Please try Apollo 3.5. I remember one of the fix is related to this issue. Thanks.

**Comment by luqiang21** [comment]
@lianglia-apollo Great, thank you for reminding me.

**Comment by jmtao** [comment]
Hi @luqiang21 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
