### ISSUE TITLE
Why need to use Lidar reliability factor when perform class fusion in standard mode?

### ISSUE THREAD

**Issue by jamchen1025** [ApolloAuto/apollo#5883]
Hi Apollo Team,

As the title, in the perception fusion subnode [PerformClassFussion function](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/obstacle/fusion/probabilistic_fusion/pbf_track.cc#L605), 

1. Why need to multiply lidar reliability factor(0.5) in "default standard mode"?
    (only has lidar data, because radar data will be ignored)
2. If I don't multiply lidar reliability factor in standard mode, does it means that I trust the new lidar data more?
3. Why the class type information in radar subnode can't be used for class fusion? in the GetReliabilityFactor function, it will return 0 when the input data is radar, which means that don't need to fuse, right?

Any comments will be appreciated~

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
