### ISSUE TITLE
Tracking algorithms

### ISSUE THREAD

**Issue by funkydvd** [ApolloAuto/apollo#5888]
Hi, I need to know what are the tracking algorithms used in apollo (some papers would be excellent, if you can). From what I saw, there is a cascaded tracker that use 3 filters, but I could guess only one of them, I suppose kcf means Kernelized Correlation Filters, the rest of them I couldn't guess it (cs2d and dlf). I also saw that in the lidar section it is used a Hungarian Matcher with Kalman Filter, am I right?
Thank you and sorry if it is written in the documentation but I couldn't find it.
David

**Comment by techoe** [comment]
Apollo uses Hungarian algorithm for the multiple hypothesis data association. We didn't publish any paper but code on this.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
