### ISSUE TITLE
Apollo open data platform and perception module

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5889]
Hi Apollo：
     Apollo的数据平台开放了很多的数据，比如激光雷达的点云数据，红绿灯检测的数据，这些数据都是Apollo进行预处理过后直接可以送给perception模块使用的吧？对于提供的红绿灯检测数据，这些数据可以在训练平台上使用，可不可以直接在Apollo里使用呢？如果可以，怎么把这些数据用在Apollo里面呢？rostopic广播给percption模块？您讲的使用这些数据训练算法，这些算法指的是开发者自己写的算法制作成的caffe模型？如果是，把这些模型替换掉Apollo里面的红绿灯识别模型是不是就达到使用这些数据的目的呢？谢谢您！

**Comment by techoe** [comment]
@breakisx, Thank you for using Apollo! Could you ask again in English for the community?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
