### ISSUE TITLE
Where to download the perception yolo3 detector model?

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#5910]
Where to download the perception model (trained weigths), after digging the docs there is nowhere to find it.

**Comment by alexbuyval** [comment]
You can find it into './modules/perception/model/' directory. However, please note, that some models will be able only inside the docker.

For instance,
```
alex@in_dev_docker:/apollo$ ls ./modules/perception/model/yolo_camera_detector/yolo3d_1128/
CalibrationTable  anchors.txt  deploy.md  deploy.md.metadata  deploy.pt  feature.pt  types.txt
```

**Comment by techoe** [comment]
Thank you @alexbuyval  for answering the question. This issue is closed since it has been answered.
