### ISSUE TITLE
Question about HW Camera Installation

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5914]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Question
Hi Apollo team, now I'm trying to run Apollo platform with my vehicle.
What I'm going to do now is Lowcost Perception with using 1 Camera and Radar.

I bought a Leopard Camera which is same with Apollo reference one. But because lens of the Camera is exposed to the outside, it seems that there're some problems like unnecessary light reflection. And I thought I need a housing or case, or something like that.

Do you have any guideline for installing camera HW or some installed pictures ?
(more detailed than 'quick start guide - hw installation')

Thanks!

**Comment by natashadsouza** [comment]
Please refer to [camera specs guide](https://github.com/ApolloAuto/apollo/tree/master/docs/specs/Camera) for more information. Let me know if you have additional questions.

**Comment by CCodie** [comment]
Hi, @natashadsouza . Thank you for the reply :)
Actually I wonder about how the camera attached at a windshield.
Apollo team just locate that camera with case at the windshield or with any other customized case ?

**Comment by natashadsouza** [comment]
@CCodie The cameras are placed on a customized mount outside the car on either side of the LiDAR.

**Comment by YangHan101** [comment]
@CCodie You can also 3d print a camera mount and secure it onto the windshield.

**Comment by natashadsouza** [comment]
@CCodie apologies for the delay in responding. If you have a specific design in mind, we would be happy to evaluate it for you.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
