### ISSUE TITLE
Planning failed with one static obstacle ahead the vehicle under SimControl mode 

### ISSUE THREAD

**Issue by lygincn** [ApolloAuto/apollo#5915]
### System information

- **OS Platform and Distribution**  Linux Ubuntu 14.04:
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  latest master branch

### Steps to reproduce the issue:
- generated one static obstacle in the middle of the lane with the script "replay_perception.py"(the purple one in pictures)
- start simcontrol --> start planning, routing and prediction modules --> set the start and end point in the map --> send routing request 
- planning started, when approaching the obstacle, the vehicle made a stop decision for a while, like in this picture:
![screenshot from 2018-10-24 16_03_39](https://user-images.githubusercontent.com/40354939/47417034-a60b3f80-d7a9-11e8-8509-4c534cc820ba.png)
 then after about 10s the vehicle made a path planned like in this picture:
![screenshot from 2018-10-24 15_53_50](https://user-images.githubusercontent.com/40354939/47417142-e965ae00-d7a9-11e8-9c6b-5f62a7c2841e.png)
but it didn't followed the path exactly, which is to change to another lane with a big turn, but decided to turn with a smaller angle like this:
![screenshot from 2018-10-24 16_05_01](https://user-images.githubusercontent.com/40354939/47417286-3b0e3880-d7aa-11e8-9517-39c098826b15.png)
and by turning the vehicle failed to drive pass the obstacle and stopped near it, forever... 
![screenshot from 2018-10-24 15_53_59](https://user-images.githubusercontent.com/40354939/47417364-6a24aa00-d7aa-11e8-8a8e-c934641cdd04.png)
![screenshot from 2018-10-24 15_52_00](https://user-images.githubusercontent.com/40354939/47417374-6e50c780-d7aa-11e8-9313-df6d416a36d4.png)

Do you guys have any idea why the vehicle acts like this? The planner used is EM-planner. 
I've noticed that in this file  [apollo/modules/planning/conf/lane_follow_scenario_config.pb.txt]([url])  we can change the parameters for EM-planner, but I'm not quite sure which parameter or constraint I should change for this case. 
Any idea or suggestion is appreciated! Thanks a lot :)

**Comment by lianglia-apollo** [comment]
Thanks. We also noticed this. It will get improved in the next release.

**Comment by lygincn** [comment]
@lianglia-apollo thank you for your reply. Looking forward to your new release. But before it can you please maybe give me some hints about where the reason may come from? I´d very like to give it some try. :)

**Comment by lygincn** [comment]
@lesun90 thank you very much for reply, really appreciate it. I'll try following your advice :)

**Comment by lygincn** [comment]
by changing the parameter Step_length_min and step_length_max to 11, can the vehicle successfully pass the obstacle. according to my experiments 11  is the  limit value in this case. Thank you all.
