### ISSUE TITLE
PROJECT_NUMBER         = 2.0 in apollo.doxygen

### ISSUE THREAD

**Issue by wzhang1** [ApolloAuto/apollo#5918]
**Describe the bug**
Sorry if I understand the version number wrong, I just started to read the doc of apollo and
the branch I check out is v3.1_dev, in  apollo.doxygen
line 41

PROJECT_NUMBER         = 2.0 

If I understand the name correctly, should it be like this?

PROJECT_NUMBER         = 3.1

**To Reproduce**
doxygen apollo.doxygen

**Expected behavior**
In the main page of the generated document, you will see

Apollo  2.0
Open source self driving car software

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wzhang1** [comment]
Desktop (please complete the following information):
not applied
Smartphone (please complete the following information):

not applied

**Comment by mickeyouyou** [comment]
you can change it and generate documents on local.
