### ISSUE TITLE
dreamview has run,but chrome open the localhost:8888 that don't access

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5923]
### System information

- **OS Platform and Distribution Linux Ubuntu 14.04
- **Apollo installed from source
- **Apollo version 3.0

bash scripts/bootstrap.sh
it display unxi:///tmp/supervisord.sock refused connection.
so I  modify /etc/supervisord.conf and modules/tools/supervisord/dev.conf,modify it to :
;[unxi_http_server]
;file=/tmp/supervisor.sock

[inet_http_server]
port=127.0.0.1:9001

[supervisorctl]
;serverurl=unix:///tmp/supervisor.sock
serverurl=http://127.0.0.1:9001

then kill all task in docker, and bash scripts/bootstrap.sh , it display:
Started supervisord with dev conf 
Start roscore...
voice_detector: started
dreamview:started 
Dreamview is running at http://localhost:8888

and I run ps -e, I can see the dreamview task is running ,but input http://localhost:8888 in chrome, it display that don't access.
this is why ? 
Thank you!

**Comment by natashadsouza** [comment]
@breakisx go to the [following document](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md) and check the last question. If you still unable to resolve it, please send us a screenshot of your browser window. Also please check that you have a stable connection.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. 
@breakisx feel free to reopen if you have additional questions. Thanks!
