### ISSUE TITLE
How can we verify the radar sensor ?

### ISSUE THREAD

**Issue by CCodie** [ApolloAuto/apollo#5927]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux 14.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Question
Hi Apollo Team, I have a question about the Radar sensor.
Now I'm trying to run Lowcost-Perception with my vehicle.
I'm using Leopard Camera which is same with Apollo Reference HW but the vehicle is not same so I modified CAN codes about Conti_Radar.

I checked that my Apollo Platform subscribes Radar Topic, but I wonder that how can I verify that radar topic is reliable ?

Q. How can I verify the radar sensor ? I can receive the radar topic but I wonder that is reliable.
Q. I want to know how Apollo team verified the radar sensor topic. Is there any tool ?

Thank you :)

**Comment by techoe** [comment]
For Q1 and Q2: You can test your radar by moving around with known distance.
