### ISSUE TITLE
How obstacle speed is computed in navigation mode?

### ISSUE THREAD

**Issue by luqiang21** [ApolloAuto/apollo#5936]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source )**:
- **Apollo version (3.0)**:

### Steps to reproduce the issue:
- **We are using [LG autonomous driving simulator](https://github.com/lgsvl/simulator) to test Apollo navigation mode while only using camera sensor, IMU and GPS**
- **We can see that the speed for the obstacle is obtained even with only camera sensor while the value was not stable and accurate for a stopped front car**

### Questions
- What kind of algorithm are we using to get the speed of detected obstacle with only image data?
- I can see that on line 466 of function `FusionSubnode::GeneratePbMsg` in `perception/obstacle/onboard/fusion_subnode.cc` file, the obstacle's speed is obtained by adding relative speed and ego car speed, but I am having a hard time to find where the relative speed of the obstacle is computed. Can you kindly let me know the corresponding file that I can look into?

Thank you so much for your great work!

**Comment by GPrathap** [comment]
> I think I found the place where the obstacle's speed is obtained only with camera images through debugging. The `object`'s speed of `objects` will be given after filter is applied. The corresponding file is located at `perception/obstacle/camera/filter/object_camera_filter.cc`. It is using three Kalman Filter for $(x, \dot(x))$, $(y, \dot(y))$ and $(\theta, \dot(\theta))$. Every time `velocity.x()` and `velocity.y()` get updated from the filters and `velocity.z()` is set as `0.0`.
> 
> It seems like the `object_camera_extended_kalman_filter.cc` is using 1 extended kalman to predict and update state $(x, y, \theta, v)$. Please correct me if I am wrong. Thanks.

Yeap you are right :)
