### ISSUE TITLE
Viewing Velodyne PoinCloud data in rviz

### ISSUE THREAD

**Issue by RobotBramhana** [ApolloAuto/apollo#5945]
Hi,

I am publishing a pointcloud of type ```PointCloud<apollo::drivers::lidar_velodyne::PointXYZ>``` 

In order to select the frame, neither the /tf not /tf_static is available outside the docker without which the data is not displayed in rviz.

How to view pointcloud data which is being published inside docker, by running rviz outisde docker? Any other solution will also be appreciated.

**Comment by melvinyesudas** [comment]
@SS6141  You got the solution? I am facing the same issue!

**Comment by techoe** [comment]
Thank you for using Apollo! You can visualize point cloud data using Dreamview.

**Comment by TheGreatGalaxy** [comment]
> Thank you for using Apollo! You can visualize point cloud data using Dreamview.
@techoe I want to using dreamview to display my own point cloud. But i don't know how to do that? Can you give me some suggestion? Thanks a lot!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
