### ISSUE TITLE
Want to include jsk_recognition toolkit in apollo source codes?

### ISSUE THREAD

**Issue by chowkamlee81** [ApolloAuto/apollo#5952]
Iam using jsk_recognition toolkit to subscribe boundingboxarray into cpp code. I don't know how to include jsk_recognition toolkit in apollo. Kindly suggest technique. Do the needful

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
