### ISSUE TITLE
Open source plan for the MSF localization library

### ISSUE THREAD

**Issue by junjieshen** [ApolloAuto/apollo#5969]
Hello,
I am currently studying the MSF algorithm and trying to improve it with additional sensor sources. The MSF algorithm was published in the [paper](https://arxiv.org/abs/1711.05805). But it seems the fusion of errors from GNSS and LiDAR is missing in the paper. So I want to take a look at the source code but unfortunately the core algorithm is released as a shared library for now (at `/usr/local/apollo/local_integ` in the docker). I am just curious why Apollo choose to close source this part, and if possible please shed some light on when will it be open-sourced.

Thanks!
Junjie

### System information

- Linux Ubuntu 14.04
- Apollo installed from source or binary)
- Apollo version 2.5

**Comment by frontw** [comment]
Any update?

**Comment by jimmyw404** [comment]
@guoweiwan  @natashadsouza Hello. I am also curious about this question. I am researching ADS framework options and a closed source system for a critical module like localization is very troublesome to me. 

Is there a plan to open source the MSF localization component?

**Comment by daohu527** [comment]
Thanks for your advice. There are currently no open source plans, we will evaluate whether to add this feature and feedback soon.
