### ISSUE TITLE
orange color line on routing editing.

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#5970]
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04 with LG Automotive Simulator 
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

I'm using apollo with LG simulator. Our team makes the map in the simulator. On the Routing Editing tab of the Dreamview, there is orange line along the lane. I thought that it was because of CURB annotation of boundary type. But without CURB annotation, orange line appeared. Could you let me know what orange line means in the following screenshot?

![image](https://user-images.githubusercontent.com/14055939/47753163-d8a6b380-dc53-11e8-85bc-9e1a9950fb54.png)

**Comment by kk2491** [comment]
I think those orange lines represents **road**. Can you go to **layer menu** and try toggling the **road** button in **Map** option. 

Thank you,
KK

**Comment by cyberphysicalrobotics** [comment]
The following is when I turned Road on in Map in of Layer Menu. It showed more orange lines. That's why I'm not sure if it's road or not.

![image](https://user-images.githubusercontent.com/14055939/47820766-baa48600-dd1b-11e8-8118-223886a53573.png)

**Comment by vlin17** [comment]
Have you figured out what those lines are?  This is a puzzling question as the only coral color used in the map is [CURB](https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/frontend/src/renderer/map.js#L106).

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
