### ISSUE TITLE
how is the asynchronous sensor fusion implemented?

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#5972]
in the doc:https://github.com/ApolloAuto/apollo/blob/v3.1_dev/docs/specs/3d_obstacle_perception.md
we can see the LiDAR based 3D Obstacle Perception algorithm.

in the doc: https://github.com/ApolloAuto/apollo/blob/v3.1_dev/docs/specs/perception_apollo_3.0.md
we can see that Apollo implemented a "Asynchronous sensor fusion"

> Asynchronous sensor fusion: unlike the previous version, Perception in Apollo 3.0 is capable of consolidating all the information and data points by asynchronously fusing LiDAR, Radar and Camera data. Such conditions allow for more comprehensive data capture and reflect more practical sensor environments.

but in the flow chart of Apollo 3.0 Perception module, I can't see the LiDAR data( only camera and radar data). Also, I can't figure it out that how is the "Asynchronous sensor fusion" implemented.

**Comment by westeast** [comment]
并非专业做感知，说下我的理解哈：
这里其实对lidar,radar,camera都做了融合，融合思路 是这样的，三个传感器的输出先都统一转成SensorObject这样的统一结构，然后每个传感器的都有所检测出的障碍物的时间戳，这个时间戳做过同步，可以理解是用asu硬件这层就同步了，同时每个障碍物还有坐标位置，速度，加速度，等属性数据，把所有传感器的输出集中在一起，通过时间戳可以找到各传感器的最相近帧，然后用一些track算法或者 kalman滤波的算法不各个障碍物做一些判断，判断哪些障碍物可能是同一个障碍物，对于可能性大的就当成同一个障碍物，这样处理一边就算是最终的融合结果，详细可以看https://github.com/ApolloAuto/apollo/blob/master/modules/perception/obstacle/fusion/probabilistic_fusion/probabilistic_fusion.cc  这里Fuse()函数。
如下：集中三个传感器的数据：
```
// 1. collect sensor objects data
    for (size_t i = 0; i < multi_sensor_objects.size(); ++i) {
      auto sensor_type = multi_sensor_objects[i].sensor_type;
      ADEBUG << "add sensor measurement: " << GetSensorType(sensor_type)
             << ", obj_cnt : " << multi_sensor_objects[i].objects.size() << ", "
             << std::fixed << std::setprecision(12)
             << multi_sensor_objects[i].timestamp;
      if (is_lidar(sensor_type) && !config_.use_lidar()) {
        continue;
      }
      if (is_radar(sensor_type) && !config_.use_radar()) {
        continue;
      }
      if (is_camera(sensor_type) && !use_camera_) {
        continue;
      }

      AINFO << "GetSensorType(multi_sensor_objects[i].sensor_type)"
            << GetSensorType(multi_sensor_objects[i].sensor_type);

      AINFO << "publish_sensor_id_" << publish_sensor_id_;

      if (GetSensorType(multi_sensor_objects[i].sensor_type) ==
          publish_sensor_id_) {
        need_to_fusion = true;
        fusion_time = multi_sensor_objects[i].timestamp;
        started_ = true;
        sensor_manager_->AddSensorMeasurements(multi_sensor_objects[i]);
      } else if (started_) {
        sensor_manager_->AddSensorMeasurements(multi_sensor_objects[i]);
      }
    }

    options->fused = need_to_fusion;
    if (!need_to_fusion) {
      sensor_data_rw_mutex_.unlock();
      return true;
    }
```

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
