### ISSUE TITLE
localhost:8888

### ISSUE THREAD

**Issue by riskeverything** [ApolloAuto/apollo#5974]
When I use "bash scripts/bootstrap.sh" to star the HMI,I get the informatation like this:

Started supervisord with dev conf
Start roscore...
voice_detector: started
Dreamview is running at http://localhost:8888

However, I can't open the http://localhost:8888, the chrome says:
This site can’t be reached
localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall

I have no idea to control the question.

**Comment by natashadsouza** [comment]
@riskeverything you could check these 2 documents: [Dreamview FAQs](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md) and 
[debugging the dreamview start problem](https://github.com/ApolloAuto/apollo2/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md)

**Comment by luannan** [comment]
Please check FMA is supported by your CPU. If not, there should be the problem.

Please refer my essay for more info.
https://zhuanlan.zhihu.com/p/51160743
