### ISSUE TITLE
Definition of has_out in file /apollo/modules/perception/obstacle/lidar/object_builder/min_box/min_box.cc

### ISSUE THREAD

**Issue by willsiriusAD** [ApolloAuto/apollo#5975]
**Definition of the boolean has_out in function ReconstructPolygon**

My understanding of the variable *has_out* is that it shows whether the polygon is concave or not. If there is an outlier, this variable will be true. In other words, the polygon points are concave. 

There are three if clause that might assign the variable as true and I have question about the third one.

If the point with index j is the max_point and the point i is not min, then there are many scenarios that many scenarios that the variable is assigned true when the polygon is convex.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
