### ISSUE TITLE
percption  module(about data_generator for lidar)

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5976]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)
- **Apollo installed from (source)
- **Apollo version (3.0)

Hello Apollo：
    what is /apollo/module/perception/tool/data_generator/data/sensor_data_0? What does it do? What does it have to do with sample_sensor_output_data in the same dir?

**Comment by techoe** [comment]
Close for the duplicated question with #5989
