### ISSUE TITLE
external/com_google_protobuf/protobuf.bzl", line 247, in cc_proto_library 		cc_libs += [default_runtime] trying to mutate a frozen object

### ISSUE THREAD

**Issue by chowkamlee81** [ApolloAuto/apollo#5978]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:  ubuntu14.0.4
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: version3.0

### Steps to reproduce the issue:
- ./apollo.sh build:
Iam following the same commands to work on apollo.3.0 version.
After giving ./apollo.sh build, i got error below.  pls help me out in resolving this issue.

administrator@in_dev_docker:/apollo$ ./apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
ERROR: /home/administrator/.cache/bazel/_bazel_administrator/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:441:1: Traceback (most recent call last):
	File "/home/administrator/.cache/bazel/_bazel_administrator/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD", line 441
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "/home/administrator/.cache/bazel/_bazel_administrator/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /home/administrator/.cache/bazel/_bazel_administrator/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD:742:1: Traceback (most recent call last):
	File "/home/administrator/.cache/bazel/_bazel_administrator/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/BUILD", line 742
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "/home/administrator/.cache/bazel/_bazel_administrator/540135163923dd7d5820f3ee4b306b32/external/com_google_protobuf/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: Evaluation of query "//..." failed due to BUILD file errors
============================
[ERROR] Build failed!
[INFO] Took 2 seconds

**Comment by natashadsouza** [comment]
Please delete folder {HOME}/.cache/bazel/_bazel_{USER}, run `bazel clean`, and try build again.
Let me know if you still face this issue. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
