### ISSUE TITLE
Where I can find sample Apollo HD Map

### ISSUE THREAD

**Issue by jiweiqi** [ApolloAuto/apollo#5981]
Apollo uses two map files, i.e., HD MAP in OpenDRIVE format (.xml) and basemap. As for the .xml map file, where I can get a free copy of sample HD Map for testing the Autonomous Driving system in our own simulation environment (or purchase). The zone of the map doesn't has to be very large.

In Chinese: 哪里可以获取免费或者收费的 Apollo 地图，.xml格式的那部分，basemap可有可无。

**Comment by dvangeyn** [comment]
@jiweiqi : In the docker image, once you load it, you should have /apollo/modules/map/data/sunnyvale_loop - which is not a huge area, but has all lanes, bike lanes, lights, etc. For example, the base_map.xml is 201MB, base_map.bin is 54MB. We have used it as a sample to produce our own maps from in the past.
