### ISSUE TITLE
/apollo/modules/tools/prediction/mlp_train.py ERROR. AttributeError: 'Sequential' object has no attribute 'flattened_layers'

### ISSUE THREAD

**Issue by bssung** [ApolloAuto/apollo#5983]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from source
- **Apollo version 3.0

I follow the guide https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_train_prediction_mlp_model.md.

But at the last step,  I excute  python mlp_train.py Apollo/data/prediction/feature.0.label.h5, I met a error: AttributeError: 'Sequential' object has no attribute 'flattened_layers'.

The whole log is as follows:

 python mlp_train.py /mnt/SSD2/apollo3.0/apollo/data/prediction/feature.0.label.h5
/home/cy/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Data load success.
data size = (221, 63)
training size = (176, 63)
mlp_train.py:133: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(30, kernel_initializer="he_normal", activation="relu", kernel_regularizer=<keras.reg..., input_dim=62)`
  W_regularizer = l2(0.01)))
mlp_train.py:138: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(15, kernel_regularizer=<keras.reg..., activation="relu", kernel_initializer="he_normal")`
  W_regularizer = l2(0.01)))
mlp_train.py:143: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, kernel_regularizer=<keras.reg..., activation="sigmoid", kernel_initializer="he_normal")`
  W_regularizer = l2(0.01)))
mlp_train.py:289: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  batch_size = 32)
Epoch 1/20
2018-11-05 15:08:13.070807: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-05 15:08:13.071021: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
176/176 [==============================] - 0s 2ms/step - loss: 1.7286 - acc: 0.4943
Epoch 2/20
176/176 [==============================] - 0s 40us/step - loss: 1.4630 - acc: 0.7727
Epoch 3/20
176/176 [==============================] - 0s 52us/step - loss: 1.3241 - acc: 0.8977
Epoch 4/20
176/176 [==============================] - 0s 50us/step - loss: 1.2342 - acc: 0.9318
Epoch 5/20
176/176 [==============================] - 0s 52us/step - loss: 1.1679 - acc: 0.9375
Epoch 6/20
176/176 [==============================] - 0s 49us/step - loss: 1.1169 - acc: 0.9489
Epoch 7/20
176/176 [==============================] - 0s 45us/step - loss: 1.0753 - acc: 0.9489
Epoch 8/20
176/176 [==============================] - 0s 51us/step - loss: 1.0383 - acc: 0.9489
Epoch 9/20
176/176 [==============================] - 0s 61us/step - loss: 1.0015 - acc: 0.9602
Epoch 10/20
176/176 [==============================] - 0s 53us/step - loss: 0.9702 - acc: 0.9602
Epoch 11/20
176/176 [==============================] - 0s 75us/step - loss: 0.9412 - acc: 0.9659
Epoch 12/20
176/176 [==============================] - 0s 59us/step - loss: 0.9118 - acc: 0.9659
Epoch 13/20
176/176 [==============================] - 0s 63us/step - loss: 0.8847 - acc: 0.9659
Epoch 14/20
176/176 [==============================] - 0s 72us/step - loss: 0.8585 - acc: 0.9659
Epoch 15/20
176/176 [==============================] - 0s 71us/step - loss: 0.8321 - acc: 0.9659
Epoch 16/20
176/176 [==============================] - 0s 62us/step - loss: 0.8068 - acc: 0.9659
Epoch 17/20
176/176 [==============================] - 0s 64us/step - loss: 0.7816 - acc: 0.9659
Epoch 18/20
176/176 [==============================] - 0s 59us/step - loss: 0.7575 - acc: 0.9659
Epoch 19/20
176/176 [==============================] - 0s 57us/step - loss: 0.7341 - acc: 0.9659
Epoch 20/20
176/176 [==============================] - 0s 43us/step - loss: 0.7102 - acc: 0.9659
Model trained success.
45/45 [==============================] - 0s 1ms/step

The accuracy on testing dat is 0.9333333359824286

For more detailed evaluation results, please refer to /mnt/SSD2/apollo3.0/apollo/modules/tools/prediction/mlp_train/evaluation_report.log
Traceback (most recent call last):
  File "mlp_train.py", line 311, in <module>
    save_model(model, param_norm, model_path)
  File "mlp_train.py", line 227, in save_model
    for layer in model.flattened_layers:
AttributeError: 'Sequential' object has no attribute 'flattened_layers'

Can anyone help?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
