### ISSUE TITLE
Apollo 3.0: Upgraded Architecture

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5984]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.0)**:

Hello :+1: 
     in https://github.com/ApolloAuto/apollo; there is a image that is Apollo 3.0: Upgraded Architecture. and in image,  it have a words that is "Mass production service components", what is means ? Please tell me. thank you

**Comment by lesun90** [comment]
Apollo going through a big makeover, just wait for it.

**Comment by Zhenni17** [comment]
Hi @breakisx , 

The Mass Production Service Components are the components that are critical for manufacturing autonomous driving vehicles. This module is not open sourced. If you or your company is interested in manufacturing smart vehicles, we are more than happy to connect you with our business development team and they can tell you more.
