### ISSUE TITLE
Documentation about the API used for routing

### ISSUE THREAD

**Issue by karussell** [ApolloAuto/apollo#5986]
The information about the routing and how it is integrated in the system is rather rare. Do you have more information about this?

https://github.com/ApolloAuto/apollo/tree/master/modules/routing

We would like to develop a replacement for this routing via our [open source GraphHopper routing engine](https://github.com/graphhopper/graphhopper) using world wide OpenStreetMap data. The idea is to replace the current web (?) service and do the routing (A-to-B route geometry & [navigation](https://github.com/graphhopper/graphhopper-navigation)) and route optimization (location assignment in style of Uber Pool) behind the scene. Or is the routing module meant for on-board routing?

**Comment by ycool** [comment]
The current version of routing module is on-board routing. Its input and output API is defined at https://github.com/ApolloAuto/apollo/blob/master/modules/routing/proto/routing.proto#L27.
