### ISSUE TITLE
gnss.ERROR 我使用的硬件是flexPak6 不是 ProPak6 我不知道该如何解决.

### ISSUE THREAD

**Issue by michaelchuh** [ApolloAuto/apollo#5987]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version ( 2.5)**:

### Steps to reproduce the issue:
Log file created at: 2018/11/06 09:40:54
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1106 09:40:54.423166  7540 serial_stream.cc:127] Open device /dev/novatel0 failed, error: No such file or directory
E1106 09:40:54.423207  7540 raw_stream.cc:306] data stream connect failed.
E1106 09:40:54.423213  7540 raw_stream.cc:260] gnss driver connect failed.
E1106 09:40:54.447410  7540 apollo_app.cc:59] gnss Init failed: DRIVER_ERROR_GNSS: Init stream failed!

data {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/novatel0"
        baud_rate: 115200
    }
}

rtk_from {
    format: RTCM_V3
    ntrip {
        address:"210.117.198.81"
        port: 2101
        mount_point:"VRS-RTCM31"
        user:"syhong5678"
        password:"xxxx"
        timeout_s: 5
    }
    push_location: true
}

rtk_to {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/novatel1"
        baud_rate: 115200
    }
}

command {
    format: NOVATEL_BINARY
    serial {
        device: "/dev/novatel2"
        baud_rate: 115200
    }
}

rtk_solution_type: RTK_RECEIVER_SOLUTION
imu_type: ADIS16488
proj4_text: "+proj=utm +zone=52 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

tf {
    frame_id: "world"
    child_frame_id: "novatel"
}

### Supporting materials (screenshots, command lines, code/script snippets):

![1](https://user-images.githubusercontent.com/44666135/48036250-cde7a380-e1aa-11e8-9c43-fca507909436.png)
![2](https://user-images.githubusercontent.com/44666135/48036254-d17b2a80-e1aa-11e8-8114-c94f1da19590.png)

**Comment by michaelchuh** [comment]
结果是要运行setup.sh来让设置成功初始化.

**Comment by YangHan101** [comment]
Developer solved the problem. Thanks for sharing @michaelchuh!
