### ISSUE TITLE
I want to know how you rename your video0/1 in /dev to /dev/camera/traffic_light, obstacle, lanemark ???

### ISSUE THREAD

**Issue by laureatian** [ApolloAuto/apollo#5988]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by laureatian** [comment]
UBSYSTEM=="video4linux", DEVNAME=="/dev/video0",ID_SERIAL=="Leopard_Imaging_AR023Z_1_0000001001", MODE="777", SYMLINK="/dev/obstacle"    
I add this rule in 100-leopaed.rules  in /etc/udev/rules.d/..,  however neither MODE is changed nor SYMLINK is created, reboot or replugin all doesn't work. I do not know why  this configuration file do  not work, I am working on ubuntu16.   Is there anything wrong with this rule???

**Comment by laureatian** [comment]
@gengqx

**Comment by laureatian** [comment]
Do you mean the ID_SERIAL you can get from this command"udevadm info --query=all  --name=/dev/video0"     @gengqx

**Comment by laureatian** [comment]
this is what I got from this command.
rules.d udevadm info --query=all --name=/dev/video0
P: /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/video4linux/video0
N: video0
S: v4l/by-id/usb-Leopard_Imaging_AR023Z_1_0000001001-video-index0
S: v4l/by-path/pci-0000:00:14.0-usb-0:2:1.0-video-index0
E: COLORD_DEVICE=1
E: COLORD_KIND=camera
E: DEVLINKS=/dev/v4l/by-id/usb-Leopard_Imaging_AR023Z_1_0000001001-video-index0 /dev/v4l/by-path/pci-0000:00:14.0-usb-0:2:1.0-video-index0
E: DEVNAME=/dev/video0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/video4linux/video0
E: ID_BUS=usb
E: ID_FOR_SEAT=video4linux-pci-0000_00_14_0-usb-0_2_1_0
E: ID_MODEL=AR023Z_1
E: ID_MODEL_ENC=AR023Z_1
E: ID_MODEL_ID=00db
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_0
E: ID_REVISION=0000
E: ID_SERIAL=Leopard_Imaging_AR023Z_1_0000001001
E: ID_SERIAL_SHORT=0000001001
E: ID_TYPE=video
E: ID_USB_DRIVER=uvcvideo
E: ID_USB_INTERFACES=:0e0100:0e0200:
E: ID_USB_INTERFACE_NUM=00
E: ID_V4L_CAPABILITIES=:capture:
E: ID_V4L_PRODUCT=AR023Z_1
E: ID_V4L_VERSION=2
E: ID_VENDOR=Leopard_Imaging
E: ID_VENDOR_ENC=Leopard\x20Imaging
E: ID_VENDOR_ID=2a0b
E: MAJOR=81
E: MINOR=0
E: SUBSYSTEM=video4linux
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=9321045247

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
