### ISSUE TITLE
module/perception/tool/data_generator

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#5989]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.0)**:

Hello Apollo:
   build apollo to use source in docker, and generate  bazel-bin and so on. I want to know in module/perception/tool/data_generator/data/sample_sensor_output_data that Where is it generated? How is it generated?  it seems that data_generated(module/perception/tool/data_generator/) haven't   generated sample_sensor_output_data.  and in bazel-bin/module/perception/tool/data_generator， when I  excute ./data_generator, and it will error. and generate some  data in module/perception/tool/data_generator/data/sensor_data_0， I can't understand the style and I can't understand why data_generatored  generate  the data which is not sample_sensor_output_data?

**Comment by techoe** [comment]
Thank you for using Apollo! We do not support data_generator any more. Please use Apollo 3.5 and let us know if you have any issue.
