### ISSUE TITLE
Why my apollo page http://localhost:8888/ (DreamView) Not update 

### ISSUE THREAD

**Issue by pancumtneu** [ApolloAuto/apollo#5991]
When my project compile complete ,I follow this procedure :bash docker/scripts/dev_start.sh ---bash docker/scripts/dev_into.sh----bash docker/scripts/release_start.sh ---bash apollo.sh build ----bash scripts/bootstrap.sh.Then the terminal prompt me :http://localhost:8888/  and then I input rosbag play demo_2.0. The program begin to run  .But the DreamView page not change,all buttons not work,there ain't a car and other option in it,ti seems that the web page didn't response.But it works previously.How can I solve this problem ？？？？？

**Comment by vlin17** [comment]
Could you check /apollo/data/log to see if there's any error?

**Comment by pancumtneu** [comment]
> Could you check /apollo/data/log to see if there's any error?
I checked this folder and want to see what happened inside,so I clear it but it works and the DreamView page changed somehow ,but it turn bad again.Meanwhile the Ubuntu prompt me there is not enough disk space for me ,the folder /home/apollo/data/core occupied 110G space .This is another problem . 
Please see these links   https://github.com/ApolloAuto/apollo/issues/2773  https://github.com/ApolloAuto/apollo/issues/4583

**Comment by pancumtneu** [comment]
> Could you check /apollo/data/log to see if there's any error?

The file roscore.out  in log folder is empty .None character

**Comment by vlin17** [comment]
Buttons don't not work because dreamview is waiting for ego-car position from /apollo/localization/pose topic. Please try running apollo/scripts/diagnostics.sh to see if there's any messages from the desired topic.

**Comment by pancumtneu** [comment]
> Buttons don't not work because dreamview is waiting for ego-car position from /apollo/localization/pose topic. Please try running apollo/scripts/diagnostics.sh to see if there's any messages from the desired topic.

It turns worse  the message is  :File "modules/tools/diagnostics/diagnostics.py", line 180
    print traceback.format_exc()    and the batch can't loacate the problem

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved in #6025
