### ISSUE TITLE
apollo base_map.xml point coordinate system

### ISSUE THREAD

**Issue by cevatbostancioglu** [ApolloAuto/apollo#5992]
Hello, i am converting apollo base_map.xml file format to opendrive format. 
As you described in apollo_hdmap_opendrive_specs_3.0 , point record is 
![image](https://user-images.githubusercontent.com/6525009/48074158-5be67d00-e1f1-11e8-9218-8296a2a786b6.png)

OpenDrive Point format is:
![image](https://user-images.githubusercontent.com/6525009/48074430-f47cfd00-e1f1-11e8-948b-6a8651743d0a.png)

and apollo seems to be spherical coordinate system format. So i am just wondering how i can convert this variables to opendrive format(looks like cartesian coordinate system) when z=0 everytime ?
it will always return 0 ?

![image](https://user-images.githubusercontent.com/6525009/48075035-51c57e00-e1f3-11e8-82e1-8eb6cd7e704c.png)

sph2cart -- Transform spherical to Cartesian coordinates(numpy dependent)

def sph2cart(az, el, r):
    rcos_theta = r * np.cos(el)
    x = rcos_theta * np.cos(az)
    y = rcos_theta * np.sin(az)
    z = r * np.sin(el)
    return x, y, z

**Comment by cevatbostancioglu** [comment]
i think i found something. CoordinateConvertTool::CoordiateConvert function is for transforms coordinates and it's using z=1 const. So do you think is this correct?
![image](https://user-images.githubusercontent.com/6525009/48115089-a2c88700-e272-11e8-961a-6c760fba5a51.png)

// usage
if (0 != pj_transform(pj_from_, pj_to_, 1, 1, &gps_longitude,
                          &gps_latitude, &gps_alt)) {
    std::string err_msg = "fail to transform coordinate";
    return Status(apollo::common::ErrorCode::HDMAP_DATA_ERROR, err_msg);
  }

//proj_api.h
int pj_transform( projPJ src, projPJ dst, long point_count, int point_offset,
                  double *x, double *y, double *z );

**Comment by jiweiqi** [comment]
Hi,

I think that the HD module in Apollo uses the [proj4](https://github.com/OSGeo/proj.4) api, as shown in your second post. It can convert the GPS coordinate to UTM.

Best,
Weiqi

**Comment by cevatbostancioglu** [comment]
Hello, 
i have tested as follows in apollo docker:
`
from pyproj import *
from pyproj import *
>>> inp = Proj("+proj=utm +zone=50 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs", preserve_units=True)
>>> wgs = Proj("+proj=longlat +ellps=WGS84 +no_defs")
>>> x1,y1=(-1.220249913e+02, 3.741627098e+01)
>>> print(transform(inp, wgs, x1, y1))
(112.51016289486766, 0.0003374709003722207) #(points nowhere)
`
x1,y1 comes from one of the lanes left boundarie point.
inp parameters comes from : https://github.com/ApolloAuto/apollo/blob/fb12723bd6dcba88ecccb6123ea850da1e050171/modules/perception/traffic_light/projection/test/data/multi_projection/velodyne64_novatel_extrinsics.yaml

wgs parameters come from base_map.xml header.

![image](https://user-images.githubusercontent.com/6525009/48269575-eecd2480-e448-11e8-9a10-4b4a4d53b643.png)

pyproj is python interface for proj4

So do you guys have any idea?

**Comment by cevatbostancioglu** [comment]
Hello all,
i solve the problem.

#https://awsm-tools.com/geo/geographic-to-utm
from pyproj import *
wgs84 = Proj("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
utm = Proj(<your utm header settings>)
lon, lat, az = transform(wgs84, utm, source_point.x, source_point.y, source_point.z)

**Comment by CCodie** [comment]
@cevatbostancioglu Hi, did you receive `apollo_hdmap_opendrive_specs_3.0` from Apollo Team?
Could you please share that file ? I wonder about the specifications.
ijh3062@gmail.com
I would be really appreciate if you could send me. Thanks !

**Comment by Wang4758** [comment]
@cevatbostancioglu Hi, could you please also share the `apollo_hdmap_opendrive_specs_3.0` file with me? I would really appreciate it. My Email is xiao.wang4758@gmail.com

**Comment by ArtistZhou** [comment]
where can i get apollo opendrive sample data? i found Apollo OpenDRIVE specification:https://github.com/chucklqsun/apollo_learning
