### ISSUE TITLE
Missing translations in Apollo Simulation (https://azure.apollo.auto)

### ISSUE THREAD

**Issue by svanlund** [ApolloAuto/apollo#5993]
Hi,

Just a quick question regarding the status of the simulation service. Sorry about reporting this so late, but I've been seeing this (in Chrome/Firefox) since I signed up at https://azure.apollo.auto some months back:

![image](https://user-images.githubusercontent.com/43830/48088107-61e45a00-e201-11e8-8ec1-8c9751218072.png)

Are others experiencing missing English translations or is it perhaps a problem specific to my account?

Thanks!

David

**Comment by siyangy** [comment]
@svanlund Can you take a second look? It should be fixed now.

**Comment by kiboliu** [comment]
@svanlund Could you try ctrl+shift+R to force refresh the page in case that there may exists some cache? Meanwhile could you provide me with your browser's language, you can get it by right click -> inspect and then type 'navigator.language' in console. Thank you.

**Comment by svanlund** [comment]
Good catch - it's the browser's language! I'm using "sv-SE". Setting it to "en-US" in the browser settings turned out to be a successful workaround.

**Comment by svanlund** [comment]
Retested - Now defaulting to English translations when using "sv-SE". Thanks!
