### ISSUE TITLE
Error related to 'flagfile' has been occuring for IMU-Vehicle calibration. 

### ISSUE THREAD

**Issue by pkh0104** [ApolloAuto/apollo#5996]
Hello.
I'm trying to calibrate IMU to Vehicle for autonomous driving in RTK mode.
But the IMU to Vehicle calibration program has been exiting with an error message.
Is this related to docker or something else?
The program is not revealed so that I can't know what this error means.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- dev_into
- /apollo$ ./scripts/bootstrap.sh
- Enable GPS, CAN bus and Localization in RTK mode.
- Check odometory topic.
- Downloads https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip
- Symbolic link *.so files the program needs.
- /apollo$ ./scripts/sensor_calibration.sh imu_vehicle

### Supporting materials (screenshots, command lines, code/script snippets):
- Error Message : "ERROR: flag 'flagfile' was defined more than once (in files '/home/tmp/gflags-2.2.0/src/gflags.cc' and '/tmp/gflags-2.2.0/src/gflags.cc')."
- Even there are no /home/tmp/gflags-2.2.0/ directory and /tmp/gflags-2.2.0/ directory. I was able to find /home/tmp/gflags-2.2.0.tar.gz file only.

**Comment by jinxiao1231** [comment]
When I input the command: bash sensor_calibration.sh lidar_camera
There is the same error as you provided, have you solve the problem?

**Comment by jinxiao1231** [comment]
@pkh0104 @weidezhang @natashadsouza

**Comment by pkh0104** [comment]
I still have the problem after reinstalling entire system(IPC).
By the way, I wrote wrong Apollo version. Apollo version which I'am using is not 3.0 but 3.x that I pulled form master branch on mid October.
At that time, The version of docker image was changed  to dev-x86_64-20180906_2002.
Can that change cause this problem by any chance?

**Comment by tkkhuu** [comment]
I am having a similar problem for lidar-camera calibrator, specifically, the error message is 
ERROR: something wrong with flag 'flagfile' in file '/tmp/gflags-2.2.0/src/gflags.cc'.  One possibility: file '/tmp/gflags-2.2.0/src/gflags.cc' is being linked both statically and dynamically into this executable.

I'm not sure how to debug this, any help is appreciated

**Comment by natashadsouza** [comment]
> Thank you for your comment.
> But I still have the problem after reinstalling entire system(IPC).
> By the way, I wrote wrong Apollo version. Apollo version which I'am using is not 3.0 but **3.x that I pulled from master branch on mid October.**
> At that time, The version of docker image was changed to dev-x86_64-20180906_2002.
> Can that change cause this problem by any chance?

@pkh0104 have you tried pulling from the latest branch? Please try that and let me know if you still see an error. Thank you for your interest in Apollo

**Comment by natashadsouza** [comment]
> I am having a similar problem for lidar-camera calibrator, specifically, the error message is
> ERROR: something wrong with flag 'flagfile' in file '/tmp/gflags-2.2.0/src/gflags.cc'. One possibility: file '/tmp/gflags-2.2.0/src/gflags.cc' is being linked both statically and dynamically into this executable.
> 
> I'm not sure how to debug this, any help is appreciated

@tkkhuu please try the suggestion recommended above: "purge all gflags and install apollo again." Let me know if you still see an issue post that. Thanks!

**Comment by wf1024966** [comment]
> Hello.
> I'm trying to calibrate IMU to Vehicle for autonomous driving in RTK mode.
> But the IMU to Vehicle calibration program has been exiting with an error message.
> Is this related to docker or something else?
> The program is not revealed so that I can't know what this error means.
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
> * **Apollo installed from (source or binary)**: source
> * **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0
> 
> ### Steps to reproduce the issue:
> * dev_into
> * /apollo$ ./scripts/bootstrap.sh
> * Enable GPS, CAN bus and Localization in RTK mode.
> * Check odometory topic.
> * Downloads https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip
> * Symbolic link *.so files the program needs.
> * /apollo$ ./scripts/sensor_calibration.sh imu_vehicle
> 
> ### Supporting materials (screenshots, command lines, code/script snippets):
> * Error Message : "ERROR: flag 'flagfile' was defined more than once (in files '/home/tmp/gflags-2.2.0/src/gflags.cc' and '/tmp/gflags-2.2.0/src/gflags.cc')."
> * Even there are no /home/tmp/gflags-2.2.0/ directory and /tmp/gflags-2.2.0/ directory. I was able to find /home/tmp/gflags-2.2.0.tar.gz file only.

hello,i canot download the calibration tool with the url:https://apollocache.blob.core.windows.net/apollo-cache/imu_car_calibrator.zip.Can you send me one copy?Thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
