### ISSUE TITLE
cnn_segmentation_test

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#6000]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.0)**:

Hello  Apollo : 
      when I run build apollo.sh test， it will  display some  test  pass.  but there is not cnn_segementation_test, so I  run a single test (bazel-bin/module/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test, it always display Segmentation fault
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CNNSegmentationTest
[ RUN      ] CNNSegmentationTest.test_cnnseg_det
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc:245: Failure
      Expected: out_objects.size()
      Which is: 13
To be equal to: 15
[  FAILED  ] CNNSegmentationTest.test_cnnseg_det (1888 ms)
[----------] 1 test from CNNSegmentationTest (1888 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1888 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CNNSegmentationTest.test_cnnseg_det

 1 FAILED TEST
Segmentation fault

**Comment by alexbuyval** [comment]
It just means that the test expected to find 15 objects, but found only 13.

I guess the Apollo updated the YOLO weights or another parameters, but forgot to update the cnn_segmentation_test. However, I am not sure.

**Comment by breakisx** [comment]
> It just means that the test expected to find 15 objects, but found only 13.
> 
> I guess the Apollo updated the YOLO weights or another parameters, but forgot to update the cnn_segmentation_test. However, I am not sure.

Hello! alexbuyval @alexbuyval , 
      I  changed the number 15 to 13 in modules/perception/obstacle/lidar/segmentation/cnnseg/cnn_segmentation_test.cc ,and run, it display to had passed, but in finally display segmentation fault(core dumped)

**Comment by xinwf** [comment]
@breakisx ,  I also have done this, it will not success until there is an obstacle in the picture. You can take a photo with pixel 1920*1080, and clear lane, the obstacle can be vehicle or pedestrian.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thank you @xinwf
