### ISSUE TITLE
高精地图咨询

### ISSUE THREAD

**Issue by riskeverything** [ApolloAuto/apollo#6003]
请问高精地图的生成，必须是采用apollo的硬件平台方案，还是只需要相同的数据格式？另外，地图的生成是在百度做吗？收费还是免费？

**Comment by daohu527** [comment]
@riskeverything There is a [online guide](https://github.com/ApolloAuto/apollo/blob/62ad889c00df7f68261a23da03c1e535bc3d1309/docs/quickstart/Apollo_3_5_map_collection_guide.md), I think it's all right to collect a map by yourself. If you record the bag with the some format.
The hardware may be a bit redundant for map acquisition, and also need to be calibrated. I think there may be a deprecated version of the hardware and software solution in the future. It may work only by mailing a device.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions.
Thanks!
