### ISSUE TITLE
Dreamview problems

### ISSUE THREAD

**Issue by PPR-HIT** [ApolloAuto/apollo#6005]
module monitor and dreamview is already running but the dreamviewer localhost:8888 shows nothing
![screenshot from 2018-11-09 18-36-54](https://user-images.githubusercontent.com/35942278/48257826-96992100-e44e-11e8-91b1-54992cbb8965.png)

**Comment by pancumtneu** [comment]
I've got the same problem .It's awful.But sometimes it work I don't know what to do

**Comment by siyangy** [comment]
You can check browser console, log under /apollo/data/log/dreamview.INFO and https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md for further troubleshooting.

**Comment by djbyrne** [comment]
I had the same problem while using firefox. Switching to chrome resolved the issue.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. If you have any additional questions feel free to reopen. Thanks!
