### ISSUE TITLE
sensors data sync

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#6006]
Hi Apollo,
    请问apollo中，有哪些传感器之间需要做同步？如何实现同步的？谢谢。

**Comment by ahuer2435** [comment]
谢谢,看到有一个radar,一个单目,一个双目,一个lidar,一个gps和一个imu.
这些传感器,有哪些之间需要做数据同步,如何实现数据同步?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
