### ISSUE TITLE
How could lattice planning work if kappa & dkappa are zero in reference line

### ISSUE THREAD

**Issue by quhezheng** [ApolloAuto/apollo#6011]
### Confused by the current implementation on lattice planner

- **Frenet coordinate refer to kappa & dkappa from HDMap in coordinate converstion, why the code initiate  them as zero but never update it else values?**
- **lattice planner never got used in code base? I don't see any class factory refer to it**
- **Is  lattice planner tested & usable or under development?**

**Comment by lianglia-apollo** [comment]
We are currently using public_road_planner in Apollo 3.5.
