### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#6012]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.0 release , is not master)**:

Apollo Hello: 
      in apollo source, there is many  the file of test, and I execute bash apollo.sh build_gpu(on apollo IPC and I install nvidia gpu driver and cuda and so on), and then I enter bazel-bin/module/perception/obstacle/lidar/object_builder/min_box/min_box_test, execute it(I change some configure)，so it display  the time of execution that is  different with ‘’bash apollo.sh test‘（the same example for min_box_test）’ and cnn_segemention_test always display  segement dump. Please help me,thank you

**Comment by natashadsouza** [comment]
@breakisx please share a screenshot of the error message. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as there has been no responses.
