### ISSUE TITLE
Overtake Behavior in Apollo

### ISSUE THREAD

**Issue by BoChang11** [ApolloAuto/apollo#6015]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I would like to understand how the **Overtake** scenario has been covered in Apollo.

The one explained in the **Traffic Decider** deals with obstacle which is trying to overtake the Autonomous car. **My question is on the scenario where Autonomous Car overtakes the Obstacle moving in front of it.**

Please help me in below doubts:
1. Whether the overtake (ego vehicle overtaking obstacle) is implemented in Apollo?
2. If implemented, what are the conditions the obstacle and Autonomous vehicle need to satisfy?
3. Whether the overtake would be done instantly or initially Follow will be done and gradually overtake?
4. C++ file where the overtake condition is covered.

BR, Chang

**Comment by ycool** [comment]
overtaking is implemented in Apollo and it is determined by ST algorithm. Its implementation can be found at https://github.com/ApolloAuto/apollo/blob/master/modules/planning/tasks/deciders/speed_decider/speed_decider.cc.
