### ISSUE TITLE
where is the Dockerfile for aarch64 docker image?

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6017]
hello apollo guys, I can see there is an aarch64 docker image but i can't see the Dockfile for it. There is only a "dev.x86_64.dockerfile" for x86 platform. I have some problem in building apollo in arm platform. Could you tell me where i can find the dockerfile for aarch64?

thanks

**Comment by zhxt** [comment]
You can try to apply the patches from PR #5953, or waiting for the merge.

**Comment by narendahr15** [comment]
Hi @zhxt , Is there any plans for supporting the Arm 64 platforms(like Drive PX2)?  I have followed your tutorial for building the apollo 3.0 without the docker. But still it would be great to have the official support from Apollo.

**Comment by zhxt** [comment]
@narendahr15 Sorry, I have no exact information about the plans since I'm not from the official team. However, as you may see from that PR, supports for arm64 platform is on the way, at least for TX2, so I think it won't be too long for PX2. Let's see.
