### ISSUE TITLE
GEM vehicle parameters

### ISSUE THREAD

**Issue by ankitvora7** [ApolloAuto/apollo#6019]
I was looking at the GEM e2 vehicle spec sheet on the Polaris website (https://gem.polaris.com/en-us/e2/specs/) to verify the vehicle parameters provided in apollo/modules/common/data/gem_config.pb.txt. Few parameters like length, wheel_base, turning_radius seem to be different. What's the reason for this ? Is it intentional ? Thanks in advance.

**Comment by natashadsouza** [comment]
@ankitvora7 that config file was written by our partners from AutonomousStuff. It'd be best if you could reach out to them regarding the parameters.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
