### ISSUE TITLE
would it be possible that the use any map to utilize the 'CartesianFrenetConverter' function? 

### ISSUE THREAD

**Issue by vivanraaj** [ApolloAuto/apollo#6022]
my map only gives out x and y position but i want them to be mapped to frenet 's' and 'd'

**Comment by zezhou** [comment]
You can use road center line to  build reference line. When you have reference line, you can map any point to frenet 's' and 'd'

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
