### ISSUE TITLE
How to get localization in navigation SimControl mode ?

### ISSUE THREAD

**Issue by wujiyoung** [ApolloAuto/apollo#6024]
I want to simulate navigation planning in SimControl mode with a smoothed reference line, but I can not get localization if I do not play a relative rosbag. However, in standard mode, the planning simulation works well with a given routing result, which do not access any localization data from a rosbag or something else. 
Thus, my question is:
+ where the input localization for planning module come from in standard mode ?
+ how can I get the localization data in navigation mode ?

**Comment by daohu527** [comment]
@wujiyoung They are not the same in principle. Since it is navigation, why do you need planning?
