### ISSUE TITLE
Why there isn't a picture or car in DreamView 

### ISSUE THREAD

**Issue by pancumtneu** [ApolloAuto/apollo#6025]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by pancumtneu** [comment]
I'v compiled the project as the tutorial told me: bash docker/script/dev……but  at the DreamView page http://localhost:8888/  there isn't an animation inside .But it works few days ago and these days  it turns bad.How could solve this problem .I check the log file "/home/apollo/apollo/data/log/roscore.out"  it print Couldn't find an AF_INET address for [in_release_docker] what does it mean?   I'm going  insane！！！
Here is the same question link by me https://github.com/ApolloAuto/apollo/issues/5991

**Comment by pancumtneu** [comment]
The command rosbag play demo2.0.bag   runs normally

**Comment by siyangy** [comment]
@pancumtneu Can you please check this document https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md? You will be able to find some most common Dreamview related issues along with how to debug them.

**Comment by pancumtneu** [comment]
> @pancumtneu Can you please check this document https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md? You will be able to find some most common Dreamview related issues along with how to debug them.

Thank you for your answer！ I have solved the problem.I miss a important procedure "bash docker/scripts/release_into.sh" which is referred to in the link you provided .But the command isn't emerged in previous tutorials.    I run the "docer ps" and finding that the "rosbag play“ should run in  “apollo_release” image instead of "apollo_dev". I really don't know their difference so I think I have to study the docker and ROS  .

**Comment by pancumtneu** [comment]
> @pancumtneu Can you please check this document https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md? You will be able to find some most common Dreamview related issues along with how to debug them.

By the way ，Are you Chinese?

**Comment by pancumtneu** [comment]
> @pancumtneu Can you please check this document https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md? You will be able to find some most common Dreamview related issues along with how to debug them.

By the way ，Are you Chinese?

**Comment by xinwf** [comment]
Now, you can close this issue.
