### ISSUE TITLE
hdmap - I want to know more about the map in the simulation 

### ISSUE THREAD

**Issue by carlin314** [ApolloAuto/apollo#603]
I see the map tool in modules, but I guess the hdmap in your simulation is sunnyvale_loop.bin,

but I can't find this file, I dont really understand the map

it comples the map in opendrive format to binary, all i know is this

but I hope there is some more document to use the map tool

could someone who know about it tell me how the original file .xml to the final file .bin

**Comment by msbeta** [comment]
You can try the following command to convert file .xml to .bin file, parameter InputDir refers to the directory where XML is saved, and OutputDir refers to the output directory where bin will be saved.
bazel build //modules/map/tools:proto_map_generator
bazel-bin/modules/map/tools/proto_map_generator --map_dir=InputDir --output_dir=OutputDir

**Comment by chucklqsun** [comment]
@msbeta is Apollo using OpenDrive format for hdmap? How to open and edit the map file of sunnyvale for some purposes, such as modify lane? I use odrviewer from opendrive.org to open the map xml file and failed.

**Comment by rockcdr** [comment]
Tested on OpenDrive sample files (V1.4 format) from OpenDrive.org. "proto_map_generator" does not work.

**Comment by chucklqsun** [comment]
@rockcdr I've reviewed the Apollo code and find its HDMap head and body structure does NOT completely follow OpenDrive v1.4 official spec.

**Comment by rockcdr** [comment]
@chucklqsun Yes, in the base_map.xml, it is strange to have revMajor="0" and revMinor="6". Should be "1" and something.

`<?xml version="1.0" encoding="UTF-8" ?>
<OpenDRIVE xmlns="http://www.opendrive.org">
    <header revMajor="0" revMinor="6" name="yongfengchanyeyuan" version="1.4" date="2017-11-20T17:58:11" north="3.741827476e+01" south="3.740239160e+01" east="-1.219960182e+02" west="-1.220307622e+02" vendor="Baidu">
        <geoReference>
            <![CDATA[+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs]]>
</geoReference>
    </header>`

**Comment by msbeta** [comment]
@chucklqsun @rockcdr The Apollo OpenDrive Format has modified and extended the standard OpenDrive specification, so if necessary, you can email us，or you can leave your email address，we will send the the Apollo OpenDrive specification to you.

**Comment by msbeta** [comment]
Hi @carlin314 @chucklqsun @rockcdr , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open an new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Comment by chucklqsun** [comment]
@msbeta Thanks for your reply. It will be very helpful if you send me a copy of Apollo OpenDrive specification (to 77167680[at]qq.com ).

**Comment by msbeta** [comment]
hi, @chucklqsun  , I have already emailed the Apollo map specification document to you. Please feel free to let me know if there are any other issues we can help with on the map side, thanks!

**Comment by chucklqsun** [comment]
@msbeta Got it! Thanks mate.

**Comment by carlin314** [comment]
@msbeta It will be also very helpful if you send me a copy of Apollo OpenDrive specification (to cmw314lion@gmail.com ).I am also confused of the difference between the origin opendrive and apollo opendrive

**Comment by thilo20** [comment]
can you please send me the Apollo OpenDrive spec to Thilo.schaper@gmx.de?

**Comment by candyguo** [comment]
can you please send me the Apollo OpenDrive spec to candyguo_fly@163.com?

**Comment by methedras** [comment]
@msbeta Please send me the current Apollo OpenDRIVE spec to peter.fryscak@vectorzeroinc.com

**Comment by dorintt** [comment]
Why not publish the apollo specific opendrive spec? I thought Baidu wants to make everything open source so it's easy to get started.

**Comment by whunmr** [comment]
@msbeta, could you please send me the Apollo OpenDrive spec to whunmr[at]gmail.com

thanks mate.

**Comment by alexbuyval** [comment]
@msbeta  Could you, please, send me the Apollo OD spec to alexbuyval@gmail.com

Thanks!

**Comment by xiangguomin** [comment]
@msbeta Can you please send me the apollo OpenDrive spec to xiangguomin@gmail.com as well?
Thanks!

**Comment by natashadsouza** [comment]
Hi going forward please use: [the following link ](https://www.surveymonkey.com/r/DXWK3Q6) to send us your details. Thanks!

**Comment by JWhitleyAStuff** [comment]
@msbeta and/or @natashadsouza - I have filled out the above form several days ago but have not received any response. Could you please email this to me at jwhitley@autonomoustuff.com? Thank you.

**Comment by jmloveyj** [comment]
@msbeta and/or @natashadsouza - I have filled out the above form several days ago but have not received any response. Could you please email this to me at jmloveyj@sina.cn? Thank you.

**Comment by ruisir001** [comment]
@msbeta @natashadsouza , Could you, please, send me the Apollo OpenDrive spec to liurui019@163.com

Thanks!

**Comment by ruisir001** [comment]
@chucklqsun Could you, please, send me the Apollo OpenDrive spec to liurui019@163.com

**Comment by Wang4758** [comment]
@msbeta Could you please send me the Apollo OpenDrive spec to xiao.wang4758@gmail.com?

**Comment by ankaret** [comment]
@msbeta @natashadsouza  I have filled the survey but haven't received any email from you, can you please send me the Apollo OpenDrive spec to anna.rettinger@gmail.com?

**Comment by diff8911** [comment]
@msbeta Could you please send me the Apollo OpenDrive spec to diff8911@gmail.com?

**Comment by natashadsouza** [comment]
Closing this issue. Please follow up on #3005 with all your requests. Thanks!

**Comment by MonkeyJohn** [comment]
> Closing this issue. Please follow up on #3005 with all your requests. Thanks!
@natashadsouza Could you please send me the Apollo OpenDrive spec to xjs127@163.com?

**Comment by pjs9115916** [comment]
> @msbeta Got it! Thanks mate.

It will be also very helpful if you send me a copy of Apollo OpenDrive specification (to panjisong@cuhk.edu.cn ).I am also confused of the difference between the origin opendrive and apollo opendrive

**Comment by ArtistZhou** [comment]
where can i get apollo opendrive sample data? i found Apollo OpenDRIVE specification:https://github.com/chucklqsun/apollo_learning

**Comment by ArtistZhou** [comment]
> @chucklqsun @rockcdr The Apollo OpenDrive Format has modified and extended the standard OpenDrive specification, so if necessary, you can email us，or you can leave your email address，we will send the the Apollo OpenDrive specification to you.

Can Ｉ　get  xml file from you? I can  not find this file base_map.xml

**Comment by windcatcher** [comment]
@msbeta Could you please send me the Apollo OpenDrive spec to lms681@163.com?

**Comment by wangruoyi123456** [comment]
@msbeta@natashadsouza  Could you please send me the Apollo OpenDrive spec to wangruoyi@neolix.cn
thanks

**Comment by glebkiselev** [comment]
@msbeta Could you please send me the Apollo OpenDrive spec to glebkiselev777@gmail.com?

**Comment by sszove** [comment]
@msbeta Could you please send me the Apollo OpenDrive spec to pisceszove@163.com?

**Comment by wangzhensuo** [comment]
> 
> 
> Tested on OpenDrive sample files (V1.4 format) from OpenDrive.org. "proto_map_generator" does not work.
I tested on base_map.xml from apollo. it is also could not be convert.
`./bazel-bin/modules/map/tools/proto_map_generator --map_dir=./modules/map/data/sunnyvale_loop --output_dir=./modules/map/data/sunnyvale_loop`

**Comment by wangzhensuo** [comment]
I found a method to fix this error.
when I run cmd,I meet errors:

> [cpoc@in-dev-docker:/apollo]$ bazel-bin/modules/map/tools/proto_map_generator --map_dir=modules/map/data/new --output_dir=modules/map/data/new
E0111 10:33:41.756587 28383 opendrive_adapter.cc:44] []fail to parse opendrive header, unsupport data in more than one zones
F0111 10:33:41.757151 28383 proto_map_generator.cc:39] Check failed: apollo::hdmap::adapter::OpendriveAdapter::LoadData(map_filename, &pb_map) []fail to load data from : modules/map/data/new/base_map.xml
*** Check failure stack trace: ***
    @     0x7f6591ecb60d  google::LogMessage::Fail()
    @     0x7f6591ecdaca  google::LogMessage::SendToLog()
    @     0x7f6591ecb01d  google::LogMessage::Flush()
    @     0x7f6591ecea79  google::LogMessageFatal::~LogMessageFatal()
    @     0x557fab562409  main
    @     0x7f6590d31b97  __libc_start_main
    @     0x557fab56216a  _start
    @              (nil)  (unknown)
Aborted (core dumped)

then,I found where errors occurs

    int eastZone = GetLongZone(east);
    int westZone = GetLongZone(west);
    if (eastZone != westZone) {
      std::string err_msg = "unsupport data in more than one zones";
      return Status(apollo::common::ErrorCode::HDMAP_DATA_ERROR, err_msg);
    }

then,I opened base_map.xml,and change "east"  and "west" to the same value.
and run above cmd
(bazel-bin/modules/map/tools/proto_map_generator --map_dir=modules/map/data/new --output_dir=modules/map/data/new) 
again. it is successfully generate base_map.txt and base_map.bin from base_map.xml.
I do not know this method is correct or not,if anyone know a better method,please tell me,thank you.

**Comment by rahulkrishn1990** [comment]
Hallo @natashadsouza,

I have filled above form requesting the Custom Apollo's OpenDrive format.
Could you please email me the document at enishettyrahul@gmail.com ?

Regards,
Rahul

**Comment by SamerSeed** [comment]
Could you send your specks on iskander.aka@mail.ru, please?

**Comment by rahulkrishn1990** [comment]
Hallo Sameer,

Do you work for Apollo?

Or do you need the Apollo map specifications?

Regards,
Rahul

**Comment by SamerSeed** [comment]
I m trying to dig into apollo. I need the Apollo map specifications.
 
 
С уважением,
Отрощенко Александр
 
  
>Суббота, 27 марта 2021, 11:08 +03:00 от rahulkrishn1990 ***@***.***>:
> 
>  Hallo Sameer,
>
>Do you work for Apollo?
>
>Or do you need the Apollo map specifications?
>
>Regards,
>Rahul
>
>

**Comment by rahulkrishn1990** [comment]
Ok. I do not have it.

I am also waiting for reply from Apollo community.

**Comment by yufeilongyuan** [comment]
LGSVL还是很香的，导入导出，不难吧。细微差别，自己改一下代码就好了啊，目前看还不用修改

**Comment by Mingkun-wxc** [comment]
Thanks for your reply. It will be very helpful if you send me a copy of Apollo OpenDrive specification (to mingkun_wxc@163.com ).

**Comment by worldmapforyou** [comment]
I developed an online apollo opendrive visualization tool, refer to the following website: www.worldmapforyou.com, you can open the apollo opendrive data of ***.bin, the data will not be sent to the server, but directly parsed on the client. Can view the properties of the map
