### ISSUE TITLE
planner是如何避免跟轨迹冲出道路边缘如防护栏等的？

### ISSUE THREAD

**Issue by quhezheng** [ApolloAuto/apollo#6038]
生成trajectory时，只考虑了obstacle和reference line的关系， 没有看到处理防护栏道路边缘的逻辑， 为什么？

**Comment by zezhou** [comment]
在制作生成高精地图时，你说的护栏、道路边缘等非道路的就已经标记为不可行驶区域被排除了。另外在车辆行驶时，perception 也会实时检测这些障碍物。传到 planning时，这些都已经被标记为不可行驶区域， planning只会在可行驶区域撒点规划，自然不需要处理这些不可行驶静态障碍物的逻辑。

**Comment by lianglia-apollo** [comment]
Please see the above comments.
