### ISSUE TITLE
Please send car initial position and map data.

### ISSUE THREAD

**Issue by GerberaTetra1991** [ApolloAuto/apollo#604]
Access HMI

Access HMI by opening your favorite browser, e.g. Chrome, go to http://localhost:8887, click Dreamview to start. 

And click upper-right Dreamview button to load Dreamview UI.

but I can't see the Dreamview UI.  I can see a big logo “apollo” and tips“Please send car initial position and map data.”

What should I do to send car initial position and map data.

Thanks for your help！

**Comment by xiaoxq** [comment]
You need to have these messages in ROS.

To simulate, you can play a bag. E.g.:
    rosbag play -l docs/demo_guide/demo_1.5.bag

**Comment by GerberaTetra1991** [comment]
Thanks！
Now i can play it.
