### ISSUE TITLE
packet rate for HDL64E_S3D

### ISSUE THREAD

**Issue by rgc183** [ApolloAuto/apollo#6041]
https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/velodyne/velodyne_driver/src/driver/driver64.cpp#L36 can anyone tell me how do we calculate this packet rate? Number of points generated for S3D are 1.3 millions/sec according to that packet rate should be same as 64E_S2. But here why it is different ? Any link to document would be helpful.

**Comment by rgc183** [comment]
bounce.!

**Comment by fengqikai1414** [comment]
HDL64E_S3D meas HDL64E_S3 dual returns mode, will generate 2.2million points seconds.

**Comment by hzdsdhr** [comment]
check this:https://answers.ros.org/question/67320/packet-rate-of-velodyne-hdl-64e-in-velodyne_driver/

**Comment by rgc183** [comment]
Thanks @fengjingchao-cn ! 
All the lidars are configurable using HW commands. Does it mean that even if we configure to use strongest mode it will still be throwing 2.2 million points?

**Comment by rgc183** [comment]
Also @fengqikai1414 do you know how to detect duplicate points? Is there any field specifying that ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
