### ISSUE TITLE
question about apollo map module 

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#6048]
code version: apollo 3.0
Dear apollo developer,
     when i trace planning module code,i find in navigation mode, apollo use relative map,
    so planning module receive the map information from relative map, i don't understand the lane and the path what both of means, and segment , 
    is there some document to describe lane 、path and segment information? such as lane-id and path-id,what is means?

**Comment by xinwf** [comment]
According to my understanding, those three concepts in map may can be shown as following:
This is a path from A to B
        ---------------------------------------
                         lane 0
        ---------------------------------------
A                       lane 1                                                           B
        ----------------------------------------------------
        |       seg0     |       seg1       |       seg2       |
        ----------------------------------------------------

The path in our life, is something like xxxx Road, and the the lane is how many cars can run side by side at the same time, segment is the smaller unit defined by apollo team, I think maybe it is easier for the car  to change lane or overtake.

**Comment by xinwf** [comment]
@freeclouds , no, in our relative map, there is no segment, just one lane, I think the segment concept is meaningful in HdMap,  we haven't tried add two lanes by this way, I don't know whether it will success or not.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
