### ISSUE TITLE
What is and Where is "ApolloOdometry" defined?

### ISSUE THREAD

**Issue by kimjongyoung** [ApolloAuto/apollo#6049]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by natashadsouza** [comment]
@kimjongyoung you can read more about it [in this guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/multiple_lidar_gnss_calibration_guide.md)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
