### ISSUE TITLE
/apollo/module/perception/data/hm_tracker_test/*.pose *.seg

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#6053]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source )**:
- **Apollo version ( 3.0)**:

hello Apollo： 
    excuse me, in  modules/perception/data/hm_tracker_test/, there are seven group files, Does each set of files represent an obstacle that needs to be followed? Or are these files a state of obstruction to follow?
     Thank  you very much! 
      good best.

**Comment by techoe** [comment]
The files are data for a unit test of tracking in /apollo/modules/perception/obstacle/lidar/tracker/hm_tracker/hm_tracker_test.cc
each row in *.pos represents a pose of an object
object_id, timestamp, translation_x, translation_y, translation_z, quaternion_x, quaternion_y, quaternion_z, quaternion_w
*.seg contains a set of point cloud
