### ISSUE TITLE
Difference beteween README.md  and apollo.auto's Apollo Road Map

### ISSUE THREAD

**Issue by take97531** [ApolloAuto/apollo#6058]
There is difference in 2020 beteween  README.md's scope and features of Apollo release  and apollo.auto's Apollo Road Map. I have interested in this project, so I want to know which one is correct. 

-README.md
![readme md](https://user-images.githubusercontent.com/37101456/48784275-b02b4a00-ed25-11e8-8696-6a4b20b1d10f.PNG)

-apollo.auto
![apollo auto](https://user-images.githubusercontent.com/37101456/48784264-ac97c300-ed25-11e8-8659-52b399df4a0b.PNG)

**Comment by natashadsouza** [comment]
@take97531 if you look at the titles carefully, you would notice that they are the same. While the apollo.auto is a future plan, the diagram in the Readme is an update on what has been accomplished so far. Both serve different purposes. Let me know if you have any additional questions. Thanks!

**Comment by natashadsouza** [comment]
@take97531 the ReadMe graph is an ongoing development graph which says that Highways etc will be developed post 2020. Let me know if you have any additional questions. Thanks.

**Comment by zk5580752** [comment]
> @natashadsouza I mean diagram in Readme says "Highway and roads full autonomous in 2020" but apollo.auto(http://apollo.auto/) says it's 2021's plan.

Yes, thank you for you reminder. Apollo cannot plan an exactly diagram without any progress, but it is almost close between them. The progress will be dynamic changes and we think that will be fine prepared in around 2020-2021.

**Comment by natashadsouza** [comment]
Closing this issue currently. If you have any additional questions feel free to reopen this issue. Thanks!
