### ISSUE TITLE
Apollo 3.0 中只用一个前置camera和一个前置radar能实现高速公路上的换道吗

### ISSUE THREAD

**Issue by weiyouxiangqian** [ApolloAuto/apollo#6061]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by natashadsouza** [comment]
@weiyouxiangqian 车上还有其他传感器吗？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
