### ISSUE TITLE
navigation模式下的仿真怎么更新车身位置？

### ISSUE THREAD

**Issue by wujiyoung** [ApolloAuto/apollo#6067]
各位大佬们，我想实现自定义参考线数据的planning仿真，在#6024 中我已经提过这个问题，可能我的英语水平比较渣，各位大佬都不理解，我这边再用中文说明一下吧。
我知道，在standard的仿真模式下，开启planning和routing模块之后，选择一条默认路线就可以实现planning的仿真了，但我想知道这种模式下车的位置是怎么更新的，是根据planning输出的轨迹来的吗？如果是这样的话，为什么navigation模式下不行？
在navigation模式下，我通过`moudles/tools/navigator/navigator.py`发送了一条参考线轨迹，然后打开planning和relative map模块进行仿真，但是这样好像并没有作用，我在#6014 中描述了这个情况，可惜并没有人帮忙解答。只有当我循环播放相应的录制的rosbag时，planning貌似才能正常，所以我觉得关键应该在于车身位置的更新，因为播放的rosbag中时包含了定位信息的。
那么现在的问题就是，为什么standard模式下仿真，不需要额外的定位信息也能正常实现，而navigation模式下还需要额外的定位信息？navigation模式下怎样才能实现与standard模式一样根据planning的输出轨迹更新位置？

**Comment by zezhou** [comment]
没有看明白你的问题, 我理解可能不是定位的问题, 而是 reference line 的问题. 
standard 模式中的  reference line 是 HDMap 中来的,  HDMap 是事先采好的，作为本地文件存在硬盘上。navigation 模式中的  reference line 用了 relative map.  relative map 可以是感知实时生成的，仿真时由 rosbag 包中发送的。所以需要播放bag包...

**Comment by wujiyoung** [comment]
standard模式下仿真的话不是需要车辆实时位置的吗，这个实时位置时怎么获取的？navigation模式下可以通过rosbag包中发送得到

**Comment by wujiyoung** [comment]
@xinwf 这个我知道，但是planning模块是需要localization数据的，我在记录standard模式下rosbag的时候也是看到有localization数据的，我想知道的是这个localization数据是怎么获取的。有地图是没错的，但是不是有地图就能有及时的定位了啊，这个还得根据planning的结果吧，所以我好奇的是planning的输入localization是不是根据前面帧输出的trajectory获得的，而起始位置则是routing的起始位置。

**Comment by zezhou** [comment]
可以看下这个https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/backend/sim_control/sim_control.cc 中  SimControl::OnReceiveNavigationInfo 和 SimControl::PerfectControlModel 的实现。
前面一个是在navigation模式下, localization 就是 relative map 实时算出的path的第一个点. 后面一个讲 standard 模式下，localization 就是取的 planning 的trajectory上相对时间对应应的点.

**Comment by wujiyoung** [comment]
@zezhou 非常感谢

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
