### ISSUE TITLE
How can I handle this build error?

### ISSUE THREAD

**Issue by aimhigh53** [ApolloAuto/apollo#6068]
My device:MACBOOK pro 2018
-RAM:16G
-SSD:512
-OS: [iOS]

Thank you guys for your interest in my issue :)

I setup this software https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide  .

But I ran into this build error....

How can I deal with this problem?

 
ins25k@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] System memory [1.95G] is lower than minimum required memory size [2.0G]. Apollo build could fail.
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
____Loading package: modules/planning/proto
____Loading package: modules/drivers/camera/nodes
____Loading package: modules/perception/obstacle/camera/detector/yolo_camera_detector/proto
____Loading package: modules/monitor/conf
____Loading package: modules/map/proto
____Loading package: modules/localization/msf/local_tool/map_creation
____Loading package: modules/drivers/lidar_velodyne/proto
____Loading package: modules/drivers/radar/racobit_radar/proto
____Loading package: modules/control/integration_tests
____Loading package: modules/canbus/tools
[INFO] Building on x86_64...
[INFO] Building with --jobs=6 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Found 1821 targets...
INFO: From Compiling modules/drivers/camera/usb_cam/usb_cam.cc:
modules/drivers/camera/usb_cam/usb_cam.cc:231:13: warning: 'void apollo::drivers::camera::mono102mono8(char*, char*, int)' defined but not used [-Wunused-function]
 static void mono102mono8(char *RAW, char *MONO, int NumPixels) {
             ^
modules/drivers/camera/usb_cam/usb_cam.cc:241:13: warning: 'void apollo::drivers::camera::yuyv2rgb(char*, char*, int)' defined but not used [-Wunused-function]
 static void yuyv2rgb(char *YUV, char *RGB, int NumPixels) {
             ^
INFO: From Compiling modules/drivers/gnss/third_party/rcvraw.c:
modules/drivers/gnss/third_party/rcvraw.c: In function 'decode_glostr':
modules/drivers/gnss/third_party/rcvraw.c:526:7: warning: unused variable 'M' [-Wunused-variable]
   int M = getbitu(buff, i, 2);
       ^
modules/drivers/gnss/third_party/rcvraw.c:522:7: warning: unused variable 'NT' [-Wunused-variable]
   int NT = getbitu(buff, i, 11);
       ^
modules/drivers/gnss/third_party/rcvraw.c:500:7: warning: unused variable 'ln' [-Wunused-variable]
   int ln = getbitu(buff, i, 1);
       ^
modules/drivers/gnss/third_party/rcvraw.c:442:7: warning: variable 'P4' set but not used [-Wunused-but-set-variable]
   int P4 = 0;
       ^
modules/drivers/gnss/third_party/rcvraw.c:441:7: warning: variable 'P3' set but not used [-Wunused-but-set-variable]
   int P3 = 0;
       ^
modules/drivers/gnss/third_party/rcvraw.c:440:7: warning: variable 'P2' set but not used [-Wunused-but-set-variable]
   int P2 = 0;
       ^
modules/drivers/gnss/third_party/rcvraw.c:439:7: warning: variable 'P1' set but not used [-Wunused-but-set-variable]
   int P1 = 0;
       ^
modules/drivers/gnss/third_party/rcvraw.c:438:7: warning: variable 'P' set but not used [-Wunused-but-set-variable]
   int P = 0;
       ^
INFO: From Compiling modules/drivers/gnss/third_party/rtcm3.c:
modules/drivers/gnss/third_party/rtcm3.c: In function 'decode_type1045':
modules/drivers/gnss/third_party/rtcm3.c:1235:53: warning: variable 'rsv' set but not used [-Wunused-but-set-variable]
   int i = 24 + 12, prn, sat, week, e5a_hs, e5a_dvs, rsv, sys = SYS_GAL;
                                                     ^
modules/drivers/gnss/third_party/rtcm3.c: In function 'decode_msm_head':
modules/drivers/gnss/third_party/rtcm3.c:2188:18: warning: variable 'dow' set but not used [-Wunused-but-set-variable]
   int i = 24, j, dow, mask, staid, type, ncell = 0;
                  ^
INFO: From Compiling modules/drivers/gnss/third_party/novatel.c:
modules/drivers/gnss/third_party/novatel.c: In function 'decode_galephemerisb':
modules/drivers/gnss/third_party/novatel.c:1005:7: warning: variable 'rcv_inav' set but not used [-Wunused-but-set-variable]
   int rcv_inav = 0;
       ^
modules/drivers/gnss/third_party/novatel.c: In function 'decode_galalmanacb':
modules/drivers/gnss/third_party/novatel.c:1151:7: warning: variable 'ioda' set but not used [-Wunused-but-set-variable]
   int ioda = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1147:7: warning: variable 'rcv_inav' set but not used [-Wunused-but-set-variable]
   int rcv_inav = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1146:7: warning: variable 'rcv_fnav' set but not used [-Wunused-but-set-variable]
   int rcv_fnav = 0;
       ^
modules/drivers/gnss/third_party/novatel.c: In function 'decode_galclockb':
modules/drivers/gnss/third_party/novatel.c:1221:7: warning: variable 'wn0g' set but not used [-Wunused-but-set-variable]
   int wn0g = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1220:7: warning: variable 't0g' set but not used [-Wunused-but-set-variable]
   int t0g = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1219:7: warning: variable 'dtlsf' set but not used [-Wunused-but-set-variable]
   int dtlsf = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1218:7: warning: variable 'dn' set but not used [-Wunused-but-set-variable]
   int dn = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1217:7: warning: variable 'wnlsf' set but not used [-Wunused-but-set-variable]
   int wnlsf = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1214:7: warning: variable 'leaps' set but not used [-Wunused-but-set-variable]
   int leaps = 0;
       ^
modules/drivers/gnss/third_party/novatel.c:1212:10: warning: variable 'a1g' set but not used [-Wunused-but-set-variable]
   double a1g = 0.0;
          ^
modules/drivers/gnss/third_party/novatel.c:1211:10: warning: variable 'a0g' set but not used [-Wunused-but-set-variable]
   double a0g = 0.0;
          ^
modules/drivers/gnss/third_party/novatel.c: In function 'decode_galionob':
modules/drivers/gnss/third_party/novatel.c:1265:7: warning: variable 'sf' set but not used [-Wunused-but-set-variable]
   int sf[5];
       ^
modules/drivers/gnss/third_party/novatel.c: In function 'decode_galfnavrawpageb':
modules/drivers/gnss/third_party/novatel.c:1300:7: warning: variable 'sigch' set but not used [-Wunused-but-set-variable]
   int sigch = 0;
       ^
modules/drivers/gnss/third_party/novatel.c: In function 'decode_galinavrawwordb':
modules/drivers/gnss/third_party/novatel.c:1333:7: warning: variable 'sigch' set but not used [-Wunused-but-set-variable]
   int sigch = 0;
       ^
modules/drivers/gnss/third_party/novatel.c: In function 'decode_rawcnavframeb':
modules/drivers/gnss/third_party/novatel.c:1388:7: warning: variable 'sigch' set but not used [-Wunused-but-set-variable]
   int sigch = 0;
       ^
INFO: From Generating C++ proto_library //modules/planning/proto:planning_config_proto_lib:
modules/planning/proto/planning_config.proto: warning: Import modules/planning/proto/planner_open_space_config.proto but not used.
INFO: From Generating Descriptor Set proto_library //modules/planning/proto:planning_config_proto_lib:
modules/planning/proto/planning_config.proto: warning: Import modules/planning/proto/planner_open_space_config.proto but not used.
INFO: From Compiling modules/drivers/lidar_velodyne/pointcloud/rawdata.cc:
modules/drivers/lidar_velodyne/pointcloud/rawdata.cc: In member function 'void apollo::drivers::lidar_velodyne::RawData::unpack_vls128(const VelodynePacket&, apollo::drivers::lidar_velodyne::VPointCloud&)':
modules/drivers/lidar_velodyne/pointcloud/rawdata.cc:547:5: warning: typedef 'vls128_raw_packet_t' locally defined but not used [-Wunused-local-typedefs]
   } vls128_raw_packet_t;
     ^
ERROR: /apollo/modules/perception/obstacle/camera/common/BUILD:21:1: C++ compilation of rule '//modules/perception/obstacle/camera/common:util' failed (Exit 4).
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 579.052s, Critical Path: 118.90s
============================
[ERROR] Build failed!
[INFO] Took 598 seconds
============================
ins25k@in_dev_docker:/apollo$ docker ps
bash: docker: command not found

**Comment by natashadsouza** [comment]
Also, how much memory do you have available? We would recommend not building Apollo on a laptop due to the size of the build.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. Feel free to reopen if you are still facing any issues. Thanks!
