### ISSUE TITLE
Wrong intrinsic camera parameters loading error 

### ISSUE THREAD

**Issue by GPrathap** [ApolloAuto/apollo#6071]
**Describe the bug**
Let's say we have two camera subnodes where it is required to instantiate two separate camera submodules. But independent of the camera, intrinsic parameters of the front camera or defined camera parameters in here `(FLAGS_geometry_camera_converter_config)` are loaded in[ GeometryCameraConverter::Init() ](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/obstacle/camera/converter/geometry_camera_converter.cc#L30). 

Thus, I would suggest improving this by proving the **device id** ` GeometryCameraConverter::Init( device_is_of_camera)` and load the corresponding camera parameters.  

**To Reproduce**
Try adding more than one camera subnodes,

      `subnodes {
            id: 3
            name: "CameraProcessSubnode"
            reserve: "device_id:front_right_side_camera;pb_obj:1;pb_ln_msk_:0;"
            type: SUBNODE_IN
    }
    # Visualization node with OpenGL
    subnodes {
            id: 41
            name: "VisualizationSubnode"
            reserve: "vis_driven_event_id:1008;camera_event_id:1008;camera_device_id:front_right_side_camera"
    }
    # Camera node. publish pb with non-zero int
    subnodes {
            id: 4
            name: "CameraProcessSubnode"
            reserve: "device_id:front_left_side_camera;pb_obj:1;pb_ln_msk_:0;"
            type: SUBNODE_IN
    }`

**Expected behavior**
Each camera should have its own camera parameters 

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser chrome

**Comment by techoe** [comment]
I love your idea! In the current Apollo (3.5), we changed the sensor configuration to handle multiple sensors. We use sensor name as a unique ID. Thank you.

**Comment by GPrathap** [comment]
Yeap, we changed code based in 3.0. We are going to move to 3.5 soon while discarding all the changed has done for perception module :D . Thanks
