### ISSUE TITLE
rosbag play and perception exit and restart

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#6072]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source On apollo IPC)**:
- **Apollo version (3.0)**:

when I　run rosbag play apollo_2.0_camera_sample.bag , the perception module awlays  exit and restart, I can't find the reason, do you have some suggestion to give me ? thank you

**Comment by techoe** [comment]
I am closing it since there is no further question after last answer.
