### ISSUE TITLE
decision.proto - MainChangeLane deprecated ?

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#6075]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

I could see that the message ```MainChangeLane``` in decision.proto has been deprecated. Is there a need of ```change_lane_decider.cc``` as this code completely dependent on ```MainChangeLane``` message. 

Also is there any other way to monitor the change lane status of autonomous vehicle.

Thank you
KK

**Comment by BoChang11** [comment]
@natashadsouza Also kindly let me know if the below proto buffer message is being used anywhere.

```
message ChangeLaneStatus {
  enum Status {
    IN_CHANGE_LANE = 1; // during change lane state
    CHANGE_LANE_FAILED = 2; // change lane failed
    CHANGE_LANE_SUCCESS = 3; // change lane failed
  }
  optional Status status = 1;
  // the id of the route segment that the vehicle is driving on
  optional string path_id = 2;
  // the time stamp when the state started.
  optional double timestamp = 3;
}
```

I tried to extract the lane change status using the above proto buffer messages. However it was not successful. Also I tried to put breakpoint in ```change_lane_decider.cc``` code where this message is being used, unfortunately control doesnt event go inside that code.

Could you please help me understanding whether this message is being used to fetch the status of lane change. Also is there any other to get the details.

Thank you,
KK

**Comment by kk2491** [comment]
@natashadsouza Also kindly let me know if the below proto buffer message is being used anywhere.

```
message ChangeLaneStatus {
  enum Status {
    IN_CHANGE_LANE = 1; // during change lane state
    CHANGE_LANE_FAILED = 2; // change lane failed
    CHANGE_LANE_SUCCESS = 3; // change lane failed
  }
  optional Status status = 1;
  // the id of the route segment that the vehicle is driving on
  optional string path_id = 2;
  // the time stamp when the state started.
  optional double timestamp = 3;
}
```

I tried to extract the lane change status using the above proto buffer messages. However it was not successful. Also I tried to put breakpoint in ```change_lane_decider.cc``` code where this message is being used, unfortunately control doesnt event go inside that code.

Could you please help me understanding whether this message is being used to fetch the status of lane change. Also is there any other to get the details.

Thank you,
KK

**Comment by lianglia-apollo** [comment]
Change lane is supported through the combination effect from reference line provider, frame, reference line info, and a class called "ChangeLaneDecider". 
Please first verify that the routing has a lane change region, otherwise the lane change will not take effect.

**Comment by jmtao** [comment]
Hi @kk2491  hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
