### ISSUE TITLE
apollo3.0编译成功但是打不开localhost:8888

### ISSUE THREAD

**Issue by portguas** [ApolloAuto/apollo#6076]
**环境是Ubuntu14.04+apollo3.0. 前面的编译都成功。并且提示 dreamview已经启动.**
root@in_dev_docker:/apollo# sudo bash scripts/bootstrap.sh
Start roscore...
Launched module monitor.
Launched module dreamview.
Dreamview is running at http://localhost:8888
root@in_dev_docker:/apollo# ps aux | grep dreamview
root     29743  0.0  0.0   8880   868 pts/5    S+   14:45   0:00 grep --color=auto dreamview
**但是在浏览器打不开.查看apollo/data/log里面的monitor.ERROR.如下**
Log file created at: 2018/11/27 10:05:15
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1127 10:05:15.752868  6806 can_checker_factory.cc:48] Failed to create CAN checker with parameter: brand: ESD_CAN
type: PCI_CARD
channel_id: CHANNEL_ID_ZERO
E1127 10:05:45.841301  6806 can_checker_factory.cc:48] Failed to create CAN checker with parameter: brand: ESD_CAN
type: PCI_CARD
channel_id: CHANNEL_ID_ZERO
E1127 10:06:16.367076  6806 can_checker_factory.cc:48] Failed to create CAN checker with parameter: brand: ESD_CAN
type: PCI_CARD
channel_id: CHANNEL_ID_ZERO
E1127 10:06:46.976133  6806 can_checker_factory.cc:48] Failed to create CAN checker with parameter: brand: ESD_CAN
type: PCI_CARD
channel_id: CHANNEL_ID_ZERO
E1127 10:07:17.101784  6806 can_checker_factory.cc:48] Failed to create CAN checker with parameter: brand: ESD_CAN
type: PCI_CARD
channel_id: CHANNEL_ID_ZERO
**尝试使用https://github.com/ApolloAuto/apollo/issues/3615里面的编译pcl的方法，不行.在cmake ..这一步就出现好多库找不到.很多. 请问该如何修改。谢谢**

**Comment by natashadsouza** [comment]
@portguas refer to [Dreamview FAQs](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md) document. Thanks!

**Comment by portguas** [comment]
@natashadsouza  Yes, i do exactly as the FAQs docnment says. But it doesn't work.

**Comment by zezhou** [comment]
Can you paste your dreamview log here? The log is in /apollo/data/log/dreamview.INFO

**Comment by luannan** [comment]
@portguas  Do you have the CAN card driver? 
https://github.com/ApolloAuto/apollo/tree/master/third_party/can_card_library/esd_can

**Comment by Orientlee** [comment]
Have you fixed this problem?  I have the same problem with you .......Need help.... @portguas

**Comment by natashadsouza** [comment]
@Zhenyu-Li give us additional details regarding your version and also any error messages you see in your Dreamview log. Thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
