### ISSUE TITLE
- Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.

### ISSUE THREAD

**Issue by zhangw0128** [ApolloAuto/apollo#6078]
Hello-

I am trying to run “bin/prepare-refseqs.pl --fasta yourgenome.fasta --out /opt/apollo/data” to add a new organism to the panel，but the organism isn't loaded up the webapollo. and the trackList.json is right.
Thanks,

Best,

zhangw
 p.s. here is the JSON file if that tells you anything:
{
   "formatVersion" : 1,
   "tracks" : [
      {
         "category" : "Reference sequence",
         "chunkSize" : 20000,
         "key" : "Reference sequence",
         "label" : "DNA",
         "seqType" : "dna",
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "type" : "SequenceTrack",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-"
      },
      {
         "compress" : 0,
         "key" : "tRNA",
         "label" : "tRNA",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : null,
         "type" : "FeatureTrack",
         "urlTemplate" : "tracks/tRNA/{refseq}/trackData.json"
      }
   ]
}

**Comment by mickeyouyou** [comment]
Hey friend, you must be the wrong place. I guess you should pull a issue on here https://github.com/GMOD/Apollo.
