### ISSUE TITLE
Building apollo with llvm 

### ISSUE THREAD

**Issue by jiwonjoung** [ApolloAuto/apollo#6081]
Has anyone tried to build apollo with wllvm? I am  interested in  generating the LLVM bitcode for all the files in the apollo source tree and  am running into  several errors.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by E00N777** [comment]
Hi there, I've also recently been trying to compile apollo using llvm and came up with llvm bitcde and I'm having some difficulties. Apollo uses the bazel tool, but I don't know how to change the compiler settings of bazel. Have you done this? I need your help

**Comment by lilejin322** [comment]
@YuqiHuai Any suggestions? I've also encountered the problem regarding using wllvm: https://github.com/travitch/whole-program-llvm to be assigned as bazel --crosstool_top=tools/wllvm:toolchain in this instruction: https://github.com/h1994st/ApolloLLVMCompile
