### ISSUE TITLE
It's required to set static transformation 

### ISSUE THREAD

**Issue by GPrathap** [ApolloAuto/apollo#6082]
**Describe the bug**
When setting the camera transformation with respect to the world or static transformation with respect to the car, here (https://github.com/ApolloAuto/apollo/blob/master/modules/perception/obstacle/onboard/camera_process_subnode.cc#L277) it was assigned the wrong transformation matrix because this transformation is used in visualization_subnode.cc as well. 

**To Reproduce**
I guess, this ` (*sensor_objects)->sensor2world_pose_static = *(options.camera_trans);` is needed to be changed into this:` (*sensor_objects)->sensor2world_pose_static = camera_to_car_;`
`

**Expected behavior**
If we do so, when we visulize the the camera it shows intiall pose and how it change when it moves.

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser chrome

**Comment by GPrathap** [comment]
Any update in this?

**Comment by techoe** [comment]
Thank you for the report! The current Apollo does not have such code any more.
