### ISSUE TITLE
Clean Up Build System

### ISSUE THREAD

**Issue by MicahChambers** [ApolloAuto/apollo#6085]
Is there any ongoing effort to clean up the build system? Its kind of confusing.

- there should be no reason to generate the WORKSPACE file, bazel is essentially python
- any user should be able to easily recreate the images used for `docker/scripts/dev_start.sh` with the dockerfile in `docker/build/` but could not get it to work without modification
- `apollo.sh` is overloaded, a more traditional interface would be a Makefile that calls scripts. e.g. `make gpu_opt` `make lint` etc
- `docker/dev_start.sh` should be split between local and non-local
- Also the cleanest way to orchestrate several docker containers is with docker-compose, have you guys considered using that?

I am happy to make PRs for some of these if there is interest on your end.

**Comment by natashadsouza** [comment]
@MicahChambers thank you for sharing your feedback. You are right about the Build CleanUp and we are working actively towards making it happen. I would encourage you to make PRs on your end too as we definitely rely on developer contribution to take our technology forward. 
Please make all the PRs to [Apollo 3.0 dev branch](https://github.com/ApolloAuto/apollo/tree/v3.1_dev). 
Let us know if you have any additional questions. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue currently. @MicahChambers you are always encouraged to make pull requests. We thank you for working on Apollo!

**Comment by marcusvinicius178** [comment]
Hi @natashadsouza  **which command can I run in docker to clean the built images?** And restart compiling the pkgs? I was used with:
` ROS1: catkin_make_clean `
and with Autoware.Auto : 
`rm -rf build/ install/ log/ src/external/`
For Apollo 6.0:

`????`
Besides that I would like usage tutorials from Apollo. Where Could I find? I am facing issues to switch path planners and compile the planning pkg without errors, due lack of instructions...
https://github.com/ApolloAuto/apollo/issues/13763

Pleaselet me know how to properly change **the planning_config.proto** code to trigger the planners (RTK, Road Public, Nav and Lattice) one by one without generate errors. ****

Thanks in advance!
