### ISSUE TITLE
Is code build required every time I log in to docker?

### ISSUE THREAD

**Issue by palejiya** [ApolloAuto/apollo#6086]
So Every time I want to use Dreamview, it seems It requires code build. Even though there is no change in the source code, why build process is required just to run Dreamview?

For example, After building the code, when I exit the docker and the re-enter and try  

> bash bootstrap.sh

I see following
> 
> Start roscore...
> Could not launch module monitor. Is it already built?
> Could not launch module dreamview. Is it already built?
> 

Is there a way to skip unnecessary build process every time I want to just already build code?

**Comment by xinwf** [comment]
After you have done a great change in docker, you can commit this docker with the same name or another new name, when you login into the docker with this name or the new name next time, you don't need to build again if you haven't changed your code or launch file.

**Comment by GPrathap** [comment]
when you start your docker container start with `bash docker/script/dev_start.sh -l `. It will not start a new container but run already built the container. Hope this will help. Also if you do changes in docker container push them to the docker hub. Then all the other things will be preserved.

**Comment by palejiya** [comment]
@GPrathap 

Thank you. What I am wondering is that I after I build the code, I want to save it as a local container that I can start anytime without login into docker. 
So how can I save the build code into local container and reuse it again and again?

Thanks

**Comment by GPrathap** [comment]
`bash docker/script/dev_start.sh -l`  this will not pull from the docker hub. It uses the local image. But every time when you want to build or run you have to log in to the local container. There is no way without login into the container. Don't try to install into your PC. it may take a lot of time get it ready. So use `bash docker/script/dev_start.sh -l` and then `bash docker/script/dev_into.sh -l` and have fun :)

**Comment by palejiya** [comment]
@GPrathap , Thank you for all help. 

So after starting docker with dev_start.sh and then entering it with dev_into.sh,  I build the code.
 I created a release images. I can see them with command "docker images".  

But when I exit the docker and then run 
bash scripts/bootstrap.sh -l
and
bash docker/script/dev_into.sh -l

I cannot run launch Dreamview with bootstrap.sh file. I get following error  (in the screenshot)

![screenshot from 2018-12-22 20-09-42](https://user-images.githubusercontent.com/22257121/50379902-9da67800-0625-11e9-8b0b-ab0a2f7e9a32.png)


I am not sure what I am missing here. Please help.  Thanks

**Comment by xinwf** [comment]
Have a look in this [issue](https://github.com/ApolloAuto/apollo/issues/6087) about permission problem.

**Comment by GPrathap** [comment]
@palejiya according to the error, you don't have permission for file writing data/log directory, please check the permission on this directory and give write access

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
