### ISSUE TITLE
apollo搭建问题

### ISSUE THREAD

**Issue by seniorstudent** [ApolloAuto/apollo#6087]
### System information

- Linux Ubuntu 16.04:
- **Apollo version (master):

### Issue:
新手有如下问题请组织支援：
1. 在apollo搭建过程中，代码编译完成后启动dreamview的时候出现如下Permission denied，是我用户权限的问题吗？
============================
[ OK ] Build passed!
[INFO] Took 2868 seconds
============================
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
Start roscore...
scripts/bootstrap.sh: line 38: ./scripts/monitor.sh: Permission denied
scripts/bootstrap.sh: line 39: ./scripts/dreamview.sh: Permission denied

2. 每次进入dreamview都必须先编译代码吗？
如果我关掉了dreamview，后面要重新进入的话，需要再编译一次代码吗？ 这个编译的耗时还是蛮长的。

期待回复！

**Comment by seniorstudent** [comment]
问题1 已自己解决。
通过命令 chomd a+x

**Comment by HongweiSunny** [comment]
我之前也是每次重新进入都要编译，期待解决方案

**Comment by xinwf** [comment]
不需要每次都重新编译，但需要一些操作
1，第一次下载完所有docker文件并按照教程进入docker内部编译后，用docker commit命令提交一个本地的docker，下次进入的时候使用 -l -t  commited_docker_name 参数即可加载上次已经发生改动的docker而不需要重新编译。
此后的操作分为三种：
2，如果你改动了代码，需要重新编译，毫无疑问
3，如果你只是改动了launch文件，你可以拷贝该launch文件到对应的位置(这个是在docker内部完成的)而不需要重新编译，如果你不知道要把launch文件拷贝到哪，那就编译吧，编译的时候会重新拷贝launch文件。
4，如果你只是改动了配置文件，通常是不需要重新编译的，如果是涉及车辆或者地图的参数，切换一下车辆或者地图应该就能使其生效。

如果你在docker内部做了较大修改，比如修改了环境变量或者加入了新的文件或者安装了新的软件，你应该在最后停止所有的模块提交一次docker，这样你的修改才会保存下来，一般我会使用同一个name，要不然docker占用的空间实在太大了。在提交docker时顺便多说一句，如果/home/ubuntu/.ros/log/目录下的日志很大，删除后再提交。

另外说一下权限问题，在docker内部，强烈推荐使用普通用户，如果以前用了sudo或者root用户怎么办？切换到root用户，停止所有模块，删除/tmp目录和/home/ubuntu/.ros/log/下的所有文件，退出，提交docker，重新进入docker以后即可使用普通用户。

**Comment by ZhouHaining** [comment]
非常感谢，学习了！

**Comment by seniorstudent** [comment]
非常感谢，学习了！
