### ISSUE TITLE
IsNewRouting queries

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#6088]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Issue

I am trying to use the below function ```IsNewRouting``` function in ```planning module``` to determine one of the behavior of the autonomous vehicle.

For example : Counter needs to be reset when new routing has been given to the autonomous vehicle. 

However I am not able to get this working as expected. Could you please let me know if the below code snippet is working one.  

This is from ```planning.cc``` in ```Planning::ResetPullOver```
```
  if (hdmap::PncMap::IsNewRouting(last_routing_, response)) {
    pull_over->Clear();
    last_routing_ = response;
    AINFO << "Cleared Pull Over Status after received new routing";
  }
```

Thank you,
KK

**Comment by lianglia-apollo** [comment]
The code looks fine. If it doesn't work, please try to printout the msg of last_routing_ and response to see if there is a difference.

**Comment by jmtao** [comment]
Hi @kk2491 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
