### ISSUE TITLE
timestamp of lidar is not in the proper format

### ISSUE THREAD

**Issue by GPrathap** [ApolloAuto/apollo#6089]
**Describe the bug**

`E1203 21:01:33.305027 22823 transform_input.cc:69] Cannot transform frame: odom to frame base_link , err: Lookup would require extrapolation into the past.  Requested time 1868.406659000 but the earliest data is at time 1542186556.976089512, when looking up transform from frame [base_link] to frame [odom]. canTransform returned after 0.903852 timeout was 0.9.. Frames: Frame base_link exists with parent
`
Referring to the above error, it happens when it tries to retrieve transformation (: localization to frame velodyne16 ) inside the **lidar subnode**. Here, localization to frame velodyne16 are the

Problem is when I check the time stamps camera_process_subnode and lidar_process_subnode will give two different timestamps in the incoming ros messages. 
Usually in the camera_process_subnode.cc timestamp something similar to this: 1.54219e+18, but in the lidar_process_bubnode it gives something like 1869.42. 

A header of lidar message
```
---
seq: 0
stamp: 
  secs: 1837
  nsecs: 137829000
frame_id: velodyne16
---

```
A header of camera message
```
---
seq: 0
stamp: 
  secs: 1542186673
  nsecs: 177726065
frame_id: pylon_camera
---
```

That is why it's not able to retrieve transformation from tf. I guess the problem in the lidar driver where ros time is being sat. I guess something is wrong here (https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/velodyne/velodyne_pointcloud/src/lib/velodyne16_parser.cpp#L31). 

Still, I can't find out why this is happening? If you say something useful it will be really appreciated. 

But I did get this warning: **/use_sim_time is not set, will not subscribe to simulated time [/clock] topic**

**To Reproduce**
Explained in detail above.

**Expected behavior**
Explained in detail above.

**Desktop (please complete the following information):**
 - OS: Linux 16
 - Browser Chrome
 - Version 3.0
.

**Comment by GPrathap** [comment]
I was able to resolve the issue setting the incoming timestamp into an outgoing message in here (https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/velodyne/velodyne_pointcloud/src/lib/velodyne16_parser.cpp#L37) 

#include <pcl_conversions/pcl_conversions.h>
...
pcl_conversions::toPCL(scan_msg->header.stamp, out_msg->header.stamp);

I want to say that we dont have gps seosor because of that gps time can be utilized in our case. So this would be the only way to get resolved the issue. If I am missing something correct me. If not you may close this issue. 

Thank you!.

**Comment by GPrathap** [comment]
Any update in this?

**Comment by 1184** [comment]
Hi,I'm sorry to disturb you.I think I met the same problem with you.
How did you let the exchange the time? 
My error just like the picture show:
![5](https://user-images.githubusercontent.com/37065656/56481969-4097d180-64f4-11e9-9f2a-90a2f8d195ea.png)
thank your time.

**Comment by GPrathap** [comment]
I guess this warning is due to tf_buffer timeout limit. First, try increasing the timeout limit. It uses, [canTransform ](http://docs.ros.org/indigo/api/tf2_ros/html/c++/classtf2__ros_1_1Buffer.html) , If you still get the error to let's post it here again.

**Comment by 1184** [comment]
I don't know how to change the value of timeout. Finally,I reinstalled my ros and my siulation.

**Comment by GPrathap** [comment]
Can you say what is the version you are using and which subnode you are getting this error?

**Comment by warden2018** [comment]
@1184  the value of timeout can be changed here:
`modules/drivers/velodyne/velodyne/launch/start_velodyne_16.launch`
`<arg name="tf_query_timeout" default="0.1"/>`
If you use velodyne 16. The compensator will use the param.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
