### ISSUE TITLE
Apollo planning  TrafficDecider question

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#6090]
Dear apollo developer,
apollo code version:3.0
about module : planning
I don't understand in BuildPlanningTarget function, why include obstacle->obstacle()->IsVirtual() judegement,if the obstacle is not virtual so will always false ,how to calculation the min_s?
code:
void TrafficDecider::BuildPlanningTarget(
    ReferenceLineInfo *reference_line_info) {
  double min_s = std::numeric_limits<double>::infinity();
  // std::cout << "min_s"<< min_s<<std::endl; 
  StopPoint stop_point;
  for (const auto *obstacle :
       reference_line_info->path_decision()->path_obstacles().Items()) {
    if (obstacle->obstacle()->IsVirtual() &&
        obstacle->HasLongitudinalDecision() &&
        obstacle->LongitudinalDecision().has_stop() &&
        obstacle->PerceptionSLBoundary().start_s() < min_s) {
      AINFO << "BuildPlanningTarget enter";
      min_s = obstacle->PerceptionSLBoundary().start_s();
      const auto &stop_code =
          obstacle->LongitudinalDecision().stop().reason_code();
      if (stop_code == StopReasonCode::STOP_REASON_DESTINATION ||
          stop_code == StopReasonCode::STOP_REASON_CROSSWALK ||
          stop_code == StopReasonCode::STOP_REASON_STOP_SIGN ||
          stop_code == StopReasonCode::STOP_REASON_YIELD_SIGN ||
          stop_code == StopReasonCode::STOP_REASON_CREEPER ||
          stop_code == StopReasonCode::STOP_REASON_REFERENCE_END ||
          stop_code == StopReasonCode::STOP_REASON_SIGNAL) {
        stop_point.set_type(StopPoint::HARD);
        ADEBUG << "Hard stop at: " << min_s
               << "REASON: " << StopReasonCode_Name(stop_code);
      } else if (stop_code == StopReasonCode::STOP_REASON_YELLOW_SIGNAL) {
        stop_point.set_type(StopPoint::SOFT);
        ADEBUG << "Soft stop at: " << min_s << "  STOP_REASON_YELLOW_SIGNAL";
      } else {
        ADEBUG << "No planning target found at reference line.";
      }
    }
  }

**Comment by lianglia-apollo** [comment]
If the obstacle is not virtual, its SL boundary will be calculated when we initialize frame.
