### ISSUE TITLE
Running offine demo on Xavier 

### ISSUE THREAD

**Issue by manishshakya** [ApolloAuto/apollo#6091]
Hi All,

I am trying to run offine demo  on  Nvidia Xavier Dev kit. It is running Ubuntu 18.04.

I have installed docker using  following command.
sudo docker/setup_host/install_nvidia_docker.sh

When I do dev_start.sh, I see following error

sudo  bash docker/scripts/dev_start.sh
Status: Downloaded newer image for apolloauto/apollo:yolo3d_volume-aarch64-latest
5afedb5ba779660bbd8f737b89a02dbb9b6b11e4f61b21e0fbb806b2e5507b0a
[INFO] Starting docker container "apollo_dev" ...
docker: Error response from daemon: No such container: apollo_map_volume-sunnyvale_big_loop.
See 'docker run --help'.
[ERROR] Failed to start docker container "apollo_dev" based on image: apolloauto/apollo:dev-aarch64-20170927_1111

It seems aarch64 image has not been updated for long time. Is there a way to run aarch64 demo image. Am I doing something wrong. Any input would be appreciated.

**Comment by natashadsouza** [comment]
@manishshakya please refer to #4636 and let me know if you have any additional questions. You will also need to install this additional library. Please refer this [document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md)

**Comment by manishshakya** [comment]
So, I tried patches from @muleisheng  for TX2.  I got pass the previous error but got into following error.
root@in_dev_docker:/apollo# bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Could not find javac
============================
[ERROR] Build failed!
[INFO] Took 0 seconds
============================
root@in_dev_docker:/apollo#

**Comment by manishshakya** [comment]
I tried patches from @muleisheng  for TX2.  I got pass of previous error but got into following error.
root@in_dev_docker:/apollo# bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
Could not find javac
============================
[ERROR] Build failed!
[INFO] Took 0 seconds
============================
root@in_dev_docker:/apollo#

**Comment by gouchaoer** [comment]
do you have any progress?
I am also trying to run apollo on xavier

**Comment by aboarya** [comment]
@manishshakya Any luck getting it to work on Xavier?

**Comment by kolamanlee** [comment]
> I tried patches from @muleisheng for TX2. I got pass of previous error but got into following error.
> 
> > root@in_dev_docker:/apollo#
> > bash apollo.sh build
> > System check passed. Build continue ...
> > [WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
> > Running build under GPU mode. GPU is required to run the build.
> > [INFO] Start building, please wait ...
> > INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
> > Could not find javac
> > ============================
> > [ERROR] Build failed!
> > [INFO] Took 0 seconds
> > ============================
> > root@in_dev_docker:/apollo#
> 
> >

I have this issue also, how to solve it?

**Comment by storypku** [comment]
Tag this question to revisit later on my Xavier later.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
