### ISSUE TITLE
Can't download dataset from http://data.apollo.auto (no SMS received)

### ISSUE THREAD

**Issue by frontw** [ApolloAuto/apollo#6092]
Hi! 
I'm trying to download MSF dataset, but here is SMS confirmation window on data.apollo.auto and I didn't receive any SMS, tried 2 phone numbers. I'm from Russia (+7). 
Is it possible to use another authorization method?
Thanks!

**Comment by Zhenni17** [comment]
Hi @frontw , we are aware there are some bug when non-Chinese number trying to login the system and download the data. We will communicate the bug with our engineers and have it fixed soon. Please be patient with us.

**Comment by frontw** [comment]
Any other option to download data?

**Comment by natashadsouza** [comment]
@frontw you would need either a United states or China phone number. Sorry about that! we are still working with our team to have it resolved. Thank you for your patience.

**Comment by natashadsouza** [comment]
Closing this issue. If you have additional questions feel free to reopen it. Thanks!
