### ISSUE TITLE
Apollo的深度学习是并行的么？

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6094]
我看到lidar那里用到了caffe的深度学习网络，还有camera的交通灯检测+识别，还有camera的车道线检测+障碍物检测，这么多的地方用到了深度学习。假如caffe里配置是gpu模式，那么某一个时刻这个地方占用了GPU，那另一个地方是不是就卡在那里只有等GPU空闲出来了才能上呢？

**Comment by zk5580752** [comment]
可以通过GPU配置，分配合适的计算资源，不让一个模型占用全部的GPU，这样就可以同时运算了。
