### ISSUE TITLE
How to add my algorithm into the apollo project ?

### ISSUE THREAD

**Issue by pancumtneu** [ApolloAuto/apollo#6096]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by natashadsouza** [comment]
@pancumtneu we have documents available on how to add your own algorithm, how to compile using VS Code and how to run your project using Dreamview.  As for whether it would break the code, you would have to test it as we do not have any information on your code.
Please let me know if you have any additional questions post reading the documents. Thanks!

**Comment by pancumtneu** [comment]
> @pancumtneu we have documents available on how to add your own algorithm, how to compile using VS Code and how to run your project using Dreamview. As for whether it would break the code, you would have to test it as we do not have any information on your code.
> Please let me know if you have any additional questions post reading the documents. Thanks!

Is there any demos or tutorials about how to control a car compiled by VisualCode .The document didn't have the detail procedure .Thx

**Comment by natashadsouza** [comment]
@pancumtneu you could refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_using_vscode.md). Let me know if this answers your question.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
