### ISSUE TITLE
Data to test perception module

### ISSUE THREAD

**Issue by pfrcks** [ApolloAuto/apollo#6098]
Hi,

I understand that we are supposed to download data for apollo open data but I am unsure as to what data do I need to download to test the perception module. Can anyone help with this?

**Comment by xinwf** [comment]
demo_2.5.bag is ok, but you need to do some work, and steps are in the following:
1, make sure you have installed the nvidia driver successfully with the document with title like `how_to_run_perception_module_on_your_local_computer` in `docs/how_to` directory
2, you need to filter the obstacle topic from demo_2.5.bag with such command `rosbag filter src.bag dst.bag "topic !='/apollo/perception/obstacles'"`
3, start docker, build the code with param 'build_opt_gpu'
4, start dreamview with bootstrap.sh
5, start the perception mode in terminal with the script `perception_lowcost_vis.sh`
6, rosbag play dst.bag
then it will pop up a window, if it doesn't appear any errors, now, everything is ok, perception module works well.
