### ISSUE TITLE
routing not ready; skip the planning cycle

### ISSUE THREAD

**Issue by pfrcks** [ApolloAuto/apollo#6100]
Hi,

I have successfully built the offline gpu version of the stack. While trying the modules on one of the data files downloaded from Apollo Open Data I am unable to get Planning, Routing and Control to work.

All of them are interdependent. Planning logs have the error 
`E1210 15:12:26.720872  9669 reference_line_provider.cc:184] Routing is not ready.
4542 E1210 15:12:26.770990  9669 reference_line_provider.cc:184] Routing is not ready.`

and subsequently control logs have the error 
`E1210 15:11:24.003744  9501 control.cc:233] Failed to produce control command:planning has no trajectory point.`

Any idea what might be going wrong?

**Comment by zezhou** [comment]
It looks like routing module is not OK. Do you  select route manually? You can see [7.Under Default Routing select your desired route.](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_3_0_quick_start.md) to check if it right. And, what's the command you start all these modules?

**Comment by kk2491** [comment]
@pfrcks If you are selecting the route manually it doesn't correspond to any Demo bag. It is independent of bag file.
