### ISSUE TITLE
Control speed of the autonomous car in Planning module

### ISSUE THREAD

**Issue by BoChang11** [ApolloAuto/apollo#6101]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

Hi,

I am trying to control the speed of the autonomous vehicle from **Planning module**. Is there a way to do it?

Example : Consider autonomous car is going at a speed of 15 m/s and I need to reach Point A at 5 m/s.
Is there a way I could control the speed from planning module. 

I have gone through the FLAGS in **planning_gflags.cc**, but could not find the relevant FLAG which would do the needful. 

BR

**Comment by iradionov** [comment]
You can tune it in 
/apollo/modules/planning/conf/planning.conf

--planning_upper_speed_limit
--default_cruise_speed

**Comment by JJRedmond** [comment]
You can tune it in
/apollo/modules/planning/conf/planning.conf

--planning_upper_speed_limit
--default_cruise_speed

**Comment by lianglia-apollo** [comment]
There is no simple ways to do it by tuning parameters. For this new requirement , the user will need to implement a planner with the new algorithm.
