### ISSUE TITLE
what's the meanning of --no-opengl--files when install nvidia driver?

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6102]
I successfully installed nvidia driver last month. 
But yesterday my PC had a electricity failure.
Then I can't login the GUI anymore. It just loop after input the password.
I uninstall driver and reinstall it just like I did last month, but failed.
Then I search a answer that install the driver with '--no-opengl--files' parameter.
It succeed, i use nvidia-smi to check the cuda is OK. But the desktop GUI have a very low resolution.

I want to know why.

**Comment by natashadsouza** [comment]
@gouchaoer are you still seeing this issue? I am sorry for the delay in responding to your request.
