### ISSUE TITLE
Error while running MSF Localization

### ISSUE THREAD

**Issue by pfrcks** [ApolloAuto/apollo#6103]
Hi,

I am on Apollo 3.0 and I followed the guide mentioned at https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md to run MSF locatization.

I downloaded the data from Apollo Open Data and followed the necessary steps. However I am getting the following error

`Waiting 0.2 seconds after advertising topics.../apollo/apollo-platform/ros/ros_comm/roscpp/src/libros/publication.cpp:629 Publication::validateHeader() [ERROR] [1544541017.517321895]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
 done.
`

From past similar issues I thought this error was due to running MSF loc on demo bags because they were recorded with older versions of Apollo.

Any advice?

**Comment by pfrcks** [comment]
Figured it out. You need to remove `corrected_imu` topic from the all the bags.

`rosbag filter bag_name new_bag_name "'corrected_imu' not in topic"

**Comment by flnlucifer** [comment]
> Figured it out. You need to remove `corrected_imu` topic from the all the bags.
> 
> `rosbag filter bag_name new_bag_name "'corrected_imu' not in topic"`
@pfrcks 
Hi, could you please help to check #7077 ? I faced the same problem. thx
