### ISSUE TITLE
[Target path is not writable] issue in file.cc

### ISSUE THREAD

**Issue by nulungzi2001** [ApolloAuto/apollo#6104]
after choosing a vehicle (e.g., mkz_example) in dreamview, I found that some files in modules/calibration/data/mkz_example are copied to destinations defined in 'vehicle_data.pb.txt'.

But, it seems that it fails to copy files to some specific folders such as /home/tmp/ros/share/velodyne/....

can you check this issue?

the followings are error messages I got when run dreamview.
E1211 13:58:57.014475  9172 file.cc:117] Target path is not writable: /home/tmp/ros/share/velodyne_pointcloud/params/velodyne64_height.yaml
E1211 13:58:57.014536  9172 file.cc:117] Target path is not writable: /home/tmp/ros/share/velodyne_pointcloud/params/64E_S3_calibration_example.yaml
E1211 13:58:57.014585  9172 file.cc:117] Target path is not writable: /home/tmp/ros/share/velodyne_pointcloud/params/velodyne64_novatel_extrinsics_example.yaml
E1211 13:58:57.015326  9172 file.cc:117] Target path is not writable: /home/tmp/ros/share/usb_cam/launch/start_leopard.launch
E1211 13:58:57.015368  9172 file.cc:117] Target path is not writable: /home/tmp/ros/share/usb_cam/launch/start_obstacle_camera.launch
nohup: appending output to 'nohup.out'

**Comment by ycool** [comment]
Please try it again in the latest code and feel free to reopen this issue if it happens again. Thanks.
