### ISSUE TITLE
apollo docker ROS通信问题

### ISSUE THREAD

**Issue by GR-Li** [ApolloAuto/apollo#6107]
apollo docker 如何与宿主机ubuntu t通信？如在apollo自定义一个ros msg类型的std_msgs::Uint8的topic,发布，宿主机Ubuntu接收到该话题的消息，相反，宿主机ubuntu自定一个ros msg类型.,apollo订阅该话题，如何接收到宿主机传来的消息?有好的解决方法吗？

**Comment by storypku** [comment]
Stale issue closed.
