### ISSUE TITLE
Apollo3.0的深度学习总算力是多少？

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6108]
看了一下tesla的硬件平台以及eyeq5的平台，INT8的深度学习算力都几十TOPS，而FP32的深度学习算力相对就差一点了，不知道有谁知道Apollo3.0的深度学习算力是多少？nvidia的TX2啊Xavier啊Pegasus之类的平台哪个能hold住Apollo

**Comment by gouchaoer** [comment]
tesla在PX2上没有用双GPU的chauffeur版本，具体见：
https://en.wikipedia.org/wiki/Drive_PX-series#Drive_PX_2，后来tesla又double了cpu核心数量，这是不是说明目前来说深度学习的GPU算力是足够的，而cpu需要的算力其实不够。。。现在官方的工控机cpu和1080ti的显卡肯定是绰绰有余，但是工控机+1080显卡只能说测试开发算法用比较好，实际场景还是需要嵌入式的SoC的吧？

**Comment by daohu527** [comment]
@gouchaoer 不知道你讨论的是硬件还是软件，还是软件需要的算力，目前已经更新到7.0版本了，因此3.0版本的相关问题可能不再维护
