### ISSUE TITLE
Least painful way to setup and build apollo locally with gpu support [Guide]

### ISSUE THREAD

**Issue by pfrcks** [ApolloAuto/apollo#6110]
I'm not sure whether this is documented somewhere but there is a very painless way to setup the apollo stack locally with gpu support.

**Note**: This assumes that you already have nvidia drivers + cuda installed on your system. I have not tested it in a system which has no nvidia drivers/cuda. 

1. install docker
2. install nvidia-docker
3. clone repo
4. change `./docker/scripts/dev_start.sh` adding
`-v /usr/src:/usr/src \
-v /lib/modules:/lib/modules \` in command `docker run -it`
5. `./docker/scripts/dev_start.sh` followed by `docker exec -it apollo_dev /bin/bash`
6. `bash apollo.sh build_gpu --local_resources 2048,1.0,1.0` (makes it less cpu intensive while building)

That's it. You don't need to mess around or install nvidia drivers/cuda inside the docker. This allows it to work even in Ubuntu 16.04/18.04

**Comment by natashadsouza** [comment]
@pfrcks apologies for the delay in responding. You could create a regular .md file and submit it under docs > how to > "how_to_build_locally_with_gpu_support.md"
Thank you so much for contributing!
Let me know if you have any questions.

**Comment by natashadsouza** [comment]
Closing this issue currently. @pfrcks awaiting your pull request on this issue. Thanks!
