### ISSUE TITLE
Sample data set

### ISSUE THREAD

**Issue by mahmoodn** [ApolloAuto/apollo#6123]
I am interested in ApolloAuto. Problem is that I want to simulate a test data set on my computer for some GPU purposes. So, I am not going to install any physical device on the car. Is there any sample data for testing and simulation goals? I didn't find clear answer by browsing the folders. Maybe I missed something.

Any help?

**Comment by natashadsouza** [comment]
@mahmoodn we have some sample data on our [website](http://data.apollo.auto/?locale=en-us&lang=en) but you need to be in the United States to be able to access it. Sorry for the delay in responding to your request. Thanks!
