### ISSUE TITLE
I submitted the request for map specification by survey link and asked @msbeta @Zhenni17 @natashadsouza for attachment many times. No response. So open new issue Here. jmloveyj@sina.cn

### ISSUE THREAD

**Issue by jmloveyj** [ApolloAuto/apollo#6162]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by natashadsouza** [comment]
@jmloveyj the team is extremely busy with our launch. We understand there might be a backlog on responding on the survey link. We apologize and request your patience on the same. The team should get back to you soon. Currently closing this issue. Thanks!
