### ISSUE TITLE
File missing in release docker 3.0.0 

### ISSUE THREAD

**Issue by Smlight** [ApolloAuto/apollo#6166]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: Just docker
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- I just follow the steps in [demo_guide](https://github.com/ApolloAuto/apollo/tree/r3.0.0/docs/demo_guide) to run an offline demo with the very version **release 3.0.0**. 

1. Start the docker release environment using the command:
    ```
    bash docker/scripts/release_start.sh
    ```
    *I typed 'y' because I am a chinese user.*

2. Enter the docker release environment:

    ```
    bash docker/scripts/release_into.sh
    ```

3. Now you can play the rosbag:

    ```
    sudo python docs/demo_guide/rosbag_helper.py demo_2.0.bag #download rosbag
    rosbag play demo_2.0.bag --loop
    ```

    When I executed the first command in this step, what I saw is as followed: 

    `python: can't open file 'docs/demo_guide/rosbag_helper.py': [Errno 2] No such file or directory
    `

### Supporting materials (screenshots, command lines, code/script snippets):
![screenshot](https://user-images.githubusercontent.com/3436211/50076127-bffe5700-021b-11e9-9bc6-f58368c2aa60.png)

I know I can use the bash script to download rosbags, but it would be better if you fix your docker image!

**Comment by natashadsouza** [comment]
@Smlight we changed the build process: please refer to [this document](https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide) as we chose to do away with the release container.
Let me know if you have any questions.
Thanks!

**Comment by Smlight** [comment]
@natashadsouza Thank you, it works now!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved!
