### ISSUE TITLE
[Offline Demo] Dreamview always showing "Please send car initial position and map data" even with rosbag play in background

### ISSUE THREAD

**Issue by zwang92** [ApolloAuto/apollo#6187]
### Host System information

- **OS Platform and Distribution**:
Ubuntu~16.04.4
- **Apollo installed from (source or binary)**:
git clone https://github.com/ApolloAuto/apollo.git
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
git clone https://github.com/ApolloAuto/apollo.git

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
1. follow "Run Offline Demo" steps in https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide
2. i have successfully done  "Setup steps 1 ~ 4 in Run Offline Demo"
    PS: For Step1 and Step2, it needs sudo to use docker as following: is there problem here ?
               sudo bash docker/scripts/dev_start.sh
               sudo bash docker/scripts/dev_into.sh
3. For Step5 "Now you can play the rosbag:" ,  i need to "source /home/tmp/ros/setup.bash" in order to have rosbag work, then run the command "rosbag play demo_2.0.bag --loop" to enable rosbag to keep playing the bag in a loop playback mode as following picture
![image](https://user-images.githubusercontent.com/6805661/50155469-17c5bc80-0307-11e9-978f-eef618e2ad84.png)
    PS: it is found apollo docker ubuntu version is 16.04 and ROS version is indigo, is there compatibility issue here (ROS indigo only support ubuntu 14.04)  ?
![image](https://user-images.githubusercontent.com/6805661/50195377-be4aa580-0379-11e9-8f48-31953a5a3439.png)

4. The issue is that the chrome open "localhost:8888" and always show "Please send car initial position and map data" even rosbag running in the background in 3.
![image](https://user-images.githubusercontent.com/6805661/50155434-01b7fc00-0307-11e9-8263-c8871a9d8b2c.png)
    PS: after "cat /apollo/data/log/dreamview.INFO", it seems there is no data ready even i already have rosbag play in the same time as description in 3
![image](https://user-images.githubusercontent.com/6805661/50196621-cbb65e80-037e-11e9-8fc8-ead376ee1ba1.png)

**Could anyone give some suggestions ? thanks a lot**

**Comment by zwang92** [comment]
Any comments ?

**Comment by zwang92** [comment]
I think the direct cause of the issue6187 is fail to start some modules as following picture, which cause corresponding writer not available to publish data to reader in above comments, ex: planning_writer_ not available due to fail of /apollo/modules/planning/dag/planning_navi.dag
![image](https://user-images.githubusercontent.com/6805661/50292593-7e380f80-04ac-11e9-985a-43b32022b37c.png)

**Comment by unacao** [comment]
Sorry for the inconvenience and thanks for the details! On Dec 14, Apollo master branch has just switched from ROS to our own framework Cyber; you can see a general description if you search for "Apollo Master Upgrade" in our frontpage README.
I think the issue here is the demo guide you referred to seems to still talk about setup in ROS framework, given the demo bag is recorded and replayed as ros bag, while dreamview and other modules in master branch have all upgraded to work with Cyber. We are preparing for a release 3.5.0 in the coming month, and the demo data compatible with Cyber framework will be released for sure. We will definitely have our technical writers update the demo guide. Sorry for the confusion again!

**Comment by zwang92** [comment]
Thank you @unacao very much for the comments. I still have two questions as following after reading you comments, could you please have a check:
Q1: I am still wondering what the root cause of the issue is 
     a) "demo bag is recorded and replayed as ros bag"
     b) "mainboard fail to start some key modules process ex: planning as above comments"  or
     c)  "both a) and b)"  

Q2: Could you give more explanation about how ros bag communicate with dreamview (wiki link will be nice if any) ?

**Comment by xiaoxq** [comment]
> b) "mainboard fail to start some key modules process ex: planning as above comments" or

Thanks for the digging!
I guess b) is the answer. But unfortunately we don't have log for the os.system(). I will add it to the code right away, then we can see what happened. My guess is "mainboard not found", which might be resulted by mis-configged env or build failure.

**Comment by unacao** [comment]
To be clear, there are two issues here:
1. HMI failed to start the modules in Cyber framework.
2. The data played is in ROS format, while the dreamview module started is in Cyber format.

To visualize the data in dreamview, issue 1 should not be a blocker, and therefore a separate issue on its own. You should be able to visualize the data as long as the data and dreamview module are both in the same framework, i.e. ros bag + any previous releases, or cyber record + master. Issue 2 is resolved by your checkout of r3.0.0

**Comment by 7chenko** [comment]
Hi, I can't find any info on the Cyber framework. My current integration with Apollo involves sending/receiving with ROS through the Apollo module ROS topics. Will this no longer work past r3.0.0?

**Comment by xiaoxq** [comment]
Starting from v3.5, all modules have been sending/receiving messages with CyberRT reader/writer. So the ROS messages would be no longer processed.

**Comment by unacao** [comment]
Please refer to our documentations here for explanation of CyberRT
https://github.com/ApolloAuto/apollo/tree/master/docs/cyber
