### ISSUE TITLE
Third party perception coordinate transform error 

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#6210]
**Describe the bug**

The equation for coordinate transform in third party perception is not correct. According to my research.
**To Reproduce**
1. Go to  apollo/modules/third_party_perception/common/third_party_perception_util.cc
Function ：

double GetAngleFromQuaternion(const Quaternion quaternion) {
  double theta = std::atan2(2.0 * quaternion.qw() * quaternion.qz() +
                                quaternion.qx() * quaternion.qy(),
                            1.0 - 2.0 * (quaternion.qy() * quaternion.qy() +
                                         quaternion.qz() * quaternion.qz())) +
                 std::acos(-1.0) / 2.0;
  return theta;
}

**Expected behavior**
The rotation formula for Z-axis is not correct

**Screenshots**
The correct formula

![image](https://user-images.githubusercontent.com/16748704/50197544-7a0fd300-0382-11e9-9114-de834af85e7a.png)

As per discusstion above ， it should be adjust as：

double GetAngleFromQuaternion(const Quaternion quaternion) {
  double theta = std::atan2(2.0 * （quaternion.qw() * quaternion.qz() +
                                quaternion.qx() * quaternion.qy()）,
                            1.0 - 2.0 * (quaternion.qy() * quaternion.qy() +
                                         quaternion.qz() * quaternion.qz())) +
                 std::acos(-1.0) / 2.0;
  return theta;
}

**Comment by Capri2014** [comment]
Thanks! @JonathanJones92
