### ISSUE TITLE
Ubunut 16.04  rc_3.5:  apollo.sh build_no_perception errror

### ISSUE THREAD

**Issue by useebear** [ApolloAuto/apollo#6211]
I have come across the following error when build for apollo rc_3.5 with no perception on Ubuntu 16.04. Could you help me on this problem? Thank you.

 /apollo/modules/map/relative_map/BUILD:71:1: Linking of rule '//modules/map/relative_map:librelative_map_component.so' failed (Exit 1).
/usr/bin/ld: bazel-out/local-opt/bin/modules/map/relative_map/librelative_map_component_lib.a(relative_map_component.o): relocation R_X86_64_32S against `_ZTVN6apollo5cyber9transport19ListenerHandlerBaseE' can not be used when making a shared object; recompile with -fPIC
bazel-out/local-opt/bin/modules/map/relative_map/librelative_map_component_lib.a(relative_map_component.o): error adding symbols: Bad value
collect2: error: ld returned 1 exit status

**Comment by jinghaomiao** [comment]
Please do a clean by "apollo.sh clean" and rebuild it.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @useebear feel free to reopen if you are still seeing any errors. Thanks!
