### ISSUE TITLE
Questions about MPC

### ISSUE THREAD

**Issue by seniorstudent** [ApolloAuto/apollo#6213]
**Q1:**  Do you have any spec for mpc control to help us to kown the matrix? 
In apollo-master\modules\control\controller\mpc_controller.cc :
matrix_a_(5, 5) = 0.0;  
Why the element is 0 instead of 1 since is related to speed error?

**Q2:** The output of SolveLinearMPC is the increasment of control, delta u ?

**Comment by apollodevcommunity** [comment]
Q1:因为这是状态控制方程的形式，等号左边是dot_station_rate，所以 matrix_a_(5  5)=0，而matrix_a_(5  6)=1  正好满足等式。Q2:MPC的输出是控制增量，目的是为防止控制量发生突变。
——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=527
