### ISSUE TITLE
Where can I fond some architecture documents about cyber ?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#6228]
### Steps to reproduce the issue:
I  only found one cyber command document  and I want some architecture docs.

**Comment by zhxt** [comment]
直接看代码更直观（机智

ps：估计快了吧，过两天就发布了

**Comment by westeast** [comment]
@zhxt 的确，习惯是看代码之前先看点文档 ，如果还没有就直接看代码了，哈~  你去哪里上班了，记得你微信说跳槽了，哈~

**Comment by zhxt** [comment]
@westeast 文档已经更新了[Cyber RT](https://github.com/ApolloAuto/apollo/blob/master/cyber/README.md)。 其他微信私聊哈。

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved. Feel free to reopen if this issue persists. Thanks!
