### ISSUE TITLE
apollo ide问题

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#623]
您好，
    请问下你们使用的是哪种IDE调试apollo，是否支持单步调试？

**Comment by lianglia-apollo** [comment]
Personally, I recommend vim. https://pascalprecht.github.io/2014/03/18/why-i-use-vim/

**Comment by startcode** [comment]
we don't have an officially supported IDE.
I use gdb now.

**Comment by ahuer2435** [comment]
了解，谢谢。
