### ISSUE TITLE
can not continue to build Ubuntu

### ISSUE THREAD

**Issue by Renataaa** [ApolloAuto/apollo#6233]
when building the project on Ubuntu 16.04, my system  will crash frequently.  I tried several times but each time i tried it will stop at different stage. No error alert

**Comment by zezhou** [comment]
I use docker to run apollo in Ubuntu 16.04 and it works well.

**Comment by natashadsouza** [comment]
We recommend using [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_3.0_with_ubuntu16.md). Closing this issue currently. Feel free to reopen if you have additional questions. Thanks!
