### ISSUE TITLE
Failed to update my forked repository to the latest master branch.

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#6238]
I migrated Apollo master branch to the latest version according to the document [Migrate to Apollo master from old versions](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_migrate_to_the_updated_apollo_master_from_old_versions.md). The migration task was completed successfully.
But when I updated my forked repository with the`git push -f origin master` command, the following error occured:
```
open /home/davidhopper/code/apollo/docs/specs/Camera/images/Argus_Specs1.png: no such file or directory                                                                                                             
error: failed to push some refs to 'git@github.com:davidhopper2003/apollo.git'
```
My remote repositories are shown as follows:
![remote_repo](https://user-images.githubusercontent.com/31435476/50270022-26c57f80-046b-11e9-94dd-7ef9ef4750d8.png)

How can I solve it? Thank you.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**:  source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  > 3.0, latest master branch

**Comment by davidhopper2003** [comment]
@natashadsouza Thanks for your reply. The build process was successfully completed. I got the above error when I forced updating the local master branch  to my forked repository. In other words, I couldn't update the master branch of my personal forked repository with the latest apollo master branch.

**Comment by diegohu** [comment]
@davidhopper2003 Try this
`git lfs fetch --all` before git push. I just updated my fork successfully without deleting the repo.

**Comment by ycool** [comment]
please run git lfs fetch --all before git push to resolve the issue.
