### ISSUE TITLE
Error: No such container: apollo_dev

### ISSUE THREAD

**Issue by shiba24** [ApolloAuto/apollo#624]
Hi all, 

I am trying to run this wonderful project on my ubuntu (14.04) environment.
I already have installed docker, and when running `bash docker/scripts/dev_start.sh`, I got the error `Error: No such container: apollo_dev`.

Docker version is 17.09.0-ce, build afdb6d4. Does anyone have any idea?

Thank you in advance!

**Comment by gagaqq11** [comment]
I have the same error on ubuntu(16.04).
Unable to find image 'apolloauto/apollo:dev-x86_64-20170926_1848' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Error response from daemon: No such container: apollo_dev

**Comment by wanglei828** [comment]
Hi,
To use the docker hub, you need register an account. In your local machine, you need to first use "docker login -u user_name -p passwd"  to login. Then you can pull the docker image from our public repo. 
The error "No such container: apollo_dev" means your container startup fails.

**Comment by NatureEngine** [comment]
I have the same error on ubuntu (14.04). Apollo 1.5 
Error response from daemon: No such container: apollo_dev

**Comment by westeast** [comment]
My step by step startup : https://zhuanlan.zhihu.com/p/29722428
maybe your container startup fails
