### ISSUE TITLE
conf folder is missing in the perception module of the updated version

### ISSUE THREAD

**Issue by landuber** [ApolloAuto/apollo#6249]
**Describe the bug**
conf folder is missing in the perception module.

**Expected behavior**
The documentation mentions modules/perception/conf/perception_lowcost.conf, however, the file doesn't exist in the repo

**Comment by landuber** [comment]
> **Describe the bug**
> conf folder is missing in the perception module.
> 
> **Expected behavior**
> The documentation mentions modules/perception/conf/perception_lowcost.conf, however, the file doesn't exist in the repo.

> The launch folder also is not there. Any help will be appreciated.

**Comment by techoe** [comment]
The conf file of perception used to be at modules/perception/conf in Apollo 2.5. From Apollo 3.5 the conf files are at modules/perception/production/conf.

**Comment by HouYuu** [comment]
So could you tell me where i can find the conf file “perception_lowcost.conf” in Apollo 3.5？

**Comment by techoe** [comment]
There is no specific low-cost configuration file in Apollo 3.5.

**Comment by HouYuu** [comment]
Thanks for your answer, and how to launch the perception module if there is no sepecfic low low-cost configuration file in Apollo 3.5.

**Comment by HouYuu** [comment]
> 
> 
> There is no specific low-cost configuration file in Apollo 3.5.

Thanks for your answer, and how to launch the perception module if there is no sepecfic low low-cost configuration file in Apollo 3.5.

**Comment by KaWaiTsoiBaidu** [comment]
@HouYuu 
could you try `cyber_launch start modules/perception/production/launch/perception_all.launch` , without modifying any config files?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
