### ISSUE TITLE
相机的FOV多大

### ISSUE THREAD

**Issue by haithink** [ApolloAuto/apollo#6253]
请问目前用于 障碍物检测 和 红绿灯 感知的 相机的FOV  分别是多大？ 根据内参数进行计算得到的结果不对（应该是因为 畸变原因)。 文档里提到的相机手册也没说。。。

**Comment by haithink** [comment]
百度的视频说了， 分别是 30度 和60 度。

**Comment by Durant35** [comment]
> 百度的视频说了， 分别是 30度 和60 度。

@haithink 方便share一下link吗？

**Comment by haithink** [comment]
> > 百度的视频说了， 分别是 30度 和60 度。
> 
> @haithink 方便share一下link吗？ 我从https://www.mouser.cn/datasheet/2/233/LI-USB30-AR023ZWDR_datasheet-1101519.pdf 了解到，标准6mm镜头下是58° HFOV

sorry，时间过去太久了，印象里是当时apollo官方出的教学讲解视频里说的。
