### ISSUE TITLE
Error in Release binaries,

### ISSUE THREAD

**Issue by jojo666666** [ApolloAuto/apollo#6256]
Hi,

I trying to setup Apollo in my local machine.
I have installed ros my machine (using DELL XPS, GPU without Nvidia,Ubuntu 18.04)

while running
bash apollo.sh release
I getting following error :
 /apollo
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
____Loading package: third_party/can_card_library/esd_can
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
cp: cannot create regular file '/home/joo/.cache/apollo_release/apollo/bazel-bin/modules/tools/visualizer/cyber_visualizer': Permission denied

Then, i command:
joo@in_dev_docker:/apollo$ sudo chmod 777 '/home/joo/.cache/apollo_release/apollo/bazel-bin/modules/tools/visualizer/cyber_visualizer' and release binaries again
The result is same as above.

and when i conmand:
joo@in_dev_docker:/apollo$sudo bash apollo.sh release
The result is more mistakes than before.

when i play the rosbag,i followed #5450
source /apollo/scripts/apollo_base.sh
source /home/tmp/ros/setup.bash
I can see a car, and the delay of prediction and control is close to 0. But there are always some reasons that trigger the safety mode, the car can not move forward.

I really need some help.

**Comment by mumianyuxin** [comment]
I met the same problem, and do you solve the problem?

**Comment by jojo666666** [comment]
It is not yet settled. Version 16.04 has been replaced. @mumianyuxin

**Comment by mumianyuxin** [comment]
ok, thank you!

**Comment by mftaha** [comment]
Facing the same issue (on 14.04)., @jojo666666 i didn't quite get your comment, any possible solution for the issue?

**Comment by natashadsouza** [comment]
@jojo666666 @mumianyuxin  could you give us additional information - system specifications, Apollo version, built from? This will help us debug your issue better.
