### ISSUE TITLE
Dreamview launch problem

### ISSUE THREAD

**Issue by soumyaGWM** [ApolloAuto/apollo#6260]
I am using following system configuration

### System information

- **Ubuntu 16.04LTS**:
- **Apollo installed from source**:
- **Apollo version3.0**:
- **Udoo with x86_64 platform**:
[attachment1]
![screenshot from 2018-12-21 18-50-24](https://user-images.githubusercontent.com/46049675/50345656-dd059380-0555-11e9-84e3-46e1a2e8f3b2.png)

I'm using the following steps for building apollo and launch dreamview.
1. $ bash docker/scripts/dev_start.sh 
2. $ bash docker/scripts/dev_into.sh
3. $ bash apollo.sh build
**after** **successful** **build** **to** **launch** **dreamview**
4. $ bash scripts/bootstrap.sh start
       Started supervisord with dev conf
       Start roscore...
       voice_detector: started
       dreamview: started
       Dreamview is running at http://localhost:8888 

From the chrome browser we are unable to launch dreamview. see the attachment.
![localhost](https://user-images.githubusercontent.com/46049675/50346133-69fd1c80-0557-11e9-88cf-c760ae62acee.png)

From the  **rosnode** **list** we are not able to find **dreamview**
Can you please guide me to fix this issue.

**Comment by SS6141** [comment]
Hi,
Even I am facing the same problem.

**Comment by natashadsouza** [comment]
Please check out our [Dreamview start problem document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md). If you have any additional questions, feel free to reopen this issue. Thanks!
