### ISSUE TITLE
Failed to start the cyber_visualizer tool

### ISSUE THREAD

**Issue by davidhopper2003** [ApolloAuto/apollo#6279]
Hi, folks.
When I started the `cyber_visualizer` tool, I got the following error:
![cyber_visualizer_error](https://user-images.githubusercontent.com/31435476/50389094-2e816e80-0760-11e9-9e81-c6034ab003aa.png)
Could you give me some advice? Thanks.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**:  from source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  > 3.0, latest master branch
- **Graphics card**: GeForce GTX 1050 Ti
- **Graphics card driver information**: 
![nvidia-smi](https://user-images.githubusercontent.com/31435476/50393042-75865880-078e-11e9-8e9b-b52fa32bcb2d.png)
![nvidia-settings](https://user-images.githubusercontent.com/31435476/50393049-7fa85700-078e-11e9-9281-0d77c883e92b.png)

### Steps to reproduce the issue:

``` bash
# Start the docker.
bash docker/scripts/dev_start.sh -C
# Step into the docker.
bash docker/scripts/dev_into.sh
# Build the apollo project in the docker.
# "-j 16" depends on the number of CPU cores on your machine.
bash apollo.sh build -j 16
source /apollo/cyber/setup.bash
cyber_visualizer
```

### Supporting materials (screenshots, command lines, code/script snippets):
Here is the output of my computer: 
``` bash
# Out of the docker.
lspci -vnn | grep "VGA"
pacman -Qs libgl
```
![cyber_visualizer_info1](https://user-images.githubusercontent.com/31435476/50392738-d2344400-078b-11e9-98d5-2f09c1835995.png)
![cyber_visualizer_info2](https://user-images.githubusercontent.com/31435476/50392739-d2344400-078b-11e9-87e5-49a181f9c878.png)

**Comment by GoLancer** [comment]
Try 
```
bash docker/setup_host/install_nvidia_docker.sh
```
and then restart docker. 
Hope it will be helpful.

**Comment by davidhopper2003** [comment]
@GoLancer 
Thanks for your amazing advice. After I ran the following command: 
``` bash
# Out of the docker.
bash docker/setup_host/install_nvidia_docker.sh
```
An error is shown as follows when I restarted the Docker. In other words, the Docker can't be started because of the inconsistentence of the NVidia graphics driver version. 
![docker_start_error](https://user-images.githubusercontent.com/31435476/50464559-976d1e80-09cc-11e9-997c-de490a3dff17.png)

By the way, the NVidia graphics driver version of my machine is 384 and I can't install the 375 version recommended by Apollo.

**Comment by simon750324** [comment]
@davidhopper2003 

If you want to install nvidia driver 384.130, you can try below steps.

```
wget http://us.download.nvidia.com/XFree86/Linux-x86_64/384.130/NVIDIA-Linux-x86_64-384.130.run
chmod +x ./NVIDIA-Linux-x86_64-384.130.run
./NVIDIA-Linux-x86_64-384.130.run --no-opengl-files -a -s
```

**Comment by davidhopper2003** [comment]
@simon750324 
Thank you. I'll try it.

**Comment by davidhopper2003** [comment]
> @davidhopper2003
> 
> If you want to install nvidia driver 384.130 in docker, you can try below steps.
> 
> ```
> wget http://us.download.nvidia.com/XFree86/Linux-x86_64/384.130/NVIDIA-Linux-x86_64-384.130.run
> chmod +x ./NVIDIA-Linux-x86_64-384.130.run
> sudo ./NVIDIA-Linux-x86_64-384.130.run --no-opengl-files -a -s
> ```

This method doesn't work. I used the following command to install the NVIDIA driver inside Docker.
```
# In Docker
sudo apt update
apt search nvidia-384
sudo apt install nvidia-384
nvidia-smi
```

**Comment by davidhopper2003** [comment]
The problem has been resolved.
