### ISSUE TITLE
You need to install and run git-lfs when working with apollo.

### ISSUE THREAD

**Issue by defendergz** [ApolloAuto/apollo#6282]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:2.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
i want to install apollo without hardware for localization use own .bag file. my step as following:
1  install git 
2 git clone apollo & cd apollo path
3 bash docker/setup_host/install_docker.sh
4 restart % cd apollo
5 docker ps 
6 bash docker/scripts/dev_start.sh -C
i got this and i do have installed git lfs:
"
You need to install and run git-lfs when working with apollo.
New versions of git manage it automotically, but old versions may 
need to run `git lfs clone` and `git lfs pull`.
"

![image](https://user-images.githubusercontent.com/37363725/50410078-b2eff200-0831-11e9-8a6d-a6dc5f306f0a.png)

![image](https://user-images.githubusercontent.com/37363725/50409937-fbf37680-0830-11e9-8b88-845682b626e9.png)

anyone can help me?  please!!

**Comment by defendergz** [comment]
file:///home/cc/%E5%9B%BE%E7%89%87/2018-12-25%2010:03:18%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by defendergz** [comment]
@all2one @mbinna @bigwhite @weidezhang

**Comment by xiaoxq** [comment]
Please try "git lfs fetch --all".

**Comment by defendergz** [comment]
@davidhopper2003 
> You can refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_migrate_to_the_updated_apollo_master_from_old_versions.md) or [my blog](https://blog.csdn.net/davidhopper/article/details/85097502) to solve this problem.

thanks for ur reply
when i perform `bash scripts/bootstrap.sh` ,
![2018-12-26 21 31 32](https://user-images.githubusercontent.com/37363725/50447455-2c810080-0956-11e9-9c76-f76aebc6b16c.png)

and open `http://localhost:8888/`, there is nothing :
![2018-12-26 21 33 13](https://user-images.githubusercontent.com/37363725/50447458-31de4b00-0956-11e9-93f9-2b4a34a4b054.png)
could u plz tell me how to deal with it? thank u

**Comment by davidhopper2003** [comment]
@defendergz Is your local code freshly downloaded? Do you recompiled your code?

**Comment by defendergz** [comment]
> @defendergz Is your local code freshly cloned? Do you recompiled your code?

yes, i cloned it by `git lfs clone https://github.com/ApolloAuto/apollo.git` as ur blog yesterday ，and recompiled just now by `bash apollo.sh build` , i passed build and met the same situation as above.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen should you have any additional questions. Thanks!
