### ISSUE TITLE
How to deal with the vehicle params when we want to adapt apollo to trailer

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#6295]
Dear apollo team developers, 
&ensp;&ensp; We want to adapt apollo to a trailer, but now, apollo is used for those cars that they are a rigid body, do you have any ideas or suggestions about this situation? It involves so many aspects to take consideration, if we want to simplify it now, can we make it work only by adjusting vehicle params, like the **wheel_base**, **wheel_rolling_radius**, **min_turn_radius**?
&ensp;&ensp;If any other team or project that is doing something similar to ours, welcome you to give us some advice or we can talk about relative problems.

**Comment by lianglia-apollo** [comment]
Simply modifying the vehicle params won't work if the vehicle has a trailer. Different planning (maybe control) module(s) will be needed.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no communication in a while. @xinwf feel free to reopen it if you have additional questions. Thanks!
