### ISSUE TITLE
Intermediate RoutingResponse 

### ISSUE THREAD

**Issue by BoChang11** [ApolloAuto/apollo#6309]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

I could see some new **RoutingResponses** are being generated when there is a lane change behavior.

For example : I have given the routing from point A to B which involves a lane change. 
During the start of the routing lets say I get **RoutingResponseA**, and after the lane change I get **RoutingResponseB**. 
1. How would I retain the first **RoutingResponseA**, till the end of the journey.
2. How could I avoid these intermediate **RoutingResponses**, so that I consider RoutingResponses between 2 successive routing given by the user. 

Note : I am using **AdapterManager::GetRoutingResponse()->GetLatestObserved()**; 

Kindly let me know if you need more details from my end to clarify the doubt. 

### Supporting materials (screenshots, command lines, code/script snippets):

BR

**Comment by ycool** [comment]
lane change won't trigger a new routing response. It only happens when the self driving car finds out it can't itself out of the current routing situation (e.g. fail to change lane). Then it will trigger re-routing.
