### ISSUE TITLE
DreamView rendering issue

### ISSUE THREAD

**Issue by aravindSwamy94** [ApolloAuto/apollo#6317]
Hi, 
          I m using Ubunut 16.04 and the apollo's recent master branch (i suppose 3.5) version of the code.

The issue what I'm facing is dreamview is launched but I'm not able to visualize the map and car loaded on the simulation. If I give a routing request , car starts moving, i can visualize that by change in the speed of the vehicle. But I'm not able to look at the map information and car movement. Im testing with sim_control by activating only planning and routing modules.

Also all the images on the module controller/layer manager are missing

PFA the images for your reference 
![no_rendereing](https://user-images.githubusercontent.com/46023668/50513982-5a368880-0ac1-11e9-9496-e36749751666.png)
![image_missingfortoolbars](https://user-images.githubusercontent.com/46023668/50513986-5dca0f80-0ac1-11e9-8cb7-1f9e5bee41f5.png)

Request you to help me on this issue. Thanks in advance

**Comment by aravindSwamy94** [comment]
The same issue is seen with cyber_visualizer as well. Please find the attached screenshot
![cyber_visualizer](https://user-images.githubusercontent.com/46023668/50514788-9ae4d080-0ac6-11e9-819d-b0fa9b3ef110.png)

**Comment by unacao** [comment]
The images may not be properly downloaded as most of them are stored with git lfs. You can check the file modules/dreamview/frontend/dist/app.bundle.js and see if it only contains a little information about git lfs links. You can try to run "git lfs pull" and the app.bundle.js should contain a large chunk of uglified code.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @aravindSwamy94 feel free to reopen if you have additional questions. Thanks!
