### ISSUE TITLE
Localization tool - evaluate_compare.py

### ISSUE THREAD

**Issue by sudhanva-s** [ApolloAuto/apollo#6357]
Hi everyone,

What does evaluation file in ```https://github.com/ApolloAuto/apollo/blob/master/modules/tools/localization/evaluate_compare.py``` mean in line 237 ?

**Comment by mickeyouyou** [comment]
Line 237 just is arguments value check.
You can reference the document which introduce the usage of this script [how_to_run_MSF_localization_module_on_your_local_computer.md](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md)

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
