### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mumianyuxin** [ApolloAuto/apollo#6381]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:ubuntu 16.04
- **Apollo installed from (source or binary)**: source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.0

### Steps to reproduce the issue:
- When I build with `bash apollo.sh build`, the error happened, how to deal with it?
**Thank you!**
![image](https://user-images.githubusercontent.com/32149232/50678330-1ef40680-1039-11e9-9b6c-fc06086e1d50.png)

**Comment by jinghaomiao** [comment]
Please run a apollo.sh clean and rebuild the system.

**Comment by natashadsouza** [comment]
@mumianyuxin were you able to resolve your issue?

**Comment by mumianyuxin** [comment]
No, I don't.

**Comment by natashadsouza** [comment]
@mumianyuxin did you try rebuilding?

**Comment by mumianyuxin** [comment]
Yes, I did, but failed.

**Comment by natashadsouza** [comment]
Are you seeing the same error messages as above? Have you successfully installed Git LFS? 
Please check our software FAQs for instructions on how to migrate to the master branch. @mumianyuxin
