### ISSUE TITLE
module monitor not building

### ISSUE THREAD

**Issue by vdjapic** [ApolloAuto/apollo#6386]
I am using Apollo 3.0. See below. Can you pls help me resolve this issue?

administrator@in_dev_docker:/apollo$ ./scripts/bootstrap.sh 
Start roscore...
/apollo/scripts/apollo_base.sh: line 224: 14911 Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/monitor/monitor --flagfile=modules/monitor/conf/monitor.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/monitor.out 2>&1
Could not launch module monitor. Is it already built?
Launched module dreamview.
Dreamview is running at http://localhost:8888

**Comment by xiaoxq** [comment]
Could you try "bazel build modules/monitor" and post the logs?

**Comment by vdjapic** [comment]
administrator@in_dev_docker:/apollo$ bazel build modules/monitor
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.....................................
INFO: Analysed target //modules/monitor:monitor (68 packages loaded).
INFO: Found 1 target...
Target //modules/monitor:monitor up-to-date:
  bazel-bin/modules/monitor/monitor
INFO: Elapsed time: 477.410s, Critical Path: 138.59s
INFO: Build completed successfully, 1305 total actions

**Comment by vdjapic** [comment]
Then I tried to start bootstrap but I got: "Could not launch module dreamview. Is it already built?". Then I did: "bazel build modules/dreamview". 

"administrator@in_dev_docker:/apollo$ ./scripts/bootstrap.sh 
Start roscore...
Launched module monitor.
Could not launch module dreamview. Is it already built?
administrator@in_dev_docker:/apollo$ bazel build modules/dreamview "

BUT "dreamview failed to build". I got:

"INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed target //modules/dreamview:dreamview (19 packages loaded).
INFO: Found 1 target...
ERROR: /apollo/modules/dreamview/backend/handlers/BUILD:23:1: C++ compilation of rule '//modules/dreamview/backend/handlers:image_handler' failed (Exit 1)
In file included from modules/dreamview/backend/handlers/image_handler.cc:24:0:
./modules/perception/traffic_light/util/color_space.h:163:25: error: '__m256i' was not declared in this scope
 const size_t A = sizeof(__m256i);
                         ^
./modules/perception/traffic_light/util/color_space.h:169:7: error: '__m256i' does not name a type
 const __m256i K_ZERO = SIMD_MM256_SET1_EPI8(0);
.......
Target //modules/dreamview:dreamview failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 172.675s, Critical Path: 65.80s
FAILED: Build did NOT complete successfully"

**Comment by xinwf** [comment]
It's easy to solve this problem(Is it already built), after you use build or build_gpu command to compile successfully, if it gives you this error, just exit docker(not stop) and re-enter, it's ok, have a try, if not, maybe other problems.

**Comment by vdjapic** [comment]
Still Dreamview not opening in the browser (http://localhost:8888), even after run dreamview start :

administrator@in_dev_docker:/apollo$ ./scripts/bootstrap.sh     
Start roscore...
Launched module monitor.
Launched module dreamview.
Dreamview is running at http://localhost:8888
administrator@in_dev_docker:/apollo$ run dreamview start     
[1] 4794
Launched module dreamview.
administrator@in_dev_docker:/apollo$ rosnode list
/SystemMonitor
/rosout
[1]+  Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/dreamview.out 2>&1
administrator@in_dev_docker:/apollo$ ./scripts/bootstrap.sh stop
Module dreamview is not running - skipping.
Successfully stopped module monitor.
roscore: stopped
administrator@in_dev_docker:/apollo$ ./scripts/bootstrap.sh      
Start roscore...
Launched module monitor.
Launched module dreamview.
Dreamview is running at http://localhost:8888
administrator@in_dev_docker:/apollo$ rosnode list
/SystemMonitor
/rosout
administrator@in_dev_docker:/apollo$ run dreamview start
[1] 5096
Launched module dreamview.
administrator@in_dev_docker:/apollo$ rosnode list
/SystemMonitor
/rosout
[1]+  Illegal instruction     (core dumped) nohup /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/dreamview.out 2>&1
administrator@in_dev_docker:/apollo$

**Comment by xinwf** [comment]
Maybe it's the docker problem, we have met similar situation, but the difference is that our dreamview works well at the beginning, after we stop it and restart it again, it occurs this problem, and then, we only can exit and stop docker, restart docker again. Sometimes we only can get rostopic info from one terminal, after we get a pure docker again, this problem doesn't happen any more.

**Comment by cdemirsoy** [comment]
This must be because of the PCL library. It was compiled for a certain processor that has some modern instruction set but my computer was old as yours is and pcl library did not work. There is already a post in the issues regarding that and it is easy to solve.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by Alphabaijinde** [comment]
> Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

how can i success what use bazel building the  dreamview

**Comment by storypku** [comment]
> > Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
> 
> how can i success what use bazel building the dreamview

？I didn't quite get what you mean... You can use Chinese for questions also.

**Comment by Alphabaijinde** [comment]
apollo-r2.5.0
启动人机交互界面命令： bash scripts/bootstrap.sh
错误：Could not launch module dreamview. Is it already built?

使用bazel builde dreamview, 构建dreamview   
报错：
In file included from modules/dreamview/backend/handlers/image_handler.cc:24:0:
./modules/perception/traffic_light/util/color_space.h:163:25: error: '__m256i' was not declared in this scope
const size_t A = sizeof(__m256i);
^
这个错误怎么解决？只能重新进入docker吗？




> > > Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
> > 
> > 
> > how can i success what use bazel building the dreamview
> 
> ？I didn't quite get what you mean... You can use Chinese for questions also.

**Comment by ntutangyun** [comment]
@Alphabaijinde usually if you see could not launch module xxx, you could try to build everything again, with `bash apollo.sh build_opt_gpu`.
