### ISSUE TITLE
modules/monitor not build on 3.0

### ISSUE THREAD

**Issue by soumyaGWM** [ApolloAuto/apollo#6387]
Hi,
I'm using the following system specification:
**System information**
- Ubuntu 16.04LTS
-  Apollo 3.0 installed from source
-  Udoo with x86_64 platform
When I have build succeed as per the below attachment:
![screenshot from 2019-01-04 18-25-57](https://user-images.githubusercontent.com/46049675/50689105-54efb580-104e-11e9-836a-cb35f2e2700d.png)
but I could not run modules monitor:
apollo$ run monitor start
[1] 31796
[1]+  Exit 127                nohup /apollo/modules/monitor/monitor --flagfile=modules/monitor/conf/monitor.conf --log_dir=/apollo/data/log < /dev/null > /apollo/data/log/monitor.out 2>&1
Could not launch module monitor. Is it already built?
![monitor](https://user-images.githubusercontent.com/46049675/50689371-8026d480-104f-11e9-91ff-fe623deb0218.png)
after I look up my system hardware specification info carefully , we found that UDOO_x86 PC using HDMI secondary port for display (no VGA port available), on the other hand once run **lspci** on terminal we can see VGA compatible controller available on PCI bus.
![lspci](https://user-images.githubusercontent.com/46049675/50689749-eb24db00-1050-11e9-9575-f5403e793040.png)
we observed during every building modules/monitor is skip building,  I doubt HDMI secondary display on UDOO_x86 PC is may not compatible. 

Any help to resolve this issue is much appreciated.

Regards,
Soumya.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if the issue persists. Thanks!
