### ISSUE TITLE
rosbag play can not play successfully

### ISSUE THREAD

**Issue by jinjinhong** [ApolloAuto/apollo#6414]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
I have run as this command:
./apollo.sh build_opt_gpu
./scripts/bootstrap.sh
./scripts/perception_lowcost_vis.sh
rosbag play demo_2.5.bag , then the command line like this:
root@in_dev_docker:/apollo# rosbag play demo_2.0.bag -l --clock
[ INFO] [1546846313.415296697]: Opening demo_2.0.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
 [RUNNING]  Bag Time: 1514497058.004191   Duration: 0.000000 / 34.895545     
the time no change ,

**Comment by natashadsouza** [comment]
@jinjinhong can you give us additional system information to help us troubleshoot better? Thanks!

**Comment by jinjinhong** [comment]
> @jinjinhong can you give us additional system information to help us troubleshoot better? Thanks!
Thank you for your reply. The problem is solved. Do you have any experience in adding new modules? I need to add new detection functions to the sensing module.

**Comment by jinjinhong** [comment]
@natashadsouza Thank you for your reply. The problem is solved. Do you have any experience in adding new modules? I need to add new detection functions to the sensing module.

**Comment by natashadsouza** [comment]
@jinjinhong Apollo currently functions as a single system, therefore before adding a module to it, understand that there would be a lot of additional work to be done to ensure that the module functions perfectly with the other modules of Apollo. Simply add your module to the modules/ folder. You can use modules/routing as an example, which is a relatively simple module. Write the BUILD files properly and apollo.sh will build your module automatically

**Comment by natashadsouza** [comment]
Closing this issue as it is resolved. Feel free to reopen it should you have additional questions.
