### ISSUE TITLE
[localization]RawImuProcess cur_imu_time and pre_imu_time

### ISSUE THREAD

**Issue by lvxin0805** [ApolloAuto/apollo#6416]
Dear Sir,
Now I'm reading the localization sourcecode, in the void LocalizationIntegProcess::RawImuProcess(const ImuData &imu_msg) function, should we calculate the delta_time and then set the cur_imu_time to pre_imu_time?

  static double pre_imu_time = cur_imu_time;
  double delta_time = cur_imu_time - pre_imu_time;

  if (delta_time > 0.1) {
    ADEBUG << std::setprecision(16) << "the imu message loss more than 10, "
           << "the pre time and current time: " << pre_imu_time << " "
           << cur_imu_time;
  } else if (delta_time < 0.0) {
    ADEBUG << std::setprecision(16)
           << "received imu message's time is eary than last imu message, "
           << "the pre time and current time: " << pre_imu_time << " "
           << cur_imu_time;
  }

**Comment by devynliu** [comment]
你好，这是C++语言的规则，静态变量修饰时在程序运行是只允许运行一次，也就是说static double pre_imu_time = cur_imu_time;语句在你整个程序中只会运行一次。但pre_imu_time 这个变量在整个程序运行时会保留最后一次的修改。你可以看到这个函数最后把当前时间赋值给了前一次imu时间。也就是说在下一次运行这个函数时，当前时间 和上一帧imu时间进行了比较。以此检验帧是否丢失。望理解。

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
