### ISSUE TITLE
Explanation of the parameters localization.conf 

### ISSUE THREAD

**Issue by vdjapic** [ApolloAuto/apollo#6417]
Can you pls send me a document that explains the definition of the parameters in apollo/modules/localization/conf/localization.conf ?

**Comment by xinwf** [comment]
Give it up, no one will send you such a document, just get the meaning of them from the code or a short description in xxx_gflags.cc.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
