### ISSUE TITLE
lidar drivers support

### ISSUE THREAD

**Issue by AramSo** [ApolloAuto/apollo#6434]
**Is your feature request related to a problem? Please describe.**
Currently, Apollo only supports two lidar drivers. 
- https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_hardware_system_installation_guide_v1.md#light-detection-and-ranging-system-(lidar)-

However, 
1. vls 128
In contrib, it looks like there is a newer driver like vls-128.
(https://github.com/ApolloAuto/apollo-contrib/tree/master/velodyne_vls)

2. Apollo's paper says that the following lidar(Riegl VMX-1HA) is being used. It looks like an unsupported driver here.
- https://arxiv.org/pdf/1803.06184.pdf (see 4 pages)

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**

**Additional context**
What is the best performance LiDAR? vls-128 or VMX-1HA?

**Comment by lianglia-apollo** [comment]
Sorry for the confusion. The code base in this repo is not directly related to the paper you mentioned (https://arxiv.org/pdf/1803.06184.pdf).

We are using vls-128 lidar. Please see the documents in this repo for reference.
