### ISSUE TITLE
为什么这版开源程序每一个模块都没有main.cc？

### ISSUE THREAD

**Issue by 14212094** [ApolloAuto/apollo#6436]
各位大牛好 我是apollo方面的入门者，想问下为什么这版apollo程序每个模块都没有main.cc？谢谢

**Comment by zezhou** [comment]
新版本(3.5)开始引入了cyber这个实时通讯框架（类似于ros ）, 它会将每个模块以 '.so' 库的形式载入，而不再是每个模块单独 bin 文件的形式了

Apollo introduce 'cyber' since version 3.5, which load each module by '.so'.

**Comment by davidhopper2003** [comment]
My blog analyzed this issue. Please refer to [my blog](https://blog.csdn.net/davidhopper/article/details/85248799) for details.

**Comment by 14212094** [comment]
@zezhou 谢谢~

**Comment by 14212094** [comment]
@davidhopper2003 Thank you~
