### ISSUE TITLE
bash apollo.sh build error！----file name too long

### ISSUE THREAD

**Issue by lql7595** [ApolloAuto/apollo#6448]
**Describe the bug**
When I executed bash apollo.sh build, an error occurred.

**Screenshots**
![qq 20190109111103](https://user-images.githubusercontent.com/46510241/50874547-524ee080-13ff-11e9-8731-b2649959dd3d.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser google

**Additional context**
The same error occurs when apollo.sh build_cpu

**Comment by jinghaomiao** [comment]
Looks like the issues are resolved. Closing the ticket now.
