### ISSUE TITLE
Offline Perception Visualizer in Apollo 3.5

### ISSUE THREAD

**Issue by tpengchang** [ApolloAuto/apollo#6450]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:
I don't find export_pcd_offline tool to generate *.pcd and pose.txt.
There is also no gen_pose_file.py is in Apollo 3.5.
How can I use Offline Perception Visualizer in Apollo 3.5?

**Comment by techoe** [comment]
Thank you for using Apollo! Dreamview is currently used for online or offline visualization.

**Comment by jinfagang** [comment]
@techoe Is there any cyber visualizer tutorial? I want visualize the lidar min box regression result as bounding box

**Comment by natashadsouza** [comment]
@jinfagang you could refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md) for cyber tools. Reach out if you have additional questions. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
