### ISSUE TITLE
Some kind of slack/discord channel

### ISSUE THREAD

**Issue by harlowja** [ApolloAuto/apollo#6457]
Where exactly do people go to talk to the apollo developers or community?

From what I can tell IRC is empty, there isn't a google group, so I'm wondering exactly where is the place to talk to the larger community?

**Comment by zhxt** [comment]
Yeah, that's true, most of time, only me , one of my friend(from another community) and a log bot are hanging on IRC channel  >_>!  Only a few people knows there is an IRC channel :-(

Actually there is a slack channel, too.  Although it seems not opened for all developers by default. But I think you can ask @Zhenni17 for an invitation.

And there are also several local [WeChat](https://www.wechat.com/en/) groups(more than ten, about 5000+ people/developers there, add 'apollodev' as wechat friend and ask for joining if you like).

**Comment by harlowja** [comment]
Ah, cool, it'd be great to like put this information on the main github or website or something :)

**Comment by harlowja** [comment]
@Zhenni17 can u add/invite `harlowja@gmail.com`

**Comment by natashadsouza** [comment]
@harlowja we do have a private channel, but are in the process of setting up one for our developers as well. Stay tuned!
