### ISSUE TITLE
"Rosbag command not found" error

### ISSUE THREAD

**Issue by Iali99** [ApolloAuto/apollo#6463]
I have successfully built apollo 3.0. I am also able to launch Dreamview. But when I try to use the rosbag play command to play the rosbag file, it gives the error : "rosbag : command not found" . I have searched for solutions in the issues section. I found out that ros is not installed after building apollo. There is no ros directory inside " /apollo/bazel-apollo/external/ " . Can you please help me with this?

**Comment by KitFung** [comment]
`source /apollo/scripts/apollo_bash.sh`

**Comment by Iali99** [comment]
I have tried that. It is not working. As I said, there is no ros folder anywhere in apollo directory.

**Comment by KitFung** [comment]
Is this folder `/home/tmp/ros/` exist?

**Comment by HongyiSun** [comment]
There should be ROS support on the 3.0 branch.
And we have updated the demo docs for master (apollo 3.5) recently. Please try again with the most recent code if you are working on the master branch.

**Comment by Iali99** [comment]
I have built the latest code. It has ros folder. But the error continues. There is only one command "rosbag_to_record". There is rosbag file in /apollo/bazel-apollo/external/ros/bin . I tried using "source /apollo/scripts/apollo_base.sh" but it doesnot work

**Comment by Iali99** [comment]
I was just following the doc. So I wanted to use rosbag. Now I have run the demo successfully using the .record file given. Thanks for the help.
