### ISSUE TITLE
Simulation profiling

### ISSUE THREAD

**Issue by AlessandroToschi** [ApolloAuto/apollo#6470]
OS Platform and Distribution (e.g., Linux Ubuntu 14.04):Linux Ubuntu 14.04
    Apollo installed from (source or binary): source master
    Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 3.5
I would like to profile the software modules during the simulation provided in the demo guide 'demo_3.5.record'.
I compiled the modules using the 'build_prof' flag. 
I don't have hardware and I would like to profile as many modules as possible in my local computer. Is there a way to do that?

I've seen that there is a doc about profiling but when I try it with a module such like 'planning' it returns immediately because of the configuration file provided.

I am following the guide 'Run Offline Demo' so how can I profile that demo? Is there an order in which turn on the different modules in dremviewer? Do I have to donwload some special dataset from the apollo data auto?

Thank you for any reply.

**Comment by daohu527** [comment]
At present, some modules support performance testing, but not all of them. The performance can be tested by means of simulation, but I think case by case analysis is needed.
