### ISSUE TITLE
About apollo finite state machine in planning

### ISSUE THREAD

**Issue by panpgg** [ApolloAuto/apollo#6472]
Hi,
    From https://github.com/ApolloAuto/apollo/blob/master/modules/planning/README.md, we know that there is finite state machine in planning, but no document about it. I have searched all source code and have no idea.
    Do you have any explanation for FSM or any hint I can start?

Thanks.

**Comment by lianglia-apollo** [comment]
You can refer to the scenario manager for details. We didn't use "FSM" explicitly in the code.

**Comment by panpgg** [comment]
Hi lianglia,
Thanks for your replay. Do you mean the "finite state machine" are refer to LANE_FOLLOW, SIDE_PASS, STOP_SIGN_UNPROTECTED, TRAFFIC_LIGHT_RIGHT_TURN_UNPROTECTED?
If above question is yes, is the state machine decided by scenario_manager(void ScenarioManager::Update())?
And does scenario_manager only exist in public_road_planner?
Because other planner(lattice, open_space, navi) has no sensor_manager.

Thanks.

**Comment by lianglia-apollo** [comment]
The answers to all your questions are "YES".

The scenario manager managers/selects one of the appropriate scenarios. The architecture was designed this way as we want to manipulate every scenario with multiple stages, which can have multiple different tasks with different parameters.

Scenario manager is only in public_road_planner, which is the planner used in Apollo 3.5. We provide simple interface and all other planners can incorporate multiple scenarios easily.

**Comment by jmtao** [comment]
@panpgg these are different planners at high level, and only one would be selected and in use. 
StdPlanning (now called OnLanePlanning) is the default one. 
NaviPlanning is the a navigation mode which doesn't requires HD Map. 
OpenSpacePlanning is a mode to handle open space parking and etc. 
There's no FSM or state switching among them. 

Hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
