### ISSUE TITLE
NavigationInfo

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#6474]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

###  the issue:
When i see the README.md in relative map module,i find the output is  "NavigationInfo received from dreamview module",but in the config file,it shows Navigation is just Recive only .Could someone tell me why?

**Comment by davidhopper2003** [comment]
In my experience, I think there is an error in the `README.md ` document. `NavigationInfo` is just the input data of the `Relative Map` module, not the output data.
@yifeijiang Am I correct?

**Comment by natashadsouza** [comment]
@davidhopper2003 you are correct. Please find PR #7308 that resolves it. Thank you so much for your response.
