### ISSUE TITLE
Dreamview return an empty page

### ISSUE THREAD

**Issue by aasatria** [ApolloAuto/apollo#6479]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:14.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

Just followed the instruction. basicly:
bash dev_start.sh
bash dev_into.sh
bash apollo.sh clean
bash apollo.sh build
bash script/bootstrap.sh
#success but page is empty
![screenshot from 2019-01-14 16-25-07](https://user-images.githubusercontent.com/46490066/51102223-0e057b00-1819-11e9-9bb4-1bd812b76f1d.png)

when browsing to localhost:8888, the response is an empty page with

**Comment by westeast** [comment]
I have the same problem . and I solve it by `git lfs fetch --all .` at the project root directory.
because some bundle.js file have not update from git lfs.

**Comment by aasatria** [comment]
> I have the same problem . and I solve it by `git lfs fetch --all .` at the project root directory.
> because some bundle.js file have not update from git lfs.

Thank You! re-fetching using lfs and then rebuilding it works, The Dreamview now shows up.

**Comment by Younch-15** [comment]
> Thank You! re-fetching using lfs and then rebuilding it works, The Dreamview now shows up.

Hi aasatria,

I'm facing exactly the same problem with you. I tried `git lfs fetch --all` but it doesn't work.

_yhm@in_dev_docker:/apollo$ git lfs fetch --all
fetch: Fetching all references..._

Could you please tell me detailed steps you followed to solve this issue? I would be very grateful about that.

**Comment by aasatria** [comment]
> I'm facing exactly the same problem with you. I tried `git lfs fetch --all` but it doesn't work.
> 
> _yhm@in_dev_docker:/apollo$ git lfs fetch --all fetch: Fetching all references..._
> 
> Could you please tell me detailed steps you followed to solve this issue? I would be very grateful about that.

'~$ git lfs clone https://github.com/ApolloAuto/apollo.git apollo-repo'
'~$ cd apollo-repo/'
'~/apollo-repo$ git lfs fetch --all'

followed with dev_start and dev_into, and rebuild.

**Comment by aboarya** [comment]
I followed the same instructions above
```
$ cd apollo-repo/
$ ~/apollo-repo$ git lfs fetch --all

followed with dev_start and dev_into, and rebuild.
```

However still seeing the blank page in Chrome and Firefore.  based on [6479](https://github.com/ApolloAuto/apollo/issues/6479) I am also seeing that `app.bundle.js` is only metadata and not the actual content

**Comment by aboarya** [comment]
The problem for me (and I expect for some others) was that git lfs was not initialized.  So in summary:
```
git clone https://github.com/ApolloAuto/apollo.git
git lfs install
git lfs fetch --all
```
You can now confirm that `app.bundle.js` is actual content
```
$ cat modules/dreamview/frontend/dist/app.bundle.js
```
Will be actual js code and not git lfs metadata

**Comment by Younch-15** [comment]
@aasatria I just got my dreamview worked. Thank you!
