### ISSUE TITLE
Demo 3.5 camera sensor and LiDAR point cloud not working?

### ISSUE THREAD

**Issue by mok232** [ApolloAuto/apollo#6480]
I have setup Apollo 3.5 and the demo runs fine (see screenshot below). 

![screenshot from 2019-01-14 11-56-08](https://user-images.githubusercontent.com/40494713/51103842-a857c580-17fd-11e9-9183-b4fb108a23c6.png)

However, I cannot open the camera sensor and LiDAR point cloud shown in the following demo:

https://www.youtube.com/watch?v=JWoNMFsPRH8

For reference, the camera view appears blank as shown in the bottom right corner of the screenshot below:

![screenshot from 2019-01-14 13-12-19](https://user-images.githubusercontent.com/40494713/51103979-1e5c2c80-17fe-11e9-86c1-0322d1a3cf03.png)

**Comment by mickeyouyou** [comment]
File size is limited and `demo_3.5.record` does not contain point cloud and image data

**Comment by mok232** [comment]
In that case, is it possible to get the demo_3.5.record file that contains the image data? Also, is it possible to run the previous demos (e.g. demo_2.5.bag) on Apollo 3.5?

**Comment by mickeyouyou** [comment]
You can use this tool transform every rosbag to record .  `rosbag_to_record `https://github.com/ApolloAuto/apollo/tree/master/modules/data/tools/rosbag_to_record

**Comment by lianglia-apollo** [comment]
It is self explained. 
```std::cout << "Usage:\n" << "  rosbag_to_record input.bag output.record" << std::endl;```

**Comment by tornadomeet** [comment]
```bash apollo.sh build``` do not generate ```rosbag_to_record```, and  ```bazel build modules/data/tools/rosbag_to_record/...``` build will failed as https://github.com/ApolloAuto/apollo/issues/9824
