### ISSUE TITLE
Is Apollo Cyber RT centralized arch? If the answer is yes, once Cyber RT carshed, the whole system crash. Baidu ROS before is decentralization, so the scenario discussed here would not happen.

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6507]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by Zhenni17** [comment]
Closing the issue.

**Comment by CCodie** [comment]
Hi @KitFung , can I get some information or documents about Cyber RT in English ?
And I wonder when the Apollo Team will upload the materials about Cyber RT.
Thanks !
