### ISSUE TITLE
ImportError: No module named modules.hmi.proto.config_pb2

### ISSUE THREAD

**Issue by qsphan** [ApolloAuto/apollo#651]
Hi,
I got the error as in the title when trying to start HMI from Docker, using `bash scripts/hmi.sh`. I followed all the steps in the README file. Here is the whole output:

> root@in_dev_docker:/apollo# bash scripts/hmi.sh
>
> Start roscore...
> Start HMI ros bridge...
> Failed to start HMI.
> Traceback (most recent call last):
>   File "modules/hmi/web/hmi_main.py", line 25, in <module>
>     from config import Config
>   File "/apollo/modules/hmi/web/config.py", line 26, in <module>
>     import modules.hmi.proto.config_pb2 as config_pb2
> ImportError: No module named modules.hmi.proto.config_pb2

Any help would be highly appreciated.

**Comment by xiaoxq** [comment]
Did you run "apollo.sh build"? Did it show any error message?

**Comment by qsphan** [comment]
Sorry, I made a mistake when building. I can run Appollo now.
Please delete this issue. Thank you.
