### ISSUE TITLE
Is the apollo obstacle detection updated?

### ISSUE THREAD

**Issue by fred0209** [ApolloAuto/apollo#6512]
Apollo3.5 obstacle detection can only detect vehicles pedestrians and bicycles(I test same image), like same to 3.0, but the introduction said that there are updates, the code also appears to be like this；

**Comment by KaWaiTsoiBaidu** [comment]
@fred0209 
I tested with some images, and it detected classes such as TRAFFIC_CONE, VAN and so on in addition to cars, bicycles and pedestrians.  Could you provide details on how you tested your images?

**Comment by techoe** [comment]
Thank you for the question. The perception module detects other objects including road cones but it does not pass them to the control. We plan to pass them in future release.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
