### ISSUE TITLE
apollo.sh [test|test_cpu] 

### ISSUE THREAD

**Issue by poutyface** [ApolloAuto/apollo#6528]
**Describe the bug**
Apollo v3.5 or later.
Currently, Apollo team execute apollo.sh [test|test_cpu] ?   
Some perception module tests are fail. (e.g. unknown.pt file is not exist)
And test_cpu mode do not filter out tests depends on GPU.
The following line in apollo.sh is not correct.
```
    BUILD_TARGETS="`echo "$BUILD_TARGETS" | grep -v "cnn_segmentation_test\|yolo_camera_detector_test\|unity_recognize_test\|perception_traffic_light_rectify_test\|cuda_util_test"`"
```

**To Reproduce**
```
> bash apollo.sh test
> bash apollo.sh test_cpu
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by natashadsouza** [comment]
@poutyface could you create a Pull Request with your recommendation to fix the bug you described? Thank you for your contribution to our platform.
