### ISSUE TITLE
VLP-16 Calib faliure 

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#6534]
We tried to calibrate our VLP-16 placed in the top of our model.
The GPS sync signal have been firmly connected. 

We tried to use the Apollo software lidar-gnss calib tool. However the results seems bad as below:
![image](https://user-images.githubusercontent.com/16748704/51308481-3097ce00-1a7d-11e9-97a2-5b1c021d1b52.png)

One possible factor that cause this could be:
![image](https://user-images.githubusercontent.com/16748704/51308836-0692db80-1a7e-11e9-9e15-e0486ded52b7.png)

Could the Apollo team or developers give us some idea to help us out. We have pend on this issue for days.

Thanks!

**Comment by JonathanJones92** [comment]
@bigwhite @Axin0626 @mickeyouyou  Sincerelly ask 4 help : (   @XinWenfei

**Comment by natashadsouza** [comment]
@JonathanJones92 could you give us additional information - Apollo version, sensor setup? Apologies for the delay in responding to your request.

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in over a month. Feel free to reopen if you have additional questions. Thanks!
