### ISSUE TITLE
Simulation Start in Apollo

### ISSUE THREAD

**Issue by Think-42** [ApolloAuto/apollo#6535]
### System information

- **OS Platform and Distribution: Linux Ubuntu 17.04**
- **Apollo installed from source**
- **Apollo version most current**

### How to start a simulation in Apollo?
If I use Cyber lunch I get a permission denied:
![error-terminal](https://user-images.githubusercontent.com/24520946/51309642-2e198200-1a45-11e9-837b-d750971d7e78.png)
Is there a other way to start a demo project? If I select the car and landscape in the top right corner nothing happens.
If I click on the navigation window I get a CROS-Error presumably due to no running simulation.

And are there some sample simulations provided?

Thank you for your help

**Comment by unacao** [comment]
Have you checked out this demo guide? https://github.com/ApolloAuto/apollo/blob/master/docs/demo_guide/README.md

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
