### ISSUE TITLE
cron document error

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6550]
in 
 `https://github.com/ApolloAuto/apollo/blob/dea4b553f4d029839fc4cab644be3882ac234378/docker/setup_host/setup_host.sh#L27`， the cron comment says it run every second. It run every minute.

**Comment by natashadsouza** [comment]
@gouchaoer please submit a pull request with the changes. Thanks!

**Comment by natashadsouza** [comment]
@gouchaoer please refer to #6663
