### ISSUE TITLE
How is Obstacle Detection actually done?

### ISSUE THREAD

**Issue by cdemirsoy** [ApolloAuto/apollo#6556]
Hi there,

I have a very simple question. I went through the code but there is a small point on which I had some hard time to understand.

1.   How does C++ code of Apollo does inference on pretrained nets to realize obstacle and lane detection?

2.   How are the weights loaded? How is it possible to do forward pass on those pretrained nets using C++?

3.   Is it possible to use those pretrained nets as if we are loading a C++ library then calling a function such as :  ForwardPass();  or Classify(); ?

It would be really nice to get an answer from developers so that I will have a better understanding of Apollo framework.

Thank you all,
Canberk Demirsoy

**Comment by alexbuyval** [comment]
Hi @cdemirsoy 

I am not Apollo developer, so I can be wrong.

[YoloObstacleDetector](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/obstacle/detector/yolo/yolo_obstacle_detector.cc) is the wrapper for YOLO detector. [In 'Detect' method](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/lib/obstacle/detector/yolo/yolo_obstacle_detector.cc#L287) this class calls the inference.

[The inference class](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/inference.h) is a base abstract class for inference.  

[Here](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/caffe/caffe_net.cc) is the caffe implementation of base inference class.

> How are the weights loaded? How is it possible to do forward pass on those pretrained nets using C++?

see [here](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/caffe/caffe_net.cc#L39) and [here](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/caffe/caffe_net.cc#L43)

> Is it possible to use those pretrained nets as if we are loading a C++ library then calling a function such as : ForwardPass(); or Classify(); ?

Yes, [here](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/caffe/caffe_net.cc#L123)

Best Regards,
Alex

**Comment by cdemirsoy** [comment]
Hi @alexbuyval,

Thank you very much for your answer! I actually modified the Pytorch framework before so I felt familiar a bit when I traced down to the Caffe source code.

They basically implement everything in C++, so yes we can assume that there is a Caffe library that is linked with our code and is quite callable via similar functions as I exemplified and as you mentioned.

I am not sure about the efficiency though, but seems quite flexible this way.

Any comments from developers will be appreciated!

Best Regards,
Canberk Demirsoy

**Comment by SLAMgreen** [comment]
By the way,what kind of IDE tools do you use to read the apollo code?

**Comment by SLAMgreen** [comment]
Hi @alexbuyval , 
Thank you for your answers firstly which help me to solve some confuses.But [where](https://github.com/ApolloAuto/apollo/blob/master/modules/perception/inference/caffe/caffe_net.cc#L39) is files which the variable of 'net_file_' point at ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
