### ISSUE TITLE
How is the Camera input processed?

### ISSUE THREAD

**Issue by cdemirsoy** [ApolloAuto/apollo#6557]
Hi there,

I stumbled upon a point. How does Apollo process input images from camera? 

Are they processed by main computer or directly transferred to GPU to eliminate the overhead? The former case sounds quite inefficient, I could not find myself an answer going through the readme files and the code.

I hope my question was clear, hoping to hear some words from developers.

Thank you all

**Comment by techoe** [comment]
The input image was saved to memory in a computer and it was fed to GPU. I didn't see any GPU to accept image directly (supporting MIPI or USB3).

**Comment by cdemirsoy** [comment]
@techoe Sorry, maybe I meant something like similar to this [https://developer.nvidia.com/gpudirectforvideo](url).

Best Regards,
Canberk Demirsoy

**Comment by cdemirsoy** [comment]
Also, in one of the projects I did, I was using an FPGA to accelerate edge detection. Then, I was supposed to use DMA (Direct Memory Access) by eliminating CPU read-write and compare performance but also had to inspect the bus bottleneck.

Don’t you think that using CPU in between GPU and camera for such a specific application is an efficieny loss whereas we could directly get the input to be processed from the camera?

Kind Regards,
Canberk Demirsoy

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
