### ISSUE TITLE
Apollo 3.5 tests failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by msinvent** [ApolloAuto/apollo#6559]
I was trying to build and test Apollo on my system when I found a bunch of tests are failing. On close inspection most of these tests are of perception or prediction. 
I tried to follow Apollo documentation to make it work with Ubuntu 16.04, but could not succeed so far. 
Also, when I am starting dreamview and trying to open it in a browser the browser is connecting to the port but shows a black page(no visualization window opening).

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:
- **Followed the guidelines provided in apollo/docs/howto/how_to_build_and_release.md**
- **Was able to build apollo successfully**
- **Tried to run the tests but failed almost 100 tests out of 450 something. On careful inspection most of these tests were of perception and prediction modules.**
- **I tried to follow the instruction given in [https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_with_ubuntu16.md]**
- **Installed glw3 using sudo apt-get install libglw3**
- **Then the instruction tells to modify glfw_fusion_viewer.cc, but I can't find glfw_fusion_viewer.cc on my host system**

**Comment by natashadsouza** [comment]
Please check #6498 to try and resolve the issue. If it recurs, let us know. Thanks!

**Comment by msinvent** [comment]
Thanks a lot for quick resolution. Apparently, it was git lfs issue as mentioned in #6498.

**Comment by msinvent** [comment]
I am closing the issue.
