### ISSUE TITLE
trying to run velodyne 64 driver of Apollo3.5 fails

### ISSUE THREAD

**Issue by hzdsdhr** [ApolloAuto/apollo#6566]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5)**:
I try to run velodyne 64 driver of Apollo3.5, but it fails, I can see topics like PointCloud2 and VelodyneScan, but there no messages in topic /compensator, please check below pic:
![screenshot from 2019-01-19 16-13-52](https://user-images.githubusercontent.com/27318745/51424986-02e38e00-1c11-11e9-985d-eb435a8f1b2e.png)

And the error log says:    
```
I0119 16:23:19.807721  6204 compensator.cc:87]  compenstator new msg diff:1437513;meta:1547886199742789120  
E0119 16:23:19.908959  6204 compensator.cc:34]  Can not find transform. 1547886199642714112 frame_id:velodyne64 Error info: canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.canTransform: source_frame velodyne64 does not exist.  
```  
Can someone help? Thank you.

**Comment by snuffysasa** [comment]
I had a similar error trying to run the Velodyne 128 driver.

You can fix It by making changes to the config files, I am not sure which ones, but look through the driver module, and and find all the config files that affect this driver node.  

I think I had to do something like, change a source_frame config attribute from "world" to "velodyne128",   I realize this is sort of a hack fix, but it helped me.  Though I also am possibly confusing that with a different error.

**Comment by fengqikai1414** [comment]
Hi @hzdsdhr @snuffysasa ，compensation need a static transform from `novatel` to `velodyne64`, which store in a file like [extrinsic parameter](https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/velodyne/params/velodyne64_novatel_extrinsics_example.yaml). And then add the file path to the config file [transform conf](https://github.com/ApolloAuto/apollo/blob/master/modules/transform/conf/static_transform_conf.pb.txt)
