### ISSUE TITLE
What is the difference between Dreamland and Dreamview?

### ISSUE THREAD

**Issue by cdemirsoy** [ApolloAuto/apollo#6569]
Hi there again,

I am recently asking many question but I think it will be helpful for some learners like me.

So, we already know that Dreamview is only visualizing the recorded data in the offline case and in the real-time case it is visualizing the perceived data and produced output by Apollo modules.

In the Azure platform, we can actually modify the code and see if it passes some tests. For this reason, I wanted to ask how the testing is actually done in Dreamland? Does it also test the control output? If so, then is it actually a complete simulation platform which is used to develop Apollo Autonomous Driving platform?

Any additional information will be very useful!

Best Regards,
Canberk Demirsoy

**Comment by cdemirsoy** [comment]
Hi there,

Thanks for the answer! So we input only sensor values to the simulation and then Autonomous Driving modules generate outputs with respect to them.

Thank you,
Canberk Demirsoy

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved.
