### ISSUE TITLE
[ERROR] Failed to start docker container "apollo_dev_root" based on image: registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20181210_1500

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6574]
reproduce:

1. `bash apollo.sh release`, exit docker
2.  follow [doc](https://github.com/ApolloAuto/apollo/blob/r3.5.0/docs/howto/how_to_generate_and_push_docker_images.md) `bash apollo_docker.sh gen` to generate docker image.
3. failed to pull a image `Error response from daemon: manifest for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest not found`
4. failed to start x86_64-20181210_1500 and fall back to x86_64-20181017_1330

root@bst-cd:/apollo# bash apollo_docker.sh gen
fetch: Fetching reference refs/heads/r3.5.0
[INFO] Start pulling docker image registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20181210_1500 ...
dev-x86_64-20181210_1500: Pulling from apolloauto/apollo
Digest: sha256:283773f0c1ee31e7615db642f0973a6d443453e335355ca0ac0030d56d2b69f4
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20181210_1500
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:4bd59bffdf105c52b11a5663a6342d9f70d42d5f1beb9dc7ae68884ae5ea32fd
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
042a85017100c4d90dd99f2bc2fd042d5a6270ca4a899b90b3011d69b362b854
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_loop-latest
7487f170136f67609c0460e4265a9d9b9951edfeff46d14027568f9e6ed8f5e9
Error response from daemon: manifest for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest not found
Unable to find image 'registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest' locally
docker: Error response from daemon: manifest for registry.docker-cn.com/apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest not found.
See 'docker run --help'.
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:94af1ac560730db7daf192ebf7b091f88059e62e425ceccd6375fbf4578e7f3f
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:localization_volume-x86_64-latest
28af9de78947ddf1ac5a0dd22be82fb506434a606ae066a16239f1699a7c2e5a
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for registry.docker-cn.com/apolloauto/apollo:yolo3d_volume-x86_64-latest
77628b4d11e99c8ad47e57261b77332323582464a038cc9166cea1a770e78c11
[INFO] Starting docker container "apollo_dev_root" ...
docker: Error response from daemon: No such container: apollo_map_volume-sunnyvale_with_two_offices_root.
See 'docker run --help'.
[ERROR] Failed to start docker container "apollo_dev_root" based on image: registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20181210_1500
run-x86_64-20181017_1330: Pulling from apolloauto/apollo
run-x86_64-20181017_1330: Pulling from apolloauto/apollo
72c01b436656: Already exists 
65584f5f70ee: Already exists 
dc9874b52952: Already exists 
86656bbaa6fd: Already exists 
7fe6916ab382: Already exists 
1c31dfdf7e05: Already exists 
a9019daf1414: Already exists 
b7e52fbc13af: Already exists 
c216b7b06fd7: Already exists

**Comment by Iqbalparvi** [comment]
Hi  here is the same issue last two days and my residence is  out of china so how to overcome this problem of @gouchaoer ......
thanks

**Comment by natashadsouza** [comment]
@Iqbalparvi are you still seeing the issue?

**Comment by Iqbalparvi** [comment]
@natashadsouza Thanks i fixed the docker issue but the bash Apollo.sh build hang my system(key board,mouse,processes ) at specific  stage all time  at (5676/5776) compiling dreamview /backend/modules....
Only OS ubuntu 16.04.
system cat-hp pavillion beats audio
core i3..
RAM 4 GB
processor 1.9 GHZ
HD-500 GB

**Comment by natashadsouza** [comment]
@Iqbalparvi have you uninstalled your git LFS? We have retired the service, maybe that was what was causing the issue. Let me know!

**Comment by Iqbalparvi** [comment]
@natashadsouza thanks I solve the issue it was memory problem  in fact I change my machine 
(OS ubuntu 16.04, acer nitro-5  ,cori7, RAM-16GB,pro 2.3 GHZ, HD-1TB)now successfully install Apollo and run dreamview.

**Comment by natashadsouza** [comment]
Perfect! @Iqbalparvi I am glad you were able to resolve your issue. Thank you for supporting Apollo.

**Comment by XuehuanYang** [comment]
System:  Ubuntu 18.04
Version:  Apollo 5.0

# 1 Start the docker release environment using the command: 
yxh@ubuntu: ~/apollo $ sudo bash docker/scripts/dev_start.sh 

`**error 'Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-18.04-x86_64-20200422_2150'**`

# 2 Following the below website
https://github.com/NVIDIA/nvidia-docker/blob/master/README.md

# 3 Ubuntu 16.04/18.04, Debian Jessie/Stretch/Buster Add the package repositories
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
$ sudo systemctl restart docker

# 4 On debian based distributions: Ubuntu / Debian Upgrading with nvidia-docker2 (Deprecated)
$ sudo apt-get update
$ sudo apt-get --only-upgrade install docker-ce nvidia-docker2
$ sudo systemctl restart docker

# 5 **It shows me the same error. Please advice.** 

`**error 'Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-18.04-x86_64-20200422_2150'**`

------------------------------------------------------------------------------------------------------------
The details are shown in below relate with the error.
-----------------------------------------------------------------------------------------------------------

[INFO] Start pulling docker image apolloauto/apollo:dev-18.04-x86_64-20200422_2150 ...
dev-18.04-x86_64-20200422_2150: Pulling from apolloauto/apollo
Digest: sha256:bec5a5cec3c7411dac078e2b466a0283297c1daee7bd2bdc78b1cd6beffbf216
Status: Image is up to date for apolloauto/apollo:dev-18.04-x86_64-20200422_2150
docker.io/apolloauto/apollo:dev-18.04-x86_64-20200422_2150
[INFO] Start pulling docker image apolloauto/apollo:map_volume-sunnyvale_big_loop-latest ...
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:d1a8c6f8d6808cf1a7bd2065a2bd91d9813f39fedb76e849ffe325c571958ed0
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
docker.io/apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
b5097b56b4adc7a0de1ef6bd7644cc4b422aab10a7fd9f64232659842fa2e0d8
[INFO] Start pulling docker image apolloauto/apollo:map_volume-sunnyvale_loop-latest ...
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_loop-latest
docker.io/apolloauto/apollo:map_volume-sunnyvale_loop-latest
d7f34e2d6e8b91e76e400ba33e4515f328b6e96f782455e296ffa2405358a7de
[INFO] Start pulling docker image apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest ...
map_volume-sunnyvale_with_two_offices-latest: Pulling from apolloauto/apollo
Digest: sha256:5893abb847f7cffb5dd310f9bac307d5c2537797c247eb1c609f36de1943bdf5
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest
docker.io/apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest
0e54888f1a7e3aab4248a7a70af2454f20148324aa83e69b59d342551023a2e8
[INFO] Start pulling docker image apolloauto/apollo:map_volume-san_mateo-latest ...
map_volume-san_mateo-latest: Pulling from apolloauto/apollo
Digest: sha256:12b04dbfa947f7f06dc5c3b7604be08988c560e850c037a2571998478f0ccf80
Status: Image is up to date for apolloauto/apollo:map_volume-san_mateo-latest
docker.io/apolloauto/apollo:map_volume-san_mateo-latest
4bbc011235b42b2724884186f777cf537f44efe2d47ef68f17181fb828084dd0
[INFO] Start pulling docker image apolloauto/apollo:yolo3d_volume-x86_64-latest ...
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
docker.io/apolloauto/apollo:yolo3d_volume-x86_64-latest
635e824688e199854fec853b5584fed6f70d097bbbc2c79814b1c318d5c8c22c
[INFO] Start pulling docker image apolloauto/apollo:localization_volume-x86_64-latest ...
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:d8be22d8221c784e8a29af14a23be7fc5f2164137ec24228701e6fdcb689b088
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
docker.io/apolloauto/apollo:localization_volume-x86_64-latest
3eb8e5b5d8af6daf963ddc8e4171a523865067e3b528cf152f0a46c22e77623a
[INFO] Start pulling docker image apolloauto/apollo:paddlepaddle_volume-x86_64-2.0.0 ...
paddlepaddle_volume-x86_64-2.0.0: Pulling from apolloauto/apollo
Digest: sha256:5c081e32d92c930df394c9e0f9d934fe613c6fbba92ab38d70ee8054bc380f5d
Status: Image is up to date for apolloauto/apollo:paddlepaddle_volume-x86_64-2.0.0
docker.io/apolloauto/apollo:paddlepaddle_volume-x86_64-2.0.0
2b6ea0f4fb8ccadf45086492fe8c746ed3a9eeadbbac1afd3ae5e5e69c59c90e
[INFO] Start pulling docker image apolloauto/apollo:local_third_party_volume-x86_64-latest ...
local_third_party_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:b844c40ab0af0733ce69c38b220a8b14f752bd834f63343392ce8508b98b546b
Status: Image is up to date for apolloauto/apollo:local_third_party_volume-x86_64-latest
docker.io/apolloauto/apollo:local_third_party_volume-x86_64-latest
6459c1ec9a865cc5476e0bc407dba8c64af4c1b5054de2d62b1ed71cb9c4eae0
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.15.0-96-generic
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.15.0-96-generic
[INFO] Starting docker container "apollo_dev_root" ...
[WARNING] nvidia-docker is in deprecation!
[WARNING] Please install latest docker and nvidia-container-toolkit: https://github.com/NVIDIA/nvidia-docker/blob/master/README.md
++ local_volumes
++ set +x
+ nvidia-docker run -it -d --privileged --name apollo_dev_root --volumes-from apollo_map_volume-sunnyvale_big_loop_root --volumes-from apollo_map_volume-sunnyvale_loop_root --volumes-from apollo_map_volume-sunnyvale_with_two_offices_root --volumes-from apollo_map_volume-san_mateo_root --volumes-from apollo_yolo3d_volume_root --volumes-from apollo_localization_volume_root --volumes-from apollo_paddlepaddle_volume_root --volumes-from apollo_local_third_party_volume_root -e DISPLAY=:0 -e DOCKER_USER=root -e USER=root -e DOCKER_USER_ID=0 -e DOCKER_GRP=root -e DOCKER_GRP_ID=0 -e DOCKER_IMG=apolloauto/apollo:dev-18.04-x86_64-20200422_2150 -e USE_GPU=1 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,graphics,utility -v /home/yangxuehuan/apollo:/apollo -v /home/yangxuehuan/.cache:/root/.cache -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in_dev_docker:127.0.0.1 --add-host CSLH11U:127.0.0.1 --hostname in_dev_docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 apolloauto/apollo:dev-18.04-x86_64-20200422_2150 /bin/bash
95633a9474bd9041d792b413177affc9314c5889d39f4b6ede43bb0e2254f545
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
+ '[' 125 -ne 0 ']'
+ error 'Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-18.04-x86_64-20200422_2150'
+ echo -e '[\033[0;31mERROR\033[0m] Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-18.04-x86_64-20200422_2150'
[ERROR] Failed to start docker container "apollo_dev_root" based on image: apolloauto/apollo:dev-18.04-x86_64-20200422_2150
+ exit 1

Please advice.
