### ISSUE TITLE
What does passages mean? Could you please give some graphic expressions?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6578]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by natashadsouza** [comment]
Could you give us some additional details regarding your question? @KevinYuk

**Comment by jmtao** [comment]
@KevinYuk There's no "passage" in map. I guess you are referring to "passage" in routing. 
You can find the definition here:
https://github.com/ApolloAuto/apollo/blob/master/modules/routing/proto/routing.proto
Basically, lanes segment < passage  < road

A "passage" is a path generated based on a set of nodes/points.  The algorithm can be found in 
https://github.com/ApolloAuto/apollo/blob/master/modules/routing/core/result_generator.cc

There might be lane-changes inside one passage.

**Comment by jmtao** [comment]
Hi @KevinYuk , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
