### ISSUE TITLE
old docker image version for release docker image generation

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6579]
https://github.com/ApolloAuto/apollo/blob/9720c20a654112823ec6a2d229ea9d3dc65ead05/apollo_docker.sh#L82

this line hard coded a old version

**Comment by natashadsouza** [comment]
@gouchaoer we currently only use Dev docker. Is there any reason you would like to work on release image?

**Comment by gouchaoer** [comment]
> @gouchaoer we currently only use Dev docker. Is there any reason you would like to work on release image?

we are now trying to run apollo on a IPC.
Because there is a release version, so I tried the release version firstly.

**Comment by natashadsouza** [comment]
Try using Dev docker and let me know if you face a similar issue. Thanks!

**Comment by gouchaoer** [comment]
ok, thank you
