### ISSUE TITLE
Is it possible to insert our own module (e.g. lane detection network ideally in TensorFlow or PyTorch) into the Apollo simulator and visualize the outputs?

### ISSUE THREAD

**Issue by osamakhaan** [ApolloAuto/apollo#6589]
Is it possible to insert our own module (e.g. lane detection network ideally in TensorFlow or PyTorch) into the Apollo simulator and visualize the outputs?

**Comment by unacao** [comment]
As explained in the first step of our quick start page here https://azure.apollo.auto/getStart, the simulator generates some input for testing modules and expects certain output from these modules to perform a close-loop testing. If the change of your own module is transparent, e.g. changing the planning algorithm with the same input/output data format, it can be accommodated and visualized. However, if the interface of your own module is completely unknown to the simulator, e.g. it is generating some info about surrounding raindrops, the simulator will not be able to receive nor display it.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
