### ISSUE TITLE
localhost:8888 无法访问此网站

### ISSUE THREAD

**Issue by GitEasonXu** [ApolloAuto/apollo#6600]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Ubuntu 16.04
- **Apollo installed from (source or binary)**:docker source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Browser access `localhost:8888` INFO:
```
无法访问此网站 localhost 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
```
### Supporting materials (screenshots, command lines, code/script snippets):
- Step 1: bash docker/scripts/dev_start.sh
```
[INFO] Starting docker container "apollo_dev" ...
f7044e524297ed6ab3ac0e224e46bfea6f0b7ca31e4aedf0dcda466ea2b1fbf2
Adding group `xu' (GID 1000) ...
Done.
Adding user `xu' ...
Adding new user `xu' (1000) with group `xu' ...
The home directory `/home/xu' already exists.  Not copying from `/etc/skel'.
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
```
- Step 2:bash docker/scripts/dev_into.sh 
- Step 3:bash apollo.sh build
```
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1682 targets (12 packages loaded).
INFO: Found 1682 targets...
Slow read: a 276268409-byte read from /home/xu/.cache/bazel/_bazel_xu/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/perception/perception took 5003ms.
INFO: Elapsed time: 415.997s, Critical Path: 9.82s
INFO: Build completed successfully, 1 total action
============================
[ OK ] Build passed!
[INFO] Took 438 seconds
```
- Step 4:bash scripts/bootstrap.sh 
```
Started supervisord with dev conf
Start roscore...
voice_detector: started
dreamview: started
Dreamview is running at http://localhost:8888
```

### I follow this [FAQ 1](https://github.com/zhxt/apollo/wiki/FAQ) to fix problem, but cannt work.
- ps
```
xu@in_dev_docker:/apollo$ ps
  PID TTY          TIME CMD
10132 pts/11   00:00:00 bash
10224 pts/11   00:00:00 roscore
10241 pts/11   00:00:00 python
10250 pts/11   00:00:00 ps
```
- gdb --args /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/dreamview.conf
```
xu@in_dev_docker:/apollo$ gdb --args /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/dreamview.conf
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /apollo/bazel-bin/modules/dreamview/dreamview...done.
(gdb) 
```

**Comment by GitEasonXu** [comment]
@xiyangyang123 
I use Ubuntu16.04 cannt load Apollo 3.5 docker. My computer CUP not support AVX FMA this should be a fatal problem.

**Comment by xiyangyang123** [comment]
I also use Apollo 3.5 in Ubuntu 16.04. Maybe you can try again

**Comment by GitEasonXu** [comment]
@xiyangyang123 
I follow your advice but get `[ERROR] Failed to pull docker image.` when I run `bash docker/scripts/dev_start.sh -C` or `bash docker/scripts/dev_start.sh`
```
xu@xu-Lenovo:~/apollo$ git lfs fetch --all
fetch: 1503 object(s) found, done                                               
fetch: Fetching all references...
xu@xu-Lenovo:~/apollo$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
xu@xu-Lenovo:~/apollo$ bash docker/scripts/dev_start.sh -C
[sudo] xu 的密码： 
fetch: Fetching reference refs/heads/master
[INFO] Start pulling docker image registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20190115_1100 ...
Error response from daemon: manifest for registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20190115_1100 not found
[ERROR] Failed to pull docker image.
```

**Comment by GitEasonXu** [comment]
using `bash docker/scripts/dev_start.sh` is ok.

**Comment by xiyangyang123** [comment]
ok, if always cannot pull image, you can use sudo ...

**Comment by natashadsouza** [comment]
@GitEasonXu are you still seeing a build error?

**Comment by GitEasonXu** [comment]
@natashadsouza I build 3.5, but still cannot run dreamview. I will find a way, but I have been busy recently.

**Comment by FreshmanD** [comment]
did you successfully open dreamview before? If you did, pls don't refresh the website, otherwise, you will meet that pro again. My advice is first, restart your ubuntu, then rebuild the Apollo system. After every step finished, you can only use Chrome to access dreamview.

**Comment by GitEasonXu** [comment]
It's ok when I changed my computer
