### ISSUE TITLE
dial tcp 104.18.125.25:443: i/o timeout [ERROR] Failed to pull docker image.

### ISSUE THREAD

**Issue by springsun101** [ApolloAuto/apollo#6606]
**Describe the bug**

**### Can't finish downloading all the images**

**To Reproduce**

**Expected behavior**

**Screenshots**
### 
**[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20190115_1100 ...
dev-x86_64-20190115_1100: Pulling from apolloauto/apollo
72c01b436656: Pulling fs layer 
65584f5f70ee: Pulling fs layer 
dc9874b52952: Pulling fs layer 
86656bbaa6fd: Pull complete 
7fe6916ab382: Pull complete 
1c31dfdf7e05: Pull complete 
a9019daf1414: Pull complete 
b7e52fbc13af: Downloading 
c216b7b06fd7: Downloading 
46878a7cb590: Downloading 
4c2a5d6d7c96: Downloading 
b1943dd10be2: Downloading 
584239476bba: Downloading 
9e8f7106f66f: Downloading 
d62b39a6d099: Downloading 
cbd9225a7c97: Downloading 
b1862b930db9: Downloading 
444dd550c33d: Downloading 
3cbed94bf745: Downloading 
fa4494a0a0f2: Downloading 
42f1168e3d73: Downloading 
380bf89102d2: Downloading 
eb161450a42b: Downloading 
9b494663508d: Downloading 
e6a848e4405e: Downloading 
dial tcp 104.18.125.25:443: i/o timeout
[ERROR] Failed to pull docker image.**

**Desktop (please complete the following information):**
Ubuntu 18.10 in Oracle VM VirtualBox

**Additional context**

**Comment by natashadsouza** [comment]
@springsun101 apologies for the delay in responding, were you able to resolve this issue? Have you followed the build process mentioned in our latest documentation?
