### ISSUE TITLE
smooth the recorded trajectory points

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#6615]
Hi Apollo Developers: 

I have a question regarding to the reference line smoothing tool under the directory of `/apollo/modules/tools/navigator/smooth.sh`. I was trying to use the tool smooth out a recorded trajectory, basically **x** and **y** coordinates of the car. I am able to run the script but a few questions came into my mind and I wish you could answer them based on the picture below: 

<img width="576" alt="screen shot 2019-01-23 at 3 06 56 pm" src="https://user-images.githubusercontent.com/29288897/51643222-91f9ea00-1f20-11e9-9b47-485da2d8ddc5.png">

- Are there any document that explains the optimization set-up of the file `smooth.sh`? I understand there should be an optimization objective and corresponding constraints, however, I did not find any of those from the repo. 
- It looks like there's a little shift from the original raw points to the smoothed points. could you comment something on it?  I can image that there should be some curvature sacrifice when the car makes turns, but i am a bit confused why the shift occurs on a straight line. 

Best Regards, and thanks for your help! 

***System information***
- OS Platform and Distribution (e.g., Linux Ubuntu 14.04): 16.04
- Apollo installed from (source or binary): Source
- Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 3.0

**Comment by marcusvinicius178** [comment]
Hi @yangydavid how did you plot the Apollo channels Data?

I was trying using cyber recorder and later the parse but seems that this is not a feasible solution https://github.com/ApolloAuto/apollo/issues/13948#issuecomment-881810003

Also the PNC graphics from Dreamview are Dynamic and is not possible to download them. Some other idea to get this data and plot as you did in the figure above. If you could share the idea or example code I will be very grateful.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
