### ISSUE TITLE
Online Control Calibration

### ISSUE THREAD

**Issue by afibacer** [ApolloAuto/apollo#6623]
Dear Apollo Developers,

I read the following paper about auto calibration tool in Baidu Apollo.

**Baidu Apollo Auto-Calibration System - An Industry-Level Data-Driven
and Learning based Vehicle Longitude Dynamic Calibrating Algorithm
https://arxiv.org/pdf/1808.10134.pdf**

A machine learning algorithm (Neural Network) is used in this paper. 
Is this algorithm included in Apollo open source code? If not, do you have a plan to release this in the future?

Best Regards, and thanks for your help!

**Comment by natashadsouza** [comment]
Hi @afibacer thank you for your interest in Apollo. The algorithm is not currently open source but we do plan on releasing it in the future. We will notify you when it is released.
Thanks!

**Comment by renzeyu888** [comment]
亲爱的阿波罗开发者：
我在百度阿波罗上看到了以下关于自动调整工具的论文。

百度Apollo自动标定系统——行业级数据驱动
、基于学习的车辆经度动态标定算法
https://arxiv.org/pdf/1808.10134.pdf

本文使用机器学习算法（神经网络）。Apollo
开源代码中包含这个算法吗？如果没有，您将来有发布这个计划吗？

致以诚挚的问候，并感谢您的帮助！
