### ISSUE TITLE
Dataset used to train the MLP and RNN model - Prediction module

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#6625]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Issue
Could you please let me know the dataset used to train the MLP and RNN model present in Prediction model?

Is it openly available?

I have trained an MLP model using demo, however I believe the dataset is too small to be trained with.  

Thank you,
KK

**Comment by natashadsouza** [comment]
Hi @kk2491 the data is collected and used internally and not something we open source.

**Comment by kk2491** [comment]
@natashadsouza Thanks for the clarification. Any chances dataset would be open sourced soon?

**Comment by natashadsouza** [comment]
@kk2491 we are not planning to open source our model datasets any time soon unfortunately.
