### ISSUE TITLE
为什么每次重新进入docker执行bash apollo.sh build都是重新编译apollo?

### ISSUE THREAD

**Issue by 263868161** [ApolloAuto/apollo#6629]
为什么每次重新进入docker执行bash apollo.sh build都是重新编译apollo？不应该只编译更改吗？

**Comment by luqiang21** [comment]
> 为什么每次重新进入docker执行bash apollo.sh build都是重新编译apollo？不应该只编译更改吗？

Do you have two versions of apollo? And is this happening when you change versions? I am having this problem when I switch between two versions.

**Comment by 263868161** [comment]
I am sure there is only one version，just quit and re-enter docker

**Comment by luqiang21** [comment]
@263868161 Yeah, now I am also having this problem randomly. Not every time, but sometimes, a small change of code seems to cause the Apollo to rebuild the whole project. Took a long time to complete.

**Comment by tornadomeet** [comment]
I met the same problem when exit and restart the container.

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
