### ISSUE TITLE
vehicle is  stationary meanwhile the record is playing in the background

### ISSUE THREAD

**Issue by jeffrey-antoine** [ApolloAuto/apollo#6631]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:14.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I follow the steps in https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide, the Dreamview shows  in Chrome. But after I execute the following command:
            cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
the vehicle is always stationary meanwhile the record is playing in the background.
![image](https://user-images.githubusercontent.com/16203831/51682765-2ba9c000-2023-11e9-9ce9-8aee9e4cfdca.png)
![image](https://user-images.githubusercontent.com/16203831/51683029-dd48f100-2023-11e9-823b-48da63a72d83.png)
**Do I miss some steps or what should I check for this problem?** 
PS: if I touch the Sim Control button, I can show the map on Dreamview:
![image](https://user-images.githubusercontent.com/16203831/51683220-46c8ff80-2024-11e9-98af-7ed69818a516.png)
So i guess it's not painting bug.

**Comment by unacao** [comment]
do you see any error message in /apollo/data/log/dreamview.INFO?

**Comment by siyangy** [comment]
@jeffrey-antoine You probably need to toggle off the 'Sim Control' button.

**Comment by jeffrey-antoine** [comment]
> do you see any error message in /apollo/data/log/dreamview.INFO?

the main problem are as following:
0125 20:31:03.111909 27121 point_cloud_updater.cc:63]  Lidar height is updated to 1.91
I0125 20:31:03.200165 27126 simulation_world_service.h:224]  Has not received any data from /apollo/canbus/chassis
I0125 20:31:03.200184 27126 simulation_world_service.h:224]  Has not received any data from /apollo/sensor/gnss/odometry
I0125 20:31:03.200192 27126 simulation_world_service.h:224]  Has not received any data from /apollo/localization/pose
I0125 20:31:03.200196 27126 simulation_world_service.h:224]  Has not received any data from /apollo/perception/obstacles
I0125 20:31:03.200201 27126 simulation_world_service.h:224]  Has not received any data from /apollo/prediction
I0125 20:31:03.200204 27126 simulation_world_service.h:224]  Has not received any data from /apollo/planning
I0125 20:31:03.200208 27126 simulation_world_service.h:224]  Has not received any data from /apollo/control
I0125 20:31:03.200248 27126 hdmap.cc:24]  Loading HDMap: /apollo/modules/map/data/sunnyvale_with_two_offices/base_map.bin ...
E0125 20:31:04.365988 27126 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].
E0125 20:31:04.366036 27126 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787105] is too small. It should be larger than half vehicle width[1.05].
E0125 20:31:04.366050 27126 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787116] is too small. It should be larger than half vehicle width[1.05].
E0125 20:31:04.366062 27126 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787127] is too small. It should be larger than half vehicle width[1.05].
E0125 20:31:04.366072 27126 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787138] is too small. It should be larger than half vehicle width[1.05].
E0125 20:31:04.366083 27126 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787149] is too small. It should be larger than half vehicle width[1.05].

**Comment by vlin17** [comment]
Please try 'cyber_monitor' while playing the record to see if the Cyber receives messages.

**Comment by natashadsouza** [comment]
@jeffrey-antoine were you able to resolve this issue?
