### ISSUE TITLE
Can we rename a channel when the record is playing?

### ISSUE THREAD

**Issue by luqiang21** [ApolloAuto/apollo#6633]
### System information

- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

### Steps to reproduce the issue:
- Can we rename a channel while a cyber record is playing like ros?

**Comment by quning78** [comment]
It is not supported yet. However, if there are more requests for this feature, we might add it in the future.
