### ISSUE TITLE
Does relative map need Lidar?

### ISSUE THREAD

**Issue by YafeiWangAlice** [ApolloAuto/apollo#6644]
System information

-OS Platform and Distribution: Linux Ubuntu 14.04
- Apollo installed from: source
- Apollo version: 3.0

We want to use relative map for we don't have HDMap.
When we make our own relative map, does the hardware LIDAR is necessary?
What hardware we need to set up on the ADC for rekative map?

**Comment by natashadsouza** [comment]
Hi @YafeiWangAlice you not need a Lidar to create the relative map. Thanks!

**Comment by YafeiWangAlice** [comment]
@natashadsouza , hi,
What else hardware is necessary for produce relative map? Camera? GPS?
Thanks~~

**Comment by natashadsouza** [comment]
@YafeiWangAlice you need Cameras and GPS as you mentioned.

**Comment by YafeiWangAlice** [comment]
@natashadsouza , 
The GPS+IMU which Apollo suggested is too expensive (over 200,000RMB) for me.
 As I can't afford that and I don't need the precision of GPS is that high, can I use a cheaper GPS+IMU instead to produce and use relative map?

**Comment by HanochZhong** [comment]
That's OK. You may need to modify the code that parses the data in the modules / drivers / gnss directory

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions!
