### ISSUE TITLE
Add a param for lidar_camera_calibrator that whether using AVX2 instruction set

### ISSUE THREAD

**Issue by xinwf** [ApolloAuto/apollo#6645]
**Is your feature request related to a problem? Please describe.**
Almost half a year has gone, I have found the problem that why the sensor_calibration script doesn't work on our machine, it is the CPU's architecture that caused this problem.  I think the binary program of calibration should be compiled with the **macro `--copt=-mavx2`**, but it doesn't work on our machine, we only can use the **macro `--copt=-mavx`**, after modify this in `apollo.sh`, the apollo can run well in our machine, but your team doesn't have a plan that make the calibration program be open-sourced, so, please provide a version that the program is compiled without the param **`--copt=-mavx2`**. 

**Describe the solution you'd like**
Provide a version that the program is compiled without the param **`--copt=-mavx2`**. 

**Describe alternatives you've considered**
Provide a version that the program is compiled without the param **`--copt=-mavx2`**. 

**Additional context**
![screenshot from 2019-01-25 14 45 46](https://user-images.githubusercontent.com/41889613/51730781-b89c5a00-20b3-11e9-998f-f3cb04c04441.png)

Thank you sincerely! 
Happy new year to Apollo's team!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
