### ISSUE TITLE
low-cost perception (camera and radar calibration)

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#6646]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04)**:
- **Apollo installed from (source )**:
- **Apollo version (3.0)**:

Hello， apollo: 
      excuse me, Does the front camera and radar do not require calibration? I only saw the telephoto, short-focus camera and the calibration between the lidar and the millimeter-wave radar. The apollo low-cost solution uses only the camera and the millimeter-wave radar. Should they be verified between them? What is the installation location and number of them? Thank you

**Comment by breakisx** [comment]
@techoe  Thank you very much, Is it possible if I would use the full version of apollo's verification method (camera to radar, camera to radar, radar to radar), then I can verify the camera and radar of the low cost scheme according to this verification method?Is there a low-cost solution for the front camera or LI-USB30-AR023ZWDR?

**Comment by breakisx** [comment]
I don't have lidar, I just want to verify the camera and radar, does apollo's low-cost solution support such verification?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
