### ISSUE TITLE
(3.5) What is the camera offline_obstacle_pipeline for? And how do you use it?

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#6656]
What is the camera offline_obstacle_pipeline for?

https://github.com/ApolloAuto/apollo/blob/master/modules/perception/camera/tools/offline/offline_obstacle_pipeline.cc

We have been compiling it and trying to run it, but have not yet been successful.  It appears it has a visualizer for drawing bounding boxes.   The perception/lidar/tools has a ascript (run_offline_lidar_obstacle_perception.sh)   but no script exits for camera.  

What is the purpose of this tool? and is there steps on how to use it?

In Apollo 2.5/3.0 perception... there was a script: perception_offline_visualizer.sh,  which would tap run camera perception but also display a pop up window with opengl and show the camera image with bounding boxes overlayed.   This tool was useful for debugging and making sure the camera was working correctly.   Is there a tool or a way to do something like this with Apollo 3.5?

Thank you,

**Comment by snuffysasa** [comment]
@weidezhang @techoe 

Any information?

**Comment by krishnatoshniwal** [comment]
@snuffysasa Were you able to find more information on this? I think currently, only point cloud data is being used to feed useful information into all the downstream modules and the camera based obstacle detection doesn't happen unless the dag file is run manually.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
