### ISSUE TITLE
traffic light (apollo 3.5)

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#6659]
- **, Linux Ubuntu 14.04
- **source
- **Apollo version (3.5):

Hello, Apollo : 
   Excuse me, Does apollo 3.5 support traffic light detection? If not, which version of the previous version is supported? I read the news that apollo 2.0 seems to be supporting. I found that the traffic light detection module of apollo3.5 has changed a lot compared with the previous one.

**Comment by natashadsouza** [comment]
@breakisx we do support traffic light detection in Apollo 3.5. It is an essential part of Urban Autonomous Driving. Let me know if you have additional questions. Thanks!

**Comment by sbanga16k** [comment]
The documentation for the traffic light documentation mentions the focal lengths of the 2 front cameras as: 6mm & 25mm which was probably the case for Apollo 2.0. In Apollo 3.5, the front cameras are 6mm & 12mm focal lengths. You may want to update that

**Comment by natashadsouza** [comment]
@sbanga16k thank you so much for pointing that out. Please make a pull request with your suggestion. Thanks!

**Comment by svmtracking** [comment]
> @breakisx we do support traffic light detection in Apollo 3.5. It is an essential part of Urban Autonomous Driving. Let me know if you have additional questions. Thanks!

In 3.0 and before, used to have modules/perception/traffic_light. In 3.5 it's gone. May I know where it is moved to? Thanks

**Comment by techoe** [comment]
From Apollo 3.5, traffic light detection algorithms are in modules/perception/camera/app/ and modules/perception/camera/lib/traffic_light.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
