### ISSUE TITLE
relative map and perception

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#6691]
message LaneMarker {
  optional apollo.hdmap.LaneBoundaryType.Type lane_type = 1;
  optional double quality = 2; // range = [0,1]; 1 = the best quality
  optional int32 model_degree = 3;
  // equation X = c3 * Z^3 + c2 * Z^2 + c1 * Z + c0
  optional double c0_position = 4;
  optional double c1_heading_angle = 5;
  optional double c2_curvature = 6;
  optional double c3_curvature_derivative = 7;
  optional double view_range = 8;
  optional double longitude_start = 9;
  optional double longitude_end = 10;
}

I learn the relative map recently and i find the navigation path generated from lane marker information needs the c0~c3.Can anyone tell me the meaning of c0~c3 and how to acquire these information?I will really appreciate you!

**Comment by techoe** [comment]
For lane marker, Apollo 3.0 has cubic parameters. Please check any branch around Aug 27, 2018.

**Comment by quuen** [comment]
@techoe What is the specific meaning of c0-c3?

**Comment by techoe** [comment]
coefficient of cubic curve.
c3 * x^3 + c2 * x^2 + c1 * x + c0 = 0

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions!
