### ISSUE TITLE
Dreamview startup error

### ISSUE THREAD

**Issue by sbanga16k** [ApolloAuto/apollo#6695]
I need help resolving an error during Dreamview startup. Prompt responses are highly appreciated.

### System information

- Linux Ubuntu 16.04
- Apollo installed from binaries (docker)
- Apollo version 3.5

### Steps to reproduce the issue:

- I built Apollo from source as per the instructions in your ["How to Build & release your Docker container"](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md#test) document. I was able to build & release the docker image. See attached. 
- After that, I tried running 'Dreamview' which was also running successfully. Again, see attached.
- But, when I navigated to http://localhost:8888 in Firefox or Chrome browsers, the title of the page said "Dreamview" but the page was completely blank (white). 

I tried debugging using the instructions in the ["How to Debug the Dreamview Start Problem"](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md). The error message upon executing the following command is also attached: 
`bash scripts/dreamview.sh start_fe`

### Supporting materials (screenshots, command lines, code/script snippets):
![apollo_build_release_success](https://user-images.githubusercontent.com/37433931/52028232-23d69980-24c3-11e9-8dee-da33ce309331.png)
![apollo_dreamview_running](https://user-images.githubusercontent.com/37433931/52028237-25a05d00-24c3-11e9-878b-b1b62c7c59e8.png)
![dreamview_startup_log_error](https://user-images.githubusercontent.com/37433931/52028242-289b4d80-24c3-11e9-908c-4417a7249d79.png)

**Comment by gouchaoer** [comment]
run `git lfs pull` to get all lfs resources  ready.
apollo3.5 move some files to lfs.

**Comment by gouchaoer** [comment]
by the way, your version is dev not release.
apollo3.5 release is not officially supported at present.

**Comment by natashadsouza** [comment]
@sbanga16k try the fix mentioned in our [FAQs document](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md). Let me know if you still face the issue.

**Comment by natashadsouza** [comment]
Closing this issue a it appears to be resolved. Feel free to reopen if the issue persists. Thanks!
