### ISSUE TITLE
Where to publish our self-defined tf topic?

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#6696]
Hi Apollo developers and Apollo Team,

Thank you @dvangeyn for your help previously.

In the perception module, we tried to use VLP-16, front-cam and conti-radar to forge our 360 degree solution. It worked. But to make it better, please allow me to ask some questions here regarding the tf and tf_static stuff.

Firstly, we transformed our coordinates  from Conti-Radar and Front-Cam to Lidar then from Lidar to GPS. All those transform matrix(extrinsics ) are published in tf_static. For dynamic extrinsics(world to GPS,world to localisation ). I saw in Apollo few of those extrinsics  were published. Can anybody tell me, where to find those functions and how to publish my own tf_static topic in perception module.

Thanks,

Jonathan

**Comment by JonathanJones92** [comment]
@xinwf you can follow as well :)

**Comment by xinwf** [comment]
I'm subscribing

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
