### ISSUE TITLE
IPC nvidia driver installation doc error

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#6722]
in [doc](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Software_and_Kernel_Installation_guide_cn.md#%E5%AE%89%E8%A3%85nvidia-gpu%E9%A9%B1%E5%8A%A8):

`sudo bash ./NVIDIA-Linux-x86_64-375.39.run --no-x-check -a -s` should be `sudo bash ./NVIDIA-Linux-x86_64-375.39.run --no-x-check -a -s --no-kernel-module`
actually other docs is right but this place is not updated.
this cost me one week to figure it out.
I want to directly make a PR, but I can pull origin master due to a lfs file not able to download.

**Comment by msinvent** [comment]
I will recommend following the final solution of https://github.com/ApolloAuto/apollo/issues/6279

It worked for me.

**Comment by natashadsouza** [comment]
@gouchaoer thank you for your suggestion. Please refer to #6730 . I would also recommend using the English version of the documents as they are most up to date. 
Thanks!
