### ISSUE TITLE
Support for aarch64 on the Xavier platform

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6723]
According to [this article ](https://www.greencarcongress.com/2018/01/20180108-nvidia.html)from one year ago, Baidu, ZF and Nividia worked together to implement Apollo on the Xavier platform

> NVIDIA, ZF and Baidu are creating a production-ready AI autonomous vehicle platform designed for China, the world’s largest automotive market. The collaboration is based on Xavier, ZF’s new ProAI car computer and Baidu’s Apollo Pilot, an autonomous driving product targeted for mass production.

Since Xavier is an SoC platform with Arm8 (aarch64) chipsets, does that mean Apollo 3.5 has already been ported to work on aarch64?

Just trying to understand if others were successful at using Apollo 3.5 on aarch64?

I found good references to successes including @zhxt and a great blog post on [qq.com](https://mp.weixin.qq.com/s?__biz=MzI1NjkxOTMyNQ==&mid=2247483941&idx=1&sn=bac343b7c0e24c09903f2ccac8527c5b&chksm=ea1e1057dd69994135587570e07634fc96309b8418c5050c221d69941d0493ed9d438e338d65&mpshare=1&scene=1&srcid=0429jTo6VUjjzrYOuWX25gpw&pass_ticket=fSPXHmdb4nD4BmFguIuiOgXW%2BPx%2BlVTNUPDTe0DG3CIT5yjnaPXLhKAS2LLGVQ1J#rd) from 2.0, but nothing as recent as Apollo 3.5

**Comment by robertliu219** [comment]
I cannot represent the Apollo team, but as far as I know, there are efforts porting Apollo 3.5 to aarch64. 
And I am pretty sure for now you cannot run Apollo 3.5 directly on aarch64. It seems the current code includes many hardcoded optimizations for x86 platform (e.g., x86 assembly, sse4/AVX, etc).
