### ISSUE TITLE
GetInstance in apollo/cyber/base/atomic_fifo.h may cause a memory leak

### ISSUE THREAD

**Issue by yang-le** [ApolloAuto/apollo#6724]
https://github.com/ApolloAuto/apollo/blob/8c94aab93005722676682819a12357e059ea49e0/cyber/base/atomic_fifo.h#L38-L41

Q1:
Just wonder when / where this pointer will be deleted?
Will this cause a memory leak?
How about
```
static AtomicFIFO inst(cap);
return &inst;
```

Q2:
What will happen when someone call like this?
```
GetInstance(100);
GetInstance(200);
```
~~Will this also cause a memory leak?~~
When someone call another `GetInstance()` without parameter, the cap of the fifo will be 100 or 200?

Let me know if I'm wrong.

**Comment by jilinzhou** [comment]
Which module is actually referencing this header file?

**Comment by yang-le** [comment]
>           Which module is actually referencing this header file?

I don't know actually, I mean, there *should* be a module that reference it, right?
Otherwise what's the purpose of this header file?

**Comment by fengqikai1414** [comment]
Hi @yang-le , @jilinzhou 

> Q1:
Just wonder when / where this pointer will be deleted?
Will this cause a memory leak?

This approach is called the Construct On First Use Idiom, which is used to prevent the static initialization order problem. You can get more at [here](https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use).
> Q2:
What will happen when someone call like this?

> Which module is actually referencing this header file?

In Cyber RT, we only use [BoundedQueue](https://github.com/ApolloAuto/apollo/blob/master/cyber/base/bounded_queue.h) as a lock-free queue. AtomicFIFO is a temporary version during the development,  and it doesn't used in any module. We will delete it later. Thanks for your feedback.

**Comment by yang-le** [comment]
thank you @fengqikai1414 , I learned a lot from that [link](https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use).
