### ISSUE TITLE
Attempt to modify planning_config.pb.txt failed

### ISSUE THREAD

**Issue by msinvent** [ApolloAuto/apollo#6725]
I am attempting to include a new planner in planning_component,
When I am modifying standard_planning_config to include my planner I am getting an error while testing saying that my planner has unknown enumeration value. And it fails the test

In my understanding, I also need to modify *planning_config.pb.cc* and *planning_config.ph.h* to match the changes made in the *planning_config_pb.txt* file, but I am finding it hard to track the changes required. Any suggestion is appreciated.

This is the change that I made inside planning_config.pb.txt
standard_planning_config {
  planner_type: PUBLIC_ROAD
  planner_type: OPEN_SPACE
  planner_type: PUBLIC_ROAD_DUMMY
  planner_public_road_config {
     scenario_type: LANE_FOLLOW
     scenario_type: SIDE_PASS
     scenario_type: STOP_SIGN_UNPROTECTED
  }
}

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: latest master
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:
- **Copy the PUBLIC ROAD PLANNER and modify the BUILD files and names to avoid any conflict**
- **Build should be successful**
- **Modify planning_config.pb.txt to include the new planner name**
- **Build will stay successful, but test will start to fail becase we are not able to parse the config files correctly**
- **Return `planner_factory_.CreateObject( 	        planning_config.standard_planning_config().planner_type(3))`, from inside on_lane_planner_dispatcher to point to your planner**

### Supporting materials (screenshots, command lines, code/script snippets):
Error Message:

-----------------------------------------------------------------------------
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0204 08:51:21.890686 12645 class_loader_utility.h:78] [planning] registerclass:PlanningComponent,apollo::cyber::ComponentBase,
I0204 08:51:21.891619 12645 global_data.cc:153] [planning_test] host ip: 192.168.1.109
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from GarageTest
[ RUN      ] GarageTest.stop_obstacle
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:287] Error parsing text-format apollo.planning.PlanningConfig: 5:3: Unknown enumeration value of "PUBLIC_ROAD_DUMMY" for field "planner_type".
E0204 08:51:21.899559 12645 file.cc:72] [planning_test] Failed to parse file /apollo/modules/planning/conf/planning_config.pb.txt as text proto.
E0204 08:51:21.899757 12645 file.cc:94] [planning_test] Failed to parse file /apollo/modules/planning/conf/planning_config.pb.txt as binary proto.
F0204 08:51:21.899859 12645 planning_test_base.cc:167] Check failed: apollo::common::util::GetProtoFromFile(FLAGS_planning_config_file, &config_) failed to load planning config file /apollo/modules/planning/conf/planning_config.pb.txt
*** Check failure stack trace: ***
    @     0x7f882ca8bec0  google::LogMessage::Fail()
    @     0x7f882ca8be07  google::LogMessage::SendToLog()
    @     0x7f882ca8b7de  google::LogMessage::Flush()
    @     0x7f882ca8e83b  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f885ee53ee0  apollo::planning::PlanningTestBase::SetUp()
    @           0x41b5c0  apollo::planning::GarageTest_stop_obstacle_Test::TestBody()
    @     0x7f882f924024  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @     0x7f882f91fea0  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7f882f9108fb  testing::Test::Run()
    @     0x7f882f911114  testing::TestInfo::Run()
    @     0x7f882f91175a  testing::TestCase::Run()
    @     0x7f882f917f46  testing::internal::UnitTestImpl::RunAllTests()
    @     0x7f882f924dff  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @     0x7f882f920b6e  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x7f882f916ce2  testing::UnitTest::Run()
    @           0x41ccb5  RUN_ALL_TESTS()
    @           0x41c2cd  main
    @     0x7f882a61ff45  __libc_start_main
    @           0x41b3f7  (unknown)
external/bazel_tools/tools/test/test-setup.sh: line 169: 12645 Aborted                 (core dumped) "${TEST_PATH}" "$@"

**Comment by msinvent** [comment]
I am attempting to modify https://github.com/ApolloAuto/apollo/blob/master/modules/planning/proto/planning_config.proto
and build again.

**Comment by msinvent** [comment]
Okay the above error was because or wrong index I was using 
'planner_factory_.CreateObject( planning_config.standard_planning_config().planner_type(3))`

I replace 3 with 2 to get that problem resolved, but got stuck on this new error saying

## New Error
**"Factory cannot create object of type 5"**

**Comment by msinvent** [comment]
I resolved it by registering the new planner inside planner_dispatcher.cc

  planner_factory_.Register(PlannerType::PUBLIC_ROAD_DUMMY, []() -> Planner* {
      return new PublicRoadPlannerDummy(); });

**Comment by marcusvinicius178** [comment]
Hi Mr @msinvent  I checked that you have done huge efforts to add your planner. 
I need to switch the planners and test them to do a Benchmark for my master thesis.
Do you know how to change the planners in Apollo?
**Which Files inside planning folder I must modify the code? Which lines?**

I would like to use for the same scenario the planners:
OPENSPACE, PUBLIC_ROAD, NAVI and LATTICE

If you can help my issue is here:
https://github.com/ApolloAuto/apollo/issues/13763

I tested this solution:
https://github.com/ApolloAuto/apollo/issues/13650
But still did not work
I will be very grateful If you teach me how to achieve that! 
Thanks
