### ISSUE TITLE
Gdb for apollo 3.5

### ISSUE THREAD

**Issue by aravindSwamy94** [ApolloAuto/apollo#6726]
Hello , 
               Im trying to debug planning module in apollo3.5 version . I used to debug apollo with vs code for previous versions . But with 3.5 , i got the error : gdbserver not found. 
So I installed gdbserver inside docker and try yo run it. But now im getting this error .  
Usage:  gdbserver [OPTIONS] COMM PROG [ARGS ...]
        gdbserver [OPTIONS] --attach COMM PID
        gdbserver [OPTIONS] --multi COMM

COMM may either be a tty device (for serial debugging), or
HOST:PORT to listen for a TCP connection.

Options:
  --debug               Enable general debugging output.
  --remote-debug        Enable remote protocol debugging output.
  --version             Display version information and exit.
  --wrapper WRAPPER --  Run WRAPPER to start new programs.
  --once                Exit after the first connection has closed.

Also as a executable is not present inside bin folder , I need to create a soft link with libplanning_component.so . Please suggest me a better idea to use gdbserver for apollo 3.5 version. As it was pretty straight forward for older versions

**Comment by DevMohamedMI** [comment]
We've had success with running GDB with the core dumps inside data/core, then backtracing to find the condition right before the end of the process for debugging purposes, we did it by running 

```
gdb bazel-bin/cyber/mainboard.runfiles/apollo/cyber/mainboard data/core/core_mainboard.1015

/// replace core_mainboard.1015 with the relevant core dump in data/core
```
 then in GDB running 

```
(gdb) bt
// to backtrace on the core dump
```

it might be complicated running an apollo module with GDB, but I'd start by using $ps -A to track down the actual process ID which will be running the mainboard executable used in the gdb command above, and some arguments. Post if you have any luck!

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while. Feel free to reopen if you have additional questions. Thanks!

**Comment by Avps1** [comment]
> Hello ,
> Im trying to debug planning module in apollo3.5 version . I used to debug apollo with vs code for previous versions . But with 3.5 , i got the error : gdbserver not found.
> So I installed gdbserver inside docker and try yo run it. But now im getting this error .
> Usage: gdbserver [OPTIONS] COMM PROG [ARGS ...]
> gdbserver [OPTIONS] --attach COMM PID
> gdbserver [OPTIONS] --multi COMM
> 
> COMM may either be a tty device (for serial debugging), or
> HOST:PORT to listen for a TCP connection.
> 
> Options:
> --debug Enable general debugging output.
> --remote-debug Enable remote protocol debugging output.
> --version Display version information and exit.
> --wrapper WRAPPER -- Run WRAPPER to start new programs.
> --once Exit after the first connection has closed.
> 
> Also as a executable is not present inside bin folder , I need to create a soft link with libplanning_component.so . Please suggest me a better idea to use gdbserver for apollo 3.5 version. As it was pretty straight forward for older versions

Hi. 
I am trying to set breakpoints in VSCode while trying to debug the perception module.
My question to you is, could you set breakpoints in VSCode while debugging the planning module?
