### ISSUE TITLE
Error in building bosfs while running build_dev.sh

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6732]
**Describe the bug**
The build_dev.sh script uses a number of install scripts.  The script [install_bosfs.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_bosfs.sh) downloads the bosfs-1.0.0.8.tar.gz and runs its `build.sh` but fails in two places:

1) The `autogen.sh` script calls `aclocal` which had not yet been installed in the container
2) undefined reference to uuid-dev

```
bce_request.cpp:36: undefined reference to `uuid_generate'
```

**To Reproduce**
1. Remove any old docker images to start fresh
2. run ./build_dev.sh ./dev.x86_64.dockerfile from docker/build

**Screenshots**

**Screenshot of first error due to missing aclocal**

![screenshot from 2019-02-04 20-07-43](https://user-images.githubusercontent.com/2354387/52251769-dbf1b100-28cc-11e9-91cd-a793917ee08c.png)

**Screenshot of second error due to missing uuid-dev**
![screenshot from 2019-02-04 22-32-48](https://user-images.githubusercontent.com/2354387/52251797-f592f880-28cc-11e9-9948-382f62121329.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a [pull request](https://github.com/ApolloAuto/apollo/pull/6736) to fix this issue

**Comment by natashadsouza** [comment]
Seems like this issue has been resolved. @aboarya thank you very much for the pull request!
