### ISSUE TITLE
Error in running install_ipopt.sh while building dev container

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6735]
**Describe the bug**
The build_dev.sh script uses a number of install scripts.  The script [install_ipopt.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_ipopt.sh) attempts to install `gfortan` using apt-get but the container is missing the[ universe repository](https://askubuntu.com/a/970713)

**To Reproduce**
1. Remove any old docker images to start fresh
2. run ./build_dev.sh ./dev.x86_64.dockerfile from docker/build

**Screenshots**

![screenshot from 2019-02-05 08-21-54](https://user-images.githubusercontent.com/2354387/52281945-34f13180-292d-11e9-8f5a-986b5ab026e4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a [pull request](https://github.com/ApolloAuto/apollo/pull/6737) to fix this issue

**Comment by natashadsouza** [comment]
Closing this issue as it has been resolved.
