### ISSUE TITLE
Unable to locate apt packages from install_python_modules.sh during dev container build

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6738]
**Describe the bug**
The build_dev.sh script uses a number of install scripts.  The script [install_python_modules.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_python_modules.sh) fails with `unable to locate apt packages`.

It needs an `apt-get -y update` before the `apt-get -y install`

**To Reproduce**
1. Remove any old docker images to start fresh
2. run ./build_dev.sh ./dev.x86_64.dockerfile from docker/build

**Screenshots**

![screenshot from 2019-02-05 11-07-31](https://user-images.githubusercontent.com/2354387/52291905-77bd0480-2941-11e9-9cd7-7e27863d95ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a[ pull request](https://github.com/ApolloAuto/apollo/pull/6739) to fix this issue

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks!
