### ISSUE TITLE
Leveldb header file missing during dev container build

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6741]
**Describe the bug**
The build_dev.sh script uses a number of install scripts.  The script [install_python_modules.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_python_modules.sh) fails with:

plyvel/_plyvel.cpp:359:24: fatal error: leveldb/db.h: No such file or directory

It needs to install the package `libleveldb-dev`

**To Reproduce**
1. Remove any old docker images to start fresh
2. run ./build_dev.sh dev.x86_64.dockerfile from docker/build

**Screenshots**

![screenshot from 2019-02-05 13-21-20](https://user-images.githubusercontent.com/2354387/52295619-48f75c00-294a-11e9-8084-71ee4b64ffc0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a [pull request](https://github.com/ApolloAuto/apollo/pull/6742) to fix this issue

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved. Thanks!
