### ISSUE TITLE
install_supervisor.sh container script unable to locate package supervisor 

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6743]
**Describe the bug**
The build_dev.sh container build script uses a number of install scripts.  The script [install_supervisor.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_supervisor.sh) fails with:

`unable to locate package supervisor `

This can be fixed with an `apt-get -y update` before the `apt-get -y install`

**To Reproduce**
1. Remove any old docker images to start fresh
2. run ./build_dev.sh dev.x86_64.dockerfile from docker/build

**Screenshots**

![screenshot from 2019-02-05 14-36-45](https://user-images.githubusercontent.com/2354387/52300110-0ab36a00-2955-11e9-841c-fba7f4012f0b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a pull request to fix this issue

**Comment by Capri2014** [comment]
code merged and close this issue, thanks!
