### ISSUE TITLE
ADEBUG_MODULE in cyber/common/log.h parameter not used

### ISSUE THREAD

**Issue by yang-le** [ApolloAuto/apollo#6749]
https://github.com/ApolloAuto/apollo/blob/f1f2a57ece8cd993ae8eb7f604978e3a054a1b0c/cyber/common/log.h#L37-L38

Why this macro's parameter `moudule` not used?
I think it should be
```
#define ADEBUG_MODULE(module) \ 
   VLOG(4) << LEFT_BRACKET << module << RIGHT_BRACKET << "[DEBUG] "
```
or
```
#define ADEBUG_MODULE \ 
   VLOG(4) << LEFT_BRACKET << MODULE_NAME << RIGHT_BRACKET << "[DEBUG] "
```

**Comment by fengqikai1414** [comment]
Thanks @yang-le  for this issue.
#6954 will fix it.

**Comment by Smlight** [comment]
@fengqikai1414 @GoLancer I think the problem is still here over many branches even now!

> [apollo/cyber/common/log.h](https://github.com/ApolloAuto/apollo/blob/master/cyber/common/log.h#L37-L38)
> 
>  #define ADEBUG_MODULE(module) \ 
>    VLOG(4) << LEFT_BRACKET << MODULE_NAME << RIGHT_BRACKET << "[DEBUG] " 
> 
> Why this macro's parameter `moudule` not used?
> I think it should be
> 
> ```
> #define ADEBUG_MODULE(module) \ 
>    VLOG(4) << LEFT_BRACKET << module << RIGHT_BRACKET << "[DEBUG] "
> ```
> or
> 
> ```
> #define ADEBUG_MODULE \ 
>    VLOG(4) << LEFT_BRACKET << MODULE_NAME << RIGHT_BRACKET << "[DEBUG] "
> ```

**Comment by Smlight** [comment]
@fengqikai1414 @GoLancer @xiaoxq  I think the problem is still here over many branches even now!

> [apollo/cyber/common/log.h](https://github.com/ApolloAuto/apollo/blob/master/cyber/common/log.h#L37-L38)
> 
>  #define ADEBUG_MODULE(module) \ 
>    VLOG(4) << LEFT_BRACKET << MODULE_NAME << RIGHT_BRACKET << "[DEBUG] " 
> 
> Why this macro's parameter `moudule` not used?
> I think it should be
> 
> ```
> #define ADEBUG_MODULE(module) \ 
>    VLOG(4) << LEFT_BRACKET << module << RIGHT_BRACKET << "[DEBUG] "
> ```
> or
> 
> ```
> #define ADEBUG_MODULE \ 
>    VLOG(4) << LEFT_BRACKET << MODULE_NAME << RIGHT_BRACKET << "[DEBUG] "
> ```

**Comment by quning78** [comment]
you can submit a commit for this as well @Smlight
