### ISSUE TITLE
GetCurrentPath in apollo/cyber/common/file.cc may cause a memory leak

### ISSUE THREAD

**Issue by yang-le** [ApolloAuto/apollo#6751]
https://github.com/ApolloAuto/apollo/blob/2b9839090e5d2716761fde41a05ff3cc41c87337/cyber/common/file.cc#L319

According to Linux man page
> get_current_dir_name() will malloc(3) an array big enough to hold the absolute pathname of the current working directory. If the environment variable PWD is set, and its value is correct, then that value will be returned. The caller should free(3) the returned buffer. 

So I think it's better to free the returned buffer.

**Comment by GoLancer** [comment]
Thanks @yang-le  for this issue.
#6953 will fix it.
