### ISSUE TITLE
Mismatch of the osqp header install directory

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6756]
**Describe the bug**
The bazel BUILD of the math common module is expecting the `osqp` dependency under `/usr/local/include`.
The `docker/build/install_osqp.sh` script places it `/usr/include`

**To Reproduce**
1. Remove any old docker images to start fresh
2. run `./build_dev.sh dev.x86_64.dockerfile` from docker/build
3. run `bash docker/scripts/dev_start.sh -l -t <image-id>`
4. run `bash docker/scripts/dev_into.sh`
5. run `bash apollo.sh build`

**Expected behavior**
Successful bazel build

**Screenshots**
![screenshot from 2019-02-06 02-17-22](https://user-images.githubusercontent.com/2354387/52326355-5f3b0180-29b6-11e9-835a-1388eeae1134.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
Created a [pull request](https://github.com/ApolloAuto/apollo/pull/6757) for this issue

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks!
