### ISSUE TITLE
Qt 5.1 missing from freshly build dev container

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6760]
**Describe the bug**

A freshly built dev container is missing the Qt 5.1 library and gcc_64 binary required by bazel.

**To Reproduce**
1. Remove any old docker images to start fresh
2. run `./build_dev.sh dev.x86_64.dockerfile` from docker/build
3. run `bash docker/scripts/dev_start.sh -l -t <image-id>`
4. run `bash docker/scripts/dev_into.sh`
5. run `bash apollo.sh build`

**Screenshots**

![screenshot from 2019-02-06 14-43-44](https://user-images.githubusercontent.com/2354387/52369190-1d45a600-2a1e-11e9-8808-5474bce2ca78.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a [pull request ](https://github.com/ApolloAuto/apollo/pull/6761)to fix this issue

**Comment by natashadsouza** [comment]
Thank you for submitting this pull request @aboarya 
Closing this issue currently.
