### ISSUE TITLE
Missing civetweb artifact with a fresh build of the dev container

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6769]
**Describe the bug**
The `install_bazel_packages.sh` script downloads a number of artifacts to `/home/tmp` but is missing the civetweb v1.11 Release.

**To Reproduce**
1. Remove any old docker images to start fresh
2. run `./build_dev.sh dev.x86_64.dockerfile` from docker/build
3. run `bash docker/scripts/dev_start.sh -l -t <image-tag>`
4. run `bash docker/scripts/dev_into.sh`
5. run `bash apollo.sh build`

**Screenshots**

![screenshot from 2019-02-07 01-34-53](https://user-images.githubusercontent.com/2354387/52416991-d9ec4580-2ab8-11e9-89cb-ff4af8494809.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a [pull request](https://github.com/ApolloAuto/apollo/pull/6770) to fix this issue

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved. Thanks!
