### ISSUE TITLE
Missing poco library with a fresh build of the dev container

### ISSUE THREAD

**Issue by aboarya** [ApolloAuto/apollo#6771]
**Describe the bug**

When building apollo on a locally built dev container, bazel fails with the error:

```
cyber/class_loader/utility/class_loader_utility.h:20:32: fatal error:
Poco/SharedLibrary.h: No such file or directory
#include <Poco/SharedLibrary>
```

**To Reproduce**
1. Remove any old docker images to start fresh
2. run `./build_dev.sh dev.x86_64.dockerfile` from docker/build
3. run `bash docker/scripts/dev_start.sh -l -t <image-tag>`
4. run `bash docker/scripts/dev_into.sh`
5. run `bash apollo.sh build`

**Screenshots**

![screenshot from 2019-02-07 01-53-11](https://user-images.githubusercontent.com/2354387/52419322-d3ac9800-2abd-11e9-910c-7bfd7cab508e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 
**Additional context**
I created a [pull request](https://github.com/ApolloAuto/apollo/pull/6772) to fix this issue

**Comment by natashadsouza** [comment]
@aboarya for your PRs, please submit it with its title in the following format: "**Module: change**"
Closing this issue as it seems to be resolved. Thanks!

**Comment by aboarya** [comment]
Hi @natashadsouza thanks so much! It's really great to be able to contribute to this project!

Do you mean to make the title with "Build:change" or "Module:Build" (similar to the label)?

Thanks again!

**Comment by natashadsouza** [comment]
Your first suggestion: "Build: added poco ...". You can also look at PRs submitted by Apollo team members for added insights. Thank you so much for all your contribution. We truly appreciate it :)

**Comment by shifakhan4892** [comment]
Hi @aboarya, 

I am having the same error with poco when I am trying to build the modules independently. 
I figured that when I was building the docker image, I am getting the following error :

![poco error](https://user-images.githubusercontent.com/16239521/55744025-7d929d00-59f9-11e9-8771-8e5bfa923665.png)


I am using Ubuntu 14.04 and executing it inside the docker. Do you think there is a solution to this ?
Also, I used the current merged Poco installer file.
 
Thanks,
