### ISSUE TITLE
throttle_input and throttle_cmd difference

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#6780]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
HI, I have a question regrading to the topic `/apollo/canbus/chassis/` I noticed that when the car is idling, the throttle input and throttle output are not set to zero, they have a value around ~15. However, throttle_cmd is set to 0 as expected. I am wondering what's the difference between "throttle_input" and "throttle_cmd". Does it have anything to do with the "deadband" of the engine?

**Comment by Capri2014** [comment]
You are right, except this "dead-band" is from throttle mechanical system, not directly from engine.
