### ISSUE TITLE
Turn on SimControl without Dreamview GUI?

### ISSUE THREAD

**Issue by Wang4758** [ApolloAuto/apollo#6795]
Hello, 

I would like to know whether it is possible to turn on the SimControl mode without the Dreamview GUI. Because the container is running on our server and I couldn't find a way to forward the GUI to my local machine. So is it possible or which command should I run?

**Comment by vlin17** [comment]
There are two possible ways to do so without GUI
1. download websocket command tool and 
send `{"type": "ToggleSimControl", "enable":  [false|true] }` to ws://<localhost or your server ip>:8888/websocket
2. customize dreamview to turn on SimControl through gflag. In fact, it is how it was done in v2.0.0.

**Comment by natashadsouza** [comment]
Closing this issue a it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
