### ISSUE TITLE
WORKSPACE: Permission Denied during build

### ISSUE THREAD

**Issue by deepaktalwardt** [ApolloAuto/apollo#6798]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04 LTS
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0.0

### Steps to reproduce the issue:
Can someone explain why I get these Permission denied errors. I feel like the permissions are a bit messed up and would like someone to help me fix them. I don't have the hardware and am trying to run Apollo on my laptop.

The build continues to run after these errors, however, I haven't been able to successfully run Apollo yet. Please advise. Thank you.

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/7192506/52549093-3637b980-2d86-11e9-8cf0-1d8559848841.png)

**Comment by deepaktalwardt** [comment]
The build failed eventually giving me the following error:
![image](https://user-images.githubusercontent.com/7192506/52549861-32a63180-2d8a-11e9-98b5-eaca1e7361fd.png)

**Comment by cy19890513** [comment]
I am also new to apollo project. I followed this without hardware tutorial. I only able to say i was able to build with the tutorial. The link is this: https://github.com/ApolloAuto/apollo/tree/master/docs/demo_guide. Maybe try with sudo <command> to get rid of permission error.

**Comment by FreshmanD** [comment]
Do you test your docker?  I think the reason should be you don't add your current user into docker group. pls follow this step:https://docs.docker.com/install/linux/linux-postinstall/

**Comment by deepaktalwardt** [comment]
Thanks @FreshmanD ! I needed to provide my user all permissions to the apollo folder to make it work. I did add the user to the docker group to make it run without sudo, but that alone didn't fix all issues.
