### ISSUE TITLE
BUILD: Fail to build & release v3.5.0 with clean docker image

### ISSUE THREAD

**Issue by dawonn-haval** [ApolloAuto/apollo#6800]
**Describe the bug**
Build fails when following the kiwi: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md

```
user@in_dev_docker:/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under GPU mode. GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
.
____Loading package: modules/localization/msf/local_tool/map_creation
____Loading package: modules/dreamview/backend/simulation_world
____Loading package: modules/perception/fusion/lib/fusion_system/probabilistic_fusion
____Loading package: modules/perception/onboard/inner_component_messages
____Loading package: modules/perception/lidar/app/proto
____Loading package: modules/localization/conf
____Loading package: modules/perception/camera/lib/calibrator/common
____Loading package: modules/perception/radar/lib/dummy
____Loading package: modules/prediction/network/cruise_model
____Loading package: modules/control/integration_tests
____Loading package: modules/prediction/predictor
____Loading package: modules/planning/planner/lattice
____Loading package: modules/data
____Loading package: modules/perception/common/i_lib
____Loading package: modules/perception/inference
____Loading package: modules/planning/math
____Loading package: modules/planning/tasks/optimizers/qp_spline_st_speed
____Loading package: modules/v2x/common
____Loading package: cyber
____Loading package: cyber/timer
____Loading package: cyber/task
____Loading package: cyber/data
____Loading package: cyber/examples/proto
____Loading package: cyber/message
[INFO] Building on x86_64...
[INFO] Building with --jobs=8 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (02-11 19:02:04.979) Found 3240 targets...
ERROR: (02-11 19:02:05.969) /apollo/modules/v2x/common/BUILD:5:1: undeclared inclusion(s) in rule '//modules/v2x/common:v2x_proxy_gflags':
this rule is missing dependency declarations for the following files included by 'modules/v2x/common/v2x_proxy_gflags.cc':
  'bazel-out/local-dbg/genfiles/external/com_github_gflags_gflags/gflags/gflags.h'
  'bazel-out/local-dbg/genfiles/external/com_github_gflags_gflags/gflags/gflags_declare.h'
  'bazel-out/local-dbg/genfiles/external/com_github_gflags_gflags/gflags/gflags_google.h'.
INFO: (02-11 19:02:06.069) Elapsed time: 8.292s, Critical Path: 0.29s
============================
[ERROR] Build failed!
[INFO] Took 23 seconds
============================
user@in_dev_docker:/apollo$ git status
```

**To Reproduce**
1. follow the wiki, and execute  bash apollo.sh build

**Expected behavior**
I expect no build failures when using a release version in a clean docker environment.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome
 - Version v3.5.0

**Additional context**
Similar to https://github.com/ApolloAuto/apollo/issues/5755 
Deleting that folder and rebuilding was successful, however I do not actually understand what was actually broken to be honest...

**Comment by dawonn-haval** [comment]
I'm not sure if I should start a new issue, but after following the instructions in #5755, I then returned to the wiki and tried to run 'release' which failed:

```
user@in_dev_docker:/apollo$ bash apollo.sh release
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
/apollo
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
____Loading package: third_party/can_card_library/esd_can
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
cp: cannot create regular file '/home/user/.cache/apollo_release/apollo/bazel-bin/modules/tools/visualizer/cyber_visualizer': Permission denied
```

**Comment by dawonn-haval** [comment]
![image](https://user-images.githubusercontent.com/44446780/52643566-50b78300-2eab-11e9-9bd7-87ebc7265417.png)

The file is marked read only, not yet sure why or where this comes from. I'm starting by looking at  apollo.sh release().

**Comment by dawonn-haval** [comment]
Dreamview fails to load:
```

dereck@in_dev_docker:/apollo$ ./scripts/bootstrap.sh start
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Dreamview is running at http://localhost:8888
dereck@in_dev_docker:/apollo$ 
```

I just get a blank white page when loading that url in my web browser.

**Comment by dawonn-haval** [comment]
I would be happy to post any log files etc, I'm new to apollo and don't really know where to look yet...

**Comment by dawonn-haval** [comment]
After many rebuilds on both master and v3.5.0. I rebooted my computer and now dreamview kinda loads:
![image](https://user-images.githubusercontent.com/44446780/52665218-0ea53600-2ed9-11e9-9506-bbf706b982af.png)

All of the images appear to be broken however.

**Comment by dawonn-haval** [comment]
I manually executed apollo.sh release() and it looks like cyber_visualizer is copied twice:
![image](https://user-images.githubusercontent.com/44446780/52667410-bd984080-2ede-11e9-9444-31ae23f282f2.png)

Here's the two lines that are setting those vars:
https://github.com/ApolloAuto/apollo/blob/3b91c914c8177af19bb031d57815fb03e094d304/apollo.sh#L321
https://github.com/ApolloAuto/apollo/blob/3b91c914c8177af19bb031d57815fb03e094d304/apollo.sh#L332

This also looks suspicious to me. The CYBERBIN query looks like it is copying everything in apollo [//...] and then the next chuck of code is trying to only copy the code from the tools module: [//modules/tools/...]

I wonder if the CYBERBIN line is actually a greedy bug, and not really supposed to be globbing everything?

**Comment by dawonn-haval** [comment]
I added an -f option to cp and that resolved the error:
`cp -Pf --parent "bazel-bin/${BIN}" ${APOLLO_RELEASE_DIR}`

I'm pretty sure that's not the correct solution though. It would be nice to hear some thoughts from someone that understands the bigger picture.

**Comment by dawonn-haval** [comment]
To get apollo_docker.sh gen_docker to work I likewise needed to update the cp options:

https://github.com/ApolloAuto/apollo/blob/master/apollo_docker.sh#L111
`    docker exec apollo_release bash -c 'cp -LrPf --parent /root/mnt/apollo_release/apollo /'`

I'm still not sure if it works, but the first time through it gave me tons of errors, and now it give me none, so that's a good start I think? 

![image](https://user-images.githubusercontent.com/44446780/52672829-f0e1cc00-2eec-11e9-8281-1fd39a1c3d40.png)

**Comment by dawonn-haval** [comment]
I deleted my .cache/bazel folder and rebuilt. This allows dreamview to load, but it is missing some icons on the left:
![image](https://user-images.githubusercontent.com/44446780/52722351-65fae300-2f79-11e9-958f-73fc86b6c0c4.png)

**Comment by dawonn-haval** [comment]
Looks like the broken images in dreamview are due to LFS. I installed lfs after cloning the repo whiche left the 'pointers' in the working directory.  The following command replaced the pointers with the real files and now dreamview is looking a bit better:

`git lft pull`

![image](https://user-images.githubusercontent.com/44446780/52734142-808d8600-2f92-11e9-8d80-2555bd6041c2.png)

**Comment by dawonn-haval** [comment]
In Summary:
* The apollo build system caches data outside of the docker container, and an old build conflicted with my latest build.
* Then I got an error while "releasing" because a read only file was being copied twice in the release process. 
* Then I encountered an error trying to run the released container, adduser.sh is missing, and decided to try and run from the development environment without releasing.
* I found that dreview loaded without images, which was resolved by git lfs pull.

**Comment by natashadsouza** [comment]
@dawonn-haval apologies for the delay in responding. Are you still having build issues? It seems like you found the issue to be Git LFS one. If you are still seeing the issue, please @-mention me and send in a screenshot of the logs you see. Thanks!
