### ISSUE TITLE
Can traffic regulation loading make it possible to add new traffic rules without modifying the code?

### ISSUE THREAD

**Issue by liujiwei777** [ApolloAuto/apollo#6809]
void TrafficDecider::RegisterRules() {
  s_rule_factory.Register(TrafficRuleConfig::BACKSIDE_VEHICLE,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new BacksideVehicle(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::CHANGE_LANE,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new ChangeLane(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::CROSSWALK,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new Crosswalk(config);
                          });

  s_rule_factory.Register(TrafficRuleConfig::DESTINATION,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new Destination(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::KEEP_CLEAR,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new KeepClear(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::PULL_OVER,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new PullOver(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::REFERENCE_LINE_END,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new ReferenceLineEnd(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::REROUTING,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new Rerouting(config);
                          });
  s_rule_factory.Register(TrafficRuleConfig::SIGNAL_LIGHT,
                          [](const TrafficRuleConfig &config) -> TrafficRule * {
                            return new SignalLight(config);
                          });
}
--------------------------------------------------------------------------------------------
Is this code modified with configuration loading and C++ template without adding new rules to modify the code?

**Comment by jmtao** [comment]
@liujiwei777 I'm not sure what you exactly mean. If you want to add a new traffic rule and make it run, you have to create a class/implementation of that rule (please refer to any traffic rule class at https://github.com/ApolloAuto/apollo/tree/master/modules/planning/traffic_rules, as examples), and also create configuration if needed (please refer to https://github.com/ApolloAuto/apollo/blob/master/modules/planning/proto/traffic_rule_config.proto)
 
And then register your traffic rule as above, to make it effective and run. 

Hope this answers your questions. 
Thanks for supporting Apollo!
