### ISSUE TITLE
Is an external IMU required with Novatel PwrPak7 GNSS?

### ISSUE THREAD

**Issue by ak201790** [ApolloAuto/apollo#6810]
Shouldn't it be "**ProPak 6**" instead of "**ProPak 7**" in this [diagram](https://github.com/ApolloAuto/apollo/blob/35f5a945b9e47941505b1037118772a9a86b52b1/docs/demo_guide/images/Hardware_connection_3_5.png)?

Or do you guys mean "**PwrPak 7**"? If so then PwrPak7D-E1 already encloses an IMU ( Epson EG320N). Are you guys using an external IMU as well with the PwrPak7D-E1 GNSS/INS enclosure? If yes, which IMU are you using?

![issue](https://user-images.githubusercontent.com/36643158/52608866-1d83de00-2e30-11e9-8d82-b82f6a216f12.jpg)

**Comment by natashadsouza** [comment]
@ak201790 you are correct. It is supposed to be  PP6. We also do support PP7 which was introduced with the latest version Apollo 3.5. The image will be updated shortly. Thanks!

**Comment by natashadsouza** [comment]
Please check #6877
