### ISSUE TITLE
app.bundle.js can not load

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#6811]
Even after runing:

```
git-lfs fetch --all
```

the app.bundle.js can not fetch, it contains something like this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:66df713923032a98a1ea140bac0308cd4f4fe30389eda3a025d275eb7ffbf8ca
size 1685587

```

Deamview got nothing, how to solve it?

**Comment by xiaoxq** [comment]
How does "git lfs fetch" say?

**Comment by jinfagang** [comment]
@xiaoxq  OK, seems this is an issue. I manually download js file place it into `modules/dreamview/frontend` and the interface comes out, both chrome and firefox. But the icons and loader which in `assets` folder are not loaded correctly.

I already run `git lfs fetch --all` and it runs somewhat large files and indicates me all files are fetched, but actually it fetch 1.5G files except those dreamview needed files.

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/52615671-f3362d00-2ed0-11e9-8700-9ed7b0b5567b.png)

**Comment by jinfagang** [comment]
Well, as well as those records file:

```
@in_dev_docker:/apollo/docs/demo_guide$ cat demo_3.5.record 
version https://git-lfs.github.com/spec/v1
oid sha256:7bd3d160eeb8ff85953df54c93be9c4fe9f1e87ab5e5846a42417633151f1465
size 96246211

```

Should I run git lfs inside docker??
but the docker does not contains git lfs... when I install from apt-get, there are such error;
```
@in_dev_docker:/apollo/docs/demo_guide$ sudo apt install git-lfs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty-backports/universe amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-backports_universe_binary-amd64_Packages.gz)
W: You may want to run apt-get update to correct these problems
E: Unable to locate package git-lfs

```

**Comment by e-guy** [comment]
I got the same issue

**Comment by aboarya** [comment]
@jinfagang You should run this on the host:

```
cd <apollo-checkout-directory>
git lfs fetch --all
cat modules/dreamview/frontend/dist/app.bundle.js # to verify
```

**Comment by aboarya** [comment]
https://github.com/ApolloAuto/apollo/issues/6498#issuecomment-455288291

**Comment by natashadsouza** [comment]
@jinfagang are you still facing the issue? @aboarya thank you for the fix. I believe your suggestion should have fixed the issue. Feel free to reopen this issue if you still have additional questions.

**Comment by magicalwz** [comment]
seem to me that you should execute

git lfs fetch
git lfs checkout
# or
git lfs pull


according to  https://zzz.buzz/zh/2016/04/19/the-guide-to-git-lfs/
