### ISSUE TITLE
HELP: fail to bash apollo.sh build

### ISSUE THREAD

**Issue by yingchen1991** [ApolloAuto/apollo#6813]
Hi, when I run 'bash apollo.sh build', but it goes as follows:
(I add a lot of code in my project)
### System information

- **OS Platform and Distribution (Linux Ubuntu 16.04)**
- **Apollo installed from (source)**:
- **Apollo version (1.5)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

>System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
[INFO] Skip building perception module!
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/bazel_cache/civetweb/BUILD:3:5: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:10:18: invalid character: '&'
ERROR: /apollo/bazel_cache/civetweb/BUILD:15:8: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:17:12: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:19:15: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:19:16: invalid character: '@'
ERROR: /apollo/bazel_cache/civetweb/BUILD:20:10: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:20:18: invalid character: '&'
ERROR: /apollo/bazel_cache/civetweb/BUILD:21:10: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:21:11: invalid character: '?'
ERROR: /apollo/bazel_cache/civetweb/BUILD:28:8: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:29:12: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:29:13: invalid character: '@'
ERROR: /apollo/bazel_cache/civetweb/BUILD:49:8: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:51:12: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:53:11: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:54:8: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:54:9: invalid character: '?'
ERROR: /apollo/bazel_cache/civetweb/BUILD:63:8: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:65:12: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:67:8: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:73:17: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:73:22: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:73:32: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:88:9: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:89:18: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:90:9: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:91:13: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:92:9: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:93:9: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:93:43: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:94:8: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:95:4: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:97:2: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:100:19: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:101:21: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:104:12: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:107:6: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:112:12: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:112:44: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:112:83: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:112:93: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:127:6: invalid character: '$'
ERROR: /apollo/bazel_cache/civetweb/BUILD:131:1: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:135:11: indentation error
ERROR: /apollo/bazel_cache/civetweb/BUILD:2:10: syntax error at 'pipefail': expected newline
ERROR: /apollo/bazel_cache/civetweb/BUILD:5:10: syntax error at '{': expected newline
ERROR: /apollo/bazel_cache/civetweb/BUILD:9:10: syntax error at '{': expected newline
ERROR: /apollo/bazel_cache/civetweb/BUILD:13:12: syntax error at '{': expected newline
ERROR: /apollo/bazel_cache/civetweb/BUILD:19:17: syntax error at ';': expected expression
ERROR: /apollo/bazel_cache/civetweb/BUILD:2:6: name 'euo' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:5:1: name 'stdout' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:9:1: name 'stderr' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:13:1: name 'prereqs' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:19:17: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:21:20: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:54:18: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:73:35: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:81:19: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:83:34: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:84:34: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:85:27: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:86:26: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:87:22: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:88:16: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:89:25: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:90:16: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:91:20: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:93:34: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:94:15: contains syntax error(s)
ERROR: /apollo/bazel_cache/civetweb/BUILD:101:3: name 'local' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:104:3: name 'mkdir' is not defined (did you mean 'dir'?)
ERROR: /apollo/bazel_cache/civetweb/BUILD:107:3: name 'cd' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:108:3: name 'trap' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:111:3: name 'check' is not defined
ERROR: /apollo/bazel_cache/civetweb/BUILD:112:3: name 'cmake' is not defined
ERROR: package contains errors: bazel_cache/civetweb
ERROR: error loading package 'bazel_cache/civetweb': Package 'bazel_cache/civetweb' contains errors
============================
[ERROR] Build failed!
[INFO] Took 15 seconds
============================

Any help?
Thanks!

**Comment by natashadsouza** [comment]
@yingchen1991 please refer to our [Software FAQs](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md) or you could go through similar issues created labelled "Build" .
Also, to troubleshoot better, we do need additional information, please fill out the requirements in the form included above.

**Comment by natashadsouza** [comment]
Closing this issue a it appears to be resolved. Feel free to reopen if the issue persists. Thanks!
