### ISSUE TITLE
Regarding path decider, what's the difference between "side pass" decision and "overtake" decision?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6837]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by jmtao** [comment]
@KevinYuk 
"SidePass" is a "lateral" object decision, similar to "Nudge". These decisions help ego vehicle to dudge obstacle(s) in lateral direction while passing them. 
"SidePass" may cross lane boundaries little bit, and "Nudge" would be within the current lane. 

"Overtake"/"Yield"/"Stop" are "longitudinal" object decisions when ego vehicle and other obstacles's path may cross. 
OVERTAKE: ego vehicle shall arrive certain point BEFORE another vehicle/moving obstacle. 
YIELD: ego vehicle shall arrive certain point AFTER another vehicle/moving obstacle. 
STOP: ego vehicle shall STOP behind another vehicle/obstacle. 

For more object decisions, please refer to:
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/proto/decision.proto

Thanks for supporting Apollo!

**Comment by KevinYuk** [comment]
@jmtao 
Nice. Beautiful summary!
BTW, from the link above, I also found "avoid" decision. What does that mean?

**Comment by jmtao** [comment]
@KevinYuk "avoid" decision is a special decision we design/plan for ESTOP. 
When ADC is unable to self-driving properly, it'll enter estop scenario.  It may hard-brake, or cruise via a safe route if possible.  During this period, it still need to dudge/avoid obstacles, but the algrithmn/handling can be very different from Nudge decision in normal situation. That's the decision of AVOID.

**Comment by KevinYuk** [comment]
@jmtao The "avoid" decision is "lateral" object decision in safe route cruise scenario. Am I right?

**Comment by jmtao** [comment]
@KevinYuk yes. you are right. the "avoid" decision is a "lateral" object decision in e-stop mode. (we don't have a "safe route cruise" scenario though.)

hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
