### ISSUE TITLE
In PathDecider solver, I found that you only add decision for static obstacles, especially for pedestrain and bycycle. How about dynamic obstacles?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6849]
```
bool PathDecider::MakeObjectDecision(const PathData &path_data,
                                     PathDecision *const path_decision) {
  DCHECK_NOTNULL(path_decision);
  if (!MakeStaticObstacleDecision(path_data, path_decision)) {
    AERROR << "Failed to make decisions for static obstacles";
    return false;
  }
  return true;
}







 for (const auto *path_obstacle : path_decision->path_obstacles().Items()) {
    const auto &obstacle = *path_obstacle->obstacle();
    bool is_bycycle_or_pedestrain =
        (obstacle.Perception().type() ==
             perception::PerceptionObstacle::BICYCLE ||
         obstacle.Perception().type() ==
             perception::PerceptionObstacle::PEDESTRIAN);

```

**Comment by jmtao** [comment]
Currently, we make decisions(Nudge/Stop) for static obstacles in PathDecide.
The decisions(Yield/Overtake and etc) for moving obstacles are made by STGraph.

**Comment by KevinYuk** [comment]
@jmtao I read the code, and found that moving obstacles decision is made in speedDecider solver. Just as you said it's made by STGraph. However, why don't make decision for static and moving obstacles in PathDecider solver at the same time? In PathDecider, we have already got moving obstacle prediction trajectory from Prediction Module ros msg broadcast, even in SL graph (not ST graph), we could make decision(Yield/Overtake and etc) for moving obstacle.

**Comment by jmtao** [comment]
we plan path first, and then speed based on path.  
Currently we don't have SL graph. We have SL info, but that's not enough to make decision for moving obstacles without dimension of T(time).

**Comment by KevinYuk** [comment]
@jmtao Thanks for your reply.
Could I understand as below? Am I right?
When Apollo performs path profile, it only consider static obstacle to draw a path and don't consider moving obstacle. So if there is a moving obstacle(not oncoming direction) in front of ADC, Apollo cannot "see" this moving obstacle. The planning path would "cross" this moving obstacle ahead. Please check the picture below.
![image](https://user-images.githubusercontent.com/20220399/52826444-d467ae80-30fb-11e9-9d72-e9b43a0de600.png)

**Comment by jmtao** [comment]
@KevinYuk once the path has been planed, we make decision for moving obstacles based on STGraph, and a "OVERTAKE/YIELD/STOP decision (which would be achieved via speed) would be made if their paths may cross ego vehicle's path. 
In your second graph, ADC may slowdown(follow) or yield to that moving obstacle depending on its path/speed/heading.

**Comment by KevinYuk** [comment]
@jmtao Understood. Thanks a lot.
