### ISSUE TITLE
Regarding ST Boundary Type, what does "KEEP_CLEAR" mean?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6852]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by jmtao** [comment]
@KevinYuk KEEP_CLEAR is a special area that is "crossable" on STGraph. It's created based on keep-clear zone or junctions that must be kept clear. 
If they can be crossed under certain conditions, they are crossable; otherwise, ego vehicle must stop behind its start line.

**Comment by jmtao** [comment]
@KevinYuk hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
