### ISSUE TITLE
Confused about "GetDxDzForCenterFromGroundLineSeg" in obj_postprocesser.cc

### ISSUE THREAD

**Issue by fjc523** [ApolloAuto/apollo#6855]
I have two questions about function `GetDxDzForCenterFromGroundLineSeg`:

1. The function seems to calculate the smallest difference (dx and dz)  between the four bottom vertex of 3D bbox and the  "line_segs", which are the low line of 2d bboxes in the image. Why the sum of the differences can be the compensation value to the postion of object's center ?

2. The number of "line_segs" increases when preocess more objs in one frame, eg. the first obj have only one "line_segs", but the third obj will have three "line_segs". Why not process all objs with same "line_segs" (eg. with all "line_segs" or just with their corresponding "line_segs")?

I will be appreciated if someone could answer my confusion.

Thank you.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
