### ISSUE TITLE
How to cite apollo ? 

### ISSUE THREAD

**Issue by jediofgever** [ApolloAuto/apollo#6857]
How to cite apollo ? for my scientific paper

**Comment by natashadsouza** [comment]
@jediofgever thank you for your question. 
We recommend using the standard acceptable format:
Baidu Apollo team (2017), Apollo: Open Source Autonomous Driving, URL:https://github.com/ApolloAuto/apollo

Let me know if you have any additional questions.

**Comment by jediofgever** [comment]
To anyone use bibtex;
```
@misc{ap,
  title = {{Baidu Apollo team (2017), Apollo: Open Source Autonomous Driving},
  howpublished = {\url{https://github.com/ApolloAuto/apollo}},
  note = {Accessed: 2019-02-11}
}}
```


![image](https://user-images.githubusercontent.com/18460336/52849290-a3af6580-314b-11e9-93ef-11f6b2d036d9.png)
