### ISSUE TITLE
Canbus module: the can_sender message should be updated within the PowerSendThreadFunc, not OnControlCommand

### ISSUE THREAD

**Issue by liangyd** [ApolloAuto/apollo#6869]
**Describe the bug**
Apollo's canbus module updates the can_sender when it receives control data. In this case, it fails to handle the use case when a CAN Tx message has an alive counter and its message trasmit rate is lower than control data update rate. This will probably cause a CAN bus communication issue for certain type of vehicles.

I am using canbus module to send a can message whose last data byte needs to increment every time when it is sent out successfully. In this case, the expected CAN output sequence is:
canid: 123 candata: 00 00 00 00 00 00 00 F1
canid: 123 candata: 00 00 00 00 00 00 00 F2
canid: 123 candata: 00 00 00 00 00 00 00 F3
canid: 123 candata: 00 00 00 00 00 00 00 F4
...

However, the output is:
canid: 123 candata: 00 00 00 00 00 00 00 F1
canid: 123 candata: 00 00 00 00 00 00 00 F3
...
And the discontinued alivecounter triggers an error in the vehicle. 

Then, I noticed that the the can_sender.update() is called by OnControlCommand which runs at a faster rate than my target can message rate.

If I comment out the can_sender.update() in the OnControlCommand() function and add message.Update() inside the for loop within the PowerSendThread, the issue will be resolved..

**To Reproduce**
1. write a new can message inside the protocol folder which has an incremented alive counter. Every time it is called, the data is incremented.  
2. run the canbus module separately, or run the full-stack. 
3. log the can message output.
4. change the can message's period, and log the can messages again.
5. When the can message's period is low and the control_command's update rate is higher, I will see the discontinued alivecounter. 

**Expected behavior**
When the can tx message's period is low and the control_command's update rate is higher, I will see the discontinued alivecounter in the can output logfile. 

**Screenshots**

**Desktop (please complete the following information):**
ubuntu 16.04

**Smartphone (please complete the following information):**
none

**Additional context**

**Comment by Capri2014** [comment]
@liangyd Please update your message rate accordingly, see https://github.com/ApolloAuto/apollo/blob/f2c7896c43616bf4010e028328e7c0cc39598b23/modules/canbus/vehicle/lincoln/protocol/gear_66.cc#L32 for the reference.

**Comment by Capri2014** [comment]
@liangyd If your canbus rate is lower than the control rate, a better choice might be to lower your control rate instead.

**Comment by liangyd** [comment]
@Capri2014 Thanks for your reply. :-) The fact is: I have can messages with different peroids. For example, some can messages needs to be sent every 100ms, while others 10 ms. The one with alive counter is the slower one. If I reduce the control rate, the can messages with faster rate with be impacted...

**Comment by HanochZhong** [comment]
control periods is 10ms default, but，you can use a strategy in the CANbus module to call your CAN signal at 100ms。For example, counting.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
