### ISSUE TITLE
Socket_can_client: a better way to write message_id filter

### ISSUE THREAD

**Issue by liangyd** [ApolloAuto/apollo#6871]
**Is your feature request related to a problem? Please describe.**
No..

**Describe the solution you'd like**
In line 76, socket_can_client_raw.cc, it write a receive message filter:
  // init config and state
  // 1. set receive message_id filter, ie white list
struct can_filter filter[2048];
  for (int i = 0; i < 2048; ++i) {
    filter[i].can_id = 0x000 + i;
    filter[i].can_mask = CAN_SFF_MASK;
  }
int ret = setsockopt(dev_handler_, SOL_CAN_RAW, CAN_RAW_FILTER, &filter,
                       sizeof(filter));

This filter actually pass through all the messages...

I guess the goal of this filter is to get all the messages with SFF CAN IDs from 0x0 to 0x7FF. If so, I think it would be better to write the filter like this without the for loop: 
struct can_filter filter;
  filter.can_id = 0x0;
  filter.can_mask = 0xFFFFF800;
  int ret = setsockopt(dev_handler_, SOL_CAN_RAW, CAN_RAW_FILTER, &filter,
                       sizeof(filter));

Or we can write like this, though it has the for loop:
 for (int i = 0; i < 2048; ++i) {
    filter[i].can_id = 0x000 + i;
    filter[i].can_mask = (CAN_SFF_MASK|CAN_EFF_FLAG);
  }
int ret = setsockopt(dev_handler_, SOL_CAN_RAW, CAN_RAW_FILTER, &filter,
                       sizeof(filter));

If the true intention is to filter out nothing, maybe we can probably comment out this filter :-)
Thanks for your consideration.

**Describe alternatives you've considered**

**Additional context**

**Comment by HanochZhong** [comment]
Refer to your Socket2CAN hardware device programming manual.

**Comment by natashadsouza** [comment]
Closing this issue currently. Thank you very much for your interest in Apollo and for submitting a feature request. We will let you know when it is being worked on and when we will release it. In the mean time, feel free to submit pull requests related to your feature request.
