### ISSUE TITLE
Require the compress option 'bz2' of cyberRT

### ISSUE THREAD

**Issue by xhzzhang** [ApolloAuto/apollo#6899]
**Is your feature request related to a problem? Please describe.**
Apollo use rosbag before apollo 3.5, the rosbag have a compress 'bz2' to use few hdd when record topic.

**Describe the solution you'd like**
Hope cyber_record have add option 'bz2' like rosbag_record.

**Describe alternatives you've considered**
None

**Additional context**
Hope it before Q4 of 2019.

**Comment by GoLancer** [comment]
Thanks for your suggestion. We will support this feature in Q3.
