### ISSUE TITLE
camera num& do you used fisheye (apollo 3.5)

### ISSUE THREAD

**Issue by HanochZhong** [ApolloAuto/apollo#6903]
In apollo/modules/drivers/camera/dag/camera.dag has a components: include fisheye

 components {
      class_name : "CameraComponent"
      config {
        name : "camera_front_fisheye"
        config_file_path : "/apollo/modules/drivers/camera/conf/camera_front_fisheye.pb.txt"
      }
}

but in perception modules include  apollo/modules/perception/production/dag/ has not about fisheye camera, what about that ? apollo 3.5 only use three camera ?

**Comment by techoe** [comment]
You can add front_fisheye in perception_traffic.dag for better traffic light detection. dag files are sampled configuration.

**Comment by natashadsouza** [comment]
Closing this issue as ti appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
