### ISSUE TITLE
Question: Does the road height (elevation) matters for apollo?

### ISSUE THREAD

**Issue by wobistdu** [ApolloAuto/apollo#6908]
For the routing, the waypoint is 2D point, and the routing response is road segments, so the answer for that module is NO. 

What about planning and controlling? I checked the HD map xml parser, the code parses some "z" value from the map file, but it ignores the others. So I am a bit confused, does the road height (z value) matters for apollo?
I tried adding the height value into the parse, but in the dreamview sim control it seems to locate the car on z=0 plane instead of the road plane, and the projection makes it difficult to accurately set the routing point x y  inside the road lane range.

Thanks

**Comment by jmtao** [comment]
@wobistdu Currently we don't support 3D map and 3D position, z usually is set to 0 by default. We'll support that soon.

**Comment by wobistdu** [comment]
@jmtao Thanks for the confirmation. Hope we can get that soon.
Currently I tried to run a map with flyover and tunnels, I add the height into hdmap, but doesn't work well.
I can set z to zero, but the traffic cars will look like "fly over the roads".

**Comment by natashadsouza** [comment]
Thank you for the suggestion @wobistdu 
We have included it in our enhancement requests.
We will let you know once we support 3D map and position.
Currently closing this issue!
