### ISSUE TITLE
Question: Can we visualize point cloud data using Dreamview?

### ISSUE THREAD

**Issue by huyichen19950417** [ApolloAuto/apollo#6909]
### Apollo version:

- **Apollo 3.0**

### Problem:
**I wonder if we can visualize our own point cloud data in Dreamview just like rviz. I have tried to visualize my own point cloud data in dreamview by publishing the data into the topic "/apollo/sensor/velodyne64/compensator/PointCloud2". I have lit up the button of "velodyne" in the Dreamview, but cannot visualize the point cloud. Have I done it in a wrong way? Or is there a correct way/tutorial about visualizing point cloud data in Dreamview?** 

### Screenshots:
![pub_to_apollo](https://user-images.githubusercontent.com/42275638/53005744-2417e400-3434-11e9-82a0-92218ecbc1e1.png)
![screenshot_dreamview_1](https://user-images.githubusercontent.com/42275638/53005872-65a88f00-3434-11e9-8a21-a79a1dfb1936.png)

**Comment by unacao** [comment]
You are right in feeding point cloud data to the topic /apollo/sensor/velodyne64/compensator/PointCloud2. To turn on the visualization, please go to "Layer Menu" on the left sidebar, then turn on "Point Cloud" under "Perception" module.

**Comment by vlin17** [comment]
Have you tired turning on "Layer Menu" -> "Perception" -> "Point Cloud" ?

**Comment by htabani** [comment]
We have several bags that they do not contain point clouds. From where we can access to the point clouds data? We are unable to generate our own point cloud data since we do not have any LiDAR sensor.

**Comment by huyichen19950417** [comment]
I have solved this problem by feeding a localization message into "/apollo/localization/pose" topic. It seems that at least we need the message from these two topics to visualize our own point clouds in dreamview.

**Comment by huyichen19950417** [comment]
> We have several bags that they do not contain point clouds. From where we can access to the point clouds data? We are unable to generate our own point cloud data since we do not have any LiDAR sensor.

We can download rosbags with point cloud from apollo official website.

**Comment by huyichen19950417** [comment]
> You are right in feeding point cloud data to the topic /apollo/sensor/velodyne64/compensator/PointCloud2. To turn on the visualization, please go to "Layer Menu" on the left sidebar, then turn on "Point Cloud" under "Perception" module.

Thank you very much ! :)
