### ISSUE TITLE
Lexus model supported

### ISSUE THREAD

**Issue by kkhitsko** [ApolloAuto/apollo#6910]
Please tell me which model of Lexus vehicle is supported?

**Comment by natashadsouza** [comment]
@kkhitsko Lexus RX 450h

**Comment by kkhitsko** [comment]
As I understand, this vehicle is supported only with pacmode3 module?

**Comment by natashadsouza** [comment]
@kkhitsko could you be more specific?

**Comment by kkhitsko** [comment]
As I can see CAN indexes in [repository ](https://github.com/ApolloAuto/apollo/tree/master/modules/canbus/vehicle/lexus/protocol) for steering, acceleration, brake etc. is different from indexes from Lexus RX450 CAN indexes. This   CAN indexes the same as indexes for pacmode CAN module from [Autonomustuff](https://github.com/astuff/pacmod1_2_dbc/blob/master/as_pacmod_v2.dbc). Also, I can see from [proto](https://github.com/ApolloAuto/apollo/blob/master/modules/canbus/proto/lexus.proto), Lexus vehicle state has 'pacmod_fault' fields. 

Based on this and my research on the Lexus canbus, I came to the conclusion that you added support for the Lexus using the module pacmode3 and I had a question, whether you would add Lexus support for other modules, like esd_can and others?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
