### ISSUE TITLE
Why Apollo stitches reference line? Just for saving computation resource?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6914]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by JasonZhou404** [comment]
For now, we don't support offline reference line smoothing because of the complexity of city lane network. In current implementation, stitching is for stabilizing reference line and saving computation effort

**Comment by natashadsouza** [comment]
Closing this issue. Feel free to reopen it if you have additional questions @KevinYuk
