### ISSUE TITLE
Any plan for supporting Nvidia RTX 2080?

### ISSUE THREAD

**Issue by junjieshen** [ApolloAuto/apollo#6916]
Hi,

I wonder if Apollo is going to support the new 20 series GPUs such as RTX 2080? 

As indicated in another [issue](https://github.com/ApolloAuto/apollo/issues/4233), Apollo comes with a pre-compiled version of Caffe which doesn't support new GPU architectures such as Volta. Is this still the case in version 3.5? If not, would Apollo provide support in next releases for 20 series GPUs?

Thanks,
Junjie

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by deepaktalwardt** [comment]
@techoe @natashadsouza Can you please explain if perception works on RTX 20-series? This series is also based on Turing architecture, same as the GTX 10- series. Would perception have any issues with these GPUs?

**Comment by techoe** [comment]
We cannot verify it at this moment since we do not have RTX_2080 in-house. I would appreciate if someone test with different GPUs and let us know. Thank you!

**Comment by michaelowenliu** [comment]
@junjieshen @techoe I am using RTX2070, and succeed following the official build/install instructions.

**Comment by deepaktalwardt** [comment]
@michaelowenliu can you confirm that Perception module works properly as well?

**Comment by michaelowenliu** [comment]
@deepaktalwardt could you tell me how to confirm it? I can try it. Currently I just finished the build/installation without hardware and see the dreamview demo.

**Comment by deepaktalwardt** [comment]
@michaelowenliu You can follow the step by step instructions here: apollo/docs/howto/how_to_run_perception_module_on_your_local_computer.md

Thank you for trying this out! Waiting to hear the results

**Comment by michaelowenliu** [comment]
@deepaktalwardt, Hi

[perception]  ]. sampled_right_width_[0.814828] is too small. It should be larger than half vehicle width[1.05].
[perception]  E0321 14:17:33.081907 19244 hdmap_common.cc:183] [mainboard] lane[id = id: "11265_1_-1"
[perception]  ]. sampled_right_width_[0.817991] is too small. It should be larger than half vehicle width[1.05].
[perception]  E0321 14:17:33.081920 19244 hdmap_common.cc:183] [mainboard] lane[id = id: "11265_1_-1"

**Comment by junjieshen** [comment]
@michaelowenliu Hi, have you tried to run "./apollo.sh test_gpu". I remember my build succeed, but the perception tests failed.

**Comment by michaelowenliu** [comment]
@junjieshen Hi, what outputs do you expect if it fails or succeed? I am just an beginner on Apollo.

**Comment by fzd9752** [comment]
Hi @michaelowenliu,

It will report fails after you run `./apollo.sh test_gpu`. Also you can find "Error" in `/apollo/data/log/perception.out` file if the perception module could not work properly.

I've a RTX2070 as well. Can you share the configuration of your host, includes OS version, Nvidia driver version, Cuda version and so on? It will be really appreciate.

**Comment by penghuihuang** [comment]
@michaelowenliu Hello, I tried 2070 with ubuntu 16.04, apollo 3.0, nvidia driver 430.14, doesn't work for me, could you please share some knowledge about how you made it? Thank you a lot!

**Comment by michaelowenliu** [comment]
@penghuihuang Hi, it also failed. Now I don't have any plan on it.

**Comment by usasos000** [comment]
I have the same issues here,
Now , I can not buy new 1080 in market because it has stop production over half year.
the 2080 looks like conflict with apollo kernel
Anyone Run 2080 on real car successfully,please teach me

**Comment by Nikita240** [comment]
Yep, running into a problem with an RTX 2080 Max-Q as well.

```
Kubuntu 19.04
nvidia-driver-418
cuda-10.1
apollo-5.0
```

The docker container gets shipped with cuda-8.0. This means that when you build apollo inside docker, you're building it with a version of cuda which is incompatible with your GPU. 

```bash
F0922 16:52:46.091820 31200 permute_layer.cu:78] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
```

[Meaning of "Invalid Device Function"](https://stackoverflow.com/a/33276793)

![image](https://user-images.githubusercontent.com/6479817/65396670-81bf3680-dd5d-11e9-808d-be24d0704345.png)

_Note: RTX-series cards use the **Turing** architecture_

[CUDA GPU architecture compatibility](https://en.wikipedia.org/wiki/CUDA#GPUs_supported)

Time to update the CUDA version used by Apollo?

**Comment by Autofoxsys** [comment]
Yes indeed, an updated version of cuda would be much appreciated.
From what I see on NVIDIA's website, the most recent architecture for which there are specific automotive products is **Volta** - with their JETSON AGX XAVIER SERIES.

**Comment by srirambadri** [comment]
Hi @Nikita240 ,

I'm having problems with my rtx2080ti gpu.

When i run ./apollo.sh test_gp, the perception module throws an error. But it's not the same as yours.

CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

Do you know if this could be because of the same reason as yours, that the Turing architecture is not supported by apollo, as I don't get any message saying my GPU is invalid

**Comment by AIasd** [comment]
Hi!
Just wonder if there is update on this issue or any plan to support the Turing architecture in the near future?

**Comment by Avps1** [comment]
Hi,
Is NVIDIA RTX 2080 supported now for Apollo 5.0 ?

**Comment by faysalhossain2007** [comment]
Will it be wise to buy RTX 2080 now and wait for the support from Apollo 5.0? In the meantime, try to build the Apollo using CPU?

**Comment by AIasd** [comment]
Hi,
Will NVIDIA RTX 2080 be supported in the near future?

**Comment by lemketron** [comment]
> Will NVIDIA RTX 2080 be supported in the near future?

I believe current apollo/master supports the RTX2080.

**Comment by AIasd** [comment]
> > Will NVIDIA RTX 2080 be supported in the near future?
> 
> I believe current apollo/master supports the RTX2080.

That's great! Do you have any idea on if it will be supported by carla or lgsvl?

**Comment by storypku** [comment]
> > Will NVIDIA RTX 2080 be supported in the near future?
> 
> 
> 
> I believe current apollo/master supports the RTX2080.

Not yet，actually. RTX 2080 cards will be supported in a month or two，depending on our progress.

**Comment by AlexandrZabolotny** [comment]
> > > Will NVIDIA RTX 2080 be supported in the near future?
> > 
> > 
> > I believe current apollo/master supports the RTX2080.
> 
> Not yet，actually. RTX 2080 cards will be supported in a month or two，depending on our progress.

**Could you inform in this issu when you solve this problem?**

**Comment by lemketron** [comment]
> > > Will NVIDIA RTX 2080 be supported in the near future?
> > 
> > 
> > I believe current apollo/master supports the RTX2080.
> 
> Not yet，actually. RTX 2080 cards will be supported in a month or two，depending on our progress.

@storypku I'm confused... Doesn't apollo/master already support the RTX cards? I've used it on my 15" Razer Blade which has a RTX2070, along with the LGSVL Simulator as documented on the [LGSVL Simulator](https://www.lgsvlsimulator.com/docs/apollo-master-instructions/) site (though it maxes out all 12 cores and can exhaust the 8GB of GPU memory in my laptop which can cause apollo modules to crash).

A desktop workstation with a RTX 2080 Ti (with 11GB of GPU memory) would likely handle it more easily, but another option is to run Apollo and Simulator on separate machines which is my preferred setup.

Are you just saying that master has not hit "release" status yet for the next version of apollo? Or are there still known issues running apollo master on an RTX card?  Thanks!

**Comment by lemketron** [comment]
> Compute capabilities specified here was for SMs=[3.0,6.1]. RTX 2080 Ti cards are running in a backward-compatible state.

@storypku That's interesting, thanks. I noticed that `cuda_library.bzl` has not changed since apollo 5.0 which crashed when running on the RTX2080 but now in apollo master it does seem to run without crashing. So I'm guessing something else was done to fix this since 5.0, though it sounds like you're saying it's perhaps not running as optimally as it could if it were fully supported rather than running in backward-compatible mode.

In any case it will be great to have full official support when it is ready.  Thanks for the update!

**Comment by ChihweiLHBird** [comment]
> > has not hit "release" status yet fo
> 
> Sorry for my not-so-exact expression.
> In `tools/cuda_library.bzl`:
> 
> ```
> cuda_arch = " ".join([
>     "-arch=sm_30",
>     "-gencode=arch=compute_30,code=sm_30",
>     "-gencode=arch=compute_50,code=sm_50",
>     "-gencode=arch=compute_52,code=sm_52",
>     "-gencode=arch=compute_60,code=sm_60",
>     "-gencode=arch=compute_61,code=sm_61",
>     "-gencode=arch=compute_61,code=compute_61",
> ])
> ```
> 
> Compute capabilities specified here was for SMs=[3.0,6.1]. RTX 2080 Ti cards are running in a backward-compatible state.

@storypku Can you tell me is RTX 2080 supported by `pre6` version of Apollo? We plan to buy a GPU and would like to know what's the best GPU that is supported by Apollo at this time or a near future. Thank you!

**Comment by storypku** [comment]
> > > has not hit "release" status yet fo
> > 
> > 
> > Sorry for my not-so-exact expression.
> > In `tools/cuda_library.bzl`:
> > ```
> > cuda_arch = " ".join([
> >     "-arch=sm_30",
> >     "-gencode=arch=compute_30,code=sm_30",
> >     "-gencode=arch=compute_50,code=sm_50",
> >     "-gencode=arch=compute_52,code=sm_52",
> >     "-gencode=arch=compute_60,code=sm_60",
> >     "-gencode=arch=compute_61,code=sm_61",
> >     "-gencode=arch=compute_61,code=compute_61",
> > ])
> > ```
> > 
> > 
> > Compute capabilities specified here was for SMs=[3.0,6.1]. RTX 2080 Ti cards are running in a backward-compatible state.
> 
> @storypku Can you tell me is RTX 2080 supported by `pre6` version of Apollo? What about `master` branch? We plan to buy a GPU and would like to know what's the best GPU that is supported by Apollo at this time or a near future. Thank you!

RTX 2080 cards was fully supported by the `master` branch. As for `pre6`,  I am afraid RTX 2080 would run in backward compatible state only. There was no easy way for `pre6` to take full advantage of RTX 2080 cards. And that's the main reason we made great effort to breaking upgrade this new `master` branch.

**Comment by storypku** [comment]
> > > > has not hit "release" status yet fo
> > > 
> > > 
> > > Sorry for my not-so-exact expression.
> > > In `tools/cuda_library.bzl`:
> > > ```
> > > cuda_arch = " ".join([
> > >     "-arch=sm_30",
> > >     "-gencode=arch=compute_30,code=sm_30",
> > >     "-gencode=arch=compute_50,code=sm_50",
> > >     "-gencode=arch=compute_52,code=sm_52",
> > >     "-gencode=arch=compute_60,code=sm_60",
> > >     "-gencode=arch=compute_61,code=sm_61",
> > >     "-gencode=arch=compute_61,code=compute_61",
> > > ])
> > > ```
> > > 
> > > 
> > > Compute capabilities specified here was for SMs=[3.0,6.1]. RTX 2080 Ti cards are running in a backward-compatible state.
> > 
> > 
> > @storypku Can you tell me is RTX 2080 supported by `pre6` version of Apollo? What about `master` branch? We plan to buy a GPU and would like to know what's the best GPU that is supported by Apollo at this time or a near future. Thank you!
> 
> RTX 2080 cards was fully supported by the `master` branch now. As for `pre6`, I am afraid RTX 2080 would run in backward compatible state only. There was no easy way for `pre6` to take full advantage of RTX 2080 cards. And that's the main reason we made great effort to breaking upgrade this new `master` branch.

**Comment by ChihweiLHBird** [comment]
> > > > has not hit "release" status yet fo
> > > 
> > > 
> > > Sorry for my not-so-exact expression.
> > > In `tools/cuda_library.bzl`:
> > > ```
> > > cuda_arch = " ".join([
> > >     "-arch=sm_30",
> > >     "-gencode=arch=compute_30,code=sm_30",
> > >     "-gencode=arch=compute_50,code=sm_50",
> > >     "-gencode=arch=compute_52,code=sm_52",
> > >     "-gencode=arch=compute_60,code=sm_60",
> > >     "-gencode=arch=compute_61,code=sm_61",
> > >     "-gencode=arch=compute_61,code=compute_61",
> > > ])
> > > ```
> > > 
> > > 
> > > Compute capabilities specified here was for SMs=[3.0,6.1]. RTX 2080 Ti cards are running in a backward-compatible state.
> > 
> > 
> > @storypku Can you tell me is RTX 2080 supported by `pre6` version of Apollo? What about `master` branch? We plan to buy a GPU and would like to know what's the best GPU that is supported by Apollo at this time or a near future. Thank you!
> 
> RTX 2080 cards was fully supported by the `master` branch now. As for `pre6`, I am afraid it would keep RTX 2080 run in backward compatible state only ... There was no easy way for `pre6` to take full advantage of RTX 2080 cards. And that's one of the top reasons we made great efforts to breaking upgrade this new `master` branch.

Thank you for your response.

**Comment by storypku** [comment]
As RTX 2080 is now fully supported by the `master` branch, I am going to close this issue. Thanks all for supporting Apollo. If you have any other questions, please file a new issue any time.

**Comment by lemketron** [comment]
> As RTX 2080 is now fully supported by the `master` branch, I am going to close this issue. Thanks all for supporting Apollo. If you have any other questions, please file a new issue any time.

Does this mean perception is working again in master on RTX 2080? If so, can you say which commit that was? I'm investigating a report that it's still not working (as of yesterday).

If it is fully working then this means RTX users can use stop using the pre6 branch and switch to master?  Thanks!

**Comment by lemketron** [comment]
Can we please re-open this issue until perception is fixed in master for the RTX-20x0 GPUs?

**Comment by storypku** [comment]
> Can we please re-open this issue until perception is fixed in master for the RTX-20x0 GPUs?

What about create a new issue ?
