### ISSUE TITLE
planning & control module generate many errors

### ISSUE THREAD

**Issue by fisher2020** [ApolloAuto/apollo#692]
hi,when i run rosbag play demo_1.5.bag,I found that /apollo/data/logs/ generate many errors,

such as planning module:
E1016 23:02:21.896390 13100 reference_line_provider.cc:86] Routing is not ready.
E1016 23:02:21.974669 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.075546 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.175655 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.275456 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.375326 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.396960 13100 reference_line_provider.cc:86] Routing is not ready.
E1016 23:02:22.475226 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.575094 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.675748 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.775797 13104 planning.cc:199] routing not ready; skip the planning cycle.
E1016 23:02:22.875663 13104 planning.cc:199] routing not ready; skip the planning cycle.

or control module:
W1016 23:02:58.422113 13557 control.cc:244] planning has no trajectory point.
E1016 23:02:58.422140 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.433187 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.443169 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.452208 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.463287 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.473215 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.483230 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.493230 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.503286 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.513042 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.
E1016 23:02:58.523180 13557 control.cc:200] Failed to produce control command:planning has no trajectory point.

which means that the apollo didnot run rightly/normally.i use exactly the docker environment.
in the hmi ,i turn on all the modules,
![image](https://user-images.githubusercontent.com/32329915/31649610-4193811c-b346-11e7-91cb-efe3a4bda363.png),,can anybody help me?thanks

**Comment by startcode** [comment]
The provided demo_1.5.bag is not compatible with the latest code now. we are working to upgrade it. I will update in this thread when we finish.

`E1016 23:02:21.974669 13104 planning.cc:199] routing not ready; skip the planning cycle.` -- click The 'Default Routing' or 'Edit Routing' button in dream view.
The control module is just complaining that it has not received any planning result.

**Comment by fisher2020** [comment]
hi,@startcode ,thanks for your reply. I clicked the  Default Routing button in dream view,but it still has the error E1016 23:02:21.974669 13104 planning.cc:199] routing not ready; skip the planning cycle. ;why did this  error happen?

**Comment by fisher2020** [comment]
in routing.in_dev_docker.root.log.INFO.20171017-001425.659,it shows that :
Log file created at: 2017/10/17 00:14:25
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1017 00:14:25.022639   659 routing.cc:38] Use routing topology graph path: modules/map/data/demo/routing_map.txt  

and in routing.out it shows that:

[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/repeated_field.h:1481] CHECK failed: (index) >= (0):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) >= (0):

**Comment by ycool** [comment]
@fisher2020  to run rosbag play demo_1.5.bag, it doesn't need start planning, control, etc node. You only need start dreamview node(map selects: sunnyvale loop) to see the demo. The bag contains planning, control, etc messages.

**Comment by fisher2020** [comment]
@ycool ,thank you for your replay. I can see the demo in the dreamview as your suggestions. and now I want to test/debug the modules(such as planning module ) through play the bag(play the bag will send data of topics to the modules ).  but the planning will generate many errors at Planning::RunOnce()function, the error shows that routing is not ready..but I can not successfully lanuch the routing module, the module fails in the function apollo::routing::FindAnchorPoint():
  double rate = (StartS() + EndS()) / 2.0 / Length();    (div by 0 trigger the fail)
 trace: 
apollo::routing::TopoNode::FindAnchorPoint (this=0x13b7ec0) at modules/routing/graph/topo_node.cc:134
134     
int anchor_index = static_cast<int>(total_size * rate);(gdb) bt 
#0  apollo::routing::TopoNode::FindAnchorPoint (this=0x13b7ec0) at modules/routing/graph/topo_node.cc:134
#1  0x00000000006c098f in apollo::routing::TopoNode::Init (this=0x13b7ec0) at modules/routing/graph/topo_node.cc:111
#2  0x00000000006c0564 in apollo::routing::TopoNode::TopoNode (this=0x13b7ec0, node=...) at modules/routing/graph/topo_node.cc:96
#3  0x0000000000694bfb in apollo::routing::TopoGraph::LoadNodes (this=0x13b7db0, graph=...) at modules/routing/graph/topo_graph.cc:41
#4  0x000000000069501f in apollo::routing::TopoGraph::LoadGraph (this=0x13b7db0, graph=...) at modules/routing/graph/topo_graph.cc:78
#5  0x000000000053df19 in apollo::routing::Navigator::Navigator (this=0xe352e0, topo_file_path="modules/map/data/demo/routing_map.txt") at modules/routing/core/navigator.cc:109
#6  0x00000000004160f8 in apollo::routing::Routing::Init (this=0x7fffffffdfe0) at modules/routing/routing.cc:39
#7  0x000000000042613a in apollo::common::ApolloApp::Spin (this=0x7fffffffdfe0) at modules/common/apollo_app.cc:41
#8  0x0000000000415572 in main (argc=1, argv=0x7fffffffe188) at modules/routing/main.cc:21

do you know the reason?

**Comment by jmtao** [comment]
@fisher2020 demo_1.5.bag is for demo/display purpose. The routing msg recorded in it may be obsolete since we've had a few map updates. When you run planning module on your own, the planning module is reading from the latest map, which may not be compatible with the routing msg recorded in this bag. That caused the above failures. 

If you want to run your own planning module using this bag, you'll need to
(1) filter the existing planning msg from this bag first (using "rosbag filter" command, or just download "demo_1.5.np.bag" as @startcode mentioned above)
(2) generate routing for your planning module to read.

In DreamView, there's a "Route Editing" menu on the left menu panel. We are going to add a manual on how to use it later. You probably also can figure out how to use it. It is pretty straight-forward.

Thanks!
