### ISSUE TITLE
Apollo 3.5 appears to have no Lane Tracking?

### ISSUE THREAD

**Issue by snuffysasa** [ApolloAuto/apollo#6921]
In Apollo 3.5, I have throughly read through the perception module code.

It appears that there is no Lane Tracking, as in no Lane history, matching detection to previous frames, and no filtering such as a Kalman Filter or Particle filter for processing Lane Lines.

Is this correct?  Or have I missed something? Thanks

**Comment by techoe** [comment]
We detect lane line type (L0, L1, L2, R0, R1, R2,...) directly from a network. Therefore, we don't need to track lane lines any more. Please check the most recent lane line detection code.

**Comment by snuffysasa** [comment]
Thank you @techoe 

We ended up implementing our own lane tracking...

However, I am confused why you say tracking is not needed....? Isn't there other reasons to have lane tracking, such as motion estimation, prediction, stability, and filtering out bad detections?

**Comment by techoe** [comment]
When each lane line segmentation results provide lane types (L0, L1, R0, ...). We can simply sample points . To handle bad detection, the RANSAC based line fitting algorithm is added as a post-processing.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thanks.
