### ISSUE TITLE
LiDAR - IMU Calibration: Unable to create calibration task

### ISSUE THREAD

**Issue by andytolst** [ApolloAuto/apollo#6929]
I'm trying to follow the steps in Lidar-IMU calibration guide:
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/apollo_lidar_imu_calibration_guide.md

when I try to create a new task here:
https://console.bce.baidu.com/apollo/calibrator/index/list

it asks for additional registration, and I've entered all the data, but I still can't create a new calibration task.
Please advice. Thanks.

**Comment by natashadsouza** [comment]
@andytolst have you tried creating a new account? Do you see an error message on the console page? If so please send us a screenshot. Thanks!

**Comment by andytolst** [comment]
@natashadsouza 
I login using my phone number and text message, go to 
https://console.bce.baidu.com/apollo/calibrator/index/list
and hit "New Task"

![baidu_calibration](https://user-images.githubusercontent.com/1422400/53269158-00a3a200-369d-11e9-946a-3c986454034c.jpg)

Enter all the details, it says it's submitted and "we will contact you in time" - that was 3 days ago
![baidu_cloud_submitted](https://user-images.githubusercontent.com/1422400/53269225-2d57b980-369d-11e9-937c-da922069eba0.jpg)

After that I'm still not able to create a new task:

![baidu_cloud2](https://user-images.githubusercontent.com/1422400/53269255-3ea0c600-369d-11e9-84e8-723f91579ebf.jpg)

**Comment by natashadsouza** [comment]
@andytolst we will have this checked. This guide was used for Apollo 2.0. But in the mean time, I would recommending using the tool in this [newer guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/multiple_lidar_gnss_calibration_guide.md). Let me know if you have any questions.

**Comment by andytolst** [comment]
@natashadsouza Thanks! I'll try that

**Comment by natashadsouza** [comment]
Great! Let me know if you have any questions.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @andytolst feel free to reopen it if you have additional questions.

**Comment by FelicxFoster** [comment]
@natashadsouza hello, I found the link of [calibration service page](https://console.bce.baidu.com/apollo/calibrator/index/list) has been  deactivated. Is there a new link? thx
