### ISSUE TITLE
Calling push_back on a non-vector object

### ISSUE THREAD

**Issue by robertliu219** [ApolloAuto/apollo#6945]
**Describe the bug**
In the file ./modules/perception/common/i_lib/pc/i_struct_s.h:706, the code tries to call push_back on a non-vector object, i.e., "voxels_[id].push_back(n);"

**To Reproduce**
Currently the method "bool VoxelGridXY<T>::Set()" is not called, so the compiler does not compile this buggy snippet. But I am trying to compile the code on ARM platform, and will have to call this non-sse4-optimized "bool VoxelGridXY<T>::Set()" method, and thus the compiler will report the compiling error.

**Expected behavior**
The expected code should be:
voxels_[id].**indices_**.push_back(n);

**Comment by techoe** [comment]
Thank you so much for finding the bug. The fix is in #7304.
