### ISSUE TITLE
How can I generate the background.jpg and it's information?

### ISSUE THREAD

**Issue by apppcs** [ApolloAuto/apollo#6951]
After check modules/map/data/sunnyvale_big_loop/background.jpg, I have two questions below :

1. How to generate the "background.jpg" from local_map/image/000/north/10/xxxxxxxx ?

2. How do you determine the parameters on xres, yres, mpp, xorigin, yorigin ?
		"sunnyvale_big_loop": {
			"mpp": 0.125,
			"xres": 24576,
			"yres": 16384,
			"xorigin": 587392,
			"yorigin": 4140800,
			"type": "default",
			"tileRange": 4
		},

**Comment by KitFung** [comment]
mpp = resolution
xorigin,yorigin = the world coordination of the (0,0) in the image
xres = the real x lrange / resolution
yres = the real y lrange / resolution

Then just use the above parameter to combine all the image in the image folder

**Comment by frontw** [comment]
Hi @KitFung!

Could you, please, give some details on this.

> Then just use the above parameter to combine all the image in the image folder

I have local lossy map, generated with msf_simple_map_creator.sh, same to issue creator. How could I combine it in one image (background.jpg)?
Is there any special script in Apollo or it's recommended to make own?

Thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
