### ISSUE TITLE
libpcl install directory is out of sync with velodyne drive dependency path

### ISSUE THREAD

**Issue by yuan8421** [ApolloAuto/apollo#696]
The libpcl will be installed in the directory 

> /usr/include/pcl*

 and 

> /usr/lib/libpcl*

However, to build velodyne driver, it depends on the directory 

> /usr/local/include/pcl*

 and 

> /usr/local/lib/libpcl*

**Comment by fy2462** [comment]
@yuan8421 you can set the softlink in the path /usr/local/include

**Comment by yuan8421** [comment]
@fy2462 Thank you for advise. I've already do that. It will be nice if others would not do so.

**Comment by xiaoxq** [comment]
Should have been fixed by the refactored dockerfile. Please refer to docker/build to have a try and file new issue if there is problem.

**Comment by yuan8421** [comment]
@xiaoxq Can I ask which commit fix this issue?

**Comment by xiaoxq** [comment]
You can check the history of this file: https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_pcl.sh

**Comment by yuan8421** [comment]
I just found it. Thx reply though.
