### ISSUE TITLE
the output of perception

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#6970]
Could anyone tell me that  the meaning of  the following parameters represent about the lane line.  
// equation X = c3 * Z^3 + c2 * Z^2 + c1 * Z + c0
  optional double c0_position = 4;
  optional double c1_heading_angle = 5;
  optional double c2_curvature = 6;
  optional double c3_curvature_derivative = 7;
I think c0 is the distance about the start point of the lane line to the vehicle,c2 represents that the  curvature of the lane line.And i want to know the reason that the curvature is calculated according to the curvature formula is different from this c2_curvature.
Can i get these parameters just like the course AdvanceLane_finding in the Udacity? Is this the same in the Apollo?
And i will really appreciate you if you can tell me how can i get them.

**Comment by techoe** [comment]
c[0..3] are the coefficients of cubic curve to represent curvy lane line. I don't know AdvanceLane_finding but this representation is quite intuitive. Please note that the origin of the coordinate system is the center of a rear axle.

**Comment by natashadsouza** [comment]
@quuen was your question resolved? Kindly close the issue if you have no more questions. Thank you for your interest in Apollo.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if the issue persists. Thanks.
