### ISSUE TITLE
the tool about relativemap_viewer

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#6971]
![xx](https://user-images.githubusercontent.com/45919445/53342922-15589200-394a-11e9-84d4-cfe1447c1d22.png)
Why is the  generated lane line by the perception module represented by green visualized as oblique rather than straight?
Why the right line of the generated lane line represented by blue color exceeded the perception lane on the right？

**Comment by yifeijiang** [comment]
It depends on:
1. how did you collect navigation line, e.g., how accurate they are?
2. how accurate is your localization?
3 what perception hardware and software were used?
4 what is the road condition? e.g., how clear is the lane marker? what is the lanes structure?
5 what is the vehicle status at the time of plot? 
If you could give more context of your question, others may understand your question better.

**Comment by quuen** [comment]
@yifeijiang Thanks for your reply!I just play the demo2.5 bag and feed some relative topics to generate raletive map and observe the relative map by this tool.

**Comment by techoe** [comment]
The diverging lane line shows incorrect camera parameters.

**Comment by quuen** [comment]
@techoe I generated the relative map by using the topic /apollo/perception/obstacles /apollo/canbus/chassis /apollo/localization/pose and navigation line extracted from demo 2.5 bag.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
