### ISSUE TITLE
Path Planning(M-step) DP search: why static obs cost calculation is based on Frenet coordinate system? moving obs cost calculation is based on Cartesian coordinate system?

### ISSUE THREAD

**Issue by KevinYuk** [ApolloAuto/apollo#6981]
I print the static obs bounding box (need convert from Frenet coordinate to Cartesian coordinate); while, for moving obs, just need directly print this min max corner(don't need convert).

![image](https://user-images.githubusercontent.com/20220399/53381485-db1fdc80-39ab-11e9-9a06-8133ee642b65.png)

**Comment by jmtao** [comment]
@KevinYuk I think you've pointed out why. In the line you marked as above, GetCostBetweenObsBoxes(), the bounding boxes of other obstacles along their trajectory are based on  Cartesian coordinate, provided by Prediction module.
