### ISSUE TITLE
when ADC is sidepassing  obstacle A, at stage_pass_obstacle, perception module gives a new obstacle at the front of obstacle A, can apollo 3.5 deal with this scence?

### ISSUE THREAD

**Issue by guqiangwei** [ApolloAuto/apollo#6991]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- ** Linux Ubuntu 16.04**:
- **Apollo installed from source **:
- **Apollo version 3.5**:

### Steps to reproduce the issue:
ps:
sometimes stage_approach_obstacle_stage/ stage_wait_on_point loop when planning running

**Comment by jmtao** [comment]
@guoweiwan In Apollo 3.5, the SidePass feature supports to side-pass static obstacle(s) if doable, and therefore we don't expect the targeted obstacle change or move.  Once we identify the obstacle to side-pass, we plan a trajectory based on its location, size etc.  And therefore if there's a NEW obstacle appears in front of it (I assume you meant to say very close), we won't "re-plan" for that. If our originally planned trajectory doesn't work  well to side-pass this NEW obstacle at the same time, we may fail. 
We'll provide better support in future release though. 

Hope this answered your question. 
Thanks for supporting Apollo!
