### ISSUE TITLE
why car stops at the junction

### ISSUE THREAD

**Issue by diff8911** [ApolloAuto/apollo#7005]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- after starting the dreamview, I open the SimControl mode and select module Routing and Planning，chose the first default routing
- the car runs well at start，but stops at a junction and  never starts again, as the followed picture.
![stop at junction](https://user-images.githubusercontent.com/46886815/53486503-dc442d00-3ac3-11e9-91f0-cc0f4b3010c5.png)

- **why this happen and how can I fix it?**

thank you very much.

**Comment by jmtao** [comment]
@diff8911 ego vehicle may stop at junction because of traffic rule (stop sign, traffic light, and etc).
You can switch to default view (vs Overhead view in your screen shot), to see the red stop fence. There's a sign attached to it, pretty self-explanatory what's the reason for this stop fence. 
Or you can use cyber_minor to view /apollo/planning topic, to see what's the stop reason for it.

**Comment by diff8911** [comment]
@jmtao Thank you for your reply. How can I change the red to green, or how can I just remove the fence?

**Comment by jmtao** [comment]
@diff8911 It depends on what's the stop reason in your case (red light, or stop sign).

**Comment by diff8911** [comment]
@diff8911 Could you please tell me how to turn the red light to green and how to remove the stop sign?

**Comment by diff8911** [comment]
@jmtao 
Could you please tell me how to turn the red light to green and how to remove the stop sign?

**Comment by hyunjaecho94** [comment]
I'm having a similar issue. The car stops at a traffic light and even after it turns green, the car does not move.

**Comment by jmtao** [comment]
@diff8911 
* for traffic-light, you can try "scripts/manual_light.sh", it would flip the current light color for you on the flu. 
* for stop-sign, you can't bypass the stop sign on the fly if your car is supposed to STOP. If you don't care about the stop-sign behavior and FEEL SAFE, you can disable stop-sign feature. The gflag is "enable_scenario_stop_sign" at 
https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/planning_gflags.h

**Comment by jmtao** [comment]
Hi @diff8911 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
