### ISSUE TITLE
how to use Apollo with my own simulation software

### ISSUE THREAD

**Issue by diff8911** [ApolloAuto/apollo#7006]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- using my own simulation software publish the followed topics to Apollo：/apollo/localization/pose, /apollo/canbus/chassis
- my simulation software subscribe the followed topic from Apollo: /apollo/control
- open dreamview, select Routing, Planning and Control module, make a routing in the RouteEditing panel and sent it
- **but the topic /apollo/control sent noting and the car stops.  And I can not chose the StartAuto botton. Why? How can I fix it？**
- **I noticed in the Module Delay panel the delay time of PerceptionObstacle and Prediction are red while the delay time of TrafficLight is white. What does the difference mean?**

Thank you very much.
![could not start](https://user-images.githubusercontent.com/46886815/53487395-76a57000-3ac6-11e9-8e95-06b879d9402f.png)

**Comment by vlin17** [comment]
1. From the screenshot, it seems like the planning module is not ready. Please check planning log under /apollo/data/log to see if there's any warning or error messages.
2. the StartAuto button is enabled when the planning module sends EngageAdvice as READY_TO_ENGAGE .
3. On Module Delay panel, a module's delay time will be highlight to red to capture user's attention if the module (except traffic light) has not been updated for 2 seconds.

Hope the information is enough for you to continue on using Apollo with your simulation software.
