### ISSUE TITLE
Oops! Something went wrong

### ISSUE THREAD

**Issue by Spatialghost** [ApolloAuto/apollo#7012]
Hi, i built Apollo 3.5. for Ubuntu 18.04 and when i starting Dreamview, i see error "Oops! Something went wrong". If somebody met same error, how to fix this error?
Thank you. 
![screenshot_9](https://user-images.githubusercontent.com/36438927/53505608-fdae1480-3ad5-11e9-9b8d-81df67b5c54d.png)

**Comment by natashadsouza** [comment]
@Spatialghost do you see any error messages in your terminal?

**Comment by Spatialghost** [comment]
> 
> 
> @Spatialghost do you see any error messages in your terminal?

Absolutely without any errors.

**Comment by natashadsouza** [comment]
Could you send me a screenshot of your console error messages? @Spatialghost

**Comment by natashadsouza** [comment]
Closing this issue as there has been no response in a while. Feel free to reopen if the issue persists.
