### ISSUE TITLE
Use Standard FastRTPS Package

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#7043]
Apollo's current version of FastRTPS seems to be old and modified. I cannot find the modified source files.

Packaging a standard 1.7.1 release of FastRTPS in docker will work. I'm not sure if the modifications are necessary.

Another solutions would be to release the original FastRTPS release and the related diff.

One of the bug fixes from FastRTPS that would be nice is https://github.com/eProsima/Fast-RTPS/issues/181.

**Comment by KitFung** [comment]
1. use 1.5..0 version
2. need to install to `/usr/local/fast-rtps`
3. Also need to move the fastcdr header and shared library to there
4. Need to change the data sending part. (Otherwise, it will have some issue while dealing with the '/0')

maybe it still need more change.
I hope baidu will also release their modified version asap.

**Comment by baowanyu** [comment]
@Fla3inH0tCheet0s

**Comment by baowanyu** [comment]
You can find FastRTPS 1.4.0 patch from another repo. https://github.com/ApolloAuto/apollo-platform/tree/master/ros/third_party

Upgrading FastRTPS is already in our plan. We will release it after full testing,

**Comment by quning78** [comment]
Closed for now. 

Please reopen if you have further questions. Thanks!

**Comment by sjtugjy** [comment]
@baowanyu 
Hi, 
I found that FastRTPS 1.4.0 from apollo-platform cannot work for CyberRT.

The compiler complains as follows:
cyber/service_discovery/topology_manager.cc:152:10: error: 'DROPPED_RTPSPARTICIPANT' is not a member of 'eprosima::fastrtps::rtps::DISCOVERY_STATUS'.

I am wondering which version and patch are used for CyberRT. 
Thanks.

@KitFung 
Hi, 
I also tried FastRTPS 1.5.0 and Fast-CDR-1.0.7. The compilation is OK.
But the generated executable cannot work well.
The example talker outputs the following warning: 
manager.cc:192] [talker] !message::ParseFromString(msg_str, &msg) is not met.
And the talker cannot talk to the listener.
Could you share a patch about your modification? 

Thanks.

**Comment by bhaskarsuper9000** [comment]
Sorry to comment on a closed issue, but just wondering if r5.0.0 is still using patched FastRTPS 1.4.0 or a does it come with a later version of FastRTPS? Any response is appreciated, thanks.

**Comment by jinfagang** [comment]
@bhaskarsuper9000  Also curiosity about this, but as far as I know (look into master codes) it's still fastrtps1.4 or fastrtps1.5 since some namespace it's still not changed.

For better work, we should using fastrtps 1.5.0 to work with it.

**Comment by weidezhang** [comment]
it's https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/FastRTPS_1.5.0.patch and built in docker already
