### ISSUE TITLE
Vehicle drives out of the map in Demo 2.5

### ISSUE THREAD

**Issue by Wang4758** [ApolloAuto/apollo#7058]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
* rosbag play demo.2.5.bag

So when I play the demo2.5.bag there was no lane showing. I checked the trajectory of the vehicle and also the map file, it turns out that the vehicle was actually driving out of the provided map. Is there a way to specify the start and end point of the vehicle so that it can drive on the lanes inside the map? I tried to change the destination point in Navigation mode. But I got 'Navigation info not received' all the time. Thanks

**Comment by XinrRunChao** [comment]
Can you share your download address about the demo.2.5.bag? I download from https://github.com/ApolloAuto/apollo/releases/download/v2.5.0/demo_2.5.bag, but the bag can not work!

**Comment by XinrRunChao** [comment]
Can you share your download websit about the demo.2.5.bag? I download from https://github.com/ApolloAuto/apollo/releases/download/v2.5.0/demo_2.5.bag, but the bag can not work!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
