### ISSUE TITLE
rosbag_to_record creates empty record file during conversion

### ISSUE THREAD

**Issue by ankita9017** [ApolloAuto/apollo#7060]
I am trying to convert a bag file to record file using the rosbag_to_record tool. However, it returns an empty record file:

![image](https://user-images.githubusercontent.com/30883964/53666346-be410e80-3c22-11e9-9ebc-f5c6c8e57123.png)

Is there something else that I need to do before I run the conversion?

### System information

- **OS Platform and Distribution**: Ubuntu 14.04
- **Apollo installed from**: Docker
- **Apollo version**: 3.5

**Comment by Eclipsehelio** [comment]
Would you please attach the result of 'rosbag info xxx.bag'? Maybe this file is corrupted.

**Comment by kyleApollo** [comment]
@akn9017 Please provide the bag you tried to convert and the full command you used for further investigation.

**Comment by natashadsouza** [comment]
@akn9017 waiting on your response. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
