### ISSUE TITLE
why the car is offset from the planned trajectory

### ISSUE THREAD

**Issue by diff8911** [ApolloAuto/apollo#7074]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 2.0

### Steps to reproduce the issue:
- using my own simulation software publish the followed topics to Apollo：/apollo/localization/pose, /apollo/canbus/chassis
- my simulation software subscribe the followed topic from Apollo: /apollo/control
- open dreamview, select Routing, Planning and Control module, make a routing in the RouteEditing panel and sent it
- **when the speed of the car is zero，the planned trajectory (the green thick curvy band) is perfect in front of the car**, as the followed picture:
![when car stopping](https://user-images.githubusercontent.com/46886815/53679614-bad48280-3d09-11e9-800f-3c4fbcbf5400.png)

- **after I press the Start Auto botton ,the car is good to move foward. But the car is offset from the planned trajectory to the right**, as the followed picture:
![when car moving](https://user-images.githubusercontent.com/46886815/53679619-bf00a000-3d09-11e9-9c1a-4d5b3a466f70.png)

- **Why this happens？ Are there something wrong when I simulate the /apollo/localization/pose topic？**
 Thank you very much.

**Comment by natashadsouza** [comment]
@diff8911 is it the same issue as #7122 ? If so could we close this issue and continue discussing it on that thread? Thanks!

**Comment by natashadsouza** [comment]
Closing this issue. Please continue discussing on #7122 thanks!
