### ISSUE TITLE
Cannot run localization module and visualization tool in Apollo 3.0

### ISSUE THREAD

**Issue by flnlucifer** [ApolloAuto/apollo#7077]
- **OS Platform and Distribution (Linux Ubuntu 16.04)
- **Apollo installed from (sourcey)
- **Apollo version (3.0)

### Steps to reproduce the issue:
I just using apollo2.0 data(demo-multi_sensor_fusion_localization-data-apollo-2.0.tar.gz) to run localization module in Apollo 3.0 framework.
Then I suffer the error.
[ERROR] [1551679617.692385297]: Client [/localization] wants topic /apollo/sensor/gnss/corrected_imu to have datatype/md5sum [pb_msgs/CorrectedImu/81aef4a818ce273a8af85a440ccdb0f7], but our version has [pb_msgs/Imu/bdef0ba51869607ed95736d41e80c1f5]. Dropping connection.
and when remove the corrected imu msg , I can play the bag. But when I try to run visualization tool,
I suffered:
Load lidar extrinsic succeed.
Resolution: 0.125
Dataset: /user/ad-eap/dev/liuyu43/pipeline_seqs/ieout_sunnyvale_region_1214/compensated_pcd//seqs/
Loaded the map configuration from: /apollo/DATA_PATH/local_map/config.xml.
Load map config succeed.
Gtk-Message: Failed to load module "canberra-gtk-module"
[ WARN] [1551682003.420837714]: transport file: /home/tmp/ros/etc/ros/transport_mode.yaml is not map
[ WARN] [1551682003.420941373]: Parse transport_mode file failed
Un-organized-point-cloud
Un-organized-point-cloud
Un-organized-point-cloud
Un-organized-point-cloud
Un-organized-point-cloud
Un-organized-point-cloud
E0304 14:46:45.229487 10934 visualization_manager.cc:242] The queried buffer is empty.
E0304 14:46:45.230624 10934 visualization_manager.cc:242] The queried buffer is empty.
Un-organized-point-cloud
E0304 14:46:45.332228 10934 visualization_manager.cc:242] The queried buffer is empty.
E0304 14:46:45.332300 10934 visualization_manager.cc:242] The queried buffer is empty.
Un-organized-point-cloud

Could anyone help to solve the problem?

**Comment by flnlucifer** [comment]
localization log:
Log file created at: 2019/03/04 14:06:11
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0304 14:06:11.557689  7087 msf_localization.cc:152] map: /apollo/DATA_PATH/local_map
E0304 14:06:11.557896  7087 msf_localization.cc:153] lidar_extrin: modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml
E0304 14:06:11.557910  7087 msf_localization.cc:154] lidar_height: modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
E0304 14:06:11.558887  7087 msf_localization.cc:219] Ant imu lever arm file: modules/localization/msf/params/gnss_params/ant_imu_leverarm.yaml
E0304 14:09:32.997985  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 17.53336954116821
E0304 14:09:50.556952  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 17.53336954116821
E0304 14:10:08.114079  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 17.53336954116821
E0304 14:32:37.240799  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 6.41836142539978
E0304 14:32:54.800402  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 17.53336954116821
E0304 14:44:21.869216  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 2.993361473083496
E0304 14:44:39.426017  7118 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423892.159559delay time: 17.53336954116821

**Comment by dlutguobin** [comment]
same problem....

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
