### ISSUE TITLE
Adding a new installer and mounting a new image. 

### ISSUE THREAD

**Issue by shifakhan4892** [ApolloAuto/apollo#7079]
Hi Apollo Developers, 
In my local machine I added a new installer in docker/build/installers and then created a new docker image using the ./build_dev.sh ./dev.x86_64.dockerfile, pushed it into my local apolloauto/apollo repo. 

Executed  ./dev_start -l |-t tag number

I cannot start a container with the formed image. Am I missing out any steps ?

**Comment by aboarya** [comment]
@shifakhan4892 those sound like the right steps, except maybe the `|` in `./dev_start -l |-t tag number` but maybe that's just a typo in your question.

What's the exact error you are seeing?

**Comment by shifakhan4892** [comment]
@aboarya thanks for the reply. I am getting the following error : 

shifa@shifa-HP-Laptop-15-db0xxx:~/Downloads/apollo/docker$ ./scripts/dev_start.sh --tag dev-x86_64-20190304_1454
[sudo] password for shifa: 
fetch: Fetching reference refs/heads/master
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20190304_1454 ...
Error response from daemon: manifest for apolloauto/apollo:dev-x86_64-20190304_1454 not found
[ERROR] Failed to pull docker image.

**Comment by aboarya** [comment]
Hi @shifakhan4892 
the exact command should be:
```
# ./scripts/dev_start.sh -l (small case L) -t dev-x86_64-20190304_1454
shifa@shifa-HP-Laptop-15-db0xxx:~/Downloads/apollo/docker$ ./scripts/dev_start.sh -l -t dev-x86_64-20190304_1454
```
If that still fails, please run 
```
shifa@shifa-HP-Laptop-15-db0xxx: docker images
```
this should list all the images that you have locally.  verify that `dev-x86_64-20190304_1454` is the correct image

**Comment by shifakhan4892** [comment]
@aboarya thanks for the reply. I tried your suggestion 

shifa@shifa-HP-Laptop-15-db0xxx:~/Downloads/apollo/docker$ ./scripts/dev_start.sh -l -t dev-x86_64-20190304_1454
[sudo] password for shifa: 
fetch: Fetching reference refs/heads/master
[INFO] Start docker container based on local image : apolloauto/apollo:dev-x86_64-20190304_1454
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:4bd59bffdf105c52b11a5663a6342d9f70d42d5f1beb9dc7ae68884ae5ea32fd
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
3f3572eeacc5cc5c5fe026f9c04b2888ec8d7221b9d6369855145b1f2c9cb966
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_loop-latest
87a72aba1f9b4db66f5108c6f290c92cd1da36f4a17dc67a16de6668abdf20b4
map_volume-sunnyvale_with_two_offices-latest: Pulling from apolloauto/apollo
Digest: sha256:9f94f738f3f84521dfb14f1d46c769f1f44ff430f479712e1c0ece5fe2772907
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest
800da44fbbcbaa763fa375a0102347200e58cca9ff29b78740c32ac447e9e9fb
map_volume-san_mateo-latest: Pulling from apolloauto/apollo
Digest: sha256:7e7cbce6269d4f45f2fd087ced8406a3f45c6cbcc366e38af5458e8bcbdf2ba3
Status: Image is up to date for apolloauto/apollo:map_volume-san_mateo-latest
8c2da6ca96577c9a36da25d73d2b73d52eaf1946a389c1a3aba2d7c6f22c03b2
map_volume-san_mateo_hdl64-latest: Pulling from apolloauto/apollo
Digest: sha256:44692970190b520a4eb876b3740a54da0a255d8b51848c1da8c7217bca99d067
Status: Image is up to date for apolloauto/apollo:map_volume-san_mateo_hdl64-latest
302b840819e5dd0faf2685f7cb1d3fc58e7053e07888282663f205ad2087ef21
modprobe: FATAL: Module nvidia not found.
modprobe: FATAL: Module nvidia-uvm not found.
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:94af1ac560730db7daf192ebf7b091f88059e62e425ceccd6375fbf4578e7f3f
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
aeb82b50fa759d60582e43c59c906c78aa5a664817fa379fb9e06244a3b722fb
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
f5c5776f879922e42d1742fd1a3dd891c899dda050fd01c43b5badb0a93a31ba
[INFO] Starting docker container "apollo_dev_shifa" ...
3601c9a18b7d82e9871dbe76f8b1644f3e38e538a6263c5fd9dcf7c30336dd40
docker: Error response from daemon: linux spec user: unable to find user apollo: no matching entries in passwd file.
[ERROR] Failed to start docker container "apollo_dev_shifa" based on image: apolloauto/apollo:dev-x86_64-20190304_1454

and the "docker images" shows the following 

 shifa@shifa-HP-Laptop-15-db0xxx:~/Downloads/apollo/docker$ docker images
REPOSITORY          TAG                                            IMAGE ID            CREATED             SIZE

apolloauto/apollo   dev-x86_64-20190304_1454                       2d95f6a6aacb        2 days ago          4.48GB
apolloauto/apollo   dev-x86_64-20190228_1414                       62efd78bc092        3 days ago          7.03GB
nvidia/cuda         8.0-cudnn7-devel-ubuntu14.04                   3f15c1f57d38        4 weeks ago         2.02GB
apolloauto/apollo   map_volume-san_mateo_hdl64-latest              c41de576fabe        8 weeks ago         168MB
apolloauto/apollo   map_volume-san_mateo-latest                    f714fb7b6c41        8 weeks ago         195MB
apolloauto/apollo   map_volume-sunnyvale_with_two_offices-latest   c57193dfbb94        8 weeks ago         373MB
apolloauto/apollo   localization_volume-x86_64-latest              5486a0d71a97        3 months ago        5.43MB
apolloauto/apollo   map_volume-sunnyvale_big_loop-latest           ae6c3090ea38        5 months ago        438MB
apolloauto/apollo   yolo3d_volume-x86_64-latest                    6a9cbf71163e        6 months ago        275MB
apolloauto/apollo   map_volume-sunnyvale_loop-latest               36dc0d1c2551        13 months ago       906MB

 I feel there is a problem with my local repo or something. Do you think that must be an issue ?

**Comment by aboarya** [comment]
@shifakhan4892 The actual error is:
```
docker: Error response from daemon: linux spec user: unable to find user apollo: no matching entries in passwd file.
```
I ran into this also when I built my own container.  
What worked for me; and I am not sure it's the correct solution, is to comment out [install_user.sh](https://github.com/ApolloAuto/apollo/blob/master/docker/build/dev.x86_64.dockerfile#L70) from `dev.x86_64.dockerfile`.

Then update [USER apollo](https://github.com/ApolloAuto/apollo/blob/master/docker/build/dev.x86_64.dockerfile#L75) to `USER root`.

Then rebuild the container
```
./build_dev.sh ./dev.x86_64.dockerfile
```
Of course you'll get a new tag so you have to update the `dev_start` command.
```
shifa@shifa-HP-Laptop-15-db0xxx:~/Downloads/apollo/docker$ ./scripts/dev_start.sh -l -t dev-x86_64-<new-time>
```
The error you're seeing is in this [line of code](https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_user.sh#L24) but it fails silently so the script does not fail to build the container. 

Then when you try to start it, it can't find that user.  So work-around is to use the `root` user, which is OK, because during the container launch, [this script](https://github.com/ApolloAuto/apollo/blob/master/scripts/docker_adduser.sh) is called by the `dev_start.sh` script, and a user with the same ID and Group ID as your local system user `shifa` will be created on the container

**Comment by shifakhan4892** [comment]
Thanks a lot for the help. It works now :)
