### ISSUE TITLE
How to make my own demo

### ISSUE THREAD

**Issue by pancumtneu** [ApolloAuto/apollo#7096]
I have read  some articles about modifying the code, and one question puzzles me.
How do I make a simple demo (in DreamView because I don't have the hardware)? For example, control the car, go straight, turn, where should I modify the code, and then how to compile and run? Is it in the docker environment  window? If we modify the code, will it damage the downloaded original source code.When I finish my code with my own algorithm HOW can I simulate it in dreamview simulate .

**Comment by aboarya** [comment]
@pancumtneu There is a specific simulator for what you are talking about that's different from Dreamview.  The simulator is called [Dreamland](https://azure.apollo.auto/).  It's hosted on Microsoft Azure, and is free to join.  

Once you create an account and read through the docs, you'll find an email address that you can use to request full access.

The way it works is: you make an algorithm change, then choose a simulation scenario, then submit.  Once it's finished, you can view the results in a Dreamview that's hosted online.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
