### ISSUE TITLE
planning in navigation mode

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#7098]
Is the trajectory point generated by the planning module in the navigation mode a point in the enu coordinate system or the flu coordinate system ?

**Comment by quuen** [comment]
emm......

**Comment by natashadsouza** [comment]
@quuen it is the FLU coordinate system

**Comment by quuen** [comment]
@natashadsouza Thanks for your reply!But i still have a question about how to compute longitudinal Errors in the file /apollo/modules/control/controller/lon_controller.cc.

  auto matched_point = trajectory_analyzer->QueryMatchedPathPoint(
      VehicleStateProvider::instance()->x(),
      VehicleStateProvider::instance()->y());

I think x,y represents the point in the enu coordinate system,in the navigation mode the trajectory point is in the flu coordinate system.And i do not see Coordinate transformation,so how are they calculated in the different coordinate system?

**Comment by quuen** [comment]
em...

**Comment by quuen** [comment]
@natashadsouza I still have some doubts,would you mind explain it?

**Comment by quuen** [comment]
@natashadsouza I still have some doubts,would you mind explaining it?

**Comment by natashadsouza** [comment]
@quuen the algorithms are all written in the FLU coordinate system. And the Coordinate transformation does happen within the code itself.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
