### ISSUE TITLE
cannot see poind cloud in dreamview

### ISSUE THREAD

**Issue by flnlucifer** [ApolloAuto/apollo#7115]
**OS Platform and Distribution (Linux Ubuntu 16.04)
**Apollo installed from (sourcey)
**Apollo version (3.0)

### Steps to reproduce the issue:
I just using apollo2.0 data(demo-multi_sensor_fusion_localization-data-apollo-2.0.tar.gz) to run localization module in Apollo 3.0 framework. I can see the localization status and point cloud by localization online visualization tool, but I can't see point cloud data in Dreamview. Only the localization module was running.

Here is the error log of localization module.

Log file created at: 2019/03/05 17:56:38
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0305 17:56:38.638064 11897 msf_localization.cc:152] map: /apollo/DATA_PATH/local_map
E0305 17:56:38.638438 11897 msf_localization.cc:153] lidar_extrin: modules/localization/msf/params/velodyne_params/velodyne64_novatel_extrinsics_example.yaml
E0305 17:56:38.638456 11897 msf_localization.cc:154] lidar_height: modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
E0305 17:56:38.640888 11897 msf_localization.cc:219] Ant imu lever arm file: modules/localization/msf/params/gnss_params/ant_imu_leverarm.yaml
E0305 17:57:22.654304 11958 base_map_node.cc:305] map node compress ratio: 0.135361
E0305 17:57:22.786645 11958 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4587 Northing: 32352)
E0305 17:57:22.866958 11958 base_map_node.cc:305] map node compress ratio: 0.254251
E0305 17:57:22.998772 11958 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4588 Northing: 32352)
E0305 17:57:23.038808 11958 base_map_node.cc:305] map node compress ratio: 0.129855
E0305 17:57:23.187045 11958 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4587 Northing: 32353)
E0305 17:57:23.247341 11958 base_map_node.cc:305] map node compress ratio: 0.192014
E0305 17:57:23.400804 11958 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4588 Northing: 32353)
E0305 17:57:23.562741 11962 base_map_node.cc:305] map node compress ratio: 0.015233
E0305 17:57:23.592726 11964 base_map_node.cc:305] map node compress ratio: 0.175726
E0305 17:57:23.616598 11961 base_map_node.cc:305] map node compress ratio: 0.0719407
E0305 17:57:23.630455 11959 base_map_node.cc:305] map node compress ratio: 0.185632
E0305 17:57:23.648696 11960 base_map_node.cc:305] map node compress ratio: 0.208169
E0305 17:57:23.668308 11963 base_map_node.cc:305] map node compress ratio: 0.206795
E0305 17:57:23.828147 11962 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4589 Northing: 32351)
E0305 17:57:23.923898 11960 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4588 Northing: 32351)
E0305 17:57:23.937166 11959 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4586 Northing: 32351)
E0305 17:57:23.997485 11964 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4587 Northing: 32351)
E0305 17:57:24.036100 11963 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4586 Northing: 32353)
E0305 17:57:24.075461 11961 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4586 Northing: 32352)
E0305 17:57:24.231834 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423691.348141delay time: 0.894444465637207
E0305 17:57:24.234925 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423691.548244delay time: 0.7043423652648926
E0305 17:57:24.236152 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423691.748347delay time: 0.5092394351959229
E0305 17:57:24.340274 11959 base_map_node.cc:305] map node compress ratio: 0.136059
E0305 17:57:24.371131 11964 base_map_node.cc:305] map node compress ratio: 0.24648
E0305 17:57:24.384832 11962 base_map_node.cc:305] map node compress ratio: 0.118133
E0305 17:57:24.422894 11960 base_map_node.cc:305] map node compress ratio: 0.242135
E0305 17:57:24.690204 11962 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4586 Northing: 32350)
E0305 17:57:24.720836 11960 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4587 Northing: 32350)
E0305 17:57:24.787600 11964 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4588 Northing: 32350)
E0305 17:57:24.793639 11959 base_map.cc:268]  Loaded map node: Map node (Resolution ID: 0 Zone ID: 10 Easting: 4589 Northing: 32350)
E0305 17:57:24.978291 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423692.148557delay time: 0.8290286064147949
E0305 17:57:24.981889 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423692.34866delay time: 0.6289255619049072
E0305 17:57:24.983821 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423692.548763delay time: 0.4288234710693359
E0305 17:57:25.482180 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423692.948967delay time: 0.5586714744567871
E0305 17:57:25.863075 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423693.349179delay time: 0.533461332321167
E0305 17:57:26.226209 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423693.749556delay time: 0.4980943202972412
E0305 17:57:26.619432 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423694.149767delay time: 0.4878816604614258
E0305 17:57:27.003816 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423694.551009delay time: 0.4166405200958252
E0305 17:57:27.392467 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423694.951215delay time: 0.4164364337921143
E0305 17:57:27.802377 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423695.359194delay time: 0.4084575176239014
E0305 17:57:28.212105 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423695.759398delay time: 0.4332525730133057
E0305 17:57:28.688968 11966 localization_lidar_process.cc:279] LocalizationLidar GetPredictPose: Lidar msg too old! lidar time: 1514423696.15961delay time: 0.5530414581298828

And the dreamview error log below
Log file created at: 2019/03/05 17:46:48
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0305 17:46:48.451228  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451388  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787105] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451405  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787116] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451414  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787127] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451423  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787138] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451433  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787149] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451442  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787161] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451452  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787172] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451460  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787184] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451469  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787195] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451478  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787207] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451494  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787218] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451511  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.78723] is too small. It should be larger than half vehicle width[1.05].
E0305 17:46:48.451521  5661 hdmap_common.cc:175] lane[id = id: "2652_1_-1"

**Comment by daohu527** [comment]
I'm not sure but it may cause by the map not loading properly
