### ISSUE TITLE
control module

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#7116]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Ubuntu 16.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.0
I am confused about the file /apollo/modules/control/controller/lat_controller.cc and /apollo/modules/control/controller/lon_controller.cc.
Why does the calculation of the lateral error take into account the navigation mode, and the calculation of the longitudinal error does not take into account the navigation mode?

**Comment by quuen** [comment]
emm..

**Comment by afibacer** [comment]
I have the same question, too. Do we need to modify longitudinal control code in order to support longitudinal control in navigation mode? 
Thanks.

**Comment by quuen** [comment]
emm...

**Comment by quuen** [comment]
![image](https://user-images.githubusercontent.com/45919445/58332392-b2559900-7e6d-11e9-834d-81e432b9d396.png)

**Comment by quuen** [comment]
@natashadsouza Could you tell me why?Thank you very much!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
