### ISSUE TITLE
when build apollo3.5 , System crash

### ISSUE THREAD

**Issue by Tangtang1234** [ApolloAuto/apollo#7121]
![image](https://user-images.githubusercontent.com/35449398/53853519-bc02f980-4000-11e9-8044-6026d2da77b0.png)

**Comment by gvc0461082002** [comment]
That's exact the same issue I experienced today.
The system was down without any response , while I am building apollo3.5 under ubuntu 18.04. 
I failed twice with no exception.
A message poped up" could not start ksmserver" before the system reboot automatically.
Will try again

**Comment by gvc0461082002** [comment]
My issue has been solved after repair some broken packages under ubuntu18.
The system entered into recovery mode, then Repair Broken Packages
Reboot again after the above, then I built it again with GPU enabled
everything is fine.

**Comment by Tangtang1234** [comment]
> My issue has been solved after repair some broken packages under ubuntu18.
> The system entered into recovery mode, then Repair Broken Packages
> Reboot again after the above, then I built it again with GPU enabled
> everything is fine.

OK, thank you very much!Ever tried using only CPU?

**Comment by gvc0461082002** [comment]
> > My issue has been solved after repair some broken packages under ubuntu18.
> > The system entered into recovery mode, then Repair Broken Packages
> > Reboot again after the above, then I built it again with GPU enabled
> > everything is fine.
> 
> OK, thank you very much!Ever tried using only CPU?

I am using the GPU mode

**Comment by natashadsouza** [comment]
@Tangtang1234 @gvc0461082002 could you give us additional details - what version of Apollo, your CPU/ GPU information, memory? It will be really helpful for us to not only debug your issue but help prevent it from happening to anyone else in the developer community. 
@gvc0461082002 which packages did you need to fix to get it running?
Thanks!

**Comment by Tangtang1234** [comment]
> @Tangtang1234 @gvc0461082002 could you give us additional details - what version of Apollo, your CPU/ GPU information, memory? It will be really helpful for us to not only debug your issue but help prevent it from happening to anyone else in the developer community.
> @gvc0461082002 which packages did you need to fix to get it running?
> Thanks!
Apollo 3.5, build with source code in CPU mode,and  size of the memory is 5G .

**Comment by natashadsouza** [comment]
@Tangtang1234 we recommend a system of at least 6~8GB while working on the Apollo platform. Also running it using a GPU is what we recommend as well.

**Comment by gvc0461082002** [comment]
> > @Tangtang1234 @gvc0461082002 could you give us additional details - what version of Apollo, your CPU/ GPU information, memory? It will be really helpful for us to not only debug your issue but help prevent it from happening to anyone else in the developer community.
> > @gvc0461082002 which packages did you need to fix to get it running?
> > Thanks!
> > Apollo 3.5, build with source code in CPU mode,and  size of the memory is 5G .

Hi Tangtang:
My system:
KDE 18.04.2 LTS (Plasma)
32GB
Nvidia Titan 1080 8GB
CPU : i7 6800K
kernel: linux 4.15.0-46-generic(x86_64)
Asi mentioned before, a message " faile to start ksmserver" poped up. The plasma is really vulnerable after I google the message. Then I chose to let all broken packages(including all known unknown)
 repaired by the ubuntu automatically.
Another suggestion is to enter into /var/log, to read system log if necessary

All the best to you :)

**Comment by Tangtang1234** [comment]
@gvc0461082002   Thanks! my computer is lower on configuration.

**Comment by natashadsouza** [comment]
@Tangtang1234 were you able to resolve your issue? Is there anything else we can help you with?

**Comment by storypku** [comment]
Close long-time-no-response issue. 

FYI, We have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now.
