### ISSUE TITLE
steering wheel suddenly turns right every some seconds

### ISSUE THREAD

**Issue by diff8911** [ApolloAuto/apollo#7122]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 2.0

### Steps to reproduce the issue:
- using my own simulation software publish the followed topics to Apollo：/apollo/localization/pose, /apollo/canbus/chassis
- my simulation software subscribe the followed topic from Apollo: /apollo/control
- open dreamview, select Routing, Planning and Control module, make a routing in the RouteEditing panel and sent it
- **after I press the Start Auto botton ,the car is good to move foward. But the steering wheel suddenly turns right every some seconds**, as the followed video:
https://github.com/diff8911/helllo-world/blob/master/suddenly%20turn%20right.mp4
- **Why this happens？How can I fix it**
 Thank you very much.

**Comment by Capri2014** [comment]
Not sure with these limited information.

**Comment by diff8911** [comment]
> Not sure with these limited information.
What information can I provide to locate the problem？

**Comment by natashadsouza** [comment]
@diff8911 we do not have any information regarding your simulation software. Also, your logs would be really helpful as a number of things could have gone wrong to have caused this.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
