### ISSUE TITLE
Failed to start docker container "apollo_dev" based on image: apolloauto/apollo:dev-x86_64-20190228_1414

### ISSUE THREAD

**Issue by Prj1508** [ApolloAuto/apollo#7130]
I was running APOLLO on my laptop until yesterday and I just did a restart of my system today. Its throwing error message when I try to start the docker, it fetches all the images, but towards end, it exits with this error code
[INFO] Starting docker container "apollo_dev_jpm" ...
docker: Error response from daemon: create nvidia_driver_384.130: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.
[ERROR] Failed to start docker container "apollo_dev_jpm" based on image: apolloauto/apollo:dev-x86_64-20190228_1414

**Comment by Prj1508** [comment]
The issue was with Nvidia docker. I purged and reinstalled and now its working fine

**Comment by xhaoAI** [comment]
purge Nvidia docker？ which one? I have encountered the same problem with you. Could you describe more specificly?
