### ISSUE TITLE
How does MSF localization module work?

### ISSUE THREAD

**Issue by ankita9017** [ApolloAuto/apollo#7141]
How does MSF localization module work? The demo Sunnyvale HD map does not seem to contain any pointclouds and it seems to be purely semantic/vector map.

How does the MSF localization module use such a map (without pointclouds) to do LIDAR based localization?

Also, where are the files pose_forcast.h, sins_struct.h, etc as referred in MSF local_integ module?

**Comment by frontw** [comment]
Also couldn't find pose_forcast.h, very curious

**Comment by frontw** [comment]
UPD: files pose_forcast.h, sins_struct.h could be found at /usr/local/apollo/local_integ/include
Also /usr/local/apollo/local_integ/lib/ has liblocalization_msf.so. Do I understand right, that Apollo localization is not open source fully?

**Comment by natashadsouza** [comment]
@frontw you are correct. There are algorithms and features that not open source at the moment.

**Comment by apollodevcommunity** [comment]
您好，msf定位必须使用pointcloud点云地图（local_map），没有点云地图，msf中的点云无法进行匹配。点云地图的生成请参考脚本：msf_simple_map_creator.sh 和apollo 的地图服务功能。您所说的pose_forcast.h sins_struct.h 包括他的.c在apollo中是不开放的程序，它是用可执行文件直接调用，这是Apollo较为核心的部分。相关思路可参考apollo 提供的相关msf论文。——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=490
