### ISSUE TITLE
apollo3.5编译成功但是打不开localhost：8888

### ISSUE THREAD

**Issue by zhuyingjie1** [ApolloAuto/apollo#7144]

**Comment by natashadsouza** [comment]
@zhuyingjie1 please refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md). Also, read through some of the previous issues for recommendations. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue. Please continue the discussion on #7147
