### ISSUE TITLE
please only allow root user to exec the docker/scripts/dev_start.sh

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#7145]
in the `dev_start.sh`, the script will mount `~/.cache` into the container volume. But if you use normal user to exec that shell script, in the container, some program will change the owner of the `.cache` dir. Everytime you restart your ubuntu system, the x-windows  will use ~/.cache dir and failed to start.

this cost us some time to figure it out.

**Comment by Eclipsehelio** [comment]
so you can mount ~/.cache/bazel to another path, just like this:
    volumes="-v $APOLLO_ROOT_DIR:/apollo \
             -v $HOME/.cache:${DOCKER_HOME}/.cache \
             -v ${APOLLO_ROOT_DIR}/../bazel:${DOCKER_HOME}/.cache/bazel"

**Comment by natashadsouza** [comment]
@gouchaoer thank you for the input. We really appreciate it!
