### ISSUE TITLE
dreamview已经运行，但chrome打开localhost：8888

### ISSUE THREAD

**Issue by zhuyingjie1** [ApolloAuto/apollo#7147]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5
![screenshot from 2019-03-07 11-16-38](https://user-images.githubusercontent.com/39542010/53929988-a22de900-40ca-11e9-875d-bf254598fea7.png)
![screenshot from 2019-03-07 11-17-17](https://user-images.githubusercontent.com/39542010/53929993-a78b3380-40ca-11e9-88e6-dd42bf82dcb2.png)

)**:

### Steps to reproduce the issue:
- ** run "bash scripts/dreamview.sh"；I’m having difficulty connecting to localhost:8888 on Chrome**:

**Comment by natashadsouza** [comment]
Adding reference to #7144. Please create only 1 issue for the same question. Thanks!
@zhuyingjie1 please refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md). Also, read through some of the previous issues for recommendations. Thanks!
