### ISSUE TITLE
Can't get /perception/inner/PrefusedObjects

### ISSUE THREAD

**Issue by Eddy819** [ApolloAuto/apollo#7150]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

### Steps to reproduce the issue:
We successfully run the **fusion_camera_detection_component.cc** and see obstacle info is published in channel `/perception/obstacles` in cyber_monitor as well.
However, we are not able to see the channel `/perception/inner/PrefusedObjects` in cyber_monitor.
In the mean time, we check the log and see `send out prefused msg, ts: 1551930057.174979 ret: 1`

I just wondering what go wrong!

Thank you so much.

**Comment by luqiang21** [comment]
Same here, we are able to see `/perception/obstacles` and `/perception/camera_debug` channels. But we cannot see `/perception/inner/PrefusedObjects` and `/perception/inner/camera_viz_msg` which are defined in `modules/perception/production/conf/perception/camera/fusion_camera_detection_component.pb.txt`.

**Comment by techoe** [comment]
Currently /perception/obstacles is an only visible topic outside of the perception module.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if the issue persists. Thanks!

**Comment by qwetqwe** [comment]
> Currently /perception/obstacles is an only visible topic outside of the perception module.

Hello I want to configure it to visible topic,could you tell me where I can configure

**Comment by qwetqwe** [comment]
> Currently /perception/obstacles is an only visible topic outside of the perception module.

Hello, I want to configure it to visible topic,could you tell me where I can configure

**Comment by qwetqwe** [comment]
@techoe  Hello I want to configure it to visible topic,could you tell me where I can configure

**Comment by josh-wende** [comment]
@qwetqwe did you ever figure out how to do this? It seems there's a lot of useful information being passed around internally within the perception module. Did you need to create a new node to add to the perception dag which reads the inner channel and republishes it to an external channel?

**Comment by hdm8809** [comment]
Hello, I find that /perception/inner/PrefusedObjects is a class type, /perception/obstacles is a proto.
Proto topic can display in cyber_monitor.
I want to know how to display a class type topcic.
Thanks.
