### ISSUE TITLE
How to compare the performance and delays between CyberRT and ROS ?

### ISSUE THREAD

**Issue by bssung** [ApolloAuto/apollo#7152]
Apollo team release CyberRT, thought it is better than ROS.
But how to test it? Are there some tools or benchmark? 
Or how to write code to compare the performance? 
Thanks

**Comment by quning78** [comment]
@bssung great to know you are interested in Cyber RT. 

For comparison, we have some similar examples in both Apollo ROS and Cyber RT as below:

https://github.com/ApolloAuto/apollo-platform/tree/master/ros/ros_tutorials/roscpp_tutorials

https://github.com/ApolloAuto/apollo/tree/master/cyber/examples

Also, for whatever the metrics you would like to get, you can add more tests following the manual in https://github.com/ApolloAuto/apollo/blob/master/docs/cyber.

Recently we added one more manual to help you migrate your ROS application to Cyber RT. 

https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Migration_Guide.md

Let me know if you are running into any problems writing your own code on Cyber RT.

**Comment by natashadsouza** [comment]
Currently closing this issue. @bssung if you have any additional questions, feel free to reopen it!
