### ISSUE TITLE
ubuntu16.04 浏览器显示dreamview显示空白

### ISSUE THREAD

**Issue by huamoxian** [ApolloAuto/apollo#7153]
按照3.5 start guide进行编译，执行，打开浏览器之后，dreamview显示空白

**Comment by natashadsouza** [comment]
@huamoxian please refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md). Also, read through some of the previous issues for recommendations. Thanks!

**Comment by natashadsouza** [comment]
@huamoxian were you able to resolve your issue? Currently closing this issue as it appears to be resolved. Feel free to reopen if the issue persists. Thanks!
