### ISSUE TITLE
The use of adc_sl_boundary

### ISSUE THREAD

**Issue by YaoQii** [ApolloAuto/apollo#7154]
Hello, 
I have a question about the use of `const SLBoundary& AdcSlBoundary() const;` and `const SLBoundary& VehicleSlBoundary() const` which both in the [reference_line_info.h](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/reference_line_info.h). 

In my opinion, maybe we should use `VehicleSlBoundary()` which mean the real time location more often, but not the `AdcSlBoundary()` which means the planning start point. such as [obstacle_blocking_analyzer.cc](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/common/obstacle_blocking_analyzer.cc)

Thanks for your reponse.

**Comment by jmtao** [comment]
@YaoQii they serve different purposes.

**Comment by jmtao** [comment]
Hi @YaoQii , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
