### ISSUE TITLE
how to train model of cnn_segmentation in perception module

### ISSUE THREAD

**Issue by chasingw** [ApolloAuto/apollo#716]

**Comment by jzhuucla** [comment]
We only released the pretrained model of CNNSegmentation for testing at this moment.

**Comment by chasingw** [comment]
@jzhuucla Thanks and do you have plan to release the other model , solver or something used to train the model of cnn_segmentation?

**Comment by bill-rideos** [comment]
+1 on this. It'd be great expose this to open source community.

**Comment by Peter9606** [comment]
@charliezwc  @bill-rideos  Here is a piece of information might help you understand something behind CNN Segmentation, in Chinese.
https://zhuanlan.zhihu.com/p/30311165

**Comment by ahsueh1996nutonomy** [comment]
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception.md in English
