### ISSUE TITLE
brake/throttle calibration

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#7197]
Can someone tell me what is the principle of vehicle brake throttle calibration?I will really appreciate you！

**Comment by mickeyouyou** [comment]
1. The throttle and brake are at least larger than deadzone (the minimum effective action value).
2. Acquisition of complete curve data from natural acceleration to vehicle braking (full braking); complete data like below;
3. Iteration to adapt the query of control values under different speeds and accelerations.

![calibration](https://user-images.githubusercontent.com/3821311/54117229-4a291680-442b-11e9-8084-96030af710cd.png)

**Comment by natashadsouza** [comment]
Currently closing this issue. 
@quuen feel free to reopen if this issue persists. Thanks!

**Comment by Addi2020** [comment]
How to collect data while Update Vehicle Calibration for Throttle and Brakes?
Collect Data
1.Run python data_collector.py for different commands, commands like x y z, where x is acceleration command, y is speed limit(mps), z is decceleration command,Positive number for throttle and negative number for brake.Run each command multiple times.
2. Adjust the command script based on the vehicle response.
3. Run python plot_data.py to open recorded data and visualize collected data.

Q＃１ x y z can be any random values? e.g. 5 10 -15, 50 5 -30, 25 15 -50, 60 15 -40 etc?
Q#2 How to adjust command script based on the vehicle response？
Q#3 how do we know the collected data is correct?

![Screenshot from 2020-04-23 14-36-50](https://user-images.githubusercontent.com/61130487/80067230-0d0cde80-8570-11ea-90a6-adca4473bd5f.png)

**Comment by Addi2020** [comment]
@mickeyouyou
