### ISSUE TITLE
modules/prediction/README.md Input error

### ISSUE THREAD

**Issue by chengfen1987** [ApolloAuto/apollo#7201]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**:
binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
master

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
in README.md
**Input**
- Obstacles information from the perception module
-   Localization information from the localization module
-   Planning trajectory of the previous computing cycle from the planning module

should remove 
-   Planning trajectory of the previous computing cycle from the planning module

### Supporting materials (screenshots, command lines, code/script snippets):

in README_cn.md
**输入**
- 障碍物
- 定位

**Comment by mickeyouyou** [comment]
need to read planning info. of last frame and call OnPlanning to update the ADCTrajectoryContainer

**Comment by natashadsouza** [comment]
Closing this issue as it is resolved. Feel free to reopen if you have additional questions. Thanks!
