### ISSUE TITLE
apollo3.5 build failed

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#7203]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:

when I use the command  **bash apollo.sh build -j 1**,and build failed. And ERROR info is like this:

ERROR: (03-10 10:35:36.396) /apollo/modules/prediction/BUILD:26:1: Linking of rule '//modules/prediction:prediction_component_test' failed (Exit 1).
/usr/bin/ld: warning: libcuda.so.1, needed by bazel-out/local-dbg/bin/_solib_k8/_U@pytorch_Ugpu_S_S_Cpytorch_Ugpu___Uexternal_Spytorch_Ugpu_Slib/libthnvrtc.so, not found (try using -rpath or -rpath-link)

### Supporting materials (screenshots, command lines, code/script snippets):
![图片](https://user-images.githubusercontent.com/30464144/54086014-c0703f00-437f-11e9-9a55-7bf370e6ddef.png)

**Comment by acorovic** [comment]
+1
I have cuda installed and working properly, libcuda.so.1 is inn /usr/lib/x86_64-linux-gnu. Tried adding it to LD_LIBRARY_PATH, but still getting this error.

**Comment by qwetqwe** [comment]
The problem is that I don't remove content in .cache/bazel
