### ISSUE TITLE
Convert apollo::perception::pcl_util PointCloud type PointXYZIH to pcl::PointXYZI

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#7224]
Is there any way to convert apollo self defined pcl point type to pcl original type?

```
apollo::pcl_util::Point (PointXYZH) -> pcl::PointXYZI
```

**Comment by techoe** [comment]
We may not have such a tool for conversion.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
