### ISSUE TITLE
question about localization frame and localization messages

### ISSUE THREAD

**Issue by Wang4758** [ApolloAuto/apollo#7225]
Hi,
I ran the rosbag demo2.5.bag and tried to figure out the coordinate systems of Apollo. I found something really strange. So the localization messages have really large position values, which I assume are referred to the /world frame. And the /localization frame seems to move with the car. But if I transform the localization messages from /world frame to /localization frame, I got an offset of the y position which grows larger and larger but should actually stay zero. So my question is, did I understand the coordinate system wrong or could you please clarify why this happens?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
