### ISSUE TITLE
Why does the record file not all plain text?

### ISSUE THREAD

**Issue by Smlight** [ApolloAuto/apollo#7246]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: docker
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

I found the direct write code below, did I miss something?
https://github.com/ApolloAuto/apollo/blob/r3.5.0/cyber/record/file/record_file_writer.h#L126
https://github.com/ApolloAuto/apollo/blob/r3.5.0/cyber/record/file/record_file_writer.h#L138

This is the apollo/docs/demo_guide/demo_3.5.record file
![2019-03-13 17-05-13屏幕截图](https://user-images.githubusercontent.com/3436211/54266426-525f8e00-45b2-11e9-9228-3cc304b311e1.png)

**Comment by baowanyu** [comment]
All we write directly to the record file is the section tag which include section length and section type. Then we started writing serialized PB messages to record file. These inputs are encoded and cannot be opened in a plain text editor. @Smlight

**Comment by gruminions** [comment]
Currently closing this issue. @Smlight if you have any additional questions, feel free to reopen it!
