### ISSUE TITLE
Lidar cnn seg slow speed

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#7247]
Load lidar cnn caffe model, calculate time is runs:

```
I0313 19:43:21.665606 14448 apollo_lidar_detect.cpp:106] seg cost: 102ms
I0313 19:43:21.672451 14448 apollo_lidar_detect.cpp:109] build cost: 6ms
I0313 19:43:21.672760 14448 apollo_lidar_detect.cpp:113] pub cost: 0ms
I0313 19:43:21.675539 14448 apollo_lidar_detect.cpp:102] pre seg cost: 2ms
I0313 19:43:21.770306 14448 apollo_lidar_detect.cpp:106] seg cost: 94ms
I0313 19:43:21.778688 14448 apollo_lidar_detect.cpp:109] build cost: 8ms
I0313 19:43:21.779040 14448 apollo_lidar_detect.cpp:113] pub cost: 0ms
I0313 19:43:21.781972 14448 apollo_lidar_detect.cpp:102] pre seg cost: 2ms
I0313 19:43:21.867998 14448 apollo_lidar_detect.cpp:106] seg cost: 86ms
I0313 19:43:21.876662 14448 apollo_lidar_detect.cpp:109] build cost: 8ms
I0313 19:43:21.877081 14448 apollo_lidar_detect.cpp:113] pub cost: 0ms
I0313 19:43:21.879896 14448 apollo_lidar_detect.cpp:102] pre seg cost: 2ms
I0313 19:43:21.966495 14448 apollo_lidar_detect.cpp:106] seg cost: 86ms
I0313 19:43:21.974934 14448 apollo_lidar_detect.cpp:109] build cost: 8ms
I0313 19:43:21.975292 14448 apollo_lidar_detect.cpp:113] pub cost: 0ms
I0313 19:43:21.978260 14448 apollo_lidar_detect.cpp:102] pre seg cost: 2ms
I0313 19:43:22.064615 14448 apollo_lidar_detect.cpp:106] seg cost: 86ms

```

The network out time are very high, minbox build also cost to many times. Is that normal? which speed is normal in Apollo?

**Comment by techoe** [comment]
The processing depends on GPU. Which GPU do you use?

**Comment by jinfagang** [comment]
@techoe  GTX1080 Ti.  It runs about 89ms when forward network, 30ms when build minbox. totally using more than 120 ms approximately. Does it runs realtime (more than 15fps) on other devices?

**Comment by techoe** [comment]
GPU seems good enough. Please check CPU. The total lidar processing time should be less than 100ms.

**Comment by jinfagang** [comment]
@techoe The model runs on GPU, calculated time needs approximately 80ms in forward time. More than 40ms in MinBox building. Does the network forward time normal? And how to accerlerate the minbox building time?

**Comment by xueyingliu** [comment]
Hi, How do you build cnn seg, I meet the following error, 
`ERROR: /apollo/modules/perception/inference/caffe/BUILD:6:11: no such package '@caffe//': The repository '@caffe' could not be resolved and referenced by '//modules/perception/inference/caffe:caffe_net_lib'`

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
