### ISSUE TITLE
please sent car initial position and map data

### ISSUE THREAD

**Issue by zwjnju** [ApolloAuto/apollo#727]
I have follow the installation, when I click dreamview , "please sent car initial position and map data" comes out ,why?

**Comment by ahuer2435** [comment]
执行rosbag play -l docs/demo_guide/demo_1.5.bag --loop 才可以看到汽车运动页面。因为/dreamview节点没有收到自动驾驶相关的数据，所以还不能显示，所以需要rosbag 命令把数据发布出来。

**Comment by zwjnju** [comment]
I have download ros-indigo-apollo-1.5.0.tar.gz from apollo-platform
and install ros_x86_64 ,but when I run rosbag, it shows that "The program 'rosbag' is currently not installed. You can install it by typing:
apt install python-rosbag" @ahuer2435

**Comment by westeast** [comment]
@zwjnju 显示 没有rosbag可能你没有编译好，记得是在docker环境里编译，然后rosbag也是在docker环境里运行~

**Comment by ahuer2435** [comment]
我用的是apollo，不是apollo-platform，然后按照其中README_cn.md操作。apollo-platform似乎只有ros部分，并没有apollo，所以建议使用apollo。然后操作如westeast 所说，编译和rosbag都需要在docker环境下，具体可以参考apollo下的README_cn.md或者README.md。

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
