### ISSUE TITLE
Error with python_modules while building docker image 

### ISSUE THREAD

**Issue by shifakhan4892** [ApolloAuto/apollo#7271]
Hi Apollo developers,
I am trying to build an apollo image using ./build_dev.sh ./dev.x86_64.dockerfile and I am getting an error in install_python_modules.sh
Following is the screenshot of the error. Please let me know if anyone has an idea to fix it. 
![python_modules error](https://user-images.githubusercontent.com/16239521/54368489-44f1e480-4642-11e9-8ec9-8a025db1424a.png)

**Comment by Eclipsehelio** [comment]
Try to add 'python cython' in line 41 of dev.x86_64.dockerfile before '&&' !

**Comment by shifakhan4892** [comment]
@Eclipsehelio I tried that but now I am getting a different error. 
Can't understand this error. I am using Ubuntu 14.04. 
Suggestions will be appreciated. This was working fine a month ago but doesn't work now. 

![python_modules2](https://user-images.githubusercontent.com/16239521/54393935-7afe8b00-4679-11e9-80a0-0da63c149431.png)

**Comment by natashadsouza** [comment]
@shifakhan4892 we recommend following the recommended [build process](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md). If you have any additional questions, feel free to write back. Thanks!

**Comment by gengqx** [comment]
@natashadsouza @Eclipsehelio @shifakhan4892 @xiaoxq This happens when we want build our own docker images,not in build the apollo project.I have not solve this problem,Could any one give us some help?

**Comment by Eclipsehelio** [comment]
Months ago I built my own docker images on TX2, The main problems I encountered were cousred by unstable network, Then I compared dev.aarch64.dockerfile with dev.x86_64.dockerfile, I found that maybe there were still some third-party libraries not installed. Try to replace apt-get with the follwing commands in dev.x86_64.dockerfile.
apt-get install -y --force-yes bc \
            cppcheck \
            debconf-utils \
            doxygen \
            graphviz \
            gdb \
            git \
            subversion \
            lcov \
            libblas-dev \
            libboost-all-dev \
            libcurl4-openssl-dev \
            libfreetype6-dev \
            liblapack-dev \
            libpcap-dev \
            locate \
            lsof \
            realpath \
            shellcheck \
            vim \
            v4l-utils \
            nfs-common \
            zip \
            apt-transport-https \
            build-essential \
            cmake \
            curl \
            software-properties-common \
            wget \
            unzip \
            zip \
            python \
            sudo \
            autoconf \
            automake \
            libtool \
            libmagic-dev \
            libatlas-base-dev \
            libflann-dev \
            libhdf5-serial-dev \
            libicu-dev \
            liblmdb-dev \
            libopencv-dev \
            libqhull-dev \
            libsnappy-dev \
            libvtk5-dev \
            libvtk5-qt4-dev \
            mpi-default-dev \
            libunwind8-dev \
            libblas-dev \
            liblapack-dev \
            gfortran \
            libgeos-dev \
            libleveldb-dev \
            python-matplotlib \
            python-pip \
            python-psutil \
            python-scipy \
            python-software-properties \
            python3-psutil \
            python-vtk \
            python-pyaudio \
            python3-pyaudio \
            python-nose \
            sox \
            libvtk-java \
            libeigen3-dev \
            libflann-dev \
            libusb-1.0-0-dev \
            libudev-dev \
            freeglut3-dev \
            libpng12-dev \
            libgtest-dev \
            libxmu-dev \
            libbz2-dev \
            libconsole-bridge-dev \
            libeigen3-dev \
            libgstreamer-plugins-base0.10-dev \
            libgstreamer0.10-dev \
            liblog4cxx10-dev \
            liblz4-dev \
            libpoco-dev \
            libproj-dev \
            libtinyxml-dev \
            libyaml-cpp-dev \
            sip-dev \
            uuid-dev \
            zlib1g-dev \
            supervisor \
            libpcre3 \
            libpcre3-dev \
            swig \
            libtheora-dev \
            yarn glusterfs-client \
            libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libglfw-dev freeglut3-dev \
            python-empy
pip install netifaces

**Comment by Eclipsehelio** [comment]
Oops! The back slash Vanished, remember to add back slash at the end of each line except the last line!
I will build the x86_64 docker image later and report the problems I will encounter!

**Comment by gengqx** [comment]
I think i have solve this problem.recently pyproj have update to 2.0, this would casue a problem. so make pyproj == 1.9.6 would work . see pr #7290

**Comment by natashadsouza** [comment]
@gengqx if it fixed the above issue, can you please confirm and close this issue? Also, thank you very much for submitting a fix!

**Comment by shifakhan4892** [comment]
Yes it's fixed. Thanks @gengqx and @Eclipsehelio
