### ISSUE TITLE
Need help about open space planner

### ISSUE THREAD

**Issue by wobistdu** [ApolloAuto/apollo#7281]
Hi, I am very interested about the parking scenario mentioned in  https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Open_Space_Planner.md
Is there anywhere I can try to run a demo about the parking? It needs specific opendrive file with these parking lot information, right?

Thanks

**Comment by Capri2014** [comment]
Hi, thanks for your interest! We are currently working on the architect refactoring on it to extend it and support more scenarios besides parking.  More information would be updated once the refactoring done and validated.  For the data format about parking, it is already available in https://github.com/ApolloAuto/apollo/blob/master/modules/map/proto/map_parking_space.proto
