### ISSUE TITLE
Failed to pull docker image.

### ISSUE THREAD

**Issue by guofengpeng** [ApolloAuto/apollo#7285]
您好，执行bash docker/scripts/dev_start.sh 这个命令时候出现### 【error】Failed to pull docker image.
应该怎么弄？

**Comment by natashadsouza** [comment]
@guofengpeng could you give us more details - Apollo version, System specs, OS etc?

**Comment by guofengpeng** [comment]
apollo 3.5 ,ubuntu 16.04
as follow:
guofengpeng@guofengpeng-Lenovo-G50-80:~/apollo$ bash docker/scripts/dev_start.sh[sudo] guofengpeng 的密码： 
fetch: Fetching reference refs/heads/master
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20190128_1800 ...
Error response from daemon: manifest for apolloauto/apollo:dev-x86_64-20190128_1800 not found
[ERROR] Failed to pull docker image.
guofengpeng@guofengpeng-Lenovo-G50-80:~/apollo$

**Comment by mickeyouyou** [comment]
You can try update the codes (pull from master ) and try pull docker images from china use parameter `-C`  like `bash docker/scripts/dev_start.sh -C `

**Comment by guofengpeng** [comment]
thank you much
