### ISSUE TITLE
Leopard Imaging Firmware Update Interrupted

### ISSUE THREAD

**Issue by dengyuchenkit** [ApolloAuto/apollo#7303]
Hi,
I interrupted the firmware update of leopard camera and the camera became malfunctioned. It can't be recognized by computer software. 
![fw_update_error1](https://user-images.githubusercontent.com/21317994/54460486-135f4300-4740-11e9-8c23-51e19448dc48.jpg)
Do you have any solutions to the situation? Thank you.
Yuchen

**Comment by natashadsouza** [comment]
@dengyuchenkit this is a question you would need to direct to Leopard Imaging. Thanks!

**Comment by Yu-Cheung** [comment]
Hi, do you solve it?
