### ISSUE TITLE
lattice planner deal with static obstacle

### ISSUE THREAD

**Issue by stdpython** [ApolloAuto/apollo#7314]
I have read some code of the lattice planner. And I found that if the static obstacle on the lane which the car running, the static obstacle will map to the ST graph.
And it is weird, we did not consider it's shape and accurate location. the obstacle may not conflict to the car, and we just map it, leads the car stop or change lane.

lattice planner中对于静止障碍物的处理似乎有一些粗糙，我看到代码中表示，如果静止障碍物在当前车道上，就直接将其映射到ST图中，因此，如果车道上最右侧有一个小箱子（正常行驶不会撞到），我们应该不予考虑，但lattice中，我们似乎无法通过它。当然在em planner中，这个不是问题。

void PathTimeGraph::SetStaticObstacle(
    const Obstacle* obstacle,
    const std::vector<PathPoint>& discretized_ref_points) {
  const Polygon2d& polygon = obstacle->PerceptionPolygon();

  std::string obstacle_id = obstacle->Id();
  SLBoundary sl_boundary =
      ComputeObstacleBoundary(polygon.GetAllVertices(), discretized_ref_points);

  double left_width = FLAGS_default_reference_line_width * 0.5;
  double right_width = FLAGS_default_reference_line_width * 0.5;
  ptr_reference_line_info_->reference_line().GetLaneWidth(
      sl_boundary.start_s(), &left_width, &right_width);
  if (sl_boundary.start_s() > path_range_.second ||
      sl_boundary.end_s() < path_range_.first ||
      sl_boundary.start_l() > left_width ||
      sl_boundary.end_l() < -right_width) {
    ADEBUG << "Obstacle [" << obstacle_id << "] is out of range.";
    return;
  }

  path_time_obstacle_map_[obstacle_id].set_obstacle_id(obstacle_id);
  path_time_obstacle_map_[obstacle_id].mutable_bottom_left()->CopyFrom(
      SetPathTimePoint(obstacle_id, sl_boundary.start_s(), 0.0));
  path_time_obstacle_map_[obstacle_id].mutable_bottom_right()->CopyFrom(
      SetPathTimePoint(obstacle_id, sl_boundary.start_s(),
                       FLAGS_trajectory_time_length));
  path_time_obstacle_map_[obstacle_id].mutable_upper_left()->CopyFrom(
      SetPathTimePoint(obstacle_id, sl_boundary.end_s(), 0.0));
  path_time_obstacle_map_[obstacle_id].mutable_upper_right()->CopyFrom(
      SetPathTimePoint(obstacle_id, sl_boundary.end_s(),
                       FLAGS_trajectory_time_length));
  static_obs_sl_boundaries_.push_back(std::move(sl_boundary));
  ADEBUG << "ST-Graph mapping static obstacle: " << obstacle_id
         << ", start_s : " << sl_boundary.start_s()
         << ", end_s : " << sl_boundary.end_s()
         << ", start_l : " << sl_boundary.start_l()
         << ", end_l : " << sl_boundary.end_l();
}

**Comment by YongzhengZhao** [comment]
EM算法的核心之一就是ST和SL规划的解耦, 你说的这个问题确实是在ST上无法越过的, 但是EM会同时在多条参考线上同时规划,这样就没问题了. 百度的算法是基于路的, 不是基于自由的.

**Comment by YongzhengZhao** [comment]
你说的这个问题确实是在ST上无法越过的, 但是这种情况下就变道了, 这样投影就没问题. Lattice是基于高速公路的, 你说的那种情况发生的概率很小

**Comment by breezygogo** [comment]
额，这个问题是这样的，首先横向规划能绕开吗？当然是能的吧，因为这个小箱子，在横向规划的时候会考虑到对吧，纵向规划采样四个情况是吧，巡航，跟车、超车，停车，采样完速度规划曲线了，然后再去计算cost，只要是可行的速度规划曲线的cost都会很大是吧，但是都大，没问题啊，选一个相对小的就是了，然后再横纵向combine一下，再去做碰撞检测，这个时候不会撞是吧，因为横向不撞，纵向只是纵向速度而已，所以依然能规划通过是吧。

**Comment by YongzhengZhao** [comment]
您的邮件我已经收到谢谢赵永正

**Comment by breezygogo** [comment]
加个好友？
