### ISSUE TITLE
class Box2d has an error calculation on max_x, max_y

### ISSUE THREAD

**Issue by kennethyu2017** [ApolloAuto/apollo#7317]
**Describe the bug**
apollo version: 3.5 till Mar18,2019:
code: 
  in  modules/common/math/box2d.h ,  max_x, max_y are initialized as following:
  double max_x_ = std::numeric_limits<double>::min();
  double max_y_ = std::numeric_limits<double>::min();

 in  box2d.cc, they are calculated in function Box2d::InitCorners() : 
 for (auto &corner : corners_) {
    max_x_ = std::fmax(corner.x(), max_x_);  
    max_y_ = std::fmax(corner.y(), max_y_); 
  }
actually ,for foating-point types with denormalization, std::numeric_limits<double>::min() returns the minimum positive normalized value,i.e., ~0.0 , so when the corner_x() or corner_y() is negative, the max_x_ or max_y_ will get wrong result.

**To Reproduce**
create a Box2d instance with negative corner coordinates values, then call max_x(), max_y() to check the values.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 16.04
 - Version : apollo version: 3.5 till Mar18,2019:

**Comment by kennethyu2017** [comment]
It should be using std::numeric_limits<double>::lowest()  instead.

**Comment by natashadsouza** [comment]
@kennethyu2017 please submit a pull request with your code enhancement. Thank you so much for your contribution.

**Comment by kennethyu2017** [comment]
Pull request and merge done,  thank you guys.

**Comment by mickeyouyou** [comment]
Thanks for your contributing.
