### ISSUE TITLE
dreamview start no response

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#7318]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

I have finish install docker、nvidia-driver and so on, then compile the apollo 3.5 finished, and bash scripts/bootstrap.sh, I find the dreamview process is running, but during the startup process there is the following information in dreamview.log

og file created at: 2019/03/18 16:23:01
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0318 16:23:01.499306 14355 init.cc:112]  Register exit handle succ.
I0318 16:23:01.502439 14355 map_service.cc:106]  Failed to open map meta file: /metaInfo.json
I0318 16:23:01.502449 14355 map_service.cc:143]  Updated with map: x_offset 0, y_offset 0
I0318 16:23:01.564004 14355 hmi_worker.cc:175]  Loaded HMI config: modes {
。。。。
}
I0318 16:23:01.565397 14355 kv_db.cc:66]  Executing SQL: CREATE TABLE IF NOT EXISTS key_value (key VARCHAR(128) PRIMARY KEY NOT NULL, value TEXT);
I0318 16:23:01.565466 14355 kv_db.cc:66]  Executing SQL: INSERT OR REPLACE INTO key_value (key, value) VALUES ('/apollo/hmi/status:current_mode', 'Mkz Standard Debug');
I0318 16:23:01.567440 14355 point_cloud_updater.cc:63]  Lidar height is updated to 1.91
I0318 16:23:01.656718 14359 simulation_world_service.h:224]  Has not received any data from /apollo/canbus/chassis
I0318 16:23:01.656800 14359 simulation_world_service.h:224]  Has not received any data from /apollo/sensor/gnss/odometry
I0318 16:23:01.656818 14359 simulation_world_service.h:224]  Has not received any data from /apollo/localization/pose
I0318 16:23:01.656832 14359 simulation_world_service.h:224]  Has not received any data from /apollo/perception/obstacles
I0318 16:23:01.656844 14359 simulation_world_service.h:224]  Has not received any data from /apollo/prediction
I0318 16:23:01.656857 14359 simulation_world_service.h:224]  Has not received any data from /apollo/planning
I0318 16:23:01.656868 14359 simulation_world_service.h:224]  Has not received any data from /apollo/control
I0318 16:23:01.657021 14359 hdmap.cc:24]  Loading HDMap: /apollo/modules/map/data/sunnyvale_big_loop/base_map.bin ...
E0318 16:23:02.765424 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765470 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787105] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765486 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787116] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765503 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787127] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765525 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787138] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765692 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787149] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765709 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787161] is too small. It should be larger than half vehicle width[1.05].
E0318 16:23:02.765718 14359 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787172] is too small. It should be larger than half vehicle width[1.05].

when I input localhost:8888 in chrome，there is no something. that is blank page，and No error message is displayed，such  as Inaccessible

**Comment by natashadsouza** [comment]
@breakisx please look through our [FAQs document](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Dreamview_FAQs.md). Let me know if those suggestions do not work. Thanks!

**Comment by llrraa** [comment]
try to run "git lfs fetch --all ." at the project root directory.
If still not ok, please show some more log.
reference: [reference](https://github.com/ApolloAuto/apollo/issues/7228)

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
