### ISSUE TITLE
Is there an up to date guide on how to start the perception module?

### ISSUE THREAD

**Issue by vattenbuffel** [ApolloAuto/apollo#7320]
Me and my friend are having problems getting the perception module up and running. We've followed various guides but not found one that works. We noticed that all of the guides we've found are quite old. Is there a guide on how to start the perception module which works with Apollo3.5?

**Comment by natashadsouza** [comment]
@vattenbuffel could you give us details on what you were trying to run using the perception module? Was it algorithm testing or something else? Also, which guides have you referred to that did not help?

**Comment by vattenbuffel** [comment]
@natashadsouza We've followed two guides. [Guide 1](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md), [guide 2](https://github.com/ApolloAuto/apollo/tree/master/modules/perception), we followed the steps under "setup instructions", the third guide was under issues here on github but I can't seem to find it.

I don't understand what you mean by "what you were trying to run using the perception module". We want to start the module so that we can use the cyber visualizer to see if Apollo can identify a human. Is this wrong?

**Comment by techoe** [comment]
Obviously the instruction was outdated. Please follow this instruction

0. Get into the docker by bstart and binto
1. Build
> ./apollo.sh build_opt gpu
2. Run bootstrap.sh
> bootstrap.sh
3. Launch Dreamview from your web browser by typing following address
http://localhost:8888/
4. Select car and map in the dreamview

5. Select transform button in Dreamview or type command
> cyber_launch start /apollo/modules/transform/launch/static_transform.launch

5. If image is compressed launch image decompression module
> cyber_launch start /apollo/modules/tools/image_decompress/launch/image_decompress.launch

6. Launch perception modules
> cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch

7. Play recorded bag
> cyber_recorder play -f /apollo/data/bag/anybag -r 0.2

**Comment by michaelowenliu** [comment]
> Obviously the instruction was outdated. Please follow this instruction
> 
> 1. Get into the docker by
> 
> > $APOLLO_HOME/docker/scripts/dev_start.sh
> > $APOLLO_HOME/docker/scripts/dev_into.sh
> 
> 1. Build
> 
> > ./apollo.sh build_opt_gpu
> 
> 1. Run bootstrap.sh
> 
> > bootstrap.sh
> 
> 1. Launch Dreamview from your web browser by typing following address
>    http://localhost:8888/
> 2. Select car and map in the dreamview
> 3. Select transform button in Dreamview or type command
> 
> > cyber_launch start /apollo/modules/transform/launch/static_transform.launch
> 
> 1. If image is compressed launch image decompression module
> 
> > cyber_launch start /apollo/modules/tools/image_decompress/launch/image_decompress.launch
> 
> 1. Launch perception modules
> 
> > cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch
> 
> 1. Play recorded bag
> 
> > cyber_recorder play -f /apollo/data/bag/anybag -r 0.2

@techoe, hi, thanks a lot. Could you please update the instruction carefully once you release the new version? Since there is little information on it, the official instruction would be only way to us. Thank you.

**Comment by vattenbuffel** [comment]
@techoe We tried your instructions and got errors. Firstly it told us that the file "/apollo/modules/perception/production/launch/perception_all" don't exist so we change it into "/apollo/modules/perception/production/launch/perception". That gave us the following error on step 6. ![ErrorWithNewGuide](https://user-images.githubusercontent.com/7643918/54828075-af92c800-4cb3-11e9-8e6a-12d9234cd4ba.png)
We tried with "/apollo/modules/perception/production/launch/perception_camera" as well and that gave the same error.

We checked which path it used to load the camera intrinsic file and indeed there was no file at that path.  The block of code which failed and the path it used to fail is shown here:
![yamlpath](https://user-images.githubusercontent.com/7643918/54829265-54160980-4cb6-11e9-8852-40fda0caee82.png)

We tried to locate the file ourselves and found at this path "/home/twizy1/apollo_3.5_test/apollo/modules/perception/production/data/perception/camera/params/front_6mm_intrinsics.yaml". 

How we added the camera. (its a camera form leopard imaging) 
We tried to symlink our cameras into Apollo with the 99-webcam.rules and changed the ATTR{name} to ATTR{ID_MODEL} and got an error where the command ATTR{} was not found. We also tried the setuphost script but where not sure if it should be run inside or outside docker, outside doocker it did not seam to do much and inside docker we got the error: VIDIOC_S_FMT from the file usb_cam.cc: 333. So we tried to "manually" link the camera to /dev/camera/front_6mm which seamed to work. But we are uncertain if this is the correct way to add a camera. 

It might be worth noting that we're trying to start the perception module only using a camera, not using radar or lidar.

**Comment by techoe** [comment]
Hi, 
The screenshot of the code doesn't seem to be the code in the repo. It should be
      if (!LoadBrownCameraIntrinsic(intrinsic_file, distort_model.get())) {
        AERROR << "Failed to load camera intrinsic:" << intrinsic_file;
        return false;
      }
Please check cyber_monitor if front_6mm camera is correctly published.

**Comment by vattenbuffel** [comment]
@techoe Thanks for the response. We've resolved this problem.

**Comment by yfzm** [comment]
@vattenbuffel We encountered this problem too. Could you please tell me how you get this problem solved?

**Comment by vattenbuffel** [comment]
We stopped using Apollo. Apollo proved far too difficult to get running.

________________________________
Från: Li Hao <notifications@github.com>
Skickat: den 27 maj 2019 09:52:29
Till: ApolloAuto/apollo
Kopia: Noa Lindén; Mention
Ämne: Re: [ApolloAuto/apollo] Is there an up to date guide on how to start the perception module? (#7320)


@vattenbuffel<https://github.com/vattenbuffel> We encountered this problem too. Could you please tell me how you get this problem solved?

**Comment by Zhenni17** [comment]
@vattenbuffel I am very sorry to hear you had such a difficult time get Apollo up and running. We take our developer experience very seriously, and I'd love to connect with you and hear more about your experience. Please send me an email at wuzhenni01@baidu.com and I'd love to learn more about your experience.

**Comment by vattenbuffel** [comment]
We're almost done with our bachelor thesis now so there's no point in sending you an email. We've recommended our supervisor not to use Apollo in the future because of the lack of guides, up to date documentation and help.

________________________________
Från: Zhenni Wu <notifications@github.com>
Skickat: den 28 maj 2019 22:53:09
Till: ApolloAuto/apollo
Kopia: Noa Lindén; Mention
Ämne: Re: [ApolloAuto/apollo] Is there an up to date guide on how to start the perception module? (#7320)


@vattenbuffel<https://github.com/vattenbuffel> I am very sorry to hear you had such a difficult time get Apollo up and running. We take our developer experience very seriously, and I'd love to connect with you and hear more about your experience. Please send me an email at wuzhenni01@baidu.com<mailto:wuzhenni01@baidu.com> and I'd love to learn more about your experience.

**Comment by jxr041100** [comment]
I have followed the instructions and play perception module, **but from dreamview does not show any perception result.**

`cyber_launch start /apollo/modules/transform/launch/static_transform.launch`
`cyber_launch start modules/drivers/tools/image_decompress/launch/image_decompress.launch`
 `cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch
`
`cyber_recorder play -f /apollo/data/bag/2021-03-18-21-39-11/20210318213911.record.00000 -r 0.2`


![Screenshot from 2021-03-28 11-52-26](https://user-images.githubusercontent.com/13891628/112764173-332ad200-8fbc-11eb-93e2-5d5a9bdc353e.png)
