### ISSUE TITLE
Support rostopic and topic_tools Like Tools in Cyber

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#7329]
Now that apollo is primarily using cyber for communications, there are some basic diagnostic tools missing. ROS, has [rostopic](http://wiki.ros.org/rostopic) and [topic_tools](http://wiki.ros.org/topic_tools). There is `cyber_monitor`, but it is not as general purpose and does not interoperate with shell.

A simple cyber_echo that takes arbitrary messages without a pb description would be very useful. It seems that protobuf description gets transmitted, but the `cyber::Reader` needs the explicit type.

Just supporting `google::protobuf::Any` or `google::protobuf::Message` in reader would be a good start. Then, users can write these tools easier.

Some of the nice features in shell is echoing a topic, then piping it `grep` and saving as plain text to a file. The bandwidth feature and info would be nice from rostopic. The relay tool is useful from topic_tools.

**Comment by yaoweifeng01** [comment]
@Fla3inH0tCheet0s Thanks for your suggestion. The tools you suggested are already in our plan, and soon you will see related tools like cyber_channel.

**Comment by natashadsouza** [comment]
Closing this issue currently. Thank you so much for your suggestion @Fla3inH0tCheet0s 
We will let you know once we have released the tools.
