### ISSUE TITLE
Permission Denied when running scripts/bootstrap.sh

### ISSUE THREAD

**Issue by michaelowenliu** [ApolloAuto/apollo#7336]
root@in_dev_docker:/apollo# sudo bash scripts/bootstrap.sh
scripts/bootstrap.sh: line 30: ./scripts/monitor.sh: Permission denied
scripts/bootstrap.sh: line 31: ./scripts/dreamview.sh: Permission denied
root@in_dev_docker:/apollo# bash scripts/bootstrap.sh
scripts/bootstrap.sh: line 30: ./scripts/monitor.sh: Permission denied
scripts/bootstrap.sh: line 31: ./scripts/dreamview.sh: Permission denied

**Comment by Eclipsehelio** [comment]
find . -name "*.sh" | xargs chmod a+x
find . -name "*.bash" | xargs chmod a+x

**Comment by michaelowenliu** [comment]
> find . -name "*.sh" | xargs chmod a+x
> find . -name "*.bash" | xargs chmod a+x

@Eclipsehelio Hi,
Thank you. solve this problem. Now dreamview webpage shows nothing. Module monitor and dreamview are running. I have followed previous issues already, but it still fails to show.

My host server is Ubuntu 18.04

`root@in_dev_docker:/apollo# sudo bash scripts/bootstrap.sh
Module monitor is already running - skipping.
Module dreamview is already running - skipping.`

**Comment by Eclipsehelio** [comment]
@michaelowenliu Sorry for the delayed response. 
Are you visiting dreamview on another computer? 
What's the web browser you are using(recommended to use firefox)? 
I think you should use wget command to verify that dreamview is actually running in the docker container firstly, just like this:
**wget localhost:8888**
As the first step is ok, then you could do it outside the container.
Or all the above steps do failed, could you upload the dreamview's log(/apollo/data/log/)?

**Comment by michaelowenliu** [comment]
> @michaelowenliu Sorry for the delayed response.
> Are you visiting dreamview on another computer?
> What's the web browser you are using(recommended to use firefox)?
> I think you should use wget command to verify that dreamview is actually running in the docker container firstly, just like this:
> **wget localhost:8888**
> As the first step is ok, then you could do it outside the container.
> Or all the above steps do failed, could you upload the dreamview's log(/apollo/data/log/)?

@Eclipsehelio Hi, after updating the repo, it works. Thank you.

**Comment by omaidb** [comment]
monitor.log.info.20190819-174547.13339
Log file created at: 2019/08/19 17:45:47
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0819 17:45:47.556493 13339 class_loader_utility.h:78]  registerclass:Monitor,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/monitor/libmonitor.so

**Comment by omaidb** [comment]
[log.tar.gz](https://github.com/ApolloAuto/apollo/files/3515553/log.tar.gz)
这是相关的日志
