### ISSUE TITLE
problem about How to Run Perception Module on Your Local Computer

### ISSUE THREAD

**Issue by basser2** [ApolloAuto/apollo#7339]
Install Nvidia driver in docker failed ! [ How to Run Perception Module on Your Local Computer ]
![image](https://user-images.githubusercontent.com/42443887/54613793-497d2980-4a96-11e9-9d69-ab023f16dff4.png)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**

How to fix this？

**Comment by Logital** [comment]
This may be because your ubuntu16 GUI service, StartX, can try to end it.

**Comment by natashadsouza** [comment]
@basser2 were you able to resolve this issue, if so we would like to close it. Thanks!
