### ISSUE TITLE
Dark SCNN postprocessing pipeline working?

### ISSUE THREAD

**Issue by DevMohamedMI** [ApolloAuto/apollo#7345]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**:
Binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
3.5

Hey, we created a launch file to run dag_streaming_perception_lane.dag on the master branch, in order to take advantage of the new Dark SCNN lane line neural network. We've verified a confidence mask is coming through as an output of the NN, but it looks like the lane postprocessing pipeline is not processing the segmentation mask correctly yet, and therefore outputting no lane line objects. We were wondering what the status of this was, and is DarkSCNN functionality something to expect soon?

**Comment by techoe** [comment]
The new lane line detection module is working fine. Please use dag_streaming_perception_lane.dag for Dark SCNN lane line detection and all other camera-based detection.

**Comment by yyuuliang** [comment]
hi, 
I have also noticed the new lane detection method is introduced in 3.5. where can I find the Dark SCNN module?
