### ISSUE TITLE
Lidar module about "Spp" and cnn_segmentation

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#7348]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source )**:
- **Apollo version (3.5)**:

In lidar modules, there is the "Spp_engine" directory, what is mean about "Spp" ? 
apollo 3.5 open the cnn_segmentation algorithm about point cloud ?

**Comment by breakisx** [comment]
that is Spatial Pyramid Pooling  ?

**Comment by chenggongliang** [comment]
> that is Spatial Pyramid Pooling ?

Do you have an answer?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
