### ISSUE TITLE
Can I use apollo3.5 to realize Tracking function without camera, Iidar and radar 

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#7398]
I only have GPS/IMU, can I use apollo 3.5 to realize Tracking function without camera, Iidar and radar, just like function in apollo 1.0?
how should I do?

**Comment by mickeyouyou** [comment]
Yeah, Absolutely yes!
You can select the mode `RTK`, that keep the same function and logic with Apollo 1.0.

How to use the RTK Mode，you can refer this issue #5423

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you additional questions. Thanks!
