### ISSUE TITLE
Integrating my own python path planning module with apollo

### ISSUE THREAD

**Issue by vimalrajayyappan** [ApolloAuto/apollo#7409]
Hello Everyone,

I had recently started Apollo. I'm having my own path planning module in PYTHON which I wanted to be integrated with Apollo. Please suggest me the approach you had taken for making the Apollo use your own path planning algorithm. This is entirely in a simulation environment.

Since I'm new to this please explain in a bit detail.

**Comment by natashadsouza** [comment]
Apollo currently functions as a single system, therefore before adding a module to it, understand that there would be a lot of additional work to be done to ensure that the module functions perfectly with the other modules of Apollo. Firstly, add your module to the `modules/` folder. You can use `modules/routing` as an example, which is a relatively simple module. Write the BUILD files properly and apollo.sh will build your module automatically. I would also recommend reading through our planning documentation to understand what should be your input and output formats.

**Comment by vimalrajayyappan** [comment]
Yeah I had read 'how to' docs as you mentioned but I dint find any docs having how to add planners. I have developed my module in PYTHON. Will be more helpful if you provide me link to steps. Thanks

**Comment by Dezhao-Huang** [comment]
I don't think they answer this question well. No specifics at all.

**Comment by xiaoxq** [comment]
Now we are using Bazel to manage python packages. Please refer to Bazel docs for adding new module :)
