### ISSUE TITLE
How do I know the apollo version that I git clone?

### ISSUE THREAD

**Issue by mmdai617** [ApolloAuto/apollo#7425]
Hello everyone, I encounter a problem when I try to install baidu apollo recently. That is, how do I know the apollo version that I git clone when I use '' git clone http://github.com/apolloauto/apollo''?  Can I specify the version to install? Actually I want to install apollo v2.5 or v3.0.

**Comment by HongyiSun** [comment]
You can switch a git branch by something like: ```bash
git checkout remotes/origin/r3.0.0
```
after cd in to the apollo folder

**Comment by natashadsouza** [comment]
@mmdai617 please note that if you clone master it will always be the latest verison. Also as HongyiSun mentioned, there are branches that you could go to, to see which version of Apollo you would like to install
