### ISSUE TITLE
Import apollo hdmap xodr file

### ISSUE THREAD

**Issue by yumianhuli2** [ApolloAuto/apollo#7426]
Hello,if I have apollo hd map.xodr.where can I put apollo hd map.xodr file in apollo3.0 docker ?
Thanks!

**Comment by HongyiSun** [comment]
In apollo docker, the map files are mounted to `/apollo/modules/map/data/' folder

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
