### ISSUE TITLE
received unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by mmdai617** [ApolloAuto/apollo#7428]
Hello, everyone. Recently I am disturbed by the following problem and need your help.
After git clone apolloauto/apollo, when I try to pull the image using the command "bash docker/scripts/dev_start.sh -C" , I get the following error: 
**received unexpected HTTP status: 500 Internal Server Error
[ERROR] Failed to pull docker image.**

My docker version is 18.09.3, ubuntu version is 16.04LTS

Appreciate for your help!

![Screenshot from 2019-03-23 12-06-15](https://user-images.githubusercontent.com/47624638/54861465-25ef0300-4d64-11e9-942c-d162dc58150f.png)

**Comment by mickeyouyou** [comment]
It's a response of docker hub, you can remove the paramete `-C` and try agian.

**Comment by wuhangchen** [comment]
the trouble that i also  pull the apollo 3.5.0 of version images, therefore now is it salve now ?please help me?but i use the option of -C it sames also some probleam?

**Comment by mickeyouyou** [comment]
That was intermittent. Next time double check from another machine if possible.

**Earlier thoughts:**
With the default docker-machine running, regenerating the tls certs:

`docker-machine regenerate-certs`

fixes the problem, sometimes, for one pull. But has also yielded:

```
 Error response from daemon: Get <url omitted>: Get <url omitted>: 
 net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by JokerLbz** [comment]
Hello， I have met the same problem.
Whenever I want to pull the container `3f91447c5641` and `0796d528009a` the server responded to me HTTP error 500.
And i solved the problem by using `bash docker/scripts/dev_start.sh` **without parameter** `-C`.

**Comment by mickeyouyou** [comment]
please refer last comment to solve issue like this, thank you .
