### ISSUE TITLE
PERCEPTION: Failed to get shared data: CameraSharedData

### ISSUE THREAD

**Issue by warden2018** [ApolloAuto/apollo#7432]
### System information

- **OS Platform Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 3.0**:

### Steps to reproduce the issue:
- **DAG file: modules/perception/conf/dag_camera_obstacle_vis.config**
- **Three cameras are working real time and topics are ready**
- **The Camera visualizer has real time detection for 10 seconds and then stuck there**
- **Below is the visualizer content and the perception.ERROR log from /apollo/data/log/**

### Supporting materials (screenshots, command lines, code/script snippets):
![1871545360](https://user-images.githubusercontent.com/48422255/54873876-08c93b80-4e1b-11e9-953c-91cdcda0a4c5.jpg)
[perception.txt](https://github.com/ApolloAuto/apollo/files/2999962/perception.txt)

**Comment by mickeyouyou** [comment]
Repeated error message in the log: 
```log
Log file created at: 2019/03/14 16:16:25
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0314 16:16:25.383870 32203 visualization_subnode.cc:247] Failed to get shared data: CameraSharedData
E0314 16:16:26.494545 32203 visualization_subnode.cc:247] Failed to get shared data: CameraSharedData
E0314 16:16:26.657229 32203 visualization_subnode.cc:247] Failed to get shared data: CameraSharedData
E0314 16:16:26.782308 32203 visualization_subnode.cc:247] Failed to get shared data: CameraSharedData
E0314 16:16:26.884235 32203 visualization_subnode.cc:247] Failed to get shared data: CameraSharedData
```

**Comment by techoe** [comment]
When the visualization module does not receive a camera frame at moment, this message will be shown, but it won't affect any performance.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
