### ISSUE TITLE
Apollo Kernel and Tesla P4 GPU driver installation issue

### ISSUE THREAD

**Issue by warden2018** [ApolloAuto/apollo#7433]
I have this issue for several days. I hope community can give us a better documented article: How to install GPU driver and Apollo kernel at one PC and no problem. Many thanks for Baidu side or developers.

### System information

- **OS Platform Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 3.0**:

### Steps to reproduce the issue:
- **I am running Apollo 3.0 perception in a real car**
- **Perception of camera part can run only for 10 seconds: https://github.com/ApolloAuto/apollo/issues/7432**
- **I am not sure whether it is related to the apollo kernel not installed in the system**
- **So in order to make sure EVERYTHING is installed, I try to do complete installation.**

- **I do the steps according to this: https://github.com/ApolloAuto/apollo-kernel/blob/master/README.md**

- **I have two Tesla P4 NVIDIA GPU, and the official driver for this GPU is 384.66**

- **After installing Apollo kernel, I modify the install-nvidia.sh**

`NV_FILE="NVIDIA-Linux-x86_64-384.66.run"`

- **It says done to install nvidia kernel driver and user libraries**
- **But after nvidia-smi the result is not good:**

> Failed to initialize NVML: Function Not Found
![install-nvidia](https://user-images.githubusercontent.com/48422255/54874197-3dd88c80-4e21-11e9-89d5-7bad2df49653.png)
![install-folder](https://user-images.githubusercontent.com/48422255/54874198-3e712300-4e21-11e9-9b08-1a6652798a4b.png)

### Another try:
What is more, I also tried this article for GPU compilation of Apollo part. This part has steps for how to install kernel and GPU at the same time.
[Apollo develop community:开发者说 | Ubuntu14.04搭建GPU版本的Apollo3.5平台](https://mp.weixin.qq.com/s?__biz=MzI1NjkxOTMyNQ==&mid=2247486500&idx=1&sn=9536e50520d940888bf2d81565be0bde&chksm=ea1e1e56dd6997400291cac3b0665d4dafd0b30b7069dc0a6c5e68a6e2d385c552586e9578b4&mpshare=1&scene=1&srcid=0319piDDpzUbbxIK9DgBHy9m&pass_ticket=Jfs5KnpDd8vbpGAufcIy9yrOeky9WO%2BZXy%2FtM5IPg6d2km7STa2A4o3bzDTRkKWm#rd)

And this article does not work for me: [Developer's solution for IPC：Nuvo-5095GC GPU: NVIDIA GTX-1050Ti](https://note.youdao.com/ynoteshare1/index.html?id=f1f44a10594d9134281b917e3923a3e4&type=note#/)
After these steps infinite login issue arises.

**Comment by gengqx** [comment]
can you put  the log (data/log/perception.INFO) here ?

**Comment by warden2018** [comment]
@gengqx Hi!
The INFO file is here. But I am not sure whether this is something with my issue. I already check that there is no frame input skip for camera_process_subnode. But Dreamview and camera visualizer seems not working well. 
[perception.txt](https://github.com/ApolloAuto/apollo/files/3012029/perception.txt)

**Comment by gengqx** [comment]
if it can only run for several seconds,then you can use 
```
bash scripts/perception.sh start_fe
```
to see the error.

**Comment by warden2018** [comment]
@gengqx Thanks! The perception.ERROR no longer has issues of camera visualizer. Works for me.

**Comment by warden2018** [comment]
@gengqx  Do you have some advice of installing Apollo kernel and GPU driver?

**Comment by gengqx** [comment]
I'm not apollo team.Currently, I did not evaluate the kernel performance,but this kernel would have effect on the nvidia driver,so,I did not install apollo kernel any more.

**Comment by warden2018** [comment]
@gengqx  So your vehicle can run Apollo in REAL ROADS without Apollo kernel installed?

**Comment by gengqx** [comment]
Yes.

**Comment by warden2018** [comment]
I did it successfully. Always install apollo kernel first.
Use the install-nvidia.sh provided by the Apollo kernel. Note that Apollo kernel has one version: 375.**. So If the flag NEED_TO_COMPILE_NV_KO is set to 0, we need to set it 1 and it means to compile the exactly same .ko files for the kernel to modprobe.
Actually, after modifying two lines:
```
NV_FILE="NVIDIA-LINUX-X86_64-384.66.run"
NV_URL="http://us.download.nvidia.com/XFree86/Linux-x86_64/384.66/${NV_FILE}"
```

The .run installer file will be downloaded and extracted into a folder. But with wrong name:appended -diagnostic. So first 

```
#!/bin/bash
mv NVDIA-Linux-x86_64-384.66-diagnostic NVDIA-Linux-x86_64-384.66
```

And the .sh file can find the source folder and do compiling and installation.
Remember that .ko files is installed into /lib/modules/4.4.32-apollo-2-RT/kernel/drivers/video/ .
More to read can refer to the install-nvidia.sh file. Now SVB has only GPU driver 384.66 for Tesla P4.
After all this, reboot is preferred.

**Comment by Kailiangdong** [comment]
hello ,Do you finally succussfully install apollo on P4 server?Thank you . @warden2018
