### ISSUE TITLE
How can i connecting apollo ros to outside docker simulator in window10

### ISSUE THREAD

**Issue by rhtm02** [ApolloAuto/apollo#7434]
I wanna connecting apollo and window10 matlab's prescan simulator fortunTley matlab aplliance Robot System Toolbox so i make Publish topic ("/apollo/point" type: geometry_msg/Point)in matlab and in docker use command " rostopic list "  is there my publish topic "/apollo/point" but i use command "rotopic echo" nothing in there  i think this issue is maybe docker IP issue anybody please help me

**Comment by natashadsouza** [comment]
@rhtm02 which version of Apollo are you trying to build out, and could you share your system information. Thanks!

**Comment by rhtm02** [comment]
I'm using apollo 2.5 version and in docker ubuntu 14.04 ver using apollo build setting !!

**Comment by natashadsouza** [comment]
Unfortunately we have not tested Matlab and Apollo's compatibility. We can wait to see if any other developers in the community have tested it and if there were successful. Sorry I could not be of more assistance.

**Comment by rhtm02** [comment]
@natashadsouza  Thx  !!!

**Comment by natashadsouza** [comment]
Closing this issue currently. Should we decide to support matlab, we will communicated the same to you. Thanks for your support to the Apollo platform!
