### ISSUE TITLE
Modify record file

### ISSUE THREAD

**Issue by AOIlunar** [ApolloAuto/apollo#7437]
Is there a way that I can extract information, write in information or delete information in a record file?
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

**Comment by yaoweifeng01** [comment]
Hi @AOIlunar ,there are two ways to modify record, C++ and Python API. Please refer to [C++ Record Demo](https://github.com/ApolloAuto/apollo/blob/master/cyber/examples/record.cc),[Python Record Demo](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/examples/record_trans.py). For more, please read this document  [CyberRT_API_for_Developers](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_API_for_Developers.md#Record-file-Read-and-Write).Hope to help you.
