### ISSUE TITLE
Docker error response from demon

### ISSUE THREAD

**Issue by Prj1508** [ApolloAuto/apollo#7438]
I am not able to launch the docker in Apollo. When I do bash docker/scripts/dev_start.sh, it throws an error message as below

docker: Error response from daemon: Error processing tar file(exit status 1): unexpected EOF.
See 'docker run --help'.

and then...

[ERROR] Failed to start docker container "apollo_dev_Prj1508" based on image: apolloauto/apollo:dev-x86_64-20190228_1414

I cleaned my local repo and cloned the fresh image from main, but the issues remains. Please let me know as I am stuck for couple of days on this

thanks

**Comment by natashadsouza** [comment]
@Prj1508 could you give us additional details like which version of Apollo you are working on and your system specifications.

**Comment by Iqbalparvi** [comment]
Hi.... any one plz  need sugestions to solve this issue..
 bash docker/scripts/dev_start.sh
[sudo] password for iqbal: 
fetch: Fetching reference refs/heads/r3.5.0
[INFO] Start pulling docker image apolloauto/apollo:dev-x86_64-20181210_1500 ...
dev-x86_64-20181210_1500: Pulling from apolloauto/apollo
Digest: sha256:283773f0c1ee31e7615db642f0973a6d443453e335355ca0ac0030d56d2b69f4
Status: Image is up to date for apolloauto/apollo:dev-x86_64-20181210_1500
map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:68ab11db001d315fcd896a06d9100e6fa6ac0f2d578b6988a4e194b02cee62da
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
docker: Error response from daemon: failed to copy files: userspace copy failed: write /var/snap/docker/common/var-lib-docker/volumes/9e4ad6977b98868bdd337451359b449a15b3e904f8ecefcfb711988074aeec8f/_data/base_map.txt: no space left on device.
See 'docker run --help'.
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_loop-latest
docker: Error response from daemon: failed to copy files: userspace copy failed: write /var/snap/docker/common/var-lib-docker/volumes/5d19c5ac65033cfb933b363209a49a4d514f9f67e32a2f0c82d435dd40e4fcce/_data/base_map.xml: no space left on device.
See 'docker run --help'.
map_volume-sunnyvale_with_two_offices-latest: Pulling from apolloauto/apollo
Digest: sha256:9f94f738f3f84521dfb14f1d46c769f1f44ff430f479712e1c0ece5fe2772907
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_with_two_offices-latest
docker: Error response from daemon: failed to copy files: userspace copy failed: write /var/snap/docker/common/var-lib-docker/volumes/4ec64d238584a85282e3e6c7df6acfc6c64842d833311abcbc158a78b97cc0ee/_data/local_map/map/000/north/10/00032351/00004587: no space left on device.
See 'docker run --help'.
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.15.0-45-generic
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.15.0-45-generic
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:94af1ac560730db7daf192ebf7b091f88059e62e425ceccd6375fbf4578e7f3f
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
3023a0844ba254c764d4e83488cbf76f6f2a33941ddea0b5e41de9f9bd71da92
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
docker: Error response from daemon: failed to copy files: userspace copy failed: write /var/snap/docker/common/var-lib-docker/volumes/cee67aa964b2bf667d0efe248d7b8f02c9e8765a51c664a08769d05942e18837/_data/deploy.md: no space left on device.
See 'docker run --help'.
[INFO] Starting docker container "apollo_dev_iqbal" ...
docker: Error response from daemon: No such container: apollo_map_volume-sunnyvale_big_loop_iqbal.
See 'docker run --help'.
[ERROR] Failed to start docker container "apollo_dev_iqbal" based on image: apolloauto/apollo:dev-x86_64-20181210_1500
OS: Ubuntu 16.04, apollo 3.5

**Comment by gengqx** [comment]
@Iqbalparvi Your computer has no space left,cause this error.

**Comment by Iqbalparvi** [comment]
@gengqx any dir to make it free..

**Comment by natashadsouza** [comment]
@Iqbalparvi you need atleast 6GB of space before building out Apollo. I would recommend deleting Apollo repo freeing up some space and then trying again.

**Comment by Iqbalparvi** [comment]
@natashadsouza i have free space but idont know why this problem occur,can u please give me any link to make delete of log files of docker program

**Comment by natashadsouza** [comment]
@Iqbalparvi if you had free space, the error would not have occurred. Could you share your system's information with us?

**Comment by Iqbalparvi** [comment]
@natashadsouza its Ubuntu 16.04, Apollo 3.5, i think its root directory space error and the proc file used space in TB but i cant free this till ...is there any comand to free space from root directory or proc files

**Comment by natashadsouza** [comment]
@Iqbalparvi you could run the following on your host:
docker/setup_host/cleanup_resources.sh to free some resources.
Let me know if this helps!

**Comment by Iqbalparvi** [comment]
Thank you so much  I fixed the problem now..

**Comment by Prj1508** [comment]
@natashadsouza its Ubuntu 16.04, Apollo 3.5,

**Comment by Prj1508** [comment]
My system has GPU1070

**Comment by natashadsouza** [comment]
@Prj1508 could you send us a screenshot of the error messages you see?

**Comment by Thinsheep** [comment]
@Iqbalparvi 
How did you fix your problem?
