### ISSUE TITLE
How can I test the control module without a real car?

### ISSUE THREAD

**Issue by Younch-15** [ApolloAuto/apollo#7442]
- **Apollo version**:3.5

I have been trying to test the performance of the sample vehicle lincoln mx8 under a given complex path. After I compiled `control_component_test.cc` in `apollo/modules/control` and manually input a straight path which started at (0,0,0) and ended at (4.6,0,0), I found the .INFO file like this:

> Log file created at: 2019/03/25 13:34:28
> Running on machine: in_dev_docker
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> I0325 13:34:28.812129 11484 control_component.cc:42]  Control init, starting ...
> I0325 13:34:28.837960 11484 control_component.cc:48]  Conf file: /apollo/modules/control/testdata/conf/control_conf.pb.txt is loaded.
> I0325 13:34:28.837970 11484 control_component.cc:50]  Conf file:  is loaded.
> I0325 13:34:28.837975 11484 controller_agent.cc:36]  Only support MPC controller or Lat + Lon controllers as of now
> I0325 13:34:28.838163 11484 lat_controller.cc:84]  Using LQR-based Lateral Controller
> I0325 13:34:28.838241 11484 lon_controller.cc:76]  LON_CONTROLLER used.
> I0325 13:34:28.838587 11484 lat_controller.cc:250]  Lateral control gain scheduler loaded
> I0325 13:34:28.838889 11484 lat_controller.cc:155]  LQR-based Lateral Controller begin.
> I0325 13:34:28.838897 11484 lat_controller.cc:156]  [LatController parameters] mass_: 2080, iz_: 4208.3, lf_: 1.4224, lr_: 1.4224
> I0325 13:34:28.838944 11484 controller_agent.cc:94]  Controller <LQR-based Lateral Controller> init done!
> I0325 13:34:28.838956 11484 lon_controller.cc:128]  Control calibration table loaded
> I0325 13:34:28.838973 11484 lon_controller.cc:129]  Control calibration table size is 2694
> I0325 13:34:28.840996 11484 controller_agent.cc:94]  Controller <LON_CONTROLLER> init done!
> I0325 13:34:28.850347 11484 control_component.cc:98]  Control resetting vehicle state, sleeping for 1000 ms ...
> I0325 13:34:29.850587 11484 control_component.cc:104]  Control default driving action is STOP
> E0325 13:34:29.852226 11491 control_component.cc:265]  **Chassis msg is not ready!**
> I0325 13:34:29.868499 11495 lon_controller.cc:413]  **the last point found in path and speed > speed_deadzone**
> I0325 13:34:29.874752 11493 lon_controller.cc:413]  the last point found in path and speed > speed_deadzone
> I0325 13:34:29.885205 11491 lon_controller.cc:413]  the last point found in path and speed > speed_deadzone
> I0325 13:34:29.896140 11501 lon_controller.cc:413]  the last point found in path and speed > speed_deadzone
> I0325 13:34:29.907552 11500 lon_controller.cc:413]  the last point found in path and speed > speed_deadzone
> I0325 13:34:29.917747 11486 lon_controller.cc:413]  the last point found in path and speed > speed_deadzone
> ...

Now I'm wondering if I have missed some important configuration, or it's just unable to test the control module without a real car (with real GPS message input)?

Any help would be appreciated!

**Comment by Capri2014** [comment]
Not as of now, but stay tuned ! :)

**Comment by natashadsouza** [comment]
Hi @Younch-15 thank you for using Apollo and for submitting this request. We will let you know when you would be able to test the control module without a vehicle. Thanks and stay tuned!

**Comment by Younch-15** [comment]
Thanks for the reply! Can I get a control command just using those planning/chassis/localization/pad .pb.txt files? Or is there any other information, such as map or GPS, which the control module also uses as input?
