### ISSUE TITLE
bash docker/scripts/dev_start.sh issue on adduser

### ISSUE THREAD

**Issue by aravindSwamy94** [ApolloAuto/apollo#7444]
Please find my error below:

map_volume-sunnyvale_big_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:68ab11db001d315fcd896a06d9100e6fa6ac0f2d578b6988a4e194b02cee62da
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_big_loop-latest
863a428e12144c5f65e01f8ddf0fdd296f6f224a78721549fd1335ce957519b5
map_volume-sunnyvale_loop-latest: Pulling from apolloauto/apollo
Digest: sha256:1337ca5d357f33318e38368b6218d343f6138c63a9bb491175ca7cdd39c1a789
Status: Image is up to date for apolloauto/apollo:map_volume-sunnyvale_loop-latest
616515bb96ae8702c4f095487451be81da527e56e9664b1d84a821100a3b4c25
[INFO] Start docker container based on local image : apolloauto/apollo:abcdef
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:94af1ac560730db7daf192ebf7b091f88059e62e425ceccd6375fbf4578e7f3f
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
9a795d6c17692ca15fdc14e8fa40af24f39564b8c86fae2d442295fec69fc1e2
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
7b5c4cededc79187df113fa81204116be4ad30ba1d9a7a8ca5bf33a2ff5e3ee0
[INFO] Starting docker container "apollo_dev" ...
b8a071c29a5c6820c67a8a75db932ccec5556183d1bd9130b1f1f89788b76efa
**bash: /apollo/scripts/docker_adduser.sh: Permission denied**
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!

Also with the above error, dev_into.sh is also not working . It shows,

unable to find user xXx: no matching entries in passwd file

**Comment by natashadsouza** [comment]
@aravindSwamy94 could you give us additional details like which Apollo version are you running on, system information and steps to reproduce you error message. Thanks!

**Comment by aravindSwamy94** [comment]
Hi @natashadsouza : Im using apollo 3.5 version . And im just running, 
bash docker/scripts/dev_start.sh


That gives me this error.
where im not able to enter into docker

**Comment by natashadsouza** [comment]
@aravindSwamy94 check the recommendation on #7079 and let me know if it resolves your issue. Thanks!

**Comment by lzc201147** [comment]
Hi @aravindSwamy94 , I have met the same problem, I'm also using Apollo 3.5 version, the following information are displayed in termination:
[INFO] Starting docker container "apollo_dev_" ...
f97075dfa68ca0da2be4c94d061c4845e896378cee5acfe7ae0e5cb9eba42095
Adding group `docker' (GID 999) ...
Done.
usermod: user '' does not exist
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
lzc@lzc-Lenovo:~/apollo$ bash docker/scripts/dev_into.sh
unable to find user -it: no matching entries in passwd file
So,,,   how do you solve the problem??

**Comment by natashadsouza** [comment]
@lzc201147 we believe it could be a Git LFS issue, our [Software FAQs](https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md) should help support this better. Let me know if you have any additional questions.

**Comment by amontserratAG** [comment]
Hi, I have a different output error:

$ bash docker/scripts/dev_into.sh 
Error response from daemon: Container e3543972b1fd14d72c5f474c0c32452abaeaf296a6cb0b4ef955f360353852e1 is not running

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have any questions. Thanks!

**Comment by dingjiangang** [comment]
I have met the same problem, I'm also using Apollo 3.5 version, the following information are displayed in termination:
[INFO] Starting docker container "apollo_dev_" ...
f97075dfa68ca0da2be4c94d061c4845e896378cee5acfe7ae0e5cb9eba42095
Adding group `docker' (GID 999) ...
Done.
usermod: user '' does not exist
[ OK ] Finished setting up Apollo docker environment. Now you can enter with:
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
lzc@lzc-Lenovo:~/apollo$ bash docker/scripts/dev_into.sh
unable to find user -it: no matching entries in passwd file
So,,, how do you solve the problem??
