### ISSUE TITLE
Incorrect IMU Type numbers in the Novatel Driver

### ISSUE THREAD

**Issue by FlorentRevest** [ApolloAuto/apollo#7450]
I have a PwrPak7-E1 which integrates an EPSON G320N IMU.
My GNSS protobuf config file sets the _imu_type_ argument to _G320N_ and is read correctly (the debug logs show that G320N is read)
However, the GNSS driver tries to read the IMU type from the PwrPark and detects a _CPT_XW5651_ instead. It then uses parameters of the CPT XW5651 (such as the sampling rate) which are incorrect in my setup and ends up with thousands of unexpected delay in IMU data.
While reading the Novatel documentation, I found the table of correspondences between IMU types and their numbers https://docs.novatel.com/oem7/Content/SPAN_Commands/CONNECTIMU.htm
It appears that Novatel has assigned the number 41 to the _G320N_ while Apollo has assigned the number 41 to the _CPT_XW5651_ and 40 to G320N.
By swapping the values of the G320N with the values of the CPT_XW5651 in modules/drivers/gnss/proto/config.proto, I was able to get the driver to find the correct parameters for my IMU and work correctly.
I suspect that many of the imu_type values in modules/drivers/gnss/proto/config.proto are wrong. I would have loved to send a PR to correct them but I don't find most of the IMUs listed in the Apollo code in the Novatel documentation (for instance I can't find what the number of CPT_XW5651 should be)

**Comment by natashadsouza** [comment]
@FlorentRevest thank you so much for using Apollo. Apollo currently only works with limited GNSS hardware as you can see in the [Specs documents](https://github.com/ApolloAuto/apollo/tree/master/docs/specs/Navigation). We are in the process of evaluating and adding new sensors to our platform daily. But for now, I highly encourage you to submit a PR for those IMUs that you are confident about to help our community :)
