### ISSUE TITLE
Apollo community gitter chat for  apollo setup ,use , develop , gitter.im/ApolloAutoCN

### ISSUE THREAD

**Issue by stingzheng** [ApolloAuto/apollo#7464]
Apollo community gitter chat for  apollo setup ,use , develop .  weclome to add and share about your apollo and autopilot  experience!  [ not official  ]

https://gitter.im/ApolloAutoCN

**Comment by natashadsouza** [comment]
Thank you for creating it @stingzheng 
Let's keep this community vibrant!
