### ISSUE TITLE
The frequency of "/apollo/perception/obstacles"

### ISSUE THREAD

**Issue by lhh0916** [ApolloAuto/apollo#7467]
Hello, what is the output frequency of apollo 3.5 "/apollo/perception/obstacles"? I only input the data of lidar64 (not including lidar128/16, camera and radar), run the perception module, monitor with cyber_monitor, The frequency of "/apollo/perception/obstacles" is about 0.88 ~ 1. Why is it so low?

Channels                                             FrameRatio
/apollo/localization/pose                           100.05
/apollo/perception/obstacles                         0.91
/apollo/sensor/camera/front_12mm/image               0.00
/apollo/sensor/camera/front_6mm/image                0.00
/apollo/sensor/velodyne64/compensator/PointCloud2   9.87
/perception/camera_debug                             0.00
/perception/obstacles                                0.00
/tf                                                  100.00
/tf_static                                           0.00

另外,请问哪里有提供apollo3.5的sample包,包含lidar128/16,camera 6mm/12mm,radar及相关pose,tf等的输入topic,并带有hdmap demo?

**Comment by techoe** [comment]
0,91 is too low. What GPU and CPU were you using for this test?

**Comment by lhh0916** [comment]
@techoe 
Sorry, I compiled with "./apollo.sh build". I always thought that "./apollo.sh build" was compiled by GPU by default, and then tried again "./apollo.sh build_opt_gpu" compiled, the output is 10Hz.
This problem has been solved, thank you!

**Comment by natashadsouza** [comment]
Closing this issue as the issue as been resolved.
