### ISSUE TITLE
why in the docker i cant init my can device,while outside docker it init successfully

### ISSUE THREAD

**Issue by wyqhnr** [ApolloAuto/apollo#747]
is there any difference between running application in the docker and outside the docker?
seems the docker image and the host share the same ip address,because my udpapplication run well in the docker as outside.
how can i use my can device in the docker?any suggestion?

**Comment by Capri2014** [comment]
May I know why you need to init your can device inside docker? In general, we first setup_device before enter into docker in `scripts/apollo_base.sh`, and map this can device in `docker/scripts/dev_start.sh`

**Comment by wyqhnr** [comment]
for now, i intend to build an minimum apollo ros environment with a pc and notebook. i have built apollo and installed apollo ros on both computers.When i put my can_program in docker, the problem appears. 
It was simple can program compiled by qtcreator outside the docker. 
the example code is as follow:
////////////////////////////////////////////////////////////////////////////////////////////////////
#include <pthread.h>

#define PCAN_DEVICE		PCAN_USBBUS2

/*
int main(int argc, char* argv[]){
  pthread_t f1_thread; 
  void* _main(void*);
  pthread_create(&f1_thread,NULL,_main,NULL);
  pthread_join(f1_thread,NULL);
}
*/
//void* _main(void*)
int main(int argc, char* argv[])
{
	TPCANMsg Message;
	TPCANStatus Status;
	unsigned long ulIndex = 0;

	Status = CAN_Initialize(PCAN_DEVICE, PCAN_BAUD_500K, 0, 0, 0);
	printf("Initialize CAN: %i\n",(int)Status);

	Message.ID = 0x77;
	Message.LEN = 8;
	Message.MSGTYPE = PCAN_MESSAGE_EXTENDED;
	Message.DATA[0]=0;

	while(1)
	    while ((Status=CAN_Write(PCAN_DEVICE,&Message)) == PCAN_ERROR_OK) {
		Message.DATA[0]++;
	        ulIndex++;
	        if ((ulIndex % 1000) == 0)
		        printf("  - T Message %i\n", (int)ulIndex);
	    }

	printf("STATUS %i\n", (int)Status);

	return 0;
}
////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by Capri2014** [comment]
@wyqhnr  Sorry for the late reply, somehow I did not get a notice for your reply. 

Are you trying to use PCAN? We do not yet support/host PCAN inbox due the license issue, currently supported can client are only ESD_CAN and SOCKET_CAN. But if you want to customize for PCAN, I would recommend do similar things as in 
1. Add PCAN .so and header in third_party like esd_can do.
(https://github.com/ApolloAuto/apollo/blob/master/third_party/can_card_library/esd_can/README.md)

2. Write a customized PCAN client like in 
(https://github.com/Capri2014/apollo/blob/master/docs/howto/how_to_add_a_new_can_card.md) 
or you can refer to this commit (https://github.com/ApolloAuto/apollo/commit/8146e9b6220bb2d8ce3e0dca52429f9e52941230)

**Comment by wyqhnr** [comment]
thanks for your reply. @Capri2014

**Comment by AshleyRoth** [comment]
@wyqhnr Hello! how you connect CAN to your notebook?
