### ISSUE TITLE
Connect Apollo to Tools like Carsim

### ISSUE THREAD

**Issue by shreyascn7** [ApolloAuto/apollo#7481]
Hello, 

I would like to use Apollo with commercially available simulator tools such as Carsim. How do I do this? 

Is there any document that describes the inputs and outputs of Apollo Software? How do I get access to this? 

Please suggest.

**Comment by shreyascn7** [comment]
Any update on this?

**Comment by natashadsouza** [comment]
@shreyascn7 you could refer to [the Software Architecture](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Apollo_3.5_Software_Architecture.md) document for details on input/output, however as we have our own simulation software, we do not offer support on how to use Apollo on a different simulator. Thanks!
