### ISSUE TITLE
Is the proprietary libcaffe.so built in the same apollo bazel project?

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#7489]
We need to compile our own caffe dynamic library from source code and replace the proprietary libcaffe.so provided by baidu.
In the beginning, we clone the `BVLC/caffe` and compile it following the caffe official instructions. We get libcaffe.so and caffe header files, and copy it into the apollo project and replace the  proprietary libcaffe.

But we realized that the caffe depends on many third-party libs that shared with the original apollo project. for example cublas, protobuf, glog, gflag and so on.
So we must compile the caffe in the apollo bazel project. Otherwise, the cublas, protobuf, glog, gflag libs will have two versions.

We are stuck here, 3q

**Comment by xiaoxq** [comment]
Yeah, we also adapted it to Apollo, and build them in Apollo environment.
Please check https://github.com/ApolloAuto/caffe

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have any questions. Thanks!
