### ISSUE TITLE
Failed to open a caffemodel file

### ISSUE THREAD

**Issue by vattenbuffel** [ApolloAuto/apollo#7490]
### System information
Linux Ubuntu 14.04
Apollo is installed from source. The version is 3.5.
Nvidia drivers: 415.27
CUDA version: 10.0

### Steps to reproduce the issue:
1.    $APOLLO_HOME/docker/scripts/dev_start.sh
2.    $APOLLO_HOME/docker/scripts/dev_into.sh
3.    ./apollo.sh build
4.    cyber_launch start /apollo/modules/transform/launch/static_transform.launch
5.    cyber_launch start /apollo/modules/perception/production/launch/perception.launch

### Supporting materials (screenshots, command lines, code/script snippets):
![caffeError](https://user-images.githubusercontent.com/7643918/55075178-995d8100-5092-11e9-948c-f9459ce30d1a.png)

When I try to launch the perception module I get the error shown in the picture. I don't know why I get this error or how to solve it. I know that the recommended nvidia drivers is 375 and cuda 8.0 but I found it troublesome to install them. Could this be the root of the problem?

EDIT:
I did some debugging and found that it doesn't fail when opening other .caffemodel files. For example, /apollo/modules/perception/production/./data/perception/lidar/models/cnnseg/velodyne16/deploy.caffemodel works fine. Does this mean that there're no driver problems but rather a fault with /apollo/modules/perception/production/data/perception/camera/models/lane_detector/denseline/deploy.caffemodel? 

EDIT: 
I solved it by deleting, what I believe to be, the faulty file and downloaded a working one from the master branch.

**Comment by fzd9752** [comment]
@vattenbuffel Could you please share more about how to build Apollo 3.5 with CUDA version: 10.0? Thanks in advance.

**Comment by vattenbuffel** [comment]
@fzd9752 to build I just ran this command ./apollo.sh build.

Me and my peers have abandoned Apollo. It proved far too difficult to get it to work properly :(
