### ISSUE TITLE
[Cyber][scheduler]how to switch next CRoutine?

### ISSUE THREAD

**Issue by lvxin0805** [ApolloAuto/apollo#7530]
Dear Sir,
In the SchedulerClassic::DispatchTask operation, the scheduler will call PerfEventCache::Instance()->AddSchedEvent to create a croutine, and the AddSchedEvent will enqueue the SchedPerf::RT_CREATE event to event_queue_, I guess croutine module will dequeue the eventbuffer, but I can't find these codes segments.....

**Comment by zaxon** [comment]
hi~ PerfEventCache is just a performance debug module, i think u can refer to croutine module directly which have the real croutine codes
