### ISSUE TITLE
Several questions about Apollo

### ISSUE THREAD

**Issue by dingo2003** [ApolloAuto/apollo#7535]
I am from a startup corp. and responsible for one project related to autonomous driving. I am now investigating the open source platform. 
Here I have some questions about Apollo project:
1. ROS Indigo lgloo is used. Is there the plan to upgrade it?
2. I tried to install it on Ubuntu16.04 but failed. Finally I installed it on Ubuntu14.04. Is there the plan to move on ubuntu18.04?

**Comment by natashadsouza** [comment]
@dingo2003 in response to your questions:
1. Which version of Apollo are you currently building? If you are working on Apollo 3.5, we use our own framework called Cyber RT. You can[ read more about it here](https://github.com/ApolloAuto/apollo/tree/master/docs/cyber)

2. Ubuntu 16.04 should run Apollo just fine, we have had developers test it. Please refer to other issues on the same topic to resolve your concern. Migrating to Ubuntu 18 is definitely on our roadmap. More details to follow through soon.

**Comment by dingo2003** [comment]
The version I built is v3.0.
Thanks a lot for you quick response.
