### ISSUE TITLE
Msg transmission with the node outside the docker

### ISSUE THREAD

**Issue by Zhenyu-Li** [ApolloAuto/apollo#7536]
Hi,

Can people use a ros node outside the docker to get or send  msg  from/to node inside the docker?  It seems that they can connect wiht each other,  but no msg is transferred. What is the reason for this? Any advice to realize it?
 
Thanks

### System information
- **OS Platform and Distribution (Linux Ubuntu 18.04)**:
- **Apollo installed from (source )**:
- **Apollo version  (3.0)**:

**Comment by apollodevcommunity** [comment]
Have you passed \"--net=host\" parameter to the docker run command? This enables your docker to share the network with its host.  And also   consider to export the IP addresses of both sides. ——Reply reference comes from the Apollo developer community issue master contest https://apollo.auto/developer/questiondata_cn.html?target=484
