### ISSUE TITLE
One Program Multiple Domain IDs in Cyber

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#7546]
I want to create a bridge across two RTPS domains. It seems that cyber does not support this. More specifically,  [TopologyManager](https://github.com/ApolloAuto/apollo/blob/master/cyber/service_discovery/topology_manager.h#L90) is a singleton that creates fastRTPS participants. A [Participant](https://github.com/ApolloAuto/apollo/blob/master/cyber/transport/rtps/participant.cc#L69) looks up the domain via an environment variable.

It might be as simple as instantiating TopologyManager with cyber IP and domain ID as parameters. The default cyber IP and domain ID values can be read from environment variables. Also, it would be nice if there were examples programs bridging across domains.

This feature is part of RTPS. These bridges become more useful at scale. They can be used to control physical machine resources across a limited bandwidth. They may also be useful for V2X networks.

**Comment by gruminions** [comment]
Hi Fla3inH0tCheet0s, thanks for your recommendations!
Now, CyberRT can not meet your requirement to create a bridge between two RTPS domains. We will discuss and bring solutions as soon as possible.
Thank you again!
