### ISSUE TITLE
chown: invalid user: 'my_name:my_name'

### ISSUE THREAD

**Issue by kk2491** [ApolloAuto/apollo#7575]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Issue : I have installed some packages in the docker and committed the image so that I can use the same image for future use. However when I try to load the local image I am facing the below error. Could you please let me know the fix for this.

```
[INFO] *********************apollo new image is built*******************
addgroup: The GID `1001' is already in use.
usermod: user 'my_name' does not exist
chown: invalid user: 'my_name:my_name'
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
```
Though it says ```Now you can enter with: 
bash docker/scripts/dev_into.sh``` when I try it I am getting the below error:
```
unable to find user my_name: no matching entries in passwd file
```

**Comment by natashadsouza** [comment]
@kk2491 have you installed Docker using our recommended process? Also are you building directly as root? 
Another recommendation is that I think you have to remove all containers and images and also grant the correct permissions. Let me know if these help.

**Comment by kk2491** [comment]
@natashadsouza Thanks for the response.

Yes, I have installed the docker using the recommended process. And I am able to ```dev_start.sh``` without any issues, if I use the default images. Issue occurs if I use the custom docker image which is locally saved.

Thank you,
KK

**Comment by xiaoxq** [comment]
Hi @kk2491 , you are supposed to build docker image from Dockerfile instead of `docker commit` in a running container.
`scirpts/docker_adduser.sh` will setup the container accordingly. So if you bring up a container from a customized container, this script runs twice which causes conflict and failure.

**Comment by kk2491** [comment]
@xiaoxq @natashadsouza Thanks for the help. I will try to modify the dockerfile to install the required packages.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if this issue persists.
