### ISSUE TITLE
Can the cyber_monitor module add bandwidth monitoring for each channel?

### ISSUE THREAD

**Issue by zyffei** [ApolloAuto/apollo#7580]
When we deploy components distributed on multiple hosts, the components communicate through fast-rtps, hoping to monitor the network bandwidth required by each channel.

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 14.04): Linux Ubuntu 16.04
    Apollo installed from (source or binary): source
    Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 3.5

**Comment by ZeusJupiter** [comment]
Thank you for your submission. Please sign our Contributor License Agreement before we can accept it. Thanks.

**Comment by ZeusJupiter** [comment]
The method of calculating Bandwidth is inaccurate for that the size of channel message is variable at the same channel.

**Comment by zyffei** [comment]
I've updated my broadband calculating method. Please review it.
