### ISSUE TITLE
View running cyber nodes/components

### ISSUE THREAD

**Issue by krishnatoshniwal** [ApolloAuto/apollo#7584]
Is there any way to check active cyber nodes and the channels they are subscribed to?

**Comment by gruminions** [comment]
@krishnatoshniwal Thanks for your question! The tool you suggested is already in our plan, it will be released soon.

I write a sample for you to get active nodes as following:
https://github.com/gruminions/apollo/commit/83583fa4df806466bc0c177e075911249095076c

You can also use the related APIs to implement your handy tools. For example, if you want to get channels, you can use the APIs provided by ChannelManager.

Thank you again, further discussion is welcome.

**Comment by zhangchaoltt** [comment]
nice
