### ISSUE TITLE
bash apollo.sh release_noproprietary

### ISSUE THREAD

**Issue by SJHBXShub** [ApolloAuto/apollo#7588]
### System information
- **OS Platform and Distribution Linux Ubuntu 14.04 without GPU**
- **Apollo version 3.5**

### Steps to reproduce the issue:
I try to Build and Release your Docker Container. When I run this commend:
**bash apollo.sh release_noproprietary** I will confront the following error

### Supporting materials (screenshots, command lines, code/script snippets):
<img width="960" alt="微信截图_20190401161333" src="https://user-images.githubusercontent.com/30001336/55356599-1de83f00-5499-11e9-8044-a875aae59197.png">

Could you help me solve this problem?

**Comment by natashadsouza** [comment]
@SJHBXShub do you have the necessary hardware to run Apollo?

**Comment by SJHBXShub** [comment]
I do not have hardware and GPU. I open a virtual machine on Google Cloud. Linux Ubuntu 14.04. 
Here is my procedure:
1. install docker ( it is OK)
2. install LFT (It is OK)
3. bash docker/scripts/dev_start.sh( It is OK)
4. bash docker/scripts/dev_into.sh(It is OK)
5. **bash apollo.sh release_noproprietary (It is Wrong!!!)**
Do u think the procedure is right?

**Comment by SJHBXShub** [comment]
Hello, I follow the guide to run code. After I run commend as following:
install docker ( it is OK)
install LFT (It is OK)
$bash docker/scripts/dev_start.sh( It is OK)
$bash docker/scripts/dev_into.sh(It is OK)
$bash scripts/bootstrap.sh (It is OK)
Then type http://localhost:8888 on firefox. the image like this. Could you help me solve this problem. I really spend long time in solving this problem.
<img width="861" alt="微信截图_20190401233602" src="https://user-images.githubusercontent.com/30001336/55374723-80603000-54d7-11e9-848d-014bb2bbae1c.png">

**Comment by christian-lanius** [comment]
Can you check the response of the server? I.e. right click and choose "View page source". This looks like an error I had with git-lfs not being setup correctly.

**Comment by SJHBXShub** [comment]
@christian-lanius 
hello, the response of server is ok. Could you tell me how to setup fit-lfs correctly?

**Comment by SJHBXShub** [comment]
I have solve this problem. The major problem is the firefox is not support WebGL. we can use the following link the check:
http://webglreport.com/?v=2
