### ISSUE TITLE
Conflict between Apollo RT kernel and Nvidia driver

### ISSUE THREAD

**Issue by JonathanJones92** [ApolloAuto/apollo#7598]
**Describe the bug**
The nvidia driver does not support 3D graphic acceleration while co-exist with Apollo RT Kernel.

**To Reproduce**
1. Launch Apollo 3.0 system with Lidar, camera, radar perception mode 
2. Open the Dreamview

**Expected behavior**
You will see the system become extremly slow and not respond to any action because the CPU are rendering all the graphic content instead of GPU. The 'Compiz' process eat all the CPU computation resources. 

**Screenshots**
![09993e75-c7b0-4f6e-8d27-d6031bce0579](https://user-images.githubusercontent.com/16748704/55369487-53d50400-5529-11e9-8937-c7d6db0449d8.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04.03
 - Browser:  chrome, firefox
 - Version: Apollo 3.0, Apollo 3.1.

**Additional context**
We tried to reinstall the GPU driver but and 3D acceleration（compiz） is still now running on GPU. If a different version of GPU driver are used, the Ubuntu UI will crash because the exist of Apollo RT Kernel.

**Comment by JonathanJones92** [comment]
@natashadsouza @weidezhang @bigwhite  Apollo team， Please help us to check ， thanks.

**Comment by zhangchaoltt** [comment]
hi, JonathanJones92 , please install docker according to the documentation  https://github.com/ApolloAuto/apollo/tree/master/docker/scripts#install-nvidia-docker-optional

**Comment by JonathanJones92** [comment]
> hi, JonathanJones92 , please install docker according to the documentation https://github.com/ApolloAuto/apollo/tree/master/docker/scripts#install-nvidia-docker-optional

Hi @zhangchaoltt , 
                            Thanks for your timly reply.

                             I think I did install nvidia driver inside and outside docker properly because I run 'nvidia-smi' on both sides. They all return correct GPU driver info(The same driver version info). May I ask what it will be if I install the nvidia-docker correctly? Is there any checkpoint infomation that I can find if I did all the driver stuff correctly?

                       Thank you again :) 

Jonathan

**Comment by storypku** [comment]
A late reply. We have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. 
It should work OK with Nvidia driver. 

Thank you.
