### ISSUE TITLE
Is there any signal or topic can be detected when we reach to goal

### ISSUE THREAD

**Issue by s894330** [ApolloAuto/apollo#7602]
As title, when vehicle reach the goal, is there any signal or topic can be detected?
we want to know whether the vehicle is reach the goal or not
thank you

### System information

- **Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 3.5**:

**Comment by unacao** [comment]
maybe you can check if planning->decision->main_decision->mission_complete?

**Comment by s894330** [comment]
OK, it works, thank you :-)
