### ISSUE TITLE
Some confusion on atomic values synchronization of CyberRT’s ShareMemory communication mechanism

### ISSUE THREAD

**Issue by bssung** [ApolloAuto/apollo#7624]
CyberRT uses ShareMemory to transport messages. 
In talker/listener example, talker AcquireBlockToWrite and then ReleaseWrittenBlock, listener AcquireBlockToRead and then ReleaseReadBlock. 
In my understanding ,that's a classic producer/consumer model. And it uses atomic values to synchronize, core function is compare_exchange_weak.

Talker can write the block when atmic value is 0, AcquireBlockToWrite means setting atomic value to -1, and ReleaseWrittenBlock means setting atomic value to 0.
Listener can read the block when atomic value greater than -1, AcquireBlockToRead means adding 1 to atomic value, and ReleaseReadBlock means subtracting 1 to atomic value.

So, if there are 2 listeners, the first listener add the atomic value to 1, and the second listener add the atomic value to 2, then they can read the block at the same time.

I'm confused why 2 listeners can read the block at the same time, for my understanding, 2 consumers should be mutually-exclusive.

**Comment by gruminions** [comment]
Hi bssung, thanks for your question.
When listeners read from block, they would not modify the data in block. So, CyberRT supports concurrent reading.

**Comment by bssung** [comment]
Got it，thanks @gruminions
