### ISSUE TITLE
CyberVisualizer:No data problem

### ISSUE THREAD

**Issue by lhh0916** [ApolloAuto/apollo#7656]
Hello guys!
When I started the cyber_visualizer tool, there was no data play,but in cyber_monitor.
![Screenshot from 2019-04-04 15:47:47](https://user-images.githubusercontent.com/18008528/55549342-2b573080-5708-11e9-8ded-6f3853ed8161.png)
![Screenshot from 2019-04-04 16:05:16](https://user-images.githubusercontent.com/18008528/55549350-314d1180-5708-11e9-9859-6282dec0fafb.png)

My nvidia driver is 375.39.
@in_dev_docker:/apollo/docs/demo_guide$ glxinfo -v | grep -i opengl
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)
OpenGL version string: 2.1 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL extensions:

in_dev_docker:/apollo/docs/demo_guide$ uname -a
Linux in_dev_docker 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Why is this, how can I solve it?
Should I upgrade opengl to version 3.3 or later? How to upgrade? I did not upgrade successfully.
please thank you very much.

**Comment by gruminions** [comment]
Hi, @lhh0916  can you provide the record you used?
Thank you!

**Comment by lhh0916** [comment]
@gruminions I converted "apollo_2.0_camera_sample.bag"  to "apollo_2.0_camera_sample.record" by rosbag_to_record.

**Comment by gruminions** [comment]
> @gruminions I converted "apollo_2.0_camera_sample.bag" to "apollo_2.0_camera_sample.record" by rosbag_to_record.

Sorry, I failed to find "apollo_2.0_camera_sample.bag", can you share the link?
Thank you.

**Comment by lhh0916** [comment]
> > @gruminions I converted "apollo_2.0_camera_sample.bag" to "apollo_2.0_camera_sample.record" by rosbag_to_record.
> 
> Sorry, I failed to find "apollo_2.0_camera_sample.bag", can you share the link?
> Thank you.

**Comment by lhh0916** [comment]
@gruminions  "https://github.com/ApolloAuto/apollo/releases/download/v2.0.0/apollo_2.0_camera_sample.bag"

**Comment by ZeusJupiter** [comment]
@lhh0916 you docker don't support OpenGL shading language 3.3 or higher. Please try the following:
1: download the correct nvidia graphics driver  from "https://www.nvidia.com/Download/index.aspx?lang=en-us"
2: install this driver for your host machine and reboot your machine
3: put the downloaded driver into apollo docker
4: enter into the apollo  docker container, and then install the driver for apollo docker container like this:
          " sudo bash nvidia-driver-file -a -N --ui=none --no-kernel-module". When meeting "[default: (N)o]:", press enter key. 

5: try cyber_visualizer again.

**Comment by quning78** [comment]
Closed for now, please reopen if you still have problems with it.

**Comment by lhh0916** [comment]
@ZeusJupiter 
I reinstalled the nvidia driver and solved the problem, thank you very much!

**Comment by qwetqwe** [comment]
@ZeusJupiter Do you use nvidia-docker or nvidia container toolkit？When I install NVIDIA driver in docker, there are some conflicts with host driver
