### ISSUE TITLE
strange link bazel-apollo -> /home/ubuntu/.cache/.../apollo/

### ISSUE THREAD

**Issue by wyqhnr** [ApolloAuto/apollo#767]
after finished building apollo,i found in home directory this,is this correct? can i clean ~/.cache folder?
ubuntu@u0:~/桌面/apl/apollo$ ll
总用量 260
drwxrwxr-x 11 ubuntu ubuntu   4096 10月 16 17:15 ./
drwx------  7 ubuntu ubuntu   4096 10月 18 17:17 ../
-rwxr-xr-x  1 ubuntu ubuntu   3115 10月  9 14:35 apollo_docker.sh*
-rw-rw-r--  1 ubuntu ubuntu 100469 10月  9 14:35 apollo.doxygen
-rwxr-xr-x  1 ubuntu ubuntu  18067 10月  9 14:35 apollo.sh*
-rw-rw-r--  1 ubuntu ubuntu    849 10月  9 14:35 AUTHORS.md
lrwxrwxrwx  1 ubuntu ubuntu     88 10月 10 16:26 bazel-apollo -> /home/ubuntu/.cache/bazel/_bazel_ubuntu/540135163923dd7d5820f3ee4b306b32/execroot/apollo/
lrwxrwxrwx  1 ubuntu ubuntu    112 10月 10 16:26 bazel-bin -> /home/ubuntu/.cache/bazel/_bazel_ubuntu/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/

**Comment by xiaoxq** [comment]
Yes, it's expected behavior of bazel.
We mount your ~/.cache into docker container so that even when you start a new container, bazel can find the cache and reuse compiled objects.
