### ISSUE TITLE
The argument type of Calling DenseToCSCMatrix() does not match its signature,

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#7687]
**Describe the bug**

Here is the signature for DenseToCSCMatrix() in modules/common/math/matrix_operations.h

```
template <typename T, int M, int N, typename D>
void DenseToCSCMatrix(const Eigen::Matrix<T, M, N> &dense_matrix,
                      std::vector<T> *data, std::vector<D> *indices,
                      std::vector<D> *indptr)
```
Note: the data element type for **dense_matrix** and **data** should have the same type.

In modules/planning/math/finite_element_qp/fem_1d_expanded_jerk_qp_problem.h

```
void Fem1dExpandedJerkQpProblem::CalculateAffineConstraintUsingDenseMatrix(
    std::vector<c_float>* A_data, std::vector<c_int>* A_indices,
    std::vector<c_int>* A_indptr, std::vector<c_float>* lower_bounds,
    std::vector<c_float>* upper_bounds) {
...
  MatrixXd affine_constraint = MatrixXd::Zero(kNumConstraint, kNumParam);
...
  DenseToCSCMatrix(affine_constraint, A_data, A_indices, A_indptr);
}
```

Here affine_constraint has a type of MatrixXd which means **double** for the element. However, A_data has a **float** type. So the compiler cannot create a specialized template for DenseToCSCMatrix as we expected where the template expects the same data type for dense_matrix and data.  I came across this issue during x-compilation onto qnx.

To fix, just change affine_contraint from MatrixXd int MatrixXf.

**Comment by zezhou** [comment]
maybe you can submit a pull request to fix this.
