### ISSUE TITLE
如何百度apollo搭建开发环境，和如何对百度apollo进行调试呢？？？还请帮忙

### ISSUE THREAD

**Issue by gitLongjie** [ApolloAuto/apollo#771]

**Comment by xiaoxq** [comment]
你可以阅读我们的README，尝试按照步骤把Demo先跑起来。如果遇到什么问题，可以搜索以往开发者的解决方案；如果仍然无法解决，可以继续创建issue提出，我们会在第一时间答复或修复 :)

**Comment by gitLongjie** [comment]
感谢您的回答，我已经把demo跑起来了，目前想要添加自己的代码模块，可是我目前还不会搭建开发工程，主要想学习怎么搭建开发环境，和如何对整个系统调试。编写自己的模型进行训练。谢谢

**Comment by xiaoxq** [comment]
我们使用bazel作为编译环境，你可以先学习一下它对代码的组织形式。
作为试验的话你可以将代码放在任何子路径下；
作为一个模块的话可以在modules下新建目录；
作为已有模块的补充的话应该放在该模块的目录里。
任何组织形式，都应该编写正确的BUILD file，那么bazel就可以发现并编译它。

**Comment by gitLongjie** [comment]
好的，谢谢 @xiaoxq
