### ISSUE TITLE
Build error with Apollo v3.5 due to C++ compilation rule failed

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#7710]
### System information
- **OS Platform and Distribution: Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 3.5 release**:

### Steps to reproduce the issue:
I try to build the Apollo v3.5 (release) code with the command **bash apollo.sh build_cpu** inside the Apollo container (apolloauto/apollo:dev-x86_64-20181210_1500) but the build failed with the following error. 
`ERROR: (04-07 00:54:12.132) /apollo/modules/v2x/v2x_proxy/obu_interface/grpc_interface/BUILD:23:1: C++ compilation of rule '//modules/v2x/v2x_proxy/obu_interface/grpc_interface:grpc_server' failed (Exit 1).`

Removing .cache/bazel as suggested [here](https://github.com/ApolloAuto/apollo/issues/7203) does not help.

**Comment by natashadsouza** [comment]
@hongkedavid can you give us additional details to help debug better - like which document you followed?

**Comment by mickeyouyou** [comment]
maybe you can update the code to master, and then have a try to build.

**Comment by hongkedavid** [comment]
The issue is fixed, probably due to the insufficient disk space in my setup.
