### ISSUE TITLE
dreamview is blank

### ISSUE THREAD

**Issue by luyangsiyi** [ApolloAuto/apollo#7712]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by llrraa** [comment]
try to run "git lfs fetch --all ." at the project root directory.
If still not ok, please show some more log.
reference: [](https://github.com/ApolloAuto/apollo/issues/7228)

**Comment by natashadsouza** [comment]
@luyangsiyi were you able to resolve your issue with @llrraa suggestion? If not please share a screenshot of the error message.

**Comment by natashadsouza** [comment]
Closing this issue as it is resolved. Feel free to reopen if you have additional questions. Thanks!
