### ISSUE TITLE
Running Apollo Perception 3.0 in ROS

### ISSUE THREAD

**Issue by cedricxie** [ApolloAuto/apollo#7715]
Hey guys, 

I want to share with you an awesome project I worked on using Apollo! Apollo from Baidu is a great autonomous driving platform, probably the best one that you can find that is open source. 

However, the learning curve could be steep when you first learn it. What if it can be run in normal ROS? Isn't that great?! Check out my on-going project here at https://github.com/cedricxie/apollo_perception_ros. Object detection / tracking / fusion based on Apollo 3.0 in ROS! Complete lidar / camera / radar perception pipeline. 

Let me know your thoughts/ideas on this. Hope you enjoy it and have fun!

Yuesong

**Comment by daohu527** [comment]
It would be great if ros and apollo could unify middleware. We do not currently recommend this, and suggest porting the algorithm as much as possible
