### ISSUE TITLE
Changing configuration parameters 

### ISSUE THREAD

**Issue by atomattias** [ApolloAuto/apollo#7725]
I would like to test my planing algorithm. To do so I need to feed  different configuration parameters continuously inside apollo/modules/planning/conf/. 

- My question is: How can i write in to those files

**Comment by jmtao** [comment]
@atomattias what do you mean by saying "feed different conf params CONTINUOUSLY"? Do you mean you want to update the conf again and again, on the fly? We don't really support that. Normally, the config file is loaded with initialization one time.  It would not have any effects if you update the conf files later.

**Comment by atomattias** [comment]
yes i wanted to update some parameters in apollo/modules/planning/conf/ again and again, on the fly. I would like to test my planning algorithm for different set of rules, could you please suggest?

**Comment by jmtao** [comment]
@atomattias we don't really support that.  But it depends on which conf you need update. Some conf may be loaded in every frame. If not, you can update code to do that if doable.
