### ISSUE TITLE
bash dev_start.sh failed

### ISSUE THREAD

**Issue by luyangsiyi** [ApolloAuto/apollo#7726]
I try to install Apollo3.5 on Ubuntu 16.04 on my Mac. 
When I run `bash docker/scripts/dev_start.sh`, I got the error as followed.
<img width="912" alt="屏幕快照 2019-04-08 下午7 29 55" src="https://user-images.githubusercontent.com/24309599/55721063-f531ed80-5a34-11e9-9e3f-34f07d6edc02.png">

So I tried to comment out the relevant code, and continued to build Apollo successfully. But when I run `bash scripts/bootstrap.sh` and go to localhost:8888, dreamview turned out to be blank.

How could I solve this problem?
Thanks so much!

**Comment by llrraa** [comment]
try to run "git lfs fetch --all ." at the project root directory.
If still not ok, please show some more log.

**Comment by luyangsiyi** [comment]
> try to run "git lfs fetch --all ." at the project root directory.
> If still not ok, please show some more log.

I tried to run "git lfs fetch --all" like this
![image](https://user-images.githubusercontent.com/24309599/56340683-38cee900-61e5-11e9-886e-b7b86c0d1b5e.png)

And after I built Apollo, Dreamview is still blank.
![image](https://user-images.githubusercontent.com/24309599/56340521-b6dec000-61e4-11e9-9251-8e7d4a8c2de2.png)
![image](https://user-images.githubusercontent.com/24309599/56340539-c4944580-61e4-11e9-83d9-4080e670ecc1.png)

**Comment by llrraa** [comment]
Maybe you can try http://127.0.0.1:8888

**Comment by luyangsiyi** [comment]
> Maybe you can try http://127.0.0.1:8888

It still doesn't work.

**Comment by luyangsiyi** [comment]
I finally tried to build apollo 3.0 instead of the newest version.

**Comment by natashadsouza** [comment]
@luyangsiyi unfortunately as Git LFS is not internally developed, you would need to reach out on their page to help resolve your issue. My recommendation is delete Apollo along with Git LFS and try reinstalling it one more time. Sorry we could not be of more help to you. Closing this issue currently. Feel free to reach out if you have additional questions. Thanks!
