### ISSUE TITLE
Error while Building modules inside the docker.

### ISSUE THREAD

**Issue by shifakhan4892** [ApolloAuto/apollo#7728]
Hi Apollo Developers,

I am trying to build independent modules inside the docker and I am having this error popping for most of the modules. Can anyone advise ?

![error while building](https://user-images.githubusercontent.com/16239521/55737425-c98a1580-59ea-11e9-935c-363cb762cc87.png)

Also, I am having errors related to Poco library after building the docker image. 

shifa@in_dev_docker:/apollo$ bazel build //modules/data:all
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (04-08 15:43:21.154) Found 6 targets...
ERROR: (04-08 15:43:37.356) /apollo/modules/data/BUILD:18:1: C++ compilation of rule '//modules/data:data_component_lib' failed (Exit 1).
In file included from ./cyber/class_loader/class_loader_register_macro.h:20:0,
                 from ./cyber/class_loader/class_loader.h:26,
                 from ./cyber/component/component_base.h:25,
                 from ./cyber/component/timer_component.h:22,
                 from ./modules/data/data_component.h:26,
                 from modules/data/data_component.cc:16:
./cyber/class_loader/utility/class_loader_utility.h:20:32: fatal error: Poco/SharedLibrary.h: No such file or directory
 #include <Poco/SharedLibrary.h>
                                ^
compilation terminated.
INFO: (04-08 15:43:37.402) Elapsed time: 16.864s, Critical Path: 3.65s

shifa@in_dev_docker:/apollo$ bazel build //modules/v2x:all
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (04-08 15:44:42.489) Found 1 target...
ERROR: (04-08 15:44:53.386) /apollo/modules/v2x/v2x_proxy/obu_interface/grpc_interface/BUILD:23:1: C++ compilation of rule '//modules/v2x/v2x_proxy/obu_interface/grpc_interface:grpc_server' failed (Exit 1).
In file included from ./cyber/class_loader/class_loader_register_macro.h:20:0,
                 from ./cyber/class_loader/class_loader.h:26,
                 from ./cyber/component/component_base.h:25,
                 from ./cyber/component/component.h:29,
                 from ./cyber/cyber.h:25,
                 from ./modules/v2x/v2x_proxy/obu_interface/grpc_interface/grpc_server.h:26,
                 from modules/v2x/v2x_proxy/obu_interface/grpc_interface/grpc_server.cc:22:
./cyber/class_loader/utility/class_loader_utility.h:20:32: fatal error: Poco/SharedLibrary.h: No such file or directory
 #include <Poco/SharedLibrary.h>
                                ^
compilation terminated.
Target //modules/v2x:v2x failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: (04-08 15:44:53.434) Elapsed time: 12.112s, Critical Path: 10.27s

**Comment by natashadsouza** [comment]
You could check @aboarya suggestion in #6771 and let us know if it helps! Thanks.

**Comment by natashadsouza** [comment]
Closing this issue as we have not received a response and assume you were able to resolve the issue. Feel free to reopen if you have additional questions. Thanks!
