### ISSUE TITLE
publishing messages to cyberRT channels on a remote machine 

### ISSUE THREAD

**Issue by ak201790** [ApolloAuto/apollo#7742]
Is it possible with the Cyber framework to run CyberRT on two machines and have talker and listener node on these two separate machines? How can this be achieved?

E.g. In ROS, this can be achieved by changing the ROS_MASTER_URI. Is there something similar in Cyber?

**Comment by gruminions** [comment]
@ak201790 Hi, maybe you can follow @fengqikai1414 's answer in this issue: https://github.com/ApolloAuto/apollo/issues/7050

> Hi @Tony301X
> You just need to modify line 20 of `/apollo/cyber/setup.bash`
> 
> ```shell
> export CYBER_IP=127.0.0.1
> ```
> 
> Suppose you have two hosts A and B，the ip of A is `192.168.10.6`, and the ip of B is `192.168.10.7`. Then set `CYBER_IP` to `192.168.10.6` on host A, and set `CYBER_IP` to `192.168.10.7` on host B. Now host A can communicate with host B.

**Comment by gruminions** [comment]
Currently closing this issue. @ak201790 if you have any additional questions, feel free to reopen it!

**Comment by Jiangkui12** [comment]
您好，在同一个物理主机上，两个docker镜像之间如何通过CyberRT通信?
