### ISSUE TITLE
ubuntu1604 下运行 examples下的 talker/listener 程序，节点无法收到对方消息

### ISSUE THREAD

**Issue by luozhaohui** [ApolloAuto/apollo#7749]
**问题**
ubuntu1604 下运行 examples 下的 talker/listener 程序，listener 节点无法收到 talker  发送的消息。两者的日志中都出现如下信息：
"manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met."

**环境**
ubuntu1604 下非 docker 环境

**日志**
talker 日志内容：
```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0409 20:29:33.547168 25340 environment.h:33]  Environment variable [CYBER_PATH] not set, fallback to 
W0409 20:29:33.547222 25340 scheduler_factory.cc:67]  Pls make sure schedconf exist and which format is correct.
W0409 20:29:33.547243 25340 environment.h:33]  Environment variable [CYBER_PATH] not set, fallback to 
I0409 20:29:33.547345 25342 processor.cc:81]  processor_tid: 25342
I0409 20:29:33.547379 25343 processor.cc:81]  processor_tid: 25343
I0409 20:29:33.547686 25345 processor.cc:81]  processor_tid: 25345
I0409 20:29:33.548516 25344 processor.cc:81]  processor_tid: 25344
I0409 20:29:33.548517 25346 processor.cc:81]  processor_tid: 25346
I0409 20:29:33.548683 25347 processor.cc:81]  processor_tid: 25347
I0409 20:29:33.548889 25348 processor.cc:81]  processor_tid: 25348
I0409 20:29:33.548990 25350 processor.cc:81]  processor_tid: 25350
I0409 20:29:33.549054 25351 processor.cc:81]  processor_tid: 25351
I0409 20:29:33.549118 25349 processor.cc:81]  processor_tid: 25349
I0409 20:29:33.549369 25353 processor.cc:81]  processor_tid: 25353
I0409 20:29:33.549502 25352 processor.cc:81]  processor_tid: 25352
I0409 20:29:33.549628 25354 processor.cc:81]  processor_tid: 25354
I0409 20:29:33.549743 25355 processor.cc:81]  processor_tid: 25355
I0409 20:29:33.549778 25356 processor.cc:81]  processor_tid: 25356
I0409 20:29:33.549801 25340 init.cc:104]  Register exit handle succ.
I0409 20:29:33.549818 25357 processor.cc:81]  processor_tid: 25357
W0409 20:29:33.555671 25340 environment.h:33]  Environment variable [cyber_trans_perf] not set, fallback to 
W0409 20:29:33.555693 25340 environment.h:33]  Environment variable [cyber_sched_perf] not set, fallback to 
I0409 20:29:33.555703 25340 talker.cc:48]  talker sent a message!
W0409 20:29:33.556064 25362 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
I0409 20:29:34.556705 25340 talker.cc:48]  talker sent a message!
I0409 20:29:35.555857 25340 talker.cc:48]  talker sent a message!
I0409 20:29:36.555917 25340 talker.cc:48]  talker sent a message!
I0409 20:29:37.556257 25340 talker.cc:48]  talker sent a message!
I0409 20:29:38.555981 25340 talker.cc:48]  talker sent a message!
I0409 20:29:39.556118 25340 talker.cc:48]  talker sent a message!
W0409 20:29:39.720752 25362 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
I0409 20:29:40.557258 25340 talker.cc:48]  talker sent a message!
I0409 20:29:41.556228 25340 talker.cc:48]  talker sent a message!
I0409 20:29:42.559804 25340 talker.cc:48]  talker sent a message!
I0409 20:29:43.557693 25340 talker.cc:48]  talker sent a message!
I0409 20:29:44.556190 25340 talker.cc:48]  talker sent a message!
I0409 20:29:45.559264 25340 talker.cc:48]  talker sent a message!
I0409 20:29:46.556226 25340 talker.cc:48]  talker sent a message!
I0409 20:29:47.556109 25340 talker.cc:48]  talker sent a message!
W0409 20:29:48.532344 25362 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
```

listener 日志内容：
```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0409 20:29:39.481803 25384 environment.h:33]  Environment variable [CYBER_PATH] not set, fallback to 
W0409 20:29:39.481834 25384 scheduler_factory.cc:67]  Pls make sure schedconf exist and which format is correct.
W0409 20:29:39.481900 25384 environment.h:33]  Environment variable [CYBER_PATH] not set, fallback to 
I0409 20:29:39.482599 25386 processor.cc:81]  processor_tid: 25386
I0409 20:29:39.482925 25387 processor.cc:81]  processor_tid: 25387
I0409 20:29:39.483857 25388 processor.cc:81]  processor_tid: 25388
I0409 20:29:39.483985 25390 processor.cc:81]  processor_tid: 25390
I0409 20:29:39.484417 25392 processor.cc:81]  processor_tid: 25392
I0409 20:29:39.484982 25393 processor.cc:81]  processor_tid: 25393
I0409 20:29:39.484794 25391 processor.cc:81]  processor_tid: 25391
I0409 20:29:39.485086 25389 processor.cc:81]  processor_tid: 25389
I0409 20:29:39.485682 25394 processor.cc:81]  processor_tid: 25394
I0409 20:29:39.485683 25395 processor.cc:81]  processor_tid: 25395
I0409 20:29:39.486275 25396 processor.cc:81]  processor_tid: 25396
I0409 20:29:39.486382 25397 processor.cc:81]  processor_tid: 25397
I0409 20:29:39.486706 25400 processor.cc:81]  processor_tid: 25400
I0409 20:29:39.486632 25384 init.cc:104]  Register exit handle succ.
I0409 20:29:39.486457 25398 processor.cc:81]  processor_tid: 25398
I0409 20:29:39.486831 25401 processor.cc:81]  processor_tid: 25401
I0409 20:29:39.486981 25399 processor.cc:81]  processor_tid: 25399
I0409 20:29:39.497285 25384 scheduler.cc:55]  create croutine: listener_channel/chatter
W0409 20:29:39.497339 25384 environment.h:33]  Environment variable [cyber_trans_perf] not set, fallback to 
W0409 20:29:39.497370 25384 environment.h:33]  Environment variable [cyber_sched_perf] not set, fallback to 
W0409 20:29:39.499263 25406 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
W0409 20:29:39.720604 25406 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
W0409 20:29:48.532429 25406 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
W0409 20:29:50.356101 25406 manager.cc:192]  !message::ParseFromString(msg_str, &msg) is not met.
```

**Comment by luozhaohui** [comment]
将 manager.cc 中的 OnRemoteChange 替换为如下代码，可以正常收发消息。

```
void Manager::OnRemoteChange(const std::string& msg_str) {
  if (is_shutdown_.load()) {
    ADEBUG << "the manager has been shut down.";
    return;
  }

  ChangeMsg msg;
  // RETURN_IF(!message::ParseFromString(msg_str, &msg));
  if (message::HasParseFromString<ChangeMsg>::value) {
    msg.ParseFromString(msg_str);
  }
  else {
    AWARN << "HasParseFromString<ChangeMsg> is not met.";
    return;
  }

  if (IsFromSameProcess(msg)) {
    return;
  }
  RETURN_IF(!Check(msg.role_attr()));
  Dispose(msg);
}
```

**Comment by gruminions** [comment]
> 将 manager.cc 中的 OnRemoteChange 替换为如下代码，可以正常收发消息。
> 
> ```
> void Manager::OnRemoteChange(const std::string& msg_str) {
>   if (is_shutdown_.load()) {
>     ADEBUG << "the manager has been shut down.";
>     return;
>   }
> 
>   ChangeMsg msg;
>   // RETURN_IF(!message::ParseFromString(msg_str, &msg));
>   if (message::HasParseFromString<ChangeMsg>::value) {
>     msg.ParseFromString(msg_str);
>   }
>   else {
>     AWARN << "HasParseFromString<ChangeMsg> is not met.";
>     return;
>   }
> 
>   if (IsFromSameProcess(msg)) {
>     return;
>   }
>   RETURN_IF(!Check(msg.role_attr()));
>   Dispose(msg);
> }
> ```

Hi zhaohui, thanks for your contributions!
However, it seems that there is no change in logic.
https://github.com/ApolloAuto/apollo/blob/master/cyber/message/message_traits.h#L157

Thank you again!

**Comment by chouer19** [comment]
> 将 manager.cc 中的 OnRemoteChange 替换为如下代码，可以正常收发消息。
> 
> ```
> void Manager::OnRemoteChange(const std::string& msg_str) {
>   if (is_shutdown_.load()) {
>     ADEBUG << "the manager has been shut down.";
>     return;
>   }
> 
>   ChangeMsg msg;
>   // RETURN_IF(!message::ParseFromString(msg_str, &msg));
>   if (message::HasParseFromString<ChangeMsg>::value) {
>     msg.ParseFromString(msg_str);
>   }
>   else {
>     AWARN << "HasParseFromString<ChangeMsg> is not met.";
>     return;
>   }
> 
>   if (IsFromSameProcess(msg)) {
>     return;
>   }
>   RETURN_IF(!Check(msg.role_attr()));
>   Dispose(msg);
> }
> ```

嗨，罗大神，我也是不在docker上编译运行apollo的cyberRT架构，同样在测试talker和listener的时候遇到了，listner无法接收到消息，而且cyber_chanel工具echo也没有东西。
按照你这一段代码修改一下manager.cc文件就奏效了。

然而疑惑的是，我在百度提供的docker环境里却不需要改这个源码文件，所以我想是哪里出了问题？是proto版本不同？
改这样代码，与原来不同的应该就是proto的Message运行ParseFromString函数的时候，若返回false意味着什么，要不要丢掉。
我看有人解释说，ParseFromString有的版本无返回值？如果这样那就必须改成你的这个答案。我去试试

**Comment by minhanghuang** [comment]
我从Apollo中将Cyber剥离出来单独运行时,也遇到了相同的问题,使用@[zhongjunni](https://github.com/zhongjunni)提供的方法能解决,但是根本的原因是因为我在编译`fastrtps 1.5.0`时,没有将Apollo 提供的patch文件打入`fastrtps 1.5.0`, 因此, 我只要将补丁文件打入`fastrtps`后,重新编译, 不需要修改`manager.cc`,   talker/listener能正常运行

**Comment by shelman-zl** [comment]
> 我从Apollo中将Cyber剥离出来单独运行时,也遇到了相同的问题,使用@[zhongjunni](https://github.com/zhongjunni)提供的方法能解决,但是根本的原因是因为我在编译`fastrtps 1.5.0`时,没有将Apollo 提供的patch文件打入`fastrtps 1.5.0`, 因此, 我只要将补丁文件打入`fastrtps`后,重新编译, 不需要修改`manager.cc`, talker/listener能正常运行

你好，我咨询一下，这个怎么把这个补丁打入fastrtps 1.5.0中，谢谢？

**Comment by cherishTMYY** [comment]
> 我从Apollo中将Cyber剥离出来单独运行时,也遇到了相同的问题,使用@[zhongjunni](https://github.com/zhongjunni)提供的方法能解决,但是根本的原因是因为我在编译`fastrtps 1.5.0`时,没有将Apollo 提供的patch文件打入`fastrtps 1.5.0`, 因此, 我只要将补丁文件打入`fastrtps`后,重新编译, 不需要修改`manager.cc`, talker/listener能正常运行

您好，想请教您说的这个是怎么操作阿？请问有教程吗？

**Comment by daohu527** [comment]
The patch is here
https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/FastRTPS_1.5.0.patch

## install pathed fastrtps
#### 1. The easiest way is to use apollo prebuild fastrtps directly, support both x86 and arm
https://github.com/ApolloAuto/apollo/blob/446c9c6d481fef9853ab9f167a0e934092058244/docker/build/installers/install_fast-rtps.sh#L64-L83


#### 2. or you can build fastrtps youself, First download the code and apply the patch
https://github.com/ApolloAuto/apollo/blob/446c9c6d481fef9853ab9f167a0e934092058244/docker/build/installers/install_fast-rtps.sh#L46-L62

**Comment by cherishTMYY** [comment]
> gle-branch --branch release/1.5.0 --depth 1 ht

Okay, thank you very much for your reply

**Comment by minhanghuang** [comment]
> > 我从Apollo中将Cyber剥离出来单独运行时,也遇到了相同的问题,使用@[zhongjunni](https://github.com/zhongjunni)提供的方法能解决,但是根本的原因是因为我在编译`fastrtps 1.5.0`时,没有将Apollo 提供的patch文件打入`fastrtps 1.5.0`, 因此, 我只要将补丁文件打入`fastrtps`后,重新编译, 不需要修改`manager.cc`, talker/listener能正常运行
> 
> 您好，想请教您说的这个是怎么操作阿？请问有教程吗？

- 打补丁

```
cd Fast-RTPS
patch -p1 < FastRTPS_1.5.0.patch
```
补丁文件在这里: https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/FastRTPS_1.5.0.patch

- 修改

编译过程可能会报错, 在报错的文件头部加上`#include <functional>`, 重新编译

**Comment by cherishTMYY** [comment]
> > > 我从Apollo中将Cyber剥离出来单独运行时,也遇到了相同的问题,使用@[zhongjunni](https://github.com/zhongjunni)提供的方法能解决,但是根本的原因是因为我在编译`fastrtps 1.5.0`时,没有将Apollo 提供的patch文件打入`fastrtps 1.5.0`, 因此, 我只要将补丁文件打入`fastrtps`后,重新编译, 不需要修改`manager.cc`, talker/listener能正常运行
> > 
> > 
> > 您好，想请教您说的这个是怎么操作阿？请问有教程吗？
> 
>     * 打补丁
> 
> 
> ```
> cd Fast-RTPS
> patch -p1 < FastRTPS_1.5.0.patch
> ```
> 
> 补丁文件在这里: https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/FastRTPS_1.5.0.patch
> 
>     * 修改
> 
> 
> 编译过程可能会报错, 在报错的文件头部加上`#include <functional>`, 重新编译

恩，感谢您的答复，已经成功处理patch问题

**Comment by shelman-zl** [comment]
thanks
