### ISSUE TITLE
How can we build Apollo project without docker？

### ISSUE THREAD

**Issue by JSnobody** [ApolloAuto/apollo#7750]

**Comment by gengqx** [comment]
It is recommend to run inside docker,it would have very little Impact on Performance. if you really need to run without docker,you can reference to docker/build/ folder install all dependencies and modify some scripts to run it .currently it is not support by the apollo team.

**Comment by natashadsouza** [comment]
@JSnobody we do not support building Apollo outside the docker environment. Is there a reason why you were attempting to build it without using docker?

**Comment by JSnobody** [comment]
Hi, both, I got it. Thank you very much! You can close the issue.
