### ISSUE TITLE
How to test canbus module with ESD CAN card

### ISSUE THREAD

**Issue by ak201790** [ApolloAuto/apollo#7757]
When I run `cyber_launch start modules/canbus/launch/canbus.launch` I get following error:
![image](https://user-images.githubusercontent.com/36643158/55835498-28c25580-5ad1-11e9-931e-6ca91961dbbb.png)

Running `ls /dev/can*` shows the can devices.
Also `lspci -tv` shows ESD card - `+-1b.0-[02]----00.0  ESD Electronic System Design GmbH Device 0402`

How can I test if the can drivers are working for Apollo?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 14.04.3
- **Apollo installed from (source or binary)**: Docker
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

**Comment by gengqx** [comment]
you should install a esdcan-pcie402 driver and add a library in third_party/can_card_library. Most time,it would work.

**Comment by esd-apollo** [comment]
Regarding your question how you could verify that the esd can drivers are working properly, we would propose the following steps:

a. Confirm that the kernel module is loaded, use
`lsmod | grep esdcan`

The loaded module esdcan_pcie402 should show up like this:
```
user@host:~$ lsmod | grep esdcan
esdcan_pcie402        106496  0

```
b. Check that the device nodes /dev/can* are present. Please add the output of
“ls –l /dev/can*” 
to your next report. It should look like this:

```
user@host:~$ ls -l /dev/can*
crw-rw-rw- 1 root root 52, 0 Apr 16 13:01 /dev/can0
crw-rw-rw- 1 root root 52, 1 Apr 16 13:01 /dev/can1

```
c. If the device nodes are present, please use the cantest tool which is provided here:
https://github.com/ApolloAuto/apollo-contrib/tree/master/esd/bin64
to display what can interfaces are seen by an application that uses the libntcan library.
 
The output of “cantest -2” should look like this:
```
user@host:~$ cantest -2
CAN Test Rev 3.0.7  -- (c) 1997 - 2018 esd electronics gmbh

Available CAN-Devices:
Net   0: ID=CAN_PCIE402 (2 ports) Serial no.: GA000128
         Versions (hex): Lib=4.1.04 Drv=3.A.07 HW=1.0.16 FW=0.0.47 (0.0.00)
         Baudrate=7fffffff (Not set) Status=0000 Features=00000ffa
         Ctrl=esd Advanced CAN Core @ 80 MHz (Error Active / REC:0 / TEC:0)
         Transceiver=TI SN65HVD251
         TimestampFreq=80.000000 MHz Timestamp=000000B9F97F00F6
Net   1: ID=CAN_PCIE402 (2 ports) Serial no.: GA000128
         Versions (hex): Lib=4.1.04 Drv=3.A.07 HW=1.0.16 FW=0.0.47 (0.0.00)
         Baudrate=7fffffff (Not set) Status=0000 Features=00000ffa
         Ctrl=esd Advanced CAN Core @ 80 MHz (Error Active / REC:0 / TEC:0)
         Transceiver=TI SN65HVD251
         TimestampFreq=80.000000 MHz Timestamp=000000B9F97F1AE6
```

As you can see here the CAN networks 0 and 1 are available.

Hopefully this helps.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have any additional questions. Thanks!

**Comment by phs4530** [comment]
A build error occurs.
Should version esd_candriver 4.2.2 not be used?

root@in_dev_docker:/apollo/third_party/can_card_library/esd_can/bin# lsmod | grep esdcan
esdcan_pcie402        110592  0
root@in_dev_docker:/apollo/third_party/can_card_library/esd_can/bin# ls -l /dev/can*
crw-rw-rw- 1 root root 52, 0 Jul  6 08:43 /dev/can0
crw-rw-rw- 1 root root 52, 1 Jul  6 08:43 /dev/can1
crw-rw-rw- 1 root root 52, 2 Jul  6 08:43 /dev/can2
crw-rw-rw- 1 root root 52, 3 Jul  6 08:43 /dev/can3

in docker:
root@in_dev_docker:/apollo/third_party/can_card_library/esd_can/bin# ./cantest -2 
./cantest: error while loading shared libraries: libntcan.so.4: cannot open shared object file: No such file or directory

out docker:
springcloud@springcloud-Nuvo-8108GC-Series:~/Downloads/esdcan-pcie402-linux-x86_64-4.0.1/bin64$ ./cantest -2
CAN Test FD Rev 3.0.10  -- (c) 1997 - 2018 esd electronics gmbh

Available CAN-Devices: 
Net   0: ID=CAN_PCIE402 (4 ports) Serial no.: GP002216
         Versions (hex): Lib=4.2.02 Drv=4.0.01 HW=1.0.16 FW=0.0.47 (0.0.00)
         Baudrate=7fffffff (Not set) Status=0000 Features=00000ffa
         Ctrl=esd Advanced CAN Core @ 80 MHz (Error Active / REC:0 / TEC:0)
         Transceiver=TI SN65HVD265
         TimestampFreq=80.000000 MHz Timestamp=000000605525B582
Net   1: ID=CAN_PCIE402 (4 ports) Serial no.: GP002216
         Versions (hex): Lib=4.2.02 Drv=4.0.01 HW=1.0.16 FW=0.0.47 (0.0.00)
         Baudrate=7fffffff (Not set) Status=0000 Features=00000ffa
         Ctrl=esd Advanced CAN Core @ 80 MHz (Error Active / REC:0 / TEC:0)
         Transceiver=TI SN65HVD265
         TimestampFreq=80.000000 MHz Timestamp=000000605525D422
Net   2: ID=CAN_PCIE402 (4 ports) Serial no.: GP002216
         Versions (hex): Lib=4.2.02 Drv=4.0.01 HW=1.0.16 FW=0.0.47 (0.0.00)
         Baudrate=7fffffff (Not set) Status=0000 Features=00000ffa
         Ctrl=esd Advanced CAN Core @ 80 MHz (Error Active / REC:0 / TEC:0)
         Transceiver=TI SN65HVD265
         TimestampFreq=80.000000 MHz Timestamp=000000605525EDC2
Net   3: ID=CAN_PCIE402 (4 ports) Serial no.: GP002216
         Versions (hex): Lib=4.2.02 Drv=4.0.01 HW=1.0.16 FW=0.0.47 (0.0.00)
         Baudrate=7fffffff (Not set) Status=0000 Features=00000ffa
         Ctrl=esd Advanced CAN Core @ 80 MHz (Error Active / REC:0 / TEC:0)
         Transceiver=TI SN65HVD265
         TimestampFreq=80.000000 MHz Timestamp=00000060552609E2

I add all the files in third_party.
root@in_dev_docker:/apollo/third_party/can_card_library/esd_can# ls
BUILD  README.md  bin  include  lib
