### ISSUE TITLE
DROPPED_RTPSPARTICIPANT error while building modules. How to FastRTPS_1.4.0.patch ?

### ISSUE THREAD

**Issue by shifakhan4892** [ApolloAuto/apollo#7778]
Hi Apollo platform developers,
I wanted to know how to apply the patch "FastRTPS_1.4.0.patch", I couldn't find any documentation on how to do that. I am working inside the docker and encountering the following errors. I think applying the patch will solve the issue.

shifa@in_dev_docker:/apollo$ bazel build //modules/routing:all
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (04-10 14:22:20.458) Found 6 targets...
ERROR: (04-10 14:22:31.558) /apollo/cyber/service_discovery/BUILD:5:1: C++ compilation of rule '//cyber/service_discovery:topology_manager' failed (Exit 1).
cyber/service_discovery/topology_manager.cc: In member function 'bool apollo::cyber::service_discovery::TopologyManager::Convert(const PartInfo&, apollo::cyber::proto::ChangeMsg*)':
cyber/service_discovery/topology_manager.cc:152:10: error: 'DROPPED_RTPSPARTICIPANT' is not a member of 'eprosima::fastrtps::rtps::DISCOVERY_STATUS'
case eprosima::fastrtps::rtps::DISCOVERY_STATUS::DROPPED_RTPSPARTICIPANT:
^
INFO: (04-10 14:22:31.604) Elapsed time: 12.172s, Critical Path: 5.79s

Might be a silly question. Can someone please help me ?

**Comment by gruminions** [comment]
Hi, maybe you can follow @Eclipsehelio 's answer in this issue: https://github.com/ApolloAuto/apollo/issues/7240

**Comment by shifakhan4892** [comment]
Hi @gruminions, 
I tried doing what @Eclipsehelio suggested, but I am encountering another error now and still facing the same error building in some other modules.

shifa@in_dev_docker:/apollo$ bazel build //modules/guardian:all
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (04-11 17:33:54.404) Found 2 targets...
ERROR: (04-11 17:33:54.572) /apollo/cyber/BUILD:67:1: Linking of rule '//cyber:cyber_core' failed (Exit 1).
/usr/bin/ld: //usr/local/lib/libglog.a(libglog_la-logging.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libglog.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
INFO: (04-11 17:33:54.606) Elapsed time: 0.642s, Critical Path: 0.04s
================================================================================

shifa@in_dev_docker:/apollo$ bazel build //modules/data:all
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
INFO: (04-11 16:42:33.229) Found 6 targets...
ERROR: (04-11 16:42:38.559) /apollo/cyber/service_discovery/BUILD:5:1: C++ compilation of rule '//cyber/service_discovery:topology_manager' failed (Exit 1).
cyber/service_discovery/topology_manager.cc: In member function 'bool apollo::cyber::service_discovery::TopologyManager::Convert(const PartInfo&, apollo::cyber::proto::ChangeMsg*)':
cyber/service_discovery/topology_manager.cc:152:10: error: 'DROPPED_RTPSPARTICIPANT' is not a member of 'eprosima::fastrtps::rtps::DISCOVERY_STATUS'
     case eprosima::fastrtps::rtps::DISCOVERY_STATUS::DROPPED_RTPSPARTICIPANT:
          ^
INFO: (04-11 16:42:38.612) Elapsed time: 6.070s, Critical Path: 4.60s

Anyone has any idea of what should be done ? 
Thanks.

**Comment by natashadsouza** [comment]
@shifakhan4892 were you able to build Apollo normally? Is it only this patch that is causing a build failure?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
