### ISSUE TITLE
 computation in component is much lower

### ISSUE THREAD

**Issue by jeff-zhang123** [ApolloAuto/apollo#7795]
We are facing a problem that, computation is much lower if executed in a CyberRT component. 

We just write an image undistortion program using opencv (cpu mode) in docker. The computation takes less than 10ms only. However, when translating to a component, the undistortion process takes more than 100ms. We put the computation in the Proc function of the component, and use another component to send message only. Then, we config the scheduler of this component, results not change. Only the mentioned two components are launched in docker.  

Addition, we change the processor_num in the scheduler_conf file, but changes not occure.

So, what's the problem?  and why the scheduler conf is not work?

**Comment by zhangchaoltt** [comment]
I think maybe these are two problems. First，the conf file corresponds to the process name, the scheduler conf is not work, I guess it may not be the conf file for your process. If the processor does not have the corresponds conf,  it will use the default_proc_num in cyber.pb.conf, normally there's nothing wrong here. Then,  can you show the detail of your case ? Otherwise, it's not good to locate the problem

**Comment by jeff-zhang123** [comment]
@zhangchaoltt   Thanks. The test codes are as follows:

TestComponent.cc  [dir: apollo/modules/test/]
bool TestComponent::Proc(const std::shared_ptr<TriggerCompMsg>& msg){
  double start_time = cyber::Time::Now().ToSecond();
  undistort_one_image();
  std::cout << "diff time: " << cyber::Time::Now().ToSecond() - start_time<< std::endl;
  return true;
}

dag file    [dir: apollo/modules/test/]
module_config {
    module_library : "/apollo/bazel-bin/modules/test/libtest_component.so"
    components {
     class_name : "TestComponent"
      config {
        name : "undist_img"
        readers {
          channel: "/apollo/test"
        }
      }
    }
}

launch file    [dir: apollo/modules/test/]
<cyber>
    <module>
        <name>test</name>
        <dag_conf>/apollo/modules/test/test.dag</dag_conf>
        <process_name>test_undist</process_name>
    </module>
</cyber>

scheduler conf file  [dir: apollo/cyber/conf/test_undist.conf]
scheduler_conf {
  policy: "classic"
  classic_conf {
    groups: [
      {
        name: "undistortion_test"
        processor_num: 8
        affinity: "range"
        cpuset: "0-7"
        processor_policy: "SCHED_OTHER"
        processor_prio: 0
        tasks: [
          {
            name: "undist_img"
            prio: 0
          }
        ]
      }
    ]
  }
}

**Comment by zhangchaoltt** [comment]
You can use cyber::Time::Now().ToNanosecond() instead of  cyber::Time::Now().ToSecond()  to calculate time-consuming

**Comment by jeff-zhang123** [comment]
> You can use cyber::Time::Now().ToNanosecond() instead of cyber::Time::Now().ToSecond() to calculate time-consuming

sorry, it doesn't work for me. Time consuming is the same as using cyber::Time::Now().ToSecond().

In addition, I modify the routine_num and default_proc_num in the cyber.pb.conf, but time consuming does not change also.

**Comment by jeff-zhang123** [comment]
sorry, it doesn't work for me. Time consuming is the same as using cyber::Time::Now().ToSecond().

In addition, I modify the routine_num and default_proc_num in the cyber.pb.conf, but time consuming does not change also.

**Comment by zhangchaoltt** [comment]
@jeff-zhang123 Try this command `bazel build -c opt --copt=-fpic //cyber/...`  to build CyberRT,  which mean enable compiler optimization with level 2, as same as -O2. then test your case.

**Comment by jeff-zhang123** [comment]
@zhangchaoltt   I update cyberRT to the latest version, and build cyber using your command. it's ok now, I change the routine_num from 100 to 10, and cyber_launch my test component, time consuming reaches 7ms. Thanks for your reply.
