### ISSUE TITLE
localization volume has no v1.0.3 version but lastest has update to 1.0.3

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#7796]
the localization volume has an image :
localization_volume-x86_64-v1.0.1
localization_volume-x86_64-v1.0.2
localization_volume-x86_64-latest

the lastet msf library has update to a version of liblocalization_msf.so.1.0.3
but the volume does not ,and the 1.0.3 code could not capable with 1.0.2 version.
it is not convenient, could you add a docker image with tag:
 localization_volume-x86_64-v1.0.3
the content is same with localization_volume-x86_64-latest

@xiaoxq

**Comment by xiaoxq** [comment]
Sure. I'll take a look tmr.

**Comment by xiaoxq** [comment]
Done. Thanks for the great suggestion!
