### ISSUE TITLE
Relative Map in Apollo 3.5

### ISSUE THREAD

**Issue by tpengchang** [ApolloAuto/apollo#7826]
There are three relative map mode in apollo 2.5: 
 Mode 1: perception
 Mode 2: navigator + perception
 Mode 3: HDMap + navigator + perception.

Does apollo 3.5 also support these modes?

![2019-04-12_110051](https://user-images.githubusercontent.com/24878142/56009496-85f91980-5d12-11e9-8df7-1a5526e5e92d.jpg)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5 (main branch)

**Comment by yifeijiang** [comment]
Those modes are not supported in 3.5 yet.

**Comment by natashadsouza** [comment]
Currently closing this issue.
@tpengchang we will let you know if our development decisions change in the future.
Thank you for supporting the Apollo platform.
