### ISSUE TITLE
Cannot start auto

### ISSUE THREAD

**Issue by pengpingliang** [ApolloAuto/apollo#7829]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:14.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
     All the modules were started with no errors in Navigation Mode.Push the StartAuto button,the system cannot change the driving mode to "start auto". 

### Supporting materials (screenshots, command lines, code/script snippets):

-  I have tried to debug the problem, and found the pad_msg is always nullptr as the following the code!

 control_component.cc

 pad_msg_reader_->Observe();
  const auto &pad_msg = pad_msg_reader_->GetLatestObserved();
  if (pad_msg != nullptr) {  // fail: pad_msg  is nullptr
    OnPad(pad_msg);
  }

- But "/apollo/control/pad" the Message can be shown in the terminal by Cyber_monitor.

- The control module can receive localization message !

**Comment by ycool** [comment]
You can trigger auto mode by either from dreamview or https://github.com/ApolloAuto/apollo/blob/master/scripts/pad.sh.
