### ISSUE TITLE
E0412  Check section type failed; Read header section fail;Open record file failed

### ISSUE THREAD

**Issue by 18500864609** [ApolloAuto/apollo#7831]
when I type the commond :cyber_recorder play -f data/20190409_static.record --loop 
mistake like this picture,
![Screenshot from 2019-04-12 15-36-07](https://user-images.githubusercontent.com/35217567/56020285-5dd0e100-5d39-11e9-8055-406d8bd300c0.png)
I pull apollo 3.5 and can play the "cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop'' successfully! but when I want to play the record that I recoreded ,it failed.who can tell me why and tell me how to solve this problem……

**Comment by gruminions** [comment]
> when I type the commond :cyber_recorder play -f data/20190409_static.record --loop
> mistake like this picture,
> ![Screenshot from 2019-04-12 15-36-07](https://user-images.githubusercontent.com/35217567/56020285-5dd0e100-5d39-11e9-8055-406d8bd300c0.png)
> I pull apollo 3.5 and can play the "cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop'' successfully! but when I want to play the record that I recoreded ,it failed.who can tell me why and tell me how to solve this problem……

Hi @18500864609 , maybe your record file 20190409_static.record is incomplete.
I guess when you quit recording, you killed the recording process directly.

**Comment by 18500864609** [comment]
the record can play in the caros which is made by baidu developer， but when I copy it to my computer with ubuntu 16.04 in apollo 3.5 and play ,it falied. so?

**Comment by gruminions** [comment]
> the record can play in the caros which is made by baidu developer， but when I copy it to my computer with ubuntu 16.04 in apollo 3.5 and play ,it falied. so?

You meet another problem?

**Comment by 18500864609** [comment]
肯定有问题呀，这个包只能在录制包的工控机上跑，那是个纯server界面，没法开发，我把包放到自己的电脑上，放不了，报了上面的错误，包打不开，没法订阅topic，没有数据怎么开发呢？而且工控机的系统和apollo3.5 还不一样，我的电脑和工控机在一个网段下，也没法用cyber_monitor 获取工控机上放的包的channel，这可咋整啊……

**Comment by gruminions** [comment]
> 肯定有问题呀，这个包只能在录制包的工控机上跑，那是个纯server界面，没法开发，我把包放到自己的电脑上，放不了，报了上面的错误，包打不开，没法订阅topic，没有数据怎么开发呢？而且工控机的系统和apollo3.5 还不一样，我的电脑和工控机在一个网段下，也没法用cyber_monitor 获取工控机上放的包的channel，这可咋整啊……

我觉得你得先确认下你录的这个包 20190409_static.record 有没有问题。
在你机器上cyber_recorder info 20190409_static.record 显示什么？

**Comment by 18500864609** [comment]
这个包在一台装了caros工控机上是能跑的，在我的机器上info的话，提示如下：
![Screenshot from 2019-04-12 17-23-44](https://user-images.githubusercontent.com/35217567/56027048-f0787c80-5d47-11e9-9c21-147011d353c7.png)

**Comment by gruminions** [comment]
方便共享一下这个record文件吗，我下载下来看一下

**Comment by 18500864609** [comment]
你好，录制的文件比较大，所以共享到百度网盘里了，麻烦您下载一下，400多M
链接：https://pan.baidu.com/s/1tg0FP-Qzv7CWiZ-p4AN9bg 
提取码：d535 
多谢！

**Comment by gruminions** [comment]
> 你好，录制的文件比较大，所以共享到百度网盘里了，麻烦您下载一下，400多M
> 链接：https://pan.baidu.com/s/1tg0FP-Qzv7CWiZ-p4AN9bg
> 提取码：d535
> 多谢！

我的机器上也打不开，显示的信息跟你的一样。

你可以在工控机上播放record，然后在你的机器上接收消息。
可以按照fengqikai1414在这个issue：https://github.com/ApolloAuto/apollo/issues/7050 里的回答，设置一下CYBER_IP，更新环境变量后，再运行

**Comment by gruminions** [comment]
Currently closing this issue. @18500864609 if you have any additional questions, feel free to reopen it!
