### ISSUE TITLE
Apollo Data Open Platform access not possible

### ISSUE THREAD

**Issue by christian-lanius** [ApolloAuto/apollo#7837]
Trying to access the data linked in various places at http://data.apollo.auto/?locale=en-us&lang=en asks for a phone number to create a Baidu login. However the interface does not allow oneself to choose their own country code. The drop-down menu is missing various countries, including f.ex. Germany. This prohibits me to actually download the data.

**Comment by FlorentRevest** [comment]
My team meets the exact same issue.
We also face difficulties registering to the Baidu cloud with a Norwegian or French phone number. It looks like most European countries are missing, which is weird considering that countries such as North Korea are listed.

**Comment by natashadsouza** [comment]
Currently we only provide data download access for US based developers. We are working on making it available globally but that is still in development. We will let you know when it is available. We are truly sorry for the inconvenience.
