### ISSUE TITLE
Calibration tools compatibilty with 3rd party cameras

### ISSUE THREAD

**Issue by FlorentRevest** [ApolloAuto/apollo#7840]
In our project, we want to use the cameras integrated to our LIDAR, the HESAI Pandora. (listed as supported by Apollo)
However, when running the camera-camera or camera-lidar calibration tools, we observed that the tools would crash.
First, it would assert that the camera dimensions are 1920x1080, however the Pandora cameras have a resolution of 1280x720. Couldn't the tools be extended to support this resolutions?
The tool would also crash when trying to read the images because the Pandora driver publishes images in RGB format and the tools expect YUV images. Again, could the calibration tools be extended to support RGB images?
As a workaround, I made a tool that scales images up and converts them from RGB to YUV: https://github.com/FlorentRevest/apollo/blob/v3.0/modules/tools/pandora_camera_scaler/pandora_camera_scaler.py After converting a bag full of feature-points to a format accepted by the tools, I am able to run the camera-camera calibration without crashes. However, the tool never stops running and never outputs any calibration files. Am I still missing something?

**Comment by freeHackOfJeff** [comment]
@FlorentRevest Many thanks for trying out and help testing calibration tools! The current tool is still in development and improvement stage, and we'd like to get more input in order to cover more scenarios. Also, we'll take your questions and issues into consideration for further development.

**Comment by FlorentRevest** [comment]
Good to hear @freeHackOfJeff, thank you !

Just for the record, if anyone stumbles upon this issue while trying to calibrate a HESAI Pandora, I would recommend extracting both the extrinsic and intrinsic calibration from what's recorded in the device itself. 
https://github.com/HesaiTechnology/pandora_projection_ros/blob/master/src/pandora_projection.cc#L546

This does not solve the radar-camera calibration problem and doesn't help with other camera types but it can help someone in the same situation as me.

**Comment by natashadsouza** [comment]
@FlorentRevest thank you for sharing your fix with the community. We really appreciate your contribution! Closing this issue currently.
