### ISSUE TITLE
The use of cyber schedule

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#7884]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

Hello, Apollo: 
     In Cyber's use case presentation, the configuration for scheduling is as follows.
    scheduler_conf {
           policy: "classic"
           classic_conf {
                 groups:   [
                       {
                                   name: "group1"
                                    process_num: 16
                                    affinity: "range"
                                     cpuset: "0-7,16-23"
                                     processor_policy: "SCHED_OTHER"
                                      process_prio: 0
                                      task:     [
                                             {
                                                      name: "ABC"
                                                      prio: 2
                                               }
                                         ]
                                   }
                                .....
Why are few modules in Apollo using Cyber in this way?

**Comment by zhangchaoltt** [comment]
Hi, @breakisx, a process has a corresponding schedule conf， many modules in Apollo are loaded into a process to start using the compute_sched.conf or control_sched.conf.

**Comment by lvxin0805** [comment]
only some use dataprovider key modules using the scheduler

**Comment by zhangchaoltt** [comment]
Currently closing this issue. @breakisx  if you have any additional questions, feel free to reopen it!
