### ISSUE TITLE
How to run ./scripts/localization_online_visualizer.sh successfully?

### ISSUE THREAD

**Issue by hyx007** [ApolloAuto/apollo#7886]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Ubuntu16.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
1.missing param.txt file while run './scripts/localization_online_visualizer.sh'';
2.Show nothing after run './scripts/localization_online_visualizer.sh'

Could you provide a "how to" document about how to run './scripts/localization_online_visualizer.sh' ? Thx a lot.

**Comment by mickeyouyou** [comment]
You can refer this document 
[How to Run MSF Localization Module On Your Local Computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md)

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
