### ISSUE TITLE
Cyber coroutine: not saving floating point context during switching context

### ISSUE THREAD

**Issue by d-wang03** [ApolloAuto/apollo#7899]
I'm tring to port cyber to aarch64. However, while reading swap.S, I found that floating point context is not saved nor switched. What is the consideration? Will it lead to some unexpected conditions?

**Comment by GoLancer** [comment]
Thanks for your question.
Saving and restoring the FP context is time consuming.
In user-space context switch, we don't have to save/restore floating pointer registers.

**Comment by quning78** [comment]
here is another discussion about why floating point is not necessary. Let me know if you have any other questions.

http://www.crystalclearsoftware.com/soc/coroutine/coroutine/linuxasm.html
