### ISSUE TITLE
Error while building ESD Kernel Driver

### ISSUE THREAD

**Issue by ryandeng1** [ApolloAuto/apollo#79]
When I run ln -s Makefile.esd Makefile;make I get this error message:

make -C /lib/modules/4.4.0-83-generic/build M=/home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src modules
make[1]: Entering directory `/usr/src/linux-headers-4.4.0-83-generic'
  CC [M]  /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/esdcan.o
  CC [M]  /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/osif.o
  SHIPPED /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/nucleus.o
  SHIPPED /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/esdacc.o
  SHIPPED /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/board.o
  SHIPPED /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/boardrc.o
  SHIPPED /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/crc32.o
  LD [M]  /home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/esdcan-pcie402.o
ld: Relocatable linking with relocations from format elf64-x86-64 (/home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/nucleus.o) to format elf32-i386 (/home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/esdcan-pcie402.o) is not supported
make[2]: *** [/home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src/esdcan-pcie402.o] Error 1
make[1]: *** [_module_/home/ryan/Desktop/esdcan-pcie402-linux-2.6.x-x86_64-3.10.4/src] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-4.4.0-83-generic'
make: *** [default] Error 2

**Comment by journey-wang** [comment]
Please contact  support@esd.eu to obtain esdcan-pcie402 for linux 4.4.x kernel, not linux-2.6.x.

**Comment by rdeng2614** [comment]
Is it necessary to install the Linux 4.4.x kernel? When I didn't install the kernel, this part of the build process did not error out, but I'm not sure what would happen down the road.

**Comment by journey-wang** [comment]
You can install apollo kernel firstly by following this guide (remember to reboot machine before install esdcan driver): https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start_developer.md#build-the-apollo-kernel

Seems that your current kernel is not x86_64
ld: Relocatable linking with relocations from format elf64-x86-64 to format elf32-i386

**Comment by rdeng2614** [comment]
If I install the Apollo Kernel without running the command 
"sudo apt-get install linux-generic-lts-xenial"
will I run into errors down the road?

The reason I am asking is because I don't have a esdcan-pcie402 board yet, and the website currently only offers packages for linux kernels 2.6.x and 3.0.x

**Comment by quning78** [comment]
Yes, your problem is that your driver is specific for Linux 2.6 as the name shows. 

esdcan-pcie402-linux-2.6.x-x86_64-3.10.4

You can skip this part for now if you are just trying out with offline demo. But it's required if you want to have your build to control the vehicle.

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
