### ISSUE TITLE
how to start the docker without update?

### ISSUE THREAD

**Issue by debuleilei** [ApolloAuto/apollo#7902]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Ubuntu 16.04
- **Apollo installed from (source or binary)**:source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I want to know why when I start the docker ,it will take a long time today ,yesterday is ok! is there a good way to stop this update and also start the docker ?

### Supporting materials (screenshots, command lines, code/script snippets):
![Screenshot from 2019-04-17 14-55-20](https://user-images.githubusercontent.com/35217567/56267247-dca29100-6120-11e9-89db-93c5e98cb4b9.png)

**Comment by natashadsouza** [comment]
@debuleilei docker takes care of updating the packages and it should not happen more than once. Has this happened more than once?

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reach out if you have additional questions. Thanks!
