### ISSUE TITLE
Cyber transport mode

### ISSUE THREAD

**Issue by daohu527** [ApolloAuto/apollo#7919]
### System information
- **Apollo version 3.5**:

### Steps to reproduce the issue:
Recently I used ros-bridge to let the simulator communicate with apollo for emulation. It works well for ros because it supports multi-machine communication. I know that appllo 3.5 will use "cyber" instead of ros. Does "cyber" supports multiple computer communication through socket?
I found the transfer mode supported by "cyber":
```
enum OptionalMode {
  HYBRID = 0;
  INTRA = 1;
  SHM = 2;
  RTPS = 3;
}
```
What is the difference between them? I can't find any documentation about them. Could you pls offer some doc, or I can contribute some in the future. Thank you!

**Comment by gruminions** [comment]
CyberRT supports cross-host communication.
You can follow fengqikai1414 's answer in this issue: https://github.com/ApolloAuto/apollo/issues/7050#issuecomment-468584667

Thanks for your question.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by ZeusJupiter** [comment]
When multiple computer communicate of cyber each other, the CYBER_IP in "apollo-install-dir/cyber/setup.bash" of each computer  must be the ip of each computer， eg. the CYBER_IP of computer A should be the ip of computer A.

**Comment by daohu527** [comment]
@ZeusJupiter Thx I have learn a lot this days.
