### ISSUE TITLE
Build Error: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@ad_rss_lib'

### ISSUE THREAD

**Issue by jzlwlhao** [ApolloAuto/apollo#7921]
![image](https://user-images.githubusercontent.com/44965839/56335265-65c3d180-61ce-11e9-8976-d46aeb2f7c6e.png)

**Comment by jzlwlhao** [comment]
input command: bash apollo.sh build_cpu
similar issue:
![image](https://user-images.githubusercontent.com/44965839/56403428-dda7ff80-6293-11e9-8939-fce9fc33e312.png)

**Comment by natashadsouza** [comment]
@jzlwlhao could you give us additional details regarding your system?

**Comment by jzlwlhao** [comment]
Ubuntu 16.04.6 LTS 

root@in_dev_docker:/apollo# cat /proc/version
Linux version 4.4.0-62-generic (buildd@lcy01-30) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017

**Comment by natashadsouza** [comment]
@jzlwlhao could you try building using the regular build command and not the build_cpu command instead and let me know if you see any errors?

**Comment by jzlwlhao** [comment]
Almost same error: java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@adv_plat' (requested by nodes 'REPOSITORY:@adv_plat')

**Comment by natashadsouza** [comment]
> Almost same error: java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@adv_plat' (requested by nodes 'REPOSITORY:@adv_plat')

Did you delete the repository and start over before trying this? I recommend you start over and try the regular build command. I am sorry for the trouble.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by Seo80** [comment]
Dear @natashadsouza,

I've got a similar issue while I'm trying to execute following command: "./apollo.sh build_gpu". In particular, I get this error: "Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@ctpl' (requested by nodes 'REPOSITORY:@ctpl')".
Could it be an issue due to I'm working with a proxy? NOTE: I can't avoid its use.

Thank you!!!
