### ISSUE TITLE
traffic_light_status DAG descrption issue

### ISSUE THREAD

**Issue by lvxin0805** [ApolloAuto/apollo#7927]
Hi,
in apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag file,
it list TrafficLightsComponent sub module information, and read light status from this channel : "/apollo/perception/traffic_light_status"
My question is which module send messge by this channel? I can't search other DAG or conf files about it.....
many thanks.

**Comment by lvxin0805** [comment]
in the trafficlights_perception_component.config,
traffic_light_output_channel_name : "/perception/traffic_light_status" configuration had been disabled

**Comment by lvxin0805** [comment]
in the trafficlights_perception_component.config,
traffic_light_output_channel_name : "/perception/traffic_light_status" configuration had been disabled

replaced it with :traffic_light_output_channel_name : "/apollo/perception/traffic_light"

**Comment by yg13** [comment]
> in the trafficlights_perception_component.config,
> traffic_light_output_channel_name : "/perception/traffic_light_status" configuration had been disabled
> 
> replaced it with :traffic_light_output_channel_name : "/apollo/perception/traffic_light"

Sorry for the late reply. If you are using the up-to-date applo, the defaut output channel "/apollo/perception/traffic_light" should work.

If you work offline, you can turn on the image-based visualizer by making "--start_visualizer=true" at 'modules/perception/production/conf/perception/perception_common.flag'. Then you can confirm the results out of the traffic light component visually and directly.

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
