### ISSUE TITLE
about the external trigger of camera

### ISSUE THREAD

**Issue by pengpingliang** [ApolloAuto/apollo#7992]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**:source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

In apollo 3.5, there is a function adv_trigger_enable in the camera driver usb_cam.cc( L402 ).
I cannot enable the external trigger of my camera  LI-USB30-AR02．

Q:
1．I want to enable the external trigger of my camera, How should I do it ?
2．I cannot find the define of the function adv_trigger_enable. How do it work?

**Comment by freeHackOfJeff** [comment]
Thanks for your question. Before driver expert's response, can you please gone through below commits?
https://github.com/ApolloAuto/apollo/commit/811145f8130c9389bb7809cc73d9f5d4843e2352
It looks like adv_trigger_enable is compiled in corresponding static library.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
