### ISSUE TITLE
Cyber talker or listener run outside the docker

### ISSUE THREAD

**Issue by daohu527** [ApolloAuto/apollo#7995]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: **Linux Ubuntu 14.04.5**
- **Apollo installed from (source or binary)**: **source**
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: **Apollo 3.5**

### Steps to reproduce the issue:
I need to use carla python client connect with apollo. So I try to run a example like this:
I run a listener outside the apollo docker, and run a talker inside the docker. Also tried in reverse.
1. Copy cyber.so and depends lib outside the docker. 
2. Run "python cyber/python/examples/listener.py" outside of docker. 
3. Run "python cyber/python/examples/talker.py" in docker. 
I ran both scripts inside the docker and they worked well. When I run as above they seems to connect but receive the following error:  
**talker**
```
apollo@in_dev_docker:/apollo$ python cyber/python/examples/talker.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0423 12:44:10.171006 27691 global_data.cc:153] [talker_sample] host ip: 192.168.1.102
================================================================================
write msg -> integer: 2
text: "talker:send Alex!"

================================================================================
write msg -> integer: 3
text: "talker:send Alex!"
```
**listener**
```
$ python cyber/python/examples/listener.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0423 12:44:08.900657 27662 global_data.cc:153] [cyber_py] host ip: 192.168.1.102
========================================================================================================================
E0423 12:44:11.176287 27688 segment.cc:233] [cyber_py] get shm failed.
E0423 12:44:11.176373 27688 segment.cc:85] [cyber_py] init failed, can't read now.
E0423 12:44:12.177665 27688 segment.cc:233] [cyber_py] get shm failed.
E0423 12:44:12.177772 27688 segment.cc:85] [cyber_py] init failed, can't read now.
E0423 12:44:13.179174 27688 segment.cc:233] [cyber_py] get shm failed.
E0423 12:44:13.179261 27688 segment.cc:85] [cyber_py] init failed, can't read now.
E0423 12:44:13.569265 27688 segment.cc:233] [cyber_py] get shm failed.
```
Any ideas?

**Comment by ZeusJupiter** [comment]
I think it's an issue of cross-machine communication. Please reference to "https://github.com/ApolloAuto/apollo/issues/7050#issuecomment-468584667"

**Comment by daohu527** [comment]
@ZeusJupiter Thanks for your reply! 
I have read the comments and I have successfully connected the two clients in docker. In addition, I have connected one client in the docker on one computer to another client on another computer( Cross physical machine ).  

I don't think this is my operational error. Maybe this caused by running one client in docker and the other don't(they both in one computer, but one in docker, one outside). I guess this's because they think they are in the same computer, so use shm mode to communicate, but they don't. 

Maybe some configurations will fix this? I have also submitted a issue to the fast-RTPS and wait for there reply [#501](https://github.com/eProsima/Fast-RTPS/issues/501)

**Comment by ZeusJupiter** [comment]
@daohu527 Please modify the CYBER_IP of "apollo-install-dir/setup.bash" for host and docker. Make sure the CYBER_IP of host machine is the host's ip , and the CYBER_IP of docker is the docker's ip.

**Comment by daohu527** [comment]
@ZeusJupiter Thx, I follow the method and it works well.
Moreover, Could you introduce how the client in docker find the client outside the docker? Is the container port transparent, or is it some RTPS protocol? Thanks again for you job!

**Comment by GoLancer** [comment]
@daohu527  Client in docker find other clients using RTPS discovery, which is a peer-to-peer discovery system using multicast.

**Comment by daohu527** [comment]
It's hard to understand why client in docker will multicast to the host. I will try to learn how the docker network work. Thx

**Comment by Yimags** [comment]
@daohu527 Hello, I am also trying to connect .py in- and outside the docker just like your case with Apollo 6.0. But I got a `No module named 'cyber.proto.unit_test_pb2''` [error](https://github.com/ApolloAuto/apollo/issues/13187#issue-766895988). I learnt that python binaries are handled by bazel from apollo-6.0. So is it still possible to connect  .py in- and outside the docker?
Thx in advance!

**Comment by daohu527** [comment]
I'm not sure and need to check, I currently execute it by compiling python to binary. 

I am not sure that I can run python scripts directly, due to some problems in 6.0

**Comment by AlexandrZabolotny** [comment]
Hi all!
I am using Apollo pre6  
I am running Apollo on two parallel PCs according to this [instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_setup_dual_ipc.md).  
But I notice the following peculiarity. The frequency of published channels by computer # 1 does not match the frequency of this channel on computer # 2. For example, if the frequency of the channel "/ apollo / sensor / lidar128 / compensator / PointCloud2" on PC1 is 10 Hz, then the frequency on PC2 can be 6 Hz. I also noticed a feature that big data channels slow down the work of another PC.  

So I have a question.  
Is it possible to publish not all channels, but selective channels between two PCs?
