### ISSUE TITLE
No rosbag command

### ISSUE THREAD

**Issue by wadewang6** [ApolloAuto/apollo#80]
Hi how can i get the rosbag command?

**Comment by ycool** [comment]
Any context about your current env? Which way do you choose to run Apollo?
The possible ways to run Apollo can be found at https://github.com/ApolloAuto/apollo/blob/master/FAQ.md

**Comment by gkevinyen5418** [comment]
You probably have to install rosbag by yourself
for example in my ubuntu "sudo apt install python-rosbag"

**Comment by aiguo159** [comment]
rosbag is available as part of the Docker environment -- you don't need to install it yourself if you use the docker environment. Make sure you are running rosbag command within the docker environment.

**Comment by zezhou** [comment]
@wadewang6 
I have met the same problem and I solved it by following commands:

`source /apollo/bazel-apollo/external/ros/setup.bash`

which via https://github.com/ApolloAuto/apollo/issues/80

**Comment by liabixiaoxin** [comment]
I was having the same issue and @zezhou 's answer worked just fine for me.

**Comment by xiaoxq** [comment]
A better solution is to `source /apollo/scripts/apollo_base.sh`, which actually should have been run once when you enter the container. But there is no harm to do it again by hand, if you cannot find ros.
