### ISSUE TITLE
Is to possible to get velodyne_packets and save it to bag instead of pointcloud to reduce bag size?

### ISSUE THREAD

**Issue by frontw** [ApolloAuto/apollo#8026]
Original ROS velodyne_driver publishes /velodyne_packets, that are converted to /velodyne_points by velodyne_pointcloud. 

When writing bag files it's better to save /velodyne_packets instead of /velodyne_points for significant file size reduce.

In Apollo I can't find /velodyne_packets. Is it possible to get it and save to bag instead of point cloud in Apollo v3.0.0?

How VelodyneScanUnified differs? Could it be read in ROS without Apollo?

**Comment by Dengchengliang** [comment]
You can save VelodyneScanUnified in bag and run velodyne launch offline to generate point cloud.
VelodyneScanUnified is ROS msg,  one more "basetime" item in its defination. You can copy the VelodyneScanUnified.msg into your own ROS project to use it.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by Creling** [comment]
Hello, I wonder what is the file formt the bag is? Is is possible to extra pointclouds from `.record` ?
