### ISSUE TITLE
Conversion tools or instructions from standard OpenDrive Format to Apollo's HDMAP OpenDRIVE Format

### ISSUE THREAD

**Issue by xmyqsh** [ApolloAuto/apollo#8045]
Does anyone have the conversion tools or instructions from standard OpenDrive Format to Apollo's HD MAP OpenDRIVE Format？
Some correspondence example is also welcome.

Lots of people have got Apollo‘s HDMap specification here. #3005

**Comment by christian-lanius** [comment]
I am also very interested in this. It could allow us to leverage tools/databases like openstreetmap .

**Comment by natashadsouza** [comment]
Unfortunately we do not support this conversion internally, however our developer community is welcome to respond to this request.
@xmyqsh @christian-lanius thank you both for your interest in Apollo.

**Comment by xmyqsh** [comment]
@christian-lanius I have several materials about this topic. If you are interesting, you could connect me [here](https://discord.gg/7S2HeW).

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by lucasnmatias** [comment]
@xmyqsh hi I'm also deeply interested on this topic, can you provide the materials that you have?

**Comment by Thinsheep** [comment]
hi @xmyqsh 
Could you please give me the materials about this topic?
sgttrieu@gmail.com

**Comment by daohu527** [comment]
There is already a tool for now [imap](https://github.com/daohu527/imap)
