### ISSUE TITLE
problem when debug apollo using vscode

### ISSUE THREAD

**Issue by sunnyguanguanguan** [ApolloAuto/apollo#8046]
### System information
- ** Linux Ubuntu 16.04
- **Apollo version 3.0**:

### Steps to reproduce the issue:
 when i use vscode debug apollo project ,i meet some problem.
after press F5,get some problrm like this:

Unable to start debugging. Program path '/home/zlab-apollo/apollo/bazel-bin/modules/planning/planning' is missing or invalid.
GDB failed with message: /home/zlab-apollo/apollo/bazel-bin/modules/planning/planning: 没有那个文件或目录.
This may occur if the process's executable was changed after the process was started, such as when installing an update. Try re-launching the application or restarting the machine.

i look for the path,and  i found that in apollo files,there is a  soft link name bazel-bin,but when i click it ,it erro:
无法使用此链接，因为其目标
“/root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin”不存在。
![2019-04-25 16-47-50屏幕截图](https://user-images.githubusercontent.com/48610091/56722708-36870480-677a-11e9-9a4f-c08a661bf188.png)
![2019-04-25 16-48-04屏幕截图](https://user-images.githubusercontent.com/48610091/56722734-3f77d600-677a-11e9-945f-f6ac6eabbe49.png)

**Comment by natashadsouza** [comment]
@sunnyguanguanguan have you tried following the steps mentioned in [this guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md)

**Comment by sunnyguanguanguan** [comment]
> @sunnyguanguanguan have you tried following the steps mentioned in [this guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md)

actually,i install docker-ce using  /apollo/docker/setup_host/install_docker.sh,then i can pull images and open dreamviwer successfully  .
And,i can open Apollo project and build successfully in vscode. 
![vscode](https://user-images.githubusercontent.com/48610091/56794464-c099a080-6840-11e9-99cf-ed25807d7023.png)

**Comment by natashadsouza** [comment]
@sunnyguanguanguan so was your build successful?

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by Hongmin2018** [comment]
The same problem as you show, and i wonder if you solve it and how?

**Comment by Hongmin2018** [comment]
The same problem as you show, and make a soft link mauually. 
I wonder that how you solve it. 
Thanks

**Comment by wuzp986** [comment]
I encountered the same problem, how did you solve it?

**Comment by EthanCodesss** [comment]
I also ncountered the same problem, how did you solve it?

**Comment by wlxxi** [comment]
How did you solved it? I met the same trouble.

**Comment by wlxxi** [comment]
> @sunnyguanguanguan have you tried following the steps mentioned in [this guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md)

I'm sorry that this link is invalid, have you solved this problem?
