### ISSUE TITLE
canbus component does not exit gracefully

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#8053]
**Describe the bug**
As subject

**To Reproduce**
1. Launch canbus component using mainboard
`>>mainboard -d /apollo/modules/canbus/dag/canbus.dag`
2. Shutdown it using Ctrl+C
3. The console shows:
```
terminate called without an active exception
Abort 
```

**Cause**
No cleanup of those handles: vehicle_controller_, can_receiver_, can_sender_, and can_client_.

**Fix**
The cyber component has a cleanup hook function called **Clear()** which will be called inside ComponentBase::Shutdown(). Override of this Clear() function inside CanbusComponent fixes the issue.

```
void CanbusComponent::Clear() {

  can_sender_.Stop();
  can_receiver_.Stop();
  can_client_->Stop();
  vehicle_controller_->Stop();

  AINFO << "Cleanup Canbus component";
}
```

**Comment by Capri2014** [comment]
@jilinzhou Thanks! Could you help create a PR for this?

**Comment by jilinzhou** [comment]
@Capri2014 : will do.
