### ISSUE TITLE
Ubuntu16.04 dreamview vehicle won't move 

### ISSUE THREAD

**Issue by kttnk** [ApolloAuto/apollo#8066]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
* bash ./docker/scripts/dev_start.sh
* bash ./docker/scripts/dev_into.sh
* bash ./apollo.sh build
* bash scripts/bootstrap.sh 
* Tasks: Sim Control: ON
* Module Controller: Routing: ON
* Module Controller: Planning: ON
* Default Routing Sunnyvale Loop: ON
* Gives me the screen shot below.  Planning automatically OFF.

### Supporting materials (screenshots, command lines, code/script snippets):
![ubuntu16_dreamview_output](https://user-images.githubusercontent.com/40339488/56793221-70254180-6846-11e9-8c30-885f9e0abe35.png)

**Comment by kttnk** [comment]
One of my machines worked after following #6811 !
The main case seems "git lfs" issue.
* Outside of the docker 
<pre>
cat modules/dreamview/frontend/dist/app.bundle.js 
git lfs fetch --all
git lfs pull
cat modules/dreamview/frontend/dist/app.bundle.js
bash docker/scripts/dev_into.sh
</pre>
* Inside of the docker 
<pre>
bash apollo.sh build
bash scripts/bootstrap.sh
</pre>

I will check the another machine also.
If it works, I will close this issue.  

Thank you in advance!

**Comment by natashadsouza** [comment]
@kttnk thank you for posting a possible fix. If it is a Git LFS issue, we do recommend cleaning your system of the download, and re-downloading Git LFS before downloading Apollo once again. Let us know if you have any issues in the mean time. Thanks!

**Comment by kttnk** [comment]
I conformed this solution works with another machine.  
Closing...
