### ISSUE TITLE
how to read many topic at the same time by cyber_RT?

### ISSUE THREAD

**Issue by debuleilei** [ApolloAuto/apollo#8070]
hello, as mentioned in the apollo/linster.cc,if I want to listen one topic,I can do like this below 
auto listener = listener_node->CreateReader<adu::common::sensor::BestPos>(  "/sensor/novatel/bestgnsspos", MessageCallback);

but if I want to read 4 topics at the same time, what's the best way that I  should  do?

**Comment by ZeusJupiter** [comment]
@debuleilei , hello, now "Cyber Reader" could not support reading many one topic at the same time, but you can use "Cyber Component". It can read many one topic at the same time.Thank you.

**Comment by xmyqsh** [comment]
It is a strange demand to read 4 topics at the same time in the same one "Cyber Component".

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
