### ISSUE TITLE
[suggestion] remove the documents and images from code repository

### ISSUE THREAD

**Issue by chucklqsun** [ApolloAuto/apollo#8073]
Too many images in the repository and the time for git clone is very very long (and annoying). These documents and images are useless for developers who usually check docs on the website. The best practice to maintain document is using system like wiki or confluence.

**Comment by natashadsouza** [comment]
Hi @chucklqsun that is great feedback. We will definitely look into your suggestion and see how we can make the Apollo clone process more efficient. Thanks!
