### ISSUE TITLE
Dose Apollo 3.5 has CIPV function

### ISSUE THREAD

**Issue by LidarADAS** [ApolloAuto/apollo#8088]
I found CIPV in Apollo3.0, but I do not see it in Apollo 3.5.

**Comment by xiaoxq** [comment]
In Apollo 3.5 we released the new CyberRT, and then started the work of migration everything on top of it. The CIPV part is done recently (https://github.com/ApolloAuto/apollo/commit/a09416cef0b889cba128ade212b5822f5c65db28), so it will be in Apollo 4.0. Enjoy!

**Comment by xmyqsh** [comment]
@xiaoxq Does Apollo support lane following using lane detection result instead of HDMap?

**Comment by natashadsouza** [comment]
@xmyqsh as mentioned, we are in the process of migrating our features on to Cyber RT and request your patience. We will have more information about CIPV during Apollo 4.0 release. Stay tuned!

**Comment by LidarADAS** [comment]
Got it, thank you for your reply.
