### ISSUE TITLE
  Is there a plan to upgrade docker image to use Ubuntu 16? When will it be upgraded?

### ISSUE THREAD

**Issue by ax7476** [ApolloAuto/apollo#8089]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by natashadsouza** [comment]
Hi @ax7476 thank you for your question. We are currently in the process of upgrading to Ubuntu 18 and even have a branch created for it. We will not be releasing a version that is based on Ubuntu 16 unfortunately.

**Comment by ax7476** [comment]
Is there an approximate release date about updating to Ubuntu 18?

**Comment by natashadsouza** [comment]
We have a version release coming up in July. You should hear more from us closer to the date. Thank you for your interest in Apollo.
