### ISSUE TITLE
Is it same of cyber_rt and cybertron ?

### ISSUE THREAD

**Issue by debuleilei** [ApolloAuto/apollo#8091]
I get a work to make some codings in an caros system which is supplied by Baidu.but I find that the system is a little different from the apollo, It is build by Cybertron, I Have tried to test the listener in this system ,but I failed although I have change the proto  which is right in the caros system.
  Can you give me some advice? the below pic show the log ,I can't get enough details to ensure what to do........
![Screenshot from 2019-04-29 15-23-38](https://user-images.githubusercontent.com/35217567/56885696-a5789c00-6a9f-11e9-84ad-222b546dbe44.png)

**Comment by debuleilei** [comment]
I 'm wondering if I could make some codings in apollo environment, and make it work  in the adu which use the cybertron ? is it possible? now I met a problem that I can't open a node in the cybertron environment ,

**Comment by Dengchengliang** [comment]
You can ping me in company network about this question, or contact you in company network when you send your hi account.

**Comment by Dengchengliang** [comment]
You can ping me in company network about this question, or contact you in company network when you send your hi account.

**Comment by Dengchengliang** [comment]
You can ping me in company network about this question, or contact you in company network when you send your hi account.

**Comment by debuleilei** [comment]
sorry ,I 'm not a worker in baidu, but another company's worker. Is there anyway to solve this problem?

**Comment by Dengchengliang** [comment]
Could you give more information about cyber version which you are using? When and who supply that from Baidu?

**Comment by quning78** [comment]
@debuleilei please message us privately to discuss any issue which is not in our public repo. Thanks!
