### ISSUE TITLE
bug in demo_2.5.bag

### ISSUE THREAD

**Issue by Wang4758** [ApolloAuto/apollo#8100]
**Describe the bug**
The position of  obstacle should be referred to world frame according to the proto definition. But the /apollo/perception/obstacles messages in demo_2.5.bag have really small values for positions. So I guess they were referred to vehicle frame instead. Is that a bug?

**To Reproduce**
rosbag play demo_2.5.bag
rostopic echo /apollo/perception/obstacles

**Expected behavior**
positions are really small values

**Comment by yifeijiang** [comment]
Obstacles are referred to vehicle frame for Navi mode of Apollo 2.5.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
