### ISSUE TITLE
Release of Caffe Sources

### ISSUE THREAD

**Issue by christian-lanius** [ApolloAuto/apollo#8102]
I am working on creating an up-to-date docker image with ubuntu 18.04/cuda 10.1 and I am by now capable of running perception. To run traffic light detection however, one can not use the BVLC/caffe, as some layers (at least: permute, which can be taken from here https://github.com/BVLC/caffe/commit/b68695db42aa79e874296071927536363fe1efbf and RPNProposalSSD) are missing. Thus, during runtime, the traffic light module will crash with the error: 
> [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 2428:18: Message type "caffe.LayerParameter" has no field named "bbox_reg_param".
F0430 16:14:44.847780 31927 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /apollo/modules/perception/production/data/perception/camera/models/traffic_light_detection/./deploy.prototxt

Can you make the source code/modifications for the layers which are not part of the official caffe available? This would allow us to build our own caffe instead of relying on the binaries which are pulled in during docker build (build_gpu_caffe.sh). I am not interested in the training of the models, so probably, header, source and the modified caffe.proto are enough.

I checked the ApolloAuto/caffe git as well, but the changes made for the traffic light detection seem not to be reflected in there.

**Comment by christian-lanius** [comment]
I messed up and did not see that the necessary changes are applied in the apollo branch of the caffe clone. I am sorry about that.

**Comment by dfguooo** [comment]
Hi, @christian-lanius @liuqf0425. I got the same problem with apollo's caffe layers. May I know how to find the source code or modifications in apollo's caffe? Thanks:)

**Comment by icolwell-as** [comment]
According to this issue: https://github.com/ApolloAuto/apollo/issues/5876 the caffe source was released at some point here: https://github.com/ApolloAuto/caffe

But it seems like it was removed, does anyone know where to find the source code now?
