### ISSUE TITLE
how to generate data in OpenDrive format?

### ISSUE THREAD

**Issue by ljxiango** [ApolloAuto/apollo#8118]
I'm a beginner in OpenDrive. I've read the instructions and learned a lot from OpenDrive and apollo OpenDrive.

   I have a high-precision map built by slam, but I don't know how to generate data in OpenDrive format. I learned that JOSM is an editing tool for OpenStreetMap that can generate data in OpenStreetMap format. Is there an editing tool that can generate data in OpenDrive format, just like JOSM for OpenStreetMap？
   Thanks, I look forward to your help.

**Comment by natashadsouza** [comment]
Hi @ljxiango 
We do not currently have any tools to convert your map into Opendrive or the Apollo Opendrive format that is available on open source. You could refer to Opendrive's website for tools on converting your current map. Closing this issue currently.
