### ISSUE TITLE
velodyne driver inserts invalid packets into the final scan msg if socket read fails.

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#8123]
In driver.cc:

```
int VelodyneDriver::PollStandard(std::shared_ptr<VelodyneScan> scan) {
  // Since the velodyne delivers data at a very high rate, keep reading and
  // publishing scans as fast as possible.
  while ((config_.use_poll_sync() &&
          ((config_.is_main_frame() &&
            scan->firing_pkts_size() < config_.npackets()) ||
           (!config_.is_main_frame() && sync_counter == last_count_))) ||
         (!config_.use_poll_sync() &&
          scan->firing_pkts_size() < config_.npackets())) {
    while (true) {
      // keep reading until full packet received
      VelodynePacket* packet = scan->add_firing_pkts();
      int rc = input_->get_firing_data_packet(packet);

      if (rc == 0) {
        break;  // got a full packet?
      } else if (rc < 0) {
        return rc;
      }
    }
  }
  if (config_.use_poll_sync()) {
    if (config_.is_main_frame()) {
      ++sync_counter;
    } else {
      last_count_ = sync_counter;
    }
  }
  return 0;
}
```

Before calling of input_->get_firing_data_packet(packet), this expected new packet is already appended into the scan->firing_packets:

` VelodynePacket* packet = scan->add_firing_pkts();`

If calling of input_->get_firing_data_packet(packet) fails, this empty packet is published along with other good packets. Then in the convert stage, the processing of each packet from this scan generates some timestamp jump errors.

**Comment by jilinzhou** [comment]
Although it is an issue, our problem is actually caused by velodyne VLP16 firmware: that once a while , the velodyne VLP 16 sends out a packet with wrong timestamp. I directly parse out the timestamp when the packet is received and compare it with the previous one as the following:

```
int VelodyneDriver::PollStandard(std::shared_ptr<VelodyneScan> scan) {
...
      VelodynePacket packet;
      int rc = input_->get_firing_data_packet(&packet);
      const unsigned int* timestamp_since_last_hour =
          reinterpret_cast<const unsigned int*>(packet.data().data() + 1200);
      double pkt_timestamp = static_cast<double>(*timestamp_since_last_hour);  // usec

      if (pkt_timestamp - prev_pkt_timestamp < 0.0) {
        AERROR << "Invalid packet received" << pkt_timestamp - prev_pkt_timestamp;
      }

...
}
```

Here is what I see:

```
E0501 13:38:58.334810     4 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1328
E0501 13:38:58.415807    14 driver.cc:155] [velodyne_driver] Invalid packet received-61046
E0501 13:38:58.417806     6 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1327
E0501 13:38:58.417806     6 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1327


... later on in convert stage

E0501 13:38:58.435806     6 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1327
E0501 13:38:58.436806     6 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1327
E0501 13:38:58.436806     6 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: -61046
E0501 13:38:58.436806     6 velodyne16_parser.cc:94] [velodyne_convert] The current packet timestamp is earlier than the previous one
E0501 13:38:58.517803     4 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 62374
E0501 13:38:58.518803     4 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1327
E0501 13:38:58.518803     4 velodyne16_parser.cc:92] [velodyne_convert] delta time in between packets: 1327

```

It seems that we need to ignore this invalid packet in the first place.

**Comment by fengliu00** [comment]
Can I ask how usually the issue occurs, every 1 second, 1 minute or longer? As you described, it is possibly caused by the incorrect firmware version inside 16-beam velodyne unit. How did you confirm it, according to the log created by you or a method else?

**Comment by jilinzhou** [comment]
@fengliu00 : This happens on our Renasas H3 board running qnx. With more debugging, we do not think it the problem of Velodyne firmware at the moment. We are trying different network drivers now. Will keep you updated.

**Comment by fengliu00** [comment]
Can you check the incoming packets, especially the packet tagged with the incorrect timestamp by a sniffer tool on Ethernet? I wonder the packet with the incorrect timestamp as you thought just arrives little bit later at ethernet interface or socket.

**Comment by jilinzhou** [comment]
@fengliu00 : We can confirm now it is the issue of network driver we are using. After we switched to a ethernet-usb dongle, the issue disappears. We need to confirm it again with two velodynes running at the same time.

**Comment by jilinzhou** [comment]
With two VLP 16 running for a while, we have not seen the same issue. I will close the issue for now. Thanks for all!
