### ISSUE TITLE
displays nothing on rosnode list and rostopic list 

### ISSUE THREAD

**Issue by chowkamlee81** [ApolloAuto/apollo#8149]
We build apollo3.0 release using below procedure

a) bash docker/scripts/dev_start.sh
b) bash docker/scripts/dev_into.sh
c) bash apollo.sh build
d) bash scripts/bootstrap.sh

roscore is running after bash scripts/bootstrap.sh and also apollo build got successfully, Dreamview is getting launched.
But rosnode list and rostopic list displays nothing.

Kindly help

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
