### ISSUE TITLE
HDL32e velodyne driver GPS timestamp is off after EPOC change

### ISSUE THREAD

**Issue by nulungzi2001** [ApolloAuto/apollo#8150]
I found that the GPS timestamp of point cloud coming out of HDL32e velodyne driver is different to actual GPS time (from other device like Applanix or Novatel GNSS system). I guess an EPOC change happened around April. 6 caused this problem. That is, the EPOC change is accounted for in the GNSS systems but not in velodyne GPS pucks.. Do you have any solution to this issue?

**Comment by cicelprg** [comment]
The timestamp parses from the positioning data packets directly which send by HDL32e，so please check if the device status is normal？

**Comment by nulungzi2001** [comment]
It is confirmed that the device status is normal. Timestamp was OK before April. 6 (the setting was like normal HDL32e + garmin GPS puck connected to HDL32e + HDL32e driver from Apollo/ROS). But now (after April. 6), the timestamp is off from other GNSS timestamp even with using the same setting as above.

**Comment by nulungzi2001** [comment]
could anyone explain the reason behind adding (2000-1900) to the year and subtracting 1 from month in the following function in "driver.cpp" written by Apollo?

void VelodyneDriver::set_base_time_from_nmea_time(NMEATimePtr nmea_time,
                                                  uint64_t& basetime) {
  tm time;
  time.tm_year = nmea_time->year + (2000 - 1900);
  time.tm_mon = nmea_time->mon - 1;
  time.tm_mday = nmea_time->day;
  time.tm_hour = nmea_time->hour;
  time.tm_min = 0;
  time.tm_sec = 0;

  // set last gps time using gps socket packet
  last_gps_time_ = (nmea_time->min * 60 + nmea_time->sec) * 1e6;

  ROS_INFO("Set base unix time : %d-%d-%d %d:%d:%d", time.tm_year, time.tm_mon,
           time.tm_mday, time.tm_hour, time.tm_min, time.tm_sec);
  uint64_t unix_base = static_cast<uint64_t>(timegm(&time));
  basetime = unix_base * 1e6;
}

**Comment by cicelprg** [comment]
> could anyone explain the reason behind adding (2000-1900) to the year and subtracting 1 from month in the following function in "driver.cpp" written by Apollo?
> 
> void VelodyneDriver::set_base_time_from_nmea_time(NMEATimePtr nmea_time,
> uint64_t& basetime) {
> tm time;
> time.tm_year = nmea_time->year + (2000 - 1900);
> time.tm_mon = nmea_time->mon - 1;
> time.tm_mday = nmea_time->day;
> time.tm_hour = nmea_time->hour;
> time.tm_min = 0;
> time.tm_sec = 0;
> 
> // set last gps time using gps socket packet
> last_gps_time_ = (nmea_time->min * 60 + nmea_time->sec) * 1e6;
> 
> ROS_INFO("Set base unix time : %d-%d-%d %d:%d:%d", time.tm_year, time.tm_mon,
> time.tm_mday, time.tm_hour, time.tm_min, time.tm_sec);
> uint64_t unix_base = static_cast<uint64_t>(timegm(&time));
> basetime = unix_base * 1e6;
> }

This function mainly converts NMEA-time into Linux timestamp，the NMEA-time parse from GPRMC sentence which send by postioning data packet. According to the official document description of velodyne, the GPRMC format is as follow pic.

![image](https://user-images.githubusercontent.com/5786533/57355285-43571f80-71a0-11e9-80eb-af1dbe9c9b7f.png)

And now is 2000, so we need add 2000, and the year filed of tm struct is from 1900，so we need subtracting 1900,  and so on.

I think you should check if the GPRMC statement conforms to the velodyne device, and the velodyne official documentation may help you.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
