### ISSUE TITLE
Control module couldn't follow steering command in vallet parking 

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#8161]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 14.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5
Commit number: 00755793a0051f1f130f4eaba1dfaee687a85349
Using LGSVL Simulator.

### Steps to reproduce the issue:
1.Made parking space on hdmap.
2.Checked parking operation worked with Simcontrol on dreamview.
3.Ran Localization, Perception, Planning, Prediction, Routing, Traffic Light, Transform.
4.The vehicle stops near to the parking space.
5.The planning modules started vallet parking and made trajectory.

Issue: The control module couldn't follow the target steering command. Steering target is small number. Then the controller doesn't make car moving. Sometimes, the car is moving but steering is applied too much. It doesn't stop at the moment when the vehicle is supposed to stop steering. How can I make it working? Any suggestion?

![image](https://user-images.githubusercontent.com/14055939/57172456-2784ff80-6dd5-11e9-9764-c42cf6134124.png)
![image](https://user-images.githubusercontent.com/14055939/57172458-2f44a400-6dd5-11e9-889d-f195e58b2ceb.png)

**Comment by Capri2014** [comment]
Lol, the control-in-loop is not available yet, so what you saw via Dreamview is under "perfect control", a.k.a planning trajectory directly re-interpreted as chassis & localization information.

**Comment by natashadsouza** [comment]
Currently closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by dongyy1148** [comment]
@cyberphysicalrobotics Hi. Could you tell me how you ask Apollo to use the valet parking scenario? Is it called in dreamview? I also use the LGSVL simulator. Thanks!

**Comment by cyberphysicalrobotics** [comment]
There is a map, provided by Apollo, which has parking space. The map name is sunnyvale_with_two_offices. In the map directory, there is default routing file defining point of interest. Its file name is default_end_way_point.txt. You can refer to this file and notice how this file defines waypoints to trigger parking scenario. 

When you test parking scenario, follow these steps.
1.Run dreamview. 
2.In Tasks tab, turn sim control on.
3.In Module Controller, run Routing and Planning modules.
4.In Default Routing, you can choose one of parking waypoints.
Then you can see the vehicle doing parking.

I'm working on vehicle parking with LGSVL simulator. In apollo 3.5, Planning module doesn't seem to be done with vallet parking.

**Comment by Capri2014** [comment]
@cyberphysicalrobotics Thanks for your reply. And in 3.5, you need to change specific configs to enable open space planning, but in latest code it is been merged to new `valet_parking` scenarios and no specially configs needed. :)

**Comment by dongyy1148** [comment]
@cyberphysicalrobotics Thanks a lot for your detailed explanation. Based on your explanation, the parking seems to be limited to the parking scenario and it cannot be used in other maps like SF's parking spaces along the road. Am I right?
