### ISSUE TITLE
What does this code mean?

### ISSUE THREAD

**Issue by newmcc** [ApolloAuto/apollo#8164]
Hello, 

The following code confuses me, anyone can explain its grammar？

`  []() -> LocalizationBase* { return new RTKLocalization(); })`;

 ` []()->`  means what?
It is in Localization.cc of apollo1.0 and line 38.

thanks.

**Comment by krishnatoshniwal** [comment]
Its a lambda function with no input parameter and the return object having the type ```LocalizationBase*```. Look up on lambda expressions [here](https://en.cppreference.com/w/cpp/language/lambda)

**Comment by newmcc** [comment]
I see, thank you！
