### ISSUE TITLE
(rtk_localization.cc) line 156 typo, 'Raw GPS Message...' should be 'Raw IMU Message...'

### ISSUE THREAD

**Issue by trooperli** [ApolloAuto/apollo#8185]
**Describe the bug**
'Raw GPS Message...' should be 'Raw IMU Message...'. This is a typo.

**Comment by natashadsouza** [comment]
@trooperli thank you for supporting the Apollo community. Please make a pull request to modify the code. Thank you!

**Comment by natashadsouza** [comment]
Refer to #8231 
Closing this issue.
