### ISSUE TITLE
Can we set initial vehicle speed during simcontrol simulation

### ISSUE THREAD

**Issue by s894330** [ApolloAuto/apollo#8190]
When simcontrol, the vehicle always start from speed 0km/h, can we set initial speed (like 20km/h) for vehicle to start? thank you

**Comment by s894330** [comment]
After study dreamview/backend/sim_control/sim_control.h, I found the declare
`  void Init(bool set_start_point, double start_velocity = 0.0,
            double start_acceleration = 0.0) override;`

maybe we can set initial speed using start_velocity variable?
thank you

**Comment by natashadsouza** [comment]
@s894330 is there a reason why you would like the initial vehicle speed to be changed?

**Comment by s894330** [comment]
hi Natashadsouza,

sorry for late reply,

when we test on real car and cyber recorder is recording and happened some problem in some situation which the vehicle speed may not be zero, we then want to reproduce the same situation in simulator, that is why I want to let initial speed not zero ,but set to definite speed according the record bag period

**Comment by natashadsouza** [comment]
Can you share with us what the error messages are?

**Comment by s894330** [comment]
hi, Natashadsouza

currently we do not have real car in test, we just make schedule for all stuff, and firstly studying how to debug if we meet problem in real car and then reproduce situation in lab. Now I can reproduce the same situation if starting speed is zero using record bag(only record obstacles and routingrequest topic), if the record bag is recorded when speed is not zero, the replay obstacles will mismatch in simulation ,since the initial speed in bag is not zero, but the initial speed in simulation is zero. I still investigate how to handle this, thank you

**Comment by s894330** [comment]
hi all

let me make an example to explain why I want to set initial speed not zero in simcontrol

example:
we start vehicle in speed zero and begin record bag, now vehicle begin to auto-pilot to destination using apollo software, after 40 minutes later (not yet goal reached), something happened (and vehicle speed is not zero), so we stop it, and collect the record bag back to lab to reproduce issue

the record bag is so big (about 40 minutes), the reproduce time will be long if we replay from head of bag, so we want to only replay bag from about 38 minutes to 40 minutes, this will speed up the debug time, but the initial vehicle speed will not be zero

this is why I want to set initial vehicle speed to non zero.
I am not sure if it is possible to set vehicle initial speed according data in record bag

thank you for your help :-)

**Comment by daohu527** [comment]
Yes, but you need to modify the code in the sim_control part, you can get the speed of the vehicle from the chassis in the bag

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
