### ISSUE TITLE
不能使用中国镜像

### ISSUE THREAD

**Issue by caoyifeng001** [ApolloAuto/apollo#8196]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information
Ubuntu16.04
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
不能使用中国镜像，使用外国的经常中途挂掉
### Supporting materials (screenshots, command lines, code/script snippets):
cbin@cbin-MS-7B23:~/apollo-1$ sudo bash docker/scripts/dev_start.sh -C
[INFO] Start pulling docker image registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20181210_1500 ...
Error response from daemon: Get https://registry.docker-cn.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[ERROR] Failed to pull docker image.

**Comment by natashadsouza** [comment]
@caoyifeng001 为什么不尝试使用Apollo软件安装指南中提到的过程构建Docker容器？

**Comment by caoyifeng001** [comment]
sudo bash docker/scripts/dev_start.sh -C 这个命令行不是docker下载吗

**Comment by natashadsouza** [comment]
@caoyifeng001 这不是Docker下载命令，而是Apollo的docker容器的构建命令。您应首先下载Docker，然后使用此命令。参考这个文件：[https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md)

**Comment by gengqx** [comment]
@caoyifeng001 目前docker-cn并非apollo的team维护，最近docker的美国及中国服务器都有些问题。。。目前没有更好的方法，只能多此 尝试或者翻墙解决。其他的解决方案比如，我们内部做了一个使用阿里云的私有服务器同步apollo的docker，但是如果本身访问有问题，也没有更好的办法，近期的新的镜像就可能无法同步，也只能通过多次尝试或者翻墙解决。

**Comment by natashadsouza** [comment]
@gengqx you mentioned server problem, could you elaborate on that please?

**Comment by gengqx** [comment]
@natashadsouza  the docker hub server is maintained by docker hub team,I could not help on this. On the other hand,the connection to docker hub server is also influenced by GFW.

**Comment by natashadsouza** [comment]
Thanks for the information @gengqx we will look into how this can be made more efficient for our developers.

**Comment by maoyuze** [comment]
> 
> 
> @caoyifeng001 这不是Docker下载命令，而是Apollo的docker容器的构建命令。您应首先下载Docker，然后使用此命令。参考这个文件：https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md

我已经用apt-get安装好了docker，尝试了docker run hello-world,可以正常运行。但是，执行bash ./docker/scripts/dev_start.sh -C还是失败，若不加-C，又特别慢，没有其他方法了吗？

**Comment by mickeyouyou** [comment]
will remove docker-cn please use default docker image download url.

thanks
