### ISSUE TITLE
Build apollo in vscode failed 

### ISSUE THREAD

**Issue by xclord** [ApolloAuto/apollo#8216]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
mac 10.14
- **Apollo installed from (source or binary)**:
build apollo in vscode
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:    
3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
I followed this instruction : https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_debug_apollo_in_vscode_cn.md

### Supporting materials (screenshots, command lines, code/script snippets):

____(05-08 08:21:22.561) [5,346 / 5,947] Still waiting for 2 jobs to complete:
      Running (local):
        Compiling modules/dreamview/backend/simulation_world/simulation_world_service.cc, 1376 s
        Compiling modules/dreamview/backend/main.cc, 1322 s
ERROR: (05-08 08:27:10.967) /apollo/modules/dreamview/backend/simulation_world/BUILD:5:1: C++ compilation of rule '//modules/dreamview/backend/simulation_world:simulation_world_service' failed (Exit 4).
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
============================
[ERROR] Build failed!
[INFO] Took 198 seconds
============================
The terminal process terminated with exit code: 255

**Comment by zezhou** [comment]
apollo 3.5 doesn't support  mac os, even in docker ...

**Comment by xclord** [comment]
> apollo 3.5 doesn't support mac os, even in docker ...

which version is supported in mac ?  is there a plan to support mac in version3.5 ...

**Comment by natashadsouza** [comment]
@xclord we do not currently support building Apollo on MAC and do not have it currently in our development plan. We recommend using a VM instead with Ubuntu 14.04. We are in the process of upgrading to Ubuntu 18.04.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
