### ISSUE TITLE
参考硬件报价

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo#822]
您好，有看到apollo提供的硬件参考平台，想问下能否提供下这些硬件器件的参考价格，范围也可以，网上似乎搜不到这些信息，谢谢。

**Comment by YangHan101** [comment]
您好，感谢您的咨询！
很遗憾的是我们没有公开硬件供应商定价的权限。以我的了解，硬件供应商通常不会把定价公布在网络上。如果您对我们提供的硬件价格感兴趣的话，还请您通过电邮，电话或者网站直接联系相应的硬件供应商。以下是几个核心硬件供应商的联系方式。每个供应商的网页上应该有相应的获得报价的链接，或者询问价格的电子邮件信息。

### Neousys：
15F No. 868-3,   Zhongzheng Road
Zhonghe District, New Taipei City 23586
Taiwan, R.O.C.
Tel: 886-2-22236182
[Neousys Nuvo-6108GC webpage](https://www.neousys-tech.com/en/product/application/rugged-embedded/nuvo-6108gc-gpu-computing)
 
### ESD electronics, Inc.
PO Box 270
Greenfield, MA 01302
(413)772-3170
michelle.harris@esd.eu
http://www.esd-electronics-usa.com
 [ESD CAN card webpage](https://esd.eu/en/content/can-pcie402-fd-overview)

### NovAtel Inc.
Sean Walsh
1120-68th Avenue N.E. Calgary AB Canada   T2E 8S5
(713)893-6694
sean.walsh@novatel.com

You can choose 
[NovAtel SPAN-IGM-A1](https://www.novatel.com/products/span-gnss-inertial-systems/span-combined-systems/span-igm-a1/)

Or
[Novatel Propak6](https://www.novatel.com/products/gnss-receivers/enclosures/propak6/)
[Novatel IMU-IGM-A1](https://www.novatel.com/products/span-gnss-inertial-systems/span-imus/span-mems-imus/imu-igm-a1/)

### Velodyne LiDAR
5521 Hellyer Ave, San Jose, CA 95138
(408)465-2800
[Velodyne HDL64 LiDAR](http://www.velodynelidar.com/hdl-64e.html)

如果您还有更多疑问，请在下方留言，我们一定及时答复。

**Comment by ahuer2435** [comment]
好的，谢谢了。

**Comment by junjieshen** [comment]
Hi @YangHan101,

Do you have any contact information for purchasing the supported Navtech GPS (Navtech NV-GI120)?

Thanks,
Junjie
