### ISSUE TITLE
RTK Replay planning mode with additional planning tasks and driving scenarios

### ISSUE THREAD

**Issue by kkhitsko** [ApolloAuto/apollo#8222]
It's it possible to configure and run planning module in RTK Replay mode with ability to change line or emergency stop to avoid obstacles collision?

**Comment by yifeijiang** [comment]
No, you need use standard mode for those functions.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
