### ISSUE TITLE
Error: This repository is over its data quota

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#8281]
when we try to fetch the new apollo lfs file,using comman:
```
git lfs fetch --all upstream
```

we would got:
```
fetch: 1621 object(s) found, done                                                                                                                                                                            
fetch: Fetching all references...
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                                                          
error: failed to fetch some objects from 'https://github.com/apolloauto/apollo.git/info/lfs'
```

**Comment by amontserratAG** [comment]
Hi! same error, different instruction:
$ bash docker/scripts/dev_start.sh
Updated git hooks.
Git LFS initialized.
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.

**Comment by xiaoxq** [comment]
Thank you for reporting! We noticed this LFS issue and is working on it. Hopefully it will be back on Monday (i.e. Tuesday in China).
