### ISSUE TITLE
Compile apollo Cyber RT in aarch64 platform, need fastrtps modification

### ISSUE THREAD

**Issue by bssung** [ApolloAuto/apollo#8289]
Cyber RT depends on fastrtps. 
But fastrtps is not open source in X86 cyber RT. 
The eProsima Fast RTPS ( fastrtps 1.5.0 and fastcdr 1.0.7 ) in official website does't work well in aarch64 cyber RT.
What is the modification of fastrtps?

**Comment by darbee** [comment]
> Cyber RT depends on fastrtps.
> But fastrtps is not open source in X86 cyber RT.
> The eProsima Fast RTPS ( fastrtps 1.5.0 and fastcdr 1.0.7 ) in official website does't work well in aarch64 cyber RT.
> What is the modification of fastrtps?
What does “does't work well in aarch64 cyber RT” mean? Can't nodes communicate with each other or 
or losting message？Can you describe it more specifically?

There are indeed some things that need to be changed in fast rtps:
Find the socket_ops.ipp file in third_party_src/fast_rtps/thirdparty/asio/asio/include/asio/detail/impl/ folder:
` #if defined(__MACH__) && defined(__APPLE__) \
  || defined(__NetBSD__) || defined(__FreeBSD__) || defined(__OpenBSD__)
  || defined(__NetBSD__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(YOURPLATFORM)
    // To implement portable behaviour for SO_REUSEADDR with UDP sockets we
    // need to also set SO_REUSEPORT on BSD-based platforms.
    if ((state & datagram_oriented)`

add YOURPLATFORM to the macro definition.

Find multicast.cpp file in  third_party_src/fast_rtps/thirdparty/asio/asio/src/tests/unit/ip/multicast.cpp  folder,:
`#if (defined(__MACH__) && defined(__APPLE__)) \
  || defined(__FreeBSD__) \
  || defined(__NetBSD__) \
  || defined(__OpenBSD__)
  || defined(__OpenBSD__) \
  || defined(__QNX__)
  const ip::address multicast_address_v6 = ip::make_address("ff02::1%lo0", ec);
#else // (defined(__MACH__) && defined(__APPLE__))
      //   || defined(YOURPLATFORM)`

and  add YOURPLATFORM to the macro definition.

**Comment by bssung** [comment]
Hello @darbee ,  I run the talker/listener examples of Cyber RT, they can't communicate with each other.
Here is the log:
//////////////////////////////////////////////////////////////////////////////////////////////////////
taker.INFO:
I0212 22:14:20.124140  4517 init.cc:112]  Register exit handle succ.
I0212 22:16:26.607206  4517 talker.cc:42]  talker sent a message!
I0212 22:23:33.528126  4517 talker.cc:42]  talker sent a message!
W0212 22:23:33.528605  4517 rate.cc:95]  Detect forward jumps in time
I0212 22:23:33.528791  4517 talker.cc:42]  talker sent a message!
W0212 22:23:33.530519  4541 manager.cc:192]  !message::ParseFromString(msg_str,
&msg) is not met.
I0212 22:23:41.030671  4517 talker.cc:42]  talker sent a message!
W0212 22:23:41.030889  4517 rate.cc:95]  Detect forward jumps in time

listener.INFO:
I0212 22:13:49.499541  4491 init.cc:112]  Register exit handle succ.
W0212 22:23:30.697654  4515 manager.cc:192]  !message::ParseFromString(msg_str,
&msg) is not met.

///////////////////////////////////////////////////////////////////////////////////////////////////////

I am debuging this problem, and found some part of the string message is missing. 
The string messages are published and received by these 2 functions. These 2 functions will call Fast-RTPS's functions.
apollo::cyber::service_discovery::Manager::Publish("\b\254\243\3... 001\030\000 \001(\002")
apollo::cyber::service_discovery::Manager::OnRemoteChange("\b\254\243\3... 001\030")

The \000 \001(\002 string is missing. 

If I don't describe clearly, please let me konw. Thank you.

**Comment by bssung** [comment]
@darbee   I compiled fastrtps on the aarch64 platform. According to what you said, I defined AARCH64, and then added "||defined(AARCH64)" to the location of the socket_ops.ipp file and the multicast.cpp file. Compile cyber again. RTPS_ERROR Error] Reader 1.f.0.3.e2.1d.0.0.0.0.0.0|0.0.4.4 cannot match write 1.f.0.3.c9.1d.0.0.0.0.0.0|0.0.3.3 -> Function PairingReader" Am I doing right?  How can I solve this problem? Thank you.

**Comment by darbee** [comment]
> Hello @darbee , I run the talker/listener examples of Cyber RT, they can't communicate with each other.
> Here is the log:
> //////////////////////////////////////////////////////////////////////////////////////////////////////
> taker.INFO:
> I0212 22:14:20.124140 4517 init.cc:112] Register exit handle succ.
> I0212 22:16:26.607206 4517 talker.cc:42] talker sent a message!
> I0212 22:23:33.528126 4517 talker.cc:42] talker sent a message!
> W0212 22:23:33.528605 4517 rate.cc:95] Detect forward jumps in time
> I0212 22:23:33.528791 4517 talker.cc:42] talker sent a message!
> W0212 22:23:33.530519 4541 manager.cc:192] !message::ParseFromString(msg_str,
> &msg) is not met.
> I0212 22:23:41.030671 4517 talker.cc:42] talker sent a message!
> W0212 22:23:41.030889 4517 rate.cc:95] Detect forward jumps in time
> 
> listener.INFO:
> I0212 22:13:49.499541 4491 init.cc:112] Register exit handle succ.
> W0212 22:23:30.697654 4515 manager.cc:192] !message::ParseFromString(msg_str,
> &msg) is not met.
> 
> ///////////////////////////////////////////////////////////////////////////////////////////////////////
> 
> I am debuging this problem, and found some part of the string message is missing.
> The string messages are published and received by these 2 functions. These 2 functions will call Fast-RTPS's functions.
> apollo::cyber::service_discovery::Manager::Publish("\b\254\243\3... 001\030\000 \001(\002")
> apollo::cyber::service_discovery::Manager::OnRemoteChange("\b\254\243\3... 001\030")
> 
> The \000 \001(\002 string is missing.
> 
> If I don't describe clearly, please let me konw. Thank you.

Hi @bssung , through your description, it seems to be a problem of string truncation.
`\b\254\243\3... 001\030\000 \001(\002"`
the 000 may be treated as the end of string. I also fixed this bug of fast rtps.
You look the the site :
https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch
 It's the patch of string truncation.

What you should focus on is the function `serialize` modified in the cdr.h and cdr.cpp files.

**Comment by darbee** [comment]
> @darbee I compiled fastrtps on the aarch64 platform. According to what you said, I defined AARCH64, and then added "||defined(AARCH64)" to the location of the socket_ops.ipp file and the multicast.cpp file. Compile cyber again. RTPS_ERROR Error] Reader 1.f.0.3.e2.1d.0.0.0.0.0.0|0.0.4.4 cannot match write 1.f.0.3.c9.1d.0.0.0.0.0.0|0.0.3.3 -> Function PairingReader" Am I doing right? How can I solve this problem? Thank you.

If this change is not suitable for your situation, you can restore the original code first, because I did not test the situation under arm linux, so I am not sure that this modification will adapt to your platform, if there is any progress or problem, You can inform me in time.

**Comment by bssung** [comment]
Thanks! The patch works well.

**Comment by thymbahutymba** [comment]
Hi guys, I'm trying to run the same example on aarch64 using the r6.0.0 branch. Even though running the example on x86_64 works fine, on aarch64 the listener seems not to receive the message. The talker says that it has sent the message but in the listener log there is no trace of it. I tried to sniff the packets using wireshark and there isn't trace of it! I'm trying to run the talker and the listener on different containers using how it is explained on #7050. This approach on x86_64, as I said, works fine with correct communication between them. Could you help me?
