### ISSUE TITLE
Build error!

### ISSUE THREAD

**Issue by Jeffvvvv** [ApolloAuto/apollo#830]
I used google cloud platform to create a ubuntu 14.04 instance, and followed the installing instructions of README.md. But I got this error while building Apollo.sh:

Another issue also proposed the similar problems and said this is a proxy issue. I need to set the environmental variables(HTTP_PROXY, HTTPS_PROXY and NO_PROXY) properly.. But I am still not clear how to modify the environmental variables. Could anyone help me solve the issue or discuss it together~~

> System check passed. Build continue ...
apollo.sh: line 61: WORKSPACE: Permission denied
sed: couldn't open temporary file ./sed77haQl: Permission denied
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/calibration/lidar_ex_checker/BUILD:5:1: no such package '@vtk//': Expected directory at /usr/include/vtk-VTK_VERSION but it does not exist. and referenced by '//
modules/calibration/lidar_ex_checker:lidar_ex_checker_lib'
ERROR: Analysis of target '//modules/calibration/lidar_ex_checker:lidar_ex_checker' failed; build aborted
INFO: Elapsed time: 2.655s
FAILED: Build did NOT complete successfully (10 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 16 seconds

**Comment by xiaoxq** [comment]
Did you run it in docker container or directly on the 14.04 instance?

Actually you can use any Linux instance as long as it has docker installed properly. Just remember to work inside the docker container, always.

**Comment by xiaoxq** [comment]
This issue is closed as it becomes stale. Please file a new one if it's not figured out.
