### ISSUE TITLE
apollo 3.5 在cpu主频比较低时，camera帧率达不到30帧

### ISSUE THREAD

**Issue by zyffei** [ApolloAuto/apollo#8304]
1.apollo 3.5 使用IO_METHOD_MMAP启动camera,在cpu主频比较低的时候（如：800MHZ,1.2GHZ），摄像头帧率达不到30帧；当cpu主频提高（如2.6GHZ），帧率可以达到30帧；但如果使用IO_METHOD_USERPTR方式的话，cpu主频800MHZ都可以达到30帧；
2.如果使用apollo 2.5的版本试，cpu主频 800MHZ，IO_METHOD_MMAP方式，都可以达到30帧；

**Comment by kungeng** [comment]
@zyffei 测试时camera数目是多少？

**Comment by zyffei** [comment]
就测试一个camera的时候就可以出来,CPU主频只要比较低800Mhz,1.2G都可以复现； 
打印就是在UsbCam::poll 里面select驱动上来的数据达不到30，在15帧左右；cpu主频变化帧数也变化。

**Comment by kungeng** [comment]
我们之前观察到，在固定主频下，随着照相机数目的增加（从1个到5个相机），照相机帧率有显著降低。请你能否确定一下这个现象能否复现？谢谢！

**Comment by zyffei** [comment]
只使用一个摄像头就可以复现：
1.安装cpufrequtils
sudo apt-get install cpufrequtils
2.设置cpu主频，可以设置所有cpu主频到最低频率如： 1200000
sudo cpufreq-set -c [cpu] -g userspace -d 1200000 -u 1200000
例如有48个核可以使用如下命令：
for((i=0;i<48;i++));do sudo cpufreq-set -c $i -g userspace -d 1200000 -u 1200000;done

3.设置摄像头使用IO_METHOD_MMAP方式，用cyber_launch启动单个摄像头，帧率就差不多15帧；如果设置摄像头使用IO_METHOD_USERPTR方式，帧率都可以达到30；同样如果使用的是apollo 2.5也可以达到；

4.如果固定cpu主频到3G，帧率稳定达到30;

**Comment by zyffei** [comment]
可以使用cpufreq-info查看cpu的频率信息

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
