### ISSUE TITLE
Radar usage in perception module

### ISSUE THREAD

**Issue by mcmindcoder** [ApolloAuto/apollo#8328]
I noticed that among 3 input channels (lidar,camera,radar) the last one is discriminated a bit throughout perception module.

Here are 2 examples:
1. In probabilistic_fusion.pt config readar set as prohibition sensor
`prohibition_sensors: "radar_front"`
As a result **probabilistic_fusion.cpp** > **ProbabilisticFusion::CreateNewTracks** method is unable to create new tracks for radar provided objects.

Radar detects objects at longer distance. So it is the 1st sensor to see objects from far away. But it's unable to create a track unless object is picked up by other sensor. Could you tell what is the reason for that solution?

2. Inside **hm_tracks_objects_match.cpp** > **HMTrackersObjectsAssociation::Associate** there is a line
`bool do_nothing = (sensor_objects[0]->GetSensorId() == "radar_front")`
So objects from radar aren't matched with existing tracks. Feels like they are simply ignored.

Could you tell why is that so?

**Comment by techoe** [comment]
No. Radar is heavily used for velocity estimation in sensor fusion.

**Comment by mc-android-developer** [comment]
Hi @techoe Could you comment specifically on these 2 examples.
1. Why new tracks are not created based on radar readings?
2. Why not trying to match (do_nothing) with existing tracks when sensor is "radar_front"?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
