### ISSUE TITLE
Continental ARS 408 CAN总线接口协议

### ISSUE THREAD

**Issue by wxbbuaa2011** [ApolloAuto/apollo#8331]
想知道大陆408的接口协议，怎么解析出速度，距离等信息的?可以给开发费帮我实现下,。做过的联系下我，谢谢您帮下我。邮箱:wxbbuaa2011@163.com.

**Comment by gengqx** [comment]
在modules/drivers/radar/conti_radar 下已经有驱动了，无需再找人开发。

**Comment by wxbbuaa2011** [comment]
嗯嗯，好的，谢谢！

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Thank you for supporting Apollo!

**Comment by SnailWalkerYC** [comment]
> 在modules/drivers/radar/conti_radar 下已经有驱动了，无需再找人开发。

有没有类似于apollo/modules/tools/gen_vehicle_protocol 这种parser dbc文件的工具给RAS 408呢？

**Comment by 13940267943** [comment]
> 在modules/drivers/radar/conti_radar 下已经有驱动了，无需再找人开发。
您好，关于大陆４０８毫米波雷达的具体总线协议哪里找？
现在是数据得到了，但不知道具体位含义
