### ISSUE TITLE
[Important Announcement] Retiring Git LFS Service

### ISSUE THREAD

**Issue by Zhenni17** [ApolloAuto/apollo#8341]
Dear Apollo Developers,

Due to a fatal bug with Git LFS that has caused restricted access to Apollo repos, we have decided to retire the service from all Apollo repos. On May 14th 2:07 PM Pacific Time, the Apollo Team has completed the migration. We are sorry for any inconveniences this may cause you.

We have compiled a list of steps that you can take to avoid being affected by this change.
 
For those of you who have not made any local changes:

1. Disable LFS on your computer: 
       - git lfs uninstall

2. Sync with our most up-to-date Apollo repo: 
       - git pull — rebase upstream master where “upstream” is your defined alias of our Apollo repo

3. Hard reset your forked repo: - git push -f original master

For those who have made local changes but have not submitted the changes: 
1. Save your changes
2. Repeat the above steps 1 to 3
3. Re-apply the changes

For those who have local changes and have been submitted to your forked repo,
please cherry-pick those changes to the new repo and submit your commits.

Please note if your repo did not sync with ours, you will still be using the Git LFS service. However, once the service is disabled, there is a high likelihood that your access to Apollo repos will be blocked/denied. To avoid such an incident, please follow the steps listed above that best fit your situation.

If you are still experiencing issues, you can always re-fork the repo. Let us know if you need any assistance on this process by creating an issue. As always, we appreciate your support to the Apollo Project!

Best,
Apollo Team

**Comment by left4taco** [comment]
@Zhenni17 Could you list some references of the **fatal bug** for better traceability? Thanks.

**Comment by Zhenni17** [comment]
Hi @left4taco , the fatal bug would prevent us and external developers' access to our Apollo repos, so it was defined as a fatal bug. Hope that answered your question!

**Comment by left4taco** [comment]
@Zhenni17 Thanks for replying. But could you be more specific on that? Like what was the behavior of `git-lfs` before? How to reproduce the bug?

**Comment by natashadsouza** [comment]
@left4taco if you go through the previous issues, you will see many developers struggling to build Apollo due to how buggy GitLFS was. Also, a lot of new developers wrote to us about how they could not access our repo. Just search for Git LFS in the issues section. Thanks!

**Comment by Autofoxsys** [comment]
Hi,
The [quick-start guide to installing Apollo](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#Install-apollo-kernel) still says that you need to install Git LFS.
This is untrue, right?  Should this install guide be updated?

**Comment by xiaoxq** [comment]
> Hi,
> The [quick-start guide to installing Apollo](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md#Install-apollo-kernel) still says that you need to install Git LFS.
> This is untrue, right? Should this install guide be updated?

Thank you! Fixed with https://github.com/ApolloAuto/apollo/pull/10278.
