### ISSUE TITLE
E2E module poor performance and Bug

### ISSUE THREAD

**Issue by hongyuli** [ApolloAuto/apollo#835]
Hi, 

I trained the e2e/model_demo with its dataset, but the prediction accuracy on the testset is so bad. The relative error(error mean/ground truth mean) of both steering wheel angle/curvature prediction and acceleration prediction are more than 100%.

For the steering wheel curvature, the testset groundtruth mean is around 0.002066, but the prediction curvature mean is around 0.000644, which is in a different order.

For the acceleration, the testset groundtruth mean is around 15.319, but the prediction acceleration mean is around 0.2197, which is even worse.

Besides, I found one 'bug' in the 'run_model.py' for the acceleration prediction. During training, the input frames were normalized by 'img = cv2.imdecode(f[t][:], 1) / 127.5 - 1.0'. However, there is no normalization on the frames during prediction. The raw pixels are directly fed to RNN.

I'm wondering whether anyone has run this model before, and how good is your result.
The dataset I use is downloaded from Baidu Cloud, which is the 'End-to-End Demonstration Data'. This supposed to be the default dataset right?

Thanks.

Hongyu

**Comment by yanys1** [comment]
1. The focus of this open source is the data, so the code is to help developers quickly understand the open source data format and how to use the open source data. Follow-up we will continue to open our models and algorithms. Of course, you can make a pull request.
2. The demo code has be updated, and thanks  for your comment.
3. Baidu Cloud is the right data download link, the size is about 155G.

**Comment by hongyuli** [comment]
If you want to help developers to understand the dataset, you should improve your dataset documentation, but not provide such a useless model. You are not helping developers, but only misleading them and wasting their time.

Your dataset document does not have the formula to convert the curvatures to steering angles, and some data fields descriptions are also missing such as why you have four columns of curvatures.

Well, I do agree your current decision to delete this model. DO NOT waste other developer's time anymore.

**Comment by yanys1** [comment]
1. According to ackerman model, it can convert the curvature to steering angle.
2. In fact, the source collection data is GPS, the six curvatures are obtained by  interpolation operation and smooth method in preprocess.

**Comment by jinghaomiao** [comment]
E2E is only a research effort and we encourage developers to use it as a starting point for your own research purpose.
