### ISSUE TITLE
internet disconnected of LAN when the simulation runs

### ISSUE THREAD

**Issue by gvc0461082002** [ApolloAuto/apollo#8374]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:18.04
- **Apollo installed from (source)**:source
- **Apollo version (3.0 and 3.5)**:3.0 and 3.5,  

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
Hi All:
1. I followed the steps to build and launch demo, watch it via 8888, and everything works fine
2. the internet was disconnected, and everyone in our LAN (more than 30 persons) was offline during the period when I ran the simulation, whatever big loop or others.
3. I didn't have hardware, running the simulation only 
4. when I tried it at my home ( only 2 persons in a LAN), everything functioned well, without disconnection issue.

**Comment by natashadsouza** [comment]
@gvc0461082002 we have never seen this happen? Did it happen just that once?

**Comment by gvc0461082002** [comment]
> @gvc0461082002 we have never seen this happen? Did it happen just that once?

HI Natasha:
The problems happened since ubutnu16.04/apollo3.0
Actually, the bandwidth cost ranges from 20k to 40k , as displayed from system monitor.
I did use lsof-i to get all links details.
When I stopped the docker, usually there are more than 8 containers will be closed.
I am not sure the issues from communications among nodes.
Another finding is map loading of Navigation is fast at home while it's slow in the company's LAN.

**Comment by natashadsouza** [comment]
@gvc0461082002 I am not sure why this is happening on your end. It is not something that we face internally or something I have faced on an external network. Are you sure this is occurring due to Apollo and is not an external network issue?

**Comment by gvc0461082002** [comment]
Hi Natasha:
It could be a network issue not related to  ApolloAuto.
It hasn't been figured out by me now. But I like to this one closed.
The uploading rate rang from 30-50kib/s indicated by ksysguard under kde18.04, incuring
the jamming issue.


Cheers
Fenglu Ge




------------------ Original ------------------

**Comment by natashadsouza** [comment]
@gvc0461082002 sure I will close the issue. If you have any further questions, feel free to reopen it. Thanks!
