### ISSUE TITLE
dreamview: ERROR (spawn error)

### ISSUE THREAD

**Issue by JoelinChee** [ApolloAuto/apollo#8377]
Hi, everyone. 
I have successfully compiled the apollo by using 
bash apollo.sh build.
However, when I wanted to start apollo by using 
bash scripts/bootstrap.sh
There is one problem:

joelin@in_dev_docker:/apollo$ bash scripts/bootstrap.sh
Started supervisord with dev conf
Start roscore...
scripts/roscore.sh: line 28: /apollo/data/log/roscore.out: Permission denied
voice_detector: started
scripts/voice_detector.sh: line 28: /apollo/data/log/voice_detector.out: Permission denied
dreamview: ERROR (spawn error)

Does anyone know how to fix this problem.

I think it is maybe I have a docker containing apollo 3.5 in my PC
I also need one docker to have apollo 3.0.

**Comment by natashadsouza** [comment]
@JoelinChee I believe you are correct. It is because of multiple docker containers. Unfortunately this is not supported, but we have had developers run 2 instances before, please look up similar issue threads for support on how to do so. Thank you!

**Comment by mhzhou2021** [comment]
@JoelinChee sudo rm -rf /apollo/data/log
