### ISSUE TITLE
where is the fastrtps installation scripts in the dockerfile?

### ISSUE THREAD

**Issue by gouchaoer** [ApolloAuto/apollo#8383]
In `dev.x86_64.dockerfile` and `installers`, I can't find any scripts contains fast-rtps installations part.
But in the docker container, the fast-rtps in located in `/usr/local` path.
Is the official docker image built by the  `dev.x86_64.dockerfile` ?

**Comment by xiaoxq** [comment]
Plz check https://github.com/ApolloAuto/apollo/blob/master/docker/build/installers/install_fast-rtps.sh
