### ISSUE TITLE
cybertron how to subcrib the channels like lidar_points

### ISSUE THREAD

**Issue by debuleilei** [ApolloAuto/apollo#8384]
hello,I met a problem that after I get a library of cybertron and so on ,without docs about how to use it .then I try to  subcribe the velodyne's topic ,but I can't make it according to the apollo docs ,can you give me some details ……

**Comment by natashadsouza** [comment]
@debuleilei this is an internal library with restricted access. Do you mind contacting us via email: natashadsouza@baidu.com.
