### ISSUE TITLE
Cyber Log Should Publish Like ROS

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#8388]
One feature that I really liked in ROS is that the log command publishes to `/rosout` and `/rosout_agg`. This is useful for integration tests, data recording, and tooling. For example, a test tool could subscribe to this message and assert that there are no error messages. Also, this keeps all the log messages in the .record files. That way, only the .record files should be managed. Finally, there is a nice tool in ROS call rqt_console. It is a GUI that allows filtering of messages. Tailing files and using grep works too, but this tool is more beginner friendly.

I propose that each log message write to a topic like `/rosout`. It could be called `/cyberout`. There may be need for the `_out` for optimization. It's a little challenging to couple the logging and the publishing together, but it is much more powerful.

**Comment by baowanyu** [comment]
More developer tools are in our plans, but they are not yet open.

**Comment by natashadsouza** [comment]
@Fla3inH0tCheet0s thank you very much for your suggestion. As @baowanyu mentioned, there is definitely a trade off between CPU cost and efficient management of resources when using a logging service. It is something we are currently considering and will hopefully have a resolution soon. Thank you for your support and great suggestion.
