### ISSUE TITLE
cyber TimerComponent cleanup during shutdown

### ISSUE THREAD

**Issue by jilinzhou** [ApolloAuto/apollo#8391]
**Describe the bug**
1. There is a public member function Process() which seems never get called.

```
bool TimerComponent::Process() {
  if (is_shutdown_.load()) {
    return true;
  }
  return Proc();
}
```

2.  In Initialize() function, the task is added to the timing_wheel through member variable timer_. Notice in the callback function, ptr->Proc() is called instead of ptr->Process().

```
bool TimerComponent::Initialize(const TimerComponentConfig& config) {
  if (!config.has_name() || !config.has_interval()) {
    AERROR << "Missing required field in config file.";
    return false;
  }
  node_.reset(new Node(config.name()));
  LoadConfigFiles(config);
  if (!Init()) {
    return false;
  }

  std::weak_ptr<TimerComponent> self =
      std::dynamic_pointer_cast<TimerComponent>(shared_from_this());
  auto func = [self]() {
    auto ptr = self.lock();
    if (ptr) {
      ptr->Proc();
    }
  };
  timer_.reset(new Timer(config.interval(), func, false));
  timer_->Start();
  return true;
}
```
There is no corresponding timer_->Stop() call to remove the task from the timing_wheel.

3. During shutdown, there is potential memory faults because Proc() from the derived class can be called in the timing wheel. Note: The timing_wheel is a singleton instance (I am not sure when its destructor gets called during shutdown).

Possible Fix:

1. Stop the timer inside Process(), so the task will not be added to the timing_wheel again.

```
bool TimerComponent::Process() {
  if (is_shutdown_.load()) {
    timer_->Stop();
    return true;
  }
  return Proc();
}
```

2. In callback function, call ptr->Process() instead of ptr->Proc()

```
  std::weak_ptr<TimerComponent> self =
      std::dynamic_pointer_cast<TimerComponent>(shared_from_this());
  auto func = [self]() {
    auto ptr = self.lock();
    if (ptr) {
      ptr->Process();
    }
  };
```

Any comments will be appreciated.

**Comment by yaoweifeng01** [comment]
Thank you. The bug you said indeed exists. We will use ptr->Process() than ptr->Proc(). timer_->Stop() will be invoked duration timer_'s desctruction, so I think timer_->Stop() is not need to be invoked in Process

**Comment by quning18** [comment]
Please reopen if you have further questions.
