### ISSUE TITLE
cannot run cyber_visualizer

### ISSUE THREAD

**Issue by flnlucifer** [ApolloAuto/apollo#8405]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (Linux Ubuntu 16.04)
- **Apollo installed from (source)
- **Apollo version (3.5)

### Steps to reproduce the issue:
I install nvidia-docker out of docker and get the right nvidia info in docker. But I cannot run cyber_visualizer. 

![nvidia](https://user-images.githubusercontent.com/8034877/58001205-691fe500-7b0d-11e9-8fb9-7f06ee407ed0.png)

### Supporting materials (screenshots, command lines, code/script snippets):
tao@in_dev_docker:/apollo/cyber$ cyber_visualizer
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version

**Comment by fzd9752** [comment]
It's the problem of incomplete driver of openGL and Nvidia driver. Please refer to https://github.com/ApolloAuto/apollo/issues/6693 and https://github.com/ApolloAuto/apollo/issues/1832.

**Comment by flnlucifer** [comment]
> If you install nvidia driver inside docker by yourself, it could be the problem of incomplete driver of openGL and Nvidia driver. Please refer to #6693 and #1832.
> 
> I met same issue of this by using nvidia-docker2 to running apollo docker. Acoording to Nvidia-docker team [NVIDIA/nvidia-docker#534](https://github.com/NVIDIA/nvidia-docker/issues/534), nvidia docker 2 doesn't support OpenGL. You may downgrade from nvidia docker2 to 1.0 if you use nvidia docker. Otherwise, it needs us to install opengl mannually.

thx!

**Comment by natashadsouza** [comment]
@flnlucifer let us know if that resolved your issue. Thanks!

**Comment by flnlucifer** [comment]
> @flnlucifer let us know if that resolved your issue. Thanks!

no issue now. Thanks.

**Comment by wzjin2017** [comment]
> > @flnlucifer let us know if that resolved your issue. Thanks!
> 
> no issue now. Thanks.

Hi could you share the solution to this issue? I tried the one mentioned in #6693 but it didn't work. Thanks!
