### ISSUE TITLE
Routing not ready

### ISSUE THREAD

**Issue by yangydavid** [ApolloAuto/apollo#8439]
**Describe the bug**
We are using Apollo 3.5 version and running into some issues with the planning module. After
finishing a routing request. The console on the dreamview shows "Routing Success! ". However, the "planning.INFO" tells me the routing is not ready. The consequence is that although there is a red line shows up on the map (reference_line), no planning messages are being published.

**Comment by jmtao** [comment]
@yangydavid this is hard to diagnose the issue. send us the bag file if you still need help.

**Comment by jmtao** [comment]
Hi @yangydavid , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!

**Comment by Hershey988** [comment]
Hi @jmtao, I did what you suggested and whenever I request a route the planning module stops, but I can see the red line (routing)on the map.

**Comment by zhangs666** [comment]
> Hi @yangydavid , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.
> 
> Thank you for supporting Apollo!

hi,how to launch planning module manually from terminal?

**Comment by daohu527** [comment]
You can use `cyber_launch` to start mouldes.
```
cyber_launch start modules/planning/launch/planning.launch
```
