### ISSUE TITLE
GNSS Hardware adaptation of Apollo 3.0.

### ISSUE THREAD

**Issue by JustWannaHugU** [ApolloAuto/apollo#8452]
中文描述:
我是一名自动驾驶爱好者，最近在进行Apollo3.0的GPS的硬件适配工作，然后我遇到了一些问特地来求助各位Apollo布道师：
我从“https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_gps_receiver.md ” 这个网站中了解到“Apollo系统中默认使用Novatel 板卡”，但我使用的GPS和IMU均是价格比较低廉的国产设备，硬件适配的过程遇到了很多麻烦，我整理了如下几个问题，希望得到你们的帮助：
1.	如果想要成功将GPS和IMU适配到Apollo平台中，是否一定需要购买Novatel板卡呢？是不是说只有在使用Novatel板卡的基础上才能进行接下来的“添加新的GPS接受器”的四个步骤.吗？
2.	如果不使用Novatel板卡，我还可以完成Apollo的GNSS组合惯导适配工作吗？（将我现有的GPS和IMU设备成功Apollo的适配）？如果可以我应该怎么做。
3.	由于我使用的是国产的便宜IMU设备，因此为了进行IMU的适配工作我必须采用迂回策略，即先将我的国产IMU设备的原始数据格式转化成Novatel的IMU设备SPAN-IGM-A1的原始数据格式，然后就可以利用Apollo的数据处理和解析函数进行精确定位和姿态运算了；我目前遇到的问题是再尝试查阅了SPAN-IGM-A1™这款Apollo官方使用的IMU设备的说明书后，并未找到其输入到Apollo串口的原始数据格式，请问我能得到原始IMU数据格式吗？如果我不能或者没有权限得到SPAN-IGM-A1这款IMU的原始数据格式，那么我应该如何完成将我的国产IMU设备适配到Apollo平台呢?

English Description:
I'm a self-driving enthusiast. Now I've been working on Apollo3.0's GPS hardware adaptation and I had some questions from Apollo platform.I hope you could offer some help or give me some advice.Thank your in advance!
I learned from “The Default GPS receiver used in Apollo is Novatel cards. ” in this website of“https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_add_a_gps_receiver.md”
But I use cheaper sensors equipment made in China such as GPS and IMU.So,the process of hardware adaptation encountered a lot of trouble. I have sorted out the following questions and hope to get your help.
1.	If I want to successfully adapt GPS and IMU to Apollo platform, do I have to buy Novatel board card? Only Novatel board card can be used in the next four steps of "adding a new GPS receiver".
2.	2. If I don't use Novatel board card, can I finish Apollo's GNSS combined inertial navigation adaptation work? [will I successfully fit my existing GPS and IMU Apollo devices?] What should I do if I can?
3.	 Because I used homemade cheap IMU devices, therefore to carry out innovative adaptation work I have to use alternate strategy, which will be my first domestic company equipment raw data format into Novatel IMU equipment SPAN - IGM - A1 original data format, and then you can use of Apollo, data processing and analytical function for precise positioning and attitude; My current problem is to try to consult the SPAN - IGM - A1 ™ the Apollo, after the official use of innovative equipment specifications, did not find its input to the raw data format of the serial port of Apollo, I can get the original of IMU data format, please? If I can't or don't have permission to get the raw data format of the span-igm-a1 IMU, how can I complete the adaptation of my domestic IMU device to Apollo platform?

**Comment by JustWannaHugU** [comment]
Please divide the problem into localization module and I am looking forward to your reply!

**Comment by JustWannaHugU** [comment]
Anybody？

**Comment by ZhangJian322920** [comment]
Anybody can help us

**Comment by xmyqsh** [comment]
@JustWannaHugU @ZhangJian322920 
Apollo 好像有专门的技术支持团队，你可以通过Apollo官网联系到他们，进行合作。

如果自己做的话，首先，硬件设备不一样，驱动肯定得重写。
其次，定位是最为关键的技术之一，我建议，针对自己的设备，重写localization中闭源部分代码，并根据自己设备的特性，适配算法，适配参数。这样，一方面可以发挥硬件的最大性能，另一方面，对算法细节的把控也是安全的保证。
最后，不同的应用场景，对设备的成本，精度的要求，都不一样。不要拿着锤子找钉子，要在成本、精度、算法之间做权衡。

**Comment by JustWannaHugU** [comment]
> @JustWannaHugU @ZhangJian322920
> Apollo 好像有专门的技术支持团队，你可以通过Apollo官网联系到他们，进行合作。
> 
> 如果自己做的话，首先，硬件设备不一样，驱动肯定得重写。
> 其次，定位是最为关键的技术之一，我建议，针对自己的设备，重写localization中闭源部分代码，并根据自己设备的特性，适配算法，适配参数。这样，一方面可以发挥硬件的最大性能，另一方面，对算法细节的把控也是安全的保证。
> 最后，不同的应用场景，对设备的成本，精度的要求，都不一样。不要拿着锤子找钉子，要在成本、精度、算法之间做权衡。

感谢回复，目前已经放弃使用国产设备，花大价钱买了国外设备，不得不说。
