### ISSUE TITLE
Cannot connect to localhost:8887

### ISSUE THREAD

**Issue by Xin0711** [ApolloAuto/apollo#846]
We try to run the offline demo, but we can not connect to localhost server when the HMI is running.

> Start HMI ros bridge...
> HMI is running at http://localhost:8887
> d-172-25-98-147:apollo-master xin$ bash docker/scripts/release_into.sh
> xin@in_release_docker:/apollo$ 
> xin@in_release_docker:/apollo$ rosbag play docs/demo_guide/demo.bag --loop
> /tmp/apollo-platform/ros/ros_comm/rosbag/src/player.cpp:125 Player::publish() [ INFO] [1508960345.916072695]: Opening docs/demo_guide/demo.bag
> 
> Waiting 0.2 seconds after advertising topics... done.
> 
> Hit space to toggle paused, or 's' to step.
>  [RUNNING]  Bag Time: 1497125292.440853   Duration : 23.298373 / 38.393816

**Comment by xiaoxq** [comment]
Are you visiting HMI on the same host machine?
It should be <apollo_host_ip>:8887 instead of localhost:8887 if you are not on the localhost.

BTW, could you also post the content of data/log/hmi.out?

**Comment by xiaoxq** [comment]
HMI on port 8887 has been retired. We have integrated it into Dreamview which runs on port 8888.

Thanks.
