### ISSUE TITLE
dreamview 地图问题

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#8464]
dreamview 显示的地图文件在哪里？

**Comment by HongyiSun** [comment]
There is a global gflag named `map_dir` to set your map directory, which has default as: `/apollo/modules/map/data/<map_name>`

**Comment by daohu527** [comment]
Seems to be resolved, we will close this issue. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
