### ISSUE TITLE
How to use simulation time in Cyber?

### ISSUE THREAD

**Issue by xmyqsh** [ApolloAuto/apollo#8469]
I'm moving from ros to cyber.
What's the similar method in cyber that corresponding to `/clock` topic used in [Simulation Time](http://wiki.ros.org/Clock#Using_Simulation_Time_from_the_.2BAC8-clock_Topic) in ros?

**Comment by from-wind** [comment]
Thank you for your attension. We Planned to add this, but it's not Scheduled.

**Comment by xmyqsh** [comment]
@from-wind Thanks for your immediate reply. Look forward.
