### ISSUE TITLE
cyber example

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#8470]
i can't run the  example -- listener.
the error info as below:
I0523 18:32:28.248347 12705 shm_dispatcher.cc:60]  [DEBUG] Reading sharedmem message: channel/chatter from block: 2
E0523 18:32:28.248370 12705 segment.cc:233]  get shm failed.
E0523 18:32:28.248389 12705 segment.cc:85]  init failed, can't read now.
W0523 18:32:28.248400 12705 shm_dispatcher.cc:66]  fail to acquire block, channel: channel/chatter index: 2

someone knows?

**Comment by from-wind** [comment]
Hi, can you reinsatall your docker?  The example run well in my envirionment.

**Comment by ctwfei** [comment]
It seems that the creation of shared memory failed. Can you provide the corresponding talker log？
Thanks you.

**Comment by quning18** [comment]
Please reopen if you still have problems on this. @wanggujin
