### ISSUE TITLE
A graph visualizer for relationships between nodes

### ISSUE THREAD

**Issue by bongjoonhyun** [ApolloAuto/apollo#8475]
Hi Baidu Apollo Team,

I'm a newbie here.

I'm trying to understand the Apollo system, and the first thing I want to know is the relationship between nodes; there are readers and writers and communicating with each other by passing messages.

I'm wondering if there a tool for drawing a graph to visualize such relationships.

I can find one in ROS, but I'm not sure Baidu Apollo has similar features.

Thanks!

**Comment by from-wind** [comment]
Hi, Thank you for your attention. You can use cyber_monitor to find the channel's reader and writer

**Comment by bongjoonhyun** [comment]
Thanks! I tried to use cyber_visualizer but it led me to this issue #8565

**Comment by quning18** [comment]
@bongjoonhyun visualizer is for sensor visualization, not topology. 

We have both cyber_node and cyber_monitor which help you understand the topology, but we don't have the visualization tool for now.

Please reopen if you have further questions.
