### ISSUE TITLE
Question about Component::Proc function

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#8491]
How can i trigger the Proc function, such as Localization component ?

**Comment by zhangchaoltt** [comment]
Hi, @wanggujin you can read this example, the CommonComponentSample component subscribes message from channel /apollo/prediction，which is in common.dag. When the message arrives，it will trigger the proc func.
 https://github.com/ApolloAuto/apollo/tree/master/cyber/examples/common_component_example

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
