### ISSUE TITLE
question about load map base_map.bin

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#8500]
I0524 18:10:56.148994  9978 hdmap.cc:24]  Loading HDMap: /apollo/modules/map/data/sunnyvale_big_loop/base_map.bin ...
E0524 18:10:57.397356  9978 hdmap_common.cc:175]  lane[id = id: "2652_1_-1"
]. sampled_left_width_[0.787094] is too small. It should be larger than half vehicle width[1.05].

this is why?

**Comment by ycool** [comment]
It means lane 2652_1_-1 is too narrow for a vehicle. but it is ok for other obstacles.
