### ISSUE TITLE
Connect to PC running Cyber outside local segment 

### ISSUE THREAD

**Issue by krishnatoshniwal** [ApolloAuto/apollo#8507]
When referring to #7050, I came across a note saying that the IP of two systems must be in the same local segment.   
However, is it possible to connect to an IP which is just outside the local segment, for example connecting a 192.168.1.1 to 192.168.2.1. Is there any changes that I can do to the code so that the pc outside the local segment can be discovered as well?

I've also confirmed that both tcp and udp communication can be established using netstat.

**Comment by daohu527** [comment]
If you want to support service auto-discovery, it must be on the same network segment, or you can set the subnet mask and try
