### ISSUE TITLE
Cannot set property default of #<Object> which has only a getter

### ISSUE THREAD

**Issue by sol-idsnake** [ApolloAuto/apollo#8513]
After updating apollo to the latest version (2.6) with apollo-boost (0.4), next-with-apollo (3.4), react (16.8.6), and next (8.1) I get the following error when compiling:

`Cannot set property default of #<Object> which has only a getter`

The trace-stack says it's coming from _app.js, when declaring:

`<ApolloProvider client={apollo}>`

> [ error ] TypeError: Cannot set property default of #<Object> which has only a getter
>    at Object.<anonymous> (Z:\frontend\node_modules\apollo-boost\lib\bundle.cjs.js:158:17)
>    at Module._compile (internal/modules/cjs/loader.js:701:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>    at Module.load (internal/modules/cjs/loader.js:600:32)
>    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
>    at Module.require (internal/modules/cjs/loader.js:637:17)
>    at require (internal/modules/cjs/helpers.js:22:18)
>    at Object.apollo-boost (Z:\frontend\.next\server\static\development\pages\_app.js:1409:18)
>    at __webpack_require__ (Z:\frontend\.next\server\static\development\pages\_app.js:23:31)
>    at Module../lib/withData.js (Z:\frontend\.next\server\static\development\pages\_app.js:334:70)
>    at __webpack_require__ (Z:\frontend\.next\server\static\development\pages\_app.js:23:31)
>    at Module../pages/_app.js (Z:\frontend\.next\server\static\development\pages\_app.js:1274:72)
>    at __webpack_require__ (Z:\frontend\.next\server\static\development\pages\_app.js:23:31)
>    at Object.0 (Z:\frontend\.next\server\static\development\pages\_app.js:1397:18)
>    at __webpack_require__ (Z:\frontend\.next\server\static\development\pages\_app.js:23:31)

### System information

- **Windows 10 Pro**

### Steps to reproduce the issue:

>    "dependencies": {
>        "@babel/core": "^7.4.5",
>        "apollo-boost": "^0.4.0",
>        "apollo-client": "^2.6.0",
>        "graphql": "^14.3.1",
>        "graphql-tag": "^2.10.1",
>        "next": "^8.1.0",
>        "next-with-apollo": "^3.4.0",
>        "react": "^16.8.6",
>        "react-adopt": "^0.6.0",
>        "react-apollo": "^2.5.6",
>        "react-dom": "^16.8.6",
>    },

with the command `npm run dev`:
> "dev": "next -p 7777",

**Comment by wiesys** [comment]
I have the same issue. Did you figured it out?
