### ISSUE TITLE
Error while running planning module using "cyber_launch"

### ISSUE THREAD

**Issue by zezhang** [ApolloAuto/apollo#8515]
platform: ubuntu 18.04+apollo 3.5
module: planning
issue:
I use "`bash apollo.sh build_cpu`" command to build the apollo3.5. The build was successful without any error message. However, when I try to launch the individual planning module using the command: "`cyber_launch start modules/planning/launch/planning.launch`", I got the following error messages:
![1](https://user-images.githubusercontent.com/14190932/58375555-b217d500-7f23-11e9-934a-c872b30542d7.png)

Please note that other modules (e.g. control module), was able to run successfully using the same method.

Any help would be appreciated.

**Comment by quning18** [comment]
@zezhang seems libplanning_component is missing from the log, have you double checked if the so is in there?

**Comment by zezhang** [comment]
Yes. The file is under the specified directory. It looks the libadolc.so.2 is missing, but I'm not sure where does this library come from. I don't think it's related to Apollo since I can compile everything successfully.

**Comment by yaoweifeng01** [comment]
@zezhang  Maybe libadolc.so.2 is missing, I think there is a problem with the docker environment. Can I find this file? "/local/adolc/lib64/libadolc.so.2 ."

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!
