### ISSUE TITLE
I can't start dreamview

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#8516]
computer: intel core i3
os: ubuntu 16.04   64 bit
have installed nvidia driver
but can't start dreamview
log as follows:
[.....monitor_manager.cc:52] No HMIStatus was received

that's why???

**Comment by natashadsouza** [comment]
@wanggujin could you post your terminal error messages here?
Also, which version of Apollo are you working on?

**Comment by wanggujin** [comment]
> @wanggujin could you post your terminal error messages here?
> Also, which version of Apollo are you working on?

apollo 3.5

**Comment by natashadsouza** [comment]
@wanggujin we would need a screenshot of your error messages. Thanks!

**Comment by unacao** [comment]
and what do you mean by cannot start dreamview? Did the output of './script/bootstrap.sh' tell you there is a core dump, or the webpage is blank when you visit 'localhost:8888'?

**Comment by xiaoxiaosanyuan** [comment]
@unacao excuse me, when I visit 'localhost:8888' the webpage is blank, what should I do then?thanks!

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
