### ISSUE TITLE
MAP: Map integration in Apollo 3.0

### ISSUE THREAD

**Issue by warden2018** [ApolloAuto/apollo#8517]
### System information

- **OS Platform and Distribution ( Linux Ubuntu 14.04)**
- **Apollo installed from (source)**
- **Apollo version (3.0)**

### Steps to reproduce the issue:
- **With the base_map.bin I tried to generate routing_map and sim_map. which is described in READMe file: modules/map/data/README.md. But the default_end_way_point.txt file I am not sure what should be in it. **
-**I create folder in modules/map/data/demo_1/ (In docker container). After bootstrap the dreamview can select the demo_1 map but I can not see my map content in dreamview which is good for Sunnyvale Loop after I choose Sunnyvale Loop..**
- **I record localization(RTK method) point cloud, image data and all the other data in the base_map zone.**
![Screenshot from 2019-05-27 10:56:25](https://user-images.githubusercontent.com/48422255/58392773-2a8aad00-806e-11e9-994f-55a62081adbd.png)
So questions for map integration:
- **How to fill in the default_end_way_point.txt**
- **How to validate my map is available in Apollo system**
- **There are other files in example map data folder as shown below. I don't know what are they for.**
![Screenshot from 2019-05-27 11:15:04](https://user-images.githubusercontent.com/48422255/58393295-bbfb1e80-8070-11e9-92e0-2243228177ed.png)

So any one can help me with MAP integration? Waiting for your kind reply.

**Comment by ycool** [comment]
default_end_way_point.txt defines some POI for easier usage. Its proto is defined at https://github.com/ApolloAuto/apollo/blob/master/modules/routing/proto/poi.proto. You can create an empty file if you don't need any POI.
