### ISSUE TITLE
apollo_r1.0.0: bash apollo.sh build error dreamview not work

### ISSUE THREAD

**Issue by qcqcc** [ApolloAuto/apollo#8520]
WARNING: Running Bazel server needs to be killed, because the startup options are different.
INFO: Found 190 targets...
ERROR: /apollo/modules/control/tools/BUILD:19:1: Linking of rule '//modules/control/tools:enter_auto_mode' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-dbg/bin/modules/control/tools/enter_auto_mode -Lbazel-out/local-dbg/bin/_solib_k8/_U_S_Sthird_Uparty_Sros_Cros_Ucommon___Uthird_Uparty_Sros_Slib ... (remaining 10 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
modules/control/tools/enter_auto_mode.cc:100: error: undefined reference to 'ros::init(int&, char**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
third_party/ros/include/ros/publisher.h:107: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
third_party/ros/include/ros/publisher.h:107: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
third_party/ros/include/ros/publisher.h:107: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
third_party/ros/include/ros/publisher.h:113: error: undefined reference to 'ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ros::console::levels::Level)'
modules/common/adapters/adapter_manager.cc:49: error: undefined reference to 'ros::NodeHandle::NodeHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 18.971s, Critical Path: 6.72s
============================
[ERROR] Build failed!
[INFO] Took 57.017 seconds
============================

++++++++++++++++++++++++env.txt++++++++++++++++++++++++++++
in_dev_docker
+ echo 'Inside docker'
Inside docker
+ uname -a
Linux in_dev_docker 4.4.32-apollo-1-NonRT-RT #2 SMP PREEMPT RT Fri May 10 23:07:17 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
+ pip list
actionlib (1.11.5)
aniso8601 (1.2.1)
argparse (1.2.1)
bondpy (1.7.19)
catkin (0.6.19)
catkin-pkg (0.4.12)
catkin-pkg-modules (0.4.12)
certifi (2017.4.17)
chardet (3.0.4)
click (6.7)
colorama (0.2.5)
cryptography (1.2.3)
decorator (3.4.0)
docutils (0.11)
dynamic-reconfigure (1.5.48)
empy (3.1)
enum-compat (0.0.2)
enum34 (1.1.6)
eventlet (0.21.0)
Flask (0.12.2)
Flask-RESTful (0.3.5)
Flask-SocketIO (2.8.6)
futures (3.1.1)
gencpp (0.5.5)
genlisp (0.4.15)
genmsg (0.5.8)
genpy (0.5.10)
glog (0.3.1)
google-apputils (0.4.2)
greenlet (0.4.12)
grpc (0.3-19)
grpcio (1.3.5)
grpcio-tools (1.3.5)
html5lib (0.999)
idna (2.5)
ipaddress (1.0.16)
itsdangerous (0.24)
Jinja2 (2.9.6)
MarkupSafe (1.0)
matplotlib (1.3.1)
message-filters (1.11.21)
msgpack-python (0.4.8)
ndg-httpsclient (0.4.0)
nose (1.3.1)
numpy (1.12.1)
Pillow (2.3.0)
pip (1.5.4)
pluginlib (1.10.5)
protobuf (3.1.0)
pyasn1 (0.1.9)
pycurl (7.19.3)
Pygments (1.6)
pyOpenSSL (0.15.1)
pyparsing (2.0.1)
pyserial (3.3)
Pyste (0.9.10)
python-apt (0.9.3.5ubuntu2)
python-dateutil (1.5)
python-engineio (1.5.4)
python-gflags (3.1.1)
python-socketio (1.7.5)
pytz (2012c)
PyYAML (3.12)
requests (2.18.1)
roman (2.0.0)
rosbag (1.11.21)
rosboost-cfg (1.11.14)
rosclean (1.11.14)
roscreate (1.11.14)
rosgraph (1.11.21)
roslaunch (1.11.21)
roslib (1.11.14)
roslz4 (1.11.21)
rosmake (1.11.14)
rosmaster (1.11.21)
rosmsg (1.11.21)
rosnode (1.11.21)
rosparam (1.11.21)
rospbconvertor (1.0.0)
rospkg (1.1.1)
rospy (1.11.21)
rosservice (1.11.21)
rostest (1.11.21)
rostopic (1.11.21)
rosunit (1.11.14)
roswtf (1.11.21)
scipy (0.13.3)
sensor-msgs (1.11.9)
setuptools (3.3)
six (1.10.0)
smclib (1.7.19)
tf (1.11.8)
tf-conversions (1.11.8)
tf2-geometry-msgs (0.5.13)
tf2-kdl (0.5.13)
tf2-py (0.5.13)
tf2-ros (0.5.13)
tf2-sensor-msgs (0.5.13)
urllib3 (1.21.1)
Werkzeug (0.12.2)
wheel (0.24.0)
wsgiref (0.1.2)
+ echo -----------env---------------
-----------env---------------
+ env
HOSTNAME=in_dev_docker
TERM=xterm
ROS_ROOT=/apollo/third_party/ros/share/ros
ROS_PACKAGE_PATH=/apollo/third_party/ros/share:/apollo/third_party/ros/stacks:/apollo/third_party/ros_x86_64/share:/apollo/third_party/ros_x86_64/stacks
ROS_MASTER_URI=http://localhost:11311
APOLLO_BIN_PREFIX=/apollo/bazel-bin
USER=apple
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/apollo/third_party/ros/lib:/apollo/third_party/ros_x86_64/lib
APOLLO_IN_DOCKER=true
CPATH=/apollo/third_party/ros/include:/apollo/third_party/ros_x86_64/include
PATH=/apollo/third_party/ros/bin:/apollo/third_party/ros_x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ROS_DOMAIN_ID=55781777
PWD=/apollo
ROSLISP_PACKAGE_DIRECTORIES=
DOCKER_USER=apple
DOCKER_USER_ID=1001
HOME=/home/apple
SHLVL=2
ROS_DISTRO=indigo
PYTHONPATH=/apollo/bazel-genfiles:/apollo/third_party/ros/lib/python2.7/dist-packages:/apollo/third_party/ros_x86_64/lib/python2.7/dist-packages
DEBIAN_FRONTEND=noninteractive
LESSOPEN=| /usr/bin/lesspipe %s
PKG_CONFIG_PATH=/apollo/third_party/ros/lib/pkgconfig:/apollo/third_party/ros_x86_64/lib/pkgconfig
DISPLAY=localhost:10.0
CMAKE_PREFIX_PATH=/apollo/third_party/ros:/apollo/third_party/ros_x86_64
LESSCLOSE=/usr/bin/lesspipe %s %s
ROS_ETC_DIR=/apollo/third_party/ros/etc/ros
_=/usr/bin/env

**Comment by natashadsouza** [comment]
@qcqcc could you give us your system config to help debug better?

**Comment by qcqcc** [comment]
Thank you for your reply.
thank you very much.

apollo version:r1.0.0
uname -a:
Linux in_dev_docker 4.4.32-apollo-1-NonRT-RT #2 SMP PREEMPT RT Fri May 10 23:07:17 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

apollo-platform ros build succeed


============================
[ OK ] Build ros succeed!
============================`



I added configuration to WORKSPACE:

New_local_repository（

Name = ros,

Build_file = third_party/ros.BUILD,

Path = "/ home / TMP / ros"

)
now, apollo.sh build passed.

`root@in_dev_docker:/apollo# sudo bash apollo.sh build
[WARNING] ESD CAN library supplied by ESD Electronics does not exit.
[WARNING] If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md
.
____Loading package: modules/decision/common
____Loading package: modules/perception/proto
____Loading package: modules/canbus/tools
____Loading package: modules/control/filters
____Loading package: modules/control/common
____Loading package: modules/hmi/utils
____Loading package: modules/localization/proto
____Loading package: modules/common/monitor
____Loading package: third_party/ros_aarch64
____Loading package: modules/common/monitor/proto
____Loading package: modules/hmi/proto
____Loading package: modules/localization/rtk
____Loading package: modules/control/proto
____Loading package: modules/dreamview/proto
____Loading package: modules/decision/proto
____Loading package: third_party/can_card_library/esd_can
____Loading package: modules/common/adapters/proto
____Loading package: @google_styleguide//
____Loading package: @com_github_google_protobuf//
____Loading package: @curlpp//
____Loading package: @glog//
____Loading package: @gtest//
____Loading package: @com_github_grpc_grpc//
____Loading package: @civetweb//
____Loading package: @websocketpp//
____Loading package: @eigen//
Building on x86_64, with targets:
//tools/platforms:x86_64
//tools/platforms:aarch64
//modules/prediction:prediction
//modules/prediction:prediction_lib
//modules/prediction/common:prediction_common
//modules/planning/conf:planning_trajectory_adapter_manager_config
//modules/planning:planning_testdata
//modules/planning:planning
//modules/planning:lib_planning
//modules/planning/planner:lib_planner
//modules/planning/common:lib_planning_common
//modules/perception:perception
//modules/perception/conf:perception_adapter_manager_config
//modules/perception:perception_lib
//modules/perception/common:perception_common
//modules/monitor/common:platform_common_lib
//modules/monitor/common:interface
//modules/localization/proto:localization_config_proto_pylib
//modules/localization/proto:imu_proto_pylib
//modules/localization/proto:gps_proto_pylib
//modules/localization/proto:camera_proto_pylib
//modules/localization/proto:camera_parameter_proto_pylib
//modules/localization:localization
//modules/localization/conf:localization_adapter_manager_config
//modules/localization:localization_app
//modules/localization/rtk:rtk_localization
//modules/localization/camera:camera_localization
//modules/localization/proto:localization_config_proto
//modules/localization/proto:localization_config_proto.pb
//modules/localization/proto:camera_parameter_proto
//modules/localization/proto:camera_parameter_proto.pb
//modules/localization:localization_base
//modules/hmi/ros_node:ros_node_service
//modules/hmi/proto:runtime_status_proto_pylib
//modules/hmi/proto:ros_node_proto_pylib
//modules/hmi/proto:ros_node_proto
//modules/hmi/proto:ros_node_proto.pb
//modules/hmi/proto:config_proto_pylib
//modules/dreamview/proto:simulation_world_proto_pylib
//modules/planning/proto:planning_proto_pylib
//modules/localization/proto:localization_proto_pylib
//modules/localization/proto:pose_proto_pylib
//modules/dreamview/conf:dreamview_adapter_manager_config
//modules/dreamview:dreamview
//modules/dreamview/backend:backend
//modules/dreamview/backend:websocket
//modules/dreamview/backend:simulation_world_service
//modules/dreamview/backend:trajectory_point_collector
//modules/dreamview/proto:simulation_world_proto
//modules/dreamview/proto:simulation_world_proto.pb
//modules/dreamview:frontend
//modules/decision/proto:decision_proto_pylib
//modules/prediction/proto:prediction_proto_pylib
//modules/perception/proto:perception_proto_pylib
//modules/decision/conf:localization_adapter_manager_config
//modules/decision:decision
//modules/decision:lib_decision
//modules/decision/common:decision_common
//modules/control/tools:pad_terminal
//modules/control/tools:enter_auto_mode
//modules/control/tools:control_tester
//modules/control/proto:control_proto_pylib
//modules/control/integration_tests:control_test_base
//modules/control/filters:filters
//modules/control:lib_pad_terminal
//modules/control:control_testdata
//modules/control:control
//modules/control:lib_control
//modules/control/controller:controller
//modules/control/controller:controller_agent
//modules/control/controller:lon_controller
//modules/control/controller:lat_controller
//modules/control/filters:mean_filter
//modules/control/filters:digital_filter
//modules/control/filters:digital_filter_coefficients
//modules/control/controller:controller_interface
//modules/control/common:common
//modules/control/common:trajectory_analyzer
//modules/control/common:pid_controller
//modules/control/common:interpolation_2d
//modules/control/common:hysteresis_filter
//modules/control/common:control_gflags
//modules/control/common:base_types
//modules/control/common:definitions
//modules/localization:localization_testdata
//modules/common/vehicle_state:vehicle_state
//modules/localization/common:localization_common
//modules/common/util/testing:simple_proto
//modules/common/util/testing:simple_proto.pb
//modules/common/proto:gnss_status_proto
//modules/common/proto:gnss_status_proto.pb
//modules/common/monitor/proto:monitor_proto_pylib
//modules/common/configs/proto:vehicle_config_proto_pylib
//modules/common/configs:vehicle_config_helper
//modules/common/data:vehicle_config_data
//modules/common/configs/proto:vehicle_config_proto
//modules/common/configs/proto:vehicle_config_proto.pb
//modules/common/configs:config_gflags
//modules/common/adapters/proto:adapter_config_proto_pylib
//modules/canbus/tools:teleop
//modules/canbus/tools:canbus_tester
//modules/canbus/proto:canbus_proto_pylib
//modules/common/proto:common_proto_pylib
//modules/canbus/can_client:can_client_tool
//modules/canbus:canbus_testdata
//modules/canbus:canbus
//modules/canbus:canbus_lib
//modules/common/monitor:monitor
//modules/common/adapters:adapter_manager
//modules/common/adapters/proto:adapter_config_proto
//modules/common/adapters/proto:adapter_config_proto.pb
//modules/common/adapters:message_adapters
//modules/planning/proto:planning_proto
//modules/planning/proto:planning_proto.pb
//modules/localization/proto:localization_proto
//modules/localization/proto:localization_proto.pb
//modules/localization/proto:imu_proto
//modules/localization/proto:imu_proto.pb
//modules/localization/proto:gps_proto
//modules/localization/proto:gps_proto.pb
//modules/localization/proto:camera_proto
//modules/localization/proto:pose_proto
//modules/localization/proto:pose_proto.pb
//modules/localization/proto:camera_proto.pb
//modules/decision/proto:decision_proto
//modules/prediction/proto:prediction_proto
//modules/prediction/proto:prediction_proto.pb
//modules/perception/proto:perception_proto
//modules/perception/proto:perception_proto.pb
//modules/decision/proto:decision_proto.pb
//modules/common/monitor/proto:monitor_proto
//modules/common/monitor/proto:monitor_proto.pb
//modules/common/adapters:adapter
//modules/common/adapters:adapter_gflags
//modules/common:apollo_app
//modules/hmi/utils:hmi_status_helper
//modules/hmi/utils:restful_client
//modules/hmi/proto:runtime_status_proto
//modules/hmi/proto:runtime_status_proto.pb
//modules/common/status:status
//modules/canbus/vehicle:vehicle_factory
//modules/canbus/vehicle:lincoln_vehicle_factory
//modules/canbus/vehicle/lincoln:lincoln_controller
//modules/canbus/vehicle/lincoln:lincoln_message_manager
//modules/canbus/vehicle/lincoln/protocol:canbus_lincoln_protocol
//modules/canbus/vehicle:abstract_vehicle_factory
//modules/canbus/vehicle:vehicle_controller_base
//modules/canbus/can_comm:can_sender
//modules/canbus/can_comm:can_receiver
//modules/canbus/vehicle:message_manager_base
//modules/control/proto:control_proto
//modules/control/proto:control_proto.pb
//modules/canbus/can_client:can_client_factory
//modules/common/util:factory
//modules/canbus/can_client/fake:fake_can_client
//modules/canbus/can_client:can_client
//modules/common/util:util
//modules/common/time:time
//modules/common/math:math
//modules/common/math:search
//modules/common/math:quaternion
//modules/common/math:lqr
//modules/common/math:linear_interpolation
//modules/common/math:kalman_filter
//modules/common/math:matrix_operations
//modules/common/math:integral
//modules/common/math:euler_angles_zxy
//modules/common/math:box2d
//modules/common/math:polygon2d
//modules/common/math:line_segment2d
//modules/common/math:angle
//modules/common/math:sin_table
//modules/common/math:aaboxkdtree2d
//modules/common/math:aabox2d
//modules/common/math:math_utils
//modules/common/math:vec2d
//modules/canbus/common:canbus_common
//modules/canbus/proto:canbus_proto
//modules/common/proto:common_proto
//modules/common/proto:header_proto
//modules/common/proto:header_proto.pb
//modules/common/proto:error_code_proto
//modules/common/proto:error_code_proto.pb
//modules/common/proto:common_proto.pb
//modules/common:common
//modules/common:macro
//modules/common:log
//modules/canbus/proto:canbus_proto.pb
//:x86_64
//:arm64
===================hualidefengexian====================================
WARNING: Running Bazel server needs to be killed, because the startup options are different.
INFO: Found 190 targets...
INFO: Elapsed time: 366.306s, Critical Path: 250.55s
============================install/ros_x86_64
[ OK ] Build passed!
[INFO] Took 404.839 seconds`

**But dreamview doesn't work properly**

`root@in_dev_docker:/apollo# sudo bash scripts/dreamview.sh start_fe
/apollo/bazel-bin/modules/dreamview/dreamview: symbol lookup error: /apollo/third_party/ros/lib/librosconsole_log4cxx.so: undefined symbol: _ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_
root@in_dev_docker:/apollo# sudo bash scripts/bootstrap.sh 
Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888
root@in_dev_docker:/apollo# sudo bash scripts/hmi.sh       
Start roscore...
HMI ros node service running at localhost:8887
HMI running at http://localhost:8887
`

symbol lookup error: /apollo/third_party/ros/lib/librosconsole_log4cxx.so: undefined symbol: _ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_

In response to this error, I reinstalled apr-1.5.1, apr-unit-1.5.3, log4cxx-0.10.0, but it was still unresolved.

find .|xargs grep -ri "_ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_"
Binary file. / liblog4cxx. so.10.0.0 matches can be found in apollo_release, but liblog4cxx. so.10.0.0 matches cannot be found in apollo_dev.

help me!

**Comment by natashadsouza** [comment]
@qcqcc When you say dreamview does not work correctly, are you seeing an issue in your terminal or in your browser? Also, we do have a guide to [debug the dreamview issue](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md)

**Comment by qcqcc** [comment]
Thank you for your help.

When running this command：
sudo bash scripts/bootstrap.sh

Output at the terminal：
`
Start roscore...
Started supervisord with dev conf
Dreamview is running at http://localhost:8888
`

Output at the data/log/dreamview.out：
`
/apollo/bazel-bin/modules/dreamview/dreamview: error while loading shared libraries: libfastcdr.so: cannot open shared object file: No such file or directory
`

ldd /apollo/bazel-bin/modules/dreamview/dreamview

`
linux-vdso.so.1 =>  (0x00007ffd245b3000)
	libcpp_common.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/libcpp_common.so (0x00007f55da345000)
	**libfastcdr.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/libfastcdr.so (0x00007f55da135000)**
	libfastrtps.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/libfastrtps.so (0x00007f55d9da4000)
	librosconsole.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/librosconsole.so (0x00007f55d9b75000)
	librosconsole_backend_interface.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/librosconsole_backend_interface.so (0x00007f55d9973000)
	librosconsole_log4cxx.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/librosconsole_log4cxx.so (0x00007f55d975e000)
	librosconsole_print.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/librosconsole_print.so (0x00007f55d955b000)
	libroscpp.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/libroscpp.so (0x00007f55d9139000)
	libroscpp_serialization.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/libroscpp_serialization.so (0x00007f55d8f35000)
	librostime.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/librostime.so (0x00007f55d8d09000)
	libxmlrpcpp.so => /apollo/apollo-platform/ros/install/ros_x86_64/lib/libxmlrpcpp.so (0x00007f55d8ae7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f55d88c3000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f55d86bf000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f55d84a2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f55d829d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f55d7f1b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f55d7c12000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f55d79fb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55d7631000)
	/lib64/ld-linux-x86-64.so.2 (0x00005613e0636000)
	libconsole_bridge.so.0.2 => /usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.2 (0x00007f55d742c000)
	liblog4cxx.so.10 => /usr/local/lib/liblog4cxx.so.10 (0x00007f55d7048000)
	libboost_regex.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0 (0x00007f55d6d40000)
	libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007f55d6b19000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f55d6901000)
	libyaml-cpp.so.0.5 => /usr/lib/x86_64-linux-gnu/libyaml-cpp.so.0.5 (0x00007f55d6684000)
	libaprutil-1.so.0 => /usr/local/apr-util/lib/libaprutil-1.so.0 (0x00007f55d645d000)
	libapr-1.so.0 => /usr/local/apr/lib/libapr-1.so.0 (0x00007f55d622a000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f55d5dc7000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f55d5a33000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f55d5808000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f55d55d0000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f55d53cb000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f55d3913000)
`

ll /apollo/apollo-platform/ros/install/ros_x86_64/lib/libfastcdr.so
`
-rw-r--r-- 1 root root 81468 May 29 17:56 /apollo/apollo-platform/ros/install/ros_x86_64/lib/libfastcdr.so
`

This file exists.

I try to use GDB
gdb --args /apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/dreamview.conf

Once gdb is launched, press r and enter key to run, if dreamview crashes, then get the backtrace with bt.

`
Starting program: /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/dreamview/dreamview --flagfile=/apollo/modules/dreamview/conf/.conf
warning: Error disabling address space randomization: Operation not permitted
/root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/dreamview/dreamview: symbol lookup error: /apollo/third_party/ros/lib/librosconsxx.so: undefined symbol: _ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_
During startup program exited with code 127.

`


Is there any problem with my operation?

thank you!

**Comment by qcqcc** [comment]
Has no friend ever encountered this problem?

help me

thanks

**Comment by luqiang21** [comment]
@qcqcc I am just guessing. You should not use `sudo` to run `bootstrap.sh`. If you cannot run it without `sudo`. Then probably you ran `dev_start.sh` using `sudo` which is incorrect. If that is the case, you should follow instructions on docker website to add your user group.

**Comment by ycool** [comment]
You can try it again in the latest master code. Thanks.
