### ISSUE TITLE
lidar cnnseg question

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#8526]
In apollo 3.5 lidar cnnseg module, this function:

```c++
void CNNSegmentation::MapPointToGrid(const pcl_util::PointCloudPtr &pc_ptr) {
  float inv_res_x = 0.5f * static_cast<float>(width_) / range_;
  float inv_res_y = 0.5 * static_cast<float>(height_) / range_;
  point2grid_.assign(pc_ptr->size(), -1);
  int pos_x = -1;
  int pos_y = -1;
  for (size_t i = 0; i < pc_ptr->size(); ++i) {
    const auto &pt = pc_ptr->at(i);
    if (pt.z <= min_height_ || pt.z >= max_height_) {
      continue;
    }
    // the coordinates of x and y are exchanged here
    // (row <-> x, column <-> y)
    // int pos_x = F2I(pt.y, range_, inv_res_x);  // col
    // int pos_y = F2I(pt.x, range_, inv_res_y);  // row
    // 2018.6.21, switch to axis rotated projection
   GroupPc2Pixel(pt.x, pt.y, inv_res_x, range_, &pos_x, &pos_y);
    if (pos_y < 0 || pos_y >= height_ || pos_x < 0 || pos_x >= width_) {
      continue;
    }
    point2grid_[i] = pos_y * width_ + pos_x;
  }
}

```
compare the previous version, there are slightly differences (which is using the comment line codes). When I try using the master branch changes of:

```
GroupPc2Pixel
```
I got all the out `point2grid_` is `-1`. But using the old lines of codes, result were normal. Here is my question:

1. why did this changes and what it is using for?
2. why the result is all -1?

**Comment by owphoo** [comment]
I guess the points are rotated 45 degrees. So more points in front of  the car can be processed by the cnn. The car can see further.
![image](https://user-images.githubusercontent.com/12474260/58445570-bb758d00-812f-11e9-8cc7-d6c1b4052ead.png)

**Comment by jinfagang** [comment]
@owphoo  Thanks, I got almost same result as previous process now.
