### ISSUE TITLE
Is there sensor data in demo_3.5.record?

### ISSUE THREAD

**Issue by yfzm** [ApolloAuto/apollo#8531]
When I use `cyber_record` command to replay `demo_3.5.record`, `cyber_monitor` shows no sensor data created. The FrameRatio of `/apollo/sensor/camera/front_6mm`, `/apollo/sensor/lidar16/compensator/PointCloud2` and some other channels are 0.

So when I launched perception module separately, no obstacle data were published because of the missing input sensor data. Where can I find the sensor data?

### System information

- **OS Platform and Distribution**: Ubuntu16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version**: 3.5

### Steps to reproduce the issue:

- build apollo and launch dreamview
- `cyber_record play -f demo_3.5.record -l`
- `cyber_monitor`

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/21277160/58452044-76118980-8148-11e9-8bb8-ab6d16cdc929.png)

**Comment by natashadsouza** [comment]
@yfzm you are correct, the demo record does not contain any sensor data.

**Comment by yfzm** [comment]
@natashadsouza Thank you for your reply.

I found sensor data at [data open platform](http://data.apollo.auto/). Is there any tutorials about how to use it in apollo 3.5?

PS: I have tried to use some data set of the platform:
- **Vehicle System Demo Data**: it still doesn't contains any camera data.
- **Calibrate Demo Data**: when I use `rosbag_to_record` to convert the format, it reports `Error: the input file is not a ros bag file`.

**Comment by githublefantian** [comment]
Please provide  sensor data you downloaded.

**Comment by githublefantian** [comment]
@yfzm  Please provide sensor data that you downloaded.

**Comment by yfzm** [comment]
I downloaded data from the **Demonstration Data** part of [Apollo Data Open Platform](http://data.apollo.auto/).

![image](https://user-images.githubusercontent.com/21277160/58692137-8df34280-83c0-11e9-9e3e-86cbb636f7ed.png)

And I downloaded **Vehicle System Demo Data** of version 2.0: `demo-sensor-data-apollo-2.0.tar.gz`

**Comment by baowanyu** [comment]
You can try conversion tool "rosbag_to_record" from document below.
https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md

**Comment by yfzm** [comment]
Hello, @baowanyu. I have tried to use `rosbag_to_record`, and it worked fine with **Vehicle System Demo Data**. But it reported error when converting **Calibrate Demo Data**: `Error: the input file is not a ros bag file.` When I dig into it, the origin exception is `BagIOException` in `bag.cpp`.

```c++
void Bag::readVersion() {
    string version_line = file_.getline();

    file_header_pos_ = file_.getOffset();

    char logtypename[100];
    int version_major, version_minor;
#if defined(_MSC_VER)
    if (sscanf_s(version_line.c_str(), "#ROS%s V%d.%d", logtypename, sizeof(logtypename), &version_major, &version_minor) != 3)
#else
    if (sscanf(version_line.c_str(), "#ROS%99s V%d.%d", logtypename, &version_major, &version_minor) != 3)
#endif
        throw BagIOException("Error reading version line");

    version_ = version_major * 100 + version_minor;

    logDebug("Read VERSION: version=%d", version_);
}
```

**Comment by baowanyu** [comment]
The bag demo-calibrator-data-apollo-1.5.bag maybe is not a valid rosbag.

@natashadsouza  Please assign relevant personnel to deal with it.


```
caros@computing:~$ rosbag info demo-calibrator-data-apollo-1.5.bag
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosbag", line 35, in <module>
    rosbag.rosbagmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbag/rosbag_main.py", line 883, in rosbagmain
    cmds[cmd](argv[2:])
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbag/rosbag_main.py", line 156, in info_cmd
    b = Bag(arg, 'r', skip_index=not options.freq)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbag/bag.py", line 173, in __init__
    self._open(f, mode, allow_unindexed)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbag/bag.py", line 1096, in _open
    if   mode == 'r': self._open_read(f, allow_unindexed)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbag/bag.py", line 1124, in _open_read
    self._version = self._read_version()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosbag/bag.py", line 1232, in _read_version
    version_line = self._file.readline().rstrip().decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

**Comment by quning18** [comment]
Please reopen if you have further questions. @yfzm
