### ISSUE TITLE
why we removed camera based localization in modules localization

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#855]
I see "It is replaced by modules/elo' in comment.

I think,  putting camera localization in modules/localization is better than put in it in  modules/elo 

and elo is just some .so files or some special roads map files and elo can not be used by other users.

so why we remove camera localization source code and add elo modules?

**Comment by startcode** [comment]
We agree that they are both localization modules. But we will re-organize and update them.
 
   modules/elo is more of a standalone binary library. In the future, we may instead provide a download link for this library. 

   modules/localization/ will be the place for all the configurable, open-source localization methods.
