### ISSUE TITLE
Perception Traffic light detection: Cannot transform frame: world to frame novatel

### ISSUE THREAD

**Issue by warden2018** [ApolloAuto/apollo#8551]
### System information

- **OS Platform Linux Ubuntu 14.04**:
- **Apollo installed from (source)**:
- **Apollo version (3.0)**:

### Steps to reproduce the issue:
- **My dag file is below:**
```
subnode_config {
    subnodes {
        id: 41
        name: "TLPreprocessorSubnode"
        type: SUBNODE_IN
    }
   
    subnodes {
        id: 42
        name: "TLProcSubnode"
        type: SUBNODE_OUT
    }
}
edge_config {
    edges {
        id: 201
        from_node: 41
        to_node: 42
        events {
            id: 1003
            name: "traffic_light"
        }
    }
}

data_config {
    datas {
        id: 3
        name: "TLPreprocessingData"
    }
    datas {
        id: 4
        name: "SceneSharedData"
    }
}
```

- **My rosbag and Map have the same region and Map can be visualized in dreamview.**
- **When I launch perception module the ERROR log shows:**
`E0529 15:45:33.271072  4423 tl_preprocessor_subnode.cc:293] TLPreprocessorSubnode failed to query pose ts:1558511727.247526884
E0529 15:45:33.271096  4423 tl_preprocessor_subnode.cc:264] camera_selection failed to get car pose, ts:1558511727.247526884
E0529 15:45:33.291450  4421 transform_input.cc:69] Cannot transform frame: world to frame novatel , err: Lookup would require extrapolation into the past.  Requested time 1558511727.208761930 but the earliest data is at time 1558511754.990000010, when looking up transform from frame [novatel] to frame [world]. canTransform returned after 0.0201707 timeout was 0.02.. Frames: Frame long_camera exists with parent short_camera.
Frame short_camera exists with parent velodyne64.
Frame velodyne64 exists with parent novatel.
Frame radar exists with parent short_camera.
Frame radar_front exists with parent velodyne64.
Frame novatel exists with parent world.
Frame velodyne16 exists with parent novatel.
Frame localization exists with parent world.
Frame left_front_frame exists with parent novatel.
Frame right_front_frame exists with parent novatel.
Frame left_rear_frame exists with parent novatel.
Frame right_rear_frame exists with parent novatel.`
- **I checked my /tf topoic: it contains localization to world(parent frame) and novatel to world(parent frame)**
- **I checked my /tf_static topoic: it contains a tf tree shown below:**
![webwxgetmsgimg](https://user-images.githubusercontent.com/48422255/58599574-75493680-82b3-11e9-8fb2-3efdf830fb67.jpeg)
- **The error occurs in TLPreprocessorSubnode::GetSignals: GetCarPose. **
- **So the root cause is the tf tree? If so is there an easy way to build/manage the tf tree? Because we have four velodyne on one car.**

**Comment by warden2018** [comment]
I think I found something:
I double checked the /tf_static(which includes all the sensor and novatel's rotation and translation relation). 
`@in_dev_docker:/apollo$ rostopic hz /tf_static 
/use_sim_time is not set, will not subscribe to simulated time [/clock] topic
subscribed to [/tf_static]
average rate: 5998.290

	min: 0.000s max: 0.000s std dev: 0.00005s window: 5
average rate: 6.232

	min: 0.000s max: 0.962s std dev: 0.35844s window: 7

no new messages

no new messages

no new messages

no new messages
`
So I am thinking I must make sure all the transform relationship must be published in a certain frequency . So is there any module to manage it or just distributed into different modules? Hope for your reply.

**Comment by techoe** [comment]
Yes tf should be provided faster (more than twice is optimal) than the most frequently publishing sensor data.

**Comment by warden2018** [comment]
Thanks for your answer. @techoe

**Comment by MengWangTHU** [comment]
@warden2018 @techoe something similar happened when I do run the perception_trafficlight.launch； Here is the problem i met.

>  E0719 09:41:26.117420  6858 trafficlights_perception_component.cc:702] [perception] Can not find transform. 1563426872.721496 frame_id: world child_frame_id: novatel Error info: canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.
[perception_trafficlights]  E0719 09:41:26.117487  6858 trafficlights_perception_component.cc:662] [perception] get pose from tf failed, child_frame_id: novatel

Your conversation seems to let me find the direction. I want to know how to set the provided faster (more than twice is optimal) than the most frequently publishing sensor data?  
Thank you very much.

**Comment by warden2018** [comment]
@MengWangTHU Hi! Currently I am using Apollo 3.0 and your system seems higher than 3.5. As far as I know, there is tf manager module in Apollo 3.5 and you can locate the issue there. Try to check the necessary information(calibration result for example).

**Comment by qilinhu** [comment]
@MengWangTHU hi!
I met the same problem as you. Have you solved this error.
E0719 09:41:26.117420 6858 trafficlights_perception_component.cc:702] [perception] Can not find transform. 1563426872.721496 frame_id: world child_frame_id: novatel Error info: canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.canTransform: target_frame world does not exist.
[perception_trafficlights] E0719 09:41:26.117487 6858 trafficlights_perception_component.cc:662] [perception] get pose from tf failed, child_frame_id: novatel

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.

**Comment by pedram-mohajer** [comment]
anybody can solve this problem?
