### ISSUE TITLE
why need traffic_light_unprotected_left(right)_turn_scenario

### ISSUE THREAD

**Issue by DinnerHowe** [ApolloAuto/apollo#8559]
hi, there.
i'm so confused about why need a traffic_light_unprotected_left(right)_turn_scenario mode here.
for instance if there is a light in cross, traffic rule will solve the problem; otherwise, if there is no light any more in cross, you don't need to do anything about traffic light

**Comment by HongyiSun** [comment]
For example, a green light with a left arrow on it, it's a protected left turn, which means we have the right of way. As we are protected and theoretically don't need to consider anyone else.(Actually we will avoid if anyone is running the red light).
But when we turn left on a junction with only solid green light without an arrow, we have to yield the right of way to an oncoming car if they are going straight. In this case, we are considered as unprotected left turn.

**Comment by rrenjie** [comment]
> For example, a green light with a left arrow on it, it's a protected left turn, which means we have the right of way. As we are protected and theoretically don't need to consider anyone else.(Actually we will avoid if anyone is running the red light).
> But when we turn left on a junction with only solid green light without an arrow, we have to yield the right of way to an oncoming car if they are going straight. In this case, we are considered as unprotected left turn.

@HongyiSun  As you mentioned even if for protected left turns you have to consider vehicles running the red light, then I wonder what exactly the difference is for the planning algorithm if there is protection or not? What I mean is, you have to yield oncoming cars (even if they are running the red light) no matter there is protection or not.

**Comment by DinnerHowe** [comment]
> > For example, a green light with a left arrow on it, it's a protected left turn, which means we have the right of way. As we are protected and theoretically don't need to consider anyone else.(Actually we will avoid if anyone is running the red light).
> > But when we turn left on a junction with only solid green light without an arrow, we have to yield the right of way to an oncoming car if they are going straight. In this case, we are considered as unprotected left turn.
> 
> @HongyiSun As you mentioned even if for protected left turns you have to consider vehicles running the red light, then I wonder what exactly the difference is for the planning algorithm if there is protection or not? What I mean is, you have to yield oncoming cars (even if they are running the red light) no matter there is protection or not.

@rrenjie bingo that's the point, you got me

**Comment by jmtao** [comment]
@DinnerHowe the reason we have different scenarios here is just because they have to run in different stages or be implemented in different way in some stage.
we have **protected**_turn vs **unprotected**_turn because in unprotected_turn scenario(s), we'll have a stage of "creep".
We have unprotected_**right**_turn vs unprotected_**left**_turn because we'll have different implementation to handle creep stage for right and left turn respectively.  For right turn, we'll creep out of stop line of the intersection, for left turn, we'll need creep further. 

A scenario is basically a sequence of stages.  That's how we decide if a scenario is needed to handle a driving situation.

**Comment by DinnerHowe** [comment]
> @DinnerHowe the reason we have different scenarios here is just because they have to run in different stages or be implemented in different way in some stage.
> we have protected_turn vs unprotected_turn because in unprotected_turn scenario(s), we'll have a stage of "creep".
> We have unprotected_right_turn vs unprotected_left_turn because we'll have different implementation to handle creep stage for right and left turn respectively. For right turn, we'll creep out of stop line of the intersection, for left turn, we'll need creep further.
> 
> A scenario is basically a sequence of stages. That's how we decide if a scenario is needed to handle a driving situation.

i known creep action, which is another part I'm not quit understand, will, let's discuss that later.
however, here, my question is why split traffic light into two parts, if we do same aciton in trafficlight junction. 
as you said, wether protected or not, ego would cross stop line, yield dangers and moving slowly, why we put this issue together making it to a general case, through defining scenario?

**Comment by natashadsouza** [comment]
@DinnerHowe even for a human driver, the behavior in an unprotected and protected left turn is different. When you have a Protected turn, you scan the road for a possibility of an oncoming vehicle that has overshot the light but can still drive out normally as you "assume" that people generally follow the rule. 
But in an unprotected turn, you are yielding to oncoming traffic, which means you creep forward slowly until the lane is completely safe to cross,  sometimes you will need to creep until the very last lane to then exit the junction, but in protected, once you have scanned the roads and are clear of doubt, you no longer creep but can drive the rest of the junction smoothly.
Let me know if you have questions.

**Comment by jmtao** [comment]
Hi @DinnerHowe , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
