### ISSUE TITLE
Can't run cyber_visualizer

### ISSUE THREAD

**Issue by bongjoonhyun** [ApolloAuto/apollo#8565]
Hi,

I tried to run cyber_visualizer by following docs in [Apollo Cyber RT Developer Tools](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md).

After hit cyber_visualizer in the docker environment, it says libGL error: failed to load driver: swrast.

I tried to follow suggestions in #8405 but neither of them could solve my problem.

I found all libgl libraries are pointing to the correct .so library.

I'm using Ubuntu 14.04 and followed the exact instruction given by the Apollo team.

**Comment by yaoweifeng01** [comment]
@bongjoonhyun Please refer to #8405 first to check if the graphics card and driver are ready.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions.
