### ISSUE TITLE
Planning: lane change with SLT graph and obstacle filter

### ISSUE THREAD

**Issue by Junzeng-x14** [ApolloAuto/apollo#8576]
I would like to ask some questions about lane change implementation the path planning. It looks like a SLT-graph is used for the path planning, but I'm confused about the lateral distance changes in function of time between two lanes. Uniformly? Didn't understand very clearly from the existing code.

Moreover, how is the moving obstacle avoidance considered during the lane change with SLT-graph. It looks like some obstacle filtering happens around it.

Thank for your help in advance.

**Comment by JasonZhou404** [comment]
1. SL graph is based on a single lane frenet frame rather than two lanes.
2. Moving obstacles only in ST graph.

**Comment by Junzeng-x14** [comment]
I see, actually always project moving obstacles into the reference line.

**Comment by jmtao** [comment]
Hi @Junzeng-x14 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
