### ISSUE TITLE
cyber inner channle cant get all message

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#8620]
**Describe the bug**
I am implementing a visualizer of sensor& fusion object.
So I created a component  to listen on two channles ,
1st receive prefused_frame  from radar componet
2nd receive fusion_frame frome fusion component 
So the data flow is like this:
radar  ->  fusion  -> visualizer
    |                                 
    |-----------------> visualizer

The Radar componet is continuing sending frames and fusion component can receive all the frames. 
BUT, the visualizer can only receive very few radar frames .(while fusion frames are all received exactly)
It seems many radar frames droped or the queue overflowed?

**Expected behavior**
The visualizer can receive all frmae sent by radar component.

the code is build on 14.04 based on the latest apollo master branch

**Comment by cicelprg** [comment]
> **Describe the bug**
> I am implementing a visualizer of sensor& fusion object.
> So I created a component to listen on two channles ,
> 1st receive prefused_frame from radar componet
> 2nd receive fusion_frame frome fusion component
> So the data flow is like this:
> radar -> fusion -> visualizer
> |
> |-----------------> visualizer
> 
> The Radar componet is continuing sending frames and fusion component can receive all the frames.
> BUT, the visualizer can only receive very few radar frames .(while fusion frames are all received exactly)
> It seems many radar frames droped or the queue overflowed?
> 
> **Expected behavior**
> The visualizer can receive all frmae sent by radar component.
> 
> the code is build on 14.04 based on the latest apollo master branch

Thank you for your question.

The fusion component can receive all the radars data and the visualizer receive few fusion frames，that is data lose `fusion -> visualizer`.  There are two possible types of data loss:

1. the fusion component drop some frames 。
2. the visualizer processing speed is slower than fusion sending speed

So，add some auxiliary logs in proc function maybe solve this problem.

**Comment by quning18** [comment]
Could you show us the code how your component listens the two channels? @sinopec

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
