### ISSUE TITLE
what's the mean about obstacle's theta in module perception?

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#8633]
apollo 3.5
what's the mean about obstacle's theta in module perception? 
is it a angle between east direction?

**Comment by KaWaiTsoiBaidu** [comment]
@wanggujin  could you specify which theta are you referring to by quoting the line of code here?

**Comment by wanggujin** [comment]
> @wanggujin could you specify which theta are you referring to by quoting the line of code here?

message PerceptionObstacle {
  optional int32 id = 1;  // obstacle ID.

  // obstacle position in the world coordinate system.
  optional common.Point3D position = 2;

  optional double theta = 3;  // heading in the world coordinate system.
  optional common.Point3D velocity = 4;  // obstacle velocity.
}

**Comment by KaWaiTsoiBaidu** [comment]
@wanggujin   As the comment stated, it should be the object heading direction in the world coordinated system.   The world coordinate system is x --> east, y --> north, z --> up.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by daohu527** [comment]
@KaWaiTsoiBaidu 
Is it angle or radians? It seems like **radians** but not angle. Could you pls help to check that. Aslo Which side does it rotate to?
