### ISSUE TITLE
Debug the new module on apollo

### ISSUE THREAD

**Issue by JoelinChee** [ApolloAuto/apollo#8637]
I create a new module called sysctrl on apollo.
I am trying to debug this module by the script dev_start_gdb_server.sh.
I have changed the launch.json and tasks.json.
However I found that it cannot stop when I set the breakpoint.
The following are the code and the process.
![Screenshot from 2019-06-04 12:07:52](https://user-images.githubusercontent.com/18168467/58852578-b2556480-86c9-11e9-9160-425d7b4275ca.png)

Does anyone know where the problem are?

**Comment by Prj1508** [comment]
I am also facing similar problem in debugging perception/radar module. Appreciate any suggestion

**Comment by Hongmin2018** [comment]
Maybe this is for GDB setting,  when received SIGINT, it cannot stop.

**Comment by Avps1** [comment]
Has anyone solved this problem?
I have the exact same problem while debugging the perception module - https://github.com/ApolloAuto/apollo/issues/11107

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
