### ISSUE TITLE
multichannle component msg process 

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#8639]
If a component resigter more than 1 channles ,How the diffrent channle msg is  handled?
If the snder frequenry is different, how the 2 channles sync the msg Proc?
Speciallly when 1 channle  send msg frequently and anthoer never send msg, It seems that the Proc Function will not be called!  Is This a bug? OR it just wokr like this?

**Comment by sinopec** [comment]
OK, I check the cyber source code ,And I found that all channle must have message to let the callback func called....
So it's a feature not a bug ..... Right?

**Comment by cicelprg** [comment]
> OK, I check the cyber source code ,And I found that all channle must have message to let the callback func called....
> So it's a feature not a bug ..... Right?


Thank you for your question.

The multichannle component proc function trigger through the first channel，when the first channel data arrive，Cyber-Rt will chose other channel newest data，then call the component proc function。

**Comment by sinopec** [comment]
> > OK, I check the cyber source code ,And I found that all channle must have message to let the callback func called....
> > So it's a feature not a bug ..... Right?
> 
> Thank you for your question.
> 
> The multichannle component proc function trigger through the first channel，when the first channel data arrive，Cyber-Rt will chose other channel newest data，then call the component proc function。

Thanks for your reply.. But still one more problem, when other channle has no data yet , the Proc process will be pending even if the first channle has many new messages. So maybe this canbe improved.

**Comment by xmyqsh** [comment]
@sinopec Other channels will cache a date queue with a timestamp.  Each time Cyber-Rt will choose other channels' newest data. If there is no data published from other channels or data in other channels has been time out, you should check your data publisher logic in the specific channels, enlarge the time out threshold, or check the whole logic.

**Comment by quning18** [comment]
Please reopen if you have further questions @sinopec
