### ISSUE TITLE
Running Apollo 3.5 with Nvidia  Quadro M2200.

### ISSUE THREAD

**Issue by leFeuilluZer** [ApolloAuto/apollo#8641]
Hi Apollo support, 

I uses a  Nvidia  Quadro M2200 on my machine, when I run Apollo (3.5) with the attached demo bag, everything works well but now I would link to run it in the LGSVL simulator (https://github.com/lgsvl/simulator). 
Firstly the perception module doesn't want to switch on and when I force it using 

> $ ./scripts/perception.sh start_fe 

I have this message error : 

`[cyber_launch_6413] INFO Stop cyber launch finished. [cyber_launch_6413] INFO cyber_launch exit. cyber_launch stop /apollo/modules/perception/production/launch/perception_all.launch [cyber_launch_6421] INFO Stop cyber launch finished. [cyber_launch_6421] INFO cyber_launch exit. cyber_launch stop /apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch [cyber_launch_6425] INFO Stop cyber launch finished. [cyber_launch_6425] INFO cyber_launch exit. cyber_launch stop /apollo/modules/transform/launch/static_transform.launch cyber_launch start /apollo/modules/transform/launch/static_transform.launch & cyber_launch start /apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch & cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch & morgiazzi@in_dev_docker:/apollo$ [cyber_launch_6429] INFO Launch file [/apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch] [cyber_launch_6429] INFO ======================================================================================================================== [cyber_launch_6430] INFO Launch file [/apollo/modules/perception/production/launch/perception_all.launch] [cyber_launch_6430] INFO ======================================================================================================================== [cyber_launch_6429] INFO Load module [image_decompress] library: [mainboard_default_6429] [CYBER_DEFAULT] conf: [/apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag] exception_handler: [] [cyber_launch_6430] INFO Load module [perception] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception.dag] exception_handler: [] [cyber_launch_6429] INFO Start process [mainboard_default_6429] successfully. pid: 6432 [cyber_launch_6429] INFO ------------------------------------------------------------------------------------------------------------------------ [cyber_launch_6428] INFO Launch file [/apollo/modules/transform/launch/static_transform.launch] [cyber_launch_6428] INFO ======================================================================================================================== [cyber_launch_6428] INFO Load module [static_transform] library: [mainboard_default_6428] [CYBER_DEFAULT] conf: [/apollo/modules/transform/dag/static_transform.dag] exception_handler: [] [cyber_launch_6430] INFO Start process [perception] successfully. pid: 6431 [cyber_launch_6430] INFO ------------------------------------------------------------------------------------------------------------------------ [cyber_launch_6430] INFO Load module [perception_camera] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: [] [cyber_launch_6430] INFO Load module [perception_traffic_light] library: [perception_trafficlights] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag] exception_handler: [] [cyber_launch_6430] INFO Start process [perception_trafficlights] successfully. pid: 6436 [cyber_launch_6430] INFO ------------------------------------------------------------------------------------------------------------------------ [cyber_launch_6428] INFO Start process [mainboard_default_6428] successfully. pid: 6434 [cyber_launch_6428] INFO ------------------------------------------------------------------------------------------------------------------------ [perception: WARNING: Logging before InitGoogleLogging() is written to STDERR] perception: WARNING: Logging before InitGoogleLogging() is written to STDERR [perception: I0531 16:35:54.378098 6431 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT ] perception: I0531 16:35:54.378098 6431 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT [perception: I0531 16:35:54.378859 6431 global_data.cc:150] [] host ip: 10.240.9.52] perception: I0531 16:35:54.378859 6431 global_data.cc:150] [] host ip: 10.240.9.52 [perception: I0531 16:35:54.379588 6431 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception, has 2 dag conf] perception: I0531 16:35:54.379588 6431 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception, has 2 dag conf [perception: I0531 16:35:54.379598 6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception.dag] perception: I0531 16:35:54.379598 6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception.dag [perception: I0531 16:35:54.379601 6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] perception: I0531 16:35:54.379601 6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag [mainboard_default_6429: WARNING: Logging before InitGoogleLogging() is written to STDERR] mainboard_default_6429: WARNING: Logging before InitGoogleLogging() is written to STDERR [mainboard_default_6429: I0531 16:35:54.390566 6432 module_argument.cc:85] [] command: mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_6429 -s CYBER_DEFAULT ] mainboard_default_6429: I0531 16:35:54.390566 6432 module_argument.cc:85] [] command: mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_6429 -s CYBER_DEFAULT [mainboard_default_6429: I0531 16:35:54.391083 6432 global_data.cc:150] [] host ip: 10.240.9.52] mainboard_default_6429: I0531 16:35:54.391083 6432 global_data.cc:150] [] host ip: 10.240.9.52 [mainboard_default_6429: I0531 16:35:54.391752 6432 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6429, has 1 dag conf] mainboard_default_6429: I0531 16:35:54.391752 6432 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6429, has 1 dag conf [mainboard_default_6429: I0531 16:35:54.391765 6432 module_argument.cc:64] [] dag_conf: /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag] mainboard_default_6429: I0531 16:35:54.391765 6432 module_argument.cc:64] [] dag_conf: /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag [mainboard_default_6428: WARNING: Logging before InitGoogleLogging() is written to STDERR] mainboard_default_6428: WARNING: Logging before InitGoogleLogging() is written to STDERR [mainboard_default_6428: I0531 16:35:54.419993 6434 module_argument.cc:85] [] command: mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_6428 -s CYBER_DEFAULT ] mainboard_default_6428: I0531 16:35:54.419993 6434 module_argument.cc:85] [] command: mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_6428 -s CYBER_DEFAULT [mainboard_default_6428: I0531 16:35:54.421075 6434 global_data.cc:150] [] host ip: 10.240.9.52] mainboard_default_6428: I0531 16:35:54.421075 6434 global_data.cc:150] [] host ip: 10.240.9.52 [mainboard_default_6428: I0531 16:35:54.421875 6434 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6428, has 1 dag conf] mainboard_default_6428: I0531 16:35:54.421875 6434 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6428, has 1 dag conf [mainboard_default_6428: I0531 16:35:54.422260 6434 module_argument.cc:64] [] dag_conf: /apollo/modules/transform/dag/static_transform.dag] mainboard_default_6428: I0531 16:35:54.422260 6434 module_argument.cc:64] [] dag_conf: /apollo/modules/transform/dag/static_transform.dag [perception_trafficlights: WARNING: Logging before InitGoogleLogging() is written to STDERR] perception_trafficlights: WARNING: Logging before InitGoogleLogging() is written to STDERR [perception_trafficlights: I0531 16:35:54.425750 6436 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT ] perception_trafficlights: I0531 16:35:54.425750 6436 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT [perception_trafficlights: I0531 16:35:54.426244 6436 global_data.cc:150] [] host ip: 10.240.9.52] perception_trafficlights: I0531 16:35:54.426244 6436 global_data.cc:150] [] host ip: 10.240.9.52 [perception_trafficlights: I0531 16:35:54.426865 6436 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception_trafficlights, has 1 dag conf] perception_trafficlights: I0531 16:35:54.426865 6436 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception_trafficlights, has 1 dag conf [perception_trafficlights: I0531 16:35:54.426877 6436 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag] perception_trafficlights: I0531 16:35:54.426877 6436 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag [mainboard_default_6428: E0531 16:35:54.519428 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_up_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519428 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_up_novatel_extrinsics.yaml [mainboard_default_6428: E0531 16:35:54.519486 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519486 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_novatel_extrinsics.yaml [mainboard_default_6428: E0531 16:35:54.519510 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_left_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519510 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_left_novatel_extrinsics.yaml [mainboard_default_6428: E0531 16:35:54.519528 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_right_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519528 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_right_novatel_extrinsics.yaml [mainboard_default_6428: E0531 16:35:54.529289 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/perception/data/params/radar_rear_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.529289 6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/perception/data/params/radar_rear_extrinsics.yaml [mainboard_default_6429: E0531 16:35:54.853380 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_6mm_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853380 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_6mm_decompress], please ensure that each node has a unique name. [mainboard_default_6429: E0531 16:35:54.853554 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_12mm_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853554 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_12mm_decompress], please ensure that each node has a unique name. [mainboard_default_6429: E0531 16:35:54.853622 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_left_fisheye_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853622 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_left_fisheye_decompress], please ensure that each node has a unique name. [mainboard_default_6429: E0531 16:35:54.853683 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_right_fisheye_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853683 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_right_fisheye_decompress], please ensure that each node has a unique name. [mainboard_default_6429: E0531 16:35:54.853744 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_rear_6mm_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853744 6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_rear_6mm_decompress], please ensure that each node has a unique name. [mainboard_default_6428: E0531 16:35:54.891752 6527 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[static_transform], please ensure that each node has a unique name.] mainboard_default_6428: E0531 16:35:54.891752 6527 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[static_transform], please ensure that each node has a unique name. [mainboard_default_6429: ] mainboard_default_6429: [mainboard_default_6428: ] mainboard_default_6428: [cyber_launch_6429] ERROR Process [mainboard_default_6429] has finished. [pid 6432, cmd mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_6429 -s CYBER_DEFAULT]. [cyber_launch_6429] INFO All processes has died. [cyber_launch_6429] INFO Cyber exit. [cyber_launch_6429] INFO All processes have been stopped. [cyber_launch_6428] ERROR Process [mainboard_default_6428] has finished. [pid 6434, cmd mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_6428 -s CYBER_DEFAULT]. [cyber_launch_6428] INFO All processes has died. [cyber_launch_6428] INFO Cyber exit. [cyber_launch_6428] INFO All processes have been stopped. [perception_trafficlights: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'] perception_trafficlights: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf' [perception_trafficlights: [NVBLAS] Cannot open default config file 'nvblas.conf'] perception_trafficlights: [NVBLAS] Cannot open default config file 'nvblas.conf' [perception_trafficlights: [NVBLAS] Config parsed] perception_trafficlights: [NVBLAS] Config parsed [perception_trafficlights: [NVBLAS] CPU Blas library need to be provided] perception_trafficlights: [NVBLAS] CPU Blas library need to be provided [perception: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'] perception: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf' [perception: [NVBLAS] Cannot open default config file 'nvblas.conf'] perception: [NVBLAS] Cannot open default config file 'nvblas.conf' [perception: [NVBLAS] Config parsed] perception: [NVBLAS] Config parsed [perception: [NVBLAS] CPU Blas library need to be provided] perception: [NVBLAS] CPU Blas library need to be provided [perception_trafficlights: F0531 16:36:00.200565 6495 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0) out of memory] perception_trafficlights: F0531 16:36:00.200565 6495 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0) out of memory [perception_trafficlights: *** Check failure stack trace: ***] perception_trafficlights: *** Check failure stack trace: *** [perception_trafficlights: @ 0x7fb83b661ec0 google::LogMessage::Fail()] perception_trafficlights: @ 0x7fb83b661ec0 google::LogMessage::Fail() [perception_trafficlights: @ 0x7fb83b661e07 google::LogMessage::SendToLog()] perception_trafficlights: @ 0x7fb83b661e07 google::LogMessage::SendToLog() [perception_trafficlights: @ 0x7fb83b6617de google::LogMessage::Flush()] perception_trafficlights: @ 0x7fb83b6617de google::LogMessage::Flush() [perception_trafficlights: @ 0x7fb83b66483b google::LogMessageFatal::~LogMessageFatal()] perception_trafficlights: @ 0x7fb83b66483b google::LogMessageFatal::~LogMessageFatal() [perception_trafficlights: @ 0x7fb7c025cfa0 caffe::SyncedMemory::mutable_gpu_data()] perception_trafficlights: @ 0x7fb7c025cfa0 caffe::SyncedMemory::mutable_gpu_data() [perception_trafficlights: @ 0x7fb7c011f1c2 caffe::Blob<>::mutable_gpu_data()] perception_trafficlights: @ 0x7fb7c011f1c2 caffe::Blob<>::mutable_gpu_data() [perception_trafficlights: @ 0x7fb7c02ec176 caffe::EltwiseLayer<>::Forward_gpu()] perception_trafficlights: @ 0x7fb7c02ec176 caffe::EltwiseLayer<>::Forward_gpu() [perception_trafficlights: @ 0x7fb7c026489c caffe::Net<>::ForwardFromTo()] perception_trafficlights: @ 0x7fb7c026489c caffe::Net<>::ForwardFromTo() [perception_trafficlights: @ 0x7fb7c0264c95 caffe::Net<>::Forward()] perception_trafficlights: @ 0x7fb7c0264c95 caffe::Net<>::Forward() [perception_trafficlights: @ 0x7fb7edb3ced1 apollo::perception::inference::CaffeNet::Infer()] perception_trafficlights: @ 0x7fb7edb3ced1 apollo::perception::inference::CaffeNet::Infer() [perception_trafficlights: @ 0x7fb7eeb32ea5 apollo::perception::camera::TrafficLightDetection::Inference()] perception_trafficlights: @ 0x7fb7eeb32ea5 apollo::perception::camera::TrafficLightDetection::Inference() [perception_trafficlights: @ 0x7fb7eeb3365f apollo::perception::camera::TrafficLightDetection::Detect()] perception_trafficlights: @ 0x7fb7eeb3365f apollo::perception::camera::TrafficLightDetection::Detect() [perception_trafficlights: @ 0x7fb7eeffd800 apollo::perception::camera::TrafficLightCameraPerception::Perception()] perception_trafficlights: @ 0x7fb7eeffd800 apollo::perception::camera::TrafficLightCameraPerception::Perception() [perception_trafficlights: @ 0x7fb826411add apollo::perception::onboard::TrafficLightsPerceptionComponent::OnReceiveImage()] perception_trafficlights: @ 0x7fb826411add apollo::perception::onboard::TrafficLightsPerceptionComponent::OnReceiveImage() [perception_trafficlights: @ 0x7fb82642daa4 _ZNKSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS0_7drivers5ImageEERKSsEEclIJRKS7_RSsEvEEvPS3_DpOT_] perception_trafficlights: @ 0x7fb82642daa4 _ZNKSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS0_7drivers5ImageEERKSsEEclIJRKS7_RSsEvEEvPS3_DpOT_ [perception_trafficlights: @ 0x7fb82642a20e _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEE6__callIvIRKS8_EILm0ELm1ELm2EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE] perception_trafficlights: @ 0x7fb82642a20e _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEE6__callIvIRKS8_EILm0ELm1ELm2EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE [perception_trafficlights: @ 0x7fb8264263e3 _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEEclIJRKS8_EvEET0_DpOT_] perception_trafficlights: @ 0x7fb8264263e3 _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEEclIJRKS8_EvEET0_DpOT_ [perception_trafficlights: @ 0x7fb826422a99 std::_Function_handler<>::_M_invoke()] perception_trafficlights: @ 0x7fb826422a99 std::_Function_handler<>::_M_invoke() [perception_trafficlights: @ 0x7fb8262fbf13 std::function<>::operator()()] perception_trafficlights: @ 0x7fb8262fbf13 std::function<>::operator()() [perception_trafficlights: @ 0x7fb8262f306f _ZZN6apollo5cyber6ReaderINS_7drivers5ImageEE4InitEvENKUlRKSt10shared_ptrIS3_EE_clES8_] perception_trafficlights: @ 0x7fb8262f306f _ZZN6apollo5cyber6ReaderINS_7drivers5ImageEE4InitEvENKUlRKSt10shared_ptrIS3_EE_clES8_ [perception_trafficlights: @ 0x7fb82630a8a5 _ZNSt17_Function_handlerIFvRKSt10shared_ptrIN6apollo7drivers5ImageEEEZNS1_5cyber6ReaderIS3_E4InitEvEUlS6_E_E9_M_invokeERKSt9_Any_dataS6_] perception_trafficlights: @ 0x7fb82630a8a5 _ZNSt17_Function_handlerIFvRKSt10shared_ptrIN6apollo7drivers5ImageEEEZNS1_5cyber6ReaderIS3_E4InitEvEUlS6_E_E9_M_invokeERKSt9_Any_dataS6_ [perception_trafficlights: @ 0x7fb8262fbf13 std::function<>::operator()()] perception_trafficlights: @ 0x7fb8262fbf13 std::function<>::operator()() [perception_trafficlights: @ 0x7fb8262fc1d2 _ZZZN6apollo5cyber8croutine20CreateRoutineFactoryINS_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS4_EEEEENS1_14RoutineFactoryEOT0_RKS6_INS0_4data11DataVisitorIT_NS0_8NullTypeESI_SI_EEEENKUlvE_clEvENKUlvE_clEv] perception_trafficlights: @ 0x7fb8262fc1d2 _ZZZN6apollo5cyber8croutine20CreateRoutineFactoryINS_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS4_EEEEENS1_14RoutineFactoryEOT0_RKS6_INS0_4data11DataVisitorIT_NS0_8NullTypeESI_SI_EEEENKUlvE_clEvENKUlvE_clEv [perception_trafficlights: @ 0x7fb82631b132 _ZNSt17_Function_handlerIFvvEZZN6apollo5cyber8croutine20CreateRoutineFactoryINS1_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS6_EEEEENS3_14RoutineFactoryEOT0_RKS8_INS2_4data11DataVisitorIT_NS2_8NullTypeESK_SK_EEEENKUlvE_clEvEUlvE_E9_M_invokeERKSt9_Any_data] perception_trafficlights: @ 0x7fb82631b132 _ZNSt17_Function_handlerIFvvEZZN6apollo5cyber8croutine20CreateRoutineFactoryINS1_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS6_EEEEENS3_14RoutineFactoryEOT0_RKS8_INS2_4data11DataVisitorIT_NS2_8NullTypeESK_SK_EEEENKUlvE_clEvEUlvE_E9_M_invokeERKSt9_Any_data [perception_trafficlights: @ 0x7fb8485456e8 std::function<>::operator()()] perception_trafficlights: @ 0x7fb8485456e8 std::function<>::operator()() [perception_trafficlights: @ 0x7fb840091cbc apollo::cyber::croutine::CRoutine::Run()] perception_trafficlights: @ 0x7fb840091cbc apollo::cyber::croutine::CRoutine::Run() [perception_trafficlights: @ 0x7fb840090f55 apollo::cyber::croutine::(anonymous namespace)::CRoutineEntry()] perception_trafficlights: @ 0x7fb840090f55 apollo::cyber::croutine::(anonymous namespace)::CRoutineEntry() [cyber_launch_6430] ERROR Process [perception] has finished. [pid 6431, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT]. [cyber_launch_6430] ERROR Process [perception_trafficlights] has finished. [pid 6436, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT]. [cyber_launch_6430] INFO All processes has died. [cyber_launch_6430] INFO Cyber exit. [cyber_launch_6430] INFO All processes have been stopped.`

Do you have an idea ? According to the simulator developper, the GPU model could be the origin of the problem.

I am open to any suggestion.

Thank you in advance.

**Comment by gengqx** [comment]
it says 
```
Check failed: error == cudaSuccess (2 vs. 0) out of memory
```
apollo recommend to use gtx1080 which have 8GB Graph memery.
if you can't change your card,maybe you can just start one sensor 
```
cyber_launch start /apollo/modules/drivers/tools/image_decompress/launch/perception_camera.launch
```

**Comment by leFeuilluZer** [comment]
Thank your for your answer, I tried your recommendation ( just using `/apollo/modules/perception/production/launch/perception_camera.launch` instead of the path you gave). It gave me this error message : 

![image](https://user-images.githubusercontent.com/48589344/58870485-8e415580-86c0-11e9-8084-653d5a298b7a.png)

**Comment by leFeuilluZer** [comment]
I compiled and run in debug mode the perception_camera. Here are the backtraces of the execution

![image](https://user-images.githubusercontent.com/48589344/59334134-15fb1580-8cfa-11e9-99a0-9de344655525.png)

**Comment by songyongkang** [comment]
node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node [prediction]

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
