### ISSUE TITLE
请教下dreamview的二次开发

### ISSUE THREAD

**Issue by shawlq** [ApolloAuto/apollo#8644]
您好，我很喜欢dreamview的设计框架，而且本身也熟悉c++11的后端开发。
目前我正在使用自己的模型玩具车，加上便宜的摄像头和小雷达；

想把dreamview改成轻量级的可视化前后端框架，仅仅用来显示设备上的感知预测结果。

计划是自己写一套底层传输，把cyber::node替换掉。同时切掉后端代码中那些控制部分，仅仅保留simulationworldwithplan的数据模型，用于前端请求响应。

我希望改造后的轻量级框架可以直接在ubuntu上使用makefile编译，而不是在厚重的apollo docker中构建。

构建框架的改造一定会有调试的过程。我担心的是dreamview的前后端之所以放在 docker中编译，是因为它存在一些我所不了解的，但又必须的依赖。而这些依赖不是能够快速识别，并且用常规手段（比如apt-get install等）就可以解决的。如果存在这些隐藏的技术依赖，会导致整个改造变得困难。

所以在尝试之前，想请教下。从设计上 dreamview的前后端，是否是纯净的、少依赖的？即对docker构建环境的依赖度较低，容易改造的那种？

**Comment by zezhou** [comment]
dreamview 是给planning 和 control 调试用的，感知的是不用dreamview的，一般用qt之类的框架自己写一个小工具，apollo的tools下面应该有相关代码。另外按你的需求也可以直接上 ros + rviz 就好了。

我改过某个版本的dreamview. 前端是纯净的，它可以直接在浏览器里显示。后端和 apollo 的数据接口绑定挺深的。举个例子，我以前改的版本没了router，dreamview都初始化不起来。前端也不好改。dreamview 前端用了 es6 + d3 + mobx ,如果你没有前端基础，前端也是很难改的。

Dreamview is making for planning and control, not for perception.

**Comment by shawlq** [comment]
@zezhou 多谢您的帮助。

从本意上来说，我希望后端放弃ros/cyber。我不需要通过dreamview去控制我的模型车。在我的模型车上已经有单片机在做简单的感知、规划、控制。现在的想法是把三者（感知、规划、和实际控制）的结果，能显示到前端。

考虑到移植性和访问量（允许实验室的师兄师姐们都能访问）。我希望是简洁的前、后端部署。
前、后端之间通过protobuf指定模型，后端通过socket完成（感知、规划、控制）数据采集，并转换成protobuf，发送给前端。前端使用three.js和chart.js技术完成数据显示（当前就是dreamview已经使用的技术）。

我希望借助dreamview现有框架做二次，在前、后端的开发技术上并没有太大困难。反而是当前dreamview基于 docker + bazel的构建框架让我有点陌生。为了以后方便，我希望能把构建改成  在ubuntu linux上通过makefile的方式构建。现在唯一的担心是代码移出来后，会因为一些特殊的依赖，导致编译调测耗费太多太多精力。

所以如果有人能在构建上给出建议，或者分享自己二次开发dreamview的过程，对我都是非常有意义的。

**Comment by zezhou** [comment]
我记得 dreamview  的前端就是通过 websocket 接口去拿 protobuf 数据的，所以按你的需求只需要 dreamview 前端部分即可。
构建这块也不需要 docker + bazel， 前端用 webpack 编译，如果你有全套前端开发环境，进入 apollo/modules/dreamview/frontend/ 执行 npm start 就可以编译调试了
不过不建议你在改造dreamview上花时间, 你们的开发目标不一样，能复用的很少
如果你一定要做，你的需求我倒是自己写过小工具，基于web/protobuf/socket 展示感知 2d/3d 结果来debug。我有时间的话倒可以整理下代码给你参考.....

**Comment by gouchaoer** [comment]
> 我记得 dreamview 的前端就是通过 websocket 接口去拿 protobuf 数据的，所以按你的需求只需要 dreamview 前端部分即可。
> 构建这块也不需要 docker + bazel， 前端用 webpack 编译，如果你有全套前端开发环境，进入 apollo/modules/dreamview/frontend/ 执行 npm start 就可以编译调试了
> 不过不建议你在改造dreamview上花时间, 你们的开发目标不一样，能复用的很少
> 如果你一定要做，你的需求我倒是自己写过小工具，基于web/protobuf/socket 展示感知 2d/3d 结果来debug。我有时间的话倒可以整理下代码给你参考.....

能参考一下你的代码么？我也遇到一样的需求，我们可以相互学习进步

**Comment by idabaicai** [comment]
请问以下现在有解决方案了吗？

**Comment by idabaicai** [comment]
@shawlq 你好，请问一下你的问题解决了吗？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
