### ISSUE TITLE
Over-fitting issues while using spline1d

### ISSUE THREAD

**Issue by Junzeng-x14** [ApolloAuto/apollo#8648]
Hi there,

I'm wondering that how's going with the spline1d polynomial interpolation, does it the polynomial function interpolate along all the time step together or just between two adjecent time step? If along all the time step together, could the over-fitting or multiple solutions from the optimization be a huge problem?

Thank you so much for the help!

**Comment by JasonZhou404** [comment]
a few pieces of polynomials along a time horizon, not two adjecent time step.

**Comment by Junzeng-x14** [comment]
I see! Thanks! I will close this issue.
