### ISSUE TITLE
getting an error message regarding node

### ISSUE THREAD

**Issue by anchans** [ApolloAuto/apollo#8687]
getting the following whenever I try to start node or try to build anything that requires node

![node_error](https://user-images.githubusercontent.com/37716287/59057639-ae534f00-884f-11e9-9ea3-194edeb98383.png)

**Comment by natashadsouza** [comment]
In the docker module, run **yarn_install** under /apollo/modules/dreamview/frontend to install all node_modules before building the frontend. Let me know if you have any questions.

**Comment by ctwfei** [comment]
Hi, @anchans Can you provide more details about your use of node? 
Thank you!

**Comment by hugomatic** [comment]
I have the same issue. Try yarn install to see it: 
`
hugo@in_dev_docker:/apollo$ cd /apollo/modules/dreamview/frontend/
hugo@in_dev_docker:/apollo/modules/dreamview/frontend$ yarn install
node[6628]: pthread_create: Invalid argument
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.89s.
`
We are using node to extend dreamview

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
