### ISSUE TITLE
Add multiple destinations

### ISSUE THREAD

**Issue by dongyy1148** [ApolloAuto/apollo#8725]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (Linux Ubuntu 16.04):
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
- Can I add multiple destinations for routing? i want the vehicle to reach one destination first and then go to another destination.

**Comment by Zhenni17** [comment]
Hi @dongyy1148 , currently this feature is not supported. However, this feature is in the product roadmap, so please stay tuned.
