### ISSUE TITLE
Debugging Perception/radar module 

### ISSUE THREAD

**Issue by Prj1508** [ApolloAuto/apollo#8779]
I am trying to debug the perception/radar module, but I am not able to find and attach appropriate gdbserver process id. I have updated launch and tasks.json files as well as start_gdb_*****.sh files for both perception and radar. 

After turning on simcontrol option and perception and radar modules in dreamview, when I grep, perception provides process id, but perception module option immediately goes off in dreamview. This is resulting in not attaching to gdbserver

Here is the system I am using
Ubuntu : 16.04
Machine  with GPU1070

thanks for your help

**Comment by Avps1** [comment]
Hi. 
Did you find a solution to this ?
I have the exact same problem. The module crashes as soon as I attach the process in gdb.
I made a little video on this : 
https://www.youtube.com/watch?v=OKnK4ANrEWY

Thanks for your help.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
