### ISSUE TITLE
如何重启apollo的几个container

### ISSUE THREAD

**Issue by yoyouwen** [ApolloAuto/apollo#8818]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:
我在重启电脑之后想再进入apollo的docker container，但是我的docker列表里只有一个container：  apollo_dev_xx。我应该如何重启其他的container：localization_volume-x86_64-latest， yolo3d_volume-x86_64-latest，map_volume-sunnyvale_big_loop-latest，map_volume-sunnyvale_loop-latest？

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/43387865/59539863-18938000-8f31-11e9-8ebb-08a9d8266901.png)

谢谢！

**Comment by shawlq** [comment]
in your /apollo, run "bash docker/scripts/dev_start.sh" restart all apollo containers
