### ISSUE TITLE
cyber_recorder

### ISSUE THREAD

**Issue by breakisx** [ApolloAuto/apollo#8828]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

Hello apollo: 
After the source cyber/setup.bash, only cyber_launch appeared, no cyber_recorder and others  appeared. What is the reason? Is there any good debugging solution?

**Comment by natashadsouza** [comment]
@breakisx did you find a fix to your question?
