### ISSUE TITLE
preload error

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#8833]
**Describe the bug**
when launch dev_start.sh , got error msg as  follows:

ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by luqiang21** [comment]
@sinopec I am having similar problems. When I `dev_start.sh`, it shows this error. But every module is working after I run `dev_into.sh`.

**Comment by renegadephysicist** [comment]
If you revert this commit it fixes the issue.

https://github.com/ApolloAuto/apollo/commit/7997b9a3312dc7aa4ac0475b6a945cd4cdf4b708#diff-ccc78ede332b74b1730b71f544c94683

**Comment by mickeyouyou** [comment]
This issue have been fixed, thank you.

**Comment by Avps1** [comment]
Hi, I am getting the same problem when I do dev_start.sh.
Can you tell me how this issue got fixed, or what should I do to fix it?

**Comment by daohu527** [comment]
I see that the latest version has deleted this configuration(LD_PRELOAD). But I wonder this issue will be ok?  


#9368
