### ISSUE TITLE
Component Interface shared_ptr Design

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#8846]
I noticed that the Component interface for `Proc` is a const reference on a `std::shared_ptr`.
https://github.com/ApolloAuto/apollo/blob/master/cyber/component/component.h#L76-L89
```
  /**
   * @brief The process logical of yours.
   *
   * @param msg0 the first channel message.
   * @param msg1 the second channel message.
   * @param msg2 the third channel message.
   * @param msg3 the fourth channel message.
   *
   * @return returns true if successful, otherwise returns false
   */
  virtual bool Proc(const std::shared_ptr<M0>& msg0,
                    const std::shared_ptr<M1>& msg1,
                    const std::shared_ptr<M2>& msg2,
                    const std::shared_ptr<M3>& msg3) = 0;
```

Can it be just a const reference to the data? It doesn't seem like the user will want to operate on a const shared_ptr reference.

Another option would be to make it pass by value for the shared_ptr. That way the user will want to avoid the copy.

The current design is usable, but seems a little overly complicated. It's better to only have what is used and necessary.

**Comment by ctwfei** [comment]
Hi Fla3inH0tCheet0s, thanks for your suggestion! 

1. Firstly, using shared_ptr can reduce the copies of messages during transmission when there are multiple readers
  
2. There is no reason to pass by value for the sake of a function call，we prefer pass by const reference for efficiency's sake when using shared_ptr.
   Scott, Andrei and Herb discussed and answered  the question about pass-by-value or pass-by-const-reference for shared_ptr during Ask Us Anything session at C++ and Beyond 2011. If you're interested, check out the video below：
[https://channel9.msdn.com/Shows/Going+Deep/C-and-Beyond-2011-Scott-Andrei-and-Herb-Ask-Us-Anything#time=04m34s]()

**Comment by Fla3inH0tCheet0s** [comment]
I think we are talking about different things. There's no need to copy *the data* in any case. I don't see why the `const shared_ptr` part is there. Also, there's some question in whether the user should be able to modify the data.

I'm proposing changing the interface to
```
virtual bool Proc(const M0& msg0, const M1& msg1, const M2& msg2, const M3& msg3) = 0;
```

The purpose is for simplicity without losing any functionality.

**Comment by ctwfei** [comment]
> I don't see why the const shared_ptr part is there

The message will be copied **N** times when fetched from the channel buffer if we just use a const reference to the data. You can learn about [the invocation mechanism of proc function](https://github.com/ApolloAuto/apollo/blob/master/cyber/croutine/routine_factory.h/#L119-L142), which may help you understand the case.

**Note**: N means the number of message receivers.


> there's some question in whether the user should be able to modify the data.

The user may need to modify the message header.

**Comment by Fla3inH0tCheet0s** [comment]
OK. There are two separate arguments.

1. Making the data const in the interface.
> The user may need to modify the message header.

That's probably right. The user may want to make a node to modify a message and forward it.

2. `std::shared_ptr` in the `Proc` interface.
> The message will be copied N times when fetched from the channel buffer if we just use a const reference to the data. You can learn about the invocation mechanism of proc function, which may help you understand the case.

I meant only to change the user facing interface. The underlying implementation is fine.

If it is not const and to follow Google Style guide of using pointers for mutable data, the proposed interface would be
```
virtual bool Proc(M0* msg0, M1* msg1, M2* msg2, M3* msg3) = 0;
```

I'm not sure if that is really an improvement. Feel free to close this.
