### ISSUE TITLE
cyber_recorder play Performance Issues

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#8851]
**Describe the bug**
`cyber_recorder play` fails to consume data on large datasets in real time. Other data players don't have this problem with this size of data.

**To Reproduce**
Play a large dataset (2GB/s) that has not been played since the computer started. Observe hiccups after 60s. It's more noticeable on slow disks or going through a busy disk like NFS.

**Expected behavior**
`cyber_recorder play` should count up continuously

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu

**Additional context**
According to https://groups.google.com/forum/#!topic/protobuf/xKQWkI3r3OA, managing the lifetime of `CodedInputStream` is important for performance due to buffering. https://github.com/ApolloAuto/apollo/blob/feda61d87b254d080896f55a17e82045d7c48d47/cyber/record/file/record_file_reader.h#L69 The file above instantiates the protobuf object every time.

**Comment by baowanyu** [comment]
Please provide record files to help analysis.
We create CodedInputStream when used, since the record file does not contain only consecutive Pb messages.

**Comment by baowanyu** [comment]
Close the problem temporarily until the record file is provided.
