### ISSUE TITLE
【紧急】虚拟机安装Apollo开发环境-构建失败-[ERROR] Build failed!

### ISSUE THREAD

**Issue by fenghongjian** [ApolloAuto/apollo#8860]
![捕获](https://user-images.githubusercontent.com/46391287/59651795-dcc11a80-91bd-11e9-9b6f-f36ad9555fd5.PNG)

vmware**虚拟机安装apollo3.5** 失败，，拉取Apollo源代码成功，docker安装成功，docker内apollo镜像拉去成功，之后编译失败。安装指导文件参考的是“ https://www.cnblogs.com/iors/p/10862713.html”

**Comment by natashadsouza** [comment]
该错误是由于内存不足引起的。你有一个至少8 GB可用内存的系统吗？ @fenghongjian

**Comment by fenghongjian** [comment]
ok  ，thank you。

**Comment by natashadsouza** [comment]
@fenghongjian you are very welcome. Closing this issue currently
