### ISSUE TITLE
Is there a way to convert rosbag to recorder file or operate the messages in recorder file

### ISSUE THREAD

**Issue by yoyouwen** [ApolloAuto/apollo#8869]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 14.04
- **Apollo installed from (source or binary)**: source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.5

### Steps to reproduce the issue:

I am trying to modify the messages in the cyber record. But it seems no Cyber RT Developer Tools can be used to read the message value and modify it. And I also see how to  convert  recorder file to rosbag. But is there a way to do the opposite?

**Comment by ctwfei** [comment]
Hi, @yoyouwen you can use rosbag_to_record tool to convert a bag file to record file. Please refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md#rosbag_to_record)

**Comment by yoyouwen** [comment]
> Hi, @yoyouwen you can use rosbag_to_record tool to convert a bag file to record file. Please refer to [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md#rosbag_to_record)

Yeah, but how can I convert a record file to bag file？

**Comment by natashadsouza** [comment]
@yoyouwen unfortunately we do not support conversion of record to the rosbag format.

**Comment by yoyouwen** [comment]
> @yoyouwen unfortunately we do not support conversion of record to the rosbag format.

Is there any where we can read the message in the record file or modify a single message?

**Comment by ctwfei** [comment]
@yoyouwen You can refer to [this example](https://github.com/ApolloAuto/apollo/blob/master/cyber/examples/record.cc) to modify the record file.
