### ISSUE TITLE
how should I understand we put the localization pose to perception_obstacle container and why we do this?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo#888]
https://github.com/ApolloAuto/apollo/blob/b2ee325f2be1308b62afc57a14abc8c31006d9d0/modules/prediction/prediction.cc#L104
`
pose_container->Insert(localization);
  PerceptionObstacle* pose_ptr = pose_container->ToPerceptionObstacle();
  if (pose_ptr != nullptr) {
    obstacles_container->InsertPerceptionObstacle(
        *(pose_ptr), pose_container->GetTimestamp());
  } else {
    ADEBUG << "Invalid pose found.";
  }

`

**Comment by jinghaomiao** [comment]
An ego vehicle is one of the obstacles as well. It'll be useful to analyze the interactions between vehicles on the road for more precise prediction. Hope this helps. Thanks!

**Comment by kechxu** [comment]
Since this question has been answered, I would like to close this issue. If you have any more question, please feel free to reopen it.
