### ISSUE TITLE
Can't reach baidu armv8 image links

### ISSUE THREAD

**Issue by yasineser** [ApolloAuto/apollo#8881]
I am tyring to create docker image for Nvidia jetson tx2. When I follow below steps to run docker build, I can't reach the links such as:
http://www.baiduapollo.club/apollo-docker/jdk-8u144-linux-arm64-vfp-hflt.tar.gz
it gives me error and I can't reach. There is a problem with the links I guess? Can you renew them?

### System information

- Nvidia Jetson Xavier -> Ubuntu 18.03 on armv8
- source -> docker
- v3.1_dev branch, means apollo 3.0 I guess

### Steps to reproduce the issue:
- cd docker/build
- sudo ./build_dev.sh dev.aarch64.dockerfile

**Comment by natashadsouza** [comment]
@yeseract which guide did you refer to, to set up Apollo's docker environment?

**Comment by yeseract** [comment]
This one:
https://github.com/ApolloAuto/apollo/tree/v3.1_dev/docker/build

While building, it starts bash commands for files and wgets some tar.gz files. Those links cannot be downloaded. When I paste it into browser, it redirects to:
http://domainwall.cloud.baidu.com/block.html

**Comment by mickeyouyou** [comment]
Sorry, This domain names need to be filed. Please wait.

**Comment by DongAi** [comment]
@yeseract, that file can be reached now, please try again. Some built-in packages on that server such as pcl, ros were built on TX2, so you may have to built them on Xavier by yourself to make it work.

**Comment by XinrRunChao** [comment]
> Sorry, This domain(http://www.baiduapollo.club/) names need to be filed. Please wait.

Hello, I want to know whether the domain is reached? Thank you very much!

**Comment by XinrRunChao** [comment]
> @yeseract, that file can be reached now, please try again. Some built-in packages on that server such as pcl, ros were built on TX2, so you may have to built them on Xavier by yourself to make it work.

Hello, where is the apollo open source code on TX2? How can I find it? Thank you very much!!

**Comment by XinrRunChao** [comment]
> I am tyring to create docker image for Nvidia jetson tx2. When I follow below steps to run docker build, I can't reach the links such as:
> http://www.baiduapollo.club/apollo-docker/jdk-8u144-linux-arm64-vfp-hflt.tar.gz
> it gives me error and I can't reach. There is a problem with the links I guess? Can you renew them?
> 
> ### System information
> * Nvidia Jetson Xavier -> Ubuntu 18.03 on armv8
> * source -> docker
> * v3.1_dev branch, means apollo 3.0 I guess
> 
> ### Steps to reproduce the issue:
> * cd docker/build
> * sudo ./build_dev.sh dev.aarch64.dockerfile

Hey gus, do you solve this problem? I met the same problem, Can you help me? Thank you very much!!

**Comment by storypku** [comment]
> Hey gus, do you solve this problem? I met the same problem, Can you help me? Thank you very much!!

Hi @XinrRunChao ,

    The Apollo team now provides CyberRT Docker image for AArch64 based on Apollo 6.0+ and Xavier. Also provided is an experimental  development image for AArch64 based on master HEAD and Xavier. 
Please note that support for AArch64 of the whole Apollo project is still WIP.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
