### ISSUE TITLE
confused about different coordination  systems

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#8957]
I am studying the coordinate systems of different sensors.And also the vechile coodinate system . This really confued me .
I check the  this document :https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination_cn.md
It tells me ,the y axis is the forward direction of the vechile,and the x axis is right forward.
But in fact ,it's just opposite. The x axis is the forward direction.

And when i use the default instrin and extrinc yawl files, I found  y axis is left forward in the camera coordinate  ,while radar & lidar is all right forward. —— how this happened? is this because i have not calibrated it yet? I use 6mm leopard usb camra，the default camera

**Comment by natashadsouza** [comment]
@sinopec each sensor has its own coordinates when installed. Calibration is definitely required to ensure that your sensors are all working in conjunction.

**Comment by sinopec** [comment]
> @sinopec each sensor has its own coordinates when installed. Calibration is definitely required to ensure that your sensors are all working in conjunction.

Thanks for your reply , I guess I have resolve it .
The default camera coordnate system need to rotate 90 degrees aound z axis to conform to veichel coordinate system . The same with the continent radar.
