### ISSUE TITLE
Run perception toolkit error 

### ISSUE THREAD

**Issue by ven1234** [ApolloAuto/apollo#8983]
i tried to run perception toolkit. By reading [https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md]. There i found an error ,  trying to  run `cyber_launch start /apollo/modules/transform/launch/static_transform.launch
` command. The requested files are empty. 

I used apollo data set. where i can get calibration files for that data-set. Thank you.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Apollo installed from (source)**:
- **Apollo version (3.5)**:

### Supporting materials (screenshot):
![1](https://user-images.githubusercontent.com/52227049/60147702-76657900-9809-11e9-9ebd-f5a0de97d9e7.png)

**Comment by KaWaiTsoiBaidu** [comment]
@ven1234   you can start the Dreamviewer first, by running ./scripts/bootstrap.sh.   Then go to localhost:8888 as indicated by the information in the terminal.  You will see the dreamviewer there. Select a vehicle in the dreamviewer and the files you mentioned will be created accordingly.

**Comment by techoe** [comment]
Closing the issue since the issue was resolved by the answer and there is no follow-up after the answer.
