### ISSUE TITLE
Why replaced DP+Optimization path planning method with Bound+optimization method

### ISSUE THREAD

**Issue by hongbozhu0303** [ApolloAuto/apollo#8992]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0, 3.5)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):
Hi, @panjiacheng ,@natashadsouza
It looks like DP+QP Optimization path planning method was discarded and replaced with path Bound + Optimization method in 3.5. Could you give an indication of why to make such a big change. Thank you.

**Comment by YajiaZhang** [comment]
Thank you for your question. The reason is the past DP + QP path optimization cannot handle complex urban driving scenarios, while current implementation (path bound + piecewise jerk method) achieves firm controlling of the path shape, thus is able to produce more flexible paths.

**Comment by Ivesss** [comment]
Could you clarify why does DP+QP path cannot handle complex urban driving scenarios please. The path that DP generated(with quintic polynomial connected between sampling points) is already feasible and optimal even without the QP part. Thank you very much!

**Comment by bnn1r** [comment]
> Thank you for your question. The reason is the past DP + QP path optimization cannot handle complex urban driving scenarios, while current implementation (path bound + piecewise jerk method) achieves firm controlling of the path shape, thus is able to produce more flexible paths.

Indeed, could you please elaborate on why is DP + QP approach not good enough for complex urban driving scenarios?

**Comment by apollodevcommunity** [comment]
dp+qp的方式比较耗时，新算法中时间效率较高，并且利用规则的凸空间决策算法能泛化更多场景 ——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=440
