### ISSUE TITLE
请教如何编译阿波罗3.0gpu版本

### ISSUE THREAD

**Issue by manglietiamichelia** [ApolloAuto/apollo#9018]
目前，我需要运行感知模块的yolo算法。
一、请问阿波罗3.0 gpu搭建的步骤概述是这样的吗？

1 安装docker
2 在镜像内安装Nvidia 375，直接使用镜像自带的cuda 8.0
3 在宿主机也安装nvidia 375
4 最后在镜像内用gpu编译

二、请问宿主机和镜像内的Nvidia是否要小版本完全一致，（比如都是375.35）？

三、如果能够正常运行感知模块，镜像内是否要运行了nvidia-smi也能查看本地显卡信息？

**Comment by wanglei828** [comment]
1. 步骤是正确的
2. 小版本不需要完全一致
3. 如果安装成功，在镜像内执行nivdia-smi是可以看到显卡信息的。

**Comment by manglietiamichelia** [comment]
@wanglei828 请问安装nvidia是否一定要使用.run文件安装？apt安装是否可行？

**Comment by manglietiamichelia** [comment]
@wanglei828 请问安装nvidia是否一定要使用.run文件安装？apt安装是否可行？

**Comment by manglietiamichelia** [comment]
@wanglei828 请问安装nvidia是否一定要使用.run文件安装？apt安装是否可行？

**Comment by manglietiamichelia** [comment]
@wanglei828 关于您的回答，我有一些跟进问题。
1 请问安装nvidia是否一定要使用.run文件安装？apt安装是否可行？
2 在宿主机上nvidia-smi可以看到显卡，在镜像中看到的时Driver/library version mismatch。请问状况是怎么回事？
3 是否有必要对于3.0版本使用nvidia-docker插件？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
