### ISSUE TITLE
Link to End-to-end source code is broken

### ISSUE THREAD

**Issue by amontserratAG** [ApolloAuto/apollo#9060]
Hi!
I found in this link:
[http://data.apollo.auto/?locale=en-us&lang=en]
 the End-To-End-Data section. It has two buttons: "Download data" and "source code".
When I click on "source code" button, it opens a broken-link error page. Would you mind
to give me the correct link? Thanks.

**Comment by natashadsouza** [comment]
@amontserratAG the e2e module is no longer a part of the Apollo platform as you can verify on our Github page as well which is why the link no longer exists.

**Comment by amontserratAG** [comment]
Ok, thanks @natashadsouza. Do you know which module replaced e2e module?
