### ISSUE TITLE
bash ./docker/scripts/dev_start.sh -C   [ERROR] Failed to pull docker image.

### ISSUE THREAD

**Issue by maoyuze** [ApolloAuto/apollo#9066]
bash ./docker/scripts/dev_start.sh -C
[INFO] Start pulling docker image registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20190617_1100 ...
Error response from daemon: Get https://registry.docker-cn.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[ERROR] Failed to pull docker image.
请问这是怎么回事啊？

**Comment by manglietiamichelia** [comment]
不用-C。目前docker的中国服务器崩溃。

**Comment by mickeyouyou** [comment]
please use `bash ./docker/scripts/dev_start.s` instead because of the instability of docker-cn.com.
