### ISSUE TITLE
cyber_monitor does not show all channels 

### ISSUE THREAD

**Issue by christian-lanius** [ApolloAuto/apollo#9067]
Hi everyone,
I am currently trying to understand the perception pipeline. For that I wanted to look at the internal messages of the lidar perception. However these internal channels, such as /perception/inner/SegmentationObjects do not show up and can not be inspected with cyber_monitor.
Is there a way to show these messages in cyber_monitor?

Kind regards

**Comment by ctwfei** [comment]
@christian-lanius unfortunately custom messages are for internal use only and do not support cross-process.so that cyber_monitor does not support these inner messages.

**Comment by natashadsouza** [comment]
Closing this issue as we currently do not support this feature. Should our plan change in the future, we will be sure to reach out.
