### ISSUE TITLE
A problem in Lat controller lateral_error calculation

### ISSUE THREAD

**Issue by ChrisRanger** [ApolloAuto/apollo#9070]
### question in lat_controller calculate lateral_error

~control
  const double dx = x - target_point.path_point().x();
  const double dy = y - target_point.path_point().y();
  const double cos_target_heading = std::cos(target_point.path_point().theta());
  const double sin_target_heading = std::sin(target_point.path_point().theta());
  double lateral_error = cos_target_heading * dy - sin_target_heading * dx;//I think '-' shoule be '+'
![22](https://user-images.githubusercontent.com/37474653/60426985-59c1aa80-9c28-11e9-9046-81fb99cab33e.png)

	​	
  	​	
 As is shown in picture,
lateral_error = e1 = L1 + L2 = dy∗cosθdes + dx∗sinθdes = sqrt(dx*dx = dy*dy), 
but why lateral_error = dy∗cosθdes − dx∗sinθdes in lat_controller.cc line691? 
Can someone help me understand it? I am  puzzled.............)

**Comment by lrodrig3** [comment]
e1 =/ L1+L2, e1 is perpendicular to Vxdes which is not the case for the L1+L2 distance.

**Comment by ChrisRanger** [comment]
> e1 =/ L1+L2, e1 is perpendicular to Vxdes which is not the case for the L1+L2 distance.
Thanks for your help, but I also have puzzles.....
Is the line between desire_point to real_point  not perpendicular to Vxdes?  ...In this case, how could I calculate e1? (In other words, how could I understand this equation "lateral_error = dy∗cosθdes − dx∗sinθdes" ?)

**Comment by ChrisRanger** [comment]
@lrodrig3 Thanks for your help, but I also don't see the point .....
Is the line between desire_point to real_point not perpendicular to Vxdes? ...In this case, how could I calculate e1? (In other words, how could I understand this equation "lateral_error = dy∗cosθdes − dx∗sinθdes" ?)

**Comment by lrodrig3** [comment]
e1 = L1 + L2 Is only true if the curvature of the ego vehicle and your target curvature is the same. Then, the L1+L2 distance will be perpendicular to Vxdes because you will have concentric circles. If the curvatures are different L1+L2 is not parallel to e1. The value of the e1 is determined with the projection of the angle between e1 and the vertical axis dy. Turns out that the angle between e1 and dy is equal to θdes

**Comment by ChrisRanger** [comment]
@lrodrig3 sorry not to reply you until now, I got it yet, thanks for your help
