### ISSUE TITLE
GetRemoveBiasImu Function needs to be changed 

### ISSUE THREAD

**Issue by lrodrig3** [ApolloAuto/apollo#9071]
In localization_integ_process.cc the function GetRemoveBiasImu has changed to GetCorrectedImu but in its reference in [here](https://github.com/ApolloAuto/apollo/blob/c7e05d9f88cd72099fde6fd87f909d3b0e0b4c2c/modules/localization/msf/local_integ/localization_integ_process.cc#L107) has not been updated.

**Comment by zhouyao4321** [comment]
I guess you have encountered some compilation problems? If so, please update the docker to fix this problem.

**Comment by lrodrig3** [comment]
What do you mean by update the docker?

**Comment by zhouyao4321** [comment]
I mean to update the docker image and restart the container.
`bash docker/scripts/dev_start.sh`

**Comment by ycool** [comment]
You can pull the latest code and restart docker container to get the latest dependent docker images.
