### ISSUE TITLE
Is there any paper or reference for the evidence combination rules/formula used in the Dempster-Shafer Theory implementation?

### ISSUE THREAD

**Issue by zoeveryday** [ApolloAuto/apollo#9077]
### System information

- **Apollo version (3.5, 5.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

It will be very helpful if anyone can provide the reference (formula) used in the DST implementation.  Is the standard "Dempster's rule of combination" used here?

![image](https://user-images.githubusercontent.com/47616652/60491061-728a9880-9cda-11e9-980f-451ba2eafc69.png)

I have looked into some answers in other issues, but couldn't find any hint...
https://github.com/ApolloAuto/apollo/issues/6785#issuecomment-462538219
https://github.com/ApolloAuto/apollo/pull/6190#issuecomment-449524363

Thanks in advance!

**Comment by techoe** [comment]
Hi @zoeveryday , There are multiple papers regarding DST but The earlier work on DST similar to Apollo’s approach can be found at 
Huadong Wu, Mel Siegel, Rainer Stiefelhagen, Jie Yang, “Sensor Fusion Using Dempster-Shafer Theory,” IEEE Instrumentation and Measurement Technology Conference, 2002 (http://www.cs.cmu.edu/~whd/publications/1076-Siegel.pdf)

**Comment by zoeveryday** [comment]
@techoe thanks for the reply. I'll close the issue.
