### ISSUE TITLE
Failed to start Dreamview

### ISSUE THREAD

**Issue by AyushiRathore** [ApolloAuto/apollo#9081]
I am trying to run the Apollo on my system without any hardware. Therefore, I followed exact instructions as given in software installation guide. 
Steps:
1. clone apollo repository
2. install docker.
3. Build and run apollo with following commands:
$ bash docker/scripts/dev_start.sh
$ bash docker/scripts/dev_into.sh
$ bash apollo.sh build_cpu
$ bash scripts/bootstrap.sh
My build for apollo got successful but after running bash scripts/bootstrap.sh I am getting the the error that apollo is failed to load. I tried to check logs but didn't found anything useful. I tried troubleshooting the problem as instructed by this link: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md
But none of the solutions is working. 
Whenever I am trying to open apollo in the browser it is giving an error that localhost refused to connect.

can someone provide me solution for the same. Am I missing something?
### System information

- **OS Platform and Distribution : Ubtuntu 14.04.6
- Apollo Verison: 3.5

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/13648313/60551250-b2607880-9cf8-11e9-9bd1-ecaed8e6bce7.png)
 this what my logs looks like:
![log](https://user-images.githubusercontent.com/13648313/60551310-f3f12380-9cf8-11e9-9479-c0bcd16a467f.PNG)

I also found this when I executed bash scripts/dreamview start_fe
![dreamviewerror](https://user-images.githubusercontent.com/13648313/60632941-608e2000-9dd6-11e9-9c85-0d3328d8a218.PNG)

**Comment by audier0879** [comment]
Hi，AyushiRathore 
I think I have a similar issue like you, and I did the following steps to fix it, I hope it can help you.
PC: intel i5-7500, 8G DDR4, integrated video card
OS: ubuntu 16.04
Version: apollo_5.0
1. open a teminal(named a) input: 
  $ bash docker/scripts/dev_start.sh
  $ bash docker/scripts/dev_into.sh
  $ bash apollo.sh build_cpu
  $ bash scripts/dreamview.sh start_fe
  input the ctrl+c into the teminal to stop the process when the teminal output stoped, shown in the figure。
![image](https://user-images.githubusercontent.com/50321853/60863163-6199d400-a252-11e9-95a3-a14d22ed1002.png)
2. open another teminal(named b), and input: 
  $ sudo apt-get install psmisc
  $ sudo lsof -i :8888
in this step I have no result shown。
3. return to the teminal a, input:
  $ bash scripts/dreamview.sh
    I only got “Launched module dreamview”, but not the “Dreamview is running at http://localhost:8888”
![image](https://user-images.githubusercontent.com/50321853/60864078-1cc36c80-a255-11e9-8ef3-fd15a3fbeb8c.png)
 $ cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
4. open Chrome and input the localhost:8888, then I got the Offline Demo.

**Comment by audier0879** [comment]
Hi，I think I found the problem from https://github.com/ApolloAuto/apollo/issues/7228.
After I run the “git lfs fetch --all” , the Dreamview can start with no problem.

**Comment by papaispicolo** [comment]
Hi Audier0879, could you give me some more information how you fixed the issue ?

I am having exactly the same issue,

I did

$ 'git lfs fetch --all'  on host
inside container 
$ bash apollo.sh build_cpu

```bash
INFO: (07-12 16:43:43.421) Elapsed time: 8.771s, Critical Path: 0.01s
1============================
[ OK ] Build passed!
[INFO] Took 643 seconds
============================
seunghan@in_dev_docker:/apollo$ #
seunghan@in_dev_docker:/apollo$ 
seunghan@in_dev_docker:/apollo$ ls
BUILD            CPPLINT.cfg  README.md   WORKSPACE     apollo.doxygen  apollo_docker.sh  bazel-bin       bazel-out       cyber  docker  modules    py_proto         scripts      tools
CONTRIBUTING.md  LICENSE      RELEASE.md  WORKSPACE.in  apollo.sh       bazel-apollo      bazel-genfiles  bazel-testlogs  data   docs    nohup.out  readthedocs.yml  third_party
seunghan@in_dev_docker:/apollo$ bash scripts/bootstrap.sh 
Module monitor is already running - skipping.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information
seunghan@in_dev_docker:/apollo$ bash scripts/dreamview.sh stop
[cyber_launch_24023] INFO Stop cyber launch finished.
[cyber_launch_24023] INFO cyber_launch exit.
Successfully stopped module dreamview.
seunghan@in_dev_docker:/apollo$ bash scripts/dreamview.sh start_fe
[cyber_launch_24393] INFO Launch file [/apollo/modules/dreamview/launch/dreamview.launch]
[cyber_launch_24393] INFO ========================================================================================================================
[cyber_launch_24393] INFO Load module [dreamview] binary: [/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt] [CYBER_DEFAULT] conf: [] exception_handler: [respawn]
[cyber_launch_24393] INFO Start process [/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt] successfully. pid: 24425
[cyber_launch_24393] INFO ------------------------------------------------------------------------------------------------------------------------
```

But I can not see anything on localhost:8888 

System information
**OS Platform and Distribution : Ubtuntu 18.04
Apollo Verison: 3.5

**Comment by audier0879** [comment]
I failed just because I didn't run the "git lfs fetch --all", so after run the command, everything is ok. 
And do you have a try in ubuntu16.04?

**Comment by papaispicolo** [comment]
Thanks @audier0879 , 

It seems that it was due to FMA/FMA3 instruction issue. My CPU is a Xeon E5-2650v2 which doesn't support FMA/FMA3 maybe.. 

```bash
xxxx@in_dev_docker:/apollo$ source scripts/apollo_base.sh;
xxxx@in_dev_docker:/apollo$ start_gdb dreamview 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /apollo/bazel-bin/modules/dreamview/dreamview...done.
(gdb) r
Starting program: /home/xxxx/.cache/bazel/_bazel_xxxx/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/dreamview/dreamview --flagfile=modules/dreamview/conf/dreamview.conf --log_dir=/apollo/data/log
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff8deb0700 (LWP 22641)]
[New Thread 0x7fff8d6af700 (LWP 22642)]
[New Thread 0x7fff8aeae700 (LWP 22643)]
[New Thread 0x7fff886ad700 (LWP 22644)]
 :
Program received signal SIGILL, Illegal instruction.
0x00007fffe0073bec in double boost::math::detail::erf_inv_imp<double, boost::math::policies::policy<boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> >(double const&, double const&, boost::math::policies::policy<boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> const&, mpl_::int_<64> const*) () from /usr/local/lib/libpcl_sample_consensus.so.1.7
(gdb)
```

**Comment by papaispicolo** [comment]
Thanks to the trouble shooting guide on FMA/FMA3 issue, now dreamview starts and I can see the UI.

https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md

**Comment by AyushiRathore** [comment]
> Hi，AyushiRathore
> I think I have a similar issue like you, and I did the following steps to fix it, I hope it can help you.
> PC: intel i5-7500, 8G DDR4, integrated video card
> OS: ubuntu 16.04
> Version: apollo_5.0
> 
> 1. open a teminal(named a) input:
>    $ bash docker/scripts/dev_start.sh
>    $ bash docker/scripts/dev_into.sh
>    $ bash apollo.sh build_cpu
>    $ bash scripts/dreamview.sh start_fe
>    input the ctrl+c into the teminal to stop the process when the teminal output stoped, shown in the figure。
>    ![image](https://user-images.githubusercontent.com/50321853/60863163-6199d400-a252-11e9-95a3-a14d22ed1002.png)
> 2. open another teminal(named b), and input:
>    $ sudo apt-get install psmisc
>    $ sudo lsof -i :8888
>    in this step I have no result shown。
> 3. return to the teminal a, input:
>    $ bash scripts/dreamview.sh
>    I only got “Launched module dreamview”, but not the “Dreamview is running at [http://localhost:8888”](http://localhost:8888%E2%80%9D)
>    ![image](https://user-images.githubusercontent.com/50321853/60864078-1cc36c80-a255-11e9-8ef3-fd15a3fbeb8c.png)
>    $ cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop
> 4. open Chrome and input the localhost:8888, then I got the Offline Demo.

Hello @audier0879  I followed your steps but got the following error:

![image](https://user-images.githubusercontent.com/13648313/61452655-4dc53080-a92a-11e9-8d50-4ae73b93bc72.png)

**Comment by AyushiRathore** [comment]
@audier0879  I tried the solutions you suggested both the cyber_recorder command and by performing git lfs fetch --all but it is giving the following error:
![image](https://user-images.githubusercontent.com/13648313/61455338-36d60c80-a931-11e9-89c1-daedc6c06437.png)

Do you think that there can be issue with the PCL?

**Comment by WooLiGuaiguai** [comment]
> 嗨，AyushiRathore 
> 我想我有类似你的问题，我做了以下步骤来解决它，我希望它可以帮到你。
> PC：intel i5-7500,8G DDR4，集成显卡
> 操作系统：ubuntu 16.04 
> 版本：apollo_5.0
> 
> 1. 打开一个teminal（命名为a）输入：
>    $ bash docker 
>    / scripts / dev_start.sh 
>    $ bash docker / scripts / dev_into.sh $ bash apollo.sh build_cpu 
>    $ bash scripts / dreamview.sh start_fe 
>    将ctrl + c输入到teminal 中当终端输出停止时停止该过程，如图所示。
>    ![图片](https://user-images.githubusercontent.com/50321853/60863163-6199d400-a252-11e9-95a3-a14d22ed1002.png)
> 2. 打开另一个终端（名为b），并输入：
>    $ sudo apt-get install psmisc 
>    $ sudo lsof -i：8888 
>    在此步骤中我没有显示结果。
> 3. 返回到终端a，输入：
>    $ bash scripts / dreamview.sh 
>    我只有“推出模块dreamview”，但不是“Dreamview运行在[http：// localhost：8888”](http://localhost:8888%E2%80%9D) 
>    $ cyber_recorder play -f docs / demo_guide / demo_3 .5。记录 - 循环
>    ![图片](https://user-images.githubusercontent.com/50321853/60864078-1cc36c80-a255-11e9-8ef3-fd15a3fbeb8c.png)
> 4. 打开Chrome并输入localhost：8888，然后我获得了离线演示。

Hello, have you installed Apollo 5.0? I have a question for you to help me.The docker compiled successfully and dreamview started successfully, but when localhost: 8888 was turned on, there was no response.

**Comment by audier0879** [comment]
> @audier0879 I tried the solutions you suggested both the cyber_recorder command and by performing git lfs fetch --all but nothing has changed it is still not opening and cyber_recorder is giving the following error:
> ![image](https://user-images.githubusercontent.com/13648313/61455338-36d60c80-a931-11e9-89c1-daedc6c06437.png)
> 
> Do you think that there can be issue with the PCL?

I think you can search the problem "cyber_recorder: command not found" in the issues search bar.

**Comment by audier0879** [comment]
> > 嗨，AyushiRathore
> > 我想我有类似你的问题，我做了以下步骤来解决它，我希望它可以帮到你。
> > PC：intel i5-7500,8G DDR4，集成显卡
> > 操作系统：ubuntu 16.04
> > 版本：apollo_5.0
> > 
> > 1. 打开一个teminal（命名为a）输入：
> >    $ bash docker
> >    / scripts / dev_start.sh
> >    $ bash docker / scripts / dev_into.sh $ bash apollo.sh build_cpu
> >    $ bash scripts / dreamview.sh start_fe
> >    将ctrl + c输入到teminal 中当终端输出停止时停止该过程，如图所示。
> >    ![图片](https://user-images.githubusercontent.com/50321853/60863163-6199d400-a252-11e9-95a3-a14d22ed1002.png)
> > 2. 打开另一个终端（名为b），并输入：
> >    $ sudo apt-get install psmisc
> >    $ sudo lsof -i：8888
> >    在此步骤中我没有显示结果。
> > 3. 返回到终端a，输入：
> >    $ bash scripts / dreamview.sh
> >    我只有“推出模块dreamview”，但不是“Dreamview运行在[http：// localhost：8888”](http://localhost:8888%E2%80%9D)
> >    $ cyber_recorder play -f docs / demo_guide / demo_3 .5。记录 - 循环
> >    ![图片](https://user-images.githubusercontent.com/50321853/60864078-1cc36c80-a255-11e9-8ef3-fd15a3fbeb8c.png)
> > 4. 打开Chrome并输入localhost：8888，然后我获得了离线演示。
> 
> Hello, have you installed Apollo 5.0? I have a question for you to help me.The docker compiled successfully and dreamview started successfully, but when localhost: 8888 was turned on, there was no response.

what is your browser，Microsoft IE or google chrome？

**Comment by AyushiRathore** [comment]
> > 嗨，AyushiRathore
> > 我想我有类似你的问题，我做了以下步骤来解决它，我希望它可以帮到你。
> > PC：intel i5-7500,8G DDR4，集成显卡
> > 操作系统：ubuntu 16.04
> > 版本：apollo_5.0
> > 
> > 1. 打开一个teminal（命名为a）输入：
> >    $ bash docker
> >    / scripts / dev_start.sh
> >    $ bash docker / scripts / dev_into.sh $ bash apollo.sh build_cpu
> >    $ bash scripts / dreamview.sh start_fe
> >    将ctrl + c输入到teminal 中当终端输出停止时停止该过程，如图所示。
> >    ![图片](https://user-images.githubusercontent.com/50321853/60863163-6199d400-a252-11e9-95a3-a14d22ed1002.png)
> > 2. 打开另一个终端（名为b），并输入：
> >    $ sudo apt-get install psmisc
> >    $ sudo lsof -i：8888
> >    在此步骤中我没有显示结果。
> > 3. 返回到终端a，输入：
> >    $ bash scripts / dreamview.sh
> >    我只有“推出模块dreamview”，但不是“Dreamview运行在[http：// localhost：8888”](http://localhost:8888%E2%80%9D)
> >    $ cyber_recorder play -f docs / demo_guide / demo_3 .5。记录 - 循环
> >    ![图片](https://user-images.githubusercontent.com/50321853/60864078-1cc36c80-a255-11e9-8ef3-fd15a3fbeb8c.png)
> > 4. 打开Chrome并输入localhost：8888，然后我获得了离线演示。
> 
> Hello, have you installed Apollo 5.0? I have a question for you to help me.The docker compiled successfully and dreamview started successfully, but when localhost: 8888 was turned on, there was no response.

Google chrome

**Comment by AyushiRathore** [comment]
> > > 嗨，AyushiRathore
> > > 我想我有类似你的问题，我做了以下步骤来解决它，我希望它可以帮到你。
> > > PC：intel i5-7500,8G DDR4，集成显卡
> > > 操作系统：ubuntu 16.04
> > > 版本：apollo_5.0
> > > 
> > > 1. 打开一个teminal（命名为a）输入：
> > >    $ bash docker
> > >    / scripts / dev_start.sh
> > >    $ bash docker / scripts / dev_into.sh $ bash apollo.sh build_cpu
> > >    $ bash scripts / dreamview.sh start_fe
> > >    将ctrl + c输入到teminal 中当终端输出停止时停止该过程，如图所示。
> > >    ![图片](https://user-images.githubusercontent.com/50321853/60863163-6199d400-a252-11e9-95a3-a14d22ed1002.png)
> > > 2. 打开另一个终端（名为b），并输入：
> > >    $ sudo apt-get install psmisc
> > >    $ sudo lsof -i：8888
> > >    在此步骤中我没有显示结果。
> > > 3. 返回到终端a，输入：
> > >    $ bash scripts / dreamview.sh
> > >    我只有“推出模块dreamview”，但不是“Dreamview运行在[http：// localhost：8888”](http://localhost:8888%E2%80%9D)
> > >    $ cyber_recorder play -f docs / demo_guide / demo_3 .5。记录 - 循环
> > >    ![图片](https://user-images.githubusercontent.com/50321853/60864078-1cc36c80-a255-11e9-8ef3-fd15a3fbeb8c.png)
> > > 4. 打开Chrome并输入localhost：8888，然后我获得了离线演示。
> > 
> > 
> > Hello, have you installed Apollo 5.0? I have a question for you to help me.The docker compiled successfully and dreamview started successfully, but when localhost: 8888 was turned on, there was no response.
> 
> what is your browser，Microsoft IE or google chrome？

Google chrome

**Comment by AyushiRathore** [comment]
My dreamview has launched successfully after following the solution:
I installed PCL library and CPU does not support AVX instructions solution as given in the link below:
https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md
after this, my dreamview has been launched successfully !!

**Comment by hadiamiri** [comment]
I also have the same problem, I tried the suggested solution to build pcl version 1.7.2 but inside docker I get error about boost library.

```
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_system
          boost_filesystem
          boost_thread
```

**Comment by AyushiRathore** [comment]
> I also have the same problem, I tried the suggested solution to build pcl version 1.7.2 but inside docker I get error about boost library.
> 
> ```
> CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.65.1
> 
>   Boost include path: /usr/include
> 
>   Could not find the following Boost libraries:
> 
>           boost_system
>           boost_filesystem
>           boost_thread
> ```

Have you tried updating your cmake. Because what I understood is that its not error of PCL its from cmake. This problem can also be there due to cmake version, in my case I used cmake 2.7

**Comment by hadiamiri** [comment]
@AyushiRathore I updated the cmake and it works.
