### ISSUE TITLE
[Pull docker images]How to pull the apollo docker image fast in china

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#9093]
Dear apollo developer,

     i need your help,how to pull the apollo docker images fast in china,
     pull the images is  slow.............slow............slow.............slow...................failed!!!!!!!!!!!!
     i have try many times,but failed,
     if someone know how to do,thanks a lot!

**Comment by christian-lanius** [comment]
Have you tried setting the INCHINA flag ( bash/docker/scripts/dev_start.sh --docker-cn-mirror)?

**Comment by freeclouds** [comment]
xxx@robot:~/apollo/apollo$ sudo bash docker/scripts/dev_start.sh --docker-cn-mirror
[INFO] Start pulling docker image registry.docker-cn.com/apolloauto/apollo:dev-x86_64-20190617_1100 ...
Error response from daemon: Get https://registry.docker-cn.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[ERROR] Failed to pull docker image.

**Comment by freeclouds** [comment]
> Have you tried setting the INCHINA flag ( bash/docker/scripts/dev_start.sh --docker-cn-mirror)?
failed

**Comment by sinopec** [comment]
using a mirror of docker hub

**Comment by freeclouds** [comment]
thanks a lot, 
i have change a vpn and use high speed internet ,
i have downed the images,
so vpn+high speed internet:
use this command------->  bash/docker/scripts/dev_start.sh 
can downed image!!
