### ISSUE TITLE
Blocking issue of BroadcastData

### ISSUE THREAD

**Issue by tigert1998** [ApolloAuto/apollo#9102]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: ubuntu 16.04
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
1. Open multiple dreamview frontends
2. `BroadcastData` by 10hz
3. Force one of the frontend to be in pending state (debug js, `confirm` or `alert`, etc)
4. Wait a moment since chrome has a buffer for data which hasn't been handled 
5. Then all the frontends with the backend websocket will get stuck

### Supporting materials (screenshots, command lines, code/script snippets):

```c++
// WebSocketHandler::BroadcastData
bool all_success = true;
for (Connection *conn : connections_to_send) {
  if (!SendBinaryData(conn, data, skippable)) {
    all_success = false;
  }
}
return all_success;

// WebSocketHandler::SendData
int ret = 0;
PERF_BLOCK(
    StrCat(name_, ": Writing ", data.size(), " bytes via websocket took"),
    0.1) {
  ret = mg_websocket_write(conn, op_code, data.c_str(), data.size());
}
```

Here we could see `mg_websocket_write` is a blocking method, if one of the frontend refuses to ACK, `BroadcastData` will no longer return. Is there anyway to fix it?

**Comment by tigert1998** [comment]
Is this issue related here?
https://github.com/civetweb/civetweb/issues/517

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
