### ISSUE TITLE
Why rosbag_to_record does not support sensor_msgs/CompressedImage?

### ISSUE THREAD

**Issue by alexbuyval** [ApolloAuto/apollo#9106]
Hi,

I would like to test the Apollo 5.0 with own data. I was going to convert my bags files into CyberRT records by 'rosbag_to_record' utility, however, I faced that the utility does not support image topics (sensor_msgs/CompressedImage, sensor_msgs/Image).

I looked at the [source code](https://github.com/ApolloAuto/apollo/blob/master/modules/data/tools/rosbag_to_record/rosbag_to_record.cc) and I didn't find any mentions of image topic.

Why did you not include these types of topics in the conversion? Are there any restrictions from CyberRT?

Regards,
Alex

**Comment by baowanyu** [comment]
This tool only supports topics for the old version of Apollo project. Some topics are not used in Apollo project, you need to customize the tool yourself.

**Comment by alexbuyval** [comment]
But you used the image topics in the old version, is not?

**Comment by baowanyu** [comment]
We don't record pictures and distribute them, So our tools don't support image-related topics. I recommend that you customize our “rosbag_to_record” tools to meet your needs. You can contact us when you encounter any problems that cannot be solved in development.

**Comment by alexbuyval** [comment]
@baowanyu  I see. Thank you!
