### ISSUE TITLE
Handle return value kHungarianOptimizerColNotFound from FindPrimeInRow()

### ISSUE THREAD

**Issue by pavel-cyngn** [ApolloAuto/apollo#9114]
Potential bug if ```int FindPrimeInRow(const size_t row)``` returns kHungarianOptimizerColNotFound, which is -1.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo installed from source**:
- **Apollo version 3.0, 5.0, and on master are affected (July 9, 2019)**:

### Steps to reproduce the issue:
- **'col'** may be out of bound for column index 'assignments_[count].second ' after casting to size_t:

![image](https://user-images.githubusercontent.com/47793128/60925855-a8d79300-a259-11e9-993b-114f876a45fe.png)

**Comment by daohu527** [comment]
@pavel-cyngn Thx! The bug has been fixed.
