### ISSUE TITLE
what's the inspva topics's azimuth  means?

### ISSUE THREAD

**Issue by debuleilei** [ApolloAuto/apollo#9125]
Hi, I'm wondering Where is the origin of coordinates about the azimuth in the inspva? it's imu position or GPS Main antenna，and what 's the zero  represente?(north or east) ,what's the positive direction ,clockwise or counterclockwise? waiting for your reply,thanks

**Comment by xmyqsh** [comment]
@debuleilei azimuth is another name of yaw.
Both imu and Multi GPS antenna could estimate it.
Which specific `cyber topic` or `code parameter` are you talking about?

**Comment by michaelhsmart** [comment]
@xmyqsh azimuth and yaw are similar, but not typically the same. Azimuth is world-fixed while yaw is body-fixed.

@debuleilei Does this link partially help? https://docs.novatel.com/oem7/Content/SPAN_Logs/INSPVA.htm

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
