### ISSUE TITLE
cyber/io/example/tcp_echo_server&client don't work as expected

### ISSUE THREAD

**Issue by storypku** [ApolloAuto/apollo#9126]
**Describe the bug**
TCP echo example in cyber/io/example doesn't work as expected.

**To Reproduce**
1. bazel build from source //cyber/io:tcp_echo_server and //cyber/io:tcp_echo_client  (on my PX2 machine)
2. In terminal A, run `bazel-bin/cyber/io/tcp_echo_server 8235`
3. In terminal B, run `bazel-bin/cyber/io/tcp_echo_client 8235`
And you will see both `server` and `client` blocks without any useful console log.

**Expected behavior**
What a typical echo server/client will do.

**Screenshots**
```
$ bazel-bin/cyber/io/tcp_echo_server 8235
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0711 23:39:28.203034  8966 global_data.cc:150] [tcp_echo_server] host ip: 172.21.81.48
[NO FURTHER OUTPUT, BLOCKING]
```

```
$ bazel-bin/cyber/io/tcp_echo_client 8235
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0711 23:39:36.357502  8991 global_data.cc:150] [tcp_echo_client] host ip: 172.21.81.48
[NO FURTHER OUTPUT, BLOCKING]
```

**Desktop (please complete the following information):**
 - OS: [ubuntu 16.04]
 - Browser [No need]
 - Version [Apollo master branch with latest commit id as of reporting: a2e382f0 ]

**Comment by storypku** [comment]
Tried the udp_echo_server/client example, the same issue exists.

**Comment by quning18** [comment]
are u running the example in docker?

**Comment by storypku** [comment]
> are u running the example in docker?

Nope. Run without docker.  Have set the CYBER_IP, CYBER_PATH env variables.

**Comment by xmyqsh** [comment]
interesting

**Comment by quning18** [comment]
We have submitted a pull request to fix this problem. 

https://github.com/ApolloAuto/apollo/pull/9152

Please reopen if that doesn't work. Closing for now.

**Comment by storypku** [comment]
Have tested both tcp and udp echo server/client examples on aarch64 and x86_64 platforms, It works fine.
