### ISSUE TITLE
Traffic light right turn unprotected scenario triggered safety mode 

### ISSUE THREAD

**Issue by louis016** [ApolloAuto/apollo#9143]
### System information

- OS Platform and Distribution: Linux Ubuntu 14.04:
- Apollo installed from source**:
- Apollo version: 3.5**:

### Steps to reproduce the issue:
- we are trying to implement the traffic light unprotected right turn scenario, when planning jump into stage_stop, the car will stop in front of the stop line and wait for 3 seconds, then it will jump into the next stage. 

- However, when our car stop in front of the stop line and wait for about 2 seconds, planning module triggered safety mode and break down.

##########################################
  if (scenario_config_.enable_right_turn_on_red()) {
    // check on wait-time
    if (traffic_light_all_stop && !traffic_light_all_green) {
      if (GetContext()->stop_start_time == 0.0) {
        GetContext()->stop_start_time = Clock::NowInSeconds();
      } else {
        auto start_time = GetContext()->stop_start_time;
        const double wait_time = Clock::NowInSeconds() - start_time;
        ADEBUG << "stop_start_time[" << start_time << "] wait_time["
               << wait_time << "]";
        if (wait_time >
            scenario_config_.red_light_right_turn_stop_duration_sec()) {
          return FinishStage(false);
        }
      }
    }
#########################################################
- We have already checked the planning log and mainborad log, there is no error. We have no idea why this scenario will trigger safety mode. Could you please tell us how can we find the error that triggered the safety mode?

- Is Apollo3.5 supporting the traffic light unprotected right turn scenario or this scenario has fixed in Apollo5.0?

**Comment by louis016** [comment]
@bigwhite @aboarya PLEASE HELP US, APOLLO TEAM : ( @natashadsouza

**Comment by louis016** [comment]
@techoe  Please help us : )

**Comment by jmtao** [comment]
@louis016 what's safety mode?

**Comment by louis016** [comment]
> @louis016 what's safety mode?

![微信图片_20190717163557](https://user-images.githubusercontent.com/38492966/61360425-fd5dbc80-a8b0-11e9-9d74-e7e2de90b4dd.jpg)

**Comment by jmtao** [comment]
@louis016  this happens where there's some error from planning. 
code:
https://github.com/ApolloAuto/apollo/blob/master/modules/monitor/software/functional_safety_monitor.cc
line 34-42. 

We don't have enough context on what's going on in your case. It would be much easier if you just debug by yourself.  Let us know if you need further support.

**Comment by jmtao** [comment]
Hi @louis016 , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
