### ISSUE TITLE
Does Apollo trained a CNNSeg model for Velodyne 16?

### ISSUE THREAD

**Issue by HanFa** [ApolloAuto/apollo#9144]
Hi Developers,

I am wondering if the CNN segmentation model has been trained for 16-channel LiDAR. There seem to be three models for VLP-16, VLP-64, VLP-128.

`➜  cnnseg git:(master) ✗ pwd
/apollo/modules/perception/production/data/perception/lidar/models/cnnseg
`

`
➜  cnnseg git:(master) ✗ ls
velodyne128 velodyne16  velodyne64
`

Are the models retrained with 16-channel, 64 and 128 dataset respectively?

If we want to use this CNN model with Velodyne 32, shall we retrain the model with the 32-channel dataset? Are there any instructions on how to train a CNN model?

Thanks so much for your attention!

**Comment by weidezhang** [comment]
unfortunately, cnn training pipeline is no open source yet. I would suggest you can try using vlp64 model on vlp32 data.
