### ISSUE TITLE
question about LaneOverlapInfo

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#9155]
apollo 3.5
Where does start_s and end_s of the LaneOverlapInfo refer?

**Comment by jmtao** [comment]
@wanggujin there is no LaneOverlapInfo. There is a PathOverlap.
https://github.com/ApolloAuto/apollo/blob/master/modules/map/pnc_map/path.h
line 91. 

A lane overlap can be PathOverlap. 
start_s: s value of the start point of this overlap (or min s of this overlap), along the current reference line
end_s: s value of the end point of this overlap (or max s of this overlap), along the current reference line

**Comment by wanggujin** [comment]
@jmtao 
thank you.
i mean the LaneOverlapInfo in map module,
you can look this, 
https://github.com/ApolloAuto/apollo/blob/r5.0.0/modules/map/proto/map_overlap.proto

Where does start_s and end_s of the LaneOverlapInfo refer?

**Comment by xmyqsh** [comment]
@wanggujin 
[LaneOverlapInfo](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L122-L126)
[start_s](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L138)
[end_s](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L140)

**Comment by wanggujin** [comment]
@jmtao @xmyqsh 
thank you for your answer.
my question is that i find the LaneOverlapInfo object is used in some function, as follow:
[LaneOverlapInfo](https://github.com/ApolloAuto/apollo/blob/r5.0.0/modules/prediction/common/junction_analyzer.cc#L67)
[LaneOverlapInfo](https://github.com/ApolloAuto/apollo/blob/master/modules/prediction/container/obstacles/obstacle_clusters.cc#L215)

but i can't find the initialize about the LaneOverlapInfo object in the entire source code directory.
i don't know that's why. 
whether the object is no longer use in the future?

**Comment by jmtao** [comment]
@wanggujin ok now I see what you refer to. 
If you look at this function: 
Prot[oOrganizer::GetLaneObjectOverlapElements](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L117)
A ObjectOverlapInfo is always associated with a "base" lane. 
e.g Along a lane "11", there can be some overlaps  "22", "33", "44" and etc, overlapping with the base lane "11". 
The start_s of the *base* lane "11" would be 0. 
start_s of overlap "22": s value of the start point of this overlap (or min s of this overlap), along lane "11", given start_s of lane "11" as 0.
end_s of overlap "22": s value of the end point of this overlap (or max s of this overlap), along lane "11", given start_s of lane "11" as 0.

**Comment by wang820203420** [comment]
> @wanggujin
> [LaneOverlapInfo](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L122-L126)
> [start_s](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L138)
> [end_s


> @wanggujin
> [LaneOverlapInfo](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L122-L126)
> [start_s](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L138)
> [end_s](https://github.com/ApolloAuto/apollo/blob/master/modules/map/hdmap/adapter/proto_organizer.cc#L140)

test

**Comment by jmtao** [comment]
Hi @wanggujin , hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
