### ISSUE TITLE
debug_roi

### ISSUE THREAD

**Issue by MengWangTHU** [ApolloAuto/apollo#9159]
### System information

- **OS Platform and Distribution  Ubuntu 16.04**:
- **Apollo installed from source **:
- **Apollo version3.5**:

尊敬的作者和各位贡献者：
我在学习交通灯信号检测的时候，发现traffic_light类有一个独特的成员称为debug_roi，这个框被可视化之后是一个远大于红绿灯范围的白色线框，我不是特别清楚这个框的来源和作用，请问哪位专家可以做一解读？
万分感谢！

**Comment by daohu527** [comment]
这个框是感兴趣区域，红绿灯检测过程中会根据高精度地图中的红绿灯坐标进行投影，从而找到图片中红绿灯的大致位置，提高检测精度和效率。
