### ISSUE TITLE
The docker compiled successfully and dreamview started successfully, but when localhost: 8888 was turned on, there was no response.

### ISSUE THREAD

**Issue by WooLiGuaiguai** [ApolloAuto/apollo#9175]
### System information

- **OS Platform and Distribution :Linux Ubuntu 16.04LTS
- **Apollo installed from :source 
- **Apollo version:5.0

### Steps to reproduce the issue:
First, the computer processor is Intel < Core < i7-8700 CPU @ 3.20 GHz * 12, then install Ubuntu 16.04.
Then：
sudo apt-get install git
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install
Then： 
git clone https://github.com/apolloauto/apollo
cd apollo
bash docker/setup_host/install_docker.sh
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
bash apollo.sh build
bash scripts/bootstrap.sh
Then the terminal displays：
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Dreamview is running at http://localhost:8888

But when I opened the website, there was nothing.
![2019-07-19 14-21-51屏幕截图](https://user-images.githubusercontent.com/49585908/61514023-813eb280-aa31-11e9-8b65-5f400a3dcb06.png)

/apollo/data/log/dreamview.log.info.20190718-203718.11952：
I0718 20:37:48.414474 11970 simulation_world_service.h:224]  Has not received any data from /apollo/perception/obstacles
I0718 20:37:48.414476 11970 simulation_world_service.h:224]  Has not received any data from /apollo/prediction
I0718 20:37:48.414479 11970 simulation_world_service.h:224]  Has not received any data from /apollo/planning
![2019-07-19 14-25-57屏幕截图](https://user-images.githubusercontent.com/49585908/61514031-88fe5700-aa31-11e9-9e76-713cdcb10afd.png)

I hope you can help me. Thank you.

**Comment by xiaoxq** [comment]
I'm wondering which document are you following, because Git-LFS has been retired for a while before Apollo 5.0. Could you refer me to it?

**Comment by WooLiGuaiguai** [comment]
> 我想知道你关注哪个文件，因为Git-LFS在Apollo 5.0之前已经退役了一段时间。你能把我推荐给我吗？

I didn't install LFS before, and then I saw someone mention a similar problem on issue. It was done by installing lfs, and I installed it 
This is the link to that question：
https://github.com/ApolloAuto/apollo/issues/6467
Thanks

**Comment by natashadsouza** [comment]
@WooLiGuaiguai please refer to our [build guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md) on how to set up Apollo. We have retired Git LFS. 
Let me know if you are still seeing the issue when you use the build guide.

**Comment by vvForedawn** [comment]
Although I didn't install LFS, I have the same problem as you.
But I found if use firefox to open http://localhost:8888, It's OK.
