### ISSUE TITLE
sins.h file in apollo 5.0 build failed

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#9185]
### System information

- OS Platform and Distribution ( Linux Ubuntu 14.04):
- **Apollo installed from (source):
- **Apollo version (5.0):

### Steps to reproduce the issue:
when I build apollo 5.0 ,some errors happenend:

ERROR: (07-20 03:39:22.795) /apollo/modules/localization/msf/local_integ/BUILD:5:1: C++ compilation of rule '//modules/localization/msf/local_integ:localization_msf_local_integ' failed (Exit 1).
modules/localization/msf/local_integ/localization_integ_process.cc: In member function 'void apollo::localization::msf::LocalizationIntegProcess::RawImuProcess(const apollo::localization::msf::ImuData&)':
modules/localization/msf/local_integ/localization_integ_process.cc:107:10: error: 'class apollo::localization::msf::Sins' has no member named 'GetRemoveBiasImu'
   sins_->GetRemoveBiasImu(&corrected_imu_);

I find sins.h file in /usr/local/apollo/local_integ/include and there is no function called GetRemoveBiasImu. Is there anything wrong with docker image apollo:dev-x86_64-20190617_1100 ?

### Supporting materials (screenshots, command lines, code/script snippets):

![image](https://user-images.githubusercontent.com/30464144/61574122-e86d6d00-aaec-11e9-8e3e-997c9d5e05c1.png)
![image](https://user-images.githubusercontent.com/30464144/61574125-fde29700-aaec-11e9-88b6-cbbdf1e4ff59.png)

**Comment by natashadsouza** [comment]
@qwetqwe  please refer to our [build guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md) on how to set up Apollo. Let me know if you are still seeing the issue when you use the build guide.

**Comment by Caitmaire** [comment]
The sins.h folder does not contain the GetRemoveBiasImu function. I think line 107 has to be removed.

**Comment by qwetqwe** [comment]
> @qwetqwe please refer to our [build guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md) on how to set up Apollo. Let me know if you are still seeing the issue when you use the build guide.

I build according to build guide step. Obviously, there must be something wrong between sins.h or localization_integ_process.cc

**Comment by einspyon** [comment]
Why I can't find anything about "sins.h" in source code ?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
