### ISSUE TITLE
Routing Module Provides a Service API

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#9197]
**Is your feature request related to a problem? Please describe.**
Currently, the routing module reads in `RoutingRequest` through the Component API: https://github.com/ApolloAuto/apollo/blob/master/modules/routing/routing_component.h#L27. And it writes via the `cyber::Writer` API: https://github.com/ApolloAuto/apollo/blob/master/modules/routing/routing_component.h#L37. A new modules can publish requests by only knowing the topic name and routing request type. But that module would have to implement it's own timeout and blocking functionality to get the results. Also, it would be up to the module publishing the routing request to correlate the request to the response.

**Describe the solution you'd like**
It would be convenient from other modules to have a service call to make the routing request and get a routing response as well as update the other modules listening for a routing response. The routing module already has a map so it should be ready to process it.

**Comment by jmtao** [comment]
@Fla3inH0tCheet0s is there an example on what scenario service APIs provided by Routing module can support better?  e.g., what module, besides the existing ones, may send routing requests via routing service APIs? 
We want to understand the request better.   Thx!

**Comment by Fla3inH0tCheet0s** [comment]
The specific scenario that I had in mind was sending a routing request via a web interface. In this case, a module can be made that converts communications like websockets to cyber. It's beneficial to report errors. Not creating a route in time is considered an error. Instead of just publish and subscribe, a blocking remote call would preferred. This feature can be done with publish and subscribe calls and threading primitives, but it is tricky to implement correctly.

**Comment by jmtao** [comment]
@Fla3inH0tCheet0s we currently don't support remote routing request. we may add that in the future. It's not gonna be as simple as a set of APIs only. 

Thanks for supporting Apollo!
