### ISSUE TITLE
Can I use AWS S3 service to do Vehicle Control Calibration?

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#9198]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

Hi, I'm trying to use vehicle calibration as explained in the following vehicle control calibration. 
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md

In the first step, I followed the instruction in Data pipeline proxy document.
https://github.com/ApolloAuto/apollo/blob/master/modules/tools/fuel_proxy/README.md
It said that I should have your own S3-compatible cloud storage. I think that I can use AWS S3 service to do that. But when I check the job config file, it's all about BOS service. Does that mean I can't use AWS S3 service? Is there job config example file for AWS S3?
https://github.com/ApolloAuto/apollo/blob/master/modules/tools/fuel_proxy/proto/job_config.proto

Best
Taehyung Kim

**Comment by xiaoxq** [comment]
Thank you for heads up, Taehyung!
Only BOS is supported for now, but we are working on supporting another global cloud provider soon. Please stay tuned :)
If it's an urgent need, maybe you can try BOS which is pretty similar to S3. You can use tools like `s3fs` and `boto3`.

**Comment by cyberphysicalrobotics** [comment]
Thanks for your reply. 
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md

**Comment by cyberphysicalrobotics** [comment]
Thanks for your reply.
I'm doing the following instruction. 
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md

There's not enough information to collect data. When I see data collection monitor, I couldn't make the progress bar changed. In order to see progress bar change, Is the Setting up Apollo Fuel Proxy essential ?

Best
Taehyung Kim
