### ISSUE TITLE
Perception (LiDAR) ROI filter issue

### ISSUE THREAD

**Issue by warden2018** [ApolloAuto/apollo#9199]
### System information

- **OS Platform and Distribution Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 3.0**:

### Steps to reproduce the issue:

- **Currently we are testing perception module using Pointcloud.**
- **In modules/perception/obstacle/onboard/lidar_process_subnode.cc:**
`if (roi_filter_->Filter(point_cloud, roi_filter_options,
                            roi_indices.get()))`

- **I found that it calls : HdmapROIFilter::Filter method. In this method the last call is return FilterWithPolygonMask(cloud_local, polygons_local, roi_indices);
In FilterWithPolygonMask method, DrawPolygonInBitmap is called and the error occurs in 3. Draw grids in bitmap based on scan intervals  which is commented in code. **

`if (scan_interval.first > scan_interval.second) {
        AERROR << "scan interval is not valid: "
               << "scan_interval.first = " << scan_interval.first << ", "
               << "scan_interval.second = " << scan_interval.second << ".";
      }`
![15562213](https://user-images.githubusercontent.com/48422255/61679624-5f974100-ad39-11e9-8d89-a1f64502ddcd.jpg)

- **So we are not sure whether there is something wrong with the map polygon which is the input of the Filter process or other input. We hope someone can help answer the question and give us some advice.**

**Comment by luqiang21** [comment]
Hi @warden2018, I am just guessing. Maybe you want to check your map file, do your lanes have correct left and right boundaries? We encountered problems when our map had wrong boundary lines for lanes. For a lane, we had the right boundary line same as the left one.

**Comment by warden2018** [comment]
Hi @luqiang21 , according to your suggestion, I should check the map input part. So what does the road/lane boundary looks like and how  it should fit the Apollo requirement? Could you please kindly show some examples.

**Comment by luqiang21** [comment]
@warden2018 I am not 100% sure your problem is due to map file. But you can try to check it. For the map example, you can check [here](https://github.com/lgsvl/apollo-3.5/blob/simulator/modules/map/data/shalun/sim_map.txt) and look at the structure of a lane. The point's coordinate in central_curve, left_boundary, right_boundary shouldn't be the same.

**Comment by warden2018** [comment]
@luqiang21 Thanks for your help. I will update after the check.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
