### ISSUE TITLE
Questions about Vehicle Control Calibration Tool

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#9211]
System information
OS Platform and Distribution (e.g., Linux Ubuntu 14.04): Ubuntu 16.04
Apollo installed from (source or binary): Source
Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 5.0

I'm doing the following instruction.
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md

Q1. There's not enough information to collect data. When I see data collection monitor, I couldn't make the progress bar changed. In order to see progress bar change, Is the Setting up Apollo Fuel Proxy essential?

Q2.When I do vehicle control calibration, should three components (GPS, Localization, Recorder) and modules (Canbus, Recorder, Sensors) work?
![image](https://user-images.githubusercontent.com/14055939/61754462-275b2700-ad68-11e9-8aad-030f1b293910.png)

Q3. Aside modules mentioned in Q2, do I need to run other modules (Transform, Prediction, Planning, Perception, Localization, Control, etc)?

Q4. There are two vehicle calibration docs like the following.
How to Update Vehicle Calibration for Throttle and Brakes: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_update_vehicle_calibration.md
Vehicle Control Calibration: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md

I think second one provides more precise calibration table because it has more specific cases like Go Straight, Reverse: Go Straight or Branch Left/Right. What's each calibration tool for? Are they separate calibration tool? Are they related each other?

Q5. I'm using with LGSVL simulator to test parking. When it comes to speed and acceleration, I think it seems like vehicle calibration table is wrong for this vehicle. What do you think about this one?
![image](https://user-images.githubusercontent.com/14055939/61754555-83be4680-ad68-11e9-8da3-56ca77843606.png)

Best
Taehyung Kim

**Comment by sjiang2018** [comment]
Thank you for your interest in Apollo platform. 
Q1. The configure file is mkz7_data_collection_table.pb.txt. It is in apollo repo.
Q2. Yes.
Q3. No. It is not at autonomous driving mode. Thus, we don't need other modules.
Q4. https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md
This one is the latest version.
Q5. To verify a calibration table, you may try a straight trajectory for test. Parking involves both longitudinal controller and lateral controller. It is hard to tell which controller went wrong.

**Comment by sjiang2018** [comment]
Hi @cyberphysicalrobotics, hope our answer resolved your question. We will close the issue for now. If you have any additional question, please feel free to open a new issue. Our engineer team are more than happy to help that.

Thank you for supporting Apollo!
