### ISSUE TITLE
problem in building apollo5.0:Cloning ad-rss-lib from github is to slow

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#9219]
When I build apollo 5.0: `./apollo.sh build`, it take a lot of time in this step:
`Cloning https://github.com/intel/ad-rss-lib: Receiving objects (1479 / 17648)`
maybe 2hours later, `Build failed`,error is: 
 ` /apollo/modules/planning/tasks/rss/BUILD:5:1: no such package '@ad_rss_lib//': Error cloning repository: Premature EOF caused by Premature EOF caused by Premature EOF and referenced by '//modules/planning/tasks/rss:decider_rss'.`
May I clone `ad-rss-lib` by myself?In which path?

### System information

- **OS Platform and Distribution:Linux Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 5.0**:

**Comment by natashadsouza** [comment]
@BigBenSure could you answer the System information questions above for better understanding?

**Comment by BigBenSure** [comment]
My system is Win10, and I build apollo 5.0 in docker Version 18.06.1-ce-win73 (19507), yesterday I try to build it again, maybe 1.5hours later , build succeed. But cloning ad-rss-lib is still slowly(I'm in China). So the problem is solved. If we have a faster way to install ad-rss-lib, it could be better.

**Comment by gengqx** [comment]
See [PR](https://github.com/ApolloAuto/apollo/pull/8085),Currentlly apollo team seem did not want to update their docker,So,You can install the lib into docker ,commit the docker,modified WORKSPACE.in file from git to local.

**Comment by BigBenSure** [comment]
Thank you very much!

**Comment by zhanghming** [comment]
@gengqx Hello,
May I ask how to install the rss lib into docker and how to commit the docker? Could you elaborate about the process? I also encounter this problem and puzzled me for a long time.

**Comment by BigBenSure** [comment]
> @gengqx Hello,
> May I ask how to install the rss lib into docker and how to commit the docker? Could you elaborate about the process? I also encounter this problem and puzzled me for a long time.
> 
> Below is the output when execute `bash apollo.sh build`:
> 
> ```shell
> [INFO] Building with --jobs=12 --ram_utilization_factor 80 for x86_64
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
> ERROR: (04-27 14:44:26.762) /apollo/modules/planning/tasks/deciders/rss_decider/BUILD:21:1: no such package '@ad_rss_lib//': Error cloning repository: Premature EOF caused by Premature EOF caused by Premature EOF and referenced by '//modules/planning/tasks/deciders/rss_decider:rss_decider_test'.
> ERROR: (04-27 14:44:26.814) Analysis of target '//modules/planning/tasks/deciders/rss_decider:rss_decider_test' failed; build aborted.
> INFO: (04-27 14:44:26.814) Elapsed time: 636.924s
> ============================
> [ERROR] Build failed!
> [INFO] Took 637 seconds
> ============================
> ```
我看你资料在北京,国内网络原因,可以改ad rss lib的源.具体方法是:
在/apollo/WORKSPACE.in里,第47到第53,替换成:
```bash
#ad-rss-lib
new_git_repository(
    name = "ad_rss_lib",
    build_file = "third_party/rss_lib.BUILD",
    tag = "v1.1.0",
    remote = "https://gitee.com/audier0879/ad-rss-lib",
)
```
把remote换成gitee的.欢迎补充.
