### ISSUE TITLE
Cannot launch perception camera, cyber channels (front6mm and 12mm) not running

### ISSUE THREAD

**Issue by gaushivs** [ApolloAuto/apollo#9232]
### System information

**
-  Linux Ubuntu 14.04 :
- Apollo installed from source
- Apollo version 3.5 - Forked
- Velodyne Lidar is used
- Camera : LI -AR023ZWDR USB3.0 
- Modified the following files :** 

camera_front_12mm.pb.txt 
camera_front_6mm.pb.txt  
front_6mm_intrinsics.yaml 
short_camera_intrinsics.yaml
short_camera_intrinsics.yaml 

What was modified ? 
- height was changed from 1080 to 1024

Reason for modification :
- When the height was 1080, the camera cyber channels did not transmit any data (red on Cyber monitor) 
![image](https://user-images.githubusercontent.com/51798238/61900582-ba17d500-aed2-11e9-8ed5-40bb47683094.png)

- When the height was changed to 1024 - the camera cyber channels started transmitting data
However, perception_camera launch file fails to run and the error is thrown as shown below. 
`image_8u.h:62] Check failed: offset_ + blob_->offset({rows - 1, cols - 1, channels_ - 1}) <= blob_->count() (6220799 vs. 5898240)`

Snapshot from the cybermonitor when the height is 1024 :
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/51798238/61900941-7b364f00-aed3-11e9-84a9-e605a898068d.png)

** Please see that the Camera Timestamp is not updated **

Refer log file : 
[mainboard_default.log.info.20190725-110428.17531.txt](https://github.com/ApolloAuto/apollo/files/3432876/mainboard_default.log.info.20190725-110428.17531.txt)

### Steps to reproduce the issue:
- Run Bootstrap.sh, start Dreamviewer
- Set Vehicle Type to Mkz_example and Mode to Navigation
- Run perception_camera.launch file [perception_camera.txt](https://github.com/ApolloAuto/apollo/files/3432848/perception_camera.txt)

### Help Wanted 
- How to enable the following channels to work (/apollo/sensor/camera/front_6mm/image and 
/apollo/sensor/camera/front_12mm/image) with the height set to 1080 (as per default Apollo3.5)?

We would like to have perception module running with the Camera data fused with the LiDAR data in our vehicle.

**Comment by gaushivs** [comment]
@natashadsouza : Please help with this issue.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
