### ISSUE TITLE
question about libtorch

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#9234]
apollo 5.0
i download the latest libtorch, but a compile error is occur:
torch::set_num_threads() is not a member of torch

that's why? version problem?

**Comment by wanggujin** [comment]
i no use cude

**Comment by natashadsouza** [comment]
@wanggujin libtorch is a part of our docker environment and does not need to downloaded separately. Please confirm.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions!
