### ISSUE TITLE
pnc map:  floating-point comparison may cuase issue

### ISSUE THREAD

**Issue by s894330** [ApolloAuto/apollo#9235]
version: apollo 5.0.0
OS: ubuntu 14.04.5
---
hi
I study the source code of planning module, and found that there is a floating-point comprasion
issue in pnc_map.cc -  void PncMap::UpdateNextRoutingWaypointIndex(int cur_index) about line 115
```
while (next_routing_waypoint_index_ < routing_waypoint_index_.size() &&
     cur_index == routing_waypoint_index_[next_routing_waypoint_index_].index &&
     adc_waypoint_.s >= routing_waypoint_index_[next_routing_waypoint_index_].waypoint.s) {
          ++next_routing_waypoint_index_;
}
```
adb_waypoint_.s and routing_waypoint_index_[next_routing_waypoint_index_].waypoint.s are double variables.

I found they sometimes will not equal even if they have the same value (for example: 4.7653),
So I think using ">=" to compare floating-point may cause some issue，maybe we should using another way to compare them

thank you

**Comment by jmtao** [comment]
@s894330 you are right. The best way to compare two floating-point values is to use an accuracy threshold instead of "==". But here we are comparing two s values and **we are iterating**, I think the tolerance is not too low, and inaccuracy can be ignored.

**Comment by s894330** [comment]
hi jmtao

I know this function is iterating, but I think there still has some problem even if it is iteration. Let me take an simple example: 

the routing_waypoint_index_[] array only has two member, first member's waypoint.s is 4.76532110, second member's waypoint.s is 7.31. And we know the adc_waypoint is calculate by mathmatical, it will has little deviation every time it calculated, take for example, maybe this time is 4.76532111, maybe next time is 4.76532109 (they all should be thinked as equal to 4.76532110)

if adc_waypoint.s is 4.76532111, it will choose second member as it's next target point, if adc_waypoint.s is 4.76532109, it will choose first member as it's next target point

I know this is not critical issue, so I will close this item. Just let you know there is minor issue here, thank you :-)
