### ISSUE TITLE
Question about ASU and AXU

### ISSUE THREAD

**Issue by gvc0461082002** [ApolloAuto/apollo#9237]
HI There:
I plan to apply apollo 5.0 for creating a self-driving vehicle.
There are some questions confusing me in the quick-start guide on HW installation section:

1.  May I setup a self-driving one without ASU and AXU?
2.  It says "You need to provide these additional components for the Additional Tasks Required" , may I know what means additional task?

Cheers
Fenglu Ge

**Comment by natashadsouza** [comment]
@gvc0461082002 
In response about your question:
1. AXU is not required, but the ASU is.
2. Could you link to where this note was mentioned, or give us more details about it.

**Comment by gvc0461082002** [comment]
> @gvc0461082002
> In response about your question:
> 
> 1. AXU is not required, but the ASU is.
> 2. Could you link to where this note was mentioned, or give us more details about it.

HI Natasha:
It's in the "Apollo 3.5 Hardware and System Installation Guide", located at "Additional Components Required"
Thanks for your quick reply.
1. May I know ASU is necessary in Apolloauto3.5?
2. Is it possible to implement Hardware assembly without ASU on 5.0 and 3.5?
3. If it's a must one, may I know how long it can be ready by order ?

Cheers
Fenglu Ge

**Comment by natashadsouza** [comment]
@gvc0461082002 my apologies for not getting back to this sooner, in response to your questions:
1. May I know ASU is necessary in Apolloauto3.5? Yes it is necessary 
2. Is it possible to implement Hardware assembly without ASU on 5.0 and 3.5? We have not tested it internally. You would definitely need to make software modifications to handle low level sensor fusion
3. If it's a must one, may I know how long it can be ready by order ? Please use [this link](http://apollo.auto/platform/hardware.html)

Thank you for your interest in Apollo!

**Comment by gvc0461082002** [comment]
> @gvc0461082002 my apologies for not getting back to this sooner, in response to your questions:
> 
> 1. May I know ASU is necessary in Apolloauto3.5? Yes it is necessary
> 2. Is it possible to implement Hardware assembly without ASU on 5.0 and 3.5? We have not tested it internally. You would definitely need to make software modifications to handle low level sensor fusion
> 3. If it's a must one, may I know how long it can be ready by order ? Please use [this link](http://apollo.auto/platform/hardware.html)
> 
> Thank you for your interest in Apollo!

Dear Nataha:
Thanks for your suggestions. 

Regards
Fenglu Ge
