### ISSUE TITLE
Which version of YOLO is used for obstacle detection?

### ISSUE THREAD

**Issue by wzjin2017** [ApolloAuto/apollo#9241]
Also, is YOLO the only algorithm used for camera-based obstacle detection?

**Comment by wzjin2017** [comment]
In[ this work](https://speakerdeck.com/mzweilin/magic-tricks-for-self-driving-cars?slide=6) from Baidu, you guys used YOLO v3. Is this v3 also the one used in the complete Apollo?

**Comment by natashadsouza** [comment]
Hi @wzjin2017 thank you for your interest in Apollo. We currently use YOLO 2.Let me know if you have any additional questions.
