### ISSUE TITLE
kmz7_data_collection_table.pb.txt to collect control data

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#9242]
Hi, I'm collecting control data for vehicle control calibration.
When I'm doing it on dreamview, the progress is not working well. So I took a look at the mkz7_data_collection_table.pb.txt file to check each criteria.

There are two parameters that I'm curious about:
1.frame_threshold: 20
2.total_frames: 6000

When I changed them to 1 and 5. the progress of each criterion was working well like the following.
![image](https://user-images.githubusercontent.com/14055939/61981942-06851280-afb0-11e9-88fc-331092b2ee85.png)

My first question is:
why total_frames is high value? Is total_frames 6000 enough to get the reliable data set? Should I stick it to 6000?

My second question is:
What is frame_threshold parameter? I assumed that this is consecutive data set met by criterion. For instance, if frame_threshold is 20, 19 data set is met by criterion and 1 data set is not, then this 20 data set is not added to total_frames. Is my assumption right? Also should I stick frame_threshold variable to 20 to get reliable data?

Best
Taehyung Kim

**Comment by sjiang2018** [comment]
1. If the localization frame rate is 100 frame/sec, than 6000 frames is total frames collected within 1-minute. You can modify the number based on your need.
2. Yes. In our case, we need at least 20 consecutive data frame for model training. You may also modify this number if your model training doesn't have this requirement.

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions.
