### ISSUE TITLE
Failed to start Dreamview &  Failed to open map meta file: /metaInfo.json

### ISSUE THREAD

**Issue by lucianzhong** [ApolloAuto/apollo#9249]
After the build process: bash scripts/bootstrap.sh
And it says failed to start dreamview.
In the dreamview log file says:Failed to open map meta file: /metaInfo.json.

zy@in_dev_docker:/apollo$ bash scripts/bootstrap.sh
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Failed to start Dreamview. Please check /apollo/data/log or /apollo/data/core for more information

04:35:31.002686 30252 map_service.cc:107]  Failed to open map meta file: /metaInfo.json

### System information

- ** Ubuntu 16.04   64bits
- **Apollo installed from source **:
- **Apollo version 5.0.0 & 3.5.0**:

**Comment by DongAi** [comment]
1. please check the log file 
2. use gdb to attach core file and Dreamview, use bt command to check the backtrace

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions.
