### ISSUE TITLE
on_lane_planning: code scequence minor issue

### ISSUE THREAD

**Issue by s894330** [ApolloAuto/apollo#9275]
### System information

- **OS Platform and Distribution (Linux Ubuntu 14.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.0)**:

### Description
Hi apollo

When I study on_lane_planning.cc, I found a minor code scequence issue. In RunOnce() at about line 230 (shown below)
```
  if (util::IsDifferentRouting(last_routing_, *local_view_.routing)) {
      last_routing_ = *local_view_.routing;
      PlanningContext::Instance()->mutable_planning_status()->Clear();
      reference_line_provider_->UpdateRoutingResponse(*local_view_.routing);
  }

  // Update reference line provider and reset pull over if necessary
  reference_line_provider_->UpdateVehicleState(vehicle_state);
```
the scequence is:
1. reference_line_provider_->UpdateRoutingResponse(*local_view_.routing);
2. reference_line_provider_->UpdateVehicleState(vehicle_state);

in the function of  reference_line_provider_->UpdateRoutingResponse(*local_view_.routing); we can see
```
bool ReferenceLineProvider::UpdateRoutingResponse(const routing::RoutingResponse &routing) {
    std::lock_guard<std::mutex> routing_lock(routing_mutex_);
    routing_ = routing;
    has_routing_ = true;
    return true;
}
```
as we can see, it set the has_routing_ to true.

And there is another thread called "GenerateThread" inside reference_line_provider, which use has_routing_ to adjudge to do things
```
void ReferenceLineProvider::GenerateThread() {
  while (!is_stop_) {
    constexpr int32_t kSleepTime = 50;  // milliseconds
    cyber::SleepFor(std::chrono::milliseconds(kSleepTime));
    const double start_time = Clock::NowInSeconds();
    if (!has_routing_) {
      AERROR << "Routing is not ready.";
      continue;
    }
    std::list<ReferenceLine> reference_lines;
    std::list<hdmap::RouteSegments> segments;
    if (!CreateReferenceLine(&reference_lines, &segments)) {
      AERROR << "Fail to get reference line";
      continue;
    }
    ....
}
```
we can see, if has_routing_ is true, it will call CreateReferenceLine() function, which shown below
```
bool ReferenceLineProvider::CreateReferenceLine(
    std::list<ReferenceLine> *reference_lines,
    std::list<hdmap::RouteSegments> *segments) {
  CHECK_NOTNULL(reference_lines);
  CHECK_NOTNULL(segments);

  common::VehicleState vehicle_state;
  {
    std::lock_guard<std::mutex> lock(vehicle_state_mutex_);
    vehicle_state = vehicle_state_;
  }

  routing::RoutingResponse routing;
  {
    std::lock_guard<std::mutex> lock(routing_mutex_);
    routing = routing_;
  }
  bool is_new_routing = false;
  {
    // Update routing in pnc_map
    if (pnc_map_->IsNewRouting(routing)) {
      is_new_routing = true;
      if (!pnc_map_->UpdateRoutingResponse(routing)) {
        AERROR << "Failed to update routing in pnc map";
        return false;
      }
    }
  }

  if (!CreateRouteSegments(vehicle_state, segments)) {
    AERROR << "Failed to create reference line from routing";
    return false;
  }
  ...
}
```
we can see it begins to use vehicle_state, and call  CreateRouteSegments(vehicle_state, segments).
So if  reference_line_provider_->UpdateRoutingResponse(*local_view_.routing) is called, the CreateRouteSegments(vehicle_state, segments) function in GenerateThread will be called

Is it possible of the following code scequence be happened?
1. reference_line_provider_->UpdateRoutingResponse(*local_view_.routing) is called
2. CreateRouteSegments(vehicle_state, segments) is called in GenerateThread
3. reference_line_provider_->UpdateVehicleState(vehicle_state);

If it happened, the vehicle_state in 2nd step maybe old or wrong data, because the newest vehicle_state data is updated at 3rd step

So I think the right code scequence in on_lane_planning.cc is below
```
  // Update reference line provider and reset pull over if necessary
  reference_line_provider_->UpdateVehicleState(vehicle_state);

  if (util::IsDifferentRouting(last_routing_, *local_view_.routing)) {
      last_routing_ = *local_view_.routing;
      PlanningContext::Instance()->mutable_planning_status()->Clear();
      reference_line_provider_->UpdateRoutingResponse(*local_view_.routing);
  }
```

just for your reference, thank you :-)

**Comment by jmtao** [comment]
@s894330 all the attributes of vehicle_state is independent of routing or planning's reference line. 
https://github.com/ApolloAuto/apollo/blob/master/modules/common/vehicle_state/proto/vehicle_state.proto
reference line is generated based on routing.  we just want to make sure vehicle_state gets updated when we generate reference line.  The sequence (update vehicle_state before or after new routing received) doesn't really matters here.

**Comment by s894330** [comment]
hi jmtao

OK, thank you :-)
