### ISSUE TITLE
Localization frame in static transformation

### ISSUE THREAD

**Issue by esra-acar** [ApolloAuto/apollo#9293]
Is **localization frame** (stated in the configuration of static transformation) **vehicle frame** (body frame) explained in https://github.com/ApolloAuto/apollo/blob/master/docs/specs/coordination.pdf? 
And how is the vehicle frame connected to **world frame**?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
