### ISSUE TITLE
Black screen for localhost:8888

### ISSUE THREAD

**Issue by mahmoodn** [ApolloAuto/apollo#9304]
With a clean clone, I ran the following commands
```
sudo ./docker/scripts/dev_start.sh
sudo ./docker/scripts/dev_into.sh
sudo ./apollo.sh build
...
1============================
[ OK ] Build passed!
[INFO] Took 2366 seconds
============================
root@in_dev_docker:/apollo# 
```

Now when I open browser and enter localhost:8888, I see a black page only.
It seems that some is started. Any recommendation for more debugging?

**Comment by mahmoodn** [comment]
BTW, mkz_example is present 

```
root@in_dev_docker:/apollo/modules/calibration/data# ls
README.md  mkz_example
```

**Comment by natashadsouza** [comment]
@mahmoodn did you run `bash scripts/bootstrap.sh`? Refer to [our launch guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_launch_Apollo.md)

**Comment by omaidb** [comment]
allride@in_dev_docker:/apollo$ bash scripts/bootstrap.sh
Module monitor is already running - skipping.
Module dreamview is already running - skipping.

**Comment by natashadsouza** [comment]
@omaidb @mahmoodn you could refer to [the Dreamview start guide](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_debug_dreamview_start_problem.md) for additional debugging information.

**Comment by omaidb** [comment]
@natashadsouza  我是在ssh中运行, bash scripts / bootstrap.sh 提示我没有找到监视器，我在gui下重新运行，但是提示我已经运行，我 bash scripts / bootstrap.sh stop 后再运行 bash scripts / bootstrap.sh start 后可以打开localhost:8888了，我没有想到监视器是必备的

**Comment by mahmoodn** [comment]
@natashadsouza 
Sorry for the delay. I missed the bootstrap. Thanks for your help.

**Comment by natashadsouza** [comment]
@mahmoodn did that resolve the problem?
@omaidb I am not sure what the problem is. Could you give us details regarding your current Apollo version, system information etc. to help us debug better?

**Comment by ycool** [comment]
You can use `ps -ef | grep dreamview` to check if dreamview starts or not.
