### ISSUE TITLE
Cyber SDK

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#9316]
Does there any standealone cyber SDK which can be used in C++ or Python deal with record files?

**Comment by baowanyu** [comment]
There is no standalone SDK, all api files are stored in Apollo git repo.
C++ API：apollo/cyber/record/
Python API: apollo/cyber/python/cyber_py/record.py

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions.
