### ISSUE TITLE
Dreamview's SimControl separated into its own module

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#9321]
As of 099f135a464f85b10599040073806fcb6b2d6c25, Apollo's open source simulator is located in dreamview/backend/sim_control. It would be nice if it was in its own module. That way it can be started and stopped without a UI. This feature is useful for process level, real-time integration frameworks.

I know there are a few solutions to running dreamview without a UI in https://github.com/ApolloAuto/apollo/issues/6795. But it seems simpler to decouple the simulation from the visualizer.

Also, the dreamview UI should probably be changed at the same time. Instead of having the SimControl button on the front page, it should be started like the other programs. There can be another config located in modules/dreamview/conf/hmi_modes/simulation.pb.txt.

**Comment by xmyqsh** [comment]
@Fla3inH0tCheet0s 
That's a good suggestion.
The `dreamview/backend/sim_control` is `PerfectControlModel`.
Do you know where is the `Control-in-loop Simulation`?
@natashadsouza [Dynamic Model - Control-in-loop Simulation](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/dynamic_model.md)

**Comment by askariz** [comment]
Hi
@xmyqsh do you find out where is the Control -in-loop Simulation ? 
@natashadsouza  the announce of apollo that mention r5.0 have the feature of it ? but it seems that i can find out any instruction of it ?

**Comment by unacao** [comment]
control-in-loop can be enabled on Apollo Simulation Service http://apollo.auto/platform/simulation.html

**Comment by xmyqsh** [comment]
@unacao 
Got it. Thanks.

**Comment by Andor233** [comment]
So,it is invisible for us?
Can I find anything about the model in this repo?

**Comment by unacao** [comment]
We provide two dynamic models: Echo and Intelli. Echo is a rule-based well-tuned dynamic model for Lincoln MKZ, and offered by third-party via a license. Due to the license restrictions, we are not able to disclose the details. Intelli is a dynamic model trained by machine learning methods. The corresponding paper will be available on IROS 2019.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
