### ISSUE TITLE
Could anybody share a .bag file for me?

### ISSUE THREAD

**Issue by xmyqsh** [ApolloAuto/apollo#9333]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: 14.04
- **Apollo installed from (source or binary)**: official source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

I want to [Run Perception Module on My Local Computer](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md)
Could anybody share a .bag file for me?  **_xmyqsh@gmail.com_**

**Comment by omaidb** [comment]
我下载了一个bag，但是我不知道怎么播放它

**Comment by xmyqsh** [comment]
@omaidb @techoe 
I can only get the `apollo_3.5.recorder`.
Is there an `apollo_5.0.recorder` available soon or later?
Is `apollo_3.5.recorder` could be used in the `branch 5.0.0` or `branch master` ?

**Comment by Iqbalparvi** [comment]
@xmyqsh yes you can download demo_3.5.recorder and run its on branch 5.0.0 
Hints:
after running bootstrap.sh 
cd docs/demo_guide/
python rosbag_helper.py demo_3.5.record
cyber_recorder play -f demo_3.5.record --loop

**Comment by xmyqsh** [comment]
@Iqbalparvi 
I have done these. But it is meaningless for me.
I want to simulate the whole stack or just except for the perception module because there is no image or lidar or radar sensor data in it. What you have seen is the car driving based on the Chassis channel in it. While, you could say, why not split it out, as well as all the intermedia channels, just use the perception obstacle channel, traffic light channel, localization channel, static_transform channel, and just test the prediction module, routing module, and the planning module, no control module because of dreamview using perfect control. 
After all of these have done. There is another problem. Can you guess it? There is no routing.pb file available.
hm.. it is not a big problem.
What the most serious is that the very earliest assumption we have made that we want to use the perception obstacle channel info as input. But think twice here. Hmm.. the perception obstacle channel is meaningless without interaction with the realtime driving environment, isn't it?

Maybe there are some other ways to use this record file that I have not figured out.
Maybe you could also have a try on the previous *.bag file. They have the sensor channel in it.
But I choose to stop here.

**Comment by xmyqsh** [comment]
I will come back with full energy.
Sooner or later.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
