### ISSUE TITLE
Open Space planner doesn't appear to work

### ISSUE THREAD

**Issue by renegadephysicist** [ApolloAuto/apollo#9336]
**Describe the bug**
When running the open space planner with Sim Control and selecting a parking spot using the Sunnyvale Map with two offices it stalls 

Hash:  4f5fb4463ec1c607b17fb62663c553b830f6a1f3

**To Reproduce**
1. Select Sunnyvale map with two offices
2. Select Sim Control
3. Select Routing and Planning
4. Go to default routing and select any parking space

**Expected behavior**
Planner should direct car to space

**Additional context**
The Ipopt solver converges to a point of local infeasibility. This can be seen by setting ipopt_print_level: 5 in planning_config.pb.txt

**Comment by deidaraho** [comment]
We are going to reset the GFLAG and use our own searching-based method to solve the problem instead of IPOPT for this issue.

**Comment by natashadsouza** [comment]
@renegadephysicist please find the changes made in PR #9347 
Currently closing this issue as it has been resolved. Feel free to reopen if you have additional questions!
