### ISSUE TITLE
[Announcement]: Apollo is migrating to Ubuntu 18.04

### ISSUE THREAD

**Issue by natashadsouza** [ApolloAuto/apollo#9363]
Hey guys,

Apollo has been successfully migrated to Ubuntu 18.04. We don’t expect a big disruption to your current work with Apollo repo, but for perception related code, you would need to:

1. Upgrade host to ubuntu_16.04 and above (Ubuntu 18.04 is preferred)
2. Update local host NVIDIA driver >=410.48. [Website link](https://www.nvidia.com/Download/index.aspx?lang=en-us)
3. Install NVIDIA-docker 2.0 - you can refer to [this link](https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)) for steps on installation

For those developers that would like to continue working with Ubuntu 14.04, please use [the Ubuntu 14 branch](https://github.com/ApolloAuto/apollo/tree/ubuntu_14.04) instead of the master branch.

Updating Apollo to Ubuntu_18.04 has been one of the most popular requests from the Apollo Developer Community, and we are excited to finally make it happen. As always, if you experiencing any problems post migration, file an issue and we will always happy to help!

**Comment by natashadsouza** [comment]
Please ensure that you **update local host NVIDIA driver >=410.48** before you **install NVIDIA-docker 2.0**.

**Comment by alexbuyval** [comment]
Hi Natasha,

I tried to run the cyber_visualizer in the new docker, however 'command not found'
```
alex@in_dev_docker:/apollo$ source cyber/setup.bash 
alex@in_dev_docker:/apollo$ cyber_visualizer
bash: cyber_visualizer: command not found
```
I have not found any source code for cyber_visualizer, so I decided that it was included in the docker container and the new container does not contain the visualizer yet. Right?

**Comment by natashadsouza** [comment]
@quning18 please confirm?

**Comment by christian-lanius** [comment]
The cyber_visualizer code is found in modules/tools/visualizer, the respective build target is //modules/tools/visualizer:cyber_visualizer
Can you try running /apollo/bazel-bin/modules/tools/visualizer/cyber_visualizer ?

**Comment by rbutucelea** [comment]
Hi @natashadsouza,

Are there any of the official releases compatible with Ubuntu 18.04  or only the master branch shall be used with it?

**Comment by alexbuyval** [comment]
> The cyber_visualizer code is found in modules/tools/visualizer, the respective build target is //modules/tools/visualizer:cyber_visualizer
> Can you try running /apollo/bazel-bin/modules/tools/visualizer/cyber_visualizer ?

Thank you for your advice. Yes, I found the cyber_visualiser code there, however, I cannot run it:
```
alex@in_dev_docker:/apollo$ ./bazel-bin/modules/tools/visualizer/cyber_visualizer
bash: ./bazel-bin/modules/tools/visualizer/cyber_visualizer: No such file or directory
```
I run 
../apollo.sh build as well as ./apollo.sh build_opt_gpu

Maybe I need to use special build command for the cyber_visualiser?

**Comment by christian-lanius** [comment]
@alexbuyval Can you try running `bazel build //modules/tools/visualizer:cyber_visualizer`?
That should build the correct target

**Comment by alexbuyval** [comment]
> @alexbuyval Can you try running `bazel build //modules/tools/visualizer:cyber_visualizer`?
> That should build the correct target.
> Unfortunately, I am on mobile, so there might be a typo.

@christian-lanius I have just tried, but I got the error:
```
alex@in_dev_docker:/apollo$  bazel build //modules/tools/visualizer:cyber_visualizer
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
.
ERROR: (08-24 14:19:51.327) /apollo/modules/tools/visualizer/BUILD:25:1: no such package '@qt//': Expected directory at /usr/local/Qt5.5.1/5.5/gcc_64 but it does not exist. and referenced by '//modules/tools/visualizer:visualizer_lib'.
ERROR: (08-24 14:19:51.343) Analysis of target '//modules/tools/visualizer:cyber_visualizer' failed; build aborted.
INFO: (08-24 14:19:51.345) Elapsed time: 1.760s
alex@in_dev_docker:/apollo$ 
```

**Comment by christian-lanius** [comment]
@alexbuyval Btw, this thread is related to Apollo being converted to Ubuntu 18.04, so our conversation does not really belong here.

That being sad: Can you verify that the folder indeed does not exist? If so, can you try running  `cd /tmp/installers &&  bash install_qt.sh`. If that does not work, can you try installing qt manually? Normally, qt should be part of the docker container. Are you using the official docker container or have you built your own?

**Comment by alexbuyval** [comment]
> Btw, this thread is related to Apollo being converted to Ubuntu 18.04, so our conversation does not really belong here.

Agree. However, I am using the official docker container, so I think that this issue is produced by some missing dependencies in the new docker. I don't need the cyber_visulizer right now, I just want to pay attention the Apollo team on this issue.

@christian-lanius Thank you for your help

**Comment by christian-lanius** [comment]
Yeah that's fair.
I built my own Ubuntu18.04 container a few months back, and I went ahead and upgraded Qt at the time to a more up-to-date one as well. However, I do not remember if that was necessary or if I only did it because I wanted to keep the deps more recent.

**Comment by fzd9752** [comment]
Great News! Thanks. What version of cuda is with Ubuntu 18? Can we use RTX 20 series to run perception module?

**Comment by nullptr123** [comment]
why not upgrade gcc to gcc-7 which is default for ubuntu 18.04?

still gcc-4.8 is too old and may be incompatible with library installed by apt-get.

**Comment by siqb** [comment]
> Hi @natashadsouza,
> 
> Are there any of the official releases compatible with Ubuntu 18.04 or only the master branch shall be used with it?

@natashadsouza , I would also like to know this. It is not at all clear which versions are compatible with Ubuntu 18.04.

**Comment by sinopec** [comment]
> why not upgrade gcc to gcc-7 which is default for ubuntu 18.04?
> 
> still gcc-4.8 is too old and may be incompatible with library installed by apt-get.

great recommendation, expect this.
