### ISSUE TITLE
CANBUS ERROR: Failed to create can client

### ISSUE THREAD

**Issue by udeto** [ApolloAuto/apollo#9365]
### System information
- **Linux Ubuntu 18.04**:
- **Apollo installed from binary**:
- **Apollo version 3.0**:

Hello, 
I am trying to run apollo 3.0 with carla 0.9.5 using a ROS bridge (https://nemodrive-docs.readthedocs.io/projects/nemodrive-apollo/en/latest/config_run.html#running). 

When I open dreamview I am getting an error, saying that the can client could not be created.
Full error from log file:
```
Log file created at: 2019/08/10 12:01:54
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0810 12:01:54.188791 10747 factory.h:112] Factory could not create Object of type : 1
E0810 12:01:54.189450 10747 can_client_factory.cc:57] Failed to create CAN client with parameter: brand: ESD_CAN
type: PCI_CARD
channel_id: CHANNEL_ID_ZERO
E0810 12:01:54.192387 10747 apollo_app.cc:59] canbus Init failed: CANBUS_ERROR: Failed to create can client.
```
I dont know where this error is coming from, or how to solve it.
Can someone please help me with that?
Thanks

**Comment by Capri2014** [comment]
Do not try launch Canbus modules in simulation environment, especially when you do not have a physical canard installed in your computer..

**Comment by XinrRunChao** [comment]
Can you resolve this problem? I encounter the same problem....helping
