### ISSUE TITLE
Traffic signs perception

### ISSUE THREAD

**Issue by Harry1993** [ApolloAuto/apollo#9397]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

Thank you guys for providing such an amazing platform. I have a few question about traffic signs perception as follows.

How does Apollo perceive traffic signs? Using YOLO?

How do we test whether or not Apollo can robustly recognize a traffic sign even if it is [maliciously crafted](http://openaccess.thecvf.com/content_cvpr_2018/papers/Eykholt_Robust_Physical-World_Attacks_CVPR_2018_paper.pdf)?

Thank you,
Yanmao

**Comment by Harry1993** [comment]
I want to do the test only in the simulation mode, not in the real-world scenario.

**Comment by hzdsdhr** [comment]
I don't think apollo has traffic sign detection. Where did you heard about this? The only traffic sign related function of apollo is in apollo map, each lane has a attribute for speed limit. So the speed limit is provided by map.

**Comment by unacao** [comment]
Traffic light detection is provided by perception module. But traffic sign is labeled by the HD map, including stop sign and yield sign.

**Comment by Harry1993** [comment]
Thanks for the information, @hzdsdhr and @unacao .

I am closing this issue because it is solved.

**Comment by GooVincent** [comment]
> 

Please how did you solve this issue? Did you refer to the traffic sign info in the HD map , did you?

**Comment by adityadikshit07** [comment]
@Harry1993 , I working on this, How did you solve this ?

**Comment by daohu527** [comment]
Use hd-map for now, we consider adding a new model to detect, but it is not yet in the plan

**Comment by adityadikshit07** [comment]
Hi @daohu527, Thanks for your reply.
I wanted to know more about it, if I want to add a [malicious stop sign](https://openaccess.thecvf.com/content_cvpr_2018/papers/Eykholt_Robust_Physical-World_Attacks_CVPR_2018_paper.pdf)
to test Apollo prediction, is there a way I could achieve this ?

**Comment by daohu527** [comment]
I think we can divide it into 2 parts:
- traffic signs detection
- make decisions using detected traffic signs

for now 
- traffic signs detection. It doesn't support apollo and we can't detect traffic signs online, but using HD maps with traffic sign information.
- make decisions using detected traffic signs. The planning module in apollo will use the detected traffic signs to make a route.

So the main difference is the first one, you can try to find some image models, such as yolo, to detect traffic signs, if you are studying how to avoid attacks

**Comment by adityadikshit07** [comment]
Thanks for your reply.
