### ISSUE TITLE
18.04 CI test failures when missing libcuda.so: /usr/lib/x86_64-linux-gnu//libcuda.so: file not recognized: File truncated

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo#9398]
Currently,our CI sever has no GPU card and nvidia driver,we use it to build and do basic test, after update to 18.04 docker, it would get this error. We have saw this [pull request](https://github.com/ApolloAuto/apollo/commit/498f27488c102741e927d0e56c83ae4c4104b23d)  Travis: fix ci test failures when missing libcuda.so.  Could fix this problem in Ubuntu 18.04?

**Comment by ycool** [comment]
Fixed by https://github.com/ApolloAuto/apollo/pull/9407. Thanks for the report.

**Comment by natashadsouza** [comment]
@gengqx thank you so much for testing out our latest update to Ubuntu 18.04. We really appreciate your feedback :)
Closing this issue as it has been resolved!

**Comment by gengqx** [comment]
Fixed,Thx.

**Comment by renegadephysicist** [comment]
Hi,

This issue has resurfaced in the latest docker image.
