### ISSUE TITLE
No conrtol-module output 

### ISSUE THREAD

**Issue by lukasthede** [ApolloAuto/apollo#9431]
Hello,

I am trying to run apollo 3.0 with the carla simulator (0.9.5) using a ros-bridge (https://nemodrive-docs.readthedocs.io/projects/nemodrive-apollo/en/latest/installation.html)
I successfully set up the ros-bridge, so that the car and the map are showing up in dreamview. But when I send a routing request the car does not move a bit, even though the planning module is working fine (blue planning trajectory is showing up). 
  
### System information

- Ubuntu 18.05
- Apollo docker version
- Apollo version 3.0

### Steps to reproduce the issue:
- Start apollo with dev_start & dev_into & bootstrap.sh
- Start apollo-ros-bridge (https://nemodrive-docs.readthedocs.io/projects/nemodrive-apollo/en/latest/config_run.html#running)
- Start Carla-simulator
- Start Carla-Ros-Bridge
- Strat apollo modules localization, routing, control, prediction and planning
- Send routing request via dreamview "route editing"

There is no error occurring while launching the control module.
This is the output of the control.info logfile:

`Log file created at: 2019/08/18 19:23:06
Running on machine: in_dev_docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0818 19:23:06.100620 16075 control.cc:48] Control init, starting control...
I0818 19:23:06.135354 16075 control.cc:51] Conf file: modules/control/conf/lincoln.pb.txt is loaded.
I0818 19:23:06.135978 16075 adapter_manager.cc:46] Init AdapterManager config:config {
  type: LOCALIZATION
  mode: RECEIVE_ONLY
  message_history_limit: 10
}
config {
  type: PAD
  mode: RECEIVE_ONLY
  message_history_limit: 10
}
config {
  type: PLANNING_TRAJECTORY
  mode: RECEIVE_ONLY
  message_history_limit: 10
}
config {
  type: CHASSIS
  mode: RECEIVE_ONLY
  message_history_limit: 10
}
config {
  type: CONTROL_COMMAND
  mode: PUBLISH_ONLY
}
config {
  type: MONITOR
  mode: DUPLEX
  message_history_limit: 1
}
is_ros: true
I0818 19:23:07.298007 16075 controller_agent.cc:36] Only support MPC controller or Lat + Lon controllers as of now
I0818 19:23:07.298779 16075 lat_controller.cc:87] Using LQR-based Lateral Controller
I0818 19:23:07.299121 16075 lon_controller.cc:129] Control calibration table loaded
I0818 19:23:07.299139 16075 lon_controller.cc:130] Control calibration table size is 1297
I0818 19:23:07.299455 16075 controller_agent.cc:94] Controller <LON_CONTROLLER> init done!
I0818 19:23:07.299486 16075 lat_controller.cc:248] Lateral control gain scheduler loaded
I0818 19:23:07.299537 16075 lat_controller.cc:159] LQR-based Lateral Controller begin.
I0818 19:23:07.299551 16075 lat_controller.cc:160] [LatController parameters] mass_: 2080, iz_: 4208.3, lf_: 1.4224, lr_: 1.4224
I0818 19:23:07.299624 16075 controller_agent.cc:94] Controller <LQR-based Lateral Controller> init done!
I0818 19:23:07.299655 16075 control.cc:91] Control resetting vehicle state, sleeping for 1000 ms ...
I0818 19:23:08.299755 16075 control.cc:97] Control default driving action is STOP
I0818 19:23:08.300050 16075 control.cc:104] Control init done!`

This is how it looks in dreamview
![Screenshot from 2019-08-18 19-44-51](https://user-images.githubusercontent.com/52383800/63228270-d9173780-c1f0-11e9-9da3-bd53424346c5.png)

Can someone please help me figure out, why there is no output from the control module?
Thanks!

**Comment by Capri2014** [comment]
did you connect it with a simulated vehicle? From this limited information, looks like no chassis feedback seen by control

**Comment by udeto** [comment]
Yes I connected the simulated vehicle from carla using the ros-bridge.
This is the rqt_graph of the Setup:
![apollo-carla](https://user-images.githubusercontent.com/52383800/63326359-5b584680-c32c-11e9-88bd-51b3e1d09f4b.png)


As you can see chassis feedback is send from the apollo-side of the ros bridge to the modules using the topics /apollo/canbus/chassis with following message:
`engine_started: true
speed_mps: 0.0
driving_mode: COMPLETE_AUTO_DRIVE
gear_location: GEAR_DRIVE
`
The other input messages for the control module are:

/apollo/localization/pose
`pose {
  position {
    x: -7.52985715866
    y: -26.41998291
    z: 0.254972994328
  }
  orientation {
    qx: -3.42130677197e-05
    qy: -2.60989763867e-05
    qz: -0.999999999074
    qw: -6.56846254911e-08
  }
  linear_velocity {
    x: 0.0
    y: -0.0
    z: 0.0
  }
  linear_acceleration {
    x: 0.0
    y: 0.0
    z: 0.0
  }
  angular_velocity {
    x: 0.0
    y: 0.0
    z: 0.0
  }
  heading: -1.57079645638
  linear_acceleration_vrf {
    x: 0.0
    y: -0.0
    z: 0.0
  }
  angular_velocity_vrf {
    x: 0.0
    y: -0.0
    z: 0.0
  }
}
measurement_time: 0.0
`

/apollo/planning
- works, as shown by the blue trajectory in dreamview
- message on ros topic looks good as well

/apollo/control/pad
- nothing is published here

I am expecting a control command on the topic /apollo/control but nothing is being published here.

Is there something wrong with the input, or am I missing some information needed by the control module? 

If you need additional info, please let me know!

**Comment by Capri2014** [comment]
Hi @udeto sorry I missed your reply earlier on, you need to send an `auto` command via `https://github.com/ApolloAuto/apollo/blob/master/modules/control/proto/pad_msg.proto` in order for control to be triggered for publishing control command, otherwise it would just be headers.

**Comment by danielbachmanncgi** [comment]
Hi @udeto, how did you even get nemodrive rod-bridge to run with carla 0.9.5?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
