### ISSUE TITLE
Control In Loop Function Missing ?

### ISSUE THREAD

**Issue by askariz** [ApolloAuto/apollo#9436]
the apollo 5.0 support control-in-loop function ?  
it seems we still can not use it with dreamview .
How soon can we use it ?

**Comment by natashadsouza** [comment]
@askariz thank you for your interest in Apollo. Control-in-loop is not a feature in Dreamview, but in [Dreamland](http://apollo.auto/platform/simulation.html). You can learn more about it [in this document](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/Dreamland_introduction.md). Please let us know if you have any more questions!

**Comment by askariz** [comment]
@natashadsouza  Thank you for you kindly remind . I get picture of it .
