### ISSUE TITLE
unit_t_ in dp_st_cost.cpp and gridded_path_time_graph.cpp is not consistent

### ISSUE THREAD

**Issue by zhuzd12** [ApolloAuto/apollo#9443]
It seems that the calculation of unit_t_ in dp_st_graph.cpp is not consistent with which in gridded_path_time_graph.cpp, causing anomalies when time resolution is fairly low.

## dp_st_graph.cpp (incorrect)
```c++
unit_t_ = total_time / config_.matrix_dimension_t();
```

## gridded_path_time_graph.cpp (correct)
```c++
unit_t_ = st_graph_data_.total_time_by_conf() /
            (gridded_path_time_graph_config_.matrix_dimension_t() - 1);
```

**Comment by JasonZhou404** [comment]
Thanks for point it out, related Pull Request is created.

**Comment by natashadsouza** [comment]
Closing this issue as it has been resolved. Feel free to reopen if you have additional questions!
