### ISSUE TITLE
apollo5如何播放bag

### ISSUE THREAD

**Issue by omaidb** [ApolloAuto/apollo#9444]
OS:Ubuntu16.04
apollo install git source
apollo5
我按照安装指引文档一步步安装完成apollo5,最终打开了localhost:8888
![image](https://user-images.githubusercontent.com/18365223/63315311-4932d400-c33d-11e9-8dce-ee076cc6df2e.png)
我下载了demo.bag
但是我不知道要怎么播放bag
apollo5没有ros，无法使用rosbag播放

**Comment by yaoweifeng01** [comment]
可以参考：https://cyber-rt.readthedocs.io/en/latest/CyberRT_Developer_Tools.html 地址。使用方式比如cyber_recorder play -f 20180720202307.record。详细命令如下：
```
$ cyber_recorder
usage: cyber_recorder <command>> [<args>]
The cyber_recorder commands are:
    info                               Show infomation of an exist record.
    play                               Play an exist record.
    record                             Record same topic.
    split                              Split an exist record.
    recover                            Recover an exist record.
```

**Comment by omaidb** [comment]
执行 cyber_recorder 后，提示
cyber_recorder: error while loading shared libraries: libfastcdr.so.1: cannot open shared object file: No such file or directory
![image](https://user-images.githubusercontent.com/18365223/63343169-eadb1500-c37f-11e9-9e19-c5372851684f.png)

**Comment by omaidb** [comment]
找到文件了，是目录错了

**Comment by yaoweifeng01** [comment]
> rosbag_to_record
> 也是提示找不到文件

编译成功了吗？apollo是要在docker中编译及运行的

**Comment by omaidb** [comment]
> > rosbag_to_record
> > 也是提示找不到文件
> 
> 编译成功了吗？apollo是要在docker中编译及运行的

我是在docker中运行的，没有看到文档指导说要编译啊

**Comment by yaoweifeng01** [comment]
我是在docker中运行的，没有看到文档指导说要编译啊
::
需要编译 参考 https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md
