### ISSUE TITLE
hmi.conf doesn't exist in some branches

### ISSUE THREAD

**Issue by dwrr** [ApolloAuto/apollo#9461]
Unsure whether it's a bug but I can only find apollo/modules/dreamview/conf/hmi.conf in demo_dev branch.

This is required for the navi_config.py script when following this tutorial -> https://github.com/ApolloAuto/apollo/blob/master/docs/technical_tutorial/navigation_mode_tutorial_cn.md

I have forked from master therefore couldn't find it.

**Comment by ycool** [comment]
hmi.conf is deprecated in the latest code.

**Comment by Moon-XUChengyuan** [comment]
> Unsure whether it's a bug but I can only find apollo/modules/dreamview/conf/hmi.conf in demo_dev branch.
> 
> This is required for the navi_config.py script when following this tutorial -> https://github.com/ApolloAuto/apollo/blob/master/docs/technical_tutorial/navigation_mode_tutorial_cn.md
> 
> I have forked from master therefore couldn't find it.

did you fix that? i am following the tutorial https://github.com/ApolloAuto/apollo/blob/master/docs/technical_tutorial/navigation_mode_tutorial_cn.md too but get this error in the first step. Thanks in advance!
