### ISSUE TITLE
Python Cyber Usage

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#9480]
Try run example got errror:

```
Traceback (most recent call last):
  File "record_parser.py", line 11, in <module>
    from cyber_py import cyber
  File "../cyber_py/cyber.py", line 32, in <module>
    CYBER_PATH = os.environ['CYBER_PATH']
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'CYBER_PATH'
```

How to set CYBER_PATH? BTW, python2 is no longer supported by official team, I think it's would be better upgrade pywrapper into python3.

Some usage is not work well with python3  such as:

```
            print "type is not supported: ", type(value)

```

**Comment by christian-lanius** [comment]
Have you run source cyber/setup.bash first? I think that script sets the CYBER_PATH environment variable.

**Comment by mickeyouyou** [comment]
thanks @christian-lanius . that is the solution.
