### ISSUE TITLE
Dual IPC

### ISSUE THREAD

**Issue by alexiskovi** [ApolloAuto/apollo#9485]
System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **Apollo version**: 3.5

### Steps to reproduce the issue:
* Change ip addresses in cyber/setup.bash
* Start docker
* `python cyber/python/examples/talker.py` on IPC 1
* `python cyber/python/examples/listener.py` on IPC 2

I tried to make distributed system with two IPC, like in #7050, but even talker-listener doesn't working despite the fact that I can ping IPCs. So, can you please share some docs about configuring network, or say, if there are other files to change from r3.5.0 to get this system work?

**Comment by zhangchaoltt** [comment]
please source setup.bash after you change ip addresses in setup.bash @alexiskovi

**Comment by alexiskovi** [comment]
@zhangchaoltt, I did this. I tried to configure setup.bash and cyber.pb.conf but no result. So, because of this, I want to know, maybe you had some special network configs, or there are some other places to change in code?

**Comment by zhangchaoltt** [comment]
Show your configuration of setup.bash in the two IPC

**Comment by alexiskovi** [comment]
export CYBER_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
binary_path="/apollo/bazel-bin/cyber"
cyber_tool_path="/apollo/bazel-bin/cyber/tools"
apollo_tool_path="/apollo/bazel-bin/modules/tools"
recorder_path="${cyber_tool_path}/cyber_recorder"
monitor_path="${cyber_tool_path}/cyber_monitor"
visualizer_path="${apollo_tool_path}/visualizer"
PYTHON_LD_PATH="/apollo/bazel-bin/cyber/py_wrapper"
launch_path="${CYBER_PATH}/tools/cyber_launch"
channel_path="${CYBER_PATH}/tools/cyber_channel"
qt_path=/usr/local/Qt5.5.1/5.5/gcc_64
rosbag_to_record_path="/apollo/bazel-bin/modules/data/tools/rosbag_to_record"


export LD_LIBRARY_PATH=${qt_path}/lib:$LD_LIBRARY_PATH
export QT_QPA_PLATFORM_PLUGIN_PATH=${qt_path}/plugins
export PATH=${binary_path}:${recorder_path}:${monitor_path}:${launch_path}:${channel_path}:${qt_path}/bin:${visualizer_path}:${rosbag_to_record_path}:$PATH
export PYTHONPATH=${PYTHON_LD_PATH}:${CYBER_PATH}/python:$PYTHONPATH

export CYBER_DOMAIN_ID=80
export CYBER_IP=192.168.1.149

export GLOG_log_dir=/apollo/data/log
export GLOG_alsologtostderr=0
export GLOG_colorlogtostderr=1
export GLOG_minloglevel=0

export cyber_trans_perf=0
export cyber_sched_perf=0

# for DEBUG log
#export GLOG_minloglevel=-1
#export GLOG_v=4

source ${CYBER_PATH}/tools/cyber_tools_auto_complete.bash

Second IPC have CYBER_IP=192.168.1.152 difference only. By the way, do i need to use linuxptp like in the Dual IPC tutorial?

**Comment by zhangchaoltt** [comment]
1. Make sure the two hosts under the same network segment of the local area network
2.RTPS transfer data using UDP, if the hosts under the same network segment of the local area network, under normal circumstances, you can definitely use tcpdump to capture related data. So please check you network again, make sure the hosts can receive data from each other with a UDP communication test program.

**Comment by zhangchaoltt** [comment]
Please reopen if you have further questions @alexiskovi

**Comment by alexiskovi** [comment]
I checked network settings and made sure that second ipc can get udp data. So now I have not idea what is wrong with it.
I cloned apollo r3.5.0 to both IPC, changed both CYBER_IP variables according to ipc's ip addresses. Started docker, and inside docker check udp, ipc's can communicate via it. But talker-listener isn't working.
What else should I check? What I possibly missed?

**Comment by zhangchaoltt** [comment]
Generally speaking, the problem can be solved according to the issue #7050 .
Now, whether there is an error when you start the talker-listener. What information can you see by executing cyber_monitor locally

**Comment by alexiskovi** [comment]
If I change back CYBER_IP to 127.0.0.1, then chatter is shown in cyber monitor:
![talker-listener](https://user-images.githubusercontent.com/19861339/64325082-2dcbf800-cfd0-11e9-971a-b05956d4ada8.png)

Else, if I change CYBER_IP to second host ip, cyber_monitor is empty:
![nrveovne](https://user-images.githubusercontent.com/19861339/64325167-548a2e80-cfd0-11e9-8132-693eb7714a69.png)

**Comment by zhangchaoltt** [comment]
Show ifconfig info in your two ipc

**Comment by alexiskovi** [comment]
setup.bash from IPC1:
![setup1](https://user-images.githubusercontent.com/19861339/64360505-4ad5ea80-d013-11e9-98b6-f6a22684b947.png)
ifconfig from IPC1:
![ifconfig1](https://user-images.githubusercontent.com/19861339/64360567-68a34f80-d013-11e9-8654-8091c79a8d03.png)

setup.bash from IPC2:
![setup2](https://user-images.githubusercontent.com/19861339/64360926-28909c80-d014-11e9-93fd-1793042dcb82.png)
ifconfig from IPC2:
![ifconfig2](https://user-images.githubusercontent.com/19861339/64360946-334b3180-d014-11e9-8a29-43c6db044a25.png)

**Comment by zhangchaoltt** [comment]
set cyber_ip=10.1.20.86 on ipc1, set cyber_ip=10.1.20.210 on ipc2

**Comment by alexiskovi** [comment]
Yes, it worked. My bad. Thanks!!!

**Comment by AlexandrZabolotny** [comment]
Hi all!
I am using Apollo pre6
I am running Apollo on two parallel PCs according to this [instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_setup_dual_ipc.md).
But I notice the following peculiarity. The frequency of published channels by computer # 1 does not match the frequency of this channel on computer # 2. For example, if the frequency of the channel "/ apollo / sensor / lidar128 / compensator / PointCloud2" on PC1 is 10 Hz, then the frequency on PC2 can be 6 Hz. I also noticed a feature that big data channels slow down the work of another PC.

So I have a question.
Is it possible to publish not all channels, but selective channels between two PCs?
