### ISSUE TITLE
Upgrade Cyber python API to python3

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#9510]
Since python2 became more and more out-of-date, especially some frequently used lib such as numpy and scipy were no longer support python2 anymore, does there any time schedule for Apollo upgrade these python wrapper to python3 support?

**Comment by baowanyu** [comment]
Upgrading the Python version requires the entire Apollo project to work together. I recommend that you follow up on major updates to the Apollo program.

**Comment by jinfagang** [comment]
I think the calling way of Cyber python lib can be easily compatible with python3, the questions is all binding of current Cyber does not compatible with python3 at all.

**Comment by nullptr123** [comment]
Is anyone on this issue? seems no one cares about this?

python2 will retire after 2 month and 3 days

**Comment by daohu527** [comment]
The latest version already supports python3
