### ISSUE TITLE
Can't find ad_rss and rss directory

### ISSUE THREAD

**Issue by youhanmo** [ApolloAuto/apollo#9511]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 18.04
- **Apollo installed from (source or binary)**: Source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:Perception Module

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
After downloading the ad-rss-lib on my own. I meet this problem.
I couldn't find the exact ad_rss directory.
I think the directory 'rss' in 'apollo/third_party/rss' meets the requirement.
But this rss directory leads to further mistakes. 
Waiting for help.

### Supporting materials (screenshots, command lines, code/script snippets):
![image](https://user-images.githubusercontent.com/26746278/63701707-0484cc80-c858-11e9-931c-a21c15d28dbf.png)

**Comment by jmtao** [comment]
@youhanmo try restarting docker.
