### ISSUE TITLE
Dynamic subscription

### ISSUE THREAD

**Issue by anchans** [ApolloAuto/apollo#9519]
I wish to know if Cyber RT supports dynamic reader subscriptions. This is something that ROS provides and it handles deletion and addition of readers along with threading really well. I did see some functions to delete readers such as `delete_PyReader` but I do not think it handles re-subscriptions and nested callbacks well. Could anyone shed some light on this?

Thanks

**Comment by mickeyouyou** [comment]
This is a suggestion I understand  to listen new reader and remove readers.


you need create a topology callback, and use this callback function in method `apollo::cyber::service_discovery::TopologyManager::Instance()::TopologyChanged`, there is example in `cyber_visualizer`:
```c++
  auto topologyCallback =
      [&w](const apollo::cyber::proto::ChangeMsg& change_msg) {
        w.TopologyChanged(change_msg);
      };

  auto channelManager =
      apollo::cyber::service_discovery::TopologyManager::Instance()
          ->channel_manager();
  channelManager->AddChangeListener(topologyCallback);
```

and in your callback function, filter by change type is `CHANGE_CHANNEL`  and ROLETYPE IS `ROLE_READER`, OperateType is OPT_JOIN or OPT_LEAVE.  here is a example below. 

```cpp
void MainWindow::TopologyChanged(
    const apollo::cyber::proto::ChangeMsg& changeMsg) {
  if (apollo::cyber::proto::ChangeType::CHANGE_CHANNEL ==
          changeMsg.change_type() &&
      apollo::cyber::proto::RoleType::ROLE_READER == changeMsg.role_type() &&
      apollo::cyber::proto::OperateType::OPT_JOIN == changeMsg.operate_type()) {
    // add you customize logic here 
    // AddNewWriter(changeMsg.role_attr());
  }
}
```

**Comment by yaoweifeng01** [comment]
@anchans We provide a Python-based interface that can be referenced [listener](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/examples/listener.py),[talker](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/examples/talker.py). You can see the "def callback(data):" in Python.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
