### ISSUE TITLE
No obstacles can be detected in navigation mode

### ISSUE THREAD

**Issue by yujun2019** [ApolloAuto/apollo#9520]
**System information**
    OS Platform and Distribution (e.g., Linux Ubuntu 14.04): Linux Ubuntu 14.04
    Apollo installed from (source or binary): Source
    Apollo version:3.5

**Steps to reproduce the issue:**
Operate according to the document 《how_to_use_apollo_2.5_navigation_mode_cn.md》, but there is no correct output. The topic “/apollo/perception/obstacles” is empty.
 
**Supporting materials (screenshots, command lines, code/script snippets):**
![Screenshot from 2019-08-27 10-09-59](https://user-images.githubusercontent.com/47655308/63735641-10ea4300-c8b3-11e9-8fa5-aadb4368b319.png)

**Comment by youhanmo** [comment]
Hi , I am wondering that did you find ad_rss directory when building  './apollo.sh build_opt_gpu'.
I can not find it anywhere.

**Comment by yujun2019** [comment]
should start tf, and lidar, before fusion
