### ISSUE TITLE
rosbag_to_record not support sensor_msgs/Image

### ISSUE THREAD

**Issue by journey-wang** [ApolloAuto/apollo#9524]
Please add the feature to rosbag_to_record tool

**Comment by Eclipsehelio** [comment]
**1、Add the following branch to 'main' function:** 
else if (channel_name == "/apollo/sensor/camera/traffic/image_short"
               || channel_name == "/apollo/sensor/camera/traffic/image_long"
               || channel_name == "/apollo/sensor/camera/image_long"
               || channel_name == "/apollo/sensor/camera/image_short") {
      auto ros_msg = m.instantiate<sensor_msgs::Image>();
      auto pb_msg = std::make_shared<apollo::drivers::Image>();
      convert_Image(pb_msg, ros_msg);
      pb_msg->SerializeToString(&serialized_str);
    }
**2、Add the 'convert_Image' function prior to 'main':**
int convert_Image(std::shared_ptr<apollo::drivers::Image> proto,
                  sensor_msgs::Image::ConstPtr rawdata) {
  auto header = proto->mutable_header();
  header->set_timestamp_sec(rawdata->header.stamp.toSec());
  header->set_frame_id(rawdata->header.frame_id);
  proto->set_frame_id(rawdata->header.frame_id);
  proto->set_measurement_time(rawdata->header.stamp.toSec());
  proto->set_width(rawdata->width);
  proto->set_height(rawdata->height);
  proto->set_encoding(rawdata->encoding);
  proto->set_step(rawdata->step);

  if (rawdata->encoding == "yuyv") {
    proto->mutable_data()->reserve(rawdata->width * rawdata->height * 2);
    proto->set_data((const void*)&rawdata->data[0], rawdata->width * rawdata->height * 2);
  } else if (rawdata->encoding == "rgb8") {
    proto->mutable_data()->reserve(rawdata->width * rawdata->height * 3);
    proto->set_data((const void*)&rawdata->data[0], rawdata->width * rawdata->height * 3);
  } else {
    std::cerr << "Wrong pixel fromat:" << rawdata->encoding <<
                 ",must be yuyv | rgb24" << std::endl;
    return 0;
  }

  return 1;
}

**Comment by journey-wang** [comment]
"if (rawdata->encoding == "yuyv") {
proto->mutable_data()->reserve(`rawdata->width * rawdata->height * 2`);
} else if (rawdata->encoding == "rgb8") {
proto->mutable_data()->reserve(`rawdata->width * rawdata->height * 3`);"

why not use: 

proto->mutable_data()->reserve(`rawdata->step * rawdata->height`);"
