### ISSUE TITLE
master branch couldn't clean; couldn't use rosbag_to_record cmd

### ISSUE THREAD

**Issue by SeasoulChris** [ApolloAuto/apollo#9532]
### System information

- **OS Platform and Distribution (Ubuntu18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (master)**:
-**NVIDIA-DRIVER Version(430) 

Hello guys， after install master branch, I got those errors:
1、
![Screenshot from 2019-08-28 12-22-38](https://user-images.githubusercontent.com/19869555/63844515-f4d1c900-c9ba-11e9-81cc-4db85cdef618.png)
2、
![1](https://user-images.githubusercontent.com/19869555/63844730-467a5380-c9bb-11e9-8562-3f2e69015711.png)
Any suggestions? Thank you!

**Comment by Eclipsehelio** [comment]
1、Make sure that there is a file named 'WORKSPACE' under /apollo/ directory
2、Maybe you should 'source /home/tmp/ros/setup.bash'. Um. that is it!

**Comment by Eclipsehelio** [comment]
If there does not have a 'WORKSPACE' file, execute './apollo.sh build' command and there will be one!

**Comment by SeasoulChris** [comment]
> If there does not have a 'WORKSPACE' file, execute './apollo.sh build' command and there will be one!

Thank you for your help , but that didn't work for me , when I try to build rosbag_to_record alone with cmd "bazel build /apollo/modules/data/tools/rosbag_to_record:all" , I got errors below:

**Comment by SeasoulChris** [comment]
> > If there does not have a 'WORKSPACE' file, execute './apollo.sh build' command and there will be one!
> 
> Thank you for your help , but that didn't work for me , when I try to build rosbag_to_record alone with cmd "bazel build /apollo/modules/data/tools/rosbag_to_record:all" , I got errors below:

**Comment by SeasoulChris** [comment]
> > If there does not have a 'WORKSPACE' file, execute './apollo.sh build' command and there will be one!
> 
> Thank you for your help , but that didn't work for me , when I try to build rosbag_to_record alone with cmd "bazel build /apollo/modules/data/tools/rosbag_to_record:all" , I got errors below:

**Comment by SeasoulChris** [comment]
> If there does not have a 'WORKSPACE' file, execute './apollo.sh build' command and there will be one!

ERROR: (09-05 09:42:57.428) /apollo/modules/data/tools/rosbag_to_record/BUILD:5:1: C++ compilation of rule '//modules/data/tools/rosbag_to_record:rosbag_to_record' failed (Exit 1).
In file included from modules/data/tools/rosbag_to_record/rosbag_to_record.cc:17:0:
external/ros/include/rosbag/bag.h: In member function 'void rosbag::Bag::doWrite(const string&, const ros::Time&, const T&, const boost::shared_ptr<std::map<std::basic_string<char>, std::basic_string<char> > >&, std::string, std::string, std::string)':
external/ros/include/rosbag/bag.h:594:85: error: there are no arguments to 'logDebug' that depend on a template parameter, so a declaration of 'logDebug' must be available [-fpermissive]
         logDebug("  curr_chunk_size=%d (threshold=%d)", chunk_size, chunk_threshold_);

**Comment by Eclipsehelio** [comment]
What about this:
bazel build --jobs=6 -c opt --verbose_failures --define ARCH=x86_64 --define USE_GPU=true --cxxopt=-DUSE_GPU --define CAN_CARD=esd_can --cxxopt=-DUSE_ESD_CAN=true --action_env=LD_LIBRARY_PATH --action_env=PATH //modules/data/tools/rosbag_to_record:rosbag_to_record

**Comment by SeasoulChris** [comment]
> How about this:
> bazel build --jobs=6 -c opt --verbose_failures --define ARCH=x86_64 --define USE_GPU=true --cxxopt=-DUSE_GPU --define CAN_CARD=esd_can --cxxopt=-DUSE_ESD_CAN=true --action_env=LD_LIBRARY_PATH --action_env=PATH //modules/data/tools/rosbag_to_record:rosbag_to_record

I tried, but still got errors:
![Screenshot from 2019-09-06 15-17-13](https://user-images.githubusercontent.com/19869555/64408627-cd18ea00-d0b9-11e9-82e0-61a2e505efe9.png)

**Comment by SeasoulChris** [comment]
> How about this:
> bazel build --jobs=6 -c opt --verbose_failures --define ARCH=x86_64 --define USE_GPU=true --cxxopt=-DUSE_GPU --define CAN_CARD=esd_can --cxxopt=-DUSE_ESD_CAN=true --action_env=LD_LIBRARY_PATH --action_env=PATH //modules/data/tools/rosbag_to_record:rosbag_to_record
I tried, but still got errors:
![Screenshot from 2019-09-06 15-17-13](https://user-images.githubusercontent.com/19869555/64408660-e15ce700-d0b9-11e9-81d1-226f875d2dff.png)

**Comment by SeasoulChris** [comment]
> How about this:
> bazel build --jobs=6 -c opt --verbose_failures --define ARCH=x86_64 --define USE_GPU=true --cxxopt=-DUSE_GPU --define CAN_CARD=esd_can --cxxopt=-DUSE_ESD_CAN=true --action_env=LD_LIBRARY_PATH --action_env=PATH //modules/data/tools/rosbag_to_record:rosbag_to_record

I tried, but still got errors:
![Screenshot from 2019-09-06 15-17-13](https://user-images.githubusercontent.com/19869555/64408887-69db8780-d0ba-11e9-898a-c7af251865a0.png)

**Comment by tornadomeet** [comment]
@SeasoulChris  do you fix this error?

**Comment by mustafaakdeniz** [comment]
It's the same compile error in r5.0 release and master branch. We need this tool but seems not possible to compile right now. Can anyone share rosbag_to_record tool binary or can developers fix this error?

**Comment by mustafaakdeniz** [comment]
I shouldn't do this and apollo devs shouldn't commit something broken to the repository but here is what I've done just to convert one bag file:
- checkout to r3.5.0
- install git-lfs and fetch all lfs files
- download all necessary docker containers
- compile rosbag_to_record and cyber_recorder 
- convert the file
