### ISSUE TITLE
GNSS Init failed：

### ISSUE THREAD

**Issue by ftesr** [ApolloAuto/apollo#9539]
I0829 08:20:34.263742  9996 data_parser.cc:110] Creating data parser of format: 31
E0829 08:20:34.266372  9996 serial_stream.cc:126] Open device /dev/ttyACM0 failed, error: No such file or directory
E0829 08:20:34.267387  9996 raw_stream.cc:306] data stream connect failed.
E0829 08:20:34.267447  9996 raw_stream.cc:260] gnss driver connect failed.
E0829 08:20:34.269091  9996 apollo_app.cc:59] gnss Init failed: DRIVER_ERROR_GNSS: Init stream failed!
E0829 08:20:34.270051  9996 serial_stream.cc:126] Open device /dev/ttyACM0 failed, error: No such file or directory
I0829 08:20:34.270119  9996 raw_stream.cc:412] Logout command: EVENTOUTCONTROL MARK2 DISABLE
E0829 08:20:34.270162  9996 serial_stream.cc:126] Open device /dev/ttyACM0 failed, error: No such file or directory
I0829 08:20:34.270262  9996 raw_stream.cc:412] Logout command: EVENTOUTCONTROL MARK1 DISABLE

**Comment by Eclipsehelio** [comment]
Is there a device file under /dev when you connect your GNSS reciever with the Compute Unit? Or the device file is  /dev/ttyACM0?
