### ISSUE TITLE
Traffic Light Display Error with demo_3.5.record

### ISSUE THREAD

**Issue by ntutangyun** [ApolloAuto/apollo#9544]
**Describe the bug**
When I keep switching setup mode from Dreamview, multiple traffic lights are spawned in the display as shown at screenshot section.

**To Reproduce**
1. Follow github instructions to download, build images, start docker containers, and build apollo inside container.
2. Follow Github instructions to launch apollo by cyber_recorder play ... demo_3.5.record -l
3. open dreamview and see the update. 
4. If now we keep switching the setup mode from one to another
5. a lot of traffic lights will be spawn during those switches.

**Expected behavior**
I expected the traffic lights should be cleared before switching to another setup mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/16061105/63915241-16d55500-ca68-11e9-86da-b5c034c58b48.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 1604
 - Browser chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
NIL

**Comment by unacao** [comment]
#9552
