### ISSUE TITLE
Build error linking libcuda.so

### ISSUE THREAD

**Issue by renegadephysicist** [ApolloAuto/apollo#9545]
**Describe the bug**
There is a linking error when building apollo

hash: 2a942d37111fe7889f3c56c0d8045b3f4bb51d6e 

**To Reproduce**
run: bash apollo.sh build

**Screenshots**
![image](https://user-images.githubusercontent.com/32599092/63930640-a28cb880-ca4b-11e9-8052-188041adce14.png)

**Additional context**
libuda.so is available at /usr/local/cuda/compat/libuda.so and  /usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so (/usr/local/cuda/lib64/stubs)

Edit: [This patch](https://github.com/ApolloAuto/apollo/files/3556442/cuda_patch.txt) fixes the problem but there might be a better solution.

**Comment by ycool** [comment]
Try `apollo.sh clean` then `apollo.sh build` again. Recently we upgraded pytorch version and it might confuse bazel build. Thanks.
