### ISSUE TITLE
How to build additional GPS receiver drivers in r1.0.0

### ISSUE THREAD

**Issue by dwrr** [ApolloAuto/apollo#9548]
### System information

- Linux Ubuntu 16.04
- Apollo from source
- Version 1.0

How do I rebuild the apollo drivers module. It doesn't contain a BUILD file and doesn't get built with the standard apollo.sh script as far as I can see. 

I tried the standard catkin_make but that requires a workspace. Looking into the third_party ros folder it seems that the gnss_driver has been built already. Is doesn't seem to be possible to just catkin_make inside this workspace so is there a procedure?

Any more information would be great, thanks guys!

**Comment by Eclipsehelio** [comment]
How about './apollo.sh buildgnss'???

**Comment by Eclipsehelio** [comment]
Follow this link https://github.com/ApolloAuto/apollo/blob/r1.0.0/docs/howto/how_to_add_a_gps_receiver.md
Maybe it will help you.

**Comment by dwrr** [comment]
Thanks for the response @Eclipsehelio . "./apollo.sh buildgnss" is what I'm looking for. It's not mentioned anywhere though is it?

**Comment by Eclipsehelio** [comment]
@dwrr I found it directly in 'apollo.sh'. As I know that 'apollo.sh' control the procedure of all the build/clean/test stage through r1.0.0 to r5.0.0. So I just scanned the source code.
