### ISSUE TITLE
Why piecewise jerk speed optimizer always  failed when ego turn?

### ISSUE THREAD

**Issue by RunningPixEl** [ApolloAuto/apollo#9554]
piecewise jerk speed optimizer always failed when ego in turn
error msg in piecewise_jerk_speed_optimizer.cc located after piecewise_jerk_problem.Optimize()
 This may caused by centric acc limit, anyone know how to solve it?

### System information

- **Linux Ubuntu 16.04)*:
- **Apollo installed from (source)**:
- **Apollo version 3.5**:

**Comment by HongyiSun** [comment]
There is a fall back speed profile after piecewise_jerk_speed_optimizer failed, which will trying to slower down the vehicle until the optimizer can find a solution.
This is actually kind of "as design", although there are things on decision side that can be improved.

**Comment by RunningPixEl** [comment]
Thanks for your answer!!

**Comment by JJRedmond** [comment]
@HongyiSun Hi! Can you tell me how to fix this problem?
