### ISSUE TITLE
control message distance error_code: OK msg: "planning has no trajectory point."

### ISSUE THREAD

**Issue by udeto** [ApolloAuto/apollo#9568]
Hi,
I want to use apollo (3.0) with the carla simulator (0.9.5.).

I have successfully connected apollo and carla, but when I pass the waypoints to apollo the car does not move.

I am sending the waypoints on the ros topic `/apollo/routing_request` and get a "Routing success!" message on the monitor as a result. 

The planning module has the following error:
```
E0831 10:11:57.656193  7432 trajectory_stitcher.cc:159] the distance between matched point and actual position is too large. Replan is triggered. lat_diff = 2.10425e-07, lon_diff = 5.0594
E0831 10:12:01.297992  7432 trajectory_stitcher.cc:159] the distance between matched point and actual position is too large. Replan is triggered. lat_diff = 2.10425e-07, lon_diff = 5.1219
```
However the planning module publishes the message on `/apollo/planning`:
`trajectory_point {
  path_point {
    x: -3.24922968276
    y: 28.2791210075
    theta: 1.55190478421
    kappa: -0.000431162972088
    s: 24.4705144127
    dkappa: 0.000184319246155
    ddkappa: 0.0
  }
  v: 5.95111747937
  a: 1.66466648484
  relative_time: 6.70252118111
}
trajectory_point {
  path_point {
    x: -3.23777273409
    y: 28.8827493509
    theta: 1.55163883064
    kappa: -0.000307242230296
    s: 25.0742514772
    dkappa: 0.000203804291745
    ddkappa: 0.0
  }
  v: 6.12670687636
  a: 1.84965984662
  relative_time: 6.80252118111
}
trajectory_point {
  path_point {
    x: -3.22579030435
    y: 29.5048805608
    theta: 1.55147580696
    kappa: -0.000164938721502
    s: 25.696498069
    dkappa: 0.000220667105494
    ddkappa: 0.0
  }
  v: 6.32156659837
  a: 2.05016769888
  relative_time: 6.90252118111
}
trajectory_point {
  path_point {
    x: -3.2133788803
    y: 30.1475223905
    theta: 1.55141123627
    kappa: -1.11946580009e-05
    s: 26.33925974
    dkappa: 0.000235441429993
    ddkappa: 0.0
  }
  v: 6.53727650853
  a: 2.26675832291
  relative_time: 7.00252118111
}
trajectory_point {
  path_point {
    x: -3.20050131583
    y: 30.8128409064
    theta: 1.55143698202
    kappa: 0.000154116151633
    s: 27.0047028702
    dkappa: 0.000248336079839
    ddkappa: 0.0
  }
  v: 6.77547329806
  a: 2.5
  relative_time: 7.10252118111
}
decision {
  main_decision {
    cruise {
      change_lane_type: FORWARD
    }
  }
  object_decision {
  }
  vehicle_signal {
    turn_signal: TURN_NONE
  }
}
latency_stats {
  total_time_ms: 5.72896003723
  task_stats {
    name: "DpPolyPathOptimizer"
    time_ms: 1.55305862427
  }
  task_stats {
    name: "PathDecider"
    time_ms: 0.00238418579102
  }
  task_stats {
    name: "DpStSpeedOptimizer"
    time_ms: 0.0715255737305
  }
  task_stats {
    name: "SpeedDecider"
    time_ms: 0.00214576721191
  }
  task_stats {
    name: "QpSplineStSpeedOptimizer"
    time_ms: 0.707387924194
  }
  task_stats {
    name: "ReferenceLineProvider"
    time_ms: 1.27267837524
  }
  init_frame_time_ms: 0.00264549255371
}
routing_header {
  timestamp_sec: 1567237881.59
  module_name: "routing"
  sequence_num: 1
}
right_of_way_status: UNPROTECTED
lane_id {
  id: "8_1_-1"
}
lane_id {
  id: "1_1_-1"
}
lane_id {
  id: "2_1_-1"
}
engage_advice {
  advice: KEEP_ENGAGED
}
trajectory_type: NORMAL

(this is of course only the end of the message)

To me it looks like the planning module is publishing a valid trajectory.

The control module however publishes the following control command on `/apollo/control`:
`header {
  timestamp_sec: 1567240253.25
  module_name: "control"
  sequence_num: 966
  lidar_timestamp: 0
  camera_timestamp: 0
  radar_timestamp: 0
  status {
    error_code: OK
    msg: "planning has no trajectory point."
  }
}
throttle: 0.0
brake: 50.0
speed: 0.0
gear_location: GEAR_DRIVE
signal {
  turn_signal: TURN_NONE
}
latency_stats {
  total_time_ms: 0.40864944458
  total_time_exceeded: false
}
engage_advice {
  advice: READY_TO_ENGAGE
}`

Dreamview looks like this:
![Screenshot from 2019-08-31 10-30-38](https://user-images.githubusercontent.com/52383800/64061398-83706100-cbda-11e9-88c6-f94327cf376b.png)

I do not understand this error, can someone please help me figure it out?

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

**Comment by Capri2014** [comment]
@udeto I think your planning trajectory looks strange: `relative_time: 6.70252118111` for the first point? What is the header time for planning modules?

**Comment by udeto** [comment]
The header time for planning modules is: 
```
timestamp_sec: 1567528938.23
module name: std_planning
sequence num: 3265
```

I am passing a pre defined route as a list of waypoints to the routing module on the /apollo/routing_request topic:


```
header {
  timestamp_sec: 1567529914.0
  module_name: "dreamview"
  sequence_num: 1
}
waypoint {
  pose {
    x: -3.45605635643
    y: 3.177764893
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45609807968
    y: 3.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45632362366
    y: 4.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45654964447
    y: 5.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45677518845
    y: 6.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45700120926
    y: 7.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45722675323
    y: 8.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45745277405
    y: 9.17774963379
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45767831802
    y: 10.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45790433884
    y: 11.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45812988281
    y: 12.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45835590363
    y: 13.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.4585814476
    y: 14.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45880746841
    y: 15.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45903301239
    y: 16.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.4592590332
    y: 17.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45948457718
    y: 18.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45971059799
    y: 19.1777496338
  }
}
waypoint {
  id: "2_1_-1"
  pose {
    x: -3.45980858803
    y: 20.1764068604
  }
}
```
I thought that maybe there was something wring with the waypoints, but the routing module seems to work..

**Comment by Capri2014** [comment]
@udeto Your routing is fine, the problem is the header time diff between planning (`1567528938.23`) and control ( `1567240253.25`), they have `288684.98` sec difference...

**Comment by udeto** [comment]
Sorry I guess the messages were from different runs. I checked again and the timestamps of both modules do not have a difference (at least no difference bigger than a second).

**Comment by Capri2014** [comment]
@udeto This is usually due to that in one of previous frame in planning was with empty trajectory, in latest mater we also added the detailed seq number of which frame with empty trajectory, like in https://github.com/ApolloAuto/apollo/blob/0a1afa44aed73e1578196b10bb3534dd779da566/modules/control/control_component.cc#L376 .

**Comment by udeto** [comment]
I figured it out, the problem was that the control module threw an "estop" error when the trajectory was not yet planned. So when the planning module published the trajectory the control module was still stuck at "estop" and therefore sending the "estop" brake command constantly. I needed to send a reset command via the control pad to get the control module to re-evaluate its status. After that the control module follows the planned trajectory.

Only one problem remains, the car is moving very slow, never exceeding 6 kmph. Is there a possibility to set a higher target velocity?

**Comment by Capri2014** [comment]
then you need to dive into the details of planning/control/mapdata, the reasons can be in all three modules, I would recommend start by checking the map speed limits.

**Comment by Capri2014** [comment]
And please create a separate threads for it.

**Comment by udeto** [comment]
Ok, thank you for your help!

**Comment by 13940267943** [comment]
did you solve the problem about  the car is moving very slow?
now, I also meet this problem.
