### ISSUE TITLE
How to run perception module

### ISSUE THREAD

**Issue by chenghanzh** [ApolloAuto/apollo#9570]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: branch r5.0.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**: On the perception documentation, I saw that the input of perception module are sensor datas and it will output obstacle, lane information. I currently have a record file with all the sensor data and I wonder if there is a way that I can put in the sensor data and get the result of those processed information. If so, where to input my data and where I can find the output? Thank you!

**Comment by luqiang21** [comment]
@chenghanzh Hi, you need to have `localization` and `transform` modules work to run `perception`. You need to check your sensor data to make sure you have the required data for those two modules.

**Comment by chenghanzh** [comment]
@luqiang21 
My record file looks like this. I downloaded it from apollo open data platform. 
![Screen Shot 2019-08-31 at 8 24 30 PM](https://user-images.githubusercontent.com/50680244/64070432-6add6680-cc2d-11e9-8fb6-5df274edbb35.png)

Do you know which command I should use and where I can find the output data (maybe visualize them)?

I tried to run files in /apollo/modules/perception/production/dag but it says segmentation fault. I think it might be input/output issues and I wander where I can find these files.

**Comment by luqiang21** [comment]
@chenghanzh To run each module, after you run `bootstrap.sh`, you can either run them using buttons in the dreamview, or run them using the corresponding `dag` files. The visualization of perception will be shown in dreamview. I suggest you try an AD simulator like [LGSVL](www.lgsvlsimulator.com) to go through all setups of apollo and check how each module works. Then you can try your data.

**Comment by chenghanzh** [comment]
@luqiang21 I'll try it. Thank you so much!

**Comment by natashadsouza** [comment]
@chenghanzh thank you for your interest in the Apollo Perception module. Currently closing this issue as it appears to be resolved. If you do have additional questions, feel free to reopen it.

**Comment by Iqbalparvi** [comment]
@Chenghanzh did you solve the problem , i want the same work with prediction module any suggestion will be appreciated
Regards

**Comment by zhanghming** [comment]
@luqiang21 Hello, you mentioned that we can use LGSVL to test the Apollo, I wonder is there any detailed steps to run LGSVL? I find the official documents are so confusing that I cann't understand a lot. 

For example, I'm not sure whether should I pull the lgsvl/apollo5.0 docker image and run all things in that image? What the relationship between the lgsvl/apollo5.0 image and the appolloauto/apollo image?

**Comment by luqiang21** [comment]
Hi @zhanghming, if you want to run apollo 5.0 with LGSVL simulator, you should use `lgsvl/apollo5.0` docker image and our [fork](https://github.com/lgsvl/apollo-5.0) of apollo since we added files to enable the connection between apollo and LGSVL. `lgsvl/apollo5.0`is based on `appolloauto/apollo`. 

Please let me know if you need any other help to run LGSVL.
