### ISSUE TITLE
请问，我可以在哪里获得apollo支持的xml格式的地图文件？

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#9572]
- **OS Platform and Distribution 16.04**:
- **Apollo installed from source**:
- **Apollo version 5.0**:

我看/apollo/module/map/data/demo/里面只有txt格式的地图，我想了解下opendrice_adapter这部分代码的运行步骤，想要通过xml格式的地图，相互印证着学习。我如何获取xml格式的地图？

**Comment by Zhenni17** [comment]
Hi @BigBenSure , we currently only opensource txt & sim based map files for the developer community. One way to attain the xml format of HD map is via Baidu Apollo's HD map service or other third party HD map provider that is compatible with Apollo software stack. Let me know if you have any additional questions.
