### ISSUE TITLE
Apollo2.5: The button "camera" in dreamview does not work. 

### ISSUE THREAD

**Issue by foreverwx219** [ApolloAuto/apollo#9573]
![dreamview](https://user-images.githubusercontent.com/46985534/64095987-fc1a1d80-cd92-11e9-910b-feebc45af2e7.png)
Hello, All
I met a problem while installing camera. According to the official guidance document(https://github.com/ApolloAuto/apollo/blob/v3.1_dev/docs/specs/D-kit/Auto_Driving--Sensor_integration_cn.md), I clicked the "camera" button to show the image. But the button closed automatically soon, and there is no output image. 

I'm not sure where the problems are. Does anyone have the same problem? Could you please give me some suggestions?

Thanks!

System information:
Apollo2.5
Ubuntu 14.04 LTS
64bits

**Comment by luqiang21** [comment]
@foreverwx219 If the button turns off automatically, that means something wrong with your camera. You should try to run the same module in terminal to see what errors you are having.

**Comment by foreverwx219** [comment]
@luqiang21 Did you mean that maybe the camera itself has problem? So I could try other sensors like lidar to find the errors.

**Comment by foreverwx219** [comment]
> @foreverwx219 If the button turns off automatically, that means something wrong with your camera. You should try to run the same module in terminal to see what errors you are having.

I tried other buttons but all of them turn on or turn off automatically, just like the picture below. What should I do to run the same module in terminal?
![dreamview_moduleControl](https://user-images.githubusercontent.com/46985534/64137677-4e5b4d00-ce2c-11e9-9c3c-64e5326f062e.png)

**Comment by luqiang21** [comment]
@foreverwx219 I am not sure whether the same command still works. I used something like `scripts/perception.sh start_fe` to run the `perception` module with debug messages. You can try to find the corresponding script for `camera` in the same folder.

**Comment by foreverwx219** [comment]
> @foreverwx219 I am not sure whether the same command still works. I used something like `scripts/perception.sh start_fe` to run the `perception` module with debug messages. You can try to find the corresponding script for `camera` in the same folder.

Thanks for your reply!
I'm not sure where the corresponding script for `camera` is. I find a document named "usb_camera.sh" in path "/apollo/scripts/". Maybe it has something wrong?
![apollo_scripts](https://user-images.githubusercontent.com/46985534/64219076-8e870200-cef6-11e9-84f0-fdd7a611587d.png)
![usb_camera](https://user-images.githubusercontent.com/46985534/64219077-8e870200-cef6-11e9-87a6-61bf46beb57c.png)

When running 'bash /apollo/apollo.sh build_usbcam', I find a warning(show in the picture below). does it cause this problem?
![build](https://user-images.githubusercontent.com/46985534/64219739-49b09a80-cef9-11e9-9a13-9c760d8a3ccd.png)

**Comment by foreverwx219** [comment]
I have solved my problem. Using 'sudo bash docker/scripts/dev_start.sh -l -t new0828' to start docker causes this problem. Then I re-install the whole system and use 'sudo chmod 777 /var/run/docker.sock'&'bash docker/scripts/dev_start.sh' to start docker. The "camera" button works well and show the picture successfully. 
Thanks very much! @luqiang21

**Comment by luqiang21** [comment]
@foreverwx219 Yeah, you should not use `sudo` when you do `dev_start.sh`. It will cause problems.
Great to hear you solved the problem.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
