### ISSUE TITLE
release image error

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#9574]
**Describe the bug**
When I want to release a docker image. I do as follows:
1. bash apollo.sh build_opt_gpu
2.bash apollo.sh release
3. exit docker 
4. bash apollo_docker.sh gen
   On this step ,many error happens:
cp: cannot stat '/root/mnt/apollo_release/apollo/bazel-bin/modules/third_party_perception/libthird_party_perception_component.so.runfiles/apollo/_solib_k8/libmodules_Scommon_Smath_Sliblinear_Uinterpolation.so': No such file or directory
cp: cannot stat '/root/mnt/apollo_release/apollo/bazel-bin/modules/third_party_perception/libthird_party_perception_component.so.runfiles/apollo/_solib_k8/libcyber_Stime_Slibrate.so': No such file or directory
cp: cannot stat '/root/mnt/apollo_release/apollo/bazel-bin/modules/third_party_perception/libthird_party_perception_component.so.runfiles/apollo/_solib_k8/libcyber_Sproto_Slibtopology_Uchange_Uproto.so': No such file or directory
cp: cannot stat '/root/mnt/apollo_release/apollo/bazel-bin/modules/third_party_perception/libthird_party_perception_component.so.runfiles/apollo/_solib_k8/libmodules_Sthird_Uparty_Uperception_Slibthird_Uparty_Uperception_Ufusion.so': No such file or directory
cp: cannot stat '/root/mnt/apollo_release/apollo/bazel-bin/modules/third_party_perception/libthird_party_perception_component.so.runfiles/apollo/_solib_k8/libmodules_Scommon_Sproto_Slibgeometry_Uproto_Ulib.so': No such file or directory

5.  bash docker/scripts/release_start.sh  iamge_tag
6. bash docker/scripts/release_into.sh
    go into the docker and execute some appliceation . And I found miss many dependency.like
libadv_bcan.so.1 => not found
libadv_trigger.so.1 => not found
libthird_Uparty_Stf2_Slibtf2.so => not found
libfastcdr.so.1 => not found
libfastrtps.so.1 => not found

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 14.04
 - Browser [e.g. chrome, safari] crhrome
 - Version [e.g. 22]  5.0.0

**Comment by Capri2014** [comment]
I thought we have deprecated the release image long time ago, please @ycool @xiaoxq @wanglei828 correct me if I am wrong.

**Comment by sinopec** [comment]
> I thought we have deprecated the release image long time ago, please @ycool @xiaoxq @wanglei828 correct me if I am wrong.

So,if I want to do e release, what should I do now?

**Comment by gengqx** [comment]
Currentlly,I use release to do real test in vehicle,I change the release base:run docker  to dev docker,to make sure all the lib are installed,then use the method you use to release a new docker.  see in apollo_docker.sh line 82.

**Comment by natashadsouza** [comment]
@sinopec we no longer use the release image. It has been taken out of our documentation and build process as well. @gengqx thank you for submitting a fix to this issue. If this method does work for you, we would like to include it in our documentation to help developers who would like to use the release image. Please confirm.

**Comment by sinopec** [comment]
> @sinopec we no longer use the release image. It has been taken out of our documentation and build process as well. @gengqx thank you for submitting a fix to this issue. If this method does work for you, we would like to include it in our documentation to help developers who would like to use the release image. Please confirm.

@gengqx  thanks for your reply , After a try,I found ,still many errors exist. If I want to make it work through, I still need to do a lot of modification —— add the missing *so.* and others.
@natashadsouza  Thanks for your reply. And I want to know If this is not supported again, what's the official way to release a image  now?

**Comment by gengqx** [comment]
Most problem may caused by the PATH which is not correct，so cafully play with it in apollo_base.sh，you would make it work。。I definitely use the release method in work. It is very convenient.
