### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by XiaoHongZuLiao** [ApolloAuto/apollo#9579]
when I build the code downloaded from GitHub, there comes a error causing building failed:
/apollo/modules/map/relative_map/tools/BUILD:18:1: C++ compilation of rule '//modules/map/relative_map/tools:navigator' failed (Exit 1).
so now , who can give me a hand......

**Comment by natashadsouza** [comment]
@XiaoHongZuLiao could you give us more details about your system as well as the steps you followed to build Apollo?

**Comment by Eclipsehelio** [comment]
Maybe there was something wrong with the zip file which you downloaded or something went wrong when you unzip the source code ...

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza well, now it doesn`t throw out any exceptions and indicate "build failed" directly......
the steps I followed to build Apollo seems to accuracy, install docker, git clone Apollo, pull down docker images and then step into docker environment, when it come to this step, all things goes well, but when I type in "bash apollo.sh build", the progress runs for little time, and during this period, I found it also downloads something like libs from Internet, after this ,it turns out "build failed". So now, I`m considering whether the RAM of my host should be at least 8G, because my host only exist 4G memory.

**Comment by XiaoHongZuLiao** [comment]
@Eclipsehelio I think there shouldn`t be someting wrong with the zip file I downloaded from github because I`ve tried so many times downloading hahaha .... But whether the code needs to be modified should be carefully taken. I have saw one suggestion that before building the project we should change the value of JOB_AGE to 1. Have you ever heard of this?

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza  sorry for my late replying!

**Comment by XiaoHongZuLiao** [comment]
@ Eclipsehelio sorry for my late replying!

**Comment by XiaoHongZuLiao** [comment]
@Eclipsehelio sorry for my late replying!

**Comment by XiaoHongZuLiao** [comment]
well, now I`m trying to build the apollo project again and failed again.....the information is :
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
ERROR: (09-16 15:38:53.089) build interrupted.
INFO: (09-16 15:38:53.091) Elapsed time: 359.813s
The OS I use this time is ubuntu 16.04, does it matter?
Or I need to run it on ubuntu18.04? I`ll try it tomorrow!!!!

**Comment by XiaoHongZuLiao** [comment]
What a pity! I`ve tried about two times where the environment and the hardware all meets the requirements, but it turns out still failed without any hint. I don`t know how to go next.

**Comment by natashadsouza** [comment]
@XiaoHongZuLiao did you upgrade your RAM and try again?

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza Yes, of course. I`ve upgrade my RAM to 8G, but failed again , even worse , without any hint.

**Comment by natashadsouza** [comment]
@XiaoHongZuLiao I would recommend deleting Apollo completely from your system, and starting over. Since we do not have any error messages, it is almost impossible for me to debug unfortunately. Please try to re-clone and build once more and send me a screenshot of the build failure if you see it again.

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza All right, I`ll try it again and thank you very much!

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza luckily, build successfully, I build the code on cloud platform thus there`s no hardware problem , now how can I run a demo on the dreamview ?

**Comment by natashadsouza** [comment]
@XiaoHongZuLiao sounds good! Just follow the "How to Build Guide" it will walk you through the process.

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza Thank you very much! And may I ask you another question? Do you know where I can get the data of High Definition Map used in Apollo, or I made a mistake, the virtual car run Apollo just use normal guide map we usually use in lives?

**Comment by natashadsouza** [comment]
@XiaoHongZuLiao you can choose the map once Dreamview is set up. There is a drop down menu to choose whichever HD map you would like to use for your testing purposes. The How to document should walk you through the process. Thanks.

**Comment by XiaoHongZuLiao** [comment]
@natashadsouza All right, thanks again!

**Comment by con00** [comment]
> @natashadsouza luckily, build successfully, I build the code on cloud platform thus there`s no hardware problem , now how can I run a demo on the dreamview ?

@XiaoHongZuLiao, congrats on your build success. I will appreciate if you can give me some hands. I am struggling with alot of bugs at every given steps, I have tried some recommendations yet build has not been successful. By the way, which virtual platform did you use this time? If you don't mind, I can set up a google handout call for few seconds of your time so I can get some guidance from you. Here is my email id: wendy4great@gmail.com

Thanks for help.
