### ISSUE TITLE
ros bag & cyber record

### ISSUE THREAD

**Issue by sinopec** [ApolloAuto/apollo#9583]
**Is your feature request related to a problem? Please describe.**
Now ,we can transform a ros bag to cyber record. but  the transformation is related to topic names but not  the topic type.  Maybe this  will cause some confusion and inconvenience 
Sometimes we also need to transform cyber record to rosbag ,specially when we want to try a new algorithm in ros, and the software package only receive ros topics. So this tool will necessary

**Comment by baowanyu** [comment]
“rosbag_to_record” is designed to help developers quickly migrate from Apollo 3.0 to 3.5,  rather than providing a transition from any ros bag to cyber record. We recommend that you customize this tool to meet the needs of your work.

**Comment by bryantaoli** [comment]
Can I turn a cyber bag to a rosbag？

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
