### ISSUE TITLE
What's the exact goal of LiDAR perception module?

### ISSUE THREAD

**Issue by jiachens** [ApolloAuto/apollo#9588]
System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Apollo version (5.0)**:

1. I am not sure whether the goal of LiDAR perception is to:
    a. **percept all the obstacles which have impacts on the driving behavior**
    b. **or only percept the vehicle, non-vehicle, pedestrian, these 3 classes**

For example, if there is a rock on the road which definitely has impacts on the driving behavior, is LiDAR perception module's responsibility to detect it as an **unknown** class? or just ignore it?

The same example generalizes to small animals on the road, should LiDAR perception module detect it or not? Note that I only consider LiDAR, no other sensors.

Thanks in advance!

**Comment by techoe** [comment]
Currently lidar is used for mapping/localization/perception. In perception, we facilitates two lidar-based object detection approaches: One is to detect multiple objects (pedestrian, cyclist, motorcycle, sedan, truck, and more) using CNN and the other is to detect and segment objects using min-cut which detects any object in lidar data.

**Comment by jiachens** [comment]
> Currently lidar is used for mapping/localization/perception. In perception, we facilitates two lidar-based object detection approaches: One is to detect multiple objects (pedestrian, cyclist, motorcycle, sedan, truck, and more) using CNN and the other is to detect and segment objects using min-cut which detects any object in lidar data.

Thanks a lot for the reply!
I found codes about NCUT which could be Normalized-Cut. Can you give me a hint on where the code is used? Since when I use the previous Apollo version, there is no NCUT or min-CUT in the codebase

**Comment by jiachens** [comment]
> Currently lidar is used for mapping/localization/perception. In perception, we facilitates two lidar-based object detection approaches: One is to detect multiple objects (pedestrian, cyclist, motorcycle, sedan, truck, and more) using CNN and the other is to detect and segment objects using min-cut which detects any object in lidar data.

Also, I just wonder that is the CNN segmentor responsible for detecting all the objects on the road, or it is responsible for only detecting the classified obstacles?

**Comment by apollodevcommunity** [comment]
得到障碍物的位置，速度，加速度等信息。具体的处理流程请参考https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception_cn.md ——回复参考来自Apollo开发者社区issue达人赛 https://apollo.auto/developer/questiondata_cn.html?target=395
