### ISSUE TITLE
apollo5.0:HDMAP OpenDRIVE Format

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#9598]
- **OS Platform and Distribution ( Linux Ubuntu 16.04)**:
- **Apollo installed from (source)**:
- **Apollo version (5.0)**:

### Supporting materials (screenshots, command lines, code/script snippets):
apollo5.0的HDMAP OpenDRIVE Format有什么更新吗？有类似OpenDRIVE官方提供的pdf解释每一个成员及其属性的定义吗？

**Comment by BigBenSure** [comment]
想问我可以在哪儿下载到这类文件？或者方便的话请发我邮箱：youngsure1993@gmail.com

**Comment by natashadsouza** [comment]
Please send us your request at issue #3005 thanks! Currently closing this issue as we already have an issue created for opendrive requests.
