### ISSUE TITLE
error while loading shared libraries: libadolc.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lucianzhong** [ApolloAuto/apollo#9600]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
while run the garage_test in planning integration test and encounter the problem:
root@in_dev_docker:/apollo/bazel-bin/modules/planning/integration_tests# ./garage_test
./garage_test: error while loading shared libraries: libadolc.so.2: cannot open shared object file: No such file or directory

The lib can be find in /usr/lib, the /etc/ld.so.conf has been edited and updated by ldconfig

root@in_dev_docker:/usr/lib# find -name '*libadolc*'
./x86_64-linux-gnu/libadolc.so
./x86_64-linux-gnu/libadolc.so.1
./x86_64-linux-gnu/libadolc.so.1.1.1
./x86_64-linux-gnu/libadolc.a

root@in_dev_docker:/usr/lib# ldconfig

**Comment by Eclipsehelio** [comment]
libadolc.so.2 is needed by 'garage_test', but there is only one version of libadolc library, which is 'libadolc.so.1', so you should execute the command 'sudo apt install libadolc2' to install it.

**Comment by lucianzhong** [comment]
@Eclipsehelio 
Thanks for the replay. But still, got the problem. The lib can be found in /usr/lib in my computer.

**Comment by Eclipsehelio** [comment]
export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
ldd ./garage_test | grep libadolc.so
What's the output?

**Comment by lucianzhong** [comment]
root@in_dev_docker:/apollo# export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
root@in_dev_docker:/apollo# ldd ./garage_test | grep libadolc.so
ldd: ./garage_test: No such file or directory
root@in_dev_docker:/apollo#

**Comment by lucianzhong** [comment]
root@in_dev_docker:/apollo/bazel-bin/modules/planning/integration_tests#  export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
root@in_dev_docker:/apollo/bazel-bin/modules/planning/integration_tests# ldd ./garage_test | grep libadolc.so
	libadolc.so.2 => not found
root@in_dev_docker:/apollo/bazel-bin/

**Comment by lucianzhong** [comment]
I have manually linked the lib, and it  works. 
But, it come with another problem.Possible the ipopt error.


root@in_dev_docker:/apollo/bazel-bin/modules/planning/integration_tests# ./garage_test
./garage_test: symbol lookup error: /root/.cache/bazel/_bazel_zy/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/planning/integration_tests/../../../_solib_k8/libmodules_Splanning_Sopen_Uspace_Strajectory_Usmoother_Slibdual_Uvariable_Uwarm_Ustart_Uipopt_Uinterface.so: undefined symbol: _ZN7adoubleaSERKS_

**Comment by Eclipsehelio** [comment]
You said that 'libadolc.so.2' is under /usr/lib, so export LD_LIBRARY_PATH will be OK.
find -name 'libadolc.so*'

**Comment by Eclipsehelio** [comment]
What's the option you use to build apollo?
It's better to execute the program under /apollo, like:
root@in_dev_docker:/apollo# ./bazel-bin/modules/planning/integration_tests/garage_test

**Comment by Eclipsehelio** [comment]
nvidia@in_dev_docker:/apollo$ ./bazel-bin/modules/planning/integration_tests/garage_test
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from GarageTest
[ RUN      ] GarageTest.stop_obstacle

**Comment by Eclipsehelio** [comment]
nvidia@in_dev_docker:/apollo$ export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
nvidia@in_dev_docker:/apollo$ ldd ./bazel-bin/modules/planning/integration_tests/garage_test | grep libadolc.so

**Comment by lucianzhong** [comment]
@Eclipsehelio 

Thanks a lot for the replay. Below is the output of the ldd command, is it right?

root@in_dev_docker:/apollo# ldd ./bazel-bin/modules/planning/integration_tests/garage_test |grep libadolc.so
	libadolc.so.2 => /usr/lib/x86_64-linux-gnu/libadolc.so.2 (0x00007fd397eec000)

**Comment by lucianzhong** [comment]
./ apollo.sh build_cpu  is the build option

**Comment by Eclipsehelio** [comment]
@lucianzhong So the error 'undefined symbol: ZN7adoubleaSERKS' still exists? Have you tried to build with the option './apollo.sh build_opt_gpu' ?

**Comment by lucianzhong** [comment]
The error still exist after ./apollo.sh build_gpu

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
