### ISSUE TITLE
Support the left-hand driving /  支持左行

### ISSUE THREAD

**Issue by lucianzhong** [ApolloAuto/apollo#9606]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

### Supporting materials (screenshots, command lines, code/script snippets):

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
The opendrive is offically support the left-hand driving,( UK and Japan ).
I just want to know how the apollo treat the right-hand driving and left-hand driving?
Do we need to modify some config files to achieve the left-hand driving if we has an appropriate left-hand driving map?

**Comment by natashadsouza** [comment]
@lucianzhong that is a very good question. We currently only support left-hand driving. Unfortunately we do not have the plans to accommodate right-hand driving on our roadmap anytime soon as well because it would require a lot of changes on the software and hardware side.

**Comment by lucianzhong** [comment]
@natashadsouza Thanks a lot. Further more, if we only care about the simulation or the software side, which part do we need to change, for example, the reference_line_provider in planning module, could you give me some hints?

**Comment by jmtao** [comment]
@lucianzhong I believe most traffic rules, deciders, optimizers, and scenarios, in Planning module will have to be updated accordingly.  And prediction, routing, map modules.

**Comment by lucianzhong** [comment]
Thanks a lot @jmtao
