### ISSUE TITLE
protoc compile navigation.proto error?

### ISSUE THREAD

**Issue by JackRen88** [ApolloAuto/apollo#9626]
Hello,everyone!
When I use protoc to compile navigation.proto,there are some error,such as:
`navigation.proto:34:3: Expected "required", "optional", or "repeated".
navigation.proto:34:6: Expected field name.`
How should I solve it?

**Comment by jmtao** [comment]
@JackRen88 Did you compile inside docker?
The maps syntax is supported starting from protobuf v3.0.0.
Please check the version of your protobuf.
