### ISSUE TITLE
"librss_module.so librss_support.so" not support on aarch64 platform

### ISSUE THREAD

**Issue by xuming7up** [ApolloAuto/apollo#9642]
when I was building apollo on xavier platform, 
apollo/third_party/rss/lib/ shows 2 binary dynamic libs - "librss_module.so librss_support.so", it looks build under x86_64 platform, how can I get aarch64 binaries? I did't find the source code, and also find ad_rss in github, is apollo's rss  expired?

### System information

- **OS Platform and Distribution ( Linux Ubuntu 18.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (3.5)**:

### Steps to reproduce the issue:
./apollo.sh build_planning

### Supporting materials (screenshots, command lines, code/script snippets):
/usr/bin/ld: cannot find -lrss_module
/usr/bin/ld: skipping incompatible bazel-out/local-dbg/bin/_solib_arm/_U_S_Sthird_Uparty_Srss_Crss___Uthird_Uparty_Srss_Slib/librss_support.so when searching for -lrss_support
/usr/bin/ld: cannot find -lrss_support
collect2: error: ld returned 1 exit status

**Comment by gengqx** [comment]
you can find the source code at https://github.com/intel/ad-rss-lib . I don't think any module depend on this,it use ad_rss lib define in the workspace.in,so may be you can try to remove the thirdparty/rss/BUILD to never build this lib. if is not work,try to use the source code to build the arm version.

**Comment by xuming7up** [comment]
Thanks， build ad-rss and link passed！
