### ISSUE TITLE
use rviz in docker

### ISSUE THREAD

**Issue by wangguanbei** [ApolloAuto/apollo#9643]
in docker run "rviz" will show: command not found
so how can I use rviz in docker?

**Comment by mustafaakdeniz** [comment]
Due to performance and safety matters, Apollo devs modified the ROS messaging structure to use protobuf, work without master node etc. You can use Apollo's own tools (take a look at apollo/modules/tools) for visualizing your data or modify the Rviz source code to make it work with Apollo

**Comment by wangguanbei** [comment]
> Due to performance and safety matters, Apollo devs modified the ROS messaging structure to use protobuf, work without master node etc. You can use Apollo's own tools (take a look at apollo/modules/tools) for visualizing your data or modify the Rviz source code to make it work with Apollo

so 3 ways to go:
1.take a look at apollo/modules/tools and it maybe meetmy needs
2.modify rviz source code(sorry i can't make it)
3.install ROS indigo at docker's outside, but can ROS runs well from inside to outside? I see the related closed issue #4892 ,but the method in it is not so clear to me, could I get an official instrcution of it?

**Comment by wangguanbei** [comment]
now I install ROS at docker's outside, when I run ` rostopic echo /apollo/sensor/gnss/best_pose` inside docker, it's OK, when I run it outside, it report `ERROR: Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?`
Does that mean, the connect is ok but the msg need to be built OUTSIDE? If so, how to built?

**Comment by wangguanbei** [comment]
after test, I'm sure that there is no connect between docker's inside and outside, so gow to solve this problem?

**Comment by XinrRunChao** [comment]
> now I install ROS at docker's outside, when I run ` rostopic echo /apollo/sensor/gnss/best_pose` inside docker, it's OK, when I run it outside, it report `ERROR: Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?`
> Does that mean, the connect is ok but the msg need to be built OUTSIDE? If so, how to built?

Do you sovle it ? I meet the same problem

**Comment by wangguanbei** [comment]
> > now I install ROS at docker's outside, when I run ` rostopic echo /apollo/sensor/gnss/best_pose` inside docker, it's OK, when I run it outside, it report `ERROR: Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?`
> > Does that mean, the connect is ok but the msg need to be built OUTSIDE? If so, how to built?
> 
> Do you sovle it ? I meet the same problem

This is because that we don't have head-files of apollo-unique-msgs outside of docker, maybe need to send ourselves's msgs by modify the source code of apollo, like a transfer station.

**Comment by XinrRunChao** [comment]
> > > now I install ROS at docker's outside, when I run ` rostopic echo /apollo/sensor/gnss/best_pose` inside docker, it's OK, when I run it outside, it report `ERROR: Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?`
> > > Does that mean, the connect is ok but the msg need to be built OUTSIDE? If so, how to built?
> > 
> > 
> > Do you sovle it ? I meet the same problem
> 
> This is because that we don't have head-files of apollo-unique-msgs outside of docker, maybe need to send ourselves's msgs by modify the source code of apollo, like a transfer station.

Thank you for your reply. But in the docker, we can use "rostopic echo" to print message in the screen, as same as the "rostopic", why the result is different? The transfer station you said is always achieved?  What is the head-files, I don't understand

**Comment by wangguanbei** [comment]
> > > > now I install ROS at docker's outside, when I run ` rostopic echo /apollo/sensor/gnss/best_pose` inside docker, it's OK, when I run it outside, it report `ERROR: Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?`
> > > > Does that mean, the connect is ok but the msg need to be built OUTSIDE? If so, how to built?
> > > 
> > > 
> > > Do you sovle it ? I meet the same problem
> > 
> > 
> > This is because that we don't have head-files of apollo-unique-msgs outside of docker, maybe need to send ourselves's msgs by modify the source code of apollo, like a transfer station.
> 
> Thank you for your reply. But in the docker, we can use "rostopic echo" to print message in the screen, as same as the "rostopic", why the result is different? The transfer station you said is always achieved? What is the head-files, I don't understand

Head-files means ".h"files, while use customized rosmsg, we will need it, just like what apollo does. In docker, it can find the head-files but outside it cannot, the reason is not clear but the result is just this.

**Comment by XinrRunChao** [comment]
> > > > > now I install ROS at docker's outside, when I run ` rostopic echo /apollo/sensor/gnss/best_pose` inside docker, it's OK, when I run it outside, it report `ERROR: Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?`
> > > > > Does that mean, the connect is ok but the msg need to be built OUTSIDE? If so, how to built?
> > > > 
> > > > 
> > > > Do you sovle it ? I meet the same problem
> > > 
> > > 
> > > This is because that we don't have head-files of apollo-unique-msgs outside of docker, maybe need to send ourselves's msgs by modify the source code of apollo, like a transfer station.
> > 
> > 
> > Thank you for your reply. But in the docker, we can use "rostopic echo" to print message in the screen, as same as the "rostopic", why the result is different? The transfer station you said is always achieved? What is the head-files, I don't understand
> 
> Head-files means ".h"files, while use customized rosmsg, we will need it, just like what apollo does. In docker, it can find the head-files but outside it cannot, the reason is not clear but the result is just this.

"*.pb.h"? Because of the message inside docker is the type of probobuf? Do you achieve the message between inside docker and outside docker about the topic, like "/apollo/sensor/gnss/best_pose"

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
