### ISSUE TITLE
[Planning]planning module change scenario use  finite state machine？

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#9657]
OS Platform and Distribution 16.04
Apollo version 3.5
About module :planning
Dear apollo developer,

- i have a question,in apollo 3.5 we can find that planning consist of  some scenario ,such as lane follow, overtaking,sidepass.....,
when we need to change scenario,such as from lane follow to overtaking,we use some decision to judge when to change scenario,
       from the apollo readme.txt documents, i can find that apollo use finite state machine to manage planning module scenario change, about  base on rules planning method, if have a Finite State Machine maybe  the planning  framework is very concise.
       but in the code i can't find some information,
       if someone know this question,tell me .
       thanks a lot.

**Comment by jmtao** [comment]
@freeclouds we manage scenario switches here: [ScenarioManager::ScenarioDispatch()](https://github.com/ApolloAuto/apollo/blob/master/modules/planning/scenarios/scenario_manager.cc#L697)
