### ISSUE TITLE
Build Error: C++ compilation of rule '@com_github_grpc_grpc//:grpc_plugin_support' failed (Exit 1)

### ISSUE THREAD

**Issue by ShepelIlya** [ApolloAuto/apollo#9666]
**Describe the bug**
There is a build error while building *grpc_plugin_support*.

**To Reproduce**
1.  Run ./apollo.sh build

**Expected behavior**
Build succeeded

**Screenshots**
![Screenshot from 2019-09-12 18-05-00](https://user-images.githubusercontent.com/11298885/64796152-f0470c00-d587-11e9-8785-e7002b62bd87.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Apollo: [e2f94a1](https://github.com/ApolloAuto/apollo/commit/e2f94a1e9bf67ca32dd30482140873f0e65acb76)

**Comment by ShepelIlya** [comment]
After commit [f4e7d40](https://github.com/ApolloAuto/apollo/commit/f4e7d40e8744cba6b8763246edca9362e5bee4f2) this error seems to be fixed. Can i close issue now?

**Comment by natashadsouza** [comment]
Thanks @ShepelIlya for confirming. I am currently closing this issue.

**Comment by YilmazOrkun** [comment]
I had the excat same Issue and after deleting .cache/bazel folder and clean -> build Apollo again it worked.
