### ISSUE TITLE
EM planner improvements?

### ISSUE THREAD

**Issue by Ivesss** [ApolloAuto/apollo#9683]
I've been trying to look for shortcomings or disadvantages for EM planner for a while, I have studied the details and the procedures very closely, but it seems like EM planner can handle most of the cases already(DP path for static obs and DP speed for moving obs is very efficient I think). So what's the major problems for EM planner then, which area can be improved. I would be appreciated if someone can clarify the major weaknesses or improvements for me, thanks.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by jmtao** [comment]
@Ivesss there's no major problems, but there's still lots of improvements to do. we are working on that. At this point, there's not much to share. 
If you have any thoughts, can you please let us know?   Thanks for supporting Apollo.
