### ISSUE TITLE
Piecewise jerk path optimizer failed when a vehicle is moving through a sharp turn

### ISSUE THREAD

**Issue by JJRedmond** [ApolloAuto/apollo#9684]
Hi, ApolloAuto community!
Can you help me and tell how can I fix this problem?

E0915 piecewise_jerk_path_optimizer.cc:205]  piecewise jerk path optimizer failed
E0915 piecewise_jerk_problem.cc:104]  failed optimization status:	primal infeasible
E0915 path_optimizer.cc:41]  Reference Line 1_0 is not drivable after PIECEWISE_JERK_PATH_OPTIMIZER

It happened when vehicle try to execute turn like at the picture. And after the last error it doesn't move.

### System information

- Linux Ubuntu 16.04:
- Apollo installed from source:
- Apollo version 5.0:

![Screenshot from 2019-09-15 13-25-54](https://user-images.githubusercontent.com/45877502/64920162-a7c46400-d7bc-11e9-864b-1fbb14272871.png)

**Comment by HongyiSun** [comment]
The primal infeasible means the optimizer proved that it's impossible to find a solution of that problem.
Could you please trying to make sure if it is feasible for your vehicle to make that turn or say if the turning is too sharp to follow? And did you ever tried to change the vehicle params under `modules/common/data/vehicle_param.pb.txt` if you are using your own different vehicle?

**Comment by JJRedmond** [comment]
@HongyiSun, thanks for your reply, it's very helpful. 

I used "Sim control" mode with the MKZ vehicle model and it seems this turn is not feasible.
When parameters was changed under modules/calibration/data/vehicle_param.pb.txt, ADC passed this turn.

**Comment by BigBenSure** [comment]
@JJRedmond ,could you please tell me which parameter you have changed under modules/calibration/data/vehicle_param.pb.txt ?
I have encountered this problem too.
