### ISSUE TITLE
Can I use Data Pipeline Proxy service as normal user?

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [ApolloAuto/apollo#9699]
Hello.

In order to generate vehicle control calibration, Data Pipleline Proxy should be done. In the Data Pipeline Proxy page, it says that this service is provided to your partner. Does this mean that normal user cannot use this service?

Vehicle Control Calibration:
https://github.com/ApolloAuto/apollo/blob/master/docs/specs/calibration_table/control_calibration.md

Data Pipeline Proxy
https://github.com/ApolloAuto/apollo/blob/master/modules/tools/fuel_proxy/README.md

**Comment by natashadsouza** [comment]
@cyberphysicalrobotics the data pipeline is only available for certain selected partners currently, but should you have a testing vehicle ready and Apollo set up on that vehicle, I recommend reaching out to <apollopartner@baidu.com> for more information on how to leverage this service.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
