### ISSUE TITLE
How to ignore traffic light?

### ISSUE THREAD

**Issue by Kailiangdong** [ApolloAuto/apollo#9707]
I have a quick quesion. How to ignore the traffic light? disable traffic_light module. Let car ignore traffic light direct go to place I give.
I try to not select traffic light module but not works. The car will stop in front of traffic light but not move.
I use apollo 3.5 and lgsvl simulator.
Thank you in advanced.

**Comment by JJRedmond** [comment]
You can set enabled: false for rule_id: TRAFFIC_LIGHT in mosules/planning/conf/traffic_rule_config.pb.txt

**Comment by Kailiangdong** [comment]
works thank you @JJRedmond
