### ISSUE TITLE
the map scale problem in dreamview 

### ISSUE THREAD

**Issue by bianheshan** [ApolloAuto/apollo#9716]
apollo 3.0 , when i input our own map , the map showing in the dreamview is very small, our map size is 15m * 6m, so where i can change the map scale

**Comment by natashadsouza** [comment]
@bianheshan could you share some screenshots of the map? Also, which map are you currently working on?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
