### ISSUE TITLE
please send car initial position and map data

### ISSUE THREAD

**Issue by KevinWeily** [ApolloAuto/apollo#973]
after i clicked the Dreamview button as the ReadMe.txt said, it jumped to the page which has a warning: pleasing send car initial position and map data,but i don't know how to send those info

**Comment by lianglia-apollo** [comment]
The map should be already configured, if not, you can manually chose sunnyvale loop map in hmi. Then, you can play a rosbag to get car position.

**Comment by zhubao0314** [comment]
Dear lianglia-apollo,
I have set the map and vehicle in probile as you said.
But it still shows this warning.
Would you please help to check?

**Comment by zhubao0314** [comment]
Hi All,
I have resolved this issue, just run rosbag in terminal to send data.
