### ISSUE TITLE
How do I change my Lincoln MKZ to drive-by-wire?

### ISSUE THREAD

**Issue by aaronhma** [ApolloAuto/apollo#9740]
**Describe the bug**
On Apollo's Hardware Installation site, it says you need to convert your car to drive by wire, but it never said how to.

**Comment by aaronhma** [comment]
Help would be appreciated!

**Comment by natashadsouza** [comment]
@aaronhma do you have a vehicle that you are trying to customize?
I would recommend contacting AutonomousStuff to help you with your request.

**Comment by aaronhma** [comment]
@natashadsouza I have a Lincoln MKZ Hybrid 2019 vehicle.

**Comment by natashadsouza** [comment]
@aaronhma as mentioned, I would recommend reaching out to AutonomousStuff as we at Baidu only provide the software stack for autonomous driving.

**Comment by aaronhma** [comment]
@natashadsouza Sure. Thanks!
