### ISSUE TITLE
Adv_plat and ad-rss-lib require github access

### ISSUE THREAD

**Issue by davidadley** [ApolloAuto/apollo#9741]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:

Ad-rss-lib and adv_plat in WORKSPACE.in both require access to github.com in order to download the relevant source code unlike the vast majority of other third party libraries which are bundled in the docker image.

I think it’s better to take a consistent approach and bundle everything together in the docker image and is also more portable.

**Comment by xiaoxq** [comment]
Should have been fixed in master HEAD.
