### ISSUE TITLE
how to transform the ENU coordinates.

### ISSUE THREAD

**Issue by quuen** [ApolloAuto/apollo#9747]
How does Apollo calculate the coordinates of the ENU coordinates?
I just found the acquisition of latitude and longitude coordinates，but i can not know how to transform it to ENU coordinates.Could anyone tell me where the code is?

**Comment by ycool** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/localization/msf/common/util/frame_transform.cc#L25
