### ISSUE TITLE
How to launch apollo in terminal?

### ISSUE THREAD

**Issue by cclinus** [ApolloAuto/apollo#9748]
Can one launch apollo from terminal without using dreamviewer? I am using lgsvl with apollo in ubuntu, and want to automate my experiment with apollo.

Any idea? Thanks.

**Comment by alexiskovi** [comment]
@cclinus you can launch modules with `mainboard -d <dag file>`. Dag files for every mode are listed in `apollo/modules/dreamview/conf/hmi_modes/`. For example, [mkz_standard_debug](https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt)

**Comment by cclinus** [comment]
@alexiskovi Thanks. To follow up, do you know how to set destination for ego vehicle so that the car starts driving automatically on the start?
