### ISSUE TITLE
Error about executing "cyber_recorder"

### ISSUE THREAD

**Issue by zhangx1923** [ApolloAuto/apollo#9750]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:14.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:last version
after installing the Apollo, I download a bag by

python rosbag_helper.py demo_3.5.record

and then:

cyber_recorder play -f docs/demo_guide/demo_3.5.record --loop

however, the terminal shows that 
file: docs/demo_guide/demo_3.5.record, chunk_number: 3, begin_time: 1546888377338834894 (2019-01-07 14:12:57), end_time: 1546888422886740928 (2019-01-07 14:13:42), message_number: 61615
earliest_begin_time: 1546888377338834894, latest_end_time: 1546888422886740928, total_msg_num: 61615
[RTPS_MSG_OUT Error] maxMessageSize cannot be greater than sendBufferSize -> Function init
[RTPS_PARTICIPANT Error] Cannot create participant, because there is any transport -> Function createParticipant
[PARTICIPANT Error] Problem creating RTPSParticipant -> Function createParticipant
E0922 17:38:50.699831  9185 topology_manager.cc:81] [cyber_recorder] init manager failed.
Segmentation fault

Could you please help me to solve this problem?

Although I met this error, my dreamview runs successfully, and the ego-car can also run.
What's the reason?

Best,
Xin

**Comment by cicelprg** [comment]
OK,  thanks for your feedback，we have not reproduced this problem locally，could you provide core stack information. you can find the core file in  `/apollo/data/core` directory, and use `gdb` tools to get stack information.

**Comment by natashadsouza** [comment]
@CPS-zhangX would you please provide the above requested information? If you are having trouble retrieving the information, reach out to us and one of us will walk you through the process. Thanks!

**Comment by ntutangyun** [comment]
HI, @natashadsouza @quning18 I'd like to ask how to stop the recording process, started with command `cyber_recorder record -a -o 1.record`.  

I tried "Ctrl+C" directly, but after it's stopped, there are multiple segments created, 

```
-rw-r--r--  1 tangyun apollo 2152104299 Dec 13 10:52 1.record.00000 
-rw-r--r--  1 tangyun apollo  957506491 Dec 13 10:52 1.record.00001
```

the first one about 2GB in size, and second one about 900MB.

then I tried both `cyber_recorder play -f 1.record.0000` and `cyber_recorder play -f 1.record`.  Both not working with following error:

```
tangyun@in_dev_docker:/apollo/test$ cyber_recorder play -f 1.record.0000
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1213 11:03:57.826463 20864 global_data.cc:150] [cyber_recorder] host ip: 155.69.147.119
E1213 11:03:57.828828 20864 record_file_reader.cc:33] [cyber_recorder] File not exist, file: 1.record.0000
E1213 11:03:57.829345 20864 record_reader.cc:32] [cyber_recorder] Failed to open record file: 1.record.0000
earliest_begin_time: 18446744073709551615, latest_end_time: 0, total_msg_num: 0
E1213 11:03:57.830209 20864 play_task_producer.cc:176] [cyber_recorder] begin time are equal or larger than end time, begin_time_ns=18446744073709551615, end_time_ns=0
```

Any help is highly appreciated. Thank you.

**Comment by ntutangyun** [comment]
the recorded file size turned out to be too large... 
If I only record selected channels, instead of all channels, the recorded file size would be much smaller and it can be re-played later.

**Comment by Avps1** [comment]
> the recorded file size turned out to be too large...
> If I only record selected channels, instead of all channels, the recorded file size would be much smaller and it can be re-played later.

Hi ntutangyn,
May I ask you why you need to record a bag ? Do you need it for debugging? I am working with Apollo+lgsvl stack, and my goal is to debug the Perception module. Do I need to the recorded bag to debug the module?
Thanks in advance for your response.

**Comment by ntutangyun** [comment]
@Avps1 Hi, I recorded the messages to check out the actual data of all the channels in runtime. 
I'm not testing the perception module, but to debug it, I think you need to record all the input channels to the perception module (such as lidar, camera data) and the output channels of the perception module. (perception/obstacles and traffic lights.)

It'd be better if you could record the internal channels of perception module. 
But I'm not sure if that's possible.

**Comment by vogaliccb** [comment]
> HI, @natashadsouza @quning18 I'd like to ask how to stop the recording process, started with command `cyber_recorder record -a -o 1.record`.
> 
> I tried "Ctrl+C" directly, but after it's stopped, there are multiple segments created,
> 
> ```
> -rw-r--r--  1 tangyun apollo 2152104299 Dec 13 10:52 1.record.00000 
> -rw-r--r--  1 tangyun apollo  957506491 Dec 13 10:52 1.record.00001
> ```
> 
> the first one about 2GB in size, and second one about 900MB.
> 
> then I tried both `cyber_recorder play -f 1.record.0000` and `cyber_recorder play -f 1.record`. Both not working with following error:
> 
> ```
> tangyun@in_dev_docker:/apollo/test$ cyber_recorder play -f 1.record.0000
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I1213 11:03:57.826463 20864 global_data.cc:150] [cyber_recorder] host ip: 155.69.147.119
> E1213 11:03:57.828828 20864 record_file_reader.cc:33] [cyber_recorder] File not exist, file: 1.record.0000
> E1213 11:03:57.829345 20864 record_reader.cc:32] [cyber_recorder] Failed to open record file: 1.record.0000
> earliest_begin_time: 18446744073709551615, latest_end_time: 0, total_msg_num: 0
> E1213 11:03:57.830209 20864 play_task_producer.cc:176] [cyber_recorder] begin time are equal or larger than end time, begin_time_ns=18446744073709551615, end_time_ns=0
> ```
> 
> Any help is highly appreciated. Thank you.

have you solved this problem?

**Comment by ntutangyun** [comment]
the recording file seems to be corrupted.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
