### ISSUE TITLE
Record a simulation and replay it

### ISSUE THREAD

**Issue by cclinus** [ApolloAuto/apollo#9751]
How to record a simulation and replay it? Can one give me an example to do this?

Thanks.

**Comment by unacao** [comment]
By "record a simulation", do you mean our open simulation service on https://azure.apollo.auto?

**Comment by cclinus** [comment]
@unacao No, I am running simulation with lg simulator. And want to record it for later analysis. So at later time, I want to replay the simulation and see how the car moves along with simulation time.

**Comment by unacao** [comment]
if you are using cyberRT, then just use its command line tool "cyber_record" with the options of "cyber_recorder record" or "cyber_recorder play"

**Comment by cclinus** [comment]
Thanks.
