### ISSUE TITLE
help wanted join the project

### ISSUE THREAD

**Issue by thanhmaikmt** [ApolloAuto/apollo#9753]
Hello

I want to join the proejct

**Comment by natashadsouza** [comment]
@thanhmaikmt could you please elaborate? As a developer/contributor/parter?

**Comment by thanhmaikmt** [comment]
Developer.

**Comment by natashadsouza** [comment]
@thanhmaikmt if you would like to contribute to the project, you could fork and clone the repo and start looking into our code base. There is documentation on how to get started with Apollo. Let me know if you have any additional questions!
