### ISSUE TITLE
Some questions regarding the EM planner

### ISSUE THREAD

**Issue by Ivesss** [ApolloAuto/apollo#9764]
Hi all, I have two questions regarding EM planner under some situations which I hope you could clarify me.
1.  When overtaking scenario. Firstly ego is driving behind a slow car(obstacle) and have decided to overtake it, after the decision has made and the ego proceeded to execute the generated path. Now, when the ego car is at the PARALLEL position of the obstacle, the decision for ego is still overtaking, but what if the obstacle car suddenly decided to speed up, the planned ego path would collide with the obs.

2. Follow up from the first question. Here I'm assuming that when projecting obstacle trajectory onto ST map, we only treat obstacle moving at a CONSTANT speed. However, in this case how are we going to deal with dynamic changing environments, specially obstacle speed might not be constant and would change according to the change of ego speed(i.e unpredictable behavior of obstacle). 

Might be that the planner is re-planning very fast? But if in this case, still, re-planning EVERYTIME after the environment changes might not be realistic, specially dealing with the emergency scenarios mentioned above. 

Thank you very much, looking forward to for your reply.

**Comment by jmtao** [comment]
@Ivesss the planning module "re-plan" in every frame (every 100 mil sec), to deal with the changing environment.  
For the example you mentioned, if there is a speed/acceleration/heading changing point of the obstacle that would cause decision changes from OVERTAKE to YIELD, the path cross point is usually along ego car's future trajectory point and still far enough and YIELDable. If it's too close for the ego car to YIELD or STOP, that means the obstacle is mostly merging to ego car's path very aggressively or hitting ego-car on purpose.   That'll involve disengagement. 
Hope this help answer your questions.  Thanks!
