### ISSUE TITLE
How to set destination for ego vehicle from terminal or config file? 

### ISSUE THREAD

**Issue by cclinus** [ApolloAuto/apollo#9768]
How to set destination for ego vehicle without using dreamviewer?  Any commands to do it ? Or via modifying some config file to do this? I'm automating some simulation . The goal is to let the ego vehicle to drive automatically on the start, to the destination, without using dreamviewer to set the destination.

**Comment by JJRedmond** [comment]
Hi, @cclinus!

You can use 
- mock_routing_request.py under /modules/tools/mock_routing/
or 
- routing_tester.cc under /modules/routing/tools/
