### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zhubao0314** [ApolloAuto/apollo#977]
### apollo@in_dev_docker:/apollo$ bash apollo.sh build 
System check passed. Build continue ...
[WARNING] System memory [1.94G] is lower than minimum required memory size [2.0G]. Apollo build could fail.
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
ERROR: /apollo/modules/common/math/BUILD:112:1: no such package '@eigen//': Error downloading [https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz] to /home/apollo/.cache/bazel/_bazel_apollo/540135163923dd7d5820f3ee4b306b32/external/eigen/3.2.10.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//modules/common/math:euler_angles_zxy'
ERROR: Analysis of target '//modules/common/math:euler_angles_zxy_test' failed; build aborted
INFO: Elapsed time: 25.242s
FAILED: Build did NOT complete successfully (12 packages loaded)
============================
[ERROR] Build failed!
[INFO] Took 69 seconds
============================
apollo@in_dev_docker:/apollo$ 

Is there anyone facing this issue?
I think it's the problem with certification of this website for bitbuket.com.

**Comment by dr-lab** [comment]
which environment you are build on?  Mac or linux?

I got failed on Mac with following error messages:

> @in_dev_docker:/apollo$ bash apollo.sh build
> System check passed. Build continue ...
> [WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
> [INFO] Start building, please wait ...
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
> .
> [INFO] Building on x86_64...
> INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
> INFO: Analysed 1004 targets (12 packages loaded).
> INFO: Found 1004 targets...
> ERROR: /apollo/modules/dreamview/backend/simulation_world/BUILD:5:1: C++ compilation of rule '//modules/dreamview/backend/simulation_world:simulation_world_service' failed (Exit 4)
> gcc: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
> INFO: Elapsed time: 174.070s, Critical Path: 66.76s
> FAILED: Build did NOT complete successfully
> ============================
> [ERROR] Build failed!
> [INFO] Took 198 seconds
> ============================

**Comment by dr-lab** [comment]
In fact, the build is within docker image,

uname -a
Linux in_dev_docker 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

docker ps
CONTAINER ID        IMAGE                                        COMMAND             CREATED             STATUS              PORTS               NAMES
c46b45b53e27        apolloauto/apollo:dev-x86_64-20171025_1428   "/bin/bash"         14 minutes ago      Up 14 minutes                           apollo_dev

**Comment by dr-lab** [comment]
After clear the image, restart docker, and re-pull every thing. Now build Success.

/apollo$ bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
.
[INFO] Building on x86_64...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Analysed 1004 targets (12 packages loaded).
INFO: Found 1004 targets...
INFO: Elapsed time: 1395.916s, Critical Path: 113.59s
INFO: Build completed successfully, 2192 total actions
============================
[ OK ] Build passed!
[INFO] Took 1420 seconds
============================

**Comment by zhubao0314** [comment]
Dear dr-lab,
I was building on Linux (ubuntu 12.4).
And I can make sure that it was happening in docker environment.
The problem is https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz can not be downloaded since the certification is a wrong one.

**Comment by dr-lab** [comment]
thanks zhubao0314, is your build success now?

**Comment by zhubao0314** [comment]
It 's still under building, so far without any problems . If passed, I will let you know.

**Comment by zhubao0314** [comment]
Dear dr-lab,

Currently I'm facing the same issue as you.
ERROR: /apollo/modules/dreamview/backend/simulation_world/BUILD:51:1: C++ compilation of rule '//modules/dreamview/backend/simulation_world:simulation_world_updater' failed (Exit 1)

How did you resolve this one?

**Comment by dr-lab** [comment]
Hi @zhubao0314,
What I did is " clear the image, restart docker, and re-pull every thing"

I am using macOS 10.13, and this Apollo image
```
docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
c46b45b53e27 apolloauto/apollo:dev-x86_64-20171025_1428 "/bin/bash" 14 minutes ago Up 14 minutes apollo_dev
```

I did not dig deeper after build success, just guess the root cause, maybe you can have a try as bellow:

1. docker remove 'all the Apollo images'
2. pull images again, when pull images from docker, make sure they from same repo. At the failed build in my case, for some unknown reason (maybe fat finger type 'Y' step), my images are from two different repo (CN + official docker hub). 

just 2 cents, may help.

**Comment by zhubao0314** [comment]
Yeah , I have passed the building.
My network is not stable which cause such problems.
Thanks for your kindly help.
Have a good day!!
