### ISSUE TITLE
Looking for demo_multi_sensor_fusion localization data for apollo 3.5

### ISSUE THREAD

**Issue by harrycheng20** [ApolloAuto/apollo#9778]
Hi, I am following the [MSF localization instruction](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_MSF_localization_module_on_your_local_computer.md) and from the instruction it requires localization data for apollo3.5:
-"In the downloaded data, you can find a folder named apollo3.5."
However I can only found the download link for localization data of [apollo2.5](http://data.apollo.auto/help?name=sensor%20data&data_key=multisensor&data_type=1&locale=en-us&lang=en), I am wondering if you can kindly point out where I can download the localization data for apollo3.5.

**Comment by zhouyao4321** [comment]
Hi, The link to the corresponding dataset had been broken.
Temporary Solution: please contact Yao Zhou, zhouyao@baidu.com, to request the dataset.  Requests need contain the following:
    Email address and affiliation (business or school)
    Application purpose

**Comment by harrycheng20** [comment]
Thank you!

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if you have additional questions. Thanks!

**Comment by ajay1606** [comment]
@natashadsouza Could anyone please provide me a localization dataset for apollo 3.5. Eagerly looking for that. 

From,
South korea
