### ISSUE TITLE
Nvidia-smi intallation error inside docker with apollo-5.0 fork

### ISSUE THREAD

**Issue by Iqbalparvi** [ApolloAuto/apollo#9786]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
*)OS Ubuntu 16.04

- **Apollo installed from (source or binary)**:
*source 
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:
*fork apollo 5.0.0

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
*I install nvidia driver three month ago outside docker and find nvidia-smi  result like:
![nvidia](https://user-images.githubusercontent.com/47267894/65568146-05fefd00-df9c-11e9-9302-1b29317e99e2.png)
*after then Today i dont see the perception obstacles inside dreamview ,so i check inside dev_start.sh after build success (apollo-5.0 fork that i used to link with lgsvl ) ,then check the nvidia-smi here it show no driver : 
![smi](https://user-images.githubusercontent.com/47267894/65568326-b3721080-df9c-11e9-846f-617565217e95.png)
*then i go to software update manually and see the advance option in ubuntu so its seems there is new updated  version of nvidia driver available at top as nvidia 415: 
![drver](https://user-images.githubusercontent.com/47267894/65568393-f207cb00-df9c-11e9-92c1-f2caafc3b4dc.png)
my question is that can i select the nvidia-415  and apply the change then may be it easily change the nvidia-418 to 456 outside the docker ?
if so then if I used the following commands into dev before bootstrap.sh  just changing the 418.56 to 415.27 as:
 1. wget http://us.download.nvidia.com/XFree86/Linux-x86_64/418.56/NVIDIA-Linux-x86_64-418.56.run
 2. sudo bash ./NVIDIA-Linux-x86_64-418.56.run --no-x-check -a -s --no-kernel-module
I am worried as i run the same command inside dev then it give error like:
![nvidia2](https://user-images.githubusercontent.com/47267894/65568693-0dbfa100-df9e-11e9-8c1d-8449b5fad290.png)
any sugestion will be appreciated

**Comment by wanglei828** [comment]
Besides installing docker in your host machine, you also need to install nvidia-docker, which can map you gpu driver in your host machine into docker container.

**Comment by Iqbalparvi** [comment]
@wanglei828  any link or command to install nvidia docker ?
and kindly clear that "is the nvidia docker install before dev_start.sh  or after build success"

**Comment by wanglei828** [comment]
You need to install nvidia-docker before dev_start.sh. You can follow the official method: https://github.com/NVIDIA/nvidia-docker

**Comment by Iqbalparvi** [comment]
@wanglei828 thanks for quick response , I follow the link and run the commands :
Ubuntu 16.04/18.04, Debian Jessie/Stretch/Buster
# Add the package repositories
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
$ sudo systemctl restart docker
But i am confused about the Docker2 upgrade option.
I succesfully established the connection between apollo-5.0 and lgsvl but in dtreamview the perception and traffic light off automatically and the car cant move automatically ,kindly suggest possible solutions to solve this issue.
regards

**Comment by srirambadri** [comment]
@Iqbalparvi  did you manage to fix the issue? If so, could you explain how you managed to do it?
