### ISSUE TITLE
what need I do to install NVIDIA driver in apollo 3.0 in apollo kernel

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#9789]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version : 3.0

### Steps to reproduce the issue:
1. the guide recommend 375.39 ，but I see that 375.39 doesn't support 2080ti， what version driver should I use?(also support apollo real-time kernel )
2. do i need to install driver outside docker?
3. what is the step?

**Comment by storypku** [comment]
Hi @qwetqwe , we have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. It works well with latest Nvidia driver.
Please follow these guides o install low-latency/realtime kernels with Nvidia drivers.

Thank you.

**Comment by Shen-Kirren** [comment]
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: ubuntu 16.04
> * **Apollo installed from (source or binary)**: source
> * **Apollo version : 3.0
> 
> ### Steps to reproduce the issue:
> 1. the guide recommend 375.39 ，but I see that 375.39 doesn't support 2080ti， what version driver should I use?(also support apollo real-time kernel )
> 2. do i need to install driver outside docker?
> 3. what is the step?

have you solved this problem? I meet the same of installing nvidia driver for apollo kernel in a ubuntu18.04 IPC with apollo3.0.
