### ISSUE TITLE
About nvidia-driver of Apollo 5.0

### ISSUE THREAD

**Issue by Kailiangdong** [ApolloAuto/apollo#9805]
A quick question, I am confuing of that.
I saw the Apollo 5.0 of 18.04 should have nvidia-driver over  410.
What about Apollo 5.0 of 14.04 branch?  Is driver 375 still recommended? Or must also over 410 .
Thank you in advanced

**Comment by natashadsouza** [comment]
@Kailiangdong if you are working on Apollo 5.0 - Ubuntu 14.04, you do not have to use Nvidia 410+.

**Comment by Kailiangdong** [comment]
@natashadsouza Thank you
