### ISSUE TITLE
apollo-5.0 fork with lgsvl (perception modules enable automatically) 

### ISSUE THREAD

**Issue by Iqbalparvi** [ApolloAuto/apollo#9811]
Hi Apollo ;
i succesfully conect the bridge bewteen apollo and lgsvl simulator 
 but faced the following problem given in the link(post on lgsvl github  but they refer me towards apollo )
https://github.com/lgsvl/simulator/issues/377#issuecomment-534816748
kindly suggest me where i am doing the mistake ,
Regards

**Comment by alexbuyval** [comment]
Hi
First of all, you need to look at logs files in ./data/log folder after running of the perception and prediction modules. 
Second, you need to check which exactly configuration did you use for perception module. Check which sensors do you actually use, which topics and so on.

**Comment by Iqbalparvi** [comment]
@alexbuyval thanks for reply I check the log file and  there is no files like perception and traffic light in /data/log folder inside apollo ....
2.
![issue](https://user-images.githubusercontent.com/47267894/66245658-ae5a5180-e752-11e9-89c6-c331876aee1a.PNG)
can you please explain more this coment.....
3.  i check nvidia-smi after dev_start.sh  it found driver install correctly but in after dev_into.sh but it say there is  no Driver found ...: 
![no driver](https://user-images.githubusercontent.com/47267894/66246830-bcac6b80-e75a-11e9-876c-29e829dfe757.png)
I think this is the stage due to which i can see the obstacles in dreamview and the perception and traffic light turn off automatically ...so can you please tell the possible solution against this issue thanks

**Comment by alexbuyval** [comment]
@Iqbalparvi 
1. It is very strange. Maybe you disabled the logging for the perception module. Could you add --v=4 flag into corresponded perception.conf file?

2. 
a. Find a hmi mode file that you choose in the dreamviewer. For instance, if you use 'Mkz Standard Debug' the corresponded file will be [mkz_standard_debug.pb.txt](https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/conf/hmi_modes/mkz_standard_debug.pb.txt)
b. Find there the part about the perception like this:
```
cyber_modules {
  key: "Perception"
  value: {
    dag_files: "/apollo/modules/perception/production/dag/dag_streaming_perception.dag"
  }
}
```
It means that the perception module use dag_streaming_perception.dag file to run all needed nodes. So you can find here which sensors are used in your configuration.

3. It very strange too. As I know there are no any such issues with new apollo's docker container based on Ubuntu 18.04
First of all that you have the following line ```Status: Image is up to date for apolloauto/apollo:dev-18.04-x86_64-20190822_1616``` during dev_start.sh
Then check the following:
Which version of nvidia drivers do you have on host?
Which version of the docker? Type ```docker -v```
Which version of the nvidia-docker? Type ```nvidia-docker -v```

**Comment by Iqbalparvi** [comment]
@alexbuyval thanks the docker version ,then it shows like:
![nvidia docker](https://user-images.githubusercontent.com/47267894/66276938-4f781200-e8e3-11e9-9fa3-b3e7ca72198f.png)
and dreamview is looks like as :
![car cant move](https://user-images.githubusercontent.com/47267894/66276943-63237880-e8e3-11e9-97f6-0223ed3a1386.png)
the perception and traffic light trun off automatically and there is no obstacles to see ,
so whats wrong from my side here ..?
thanks

**Comment by alexbuyval** [comment]
As I can see you don't have the nvidia-docker. Since you use the newest version of docker you need to use other options  to run the docker with nvidia support (see details [here](https://github.com/NVIDIA/nvidia-docker))

Try to replace ``` -it ``` option on the ```--gpus all``` in the following line of dev_start.sh file:
```
 ${DOCKER_CMD} run -it \
```
[here](https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L321) 

After running of dev_into.sh check ```nvidia-smi``` 

Please note, as I use old version of the docker I cannot check it myself, so I am not sure that it works

**Comment by Iqbalparvi** [comment]
@alexbuyval thanks ,i  already  follow the is link to install nvidia-docker like:

Ubuntu 16.04/18.04, Debian Jessie/Stretch/Buster

# Add the package repositories
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
$ curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

$ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
$ sudo systemctl restart docker
and after changing the -it to --gpus all the error occurs at the end of dev_start like:
![111111](https://user-images.githubusercontent.com/47267894/66354779-a0eed280-e9b1-11e9-913d-5f391601a1c9.png)
whats is the mistake  here ....?
regards

**Comment by bongjoonhyun** [comment]
In my case,

sudo bash docker/script/dev_start.sh
sudo bash docker/script/dev_into.sh

solved the problem. You should type dev_start.sh before dev_into.sh.

**Comment by Iqbalparvi** [comment]
@bongjoonhyun thanks i already write dev_start.sh and dev_into .sh that not solve the issue ,
actually my issue is the automatic off of perception and traffic light modules in dreamview and i cant see the obstacles in dreamview ...is there any sugestion to solve that
thanks again

**Comment by alexbuyval** [comment]
@Iqbalparvi 
For Docker 19 you don't need to install nvidia-docker, you need just to change option.
Could you share all output from dev_start.sh? It seems you have got an error during of container start.

Also check the following command:
```
docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
```

**Comment by Iqbalparvi** [comment]
@alexbuyval  yes this is the output of docker run --gpus all nvidia/cuda:9.0-base nvidia-smi:
$ docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
Unable to find image 'nvidia/cuda:9.0-base' locally
9.0-base: Pulling from nvidia/cuda
f7277927d38a: Pull complete 
8d3eac894db4: Pull complete 
edf72af6d627: Pull complete 
3e4f86211d23: Pull complete 
d6e9603ff777: Pull complete 
9454aa7cddfc: Pull complete 
a296dc1cdef1: Pull complete 
Digest: sha256:1883759ad42016faba1e063d6d86d5875cecf21c420a5c1c20c27c41e46dae44
Status: Downloaded newer image for nvidia/cuda:9.0-base
Tue Oct  8 08:18:25 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8     6W /  N/A |    228MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
2. dev_start.sh outputs:
bash docker/scripts/dev_start.sh 
[sudo] password for iqbalparvi: 
[INFO] Start docker container based on local image : lgsvl/apollo-5.0:latest
yolo3d_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:33add717a675be26c86f817d2207c1ab1ec25694f0decb63e55f0fc3d14b1397
Status: Image is up to date for apolloauto/apollo:yolo3d_volume-x86_64-latest
docker.io/apolloauto/apollo:yolo3d_volume-x86_64-latest
44c0444ba61a34a6ad7984869e5925bdd5000921251f2e316cef096844b5a338
localization_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:d8be22d8221c784e8a29af14a23be7fc5f2164137ec24228701e6fdcb689b088
Status: Image is up to date for apolloauto/apollo:localization_volume-x86_64-latest
docker.io/apolloauto/apollo:localization_volume-x86_64-latest
944608fb86379bc070ee18155bb26f30a9984f3032ab9eb822dfb96ee680e55e
paddlepaddle_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:901f110a4f13501e074f599b2c7d636a7584d290f59ef50237a7d77e66d025fb
Status: Image is up to date for apolloauto/apollo:paddlepaddle_volume-x86_64-latest
docker.io/apolloauto/apollo:paddlepaddle_volume-x86_64-latest
d784903d1dd67af3796de833cf05749ab991cfc20cf8f917bb5e7d44eef127ef
local_third_party_volume-x86_64-latest: Pulling from apolloauto/apollo
Digest: sha256:b844c40ab0af0733ce69c38b220a8b14f752bd834f63343392ce8508b98b546b
Status: Image is up to date for apolloauto/apollo:local_third_party_volume-x86_64-latest
docker.io/apolloauto/apollo:local_third_party_volume-x86_64-latest
6908a8f4bb4de8a79dc2cd0f47a1a4133b049bfde0068b715879ed7133d84003
[INFO] Starting docker container "apollo_dev_iqbalparvi" ...
++ local_volumes
++ volumes='-v /home/iqbalparvi/apollo-5.0/apollo-5.0:/apollo              -v /home/iqbalparvi/.cache:/home/iqbalparvi/.cache'
++ case "$(uname -s)" in
+++ uname -s
++ volumes='-v /home/iqbalparvi/apollo-5.0/apollo-5.0:/apollo              -v /home/iqbalparvi/.cache:/home/iqbalparvi/.cache -v /dev:/dev                                 -v /media:/media                                 -v /tmp/.X11-unix:/tmp/.X11-unix:rw                                 -v /etc/localtime:/etc/localtime:ro                                 -v /usr/src:/usr/src                                 -v /lib/modules:/lib/modules'
++ echo '-v /home/iqbalparvi/apollo-5.0/apollo-5.0:/apollo              -v /home/iqbalparvi/.cache:/home/iqbalparvi/.cache -v /dev:/dev                                 -v /media:/media                                 -v /tmp/.X11-unix:/tmp/.X11-unix:rw                                 -v /etc/localtime:/etc/localtime:ro                                 -v /usr/src:/usr/src                                 -v /lib/modules:/lib/modules'
+ nvidia-docker run -it -d --privileged --name apollo_dev_iqbalparvi --volumes-from apollo_yolo3d_volume_iqbalparvi --volumes-from apollo_localization_volume_iqbalparvi --volumes-from apollo_paddlepaddle_volume_iqbalparvi --volumes-from apollo_local_third_party_volume_iqbalparvi -e DISPLAY=:0 -e DOCKER_USER=iqbalparvi -e USER=iqbalparvi -e DOCKER_USER_ID=1000 -e DOCKER_GRP=apollo -e DOCKER_GRP_ID=1000 -e DOCKER_IMG=lgsvl/apollo-5.0:latest -e USE_GPU=1 -v /home/iqbalparvi/apollo-5.0/apollo-5.0:/apollo -v /home/iqbalparvi/.cache:/home/iqbalparvi/.cache -v /dev:/dev -v /media:/media -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /etc/localtime:/etc/localtime:ro -v /usr/src:/usr/src -v /lib/modules:/lib/modules --net host -w /apollo --add-host in_dev_docker:127.0.0.1 --add-host iqbalparvi-Nitro-AN515-52:127.0.0.1 --hostname in_dev_docker --shm-size 2G --pid=host -v /dev/null:/dev/raw1394 lgsvl/apollo-5.0:latest /bin/bash
940287db83c3b881aace34bce75098abf43c65975f4ed38bb88779f46000a4c3
+ set +x
Adding group `apollo' (GID 1000) ...
Done.
Adding user `iqbalparvi' ...
Adding new user `iqbalparvi' (1000) with group `apollo' ...
The home directory `/home/iqbalparvi' already exists.  Not copying from `/etc/skel'.
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
3.dev_into.sh
![Screenshot from 2019-10-08 19-23-09](https://user-images.githubusercontent.com/47267894/66379415-1a61e180-ea01-11e9-9791-f643a0ddc240.png)

**Comment by alexbuyval** [comment]
@Iqbalparvi 
So does nvidia-smi work in the apollo docker now?
Have you checked the perception again?

**Comment by Manoj-EK** [comment]
I have also encountered same problem as @Iqbalparvi..... I also tried all the steps said above... But couldn't find the reason... Could someone help me in this regard...

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
