### ISSUE TITLE
modules/localization/msf/local_integ/localization_lidar.h   

### ISSUE THREAD

**Issue by Aisimba-Autodriver** [ApolloAuto/apollo#9812]
在 modules/localization/msf/local_integ/localization_lidar.h 中，
#include "include/lidar_locator.h"，但是我始终找不到该文件

**Comment by luanjinlu** [comment]
if U install you apollo with docker, then this file is in your docker env. directory "/usr/local/apollo/local_integ/include/".
@Aisimba-Autodriver
