### ISSUE TITLE
Can someone explain about xml_parser and GraphCreator() which are used to create the hdmap and topo_graph

### ISSUE THREAD

**Issue by lucianzhong** [ApolloAuto/apollo#9815]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Apollo installed from (source or binary)**:
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by ycool** [comment]
GraphCreator parsed hdmap data (either xml or pb) and convert this information into node and edge for later routing computation.
