### ISSUE TITLE
Apollo 5.0 build: no such package '@boost//

### ISSUE THREAD

**Issue by warden2018** [ApolloAuto/apollo#9816]
### System information

- **OS Platform and Distribution Linux Ubuntu 18.04**:
- **Apollo installed from source**:
- **Apollo version 5.0**:

### Steps to reproduce the issue:
- **Docker dev image is: apolloauto/apollo   dev-x86_64-20190617_1100                       6b64e2b77e67        3 months ago        9.71GB**:
- **Depend on it, I build apollo 5.0 master code.**:
![build_boost](https://user-images.githubusercontent.com/48422255/65750567-45178480-e13b-11e9-8674-d4c05df16bff.png)

- **I found there is no boost folder here:**:

![boost_dir](https://user-images.githubusercontent.com/48422255/65750636-6ed0ab80-e13b-11e9-9b3c-abd4f8bff9c3.png)
orting materials (screenshots, command lines, code/script snippets):

- **So did I pull the wrong docker dev image or something wrong with something else?**:

**Comment by rockzhuang** [comment]
need to update docker image.

**Comment by warden2018** [comment]
@rockzhuang Yes, I think I downloaded the wrong docker image.  This version is perfectly working:
dev-18.04-x86_64-20190926_1332

**Comment by ycool** [comment]
You can try the latest master code. Thanks.
