### ISSUE TITLE
new vehicle 

### ISSUE THREAD

**Issue by Prj1508** [ApolloAuto/apollo#9822]
I am trying to add a new vehicle and new can card. I have followed the relevant how do docs to do so. Do I have to modify anything else in Apollo to support these changes. Where do I change the CAN signals for the new vehicle? 

I am using Apollo 3.5 on 16.04

**Comment by ycool** [comment]
https://github.com/ApolloAuto/apollo/blob/master/modules/canbus/conf/canbus_conf.pb.txt
