### ISSUE TITLE
faster approaching to StopSign

### ISSUE THREAD

**Issue by zhuzd12** [ApolloAuto/apollo#9825]
I found that the DP speed optimizer can not handle the StopSign very well, sliding for a long period of time to approach to the stop line happens frequently. 

The most straightforward approach would be building the virtual obstacle fo the stop sign without making a stop decision, which treats the stop sign equally with a real obstacle. Another way is to calculate the obstacle cost for each node considering the decisions already made including the stop decision for a stop sign. The sample code is provided below.
```c++
double DpStCost::GetObstacleCost(const StGraphPoint& st_graph_point) {
...
    if (s < s_lower) {
      // TODO(all): merge this parameter with existing parameter
      double follow_distance_s ;
      const auto& decision = obstacle->LongitudinalDecision();
      if (decision.has_stop()) {
        follow_distance_s = -decision.stop().distance_s();
      } else {
        follow_distance_s = std::max(4.0, 
          (2*init_point_.v() - obstacle->speed()) * 2.5);
      }
...
```
By the way, I thought the calculation of the following distance under normal conditions sometimes makes no sense. When a car cut in with higher speed compared with ADC, the current version of the following distance would lead to an unnecessary slowdown. An appropriate car-following distance model that considers both ego speed and obstacle speed in real-time should be applied.

**Comment by JasonZhou404** [comment]
@zhuzd12 PR #9833 could answer part of your questions. Your concern on following distance approximation is valid. Current formula is an empirical which proves to be ok with our road tests. Will make it more sophisticated in the future.  Thanks

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. @zhuzd12 thank you for your valuable suggestion on improving DP speed optimizer's STOP sign performance. We encourage you to make a pull request should you have tested a more efficient approach.

**Comment by zhuzd12** [comment]
@JasonZhou404 Thanks a lot. It seems there are multiply ways to solve the problem of faster stop sign approaching.
