### ISSUE TITLE
Prediction question about ObstaclesPrioritizer class

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#9848]
[AssignCautionLevelByEgoReferenceLine](https://github.com/ApolloAuto/apollo/blob/480778b097f9a65e209dd59133312ff921c038e9/modules/prediction/scenario/prioritization/obstacles_prioritizer.cc#L340)

what's the difference between ego_vehicle_s and ego_lane_s_ here?

**Comment by wanggujin** [comment]
By the way, what's the meaning of those new predictor and evaluator in version 5.0? What scenarios are they used for?  Can you update the README document ?
thank you !

**Comment by HongyiSun** [comment]
> [AssignCautionLevelByEgoReferenceLine](https://github.com/ApolloAuto/apollo/blob/480778b097f9a65e209dd59133312ff921c038e9/modules/prediction/scenario/prioritization/obstacles_prioritizer.cc#L340)
> 
> what's the difference between ego_vehicle_s and ego_lane_s_ here?

ego_vehicle_s is the ego vehicle position on reference line, while the ego_lane_s is the s position on current lane. Note that reference line is a set of lanes including the current lane, so the ego_vehicle_s is likely larger than the ego_lane_s.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
