### ISSUE TITLE
Apollo 5.0 with LGSVL simulator error

### ISSUE THREAD

**Issue by bongjoonhyun** [ApolloAuto/apollo#9857]
#9652 # System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source with GPU enabled
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
I'm trying to run Apollo 5.0 with LGSVL simulator.

I've followed all the necessary instructions provided by both Apollo and LGSVL.

I confirmed that the connection between Apollo and LGSVL is successful; messages are going back and forth between the two.

But when I hit to go autonomous driving mode, the ego vehicle is driving weirdly and stuck after a few seconds.

I'm suspicious this might be because of the IMU sensor errors showing at the consol.

![Screenshot 2019-10-07 17 23 09](https://user-images.githubusercontent.com/46742698/66296890-8113cc00-e929-11e9-912b-6955e216c6fb.png)

Any ideas why this is happening and how to fix this?

**Comment by AlxVoropaev** [comment]
I have the same setup and the same problem.

**Comment by rockzhuang** [comment]
Check  Module Controller tab, make sure the following modules are always on during auto-driving:
Localization, Transform, Perception, Traffic Light, Planning, Prediction, Routing, Control

If any modules are disabled, check data/log/#Module_Name#.INFO for log message, and gdb core file in foler data/core for backtrace info.

Note that an Nvidia graphic card with >8GB memory is necessary for perception module, and by default traffic light detection window view should be showing during auto driving.

**Comment by srirambadri** [comment]
@rockzhuang I followed the instuctions in the lgsvl fork and installedapollo-5.0 from source. The preception  and traffic light modules keeps turning off automatically and in the data/log folder I don t see any error messages. Do you know what could be the problem? 
![image](https://user-images.githubusercontent.com/8626656/67383441-7430e280-f58f-11e9-896a-c96f35e4a901.png)

My config is: Ubuntu 16.04 and I'm using a RTX 2080Ti GPU. As indicated in the image it's mentioned that the turing architectures aren't supported by apollo. Is it still the case?

**Comment by rockzhuang** [comment]
@srirambadri Firstly, run 'nvidia-smi' command to confirm GPU is enabled in the docker system.
"The perception and traffic light modules keeps turning off automatically" is caused by application crash, you can gdb core file to find backtrace, or debug perception/trafficlight module manually from the terminal in the docker system to find out what causes applications crash.

**Comment by srirambadri** [comment]
@rockzhuang 
![image](https://user-images.githubusercontent.com/8626656/67488909-e62d2880-f670-11e9-8b6c-41b91319a59e.png)
i think the nvidia docker uses the correct drivers installed in my system
I did ./apollo.sh test_gpu as suggested in this issue:https://github.com/ApolloAuto/apollo/issues/6916
As in the issue i get errors for the perception module as well. 

Is there a way you would test if the modules are working properly, apart from checking nvidia-smi?

**Comment by rockzhuang** [comment]
@srirambadri to debug perception module, on Module Controller tab enable all other modules except Perception, then open a new terminal:
rock@in_dev_docker:/apollo$ gdb mainboard
(gdb) r -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag

Perception module on DreamView should be enabled. Start simulator, then watch gdb.

Command for traffic light module is:
mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag

**Comment by srirambadri** [comment]
Hi,

I tried to debug using gdb and this is the output when i run the perception
module.
[image: image.png]
I found some solutions for the NVBLAS issue but what does the segmentation
fault mean in this case?

**Comment by rockzhuang** [comment]
@srirambadri the image is not showing, it's "[image: image.png]" now.

**Comment by srirambadri** [comment]
Hi,

![image](https://user-images.githubusercontent.com/8626656/67997492-a0fe8d00-fc54-11e9-925e-c9d96c75c8c2.png)

Here's the output

**Comment by rockzhuang** [comment]
It's a crash from NVidia TensorRT library, I guess the GPU is still incompatible.

**Comment by srirambadri** [comment]
@rockzhuang How do I double check if the GPU is the cause and not something else?

**Comment by DarrenWong** [comment]
@bongjoonhyun do you solve it? It seems we have a similar issue. I am using ubuntu 16.04 with GTC1070

**Comment by Avps1** [comment]
Hi. Did anybody solve this. I have the exact same issue .
My System config :  CUDA Version: 10.1 
nvidia Driver Version: 435.21  
GPU : RTX 2080
Ubuntu 18.04

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
