### ISSUE TITLE
question about the idea of relative map

### ISSUE THREAD

**Issue by justCallMeRong** [ApolloAuto/apollo#9865]
### System information

- **Ubuntu 14.04**:
- **Apollo installed from source**:
- **Apollo version 2.5**:

- **I want to know if the idea of relative map is proposed by Baidu. I didn't find other literatures about this idea. Where did the idea come from? Can you offer me some references, please? Thank you very much.**:

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
