### ISSUE TITLE
apollo/modules/map/hdmap/adapter/xml_parser/roads_xml_parser.cc

### ISSUE THREAD

**Issue by lucianzhong** [ApolloAuto/apollo#9879]
namespace {
bool IsRoadBelongToJunction(const std::string& road_id) {
  CHECK(!road_id.empty());
  return road_id != "-1";
}
}  // namespace

If my understanding is right,Change road_id to junction_id can make it is easier to understand

namespace {
// ID of the junction to which the road belongs as a path (= -1 for none)
bool IsRoadBelongToJunction(const std::string& junction_id_) {
  CHECK(!junction_id_.empty());
  return junction_id_ != "-1";
}
}  // namespace

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
