### ISSUE TITLE
Cannot pull docker images: unauthorized: authentication required

### ISSUE THREAD

**Issue by torstendemke** [ApolloAuto/apollo#9880]
cloned apollo.git from 7th oct 2019; branch: master
just executing:
bash docker/scripts/dev_start.sh

and get:
...
cdd75cbff5bf: Waiting 
7be566be84ac: Waiting 
48f2c4ff9e67: Waiting 
unauthorized: authentication required
[ERROR] Failed to pull docker image.

**Comment by ycool** [comment]
try again with the latest master. Thanks.
