### ISSUE TITLE
[planning]about openspace part question

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#9893]
- OS Platform ubuntu 16.04
- Apollo version : apollo 5.0
hi apollo developer,
    when i read the openspace code,i fond that this part code is very complete,in the pull over seanserio have many detail,i just read the relate paper about hydr A* and openspace describe in the apollo  github and source code,i don't have enough documents to help understand,is there have some detail docments such as openspace code frame? 
    thanks very much!

**Comment by Capri2014** [comment]
Two paper just submitted and would soon be available to public, thanks for your interest and stay tuned!
