### ISSUE TITLE
Does NCutSegmentation too slow?

### ISSUE THREAD

**Issue by tornadomeet** [ApolloAuto/apollo#9897]
### System information

- Linux Ubuntu 16.04:
- Apollo installed from source
- Apollo version 5.0

If choose ```NCutSegmentation``` for segmentation, the configure of ncut is the default, and not use hd_map for ori filter, only filter ground points. then  the time for segmentation takes about **3s~10min**, using ```apollo/modules/perception/lidar/tools/offline_lidar_obstacle_perception.cc``` for test.

i profile it and found the most consuming-time is https://github.com/ApolloAuto/apollo/blob/master/modules/perception/lidar/lib/segmentation/ncut/ncut.cc#L341, because it may iterate cut many times during one partition.

Is this normal? @xiaoxq  thanks.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
