### ISSUE TITLE
Is it a fully open source auto driving software?

### ISSUE THREAD

**Issue by codefordead** [ApolloAuto/apollo#99]
I found that a lot of functions are missing?

Such as we don't know how the perceptionobstacles process inside?
How to get localization through images? Is it same as some SLAM methods? 

Thanks very much.

**Comment by startcode** [comment]
Thanks for your interest in Apollo.
From the [Quit Start Guide](https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md)
> Apollo 1.0, also referred to as the Automatic GPS Waypoint Following, works in an enclosed venue such as a test track or parking lot. It accurately replays a trajectory and the speed of that trajectory that a human driver has traveled in an enclosed, flat area on solid ground.
> At this stage of development, Apollo 1.0 cannot perceive obstacles in close proximity, drive on public roads, or drive in areas without GPS signals.

The future road map is disclosed in the Apollo Website http://apollo.auto/
