### ISSUE TITLE
[build error]about build error

### ISSUE THREAD

**Issue by freeclouds** [ApolloAuto/apollo#9902]
- OS Platform and Distribution (Linux Ubuntu 16.04)
- Apollo version master:
Dear apollo developer,
          i have apollo 3.5 docker enviroment in my computer,i want use apollo master code,so i pull new images,and then into new docker ,it occuer build failed.now into 3.5 docker and master docker all of them can't build pass.
          error information as follow,is there apollo 3.5 and master use different libary?
540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/BUILD:388:1: C++ compilation of rule '@com_github_grpc_grpc//:grpc_plugin_support' failed (Exit 1).
In file included from external/com_github_grpc_grpc/src/compiler/php_generator.cc:24:0:
external/com_github_grpc_grpc/src/compiler/php_generator_helpers.h: In function 'grpc::string grpc_php_generator::GetPHPServiceFilename(const FileDescriptor*, const ServiceDescriptor*, const string&)':
external/com_github_grpc_grpc/src/compiler/php_generator_helpers.h:51:23: error: 'const class google::protobuf::FileOptions' has no member named 'has_php_namespace'
   if (file->options().has_php_namespace()) {
                       ^
external/com_github_grpc_grpc/src/compiler/php_generator_helpers.h:52:39: error: 'const class google::protobuf::FileOptions' has no member named 'php_namespace'
     oss << ReplaceAll(file->options().php_namespace(), "\\", "/");
                                       ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: At global scope:
external/com_github_grpc_grpc/src/compiler/php_generator.cc:26:40: error: 'google::protobuf::compiler::php::GeneratedClassName' has not been declared
 using google::protobuf::compiler::php::GeneratedClassName;
                                        ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: In function 'grpc::string grpc_php_generator::{anonymous}::PackageName(const FileDescriptor*)':
external/com_github_grpc_grpc/src/compiler/php_generator.cc:49:23: error: 'const class google::protobuf::FileOptions' has no member named 'has_php_namespace'
   if (file->options().has_php_namespace()) {
                       ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc:50:28: error: 'const class google::protobuf::FileOptions' has no member named 'php_namespace'
     return file->options().php_namespace();
                            ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: In function 'void grpc_php_generator::{anonymous}::PrintMethod(const MethodDescriptor*, grpc::protobuf::io::Printer*)':
external/com_github_grpc_grpc/src/compiler/php_generator.cc:74:58: error: 'GeneratedClassName' was not declared in this scope
       MessageIdentifierName(GeneratedClassName(input_type), input_type->file());
                                                          ^
external/com_github_grpc_grpc/src/compiler/php_generator.cc: In function 'grpc::string grpc_php_generator::{anonymous}::PackageName(const FileDescriptor*)':
external/com_github_grpc_grpc/src/compiler/php_generator.cc:54:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: (10-11 08:00:05.333) Elapsed time: 59.325s, Critical Path: 35.39s
================ Top noisy files during this compile ================
#1: modules/planning/math/finite_element_qp/fem_1d_qp_problem.cc with 1 warnings
#2: external/cuda/include/device_functions.h with 1 warnings
#3: external/com_github_grpc_grpc/src/compiler/php_generator.cc with 1 warnings
To expose warnings by file, please run:
./apollo.sh clean; ./apollo.sh build | grep ": warning: " | grep <file>
======================================================================

**Comment by xiaoxq** [comment]
Bazel has a cache system to reduce compiling time, but when you jump between versions it will cause problem.
Please remove `~/.cache/bazel` on HOST, and try again.

**Comment by freeclouds** [comment]
thanks your reply @xiaoxq, i have use ./apollo.sh clean to try clean the build bazel bin information,i think  that ./apollo clean can delete the compling results ,but it does't work.you said remove ~/.cache/bazel how to do it?

**Comment by xiaoxq** [comment]
On HOST machine, `rm -fr ~/.cache/bazel`.

**Comment by freeclouds** [comment]
thank you very much @xiaoxq , i have try.

**Comment by freeclouds** [comment]
@xiaoxq ,it's work,thanks!

**Comment by BigBenSure** [comment]
Hi? I have encountered this problem too. In my HOST, I have `/apollo/.cache/bazel`, `~/.cache/bazel`,two folders.I deleate both of them, but it doesn't work. How to check my docker containers? I don't know whether I need  to install protobuf 2 or not? @xiaoxq  Thanks!

**Comment by BigBenSure** [comment]
I try to `find -name "protobuf"`,result is:
```bash
./.cache/bazel/install/b2a7c13db48de65da851bda44622b261/_embedded_binaries/embedded_tools/src/main/protobuf
./.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/third_party/protobuf
./.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/third_party/nanopb/generator/proto/google/protobuf
./.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/examples/ruby/pubsub/google/protobuf
./.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/com_github_grpc_grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb/v1/google/protobuf
```
I `cd` in them, I can't find descriptor.ph.h,which is `if (file->options().has_php_namespace()) {` `has_php_namespace` declared in. Is it a bug? @xiaoxq
