### ISSUE TITLE
Build With -Werror

### ISSUE THREAD

**Issue by Fla3inH0tCheet0s** [ApolloAuto/apollo#9905]
**Is your feature request related to a problem? Please describe.**
It would be easier to spot new warnings, if there weren't warnings already in the build. There's already some warnings treated as errors in `tools/bazel.rc`. Warnings are useful.

There's not too many warnings with `./apollo.sh build`. It's just about deprecated calls in avcodec.h.

There are quite a few warnings in `./apollo.sh build_opt`. For example,
```
./modules/bridge/common/bridge_header_item.h:99:51: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
```
In addition there are a lot of warnings from using `DCHECK_NOTNULL`. Finally, there are a few warnings about potentially reading from uninitialized memory, which could cause undefined behavior.

**Describe the solution you'd like**
Add `build --copt="-Werror"` to tools/bazel.rc and add a `./apollo.sh build_opt` build to team city. The optimized build has more warnings. Also, CI will ensure that no new warnings pop up.

**Comment by storypku** [comment]
Good suggestion! Currently on the `master` branch, the most common warnings are deprecation warnings, third_party warnings themselves, and using deprecated third_party APIs from Apollo.
