### ISSUE TITLE
关于阿波罗r.1.0.0 构建成功，但localhost:8888 不能正确显示回放的问题

### ISSUE THREAD

**Issue by qpc001** [ApolloAuto/apollo#9907]
1、确保从github上正确pull 以及 checkout 到r.1.0.0版本
2、手动安装docker-ce ， 对储存image的路径进行了修改
3、能正确启动container
4、可以启动hmi.sh，并进入localhost:8887
` msi@in_dev_docker:/apollo$ bash scripts/hmi.sh 
Start roscore...
HMI ros node service running at localhost:8887
HMI running at http://localhost:8887
`
5、按照r.1.0.0的指南进行，在localhost:8887页面上启动dreamview
6、进入dreamview页面，发现只有 仪表盘，并没有 地图以及车辆模型，
    F12打开页面控制台，提示如下：

> app.bundle.js:39 WebSocket connection to ws://localhost:8889/ failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

>app.bundle.js:39 WebSocket connection to ws://localhost:8889/ failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by xiaoxiaosanyuan** [comment]
请问您的问题解决了吗？我现在也是这个问题，一切顺利，但是只有仪表盘没有车

**Comment by qpc001** [comment]
已经解决了。
1、需要执行 rosbag play -l ./docs/demo_guide/demo.bag ，才会显示车辆和地图模型
2、如果发现并没有正确开始回放，请检查 apollo/third_party/ 目录下是否有名为“ros”的文件夹， 以及该文件夹是否正确链接到 “apollo/third_party/ros_x86_64"文件夹

我的问题是由于机器本身已经安装了一个版本的ros，与apollo自带的ros发生冲突了，。冲突的原因是在启动docker容器时（即运行 bash  docker/script/dev_into.sh)，该脚本会运行一次 source ~/.bashrc ，所以请检查~/.bashrc， 尽量保持原系统ubuntu18.04 刚安装完成时的~/.bashrc 为最佳。
