### ISSUE TITLE
Log description mistake.

### ISSUE THREAD

**Issue by Chuck-Yu** [ApolloAuto/apollo#9913]
**Describe the bug**
`apollo/modules/perception/map/hdmap/hdmap_input.cc:211,212`
I guess this debug log supposes to output the "Right road_boundary downsample size" rather than the total size of left and right.

**Screenshots**
![image](https://user-images.githubusercontent.com/32628167/66743495-9dc17e00-eeac-11e9-8b33-9604c9ef401d.png)

**Comment by natashadsouza** [comment]
@Chuck-Yu we appreciate you sharing the bug with us. Please make a pull request to submit the change and the team will review it.

**Comment by Chuck-Yu** [comment]
#9950

**Comment by natashadsouza** [comment]
We really appreciate your contribution! Closing this issue as you have submitted a fix which has been approved!
