### ISSUE TITLE
apollo 5.0 need to install apollo kernel?

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#9925]
## System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04):  16.04
- **Apollo installed from (source or binary): source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 5.0
As I see, Cyber in apollo 3.5 and 5.0 can realize realtime task schedule, Do I need to install apollo kernel in apollo 3.5 and 5.0？

**Comment by ctwfei** [comment]
Hi qwetqwe,
It is strongly recommended to install the [Apollo Kernel ](https://github.com/ApolloAuto/apollo-kernel), which provides the necessary kernel level support to run Apollo software stack.

**Comment by storypku** [comment]
Hi all, we have updated Low-Latency / Realtime Kernel Installation Guide 
([English](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md) , [Chinese](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel_cn.md)) for Ubuntu 18.04 now. Please follow these docs to install PREEMPT/PREEMPT_RT kernels for Apollo. 

Thank you.
