### ISSUE TITLE
Receiving gnss message outside of docker

### ISSUE THREAD

**Issue by tonayw** [ApolloAuto/apollo#9926]
Hi all.
I was trying to run another algorithm outside of docker with gps data collected with Apollo modules. I was using the ”rostopic  echo” command to test if I can receive messages outside of docker. However in the outside-docker terminal, I always get the error message “Cannot load message class for [pb_msgs/GnssBestPose]. Are your messages built?”. My understanding is that Apollo uses the protobuf type message so it cannot be recognized outside the docker. I don’t know if my understanding is correct and I have no clue about how to fix it. Any suggestions would be helpful! Thanks!

**Comment by natashadsouza** [comment]
@tonayw what version of Apollo are you currently working on?

**Comment by tonayw** [comment]
Forgot to mention it. I’m running a 3.0 version.

**Comment by ctwfei** [comment]
Hi tonayw,
Please refer to [the similar issue](https://github.com/ApolloAuto/apollo/issues/7995)
