### ISSUE TITLE
Apollo, building the Dev docker container: build failed. Missing plat-sw.3.0.0.1?

### ISSUE THREAD

**Issue by arappazzo** [ApolloAuto/apollo#9927]
### System information

- **OS: Ubuntu 18.04.2 LTS**:
- **Apollo cloned but not yet installed (trying to build the docker container)**:
- **Apollo version: unclear at the moment**:

### Steps to reproduce the issue:
- **Install docker. See here for steps: https://docs.docker.com/install/linux/docker-ce/ubuntu/**
- **Get started with Apollo software installation. See here: https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md**
- **Before the title _Support a new Vehicle in DreamView_ the guide requires building the Dev docker environment. Go here: https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md#build_release**
- **Start the container by typing: _bash docker/scripts/dev_start.sh_**
- **Get into the container by typing: _bash docker/scripts/dev_into.sh_**
- **Build modules by typing: _bash apollo.sh build_**

As I perform the last step, the following screenshot appears for a few seconds

![Pict01](https://user-images.githubusercontent.com/56590646/66907510-bb582a00-f009-11e9-9141-d32e4609f65b.png)

And after a few seconds the build fails and this screenshot appears
![Pict02](https://user-images.githubusercontent.com/56590646/66907514-bb582a00-f009-11e9-84e0-31b4579793e4.png)

It seems like the system is trying to download/clone a package (plat-sw.3.0.0.1.zip) that's no longer in the expected path.
Where can this package be found?
Once I download the package, how do I link it to Apollo?
Thanks in advance!

**Comment by natashadsouza** [comment]
@arappazzo are you building out the latest master branch?

**Comment by arappazzo** [comment]
@natashadsouza I think so. I followed the instructions as in https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_software_installation_guide.md and checked out the master branch.
As per the first step, I didn't really clone the repository by using the suggested command, rather I downloaded it directly from here https://github.com/ApolloAuto/apollo/ and then checked out the master branch due to temporary problems with the ssh keys. Should it make any difference?

**Comment by arappazzo** [comment]
[Dev_start_output.txt](https://github.com/ApolloAuto/apollo/files/3754457/Dev_start_output.txt)
[Apollo_build_Output.txt](https://github.com/ApolloAuto/apollo/files/3754461/Apollo_build_Output.txt)

Dev_start_output.txt: output log file of the command _bash docker/scripts/dev_start.sh_
Apollo_build_output.txt: output log file of the command _bash apollo.sh build_cpu_ (after typing _bash docker/scripts/dev_into.sh_ )

**Comment by arappazzo** [comment]
By the way, after installing the nvidia driver I cannot even get to the point of launching _bash apollo.sh build_cpu_, since _bash docker/scripts/dev_into.sh_ returns an error (container not running and no way to get it run).
Unsure if I'm doing things right.

**Comment by con00** [comment]
hi  arappazzo, I am a beginner here and I am trying to get around and install apollo. I also have experienced your kind of problem and do not know how to push further with the docker. Did you get help and can you help me with step to achieve this installation and having apollo to run in my system?

Please, any help from anyone is appreciated in advance.

Thank you in advance.

**Comment by arappazzo** [comment]
The following is a guideline I've created myself for installing Apollo. It goes up to the point I've reached so far.
[Full_Installation_Document.pdf](https://github.com/ApolloAuto/apollo/files/3868034/Full_Installation_Document.pdf)

Follow the docker installation part. Then try to build the offline demo (I could make it work).
Finally, try to build the actual release (online demo).

This is the point I get stuck at. If you get there, please refer to #10159 and the issue that have been referred to in that issue.
There seems to be some trouble with bazel.

Feel free to ask, provide further logs and let me know up to where you get (tell me if you get farther...).

**Comment by con00** [comment]
@arappazzo 
Thank you for the steps outlined. I will try them out and will keep you updated as I go on with it.
I do appreciate.

**Comment by natashadsouza** [comment]
@arappazzo @con00 please rebuild Apollo using [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md) instead and let me know if you are still seeing a container issue.

**Comment by arappazzo** [comment]
> @arappazzo @con00 please rebuild Apollo using [this document](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md) instead and let me know if you are still seeing a container issue.

@natashadsouza @con00 
Please refer to issue #10159: I found out I had to do some changes in the settings before proceeding.

In any case, as suggested by @natashadsouza I've just tried to build apollo as mentioned [here](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_build_and_release.md), which actually exposes the steps I've performed so far.

What I've tried this time was to build apollo by limiting the cpu

`bash apollo.sh build --local_resources 2048,1.0,1.0`

The result is once again build failed (see attached log: log_tmp8.txt).
[log_tmp8.txt](https://github.com/ApolloAuto/apollo/files/3873608/log_tmp8.txt)

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
