### ISSUE TITLE
PaddlePaddle Docker Image

### ISSUE THREAD

**Issue by christian-lanius** [ApolloAuto/apollo#9940]
Hi,
I am currently working on getting Apollo to run on our setup. To do this, I would like to build as much as possible myself, including the docker container. I have seen that  the PaddlePaddle library is included into the container as a mounted volume from a different container. Unfortunately, I can not find any source for how to build this container. The dockerfile on dockerhub (https://hub.docker.com/layers/apolloauto/apollo/paddlepaddle_volume-x86_64-2.0.0/images/sha256-5c081e32d92c930df394c9e0f9d934fe613c6fbba92ab38d70ee8054bc380f5d) also does not contain any meaningful information on how to build PaddlePaddle from source.

Can you share with us more detailed information on how this dockerfile was built?

Kind regards,
Christian

**Comment by natashadsouza** [comment]
@christian-lanius please refer to https://github.com/PaddlePaddle/Paddle for a better understanding of PaddlePaddle

**Comment by christian-lanius** [comment]
That doesn't tell me which PaddlePaddle version exactly was used to build the docker image though, or with which compiler flags. As far as I can tell, the PaddlePaddle docker which is used in Apollo is not one of the official ones, but one built by the Apollo team.

**Comment by sofrony** [comment]
I have tried API get_version(), it returns  "version 0.0.0".
I have tried all major versions of official PaddlePaddle, nobody compatible.

**Comment by christian-lanius** [comment]
I got it to work (as in, the cnnseg test passed) by using version 1.5.2 
To get it to compile on ubuntu 18.04, you might have to a apply a short patch to it. I can share it on Monday, once I'm back in the office.
Looking at the cmake file for paddlepaddle, it always sets the version to 0.0.0 for some reason.

**Comment by sofrony** [comment]
I will be very appreciated, so once we have a patch we can make compatible docker-file and share it with hub.docker.com. Sounds great.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
