### ISSUE TITLE
Piecewise jerk optimizer documentation

### ISSUE THREAD

**Issue by DrumAliens** [ApolloAuto/apollo#9951]
Are there any papers or documentation relating to the maths behind the piecewise jerk optimizer ?? 

Even if this relates to an example that is not related to Apollo but just shows the principle of how it works

**Comment by lucianzhong** [comment]
@DrumAliens  Have you find anything helpful? I'm very confused after reading code.

**Comment by lucianzhong** [comment]
please refer to issues 9599

**Comment by DrumAliens** [comment]
Thanks for the link it gives me a starting point
