### ISSUE TITLE
Displaying custom planner's output alongside the default planner's output in Dreamview frontend

### ISSUE THREAD

**Issue by moizsajid** [ApolloAuto/apollo#9955]
I want to display both the default planner's output (in Turquoise color as shown below) as well as my custom planner's output (in Red color as shown below) in Dreamview. I want my output to look as shown below in the Supporting Materials section. I have not figured out how to do so. I see that there are some parameters defined for displaying different paths in the `master` branch of the repo. But I have not been able to find anything concrete for Apollo Version 3.0. It would be great if someone can tell me about the files in which I have to make the changes. 

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**: source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

### Supporting materials (screenshots, command lines, code/script snippets):
![0clip_image062](https://user-images.githubusercontent.com/5734680/67099196-c94eac00-f1bd-11e9-8a10-6118c93b7c49.png)

**Comment by moizsajid** [comment]
@vlin17 and @unacao help needed?

**Comment by unacao** [comment]
If you would like to visualize your customized planning path, the best way is to replace the current planning trajectory in the planning output topic, so that all the other modules subscribing to the planning output will receive the customized data. If you really need to add the customized path, you would need to change the dreamview backend and frontend. Backend for aggregating the new planning path points from your customized output and send it to frontend, e.g. similar to SimulationWorldService::UpdatePlanningTrajectory(). Frontend for parsing and drawing the customized path points received.

**Comment by vlin17** [comment]
More detail on top of unacao's comment:

Dreamview backend passes [path from planning_internal.proto](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/planning/proto/planning_internal.proto#L127) to frontend [here](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/dreamview/backend/simulation_world/simulation_world_service.cc#L826). You can add your custom paths [there](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/planning/proto/planning_internal.proto#L127) to avoid changes in dreamview backend. 

Dreamview frontend draws paths in [trajectory.js](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/dreamview/frontend/src/renderer/trajectory.js), which is where you can specify the properties of your paths. However, be sure paths are set as [visible](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/dreamview/frontend/src/renderer/trajectory.js#L104).

**Comment by moizsajid** [comment]
@unacao How do I subscribe to my Planning topic inside the SimulationWorldService::UpdatePlanningTrajectory() function? This function only takes in an ADCTrajectory object. Also, can you please tell me where the ADCTrajectory class is located? I was not able to find its definition inside the Planning module. Thanks!

**Comment by unacao** [comment]
ADCTrajectory is defined in this [planning proto](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/planning/proto/planning.proto#L77) . If you are reusing the topic /apollo/planning, dreamview subscribes to it [here](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/dreamview/backend/simulation_world/simulation_world_service.cc#L283) via the AdapterManager .
