### ISSUE TITLE
Providing my own point cloud data

### ISSUE THREAD

**Issue by AyushiRathore** [ApolloAuto/apollo#9958]
I want to provide my own point cloud data to apollo algorithm. Does anyone have any idea how can I do it.

System information
OS Platform and Distribution (e.g., Linux Ubuntu 14.04): Ubtuntu 14.04
Apollo installed from (source or binary): source
Apollo version (1.0, 1.5, 2.0, 2.5, 3.0): 3.5

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:

**Comment by ycool** [comment]
You can provide your point cloud data to perception config point cloud topic: e.g. /apollo/sensor/lidar128/PointCloud2
Its format is https://github.com/ApolloAuto/apollo/blob/master/modules/drivers/proto/pointcloud.proto
