### ISSUE TITLE
Apollo 3.0 Traffic light Module not starting

### ISSUE THREAD

**Issue by danielbachmanncgi** [ApolloAuto/apollo#9974]
Hello,
I am currently running apollo 3.0 with carla-simulator 0.9.6 https://github.com/carla-simulator/carla 
I am sending image data to the following apollo topics:
/apollo/sensor/camera/traffic/image_long
/apollo/sensor/camera/traffic/image_short
/apollo/sensor/camera/obstacle/front_6mm

In Dreamview Camera L and Camera S are showed green, but traffic light module seems to not starting. All other modules are starting just fine. The only log that I found is from the perception module: 

E1021 15:00:08.928474 10546 tl_preprocessor_subnode.cc:293] TLPreprocessorSubnode failed to query pose ts:31229.432291209
E1021 15:00:08.928505 10546 tl_preprocessor_subnode.cc:264] camera_selection failed to get car pose, ts:31229.432291209

But I am not sure if that is even the problem here. Has anyone an idea of what the problem could be and is there a way to see the camera output like shown here: https://github.com/ApolloAuto/apollo/blob/master/docs/specs/traffic_light.md#rectifier

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: binary
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 3.0

**Comment by danielbachmanncgi** [comment]
![Screenshot_2019-10-22 Dreamview](https://user-images.githubusercontent.com/54978334/67282580-5fdae000-f4d2-11e9-92b8-514cb610201f.png)
I just found that in Dreamview the Traffic lights are facing the wrong direction. Has that something todo with the module not working? If so how can I turn them around in the map data.

**Comment by vlin17** [comment]
We have improved the calculation of traffic light orientation in [later version of apollo](https://github.com/ApolloAuto/apollo/blob/r3.5.0/modules/dreamview/frontend/src/renderer/map.js#L233).  Please adopt new calculation in your code or hard code traffic light orientation in your [Dreamview](https://github.com/ApolloAuto/apollo/blob/r3.0.0/modules/dreamview/frontend/src/renderer/map.js#L305).

**Comment by danielbachmanncgi** [comment]
The log of the perception module says this:
`[NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[NVBLAS] Cannot open default config file 'nvblas.conf'
[NVBLAS] Config parsed
[NVBLAS] CPU Blas library need to be provided
`

**Comment by vlin17** [comment]
NVBLAS_CONFIG_FILE is Cuda related. Does your computer support GPU & Cuda? This [perception](https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_perception_module_on_your_local_computer.md) guide might be helpful.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
