### ISSUE TITLE
Prediction Bug

### ISSUE THREAD

**Issue by wanggujin** [ApolloAuto/apollo#9984]
[InteractionPredictor::CollisionWithEgoVehicleCost](https://github.com/ApolloAuto/apollo/blob/514e23a19561307513af91ad3d3fe2ab23c5a5d3/modules/prediction/predictor/interaction/interaction_predictor.cc#L313)

the while is a endless loop , how should i modify this code?

**Comment by wanggujin** [comment]
@HongyiSun 
@kechxu 
Help ! ! !
How to update the `remained_s` variable ?

**Comment by wanggujin** [comment]
@HongyiSun 
@kechxu 
How to update the `remained_s` variable ?

**Comment by daohu527** [comment]
@wanggujin The judgment condition of while is as follows
https://github.com/ApolloAuto/apollo/blob/514e23a19561307513af91ad3d3fe2ab23c5a5d3/modules/prediction/predictor/interaction/interaction_predictor.cc#L313

I don't understand where is the problem?
