### ISSUE TITLE
planning_gflag.cc:194 parament config question

### ISSUE THREAD

**Issue by BigBenSure** [ApolloAuto/apollo#9994]
apollo5master.
in file planning_gflag.cc:194: 
DEFINE_double(planning_upper_speed_limit, 31.3,
              "Maximum speed (m/s) in planning.");
31.3m/s means 112.68km/h. Is it too fast to apollo?

**Comment by jmtao** [comment]
@BigBenSure that's the upper bound.  31.3 m/s = 70 miles/hour.  the speed limit of most freeway in US are 65-75 miles/hour.

**Comment by BigBenSure** [comment]
> @BigBenSure that's the upper bound. 31.3 m/s = 70 miles/hour. the speed limit of most freeway in US are 65-75 miles/hour.

thank you!
